include::./index.adoc[]

[[v58-7-0]]
=== Hebreus, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v58-7-1]]

^<<v58-7-1,1>>^ Esse Melquisedeque era rei de Salém e também sacerdote do Deus Altíssimo. Quando Abraão regressava para casa, depois de derrotar os reis, Melquisedeque foi ao seu encontro e o abençoou.

[[v58-7-2]]

^<<v58-7-2,2>>^ Então Abraão separou a décima parte de tudo e a entregou a Melquisedeque, cujo nome significa "rei da justiça", enquanto rei de Salém quer dizer "rei da paz".

[[v58-7-3]]

^<<v58-7-3,3>>^ Não há registro de seu pai nem de sua mãe, nem de nenhum de seus antepassados, nem do começo nem do fim de sua vida. Semelhantemente ao Filho de Deus, ele permanece sacerdote para sempre.

[[v58-7-4]]

^<<v58-7-4,4>>^ Considerem, portanto, a importância de Melquisedeque. Até mesmo Abraão, o patriarca, a reconheceu ao entregar a ele um décimo do que havia conquistado na batalha.

[[v58-7-5]]

^<<v58-7-5,5>>^ A lei de Moisés exigia que os sacerdotes, os descendentes de Levi, recebessem o dízimo de seus irmãos israelitas, que também são descendentes de Abraão.

[[v58-7-6]]

^<<v58-7-6,6>>^ Melquisedeque, porém, que não era descendente de Levi, recebeu o dízimo e, em seguida, abençoou Abraão, que já havia recebido as promessas.

[[v58-7-7]]

^<<v58-7-7,7>>^ Sem dúvida, quem tem poder para abençoar é superior a quem é abençoado.

[[v58-7-8]]

^<<v58-7-8,8>>^ Os sacerdotes que recebem os dízimos são homens mortais. A respeito de Melquisedeque, no entanto, é dito que ele continua vivo.

[[v58-7-9]]

^<<v58-7-9,9>>^ Além disso, pode-se dizer que os levitas, que recebem o dízimo, também o entregaram por meio de Abraão.

[[v58-7-10]]

^<<v58-7-10,10>>^ Embora Levi ainda não tivesse nascido, a semente da qual ele veio já estava no corpo de Abraão, seu antepassado, quando Melquisedeque se encontrou com ele.

[[v58-7-11]]

^<<v58-7-11,11>>^ Portanto, se o sacerdócio de Levi, sob o qual o povo recebeu a lei, pudesse ter alcançado a perfeição, por que seria necessário estabelecer outro sacerdócio, com um sacerdote segundo a ordem de Melquisedeque, em vez da ordem de Arão?

[[v58-7-12]]

^<<v58-7-12,12>>^ E, se o sacerdócio muda, também é preciso que a lei mude.

[[v58-7-13]]

^<<v58-7-13,13>>^ Pois o sacerdote ao qual estamos nos referindo pertence a outra tribo, cujos membros nunca serviram no altar como sacerdotes.

[[v58-7-14]]

^<<v58-7-14,14>>^ De fato, como todos sabem, nosso Senhor veio da tribo de Judá, e Moisés nunca mencionou que dessa tribo viriam sacerdotes.

[[v58-7-15]]

^<<v58-7-15,15>>^ Essa mudança se torna ainda mais clara com o surgimento de outro sacerdote, semelhante a Melquisedeque,

[[v58-7-16]]

^<<v58-7-16,16>>^ o qual se tornou sacerdote não por cumprir leis e exigências humanas, mas pelo poder de uma vida indestrutível.

[[v58-7-17]]

^<<v58-7-17,17>>^ Pois a respeito dele foi dito: "Você é sacerdote para sempre, segundo a ordem de Melquisedeque".

[[v58-7-18]]

^<<v58-7-18,18>>^ Desse modo, o antigo requisito, por ser fraco e inútil, foi cancelado.

[[v58-7-19]]

^<<v58-7-19,19>>^ Pois a lei nunca tornou perfeita coisa alguma. Agora, porém, temos certeza de uma esperança superior, pela qual nos aproximamos de Deus.

[[v58-7-20]]

^<<v58-7-20,20>>^ Esse novo sistema foi instituído com um juramento solene. Os outros se tornaram sacerdotes sem esse juramento,

[[v58-7-21]]

^<<v58-7-21,21>>^ mas a respeito dele houve um juramento, pois Deus lhe disse: "O Senhor jurou e não voltará atrás: ‘Você é sacerdote para sempre’".

[[v58-7-22]]

^<<v58-7-22,22>>^ Por causa desse juramento, Jesus é aquele que garante uma aliança superior.

[[v58-7-23]]

^<<v58-7-23,23>>^ Além disso, havia muitos sacerdotes, pois a morte os impedia de continuar a desempenhar suas funções.

[[v58-7-24]]

^<<v58-7-24,24>>^ Mas, visto que ele vive para sempre, seu sacerdócio é permanente.

[[v58-7-25]]

^<<v58-7-25,25>>^ Portanto, ele é capaz de salvar de uma vez por todas aqueles que se aproximam de Deus por meio dele. Ele vive sempre para interceder em favor deles.

[[v58-7-26]]

^<<v58-7-26,26>>^ É de um Sumo Sacerdote como ele que necessitamos, pois é santo, irrepreensível, sem nenhuma mancha de pecado, separado dos pecadores e colocado no lugar de mais alta honra no céu.

[[v58-7-27]]

^<<v58-7-27,27>>^ Ele não precisa oferecer sacrifícios diariamente, ao contrário dos outros sumos sacerdotes, que os ofereciam primeiro por seus próprios pecados e depois pelos pecados do povo. Ele, porém, o fez de uma vez por todas quando ofereceu a si mesmo como sacrifício.

[[v58-7-28]]

^<<v58-7-28,28>>^ A lei nomeava sacerdotes limitados pela fraqueza humana. Mas, depois da lei, Deus nomeou com juramento seu Filho, que se tornou o Sumo Sacerdote perfeito para sempre.

'''

xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[Próximo Capítulo &#62;]