include::./index.adoc[]

[[v58-3-0]]
=== Hebreus, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v58-3-1]]

^<<v58-3-1,1>>^ Portanto, irmãos santos que participam do chamado celestial, considerem atentamente a Jesus, que declaramos ser Apóstolo e Sumo Sacerdote.

[[v58-3-2]]

^<<v58-3-2,2>>^ Pois ele foi fiel àquele que o designou, assim como Moisés serviu fielmente quando lhe foi confiada toda a casa de Deus.

[[v58-3-3]]

^<<v58-3-3,3>>^ Jesus, no entanto, é digno de muito mais honra que Moisés, assim como a pessoa que constrói uma casa merece mais elogios que a casa em si.

[[v58-3-4]]

^<<v58-3-4,4>>^ Pois toda casa tem um construtor, mas Deus é o construtor de todas as coisas.

[[v58-3-5]]

^<<v58-3-5,5>>^ Por certo, Moisés foi fiel como servo na casa de Deus, e seu trabalho ilustrou verdades que seriam mais tarde reveladas.

[[v58-3-6]]

^<<v58-3-6,6>>^ Mas Cristo, como Filho, é responsável por toda a casa de Deus; e nós somos a casa de Deus, se nos mantivermos corajosos e firmes em nossa esperança gloriosa.

[[v58-3-7]]

^<<v58-3-7,7>>^ Por isso o Espírito Santo diz: "Hoje, se ouvirem sua voz,

[[v58-3-8]]

^<<v58-3-8,8>>^ não endureçam o coração como eles fizeram na rebelião, quando me puseram à prova no deserto.

[[v58-3-9]]

^<<v58-3-9,9>>^ Ali seus antepassados me tentaram e me puseram à prova, apesar de terem visto meus feitos durante quarenta anos.

[[v58-3-10]]

^<<v58-3-10,10>>^ Por isso fiquei irado com aquela geração e disse: ‘Seu coração sempre se desvia de mim; vocês se recusam a andar em meus caminhos’.

[[v58-3-11]]

^<<v58-3-11,11>>^ Assim, jurei em minha ira: ‘Jamais entrarão em meu descanso’".

[[v58-3-12]]

^<<v58-3-12,12>>^ Portanto, irmãos, cuidem para que nenhum de vocês tenha coração perverso e incrédulo que os desvie do Deus vivo.

[[v58-3-13]]

^<<v58-3-13,13>>^ Advirtam uns aos outros todos os dias, enquanto ainda é "hoje", para que nenhum de vocês seja enganado pelo pecado e fique endurecido.

[[v58-3-14]]

^<<v58-3-14,14>>^ Porque nos tornaremos participantes de Cristo, se de fato mantivermos firme até o fim a confiança que nele depositamos no início.

[[v58-3-15]]

^<<v58-3-15,15>>^ Lembrem-se do que foi dito: "Hoje, se ouvirem sua voz, não endureçam o coração como eles fizeram na rebelião".

[[v58-3-16]]

^<<v58-3-16,16>>^ E quem foram os que se rebelaram mesmo depois de terem ouvido? Não foram aqueles que saíram do Egito conduzidos por Moisés?

[[v58-3-17]]

^<<v58-3-17,17>>^ E quem deixou Deus irado durante quarenta anos? Não foi o povo que pecou e cujos corpos ficaram no deserto?

[[v58-3-18]]

^<<v58-3-18,18>>^ E a quem Deus se dirigiu quando jurou que jamais entrariam em seu descanso? Não foi ao povo que lhe desobedeceu?

[[v58-3-19]]

^<<v58-3-19,19>>^ Vemos, portanto, que não puderam entrar no descanso por causa de sua incredulidade.

'''

xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[&#60; Capítulo Anterior] | <<v58-3-0,Topo>> | xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[Próximo Capítulo &#62;]