include::./index.adoc[]

[[v58-4-0]]
=== Hebreus, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v58-4-1]]

^<<v58-4-1,1>>^ Assim, uma vez que permanece a promessa de que entraremos no descanso de Deus, devemos ter cuidado para que nenhum de vocês pense que falhou.

[[v58-4-2]]

^<<v58-4-2,2>>^ Porque essas boas-novas também nos foram anunciadas, como a eles, mas a mensagem de nada lhes valeu, pois não a receberam com fé e não se uniram àqueles que ouviram.

[[v58-4-3]]

^<<v58-4-3,3>>^ Pois nós, os que cremos, entramos em seu descanso. Quanto aos demais, Deus disse: "Assim, jurei em minha ira: ‘Jamais entrarão em meu descanso’", embora suas obras estejam prontas desde a criação do mundo.

[[v58-4-4]]

^<<v58-4-4,4>>^ Sabemos que estão prontas por causa da passagem que menciona o sétimo dia: "No sétimo dia, Deus descansou de todo o seu trabalho".

[[v58-4-5]]

^<<v58-4-5,5>>^ Mas, em outra passagem, Deus diz: "Jamais entrarão em meu descanso".

[[v58-4-6]]

^<<v58-4-6,6>>^ Portanto, o descanso está disponível para que alguns entrem nele, mas os primeiros que ouviram essas boas-novas não entraram por causa de sua desobediência.

[[v58-4-7]]

^<<v58-4-7,7>>^ Por isso Deus estabeleceu outra ocasião para que entrem em seu descanso, e essa ocasião é "hoje". Ele anunciou isso por meio de Davi muito tempo depois, nas palavras já citadas: "Hoje, se ouvirem sua voz, não endureçam o coração".

[[v58-4-8]]

^<<v58-4-8,8>>^ Se Josué lhes tivesse dado descanso, Deus não teria falado de outro dia de descanso por vir.

[[v58-4-9]]

^<<v58-4-9,9>>^ Logo, ainda há um descanso definitivo à espera do povo de Deus.

[[v58-4-10]]

^<<v58-4-10,10>>^ Porque todos que entraram no descanso de Deus descansam de seu trabalho, como Deus o fez após a criação do mundo.

[[v58-4-11]]

^<<v58-4-11,11>>^ Portanto, esforcemo-nos para entrar nesse descanso. Mas, se desobedecermos, como no exemplo citado, cairemos.

[[v58-4-12]]

^<<v58-4-12,12>>^ Pois a palavra de Deus é viva e poderosa. É mais cortante que qualquer espada de dois gumes, penetrando entre a alma e o espírito, entre a junta e a medula, e trazendo à luz até os pensamentos e desejos mais íntimos.

[[v58-4-13]]

^<<v58-4-13,13>>^ Nada, em toda a criação, está escondido de Deus. Tudo está descoberto e exposto diante de seus olhos, e é a ele que prestamos contas.

[[v58-4-14]]

^<<v58-4-14,14>>^ Visto, portanto, que temos um grande Sumo Sacerdote que entrou no céu, Jesus, o Filho de Deus, apeguemo-nos firmemente àquilo em que cremos.

[[v58-4-15]]

^<<v58-4-15,15>>^ Nosso Sumo Sacerdote entende nossas fraquezas, pois enfrentou as mesmas tentações que nós, mas nunca pecou.

[[v58-4-16]]

^<<v58-4-16,16>>^ Assim, aproximemo-nos com toda confiança do trono da graça, onde receberemos misericórdia e encontraremos graça para nos ajudar quando for preciso.

'''

xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[&#60; Capítulo Anterior] | <<v58-4-0,Topo>> | xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[Próximo Capítulo &#62;]