include::./index.adoc[]

[[v58-12-0]]
=== Hebreus, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v58-12-1]]

^<<v58-12-1,1>>^ Portanto, uma vez que estamos rodeados de tão grande multidão de testemunhas, livremo-nos de todo peso que nos torna vagarosos e do pecado que nos atrapalha, e corramos com perseverança a corrida que foi posta diante de nós.

[[v58-12-2]]

^<<v58-12-2,2>>^ Mantenhamos o olhar firme em Jesus, o líder e aperfeiçoador de nossa fé. Por causa da alegria que o esperava, ele suportou a cruz sem se importar com a vergonha. Agora ele está sentado no lugar de honra à direita do trono de Deus.

[[v58-12-3]]

^<<v58-12-3,3>>^ Pensem em toda a hostilidade que ele suportou dos pecadores; desse modo, vocês não ficarão cansados nem desanimados.

[[v58-12-4]]

^<<v58-12-4,4>>^ Afinal, ainda não chegaram a arriscar a vida na luta contra o pecado.

[[v58-12-5]]

^<<v58-12-5,5>>^ Acaso vocês se esqueceram das palavras de ânimo que Deus lhes dirigiu como filhos dele? Ele disse: "Meu filho, não despreze a disciplina do Senhor; não desanime quando ele o corrigir.

[[v58-12-6]]

^<<v58-12-6,6>>^ Pois o Senhor disciplina quem ele ama e castiga todo aquele que aceita como filho".

[[v58-12-7]]

^<<v58-12-7,7>>^ Enquanto suportam essa disciplina de Deus, lembrem-se de que ele os trata como filhos. Quem já ouviu falar de um filho que nunca foi disciplinado pelo pai?

[[v58-12-8]]

^<<v58-12-8,8>>^ Se Deus não os disciplina como faz com todos os seus filhos, significa que vocês não são filhos de verdade, mas ilegítimos.

[[v58-12-9]]

^<<v58-12-9,9>>^ Uma vez que respeitávamos nossos pais terrenos que nos disciplinavam, não devemos nos submeter ainda mais à disciplina do Pai de nosso espírito e, assim, obter vida?

[[v58-12-10]]

^<<v58-12-10,10>>^ Pois nossos pais nos disciplinaram por alguns anos como julgaram melhor, mas a disciplina de Deus é sempre para o nosso bem, a fim de que participemos de sua santidade.

[[v58-12-11]]

^<<v58-12-11,11>>^ Nenhuma disciplina é agradável no momento em que é aplicada; ao contrário, é dolorosa. Mais tarde, porém, produz uma colheita de vida justa e de paz para os que assim são corrigidos.

[[v58-12-12]]

^<<v58-12-12,12>>^ Portanto, revigorem suas mãos cansadas e seus joelhos enfraquecidos.

[[v58-12-13]]

^<<v58-12-13,13>>^ Façam caminhos retos para seus pés a fim de que os mancos não caiam, mas sejam fortalecidos.

[[v58-12-14]]

^<<v58-12-14,14>>^ Esforcem-se para viver em paz com todos e procurem ter uma vida santa, sem a qual ninguém verá o Senhor.

[[v58-12-15]]

^<<v58-12-15,15>>^ Cuidem uns dos outros para que nenhum de vocês deixe de experimentar a graça de Deus. Fiquem atentos para que não brote nenhuma raiz venenosa de amargura que cause perturbação, contaminando muitos.

[[v58-12-16]]

^<<v58-12-16,16>>^ Vigiem para que ninguém seja imoral ou profano, como Esaú, que trocou seus direitos como filho mais velho por uma simples refeição.

[[v58-12-17]]

^<<v58-12-17,17>>^ Como vocês sabem, mais tarde, quando ele quis a bênção do pai, foi rejeitado. Era tarde para que houvesse arrependimento, embora ele tivesse implorado com lágrimas.

[[v58-12-18]]

^<<v58-12-18,18>>^ Vocês não chegaram a um monte que se pode tocar, a um lugar de fogo ardente, escuridão, trevas e vendaval,

[[v58-12-19]]

^<<v58-12-19,19>>^ ao toque da trombeta e à voz tão terrível que aqueles que a ouviram suplicaram que nada mais lhes fosse dito,

[[v58-12-20]]

^<<v58-12-20,20>>^ pois não podiam suportar a ordem que recebiam: "Se até mesmo um animal tocar no monte, deve ser apedrejado".

[[v58-12-21]]

^<<v58-12-21,21>>^ O próprio Moisés ficou tão assustado com o que viu a ponto de dizer: "Fiquei apavorado e tremendo de medo".

[[v58-12-22]]

^<<v58-12-22,22>>^ Vocês, porém, chegaram ao monte Sião, à cidade do Deus vivo, à Jerusalém celestial, aos incontáveis milhares de anjos em alegre reunião,

[[v58-12-23]]

^<<v58-12-23,23>>^ à congregação dos filhos mais velhos, cujos nomes estão escritos no céu, e a Deus, que é juiz de todos, aos espíritos dos justos no céu, agora aperfeiçoados,

[[v58-12-24]]

^<<v58-12-24,24>>^ a Jesus, o mediador da nova aliança, e ao sangue aspergido, que fala de coisas melhores do que falava o sangue de Abel.

[[v58-12-25]]

^<<v58-12-25,25>>^ Tenham cuidado para não se recusarem a ouvir aquele que fala. Porque, se aqueles que se recusaram a ouvir o mensageiro terreno não escaparam, certamente não escaparemos se rejeitarmos aquele que nos fala do céu.

[[v58-12-26]]

^<<v58-12-26,26>>^ Quando Deus falou naquela ocasião, sua voz fez a terra tremer, mas agora ele promete: "Mais uma vez, farei tremer não só a terra, mas também os céus".

[[v58-12-27]]

^<<v58-12-27,27>>^ Isso significa que toda a criação será abalada e removida, de modo que permaneçam apenas as coisas inabaláveis.

[[v58-12-28]]

^<<v58-12-28,28>>^ Uma vez que recebemos um reino inabalável, sejamos gratos e agrademos a Deus adorando-o com reverência e santo temor.

[[v58-12-29]]

^<<v58-12-29,29>>^ Porque nosso Deus é um fogo consumidor.

'''

xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[&#60; Capítulo Anterior] | <<v58-12-0,Topo>> | xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[Próximo Capítulo &#62;]