include::./index.adoc[]

[[v58-2-0]]
=== Hebreus, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v58-2-1]]

^<<v58-2-1,1>>^ Portanto, precisamos prestar muita atenção às verdades que temos ouvido, para não nos desviarmos delas.

[[v58-2-2]]

^<<v58-2-2,2>>^ Pois a mensagem que foi transmitida por meio de anjos permaneceu firme, e toda transgressão e desobediência recebeu o castigo merecido.

[[v58-2-3]]

^<<v58-2-3,3>>^ O que nos faz pensar que escaparemos se negligenciarmos essa grande salvação, anunciada primeiramente pelo Senhor e depois transmitida a nós por aqueles que o ouviram falar?

[[v58-2-4]]

^<<v58-2-4,4>>^ E Deus confirmou a mensagem por meio de sinais, maravilhas e diversos milagres, e também por dons do Espírito Santo, conforme sua vontade.

[[v58-2-5]]

^<<v58-2-5,5>>^ Além disso, não são anjos que governarão o mundo futuro a que nos referimos.

[[v58-2-6]]

^<<v58-2-6,6>>^ Porque em certo lugar alguém disse: "Quem é o simples mortal, para que penses nele? Quem é o filho do homem, para que com ele te importes?

[[v58-2-7]]

^<<v58-2-7,7>>^ E, no entanto, por pouco tempo o fizeste um pouco menor que os anjos e o coroaste de glória e honra.

[[v58-2-8]]

^<<v58-2-8,8>>^ Tu lhe deste autoridade sobre todas as coisas". Quando se diz "todas as coisas", significa que nada foi deixado de fora. É verdade que ainda não vimos tudo ser submetido à sua autoridade.

[[v58-2-9]]

^<<v58-2-9,9>>^ Contudo, vemos Jesus, que por pouco tempo foi feito "um pouco menor que os anjos" e que, por ter sofrido a morte, agora está coroado "de glória e honra". Sim, pela graça de Deus, Jesus experimentou a morte por todos.

[[v58-2-10]]

^<<v58-2-10,10>>^ Deus, para quem e por meio de quem todas as coisas foram criadas, escolheu levar muitos filhos à glória. E era apropriado que, por meio do sofrimento de Jesus, ele o tornasse o líder perfeito para conduzi-los à salvação.

[[v58-2-11]]

^<<v58-2-11,11>>^ Assim, tanto o que santifica como os que são santificados procedem de um só. Por isso Jesus não se envergonha de chamá-los irmãos,

[[v58-2-12]]

^<<v58-2-12,12>>^ quando diz: "Proclamarei teu nome a meus irmãos; no meio de teu povo reunido te louvarei".

[[v58-2-13]]

^<<v58-2-13,13>>^ E também afirmou: "Porei minha confiança nele", isto é, "eu e os filhos que Deus me deu".

[[v58-2-14]]

^<<v58-2-14,14>>^ Visto, portanto, que os filhos são seres humanos, feitos de carne e sangue, o Filho também se tornou carne e sangue, pois somente assim ele poderia morrer e, somente ao morrer, destruiria o diabo, que tinha o poder da morte.

[[v58-2-15]]

^<<v58-2-15,15>>^ Só dessa maneira ele libertaria aqueles que durante toda a vida estiveram escravizados pelo medo da morte.

[[v58-2-16]]

^<<v58-2-16,16>>^ Também sabemos que o Filho não veio para ajudar os anjos, mas sim os descendentes de Abraão.

[[v58-2-17]]

^<<v58-2-17,17>>^ Portanto, era necessário que ele se tornasse semelhante a seus irmãos em todos os aspectos, de modo que pudesse ser nosso misericordioso e fiel Sumo Sacerdote diante de Deus e realizar o sacrifício que remove os pecados do povo.

[[v58-2-18]]

^<<v58-2-18,18>>^ Uma vez que ele próprio passou por sofrimento e tentação, é capaz de ajudar aqueles que são tentados.

'''

xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[&#60; Capítulo Anterior] | <<v58-2-0,Topo>> | xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[Próximo Capítulo &#62;]