include::./index.adoc[]

[[v58-6-0]]
=== Hebreus, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v58-6-1]]

^<<v58-6-1,1>>^ Portanto, deixemos de lado os ensinamentos básicos a respeito de Cristo e sigamos em frente, alcançando a maturidade em nosso entendimento. Certamente não precisamos lançar novamente os alicerces, ou seja, o arrependimento das obras mortas, a fé em Deus,

[[v58-6-2]]

^<<v58-6-2,2>>^ o batismo, a imposição de mãos, a ressurreição dos mortos e o julgamento eterno.

[[v58-6-3]]

^<<v58-6-3,3>>^ Se Deus permitir, avançaremos para um maior entendimento.

[[v58-6-4]]

^<<v58-6-4,4>>^ Pois é impossível trazer de volta ao arrependimento aqueles que já foram iluminados, que já experimentaram as dádivas celestiais e se tornaram participantes do Espírito Santo,

[[v58-6-5]]

^<<v58-6-5,5>>^ que provaram a bondade da palavra de Deus e os poderes do mundo por vir,

[[v58-6-6]]

^<<v58-6-6,6>>^ e que depois se desviaram. Sim, é impossível trazê-los de volta ao arrependimento, pois, ao rejeitar o Filho de Deus, eles voltaram a pregá-lo na cruz, expondo-o à vergonha pública.

[[v58-6-7]]

^<<v58-6-7,7>>^ Quando a terra absorve a chuva que cai e produz uma boa colheita para o lavrador, recebe a bênção de Deus.

[[v58-6-8]]

^<<v58-6-8,8>>^ Mas, se a terra produz espinhos e ervas daninhas, para nada serve, sendo logo amaldiçoada e, por fim, queimada.

[[v58-6-9]]

^<<v58-6-9,9>>^ Amados, embora estejamos falando dessa forma, na realidade não cremos que se aplique a vocês. Temos certeza de que estão destinados às coisas melhores que pertencem à salvação.

[[v58-6-10]]

^<<v58-6-10,10>>^ Pois Deus não é injusto; não se esquecerá de como trabalharam arduamente para ele e lhe demonstraram seu amor ao cuidar do povo santo, como ainda fazem.

[[v58-6-11]]

^<<v58-6-11,11>>^ Nosso desejo é que vocês continuem a mostrar essa mesma dedicação até o fim, para que tenham plena certeza de sua esperança.

[[v58-6-12]]

^<<v58-6-12,12>>^ Assim, não se tornarão displicentes, mas seguirão o exemplo daqueles que, por causa de sua fé e perseverança, herdarão as promessas.

[[v58-6-13]]

^<<v58-6-13,13>>^ Considerem a promessa de Deus a Abraão. Uma vez que não havia ninguém superior por quem jurar, Deus jurou por si mesmo. Disse ele:

[[v58-6-14]]

^<<v58-6-14,14>>^ "Certamente o abençoarei e multiplicarei grandemente seus descendentes".

[[v58-6-15]]

^<<v58-6-15,15>>^ Então Abraão esperou com paciência, e recebeu o que lhe fora prometido.

[[v58-6-16]]

^<<v58-6-16,16>>^ Quando a pessoa faz um juramento, invoca alguém maior que ela. E, sem dúvida, o juramento implica uma obrigação.

[[v58-6-17]]

^<<v58-6-17,17>>^ Deus também se comprometeu por meio de um juramento, para que os herdeiros da promessa tivessem plena convicção de que ele jamais mudaria de ideia.

[[v58-6-18]]

^<<v58-6-18,18>>^ A promessa e o juramento não podem ser mudados, pois é impossível que Deus minta. Portanto, nós que nele nos refugiamos estamos firmemente seguros ao nos apegarmos à esperança posta diante de nós.

[[v58-6-19]]

^<<v58-6-19,19>>^ Essa esperança é uma âncora firme e confiável para nossa alma. Ela nos conduz até o outro lado da cortina, para o santuário interior.

[[v58-6-20]]

^<<v58-6-20,20>>^ Jesus já entrou ali por nós. Ele se tornou nosso eterno Sumo Sacerdote, segundo a ordem de Melquisedeque.

'''

xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[&#60; Capítulo Anterior] | <<v58-6-0,Topo>> | xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[Próximo Capítulo &#62;]