include::./index.adoc[]

[[v58-1-0]]
=== Hebreus, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v58-1-1]]

^<<v58-1-1,1>>^ Por muito tempo Deus falou várias vezes e de diversas maneiras a nossos antepassados por meio dos profetas.

[[v58-1-2]]

^<<v58-1-2,2>>^ E agora, nestes últimos dias, ele nos falou por meio do Filho, o qual ele designou como herdeiro de todas as coisas e por meio de quem criou o universo.

[[v58-1-3]]

^<<v58-1-3,3>>^ O Filho irradia a glória de Deus, expressa de forma exata o que Deus é e, com sua palavra poderosa, sustenta todas as coisas. Depois de nos purificar de nossos pecados, sentou-se no lugar de honra à direita do Deus majestoso no céu,

[[v58-1-4]]

^<<v58-1-4,4>>^ o que revela que o Filho é muito superior aos anjos, e o nome que ele herdou, superior ao nome deles.

[[v58-1-5]]

^<<v58-1-5,5>>^ Pois Deus nunca disse a nenhum anjo: "Você é meu Filho; hoje eu o gerei". Ou ainda: "Eu serei seu Pai, e ele será meu Filho".

[[v58-1-6]]

^<<v58-1-6,6>>^ E, quando ele trouxe seu Filho supremo ao mundo, disse: "Que todos os anjos de Deus o adorem".

[[v58-1-7]]

^<<v58-1-7,7>>^ A respeito dos anjos, ele diz: "Ele envia seus anjos como os ventos, e seus servos, como chamas de fogo".

[[v58-1-8]]

^<<v58-1-8,8>>^ Mas ao Filho ele diz: "Teu trono, ó Deus, permanece para todo o sempre; tu governas com cetro de justiça.

[[v58-1-9]]

^<<v58-1-9,9>>^ Amas a justiça e odeias o mal; por isso, Deus, o teu Deus, te ungiu. Derramou sobre ti o óleo da alegria, mais que sobre qualquer outro".

[[v58-1-10]]

^<<v58-1-10,10>>^ E diz também: "No princípio, Senhor, lançaste os fundamentos da terra, e com tuas mãos formaste os céus.

[[v58-1-11]]

^<<v58-1-11,11>>^ Eles deixarão de existir, mas tu permanecerás para sempre; eles se desgastarão, como roupa velha.

[[v58-1-12]]

^<<v58-1-12,12>>^ Tu os desdobrarás como um manto e te desfarás deles como roupa velha. Tu, porém, és sempre o mesmo; teus dias jamais terão fim".

[[v58-1-13]]

^<<v58-1-13,13>>^ E ele nunca disse a nenhum de seus anjos: "Sente-se no lugar de honra à minha direita, até que eu humilhe seus inimigos e os ponha debaixo de seus pés".

[[v58-1-14]]

^<<v58-1-14,14>>^ Portanto, os anjos são apenas servos, espíritos enviados para cuidar daqueles que herdarão a salvação.

'''

xref:057-filemom/057-filemom-001.adoc#v57-1-0[&#60; Capítulo Anterior] | <<v58-1-0,Topo>> | xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[Próximo Capítulo &#62;]