include::./index.adoc[]

[[v58-9-0]]
=== Hebreus, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v58-9-1]]

^<<v58-9-1,1>>^ A primeira aliança tinha regras para a adoração, bem como um santuário terreno.

[[v58-9-2]]

^<<v58-9-2,2>>^ Esse tabernáculo era dividido em duas partes. Na primeira, ficava o candelabro e a mesa com os pães da presença. Essa parte era chamada lugar santo.

[[v58-9-3]]

^<<v58-9-3,3>>^ Depois, havia uma cortina e, atrás dela, a segunda parte, chamada lugar santíssimo.

[[v58-9-4]]

^<<v58-9-4,4>>^ Nessa parte ficava o altar de ouro para o incenso e a arca da aliança, inteiramente coberta de ouro. Dentro da arca havia um vaso de ouro contendo maná, a vara de Arão que floresceu e as tábuas de pedra da aliança.

[[v58-9-5]]

^<<v58-9-5,5>>^ Sobre a arca ficavam os querubins da glória divina, cuja sombra se estendia por cima do lugar de expiação. Mas agora não é o momento de explicar essas coisas em detalhes.

[[v58-9-6]]

^<<v58-9-6,6>>^ Quando tudo estava preparado, os sacerdotes entravam regularmente no lugar santo para cumprir seus deveres sagrados.

[[v58-9-7]]

^<<v58-9-7,7>>^ Mas apenas o sumo sacerdote, e só uma vez por ano, entrava no lugar santíssimo. Ele sempre apresentava o sangue do sacrifício pelos próprios pecados e pelos pecados que o povo havia cometido por ignorância.

[[v58-9-8]]

^<<v58-9-8,8>>^ Com essas regras, o Espírito Santo mostra que o caminho para o lugar santíssimo não havia sido aberto enquanto o primeiro tabernáculo continuava em uso.

[[v58-9-9]]

^<<v58-9-9,9>>^ Essa é uma ilustração que aponta para o tempo presente, pois as ofertas e os sacrifícios que os sacerdotes apresentam não podem criar no adorador uma consciência totalmente limpa.

[[v58-9-10]]

^<<v58-9-10,10>>^ Tratava-se apenas de alimentos e bebidas e várias cerimônias de purificação; eram regras externas, válidas apenas até que se estabelecesse um sistema melhor.

[[v58-9-11]]

^<<v58-9-11,11>>^ Cristo se tornou o Sumo Sacerdote de todos os benefícios agora presentes. Ele entrou naquele tabernáculo maior e mais perfeito no céu, que não foi feito por mãos humanas nem faz parte deste mundo criado.

[[v58-9-12]]

^<<v58-9-12,12>>^ Com seu próprio sangue, e não com o sangue de bodes e bezerros, entrou no lugar santíssimo de uma vez por todas e garantiu redenção eterna.

[[v58-9-13]]

^<<v58-9-13,13>>^ Se, portanto, o sangue de bodes e bezerros e as cinzas de uma novilha purificavam o corpo de quem estava cerimonialmente impuro,

[[v58-9-14]]

^<<v58-9-14,14>>^ imaginem como o sangue de Cristo purificará nossa consciência das obras mortas, para que adoremos o Deus vivo. Pois, pelo poder do Espírito eterno, Cristo ofereceu a si mesmo a Deus como sacrifício perfeito.

[[v58-9-15]]

^<<v58-9-15,15>>^ Por isso ele é o mediador da nova aliança, para que todos que são chamados recebam a herança eterna que foi prometida. Porque Cristo morreu para libertá-los do castigo dos pecados que haviam cometido sob a primeira aliança.

[[v58-9-16]]

^<<v58-9-16,16>>^ Quando alguém deixa um testamento, é necessário comprovar a morte daquele que o fez.

[[v58-9-17]]

^<<v58-9-17,17>>^ O testamento só se torna válido após a morte da pessoa. Enquanto ela ainda estiver viva, o testamento não entra em vigor.

[[v58-9-18]]

^<<v58-9-18,18>>^ É por isso que até mesmo a primeira aliança foi sancionada com o sangue.

[[v58-9-19]]

^<<v58-9-19,19>>^ Depois de ler todos os mandamentos da lei a todo o povo, Moisés pegou o sangue de novilhos e de bodes, e também água, e os aspergiu com ramos de hissopo e lã vermelha sobre o Livro da Lei e sobre todo o povo.

[[v58-9-20]]

^<<v58-9-20,20>>^ Em seguida, disse: "Este sangue confirma a aliança que Deus fez com vocês".

[[v58-9-21]]

^<<v58-9-21,21>>^ Da mesma forma, aspergiu com sangue o tabernáculo e todos os utensílios usados nos serviços sagrados.

[[v58-9-22]]

^<<v58-9-22,22>>^ De fato, segundo a lei, quase tudo era purificado com sangue, pois sem derramamento de sangue não há perdão.

[[v58-9-23]]

^<<v58-9-23,23>>^ Assim, as representações das coisas no céu tiveram de ser purificadas com o sangue de animais. As verdadeiras coisas celestiais, porém, tiveram de ser purificadas com sacrifícios muitos superiores.

[[v58-9-24]]

^<<v58-9-24,24>>^ Pois Cristo não entrou num santuário feito por mãos humanas, mera representação do santuário verdadeiro no céu. Ele entrou no próprio céu, a fim de agora se apresentar diante de Deus em nosso favor.

[[v58-9-25]]

^<<v58-9-25,25>>^ E ele não entrou no céu para oferecer a si mesmo repetidamente, como o sumo sacerdote aqui na terra, que todos os anos entra no lugar santíssimo com o sangue de um animal.

[[v58-9-26]]

^<<v58-9-26,26>>^ Se fosse assim, ele precisaria ter morrido muitas vezes, desde o princípio do mundo. Mas agora, no fim dos tempos, ele apareceu uma vez por todas para remover o pecado mediante sua própria morte em sacrifício.

[[v58-9-27]]

^<<v58-9-27,27>>^ E, assim como cada pessoa está destinada a morrer uma só vez, e depois disso vem o julgamento,

[[v58-9-28]]

^<<v58-9-28,28>>^ também Cristo foi oferecido como sacrifício uma só vez para tirar os pecados de muitos. Ele voltará, não para tratar de nossos pecados, mas para trazer salvação a todos que o aguardam com grande expectativa.

'''

xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[&#60; Capítulo Anterior] | <<v58-9-0,Topo>> | xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[Próximo Capítulo &#62;]