include::./index.adoc[]

[[v58-13-0]]
=== Hebreus, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v58-13-1]]

^<<v58-13-1,1>>^ Continuem a amar uns aos outros como irmãos.

[[v58-13-2]]

^<<v58-13-2,2>>^ Não se esqueçam de demonstrar hospitalidade, porque alguns, sem o saber, hospedaram anjos.

[[v58-13-3]]

^<<v58-13-3,3>>^ Lembrem-se dos que estão na prisão, como se vocês mesmos estivessem presos. Lembrem-se dos que são maltratados, como se sofressem os maus-tratos em seu próprio corpo.

[[v58-13-4]]

^<<v58-13-4,4>>^ Honrem o casamento e mantenham pura a união conjugal, pois Deus certamente julgará os impuros e os adúlteros.

[[v58-13-5]]

^<<v58-13-5,5>>^ Não amem o dinheiro; estejam satisfeitos com o que têm. Porque Deus disse: "Não o deixarei; jamais o abandonarei".

[[v58-13-6]]

^<<v58-13-6,6>>^ Por isso, podemos dizer com toda a confiança: "O Senhor é meu ajudador, portanto não temerei; o que me podem fazer os simples mortais?".

[[v58-13-7]]

^<<v58-13-7,7>>^ Lembrem-se de seus líderes que lhes ensinaram a palavra de Deus. Pensem em todo o bem que resultou da vida deles e sigam seu exemplo de fé.

[[v58-13-8]]

^<<v58-13-8,8>>^ Jesus Cristo é o mesmo ontem, hoje e para sempre.

[[v58-13-9]]

^<<v58-13-9,9>>^ Portanto, não se deixem atrair por ensinos novos e estranhos. A força de vocês vem da graça de Deus, e não de regras sobre alimentos, que em nada ajudam aqueles que as seguem.

[[v58-13-10]]

^<<v58-13-10,10>>^ Temos um altar do qual os sacerdotes no tabernáculo não têm direito de comer.

[[v58-13-11]]

^<<v58-13-11,11>>^ O sumo sacerdote traz o sangue dos animais para o lugar santo como sacrifício pelo pecado, enquanto o corpo dos animais é queimado fora do acampamento.

[[v58-13-12]]

^<<v58-13-12,12>>^ Da mesma forma, Jesus sofreu fora das portas da cidade, para santificar seu povo mediante seu próprio sangue.

[[v58-13-13]]

^<<v58-13-13,13>>^ Portanto, vamos até ele, para fora do acampamento, e soframos a mesma desonra que ele sofreu.

[[v58-13-14]]

^<<v58-13-14,14>>^ Pois não temos neste mundo uma cidade permanente; aguardamos a cidade por vir.

[[v58-13-15]]

^<<v58-13-15,15>>^ Assim, por meio de Jesus, ofereçamos um sacrifício constante de louvor a Deus, o fruto dos lábios que proclamam seu nome.

[[v58-13-16]]

^<<v58-13-16,16>>^ E não se esqueçam de fazer o bem e de repartir o que têm com os necessitados, pois esses são os sacrifícios que agradam a Deus.

[[v58-13-17]]

^<<v58-13-17,17>>^ Obedeçam a seus líderes e façam o que disserem. O trabalho deles é cuidar de sua alma, e disso prestarão contas. Deem-lhes motivo para trabalhar com alegria, e não com tristeza, pois isso certamente não beneficiaria vocês.

[[v58-13-18]]

^<<v58-13-18,18>>^ Orem por nós, pois nossa consciência está limpa e desejamos viver de forma honrada em tudo que fazemos.

[[v58-13-19]]

^<<v58-13-19,19>>^ Orem especialmente para que eu volte e possa vê-los em breve.

[[v58-13-20]]

^<<v58-13-20,20>>^ E, agora, que o Deus da paz, que trouxe de volta dos mortos nosso Senhor Jesus, o grande Pastor das ovelhas, e confirmou uma aliança eterna com seu sangue,

[[v58-13-21]]

^<<v58-13-21,21>>^ os capacite em tudo que precisam para fazer a vontade dele. Que ele produza em vocês, mediante o poder de Jesus Cristo, tudo que é agradável a ele, a quem seja a glória para todo o sempre! Amém.

[[v58-13-22]]

^<<v58-13-22,22>>^ Suplico a vocês, irmãos, que prestem atenção naquilo que lhes escrevi nesta breve exortação.

[[v58-13-23]]

^<<v58-13-23,23>>^ Quero que saibam que nosso irmão Timóteo já saiu da prisão. Se ele vier em breve, eu o levarei comigo quando for vê-los.

[[v58-13-24]]

^<<v58-13-24,24>>^ Transmitam minhas saudações a todos os seus líderes e a todo o povo santo. Os irmãos da Itália também mandam lembranças.

[[v58-13-25]]

^<<v58-13-25,25>>^ Que a graça de Deus seja com todos vocês.

'''

xref:058-hebreus/058-hebreus-012.adoc#v58-12-0[&#60; Capítulo Anterior] | <<v58-13-0,Topo>> | xref:059-tiago/059-tiago-001.adoc#v59-1-0[Próximo Capítulo &#62;]