include::./index.adoc[]

[[v53-1-0]]
=== 2 Tessalonicenses, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v53-1-1]]

^<<v53-1-1,1>>^ Nós, Paulo, Silas e Timóteo, escrevemos esta carta à igreja em Tessalônica, a vocês que estão em Deus, nosso Pai, e no Senhor Jesus Cristo.

[[v53-1-2]]

^<<v53-1-2,2>>^ Que Deus, nosso Pai, e o Senhor Jesus Cristo lhes deem graça e paz.

[[v53-1-3]]

^<<v53-1-3,3>>^ Irmãos, não podemos deixar de dar graças a Deus por vocês, pois sua fé tem se desenvolvido cada vez mais, e seu amor uns pelos outros tem crescido.

[[v53-1-4]]

^<<v53-1-4,4>>^ Por isso nos orgulhamos de falar às outras igrejas de Deus sobre sua perseverança e fidelidade em todas as perseguições e aflições que vocês têm sofrido.

[[v53-1-5]]

^<<v53-1-5,5>>^ Deus usará essa perseguição para mostrar que seu julgamento é justo e para torná-los dignos de seu reino, pelo qual estão sofrendo.

[[v53-1-6]]

^<<v53-1-6,6>>^ Em sua justiça, Deus pagará com aflição aqueles que afligem vocês.

[[v53-1-7]]

^<<v53-1-7,7>>^ Deus concederá descanso a vocês, que são afligidos, e também a nós, na revelação do Senhor Jesus, quando ele vier do céu. Virá com seus anjos poderosos,

[[v53-1-8]]

^<<v53-1-8,8>>^ em chamas de fogo, trazendo juízo sobre os que não conhecem a Deus e sobre os que se recusam a obedecer às boas-novas de nosso Senhor Jesus.

[[v53-1-9]]

^<<v53-1-9,9>>^ Eles serão punidos com destruição eterna, separados para sempre da presença do Senhor e de seu glorioso poder.

[[v53-1-10]]

^<<v53-1-10,10>>^ No dia em que ele vier, receberá glória de seu povo santo e louvores de todos os que creem. E isso inclui vocês, pois creram naquilo que lhes dissemos a respeito dele.

[[v53-1-11]]

^<<v53-1-11,11>>^ Assim, continuamos a orar por vocês, pedindo a nosso Deus que os capacite a ter uma vida digna de seu chamado e lhes dê poder para realizar as coisas boas que a fé os motivar a fazer.

[[v53-1-12]]

^<<v53-1-12,12>>^ Então o nome de nosso Senhor Jesus será honrado em vocês, e vocês serão honrados com ele. Tudo isso é possível pela graça de nosso Deus e Senhor, Jesus Cristo.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[&#60; Capítulo Anterior] | <<v53-1-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[Próximo Capítulo &#62;]