include::./index.adoc[]

[[v53-2-0]]
=== 2 Tessalonicenses, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v53-2-1]]

^<<v53-2-1,1>>^ Agora, irmãos, vamos esclarecer algumas coisas a respeito da vinda de nosso Senhor Jesus Cristo e de nosso encontro com ele.

[[v53-2-2]]

^<<v53-2-2,2>>^ Não se deixem abalar nem assustar tão facilmente por aqueles que dizem que o dia do Senhor já começou. Não acreditem neles, mesmo que afirmem ter recebido uma visão espiritual, uma revelação ou uma carta supostamente enviada por nós.

[[v53-2-3]]

^<<v53-2-3,3>>^ Não se deixem enganar pelo que dizem, pois esse dia não virá até que surja a rebelião e venha o homem da perversidade, aquele que traz destruição.

[[v53-2-4]]

^<<v53-2-4,4>>^ Ele se exaltará e se oporá a tudo que o povo chama de "deus" e a todo objeto de culto, e até se sentará no templo de Deus e se fará passar por Deus.

[[v53-2-5]]

^<<v53-2-5,5>>^ Não se lembram de que eu lhes falei disso tudo quando estive aí?

[[v53-2-6]]

^<<v53-2-6,6>>^ E vocês sabem o que o está detendo, pois ele só pode ser revelado quando sua hora chegar.

[[v53-2-7]]

^<<v53-2-7,7>>^ Pois essa perversidade já opera secretamente e permanecerá em segredo até que se afaste aquele que a detém.

[[v53-2-8]]

^<<v53-2-8,8>>^ Então o homem da perversidade será revelado, mas o Senhor Jesus o matará com o sopro de sua boca e o destruirá com o esplendor de sua vinda.

[[v53-2-9]]

^<<v53-2-9,9>>^ Esse homem virá para realizar o trabalho de Satanás, com poder, sinais e falsas maravilhas,

[[v53-2-10]]

^<<v53-2-10,10>>^ e com todo tipo de mentira perversa para enganar os que estão caminhando para a destruição, pois se recusam a amar e a aceitar a verdade que os salvaria.

[[v53-2-11]]

^<<v53-2-11,11>>^ Portanto, Deus fará que sejam enganados, e eles crerão nessas mentiras.

[[v53-2-12]]

^<<v53-2-12,12>>^ Então serão condenados por ter prazer no mal em vez de crer na verdade.

[[v53-2-13]]

^<<v53-2-13,13>>^ Quanto a nós, não podemos deixar de dar graças a Deus por vocês, irmãos amados pelo Senhor. Somos sempre gratos porque Deus os escolheu para estarem entre os primeiros a receber a salvação por meio do Espírito que os torna santos e pela fé na verdade.

[[v53-2-14]]

^<<v53-2-14,14>>^ Ele os chamou para a salvação quando lhes anunciamos as boas-novas; agora vocês podem participar da glória de nosso Senhor Jesus Cristo.

[[v53-2-15]]

^<<v53-2-15,15>>^ Portanto, irmãos, tendo em mente todas essas coisas, permaneçam firmes e apeguem-se às tradições que lhes transmitimos, seja pessoalmente, seja por carta.

[[v53-2-16]]

^<<v53-2-16,16>>^ Que o próprio Jesus Cristo, nosso Senhor, e Deus, nosso Pai, que nos amou e pela graça nos deu eterno conforto e maravilhosa esperança,

[[v53-2-17]]

^<<v53-2-17,17>>^ os animem e os fortaleçam em tudo de bom que vocês fizerem e disserem.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[&#60; Capítulo Anterior] | <<v53-2-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[Próximo Capítulo &#62;]