include::./index.adoc[]

[[v19-61-0]]
=== Salmos, 61
// nvt ?, NVT - Nova Versão Transformadora

[[v19-61-1]]

^<<v19-61-1,1>>^ Ó Deus, ouve meu clamor! Escuta minha oração!

[[v19-61-2]]

^<<v19-61-2,2>>^ Dos confins da terra clamo a ti, com meu coração sobrecarregado. Leva-me à rocha alta e segura,

[[v19-61-3]]

^<<v19-61-3,3>>^ pois és meu refúgio e minha fortaleza, onde meus inimigos não me alcançarão.

[[v19-61-4]]

^<<v19-61-4,4>>^ Permite-me viver para sempre em teu santuário, seguro sob o abrigo de tuas asas! Interlúdio

[[v19-61-5]]

^<<v19-61-5,5>>^ Pois ouviste meus votos, ó Deus, e me deste a bênção reservada para os que temem teu nome.

[[v19-61-6]]

^<<v19-61-6,6>>^ Acrescenta muitos anos à vida do rei! Que ele viva por muitas gerações!

[[v19-61-7]]

^<<v19-61-7,7>>^ Que ele reine na presença de Deus para sempre, e que o teu amor e a tua fidelidade o guardem.

[[v19-61-8]]

^<<v19-61-8,8>>^ Então cantarei para sempre louvores ao teu nome, enquanto cumpro meus votos a cada dia.

'''

xref:019-salmos/019-salmos-060.adoc#v19-60-0[&#60; Capítulo Anterior] | <<v19-61-0,Topo>> | xref:019-salmos/019-salmos-062.adoc#v19-62-0[Próximo Capítulo &#62;]