include::./index.adoc[]

[[v19-77-0]]
=== Salmos, 77
// nvt ?, NVT - Nova Versão Transformadora

[[v19-77-1]]

^<<v19-77-1,1>>^ Clamo a Deus; sim, grito bem alto. Quem dera Deus me ouvisse!

[[v19-77-2]]

^<<v19-77-2,2>>^ Quando eu estava angustiado, busquei o Senhor. Orei a noite toda, de mãos estendidas para o céu, mas minha alma recusou ser consolada.

[[v19-77-3]]

^<<v19-77-3,3>>^ Lembro-me de Deus e começo a gemer; desfaleço, ansioso por sua ajuda. Interlúdio

[[v19-77-4]]

^<<v19-77-4,4>>^ Tu não me deixas dormir; estou tão desesperado que nem consigo falar!

[[v19-77-5]]

^<<v19-77-5,5>>^ Penso nos dias que passaram, nos anos que há muito se foram.

[[v19-77-6]]

^<<v19-77-6,6>>^ À noite, relembro canções alegres; consulto minha alma e procuro compreender minha situação.

[[v19-77-7]]

^<<v19-77-7,7>>^ Acaso o Senhor me rejeitou em definitivo? Jamais voltará a ser bondoso comigo?

[[v19-77-8]]

^<<v19-77-8,8>>^ Seu amor se foi para nunca mais voltar? Deixou de cumprir suas promessas para sempre?

[[v19-77-9]]

^<<v19-77-9,9>>^ Deus se esqueceu de ser bondoso? Em sua ira, fechou a porta para a compaixão? Interlúdio

[[v19-77-10]]

^<<v19-77-10,10>>^ Pensei: "É por esta razão que sofro; o Altíssimo voltou sua mão direita contra mim".

[[v19-77-11]]

^<<v19-77-11,11>>^ Depois, porém, lembro-me de tudo que fizeste, SENHOR; recordo-me de tuas maravilhas do passado.

[[v19-77-12]]

^<<v19-77-12,12>>^ Estão sempre em meus pensamentos; não deixo de refletir sobre teus poderosos feitos.

[[v19-77-13]]

^<<v19-77-13,13>>^ Teus caminhos, ó Deus, são santos; que deus é poderoso como o nosso Deus?

[[v19-77-14]]

^<<v19-77-14,14>>^ És o Deus que realiza maravilhas; mostras o teu poder entre as nações!

[[v19-77-15]]

^<<v19-77-15,15>>^ Com teu braço forte resgataste teu povo, os descendentes de Jacó e José. Interlúdio

[[v19-77-16]]

^<<v19-77-16,16>>^ As águas te viram, ó Deus, as águas te viram e estremeceram; até as profundezas do mar se agitaram.

[[v19-77-17]]

^<<v19-77-17,17>>^ As nuvens derramaram chuva, os trovões ressoaram nas alturas, os teus relâmpagos riscaram os céus.

[[v19-77-18]]

^<<v19-77-18,18>>^ No redemoinho ouviu-se o estrondo de teu trovão; os relâmpagos iluminaram o mundo, e a terra tremeu e se abalou.

[[v19-77-19]]

^<<v19-77-19,19>>^ Teu caminho passou pelo mar, teu trajeto, pelas águas poderosas, e ninguém percebeu teus passos.

[[v19-77-20]]

^<<v19-77-20,20>>^ Conduziste teu povo como um rebanho de ovelhas, pelas mãos de Moisés e Arão.

'''

xref:019-salmos/019-salmos-076.adoc#v19-76-0[&#60; Capítulo Anterior] | <<v19-77-0,Topo>> | xref:019-salmos/019-salmos-078.adoc#v19-78-0[Próximo Capítulo &#62;]