include::./index.adoc[]

[[v19-17-0]]
=== Salmos, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v19-17-1]]

^<<v19-17-1,1>>^ Ouve, SENHOR, minha súplica por justiça; atende a meu clamor por socorro. Escuta minha oração, pois ela vem de lábios sinceros.

[[v19-17-2]]

^<<v19-17-2,2>>^ Declara-me inocente, pois teus olhos veem com imparcialidade.

[[v19-17-3]]

^<<v19-17-3,3>>^ Tu puseste à prova meus pensamentos; durante a noite, examinaste meu coração. Tu me sondaste e não encontraste nenhum mal; estou decidido a não pecar com minhas palavras.

[[v19-17-4]]

^<<v19-17-4,4>>^ Quanto ao modo de agir, segui teus mandamentos, que me guardam de imitar as ações de pessoas cruéis.

[[v19-17-5]]

^<<v19-17-5,5>>^ Meus passos permaneceram em teu caminho, meus pés não se desviaram dele.

[[v19-17-6]]

^<<v19-17-6,6>>^ Clamo a ti, ó Deus, pois sei que responderás; inclina-te e ouve minha oração.

[[v19-17-7]]

^<<v19-17-7,7>>^ Mostra-me as maravilhas do teu amor; com teu poder, tu livras os que buscam em ti refúgio dos inimigos.

[[v19-17-8]]

^<<v19-17-8,8>>^ Protege-me, como a menina de teus olhos; esconde-me à sombra de tuas asas.

[[v19-17-9]]

^<<v19-17-9,9>>^ Guarda-me dos perversos que me atacam, dos inimigos mortais que me cercam.

[[v19-17-10]]

^<<v19-17-10,10>>^ Eles não têm compaixão; ouve como contam vantagem!

[[v19-17-11]]

^<<v19-17-11,11>>^ Seguem meus passos e me rodeiam, prontos para me derrubar.

[[v19-17-12]]

^<<v19-17-12,12>>^ São como leões famintos, ansiosos para me despedaçar, como jovens leões escondidos, de tocaia.

[[v19-17-13]]

^<<v19-17-13,13>>^ Levanta-te, ó SENHOR! Enfrenta-os e faze-os cair de joelhos! Com tua espada, livra-me dos perversos!

[[v19-17-14]]

^<<v19-17-14,14>>^ Pelo poder de tua mão, SENHOR, destrói os que buscam neste mundo sua recompensa. Satisfaz, porém, a fome dos que te são preciosos; que os filhos deles tenham fartura e deixem herança para os netos.

[[v19-17-15]]

^<<v19-17-15,15>>^ Porque sou justo, verei a ti; quando acordar, te verei face a face e me satisfarei.

'''

xref:019-salmos/019-salmos-016.adoc#v19-16-0[&#60; Capítulo Anterior] | <<v19-17-0,Topo>> | xref:019-salmos/019-salmos-018.adoc#v19-18-0[Próximo Capítulo &#62;]