include::./index.adoc[]

[[v19-104-0]]
=== Salmos, 104
// nvt ?, NVT - Nova Versão Transformadora

[[v19-104-1]]

^<<v19-104-1,1>>^ Todo o meu ser louve o SENHOR. Ó SENHOR, meu Deus, como és grandioso! Estás vestido de glória e majestade,

[[v19-104-2]]

^<<v19-104-2,2>>^ envolto num manto de luz. Estendes a cortina estrelada dos céus,

[[v19-104-3]]

^<<v19-104-3,3>>^ pões as vigas de tua casa nas nuvens de chuva. Fazes das nuvens o teu carro de combate, cavalgas nas asas do vento.

[[v19-104-4]]

^<<v19-104-4,4>>^ Os ventos são teus mensageiros, e as chamas de fogo, teus servos.

[[v19-104-5]]

^<<v19-104-5,5>>^ Firmaste o mundo sobre seus alicerces, para que jamais seja abalado.

[[v19-104-6]]

^<<v19-104-6,6>>^ Vestiste a terra com torrentes de água, com água que cobriu até os montes.

[[v19-104-7]]

^<<v19-104-7,7>>^ Por tua ordem, as águas fugiram; ao som de teu trovão, saíram correndo.

[[v19-104-8]]

^<<v19-104-8,8>>^ Montes se ergueram e vales afundaram, ao nível que tu decretaste.

[[v19-104-9]]

^<<v19-104-9,9>>^ Estabeleceste um limite para as águas, para que nunca mais cobrissem a terra.

[[v19-104-10]]

^<<v19-104-10,10>>^ Fazes as fontes derramarem água nos vales, e os riachos correm entre os montes.

[[v19-104-11]]

^<<v19-104-11,11>>^ Todos os animais bebem dessa água, e os jumentos selvagens matam a sede.

[[v19-104-12]]

^<<v19-104-12,12>>^ As aves fazem ninhos junto aos riachos e cantam entre os ramos das árvores.

[[v19-104-13]]

^<<v19-104-13,13>>^ De tua habitação celeste, envias chuva sobre os montes e enches a terra com o fruto do teu trabalho.

[[v19-104-14]]

^<<v19-104-14,14>>^ Fazes o pasto crescer para os animais, e as plantas, para as pessoas cultivarem. Permites que, da terra, colham seu alimento:

[[v19-104-15]]

^<<v19-104-15,15>>^ vinho para alegrar o coração, azeite para fazer brilhar a pele, pão para dar forças.

[[v19-104-16]]

^<<v19-104-16,16>>^ As árvores do SENHOR são bem cuidadas, os cedros do Líbano que ele plantou.

[[v19-104-17]]

^<<v19-104-17,17>>^ Nelas as aves fazem seus ninhos, nos ciprestes as cegonhas têm seu lar.

[[v19-104-18]]

^<<v19-104-18,18>>^ No alto dos montes vivem as cabras selvagens, nas rochas se escondem os coelhos silvestres.

[[v19-104-19]]

^<<v19-104-19,19>>^ Fizeste a lua para marcar as estações, e o sol sabe a hora de se pôr.

[[v19-104-20]]

^<<v19-104-20,20>>^ Envias a escuridão e se faz noite, quando vagueiam os animais do bosque.

[[v19-104-21]]

^<<v19-104-21,21>>^ Os leões jovens rugem por sua presa, saem à procura do alimento que Deus lhes provê.

[[v19-104-22]]

^<<v19-104-22,22>>^ Ao amanhecer eles se recolhem, voltam à toca para descansar.

[[v19-104-23]]

^<<v19-104-23,23>>^ Então as pessoas saem para o serviço, onde trabalham até o entardecer.

[[v19-104-24]]

^<<v19-104-24,24>>^ Ó SENHOR, que variedade de coisas criaste! Fizeste todas elas com sabedoria; a terra está cheia de tuas criaturas.

[[v19-104-25]]

^<<v19-104-25,25>>^ Ali está o oceano, vasto e imenso, cheio de seres de todo tipo, grandes e pequenos.

[[v19-104-26]]

^<<v19-104-26,26>>^ Por ele passam navios, e o Leviatã, que criaste para brincar no mar.

[[v19-104-27]]

^<<v19-104-27,27>>^ Todos dependem de ti para lhes proveres o alimento de que necessitam.

[[v19-104-28]]

^<<v19-104-28,28>>^ Quando tu lhes dás, eles o recolhem; abres a mão para alimentá-los, e eles ficam satisfeitos.

[[v19-104-29]]

^<<v19-104-29,29>>^ Se te afastas deles, porém, enchem-se de medo; quando lhes retiras o fôlego, morrem e voltam ao pó.

[[v19-104-30]]

^<<v19-104-30,30>>^ Quando sopras teu fôlego, novos seres são gerados, e renovas a face da terra.

[[v19-104-31]]

^<<v19-104-31,31>>^ Que a glória do SENHOR permaneça para sempre; o SENHOR tem prazer em tudo que criou!

[[v19-104-32]]

^<<v19-104-32,32>>^ Basta um olhar, e a terra estremece; com um simples toque, faz fumegar os montes.

[[v19-104-33]]

^<<v19-104-33,33>>^ Cantarei ao SENHOR enquanto viver, louvarei meu Deus até meu último suspiro.

[[v19-104-34]]

^<<v19-104-34,34>>^ Todos os meus pensamentos lhe sejam agradáveis; no SENHOR me alegrarei.

[[v19-104-35]]

^<<v19-104-35,35>>^ Desapareçam da terra todos os pecadores, deixem de existir para sempre os perversos. Todo o meu ser louve o SENHOR. Louvado seja o SENHOR!

'''

xref:019-salmos/019-salmos-103.adoc#v19-103-0[&#60; Capítulo Anterior] | <<v19-104-0,Topo>> | xref:019-salmos/019-salmos-105.adoc#v19-105-0[Próximo Capítulo &#62;]