include::./index.adoc[]

[[v19-73-0]]
=== Salmos, 73
// nvt ?, NVT - Nova Versão Transformadora

[[v19-73-1]]

^<<v19-73-1,1>>^ Certamente Deus é bom para Israel, para os que têm coração puro.

[[v19-73-2]]

^<<v19-73-2,2>>^ Quanto a mim, quase tropecei; meus pés escorregaram e quase caí.

[[v19-73-3]]

^<<v19-73-3,3>>^ Pois tive inveja dos orgulhosos quando os vi prosperar apesar de sua perversidade.

[[v19-73-4]]

^<<v19-73-4,4>>^ Levam uma vida sem sofrimento e têm o corpo saudável e forte.

[[v19-73-5]]

^<<v19-73-5,5>>^ Não enfrentam dificuldades, nem estão cheios de problemas, como os demais.

[[v19-73-6]]

^<<v19-73-6,6>>^ Ostentam o orgulho como um colar de pedras preciosas e vestem-se de crueldade.

[[v19-73-7]]

^<<v19-73-7,7>>^ Seus olhos cobiçam sempre mais, e o coração vive cheio de más intenções.

[[v19-73-8]]

^<<v19-73-8,8>>^ Zombam e falam somente maldades; em seu orgulho, ameaçam usar de violência.

[[v19-73-9]]

^<<v19-73-9,9>>^ Falam como se fossem donos dos céus, e suas palavras arrogantes percorrem a terra.

[[v19-73-10]]

^<<v19-73-10,10>>^ Por isso, o povo se volta para eles e bebe todas as suas palavras.

[[v19-73-11]]

^<<v19-73-11,11>>^ "O que Deus sabe?", perguntam. "Acaso o Altíssimo tem conhecimento disso?"

[[v19-73-12]]

^<<v19-73-12,12>>^ Vejam como os perversos desfrutam uma vida tranquila, enquanto suas riquezas se multiplicam.

[[v19-73-13]]

^<<v19-73-13,13>>^ Foi à toa que mantive o coração puro? Foi em vão que agi de modo íntegro?

[[v19-73-14]]

^<<v19-73-14,14>>^ O dia todo só enfrento problemas; cada manhã sou castigado.

[[v19-73-15]]

^<<v19-73-15,15>>^ Se eu tivesse falado como eles, teria traído teu povo.

[[v19-73-16]]

^<<v19-73-16,16>>^ Tentei compreender por que prosperam; que tarefa difícil!

[[v19-73-17]]

^<<v19-73-17,17>>^ Então, entrei em teu santuário, ó Deus, e por fim entendi o destino deles.

[[v19-73-18]]

^<<v19-73-18,18>>^ Tu os puseste num caminho escorregadio e os fizeste cair do precipício para a destruição.

[[v19-73-19]]

^<<v19-73-19,19>>^ São destruídos de repente, completamente tomados de pavor.

[[v19-73-20]]

^<<v19-73-20,20>>^ Quando te levantares, ó Senhor, rirás das ideias tolas deles, como quem ri de um sonho pela manhã.

[[v19-73-21]]

^<<v19-73-21,21>>^ Percebi, então, que meu coração se amargurou e que eu estava despedaçado por dentro.

[[v19-73-22]]

^<<v19-73-22,22>>^ Fui tolo e ignorante; a teus olhos devo ter parecido um animal irracional.

[[v19-73-23]]

^<<v19-73-23,23>>^ E, no entanto, ainda pertenço a ti; tu seguras minha mão direita.

[[v19-73-24]]

^<<v19-73-24,24>>^ Tu me guias com teu conselho e me conduzes a um destino glorioso.

[[v19-73-25]]

^<<v19-73-25,25>>^ Quem mais eu tenho no céu senão a ti? Eu te desejo mais que a qualquer coisa na terra.

[[v19-73-26]]

^<<v19-73-26,26>>^ Minha saúde pode acabar e meu espírito fraquejar, mas Deus continua sendo a força de meu coração; ele é minha possessão para sempre.

[[v19-73-27]]

^<<v19-73-27,27>>^ Os que te abandonam perecerão, pois destróis os que de ti se afastam.

[[v19-73-28]]

^<<v19-73-28,28>>^ Quanto a mim, como é bom estar perto de Deus! Fiz do SENHOR Soberano meu refúgio e anunciarei a todos tuas maravilhas.

'''

xref:019-salmos/019-salmos-072.adoc#v19-72-0[&#60; Capítulo Anterior] | <<v19-73-0,Topo>> | xref:019-salmos/019-salmos-074.adoc#v19-74-0[Próximo Capítulo &#62;]