include::./index.adoc[]

[[v19-88-0]]
=== Salmos, 88
// nvt ?, NVT - Nova Versão Transformadora

[[v19-88-1]]

^<<v19-88-1,1>>^ Ó SENHOR, Deus de minha salvação, clamo a ti de dia, venho a ti de noite.

[[v19-88-2]]

^<<v19-88-2,2>>^ Agora, ouve minha oração; escuta meu clamor.

[[v19-88-3]]

^<<v19-88-3,3>>^ Pois minha vida está cheia de problemas, e a morte se aproxima.

[[v19-88-4]]

^<<v19-88-4,4>>^ Fui considerado morto, alguém que já não tem forças.

[[v19-88-5]]

^<<v19-88-5,5>>^ Deixaram-me entre os mortos, estendido como um cadáver no túmulo. Caí no esquecimento e estou separado do teu cuidado.

[[v19-88-6]]

^<<v19-88-6,6>>^ Tu me lançaste na cova mais funda, nas profundezas mais escuras.

[[v19-88-7]]

^<<v19-88-7,7>>^ Tua ira pesa sobre mim; uma após a outra, tuas ondas me encobrem. Interlúdio

[[v19-88-8]]

^<<v19-88-8,8>>^ Afastaste de mim os meus amigos e para eles me tornaste repulsivo; estou preso numa armadilha, e não há como escapar.

[[v19-88-9]]

^<<v19-88-9,9>>^ As lágrimas de aflição me cegaram os olhos; todos os dias, clamo por ti, SENHOR, e a ti levanto as mãos.

[[v19-88-10]]

^<<v19-88-10,10>>^ Será que tuas maravilhas têm algum uso para os mortos? Acaso os mortos se levantam e te louvam? Interlúdio

[[v19-88-11]]

^<<v19-88-11,11>>^ Podem os que estão no túmulo anunciar teu amor? Podem proclamar tua fidelidade no lugar de destruição?

[[v19-88-12]]

^<<v19-88-12,12>>^ Acaso as trevas falam de tuas maravilhas? Pode alguém na terra do esquecimento contar de tua justiça?

[[v19-88-13]]

^<<v19-88-13,13>>^ A ti, SENHOR, eu clamo; dia após dia, continuarei a suplicar.

[[v19-88-14]]

^<<v19-88-14,14>>^ Ó SENHOR, por que me rejeitas? Por que escondes de mim o rosto?

[[v19-88-15]]

^<<v19-88-15,15>>^ Desde a juventude estive doente e à beira da morte; teus terrores me deixaram indefeso e desesperado.

[[v19-88-16]]

^<<v19-88-16,16>>^ Sim, tua ira intensa me esmagou, teus terrores acabaram comigo.

[[v19-88-17]]

^<<v19-88-17,17>>^ O dia todo, agitam-se ao meu redor como uma inundação e me encobrem por completo.

[[v19-88-18]]

^<<v19-88-18,18>>^ Tiraste de mim meus companheiros e pessoas queridas; a escuridão é a minha amiga mais chegada.

'''

xref:019-salmos/019-salmos-087.adoc#v19-87-0[&#60; Capítulo Anterior] | <<v19-88-0,Topo>> | xref:019-salmos/019-salmos-089.adoc#v19-89-0[Próximo Capítulo &#62;]