include::./index.adoc[]

[[v19-41-0]]
=== Salmos, 41
// nvt ?, NVT - Nova Versão Transformadora

[[v19-41-1]]

^<<v19-41-1,1>>^ Como é feliz aquele que se importa com o pobre! Em tempos de aflição, o SENHOR o livra.

[[v19-41-2]]

^<<v19-41-2,2>>^ O SENHOR o protege e lhe conserva a vida. Ele o faz prosperar na terra e o livra de seus inimigos.

[[v19-41-3]]

^<<v19-41-3,3>>^ O SENHOR cuida dele quando fica doente e lhe restaura a saúde.

[[v19-41-4]]

^<<v19-41-4,4>>^ Orei: "Ó SENHOR, tem misericórdia de mim! Cura-me, pois pequei contra ti!".

[[v19-41-5]]

^<<v19-41-5,5>>^ Meus inimigos, porém, só falam mal de mim: "Quando ele morrerá e será esquecido?".

[[v19-41-6]]

^<<v19-41-6,6>>^ Visitam-me como se fossem meus amigos, mas todo o tempo reúnem calúnias contra mim e depois as espalham por aí.

[[v19-41-7]]

^<<v19-41-7,7>>^ Todos que me odeiam falam de mim em sussurros e imaginam o pior.

[[v19-41-8]]

^<<v19-41-8,8>>^ "Ele está com uma doença mortal", dizem, "nunca mais se levantará da cama!"

[[v19-41-9]]

^<<v19-41-9,9>>^ Até meu melhor amigo, em quem eu confiava e com quem repartia meu pão, voltou-se contra mim.

[[v19-41-10]]

^<<v19-41-10,10>>^ SENHOR, tem misericórdia de mim! Devolve-me a saúde, para que eu lhes dê o que merecem.

[[v19-41-11]]

^<<v19-41-11,11>>^ Sei que te agradas de mim, pois não deixaste que meus inimigos triunfassem.

[[v19-41-12]]

^<<v19-41-12,12>>^ Preservaste minha vida porque sou inocente e trouxeste-me à tua presença para sempre.

[[v19-41-13]]

^<<v19-41-13,13>>^ Louvado seja o SENHOR, o Deus de Israel, de eternidade a eternidade. Amém e amém!

'''

xref:019-salmos/019-salmos-040.adoc#v19-40-0[&#60; Capítulo Anterior] | <<v19-41-0,Topo>> | xref:019-salmos/019-salmos-042.adoc#v19-42-0[Próximo Capítulo &#62;]