include::./index.adoc[]

[[v19-111-0]]
=== Salmos, 111
// nvt ?, NVT - Nova Versão Transformadora

[[v19-111-1]]

^<<v19-111-1,1>>^ Louvado seja o SENHOR! De todo o meu coração darei graças ao Senhor quando me reunir com os justos.

[[v19-111-2]]

^<<v19-111-2,2>>^ Como são grandiosas as obras do SENHOR! Todos que têm prazer nele devem nelas meditar.

[[v19-111-3]]

^<<v19-111-3,3>>^ Tudo que ele faz revela sua glória e majestade; sua justiça permanece para sempre.

[[v19-111-4]]

^<<v19-111-4,4>>^ Ele nos faz recordar suas maravilhas; o SENHOR é compassivo e misericordioso.

[[v19-111-5]]

^<<v19-111-5,5>>^ Dá alimento aos que o temem, lembra-se sempre de sua aliança.

[[v19-111-6]]

^<<v19-111-6,6>>^ Mostrou seu poder ao seu povo ao lhe dar as terras de outras nações.

[[v19-111-7]]

^<<v19-111-7,7>>^ Tudo que ele faz é justo e bom; todos os seus mandamentos são confiáveis.

[[v19-111-8]]

^<<v19-111-8,8>>^ São verdadeiros para sempre; devem ser obedecidos com fidelidade e retidão.

[[v19-111-9]]

^<<v19-111-9,9>>^ Ele pagou o resgate por seu povo, garantiu para sempre sua aliança com eles; seu nome é santo e temível!

[[v19-111-10]]

^<<v19-111-10,10>>^ O temor do SENHOR é o princípio do conhecimento; todos que obedecem a seus mandamentos mostram bom senso. Louvem-no para sempre!

'''

xref:019-salmos/019-salmos-110.adoc#v19-110-0[&#60; Capítulo Anterior] | <<v19-111-0,Topo>> | xref:019-salmos/019-salmos-112.adoc#v19-112-0[Próximo Capítulo &#62;]