include::./index.adoc[]

[[v19-9-0]]
=== Salmos, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v19-9-1]]

^<<v19-9-1,1>>^ Eu te louvarei, SENHOR, de todo o meu coração; anunciarei as maravilhas que fizeste.

[[v19-9-2]]

^<<v19-9-2,2>>^ Por causa de ti, me alegrarei e celebrarei; cantarei louvores ao teu nome, ó Altíssimo.

[[v19-9-3]]

^<<v19-9-3,3>>^ Meus inimigos recuaram; tropeçaram e morreram diante de tua presença.

[[v19-9-4]]

^<<v19-9-4,4>>^ Pois julgaste meu direito e minha causa; de teu trono julgaste com justiça.

[[v19-9-5]]

^<<v19-9-5,5>>^ Repreendeste as nações e destruíste os perversos; apagaste o nome deles de uma vez por todas.

[[v19-9-6]]

^<<v19-9-6,6>>^ O inimigo está acabado, arruinado para sempre; arrasaste suas cidades e elas caíram em esquecimento.

[[v19-9-7]]

^<<v19-9-7,7>>^ O SENHOR, porém, reina para sempre; de seu trono, executa o julgamento.

[[v19-9-8]]

^<<v19-9-8,8>>^ Julgará o mundo com justiça e governará as nações com imparcialidade.

[[v19-9-9]]

^<<v19-9-9,9>>^ O SENHOR é abrigo para os oprimidos, refúgio em tempos de aflição.

[[v19-9-10]]

^<<v19-9-10,10>>^ Quem conhece teu nome confia em ti, pois tu, SENHOR, não abandonas quem te busca.

[[v19-9-11]]

^<<v19-9-11,11>>^ Cantem louvores ao SENHOR, que reina em Sião; anunciem ao mundo seus feitos.

[[v19-9-12]]

^<<v19-9-12,12>>^ Pois aquele que vinga o sangue derramado não se esquece dos aflitos; ele não ignora seu clamor.

[[v19-9-13]]

^<<v19-9-13,13>>^ SENHOR, tem misericórdia de mim! Vê como meus inimigos me atormentam e livra-me das garras da morte.

[[v19-9-14]]

^<<v19-9-14,14>>^ Salva-me, para que eu te louve às portas de Jerusalém; para que eu me alegre por teu resgate.

[[v19-9-15]]

^<<v19-9-15,15>>^ As nações caíram na cova que abriram; seus pés ficaram presos no laço que esconderam.

[[v19-9-16]]

^<<v19-9-16,16>>^ O SENHOR é conhecido por sua justiça; os perversos são pegos nas próprias armadilhas. Interlúdio silencioso

[[v19-9-17]]

^<<v19-9-17,17>>^ Os perversos descerão à sepultura; esse é o destino de todas as nações que se esquecem de Deus.

[[v19-9-18]]

^<<v19-9-18,18>>^ O necessitado, porém, não será esquecido para sempre; a esperança dos pobres nunca mais será frustrada.

[[v19-9-19]]

^<<v19-9-19,19>>^ Levanta-te, SENHOR! Não permitas que simples mortais te desafiem! Julga as nações!

[[v19-9-20]]

^<<v19-9-20,20>>^ Faze-as tremer de medo, SENHOR; que as nações saibam que não passam de simples mortais. Interlúdio

'''

xref:019-salmos/019-salmos-008.adoc#v19-8-0[&#60; Capítulo Anterior] | <<v19-9-0,Topo>> | xref:019-salmos/019-salmos-010.adoc#v19-10-0[Próximo Capítulo &#62;]