include::./index.adoc[]

[[v19-122-0]]
=== Salmos, 122
// nvt ?, NVT - Nova Versão Transformadora

[[v19-122-1]]

^<<v19-122-1,1>>^ Alegrei-me quando me disseram: "Vamos à casa do SENHOR".

[[v19-122-2]]

^<<v19-122-2,2>>^ Agora estamos aqui, junto às suas portas, ó Jerusalém.

[[v19-122-3]]

^<<v19-122-3,3>>^ Jerusalém é cidade bem construída, com muros firmes e compactos.

[[v19-122-4]]

^<<v19-122-4,4>>^ Todas as tribos de Israel, o povo do SENHOR, sobem para cá. Vêm para dar graças ao nome do SENHOR, conforme a lei requer.

[[v19-122-5]]

^<<v19-122-5,5>>^ Aqui estão os tronos de onde se pronunciam julgamentos, os tronos da dinastia de Davi.

[[v19-122-6]]

^<<v19-122-6,6>>^ Orem pela paz de Jerusalém; sejam prósperos todos que amam esta cidade.

[[v19-122-7]]

^<<v19-122-7,7>>^ Que haja paz dentro de seus muros e prosperidade em seus palácios.

[[v19-122-8]]

^<<v19-122-8,8>>^ Em favor de minha família e amigos, direi: "Que você tenha paz, ó Jerusalém!".

[[v19-122-9]]

^<<v19-122-9,9>>^ Em favor da casa do SENHOR, nosso Deus, buscarei o seu bem.

'''

xref:019-salmos/019-salmos-121.adoc#v19-121-0[&#60; Capítulo Anterior] | <<v19-122-0,Topo>> | xref:019-salmos/019-salmos-123.adoc#v19-123-0[Próximo Capítulo &#62;]