include::./index.adoc[]

[[v19-47-0]]
=== Salmos, 47
// nvt ?, NVT - Nova Versão Transformadora

[[v19-47-1]]

^<<v19-47-1,1>>^ Batam palmas, todos os povos! Celebrem a Deus em alta voz!

[[v19-47-2]]

^<<v19-47-2,2>>^ Pois o SENHOR Altíssimo é temível; é o grande Rei de toda a terra.

[[v19-47-3]]

^<<v19-47-3,3>>^ Ele derrota os povos diante de nós e põe as nações sob nossos pés.

[[v19-47-4]]

^<<v19-47-4,4>>^ Escolheu para nós uma terra como herança, o orgulho dos descendentes de Jacó, a quem ele ama. Interlúdio

[[v19-47-5]]

^<<v19-47-5,5>>^ Deus subiu em meio a gritos de alegria; o SENHOR se elevou ao forte som de trombetas.

[[v19-47-6]]

^<<v19-47-6,6>>^ Cantem louvores a Deus, cantem louvores, cantem louvores ao nosso Rei, cantem louvores!

[[v19-47-7]]

^<<v19-47-7,7>>^ Pois Deus é o Rei de toda a terra; louvem-no com um salmo.

[[v19-47-8]]

^<<v19-47-8,8>>^ Deus reina sobre as nações, sentado em seu santo trono.

[[v19-47-9]]

^<<v19-47-9,9>>^ Os governantes do mundo se juntaram ao povo do Deus de Abraão. Pois todos os reis da terra pertencem a Deus; ele é grandemente exaltado em toda parte.

'''

xref:019-salmos/019-salmos-046.adoc#v19-46-0[&#60; Capítulo Anterior] | <<v19-47-0,Topo>> | xref:019-salmos/019-salmos-048.adoc#v19-48-0[Próximo Capítulo &#62;]