include::./index.adoc[]

[[v19-6-0]]
=== Salmos, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v19-6-1]]

^<<v19-6-1,1>>^ Ó SENHOR, não me repreendas em tua ira, nem me disciplines em tua fúria.

[[v19-6-2]]

^<<v19-6-2,2>>^ Tem compaixão de mim, SENHOR, pois estou fraco; cura-me, SENHOR, pois meus ossos agonizam.

[[v19-6-3]]

^<<v19-6-3,3>>^ Meu coração está muito angustiado; SENHOR, quando virás me restaurar?

[[v19-6-4]]

^<<v19-6-4,4>>^ Volta-te, SENHOR, e livra-me! Salva-me por causa do teu amor.

[[v19-6-5]]

^<<v19-6-5,5>>^ Pois os mortos não se lembram de ti; quem te louvará da sepultura?

[[v19-6-6]]

^<<v19-6-6,6>>^ Estou exausto de tanto gemer; à noite inundo a cama de tanto chorar, e de lágrimas a encharco.

[[v19-6-7]]

^<<v19-6-7,7>>^ A tristeza me embaça a vista; meus olhos estão cansados por causa de todos os meus inimigos.

[[v19-6-8]]

^<<v19-6-8,8>>^ Afastem-se de mim, todos vocês que praticam o mal, pois o SENHOR ouviu meu pranto.

[[v19-6-9]]

^<<v19-6-9,9>>^ O SENHOR ouviu minha súplica; o SENHOR responderá à minha oração.

[[v19-6-10]]

^<<v19-6-10,10>>^ Sejam humilhados e aterrorizados todos os meus inimigos; recuem de repente, envergonhados.

'''

xref:019-salmos/019-salmos-005.adoc#v19-5-0[&#60; Capítulo Anterior] | <<v19-6-0,Topo>> | xref:019-salmos/019-salmos-007.adoc#v19-7-0[Próximo Capítulo &#62;]