include::./index.adoc[]

[[v19-146-0]]
=== Salmos, 146
// nvt ?, NVT - Nova Versão Transformadora

[[v19-146-1]]

^<<v19-146-1,1>>^ Louvado seja o SENHOR! Que todo o meu ser louve o SENHOR.

[[v19-146-2]]

^<<v19-146-2,2>>^ Louvarei o SENHOR enquanto eu viver; cantarei a meu Deus até o último suspiro.

[[v19-146-3]]

^<<v19-146-3,3>>^ Não confiem nos poderosos; não é neles que encontrarão salvação.

[[v19-146-4]]

^<<v19-146-4,4>>^ Quando sua vida se vai, voltam ao pó, e todos os seus planos morrem com eles.

[[v19-146-5]]

^<<v19-146-5,5>>^ Como são felizes os que têm o Deus de Jacó como seu auxílio, os que põem sua esperança no SENHOR, seu Deus.

[[v19-146-6]]

^<<v19-146-6,6>>^ Ele fez os céus e a terra, o mar e tudo que neles há; ele cumpre suas promessas para sempre.

[[v19-146-7]]

^<<v19-146-7,7>>^ Faz justiça aos oprimidos e alimenta os famintos. O SENHOR liberta os prisioneiros.

[[v19-146-8]]

^<<v19-146-8,8>>^ O SENHOR abre os olhos dos cegos. O SENHOR levanta os abatidos. O SENHOR ama os justos.

[[v19-146-9]]

^<<v19-146-9,9>>^ O SENHOR protege os estrangeiros e cuida dos órfãos e das viúvas, mas frustra os planos dos perversos.

[[v19-146-10]]

^<<v19-146-10,10>>^ O SENHOR reinará para sempre; ele será seu Deus, ó Sião, por todas as gerações. Louvado seja o SENHOR!

'''

xref:019-salmos/019-salmos-145.adoc#v19-145-0[&#60; Capítulo Anterior] | <<v19-146-0,Topo>> | xref:019-salmos/019-salmos-147.adoc#v19-147-0[Próximo Capítulo &#62;]