include::./index.adoc[]

[[v19-136-0]]
=== Salmos, 136
// nvt ?, NVT - Nova Versão Transformadora

[[v19-136-1]]

^<<v19-136-1,1>>^ Deem graças ao SENHOR, porque ele é bom. Seu amor dura para sempre!

[[v19-136-2]]

^<<v19-136-2,2>>^ Deem graças ao Deus dos deuses. Seu amor dura para sempre!

[[v19-136-3]]

^<<v19-136-3,3>>^ Deem graças ao Senhor dos senhores. Seu amor dura para sempre!

[[v19-136-4]]

^<<v19-136-4,4>>^ Deem graças ao único que realiza grandes maravilhas. Seu amor dura para sempre!

[[v19-136-5]]

^<<v19-136-5,5>>^ Deem graças àquele que criou os céus com muita habilidade. Seu amor dura para sempre!

[[v19-136-6]]

^<<v19-136-6,6>>^ Deem graças àquele que colocou a terra no meio das águas. Seu amor dura para sempre!

[[v19-136-7]]

^<<v19-136-7,7>>^ Deem graças àquele que fez as luzes celestes: Seu amor dura para sempre!

[[v19-136-8]]

^<<v19-136-8,8>>^ o sol para governar o dia, Seu amor dura para sempre!

[[v19-136-9]]

^<<v19-136-9,9>>^ a lua e as estrelas para governarem a noite. Seu amor dura para sempre!

[[v19-136-10]]

^<<v19-136-10,10>>^ Deem graças àquele que matou os filhos mais velhos dos egípcios. Seu amor dura para sempre!

[[v19-136-11]]

^<<v19-136-11,11>>^ Ele tirou Israel do Egito. Seu amor dura para sempre!

[[v19-136-12]]

^<<v19-136-12,12>>^ Agiu com mão forte e braço poderoso. Seu amor dura para sempre!

[[v19-136-13]]

^<<v19-136-13,13>>^ Deem graças àquele que abriu o mar Vermelho ao meio. Seu amor dura para sempre!

[[v19-136-14]]

^<<v19-136-14,14>>^ Fez Israel atravessá-lo a salvo, Seu amor dura para sempre!

[[v19-136-15]]

^<<v19-136-15,15>>^ mas lançou o faraó e seu exército no mar Vermelho. Seu amor dura para sempre!

[[v19-136-16]]

^<<v19-136-16,16>>^ Deem graças àquele que guiou seu povo pelo deserto. Seu amor dura para sempre!

[[v19-136-17]]

^<<v19-136-17,17>>^ Deem graças àquele que feriu mortalmente grandes reis. Seu amor dura para sempre!

[[v19-136-18]]

^<<v19-136-18,18>>^ Ele matou reis poderosos: Seu amor dura para sempre!

[[v19-136-19]]

^<<v19-136-19,19>>^ Seom, rei dos amorreus, Seu amor dura para sempre!

[[v19-136-20]]

^<<v19-136-20,20>>^ e Ogue, rei de Basã. Seu amor dura para sempre!

[[v19-136-21]]

^<<v19-136-21,21>>^ Entregou a terra desses reis como herança, Seu amor dura para sempre!

[[v19-136-22]]

^<<v19-136-22,22>>^ sim, como herança a seu servo, Israel. Seu amor dura para sempre!

[[v19-136-23]]

^<<v19-136-23,23>>^ Ele se lembrou de nós em nossa humilhação. Seu amor dura para sempre!

[[v19-136-24]]

^<<v19-136-24,24>>^ Livrou-nos de nossos inimigos. Seu amor dura para sempre!

[[v19-136-25]]

^<<v19-136-25,25>>^ Ele dá alimento a todos os seres vivos. Seu amor dura para sempre!

[[v19-136-26]]

^<<v19-136-26,26>>^ Deem graças ao Deus dos céus. Seu amor dura para sempre!

'''

xref:019-salmos/019-salmos-135.adoc#v19-135-0[&#60; Capítulo Anterior] | <<v19-136-0,Topo>> | xref:019-salmos/019-salmos-137.adoc#v19-137-0[Próximo Capítulo &#62;]