include::./index.adoc[]

[[v19-25-0]]
=== Salmos, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v19-25-1]]

^<<v19-25-1,1>>^ Ó SENHOR, a ti entrego minha vida;

[[v19-25-2]]

^<<v19-25-2,2>>^ confio em ti, meu Deus! Não permitas que eu seja envergonhado, nem que meus inimigos se alegrem com minha derrota.

[[v19-25-3]]

^<<v19-25-3,3>>^ Quem confia em ti jamais será envergonhado, mas os que buscam enganar o próximo serão envergonhados.

[[v19-25-4]]

^<<v19-25-4,4>>^ Mostra-me o caminho certo, SENHOR, ensina-me por onde devo andar.

[[v19-25-5]]

^<<v19-25-5,5>>^ Guia-me pela tua verdade e ensina-me, pois és o Deus que me salva; em ti ponho minha esperança todo o dia.

[[v19-25-6]]

^<<v19-25-6,6>>^ Lembra-te, SENHOR, de tua compaixão e de teu amor, que tens mostrado desde tempos antigos.

[[v19-25-7]]

^<<v19-25-7,7>>^ Não te lembres dos pecados e da rebeldia de minha juventude; lembra-te de mim segundo o teu amor, pois és misericordioso, ó SENHOR.

[[v19-25-8]]

^<<v19-25-8,8>>^ O SENHOR é bom e justo; mostra o caminho correto aos que se desviam.

[[v19-25-9]]

^<<v19-25-9,9>>^ Guia os humildes na justiça e ensina-lhes seu caminho.

[[v19-25-10]]

^<<v19-25-10,10>>^ O SENHOR conduz com amor e fidelidade a todos que cumprem sua aliança e obedecem a seus preceitos.

[[v19-25-11]]

^<<v19-25-11,11>>^ Por causa do teu nome, ó SENHOR, perdoa meus pecados, que são muitos.

[[v19-25-12]]

^<<v19-25-12,12>>^ Quem são os que temem o SENHOR? Ele lhes mostrará o caminho que devem escolher.

[[v19-25-13]]

^<<v19-25-13,13>>^ Viverão em prosperidade, e seus filhos herdarão a terra.

[[v19-25-14]]

^<<v19-25-14,14>>^ O SENHOR é amigo dos que o temem; ele lhes ensina sua aliança.

[[v19-25-15]]

^<<v19-25-15,15>>^ Meus olhos estão sempre voltados para o SENHOR, pois ele livra meus pés de armadilhas.

[[v19-25-16]]

^<<v19-25-16,16>>^ Volta-te para mim e tem misericórdia, pois estou sozinho e aflito.

[[v19-25-17]]

^<<v19-25-17,17>>^ Meus problemas só aumentam; livra-me de toda a minha angústia!

[[v19-25-18]]

^<<v19-25-18,18>>^ Atenta para minha dor e para meu sofrimento; perdoa todos os meus pecados.

[[v19-25-19]]

^<<v19-25-19,19>>^ Vê quantos inimigos tenho e a crueldade com que me odeiam.

[[v19-25-20]]

^<<v19-25-20,20>>^ Protege minha vida e livra-me! Não permitas que eu seja envergonhado, pois em ti me refugio.

[[v19-25-21]]

^<<v19-25-21,21>>^ Que a integridade e a retidão me guardem, pois em ti ponho minha esperança.

[[v19-25-22]]

^<<v19-25-22,22>>^ Ó Deus, resgata Israel de todas as suas angústias.

'''

xref:019-salmos/019-salmos-024.adoc#v19-24-0[&#60; Capítulo Anterior] | <<v19-25-0,Topo>> | xref:019-salmos/019-salmos-026.adoc#v19-26-0[Próximo Capítulo &#62;]