include::./index.adoc[]

[[v19-33-0]]
=== Salmos, 33
// nvt ?, NVT - Nova Versão Transformadora

[[v19-33-1]]

^<<v19-33-1,1>>^ Cantem de alegria ao SENHOR, vocês que são justos; é apropriado que os íntegros o louvem.

[[v19-33-2]]

^<<v19-33-2,2>>^ Celebrem ao SENHOR com melodias da harpa, toquem música para ele com instrumento de dez cordas.

[[v19-33-3]]

^<<v19-33-3,3>>^ Entoem para ele um novo cântico, toquem com habilidade e cantem com alegria.

[[v19-33-4]]

^<<v19-33-4,4>>^ Pois a palavra do SENHOR é verdadeira e podemos confiar em tudo que ele faz.

[[v19-33-5]]

^<<v19-33-5,5>>^ Ele ama o que é justo e bom; o amor do SENHOR enche a terra.

[[v19-33-6]]

^<<v19-33-6,6>>^ O SENHOR falou, e os céus foram criados; pelo sopro de sua boca as estrelas nasceram.

[[v19-33-7]]

^<<v19-33-7,7>>^ Determinou os limites do mar e juntou os oceanos em reservatórios.

[[v19-33-8]]

^<<v19-33-8,8>>^ Que o mundo inteiro tema o SENHOR, e todos os habitantes da terra tremam diante dele.

[[v19-33-9]]

^<<v19-33-9,9>>^ Pois, quando ele falou, o mundo veio a existir; tudo surgiu por sua ordem.

[[v19-33-10]]

^<<v19-33-10,10>>^ O SENHOR desfaz os planos das nações e frustra os projetos dos povos.

[[v19-33-11]]

^<<v19-33-11,11>>^ Mas os planos do SENHOR permanecem para sempre; seus propósitos jamais serão abalados.

[[v19-33-12]]

^<<v19-33-12,12>>^ Como é feliz a nação cujo Deus é o SENHOR, cujo povo ele escolheu para lhe pertencer!

[[v19-33-13]]

^<<v19-33-13,13>>^ O SENHOR olha dos céus e vê toda a humanidade.

[[v19-33-14]]

^<<v19-33-14,14>>^ De seu trono ele observa todos os habitantes da terra.

[[v19-33-15]]

^<<v19-33-15,15>>^ Formou o coração de cada um; por isso, entende tudo que fazem.

[[v19-33-16]]

^<<v19-33-16,16>>^ Nem mesmo um poderoso exército pode salvar um rei; grande força não é suficiente para livrar um guerreiro.

[[v19-33-17]]

^<<v19-33-17,17>>^ Não confie em seu cavalo de guerra para obter vitória; apesar de toda a sua força, ele não é capaz de salvá-lo.

[[v19-33-18]]

^<<v19-33-18,18>>^ O SENHOR, porém, está atento aos que o temem, aos que esperam por seu amor.

[[v19-33-19]]

^<<v19-33-19,19>>^ Ele os livra da morte e os conserva com vida em tempos de fome.

[[v19-33-20]]

^<<v19-33-20,20>>^ Nossa esperança está no SENHOR; ele é nosso auxílio e nosso escudo.

[[v19-33-21]]

^<<v19-33-21,21>>^ Nele nosso coração se alegra, pois confiamos em seu santo nome.

[[v19-33-22]]

^<<v19-33-22,22>>^ Que o teu amor nos cerque, SENHOR, pois só em ti temos esperança.

'''

xref:019-salmos/019-salmos-032.adoc#v19-32-0[&#60; Capítulo Anterior] | <<v19-33-0,Topo>> | xref:019-salmos/019-salmos-034.adoc#v19-34-0[Próximo Capítulo &#62;]