include::./index.adoc[]

[[v19-7-0]]
=== Salmos, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v19-7-1]]

^<<v19-7-1,1>>^ Em ti me refugio, SENHOR, meu Deus; salva-me dos que me perseguem e livra-me!

[[v19-7-2]]

^<<v19-7-2,2>>^ Do contrário, eles me atacarão como leões e me despedaçarão, sem que ninguém me resgate.

[[v19-7-3]]

^<<v19-7-3,3>>^ Ó SENHOR, meu Deus, se fiz o mal, se cometi alguma injustiça,

[[v19-7-4]]

^<<v19-7-4,4>>^ se traí um amigo ou saqueei meu adversário sem razão,

[[v19-7-5]]

^<<v19-7-5,5>>^ que meus inimigos me persigam e capturem; que me pisoteiem no chão e no pó arrastem minha honra. Interlúdio

[[v19-7-6]]

^<<v19-7-6,6>>^ Levanta-te, SENHOR, em tua ira! Ergue-te contra a fúria de meus inimigos! Desperta, meu Deus, e faz justiça!

[[v19-7-7]]

^<<v19-7-7,7>>^ Reúne as nações diante de ti e toma teu lugar de autoridade sobre elas.

[[v19-7-8]]

^<<v19-7-8,8>>^ O SENHOR julga as nações; declara-me justo, ó SENHOR, pois sou inocente, ó Altíssimo!

[[v19-7-9]]

^<<v19-7-9,9>>^ Faz cessar a maldade dos perversos e dá segurança ao justo. Pois tu sondas a mente e o coração, ó Deus justo.

[[v19-7-10]]

^<<v19-7-10,10>>^ Deus é meu escudo; ele salva os que têm coração íntegro.

[[v19-7-11]]

^<<v19-7-11,11>>^ Deus é justo juiz; todos os dias ele mostra sua ira contra os perversos.

[[v19-7-12]]

^<<v19-7-12,12>>^ Se eles não se arrependerem, Deus afiará sua espada; armará seu arco para disparar,

[[v19-7-13]]

^<<v19-7-13,13>>^ preparará suas armas mortais e acenderá suas flechas com fogo.

[[v19-7-14]]

^<<v19-7-14,14>>^ Sim, o perverso gera o mal; concebe o sofrimento e dá à luz a mentira.

[[v19-7-15]]

^<<v19-7-15,15>>^ Abre uma cova profunda, mas ele próprio cai em sua armadilha.

[[v19-7-16]]

^<<v19-7-16,16>>^ Sua maldade se volta contra ele; sua violência lhe cai sobre a cabeça.

[[v19-7-17]]

^<<v19-7-17,17>>^ Darei graças ao SENHOR porque ele é justo; cantarei louvores ao nome do SENHOR Altíssimo.

'''

xref:019-salmos/019-salmos-006.adoc#v19-6-0[&#60; Capítulo Anterior] | <<v19-7-0,Topo>> | xref:019-salmos/019-salmos-008.adoc#v19-8-0[Próximo Capítulo &#62;]