include::./index.adoc[]

[[v19-138-0]]
=== Salmos, 138
// nvt ?, NVT - Nova Versão Transformadora

[[v19-138-1]]

^<<v19-138-1,1>>^ Graças te dou, SENHOR, de todo o meu coração; cantarei louvores a ti diante dos deuses.

[[v19-138-2]]

^<<v19-138-2,2>>^ Prostro-me diante do teu santo templo; louvo teu nome por teu amor e tua fidelidade, pois engradeceste acima de tudo teu nome e tua palavra.

[[v19-138-3]]

^<<v19-138-3,3>>^ Quando eu clamo, tu me respondes; coragem e força me dás.

[[v19-138-4]]

^<<v19-138-4,4>>^ Os reis de toda a terra te darão graças, SENHOR, pois todos eles ouvirão tuas palavras.

[[v19-138-5]]

^<<v19-138-5,5>>^ Sim, cantarão a respeito dos caminhos do SENHOR, pois a glória do SENHOR é grande.

[[v19-138-6]]

^<<v19-138-6,6>>^ Mesmo nas alturas, o SENHOR cuida dos humildes, mas mantém distância dos orgulhosos.

[[v19-138-7]]

^<<v19-138-7,7>>^ Ainda que eu esteja cercado de aflições, tu me protegerás da ira de meus inimigos. Estendes tua mão, e o poder de tua mão direita me liberta.

[[v19-138-8]]

^<<v19-138-8,8>>^ O SENHOR cumprirá seus planos para minha vida, pois teu amor, ó SENHOR, dura para sempre; não me abandones, pois tu me fizeste.

'''

xref:019-salmos/019-salmos-137.adoc#v19-137-0[&#60; Capítulo Anterior] | <<v19-138-0,Topo>> | xref:019-salmos/019-salmos-139.adoc#v19-139-0[Próximo Capítulo &#62;]