include::./index.adoc[]

[[v19-102-0]]
=== Salmos, 102
// nvt ?, NVT - Nova Versão Transformadora

[[v19-102-1]]

^<<v19-102-1,1>>^ SENHOR, ouve minha oração, escuta minha súplica!

[[v19-102-2]]

^<<v19-102-2,2>>^ Não escondas de mim o rosto na hora de minha aflição. Inclina-te para ouvir e responde-me depressa quando clamo a ti.

[[v19-102-3]]

^<<v19-102-3,3>>^ Pois meus dias somem como fumaça; como brasas ardentes, meus ossos queimam.

[[v19-102-4]]

^<<v19-102-4,4>>^ Meu coração está esgotado, secou-se como capim; até perdi o apetite.

[[v19-102-5]]

^<<v19-102-5,5>>^ Por causa de minha ansiedade, não passo de pele e osso.

[[v19-102-6]]

^<<v19-102-6,6>>^ Sou como a coruja no deserto, como a pequena coruja num lugar desolado.

[[v19-102-7]]

^<<v19-102-7,7>>^ Não consigo dormir; sou como o pássaro solitário no telhado.

[[v19-102-8]]

^<<v19-102-8,8>>^ Todos os dias meus inimigos me insultam; zombam de mim e me amaldiçoam.

[[v19-102-9]]

^<<v19-102-9,9>>^ As cinzas são meu alimento, e as lágrimas se misturam com minha bebida,

[[v19-102-10]]

^<<v19-102-10,10>>^ por causa de tua ira e de tua fúria, pois me levantaste e depois me lançaste fora.

[[v19-102-11]]

^<<v19-102-11,11>>^ Minha vida passa rápido, como as sombras que se vão; vou murchando, como o capim.

[[v19-102-12]]

^<<v19-102-12,12>>^ Tu, porém, SENHOR, reinarás para sempre; teu nome será lembrado por todas as gerações.

[[v19-102-13]]

^<<v19-102-13,13>>^ Tu te levantarás e terás misericórdia de Sião; já é tempo de lhe mostrar compaixão, este é o momento esperado.

[[v19-102-14]]

^<<v19-102-14,14>>^ Pois teus servos amam cada pedra de seus muros e estimam até mesmo o pó em suas ruas.

[[v19-102-15]]

^<<v19-102-15,15>>^ As nações temerão o nome do SENHOR, os reis da terra estremecerão diante de sua glória.

[[v19-102-16]]

^<<v19-102-16,16>>^ Pois o SENHOR reconstruirá Sião; ele aparecerá em sua glória.

[[v19-102-17]]

^<<v19-102-17,17>>^ Ouvirá as orações dos indefesos e não rejeitará suas súplicas.

[[v19-102-18]]

^<<v19-102-18,18>>^ Fique isto registrado para as gerações futuras, para que um povo ainda não criado louve o SENHOR.

[[v19-102-19]]

^<<v19-102-19,19>>^ Contem-lhes que o SENHOR olhou para baixo, de seu santuário celeste. Do alto olhou para a terra,

[[v19-102-20]]

^<<v19-102-20,20>>^ para ouvir o gemido dos prisioneiros, para libertar os condenados à morte.

[[v19-102-21]]

^<<v19-102-21,21>>^ Assim, o nome do SENHOR será proclamado em Sião, seu louvor, em Jerusalém,

[[v19-102-22]]

^<<v19-102-22,22>>^ quando os povos se reunirem e os reinos vierem para servir ao SENHOR.

[[v19-102-23]]

^<<v19-102-23,23>>^ No meio de minha vida, ele me tirou as forças e me encurtou os dias.

[[v19-102-24]]

^<<v19-102-24,24>>^ Mas eu clamei a ele: "Ó meu Deus, que vive para sempre, não tires minha vida enquanto ainda sou jovem!".

[[v19-102-25]]

^<<v19-102-25,25>>^ Muito tempo atrás, lançaste os fundamentos da terra e com as tuas mãos formaste os céus.

[[v19-102-26]]

^<<v19-102-26,26>>^ Eles deixarão de existir, mas tu permanecerás para sempre; eles se desgastarão, como roupa velha. Tu os trocarás, como se fossem vestuário, e os jogarás fora.

[[v19-102-27]]

^<<v19-102-27,27>>^ Tu, porém, és sempre o mesmo; teus dias jamais terão fim.

[[v19-102-28]]

^<<v19-102-28,28>>^ Os filhos de teus servos viverão em segurança, e seus descendentes prosperarão em tua presença.

'''

xref:019-salmos/019-salmos-101.adoc#v19-101-0[&#60; Capítulo Anterior] | <<v19-102-0,Topo>> | xref:019-salmos/019-salmos-103.adoc#v19-103-0[Próximo Capítulo &#62;]