include::./index.adoc[]

[[v19-129-0]]
=== Salmos, 129
// nvt ?, NVT - Nova Versão Transformadora

[[v19-129-1]]

^<<v19-129-1,1>>^ Desde minha juventude, meus inimigos me perseguem. Que todo o Israel diga:

[[v19-129-2]]

^<<v19-129-2,2>>^ Desde minha juventude, meus inimigos me perseguem, mas nunca me derrotaram.

[[v19-129-3]]

^<<v19-129-3,3>>^ Minhas costas estão cobertas de feridas, como os longos sulcos feitos pelo arado na terra.

[[v19-129-4]]

^<<v19-129-4,4>>^ O SENHOR, porém, é justo; ele me livrou das cordas dos perversos.

[[v19-129-5]]

^<<v19-129-5,5>>^ Recuem envergonhados e derrotados todos que odeiam Sião.

[[v19-129-6]]

^<<v19-129-6,6>>^ Sejam inúteis como o capim que cresce no telhado, que seca antes de crescer por inteiro,

[[v19-129-7]]

^<<v19-129-7,7>>^ capim que não é colhido pelo ceifeiro, deixado de lado por aquele que amarra os feixes.

[[v19-129-8]]

^<<v19-129-8,8>>^ Que ninguém que passar por eles diga: "O SENHOR os abençoe; nós os abençoamos em nome do SENHOR".

'''

xref:019-salmos/019-salmos-128.adoc#v19-128-0[&#60; Capítulo Anterior] | <<v19-129-0,Topo>> | xref:019-salmos/019-salmos-130.adoc#v19-130-0[Próximo Capítulo &#62;]