include::./index.adoc[]

[[v19-145-0]]
=== Salmos, 145
// nvt ?, NVT - Nova Versão Transformadora

[[v19-145-1]]

^<<v19-145-1,1>>^ Eu te exaltarei, meu Deus e Rei, louvarei teu nome para todo o sempre.

[[v19-145-2]]

^<<v19-145-2,2>>^ Todos os dias te louvarei, sim, louvarei teu nome para sempre.

[[v19-145-3]]

^<<v19-145-3,3>>^ Grande é o SENHOR! Ele é digno de muito louvor! É impossível medir sua grandeza.

[[v19-145-4]]

^<<v19-145-4,4>>^ Que cada geração conte a seus filhos sobre tuas obras e proclame teu poder.

[[v19-145-5]]

^<<v19-145-5,5>>^ Meditarei em teu majestoso e glorioso esplendor e em tuas maravilhas.

[[v19-145-6]]

^<<v19-145-6,6>>^ Todos falarão de teus feitos notáveis, e eu anunciarei tua grandeza.

[[v19-145-7]]

^<<v19-145-7,7>>^ Todos contarão a história de tua imensa bondade e cantarão de alegria sobre tua justiça.

[[v19-145-8]]

^<<v19-145-8,8>>^ O SENHOR é misericordioso e compassivo, lento para se irar e cheio de amor.

[[v19-145-9]]

^<<v19-145-9,9>>^ O SENHOR é bom para todos; derrama misericórdia sobre toda a sua criação.

[[v19-145-10]]

^<<v19-145-10,10>>^ Todas as tuas obras te darão graças, ó SENHOR, e teus fiéis te louvarão.

[[v19-145-11]]

^<<v19-145-11,11>>^ Falarão da glória do teu reino e proclamarão o teu poder.

[[v19-145-12]]

^<<v19-145-12,12>>^ Anunciarão teus feitos poderosos e a majestade e glória do teu reino.

[[v19-145-13]]

^<<v19-145-13,13>>^ Pois o teu reino é reino para sempre; tu governas por todas as gerações. O SENHOR sempre cumpre suas promessas; é bondoso em tudo que faz.

[[v19-145-14]]

^<<v19-145-14,14>>^ O SENHOR ajuda os que caíram e levanta os que estão encurvados sob o peso de suas cargas.

[[v19-145-15]]

^<<v19-145-15,15>>^ Os olhos de todos estão voltados para ti com esperança; tu lhes provês o alimento conforme necessitam.

[[v19-145-16]]

^<<v19-145-16,16>>^ Quando abres tua mão, satisfazes o anseio de todos os seres vivos.

[[v19-145-17]]

^<<v19-145-17,17>>^ O SENHOR é justo em tudo que faz; é cheio de bondade.

[[v19-145-18]]

^<<v19-145-18,18>>^ O SENHOR está perto de todos que o invocam, sim, de todos que o invocam com sinceridade.

[[v19-145-19]]

^<<v19-145-19,19>>^ Ele concede os desejos dos que o temem; ouve seus clamores e os livra.

[[v19-145-20]]

^<<v19-145-20,20>>^ O SENHOR protege todos que o amam, mas destrói os perversos.

[[v19-145-21]]

^<<v19-145-21,21>>^ Louvarei o SENHOR, e que todos na terra louvem seu santo nome, para todo o sempre!

'''

xref:019-salmos/019-salmos-144.adoc#v19-144-0[&#60; Capítulo Anterior] | <<v19-145-0,Topo>> | xref:019-salmos/019-salmos-146.adoc#v19-146-0[Próximo Capítulo &#62;]