include::./index.adoc[]

[[v19-135-0]]
=== Salmos, 135
// nvt ?, NVT - Nova Versão Transformadora

[[v19-135-1]]

^<<v19-135-1,1>>^ Louvado seja o SENHOR! Louvem o nome do SENHOR! Louvem-no vocês, servos do SENHOR,

[[v19-135-2]]

^<<v19-135-2,2>>^ vocês que servem na casa do SENHOR, nos pátios da casa de nosso Deus.

[[v19-135-3]]

^<<v19-135-3,3>>^ Louvem o SENHOR, porque o SENHOR é bom; celebrem seu nome amável com música.

[[v19-135-4]]

^<<v19-135-4,4>>^ Pois o SENHOR escolheu Jacó para si; Israel é seu tesouro especial.

[[v19-135-5]]

^<<v19-135-5,5>>^ Sim, conheço a grandeza do SENHOR; nosso Senhor é maior que qualquer outro deus.

[[v19-135-6]]

^<<v19-135-6,6>>^ O SENHOR faz tudo como deseja, nos céus e na terra, nos mares e em suas profundezas.

[[v19-135-7]]

^<<v19-135-7,7>>^ Faz as nuvens subirem sobre toda a terra, envia os relâmpagos que acompanham a chuva e manda o vento sair de seus depósitos.

[[v19-135-8]]

^<<v19-135-8,8>>^ Matou o filho mais velho de todos os lares egípcios, tanto das pessoas como dos animais.

[[v19-135-9]]

^<<v19-135-9,9>>^ Realizou sinais e maravilhas no Egito, contra o faraó e todo o seu povo.

[[v19-135-10]]

^<<v19-135-10,10>>^ Destruiu grandes nações e matou reis poderosos:

[[v19-135-11]]

^<<v19-135-11,11>>^ Seom, rei dos amorreus, Ogue, rei de Basã, e todos os reis de Canaã.

[[v19-135-12]]

^<<v19-135-12,12>>^ Entregou a terra deles como herança, sim, como herança a seu povo, Israel.

[[v19-135-13]]

^<<v19-135-13,13>>^ Teu nome, ó SENHOR, permanece para sempre; tua fama, ó SENHOR, é conhecida por todas as gerações.

[[v19-135-14]]

^<<v19-135-14,14>>^ Pois o SENHOR fará justiça ao seu povo e terá compaixão de seus servos.

[[v19-135-15]]

^<<v19-135-15,15>>^ Os ídolos das nações não passam de objetos de prata e de ouro, formados por mãos humanas.

[[v19-135-16]]

^<<v19-135-16,16>>^ Têm boca, mas não falam; olhos, mas não veem.

[[v19-135-17]]

^<<v19-135-17,17>>^ Têm ouvidos, mas não ouvem; em sua boca, não há fôlego de vida.

[[v19-135-18]]

^<<v19-135-18,18>>^ Aqueles que fazem ídolos e neles confiam são exatamente iguais a eles.

[[v19-135-19]]

^<<v19-135-19,19>>^ Ó Israel, louve o SENHOR! Ó sacerdotes, descendentes de Arão, louvem o SENHOR!

[[v19-135-20]]

^<<v19-135-20,20>>^ Ó levitas, louvem o SENHOR! Todos vocês que temem o SENHOR, louvem o SENHOR!

[[v19-135-21]]

^<<v19-135-21,21>>^ O SENHOR seja louvado desde Sião, pois ele habita em Jerusalém. Louvado seja o SENHOR!

'''

xref:019-salmos/019-salmos-134.adoc#v19-134-0[&#60; Capítulo Anterior] | <<v19-135-0,Topo>> | xref:019-salmos/019-salmos-136.adoc#v19-136-0[Próximo Capítulo &#62;]