include::./index.adoc[]

[[v19-24-0]]
=== Salmos, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v19-24-1]]

^<<v19-24-1,1>>^ A terra e tudo que nela há são do SENHOR; o mundo e todos os seus habitantes lhe pertencem.

[[v19-24-2]]

^<<v19-24-2,2>>^ Pois sobre os mares ele edificou os alicerces da terra e sobre as profundezas do oceano a estabeleceu.

[[v19-24-3]]

^<<v19-24-3,3>>^ Quem pode subir o monte do SENHOR? Quem pode permanecer em seu santo lugar?

[[v19-24-4]]

^<<v19-24-4,4>>^ Somente os que têm as mãos puras e o coração limpo, que não se entregam aos ídolos e não juram em falso.

[[v19-24-5]]

^<<v19-24-5,5>>^ Eles receberão a bênção do Senhor e a justiça do Deus de sua salvação.

[[v19-24-6]]

^<<v19-24-6,6>>^ São esses os que te buscam e adoram em tua presença, ó Deus de Jacó. Interlúdio

[[v19-24-7]]

^<<v19-24-7,7>>^ Abram-se, portões da cidade! Abram-se, antigos portais, para que entre o Rei da glória.

[[v19-24-8]]

^<<v19-24-8,8>>^ Quem é o Rei da glória? O SENHOR, forte e poderoso. O SENHOR, invencível nas batalhas.

[[v19-24-9]]

^<<v19-24-9,9>>^ Abram-se, portões da cidade! Abram-se, antigos portais, para que entre o Rei da glória.

[[v19-24-10]]

^<<v19-24-10,10>>^ Quem é o Rei da glória? O SENHOR dos Exércitos; ele é o Rei da glória.

'''

xref:019-salmos/019-salmos-023.adoc#v19-23-0[&#60; Capítulo Anterior] | <<v19-24-0,Topo>> | xref:019-salmos/019-salmos-025.adoc#v19-25-0[Próximo Capítulo &#62;]