include::./index.adoc[]

[[v19-95-0]]
=== Salmos, 95
// nvt ?, NVT - Nova Versão Transformadora

[[v19-95-1]]

^<<v19-95-1,1>>^ Venham, vamos cantar ao SENHOR! Vamos aclamar a Rocha de nossa salvação.

[[v19-95-2]]

^<<v19-95-2,2>>^ Vamos chegar diante dele com ações de graças e cantar a ele salmos de louvor.

[[v19-95-3]]

^<<v19-95-3,3>>^ Pois o SENHOR é o grande Deus, o grande Rei acima de todos os deuses.

[[v19-95-4]]

^<<v19-95-4,4>>^ Em suas mãos estão as profundezas da terra, a ele pertencem os mais altos montes.

[[v19-95-5]]

^<<v19-95-5,5>>^ O mar é dele, pois ele o criou; suas mãos formaram a terra firme.

[[v19-95-6]]

^<<v19-95-6,6>>^ Venham, vamos adorar e nos prostrar, vamos nos ajoelhar diante do SENHOR, nosso Criador,

[[v19-95-7]]

^<<v19-95-7,7>>^ pois ele é o nosso Deus. Somos o povo que ele pastoreia, o rebanho sob o seu cuidado. Quem dera hoje vocês ouvissem a voz do SENHOR!

[[v19-95-8]]

^<<v19-95-8,8>>^ Pois ele diz: "Não endureçam o coração, como fizeram seus antepassados em Meribá, como fizeram em Massá, no deserto.

[[v19-95-9]]

^<<v19-95-9,9>>^ Ali eles me tentaram e me puseram à prova, apesar de terem visto tudo que fiz.

[[v19-95-10]]

^<<v19-95-10,10>>^ Por quarenta anos estive irado com eles e disse: ‘São um povo cujo coração sempre se afasta de mim; recusam-se a andar em meus caminhos’.

[[v19-95-11]]

^<<v19-95-11,11>>^ Assim, jurei em minha ira: ‘Jamais entrarão em meu descanso’".

'''

xref:019-salmos/019-salmos-094.adoc#v19-94-0[&#60; Capítulo Anterior] | <<v19-95-0,Topo>> | xref:019-salmos/019-salmos-096.adoc#v19-96-0[Próximo Capítulo &#62;]