include::./index.adoc[]

[[v19-27-0]]
=== Salmos, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v19-27-1]]

^<<v19-27-1,1>>^ O SENHOR é minha luz e minha salvação; então, por que ter medo? O SENHOR é a fortaleza de minha vida; então, por que estremecer?

[[v19-27-2]]

^<<v19-27-2,2>>^ Quando os maus vierem para me destruir, quando meus inimigos e adversários me atacarem, eles tropeçarão e cairão.

[[v19-27-3]]

^<<v19-27-3,3>>^ Ainda que um exército me cerque, meu coração não temerá. Ainda que invistam contra mim, permanecerei confiante.

[[v19-27-4]]

^<<v19-27-4,4>>^ A única coisa que peço ao SENHOR, o meu maior desejo, é morar na casa do SENHOR todos os dias de minha vida, para contemplar a beleza do Senhor e meditar em seu templo.

[[v19-27-5]]

^<<v19-27-5,5>>^ Pois ali me abrigará em tempos de aflição e em seu santuário me esconderá; em segurança, numa rocha alta, me colocará.

[[v19-27-6]]

^<<v19-27-6,6>>^ Então manterei a cabeça erguida, acima dos inimigos que me cercam. Em seu santuário, oferecerei sacrifícios com gritos de alegria; cantarei e louvarei o SENHOR com música.

[[v19-27-7]]

^<<v19-27-7,7>>^ Ouve minha oração, ó SENHOR; tem compaixão e responde-me!

[[v19-27-8]]

^<<v19-27-8,8>>^ Meu coração ouviu tua voz dizer: "Venha e entre na minha presença", e meu coração respondeu: " SENHOR, eu irei!".

[[v19-27-9]]

^<<v19-27-9,9>>^ Não voltes as costas para mim; em tua ira, não rejeites teu servo. Sempre foste meu auxílio; não me deixes agora, não me abandones, ó Deus de minha salvação!

[[v19-27-10]]

^<<v19-27-10,10>>^ Mesmo que meu pai e minha mãe me abandonem, o SENHOR me acolherá.

[[v19-27-11]]

^<<v19-27-11,11>>^ Ensina-me a viver, SENHOR; guia-me pelo caminho certo, pois meus inimigos estão à minha espera.

[[v19-27-12]]

^<<v19-27-12,12>>^ Não permitas que eu caia nas mãos deles, pois me acusam de coisas que nunca fiz e me ameaçam, respirando violência.

[[v19-27-13]]

^<<v19-27-13,13>>^ Ainda assim, confio que verei a bondade do Senhor enquanto estiver aqui, na terra dos vivos.

[[v19-27-14]]

^<<v19-27-14,14>>^ Espere pelo Senhor e seja valente e corajoso; sim, espere pelo SENHOR.

'''

xref:019-salmos/019-salmos-026.adoc#v19-26-0[&#60; Capítulo Anterior] | <<v19-27-0,Topo>> | xref:019-salmos/019-salmos-028.adoc#v19-28-0[Próximo Capítulo &#62;]