include::./index.adoc[]

[[v19-115-0]]
=== Salmos, 115
// nvt ?, NVT - Nova Versão Transformadora

[[v19-115-1]]

^<<v19-115-1,1>>^ Não a nós, SENHOR, não a nós, mas ao teu nome seja toda a glória, por teu amor e por tua fidelidade.

[[v19-115-2]]

^<<v19-115-2,2>>^ Por que as nações dizem: "Onde está o deus deles?".

[[v19-115-3]]

^<<v19-115-3,3>>^ Nosso Deus está nos céus e faz tudo como deseja.

[[v19-115-4]]

^<<v19-115-4,4>>^ Seus ídolos não passam de objetos de prata e ouro, formados por mãos humanas.

[[v19-115-5]]

^<<v19-115-5,5>>^ Têm boca, mas não falam; olhos, mas não veem.

[[v19-115-6]]

^<<v19-115-6,6>>^ Têm ouvidos, mas não ouvem; nariz, mas não respiram.

[[v19-115-7]]

^<<v19-115-7,7>>^ Têm mãos, mas não apalpam; pés, mas não andam; garganta, mas não emitem som.

[[v19-115-8]]

^<<v19-115-8,8>>^ Aqueles que fazem ídolos e neles confiam são exatamente iguais a eles.

[[v19-115-9]]

^<<v19-115-9,9>>^ Ó Israel, confie no SENHOR; ele é seu auxílio e seu escudo!

[[v19-115-10]]

^<<v19-115-10,10>>^ Ó sacerdotes, descendentes de Arão, confiem no SENHOR; ele é seu auxílio e seu escudo!

[[v19-115-11]]

^<<v19-115-11,11>>^ Todos vocês que temem o SENHOR, confiem nele; ele é seu auxílio e seu escudo!

[[v19-115-12]]

^<<v19-115-12,12>>^ O SENHOR se lembra de nós e nos abençoará; sim, abençoará o povo de Israel e os sacerdotes, descendentes de Arão.

[[v19-115-13]]

^<<v19-115-13,13>>^ Abençoará os que temem o SENHOR, tanto os grandes como os pequenos.

[[v19-115-14]]

^<<v19-115-14,14>>^ Que o SENHOR multiplique bênçãos para vocês e seus filhos.

[[v19-115-15]]

^<<v19-115-15,15>>^ Sejam abençoados pelo SENHOR, que fez os céus e a terra.

[[v19-115-16]]

^<<v19-115-16,16>>^ Os céus pertencem ao SENHOR, mas ele deu a terra à humanidade.

[[v19-115-17]]

^<<v19-115-17,17>>^ Os mortos não cantam louvores ao SENHOR, pois desceram ao silêncio da sepultura.

[[v19-115-18]]

^<<v19-115-18,18>>^ Nós, porém, louvaremos o Senhor agora e para sempre. Louvado seja o SENHOR!

'''

xref:019-salmos/019-salmos-114.adoc#v19-114-0[&#60; Capítulo Anterior] | <<v19-115-0,Topo>> | xref:019-salmos/019-salmos-116.adoc#v19-116-0[Próximo Capítulo &#62;]