include::./index.adoc[]

[[v19-89-0]]
=== Salmos, 89
// nvt ?, NVT - Nova Versão Transformadora

[[v19-89-1]]

^<<v19-89-1,1>>^ Cantarei para sempre o teu amor, ó SENHOR! Anunciarei a tua fidelidade a todas as gerações.

[[v19-89-2]]

^<<v19-89-2,2>>^ Pois sei que o teu amor dura para sempre, e a tua fidelidade permanece firme como os céus.

[[v19-89-3]]

^<<v19-89-3,3>>^ Tu disseste: "Fiz uma aliança com Davi, meu servo escolhido. A ele fiz este juramento:

[[v19-89-4]]

^<<v19-89-4,4>>^ ‘Estabelecerei seus descendentes como reis para sempre; eles se sentarão em seu trono de geração em geração’". Interlúdio

[[v19-89-5]]

^<<v19-89-5,5>>^ Ó SENHOR, os céus louvam as tuas maravilhas; multidões de anjos te exaltam por tua fidelidade.

[[v19-89-6]]

^<<v19-89-6,6>>^ Pois quem nos céus se compara ao SENHOR? Quem é semelhante ao SENHOR entre os seres celestiais?

[[v19-89-7]]

^<<v19-89-7,7>>^ Os mais altos poderes angelicais reverenciam a Deus; ele é mais temível que todos que rodeiam seu trono.

[[v19-89-8]]

^<<v19-89-8,8>>^ Ó SENHOR, Deus dos Exércitos, quem é poderoso como tu, SENHOR? Tu és totalmente fiel!

[[v19-89-9]]

^<<v19-89-9,9>>^ Governas os mares revoltos e acalmas as ondas agitadas.

[[v19-89-10]]

^<<v19-89-10,10>>^ Esmagaste o grande monstro marinho; com o teu braço poderoso, dispersaste teus inimigos.

[[v19-89-11]]

^<<v19-89-11,11>>^ Os céus são teus, a terra é tua, tudo que há no mundo pertence a ti; tu fizeste todas as coisas.

[[v19-89-12]]

^<<v19-89-12,12>>^ Criaste o norte e o sul; o monte Tabor e o monte Hermom louvam o teu nome.

[[v19-89-13]]

^<<v19-89-13,13>>^ Teu braço é poderoso! Tua mão é forte! Tua mão direita se levanta com força gloriosa.

[[v19-89-14]]

^<<v19-89-14,14>>^ Justiça e retidão são os alicerces do teu trono, amor e verdade vão à tua frente.

[[v19-89-15]]

^<<v19-89-15,15>>^ Feliz é o povo que ouve o alegre chamado para adorar, pois andará na luz de tua presença, SENHOR.

[[v19-89-16]]

^<<v19-89-16,16>>^ O dia todo eles se alegram em teu nome e exultam em tua justiça.

[[v19-89-17]]

^<<v19-89-17,17>>^ Tu és a força gloriosa deles; é do teu agrado nos fortalecer.

[[v19-89-18]]

^<<v19-89-18,18>>^ Sim, nossa proteção vem do SENHOR; ele, o Santo de Israel, nos deu nosso rei.

[[v19-89-19]]

^<<v19-89-19,19>>^ Muito tempo atrás, numa visão, falaste a teus fiéis e disseste: "Levantei um guerreiro; dentre o povo o escolhi para ser rei.

[[v19-89-20]]

^<<v19-89-20,20>>^ Encontrei meu servo Davi e o ungi com meu santo óleo.

[[v19-89-21]]

^<<v19-89-21,21>>^ Com minha mão o firmarei, com meu braço o fortalecerei.

[[v19-89-22]]

^<<v19-89-22,22>>^ Seus inimigos não o derrotarão, os perversos não o dominarão.

[[v19-89-23]]

^<<v19-89-23,23>>^ Esmagarei seus adversários diante dele, destruirei aqueles que o odeiam.

[[v19-89-24]]

^<<v19-89-24,24>>^ Minha fidelidade e meu amor o acompanharão; em meu nome, ele crescerá em poder.

[[v19-89-25]]

^<<v19-89-25,25>>^ Estenderei seu governo sobre o mar, seu domínio, sobre os rios.

[[v19-89-26]]

^<<v19-89-26,26>>^ Ele me dirá: ‘Tu és meu Pai, meu Deus e a Rocha de minha salvação’.

[[v19-89-27]]

^<<v19-89-27,27>>^ Darei a ele os privilégios de filho mais velho, e ele será o rei mais poderoso da terra.

[[v19-89-28]]

^<<v19-89-28,28>>^ Eu o amarei e lhe serei bondoso para sempre; minha aliança com ele jamais será quebrada.

[[v19-89-29]]

^<<v19-89-29,29>>^ Farei que ele sempre tenha herdeiros; enquanto existirem os céus, seu trono não terá fim.

[[v19-89-30]]

^<<v19-89-30,30>>^ Se, porém, seus descendentes abandonarem minha lei e não seguirem meus estatutos,

[[v19-89-31]]

^<<v19-89-31,31>>^ se não obedecerem aos meus decretos e não guardarem meus mandamentos,

[[v19-89-32]]

^<<v19-89-32,32>>^ castigarei seu pecado com a vara e sua desobediência, com açoites.

[[v19-89-33]]

^<<v19-89-33,33>>^ Contudo, não desistirei de amá-lo, nem deixarei de lhe ser fiel.

[[v19-89-34]]

^<<v19-89-34,34>>^ Não quebrarei minha aliança, não voltarei atrás em minhas palavras.

[[v19-89-35]]

^<<v19-89-35,35>>^ Fiz um juramento a Davi e, em minha santidade, não minto.

[[v19-89-36]]

^<<v19-89-36,36>>^ Sua dinastia continuará para sempre, seu reino permanecerá como o sol.

[[v19-89-37]]

^<<v19-89-37,37>>^ Será duradouro como a lua, minha fiel testemunha no céu". Interlúdio

[[v19-89-38]]

^<<v19-89-38,38>>^ Agora, porém, tu o rejeitaste e o descartaste; estás irado com o teu ungido.

[[v19-89-39]]

^<<v19-89-39,39>>^ Renunciaste tua aliança com ele e jogaste sua coroa no pó.

[[v19-89-40]]

^<<v19-89-40,40>>^ Derrubaste os muros que o protegiam e destruíste as fortalezas que o defendiam.

[[v19-89-41]]

^<<v19-89-41,41>>^ Todos que por ali passam o saqueiam, e ele se tornou motivo de zombaria para seus vizinhos.

[[v19-89-42]]

^<<v19-89-42,42>>^ Tu fortaleceste seus inimigos e lhes deste razão para celebrar.

[[v19-89-43]]

^<<v19-89-43,43>>^ Tornaste inútil sua espada e não o ajudaste na batalha.

[[v19-89-44]]

^<<v19-89-44,44>>^ Acabaste com seu esplendor e derrubaste seu trono.

[[v19-89-45]]

^<<v19-89-45,45>>^ Fizeste-o envelhecer antes do tempo e o envergonhaste em público. Interlúdio

[[v19-89-46]]

^<<v19-89-46,46>>^ Até quando, SENHOR, esta situação continuará? Acaso te esconderás para sempre? Até quando tua ira arderá como fogo?

[[v19-89-47]]

^<<v19-89-47,47>>^ Lembra-te de como minha vida é curta, de como é vazia a existência humana!

[[v19-89-48]]

^<<v19-89-48,48>>^ Ninguém vive para sempre, todos morrem; ninguém escapa das garras da sepultura. Interlúdio

[[v19-89-49]]

^<<v19-89-49,49>>^ Onde está, Senhor, o teu antigo amor? Tu o prometeste a Davi com um juramento fiel.

[[v19-89-50]]

^<<v19-89-50,50>>^ Considera, Senhor, como teus servos passam vergonha; levo no coração os insultos de muitos.

[[v19-89-51]]

^<<v19-89-51,51>>^ Teus inimigos, SENHOR, têm zombado de mim; zombam do teu ungido por onde ele vai.

[[v19-89-52]]

^<<v19-89-52,52>>^ Louvado seja o SENHOR para sempre! Amém e amém!

'''

xref:019-salmos/019-salmos-088.adoc#v19-88-0[&#60; Capítulo Anterior] | <<v19-89-0,Topo>> | xref:019-salmos/019-salmos-090.adoc#v19-90-0[Próximo Capítulo &#62;]