include::./index.adoc[]

[[v19-86-0]]
=== Salmos, 86
// nvt ?, NVT - Nova Versão Transformadora

[[v19-86-1]]

^<<v19-86-1,1>>^ Inclina-te, SENHOR, e ouve minha oração; responde-me, pois estou aflito e necessitado.

[[v19-86-2]]

^<<v19-86-2,2>>^ Protege-me, pois sou fiel a ti; salva-me, pois sou teu servo e em ti confio. Tu és meu Deus!

[[v19-86-3]]

^<<v19-86-3,3>>^ Tem misericórdia de mim, ó Senhor, pois clamo a ti sem parar.

[[v19-86-4]]

^<<v19-86-4,4>>^ Alegra-me, Senhor, pois a ti me entrego.

[[v19-86-5]]

^<<v19-86-5,5>>^ Ó Senhor, tu és tão bom, tão pronto a perdoar, tão cheio de amor por todos que te buscam.

[[v19-86-6]]

^<<v19-86-6,6>>^ Ouve minha oração, SENHOR, e atende a meu clamor.

[[v19-86-7]]

^<<v19-86-7,7>>^ Em tempos de aflição, clamarei a ti, e tu me responderás.

[[v19-86-8]]

^<<v19-86-8,8>>^ Nenhum dos deuses é semelhante a ti, Senhor, nenhum deles pode fazer o que tu fazes.

[[v19-86-9]]

^<<v19-86-9,9>>^ Todas as nações que criaste virão e se prostrarão diante de ti, Senhor, e glorificarão o teu nome.

[[v19-86-10]]

^<<v19-86-10,10>>^ Pois tu és grande e realizas maravilhas; só tu és Deus.

[[v19-86-11]]

^<<v19-86-11,11>>^ Ensina-me os teus caminhos, SENHOR, para que eu viva segundo a tua verdade. Concede-me pureza de coração, para que eu honre o teu nome.

[[v19-86-12]]

^<<v19-86-12,12>>^ Ó Senhor, meu Deus, de todo o meu coração te louvarei; glorificarei o teu nome para sempre.

[[v19-86-13]]

^<<v19-86-13,13>>^ Pois grande é o teu amor por mim; tu me livraste das profundezas da morte.

[[v19-86-14]]

^<<v19-86-14,14>>^ Ó Deus, os arrogantes se levantam contra mim, pessoas violentas tentam me matar; não se importam contigo.

[[v19-86-15]]

^<<v19-86-15,15>>^ Mas tu, Senhor, és Deus de compaixão e misericórdia, lento para se irar e cheio de amor e fidelidade.

[[v19-86-16]]

^<<v19-86-16,16>>^ Olha para cá e tem compaixão de mim! Dá tua força a teu servo; sim, salva teu humilde servo.

[[v19-86-17]]

^<<v19-86-17,17>>^ Mostra-me um sinal do teu favor; então serão envergonhados os que me odeiam, pois tu, SENHOR, me ajudas e me consolas.

'''

xref:019-salmos/019-salmos-085.adoc#v19-85-0[&#60; Capítulo Anterior] | <<v19-86-0,Topo>> | xref:019-salmos/019-salmos-087.adoc#v19-87-0[Próximo Capítulo &#62;]