include::./index.adoc[]

[[v19-69-0]]
=== Salmos, 69
// nvt ?, NVT - Nova Versão Transformadora

[[v19-69-1]]

^<<v19-69-1,1>>^ Salva-me, ó Deus, pois as águas subiram até meu pescoço.

[[v19-69-2]]

^<<v19-69-2,2>>^ Afundo cada vez mais na lama e não tenho onde apoiar os pés. Entrei em águas profundas, e as correntezas me cobrem.

[[v19-69-3]]

^<<v19-69-3,3>>^ Estou exausto de tanto clamar; minha garganta está seca. Meus olhos estão inchados de tanto chorar, à espera de meu Deus.

[[v19-69-4]]

^<<v19-69-4,4>>^ Os que me odeiam sem razão são mais numerosos que os cabelos de minha cabeça. Muitos inimigos tentam me destruir com mentiras; exigem que eu devolva o que não roubei.

[[v19-69-5]]

^<<v19-69-5,5>>^ Ó Deus, tu sabes como sou tolo; é impossível esconder de ti meus pecados.

[[v19-69-6]]

^<<v19-69-6,6>>^ Não permitas que por minha causa sejam envergonhados os que em ti confiam, ó Soberano SENHOR dos Exércitos. Não deixes que por minha causa sejam humilhados, ó Deus de Israel.

[[v19-69-7]]

^<<v19-69-7,7>>^ Pois, por tua causa, suporto insultos; meu rosto está coberto de vergonha.

[[v19-69-8]]

^<<v19-69-8,8>>^ Até meus irmãos fingem não me conhecer; tratam-me como um desconhecido.

[[v19-69-9]]

^<<v19-69-9,9>>^ O zelo por tua casa me consome; os insultos dos que te insultam caíram sobre mim.

[[v19-69-10]]

^<<v19-69-10,10>>^ Quando choro e jejuo, eles zombam de mim.

[[v19-69-11]]

^<<v19-69-11,11>>^ Quando visto pano de saco, eles riem de mim.

[[v19-69-12]]

^<<v19-69-12,12>>^ Sou o assunto principal de suas conversas, e os bêbados cantam a meu respeito.

[[v19-69-13]]

^<<v19-69-13,13>>^ Eu, porém, continuo orando a ti, SENHOR, na esperança de que, desta vez, mostrarás teu favor. Responde-me, ó Deus, por teu grande amor; salva-me por tua fidelidade.

[[v19-69-14]]

^<<v19-69-14,14>>^ Livra-me do atoleiro, não permitas que eu afunde ainda mais. Salva-me dos que me odeiam, tira-me destas águas profundas.

[[v19-69-15]]

^<<v19-69-15,15>>^ Não deixes que as correntezas me cubram, nem que as águas profundas me engulam, nem que a cova da morte me devore.

[[v19-69-16]]

^<<v19-69-16,16>>^ Responde às minhas orações, ó SENHOR, pois o teu amor é bom. Cuida de mim, pois a tua misericórdia é imensa.

[[v19-69-17]]

^<<v19-69-17,17>>^ Não te escondas de teu servo; responde-me sem demora, pois estou aflito.

[[v19-69-18]]

^<<v19-69-18,18>>^ Vem e resgata-me; livra-me de meus inimigos!

[[v19-69-19]]

^<<v19-69-19,19>>^ Tu sabes que sofro zombaria, vergonha e humilhação; vês tudo que meus inimigos fazem.

[[v19-69-20]]

^<<v19-69-20,20>>^ Os insultos deles me partiram o coração; estou desesperado! Se ao menos alguém tivesse piedade de mim; quem dera viessem me consolar.

[[v19-69-21]]

^<<v19-69-21,21>>^ Em vez disso, põem veneno em minha comida; oferecem vinagre para matar minha sede.

[[v19-69-22]]

^<<v19-69-22,22>>^ Que a mesa farta diante deles se transforme em laço, e que sua prosperidade se torne armadilha.

[[v19-69-23]]

^<<v19-69-23,23>>^ Que seus olhos se escureçam para que não vejam, e que seu corpo trema sem parar.

[[v19-69-24]]

^<<v19-69-24,24>>^ Derrama tua fúria sobre eles, consome-os com o ardor de tua ira.

[[v19-69-25]]

^<<v19-69-25,25>>^ Que as casas deles fiquem desoladas, e que não reste ninguém em suas tendas.

[[v19-69-26]]

^<<v19-69-26,26>>^ Pois insultam aquele a quem castigaste, acrescentam dor a quem feriste.

[[v19-69-27]]

^<<v19-69-27,27>>^ Amontoa uns sobre os outros os pecados deles; não permitas que sejam absolvidos.

[[v19-69-28]]

^<<v19-69-28,28>>^ Apaga o nome deles do Livro da Vida; não deixes que sejam incluídos entre os justos.

[[v19-69-29]]

^<<v19-69-29,29>>^ Estou aflito e sofro; socorre-me, ó Deus, com tua salvação!

[[v19-69-30]]

^<<v19-69-30,30>>^ Então louvarei o nome de Deus com cânticos e o exaltarei com ações de graças.

[[v19-69-31]]

^<<v19-69-31,31>>^ Pois isso agrada o SENHOR mais que sacrifícios de bois, mais que ofertas de touros com chifres e cascos.

[[v19-69-32]]

^<<v19-69-32,32>>^ Os humildes verão Deus agir e se alegrarão; animem-se todos que buscam socorro em Deus.

[[v19-69-33]]

^<<v19-69-33,33>>^ Pois o SENHOR ouve o clamor dos pobres; não despreza seu povo aprisionado.

[[v19-69-34]]

^<<v19-69-34,34>>^ Louvem-no, céus e terra, os mares e tudo que neles se move.

[[v19-69-35]]

^<<v19-69-35,35>>^ Pois Deus salvará Sião e reconstruirá as cidades de Judá. Seu povo viverá ali e em sua própria terra se estabelecerá.

[[v19-69-36]]

^<<v19-69-36,36>>^ Os descendentes dos que o servem herdarão a terra, e os que o amam ali viverão, em segurança.

'''

xref:019-salmos/019-salmos-068.adoc#v19-68-0[&#60; Capítulo Anterior] | <<v19-69-0,Topo>> | xref:019-salmos/019-salmos-070.adoc#v19-70-0[Próximo Capítulo &#62;]