include::./index.adoc[]

[[v19-101-0]]
=== Salmos, 101
// nvt ?, NVT - Nova Versão Transformadora

[[v19-101-1]]

^<<v19-101-1,1>>^ Cantarei o teu amor e a tua justiça, SENHOR; com cânticos te louvarei.

[[v19-101-2]]

^<<v19-101-2,2>>^ Buscarei viver de modo inculpável; quando virás me ajudar? Viverei com integridade em minha própria casa.

[[v19-101-3]]

^<<v19-101-3,3>>^ Não olharei para coisa alguma que seja má e vulgar. Odeio todos que agem de forma desonesta; não terei nada a ver com eles.

[[v19-101-4]]

^<<v19-101-4,4>>^ Rejeitarei ideias perversas e me manterei afastado de todo mal.

[[v19-101-5]]

^<<v19-101-5,5>>^ Não tolerarei quem difama seu próximo, não suportarei presunção nem orgulho.

[[v19-101-6]]

^<<v19-101-6,6>>^ Irei à procura dos fiéis para conviverem comigo. Só terão permissão de me servir os que andam no caminho certo.

[[v19-101-7]]

^<<v19-101-7,7>>^ Não permitirei que enganadores habitem em minha casa, nem que mentirosos permaneçam em minha presença.

[[v19-101-8]]

^<<v19-101-8,8>>^ Minha tarefa diária será acabar com os perversos e expulsar da cidade do SENHOR os que praticam o mal.

'''

xref:019-salmos/019-salmos-100.adoc#v19-100-0[&#60; Capítulo Anterior] | <<v19-101-0,Topo>> | xref:019-salmos/019-salmos-102.adoc#v19-102-0[Próximo Capítulo &#62;]