include::./index.adoc[]

[[v19-62-0]]
=== Salmos, 62
// nvt ?, NVT - Nova Versão Transformadora

[[v19-62-1]]

^<<v19-62-1,1>>^ Em silêncio diante de Deus, minha alma espera, pois dele vem minha vitória.

[[v19-62-2]]

^<<v19-62-2,2>>^ Somente ele é minha rocha e minha salvação, minha fortaleza onde jamais serei abalado.

[[v19-62-3]]

^<<v19-62-3,3>>^ São tantos os inimigos contra um só homem; todos tentam me matar. Para eles, não passo de um muro inclinado ou uma cerca prestes a cair.

[[v19-62-4]]

^<<v19-62-4,4>>^ Planejam me derrubar de minha posição elevada; têm prazer em contar mentiras. Diante de mim, me elogiam; em seu coração, porém, me amaldiçoam. Interlúdio

[[v19-62-5]]

^<<v19-62-5,5>>^ Que minha alma espere em silêncio diante de Deus, pois nele está minha esperança.

[[v19-62-6]]

^<<v19-62-6,6>>^ Somente ele é minha rocha e minha salvação, minha fortaleza onde não serei abalado.

[[v19-62-7]]

^<<v19-62-7,7>>^ Minha vitória e minha honra vêm somente de Deus; ele é meu refúgio, uma rocha segura.

[[v19-62-8]]

^<<v19-62-8,8>>^ Ó meu povo, confie nele em todo tempo; derrame o coração diante dele, pois Deus é nosso refúgio. Interlúdio

[[v19-62-9]]

^<<v19-62-9,9>>^ As pessoas são vazias e enganosas, como uma rajada de vento. Se fosse colocada numa balança, toda a humanidade pesaria menos que um sopro.

[[v19-62-10]]

^<<v19-62-10,10>>^ Não ganhem a vida por meio da extorsão, nem ponham sua esperança em coisas roubadas. Se suas riquezas aumentarem, não façam delas o centro de sua vida.

[[v19-62-11]]

^<<v19-62-11,11>>^ Deus falou claramente, e eu ouvi várias vezes: O poder, ó Deus, pertence a ti;

[[v19-62-12]]

^<<v19-62-12,12>>^ o amor, Senhor, é teu. Certamente retribuirás a cada um conforme suas ações.

'''

xref:019-salmos/019-salmos-061.adoc#v19-61-0[&#60; Capítulo Anterior] | <<v19-62-0,Topo>> | xref:019-salmos/019-salmos-063.adoc#v19-63-0[Próximo Capítulo &#62;]