include::./index.adoc[]

[[v19-21-0]]
=== Salmos, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v19-21-1]]

^<<v19-21-1,1>>^ Em tua força, SENHOR, o rei se alegra; grita de alegria porque lhe dás vitória.

[[v19-21-2]]

^<<v19-21-2,2>>^ Concedeste o desejo de seu coração e não negaste nada do que ele pediu. Interlúdio

[[v19-21-3]]

^<<v19-21-3,3>>^ Tu o recebeste com riqueza de bênçãos; puseste em sua cabeça uma coroa de ouro puro.

[[v19-21-4]]

^<<v19-21-4,4>>^ Ele pediu que lhe preservasses a vida, e tu atendeste a seu pedido; seus dias se estendem para sempre.

[[v19-21-5]]

^<<v19-21-5,5>>^ Tua vitória lhe dá grande honra, e tu o cobriste de esplendor e majestade.

[[v19-21-6]]

^<<v19-21-6,6>>^ A ele deste bênçãos eternas e a alegria de tua presença.

[[v19-21-7]]

^<<v19-21-7,7>>^ Pois o rei confia no SENHOR; o amor do Altíssimo não permitirá que ele se abale.

[[v19-21-8]]

^<<v19-21-8,8>>^ Tu alcançarás todos os teus inimigos; tua forte mão direita apanhará todos que te odeiam.

[[v19-21-9]]

^<<v19-21-9,9>>^ Quando te manifestares, tu os lançarás numa fornalha ardente. Em sua ira, o SENHOR os consumirá; sim, fogo os devorará.

[[v19-21-10]]

^<<v19-21-10,10>>^ Eliminarás da face da terra seus filhos; jamais terão descendentes.

[[v19-21-11]]

^<<v19-21-11,11>>^ Embora conspirem contra ti, suas tramas perversas não terão sucesso.

[[v19-21-12]]

^<<v19-21-12,12>>^ Pois darão meia-volta e fugirão quando virem tuas flechas apontadas para eles.

[[v19-21-13]]

^<<v19-21-13,13>>^ Levanta-te, ó SENHOR, em teu poder! Com música e cânticos celebraremos tua força.

'''

xref:019-salmos/019-salmos-020.adoc#v19-20-0[&#60; Capítulo Anterior] | <<v19-21-0,Topo>> | xref:019-salmos/019-salmos-022.adoc#v19-22-0[Próximo Capítulo &#62;]