include::./index.adoc[]

[[v19-87-0]]
=== Salmos, 87
// nvt ?, NVT - Nova Versão Transformadora

[[v19-87-1]]

^<<v19-87-1,1>>^ No monte santo está a cidade fundada pelo SENHOR.

[[v19-87-2]]

^<<v19-87-2,2>>^ Ele ama a cidade de Jerusalém, mais que qualquer outro lugar em Israel.

[[v19-87-3]]

^<<v19-87-3,3>>^ Ó cidade de Deus, que coisas gloriosas são ditas a seu respeito! Interlúdio

[[v19-87-4]]

^<<v19-87-4,4>>^ Incluirei o Egito e a Babilônia entre os que me conhecem, também a Filístia e Tiro, e até a distante Etiópia; ali todos se tornaram seus cidadãos!

[[v19-87-5]]

^<<v19-87-5,5>>^ A respeito de Jerusalém se dirá: "Ali todos desfrutam os direitos de cidadãos", e o próprio Altíssimo abençoará a cidade.

[[v19-87-6]]

^<<v19-87-6,6>>^ Quando o SENHOR registrar as nações, dirá: "Ali todos se tornaram seus cidadãos!". Interlúdio

[[v19-87-7]]

^<<v19-87-7,7>>^ O povo tocará flautas e cantará: "A fonte de minha vida brota de Jerusalém!".

'''

xref:019-salmos/019-salmos-086.adoc#v19-86-0[&#60; Capítulo Anterior] | <<v19-87-0,Topo>> | xref:019-salmos/019-salmos-088.adoc#v19-88-0[Próximo Capítulo &#62;]