include::./index.adoc[]

[[v19-60-0]]
=== Salmos, 60
// nvt ?, NVT - Nova Versão Transformadora

[[v19-60-1]]

^<<v19-60-1,1>>^ Tu nos rejeitaste, ó Deus, e quebraste nossas defesas; sobre nós derramaste tua ira; agora, restaura-nos.

[[v19-60-2]]

^<<v19-60-2,2>>^ Sacudiste nossa terra e nela abriste fendas; repara as brechas, pois a terra estremece.

[[v19-60-3]]

^<<v19-60-3,3>>^ Foste muito severo conosco, teu povo, e nos fizeste beber vinho que nos deixou atordoados.

[[v19-60-4]]

^<<v19-60-4,4>>^ Contudo, levantaste uma bandeira para os que te temem, um ponto de abrigo em meio ao ataque. Interlúdio

[[v19-60-5]]

^<<v19-60-5,5>>^ Agora, livra teu povo amado; responde-nos e salva-nos por teu poder.

[[v19-60-6]]

^<<v19-60-6,6>>^ Deus, em seu santuário, prometeu: "Com alegria dividirei Siquém e medirei o vale de Sucote.

[[v19-60-7]]

^<<v19-60-7,7>>^ Gileade é minha, e também Manassés; Efraim é meu capacete, e Judá, meu cetro.

[[v19-60-8]]

^<<v19-60-8,8>>^ Moabe é minha bacia de lavar; sobre Edom limparei os pés e darei um grito de triunfo sobre a Filístia".

[[v19-60-9]]

^<<v19-60-9,9>>^ Quem me levará à cidade fortificada? Quem me guiará até Edom?

[[v19-60-10]]

^<<v19-60-10,10>>^ Acaso nos rejeitaste, ó Deus? Não marcharás mais com nossos exércitos?

[[v19-60-11]]

^<<v19-60-11,11>>^ Ajuda-nos contra nossos inimigos, pois todo socorro humano é inútil.

[[v19-60-12]]

^<<v19-60-12,12>>^ Com o auxílio de Deus, realizaremos grandes feitos, pois ele pisará os nossos inimigos.

'''

xref:019-salmos/019-salmos-059.adoc#v19-59-0[&#60; Capítulo Anterior] | <<v19-60-0,Topo>> | xref:019-salmos/019-salmos-061.adoc#v19-61-0[Próximo Capítulo &#62;]