include::./index.adoc[]

[[v19-137-0]]
=== Salmos, 137
// nvt ?, NVT - Nova Versão Transformadora

[[v19-137-1]]

^<<v19-137-1,1>>^ Junto aos rios da Babilônia, sentamos e choramos, ao nos lembrarmos de Sião.

[[v19-137-2]]

^<<v19-137-2,2>>^ Pusemos de lado nossas harpas e as penduramos nos galhos dos salgueiros.

[[v19-137-3]]

^<<v19-137-3,3>>^ Os que nos levaram cativos queriam que cantássemos; nossos opressores exigiam uma canção alegre: "Cantem para nós uma das canções de Sião!".

[[v19-137-4]]

^<<v19-137-4,4>>^ Mas como poderíamos cantar as canções do Senhor estando em terra estrangeira?

[[v19-137-5]]

^<<v19-137-5,5>>^ Se eu me esquecer de ti, ó Jerusalém, que minha mão direita perca sua habilidade.

[[v19-137-6]]

^<<v19-137-6,6>>^ Que minha língua se prenda ao céu da boca se eu não me lembrar de ti, se não fizer de Jerusalém minha maior alegria.

[[v19-137-7]]

^<<v19-137-7,7>>^ Ó SENHOR, lembra-te do que os edomitas fizeram no dia em que Jerusalém foi conquistada. Disseram: "Destruam-na! Arrasem-na até o chão!".

[[v19-137-8]]

^<<v19-137-8,8>>^ Ó Babilônia, você será destruída; feliz é aquele que lhe retribuir por tudo que fez contra nós.

[[v19-137-9]]

^<<v19-137-9,9>>^ Feliz aquele que pegar suas crianças e as esmagar contra a rocha.

'''

xref:019-salmos/019-salmos-136.adoc#v19-136-0[&#60; Capítulo Anterior] | <<v19-137-0,Topo>> | xref:019-salmos/019-salmos-138.adoc#v19-138-0[Próximo Capítulo &#62;]