include::./index.adoc[]

[[v19-29-0]]
=== Salmos, 29
// nvt ?, NVT - Nova Versão Transformadora

[[v19-29-1]]

^<<v19-29-1,1>>^ Honrem o SENHOR, seres celestiais, honrem o SENHOR por sua glória e força.

[[v19-29-2]]

^<<v19-29-2,2>>^ Honrem o SENHOR pela glória de seu nome, adorem o SENHOR no esplendor de sua santidade.

[[v19-29-3]]

^<<v19-29-3,3>>^ A voz do SENHOR ecoa sobre o mar, o Deus da glória troveja; sobre o imenso mar, o SENHOR fala.

[[v19-29-4]]

^<<v19-29-4,4>>^ A voz do SENHOR é poderosa, a voz do SENHOR é majestosa.

[[v19-29-5]]

^<<v19-29-5,5>>^ A voz do SENHOR quebra os grandes cedros, o SENHOR despedaça os cedros do Líbano.

[[v19-29-6]]

^<<v19-29-6,6>>^ Faz os montes do Líbano saltarem como bezerros, faz o monte Hermom pular como novilhos selvagens.

[[v19-29-7]]

^<<v19-29-7,7>>^ A voz do SENHOR risca o céu com relâmpagos.

[[v19-29-8]]

^<<v19-29-8,8>>^ A voz do SENHOR sacode o deserto, o SENHOR faz tremer o deserto de Cades.

[[v19-29-9]]

^<<v19-29-9,9>>^ A voz do SENHOR torce os fortes carvalhos e arranca as folhas dos bosques; em seu templo todos proclamam: "Glória!".

[[v19-29-10]]

^<<v19-29-10,10>>^ O SENHOR comanda as águas da inundação, o SENHOR governa como Rei para sempre.

[[v19-29-11]]

^<<v19-29-11,11>>^ O SENHOR dá força ao seu povo, o SENHOR os abençoa com paz.

'''

xref:019-salmos/019-salmos-028.adoc#v19-28-0[&#60; Capítulo Anterior] | <<v19-29-0,Topo>> | xref:019-salmos/019-salmos-030.adoc#v19-30-0[Próximo Capítulo &#62;]