include::./index.adoc[]

[[v19-5-0]]
=== Salmos, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v19-5-1]]

^<<v19-5-1,1>>^ Ó SENHOR, ouve minhas palavras e presta atenção a meus gemidos.

[[v19-5-2]]

^<<v19-5-2,2>>^ Atende a meu clamor por socorro, meu Rei e meu Deus, pois é somente a ti que oro.

[[v19-5-3]]

^<<v19-5-3,3>>^ Escuta minha voz logo cedo, SENHOR; toda manhã te apresento meus pedidos e fico à espera.

[[v19-5-4]]

^<<v19-5-4,4>>^ Ó Deus, tu não tens prazer algum na maldade e não toleras o pecado dos perversos.

[[v19-5-5]]

^<<v19-5-5,5>>^ Os orgulhosos não terão lugar em tua presença, pois odeias todos que praticam o mal.

[[v19-5-6]]

^<<v19-5-6,6>>^ Tu destróis os mentirosos; o SENHOR detesta assassinos e enganadores.

[[v19-5-7]]

^<<v19-5-7,7>>^ Por causa do teu grande amor entrarei em tua casa; adorarei em teu templo com profunda reverência.

[[v19-5-8]]

^<<v19-5-8,8>>^ Conduz-me pela tua justiça, SENHOR, para que meus inimigos não me vençam. Remove os obstáculos do teu caminho, para que eu o siga.

[[v19-5-9]]

^<<v19-5-9,9>>^ Meus inimigos são incapazes de falar a verdade; seu desejo mais intenso é destruir. Sua conversa é repulsiva, como o mau cheiro de um túmulo aberto; sua língua é cheia de bajulação.

[[v19-5-10]]

^<<v19-5-10,10>>^ Ó Deus, declara-os culpados; que eles caiam nas próprias armadilhas. Expulsa-os por causa de seus muitos pecados, pois se rebelaram contra ti.

[[v19-5-11]]

^<<v19-5-11,11>>^ Alegrem-se, porém, todos que em ti se refugiam; que cantem alegres louvores para sempre. Estende sobre eles tua proteção, para que exultem todos que amam teu nome.

[[v19-5-12]]

^<<v19-5-12,12>>^ Pois tu, SENHOR, abençoas os justos; com teu favor os proteges como um escudo.

'''

xref:019-salmos/019-salmos-004.adoc#v19-4-0[&#60; Capítulo Anterior] | <<v19-5-0,Topo>> | xref:019-salmos/019-salmos-006.adoc#v19-6-0[Próximo Capítulo &#62;]