include::./index.adoc[]

[[v19-32-0]]
=== Salmos, 32
// nvt ?, NVT - Nova Versão Transformadora

[[v19-32-1]]

^<<v19-32-1,1>>^ Como é feliz aquele cuja desobediência é perdoada, cujo pecado é coberto!

[[v19-32-2]]

^<<v19-32-2,2>>^ Sim, como é feliz aquele cuja culpa o SENHOR não leva em conta, cuja consciência é sempre sincera!

[[v19-32-3]]

^<<v19-32-3,3>>^ Enquanto me recusei a confessar meu pecado, meu corpo definhou, e eu gemia o dia inteiro.

[[v19-32-4]]

^<<v19-32-4,4>>^ Dia e noite, tua mão pesava sobre mim; minha força evaporou como água no calor do verão. Interlúdio

[[v19-32-5]]

^<<v19-32-5,5>>^ Finalmente, confessei a ti todos os meus pecados e não escondi mais a minha culpa. Disse comigo: "Confessarei ao SENHOR a minha rebeldia", e tu perdoaste toda a minha culpa. Interlúdio

[[v19-32-6]]

^<<v19-32-6,6>>^ Portanto, todos que forem fiéis orem a ti enquanto há tempo, para que não se afoguem quando vier a inundação.

[[v19-32-7]]

^<<v19-32-7,7>>^ Pois és meu esconderijo; tu me guardas da aflição e me cercas de cânticos de vitória. Interlúdio

[[v19-32-8]]

^<<v19-32-8,8>>^ O SENHOR diz: "Eu o guiarei pelo melhor caminho para sua vida, lhe darei conselhos e cuidarei de você.

[[v19-32-9]]

^<<v19-32-9,9>>^ Não sejam como o cavalo ou a mula, que não têm entendimento e precisam de freios e rédeas para ser controlados".

[[v19-32-10]]

^<<v19-32-10,10>>^ O perverso tem muitas tristezas, mas o que confia no SENHOR é cercado de amor.

[[v19-32-11]]

^<<v19-32-11,11>>^ Portanto, alegrem-se no SENHOR e exultem, todos vocês que são justos! Gritem de alegria, todos vocês que têm coração íntegro!

'''

xref:019-salmos/019-salmos-031.adoc#v19-31-0[&#60; Capítulo Anterior] | <<v19-32-0,Topo>> | xref:019-salmos/019-salmos-033.adoc#v19-33-0[Próximo Capítulo &#62;]