include::./index.adoc[]

[[v19-2-0]]
=== Salmos, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v19-2-1]]

^<<v19-2-1,1>>^ Por que as nações se enfurecem tanto? Por que perdem seu tempo com planos inúteis?

[[v19-2-2]]

^<<v19-2-2,2>>^ Os reis da terra se preparam para a batalha; os governantes conspiram juntos, contra o Senhor e contra seu ungido.

[[v19-2-3]]

^<<v19-2-3,3>>^ "Vamos quebrar estas correntes!", eles dizem. "Vamos nos libertar da escravidão!"

[[v19-2-4]]

^<<v19-2-4,4>>^ Aquele que governa nos céus ri; o Senhor zomba deles.

[[v19-2-5]]

^<<v19-2-5,5>>^ Então, em sua ira, ele os repreende e, com sua fúria, os aterroriza.

[[v19-2-6]]

^<<v19-2-6,6>>^ Ele diz: "Estabeleci meu rei no trono em Sião, em meu santo monte".

[[v19-2-7]]

^<<v19-2-7,7>>^ O rei proclama o decreto do SENHOR: "O SENHOR me disse: ‘Você é meu filho; hoje eu o gerei.

[[v19-2-8]]

^<<v19-2-8,8>>^ Basta pedir e lhe darei as nações como herança, a terra inteira como sua propriedade.

[[v19-2-9]]

^<<v19-2-9,9>>^ Você as quebrará com cetro de ferro e as despedaçará como vasos de barro’".

[[v19-2-10]]

^<<v19-2-10,10>>^ Portanto, reis, sejam prudentes! Aceitem a advertência, governantes da terra!

[[v19-2-11]]

^<<v19-2-11,11>>^ Sirvam ao SENHOR com temor, alegrem-se nele com tremor.

[[v19-2-12]]

^<<v19-2-12,12>>^ Sujeitem-se ao filho, para que ele não se ire e vocês não sejam destruídos de repente, pois sua ira se acende num instante; felizes, porém, os que nele se refugiam!

'''

xref:019-salmos/019-salmos-001.adoc#v19-1-0[&#60; Capítulo Anterior] | <<v19-2-0,Topo>> | xref:019-salmos/019-salmos-003.adoc#v19-3-0[Próximo Capítulo &#62;]