include::./index.adoc[]

[[v19-74-0]]
=== Salmos, 74
// nvt ?, NVT - Nova Versão Transformadora

[[v19-74-1]]

^<<v19-74-1,1>>^ Ó Deus, por que nos rejeitaste por tanto tempo? Por que é tão intensa tua ira contra as ovelhas de teu pasto?

[[v19-74-2]]

^<<v19-74-2,2>>^ Lembra-te de que somos o povo que adquiriste muito tempo atrás, a tribo que resgataste como tua propriedade; lembra-te ainda do monte Sião, a tua habitação.

[[v19-74-3]]

^<<v19-74-3,3>>^ Caminha pelas ruínas assustadoras da cidade; vê como o inimigo destruiu teu santuário.

[[v19-74-4]]

^<<v19-74-4,4>>^ Ali teus inimigos deram gritos de vitória; ali, hastearam suas bandeiras de guerra.

[[v19-74-5]]

^<<v19-74-5,5>>^ Usaram seus machados como lenhadores no bosque.

[[v19-74-6]]

^<<v19-74-6,6>>^ Com machados e picaretas, despedaçaram os painéis entalhados.

[[v19-74-7]]

^<<v19-74-7,7>>^ Incendiaram todo o teu santuário, profanaram o lugar de habitação do teu nome.

[[v19-74-8]]

^<<v19-74-8,8>>^ Pensaram: "Vamos destruir tudo!", e queimaram todos os lugares de adoração a Deus.

[[v19-74-9]]

^<<v19-74-9,9>>^ Já não vemos teus sinais; não há mais profetas, e ninguém sabe quando isso acabará.

[[v19-74-10]]

^<<v19-74-10,10>>^ Até quando, ó Deus, permitirás que nossos inimigos te insultem? Acaso deixarás que blasfemem teu nome para sempre?

[[v19-74-11]]

^<<v19-74-11,11>>^ Por que reténs tua forte mão direita? Estende-a com poder e destrói-os!

[[v19-74-12]]

^<<v19-74-12,12>>^ Tu, ó Deus, és meu rei desde a antiguidade e trazes salvação à terra.

[[v19-74-13]]

^<<v19-74-13,13>>^ Com tua força, dividiste o mar e despedaçaste as cabeças dos monstros marinhos.

[[v19-74-14]]

^<<v19-74-14,14>>^ Esmagaste as cabeças do Leviatã e o deste como alimento aos animais do deserto.

[[v19-74-15]]

^<<v19-74-15,15>>^ Fizestes jorrar fontes e riachos e secaste rios de águas torrenciais.

[[v19-74-16]]

^<<v19-74-16,16>>^ Tanto o dia como a noite pertencem a ti; criaste a luz das estrelas e o sol.

[[v19-74-17]]

^<<v19-74-17,17>>^ Determinaste os limites da terra e fizeste o verão e o inverno.

[[v19-74-18]]

^<<v19-74-18,18>>^ Vê como os inimigos te insultam, SENHOR; uma nação insensata blasfemou teu nome.

[[v19-74-19]]

^<<v19-74-19,19>>^ Não permitas que esses animais selvagens destruam tua pomba; não te esqueças para sempre de teu povo aflito.

[[v19-74-20]]

^<<v19-74-20,20>>^ Lembra-te das promessas da aliança, pois a terra está cheia de escuridão e violência.

[[v19-74-21]]

^<<v19-74-21,21>>^ Não permitas que os oprimidos voltem a ser humilhados; em vez disso, que os pobres e os necessitados louvem teu nome.

[[v19-74-22]]

^<<v19-74-22,22>>^ Levanta-te, ó Deus, e defende tua causa; lembra-te de como esses tolos te insultam o dia todo.

[[v19-74-23]]

^<<v19-74-23,23>>^ Não ignores o que teus inimigos disseram, nem o tumulto que cresce sem parar.

'''

xref:019-salmos/019-salmos-073.adoc#v19-73-0[&#60; Capítulo Anterior] | <<v19-74-0,Topo>> | xref:019-salmos/019-salmos-075.adoc#v19-75-0[Próximo Capítulo &#62;]