include::./index.adoc[]

[[v19-66-0]]
=== Salmos, 66
// nvt ?, NVT - Nova Versão Transformadora

[[v19-66-1]]

^<<v19-66-1,1>>^ Aclamem a Deus, todos os habitantes da terra!

[[v19-66-2]]

^<<v19-66-2,2>>^ Cantem a glória de seu nome, anunciem ao mundo quão glorioso ele é.

[[v19-66-3]]

^<<v19-66-3,3>>^ Digam a Deus: "Como são notáveis os teus feitos! Teus inimigos rastejam diante do teu grande poder.

[[v19-66-4]]

^<<v19-66-4,4>>^ Tudo que há na terra te adorará; cantará louvores a ti e anunciará teu nome em cânticos". Interlúdio

[[v19-66-5]]

^<<v19-66-5,5>>^ Venham e vejam as obras de Deus! Que feitos notáveis ele realiza em favor das pessoas!

[[v19-66-6]]

^<<v19-66-6,6>>^ Abriu um caminho seco pelo meio do mar, e seu povo atravessou a pé; ali nos alegramos nele.

[[v19-66-7]]

^<<v19-66-7,7>>^ Com seu grande poder, ele governa para sempre e vigia cada movimento das nações; que nenhum rebelde se levante contra ele. Interlúdio

[[v19-66-8]]

^<<v19-66-8,8>>^ Que o mundo inteiro celebre nosso Deus e cante louvores a ele em alta voz!

[[v19-66-9]]

^<<v19-66-9,9>>^ Nossa vida está em suas mãos; ele não permite que nossos pés tropecem.

[[v19-66-10]]

^<<v19-66-10,10>>^ Tu nos puseste à prova, ó Deus, e nos purificaste como prata.

[[v19-66-11]]

^<<v19-66-11,11>>^ Tu nos prendeste em tua armadilha e colocaste sobre nossas costas o fardo da opressão.

[[v19-66-12]]

^<<v19-66-12,12>>^ Permitiste que inimigos nos pisoteassem; passamos pelo fogo e pela água, mas tu nos trouxeste a um lugar de grande fartura.

[[v19-66-13]]

^<<v19-66-13,13>>^ Agora venho ao teu templo com holocaustos para cumprir os votos que fiz a ti,

[[v19-66-14]]

^<<v19-66-14,14>>^ sim, os votos sagrados que fiz quando estava em grande aflição.

[[v19-66-15]]

^<<v19-66-15,15>>^ Por isso te apresentarei holocaustos: meus melhores carneiros, como aroma agradável, e um sacrifício de novilhos e cabritos. Interlúdio

[[v19-66-16]]

^<<v19-66-16,16>>^ Venham e ouçam, todos vocês que temem a Deus, e eu lhes contarei o que ele fez por mim.

[[v19-66-17]]

^<<v19-66-17,17>>^ Pois a ele clamei por socorro e o louvei enquanto falava.

[[v19-66-18]]

^<<v19-66-18,18>>^ Se eu não tivesse confessado o pecado em meu coração, o Senhor não teria ouvido.

[[v19-66-19]]

^<<v19-66-19,19>>^ Mas Deus ouviu! Ele atendeu à minha oração.

[[v19-66-20]]

^<<v19-66-20,20>>^ Louvado seja Deus, que não rejeitou minha oração, nem afastou de mim o seu amor.

'''

xref:019-salmos/019-salmos-065.adoc#v19-65-0[&#60; Capítulo Anterior] | <<v19-66-0,Topo>> | xref:019-salmos/019-salmos-067.adoc#v19-67-0[Próximo Capítulo &#62;]