include::./index.adoc[]

[[v19-56-0]]
=== Salmos, 56
// nvt ?, NVT - Nova Versão Transformadora

[[v19-56-1]]

^<<v19-56-1,1>>^ Ó Deus, tem misericórdia de mim, pois sofro perseguição; meus inimigos me atacam o dia todo.

[[v19-56-2]]

^<<v19-56-2,2>>^ Vivo perseguido por aqueles que me caluniam, e muitos me atacam abertamente.

[[v19-56-3]]

^<<v19-56-3,3>>^ Quando eu tiver medo, porém, confiarei em ti.

[[v19-56-4]]

^<<v19-56-4,4>>^ Louvo a Deus por suas promessas, confio em Deus e não temerei; o que me podem fazer os simples mortais?

[[v19-56-5]]

^<<v19-56-5,5>>^ Sempre distorcem o que digo e passam dias tramando me prejudicar.

[[v19-56-6]]

^<<v19-56-6,6>>^ Reúnem-se para me espionar e vigiam meus passos, ansiosos para me matar.

[[v19-56-7]]

^<<v19-56-7,7>>^ Castiga-os por sua maldade; ó Deus, derruba-os em tua ira.

[[v19-56-8]]

^<<v19-56-8,8>>^ Conheces bem todas as minhas angústias; recolheste minhas lágrimas num jarro e em teu livro registraste cada uma delas.

[[v19-56-9]]

^<<v19-56-9,9>>^ Meus inimigos baterão em retirada quando eu clamar a ti; uma coisa sei: Deus está do meu lado!

[[v19-56-10]]

^<<v19-56-10,10>>^ Louvo a Deus por suas promessas, sim, louvo o SENHOR por suas promessas.

[[v19-56-11]]

^<<v19-56-11,11>>^ Confio em Deus e não temerei; o que me podem fazer os simples mortais?

[[v19-56-12]]

^<<v19-56-12,12>>^ Cumprirei os votos que fiz a ti, ó Deus, e te oferecerei um sacrifício de gratidão.

[[v19-56-13]]

^<<v19-56-13,13>>^ Pois me livraste da morte; não deixaste que meus pés tropeçassem. Agora, posso andar em tua presença, ó Deus, em tua luz que dá vida.

'''

xref:019-salmos/019-salmos-055.adoc#v19-55-0[&#60; Capítulo Anterior] | <<v19-56-0,Topo>> | xref:019-salmos/019-salmos-057.adoc#v19-57-0[Próximo Capítulo &#62;]