include::./index.adoc[]

[[v19-22-0]]
=== Salmos, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v19-22-1]]

^<<v19-22-1,1>>^ Meu Deus, meu Deus, por que me abandonaste? Por que estás tão distante de meus gemidos por socorro?

[[v19-22-2]]

^<<v19-22-2,2>>^ Todos os dias clamo a ti, meu Deus, mas não respondes; todas as noites levanto a voz, mas não encontro alívio.

[[v19-22-3]]

^<<v19-22-3,3>>^ Tu, porém, és santo e estás entronizado sobre os louvores de Israel.

[[v19-22-4]]

^<<v19-22-4,4>>^ Nossos antepassados confiaram em ti, e tu os livraste.

[[v19-22-5]]

^<<v19-22-5,5>>^ Clamaram a ti e foram libertos; em ti confiaram e jamais foram envergonhados.

[[v19-22-6]]

^<<v19-22-6,6>>^ Mas eu sou um verme, e não um homem; todos me insultam e me desprezam.

[[v19-22-7]]

^<<v19-22-7,7>>^ Os que me veem zombam de mim; riem com maldade e balançam a cabeça:

[[v19-22-8]]

^<<v19-22-8,8>>^ "Esse é o que confia no SENHOR? Que ele o livre! Que o liberte, se dele se agrada!".

[[v19-22-9]]

^<<v19-22-9,9>>^ Tu, porém, me tiraste a salvo do ventre de minha mãe e me deste segurança quando ela ainda me amamentava.

[[v19-22-10]]

^<<v19-22-10,10>>^ Fui colocado em teus braços assim que nasci; desde o ventre de minha mãe, tens sido meu Deus.

[[v19-22-11]]

^<<v19-22-11,11>>^ Não permaneças distante de mim, pois o sofrimento está próximo, e ninguém mais pode me ajudar.

[[v19-22-12]]

^<<v19-22-12,12>>^ Meus inimigos me rodeiam como touros; sim, touros ferozes de Basã me cercam.

[[v19-22-13]]

^<<v19-22-13,13>>^ Abrem a boca contra mim como leões que rugem e despedaçam a presa.

[[v19-22-14]]

^<<v19-22-14,14>>^ Minha vida é derramada como água; todos os meus ossos estão desconjuntados. Meu coração é como cera que se derrete dentro de mim.

[[v19-22-15]]

^<<v19-22-15,15>>^ Minha força secou, como um caco de barro, minha língua está grudada ao céu da boca; tu me deitaste no pó, à beira da morte.

[[v19-22-16]]

^<<v19-22-16,16>>^ Meus inimigos me rodeiam como cães, um bando de perversos me cerca; perfuraram minhas mãos e meus pés.

[[v19-22-17]]

^<<v19-22-17,17>>^ Posso contar todos os meus ossos; meus inimigos me encaram e desdenham de mim.

[[v19-22-18]]

^<<v19-22-18,18>>^ Repartem minhas roupas entre si e lançam sortes por minha veste.

[[v19-22-19]]

^<<v19-22-19,19>>^ Ó SENHOR, não permaneças distante! És minha força; vem depressa me ajudar.

[[v19-22-20]]

^<<v19-22-20,20>>^ Livra-me da espada e não permitas que esses cães me tirem a vida.

[[v19-22-21]]

^<<v19-22-21,21>>^ Salva-me da boca do leão e dos chifres dos bois selvagens.

[[v19-22-22]]

^<<v19-22-22,22>>^ Proclamarei teu nome a meus irmãos; no meio de teu povo reunido te louvarei.

[[v19-22-23]]

^<<v19-22-23,23>>^ Louvem o SENHOR, todos que o temem! Glorifiquem-no, todos os descendentes de Jacó! Reverenciem-no, todos os descendentes de Israel!

[[v19-22-24]]

^<<v19-22-24,24>>^ Pois ele não desprezou nem desdenhou o sofrimento dos aflitos; não lhes deu as costas, mas ouviu seus clamores por socorro.

[[v19-22-25]]

^<<v19-22-25,25>>^ Eu te louvarei na grande congregação; cumprirei meus votos na presença dos que te adoram.

[[v19-22-26]]

^<<v19-22-26,26>>^ Os pobres comerão e se saciarão; todos que buscam o SENHOR o louvarão e terão o coração cheio de alegria sem fim.

[[v19-22-27]]

^<<v19-22-27,27>>^ Toda a terra reconhecerá o SENHOR e voltará para ele; diante dele se prostrarão todas as famílias das nações.

[[v19-22-28]]

^<<v19-22-28,28>>^ Pois o SENHOR reina e governa sobre todos os povos.

[[v19-22-29]]

^<<v19-22-29,29>>^ Que os ricos da terra celebrem e o adorem; todos os mortais se prostrem diante dele, todos cuja vida terminará como pó.

[[v19-22-30]]

^<<v19-22-30,30>>^ Nossos filhos também o servirão, as gerações futuras ouvirão sobre o Senhor.

[[v19-22-31]]

^<<v19-22-31,31>>^ Proclamarão sua justiça aos que ainda não nasceram e falarão a respeito de tudo que ele fez.

'''

xref:019-salmos/019-salmos-021.adoc#v19-21-0[&#60; Capítulo Anterior] | <<v19-22-0,Topo>> | xref:019-salmos/019-salmos-023.adoc#v19-23-0[Próximo Capítulo &#62;]