include::./index.adoc[]

[[v19-52-0]]
=== Salmos, 52
// nvt ?, NVT - Nova Versão Transformadora

[[v19-52-1]]

^<<v19-52-1,1>>^ Por que conta vantagem de seus crimes, grande guerreiro? Não sabe que o amor de Deus dura para sempre?

[[v19-52-2]]

^<<v19-52-2,2>>^ O dia todo você trama destruição; sua língua mentirosa corta como navalha afiada.

[[v19-52-3]]

^<<v19-52-3,3>>^ Ama o mal mais que o bem e fala mais mentiras que verdades. Interlúdio

[[v19-52-4]]

^<<v19-52-4,4>>^ Você gosta de destruir os outros com suas palavras, seu mentiroso!

[[v19-52-5]]

^<<v19-52-5,5>>^ Por isso, Deus o destruirá de uma vez por todas; ele o tirará de sua casa e o arrancará da terra dos vivos. Interlúdio

[[v19-52-6]]

^<<v19-52-6,6>>^ Os justos verão isso e temerão; rirão de você e dirão:

[[v19-52-7]]

^<<v19-52-7,7>>^ "Vejam o que acontece aos poderosos guerreiros que não fazem de Deus sua fortaleza! Confiam em suas muitas riquezas e se refugiam em sua maldade".

[[v19-52-8]]

^<<v19-52-8,8>>^ Eu, porém, sou como a oliveira que floresce na casa de Deus; sempre confiarei no amor de Deus.

[[v19-52-9]]

^<<v19-52-9,9>>^ Eu te louvarei para sempre, ó Deus, por aquilo que fizeste. Confiarei em teu bom nome, na presença de teu povo fiel.

'''

xref:019-salmos/019-salmos-051.adoc#v19-51-0[&#60; Capítulo Anterior] | <<v19-52-0,Topo>> | xref:019-salmos/019-salmos-053.adoc#v19-53-0[Próximo Capítulo &#62;]