include::./index.adoc[]

[[v19-34-0]]
=== Salmos, 34
// nvt ?, NVT - Nova Versão Transformadora

[[v19-34-1]]

^<<v19-34-1,1>>^ Louvarei o SENHOR em todo o tempo; meus lábios sempre o louvarão.

[[v19-34-2]]

^<<v19-34-2,2>>^ Somente no SENHOR me gloriarei; que todos os humildes se alegrem.

[[v19-34-3]]

^<<v19-34-3,3>>^ Venham, proclamemos a grandeza do SENHOR; juntos, exaltemos o seu nome.

[[v19-34-4]]

^<<v19-34-4,4>>^ Busquei o SENHOR, e ele me respondeu; livrou-me de todos os meus temores.

[[v19-34-5]]

^<<v19-34-5,5>>^ Os que olham para ele ficarão radiantes; no rosto deles não haverá sombra de decepção.

[[v19-34-6]]

^<<v19-34-6,6>>^ Clamei ao SENHOR em meu desespero, e ele me ouviu; livrou-me de todas as minhas angústias.

[[v19-34-7]]

^<<v19-34-7,7>>^ O anjo do SENHOR é guardião; ele cerca e defende os que o temem.

[[v19-34-8]]

^<<v19-34-8,8>>^ Provem e vejam que o SENHOR é bom! Como é feliz o que nele se refugia!

[[v19-34-9]]

^<<v19-34-9,9>>^ Temam o SENHOR, vocês que lhe são fiéis, pois os que o temem terão tudo de que precisam.

[[v19-34-10]]

^<<v19-34-10,10>>^ Até mesmo os leões jovens e fortes passam fome, mas aos que buscam o SENHOR nada de bom faltará.

[[v19-34-11]]

^<<v19-34-11,11>>^ Venham, meus filhos, e ouçam-me; eu os ensinarei a temer o SENHOR.

[[v19-34-12]]

^<<v19-34-12,12>>^ Quem deseja ter uma vida longa e próspera?

[[v19-34-13]]

^<<v19-34-13,13>>^ Refreie a língua de falar maldades e os lábios de dizerem mentiras.

[[v19-34-14]]

^<<v19-34-14,14>>^ Afaste-se do mal e faça o bem; busque a paz e esforce-se para mantê-la.

[[v19-34-15]]

^<<v19-34-15,15>>^ Os olhos do SENHOR estão sobre os justos, e seus ouvidos, abertos para seus clamores.

[[v19-34-16]]

^<<v19-34-16,16>>^ O SENHOR, porém, volta o rosto contra os que praticam o mal; apagará da terra qualquer lembrança deles.

[[v19-34-17]]

^<<v19-34-17,17>>^ O SENHOR ouve os justos quando clamam por socorro; ele os livra de todas as suas angústias.

[[v19-34-18]]

^<<v19-34-18,18>>^ O SENHOR está perto dos que têm o coração quebrantado e resgata os de espírito oprimido.

[[v19-34-19]]

^<<v19-34-19,19>>^ O justo enfrenta muitas dificuldades, mas o SENHOR o livra de todas elas.

[[v19-34-20]]

^<<v19-34-20,20>>^ Pois o SENHOR protege os ossos do justo; nem um sequer será quebrado.

[[v19-34-21]]

^<<v19-34-21,21>>^ A calamidade certamente destruirá os perversos, e os que odeiam o justo serão castigados.

[[v19-34-22]]

^<<v19-34-22,22>>^ O SENHOR, porém, resgatará os que o servem; ninguém que nele se refugia será condenado.

'''

xref:019-salmos/019-salmos-033.adoc#v19-33-0[&#60; Capítulo Anterior] | <<v19-34-0,Topo>> | xref:019-salmos/019-salmos-035.adoc#v19-35-0[Próximo Capítulo &#62;]