include::./index.adoc[]

[[v19-36-0]]
=== Salmos, 36
// nvt ?, NVT - Nova Versão Transformadora

[[v19-36-1]]

^<<v19-36-1,1>>^ O pecado do ímpio sussurra ao seu coração; ele não tem o menor temor de Deus.

[[v19-36-2]]

^<<v19-36-2,2>>^ Em sua cega presunção, não percebe quão grande é sua perversidade.

[[v19-36-3]]

^<<v19-36-3,3>>^ Tudo que diz é distorcido e enganoso; não quer agir com prudência nem fazer o bem.

[[v19-36-4]]

^<<v19-36-4,4>>^ Mesmo à noite, trama maldades; suas ações nunca são boas, e não se esforça para fugir do mal.

[[v19-36-5]]

^<<v19-36-5,5>>^ Teu amor, SENHOR, é imenso como os céus; tua fidelidade vai além das nuvens.

[[v19-36-6]]

^<<v19-36-6,6>>^ Tua justiça é como os montes imponentes, teus decretos, como as profundezas do oceano; tu, SENHOR, cuidas tanto das pessoas como dos animais.

[[v19-36-7]]

^<<v19-36-7,7>>^ Como é precioso o teu amor, ó Deus! Toda a humanidade encontra abrigo à sombra de tuas asas.

[[v19-36-8]]

^<<v19-36-8,8>>^ Tu os alimentas com a fartura de tua casa e deixas que bebam de teu rio de delícias.

[[v19-36-9]]

^<<v19-36-9,9>>^ Pois és a fonte de vida, a luz pela qual vemos.

[[v19-36-10]]

^<<v19-36-10,10>>^ Derrama teu amor sobre os que te conhecem, concede justiça aos sinceros de coração.

[[v19-36-11]]

^<<v19-36-11,11>>^ Não permitas que os arrogantes me pisoteiem, nem que os perversos me empurrem.

[[v19-36-12]]

^<<v19-36-12,12>>^ Vejam! Caíram os que praticam o mal! Foram derrubados e nunca mais se levantarão.

'''

xref:019-salmos/019-salmos-035.adoc#v19-35-0[&#60; Capítulo Anterior] | <<v19-36-0,Topo>> | xref:019-salmos/019-salmos-037.adoc#v19-37-0[Próximo Capítulo &#62;]