include::./index.adoc[]

[[v19-10-0]]
=== Salmos, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v19-10-1]]

^<<v19-10-1,1>>^ Ó SENHOR, por que permaneces distante? Por que te escondes em tempos de aflição?

[[v19-10-2]]

^<<v19-10-2,2>>^ O perverso, em sua arrogância, persegue o pobre; que seja pego em suas próprias tramas.

[[v19-10-3]]

^<<v19-10-3,3>>^ Pois conta vantagem de seus desejos maus; elogia os gananciosos e amaldiçoa o SENHOR.

[[v19-10-4]]

^<<v19-10-4,4>>^ O perverso é orgulhoso demais para buscá-lo; seus planos não levam em conta que Deus existe.

[[v19-10-5]]

^<<v19-10-5,5>>^ No entanto, é bem-sucedido em tudo que faz; não vê que teu castigo o aguarda e despreza todos os seus inimigos.

[[v19-10-6]]

^<<v19-10-6,6>>^ Pensa: "Nenhum mal nos atingirá; nunca teremos problemas!".

[[v19-10-7]]

^<<v19-10-7,7>>^ Sua boca é cheia de maldições, mentiras e ameaças; em sua língua há violência e maldade.

[[v19-10-8]]

^<<v19-10-8,8>>^ Fica de tocaia nos povoados, à espera para matar inocentes; está sempre à procura de vítimas indefesas.

[[v19-10-9]]

^<<v19-10-9,9>>^ Como o leão à espreita em seu esconderijo, aguarda para atacar os desamparados. Como o caçador, ele os apanha e os arrasta dali.

[[v19-10-10]]

^<<v19-10-10,10>>^ As vítimas indefesas são esmagadas; caem sob a força do perverso.

[[v19-10-11]]

^<<v19-10-11,11>>^ O perverso diz consigo: "Deus não se importa! Fechou os olhos e não vê o que faço!".

[[v19-10-12]]

^<<v19-10-12,12>>^ Levanta-te, SENHOR! Castiga o perverso, ó Deus! Não te esqueças dos indefesos!

[[v19-10-13]]

^<<v19-10-13,13>>^ Por que o perverso continua a desprezar a Deus? Ele pensa: "Deus jamais me pedirá contas".

[[v19-10-14]]

^<<v19-10-14,14>>^ Tu, porém, vês o sofrimento e a angústia que ele causa; observa-o e castiga-o. O indefeso confia em ti; tu amparas o órfão.

[[v19-10-15]]

^<<v19-10-15,15>>^ Quebra os braços dessa gente má e perversa; pede contas de sua maldade até nada mais restar.

[[v19-10-16]]

^<<v19-10-16,16>>^ O SENHOR é rei para todo o sempre! As nações desaparecerão de sua terra.

[[v19-10-17]]

^<<v19-10-17,17>>^ Tu, SENHOR, conheces o desejo dos humildes; ouvirás seu clamor e os confortarás.

[[v19-10-18]]

^<<v19-10-18,18>>^ Farás justiça ao órfão e ao oprimido, para que nenhum simples mortal volte a lhes causar terror.

'''

xref:019-salmos/019-salmos-009.adoc#v19-9-0[&#60; Capítulo Anterior] | <<v19-10-0,Topo>> | xref:019-salmos/019-salmos-011.adoc#v19-11-0[Próximo Capítulo &#62;]