include::./index.adoc[]

[[v19-46-0]]
=== Salmos, 46
// nvt ?, NVT - Nova Versão Transformadora

[[v19-46-1]]

^<<v19-46-1,1>>^ Deus é nosso refúgio e nossa força, sempre pronto a nos socorrer em tempos de aflição.

[[v19-46-2]]

^<<v19-46-2,2>>^ Portanto, não temeremos quando vierem terremotos e montes desabarem no mar.

[[v19-46-3]]

^<<v19-46-3,3>>^ Que o oceano estrondeie e espumeje! Que os montes estremeçam enquanto as águas se elevam! Interlúdio

[[v19-46-4]]

^<<v19-46-4,4>>^ Um rio e seus canais alegram a cidade de nosso Deus, o santo lugar do Altíssimo.

[[v19-46-5]]

^<<v19-46-5,5>>^ Deus habita nessa cidade, e ela não será destruída; desde o amanhecer, Deus a protegerá.

[[v19-46-6]]

^<<v19-46-6,6>>^ As nações estão em confusão, e seus reinos desmoronam. A voz de Deus troveja, e a terra se dissolve.

[[v19-46-7]]

^<<v19-46-7,7>>^ O SENHOR dos Exércitos está entre nós; o Deus de Jacó é nossa fortaleza. Interlúdio

[[v19-46-8]]

^<<v19-46-8,8>>^ Venham, contemplem as gloriosas obras do SENHOR! Vejam como ele traz destruição sobre o mundo!

[[v19-46-9]]

^<<v19-46-9,9>>^ Acaba com as guerras em toda a terra, quebra o arco e parte ao meio a lança, e destrói os escudos com fogo.

[[v19-46-10]]

^<<v19-46-10,10>>^ "Aquietem-se e saibam que eu sou Deus! Serei honrado entre todas as nações; serei honrado no mundo inteiro."

[[v19-46-11]]

^<<v19-46-11,11>>^ O SENHOR dos Exércitos está entre nós; o Deus de Jacó é nossa fortaleza. Interlúdio

'''

xref:019-salmos/019-salmos-045.adoc#v19-45-0[&#60; Capítulo Anterior] | <<v19-46-0,Topo>> | xref:019-salmos/019-salmos-047.adoc#v19-47-0[Próximo Capítulo &#62;]