include::./index.adoc[]

[[v19-149-0]]
=== Salmos, 149
// nvt ?, NVT - Nova Versão Transformadora

[[v19-149-1]]

^<<v19-149-1,1>>^ Louvado seja o SENHOR! Cantem ao SENHOR um cântico novo, cantem louvores a ele na congregação dos fiéis.

[[v19-149-2]]

^<<v19-149-2,2>>^ Ó Israel, alegre-se em seu Criador! Ó povo de Sião, exulte em seu Rei!

[[v19-149-3]]

^<<v19-149-3,3>>^ Louvem o nome dele com danças, acompanhadas de tamborins e harpas.

[[v19-149-4]]

^<<v19-149-4,4>>^ Pois o SENHOR tem prazer em seu povo; ele coroa os humildes com vitória.

[[v19-149-5]]

^<<v19-149-5,5>>^ Alegrem-se os fiéis porque ele os honra; cantem de alegria em suas camas.

[[v19-149-6]]

^<<v19-149-6,6>>^ Louvores a Deus estejam em seus lábios, e uma espada afiada em suas mãos,

[[v19-149-7]]

^<<v19-149-7,7>>^ para se vingarem das nações e castigarem os povos,

[[v19-149-8]]

^<<v19-149-8,8>>^ para prenderem seus reis com algemas e seus líderes, com correntes de ferro,

[[v19-149-9]]

^<<v19-149-9,9>>^ para executarem a sentença escrita contra eles; esse é o glorioso privilégio de seus fiéis. Louvado seja o SENHOR!

'''

xref:019-salmos/019-salmos-148.adoc#v19-148-0[&#60; Capítulo Anterior] | <<v19-149-0,Topo>> | xref:019-salmos/019-salmos-150.adoc#v19-150-0[Próximo Capítulo &#62;]