include::./index.adoc[]

[[v19-118-0]]
=== Salmos, 118
// nvt ?, NVT - Nova Versão Transformadora

[[v19-118-1]]

^<<v19-118-1,1>>^ Deem graças ao SENHOR, porque ele é bom; seu amor dura para sempre!

[[v19-118-2]]

^<<v19-118-2,2>>^ Todo o Israel diga: "Seu amor dura para sempre!".

[[v19-118-3]]

^<<v19-118-3,3>>^ Os sacerdotes, descendentes de Arão, digam: "Seu amor dura para sempre!".

[[v19-118-4]]

^<<v19-118-4,4>>^ Todos que temem o SENHOR digam: "Seu amor dura para sempre!".

[[v19-118-5]]

^<<v19-118-5,5>>^ Em minha angústia, orei ao SENHOR; o SENHOR me ouviu e me livrou.

[[v19-118-6]]

^<<v19-118-6,6>>^ O SENHOR está comigo, portanto não temerei; o que me podem fazer os simples mortais?

[[v19-118-7]]

^<<v19-118-7,7>>^ Sim, o SENHOR está comigo, e ele me ajudará; olharei com triunfo para os que me odeiam.

[[v19-118-8]]

^<<v19-118-8,8>>^ É melhor refugiar-se no Senhor que confiar em pessoas.

[[v19-118-9]]

^<<v19-118-9,9>>^ É melhor refugiar-se no Senhor que confiar em príncipes.

[[v19-118-10]]

^<<v19-118-10,10>>^ Todas as nações hostis me cercaram, mas eu as destruí em nome do SENHOR.

[[v19-118-11]]

^<<v19-118-11,11>>^ Sim, elas me cercaram de todos os lados, mas eu as destruí em nome do SENHOR.

[[v19-118-12]]

^<<v19-118-12,12>>^ Como um enxame de abelhas me rodearam e arderam contra mim como um fogo crepitante, mas eu as destruí em nome do SENHOR.

[[v19-118-13]]

^<<v19-118-13,13>>^ Meus inimigos fizeram todo o possível para me derrubar, mas o SENHOR me sustentou.

[[v19-118-14]]

^<<v19-118-14,14>>^ O SENHOR é minha força e meu cântico; ele é minha salvação.

[[v19-118-15]]

^<<v19-118-15,15>>^ No acampamento dos justos há cânticos de alegria e vitória; a mão direita do SENHOR realizou grandes feitos!

[[v19-118-16]]

^<<v19-118-16,16>>^ A mão direita do SENHOR se levanta em triunfo; a mão direita do SENHOR realizou grandes feitos!

[[v19-118-17]]

^<<v19-118-17,17>>^ Não morrerei; pelo contrário, viverei para contar o que o SENHOR fez.

[[v19-118-18]]

^<<v19-118-18,18>>^ O SENHOR me castigou severamente, mas não me deixou morrer.

[[v19-118-19]]

^<<v19-118-19,19>>^ Abram para mim as portas por onde entram os justos; entrarei e darei graças ao SENHOR.

[[v19-118-20]]

^<<v19-118-20,20>>^ Essas portas conduzem à presença do SENHOR, e os justos entram por elas.

[[v19-118-21]]

^<<v19-118-21,21>>^ Eu te dou graças porque respondeste à minha oração e me deste vitória!

[[v19-118-22]]

^<<v19-118-22,22>>^ A pedra que os construtores rejeitaram se tornou a pedra angular.

[[v19-118-23]]

^<<v19-118-23,23>>^ Isso é obra do Senhor e é maravilhosa de ver.

[[v19-118-24]]

^<<v19-118-24,24>>^ Este é o dia que o SENHOR fez; nele nos alegraremos e exultaremos.

[[v19-118-25]]

^<<v19-118-25,25>>^ Ó SENHOR, por favor, salva-nos! Ó SENHOR, dá-nos sucesso!

[[v19-118-26]]

^<<v19-118-26,26>>^ Bendito é o que vem em nome do SENHOR; nós os abençoamos da casa do SENHOR.

[[v19-118-27]]

^<<v19-118-27,27>>^ O SENHOR é Deus e resplandece sobre nós; peguem o sacrifício e amarrem-no com cordas sobre o altar.

[[v19-118-28]]

^<<v19-118-28,28>>^ Tu és meu Deus, e eu te louvarei! Tu és meu Deus, e eu te exaltarei!

[[v19-118-29]]

^<<v19-118-29,29>>^ Deem graças ao SENHOR, porque ele é bom; seu amor dura para sempre!

'''

xref:019-salmos/019-salmos-117.adoc#v19-117-0[&#60; Capítulo Anterior] | <<v19-118-0,Topo>> | xref:019-salmos/019-salmos-119.adoc#v19-119-0[Próximo Capítulo &#62;]