include::./index.adoc[]

[[v19-30-0]]
=== Salmos, 30
// nvt ?, NVT - Nova Versão Transformadora

[[v19-30-1]]

^<<v19-30-1,1>>^ Eu te exaltarei, SENHOR, pois me livraste; não permitiste que meus inimigos rissem de mim.

[[v19-30-2]]

^<<v19-30-2,2>>^ SENHOR, meu Deus, clamei a ti por socorro, e restauraste minha saúde.

[[v19-30-3]]

^<<v19-30-3,3>>^ SENHOR, da sepultura me tiraste e não me deixaste cair na cova da morte.

[[v19-30-4]]

^<<v19-30-4,4>>^ Cantem ao SENHOR, todos que lhe são fiéis! Louvem seu santo nome,

[[v19-30-5]]

^<<v19-30-5,5>>^ pois sua ira dura apenas um instante, mas seu favor, a vida inteira! O choro pode durar toda a noite, mas a alegria vem com o amanhecer.

[[v19-30-6]]

^<<v19-30-6,6>>^ Quando eu era próspero, dizia: "Agora, nada pode me derrubar!".

[[v19-30-7]]

^<<v19-30-7,7>>^ Ó SENHOR, teu favor me mantinha firme como uma montanha; então o SENHOR me deu as costas, e entrei em pânico.

[[v19-30-8]]

^<<v19-30-8,8>>^ Clamei a ti, SENHOR, supliquei ao Senhor por misericórdia:

[[v19-30-9]]

^<<v19-30-9,9>>^ "Que vantagem terás se eu morrer, se eu descer à cova? Acaso o pó te louvará? Falará de tua fidelidade?

[[v19-30-10]]

^<<v19-30-10,10>>^ Ouve-me, SENHOR, e tem misericórdia de mim; ajuda-me, SENHOR!".

[[v19-30-11]]

^<<v19-30-11,11>>^ Transformaste meu pranto em dança; tiraste minhas roupas de luto e me vestiste de alegria,

[[v19-30-12]]

^<<v19-30-12,12>>^ para que eu cante louvores a ti e não me cale. SENHOR, meu Deus, te darei graças para sempre!

'''

xref:019-salmos/019-salmos-029.adoc#v19-29-0[&#60; Capítulo Anterior] | <<v19-30-0,Topo>> | xref:019-salmos/019-salmos-031.adoc#v19-31-0[Próximo Capítulo &#62;]