include::./index.adoc[]

[[v19-75-0]]
=== Salmos, 75
// nvt ?, NVT - Nova Versão Transformadora

[[v19-75-1]]

^<<v19-75-1,1>>^ Graças te damos, ó Deus! Graças te damos porque estás próximo; em toda parte se fala de tuas maravilhas.

[[v19-75-2]]

^<<v19-75-2,2>>^ Tu disseste: "No tempo que determinei, julgarei com justiça.

[[v19-75-3]]

^<<v19-75-3,3>>^ Quando a terra e seus moradores estremecem, sou eu que mantenho firmes seus alicerces. Interlúdio

[[v19-75-4]]

^<<v19-75-4,4>>^ "Adverti aos orgulhosos: ‘Parem de contar vantagem!’. Disse aos perversos: ‘Não levantem os punhos!

[[v19-75-5]]

^<<v19-75-5,5>>^ Não levantem os punhos aos céus em rebeldia, nem falem com tamanha arrogância’".

[[v19-75-6]]

^<<v19-75-6,6>>^ Pois ninguém na terra, de leste a oeste, nem mesmo no deserto, deve exaltar a si mesmo.

[[v19-75-7]]

^<<v19-75-7,7>>^ Somente Deus é quem julga; ele decide quem se levantará e quem cairá.

[[v19-75-8]]

^<<v19-75-8,8>>^ Pois o SENHOR tem na mão um cálice cujo vinho espuma misturado com especiarias. Ele derrama o vinho, e todos os perversos o bebem até a última gota.

[[v19-75-9]]

^<<v19-75-9,9>>^ Quanto a mim, sempre anunciarei o que Deus tem feito; cantarei louvores ao Deus de Jacó.

[[v19-75-10]]

^<<v19-75-10,10>>^ Pois Deus disse: "Acabarei com a força dos perversos, mas farei crescer o poder dos justos".

'''

xref:019-salmos/019-salmos-074.adoc#v19-74-0[&#60; Capítulo Anterior] | <<v19-75-0,Topo>> | xref:019-salmos/019-salmos-076.adoc#v19-76-0[Próximo Capítulo &#62;]