include::./index.adoc[]

[[v19-85-0]]
=== Salmos, 85
// nvt ?, NVT - Nova Versão Transformadora

[[v19-85-1]]

^<<v19-85-1,1>>^ SENHOR, abençoaste a tua terra; restauraste a condição de Israel.

[[v19-85-2]]

^<<v19-85-2,2>>^ Perdoaste a culpa do teu povo; cobriste todos os seus pecados. Interlúdio

[[v19-85-3]]

^<<v19-85-3,3>>^ Reprimiste tua fúria, sim, refreaste tua ira ardente.

[[v19-85-4]]

^<<v19-85-4,4>>^ Agora, ó Deus de nossa salvação, restaura-nos; deixa de lado tua ira contra nós.

[[v19-85-5]]

^<<v19-85-5,5>>^ Ficarás indignado conosco para sempre? Prolongarás tua ira por todas as gerações?

[[v19-85-6]]

^<<v19-85-6,6>>^ Não nos reanimarás, para que o teu povo se alegre em ti?

[[v19-85-7]]

^<<v19-85-7,7>>^ Mostra-nos o teu amor, SENHOR, e concede-nos a tua salvação.

[[v19-85-8]]

^<<v19-85-8,8>>^ Ouço com atenção o que Deus, o SENHOR, diz, pois ele fala de paz a seu povo fiel; que não voltem, porém, a seus caminhos insensatos.

[[v19-85-9]]

^<<v19-85-9,9>>^ Certamente sua salvação está perto dos que o temem; então nossa terra se encherá de sua glória.

[[v19-85-10]]

^<<v19-85-10,10>>^ O amor e a verdade se encontraram, a justiça e a paz se beijaram.

[[v19-85-11]]

^<<v19-85-11,11>>^ A verdade brota da terra, e a justiça sorri dos céus.

[[v19-85-12]]

^<<v19-85-12,12>>^ Sim, o SENHOR dará suas bênçãos; nossa terra produzirá uma farta colheita.

[[v19-85-13]]

^<<v19-85-13,13>>^ A justiça vai adiante dele e prepara o caminho para os seus passos.

'''

xref:019-salmos/019-salmos-084.adoc#v19-84-0[&#60; Capítulo Anterior] | <<v19-85-0,Topo>> | xref:019-salmos/019-salmos-086.adoc#v19-86-0[Próximo Capítulo &#62;]