include::./index.adoc[]

[[v19-50-0]]
=== Salmos, 50
// nvt ?, NVT - Nova Versão Transformadora

[[v19-50-1]]

^<<v19-50-1,1>>^ O SENHOR, o Deus Poderoso, falou; convocou toda a humanidade, desde onde o sol nasce até onde se põe.

[[v19-50-2]]

^<<v19-50-2,2>>^ Do monte Sião, lugar de perfeita beleza, Deus resplandece.

[[v19-50-3]]

^<<v19-50-3,3>>^ Nosso Deus se aproxima e não está em silêncio. Fogo devora tudo em seu caminho, e ao seu redor há uma grande tempestade.

[[v19-50-4]]

^<<v19-50-4,4>>^ Ele convoca os céus em cima e a terra embaixo, para testemunharem o julgamento de seu povo.

[[v19-50-5]]

^<<v19-50-5,5>>^ "Tragam aqui os que me são fiéis, os que fizeram comigo uma aliança de oferta de sacrifícios."

[[v19-50-6]]

^<<v19-50-6,6>>^ Então, que os céus proclamem sua justiça, pois o próprio Deus será o juiz. Interlúdio

[[v19-50-7]]

^<<v19-50-7,7>>^ "Ó meu povo, ouça o que direi, estas são minhas acusações contra você, ó Israel: Eu sou Deus, o seu Deus!

[[v19-50-8]]

^<<v19-50-8,8>>^ Não o reprovo por seus sacrifícios, nem pelos holocaustos que sempre oferecem.

[[v19-50-9]]

^<<v19-50-9,9>>^ Não preciso, contudo, dos novilhos de seus estábulos, nem dos bodes de seus currais.

[[v19-50-10]]

^<<v19-50-10,10>>^ Pois são meus todos os animais dos bosques, e sou dono do gado nos milhares de colinas.

[[v19-50-11]]

^<<v19-50-11,11>>^ Conheço cada pássaro dos montes, e todos os animais dos campos me pertencem.

[[v19-50-12]]

^<<v19-50-12,12>>^ Se eu tivesse fome, não lhes diria, pois meu é o mundo inteiro e tudo que nele há.

[[v19-50-13]]

^<<v19-50-13,13>>^ Acaso como a carne de touros ou bebo o sangue de bodes?

[[v19-50-14]]

^<<v19-50-14,14>>^ Ofereçam a Deus seu sacrifício de gratidão e cumpram os votos que fizerem ao Altíssimo.

[[v19-50-15]]

^<<v19-50-15,15>>^ Então clamem a mim em tempos de aflição; eu os livrarei, e vocês me darão glória."

[[v19-50-16]]

^<<v19-50-16,16>>^ Ao perverso, porém, Deus diz: "De que adianta recitar meus decretos e falar a respeito de minha aliança?

[[v19-50-17]]

^<<v19-50-17,17>>^ Pois você recusa minha disciplina e trata minhas palavras como lixo.

[[v19-50-18]]

^<<v19-50-18,18>>^ Quando vê ladrões, aprova o que fazem e passa seu tempo com adúlteros.

[[v19-50-19]]

^<<v19-50-19,19>>^ Sua boca está cheia de maldade, e sua língua, repleta de mentiras.

[[v19-50-20]]

^<<v19-50-20,20>>^ Vive a caluniar seu irmão, filho de sua própria mãe.

[[v19-50-21]]

^<<v19-50-21,21>>^ Enquanto você assim agia, permaneci calado, e você pensou que éramos iguais. Agora, porém, o repreenderei; contra você apresentarei minhas acusações.

[[v19-50-22]]

^<<v19-50-22,22>>^ Pensem bem e arrependam-se todos vocês que de mim se esquecem; caso contrário, eu os despedaçarei e ninguém os ajudará.

[[v19-50-23]]

^<<v19-50-23,23>>^ A gratidão, porém, é um sacrifício que de fato me honra; se permanecerem em meus caminhos, eu lhes revelarei a salvação de Deus".

'''

xref:019-salmos/019-salmos-049.adoc#v19-49-0[&#60; Capítulo Anterior] | <<v19-50-0,Topo>> | xref:019-salmos/019-salmos-051.adoc#v19-51-0[Próximo Capítulo &#62;]