include::./index.adoc[]

[[v19-91-0]]
=== Salmos, 91
// nvt ?, NVT - Nova Versão Transformadora

[[v19-91-1]]

^<<v19-91-1,1>>^ Aquele que habita no abrigo do Altíssimo encontrará descanso à sombra do Todo-poderoso.

[[v19-91-2]]

^<<v19-91-2,2>>^ Isto eu declaro a respeito do SENHOR: ele é meu refúgio, meu lugar seguro, ele é meu Deus e nele confio.

[[v19-91-3]]

^<<v19-91-3,3>>^ Pois ele o livrará das armadilhas da vida e o protegerá de doenças mortais.

[[v19-91-4]]

^<<v19-91-4,4>>^ Ele o cobrirá com as suas penas e o abrigará sob as suas asas; a sua fidelidade é armadura e proteção.

[[v19-91-5]]

^<<v19-91-5,5>>^ Não tenha medo dos terrores da noite, nem da flecha que voa durante o dia.

[[v19-91-6]]

^<<v19-91-6,6>>^ Não tema a praga que se aproxima na escuridão, nem a calamidade que devasta ao meio-dia.

[[v19-91-7]]

^<<v19-91-7,7>>^ Ainda que mil caiam ao seu lado e dez mil morram ao seu redor, você não será atingido.

[[v19-91-8]]

^<<v19-91-8,8>>^ Basta abrir os olhos, e verá como são castigados os perversos.

[[v19-91-9]]

^<<v19-91-9,9>>^ Se você se refugiar no SENHOR, se fizer do Altíssimo seu abrigo,

[[v19-91-10]]

^<<v19-91-10,10>>^ nenhum mal o atingirá, nenhuma praga se aproximará de sua casa.

[[v19-91-11]]

^<<v19-91-11,11>>^ Pois ele ordenará a seus anjos que o protejam aonde quer que você vá.

[[v19-91-12]]

^<<v19-91-12,12>>^ Eles o sustentarão com as mãos, para que não machuque o pé em alguma pedra.

[[v19-91-13]]

^<<v19-91-13,13>>^ Você pisará leões e cobras, esmagará leões ferozes e serpentes debaixo dos pés.

[[v19-91-14]]

^<<v19-91-14,14>>^ O SENHOR diz: "Livrarei aquele que me ama, protegerei o que confia em meu nome.

[[v19-91-15]]

^<<v19-91-15,15>>^ Quando clamar por mim, eu responderei e estarei com ele em meio às dificuldades; eu o resgatarei e lhe darei honra.

[[v19-91-16]]

^<<v19-91-16,16>>^ Com vida longa o recompensarei e lhe darei minha salvação".

'''

xref:019-salmos/019-salmos-090.adoc#v19-90-0[&#60; Capítulo Anterior] | <<v19-91-0,Topo>> | xref:019-salmos/019-salmos-092.adoc#v19-92-0[Próximo Capítulo &#62;]