include::./index.adoc[]

[[v19-16-0]]
=== Salmos, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v19-16-1]]

^<<v19-16-1,1>>^ Guarda-me, ó Deus, pois em ti me refugio.

[[v19-16-2]]

^<<v19-16-2,2>>^ Eu disse ao SENHOR: "Tu és meu Senhor! Tudo que tenho de bom vem de ti".

[[v19-16-3]]

^<<v19-16-3,3>>^ Os que são fiéis aqui na terra são os verdadeiros heróis; tenho prazer na companhia deles.

[[v19-16-4]]

^<<v19-16-4,4>>^ Muitas são as aflições dos que correm atrás de outros deuses; não participarei de seus sacrifícios de sangue, nem invocarei o nome deles.

[[v19-16-5]]

^<<v19-16-5,5>>^ Somente tu, SENHOR, és minha herança, meu cálice de bênçãos; tu guardas tudo que possuo.

[[v19-16-6]]

^<<v19-16-6,6>>^ A terra que me deste é agradável; que herança maravilhosa!

[[v19-16-7]]

^<<v19-16-7,7>>^ Louvarei o SENHOR, que me guia; mesmo à noite meu coração me ensina.

[[v19-16-8]]

^<<v19-16-8,8>>^ Sei que o SENHOR está sempre comigo; não serei abalado, pois ele está à minha direita.

[[v19-16-9]]

^<<v19-16-9,9>>^ Não é de admirar que meu coração esteja alegre e eu exulte; meu corpo repousa em segurança.

[[v19-16-10]]

^<<v19-16-10,10>>^ Pois tu não deixarás minha alma entre os mortos, nem permitirás que teu santo apodreça no túmulo.

[[v19-16-11]]

^<<v19-16-11,11>>^ Tu me mostrarás o caminho da vida e me darás a alegria de tua presença e o prazer de viver contigo para sempre.

'''

xref:019-salmos/019-salmos-015.adoc#v19-15-0[&#60; Capítulo Anterior] | <<v19-16-0,Topo>> | xref:019-salmos/019-salmos-017.adoc#v19-17-0[Próximo Capítulo &#62;]