include::./index.adoc[]

[[v19-116-0]]
=== Salmos, 116
// nvt ?, NVT - Nova Versão Transformadora

[[v19-116-1]]

^<<v19-116-1,1>>^ Amo o SENHOR, porque ele ouve a minha voz e as minhas orações.

[[v19-116-2]]

^<<v19-116-2,2>>^ Porque ele se inclina para ouvir, orarei enquanto viver.

[[v19-116-3]]

^<<v19-116-3,3>>^ A morte me envolveu com suas cordas, e os terrores da sepultura me dominaram; não via outra coisa senão sofrimento e tristeza.

[[v19-116-4]]

^<<v19-116-4,4>>^ Então clamei pelo nome do SENHOR: "Livra-me, SENHOR!".

[[v19-116-5]]

^<<v19-116-5,5>>^ O SENHOR é compassivo e justo; o nosso Deus é misericordioso!

[[v19-116-6]]

^<<v19-116-6,6>>^ O SENHOR protege os ingênuos; eu estava diante da morte, e ele me salvou.

[[v19-116-7]]

^<<v19-116-7,7>>^ Volte, minha alma, a descansar, pois o SENHOR lhe tem sido bom.

[[v19-116-8]]

^<<v19-116-8,8>>^ Ele livrou minha alma da morte, meus olhos, das lágrimas, meus pés, da queda.

[[v19-116-9]]

^<<v19-116-9,9>>^ Por isso, andarei na presença do Senhor enquanto viver aqui na terra.

[[v19-116-10]]

^<<v19-116-10,10>>^ Eu cri, por isso disse: "Estou profundamente aflito!".

[[v19-116-11]]

^<<v19-116-11,11>>^ Em meu desespero, declarei: "Todos são mentirosos!".

[[v19-116-12]]

^<<v19-116-12,12>>^ Que posso oferecer ao Senhor por tudo que ele me tem feito?

[[v19-116-13]]

^<<v19-116-13,13>>^ Celebrarei meu livramento e louvarei o nome do SENHOR.

[[v19-116-14]]

^<<v19-116-14,14>>^ Cumprirei meus votos ao Senhor na presença de todo o seu povo.

[[v19-116-15]]

^<<v19-116-15,15>>^ O SENHOR se importa profundamente com a morte de seus fiéis.

[[v19-116-16]]

^<<v19-116-16,16>>^ Ó SENHOR, sou teu servo, sim, teu servo, teu humilde servo; tu me livraste de minhas correntes.

[[v19-116-17]]

^<<v19-116-17,17>>^ Oferecerei a ti um sacrifício de ação de graças e louvarei o nome do SENHOR.

[[v19-116-18]]

^<<v19-116-18,18>>^ Cumprirei meus votos ao Senhor na presença de todo o seu povo,

[[v19-116-19]]

^<<v19-116-19,19>>^ na casa do SENHOR, no meio de Jerusalém. Louvado seja o SENHOR!

'''

xref:019-salmos/019-salmos-115.adoc#v19-115-0[&#60; Capítulo Anterior] | <<v19-116-0,Topo>> | xref:019-salmos/019-salmos-117.adoc#v19-117-0[Próximo Capítulo &#62;]