include::./index.adoc[]

[[v19-14-0]]
=== Salmos, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v19-14-1]]

^<<v19-14-1,1>>^ Os tolos dizem em seu coração: "Não há Deus". São corruptos e praticam o mal; nenhum deles faz o bem.

[[v19-14-2]]

^<<v19-14-2,2>>^ O SENHOR olha dos céus para toda a humanidade, para ver se alguém é sábio, se alguém busca a Deus.

[[v19-14-3]]

^<<v19-14-3,3>>^ Todos, porém, se desviaram; todos se corromperam. Ninguém faz o bem, nem um sequer!

[[v19-14-4]]

^<<v19-14-4,4>>^ Acaso os que praticam o mal jamais aprenderão? Devoram meu povo como se fosse pão e nem pensam em orar ao SENHOR.

[[v19-14-5]]

^<<v19-14-5,5>>^ Grande terror se apoderará deles, pois Deus está com os que lhe obedecem.

[[v19-14-6]]

^<<v19-14-6,6>>^ Os perversos frustram os planos dos oprimidos, mas o SENHOR protegerá seu povo.

[[v19-14-7]]

^<<v19-14-7,7>>^ Quem virá do monte Sião para salvar Israel? Quando o SENHOR restaurar seu povo, Jacó dará gritos de alegria, e Israel exultará.

'''

xref:019-salmos/019-salmos-013.adoc#v19-13-0[&#60; Capítulo Anterior] | <<v19-14-0,Topo>> | xref:019-salmos/019-salmos-015.adoc#v19-15-0[Próximo Capítulo &#62;]