include::./index.adoc[]

[[v19-42-0]]
=== Salmos, 42
// nvt ?, NVT - Nova Versão Transformadora

[[v19-42-1]]

^<<v19-42-1,1>>^ Como a corça anseia pelas correntes de água, assim minha alma anseia por ti, ó Deus.

[[v19-42-2]]

^<<v19-42-2,2>>^ Tenho sede de Deus, do Deus vivo; quando poderei estar na presença dele?

[[v19-42-3]]

^<<v19-42-3,3>>^ Dia e noite, as lágrimas têm sido meu alimento, enquanto zombam de mim o tempo todo, dizendo: "Onde está o seu Deus?".

[[v19-42-4]]

^<<v19-42-4,4>>^ Meu coração se enche de tristeza, pois me lembro de como eu andava com a multidão de adoradores, à frente do cortejo que subia até a casa de Deus, cantando de alegria e dando graças, em meio aos sons de uma grande festa.

[[v19-42-5]]

^<<v19-42-5,5>>^ Por que você está tão abatida, ó minha alma? Por que está tão triste? Espere em Deus! Ainda voltarei a louvá-lo, meu Salvador e

[[v19-42-6]]

^<<v19-42-6,6>>^ meu Deus! Agora estou profundamente abatido, mas me lembro de ti, desde o distante monte Hermom, onde nasce o Jordão, desde a terra do monte Mizar.

[[v19-42-7]]

^<<v19-42-7,7>>^ Ouço o tumulto do mar revolto, enquanto suas ondas e correntezas passam sobre mim.

[[v19-42-8]]

^<<v19-42-8,8>>^ Durante o dia, porém, o SENHOR me derrama seu amor, e à noite entoo seus cânticos e faço orações ao Deus que me dá vida.

[[v19-42-9]]

^<<v19-42-9,9>>^ Clamo: "Ó Deus, minha rocha, por que te esqueceste de mim? Por que tenho de andar entristecido, oprimido por meus inimigos?".

[[v19-42-10]]

^<<v19-42-10,10>>^ Os insultos deles me quebram os ossos; zombam de mim o tempo todo, dizendo: "Onde está o seu Deus?".

[[v19-42-11]]

^<<v19-42-11,11>>^ Por que você está tão abatida, ó minha alma? Por que está tão triste? Espere em Deus! Ainda voltarei a louvá-lo, meu Salvador e meu Deus!

'''

xref:019-salmos/019-salmos-041.adoc#v19-41-0[&#60; Capítulo Anterior] | <<v19-42-0,Topo>> | xref:019-salmos/019-salmos-043.adoc#v19-43-0[Próximo Capítulo &#62;]