include::./index.adoc[]

[[v19-72-0]]
=== Salmos, 72
// nvt ?, NVT - Nova Versão Transformadora

[[v19-72-1]]

^<<v19-72-1,1>>^ Dá ao rei tua justiça, ó Deus, e concede retidão ao filho do rei.

[[v19-72-2]]

^<<v19-72-2,2>>^ Ajuda-o a julgar teu povo corretamente; que os pobres sejam tratados com imparcialidade.

[[v19-72-3]]

^<<v19-72-3,3>>^ Que os montes produzam prosperidade para todos, e que as colinas deem muitos frutos.

[[v19-72-4]]

^<<v19-72-4,4>>^ Ajuda-o a defender os pobres dentre o povo, a salvar os filhos dos necessitados e a esmagar seus opressores.

[[v19-72-5]]

^<<v19-72-5,5>>^ Que eles te temam enquanto o sol brilhar, enquanto a lua permanecer no céu; sim, para sempre!

[[v19-72-6]]

^<<v19-72-6,6>>^ Que o governo do rei seja como a chuva sobre a grama recém-cortada, como os aguaceiros que regam a terra.

[[v19-72-7]]

^<<v19-72-7,7>>^ Que todos os justos floresçam durante seu reinado, que haja grande paz até que a lua deixe de existir.

[[v19-72-8]]

^<<v19-72-8,8>>^ Que ele reine de mar a mar, e do rio Eufrates até os confins da terra.

[[v19-72-9]]

^<<v19-72-9,9>>^ Nômades do deserto se curvarão diante dele, seus inimigos lamberão o pó a seus pés.

[[v19-72-10]]

^<<v19-72-10,10>>^ Os reis de Társis e de outras terras distantes lhe pagarão tributos. Os reis de Sabá e de Sebá lhe darão presentes.

[[v19-72-11]]

^<<v19-72-11,11>>^ Todos os reis se curvarão diante dele, e todas as nações o servirão.

[[v19-72-12]]

^<<v19-72-12,12>>^ Ele livrará o pobre que clamar por socorro e ajudará o oprimido indefeso.

[[v19-72-13]]

^<<v19-72-13,13>>^ Ele tem compaixão do fraco e do necessitado e os salvará.

[[v19-72-14]]

^<<v19-72-14,14>>^ Ele os resgatará da opressão e da violência, pois considera preciosa a vida deles.

[[v19-72-15]]

^<<v19-72-15,15>>^ Viva o rei! Que ele receba o ouro de Sabá. Que o povo sempre ore por ele e o abençoe o dia todo.

[[v19-72-16]]

^<<v19-72-16,16>>^ Que haja fartura de cereais em toda a terra, crescendo até o alto dos montes. Que as árvores frutíferas sejam como as do Líbano, e que o povo prospere como grama no campo.

[[v19-72-17]]

^<<v19-72-17,17>>^ Que o nome do rei permaneça para sempre, que dure enquanto o sol brilhar. Que todas as nações sejam abençoadas por meio dele e o louvem.

[[v19-72-18]]

^<<v19-72-18,18>>^ Louvado seja o SENHOR Deus, o Deus de Israel, o único que realiza tais maravilhas!

[[v19-72-19]]

^<<v19-72-19,19>>^ Louvado seja seu nome glorioso para sempre! Que sua glória encha toda a terra. Amém e amém!

[[v19-72-20]]

^<<v19-72-20,20>>^ Terminam aqui as orações de Davi, filho de Jessé.

'''

xref:019-salmos/019-salmos-071.adoc#v19-71-0[&#60; Capítulo Anterior] | <<v19-72-0,Topo>> | xref:019-salmos/019-salmos-073.adoc#v19-73-0[Próximo Capítulo &#62;]