include::./index.adoc[]

[[v19-48-0]]
=== Salmos, 48
// nvt ?, NVT - Nova Versão Transformadora

[[v19-48-1]]

^<<v19-48-1,1>>^ Grande é o Senhor e muito digno de louvor, na cidade de nosso Deus, em seu santo monte.

[[v19-48-2]]

^<<v19-48-2,2>>^ O monte Sião, o santo monte, é alto e magnífico; toda a terra se alegra em vê-lo; é a cidade do grande Rei.

[[v19-48-3]]

^<<v19-48-3,3>>^ O próprio Deus está em suas torres e se revela como seu protetor.

[[v19-48-4]]

^<<v19-48-4,4>>^ Os reis da terra uniram forças e avançaram contra a cidade.

[[v19-48-5]]

^<<v19-48-5,5>>^ Mas, quando a viram, ficaram espantados e fugiram aterrorizados.

[[v19-48-6]]

^<<v19-48-6,6>>^ Foram tomados de medo e se contorceram de dores, como a mulher no parto.

[[v19-48-7]]

^<<v19-48-7,7>>^ Tu os destruíste como os navios de Társis, despedaçados por um forte vento do leste.

[[v19-48-8]]

^<<v19-48-8,8>>^ Tínhamos ouvido falar da glória da cidade, mas agora a vimos com os próprios olhos, a cidade do SENHOR dos Exércitos. É a cidade de nosso Deus, que a manterá segura para sempre. Interlúdio

[[v19-48-9]]

^<<v19-48-9,9>>^ Ó Deus, em teu amor meditamos enquanto adoramos em teu templo.

[[v19-48-10]]

^<<v19-48-10,10>>^ Como teu nome merece, ó Deus, serás louvado até os confins da terra; tua forte mão direita está cheia de vitória.

[[v19-48-11]]

^<<v19-48-11,11>>^ Alegre-se o povo no monte Sião! Todas as cidades de Judá exultem por causa de teus decretos!

[[v19-48-12]]

^<<v19-48-12,12>>^ Percorram a cidade de Sião, vão e contem suas muitas torres.

[[v19-48-13]]

^<<v19-48-13,13>>^ Observem os muros fortificados e caminhem por todas as cidadelas, para que possam descrevê-las às gerações futuras.

[[v19-48-14]]

^<<v19-48-14,14>>^ Pois assim é nosso Deus; ele é nosso Deus para todo o sempre e nos guiará até o dia de nossa morte.

'''

xref:019-salmos/019-salmos-047.adoc#v19-47-0[&#60; Capítulo Anterior] | <<v19-48-0,Topo>> | xref:019-salmos/019-salmos-049.adoc#v19-49-0[Próximo Capítulo &#62;]