include::./index.adoc[]

[[v19-4-0]]
=== Salmos, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v19-4-1]]

^<<v19-4-1,1>>^ Responde-me quando clamo a ti, ó Deus que me faz justiça. Livra-me de minha angústia; tem compaixão de mim e ouve minha oração.

[[v19-4-2]]

^<<v19-4-2,2>>^ Até quando vocês jogarão minha reputação na lama? Até quando farão acusações infundadas e continuarão a mentir? Interlúdio

[[v19-4-3]]

^<<v19-4-3,3>>^ Estejam certos disto: o SENHOR separa o fiel para si; o SENHOR responderá quando eu clamar a ele.

[[v19-4-4]]

^<<v19-4-4,4>>^ Não pequem ao permitir que a ira os controle; reflitam durante a noite e permaneçam em silêncio. Interlúdio

[[v19-4-5]]

^<<v19-4-5,5>>^ Ofereçam os sacrifícios exigidos e confiem no SENHOR.

[[v19-4-6]]

^<<v19-4-6,6>>^ Muitos dizem: "Quem nos mostrará o bem?". Que a luz do teu rosto brilhe sobre nós, SENHOR!

[[v19-4-7]]

^<<v19-4-7,7>>^ Tu me deste alegria maior que a daqueles que têm fartas colheitas de cereais e vinho novo.

[[v19-4-8]]

^<<v19-4-8,8>>^ Em paz me deitarei e dormirei, pois somente tu, SENHOR, me guardas em segurança.

'''

xref:019-salmos/019-salmos-003.adoc#v19-3-0[&#60; Capítulo Anterior] | <<v19-4-0,Topo>> | xref:019-salmos/019-salmos-005.adoc#v19-5-0[Próximo Capítulo &#62;]