include::./index.adoc[]

[[v19-98-0]]
=== Salmos, 98
// nvt ?, NVT - Nova Versão Transformadora

[[v19-98-1]]

^<<v19-98-1,1>>^ Cantem ao SENHOR um cântico novo, pois ele fez maravilhas; sua mão direita e seu braço santo conquistaram a vitória!

[[v19-98-2]]

^<<v19-98-2,2>>^ O SENHOR anunciou seu poder de salvar e revelou sua justiça às nações.

[[v19-98-3]]

^<<v19-98-3,3>>^ Lembrou-se de seu amor e fidelidade a Israel; os confins da terra viram a vitória de nosso Deus.

[[v19-98-4]]

^<<v19-98-4,4>>^ Aclamem ao SENHOR todos os habitantes da terra; louvem-no em alta voz com alegres cânticos!

[[v19-98-5]]

^<<v19-98-5,5>>^ Cantem louvores ao SENHOR com a harpa, com a harpa e com cânticos harmoniosos,

[[v19-98-6]]

^<<v19-98-6,6>>^ com trombetas e ao som de cornetas; exultem e cantem diante do SENHOR, o Rei!

[[v19-98-7]]

^<<v19-98-7,7>>^ Deem gritos de louvor o mar e tudo que nele há, e também a terra e todos os seres vivos.

[[v19-98-8]]

^<<v19-98-8,8>>^ Os rios batam palmas, e os montes cantem de alegria

[[v19-98-9]]

^<<v19-98-9,9>>^ diante do SENHOR, pois ele vem julgar a terra. Julgará o mundo com justiça e as nações, com imparcialidade.

'''

xref:019-salmos/019-salmos-097.adoc#v19-97-0[&#60; Capítulo Anterior] | <<v19-98-0,Topo>> | xref:019-salmos/019-salmos-099.adoc#v19-99-0[Próximo Capítulo &#62;]