include::./index.adoc[]

[[v19-65-0]]
=== Salmos, 65
// nvt ?, NVT - Nova Versão Transformadora

[[v19-65-1]]

^<<v19-65-1,1>>^ Que grande louvor, ó Deus, te aguarda em Sião! Cumpriremos os votos que te fizemos,

[[v19-65-2]]

^<<v19-65-2,2>>^ pois respondes às nossas orações; todos virão a ti.

[[v19-65-3]]

^<<v19-65-3,3>>^ Embora sejam muitos os nossos pecados, tu perdoas nossa rebeldia.

[[v19-65-4]]

^<<v19-65-4,4>>^ Como é feliz aquele que tu escolhes para se aproximar de ti, aquele que vive em teus pátios. Quantas coisas boas nos saciarão em tua casa, em teu santo templo.

[[v19-65-5]]

^<<v19-65-5,5>>^ Tu respondes às nossas orações com notáveis feitos de justiça, ó Deus de nossa salvação. És a esperança de todos na terra, e até dos que navegam por mares distantes.

[[v19-65-6]]

^<<v19-65-6,6>>^ Formaste os montes com teu poder e de grande força te armaste.

[[v19-65-7]]

^<<v19-65-7,7>>^ Acalmaste a fúria dos mares e as ondas impetuosas, e calaste o tumulto das nações.

[[v19-65-8]]

^<<v19-65-8,8>>^ Os habitantes dos confins da terra se admiram com tuas maravilhas. Desde onde o sol nasce até onde se põe, despertas gritos de alegria.

[[v19-65-9]]

^<<v19-65-9,9>>^ Cuidas da terra e a regas, tornando-a rica e fértil. O rio de Deus tem muita água; proporciona fartura de cereais, porque assim ordenaste.

[[v19-65-10]]

^<<v19-65-10,10>>^ Encharcas o solo arado, dissolves os torrões e nivelas os sulcos. Amoleces a terra com chuvas e abençoas suas plantações.

[[v19-65-11]]

^<<v19-65-11,11>>^ Coroas o ano com boas colheitas; tuas pegadas deixam um rastro de fartura.

[[v19-65-12]]

^<<v19-65-12,12>>^ Os pastos no deserto ficam verdes, e as encostas dos montes florescem de alegria.

[[v19-65-13]]

^<<v19-65-13,13>>^ Os campos estão cobertos de rebanhos, e os vales, forrados de cereais; toda a terra grita e canta de alegria!

'''

xref:019-salmos/019-salmos-064.adoc#v19-64-0[&#60; Capítulo Anterior] | <<v19-65-0,Topo>> | xref:019-salmos/019-salmos-066.adoc#v19-66-0[Próximo Capítulo &#62;]