include::./index.adoc[]

[[v19-71-0]]
=== Salmos, 71
// nvt ?, NVT - Nova Versão Transformadora

[[v19-71-1]]

^<<v19-71-1,1>>^ Em ti, SENHOR, me refugio; não permitas que eu seja envergonhado.

[[v19-71-2]]

^<<v19-71-2,2>>^ Salva-me e resgata-me, pois tu és justo. Inclina teu ouvido para me escutar e livra-me.

[[v19-71-3]]

^<<v19-71-3,3>>^ Sê minha rocha de refúgio, onde sempre posso me esconder. Dá ordem para que eu seja liberto, pois és minha rocha e minha fortaleza.

[[v19-71-4]]

^<<v19-71-4,4>>^ Livra-me, meu Deus, do poder dos perversos, das garras dos opressores cruéis.

[[v19-71-5]]

^<<v19-71-5,5>>^ Só tu, Senhor, és minha esperança; confio em ti, SENHOR, desde a infância.

[[v19-71-6]]

^<<v19-71-6,6>>^ Sim, de ti dependo desde meu nascimento; cuidas de mim desde o ventre de minha mãe. Sempre te louvarei!

[[v19-71-7]]

^<<v19-71-7,7>>^ Minha vida é exemplo para muitos, pois tens sido minha força e meu refúgio.

[[v19-71-8]]

^<<v19-71-8,8>>^ Por isso, não deixo de te louvar; o dia todo declaro tua glória.

[[v19-71-9]]

^<<v19-71-9,9>>^ Não me rejeites agora, em minha velhice; não me abandones quando me faltam as forças.

[[v19-71-10]]

^<<v19-71-10,10>>^ Pois meus inimigos falam contra mim; juntos, planejam me matar.

[[v19-71-11]]

^<<v19-71-11,11>>^ Dizem: "Deus o abandonou! Vamos persegui-lo e prendê-lo, pois agora ninguém o livrará".

[[v19-71-12]]

^<<v19-71-12,12>>^ Ó Deus, não permaneças distante; vem depressa me socorrer, meu Deus.

[[v19-71-13]]

^<<v19-71-13,13>>^ Traz vergonha e destruição sobre meus acusadores, cobre de vergonha e humilhação os que desejam me prejudicar.

[[v19-71-14]]

^<<v19-71-14,14>>^ Eu, porém, continuarei a esperar em ti e te louvarei cada vez mais.

[[v19-71-15]]

^<<v19-71-15,15>>^ Falarei a todos de tua justiça; o dia todo, anunciarei tua salvação, embora não seja habilidoso com as palavras.

[[v19-71-16]]

^<<v19-71-16,16>>^ Louvarei teus feitos poderosos, SENHOR Soberano; contarei a todos que somente tu és justo.

[[v19-71-17]]

^<<v19-71-17,17>>^ Ó Deus, desde a infância me tens ensinado, e até hoje anuncio tuas maravilhas.

[[v19-71-18]]

^<<v19-71-18,18>>^ Não me abandones, ó Deus, agora que estou velho, de cabelos brancos. Deixe-me proclamar tua força a esta nova geração, teu poder a todos que vierem depois de mim.

[[v19-71-19]]

^<<v19-71-19,19>>^ Tua justiça, ó Deus, chega até os mais altos céus; tens feito coisas grandiosas. Quem se compara a ti, ó Deus?

[[v19-71-20]]

^<<v19-71-20,20>>^ Permitiste que eu passasse por muito sofrimento, mas ainda restaurarás minha vida e me farás subir das profundezas da terra.

[[v19-71-21]]

^<<v19-71-21,21>>^ Tu me darás ainda mais honra e voltarás a me confortar.

[[v19-71-22]]

^<<v19-71-22,22>>^ Então te louvarei com instrumento de cordas, pois és fiel às tuas promessas, ó meu Deus. Cantarei louvores a ti com a harpa, ó Santo de Israel.

[[v19-71-23]]

^<<v19-71-23,23>>^ Darei gritos de alegria e cantarei louvores a ti, pois tu me resgataste.

[[v19-71-24]]

^<<v19-71-24,24>>^ Anunciarei, o dia todo, teus feitos de justiça, pois foram envergonhados e humilhados todos que tentaram me prejudicar.

'''

xref:019-salmos/019-salmos-070.adoc#v19-70-0[&#60; Capítulo Anterior] | <<v19-71-0,Topo>> | xref:019-salmos/019-salmos-072.adoc#v19-72-0[Próximo Capítulo &#62;]