include::./index.adoc[]

[[v19-142-0]]
=== Salmos, 142
// nvt ?, NVT - Nova Versão Transformadora

[[v19-142-1]]

^<<v19-142-1,1>>^ Clamo em alta voz ao SENHOR; suplico pela misericórdia do SENHOR.

[[v19-142-2]]

^<<v19-142-2,2>>^ Derramo diante dele minhas queixas e lhe apresento minhas angústias.

[[v19-142-3]]

^<<v19-142-3,3>>^ Quando estou abatido, somente tu sabes o caminho que devo seguir. Aonde quer que eu vá, prepararam armadilhas contra mim.

[[v19-142-4]]

^<<v19-142-4,4>>^ Procuro alguém que venha me ajudar, mas ninguém sequer lembra que eu existo. Não tenho onde me abrigar, ninguém se importa com o que acontece comigo.

[[v19-142-5]]

^<<v19-142-5,5>>^ Então clamo a ti, SENHOR, e digo: "Tu és meu refúgio, és tudo que desejo na vida.

[[v19-142-6]]

^<<v19-142-6,6>>^ Ouve meu clamor, pois estou muito fraco. Livra-me dos que me perseguem, pois são fortes demais para mim.

[[v19-142-7]]

^<<v19-142-7,7>>^ Tira-me da prisão, para que eu te dê graças. Os justos se juntarão ao meu redor, pois tu és bom para mim".

'''

xref:019-salmos/019-salmos-141.adoc#v19-141-0[&#60; Capítulo Anterior] | <<v19-142-0,Topo>> | xref:019-salmos/019-salmos-143.adoc#v19-143-0[Próximo Capítulo &#62;]