include::./index.adoc[]

[[v19-90-0]]
=== Salmos, 90
// nvt ?, NVT - Nova Versão Transformadora

[[v19-90-1]]

^<<v19-90-1,1>>^ Senhor, tu tens sido nosso refúgio ao longo das gerações.

[[v19-90-2]]

^<<v19-90-2,2>>^ Antes que os montes nascessem, antes que formasses a terra e o mundo, de eternidade a eternidade, tu és Deus.

[[v19-90-3]]

^<<v19-90-3,3>>^ Fazes as pessoas voltarem ao pó quando dizes: "Retornem ao pó, mortais".

[[v19-90-4]]

^<<v19-90-4,4>>^ Para ti, mil anos são como um dia que passa, breves como algumas horas da noite.

[[v19-90-5]]

^<<v19-90-5,5>>^ Arrastas as pessoas como numa enchente; elas são como sonhos que desaparecem. São como a grama que nasce pela manhã;

[[v19-90-6]]

^<<v19-90-6,6>>^ pela manhã, brota e floresce, mas, à tarde, murcha e seca.

[[v19-90-7]]

^<<v19-90-7,7>>^ Somos consumidos por tua ira, ficamos apavorados com tua fúria.

[[v19-90-8]]

^<<v19-90-8,8>>^ Tu pões diante de ti os nossos pecados, nossos pecados secretos, e vês todos eles.

[[v19-90-9]]

^<<v19-90-9,9>>^ Passamos a vida debaixo de tua ira e terminamos nossos dias com um gemido.

[[v19-90-10]]

^<<v19-90-10,10>>^ Recebemos setenta anos, alguns chegam aos oitenta. Mas até os melhores anos são cheios de dor e desgosto; logo desaparecem, e nós voamos.

[[v19-90-11]]

^<<v19-90-11,11>>^ Quem conhece o poder de tua ira? Grande é a tua fúria, como o temor de que és digno.

[[v19-90-12]]

^<<v19-90-12,12>>^ Ajuda-nos a entender como a vida é breve, para que vivamos com sabedoria.

[[v19-90-13]]

^<<v19-90-13,13>>^ Ó SENHOR, volta-te para nós! Até quando te demorarás? Tem compaixão de teus servos.

[[v19-90-14]]

^<<v19-90-14,14>>^ Satisfaze-nos a cada manhã com o teu amor, para que cantemos de alegria até o final da vida.

[[v19-90-15]]

^<<v19-90-15,15>>^ Dá-nos alegria proporcional aos dias de aflição; compensa-nos pelos anos em que sofremos.

[[v19-90-16]]

^<<v19-90-16,16>>^ Que nós, teus servos, vejamos teus feitos outra vez; que nossos filhos vejam a tua glória.

[[v19-90-17]]

^<<v19-90-17,17>>^ Seja sobre nós a bondade do Senhor, nosso Deus; faze prosperar nossos esforços, sim, faze prosperar nossos esforços.

'''

xref:019-salmos/019-salmos-089.adoc#v19-89-0[&#60; Capítulo Anterior] | <<v19-90-0,Topo>> | xref:019-salmos/019-salmos-091.adoc#v19-91-0[Próximo Capítulo &#62;]