include::./index.adoc[]

[[v19-109-0]]
=== Salmos, 109
// nvt ?, NVT - Nova Versão Transformadora

[[v19-109-1]]

^<<v19-109-1,1>>^ Ó Deus, a quem eu louvo, não permaneças calado,

[[v19-109-2]]

^<<v19-109-2,2>>^ enquanto os perversos me caluniam e falam mentiras a meu respeito.

[[v19-109-3]]

^<<v19-109-3,3>>^ Eles me cercam de palavras odiosas e me atacam sem motivo.

[[v19-109-4]]

^<<v19-109-4,4>>^ Retribuem meu amor com acusações, mesmo enquanto oro por eles.

[[v19-109-5]]

^<<v19-109-5,5>>^ Pagam-me o bem com o mal, e o amor, com o ódio.

[[v19-109-6]]

^<<v19-109-6,6>>^ Que um perverso testemunhe contra ele, e um acusador o leve a julgamento.

[[v19-109-7]]

^<<v19-109-7,7>>^ Quando julgarem sua causa, que o declarem culpado; considerem pecado suas orações.

[[v19-109-8]]

^<<v19-109-8,8>>^ Que sua vida seja curta, e outro ocupe seu lugar.

[[v19-109-9]]

^<<v19-109-9,9>>^ Que seus filhos se tornem órfãos, e sua esposa, viúva.

[[v19-109-10]]

^<<v19-109-10,10>>^ Que seus filhos andem sem rumo, como mendigos, e sejam expulsos de suas casas em ruínas.

[[v19-109-11]]

^<<v19-109-11,11>>^ Que os credores tomem todos os seus bens, e estranhos levem o fruto de seu trabalho.

[[v19-109-12]]

^<<v19-109-12,12>>^ Que ninguém o trate com bondade, nem tenha compaixão de seus órfãos.

[[v19-109-13]]

^<<v19-109-13,13>>^ Que todos os seus descendentes morram; que o nome de sua família seja apagado na geração seguinte.

[[v19-109-14]]

^<<v19-109-14,14>>^ Que o SENHOR nunca se esqueça dos pecados de seus antepassados; que os pecados de sua mãe jamais sejam apagados.

[[v19-109-15]]

^<<v19-109-15,15>>^ Que o SENHOR se lembre sempre de sua culpa; que seu nome seja de todo esquecido.

[[v19-109-16]]

^<<v19-109-16,16>>^ Pois não quis ser bondoso com os outros; foi no encalço dos pobres e necessitados e perseguiu até a morte os de coração quebrantado.

[[v19-109-17]]

^<<v19-109-17,17>>^ Gostava de amaldiçoar; agora, que ele próprio seja amaldiçoado. Não tinha prazer em abençoar; agora, que ele não seja abençoado.

[[v19-109-18]]

^<<v19-109-18,18>>^ Para ele, amaldiçoar é como a roupa que ele veste, como a água que bebe, como os alimentos saborosos que come.

[[v19-109-19]]

^<<v19-109-19,19>>^ Agora, que suas maldições voltem para ele; apeguem-se a seu corpo como roupas, amarrem-se em torno dele como um cinto.

[[v19-109-20]]

^<<v19-109-20,20>>^ Que essas maldições se tornem castigo do Senhor para meus acusadores, para os que falam mal de mim.

[[v19-109-21]]

^<<v19-109-21,21>>^ Quanto a mim, ó SENHOR Soberano, trata-me bem, por causa do teu nome; livra-me, porque és fiel e bom.

[[v19-109-22]]

^<<v19-109-22,22>>^ Pois sou pobre e necessitado, e meu coração está ferido.

[[v19-109-23]]

^<<v19-109-23,23>>^ Vou desaparecendo, como a sombra ao entardecer; sou lançado para longe, como um gafanhoto.

[[v19-109-24]]

^<<v19-109-24,24>>^ De tanto jejuar, meus joelhos estão fracos; não passo de pele e osso.

[[v19-109-25]]

^<<v19-109-25,25>>^ Sou motivo de zombaria em todo lugar; quando me veem, balançam a cabeça em desprezo.

[[v19-109-26]]

^<<v19-109-26,26>>^ Ajuda-me, SENHOR, meu Deus; salva-me por causa do teu amor!

[[v19-109-27]]

^<<v19-109-27,27>>^ Que eles reconheçam que isso veio de ti, que tu mesmo o fizeste, SENHOR.

[[v19-109-28]]

^<<v19-109-28,28>>^ Que importa se me amaldiçoarem? Tu me abençoarás! Quando me atacarem, serão envergonhados; mas eu, teu servo, continuarei a me alegrar!

[[v19-109-29]]

^<<v19-109-29,29>>^ Que meus acusadores sejam vestidos de humilhação, que a vergonha os cubra como um manto.

[[v19-109-30]]

^<<v19-109-30,30>>^ Eu, porém, sempre darei graças ao SENHOR; louvarei seu nome diante de todos.

[[v19-109-31]]

^<<v19-109-31,31>>^ Pois ele está junto aos necessitados, pronto para salvá-los dos que os condenam.

'''

xref:019-salmos/019-salmos-108.adoc#v19-108-0[&#60; Capítulo Anterior] | <<v19-109-0,Topo>> | xref:019-salmos/019-salmos-110.adoc#v19-110-0[Próximo Capítulo &#62;]