include::./index.adoc[]

[[v19-143-0]]
=== Salmos, 143
// nvt ?, NVT - Nova Versão Transformadora

[[v19-143-1]]

^<<v19-143-1,1>>^ Ouve minha oração, SENHOR; escuta minha súplica! Responde-me, pois és fiel e justo.

[[v19-143-2]]

^<<v19-143-2,2>>^ Não leves teu servo a julgamento, pois diante de ti ninguém é inocente.

[[v19-143-3]]

^<<v19-143-3,3>>^ Meu inimigo me perseguiu; derrubou-me no chão e obrigou-me a morar em trevas, como as do túmulo.

[[v19-143-4]]

^<<v19-143-4,4>>^ Vou perdendo todo o ânimo; estou tomado de medo.

[[v19-143-5]]

^<<v19-143-5,5>>^ Lembro-me de tempos passados; reflito em todas as tuas obras e penso em tudo que fizeste.

[[v19-143-6]]

^<<v19-143-6,6>>^ Levanto minhas mãos a ti em oração; anseio por ti, como a terra seca tem sede de chuva. Interlúdio

[[v19-143-7]]

^<<v19-143-7,7>>^ Vem depressa, SENHOR, e responde-me, pois meu ânimo se esvai. Não te afastes de mim, ou morrerei.

[[v19-143-8]]

^<<v19-143-8,8>>^ Faze-me ouvir do teu amor a cada manhã, pois confio em ti. Mostra-me por onde devo andar, pois me entrego a ti.

[[v19-143-9]]

^<<v19-143-9,9>>^ Livra-me de meus inimigos, SENHOR, pois me refugio em ti.

[[v19-143-10]]

^<<v19-143-10,10>>^ Ensina-me a fazer tua vontade, pois tu és meu Deus. Que o teu Espírito bondoso me conduza adiante por um caminho reto e seguro.

[[v19-143-11]]

^<<v19-143-11,11>>^ Pela honra do teu nome, SENHOR, preserva minha vida. Por tua justiça, tira-me deste sofrimento.

[[v19-143-12]]

^<<v19-143-12,12>>^ Por teu amor, acaba com meus inimigos e destrói meus adversários, pois sou teu servo.

'''

xref:019-salmos/019-salmos-142.adoc#v19-142-0[&#60; Capítulo Anterior] | <<v19-143-0,Topo>> | xref:019-salmos/019-salmos-144.adoc#v19-144-0[Próximo Capítulo &#62;]