include::./index.adoc[]

[[v19-81-0]]
=== Salmos, 81
// nvt ?, NVT - Nova Versão Transformadora

[[v19-81-1]]

^<<v19-81-1,1>>^ Cantem louvores a Deus, nossa força! Aclamem ao Deus de Jacó.

[[v19-81-2]]

^<<v19-81-2,2>>^ Cantem! Façam soar o tamborim, a doce lira e a harpa.

[[v19-81-3]]

^<<v19-81-3,3>>^ Toquem a trombeta na lua nova e na lua cheia, para convocar a nossa festa.

[[v19-81-4]]

^<<v19-81-4,4>>^ Pois assim exigem os estatutos de Israel; esse é o decreto do Deus de Jacó.

[[v19-81-5]]

^<<v19-81-5,5>>^ Ele o ordenou como lei para Israel, quando atacou o Egito para nos libertar. Ouvi uma voz desconhecida dizer:

[[v19-81-6]]

^<<v19-81-6,6>>^ "Agora removerei o peso de seus ombros e libertarei suas mãos das tarefas pesadas.

[[v19-81-7]]

^<<v19-81-7,7>>^ Vocês clamaram a mim em sua aflição, e eu os salvei; da nuvem de tempestade lhes respondi e pus vocês à prova quando não havia água em Meribá. Interlúdio

[[v19-81-8]]

^<<v19-81-8,8>>^ "Ó meu povo, ouça minhas advertências; quem dera você me escutasse, ó Israel!

[[v19-81-9]]

^<<v19-81-9,9>>^ Jamais tenha em seu meio outro deus; não se curve diante de deus estrangeiro.

[[v19-81-10]]

^<<v19-81-10,10>>^ Pois fui eu, o SENHOR, seu Deus, que o tirei da terra do Egito. Abra bem a boca, e a encherei de coisas boas.

[[v19-81-11]]

^<<v19-81-11,11>>^ "Meu povo, no entanto, não quis ouvir; Israel não me obedeceu.

[[v19-81-12]]

^<<v19-81-12,12>>^ Por isso, deixei que seguissem seus desejos teimosos e vivessem de acordo com suas próprias ideias.

[[v19-81-13]]

^<<v19-81-13,13>>^ Ah, se meu povo me escutasse; quem dera Israel andasse em meus caminhos!

[[v19-81-14]]

^<<v19-81-14,14>>^ Então eu derrotaria seus inimigos sem demora; minhas mãos cairiam sobre seus adversários.

[[v19-81-15]]

^<<v19-81-15,15>>^ Os que odeiam o SENHOR se encolheriam diante dele, condenados para sempre.

[[v19-81-16]]

^<<v19-81-16,16>>^ Vocês, porém, eu alimentaria com trigo da melhor qualidade e os saciaria com mel silvestre tirado da rocha".

'''

xref:019-salmos/019-salmos-080.adoc#v19-80-0[&#60; Capítulo Anterior] | <<v19-81-0,Topo>> | xref:019-salmos/019-salmos-082.adoc#v19-82-0[Próximo Capítulo &#62;]