include::./index.adoc[]

[[v19-107-0]]
=== Salmos, 107
// nvt ?, NVT - Nova Versão Transformadora

[[v19-107-1]]

^<<v19-107-1,1>>^ Deem graças ao SENHOR, porque ele é bom; seu amor dura para sempre!

[[v19-107-2]]

^<<v19-107-2,2>>^ O SENHOR os resgatou? Proclamem em alta voz! Contem a todos que ele os resgatou de seus inimigos.

[[v19-107-3]]

^<<v19-107-3,3>>^ Pois ele reuniu os que estavam exilados em muitas terras, do leste e do oeste, do norte e do sul.

[[v19-107-4]]

^<<v19-107-4,4>>^ Eles vagavam pelo deserto, perdidos e sem lar.

[[v19-107-5]]

^<<v19-107-5,5>>^ Famintos e sedentos, chegaram à beira da morte.

[[v19-107-6]]

^<<v19-107-6,6>>^ Em sua aflição, clamaram ao SENHOR, e ele os livrou de seus sofrimentos.

[[v19-107-7]]

^<<v19-107-7,7>>^ Conduziu-os por um caminho seguro, a uma cidade onde pudessem morar.

[[v19-107-8]]

^<<v19-107-8,8>>^ Que louvem o SENHOR por seu grande amor e pelas maravilhas que fez pela humanidade.

[[v19-107-9]]

^<<v19-107-9,9>>^ Pois ele sacia o sedento e enche de coisas boas o faminto.

[[v19-107-10]]

^<<v19-107-10,10>>^ Estavam sentados na escuridão e em trevas profundas, presos com as algemas de ferro do sofrimento.

[[v19-107-11]]

^<<v19-107-11,11>>^ Rebelaram-se contra as palavras de Deus e desprezaram o conselho do Altíssimo.

[[v19-107-12]]

^<<v19-107-12,12>>^ Por isso ele os sujeitou a trabalhos pesados; caíram, e não houve quem os ajudasse.

[[v19-107-13]]

^<<v19-107-13,13>>^ Em sua aflição, clamaram ao SENHOR, e ele os livrou de seus sofrimentos.

[[v19-107-14]]

^<<v19-107-14,14>>^ Tirou-os da escuridão e das trevas profundas e quebrou suas algemas.

[[v19-107-15]]

^<<v19-107-15,15>>^ Que louvem o SENHOR por seu grande amor e pelas maravilhas que fez pela humanidade.

[[v19-107-16]]

^<<v19-107-16,16>>^ Pois ele quebrou as portas de bronze da prisão e partiu as trancas de ferro.

[[v19-107-17]]

^<<v19-107-17,17>>^ Foram tolos; rebelaram-se e sofreram por causa de seus pecados.

[[v19-107-18]]

^<<v19-107-18,18>>^ Não conseguiam nem pensar em comer e estavam às portas da morte.

[[v19-107-19]]

^<<v19-107-19,19>>^ Em sua aflição, clamaram ao SENHOR, e ele os livrou de seus sofrimentos.

[[v19-107-20]]

^<<v19-107-20,20>>^ Enviou sua palavra e os curou, e os resgatou da morte.

[[v19-107-21]]

^<<v19-107-21,21>>^ Que louvem o SENHOR por seu grande amor e pelas maravilhas que fez pela humanidade.

[[v19-107-22]]

^<<v19-107-22,22>>^ Que ofereçam sacrifícios de ações de graças e anunciem suas obras com canções alegres.

[[v19-107-23]]

^<<v19-107-23,23>>^ Viajaram pelo mundo em navios; percorreram as rotas comerciais dos mares.

[[v19-107-24]]

^<<v19-107-24,24>>^ Também eles viram as obras do Senhor e suas maravilhas nas águas mais profundas.

[[v19-107-25]]

^<<v19-107-25,25>>^ Por sua ordem, os ventos se levantaram e agitaram as ondas.

[[v19-107-26]]

^<<v19-107-26,26>>^ Seus navios eram lançados aos céus, depois desciam às profundezas; foram tomados de pavor.

[[v19-107-27]]

^<<v19-107-27,27>>^ Cambaleavam e tropeçavam, como bêbados, e não sabiam mais o que fazer.

[[v19-107-28]]

^<<v19-107-28,28>>^ Em sua aflição, clamaram ao SENHOR, e ele os livrou de seus sofrimentos.

[[v19-107-29]]

^<<v19-107-29,29>>^ Acalmou a tempestade e aquietou as ondas.

[[v19-107-30]]

^<<v19-107-30,30>>^ A calmaria os alegrou, e ele os levou ao porto em segurança.

[[v19-107-31]]

^<<v19-107-31,31>>^ Que louvem o SENHOR por sua bondade e pelas maravilhas que fez pela humanidade.

[[v19-107-32]]

^<<v19-107-32,32>>^ Que o exaltem em público, diante da comunidade e dos líderes do povo.

[[v19-107-33]]

^<<v19-107-33,33>>^ Ele transforma rios em desertos, e fontes de água em terra seca.

[[v19-107-34]]

^<<v19-107-34,34>>^ Torna a terra fértil em solo inútil, por causa da perversidade de seus habitantes.

[[v19-107-35]]

^<<v19-107-35,35>>^ Também transforma os desertos em açudes e a terra seca em fontes de água.

[[v19-107-36]]

^<<v19-107-36,36>>^ Leva os famintos para ali se estabelecerem e construírem suas cidades.

[[v19-107-37]]

^<<v19-107-37,37>>^ Eles semeiam campos, plantam videiras e têm grandes colheitas.

[[v19-107-38]]

^<<v19-107-38,38>>^ Sim, ele os abençoa! Ali, criam famílias numerosas, e seus rebanhos não param de crescer.

[[v19-107-39]]

^<<v19-107-39,39>>^ Mas, quando diminuem em número e empobrecem por causa da opressão, da miséria e da tristeza,

[[v19-107-40]]

^<<v19-107-40,40>>^ o SENHOR lança desprezo sobre seus príncipes e os faz vagar num deserto sem caminhos.

[[v19-107-41]]

^<<v19-107-41,41>>^ Contudo, livra do sofrimento os pobres e aumenta suas famílias como rebanhos de ovelhas.

[[v19-107-42]]

^<<v19-107-42,42>>^ Os justos verão essas coisas e se alegrarão, enquanto os perversos serão calados.

[[v19-107-43]]

^<<v19-107-43,43>>^ Quem é sábio levará tudo isso a sério; perceberá como tem sido leal o amor do SENHOR.

'''

xref:019-salmos/019-salmos-106.adoc#v19-106-0[&#60; Capítulo Anterior] | <<v19-107-0,Topo>> | xref:019-salmos/019-salmos-108.adoc#v19-108-0[Próximo Capítulo &#62;]