include::./index.adoc[]

[[v19-97-0]]
=== Salmos, 97
// nvt ?, NVT - Nova Versão Transformadora

[[v19-97-1]]

^<<v19-97-1,1>>^ O SENHOR reina! Alegre-se a terra, exultem os litorais mais distantes.

[[v19-97-2]]

^<<v19-97-2,2>>^ Nuvens escuras o cercam; justiça e retidão são a base de seu trono.

[[v19-97-3]]

^<<v19-97-3,3>>^ Fogo se espalha adiante dele, queimando todos os seus inimigos.

[[v19-97-4]]

^<<v19-97-4,4>>^ Seus relâmpagos iluminam o mundo; a terra os vê e estremece.

[[v19-97-5]]

^<<v19-97-5,5>>^ Os montes se derretem como cera diante do SENHOR, diante do Senhor de toda a terra.

[[v19-97-6]]

^<<v19-97-6,6>>^ Os céus proclamam sua justiça; todos os povos veem sua glória.

[[v19-97-7]]

^<<v19-97-7,7>>^ Sejam envergonhados os que adoram ídolos, os que contam vantagem de seus deuses inúteis, pois todos os deuses se prostram diante dele.

[[v19-97-8]]

^<<v19-97-8,8>>^ Sião ouviu e se alegrou, e todas as cidades de Judá exultam, por causa de tua justiça, ó SENHOR.

[[v19-97-9]]

^<<v19-97-9,9>>^ Pois tu, SENHOR, és supremo sobre toda a terra; és exaltado muito acima de todos os deuses.

[[v19-97-10]]

^<<v19-97-10,10>>^ Vocês que amam o SENHOR, odeiem o mal! Ele protege a vida de seus fiéis e os resgata da mão dos perversos.

[[v19-97-11]]

^<<v19-97-11,11>>^ A luz brilha sobre os justos, e a alegria, sobre os que têm coração íntegro.

[[v19-97-12]]

^<<v19-97-12,12>>^ Alegrem-se no SENHOR todos os justos e louvem seu santo nome!

'''

xref:019-salmos/019-salmos-096.adoc#v19-96-0[&#60; Capítulo Anterior] | <<v19-97-0,Topo>> | xref:019-salmos/019-salmos-098.adoc#v19-98-0[Próximo Capítulo &#62;]