include::./index.adoc[]

[[v19-140-0]]
=== Salmos, 140
// nvt ?, NVT - Nova Versão Transformadora

[[v19-140-1]]

^<<v19-140-1,1>>^ Ó SENHOR, livra-me dos perversos; protege-me dos violentos,

[[v19-140-2]]

^<<v19-140-2,2>>^ dos que tramam o mal em seu coração e provocam tumultos o tempo todo.

[[v19-140-3]]

^<<v19-140-3,3>>^ Sua língua fere como uma serpente; veneno de víbora goteja de seus lábios. Interlúdio

[[v19-140-4]]

^<<v19-140-4,4>>^ Ó SENHOR, protege-me das mãos dos perversos; guarda-me dos violentos, pois eles tramam contra mim.

[[v19-140-5]]

^<<v19-140-5,5>>^ Os orgulhosos me prepararam uma armadilha; estenderam uma rede e armaram ciladas ao longo do caminho. Interlúdio

[[v19-140-6]]

^<<v19-140-6,6>>^ Eu disse ao SENHOR: "Tu és meu Deus!"; ouve, SENHOR, as minhas súplicas.

[[v19-140-7]]

^<<v19-140-7,7>>^ Ó Soberano SENHOR, meu salvador poderoso, tu me protegeste no dia da batalha.

[[v19-140-8]]

^<<v19-140-8,8>>^ SENHOR, não dês aos perversos o que desejam; não permitas que seus planos maldosos tenham sucesso, para que não se encham de orgulho. Interlúdio

[[v19-140-9]]

^<<v19-140-9,9>>^ Sejam destruídos meus inimigos pelo mesmo mal que tramaram contra mim.

[[v19-140-10]]

^<<v19-140-10,10>>^ Caiam sobre eles brasas ardentes; sejam atirados no fogo, ou em poços fundos de onde não poderão escapar.

[[v19-140-11]]

^<<v19-140-11,11>>^ Não permitas que os mentirosos prosperem em nossa terra; derrama a calamidade sobre os violentos.

[[v19-140-12]]

^<<v19-140-12,12>>^ Sei, porém, que o SENHOR defenderá a causa dos aflitos; ele fará justiça aos pobres.

[[v19-140-13]]

^<<v19-140-13,13>>^ Certamente os justos louvarão teu nome; os íntegros viverão em tua presença.

'''

xref:019-salmos/019-salmos-139.adoc#v19-139-0[&#60; Capítulo Anterior] | <<v19-140-0,Topo>> | xref:019-salmos/019-salmos-141.adoc#v19-141-0[Próximo Capítulo &#62;]