include::./index.adoc[]

[[v19-144-0]]
=== Salmos, 144
// nvt ?, NVT - Nova Versão Transformadora

[[v19-144-1]]

^<<v19-144-1,1>>^ Louvado seja o SENHOR, minha rocha; ele treina minhas mãos para a guerra e dá a meus dedos habilidade para a batalha.

[[v19-144-2]]

^<<v19-144-2,2>>^ Ele é meu aliado infalível e minha fortaleza, minha torre segura e meu libertador. Ele é meu escudo, em quem me refugio; faz as nações se sujeitarem a mim.

[[v19-144-3]]

^<<v19-144-3,3>>^ Ó SENHOR, quem são os seres humanos, para que prestes atenção neles? Quem são os simples mortais, para que penses neles?

[[v19-144-4]]

^<<v19-144-4,4>>^ São como uma brisa; seus dias são como uma sombra que passa.

[[v19-144-5]]

^<<v19-144-5,5>>^ Abre os céus, SENHOR, e desce; toca os montes para que soltem fumaça.

[[v19-144-6]]

^<<v19-144-6,6>>^ Lança teus relâmpagos e dispersa os inimigos; atira tuas flechas e confunde-os.

[[v19-144-7]]

^<<v19-144-7,7>>^ Estende tua mão desde os céus e salva-me; tira-me das águas profundas, livra-me do poder de meus inimigos.

[[v19-144-8]]

^<<v19-144-8,8>>^ Eles têm a boca cheia de mentiras; juram dizer a verdade, mas mentem.

[[v19-144-9]]

^<<v19-144-9,9>>^ Cantarei a ti, ó Deus, um cântico novo; cantarei louvores a ti com instrumento de dez cordas.

[[v19-144-10]]

^<<v19-144-10,10>>^ Pois tu concedes vitória aos reis; livraste teu servo Davi da espada mortal.

[[v19-144-11]]

^<<v19-144-11,11>>^ Salva-me! Livra-me do poder de meus inimigos. Eles têm a boca cheia de mentiras; juram dizer a verdade, mas mentem.

[[v19-144-12]]

^<<v19-144-12,12>>^ Que nossos filhos floresçam na juventude como plantas viçosas. Que nossas filhas sejam como colunas graciosas, esculpidas para enfeitar um palácio.

[[v19-144-13]]

^<<v19-144-13,13>>^ Que nossos celeiros fiquem cheios de colheitas de todo tipo. Que os rebanhos em nossos campos se multipliquem aos milhares, e até às dezenas de milhares,

[[v19-144-14]]

^<<v19-144-14,14>>^ e que nossos bois fiquem carregados de alimentos. Que nenhum inimigo consiga romper nossos muros, que ninguém seja levado ao cativeiro, nem haja gritos de angústia em nossas praças.

[[v19-144-15]]

^<<v19-144-15,15>>^ Como são felizes os que vivem desse modo! Verdadeiramente são felizes aqueles cujo Deus é o SENHOR!

'''

xref:019-salmos/019-salmos-143.adoc#v19-143-0[&#60; Capítulo Anterior] | <<v19-144-0,Topo>> | xref:019-salmos/019-salmos-145.adoc#v19-145-0[Próximo Capítulo &#62;]