include::./index.adoc[]

[[v19-78-0]]
=== Salmos, 78
// nvt ?, NVT - Nova Versão Transformadora

[[v19-78-1]]

^<<v19-78-1,1>>^ Ó meu povo, ouça minhas instruções! Abra os ouvidos para o que direi,

[[v19-78-2]]

^<<v19-78-2,2>>^ pois lhe falarei por meio de parábola. Ensinarei enigmas de nosso passado,

[[v19-78-3]]

^<<v19-78-3,3>>^ histórias que ouvimos e conhecemos, que nossos antepassados nos transmitiram.

[[v19-78-4]]

^<<v19-78-4,4>>^ Não esconderemos essas verdades de nossos filhos; contaremos à geração seguinte os feitos gloriosos do SENHOR, seu poder e suas maravilhas.

[[v19-78-5]]

^<<v19-78-5,5>>^ Pois ele estabeleceu seus preceitos a Jacó, deu sua lei a Israel. Ordenou a nossos antepassados que a ensinassem a seus filhos,

[[v19-78-6]]

^<<v19-78-6,6>>^ para que a geração seguinte, os filhos ainda por nascer, a conhecesse, e eles, por sua vez, a ensinarão a seus filhos.

[[v19-78-7]]

^<<v19-78-7,7>>^ Portanto, cada geração deve pôr sua esperança em Deus, não esquecer seus poderosos feitos e obedecer a seus mandamentos.

[[v19-78-8]]

^<<v19-78-8,8>>^ Assim, não serão como seus antepassados, teimosos, rebeldes e infiéis, que se recusaram a confiar em Deus de todo o coração.

[[v19-78-9]]

^<<v19-78-9,9>>^ Os guerreiros de Efraim, embora armados de arcos, deram meia-volta e fugiram no dia da batalha.

[[v19-78-10]]

^<<v19-78-10,10>>^ Não cumpriram a aliança de Deus, não quiseram viver de acordo com sua lei.

[[v19-78-11]]

^<<v19-78-11,11>>^ Esqueceram o que ele havia feito, as maravilhas que lhes tinha mostrado,

[[v19-78-12]]

^<<v19-78-12,12>>^ os milagres que realizara para seus antepassados na planície de Zoã, na terra do Egito.

[[v19-78-13]]

^<<v19-78-13,13>>^ Pois ele dividiu o mar e os conduziu na travessia; fez as águas se erguerem como muralhas.

[[v19-78-14]]

^<<v19-78-14,14>>^ Durante o dia, os guiava com uma nuvem, durante a noite, com a luz do fogo.

[[v19-78-15]]

^<<v19-78-15,15>>^ No deserto, partiu as rochas para lhes dar água, como a que jorra de um manancial.

[[v19-78-16]]

^<<v19-78-16,16>>^ Da pedra, fez brotar riachos e correr água como um rio.

[[v19-78-17]]

^<<v19-78-17,17>>^ Ainda assim, continuaram a pecar contra ele e se rebelaram contra o Altíssimo no deserto.

[[v19-78-18]]

^<<v19-78-18,18>>^ Puseram Deus à prova em seu coração e exigiram a comida que tanto queriam.

[[v19-78-19]]

^<<v19-78-19,19>>^ Chegaram a falar contra o próprio Deus, dizendo: "Deus não é capaz de nos dar comida no deserto.

[[v19-78-20]]

^<<v19-78-20,20>>^ Sim, ele pode bater numa rocha e dela fazer brotar água, mas não é capaz de dar pão e carne a seu povo".

[[v19-78-21]]

^<<v19-78-21,21>>^ Quando o SENHOR os ouviu, se enfureceu; o fogo de sua ira ardeu contra Jacó. Sim, sua ira se levantou contra Israel,

[[v19-78-22]]

^<<v19-78-22,22>>^ pois não creram em Deus nem confiaram em seu cuidado.

[[v19-78-23]]

^<<v19-78-23,23>>^ Apesar disso, ele deu ordem às nuvens; abriu as portas dos céus.

[[v19-78-24]]

^<<v19-78-24,24>>^ Fez chover maná para alimentá-los; deu-lhes pão dos céus.

[[v19-78-25]]

^<<v19-78-25,25>>^ Eles comeram o pão dos anjos; receberam comida à vontade.

[[v19-78-26]]

^<<v19-78-26,26>>^ Ele enviou dos céus o vento do leste e, por seu poder, guiou o vento do sul.

[[v19-78-27]]

^<<v19-78-27,27>>^ Fez chover carne como se fosse pó, muitas e muitas aves, como a areia da praia.

[[v19-78-28]]

^<<v19-78-28,28>>^ Fez as aves caírem dentro do acampamento, ao redor de suas tendas.

[[v19-78-29]]

^<<v19-78-29,29>>^ O povo comeu à vontade; ele atendeu ao desejo deles.

[[v19-78-30]]

^<<v19-78-30,30>>^ Mas, antes que estivessem satisfeitos, enquanto ainda tinham comida na boca,

[[v19-78-31]]

^<<v19-78-31,31>>^ a ira de Deus se levantou contra eles. Ele matou seus homens mais fortes; feriu mortalmente os jovens de Israel.

[[v19-78-32]]

^<<v19-78-32,32>>^ Ainda assim, continuaram a pecar; não confiaram em Deus, apesar de suas maravilhas.

[[v19-78-33]]

^<<v19-78-33,33>>^ Por isso, reduziu a vida deles a um sopro e fez seus dias terminarem em terror.

[[v19-78-34]]

^<<v19-78-34,34>>^ Quando Deus começou a matá-los, finalmente o buscaram; arrependeram-se e levaram Deus a sério.

[[v19-78-35]]

^<<v19-78-35,35>>^ Então lembraram que Deus era sua rocha, que o Deus Altíssimo era seu redentor.

[[v19-78-36]]

^<<v19-78-36,36>>^ Contudo, foi só da boca para fora; mentiram para ele com os lábios.

[[v19-78-37]]

^<<v19-78-37,37>>^ Pois o coração não era leal a Deus; não foram fiéis à sua aliança.

[[v19-78-38]]

^<<v19-78-38,38>>^ E, no entanto, ele foi misericordioso; perdoou seus pecados e não os destruiu. Muitas vezes conteve sua ira e não se enfureceu contra eles.

[[v19-78-39]]

^<<v19-78-39,39>>^ Pois se lembrou de que eram simples mortais; passam como o vento, que não volta mais.

[[v19-78-40]]

^<<v19-78-40,40>>^ Quantas vezes se rebelaram contra ele no deserto e o entristeceram naquela terra desolada!

[[v19-78-41]]

^<<v19-78-41,41>>^ Repetidamente, puseram Deus à prova e provocaram o Santo de Israel.

[[v19-78-42]]

^<<v19-78-42,42>>^ Não se recordaram do seu poder, nem do dia em que ele os resgatou de seus inimigos.

[[v19-78-43]]

^<<v19-78-43,43>>^ Não se lembraram dos sinais que ele fizera no Egito, das maravilhas realizadas na planície de Zoã.

[[v19-78-44]]

^<<v19-78-44,44>>^ Ele transformou os rios em sangue, para que ninguém bebesse de suas águas.

[[v19-78-45]]

^<<v19-78-45,45>>^ Enviou enxames de moscas para devorá-los e rãs para destruí-los.

[[v19-78-46]]

^<<v19-78-46,46>>^ Entregou suas plantações às lagartas e suas colheitas, aos gafanhotos.

[[v19-78-47]]

^<<v19-78-47,47>>^ Destruiu as videiras com granizo e as figueiras, com geadas.

[[v19-78-48]]

^<<v19-78-48,48>>^ Entregou seu gado à chuva de pedras e seus rebanhos, aos raios.

[[v19-78-49]]

^<<v19-78-49,49>>^ Lançou sobre eles sua ira ardente, sua fúria, indignação e hostilidade. Enviou contra eles muitos anjos destruidores.

[[v19-78-50]]

^<<v19-78-50,50>>^ Voltou sua ira contra eles; não lhes poupou a vida, mas os devastou com a peste.

[[v19-78-51]]

^<<v19-78-51,51>>^ Matou todos os filhos mais velhos do Egito, a flor da juventude na terra de Cam.

[[v19-78-52]]

^<<v19-78-52,52>>^ Mas conduziu seu povo como um rebanho de ovelhas e os guiou em segurança pelo deserto.

[[v19-78-53]]

^<<v19-78-53,53>>^ Manteve-os a salvo, e não tiveram medo; o mar cobriu seus inimigos.

[[v19-78-54]]

^<<v19-78-54,54>>^ Levou o povo até a fronteira de sua terra santa, à região montanhosa que para eles conquistou.

[[v19-78-55]]

^<<v19-78-55,55>>^ Diante deles expulsou as nações e repartiu entre eles sua herança; estabeleceu as tribos de Israel em seus lugares.

[[v19-78-56]]

^<<v19-78-56,56>>^ Ainda assim, continuaram a pôr à prova o Deus Altíssimo e a se rebelar contra ele; não obedeceram a seus preceitos.

[[v19-78-57]]

^<<v19-78-57,57>>^ Voltaram atrás e foram infiéis, como seus antepassados; mostraram-se indignos de confiança, como um arco defeituoso.

[[v19-78-58]]

^<<v19-78-58,58>>^ Provocaram a ira de Deus ao construir altares para outros deuses; com seus ídolos, despertaram nele ciúmes.

[[v19-78-59]]

^<<v19-78-59,59>>^ Quando Deus os ouviu, se enfureceu e rejeitou por completo Israel.

[[v19-78-60]]

^<<v19-78-60,60>>^ Abandonou sua habitação em Siló, o tabernáculo onde vivia no meio do povo.

[[v19-78-61]]

^<<v19-78-61,61>>^ Deixou que a arca de seu poder fosse capturada, entregou sua glória nas mãos de inimigos.

[[v19-78-62]]

^<<v19-78-62,62>>^ Permitiu que seu povo fosse morto à espada, pois se enfureceu com eles, sua propriedade.

[[v19-78-63]]

^<<v19-78-63,63>>^ Os jovens foram consumidos pelo fogo, e as moças não puderam entoar canções de núpcias.

[[v19-78-64]]

^<<v19-78-64,64>>^ Os sacerdotes foram mortos à espada, e as viúvas não puderam lamentar as mortes.

[[v19-78-65]]

^<<v19-78-65,65>>^ Então o Senhor se levantou, como de um sono, como o guerreiro que desperta da embriaguez.

[[v19-78-66]]

^<<v19-78-66,66>>^ Fez os inimigos recuarem e os entregou à vergonha para sempre.

[[v19-78-67]]

^<<v19-78-67,67>>^ Rejeitou, porém, os descendentes de José; não escolheu a tribo de Efraim.

[[v19-78-68]]

^<<v19-78-68,68>>^ Antes, escolheu a tribo de Judá, o monte Sião, que ele amou.

[[v19-78-69]]

^<<v19-78-69,69>>^ Ali construiu seu santuário, alto como os céus, firme e duradouro como a terra.

[[v19-78-70]]

^<<v19-78-70,70>>^ Escolheu Davi, seu servo, e dos currais o chamou.

[[v19-78-71]]

^<<v19-78-71,71>>^ Tirou-o do pastoreio de ovelhas e cordeiros e tornou-o pastor dos descendentes de Jacó, o povo que a Deus pertence, Israel.

[[v19-78-72]]

^<<v19-78-72,72>>^ Com coração sincero, Davi cuidou deles e os conduziu com sensatez.

'''

xref:019-salmos/019-salmos-077.adoc#v19-77-0[&#60; Capítulo Anterior] | <<v19-78-0,Topo>> | xref:019-salmos/019-salmos-079.adoc#v19-79-0[Próximo Capítulo &#62;]