include::./index.adoc[]

[[v19-147-0]]
=== Salmos, 147
// nvt ?, NVT - Nova Versão Transformadora

[[v19-147-1]]

^<<v19-147-1,1>>^ Louvado seja o SENHOR! Como é bom cantar louvores a nosso Deus! Como é agradável e apropriado!

[[v19-147-2]]

^<<v19-147-2,2>>^ O SENHOR reconstrói Jerusalém e traz os exilados de volta a Israel.

[[v19-147-3]]

^<<v19-147-3,3>>^ Ele cura os de coração quebrantado e enfaixa suas feridas.

[[v19-147-4]]

^<<v19-147-4,4>>^ Conta as estrelas e chama cada uma pelo nome.

[[v19-147-5]]

^<<v19-147-5,5>>^ Nosso Senhor é grande! Seu poder é absoluto! É impossível medir seu entendimento.

[[v19-147-6]]

^<<v19-147-6,6>>^ O SENHOR protege os humildes, mas lança os perversos no pó.

[[v19-147-7]]

^<<v19-147-7,7>>^ Cantem com ações de graças ao SENHOR, cantem ao nosso Deus louvores com a harpa.

[[v19-147-8]]

^<<v19-147-8,8>>^ Ele cobre os céus de nuvens, provê chuva para a terra e faz o capim crescer nos montes.

[[v19-147-9]]

^<<v19-147-9,9>>^ Alimenta os animais selvagens e dá de comer aos filhotes dos corvos quando pedem.

[[v19-147-10]]

^<<v19-147-10,10>>^ Seu prazer não está na força do cavalo, nem no poder humano.

[[v19-147-11]]

^<<v19-147-11,11>>^ O SENHOR se agrada dos que o temem, dos que põem a esperança em seu amor.

[[v19-147-12]]

^<<v19-147-12,12>>^ Exalte o SENHOR, ó Jerusalém! Louve seu Deus, ó Sião!

[[v19-147-13]]

^<<v19-147-13,13>>^ Pois ele reforçou as trancas de suas portas e abençoou seus filhos dentro de seus muros.

[[v19-147-14]]

^<<v19-147-14,14>>^ Ele conserva a paz em suas fronteiras e satisfaz sua fome com o melhor trigo.

[[v19-147-15]]

^<<v19-147-15,15>>^ Ele envia suas ordens ao mundo, e sua palavra corre veloz.

[[v19-147-16]]

^<<v19-147-16,16>>^ Envia a neve como lã branca e espalha a geada sobre a terra como cinzas.

[[v19-147-17]]

^<<v19-147-17,17>>^ Lança granizo como pedras; quem é capaz de suportar o frio intenso?

[[v19-147-18]]

^<<v19-147-18,18>>^ Então, por sua ordem, tudo se dissolve; envia seus ventos, e o gelo derrete.

[[v19-147-19]]

^<<v19-147-19,19>>^ Ele revelou sua palavra a Jacó, seus decretos e estatutos, a Israel.

[[v19-147-20]]

^<<v19-147-20,20>>^ Não fez o mesmo com nenhuma outra nação; elas não conhecem seus estatutos. Louvado seja o SENHOR!

'''

xref:019-salmos/019-salmos-146.adoc#v19-146-0[&#60; Capítulo Anterior] | <<v19-147-0,Topo>> | xref:019-salmos/019-salmos-148.adoc#v19-148-0[Próximo Capítulo &#62;]