include::./index.adoc[]

[[v19-53-0]]
=== Salmos, 53
// nvt ?, NVT - Nova Versão Transformadora

[[v19-53-1]]

^<<v19-53-1,1>>^ Os tolos dizem em seu coração: "Não há Deus". São corruptos e praticam o mal; nenhum deles faz o bem.

[[v19-53-2]]

^<<v19-53-2,2>>^ Deus olha dos céus para toda a humanidade, para ver se alguém é sábio, se alguém busca a Deus.

[[v19-53-3]]

^<<v19-53-3,3>>^ Todos, porém, se desviaram; todos se corromperam. Ninguém faz o bem, nem um sequer!

[[v19-53-4]]

^<<v19-53-4,4>>^ Acaso os que praticam o mal jamais aprenderão? Devoram meu povo como se fosse pão e nem pensam em orar a Deus.

[[v19-53-5]]

^<<v19-53-5,5>>^ Grande terror se apoderará deles, terror como nunca experimentaram. Deus espalhará os ossos dos que atacam seu povo; serão humilhados, pois Deus os rejeitou.

[[v19-53-6]]

^<<v19-53-6,6>>^ Quem virá do monte Sião para salvar Israel? Quando Deus restaurar seu povo, Jacó dará gritos de alegria, e Israel exultará.

'''

xref:019-salmos/019-salmos-052.adoc#v19-52-0[&#60; Capítulo Anterior] | <<v19-53-0,Topo>> | xref:019-salmos/019-salmos-054.adoc#v19-54-0[Próximo Capítulo &#62;]