include::./index.adoc[]

[[v19-139-0]]
=== Salmos, 139
// nvt ?, NVT - Nova Versão Transformadora

[[v19-139-1]]

^<<v19-139-1,1>>^ Ó SENHOR, tu examinas meu coração e conheces tudo a meu respeito.

[[v19-139-2]]

^<<v19-139-2,2>>^ Sabes quando me sento e quando me levanto; mesmo de longe, conheces meus pensamentos.

[[v19-139-3]]

^<<v19-139-3,3>>^ Tu me vês quando viajo e quando descanso; sabes tudo que faço.

[[v19-139-4]]

^<<v19-139-4,4>>^ Antes mesmo de eu falar, SENHOR, sabes o que vou dizer.

[[v19-139-5]]

^<<v19-139-5,5>>^ Vais adiante de mim e me segues; pões sobre mim a tua mão.

[[v19-139-6]]

^<<v19-139-6,6>>^ Esse conhecimento é maravilhoso demais para mim; é grande demais para eu compreender!

[[v19-139-7]]

^<<v19-139-7,7>>^ É impossível escapar do teu Espírito; não há como fugir da tua presença.

[[v19-139-8]]

^<<v19-139-8,8>>^ Se subo aos céus, lá estás; se desço ao mundo dos mortos, lá estás também.

[[v19-139-9]]

^<<v19-139-9,9>>^ Se eu tomar as asas do amanhecer, se habitar do outro lado do oceano,

[[v19-139-10]]

^<<v19-139-10,10>>^ mesmo ali tua mão me guiará, e tua força me sustentará.

[[v19-139-11]]

^<<v19-139-11,11>>^ Eu poderia pedir à escuridão que me escondesse, e à luz ao meu redor que se tornasse noite,

[[v19-139-12]]

^<<v19-139-12,12>>^ mas nem mesmo na escuridão posso me esconder de ti. Para ti, a noite é tão clara como o dia; escuridão e luz são a mesma coisa.

[[v19-139-13]]

^<<v19-139-13,13>>^ Tu formaste o meu interior e me teceste no ventre de minha mãe.

[[v19-139-14]]

^<<v19-139-14,14>>^ Eu te agradeço por me teres feito de modo tão extraordinário; tuas obras são maravilhosas, e disso eu sei muito bem.

[[v19-139-15]]

^<<v19-139-15,15>>^ Tu me observavas quando eu estava sendo formado em segredo, enquanto eu era tecido na escuridão.

[[v19-139-16]]

^<<v19-139-16,16>>^ Tu me viste quando eu ainda estava no ventre; cada dia de minha vida estava registrado em teu livro, cada momento foi estabelecido quando ainda nenhum deles existia.

[[v19-139-17]]

^<<v19-139-17,17>>^ Como são preciosos os teus pensamentos a meu respeito, ó Deus; é impossível enumerá-los!

[[v19-139-18]]

^<<v19-139-18,18>>^ Não sou capaz de contá-los; são mais numerosos que os grãos de areia. E, quando acordo, tu ainda estás comigo.

[[v19-139-19]]

^<<v19-139-19,19>>^ Ó Deus, quem dera destruísses os perversos; afastem-se de mim, assassinos!

[[v19-139-20]]

^<<v19-139-20,20>>^ Eles blasfemam contra ti; teus inimigos usam teu nome em vão.

[[v19-139-21]]

^<<v19-139-21,21>>^ Acaso, SENHOR, não devo odiar os que te odeiam? Não devo desprezar os que se opõem a ti?

[[v19-139-22]]

^<<v19-139-22,22>>^ Sim, eu os odeio com todas as minhas forças, pois teus inimigos são meus inimigos.

[[v19-139-23]]

^<<v19-139-23,23>>^ Examina-me, ó Deus, e conhece meu coração; prova-me e vê meus pensamentos.

[[v19-139-24]]

^<<v19-139-24,24>>^ Mostra-me se há em mim algo que te ofende e conduze-me pelo caminho eterno.

'''

xref:019-salmos/019-salmos-138.adoc#v19-138-0[&#60; Capítulo Anterior] | <<v19-139-0,Topo>> | xref:019-salmos/019-salmos-140.adoc#v19-140-0[Próximo Capítulo &#62;]