include::./index.adoc[]

[[v19-63-0]]
=== Salmos, 63
// nvt ?, NVT - Nova Versão Transformadora

[[v19-63-1]]

^<<v19-63-1,1>>^ Ó Deus, tu és meu Deus; eu te busco de todo o coração. Minha alma tem sede de ti; todo o meu corpo anseia por ti nesta terra seca, exausta e sem água.

[[v19-63-2]]

^<<v19-63-2,2>>^ Eu te vi em teu santuário e contemplei teu poder e tua glória.

[[v19-63-3]]

^<<v19-63-3,3>>^ Teu amor é melhor que a própria vida; com meus lábios te louvarei.

[[v19-63-4]]

^<<v19-63-4,4>>^ Sim, te louvarei enquanto viver; a ti em oração levantarei as mãos.

[[v19-63-5]]

^<<v19-63-5,5>>^ Tu me satisfazes mais que um rico banquete; com cânticos de alegria te louvarei.

[[v19-63-6]]

^<<v19-63-6,6>>^ Quando me deito, fico acordado pensando em ti, meditando a teu respeito a noite toda.

[[v19-63-7]]

^<<v19-63-7,7>>^ Pois tu és meu auxílio; à sombra de tuas asas canto de alegria.

[[v19-63-8]]

^<<v19-63-8,8>>^ Minha alma se apega a ti; tua forte mão direita me sustenta.

[[v19-63-9]]

^<<v19-63-9,9>>^ Aqueles, porém, que tramam me destruir descerão às profundezas da terra.

[[v19-63-10]]

^<<v19-63-10,10>>^ Morrerão pela espada e servirão de comida para os chacais.

[[v19-63-11]]

^<<v19-63-11,11>>^ O rei, contudo, se alegrará em Deus; todos que juraram falar a verdade o louvarão, mas os mentirosos serão calados.

'''

xref:019-salmos/019-salmos-062.adoc#v19-62-0[&#60; Capítulo Anterior] | <<v19-63-0,Topo>> | xref:019-salmos/019-salmos-064.adoc#v19-64-0[Próximo Capítulo &#62;]