include::./index.adoc[]

[[v55-4-0]]
=== 2 Timóteo, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v55-4-1]]

^<<v55-4-1,1>>^ Eu lhe digo solenemente, na presença de Deus e de Cristo Jesus, que um dia julgará os vivos e os mortos quando vier para estabelecer seu reino:

[[v55-4-2]]

^<<v55-4-2,2>>^ pregue a palavra. Esteja preparado, quer a ocasião seja favorável, quer não. Corrija, repreenda e encoraje com paciência e bom ensino.

[[v55-4-3]]

^<<v55-4-3,3>>^ Pois virá o tempo em que as pessoas já não escutarão o ensino verdadeiro. Seguirão os próprios desejos e buscarão mestres que lhes digam apenas aquilo que agrada seus ouvidos.

[[v55-4-4]]

^<<v55-4-4,4>>^ Rejeitarão a verdade e correrão atrás de mitos.

[[v55-4-5]]

^<<v55-4-5,5>>^ Você, porém, deve manter a sobriedade em todas as situações. Não tenha medo de sofrer. Trabalhe para anunciar as boas-novas e realize todo o ministério que lhe foi confiado.

[[v55-4-6]]

^<<v55-4-6,6>>^ Quanto a mim, minha vida já foi derramada como oferta para Deus. O tempo de minha morte se aproxima.

[[v55-4-7]]

^<<v55-4-7,7>>^ Lutei o bom combate, terminei a corrida e permaneci fiel.

[[v55-4-8]]

^<<v55-4-8,8>>^ Agora o prêmio me espera, a coroa de justiça que o Senhor, o justo Juiz, me dará no dia de sua volta. E o prêmio não será só para mim, mas para todos que, com grande expectativa, aguardam a sua vinda.

[[v55-4-9]]

^<<v55-4-9,9>>^ Por favor, venha assim que puder.

[[v55-4-10]]

^<<v55-4-10,10>>^ Demas me abandonou, pois ama as coisas desta vida e foi para Tessalônica. Crescente foi embora para a Galácia, e Tito, para a Dalmácia.

[[v55-4-11]]

^<<v55-4-11,11>>^ Apenas Lucas está comigo. Traga Marcos com você, pois ele me será útil no ministério.

[[v55-4-12]]

^<<v55-4-12,12>>^ Enviei Tíquico a Éfeso.

[[v55-4-13]]

^<<v55-4-13,13>>^ Quando vier, não se esqueça de trazer a capa que deixei com Carpo, em Trôade. Traga também meus livros e especialmente meus pergaminhos.

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexandre, o artífice que trabalha com cobre, me prejudicou muito, mas o Senhor o julgará pelo que ele fez.

[[v55-4-15]]

^<<v55-4-15,15>>^ Tome cuidado com ele, porque se opôs fortemente a tudo que dissemos.

[[v55-4-16]]

^<<v55-4-16,16>>^ Na primeira vez que fui levado perante o juiz, ninguém me acompanhou. Todos me abandonaram. Que isso não seja cobrado deles.

[[v55-4-17]]

^<<v55-4-17,17>>^ Mas o Senhor permaneceu ao meu lado e me deu forças para que eu pudesse anunciar as boas-novas plenamente, a fim de que todos os gentios as ouvissem. E ele me livrou da boca do leão.

[[v55-4-18]]

^<<v55-4-18,18>>^ Sim, o Senhor me livrará de todo ataque maligno e me levará em segurança para seu reino celestial. A Deus seja a glória para todo o sempre! Amém.

[[v55-4-19]]

^<<v55-4-19,19>>^ Envie minhas saudações a Priscila e a Áquila e à família de Onesíforo.

[[v55-4-20]]

^<<v55-4-20,20>>^ Erasto ficou em Corinto, e deixei Trófimo doente em Mileto.

[[v55-4-21]]

^<<v55-4-21,21>>^ Faça todo o possível para estar aqui antes do inverno. Êubulo lhe manda lembranças, e também Prudente, Lino, Cláudia e todos os irmãos.

[[v55-4-22]]

^<<v55-4-22,22>>^ Que o Senhor esteja com seu espírito. E que a graça esteja com todos vocês.

'''

xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-tito/056-tito-001.adoc#v56-1-0[Próximo Capítulo &#62;]