include::./index.adoc[]

[[v55-3-0]]
=== 2 Timóteo, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v55-3-1]]

^<<v55-3-1,1>>^ Saiba que nos últimos dias haverá tempos muito difíceis.

[[v55-3-2]]

^<<v55-3-2,2>>^ Porque as pessoas só amarão a si mesmas e ao dinheiro. Serão arrogantes e orgulhosas, zombarão de Deus, desobedecerão a seus pais e serão ingratas e profanas.

[[v55-3-3]]

^<<v55-3-3,3>>^ Não terão afeição nem perdoarão; caluniarão outros e não terão autocontrole. Serão cruéis e odiarão o que é bom,

[[v55-3-4]]

^<<v55-3-4,4>>^ trairão os amigos, serão imprudentes e cheias de si e amarão os prazeres em vez de amar a Deus.

[[v55-3-5]]

^<<v55-3-5,5>>^ Serão religiosas apenas na aparência, mas rejeitarão o poder capaz de lhes dar a verdadeira devoção. Fique longe de gente assim!

[[v55-3-6]]

^<<v55-3-6,6>>^ Entre tais pessoas há aqueles que se infiltram na casa alheia e conquistam a confiança de mulheres vulneráveis, carregadas de pecados e controladas por todo tipo de desejo,

[[v55-3-7]]

^<<v55-3-7,7>>^ mulheres que estão sempre em busca de novos ensinos, mas jamais conseguem entender a verdade.

[[v55-3-8]]

^<<v55-3-8,8>>^ Esses mestres se opõem à verdade, como Janes e Jambres se opuseram a Moisés. Têm a mente depravada, e sua fé não é autêntica.

[[v55-3-9]]

^<<v55-3-9,9>>^ Contudo, não irão muito longe. Um dia, alguém verá como são insensatos, como aconteceu com Janes e Jambres.

[[v55-3-10]]

^<<v55-3-10,10>>^ Mas você sabe muito bem o que eu ensino, como vivo e qual é meu propósito de vida. Conhece minha fé, minha paciência, meu amor e minha perseverança.

[[v55-3-11]]

^<<v55-3-11,11>>^ Sabe quanta perseguição e quanto sofrimento suportei e o que me aconteceu em Antioquia, Icônio e Listra; o Senhor, porém, me livrou de tudo isso.

[[v55-3-12]]

^<<v55-3-12,12>>^ Sim, e todos que desejam ter uma vida de devoção em Cristo Jesus sofrerão perseguições.

[[v55-3-13]]

^<<v55-3-13,13>>^ Mas os perversos e os impostores irão de mal a pior. Enganarão outros e eles próprios serão enganados.

[[v55-3-14]]

^<<v55-3-14,14>>^ Você, porém, deve permanecer fiel àquilo que lhe foi ensinado. Sabe que é a verdade, pois conhece aqueles de quem aprendeu.

[[v55-3-15]]

^<<v55-3-15,15>>^ Desde a infância lhe foram ensinadas as Sagradas Escrituras, que lhe deram sabedoria para receber a salvação que vem pela fé em Cristo Jesus.

[[v55-3-16]]

^<<v55-3-16,16>>^ Toda a Escritura é inspirada por Deus e útil para nos ensinar o que é verdadeiro e para nos fazer perceber o que não está em ordem em nossa vida. Ela nos corrige quando erramos e nos ensina a fazer o que é certo.

[[v55-3-17]]

^<<v55-3-17,17>>^ Deus a usa para preparar e capacitar seu povo para toda boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[&#60; Capítulo Anterior] | <<v55-3-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[Próximo Capítulo &#62;]