include::./index.adoc[]

[[v55-2-0]]
=== 2 Timóteo, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v55-2-1]]

^<<v55-2-1,1>>^ Meu filho, seja forte por meio da graça que há em Cristo Jesus.

[[v55-2-2]]

^<<v55-2-2,2>>^ Você me ouviu ensinar verdades confirmadas por muitas testemunhas confiáveis. Agora, ensine-as a pessoas de confiança que possam transmiti-las a outros.

[[v55-2-3]]

^<<v55-2-3,3>>^ Suporte comigo o sofrimento, como bom soldado de Cristo Jesus.

[[v55-2-4]]

^<<v55-2-4,4>>^ Nenhum soldado se deixa envolver em assuntos da vida civil, pois se o fizesse não poderia agradar o oficial que o alistou.

[[v55-2-5]]

^<<v55-2-5,5>>^ O atleta não conquista o prêmio se não seguir as regras.

[[v55-2-6]]

^<<v55-2-6,6>>^ E o lavrador que trabalha arduamente deve ser o primeiro a colher o fruto de seu esforço.

[[v55-2-7]]

^<<v55-2-7,7>>^ Pense no que estou lhe dizendo. O Senhor o ajudará a entender todas essas coisas.

[[v55-2-8]]

^<<v55-2-8,8>>^ Lembre-se de que Jesus Cristo, descendente do rei Davi, ressuscitou dos mortos. Essas são as boas-novas que eu anuncio.

[[v55-2-9]]

^<<v55-2-9,9>>^ E, por causa disso, sofro e estou preso como um criminoso. Mas a palavra de Deus não está presa.

[[v55-2-10]]

^<<v55-2-10,10>>^ Portanto, estou disposto a suportar qualquer coisa se isso trouxer salvação e glória eterna em Cristo Jesus para os que foram escolhidos.

[[v55-2-11]]

^<<v55-2-11,11>>^ Esta é uma afirmação digna de confiança: "Se morrermos com ele, também com ele viveremos.

[[v55-2-12]]

^<<v55-2-12,12>>^ Se perseverarmos, com ele reinaremos. Se o negarmos, ele nos negará.

[[v55-2-13]]

^<<v55-2-13,13>>^ Se formos infiéis, ele permanecerá fiel, pois não pode negar a si mesmo".

[[v55-2-14]]

^<<v55-2-14,14>>^ Lembre essas coisas a todos e ordene-lhes na presença de Deus que deixem de brigar por causa de palavras. Essas discussões são inúteis e podem causar grave prejuízo a quem as ouve.

[[v55-2-15]]

^<<v55-2-15,15>>^ Esforce-se sempre para receber a aprovação do Deus a quem você serve. Seja um bom trabalhador, que não tem de que se envergonhar e que ensina corretamente a palavra da verdade.

[[v55-2-16]]

^<<v55-2-16,16>>^ Evite conversas tolas e profanas, que só levam a mais comportamentos mundanos.

[[v55-2-17]]

^<<v55-2-17,17>>^ Esse tipo de conversa se espalha como câncer, a exemplo do ocorrido com Himeneu e Fileto.

[[v55-2-18]]

^<<v55-2-18,18>>^ Eles deixaram o caminho da verdade, afirmando que a ressurreição dos mortos já aconteceu, e com isso desviaram alguns da fé.

[[v55-2-19]]

^<<v55-2-19,19>>^ Mas o alicerce sólido de Deus permanece firme, com esta inscrição: "O Senhor conhece quem pertence a ele" e "Todos que pertencem ao Senhor devem se afastar do mal".

[[v55-2-20]]

^<<v55-2-20,20>>^ Numa casa grande, alguns utensílios são de ouro e de prata, e outros, de madeira e de barro. Os utensílios de mais valor são reservados para ocasiões especiais, e os de menos valor, para uso diário.

[[v55-2-21]]

^<<v55-2-21,21>>^ Se você se mantiver puro, será um utensílio para fins honrosos. Sua vida será limpa, e você estará pronto para que o Senhor da casa o empregue para toda boa obra.

[[v55-2-22]]

^<<v55-2-22,22>>^ Fuja de tudo que estimule as paixões da juventude. Em vez disso, busque justiça, fidelidade, amor e paz, na companhia daqueles que invocam o Senhor com coração puro.

[[v55-2-23]]

^<<v55-2-23,23>>^ Digo mais uma vez: não se envolva em discussões tolas e ignorantes que só servem para gerar brigas.

[[v55-2-24]]

^<<v55-2-24,24>>^ O servo do Senhor não deve viver brigando, mas ser amável com todos, apto a ensinar e paciente.

[[v55-2-25]]

^<<v55-2-25,25>>^ Instrua com mansidão aqueles que se opõem, na esperança de que Deus os leve ao arrependimento e, assim, conheçam a verdade.

[[v55-2-26]]

^<<v55-2-26,26>>^ Então voltarão ao perfeito juízo e escaparão da armadilha do diabo, que os prendeu para fazerem o que ele quer.

'''

xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[&#60; Capítulo Anterior] | <<v55-2-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[Próximo Capítulo &#62;]