include::./index.adoc[]

[[v15-10-0]]
=== Esdras, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v15-10-1]]

^<<v15-10-1,1>>^ Enquanto Esdras orava e fazia essa confissão, chorando e com o rosto no chão diante do templo de Deus, uma grande multidão de israelitas — homens, mulheres e crianças — se reuniu e chorou amargamente com ele.

[[v15-10-2]]

^<<v15-10-2,2>>^ Então Secanias, filho de Jeiel, descendente de Elão, disse a Esdras: "Fomos infiéis a nosso Deus, pois nos casamos com mulheres estrangeiras, dos povos desta terra. Apesar disso, há esperança para Israel.

[[v15-10-3]]

^<<v15-10-3,3>>^ Façamos agora uma aliança com nosso Deus, firmando que nos divorciaremos de nossas esposas estrangeiras e as mandaremos embora com seus filhos. Seguiremos seu conselho e o conselho dos outros que tremem diante dos mandamentos de nosso Deus. Que tudo seja feito de acordo com a lei de Deus.

[[v15-10-4]]

^<<v15-10-4,4>>^ Levante-se, pois é seu dever nos dizer como corrigir esta situação. Nós o apoiaremos; portanto, seja forte e faça o que tem de ser feito!".

[[v15-10-5]]

^<<v15-10-5,5>>^ Então Esdras se levantou e exigiu que os líderes dos sacerdotes, os levitas e todo o povo de Israel jurassem que fariam o que Secanias tinha dito. E todos fizeram um juramento solene.

[[v15-10-6]]

^<<v15-10-6,6>>^ Em seguida, Esdras se retirou de diante do templo de Deus e foi à sala de Joanã, filho de Eliasibe. Não bebeu nem comeu nada enquanto esteve ali, pois ainda lamentava a infidelidade dos exilados que haviam regressado.

[[v15-10-7]]

^<<v15-10-7,7>>^ Depois disso, foi feita uma proclamação por todo o Judá e Jerusalém, para que todos os que vieram do exílio se reunissem em Jerusalém.

[[v15-10-8]]

^<<v15-10-8,8>>^ Aqueles que não viessem em três dias perderiam todas as suas propriedades e seriam expulsos da comunidade dos exilados, conforme a decisão dos líderes e das autoridades.

[[v15-10-9]]

^<<v15-10-9,9>>^ Dentro de três dias, todo o povo de Judá e de Benjamim havia se reunido em Jerusalém. A reunião aconteceu no dia 19 de dezembro, e todo o povo estava sentado na praça diante do templo de Deus. Tremiam por causa da seriedade do assunto e porque chovia.

[[v15-10-10]]

^<<v15-10-10,10>>^ Então o sacerdote Esdras se levantou e disse: "Vocês agiram de modo infiel. Aumentaram a culpa de Israel ao se casar com mulheres estrangeiras.

[[v15-10-11]]

^<<v15-10-11,11>>^ Agora, confessem seu pecado ao SENHOR, o Deus de seus antepassados, e façam o que agrada a ele. Separem-se do povo da terra e dessas mulheres estrangeiras".

[[v15-10-12]]

^<<v15-10-12,12>>^ Toda a comunidade respondeu em alta voz: "Você tem razão! Faremos o que disse!

[[v15-10-13]]

^<<v15-10-13,13>>^ No entanto, não é algo que possa ser feito em um dia ou dois, pois há muitos de nós envolvidos neste grande pecado. E agora é a estação das chuvas, portanto não podemos ficar aqui fora por muito mais tempo.

[[v15-10-14]]

^<<v15-10-14,14>>^ Que nossos líderes decidam por toda a comunidade. Todo aquele que tiver uma esposa estrangeira virá num dia marcado, acompanhado das autoridades e dos juízes de sua cidade, para que a ira ardente de nosso Deus a esse respeito seja afastada de nós".

[[v15-10-15]]

^<<v15-10-15,15>>^ Os únicos que se opuseram à proposta foram Jônatas, filho de Asael, e Jazeías, filho de Ticvá, apoiados por Mesulão e pelo levita Sabetai.

[[v15-10-16]]

^<<v15-10-16,16>>^ Foi esse, portanto, o plano que seguiram. Esdras escolheu líderes para representarem suas famílias e designou cada representante por nome. No dia 29 de dezembro, os líderes se reuniram para tratar da questão.

[[v15-10-17]]

^<<v15-10-17,17>>^ Assim, em 27 de março, o primeiro dia do novo ano, haviam terminado de resolver todos os casos de homens que tinham se casado com mulheres estrangeiras.

[[v15-10-18]]

^<<v15-10-18,18>>^ Os sacerdotes que se casaram com mulheres estrangeiras foram: Da família de Jesua, filho de Jeozadaque, e de seus irmãos: Maaseias, Eliézer, Jaribe e Gedalias.

[[v15-10-19]]

^<<v15-10-19,19>>^ Assumiram o compromisso de divorciar-se de suas esposas, e cada um ofereceu um carneiro como sacrifício por causa de sua culpa.

[[v15-10-20]]

^<<v15-10-20,20>>^ Da família de Imer: Hanani e Zebadias.

[[v15-10-21]]

^<<v15-10-21,21>>^ Da família de Harim: Maaseias, Elias, Semaías, Jeiel e Uzias.

[[v15-10-22]]

^<<v15-10-22,22>>^ Da família de Pasur: Elioenai, Maaseias, Ismael, Natanael, Jozabade e Elasa.

[[v15-10-23]]

^<<v15-10-23,23>>^ Os levitas culpados desse pecado foram: Jozabade, Simei, Quelaías (também chamado Quelita), Petaías, Judá e Eliézer.

[[v15-10-24]]

^<<v15-10-24,24>>^ O cantor culpado desse pecado foi: Eliasibe. Os porteiros culpados desse pecado foram: Salum, Telém e Uri.

[[v15-10-25]]

^<<v15-10-25,25>>^ Os outros israelitas culpados desse pecado foram: Da família de Parós: Ramias, Jezias, Malquias, Miamim, Eleazar, Malquias e Benaia.

[[v15-10-26]]

^<<v15-10-26,26>>^ Da família de Elão: Matanias, Zacarias, Jeiel, Abdi, Jeremote e Elias.

[[v15-10-27]]

^<<v15-10-27,27>>^ Da família de Zatu: Elioenai, Eliasibe, Matanias, Jeremote, Zabade e Aziza.

[[v15-10-28]]

^<<v15-10-28,28>>^ Da família de Bebai: Joanã, Hananias, Zabai e Atlai.

[[v15-10-29]]

^<<v15-10-29,29>>^ Da família de Bani: Mesulão, Maluque, Adaías, Jasube, Seal e Jeremote.

[[v15-10-30]]

^<<v15-10-30,30>>^ Da família de Paate-Moabe: Adna, Quelal, Benaia, Maaseias, Matanias, Bezaleel, Binui e Manassés.

[[v15-10-31]]

^<<v15-10-31,31>>^ Da família de Harim: Eliézer, Issias, Malquias, Semaías, Simeão,

[[v15-10-32]]

^<<v15-10-32,32>>^ Benjamim, Maluque e Semarias.

[[v15-10-33]]

^<<v15-10-33,33>>^ Da família de Hasum: Matenai, Matatá, Zabade, Elifelete, Jeremai, Manassés e Simei.

[[v15-10-34]]

^<<v15-10-34,34>>^ Da família de Bani: Maadai, Anrão, Uel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Benaia, Bedias, Queluí,

[[v15-10-36]]

^<<v15-10-36,36>>^ Vanias, Meremote, Eliasibe,

[[v15-10-37]]

^<<v15-10-37,37>>^ Matanias, Matenai e Jaasai.

[[v15-10-38]]

^<<v15-10-38,38>>^ Da família de Binui: Simei,

[[v15-10-39]]

^<<v15-10-39,39>>^ Selemias, Natã, Adaías,

[[v15-10-40]]

^<<v15-10-40,40>>^ Macnadbai, Sasai, Sarai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Azareel, Selemias, Semarias,

[[v15-10-42]]

^<<v15-10-42,42>>^ Salum, Amarias e José.

[[v15-10-43]]

^<<v15-10-43,43>>^ Da família de Nebo: Jeiel, Matitias, Zabade, Zebina, Jadai, Joel e Benaia.

[[v15-10-44]]

^<<v15-10-44,44>>^ Todos esses homens se casaram com mulheres estrangeiras, e alguns tiveram filhos com essas esposas.

'''

xref:015-esdras/015-esdras-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-neemias/016-neemias-001.adoc#v16-1-0[Próximo Capítulo &#62;]