include::./index.adoc[]

[[v15-1-0]]
=== Esdras, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v15-1-1]]

^<<v15-1-1,1>>^ No primeiro ano de Ciro, rei da Pérsia, o SENHOR cumpriu a profecia que havia anunciado por meio de Jeremias. Despertou o coração de Ciro para registrar por escrito a seguinte proclamação e enviá-la a todo o seu reino:

[[v15-1-2]]

^<<v15-1-2,2>>^ "Assim diz Ciro, rei da Pérsia: "O SENHOR, o Deus dos céus, me deu todos os reinos da terra. Ele me encarregou de lhe construir um templo em Jerusalém, em Judá.

[[v15-1-3]]

^<<v15-1-3,3>>^ Quem pertence ao povo de Deus, volte a Jerusalém, em Judá, para reconstruir o templo do SENHOR, o Deus de Israel, que habita em Jerusalém. E que seu Deus esteja com vocês!

[[v15-1-4]]

^<<v15-1-4,4>>^ Onde quer que se encontre esse remanescente judeu, que seus vizinhos ajudem com as despesas, dando-lhes prata e ouro, suprimentos e animais, além de ofertas voluntárias para o templo de Deus, em Jerusalém".

[[v15-1-5]]

^<<v15-1-5,5>>^ Então o SENHOR despertou o coração dos sacerdotes, dos levitas e dos chefes das tribos de Judá e Benjamim, para que fossem a Jerusalém e reconstruíssem o templo do SENHOR.

[[v15-1-6]]

^<<v15-1-6,6>>^ Todos os seus vizinhos ajudaram, dando-lhes utensílios de prata e ouro, suprimentos e animais. Também lhes deram muitos presentes valiosos, além de todas as ofertas voluntárias.

[[v15-1-7]]

^<<v15-1-7,7>>^ O rei Ciro tirou os utensílios que o rei Nabucodonosor havia levado do templo do SENHOR, em Jerusalém, e colocado no templo de seus próprios deuses.

[[v15-1-8]]

^<<v15-1-8,8>>^ Ciro, rei da Pérsia, deu instruções a Mitredate, seu tesoureiro, para que contasse esses utensílios e os entregasse a Sesbazar, líder dos exilados que voltavam para Judá.

[[v15-1-9]]

^<<v15-1-9,9>>^ Esta é uma lista dos objetos que foram devolvidos: 30 bacias de ouro, 1.000 bacias de prata, 29 incensários de prata,

[[v15-1-10]]

^<<v15-1-10,10>>^ 30 tigelas de ouro, 410 tigelas de prata, 1.000 objetos diversos.

[[v15-1-11]]

^<<v15-1-11,11>>^ Ao todo, havia 5.400 utensílios de ouro e prata. Sesbazar trouxe tudo isso consigo quando os exilados voltaram da Babilônia para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[&#60; Capítulo Anterior] | <<v15-1-0,Topo>> | xref:015-esdras/015-esdras-002.adoc#v15-2-0[Próximo Capítulo &#62;]