include::./index.adoc[]

[[v15-6-0]]
=== Esdras, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v15-6-1]]

^<<v15-6-1,1>>^ Então o rei Dario ordenou que se fizesse uma busca nos arquivos da Babilônia, que ficavam guardados junto aos tesouros.

[[v15-6-2]]

^<<v15-6-2,2>>^ Mas foi na fortaleza em Ecbatana, na província da Média, que se encontrou um documento que dizia: "Memorando:

[[v15-6-3]]

^<<v15-6-3,3>>^ "No primeiro ano do reinado do rei Ciro, foi publicado um decreto a respeito do templo de Deus, em Jerusalém. "Que o templo seja reconstruído para ser um local onde se ofereçam sacrifícios, usando os alicerces originais. Ele terá 27 metros de altura e 27 metros de largura.

[[v15-6-4]]

^<<v15-6-4,4>>^ A cada três camadas de grandes pedras, será colocada uma camada de madeira. Todas as despesas serão pagas pela tesouraria real.

[[v15-6-5]]

^<<v15-6-5,5>>^ Além disso, os utensílios de ouro e de prata que Nabucodonosor levou do templo de Deus, em Jerusalém, para a Babilônia devem ser devolvidos a Jerusalém e colocados em seus devidos lugares. Que sejam levados de volta ao templo de Deus".

[[v15-6-6]]

^<<v15-6-6,6>>^ O rei Dario enviou esta mensagem: "Agora, portanto, Tatenai, governador da província a oeste do rio Eufrates, Setar-Bozenai, seus companheiros e outros oficiais a oeste do rio Eufrates, permaneçam afastados de lá!

[[v15-6-7]]

^<<v15-6-7,7>>^ Não interfiram na construção do templo de Deus. Deixem que seja reconstruído em seu antigo local, e não impeçam o governador de Judá e os líderes dos judeus de realizarem seu trabalho.

[[v15-6-8]]

^<<v15-6-8,8>>^ "Além disso, decreto que ajudem esses líderes dos judeus a reconstruir o templo de Deus. Paguem, sem demora, todos os custos da construção, usando os impostos recolhidos na província a oeste do rio Eufrates, para que a obra não seja interrompida.

[[v15-6-9]]

^<<v15-6-9,9>>^ "Deem aos sacerdotes em Jerusalém tudo que eles precisarem: novilhos, carneiros e cordeiros para os holocaustos oferecidos ao Deus dos céus. Providenciem, sem falta, a quantidade de trigo, sal, vinho e azeite que for necessária para cada dia.

[[v15-6-10]]

^<<v15-6-10,10>>^ Assim, eles poderão oferecer sacrifícios agradáveis ao Deus dos céus e orar pelo bem-estar do rei e de seus filhos.

[[v15-6-11]]

^<<v15-6-11,11>>^ "Se alguém desobedecer a este decreto de alguma maneira, terá uma viga de sua casa arrancada. Ele será amarrado a essa viga e pendurado nela, e sua casa será transformada num monte de entulho.

[[v15-6-12]]

^<<v15-6-12,12>>^ Que o Deus que escolheu a cidade de Jerusalém como lugar para que seu nome seja honrado destrua qualquer rei ou nação que desobedecer a esta ordem e destruir este templo. "Eu, Dario, publiquei este decreto. Que ele seja obedecido com toda a diligência".

[[v15-6-13]]

^<<v15-6-13,13>>^ Tatenai, governador da província a oeste do rio Eufrates, Setar-Bozenai e seus companheiros obedeceram de imediato à ordem do rei Dario.

[[v15-6-14]]

^<<v15-6-14,14>>^ Com isso, os líderes dos judeus puderam continuar seu trabalho e foram encorajados pela pregação dos profetas Ageu e Zacarias, filho de Ido. Finalmente, o templo foi terminado, como havia sido ordenado pelo Deus de Israel e decretado por Ciro, Dario e Artaxerxes, reis da Pérsia.

[[v15-6-15]]

^<<v15-6-15,15>>^ O templo foi concluído no dia 12 de março, no sexto ano do reinado do rei Dario.

[[v15-6-16]]

^<<v15-6-16,16>>^ Então o templo de Deus foi dedicado com grande alegria pelos israelitas, pelos sacerdotes, pelos levitas e pelo restante do povo que regressou do exílio.

[[v15-6-17]]

^<<v15-6-17,17>>^ Durante a cerimônia de dedicação, foram sacrificados cem novilhos, duzentos carneiros e quatrocentos cordeiros. Doze bodes foram apresentados como oferta pelo pecado de todo o Israel, de acordo com o número das tribos.

[[v15-6-18]]

^<<v15-6-18,18>>^ Em seguida, os sacerdotes e os levitas foram divididos em vários grupos para servirem no templo de Deus, em Jerusalém, conforme prescrito no Livro de Moisés.

[[v15-6-19]]

^<<v15-6-19,19>>^ No dia 21 de abril, o povo que havia regressado do exílio celebrou a Páscoa.

[[v15-6-20]]

^<<v15-6-20,20>>^ Os sacerdotes e os levitas haviam se purificado e estavam cerimonialmente puros. Abateram o cordeiro da Páscoa por todos que regressaram, por seus colegas, os sacerdotes, e por si mesmos.

[[v15-6-21]]

^<<v15-6-21,21>>^ Todo o povo de Israel que havia regressado do exílio participou da refeição de Páscoa, junto com todos que haviam deixado os costumes impuros dos povos que ali viviam a fim de adorar o SENHOR, o Deus de Israel.

[[v15-6-22]]

^<<v15-6-22,22>>^ Em seguida, comemoraram durante sete dias a Festa dos Pães sem Fermento. Houve grande alegria em toda a terra, pois o SENHOR tornou o rei da Assíria favorável a eles e o levou a ajudá-los a reconstruir o templo de Deus, o Deus de Israel.

'''

xref:015-esdras/015-esdras-005.adoc#v15-5-0[&#60; Capítulo Anterior] | <<v15-6-0,Topo>> | xref:015-esdras/015-esdras-007.adoc#v15-7-0[Próximo Capítulo &#62;]