include::./index.adoc[]

[[v15-9-0]]
=== Esdras, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v15-9-1]]

^<<v15-9-1,1>>^ Depois que essas coisas foram feitas, os líderes judeus vieram e me disseram: "Muitos israelitas, e até mesmo alguns sacerdotes e levitas, não se mantiveram separados dos outros povos que habitam nesta terra. Adotaram as práticas detestáveis dos cananeus, dos hititas, dos ferezeus, dos jebuseus, dos amonitas, dos moabitas, dos egípcios e dos amorreus.

[[v15-9-2]]

^<<v15-9-2,2>>^ Os homens de Israel se casaram com mulheres desses povos e as tomaram como esposas para seus filhos. A descendência santa se contaminou por meio desses casamentos mistos. E, pior ainda, os líderes e os oficiais foram os primeiros a cometer essa infidelidade".

[[v15-9-3]]

^<<v15-9-3,3>>^ Quando ouvi isso, rasguei minha túnica e meu manto, arranquei cabelos da cabeça e da barba e me sentei, absolutamente pasmo.

[[v15-9-4]]

^<<v15-9-4,4>>^ Então todos que tremiam diante das palavras do Deus de Israel vieram e sentaram-se comigo por causa dessa infidelidade cometida pelos exilados que haviam regressado. E fiquei sentado ali, atônito, até o sacrifício da tarde.

[[v15-9-5]]

^<<v15-9-5,5>>^ Na hora do sacrifício, levantei-me de onde havia sentado em lamentação, com as roupas rasgadas. Caí de joelhos, ergui as mãos ao SENHOR, meu Deus,

[[v15-9-6]]

^<<v15-9-6,6>>^ e orei: "Ó meu Deus, estou profundamente humilhado e tenho vergonha de levantar meu rosto para ti. Pois nossos pecados se elevam acima de nossa cabeça, e nossa culpa chegou até os céus.

[[v15-9-7]]

^<<v15-9-7,7>>^ Desde os dias de nossos antepassados até agora, temos vivido cheios de pecado. Por isso, nós, nossos reis e nossos sacerdotes fomos entregues nas mãos dos reis da terra. Fomos mortos, capturados, roubados e desprezados, como acontece hoje.

[[v15-9-8]]

^<<v15-9-8,8>>^ "Agora, porém, a graça do SENHOR, nosso Deus, nos foi concedida por um breve momento. Ele permitiu que alguns de nós sobrevivêssemos como um remanescente e nos deu segurança neste lugar santo. Nosso Deus iluminou nossos olhos e nos concedeu um pouco de alívio de nossa escravidão.

[[v15-9-9]]

^<<v15-9-9,9>>^ Éramos escravos, mas, em seu amor leal, nosso Deus não nos abandonou na escravidão. Em vez disso, fez os reis da Pérsia nos tratarem com bondade. Ele renovou nossas forças, para que reconstruíssemos o templo de nosso Deus e restaurássemos suas ruínas. Deu-nos um muro de proteção em Judá e em Jerusalém.

[[v15-9-10]]

^<<v15-9-10,10>>^ "Agora, ó nosso Deus, o que podemos dizer depois de tudo isso? Pois, mais uma vez, abandonamos teus mandamentos!

[[v15-9-11]]

^<<v15-9-11,11>>^ Tu nos advertiste por meio de teus servos, os profetas, quando eles disseram: ‘A terra em que estão entrando está inteiramente contaminada pelas práticas detestáveis dos povos que nela habitam. Está cheia de corrupção, de uma extremidade à outra.

[[v15-9-12]]

^<<v15-9-12,12>>^ Não permitam que suas filhas se casem com os filhos deles, nem tomem as filhas deles como esposas para seus filhos. Jamais promovam a paz e a prosperidade dessas nações. Se seguirem essas instruções, serão fortes, desfrutarão das coisas boas que a terra produz e deixarão essa prosperidade como herança para seus filhos para sempre’.

[[v15-9-13]]

^<<v15-9-13,13>>^ "Tudo que nos aconteceu é castigo de nossa maldade e de nossa grande culpa. Ainda assim, recebemos um castigo muito menor do que merecíamos, pois tu, nosso Deus, permitiste que alguns de nós sobrevivêssemos como um remanescente.

[[v15-9-14]]

^<<v15-9-14,14>>^ E, no entanto, quebramos teus mandamentos outra vez e nos casamos com pessoas que praticam essas coisas detestáveis. Acaso tua ira não será suficiente para nos destruir, a ponto de não sobreviver nem mesmo este pequeno remanescente?

[[v15-9-15]]

^<<v15-9-15,15>>^ Ó SENHOR, Deus de Israel, tu és justo. Aqui estamos diante de ti com nossa culpa, um mero remanescente que escapou, embora, por sermos culpados, nenhum de nós tenha o direito de estar em tua presença".

'''

xref:015-esdras/015-esdras-008.adoc#v15-8-0[&#60; Capítulo Anterior] | <<v15-9-0,Topo>> | xref:015-esdras/015-esdras-010.adoc#v15-10-0[Próximo Capítulo &#62;]