include::./index.adoc[]

[[v15-5-0]]
=== Esdras, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v15-5-1]]

^<<v15-5-1,1>>^ Nessa época, os profetas Ageu e Zacarias, filho de Ido, profetizaram aos judeus de Judá e Jerusalém. Falavam em nome do Deus de Israel, que estava sobre eles.

[[v15-5-2]]

^<<v15-5-2,2>>^ Em resposta, Zorobabel, filho de Sealtiel, e Jesua, filho de Jeozadaque, começaram outra vez a reconstruir o templo de Deus em Jerusalém. E os profetas de Deus estavam com eles e os auxiliavam.

[[v15-5-3]]

^<<v15-5-3,3>>^ Tatenai, governador da província a oeste do rio Eufrates, Setar-Bozenai e seus companheiros foram a Jerusalém e perguntaram: "Quem lhes deu permissão para reconstruir este templo e restaurar esta estrutura?".

[[v15-5-4]]

^<<v15-5-4,4>>^ Também perguntaram os nomes de todos os homens que trabalhavam no templo.

[[v15-5-5]]

^<<v15-5-5,5>>^ Mas os olhos de Deus estavam sobre os líderes judeus, e eles não foram impedidos de prosseguir com a construção até que um relatório fosse enviado a Dario e ele comunicasse sua decisão.

[[v15-5-6]]

^<<v15-5-6,6>>^ Esta é uma cópia da carta que o governador Tatenai, Setar-Bozenai e os outros oficiais da província a oeste do rio Eufrates enviaram ao rei Dario:

[[v15-5-7]]

^<<v15-5-7,7>>^ "Ao rei Dario. Saudações.

[[v15-5-8]]

^<<v15-5-8,8>>^ "Informamos ao rei que fomos até o local da construção do templo do grande Deus na província de Judá. O templo está sendo reconstruído com pedras especialmente preparadas, e as vigas já estão sendo colocadas nas paredes. A obra avança com muita energia e êxito.

[[v15-5-9]]

^<<v15-5-9,9>>^ "Perguntamos aos líderes: ‘Quem lhes deu permissão para reconstruir este templo e restaurar esta estrutura?’.

[[v15-5-10]]

^<<v15-5-10,10>>^ E exigimos os nomes deles, para que pudéssemos dizer ao rei quem eram os líderes.

[[v15-5-11]]

^<<v15-5-11,11>>^ "Esta foi a resposta: ‘Somos servos do Deus dos céus e da terra e estamos reconstruindo o templo que foi construído aqui muitos anos atrás, por um grande rei de Israel.

[[v15-5-12]]

^<<v15-5-12,12>>^ Nossos antepassados, porém, provocaram a ira do Deus dos céus, e ele os entregou a Nabucodonosor, rei da Babilônia, que destruiu este templo e deportou o povo para a Babilônia.

[[v15-5-13]]

^<<v15-5-13,13>>^ No entanto, Ciro, rei da Babilônia, no primeiro ano de seu reinado, publicou um decreto ordenando que o templo de Deus fosse reconstruído.

[[v15-5-14]]

^<<v15-5-14,14>>^ O rei Ciro também devolveu os utensílios de ouro e de prata que Nabucodonosor havia tirado do templo de Deus, em Jerusalém, e colocado no templo da Babilônia. Esses utensílios foram removidos dali e entregues a um homem chamado Sesbazar, a quem o rei Ciro nomeou governador de Judá.

[[v15-5-15]]

^<<v15-5-15,15>>^ O rei instruiu Sesbazar a colocar os utensílios de volta em seu lugar, em Jerusalém, e a reconstruir o templo de Deus em seu antigo local.

[[v15-5-16]]

^<<v15-5-16,16>>^ Então Sesbazar veio e lançou os alicerces do templo de Deus em Jerusalém. O povo tem trabalhado nele desde então, embora ainda não esteja acabado’.

[[v15-5-17]]

^<<v15-5-17,17>>^ "Portanto, se parecer bem ao rei, pedimos que se faça uma busca nos arquivos reais da Babilônia, para descobrir se o rei Ciro de fato publicou esse decreto ordenando a reconstrução do templo de Deus, em Jerusalém. E que o rei nos informe sua decisão sobre esse assunto".

'''

xref:015-esdras/015-esdras-004.adoc#v15-4-0[&#60; Capítulo Anterior] | <<v15-5-0,Topo>> | xref:015-esdras/015-esdras-006.adoc#v15-6-0[Próximo Capítulo &#62;]