include::./index.adoc[]

[[v15-7-0]]
=== Esdras, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v15-7-1]]

^<<v15-7-1,1>>^ Muitos anos depois, durante o reinado de Artaxerxes, rei da Pérsia, havia um homem chamado Esdras. Ele era filho de Seraías, filho de Azarias, filho de Hilquias,

[[v15-7-2]]

^<<v15-7-2,2>>^ filho de Salum, filho de Zadoque, filho de Aitube,

[[v15-7-3]]

^<<v15-7-3,3>>^ filho de Amarias, filho de Azarias, filho de Meraiote,

[[v15-7-4]]

^<<v15-7-4,4>>^ filho de Zeraías, filho de Uzi, filho de Buqui,

[[v15-7-5]]

^<<v15-7-5,5>>^ filho de Abisua, filho de Fineias, filho de Eleazar, filho do sumo sacerdote Arão.

[[v15-7-6]]

^<<v15-7-6,6>>^ Esdras era escriba, conhecedor da lei de Moisés, dada ao povo pelo SENHOR, o Deus de Israel. Esdras foi da Babilônia a Jerusalém, e o rei lhe deu tudo que ele pediu, porque a mão do SENHOR, seu Deus, estava sobre ele.

[[v15-7-7]]

^<<v15-7-7,7>>^ Alguns dos israelitas, e também alguns sacerdotes, levitas, cantores, guardas das portas e servidores do templo, viajaram com ele para Jerusalém no sétimo ano do reinado de Artaxerxes.

[[v15-7-8]]

^<<v15-7-8,8>>^ Esdras chegou a Jerusalém em agosto desse mesmo ano.

[[v15-7-9]]

^<<v15-7-9,9>>^ Partiu da Babilônia em 8 de abril, o primeiro dia do novo ano, e chegou a Jerusalém em 4 de agosto, porque a bondosa mão do SENHOR, seu Deus, estava sobre ele.

[[v15-7-10]]

^<<v15-7-10,10>>^ Pois Esdras tinha decidido estudar a lei do SENHOR, obedecer a ela e ensinar seus decretos e estatutos ao povo de Israel.

[[v15-7-11]]

^<<v15-7-11,11>>^ O rei Artaxerxes tinha dado uma cópia da seguinte carta a Esdras, o sacerdote e escriba que estudava os mandamentos e decretos do SENHOR e os ensinava a Israel:

[[v15-7-12]]

^<<v15-7-12,12>>^ "De Artaxerxes, rei dos reis, ao sacerdote Esdras, mestre da lei do Deus dos céus. Saudações.

[[v15-7-13]]

^<<v15-7-13,13>>^ "Eu decreto que qualquer israelita em meu reino, incluindo os sacerdotes e os levitas, que desejar regressar com você para Jerusalém, poderá ir.

[[v15-7-14]]

^<<v15-7-14,14>>^ Eu e meus sete conselheiros o instruímos a investigar a situação em Judá e em Jerusalém, com base na lei de seu Deus, que está em suas mãos.

[[v15-7-15]]

^<<v15-7-15,15>>^ Também o encarregamos de levar consigo a prata e o ouro que lhe entregamos voluntariamente como oferta para o Deus de Israel, que habita em Jerusalém.

[[v15-7-16]]

^<<v15-7-16,16>>^ "Além disso, você levará toda prata e todo ouro que obtiver na província da Babilônia, bem como as ofertas voluntárias do povo e dos sacerdotes para o templo de seu Deus, em Jerusalém.

[[v15-7-17]]

^<<v15-7-17,17>>^ Use esses recursos para comprar novilhos, carneiros, cordeiros e as respectivas ofertas de cereal e ofertas derramadas. Tudo isso será oferecido no altar do templo de seu Deus, em Jerusalém.

[[v15-7-18]]

^<<v15-7-18,18>>^ A prata e o ouro que restarem poderão ser usados como parecer melhor a você e a seu povo, conforme a vontade de Deus.

[[v15-7-19]]

^<<v15-7-19,19>>^ "Quanto aos utensílios que lhe confiamos para o serviço no templo de seu Deus, entregue-os todos diante do Deus de Jerusalém.

[[v15-7-20]]

^<<v15-7-20,20>>^ Se precisar de mais alguma coisa para o templo de seu Deus, ou para qualquer necessidade semelhante, use recursos da tesouraria real.

[[v15-7-21]]

^<<v15-7-21,21>>^ "Eu, o rei Artaxerxes, envio o seguinte decreto a todos os tesoureiros da província a oeste do rio Eufrates: ‘Deem a Esdras, sacerdote e mestre da lei do Deus dos céus, tudo que ele requisitar.

[[v15-7-22]]

^<<v15-7-22,22>>^ Deem-lhe até 3.500 quilos de prata, 100 cestos grandes de trigo, 100 tonéis de vinho, 100 tonéis de azeite e sal à vontade.

[[v15-7-23]]

^<<v15-7-23,23>>^ Tenham o cuidado de providenciar tudo que o Deus dos céus ordenar para seu templo; afinal, por que provocar a ira de Deus contra este império do rei e de seus filhos?

[[v15-7-24]]

^<<v15-7-24,24>>^ Também decreto que nenhum sacerdote, levita, cantor, guarda das portas, servidor do templo, nem qualquer outro trabalhador no templo será obrigado a pagar tributos, impostos e taxas de qualquer tipo’.

[[v15-7-25]]

^<<v15-7-25,25>>^ "E você, Esdras, use a sabedoria que seu Deus lhe deu para nomear magistrados e juízes que conheçam as leis de seu Deus para governarem todo o povo na província a oeste do rio Eufrates. Ensine a lei a todos que não a conhecem.

[[v15-7-26]]

^<<v15-7-26,26>>^ Qualquer um que se recusar a obedecer à lei de seu Deus e do rei será castigado de imediato com a morte, com o exílio, com o confisco dos bens ou com a prisão".

[[v15-7-27]]

^<<v15-7-27,27>>^ Louvem o SENHOR, o Deus de nossos antepassados, que colocou no coração do rei o desejo de embelezar o templo do SENHOR, em Jerusalém,

[[v15-7-28]]

^<<v15-7-28,28>>^ e que me mostrou seu amor leal ao honrar-me diante do rei, de seu conselho e de todos os seus oficiais poderosos! Senti-me encorajado porque a mão do SENHOR, meu Deus, estava sobre mim e reuni alguns dos líderes de Israel para voltar comigo a Jerusalém.

'''

xref:015-esdras/015-esdras-006.adoc#v15-6-0[&#60; Capítulo Anterior] | <<v15-7-0,Topo>> | xref:015-esdras/015-esdras-008.adoc#v15-8-0[Próximo Capítulo &#62;]