include::./index.adoc[]

[[v15-8-0]]
=== Esdras, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v15-8-1]]

^<<v15-8-1,1>>^ Esta é uma lista dos chefes de família, com suas genealogias, aqueles que regressaram comigo da Babilônia durante o reinado do rei Artaxerxes:

[[v15-8-2]]

^<<v15-8-2,2>>^ da família de Fineias: Gérson; da família de Itamar: Daniel; da família de Davi: Hatus,

[[v15-8-3]]

^<<v15-8-3,3>>^ descendente de Secanias; da família de Parós: Zacarias e 150 homens registrados com ele;

[[v15-8-4]]

^<<v15-8-4,4>>^ da família de Paate-Moabe: Elioenai, filho de Zeraías, e 200 homens registrados com ele;

[[v15-8-5]]

^<<v15-8-5,5>>^ da família de Zatu: Secanias, filho de Jaaziel, e 300 homens registrados com ele;

[[v15-8-6]]

^<<v15-8-6,6>>^ da família de Adim: Ebede, filho de Jônatas, e 50 homens registrados com ele;

[[v15-8-7]]

^<<v15-8-7,7>>^ da família de Elão: Jesaías, filho de Atalias, e 70 homens registrados com ele;

[[v15-8-8]]

^<<v15-8-8,8>>^ da família de Sefatias: Zebadias, filho de Micael, e 80 homens registrados com ele;

[[v15-8-9]]

^<<v15-8-9,9>>^ da família de Joabe: Obadias, filho de Jeiel, e 218 homens registrados com ele;

[[v15-8-10]]

^<<v15-8-10,10>>^ da família de Bani: Selomite, filho de Josifias, e 160 homens registrados com ele;

[[v15-8-11]]

^<<v15-8-11,11>>^ da família de Bebai: Zacarias, filho de Bebai, e 28 homens registrados com ele;

[[v15-8-12]]

^<<v15-8-12,12>>^ da família de Azgade: Joanã, filho de Hacatã, e 110 homens registrados com ele;

[[v15-8-13]]

^<<v15-8-13,13>>^ da família de Adonicam, que chegaram depois: Elifelete, Jeiel e Semaías, e 60 homens registrados com eles;

[[v15-8-14]]

^<<v15-8-14,14>>^ da família de Bigvai: Utai e Zacur, e 70 homens registrados com eles.

[[v15-8-15]]

^<<v15-8-15,15>>^ Reuni os exilados perto do canal de Aava, e acampamos ali por três dias enquanto eu revisava as listas do povo e dos sacerdotes que haviam chegado. Descobri que nenhum levita se havia oferecido para nos acompanhar.

[[v15-8-16]]

^<<v15-8-16,16>>^ Por isso, mandei chamar Eliézer, Ariel, Semaías, Elnatã, Jaribe, Elnatã, Natã, Zacarias e Mesulão, líderes do povo. Também mandei chamar Joiaribe e Elnatã, dois homens com discernimento.

[[v15-8-17]]

^<<v15-8-17,17>>^ Enviei-os a Ido, chefe dos levitas em Casifia, para que pedissem a ele, a seus parentes e aos servidores do templo que nos enviassem ministros para o templo de Deus, em Jerusalém.

[[v15-8-18]]

^<<v15-8-18,18>>^ Visto que a bondosa mão de nosso Deus estava sobre nós, eles nos enviaram Serebias, junto com 18 de seus filhos e parentes. Era um homem inteligente, descendente de Mali, descendente de Levi, filho de Israel.

[[v15-8-19]]

^<<v15-8-19,19>>^ Também nos enviaram Hasabias, junto com Jesaías, dos descendentes de Merari, 20 de seus filhos e parentes,

[[v15-8-20]]

^<<v15-8-20,20>>^ e 220 servidores do templo. Os servidores do templo eram assistentes dos levitas, um grupo de trabalhadores do templo instituído pelo rei Davi e por seus oficiais. Todos estavam registrados por nome.

[[v15-8-21]]

^<<v15-8-21,21>>^ Ali, junto ao canal de Aava, ordenei que todos nós jejuássemos e nos humilhássemos diante de nosso Deus. Oramos para que ele nos proporcionasse uma viagem segura e nos protegesse, como também a nossos filhos e a nossos bens.

[[v15-8-22]]

^<<v15-8-22,22>>^ Pois tive vergonha de pedir ao rei soldados e cavaleiros para nos acompanhar e nos proteger de inimigos ao longo do caminho. Afinal, tínhamos dito ao rei: "A bondosa mão de nosso Deus está sobre todos que o adoram, mas seu poder e sua ira estão contra todos que o abandonam".

[[v15-8-23]]

^<<v15-8-23,23>>^ Assim, jejuamos e pedimos com fervor que nosso Deus cuidasse de nós, e ele atendeu à nossa oração.

[[v15-8-24]]

^<<v15-8-24,24>>^ Nomeei doze chefes dos sacerdotes — Serebias, Hasabias e outros dez sacerdotes —

[[v15-8-25]]

^<<v15-8-25,25>>^ para ficarem encarregados do transporte da prata, do ouro e dos outros objetos que o rei, seu conselho, seus oficiais e todo o povo de Israel haviam doado para o templo de Deus.

[[v15-8-26]]

^<<v15-8-26,26>>^ Pesei o tesouro ao entregá-lo, e seu total era: 22.750 quilos de prata, 3.500 quilos de utensílios de prata, 3.500 quilos de ouro,

[[v15-8-27]]

^<<v15-8-27,27>>^ 20 tigelas de ouro, cada uma pesando 8,6 quilos; 2 utensílios finos de bronze polido, tão valiosos como ouro.

[[v15-8-28]]

^<<v15-8-28,28>>^ Eu disse aos sacerdotes: "Vocês e esses tesouros foram consagrados ao SENHOR. A prata e o ouro são ofertas voluntárias ao SENHOR, o Deus de nossos antepassados.

[[v15-8-29]]

^<<v15-8-29,29>>^ Guardem bem esses tesouros até que os apresentem aos líderes dos sacerdotes, aos levitas e aos chefes de família de Israel, que os pesarão nos depósitos do templo do SENHOR, em Jerusalém".

[[v15-8-30]]

^<<v15-8-30,30>>^ Os sacerdotes e os levitas aceitaram a responsabilidade de transportar esses tesouros de prata e de ouro até o templo de nosso Deus, em Jerusalém.

[[v15-8-31]]

^<<v15-8-31,31>>^ Levantamos acampamento junto ao canal de Aava, no dia 19 de abril, e partimos para Jerusalém. E a mão de nosso Deus nos protegeu e nos guardou de inimigos e bandidos ao longo do caminho.

[[v15-8-32]]

^<<v15-8-32,32>>^ Assim, chegamos em segurança a Jerusalém, onde descansamos por três dias.

[[v15-8-33]]

^<<v15-8-33,33>>^ No quarto dia depois de nossa chegada, a prata, o ouro e os utensílios valiosos foram pesados no templo de nosso Deus e entregues a Meremote, filho do sacerdote Urias. Estavam com ele Eleazar, filho de Fineias, e os levitas Jozabade, filho de Jesua, e Noadias, filho de Binui.

[[v15-8-34]]

^<<v15-8-34,34>>^ Pesaram e contaram tudo, e o peso total foi registrado oficialmente.

[[v15-8-35]]

^<<v15-8-35,35>>^ Os exilados que haviam regressado do cativeiro ofereceram holocaustos ao Deus de Israel. Apresentaram 12 touros por todo o povo de Israel, 96 carneiros e 77 cordeiros. Também apresentaram 12 bodes como oferta pelo pecado. Tudo isso foi oferecido como holocausto ao SENHOR.

[[v15-8-36]]

^<<v15-8-36,36>>^ Os decretos do rei foram entregues aos oficiais que ocupavam os cargos mais elevados e aos governadores da província a oeste do rio Eufrates, que passaram a apoiar o povo e o templo de Deus.

'''

xref:015-esdras/015-esdras-007.adoc#v15-7-0[&#60; Capítulo Anterior] | <<v15-8-0,Topo>> | xref:015-esdras/015-esdras-009.adoc#v15-9-0[Próximo Capítulo &#62;]