include::./index.adoc[]

[[v15-4-0]]
=== Esdras, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v15-4-1]]

^<<v15-4-1,1>>^ Os inimigos de Judá e Benjamim souberam que os exilados estavam reconstruindo o templo do SENHOR, o Deus de Israel.

[[v15-4-2]]

^<<v15-4-2,2>>^ Eles foram a Zorobabel e aos outros chefes de família e disseram: "Queremos participar da construção, pois também adoramos seu Deus, como vocês. Temos oferecido sacrifícios para ele desde que Esar-Hadom, rei da Assíria, nos trouxe para cá".

[[v15-4-3]]

^<<v15-4-3,3>>^ Mas Zorobabel, Jesua e os outros chefes de família de Israel responderam: "De maneira nenhuma! Vocês não podem participar desse trabalho. Somente nós construiremos o templo para o SENHOR, o Deus de Israel, conforme Ciro, rei da Pérsia, nos ordenou".

[[v15-4-4]]

^<<v15-4-4,4>>^ Então os habitantes da região tentaram desanimar e amedrontar o povo de Judá, para que não continuassem a construção.

[[v15-4-5]]

^<<v15-4-5,5>>^ Subornaram agentes para trabalhar contra eles e frustrar seus planos. Isso prosseguiu durante todo o reinado de Ciro, rei da Pérsia, até que Dario, rei da Pérsia, subiu ao poder.

[[v15-4-6]]

^<<v15-4-6,6>>^ Anos depois, quando Xerxes começou a reinar, os inimigos de Judá escreveram uma carta de acusação contra o povo de Judá e de Jerusalém.

[[v15-4-7]]

^<<v15-4-7,7>>^ Mais tarde, durante o reinado de Artaxerxes, rei da Pérsia, os inimigos de Judá, liderados por Bislão, Mitredate e Tabeel, enviaram a Artaxerxes uma carta em aramaico, que foi traduzida para o rei.

[[v15-4-8]]

^<<v15-4-8,8>>^ O comandante Reum e o secretário da corte Sinsai escreveram a carta, na qual apresentaram ao rei Artaxerxes um relatório negativo sobre Jerusalém.

[[v15-4-9]]

^<<v15-4-9,9>>^ Saudaram o rei em nome de todos os seus colegas: os juízes e as autoridades locais, o povo de Tarpel, os persas, os babilônios e o povo de Ereque e de Susã (isto é, Elão).

[[v15-4-10]]

^<<v15-4-10,10>>^ Também enviaram saudações do restante do povo que o grande e renomado Assurbanípal havia deportado e estabelecido em Samaria e em todas as terras vizinhas da província a oeste do rio Eufrates.

[[v15-4-11]]

^<<v15-4-11,11>>^ Esta é uma cópia da carta: "Ao rei Artaxerxes, de seus súditos leais na província a oeste do rio Eufrates.

[[v15-4-12]]

^<<v15-4-12,12>>^ "Informamos ao rei que os judeus que saíram da Babilônia para Jerusalém estão reconstruindo esta cidade rebelde e má. Já restauraram os alicerces e, em breve, terminarão os muros.

[[v15-4-13]]

^<<v15-4-13,13>>^ É bom o rei saber que, se esta cidade for reconstruída e seus muros forem concluídos, haverá grande prejuízo para o tesouro real, pois os judeus se recusarão a lhe pagar tributos, impostos e taxas.

[[v15-4-14]]

^<<v15-4-14,14>>^ "Visto que somos seus súditos leais e não desejamos vê-lo desonrado desse modo, enviamos ao rei estas informações.

[[v15-4-15]]

^<<v15-4-15,15>>^ Sugerimos que se faça uma busca no registro de seus antepassados, no qual o rei descobrirá como esta cidade foi rebelde em outros tempos. Aliás, foi destruída por causa de sua longa e problemática história de rebelião contra os reis e as nações que a dominavam.

[[v15-4-16]]

^<<v15-4-16,16>>^ Declaramos ao rei que, se esta cidade for reconstruída e seus muros forem concluídos, o rei perderá a província a oeste do rio Eufrates".

[[v15-4-17]]

^<<v15-4-17,17>>^ O rei Artaxerxes enviou a seguinte resposta: "Ao comandante Reum, ao secretário da corte Sinsai, e a seus companheiros em Samaria e em toda a província a oeste do rio Eufrates. Saudações.

[[v15-4-18]]

^<<v15-4-18,18>>^ "A carta que vocês enviaram foi traduzida e lida para mim.

[[v15-4-19]]

^<<v15-4-19,19>>^ Ordenei que se fizesse uma busca nos registros e descobri que, de fato, Jerusalém tem sido, ao longo dos anos, foco de insurreição contra vários reis. Aliás, rebeliões e revoltas são normais ali.

[[v15-4-20]]

^<<v15-4-20,20>>^ Reis poderosos governaram sobre Jerusalém e sobre toda a província a oeste do rio Eufrates e receberam tributos, impostos e taxas.

[[v15-4-21]]

^<<v15-4-21,21>>^ Portanto, deem ordens para que esses homens parem seu trabalho. A cidade não deve ser reconstruída enquanto eu não mandar.

[[v15-4-22]]

^<<v15-4-22,22>>^ Sejam diligentes e não descuidem desse assunto, pois não devemos permitir que a situação prejudique os interesses do rei".

[[v15-4-23]]

^<<v15-4-23,23>>^ Quando a carta do rei Artaxerxes foi lida para Reum, Sinsai e seus companheiros, eles foram depressa a Jerusalém e, fazendo uso de força, obrigaram os judeus a parar a construção.

[[v15-4-24]]

^<<v15-4-24,24>>^ Assim, a obra no templo de Deus em Jerusalém foi interrompida e ficou parada até o segundo ano do reinado de Dario, rei da Pérsia.

'''

xref:015-esdras/015-esdras-003.adoc#v15-3-0[&#60; Capítulo Anterior] | <<v15-4-0,Topo>> | xref:015-esdras/015-esdras-005.adoc#v15-5-0[Próximo Capítulo &#62;]