include::./index.adoc[]

[[v57-1-0]]
=== Filemom, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v57-1-1]]

^<<v57-1-1,1>>^ Eu, Paulo, prisioneiro de Cristo Jesus, escrevo esta carta, junto com nosso irmão Timóteo, a Filemom, nosso amado colaborador,

[[v57-1-2]]

^<<v57-1-2,2>>^ à irmã Áfia, a Arquipo, nosso companheiro na luta, e à igreja que se reúne em sua casa.

[[v57-1-3]]

^<<v57-1-3,3>>^ Que Deus, nosso Pai, e o Senhor Jesus Cristo lhes deem graça e paz.

[[v57-1-4]]

^<<v57-1-4,4>>^ Sempre dou graças a meu Deus por você em minhas orações,

[[v57-1-5]]

^<<v57-1-5,5>>^ pois ouço com frequência de sua fé no Senhor Jesus e de seu amor por todo o povo santo.

[[v57-1-6]]

^<<v57-1-6,6>>^ Oro para que você ponha em prática a comunhão que vem da fé, à medida que entender e experimentar todas as coisas boas que temos em Cristo.

[[v57-1-7]]

^<<v57-1-7,7>>^ Seu amor, meu irmão, tem me dado muita alegria e conforto, pois sua bondade tem revigorado o coração do povo santo.

[[v57-1-8]]

^<<v57-1-8,8>>^ Por isso, ainda que pudesse exigir em Cristo que você faça o que é certo,

[[v57-1-9]]

^<<v57-1-9,9>>^ prefiro pedir com base no amor — eu, Paulo, já velho e agora prisioneiro de Cristo Jesus.

[[v57-1-10]]

^<<v57-1-10,10>>^ Suplico que demonstre bondade a meu filho Onésimo. Tornei-me pai dele na fé quando estava aqui na prisão.

[[v57-1-11]]

^<<v57-1-11,11>>^ Onésimo não lhe foi de muita utilidade no passado, mas agora é muito útil para nós dois.

[[v57-1-12]]

^<<v57-1-12,12>>^ Eu o envio de volta a você, e com ele vai meu próprio coração.

[[v57-1-13]]

^<<v57-1-13,13>>^ Gostaria de mantê-lo aqui comigo enquanto estou preso por anunciar as boas-novas; assim ele me ajudaria em seu lugar.

[[v57-1-14]]

^<<v57-1-14,14>>^ Mas eu nada quis fazer sem seu consentimento. Meu desejo era que você ajudasse de boa vontade, e não por obrigação.

[[v57-1-15]]

^<<v57-1-15,15>>^ Ao que parece, você perdeu Onésimo por algum tempo para ganhá-lo de volta para sempre.

[[v57-1-16]]

^<<v57-1-16,16>>^ Ele já não é um escravo para você. É mais que um escravo: é um irmão amado, especialmente para mim. Agora ele será muito mais importante para você, como pessoa e como irmão no Senhor.

[[v57-1-17]]

^<<v57-1-17,17>>^ Portanto, se me considera seu companheiro na fé, receba-o como receberia a mim.

[[v57-1-18]]

^<<v57-1-18,18>>^ Se ele o prejudicou de alguma forma ou se lhe deve algo, cobre de mim.

[[v57-1-19]]

^<<v57-1-19,19>>^ Eu, Paulo, escrevo de próprio punho: Eu pagarei. E não mencionarei que você me deve sua própria vida.

[[v57-1-20]]

^<<v57-1-20,20>>^ Sim, meu irmão, faça-me essa gentileza no Senhor. Reanime meu coração em Cristo!

[[v57-1-21]]

^<<v57-1-21,21>>^ Escrevo esta carta certo de que você fará o que lhe peço, e até mais.

[[v57-1-22]]

^<<v57-1-22,22>>^ Por favor, prepare um quarto para mim, pois espero que minhas orações sejam respondidas e eu possa voltar a visitá-lo em breve.

[[v57-1-23]]

^<<v57-1-23,23>>^ Epafras, meu companheiro de prisão em Cristo Jesus, manda lembranças.

[[v57-1-24]]

^<<v57-1-24,24>>^ Marcos, Aristarco, Demas e Lucas, meus colaboradores, também enviam saudações.

[[v57-1-25]]

^<<v57-1-25,25>>^ Que a graça de nosso Senhor Jesus Cristo esteja com o espírito de vocês.

'''

xref:056-tito/056-tito-003.adoc#v56-3-0[&#60; Capítulo Anterior] | <<v57-1-0,Topo>> | xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[Próximo Capítulo &#62;]