include::./index.adoc[]

[[v39-2-0]]
=== Malaquias, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v39-2-1]]

^<<v39-2-1,1>>^ "Ouçam, sacerdotes! Este mandamento é para vocês.

[[v39-2-2]]

^<<v39-2-2,2>>^ Escutem-me e decidam honrar meu nome", diz o SENHOR dos Exércitos, "pois, do contrário, enviarei maldição sobre vocês. Amaldiçoarei até mesmo as bênçãos que receberem. Na verdade, já as amaldiçoei, pois vocês não levaram a sério minha advertência.

[[v39-2-3]]

^<<v39-2-3,3>>^ Castigarei seus descendentes, esfregarei em seu rosto o esterco dos sacrifícios que vocês ofereceram em suas festas sagradas e os lançarei no monte de esterco.

[[v39-2-4]]

^<<v39-2-4,4>>^ Assim, vocês saberão que enviei este mandamento para que minha aliança com os levitas continue", diz o SENHOR dos Exércitos.

[[v39-2-5]]

^<<v39-2-5,5>>^ "O propósito de minha aliança com os levitas era dar vida e paz, e foi o que lhes dei. Para isso, era necessário que me temessem, e eles demonstraram grande temor por mim e reverência por meu nome.

[[v39-2-6]]

^<<v39-2-6,6>>^ Transmitiram ao povo a verdade das leis que receberam de mim. Não mentiram nem enganaram; andaram comigo, vivendo de modo pacífico e justo, e desviaram muitos do pecado.

[[v39-2-7]]

^<<v39-2-7,7>>^ "As palavras do sacerdote devem guardar o conhecimento de Deus, e o povo deve buscar o sacerdote para receber instrução, pois ele é mensageiro do SENHOR dos Exércitos.

[[v39-2-8]]

^<<v39-2-8,8>>^ Mas vocês, sacerdotes, se desviaram dos caminhos de Deus. Suas instruções fizeram muitos caírem em pecado. Vocês quebraram a aliança que fiz com os levitas", diz o SENHOR dos Exércitos.

[[v39-2-9]]

^<<v39-2-9,9>>^ "Por isso fiz que vocês fossem desprezados e humilhados diante de todo o povo, pois não me obedeceram, mas mostraram parcialidade na aplicação de minha lei."

[[v39-2-10]]

^<<v39-2-10,10>>^ Não somos filhos do mesmo Pai? Não fomos todos criados pelo mesmo Deus? Então por que traímos uns aos outros e quebramos a aliança de nossos antepassados?

[[v39-2-11]]

^<<v39-2-11,11>>^ Judá foi infiel, e uma coisa detestável foi feita em Israel e em Jerusalém. Os homens de Judá contaminaram o santuário que o SENHOR ama ao se casarem com mulheres que adoram deuses estrangeiros.

[[v39-2-12]]

^<<v39-2-12,12>>^ Que o SENHOR elimine das casas de Israel até o último homem que fez isso e que, ainda assim, apresenta uma oferta ao SENHOR dos Exércitos.

[[v39-2-13]]

^<<v39-2-13,13>>^ Há outra coisa que vocês fazem. Cobrem de lágrimas o altar do SENHOR, choram e gemem porque ele não dá atenção às suas ofertas nem as aceita com prazer.

[[v39-2-14]]

^<<v39-2-14,14>>^ E ainda perguntam: "Por quê?". Porque o SENHOR foi testemunha dos votos que você e sua esposa fizeram quando jovens. Mas você foi infiel, embora ela tenha continuado a ser sua companheira, a esposa à qual você fez seus votos de casamento.

[[v39-2-15]]

^<<v39-2-15,15>>^ Acaso o SENHOR não o fez um só com sua esposa? Em corpo e em espírito vocês pertencem a ele. E o que ele quer? Dessa união, quer filhos dedicados a ele. Portanto, guardem seu coração; permaneçam fiéis à esposa de sua mocidade.

[[v39-2-16]]

^<<v39-2-16,16>>^ "Pois eu odeio o divórcio", diz o SENHOR, o Deus de Israel. "Divorciar-se de sua esposa é cobri-la de crueldade", diz o SENHOR dos Exércitos. "Portanto, guardem seu coração; não sejam infiéis."

[[v39-2-17]]

^<<v39-2-17,17>>^ Vocês cansaram o SENHOR com suas palavras. "De que maneira o cansamos?", vocês perguntam. Vocês o cansaram dizendo que todos que praticam o mal são bons aos olhos do SENHOR e que ele se agrada deles, e também ao perguntar: "Onde está o Deus da justiça?".

'''

xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[&#60; Capítulo Anterior] | <<v39-2-0,Topo>> | xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[Próximo Capítulo &#62;]