include::./index.adoc[]

[[v39-1-0]]
=== Malaquias, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v39-1-1]]

^<<v39-1-1,1>>^ Esta é a mensagem que o SENHOR anunciou a Israel por meio do profeta Malaquias.

[[v39-1-2]]

^<<v39-1-2,2>>^ "Eu sempre amei vocês", diz o SENHOR. Mas vocês perguntam: "De que maneira nos amou?". E o SENHOR responde: "Foi desta maneira: amei seu antepassado Jacó,

[[v39-1-3]]

^<<v39-1-3,3>>^ mas rejeitei o irmão dele, Esaú, e devastei sua região montanhosa. Transformei a propriedade de Esaú num deserto para chacais".

[[v39-1-4]]

^<<v39-1-4,4>>^ O povo de Edom talvez diga: "Fomos arrasados, mas reconstruiremos as ruínas". O SENHOR dos Exércitos, porém, declara: "Podem reconstruir, mas eu demolirei tudo outra vez. Seu país ficará conhecido como ‘Terra da Maldade’, e seu povo será chamado de ‘Povo Contra o Qual o SENHOR Está Irado Para Sempre’.

[[v39-1-5]]

^<<v39-1-5,5>>^ Quando vocês virem a destruição com os próprios olhos, dirão: ‘A grandeza do SENHOR vai muito além das fronteiras de Israel!’".

[[v39-1-6]]

^<<v39-1-6,6>>^ O SENHOR dos Exércitos diz aos sacerdotes: "O filho honra seu pai, e o servo respeita seu senhor. Se eu sou seu pai e seu senhor, onde estão a honra e o respeito que mereço? Vocês desprezam meu nome! "Mas vocês perguntam: ‘De que maneira desprezamos teu nome?’.

[[v39-1-7]]

^<<v39-1-7,7>>^ "Vocês o desprezam oferecendo sacrifícios contaminados sobre meu altar. "E vocês perguntam: ‘De que maneira contaminamos os sacrifícios?’. "Vocês os contaminam dizendo que a mesa do SENHOR não merece respeito.

[[v39-1-8]]

^<<v39-1-8,8>>^ Acaso não é errado sacrificarem animais cegos? Não é errado oferecerem animais aleijados e doentes? Apresentem ofertas como essas a seu governador e vejam se ele ficará satisfeito e se agradará de vocês!", diz o SENHOR dos Exércitos.

[[v39-1-9]]

^<<v39-1-9,9>>^ "Vão em frente, supliquem a Deus para que tenha compaixão de vocês. Mas por que ele atenderia, uma vez que apresentam esse tipo de oferta?", diz o SENHOR dos Exércitos.

[[v39-1-10]]

^<<v39-1-10,10>>^ "Quem dera um de vocês fechasse as portas do templo para que não se acendesse em vão o fogo do meu altar! Não me agrado de vocês", diz o SENHOR dos Exércitos, "e não aceitarei suas ofertas.

[[v39-1-11]]

^<<v39-1-11,11>>^ Contudo, meu nome é honrado de manhã até a noite por pessoas de outras nações. Em todo o mundo oferecem incenso e sacrifícios puros em minha honra, pois meu nome é grande entre as nações", diz o SENHOR dos Exércitos.

[[v39-1-12]]

^<<v39-1-12,12>>^ "Mas vocês, com suas ações, desonram meu nome. Ao trazer alimentos desprezíveis, declaram que não há nada de errado em contaminar a mesa do Senhor.

[[v39-1-13]]

^<<v39-1-13,13>>^ Dizem: ‘É difícil demais servir ao SENHOR!’ e desprezam minhas ordens", diz o SENHOR dos Exércitos. "Vocês trazem como ofertas animais roubados, aleijados e doentes! Acaso devo aceitar de suas mãos esse tipo de oferta?", diz o SENHOR.

[[v39-1-14]]

^<<v39-1-14,14>>^ "Maldito seja o trapaceiro que promete um carneiro forte de seu rebanho, mas depois sacrifica ao Senhor um animal defeituoso. Pois eu sou o grande Rei", diz o SENHOR dos Exércitos, "e meu nome é temido entre as nações!"

'''

xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[&#60; Capítulo Anterior] | <<v39-1-0,Topo>> | xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[Próximo Capítulo &#62;]