include::./index.adoc[]

[[v39-3-0]]
=== Malaquias, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v39-3-1]]

^<<v39-3-1,1>>^ "Vejam! Envio meu mensageiro, que preparará o caminho diante de mim. Então, de repente, o Senhor a quem vocês buscam virá a seu templo. O mensageiro da aliança, por quem vocês anseiam, certamente virá", diz o SENHOR dos Exércitos.

[[v39-3-2]]

^<<v39-3-2,2>>^ "Mas quem poderá suportar quando ele vier? Quem permanecerá em pé em sua presença quando ele aparecer? Pois ele será como fogo ardente que refina o metal, como sabão forte que branqueia as roupas.

[[v39-3-3]]

^<<v39-3-3,3>>^ Ele se sentará como refinador de prata e queimará toda impureza. Purificará os levitas e os refinará como ouro e prata, para que voltem a oferecer sacrifícios aceitáveis ao SENHOR.

[[v39-3-4]]

^<<v39-3-4,4>>^ Então o SENHOR se agradará novamente das ofertas do povo de Judá e do povo de Jerusalém, como no passado.

[[v39-3-5]]

^<<v39-3-5,5>>^ "Naquele dia, eu julgarei vocês. Não demorarei para testemunhar contra todos os feiticeiros, adúlteros e mentirosos. Falarei contra aqueles que roubam o salário de seus empregados, que oprimem as viúvas e os órfãos, ou que privam os estrangeiros de seus direitos, pois essas pessoas não me temem", diz o SENHOR dos Exércitos.

[[v39-3-6]]

^<<v39-3-6,6>>^ "Eu sou o SENHOR e não mudo. Por isso vocês, descendentes de Jacó, ainda não foram destruídos.

[[v39-3-7]]

^<<v39-3-7,7>>^ Desde os dias de seus antepassados vocês se afastaram de meus decretos e não os seguiram. Agora, voltem-se para mim, e eu me voltarei para vocês", diz o SENHOR dos Exércitos. "Mas vocês perguntam: ‘De que maneira voltaremos?’.

[[v39-3-8]]

^<<v39-3-8,8>>^ "Acaso alguém pode roubar a Deus? Mas vocês têm me roubado! "Perguntam: ‘Em que te roubamos?’. "Vocês me roubaram nos dízimos e nas ofertas.

[[v39-3-9]]

^<<v39-3-9,9>>^ Estão sob maldição, pois a nação inteira tem me roubado.

[[v39-3-10]]

^<<v39-3-10,10>>^ Tragam todos os seus dízimos aos depósitos do templo, para que haja provisão em minha casa. Se o fizerem", diz o SENHOR dos Exércitos, "abrirei as janelas do céu para vocês. Derramarei tantas bênçãos que não haverá espaço para guardá-las! Sim, ponham-me à prova!

[[v39-3-11]]

^<<v39-3-11,11>>^ Suas colheitas serão fartas, pois as protegerei das pragas. Suas uvas não cairão das videiras antes de amadurecerem", diz o SENHOR dos Exércitos.

[[v39-3-12]]

^<<v39-3-12,12>>^ "Então todas as nações os chamarão de abençoados, pois sua terra será cheia de alegria", diz o SENHOR dos Exércitos.

[[v39-3-13]]

^<<v39-3-13,13>>^ "Vocês falaram coisas terríveis contra mim", diz o SENHOR. "Mas vocês perguntam: ‘O que falamos contra ti?’.

[[v39-3-14]]

^<<v39-3-14,14>>^ "Vocês disseram: ‘De que adianta servir a Deus? Que vantagem temos em obedecer a suas ordens ou chorar por nossos pecados diante do SENHOR dos Exércitos?

[[v39-3-15]]

^<<v39-3-15,15>>^ De agora em diante, chamaremos de abençoados os arrogantes. Pois os que praticam maldades enriquecem, e os que provocam a ira de Deus nenhum mal sofrem’."

[[v39-3-16]]

^<<v39-3-16,16>>^ Então aqueles que temiam o SENHOR falaram uns com os outros, e o SENHOR ouviu o que disseram. Na presença dele, foi escrito um livro memorial para registrar os nomes dos que o temiam e que sempre honravam seu nome.

[[v39-3-17]]

^<<v39-3-17,17>>^ "Eles serão meu povo", diz o SENHOR dos Exércitos. "No dia em que eu agir, eles serão meu tesouro especial. Terei compaixão deles como o pai tem compaixão de seu filho obediente.

[[v39-3-18]]

^<<v39-3-18,18>>^ Então vocês verão outra vez a diferença entre o justo e o mau, entre o que serve a Deus e o que não serve."

'''

xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[&#60; Capítulo Anterior] | <<v39-3-0,Topo>> | xref:039-malaquias/039-malaquias-004.adoc#v39-4-0[Próximo Capítulo &#62;]