include::./index.adoc[]

[[v39-4-0]]
=== Malaquias, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v39-4-1]]

^<<v39-4-1,1>>^ Assim diz o SENHOR dos Exércitos: "O dia do julgamento se aproxima e arde como uma fornalha. Naquele dia, serão queimados como palha os arrogantes e os perversos. Serão consumidos, desde as raízes até os ramos.

[[v39-4-2]]

^<<v39-4-2,2>>^ "Mas, para vocês que temem meu nome, o sol da justiça se levantará, trazendo cura em suas asas. E vocês sairão e saltarão de alegria, como bezerros soltos no pasto.

[[v39-4-3]]

^<<v39-4-3,3>>^ No dia em que eu agir, vocês pisarão sobre os perversos como se eles fossem pó sob os seus pés", diz o SENHOR dos Exércitos.

[[v39-4-4]]

^<<v39-4-4,4>>^ "Lembrem-se de obedecer à lei de Moisés, meu servo, a todos os decretos e estatutos que dei a todo o Israel no monte Sinai.

[[v39-4-5]]

^<<v39-4-5,5>>^ "Vejam, eu lhes envio o profeta Elias antes da vinda do grande e terrível dia do SENHOR.

[[v39-4-6]]

^<<v39-4-6,6>>^ Ele fará que o coração dos pais volte para seus filhos e o coração dos filhos volte para seus pais. Do contrário, eu virei e castigarei a terra com maldição."

'''

xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[&#60; Capítulo Anterior] | <<v39-4-0,Topo>> | xref:040-mateus/040-mateus-001.adoc#v40-1-0[Próximo Capítulo &#62;]