include::./index.adoc[]

[[v25-3-0]]
=== Lamentações, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v25-3-1]]

^<<v25-3-1,1>>^ Eu sou aquele que viu as aflições trazidas pela vara da ira do SENHOR.

[[v25-3-2]]

^<<v25-3-2,2>>^ Ele me conduziu para a escuridão e removeu toda a luz.

[[v25-3-3]]

^<<v25-3-3,3>>^ Voltou sua mão contra mim repetidamente, o dia todo.

[[v25-3-4]]

^<<v25-3-4,4>>^ Fez minha pele e minha carne envelhecerem e me quebrou os ossos.

[[v25-3-5]]

^<<v25-3-5,5>>^ Sitiou-me e cercou-me de angústia e aflição.

[[v25-3-6]]

^<<v25-3-6,6>>^ Enterrou-me num lugar escuro, como os que há muito morreram.

[[v25-3-7]]

^<<v25-3-7,7>>^ Cercou-me de muros, e não consigo escapar; prendeu-me com pesadas correntes.

[[v25-3-8]]

^<<v25-3-8,8>>^ E, ainda que eu clame e grite, ele fechou os ouvidos para minha oração.

[[v25-3-9]]

^<<v25-3-9,9>>^ Com um muro de pedra, impediu meu caminho; tornou minha estrada tortuosa.

[[v25-3-10]]

^<<v25-3-10,10>>^ Escondeu-se como um urso ou um leão que espera para atacar.

[[v25-3-11]]

^<<v25-3-11,11>>^ Arrastou-me para fora do caminho e despedaçou-me; deixou-me devastado.

[[v25-3-12]]

^<<v25-3-12,12>>^ Preparou seu arco e me fez alvo de suas flechas.

[[v25-3-13]]

^<<v25-3-13,13>>^ As flechas que ele atirou entraram fundo em meu coração.

[[v25-3-14]]

^<<v25-3-14,14>>^ Meu povo ri de mim; o dia inteiro entoam canções de zombaria.

[[v25-3-15]]

^<<v25-3-15,15>>^ De amargura ele me encheu e me fez beber um amargo cálice de dor.

[[v25-3-16]]

^<<v25-3-16,16>>^ Fez-me comer pedrinhas até quebrar os dentes e cobriu-me de pó.

[[v25-3-17]]

^<<v25-3-17,17>>^ Tirou-me a paz, e já não sei o que é prosperar.

[[v25-3-18]]

^<<v25-3-18,18>>^ Grito: "Meu esplendor se foi! Tudo que eu esperava do SENHOR se perdeu!".

[[v25-3-19]]

^<<v25-3-19,19>>^ Como é amargo recordar meu sofrimento e meu desamparo!

[[v25-3-20]]

^<<v25-3-20,20>>^ Lembro-me sempre destes dias terríveis enquanto lamento minha perda.

[[v25-3-21]]

^<<v25-3-21,21>>^ Ainda ouso, porém, ter esperança quando me recordo disto:

[[v25-3-22]]

^<<v25-3-22,22>>^ O amor do SENHOR não tem fim! Suas misericórdias são inesgotáveis.

[[v25-3-23]]

^<<v25-3-23,23>>^ Grande é sua fidelidade; suas misericórdias se renovam cada manhã.

[[v25-3-24]]

^<<v25-3-24,24>>^ Digo a mim mesmo: "O SENHOR é minha porção; por isso, esperarei nele!".

[[v25-3-25]]

^<<v25-3-25,25>>^ O SENHOR é bom para os que dependem dele, para os que o buscam.

[[v25-3-26]]

^<<v25-3-26,26>>^ Portanto, é bom esperar em silêncio pela salvação do SENHOR.

[[v25-3-27]]

^<<v25-3-27,27>>^ É bom as pessoas se sujeitarem, ainda jovens, ao jugo de sua disciplina.

[[v25-3-28]]

^<<v25-3-28,28>>^ Que permaneçam sozinhas e em silêncio sob o jugo do SENHOR.

[[v25-3-29]]

^<<v25-3-29,29>>^ Que se deitem com o rosto no pó, pois talvez ainda haja esperança.

[[v25-3-30]]

^<<v25-3-30,30>>^ Que deem a outra face para os que os ferem e aceitem os insultos de seus inimigos.

[[v25-3-31]]

^<<v25-3-31,31>>^ Pois o Senhor não abandona ninguém para sempre.

[[v25-3-32]]

^<<v25-3-32,32>>^ Embora traga tristeza, também mostra compaixão, por causa da grandeza de seu amor.

[[v25-3-33]]

^<<v25-3-33,33>>^ Pois não tem prazer em afligir as pessoas, nem em lhes causar tristeza.

[[v25-3-34]]

^<<v25-3-34,34>>^ Quando alguém esmaga sob os pés todos os prisioneiros da terra,

[[v25-3-35]]

^<<v25-3-35,35>>^ quando nega a outros seus direitos em oposição ao Altíssimo,

[[v25-3-36]]

^<<v25-3-36,36>>^ quando distorce a justiça nos tribunais, será que o Senhor não vê tudo isso?

[[v25-3-37]]

^<<v25-3-37,37>>^ Quem pode ordenar que algo aconteça sem a permissão do Senhor?

[[v25-3-38]]

^<<v25-3-38,38>>^ Acaso o Altíssimo não envia tanto a calamidade como o bem?

[[v25-3-39]]

^<<v25-3-39,39>>^ Então por que nós, humanos, nos queixamos quando somos castigados por nossos pecados?

[[v25-3-40]]

^<<v25-3-40,40>>^ Em vez disso, examinemos nossos caminhos e voltemos para o SENHOR.

[[v25-3-41]]

^<<v25-3-41,41>>^ Levantemos o coração e as mãos para Deus nos céus e digamos:

[[v25-3-42]]

^<<v25-3-42,42>>^ "Pecamos e nos rebelamos, e tu não nos perdoaste.

[[v25-3-43]]

^<<v25-3-43,43>>^ "Com tua ira nos envolveste, nos perseguiste e nos massacraste sem piedade.

[[v25-3-44]]

^<<v25-3-44,44>>^ Tu te escondeste numa nuvem, para que nossas orações não chegassem a ti.

[[v25-3-45]]

^<<v25-3-45,45>>^ Como refugo e lixo, nos lançaste fora, no meio das nações.

[[v25-3-46]]

^<<v25-3-46,46>>^ "Todos os nossos inimigos falam contra nós.

[[v25-3-47]]

^<<v25-3-47,47>>^ Vivemos cheios de medo, pois estamos presos numa armadilha, devastados e arruinados".

[[v25-3-48]]

^<<v25-3-48,48>>^ Rios de lágrimas correm de meus olhos pela destruição de meu povo.

[[v25-3-49]]

^<<v25-3-49,49>>^ Minhas lágrimas correm sem parar; não cessarão

[[v25-3-50]]

^<<v25-3-50,50>>^ até que o SENHOR se incline dos céus e veja.

[[v25-3-51]]

^<<v25-3-51,51>>^ Meu coração está aflito pelo destino das mulheres de Jerusalém.

[[v25-3-52]]

^<<v25-3-52,52>>^ Meus inimigos, a quem nunca fiz mal, caçaram-me como se eu fosse um pássaro.

[[v25-3-53]]

^<<v25-3-53,53>>^ Num poço me jogaram e atiraram pedras sobre mim.

[[v25-3-54]]

^<<v25-3-54,54>>^ A água subiu acima de minha cabeça e clamei: "É o fim!".

[[v25-3-55]]

^<<v25-3-55,55>>^ Mas, lá do fundo do poço, invoquei teu nome, SENHOR.

[[v25-3-56]]

^<<v25-3-56,56>>^ Tu me ouviste quando clamei: "Ouve minha súplica! Escuta meu clamor por socorro!".

[[v25-3-57]]

^<<v25-3-57,57>>^ Sim, tu vieste quando clamei e disseste: "Não tenha medo".

[[v25-3-58]]

^<<v25-3-58,58>>^ Senhor, defende minha causa, pois redimiste minha vida.

[[v25-3-59]]

^<<v25-3-59,59>>^ Viste a injustiça que me fizeram, SENHOR; demonstra tua justiça.

[[v25-3-60]]

^<<v25-3-60,60>>^ Viste os planos vingativos. que meus inimigos tramaram contra mim.

[[v25-3-61]]

^<<v25-3-61,61>>^ SENHOR, ouviste os insultos deles; sabes muito bem dos planos que tramaram.

[[v25-3-62]]

^<<v25-3-62,62>>^ Meus inimigos me acusam e conspiram contra mim o dia todo.

[[v25-3-63]]

^<<v25-3-63,63>>^ Olha para eles! Sentados ou em pé, zombam de mim com suas canções.

[[v25-3-64]]

^<<v25-3-64,64>>^ SENHOR, dá-lhes o que merecem por todo o mal que fizeram.

[[v25-3-65]]

^<<v25-3-65,65>>^ Dá-lhes coração duro e teimoso, e que tuas maldições caiam sobre eles.

[[v25-3-66]]

^<<v25-3-66,66>>^ Persegue-os em tua ira e destrói-os sob os céus do SENHOR.

'''

xref:025-lamentacoes/025-lamentacoes-002.adoc#v25-2-0[&#60; Capítulo Anterior] | <<v25-3-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-004.adoc#v25-4-0[Próximo Capítulo &#62;]