include::./index.adoc[]

[[v25-1-0]]
=== Lamentações, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v25-1-1]]

^<<v25-1-1,1>>^ A cidade que antes era cheia de gente agora está deserta. Antes era grande entre as nações, agora está sozinha, como uma viúva. Antes era rainha de toda a terra, agora é escrava.

[[v25-1-2]]

^<<v25-1-2,2>>^ Ela passa a noite aos prantos; lágrimas correm por seu rosto. De todos os seus amantes, não resta um sequer para consolá-la. Todos os seus amigos a traíram e se tornaram seus inimigos.

[[v25-1-3]]

^<<v25-1-3,3>>^ Judá foi levada para o exílio e oprimida com cruel escravidão. Vive entre as nações e não tem lugar para descansar. Seus inimigos a perseguiram, e ela não tem a quem recorrer.

[[v25-1-4]]

^<<v25-1-4,4>>^ As estradas para Sião estão de luto, pois as multidões já não vêm celebrar as festas. Os portões da cidade estão em silêncio, os sacerdotes gemem, as moças choram. Como é amargo seu destino!

[[v25-1-5]]

^<<v25-1-5,5>>^ Seus adversários se tornaram seus senhores, e seus inimigos prosperam, pois o SENHOR castigou Jerusalém por seus muitos pecados. Seus filhos foram capturados e levados para o exílio.

[[v25-1-6]]

^<<v25-1-6,6>>^ A bela Sião foi despojada de toda a sua majestade. Seus príncipes são como cervos famintos em busca de pasto. Estão fracos demais para fugir do inimigo que os persegue.

[[v25-1-7]]

^<<v25-1-7,7>>^ Em meio à sua tristeza e às suas andanças, Jerusalém se lembra de seu antigo esplendor. Agora, porém, caiu nas mãos de seu inimigo, e não há quem a ajude. Seu inimigo a derrubou e zombou de sua queda.

[[v25-1-8]]

^<<v25-1-8,8>>^ Jerusalém pecou terrivelmente, por isso foi jogada fora como trapo imundo. Todos que antes a honravam agora a desprezam, pois a viram nua e humilhada. Só resta a ela gemer e esconder o rosto.

[[v25-1-9]]

^<<v25-1-9,9>>^ Com sua impureza, contaminou as vestes e não pensou nas consequências. Agora está caída no chão, e não há quem a levante. " SENHOR, vê minha aflição", ela diz. "O inimigo triunfou."

[[v25-1-10]]

^<<v25-1-10,10>>^ O inimigo a saqueou e levou todos os seus valiosos bens. Ela viu estrangeiros profanarem seu templo sagrado, o lugar em que o SENHOR os proibira de entrar.

[[v25-1-11]]

^<<v25-1-11,11>>^ Seu povo geme, à procura de pão; trocaram seus tesouros por alimento para sobreviver. "Olha, SENHOR", ela se lamenta, "e vê como sou desprezada!

[[v25-1-12]]

^<<v25-1-12,12>>^ "Isso tudo nada significa para vocês que passam por mim? Olhem ao redor e vejam se há dor igual à minha, que o SENHOR trouxe sobre mim quando se acendeu sua ira.

[[v25-1-13]]

^<<v25-1-13,13>>^ "Do céu enviou fogo que me queima os ossos; pôs uma armadilha em meu caminho e me fez voltar atrás. Deixou-me devastada, atormentada o dia todo por uma doença.

[[v25-1-14]]

^<<v25-1-14,14>>^ "Trançou meus pecados como uma corda para me prender ao jugo do exílio. O Senhor me tirou a força e me entregou a meus inimigos; estou indefesa nas mãos deles.

[[v25-1-15]]

^<<v25-1-15,15>>^ "O Senhor tratou meus homens valentes com desprezo. Por ordem sua, um grande exército veio para esmagar meus jovens guerreiros. O Senhor pisou a amada cidade de Jerusalém como se pisam uvas no tanque de prensar.

[[v25-1-16]]

^<<v25-1-16,16>>^ "Choro por todas essas coisas, lágrimas correm por meu rosto. Não resta ninguém para me consolar, estão longe os que poderiam me animar. Meus filhos não têm futuro, pois o inimigo nos conquistou."

[[v25-1-17]]

^<<v25-1-17,17>>^ Sião estende as mãos, mas ninguém a consola. O SENHOR disse a respeito de seu povo, Israel: "Que seus vizinhos sejam seus inimigos! Que Jerusalém seja jogada fora como trapo imundo!".

[[v25-1-18]]

^<<v25-1-18,18>>^ "O SENHOR é justo", diz Jerusalém, "pois me rebelei contra ele. Ouçam todos os povos e vejam minha angústia, pois meus filhos e filhas foram levados para o exílio.

[[v25-1-19]]

^<<v25-1-19,19>>^ "Pedi ajuda a meus aliados, mas eles me traíram. Meus sacerdotes e meus líderes morreram de fome na cidade, enquanto procuravam alimento para sobreviver.

[[v25-1-20]]

^<<v25-1-20,20>>^ " SENHOR, vê minha angústia! Meu coração está aflito, e minha alma, desesperada, pois me rebelei terrivelmente contra ti. Nas ruas, a espada mata, e, em casa, só há morte.

[[v25-1-21]]

^<<v25-1-21,21>>^ "Outros ouviram meus gemidos, mas ninguém veio me consolar. Quando meus inimigos souberam de minha desgraça, se alegraram de ver o que tu havias feito. Ah, traze o dia que prometeste, em que eles sofrerão como eu sofri!

[[v25-1-22]]

^<<v25-1-22,22>>^ "Vê todas as maldades deles, SENHOR, e castiga-os como me castigaste, por todos os meus pecados. Meus gemidos são muitos, e meu coração está enfermo."

'''

xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[&#60; Capítulo Anterior] | <<v25-1-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-002.adoc#v25-2-0[Próximo Capítulo &#62;]