include::./index.adoc[]

[[v5-10-0]]
=== Deuteronômio, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v5-10-1]]

^<<v5-10-1,1>>^ "Naquela ocasião, o SENHOR me disse: ‘Corte duas tábuas de pedra, como as anteriores. Faça também uma arca de madeira e suba ao monte para encontrar-se comigo,

[[v5-10-2]]

^<<v5-10-2,2>>^ e eu escreverei nas tábuas as mesmas palavras que estavam nas anteriores, aquelas que você despedaçou. Em seguida, coloque as tábuas na arca’.

[[v5-10-3]]

^<<v5-10-3,3>>^ "Fiz, portanto, a arca de madeira de acácia e cortei duas tábuas de pedra, como as anteriores. Subi ao monte levando as tábuas na mão.

[[v5-10-4]]

^<<v5-10-4,4>>^ Mais uma vez, o SENHOR escreveu os dez mandamentos nas tábuas e as entregou a mim. Eram as mesmas palavras que o SENHOR lhes tinha proclamado do meio do fogo no dia em que vocês se reuniram ao pé do monte.

[[v5-10-5]]

^<<v5-10-5,5>>^ Então virei-me, desci o monte e coloquei as tábuas na arca da aliança que eu tinha feito. As tábuas ainda estão dentro da arca, conforme o SENHOR me ordenou.

[[v5-10-6]]

^<<v5-10-6,6>>^ (Os israelitas saíram dos poços do povo de Jacã e viajaram para Moserá, onde Arão morreu e foi sepultado. Eleazar, seu filho, serviu como sacerdote em seu lugar.

[[v5-10-7]]

^<<v5-10-7,7>>^ Em seguida, viajaram para Gudgodá e, de lá, para Jotbatá, terra com muitos ribeiros.

[[v5-10-8]]

^<<v5-10-8,8>>^ Naquela ocasião, o SENHOR separou a tribo de Levi para carregar a arca da aliança do SENHOR e para estar diante do SENHOR, a fim de servi-lo e de pronunciar bênçãos em seu nome. Essas são suas responsabilidades até hoje.

[[v5-10-9]]

^<<v5-10-9,9>>^ Por isso os levitas não têm porção alguma de terra como herança entre seus irmãos israelitas. O próprio SENHOR é sua herança, conforme o SENHOR, seu Deus, lhes prometeu.)

[[v5-10-10]]

^<<v5-10-10,10>>^ "Quanto a mim, fiquei no monte, na presença do SENHOR, quarenta dias e quarenta noites, como da primeira vez. E, também dessa vez, o SENHOR ouviu minhas súplicas e concordou em não destruí-los.

[[v5-10-11]]

^<<v5-10-11,11>>^ Então o SENHOR me disse: ‘Levante-se, siga viagem e guie o povo, para que entrem e tomem posse da terra que jurei dar a seus antepassados’."

[[v5-10-12]]

^<<v5-10-12,12>>^ "Agora, Israel, o que o SENHOR, seu Deus, requer de você? Somente que você tema o SENHOR, seu Deus, que viva de maneira agradável a ele e que ame e sirva ao SENHOR, seu Deus, de todo o coração e de toda a alma.

[[v5-10-13]]

^<<v5-10-13,13>>^ Obedeça sempre aos mandamentos e decretos do SENHOR que hoje lhe dou para o seu próprio bem.

[[v5-10-14]]

^<<v5-10-14,14>>^ "Veja, os mais altos céus e a terra, e tudo que nela há, pertencem ao SENHOR, seu Deus.

[[v5-10-15]]

^<<v5-10-15,15>>^ E, no entanto, o SENHOR escolheu seus antepassados para amá-los, e escolheu vocês, descendentes deles, dentre todas as nações, como hoje se vê.

[[v5-10-16]]

^<<v5-10-16,16>>^ Portanto, submetam-se a ele de coração e deixem de ser teimosos.

[[v5-10-17]]

^<<v5-10-17,17>>^ "Pois o SENHOR, seu Deus, é Deus dos deuses e Senhor dos senhores. É o grande Deus, o Deus poderoso e temível, que não mostra parcialidade e não aceita subornos.

[[v5-10-18]]

^<<v5-10-18,18>>^ Ele faz justiça aos órfãos e às viúvas. Ama os estrangeiros que vivem entre vocês e lhes dá alimento e roupas.

[[v5-10-19]]

^<<v5-10-19,19>>^ Portanto, amem também os estrangeiros, pois, em outros tempos, vocês foram estrangeiros na terra do Egito.

[[v5-10-20]]

^<<v5-10-20,20>>^ Temam o SENHOR, seu Deus, sirvam-no e apeguem-se a ele. Quando fizerem juramentos, jurem somente pelo nome dele.

[[v5-10-21]]

^<<v5-10-21,21>>^ Somente ele é seu Deus, o único digno de seu louvor, aquele que, por vocês, fez os milagres poderosos que vocês viram com os próprios olhos.

[[v5-10-22]]

^<<v5-10-22,22>>^ Quando seus antepassados desceram até o Egito, eram apenas setenta pessoas. Agora, porém, o SENHOR, seu Deus, os tornou tão numerosos quanto as estrelas do céu!"

'''

xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[&#60; Capítulo Anterior] | <<v5-10-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[Próximo Capítulo &#62;]