include::./index.adoc[]

[[v5-26-0]]
=== Deuteronômio, 26
// nvt ?, NVT - Nova Versão Transformadora

[[v5-26-1]]

^<<v5-26-1,1>>^ "Quando tiverem entrado na terra que o SENHOR, seu Deus, lhes dá como herança e a tiverem conquistado e se estabelecido nela,

[[v5-26-2]]

^<<v5-26-2,2>>^ coloquem num cesto alguns dos primeiros frutos de cada colheita que produziram e levem-no ao lugar que o SENHOR, seu Deus, escolher para habitação do seu nome.

[[v5-26-3]]

^<<v5-26-3,3>>^ Dirijam-se ao sacerdote que estiver de serviço naquela ocasião e digam-lhe: ‘Com esta oferta reconheço diante do SENHOR, seu Deus, ter entrado na terra que o SENHOR jurou a nossos antepassados que nos daria’.

[[v5-26-4]]

^<<v5-26-4,4>>^ O sacerdote pegará o cesto de suas mãos e o colocará diante do altar do SENHOR, seu Deus.

[[v5-26-5]]

^<<v5-26-5,5>>^ "Então vocês declararão na presença do SENHOR, seu Deus: ‘Meu antepassado Jacó era um nômade arameu que foi viver no Egito como estrangeiro. Quando chegou, sua família não era numerosa, mas no Egito ela se tornou uma grande e poderosa nação.

[[v5-26-6]]

^<<v5-26-6,6>>^ Quando os egípcios nos oprimiram e nos humilharam, sujeitando-nos à escravidão,

[[v5-26-7]]

^<<v5-26-7,7>>^ clamamos ao SENHOR, o Deus de nossos antepassados. O SENHOR ouviu nossos clamores e viu nossas dificuldades, nosso trabalho árduo e a opressão que sofríamos.

[[v5-26-8]]

^<<v5-26-8,8>>^ Por isso, o SENHOR nos libertou do Egito com mão forte e braço poderoso, com atos temíveis, sinais e maravilhas.

[[v5-26-9]]

^<<v5-26-9,9>>^ Trouxe-nos para este lugar e nos deu esta terra que produz leite e mel com fartura!

[[v5-26-10]]

^<<v5-26-10,10>>^ E agora, SENHOR, trago os primeiros frutos da colheita que, do solo, me deste’. Em seguida, coloquem o cesto diante do SENHOR, seu Deus, e prostrem-se diante dele em adoração.

[[v5-26-11]]

^<<v5-26-11,11>>^ Depois disso, alegrem-se por todas as coisas boas que o SENHOR, seu Deus, tem dado a vocês e a suas famílias. Lembrem-se de incluir na celebração os levitas e os estrangeiros que vivem entre vocês.

[[v5-26-12]]

^<<v5-26-12,12>>^ "A cada três anos, separem um dízimo especial de suas colheitas. Nesse ano, entreguem seus dízimos aos levitas, aos estrangeiros, aos órfãos e às viúvas, para que eles comam até se saciarem em suas cidades.

[[v5-26-13]]

^<<v5-26-13,13>>^ Então declarem na presença do SENHOR, seu Deus: ‘Dediquei, da minha casa, a oferta sagrada e a entreguei aos levitas, aos estrangeiros, aos órfãos e às viúvas, conforme ordenaste. Não quebrei nenhum dos teus mandamentos nem me esqueci de nenhum deles.

[[v5-26-14]]

^<<v5-26-14,14>>^ Não comi coisa alguma desta oferta enquanto estava de luto, nem a toquei enquanto estava cerimonialmente impuro, e não ofereci coisa alguma dela aos mortos. Obedeci ao SENHOR, meu Deus, e fiz tudo que me ordenaste.

[[v5-26-15]]

^<<v5-26-15,15>>^ Agora, olha desde a tua santa habitação no céu e abençoa o teu povo, Israel, e a terra que juraste a nossos antepassados que nos darias, uma terra que produz leite e mel com fartura’."

[[v5-26-16]]

^<<v5-26-16,16>>^ "Hoje o SENHOR, seu Deus, ordenou que obedeçam a todos estes decretos e estatutos. Cumpram-nos cuidadosamente, de todo o seu coração e de toda a sua alma.

[[v5-26-17]]

^<<v5-26-17,17>>^ Hoje vocês declararam que o SENHOR é o seu Deus e que andarão em seus caminhos, obedecerão a seus decretos, mandamentos e estatutos e farão tudo que ele mandar.

[[v5-26-18]]

^<<v5-26-18,18>>^ O SENHOR declarou hoje que vocês são seu povo, sua propriedade especial, conforme ele havia prometido, e que devem obedecer a todos os seus mandamentos.

[[v5-26-19]]

^<<v5-26-19,19>>^ Se o fizerem, ele os colocará muito acima de todas as outras nações que ele fez, e vocês receberão louvores, honra e fama. Serão uma nação santa ao SENHOR, seu Deus, exatamente como ele prometeu."

'''

xref:005-deuteronomio/005-deuteronomio-025.adoc#v5-25-0[&#60; Capítulo Anterior] | <<v5-26-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[Próximo Capítulo &#62;]