include::./index.adoc[]

[[v5-6-0]]
=== Deuteronômio, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v5-6-1]]

^<<v5-6-1,1>>^ "Estes são os mandamentos, os decretos e os estatutos que o SENHOR, seu Deus, me encarregou de lhes ensinar. Não deixem de cumpri-los na terra que em breve vocês possuirão.

[[v5-6-2]]

^<<v5-6-2,2>>^ Vocês, seus filhos e netos temerão o SENHOR, seu Deus, enquanto viverem. Se obedecerem a todos os seus decretos e mandamentos, desfrutarão de vida longa.

[[v5-6-3]]

^<<v5-6-3,3>>^ Ouça com atenção, Israel, e tenha o cuidado de obedecer. Então tudo irá bem com vocês e terão muitos filhos na terra que produz leite e mel com fartura, exatamente como lhes prometeu o SENHOR, o Deus de seus antepassados.

[[v5-6-4]]

^<<v5-6-4,4>>^ "Ouça, ó Israel! O SENHOR, nosso Deus, o SENHOR é único!

[[v5-6-5]]

^<<v5-6-5,5>>^ Ame o SENHOR, seu Deus, de todo o seu coração, de toda a sua alma e de toda a sua força.

[[v5-6-6]]

^<<v5-6-6,6>>^ Guarde sempre no coração as palavras que hoje eu lhe dou.

[[v5-6-7]]

^<<v5-6-7,7>>^ Repita-as com frequência a seus filhos. Converse a respeito delas quando estiver em casa e quando estiver caminhando, quando se deitar e quando se levantar.

[[v5-6-8]]

^<<v5-6-8,8>>^ Amarre-as às mãos e prenda-as à testa como lembrança.

[[v5-6-9]]

^<<v5-6-9,9>>^ Escreva-as nos batentes das portas de sua casa e em seus portões.

[[v5-6-10]]

^<<v5-6-10,10>>^ "Em breve, o SENHOR, seu Deus, os conduzirá à terra que ele jurou dar a seus antepassados Abraão, Isaque e Jacó. É uma terra com cidades grandes e prósperas que vocês não construíram.

[[v5-6-11]]

^<<v5-6-11,11>>^ As casas estarão cheias de bens que vocês não produziram. Vocês tirarão água de cisternas que não cavaram, e comerão os frutos de vinhedos e oliveiras que não plantaram. Quando tiverem comido até se fartarem nessa terra,

[[v5-6-12]]

^<<v5-6-12,12>>^ cuidem para não se esquecerem do SENHOR, que os libertou da escravidão na terra do Egito.

[[v5-6-13]]

^<<v5-6-13,13>>^ Temam o SENHOR, seu Deus, e sirvam a ele. Quando fizerem um juramento, jurem somente pelo nome dele.

[[v5-6-14]]

^<<v5-6-14,14>>^ "Não sigam nenhum dos deuses das nações vizinhas,

[[v5-6-15]]

^<<v5-6-15,15>>^ pois o SENHOR, seu Deus, que vive entre vocês, é Deus zeloso. Se o fizerem, a ira do SENHOR, seu Deus, se acenderá contra vocês, e ele os eliminará da face da terra.

[[v5-6-16]]

^<<v5-6-16,16>>^ Não ponham à prova o SENHOR, seu Deus, como fizeram quando se queixaram em Massá.

[[v5-6-17]]

^<<v5-6-17,17>>^ Obedeçam cuidadosamente aos mandamentos do SENHOR, seu Deus, bem como a todos os preceitos e decretos que ele lhes ordenou.

[[v5-6-18]]

^<<v5-6-18,18>>^ Façam o que é certo e bom aos olhos do SENHOR, para que tudo vá bem com vocês e tomem posse da boa terra em que vão entrar, a terra que o SENHOR prometeu sob juramento a seus antepassados.

[[v5-6-19]]

^<<v5-6-19,19>>^ Vocês expulsarão todos os inimigos que vivem nela, como o SENHOR disse que fariam.

[[v5-6-20]]

^<<v5-6-20,20>>^ "No futuro, seus filhos lhes perguntarão: ‘O que significam estes preceitos, decretos e estatutos que o SENHOR, nosso Deus, lhes deu?’.

[[v5-6-21]]

^<<v5-6-21,21>>^ "Então vocês lhes dirão: ‘Éramos escravos do faraó no Egito, mas o SENHOR nos tirou de lá com sua mão forte.

[[v5-6-22]]

^<<v5-6-22,22>>^ O SENHOR realizou sinais e maravilhas diante de nossos olhos e enviou castigos terríveis sobre o Egito, o faraó e todo o seu povo.

[[v5-6-23]]

^<<v5-6-23,23>>^ Ele nos tirou do Egito para nos dar esta terra que ele havia prometido sob juramento a nossos antepassados.

[[v5-6-24]]

^<<v5-6-24,24>>^ E o SENHOR ordenou que cumpramos todos estes decretos e temamos o SENHOR, nosso Deus, para que ele sempre nos abençoe e preserve nossa vida, como tem feito até hoje.

[[v5-6-25]]

^<<v5-6-25,25>>^ Pois a nossa justiça estará em obedecermos cuidadosamente aos mandamentos que o SENHOR, nosso Deus, nos ordenou’."

'''

xref:005-deuteronomio/005-deuteronomio-005.adoc#v5-5-0[&#60; Capítulo Anterior] | <<v5-6-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[Próximo Capítulo &#62;]