include::./index.adoc[]

[[v5-30-0]]
=== Deuteronômio, 30
// nvt ?, NVT - Nova Versão Transformadora

[[v5-30-1]]

^<<v5-30-1,1>>^ "No futuro, quando vocês experimentarem todas as bênçãos e maldições que lhes relatei, e quando estiverem vivendo entre as nações onde o SENHOR, seu Deus, os exilou, levem todas estas instruções a sério.

[[v5-30-2]]

^<<v5-30-2,2>>^ Se, nessa ocasião, vocês e seus filhos voltarem para o SENHOR, seu Deus, e se obedecerem de todo o coração e de toda a alma a todos os mandamentos que hoje lhes dou,

[[v5-30-3]]

^<<v5-30-3,3>>^ então o SENHOR, seu Deus, restaurará sua situação. Ele terá misericórdia de vocês e os reunirá de todas as nações por onde os espalhou.

[[v5-30-4]]

^<<v5-30-4,4>>^ Embora tenham sido banidos até os confins da terra, o SENHOR, seu Deus, os juntará e de lá os trará de volta.

[[v5-30-5]]

^<<v5-30-5,5>>^ O SENHOR, seu Deus, os trará à terra que pertencia a seus antepassados, e ela será sua outra vez. Então ele os tornará ainda mais prósperos e numerosos que seus antepassados!

[[v5-30-6]]

^<<v5-30-6,6>>^ "O SENHOR, seu Deus, transformará o coração de vocês e de todos os seus descendentes, para que o amem de todo o coração e de toda a alma, e para que vivam!

[[v5-30-7]]

^<<v5-30-7,7>>^ O SENHOR, seu Deus, enviará todas essas maldições sobre seus inimigos e sobre aqueles que os odeiam e os perseguem.

[[v5-30-8]]

^<<v5-30-8,8>>^ Então vocês voltarão a obedecer ao SENHOR e a cumprir todos os mandamentos que hoje lhes dou.

[[v5-30-9]]

^<<v5-30-9,9>>^ "O SENHOR, seu Deus, lhes dará sucesso em tudo que fizerem. Também lhes dará muitos filhos e rebanhos numerosos e fará seus campos produzirem colheitas fartas, pois o SENHOR voltará a ter prazer em ser bondoso com vocês, como aconteceu com seus antepassados.

[[v5-30-10]]

^<<v5-30-10,10>>^ O SENHOR, seu Deus, se alegrará em vocês se lhe obedecerem e cumprirem os mandamentos e decretos escritos neste Livro da Lei, e se voltarem para o SENHOR, seu Deus, de todo o coração e de toda a alma."

[[v5-30-11]]

^<<v5-30-11,11>>^ "Este mandamento que hoje lhes dou não é difícil demais para vocês, nem está fora de seu alcance.

[[v5-30-12]]

^<<v5-30-12,12>>^ Não está guardado no céu, tão longe que vocês tenham de perguntar: ‘Quem subirá ao céu a fim de trazê-lo até nós aqui embaixo, para que possamos ouvir e obedecer?’.

[[v5-30-13]]

^<<v5-30-13,13>>^ Não está guardado além do mar, tão distante que vocês tenham de perguntar: ‘Quem atravessará o mar a fim de trazê-lo até nós, para que possamos ouvir e obedecer?’.

[[v5-30-14]]

^<<v5-30-14,14>>^ Não, a mensagem está bem perto; está em seus lábios e em seu coração, para que possam obedecer.

[[v5-30-15]]

^<<v5-30-15,15>>^ "Agora ouçam! Hoje lhes dou a escolha entre a vida e a morte, entre a prosperidade e a calamidade.

[[v5-30-16]]

^<<v5-30-16,16>>^ Pois hoje ordeno que amem o SENHOR, seu Deus, e guardem seus mandamentos, decretos e estatutos, andando em seus caminhos. Se o fizerem, viverão e se multiplicarão, e o SENHOR, seu Deus, abençoará vocês e a terra em que estão prestes a entrar para tomar posse dela.

[[v5-30-17]]

^<<v5-30-17,17>>^ "Se, contudo, seu coração se desviar e vocês se recusarem a ouvir, se forem levados a seguir e adorar outros deuses,

[[v5-30-18]]

^<<v5-30-18,18>>^ eu os advirto hoje de que certamente serão destruídos. Não terão uma vida longa e boa na terra que estão atravessando o Jordão para ocupar.

[[v5-30-19]]

^<<v5-30-19,19>>^ "Hoje lhes dei a escolha entre a vida e a morte, entre bênçãos e maldições. Agora, chamo os céus e a terra como testemunhas da escolha que fizerem. Escolham a vida, para que vocês e seus filhos vivam!

[[v5-30-20]]

^<<v5-30-20,20>>^ Façam isso amando, obedecendo e apegando-se fielmente ao SENHOR, pois ele é a sua vida! Se vocês o amarem e lhe obedecerem, ele lhes dará vida longa na terra que o SENHOR jurou dar a seus antepassados Abraão, Isaque e Jacó".

'''

xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[&#60; Capítulo Anterior] | <<v5-30-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[Próximo Capítulo &#62;]