include::./index.adoc[]

[[v5-11-0]]
=== Deuteronômio, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v5-11-1]]

^<<v5-11-1,1>>^ "Amem o SENHOR, seu Deus, e obedeçam sempre ao que ele exige: seus estatutos, decretos e mandamentos.

[[v5-11-2]]

^<<v5-11-2,2>>^ Lembrem-se de que hoje não falo a seus filhos, que nunca experimentaram a disciplina do SENHOR, seu Deus, nem viram a grandeza, a mão forte e o seu braço poderoso.

[[v5-11-3]]

^<<v5-11-3,3>>^ Eles não viram os sinais e os atos poderosos que ele realizou no Egito contra o faraó e toda a sua terra.

[[v5-11-4]]

^<<v5-11-4,4>>^ Não viram o que ele fez aos exércitos dos egípcios e a seus cavalos e carros de guerra, como ele os afogou no mar Vermelho enquanto perseguiam vocês. Ele os destruiu e até hoje não se recuperaram.

[[v5-11-5]]

^<<v5-11-5,5>>^ "Seus filhos não viram como o SENHOR cuidou de vocês no deserto até chegarem aqui.

[[v5-11-6]]

^<<v5-11-6,6>>^ Não viram o que ele fez a Datã e Abirão (filhos de Eliabe, descendente de Rúben) quando a terra abriu a boca no acampamento israelita e os engoliu, junto com suas famílias, tendas e todos os seres vivos que pertenciam a eles.

[[v5-11-7]]

^<<v5-11-7,7>>^ Vocês, porém, viram com os próprios olhos que o SENHOR realizou todos esses atos poderosos!"

[[v5-11-8]]

^<<v5-11-8,8>>^ "Portanto, obedeçam a todos os mandamentos que hoje lhes dou, para que tenham forças para avançar e conquistar a terra da qual estão prestes a tomar posse.

[[v5-11-9]]

^<<v5-11-9,9>>^ Se obedecerem, terão vida longa na terra que o SENHOR jurou dar a seus antepassados e a vocês, os descendentes deles, uma terra que produz leite e mel com fartura!

[[v5-11-10]]

^<<v5-11-10,10>>^ Pois a terra em que vocês estão prestes a entrar para tomar posse não é como a terra do Egito, de onde vocês vieram e onde plantavam as sementes e faziam valas de irrigação com o pé, como numa horta.

[[v5-11-11]]

^<<v5-11-11,11>>^ A terra da qual em breve tomarão posse é uma terra de montes e vales, com chuva em grande quantidade,

[[v5-11-12]]

^<<v5-11-12,12>>^ terra da qual o SENHOR, seu Deus, cuida continuamente, todo o ano!

[[v5-11-13]]

^<<v5-11-13,13>>^ "Se obedecerem fielmente aos mandamentos que hoje lhes dou, e se amarem o SENHOR, seu Deus, e servirem a ele de todo o seu coração e de toda a sua alma,

[[v5-11-14]]

^<<v5-11-14,14>>^ ele mandará as chuvas na estação apropriada, as chuvas de outono e de primavera, para que vocês juntem suas colheitas de cereais e produzam vinho novo e azeite.

[[v5-11-15]]

^<<v5-11-15,15>>^ Ele dará bons pastos para seus animais, e vocês terão alimento com fartura.

[[v5-11-16]]

^<<v5-11-16,16>>^ "Mas tenham cuidado! Não deixem seu coração ser enganado, levando-os a afastar-se do SENHOR e a adorar outros deuses.

[[v5-11-17]]

^<<v5-11-17,17>>^ Se o fizerem, a ira do SENHOR se acenderá contra vocês. Ele fechará o céu e reterá a chuva, e a terra não produzirá suas colheitas. Em pouco tempo, vocês serão removidos da boa terra que o SENHOR lhes dá.

[[v5-11-18]]

^<<v5-11-18,18>>^ "Gravem estas minhas palavras no coração e na mente. Amarrem-nas às mãos e prendam-nas à testa como lembrança.

[[v5-11-19]]

^<<v5-11-19,19>>^ Ensinem-nas a seus filhos. Conversem a respeito delas quando estiverem em casa e quando estiverem caminhando, quando se deitarem e quando se levantarem.

[[v5-11-20]]

^<<v5-11-20,20>>^ Escrevam-nas nos batentes das portas de suas casas e em seus portões,

[[v5-11-21]]

^<<v5-11-21,21>>^ para que, enquanto o céu permanecer acima da terra, vocês e seus filhos prosperem neste chão que o SENHOR jurou dar a seus antepassados.

[[v5-11-22]]

^<<v5-11-22,22>>^ "Obedeçam cuidadosamente a todos os mandamentos que lhes dou. Amem o SENHOR, seu Deus, andando em seus caminhos e apegando-se firmemente a ele.

[[v5-11-23]]

^<<v5-11-23,23>>^ Então o SENHOR expulsará todas as nações de diante de vocês e, embora elas sejam muito maiores e mais fortes, vocês tomarão posse de suas terras.

[[v5-11-24]]

^<<v5-11-24,24>>^ Todo lugar em que puserem os pés será de vocês. Suas fronteiras se estenderão do deserto, ao sul, até o Líbano, ao norte, e do rio Eufrates, a leste, até o mar Mediterrâneo, a oeste.

[[v5-11-25]]

^<<v5-11-25,25>>^ Aonde quer que forem em toda a terra, ninguém será capaz de lhes resistir, pois o SENHOR, seu Deus, fará os povos se apavorarem e temerem vocês, como lhes prometeu.

[[v5-11-26]]

^<<v5-11-26,26>>^ "Vejam, hoje lhes dou a escolha entre bênção e maldição!

[[v5-11-27]]

^<<v5-11-27,27>>^ Vocês serão abençoados se obedecerem aos mandamentos do SENHOR, seu Deus, que hoje lhes dou,

[[v5-11-28]]

^<<v5-11-28,28>>^ mas serão amaldiçoados se rejeitarem os mandamentos do SENHOR, seu Deus, afastando-se de seus caminhos e adorando deuses que vocês não conheciam.

[[v5-11-29]]

^<<v5-11-29,29>>^ "Quando o SENHOR, seu Deus, os fizer entrar na terra da qual em breve vocês tomarão posse, pronunciem a bênção no monte Gerizim e a maldição no monte Ebal.

[[v5-11-30]]

^<<v5-11-30,30>>^ (Esses dois montes ficam a oeste do rio Jordão, na terra dos cananeus que vivem no vale do Jordão, perto da cidade de Gilgal, junto aos carvalhos de Moré.)

[[v5-11-31]]

^<<v5-11-31,31>>^ Vocês estão prestes a atravessar o rio Jordão para tomar posse da terra que o SENHOR, seu Deus, lhes dá. Quando a conquistarem e estiverem vivendo nela,

[[v5-11-32]]

^<<v5-11-32,32>>^ tenham o cuidado de cumprir todos os decretos e estatutos que hoje lhes dou."

'''

xref:005-deuteronomio/005-deuteronomio-010.adoc#v5-10-0[&#60; Capítulo Anterior] | <<v5-11-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[Próximo Capítulo &#62;]