include::./index.adoc[]

[[v5-1-0]]
=== Deuteronômio, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v5-1-1]]

^<<v5-1-1,1>>^ Estas são as palavras que Moisés disse a todo o povo de Israel quando estavam no deserto, a leste do rio Jordão, acampados no vale do Jordão, perto de Sufe, entre Parã, de um lado, e Tofel, Labã, Hazerote e Di-Zaabe, do outro.

[[v5-1-2]]

^<<v5-1-2,2>>^ Normalmente, são necessários apenas onze dias para viajar do monte Sinai até Cades-Barneia pelo caminho do monte Seir.

[[v5-1-3]]

^<<v5-1-3,3>>^ No entanto, quarenta anos depois da saída do Egito, no primeiro dia do décimo primeiro mês, Moisés se dirigiu aos israelitas e lhes transmitiu tudo que o SENHOR lhe havia ordenado.

[[v5-1-4]]

^<<v5-1-4,4>>^ Isso aconteceu depois que ele derrotou Seom, rei dos amorreus que vivia em Hesbom, e, em Edrei, derrotou Ogue, o rei de Basã que vivia em Astarote.

[[v5-1-5]]

^<<v5-1-5,5>>^ Enquanto estavam na terra de Moabe, a leste do Jordão, Moisés começou a lhes explicar as seguintes instruções.

[[v5-1-6]]

^<<v5-1-6,6>>^ "Quando estávamos no monte Sinai, o SENHOR, nosso Deus, nos disse: ‘Vocês já ficaram muito tempo neste monte.

[[v5-1-7]]

^<<v5-1-7,7>>^ É hora de levantar acampamento e seguir viagem. Vão à região montanhosa dos amorreus e a todas as regiões vizinhas: o vale do Jordão, a região montanhosa, as colinas do oeste, o Neguebe e a planície costeira. Vão à terra dos cananeus e ao Líbano, e avancem até o grande rio Eufrates.

[[v5-1-8]]

^<<v5-1-8,8>>^ Vejam, eu lhes dou toda esta terra! Entrem e tomem posse dela, pois é a terra que o SENHOR jurou dar a seus antepassados Abraão, Isaque e Jacó, e a todos os seus descendentes’."

[[v5-1-9]]

^<<v5-1-9,9>>^ Moisés continuou: "Naquela ocasião, eu lhes disse: ‘Vocês são um peso grande demais para eu carregar sozinho.

[[v5-1-10]]

^<<v5-1-10,10>>^ O SENHOR, seu Deus, aumentou sua população e os tornou tão numerosos quanto as estrelas do céu.

[[v5-1-11]]

^<<v5-1-11,11>>^ Que o SENHOR, o Deus de seus antepassados, os multiplique mil vezes mais e os abençoe como ele prometeu.

[[v5-1-12]]

^<<v5-1-12,12>>^ Mas vocês são um peso grande demais para mim! Como poderei lidar com todos os seus problemas e conflitos?

[[v5-1-13]]

^<<v5-1-13,13>>^ Escolham alguns homens respeitados de cada tribo, conhecidos por sua sabedoria e entendimento, e eu os designarei para serem seus líderes’.

[[v5-1-14]]

^<<v5-1-14,14>>^ "Então vocês responderam: ‘Seu plano é bom!’.

[[v5-1-15]]

^<<v5-1-15,15>>^ Assim, convoquei os homens respeitados que vocês selecionaram de suas tribos e os nomeei para serem juízes e oficiais sobre vocês. Alguns ficaram responsáveis por mil pessoas, outros por cem, outros por cinquenta, e outros por dez.

[[v5-1-16]]

^<<v5-1-16,16>>^ "Naquela ocasião, ordenei aos juízes: ‘Deem atenção aos casos de seus irmãos israelitas e também dos estrangeiros que vivem entre vocês. Sejam completamente justos em todas as suas decisões

[[v5-1-17]]

^<<v5-1-17,17>>^ e imparciais em seus julgamentos. Cuidem tanto dos casos dos pobres como dos ricos. Não deixem que ninguém os intimide, pois Deus dará a decisão por seu intermédio. Tragam-me os casos que forem difíceis demais para vocês, e eu cuidarei deles’.

[[v5-1-18]]

^<<v5-1-18,18>>^ "Naquela ocasião, eu lhes ordenei tudo que deveriam fazer."

[[v5-1-19]]

^<<v5-1-19,19>>^ "Em seguida, conforme o SENHOR, nosso Deus, ordenou, partimos do monte Sinai e atravessamos o deserto imenso e assustador, como vocês lembram, e nos dirigimos à região montanhosa dos amorreus. Quando chegamos a Cades-Barneia,

[[v5-1-20]]

^<<v5-1-20,20>>^ eu lhes disse: ‘Vocês chegaram à região montanhosa dos amorreus, que o SENHOR, nosso Deus, nos dá.

[[v5-1-21]]

^<<v5-1-21,21>>^ Vejam, o SENHOR, seu Deus, colocou a terra diante de vocês! Vão e tomem posse dela, conforme o SENHOR, o Deus de seus antepassados, lhes prometeu. Não tenham medo nem desanimem!’.

[[v5-1-22]]

^<<v5-1-22,22>>^ "Então todos vocês vieram e me disseram: ‘Primeiro, enviemos espiões para que façam o reconhecimento da terra para nós. Eles recomendarão o melhor caminho e indicarão em quais cidades devemos entrar’.

[[v5-1-23]]

^<<v5-1-23,23>>^ "A ideia me pareceu boa, por isso escolhi doze espiões, um de cada tribo.

[[v5-1-24]]

^<<v5-1-24,24>>^ Eles foram à região montanhosa, chegaram ao vale de Escol e fizeram o reconhecimento.

[[v5-1-25]]

^<<v5-1-25,25>>^ Pegaram alguns dos frutos da região e os trouxeram para nós. Então, relataram: ‘A terra que o SENHOR, nosso Deus, nos dá é, de fato, uma terra boa’."

[[v5-1-26]]

^<<v5-1-26,26>>^ "Contudo, vocês se rebelaram contra a ordem do SENHOR, seu Deus, e se recusaram a entrar.

[[v5-1-27]]

^<<v5-1-27,27>>^ Queixaram-se dentro de suas tendas e disseram: ‘Com certeza o SENHOR nos odeia. Por isso nos trouxe do Egito, a fim de nos entregar nas mãos dos amorreus para sermos exterminados.

[[v5-1-28]]

^<<v5-1-28,28>>^ Para onde podemos ir? Nossos irmãos nos desanimaram com seu relatório. Eles disseram: ‘Os habitantes da terra são mais altos e poderosos que nós, e suas cidades são grandes, com muros que sobem até o céu! Vimos até os descendentes de Enaque!’.

[[v5-1-29]]

^<<v5-1-29,29>>^ "Eu lhes disse: ‘Não entrem em pânico nem tenham medo deles!

[[v5-1-30]]

^<<v5-1-30,30>>^ O SENHOR, seu Deus, irá adiante de vocês. Ele lutará em seu favor, conforme tudo que vocês o viram fazer no Egito.

[[v5-1-31]]

^<<v5-1-31,31>>^ Também viram como o SENHOR, seu Deus, cuidou de vocês ao longo do caminho, enquanto viajavam pelo deserto, como um pai cuida de seu filho. Agora ele os trouxe a este lugar’.

[[v5-1-32]]

^<<v5-1-32,32>>^ "No entanto, mesmo depois de tudo que ele fez, vocês se recusaram a confiar no SENHOR, seu Deus,

[[v5-1-33]]

^<<v5-1-33,33>>^ que vai adiante de vocês buscando lugares para acamparem e guiando-os com uma coluna de fogo durante a noite e uma coluna de nuvem durante o dia.

[[v5-1-34]]

^<<v5-1-34,34>>^ "Quando o SENHOR ouviu vocês se queixarem, ficou irado e, por isso, fez um juramento:

[[v5-1-35]]

^<<v5-1-35,35>>^ ‘Nenhum de vocês desta geração perversa viverá para ver a boa terra que eu jurei dar a seus antepassados.

[[v5-1-36]]

^<<v5-1-36,36>>^ A única exceção será Calebe, filho de Jefoné. Ele verá a terra, pois seguiu o SENHOR em tudo. Darei a ele e a seus descendentes parte da terra que ele explorou durante sua missão de reconhecimento’.

[[v5-1-37]]

^<<v5-1-37,37>>^ "Foi por causa de vocês que o SENHOR se irou contra mim. Ele me disse: ‘Você também não entrará na terra!

[[v5-1-38]]

^<<v5-1-38,38>>^ Seu auxiliar, Josué, filho de Num, entrará na terra. Encoraje-o, pois ele conduzirá o povo quando Israel tomar posse dela.

[[v5-1-39]]

^<<v5-1-39,39>>^ Darei a terra a seus filhos pequenos, às crianças que não sabem a diferença entre certo e errado. Vocês temiam que seus pequeninos fossem capturados, mas serão eles que tomarão posse da terra.

[[v5-1-40]]

^<<v5-1-40,40>>^ Quanto a vocês, deem meia-volta e retornem ao deserto, em direção ao mar Vermelho’.

[[v5-1-41]]

^<<v5-1-41,41>>^ "Então vocês admitiram: ‘Pecamos contra o SENHOR! Agora, subiremos e lutaremos pela terra, como o SENHOR, nosso Deus, ordenou’. Seus homens se armaram para a guerra, pensando que seria fácil atacar a região montanhosa.

[[v5-1-42]]

^<<v5-1-42,42>>^ "Mas o SENHOR me encarregou de lhes dizer: ‘Não ataquem, pois não estou com vocês. Se forem por conta própria, serão derrotados por seus inimigos’.

[[v5-1-43]]

^<<v5-1-43,43>>^ "Foi o que eu lhes disse, mas vocês não deram ouvidos. Em vez disso, rebelaram-se mais uma vez contra a ordem do SENHOR e, arrogantemente, foram à região montanhosa para lutar.

[[v5-1-44]]

^<<v5-1-44,44>>^ Os amorreus que viviam ali saíram e os atacaram como um enxame de abelhas. Eles os perseguiram e os massacraram ao longo de todo o caminho, desde Seir até Hormá.

[[v5-1-45]]

^<<v5-1-45,45>>^ Então vocês voltaram e choraram diante do SENHOR, mas o SENHOR se recusou a ouvi-los.

[[v5-1-46]]

^<<v5-1-46,46>>^ Por isso, ficaram em Cades por um longo tempo."

'''

xref:004-numeros/004-numeros-036.adoc#v4-36-0[&#60; Capítulo Anterior] | <<v5-1-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[Próximo Capítulo &#62;]