include::./index.adoc[]

[[v5-2-0]]
=== Deuteronômio, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v5-2-1]]

^<<v5-2-1,1>>^ "Depois disso, demos meia-volta e regressamos pelo deserto, em direção ao mar Vermelho, conforme a instrução que o SENHOR me deu. Por um longo tempo, vagamos de um lugar para outro na região do monte Seir.

[[v5-2-2]]

^<<v5-2-2,2>>^ "Finalmente, o SENHOR me disse:

[[v5-2-3]]

^<<v5-2-3,3>>^ ‘Vocês andaram por esta região montanhosa tempo suficiente; agora, sigam para o norte.

[[v5-2-4]]

^<<v5-2-4,4>>^ Dê as seguintes ordens ao povo: Vocês passarão pelo território de seus parentes edomitas, os descendentes de Esaú, que habitam em Seir. Tenham muito cuidado, pois os edomitas se sentirão ameaçados.

[[v5-2-5]]

^<<v5-2-5,5>>^ Não os perturbem, pois eu dei a eles como propriedade toda a região montanhosa ao redor do monte Seir, e não darei a vocês um metro sequer da terra deles.

[[v5-2-6]]

^<<v5-2-6,6>>^ Paguem por todo alimento que comerem e pela água que beberem.

[[v5-2-7]]

^<<v5-2-7,7>>^ Pois o SENHOR, seu Deus, tem abençoado vocês em tudo que têm feito. Ele tem cuidado de cada um de seus passos por este grande deserto. Durante estes quarenta anos, o SENHOR, seu Deus, tem estado com vocês, e nada lhes tem faltado’.

[[v5-2-8]]

^<<v5-2-8,8>>^ "Assim, contornamos o território de nossos parentes, os descendentes de Esaú, que habitam em Seir. Evitamos o caminho que passa pelo vale de Arabá, que sobe de Elate e Eziom-Geber. "Então, quando nos dirigimos para o norte pelo caminho do deserto de Moabe,

[[v5-2-9]]

^<<v5-2-9,9>>^ o SENHOR nos advertiu: ‘Não perturbem os moabitas, os descendentes de Ló, nem comecem uma guerra contra eles. Eu dei a eles como propriedade a região de Ar, e não darei a vocês parte alguma do território deles’.

[[v5-2-10]]

^<<v5-2-10,10>>^ (Antigamente, um povo chamado emins havia habitado na região de Ar. Eram tão fortes, numerosos e altos quanto os enaquins.

[[v5-2-11]]

^<<v5-2-11,11>>^ Os emins e os enaquins também eram conhecidos como refains, embora os moabitas os chamassem de emins.

[[v5-2-12]]

^<<v5-2-12,12>>^ Em outros tempos, os horeus haviam habitado em Seir, mas os edomitas os expulsaram e ocuparam sua terra, da mesma forma que Israel expulsou os habitantes de Canaã quando o SENHOR lhe deu a terra deles.)

[[v5-2-13]]

^<<v5-2-13,13>>^ "Então o SENHOR nos disse: ‘Mexam-se! Atravessem o ribeiro de Zerede’. Assim, atravessamos o ribeiro.

[[v5-2-14]]

^<<v5-2-14,14>>^ "Trinta e oito anos se passaram desde que partimos pela primeira vez de Cades-Barneia até atravessarmos, por fim, o ribeiro de Zerede. Àquela altura, todos os homens com idade suficiente para ir à guerra tinham morrido no deserto, como o SENHOR havia jurado que aconteceria.

[[v5-2-15]]

^<<v5-2-15,15>>^ A mão do SENHOR pesou sobre eles e os eliminou, e eles morreram no meio do acampamento.

[[v5-2-16]]

^<<v5-2-16,16>>^ "Quando todos os homens com idade suficiente para ir à guerra haviam morrido,

[[v5-2-17]]

^<<v5-2-17,17>>^ o SENHOR me disse:

[[v5-2-18]]

^<<v5-2-18,18>>^ ‘Hoje vocês atravessarão a fronteira com Moabe pela região de Ar

[[v5-2-19]]

^<<v5-2-19,19>>^ e se aproximarão da terra dos amonitas, os descendentes de Ló. Não os perturbem nem comecem uma guerra contra eles. Eu dei a eles como propriedade a terra de Amom, e não darei a vocês parte alguma do território deles’.

[[v5-2-20]]

^<<v5-2-20,20>>^ (Antigamente, aquela região era considerada terra dos refains que haviam habitado ali, embora os amonitas os chamassem de zanzumins.

[[v5-2-21]]

^<<v5-2-21,21>>^ Também eram tão fortes, numerosos e altos quanto os enaquins. Mas o SENHOR os destruiu para que os amonitas tomassem posse de sua terra.

[[v5-2-22]]

^<<v5-2-22,22>>^ Ele fez o mesmo pelos descendentes de Esaú que habitavam em Seir, pois destruiu os horeus para que os descendentes de Esaú se estabelecessem no lugar deles. Os descendentes de Esaú habitam nessa terra até hoje.

[[v5-2-23]]

^<<v5-2-23,23>>^ Algo parecido aconteceu quando os caftoreus de Creta invadiram e destruíram os aveus, que habitavam em povoados na região de Gaza.)

[[v5-2-24]]

^<<v5-2-24,24>>^ "Então o SENHOR disse: ‘Mexam-se! Atravessem o vale de Arnom. Vejam, eu lhes entregarei o amorreu Seom, rei de Hesbom, e lhes darei a terra dele. Ataquem-no e comecem a tomar posse daquele território.

[[v5-2-25]]

^<<v5-2-25,25>>^ A partir de hoje, farei os povos de toda a terra se encherem de medo por sua causa. Quando ouvirem relatos a seu respeito, tremerão de angústia e pavor’."

[[v5-2-26]]

^<<v5-2-26,26>>^ "Do deserto de Quedemote, enviei embaixadores ao rei Seom de Hesbom com a seguinte proposta de paz:

[[v5-2-27]]

^<<v5-2-27,27>>^ ‘Deixe-nos atravessar seu território. Ficaremos na estrada principal e não nos desviaremos nem para um lado nem para o outro.

[[v5-2-28]]

^<<v5-2-28,28>>^ Venda-nos alimentos para comermos e água para bebermos, e pagaremos por tudo. Queremos apenas permissão para passar por seu território.

[[v5-2-29]]

^<<v5-2-29,29>>^ Os descendentes de Esaú, que habitam em Seir, nos permitiram passar pelo território deles, como também fizeram os moabitas, que habitam na região de Ar. Deixe-nos passar até atravessarmos o Jordão e entrarmos na terra que o SENHOR, nosso Deus, nos dá’.

[[v5-2-30]]

^<<v5-2-30,30>>^ "Mas Seom, rei de Hesbom, não nos permitiu passar, pois o SENHOR, seu Deus, endureceu-lhe o coração e o tornou hostil, a fim de entregá-lo em nossas mãos, como de fato aconteceu.

[[v5-2-31]]

^<<v5-2-31,31>>^ "Então o SENHOR me disse: ‘Veja, eu lhes entrego o rei Seom e seu território. Agora, comecem a conquistar sua terra e a tomar posse dela’.

[[v5-2-32]]

^<<v5-2-32,32>>^ "Então o rei Seom declarou guerra contra nós e mobilizou todas as suas tropas em Jaza.

[[v5-2-33]]

^<<v5-2-33,33>>^ Mas o SENHOR, nosso Deus, o entregou a nós, e matamos a ele, seus filhos e todo o seu povo.

[[v5-2-34]]

^<<v5-2-34,34>>^ Conquistamos todas as suas cidades e as destruímos completamente. Matamos homens, mulheres e crianças. Não poupamos ninguém.

[[v5-2-35]]

^<<v5-2-35,35>>^ Tomamos como despojo todos os animais e todos os objetos de valor das cidades que conquistamos.

[[v5-2-36]]

^<<v5-2-36,36>>^ "Também conquistamos Aroer, à beira do vale de Arnom, além da cidade no vale e toda a região até Gileade. Nenhuma cidade tinha muralhas fortes o suficiente para nos deter, pois o SENHOR, nosso Deus, nos entregou tudo.

[[v5-2-37]]

^<<v5-2-37,37>>^ Evitamos, porém, a terra dos amonitas, ao longo do rio Jaboque, e as cidades da região montanhosa, ou seja, todos os lugares que o SENHOR, nosso Deus, havia ordenado que deixássemos em paz."

'''

xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[&#60; Capítulo Anterior] | <<v5-2-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-003.adoc#v5-3-0[Próximo Capítulo &#62;]