include::./index.adoc[]

[[v5-33-0]]
=== Deuteronômio, 33
// nvt ?, NVT - Nova Versão Transformadora

[[v5-33-1]]

^<<v5-33-1,1>>^ Esta é a bênção que Moisés, homem de Deus, deu aos israelitas antes de sua morte:

[[v5-33-2]]

^<<v5-33-2,2>>^ "O SENHOR veio do monte Sinai e alvoreceu sobre nós desde o monte Seir; resplandeceu desde o monte Parã e veio de Meribá-Cades com fogo ardente em sua mão direita.

[[v5-33-3]]

^<<v5-33-3,3>>^ Por certo ele ama seu povo; todos os seus santos estão em suas mãos. Seguem seus passos e recebem seus ensinamentos.

[[v5-33-4]]

^<<v5-33-4,4>>^ Moisés nos deu a lei, a propriedade especial do povo de Israel.

[[v5-33-5]]

^<<v5-33-5,5>>^ O SENHOR era rei em Jesurum, quando os líderes do povo se reuniram, quando as tribos de Israel se juntaram como uma só".

[[v5-33-6]]

^<<v5-33-6,6>>^ "Que a tribo de Rúben viva e não desapareça, embora não seja numerosa".

[[v5-33-7]]

^<<v5-33-7,7>>^ Foi isto que Moisés disse a respeito da tribo de Judá: "Ó SENHOR, ouve o clamor de Judá e reúne-os como um só povo. Dá-lhes forças para defender sua causa; ajuda-os contra seus inimigos".

[[v5-33-8]]

^<<v5-33-8,8>>^ A respeito da tribo de Levi, disse: "Ó SENHOR, deste o Tumim e o Urim, as sortes sagradas, a teus servos fiéis. Tu os provaste em Massá e lutaste com eles junto às águas de Meribá.

[[v5-33-9]]

^<<v5-33-9,9>>^ Os levitas obedeceram à tua palavra e guardaram a tua aliança. Foram mais leais a ti que aos próprios pais. Ignoraram os parentes e não reconheceram os próprios filhos.

[[v5-33-10]]

^<<v5-33-10,10>>^ Ensinaram teus estatutos a Jacó, deram tuas instruções a Israel. Oferecem incenso diante de ti e apresentam holocaustos inteiros no teu altar.

[[v5-33-11]]

^<<v5-33-11,11>>^ Abençoa o serviço dos levitas, ó SENHOR, e aceita todo o trabalho de suas mãos. Quebra os quadris de seus inimigos; derruba seus adversários, para que nunca voltem a se levantar".

[[v5-33-12]]

^<<v5-33-12,12>>^ A respeito da tribo de Benjamim, disse: "Benjamim é amado pelo Senhor e vive em segurança ao seu lado. Ele o protege continuamente e o faz descansar sobre seus ombros".

[[v5-33-13]]

^<<v5-33-13,13>>^ A respeito da tribo de José, disse: "O SENHOR abençoe suas terras com a dádiva preciosa do orvalho do céu e água das profundezas da terra;

[[v5-33-14]]

^<<v5-33-14,14>>^ com os ricos frutos que amadurecem ao sol e as colheitas fartas de cada mês;

[[v5-33-15]]

^<<v5-33-15,15>>^ com as mais excelentes safras dos montes antigos, e os ricos frutos das colinas eternas;

[[v5-33-16]]

^<<v5-33-16,16>>^ com as melhores dádivas da terra e sua fartura, e o favor daquele que apareceu no arbusto em chamas. Que essas bênçãos repousem sobre a cabeça de José e coroem a fronte do príncipe entre seus irmãos.

[[v5-33-17]]

^<<v5-33-17,17>>^ José é majestoso como um touro jovem; tem a força de um boi selvagem. Com seus chifres expulsará as nações distantes até os confins da terra. Essa é a minha bênção para as multidões de Efraim e para os milhares de Manassés".

[[v5-33-18]]

^<<v5-33-18,18>>^ A respeito da tribo de Zebulom, disse: "Que o povo de Zebulom prospere em suas viagens, que o povo de Issacar prospere em suas tendas.

[[v5-33-19]]

^<<v5-33-19,19>>^ Convocam o povo ao monte para ali oferecer os sacrifícios apropriados. Fartam-se das riquezas do mar e dos tesouros escondidos na areia".

[[v5-33-20]]

^<<v5-33-20,20>>^ A respeito da tribo de Gade, disse: "Abençoado é aquele que expande o território de Gade! Gade fica à espreita como leão, para arrancar um braço ou uma cabeça.

[[v5-33-21]]

^<<v5-33-21,21>>^ O povo de Gade tomou para si a melhor parte da terra; a ele foi entregue a porção do líder. Quando os líderes do povo estavam reunidos, executou a justiça do Senhor e obedeceu a seus estatutos para Israel".

[[v5-33-22]]

^<<v5-33-22,22>>^ A respeito da tribo de Dã, disse: "Dã é filhote de leão, que salta de Basã".

[[v5-33-23]]

^<<v5-33-23,23>>^ A respeito da tribo de Naftali, disse: "Ó Naftali, você é rico em favor e repleto das bênçãos do SENHOR; herdará as terras do oeste e do sul".

[[v5-33-24]]

^<<v5-33-24,24>>^ E, a respeito da tribo de Aser, disse: "Que Aser seja mais abençoado que os outros filhos; seja ele estimado por seus irmãos e banhe os pés em óleo de oliva.

[[v5-33-25]]

^<<v5-33-25,25>>^ Que as trancas de suas portas sejam de ferro e bronze e sua força dure por todos os seus dias".

[[v5-33-26]]

^<<v5-33-26,26>>^ "Não há ninguém como o Deus de Jesurum! Ele cavalga pelos céus para ajudá-los e monta as nuvens com majestoso esplendor.

[[v5-33-27]]

^<<v5-33-27,27>>^ O Deus eterno é seu refúgio, e seus braços eternos os sustentam. Expulsa os inimigos de diante de vocês e grita: ‘Destruam esses povos!’.

[[v5-33-28]]

^<<v5-33-28,28>>^ Israel viverá em paz, a fonte de Jacó estará segura numa terra de cereais e vinho novo, onde os céus gotejam orvalho.

[[v5-33-29]]

^<<v5-33-29,29>>^ Como você é feliz, ó Israel! Quem é como você, povo salvo pelo SENHOR? Ele é seu escudo protetor e sua espada triunfante! Seus inimigos se encolherão de medo diante de você, e você lhes pisoteará as costas".

'''

xref:005-deuteronomio/005-deuteronomio-032.adoc#v5-32-0[&#60; Capítulo Anterior] | <<v5-33-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[Próximo Capítulo &#62;]