include::./index.adoc[]

[[v5-13-0]]
=== Deuteronômio, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v5-13-1]]

^<<v5-13-1,1>>^ "Surgirão entre vocês profetas ou pessoas que têm sonhos sobre o futuro, e eles prometerão sinais ou milagres.

[[v5-13-2]]

^<<v5-13-2,2>>^ Se os sinais ou milagres preditos acontecerem, e essas pessoas disserem: ‘Venham, vamos adorar outros deuses!’, deuses que até então vocês não conheciam,

[[v5-13-3]]

^<<v5-13-3,3>>^ não deem ouvidos às palavras deles. É um teste do SENHOR, seu Deus, para ver se vocês o amam de todo o seu coração e de toda a sua alma.

[[v5-13-4]]

^<<v5-13-4,4>>^ Sigam somente o SENHOR, seu Deus, e temam a ele somente. Obedeçam a seus mandamentos, ouçam sua voz, sirvam-no e apeguem-se a ele.

[[v5-13-5]]

^<<v5-13-5,5>>^ Os falsos profetas e sonhadores que tentarem desviá-los devem ser executados, pois incentivaram a rebelião contra o SENHOR, seu Deus, que os libertou da escravidão e os tirou da terra do Egito. Uma vez que eles tentaram desviá-los do caminho que o SENHOR, seu Deus, ordenou que seguissem, vocês terão de executá-los. Desse modo, vocês eliminarão o mal do seu meio.

[[v5-13-6]]

^<<v5-13-6,6>>^ "Se alguém o instigar secretamente, seja seu irmão, seu filho ou filha, sua esposa querida ou seu amigo mais chegado, e disser: ‘Vamos adorar outros deuses!’, deuses que nem você nem seus antepassados conheceram,

[[v5-13-7]]

^<<v5-13-7,7>>^ deuses dos povos vizinhos ou de povos dos confins da terra,

[[v5-13-8]]

^<<v5-13-8,8>>^ não ceda nem dê ouvidos. Não tenha pena dele, não o poupe nem o proteja.

[[v5-13-9]]

^<<v5-13-9,9>>^ Execute-o! Dê o primeiro golpe e, em seguida, todo o povo participará da execução.

[[v5-13-10]]

^<<v5-13-10,10>>^ Apedrejem os culpados até a morte, pois eles tentaram afastá-lo do SENHOR, seu Deus, que os libertou da terra do Egito, do lugar de escravidão.

[[v5-13-11]]

^<<v5-13-11,11>>^ Então todo o Israel ouvirá e temerá, e ninguém voltará a agir tão perversamente no meio de vocês.

[[v5-13-12]]

^<<v5-13-12,12>>^ "Quando começarem a viver nas cidades que o SENHOR, seu Deus, lhes dá, e ouvirem dizer

[[v5-13-13]]

^<<v5-13-13,13>>^ que homens perversos fizeram os habitantes da cidade se desviarem, dizendo: ‘Venham, vamos adorar outros deuses’, deuses que até então vocês não conheciam,

[[v5-13-14]]

^<<v5-13-14,14>>^ examinem os fatos com cuidado. Se descobrirem que a informação for verdadeira e esse ato detestável foi mesmo cometido entre vocês,

[[v5-13-15]]

^<<v5-13-15,15>>^ ataquem a cidade e matem à espada todos os habitantes e todos os animais, destruindo-os completamente.

[[v5-13-16]]

^<<v5-13-16,16>>^ Amontoem os despojos no meio da praça pública e queimem toda a cidade como oferta ao SENHOR, seu Deus. A cidade permanecerá em ruínas para sempre; jamais será reconstruída.

[[v5-13-17]]

^<<v5-13-17,17>>^ Não guardem coisa alguma do despojo que foi separado para destruição. Então o SENHOR afastará sua ira ardente e os tratará com misericórdia. Terá compaixão de vocês e os transformará numa nação numerosa, como prometeu sob juramento a seus antepassados.

[[v5-13-18]]

^<<v5-13-18,18>>^ "O SENHOR, seu Deus, só será misericordioso se vocês ouvirem sua voz e obedecerem a todos os seus mandamentos que hoje lhes dou, para que façam o que é certo aos olhos do SENHOR."

'''

xref:005-deuteronomio/005-deuteronomio-012.adoc#v5-12-0[&#60; Capítulo Anterior] | <<v5-13-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[Próximo Capítulo &#62;]