include::./index.adoc[]

[[v5-4-0]]
=== Deuteronômio, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v5-4-1]]

^<<v5-4-1,1>>^ "Agora, Israel, ouça com atenção estes decretos e estatutos que lhe ensinarei. Cumpram-nos para que vocês vivam, entrem na terra que o SENHOR, o Deus de seus antepassados, lhes dá e tomem posse dela.

[[v5-4-2]]

^<<v5-4-2,2>>^ Não acrescentem coisa alguma às ordens que eu lhes dou, nem tirem coisa alguma delas. Simplesmente obedeçam aos mandamentos do SENHOR, seu Deus, que eu lhes dou.

[[v5-4-3]]

^<<v5-4-3,3>>^ "Vocês viram com os próprios olhos o que o SENHOR fez no incidente em Baal-Peor. Ali, o SENHOR, seu Deus, destruiu todos aqueles que adoraram Baal, o deus de Peor.

[[v5-4-4]]

^<<v5-4-4,4>>^ Mas vocês, que foram fiéis ao SENHOR, seu Deus, estão hoje todos vivos.

[[v5-4-5]]

^<<v5-4-5,5>>^ "Vejam, agora eu lhes ensino estes decretos e estatutos conforme me ordenou o SENHOR, meu Deus, para que vocês os cumpram na terra em que estão prestes a entrar para tomar posse dela.

[[v5-4-6]]

^<<v5-4-6,6>>^ Obedeçam-lhes por completo, e assim demonstrarão sabedoria e inteligência às nações vizinhas. Quando elas ouvirem estes decretos, exclamarão: ‘Como é sábio e prudente o povo dessa grande nação!’.

[[v5-4-7]]

^<<v5-4-7,7>>^ Pois que grande nação tem um deus tão próximo de si como o SENHOR, nosso Deus, está próximo de nós sempre que o invocamos?

[[v5-4-8]]

^<<v5-4-8,8>>^ E que grande nação tem decretos e estatutos tão justos quanto este conjunto de leis que hoje lhes dou?

[[v5-4-9]]

^<<v5-4-9,9>>^ "Fiquem muito atentos! Cuidem para que não se esqueçam daquilo que viram com os próprios olhos. Não deixem que essas lembranças se apaguem de sua memória enquanto viverem. Passem-nas adiante a seus filhos e netos.

[[v5-4-10]]

^<<v5-4-10,10>>^ Nunca se esqueçam do dia em que estiveram diante do SENHOR, seu Deus, no monte Sinai, onde o SENHOR me disse: ‘Convoque o povo para que se apresente diante de mim, e eu os instruirei pessoalmente. Eles aprenderão a me temer enquanto viverem e ensinarão seus filhos a também me temer’.

[[v5-4-11]]

^<<v5-4-11,11>>^ "Vocês se aproximaram e ficaram ao pé do monte, enquanto o monte ardia em chamas que subiam até o céu. Ao mesmo tempo, o monte foi envolvido por nuvens negras e densa escuridão.

[[v5-4-12]]

^<<v5-4-12,12>>^ Então o SENHOR lhes falou do meio do fogo. Vocês ouviram o som de suas palavras, mas não viram sua forma; havia apenas uma voz.

[[v5-4-13]]

^<<v5-4-13,13>>^ Ele proclamou sua aliança, os dez mandamentos. Gravou-os em duas tábuas de pedra e ordenou que os cumprissem.

[[v5-4-14]]

^<<v5-4-14,14>>^ Foi naquela ocasião que o SENHOR me ordenou que lhes ensinasse seus decretos e estatutos, para que vocês os cumprissem na terra em que estão prestes a entrar para tomar posse dela."

[[v5-4-15]]

^<<v5-4-15,15>>^ "Tenham muito cuidado! No dia em que o SENHOR lhes falou do meio do fogo no monte Sinai, vocês não viram forma alguma.

[[v5-4-16]]

^<<v5-4-16,16>>^ Portanto, não se corrompam fazendo ídolos de qualquer forma, seja de homem ou de mulher,

[[v5-4-17]]

^<<v5-4-17,17>>^ de animal terrestre, de ave no céu,

[[v5-4-18]]

^<<v5-4-18,18>>^ de animal que rasteja pelo chão ou de peixe das profundezas do mar.

[[v5-4-19]]

^<<v5-4-19,19>>^ E, quando olharem para o céu e virem o sol, a lua e as estrelas, todo o exército do céu, não caiam na tentação de prostrar-se diante deles e adorá-los. O SENHOR, seu Deus, os deu a todos os povos da terra.

[[v5-4-20]]

^<<v5-4-20,20>>^ Lembrem-se de que o SENHOR os libertou do Egito, uma fornalha de fundir ferro, para torná-los seu povo e sua propriedade especial, como hoje se vê.

[[v5-4-21]]

^<<v5-4-21,21>>^ "E, no entanto, o SENHOR se irou contra mim por causa de vocês. Jurou que eu não atravessaria o rio Jordão para entrar na boa terra que o SENHOR, seu Deus, lhes dá como propriedade.

[[v5-4-22]]

^<<v5-4-22,22>>^ Vocês atravessarão o Jordão e tomarão posse dessa boa terra, mas eu não. Morrerei aqui, deste lado do rio.

[[v5-4-23]]

^<<v5-4-23,23>>^ Portanto, tenham cuidado para não se esquecerem da aliança que o SENHOR, seu Deus, fez com vocês. Não façam ídolos de qualquer aparência ou forma, pois o SENHOR, seu Deus, proibiu isso.

[[v5-4-24]]

^<<v5-4-24,24>>^ O SENHOR, seu Deus, é fogo devorador; é Deus zeloso.

[[v5-4-25]]

^<<v5-4-25,25>>^ "No futuro, quando vocês tiverem filhos e netos e já estiverem habitando na terra há muito tempo, não se corrompam fazendo ídolos de qualquer forma. Isso é mau aos olhos do SENHOR, seu Deus, e provocará sua ira.

[[v5-4-26]]

^<<v5-4-26,26>>^ "Hoje, apelo para o céu e para a terra como testemunhas contra vocês. Se quebrarem a aliança, desaparecerão rapidamente da terra da qual tomarão posse depois de atravessar o Jordão. Habitarão ali por pouco tempo e depois serão totalmente destruídos.

[[v5-4-27]]

^<<v5-4-27,27>>^ O SENHOR os dispersará entre as nações, onde apenas alguns de vocês sobreviverão.

[[v5-4-28]]

^<<v5-4-28,28>>^ Lá, em terra estrangeira, adorarão deuses de madeira e pedra, feitos por mãos humanas, deuses que não podem ver, nem ouvir, nem comer, nem cheirar.

[[v5-4-29]]

^<<v5-4-29,29>>^ De lá, porém, vocês buscarão o SENHOR, seu Deus, outra vez. E, se o buscarem de todo o coração e de toda a alma, o encontrarão.

[[v5-4-30]]

^<<v5-4-30,30>>^ "No futuro distante, quando estiverem sofrendo todas essas coisas, finalmente voltarão para o SENHOR, seu Deus, e ouvirão o que ele lhes diz.

[[v5-4-31]]

^<<v5-4-31,31>>^ Pois o SENHOR, seu Deus, é Deus misericordioso; não os abandonará nem os destruirá, nem se esquecerá da aliança solene que fez com seus antepassados."

[[v5-4-32]]

^<<v5-4-32,32>>^ "Investiguem toda a história, desde o dia em que Deus criou os seres humanos sobre a terra até agora, e procurem desde uma extremidade do céu até a outra. Alguma vez se viu ou ouviu coisa tão grandiosa como esta?

[[v5-4-33]]

^<<v5-4-33,33>>^ Algum outro povo ouviu a voz de Deus falar do meio do fogo, como vocês ouviram, e sobreviveu?

[[v5-4-34]]

^<<v5-4-34,34>>^ Algum outro deus já tentou tirar uma nação do meio de outra nação e tomá-la para si com provas, sinais, maravilhas, guerra, mão forte, braço poderoso e atos temíveis? E, no entanto, foi isso que o SENHOR, seu Deus, fez por vocês no Egito, bem diante de seus olhos!

[[v5-4-35]]

^<<v5-4-35,35>>^ "Ele lhes mostrou todas essas coisas para que vocês soubessem que o SENHOR é Deus, e não há outro além dele.

[[v5-4-36]]

^<<v5-4-36,36>>^ Permitiu que vocês ouvissem sua voz que vinha do céu para instruí-los e permitiu que vissem seu grande fogo na terra para falar-lhes do meio dele.

[[v5-4-37]]

^<<v5-4-37,37>>^ Porque amou seus antepassados, ele escolheu abençoar vocês, os descendentes, e ele mesmo os tirou do Egito com grande poder.

[[v5-4-38]]

^<<v5-4-38,38>>^ Ele expulsou nações muito maiores e mais poderosas que vocês para estabelecê-los na terra delas e entregá-la a vocês como herança, como hoje se vê.

[[v5-4-39]]

^<<v5-4-39,39>>^ "Portanto, reconheçam este fato e guardem-no firmemente na memória: O SENHOR é Deus nos céus e na terra, e não há outro além dele.

[[v5-4-40]]

^<<v5-4-40,40>>^ Se obedecerem a todos os decretos e mandamentos que hoje lhes dou, tudo irá bem com vocês e seus filhos, e vocês terão vida longa na terra que o SENHOR, seu Deus, lhes dá para sempre".

[[v5-4-41]]

^<<v5-4-41,41>>^ Então Moisés separou três cidades de refúgio do lado leste do rio Jordão.

[[v5-4-42]]

^<<v5-4-42,42>>^ Assim, alguém que tivesse matado outra pessoa acidentalmente, sem hostilidade anterior, poderia fugir para uma dessas cidades e viver em segurança.

[[v5-4-43]]

^<<v5-4-43,43>>^ Estas eram as cidades: Bezer, no planalto do deserto, para a tribo de Rúben; Ramote, em Gileade, para a tribo de Gade; Golã, em Basã, para a tribo de Manassés.

[[v5-4-44]]

^<<v5-4-44,44>>^ Esta é a lei que Moisés apresentou ao povo de Israel.

[[v5-4-45]]

^<<v5-4-45,45>>^ Estes são os preceitos, decretos e estatutos que Moisés deu aos israelitas quando saíram do Egito,

[[v5-4-46]]

^<<v5-4-46,46>>^ enquanto estavam acampados no vale junto a Bete-Peor, do lado leste do Jordão. (Em outros tempos, os amorreus ocuparam essa terra durante o reinado de Seom, que vivia em Hesbom. Mas, quando saíram do Egito, Moisés e os israelitas aniquilaram esse rei e seu povo.

[[v5-4-47]]

^<<v5-4-47,47>>^ Os israelitas tomaram posse do território de Seom e do território de Ogue, rei de Basã, os dois reis dos amorreus que viviam a leste do Jordão.

[[v5-4-48]]

^<<v5-4-48,48>>^ Conquistaram toda a região, desde Aroer, na beira do vale de Arnom, até o monte Siriom, também chamado de Hermom.

[[v5-4-49]]

^<<v5-4-49,49>>^ Conquistaram também a margem leste do rio Jordão até o mar Morto, ao sul, abaixo das encostas do monte Pisga.)

'''

xref:005-deuteronomio/005-deuteronomio-003.adoc#v5-3-0[&#60; Capítulo Anterior] | <<v5-4-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-005.adoc#v5-5-0[Próximo Capítulo &#62;]