include::./index.adoc[]

[[v5-8-0]]
=== Deuteronômio, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v5-8-1]]

^<<v5-8-1,1>>^ "Obedeçam cuidadosamente a todos os mandamentos que hoje lhes dou. Assim, vocês viverão e se multiplicarão, e entrarão e tomarão posse da terra que o SENHOR jurou dar a seus antepassados.

[[v5-8-2]]

^<<v5-8-2,2>>^ Lembrem-se de como o SENHOR, seu Deus, os guiou pelo deserto estes quarenta anos, humilhando-os e pondo à prova seu caráter, para ver se vocês obedeceriam ou não a seus mandamentos.

[[v5-8-3]]

^<<v5-8-3,3>>^ Sim, ele os humilhou, permitindo que tivessem fome. Em seguida, ele os sustentou com maná, um alimento que nem vocês nem seus antepassados conheciam, a fim de lhes ensinar que as pessoas não vivem só de pão, mas de toda palavra que vem da boca do SENHOR.

[[v5-8-4]]

^<<v5-8-4,4>>^ Ao longo de todos estes quarenta anos, suas roupas não se gastaram e seus pés não incharam nem criaram bolhas.

[[v5-8-5]]

^<<v5-8-5,5>>^ Pensem nisto: assim como o pai disciplina o filho, também o SENHOR, seu Deus, disciplina vocês para o seu próprio bem.

[[v5-8-6]]

^<<v5-8-6,6>>^ "Portanto, obedeçam aos mandamentos do SENHOR, seu Deus, andando em seus caminhos e temendo a ele.

[[v5-8-7]]

^<<v5-8-7,7>>^ Pois o SENHOR, seu Deus, está levando vocês para uma terra boa, com riachos e tanques de água, com fontes que jorram nos vales e colinas.

[[v5-8-8]]

^<<v5-8-8,8>>^ É uma terra de trigo e cevada, com vinhedos, figueiras e romãzeiras, com azeite e mel.

[[v5-8-9]]

^<<v5-8-9,9>>^ É uma terra onde há muito alimento e não falta coisa alguma. É uma terra onde há ferro nas rochas e cobre em grande quantidade nos montes.

[[v5-8-10]]

^<<v5-8-10,10>>^ Quando tiverem comido até se saciarem, lembrem-se de louvar o SENHOR, seu Deus, pela boa terra que ele lhes deu.

[[v5-8-11]]

^<<v5-8-11,11>>^ "Tenham cuidado para que, em meio à fartura, não se esqueçam do SENHOR, seu Deus, e desobedeçam aos mandamentos, estatutos e decretos que hoje lhes dou.

[[v5-8-12]]

^<<v5-8-12,12>>^ Quando ficarem satisfeitos e forem prósperos, quando tiverem construído belas casas onde morar,

[[v5-8-13]]

^<<v5-8-13,13>>^ e quando seus rebanhos tiverem se tornado numerosos e sua prata e seu ouro tiverem se multiplicado junto com todos os seus bens, tenham cuidado!

[[v5-8-14]]

^<<v5-8-14,14>>^ Não se tornem orgulhosos e não se esqueçam do SENHOR, seu Deus, que os libertou da escravidão na terra do Egito.

[[v5-8-15]]

^<<v5-8-15,15>>^ Ele os guiou pelo deserto imenso e assustador, cheio de serpentes venenosas e escorpiões, uma terra quente e seca. Ele lhes deu água da rocha.

[[v5-8-16]]

^<<v5-8-16,16>>^ Sustentou-os no deserto com maná, alimento que seus antepassados não conheciam, para humilhá-los e prová-los para o seu próprio bem.

[[v5-8-17]]

^<<v5-8-17,17>>^ Fez tudo isso para que vocês jamais viessem a pensar: ‘Conquistei toda esta riqueza com minha própria força e capacidade’.

[[v5-8-18]]

^<<v5-8-18,18>>^ Lembrem-se do SENHOR, seu Deus. É ele que lhes dá força para serem bem-sucedidos, a fim de confirmar a aliança solene que fez com seus antepassados, como hoje se vê.

[[v5-8-19]]

^<<v5-8-19,19>>^ "Uma coisa, porém, eu lhes garanto: se vocês se esquecerem do SENHOR, seu Deus, e seguirem outros deuses, adorando-os e curvando-se diante deles, certamente serão destruídos.

[[v5-8-20]]

^<<v5-8-20,20>>^ Assim como o SENHOR destruiu outras nações em seu caminho, vocês também serão destruídos caso se recusem a obedecer ao SENHOR, seu Deus."

'''

xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[&#60; Capítulo Anterior] | <<v5-8-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[Próximo Capítulo &#62;]