include::./index.adoc[]

[[v5-7-0]]
=== Deuteronômio, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v5-7-1]]

^<<v5-7-1,1>>^ "Quando o SENHOR, seu Deus, os fizer entrar na terra que vocês em breve possuirão, ele removerá de diante de vocês muitas nações: os hititas, os girgaseus, os amorreus, os cananeus, os ferezeus, os heveus e os jebuseus. Essas sete nações são mais numerosas e mais poderosas que vocês.

[[v5-7-2]]

^<<v5-7-2,2>>^ Quando o SENHOR, seu Deus, entregá-las em suas mãos e vocês as conquistarem, destruam-nas completamente. Não façam tratados nem tenham pena delas.

[[v5-7-3]]

^<<v5-7-3,3>>^ Não se unam a elas por meio de casamentos. Não deem suas filhas em casamento aos filhos delas, nem tomem as filhas delas como esposas para seus filhos,

[[v5-7-4]]

^<<v5-7-4,4>>^ pois farão seus filhos se afastarem de mim para adorar outros deuses. Então a ira do SENHOR arderá contra vocês e os destruirá rapidamente.

[[v5-7-5]]

^<<v5-7-5,5>>^ Portanto, façam o seguinte: quebrem seus altares idólatras e despedacem suas colunas sagradas. Cortem os postes de Aserá e queimem seus ídolos.

[[v5-7-6]]

^<<v5-7-6,6>>^ Vocês são um povo santo que pertence ao SENHOR, seu Deus. Dentre todos os povos da terra, o SENHOR, seu Deus, os escolheu para serem sua propriedade especial.

[[v5-7-7]]

^<<v5-7-7,7>>^ "O SENHOR não se afeiçoou a vocês nem os escolheu por serem mais numerosos que outras nações, pois vocês eram a menor de todas as nações!

[[v5-7-8]]

^<<v5-7-8,8>>^ Antes, foi simplesmente porque o SENHOR os amou e foi fiel ao juramento que fez a seus antepassados. Por isso o SENHOR os libertou com mão forte da escravidão e da opressão do faraó, rei do Egito.

[[v5-7-9]]

^<<v5-7-9,9>>^ Reconheçam, portanto, que o SENHOR, seu Deus, é, de fato, Deus. Ele é o Deus fiel que cumpre por mil gerações sua aliança de amor com todos que o amam e obedecem a seus mandamentos.

[[v5-7-10]]

^<<v5-7-10,10>>^ Não hesita, porém, em castigar e destruir aqueles que o rejeitam.

[[v5-7-11]]

^<<v5-7-11,11>>^ Assim, obedeçam a todos estes mandamentos, decretos e estatutos que hoje lhes dou.

[[v5-7-12]]

^<<v5-7-12,12>>^ "Se vocês guardarem estes estatutos e os cumprirem com cuidado, o SENHOR, seu Deus, cumprirá sua aliança de amor com vocês, como prometeu sob juramento a seus antepassados.

[[v5-7-13]]

^<<v5-7-13,13>>^ Ele os amará, os abençoará e os fará crescer, tornando férteis seus filhos, sua terra e seus animais. Quando chegarem à terra que ele jurou dar a seus antepassados, vocês terão produção farta de cereais, vinho novo e azeite, e também grandes rebanhos de bois e ovelhas.

[[v5-7-14]]

^<<v5-7-14,14>>^ Vocês serão mais abençoados que todas as nações da terra. Nenhum de seus homens ou mulheres será estéril, e todos os seus animais darão cria.

[[v5-7-15]]

^<<v5-7-15,15>>^ O SENHOR os protegerá de toda enfermidade. Não permitirá que sofram as doenças terríveis que conheceram no Egito; em vez disso, ele as enviará sobre todos os seus inimigos!

[[v5-7-16]]

^<<v5-7-16,16>>^ "Destruam todas as nações que o SENHOR, seu Deus, lhes entregar. Não tenham pena delas nem adorem seus deuses, pois isso seria uma armadilha para vocês.

[[v5-7-17]]

^<<v5-7-17,17>>^ Talvez vocês se perguntem: ‘Como poderemos conquistar essas nações que são muito mais numerosas que nós?’.

[[v5-7-18]]

^<<v5-7-18,18>>^ Não tenham medo delas! Lembrem-se apenas daquilo que o SENHOR, seu Deus, fez ao faraó e a toda a terra do Egito.

[[v5-7-19]]

^<<v5-7-19,19>>^ Lembrem-se das grandes demonstrações de poder que o SENHOR, seu Deus, enviou contra eles. Vocês viram com os próprios olhos! E lembrem-se dos sinais e maravilhas, da mão forte e do braço poderoso com os quais ele os tirou do Egito. O SENHOR, seu Deus, usará esse mesmo poder contra todos os povos que vocês temem.

[[v5-7-20]]

^<<v5-7-20,20>>^ Sim, o SENHOR, seu Deus, enviará terror para expulsar os poucos sobreviventes que ainda estiverem escondidos de vocês!

[[v5-7-21]]

^<<v5-7-21,21>>^ "Não tenham medo dessas nações, pois o SENHOR, seu Deus, está entre vocês, e é Deus grande e temível.

[[v5-7-22]]

^<<v5-7-22,22>>^ O SENHOR, seu Deus, expulsará essas nações de diante de vocês, pouco a pouco. Vocês não as eliminarão de uma vez, pois, se assim fosse, os animais selvagens se multiplicariam rápido demais e os ameaçariam.

[[v5-7-23]]

^<<v5-7-23,23>>^ Mas o SENHOR, seu Deus, as entregará a vocês. Ele as lançará em total confusão, até que sejam destruídas.

[[v5-7-24]]

^<<v5-7-24,24>>^ Entregará os reis dessas nações em suas mãos, e vocês apagarão o nome deles da face da terra. Ninguém poderá lhes resistir, e vocês destruirão a todos.

[[v5-7-25]]

^<<v5-7-25,25>>^ "Queimem os ídolos das nações no fogo e não cobicem a prata nem o ouro que os revestem. Não tomem nenhum desses metais para si, pois isso seria uma armadilha para vocês; é algo detestável para o SENHOR, seu Deus.

[[v5-7-26]]

^<<v5-7-26,26>>^ Não levem para dentro de suas casas objeto algum que seja detestável, pois, como eles, vocês serão destruídos. Considerem essas coisas absolutamente detestáveis, pois estão separadas para a destruição."

'''

xref:005-deuteronomio/005-deuteronomio-006.adoc#v5-6-0[&#60; Capítulo Anterior] | <<v5-7-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-008.adoc#v5-8-0[Próximo Capítulo &#62;]