include::./index.adoc[]

[[v5-28-0]]
=== Deuteronômio, 28
// nvt ?, NVT - Nova Versão Transformadora

[[v5-28-1]]

^<<v5-28-1,1>>^ "Se vocês obedecerem em tudo ao SENHOR, seu Deus, e cumprirem fielmente todos estes mandamentos que hoje lhes dou, o SENHOR, seu Deus, os colocará muito acima de todas as nações da terra.

[[v5-28-2]]

^<<v5-28-2,2>>^ Se obedecerem ao SENHOR, seu Deus, vocês receberão as seguintes bênçãos:

[[v5-28-3]]

^<<v5-28-3,3>>^ Suas cidades e seus campos serão abençoados.

[[v5-28-4]]

^<<v5-28-4,4>>^ Seus filhos e suas colheitas serão abençoados. As crias de seu gado e de seus rebanhos serão abençoadas.

[[v5-28-5]]

^<<v5-28-5,5>>^ Seus cestos de frutos e tigelas de amassar pão serão abençoados.

[[v5-28-6]]

^<<v5-28-6,6>>^ A todo lugar que forem e em tudo que fizerem, serão abençoados.

[[v5-28-7]]

^<<v5-28-7,7>>^ "O SENHOR derrotará seus inimigos quando eles os atacarem. Eles virão contra vocês de uma direção, mas serão dispersados em sete direções.

[[v5-28-8]]

^<<v5-28-8,8>>^ "O SENHOR lhes garantirá bênção em tudo que fizerem e encherá seus celeiros de cereais. O SENHOR, seu Deus, os abençoará na terra que ele lhes dá.

[[v5-28-9]]

^<<v5-28-9,9>>^ "Se obedecerem aos mandamentos do SENHOR, seu Deus, e andarem em seus caminhos, o SENHOR os constituirá como seu povo santo, conforme prometeu sob juramento.

[[v5-28-10]]

^<<v5-28-10,10>>^ Assim, todas as nações da terra verão que vocês são um povo que o SENHOR tomou para si e os temerão.

[[v5-28-11]]

^<<v5-28-11,11>>^ "O SENHOR lhes dará prosperidade na terra que ele jurou a seus antepassados que daria a vocês, e os abençoará com muitos filhos, rebanhos numerosos e colheitas fartas.

[[v5-28-12]]

^<<v5-28-12,12>>^ No tempo certo, o SENHOR enviará chuvas de seu rico tesouro no céu e abençoará todo o trabalho que realizarem. Vocês emprestarão a muitas nações, mas jamais precisarão tomar emprestado delas.

[[v5-28-13]]

^<<v5-28-13,13>>^ Se derem ouvidos a estes mandamentos que hoje lhes dou e se os cumprirem fielmente, o SENHOR os fará cabeça, e não cauda, e vocês estarão sempre por cima, e nunca por baixo.

[[v5-28-14]]

^<<v5-28-14,14>>^ Não se desviem, por menos que seja, de nenhum dos mandamentos que hoje lhes dou, e não sigam outros deuses nem os adorem."

[[v5-28-15]]

^<<v5-28-15,15>>^ "Mas, se vocês se recusarem a dar ouvidos ao SENHOR, seu Deus, e não cumprirem todos os mandamentos e decretos que hoje lhes dou, as seguintes maldições cairão sobre vocês e os atingirão:

[[v5-28-16]]

^<<v5-28-16,16>>^ Suas cidades e seus campos serão amaldiçoados.

[[v5-28-17]]

^<<v5-28-17,17>>^ Seus cestos de frutos e suas tigelas de amassar pão serão amaldiçoados.

[[v5-28-18]]

^<<v5-28-18,18>>^ Seus filhos e suas colheitas serão amaldiçoados. As crias de seu gado e de seus rebanhos serão amaldiçoadas.

[[v5-28-19]]

^<<v5-28-19,19>>^ A todo lugar que forem e em tudo que fizerem, serão amaldiçoados.

[[v5-28-20]]

^<<v5-28-20,20>>^ "O próprio SENHOR enviará maldições, confusão e frustração em tudo que fizerem, até que, por fim, vocês sejam completamente destruídos por terem praticado o mal e me abandonado.

[[v5-28-21]]

^<<v5-28-21,21>>^ O SENHOR os afligirá com pragas, até fazê-los desaparecer da terra em que estão prestes a entrar para tomar posse.

[[v5-28-22]]

^<<v5-28-22,22>>^ O SENHOR os ferirá com doenças debilitantes, com febres e inflamações, com calor ardente e secas, com ferrugem e mofo. Essas calamidades os perseguirão até que vocês morram.

[[v5-28-23]]

^<<v5-28-23,23>>^ O céu sobre sua cabeça será tão duro quanto o bronze, e a terra debaixo de vocês será tão impenetrável quanto o ferro.

[[v5-28-24]]

^<<v5-28-24,24>>^ O SENHOR transformará em pó a chuva que rega sua terra, e cinzas cairão do céu até que vocês sejam destruídos.

[[v5-28-25]]

^<<v5-28-25,25>>^ "O SENHOR fará seus inimigos os derrotarem. Vocês os atacarão de uma direção, mas serão dispersados em sete direções. Serão motivo de horror para todos os reinos da terra.

[[v5-28-26]]

^<<v5-28-26,26>>^ Seus cadáveres serão alimento para as aves do céu e para os animais selvagens, e não haverá ninguém para enxotá-los.

[[v5-28-27]]

^<<v5-28-27,27>>^ "O SENHOR os afligirá com as feridas purulentas do Egito e com tumores, sarna e coceira incuráveis.

[[v5-28-28]]

^<<v5-28-28,28>>^ O SENHOR os castigará com loucura, cegueira e pânico.

[[v5-28-29]]

^<<v5-28-29,29>>^ Andarão tateando em plena luz do dia, como cegos na escuridão, mas não encontrarão o caminho. Serão oprimidos e roubados continuamente, e ninguém virá para socorrê-los.

[[v5-28-30]]

^<<v5-28-30,30>>^ "Você ficará noivo de uma mulher, mas outro homem dormirá com ela. Construirá uma casa, mas outra pessoa morará nela. Plantará um vinhedo, mas não aproveitará seus frutos.

[[v5-28-31]]

^<<v5-28-31,31>>^ Seu boi será abatido diante de seus olhos, mas você não provará um pedaço sequer da carne. Seu jumento lhe será tomado e não será devolvido. Suas ovelhas serão entregues a seus inimigos, e não haverá quem o ajude.

[[v5-28-32]]

^<<v5-28-32,32>>^ Você verá seus filhos e filhas serem levados embora como escravos. Sentirá intensa saudade deles, mas nada poderá fazer.

[[v5-28-33]]

^<<v5-28-33,33>>^ Uma nação estrangeira desconhecida consumirá as colheitas que vocês trabalharam arduamente para produzir. Vocês sofrerão opressão constante e serão tratados com crueldade.

[[v5-28-34]]

^<<v5-28-34,34>>^ Quando virem as tragédias ao seu redor, acabarão enlouquecendo.

[[v5-28-35]]

^<<v5-28-35,35>>^ O SENHOR lhes cobrirá os joelhos e as pernas com feridas incuráveis. Terão feridas da cabeça aos pés.

[[v5-28-36]]

^<<v5-28-36,36>>^ "O SENHOR enviará vocês e seu rei para o exílio numa nação que vocês e seus antepassados não conheceram. Ali, adorarão deuses de madeira e de pedra!

[[v5-28-37]]

^<<v5-28-37,37>>^ Serão motivo de horror, de ridículo e de zombaria entre as nações para as quais o SENHOR os enviar.

[[v5-28-38]]

^<<v5-28-38,38>>^ "Semearão muito, mas colherão pouco, pois os gafanhotos devorarão suas plantações.

[[v5-28-39]]

^<<v5-28-39,39>>^ Plantarão vinhedos e cuidarão deles, mas não beberão o vinho nem comerão as uvas, pois vermes devorarão as videiras.

[[v5-28-40]]

^<<v5-28-40,40>>^ Cultivarão oliveiras em todo o seu território, mas nunca usarão azeite, pois os frutos cairão antes de amadurecer.

[[v5-28-41]]

^<<v5-28-41,41>>^ Terão filhos e filhas, mas os perderão, pois eles serão levados para o cativeiro.

[[v5-28-42]]

^<<v5-28-42,42>>^ Enxames de insetos destruirão suas árvores e suas plantações.

[[v5-28-43]]

^<<v5-28-43,43>>^ "Os estrangeiros que vivem entre vocês se tornarão cada vez mais fortes, enquanto vocês se tornarão cada vez mais fracos.

[[v5-28-44]]

^<<v5-28-44,44>>^ Eles lhes emprestarão dinheiro, mas vocês não emprestarão a eles. Eles serão a cabeça, e vocês serão a cauda!

[[v5-28-45]]

^<<v5-28-45,45>>^ "Se vocês se recusarem a dar ouvidos ao SENHOR, seu Deus, e a obedecer aos mandamentos e decretos que ele lhes deu, todas estas maldições os perseguirão e os alcançarão até que sejam destruídos.

[[v5-28-46]]

^<<v5-28-46,46>>^ Estes horrores servirão de sinal e advertência para vocês e seus descendentes para sempre.

[[v5-28-47]]

^<<v5-28-47,47>>^ Se não servirem ao SENHOR, seu Deus, com alegria e entusiasmo pelos muitos benefícios que receberam,

[[v5-28-48]]

^<<v5-28-48,48>>^ servirão aos inimigos que o SENHOR enviará contra vocês. Ficarão famintos, sedentos, despidos e desprovidos de tudo. O SENHOR porá um jugo de ferro sobre seu pescoço e os oprimirá severamente até que os tenha destruído.

[[v5-28-49]]

^<<v5-28-49,49>>^ "Dos confins da terra, o SENHOR trará contra vocês uma nação distante que se lançará sobre vocês como um abutre. Será uma nação cuja língua vocês não compreendem,

[[v5-28-50]]

^<<v5-28-50,50>>^ povo feroz e cruel, que não tem respeito pelos idosos nem pena dos jovens.

[[v5-28-51]]

^<<v5-28-51,51>>^ Os exércitos deles devorarão seus animais e colheitas, e vocês serão destruídos. Não deixarão coisa alguma dos seus cereais, nem vinho novo, azeite, bezerros ou cordeiros, e vocês morrerão de fome.

[[v5-28-52]]

^<<v5-28-52,52>>^ Atacarão suas cidades até derrubarem todos os muros fortificados de sua terra, as muralhas nas quais vocês confiavam como proteção. Atacarão todas as cidades da terra que o SENHOR, seu Deus, lhes dá.

[[v5-28-53]]

^<<v5-28-53,53>>^ "O cerco e a grande aflição que o ataque inimigo causará serão tão terríveis que vocês comerão a carne de seus próprios filhos e filhas, que o SENHOR, seu Deus, lhes deu.

[[v5-28-54]]

^<<v5-28-54,54>>^ Até o homem de coração mais gentil em seu meio não terá pena do próprio irmão, da esposa amada e dos filhos que sobreviverem.

[[v5-28-55]]

^<<v5-28-55,55>>^ Ele se recusará a dividir com eles a carne que estiver devorando, a carne de um dos próprios filhos, pois não sobrará outra coisa para ele comer durante o cerco e a grande aflição que o inimigo trará sobre todas as suas cidades.

[[v5-28-56]]

^<<v5-28-56,56>>^ A mulher de coração mais gentil entre vocês, tão delicada que nem sequer tocaria o chão com o pé, será mesquinha com o marido a quem ama e com o próprio filho ou filha.

[[v5-28-57]]

^<<v5-28-57,57>>^ Esconderá deles a placenta e o bebê recém-nascido que ela deu à luz para comê-los sozinha em segredo. Não terá outra coisa para comer durante o cerco e a grande aflição que o inimigo trará sobre todas as suas cidades.

[[v5-28-58]]

^<<v5-28-58,58>>^ "Se vocês se recusarem a obedecer a todos os termos desta lei escritos neste livro e se não temerem o nome glorioso e terrível do SENHOR, seu Deus,

[[v5-28-59]]

^<<v5-28-59,59>>^ o SENHOR oprimirá vocês e seus filhos com pragas indescritíveis. Serão pragas intensas e sem alívio, doenças agonizantes e insuportáveis.

[[v5-28-60]]

^<<v5-28-60,60>>^ Ele os afligirá com todas as doenças do Egito, que vocês temiam tanto, e não terão alívio.

[[v5-28-61]]

^<<v5-28-61,61>>^ O SENHOR os afligirá com todas as enfermidades e pragas que existem, mesmo aquelas que não são mencionadas neste Livro da Lei, até que sejam destruídos.

[[v5-28-62]]

^<<v5-28-62,62>>^ Ainda que se tornem tão numerosos quanto as estrelas do céu, poucos restarão, pois não deram ouvidos ao SENHOR, seu Deus.

[[v5-28-63]]

^<<v5-28-63,63>>^ "Assim como o SENHOR teve grande prazer em fazê-los prosperar e se multiplicar, também terá prazer em destruí-los. Vocês serão arrancados da terra em que estão prestes a entrar para tomar posse.

[[v5-28-64]]

^<<v5-28-64,64>>^ O SENHOR os espalhará entre todas as nações, de uma extremidade à outra do mundo. Ali, adorarão deuses estrangeiros que nem vocês nem seus antepassados conheceram, deuses de madeira e pedra.

[[v5-28-65]]

^<<v5-28-65,65>>^ Não encontrarão paz nem lugar de descanso entre essas nações. O SENHOR fará seu coração estremecer, sua vista falhar e sua alma desanimar.

[[v5-28-66]]

^<<v5-28-66,66>>^ Sua vida estará sempre por um fio. Passarão os dias e as noites com medo, sem ter certeza se sobreviverão.

[[v5-28-67]]

^<<v5-28-67,67>>^ Pela manhã dirão: ‘Quem nos dera já fosse noite!’, e à noite: ‘Quem nos dera já fosse dia!’. Pois se encherão de pavor com os horrores que verão ao seu redor.

[[v5-28-68]]

^<<v5-28-68,68>>^ Então o SENHOR os mandará em navios de volta para o Egito, o lugar que eu prometi que nunca mais veriam. Lá, tentarão vender a si mesmos como escravos para seus inimigos, mas ninguém os comprará".

'''

xref:005-deuteronomio/005-deuteronomio-027.adoc#v5-27-0[&#60; Capítulo Anterior] | <<v5-28-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-029.adoc#v5-29-0[Próximo Capítulo &#62;]