include::./index.adoc[]

[[v5-25-0]]
=== Deuteronômio, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v5-25-1]]

^<<v5-25-1,1>>^ "Quando duas pessoas brigarem e o caso chegar a um tribunal, os juízes declararão que uma pessoa tem razão e a outra está errada.

[[v5-25-2]]

^<<v5-25-2,2>>^ Se a pessoa que está errada for sentenciada a receber açoites, o juiz ordenará que ela se deite e seja açoitada na presença dele, com um número de açoites proporcional ao crime.

[[v5-25-3]]

^<<v5-25-3,3>>^ Jamais ultrapassem, porém, quarenta açoites; mais que quarenta açoites seria uma humilhação pública para seu irmão israelita.

[[v5-25-4]]

^<<v5-25-4,4>>^ "Não amordacem o boi para impedir que ele coma enquanto debulha os cereais.

[[v5-25-5]]

^<<v5-25-5,5>>^ "Se dois irmãos estiverem morando juntos na mesma propriedade e um deles morrer sem deixar filhos, a viúva não se casará com alguém de fora da família. O irmão de seu marido se casará com ela, e eles terão relações sexuais. Desse modo, ele cumprirá os deveres de cunhado.

[[v5-25-6]]

^<<v5-25-6,6>>^ O primeiro filho que ela tiver com ele será considerado filho do irmão falecido, para que seu nome não seja esquecido em Israel.

[[v5-25-7]]

^<<v5-25-7,7>>^ "Se, contudo, o homem se recusar a casar-se com a viúva de seu irmão, ela irá até a porta da cidade e dirá às autoridades ali reunidas: ‘O irmão de meu falecido esposo se recusa a preservar o nome do irmão em Israel. Não quer cumprir os deveres de cunhado, casando-se comigo’.

[[v5-25-8]]

^<<v5-25-8,8>>^ As autoridades da cidade o convocarão e conversarão com ele. Se, ainda assim, ele insistir e disser: ‘Não quero me casar com ela’,

[[v5-25-9]]

^<<v5-25-9,9>>^ a viúva se aproximará do homem na presença das autoridades, tirará a sandália do pé dele e cuspirá em seu rosto. Em seguida, ela declarará: ‘É isso que acontece com o homem que se recusa a dar filhos para seu irmão’.

[[v5-25-10]]

^<<v5-25-10,10>>^ Desse dia em diante, a família dele será chamada em Israel de ‘família do descalçado’.

[[v5-25-11]]

^<<v5-25-11,11>>^ "Se dois israelitas brigarem e a esposa de um deles, na tentativa de livrar o marido de quem o agride, agarrar os órgãos genitais do outro homem,

[[v5-25-12]]

^<<v5-25-12,12>>^ cortem a mão da mulher. Não tenham pena dela.

[[v5-25-13]]

^<<v5-25-13,13>>^ "Quando pesarem mercadorias, usem balanças precisas.

[[v5-25-14]]

^<<v5-25-14,14>>^ Usem também medidas completas e justas.

[[v5-25-15]]

^<<v5-25-15,15>>^ Sim, usem sempre pesos e medidas exatos e justos, para que tenham vida longa na terra que o SENHOR, seu Deus, lhes dá.

[[v5-25-16]]

^<<v5-25-16,16>>^ Quem engana com pesos e medidas desonestos é detestável ao SENHOR, seu Deus.

[[v5-25-17]]

^<<v5-25-17,17>>^ "Nunca se esqueçam daquilo que os amalequitas lhes fizeram quando vocês saíram do Egito.

[[v5-25-18]]

^<<v5-25-18,18>>^ Eles os atacaram quando vocês estavam cansados e esgotados e feriram mortalmente os mais fracos que ficaram para trás. Não temeram a Deus.

[[v5-25-19]]

^<<v5-25-19,19>>^ Portanto, quando o SENHOR, seu Deus, lhes proporcionar descanso de todos os seus inimigos na terra que ele lhes dá como herança, destruam os amalequitas e apaguem a memória deles de debaixo do céu. Jamais se esqueçam disso!"

'''

xref:005-deuteronomio/005-deuteronomio-024.adoc#v5-24-0[&#60; Capítulo Anterior] | <<v5-25-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-026.adoc#v5-26-0[Próximo Capítulo &#62;]