include::./index.adoc[]

[[v5-27-0]]
=== Deuteronômio, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v5-27-1]]

^<<v5-27-1,1>>^ Então Moisés, acompanhado dos líderes de Israel, deu a seguinte ordem ao povo: "Obedeçam a todos estes mandamentos que hoje lhes dou.

[[v5-27-2]]

^<<v5-27-2,2>>^ Quando atravessarem o rio Jordão e entrarem na terra que o SENHOR, seu Deus, lhes dá, levantem pedras grandes e pintem-nas com cal.

[[v5-27-3]]

^<<v5-27-3,3>>^ Escrevam nelas todos os termos desta lei quando atravessarem o rio para entrar na terra que o SENHOR, seu Deus, lhes dá, uma terra que produz leite e mel com fartura, conforme lhes prometeu o SENHOR, o Deus de seus antepassados.

[[v5-27-4]]

^<<v5-27-4,4>>^ Depois de atravessarem o Jordão, levantem essas pedras pintadas de cal no monte Ebal, como hoje lhes ordeno.

[[v5-27-5]]

^<<v5-27-5,5>>^ "Construam ali um altar para o SENHOR, seu Deus, usando pedras inteiras, em sua forma natural. Não alterem a forma das pedras com ferramenta de ferro.

[[v5-27-6]]

^<<v5-27-6,6>>^ Construam o altar com pedras que não foram cortadas e usem-no para oferecer holocaustos ao SENHOR, seu Deus.

[[v5-27-7]]

^<<v5-27-7,7>>^ Apresentem também sacrifícios de ofertas de paz e celebrem, comendo e alegrando-se na presença do SENHOR, seu Deus.

[[v5-27-8]]

^<<v5-27-8,8>>^ Escrevam de forma bem visível todos os termos desta lei nas pedras pintadas de cal".

[[v5-27-9]]

^<<v5-27-9,9>>^ Em seguida, Moisés e os sacerdotes levitas disseram a todo o Israel: "Faça silêncio e ouça, ó Israel! Hoje você se tornou o povo do SENHOR, seu Deus.

[[v5-27-10]]

^<<v5-27-10,10>>^ Obedeça, portanto, ao SENHOR, seu Deus, cumprindo todos estes mandamentos e decretos que hoje lhe dou".

[[v5-27-11]]

^<<v5-27-11,11>>^ No mesmo dia, Moisés deu ao povo a seguinte ordem:

[[v5-27-12]]

^<<v5-27-12,12>>^ "Quando atravessarem o rio Jordão, as tribos de Simeão, Levi, Judá, Issacar, José e Benjamim ficarão no monte Gerizim, de onde proclamarão uma bênção sobre o povo.

[[v5-27-13]]

^<<v5-27-13,13>>^ As tribos de Rúben, Gade, Aser, Zebulom, Dã e Naftali ficarão no monte Ebal, de onde proclamarão uma maldição.

[[v5-27-14]]

^<<v5-27-14,14>>^ "Então os levitas dirão em alta voz a todo o povo de Israel:

[[v5-27-15]]

^<<v5-27-15,15>>^ ‘Maldito quem esculpir ou fundir um ídolo e o levantar em segredo. Os ídolos, trabalhos de artesãos, são detestáveis ao SENHOR’. E todo o povo responderá: ‘Amém!’.

[[v5-27-16]]

^<<v5-27-16,16>>^ ‘Maldito quem desonrar pai ou mãe’. E todo o povo responderá: ‘Amém!’.

[[v5-27-17]]

^<<v5-27-17,17>>^ ‘Maldito quem roubar a propriedade do próximo, movendo um marco de divisa’. E todo o povo responderá: ‘Amém!’.

[[v5-27-18]]

^<<v5-27-18,18>>^ ‘Maldito quem fizer o cego se desviar de seu caminho’. E todo o povo responderá: ‘Amém!’.

[[v5-27-19]]

^<<v5-27-19,19>>^ ‘Maldito quem negar justiça aos estrangeiros, aos órfãos ou às viúvas’. E todo o povo responderá: ‘Amém!’.

[[v5-27-20]]

^<<v5-27-20,20>>^ ‘Maldito quem tiver relações sexuais com a esposa de seu pai, pois desonrou seu pai’. E todo o povo responderá: ‘Amém!’.

[[v5-27-21]]

^<<v5-27-21,21>>^ ‘Maldito quem tiver relações sexuais com um animal’. E todo o povo responderá: ‘Amém!’.

[[v5-27-22]]

^<<v5-27-22,22>>^ ‘Maldito quem tiver relações sexuais com sua irmã, seja filha de seu pai ou de sua mãe’. E todo o povo responderá: ‘Amém!’.

[[v5-27-23]]

^<<v5-27-23,23>>^ ‘Maldito quem tiver relações sexuais com sua sogra’. E todo o povo responderá: ‘Amém!’.

[[v5-27-24]]

^<<v5-27-24,24>>^ ‘Maldito quem matar o seu próximo em segredo’. E todo o povo responderá: ‘Amém!’.

[[v5-27-25]]

^<<v5-27-25,25>>^ ‘Maldito quem aceitar pagamento para matar um inocente’. E todo o povo responderá: ‘Amém!’.

[[v5-27-26]]

^<<v5-27-26,26>>^ ‘Maldito quem não confirmar e cumprir os termos desta lei’. E todo o povo responderá: ‘Amém!’."

'''

xref:005-deuteronomio/005-deuteronomio-026.adoc#v5-26-0[&#60; Capítulo Anterior] | <<v5-27-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-028.adoc#v5-28-0[Próximo Capítulo &#62;]