include::./index.adoc[]

[[v5-21-0]]
=== Deuteronômio, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v5-21-1]]

^<<v5-21-1,1>>^ "Quando estiverem na terra que o SENHOR, seu Deus, lhes dá, e alguém for encontrado morto no campo e não se saiba quem o matou,

[[v5-21-2]]

^<<v5-21-2,2>>^ as autoridades e os juízes medirão a distância do local onde está o cadáver até as cidades vizinhas.

[[v5-21-3]]

^<<v5-21-3,3>>^ Quando se determinar qual é a cidade mais próxima, as autoridades da cidade escolherão do rebanho uma novilha que nunca tenha sido usada para trabalhar no campo e nunca tenha puxado um arado.

[[v5-21-4]]

^<<v5-21-4,4>>^ Levarão a novilha a um vale que não tenha sido lavrado nem semeado e pelo qual passe um ribeiro. Ali, no vale, quebrarão o pescoço da novilha.

[[v5-21-5]]

^<<v5-21-5,5>>^ Os sacerdotes levitas se aproximarão, pois o SENHOR, seu Deus, os escolheu para servirem diante dele e pronunciarem bênçãos em seu nome. Cabe a eles decidir todos os casos legais e criminais.

[[v5-21-6]]

^<<v5-21-6,6>>^ "As autoridades daquela cidade lavarão as mãos sobre a novilha cujo pescoço foi quebrado

[[v5-21-7]]

^<<v5-21-7,7>>^ e dirão: ‘Nossas mãos não derramaram o sangue dessa pessoa, nem vimos o crime acontecer.

[[v5-21-8]]

^<<v5-21-8,8>>^ Ó SENHOR, perdoa o teu povo, Israel, o qual libertaste. Não culpes o teu povo pela morte de um inocente’. Assim, serão absolvidos da culpa pelo sangue da pessoa.

[[v5-21-9]]

^<<v5-21-9,9>>^ Desse modo, vocês removerão do seu meio a culpa pela morte da vítima e farão o que é certo aos olhos do SENHOR."

[[v5-21-10]]

^<<v5-21-10,10>>^ "Quando vocês saírem para guerrear contra seus inimigos e o SENHOR, seu Deus, entregá-los em suas mãos e vocês os fizerem prisioneiros,

[[v5-21-11]]

^<<v5-21-11,11>>^ pode acontecer de algum de vocês vir uma mulher bonita entre os cativos, sentir-se atraído por ela e desejar casar-se com ela.

[[v5-21-12]]

^<<v5-21-12,12>>^ Nesse caso, leve-a para casa, onde ela raspará a cabeça, cortará as unhas

[[v5-21-13]]

^<<v5-21-13,13>>^ e trocará as roupas que estava usando quando foi capturada. Ela ficará em sua casa, mas você deixará que ela fique de luto pelo pai e pela mãe por um mês inteiro. Depois disso, você se casará com ela. Passará a ser seu marido, e ela será sua esposa.

[[v5-21-14]]

^<<v5-21-14,14>>^ Se depois do casamento ela não o agradar, liberte-a. Não a venda nem a trate como escrava, pois você a humilhou."

[[v5-21-15]]

^<<v5-21-15,15>>^ "Se um homem tiver duas esposas e amar apenas uma delas, mas ambas lhe derem filhos homens, e o filho mais velho for da esposa que ele não ama,

[[v5-21-16]]

^<<v5-21-16,16>>^ quando dividir sua herança o homem não poderá dar a porção maior ao filho da esposa amada, como se este fosse o filho mais velho.

[[v5-21-17]]

^<<v5-21-17,17>>^ Terá de reconhecer os direitos do filho mais velho, da esposa não amada, dando-lhe porção dobrada. Ele é o primeiro filho do vigor de seu pai, e os direitos do filho mais velho lhe pertencem."

[[v5-21-18]]

^<<v5-21-18,18>>^ "Se um homem tiver um filho teimoso e rebelde, que não obedece ao pai nem à mãe, apesar de eles o disciplinarem,

[[v5-21-19]]

^<<v5-21-19,19>>^ o pai e a mãe levarão o filho até a porta da cidade e dirão às autoridades ali reunidas:

[[v5-21-20]]

^<<v5-21-20,20>>^ ‘Este nosso filho é teimoso e rebelde e se recusa a obedecer. É mau-caráter e vive bêbado’.

[[v5-21-21]]

^<<v5-21-21,21>>^ Então todos os homens da cidade o executarão por apedrejamento. Desse modo, vocês eliminarão o mal do seu meio, e todo o Israel ficará sabendo disso e temerá."

[[v5-21-22]]

^<<v5-21-22,22>>^ "Se alguém cometeu um crime que merece a pena de morte e, por isso, foi executado e pendurado numa árvore,

[[v5-21-23]]

^<<v5-21-23,23>>^ não deverá permanecer pendurado ali durante a noite. Enterrem o corpo no mesmo dia, pois todo aquele que é pendurado é maldito aos olhos de Deus. Desse modo, vocês evitarão a contaminação da terra que o SENHOR, seu Deus, lhes dá como herança."

'''

xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[&#60; Capítulo Anterior] | <<v5-21-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-022.adoc#v5-22-0[Próximo Capítulo &#62;]