include::./index.adoc[]

[[v5-34-0]]
=== Deuteronômio, 34
// nvt ?, NVT - Nova Versão Transformadora

[[v5-34-1]]

^<<v5-34-1,1>>^ Então Moisés subiu das campinas de Moabe ao monte Nebo, até o topo do Pisga, do lado oposto de Jericó. Ali o SENHOR lhe mostrou toda a terra, de Gileade a Dã;

[[v5-34-2]]

^<<v5-34-2,2>>^ toda a terra de Naftali; a terra de Efraim e Manassés; a terra de Judá, que se estende até o mar Mediterrâneo;

[[v5-34-3]]

^<<v5-34-3,3>>^ o Neguebe; o vale do Jordão, com Jericó, a cidade das palmeiras, até Zoar.

[[v5-34-4]]

^<<v5-34-4,4>>^ O SENHOR disse a Moisés: "Esta é a terra que prometi sob juramento a Abraão, Isaque e Jacó, quando disse: ‘Eu a darei a seus descendentes’. Sim, permiti que você a visse com seus próprios olhos, mas você não atravessará o rio para entrar nela".

[[v5-34-5]]

^<<v5-34-5,5>>^ Assim, Moisés, servo do SENHOR, morreu ali na terra de Moabe, conforme o SENHOR tinha dito.

[[v5-34-6]]

^<<v5-34-6,6>>^ Ele o sepultou num vale junto a Bete-Peor, em Moabe, mas até hoje ninguém sabe o lugar exato.

[[v5-34-7]]

^<<v5-34-7,7>>^ Moisés tinha 120 anos quando morreu e, no entanto, ainda enxergava bem e tinha todas as suas forças.

[[v5-34-8]]

^<<v5-34-8,8>>^ Os israelitas prantearam a morte de Moisés por trinta dias nas campinas de Moabe, até se cumprir o período do ritual de luto.

[[v5-34-9]]

^<<v5-34-9,9>>^ Josué, filho de Num, estava cheio do espírito de sabedoria, pois Moisés havia imposto as mãos sobre ele. Por isso, os israelitas lhe obedeceram e fizeram o que SENHOR havia ordenado a Moisés.

[[v5-34-10]]

^<<v5-34-10,10>>^ Nunca houve em Israel outro profeta como Moisés, a quem o SENHOR conhecia face a face.

[[v5-34-11]]

^<<v5-34-11,11>>^ O SENHOR o enviou ao Egito para realizar todos os sinais e maravilhas contra o faraó, contra todos os seus servos e contra toda a sua terra.

[[v5-34-12]]

^<<v5-34-12,12>>^ Com grande poder, Moisés realizou atos temíveis diante dos olhos de todo o Israel.

'''

xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[&#60; Capítulo Anterior] | <<v5-34-0,Topo>> | xref:006-josue/006-josue-001.adoc#v6-1-0[Próximo Capítulo &#62;]