include::./index.adoc[]

[[v5-16-0]]
=== Deuteronômio, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v5-16-1]]

^<<v5-16-1,1>>^ "A cada ano, no mês de abibe, celebrem a Páscoa em homenagem ao SENHOR, seu Deus, pois foi nesse mês, durante a noite, que o SENHOR, seu Deus, os libertou do Egito.

[[v5-16-2]]

^<<v5-16-2,2>>^ O sacrifício de Páscoa será um animal do gado ou do rebanho, oferecido ao SENHOR, seu Deus, no lugar que ele escolher para habitação do seu nome.

[[v5-16-3]]

^<<v5-16-3,3>>^ Comam o sacrifício com pães sem fermento. Durante sete dias, comam pão sem fermento, como fizeram quando fugiram às pressas do Egito. Comam esse pão, o pão do sofrimento, para se lembrarem, por toda a vida, do dia em que saíram do Egito.

[[v5-16-4]]

^<<v5-16-4,4>>^ Durante esses sete dias, não deve haver a mínima quantidade de fermento nas casas em toda a sua terra. E, quando sacrificarem o cordeiro de Páscoa ao entardecer do primeiro dia, não deixem sobras para a manhã seguinte.

[[v5-16-5]]

^<<v5-16-5,5>>^ "Não ofereçam o sacrifício de Páscoa em nenhuma das cidades que o SENHOR, seu Deus, lhes dá.

[[v5-16-6]]

^<<v5-16-6,6>>^ Ofereçam-no apenas no lugar que o SENHOR, seu Deus, escolher para habitação do seu nome. Sacrifiquem-no ali ao entardecer, enquanto o sol se põe, no mesmo período do dia em que saíram do Egito.

[[v5-16-7]]

^<<v5-16-7,7>>^ Assem e comam o cordeiro no lugar que o SENHOR, seu Deus, escolher. Na manhã seguinte, voltem às suas tendas.

[[v5-16-8]]

^<<v5-16-8,8>>^ Durante os seis dias seguintes, comam pão sem fermento. No sétimo dia, declarem outra reunião sagrada em homenagem ao SENHOR, seu Deus, e não façam trabalho algum."

[[v5-16-9]]

^<<v5-16-9,9>>^ "Contem sete semanas a partir do dia em que começarem a colheita de cereais.

[[v5-16-10]]

^<<v5-16-10,10>>^ Então celebrem a Festa da Colheita em homenagem ao SENHOR, seu Deus. Levem uma oferta voluntária proporcional às bênçãos que receberam dele.

[[v5-16-11]]

^<<v5-16-11,11>>^ Será um tempo de celebração diante do SENHOR, seu Deus, no lugar que ele escolher para habitação do seu nome. Celebrem com seus filhos e filhas, com seus servos e servas, com os levitas das suas cidades e com os estrangeiros, órfãos e viúvas que vivem entre vocês.

[[v5-16-12]]

^<<v5-16-12,12>>^ Lembrem-se de que, um dia, vocês foram escravos no Egito e, portanto, tenham o cuidado de cumprir todos estes decretos."

[[v5-16-13]]

^<<v5-16-13,13>>^ "Celebrem a Festa das Cabanas durante sete dias, no final da época da colheita, depois que ajuntarem os cereais e prensarem as uvas.

[[v5-16-14]]

^<<v5-16-14,14>>^ Essa festa será um tempo de alegria e comemoração com seus filhos e filhas, seus servos e servas, com os levitas, estrangeiros, órfãos e viúvas de suas cidades.

[[v5-16-15]]

^<<v5-16-15,15>>^ Durante sete dias, celebrem essa festa em homenagem ao SENHOR, seu Deus, no lugar que ele escolher, pois ele é quem os abençoa em todas as suas colheitas e lhes dá sucesso em todo o seu trabalho. Essa festa será um tempo de grande alegria para vocês.

[[v5-16-16]]

^<<v5-16-16,16>>^ "A cada ano, todos os homens de Israel devem celebrar estas três festas: a Festa dos Pães sem Fermento, a Festa da Colheita e a Festa das Cabanas. Em cada uma dessas ocasiões, todos os homens devem comparecer diante do SENHOR, seu Deus, no lugar que ele escolher. Não devem, porém, apresentar-se diante do SENHOR de mãos vazias.

[[v5-16-17]]

^<<v5-16-17,17>>^ Todos devem ofertar de acordo com as bênçãos que receberam do SENHOR, seu Deus."

[[v5-16-18]]

^<<v5-16-18,18>>^ "Nomeiem juízes e oficiais de cada uma de suas tribos em todas as cidades que o SENHOR, seu Deus, lhes dá. Eles julgarão o povo com justiça.

[[v5-16-19]]

^<<v5-16-19,19>>^ Nunca distorçam a justiça nem mostrem parcialidade. Nunca aceitem subornos, pois eles cegam os olhos dos sábios e corrompem as decisões dos íntegros.

[[v5-16-20]]

^<<v5-16-20,20>>^ Que a justiça verdadeira prevaleça sempre, para que vocês vivam e tomem posse da terra que o SENHOR, seu Deus, lhes dá.

[[v5-16-21]]

^<<v5-16-21,21>>^ "Jamais levantem um poste de madeira para Aserá junto ao altar que edificarem para o SENHOR, seu Deus.

[[v5-16-22]]

^<<v5-16-22,22>>^ Jamais levantem colunas sagradas para adoração, pois isso é detestável para o SENHOR, seu Deus."

'''

xref:005-deuteronomio/005-deuteronomio-015.adoc#v5-15-0[&#60; Capítulo Anterior] | <<v5-16-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-017.adoc#v5-17-0[Próximo Capítulo &#62;]