include::./index.adoc[]

[[v5-31-0]]
=== Deuteronômio, 31
// nvt ?, NVT - Nova Versão Transformadora

[[v5-31-1]]

^<<v5-31-1,1>>^ Quando Moisés havia terminado de dar estas instruções a todo o povo de Israel,

[[v5-31-2]]

^<<v5-31-2,2>>^ ele disse: "Estou com 120 anos e já não sou capaz de conduzi-los. O SENHOR me disse: ‘Você não atravessará o rio Jordão’.

[[v5-31-3]]

^<<v5-31-3,3>>^ Mas o próprio SENHOR, seu Deus, atravessará adiante de vocês. Ele destruirá as nações que vivem ali, e vocês tomarão posse da terra. Josué os conduzirá até o outro lado do rio, conforme o SENHOR prometeu.

[[v5-31-4]]

^<<v5-31-4,4>>^ "O SENHOR destruirá as nações que vivem na terra, como destruiu Seom e Ogue, os reis dos amorreus.

[[v5-31-5]]

^<<v5-31-5,5>>^ O SENHOR lhes entregará os povos que vivem ali, e vocês farão com eles o que eu lhes ordenei.

[[v5-31-6]]

^<<v5-31-6,6>>^ Portanto, sejam fortes e corajosos! Não tenham medo e não se apavorem diante deles. O SENHOR, seu Deus, irá adiante de vocês. Ele não os deixará nem os abandonará".

[[v5-31-7]]

^<<v5-31-7,7>>^ Então, enquanto todo o Israel observava, Moisés mandou chamar Josué e lhe disse: "Seja forte e corajoso, pois você conduzirá este povo à terra que o SENHOR jurou a seus antepassados que lhes daria. Você a dividirá entre eles e a entregará como herança.

[[v5-31-8]]

^<<v5-31-8,8>>^ Não tenha medo nem desanime, pois o próprio SENHOR irá adiante de vocês. Ele estará com vocês; não os deixará nem os abandonará".

[[v5-31-9]]

^<<v5-31-9,9>>^ Moisés escreveu toda esta lei num livro e o entregou aos sacerdotes que transportavam a arca da aliança do SENHOR e às autoridades de Israel.

[[v5-31-10]]

^<<v5-31-10,10>>^ Depois, Moisés lhes deu a seguinte ordem: "Ao final de cada sete anos, no ano do cancelamento das dívidas, durante a Festa das Cabanas,

[[v5-31-11]]

^<<v5-31-11,11>>^ leiam este Livro da Lei para todo o povo de Israel, quando estiverem reunidos diante do SENHOR, seu Deus, no lugar que ele escolher.

[[v5-31-12]]

^<<v5-31-12,12>>^ Convoquem todos: homens, mulheres, crianças e os estrangeiros que vivem em suas cidades, para que ouçam este Livro da Lei e aprendam a temer o SENHOR, seu Deus, e a obedecer fielmente a todos os termos desta lei.

[[v5-31-13]]

^<<v5-31-13,13>>^ Façam isso para que seus filhos, que não conhecem estas instruções, as ouçam e aprendam a temer o SENHOR, seu Deus. Façam isso enquanto viverem na terra da qual tomarão posse ao atravessar o Jordão".

[[v5-31-14]]

^<<v5-31-14,14>>^ Então o SENHOR disse a Moisés: "É chegada a hora de você morrer. Chame Josué e apresentem-se na tenda do encontro, onde darei minhas ordens a ele". Moisés e Josué foram e se apresentaram na tenda do encontro.

[[v5-31-15]]

^<<v5-31-15,15>>^ O SENHOR lhes apareceu numa coluna de nuvem, que parou à entrada da tenda sagrada.

[[v5-31-16]]

^<<v5-31-16,16>>^ O SENHOR disse a Moisés: "Você está prestes a morrer e a se reunir a seus antepassados. Quando não estiver mais aqui, este povo começará a se prostituir, adorando deuses estrangeiros, os deuses da terra para onde se dirigem. Eles me abandonarão e quebrarão a aliança que fiz com eles.

[[v5-31-17]]

^<<v5-31-17,17>>^ Então minha ira arderá contra eles. Eu os abandonarei, esconderei deles minha face, e eles serão devorados. Aflições terríveis os atingirão e, naquele dia, dirão: ‘Estas calamidades nos atingiram porque o SENHOR não está mais entre nós!’.

[[v5-31-18]]

^<<v5-31-18,18>>^ Naquele dia, esconderei deles minha face por causa de todo o mal que praticaram, adorando outros deuses.

[[v5-31-19]]

^<<v5-31-19,19>>^ "Escrevam, portanto, as palavras desta canção e ensinem-na aos israelitas. Ajudem o povo a aprendê-la, para que ela sirva de testemunha a meu favor e contra eles.

[[v5-31-20]]

^<<v5-31-20,20>>^ Pois eu os farei entrar na terra que jurei dar a seus antepassados, uma terra que produz leite e mel com fartura. Lá, eles se tornarão prósperos, comerão à vontade e engordarão. Contudo, começarão a adorar outros deuses; eles me desprezarão e quebrarão a minha aliança.

[[v5-31-21]]

^<<v5-31-21,21>>^ E, quando grandes calamidades lhes ocorrerem, esta canção servirá de prova contra eles, pois seus descendentes jamais se esquecerão dela. Eu conheço as intenções deles, mesmo antes de entrarem na terra que jurei lhes dar".

[[v5-31-22]]

^<<v5-31-22,22>>^ Assim, naquele mesmo dia, Moisés escreveu as palavras da canção e a ensinou aos israelitas.

[[v5-31-23]]

^<<v5-31-23,23>>^ Então o SENHOR deu ordens a Josué, filho de Num, com as seguintes palavras: "Seja forte e corajoso, pois você conduzirá o povo de Israel à terra que jurei lhes dar. Eu estarei com você".

[[v5-31-24]]

^<<v5-31-24,24>>^ Quando Moisés terminou de escrever os termos desta lei num livro,

[[v5-31-25]]

^<<v5-31-25,25>>^ deu a seguinte ordem aos levitas que transportavam a arca da aliança do SENHOR:

[[v5-31-26]]

^<<v5-31-26,26>>^ "Peguem este Livro da Lei e coloquem-no ao lado da arca da aliança do SENHOR, seu Deus, para que ele fique ali como testemunha contra vocês.

[[v5-31-27]]

^<<v5-31-27,27>>^ Pois eu sei como são rebeldes e teimosos. Se, mesmo agora, enquanto ainda estou vivo e em seu meio, vocês se rebelaram, quanto mais rebeldes serão depois da minha morte!

[[v5-31-28]]

^<<v5-31-28,28>>^ "Convoquem agora todas as autoridades e os oficiais de suas tribos para que eu lhes fale diretamente e chame os céus e a terra para testemunharem contra eles.

[[v5-31-29]]

^<<v5-31-29,29>>^ Sei que depois de minha morte vocês se tornarão inteiramente corruptos e se afastarão do caminho que lhes ordenei que seguissem. Nos dias futuros, a calamidade cairá sobre vocês, pois farão o que é mau aos olhos do SENHOR e provocarão a ira dele contra seus atos".

[[v5-31-30]]

^<<v5-31-30,30>>^ Então Moisés recitou a canção inteira diante de toda a comunidade de Israel:

'''

xref:005-deuteronomio/005-deuteronomio-030.adoc#v5-30-0[&#60; Capítulo Anterior] | <<v5-31-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-032.adoc#v5-32-0[Próximo Capítulo &#62;]