include::./index.adoc[]

[[v5-15-0]]
=== Deuteronômio, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v5-15-1]]

^<<v5-15-1,1>>^ "Ao final de cada sete anos, cancelem as dívidas de todos a quem vocês tiverem feito um empréstimo.

[[v5-15-2]]

^<<v5-15-2,2>>^ O cancelamento será efetuado da seguinte forma: todos cancelarão os empréstimos que fizeram a irmãos israelitas. Ninguém exigirá pagamento do seu próximo ou de seus parentes, pois chegou o tempo do SENHOR para liberá-los das dívidas.

[[v5-15-3]]

^<<v5-15-3,3>>^ Essa liberação se aplica somente aos irmãos israelitas, e não aos estrangeiros que vivem entre vocês.

[[v5-15-4]]

^<<v5-15-4,4>>^ "Não deverá haver pobres entre vocês, pois o SENHOR, seu Deus, os abençoará grandemente na terra que lhes dá como herança.

[[v5-15-5]]

^<<v5-15-5,5>>^ Receberão essa bênção se tiverem o cuidado de obedecer ao SENHOR, seu Deus, e cumprir todos estes mandamentos que hoje lhes dou.

[[v5-15-6]]

^<<v5-15-6,6>>^ O SENHOR, seu Deus, os abençoará conforme prometeu. Vocês emprestarão dinheiro a muitas nações, mas jamais precisarão tomar emprestado. Governarão muitas nações, mas não serão governados por nação alguma.

[[v5-15-7]]

^<<v5-15-7,7>>^ "Se, contudo, houver algum israelita pobre em suas cidades quando chegarem à terra que o SENHOR, seu Deus, lhes dá, não endureçam o coração e não fechem a mão para ele.

[[v5-15-8]]

^<<v5-15-8,8>>^ Ao contrário, sejam generosos e emprestem-lhe o que for necessário.

[[v5-15-9]]

^<<v5-15-9,9>>^ Não sejam mesquinhos nem se recusem a emprestar a alguém só porque o ano de cancelamento das dívidas está próximo. Se vocês se recusarem a fornecer o empréstimo e a pessoa necessitada clamar ao SENHOR, vocês serão considerados culpados de pecado.

[[v5-15-10]]

^<<v5-15-10,10>>^ Deem aos pobres com generosidade, e não com má vontade, pois o SENHOR, seu Deus, os abençoará em tudo que fizerem.

[[v5-15-11]]

^<<v5-15-11,11>>^ Sempre haverá pobres na terra. Por isso, ordeno que compartilhem seus bens generosamente com os pobres e com outros necessitados de sua terra."

[[v5-15-12]]

^<<v5-15-12,12>>^ "Se um irmão hebreu, homem ou mulher, vender-se a você como escravo, ele lhe servirá por seis anos. Depois disso, liberte-o no sétimo ano.

[[v5-15-13]]

^<<v5-15-13,13>>^ "Quando libertar um escravo, não o mande embora de mãos vazias.

[[v5-15-14]]

^<<v5-15-14,14>>^ Seja generoso e dê-lhe de despedida um presente dos animais de seu rebanho, dos cereais de sua eira e do vinho de sua prensa de uvas. Compartilhe com ele um pouco da fartura com a qual o SENHOR, seu Deus, o abençoou.

[[v5-15-15]]

^<<v5-15-15,15>>^ Lembre-se de que, um dia, você foi escravo na terra do Egito e o SENHOR, seu Deus, o libertou. Por isso lhe dou essa ordem.

[[v5-15-16]]

^<<v5-15-16,16>>^ "Mas, se por estar bem com você e amar você e sua família, o servo disser: ‘Não quero ir embora’,

[[v5-15-17]]

^<<v5-15-17,17>>^ você pegará um furador e furará a ponta da orelha dele contra a porta. Depois disso, ele será seu escravo para o resto da vida. Faça o mesmo com as escravas.

[[v5-15-18]]

^<<v5-15-18,18>>^ "Quando libertar seus escravos, não considere isso uma grande perda. Lembre-se de que, por seis anos, eles lhe prestaram serviços equivalentes a duas vezes o salário de empregados contratados, e o SENHOR, seu Deus, o abençoará em tudo que você fizer."

[[v5-15-19]]

^<<v5-15-19,19>>^ "Separem para o SENHOR, seu Deus, os machos das primeiras crias do gado e dos rebanhos. Não usem a primeira cria do gado para trabalhar no campo, e não tosquiem a primeira cria das ovelhas.

[[v5-15-20]]

^<<v5-15-20,20>>^ Em vez disso, a cada ano, comam esses animais com sua família na presença do SENHOR, seu Deus, no lugar que ele escolher.

[[v5-15-21]]

^<<v5-15-21,21>>^ Mas, se essa primeira cria tiver algum defeito, se o animal for manco, cego ou tiver algum outro problema, não o sacrifiquem ao SENHOR, seu Deus.

[[v5-15-22]]

^<<v5-15-22,22>>^ Comam o animal na cidade em que morarem. Qualquer pessoa poderá comê-lo, esteja cerimonialmente pura ou impura, assim como qualquer um pode comer uma gazela ou um veado.

[[v5-15-23]]

^<<v5-15-23,23>>^ Não comam, porém, o sangue do animal; derramem-no no chão, como se fosse água."

'''

xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[&#60; Capítulo Anterior] | <<v5-15-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[Próximo Capítulo &#62;]