include::./index.adoc[]

[[v5-29-0]]
=== Deuteronômio, 29
// nvt ?, NVT - Nova Versão Transformadora

[[v5-29-1]]

^<<v5-29-1,1>>^ Estes são os termos da aliança que o SENHOR ordenou que Moisés fizesse com os israelitas enquanto estavam na terra de Moabe, além da aliança que havia feito com eles no monte Sinai.

[[v5-29-2]]

^<<v5-29-2,2>>^ Moisés convocou todo o povo de Israel e lhe disse: "Vocês viram com os próprios olhos tudo que o SENHOR fez na terra do Egito ao faraó, a todos os seus servos e a toda a sua terra.

[[v5-29-3]]

^<<v5-29-3,3>>^ Presenciaram todas as grandes demonstrações de poder, os sinais e as espantosas maravilhas.

[[v5-29-4]]

^<<v5-29-4,4>>^ Até hoje, porém, o SENHOR não lhes deu mente para entender, nem olhos para ver, nem ouvidos para ouvir!

[[v5-29-5]]

^<<v5-29-5,5>>^ Durante quarenta anos eu os conduzi pelo deserto e, no entanto, suas roupas e sandálias não se gastaram.

[[v5-29-6]]

^<<v5-29-6,6>>^ Vocês não comeram pão nem beberam vinho ou outra bebida fermentada, mas receberam alimento para que soubessem que ele é o SENHOR, seu Deus.

[[v5-29-7]]

^<<v5-29-7,7>>^ "Quando chegamos aqui, Seom, rei de Hesbom, e Ogue, rei de Basã, nos atacaram, mas nós os derrotamos.

[[v5-29-8]]

^<<v5-29-8,8>>^ Conquistamos seu território e o entregamos às tribos de Rúben, Gade e à meia tribo de Manassés, como sua herança.

[[v5-29-9]]

^<<v5-29-9,9>>^ "Portanto, obedeçam aos termos desta aliança, para prosperarem em tudo que fizerem.

[[v5-29-10]]

^<<v5-29-10,10>>^ Todos vocês — chefes de tribos, autoridades, oficiais, e todos os homens de Israel — estão hoje na presença do SENHOR, seu Deus.

[[v5-29-11]]

^<<v5-29-11,11>>^ Estão acompanhados de suas crianças e esposas, bem como dos estrangeiros que vivem em seu meio, que cortam lenha e carregam água para vocês.

[[v5-29-12]]

^<<v5-29-12,12>>^ Estão aqui hoje para entrar na aliança solene que o SENHOR, seu Deus, faz com vocês, aliança que inclui maldições.

[[v5-29-13]]

^<<v5-29-13,13>>^ Ao entrarem na aliança hoje, ele os confirmará como seu povo e reafirmará que é o seu Deus, conforme prometeu sob juramento a vocês e a seus antepassados Abraão, Isaque e Jacó.

[[v5-29-14]]

^<<v5-29-14,14>>^ "Não é só com vocês que faço esta aliança, incluindo suas maldições.

[[v5-29-15]]

^<<v5-29-15,15>>^ Faço a aliança com vocês que estão hoje na presença do SENHOR, nosso Deus, e também com as gerações futuras que não estão aqui.

[[v5-29-16]]

^<<v5-29-16,16>>^ "Vocês se lembram de como vivemos na terra do Egito e passamos pelo território de nações inimigas quando saímos de lá.

[[v5-29-17]]

^<<v5-29-17,17>>^ Viram as práticas detestáveis delas e seus ídolos de madeira, pedra, prata e ouro.

[[v5-29-18]]

^<<v5-29-18,18>>^ Faço esta aliança com vocês para que ninguém, nenhum homem, mulher, clã ou tribo em seu meio, se afaste do SENHOR, nosso Deus, para adorar os deuses das outras nações, e para que nenhuma raiz em seu meio produza frutos amargos e venenosos.

[[v5-29-19]]

^<<v5-29-19,19>>^ "Aqueles que ouvirem as advertências desta maldição não devem se parabenizar e pensar: ‘Estou seguro, embora siga os desejos do meu coração obstinado’. Isso levaria à ruína total!

[[v5-29-20]]

^<<v5-29-20,20>>^ O SENHOR não os perdoará. Ao contrário, sua ira e seu zelo arderão contra eles. Todas as maldições escritas neste livro cairão sobre eles, e o SENHOR apagará seus nomes de debaixo do céu.

[[v5-29-21]]

^<<v5-29-21,21>>^ O SENHOR os separará de todas as tribos de Israel a fim de derramar sobre eles todas as maldições da aliança registradas neste Livro da Lei.

[[v5-29-22]]

^<<v5-29-22,22>>^ "Então as gerações futuras, tanto seus descendentes como os estrangeiros que vêm de terras distantes, verão a devastação da terra e as doenças com as quais o SENHOR a aflige.

[[v5-29-23]]

^<<v5-29-23,23>>^ Dirão: ‘A terra inteira foi devastada por enxofre e sal. É uma terra estéril, onde não há nada plantado e nada cresce, nem uma folha de grama. É como as cidades de Sodoma e Gomorra, Admá e Zeboim, que o SENHOR destruiu com sua furiosa ira’.

[[v5-29-24]]

^<<v5-29-24,24>>^ "Todas as nações vizinhas perguntarão: ‘Por que o SENHOR fez isso com esta terra? Por que se irou tanto?’.

[[v5-29-25]]

^<<v5-29-25,25>>^ "E a resposta será: ‘Foi porque o povo desta terra abandonou a aliança que o SENHOR, o Deus de seus antepassados, fez com eles quando os tirou da terra do Egito.

[[v5-29-26]]

^<<v5-29-26,26>>^ Afastaram-se dele para servir e adorar outros deuses que não conheciam, deuses que não lhes era permitido adorar.

[[v5-29-27]]

^<<v5-29-27,27>>^ Por isso a ira do SENHOR ardeu contra esta terra e trouxe sobre ela todas as maldições registradas neste livro.

[[v5-29-28]]

^<<v5-29-28,28>>^ Com grande ira e fúria, o SENHOR arrancou seu povo da terra e o baniu para outra terra, onde vivem até hoje!’.

[[v5-29-29]]

^<<v5-29-29,29>>^ "O SENHOR, nosso Deus, tem segredos que ninguém conhece. Não seremos responsabilizados por eles, mas nós e nossos filhos somos responsáveis para sempre por tudo que ele nos revelou, para que obedeçamos a todos os termos desta lei."

'''

xref:005-deuteronomio/005-deuteronomio-028.adoc#v5-28-0[&#60; Capítulo Anterior] | <<v5-29-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-030.adoc#v5-30-0[Próximo Capítulo &#62;]