include::./index.adoc[]

[[v5-19-0]]
=== Deuteronômio, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v5-19-1]]

^<<v5-19-1,1>>^ "Quando o SENHOR, seu Deus, destruir as nações cujo território ele lhes dá, vocês tomarão posse da terra e se estabelecerão nas cidades e casas que elas construíram.

[[v5-19-2]]

^<<v5-19-2,2>>^ Em seguida, separarão três cidades de refúgio na terra que o SENHOR, seu Deus, lhes dá.

[[v5-19-3]]

^<<v5-19-3,3>>^ Preparem estradas e dividam em três regiões a terra que o SENHOR, seu Deus, lhes dá como propriedade, com uma dessas cidades em cada região. Quem tiver matado alguém poderá fugir para uma dessas cidades de refúgio e ficar a salvo.

[[v5-19-4]]

^<<v5-19-4,4>>^ "Isso se aplica a alguém que, sem intenção e sem mostrar hostilidade anterior, matar outra pessoa: ele poderá fugir para uma dessas cidades de refúgio e viver em segurança.

[[v5-19-5]]

^<<v5-19-5,5>>^ Se acontecer, por exemplo, de alguém ir com um vizinho cortar lenha num bosque e, quando um deles levantar o machado para cortar uma árvore, o ferro do machado escapar do cabo, atingir a outra pessoa e causar sua morte, o homicida poderá fugir para uma das cidades de refúgio a fim de salvar a vida.

[[v5-19-6]]

^<<v5-19-6,6>>^ "Se, contudo, a distância até a cidade de refúgio for muito grande e acontecer que, irado, o parente encarregado de vingar a morte da vítima alcance e mate o homicida, o castigo não seria merecido, pois o fugitivo não mostrou hostilidade anterior à vítima.

[[v5-19-7]]

^<<v5-19-7,7>>^ Por isso, ordeno que separem três cidades de refúgio.

[[v5-19-8]]

^<<v5-19-8,8>>^ "Se o SENHOR, seu Deus, ampliar seu território conforme jurou a seus antepassados e lhes der toda a terra que lhes prometeu,

[[v5-19-9]]

^<<v5-19-9,9>>^ separem mais três cidades de refúgio. (Ele lhes dará a terra se vocês cumprirem cuidadosamente todos os mandamentos que hoje lhes dou, se sempre amarem o SENHOR, seu Deus, e andarem em seus caminhos.)

[[v5-19-10]]

^<<v5-19-10,10>>^ Com isso, vocês evitarão a morte de inocentes na terra que o SENHOR, seu Deus, lhes dá como herança. Do contrário, seriam culpados pelo sangue de inocentes.

[[v5-19-11]]

^<<v5-19-11,11>>^ "Se, contudo, alguém demonstrar hostilidade a seu vizinho, ficar à espreita dele e o atacar e matar, fugindo depois para uma das cidades de refúgio,

[[v5-19-12]]

^<<v5-19-12,12>>^ as autoridades da cidade do homicida enviarão representantes à cidade de refúgio para trazê-lo de volta e entregá-lo ao vingador da vítima, para que ele execute o homicida.

[[v5-19-13]]

^<<v5-19-13,13>>^ Não tenham pena dele. Eliminem de Israel a culpa de matar inocentes. Assim, tudo irá bem com vocês."

[[v5-19-14]]

^<<v5-19-14,14>>^ "Quando tomarem posse da terra que o SENHOR, seu Deus, lhes dá como herança, jamais roubem terras de outros, mudando de lugar os marcos de divisa que seus antepassados colocaram.

[[v5-19-15]]

^<<v5-19-15,15>>^ "Não condenem alguém por um crime ou delito com base no depoimento de apenas uma testemunha. Os fatos a respeito do caso devem ser confirmados pelo depoimento de duas ou três testemunhas.

[[v5-19-16]]

^<<v5-19-16,16>>^ "Se uma testemunha mal-intencionada se apresentar e acusar alguém de ter cometido um crime,

[[v5-19-17]]

^<<v5-19-17,17>>^ tanto o acusador como o acusado comparecerão diante do SENHOR, apresentando-se aos sacerdotes e juízes que estiverem de serviço na ocasião.

[[v5-19-18]]

^<<v5-19-18,18>>^ Os juízes farão uma investigação cuidadosa do caso. Se a testemunha fez acusações falsas contra seu irmão israelita,

[[v5-19-19]]

^<<v5-19-19,19>>^ apliquem-lhe a sentença que ela planejava para a outra pessoa. Desse modo, vocês eliminarão o mal do seu meio.

[[v5-19-20]]

^<<v5-19-20,20>>^ O restante do povo ficará sabendo disso e terá medo de cometer tamanha maldade.

[[v5-19-21]]

^<<v5-19-21,21>>^ Não tenham pena do culpado. Sua regra deve ser: vida por vida, olho por olho, dente por dente, mão por mão, pé por pé."

'''

xref:005-deuteronomio/005-deuteronomio-018.adoc#v5-18-0[&#60; Capítulo Anterior] | <<v5-19-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[Próximo Capítulo &#62;]