include::./index.adoc[]

[[v5-22-0]]
=== Deuteronômio, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v5-22-1]]

^<<v5-22-1,1>>^ "Se você vir solto por aí o boi ou a ovelha de um israelita, não fuja de sua responsabilidade. Devolva o animal ao dono.

[[v5-22-2]]

^<<v5-22-2,2>>^ Se o dono não morar por perto ou se você não o conhecer, leve o animal para sua casa e fique com ele até o dono vir procurá-lo. Então, devolva o animal.

[[v5-22-3]]

^<<v5-22-3,3>>^ Faça o mesmo se encontrar um jumento, uma peça de roupa ou qualquer outra coisa que alguém tenha perdido. Não fuja de sua responsabilidade.

[[v5-22-4]]

^<<v5-22-4,4>>^ "Se você vir o jumento ou o boi de um israelita caído no caminho, não o ignore. Vá e ajude o dono a levantar o animal.

[[v5-22-5]]

^<<v5-22-5,5>>^ "A mulher não deve usar roupas de homem, e o homem não deve usar roupas de mulher. Quem age desse modo é detestável aos olhos do SENHOR, seu Deus.

[[v5-22-6]]

^<<v5-22-6,6>>^ "Se acontecer de você encontrar o ninho de um pássaro numa árvore ou no chão, e houver nele filhotes ou ovos que a mãe esteja chocando, não leve a mãe junto com os filhotes.

[[v5-22-7]]

^<<v5-22-7,7>>^ Leve os filhotes, mas deixe a mãe, para que você prospere e tenha vida longa.

[[v5-22-8]]

^<<v5-22-8,8>>^ "Quando você construir uma casa nova, coloque um parapeito em torno do terraço. Desse modo, se alguém cair do terraço, você e sua família não serão culpados pela morte da vítima.

[[v5-22-9]]

^<<v5-22-9,9>>^ "Não plantem nenhuma outra semente entre as videiras em seu vinhedo. Se o fizerem, estarão proibidos de usar tanto as uvas desse vinhedo como o fruto da outra plantação que semearam.

[[v5-22-10]]

^<<v5-22-10,10>>^ "Não arem a terra com um boi e um jumento presos ao mesmo jugo.

[[v5-22-11]]

^<<v5-22-11,11>>^ "Não usem roupas feitas de fios de lã e linho entrelaçados.

[[v5-22-12]]

^<<v5-22-12,12>>^ "Coloquem franjas nas quatro pontas do manto com o qual vocês se cobrem."

[[v5-22-13]]

^<<v5-22-13,13>>^ "Se um homem se casar com uma mulher e, depois de ter relações com ela, rejeitá-la

[[v5-22-14]]

^<<v5-22-14,14>>^ e acusá-la publicamente de conduta vergonhosa, dizendo: ‘Quando me casei com esta mulher, descobri que ela não era virgem’,

[[v5-22-15]]

^<<v5-22-15,15>>^ então o pai e a mãe da mulher levarão a prova da virgindade da filha até a porta da cidade, onde as autoridades estarão reunidas.

[[v5-22-16]]

^<<v5-22-16,16>>^ O pai lhes dirá: ‘Dei minha filha em casamento a este homem, e agora ele a rejeitou.

[[v5-22-17]]

^<<v5-22-17,17>>^ Acusou-a de conduta vergonhosa, dizendo: ‘Descobri que sua filha não era virgem’. Aqui está, porém, a prova da virgindade de minha filha’. Então os pais estenderão o lençol da filha diante das autoridades,

[[v5-22-18]]

^<<v5-22-18,18>>^ e eles pegarão o homem e o castigarão.

[[v5-22-19]]

^<<v5-22-19,19>>^ Também lhe aplicarão uma multa de cem peças de prata que ele pagará ao pai da mulher, uma vez que acusou publicamente de conduta vergonhosa uma virgem de Israel. Ela continuará a ser esposa do homem, e ele jamais poderá se divorciar dela.

[[v5-22-20]]

^<<v5-22-20,20>>^ "Mas, se as acusações do homem forem verdadeiras e ele puder provar que a mulher não era virgem,

[[v5-22-21]]

^<<v5-22-21,21>>^ então ela será levada até a porta da casa de seu pai e ali será executada por apedrejamento pelos homens da cidade. Ela cometeu um crime vergonhoso em Israel, praticando imoralidade sexual enquanto vivia na casa de seus pais. Desse modo, vocês eliminarão o mal do seu meio.

[[v5-22-22]]

^<<v5-22-22,22>>^ "Se um homem for flagrado cometendo adultério, ele e a mulher terão de morrer. Desse modo, vocês eliminarão o mal do meio de Israel.

[[v5-22-23]]

^<<v5-22-23,23>>^ "Se um homem encontrar uma moça virgem, prometida em casamento, e tiver relações sexuais com ela dentro da cidade,

[[v5-22-24]]

^<<v5-22-24,24>>^ levem os dois para a porta da cidade e executem-nos por apedrejamento. A mulher é culpada porque não gritou por socorro, e o homem deverá morrer porque humilhou a esposa de outro homem. Desse modo, vocês eliminarão o mal do seu meio.

[[v5-22-25]]

^<<v5-22-25,25>>^ "Mas, se o homem encontrar a moça prometida em casamento no campo e a violentar, somente o homem deverá ser morto.

[[v5-22-26]]

^<<v5-22-26,26>>^ Não façam nada à moça; não cometeu crime algum que mereça a pena de morte. É tão inocente quanto uma vítima de homicídio.

[[v5-22-27]]

^<<v5-22-27,27>>^ Uma vez que o homem a violentou no campo, deve-se presumir que ela gritou, mas não houve quem a socorresse.

[[v5-22-28]]

^<<v5-22-28,28>>^ "Se um homem tiver relações com uma moça virgem, mas que não esteja prometida em casamento, e eles forem descobertos,

[[v5-22-29]]

^<<v5-22-29,29>>^ o homem pagará ao pai da moça cinquenta peças de prata. Uma vez que ele humilhou a moça, se casará com ela e jamais poderá se divorciar.

[[v5-22-30]]

^<<v5-22-30,30>>^ "Nenhum homem tomará por mulher alguém que foi esposa de seu pai, pois isso desonraria seu pai."

'''

xref:005-deuteronomio/005-deuteronomio-021.adoc#v5-21-0[&#60; Capítulo Anterior] | <<v5-22-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[Próximo Capítulo &#62;]