include::./index.adoc[]

[[v5-32-0]]
=== Deuteronômio, 32
// nvt ?, NVT - Nova Versão Transformadora

[[v5-32-1]]

^<<v5-32-1,1>>^ "Escutem, ó céus, e falarei! Ouça, ó terra, aquilo que digo!

[[v5-32-2]]

^<<v5-32-2,2>>^ Que meu ensino desça sobre vocês como chuva, que minhas palavras se derramem como orvalho. Caiam como chuva sobre a grama, como garoa suave sobre o capim novo.

[[v5-32-3]]

^<<v5-32-3,3>>^ Proclamarei o nome do SENHOR; exaltemos o nosso Deus!

[[v5-32-4]]

^<<v5-32-4,4>>^ Ele é a Rocha, e suas obras são perfeitas; tudo que ele faz é certo. É um Deus fiel, que nunca erra, é justo e verdadeiro!

[[v5-32-5]]

^<<v5-32-5,5>>^ "Seu povo o tratou de maneira desleal, agiu maldosamente, e não como seus filhos; são uma geração perversa e corrompida.

[[v5-32-6]]

^<<v5-32-6,6>>^ É assim que retribuem ao SENHOR, povo tolo e sem juízo? Não é ele o Pai de vocês, que os criou? Não foi ele que os fez e os estabeleceu?

[[v5-32-7]]

^<<v5-32-7,7>>^ Lembrem-se dos dias de muito tempo atrás, pensem nas gerações passadas. Perguntem a seus pais, e eles os informarão; consultem os líderes, e eles lhes contarão.

[[v5-32-8]]

^<<v5-32-8,8>>^ Quando o Altíssimo distribuiu a terra entre as nações, quando dividiu a humanidade, fixou os limites dos povos, de acordo com o número dos filhos de Israel.

[[v5-32-9]]

^<<v5-32-9,9>>^ "Pois o povo de Israel pertence ao SENHOR; Jacó é sua propriedade especial.

[[v5-32-10]]

^<<v5-32-10,10>>^ Encontrou-os numa terra deserta, numa região desolada e de ventos uivantes. Cercou-os e cuidou deles, protegeu-os como a pupila de seus olhos.

[[v5-32-11]]

^<<v5-32-11,11>>^ Como a águia que incentiva seus filhotes e paira sobre a ninhada, ele estendeu as asas para tomá-los e levá-los em segurança sobre suas penas.

[[v5-32-12]]

^<<v5-32-12,12>>^ O SENHOR, e mais ninguém, os guiou; nenhum deus estrangeiro os conduziu.

[[v5-32-13]]

^<<v5-32-13,13>>^ Ele os fez cavalgar sobre os lugares altos da terra e alimentar-se dos frutos dos campos. Nutriu-os com mel da rocha e azeite dos altos rochedos.

[[v5-32-14]]

^<<v5-32-14,14>>^ Alimentou-os com coalhada do gado e leite do rebanho, com a gordura de cordeiros, de carneiros e de bodes de Basã. Comeram o melhor do trigo e beberam do vinho mais fino que as uvas podem dar.

[[v5-32-15]]

^<<v5-32-15,15>>^ "Mas Jesurum não demorou a engordar e se rebelar; o povo se tornou pesado, corpulento e empanturrado! Então abandonaram o Deus que os criou, fizeram pouco caso da Rocha de sua salvação.

[[v5-32-16]]

^<<v5-32-16,16>>^ Provocaram seu zelo, adorando deuses estrangeiros; despertaram sua fúria com ídolos detestáveis.

[[v5-32-17]]

^<<v5-32-17,17>>^ Ofereceram sacrifícios a demônios que não são Deus, a deuses que não conheciam, deuses novos, sem história, deuses que seus antepassados jamais temeram.

[[v5-32-18]]

^<<v5-32-18,18>>^ Abandonaram a Rocha que os gerou, esqueceram-se do Deus que os fez nascer.

[[v5-32-19]]

^<<v5-32-19,19>>^ "O SENHOR viu isso e se afastou, provocado à ira por seus filhos e filhas.

[[v5-32-20]]

^<<v5-32-20,20>>^ Disse: ‘Eu os abandonarei; veremos o que será deles! Pois são uma geração perversa, filhos infiéis.

[[v5-32-21]]

^<<v5-32-21,21>>^ Provocaram meu ciúme adorando coisas que não são Deus; despertaram minha ira com seus ídolos inúteis. Agora, provocarei seu ciúme com uma gente que nem sequer é povo; despertarei sua ira por meio de uma nação insensata.

[[v5-32-22]]

^<<v5-32-22,22>>^ Pois minha ira arde como o fogo e queima até as profundezas da sepultura. Devora a terra e todas as suas colheitas e incendeia os alicerces dos montes.

[[v5-32-23]]

^<<v5-32-23,23>>^ Amontoarei calamidades sobre eles e os derrubarei com minhas flechas.

[[v5-32-24]]

^<<v5-32-24,24>>^ Eu os enfraquecerei com fome, febre alta e enfermidade mortal. Enviarei as presas de animais selvagens, e o veneno das serpentes que se arrastam no pó.

[[v5-32-25]]

^<<v5-32-25,25>>^ Fora de casa, a espada trará morte; dentro dela, o pavor atingirá rapazes e moças, crianças e idosos.

[[v5-32-26]]

^<<v5-32-26,26>>^ Meu desejo era aniquilá-los, apagar até sua lembrança dentre os povos.

[[v5-32-27]]

^<<v5-32-27,27>>^ Mas temi a reação dos inimigos de Israel, que entenderiam mal e diriam: ‘Foi o nosso poder que triunfou! O SENHOR nada teve a ver com isso!’".

[[v5-32-28]]

^<<v5-32-28,28>>^ "Israel, porém, é uma nação sem juízo; seu povo é tolo, sem entendimento.

[[v5-32-29]]

^<<v5-32-29,29>>^ Ah, se fossem sábios e compreendessem estas coisas! Ah, se soubessem o fim que os espera!

[[v5-32-30]]

^<<v5-32-30,30>>^ Como poderia uma só pessoa perseguir mil deles, e duas pessoas fazer dez mil fugirem, a não ser que sua Rocha os tivesse vendido, a não ser que o SENHOR os tivesse entregado?

[[v5-32-31]]

^<<v5-32-31,31>>^ Mas a rocha de nossos inimigos não é como nossa Rocha, como até eles mesmos reconhecem.

[[v5-32-32]]

^<<v5-32-32,32>>^ A videira deles vem da videira de Sodoma, dos campos de Gomorra. As uvas deles são veneno, e seus cachos são amargos.

[[v5-32-33]]

^<<v5-32-33,33>>^ O vinho deles é veneno de cobras, peçonha mortal de serpentes.

[[v5-32-34]]

^<<v5-32-34,34>>^ "O SENHOR diz: ‘Acaso não selei estas coisas e as guardei em meus tesouros?

[[v5-32-35]]

^<<v5-32-35,35>>^ A vingança cabe a mim, eu lhes darei o troco; no devido tempo, seus pés escorregarão. O dia da calamidade chegará, e seu destino os alcançará’.

[[v5-32-36]]

^<<v5-32-36,36>>^ "Por certo o SENHOR julgará seu povo, e mudará seus planos para seus servos, quando vir que a força deles se esgotou e que ninguém sobrou, nem escravo nem livre.

[[v5-32-37]]

^<<v5-32-37,37>>^ Então ele perguntará: ‘Onde estão seus deuses, as rochas em que se refugiaram?

[[v5-32-38]]

^<<v5-32-38,38>>^ Onde estão os deuses que comeram a gordura de seus sacrifícios e beberam o vinho de suas ofertas? Que esses deuses se levantem e os socorram! Que eles lhes deem abrigo!

[[v5-32-39]]

^<<v5-32-39,39>>^ Vejam agora que eu sou o único; não há outro deus além de mim! Causo a morte e dou a vida, causo a ferida e faço sarar; ninguém pode escapar de minha mão poderosa!

[[v5-32-40]]

^<<v5-32-40,40>>^ Agora, levanto minha mão para o céu e declaro: ‘Tão certo quanto eu vivo,

[[v5-32-41]]

^<<v5-32-41,41>>^ quando eu afiar minha espada reluzente, e começar a fazer justiça, eu me vingarei de meus inimigos e darei o troco aos que me rejeitaram.

[[v5-32-42]]

^<<v5-32-42,42>>^ Farei minhas flechas se embebedarem de sangue, e minha espada devorará carne: o sangue dos massacrados e dos prisioneiros, e as cabeças dos líderes inimigos’.

[[v5-32-43]]

^<<v5-32-43,43>>^ "Alegrem-se com ele, ó céus, e todos os anjos de Deus o adorem. Alegrem-se com seu povo, ó nações, e todos os anjos se fortaleçam nele; Pois ele retribuirá o sangue de seus filhos e se vingará de seus inimigos. Ele dará o troco aos que o odeiam e purificará a terra de seu povo".

[[v5-32-44]]

^<<v5-32-44,44>>^ Então Moisés foi com Josué, filho de Num, e recitou todas as palavras dessa canção para o povo.

[[v5-32-45]]

^<<v5-32-45,45>>^ Quando Moisés terminou de recitar todas essas palavras ao povo de Israel,

[[v5-32-46]]

^<<v5-32-46,46>>^ acrescentou: "Levem a sério todas as advertências que hoje lhes dei. Transmitam-nas como ordens a seus filhos, para que eles cumpram fielmente todos os termos desta lei.

[[v5-32-47]]

^<<v5-32-47,47>>^ Não são palavras vazias; são a vida de vocês! Se obedecerem a elas, terão vida longa na terra da qual tomarão posse quando atravessarem o rio Jordão".

[[v5-32-48]]

^<<v5-32-48,48>>^ Naquele mesmo dia, o SENHOR disse a Moisés:

[[v5-32-49]]

^<<v5-32-49,49>>^ "Vá a Moabe, às montanhas a leste do rio, e suba o monte Nebo, do lado oposto de Jericó. Veja a terra de Canaã, a terra que dou aos israelitas como sua propriedade.

[[v5-32-50]]

^<<v5-32-50,50>>^ Você morrerá ali no monte e será reunido a seus antepassados, como Arão morreu no monte Hor e foi reunido a seus antepassados.

[[v5-32-51]]

^<<v5-32-51,51>>^ Será assim porque vocês dois quebraram minha confiança diante dos israelitas nas águas de Meribá, em Cades, no deserto de Zim. Não honraram minha santidade para os israelitas.

[[v5-32-52]]

^<<v5-32-52,52>>^ Por isso você verá a terra de longe, mas não entrará na terra que dou ao povo de Israel".

'''

xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[&#60; Capítulo Anterior] | <<v5-32-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[Próximo Capítulo &#62;]