include::./index.adoc[]

[[v34-3-0]]
=== Naum, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v34-3-1]]

^<<v34-3-1,1>>^ Que aflição espera Nínive, cidade de homicídio e mentiras! É cheia de riquezas tomadas à força, e nunca lhe faltam vítimas.

[[v34-3-2]]

^<<v34-3-2,2>>^ Ouçam o estalo de chicotes, o estrondo de rodas! Os cavalos vêm galopando, e os carros de guerra sacodem sem parar.

[[v34-3-3]]

^<<v34-3-3,3>>^ Vejam as espadas faiscantes e as lanças reluzentes quando passa a cavalaria! Há incontáveis mortos, montes de cadáveres. Os corpos são tantos que os vivos neles tropeçam.

[[v34-3-4]]

^<<v34-3-4,4>>^ Tudo isso porque Nínive, prostituta bela, dona de encantamentos mortais, seduziu as nações com sua beleza. Ensinou a elas sua magia e enfeitiçou gente de toda parte.

[[v34-3-5]]

^<<v34-3-5,5>>^ "Sou seu inimigo!", diz o SENHOR dos Exércitos. "Agora levantarei suas vestes e mostrarei às nações sua nudez e vergonha.

[[v34-3-6]]

^<<v34-3-6,6>>^ Cobrirei você de sujeira e mostrarei ao mundo como é desprezível.

[[v34-3-7]]

^<<v34-3-7,7>>^ Todos que a virem se afastarão e dirão: ‘Nínive está arruinada! Onde estão os que choram por ela?’. Alguém lamentará sua destruição?"

[[v34-3-8]]

^<<v34-3-8,8>>^ Acaso você é melhor que a cidade de Tebas, situada junto ao rio Nilo e cercada de água? Por todos os lados era protegida pelo rio, e as águas eram seus muros.

[[v34-3-9]]

^<<v34-3-9,9>>^ A Etiópia e a terra do Egito lhe davam apoio ilimitado. A naçõe de Pute e a Líbia estavam entre seus aliados.

[[v34-3-10]]

^<<v34-3-10,10>>^ E, no entanto, Tebas foi conquistada, e seus habitantes, levados como escravos. Seus bebês foram lançados com violência contra as pedras nas ruas. Soldados tiraram sortes para decidir quem levaria oficiais egípcios como servos; todos os seus líderes foram acorrentados.

[[v34-3-11]]

^<<v34-3-11,11>>^ E você, Nínive, também tropeçará como um bêbado e se esconderá de medo do inimigo que ataca.

[[v34-3-12]]

^<<v34-3-12,12>>^ Todas as suas fortalezas cairão; serão devoradas como figos maduros que caem na boca de quem sacode a árvore.

[[v34-3-13]]

^<<v34-3-13,13>>^ Seus soldados ficarão fracos e indefesos como mulheres. Os portões de sua terra serão escancarados para o inimigo, e fogo consumirá as trancas.

[[v34-3-14]]

^<<v34-3-14,14>>^ Prepare-se para o cerco! Estoque água! Reforce suas defesas! Entre nos buracos para pisar o barro, coloque-o nas formas e faça tijolos para reparar os muros!

[[v34-3-15]]

^<<v34-3-15,15>>^ Mesmo assim, o fogo a devorará; a espada a exterminará. O inimigo a consumirá como gafanhotos que devoram tudo pela frente. Mesmo que você se multiplique como gafanhotos, não haverá como escapar.

[[v34-3-16]]

^<<v34-3-16,16>>^ Seus comerciantes se tornaram mais numerosos que as estrelas do céu. Mas, como nuvem de gafanhotos, devastam a terra e voam para longe.

[[v34-3-17]]

^<<v34-3-17,17>>^ Seus guardas e oficiais também são como gafanhotos, que se ajuntam sobre os muros nos dias frios. Mas, como gafanhotos que voam embora quando o sol aparece, todos vão para longe e desaparecem.

[[v34-3-18]]

^<<v34-3-18,18>>^ Seus líderes dormem, ó rei assírio; seus nobres estão mortos, estendidos no pó. Seu povo está espalhado pelos montes, e não há quem os reúna.

[[v34-3-19]]

^<<v34-3-19,19>>^ Não há cura para sua ferida; ela é mortal. Todos que ouvirem sobre sua destruição baterão palmas de alegria. Onde se poderá encontrar alguém que não sofreu com sua constante crueldade?

'''

xref:034-naum/034-naum-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[Próximo Capítulo &#62;]