include::./index.adoc[]

[[v34-1-0]]
=== Naum, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v34-1-1]]

^<<v34-1-1,1>>^ Naum, que vivia em Elcós, recebeu numa visão esta mensagem acerca de Nínive.

[[v34-1-2]]

^<<v34-1-2,2>>^ O SENHOR é Deus zeloso, cheio de vingança e ira. Vinga-se de todos que a ele se opõem e reserva sua fúria para seus inimigos.

[[v34-1-3]]

^<<v34-1-3,3>>^ O SENHOR é lento para se irar, mas tem grande poder e nunca deixa de castigar o culpado. Demonstra seu poder no vendaval e na tempestade; as nuvens são poeira debaixo de seus pés.

[[v34-1-4]]

^<<v34-1-4,4>>^ À sua ordem, os oceanos secam e os rios desaparecem. Os pastos verdejantes de Basã e do Carmelo se esvaem, e os bosques do Líbano murcham.

[[v34-1-5]]

^<<v34-1-5,5>>^ Em sua presença, os montes tremem e as colinas se derretem; a terra estremece e seus habitantes são destruídos.

[[v34-1-6]]

^<<v34-1-6,6>>^ Quem pode resistir à sua indignação? Quem pode sobreviver à sua ira ardente? Sua fúria queima como fogo, e os montes desabam em sua presença.

[[v34-1-7]]

^<<v34-1-7,7>>^ O SENHOR é bom; é forte refúgio quando vem a aflição. Está perto dos que nele confiam,

[[v34-1-8]]

^<<v34-1-8,8>>^ mas arrasará seus inimigos com uma tremenda inundação. Perseguirá seus adversários escuridão adentro.

[[v34-1-9]]

^<<v34-1-9,9>>^ Por que vocês tramam contra o SENHOR? Ele os destruirá com um só golpe; não precisará vir outra vez.

[[v34-1-10]]

^<<v34-1-10,10>>^ Seus inimigos, emaranhados como espinheiros e cambaleantes como bêbados, serão queimados como palha seca.

[[v34-1-11]]

^<<v34-1-11,11>>^ Ó Nínive, quem é esse seu conselheiro perverso, que trama o mal contra o SENHOR?

[[v34-1-12]]

^<<v34-1-12,12>>^ Assim diz o SENHOR: "Embora os assírios tenham muitos aliados, serão destruídos e desaparecerão. Ó meu povo, eu o castiguei antes, mas não o castigarei outra vez.

[[v34-1-13]]

^<<v34-1-13,13>>^ Agora quebrarei o jugo sobre seu pescoço e arrancarei as correntes de sua opressão".

[[v34-1-14]]

^<<v34-1-14,14>>^ E assim diz o SENHOR acerca dos assírios: "Vocês não terão mais filhos para dar continuidade ao seu nome; destruirei todos os ídolos nos templos de seus deuses. Estou preparando uma sepultura para vocês, pois são desprezíveis!".

[[v34-1-15]]

^<<v34-1-15,15>>^ Vejam, um mensageiro vem pelas montanhas com boas notícias! Ele traz uma mensagem de paz. Celebrem suas festas, ó habitantes de Judá, e cumpram seus votos, pois seus inimigos perversos nunca mais invadirão sua terra; serão completamente destruídos.

'''

xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[&#60; Capítulo Anterior] | <<v34-1-0,Topo>> | xref:034-naum/034-naum-002.adoc#v34-2-0[Próximo Capítulo &#62;]