include::./index.adoc[]

[[v34-2-0]]
=== Naum, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v34-2-1]]

^<<v34-2-1,1>>^ Ó Nínive, seu inimigo vem destruí-la. Guarde as muralhas! Vigie as estradas! Prepare suas defesas! Reúna suas forças!

[[v34-2-2]]

^<<v34-2-2,2>>^ Embora os saqueadores tenham despojado Israel, o SENHOR restaurará sua honra. Os ramos da videira foram arrancados, mas ele restaurará seu esplendor.

[[v34-2-3]]

^<<v34-2-3,3>>^ Os escudos de seus guerreiros são vermelhos; vejam os uniformes escarlates dos soldados valentes! Observem seus reluzentes carros de guerra se alinharem, enquanto as lanças se agitam acima deles.

[[v34-2-4]]

^<<v34-2-4,4>>^ Os implacáveis carros de guerra percorrem as ruas e atravessam velozes as praças. Brilham como tochas de fogo e se movem com a rapidez de relâmpagos.

[[v34-2-5]]

^<<v34-2-5,5>>^ Os oficiais são convocados e, de tanta pressa, saem tropeçando, correndo para os muros a fim de organizar as defesas.

[[v34-2-6]]

^<<v34-2-6,6>>^ As comportas do rio foram abertas! O palácio está prestes a desabar!

[[v34-2-7]]

^<<v34-2-7,7>>^ O exílio de Nínive foi decretado, e todas as servas lamentam sua derrota. Gemem como pombas e batem no peito em sinal de tristeza.

[[v34-2-8]]

^<<v34-2-8,8>>^ Nínive é como um açude rompido, que deixa vazar seu povo. "Parem! Parem!", alguém grita, mas ninguém olha para trás.

[[v34-2-9]]

^<<v34-2-9,9>>^ Saqueiem a prata! Levem o ouro! Os tesouros de Nínive não têm fim; sua riqueza é incalculável.

[[v34-2-10]]

^<<v34-2-10,10>>^ A cidade é saqueada e fica vazia e arruinada; corações se derretem e joelhos vacilam. O povo fica angustiado, de rosto pálido, tremendo de medo.

[[v34-2-11]]

^<<v34-2-11,11>>^ Onde está agora a grande Nínive, toca cheia de leões? Ali o povo, como leões e seus filhotes, andava livremente e sem temor.

[[v34-2-12]]

^<<v34-2-12,12>>^ O leão despedaçava a carne para seus filhotes e estrangulava a presa para a leoa. Enchia sua toca de presas e suas cavernas, de despojos.

[[v34-2-13]]

^<<v34-2-13,13>>^ "Sou seu inimigo!", diz o SENHOR dos Exércitos. "Em breve seus carros serão queimados, e seus jovens morrerão na batalha. Você nunca mais saqueará nações conquistadas; jamais se ouvirá novamente a voz de seus mensageiros."

'''

xref:034-naum/034-naum-001.adoc#v34-1-0[&#60; Capítulo Anterior] | <<v34-2-0,Topo>> | xref:034-naum/034-naum-003.adoc#v34-3-0[Próximo Capítulo &#62;]