include::./index.adoc[]

[[v48-2-0]]
=== Gálatas, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v48-2-1]]

^<<v48-2-1,1>>^ Catorze anos depois, voltei a Jerusalém, dessa vez com Barnabé, e Tito também nos acompanhou.

[[v48-2-2]]

^<<v48-2-2,2>>^ Fui para lá por causa de uma revelação. Reuni-me em particular com os líderes e compartilhei com eles as boas-novas que tenho anunciado aos gentios. Queria me certificar de que estávamos de acordo, pois temia que meus esforços, anteriores e presentes, fossem considerados inúteis.

[[v48-2-3]]

^<<v48-2-3,3>>^ Mas eles me apoiaram e nem sequer exigiram que Tito, que me acompanhava, fosse circuncidado, embora fosse gentio.

[[v48-2-4]]

^<<v48-2-4,4>>^ Essa questão foi levantada apenas por causa de alguns falsos irmãos que se infiltraram em nosso meio para nos espionar e nos tirar a liberdade que temos em Cristo Jesus. Sua intenção era nos escravizar,

[[v48-2-5]]

^<<v48-2-5,5>>^ mas não cedemos a eles nem por um momento, a fim de preservar a verdade das boas-novas para vocês.

[[v48-2-6]]

^<<v48-2-6,6>>^ Quanto aos líderes — cuja reputação, a propósito, não fez diferença alguma para mim, pois Deus não age com favoritismo —, nada tiveram a acrescentar àquilo que eu pregava.

[[v48-2-7]]

^<<v48-2-7,7>>^ Ao contrário, viram que me havia sido confiada a responsabilidade de anunciar as boas-novas aos gentios, assim como a Pedro tinha sido confiada a responsabilidade de anunciar as boas-novas aos judeus.

[[v48-2-8]]

^<<v48-2-8,8>>^ Pois o mesmo Deus que atuou por meio de Pedro como apóstolo aos judeus também atuou por meu intermédio como apóstolo aos gentios.

[[v48-2-9]]

^<<v48-2-9,9>>^ De fato, Tiago, Pedro e João, tidos como colunas, reconheceram a graça que me foi dada e aceitaram Barnabé e a mim como seus colaboradores. Eles nos incentivaram a dar continuidade à pregação aos gentios, enquanto eles prosseguiriam no trabalho com os judeus.

[[v48-2-10]]

^<<v48-2-10,10>>^ Sua única sugestão foi que continuássemos a ajudar os pobres, o que sempre fiz com dedicação.

[[v48-2-11]]

^<<v48-2-11,11>>^ Mas, quando Pedro veio a Antioquia, tive de opor-me a ele abertamente, pois o que ele fez foi muito errado.

[[v48-2-12]]

^<<v48-2-12,12>>^ No começo, quando chegou, ele comia com os gentios. Mais tarde, porém, quando vieram alguns amigos de Tiago, começou a se afastar, com medo daqueles que insistiam na necessidade de circuncisão.

[[v48-2-13]]

^<<v48-2-13,13>>^ Como resultado, outros judeus imitaram a hipocrisia de Pedro, e até mesmo Barnabé se deixou levar por ela.

[[v48-2-14]]

^<<v48-2-14,14>>^ Quando vi que não estavam seguindo a verdade das boas-novas, disse a Pedro diante de todos: "Se você, que é judeu de nascimento, vive como gentio, e não como judeu, por que agora obriga esses gentios a viverem como judeus?

[[v48-2-15]]

^<<v48-2-15,15>>^ Você e eu somos judeus de nascimento, e não pecadores, como os judeus consideram os gentios.

[[v48-2-16]]

^<<v48-2-16,16>>^ E, no entanto, sabemos que uma pessoa é declarada justa diante de Deus pela fé em Jesus Cristo, e não pela obediência à lei. E cremos em Cristo Jesus, para que fôssemos declarados justos pela fé em Cristo, e não porque obedecemos à lei. Pois ninguém é declarado justo diante de Deus pela obediência à lei".

[[v48-2-17]]

^<<v48-2-17,17>>^ Mas, se a busca da justiça por meio de Cristo nos torna culpados de abandonar a lei, isso torna Cristo responsável por nosso pecado? De maneira nenhuma!

[[v48-2-18]]

^<<v48-2-18,18>>^ Se, pois, reconstruo o antigo sistema da lei que já destruí, então faço de mim mesmo transgressor da lei.

[[v48-2-19]]

^<<v48-2-19,19>>^ Pois, quando procurei viver por meio da lei, ela me condenou. Portanto, morri para a lei a fim de viver para Deus.

[[v48-2-20]]

^<<v48-2-20,20>>^ Fui crucificado com Cristo; assim, já não sou eu quem vive, mas Cristo vive em mim. Portanto, vivo neste corpo terreno pela fé no Filho de Deus, que me amou e se entregou por mim.

[[v48-2-21]]

^<<v48-2-21,21>>^ Não considero a graça de Deus algo sem sentido. Pois, se a obediência à lei nos tornasse justos diante de Deus, não haveria necessidade alguma de Cristo morrer.

'''

xref:048-galatas/048-galatas-001.adoc#v48-1-0[&#60; Capítulo Anterior] | <<v48-2-0,Topo>> | xref:048-galatas/048-galatas-003.adoc#v48-3-0[Próximo Capítulo &#62;]