include::./index.adoc[]

[[v48-4-0]]
=== Gálatas, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v48-4-1]]

^<<v48-4-1,1>>^ Portanto, pensem da seguinte forma: enquanto não atingir a idade adequada, o herdeiro não está numa posição muito melhor que a de um escravo, apesar de ser dono de todos os bens.

[[v48-4-2]]

^<<v48-4-2,2>>^ Deve obedecer a seus tutores e administradores até a idade determinada por seu pai.

[[v48-4-3]]

^<<v48-4-3,3>>^ O mesmo acontecia conosco. Éramos como crianças; éramos escravos dos princípios básicos deste mundo.

[[v48-4-4]]

^<<v48-4-4,4>>^ Mas, quando chegou o tempo certo, Deus enviou seu Filho, nascido de uma mulher e sob a lei.

[[v48-4-5]]

^<<v48-4-5,5>>^ Assim o fez para resgatar a nós que estávamos sob a lei, a fim de nos adotar como seus filhos.

[[v48-4-6]]

^<<v48-4-6,6>>^ E, porque nós somos seus filhos, Deus enviou ao nosso coração o Espírito de seu Filho, e por meio dele clamamos: " Aba , Pai".

[[v48-4-7]]

^<<v48-4-7,7>>^ Agora você já não é escravo, mas filho de Deus. E, uma vez que é filho, Deus o tornou herdeiro dele.

[[v48-4-8]]

^<<v48-4-8,8>>^ Antes de conhecerem a Deus, vocês eram escravos de supostos deuses que, na verdade, nem existem.

[[v48-4-9]]

^<<v48-4-9,9>>^ Agora que conhecem a Deus, ou melhor, agora que Deus os conhece, por que desejam voltar atrás e tornar-se novamente escravos dos frágeis e inúteis princípios básicos deste mundo?

[[v48-4-10]]

^<<v48-4-10,10>>^ Vocês insistem em guardar certos dias, meses, estações ou anos.

[[v48-4-11]]

^<<v48-4-11,11>>^ Temo por vocês. Talvez meu árduo trabalho em seu favor tenha sido inútil.

[[v48-4-12]]

^<<v48-4-12,12>>^ Irmãos, peço-lhes que sejam como eu, pois eu também sou como vocês. E vocês não me trataram mal

[[v48-4-13]]

^<<v48-4-13,13>>^ e certamente se lembram de que eu estava doente quando lhes anunciei as boas-novas pela primeira vez.

[[v48-4-14]]

^<<v48-4-14,14>>^ Embora minha saúde precária fosse uma tentação para me rejeitarem, vocês não me desprezaram nem me mandaram embora. Ao contrário, acolheram-me e cuidaram de mim como se eu fosse um anjo de Deus, ou mesmo o próprio Cristo Jesus.

[[v48-4-15]]

^<<v48-4-15,15>>^ Que aconteceu com a alegria que vocês demonstraram naquela ocasião? Estou certo de que, se fosse possível, teriam arrancado os próprios olhos e os teriam dado a mim.

[[v48-4-16]]

^<<v48-4-16,16>>^ Acaso me tornei inimigo de vocês porque lhes digo a verdade?

[[v48-4-17]]

^<<v48-4-17,17>>^ Esses falsos mestres estão extremamente ansiosos para agradá-los, mas suas intenções não são boas. Querem afastá-los de mim para que dependam deles.

[[v48-4-18]]

^<<v48-4-18,18>>^ Se alguém deseja agradá-los, muito bem; mas que o faça sempre, e não só quando estou com vocês.

[[v48-4-19]]

^<<v48-4-19,19>>^ Ó meus filhos queridos, sinto como se estivesse passando outra vez pelas dores de parto por sua causa, e elas continuarão até que Cristo seja plenamente desenvolvido em vocês.

[[v48-4-20]]

^<<v48-4-20,20>>^ Gostaria de poder estar aí com vocês para lhes falar em outro tom. Mas, distante como estou, não sei o que mais fazer para ajudá-los.

[[v48-4-21]]

^<<v48-4-21,21>>^ Digam-me, vocês que desejam viver debaixo da lei: acaso sabem o que a lei diz de fato?

[[v48-4-22]]

^<<v48-4-22,22>>^ De acordo com as Escrituras, Abraão teve dois filhos, um nascido de uma escrava e outro de sua esposa, que era livre.

[[v48-4-23]]

^<<v48-4-23,23>>^ O filho da escrava nasceu segundo a vontade humana; o filho da mulher livre nasceu segundo a promessa.

[[v48-4-24]]

^<<v48-4-24,24>>^ Essas duas mulheres ilustram duas alianças. A primeira, Hagar, representa o monte Sinai, onde o povo recebeu a lei que o escravizou.

[[v48-4-25]]

^<<v48-4-25,25>>^ E Hagar, que é o monte Sinai, na Arábia, representa a Jerusalém de agora, pois ela e seus filhos vivem sob a escravidão da lei.

[[v48-4-26]]

^<<v48-4-26,26>>^ A segunda, Sara, representa a Jerusalém celestial. Ela é a mulher livre, e é nossa mãe.

[[v48-4-27]]

^<<v48-4-27,27>>^ Como dizem as Escrituras: "Alegre-se, mulher sem filhos, você que nunca deu à luz! Grite de alegria, você que nunca esteve em trabalho de parto! Pois a abandonada agora tem mais filhos que a mulher que vive com o marido".

[[v48-4-28]]

^<<v48-4-28,28>>^ E vocês, irmãos, são filhos da promessa, como Isaque.

[[v48-4-29]]

^<<v48-4-29,29>>^ Ismael, o filho nascido da vontade humana, perseguiu Isaque, o filho nascido do poder do Espírito, e o mesmo ocorre agora.

[[v48-4-30]]

^<<v48-4-30,30>>^ Mas o que dizem as Escrituras sobre isso? "Livre-se da escrava e do filho dela, pois o filho da escrava não será herdeiro junto com o filho da mulher livre."

[[v48-4-31]]

^<<v48-4-31,31>>^ Portanto, irmãos, não somos filhos da escrava; somos filhos da mulher livre.

'''

xref:048-galatas/048-galatas-003.adoc#v48-3-0[&#60; Capítulo Anterior] | <<v48-4-0,Topo>> | xref:048-galatas/048-galatas-005.adoc#v48-5-0[Próximo Capítulo &#62;]