include::./index.adoc[]

[[v48-3-0]]
=== Gálatas, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v48-3-1]]

^<<v48-3-1,1>>^ Ó gálatas insensatos! Quem os enfeitiçou? Jesus Cristo não lhes foi explicado tão claramente como se tivessem visto com os próprios olhos a morte dele na cruz?

[[v48-3-2]]

^<<v48-3-2,2>>^ Deixem-me perguntar apenas uma coisa: vocês receberam o Espírito porque obedeceram à lei ou porque creram na mensagem que ouviram?

[[v48-3-3]]

^<<v48-3-3,3>>^ Será que perderam o juízo? Tendo começado no Espírito, por que agora procuram tornar-se perfeitos por seus próprios esforços?

[[v48-3-4]]

^<<v48-3-4,4>>^ Será que foi à toa que passaram por tantos sofrimentos? É claro que não foi à toa!

[[v48-3-5]]

^<<v48-3-5,5>>^ Volto a perguntar: acaso aquele que lhes deu o Espírito e realizou milagres entre vocês agiu assim porque vocês obedeceram à lei ou porque creram na mensagem que ouviram?

[[v48-3-6]]

^<<v48-3-6,6>>^ Da mesma forma, "Abraão creu em Deus, e assim foi considerado justo".

[[v48-3-7]]

^<<v48-3-7,7>>^ Logo, os verdadeiros filhos de Abraão são aqueles que creem.

[[v48-3-8]]

^<<v48-3-8,8>>^ As Escrituras previram esse tempo em que Deus declararia os gentios justos por meio da fé. Ele anunciou essas boas-novas a Abraão há muito tempo, quando disse: "Todas as nações da terra serão abençoadas por seu intermédio".

[[v48-3-9]]

^<<v48-3-9,9>>^ Portanto, todos os que creem participam da mesma bênção que Abraão recebeu por crer.

[[v48-3-10]]

^<<v48-3-10,10>>^ Contudo, os que confiam na lei para serem declarados justos estão sob maldição, pois as Escrituras dizem: "Maldito quem não se mantiver obediente a tudo que está escrito no Livro da Lei".

[[v48-3-11]]

^<<v48-3-11,11>>^ É evidente, portanto, que ninguém pode ser declarado justo diante de Deus pela lei. Pois as Escrituras dizem: "O justo viverá pela fé".

[[v48-3-12]]

^<<v48-3-12,12>>^ A lei, porém, não é baseada na fé, pois diz: "Quem obedece à lei viverá por ela".

[[v48-3-13]]

^<<v48-3-13,13>>^ Mas Cristo nos resgatou da maldição pronunciada pela lei tomando sobre si a maldição por nossas ofensas. Pois as Escrituras dizem: "Maldito todo aquele que é pendurado num madeiro".

[[v48-3-14]]

^<<v48-3-14,14>>^ Por meio de Cristo Jesus, os gentios foram abençoados com a mesma bênção de Abraão, para que recebêssemos, pela fé, o Espírito prometido.

[[v48-3-15]]

^<<v48-3-15,15>>^ Irmãos, apresento-lhes um exemplo da vida diária. Ninguém pode anular ou fazer acréscimos a uma aliança irrevogável.

[[v48-3-16]]

^<<v48-3-16,16>>^ Pois bem, Deus fez a promessa a Abraão e a seu descendente. Observem que as Escrituras não dizem "a seus descendentes", como se fosse uma referência a muitos, mas sim "a seu descendente", isto é, Cristo.

[[v48-3-17]]

^<<v48-3-17,17>>^ É isto que quero dizer: a lei, que veio 430 anos depois, não pode anular a aliança que Deus estabeleceu com Abraão, pois nesse caso a promessa seria quebrada.

[[v48-3-18]]

^<<v48-3-18,18>>^ Portanto, se a herança pudesse ser recebida pela obediência à lei, ela não viria pela aceitação da promessa. No entanto, Deus, em sua bondade, a concedeu a Abraão como promessa.

[[v48-3-19]]

^<<v48-3-19,19>>^ Qual era, então, o propósito da lei? Ela foi acrescentada à promessa para mostrar às pessoas seus pecados. Mas a lei deveria durar apenas até a vinda do descendente prometido. Por meio de anjos, a lei foi entregue a um mediador.

[[v48-3-20]]

^<<v48-3-20,20>>^ O mediador, porém, só é necessário quando dois ou mais precisam chegar a um acordo, e Deus é um só.

[[v48-3-21]]

^<<v48-3-21,21>>^ Existe, portanto, algum conflito entre a lei e as promessas de Deus? De maneira nenhuma! Se a lei fosse capaz de nos conceder nova vida, seríamos declarados justos pela obediência a ela.

[[v48-3-22]]

^<<v48-3-22,22>>^ Mas as Escrituras afirmam que somos todos prisioneiros do pecado, de modo que nós, os que cremos, recebemos a promessa de libertação apenas pela fé em Jesus Cristo.

[[v48-3-23]]

^<<v48-3-23,23>>^ Antes que o caminho da fé se tornasse disponível, fomos colocados sob a custódia da lei e mantidos sob a sua guarda, até que essa fé fosse revelada.

[[v48-3-24]]

^<<v48-3-24,24>>^ Em outras palavras, a lei foi nosso guardião até a vinda de Cristo; ela nos protegeu até que, por meio da fé, pudéssemos ser declarados justos.

[[v48-3-25]]

^<<v48-3-25,25>>^ Agora que veio o caminho da fé, não precisamos mais da lei como guardião.

[[v48-3-26]]

^<<v48-3-26,26>>^ Pois todos vocês são filhos de Deus por meio da fé em Cristo Jesus.

[[v48-3-27]]

^<<v48-3-27,27>>^ Todos que foram unidos com Cristo no batismo se revestiram de Cristo.

[[v48-3-28]]

^<<v48-3-28,28>>^ Não há mais judeu nem gentio, escravo nem livre, homem nem mulher, pois todos vocês são um em Cristo Jesus.

[[v48-3-29]]

^<<v48-3-29,29>>^ E agora que pertencem a Cristo, são verdadeiros filhos de Abraão, herdeiros dele segundo a promessa de Deus.

'''

xref:048-galatas/048-galatas-002.adoc#v48-2-0[&#60; Capítulo Anterior] | <<v48-3-0,Topo>> | xref:048-galatas/048-galatas-004.adoc#v48-4-0[Próximo Capítulo &#62;]