include::./index.adoc[]

[[v48-5-0]]
=== Gálatas, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v48-5-1]]

^<<v48-5-1,1>>^ Portanto, permaneçam firmes nessa liberdade, pois Cristo verdadeiramente nos libertou. Não se submetam novamente à escravidão da lei.

[[v48-5-2]]

^<<v48-5-2,2>>^ Prestem atenção! Eu, Paulo, lhes digo: se vocês se deixarem ser circuncidados, Cristo de nada lhes servirá.

[[v48-5-3]]

^<<v48-5-3,3>>^ Volto a dizer: todo aquele que se deixa ser circuncidado deve obedecer a toda a lei.

[[v48-5-4]]

^<<v48-5-4,4>>^ Pois, se vocês procuram tornar-se justos diante de Deus pelo cumprimento da lei, foram separados de Cristo e caíram para longe da graça.

[[v48-5-5]]

^<<v48-5-5,5>>^ Mas nós que vivemos pelo Espírito esperamos ansiosamente receber pela fé a justiça que Deus nos prometeu.

[[v48-5-6]]

^<<v48-5-6,6>>^ Pois, em Cristo Jesus, não há benefício algum em ser ou não circuncidado. O que importa é a fé que se expressa pelo amor.

[[v48-5-7]]

^<<v48-5-7,7>>^ Vocês estavam indo bem na corrida; quem os impediu de seguir a verdade?

[[v48-5-8]]

^<<v48-5-8,8>>^ Certamente não foi Deus quem os levou a pensar assim, pois ele os chamou para serem livres.

[[v48-5-9]]

^<<v48-5-9,9>>^ Um pouco de fermento se espalha por toda a massa.

[[v48-5-10]]

^<<v48-5-10,10>>^ Confio que o Senhor os guardará de crer em falsos ensinamentos. Aquele que os perturbar, seja ele quem for, será julgado.

[[v48-5-11]]

^<<v48-5-11,11>>^ Irmãos, se eu ainda prego que vocês devem ser circuncidados, como dizem alguns, por que continuo a ser perseguido? Se eu não pregasse a salvação exclusivamente por meio da cruz, ninguém se ofenderia.

[[v48-5-12]]

^<<v48-5-12,12>>^ Esses sujeitos que os perturbam deveriam castrar a si mesmos!

[[v48-5-13]]

^<<v48-5-13,13>>^ Porque vocês, irmãos, foram chamados para viver em liberdade. Não a usem, porém, para satisfazer sua natureza humana. Ao contrário, usem-na para servir uns aos outros em amor.

[[v48-5-14]]

^<<v48-5-14,14>>^ Pois toda a lei pode ser resumida neste único mandamento: "Ame o seu próximo como a si mesmo".

[[v48-5-15]]

^<<v48-5-15,15>>^ Mas, se vocês estão sempre mordendo e devorando uns aos outros, tenham cuidado, pois correm o risco de se destruírem.

[[v48-5-16]]

^<<v48-5-16,16>>^ Por isso digo: deixem que o Espírito guie sua vida. Assim, não satisfarão os anseios de sua natureza humana.

[[v48-5-17]]

^<<v48-5-17,17>>^ A natureza humana deseja fazer exatamente o oposto do que o Espírito quer, e o Espírito nos impele na direção contrária àquela desejada pela natureza humana. Essas duas forças se confrontam o tempo todo, de modo que vocês não têm liberdade de pôr em prática o que intentam fazer.

[[v48-5-18]]

^<<v48-5-18,18>>^ Quando, porém, são guiados pelo Espírito, não estão debaixo da lei.

[[v48-5-19]]

^<<v48-5-19,19>>^ Quando seguem os desejos da natureza humana, os resultados são extremamente claros: imoralidade sexual, impureza, sensualidade,

[[v48-5-20]]

^<<v48-5-20,20>>^ idolatria, feitiçaria, hostilidade, discórdias, ciúmes, acessos de raiva, ambições egoístas, dissensões, divisões,

[[v48-5-21]]

^<<v48-5-21,21>>^ inveja, bebedeiras, festanças desregradas e outros pecados semelhantes. Repito o que disse antes: quem pratica essas coisas não herdará o reino de Deus.

[[v48-5-22]]

^<<v48-5-22,22>>^ Mas o Espírito produz este fruto: amor, alegria, paz, paciência, amabilidade, bondade, fidelidade,

[[v48-5-23]]

^<<v48-5-23,23>>^ mansidão e domínio próprio. Não há lei contra essas coisas!

[[v48-5-24]]

^<<v48-5-24,24>>^ Aqueles que pertencem a Cristo Jesus crucificaram as paixões e os desejos de sua natureza humana.

[[v48-5-25]]

^<<v48-5-25,25>>^ Uma vez que vivemos pelo Espírito, sigamos a direção do Espírito em todas as áreas de nossa vida.

[[v48-5-26]]

^<<v48-5-26,26>>^ Não nos tornemos orgulhosos, provocando e invejando uns aos outros.

'''

xref:048-galatas/048-galatas-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatas/048-galatas-006.adoc#v48-6-0[Próximo Capítulo &#62;]