include::./index.adoc[]

[[v48-6-0]]
=== Gálatas, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v48-6-1]]

^<<v48-6-1,1>>^ Irmãos, se alguém for vencido por algum pecado, vocês que são guiados pelo Espírito devem, com mansidão, ajudá-lo a voltar ao caminho certo. E cada um cuide para não ser tentado.

[[v48-6-2]]

^<<v48-6-2,2>>^ Ajudem a levar os fardos uns dos outros e obedeçam, desse modo, à lei de Cristo.

[[v48-6-3]]

^<<v48-6-3,3>>^ Se vocês se consideram importantes demais para ajudar os outros, estão apenas enganando a si mesmos.

[[v48-6-4]]

^<<v48-6-4,4>>^ Cada um preste muita atenção em seu trabalho, pois então terá a satisfação de havê-lo feito bem e não precisará se comparar com os outros.

[[v48-6-5]]

^<<v48-6-5,5>>^ Porque cada um de nós é responsável pela própria conduta.

[[v48-6-6]]

^<<v48-6-6,6>>^ Aqueles que recebem o ensino da palavra devem repartir com seus mestres todas as coisas boas.

[[v48-6-7]]

^<<v48-6-7,7>>^ Não se deixem enganar: ninguém pode zombar de Deus. A pessoa sempre colherá aquilo que semear.

[[v48-6-8]]

^<<v48-6-8,8>>^ Quem vive apenas para satisfazer sua natureza humana colherá dessa natureza ruína e morte. Mas quem vive para agradar o Espírito colherá do Espírito a vida eterna.

[[v48-6-9]]

^<<v48-6-9,9>>^ Portanto, não nos cansemos de fazer o bem. No momento certo, teremos uma colheita de bênçãos, se não desistirmos.

[[v48-6-10]]

^<<v48-6-10,10>>^ Por isso, sempre que tivermos oportunidade, façamos o bem a todos, especialmente aos da família da fé.

[[v48-6-11]]

^<<v48-6-11,11>>^ Vejam com que letras grandes lhes escrevo, de próprio punho, estas palavras finais!

[[v48-6-12]]

^<<v48-6-12,12>>^ Aqueles que procuram obrigá-los a se circuncidarem desejam causar boa impressão para outros, a fim de não serem perseguidos por ensinar que somente a cruz de Cristo pode salvar.

[[v48-6-13]]

^<<v48-6-13,13>>^ E nem mesmo aqueles que defendem a circuncisão cumprem toda a lei. Querem que vocês sejam circuncidados só para que eles se gloriem disso.

[[v48-6-14]]

^<<v48-6-14,14>>^ Quanto a mim, que eu jamais me glorie em qualquer coisa, a não ser na cruz de nosso Senhor Jesus Cristo. Por causa dessa cruz meu interesse neste mundo foi crucificado, e o interesse do mundo em mim também morreu.

[[v48-6-15]]

^<<v48-6-15,15>>^ Não importa se fomos circuncidados ou não. O que importa é que fomos transformados em nova criação.

[[v48-6-16]]

^<<v48-6-16,16>>^ Que a paz e a misericórdia de Deus estejam sobre todos os que vivem de acordo com esse princípio e sobre o Israel de Deus.

[[v48-6-17]]

^<<v48-6-17,17>>^ De agora em diante, que ninguém me perturbe com essas coisas, pois levo em meu corpo cicatrizes que mostram que pertenço a Jesus.

[[v48-6-18]]

^<<v48-6-18,18>>^ Irmãos, que a graça de nosso Senhor Jesus Cristo esteja com o espírito de vocês. Amém.

'''

xref:048-galatas/048-galatas-005.adoc#v48-5-0[&#60; Capítulo Anterior] | <<v48-6-0,Topo>> | xref:049-efesios/049-efesios-001.adoc#v49-1-0[Próximo Capítulo &#62;]