include::./index.adoc[]

[[v21-9-0]]
=== Eclesiastes, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v21-9-1]]

^<<v21-9-1,1>>^ Dediquei-me também a investigar isto: embora os justos e os sábios, e também suas ações, estejam nas mãos de Deus, ninguém sabe o que os aguarda, se amor ou ódio.

[[v21-9-2]]

^<<v21-9-2,2>>^ No fim, todos têm o mesmo destino, seja a pessoa justa ou perversa, boa ou má, cerimonialmente pura ou impura, religiosa ou não. Ocorre o mesmo à pessoa de bem e ao pecador; aquele que faz promessas a Deus é tratado como o que teme fazê-lo.

[[v21-9-3]]

^<<v21-9-3,3>>^ É uma grande tragédia que todos debaixo do sol tenham o mesmo destino. Além disso, o coração das pessoas está cheio de maldade. Elas seguem seu próprio caminho de loucura, pois não há nada adiante, senão a morte.

[[v21-9-4]]

^<<v21-9-4,4>>^ Só para os vivos há esperança. Como dizem: "Melhor ser um cão vivo que um leão morto".

[[v21-9-5]]

^<<v21-9-5,5>>^ Os vivos pelo menos sabem que vão morrer, mas os mortos nada sabem. Já não têm recompensas para receber e caem no esquecimento.

[[v21-9-6]]

^<<v21-9-6,6>>^ Amar, odiar, invejar, tudo que já fizeram ao longo da vida passou há muito tempo. Já não participam de coisa alguma que acontece debaixo do sol.

[[v21-9-7]]

^<<v21-9-7,7>>^ Portanto, coma sua comida com prazer e beba seu vinho com alegria, pois Deus se agrada disso.

[[v21-9-8]]

^<<v21-9-8,8>>^ Vista roupas elegantes e use perfume.

[[v21-9-9]]

^<<v21-9-9,9>>^ Viva alegremente com a mulher que você ama todos os dias desta vida sem sentido que Deus lhe deu debaixo do sol, pois essa é a recompensa por todos os seus esforços neste mundo.

[[v21-9-10]]

^<<v21-9-10,10>>^ Tudo que fizer, faça bem feito, pois quando descer à sepultura não haverá trabalho, nem planos, nem conhecimento, nem sabedoria.

[[v21-9-11]]

^<<v21-9-11,11>>^ Observei outra coisa debaixo do sol. Aquele que corre mais rápido nem sempre ganha a corrida, e o guerreiro mais forte nem sempre vence a batalha. Às vezes os sábios passam fome, os sensatos não enriquecem, e os instruídos não alcançam sucesso. Tudo depende de se estar no lugar certo na hora certa.

[[v21-9-12]]

^<<v21-9-12,12>>^ Ninguém é capaz de prever quando virão os tempos difíceis. Como peixe na rede ou pássaro na armadilha, as pessoas caem em desgraça de modo repentino.

[[v21-9-13]]

^<<v21-9-13,13>>^ Outro exemplo de sabedoria me impressionou enquanto eu observava como as coisas funcionam debaixo do sol.

[[v21-9-14]]

^<<v21-9-14,14>>^ Havia uma cidade pequena, com poucos habitantes, e um grande rei veio com seu exército e a cercou.

[[v21-9-15]]

^<<v21-9-15,15>>^ Um homem sábio, mas muito pobre, usou sua sabedoria para salvar a cidade. Depois, porém, ninguém se lembrou de lhe agradecer.

[[v21-9-16]]

^<<v21-9-16,16>>^ Por isso, pensei: embora a sabedoria seja melhor que a força, o sábio é desprezado quando é pobre. Suas palavras logo são esquecidas.

[[v21-9-17]]

^<<v21-9-17,17>>^ É melhor ouvir as palavras calmas da pessoa sábia que os gritos do rei tolo.

[[v21-9-18]]

^<<v21-9-18,18>>^ É melhor ter sabedoria que armas de guerra, mas um só pecador destrói muitas coisas boas.

'''

xref:021-eclesiastes/021-eclesiastes-008.adoc#v21-8-0[&#60; Capítulo Anterior] | <<v21-9-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-010.adoc#v21-10-0[Próximo Capítulo &#62;]