include::./index.adoc[]

[[v21-3-0]]
=== Eclesiastes, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v21-3-1]]

^<<v21-3-1,1>>^ Há um momento certo para tudo, um tempo para cada atividade debaixo do céu.

[[v21-3-2]]

^<<v21-3-2,2>>^ Há tempo de nascer, e tempo de morrer; tempo de plantar, e tempo de colher.

[[v21-3-3]]

^<<v21-3-3,3>>^ Tempo de matar, e tempo de curar; tempo de derrubar, e tempo de construir.

[[v21-3-4]]

^<<v21-3-4,4>>^ Tempo de chorar, e tempo de rir; tempo de se entristecer, e tempo de dançar.

[[v21-3-5]]

^<<v21-3-5,5>>^ Tempo de espalhar pedras, e tempo de ajuntá-las; tempo de abraçar, e tempo de se afastar.

[[v21-3-6]]

^<<v21-3-6,6>>^ Tempo de procurar, e tempo de deixar de buscar; tempo de guardar, e tempo de jogar fora.

[[v21-3-7]]

^<<v21-3-7,7>>^ Tempo de rasgar, e tempo de remendar; tempo de calar, e tempo de falar.

[[v21-3-8]]

^<<v21-3-8,8>>^ Tempo de amar, e tempo de odiar; tempo de guerra, e tempo de paz.

[[v21-3-9]]

^<<v21-3-9,9>>^ O que as pessoas ganham com tanto trabalho árduo?

[[v21-3-10]]

^<<v21-3-10,10>>^ Vi o fardo que Deus pôs sobre toda a humanidade.

[[v21-3-11]]

^<<v21-3-11,11>>^ E, no entanto, Deus fez tudo apropriado para seu devido tempo. Ele colocou um senso de eternidade no coração humano, mas mesmo assim ninguém é capaz de entender toda a obra de Deus, do começo ao fim.

[[v21-3-12]]

^<<v21-3-12,12>>^ Concluí, portanto, que a melhor coisa a fazer é ser feliz e desfrutar a vida enquanto é possível.

[[v21-3-13]]

^<<v21-3-13,13>>^ Cada um deve comer e beber e desfrutar os frutos de seu trabalho, pois são presentes de Deus.

[[v21-3-14]]

^<<v21-3-14,14>>^ E sei que tudo que Deus faz é definitivo; não se pode acrescentar ou tirar nada. O propósito de Deus é que as pessoas o temam.

[[v21-3-15]]

^<<v21-3-15,15>>^ O que acontece agora já aconteceu antes, e o que acontecerá no futuro também já aconteceu, pois Deus faz as mesmas coisas acontecerem repetidamente.

[[v21-3-16]]

^<<v21-3-16,16>>^ Observei também que debaixo do sol há maldade onde deveria haver justiça. Sim, até os tribunais são corruptos.

[[v21-3-17]]

^<<v21-3-17,17>>^ Disse a mim mesmo: "No devido tempo, Deus julgará tanto os justos como os perversos, por tudo que fizeram".

[[v21-3-18]]

^<<v21-3-18,18>>^ Também refleti sobre a condição humana, como Deus mostra às pessoas que elas não são melhores que os animais.

[[v21-3-19]]

^<<v21-3-19,19>>^ Pois tanto pessoas como animais têm o mesmo destino: ambos respiram e ambos morrem. As pessoas não têm vantagem alguma sobre os animais. Isso não faz o menor sentido!

[[v21-3-20]]

^<<v21-3-20,20>>^ Todos vão para o mesmo lugar: vieram do pó e a ele retornam.

[[v21-3-21]]

^<<v21-3-21,21>>^ Afinal, quem pode afirmar que o espírito dos seres humanos vai para cima e o espírito dos animais desce para a terra?

[[v21-3-22]]

^<<v21-3-22,22>>^ Vi, portanto, que a melhor coisa a fazer é alegrar-se com seu trabalho. É isso que nos cabe na vida. Ninguém nos trará de volta para ver o que acontece depois que morremos.

'''

xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[&#60; Capítulo Anterior] | <<v21-3-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[Próximo Capítulo &#62;]