include::./index.adoc[]

[[v21-5-0]]
=== Eclesiastes, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v21-5-1]]

^<<v21-5-1,1>>^ Quando você entrar na casa de Deus, tome cuidado com o que faz e ouça com atenção. Age mal quem apresenta ofertas a Deus sem pensar.

[[v21-5-2]]

^<<v21-5-2,2>>^ Não se precipite em fazer promessas nem em apresentar suas questões a Deus. Afinal, Deus está nos céus, e você, na terra; portanto, fale pouco.

[[v21-5-3]]

^<<v21-5-3,3>>^ Do excesso de trabalho vem o sonho agitado; do excesso de palavras vêm as promessas do tolo.

[[v21-5-4]]

^<<v21-5-4,4>>^ Quando fizer uma promessa a Deus, não demore a cumpri-la, pois ele não se agrada dos tolos. Cumpra todas as promessas que fizer.

[[v21-5-5]]

^<<v21-5-5,5>>^ É melhor não dizer nada que fazer uma promessa e não cumprir.

[[v21-5-6]]

^<<v21-5-6,6>>^ Não permita que sua boca o leve a pecar. E não se defenda dizendo ao mensageiro do templo que a promessa foi um engano. Isso deixaria Deus irado, e ele poderia destruir tudo que você conquistou.

[[v21-5-7]]

^<<v21-5-7,7>>^ Sonhar demais é inútil, assim como falar muito. Em vez disso, tema a Deus.

[[v21-5-8]]

^<<v21-5-8,8>>^ Não se surpreenda se, em toda a terra, você vir os pobres sofrendo opressão pelos poderosos, e a justiça e o direito sendo pervertidos. Cada oficial é subordinado a uma autoridade superior, e a justiça se perde em meio à burocracia.

[[v21-5-9]]

^<<v21-5-9,9>>^ Até mesmo o rei tira para si o máximo proveito da terra.

[[v21-5-10]]

^<<v21-5-10,10>>^ Quem ama o dinheiro nunca terá o suficiente. Quem ama a riqueza nunca se satisfará com o que ganha. Não faz sentido viver desse modo!

[[v21-5-11]]

^<<v21-5-11,11>>^ Quanto mais você tem, mais pessoas aparecem para ajudá-lo a gastar. Portanto, de que serve a riqueza, senão para vê-la escapar por entre os dedos?

[[v21-5-12]]

^<<v21-5-12,12>>^ Quem trabalha com dedicação dorme bem, quer coma pouco, quer muito. As muitas riquezas, porém, não deixam o rico dormir.

[[v21-5-13]]

^<<v21-5-13,13>>^ Observei ainda outro grave problema debaixo do sol: o acúmulo de riquezas prejudica seu dono.

[[v21-5-14]]

^<<v21-5-14,14>>^ Se o dinheiro é colocado em investimentos arriscados e eles dão errado, perde-se tudo. No final, não sobra nada para deixar aos filhos.

[[v21-5-15]]

^<<v21-5-15,15>>^ Todos nós chegamos ao fim da vida nus e de mãos vazias, como no dia em que nascemos. Não levamos conosco o fruto de nosso trabalho.

[[v21-5-16]]

^<<v21-5-16,16>>^ Isto também é um grande mal: as pessoas vão embora deste mundo como vieram. Todo o seu esforço é inútil, como trabalhar para o vento.

[[v21-5-17]]

^<<v21-5-17,17>>^ Passam a vida sob uma nuvem escura de frustração, doença e indignação.

[[v21-5-18]]

^<<v21-5-18,18>>^ Ainda assim, observei pelo menos uma coisa positiva: é bom que as pessoas comam, bebam e desfrutem os resultados de seu trabalho debaixo do sol durante a vida curta que Deus lhes dá e aceitem a parte que lhes cabe.

[[v21-5-19]]

^<<v21-5-19,19>>^ Também é bom receber de Deus riqueza e boa saúde para aproveitá-la. Alegrar-se com seu trabalho e aceitar a parte que lhe cabe na vida são, sem dúvida, presentes de Deus.

[[v21-5-20]]

^<<v21-5-20,20>>^ Deus mantém as pessoas tão ocupadas com as alegrias da vida que não lhes sobra tempo para refletir sobre o passado.

'''

xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[&#60; Capítulo Anterior] | <<v21-5-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[Próximo Capítulo &#62;]