include::./index.adoc[]

[[v21-1-0]]
=== Eclesiastes, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v21-1-1]]

^<<v21-1-1,1>>^ Estas são as palavras do Mestre, filho de Davi, que reinou em Jerusalém.

[[v21-1-2]]

^<<v21-1-2,2>>^ "Nada faz sentido", diz o Mestre. "Nada faz o menor sentido."

[[v21-1-3]]

^<<v21-1-3,3>>^ O que as pessoas ganham com todo o seu árduo trabalho debaixo do sol?

[[v21-1-4]]

^<<v21-1-4,4>>^ Gerações vêm e gerações vão, mas a terra permanece a mesma.

[[v21-1-5]]

^<<v21-1-5,5>>^ O sol nasce, o sol se põe e, logo, retorna a seu lugar para nascer outra vez.

[[v21-1-6]]

^<<v21-1-6,6>>^ O vento sopra para o sul, depois para o norte; dá voltas e mais voltas, soprando em círculos.

[[v21-1-7]]

^<<v21-1-7,7>>^ Os rios correm para o mar, mas ele nunca se enche; a água retorna aos rios e corre novamente para o mar.

[[v21-1-8]]

^<<v21-1-8,8>>^ Tudo é tão cansativo que não há como descrever. Não importa quanto vemos, nunca ficamos satisfeitos; não importa quanto ouvimos, nunca nos contentamos.

[[v21-1-9]]

^<<v21-1-9,9>>^ A história simplesmente se repete. O que foi feito antes será feito outra vez. Nada debaixo do sol é realmente novo.

[[v21-1-10]]

^<<v21-1-10,10>>^ De vez em quando, alguém diz: "Isto é novidade!". O fato, porém, é que nada é realmente novo.

[[v21-1-11]]

^<<v21-1-11,11>>^ Não nos lembramos do que aconteceu no passado, e as gerações futuras tampouco se lembrarão do que fazemos hoje.

[[v21-1-12]]

^<<v21-1-12,12>>^ Eu, o Mestre, fui rei de Israel e vivi em Jerusalém.

[[v21-1-13]]

^<<v21-1-13,13>>^ Dediquei-me a buscar o entendimento e a usar a sabedoria para examinar tudo que se faz debaixo do céu. Descobri que Deus deu uma existência trágica à humanidade.

[[v21-1-14]]

^<<v21-1-14,14>>^ Observei tudo que acontece debaixo do sol e, de fato, nada faz sentido; é como correr atrás do vento.

[[v21-1-15]]

^<<v21-1-15,15>>^ O que está errado não pode ser corrigido; o que ainda falta não pode ser recuperado.

[[v21-1-16]]

^<<v21-1-16,16>>^ Disse a mim mesmo: "Sou mais sábio que todos os reis que governaram em Jerusalém antes de mim. Tenho mais sabedoria e conhecimento que eles".

[[v21-1-17]]

^<<v21-1-17,17>>^ Então me dediquei a aprender de tudo: desde a sabedoria até a loucura e a insensatez. Descobri, por experiência, que procurar essas coisas também é como correr atrás do vento.

[[v21-1-18]]

^<<v21-1-18,18>>^ Quanto maior a sabedoria, maior a aflição; quanto maior o conhecimento, maior a tristeza.

'''

xref:020-proverbios/020-proverbios-031.adoc#v20-31-0[&#60; Capítulo Anterior] | <<v21-1-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[Próximo Capítulo &#62;]