include::./index.adoc[]

[[v21-2-0]]
=== Eclesiastes, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v21-2-1]]

^<<v21-2-1,1>>^ Disse a mim mesmo: "Venha, vamos experimentar o prazer; vamos procurar as coisas boas da vida!". Descobri, porém, que isso também não fazia sentido.

[[v21-2-2]]

^<<v21-2-2,2>>^ Portanto, disse: "O riso é tolice. De que adianta buscar o prazer?".

[[v21-2-3]]

^<<v21-2-3,3>>^ Depois de pensar muito, resolvi me animar com vinho. E, enquanto ainda buscava a sabedoria, apeguei-me à insensatez. Assim, procurei experimentar o que haveria de melhor para as pessoas em sua curta vida debaixo do sol.

[[v21-2-4]]

^<<v21-2-4,4>>^ Dediquei-me a projetos grandiosos, construindo casas enormes e plantando belos vinhedos.

[[v21-2-5]]

^<<v21-2-5,5>>^ Fiz jardins e parques e os enchi de árvores frutíferas de toda espécie.

[[v21-2-6]]

^<<v21-2-6,6>>^ Construí açudes para juntar água e regar meus pomares verdejantes.

[[v21-2-7]]

^<<v21-2-7,7>>^ Comprei escravos e escravas, e outros nasceram em minha casa. Tive muito gado e rebanhos, mais que todos os que viveram em Jerusalém antes de mim.

[[v21-2-8]]

^<<v21-2-8,8>>^ Juntei grande quantidade de prata e ouro, tesouros de muitos reis e províncias. Contratei cantores e cantoras e tive muitas concubinas. Tive tudo que um homem pode desejar!

[[v21-2-9]]

^<<v21-2-9,9>>^ Tornei-me mais importante que todos os que viveram em Jerusalém antes de mim, e nunca me faltou sabedoria.

[[v21-2-10]]

^<<v21-2-10,10>>^ Tudo que desejei, busquei e consegui. Não me neguei prazer algum. No trabalho árduo, encontrei grande prazer, a recompensa por meus esforços.

[[v21-2-11]]

^<<v21-2-11,11>>^ Mas, ao olhar para tudo que havia me esforçado tanto para realizar, vi que nada fazia sentido; era como correr atrás do vento. Não havia nada que valesse a pena debaixo do sol.

[[v21-2-12]]

^<<v21-2-12,12>>^ Então resolvi comparar a sabedoria com a loucura e a insensatez (pois quem pode fazê-lo melhor que eu, o rei?).

[[v21-2-13]]

^<<v21-2-13,13>>^ Pensei: "A sabedoria é melhor que a insensatez, assim como a luz é melhor que as trevas.

[[v21-2-14]]

^<<v21-2-14,14>>^ O sábio vê para onde está indo, mas o tolo anda na escuridão". Apesar disso, vi que o sábio e o tolo têm o mesmo destino.

[[v21-2-15]]

^<<v21-2-15,15>>^ Disse a mim mesmo: "Uma vez que terei o mesmo fim do tolo, de que vale toda a minha sabedoria? Nada disso faz sentido!".

[[v21-2-16]]

^<<v21-2-16,16>>^ Pois nem o sábio nem o tolo serão lembrados por muito tempo; ambos morrerão, e logo serão esquecidos.

[[v21-2-17]]

^<<v21-2-17,17>>^ Por isso, passei a odiar minha vida, pois tudo que é feito debaixo do sol é frustrante. Nada faz sentido; é como correr atrás do vento.

[[v21-2-18]]

^<<v21-2-18,18>>^ Passei a odiar todo o meu árduo trabalho debaixo do sol, pois deixarei para meus sucessores tudo que me esforcei para obter.

[[v21-2-19]]

^<<v21-2-19,19>>^ E quem pode dizer se eles serão sábios ou tolos? No entanto, terão controle sobre tudo que consegui debaixo do sol, com minha habilidade e meu esforço. Isso não faz o menor sentido!

[[v21-2-20]]

^<<v21-2-20,20>>^ Assim, cheguei a me desesperar e questionei o valor de todo o meu árduo trabalho debaixo do sol.

[[v21-2-21]]

^<<v21-2-21,21>>^ Algumas pessoas trabalham com sabedoria, conhecimento e habilidade, mas terão de deixar o resultado de seu trabalho para alguém que não se esforçou. Isso também não faz sentido; é uma grande tragédia.

[[v21-2-22]]

^<<v21-2-22,22>>^ O que as pessoas ganham com tanto esforço e ansiedade debaixo do sol?

[[v21-2-23]]

^<<v21-2-23,23>>^ Seus dias de trabalho são cheios de dor e tristeza, e nem mesmo à noite sua mente descansa. Nada faz sentido.

[[v21-2-24]]

^<<v21-2-24,24>>^ Por isso, concluí que a melhor coisa a fazer é desfrutar a comida e a bebida e encontrar satisfação no trabalho. Percebi, então, que esses prazeres vêm da mão de Deus.

[[v21-2-25]]

^<<v21-2-25,25>>^ Pois quem pode comer ou desfrutar algo sem ele?

[[v21-2-26]]

^<<v21-2-26,26>>^ Deus concede sabedoria, conhecimento e alegria àqueles que lhe agradam. Se, porém, um pecador enriquece, Deus lhe toma a riqueza e a entrega àqueles que lhe agradam. Isso também não faz sentido; é como correr atrás do vento.

'''

xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[&#60; Capítulo Anterior] | <<v21-2-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[Próximo Capítulo &#62;]