include::./index.adoc[]

[[v21-8-0]]
=== Eclesiastes, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v21-8-1]]

^<<v21-8-1,1>>^ Como é maravilhoso ser sábio, analisar e interpretar as coisas! A sabedoria ilumina o rosto e abranda a dureza das feições.

[[v21-8-2]]

^<<v21-8-2,2>>^ Obedeça ao rei, como jurou a Deus que faria.

[[v21-8-3]]

^<<v21-8-3,3>>^ Não procure evitar seu dever, nem se junte aos que tramam o mal, pois o rei faz o que bem entende.

[[v21-8-4]]

^<<v21-8-4,4>>^ Suas ordens têm respaldo em seu grande poder. Ninguém pode resistir a elas nem as questionar.

[[v21-8-5]]

^<<v21-8-5,5>>^ Quem obedece às suas ordens não será castigado. Quem é sábio encontrará o tempo e o modo apropriado de fazer o que é certo,

[[v21-8-6]]

^<<v21-8-6,6>>^ pois há um tempo e um modo para tudo, mesmo em meio às dificuldades.

[[v21-8-7]]

^<<v21-8-7,7>>^ Aliás, como é possível evitar o que não se sabe que acontecerá?

[[v21-8-8]]

^<<v21-8-8,8>>^ Ninguém pode impedir o próprio espírito de partir. Ninguém é capaz de evitar o dia de sua morte; não há como fugir dessa batalha. E, diante da morte, a maldade certamente não livrará o perverso.

[[v21-8-9]]

^<<v21-8-9,9>>^ Pensei muito sobre tudo que acontece debaixo do sol, onde as pessoas têm poder para prejudicar umas às outras.

[[v21-8-10]]

^<<v21-8-10,10>>^ Vi perversos serem sepultados com honra; frequentavam o templo e hoje são elogiados na mesma cidade em que cometeram seus crimes. Isso também não faz sentido.

[[v21-8-11]]

^<<v21-8-11,11>>^ Quando um crime não é castigado de imediato, as pessoas se veem incentivadas a fazer o mal.

[[v21-8-12]]

^<<v21-8-12,12>>^ Mas, ainda que alguém peque cem vezes e continue a viver por muito tempo, sei que aqueles que temem a Deus terminarão em situação melhor.

[[v21-8-13]]

^<<v21-8-13,13>>^ Os perversos não prosperarão, pois não temem a Deus. Seus dias, como as sombras do anoitecer, não se prolongarão.

[[v21-8-14]]

^<<v21-8-14,14>>^ Há mais uma coisa que não faz sentido em nosso mundo. Nesta vida, justos muitas vezes são tratados como se fossem perversos, e perversos, como se fossem justos. Isso não faz sentido algum!

[[v21-8-15]]

^<<v21-8-15,15>>^ Recomendo, portanto, que as pessoas aproveitem a vida, pois a melhor coisa a fazer neste mundo é comer, beber e alegrar-se. Assim, terão algo que os acompanhe em todo o árduo trabalho que Deus lhes dá debaixo do sol.

[[v21-8-16]]

^<<v21-8-16,16>>^ Enquanto procurava sabedoria e observava os fardos pesados que as pessoas carregam aqui na terra, vi que, dia e noite, sua atividade não cessa.

[[v21-8-17]]

^<<v21-8-17,17>>^ Percebi que ninguém é capaz de descobrir tudo que Deus faz debaixo do sol. Nem mesmo os mais sábios conseguem compreender tudo, embora afirmem o contrário.

'''

xref:021-eclesiastes/021-eclesiastes-007.adoc#v21-7-0[&#60; Capítulo Anterior] | <<v21-8-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[Próximo Capítulo &#62;]