include::./index.adoc[]

[[v6-5-0]]
=== Josué, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v6-5-1]]

^<<v6-5-1,1>>^ Quando todos os reis amorreus a oeste do Jordão e todos os reis cananeus que viviam junto ao mar souberam como o SENHOR havia secado o Jordão para que os israelitas atravessassem, perderam o ânimo e se encheram de medo por causa deles.

[[v6-5-2]]

^<<v6-5-2,2>>^ Naquela ocasião, o SENHOR disse a Josué: "Prepare facas de pedra e circuncide esta segunda geração de israelitas".

[[v6-5-3]]

^<<v6-5-3,3>>^ Então Josué preparou facas de pedra e circuncidou toda a população masculina de Israel em Gibeate-Aralote.

[[v6-5-4]]

^<<v6-5-4,4>>^ Josué teve de circuncidá-los porque todos os homens com idade suficiente para ir à guerra quando saíram do Egito haviam morrido no deserto.

[[v6-5-5]]

^<<v6-5-5,5>>^ Todos os que saíram haviam sido circuncidados, mas isso não aconteceu com os homens que nasceram depois da saída do Egito, durante o tempo no deserto.

[[v6-5-6]]

^<<v6-5-6,6>>^ Os israelitas andaram quarenta anos pelo deserto, até que tivessem morrido todos os homens com idade suficiente para ir à guerra quando saíram do Egito. O povo havia desobedecido ao SENHOR, e o SENHOR jurou que não os deixaria entrar na terra que ele tinha prometido solenemente nos dar, uma terra que produz leite e mel com fartura.

[[v6-5-7]]

^<<v6-5-7,7>>^ Assim, Josué circuncidou os filhos dos israelitas que haviam crescido e tomado o lugar de seus pais, pois não tinham sido circuncidados no caminho.

[[v6-5-8]]

^<<v6-5-8,8>>^ Depois que toda a população masculina foi circuncidada, o povo permaneceu no acampamento até os homens se recuperarem.

[[v6-5-9]]

^<<v6-5-9,9>>^ Então o SENHOR disse a Josué: "Hoje lancei fora a vergonha de sua escravidão no Egito". Por isso, até hoje aquele lugar se chama Gilgal.

[[v6-5-10]]

^<<v6-5-10,10>>^ Enquanto estavam acampados em Gilgal, na planície de Jericó, os israelitas celebraram a Páscoa ao entardecer do décimo quarto dia do primeiro mês.

[[v6-5-11]]

^<<v6-5-11,11>>^ No dia seguinte, começaram a comer pão sem fermento e grãos tostados produzidos na terra.

[[v6-5-12]]

^<<v6-5-12,12>>^ No dia em que começaram a comer das colheitas da terra, o maná deixou de cair e nunca mais apareceu. Daquele momento em diante, os israelitas passaram a se alimentar do que a terra de Canaã produzia.

[[v6-5-13]]

^<<v6-5-13,13>>^ Quando Josué estava perto da cidade de Jericó, olhou para cima e viu um homem em pé diante dele, com uma espada na mão. Josué se aproximou e lhe perguntou: "Você é amigo ou inimigo?".

[[v6-5-14]]

^<<v6-5-14,14>>^ O homem respondeu: "Na verdade, cheguei agora e sou comandante do exército do SENHOR". Então Josué se prostrou com o rosto no chão em sinal de reverência e disse: "Que ordens meu senhor tem para mim?".

[[v6-5-15]]

^<<v6-5-15,15>>^ O comandante do exército do SENHOR respondeu: "Tire as sandálias, pois o lugar em que você está é santo". E Josué obedeceu.

'''

xref:006-josue/006-josue-004.adoc#v6-4-0[&#60; Capítulo Anterior] | <<v6-5-0,Topo>> | xref:006-josue/006-josue-006.adoc#v6-6-0[Próximo Capítulo &#62;]