include::./index.adoc[]

[[v6-23-0]]
=== Josué, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v6-23-1]]

^<<v6-23-1,1>>^ Muito tempo se passou depois de o SENHOR ter concedido a Israel descanso de todos os seus inimigos. Josué, agora bastante idoso,

[[v6-23-2]]

^<<v6-23-2,2>>^ convocou todo o Israel, com seus líderes, chefes, juízes e oficiais, e disse: "Já estou bem idoso.

[[v6-23-3]]

^<<v6-23-3,3>>^ Vocês viram tudo que o SENHOR, seu Deus, fez por vocês. O SENHOR, seu Deus, lutou em seu favor contra seus inimigos.

[[v6-23-4]]

^<<v6-23-4,4>>^ Eu reparti entre vocês como herança toda a terra das nações que ainda não foram conquistadas, bem como a terra das nações que já derrotamos desde o rio Jordão até o mar Mediterrâneo, a oeste.

[[v6-23-5]]

^<<v6-23-5,5>>^ Essa terra será de vocês, pois o SENHOR, seu Deus, expulsará de diante de vocês os povos que habitam ali. Vocês tomarão posse da terra deles, conforme o SENHOR, seu Deus, lhes prometeu.

[[v6-23-6]]

^<<v6-23-6,6>>^ "Por isso, esforcem-se ao máximo para cumprir cuidadosamente tudo que Moisés escreveu no Livro da Lei. Não se desviem dele, nem para um lado nem para o outro.

[[v6-23-7]]

^<<v6-23-7,7>>^ Não se misturem com os povos que ainda restam na terra. Nem sequer mencionem o nome dos deuses deles e muito menos jurem por eles. Não sirvam nem adorem esses deuses,

[[v6-23-8]]

^<<v6-23-8,8>>^ mas apeguem-se firmemente ao SENHOR, seu Deus, como fizeram até hoje.

[[v6-23-9]]

^<<v6-23-9,9>>^ "Pois o SENHOR expulsou de diante de vocês grandes e poderosas nações e, até hoje, ninguém conseguiu lhes resistir.

[[v6-23-10]]

^<<v6-23-10,10>>^ Cada um de vocês fará fugir mil homens do inimigo, porque o SENHOR, seu Deus, luta por vocês, conforme prometeu.

[[v6-23-11]]

^<<v6-23-11,11>>^ Portanto, dediquem-se com empenho a amar o SENHOR, seu Deus.

[[v6-23-12]]

^<<v6-23-12,12>>^ "Mas, se vocês se desviarem dele e se apegarem aos costumes dos sobreviventes das nações que ainda restam no meio de vocês, e se casarem com eles, e eles com vocês,

[[v6-23-13]]

^<<v6-23-13,13>>^ saibam, com certeza, que o SENHOR, seu Deus, não expulsará essas nações de diante de vocês. Ao contrário, elas serão isca e armadilha para vocês, chicote em suas costas e espinhos em seus olhos. E vocês desaparecerão para sempre desta boa terra que o SENHOR, seu Deus, lhes deu.

[[v6-23-14]]

^<<v6-23-14,14>>^ "Em breve morrerei e irei pelo caminho de toda a terra. Vocês sabem, de todo o coração, que todas as boas promessas do SENHOR, seu Deus, se cumpriram. Nenhuma delas falhou!

[[v6-23-15]]

^<<v6-23-15,15>>^ Mas, assim como o SENHOR, seu Deus, lhes deu as coisas boas que ele prometeu, também fará vir calamidades sobre vocês se lhe desobedecerem. O SENHOR, seu Deus, os eliminará completamente desta boa terra que lhes deu.

[[v6-23-16]]

^<<v6-23-16,16>>^ Se vocês quebrarem a aliança do SENHOR, seu Deus, servindo ou adorando outros deuses, a ira do SENHOR arderá contra vocês, e desaparecerão rapidamente da boa terra que ele lhes deu".

'''

xref:006-josue/006-josue-022.adoc#v6-22-0[&#60; Capítulo Anterior] | <<v6-23-0,Topo>> | xref:006-josue/006-josue-024.adoc#v6-24-0[Próximo Capítulo &#62;]