include::./index.adoc[]

[[v6-19-0]]
=== Josué, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v6-19-1]]

^<<v6-19-1,1>>^ A segunda porção de terra foi entregue por sorteio aos clãs da tribo de Simeão. Sua herança ficava dentro do território de Judá:

[[v6-19-2]]

^<<v6-19-2,2>>^ A herança de Simeão incluía: Berseba, Seba, Moladá,

[[v6-19-3]]

^<<v6-19-3,3>>^ Hazar-Sual, Balá, Azém,

[[v6-19-4]]

^<<v6-19-4,4>>^ Eltolade, Betul, Hormá,

[[v6-19-5]]

^<<v6-19-5,5>>^ Ziclague, Bete-Marcabote, Hazar-Susa,

[[v6-19-6]]

^<<v6-19-6,6>>^ Bete-Lebaote e Saruém; treze cidades com os povoados ao redor.

[[v6-19-7]]

^<<v6-19-7,7>>^ Também incluía: Aim, Rimom, Eter e Asã; quatro cidades com os povoados ao redor,

[[v6-19-8]]

^<<v6-19-8,8>>^ e também os povoados vizinhos até Baalate-Beer (também conhecida como Ramá do Neguebe). Essa foi a herança designada aos clãs da tribo de Simeão.

[[v6-19-9]]

^<<v6-19-9,9>>^ Sua porção de terra foi tirada de uma parte da herança de Judá, pois o território de Judá era grande demais para eles. Assim, a tribo de Simeão recebeu sua herança dentro do território de Judá.

[[v6-19-10]]

^<<v6-19-10,10>>^ A terceira porção de terra foi entregue por sorteio aos clãs da tribo de Zebulom: A divisa da herança de Zebulom chegava até Saride.

[[v6-19-11]]

^<<v6-19-11,11>>^ Dali prosseguia para o oeste, passando por Maralá, chegando até Dabesete e seguindo para o ribeiro junto a Jocneão.

[[v6-19-12]]

^<<v6-19-12,12>>^ Na direção oposta, a divisa se estendia para o leste desde Saride até o limite de Quislote-Tabor e, dali, para Daberate, subindo até Jafia.

[[v6-19-13]]

^<<v6-19-13,13>>^ Depois continuava para o leste, até Gate-Héfer, Ete-Cazim e Rimom, e fazia uma curva na direção de Neá.

[[v6-19-14]]

^<<v6-19-14,14>>^ A divisa norte de Zebulom passava por Hanatom e terminava no vale de Iftá-El.

[[v6-19-15]]

^<<v6-19-15,15>>^ Além das cidades mencionadas, ali estavam: Catate, Naalal, Sinrom, Idala e Belém; doze cidades com os povoados ao redor.

[[v6-19-16]]

^<<v6-19-16,16>>^ A herança designada aos clãs da tribo de Zebulom incluía essas cidades com os povoados ao redor.

[[v6-19-17]]

^<<v6-19-17,17>>^ A quarta porção de terra foi entregue por sorteio aos clãs da tribo de Issacar:

[[v6-19-18]]

^<<v6-19-18,18>>^ Seu território abrangia as seguintes cidades: Jezreel, Quesulote, Suném,

[[v6-19-19]]

^<<v6-19-19,19>>^ Hafaraim, Siom, Anaarate,

[[v6-19-20]]

^<<v6-19-20,20>>^ Rabite, Quisiom, Ebes,

[[v6-19-21]]

^<<v6-19-21,21>>^ Remete, En-Ganim, En-Hadá e Bete-Pazes.

[[v6-19-22]]

^<<v6-19-22,22>>^ A divisa também chegava a Tabor, Saazima e Bete-Semes, e terminava no Jordão; dezesseis cidades com os povoados ao redor.

[[v6-19-23]]

^<<v6-19-23,23>>^ A herança designada aos clãs de Issacar incluía essas cidades com os povoados ao redor.

[[v6-19-24]]

^<<v6-19-24,24>>^ A quinta porção de terra foi entregue por sorteio aos clãs da tribo de Aser:

[[v6-19-25]]

^<<v6-19-25,25>>^ Seu território abrangia as seguintes cidades: Helcate, Hali, Béten, Acsafe,

[[v6-19-26]]

^<<v6-19-26,26>>^ Alameleque, Amade e Misal. A divisa a oeste chegava até o Carmelo e Sior-Libnate,

[[v6-19-27]]

^<<v6-19-27,27>>^ depois fazia uma curva para o leste, em direção a Bete-Dagom, se estendia até Zebulom, no vale de Iftá-El, ia para o norte, até Bete-Emeque e Neiel. Dali prosseguia para Cabul, ao norte,

[[v6-19-28]]

^<<v6-19-28,28>>^ Abdom, Reobe, Hamom e Caná, até a grande Sidom.

[[v6-19-29]]

^<<v6-19-29,29>>^ Depois a divisa fazia uma curva em direção a Ramá e à cidade fortificada de Tiro, de onde virava em direção a Hosa e terminava no mar Mediterrâneo. O território também incluía Meebel, Aczibe,

[[v6-19-30]]

^<<v6-19-30,30>>^ Umá, Afeque e Reobe; 22 cidades com os povoados ao redor.

[[v6-19-31]]

^<<v6-19-31,31>>^ A herança designada aos clãs da tribo de Aser incluía essas cidades com os povoados ao redor.

[[v6-19-32]]

^<<v6-19-32,32>>^ A sexta porção de terra foi entregue por sorteio aos clãs da tribo de Naftali:

[[v6-19-33]]

^<<v6-19-33,33>>^ Sua divisa começava em Helefe, no carvalho de Zaanim, passava por Adami-Neguebe e Jabneel, até Lacum, e terminava no rio Jordão.

[[v6-19-34]]

^<<v6-19-34,34>>^ A divisa oeste passava por Aznote-Tabor e ia para Hucoque. Chegava à divisa de Zebulom, ao sul, à divisa de Aser, a oeste, e ao rio Jordão, a leste.

[[v6-19-35]]

^<<v6-19-35,35>>^ Suas cidades fortificadas eram: Zidim, Zer, Hamate, Racate, Quinerete,

[[v6-19-36]]

^<<v6-19-36,36>>^ Adamá, Ramá, Hazor,

[[v6-19-37]]

^<<v6-19-37,37>>^ Quedes, Edrei, En-Hazor,

[[v6-19-38]]

^<<v6-19-38,38>>^ Irom, Migdal-El, Horém, Bete-Anate e Bete-Semes; dezenove cidades com os povoados ao redor.

[[v6-19-39]]

^<<v6-19-39,39>>^ A herança designada aos clãs da tribo de Naftali incluía essas cidades com os povoados ao redor.

[[v6-19-40]]

^<<v6-19-40,40>>^ A sétima porção de terra foi entregue por sorteio aos clãs da tribo de Dã:

[[v6-19-41]]

^<<v6-19-41,41>>^ O território designado como sua herança abrangia estas cidades: Zorá, Estaol, Ir-Semes,

[[v6-19-42]]

^<<v6-19-42,42>>^ Saalabim, Aijalom, Itla,

[[v6-19-43]]

^<<v6-19-43,43>>^ Elom, Timna, Ecrom,

[[v6-19-44]]

^<<v6-19-44,44>>^ Elteque, Gibetom, Baalate,

[[v6-19-45]]

^<<v6-19-45,45>>^ Jeúde, Bene-Beraque, Gate-Rimom,

[[v6-19-46]]

^<<v6-19-46,46>>^ Me-Jarcom e Racom, e o território em frente de Jope.

[[v6-19-47]]

^<<v6-19-47,47>>^ Os membros da tribo de Dã tiveram dificuldade em tomar posse de sua terra, por isso atacaram a cidade de Lesém. Eles a tomaram, massacraram seu povo e se estabeleceram nela. Mudaram o nome da cidade para Dã, em homenagem a seu antepassado.

[[v6-19-48]]

^<<v6-19-48,48>>^ A herança designada aos clãs da tribo de Dã incluía essas cidades com os povoados ao redor.

[[v6-19-49]]

^<<v6-19-49,49>>^ Depois que todo o território havia sido repartido entre as tribos, os israelitas deram a Josué uma porção de terra como herança no meio deles,

[[v6-19-50]]

^<<v6-19-50,50>>^ pois o SENHOR tinha dito que ele poderia receber qualquer cidade que quisesse. Ele escolheu Timnate-Sera, na região montanhosa de Efraim. Ali reconstruiu a cidade e habitou nela.

[[v6-19-51]]

^<<v6-19-51,51>>^ Foram esses os territórios que o sacerdote Eleazar, Josué, filho de Num, e os chefes das tribos designaram como herança para as tribos de Israel, por sorteio na presença do SENHOR, à entrada da tenda do encontro em Siló. Assim, concluíram a distribuição da terra.

'''

xref:006-josue/006-josue-018.adoc#v6-18-0[&#60; Capítulo Anterior] | <<v6-19-0,Topo>> | xref:006-josue/006-josue-020.adoc#v6-20-0[Próximo Capítulo &#62;]