include::./index.adoc[]

[[v6-1-0]]
=== Josué, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v6-1-1]]

^<<v6-1-1,1>>^ Depois que Moisés, servo do SENHOR, morreu, o SENHOR disse a Josué, filho de Num, auxiliar de Moisés:

[[v6-1-2]]

^<<v6-1-2,2>>^ "Meu servo Moisés está morto; chegou a hora de você conduzir todo este povo, os israelitas, para atravessar o rio Jordão e entrar na terra que eu lhes dou.

[[v6-1-3]]

^<<v6-1-3,3>>^ Eu darei a vocês todo o lugar em que pisarem, conforme prometi a Moisés,

[[v6-1-4]]

^<<v6-1-4,4>>^ desde o deserto do Neguebe, ao sul, até os montes do Líbano, ao norte; desde o rio Eufrates, a leste, até o mar Mediterrâneo, a oeste, incluindo toda a terra dos hititas.

[[v6-1-5]]

^<<v6-1-5,5>>^ Enquanto você viver, ninguém será capaz de lhe resistir, pois eu estarei com você, assim como estive com Moisés. Não o deixarei nem o abandonarei.

[[v6-1-6]]

^<<v6-1-6,6>>^ "Seja forte e corajoso, pois você conduzirá este povo para tomar posse da terra que jurei dar a seus antepassados.

[[v6-1-7]]

^<<v6-1-7,7>>^ Seja somente forte e muito corajoso. Tenha o cuidado de cumprir toda a lei que meu servo Moisés lhe ordenou. Não se desvie dela nem para um lado nem para o outro. Assim você será bem-sucedido em tudo que fizer.

[[v6-1-8]]

^<<v6-1-8,8>>^ Relembre continuamente os termos deste Livro da Lei. Medite nele dia e noite, para ter certeza de cumprir tudo que nele está escrito. Então você prosperará e terá sucesso em tudo que fizer.

[[v6-1-9]]

^<<v6-1-9,9>>^ Esta é minha ordem: Seja forte e corajoso! Não tenha medo nem desanime, pois o SENHOR, seu Deus, estará com você por onde você andar".

[[v6-1-10]]

^<<v6-1-10,10>>^ Então Josué ordenou aos oficiais do povo:

[[v6-1-11]]

^<<v6-1-11,11>>^ "Percorram o acampamento e digam ao povo que prepare os suprimentos, pois daqui a três dias vocês atravessarão o rio Jordão e tomarão posse da terra que o SENHOR, seu Deus, lhes dá".

[[v6-1-12]]

^<<v6-1-12,12>>^ Em seguida, Josué convocou as tribos de Rúben e Gade e a meia tribo de Manassés e disse:

[[v6-1-13]]

^<<v6-1-13,13>>^ "Lembrem-se do que Moisés, servo do SENHOR, lhes ordenou: ‘O SENHOR, seu Deus, lhes concede um lugar de descanso e lhes dá esta terra’.

[[v6-1-14]]

^<<v6-1-14,14>>^ Suas esposas, seus filhos e seus animais ficarão na terra que Moisés designou para vocês a leste do Jordão. Mas seus guerreiros valentes, completamente armados, atravessarão o Jordão à frente das outras tribos e as ajudarão.

[[v6-1-15]]

^<<v6-1-15,15>>^ Permaneçam com seus irmãos até que o SENHOR conceda descanso a eles como concedeu a vocês, e até que eles também tomem posse da terra que o SENHOR, seu Deus, lhes dá. Só então vocês voltarão e se estabelecerão na terra a leste do Jordão, o lugar que Moisés, servo do SENHOR, designou para que vocês tomassem posse".

[[v6-1-16]]

^<<v6-1-16,16>>^ Eles responderam a Josué: "Faremos tudo que você ordenar e iremos aonde nos enviar.

[[v6-1-17]]

^<<v6-1-17,17>>^ Obedeceremos a você como obedecemos em tudo a Moisés. Que o SENHOR, seu Deus, esteja sempre com você, como esteve com Moisés.

[[v6-1-18]]

^<<v6-1-18,18>>^ Quem se rebelar contra as suas ordens e não obedecer às suas palavras será morto. Seja somente forte e corajoso!".

'''

xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[&#60; Capítulo Anterior] | <<v6-1-0,Topo>> | xref:006-josue/006-josue-002.adoc#v6-2-0[Próximo Capítulo &#62;]