include::./index.adoc[]

[[v6-13-0]]
=== Josué, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v6-13-1]]

^<<v6-13-1,1>>^ Josué já era idoso, e o SENHOR lhe disse: "Você está envelhecendo, e ainda há muita terra a ser conquistada.

[[v6-13-2]]

^<<v6-13-2,2>>^ Este é o território que resta: todas as regiões dos filisteus e dos gesuritas;

[[v6-13-3]]

^<<v6-13-3,3>>^ o território mais amplo dos cananeus, desde o ribeiro de Sior, na divisa com o Egito, até a divisa de Ecrom, ao norte. Abrange o território de cinco governantes filisteus: de Gaza, de Asdode, de Ascalom, de Gate e de Ecrom.

[[v6-13-4]]

^<<v6-13-4,4>>^ Também falta conquistar a terra dos aveus, ao sul. Ao norte, a seguinte região ainda não foi conquistada: toda a terra dos cananeus, incluindo Meara, pertencente aos sidônios, até Afeca, na divisa com os amorreus;

[[v6-13-5]]

^<<v6-13-5,5>>^ a terra dos gibleus e toda a região montanhosa do Líbano, a leste, desde Baal-Gade, ao pé do monte Hermom, até Lebo-Hamate;

[[v6-13-6]]

^<<v6-13-6,6>>^ e toda a região montanhosa, a oeste, desde o Líbano até Misrefote-Maim, incluindo toda a terra dos sidônios. "Eu mesmo expulsarei esses povos da terra de diante dos israelitas. Não deixem, portanto, de dar esta terra a Israel como herança, conforme eu lhes ordenei.

[[v6-13-7]]

^<<v6-13-7,7>>^ Dividam todo este território como herança entre as nove tribos e a meia tribo de Manassés".

[[v6-13-8]]

^<<v6-13-8,8>>^ A outra metade da tribo de Manassés e as tribos de Rúben e Gade já haviam recebido sua porção de terra como herança a leste do Jordão, designada para eles por Moisés, servo do SENHOR.

[[v6-13-9]]

^<<v6-13-9,9>>^ Seu território se estendia desde Aroer, na beira do vale do Arnom, incluindo a cidade no meio do vale, passando pelo planalto além de Medeba, até Dibom.

[[v6-13-10]]

^<<v6-13-10,10>>^ Também abrangia todas as cidades de Seom, rei dos amorreus, que havia reinado em Hesbom, e se estendia até a divisa de Amom.

[[v6-13-11]]

^<<v6-13-11,11>>^ Incluía Gileade, o território dos reinos de Gesur e Maaca, todo o monte Hermom e toda a região de Basã, até Salcá,

[[v6-13-12]]

^<<v6-13-12,12>>^ e também todo o reino de Ogue, rei de Basã, que havia reinado em Astarote e Edrei. O rei Ogue era o último dos refains, pois Moisés os havia atacado e expulsado.

[[v6-13-13]]

^<<v6-13-13,13>>^ Mas os israelitas não expulsaram os habitantes de Gesur e Maaca, de modo que vivem no meio de Israel até hoje.

[[v6-13-14]]

^<<v6-13-14,14>>^ Moisés não havia designado porção alguma de terra como herança para a tribo de Levi. Em vez disso, conforme o SENHOR lhes havia prometido, sua herança vinha das ofertas especiais para o SENHOR, o Deus de Israel.

[[v6-13-15]]

^<<v6-13-15,15>>^ Moisés havia designado a seguinte área aos clãs da tribo de Rúben:

[[v6-13-16]]

^<<v6-13-16,16>>^ Seu território se estendia desde Aroer, na beira do vale do Arnom, incluindo a cidade no meio do vale, até o planalto além de Medeba.

[[v6-13-17]]

^<<v6-13-17,17>>^ Abrangia Hesbom e as outras cidades do planalto: Dibom, Bamote-Baal, Bete-Baal-Meom,

[[v6-13-18]]

^<<v6-13-18,18>>^ Jaza, Quedemote, Mefaate,

[[v6-13-19]]

^<<v6-13-19,19>>^ Quiriataim, Sibma, Zerete-Saar, na colina acima do vale,

[[v6-13-20]]

^<<v6-13-20,20>>^ Bete-Peor, as encostas do Pisga e Bete-Jesimote.

[[v6-13-21]]

^<<v6-13-21,21>>^ O território de Rúben também incluía todas as cidades do planalto e todo o reino de Seom, o rei amorreu que havia reinado em Hesbom. Seom havia sido morto por Moisés junto com os líderes de Midiã: Evi, Requém, Zur, Hur e Reba, príncipes que habitavam naquela região e eram aliados de Seom.

[[v6-13-22]]

^<<v6-13-22,22>>^ Os israelitas também mataram Balaão, filho de Beor, que usava mágica para prever o futuro.

[[v6-13-23]]

^<<v6-13-23,23>>^ O rio Jordão marcava a divisa oeste da tribo de Rúben. As cidades e seus povoados ao redor nessa região foram entregues aos clãs da tribo de Rúben como sua herança.

[[v6-13-24]]

^<<v6-13-24,24>>^ Moisés havia designado a seguinte área aos clãs da tribo de Gade:

[[v6-13-25]]

^<<v6-13-25,25>>^ Seu território abrangia Jazar, todas as cidades de Gileade e metade da terra de Amom, até a cidade de Aroer, logo a oeste de Rabá.

[[v6-13-26]]

^<<v6-13-26,26>>^ Estendia-se desde Hesbom até Ramate-Mispá e Betonim, e desde Maanaim até o território de Lo-Debar.

[[v6-13-27]]

^<<v6-13-27,27>>^ No vale, incluía Bete-Arã, Bete-Ninra, Sucote, Zafom, e o restante das terras de Seom, rei de Hesbom. A divisa ocidental acompanhava o rio Jordão e se estendia ao norte até a ponta do mar da Galileia, e depois fazia uma curva para o leste.

[[v6-13-28]]

^<<v6-13-28,28>>^ As cidades com os povoados ao redor foram entregues aos clãs da tribo de Gade como sua herança.

[[v6-13-29]]

^<<v6-13-29,29>>^ Moisés havia designado a seguinte área aos clãs da meia tribo de Manassés:

[[v6-13-30]]

^<<v6-13-30,30>>^ Seu território se estendia desde Maanaim e abrangia toda a região de Basã, todo o antigo território do rei Ogue, e as sessenta cidades de Jair, em Basã.

[[v6-13-31]]

^<<v6-13-31,31>>^ Também incluía metade de Gileade, bem como Astarote e Edrei, cidades do reino de Ogue em Basã. Tudo isso foi entregue à metade dos descendentes de Maquir, filho de Manassés, segundo seus clãs.

[[v6-13-32]]

^<<v6-13-32,32>>^ Essa foi a divisão de terras como herança que Moisés designou enquanto estava nas campinas de Moabe, do outro lado do rio Jordão, a leste de Jericó.

[[v6-13-33]]

^<<v6-13-33,33>>^ À tribo de Levi, porém, Moisés não deu porção alguma de terra como herança, pois o SENHOR, o Deus de Israel, havia prometido que ele próprio seria sua herança.

'''

xref:006-josue/006-josue-012.adoc#v6-12-0[&#60; Capítulo Anterior] | <<v6-13-0,Topo>> | xref:006-josue/006-josue-014.adoc#v6-14-0[Próximo Capítulo &#62;]