include::./index.adoc[]

[[v6-6-0]]
=== Josué, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v6-6-1]]

^<<v6-6-1,1>>^ Os portões de Jericó estavam muito bem fechados, pois seus habitantes tinham medo dos israelitas. Ninguém podia sair nem entrar.

[[v6-6-2]]

^<<v6-6-2,2>>^ Mas o SENHOR disse a Josué: "Eu lhe entreguei Jericó, seu rei e todos os seus fortes guerreiros.

[[v6-6-3]]

^<<v6-6-3,3>>^ Você e seus homens de guerra marcharão ao redor da cidade uma vez por dia, durante seis dias.

[[v6-6-4]]

^<<v6-6-4,4>>^ Sete sacerdotes irão à frente da arca, e cada um levará uma trombeta de chifre de carneiro. No sétimo dia, marchem ao redor da cidade sete vezes, enquanto os sacerdotes tocam as trombetas.

[[v6-6-5]]

^<<v6-6-5,5>>^ Quando os sacerdotes fizerem soar um toque longo, todo o povo dará um forte grito de guerra. Então cairá o muro da cidade e o povo atacará, cada um do ponto onde estiver".

[[v6-6-6]]

^<<v6-6-6,6>>^ Josué, filho de Num, reuniu os sacerdotes e disse: "Levem a arca da aliança do SENHOR e escolham sete sacerdotes para irem à frente dela, cada sacerdote com uma trombeta de chifre de carneiro".

[[v6-6-7]]

^<<v6-6-7,7>>^ Em seguida, ordenou ao povo: "Marchem ao redor da cidade. Os homens armados irão à frente da arca do SENHOR".

[[v6-6-8]]

^<<v6-6-8,8>>^ Depois que Josué falou ao povo, os sete sacerdotes que levavam as trombetas diante do SENHOR começaram a marchar, avançando e tocando os instrumentos. A arca da aliança do SENHOR ia atrás deles.

[[v6-6-9]]

^<<v6-6-9,9>>^ Alguns dos homens armados iam à frente dos sacerdotes que tocavam as trombetas e outros iam atrás da arca, enquanto os sacerdotes tocavam sem parar.

[[v6-6-10]]

^<<v6-6-10,10>>^ Josué ordenou: "Não soltem o grito de guerra! Não digam palavra alguma até que eu lhes dê a ordem. Então, gritem!".

[[v6-6-11]]

^<<v6-6-11,11>>^ Assim, a arca do SENHOR foi levada ao redor da cidade apenas uma vez naquele dia; depois, voltaram ao acampamento e ali passaram a noite.

[[v6-6-12]]

^<<v6-6-12,12>>^ Na manhã seguinte, Josué se levantou cedo e, mais uma vez, os sacerdotes levaram a arca do SENHOR.

[[v6-6-13]]

^<<v6-6-13,13>>^ Os sete sacerdotes com as trombetas de chifre de carneiro marcharam à frente da arca do SENHOR, tocando seus instrumentos. Os homens armados marcharam à frente dos sacerdotes com as trombetas e atrás da arca do SENHOR, enquanto os sacerdotes tocavam sem parar.

[[v6-6-14]]

^<<v6-6-14,14>>^ No segundo dia, marcharam ao redor da cidade uma vez e depois voltaram ao acampamento. Fizeram o mesmo por seis dias.

[[v6-6-15]]

^<<v6-6-15,15>>^ No sétimo dia, os israelitas se levantaram ao amanhecer e marcharam ao redor da cidade, como haviam feito antes. Dessa vez, porém, rodearam a cidade sete vezes.

[[v6-6-16]]

^<<v6-6-16,16>>^ Na sétima vez, enquanto os sacerdotes faziam soar um toque longo das trombetas, Josué ordenou ao povo: "Gritem! O SENHOR lhes entregou a cidade!

[[v6-6-17]]

^<<v6-6-17,17>>^ Jericó e tudo que há dentro dela serão completamente destruídos como oferta ao SENHOR. Somente a prostituta Raabe e os outros que estiverem em sua casa serão poupados, pois ela protegeu nossos espiões.

[[v6-6-18]]

^<<v6-6-18,18>>^ "Não levem coisa alguma daquilo que foi separado para destruição, ou vocês mesmos serão completamente destruídos e trarão desgraça ao acampamento de Israel.

[[v6-6-19]]

^<<v6-6-19,19>>^ Toda a prata, todo o ouro e todos os objetos de bronze e de ferro serão separados para o SENHOR e deverão ser levados para o seu tesouro".

[[v6-6-20]]

^<<v6-6-20,20>>^ Quando o povo ouviu o som das trombetas, gritou com toda a força. De repente, o muro de Jericó veio abaixo. O povo atacou a cidade, cada um do ponto onde estava, e a tomou.

[[v6-6-21]]

^<<v6-6-21,21>>^ Com suas espadas, destruíram completamente tudo que havia dentro dela: homens e mulheres, jovens e velhos, bois, ovelhas e jumentos.

[[v6-6-22]]

^<<v6-6-22,22>>^ Josué disse aos dois espiões: "Cumpram sua promessa! Vão à casa da prostituta e tirem-na de lá com toda a sua família".

[[v6-6-23]]

^<<v6-6-23,23>>^ Então os homens que haviam espionado a terra entraram na cidade e tiraram de lá Raabe, seu pai, sua mãe, seus irmãos e todos os outros parentes que estavam com ela. Levaram a família toda para um lugar seguro fora do acampamento de Israel.

[[v6-6-24]]

^<<v6-6-24,24>>^ Os israelitas incendiaram a cidade e tudo que havia dentro dela. Guardaram somente a prata, o ouro e todos os objetos de bronze e de ferro para o tesouro da casa do SENHOR.

[[v6-6-25]]

^<<v6-6-25,25>>^ Josué, no entanto, poupou a vida da prostituta Raabe e dos parentes que estavam em sua casa, pois ela escondeu os espiões que Josué tinha enviado a Jericó. E até hoje ela vive no meio de Israel.

[[v6-6-26]]

^<<v6-6-26,26>>^ Naquela ocasião, Josué pronunciou esta maldição: "Que a maldição do SENHOR caia sobre qualquer um que tentar reconstruir a cidade de Jericó. À custa de seu filho mais velho, lançará o alicerce. À custa de seu filho mais novo, colocará seus portões".

[[v6-6-27]]

^<<v6-6-27,27>>^ Assim, o SENHOR estava com Josué, e sua fama se espalhou por toda a terra.

'''

xref:006-josue/006-josue-005.adoc#v6-5-0[&#60; Capítulo Anterior] | <<v6-6-0,Topo>> | xref:006-josue/006-josue-007.adoc#v6-7-0[Próximo Capítulo &#62;]