include::./index.adoc[]

[[v6-10-0]]
=== Josué, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v6-10-1]]

^<<v6-10-1,1>>^ Adoni-Zedeque, rei de Jerusalém, soube que Josué havia capturado e destruído completamente a cidade de Ai e matado seu rei, assim como tinha destruído a cidade de Jericó e matado seu rei. Também soube que os gibeonitas haviam feito um tratado de paz com Israel e agora viviam no meio deles.

[[v6-10-2]]

^<<v6-10-2,2>>^ Ele e seu povo tiveram muito medo, pois Gibeom era uma cidade grande como as cidades reais, ainda maior que a cidade de Ai, e os gibeonitas eram guerreiros valentes.

[[v6-10-3]]

^<<v6-10-3,3>>^ Por isso, Adoni-Zedeque, rei de Jerusalém, enviou mensageiros a vários outros reis: a Hoão, rei de Hebrom, a Piram, rei de Jarmute, a Jafia, rei de Laquis, e a Debir, rei de Eglom.

[[v6-10-4]]

^<<v6-10-4,4>>^ "Venham e ajudem-me a destruir Gibeom, pois seu povo fez um tratado de paz com Josué e os israelitas", pediu ele.

[[v6-10-5]]

^<<v6-10-5,5>>^ Então os cinco reis amorreus uniram seus exércitos para atacar juntos. Posicionaram suas tropas perto de Gibeom e avançaram contra ela.

[[v6-10-6]]

^<<v6-10-6,6>>^ Os homens de Gibeom enviaram mensageiros a Josué em seu acampamento em Gilgal. "Não abandone seus servos!", suplicaram. "Venha depressa e salve-nos! Ajude-nos, pois todos os reis amorreus que vivem na região montanhosa uniram forças para nos atacar!"

[[v6-10-7]]

^<<v6-10-7,7>>^ Josué e todo o seu exército, incluindo seus melhores guerreiros, partiram de Gilgal para Gibeom.

[[v6-10-8]]

^<<v6-10-8,8>>^ "Não tenha medo desses reis", disse o SENHOR a Josué. "Eu os entreguei em suas mãos. Nenhum deles será capaz de resistir a você."

[[v6-10-9]]

^<<v6-10-9,9>>^ Josué marchou a noite toda desde Gilgal e pegou os exércitos amorreus de surpresa.

[[v6-10-10]]

^<<v6-10-10,10>>^ O SENHOR trouxe pânico sobre os amorreus, e o exército de Israel massacrou muitos deles em Gibeom. Perseguiram o inimigo ao longo da subida para Bete-Horom, matando os amorreus até Azeca e Maquedá.

[[v6-10-11]]

^<<v6-10-11,11>>^ Enquanto os amorreus recuavam pelo caminho de Bete-Horom, o SENHOR os destruiu com uma terrível chuva de pedras de granizo que ele enviou do céu e que continuou até chegarem a Azeca. As pedras eliminaram mais inimigos do que os israelitas mataram à espada.

[[v6-10-12]]

^<<v6-10-12,12>>^ No dia em que o SENHOR deu aos israelitas vitória sobre os amorreus, Josué orou ao SENHOR diante do povo e disse: "Que o sol pare sobre Gibeom, e a lua, sobre o vale de Aijalom!".

[[v6-10-13]]

^<<v6-10-13,13>>^ O sol parou e a lua ficou onde estava, até que o povo tivesse derrotado seus inimigos. Acaso esse acontecimento não está registrado no Livro de Jasar ? O sol parou no meio do céu e não se pôs por cerca de um dia inteiro.

[[v6-10-14]]

^<<v6-10-14,14>>^ Nunca antes nem depois houve um dia semelhante, quando o SENHOR respondeu a uma oração como essa. Certamente o SENHOR lutou por Israel naquele dia!

[[v6-10-15]]

^<<v6-10-15,15>>^ Então Josué e todo o exército de Israel voltaram ao acampamento em Gilgal.

[[v6-10-16]]

^<<v6-10-16,16>>^ Durante a batalha, os cinco reis fugiram e se esconderam numa caverna em Maquedá.

[[v6-10-17]]

^<<v6-10-17,17>>^ Quando Josué soube que eles haviam sido encontrados,

[[v6-10-18]]

^<<v6-10-18,18>>^ deu a seguinte ordem: "Fechem a entrada da caverna com pedras grandes e ponham guardas ali, para que os reis não saiam.

[[v6-10-19]]

^<<v6-10-19,19>>^ Quanto aos demais soldados, continuem a perseguir os inimigos e matem os da retaguarda. Não deixem que voltem às suas cidades, pois o SENHOR, seu Deus, lhes deu vitória sobre eles".

[[v6-10-20]]

^<<v6-10-20,20>>^ Assim, Josué e o exército israelita continuaram a aniquilar o inimigo. Exterminaram os cinco exércitos, com exceção de uns poucos sobreviventes que conseguiram chegar às cidades fortificadas.

[[v6-10-21]]

^<<v6-10-21,21>>^ As tropas voltaram em segurança para Josué, no acampamento de Maquedá. Depois disso, ninguém se atreveu a dizer uma palavra contra o povo de Israel.

[[v6-10-22]]

^<<v6-10-22,22>>^ Então Josué ordenou: "Removam as pedras que estão na entrada da caverna e tragam os cinco reis para cá".

[[v6-10-23]]

^<<v6-10-23,23>>^ Eles tiraram da caverna os cinco reis das cidades de Jerusalém, Hebrom, Jarmute, Laquis e Eglom.

[[v6-10-24]]

^<<v6-10-24,24>>^ Os reis foram trazidos para fora, diante de Josué, e ele ordenou aos comandantes de seu exército: "Venham e coloquem o pé sobre o pescoço dos reis". E eles obedeceram.

[[v6-10-25]]

^<<v6-10-25,25>>^ "Não tenham medo nem desanimem", disse Josué. "Sejam fortes e corajosos, pois é isso que o SENHOR fará com todos os inimigos que vocês enfrentarem."

[[v6-10-26]]

^<<v6-10-26,26>>^ Então Josué matou os cinco reis e os pendurou em cinco árvores, onde ficaram até a tarde.

[[v6-10-27]]

^<<v6-10-27,27>>^ Ao entardecer, Josué ordenou que os corpos fossem tirados das árvores e lançados na caverna onde os reis haviam se escondido. A entrada da caverna foi fechada com pedras grandes, que estão lá até hoje.

[[v6-10-28]]

^<<v6-10-28,28>>^ Naquele mesmo dia, Josué tomou a cidade de Maquedá e a destruiu. Matou todos os seus habitantes, incluindo o rei, sem deixar sobreviventes. Destruiu todos eles e matou o rei de Maquedá, como havia feito com o rei de Jericó.

[[v6-10-29]]

^<<v6-10-29,29>>^ Então Josué e todo o exército de Israel avançaram para Libna e a atacaram.

[[v6-10-30]]

^<<v6-10-30,30>>^ O SENHOR entregou a cidade e seu rei nas mãos dos israelitas, que mataram todos os seus habitantes, sem deixar sobreviventes. Depois Josué matou o rei de Libna, como havia feito com o rei de Jericó.

[[v6-10-31]]

^<<v6-10-31,31>>^ De Libna, Josué e todo o exército israelita avançaram para Laquis e a atacaram.

[[v6-10-32]]

^<<v6-10-32,32>>^ O SENHOR também entregou Laquis nas mãos de Israel. Josué a tomou no segundo dia e matou todos os seus habitantes, como havia feito com Libna.

[[v6-10-33]]

^<<v6-10-33,33>>^ Durante o ataque a Laquis, Horão, rei de Gezer, chegou com seu exército para ajudar a defender a cidade, mas os homens de Josué mataram o rei e seu exército, sem deixar sobreviventes.

[[v6-10-34]]

^<<v6-10-34,34>>^ Em seguida, Josué e todo o exército israelita avançaram para Eglom e a atacaram.

[[v6-10-35]]

^<<v6-10-35,35>>^ Tomaram a cidade naquele dia e mataram todos os seus habitantes. Destruíram todos, como haviam feito com Laquis.

[[v6-10-36]]

^<<v6-10-36,36>>^ De Eglom, Josué e todo o exército de Israel subiram para Hebrom e a atacaram.

[[v6-10-37]]

^<<v6-10-37,37>>^ Tomaram a cidade e mataram todos os seus habitantes, incluindo o rei, sem deixar sobreviventes. Fizeram o mesmo com todos os povoados vizinhos. Destruíram toda a população, como haviam feito com Eglom.

[[v6-10-38]]

^<<v6-10-38,38>>^ Então Josué e todo o exército israelita voltaram e atacaram Debir.

[[v6-10-39]]

^<<v6-10-39,39>>^ Tomaram a cidade, o rei e todos os povoados vizinhos. Destruíram todos, sem deixar sobreviventes. Fizeram com Debir e seu rei o mesmo que haviam feito com Hebrom, Libna e seus reis.

[[v6-10-40]]

^<<v6-10-40,40>>^ Assim, Josué conquistou toda a região: a região montanhosa, o Neguebe, as colinas do oeste e as encostas dos montes, derrotando todos os seus reis. Destruiu todos na terra, sem deixar sobreviventes, conforme o SENHOR, o Deus de Israel, havia ordenado.

[[v6-10-41]]

^<<v6-10-41,41>>^ Josué os massacrou de Cades-Barneia a Gaza, e da região ao redor de Gósen até Gibeom.

[[v6-10-42]]

^<<v6-10-42,42>>^ Conquistou todos esses reis e suas terras numa só campanha, pois o SENHOR, o Deus de Israel, lutou por Israel.

[[v6-10-43]]

^<<v6-10-43,43>>^ Então Josué e todo o exército israelita voltaram ao acampamento em Gilgal.

'''

xref:006-josue/006-josue-009.adoc#v6-9-0[&#60; Capítulo Anterior] | <<v6-10-0,Topo>> | xref:006-josue/006-josue-011.adoc#v6-11-0[Próximo Capítulo &#62;]