include::./index.adoc[]

[[v6-9-0]]
=== Josué, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v6-9-1]]

^<<v6-9-1,1>>^ Todos os reis a oeste do rio Jordão souberam do que havia acontecido. Eram os reis dos hititas, dos amorreus, dos cananeus, dos ferezeus, dos heveus e dos jebuseus que viviam nas montanhas, nas colinas do oeste, ao longo do litoral do mar Mediterrâneo, até as montanhas do Líbano, ao norte.

[[v6-9-2]]

^<<v6-9-2,2>>^ Esses reis juntaram suas tropas para lutar como um só exército contra Josué e os israelitas.

[[v6-9-3]]

^<<v6-9-3,3>>^ Contudo, quando os habitantes de Gibeom souberam do que Josué tinha feito com Jericó e Ai,

[[v6-9-4]]

^<<v6-9-4,4>>^ usaram de astúcia para se salvar. Enviaram mensageiros a Josué e carregaram seus jumentos com sacos gastos e vasilhas de couro velhas e rachadas.

[[v6-9-5]]

^<<v6-9-5,5>>^ Os mensageiros calçavam sandálias gastas e remendadas e vestiam roupas esfarrapadas, e também levavam pães secos e esfarelados.

[[v6-9-6]]

^<<v6-9-6,6>>^ Quando chegaram ao acampamento em Gilgal, disseram a Josué e aos líderes de Israel: "Viemos de uma terra distante para pedir que vocês façam um tratado de paz conosco".

[[v6-9-7]]

^<<v6-9-7,7>>^ Os israelitas disseram a esses heveus: "Como podemos ter certeza de que não vivem aqui por perto? Pois, se for o caso, não podemos fazer tratado algum com vocês".

[[v6-9-8]]

^<<v6-9-8,8>>^ Eles responderam: "Somos seus servos". "Mas quem são vocês?", insistiu Josué. "De onde vieram?"

[[v6-9-9]]

^<<v6-9-9,9>>^ Eles disseram: "Seus servos vieram de uma terra muito distante. Ouvimos falar do poder do SENHOR, seu Deus, e de tudo que ele fez no Egito.

[[v6-9-10]]

^<<v6-9-10,10>>^ Também soubemos do que ele fez aos dois reis amorreus a leste do Jordão: Seom, rei de Hesbom, e Ogue, rei de Basã, que vivia em Astarote.

[[v6-9-11]]

^<<v6-9-11,11>>^ Por isso, nossos líderes e todo o nosso povo nos instruíram: ‘Levem provisões para uma viagem longa. Vão encontrar-se com os israelitas e digam-lhes: Somos seus servos; por favor, façam um tratado conosco’.

[[v6-9-12]]

^<<v6-9-12,12>>^ "Estes pães haviam acabado de sair do forno quando partimos. Agora, como podem ver, estão secos e esfarelados.

[[v6-9-13]]

^<<v6-9-13,13>>^ Estas vasilhas de couro estavam novas quando as enchemos, mas agora estão rachadas. E nossas roupas e sandálias estão gastas da viagem extremamente longa".

[[v6-9-14]]

^<<v6-9-14,14>>^ Os israelitas examinaram as provisões deles, mas não consultaram o SENHOR a respeito.

[[v6-9-15]]

^<<v6-9-15,15>>^ Josué fez um tratado de paz com aqueles homens e garantiu que pouparia a vida deles, e os líderes da comunidade confirmaram o acordo com um juramento.

[[v6-9-16]]

^<<v6-9-16,16>>^ Três dias depois de fazerem esse tratado, os israelitas descobriram que, na verdade, os gibeonitas viviam ali perto.

[[v6-9-17]]

^<<v6-9-17,17>>^ Partiram de imediato naquela direção e, em três dias, chegaram às cidades dos gibeonitas, chamadas Gibeom, Quefira, Beerote e Quiriate-Jearim.

[[v6-9-18]]

^<<v6-9-18,18>>^ Contudo, não atacaram as cidades, pois os líderes da comunidade haviam feito um juramento em nome do SENHOR, o Deus de Israel. Toda a comunidade se queixou contra seus líderes por causa do tratado,

[[v6-9-19]]

^<<v6-9-19,19>>^ mas eles responderam: "Uma vez que fizemos um juramento na presença do SENHOR, o Deus de Israel, não podemos tocar neles.

[[v6-9-20]]

^<<v6-9-20,20>>^ Temos de deixá-los viver, pois se quebrássemos o juramento a ira divina cairia sobre nós.

[[v6-9-21]]

^<<v6-9-21,21>>^ Que eles vivam!". Assim, os israelitas os colocaram para cortar lenha e carregar água para toda a comunidade, de acordo com a decisão dos líderes.

[[v6-9-22]]

^<<v6-9-22,22>>^ Josué reuniu os gibeonitas e lhes disse: "Por que vocês mentiram para nós? Por que disseram que viviam numa terra distante da nossa quando, na verdade, vivem aqui perto?

[[v6-9-23]]

^<<v6-9-23,23>>^ Sejam amaldiçoados! De agora em diante, vocês serão sempre servos, encarregados de cortar lenha e carregar água para a casa do meu Deus".

[[v6-9-24]]

^<<v6-9-24,24>>^ Eles responderam: "Agimos desse modo porque foi anunciado a nós, seus servos, que o SENHOR, seu Deus, havia ordenado a seu servo Moisés que desse a vocês toda esta terra e que destruísse todos os seus habitantes. Tememos muito por nossa vida por causa de vocês.

[[v6-9-25]]

^<<v6-9-25,25>>^ Agora, estamos em suas mãos. Façam conosco o que lhes parecer correto".

[[v6-9-26]]

^<<v6-9-26,26>>^ Assim, Josué livrou os gibeonitas e não permitiu que os israelitas os matassem.

[[v6-9-27]]

^<<v6-9-27,27>>^ Naquele dia, porém, encarregou-os de cortar lenha e carregar água para toda a comunidade de Israel e para o altar do SENHOR, no lugar que o SENHOR escolhesse construí-lo. Isso é o que fazem até hoje.

'''

xref:006-josue/006-josue-008.adoc#v6-8-0[&#60; Capítulo Anterior] | <<v6-9-0,Topo>> | xref:006-josue/006-josue-010.adoc#v6-10-0[Próximo Capítulo &#62;]