include::./index.adoc[]

[[v6-8-0]]
=== Josué, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v6-8-1]]

^<<v6-8-1,1>>^ O SENHOR disse a Josué: "Não tenha medo nem desanime! Pegue todos os seus homens de guerra e avance contra Ai, pois eu lhe entreguei o rei de Ai, seu povo e sua terra.

[[v6-8-2]]

^<<v6-8-2,2>>^ Você os destruirá como destruiu Jericó e seu rei. Desta vez, porém, poderão ficar com os despojos e os animais. Prepare uma emboscada atrás da cidade".

[[v6-8-3]]

^<<v6-8-3,3>>^ Então Josué e todos os seus homens de guerra partiram para atacar Ai. Josué escolheu trinta mil de seus melhores guerreiros e, de noite, os enviou

[[v6-8-4]]

^<<v6-8-4,4>>^ com as seguintes ordens: "Armem uma emboscada atrás da cidade, perto dela, e preparem-se para entrar em ação.

[[v6-8-5]]

^<<v6-8-5,5>>^ Quando nosso exército principal atacar, os homens de Ai sairão para a luta, como fizeram antes, e nós fugiremos deles.

[[v6-8-6]]

^<<v6-8-6,6>>^ Eles nos perseguirão até que os tenhamos atraído para longe da cidade, pois dirão: ‘Os israelitas estão fugindo de nós como fizeram antes’. Então, enquanto corremos deles,

[[v6-8-7]]

^<<v6-8-7,7>>^ vocês sairão da emboscada e tomarão a cidade, pois o SENHOR, seu Deus, a entregará em suas mãos.

[[v6-8-8]]

^<<v6-8-8,8>>^ Ponham fogo na cidade, conforme o SENHOR ordenou. Essas são as minhas ordens".

[[v6-8-9]]

^<<v6-8-9,9>>^ Josué os enviou, e eles foram ao lugar da emboscada, entre Betel e o lado oeste de Ai. Josué, porém, passou a noite com o povo no acampamento.

[[v6-8-10]]

^<<v6-8-10,10>>^ No dia seguinte, logo cedo, Josué passou em revista a tropa e partiu para Ai acompanhado dos líderes de Israel.

[[v6-8-11]]

^<<v6-8-11,11>>^ Todos os homens de guerra que estavam com Josué se aproximaram da cidade e acamparam do lado norte de Ai, onde um vale os separava da cidade.

[[v6-8-12]]

^<<v6-8-12,12>>^ Naquela noite, Josué enviou cerca de cinco mil homens para esperarem escondidos entre Betel e Ai, do lado oeste da cidade.

[[v6-8-13]]

^<<v6-8-13,13>>^ O exército principal se posicionou ao norte da cidade, e o grupo da emboscada, a oeste. Josué, por sua vez, passou a noite no meio do vale.

[[v6-8-14]]

^<<v6-8-14,14>>^ Quando o rei de Ai viu os israelitas do outro lado do vale, ele e seu exército se apressaram e saíram bem cedo para os atacarem no local de onde se avista o vale do Jordão. Não sabiam, porém, que havia uma emboscada atrás da cidade.

[[v6-8-15]]

^<<v6-8-15,15>>^ Josué e o exército de Israel fugiram em direção ao deserto, como se estivessem derrotados.

[[v6-8-16]]

^<<v6-8-16,16>>^ Todos os homens da cidade foram chamados para persegui-los e, com isso, acabaram atraídos para longe da cidade.

[[v6-8-17]]

^<<v6-8-17,17>>^ Não restou um só homem em Ai e em Betel que não perseguisse Israel, e as cidades ficaram totalmente desprotegidas.

[[v6-8-18]]

^<<v6-8-18,18>>^ Então o SENHOR disse a Josué: "Aponte para Ai a lança que você tem na mão, pois eu lhe entregarei a cidade". Josué fez conforme ordenado

[[v6-8-19]]

^<<v6-8-19,19>>^ e, assim que deu esse sinal, todos os homens da emboscada saíram correndo de sua posição e invadiram a cidade. Em pouco tempo, eles a capturaram e a incendiaram.

[[v6-8-20]]

^<<v6-8-20,20>>^ Quando os homens de Ai olharam para trás, a fumaça da cidade subia ao céu e eles não tinham para onde ir, pois os israelitas que fugiam em direção ao deserto se voltaram contra seus perseguidores.

[[v6-8-21]]

^<<v6-8-21,21>>^ Ao perceberem que a emboscada havia sido bem-sucedida e fumaça subia da cidade, Josué e todo o exército de Israel deram meia-volta e atacaram os homens de Ai.

[[v6-8-22]]

^<<v6-8-22,22>>^ Enquanto isso, os israelitas que estavam dentro da cidade saíram e atacaram o inimigo pela retaguarda. Os homens de Ai ficaram presos no meio, com guerreiros israelitas de ambos os lados. Israel os atacou, e nenhum deles sobreviveu nem escapou.

[[v6-8-23]]

^<<v6-8-23,23>>^ Somente o rei de Ai foi capturado vivo e levado a Josué.

[[v6-8-24]]

^<<v6-8-24,24>>^ Quando o exército israelita terminou de perseguir e matar todos os homens de Ai nos campos abertos, voltou e acabou com quem tinha ficado dentro da cidade.

[[v6-8-25]]

^<<v6-8-25,25>>^ Toda a população de Ai, no total de doze mil homens e mulheres, foi exterminada naquele dia,

[[v6-8-26]]

^<<v6-8-26,26>>^ pois Josué manteve sua lança estendida até que todos os moradores de Ai tivessem sido completamente destruídos.

[[v6-8-27]]

^<<v6-8-27,27>>^ Somente os animais e os tesouros da cidade não foram destruídos, pois Israel os tomou como despojo, conforme o SENHOR havia ordenado a Josué.

[[v6-8-28]]

^<<v6-8-28,28>>^ Então Josué pôs fogo na cidade de Ai, e ela se tornou, para sempre, uma pilha de ruínas, um lugar desolado até hoje.

[[v6-8-29]]

^<<v6-8-29,29>>^ Josué enforcou o rei de Ai numa árvore e ali o deixou até a tarde. Ao pôr do sol, os israelitas retiraram o corpo da árvore e, por ordem de Josué, o lançaram em frente à porta da cidade. Sobre ele levantaram uma pilha de pedras, que permanece lá até hoje.

[[v6-8-30]]

^<<v6-8-30,30>>^ Então Josué construiu no monte Ebal um altar ao SENHOR, o Deus de Israel.

[[v6-8-31]]

^<<v6-8-31,31>>^ Seguiu as ordens que Moisés, servo do SENHOR, havia escrito no Livro da Lei: "Façam um altar de pedras inteiras, em sua forma natural, que não tenham sido trabalhadas com ferramentas de ferro". Sobre o altar, apresentaram ao SENHOR holocaustos e ofertas de paz.

[[v6-8-32]]

^<<v6-8-32,32>>^ E, enquanto os israelitas observavam, Josué copiou nas pedras a lei que Moisés lhes tinha escrito.

[[v6-8-33]]

^<<v6-8-33,33>>^ Todo o Israel, tanto os estrangeiros como os israelitas de nascimento, junto com os líderes, oficiais e juízes, se dividiu em dois grupos. Um grupo ficou em frente ao monte Gerizim, e o outro, em frente ao monte Ebal. Entre os dois grupos, que estavam voltados um para o outro, ficaram os sacerdotes levitas que levavam a arca da aliança do SENHOR. Tudo foi feito de acordo com as ordens transmitidas de antemão por Moisés, servo do SENHOR, para que o povo de Israel fosse abençoado.

[[v6-8-34]]

^<<v6-8-34,34>>^ Em seguida, Josué leu todas as bênçãos e maldições que Moisés havia escrito no Livro da Lei.

[[v6-8-35]]

^<<v6-8-35,35>>^ Cada palavra de cada ordem de Moisés foi lida para toda a comunidade de Israel, incluindo as mulheres, as crianças e os estrangeiros que viviam entre eles.

'''

xref:006-josue/006-josue-007.adoc#v6-7-0[&#60; Capítulo Anterior] | <<v6-8-0,Topo>> | xref:006-josue/006-josue-009.adoc#v6-9-0[Próximo Capítulo &#62;]