include::./index.adoc[]

[[v6-15-0]]
=== Josué, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v6-15-1]]

^<<v6-15-1,1>>^ As terras distribuídas por sorteio aos clãs da tribo de Judá se estendiam para o sul, até a divisa com Edom, e chegavam ao deserto de Zim, no extremo sul:

[[v6-15-2]]

^<<v6-15-2,2>>^ A divisa ao sul começava na extremidade sul do mar Morto,

[[v6-15-3]]

^<<v6-15-3,3>>^ seguia para o sul pela ladeira do Escorpião, passando pelo deserto de Zim e prosseguindo até Hezrom, ao sul de Cades-Barneia. Então subia até Adar e fazia uma curva em direção a Carca.

[[v6-15-4]]

^<<v6-15-4,4>>^ Dali passava por Azmom, continuava até o ribeiro do Egito e seguia até o mar Mediterrâneo. Essa era a divisa ao sul deles.

[[v6-15-5]]

^<<v6-15-5,5>>^ A divisa a leste se estendia ao longo do mar Morto até a foz do rio Jordão. A divisa ao norte começava na extremidade onde o Jordão deságua no mar Morto,

[[v6-15-6]]

^<<v6-15-6,6>>^ subia dali para Bete-Hogla e continuava ao norte de Bete-Arabá, até a Pedra de Boã (Boã era filho de Rúben).

[[v6-15-7]]

^<<v6-15-7,7>>^ A partir desse ponto, passava pelo vale de Acor até Debir, fazendo uma curva para o norte, em direção a Gilgal, que ficava de frente ao desfiladeiro de Adumim, do lado sul do vale. Dali a divisa se estendia para as águas de En-Semes, até En-Rogel.

[[v6-15-8]]

^<<v6-15-8,8>>^ Depois passava pelo vale de Ben-Hinom, pela encosta sul dos jebuseus, onde fica a cidade de Jerusalém. Em seguida estendia-se para o oeste, até o alto do monte acima do vale de Hinom, e continuava até a extremidade norte do vale de Refaim.

[[v6-15-9]]

^<<v6-15-9,9>>^ A divisa prosseguia do alto do monte para a fonte nas águas de Neftoa, até as cidades do monte Efrom. Então fazia uma curva em direção a Baalá (isto é, Quiriate-Jearim).

[[v6-15-10]]

^<<v6-15-10,10>>^ Rodeava Baalá em direção ao oeste, até o monte Seir, passava pela cidade de Quesalom, na encosta norte do monte Jearim, descia a Bete-Semes e passava por Timna.

[[v6-15-11]]

^<<v6-15-11,11>>^ Depois a divisa continuava até a encosta do monte ao norte de Ecrom, onde fazia uma curva em direção a Sicrom e o monte Baalá. Passava por Jabneel e terminava no mar Mediterrâneo.

[[v6-15-12]]

^<<v6-15-12,12>>^ A divisa ocidental era o litoral do mar Mediterrâneo. Essas são as divisas dos clãs da tribo de Judá.

[[v6-15-13]]

^<<v6-15-13,13>>^ Por ordem do SENHOR, Josué designou uma porção no meio do território de Judá para Calebe, filho de Jefoné. Calebe recebeu a cidade de Quiriate-Arba (isto é, Hebrom), assim chamada por causa de Arba, um antepassado de Enaque.

[[v6-15-14]]

^<<v6-15-14,14>>^ Calebe expulsou três grupos de enaquins: os descendentes de Sesai, de Aimã e de Talmai, filhos de Enaque.

[[v6-15-15]]

^<<v6-15-15,15>>^ Dali ele partiu para lutar contra os habitantes da cidade de Debir (antes chamada de Quiriate-Sefer).

[[v6-15-16]]

^<<v6-15-16,16>>^ Calebe disse: "Darei minha filha Acsa em casamento a quem atacar e tomar Quiriate-Sefer".

[[v6-15-17]]

^<<v6-15-17,17>>^ Otoniel, filho de Quenaz, irmão de Calebe, tomou a cidade, e Calebe lhe deu Acsa como esposa.

[[v6-15-18]]

^<<v6-15-18,18>>^ Quando Acsa se casou com Otoniel, ela insistiu para que ele pedisse um campo ao pai dela. Assim que ela desceu do jumento, Calebe lhe perguntou: "O que você quer?".

[[v6-15-19]]

^<<v6-15-19,19>>^ Ela respondeu: "Quero mais um presente. O senhor me deu terras no deserto do Neguebe; agora, peço que também me dê fontes de água". Então Calebe lhe deu as fontes superiores e as fontes inferiores.

[[v6-15-20]]

^<<v6-15-20,20>>^ Esta foi a herança designada aos clãs da tribo de Judá:

[[v6-15-21]]

^<<v6-15-21,21>>^ As cidades de Judá situadas ao longo da divisa com Edom, no extremo sul, eram: Cabzeel, Éder, Jagur,

[[v6-15-22]]

^<<v6-15-22,22>>^ Quiná, Dimona, Adada,

[[v6-15-23]]

^<<v6-15-23,23>>^ Quedes, Hazor, Itnã,

[[v6-15-24]]

^<<v6-15-24,24>>^ Zife, Telém, Bealote,

[[v6-15-25]]

^<<v6-15-25,25>>^ Hazor-Hadata, Queriote-Hezrom (isto é, Hazor),

[[v6-15-26]]

^<<v6-15-26,26>>^ Amã, Sema, Moladá,

[[v6-15-27]]

^<<v6-15-27,27>>^ Hazar-Gada, Hesmom, Bete-Pelete,

[[v6-15-28]]

^<<v6-15-28,28>>^ Hazar-Sual, Berseba, Biziotiá,

[[v6-15-29]]

^<<v6-15-29,29>>^ Baalá, Iim, Azém,

[[v6-15-30]]

^<<v6-15-30,30>>^ Eltolade, Quesil, Hormá,

[[v6-15-31]]

^<<v6-15-31,31>>^ Ziclague, Madmana, Sansana,

[[v6-15-32]]

^<<v6-15-32,32>>^ Lebaote, Silim, Aim e Rimom; ao todo, 29 cidades com os povoados ao redor.

[[v6-15-33]]

^<<v6-15-33,33>>^ As seguintes cidades situadas nas colinas do oeste também foram entregues a Judá: Estaol, Zorá, Asná,

[[v6-15-34]]

^<<v6-15-34,34>>^ Zanoa, En-Ganim, Tapua, Enã,

[[v6-15-35]]

^<<v6-15-35,35>>^ Jarmute, Adulão, Socó, Azeca,

[[v6-15-36]]

^<<v6-15-36,36>>^ Saaraim, Aditaim, Gederá e Gederotaim; catorze cidades com os povoados ao redor.

[[v6-15-37]]

^<<v6-15-37,37>>^ Também foram incluídas: Zenã, Hadasa, Migdal-Gade,

[[v6-15-38]]

^<<v6-15-38,38>>^ Dileã, Mispá, Jocteel,

[[v6-15-39]]

^<<v6-15-39,39>>^ Laquis, Bozcate, Eglom,

[[v6-15-40]]

^<<v6-15-40,40>>^ Cabom, Laamás, Quitlis,

[[v6-15-41]]

^<<v6-15-41,41>>^ Gederote, Bete-Dagom, Naamá e Maquedá; dezesseis cidades com os povoados ao redor.

[[v6-15-42]]

^<<v6-15-42,42>>^ Além dessas, também foram entregues: Libna, Eter, Asã,

[[v6-15-43]]

^<<v6-15-43,43>>^ Iftá, Asná, Nezibe,

[[v6-15-44]]

^<<v6-15-44,44>>^ Queila, Aczibe e Maressa; nove cidades com os povoados ao redor.

[[v6-15-45]]

^<<v6-15-45,45>>^ O território da tribo de Judá abrangia, ainda, Ecrom com os assentamentos e povoados ao redor.

[[v6-15-46]]

^<<v6-15-46,46>>^ De Ecrom, a divisa se estendia para o oeste, e incluía as cidades perto de Asdode, com os povoados ao redor.

[[v6-15-47]]

^<<v6-15-47,47>>^ Também incluía Asdode, com os assentamentos e povoados ao redor, e Gaza, com os assentamentos e povoados ao redor, até o ribeiro do Egito, e ao longo do litoral do mar Mediterrâneo.

[[v6-15-48]]

^<<v6-15-48,48>>^ Judá também recebeu estas cidades na região montanhosa: Samir, Jatir, Socó,

[[v6-15-49]]

^<<v6-15-49,49>>^ Daná, Quiriate-Sana (isto é, Debir),

[[v6-15-50]]

^<<v6-15-50,50>>^ Anabe, Estemo, Anim,

[[v6-15-51]]

^<<v6-15-51,51>>^ Gósen, Holom e Gilo; onze cidades com os povoados ao redor.

[[v6-15-52]]

^<<v6-15-52,52>>^ Foram incluídas ainda: Arabe, Dumá, Esã,

[[v6-15-53]]

^<<v6-15-53,53>>^ Janim, Bete-Tapua, Afeca,

[[v6-15-54]]

^<<v6-15-54,54>>^ Hunta, Quiriate-Arba (isto é, Hebrom), e Zior; nove cidades com os povoados ao seu redor.

[[v6-15-55]]

^<<v6-15-55,55>>^ Além destas, também foram entregues: Maom, Carmelo, Zife, Jutá,

[[v6-15-56]]

^<<v6-15-56,56>>^ Jezreel, Jocdeão, Zanoa,

[[v6-15-57]]

^<<v6-15-57,57>>^ Caim, Gibeá e Timna; dez cidades com os povoados ao redor.

[[v6-15-58]]

^<<v6-15-58,58>>^ E ainda: Halul, Bete-Zur, Gedor,

[[v6-15-59]]

^<<v6-15-59,59>>^ Maarate, Bete-Anote e Eltecom; seis cidades com os povoados ao redor.

[[v6-15-60]]

^<<v6-15-60,60>>^ Também: Quiriate-Baal (isto é, Quiriate-Jearim), e Rabá; duas cidades com os povoados ao redor.

[[v6-15-61]]

^<<v6-15-61,61>>^ No deserto ficavam: Bete-Arabá, Midim, Secacá,

[[v6-15-62]]

^<<v6-15-62,62>>^ Nibsã, a Cidade do Sal e En-Gedi; seis cidades com os povoados ao redor.

[[v6-15-63]]

^<<v6-15-63,63>>^ Contudo, a tribo de Judá não conseguiu expulsar os jebuseus, que habitavam em Jerusalém, de modo que os jebuseus vivem até hoje no meio de Judá.

'''

xref:006-josue/006-josue-014.adoc#v6-14-0[&#60; Capítulo Anterior] | <<v6-15-0,Topo>> | xref:006-josue/006-josue-016.adoc#v6-16-0[Próximo Capítulo &#62;]