include::./index.adoc[]

[[v6-17-0]]
=== Josué, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v6-17-1]]

^<<v6-17-1,1>>^ A porção seguinte de terra foi entregue por sorteio à meia tribo de Manassés, os descendentes do filho mais velho de José. Maquir, filho mais velho de Manassés, era pai de Gileade. Guerreiros valentes, ele e seus descendentes receberam as regiões de Gileade e Basã, a leste do rio Jordão.

[[v6-17-2]]

^<<v6-17-2,2>>^ Assim, a porção de terra a oeste do Jordão foi para as demais famílias dos clãs da tribo de Manassés: Abiezer, Heleque, Asriel, Siquém, Héfer e Semida. Esses descendentes do sexo masculino representavam os clãs de Manassés, filho de José.

[[v6-17-3]]

^<<v6-17-3,3>>^ Contudo, Zelofeade, filho de Héfer, filho de Gileade, filho de Maquir, filho de Manassés, não teve filhos, mas somente filhas. Seus nomes eram: Maala, Noa, Hogla, Milca e Tirza.

[[v6-17-4]]

^<<v6-17-4,4>>^ Essas mulheres foram ao sacerdote Eleazar, a Josué, filho de Num, e aos líderes israelitas e disseram: "O SENHOR ordenou a Moisés que nos entregasse uma porção de terra como herança junto a nossos parentes". Então Josué lhes deu uma herança entre os irmãos de seu pai, conforme o SENHOR havia ordenado.

[[v6-17-5]]

^<<v6-17-5,5>>^ Assim, a tribo de Manassés recebeu, no total, dez porções de terra, além de Gileade e Basã, do outro lado do Jordão,

[[v6-17-6]]

^<<v6-17-6,6>>^ pois as descendentes de Manassés receberam uma herança entre os descendentes dele. (A terra de Gileade foi entregue aos demais descendentes de Manassés.)

[[v6-17-7]]

^<<v6-17-7,7>>^ A divisa da tribo de Manassés se estendia desde Aser até Micmetá, perto de Siquém. Dali prosseguia para o sul, de Micmetá até o assentamento junto à fonte de Tapua.

[[v6-17-8]]

^<<v6-17-8,8>>^ As terras ao redor de Tapua pertenciam a Manassés, mas a cidade de Tapua propriamente dita, na divisa do território de Manassés, pertencia à tribo de Efraim.

[[v6-17-9]]

^<<v6-17-9,9>>^ Da fonte de Tapua a divisa de Manassés seguia pelo vale de Caná e dali chegava até o mar Mediterrâneo. Várias cidades ao sul do vale ficavam dentro do território de Manassés, mas, na verdade, pertenciam à tribo de Efraim.

[[v6-17-10]]

^<<v6-17-10,10>>^ Em geral, porém, a terra ao sul do vale pertencia a Efraim, e a terra ao norte do vale pertencia a Manassés. A divisa de Manassés acompanhava o lado norte do ribeiro e terminava no mar Mediterrâneo. Ao norte de Manassés ficava o território de Aser e, a leste, o território de Issacar.

[[v6-17-11]]

^<<v6-17-11,11>>^ As seguintes cidades dentro do território de Issacar e Aser foram entregues a Manassés: Bete-Sã, Ibleã, Dor (isto é, Nafote-Dor), En-Dor, Taanaque e Megido, cada uma com os assentamentos ao redor.

[[v6-17-12]]

^<<v6-17-12,12>>^ Contudo, os descendentes de Manassés não conseguiram ocupar essas cidades, pois os cananeus estavam determinados a permanecer naquela região.

[[v6-17-13]]

^<<v6-17-13,13>>^ Mais tarde, quando os israelitas se tornaram fortes o suficiente, submeteram os cananeus a trabalhos forçados, mas não os expulsaram completamente.

[[v6-17-14]]

^<<v6-17-14,14>>^ Os descendentes de José foram a Josué e perguntaram: "Por que você nos deu apenas uma porção de terra como herança, uma vez que o SENHOR nos tornou um povo tão numeroso?".

[[v6-17-15]]

^<<v6-17-15,15>>^ Josué respondeu: "Se vocês são tão numerosos, e se a região montanhosa de Efraim não é grande o suficiente para vocês, abram espaço nos bosques onde habitam os ferezeus e os refains".

[[v6-17-16]]

^<<v6-17-16,16>>^ Os descendentes de José disseram: "É verdade que a região montanhosa não é grande o suficiente para nós. Mas todos os cananeus do vale, tanto os de Bete-Sã e dos povoados ao redor como os do vale de Jezreel, têm carros de guerra com rodas de ferro; são fortes demais para nós".

[[v6-17-17]]

^<<v6-17-17,17>>^ Então Josué disse às tribos de Efraim e Manassés, os descendentes de José: "Uma vez que vocês são tão numerosos e fortes, receberão mais de uma porção.

[[v6-17-18]]

^<<v6-17-18,18>>^ Os bosques na região montanhosa também serão seus. Abram todo o espaço que desejarem e tomem posse de seus limites mais distantes. E, embora os cananeus dos vales sejam fortes e tenham carros de guerra com rodas de ferro, vocês conseguirão expulsá-los".

'''

xref:006-josue/006-josue-016.adoc#v6-16-0[&#60; Capítulo Anterior] | <<v6-17-0,Topo>> | xref:006-josue/006-josue-018.adoc#v6-18-0[Próximo Capítulo &#62;]