include::./index.adoc[]

[[v6-11-0]]
=== Josué, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v6-11-1]]

^<<v6-11-1,1>>^ Quando Jabim, rei de Hazor, soube do que havia acontecido, enviou mensagens aos seguintes reis: a Jobabe, rei de Madom; ao rei de Sinrom; ao rei de Acsafe;

[[v6-11-2]]

^<<v6-11-2,2>>^ a todos os reis da região montanhosa ao norte; aos reis do vale do Jordão, ao sul da Galileia; aos reis das colinas do oeste; aos reis de Nafote-Dor, a oeste;

[[v6-11-3]]

^<<v6-11-3,3>>^ aos reis de Canaã, a leste e a oeste; aos reis dos amorreus, dos hititas, dos ferezeus, dos jebuseus da região montanhosa, e dos heveus das cidades nas encostas do Hermom, na região de Mispá.

[[v6-11-4]]

^<<v6-11-4,4>>^ Todos esses reis saíram para lutar. Juntos, seus exércitos formavam uma grande multidão, como a areia na beira do mar, equipados com muitos cavalos e carros de guerra.

[[v6-11-5]]

^<<v6-11-5,5>>^ Os reis se uniram e acamparam ao redor das águas perto de Merom, para guerrearem contra Israel.

[[v6-11-6]]

^<<v6-11-6,6>>^ Então o SENHOR disse a Josué: "Não tenha medo deles. Amanhã a esta hora eu os entregarei todos mortos a Israel. Vocês deverão cortar os tendões de seus cavalos e queimar seus carros de guerra".

[[v6-11-7]]

^<<v6-11-7,7>>^ Josué e todo o exército foram às águas perto de Merom e atacaram de surpresa,

[[v6-11-8]]

^<<v6-11-8,8>>^ e o SENHOR deu a Israel vitória sobre seus inimigos. Os israelitas os perseguiram até a grande Sidom, até Misrefote-Maim e até o vale de Mispá, a leste, e não sobrou nenhum guerreiro inimigo com vida.

[[v6-11-9]]

^<<v6-11-9,9>>^ Então Josué cortou os tendões dos cavalos e queimou todos os carros de guerra, conforme o SENHOR havia ordenado.

[[v6-11-10]]

^<<v6-11-10,10>>^ Depois, Josué voltou, tomou Hazor e matou seu rei. Em outros tempos, Hazor havia sido a capital de todos esses reinos.

[[v6-11-11]]

^<<v6-11-11,11>>^ Os israelitas mataram e destruíram completamente todos que viviam na cidade, sem deixar sobreviventes. Ninguém foi poupado. Por fim, Josué queimou a cidade.

[[v6-11-12]]

^<<v6-11-12,12>>^ Josué matou todos os outros reis e seus povos e os destruiu completamente, conforme Moisés, servo do SENHOR, havia ordenado.

[[v6-11-13]]

^<<v6-11-13,13>>^ Mas Israel não incendiou nenhuma das cidades construídas nas colinas, exceto Hazor, que Josué queimou.

[[v6-11-14]]

^<<v6-11-14,14>>^ Os israelitas tomaram todos os despojos e os animais das cidades destruídas, mas mataram todos os seus habitantes, sem deixar sobreviventes.

[[v6-11-15]]

^<<v6-11-15,15>>^ Conforme o SENHOR havia ordenado a seu servo Moisés, também Moisés ordenou a Josué, e ele obedeceu fielmente a todas as ordens que o SENHOR tinha dado a Moisés.

[[v6-11-16]]

^<<v6-11-16,16>>^ Assim, Josué conquistou toda aquela terra: a região montanhosa, todo o Neguebe, toda a região ao redor da cidade de Gósen, as colinas do oeste, o vale do Jordão, os montes de Israel e as colinas próximas.

[[v6-11-17]]

^<<v6-11-17,17>>^ O território israelita se estendia agora desde o monte Halaque, que sobe em direção a Seir, até Baal-Gade, no vale do Líbano, ao pé do monte Hermom. Josué capturou e matou todos os reis desses territórios,

[[v6-11-18]]

^<<v6-11-18,18>>^ depois de guerrear contra eles por muito tempo.

[[v6-11-19]]

^<<v6-11-19,19>>^ Ninguém na região fez tratados de paz com os israelitas, exceto os heveus de Gibeom. Todos os outros foram derrotados na guerra,

[[v6-11-20]]

^<<v6-11-20,20>>^ pois o SENHOR lhes endureceu o coração para que lutassem contra Israel. Por isso, foram completamente destruídos, sem misericórdia, conforme o SENHOR havia ordenado a Moisés.

[[v6-11-21]]

^<<v6-11-21,21>>^ Nesse período, Josué destruiu todos os descendentes de Enaque da região montanhosa de Hebrom, Debir, Anabe, e de toda a região montanhosa de Judá e Israel. Matou todos eles e destruiu completamente suas cidades.

[[v6-11-22]]

^<<v6-11-22,22>>^ Não sobreviveu nenhum descendente de Enaque em todo o território dos israelitas, embora restassem alguns em Gaza, Gate e Asdode.

[[v6-11-23]]

^<<v6-11-23,23>>^ Assim, Josué assumiu o controle de toda a terra, conforme o SENHOR havia instruído Moisés. Josué a entregou ao povo de Israel como herança e a repartiu entre as tribos. E, por fim, a terra descansou da guerra.

'''

xref:006-josue/006-josue-010.adoc#v6-10-0[&#60; Capítulo Anterior] | <<v6-11-0,Topo>> | xref:006-josue/006-josue-012.adoc#v6-12-0[Próximo Capítulo &#62;]