include::./index.adoc[]

[[v6-4-0]]
=== Josué, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v6-4-1]]

^<<v6-4-1,1>>^ Quando todo o povo havia atravessado o Jordão, o SENHOR disse a Josué:

[[v6-4-2]]

^<<v6-4-2,2>>^ "Escolha doze homens, um de cada tribo,

[[v6-4-3]]

^<<v6-4-3,3>>^ e dê a eles as seguintes ordens: ‘Peguem doze pedras do local onde os sacerdotes estão parados no meio do rio. Levem as pedras com vocês e amontoem-nas no lugar onde vão acampar esta noite’".

[[v6-4-4]]

^<<v6-4-4,4>>^ Então Josué convocou os doze homens que havia escolhido, um de cada tribo de Israel,

[[v6-4-5]]

^<<v6-4-5,5>>^ e lhes disse: ‘Vão até o meio do Jordão, à frente da arca do SENHOR, seu Deus. Cada um de vocês pegue uma pedra e carregue-a sobre o ombro; serão doze pedras no total, uma para cada tribo de Israel.

[[v6-4-6]]

^<<v6-4-6,6>>^ Elas serão um monumento entre vocês. No futuro, seus filhos perguntarão: ‘O que significam estas pedras?’,

[[v6-4-7]]

^<<v6-4-7,7>>^ e vocês dirão: ‘Elas servem para nos lembrar que o rio Jordão parou de correr quando a arca da aliança do SENHOR passou por ele’. Essas pedras serão uma recordação no meio dos israelitas para sempre".

[[v6-4-8]]

^<<v6-4-8,8>>^ Assim, os israelitas fizeram como Josué havia ordenado. Pegaram doze pedras do meio do Jordão, uma para cada tribo, exatamente como o SENHOR tinha dito a Josué. Levaram as pedras ao lugar onde acamparam aquela noite e as deixaram ali.

[[v6-4-9]]

^<<v6-4-9,9>>^ Josué também ergueu um monumento com doze pedras no meio do Jordão, no lugar onde haviam parado os sacerdotes que levavam a arca da aliança. Essas pedras estão lá até hoje.

[[v6-4-10]]

^<<v6-4-10,10>>^ Os sacerdotes que levavam a arca ficaram parados no meio do rio até que fossem cumpridas todas as ordens do SENHOR transmitidas a Josué por Moisés. E o povo se apressou em atravessar o leito do rio.

[[v6-4-11]]

^<<v6-4-11,11>>^ Quando todos chegaram ao outro lado, os sacerdotes atravessaram com a arca do SENHOR, enquanto o povo observava.

[[v6-4-12]]

^<<v6-4-12,12>>^ Os guerreiros das tribos de Rúben e Gade e da meia tribo de Manassés atravessaram à frente dos israelitas, armados conforme Moisés havia instruído.

[[v6-4-13]]

^<<v6-4-13,13>>^ Esses homens, cerca de quarenta mil, estavam armados para a guerra, e o SENHOR ia com eles enquanto avançavam para a planície de Jericó.

[[v6-4-14]]

^<<v6-4-14,14>>^ Naquele dia, o SENHOR fez de Josué um grande líder aos olhos de todo o Israel, e eles o respeitaram enquanto ele viveu, como haviam respeitado Moisés.

[[v6-4-15]]

^<<v6-4-15,15>>^ O SENHOR disse a Josué:

[[v6-4-16]]

^<<v6-4-16,16>>^ "Ordene aos sacerdotes que levam a arca da aliança que saiam do meio do rio".

[[v6-4-17]]

^<<v6-4-17,17>>^ Então Josué ordenou: "Saiam do meio do rio!".

[[v6-4-18]]

^<<v6-4-18,18>>^ Assim que os sacerdotes que levavam a arca da aliança do SENHOR saíram do leito do rio e pisaram em terra seca, a água do Jordão voltou a fluir e transbordou sobre as margens como antes.

[[v6-4-19]]

^<<v6-4-19,19>>^ O povo atravessou o Jordão no décimo dia do primeiro mês e acampou em Gilgal, a leste de Jericó.

[[v6-4-20]]

^<<v6-4-20,20>>^ Foi ali, em Gilgal, que Josué ergueu o monumento com as doze pedras tiradas do Jordão.

[[v6-4-21]]

^<<v6-4-21,21>>^ Então Josué disse aos israelitas: "No futuro, seus filhos perguntarão: ‘O que significam estas pedras?’,

[[v6-4-22]]

^<<v6-4-22,22>>^ e vocês dirão: ‘Aqui o povo de Israel atravessou o Jordão a pés enxutos’.

[[v6-4-23]]

^<<v6-4-23,23>>^ Pois o SENHOR, seu Deus, secou o rio diante de seus olhos e o manteve seco até todos vocês atravessarem, como fez com o mar Vermelho quando o secou até que todos vocês tivessem atravessado.

[[v6-4-24]]

^<<v6-4-24,24>>^ Fez isso para que todas as nações da terra saibam que a mão do SENHOR é poderosa e para que vocês temam o SENHOR, seu Deus, para sempre".

'''

xref:006-josue/006-josue-003.adoc#v6-3-0[&#60; Capítulo Anterior] | <<v6-4-0,Topo>> | xref:006-josue/006-josue-005.adoc#v6-5-0[Próximo Capítulo &#62;]