include::./index.adoc[]

[[v6-22-0]]
=== Josué, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v6-22-1]]

^<<v6-22-1,1>>^ Então Josué convocou as tribos de Rúben e Gade e a meia tribo de Manassés

[[v6-22-2]]

^<<v6-22-2,2>>^ e lhes disse: "Vocês fizeram tudo que Moisés, servo do SENHOR, mandou e obedeceram a todas as minhas ordens.

[[v6-22-3]]

^<<v6-22-3,3>>^ Durante todo esse tempo e até hoje, não abandonaram seus irmãos das outras tribos e tiveram o cuidado de obedecer a tudo que o SENHOR, seu Deus, ordenou.

[[v6-22-4]]

^<<v6-22-4,4>>^ Agora o SENHOR, seu Deus, concedeu descanso a seus irmãos, como prometeu a eles. Portanto, voltem para casa, para a terra que Moisés, servo do SENHOR, lhes deu como sua propriedade do outro lado do rio Jordão.

[[v6-22-5]]

^<<v6-22-5,5>>^ Mas tenham muito cuidado de cumprir todos os mandamentos e a lei que Moisés, servo do SENHOR, lhes deu. Amem o SENHOR, seu Deus, andem em todos os seus caminhos, obedeçam a seus mandamentos, apeguem-se a ele firmemente e sirvam-no de todo o coração e de toda a alma".

[[v6-22-6]]

^<<v6-22-6,6>>^ Então Josué os abençoou e se despediu deles, e eles foram para casa.

[[v6-22-7]]

^<<v6-22-7,7>>^ Moisés tinha dado o território de Basã, a leste do rio Jordão, à meia tribo de Manassés. À outra metade da tribo, Josué deu terras a oeste do Jordão. Quando Josué se despediu deles e os abençoou,

[[v6-22-8]]

^<<v6-22-8,8>>^ disse: "Voltem para casa com toda a riqueza que tomaram de seus inimigos: grandes rebanhos, prata, ouro, bronze, ferro e muitas roupas. Repartam os despojos com seus parentes".

[[v6-22-9]]

^<<v6-22-9,9>>^ Assim, os homens de Rúben e Gade e da meia tribo de Manassés deixaram os outros israelitas em Siló, na terra de Canaã, e partiram para sua própria terra em Gileade, da qual haviam tomado posse de acordo com a ordem do SENHOR, por meio de Moisés.

[[v6-22-10]]

^<<v6-22-10,10>>^ Enquanto ainda estavam em Canaã, chegaram a um lugar chamado Gelilote, perto do rio Jordão. Ali os homens de Rúben e Gade e da meia tribo de Manassés pararam e construíram um altar grande e imponente.

[[v6-22-11]]

^<<v6-22-11,11>>^ Os outros israelitas souberam que os membros das tribos de Rúben e Gade e da meia tribo de Manassés haviam construído um altar em Gelilote, nos limites da terra de Canaã, do lado oeste do Jordão.

[[v6-22-12]]

^<<v6-22-12,12>>^ Por isso, toda a comunidade de Israel se reuniu em Siló e se preparou para guerrear contra eles.

[[v6-22-13]]

^<<v6-22-13,13>>^ Antes, porém, enviaram à terra de Gileade uma delegação liderada por Fineias, filho do sacerdote Eleazar, para conversar com as tribos de Rúben e Gade e a meia tribo de Manassés.

[[v6-22-14]]

^<<v6-22-14,14>>^ A delegação era formada por dez líderes de Israel, um de cada uma das dez tribos, e todos eles eram chefes de suas famílias dentro dos clãs de Israel.

[[v6-22-15]]

^<<v6-22-15,15>>^ Quando chegaram à terra de Gileade, disseram às tribos de Rúben e Gade e à meia tribo de Manassés:

[[v6-22-16]]

^<<v6-22-16,16>>^ "Toda a comunidade do SENHOR quer saber por que vocês foram tão infiéis ao Deus de Israel! Como puderam se afastar tanto do SENHOR? Vocês construíram para si um altar, rebelando-se contra ele!

[[v6-22-17]]

^<<v6-22-17,17>>^ Não bastou o pecado do incidente em Peor? Até hoje, não estamos completamente purificados dele, mesmo depois que a praga feriu toda a comunidade do SENHOR.

[[v6-22-18]]

^<<v6-22-18,18>>^ E, ainda assim, vocês abandonam o SENHOR. Se hoje vocês se rebelarem contra o SENHOR, amanhã ele voltará sua ira contra toda a comunidade de Israel!

[[v6-22-19]]

^<<v6-22-19,19>>^ "Se a porção de terra que receberam como herança está impura, passem para o nosso lado, para a terra do SENHOR, onde está o tabernáculo do SENHOR, e tomem posse de um território entre nós. Mas não se rebelem contra o SENHOR nem contra nós, construindo para si um altar que não seja o verdadeiro altar do SENHOR, nosso Deus.

[[v6-22-20]]

^<<v6-22-20,20>>^ Quando Acã, descendente de Zerá, foi infiel ao SENHOR, roubando as coisas separadas para o SENHOR, a ira divina não caiu sobre toda a comunidade de Israel? E Acã não foi o único que morreu por causa do seu pecado!".

[[v6-22-21]]

^<<v6-22-21,21>>^ Então os membros das tribos de Rúben e Gade e da meia tribo de Manassés responderam aos chefes dos clãs de Israel:

[[v6-22-22]]

^<<v6-22-22,22>>^ "O SENHOR, o Poderoso, é Deus! O SENHOR, o Poderoso, é Deus! Ele sabe a verdade, e que Israel a saiba também! Não construímos o altar por rebeldia nem por infidelidade ao SENHOR. Se o fizemos, não poupem nossa vida hoje.

[[v6-22-23]]

^<<v6-22-23,23>>^ Se construímos o altar para nos afastarmos do SENHOR ou para apresentarmos holocaustos, ofertas de cereal ou ofertas de paz, que o próprio SENHOR nos castigue.

[[v6-22-24]]

^<<v6-22-24,24>>^ "A verdade é que construímos este altar por medo de que, no futuro, seus descendentes digam aos nossos: ‘Que direito vocês têm de adorar o SENHOR, o Deus de Israel?

[[v6-22-25]]

^<<v6-22-25,25>>^ O SENHOR pôs o rio Jordão como barreira entre o nosso povo e o povo de Rúben e Gade. Vocês não têm parte com o SENHOR’. Então seus descendentes poderão impedir os nossos de adorarem o SENHOR.

[[v6-22-26]]

^<<v6-22-26,26>>^ "Por isso, resolvemos construir o altar, não para oferecer holocaustos ou sacrifícios,

[[v6-22-27]]

^<<v6-22-27,27>>^ mas como testemunho. Ele lembrará os nossos e os seus descendentes de que nós também temos o direito de servir ao SENHOR em seu santuário com holocaustos, sacrifícios e ofertas de paz. Então seus descendentes não poderão dizer aos nossos: ‘Vocês não têm parte com o SENHOR’.

[[v6-22-28]]

^<<v6-22-28,28>>^ "Se disserem isso, nossos descendentes responderão: ‘Vejam esta réplica do altar do SENHOR que nossos antepassados fizeram. Não é para holocaustos nem sacrifícios; é uma lembrança do relacionamento que vocês e nós temos com o SENHOR’.

[[v6-22-29]]

^<<v6-22-29,29>>^ Longe de nós nos rebelarmos contra o SENHOR, ou nos afastarmos dele, construindo nosso próprio altar para holocaustos, ofertas de cereal ou sacrifícios. Somente o altar do SENHOR, nosso Deus, que está diante do seu tabernáculo pode ser usado para esse fim".

[[v6-22-30]]

^<<v6-22-30,30>>^ Quando o sacerdote Fineias e os líderes da comunidade, os chefes dos clãs de Israel, ouviram o que os membros das tribos de Rúben e Gade e da meia tribo de Manassés disseram, ficaram satisfeitos.

[[v6-22-31]]

^<<v6-22-31,31>>^ Fineias, filho do sacerdote Eleazar, lhes respondeu: "Hoje sabemos que o SENHOR está no meio de nós, pois vocês não foram infiéis ao SENHOR, como havíamos imaginado. Ao contrário, livraram Israel de ser destruído pela mão do SENHOR".

[[v6-22-32]]

^<<v6-22-32,32>>^ Então Fineias, filho do sacerdote Eleazar, e os outros líderes deixaram as tribos de Rúben e Gade em Gileade e voltaram à terra de Canaã para relatar aos israelitas o que havia acontecido.

[[v6-22-33]]

^<<v6-22-33,33>>^ Todos os israelitas ficaram satisfeitos, louvaram a Deus e não falaram mais em guerrear contra Rúben e Gade.

[[v6-22-34]]

^<<v6-22-34,34>>^ Os membros das tribos de Rúben e Gade chamaram o altar de "Testemunho", pois disseram: "É um testemunho entre nós e eles de que o SENHOR é, também, o nosso Deus".

'''

xref:006-josue/006-josue-021.adoc#v6-21-0[&#60; Capítulo Anterior] | <<v6-22-0,Topo>> | xref:006-josue/006-josue-023.adoc#v6-23-0[Próximo Capítulo &#62;]