include::./index.adoc[]

[[v6-12-0]]
=== Josué, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v6-12-1]]

^<<v6-12-1,1>>^ Estes são os reis a leste do Jordão que os israelitas mataram e de cujas terras se apossaram. Seu território se estendia desde o vale do Arnom até o monte Hermom, e incluía toda a terra no lado leste do vale do Jordão.

[[v6-12-2]]

^<<v6-12-2,2>>^ Derrotaram Seom, rei dos amorreus, que vivia em Hesbom. Seu reino abrangia Aroer, à beira do vale do Arnom, e se estendia desde a cidade no meio do vale até o rio Jaboque, que é a divisa com os amonitas. Esse território incluía toda a metade sul de Gileade.

[[v6-12-3]]

^<<v6-12-3,3>>^ Seom também controlava o vale do Jordão e algumas regiões a leste, desde o mar da Galileia, ao norte, até o mar Morto, ao sul, incluindo o caminho para Bete-Jesimote e, mais ao sul, as encostas do monte Pisga.

[[v6-12-4]]

^<<v6-12-4,4>>^ Derrotaram Ogue, rei de Basã e o último dos refains, que vivia em Astarote e em Edrei.

[[v6-12-5]]

^<<v6-12-5,5>>^ Ele governava o território que se estendia desde o monte Hermom até Salcá, ao norte; toda a região de Basã, a leste, até a divisa com os reinos de Gesur e Maaca, a oeste. Esse território abrangia a metade norte de Gileade, até a divisa com Seom, rei de Hesbom.

[[v6-12-6]]

^<<v6-12-6,6>>^ Moisés, servo do SENHOR, e os israelitas haviam destruído o povo do rei Seom e o povo do rei Ogue. Moisés havia entregado a terra deles como propriedade às tribos de Rúben e Gade e à meia tribo de Manassés.

[[v6-12-7]]

^<<v6-12-7,7>>^ Esta é a lista dos reis que Josué e os israelitas derrotaram a oeste do rio Jordão, desde Baal-Gade, no vale do Líbano, até o monte Halaque, que sobe em direção a Seir. Josué deu essa terra como propriedade às tribos de Israel e a repartiu entre elas.

[[v6-12-8]]

^<<v6-12-8,8>>^ A terra abrangia a região montanhosa, as colinas do oeste, o vale do Jordão, as encostas dos montes, o deserto e o Neguebe. Nessa região viviam os hititas, os amorreus, os cananeus, os ferezeus, os heveus e os jebuseus. Estes são os reis que Israel derrotou:

[[v6-12-9]]

^<<v6-12-9,9>>^ O rei de Jericó, o rei de Ai, próxima a Betel,

[[v6-12-10]]

^<<v6-12-10,10>>^ o rei de Jerusalém, o rei de Hebrom,

[[v6-12-11]]

^<<v6-12-11,11>>^ o rei de Jarmute, o rei de Laquis,

[[v6-12-12]]

^<<v6-12-12,12>>^ o rei de Eglom, o rei de Gezer,

[[v6-12-13]]

^<<v6-12-13,13>>^ o rei de Debir, o rei de Geder,

[[v6-12-14]]

^<<v6-12-14,14>>^ o rei de Hormá, o rei de Arade,

[[v6-12-15]]

^<<v6-12-15,15>>^ o rei de Libna, o rei de Adulão,

[[v6-12-16]]

^<<v6-12-16,16>>^ o rei de Maquedá, o rei de Betel,

[[v6-12-17]]

^<<v6-12-17,17>>^ o rei de Tapua, o rei de Héfer,

[[v6-12-18]]

^<<v6-12-18,18>>^ o rei de Afeque, o rei de Lasarom,

[[v6-12-19]]

^<<v6-12-19,19>>^ o rei de Madom, o rei de Hazor,

[[v6-12-20]]

^<<v6-12-20,20>>^ o rei de Sinrom-Merom, o rei de Acsafe,

[[v6-12-21]]

^<<v6-12-21,21>>^ o rei de Taanaque, o rei de Megido,

[[v6-12-22]]

^<<v6-12-22,22>>^ o rei de Quedes, o rei de Jocneão, no Carmelo,

[[v6-12-23]]

^<<v6-12-23,23>>^ o rei de Dor, na cidade de Nafote-Dor, o rei de Goim, em Gilgal,

[[v6-12-24]]

^<<v6-12-24,24>>^ e o rei de Tirza. Ao todo, os israelitas derrotaram 31 reis.

'''

xref:006-josue/006-josue-011.adoc#v6-11-0[&#60; Capítulo Anterior] | <<v6-12-0,Topo>> | xref:006-josue/006-josue-013.adoc#v6-13-0[Próximo Capítulo &#62;]