include::./index.adoc[]

[[v6-3-0]]
=== Josué, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v6-3-1]]

^<<v6-3-1,1>>^ No dia seguinte, logo cedo, Josué e todos os israelitas partiram de Sitim e chegaram às margens do Jordão, onde acamparam antes de atravessar o rio.

[[v6-3-2]]

^<<v6-3-2,2>>^ Três dias depois, os oficiais percorreram o acampamento

[[v6-3-3]]

^<<v6-3-3,3>>^ e deram a seguinte ordem ao povo: "Quando virem a arca da aliança do SENHOR, seu Deus, sendo carregada pelos sacerdotes levitas, saiam de suas posições e sigam a arca.

[[v6-3-4]]

^<<v6-3-4,4>>^ Tenham o cuidado de ficar cerca de um quilômetro atrás dela. Não se aproximem demais! Assim vocês saberão por onde ir, pois nunca passaram por este caminho".

[[v6-3-5]]

^<<v6-3-5,5>>^ Então Josué disse ao povo: "Purifiquem-se, pois amanhã o SENHOR fará grandes maravilhas entre vocês!".

[[v6-3-6]]

^<<v6-3-6,6>>^ Pela manhã, Josué disse aos sacerdotes: "Levantem a arca da aliança e conduzam o povo para o outro lado do rio". Eles levantaram a arca da aliança e foram à frente do povo.

[[v6-3-7]]

^<<v6-3-7,7>>^ O SENHOR disse a Josué: "Hoje começarei a fazer de você um grande líder aos olhos de todo o Israel. Eles saberão que estou com você, assim como estive com Moisés.

[[v6-3-8]]

^<<v6-3-8,8>>^ Dê a seguinte ordem aos sacerdotes que carregam a arca da aliança: ‘Quando chegarem junto às margens do Jordão, parem exatamente ali’".

[[v6-3-9]]

^<<v6-3-9,9>>^ Então Josué disse aos israelitas: "Aproximem-se e ouçam o que diz o SENHOR, seu Deus.

[[v6-3-10]]

^<<v6-3-10,10>>^ Hoje vocês saberão que o Deus vivo está entre vocês. Ele certamente expulsará os cananeus, os hititas, os heveus, os ferezeus, os girgaseus, os amorreus e os jebuseus de diante de vocês.

[[v6-3-11]]

^<<v6-3-11,11>>^ Vejam, a arca da aliança, que pertence ao Soberano de toda a terra, os conduzirá para o outro lado do Jordão!

[[v6-3-12]]

^<<v6-3-12,12>>^ Escolham agora doze homens das tribos de Israel, um de cada tribo.

[[v6-3-13]]

^<<v6-3-13,13>>^ Os sacerdotes levarão a arca do SENHOR, o Soberano de toda a terra. Assim que seus pés tocarem as águas do Jordão, a correnteza será interrompida rio acima, e as águas se levantarão como um muro".

[[v6-3-14]]

^<<v6-3-14,14>>^ O povo deixou o acampamento para atravessar o Jordão, e os sacerdotes que levavam a arca da aliança foram à frente deles.

[[v6-3-15]]

^<<v6-3-15,15>>^ Era a estação da colheita, e o Jordão transbordava sobre as margens. Assim que os sacerdotes que levavam a arca puseram os pés na água junto às margens do rio,

[[v6-3-16]]

^<<v6-3-16,16>>^ a correnteza acima daquele ponto foi interrompida e começou a se acumular a uma grande distância de lá, perto da cidade chamada Adam, nos arredores de Zaretã. E a água abaixo daquele ponto correu para o mar Morto, até o leito do rio secar. Então todo o povo atravessou em frente da cidade de Jericó.

[[v6-3-17]]

^<<v6-3-17,17>>^ Os sacerdotes que levavam a arca da aliança do SENHOR ficaram parados no meio do leito do rio, em terra seca, enquanto o povo passava. Esperaram ali até que todo o Israel tivesse atravessado o Jordão em terra seca.

'''

xref:006-josue/006-josue-002.adoc#v6-2-0[&#60; Capítulo Anterior] | <<v6-3-0,Topo>> | xref:006-josue/006-josue-004.adoc#v6-4-0[Próximo Capítulo &#62;]