include::./index.adoc[]

[[v50-3-0]]
=== Filipenses, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v50-3-1]]

^<<v50-3-1,1>>^ Por fim, meus irmãos, alegrem-se no Senhor. Nunca me canso de dizer-lhes estas coisas, e o faço para protegê-los.

[[v50-3-2]]

^<<v50-3-2,2>>^ Cuidado com os cães, aqueles que praticam o mal, os mutiladores que exigem a circuncisão.

[[v50-3-3]]

^<<v50-3-3,3>>^ Pois nós, que adoramos por meio do Espírito de Deus, somos os verdadeiros circuncidados. Alegramo-nos no que Cristo Jesus fez por nós. Não colocamos nenhuma confiança nos esforços humanos,

[[v50-3-4]]

^<<v50-3-4,4>>^ ainda que, se outros pensam ter motivos para confiar nos próprios esforços, eu teria ainda mais!

[[v50-3-5]]

^<<v50-3-5,5>>^ Fui circuncidado com oito dias de vida. Sou israelita de nascimento, da tribo de Benjamim, um verdadeiro hebreu. Era membro dos fariseus, extremamente obediente à lei judaica.

[[v50-3-6]]

^<<v50-3-6,6>>^ Era tão zeloso que persegui a igreja. E, quanto à justiça, cumpria a lei com todo rigor.

[[v50-3-7]]

^<<v50-3-7,7>>^ Pensava que essas coisas eram valiosas, mas agora as considero insignificantes por causa de Cristo.

[[v50-3-8]]

^<<v50-3-8,8>>^ Sim, todas as outras coisas são insignificantes comparadas ao ganho inestimável de conhecer a Cristo Jesus, meu Senhor. Por causa dele, deixei de lado todas as coisas e as considero menos que lixo, a fim de poder ganhar a Cristo

[[v50-3-9]]

^<<v50-3-9,9>>^ e nele ser encontrado. Não conto mais com minha própria justiça, que vem da obediência à lei, mas sim com a justiça que vem pela fé em Cristo, pois é com base na fé que Deus nos declara justos.

[[v50-3-10]]

^<<v50-3-10,10>>^ Quero conhecer a Cristo e experimentar o grande poder que o ressuscitou. Quero sofrer com ele, participando de sua morte,

[[v50-3-11]]

^<<v50-3-11,11>>^ para, de alguma forma, alcançar a ressurreição dos mortos!

[[v50-3-12]]

^<<v50-3-12,12>>^ Não estou dizendo que já obtive tudo isso, que já alcancei a perfeição. Mas prossigo a fim de conquistar essa perfeição para a qual Cristo Jesus me conquistou.

[[v50-3-13]]

^<<v50-3-13,13>>^ Não, irmãos, não a alcancei, mas concentro todos os meus esforços nisto: esquecendo-me do passado e olhando para o que está adiante,

[[v50-3-14]]

^<<v50-3-14,14>>^ prossigo para o final da corrida, a fim de receber o prêmio celestial para o qual Deus nos chama em Cristo Jesus.

[[v50-3-15]]

^<<v50-3-15,15>>^ Todos nós que alcançamos a maturidade devemos concordar quanto a essas coisas. Se discordam em algum ponto, confio que Deus o esclarecerá para vocês.

[[v50-3-16]]

^<<v50-3-16,16>>^ Contudo, devemos prosseguir de maneira coerente com o que já alcançamos.

[[v50-3-17]]

^<<v50-3-17,17>>^ Irmãos, sejam meus imitadores e aprendam com aqueles que seguem nosso exemplo.

[[v50-3-18]]

^<<v50-3-18,18>>^ Pois, como lhes disse muitas vezes, e o digo novamente com lágrimas nos olhos, há muitos cuja conduta mostra que são, na verdade, inimigos da cruz de Cristo.

[[v50-3-19]]

^<<v50-3-19,19>>^ Estão rumando para a destruição. O deus deles é seu próprio apetite. Vangloriam-se de coisas vergonhosas e pensam apenas na vida terrena.

[[v50-3-20]]

^<<v50-3-20,20>>^ Nossa cidadania, no entanto, vem do céu, e de lá aguardamos ansiosamente a volta do Salvador, o Senhor Jesus Cristo.

[[v50-3-21]]

^<<v50-3-21,21>>^ Ele tomará nosso frágil corpo mortal e o transformará num corpo glorioso como o dele, usando o mesmo poder com o qual submeterá todas as coisas a seu domínio.

'''

xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[&#60; Capítulo Anterior] | <<v50-3-0,Topo>> | xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[Próximo Capítulo &#62;]