include::./index.adoc[]

[[v50-2-0]]
=== Filipenses, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v50-2-1]]

^<<v50-2-1,1>>^ Há alguma motivação por estar em Cristo? Há alguma consolação que vem do amor? Há alguma comunhão no Espírito? Há alguma compaixão e afeição?

[[v50-2-2]]

^<<v50-2-2,2>>^ Então completem minha alegria concordando sinceramente uns com os outros, amando-se mutuamente e trabalhando juntos com a mesma forma de pensar e um só propósito.

[[v50-2-3]]

^<<v50-2-3,3>>^ Não sejam egoístas, nem tentem impressionar ninguém. Sejam humildes e considerem os outros mais importantes que vocês.

[[v50-2-4]]

^<<v50-2-4,4>>^ Não procurem apenas os próprios interesses, mas preocupem-se também com os interesses alheios.

[[v50-2-5]]

^<<v50-2-5,5>>^ Tenham a mesma atitude demonstrada por Cristo Jesus.

[[v50-2-6]]

^<<v50-2-6,6>>^ Embora sendo Deus, não considerou que ser igual a Deus fosse algo a que devesse se apegar.

[[v50-2-7]]

^<<v50-2-7,7>>^ Em vez disso, esvaziou a si mesmo; assumiu a posição de escravo e nasceu como ser humano. Quando veio em forma humana,

[[v50-2-8]]

^<<v50-2-8,8>>^ humilhou-se e foi obediente até a morte, e morte de cruz.

[[v50-2-9]]

^<<v50-2-9,9>>^ Por isso Deus o elevou ao lugar de mais alta honra e lhe deu o nome que está acima de todos os nomes,

[[v50-2-10]]

^<<v50-2-10,10>>^ para que, ao nome de Jesus, todo joelho se dobre, nos céus, na terra e debaixo da terra,

[[v50-2-11]]

^<<v50-2-11,11>>^ e toda língua declare que Jesus Cristo é Senhor, para a glória de Deus, o Pai.

[[v50-2-12]]

^<<v50-2-12,12>>^ Quando eu estava aí, meus amados, vocês sempre seguiam minhas instruções. Agora que estou longe, é ainda mais importante que o façam. Trabalhem com afinco a sua salvação, obedecendo a Deus com reverência e temor.

[[v50-2-13]]

^<<v50-2-13,13>>^ Pois Deus está agindo em vocês, dando-lhes o desejo e o poder de realizarem aquilo que é do agrado dele.

[[v50-2-14]]

^<<v50-2-14,14>>^ Façam tudo sem queixas nem discussões,

[[v50-2-15]]

^<<v50-2-15,15>>^ de modo que ninguém possa acusá-los. Levem uma vida pura e inculpável como filhos de Deus, brilhando como luzes resplandecentes num mundo cheio de gente corrompida e perversa.

[[v50-2-16]]

^<<v50-2-16,16>>^ Apeguem-se firmemente à mensagem da vida. Então, no dia em que Cristo voltar, me orgulharei de saber que não participei da corrida em vão e que não trabalhei inutilmente.

[[v50-2-17]]

^<<v50-2-17,17>>^ Contudo, me alegrarei mesmo se perder a vida, entregando-a a Deus como oferta derramada, da mesma forma que o serviço fiel de vocês é uma oferta a Deus. E quero que todos vocês participem dessa alegria.

[[v50-2-18]]

^<<v50-2-18,18>>^ Sim, alegrem-se, e eu me alegrarei com vocês.

[[v50-2-19]]

^<<v50-2-19,19>>^ Se for da vontade do Senhor Jesus, espero enviar-lhes Timóteo em breve para visitá-los. Assim ele poderá me animar, contando-me notícias de vocês.

[[v50-2-20]]

^<<v50-2-20,20>>^ Não tenho ninguém que se preocupe sinceramente com o bem-estar de vocês como Timóteo.

[[v50-2-21]]

^<<v50-2-21,21>>^ Todos os outros se preocupam apenas consigo mesmos, e não com o que é importante para Jesus Cristo.

[[v50-2-22]]

^<<v50-2-22,22>>^ Mas vocês sabem que Timóteo provou seu valor. Como um filho junto ao pai, ele tem servido ao meu lado na proclamação das boas-novas.

[[v50-2-23]]

^<<v50-2-23,23>>^ Espero enviá-lo assim que souber o que me acontecerá aqui.

[[v50-2-24]]

^<<v50-2-24,24>>^ E tenho confiança no Senhor de que, em breve, eu mesmo irei vê-los.

[[v50-2-25]]

^<<v50-2-25,25>>^ Enquanto isso, penso que devo enviar-lhes de volta Epafrodito. Ele é um verdadeiro irmão, colaborador e companheiro de lutas, que também foi mensageiro de vocês para me ajudar em minha necessidade.

[[v50-2-26]]

^<<v50-2-26,26>>^ Ele deseja muito vê-los e está angustiado porque vocês souberam que ele esteve doente.

[[v50-2-27]]

^<<v50-2-27,27>>^ De fato, ficou enfermo e quase morreu. Mas Deus teve misericórdia dele, e também de mim, para que eu não tivesse uma tristeza atrás da outra.

[[v50-2-28]]

^<<v50-2-28,28>>^ Por isso, estou ainda mais ansioso para enviá-lo de volta, pois sei que vocês se alegrarão em vê-lo, e eu não ficarei tão preocupado com vocês.

[[v50-2-29]]

^<<v50-2-29,29>>^ Recebam-no com grande alegria no Senhor e deem-lhe a honra que ele merece,

[[v50-2-30]]

^<<v50-2-30,30>>^ pois arriscou a vida pela obra de Cristo e esteve a ponto de morrer enquanto fazia por mim o que vocês mesmos não podiam fazer.

'''

xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[Próximo Capítulo &#62;]