include::./index.adoc[]

[[v50-4-0]]
=== Filipenses, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v50-4-1]]

^<<v50-4-1,1>>^ Portanto, meus amados irmãos, permaneçam firmes no Senhor. Amo vocês e anseio vê-los, pois são minha alegria e minha coroa de recompensa.

[[v50-4-2]]

^<<v50-4-2,2>>^ Agora, suplico a Evódia e a Síntique: tendo em vista que estão no Senhor, resolvam seu desentendimento.

[[v50-4-3]]

^<<v50-4-3,3>>^ E peço a você, meu fiel colaborador, que ajude essas duas mulheres, pois elas trabalharam arduamente comigo na propagação das boas-novas, e também com Clemente e com meus outros colaboradores, cujos nomes estão escritos no livro da vida.

[[v50-4-4]]

^<<v50-4-4,4>>^ Alegrem-se sempre no Senhor. Repito: alegrem-se!

[[v50-4-5]]

^<<v50-4-5,5>>^ Que todos vejam que vocês são amáveis em tudo que fazem. Lembrem-se de que o Senhor virá em breve.

[[v50-4-6]]

^<<v50-4-6,6>>^ Não vivam preocupados com coisa alguma; em vez disso, orem a Deus pedindo aquilo de que precisam e agradecendo-lhe por tudo que ele já fez.

[[v50-4-7]]

^<<v50-4-7,7>>^ Então vocês experimentarão a paz de Deus, que excede todo entendimento e que guardará seu coração e sua mente em Cristo Jesus.

[[v50-4-8]]

^<<v50-4-8,8>>^ Por fim, irmãos, quero lhes dizer só mais uma coisa. Concentrem-se em tudo que é verdadeiro, tudo que é nobre, tudo que é correto, tudo que é puro, tudo que é amável e tudo que é admirável. Pensem no que é excelente e digno de louvor.

[[v50-4-9]]

^<<v50-4-9,9>>^ Continuem a praticar tudo que aprenderam e receberam de mim, tudo que ouviram de mim e me viram fazer. Então o Deus da paz estará com vocês.

[[v50-4-10]]

^<<v50-4-10,10>>^ Como eu me alegro no Senhor por vocês terem voltado a se preocupar comigo! Sei que sempre se preocuparam comigo, mas não tinham oportunidade de me ajudar.

[[v50-4-11]]

^<<v50-4-11,11>>^ Não digo isso por estar necessitado, pois aprendi a ficar satisfeito com o que tenho.

[[v50-4-12]]

^<<v50-4-12,12>>^ Sei viver na necessidade e também na fartura. Aprendi o segredo de viver em qualquer situação, de estômago cheio ou vazio, com pouco ou muito.

[[v50-4-13]]

^<<v50-4-13,13>>^ Posso todas as coisas por meio de Cristo, que me dá forças.

[[v50-4-14]]

^<<v50-4-14,14>>^ Mesmo assim, vocês fizeram bem em me ajudar na dificuldade pela qual estou passando.

[[v50-4-15]]

^<<v50-4-15,15>>^ Como sabem, filipenses, vocês foram os únicos que me ajudaram financeiramente quando lhes anunciei as boas-novas pela primeira vez e depois segui viagem saindo da Macedônia. Nenhuma outra igreja o fez.

[[v50-4-16]]

^<<v50-4-16,16>>^ Até quando eu estava em Tessalônica, vocês enviaram ajuda em mais de uma ocasião.

[[v50-4-17]]

^<<v50-4-17,17>>^ Não digo isso porque quero receber uma oferta de vocês. Pelo contrário, desejo que sejam recompensados por sua bondade.

[[v50-4-18]]

^<<v50-4-18,18>>^ No momento, tenho tudo de que preciso, e mais. Minhas necessidades foram plenamente supridas pelas contribuições que vocês enviaram por Epafrodito. Elas são um sacrifício de aroma suave, uma oferta aceitável e agradável a Deus.

[[v50-4-19]]

^<<v50-4-19,19>>^ E esse mesmo Deus que cuida de mim lhes suprirá todas as necessidades por meio das riquezas gloriosas que nos foram dadas em Cristo Jesus.

[[v50-4-20]]

^<<v50-4-20,20>>^ Agora, toda a glória seja a Deus, nosso Pai, para todo o sempre! Amém.

[[v50-4-21]]

^<<v50-4-21,21>>^ Transmitam minhas saudações a cada um do povo santo em Cristo Jesus. Os irmãos que estão comigo também mandam lembranças.

[[v50-4-22]]

^<<v50-4-22,22>>^ Todo o povo santo daqui lhes envia saudações, especialmente os que pertencem à casa de César.

[[v50-4-23]]

^<<v50-4-23,23>>^ Que a graça do Senhor Jesus Cristo seja com o espírito de vocês.

'''

xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[&#60; Capítulo Anterior] | <<v50-4-0,Topo>> | xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[Próximo Capítulo &#62;]