include::./index.adoc[]

[[v26-24-0]]
=== Ezequiel, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v26-24-1]]

^<<v26-24-1,1>>^ Em 15 de janeiro, durante o nono ano do exílio do rei Joaquim, recebi esta mensagem do SENHOR:

[[v26-24-2]]

^<<v26-24-2,2>>^ "Filho do homem, registre esta data, pois hoje o rei da Babilônia começou a atacar Jerusalém.

[[v26-24-3]]

^<<v26-24-3,3>>^ Depois, use uma ilustração para transmitir a esses rebeldes a seguinte mensagem do SENHOR Soberano: "Coloque uma panela no fogo e ponha água dentro dela.

[[v26-24-4]]

^<<v26-24-4,4>>^ Encha-a com os pedaços mais seletos de carne: a coxa, o quarto dianteiro e os cortes mais macios.

[[v26-24-5]]

^<<v26-24-5,5>>^ Use somente as melhores ovelhas do rebanho e amontoe lenha no fogo sob a panela. Faça a água ferver e cozinhe os ossos com a carne.

[[v26-24-6]]

^<<v26-24-6,6>>^ "Agora, assim diz o SENHOR Soberano: Que aflição espera Jerusalém, cidade de assassinos! Ela é a panela enferrujada, cuja sujeira não se pode limpar. Pegue a carne sem escolhê-la, pois nenhum pedaço é melhor que o outro.

[[v26-24-7]]

^<<v26-24-7,7>>^ Porque o sangue que ela derramou está espalhado sobre as pedras; nem sequer foi derramado no chão, onde o pó o cobriria.

[[v26-24-8]]

^<<v26-24-8,8>>^ Portanto, espalharei seu sangue numa pedra, para que todos vejam, uma expressão de minha ira e de minha vingança contra ela.

[[v26-24-9]]

^<<v26-24-9,9>>^ "Assim diz o SENHOR Soberano: Que aflição espera Jerusalém, cidade de assassinos; eu mesmo amontoarei a lenha debaixo dela!

[[v26-24-10]]

^<<v26-24-10,10>>^ Sim, amontoe a lenha; que ardam as chamas para fazer a panela ferver. Cozinhe a carne com diversos temperos, depois queime os ossos.

[[v26-24-11]]

^<<v26-24-11,11>>^ Agora, coloque a panela vazia sobre as brasas, esquente-a até ficar incandescente e queime a ferrugem e a sujeira.

[[v26-24-12]]

^<<v26-24-12,12>>^ Mas de nada adianta; não se pode limpar a ferrugem, nem mesmo com fogo.

[[v26-24-13]]

^<<v26-24-13,13>>^ Sua impureza é sua depravação; tentei limpá-la, mas você não quis. Portanto, agora ficará em sua impureza, até que eu tenha satisfeito minha fúria contra você.

[[v26-24-14]]

^<<v26-24-14,14>>^ "Eu, o SENHOR, falei! Chegou a hora, e não me conterei. Não mudarei de ideia nem terei compaixão. Você será julgada de acordo com suas ações, diz o SENHOR Soberano".

[[v26-24-15]]

^<<v26-24-15,15>>^ Recebi esta mensagem do SENHOR:

[[v26-24-16]]

^<<v26-24-16,16>>^ "Filho do homem, com um só golpe tirarei de você seu tesouro mais precioso. Contudo, você não deve mostrar tristeza alguma com a morte dela. Não chore, não derrame lágrimas.

[[v26-24-17]]

^<<v26-24-17,17>>^ Sofra em silêncio, mas não lamente junto ao túmulo. Não descubra a cabeça nem tire as sandálias. Não siga os rituais de luto nem aceite comida de amigos que vierem consolá-lo".

[[v26-24-18]]

^<<v26-24-18,18>>^ Pela manhã, anunciei essa mensagem ao povo e, à tarde, minha esposa morreu. No dia seguinte, fiz tudo que me havia sido ordenado.

[[v26-24-19]]

^<<v26-24-19,19>>^ Então o povo perguntou: "O que significa tudo isso? O que você quer nos dizer?".

[[v26-24-20]]

^<<v26-24-20,20>>^ Eu respondi: "Recebi uma mensagem do Senhor

[[v26-24-21]]

^<<v26-24-21,21>>^ e fui instruído a transmiti-la ao povo de Israel. Assim diz o SENHOR Soberano: ‘Profanarei meu templo, a fonte de sua segurança e seu orgulho, o lugar que lhes dá prazer ao coração. Seus filhos e filhas, que vocês deixaram para trás, serão mortos à espada.

[[v26-24-22]]

^<<v26-24-22,22>>^ Então vocês farão como Ezequiel. Não seguirão os rituais de luto nem se consolarão com comida trazida pelos amigos.

[[v26-24-23]]

^<<v26-24-23,23>>^ Sua cabeça permanecerá coberta, e não tirarão as sandálias. Não prantearão nem chorarão, mas definharão por causa de seus pecados. Lamentarão uns com os outros por todo o mal que fizeram.

[[v26-24-24]]

^<<v26-24-24,24>>^ Ezequiel lhes serve de exemplo; farão exatamente o que ele fez. E, quando esse dia chegar, saberão que eu sou o SENHOR Soberano’".

[[v26-24-25]]

^<<v26-24-25,25>>^ Então o SENHOR me disse: "Filho do homem, no dia em que eu tirar deles sua fortaleza — sua alegria e sua glória, o desejo de seu coração e seu tesouro mais precioso —, também tirarei deles seus filhos e filhas.

[[v26-24-26]]

^<<v26-24-26,26>>^ Nesse dia, um sobrevivente de Jerusalém virá ao seu encontro na Babilônia e lhe contará o que aconteceu.

[[v26-24-27]]

^<<v26-24-27,27>>^ Quando ele chegar, você recuperará sua voz para que possa falar com ele, e isso será um sinal para o povo. Então eles saberão que eu sou o SENHOR".

'''

xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]