include::./index.adoc[]

[[v26-7-0]]
=== Ezequiel, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v26-7-1]]

^<<v26-7-1,1>>^ Então recebi esta mensagem do SENHOR:

[[v26-7-2]]

^<<v26-7-2,2>>^ "Filho do homem, assim diz o SENHOR Soberano a Israel: "Chegou o fim! Para onde quer que vocês olhem, norte, sul, leste ou oeste, sua terra está acabada.

[[v26-7-3]]

^<<v26-7-3,3>>^ Não resta esperança, pois lançarei minha ira contra vocês. Eu os chamarei para prestar contas de todos os seus pecados detestáveis.

[[v26-7-4]]

^<<v26-7-4,4>>^ Não os pouparei nem terei piedade; darei a vocês o que merecem por todos os seus pecados detestáveis. Então saberão que eu sou o SENHOR.

[[v26-7-5]]

^<<v26-7-5,5>>^ "Assim diz o SENHOR Soberano: Desgraça após desgraça se aproximam!

[[v26-7-6]]

^<<v26-7-6,6>>^ Chegou o fim, finalmente chegou; sua condenação os espera!

[[v26-7-7]]

^<<v26-7-7,7>>^ Ó povo de Israel, já amanhece o dia de sua destruição; chegou a hora, o tempo da aflição está próximo. Nos montes se ouvem gritos de angústia, e não de alegria.

[[v26-7-8]]

^<<v26-7-8,8>>^ Em breve derramarei sobre vocês minha fúria e contra vocês lançarei minha ira. Eu os chamarei para prestar contas de todos os seus pecados detestáveis.

[[v26-7-9]]

^<<v26-7-9,9>>^ Não os pouparei nem terei piedade; darei a vocês o que merecem por todos os seus pecados detestáveis. Então saberão que eu, o SENHOR, os feri.

[[v26-7-10]]

^<<v26-7-10,10>>^ "O dia do juízo chegou; sua destruição os espera! A vara da perversidade brotou, sim, o orgulho do povo floresceu.

[[v26-7-11]]

^<<v26-7-11,11>>^ Sua violência se transformou numa vara que os castigará por sua maldade. Nenhum dos orgulhosos sobreviverá; toda a sua riqueza e prestígio desaparecerão.

[[v26-7-12]]

^<<v26-7-12,12>>^ Sim, chegou a hora; este é o dia! Que os compradores não se alegrem, nem os vendedores se entristeçam, pois todos eles cairão sob a minha ira ardente.

[[v26-7-13]]

^<<v26-7-13,13>>^ Ainda que os comerciantes sobrevivam, jamais voltarão a seus negócios. Pois a profecia contra o povo não mudará. Ninguém cuja vida é corrompida pelo pecado se recuperará."

[[v26-7-14]]

^<<v26-7-14,14>>^ "A trombeta convoca o exército, mas ninguém sai para guerrear, pois minha fúria está contra todos eles.

[[v26-7-15]]

^<<v26-7-15,15>>^ Fora da cidade há guerra, dentro dela, doença e fome. Quem estiver fora dos muros será morto pela espada do inimigo. Quem estiver dentro da cidade morrerá de fome e doença.

[[v26-7-16]]

^<<v26-7-16,16>>^ Os sobreviventes que fugirem para os montes gemerão como pombas, por causa de seus pecados.

[[v26-7-17]]

^<<v26-7-17,17>>^ Suas mãos ficarão fracas, e seus joelhos, frouxos como água.

[[v26-7-18]]

^<<v26-7-18,18>>^ De pano de saco se vestirão e ficarão cobertos de horror. Rasparão a cabeça, em sinal de tristeza e remorso.

[[v26-7-19]]

^<<v26-7-19,19>>^ "Jogarão seu dinheiro na rua, o lançarão fora como se fosse lixo. Seu ouro e sua prata não os salvarão no dia da ira do SENHOR. Não os saciarão nem os alimentarão, pois sua ganância só os faz tropeçar.

[[v26-7-20]]

^<<v26-7-20,20>>^ Tinham orgulho de suas lindas joias e com elas fizeram ídolos detestáveis e imagens repugnantes. Por isso farei que todas as suas riquezas se tornem repulsivas para eles

[[v26-7-21]]

^<<v26-7-21,21>>^ e as entregarei como despojo a estrangeiros, às nações perversas, e elas as profanarão.

[[v26-7-22]]

^<<v26-7-22,22>>^ Desviarei deles meu olhar quando ladrões invadirem e profanarem minha terra preciosa.

[[v26-7-23]]

^<<v26-7-23,23>>^ "Preparem correntes para meu povo, pois o sangue de crimes terríveis cobre a terra; Jerusalém está cheia de violência.

[[v26-7-24]]

^<<v26-7-24,24>>^ Trarei as nações mais cruéis para ocuparem suas casas. Acabarei com o orgulho dos poderosos e profanarei seus santuários.

[[v26-7-25]]

^<<v26-7-25,25>>^ O terror tomará conta do povo; buscarão a paz, mas não a encontrarão.

[[v26-7-26]]

^<<v26-7-26,26>>^ Virá uma calamidade após a outra, um rumor após o outro. Buscarão sem sucesso uma visão dos profetas. Não receberão ensinamentos dos sacerdotes nem conselhos das autoridades.

[[v26-7-27]]

^<<v26-7-27,27>>^ O rei e o príncipe ficarão desamparados e chorarão de desespero; as mãos do povo tremerão de medo. Trarei sobre eles o mal que fizeram a outros, e receberão o castigo que tanto merecem. Então saberão que eu sou o SENHOR".

'''

xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[&#60; Capítulo Anterior] | <<v26-7-0,Topo>> | xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[Próximo Capítulo &#62;]