include::./index.adoc[]

[[v26-27-0]]
=== Ezequiel, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v26-27-1]]

^<<v26-27-1,1>>^ Recebi esta mensagem do SENHOR:

[[v26-27-2]]

^<<v26-27-2,2>>^ "Filho do homem, entoe um cântico fúnebre para Tiro,

[[v26-27-3]]

^<<v26-27-3,3>>^ essa cidade que é entrada para o mar, que estabelece relações comerciais com muitas nações. Transmita-lhe a seguinte mensagem do SENHOR Soberano: "Ó cidade de Tiro, você se gloriava: ‘Minha beleza é perfeita!’.

[[v26-27-4]]

^<<v26-27-4,4>>^ Estendeu seus limites para o mar; seus construtores aperfeiçoaram sua beleza.

[[v26-27-5]]

^<<v26-27-5,5>>^ Você era como uma grande embarcação, construída com os melhores ciprestes de Senir. Com um cedro do Líbano fabricaram seu mastro.

[[v26-27-6]]

^<<v26-27-6,6>>^ Fizeram seus remos com carvalhos de Basã. Seu convés de pinho dos litorais de Chipre era decorado com marfim.

[[v26-27-7]]

^<<v26-27-7,7>>^ Suas velas eram de linho egípcio da melhor qualidade e esvoaçavam sobre você como uma bandeira. Seus toldos eram azuis e vermelhos, coloridos com tinturas dos litorais de Elisá.

[[v26-27-8]]

^<<v26-27-8,8>>^ Seus remadores eram de Sidom e Arvade, seus timoneiros, homens habilidosos de Tiro.

[[v26-27-9]]

^<<v26-27-9,9>>^ Antigos e sábios artesãos de Gebal calafetaram a embarcação. Navios de todas as nações vinham com mercadorias para negociar com você.

[[v26-27-10]]

^<<v26-27-10,10>>^ "Homens das terras distantes da Pérsia, de Lídia e da Líbia serviam em seu grande exército. Penduravam os escudos e os capacetes em seus muros e assim lhe davam muita honra.

[[v26-27-11]]

^<<v26-27-11,11>>^ Homens de Arvade e de Heleque montavam guarda no alto de seus muros, e em suas torres ficavam homens de Gamade. Os escudos deles, pendurados em seus muros, completavam sua beleza.

[[v26-27-12]]

^<<v26-27-12,12>>^ "Társis enviava negociantes para comprar sua grande variedade de mercadorias em troca de prata, ferro, estanho e chumbo,

[[v26-27-13]]

^<<v26-27-13,13>>^ e comerciantes da Grécia, de Tubal e de Meseque traziam escravos e artigos de bronze para negociar com você.

[[v26-27-14]]

^<<v26-27-14,14>>^ "De Bete-Togarma vinham cavalos de montaria, cavalos para carros de guerra e mulas para serem negociados por suas mercadorias,

[[v26-27-15]]

^<<v26-27-15,15>>^ e comerciantes vinham de Dedã. Você tinha o monopólio do mercado de várias regiões litorâneas, que lhe pagavam com presas de marfim e madeira de ébano.

[[v26-27-16]]

^<<v26-27-16,16>>^ "A Síria enviava negociantes para comprar sua grande variedade de mercadorias, e em troca lhe dava turquesa, tinturas vermelhas, bordados, linho fino e joias de coral e de rubis.

[[v26-27-17]]

^<<v26-27-17,17>>^ Judá e Israel faziam comércio com você e pagavam com trigo de Minite, figos, mel, azeite e bálsamo.

[[v26-27-18]]

^<<v26-27-18,18>>^ "Damasco enviava negociantes para comprar sua grande variedade de mercadorias, e em troca lhe dava vinho de Helbom e lã de Zaar.

[[v26-27-19]]

^<<v26-27-19,19>>^ Gregos de Uzal vinham negociar suas mercadorias, e em troca traziam ferro trabalhado, cássia e cálamo perfumado.

[[v26-27-20]]

^<<v26-27-20,20>>^ "Dedã enviava negociantes para comercializar com você seus valiosos mantos para selas.

[[v26-27-21]]

^<<v26-27-21,21>>^ Os árabes e os príncipes de Quedar enviavam comerciantes para negociar com você e pagavam com cordeiros, carneiros e bodes.

[[v26-27-22]]

^<<v26-27-22,22>>^ Negociantes de Sabá e de Ramá lhe davam especiarias de todo tipo, joias e ouro em troca de suas mercadorias.

[[v26-27-23]]

^<<v26-27-23,23>>^ "Harã, Cane, Éden, Sabá, Assur e Quilmade também vinham com seus negociantes.

[[v26-27-24]]

^<<v26-27-24,24>>^ Traziam tecidos da melhor qualidade para comercializar: tecido azul, bordados e tapetes multicoloridos enrolados e amarrados com cordões.

[[v26-27-25]]

^<<v26-27-25,25>>^ Os navios de Társis eram suas caravanas marítimas. Os depósitos em sua ilha viviam abarrotados!"

[[v26-27-26]]

^<<v26-27-26,26>>^ "Mas veja! Seus remadores a levaram para águas tempestuosas! Um poderoso vento do leste a despedaçou no coração do mar.

[[v26-27-27]]

^<<v26-27-27,27>>^ Tudo se perdeu: riquezas e mercadorias, marinheiros e pilotos, construtores de navios, negociantes e guerreiros. No dia de sua ruína, todos a bordo afundam até as profundezas do mar.

[[v26-27-28]]

^<<v26-27-28,28>>^ Suas cidades no litoral tremem, seus pilotos gritam de pavor.

[[v26-27-29]]

^<<v26-27-29,29>>^ Todos os remadores abandonam os navios, os marinheiros e os pilotos ficam na praia.

[[v26-27-30]]

^<<v26-27-30,30>>^ Gritam por você e choram amargamente. Jogam pó sobre a cabeça e rolam em cinzas.

[[v26-27-31]]

^<<v26-27-31,31>>^ Por sua causa raspam a cabeça e se vestem de pano de saco. Choram com amarga angústia e profunda lamentação.

[[v26-27-32]]

^<<v26-27-32,32>>^ Enquanto lamentam e choram por você, entoam este triste cântico fúnebre: ‘Acaso houve alguma cidade como Tiro, que agora está em silêncio no fundo do mar?

[[v26-27-33]]

^<<v26-27-33,33>>^ As mercadorias que você negociava pelos mares satisfaziam os desejos de muitas nações. Reis nos confins da terra se enriqueceram com seu comércio.

[[v26-27-34]]

^<<v26-27-34,34>>^ Agora você é um navio naufragado e quebrado no fundo do mar. Suas mercadorias e seus tripulantes afundaram com você.

[[v26-27-35]]

^<<v26-27-35,35>>^ Todos que moram no litoral estão espantados com seu terrível destino. Os reis estão horrorizados e olham com expressão perturbada.

[[v26-27-36]]

^<<v26-27-36,36>>^ Os comerciantes entre as nações balançam a cabeça quando a veem, pois você chegou a um terrível fim e não mais existirá’".

'''

xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[&#60; Capítulo Anterior] | <<v26-27-0,Topo>> | xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[Próximo Capítulo &#62;]