include::./index.adoc[]

[[v26-41-0]]
=== Ezequiel, 41
// nvt ?, NVT - Nova Versão Transformadora

[[v26-41-1]]

^<<v26-41-1,1>>^ Depois disso, o homem me levou ao santuário do templo. Mediu as paredes de cada lado de sua porta, e tinham 3 metros de espessura.

[[v26-41-2]]

^<<v26-41-2,2>>^ A entrada tinha 5 metros de largura, e as paredes de cada lado tinham 2,5 metros de comprimento. O santuário propriamente dito tinha 20 metros de comprimento e 10 metros de largura.

[[v26-41-3]]

^<<v26-41-3,3>>^ Então ele passou do santuário para a sala interna. Mediu as paredes de cada lado de sua entrada, e tinham 1 metro de espessura. A entrada tinha 3 metros de largura, e as paredes de cada lado da entrada tinham 3,5 metros de comprimento.

[[v26-41-4]]

^<<v26-41-4,4>>^ A sala interna do santuário tinha 10 metros de comprimento e 10 metros de largura. Ele me disse: "Este é o lugar santíssimo".

[[v26-41-5]]

^<<v26-41-5,5>>^ Então ele mediu a parede do templo, e tinha 3 metros de espessura. Junto à parte externa da parede havia uma fileira de salas; cada sala tinha 2 metros de largura.

[[v26-41-6]]

^<<v26-41-6,6>>^ Essas salas laterais ficavam em três andares, uma acima da outra, e havia trinta salas em cada andar. Os pontos de sustentação das salas laterais ficavam apoiados em saliências externas na parede do templo; não se estendiam para dentro da parede.

[[v26-41-7]]

^<<v26-41-7,7>>^ Cada andar era mais largo que o andar abaixo, acompanhando a inclinação da parede do templo. Uma escada subia do andar inferior para os andares do meio e de cima.

[[v26-41-8]]

^<<v26-41-8,8>>^ Vi que o templo era construído sobre uma plataforma que servia de base para as salas laterais. Essa plataforma tinha 3 metros de altura.

[[v26-41-9]]

^<<v26-41-9,9>>^ A parede externa das salas laterais do templo tinha 2,5 metros espessura. Havia, portanto, uma área aberta entre essas salas laterais

[[v26-41-10]]

^<<v26-41-10,10>>^ e a fileira de salas junto à parede externa do pátio interno. Essa área aberta tinha 10 metros de largura e se estendia ao redor de todo o templo.

[[v26-41-11]]

^<<v26-41-11,11>>^ Duas portas nas salas laterais davam para a área aberta da plataforma, que tinha 2,5 metros de largura. Uma porta ficava voltada para o norte, e a outra, para o sul.

[[v26-41-12]]

^<<v26-41-12,12>>^ Havia um edifício grande a oeste, voltado para o pátio do templo. Tinha 35 metros de largura e 45 metros de comprimento, e suas paredes tinham 2,5 metros de espessura.

[[v26-41-13]]

^<<v26-41-13,13>>^ Então o homem mediu o templo, e tinha 50 metros de comprimento. O pátio ao redor do edifício, incluindo suas paredes, tinha mais 50 metros de comprimento.

[[v26-41-14]]

^<<v26-41-14,14>>^ O pátio interno do lado leste do templo tinha 50 metros de largura.

[[v26-41-15]]

^<<v26-41-15,15>>^ O edifício a oeste, incluindo suas duas paredes, também tinha 50 metros de largura. O santuário, a sala interna e o pórtico do templo

[[v26-41-16]]

^<<v26-41-16,16>>^ eram todos revestidos de madeira, assim como as armações das janelas embutidas. As paredes internas eram revestidas de madeira acima e abaixo das janelas.

[[v26-41-17]]

^<<v26-41-17,17>>^ O espaço acima da porta que dava para a sala interna e suas paredes internas e externas também eram revestidos de madeira.

[[v26-41-18]]

^<<v26-41-18,18>>^ Todas as paredes eram enfeitadas com entalhes de querubins, cada um com dois rostos, alternados com entalhes de palmeiras.

[[v26-41-19]]

^<<v26-41-19,19>>^ Um dos rostos do querubim, o rosto de homem, ficava voltado para a palmeira de um lado. O outro rosto, o de leão forte, ficava voltado para a palmeira do outro lado. Havia figuras entalhadas ao redor de todo o templo,

[[v26-41-20]]

^<<v26-41-20,20>>^ desde o chão até o alto das paredes, inclusive na parede externa do santuário.

[[v26-41-21]]

^<<v26-41-21,21>>^ Na entrada do santuário havia colunas quadradas, e as colunas na entrada do lugar santíssimo eram semelhantes.

[[v26-41-22]]

^<<v26-41-22,22>>^ Havia um altar de madeira com 1,5 metros de altura e 1 metro de cada lado. Seus cantos, sua base e seus lados eram de madeira. O homem me disse: "Esta é a mesa que fica na presença do SENHOR".

[[v26-41-23]]

^<<v26-41-23,23>>^ Tanto o santuário como o lugar santíssimo tinham portas duplas,

[[v26-41-24]]

^<<v26-41-24,24>>^ cada uma com duas folhas que se abriam para os dois lados.

[[v26-41-25]]

^<<v26-41-25,25>>^ As portas que davam para o santuário eram enfeitadas com entalhes de querubins e de palmeiras, assim como as paredes. E havia uma cobertura de madeira na frente do pórtico do templo.

[[v26-41-26]]

^<<v26-41-26,26>>^ Dos dois lados do pórtico havia janelas embutidas enfeitadas com entalhes de palmeiras. As salas laterais junto à parede externa também tinham coberturas.

'''

xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[&#60; Capítulo Anterior] | <<v26-41-0,Topo>> | xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[Próximo Capítulo &#62;]