include::./index.adoc[]

[[v26-36-0]]
=== Ezequiel, 36
// nvt ?, NVT - Nova Versão Transformadora

[[v26-36-1]]

^<<v26-36-1,1>>^ "Filho do homem, profetize aos montes de Israel e transmita-lhes esta mensagem: Ó montes de Israel, ouçam a palavra do SENHOR!

[[v26-36-2]]

^<<v26-36-2,2>>^ Assim diz o SENHOR Soberano: Seus inimigos zombaram de vocês, dizendo: ‘Bem feito! Agora as antigas montanhas são nossas!’.

[[v26-36-3]]

^<<v26-36-3,3>>^ Por isso, transmita aos montes de Israel esta mensagem do SENHOR Soberano: Seus inimigos o atacaram de todos os lados e o tornaram propriedade de muitas nações e objeto de muita zombaria e calúnia.

[[v26-36-4]]

^<<v26-36-4,4>>^ Portanto, ó montes de Israel, ouçam a palavra do SENHOR Soberano. Ele fala às colinas e aos montes, aos desfiladeiros e aos vales, às ruínas arrasadas e às cidades desertas, destruídas e ridicularizadas pelas nações vizinhas.

[[v26-36-5]]

^<<v26-36-5,5>>^ Assim diz o SENHOR Soberano: A ira de meu zelo arde contra essas nações, especialmente contra Edom, porque me desprezaram completamente, se apossaram de minha terra com satisfação e a tomaram como despojo.

[[v26-36-6]]

^<<v26-36-6,6>>^ "Portanto, profetize às colinas e aos montes, aos desfiladeiros e aos vales de Israel. Assim diz o SENHOR Soberano: Estou furioso em meu zelo porque vocês passaram vergonha diante das nações vizinhas.

[[v26-36-7]]

^<<v26-36-7,7>>^ Portanto, assim diz o SENHOR Soberano: Jurei solenemente que essas nações logo passarão vergonha também.

[[v26-36-8]]

^<<v26-36-8,8>>^ "Os montes de Israel, no entanto, produzirão colheitas fartas de frutos para meu povo, pois em breve ele voltará para casa!

[[v26-36-9]]

^<<v26-36-9,9>>^ Pois estou com vocês e lhes darei atenção. Seu solo será arado, e suas lavouras serão plantadas.

[[v26-36-10]]

^<<v26-36-10,10>>^ Multiplicarei a população de Israel, e as cidades arruinadas serão reconstruídas e ficarão cheias de gente.

[[v26-36-11]]

^<<v26-36-11,11>>^ Multiplicarei tanto as pessoas como os animais. Ó montes de Israel, trarei gente para habitá-los outra vez! Eu os tornarei ainda mais prósperos que antes. Então vocês saberão que eu sou o SENHOR.

[[v26-36-12]]

^<<v26-36-12,12>>^ Farei meu povo andar sobre vocês novamente, e serão território dele. Vocês nunca mais o deixarão sem filhos.

[[v26-36-13]]

^<<v26-36-13,13>>^ "Assim diz o SENHOR Soberano: As outras nações zombam de você e dizem: ‘É uma terra que devora seu povo e os deixa sem filhos!’.

[[v26-36-14]]

^<<v26-36-14,14>>^ Mas você nunca mais devorará seu povo nem o deixará sem filhos, diz o SENHOR Soberano.

[[v26-36-15]]

^<<v26-36-15,15>>^ Não o deixarei ouvir os insultos de outras nações, nem sua zombaria. Você não será uma terra que faz sua nação cair, diz o SENHOR Soberano".

[[v26-36-16]]

^<<v26-36-16,16>>^ Então recebi esta mensagem do SENHOR:

[[v26-36-17]]

^<<v26-36-17,17>>^ "Filho do homem, quando os israelitas viviam em sua própria terra, eles a profanaram com seu estilo de vida. Para mim, sua conduta foi tão impura como o fluxo menstrual de uma mulher.

[[v26-36-18]]

^<<v26-36-18,18>>^ Eles contaminaram a terra com assassinato e adoração a ídolos, por isso derramei sobre eles minha fúria.

[[v26-36-19]]

^<<v26-36-19,19>>^ Eu os espalhei entre as nações para castigá-los por sua conduta.

[[v26-36-20]]

^<<v26-36-20,20>>^ Quando, porém, foram espalhados entre as nações, desonraram meu santo nome. Pois as nações diziam: ‘Este é o povo do SENHOR, mas ele não foi capaz de mantê-lo a salvo em sua própria terra!’.

[[v26-36-21]]

^<<v26-36-21,21>>^ Tive consideração por meu santo nome, que meu povo desonrou entre as nações.

[[v26-36-22]]

^<<v26-36-22,22>>^ "Portanto, transmita ao povo de Israel esta mensagem do SENHOR Soberano: Eu os trarei de volta, ó povo de Israel, mas não porque merecem. Farei isso por causa do meu santo nome, que vocês desonraram entre as nações.

[[v26-36-23]]

^<<v26-36-23,23>>^ Eu lhes mostrarei a santidade de meu grande nome, o nome que vocês desonraram entre as nações. E, quando eu mostrar minha santidade por meio de vocês diante das nações, diz o SENHOR, elas saberão que eu sou o SENHOR.

[[v26-36-24]]

^<<v26-36-24,24>>^ Pois eu os reunirei dentre as nações e os trarei de volta para sua terra.

[[v26-36-25]]

^<<v26-36-25,25>>^ "Então aspergirei sobre vocês água pura, e ficarão limpos. Eu os purificarei de sua impureza e sua adoração a ídolos.

[[v26-36-26]]

^<<v26-36-26,26>>^ Eu lhes darei um novo coração e colocarei em vocês um novo espírito. Removerei seu coração de pedra e lhes darei coração de carne.

[[v26-36-27]]

^<<v26-36-27,27>>^ Porei dentro de vocês meu Espírito, para que sigam meus decretos e tenham o cuidado de obedecer a meus estatutos.

[[v26-36-28]]

^<<v26-36-28,28>>^ "Vocês habitarão em Israel, a terra que dei a seus antepassados. Vocês serão o meu povo, e eu serei o seu Deus.

[[v26-36-29]]

^<<v26-36-29,29>>^ Eu os livrarei de sua impureza. Aumentarei a produção de cereais e não enviarei mais fome à terra.

[[v26-36-30]]

^<<v26-36-30,30>>^ Darei colheitas fartas de suas árvores frutíferas e seus campos, e nunca mais as nações vizinhas zombarão de sua terra por causa da fome.

[[v26-36-31]]

^<<v26-36-31,31>>^ Então se lembrarão dos pecados que cometeram no passado e terão aversão de si mesmos por todas as coisas detestáveis que fizeram.

[[v26-36-32]]

^<<v26-36-32,32>>^ Mas assim diz o SENHOR Soberano: Lembrem-se de que não farei tudo isso porque vocês merecem. Ó meu povo de Israel, vocês deveriam se envergonhar profundamente de tudo que fizeram!

[[v26-36-33]]

^<<v26-36-33,33>>^ "Assim diz o SENHOR Soberano: Quando eu os purificar de seus pecados, farei que suas cidades voltem a ser habitadas e as ruínas sejam reconstruídas.

[[v26-36-34]]

^<<v26-36-34,34>>^ Os campos que estavam vazios e desolados à vista de todos voltarão a ser cultivados.

[[v26-36-35]]

^<<v26-36-35,35>>^ E, quando eu trouxer vocês de volta, as pessoas dirão: ‘Essa terra que antes era deserta agora é como o jardim do Éden! As cidades abandonadas e em ruínas agora têm muros fortes e estão cheias de gente!’.

[[v26-36-36]]

^<<v26-36-36,36>>^ Com isso, as nações vizinhas que restarem saberão que eu, o SENHOR, reconstruí as ruínas e replantei onde estava deserto. Pois eu, o SENHOR, falei e cumprirei o que prometi.

[[v26-36-37]]

^<<v26-36-37,37>>^ "Assim diz o SENHOR Soberano: Estou disposto a ouvir as orações de Israel e a multiplicar seu povo como um rebanho.

[[v26-36-38]]

^<<v26-36-38,38>>^ Serão numerosos como os rebanhos consagrados que enchem as ruas de Jerusalém na época de suas festas. As cidades que estavam em ruínas voltarão a ficar cheias de gente, e todos saberão que eu sou o SENHOR".

'''

xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[&#60; Capítulo Anterior] | <<v26-36-0,Topo>> | xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[Próximo Capítulo &#62;]