include::./index.adoc[]

[[v26-21-0]]
=== Ezequiel, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v26-21-1]]

^<<v26-21-1,1>>^ Recebi esta mensagem do SENHOR:

[[v26-21-2]]

^<<v26-21-2,2>>^ "Filho do homem, volte o rosto para Jerusalém e profetize contra Israel e seus santuários.

[[v26-21-3]]

^<<v26-21-3,3>>^ Diga-lhe: ‘Assim diz o SENHOR: Sou seu inimigo, ó Israel, e estou prestes a tirar a espada da bainha para destruir seu povo, tanto os justos como os perversos.

[[v26-21-4]]

^<<v26-21-4,4>>^ Sim, eliminarei tanto os justos como os perversos! Empunharei minha espada contra todos na terra, desde o sul até o norte.

[[v26-21-5]]

^<<v26-21-5,5>>^ O mundo inteiro saberá que eu sou o SENHOR. A espada está em minha mão, e ela não voltará à bainha’.

[[v26-21-6]]

^<<v26-21-6,6>>^ "Filho do homem, comece a gemer! Comece a gemer diante do povo com amargura e coração quebrantado.

[[v26-21-7]]

^<<v26-21-7,7>>^ Quando lhe perguntarem por que você está gemendo, diga-lhes: ‘Estou gemendo por causa da notícia que recebi. Quando ela se realizar, até mesmo o coração mais valente se derreterá de medo; toda a força desaparecerá. Todo espírito se angustiará; joelhos fortes se tornarão frouxos como água. E o SENHOR Soberano diz: Ela está vindo! Está a caminho!’".

[[v26-21-8]]

^<<v26-21-8,8>>^ Em seguida, o SENHOR me disse:

[[v26-21-9]]

^<<v26-21-9,9>>^ "Filho do homem, transmita ao povo esta mensagem do Senhor: "Uma espada, uma espada está sendo afiada e polida.

[[v26-21-10]]

^<<v26-21-10,10>>^ Está sendo afiada para a matança e polida para faiscar como relâmpago. Agora nos alegraremos com o cetro de meu filho, o governante de Judá? A espada despreza qualquer pedaço de madeira!

[[v26-21-11]]

^<<v26-21-11,11>>^ Sim, a espada está sendo afiada e polida, preparada para as mãos do carrasco.

[[v26-21-12]]

^<<v26-21-12,12>>^ "Filho do homem, grite e lamente-se, bata nas coxas em sinal de angústia, pois a espada matará meu povo e seus líderes; todos morrerão!

[[v26-21-13]]

^<<v26-21-13,13>>^ Ela porá todos eles à prova; e o que acontecerá quando o cetro, que a espada despreza, não mais existir?, diz o SENHOR Soberano.

[[v26-21-14]]

^<<v26-21-14,14>>^ "Filho do homem, profetize para eles e bata palmas. Depois, pegue a espada e golpeie duas vezes, ou mesmo três vezes, para simbolizar a matança, a grande matança que os ameaça de todos os lados.

[[v26-21-15]]

^<<v26-21-15,15>>^ Que o coração deles se derreta de terror, pois a espada reluz em todas as portas. Faísca como relâmpago e está polida para a matança.

[[v26-21-16]]

^<<v26-21-16,16>>^ Ó espada, golpeie à direita, golpeie à esquerda, para onde se virar e onde quiser.

[[v26-21-17]]

^<<v26-21-17,17>>^ Eu também baterei palmas e satisfarei minha fúria. Eu, o SENHOR, falei!".

[[v26-21-18]]

^<<v26-21-18,18>>^ Recebi esta mensagem do SENHOR:

[[v26-21-19]]

^<<v26-21-19,19>>^ "Filho do homem, desenhe um mapa e sobre ele trace dois caminhos para que a espada do rei da Babilônia os siga. Coloque um marco na estrada que sai da Babilônia, onde ela se divide em dois caminhos,

[[v26-21-20]]

^<<v26-21-20,20>>^ um para Amom e sua capital, Rabá, e outro para Judá e Jerusalém, a cidade fortificada.

[[v26-21-21]]

^<<v26-21-21,21>>^ O rei da Babilônia está na encruzilhada, sem saber se deve atacar Jerusalém ou Rabá. Ele chama seus adivinhos para que façam previsões, e eles lançam sortes com flechas sacudidas da aljava, consultam seus ídolos e examinam o fígado de animais sacrificados.

[[v26-21-22]]

^<<v26-21-22,22>>^ O presságio em sua mão direita indica ‘Jerusalém!’. Seus soldados atacarão as portas da cidade com troncos e darão gritos de guerra. Levantarão torres de cerco e construirão rampas contra os muros.

[[v26-21-23]]

^<<v26-21-23,23>>^ Os habitantes de Jerusalém pensarão que se trata de um presságio falso, por causa de seu acordo com os babilônios. Mas o rei da Babilônia os lembrará de sua rebeldia. Ele os atacará e os levará prisioneiros.

[[v26-21-24]]

^<<v26-21-24,24>>^ "Portanto, assim diz o SENHOR Soberano: Repetidamente, vocês me lembram de seus pecados e sua rebeldia. Nem sequer tentam escondê-los! Em tudo que fazem, seus pecados ficam evidentes. Por isso, chegou a hora de seu castigo.

[[v26-21-25]]

^<<v26-21-25,25>>^ "Ó príncipe de Israel, corrupto e perverso, o dia do acerto de contas chegou!

[[v26-21-26]]

^<<v26-21-26,26>>^ Assim diz o SENHOR Soberano: "Tire sua coroa coberta de joias, pois o antigo sistema está para mudar. Os humildes serão exaltados, e os orgulhosos, humilhados.

[[v26-21-27]]

^<<v26-21-27,27>>^ Destruição! Destruição! Certamente destruirei o reino, e não será restaurado até que venha aquele que tem o direito de julgá-lo; então o entregarei a ele."

[[v26-21-28]]

^<<v26-21-28,28>>^ "Agora, filho do homem, profetize acerca dos amonitas e sua zombaria. Transmita-lhes esta mensagem do SENHOR Soberano: "Uma espada, uma espada está pronta para a matança. Está polida para destruir e faísca como relâmpago.

[[v26-21-29]]

^<<v26-21-29,29>>^ Seus profetas lhes deram visões falsas, seus adivinhos lhes contaram mentiras. A espada cairá sobre o pescoço dos perversos, para quem chegou o dia do juízo.

[[v26-21-30]]

^<<v26-21-30,30>>^ "Agora, ponham a espada de volta na bainha, pois em sua própria terra, no lugar onde nasceram, eu os julgarei.

[[v26-21-31]]

^<<v26-21-31,31>>^ Derramarei minha fúria sobre vocês e soprarei em vocês o fogo de minha ira. Eu os entregarei a homens cruéis, hábeis em destruir.

[[v26-21-32]]

^<<v26-21-32,32>>^ Vocês serão combustível para o fogo, e seu sangue será derramado em sua própria terra. Não haverá mais lembrança de vocês na história, pois eu, o SENHOR, falei!".

'''

xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[&#60; Capítulo Anterior] | <<v26-21-0,Topo>> | xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[Próximo Capítulo &#62;]