include::./index.adoc[]

[[v26-13-0]]
=== Ezequiel, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v26-13-1]]

^<<v26-13-1,1>>^ Então recebi esta mensagem do SENHOR:

[[v26-13-2]]

^<<v26-13-2,2>>^ "Filho do homem, profetize contra os falsos profetas de Israel, que falam o que lhes vem à mente. Diga-lhes: ‘Ouçam a palavra do SENHOR.

[[v26-13-3]]

^<<v26-13-3,3>>^ Assim diz o SENHOR Soberano: Que aflição espera esses profetas insensatos, que seguem a própria imaginação e que não viram coisa alguma!’.

[[v26-13-4]]

^<<v26-13-4,4>>^ "Ó povo de Israel, seus profetas são como chacais no meio de ruínas.

[[v26-13-5]]

^<<v26-13-5,5>>^ Não tomaram nenhuma providência para consertar as brechas nos muros que rodeiam a nação, para que permanecesse firme na batalha no dia do SENHOR.

[[v26-13-6]]

^<<v26-13-6,6>>^ Em vez disso, anunciaram visões falsas e fizeram previsões mentirosas. Dizem: ‘Esta mensagem é do SENHOR’, embora o SENHOR jamais os tenha enviado. E, no entanto, esperam que as palavras que profetizam se cumpram!

[[v26-13-7]]

^<<v26-13-7,7>>^ Acaso não são falsas suas visões e mentirosas suas previsões, se vocês afirmam: ‘Esta mensagem é do SENHOR’, quando nem sequer falei com vocês?

[[v26-13-8]]

^<<v26-13-8,8>>^ "Portanto, assim diz o SENHOR Soberano: Porque suas palavras são falsas e suas visões, mentirosas, eu me colocarei contra vocês, diz o SENHOR Soberano.

[[v26-13-9]]

^<<v26-13-9,9>>^ Levantarei minha mão contra todos os profetas que têm visões falsas e fazem previsões mentirosas, e eles serão expulsos da comunidade de Israel. Apagarei seus nomes dos registros de Israel, e eles nunca voltarão a pisar em sua própria terra. Então vocês saberão que eu sou o SENHOR Soberano.

[[v26-13-10]]

^<<v26-13-10,10>>^ "Isso acontecerá porque esses profetas enganam meu povo, dizendo: ‘Tudo está em paz’, quando não há paz alguma. É como se o povo tivesse construído um muro precário e esses profetas o cobrissem com cal!

[[v26-13-11]]

^<<v26-13-11,11>>^ Diga aos que passam cal que o muro logo cairá. Uma forte tempestade virá, e grandes pedras de granizo e ventos impetuosos o derrubarão.

[[v26-13-12]]

^<<v26-13-12,12>>^ E, quando o muro cair, o povo dirá: ‘O que aconteceu com a cal que vocês passaram?’.

[[v26-13-13]]

^<<v26-13-13,13>>^ "Portanto, assim diz o SENHOR Soberano: Destruirei esse muro com ventos impetuosos de indignação, com forte tempestade de ira e com pedras de granizo de fúria.

[[v26-13-14]]

^<<v26-13-14,14>>^ Despedaçarei seu muro coberto de cal até os alicerces e, quando ele cair, esmagará vocês. Então vocês saberão que eu sou o SENHOR.

[[v26-13-15]]

^<<v26-13-15,15>>^ Enfim satisfarei minha fúria contra o muro e contra aqueles que o cobriram com cal. Em seguida, direi a vocês: ‘O muro e aqueles que o cobriram com cal não existem mais.

[[v26-13-16]]

^<<v26-13-16,16>>^ Eram os profetas de Israel, que anunciavam visões de paz para Jerusalém, quando não há paz alguma. Eu, o SENHOR Soberano, falei!’."

[[v26-13-17]]

^<<v26-13-17,17>>^ "Agora, filho do homem, pronuncie-se contra as mulheres que profetizam o que lhes vem à mente.

[[v26-13-18]]

^<<v26-13-18,18>>^ Assim diz o SENHOR Soberano: Que aflição espera vocês, mulheres que enlaçam a alma de meu povo, tanto dos jovens como dos idosos! Amarram amuletos no pulso deles e lhes fazem véus para a cabeça. Pensam que podem enlaçar outros sem provocar a própria destruição?

[[v26-13-19]]

^<<v26-13-19,19>>^ Vocês me desonram no meio de meu povo em troca de uns punhados de cevada ou um pedaço de pão. Quando mentem ao meu povo, que gosta de ouvir mentiras, vocês matam aqueles que não deviam morrer e prometem vida àqueles que não deviam viver.

[[v26-13-20]]

^<<v26-13-20,20>>^ "Assim diz o SENHOR Soberano: Estou contra todos os seus amuletos, que vocês usam para enlaçar meu povo. Eu os arrancarei de seus braços e libertarei meu povo, como pássaros que alguém solta de uma gaiola.

[[v26-13-21]]

^<<v26-13-21,21>>^ Arrancarei os véus e livrarei meu povo de suas mãos, e eles não serão mais suas vítimas. Então vocês saberão que eu sou o SENHOR.

[[v26-13-22]]

^<<v26-13-22,22>>^ Com suas mentiras, vocês desanimaram os justos, mas eu não queria que eles se entristecessem. Também encorajaram os perversos ao lhes prometer vida, embora eles continuem a pecar.

[[v26-13-23]]

^<<v26-13-23,23>>^ Por causa de tudo isso, vocês não falarão mais de visões que nunca tiveram, nem farão previsões enganosas. Pois eu livrarei meu povo de suas mãos. Então vocês saberão que eu sou o SENHOR".

'''

xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[&#60; Capítulo Anterior] | <<v26-13-0,Topo>> | xref:026-ezequiel/026-ezequiel-014.adoc#v26-14-0[Próximo Capítulo &#62;]