include::./index.adoc[]

[[v26-4-0]]
=== Ezequiel, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v26-4-1]]

^<<v26-4-1,1>>^ "Agora, filho do homem, pegue um tijolo de barro, coloque-o à sua frente e desenhe nele a cidade de Jerusalém.

[[v26-4-2]]

^<<v26-4-2,2>>^ Retrate a cidade cercada. Construa um muro ao redor dela, arme o acampamento inimigo e cerque a cidade com rampas e troncos de ataque.

[[v26-4-3]]

^<<v26-4-3,3>>^ Pegue uma panela de ferro e coloque-a entre você e a cidade. Volte-se para a cidade e mostre como será o cerco de Jerusalém. Isso será um sinal de advertência para o povo de Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ "Agora, deite-se sobre o lado esquerdo e ponha sobre si os pecados de Israel. Você terá de carregar os pecados de Israel pelo número de dias que ficar deitado sobre o lado esquerdo.

[[v26-4-5]]

^<<v26-4-5,5>>^ Determinei que carregará os pecados de Israel por 390 dias, um dia para cada ano de pecado do povo.

[[v26-4-6]]

^<<v26-4-6,6>>^ Depois, deite-se sobre o lado direito durante quarenta dias, um dia para cada ano de pecado de Judá.

[[v26-4-7]]

^<<v26-4-7,7>>^ "Enquanto isso, continue a olhar para o cerco de Jerusalém. Deite-se com o braço descoberto e profetize contra a cidade.

[[v26-4-8]]

^<<v26-4-8,8>>^ Eu o amarrarei com cordas para que você não possa virar-se de um lado para o outro, até que tenha completado os dias do cerco.

[[v26-4-9]]

^<<v26-4-9,9>>^ "Pegue um pouco de trigo, cevada, feijão, lentilha, milho-miúdo e trigo candeal e misture-os numa vasilha. Use-os para preparar seu pão durante os 390 dias em que ficará deitado sobre o lado esquerdo.

[[v26-4-10]]

^<<v26-4-10,10>>^ Racione suas porções, 240 gramas por dia, e coma-as em horas determinadas.

[[v26-4-11]]

^<<v26-4-11,11>>^ Depois, meça pouco mais de meio litro de água para cada dia e beba-a em horas determinadas.

[[v26-4-12]]

^<<v26-4-12,12>>^ Prepare e coma esse alimento como faria com bolos de cevada. Asse-o diante de todo o povo, usando fezes humanas secas como combustível."

[[v26-4-13]]

^<<v26-4-13,13>>^ E o SENHOR disse: "Assim os israelitas comerão pão impuro na terra dos gentios, para onde eu os expulsarei".

[[v26-4-14]]

^<<v26-4-14,14>>^ Então eu disse: "Ó SENHOR Soberano, jamais me contaminei! Desde a infância, nunca comi animais mortos por doença ou despedaçados por outros animais. Nunca comi carne alguma proibida pela lei".

[[v26-4-15]]

^<<v26-4-15,15>>^ Então ele me disse: "Em lugar de fezes humanas, você pode usar esterco de vaca para assar o pão".

[[v26-4-16]]

^<<v26-4-16,16>>^ E acrescentou: "Filho do homem, tornarei a comida extremamente escassa em Jerusalém. Será pesada com grande cuidado e consumida com medo. A água será racionada, e o povo beberá com desespero.

[[v26-4-17]]

^<<v26-4-17,17>>^ Diante da falta de comida e água, olharão uns para os outros aterrorizados e definharão debaixo de seu castigo."

'''

xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]