include::./index.adoc[]

[[v26-38-0]]
=== Ezequiel, 38
// nvt ?, NVT - Nova Versão Transformadora

[[v26-38-1]]

^<<v26-38-1,1>>^ Recebi esta mensagem do SENHOR:

[[v26-38-2]]

^<<v26-38-2,2>>^ "Filho do homem, volte o rosto para Gogue, da terra de Magogue, príncipe que governa as nações de Meseque e Tubal, e profetize contra ele.

[[v26-38-3]]

^<<v26-38-3,3>>^ Transmita-lhe esta mensagem do SENHOR Soberano: Gogue, príncipe de Meseque e Tubal, sou seu inimigo.

[[v26-38-4]]

^<<v26-38-4,4>>^ Eu o farei voltar e colocarei argolas em seu queixo para levá-lo junto com todo o seu exército: seus cavalos e condutores de carros de guerra vestidos com sua armadura completa e uma grande multidão armada com escudos e espadas.

[[v26-38-5]]

^<<v26-38-5,5>>^ A Pérsia, a Etiópia e a Líbia, com todas as suas armas, o acompanharão.

[[v26-38-6]]

^<<v26-38-6,6>>^ Gômer e todos os seus exércitos também se unirão a você, bem como os exércitos de Bete-Togarma, do extremo norte, e muitos outros.

[[v26-38-7]]

^<<v26-38-7,7>>^ "Prepare-se; esteja pronto! Mantenha todos os exércitos ao seu redor de prontidão e assuma o comando deles.

[[v26-38-8]]

^<<v26-38-8,8>>^ Daqui a muito tempo, você será convocado para entrar em ação. No futuro distante, você virá de repente sobre a terra de Israel, que viverá confiante depois de ter se recuperado da guerra e depois que seu povo tiver regressado de muitas terras para os montes de Israel.

[[v26-38-9]]

^<<v26-38-9,9>>^ Você e todos os seus aliados, um exército imenso e assustador, virão sobre Israel como uma tempestade e cobrirão a terra como uma nuvem.

[[v26-38-10]]

^<<v26-38-10,10>>^ "Assim diz o SENHOR Soberano: Naquele dia, maus pensamentos lhe virão à mente e você tramará um plano perverso.

[[v26-38-11]]

^<<v26-38-11,11>>^ Dirá: ‘Israel é uma terra desprotegida, cheia de povoados sem muros, sem portões e sem trancas. Marcharei contra ela e acabarei com esse povo que vive tão confiante.

[[v26-38-12]]

^<<v26-38-12,12>>^ Irei às cidades antes desoladas, mas que agora estão cheias de gente que voltou do exílio em muitas nações. Tomarei grande quantidade de despojo, pois agora seus habitantes têm muito gado e outros bens. Pensam que o mundo gira em torno deles!’.

[[v26-38-13]]

^<<v26-38-13,13>>^ Contudo, Sabá, Dedã e os comerciantes de Társis, com todos os seus jovens guerreiros, perguntarão: ‘Você pensa mesmo que os grandes exércitos que reuniu podem tomar a prata e o ouro deles? Acham que podem levar seus rebanhos, apoderar-se de seus bens e tomar despojos?’.

[[v26-38-14]]

^<<v26-38-14,14>>^ "Portanto, filho do homem, profetize contra Gogue. Transmita-lhe esta mensagem do SENHOR Soberano: Quando meu povo estiver vivendo confiante na terra dele, então você despertará.

[[v26-38-15]]

^<<v26-38-15,15>>^ Virá de sua terra no extremo norte com sua grande cavalaria e seu exército poderoso,

[[v26-38-16]]

^<<v26-38-16,16>>^ atacará meu povo, Israel, e cobrirá a terra como uma nuvem. Naquele dia, trarei você, Gogue, contra minha terra à vista de todos e mostrarei minha santidade por meio de tudo que lhe acontecer. Então todas as nações me conhecerão.

[[v26-38-17]]

^<<v26-38-17,17>>^ "Assim diz o SENHOR Soberano: Acaso você é aquele de quem falei muito tempo atrás, quando anunciei por meio de meus servos, os profetas de Israel, que, no futuro, o traria contra meu povo?

[[v26-38-18]]

^<<v26-38-18,18>>^ Mas assim diz o SENHOR Soberano: Quando Gogue invadir a terra de Israel, minha fúria transbordará!

[[v26-38-19]]

^<<v26-38-19,19>>^ Pois, em meu zelo e em minha ira ardente, sacudirei a terra de Israel violentamente naquele dia.

[[v26-38-20]]

^<<v26-38-20,20>>^ Todos os seres vivos, os peixes do mar, as aves do céu, os animais do campo, os animais que rastejam pelo chão, e todas as pessoas da terra, tremerão em minha presença. Montes serão derrubados, despenhadeiros cairão e muros desabarão.

[[v26-38-21]]

^<<v26-38-21,21>>^ Convocarei a espada contra você em todas as colinas de Israel, diz o SENHOR Soberano, e seus homens voltarão as espadas uns contra os outros.

[[v26-38-22]]

^<<v26-38-22,22>>^ Castigarei você e seus exércitos com doença e derramamento de sangue; enviarei chuvas torrenciais, granizo, fogo e enxofre!

[[v26-38-23]]

^<<v26-38-23,23>>^ Com isso mostrarei minha grandeza e santidade e me farei conhecido às nações do mundo. Então saberão que eu sou o SENHOR."

'''

xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[&#60; Capítulo Anterior] | <<v26-38-0,Topo>> | xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[Próximo Capítulo &#62;]