include::./index.adoc[]

[[v26-19-0]]
=== Ezequiel, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v26-19-1]]

^<<v26-19-1,1>>^ "Entoe este cântico fúnebre pelos príncipes de Israel:

[[v26-19-2]]

^<<v26-19-2,2>>^ "Que é sua mãe? Uma leoa entre os leões! Ela se deitava entre os leõezinhos e criava seus filhotes.

[[v26-19-3]]

^<<v26-19-3,3>>^ Criou um deles para se tornar um leão forte. Ele aprendeu a caçar e a despedaçar a presa e se tornou devorador de gente.

[[v26-19-4]]

^<<v26-19-4,4>>^ As nações ouviram falar dele e o apanharam na cova que lhe prepararam. Com ganchos o levaram para a terra do Egito.

[[v26-19-5]]

^<<v26-19-5,5>>^ "Quando a leoa viu que sua esperança por ele estava perdida, pegou outro filhote e o ensinou a ser um leão forte.

[[v26-19-6]]

^<<v26-19-6,6>>^ Ele andava entre os leões e se destacava por sua força. Aprendeu a caçar e a despedaçar a presa e também se tornou devorador de gente.

[[v26-19-7]]

^<<v26-19-7,7>>^ Derrubou fortalezas e destruiu cidades. A terra e seus habitantes tremiam de medo quando ouviam seu rugido.

[[v26-19-8]]

^<<v26-19-8,8>>^ Então os exércitos das nações o atacaram e o cercaram por todos os lados. Lançaram uma rede sobre ele e o apanharam na cova que lhe prepararam.

[[v26-19-9]]

^<<v26-19-9,9>>^ Com ganchos o arrastaram para dentro de uma jaula e o levaram ao rei da Babilônia. Eles o mantiveram preso, para que nunca mais se ouvisse sua voz nos montes de Israel.

[[v26-19-10]]

^<<v26-19-10,10>>^ "Sua mãe era como uma videira plantada junto à água. Tinha folhagem viçosa e dava frutos, porque havia muita água.

[[v26-19-11]]

^<<v26-19-11,11>>^ Seus ramos se tornaram fortes o suficiente para serem cetros de reis. Ela cresceu, ficou muito alta e se elevou acima de todas as outras.

[[v26-19-12]]

^<<v26-19-12,12>>^ Mas a videira foi arrancada pela raiz com fúria e atirada ao chão. O vento do deserto secou seus frutos e quebrou seus fortes ramos, por isso ela murchou e foi consumida pelo fogo.

[[v26-19-13]]

^<<v26-19-13,13>>^ Agora a videira está plantada no deserto, onde o solo é duro e seco.

[[v26-19-14]]

^<<v26-19-14,14>>^ De seus ramos saiu fogo e consumiu seus frutos. Os ramos que sobraram não são fortes o suficiente para serem cetros de reis. "Este é um cântico fúnebre e será entoado num funeral".

'''

xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[&#60; Capítulo Anterior] | <<v26-19-0,Topo>> | xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[Próximo Capítulo &#62;]