include::./index.adoc[]

[[v26-2-0]]
=== Ezequiel, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v26-2-1]]

^<<v26-2-1,1>>^ "Levante-se, filho do homem", disse a voz. "Quero falar com você."

[[v26-2-2]]

^<<v26-2-2,2>>^ Enquanto ele falava, o Espírito entrou em mim e me pôs em pé, e eu ouvi suas palavras com atenção.

[[v26-2-3]]

^<<v26-2-3,3>>^ "Filho do homem", disse ele, "eu o envio à nação de Israel, uma nação rebelde, que se revoltou contra mim. Até hoje, eles e seus antepassados têm se revoltado contra mim.

[[v26-2-4]]

^<<v26-2-4,4>>^ São um povo teimoso, de coração duro. Mas eu o envio para lhes dizer: ‘Assim diz o SENHOR Soberano!’.

[[v26-2-5]]

^<<v26-2-5,5>>^ E, quer eles ouçam quer não — lembre-se de que são rebeldes —, pelo menos saberão que tiveram um profeta no meio deles.

[[v26-2-6]]

^<<v26-2-6,6>>^ "Filho do homem, não tenha medo deles nem de suas palavras. Não tema, ainda que suas ameaças o cerquem como urtigas, espinhos e escorpiões. Não desanime com seus olhares raivosos, pois são um povo rebelde.

[[v26-2-7]]

^<<v26-2-7,7>>^ Anuncie-lhes minha mensagem, quer eles ouçam quer não, pois são completamente rebeldes.

[[v26-2-8]]

^<<v26-2-8,8>>^ Filho do homem, preste atenção ao que lhe digo. Não seja rebelde como eles. Abra sua boca e coma o que lhe dou."

[[v26-2-9]]

^<<v26-2-9,9>>^ Então olhei e vi a mão de alguém estendida para mim. Segurava um rolo,

[[v26-2-10]]

^<<v26-2-10,10>>^ que ela abriu. Vi que de ambos os lados estavam escritos cânticos fúnebres, lamentações e palavras de condenação.

'''

xref:026-ezequiel/026-ezequiel-001.adoc#v26-1-0[&#60; Capítulo Anterior] | <<v26-2-0,Topo>> | xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[Próximo Capítulo &#62;]