include::./index.adoc[]

[[v26-39-0]]
=== Ezequiel, 39
// nvt ?, NVT - Nova Versão Transformadora

[[v26-39-1]]

^<<v26-39-1,1>>^ "Filho do homem, profetize contra Gogue. Transmita-lhe esta mensagem do SENHOR Soberano: Sou seu inimigo, ó Gogue, príncipe que governa as nações de Meseque e Tubal.

[[v26-39-2]]

^<<v26-39-2,2>>^ Eu o farei dar a volta e o trarei do extremo norte, e o conduzirei em direção aos montes de Israel.

[[v26-39-3]]

^<<v26-39-3,3>>^ Derrubarei o arco de sua mão esquerda e as flechas de sua mão direita.

[[v26-39-4]]

^<<v26-39-4,4>>^ Você, seu exército e seus aliados morrerão nos montes. Eu os darei como alimento aos abutres e aos animais selvagens.

[[v26-39-5]]

^<<v26-39-5,5>>^ Você cairá em campos abertos, pois eu falei, diz o SENHOR Soberano.

[[v26-39-6]]

^<<v26-39-6,6>>^ Enviarei fogo sobre Magogue e sobre todos os seus aliados que vivem em segurança no litoral. Então eles saberão que eu sou o SENHOR.

[[v26-39-7]]

^<<v26-39-7,7>>^ "Assim, farei conhecido meu santo nome no meio de meu povo, Israel. Não deixarei que ninguém desonre meu nome. E as nações também saberão que eu sou o SENHOR, o Santo de Israel.

[[v26-39-8]]

^<<v26-39-8,8>>^ Esse dia de julgamento virá, diz o SENHOR Soberano. Tudo acontecerá como eu declarei.

[[v26-39-9]]

^<<v26-39-9,9>>^ "Então os habitantes das cidades de Israel sairão e recolherão seus escudos pequenos e os grandes, seus arcos e flechas, seus dardos e lanças e os usarão como lenha. Haverá o suficiente para sete anos!

[[v26-39-10]]

^<<v26-39-10,10>>^ Não precisarão cortar lenha dos campos nem dos bosques, pois essas armas fornecerão todo o combustível necessário. Eles saquearão aqueles que os saquearam e despojarão aqueles que os despojaram, diz o SENHOR Soberano.

[[v26-39-11]]

^<<v26-39-11,11>>^ "Nesse dia, prepararei um enorme cemitério para Gogue e suas multidões no vale dos Viajantes, a leste do mar Morto. Ele impedirá a passagem dos que viajam por ali, e eles mudarão o nome do lugar para vale das Multidões de Gogue.

[[v26-39-12]]

^<<v26-39-12,12>>^ O povo de Israel levará sete meses para sepultar os corpos e purificar a terra.

[[v26-39-13]]

^<<v26-39-13,13>>^ Todos em Israel ajudarão a sepultar, pois esse dia em que eu mostrar minha glória será uma data memorável para Israel, diz o SENHOR Soberano.

[[v26-39-14]]

^<<v26-39-14,14>>^ "Depois de sete meses, grupos de homens serão nomeados para percorrer a terra em busca de esqueletos para sepultar, a fim de que a terra seja purificada.

[[v26-39-15]]

^<<v26-39-15,15>>^ Onde forem encontrados ossos, será colocado um sinal para que os coveiros os levem e os enterrem no vale das Multidões de Gogue.

[[v26-39-16]]

^<<v26-39-16,16>>^ (Haverá ali uma cidade chamada Hamoná.) E com isso, enfim, a terra será purificada.

[[v26-39-17]]

^<<v26-39-17,17>>^ "Agora, filho do homem, assim diz o SENHOR Soberano: Chame todas as aves e todos os animais selvagens e diga-lhes: Reúnam-se para meu grande banquete sacrificial. Venham, de longe e de perto, para os montes de Israel e ali comam carne e bebam sangue!

[[v26-39-18]]

^<<v26-39-18,18>>^ Comam a carne de homens poderosos e bebam o sangue dos príncipes das nações como se fossem carneiros, cordeiros, bodes e touros, todos animais engordados de Basã.

[[v26-39-19]]

^<<v26-39-19,19>>^ Devorem carne até se empanturrar e bebam sangue até se embriagar. Este é o banquete sacrificial que lhes preparei.

[[v26-39-20]]

^<<v26-39-20,20>>^ Comam com fartura à minha mesa; comam cavalos, condutores de carros de guerra, homens valentes e guerreiros de toda espécie, diz o SENHOR Soberano.

[[v26-39-21]]

^<<v26-39-21,21>>^ "Desse modo, mostrarei minha glória às nações. Todos verão o castigo que trouxe sobre eles e o poder de minha mão quando eu castigo.

[[v26-39-22]]

^<<v26-39-22,22>>^ E, daquele dia em diante, o povo de Israel saberá que sou o SENHOR, seu Deus.

[[v26-39-23]]

^<<v26-39-23,23>>^ As nações saberão por que Israel foi enviado para o exílio: foi como castigo por causa do pecado, pois foram infiéis a seu Deus. Por isso me afastei deles e os entreguei a seus inimigos, para que os destruíssem.

[[v26-39-24]]

^<<v26-39-24,24>>^ Escondi deles o rosto e os castiguei por causa de sua impureza e de seus pecados."

[[v26-39-25]]

^<<v26-39-25,25>>^ "Portanto, assim diz o SENHOR Soberano: Acabarei com o exílio de meu povo; terei compaixão de todo o Israel, pois tenho zelo por meu santo nome.

[[v26-39-26]]

^<<v26-39-26,26>>^ Quando voltarem para sua terra e viverem em segurança, sem que ninguém lhes cause medo, assumirão a responsabilidade por sua vergonha e infidelidade no passado.

[[v26-39-27]]

^<<v26-39-27,27>>^ Quando eu os trouxer de volta das terras de seus inimigos, mostrarei minha santidade no meio deles, para que todas as nações a vejam.

[[v26-39-28]]

^<<v26-39-28,28>>^ Então meu povo saberá que eu sou o SENHOR, seu Deus, pois os enviei para o exílio entre as nações e os trouxe de volta para sua terra. Não deixarei nenhum deles para trás

[[v26-39-29]]

^<<v26-39-29,29>>^ e nunca mais me afastarei deles, pois derramarei meu Espírito sobre o povo de Israel. Eu, o SENHOR Soberano, falei!".

'''

xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[&#60; Capítulo Anterior] | <<v26-39-0,Topo>> | xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[Próximo Capítulo &#62;]