include::./index.adoc[]

[[v26-43-0]]
=== Ezequiel, 43
// nvt ?, NVT - Nova Versão Transformadora

[[v26-43-1]]

^<<v26-43-1,1>>^ Depois disso, o homem me levou à porta leste.

[[v26-43-2]]

^<<v26-43-2,2>>^ De repente, a glória do Deus de Israel surgiu, vindo do leste. O som de sua vinda era como o rugido de águas revoltas, e toda a paisagem se iluminou com sua glória.

[[v26-43-3]]

^<<v26-43-3,3>>^ A visão era como as outras que eu havia tido, primeiro junto ao rio Quebar e depois quando ele veio destruir Jerusalém. Prostrei-me com o rosto no chão,

[[v26-43-4]]

^<<v26-43-4,4>>^ e a glória do SENHOR entrou no templo pela porta leste.

[[v26-43-5]]

^<<v26-43-5,5>>^ Então o Espírito me pôs em pé e me levou ao pátio interno, e a glória do SENHOR encheu o templo.

[[v26-43-6]]

^<<v26-43-6,6>>^ Ouvi alguém falar comigo de dentro do templo, enquanto o homem que havia tomado as medidas estava ao meu lado.

[[v26-43-7]]

^<<v26-43-7,7>>^ O SENHOR me disse: "Filho do homem, este é o lugar de meu trono e o lugar onde descanso meus pés. Habitarei aqui para sempre no meio do povo de Israel. Eles e seus reis nunca mais profanarão meu santo nome ao cometer adultério adorando outros deuses ou ao honrar relíquias de seus reis que morreram.

[[v26-43-8]]

^<<v26-43-8,8>>^ Puseram os altares de seus ídolos ao lado de meu altar, com apenas uma parede entre mim e eles. Profanaram meu santo nome com esse pecado detestável, por isso os consumi em minha ira.

[[v26-43-9]]

^<<v26-43-9,9>>^ Agora, que deixem de adorar outros deuses e honrar as relíquias de seus reis, e eu habitarei no meio deles para sempre.

[[v26-43-10]]

^<<v26-43-10,10>>^ "Filho do homem, descreva para o povo de Israel o templo que lhe mostrei, para que eles se envergonhem de todos os seus pecados. Que eles estudem a planta do templo

[[v26-43-11]]

^<<v26-43-11,11>>^ e fiquem envergonhados de tudo que fizeram. Descreva-lhes todas as especificações do templo, incluindo as entradas e saídas, e todos os outros detalhes. Fale de seus decretos e suas leis. Escreva todas essas especificações e todos esses decretos diante do povo, para que se lembrem deles e lhes obedeçam.

[[v26-43-12]]

^<<v26-43-12,12>>^ E esta é a lei do templo: todo o alto do monte onde está o templo é santo. Sim, esta é a lei do templo."

[[v26-43-13]]

^<<v26-43-13,13>>^ "Estas são as medidas do altar: há uma calha ao redor de todo o altar com 0,5 metro de profundidade e 0,5 metro de largura, com uma borda de 23 centímetros à sua volta. E esta é a altura do altar:

[[v26-43-14]]

^<<v26-43-14,14>>^ da calha o altar se eleva por 1 metro até uma borda inferior ao seu redor com 0,5 metro de largura. Da borda inferior o altar se eleva por 2 metros até a borda superior, que também tem 0,5 metro de largura.

[[v26-43-15]]

^<<v26-43-15,15>>^ A parte de cima do altar, onde fica o fogo, se eleva mais 2 metros, com um chifre em cada um dos quatro cantos.

[[v26-43-16]]

^<<v26-43-16,16>>^ A parte de cima do altar é quadrada, com 6 metros de cada lado.

[[v26-43-17]]

^<<v26-43-17,17>>^ A borda superior também forma um quadrado, com 7 metros de cada lado, uma calha de 0,5 metro e uma saliência de 25 centímetros ao redor da borda. Há degraus do lado leste do altar".

[[v26-43-18]]

^<<v26-43-18,18>>^ Então ele me disse: "Filho do homem, assim diz o SENHOR Soberano: Estas serão as regras para a queima de ofertas e a aspersão de sangue depois que o altar for construído.

[[v26-43-19]]

^<<v26-43-19,19>>^ Nessa ocasião, os sacerdotes levitas da família de Zadoque, aqueles que servem diante de mim, devem receber um novilho para uma oferta pelo pecado, diz o SENHOR Soberano.

[[v26-43-20]]

^<<v26-43-20,20>>^ Você pegará um pouco do sangue do novilho e o aplicará aos quatro chifres do altar, aos quatro cantos da borda superior e à saliência em volta da borda. Com isso, purificará o altar e fará expiação por ele.

[[v26-43-21]]

^<<v26-43-21,21>>^ Em seguida, pegará o novilho para a oferta pelo pecado e o queimará no lugar indicado, fora da área do templo.

[[v26-43-22]]

^<<v26-43-22,22>>^ "No segundo dia, apresentará como oferta pelo pecado um bode sem defeito. Em seguida, purificará o altar e fará expiação por ele novamente, como fez com o novilho.

[[v26-43-23]]

^<<v26-43-23,23>>^ Quando tiver terminado a cerimônia de purificação, apresentará outro novilho sem defeito e um carneiro perfeito do rebanho.

[[v26-43-24]]

^<<v26-43-24,24>>^ Você os oferecerá ao SENHOR, e os sacerdotes espalharão sal sobre eles e os apresentarão como holocausto ao SENHOR.

[[v26-43-25]]

^<<v26-43-25,25>>^ "Todos os dias, por sete dias, você apresentará um bode, um novilho e um carneiro do rebanho como oferta pelo pecado. Nenhum desses animais deve ter qualquer defeito.

[[v26-43-26]]

^<<v26-43-26,26>>^ Fará isso todos os dias, por sete dias, para purificar o altar e fazer expiação por ele e, desse modo, separá-lo para o uso sagrado.

[[v26-43-27]]

^<<v26-43-27,27>>^ No oitavo dia, e a cada dia depois disso, os sacerdotes oferecerão no altar os holocaustos e as ofertas de paz do povo. Então eu aceitarei vocês. Eu, o SENHOR Soberano, falei!".

'''

xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[&#60; Capítulo Anterior] | <<v26-43-0,Topo>> | xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[Próximo Capítulo &#62;]