include::./index.adoc[]

[[v26-33-0]]
=== Ezequiel, 33
// nvt ?, NVT - Nova Versão Transformadora

[[v26-33-1]]

^<<v26-33-1,1>>^ Mais uma vez, recebi uma mensagem do SENHOR:

[[v26-33-2]]

^<<v26-33-2,2>>^ "Filho do homem, transmita esta mensagem a seu povo: ‘Quando eu trago um exército contra um país, os habitantes dessa terra escolhem alguém para ser vigia.

[[v26-33-3]]

^<<v26-33-3,3>>^ Quando o vigia vê o inimigo, ele dá o sinal de alarme para avisar o povo.

[[v26-33-4]]

^<<v26-33-4,4>>^ Se aqueles que ouvirem o sinal de alarme não tomarem providências, serão culpados da própria morte.

[[v26-33-5]]

^<<v26-33-5,5>>^ Ouviram o sinal de alarme, mas não deram atenção, de modo que a responsabilidade é deles. Se tivessem dado atenção à advertência, teriam salvado a vida.

[[v26-33-6]]

^<<v26-33-6,6>>^ Se, contudo, o vigia vê o inimigo, mas não dá o sinal de alarme para advertir o povo, ele é responsável. Eles morrerão em seus pecados, mas considerarei o vigia responsável pela morte deles’.

[[v26-33-7]]

^<<v26-33-7,7>>^ "Agora, filho do homem, eu o coloquei como vigia do povo de Israel. Portanto, ouça o que eu digo e advirta-os em meu nome.

[[v26-33-8]]

^<<v26-33-8,8>>^ Se eu anunciar que alguns perversos certamente morrerão e você não lhes disser que mudem sua conduta, eles morrerão em seus pecados, mas considerarei você responsável pela morte deles.

[[v26-33-9]]

^<<v26-33-9,9>>^ Se, contudo, você os advertir para que mudem sua conduta e eles não o fizerem, morrerão em seus pecados, mas você salvará a vida."

[[v26-33-10]]

^<<v26-33-10,10>>^ "Filho do homem, transmita esta mensagem ao povo de Israel: Vocês dizem: ‘Nossos pecados pesam sobre nós; estamos definhando! Como sobreviveremos?’.

[[v26-33-11]]

^<<v26-33-11,11>>^ Tão certo como eu vivo, diz o SENHOR Soberano, não tenho prazer algum na morte dos perversos. Antes, meu desejo é que se afastem de seus maus caminhos, para que vivam. Arrependam-se! Afastem-se de sua maldade! Por que morrer, ó povo de Israel?

[[v26-33-12]]

^<<v26-33-12,12>>^ "Filho do homem, transmita esta mensagem a seu povo: A conduta justa dos justos não os salvará se eles se voltarem para o pecado, nem a conduta perversa dos perversos os destruirá se eles se afastarem de seus pecados.

[[v26-33-13]]

^<<v26-33-13,13>>^ Se eu disser aos justos que eles viverão, mas depois eles pecarem, confiando que sua justiça no passado os salvará, nenhum de seus atos de justiça será lembrado, e eles morrerão por causa de seus pecados.

[[v26-33-14]]

^<<v26-33-14,14>>^ Suponhamos que eu diga aos perversos que eles certamente morrerão, mas depois eles se afastem de seus pecados e façam o que é justo e certo.

[[v26-33-15]]

^<<v26-33-15,15>>^ Pode ser, por exemplo, que devolvam a garantia de um devedor, restituam o que roubaram, obedeçam a meus decretos que dão vida e não pratiquem mais o mal. Nesse caso, certamente viverão, e não morrerão.

[[v26-33-16]]

^<<v26-33-16,16>>^ Nenhum de seus pecados do passado será lembrado, pois fizeram o que é justo e certo, e certamente viverão.

[[v26-33-17]]

^<<v26-33-17,17>>^ "Seu povo diz: ‘O Senhor não é justo’, mas são eles os injustos.

[[v26-33-18]]

^<<v26-33-18,18>>^ Pois, se os justos se afastarem de sua conduta justa e praticarem o mal, morrerão.

[[v26-33-19]]

^<<v26-33-19,19>>^ Mas, se os perversos se afastarem de sua conduta perversa e fizerem o que é justo e certo, viverão.

[[v26-33-20]]

^<<v26-33-20,20>>^ Ó povo de Israel, vocês dizem: ‘O Senhor não é justo’. Mas eu julgarei cada um de vocês de acordo com suas ações".

[[v26-33-21]]

^<<v26-33-21,21>>^ Em 8 de janeiro, no décimo segundo ano de nosso exílio, um sobrevivente de Jerusalém veio a mim e disse: "A cidade caiu!".

[[v26-33-22]]

^<<v26-33-22,22>>^ Na noite anterior, a mão do SENHOR tinha vindo sobre mim e me restaurado a voz. Por isso, consegui falar quando o homem chegou na manhã seguinte.

[[v26-33-23]]

^<<v26-33-23,23>>^ Então recebi esta mensagem do SENHOR:

[[v26-33-24]]

^<<v26-33-24,24>>^ "Filho do homem, o remanescente de Israel, que vive espalhado entre as cidades arruinadas, anda dizendo: ‘Abraão era um só e, no entanto, veio a possuir toda a terra. Nós somos muitos; certamente a terra nos foi dada como propriedade’.

[[v26-33-25]]

^<<v26-33-25,25>>^ Portanto, diga-lhes: ‘Assim diz o SENHOR Soberano: Vocês comem carne com sangue, adoram ídolos e assassinam inocentes. Acreditam mesmo que a terra deve ser sua?

[[v26-33-26]]

^<<v26-33-26,26>>^ Assassinos! Idólatras! Adúlteros! Acaso deveriam possuir a terra?’.

[[v26-33-27]]

^<<v26-33-27,27>>^ "Diga-lhes: ‘Assim diz o SENHOR Soberano: Tão certo como eu vivo, os que vivem nas ruínas morrerão à espada, os que vivem nos campos abertos serão devorados por animais selvagens que eu enviarei, e os que estão escondidos em fortalezas e em cavernas morrerão de doença.

[[v26-33-28]]

^<<v26-33-28,28>>^ Destruirei completamente a terra e arrasarei o orgulho de seu poder. Os montes de Israel ficarão desolados, e ninguém passará por eles.

[[v26-33-29]]

^<<v26-33-29,29>>^ Quando eu tiver destruído a terra completamente por causa de seus pecados detestáveis, eles saberão que eu sou o SENHOR’.

[[v26-33-30]]

^<<v26-33-30,30>>^ "Filho do homem, seu povo fala de você em suas casas e junto às portas. Dizem uns aos outros: ‘Venham, vamos ouvir o que o profeta tem a nos dizer da parte do SENHOR’.

[[v26-33-31]]

^<<v26-33-31,31>>^ Eles vêm, fingindo ser sinceros, e sentam-se diante de você. Ouvem suas palavras, mas não têm intenção alguma de pô-las em prática. Têm a boca cheia de palavras sensuais, e seu coração só quer dinheiro.

[[v26-33-32]]

^<<v26-33-32,32>>^ Eles o consideram um divertimento, como alguém que entoa canções de amor com uma linda voz ou toca belas músicas num instrumento. Ouvem suas palavras, mas não as põem em prática.

[[v26-33-33]]

^<<v26-33-33,33>>^ Quando, porém, todas essas terríveis coisas acontecerem, e elas certamente acontecerão, saberão que um profeta esteve no meio deles".

'''

xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[&#60; Capítulo Anterior] | <<v26-33-0,Topo>> | xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[Próximo Capítulo &#62;]