include::./index.adoc[]

[[v26-16-0]]
=== Ezequiel, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v26-16-1]]

^<<v26-16-1,1>>^ Então recebi outra mensagem do SENHOR:

[[v26-16-2]]

^<<v26-16-2,2>>^ "Filho do homem, faça Jerusalém ver como são detestáveis seus pecados.

[[v26-16-3]]

^<<v26-16-3,3>>^ Transmita-lhe esta mensagem do SENHOR Soberano: Você não passa de uma cananeia! Seu pai era amorreu, e sua mãe era hitita.

[[v26-16-4]]

^<<v26-16-4,4>>^ No dia em que você nasceu, ninguém cortou seu cordão umbilical, nem a lavou, nem a esfregou com sal, nem a enrolou em panos.

[[v26-16-5]]

^<<v26-16-5,5>>^ Ninguém teve compaixão nem cuidou de você. No dia em que nasceu, você foi rejeitada e abandonada num campo.

[[v26-16-6]]

^<<v26-16-6,6>>^ "Mas eu passei por lá e a vi, indefesa, esperneando em seu sangue, e lhe disse: ‘Viva!’.

[[v26-16-7]]

^<<v26-16-7,7>>^ Eu a fiz desenvolver-se, como uma planta no campo. Você cresceu e se tornou uma linda joia. Seus seios se formaram e seu cabelo cresceu, mas você continuava nua.

[[v26-16-8]]

^<<v26-16-8,8>>^ Quando passei por você outra vez, vi que já tinha idade suficiente para amar. Eu a envolvi com meu manto para cobrir sua nudez e pronunciei meus votos de casamento. Fiz uma aliança com você, diz o SENHOR Soberano, e você se tornou minha.

[[v26-16-9]]

^<<v26-16-9,9>>^ "Então lavei você, limpei o sangue e passei óleo perfumado em sua pele.

[[v26-16-10]]

^<<v26-16-10,10>>^ Eu lhe dei roupas caras de linho fino e de seda com lindos bordados e sandálias feitas do mais excelente couro de cabra.

[[v26-16-11]]

^<<v26-16-11,11>>^ Também lhe dei belas joias, pulseiras e lindos colares,

[[v26-16-12]]

^<<v26-16-12,12>>^ uma argola para o nariz, brincos para as orelhas e uma bela coroa para a cabeça.

[[v26-16-13]]

^<<v26-16-13,13>>^ Assim, você foi enfeitada com ouro e prata. Suas roupas eram feitas de linho fino e seda e tinham lindos bordados. Você comia os alimentos mais seletos — farinha da melhor qualidade, mel e azeite — e se tornou mais linda que nunca. Parecia uma rainha, e de fato era!

[[v26-16-14]]

^<<v26-16-14,14>>^ Sua fama logo se espalhou por todo o mundo, por causa de sua beleza. Eu a vesti com meu esplendor e aperfeiçoei sua beleza, diz o SENHOR Soberano.

[[v26-16-15]]

^<<v26-16-15,15>>^ "No entanto, você pensou que era dona de sua fama e de sua beleza. Então, entregou-se como prostituta a todo homem que passava. Sua beleza estava à disposição de quem a pedisse.

[[v26-16-16]]

^<<v26-16-16,16>>^ Usou os presentes lindos que lhe dei para fazer altares para seus ídolos e ali se prostituiu. Nunca se viu uma coisa dessas!

[[v26-16-17]]

^<<v26-16-17,17>>^ Pegou as joias e os enfeites de ouro e prata que lhe dei, fez estátuas de homens e as adorou. Desse modo, cometeu adultério contra mim.

[[v26-16-18]]

^<<v26-16-18,18>>^ Com as lindas roupas bordadas que lhe dei, vestiu seus ídolos e usou meu óleo perfumado e meu incenso para adorá-los.

[[v26-16-19]]

^<<v26-16-19,19>>^ Colocou diante deles como sacrifício a farinha da melhor qualidade, o azeite e o mel com que cuidei de você, diz o SENHOR Soberano.

[[v26-16-20]]

^<<v26-16-20,20>>^ "Depois, pegou seus filhos e suas filhas, que havia gerado para mim, e os sacrificou a seus deuses. Acaso não bastou você se prostituir?

[[v26-16-21]]

^<<v26-16-21,21>>^ Também teve de matar meus filhos como sacrifício a ídolos?

[[v26-16-22]]

^<<v26-16-22,22>>^ Em todo o seu pecado detestável e em seu adultério, você não se lembrou daqueles dias, muito tempo atrás, em que estava nua e abandonada, esperneando em seu sangue.

[[v26-16-23]]

^<<v26-16-23,23>>^ "Que aflição a espera!, diz o SENHOR Soberano. Além de todas as suas maldades,

[[v26-16-24]]

^<<v26-16-24,24>>^ você construiu um lugar de adoração e ergueu altares a ídolos em todas as praças da cidade.

[[v26-16-25]]

^<<v26-16-25,25>>^ Em cada esquina, contaminou sua beleza e ofereceu seu corpo a todos que passavam, aumentando sua prostituição.

[[v26-16-26]]

^<<v26-16-26,26>>^ Então acrescentou a seus amantes o lascivo Egito e provocou minha ira com promiscuidade cada vez maior.

[[v26-16-27]]

^<<v26-16-27,27>>^ Por isso eu a feri com minha mão e reduzi seu território. Entreguei-a a seus inimigos, os filisteus, e até eles ficaram espantados com sua conduta depravada.

[[v26-16-28]]

^<<v26-16-28,28>>^ Você também se prostituiu com os assírios. Parece que nunca se cansa de procurar amantes! E, mesmo depois de se prostituir com eles, não ficou satisfeita.

[[v26-16-29]]

^<<v26-16-29,29>>^ Acrescentou a seus amantes a Babilônia, terra de comerciantes, mas ainda assim não se contentou.

[[v26-16-30]]

^<<v26-16-30,30>>^ "Como seu coração é fraco, diz o SENHOR Soberano, para fazer essas coisas e se comportar como uma prostituta desavergonhada!

[[v26-16-31]]

^<<v26-16-31,31>>^ Constrói lugares de adoração em todas as esquinas e altares a seus ídolos em todas as praças. Na verdade, você foi pior que uma prostituta, pois nem exigiu pagamento.

[[v26-16-32]]

^<<v26-16-32,32>>^ Sim, você é uma esposa adúltera que acolhe estranhos em vez do marido.

[[v26-16-33]]

^<<v26-16-33,33>>^ As prostitutas cobram por seus serviços, mas você não! Oferece presentes a seus amantes e os suborna para adulterarem com você.

[[v26-16-34]]

^<<v26-16-34,34>>^ Faz, portanto, o contrário de outras prostitutas. Paga seus amantes em vez de eles pagarem você!"

[[v26-16-35]]

^<<v26-16-35,35>>^ "Portanto, prostituta, ouça esta mensagem do SENHOR.

[[v26-16-36]]

^<<v26-16-36,36>>^ Assim diz o SENHOR Soberano: Visto que você derramou sua lascívia e se expôs em prostituição a todos os seus amantes, adorou ídolos detestáveis e matou seus filhos como sacrifícios a seus deuses,

[[v26-16-37]]

^<<v26-16-37,37>>^ ouça o que farei. Reunirei todos os seus aliados — seus amantes com os quais você teve prazer, os que você amou e também os que odiou — e a deixarei nua diante deles, para que todos a vejam.

[[v26-16-38]]

^<<v26-16-38,38>>^ Eu a castigarei por homicídio e adultério e, na fúria de meu ciúme, a cobrirei de sangue.

[[v26-16-39]]

^<<v26-16-39,39>>^ Então a entregarei a esses muitos povos que são seus amantes, e eles a destruirão. Derrubarão seus lugares de adoração e os altares de seus ídolos. Arrancarão suas roupas, levarão suas lindas joias e a deixarão completamente nua.

[[v26-16-40]]

^<<v26-16-40,40>>^ Eles se juntarão e formarão uma multidão violenta que a apedrejará e a cortará com espadas.

[[v26-16-41]]

^<<v26-16-41,41>>^ Queimarão suas casas e a castigarão diante de muitas mulheres. Eu porei fim à sua prostituição, e você não pagará mais seus muitos amantes.

[[v26-16-42]]

^<<v26-16-42,42>>^ "Por fim, satisfarei minha fúria contra você, e meu ciúme se acalmará. Ficarei tranquilo e já não ficarei irado com você.

[[v26-16-43]]

^<<v26-16-43,43>>^ Primeiro, porém, uma vez que você não se lembrou de sua juventude, mas provocou minha ira com todas as suas maldades, eu lhe darei o castigo merecido por sua conduta, diz o SENHOR Soberano. Pois a todos os seus pecados detestáveis você acrescentou a depravação.

[[v26-16-44]]

^<<v26-16-44,44>>^ Todos que inventam provérbios dirão a seu respeito: ‘Tal mãe, tal filha’.

[[v26-16-45]]

^<<v26-16-45,45>>^ Pois sua mãe detestava o marido e os filhos, e você faz o mesmo. É exatamente como suas irmãs, que também desprezaram marido e filhos. De fato, sua mãe era hitita, e seu pai, amorreu.

[[v26-16-46]]

^<<v26-16-46,46>>^ "Sua irmã mais velha era Samaria, que vivia com as filhas ao norte. Sua irmã mais nova era Sodoma, que vivia com as filhas ao sul.

[[v26-16-47]]

^<<v26-16-47,47>>^ Mas você não apenas imitou sua conduta e seus pecados detestáveis; em pouco tempo, você as superou em sua depravação.

[[v26-16-48]]

^<<v26-16-48,48>>^ Tão certo como eu vivo, diz o SENHOR Soberano, Sodoma e suas filhas nunca foram tão perversas quanto você e suas filhas.

[[v26-16-49]]

^<<v26-16-49,49>>^ Sodoma cometia os pecados de orgulho, glutonaria e preguiça, enquanto os pobres e necessitados sofriam.

[[v26-16-50]]

^<<v26-16-50,50>>^ Era arrogante e cometia pecados detestáveis, por isso eu a exterminei, como você viu.

[[v26-16-51]]

^<<v26-16-51,51>>^ "Nem mesmo Samaria cometeu metade dos pecados que você cometeu. Você fez coisas muito mais detestáveis que suas irmãs. Comparadas a você, elas parecem justas.

[[v26-16-52]]

^<<v26-16-52,52>>^ Você deveria se envergonhar. Seus pecados são tão terríveis que fazem suas irmãs parecerem justas, e até mesmo puras. Que coisa vergonhosa!

[[v26-16-53]]

^<<v26-16-53,53>>^ "Um dia, porém, restaurarei Sodoma e Samaria, e você também.

[[v26-16-54]]

^<<v26-16-54,54>>^ Então você ficará verdadeiramente envergonhada de tudo que fez, pois seus pecados fazem suas irmãs se sentirem bem em comparação com você.

[[v26-16-55]]

^<<v26-16-55,55>>^ Quando suas irmãs, Sodoma e Samaria, e todos os seus habitantes forem restaurados, você também será restaurada.

[[v26-16-56]]

^<<v26-16-56,56>>^ Você, em seus dias de arrogância, desprezava Sodoma.

[[v26-16-57]]

^<<v26-16-57,57>>^ Agora, porém, sua perversidade se tornou evidente para todo o mundo, e você é desprezada por Edom, por todos os vizinhos dele e pela Filístia.

[[v26-16-58]]

^<<v26-16-58,58>>^ Esse é o castigo por sua depravação e seus pecados detestáveis, diz o SENHOR.

[[v26-16-59]]

^<<v26-16-59,59>>^ "Assim diz o SENHOR Soberano: Eu lhe darei o que você merece, pois não levou a sério seus votos solenes e quebrou sua aliança.

[[v26-16-60]]

^<<v26-16-60,60>>^ Contudo, me lembrarei da aliança que fiz com você em sua juventude e estabelecerei com você uma aliança permanente.

[[v26-16-61]]

^<<v26-16-61,61>>^ Então você se lembrará com vergonha de tudo que fez. Farei que suas irmãs, Samaria e Sodoma, se tornem suas filhas, embora elas não façam parte de nossa aliança.

[[v26-16-62]]

^<<v26-16-62,62>>^ Reafirmarei minha aliança com você, e você saberá que eu sou o SENHOR.

[[v26-16-63]]

^<<v26-16-63,63>>^ Você se lembrará de seus pecados e ficará calada de tanta vergonha quando eu perdoar tudo que fez. Eu, o SENHOR Soberano, falei!".

'''

xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[&#60; Capítulo Anterior] | <<v26-16-0,Topo>> | xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[Próximo Capítulo &#62;]