include::./index.adoc[]

[[v26-10-0]]
=== Ezequiel, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v26-10-1]]

^<<v26-10-1,1>>^ Olhei e vi algo que se parecia com um trono de safira sobre uma superfície de cristal acima da cabeça dos querubins.

[[v26-10-2]]

^<<v26-10-2,2>>^ Então o SENHOR disse ao homem vestido de linho: "Vá entre as rodas que estão debaixo dos querubins, pegue um punhado de brasas ardentes e espalhe-as sobre a cidade". Ele assim fez enquanto eu observava.

[[v26-10-3]]

^<<v26-10-3,3>>^ Os querubins estavam na extremidade sul do templo quando o homem entrou, e a nuvem de glória encheu o pátio interno.

[[v26-10-4]]

^<<v26-10-4,4>>^ Então a glória do SENHOR se elevou acima dos querubins e foi para a porta do templo. Essa nuvem encheu o templo, e o pátio resplandeceu com a glória do SENHOR.

[[v26-10-5]]

^<<v26-10-5,5>>^ O movimento das asas dos querubins fazia um som como a voz do Deus Todo-poderoso, e podia-se ouvi-lo até no pátio externo.

[[v26-10-6]]

^<<v26-10-6,6>>^ O SENHOR ordenou ao homem vestido de linho: "Vá entre os querubins e pegue algumas brasas ardentes que estão entre as rodas". O homem foi e colocou-se ao lado das rodas.

[[v26-10-7]]

^<<v26-10-7,7>>^ Em seguida, um dos querubins estendeu a mão e pegou algumas brasas ardentes do fogo que estava entre os querubins. Colocou as brasas nas mãos do homem vestido de linho, e o homem as recebeu e saiu.

[[v26-10-8]]

^<<v26-10-8,8>>^ (Todos os querubins tinham debaixo das asas o que se parecia com mãos humanas.)

[[v26-10-9]]

^<<v26-10-9,9>>^ Olhei e vi que cada um dos quatro querubins tinha ao seu lado uma roda, e as rodas brilhavam como berilo.

[[v26-10-10]]

^<<v26-10-10,10>>^ As quatro rodas eram semelhantes e feitas da mesma forma; cada uma tinha dentro dela outra roda que girava na transversal.

[[v26-10-11]]

^<<v26-10-11,11>>^ Os querubins podiam se deslocar em qualquer uma das quatro direções, sem se virar enquanto se moviam. Deslocavam-se para a frente, sem se virar.

[[v26-10-12]]

^<<v26-10-12,12>>^ Tanto os querubins como as rodas eram cobertos de olhos. Os querubins tinham olhos por todo o corpo, inclusive nas mãos, nas costas e nas asas.

[[v26-10-13]]

^<<v26-10-13,13>>^ Ouvi alguém se referir às rodas como "rodas giratórias".

[[v26-10-14]]

^<<v26-10-14,14>>^ Cada um dos quatro querubins tinha quatro rostos: o primeiro era rosto de boi, o segundo, de homem, o terceiro, de leão, e o quarto, de águia.

[[v26-10-15]]

^<<v26-10-15,15>>^ Então os querubins se elevaram. Eram os mesmos seres vivos que eu tinha visto junto ao rio Quebar.

[[v26-10-16]]

^<<v26-10-16,16>>^ Quando os querubins se moviam, as rodas se moviam com eles. Quando levantavam as asas para voar, as rodas os acompanhavam.

[[v26-10-17]]

^<<v26-10-17,17>>^ Quando os querubins paravam, as rodas paravam. Quando voavam para cima, as rodas subiam, pois o espírito dos seres vivos estava nas rodas.

[[v26-10-18]]

^<<v26-10-18,18>>^ Então a glória do SENHOR se afastou da porta do templo e parou sobre os querubins.

[[v26-10-19]]

^<<v26-10-19,19>>^ E, enquanto eu observava, os querubins voaram, acompanhados de suas rodas, até a porta leste do templo do SENHOR. E a glória do Deus de Israel pairava sobre eles.

[[v26-10-20]]

^<<v26-10-20,20>>^ Esses seres vivos eram os mesmos que eu tinha visto debaixo do Deus de Israel quando estava junto ao rio Quebar. Eu sabia que eram querubins,

[[v26-10-21]]

^<<v26-10-21,21>>^ pois cada um tinha quatro rostos, quatro asas e o que se parecia com mãos humanas debaixo das asas.

[[v26-10-22]]

^<<v26-10-22,22>>^ E seus rostos eram iguais aos dos seres que eu tinha visto no Quebar, e se deslocavam para a frente, como os outros.

'''

xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[&#60; Capítulo Anterior] | <<v26-10-0,Topo>> | xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[Próximo Capítulo &#62;]