include::./index.adoc[]

[[v26-6-0]]
=== Ezequiel, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v26-6-1]]

^<<v26-6-1,1>>^ Recebi outra mensagem do SENHOR:

[[v26-6-2]]

^<<v26-6-2,2>>^ "Filho do homem, volte o rosto para os montes de Israel e profetize contra eles.

[[v26-6-3]]

^<<v26-6-3,3>>^ Proclame esta mensagem do SENHOR Soberano contra os montes de Israel. Assim diz o SENHOR Soberano aos montes, às colinas, aos desfiladeiros e aos vales: Estou prestes a trazer guerra sobre vocês e destruir seus santuários idólatras.

[[v26-6-4]]

^<<v26-6-4,4>>^ Todos os seus altares serão demolidos, e seus lugares de adoração serão destruídos. Matarei o povo diante de seus ídolos.

[[v26-6-5]]

^<<v26-6-5,5>>^ Porei os cadáveres dos israelitas diante de seus ídolos e espalharei os ossos ao redor de seus altares.

[[v26-6-6]]

^<<v26-6-6,6>>^ Onde quer que vocês vivam, haverá desolação, e destruirei os santuários idólatras. Seus altares serão demolidos, seus ídolos serão despedaçados, seus lugares de adoração serão derrubados e todos os objetos religiosos que vocês fizeram serão destruídos.

[[v26-6-7]]

^<<v26-6-7,7>>^ O lugar ficará cheio de cadáveres, e vocês saberão que somente eu sou o SENHOR.

[[v26-6-8]]

^<<v26-6-8,8>>^ "Deixarei, porém, que alguns do meu povo escapem da destruição, e eles serão espalhados entre as nações do mundo.

[[v26-6-9]]

^<<v26-6-9,9>>^ Então, quando estiverem exilados entre as nações, se lembrarão de mim. Reconhecerão quanto me entristece seu coração infiel e seus olhos lascivos por seus ídolos. Por fim, terão nojo de si mesmos por causa de todos os seus pecados detestáveis.

[[v26-6-10]]

^<<v26-6-10,10>>^ Saberão que somente eu sou o SENHOR e que falava sério quando disse que traria sobre eles essa calamidade.

[[v26-6-11]]

^<<v26-6-11,11>>^ "Assim diz o SENHOR Soberano: Batam palmas de horror e batam os pés. Gritem por causa de todos os pecados detestáveis que o povo de Israel cometeu. Agora, morrerão de guerra, fome e doença.

[[v26-6-12]]

^<<v26-6-12,12>>^ A doença matará os que estiverem exilados em lugares distantes, a guerra destruirá os que estiverem por perto, e os que sobrarem morrerão de fome. Enfim derramarei toda a minha fúria sobre eles.

[[v26-6-13]]

^<<v26-6-13,13>>^ Eles saberão que sou o SENHOR quando seus mortos estiverem espalhados entre os ídolos e os altares em todas as colinas e montes, debaixo de toda árvore verdejante e de todo carvalho que dá sombra, os lugares onde ofereciam sacrifícios a seus ídolos.

[[v26-6-14]]

^<<v26-6-14,14>>^ Eu os arrasarei e deixarei suas cidades desoladas, desde o deserto, no sul, até Ribla, no norte. Então saberão que eu sou o SENHOR".

'''

xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[Próximo Capítulo &#62;]