include::./index.adoc[]

[[v26-26-0]]
=== Ezequiel, 26
// nvt ?, NVT - Nova Versão Transformadora

[[v26-26-1]]

^<<v26-26-1,1>>^ Em 3 de fevereiro, no décimo segundo ano do exílio do rei Joaquim, recebi esta mensagem do SENHOR:

[[v26-26-2]]

^<<v26-26-2,2>>^ "Filho do homem, Tiro se alegrou com a queda de Jerusalém e disse: ‘Ah! Aquela que era a porta para as mais prósperas rotas comerciais do leste foi quebrada, e agora é minha vez! Porque ela está desolada, eu ficarei rico!’.

[[v26-26-3]]

^<<v26-26-3,3>>^ "Portanto, assim diz o SENHOR Soberano: Ó cidade de Tiro, sou seu inimigo e trarei muitas nações contra você, como ondas do mar que quebram em suas praias.

[[v26-26-4]]

^<<v26-26-4,4>>^ Elas destruirão os muros de Tiro e derrubarão suas torres. Eu rasparei seu solo até torná-lo rocha bruta!

[[v26-26-5]]

^<<v26-26-5,5>>^ Será apenas uma rocha no mar, um lugar para os pescadores estenderem suas redes, pois eu falei, diz o SENHOR Soberano. Tiro se tornará presa de muitas nações,

[[v26-26-6]]

^<<v26-26-6,6>>^ e seus povoados no continente serão destruídos pela espada. Então eles saberão que eu sou o SENHOR.

[[v26-26-7]]

^<<v26-26-7,7>>^ "Assim diz o SENHOR Soberano: Do norte trarei contra Tiro o rei da Babilônia, Nabucodonosor. Ele é rei de reis e virá com seus cavalos, seus carros de guerra e condutores, e com um grande exército.

[[v26-26-8]]

^<<v26-26-8,8>>^ Primeiro ele destruirá os povoados no continente, e depois, para atacá-la, construirá um muro de cerco e uma rampa e levantará uma barreira de escudos contra você.

[[v26-26-9]]

^<<v26-26-9,9>>^ Usará troncos para atacar seus muros e demolirá suas torres com marretas.

[[v26-26-10]]

^<<v26-26-10,10>>^ Os cascos dos cavalos dele encherão a cidade de poeira, e o barulho dos condutores e dos carros de guerra fará estremecer os muros quando passarem por suas portas quebradas.

[[v26-26-11]]

^<<v26-26-11,11>>^ Os cavaleiros pisotearão todas as ruas da cidade. Matarão seu povo à espada, e suas fortes colunas cairão.

[[v26-26-12]]

^<<v26-26-12,12>>^ "Saquearão todas as suas riquezas e mercadorias e derrubarão seus muros. Destruirão suas lindas casas e lançarão ao mar suas pedras, suas vigas de madeira e até mesmo seu pó.

[[v26-26-13]]

^<<v26-26-13,13>>^ Acabarei com a música de seus cânticos, e não se ouvirá mais o som da harpa no meio de seu povo.

[[v26-26-14]]

^<<v26-26-14,14>>^ Transformarei sua ilha em rocha bruta, um lugar para os pescadores estenderem suas redes. Você jamais será reconstruída, pois eu, o SENHOR, falei. Sim, o SENHOR Soberano falou!"

[[v26-26-15]]

^<<v26-26-15,15>>^ "Assim diz o SENHOR Soberano à cidade de Tiro: Todo o litoral estremecerá com o estrondo de sua queda, enquanto os feridos gemem durante a matança.

[[v26-26-16]]

^<<v26-26-16,16>>^ Os governantes das cidades portuárias descerão de seus tronos e removerão seus mantos e suas belas roupas. Sentarão no chão, tremendo de pavor por causa de sua destruição.

[[v26-26-17]]

^<<v26-26-17,17>>^ Lamentarão por você e entoarão este cântico fúnebre: "Ó famosa cidade da ilha, que governava o mar, como você foi destruída! Seus habitantes, com poder naval, espalhavam medo por todo o mundo.

[[v26-26-18]]

^<<v26-26-18,18>>^ Agora, as regiões litorâneas estremecem com sua queda; as ilhas se apavoram diante de sua ruína.

[[v26-26-19]]

^<<v26-26-19,19>>^ "Assim diz o SENHOR Soberano: Transformarei Tiro em ruínas desabitadas, como muitas outras. Eu a sepultarei debaixo das ondas terríveis, e grandes mares a engolirão.

[[v26-26-20]]

^<<v26-26-20,20>>^ Eu a enviarei à cova, para juntar-se àqueles que desceram até lá há muito tempo. Sua cidade permanecerá em ruínas, sepultada debaixo da terra, como aqueles que estão na cova, que entraram no mundo dos mortos. Você já não terá lugar na terra dos vivos.

[[v26-26-21]]

^<<v26-26-21,21>>^ Eu lhe darei um fim terrível, e você deixará de existir. Procurarão por você, mas nunca mais a encontrarão. Eu, o SENHOR Soberano, falei!".

'''

xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[&#60; Capítulo Anterior] | <<v26-26-0,Topo>> | xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[Próximo Capítulo &#62;]