include::./index.adoc[]

[[v26-44-0]]
=== Ezequiel, 44
// nvt ?, NVT - Nova Versão Transformadora

[[v26-44-1]]

^<<v26-44-1,1>>^ Depois disso, o homem me levou de volta à porta leste no muro externo do templo, mas ela estava fechada.

[[v26-44-2]]

^<<v26-44-2,2>>^ Então o SENHOR me disse: "Esta porta deve permanecer fechada; nunca mais será aberta. Ninguém jamais a abrirá nem passará por ela, pois o SENHOR, o Deus de Israel, entrou por ela. Portanto, permanecerá sempre fechada.

[[v26-44-3]]

^<<v26-44-3,3>>^ Somente o príncipe pode sentar-se junto a essa entrada para comer na presença do SENHOR. Mas só pode entrar e sair pelo pórtico da entrada".

[[v26-44-4]]

^<<v26-44-4,4>>^ Então o homem me levou para a frente do templo, passando pela porta norte. Olhei e vi a glória do SENHOR encher o templo do SENHOR, e prostrei-me com o rosto no chão.

[[v26-44-5]]

^<<v26-44-5,5>>^ Então o SENHOR me disse: "Filho do homem, preste atenção. Use seus olhos e seus ouvidos e escute atentamente tudo que lhe digo acerca das regras no templo do SENHOR. Observe com atenção os procedimentos para o uso das entradas e saídas do templo.

[[v26-44-6]]

^<<v26-44-6,6>>^ E transmita a esses rebeldes, o povo de Israel, esta mensagem do SENHOR Soberano: Ó povo de Israel, basta de seus pecados detestáveis!

[[v26-44-7]]

^<<v26-44-7,7>>^ Vocês trouxeram estrangeiros incircuncisos para dentro de meu santuário, gente incircuncisa de corpo e coração. Com isso, profanaram meu templo enquanto me ofereciam comida, a gordura e o sangue dos sacrifícios. Além de todos os seus outros pecados detestáveis, vocês quebraram minha aliança.

[[v26-44-8]]

^<<v26-44-8,8>>^ Em vez de guardar minhas ordens sobre as coisas sagradas, contrataram estrangeiros para realizar o serviço de meu santuário.

[[v26-44-9]]

^<<v26-44-9,9>>^ "Portanto, assim diz o SENHOR Soberano: Nenhum estrangeiro, nem mesmo aqueles que vivem no meio do povo de Israel, entrará em meu santuário se não tiver sido circuncidado, de corpo e coração.

[[v26-44-10]]

^<<v26-44-10,10>>^ E os homens da tribo de Levi que me abandonaram quando Israel se afastou de mim para adorar ídolos sofrerão as consequências de seus pecados.

[[v26-44-11]]

^<<v26-44-11,11>>^ Ainda poderão ser guardas do templo e das portas, poderão abater os animais trazidos para os holocaustos e estar presentes para servir o povo.

[[v26-44-12]]

^<<v26-44-12,12>>^ Contudo, incentivaram o povo a adorar ídolos e fizeram Israel cair em pecado profundo. Por isso, jurei solenemente que eles sofrerão as consequências de seus pecados, diz o SENHOR Soberano.

[[v26-44-13]]

^<<v26-44-13,13>>^ Não se aproximarão de mim para me servir como sacerdotes. Não tocarão em nenhuma das minhas coisas sagradas nem nas ofertas sagradas, pois carregarão a vergonha de todos os pecados detestáveis que cometeram.

[[v26-44-14]]

^<<v26-44-14,14>>^ Cuidarão do templo e serão encarregados do trabalho de manutenção e dos serviços gerais.

[[v26-44-15]]

^<<v26-44-15,15>>^ "Contudo, os sacerdotes levitas da família de Zadoque continuaram a servir fielmente no templo quando Israel me abandonou. Eles me servirão; estarão em minha presença e oferecerão a gordura e o sangue dos sacrifícios, diz o SENHOR Soberano.

[[v26-44-16]]

^<<v26-44-16,16>>^ Somente eles entrarão em meu santuário e se aproximarão de minha mesa para me servir. Eles cumprirão todas as minhas ordens.

[[v26-44-17]]

^<<v26-44-17,17>>^ "Quando entrarem pela porta para o pátio interno, vestirão somente roupas de linho. Não usarão veste alguma de lã enquanto estiverem de serviço no pátio interno ou no templo propriamente dito.

[[v26-44-18]]

^<<v26-44-18,18>>^ Usarão turbantes de linho e as roupas de baixo de linho. Nunca vestirão roupas que os façam transpirar.

[[v26-44-19]]

^<<v26-44-19,19>>^ Quando voltarem ao pátio externo, onde o povo está, removerão as vestes que usam enquanto me servem. Deixarão essas vestes nas salas sagradas e vestirão outras roupas, a fim de não colocar ninguém em perigo ao consagrá-lo indevidamente por meio das vestes.

[[v26-44-20]]

^<<v26-44-20,20>>^ "Não rasparão a cabeça nem deixarão o cabelo comprido demais; antes, o manterão aparado.

[[v26-44-21]]

^<<v26-44-21,21>>^ Os sacerdotes não beberão vinho antes de entrar no pátio interno.

[[v26-44-22]]

^<<v26-44-22,22>>^ Poderão escolher a esposa somente entre as virgens de Israel ou entre as viúvas dos sacerdotes. Não se casarão com outras viúvas nem com mulheres divorciadas.

[[v26-44-23]]

^<<v26-44-23,23>>^ Ensinarão meu povo a diferença entre sagrado e profano, entre cerimonialmente puro e impuro.

[[v26-44-24]]

^<<v26-44-24,24>>^ "Servirão como juízes para resolver desentendimentos entre membros de meu povo. Suas decisões serão baseadas em meus estatutos. E eles mesmos obedecerão às minhas instruções e aos meus decretos em todas as festas sagradas e se certificarão de que meus sábados sejam separados como dias santos.

[[v26-44-25]]

^<<v26-44-25,25>>^ "O sacerdote não deverá se contaminar por se aproximar de uma pessoa morta, a menos que seja seu pai, sua mãe, seu filho, sua filha, seu irmão ou sua irmã não casada. Nesses casos, será permitido que se torne impuro.

[[v26-44-26]]

^<<v26-44-26,26>>^ Mesmo assim, só poderá retomar seus deveres no templo depois de se purificar cerimonialmente e esperar sete dias.

[[v26-44-27]]

^<<v26-44-27,27>>^ No primeiro dia em que voltar ao trabalho e entrar no pátio interno e no santuário, apresentará uma oferta pelo pecado por si mesmo, diz o SENHOR Soberano.

[[v26-44-28]]

^<<v26-44-28,28>>^ "Os sacerdotes não terão propriedades nem porção alguma de terra, pois eu sou sua herança.

[[v26-44-29]]

^<<v26-44-29,29>>^ Seu alimento virá das ofertas e dos sacrifícios que os israelitas trouxerem para o templo: as ofertas de cereal, as ofertas pelo pecado e as ofertas pela culpa. Tudo que for consagrado para o SENHOR pertencerá aos sacerdotes.

[[v26-44-30]]

^<<v26-44-30,30>>^ Os primeiros frutos maduros e todas as ofertas trazidas irão para os sacerdotes. As primeiras porções serão entregues aos sacerdotes, para que os lares de vocês sejam abençoados.

[[v26-44-31]]

^<<v26-44-31,31>>^ Os sacerdotes não comerão carne de qualquer ave ou animal que morrer de causas naturais ou que for morto por outro animal."

'''

xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[&#60; Capítulo Anterior] | <<v26-44-0,Topo>> | xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[Próximo Capítulo &#62;]