include::./index.adoc[]

[[v26-14-0]]
=== Ezequiel, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v26-14-1]]

^<<v26-14-1,1>>^ Então alguns dos líderes de Israel me visitaram e, enquanto estavam sentados comigo,

[[v26-14-2]]

^<<v26-14-2,2>>^ recebi esta mensagem do SENHOR:

[[v26-14-3]]

^<<v26-14-3,3>>^ "Filho do homem, esses homens levantaram ídolos em seu coração e seguem coisas que os farão cair em pecado. Por que eu ouviria os pedidos deles?

[[v26-14-4]]

^<<v26-14-4,4>>^ Por isso, diga-lhes: ‘Assim diz o SENHOR Soberano: O povo de Israel levanta ídolos em seu coração e cai em pecado, e depois vai consultar um profeta. Portanto, eu, o SENHOR, lhes darei o tipo de resposta que sua grande idolatria merece.

[[v26-14-5]]

^<<v26-14-5,5>>^ Farei isso para conquistar o coração de todo o meu povo, que se afastou de mim para seguir ídolos’.

[[v26-14-6]]

^<<v26-14-6,6>>^ "Portanto, diga ao povo de Israel: ‘Assim diz o SENHOR Soberano: Arrependam-se e afastem-se de seus ídolos; parem de cometer pecados detestáveis!

[[v26-14-7]]

^<<v26-14-7,7>>^ Pois eu, o SENHOR, responderei a todos, tanto israelitas como estrangeiros, que se afastam de mim, levantam ídolos em seu coração e, desse modo, caem em pecado, e depois procuram um profeta para me consultar.

[[v26-14-8]]

^<<v26-14-8,8>>^ Eu me voltarei contra essas pessoas e farei delas um exemplo ao eliminá-las do meio de meu povo. Então vocês saberão que eu sou o SENHOR.

[[v26-14-9]]

^<<v26-14-9,9>>^ "‘E, se um profeta é enganado e levado a transmitir uma mensagem, é porque eu, o SENHOR, o enganei. Levantarei minha mão contra esses profetas e os eliminarei do meio de Israel.

[[v26-14-10]]

^<<v26-14-10,10>>^ Tanto os falsos profetas como os que buscam a orientação deles serão castigados por seus pecados.

[[v26-14-11]]

^<<v26-14-11,11>>^ Assim, o povo de Israel aprenderá a não se desviar mais de mim nem se contaminar com todos os seus pecados. Eles serão o meu povo, e eu serei o seu Deus. Eu, o SENHOR Soberano, falei!’".

[[v26-14-12]]

^<<v26-14-12,12>>^ Então recebi esta mensagem do SENHOR:

[[v26-14-13]]

^<<v26-14-13,13>>^ "Filho do homem, suponhamos que o povo de uma terra tivesse pecado contra mim, e eu levantasse minha mão para esmagá-lo, cortasse seu suprimento de comida e enviasse fome para destruir tanto pessoas como animais.

[[v26-14-14]]

^<<v26-14-14,14>>^ Mesmo que Noé, Daniel e Jó estivessem ali, sua justiça não salvaria ninguém a não ser eles mesmos, diz o SENHOR Soberano.

[[v26-14-15]]

^<<v26-14-15,15>>^ "Ou suponhamos que eu enviasse animais selvagens para invadir a nação e tornar a terra tão desolada e perigosa que ninguém poderia passar por ela.

[[v26-14-16]]

^<<v26-14-16,16>>^ Tão certo como eu vivo, diz o SENHOR Soberano, mesmo que esses três homens estivessem ali, não seriam capazes de salvar seus filhos nem suas filhas. Apenas eles seriam salvos, mas a terra seria arrasada.

[[v26-14-17]]

^<<v26-14-17,17>>^ "Ou suponhamos que eu trouxesse guerra contra a terra e enviasse exércitos inimigos para destruir tanto pessoas como animais.

[[v26-14-18]]

^<<v26-14-18,18>>^ Tão certo como eu vivo, diz o SENHOR Soberano, mesmo que esses três homens estivessem ali, não seriam capazes de salvar seus filhos nem suas filhas. Apenas eles seriam salvos.

[[v26-14-19]]

^<<v26-14-19,19>>^ "Ou suponhamos que eu derramasse minha fúria ao enviar uma epidemia sobre a terra e essa doença matasse tanto pessoas como animais.

[[v26-14-20]]

^<<v26-14-20,20>>^ Tão certo como eu vivo, diz o SENHOR Soberano, ainda que Noé, Daniel e Jó estivessem ali, não seriam capazes de salvar seus filhos nem suas filhas. Somente eles seriam salvos por sua justiça.

[[v26-14-21]]

^<<v26-14-21,21>>^ "Agora, assim diz o SENHOR Soberano: Como será terrível quando esses quatro castigos terríveis — guerra, fome, animais selvagens e doença — caírem sobre Jerusalém e destruírem todo o seu povo e seus animais!

[[v26-14-22]]

^<<v26-14-22,22>>^ Contudo, haverá sobreviventes, que se juntarão a vocês no exílio na Babilônia. Vocês verão com os próprios olhos como eles são perversos e se sentirão consolados diante da calamidade que eu trouxe sobre Jerusalém.

[[v26-14-23]]

^<<v26-14-23,23>>^ Quando se encontrarem com eles, entenderão que não foi sem motivo que fiz essas coisas a Israel. Eu, o SENHOR Soberano, falei!".

'''

xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[&#60; Capítulo Anterior] | <<v26-14-0,Topo>> | xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[Próximo Capítulo &#62;]