include::./index.adoc[]

[[v26-40-0]]
=== Ezequiel, 40
// nvt ?, NVT - Nova Versão Transformadora

[[v26-40-1]]

^<<v26-40-1,1>>^ Em 28 de abril, no vigésimo quinto ano de nosso exílio, catorze anos depois da queda de Jerusalém, a mão do SENHOR veio sobre mim, e ele me levou para lá.

[[v26-40-2]]

^<<v26-40-2,2>>^ Numa visão, Deus me levou para a terra de Israel e me colocou num monte muito alto. Dali, vi em direção ao sul algo parecido com uma cidade.

[[v26-40-3]]

^<<v26-40-3,3>>^ Quando ele me levou mais perto, vi um homem cuja face brilhava como bronze. Ele estava em pé junto a uma porta e tinha na mão uma corda de medir feita de linho e uma vara de medir.

[[v26-40-4]]

^<<v26-40-4,4>>^ Disse-me: "Filho do homem, observe e ouça. Preste muita atenção a tudo que lhe mostrarei. Você foi trazido aqui para que eu lhe mostre várias coisas. Depois você voltará ao povo de Israel e contará tudo que vir".

[[v26-40-5]]

^<<v26-40-5,5>>^ Vi um muro que cercava completamente a área do templo. O homem pegou a vara de medir de 3 metros de comprimento e com ela mediu o muro, que tinha 3 metros de espessura e 3 metros de altura.

[[v26-40-6]]

^<<v26-40-6,6>>^ Em seguida, foi à porta leste. Subiu os degraus e mediu a soleira da porta, que tinha 3 metros de profundidade.

[[v26-40-7]]

^<<v26-40-7,7>>^ Na passagem de entrada, havia salas para guardas de cada lado. Cada uma das salas era quadrada e media 3 metros de cada lado, e a distância entre as salas era de 2,5 metros ao longo da parede da passagem. A soleira interna da porta, que dava para o pórtico na extremidade interna da passagem de entrada, tinha 3 metros de profundidade.

[[v26-40-8]]

^<<v26-40-8,8>>^ Ele também mediu o pórtico.

[[v26-40-9]]

^<<v26-40-9,9>>^ Tinha 4 metros de extensão e suas colunas tinham 1 metro de espessura. Esse pórtico era a extremidade interna da passagem de entrada e era voltado para o templo.

[[v26-40-10]]

^<<v26-40-10,10>>^ Havia três salas de cada lado da passagem de entrada. Cada uma tinha as mesmas medidas, e as paredes entre elas também eram idênticas.

[[v26-40-11]]

^<<v26-40-11,11>>^ Então o homem mediu a porta de entrada, que tinha 5 metros de largura e 6,5 metros de comprimento na passagem.

[[v26-40-12]]

^<<v26-40-12,12>>^ Em frente de cada sala havia uma mureta com 0,5 metro de altura. As salas propriamente ditas tinham 3 metros de cada lado.

[[v26-40-13]]

^<<v26-40-13,13>>^ Então ele mediu toda a largura da porta, a distância desde a parede dos fundos de uma sala para guardas até a parede dos fundos de outra sala; essa distância era de 12,5 metros.

[[v26-40-14]]

^<<v26-40-14,14>>^ Mediu as paredes divisórias ao longo de todo o interior da passagem até o pórtico; a distância era de 30 metros.

[[v26-40-15]]

^<<v26-40-15,15>>^ O comprimento total da passagem, de uma extremidade à outra, era de 25 metros.

[[v26-40-16]]

^<<v26-40-16,16>>^ Nas paredes das salas e em suas paredes divisórias havia janelas embutidas que se estreitavam em direção à parte interna. Também havia janelas no pórtico. As superfícies das paredes divisórias eram enfeitadas com entalhes de palmeiras.

[[v26-40-17]]

^<<v26-40-17,17>>^ Então o homem me levou pela entrada até o pátio externo do templo. Ao longo das paredes do pátio havia uma calçada e, junto às paredes, havia trinta salas que abriam para a calçada.

[[v26-40-18]]

^<<v26-40-18,18>>^ A calçada ladeava as portas, e seu comprimento desde os muros até o pátio era o mesmo da passagem de entrada. Essa era a calçada inferior.

[[v26-40-19]]

^<<v26-40-19,19>>^ Em seguida, o homem mediu a largura do pátio externo do templo, entre a entrada externa e a interna, e a distância era de 50 metros.

[[v26-40-20]]

^<<v26-40-20,20>>^ O homem mediu a porta norte da mesma forma que a leste.

[[v26-40-21]]

^<<v26-40-21,21>>^ Também ali havia três salas e um pórtico. Todas as medidas eram iguais às da porta leste. A passagem da entrada tinha 25 metros de comprimento e 12,5 metros de largura entre as paredes dos fundos de uma sala para guardas e a parede dos fundos de outra sala.

[[v26-40-22]]

^<<v26-40-22,22>>^ As janelas, o pórtico e os enfeites de palmeiras eram idênticos aos da porta leste. Havia sete degraus que davam para a passagem da entrada, e o pórtico ficava na extremidade interna da passagem de entrada.

[[v26-40-23]]

^<<v26-40-23,23>>^ Do lado norte, como do lado leste, havia outra porta que dava para o pátio interno do templo, oposta à entrada externa. A distância entre as duas entradas era de 50 metros.

[[v26-40-24]]

^<<v26-40-24,24>>^ Então o homem me levou à porta sul e mediu suas partes, e eram exatamente iguais às medidas das outras portas.

[[v26-40-25]]

^<<v26-40-25,25>>^ Tinha janelas ao longo das paredes, como as outras, e um pórtico no qual a passagem de entrada abria para o pátio externo. E, como nas outras portas, a passagem de entrada tinha 25 metros de comprimento e 12,5 metros de largura.

[[v26-40-26]]

^<<v26-40-26,26>>^ Essa entrada também tinha uma escada com sete degraus que davam para ela, um pórtico na extremidade interna e enfeites de palmeiras nas paredes divisórias.

[[v26-40-27]]

^<<v26-40-27,27>>^ E aqui também havia outra entrada que dava para o pátio interno, oposta à entrada externa. A distância entre as duas entradas era de 50 metros.

[[v26-40-28]]

^<<v26-40-28,28>>^ Então o homem me levou à porta sul, que dava para o pátio interno. Ele a mediu, e tinha as mesmas medidas das outras portas.

[[v26-40-29]]

^<<v26-40-29,29>>^ Suas salas para guardas, suas paredes divisórias e seu pórtico eram do mesmo tamanho das outras portas, e havia janelas ao longo das paredes e no pórtico. E, como nas outras portas, a passagem da entrada tinha 25 metros de comprimento e 12,5 metros de largura.

[[v26-40-30]]

^<<v26-40-30,30>>^ (Os pórticos que davam para o pátio interno tinham 4 metros de comprimento e 12,5 metros de largura.)

[[v26-40-31]]

^<<v26-40-31,31>>^ O pórtico da porta sul ficava voltado para o pátio externo. Suas colunas eram enfeitadas com palmeiras, e oito degraus subiam até sua entrada.

[[v26-40-32]]

^<<v26-40-32,32>>^ Então ele me levou à porta leste, que dava para o pátio interno. Ele a mediu, e tinha as mesmas medidas das outras portas.

[[v26-40-33]]

^<<v26-40-33,33>>^ Suas salas para guardas, suas paredes divisórias e seu pórtico eram do mesmo tamanho das outras portas, e havia janelas ao longo das paredes e no pórtico. A passagem da entrada tinha 25 metros de comprimento e 12,5 metros de largura.

[[v26-40-34]]

^<<v26-40-34,34>>^ Seu pórtico ficava voltado para o pátio externo. Suas colunas eram enfeitadas com palmeiras, e oito degraus subiam até sua entrada.

[[v26-40-35]]

^<<v26-40-35,35>>^ Então ele me levou à porta norte, que dava para o pátio interno. Ele a mediu, e tinha as mesmas medidas das outras portas.

[[v26-40-36]]

^<<v26-40-36,36>>^ Suas salas para guardas, suas paredes divisórias e seu pórtico tinham as mesmas medidas das outras portas e janelas dispostas da mesma forma. A entrada da passagem tinha 25 metros de comprimento e 12,5 metros de largura.

[[v26-40-37]]

^<<v26-40-37,37>>^ Seu pórtico ficava voltado para o pátio externo. Suas colunas eram enfeitadas com palmeiras, e oito degraus subiam até sua entrada.

[[v26-40-38]]

^<<v26-40-38,38>>^ No pórtico de uma das entradas internas havia uma porta que dava para uma sala lateral onde era lavada a carne para os holocaustos.

[[v26-40-39]]

^<<v26-40-39,39>>^ De cada lado desse pórtico havia duas mesas onde os animais para os sacrifícios eram abatidos para os holocaustos, as ofertas pelo pecado e as ofertas pela culpa.

[[v26-40-40]]

^<<v26-40-40,40>>^ Do lado de fora do pórtico, de cada lado das escadas que subiam para a entrada norte, havia mais duas mesas.

[[v26-40-41]]

^<<v26-40-41,41>>^ Havia, portanto, oito mesas no total, quatro do lado de dentro e quatro do lado de fora, onde se abatiam os sacrifícios.

[[v26-40-42]]

^<<v26-40-42,42>>^ Também havia quatro mesas de pedra cortada para o preparo dos holocaustos, cada uma com 75 centímetros de comprimento e de largura e 50 centímetros de altura. Sobre essas mesas eram colocadas os instrumentos para abater os animais para os sacrifícios.

[[v26-40-43]]

^<<v26-40-43,43>>^ Havia ganchos, cada um com 8 centímetros de comprimento, presos ao redor das paredes do pórtico. A carne dos sacrifícios era colocada sobre as mesas.

[[v26-40-44]]

^<<v26-40-44,44>>^ Dentro do pátio interno havia duas salas, uma ao lado da porta norte, voltada para o sul, e outra ao lado da porta sul, voltada para o norte.

[[v26-40-45]]

^<<v26-40-45,45>>^ E o homem me disse: "A sala ao lado da porta norte é para os sacerdotes que supervisionam a manutenção do templo.

[[v26-40-46]]

^<<v26-40-46,46>>^ A sala ao lado da porta sul é para os sacerdotes encarregados do altar, os descendentes de Zadoque, pois somente eles, dentre todos os levitas, podem se aproximar do SENHOR, para servir diante dele".

[[v26-40-47]]

^<<v26-40-47,47>>^ Então o homem mediu o pátio interno, e era um quadrado com 50 metros de largura e 50 metros de comprimento. O altar ficava no pátio em frente ao templo.

[[v26-40-48]]

^<<v26-40-48,48>>^ Então ele me levou ao pórtico do templo. Mediu as paredes de ambos os lados da passagem para o pórtico, e tinham 2,5 metros de espessura. A entrada propriamente dita tinha 7 metros de largura, e as paredes de cada lado da entrada tinham mais 1,5 metros de comprimento.

[[v26-40-49]]

^<<v26-40-49,49>>^ O pórtico tinha 10 metros de largura e 6 metros de profundidade. Dez degraus subiam para ele, com uma coluna de cada lado.

'''

xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[&#60; Capítulo Anterior] | <<v26-40-0,Topo>> | xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[Próximo Capítulo &#62;]