include::./index.adoc[]

[[v26-35-0]]
=== Ezequiel, 35
// nvt ?, NVT - Nova Versão Transformadora

[[v26-35-1]]

^<<v26-35-1,1>>^ Recebi outra mensagem do SENHOR:

[[v26-35-2]]

^<<v26-35-2,2>>^ "Filho do homem, volte o rosto para o monte Seir e profetize contra seu povo.

[[v26-35-3]]

^<<v26-35-3,3>>^ Transmita-lhe esta mensagem do SENHOR Soberano: "Sou seu inimigo, ó monte Seir; levantarei minha mão contra você para destruí-lo completamente.

[[v26-35-4]]

^<<v26-35-4,4>>^ Transformarei suas cidades em ruínas e as deixarei desoladas. Então você saberá que eu sou o SENHOR.

[[v26-35-5]]

^<<v26-35-5,5>>^ "Seu ódio profundo dos israelitas o levou a matá-los quando estavam indefesos, quando eu já os havia castigado por todos os seus pecados.

[[v26-35-6]]

^<<v26-35-6,6>>^ Tão certo como eu vivo, diz o SENHOR Soberano, visto que vocês não mostraram aversão alguma ao sangue derramado, eu derramarei o seu sangue. Sua vez chegou!

[[v26-35-7]]

^<<v26-35-7,7>>^ Deixarei o monte Seir completamente desolado e matarei todos que tentarem escapar e qualquer um que voltar.

[[v26-35-8]]

^<<v26-35-8,8>>^ Encherei seus montes de cadáveres; suas colinas, seus vales e seus desfiladeiros ficarão cobertos de gente morta à espada.

[[v26-35-9]]

^<<v26-35-9,9>>^ Eu o deixarei desolado para sempre; suas cidades jamais serão reconstruídas. Então você saberá que eu sou o SENHOR.

[[v26-35-10]]

^<<v26-35-10,10>>^ "Pois você disse: ‘As terras de Israel e Judá serão minhas. Sim, tomarei posse delas. Que me importa se o SENHOR está ali?’.

[[v26-35-11]]

^<<v26-35-11,11>>^ Portanto, tão certo como eu vivo, diz o SENHOR Soberano, eu lhe darei o castigo merecido por sua ira, sua inveja e seu ódio. Eu me revelarei a Israel por meio daquilo que fizer a você.

[[v26-35-12]]

^<<v26-35-12,12>>^ Então você saberá que eu, o SENHOR, ouvi todas as palavras de desprezo que você pronunciou contra os montes de Israel. Pois você disse: ‘Estão desolados; foram entregues a mim como alimento!’.

[[v26-35-13]]

^<<v26-35-13,13>>^ Com essas palavras, você se exaltou diante de mim, e eu ouvi tudo!

[[v26-35-14]]

^<<v26-35-14,14>>^ "Assim diz o SENHOR Soberano: O mundo todo se alegrará quando eu o deixar desolado.

[[v26-35-15]]

^<<v26-35-15,15>>^ Você se alegrou com a desolação do território de Israel, e agora me alegrarei com sua desolação. Você, povo no monte Seir, e todos que vivem em Edom serão exterminados! Então saberão que eu sou o SENHOR."

'''

xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[&#60; Capítulo Anterior] | <<v26-35-0,Topo>> | xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[Próximo Capítulo &#62;]