include::./index.adoc[]

[[v26-3-0]]
=== Ezequiel, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v26-3-1]]

^<<v26-3-1,1>>^ A voz me disse: "Filho do homem, coma o que lhe dou. Coma este rolo! Depois, vá e fale ao povo de Israel".

[[v26-3-2]]

^<<v26-3-2,2>>^ Então abri a boca, e ele me deu o rolo para eu comer.

[[v26-3-3]]

^<<v26-3-3,3>>^ "Filho do homem, encha seu estômago com ele", disse a voz. Quando comi, o sabor era doce como mel em minha boca.

[[v26-3-4]]

^<<v26-3-4,4>>^ Em seguida, ele disse: "Filho do homem, vá ao povo de Israel e transmita-lhe minhas mensagens.

[[v26-3-5]]

^<<v26-3-5,5>>^ Não o envio a um povo estrangeiro, cuja língua você não entende, mas ao povo de Israel.

[[v26-3-6]]

^<<v26-3-6,6>>^ Não, eu não o envio a um povo de língua estrangeira e difícil. Se o fizesse, eles lhe dariam ouvidos!

[[v26-3-7]]

^<<v26-3-7,7>>^ O povo de Israel, porém, não lhe dará ouvidos, assim como não deu ouvidos a mim. Pois todos eles têm o coração duro e são teimosos.

[[v26-3-8]]

^<<v26-3-8,8>>^ Mas eu tornei você tão obstinado e inflexível quanto eles.

[[v26-3-9]]

^<<v26-3-9,9>>^ Endureci sua testa como a pedra mais dura. Portanto, não tenha medo deles nem tema seus olhares raivosos, pois são um povo rebelde".

[[v26-3-10]]

^<<v26-3-10,10>>^ Então ele acrescentou: "Filho do homem, primeiro deixe que minhas palavras entrem até o fundo de seu coração. Ouça-as com atenção.

[[v26-3-11]]

^<<v26-3-11,11>>^ Depois, vá a seu povo no exílio e diga-lhes: ‘Assim diz o SENHOR Soberano!’. Faça isso quer eles ouçam quer não".

[[v26-3-12]]

^<<v26-3-12,12>>^ Em seguida, o Espírito me pôs em pé, e eu ouvi uma estrondosa proclamação atrás de mim. (Que a glória do SENHOR seja louvada em sua habitação!)

[[v26-3-13]]

^<<v26-3-13,13>>^ Era o som das asas dos seres vivos que tocavam umas nas outras e o barulho das rodas debaixo deles.

[[v26-3-14]]

^<<v26-3-14,14>>^ O Espírito me levantou e me tirou de lá. Saí amargurado e agitado, mas a mão do SENHOR era forte sobre mim.

[[v26-3-15]]

^<<v26-3-15,15>>^ Cheguei à colônia dos exilados judeus em Tel-Abibe, junto ao rio Quebar. Estava atônito e permaneci no meio deles durante sete dias.

[[v26-3-16]]

^<<v26-3-16,16>>^ Depois de sete dias, o SENHOR me deu uma mensagem:

[[v26-3-17]]

^<<v26-3-17,17>>^ "Filho do homem, eu o nomeei vigia de Israel. Sempre que receber uma mensagem minha, advirta o povo.

[[v26-3-18]]

^<<v26-3-18,18>>^ Se eu avisar os perversos: ‘Vocês estão condenados à morte’, mas você não lhes transmitir a advertência, para que mudem sua conduta perversa e salvem a vida, eles morrerão em seus pecados. E eu o considerarei responsável pela morte deles.

[[v26-3-19]]

^<<v26-3-19,19>>^ Se você os advertir, mas eles não quiserem se arrepender e continuarem a pecar, eles morrerão em seus pecados. Você, porém, salvará sua vida.

[[v26-3-20]]

^<<v26-3-20,20>>^ "Se os justos se desviarem de sua conduta justa e não prestarem atenção aos obstáculos que eu puser em seu caminho, eles morrerão. E, se você não os advertir, eles morrerão em seus pecados. Nenhum dos atos de justiça deles será lembrado, e eu o considerarei responsável pela morte deles.

[[v26-3-21]]

^<<v26-3-21,21>>^ Mas, se você advertir os justos a não pecarem e eles lhe derem ouvidos e não pecarem, eles viverão. E você também salvará sua vida".

[[v26-3-22]]

^<<v26-3-22,22>>^ A mão do SENHOR veio sobre mim, e ele disse: "Levante-se e vá até o vale, e eu lhe falarei ali".

[[v26-3-23]]

^<<v26-3-23,23>>^ Levantei-me, fui até o vale e ali vi a glória do SENHOR, como na primeira visão junto ao rio Quebar, e prostrei-me com o rosto no chão.

[[v26-3-24]]

^<<v26-3-24,24>>^ Então o Espírito entrou em mim e me pôs em pé. "Vá para sua casa e tranque-se dentro dela", disse ele.

[[v26-3-25]]

^<<v26-3-25,25>>^ "Ali, filho do homem, você será amarrado com cordas e não poderá sair para o meio do povo.

[[v26-3-26]]

^<<v26-3-26,26>>^ Farei sua língua se prender ao céu da boca, para que fique mudo e não possa repreendê-los, pois são rebeldes.

[[v26-3-27]]

^<<v26-3-27,27>>^ Mas, quando eu lhe der uma mensagem, desprenderei sua língua e deixarei que fale. Então você lhes dirá: ‘Assim diz o SENHOR Soberano!’. Quem escolher ouvir, ouvirá, mas quem se recusar, não ouvirá, pois são um povo rebelde."

'''

xref:026-ezequiel/026-ezequiel-002.adoc#v26-2-0[&#60; Capítulo Anterior] | <<v26-3-0,Topo>> | xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[Próximo Capítulo &#62;]