include::./index.adoc[]

[[v26-46-0]]
=== Ezequiel, 46
// nvt ?, NVT - Nova Versão Transformadora

[[v26-46-1]]

^<<v26-46-1,1>>^ "Assim diz o SENHOR Soberano: A porta leste do pátio interno ficará fechada durante os seis dias de trabalho da semana, mas será aberta aos sábados e nas comemorações da lua nova.

[[v26-46-2]]

^<<v26-46-2,2>>^ O príncipe entrará pelo pórtico da entrada, vindo de fora. Ficará em pé junto ao batente da porta enquanto o sacerdote apresenta os holocaustos e as ofertas de paz. Ele se curvará em adoração na passagem de entrada e depois sairá por onde entrou. A porta não será fechada até a tarde.

[[v26-46-3]]

^<<v26-46-3,3>>^ O povo se curvará e adorará o SENHOR junto a essa porta aos sábados e nas comemorações da lua nova.

[[v26-46-4]]

^<<v26-46-4,4>>^ "A cada sábado o príncipe apresentará ao SENHOR um holocausto de seis cordeiros e um carneiro, todos sem defeito.

[[v26-46-5]]

^<<v26-46-5,5>>^ Apresentará uma oferta de cereal de um cesto de farinha com o carneiro e a quantidade de farinha que puder com cada cordeiro; também oferecerá um jarro de azeite para cada cesto de farinha.

[[v26-46-6]]

^<<v26-46-6,6>>^ Nas comemorações da lua nova, trará um novilho, seis cordeiros e um carneiro, todos sem defeito.

[[v26-46-7]]

^<<v26-46-7,7>>^ Junto com o novilho, apresentará um cesto de farinha da melhor qualidade como oferta de cereal. Junto com o carneiro, apresentará outro cesto de farinha. E, junto com cada cordeiro, apresentará a quantidade de farinha que desejar. Para cada cesto de farinha, oferecerá um jarro de azeite.

[[v26-46-8]]

^<<v26-46-8,8>>^ "Quando o príncipe entrar, virá pelo pórtico e sairá por onde entrou.

[[v26-46-9]]

^<<v26-46-9,9>>^ Mas, quando o povo entrar pela porta norte para adorar o SENHOR durante as festas religiosas, sairá pela porta sul. E quem entrar pela porta sul sairá pela porta norte. Ninguém sairá pela mesma porta por onde entrou, mas sempre pela porta oposta.

[[v26-46-10]]

^<<v26-46-10,10>>^ O príncipe entrará e sairá com o povo nessas ocasiões.

[[v26-46-11]]

^<<v26-46-11,11>>^ "Portanto, nas festas especiais e nas festas sagradas, a oferta de cereal será um cesto de farinha da melhor qualidade para cada novilho, mais outro cesto de farinha para cada carneiro e a quantidade de farinha que o adorador desejar oferecer com cada cordeiro. Para cada cesto de farinha será apresentado um jarro de azeite.

[[v26-46-12]]

^<<v26-46-12,12>>^ Quando o príncipe oferecer voluntariamente ao SENHOR um holocausto ou uma oferta de paz, a porta leste do pátio interno será aberta para ele, e ele oferecerá os sacrifícios como faz aos sábados. Então ele sairá e a porta será fechada.

[[v26-46-13]]

^<<v26-46-13,13>>^ "A cada manhã, vocês oferecerão um cordeiro de um ano sem defeito como holocausto ao SENHOR.

[[v26-46-14]]

^<<v26-46-14,14>>^ Junto com ele, apresentarão ao SENHOR uma oferta de cereal com a sexta parte de um cesto de farinha e um terço do jarro de azeite para umedecer a farinha da melhor qualidade. Este será um decreto permanente para vocês.

[[v26-46-15]]

^<<v26-46-15,15>>^ O cordeiro, a oferta de cereal e o azeite devem ser apresentados como sacrifício diário a cada manhã, sem falta.

[[v26-46-16]]

^<<v26-46-16,16>>^ "Assim diz o SENHOR Soberano: Se o príncipe der um pedaço de terra para um de seus filhos como herança, pertencerá a ele e a seus descendentes para sempre.

[[v26-46-17]]

^<<v26-46-17,17>>^ Mas, se o príncipe der um pedaço de terra de sua herança para um de seus servos, o servo a manterá apenas até o Ano do Jubileu. Nessa ocasião, a terra voltará para o príncipe. Contudo, aquilo que o príncipe der a seus filhos será permanente.

[[v26-46-18]]

^<<v26-46-18,18>>^ Além disso, o príncipe não poderá tomar a propriedade de ninguém à força. Se ele der propriedades a seus filhos, terão de ser de suas próprias terras, pois não quero que meu povo seja despejado de suas propriedades".

[[v26-46-19]]

^<<v26-46-19,19>>^ Depois disso, o homem me levou pela entrada ao lado da porta e me conduziu às salas sagradas reservadas para os sacerdotes e que ficavam voltadas para o norte. Mostrou-me um lugar na extremidade oeste dessas salas

[[v26-46-20]]

^<<v26-46-20,20>>^ e explicou: "Aqui os sacerdotes cozinharão a carne das ofertas pela culpa e das ofertas pelo pecado e assarão o pão feito com a farinha das ofertas de cereal. Farão isso aqui para não ter de carregar os sacrifícios pelo pátio externo e correr o risco de consagrar o povo indevidamente".

[[v26-46-21]]

^<<v26-46-21,21>>^ Então ele me levou de volta ao pátio externo e me conduziu a cada um de seus quatro cantos. Em cada canto vi uma área cercada.

[[v26-46-22]]

^<<v26-46-22,22>>^ Cada uma dessas áreas cercadas tinha 20 metros de comprimento e 15 metros de largura e era rodeada por um muro.

[[v26-46-23]]

^<<v26-46-23,23>>^ Ao longo da parte interna desses muros havia uma saliência de pedra, com lugares para acender fogo debaixo da saliência, em todo o redor.

[[v26-46-24]]

^<<v26-46-24,24>>^ O homem me disse: "Estas são as cozinhas onde os assistentes do templo cozinharão os sacrifícios oferecidos pelo povo".

'''

xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[&#60; Capítulo Anterior] | <<v26-46-0,Topo>> | xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[Próximo Capítulo &#62;]