include::./index.adoc[]

[[v26-48-0]]
=== Ezequiel, 48
// nvt ?, NVT - Nova Versão Transformadora

[[v26-48-1]]

^<<v26-48-1,1>>^ "Aqui está a lista das tribos de Israel e dos territórios que cada uma delas receberá. O território de Dã fica no extremo norte. Sua divisa segue a estrada de Hetlom até Lebo-Hamate e, de lá, para Hazar-Enã, na fronteira de Damasco, e com Hamate ao norte. O território de Dã se estende pela terra de Israel de leste a oeste.

[[v26-48-2]]

^<<v26-48-2,2>>^ "O território de Aser fica ao sul do território de Dã e também se estende de leste a oeste.

[[v26-48-3]]

^<<v26-48-3,3>>^ A terra de Naftali fica ao sul da terra de Aser e também se estende de leste a oeste.

[[v26-48-4]]

^<<v26-48-4,4>>^ Em seguida vem Manassés, ao sul de Naftali, e seu território também se estende de leste a oeste.

[[v26-48-5]]

^<<v26-48-5,5>>^ Ao sul de Manassés fica Efraim,

[[v26-48-6]]

^<<v26-48-6,6>>^ depois vem Rúben

[[v26-48-7]]

^<<v26-48-7,7>>^ e, em seguida, Judá, todos com divisas que se estendem de leste a oeste.

[[v26-48-8]]

^<<v26-48-8,8>>^ "Ao sul de Judá fica a terra separada para um propósito especial. Ela terá 12,5 quilômetros de largura e terá as mesmas fronteiras a leste e a oeste que os territórios das tribos. No centro dela estará o templo.

[[v26-48-9]]

^<<v26-48-9,9>>^ "A área separada para o SENHOR terá 12,5 quilômetros de comprimento e 10 quilômetros de largura.

[[v26-48-10]]

^<<v26-48-10,10>>^ Haverá uma faixa de terra para os sacerdotes, com 12,5 quilômetros de comprimento e 5 quilômetros de largura. No centro dela estará o templo do SENHOR.

[[v26-48-11]]

^<<v26-48-11,11>>^ Essa área será separada para os sacerdotes consagrados, os descendentes de Zadoque que me serviram fielmente e que não se desviaram junto com o povo de Israel e com os outros levitas.

[[v26-48-12]]

^<<v26-48-12,12>>^ Essa será sua porção especial quando a terra for distribuída, o território santíssimo. Junto ao território dos sacerdotes ficará a terra onde os outros levitas viverão.

[[v26-48-13]]

^<<v26-48-13,13>>^ "A terra separada para os levitas terá o mesmo tamanho e a mesma forma da terra dos sacerdotes: 12,5 quilômetros de comprimento e 5 quilômetros de largura. Juntas, essas porções de terra terão 12,5 quilômetros de comprimento e 10 quilômetros de largura.

[[v26-48-14]]

^<<v26-48-14,14>>^ Nenhuma porção dessa terra especial poderá ser vendida, trocada ou usada por outros, pois pertence ao SENHOR; é consagrada.

[[v26-48-15]]

^<<v26-48-15,15>>^ "Outra faixa de terra com 12,5 quilômetros de comprimento e 2,5 quilômetros de largura, ao sul da área sagrada do templo, será para uso público: para casas, pastos e terras comuns. No centro dela estará a cidade.

[[v26-48-16]]

^<<v26-48-16,16>>^ A cidade terá 2.250 metros de cada lado: norte, sul, leste e oeste.

[[v26-48-17]]

^<<v26-48-17,17>>^ Em volta da cidade haverá uma área aberta com 125 metros em todas as direções.

[[v26-48-18]]

^<<v26-48-18,18>>^ Fora da cidade haverá uma área para plantações que se estenderá por 5 quilômetros para leste e 5 quilômetros para oeste junto à divisa com a área sagrada. Essa terra de cultivo produzirá alimento para os trabalhadores da cidade.

[[v26-48-19]]

^<<v26-48-19,19>>^ Os que vierem das diversas tribos para trabalharem na cidade poderão cultivar essa terra.

[[v26-48-20]]

^<<v26-48-20,20>>^ A área toda, incluindo as terras sagradas e a cidade, formará um quadrado com 12,5 quilômetros de cada lado.

[[v26-48-21]]

^<<v26-48-21,21>>^ "As áreas que restarem para o leste e para o oeste das terras sagradas e da cidade serão do príncipe. Cada uma dessas áreas terá 12,5 quilômetros de comprimento e se estenderá, em direções opostas, para as fronteiras leste e oeste de Israel. No centro estarão as terras sagradas e o santuário do templo.

[[v26-48-22]]

^<<v26-48-22,22>>^ Portanto, as terras do príncipe incluirão toda a área entre os territórios separados para Judá e para Benjamim, exceto a parte separada para as terras sagradas e para a cidade.

[[v26-48-23]]

^<<v26-48-23,23>>^ "Estes são os territórios separados para as tribos restantes. O território de Benjamim se estende pela terra de Israel de leste a oeste.

[[v26-48-24]]

^<<v26-48-24,24>>^ Ao sul de Benjamim fica o território de Simeão, que também se estende de leste a oeste.

[[v26-48-25]]

^<<v26-48-25,25>>^ Em seguida vem o território de Issacar, com as mesmas divisas a leste e a oeste.

[[v26-48-26]]

^<<v26-48-26,26>>^ "Depois vem o território de Zebulom, que também se estende de leste a oeste.

[[v26-48-27]]

^<<v26-48-27,27>>^ O território de Gade fica ao sul de Zebulom, com as mesmas divisas a leste e a oeste.

[[v26-48-28]]

^<<v26-48-28,28>>^ A fronteira sul de Gade vai de Tamar até as águas de Meribá, em Cades, depois segue o ribeiro do Egito até o Mediterrâneo.

[[v26-48-29]]

^<<v26-48-29,29>>^ "Esses são os territórios que serão distribuídos como herança a cada tribo. Eu, o SENHOR Soberano, falei!"

[[v26-48-30]]

^<<v26-48-30,30>>^ "Estas serão as saídas da cidade: no muro norte, que tem 2.250 metros de comprimento,

[[v26-48-31]]

^<<v26-48-31,31>>^ haverá três saídas, cada uma com o nome de uma das tribos de Israel. A primeira será chamada Rúben, a segunda, Judá, e a terceira, Levi.

[[v26-48-32]]

^<<v26-48-32,32>>^ No muro leste, que também tem 2.250 metros de comprimento, estarão as portas chamadas José, Benjamim e Dã.

[[v26-48-33]]

^<<v26-48-33,33>>^ No muro sul, que também tem 2.250 metros, estarão as portas chamadas Simeão, Issacar e Zebulom.

[[v26-48-34]]

^<<v26-48-34,34>>^ E no muro oeste, que também tem 2.250 metros de comprimento, estarão as portas chamadas Gade, Aser e Naftali.

[[v26-48-35]]

^<<v26-48-35,35>>^ "A distância ao redor de toda a cidade será de 9 quilômetros. E, daquele dia em diante, o nome da cidade será ‘O SENHOR Está Ali’".

'''

xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[&#60; Capítulo Anterior] | <<v26-48-0,Topo>> | xref:027-daniel/027-daniel-001.adoc#v27-1-0[Próximo Capítulo &#62;]