include::./index.adoc[]

[[v26-23-0]]
=== Ezequiel, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v26-23-1]]

^<<v26-23-1,1>>^ Recebi esta mensagem do SENHOR:

[[v26-23-2]]

^<<v26-23-2,2>>^ "Filho do homem, havia duas irmãs, filhas da mesma mãe.

[[v26-23-3]]

^<<v26-23-3,3>>^ Elas se tornaram prostitutas no Egito. Quando ainda eram meninas, deixavam que homens acariciassem seus seios.

[[v26-23-4]]

^<<v26-23-4,4>>^ A irmã mais velha se chamava Oolá, e a mais nova, Oolibá. Casei-me com elas, e me deram filhos e filhas. Refiro-me a Samaria e Jerusalém, pois Oolá é Samaria, e Oolibá, Jerusalém.

[[v26-23-5]]

^<<v26-23-5,5>>^ "Então, embora fosse minha, Oolá desejou ardentemente outros amantes e se entregou aos assírios.

[[v26-23-6]]

^<<v26-23-6,6>>^ Todos eles eram jovens atraentes, capitães e comandantes, com belas roupas azuis, montados a cavalo.

[[v26-23-7]]

^<<v26-23-7,7>>^ Assim, ela se prostituiu com os homens mais desejáveis da Assíria, adorou seus ídolos e se contaminou.

[[v26-23-8]]

^<<v26-23-8,8>>^ Pois, quando ela saiu do Egito, não deixou para trás a prostituição. Continuou depravada como em sua juventude, quando os egípcios dormiram com ela, acariciaram seus seios e a usaram como prostituta.

[[v26-23-9]]

^<<v26-23-9,9>>^ "Por isso eu a entreguei a seus amantes assírios, que ela tanto desejou.

[[v26-23-10]]

^<<v26-23-10,10>>^ Eles arrancaram suas roupas, levaram seus filhos e filhas e então a mataram. Depois que ela recebeu esse castigo, sua reputação tornou-se conhecida entre todas as mulheres da terra.

[[v26-23-11]]

^<<v26-23-11,11>>^ "Contudo, embora Oolibá tenha visto o que aconteceu à sua irmã Oolá, seguiu pelo mesmo caminho. Na verdade, foi ainda mais depravada e se entregou ao desejo e à prostituição.

[[v26-23-12]]

^<<v26-23-12,12>>^ Cobiçou os assírios — os capitães e comandantes em belos uniformes, montados a cavalo —, todos eles jovens atraentes.

[[v26-23-13]]

^<<v26-23-13,13>>^ Vi que estava se contaminando, como sua irmã mais velha.

[[v26-23-14]]

^<<v26-23-14,14>>^ "Então levou sua prostituição ainda mais longe e se apaixonou por figuras pintadas numa parede, figuras de oficiais babilônios, com uniformes vermelhos chamativos

[[v26-23-15]]

^<<v26-23-15,15>>^ e com belos cintos e turbantes de tecido fino. Estavam vestidos como oficiais da terra da Babilônia.

[[v26-23-16]]

^<<v26-23-16,16>>^ Quando ela viu essas pinturas, desejou ardentemente entregar-se a eles, por isso enviou mensageiros à Babilônia para convidá-los para a visitarem.

[[v26-23-17]]

^<<v26-23-17,17>>^ Eles vieram, cometeram adultério com ela e a contaminaram na cama do amor. Depois de ser contaminada, porém, teve nojo deles e os rejeitou.

[[v26-23-18]]

^<<v26-23-18,18>>^ "Da mesma forma, eu tive nojo de Oolibá e a rejeitei, como havia rejeitado sua irmã, porque ela se exibiu diante deles e a eles se entregou para satisfazer seus desejos.

[[v26-23-19]]

^<<v26-23-19,19>>^ Entregou-se, porém, a prostituição ainda maior ao lembrar-se de sua juventude, quando era prostituta no Egito.

[[v26-23-20]]

^<<v26-23-20,20>>^ Desejou amantes com genitais grandes como de jumentos e ejaculação como de cavalos.

[[v26-23-21]]

^<<v26-23-21,21>>^ E assim, Oolibá, você reviveu a depravação de sua juventude no Egito, quando permitiu que seus seios fossem acariciados."

[[v26-23-22]]

^<<v26-23-22,22>>^ "Portanto, Oolibá, assim diz o SENHOR Soberano: De todas as partes, enviarei seus amantes contra você, as mesmas nações das quais você se afastou com nojo.

[[v26-23-23]]

^<<v26-23-23,23>>^ Os babilônios virão com todos os caldeus de Pecode, Soa e Coa. E todos os assírios virão com eles, jovens atraentes, capitães, comandantes, oficiais dos carros de guerra e outros oficiais de alto escalão, todos a cavalo.

[[v26-23-24]]

^<<v26-23-24,24>>^ Virão do norte contra você com carros de guerra, carroças e muitas armas, preparados para o ataque. Assumirão posições de batalha e a cercarão com soldados armados com escudos e capacetes. E eu a entregarei a eles para ser castigada, para que façam com você o que quiserem.

[[v26-23-25]]

^<<v26-23-25,25>>^ Voltarei contra você a ira do meu ciúme, e eles a tratarão com crueldade. Cortarão fora seu nariz e suas orelhas e matarão à espada os sobreviventes. Seus filhos serão levados como prisioneiros, e tudo que restar será queimado.

[[v26-23-26]]

^<<v26-23-26,26>>^ Arrancarão suas roupas e lindas joias.

[[v26-23-27]]

^<<v26-23-27,27>>^ Desse modo, acabarei com a depravação e a prostituição que você trouxe do Egito. Nunca mais você olhará com desejo para essas coisas, nem se lembrará mais com saudade de seu tempo no Egito.

[[v26-23-28]]

^<<v26-23-28,28>>^ "Pois assim diz o SENHOR Soberano: Certamente eu a entregarei a seus inimigos, àqueles que você detesta, àqueles que você rejeitou.

[[v26-23-29]]

^<<v26-23-29,29>>^ Eles a tratarão com ódio, tomarão tudo que você possui e a deixarão completamente nua. A vergonha de sua prostituição ficará exposta para todo o mundo.

[[v26-23-30]]

^<<v26-23-30,30>>^ Você trouxe tudo isso sobre si mesma ao se prostituir com outras nações, ao se contaminar com seus ídolos.

[[v26-23-31]]

^<<v26-23-31,31>>^ Porque você seguiu pelo mesmo caminho que sua irmã, eu a obrigarei a beber do mesmo cálice de terror do qual ela bebeu.

[[v26-23-32]]

^<<v26-23-32,32>>^ "Assim diz o SENHOR Soberano: "Você beberá do cálice de terror de sua irmã, um copo grande e fundo. Ele está cheio até a borda de desprezo e zombaria.

[[v26-23-33]]

^<<v26-23-33,33>>^ Embriaguez e angústia se apossarão de você, pois seu cálice está cheio até a borda de desgraça e desolação, o mesmo copo do qual sua irmã, Samaria, bebeu.

[[v26-23-34]]

^<<v26-23-34,34>>^ Você beberá desse cálice de terror até a última gota. Então o fará em pedaços e com os cacos mutilará seus seios. Eu, o SENHOR Soberano, falei!

[[v26-23-35]]

^<<v26-23-35,35>>^ "E, porque você se esqueceu de mim e me deu as costas, assim diz o SENHOR Soberano: Você sofrerá as consequências de sua depravação e prostituição".

[[v26-23-36]]

^<<v26-23-36,36>>^ O SENHOR me disse: "Filho do homem, pronuncie julgamento sobre Oolá e Oolibá por todos os seus pecados detestáveis.

[[v26-23-37]]

^<<v26-23-37,37>>^ Elas cometeram adultério e assassinato: adultério ao adorarem ídolos e assassinato ao queimarem como sacrifício os filhos que geraram para mim.

[[v26-23-38]]

^<<v26-23-38,38>>^ Além disso, contaminaram meu templo e profanaram meu sábado.

[[v26-23-39]]

^<<v26-23-39,39>>^ No mesmo dia em que sacrificaram seus filhos aos ídolos, tiveram a ousadia de vir ao meu templo para adorar; entraram em minha casa e a profanaram.

[[v26-23-40]]

^<<v26-23-40,40>>^ "Vocês, irmãs, enviaram mensageiros a terras distantes para conseguir homens. Quando eles chegaram, vocês tomaram banho, pintaram os olhos e colocaram suas joias mais finas para recebê-los.

[[v26-23-41]]

^<<v26-23-41,41>>^ Sentaram-se com eles num sofá com lindos bordados e colocaram meu incenso e meu óleo especial na mesa arrumada diante de vocês.

[[v26-23-42]]

^<<v26-23-42,42>>^ De seu quarto vinham sons de muitos homens bebendo e se divertindo. Eram homens do deserto, lascivos e beberrões, que colocaram pulseiras em seus braços e lindas coroas em sua cabeça.

[[v26-23-43]]

^<<v26-23-43,43>>^ Então eu disse: ‘Se eles querem mesmo ter relações com prostitutas velhas e acabadas como essas, que tenham!’.

[[v26-23-44]]

^<<v26-23-44,44>>^ E foi o que fizeram. Tiveram relações com Oolá e Oolibá, prostitutas desavergonhadas.

[[v26-23-45]]

^<<v26-23-45,45>>^ Mas os justos julgarão essas cidades irmãs de acordo com o que de fato são: adúlteras e assassinas.

[[v26-23-46]]

^<<v26-23-46,46>>^ "Agora, assim diz o SENHOR Soberano: Tragam um exército contra elas e entreguem-nas para serem aterrorizadas e saqueadas.

[[v26-23-47]]

^<<v26-23-47,47>>^ Seus inimigos as apedrejarão e as golpearão com espadas. Matarão seus filhos e filhas e queimarão suas casas.

[[v26-23-48]]

^<<v26-23-48,48>>^ Desse modo, acabarei com a depravação na terra, e meu julgamento servirá de advertência para que outras não sigam seu mau exemplo.

[[v26-23-49]]

^<<v26-23-49,49>>^ Vocês receberão o castigo merecido por sua prostituição e idolatria. Então saberão que eu sou o SENHOR Soberano".

'''

xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[&#60; Capítulo Anterior] | <<v26-23-0,Topo>> | xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[Próximo Capítulo &#62;]