include::./index.adoc[]

[[v26-5-0]]
=== Ezequiel, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v26-5-1]]

^<<v26-5-1,1>>^ "Filho do homem, pegue uma espada afiada e use-a como navalha para raspar sua cabeça e sua barba. Use uma balança para pesar o cabelo e dividi-lo em três partes.

[[v26-5-2]]

^<<v26-5-2,2>>^ Coloque uma terça parte no meio do desenho de Jerusalém e, depois de encenar o cerco à cidade, queime o cabelo ali. Espalhe outra terça parte ao redor do desenho e corte-a com a espada. Espalhe a terceira parte ao vento, pois eu espalharei meu povo com a espada.

[[v26-5-3]]

^<<v26-5-3,3>>^ Guarde apenas um pouco de cabelo e amarre-o em seu manto.

[[v26-5-4]]

^<<v26-5-4,4>>^ Então, pegue alguns desses fios de cabelo e jogue-os no fogo, para que se queimem. Dali um fogo se espalhará e destruirá todo o Israel.

[[v26-5-5]]

^<<v26-5-5,5>>^ "Assim diz o SENHOR Soberano: Esta é uma ilustração do que acontecerá a Jerusalém. Coloquei-a no centro das nações,

[[v26-5-6]]

^<<v26-5-6,6>>^ mas ela se revoltou contra meus estatutos e decretos e foi mais perversa que as nações ao seu redor. Não quis obedecer a meus estatutos e decretos.

[[v26-5-7]]

^<<v26-5-7,7>>^ "Portanto, assim diz o SENHOR Soberano: Vocês são mais rebeldes que as nações vizinhas e não quiseram obedecer a meus decretos e estatutos. Nem sequer viveram de acordo com os padrões de justiça das nações ao seu redor.

[[v26-5-8]]

^<<v26-5-8,8>>^ Portanto, eu mesmo, o SENHOR Soberano, estou contra vocês. Eu os castigarei publicamente diante de todas as nações.

[[v26-5-9]]

^<<v26-5-9,9>>^ Por causa de seus ídolos detestáveis, punirei vocês como nunca fiz antes e nunca voltarei a fazer.

[[v26-5-10]]

^<<v26-5-10,10>>^ Pais devorarão os filhos, e filhos devorarão os pais. Eu os castigarei e espalharei aos quatro ventos os poucos que sobreviverem.

[[v26-5-11]]

^<<v26-5-11,11>>^ "Tão certo como eu vivo, diz o SENHOR Soberano, eu os destruirei completamente. Não terei compaixão alguma de vocês, pois profanaram meu templo com imagens repugnantes e pecados detestáveis.

[[v26-5-12]]

^<<v26-5-12,12>>^ Uma terça parte de seu povo morrerá na cidade por doença e fome, uma terça parte será morta pelo inimigo fora dos muros da cidade, e eu espalharei uma terça parte aos quatro ventos e os perseguirei com minha espada.

[[v26-5-13]]

^<<v26-5-13,13>>^ Por fim, minha ira se completará, e ficarei satisfeito. E, quando minha fúria contra eles tiver passado, todo o Israel saberá que eu, o SENHOR, lhes falei segundo o meu zelo.

[[v26-5-14]]

^<<v26-5-14,14>>^ "Portanto, eu o transformarei em uma ruína, em objeto de insulto aos olhos das nações ao redor e para todos que passarem por ali.

[[v26-5-15]]

^<<v26-5-15,15>>^ Você se tornará alvo de insultos, zombarias e horror, e servirá de advertência para todas as nações ao redor. Elas verão o que acontece quando o SENHOR, em sua ira, castiga uma nação e a repreende, diz o SENHOR.

[[v26-5-16]]

^<<v26-5-16,16>>^ "Farei chover sobre você as flechas mortais da fome, para destruí-la. A fome se tornará cada vez mais severa, até que desapareça todo suprimento.

[[v26-5-17]]

^<<v26-5-17,17>>^ Além da fome, enviarei animais selvagens para atacá-la e devorar seus filhos. Doença e guerra a alcançarão, e trarei contra você a espada do inimigo. Eu, o SENHOR, falei!".

'''

xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[&#60; Capítulo Anterior] | <<v26-5-0,Topo>> | xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[Próximo Capítulo &#62;]