include::./index.adoc[]

[[v26-28-0]]
=== Ezequiel, 28
// nvt ?, NVT - Nova Versão Transformadora

[[v26-28-1]]

^<<v26-28-1,1>>^ Recebi esta mensagem do SENHOR:

[[v26-28-2]]

^<<v26-28-2,2>>^ "Filho do homem, transmita ao príncipe de Tiro esta mensagem do SENHOR Soberano: "Em seu grande orgulho, você diz: ‘Sou um deus! Sento-me num trono divino, no coração do mar’. Mas você é apenas homem, e não deus, embora se considere sábio como um.

[[v26-28-3]]

^<<v26-28-3,3>>^ Pensa que é mais sábio que Daniel e imagina que nenhum segredo lhe está oculto.

[[v26-28-4]]

^<<v26-28-4,4>>^ Com sua sabedoria e entendimento, acumulou grande riqueza: ouro e prata para seus tesouros.

[[v26-28-5]]

^<<v26-28-5,5>>^ Sim, sua sabedoria o enriqueceu grandemente, e suas riquezas o tornaram muito orgulhoso.

[[v26-28-6]]

^<<v26-28-6,6>>^ "Portanto, assim diz o SENHOR Soberano: Uma vez que se considera sábio como um deus,

[[v26-28-7]]

^<<v26-28-7,7>>^ trarei contra você um exército estrangeiro, o terror das nações. Empunharão espadas contra sua sabedoria maravilhosa e profanarão seu esplendor.

[[v26-28-8]]

^<<v26-28-8,8>>^ Eles o farão descer à cova, e você morrerá no fundo do mar, ferido violentamente.

[[v26-28-9]]

^<<v26-28-9,9>>^ Acaso dirá àqueles que o matarem: ‘Sou um deus’? Para eles você não será deus algum, mas apenas homem!

[[v26-28-10]]

^<<v26-28-10,10>>^ Morrerá de forma vergonhosa nas mãos de estrangeiros. Eu, o SENHOR Soberano, falei!".

[[v26-28-11]]

^<<v26-28-11,11>>^ Também recebi esta mensagem do SENHOR:

[[v26-28-12]]

^<<v26-28-12,12>>^ "Filho do homem, entoe este cântico fúnebre para o rei de Tiro. Transmita-lhe a seguinte mensagem do SENHOR Soberano: "Você era o modelo de perfeição, cheio de sabedoria e beleza.

[[v26-28-13]]

^<<v26-28-13,13>>^ Estava no Éden, o jardim de Deus. Suas roupas eram enfeitadas com todas as pedras preciosas: rubi, topázio, esmeralda, crisólito, ônix e jaspe, safira, berilo e turquesa, todas trabalhadas com cuidado para você sobre o ouro mais puro. Foram-lhe entregues no dia em que você foi criado.

[[v26-28-14]]

^<<v26-28-14,14>>^ Eu o escolhi e o ungi, como querubim guardião. Você tinha acesso ao monte santo de Deus e andava entre as pedras cintilantes.

[[v26-28-15]]

^<<v26-28-15,15>>^ "Era irrepreensível em tudo que fazia desde o dia em que foi criado, até que se achou maldade em você.

[[v26-28-16]]

^<<v26-28-16,16>>^ Seu rico comércio o levou à violência, e você pecou. Por isso o bani em desonra do monte de Deus. Eu o expulsei, ó querubim guardião, de seu lugar entre as pedras cintilantes.

[[v26-28-17]]

^<<v26-28-17,17>>^ Seu coração se encheu de orgulho por causa de sua beleza. Sua sabedoria se corrompeu por causa de seu esplendor. Por isso o atirei à terra e o expus ao olhar dos reis.

[[v26-28-18]]

^<<v26-28-18,18>>^ Você profanou seus santuários com seus muitos pecados e seu comércio desonesto. Por isso fiz sair de dentro de você um fogo que o consumiu. Reduzi-o a cinzas no chão, à vista de todos que observavam.

[[v26-28-19]]

^<<v26-28-19,19>>^ Todos que o conheciam estão horrorizados com seu destino; você chegou a um terrível fim, e não mais existirá".

[[v26-28-20]]

^<<v26-28-20,20>>^ Então recebi outra mensagem do SENHOR:

[[v26-28-21]]

^<<v26-28-21,21>>^ "Filho do homem, volte o rosto para a cidade de Sidom e profetize contra ela.

[[v26-28-22]]

^<<v26-28-22,22>>^ Transmita aos habitantes de Sidom esta mensagem do SENHOR Soberano: "Ó Sidom, sou seu inimigo e revelarei minha glória naquilo que lhe fizer. Quando eu trouxer julgamento sobre você e revelar minha santidade em seu meio, todos que observam saberão que eu sou o SENHOR.

[[v26-28-23]]

^<<v26-28-23,23>>^ Enviarei uma peste contra você, e sangue correrá em suas ruas. O ataque virá de todos os lados: seus habitantes morrerão pela espada e ficarão estendidos no meio da cidade; então todos saberão que eu sou o SENHOR.

[[v26-28-24]]

^<<v26-28-24,24>>^ Os vizinhos zombadores de Israel deixarão de feri-lo e rasgá-lo como roseiras silvestres e espinhos. Pois eles saberão que eu sou o SENHOR Soberano."

[[v26-28-25]]

^<<v26-28-25,25>>^ "Assim diz o SENHOR Soberano: O povo de Israel voltará a viver em sua própria terra, a terra que dei a meu servo Jacó. Pois eu os reunirei das terras distantes onde os espalhei e, diante das nações do mundo, revelarei minha santidade no meio de meu povo.

[[v26-28-26]]

^<<v26-28-26,26>>^ Eles viverão em segurança em Israel, construirão casas e plantarão vinhedos. E, quando eu castigar as nações vizinhas que os trataram com desprezo, eles saberão que eu sou o SENHOR, seu Deus".

'''

xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]