include::./index.adoc[]

[[v26-20-0]]
=== Ezequiel, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v26-20-1]]

^<<v26-20-1,1>>^ Em 14 de agosto, durante o sétimo ano do exílio do rei Joaquim, alguns dos líderes de Israel vieram consultar o SENHOR e, enquanto estavam sentados comigo,

[[v26-20-2]]

^<<v26-20-2,2>>^ recebi esta mensagem do SENHOR:

[[v26-20-3]]

^<<v26-20-3,3>>^ "Filho do homem, diga aos líderes de Israel: ‘Assim diz o SENHOR Soberano: Como ousam vir me consultar? Tão certo como eu vivo, diz o SENHOR Soberano, não lhes direi coisa alguma!’.

[[v26-20-4]]

^<<v26-20-4,4>>^ "Filho do homem, apresente acusações contra eles e condene-os. Faça-os ver como eram detestáveis os pecados de seus antepassados.

[[v26-20-5]]

^<<v26-20-5,5>>^ Transmita-lhes esta mensagem do SENHOR Soberano: Quando escolhi Israel, quando me revelei aos descendentes de Jacó, no Egito, jurei solenemente que eu, o SENHOR, seria o seu Deus.

[[v26-20-6]]

^<<v26-20-6,6>>^ Naquele dia, jurei que os tiraria do Egito e os levaria para uma terra que havia encontrado para eles, uma terra boa, que produz leite e mel com fartura, a mais linda de todas as terras.

[[v26-20-7]]

^<<v26-20-7,7>>^ Então lhes disse: ‘Cada um de vocês livre-se de suas imagens repugnantes pelas quais está obcecado. Não se contamine com os ídolos do Egito, pois eu sou o SENHOR, seu Deus’.

[[v26-20-8]]

^<<v26-20-8,8>>^ "Eles, porém, se rebelaram contra mim e não quiseram ouvir. Não se livraram das imagens repugnantes pelas quais estavam obcecados, nem abandonaram os ídolos do Egito. Então ameacei derramar minha fúria sobre eles para satisfazer minha ira enquanto ainda estavam no Egito.

[[v26-20-9]]

^<<v26-20-9,9>>^ Mas, por causa do meu nome, não o fiz. Não permiti que meu nome fosse desonrado entre as nações vizinhas diante das quais me revelei quando tirei os israelitas do Egito.

[[v26-20-10]]

^<<v26-20-10,10>>^ Portanto, eu os tirei do Egito e os levei para o deserto.

[[v26-20-11]]

^<<v26-20-11,11>>^ Ali lhes dei meus decretos e estatutos, para que encontrassem vida ao praticá-los.

[[v26-20-12]]

^<<v26-20-12,12>>^ Também lhes dei os sábados como sinal entre mim e eles, para lembrá-los de que eu sou o SENHOR, que os separou para serem santos.

[[v26-20-13]]

^<<v26-20-13,13>>^ "O povo de Israel, no entanto, se rebelou contra mim e não quis obedecer a meus decretos no deserto. A obediência lhes teria dado vida, mas não seguiram meus estatutos. Além disso, profanaram meus sábados. Portanto, ameacei derramar minha fúria sobre eles e consumi-los inteiramente no deserto.

[[v26-20-14]]

^<<v26-20-14,14>>^ Mais uma vez, porém, me contive por causa do meu nome, para que não fosse desonrado diante das nações que tinham visto meu poder quando tirei Israel do Egito.

[[v26-20-15]]

^<<v26-20-15,15>>^ Contudo, fiz um juramento solene contra eles no deserto. Jurei que não os faria entrar na terra que lhes tinha dado, uma terra que produz leite e mel com fartura, a mais linda de todas as terras.

[[v26-20-16]]

^<<v26-20-16,16>>^ Pois rejeitaram meus estatutos, recusaram-se a seguir meus decretos e profanaram meus sábados, porque entregaram o coração a seus ídolos.

[[v26-20-17]]

^<<v26-20-17,17>>^ Apesar disso, tive compaixão deles e não os destruí no deserto.

[[v26-20-18]]

^<<v26-20-18,18>>^ "Então adverti seus filhos no deserto a não seguirem os passos e o estilo de vida de seus pais, que se contaminaram com seus ídolos.

[[v26-20-19]]

^<<v26-20-19,19>>^ Disse-lhes: ‘Eu sou o SENHOR, seu Deus. Sigam meus decretos, obedeçam a meus estatutos

[[v26-20-20]]

^<<v26-20-20,20>>^ e guardem meus sábados como dias santos, pois são um sinal entre mim e vocês para lembrá-los de que eu sou o SENHOR, seu Deus’.

[[v26-20-21]]

^<<v26-20-21,21>>^ "Seus filhos, porém, também se rebelaram contra mim. A obediência lhes teria dado vida, mas não guardaram meus decretos nem seguiram meus estatutos. Além disso, profanaram meus sábados. Portanto, mais uma vez, ameacei derramar minha fúria sobre eles no deserto para satisfazer minha ira.

[[v26-20-22]]

^<<v26-20-22,22>>^ No entanto, contive meu julgamento por causa do meu nome, para que não fosse desonrado diante das nações que tinham visto meu poder quando tirei Israel do Egito.

[[v26-20-23]]

^<<v26-20-23,23>>^ Contudo, fiz um juramento solene contra eles no deserto. Jurei que os espalharia entre todas as nações,

[[v26-20-24]]

^<<v26-20-24,24>>^ pois não obedeceram a meus estatutos. Desprezaram meus decretos, profanaram meus sábados e cobiçaram os ídolos de seus antepassados.

[[v26-20-25]]

^<<v26-20-25,25>>^ Eu os entreguei a decretos e estatutos inúteis, que não conduziriam à vida.

[[v26-20-26]]

^<<v26-20-26,26>>^ Deixei que se contaminassem com suas ofertas idólatras e permiti que oferecessem seus primeiros filhos como sacrifícios a seus deuses, para que eu os devastasse e lhes mostrasse que somente eu sou o SENHOR."

[[v26-20-27]]

^<<v26-20-27,27>>^ "Portanto, filho do homem, transmita ao povo de Israel esta mensagem do SENHOR Soberano: Seus antepassados continuaram a blasfemar contra mim e a me trair,

[[v26-20-28]]

^<<v26-20-28,28>>^ pois, quando os trouxe à terra que lhes havia prometido, eles ofereceram sacrifícios onde quer que vissem montes altos e árvores verdejantes. Provocaram minha fúria ao oferecer sacrifícios a seus deuses. Levaram perfumes e incenso e apresentaram ofertas derramadas.

[[v26-20-29]]

^<<v26-20-29,29>>^ Disse-lhes: ‘Que lugar alto é este para onde vão?’. (Desde então, esse tipo de lugar é chamado de Bamá, ‘lugar alto’.)

[[v26-20-30]]

^<<v26-20-30,30>>^ "Portanto, transmita ao povo de Israel esta mensagem do SENHOR Soberano: Vocês continuarão a se contaminar, como fizeram seus antepassados? Vão se prostituir adorando imagens repugnantes?

[[v26-20-31]]

^<<v26-20-31,31>>^ Pois, quando apresentam ofertas para elas e sacrificam seus filhos no fogo, continuam a se contaminar com ídolos até hoje. Acaso devo permitir que me consultem, ó povo de Israel? Tão certo como eu vivo, diz o SENHOR Soberano, não lhes direi coisa alguma.

[[v26-20-32]]

^<<v26-20-32,32>>^ "Vocês dizem: ‘Queremos ser como as nações ao redor, que servem a ídolos de madeira e de pedra’. Mas o que vocês planejam nunca acontecerá.

[[v26-20-33]]

^<<v26-20-33,33>>^ Tão certo como eu vivo, diz o SENHOR Soberano, eu os governarei com mão de ferro, com grande ira e poder tremendo.

[[v26-20-34]]

^<<v26-20-34,34>>^ E com grande ira estenderei minha mão forte e meu braço poderoso e os trarei de volta das terras onde foram espalhados.

[[v26-20-35]]

^<<v26-20-35,35>>^ Eu os levarei ao deserto das nações e ali os julgarei face a face.

[[v26-20-36]]

^<<v26-20-36,36>>^ Ali os julgarei como julguei seus antepassados no deserto depois de tirá-los do Egito, diz o SENHOR Soberano.

[[v26-20-37]]

^<<v26-20-37,37>>^ Eu os examinarei cuidadosamente e os farei obedecer aos termos de minha aliança.

[[v26-20-38]]

^<<v26-20-38,38>>^ Tirarei de seu meio todos que se rebelam e se revoltam contra mim. Eu os farei sair das terras em que estão exilados, mas eles nunca entrarão na terra de Israel. Então vocês saberão que eu sou o SENHOR.

[[v26-20-39]]

^<<v26-20-39,39>>^ "Quanto a vocês, povo de Israel, assim diz o SENHOR Soberano: Continuem a adorar seus ídolos. Mais cedo ou mais tarde, porém, vocês me obedecerão e deixarão de desonrar meu santo nome com sua idolatria.

[[v26-20-40]]

^<<v26-20-40,40>>^ Pois em meu santo monte, o alto monte de Israel, diz o SENHOR Soberano, todo o povo de Israel me adorará, e eu os aceitarei. Ali exigirei que tragam todas as suas ofertas, suas melhores dádivas e tudo que me consagrarem.

[[v26-20-41]]

^<<v26-20-41,41>>^ Quando eu os trouxer de volta do exílio, vocês serão para mim como uma oferta agradável. E, por meio de vocês, demonstrarei minha santidade diante de todas as nações.

[[v26-20-42]]

^<<v26-20-42,42>>^ Então, quando eu os tiver trazido de volta à terra que, com juramento solene, prometi a seus antepassados, saberão que eu sou o SENHOR.

[[v26-20-43]]

^<<v26-20-43,43>>^ Vocês se lembrarão de todas as formas pelas quais se contaminaram e terão nojo de si mesmos por todo o mal que fizeram.

[[v26-20-44]]

^<<v26-20-44,44>>^ Saberão que eu sou o SENHOR, ó povo de Israel, quando, por causa do meu nome, eu os tratar com compaixão, apesar de toda a sua perversidade. Eu, o SENHOR Soberano, falei!".

[[v26-20-45]]

^<<v26-20-45,45>>^ Então recebi esta mensagem do SENHOR:

[[v26-20-46]]

^<<v26-20-46,46>>^ "Filho do homem, volte o rosto para o sul e pronuncie-se contra ele; profetize contra os matagais do Neguebe.

[[v26-20-47]]

^<<v26-20-47,47>>^ Diga ao bosque do sul: ‘Assim diz o SENHOR Soberano: Ouça a palavra do SENHOR! Eu o incendiarei, e todas as árvores, tanto as verdes como as secas, serão consumidas. As chamas ardentes não serão apagadas e queimarão tudo, desde o sul até o norte.

[[v26-20-48]]

^<<v26-20-48,48>>^ Todos verão que eu, o SENHOR, acendi esse fogo, e ele não será apagado’".

[[v26-20-49]]

^<<v26-20-49,49>>^ Então eu disse: "Ó SENHOR Soberano, eles dizem a meu respeito: ‘Ele só fala por meio de parábolas!’".

'''

xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[&#60; Capítulo Anterior] | <<v26-20-0,Topo>> | xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[Próximo Capítulo &#62;]