include::./index.adoc[]

[[v26-22-0]]
=== Ezequiel, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v26-22-1]]

^<<v26-22-1,1>>^ Recebi esta mensagem do SENHOR:

[[v26-22-2]]

^<<v26-22-2,2>>^ "Filho do homem, você está preparado para pronunciar julgamento sobre Jerusalém, esta cidade de assassinos? Faça que ela veja como são detestáveis seus pecados

[[v26-22-3]]

^<<v26-22-3,3>>^ e transmita-lhe esta mensagem do SENHOR Soberano: Ó cidade de assassinos, condenada e maldita, cidade de ídolos imundos e repugnantes,

[[v26-22-4]]

^<<v26-22-4,4>>^ você é culpada pelo sangue que derramou e está contaminada pelos ídolos que fez. Seu dia de castigo se aproxima! Você chegou ao fim de seus anos, e farei de você objeto de zombaria no mundo inteiro.

[[v26-22-5]]

^<<v26-22-5,5>>^ Ó cidade infame, cheia de confusão, povos distantes e próximos zombarão de você!

[[v26-22-6]]

^<<v26-22-6,6>>^ "Todo líder de Israel que vive dentro de seus muros está decidido a derramar sangue.

[[v26-22-7]]

^<<v26-22-7,7>>^ Pais e mães são tratados com desprezo, estrangeiros são obrigados a pagar por proteção, órfãos e viúvas são oprimidos em seu meio.

[[v26-22-8]]

^<<v26-22-8,8>>^ Você despreza minhas coisas santas e profana meus sábados.

[[v26-22-9]]

^<<v26-22-9,9>>^ Pessoas acusam outras falsamente e as condenam à morte. Em seu meio há idólatras e gente que faz coisas obscenas.

[[v26-22-10]]

^<<v26-22-10,10>>^ Homens têm relações sexuais com a esposa do próprio pai e se impõem sobre mulheres menstruadas.

[[v26-22-11]]

^<<v26-22-11,11>>^ Há quem cometa adultério com a esposa do vizinho, quem contamine sua nora e quem violente a própria irmã.

[[v26-22-12]]

^<<v26-22-12,12>>^ Por toda parte há assassinos de aluguel, agiotas que cobram juros abusivos e sujeitos que praticam extorsão. Não se lembram de mim, diz o SENHOR Soberano.

[[v26-22-13]]

^<<v26-22-13,13>>^ "Agora, porém, bato as mãos com indignação por causa do ganho desonesto e do derramamento de sangue em seu meio.

[[v26-22-14]]

^<<v26-22-14,14>>^ Quão forte e corajosa você será no dia do acerto de contas? Eu, o SENHOR, falei e cumprirei o que prometi.

[[v26-22-15]]

^<<v26-22-15,15>>^ Espalharei você entre as nações e acabarei com sua perversidade.

[[v26-22-16]]

^<<v26-22-16,16>>^ E, quando você tiver sido desonrada entre as nações, saberá que eu sou o SENHOR".

[[v26-22-17]]

^<<v26-22-17,17>>^ Então recebi esta mensagem do SENHOR:

[[v26-22-18]]

^<<v26-22-18,18>>^ "Filho do homem, o povo de Israel é a coisa desprezível, sem valor, que resta depois de fundir a prata. São refugo, uma mistura inútil de cobre, estanho, ferro e chumbo.

[[v26-22-19]]

^<<v26-22-19,19>>^ Portanto, diga-lhes: ‘Assim diz o SENHOR Soberano: Porque vocês são coisa desprezível, sem valor, eu os reunirei em Jerusalém.

[[v26-22-20]]

^<<v26-22-20,20>>^ Como a prata, o cobre, o ferro, o chumbo e o estanho são derretidos na fornalha, assim eu os derreterei com o calor de minha ira ardente.

[[v26-22-21]]

^<<v26-22-21,21>>^ Eu os reunirei e soprarei sobre vocês o fogo de minha fúria,

[[v26-22-22]]

^<<v26-22-22,22>>^ e vocês derreterão como a prata derrete no calor intenso. Então saberão que eu, o SENHOR, derramei sobre vocês a minha fúria’".

[[v26-22-23]]

^<<v26-22-23,23>>^ Recebi outra mensagem do SENHOR:

[[v26-22-24]]

^<<v26-22-24,24>>^ "Filho do homem, transmita esta mensagem a Israel: No dia de minha indignação, vocês serão como uma terra contaminada, uma terra sem chuva.

[[v26-22-25]]

^<<v26-22-25,25>>^ Seus príncipes tramam conspirações, como leões à espreita da presa. Devoram inocentes, apropriam-se de tesouros, obtêm riquezas por extorsão e fazem muitas viúvas na terra.

[[v26-22-26]]

^<<v26-22-26,26>>^ Seus sacerdotes não guardaram minha lei e profanaram minhas coisas santas. Não fazem distinção entre sagrado e profano e não ensinam meu povo a distinguir entre cerimonialmente puro e impuro. Desrespeitam meus sábados, de modo que sou desonrado no meio deles.

[[v26-22-27]]

^<<v26-22-27,27>>^ Seus líderes são como lobos que despedaçam as vítimas. Destroem a vida das pessoas por dinheiro!

[[v26-22-28]]

^<<v26-22-28,28>>^ E seus profetas encobrem tudo isso com visões falsas e previsões mentirosas. Dizem: ‘Recebi esta mensagem do SENHOR Soberano’, quando, na verdade, o SENHOR não lhes disse coisa alguma.

[[v26-22-29]]

^<<v26-22-29,29>>^ Até mesmo o povo oprime os pobres, rouba dos necessitados e nega justiça aos estrangeiros.

[[v26-22-30]]

^<<v26-22-30,30>>^ "Procurei alguém que reconstruísse o muro que guarda a terra, que se pusesse na brecha para que eu não a destruísse, mas não encontrei ninguém.

[[v26-22-31]]

^<<v26-22-31,31>>^ Agora, portanto, derramarei minha fúria sobre eles e os consumirei com o fogo de minha ira. Farei cair sobre sua cabeça o castigo merecido por tudo que fizeram. Eu, o SENHOR Soberano, falei!".

'''

xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[&#60; Capítulo Anterior] | <<v26-22-0,Topo>> | xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[Próximo Capítulo &#62;]