include::./index.adoc[]

[[v26-11-0]]
=== Ezequiel, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v26-11-1]]

^<<v26-11-1,1>>^ Então o Espírito me pôs em pé e me levou à porta leste do templo do SENHOR, onde vi 25 homens. Entre eles estavam Jazanias, filho de Azur, e Pelatias, filho de Benaia, líderes do povo.

[[v26-11-2]]

^<<v26-11-2,2>>^ O Espírito me disse: "Filho do homem, estes são os homens que planejam o mal e dão conselhos perversos nesta cidade.

[[v26-11-3]]

^<<v26-11-3,3>>^ Dizem ao povo: ‘Não acham que é uma boa hora para construir casas? Esta cidade é como uma panela de ferro; estamos seguros dentro dela, como a carne na panela’.

[[v26-11-4]]

^<<v26-11-4,4>>^ Portanto, filho do homem, profetize contra eles em alta voz".

[[v26-11-5]]

^<<v26-11-5,5>>^ Então o Espírito do SENHOR veio sobre mim e ordenou que eu dissesse: "Assim diz o SENHOR ao povo de Israel: Eu sei o que vocês dizem, pois conheço cada pensamento que lhes vem à mente.

[[v26-11-6]]

^<<v26-11-6,6>>^ Assassinaram muitos nesta cidade e encheram suas ruas de cadáveres.

[[v26-11-7]]

^<<v26-11-7,7>>^ "Portanto, assim diz o SENHOR Soberano: De fato, esta cidade é a panela de ferro, mas os pedaços de carne são aqueles que vocês mataram. Quanto a vocês, em breve os arrancarei da panela.

[[v26-11-8]]

^<<v26-11-8,8>>^ Trarei sobre vocês a espada de guerra que tanto temem, diz o SENHOR Soberano.

[[v26-11-9]]

^<<v26-11-9,9>>^ Eu os expulsarei de Jerusalém e os entregarei a estrangeiros, que executarão meus julgamentos contra vocês.

[[v26-11-10]]

^<<v26-11-10,10>>^ Vocês serão massacrados até as fronteiras de Israel. Eu os julgarei, e vocês saberão que eu sou o SENHOR.

[[v26-11-11]]

^<<v26-11-11,11>>^ Esta cidade não será para vocês como uma panela de ferro, e vocês não serão como a carne, segura dentro dela. Eu os julgarei até as fronteiras de Israel,

[[v26-11-12]]

^<<v26-11-12,12>>^ e vocês saberão que eu sou o SENHOR. Pois não quiseram seguir meus decretos e estatutos; em vez disso, imitaram as práticas das nações ao seu redor".

[[v26-11-13]]

^<<v26-11-13,13>>^ Enquanto eu ainda profetizava, Pelatias, filho de Benaia, morreu. Então prostrei-me com o rosto no chão e clamei: "Ó SENHOR Soberano, matarás todos que restarem em Israel?".

[[v26-11-14]]

^<<v26-11-14,14>>^ Então recebi esta mensagem do SENHOR:

[[v26-11-15]]

^<<v26-11-15,15>>^ "Filho do homem, aqueles que ainda restam em Jerusalém falam de você, de seus parentes e de todo o povo de Israel que está no exílio. Dizem: ‘Estão longe do SENHOR, por isso agora ele nos deu a terra deles!’.

[[v26-11-16]]

^<<v26-11-16,16>>^ "Portanto, diga aos exilados: ‘Assim diz o SENHOR Soberano: Embora eu os tenha espalhado entre as nações do mundo, serei um santuário para vocês durante seu tempo no exílio.

[[v26-11-17]]

^<<v26-11-17,17>>^ Eu, o SENHOR Soberano, digo que os reunirei das nações onde foram espalhados e lhes devolverei a terra de Israel’.

[[v26-11-18]]

^<<v26-11-18,18>>^ "Quando eles regressarem para sua terra natal, removerão todos os resquícios de suas imagens repugnantes e de seus ídolos detestáveis.

[[v26-11-19]]

^<<v26-11-19,19>>^ Eu lhes darei um só coração e colocarei dentro deles um novo espírito. Removerei seu coração de pedra e lhes darei coração de carne,

[[v26-11-20]]

^<<v26-11-20,20>>^ para que obedeçam a meus decretos e estatutos. Então eles serão o meu povo, e eu serei o seu Deus.

[[v26-11-21]]

^<<v26-11-21,21>>^ Quanto àqueles que anseiam por suas imagens repugnantes e seus ídolos detestáveis, darei a eles o castigo merecido por seus pecados. Eu, o SENHOR Soberano, falei!".

[[v26-11-22]]

^<<v26-11-22,22>>^ Então os querubins levantaram as asas, acompanhados de suas rodas, e a glória do Deus de Israel pairava sobre eles.

[[v26-11-23]]

^<<v26-11-23,23>>^ Então a glória do SENHOR subiu da cidade e parou acima do monte a leste.

[[v26-11-24]]

^<<v26-11-24,24>>^ Depois disso, o Espírito de Deus me levou de volta à Babilônia, para o povo no exílio. Assim terminou a minha visão.

[[v26-11-25]]

^<<v26-11-25,25>>^ E eu relatei aos exilados tudo que o SENHOR me tinha mostrado.

'''

xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[&#60; Capítulo Anterior] | <<v26-11-0,Topo>> | xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[Próximo Capítulo &#62;]