include::./index.adoc[]

[[v26-9-0]]
=== Ezequiel, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v26-9-1]]

^<<v26-9-1,1>>^ Então o SENHOR disse em alta voz: "Tragam os homens escolhidos para castigar a cidade! Digam-lhes que venham com suas armas de destruição!".

[[v26-9-2]]

^<<v26-9-2,2>>^ Logo surgiram seis homens, vindos da porta superior, voltada para o norte, e cada um tinha na mão uma arma mortal. Estava com eles um homem vestido de linho, que levava na cintura um estojo com material de escrever. Todos entraram no pátio do templo e ficaram junto ao altar de bronze.

[[v26-9-3]]

^<<v26-9-3,3>>^ Então a glória do Deus de Israel se levantou do meio dos querubins, onde havia estado, e se moveu para a entrada do templo. O SENHOR chamou o homem vestido de linho que carregava o estojo com material de escrever

[[v26-9-4]]

^<<v26-9-4,4>>^ e lhe disse: "Ande pelas ruas de Jerusalém e ponha um sinal na testa de todos que choram e gemem por causa dos pecados detestáveis cometidos em sua cidade".

[[v26-9-5]]

^<<v26-9-5,5>>^ Em seguida, ouvi o SENHOR dizer aos outros homens: "Sigam-no pela cidade e matem todos cuja testa não estiver marcada. Não mostrem compaixão nem tenham piedade!

[[v26-9-6]]

^<<v26-9-6,6>>^ Matem todos: idosos e jovens, meninas, mulheres e crianças pequenas. Mas não toquem naqueles que tiverem o sinal. Comecem aqui mesmo, no templo!". E eles começaram pelos setenta líderes, na entrada do templo.

[[v26-9-7]]

^<<v26-9-7,7>>^ "Profanem o templo!", o SENHOR ordenou. "Encham seus pátios de cadáveres. Vão!" Então eles saíram e começaram a matança em toda a cidade.

[[v26-9-8]]

^<<v26-9-8,8>>^ Enquanto isso, fiquei sozinho. Prostrei-me com o rosto no chão e clamei: "Ó SENHOR Soberano! Acaso tua fúria contra Jerusalém exterminará todos que restam em Israel?".

[[v26-9-9]]

^<<v26-9-9,9>>^ Então ele me disse: "Os pecados do povo de Israel e de Judá são muito, muito grandes. Toda a terra se encheu de homicídio; a cidade está repleta de injustiça. Eles dizem: ‘O SENHOR não nos vê; o SENHOR abandonou nossa terra!’.

[[v26-9-10]]

^<<v26-9-10,10>>^ Por isso não os pouparei nem terei piedade deles. Eu lhes darei o que merecem por tudo que fizeram".

[[v26-9-11]]

^<<v26-9-11,11>>^ Então o homem vestido de linho, que carregava o estojo com material de escrever, voltou para relatar: "Fiz o que ordenaste".

'''

xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[&#60; Capítulo Anterior] | <<v26-9-0,Topo>> | xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[Próximo Capítulo &#62;]