include::./index.adoc[]

[[v26-47-0]]
=== Ezequiel, 47
// nvt ?, NVT - Nova Versão Transformadora

[[v26-47-1]]

^<<v26-47-1,1>>^ Depois disso, o homem me levou de volta à entrada do templo. Ali, notei que jorrava água para o leste por debaixo da porta do templo e passava à direita do altar, do lado sul.

[[v26-47-2]]

^<<v26-47-2,2>>^ Ele me levou para fora do muro pela porta norte e me conduziu até a entrada leste. Ali, vi que a água corria pelo lado sul da porta leste.

[[v26-47-3]]

^<<v26-47-3,3>>^ O homem me conduziu pela água e, enquanto caminhávamos, ele ia medindo. Quando percorremos quinhentos metros, ele me levou para o outro lado do rio. Ali a água chegava a meus tornozelos.

[[v26-47-4]]

^<<v26-47-4,4>>^ Ele mediu mais quinhentos metros e atravessamos o rio novamente. Dessa vez, a água chegava a meus joelhos. Depois de mais quinhentos metros, chegava à minha cintura.

[[v26-47-5]]

^<<v26-47-5,5>>^ Então ele mediu mais quinhentos metros e ali a água era um rio fundo o suficiente para atravessar a nado, mas fundo demais para atravessar a pé.

[[v26-47-6]]

^<<v26-47-6,6>>^ Ele me perguntou: "Filho do homem, você está vendo?", e me levou de volta à margem do rio.

[[v26-47-7]]

^<<v26-47-7,7>>^ Ao voltar, fiquei surpreso de ver muitas árvores que cresciam dos dois lados do rio.

[[v26-47-8]]

^<<v26-47-8,8>>^ Então ele me disse: "Este rio corre para o leste, pelo deserto, até o vale do mar Morto. Sua água tornará pura a água salgada do mar Morto.

[[v26-47-9]]

^<<v26-47-9,9>>^ Por onde a água deste rio passar, haverá muitos seres vivos. O mar Morto ficará cheio de peixes, porque sua água se tornará pura. Surgirá vida por onde esta água fluir.

[[v26-47-10]]

^<<v26-47-10,10>>^ Pescadores ficarão às margens do mar Morto. Desde En-Gedi até En-Eglaim, as praias ficarão cobertas de redes secando ao sol. O mar Morto se encherá de peixes de toda espécie, como os peixes do mar Mediterrâneo.

[[v26-47-11]]

^<<v26-47-11,11>>^ Mas os brejos e os pântanos não serão purificados; continuarão salgados.

[[v26-47-12]]

^<<v26-47-12,12>>^ Em ambas as margens do rio crescerão árvores frutíferas de toda espécie. As folhas dessas árvores nunca secarão nem cairão, e sempre haverá frutos em seus ramos. Produzirão uma nova colheita a cada mês, pois são regadas pela água do rio que nasce no templo. Seus frutos servirão de alimento, e suas folhas, de remédio".

[[v26-47-13]]

^<<v26-47-13,13>>^ Assim diz o SENHOR Soberano: "Dividam a terra desta forma entre as doze tribos de Israel: Os descendentes de José receberão duas porções de terra.

[[v26-47-14]]

^<<v26-47-14,14>>^ As outras tribos receberão porções iguais. Jurei solenemente que daria esta terra a seus antepassados, e agora ela passará para vocês como sua herança.

[[v26-47-15]]

^<<v26-47-15,15>>^ "Estas são as fronteiras da terra: A fronteira norte se estenderá do Mediterrâneo, passando por Hetlom, depois por Lebo-Hamate, até Zedade;

[[v26-47-16]]

^<<v26-47-16,16>>^ dali seguirá para Berota e Sibraim, que ficam na divisa entre Damasco e Hamate e, por fim, para Hazer-Haticom, na divisa com Haurã.

[[v26-47-17]]

^<<v26-47-17,17>>^ Portanto, a fronteira norte se estenderá do Mediterrâneo até Hazar-Enã, na divisa entre Hamate, ao norte, e Damasco, ao sul.

[[v26-47-18]]

^<<v26-47-18,18>>^ "A fronteira leste começará num ponto entre Haurã e Damasco e se estenderá para o sul ao longo do rio Jordão, entre Israel e Gileade, passando o mar Morto e prosseguindo para o sul até Tamar. Essa será a fronteira leste.

[[v26-47-19]]

^<<v26-47-19,19>>^ "A fronteira sul se estenderá de Tamar até as águas de Meribá, em Cades, e de lá seguirá o curso do ribeiro do Egito até o Mediterrâneo. Essa será a fronteira sul.

[[v26-47-20]]

^<<v26-47-20,20>>^ "Do lado oeste, o próprio Mediterrâneo será sua divisa desde a fronteira sul até o ponto em que começa a fronteira norte, de frente para Lebo-Hamate.

[[v26-47-21]]

^<<v26-47-21,21>>^ "Dividam a terra dentro dessas fronteiras entre as tribos de Israel.

[[v26-47-22]]

^<<v26-47-22,22>>^ Distribuam a terra como herança para si mesmos e para todos os estrangeiros que vivem entre vocês e criam os filhos em seu meio. Eles serão para vocês como israelitas de nascimento e receberão herança entre as tribos.

[[v26-47-23]]

^<<v26-47-23,23>>^ Esses estrangeiros receberão terras dentro do território da tribo com a qual eles vivem. Eu, o SENHOR Soberano, falei!"

'''

xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[&#60; Capítulo Anterior] | <<v26-47-0,Topo>> | xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[Próximo Capítulo &#62;]