include::./index.adoc[]

[[v26-29-0]]
=== Ezequiel, 29
// nvt ?, NVT - Nova Versão Transformadora

[[v26-29-1]]

^<<v26-29-1,1>>^ Em 7 de janeiro, no décimo ano do exílio do rei Joaquim, recebi esta mensagem do SENHOR:

[[v26-29-2]]

^<<v26-29-2,2>>^ "Filho do homem, volte o rosto para o Egito e profetize contra o faraó, rei do Egito, e todo o seu povo.

[[v26-29-3]]

^<<v26-29-3,3>>^ Transmita-lhes esta mensagem do SENHOR Soberano: "Sou seu inimigo, ó faraó, rei do Egito, grande monstro à espreita nos ribeiros do Nilo! Pois você disse: ‘O rio Nilo é meu; eu o fiz para mim’.

[[v26-29-4]]

^<<v26-29-4,4>>^ Porei anzóis em seu queixo e o arrastarei para a terra firme, com peixes presos a suas escamas.

[[v26-29-5]]

^<<v26-29-5,5>>^ Abandonarei no deserto, para morrerem, você e todos os peixes de seu rio. Ficará em campo aberto, sem ser enterrado, pois o entreguei como alimento aos animais selvagens e às aves.

[[v26-29-6]]

^<<v26-29-6,6>>^ Todo o povo do Egito saberá que eu sou o SENHOR, pois, para Israel, você foi apenas um bordão de juncos.

[[v26-29-7]]

^<<v26-29-7,7>>^ Quando Israel o usou como apoio, você rachou e lhe feriu o ombro. Quando ele colocou sobre você o peso, você desmoronou e o fez machucar as costas.

[[v26-29-8]]

^<<v26-29-8,8>>^ "Portanto, assim diz o SENHOR Soberano: Trarei a espada contra você, ó Egito, e destruirei tanto pessoas como animais.

[[v26-29-9]]

^<<v26-29-9,9>>^ A terra do Egito ficará seca e desolada, e os egípcios saberão que eu sou o SENHOR. "Porque você disse: ‘O rio Nilo é meu; eu o fiz’,

[[v26-29-10]]

^<<v26-29-10,10>>^ agora sou seu inimigo e de seu rio. Tornarei a terra do Egito completamente seca e desolada, desde Migdol até Assuã, e até o sul, na fronteira com a Etiópia.

[[v26-29-11]]

^<<v26-29-11,11>>^ Durante quarenta anos, ninguém habitará nem passará por ali, nem pessoas nem animais.

[[v26-29-12]]

^<<v26-29-12,12>>^ Farei do Egito uma nação desolada, cercada por outras nações desoladas. Suas cidades ficarão vazias e devastadas durante quarenta anos, cercadas por outras cidades devastadas. Eu espalharei os egípcios entre as nações do mundo.

[[v26-29-13]]

^<<v26-29-13,13>>^ "Mas assim diz o SENHOR Soberano: Depois de quarenta anos, trarei os egípcios de volta das nações entre as quais foram espalhados.

[[v26-29-14]]

^<<v26-29-14,14>>^ Restaurarei o Egito e trarei seu povo de volta à terra de Patros, no sul, de onde eles vieram. No entanto, continuará a ser um reino sem importância.

[[v26-29-15]]

^<<v26-29-15,15>>^ Será a mais humilde das nações e nunca voltará a se elevar acima de seus vizinhos. Eu a tornarei tão pequena que não dominará mais nação alguma.

[[v26-29-16]]

^<<v26-29-16,16>>^ "Então Israel não confiará mais na ajuda do Egito. O Egito ficará tão devastado que lembrará Israel do pecado que cometeu ao confiar nele no passado. Então saberão que eu sou o SENHOR Soberano".

[[v26-29-17]]

^<<v26-29-17,17>>^ Em 26 de abril, o primeiro dia do ano novo, durante o vigésimo sétimo ano do exílio do rei Joaquim, recebi esta mensagem do SENHOR:

[[v26-29-18]]

^<<v26-29-18,18>>^ "Filho do homem, o exército de Nabucodonosor, rei da Babilônia, lutou contra Tiro com tanto afinco que a cabeça de seus guerreiros foi esfregada até perder o cabelo e seus ombros ficarem esfolados. E, no entanto, Nabucodonosor e seu exército não conquistaram nenhum despojo para compensar todo o esforço.

[[v26-29-19]]

^<<v26-29-19,19>>^ Portanto, assim diz o SENHOR Soberano: Darei a terra do Egito a Nabucodonosor, rei da Babilônia. Ele levará sua riqueza e saqueará tudo que houver ali para pagar seu exército.

[[v26-29-20]]

^<<v26-29-20,20>>^ Sim, eu lhe dei a terra do Egito como recompensa por seu esforço, diz o SENHOR Soberano, pois ele estava trabalhando para mim quando destruiu Tiro.

[[v26-29-21]]

^<<v26-29-21,21>>^ "E virá o dia em que farei reviver a antiga glória de Israel, e suas palavras, Ezequiel, serão ouvidas abertamente. Então eles saberão que eu sou o SENHOR".

'''

xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[&#60; Capítulo Anterior] | <<v26-29-0,Topo>> | xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[Próximo Capítulo &#62;]