include::./index.adoc[]

[[v61-3-0]]
=== 2 Pedro, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v61-3-1]]

^<<v61-3-1,1>>^ Amados, esta é minha segunda carta a vocês, e em ambas procurei refrescar sua memória e incentivá-los a pensar com clareza.

[[v61-3-2]]

^<<v61-3-2,2>>^ Quero que se lembrem do que disseram os santos profetas muito tempo atrás e do que ordenou nosso Senhor e Salvador por meio dos apóstolos que lhes enviou.

[[v61-3-3]]

^<<v61-3-3,3>>^ Acima de tudo, quero alertá-los de que nos últimos dias surgirão escarnecedores que zombarão da verdade e seguirão os próprios desejos,

[[v61-3-4]]

^<<v61-3-4,4>>^ dizendo: "O que houve com a promessa de que ele voltaria? Desde antes do tempo de nossos antepassados, tudo permanece igual, como desde a criação do mundo".

[[v61-3-5]]

^<<v61-3-5,5>>^ Eles esquecem deliberadamente que Deus, por sua palavra, há muito tempo criou os céus e a terra seca, que fez surgir em meio às águas.

[[v61-3-6]]

^<<v61-3-6,6>>^ Depois, com água destruiu todo o mundo antigo, no dilúvio.

[[v61-3-7]]

^<<v61-3-7,7>>^ Pela mesma palavra, os céus e a terra que agora existem foram reservados para o fogo e estão guardados para o dia do julgamento, quando todos os perversos serão destruídos.

[[v61-3-8]]

^<<v61-3-8,8>>^ Logo, amados, não se esqueçam disto: para o Senhor, um dia é como mil anos, e mil anos como um dia.

[[v61-3-9]]

^<<v61-3-9,9>>^ Na verdade, o Senhor não demora em cumprir sua promessa, como pensam alguns. Pelo contrário, ele é paciente por causa de vocês. Não deseja que ninguém seja destruído, mas que todos se arrependam.

[[v61-3-10]]

^<<v61-3-10,10>>^ Contudo, o dia do Senhor virá como um ladrão. Os céus desaparecerão com terrível estrondo, e até os elementos serão consumidos pelo fogo, e a terra e tudo que nela há serão expostos.

[[v61-3-11]]

^<<v61-3-11,11>>^ Visto, portanto, que tudo ao redor será destruído, a vida de vocês deve ser caracterizada por santidade e devoção,

[[v61-3-12]]

^<<v61-3-12,12>>^ esperando o dia de Deus e já antecipando sua vinda. Nesse dia, ele incendiará os céus, e os elementos se derreterão nas chamas.

[[v61-3-13]]

^<<v61-3-13,13>>^ Nós, porém, aguardamos com grande expectativa os novos céus e a nova terra que ele prometeu, um mundo pleno de justiça.

[[v61-3-14]]

^<<v61-3-14,14>>^ Portanto, amados, enquanto esperam que essas coisas aconteçam, esforcem-se para levar uma vida pacífica, pura e sem culpa aos olhos de Deus.

[[v61-3-15]]

^<<v61-3-15,15>>^ E lembrem-se de que a paciência de nosso Senhor permite que as pessoas sejam salvas. Foi isso que nosso amado irmão Paulo lhes escreveu, com a sabedoria que lhe foi concedida.

[[v61-3-16]]

^<<v61-3-16,16>>^ Ele trata dessas questões em todas as suas cartas. Alguns de seus comentários são difíceis de entender, e os ignorantes e instáveis distorceram suas cartas, como fazem com outras partes das Escrituras. Como resultado, eles próprios serão destruídos.

[[v61-3-17]]

^<<v61-3-17,17>>^ Amados, vocês já sabem dessas coisas. Portanto, estejam atentos, a fim de que não sejam levados pelos erros desses perversos e percam sua firmeza.

[[v61-3-18]]

^<<v61-3-18,18>>^ Antes, cresçam na graça e no conhecimento de nosso Senhor e Salvador Jesus Cristo. A ele seja a glória, agora e para sempre! Amém.

'''

xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[&#60; Capítulo Anterior] | <<v61-3-0,Topo>> | xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[Próximo Capítulo &#62;]