include::./index.adoc[]

[[v61-2-0]]
=== 2 Pedro, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v61-2-1]]

^<<v61-2-1,1>>^ Contudo, assim como surgiram falsos profetas entre o povo de Israel, também surgirão falsos mestres entre vocês. Eles ensinarão astutamente heresias destrutivas e até negarão o Mestre que os resgatou, trazendo sobre si mesmos destruição repentina.

[[v61-2-2]]

^<<v61-2-2,2>>^ Muitos seguirão a imoralidade vergonhosa desses mestres, e por causa deles o caminho da verdade será difamado.

[[v61-2-3]]

^<<v61-2-3,3>>^ Em sua ganância, inventarão mentiras astutas para explorar vocês, mas eles já foram condenados há muito tempo, e sua destruição não tardará.

[[v61-2-4]]

^<<v61-2-4,4>>^ Pois Deus não poupou nem os anjos que pecaram. Ele os lançou no inferno, em abismos tenebrosos, onde ficarão presos até o dia do julgamento.

[[v61-2-5]]

^<<v61-2-5,5>>^ Não poupou o mundo antigo, mas protegeu Noé, que proclamava a justiça, e sete pessoas de sua família, quando destruiu com um dilúvio o mundo dos perversos.

[[v61-2-6]]

^<<v61-2-6,6>>^ Mais tarde, condenou as cidades de Sodoma e Gomorra e as transformou em montes de cinzas, como exemplo do que acontecerá aos perversos.

[[v61-2-7]]

^<<v61-2-7,7>>^ Em contrapartida, resgatou Ló, tirando-o de Sodoma, por ser ele um homem justo, afligido com a vergonhosa imoralidade dos perversos ao seu redor.

[[v61-2-8]]

^<<v61-2-8,8>>^ Sim, Ló era um homem justo, cuja alma justa era atormentada pela maldade que via e ouvia todos os dias.

[[v61-2-9]]

^<<v61-2-9,9>>^ Vemos, portanto, que o Senhor sabe resgatar das provações os que lhe são devotos e, ao mesmo tempo, manter os perversos sob castigo até o dia do julgamento.

[[v61-2-10]]

^<<v61-2-10,10>>^ Ele é particularmente severo com aqueles que seguem desejos e instintos distorcidos e desprezam a autoridade. Tais indivíduos são orgulhosos e arrogantes, e atrevem-se até a zombar de seres sobrenaturais.

[[v61-2-11]]

^<<v61-2-11,11>>^ Já os anjos, muito maiores em poder e em força, não ousam apresentar diante do Senhor uma acusação de blasfêmia contra esses seres.

[[v61-2-12]]

^<<v61-2-12,12>>^ Os falsos mestres são como criaturas irracionais movidas pelo instinto, que nascem para apanhar e morrer. Nada sabem sobre aqueles a quem insultam e, como animais, serão destruídos por sua própria corrupção.

[[v61-2-13]]

^<<v61-2-13,13>>^ Praticam o mal e receberão o mal como recompensa. Gostam de se entregar à imoralidade em plena luz do dia. São uma vergonha e uma mancha no meio de vocês, sentindo prazer em enganá-los enquanto participam de suas refeições.

[[v61-2-14]]

^<<v61-2-14,14>>^ Cometem adultério com os olhos e abrigam um desejo insaciável de pecar. Seduzem os instáveis e são bem treinados na ganância. Vivem sob maldição,

[[v61-2-15]]

^<<v61-2-15,15>>^ desviaram-se do caminho reto e seguem os passos de Balaão, filho de Beor, que amou a recompensa que receberia por fazer o mal.

[[v61-2-16]]

^<<v61-2-16,16>>^ Balaão, porém, foi refreado em sua loucura quando uma jumenta, que não fala, o repreendeu com voz humana.

[[v61-2-17]]

^<<v61-2-17,17>>^ Eles são como fontes secas ou a neblina levada pelo vento, e estão condenados às mais escuras trevas.

[[v61-2-18]]

^<<v61-2-18,18>>^ Com palavras vazias, proclamam sua grandeza imaginária e apelam para desejos carnais distorcidos a fim de atrair de volta ao pecado aqueles que mal escaparam de uma vida enganosa.

[[v61-2-19]]

^<<v61-2-19,19>>^ Prometem liberdade, mas eles próprios são escravos da corrupção. Pois cada um é escravo daquilo que o controla.

[[v61-2-20]]

^<<v61-2-20,20>>^ E, quando alguém escapa da maldade do mundo ao conhecer nosso Senhor e Salvador Jesus Cristo, mas depois se deixa emaranhar e se escravizar novamente pelo pecado, está pior que antes.

[[v61-2-21]]

^<<v61-2-21,21>>^ Teria sido melhor nunca haver conhecido o caminho da justiça do que, conhecendo-o, rejeitar a ordem recebida para viver de modo santo.

[[v61-2-22]]

^<<v61-2-22,22>>^ Neles se confirmam os provérbios: "O cão volta a seu próprio vômito" e "A porca lavada volta a revolver-se na lama".

'''

xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[&#60; Capítulo Anterior] | <<v61-2-0,Topo>> | xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[Próximo Capítulo &#62;]