include::./index.adoc[]

[[v61-1-0]]
=== 2 Pedro, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v61-1-1]]

^<<v61-1-1,1>>^ Eu, Simão Pedro, escravo e apóstolo de Jesus Cristo, escrevo esta carta a vocês que compartilham de nossa preciosa fé, concedida por meio da justiça de Jesus Cristo, nosso Deus e Salvador.

[[v61-1-2]]

^<<v61-1-2,2>>^ Que vocês tenham cada vez mais graça e paz à medida que crescem no conhecimento de Deus e de Jesus, nosso Senhor.

[[v61-1-3]]

^<<v61-1-3,3>>^ Deus, com seu poder divino, nos concede tudo de que necessitamos para uma vida de devoção, pelo conhecimento completo daquele que nos chamou para si por meio de sua glória e excelência.

[[v61-1-4]]

^<<v61-1-4,4>>^ E, por causa de sua glória e excelência, ele nos deu grandes e preciosas promessas. São elas que permitem a vocês participar da natureza divina e escapar da corrupção do mundo causada pelos desejos humanos.

[[v61-1-5]]

^<<v61-1-5,5>>^ Diante de tudo isso, esforcem-se ao máximo para corresponder a essas promessas. Acrescentem à fé a excelência moral; à excelência moral o conhecimento;

[[v61-1-6]]

^<<v61-1-6,6>>^ ao conhecimento o domínio próprio; ao domínio próprio a perseverança; à perseverança a devoção a Deus;

[[v61-1-7]]

^<<v61-1-7,7>>^ à devoção a Deus a fraternidade; e à fraternidade o amor.

[[v61-1-8]]

^<<v61-1-8,8>>^ Quanto mais crescerem nessas coisas, mais produtivos e úteis serão no conhecimento completo de nosso Senhor Jesus Cristo.

[[v61-1-9]]

^<<v61-1-9,9>>^ Mas aqueles que não se desenvolvem desse modo são praticamente cegos, vendo apenas o que está perto, e se esquecem de que foram purificados de seus antigos pecados.

[[v61-1-10]]

^<<v61-1-10,10>>^ Por isso, irmãos, trabalhem ainda mais arduamente para mostrar que, de fato, estão entre os que foram chamados e escolhidos. Façam essas coisas e jamais tropeçarão.

[[v61-1-11]]

^<<v61-1-11,11>>^ Assim, sua entrada no reino eterno de nosso Senhor e Salvador Jesus Cristo será acompanhada de grande honra.

[[v61-1-12]]

^<<v61-1-12,12>>^ Portanto, sempre lhes lembrarei estas coisas, embora já as saibam e estejam firmes na verdade que lhes foi ensinada.

[[v61-1-13]]

^<<v61-1-13,13>>^ E é apropriado que, enquanto eu viver, continue a lembrá-los.

[[v61-1-14]]

^<<v61-1-14,14>>^ Pois nosso Senhor Jesus Cristo me mostrou que, em breve, partirei desta vida,

[[v61-1-15]]

^<<v61-1-15,15>>^ por isso me esforçarei para garantir que vocês sempre se lembrem destas coisas depois de minha partida.

[[v61-1-16]]

^<<v61-1-16,16>>^ Porque não inventamos histórias engenhosas quando lhes falamos da poderosa vinda de nosso Senhor Jesus Cristo. Vimos com os próprios olhos seu esplendor majestoso,

[[v61-1-17]]

^<<v61-1-17,17>>^ quando ele recebeu honra e glória da parte de Deus, o Pai. A voz da glória suprema de Deus lhe disse: "Este é meu Filho amado, que me dá grande alegria".

[[v61-1-18]]

^<<v61-1-18,18>>^ Nós mesmos ouvimos essa voz do céu quando estávamos com ele no monte santo.

[[v61-1-19]]

^<<v61-1-19,19>>^ Além disso, temos a mensagem que os profetas proclamaram, que é digna de toda confiança. Prestem muita atenção ao que eles escreveram, pois suas palavras são como lâmpada que ilumina um lugar escuro, até que o dia clareie e a estrela da manhã brilhe no coração de vocês.

[[v61-1-20]]

^<<v61-1-20,20>>^ Acima de tudo, saibam que nenhuma profecia nas Escrituras surgiu do entendimento do próprio profeta,

[[v61-1-21]]

^<<v61-1-21,21>>^ nem de iniciativa humana. Esses homens foram impulsionados pelo Espírito Santo e falaram da parte de Deus.

'''

xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[&#60; Capítulo Anterior] | <<v61-1-0,Topo>> | xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[Próximo Capítulo &#62;]