include::./index.adoc[]

[[v38-10-0]]
=== Zacarias, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v38-10-1]]

^<<v38-10-1,1>>^ Peçam ao SENHOR chuva na primavera, pois ele forma as nuvens de tempestade. E ele enviará aguaceiros, para que todos os campos se tornem pastos verdes.

[[v38-10-2]]

^<<v38-10-2,2>>^ Os ídolos do lar dão conselhos inúteis, os adivinhadores só predizem mentiras, e os que interpretam sonhos proclamam falsidades que não trazem nenhuma consolação. Por isso meu povo anda sem rumo, como ovelhas perdidas que não têm pastor.

[[v38-10-3]]

^<<v38-10-3,3>>^ "Minha ira arde contra seus pastores, e eu castigarei esses líderes. Pois o SENHOR dos Exércitos chegou para cuidar de Judá, seu rebanho. Ele o tornará forte e glorioso, como um majestoso cavalo na batalha.

[[v38-10-4]]

^<<v38-10-4,4>>^ De Judá virão a pedra angular, a estaca da tenda, o arco para a batalha, e todos os governantes.

[[v38-10-5]]

^<<v38-10-5,5>>^ Serão como guerreiros poderosos na batalha, que pisam os inimigos na lama sob seus pés. Pois o SENHOR está com eles na luta, e derrubarão até os cavaleiros do inimigo.

[[v38-10-6]]

^<<v38-10-6,6>>^ "Fortalecerei Judá e livrarei Israel; eu os restaurarei, porque tenho compaixão deles. Será como se eu nunca os houvesse rejeitado, pois eu sou o SENHOR, seu Deus, e ouvirei seus clamores.

[[v38-10-7]]

^<<v38-10-7,7>>^ Os habitantes de Israel serão como guerreiros poderosos, e seu coração se alegrará como se fosse pelo vinho. Seus filhos também verão isso e exultarão; sim, seu coração se alegrará no SENHOR.

[[v38-10-8]]

^<<v38-10-8,8>>^ Quando eu assobiar para eles, virão até mim, pois os resgatei. Eles crescerão e se tornarão numerosos como antes.

[[v38-10-9]]

^<<v38-10-9,9>>^ Embora eu os tenha espalhado entre as nações, ainda se lembrarão de mim nas terras distantes. Eles e seus filhos sobreviverão e voltarão para Israel.

[[v38-10-10]]

^<<v38-10-10,10>>^ Eu os trarei de volta do Egito e os juntarei da Assíria. Eu os estabelecerei outra vez em Gileade e no Líbano, até que não haja mais espaço para todos.

[[v38-10-11]]

^<<v38-10-11,11>>^ Passarão pelo mar da aflição, pois as ondas do mar serão contidas, e as águas do Nilo secarão. O orgulho da Assíria será abatido, e o domínio do Egito chegará ao fim.

[[v38-10-12]]

^<<v38-10-12,12>>^ Por meu poder fortalecerei meu povo, e, pela autoridade de meu nome, viverão. Eu, o SENHOR, falei!"

'''

xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[&#60; Capítulo Anterior] | <<v38-10-0,Topo>> | xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[Próximo Capítulo &#62;]