include::./index.adoc[]

[[v38-1-0]]
=== Zacarias, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v38-1-1]]

^<<v38-1-1,1>>^ Em novembro do segundo ano do reinado de Dario, o SENHOR deu esta mensagem ao profeta Zacarias, filho de Berequias, neto de Ido:

[[v38-1-2]]

^<<v38-1-2,2>>^ "Eu, o SENHOR, fiquei extremamente irado com seus antepassados.

[[v38-1-3]]

^<<v38-1-3,3>>^ Portanto, diga ao povo: ‘Assim diz o SENHOR dos Exércitos: Voltem-se para mim, e eu me voltarei para vocês, diz o SENHOR dos Exércitos’.

[[v38-1-4]]

^<<v38-1-4,4>>^ Não sejam como seus antepassados, que não quiseram ouvir nem deram atenção quando os antigos profetas lhes disseram: ‘Assim diz o SENHOR dos Exércitos: Deixem seus caminhos maus e abandonem suas práticas perversas’.

[[v38-1-5]]

^<<v38-1-5,5>>^ "Onde estão agora seus antepassados? Morreram há muito tempo, assim como os profetas.

[[v38-1-6]]

^<<v38-1-6,6>>^ Mas tudo que eu disse e ordenei por meio de meus servos, os profetas, aconteceu a seus antepassados. Por isso, eles se arrependeram e disseram: ‘Recebemos do SENHOR dos Exércitos o que merecíamos. Ele fez o que havia prometido’".

[[v38-1-7]]

^<<v38-1-7,7>>^ Três meses depois, no dia 15 de fevereiro, o SENHOR deu outra mensagem ao profeta Zacarias, filho de Berequias, neto de Ido.

[[v38-1-8]]

^<<v38-1-8,8>>^ Numa visão durante a noite, vi um homem montado num cavalo vermelho, parado entre algumas murtas num desfiladeiro. Atrás dele, havia cavaleiros montados em cavalos vermelhos, marrons e brancos.

[[v38-1-9]]

^<<v38-1-9,9>>^ Perguntei ao anjo que falava comigo: "Meu senhor, o que significam estes cavalos?". "Eu lhe mostrarei", o anjo respondeu.

[[v38-1-10]]

^<<v38-1-10,10>>^ O cavaleiro que estava entre as murtas explicou: "Eles são aqueles que o SENHOR enviou para percorrer a terra".

[[v38-1-11]]

^<<v38-1-11,11>>^ Então os outros cavaleiros disseram ao anjo do SENHOR, que estava entre as murtas: "Percorremos toda a terra, e ela está em paz".

[[v38-1-12]]

^<<v38-1-12,12>>^ Quando o anjo do SENHOR ouviu isso, disse: "Ó SENHOR dos Exércitos, durante estes setenta anos tens estado irado com Jerusalém e as cidades de Judá. Quanto tempo levará para voltares a ter compaixão delas?".

[[v38-1-13]]

^<<v38-1-13,13>>^ E, ao anjo que falava comigo, o SENHOR respondeu com palavras boas e consoladoras.

[[v38-1-14]]

^<<v38-1-14,14>>^ Então o anjo me disse: "Proclame esta mensagem: ‘Assim diz o SENHOR dos Exércitos: Tenho grande zelo por Jerusalém e pelo monte Sião,

[[v38-1-15]]

^<<v38-1-15,15>>^ mas estou extremamente irado com as outras nações que agora vivem tranquilas. Eu estava apenas um pouco irado com meu povo, mas as nações fizeram que ele sofresse muito.

[[v38-1-16]]

^<<v38-1-16,16>>^ "‘Portanto, assim diz o SENHOR: Voltei a mostrar compaixão por Jerusalém. Meu templo será reconstruído, diz o SENHOR dos Exércitos, e serão tiradas medidas para a reconstrução de Jerusalém’.

[[v38-1-17]]

^<<v38-1-17,17>>^ "Diga também: ‘Assim diz o SENHOR dos Exércitos: As cidades de Israel voltarão a transbordar de prosperidade, e o SENHOR voltará a consolar Sião e escolherá Jerusalém para si’".

[[v38-1-18]]

^<<v38-1-18,18>>^ Então levantei os olhos e vi quatro chifres de animais.

[[v38-1-19]]

^<<v38-1-19,19>>^ "O que significam estes chifres?", perguntei ao anjo que falava comigo. Ele respondeu: "Estes chifres representam as nações que dispersaram Judá, Israel e Jerusalém".

[[v38-1-20]]

^<<v38-1-20,20>>^ Então o SENHOR me mostrou quatro ferreiros.

[[v38-1-21]]

^<<v38-1-21,21>>^ "O que estes homens vieram fazer?", perguntei. O anjo respondeu: "Os quatro chifres são as nações que dispersaram e humilharam Judá. Agora, os ferreiros vieram para aterrorizar, derrubar e destruir essas nações".

'''

xref:037-ageu/037-ageu-002.adoc#v37-2-0[&#60; Capítulo Anterior] | <<v38-1-0,Topo>> | xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[Próximo Capítulo &#62;]