include::./index.adoc[]

[[v38-4-0]]
=== Zacarias, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v38-4-1]]

^<<v38-4-1,1>>^ Então o anjo que falava comigo voltou e me despertou, como se eu tivesse estado dormindo.

[[v38-4-2]]

^<<v38-4-2,2>>^ "O que você vê agora?", ele perguntou. Respondi: "Vejo um candelabro de ouro maciço, com uma vasilha de azeite em cima. Ao redor da vasilha há sete lâmpadas, e cada lâmpada tem sete tubos com pavios.

[[v38-4-3]]

^<<v38-4-3,3>>^ Vejo também duas oliveiras, uma de cada lado da vasilha".

[[v38-4-4]]

^<<v38-4-4,4>>^ Então perguntei ao anjo: "O que é isto, meu senhor?".

[[v38-4-5]]

^<<v38-4-5,5>>^ "Você não sabe?", perguntou o anjo. "Não, meu senhor", respondi.

[[v38-4-6]]

^<<v38-4-6,6>>^ Então ele me disse: "Assim diz o SENHOR a Zorobabel: Não por força, nem por poder, mas pelo meu Espírito, diz o SENHOR dos Exércitos.

[[v38-4-7]]

^<<v38-4-7,7>>^ Nada será obstáculo para Zorobabel, nem mesmo uma grande montanha; diante dele ela se tornará uma planície! E, quando Zorobabel colocar em lugar a última pedra do templo, o povo gritará: ‘É pela graça! É pela graça!’".

[[v38-4-8]]

^<<v38-4-8,8>>^ Depois, recebi outra mensagem do SENHOR:

[[v38-4-9]]

^<<v38-4-9,9>>^ "Zorobabel lançou os alicerces deste templo, e ele o completará. Então vocês saberão que o SENHOR dos Exércitos me enviou.

[[v38-4-10]]

^<<v38-4-10,10>>^ Não desprezem os começos humildes, pois o SENHOR se alegra ao ver a obra começar, ao ver o prumo na mão de Zorobabel". (As sete lâmpadas representam os olhos do SENHOR, que percorrem toda a terra.)

[[v38-4-11]]

^<<v38-4-11,11>>^ Então perguntei ao anjo: "O que são as duas oliveiras, uma de cada lado do candelabro?

[[v38-4-12]]

^<<v38-4-12,12>>^ E o que são os dois ramos de oliveira que derramam azeite dourado por dois tubos de ouro?".

[[v38-4-13]]

^<<v38-4-13,13>>^ "Você não sabe?", ele perguntou. "Não, meu senhor", respondi.

[[v38-4-14]]

^<<v38-4-14,14>>^ Então ele me disse: "Eles representam os dois ungidos que ficam na presença do Senhor de toda a terra".

'''

xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[Próximo Capítulo &#62;]