include::./index.adoc[]

[[v38-9-0]]
=== Zacarias, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v38-9-1]]

^<<v38-9-1,1>>^ Esta é a sentença do SENHOR contra a terra de Hadraque e a cidade de Damasco, pois os olhos da humanidade, incluindo os de todas as tribos de Israel, estão voltados para o SENHOR.

[[v38-9-2]]

^<<v38-9-2,2>>^ A destruição é garantida para Hamate, perto de Damasco, e para as cidades de Tiro e Sidom, embora sejam tão astutas.

[[v38-9-3]]

^<<v38-9-3,3>>^ Tiro construiu fortalezas e tornou a prata e o ouro tão comuns quanto o pó e a lama nas ruas.

[[v38-9-4]]

^<<v38-9-4,4>>^ Mas o Senhor despojará Tiro de seus bens e lançará suas fortalezas no mar; a cidade será consumida pelo fogo.

[[v38-9-5]]

^<<v38-9-5,5>>^ Ascalom verá a queda de Tiro e se encherá de medo. Gaza tremerá de pavor, e o mesmo acontecerá a Ecrom, pois sua esperança será frustrada. O rei de Gaza será morto, e Ascalom ficará deserta;

[[v38-9-6]]

^<<v38-9-6,6>>^ estrangeiros ocuparão Asdode. Sim, acabarei com o orgulho dos filisteus;

[[v38-9-7]]

^<<v38-9-7,7>>^ arrancarei de sua boca a carne com sangue e de seus dentes tirarei os detestáveis sacrifícios. Então os filisteus que sobreviverem adorarão o nosso Deus e se tornarão uma nova família em Judá. Os filisteus de Ecrom se unirão ao meu povo, como fizeram em outros tempos os jebuseus.

[[v38-9-8]]

^<<v38-9-8,8>>^ Guardarei meu templo e o protegerei de exércitos invasores. Nunca mais estrangeiros opressores invadirão a terra de meu povo, pois agora eu a vigio de perto.

[[v38-9-9]]

^<<v38-9-9,9>>^ Alegre-se, ó povo de Sião! Exulte, ó preciosa Jerusalém! Vejam, seu rei está chegando; ele é justo e vitorioso, mas também é humilde e vem montado num jumento, num jumentinho, cria de jumenta.

[[v38-9-10]]

^<<v38-9-10,10>>^ Removerei de Israel os carros de guerra e, de Jerusalém, os cavalos. Destruirei as armas usadas na batalha, e seu rei trará paz às nações. Seu reino se estenderá de um mar a outro e do rio Eufrates até os confins da terra.

[[v38-9-11]]

^<<v38-9-11,11>>^ Por causa da aliança que fiz com vocês, aliança selada com sangue, livrarei seus prisioneiros da morte em um poço sem água.

[[v38-9-12]]

^<<v38-9-12,12>>^ Voltem para a fortaleza, todos vocês prisioneiros que ainda têm esperança! Hoje mesmo proclamo que lhes darei o dobro do que perderam.

[[v38-9-13]]

^<<v38-9-13,13>>^ Judá é meu arco, e Israel, minha flecha. Os filhos de Sião são minha espada, e, como um guerreiro, eu a empunharei contra os gregos.

[[v38-9-14]]

^<<v38-9-14,14>>^ O SENHOR aparecerá sobre seu povo; suas flechas sairão como relâmpagos! O SENHOR Soberano tocará a trombeta e atacará como um redemoinho vindo do sul.

[[v38-9-15]]

^<<v38-9-15,15>>^ O SENHOR dos Exércitos os protegerá, e eles lançarão pedras contra seus inimigos e os derrotarão. Gritarão na batalha, como se estivessem embriagados de vinho; ficarão cheios de sangue, como uma bacia, cobertos de sangue, como os cantos do altar.

[[v38-9-16]]

^<<v38-9-16,16>>^ Naquele dia, o SENHOR, seu Deus, salvará seu povo, como o pastor salva suas ovelhas. Eles brilharão em sua terra como joias numa coroa.

[[v38-9-17]]

^<<v38-9-17,17>>^ Ah, como serão belos e maravilhosos! A fartura de trigo dará vigor aos rapazes, e o vinho novo fará florescer as moças.

'''

xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[&#60; Capítulo Anterior] | <<v38-9-0,Topo>> | xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[Próximo Capítulo &#62;]