include::./index.adoc[]

[[v38-14-0]]
=== Zacarias, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v38-14-1]]

^<<v38-14-1,1>>^ Fiquem atentos, pois se aproxima o dia do SENHOR, em que seus bens serão saqueados diante de vocês!

[[v38-14-2]]

^<<v38-14-2,2>>^ Reunirei todas as nações para lutarem contra Jerusalém. A cidade será conquistada, as casas serão saqueadas, e as mulheres, violentadas. Metade da população será levada para o exílio, e o restante será deixado na cidade.

[[v38-14-3]]

^<<v38-14-3,3>>^ Então o SENHOR sairá para lutar contra essas nações, como fez no passado.

[[v38-14-4]]

^<<v38-14-4,4>>^ Naquele dia, seus pés estarão sobre o monte das Oliveiras, a leste de Jerusalém. O monte se dividirá ao meio, formando um vale muito amplo, de leste a oeste. Metade do monte se deslocará para o norte e metade para o sul.

[[v38-14-5]]

^<<v38-14-5,5>>^ Vocês fugirão pelo vale, pois ele se estenderá até Azal. Sim, vocês fugirão, como fugiram do terremoto nos dias de Uzias, rei de Judá. Então o SENHOR, meu Deus, virá com todos os seus santos.

[[v38-14-6]]

^<<v38-14-6,6>>^ Naquele dia, as fontes de luz deixarão de brilhar;

[[v38-14-7]]

^<<v38-14-7,7>>^ ainda assim, sempre será dia! Só o SENHOR sabe como isso acontecerá. Não haverá dia nem noite como sempre houve, pois mesmo à noite haverá claridade.

[[v38-14-8]]

^<<v38-14-8,8>>^ Naquele dia, fluirão de Jerusalém águas que dão vida; metade das águas correrá para o mar Morto e metade para o Mediterrâneo. Fluirão continuamente, tanto no verão como no inverno.

[[v38-14-9]]

^<<v38-14-9,9>>^ E o SENHOR será rei sobre toda a terra. Naquele dia, haverá um só SENHOR, e somente seu nome será adorado.

[[v38-14-10]]

^<<v38-14-10,10>>^ Toda a terra, desde Geba, ao norte de Judá, até Rimom, ao sul de Jerusalém, se tornará uma grande planície. Jerusalém, contudo, ficará em seu lugar elevado e será habitada desde o portão de Benjamim até o local do portão antigo, e dali até o portão da Esquina, e desde a torre de Hananel até as prensas de uvas do rei.

[[v38-14-11]]

^<<v38-14-11,11>>^ Jerusalém, por fim em segurança, ficará cheia de gente e nunca mais será amaldiçoada nem destruída.

[[v38-14-12]]

^<<v38-14-12,12>>^ O SENHOR enviará uma praga contra todos os povos que guerrearam contra Jerusalém. Eles se transformarão em cadáveres ambulantes, com a carne em decomposição. Seus olhos apodrecerão nas órbitas, e a língua apodrecerá na boca.

[[v38-14-13]]

^<<v38-14-13,13>>^ Naquele dia, o SENHOR os encherá de grande pânico, e eles lutarão uns contra os outros com as próprias mãos.

[[v38-14-14]]

^<<v38-14-14,14>>^ Judá também lutará em Jerusalém. A riqueza de todas as nações vizinhas será recolhida, grandes quantidades de ouro e prata e de roupas.

[[v38-14-15]]

^<<v38-14-15,15>>^ Essa mesma praga cairá sobre cavalos, mulas, camelos, jumentos e todos os outros animais dos acampamentos do inimigo.

[[v38-14-16]]

^<<v38-14-16,16>>^ No final, os inimigos que sobreviverem à praga subirão a Jerusalém a cada ano para adorar o Rei, o SENHOR dos Exércitos, e para celebrar a Festa das Cabanas.

[[v38-14-17]]

^<<v38-14-17,17>>^ Se alguma nação não quiser ir a Jerusalém para adorar o Rei, o SENHOR dos Exércitos, não receberá chuva.

[[v38-14-18]]

^<<v38-14-18,18>>^ Se o povo do Egito não quiser ir à festa, o SENHOR o castigará com as mesmas pragas que enviará sobre as outras nações que se recusarem a ir.

[[v38-14-19]]

^<<v38-14-19,19>>^ O Egito e as outras nações serão castigados se não forem celebrar a Festa das Cabanas.

[[v38-14-20]]

^<<v38-14-20,20>>^ Naquele dia, até mesmo os sinos dos cavalos terão gravadas estas palavras: Santo para o SENHOR. E as panelas no templo do SENHOR serão tão sagradas quanto as bacias usadas junto ao altar.

[[v38-14-21]]

^<<v38-14-21,21>>^ Na verdade, todas as panelas em Jerusalém e em Judá serão santas ao SENHOR dos Exércitos. Todos que vierem oferecer sacrifícios poderão usar qualquer uma delas para cozinhá-los. E, naquele dia, não haverá mais comerciantes no templo do SENHOR dos Exércitos.

'''

xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[&#60; Capítulo Anterior] | <<v38-14-0,Topo>> | xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[Próximo Capítulo &#62;]