include::./index.adoc[]

[[v38-7-0]]
=== Zacarias, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v38-7-1]]

^<<v38-7-1,1>>^ Em 7 de dezembro do quarto ano do reinado de Dario, o SENHOR deu outra mensagem a Zacarias.

[[v38-7-2]]

^<<v38-7-2,2>>^ O povo de Betel tinha enviado Sarezer, Regem-Meleque e seus homens para buscar o favor do Senhor

[[v38-7-3]]

^<<v38-7-3,3>>^ e para perguntar aos profetas e aos sacerdotes no templo do SENHOR dos Exércitos: "Devemos continuar a lamentar e jejuar no quinto mês, como temos feito por tantos anos?".

[[v38-7-4]]

^<<v38-7-4,4>>^ Em resposta, o SENHOR dos Exércitos me deu esta mensagem:

[[v38-7-5]]

^<<v38-7-5,5>>^ "Diga a todo o seu povo e a seus sacerdotes: ‘Durante estes setenta anos de exílio, vocês jejuaram e lamentaram no quinto e no sétimo mês, mas foi, de fato, para mim que jejuaram?

[[v38-7-6]]

^<<v38-7-6,6>>^ E, mesmo agora, não comem e bebem apenas para agradar a si mesmos?

[[v38-7-7]]

^<<v38-7-7,7>>^ Não é esta a mesma mensagem que o SENHOR proclamou por meio dos profetas no passado, quando Jerusalém e as cidades de Judá estavam cheias de gente, e quando havia muitos habitantes no Neguebe e nas colinas de Judá?’".

[[v38-7-8]]

^<<v38-7-8,8>>^ Então Zacarias recebeu esta mensagem do SENHOR:

[[v38-7-9]]

^<<v38-7-9,9>>^ "Assim diz o SENHOR dos Exércitos: Julguem com justiça e mostrem compaixão e bondade uns pelos outros.

[[v38-7-10]]

^<<v38-7-10,10>>^ Não oprimam as viúvas, nem os órfãos, nem os estrangeiros, nem os pobres. E não tramem o mal uns contra os outros.

[[v38-7-11]]

^<<v38-7-11,11>>^ "Seus antepassados não quiseram ouvir esta mensagem. Em rebeldia, deram-me as costas e taparam os ouvidos para não escutar.

[[v38-7-12]]

^<<v38-7-12,12>>^ Tornaram o coração duro como pedra, para não ouvir as instruções nem as mensagens que o SENHOR dos Exércitos lhes enviou por seu Espírito, por meio dos antigos profetas. Por isso o SENHOR dos Exércitos ficou tão irado com eles.

[[v38-7-13]]

^<<v38-7-13,13>>^ "Porque não quiseram ouvir quando eu os chamei, não os ouvi quando eles me chamaram, diz o SENHOR dos Exércitos.

[[v38-7-14]]

^<<v38-7-14,14>>^ Como um vendaval, eu os espalhei entre as nações distantes, que eles não conheciam. Sua terra ficou tão desolada que ninguém sequer passava por ela. Transformaram sua terra agradável num deserto".

'''

xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[&#60; Capítulo Anterior] | <<v38-7-0,Topo>> | xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[Próximo Capítulo &#62;]