include::./index.adoc[]

[[v38-13-0]]
=== Zacarias, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v38-13-1]]

^<<v38-13-1,1>>^ "Naquele dia, uma fonte será aberta para a linhagem de Davi e para os habitantes de Jerusalém, uma fonte para purificá-los de todos os seus pecados e impurezas.

[[v38-13-2]]

^<<v38-13-2,2>>^ "Naquele dia", diz o SENHOR dos Exércitos, "eliminarei da terra a idolatria, de modo que até o nome dos ídolos será esquecido. Removerei da terra os falsos profetas e o espírito de impureza.

[[v38-13-3]]

^<<v38-13-3,3>>^ Se alguém continuar a profetizar, seu próprio pai e sua própria mãe lhe dirão: ‘Você deve morrer, pois profetizou mentiras em nome do SENHOR’. E, enquanto ele estiver profetizando, seu pai e sua mãe o matarão.

[[v38-13-4]]

^<<v38-13-4,4>>^ "Naquele dia, as pessoas terão vergonha de dizer que têm o dom de profetizar. Ninguém vestirá roupas de profeta para enganar outros.

[[v38-13-5]]

^<<v38-13-5,5>>^ Dirá: ‘Não sou profeta; sou lavrador. Comecei a trabalhar no campo quando era menino’.

[[v38-13-6]]

^<<v38-13-6,6>>^ E se alguém perguntar: ‘Que feridas são essas em seu peito?’, ele responderá: ‘Fui ferido na casa de meus amigos’."

[[v38-13-7]]

^<<v38-13-7,7>>^ "Desperte, ó espada, contra meu pastor, o homem que é meu companheiro", diz o SENHOR dos Exércitos. "Fira o pastor, e as ovelhas serão dispersas, e eu me voltarei contra os cordeiros.

[[v38-13-8]]

^<<v38-13-8,8>>^ Dois terços dos habitantes da terra serão feridos e morrerão", diz o SENHOR, "mas restará um terço na terra.

[[v38-13-9]]

^<<v38-13-9,9>>^ Farei essa terça parte passar pelo fogo e a purificarei. Eu a refinarei como se refina a prata e a purificarei como se purifica o ouro. Ela invocará meu nome, e eu lhe responderei. Direi: ‘Este é meu povo’, e ela dirá: ‘O SENHOR é nosso Deus’."

'''

xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[&#60; Capítulo Anterior] | <<v38-13-0,Topo>> | xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[Próximo Capítulo &#62;]