include::./index.adoc[]

[[v38-2-0]]
=== Zacarias, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v38-2-1]]

^<<v38-2-1,1>>^ Quando levantei os olhos outra vez, vi um homem segurando uma corda de medir.

[[v38-2-2]]

^<<v38-2-2,2>>^ "Aonde você vai?", perguntei. Ele respondeu: "Vou medir Jerusalém para saber sua largura e seu comprimento".

[[v38-2-3]]

^<<v38-2-3,3>>^ Então o anjo que estava comigo foi se encontrar com outro anjo que vinha em sua direção.

[[v38-2-4]]

^<<v38-2-4,4>>^ O outro anjo disse: "Corra e diga àquele jovem: ‘Um dia Jerusalém ficará tão cheia de pessoas e animais que não haverá muros na cidade, pois não caberão todos dentro dela.

[[v38-2-5]]

^<<v38-2-5,5>>^ Então eu mesmo serei um muro de fogo ao redor de Jerusalém para protegê-la, diz o SENHOR. E eu serei a glória no meio da cidade’".

[[v38-2-6]]

^<<v38-2-6,6>>^ O SENHOR diz: "Saiam! Fujam da Babilônia, na terra do norte, pois eu os espalhei aos quatro ventos.

[[v38-2-7]]

^<<v38-2-7,7>>^ Saia, povo de Sião exilado na Babilônia!".

[[v38-2-8]]

^<<v38-2-8,8>>^ Depois de um período de glória, o SENHOR dos Exércitos me enviou contra as nações que saquearam vocês e disse: "Quem lhes faz mal, faz mal à menina dos meus olhos.

[[v38-2-9]]

^<<v38-2-9,9>>^ Levantarei minha mão para esmagar essas nações, e seus próprios escravos as saquearão". Então vocês saberão que o SENHOR dos Exércitos me enviou.

[[v38-2-10]]

^<<v38-2-10,10>>^ O SENHOR diz: "Cante e alegre-se, ó bela Sião, pois venho habitar em seu meio.

[[v38-2-11]]

^<<v38-2-11,11>>^ Naquele dia, muitas nações se juntarão ao SENHOR, e elas também serão meu povo. Habitarei em seu meio, e vocês saberão que o SENHOR dos Exércitos me enviou.

[[v38-2-12]]

^<<v38-2-12,12>>^ A terra de Judá será a propriedade do SENHOR na terra santa, e mais uma vez ele escolherá Jerusalém para ser sua cidade.

[[v38-2-13]]

^<<v38-2-13,13>>^ Cale-se diante do SENHOR toda a humanidade, pois ele se levanta de sua santa habitação".

'''

xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[Próximo Capítulo &#62;]