include::./index.adoc[]

[[v38-3-0]]
=== Zacarias, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v38-3-1]]

^<<v38-3-1,1>>^ Então o anjo me mostrou o sumo sacerdote Josué em pé diante do anjo do SENHOR. Satanás, o acusador, também estava ali, ao lado direito do anjo, e fazia acusações contra Josué.

[[v38-3-2]]

^<<v38-3-2,2>>^ O SENHOR disse a Satanás: "Eu, o SENHOR, rejeito suas acusações, Satanás. Sim, o SENHOR, que escolheu Jerusalém, o repreende. Este homem é como uma brasa tirada do fogo".

[[v38-3-3]]

^<<v38-3-3,3>>^ Josué continuava em pé diante do anjo, e suas roupas estavam imundas.

[[v38-3-4]]

^<<v38-3-4,4>>^ Então o anjo disse aos que ali estavam: "Tirem as roupas imundas dele". E, voltando-se para Josué, disse: "Veja, removi seus pecados e agora lhe dou roupas de festa".

[[v38-3-5]]

^<<v38-3-5,5>>^ Eu disse: "Também precisam colocar um turbante limpo em sua cabeça". E eles colocaram um turbante limpo na cabeça dele e o vestiram com as roupas novas, enquanto o anjo do SENHOR permanecia ali.

[[v38-3-6]]

^<<v38-3-6,6>>^ Então o anjo do SENHOR falou solenemente a Josué e disse:

[[v38-3-7]]

^<<v38-3-7,7>>^ "Assim diz o SENHOR dos Exércitos: Se você andar em meus caminhos e seguir meus preceitos, receberá autoridade sobre meu templo e seus pátios. Deixarei que ande junto com os outros que aqui estão.

[[v38-3-8]]

^<<v38-3-8,8>>^ "Ouçam, ó sumo sacerdote Josué e todos os outros sacerdotes. Vocês são símbolo de coisas futuras. Em breve trarei meu servo, o Renovo.

[[v38-3-9]]

^<<v38-3-9,9>>^ Agora, olhem para a pedra que coloquei diante de Josué, uma única pedra com sete faces. Gravarei nela uma inscrição, diz o SENHOR dos Exércitos, e em um só dia removerei os pecados desta terra.

[[v38-3-10]]

^<<v38-3-10,10>>^ "E, naquele dia, diz o SENHOR dos Exércitos, cada um de vocês convidará seu próximo para sentar-se debaixo de sua videira e de sua figueira".

'''

xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[&#60; Capítulo Anterior] | <<v38-3-0,Topo>> | xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[Próximo Capítulo &#62;]