include::./index.adoc[]

[[v38-8-0]]
=== Zacarias, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v38-8-1]]

^<<v38-8-1,1>>^ Então recebi outra mensagem do SENHOR dos Exércitos:

[[v38-8-2]]

^<<v38-8-2,2>>^ "Assim diz o SENHOR dos Exércitos: Tenho muito ciúme do monte Sião e sou consumido de zelo por ele!

[[v38-8-3]]

^<<v38-8-3,3>>^ "Assim diz o SENHOR: Voltarei para o monte Sião e habitarei em Jerusalém. Então Jerusalém será chamada Cidade Fiel, e o monte do SENHOR dos Exércitos será chamado Monte Santo.

[[v38-8-4]]

^<<v38-8-4,4>>^ "Assim diz o SENHOR dos Exércitos: Homens e mulheres idosos voltarão a caminhar apoiados em suas bengalas nas ruas de Jerusalém e se sentarão juntos nas praças,

[[v38-8-5]]

^<<v38-8-5,5>>^ e as ruas da cidade ficarão cheias de meninos e meninas brincando.

[[v38-8-6]]

^<<v38-8-6,6>>^ "Assim diz o SENHOR dos Exércitos: No momento, isso pode lhes parecer impossível, ó remanescente do povo. Mas acaso é impossível para mim?, diz o SENHOR dos Exércitos.

[[v38-8-7]]

^<<v38-8-7,7>>^ "Assim diz o SENHOR dos Exércitos: Podem ter certeza de que resgatarei meu povo dos lugares para onde foram levados no leste e no oeste.

[[v38-8-8]]

^<<v38-8-8,8>>^ Eu os trarei de volta para que habitem em Jerusalém. Eles serão o meu povo, e eu serei o seu Deus fiel e justo.

[[v38-8-9]]

^<<v38-8-9,9>>^ "Assim diz o SENHOR dos Exércitos: Sejam fortes e completem a tarefa! Desde que lançaram os alicerces do templo do SENHOR dos Exércitos, vocês têm ouvido o que os profetas dizem a respeito de terminar a obra.

[[v38-8-10]]

^<<v38-8-10,10>>^ Antes de iniciarem os trabalhos do templo, não havia dinheiro para contratar pessoas ou pagar por animais. Nenhum viajante estava seguro, pois havia inimigos por toda parte. Eu os havia incitado uns contra os outros.

[[v38-8-11]]

^<<v38-8-11,11>>^ "Agora, porém, não tratarei mais o remanescente de meu povo como o tratei no passado, diz o SENHOR dos Exércitos.

[[v38-8-12]]

^<<v38-8-12,12>>^ Pois, agora, plantarão as sementes em paz. As videiras ficarão carregadas de uvas, a terra produzirá suas colheitas, e os céus derramarão o orvalho. Darei essas bênçãos como herança ao remanescente deste povo.

[[v38-8-13]]

^<<v38-8-13,13>>^ Entre as outras nações, Judá e Israel se tornaram símbolo de nação amaldiçoada, mas não será mais assim! Agora eu os resgatarei e os transformarei em bênção. Portanto, não tenham medo. Sejam fortes e continuem a reconstruir o templo!

[[v38-8-14]]

^<<v38-8-14,14>>^ "Pois assim diz o SENHOR dos Exércitos: Eu estava decidido a castigá-los quando seus antepassados provocaram minha ira, e não voltei atrás, diz o SENHOR dos Exércitos.

[[v38-8-15]]

^<<v38-8-15,15>>^ Agora, porém, estou decidido a abençoar Jerusalém e o povo de Judá. Portanto, não tenham medo.

[[v38-8-16]]

^<<v38-8-16,16>>^ Isto é o que vocês devem fazer: Digam a verdade uns aos outros. Em seus tribunais, pronunciem sentenças justas, que conduzam à paz.

[[v38-8-17]]

^<<v38-8-17,17>>^ Não tramem o mal uns contra os outros. Não se agradem de fazer juramentos falsos. Odeio todas essas coisas, diz o SENHOR".

[[v38-8-18]]

^<<v38-8-18,18>>^ Esta é outra mensagem que recebi do SENHOR dos Exércitos.

[[v38-8-19]]

^<<v38-8-19,19>>^ "Assim diz o SENHOR dos Exércitos: Os jejuns habituais que vocês têm observado no quarto mês, bem como no quinto, no sétimo e no décimo mês, chegaram ao fim. Eles se tornarão festas de alegria e celebração para o povo de Judá. Portanto, amem a verdade e a paz.

[[v38-8-20]]

^<<v38-8-20,20>>^ "Assim diz o SENHOR dos Exércitos: Pessoas de nações e cidades de todo lugar virão a Jerusalém.

[[v38-8-21]]

^<<v38-8-21,21>>^ Os habitantes de uma cidade dirão aos habitantes de outra: ‘Venham conosco a Jerusalém para pedir ao SENHOR que nos abençoe. Vamos adorar o SENHOR dos Exércitos. Estou decidido a ir’.

[[v38-8-22]]

^<<v38-8-22,22>>^ Muitos povos e nações poderosas virão a Jerusalém para buscar o SENHOR dos Exércitos e pedir que ele os abençoe.

[[v38-8-23]]

^<<v38-8-23,23>>^ "Assim diz o SENHOR dos Exércitos: Naquele dia, dez homens de nações e línguas diferentes agarrarão a barra das vestes de um judeu e dirão: ‘Deixe que o acompanhemos, pois ouvimos dizer que Deus está com vocês’".

'''

xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[&#60; Capítulo Anterior] | <<v38-8-0,Topo>> | xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[Próximo Capítulo &#62;]