include::./index.adoc[]

[[v38-5-0]]
=== Zacarias, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v38-5-1]]

^<<v38-5-1,1>>^ Levantei os olhos novamente e vi um rolo que voava.

[[v38-5-2]]

^<<v38-5-2,2>>^ "O que você vê?", perguntou o anjo. "Vejo um rolo voando", respondi. "Parece ter uns nove metros de comprimento e a metade disso de largura."

[[v38-5-3]]

^<<v38-5-3,3>>^ Em seguida, ele me disse: "Nesse rolo está a maldição que sai para toda a terra. Uma maldição do rolo diz que os ladrões serão expulsos da terra; a outra maldição diz que os que juram falsamente serão expulsos da terra.

[[v38-5-4]]

^<<v38-5-4,4>>^ E assim diz o SENHOR dos Exércitos: Envio esta maldição à casa de todo ladrão e à casa de todo que jura falsamente pelo meu nome. E minha maldição permanecerá na casa e a destruirá completamente, até sua madeira e suas pedras".

[[v38-5-5]]

^<<v38-5-5,5>>^ Então o anjo que falava comigo se adiantou e disse: "Levante os olhos e veja o que está vindo".

[[v38-5-6]]

^<<v38-5-6,6>>^ "O que é?", perguntei. Ele respondeu: "É um cesto para medir cereais e está cheio do pecado de todos que habitam a terra".

[[v38-5-7]]

^<<v38-5-7,7>>^ Então a tampa de chumbo do cesto foi levantada, e dentro dele havia uma mulher sentada.

[[v38-5-8]]

^<<v38-5-8,8>>^ O anjo disse: "A mulher se chama Perversidade", e a empurrou de volta para dentro do cesto e fechou a tampa.

[[v38-5-9]]

^<<v38-5-9,9>>^ Em seguida, levantei os olhos e vi duas mulheres voando em nossa direção, planando no vento. Suas asas pareciam asas de cegonha, e elas pegaram o cesto e o carregaram pelos ares.

[[v38-5-10]]

^<<v38-5-10,10>>^ "Para onde estão levando o cesto?", perguntei ao anjo.

[[v38-5-11]]

^<<v38-5-11,11>>^ Ele respondeu: "Para a terra da Babilônia, onde construirão um templo para ele. E, quando o templo estiver pronto, colocarão o cesto ali, em seu pedestal".

'''

xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[&#60; Capítulo Anterior] | <<v38-5-0,Topo>> | xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[Próximo Capítulo &#62;]