include::./index.adoc[]

[[v38-12-0]]
=== Zacarias, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v38-12-1]]

^<<v38-12-1,1>>^ Esta é a mensagem que o SENHOR anunciou acerca do destino de Israel: "Mensagem do SENHOR, que estendeu os céus, lançou os alicerces da terra e formou o espírito humano.

[[v38-12-2]]

^<<v38-12-2,2>>^ Farei que Jerusalém seja como uma bebida que deixará as nações vizinhas cambaleando quando enviarem seus exércitos para cercar Jerusalém e Judá.

[[v38-12-3]]

^<<v38-12-3,3>>^ Naquele dia, transformarei Jerusalém numa pedra pesada. Todas as nações se reunirão contra ela para tentar movê-la, mas só ferirão a si mesmas.

[[v38-12-4]]

^<<v38-12-4,4>>^ "Naquele dia", diz o SENHOR, "farei que todos os cavalos entrem em pânico e todos os cavaleiros enlouqueçam. Cuidarei do povo de Judá, mas cegarei todos os cavalos de seus inimigos.

[[v38-12-5]]

^<<v38-12-5,5>>^ E as famílias de Judá pensarão: ‘Os habitantes de Jerusalém encontraram força no SENHOR dos Exércitos, seu Deus’.

[[v38-12-6]]

^<<v38-12-6,6>>^ "Naquele dia, farei que as famílias de Judá sejam como uma chama que põe fogo num monte de lenha, ou como uma tocha acesa no meio de feixes de cereal. Elas incendiarão todas as nações vizinhas, à direita e à esquerda, enquanto os habitantes de Jerusalém permanecerão em segurança.

[[v38-12-7]]

^<<v38-12-7,7>>^ "O SENHOR dará vitória primeiro ao restante de Judá, antes de Jerusalém, para que a honra dos habitantes de Jerusalém e da linhagem real de Davi não seja superior à honra do restante de Judá.

[[v38-12-8]]

^<<v38-12-8,8>>^ Naquele dia, o SENHOR defenderá os habitantes de Jerusalém; o mais fraco entre eles será como o rei Davi, e os descendentes do rei serão como Deus, como o anjo do SENHOR que vai diante deles.

[[v38-12-9]]

^<<v38-12-9,9>>^ Pois, naquele dia, começarei a destruir todas as nações que atacarem Jerusalém.

[[v38-12-10]]

^<<v38-12-10,10>>^ "Então derramarei um espírito de graça e oração sobre a linhagem de Davi e os habitantes de Jerusalém. Olharão para aquele a quem transpassaram e chorarão por ele como quem chora a morte do filho único; lamentarão amargamente por ele, como quem lamenta a perda do filho mais velho.

[[v38-12-11]]

^<<v38-12-11,11>>^ Naquele dia, o pranto em Jerusalém será como o grande pranto por Hadade-Rimom no vale de Megido.

[[v38-12-12]]

^<<v38-12-12,12>>^ "Todo o Israel chorará, cada família separadamente, os maridos longe das esposas. A família de Davi chorará separadamente, bem como a família de Natã,

[[v38-12-13]]

^<<v38-12-13,13>>^ a família de Levi e a família de Simei.

[[v38-12-14]]

^<<v38-12-14,14>>^ Cada uma das famílias sobreviventes de Judá chorará separadamente, os maridos longe das esposas."

'''

xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[&#60; Capítulo Anterior] | <<v38-12-0,Topo>> | xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[Próximo Capítulo &#62;]