include::./index.adoc[]

[[v38-6-0]]
=== Zacarias, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v38-6-1]]

^<<v38-6-1,1>>^ Então levantei os olhos novamente e vi quatro carros de guerra que saíam de entre dois montes de bronze.

[[v38-6-2]]

^<<v38-6-2,2>>^ Cavalos vermelhos puxavam o primeiro carro, cavalos pretos puxavam o segundo,

[[v38-6-3]]

^<<v38-6-3,3>>^ cavalos brancos puxavam o terceiro, e cavalos malhados e fortes puxavam o quarto.

[[v38-6-4]]

^<<v38-6-4,4>>^ "O que significam estes cavalos, meu senhor?", perguntei ao anjo que falava comigo.

[[v38-6-5]]

^<<v38-6-5,5>>^ O anjo respondeu: "Eles são os quatro espíritos do céu que estão diante do Senhor de toda a terra. Saem para fazer o trabalho dele.

[[v38-6-6]]

^<<v38-6-6,6>>^ O carro de guerra com cavalos pretos vai para o norte, o carro de guerra com cavalos brancos vai para o oeste e o carro de guerra com cavalos malhados vai para o sul".

[[v38-6-7]]

^<<v38-6-7,7>>^ Os cavalos fortes estavam impacientes para sair e percorrer a terra. Então o SENHOR disse: "Vão e percorram a terra!", e eles partiram de imediato.

[[v38-6-8]]

^<<v38-6-8,8>>^ Em seguida, o SENHOR me chamou e disse: "Veja, os que foram para o norte deram descanso ao meu Espírito ali na terra do norte".

[[v38-6-9]]

^<<v38-6-9,9>>^ Então recebi outra mensagem do SENHOR:

[[v38-6-10]]

^<<v38-6-10,10>>^ "Heldai, Tobias e Jedaías trarão presentes de prata e de ouro dos judeus exilados na Babilônia. Assim que chegarem, vá ao encontro deles na casa de Josias, filho de Sofonias.

[[v38-6-11]]

^<<v38-6-11,11>>^ Aceite os presentes e faça uma coroa usando o ouro e a prata. Depois, coloque-a na cabeça do sumo sacerdote Josué, filho de Jeozadaque.

[[v38-6-12]]

^<<v38-6-12,12>>^ Diga-lhe: ‘Assim diz o SENHOR dos Exércitos: Aqui está o homem chamado Renovo. Ele brotará de seu lugar e construirá o templo do SENHOR.

[[v38-6-13]]

^<<v38-6-13,13>>^ Sim, ele construirá o templo do SENHOR. Então receberá a honra devida e, de seu trono, governará como rei. De seu trono, também servirá como sacerdote, e haverá harmonia perfeita entre as duas funções’.

[[v38-6-14]]

^<<v38-6-14,14>>^ "A coroa será um memorial no templo do SENHOR para honrar aqueles que a ofereceram: Heldai, Tobias, Jedaías e Josias, filho de Sofonias".

[[v38-6-15]]

^<<v38-6-15,15>>^ Pessoas virão de terras distantes para reconstruir o templo do SENHOR. Quando isso acontecer, vocês saberão que o SENHOR dos Exércitos me enviou. Tudo isso acontecerá se vocês obedecerem fielmente às ordens do SENHOR, seu Deus.

'''

xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[Próximo Capítulo &#62;]