include::./index.adoc[]

[[v27-7-0]]
=== Daniel, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v27-7-1]]

^<<v27-7-1,1>>^ Anteriormente, durante o primeiro ano do reinado de Belsazar, rei da Babilônia, Daniel teve um sonho e visões enquanto estava deitado em sua cama. Escreveu o que havia sonhado e foi isto que viu.

[[v27-7-2]]

^<<v27-7-2,2>>^ Naquela noite em minha visão, eu, Daniel, vi uma tempestade que agitava o grande mar, com ventos fortes que sopravam de todas as direções.

[[v27-7-3]]

^<<v27-7-3,3>>^ Então, saíram da água quatro bestas enormes, cada uma diferente das demais.

[[v27-7-4]]

^<<v27-7-4,4>>^ A primeira besta era como um leão com asas de águia. Enquanto eu observava, suas asas foram arrancadas e ela ficou em pé no chão, sobre as duas patas traseiras, como um ser humano. E lhe foi dada mente humana.

[[v27-7-5]]

^<<v27-7-5,5>>^ Vi, então, a segunda besta, e ela se parecia com um urso. Levantou-se sobre um dos lados e tinha na boca, entre os dentes, três costelas. E lhe foi dito: "Levante-se! Devore a carne de muitos!".

[[v27-7-6]]

^<<v27-7-6,6>>^ Em seguida, surgiu a terceira dessas bestas, que se parecia com um leopardo. Tinha quatro asas de ave nas costas e quatro cabeças. E lhe foi dada grande autoridade.

[[v27-7-7]]

^<<v27-7-7,7>>^ Então, em minha visão naquela noite, vi uma quarta besta, terrível, assustadora e muito forte. Devorava e despedaçava suas vítimas com grandes dentes de ferro e esmagava os restos debaixo de seus pés. Era diferente das outras três e tinha dez chifres.

[[v27-7-8]]

^<<v27-7-8,8>>^ Enquanto eu olhava para os chifres, de repente apareceu no meio deles outro chifre pequeno. Três dos chifres maiores foram arrancados pela raiz para dar lugar a ele. Esse chifre pequeno tinha olhos, como de homem, e uma boca que falava com arrogância.

[[v27-7-9]]

^<<v27-7-9,9>>^ Enquanto eu observava, foram colocados alguns tronos, e o Ancião se sentou para julgar. Suas roupas eram brancas como a neve, e seu cabelo, como a mais pura lã. Sentava-se num trono de fogo, com rodas de chamas ardentes,

[[v27-7-10]]

^<<v27-7-10,10>>^ e um rio de fogo brotava de sua presença. Milhões de anjos o serviam, muitos milhões estavam diante dele. O tribunal iniciou o julgamento, e os livros foram abertos.

[[v27-7-11]]

^<<v27-7-11,11>>^ Continuei a observar, pois podia ouvir as palavras arrogantes do pequeno chifre. Fiquei olhando até que a quarta besta foi morta e seu corpo, destruído e lançado ao fogo.

[[v27-7-12]]

^<<v27-7-12,12>>^ Então foi tirada a autoridade das outras três bestas, mas elas tiveram permissão de viver por mais algum tempo.

[[v27-7-13]]

^<<v27-7-13,13>>^ Depois, em minha visão naquela noite, vi alguém semelhante a um filho de homem vindo com as nuvens do céu. Ele se aproximou do Ancião e foi conduzido à sua presença.

[[v27-7-14]]

^<<v27-7-14,14>>^ Recebeu autoridade, honra e soberania, para que povos de todas as raças, nações e línguas lhe obedecessem. Seu domínio é eterno; não terá fim. Seu reino jamais será destruído.

[[v27-7-15]]

^<<v27-7-15,15>>^ Eu, Daniel, fiquei perturbado com tudo que tinha visto, e minhas visões me aterrorizaram.

[[v27-7-16]]

^<<v27-7-16,16>>^ Por isso aproximei-me de um dos que estavam em pé junto ao trono e perguntei o que tudo aquilo significava. Ele explicou:

[[v27-7-17]]

^<<v27-7-17,17>>^ "Essas quatro grandes bestas representam quatro reinos que surgirão da terra.

[[v27-7-18]]

^<<v27-7-18,18>>^ No final, porém, o reino será entregue ao povo santo do Altíssimo, e eles dominarão para todo o sempre".

[[v27-7-19]]

^<<v27-7-19,19>>^ Então eu quis saber o verdadeiro signifi-cado da quarta besta, tão diferente das demais e tão aterrorizante. Ela havia devorado e despedaçado suas vítimas com dentes de ferro e garras de bronze e esmagado os restos com os pés.

[[v27-7-20]]

^<<v27-7-20,20>>^ Também quis saber sobre os dez chifres em sua cabeça e o pequeno chifre que surgiu depois e derrubou três dos outros chifres. Esse chifre parecia mais forte que os demais e tinha olhos humanos e uma boca que falava com arrogância.

[[v27-7-21]]

^<<v27-7-21,21>>^ Enquanto eu observava, esse chifre guerreava contra o povo santo de Deus e o derrotava,

[[v27-7-22]]

^<<v27-7-22,22>>^ até que o Ancião, o Altíssimo, veio e pronunciou a sentença em favor de seu povo santo. Então chegou o tempo de o povo santo tomar posse do reino.

[[v27-7-23]]

^<<v27-7-23,23>>^ Depois ele me disse: "A quarta besta é o quarto reino que dominará a terra, e será diferente de todos os outros. Devorará o mundo inteiro, pisoteará e esmagará tudo que estiver em seu caminho.

[[v27-7-24]]

^<<v27-7-24,24>>^ Seus dez chifres são dez reis que governarão esse império. Então surgirá outro rei, diferente dos dez, que subjugará três reis.

[[v27-7-25]]

^<<v27-7-25,25>>^ Ele desafiará o Altíssimo e oprimirá o povo santo do Altíssimo. Tentará mudar suas festas sagradas e suas leis, e eles serão colocados sob o controle dele por um tempo, tempos, e meio tempo.

[[v27-7-26]]

^<<v27-7-26,26>>^ "Contudo, o tribunal o julgará, e todo o seu poder será tirado e completamente destruído.

[[v27-7-27]]

^<<v27-7-27,27>>^ Então serão dados ao povo santo do Altíssimo a soberania, o poder e a grandeza de todos os reinos debaixo dos céus. O reino do Altíssimo permanecerá para sempre, e todos os governantes o servirão e lhe obedecerão".

[[v27-7-28]]

^<<v27-7-28,28>>^ Assim terminou a visão. Eu, Daniel, fiquei aterrorizado por causa de meus pensamentos e meu rosto ficou pálido de medo, mas não contei essas coisas a ninguém.

'''

xref:027-daniel/027-daniel-006.adoc#v27-6-0[&#60; Capítulo Anterior] | <<v27-7-0,Topo>> | xref:027-daniel/027-daniel-008.adoc#v27-8-0[Próximo Capítulo &#62;]