include::./index.adoc[]

[[v27-6-0]]
=== Daniel, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v27-6-1]]

^<<v27-6-1,1>>^ O rei Dario resolveu dividir o reino em 120 províncias e nomeou um alto funcionário para governar cada uma delas.

[[v27-6-2]]

^<<v27-6-2,2>>^ O rei também escolheu como administradores Daniel e outros dois homens, para que supervisionassem os altos funcionários e protegessem os interesses do rei.

[[v27-6-3]]

^<<v27-6-3,3>>^ Em pouco tempo, Daniel se mostrou mais capaz que todos os outros administradores e altos funcionários. Por causa da grande capacidade de Daniel, o rei planejava colocá-lo à frente de todo o reino.

[[v27-6-4]]

^<<v27-6-4,4>>^ Os outros administradores e altos funcionários começaram a procurar falhas no modo como Daniel conduzia as questões de governo, mas nada encontraram para criticar ou condenar. Ele era leal, sempre responsável e digno de confiança.

[[v27-6-5]]

^<<v27-6-5,5>>^ Por isso, concluíram: "Nossa única chance de encontrar algum motivo para acusar Daniel será em relação às leis de seu Deus".

[[v27-6-6]]

^<<v27-6-6,6>>^ Então os administradores e os altos funcionários foram até o rei e lhe disseram: "Que o rei Dario viva para sempre!

[[v27-6-7]]

^<<v27-6-7,7>>^ Nós administradores, oficiais, altos funcionários, conselheiros e governadores estamos todos de acordo que o rei deve decretar uma lei a ser cumprida rigorosamente. Dê ordens para que, nos próximos trinta dias, qualquer pessoa que orar a alguém, divino ou humano, exceto ao rei, seja lançada na cova dos leões.

[[v27-6-8]]

^<<v27-6-8,8>>^ Agora, ó rei, decrete e assine essa lei para que não possa ser mudada, como lei oficial dos medos e dos persas, que não pode ser revogada".

[[v27-6-9]]

^<<v27-6-9,9>>^ E o rei Dario assinou a lei.

[[v27-6-10]]

^<<v27-6-10,10>>^ Quando Daniel soube que a lei tinha sido assinada, foi para casa e, como de costume, ajoelhou-se no quarto no andar de cima, com as janelas abertas na direção de Jerusalém. Orava três vezes por dia e dava graças a seu Deus.

[[v27-6-11]]

^<<v27-6-11,11>>^ Os oficiais foram juntos à casa de Daniel e o encontraram orando e pedindo ajuda a Deus.

[[v27-6-12]]

^<<v27-6-12,12>>^ Então foram diretamente ao rei e o lembraram da lei: "O rei não assinou um decreto ordenando que qualquer um que orasse a alguém, divino ou humano, exceto ao rei, fosse lançado na cova dos leões?". "Sim", respondeu o rei. "Essa decisão está em vigor; é uma lei oficial dos medos e dos persas, que não pode ser revogada."

[[v27-6-13]]

^<<v27-6-13,13>>^ Então disseram ao rei: "Aquele homem, Daniel, um dos exilados de Judá, não dá importância ao rei nem à sua lei. Continua a orar ao Deus dele três vezes por dia".

[[v27-6-14]]

^<<v27-6-14,14>>^ Quando o rei ouviu isso, ficou muito angustiado e procurou uma forma de salvar Daniel. Passou o resto do dia pensando num modo de livrá-lo dessa situação.

[[v27-6-15]]

^<<v27-6-15,15>>^ À noite, os homens foram juntos ao rei e disseram: "Ó rei, o senhor sabe que, conforme a lei dos medos e dos persas, nenhum decreto que o rei assina pode ser revogado".

[[v27-6-16]]

^<<v27-6-16,16>>^ Por fim, o rei deu ordens para que Daniel fosse preso e lançado na cova dos leões. O rei lhe disse: "Que seu Deus, a quem você serve fielmente, o livre".

[[v27-6-17]]

^<<v27-6-17,17>>^ Então trouxeram uma pedra e a colocaram sobre a abertura da cova. O rei selou a pedra com seu anel e com os anéis de seus nobres, para que ninguém pudesse resgatar Daniel.

[[v27-6-18]]

^<<v27-6-18,18>>^ O rei voltou a seu palácio e passou a noite em jejum. Não quis nenhum dos divertimentos habituais e não conseguiu dormir a noite inteira.

[[v27-6-19]]

^<<v27-6-19,19>>^ De manhã bem cedo, levantou-se e foi apressadamente à cova dos leões.

[[v27-6-20]]

^<<v27-6-20,20>>^ Quando chegou lá, gritou angustiado: "Daniel, servo do Deus vivo! O Deus a quem você serve tão fielmente pôde livrá-lo dos leões?".

[[v27-6-21]]

^<<v27-6-21,21>>^ Daniel respondeu: "Que o rei viva para sempre!

[[v27-6-22]]

^<<v27-6-22,22>>^ Meu Deus enviou seu anjo para fechar a boca dos leões de modo que não me fizessem mal, pois fui considerado inocente aos olhos de Deus. Também não fiz coisa alguma contra o senhor, ó rei".

[[v27-6-23]]

^<<v27-6-23,23>>^ O rei ficou muito alegre e ordenou que tirassem Daniel da cova. Não havia sequer um arranhão nele, pois havia confiado em seu Deus.

[[v27-6-24]]

^<<v27-6-24,24>>^ Em seguida, o rei ordenou que prendessem os homens que haviam acusado Daniel. Ordenou que fossem lançados na cova dos leões junto com suas esposas e seus filhos. Os leões os atacaram e os despedaçaram antes que chegassem ao fundo da cova.

[[v27-6-25]]

^<<v27-6-25,25>>^ Então o rei Dario enviou esta mensagem a povos de todas as raças, nações e línguas em todo o mundo: "Paz e prosperidade!

[[v27-6-26]]

^<<v27-6-26,26>>^ "Decreto que todos em meu reino devem tremer de medo diante do Deus de Daniel. Pois ele é o Deus vivo e permanecerá para sempre. Seu reino jamais será destruído, e seu domínio não terá fim.

[[v27-6-27]]

^<<v27-6-27,27>>^ Ele livra e salva seu povo; realiza sinais e maravilhas nos céus e na terra. Foi ele que livrou Daniel do poder dos leões".

[[v27-6-28]]

^<<v27-6-28,28>>^ Assim, Daniel prosperou durante o reinado de Dario e durante o reinado de Ciro, o persa.

'''

xref:027-daniel/027-daniel-005.adoc#v27-5-0[&#60; Capítulo Anterior] | <<v27-6-0,Topo>> | xref:027-daniel/027-daniel-007.adoc#v27-7-0[Próximo Capítulo &#62;]