include::./index.adoc[]

[[v27-12-0]]
=== Daniel, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v27-12-1]]

^<<v27-12-1,1>>^ "Nessa época, Miguel, o grande príncipe que guarda seu povo, se levantará. Haverá um tempo de angústia como nunca houve desde que as nações vieram a existir. Nesse tempo, porém, todos de seu povo que tiverem o nome escrito no livro serão salvos.

[[v27-12-2]]

^<<v27-12-2,2>>^ Muitos dos que estão mortos e enterrados ressuscitarão, alguns para a vida eterna e outros para a vergonha e a desonra eterna.

[[v27-12-3]]

^<<v27-12-3,3>>^ Os sábios brilharão intensamente como o esplendor do céu, e os que conduzem muitos à justiça resplandecerão como estrelas, para sempre.

[[v27-12-4]]

^<<v27-12-4,4>>^ Mas você, Daniel, mantenha esta profecia em segredo; sele o livro até o tempo do fim, quando muitos correrão de um lado para o outro e o conhecimento aumentará".

[[v27-12-5]]

^<<v27-12-5,5>>^ Então eu, Daniel, olhei e vi dois outros em pé em margens opostas do rio.

[[v27-12-6]]

^<<v27-12-6,6>>^ Um deles perguntou ao homem vestido de linho, que agora estava sobre o rio: "Quanto tempo passará até que terminem esses acontecimentos espantosos?".

[[v27-12-7]]

^<<v27-12-7,7>>^ O homem vestido de linho, que estava sobre o rio, levantou as duas mãos em direção ao céu, pronunciou um juramento solene àquele que vive para sempre e disse: "Passará um tempo, tempos e meio tempo. Quando o povo santo finalmente for quebrado, todas essas coisas se cumprirão".

[[v27-12-8]]

^<<v27-12-8,8>>^ Ouvi o que ele disse, mas não entendi o significado. Por isso, perguntei: "Meu senhor, como estas coisas terminarão?".

[[v27-12-9]]

^<<v27-12-9,9>>^ Ele respondeu: "Agora vá, Daniel, pois aquilo que eu disse será mantido em segredo e selado até o tempo do fim.

[[v27-12-10]]

^<<v27-12-10,10>>^ Muitos serão purificados, limpos e refinados por essas provações. Os perversos, porém, continuarão em sua perversidade, e nenhum deles entenderá. Somente os sábios compreenderão seu significado.

[[v27-12-11]]

^<<v27-12-11,11>>^ "A partir do momento em que o sacrifício diário for suspenso e a terrível profanação for colocada ali, haverá 1.290 dias.

[[v27-12-12]]

^<<v27-12-12,12>>^ Feliz aquele que esperar e permanecer até o fim dos 1.335 dias!

[[v27-12-13]]

^<<v27-12-13,13>>^ "Quanto a você, siga seu caminho até o fim. Você descansará e, no final dos dias, se levantará para receber sua herança".

'''

xref:027-daniel/027-daniel-011.adoc#v27-11-0[&#60; Capítulo Anterior] | <<v27-12-0,Topo>> | xref:028-oseias/028-oseias-001.adoc#v28-1-0[Próximo Capítulo &#62;]