include::./index.adoc[]

[[v27-5-0]]
=== Daniel, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v27-5-1]]

^<<v27-5-1,1>>^ Muitos anos depois, o rei Belsazar deu um grande banquete para mil de seus nobres e bebeu vinho com eles.

[[v27-5-2]]

^<<v27-5-2,2>>^ Enquanto Belsazar tomava vinho, ordenou que trouxessem as taças de ouro e prata que seu antecessor, Nabucodonosor, havia tirado do templo em Jerusalém. Queria beber nessas taças com seus nobres, suas esposas e suas concubinas.

[[v27-5-3]]

^<<v27-5-3,3>>^ Então trouxeram as taças de ouro do templo, a casa de Deus em Jerusalém, e o rei e seus nobres, suas esposas e concubinas beberam nelas.

[[v27-5-4]]

^<<v27-5-4,4>>^ Enquanto tomavam o vinho, louvavam seus ídolos feitos de ouro, prata, bronze, ferro, madeira e pedra.

[[v27-5-5]]

^<<v27-5-5,5>>^ De repente, viram dedos de mão humana escreverem no reboco da parede do palácio real, perto do candelabro. O próprio rei viu a mão enquanto ela escrevia,

[[v27-5-6]]

^<<v27-5-6,6>>^ e seu rosto ficou pálido de medo. Seus joelhos batiam um contra o outro, e suas pernas vacilavam.

[[v27-5-7]]

^<<v27-5-7,7>>^ Aos gritos, o rei mandou chamar os encantadores, os astrólogos e os adivinhos. Disse aos sábios da Babilônia: "Quem conseguir ler esta inscrição e me disser o que ela significa será vestido com um manto vermelho, e em seu pescoço será colocada uma corrente de ouro. Ele se tornará o terceiro em importância em meu reino!".

[[v27-5-8]]

^<<v27-5-8,8>>^ Quando todos os sábios do rei chegaram, nenhum deles foi capaz de ler a inscrição nem de dizer o que ela significava.

[[v27-5-9]]

^<<v27-5-9,9>>^ O rei ficou muito assustado, e seu rosto, ainda mais pálido. Seus nobres também ficaram abalados.

[[v27-5-10]]

^<<v27-5-10,10>>^ A rainha-mãe soube do que estava acontecendo ao rei e seus nobres e foi depressa à sala de banquetes. Disse ela a Belsazar: "Que o rei viva para sempre! Não fique tão pálido e assustado.

[[v27-5-11]]

^<<v27-5-11,11>>^ Há em seu reino um homem que tem nele o espírito dos santos deuses. Durante o reinado de Nabucodonosor, esse homem demonstrou percepção, entendimento e sabedoria como a dos deuses. Seu antecessor, o rei Nabucodonosor, o nomeou chefe de todos os magos, encantadores, astrólogos e adivinhos da Babilônia.

[[v27-5-12]]

^<<v27-5-12,12>>^ Esse homem, Daniel, a quem o rei deu o nome de Beltessazar, tem inteligência extraordinária e é cheio de conhecimento e entendimento. É capaz de interpretar sonhos, explicar enigmas e resolver problemas difíceis. Mande chamar Daniel, e ele lhe dirá o que significa a inscrição".

[[v27-5-13]]

^<<v27-5-13,13>>^ Daniel foi levado à presença do rei, que lhe perguntou: "Você é Daniel, um dos exilados trazidos de Judá por meu antecessor, o rei Nabucodonosor?

[[v27-5-14]]

^<<v27-5-14,14>>^ Soube que o espírito dos deuses está em você, e que é cheio de percepção, entendimento e sabedoria.

[[v27-5-15]]

^<<v27-5-15,15>>^ Meus sábios e encantadores tentaram ler as palavras na parede e me dizer o que significam, mas não conseguiram.

[[v27-5-16]]

^<<v27-5-16,16>>^ Soube que você é capaz de interpretar e resolver problemas difíceis. Se conseguir ler as palavras e disser o que significam, será vestido com um manto vermelho, e em seu pescoço será colocada uma corrente de ouro. Você se tornará o terceiro em importância em meu reino".

[[v27-5-17]]

^<<v27-5-17,17>>^ Daniel respondeu ao rei: "Guarde seus presentes ou entregue-os a outra pessoa; mas eu lhe direi o que significa a inscrição.

[[v27-5-18]]

^<<v27-5-18,18>>^ Ó rei, o Deus Altíssimo deu soberania, majestade, glória e honra a seu antecessor, Nabucodonosor.

[[v27-5-19]]

^<<v27-5-19,19>>^ Ele o engrandeceu de tal modo que povos de todas as raças, nações e línguas estremeciam de medo diante dele. Matava quem ele queria matar e poupava quem ele queria poupar; honrava quem ele queria honrar e humilhava quem ele queria humilhar.

[[v27-5-20]]

^<<v27-5-20,20>>^ Quando, porém, seu coração e sua mente se encheram de arrogância, ele foi tirado de seu trono e despojado de sua glória.

[[v27-5-21]]

^<<v27-5-21,21>>^ Foi expulso do convívio humano. Sua mente se tornou como a de um animal, e ele viveu entre os jumentos selvagens. Passou a comer capim, como os bois, e foi molhado pelo orvalho do céu, até entender que o Deus Altíssimo domina sobre todos os reinos do mundo e nomeia quem ele quer para governar sobre eles.

[[v27-5-22]]

^<<v27-5-22,22>>^ "Ó Belsazar, o senhor é sucessor dele e sabia de tudo isso, mas mesmo assim não se humilhou.

[[v27-5-23]]

^<<v27-5-23,23>>^ Desafiou o Senhor dos céus e mandou trazer essas taças do templo. O rei, seus nobres, suas esposas e suas concubinas beberam vinho dessas taças enquanto louvavam deuses de prata, ouro, bronze, ferro, madeira e pedra, deuses que não veem, não ouvem, nem sabem coisa alguma. Mas o rei não honrou ao Deus que lhe dá fôlego de vida e controla seu destino.

[[v27-5-24]]

^<<v27-5-24,24>>^ Por isso Deus enviou a mão que escreveu a mensagem.

[[v27-5-25]]

^<<v27-5-25,25>>^ "Esta é a mensagem que foi escrita: Mene, Mene, Tequel e Parsim.

[[v27-5-26]]

^<<v27-5-26,26>>^ E este é o significado das palavras: Mene : Deus contou os dias de seu reinado e determinou seu fim.

[[v27-5-27]]

^<<v27-5-27,27>>^ Tequel : Você foi pesado na balança e não atingiu o peso necessário.

[[v27-5-28]]

^<<v27-5-28,28>>^ Parsim : Seu reino será dividido e entregue aos medos e aos persas".

[[v27-5-29]]

^<<v27-5-29,29>>^ Então, por ordem de Belsazar, vestiram Daniel com um manto vermelho, colocaram em seu pescoço uma corrente de ouro e o declararam o terceiro em importância no reino.

[[v27-5-30]]

^<<v27-5-30,30>>^ Naquela mesma noite, Belsazar, rei da Babilônia, foi morto.

[[v27-5-31]]

^<<v27-5-31,31>>^ E Dario, o medo, tinha 62 anos quando se apoderou do reino.

'''

xref:027-daniel/027-daniel-004.adoc#v27-4-0[&#60; Capítulo Anterior] | <<v27-5-0,Topo>> | xref:027-daniel/027-daniel-006.adoc#v27-6-0[Próximo Capítulo &#62;]