include::./index.adoc[]

[[v27-11-0]]
=== Daniel, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v27-11-1]]

^<<v27-11-1,1>>^ Tenho acompanhado Miguel para apoiá-lo e fortalecê-lo desde o primeiro ano do reinado de Dario, o medo.)

[[v27-11-2]]

^<<v27-11-2,2>>^ "Agora, portanto, eu lhe revelarei a verdade. Outros três reis persas reinarão e serão sucedidos pelo quarto rei, muito mais rico que os outros. Ele usará sua riqueza para instigar todos a lutarem contra o reino da Grécia.

[[v27-11-3]]

^<<v27-11-3,3>>^ "Então surgirá um rei poderoso, que governará com grande autoridade e realizará tudo que desejar fazer.

[[v27-11-4]]

^<<v27-11-4,4>>^ Mas, no auge de seu poder, seu reino será quebrado e dividido em quatro partes. Não será governado pelos descendentes do rei e o reino não terá a mesma autoridade de antes, pois seu império será arrancado fora e entregue a outros.

[[v27-11-5]]

^<<v27-11-5,5>>^ "O rei do sul se tornará poderoso, mas um de seus oficiais se tornará ainda mais poderoso e governará seu reino com grande força.

[[v27-11-6]]

^<<v27-11-6,6>>^ "Alguns anos depois, será formada uma aliança entre o rei do norte e o rei do sul. A filha do rei do sul se casará com o rei do norte para garantir a aliança, mas tanto ela como seu pai perderão a influência sobre ele. Ela será abandonada, junto com aqueles que a apoiam.

[[v27-11-7]]

^<<v27-11-7,7>>^ Mas, quando um de seus parentes se tornar o rei do sul, ele reunirá um exército, entrará na fortaleza do rei do norte e o derrotará.

[[v27-11-8]]

^<<v27-11-8,8>>^ Quando ele voltar ao Egito, levará os ídolos deles, e também objetos valiosos de ouro e prata. Por alguns anos, deixará o rei do norte em paz.

[[v27-11-9]]

^<<v27-11-9,9>>^ "Mais tarde, o rei do norte invadirá o reino do sul, mas logo voltará para sua terra.

[[v27-11-10]]

^<<v27-11-10,10>>^ Os filhos do rei do norte, porém, reunirão um exército poderoso que avançará como uma inundação e levará a batalha até a fortaleza do inimigo.

[[v27-11-11]]

^<<v27-11-11,11>>^ "Enfurecido, o rei do sul sairá para lutar contra o grande exército reunido pelo rei do norte e o derrotará.

[[v27-11-12]]

^<<v27-11-12,12>>^ Depois que o exército inimigo for vencido, o rei do sul se tornará orgulhoso e executará muitos milhares de inimigos; sua vitória, porém, não durará muito tempo.

[[v27-11-13]]

^<<v27-11-13,13>>^ "Alguns anos depois, o rei do norte voltará com um exército bem equipado, muito maior que antes.

[[v27-11-14]]

^<<v27-11-14,14>>^ Nessa ocasião, haverá uma rebelião geral contra o rei do sul. Homens violentos de seu povo, Daniel, se juntarão a eles em cumprimento desta visão, mas serão derrotados.

[[v27-11-15]]

^<<v27-11-15,15>>^ Então o rei do norte virá e cercará uma cidade fortificada e a conquistará. Nem as melhores tropas do sul conseguirão resistir a esse ataque.

[[v27-11-16]]

^<<v27-11-16,16>>^ "O rei do norte continuará a avançar sem oposição; ninguém será capaz de resistir-lhe. Ele se deterá na terra gloriosa, decidido a destruí-la.

[[v27-11-17]]

^<<v27-11-17,17>>^ Fará planos de vir com a força de todo o seu reino e formará uma aliança com o rei do sul. Dará sua filha em casamento a fim de derrubar o reino, mas seu plano falhará.

[[v27-11-18]]

^<<v27-11-18,18>>^ "Depois disso, voltará sua atenção para o litoral e conquistará muitas cidades. No entanto, um comandante de outra terra acabará com sua insolência e o fará retirar-se, envergonhado.

[[v27-11-19]]

^<<v27-11-19,19>>^ Ele se refugiará em sua própria fortaleza, mas tropeçará e nunca mais será visto.

[[v27-11-20]]

^<<v27-11-20,20>>^ "Seu sucessor enviará um cobrador de impostos para manter o esplendor real. Depois de um breve reinado, porém, ele morrerá, mas não como resultado de ira nem na batalha.

[[v27-11-21]]

^<<v27-11-21,21>>^ "O próximo a subir ao poder será um homem desprezível, que não faz parte da linhagem real. Ele se infiltrará quando menos se espera e assumirá o controle do reino por meio de intrigas.

[[v27-11-22]]

^<<v27-11-22,22>>^ Diante dele, grandes exércitos serão arrasados, incluindo um príncipe da aliança.

[[v27-11-23]]

^<<v27-11-23,23>>^ Com promessas enganosas, fará várias alianças. Apesar de ter apenas um punhado de seguidores, ele se tornará forte.

[[v27-11-24]]

^<<v27-11-24,24>>^ Sem aviso, entrará nas regiões mais ricas da terra e distribuirá entre seus seguidores o despojo e os bens dos ricos, coisa que seus antecessores nunca fizeram. Fará planos para conquistar fortalezas, mas isso durará pouco tempo.

[[v27-11-25]]

^<<v27-11-25,25>>^ "Então juntará coragem e reunirá um grande exército contra o rei do sul. Este sairá para a batalha, mas de nada adiantará, pois haverá conspirações contra ele.

[[v27-11-26]]

^<<v27-11-26,26>>^ Sua derrota será causada por gente de sua própria confiança. Seu exército será arrasado, e muitos serão mortos.

[[v27-11-27]]

^<<v27-11-27,27>>^ Decididos a fazer o mal, esses reis tentarão enganar um ao outro enquanto estiverem à mesa de negociações; mas isso não fará diferença alguma, pois o fim chegará no tempo determinado.

[[v27-11-28]]

^<<v27-11-28,28>>^ "O rei do norte voltará para casa com muitas riquezas. No caminho, ele se colocará contra o povo da santa aliança e fará grandes estragos antes de seguir viagem.

[[v27-11-29]]

^<<v27-11-29,29>>^ "Então, no tempo determinado, ele voltará a invadir o sul, mas dessa vez o resultado será diferente.

[[v27-11-30]]

^<<v27-11-30,30>>^ Ele se assustará com os navios de guerra do litoral oeste e voltará para casa. Então descarregará sua ira sobre o povo da santa aliança e recompensará os que abandonarem a aliança.

[[v27-11-31]]

^<<v27-11-31,31>>^ "Seu exército tomará a fortaleza do templo, contaminará o santuário, acabará com os sacrifícios diários e colocará ali uma terrível profanação.

[[v27-11-32]]

^<<v27-11-32,32>>^ Ele usará de adulação e conquistará os que violaram a aliança; mas aqueles que conhecem seu Deus serão fortes e resistirão.

[[v27-11-33]]

^<<v27-11-33,33>>^ "Líderes sábios instruirão a muitos, mas esses mestres morrerão pela espada e pelo fogo, ou serão capturados e saqueados.

[[v27-11-34]]

^<<v27-11-34,34>>^ Durante essas perseguições, receberão pouca ajuda, e muitos que se juntarem a eles não serão sinceros.

[[v27-11-35]]

^<<v27-11-35,35>>^ Alguns dos sábios serão vítimas de perseguição e, desse modo, serão refinados, purificados e limpos até o tempo do fim, pois o tempo determinado ainda está por vir.

[[v27-11-36]]

^<<v27-11-36,36>>^ "O rei fará o que bem entender, se exaltará, afirmará ser maior que todos os deuses e chegará a blasfemar contra o Deus dos deuses. Terá êxito, mas apenas até que se complete o tempo da ira; pois aquilo que foi determinado certamente acontecerá.

[[v27-11-37]]

^<<v27-11-37,37>>^ Ele não respeitará os deuses de seus antepassados, nem o deus preferido das mulheres, nem deus algum, pois dirá que é maior que todos eles.

[[v27-11-38]]

^<<v27-11-38,38>>^ Em lugar deles, adorará o deus da fortaleza, um deus que seus antepassados não conheceram, e lhe dará honras com ouro, prata, pedras preciosas e presentes caros.

[[v27-11-39]]

^<<v27-11-39,39>>^ Dizendo contar com a ajuda desse deus estrangeiro, atacará as fortalezas mais poderosas. Honrará os que se sujeitarem a ele, os nomeará para cargos de autoridade e dividirá a terra entre eles como recompensa.

[[v27-11-40]]

^<<v27-11-40,40>>^ "Então, no tempo do fim, o rei do sul lutará contra o rei do norte. O rei do norte atacará com carros de guerra e seus condutores e com muitos navios. Invadirá várias terras e as arrasará como uma inundação.

[[v27-11-41]]

^<<v27-11-41,41>>^ Entrará na terra gloriosa e muitas nações cairão, mas Moabe, Edom e a maior parte de Amom escaparão.

[[v27-11-42]]

^<<v27-11-42,42>>^ Ele conquistará muitos países, e nem mesmo o Egito escapará.

[[v27-11-43]]

^<<v27-11-43,43>>^ Tomará para si o ouro, a prata e os tesouros do Egito, e os líbios e os etíopes serão seus servos.

[[v27-11-44]]

^<<v27-11-44,44>>^ "Mas, então, chegarão notícias do leste e do norte que o deixarão alarmado, e ele partirá enfurecido para destruir e aniquilar muitos.

[[v27-11-45]]

^<<v27-11-45,45>>^ Armará suas tendas entre o monte santo e glorioso e o mar. Enquanto estiver lá, porém, chegará a seu fim, e ninguém o ajudará."

'''

xref:027-daniel/027-daniel-010.adoc#v27-10-0[&#60; Capítulo Anterior] | <<v27-11-0,Topo>> | xref:027-daniel/027-daniel-012.adoc#v27-12-0[Próximo Capítulo &#62;]