include::./index.adoc[]

[[v27-10-0]]
=== Daniel, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v27-10-1]]

^<<v27-10-1,1>>^ No terceiro ano do reinado de Ciro, rei da Pérsia, Daniel (também chamado Beltessazar) teve outra visão. Ele entendeu que essa visão era verdadeira e se referia a certos acontecimentos que ocorreriam no futuro, tempos de guerra e de grande dificuldade.

[[v27-10-2]]

^<<v27-10-2,2>>^ Eu, Daniel, recebi essa visão depois de passar três semanas de luto.

[[v27-10-3]]

^<<v27-10-3,3>>^ Durante todo esse tempo, não havia comido nada saboroso. Não tinha provado nenhuma carne e nenhum vinho e não tinha usado nenhuma loção perfumada até passarem as três semanas.

[[v27-10-4]]

^<<v27-10-4,4>>^ Em 23 de abril daquele ano, estava em pé próximo ao grande rio Tigre.

[[v27-10-5]]

^<<v27-10-5,5>>^ Levantei os olhos e vi um homem vestido com roupas de linho e um cinto de ouro puro.

[[v27-10-6]]

^<<v27-10-6,6>>^ Seu corpo era semelhante a uma pedra preciosa. Seu rosto faiscava como relâmpago, e seus olhos eram como tochas acesas. Seus braços e seus pés brilhavam como bronze polido, e sua voz era como o som de uma grande multidão.

[[v27-10-7]]

^<<v27-10-7,7>>^ Somente eu, Daniel, tive essa visão. Os homens que estavam comigo não viram coisa alguma. De repente, porém, eles se encheram de terror e correram para se esconder.

[[v27-10-8]]

^<<v27-10-8,8>>^ Assim, fiquei ali sozinho e tive essa visão extraordinária. Perdi as forças, fiquei muito pálido e quase desfaleci.

[[v27-10-9]]

^<<v27-10-9,9>>^ Então ouvi o homem falar e, ao som de sua voz, perdi os sentidos e fiquei ali estendido, com o rosto no chão.

[[v27-10-10]]

^<<v27-10-10,10>>^ Nesse instante, a mão de alguém me tocou e me pôs, ainda trêmulo, sobre minhas mãos e meus joelhos.

[[v27-10-11]]

^<<v27-10-11,11>>^ E o homem me disse: "Daniel, você é muito precioso para Deus; por isso, ouça com atenção o que tenho a lhe dizer. Levante-se, pois fui enviado a você". Quando ele me disse isso, me levantei, ainda tremendo.

[[v27-10-12]]

^<<v27-10-12,12>>^ Em seguida, ele disse: "Não tenha medo, Daniel. Pois, desde o primeiro dia em que você começou a orar por entendimento e a se humilhar diante de seu Deus, seu pedido foi ouvido. Eu vim em resposta à sua oração.

[[v27-10-13]]

^<<v27-10-13,13>>^ Por 21 dias, porém, o príncipe do reino da Pérsia me impediu. Então Miguel, um dos príncipes mais importantes, veio me ajudar, e eu o deixei ali com os reis da Pérsia.

[[v27-10-14]]

^<<v27-10-14,14>>^ Agora estou aqui para explicar o que acontecerá com seu povo no futuro, pois essa visão se refere a um tempo que ainda está por vir".

[[v27-10-15]]

^<<v27-10-15,15>>^ Enquanto ele falava comigo, eu olhava para o chão, sem conseguir dizer uma única palavra.

[[v27-10-16]]

^<<v27-10-16,16>>^ Então aquele que se parecia com um homem tocou meus lábios, e eu abri a boca e comecei a falar. Disse àquele que estava diante de mim: "Meu senhor, estou angustiado por causa da visão que tive, e me sinto muito fraco.

[[v27-10-17]]

^<<v27-10-17,17>>^ Como é possível alguém como eu, seu servo, falar com meu senhor? Minhas forças se foram, e mal consigo respirar".

[[v27-10-18]]

^<<v27-10-18,18>>^ Então aquele que se parecia com um homem tocou em mim novamente, e senti minhas forças voltarem.

[[v27-10-19]]

^<<v27-10-19,19>>^ "Não tenha medo", ele disse, "pois você é muito precioso para Deus. Que a paz esteja com você! Tenha ânimo! Seja forte!" Enquanto ele falava, logo me senti mais forte e disse: "Fale, meu senhor, pois me fortaleceu".

[[v27-10-20]]

^<<v27-10-20,20>>^ Então ele disse: "Você sabe por que eu vim? Em breve terei de voltar para lutar com o príncipe do reino da Pérsia e, depois disso, virá o príncipe do reino da Grécia.

[[v27-10-21]]

^<<v27-10-21,21>>^ Mas agora lhe direi o que está escrito no Livro da Verdade. (Ninguém me ajuda na luta contra esses príncipes, exceto Miguel, o príncipe de vocês.

'''

xref:027-daniel/027-daniel-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-daniel/027-daniel-011.adoc#v27-11-0[Próximo Capítulo &#62;]