include::./index.adoc[]

[[v27-4-0]]
=== Daniel, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v27-4-1]]

^<<v27-4-1,1>>^ O rei Nabucodonosor enviou esta mensagem a povos de todas as raças, nações e línguas em todo o mundo: "Paz e prosperidade!

[[v27-4-2]]

^<<v27-4-2,2>>^ Quero que todos saibam dos sinais e das maravilhas que o Deus Altíssimo realizou em meu favor.

[[v27-4-3]]

^<<v27-4-3,3>>^ Como são grandes seus sinais, como são poderosas suas maravilhas! Seu reino durará para sempre, e seu domínio, por todas as gerações.

[[v27-4-4]]

^<<v27-4-4,4>>^ "Eu, Nabucodonosor, vivia em meu palácio, com todo conforto e prosperidade.

[[v27-4-5]]

^<<v27-4-5,5>>^ Certa noite, porém, tive um sonho que me assustou; enquanto estava deitado em minha cama, tive visões que me aterrorizaram.

[[v27-4-6]]

^<<v27-4-6,6>>^ Por isso mandei chamar todos os sábios da Babilônia, para que me dissessem o que meu sonho significava.

[[v27-4-7]]

^<<v27-4-7,7>>^ Quando todos os magos, encantadores, astrólogos e adivinhos vieram, eu lhes contei meu sonho, mas eles não foram capazes de me dizer o que ele significava.

[[v27-4-8]]

^<<v27-4-8,8>>^ Finalmente, Daniel se apresentou diante de mim, e eu lhe contei o sonho. (Ele se chama Beltessazar, em homenagem a meu deus, e o espírito dos santos deuses está nele.)

[[v27-4-9]]

^<<v27-4-9,9>>^ "Disse-lhe: ‘Beltessazar, chefe dos magos, sei que o espírito dos santos deuses está em você e que não há mistério que não possa resolver. Agora, diga-me o que meu sonho significa.

[[v27-4-10]]

^<<v27-4-10,10>>^ "‘Enquanto estava deitado em minha cama, tive este sonho. Vi uma grande árvore no meio da terra.

[[v27-4-11]]

^<<v27-4-11,11>>^ A árvore cresceu e ficou muito alta e forte; chegava até o céu e podia ser vista por todo o mundo.

[[v27-4-12]]

^<<v27-4-12,12>>^ Suas folhas eram verdes e novas, e ela era cheia de frutos para todos comerem. Animais selvagens viviam à sua sombra, e aves faziam ninhos em seus ramos. O mundo todo se alimentava dessa árvore.

[[v27-4-13]]

^<<v27-4-13,13>>^ "‘Então, enquanto eu sonhava, vi um mensageiro, um ser santo, que descia do céu.

[[v27-4-14]]

^<<v27-4-14,14>>^ O mensageiro gritou: ‘Derrubem a árvore e cortem seus ramos! Arranquem suas folhas e espalhem seus frutos! Espantem os animais selvagens de sua sombra e as aves, de seus ramos.

[[v27-4-15]]

^<<v27-4-15,15>>^ Mas deixem na terra o toco, com suas raízes, preso com um anel de ferro e bronze e cercado da relva verde. Que seja molhado pelo orvalho do céu e viva com os animais selvagens, em meio às plantas do campo.

[[v27-4-16]]

^<<v27-4-16,16>>^ Durante sete períodos, terá a mente de um animal selvagem em vez de mente humana.

[[v27-4-17]]

^<<v27-4-17,17>>^ Pois isso foi decretado pelos mensageiros; foi ordenado pelos seres santos, para que todos saibam que o Altíssimo domina sobre os reinos do mundo. Ele os dá a quem quer, até mesmo à pessoa mais humilde".

[[v27-4-18]]

^<<v27-4-18,18>>^ "‘Beltessazar, esse foi o sonho que eu, o rei Nabucodonosor, tive. Agora, diga-me o que ele significa, pois nenhum dos sábios de meu reino foi capaz de interpretá-lo. Mas você pode fazê-lo, pois o espírito dos santos deuses está em você’."

[[v27-4-19]]

^<<v27-4-19,19>>^ "Ao ouvir isso, Daniel (também chamado Beltessazar), ficou atônito por algum tempo, atemorizado com o significado do sonho. Então o rei lhe disse: ‘Beltessazar, não se assuste com o sonho, nem com o seu significado’. "Beltessazar respondeu: ‘Meu senhor, gostaria que os acontecimentos prenunciados nesse sonho ocorressem a seus inimigos, e não ao rei!

[[v27-4-20]]

^<<v27-4-20,20>>^ A árvore que o rei viu crescia e ficava alta e forte; chegava até o céu e podia ser vista por todo o mundo.

[[v27-4-21]]

^<<v27-4-21,21>>^ Tinha folhas verdes e novas e era cheia de frutos para todos comerem. Animais selvagens viviam à sua sombra, e aves faziam ninhos em seus ramos.

[[v27-4-22]]

^<<v27-4-22,22>>^ Essa árvore é o próprio rei. Pois o rei cresceu e se tornou forte e grande; sua grandeza chega até o céu, e seu domínio, até os confins da terra.

[[v27-4-23]]

^<<v27-4-23,23>>^ "‘Então o rei viu um mensageiro, um ser santo que descia do céu e que disse: ‘Derrubem a árvore e destruam-na! Mas deixem na terra o toco, com suas raízes, preso com um anel de ferro e bronze e cercado da relva verde. Que seja molhado pelo orvalho do céu e viva com os animais do campo por sete períodos’.

[[v27-4-24]]

^<<v27-4-24,24>>^ "‘Este é o significado do sonho, ó rei, o que o Altíssimo declarou que acontecerá a meu senhor, o rei.

[[v27-4-25]]

^<<v27-4-25,25>>^ O rei será expulso do convívio humano e viverá nos campos, com os animais selvagens. Comerá capim, como os bois, e será molhado pelo orvalho do céu. Viverá desse modo por sete períodos, até entender que o Altíssimo domina sobre os reinos do mundo e os dá a quem ele quer.

[[v27-4-26]]

^<<v27-4-26,26>>^ As raízes e o toco, porém, foram deixados na terra. Isso significa que o senhor receberá seu reino de volta quando tiver aprendido que o céu domina.

[[v27-4-27]]

^<<v27-4-27,27>>^ "‘Ó rei Nabucodonosor, aceite meu conselho. Pare de pecar e faça o que é certo. Deixe seus pecados para trás e tenha compaixão dos pobres. Quem sabe, então, o rei continuará a prosperar’."

[[v27-4-28]]

^<<v27-4-28,28>>^ "Tudo isso, porém, aconteceu ao rei Nabucodonosor.

[[v27-4-29]]

^<<v27-4-29,29>>^ Doze meses depois, ele caminhava sobre o terraço de seu palácio na Babilônia

[[v27-4-30]]

^<<v27-4-30,30>>^ e disse: ‘Vejam a grande cidade da Babilônia! Com meu próprio poder, construí esta cidade para ser o centro de meu reino e para mostrar o esplendor de minha majestade’.

[[v27-4-31]]

^<<v27-4-31,31>>^ "Enquanto essas palavras ainda estavam em sua boca, veio do céu uma voz e disse: ‘Esta mensagem é para você, rei Nabucodonosor! Você não governa mais sobre este reino.

[[v27-4-32]]

^<<v27-4-32,32>>^ Será expulso do convívio humano. Viverá nos campos com os animais selvagens e comerá capim, como os bois. Viverá desse modo por sete períodos, até que entenda que o Altíssimo domina sobre os reinos do mundo e os dá a quem ele quer’.

[[v27-4-33]]

^<<v27-4-33,33>>^ "Naquela mesma hora, a sentença se cumpriu e Nabucodonosor foi expulso do convívio humano. Passou a comer capim, como os bois, e foi molhado pelo orvalho do céu. Viveu desse modo até seu cabelo crescer como as penas das águias e suas unhas se parecerem com garras de pássaros."

[[v27-4-34]]

^<<v27-4-34,34>>^ "Passado esse tempo, eu, Nabucodonosor, olhei para o céu. Minha sanidade voltou, louvei e adorei o Altíssimo e honrei aquele que vive para sempre. "Seu domínio é para sempre, seu reino, por todas as gerações.

[[v27-4-35]]

^<<v27-4-35,35>>^ Comparados a ele, os habitantes da terra são como nada. Ele faz o que quer entre os anjos do céu e entre os habitantes da terra. Ninguém pode detê-lo nem lhe dizer: ‘Por que fazes essas coisas?’.

[[v27-4-36]]

^<<v27-4-36,36>>^ "Quando minha sanidade voltou, também recuperei minha honra e a majestade de meu reino. Meus conselheiros e nobres me procuraram e fui restaurado ao meu reino, com muito mais honra que antes.

[[v27-4-37]]

^<<v27-4-37,37>>^ "Agora eu, Nabucodonosor, louvo, glorifico e honro o Rei dos céus. Todos os seus atos são justos e verdadeiros, e ele tem poder para humilhar os orgulhosos".

'''

xref:027-daniel/027-daniel-003.adoc#v27-3-0[&#60; Capítulo Anterior] | <<v27-4-0,Topo>> | xref:027-daniel/027-daniel-005.adoc#v27-5-0[Próximo Capítulo &#62;]