include::./index.adoc[]

[[v13-15-0]]
=== 1 Crônicas, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v13-15-1]]

^<<v13-15-1,1>>^ Davi construiu várias casas para si na Cidade de Davi. Também preparou um lugar para a arca de Deus e armou uma tenda especial para ela.

[[v13-15-2]]

^<<v13-15-2,2>>^ Em seguida, ordenou: "Ninguém, a não ser os levitas, levará a arca de Deus. O SENHOR os escolheu para carregarem a arca de Deus e o servirem para sempre".

[[v13-15-3]]

^<<v13-15-3,3>>^ Então Davi convocou todo o Israel para ir a Jerusalém a fim de trazer a arca do SENHOR para o lugar que ele havia preparado.

[[v13-15-4]]

^<<v13-15-4,4>>^ Este é o número de descendentes de Arão e de levitas convocados:

[[v13-15-5]]

^<<v13-15-5,5>>^ Do clã de Coate, 120, e seu chefe era Uriel.

[[v13-15-6]]

^<<v13-15-6,6>>^ Do clã de Merari, 220, e seu chefe era Asaías.

[[v13-15-7]]

^<<v13-15-7,7>>^ Do clã de Gérson, 130, e seu chefe era Joel.

[[v13-15-8]]

^<<v13-15-8,8>>^ Dos descendentes de Elisafã, 200, e seu chefe era Semaías.

[[v13-15-9]]

^<<v13-15-9,9>>^ Dos descendentes de Hebrom, 80, e seu chefe era Eliel.

[[v13-15-10]]

^<<v13-15-10,10>>^ Dos descendentes de Uziel, 112, e seu chefe era Aminadabe.

[[v13-15-11]]

^<<v13-15-11,11>>^ Em seguida, Davi convocou os sacerdotes Zadoque e Abiatar, e os chefes dos levitas Uriel, Asaías, Joel, Semaías, Eliel e Aminadabe.

[[v13-15-12]]

^<<v13-15-12,12>>^ Disse-lhes: "Vocês são os chefes das famílias levitas. Consagrem-se, vocês e todos os seus parentes levitas, para trazerem a arca do SENHOR, o Deus de Israel, para o lugar que preparei para ela.

[[v13-15-13]]

^<<v13-15-13,13>>^ A ira do SENHOR irrompeu contra nós da primeira vez, pois não foram vocês, os levitas, que levaram a arca. Não consultamos a Deus sobre o modo apropriado de transportá-la".

[[v13-15-14]]

^<<v13-15-14,14>>^ Então os sacerdotes e os levitas se consagraram a fim de trazer para Jerusalém a arca do SENHOR, Deus de Israel.

[[v13-15-15]]

^<<v13-15-15,15>>^ Os levitas carregaram a arca de Deus sobre os ombros, usando as varas presas a ela, conforme o SENHOR havia instruído por meio de Moisés.

[[v13-15-16]]

^<<v13-15-16,16>>^ Davi também ordenou aos chefes dos levitas que nomeassem cantores e músicos para entoarem cânticos alegres acompanhados por harpas, liras e címbalos.

[[v13-15-17]]

^<<v13-15-17,17>>^ Os levitas escolheram Hemã, filho de Joel, e seus parentes levitas: Asafe, filho de Berequias, e Etã, filho de Cuxaías, do clã de Merari.

[[v13-15-18]]

^<<v13-15-18,18>>^ Foram escolhidos como seus ajudantes os seguintes homens: Zacarias, Jaaziel, Semiramote, Jeiel, Uni, Eliabe, Benaia, Maaseias, Matitias, Elifeleu, Micneias e os guardas das portas: Obede-Edom e Jeiel.

[[v13-15-19]]

^<<v13-15-19,19>>^ Os músicos Hemã, Asafe e Etã foram escolhidos para tocar os címbalos de bronze.

[[v13-15-20]]

^<<v13-15-20,20>>^ Zacarias, Aziel, Semiramote, Jeiel, Uni, Eliabe, Maaseias e Benaia foram escolhidos para tocar as harpas, em tons agudos.

[[v13-15-21]]

^<<v13-15-21,21>>^ Matitias, Elifeleu, Micneias, Obede-Edom, Azazias e Jeiel foram escolhidos para tocar as liras, em tons de oitava.

[[v13-15-22]]

^<<v13-15-22,22>>^ Quenanias, chefe dos levitas, foi escolhido para dirigir o canto, pois tinha habilidade para isso.

[[v13-15-23]]

^<<v13-15-23,23>>^ Berequias e Elcana foram escolhidos para cuidar da arca.

[[v13-15-24]]

^<<v13-15-24,24>>^ Sebanias, Josafá, Natanael, Amasai, Zacarias, Benaia e Eliézer, todos sacerdotes, foram escolhidos para tocar as trombetas enquanto iam à frente da arca de Deus. Obede-Edom e Jeías também foram escolhidos para cuidar da arca.

[[v13-15-25]]

^<<v13-15-25,25>>^ Então Davi, as autoridades de Israel e os generais do exército foram à casa de Obede-Edom a fim de trazer a arca da aliança do SENHOR para Jerusalém com grande celebração.

[[v13-15-26]]

^<<v13-15-26,26>>^ E, como Deus estava claramente ajudando os levitas enquanto carregavam a arca da aliança do SENHOR, ofereceram como sacrifício sete novilhos e sete carneiros.

[[v13-15-27]]

^<<v13-15-27,27>>^ Davi vestia um manto de linho fino, assim como os levitas que carregavam a arca, os músicos e Quenanias, o dirigente do canto. Davi também vestia um colete sacerdotal.

[[v13-15-28]]

^<<v13-15-28,28>>^ Assim, todo o Israel trouxe a arca da aliança do SENHOR com gritos de alegria, ao som de trombetas, cornetas, címbalos, harpas e liras.

[[v13-15-29]]

^<<v13-15-29,29>>^ Enquanto a arca da aliança do SENHOR entrava na Cidade de Davi, Mical, filha de Saul, olhava pela janela. Quando viu o rei Davi saltando e rindo de alegria, encheu-se de desprezo por ele.

'''

xref:013-1-cronicas/013-1-cronicas-014.adoc#v13-14-0[&#60; Capítulo Anterior] | <<v13-15-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[Próximo Capítulo &#62;]