include::./index.adoc[]

[[v13-4-0]]
=== 1 Crônicas, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v13-4-1]]

^<<v13-4-1,1>>^ Os descendentes de Judá foram: Perez, Hezrom, Carmi, Hur e Sobal.

[[v13-4-2]]

^<<v13-4-2,2>>^ Reaías, filho de Sobal, gerou Jaate. Jaate gerou Aumai e Laade. Esses foram os clãs dos zoratitas.

[[v13-4-3]]

^<<v13-4-3,3>>^ Os descendentes de Etã foram: Jezreel, Isma e Idbás, sua irmã Hazelelponi,

[[v13-4-4]]

^<<v13-4-4,4>>^ Penuel, pai de Gedor, e Ézer, pai de Husá. Todos esses foram descendentes de Hur, o filho mais velho de Efrata, antepassado de Belém.

[[v13-4-5]]

^<<v13-4-5,5>>^ Asur, pai de Tecoa, teve duas esposas: Helá e Naará.

[[v13-4-6]]

^<<v13-4-6,6>>^ Naará deu à luz Auzã, Héfer, Temeni e Haastari.

[[v13-4-7]]

^<<v13-4-7,7>>^ Helá deu à luz Zerete, Izar, Etnã

[[v13-4-8]]

^<<v13-4-8,8>>^ e Coz, antepassado de Anube, Zobeba e todos os clãs de Aarel, filho de Harum.

[[v13-4-9]]

^<<v13-4-9,9>>^ Havia um homem chamado Jabez, mais respeitado que qualquer um de seus irmãos. Sua mãe lhe deu o nome de Jabez, porque disse: "Eu o dei à luz com muita dor".

[[v13-4-10]]

^<<v13-4-10,10>>^ Jabez orou ao Deus de Israel: "Ah, como seria bom se me abençoasses e expandisses meu território! Sê comigo em tudo que eu fizer e guarda-me de todo mal e aflição!". E Deus atendeu a seu pedido.

[[v13-4-11]]

^<<v13-4-11,11>>^ Quelube, irmão de Suá, gerou Meir. Meir gerou Estom.

[[v13-4-12]]

^<<v13-4-12,12>>^ Estom gerou Bete-Rafa, Paseia e Teína. Teína gerou Ir-Naás. Esses foram os habitantes de Reca.

[[v13-4-13]]

^<<v13-4-13,13>>^ Os filhos de Quenaz foram: Otniel e Seraías. Os filhos de Otniel foram: Hatate e Meonotai.

[[v13-4-14]]

^<<v13-4-14,14>>^ Meonotai gerou Ofra. Seraías gerou Joabe, fundador de Ge-Harasim, assim chamada porque seus habitantes eram artesãos.

[[v13-4-15]]

^<<v13-4-15,15>>^ Os filhos de Calebe, filho de Jefoné, foram: Iru, Elá e Naã. O filho de Elá foi Quenaz.

[[v13-4-16]]

^<<v13-4-16,16>>^ Os filhos de Jealelel foram: Zife, Zifa, Tiria e Asareel.

[[v13-4-17]]

^<<v13-4-17,17>>^ Os filhos de Ezra foram: Jéter, Merede, Éfer e Jalom. Uma das esposas de Merede deu à luz Miriã, Samai e Isbá, pai de Estemoa.

[[v13-4-18]]

^<<v13-4-18,18>>^ Ele se casou com uma mulher de Judá que deu à luz Jerede, pai de Gedor, Héber, pai de Socó, e Jecutiel, pai de Zanoa. Merede também se casou com Bitia, filha do faraó, e ela lhe deu filhos.

[[v13-4-19]]

^<<v13-4-19,19>>^ A esposa de Hodias era irmã de Naã. Um de seus filhos gerou Queila, o garmita, e o outro gerou Estemoa, o maacatita.

[[v13-4-20]]

^<<v13-4-20,20>>^ Os filhos de Simão foram: Amnom, Rina, Ben-Hanã e Tilom. Os filhos de Isi foram: Zoete e Ben-Zoete.

[[v13-4-21]]

^<<v13-4-21,21>>^ Os descendentes de Selá, filho de Judá, foram: Er, pai de Leca; Laada, pai de Maressa; os clãs dos que trabalham com linho em Bete-Asbeia;

[[v13-4-22]]

^<<v13-4-22,22>>^ Joquim; os homens de Cozeba; Joás e Sarafe, que governaram Moabe e Jasubi-Leém. Esses nomes vêm de registros antigos.

[[v13-4-23]]

^<<v13-4-23,23>>^ Eram oleiros que habitavam em Netaim e em Gederá e que trabalhavam para o rei.

[[v13-4-24]]

^<<v13-4-24,24>>^ Os filhos de Simeão foram: Jemuel, Jamim, Jaribe, Zoar e Saul.

[[v13-4-25]]

^<<v13-4-25,25>>^ Os descendentes de Saul foram: Salum, Mibsão e Misma.

[[v13-4-26]]

^<<v13-4-26,26>>^ Os descendentes de Misma foram: Hamuel, Zacur e Simei.

[[v13-4-27]]

^<<v13-4-27,27>>^ Simei teve dezesseis filhos e seis filhas, mas nenhum de seus irmãos teve uma família grande. Por isso a tribo de Simeão nunca chegou a ser tão numerosa quanto a tribo de Judá.

[[v13-4-28]]

^<<v13-4-28,28>>^ Habitavam em Berseba, Moladá, Hazar-Sual,

[[v13-4-29]]

^<<v13-4-29,29>>^ Bila, Azém, Tolade,

[[v13-4-30]]

^<<v13-4-30,30>>^ Betuel, Hormá, Ziclague,

[[v13-4-31]]

^<<v13-4-31,31>>^ Bete-Marcabote, Hazar-Susim, Bete-Biri e Saaraim. Essas cidades permaneceram sob seu controle até o tempo do rei Davi.

[[v13-4-32]]

^<<v13-4-32,32>>^ Seus descendentes também habitavam em Etã, Aim, Rimom, Toquém e Asã, cinco cidades

[[v13-4-33]]

^<<v13-4-33,33>>^ com os povoados ao seu redor, até Baalate. Esse era seu território, e esses nomes estão listados em seus registros genealógicos.

[[v13-4-34]]

^<<v13-4-34,34>>^ Outros descendentes de Simeão foram: Mesobabe, Janleque, Josa, filho de Amazias;

[[v13-4-35]]

^<<v13-4-35,35>>^ Joel, Jeú, filho de Josibias, filho de Seraías, filho de Asiel;

[[v13-4-36]]

^<<v13-4-36,36>>^ Elioenai, Jaacobá, Jesoaías, Asaías, Adiel, Jesimiel, Benaia

[[v13-4-37]]

^<<v13-4-37,37>>^ e Ziza, filho de Sifi, filho de Alom, filho de Jedaías, filho de Sinri e filho de Semaías.

[[v13-4-38]]

^<<v13-4-38,38>>^ Esses foram os nomes de alguns dos chefes dos clãs de Simeão. Suas famílias cresceram muito

[[v13-4-39]]

^<<v13-4-39,39>>^ e mudaram-se para a região de Gerar, na parte leste do vale, à procura de pastos para seus rebanhos.

[[v13-4-40]]

^<<v13-4-40,40>>^ Encontraram ali muitas pastagens boas, e a terra era ampla, tranquila e pacífica. Alguns dos descendentes de Cam tinham vivido naquela região.

[[v13-4-41]]

^<<v13-4-41,41>>^ Mas, durante o reinado de Ezequias, rei de Judá, esses líderes de Simeão invadiram a região e destruíram completamente as habitações dos descendentes de Cam e dos meunitas. Hoje não resta vestígio deles. Mataram todos que viviam ali e tomaram a terra para si, pois queriam bons pastos para seus rebanhos.

[[v13-4-42]]

^<<v13-4-42,42>>^ Quinhentos homens da tribo de Simeão invadiram o monte Seir, liderados por Pelatias, Nearias, Refaías e Uziel, filhos de Isi.

[[v13-4-43]]

^<<v13-4-43,43>>^ Destruíram os amalequitas que haviam sobrevivido, e habitam ali até hoje.

'''

xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[&#60; Capítulo Anterior] | <<v13-4-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-005.adoc#v13-5-0[Próximo Capítulo &#62;]