include::./index.adoc[]

[[v13-22-0]]
=== 1 Crônicas, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v13-22-1]]

^<<v13-22-1,1>>^ Então Davi disse: "Este será o lugar do templo do SENHOR Deus e o lugar do altar para os holocaustos de Israel!".

[[v13-22-2]]

^<<v13-22-2,2>>^ Davi deu ordens para reunir os estrangeiros que viviam em Israel e os encarregou de preparar as pedras cortadas para a construção do templo de Deus.

[[v13-22-3]]

^<<v13-22-3,3>>^ Davi providenciou grandes quantidades de ferro para os pregos necessários para as portas e suas dobradiças, e deu tanto bronze que não se podia pesar.

[[v13-22-4]]

^<<v13-22-4,4>>^ Também providenciou inúmeras toras de cedro, pois os homens de Tiro e Sidom lhe haviam trazido grandes quantidades dessa madeira.

[[v13-22-5]]

^<<v13-22-5,5>>^ Davi disse: "Meu filho Salomão ainda é jovem e inexperiente. Uma vez que o templo do SENHOR deve ser um edifício magnífico, famoso e glorioso por todo o mundo, começarei desde já a fazer os preparativos". Assim, antes de sua morte, Davi juntou grandes quantidades de materiais para a construção.

[[v13-22-6]]

^<<v13-22-6,6>>^ Então mandou chamar seu filho Salomão e lhe ordenou que construísse um templo para o SENHOR, o Deus de Israel.

[[v13-22-7]]

^<<v13-22-7,7>>^ Disse-lhe: "Meu filho, eu quis construir um templo em honra ao nome do SENHOR, meu Deus,

[[v13-22-8]]

^<<v13-22-8,8>>^ mas o SENHOR me disse: ‘Você matou muitos homens nas batalhas em que lutou. Derramou muito sangue diante de mim, por isso não será você quem construirá um templo em honra ao meu nome.

[[v13-22-9]]

^<<v13-22-9,9>>^ Contudo, você terá um filho que será um homem de paz. Darei a ele descanso de seus inimigos de todas as terras vizinhas. Seu nome será Salomão, e darei paz e tranquilidade a Israel durante seu reinado.

[[v13-22-10]]

^<<v13-22-10,10>>^ Ele construirá um templo em honra ao meu nome. Ele será meu filho, e eu serei seu pai, e eu estabelecerei o trono de seu reino sobre Israel para sempre’.

[[v13-22-11]]

^<<v13-22-11,11>>^ "Agora, meu filho, que o SENHOR seja com você e lhe dê êxito na construção do templo do SENHOR, seu Deus, exatamente como ele prometeu a seu respeito.

[[v13-22-12]]

^<<v13-22-12,12>>^ E que o SENHOR lhe dê sabedoria e entendimento, para que você obedeça à lei do SENHOR, seu Deus, ao governar Israel.

[[v13-22-13]]

^<<v13-22-13,13>>^ Você terá êxito se for cuidadoso em obedecer aos decretos e estatutos que o SENHOR ordenou a Israel por meio de Moisés. Seja forte e corajoso; não tenha medo nem desanime!

[[v13-22-14]]

^<<v13-22-14,14>>^ "Trabalhei arduamente para providenciar os materiais para a construção do templo do SENHOR: 3.500 toneladas de ouro, 35.000 toneladas de prata e tanto ferro e bronze que não se pode pesar. Também juntei madeira e pedra, embora talvez você precise providenciar mais.

[[v13-22-15]]

^<<v13-22-15,15>>^ Você tem muitos trabalhadores habilidosos: cortadores de pedra, pedreiros, carpinteiros e artesãos de todo tipo,

[[v13-22-16]]

^<<v13-22-16,16>>^ peritos nos trabalhos com ouro, prata, bronze e ferro. Agora comece a obra, e que o SENHOR esteja com você!".

[[v13-22-17]]

^<<v13-22-17,17>>^ Então Davi ordenou a todos os líderes de Israel que ajudassem Salomão nesse projeto.

[[v13-22-18]]

^<<v13-22-18,18>>^ "O SENHOR, seu Deus, está com vocês", declarou. "Ele lhes deu descanso das nações ao redor. Entregou-as em minhas mãos, e agora estão sujeitas ao SENHOR e ao seu povo.

[[v13-22-19]]

^<<v13-22-19,19>>^ Agora busquem o SENHOR, seu Deus, de todo o coração e de toda a alma. Construam o santuário do SENHOR Deus, a fim de trazer a arca da aliança do SENHOR e os utensílios sagrados para o templo edificado em honra ao nome do SENHOR."

'''

xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[&#60; Capítulo Anterior] | <<v13-22-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-023.adoc#v13-23-0[Próximo Capítulo &#62;]