include::./index.adoc[]

[[v13-12-0]]
=== 1 Crônicas, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v13-12-1]]

^<<v13-12-1,1>>^ Estes foram os homens que se juntaram a Davi em Ziclague, quando ele estava escondido de Saul, filho de Quis. Estavam entre os guerreiros que lutaram ao lado de Davi na batalha.

[[v13-12-2]]

^<<v13-12-2,2>>^ Todos eles eram arqueiros habilidosos, capazes de atirar flechas com o arco, ou pedras com a funda, tanto com a mão esquerda como com a direita. Eram todos parentes de Saul, da tribo de Benjamim.

[[v13-12-3]]

^<<v13-12-3,3>>^ Seu chefe era Aiezer, filho de Semaá, de Gibeá; seu irmão Joás era o segundo no comando. Os outros guerreiros foram: Jeziel e Pelete, filhos de Azmavete; Beraca; Jeú, de Anatote;

[[v13-12-4]]

^<<v13-12-4,4>>^ Ismaías, de Gibeom, guerreiro valente e líder entre os Trinta; Jeremias, Jaaziel, Joanã e Jozabade, de Gederá;

[[v13-12-5]]

^<<v13-12-5,5>>^ Eluzai, Jerimote, Bealias, Semarias e Sefatias, de Harufe;

[[v13-12-6]]

^<<v13-12-6,6>>^ Elcana, Issias, Azareel, Joezer e Jasobeão, todos coraítas;

[[v13-12-7]]

^<<v13-12-7,7>>^ Joela e Zebadias, filhos de Jeroão, de Gedor.

[[v13-12-8]]

^<<v13-12-8,8>>^ Alguns guerreiros valentes e treinados para o combate da tribo de Gade também se juntaram a Davi quando ele estava na fortaleza no deserto. Eram hábeis com o escudo e a lança, ferozes como leões e ágeis como gazelas nos montes.

[[v13-12-9]]

^<<v13-12-9,9>>^ Ézer era o chefe; Obadias, o segundo; Eliabe, o terceiro;

[[v13-12-10]]

^<<v13-12-10,10>>^ Mismana, o quarto; Jeremias, o quinto;

[[v13-12-11]]

^<<v13-12-11,11>>^ Atai, o sexto; Eliel, o sétimo;

[[v13-12-12]]

^<<v13-12-12,12>>^ Joanã, o oitavo; Elzabade, o nono;

[[v13-12-13]]

^<<v13-12-13,13>>^ Jeremias, o décimo; e Macbanai, o décimo primeiro.

[[v13-12-14]]

^<<v13-12-14,14>>^ Esses guerreiros de Gade eram comandantes do exército. O mais fraco deles era capaz de enfrentar cem soldados, e o mais forte, capaz de enfrentar mil.

[[v13-12-15]]

^<<v13-12-15,15>>^ Esses foram os homens que atravessaram o Jordão durante a época de cheia do rio, no início do ano, e expulsaram todos que habitavam nos vales nas margens leste e oeste.

[[v13-12-16]]

^<<v13-12-16,16>>^ Outros de Benjamim e de Judá se juntaram a Davi na fortaleza.

[[v13-12-17]]

^<<v13-12-17,17>>^ Davi foi ao encontro deles e lhes disse: "Se vieram em paz, para me ajudar, somos amigos. Mas, se vieram para me entregar a meus inimigos, embora eu seja inocente, que o Deus de seus antepassados veja isso e castigue vocês!".

[[v13-12-18]]

^<<v13-12-18,18>>^ Então o Espírito veio sobre Amasai, chefe dos Trinta, e ele disse: "Somos seus, Davi! Estamos do seu lado, filho de Jessé! Paz e prosperidade sejam com você e com todos que o ajudam, pois o seu Deus o ajuda!". Davi os recebeu e os nomeou oficiais de suas tropas.

[[v13-12-19]]

^<<v13-12-19,19>>^ Alguns homens de Manassés desertaram do exército israelita e se juntaram a Davi quando ele saiu com os filisteus para guerrear contra Saul. Os governantes filisteus, porém, não permitiram que Davi e seus homens fossem com eles. Depois de discutirem, mandaram-no embora, pois disseram: "Se Davi passar para o lado de Saul e voltar-se contra nós, isso custará nossa cabeça".

[[v13-12-20]]

^<<v13-12-20,20>>^ Os homens de Manassés que se uniram a Davi quando ele voltava para Ziclague foram: Adna, Jozabade, Jediael, Micael, Jozabade, Eliú e Ziletai. Cada um deles comandava mil soldados da tribo de Manassés.

[[v13-12-21]]

^<<v13-12-21,21>>^ Ajudaram Davi a perseguir bandos de saqueadores, pois eram guerreiros valentes que se tornaram comandantes de seu exército.

[[v13-12-22]]

^<<v13-12-22,22>>^ A cada dia, mais homens se juntavam a Davi, até que ele passou a ter um grande exército, como o exército de Deus.

[[v13-12-23]]

^<<v13-12-23,23>>^ Estes são os números de guerreiros armados que se uniram a Davi em Hebrom. Todos queriam que Davi se tornasse rei no lugar de Saul, como o SENHOR havia prometido.

[[v13-12-24]]

^<<v13-12-24,24>>^ Da tribo de Judá, 6.800 guerreiros armados com escudos e com lanças.

[[v13-12-25]]

^<<v13-12-25,25>>^ Da tribo de Simeão, 7.100 guerreiros valentes preparados para a guerra.

[[v13-12-26]]

^<<v13-12-26,26>>^ Da tribo de Levi, 4.600 guerreiros,

[[v13-12-27]]

^<<v13-12-27,27>>^ incluindo Joiada, chefe da família de Arão, com 3.700 homens sob seu comando,

[[v13-12-28]]

^<<v13-12-28,28>>^ e Zadoque, jovem guerreiro valente, com 22 oficiais, membros de sua família.

[[v13-12-29]]

^<<v13-12-29,29>>^ Da tribo de Benjamim, parente de Saul, 3.000 guerreiros. Até então, a maioria dos homens de Benjamim tinha permanecido leal a Saul.

[[v13-12-30]]

^<<v13-12-30,30>>^ Da tribo de Efraim, 20.800 guerreiros valentes, cada um deles muito respeitado em seu próprio clã.

[[v13-12-31]]

^<<v13-12-31,31>>^ Da meia tribo de Manassés a oeste do Jordão, 18.000 foram indicados por nome para ajudarem Davi a se tornar rei.

[[v13-12-32]]

^<<v13-12-32,32>>^ Da tribo de Issacar, 200 chefes com seus parentes. Todos eles entendiam bem os acontecimentos daquele tempo e sabiam qual era o melhor caminho para Israel seguir.

[[v13-12-33]]

^<<v13-12-33,33>>^ Da tribo de Zebulom, 50.000 guerreiros treinados. Estavam bem armados e preparados para a batalha e eram inteiramente leais a Davi.

[[v13-12-34]]

^<<v13-12-34,34>>^ Da tribo de Naftali, 1.000 oficiais e 37.000 guerreiros armados com escudos e lanças.

[[v13-12-35]]

^<<v13-12-35,35>>^ Da tribo de Dã, 28.600 guerreiros, todos preparados para a batalha.

[[v13-12-36]]

^<<v13-12-36,36>>^ Da tribo de Aser, 40.000 guerreiros treinados, todos preparados para a batalha.

[[v13-12-37]]

^<<v13-12-37,37>>^ Do lado leste do rio Jordão, onde habitavam as tribos de Rúben e Gade e a meia tribo de Manassés, 120.000 soldados equipados com todos os tipos de armas.

[[v13-12-38]]

^<<v13-12-38,38>>^ Todos esses soldados vieram a Hebrom em ordem de batalha, com o único propósito de fazer Davi rei sobre todo o Israel. Na verdade, todo o Israel concordava que ele devia ser seu rei.

[[v13-12-39]]

^<<v13-12-39,39>>^ Durante três dias, comeram e beberam com Davi, pois seus parentes haviam feito preparativos para recebê-los.

[[v13-12-40]]

^<<v13-12-40,40>>^ Pessoas de lugares tão distantes como Issacar, Zebulom e Naftali trouxeram provisões sobre jumentos, camelos, mulas e bois. Trouxeram grandes quantidades de farinha, bolos de figo, bolos de passas, vinho, azeite, bois e ovelhas para a celebração. Houve grande alegria em todo o Israel.

'''

xref:013-1-cronicas/013-1-cronicas-011.adoc#v13-11-0[&#60; Capítulo Anterior] | <<v13-12-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[Próximo Capítulo &#62;]