include::./index.adoc[]

[[v13-3-0]]
=== 1 Crônicas, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v13-3-1]]

^<<v13-3-1,1>>^ Estes são os filhos de Davi que nasceram em Hebrom: O mais velho era Amnom, filho de Ainoã, de Jezreel. O segundo era Daniel, filho de Abigail, do Carmelo.

[[v13-3-2]]

^<<v13-3-2,2>>^ O terceiro era Absalão, filho de Maaca, filha de Talmai, rei de Gesur. O quarto era Adonias, filho de Hagite.

[[v13-3-3]]

^<<v13-3-3,3>>^ O quinto era Sefatias, filho de Abital. O sexto era Itreão, filho de Eglá, esposa de Davi.

[[v13-3-4]]

^<<v13-3-4,4>>^ Esses foram os seis filhos de Davi nascidos em Hebrom, onde ele reinou por sete anos e meio. Depois Davi reinou por 33 anos em Jerusalém.

[[v13-3-5]]

^<<v13-3-5,5>>^ Os filhos de Davi nascidos em Jerusalém foram: Samua, Sobabe, Natã e Salomão; a mãe deles era Bate-Seba, filha de Amiel.

[[v13-3-6]]

^<<v13-3-6,6>>^ Davi também teve outros nove filhos: Ibar, Elisua, Elpalete,

[[v13-3-7]]

^<<v13-3-7,7>>^ Nogá, Nefegue, Jafia,

[[v13-3-8]]

^<<v13-3-8,8>>^ Elisama, Eliada e Elifelete.

[[v13-3-9]]

^<<v13-3-9,9>>^ Todos esses foram filhos de Davi, além dos filhos que teve com suas concubinas. Davi também teve uma filha chamada Tamar.

[[v13-3-10]]

^<<v13-3-10,10>>^ Os descendentes de Salomão foram: Roboão, Abias, Asa, Josafá,

[[v13-3-11]]

^<<v13-3-11,11>>^ Jeorão, Acazias, Joás,

[[v13-3-12]]

^<<v13-3-12,12>>^ Amazias, Uzias, Jotão,

[[v13-3-13]]

^<<v13-3-13,13>>^ Acaz, Ezequias, Manassés,

[[v13-3-14]]

^<<v13-3-14,14>>^ Amom, Josias.

[[v13-3-15]]

^<<v13-3-15,15>>^ Os filhos de Josias foram: o mais velho, Joanã; o segundo, Jeoaquim; o terceiro, Zedequias; e o quarto, Jeoacaz.

[[v13-3-16]]

^<<v13-3-16,16>>^ Os sucessores de Jeoaquim foram: seu filho Joaquim e seu irmão Zedequias.

[[v13-3-17]]

^<<v13-3-17,17>>^ Os filhos de Joaquim, exilado pelos babilônios, foram: Sealtiel,

[[v13-3-18]]

^<<v13-3-18,18>>^ Malquirão, Pedaías, Senazar, Jecamias, Hosama e Nedabias.

[[v13-3-19]]

^<<v13-3-19,19>>^ Os filhos de Pedaías foram: Zorobabel e Simei. Os filhos de Zorobabel foram: Mesulão e Hananias. A irmã deles se chamava Selomite.

[[v13-3-20]]

^<<v13-3-20,20>>^ Seus outros cinco filhos foram: Hasubá, Oel, Berequias, Hasadias e Jusabe-Hesede.

[[v13-3-21]]

^<<v13-3-21,21>>^ Os filhos de Hananias foram: Pelatias e Jesaías. O filho de Jesaías foi Refaías. O filho de Refaías foi Arnã. O filho de Arnã foi Obadias. O filho de Obadias foi Secanias.

[[v13-3-22]]

^<<v13-3-22,22>>^ Os descendentes de Secanias foram: Semaías e seus filhos Hatus, Igal, Bariá, Nearias e Safate, seis ao todo.

[[v13-3-23]]

^<<v13-3-23,23>>^ Os filhos de Nearias foram: Elioenai, Ezequias e Azricão, três ao todo.

[[v13-3-24]]

^<<v13-3-24,24>>^ Os filhos de Elioenai foram: Hodavias, Eliasibe, Pelaías, Acube, Joanã, Delaías e Anani, sete ao todo.

'''

xref:013-1-cronicas/013-1-cronicas-002.adoc#v13-2-0[&#60; Capítulo Anterior] | <<v13-3-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-004.adoc#v13-4-0[Próximo Capítulo &#62;]