include::./index.adoc[]

[[v13-18-0]]
=== 1 Crônicas, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v13-18-1]]

^<<v13-18-1,1>>^ Depois disso, Davi derrotou e sujeitou os filisteus, conquistando Gate e seus povoados.

[[v13-18-2]]

^<<v13-18-2,2>>^ Também conquistou a terra de Moabe, e os moabitas que foram poupados se tornaram súditos de Davi e lhe pagaram tributo.

[[v13-18-3]]

^<<v13-18-3,3>>^ Davi também destruiu o exército de Hadadezer, rei de Zobá, derrotando-o em Hamate, quando Hadadezer tentou fortalecer seu controle ao longo do rio Eufrates.

[[v13-18-4]]

^<<v13-18-4,4>>^ Davi tomou mil carros de guerra, sete mil cavaleiros e vinte mil soldados da infantaria. Levou cavalos suficientes para cem carros de guerra e aleijou o restante.

[[v13-18-5]]

^<<v13-18-5,5>>^ Quando os sírios de Damasco chegaram para ajudar Hadadezer, rei de Zobá, Davi matou 22 mil deles.

[[v13-18-6]]

^<<v13-18-6,6>>^ Então colocou destacamentos de seu exército em Damasco, a capital dos sírios. Assim Davi sujeitou os sírios, e eles lhe pagaram tributo. O SENHOR concedia vitórias a Davi por onde quer que ele fosse.

[[v13-18-7]]

^<<v13-18-7,7>>^ Davi levou para Jerusalém os escudos de ouro dos oficiais de Hadadezer,

[[v13-18-8]]

^<<v13-18-8,8>>^ bem como grande quantidade de bronze de Tebá e de Cum, cidades que pertenciam a Hadadezer. Mais tarde, Salomão derreteu o bronze e o usou para fazer o grande tanque de bronze chamado Mar, as colunas e os diversos utensílios de bronze do templo.

[[v13-18-9]]

^<<v13-18-9,9>>^ Quando Toí, rei de Hamate, soube que Davi tinha destruído todo o exército de Hadadezer, rei de Zobá,

[[v13-18-10]]

^<<v13-18-10,10>>^ enviou seu filho Jorão para parabenizar Davi por sua campanha bem-sucedida. Hadadezer e Toí eram inimigos e sempre estavam em guerra. Jorão presenteou Davi com objetos de prata, ouro e bronze.

[[v13-18-11]]

^<<v13-18-11,11>>^ O rei Davi dedicou todos esses presentes ao SENHOR, junto com a prata e o ouro que ele havia tomado de outras nações: de Edom, Moabe, Amom, da Filístia e de Amaleque.

[[v13-18-12]]

^<<v13-18-12,12>>^ Abisai, filho de Zeruia, destruiu dezoito mil edomitas no vale do Sal.

[[v13-18-13]]

^<<v13-18-13,13>>^ Colocou destacamentos do exército em Edom e, assim, todos os edomitas se tornaram súditos de Davi. O SENHOR concedia vitórias a Davi por onde quer que ele fosse.

[[v13-18-14]]

^<<v13-18-14,14>>^ Davi reinou sobre todo o Israel e fazia o que era justo e correto para seu povo.

[[v13-18-15]]

^<<v13-18-15,15>>^ Joabe, filho de Zeruia, era comandante de seu exército. Josafá, filho de Ailude, era o historiador do reino.

[[v13-18-16]]

^<<v13-18-16,16>>^ Zadoque, filho de Aitube, e Aimeleque, filho de Abiatar, eram sacerdotes. Seraías era o secretário da corte.

[[v13-18-17]]

^<<v13-18-17,17>>^ Benaia, filho de Joiada, era comandante da guarda pessoal do rei. E os filhos de Davi eram seus assistentes diretos.

'''

xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[&#60; Capítulo Anterior] | <<v13-18-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[Próximo Capítulo &#62;]