include::./index.adoc[]

[[v13-23-0]]
=== 1 Crônicas, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v13-23-1]]

^<<v13-23-1,1>>^ Quando Davi já era bem idoso, nomeou seu filho Salomão rei sobre Israel.

[[v13-23-2]]

^<<v13-23-2,2>>^ Convocou todos os líderes de Israel, e também os sacerdotes e os levitas.

[[v13-23-3]]

^<<v13-23-3,3>>^ Foram contados os levitas com 30 anos ou mais, e o total chegou a 38 mil.

[[v13-23-4]]

^<<v13-23-4,4>>^ De todos os levitas, 24 mil foram designados para supervisionar o trabalho no templo do SENHOR, 6 mil para ser oficiais e juízes,

[[v13-23-5]]

^<<v13-23-5,5>>^ 4 mil para ser guardas das portas e 4 mil para louvar o SENHOR com os instrumentos musicais que Davi fez para esse fim.

[[v13-23-6]]

^<<v13-23-6,6>>^ Davi dividiu os levitas em grupos com os nomes dos clãs descendentes dos três filhos de Levi: Gérson, Coate e Merari.

[[v13-23-7]]

^<<v13-23-7,7>>^ Os descendentes de Gérson foram: Libni e Simei, filhos de Gérson.

[[v13-23-8]]

^<<v13-23-8,8>>^ Os três filhos de Libni foram: Jeiel, o chefe da família, Zetã e Joel.

[[v13-23-9]]

^<<v13-23-9,9>>^ Esses foram os chefes da família de Libni. Três descendentes de Simei foram: Selemote, Haziel e Harã.

[[v13-23-10]]

^<<v13-23-10,10>>^ Outros quatro descendentes de Simei foram: Jaate, Ziza, Jeús e Berias.

[[v13-23-11]]

^<<v13-23-11,11>>^ Jaate era o chefe da família, e Ziza, o segundo. Jeús e Berias foram contados como uma só família, pois nenhum dos dois teve muitos filhos.

[[v13-23-12]]

^<<v13-23-12,12>>^ Quatro descendentes de Coate foram: Anrão, Isar, Hebrom e Uziel.

[[v13-23-13]]

^<<v13-23-13,13>>^ Os filhos de Anrão foram: Arão e Moisés. Arão e seus descendentes foram separados para consagrar as coisas santíssimas, queimar incenso na presença do SENHOR, servi-lo e pronunciar bênçãos em seu nome para sempre.

[[v13-23-14]]

^<<v13-23-14,14>>^ Quanto a Moisés, homem de Deus, seus filhos foram contados com a tribo de Levi.

[[v13-23-15]]

^<<v13-23-15,15>>^ Os filhos de Moisés foram: Gérson e Eliézer.

[[v13-23-16]]

^<<v13-23-16,16>>^ Um dos descendentes de Gérson foi Sebuel, chefe da família.

[[v13-23-17]]

^<<v13-23-17,17>>^ Eliézer teve apenas um filho, Reabias, o chefe da família. Reabias teve muitos descendentes.

[[v13-23-18]]

^<<v13-23-18,18>>^ Um dos descendentes de Isar foi Selomite, chefe da família.

[[v13-23-19]]

^<<v13-23-19,19>>^ Os descendentes de Hebrom foram: Jerias, o chefe da família, Amarias, o segundo, Jaaziel, o terceiro, e Jecameão, o quarto.

[[v13-23-20]]

^<<v13-23-20,20>>^ Os descendentes de Uziel foram: Mica, o chefe da família, e Issias, o segundo.

[[v13-23-21]]

^<<v13-23-21,21>>^ Os descendentes de Merari foram: Mali e Musi. Os filhos de Mali foram: Eleazar e Quis.

[[v13-23-22]]

^<<v13-23-22,22>>^ Eleazar morreu sem ter filhos; teve apenas filhas. Suas filhas se casaram com os primos delas, os filhos de Quis.

[[v13-23-23]]

^<<v13-23-23,23>>^ Três descendentes de Musi foram: Mali, Éder e Jeremote.

[[v13-23-24]]

^<<v13-23-24,24>>^ Estes foram os descendentes de Levi conforme seus clãs, os chefes de suas famílias, registrados por nome. Cada um precisava ter 20 anos ou mais a fim de se qualificar para o serviço na casa do SENHOR.

[[v13-23-25]]

^<<v13-23-25,25>>^ Pois Davi disse: "O SENHOR, Deus de Israel, nos deu paz e habitará sempre em Jerusalém.

[[v13-23-26]]

^<<v13-23-26,26>>^ Os levitas não precisam mais carregar o tabernáculo nem seus utensílios de um lugar para outro".

[[v13-23-27]]

^<<v13-23-27,27>>^ De acordo com as últimas instruções de Davi, foram registrados para o serviço todos os levitas de 20 anos ou mais.

[[v13-23-28]]

^<<v13-23-28,28>>^ O trabalho dos levitas era ajudar os sacerdotes, os descendentes de Arão, no serviço da casa do SENHOR. Também cuidavam dos pátios e das salas laterais, ajudavam a realizar as cerimônias de purificação e serviam na casa de Deus de várias outras maneiras.

[[v13-23-29]]

^<<v13-23-29,29>>^ Eram encarregados dos pães da presença colocados sobre a mesa, da farinha da melhor qualidade para as ofertas de cereais, dos bolos sem fermento, dos pães assados em azeite e da mistura das massas. Eram responsáveis, ainda, por verificar todos os pesos e medidas.

[[v13-23-30]]

^<<v13-23-30,30>>^ Todas as manhãs e todas as tardes, apresentavam-se diante do SENHOR para entoar cânticos de ação de graças e louvor.

[[v13-23-31]]

^<<v13-23-31,31>>^ Ajudavam nos holocaustos oferecidos ao SENHOR nos sábados, nas festas de lua nova e em todas as outras festas fixas. O número requerido de levitas estava sempre de serviço na presença do SENHOR, e seguiam todos os procedimentos que lhes haviam sido prescritos.

[[v13-23-32]]

^<<v13-23-32,32>>^ E assim, sob a supervisão dos sacerdotes, os descendentes de Arão, os levitas guardavam a tenda do encontro e o santuário e cumpriam seus deveres no serviço da casa do SENHOR.

'''

xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[&#60; Capítulo Anterior] | <<v13-23-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-024.adoc#v13-24-0[Próximo Capítulo &#62;]