include::./index.adoc[]

[[v13-29-0]]
=== 1 Crônicas, 29
// nvt ?, NVT - Nova Versão Transformadora

[[v13-29-1]]

^<<v13-29-1,1>>^ O rei Davi se voltou para toda a comunidade e disse: "Meu filho Salomão, que Deus escolheu, ainda é jovem e inexperiente. O trabalho que ele tem pela frente é enorme, pois o templo que ele construirá não será para meros humanos, mas para o SENHOR Deus.

[[v13-29-2]]

^<<v13-29-2,2>>^ Usando todos os recursos a meu dispor, juntei o que pude para a construção do templo de meu Deus. Agora, há ouro, prata, bronze, ferro e madeira suficientes, bem como grandes quantidades de ônix e outras pedras preciosas, joias caras, todo tipo de pedra da melhor qualidade e mármore.

[[v13-29-3]]

^<<v13-29-3,3>>^ "E agora, por causa de minha alegria com a construção do templo de meu Deus, entrego todos os meus tesouros pessoais, ouro e prata, para ajudar na construção, além de todos os materiais que juntei para o santo templo.

[[v13-29-4]]

^<<v13-29-4,4>>^ Ofereço 105 toneladas de ouro de Ofir e 245 toneladas de prata refinada para revestir as paredes das construções,

[[v13-29-5]]

^<<v13-29-5,5>>^ e para os outros trabalhos em ouro e prata a serem feitos pelos artesãos. Quem seguirá meu exemplo e entregará, hoje, ofertas ao SENHOR?".

[[v13-29-6]]

^<<v13-29-6,6>>^ Então os chefes das famílias, os líderes das tribos, os generais e os capitães, e os administradores do rei ofertaram voluntariamente.

[[v13-29-7]]

^<<v13-29-7,7>>^ Para a construção do templo de Deus, entregaram 175 toneladas de ouro, 10.000 peças de ouro, 350 toneladas de prata, 630 toneladas de bronze e 3.500 toneladas de ferro.

[[v13-29-8]]

^<<v13-29-8,8>>^ Também contribuíram com pedras preciosas, que foram guardadas no tesouro da casa do SENHOR, sob os cuidados de Jeiel, descendente de Gérson.

[[v13-29-9]]

^<<v13-29-9,9>>^ O povo se alegrou com as ofertas, pois as entregou ao SENHOR voluntariamente e de todo o coração, e o rei Davi também se encheu de alegria.

[[v13-29-10]]

^<<v13-29-10,10>>^ Então Davi louvou o SENHOR na presença de toda a comunidade: "Ó SENHOR, Deus de nosso antepassado Israel, louvado sejas para sempre!

[[v13-29-11]]

^<<v13-29-11,11>>^ Ó SENHOR, a ti pertencem a grandeza, o poder, a glória, a vitória e a majestade. Tudo que há nos céus e na terra é teu, ó SENHOR, e este é teu reino. Tu estás acima de tudo.

[[v13-29-12]]

^<<v13-29-12,12>>^ Riqueza e honra vêm somente de ti, pois tu governas sobre tudo. Poder e força estão em tuas mãos, e cabe a ti exaltar e dar força.

[[v13-29-13]]

^<<v13-29-13,13>>^ "Ó nosso Deus, damos graças e louvamos teu nome glorioso!

[[v13-29-14]]

^<<v13-29-14,14>>^ Mas quem sou eu, e quem é meu povo, para que pudéssemos te dar alguma coisa? Tudo que temos vem de ti, e demos apenas o que primeiro de ti recebemos!

[[v13-29-15]]

^<<v13-29-15,15>>^ Somos estrangeiros e peregrinos na terra, como nossos antepassados antes de nós. Nossos dias na terra são como uma sombra, passam rápido, sem deixar vestígio.

[[v13-29-16]]

^<<v13-29-16,16>>^ "Ó SENHOR, nosso Deus, até mesmo estes materiais que juntamos para construir um templo em honra ao teu nome santo vêm de ti! Tudo pertence a ti!

[[v13-29-17]]

^<<v13-29-17,17>>^ Eu sei, meu Deus, que examinas nosso coração e te regozijas quando nele encontras integridade. Tu sabes que fiz tudo isso com boas intenções e vi teu povo entregar ofertas voluntariamente e com alegria.

[[v13-29-18]]

^<<v13-29-18,18>>^ "Ó SENHOR, o Deus de nossos antepassados Abraão, Isaque e Israel, leva teu povo a sempre desejar te obedecer. Mantém o coração deles sempre leal a ti.

[[v13-29-19]]

^<<v13-29-19,19>>^ Dá a meu filho Salomão o desejo sincero de obedecer a todos os teus mandamentos, preceitos e decretos, e de fazer todo o necessário a fim de construir este templo, para o qual realizei estes preparativos".

[[v13-29-20]]

^<<v13-29-20,20>>^ Então Davi disse a toda a comunidade: "Louvem o SENHOR, seu Deus!". E toda a comunidade louvou o SENHOR, o Deus de seus antepassados, e eles se prostraram e se ajoelharam diante do SENHOR e do rei.

[[v13-29-21]]

^<<v13-29-21,21>>^ No dia seguinte, trouxeram mil novilhos, mil carneiros e mil cordeiros e os apresentaram ao SENHOR como sacrifícios e holocaustos. Também trouxeram ofertas derramadas e muitos outros sacrifícios em favor de todo o Israel.

[[v13-29-22]]

^<<v13-29-22,22>>^ Naquele dia, festejaram e comeram na presença do SENHOR com grande alegria. Mais uma vez, proclamaram Salomão, filho de Davi, como rei. Ungiram Salomão diante do SENHOR, como seu líder, e ungiram Zadoque como sacerdote.

[[v13-29-23]]

^<<v13-29-23,23>>^ Salomão se sentou no trono do SENHOR em lugar de seu pai, Davi. Foi bem-sucedido em tudo, e todo o Israel lhe obedecia.

[[v13-29-24]]

^<<v13-29-24,24>>^ Todos os oficiais, os guerreiros e os filhos de Davi prometeram ser leais ao rei Salomão.

[[v13-29-25]]

^<<v13-29-25,25>>^ O SENHOR exaltou Salomão diante de todo o Israel e lhe deu mais esplendor que qualquer outro rei de Israel antes dele.

[[v13-29-26]]

^<<v13-29-26,26>>^ Davi, filho de Jessé, reinou sobre todo o Israel.

[[v13-29-27]]

^<<v13-29-27,27>>^ Reinou em Israel por quarenta anos, sete anos em Hebrom e 33 em Jerusalém.

[[v13-29-28]]

^<<v13-29-28,28>>^ Morreu em boa velhice, depois de desfrutar uma vida longa, cheia de riqueza e honra. Seu filho Salomão foi seu sucessor.

[[v13-29-29]]

^<<v13-29-29,29>>^ Todos os acontecimentos do reinado de Davi, do início ao fim, estão escritos no Registro do Vidente Samuel , no Registro do Profeta Natã  e no Registro do Vidente Gade ,

[[v13-29-30]]

^<<v13-29-30,30>>^ incluindo os grandes feitos de seu reinado e tudo que aconteceu com ele, com Israel e com todos os reinos vizinhos.

'''

xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[&#60; Capítulo Anterior] | <<v13-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[Próximo Capítulo &#62;]