include::./index.adoc[]

[[v13-1-0]]
=== 1 Crônicas, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v13-1-1]]

^<<v13-1-1,1>>^ Os descendentes de Adão foram: Sete, Enos,

[[v13-1-2]]

^<<v13-1-2,2>>^ Cainã, Maalalel, Jarede,

[[v13-1-3]]

^<<v13-1-3,3>>^ Enoque, Matusalém, Lameque

[[v13-1-4]]

^<<v13-1-4,4>>^ e Noé. Os filhos de Noé foram: Sem, Cam e Jafé.

[[v13-1-5]]

^<<v13-1-5,5>>^ Os descendentes de Jafé foram: Gômer, Magogue, Madai, Javã, Tubal, Meseque e Tirás.

[[v13-1-6]]

^<<v13-1-6,6>>^ Os descendentes de Gômer foram: Asquenaz, Rifate e Togarma.

[[v13-1-7]]

^<<v13-1-7,7>>^ Os descendentes de Javã foram: Elisá, Társis, Quitim e Rodanim.

[[v13-1-8]]

^<<v13-1-8,8>>^ Os descendentes de Cam foram: Cuxe, Mizraim, Pute e Canaã.

[[v13-1-9]]

^<<v13-1-9,9>>^ Os descendentes de Cuxe foram: Sebá, Havilá, Sabtá, Raamá e Sabtecá. Os descendentes de Raamá foram: Sabá e Dedã.

[[v13-1-10]]

^<<v13-1-10,10>>^ Cuxe também foi o antepassado de Ninrode, o primeiro guerreiro valente da terra.

[[v13-1-11]]

^<<v13-1-11,11>>^ Mizraim foi o antepassado dos luditas, anamitas, leabitas, naftuítas,

[[v13-1-12]]

^<<v13-1-12,12>>^ patrusitas, casluítas e dos caftoritas, dos quais descendem os filisteus.

[[v13-1-13]]

^<<v13-1-13,13>>^ O filho mais velho de Canaã foi Sidom. Canaã também foi o antepassado dos hititas,

[[v13-1-14]]

^<<v13-1-14,14>>^ jebuseus, amorreus, girgaseus,

[[v13-1-15]]

^<<v13-1-15,15>>^ heveus, arqueus, sineus,

[[v13-1-16]]

^<<v13-1-16,16>>^ arvadeus, zemareus e hamateus.

[[v13-1-17]]

^<<v13-1-17,17>>^ Os descendentes de Sem foram: Elão, Assur, Arfaxade, Lude e Arã. Os descendentes de Arã foram: Uz, Hul, Géter e Más.

[[v13-1-18]]

^<<v13-1-18,18>>^ Arfaxade gerou Salá, e Salá gerou Héber.

[[v13-1-19]]

^<<v13-1-19,19>>^ Héber teve dois filhos. O primeiro recebeu o nome de Pelegue, pois em sua época a terra foi dividida. O irmão de Pelegue recebeu o nome de Joctã.

[[v13-1-20]]

^<<v13-1-20,20>>^ Joctã foi o antepassado de Almodá, Salefe, Hazarmavé, Jerá,

[[v13-1-21]]

^<<v13-1-21,21>>^ Adorão, Uzal, Dicla,

[[v13-1-22]]

^<<v13-1-22,22>>^ Obal, Abimael, Sabá,

[[v13-1-23]]

^<<v13-1-23,23>>^ Ofir, Havilá e Jobabe. Todos eles foram descendentes de Joctã.

[[v13-1-24]]

^<<v13-1-24,24>>^ Os descendentes de Sem foram: Arfaxade, Selá,

[[v13-1-25]]

^<<v13-1-25,25>>^ Héber, Pelegue, Reú,

[[v13-1-26]]

^<<v13-1-26,26>>^ Serugue, Naor, Terá

[[v13-1-27]]

^<<v13-1-27,27>>^ e Abrão, mais tarde chamado de Abraão.

[[v13-1-28]]

^<<v13-1-28,28>>^ Os filhos de Abraão foram: Isaque e Ismael.

[[v13-1-29]]

^<<v13-1-29,29>>^ Estes são seus registros genealógicos: Os filhos de Ismael foram: Nebaiote, o mais velho, Quedar, Adbeel, Mibsão,

[[v13-1-30]]

^<<v13-1-30,30>>^ Misma, Dumá, Massá, Hadade, Temá,

[[v13-1-31]]

^<<v13-1-31,31>>^ Jetur, Nafis e Quedemá. Esses foram os filhos de Ismael.

[[v13-1-32]]

^<<v13-1-32,32>>^ Estes foram os filhos de Quetura, concubina de Abraão: Zinrã, Jocsã, Medã, Midiã, Isbaque e Suá. Os filhos de Jocsã foram: Sabá e Dedã.

[[v13-1-33]]

^<<v13-1-33,33>>^ Os filhos de Midiã foram: Efá, Éfer, Enoque, Abida e Elda. Todos esses foram descendentes de Abraão com sua concubina Quetura.

[[v13-1-34]]

^<<v13-1-34,34>>^ Abraão gerou Isaque. Os filhos de Isaque foram: Esaú e Israel.

[[v13-1-35]]

^<<v13-1-35,35>>^ Os filhos de Esaú foram: Elifaz, Reuel, Jeús, Jalão e Corá.

[[v13-1-36]]

^<<v13-1-36,36>>^ Os descendentes de Elifaz foram: Temã, Omar, Zefô, Gaetã, Quenaz e Amaleque, que nasceu a Timna.

[[v13-1-37]]

^<<v13-1-37,37>>^ Os descendentes de Reuel foram: Naate, Zerá, Samá e Mizá.

[[v13-1-38]]

^<<v13-1-38,38>>^ Os descendentes de Seir foram: Lotã, Sobal, Zibeão, Aná, Disom, Ézer e Disã.

[[v13-1-39]]

^<<v13-1-39,39>>^ Os descendentes de Lotã foram: Hori e Hemã. A irmã de Lotã se chamava Timna.

[[v13-1-40]]

^<<v13-1-40,40>>^ Os descendentes de Sobal foram: Alvã, Maanate, Ebal, Sefô e Onã. Os descendentes de Zibeão foram: Aiá e Aná.

[[v13-1-41]]

^<<v13-1-41,41>>^ O filho de Aná foi Disom. Os descendentes de Disom foram: Hendã, Esbã, Itrã e Querã.

[[v13-1-42]]

^<<v13-1-42,42>>^ Os descendentes de Ézer foram: Bilã, Zaavã e Acã. Os descendentes de Disã foram: Uz e Arã.

[[v13-1-43]]

^<<v13-1-43,43>>^ Estes são os reis que governaram na terra de Edom antes de os israelitas terem rei: Belá, filho de Beor, reinou na cidade de Dinabá.

[[v13-1-44]]

^<<v13-1-44,44>>^ Quando Belá morreu, Jobabe, filho de Zerá, de Bozra, foi seu sucessor.

[[v13-1-45]]

^<<v13-1-45,45>>^ Quando Jobabe morreu, Husã, da terra dos temanitas, foi seu sucessor.

[[v13-1-46]]

^<<v13-1-46,46>>^ Quando Husã morreu, Hadade, filho de Bedade, foi seu sucessor na cidade de Avite. Foi Hadade quem derrotou os midianitas na terra de Moabe.

[[v13-1-47]]

^<<v13-1-47,47>>^ Quando Hadade morreu, Samlá, da cidade de Masreca, foi seu sucessor.

[[v13-1-48]]

^<<v13-1-48,48>>^ Quando Samlá morreu, Saul, da cidade de Reobote, próxima ao Eufrates, foi seu sucessor.

[[v13-1-49]]

^<<v13-1-49,49>>^ Quando Saul morreu, Baal-Hanã, filho de Acbor, foi seu sucessor.

[[v13-1-50]]

^<<v13-1-50,50>>^ Quando Baal-Hanã morreu, Hadade foi seu sucessor na cidade de Paú. Sua mulher era Meetabel, filha de Matrede e neta de Mezaabe.

[[v13-1-51]]

^<<v13-1-51,51>>^ Então Hadade morreu. Os chefes dos clãs de Edom foram: Timna, Alvá, Jetete,

[[v13-1-52]]

^<<v13-1-52,52>>^ Oolibama, Elá, Pinom,

[[v13-1-53]]

^<<v13-1-53,53>>^ Quenaz, Temã, Mibzar,

[[v13-1-54]]

^<<v13-1-54,54>>^ Magdiel e Irã. Esses foram os chefes dos clãs de Edom.

'''

xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[&#60; Capítulo Anterior] | <<v13-1-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-002.adoc#v13-2-0[Próximo Capítulo &#62;]