include::./index.adoc[]

[[v13-26-0]]
=== 1 Crônicas, 26
// nvt ?, NVT - Nova Versão Transformadora

[[v13-26-1]]

^<<v13-26-1,1>>^ Estas são as divisões dos guardas das portas: Dos coraítas: Meselemias, filho de Coré, da família de Abiasafe.

[[v13-26-2]]

^<<v13-26-2,2>>^ O primeiro filho de Meselamias foi Zacarias, o segundo, Jediael, o terceiro, Zebadias, o quarto, Jatniel,

[[v13-26-3]]

^<<v13-26-3,3>>^ o quinto, Elão, o sexto, Joanã, e o sétimo, Elioenai.

[[v13-26-4]]

^<<v13-26-4,4>>^ O primeiro filho de Obede-Edom foi Semaías, o segundo, Jeozabade, o terceiro, Joá, o quarto, Sacar, o quinto, Natanael,

[[v13-26-5]]

^<<v13-26-5,5>>^ o sexto, Amiel, o sétimo, Issacar, e o oitavo, Peuletai. Deus havia abençoado Obede-Edom.

[[v13-26-6]]

^<<v13-26-6,6>>^ Semaías, filho de Obede-Edom, teve filhos muito capazes, que ocuparam posições de grande autoridade no clã.

[[v13-26-7]]

^<<v13-26-7,7>>^ Estes eram os nomes deles: Otni, Rafael, Obede e Elzabade. Seus parentes, Eliú e Semaquias, também foram homens muito capazes.

[[v13-26-8]]

^<<v13-26-8,8>>^ Todos esses descendentes de Obede-Edom, incluindo seus filhos e parentes, 62 ao todo, foram homens muito capazes e aptos para seu trabalho.

[[v13-26-9]]

^<<v13-26-9,9>>^ Os dezoito filhos e parentes de Meselamias também foram homens muito capazes.

[[v13-26-10]]

^<<v13-26-10,10>>^ Os filhos de Hosa, do clã de Merari, foram: Sinri, nomeado chefe por seu pai, embora não fosse o mais velho,

[[v13-26-11]]

^<<v13-26-11,11>>^ Hilquias, o segundo, Tebalias, o terceiro, e Zacarias, o quarto. Os filhos e parentes de Hosá foram treze ao todo.

[[v13-26-12]]

^<<v13-26-12,12>>^ Essas divisões de guardas das portas foram feitas conforme os chefes de suas famílias. Os guardas, como os outros levitas, serviam na casa do SENHOR.

[[v13-26-13]]

^<<v13-26-13,13>>^ Foram encarregados de guardar as portas por sorteio, de acordo com as famílias, sem levar em conta idade ou treinamento.

[[v13-26-14]]

^<<v13-26-14,14>>^ Meselemias e seu grupo ficaram responsáveis pela porta leste. Seu filho Zacarias, conselheiro de grande sabedoria, ficou responsável pela porta norte.

[[v13-26-15]]

^<<v13-26-15,15>>^ Obede-Edom ficou responsável pela porta sul, e seus filhos, pelo depósito.

[[v13-26-16]]

^<<v13-26-16,16>>^ Supim e Hosa ficaram responsáveis pela porta oeste e pela passagem que dava para o templo. O serviço dos guardas foi dividido de forma igual.

[[v13-26-17]]

^<<v13-26-17,17>>^ Todos os dias, seis levitas ficavam encarregados da porta leste, quatro da porta norte, quatro da porta sul, e duas duplas do depósito.

[[v13-26-18]]

^<<v13-26-18,18>>^ Cada dia, seis ficavam encarregados da porta oeste, quatro da passagem que dava para o templo, e dois do pátio.

[[v13-26-19]]

^<<v13-26-19,19>>^ Essas foram as divisões dos guardas das portas dos clãs de Coré e de Merari.

[[v13-26-20]]

^<<v13-26-20,20>>^ Outros levitas, sob a liderança de Aías, eram encarregados dos tesouros da casa de Deus e dos depósitos onde ficavam os objetos consagrados.

[[v13-26-21]]

^<<v13-26-21,21>>^ Da família de Libni, no clã de Gérson, Jeiel era o chefe.

[[v13-26-22]]

^<<v13-26-22,22>>^ Os filhos de Jeiel, Zetã e seu irmão Joel, eram encarregados dos tesouros da casa do SENHOR.

[[v13-26-23]]

^<<v13-26-23,23>>^ Os líderes descendentes de Anrão, de Isar, de Hebrom e de Uziel foram:

[[v13-26-24]]

^<<v13-26-24,24>>^ Do clã de Anrão, Sebuel foi descendente de Gérson, filho de Moisés. Era o oficial encarregado dos tesouros.

[[v13-26-25]]

^<<v13-26-25,25>>^ Suas gerações de parentes por parte de Eliézer foram: Reabias, Jesaías, Jorão, Zicri e Selemote.

[[v13-26-26]]

^<<v13-26-26,26>>^ Selemote e seus parentes eram encarregados dos tesouros que o rei Davi, os chefes das famílias, os generais e capitães e outros oficiais do exército haviam dedicado ao SENHOR.

[[v13-26-27]]

^<<v13-26-27,27>>^ Esses homens dedicaram parte dos despojos que haviam obtido nas batalhas para a manutenção da casa do SENHOR.

[[v13-26-28]]

^<<v13-26-28,28>>^ Selomote e seus parentes também cuidavam de todas as ofertas dedicadas ao SENHOR pelo vidente Samuel, por Saul, filho de Quis, por Abner, filho de Ner, e por Joabe, filho de Zeruia. Eram responsáveis, ainda, pelas demais ofertas dedicadas ao SENHOR.

[[v13-26-29]]

^<<v13-26-29,29>>^ Do clã de Isar, Quenanias e seus filhos receberam as responsabilidades administrativas de Israel como oficiais e juízes.

[[v13-26-30]]

^<<v13-26-30,30>>^ Do clã de Hebrom, Hasabias e seus parentes, 1.700 homens capazes, foram encarregados das terras israelitas a oeste do rio Jordão. Eram responsáveis por todas as questões relacionadas ao serviço do SENHOR e do rei nessa região.

[[v13-26-31]]

^<<v13-26-31,31>>^ Também do clã de Hebrom, Jerias era o chefe dos hebronitas, de acordo com os registros genealógicos. No quadragésimo ano do reinado de Davi, fez-se uma busca nos registros e foram encontrados homens capazes do clã de Hebrom em Jazer, na terra de Gileade.

[[v13-26-32]]

^<<v13-26-32,32>>^ Havia 2.700 homens capazes e chefes de família entre os parentes de Jerias. O rei Davi os enviou para o lado leste do Jordão e os encarregou das tribos de Rúben e Gade e da meia tribo de Manassés. Eram responsáveis por todas as questões relacionadas a Deus e ao rei.

'''

xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[&#60; Capítulo Anterior] | <<v13-26-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[Próximo Capítulo &#62;]