include::./index.adoc[]

[[v13-20-0]]
=== 1 Crônicas, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v13-20-1]]

^<<v13-20-1,1>>^ No começo do ano, época em que os reis costumavam ir à guerra, Joabe conduziu o exército israelita em ataques bem-sucedidos contra a terra dos amonitas. Durante essas operações, cercou a cidade de Rabá, a atacou e a destruiu. Mas Davi ficou em Jerusalém. Joabe conquistou Rabá e a destruiu.

[[v13-20-2]]

^<<v13-20-2,2>>^ Então Davi chegou a Rabá, removeu a coroa da cabeça do rei, e ela foi colocada sobre sua cabeça. A coroa era feita de ouro, enfeitada com pedras preciosas, e pesava cerca de 35 quilos. Davi tomou grande quantidade de despojos da cidade.

[[v13-20-3]]

^<<v13-20-3,3>>^ Também tornou os habitantes de Rabá seus escravos e os obrigou a trabalhar com serras, picaretas e machados de ferro. Foi assim que Davi tratou o povo de todas as cidades amonitas. Então ele e todo o exército voltaram para Jerusalém.

[[v13-20-4]]

^<<v13-20-4,4>>^ Depois disso, houve guerra contra os filisteus em Gezer. Enquanto lutavam, Sibecai, de Husate, matou Safe, um descendente de gigantes, e, desse modo, os filisteus foram subjugados.

[[v13-20-5]]

^<<v13-20-5,5>>^ Durante outra batalha contra os filisteus, Elanã, filho de Jair, matou Lami, irmão de Golias, de Gate. O cabo da lança de Lami era da grossura de um eixo de tecelão.

[[v13-20-6]]

^<<v13-20-6,6>>^ Em outra batalha com os filisteus em Gate, havia um homem de grande estatura com seis dedos em cada mão e seis dedos em cada pé, 24 dedos ao todo, que também era descendente de gigantes.

[[v13-20-7]]

^<<v13-20-7,7>>^ Mas, quando ele desafiou os israelitas e zombou deles, foi morto por Jônatas, filho de Simeia, irmão de Davi.

[[v13-20-8]]

^<<v13-20-8,8>>^ Esses filisteus eram descendentes dos gigantes de Gate, mas Davi e seus guerreiros os mataram.

'''

xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[&#60; Capítulo Anterior] | <<v13-20-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[Próximo Capítulo &#62;]