include::./index.adoc[]

[[v13-7-0]]
=== 1 Crônicas, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v13-7-1]]

^<<v13-7-1,1>>^ Os quatro filhos de Issacar foram: Tolá, Puá, Jasube e Sinrom.

[[v13-7-2]]

^<<v13-7-2,2>>^ Os filhos de Tolá foram: Uzi, Refaías, Jeriel, Jamai, Ibsão e Samuel. Cada um deles foi chefe de um clã. No tempo do rei Davi, o total de homens aptos para a guerra listados no registro desses clãs era de 22.600.

[[v13-7-3]]

^<<v13-7-3,3>>^ O filho de Uzi foi Israías. Os filhos de Israías foram: Micael, Obadias, Joel e Issias. Os cinco foram chefes de clãs.

[[v13-7-4]]

^<<v13-7-4,4>>^ Todos eles tiveram muitas esposas e muitos filhos, por isso o total de homens disponíveis para o serviço militar entre seus descendentes era de 36.000.

[[v13-7-5]]

^<<v13-7-5,5>>^ O total de homens aptos para a guerra de todos os clãs da tribo de Issacar era de 87.000. Todos eles foram listados nos registros genealógicos.

[[v13-7-6]]

^<<v13-7-6,6>>^ Os três filhos de Benjamim foram: Belá, Bequer e Jediael.

[[v13-7-7]]

^<<v13-7-7,7>>^ Os cinco filhos de Belá foram: Esbom, Uzi, Uziel, Jerimote e Iri. Cada um deles foi chefe de um clã. O total de homens aptos para a guerra desses clãs era de 22.034, conforme listado nos registros genealógicos.

[[v13-7-8]]

^<<v13-7-8,8>>^ Os filhos de Bequer foram: Zemira, Joás, Eliézer, Elioenai, Onri, Jeremote, Abias, Anatote e Alemete.

[[v13-7-9]]

^<<v13-7-9,9>>^ Cada um deles foi chefe de um clã. O total de homens aptos para a guerra e chefes desses clãs era de 20.200, conforme listado nos registros genealógicos.

[[v13-7-10]]

^<<v13-7-10,10>>^ O filho de Jediael foi Bilã. Os filhos de Bilã foram: Jeús, Benjamim, Eúde, Quenaaná, Zetã, Társis e Aisaar.

[[v13-7-11]]

^<<v13-7-11,11>>^ Cada um deles foi chefe de um clã. O total de homens aptos para a guerra desses clãs era de 17.200.

[[v13-7-12]]

^<<v13-7-12,12>>^ Os filhos de Ir foram: Supim e Hupim. O filho de Aer foi Husim.

[[v13-7-13]]

^<<v13-7-13,13>>^ Os filhos de Naftali foram: Jazeel, Guni, Jezer e Silém. Todos eles foram descendentes de Bila, concubina de Jacó.

[[v13-7-14]]

^<<v13-7-14,14>>^ Os descendentes de Manassés com sua concubina arameia foram: Asriel e Maquir, pai de Gileade.

[[v13-7-15]]

^<<v13-7-15,15>>^ Maquir se casou com uma mulher do clã de Hupim e Supim. A irmã de Maquir se chamava Maaca. Outro descendente de Manassés foi Zelofedade, que só teve filhas.

[[v13-7-16]]

^<<v13-7-16,16>>^ Maaca, esposa de Maquir, deu à luz um filho e lhe deu o nome de Perez. Seu irmão se chamava Seres. Os filhos de Perez foram: Ulão e Requém.

[[v13-7-17]]

^<<v13-7-17,17>>^ O filho de Ulão foi Bedã. Todos esses foram descendentes de Gileade, filho de Maquir, filho de Manassés.

[[v13-7-18]]

^<<v13-7-18,18>>^ Hamolequete, irmã de Maquir, deu à luz Isode, Abiezer e Maalá.

[[v13-7-19]]

^<<v13-7-19,19>>^ Os filhos de Semida foram: Aiã, Siquém, Liqui e Anião.

[[v13-7-20]]

^<<v13-7-20,20>>^ Os descendentes de Efraim foram: Sutela, Berede, Taate, Eleada, Taate,

[[v13-7-21]]

^<<v13-7-21,21>>^ Zabade, Sutela, Ézer e Eleade. Estes dois foram mortos quando tentavam roubar o gado de moradores dos arredores de Gate.

[[v13-7-22]]

^<<v13-7-22,22>>^ Seu pai, Efraim, lamentou sua morte por muito tempo, e seus parentes vieram consolá-lo.

[[v13-7-23]]

^<<v13-7-23,23>>^ Depois, Efraim teve relações com sua esposa, e ela engravidou e deu à luz um filho. Efraim lhe deu o nome de Berias, por causa da desgraça que sua família havia sofrido.

[[v13-7-24]]

^<<v13-7-24,24>>^ Sua filha se chamava Seerá. Ela construiu as cidades de Bete-Horom Baixa, Bete-Horom Alta e Uzém-Seerá.

[[v13-7-25]]

^<<v13-7-25,25>>^ Os descendentes de Efraim foram: Refa, Resefe, Telá, Taã,

[[v13-7-26]]

^<<v13-7-26,26>>^ Ladã, Amiúde, Elisama,

[[v13-7-27]]

^<<v13-7-27,27>>^ Num e Josué.

[[v13-7-28]]

^<<v13-7-28,28>>^ Os descendentes de Efraim habitavam no território que incluía Betel e seus povoados ao sul, Naarã a leste, Gezer e seus povoados a oeste, e Siquém e seus povoados ao norte, até Aiá e seus povoados.

[[v13-7-29]]

^<<v13-7-29,29>>^ Ao longo da divisa de Manassés, ficavam as cidades de Bete-Seã, Taanaque, Megido e Dor, com seus povoados. Os descendentes de José, filho de Israel, habitavam nessas cidades.

[[v13-7-30]]

^<<v13-7-30,30>>^ Os filhos de Aser foram: Imna, Isvá, Isvi e Berias. A irmã deles se chamava Sera.

[[v13-7-31]]

^<<v13-7-31,31>>^ Os filhos de Berias foram: Héber e Malquiel, pai de Birzavite.

[[v13-7-32]]

^<<v13-7-32,32>>^ Os filhos de Héber foram: Jaflete, Somer e Hotão. A irmã deles se chamava Suá.

[[v13-7-33]]

^<<v13-7-33,33>>^ Os filhos de Jaflete foram: Pasaque, Bimal e Asvate.

[[v13-7-34]]

^<<v13-7-34,34>>^ Os filhos de Somer foram: Aí, Roga, Jeubá e Arã.

[[v13-7-35]]

^<<v13-7-35,35>>^ Os filhos de Helém, irmão de Somer, foram: Zofa, Imna, Seles e Amal.

[[v13-7-36]]

^<<v13-7-36,36>>^ Os filhos de Zofa foram: Suá, Harnefer, Sual, Beri, Inra,

[[v13-7-37]]

^<<v13-7-37,37>>^ Bezer, Hode, Samá, Silsa, Itrã e Beera.

[[v13-7-38]]

^<<v13-7-38,38>>^ Os filhos de Jéter foram: Jefoné, Pispa e Ara.

[[v13-7-39]]

^<<v13-7-39,39>>^ Os filhos de Ula foram: Ará, Haniel e Rizia.

[[v13-7-40]]

^<<v13-7-40,40>>^ Cada um desses descendentes de Aser foi chefe de um clã. Eram todos homens escolhidos, guerreiros valentes e líderes de destaque. O total de homens disponíveis para o serviço militar era de 26.000, conforme listado nos registros genealógicos.

'''

xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[&#60; Capítulo Anterior] | <<v13-7-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-008.adoc#v13-8-0[Próximo Capítulo &#62;]