include::./index.adoc[]

[[v13-17-0]]
=== 1 Crônicas, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v13-17-1]]

^<<v13-17-1,1>>^ Quando Davi já havia se estabelecido em seu palácio, mandou chamar o profeta Natã. Disse: "Veja, moro num palácio, uma casa de cedro, enquanto a arca da aliança do SENHOR está lá fora, numa simples tenda".

[[v13-17-2]]

^<<v13-17-2,2>>^ Natã respondeu a Davi: "Faça o que tem em mente, pois Deus está com o rei".

[[v13-17-3]]

^<<v13-17-3,3>>^ Naquela mesma noite, porém, Deus disse a Natã:

[[v13-17-4]]

^<<v13-17-4,4>>^ "Vá e diga a meu servo Davi que assim diz o SENHOR: ‘Não será você que construirá uma casa para eu habitar.

[[v13-17-5]]

^<<v13-17-5,5>>^ Desde o dia em que tirei os israelitas do Egito até hoje, nunca morei numa casa. Sempre acompanhei o povo de um lugar para o outro numa tenda, num tabernáculo.

[[v13-17-6]]

^<<v13-17-6,6>>^ E, no entanto, onde quer que tenha ido com os israelitas, nunca me queixei aos líderes de Israel, aos pastores de meu povo. Nunca lhes perguntei: Por que não construíram para mim um palácio, uma casa de cedro?’.

[[v13-17-7]]

^<<v13-17-7,7>>^ "Agora vá e diga a meu servo Davi que assim diz o SENHOR dos Exércitos: ‘Eu o tirei das pastagens onde você cuidava das ovelhas e o escolhi para ser o líder de meu povo, Israel.

[[v13-17-8]]

^<<v13-17-8,8>>^ Estive com você por onde andou e destruí todos os seus inimigos diante de seus olhos. Agora, tornarei seu nome tão conhecido quanto o dos homens mais importantes da terra!

[[v13-17-9]]

^<<v13-17-9,9>>^ Providenciarei uma terra para meu povo, Israel, e os plantarei num lugar seguro, onde jamais serão perturbados. Nações perversas não os oprimirão como fizeram no passado,

[[v13-17-10]]

^<<v13-17-10,10>>^ desde o tempo em que nomeei juízes para governar meu povo, Israel. Também derrotarei todos os seus inimigos. "‘Além disso, eu declaro que o SENHOR fará uma casa para você, uma dinastia real!

[[v13-17-11]]

^<<v13-17-11,11>>^ Pois, quando você morrer e se reunir a seus antepassados, escolherei um de seus filhos, de sua própria descendência, e estabelecerei seu reino.

[[v13-17-12]]

^<<v13-17-12,12>>^ Ele é que construirá uma casa para mim, e estabelecerei seu trono para sempre.

[[v13-17-13]]

^<<v13-17-13,13>>^ Eu serei seu pai, e ele será meu filho. Jamais retirarei dele meu favor, como o retirei daquele que governou antes de você.

[[v13-17-14]]

^<<v13-17-14,14>>^ Eu o confirmarei para sempre como rei sobre minha casa e sobre meu reino, e seu trono será estabelecido para sempre’".

[[v13-17-15]]

^<<v13-17-15,15>>^ Natã voltou até Davi e contou ao rei tudo que o SENHOR lhe tinha revelado.

[[v13-17-16]]

^<<v13-17-16,16>>^ Então o rei Davi entrou no santuário, pôs-se diante do SENHOR e orou: "Quem sou eu, ó SENHOR Deus, e o que é minha família, para que me trouxesses até aqui?

[[v13-17-17]]

^<<v13-17-17,17>>^ E agora, ó Deus, como se isso não bastasse, dizes que dará a teu servo uma dinastia duradoura! Como alguém pode ser tão privilegiado, ó SENHOR Deus?

[[v13-17-18]]

^<<v13-17-18,18>>^ "Que mais posso dizer sobre o modo como me honraste? Tu sabes como teu servo é de fato.

[[v13-17-19]]

^<<v13-17-19,19>>^ Por causa de teu servo, ó SENHOR, e de acordo com tua vontade, fizeste todas estas grandes coisas e as tornaste conhecidas.

[[v13-17-20]]

^<<v13-17-20,20>>^ "Ó SENHOR, não há ninguém igual a ti! Jamais ouvimos falar de outro Deus como tu!

[[v13-17-21]]

^<<v13-17-21,21>>^ Que outra nação na terra é como teu povo, Israel? Que outra nação, ó Deus, resgataste da escravidão para ser teu povo? Engrandeceste teu nome ao livrar teu povo do Egito. Realizaste milagres impressionantes e removeste as nações do caminho de teu povo.

[[v13-17-22]]

^<<v13-17-22,22>>^ Escolheste Israel para ser teu próprio povo para sempre, e tu, ó SENHOR, te tornaste seu Deus.

[[v13-17-23]]

^<<v13-17-23,23>>^ "E agora, ó SENHOR, sou teu servo; faze o que prometeste a meu respeito e de minha família. Confirma-o como uma promessa que durará para sempre.

[[v13-17-24]]

^<<v13-17-24,24>>^ Que o teu nome seja estabelecido e honrado para sempre, a fim de que todos digam: ‘O SENHOR dos Exércitos, o Deus de Israel, é Deus para Israel!’. E que a dinastia de teu servo Davi permaneça diante de ti para sempre.

[[v13-17-25]]

^<<v13-17-25,25>>^ "Ó Deus meu, tive a coragem de fazer-te esta oração porque revelaste a teu servo que farás uma casa para mim, uma dinastia real!

[[v13-17-26]]

^<<v13-17-26,26>>^ Pois tu és Deus, ó SENHOR, e prometeste estas coisas boas a teu servo.

[[v13-17-27]]

^<<v13-17-27,27>>^ E agora, que seja do teu agrado abençoar a casa de teu servo, para que ela permaneça para sempre diante de ti. Pois, quando concedes uma bênção, ó SENHOR, é uma bênção para sempre!".

'''

xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[&#60; Capítulo Anterior] | <<v13-17-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[Próximo Capítulo &#62;]