include::./index.adoc[]

[[v13-9-0]]
=== 1 Crônicas, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v13-9-1]]

^<<v13-9-1,1>>^ Todo o Israel foi listado nos registros genealógicos do Livro dos Reis de Israel . O povo de Judá foi exilado na Babilônia por causa de sua infidelidade.

[[v13-9-2]]

^<<v13-9-2,2>>^ Os primeiros exilados a regressar a suas propriedades em suas respectivas cidades foram os sacerdotes, os levitas, os servidores do templo, além de outros israelitas.

[[v13-9-3]]

^<<v13-9-3,3>>^ Alguns membros das tribos de Judá, Benjamim, Efraim e Manassés se estabeleceram em Jerusalém.

[[v13-9-4]]

^<<v13-9-4,4>>^ Uma das famílias a voltar foi a de Utai, filho de Amiúde, filho de Onri, filho de Inri, filho de Bani, descendente de Perez, filho de Judá.

[[v13-9-5]]

^<<v13-9-5,5>>^ Do clã dos silonitas, alguns dos que voltaram foram: Asaías, o mais velho, e seus filhos.

[[v13-9-6]]

^<<v13-9-6,6>>^ Do clã dos zeraítas, alguns dos que voltaram foram: Jeuel e seus parentes. Ao todo, voltaram 690 famílias da tribo de Judá.

[[v13-9-7]]

^<<v13-9-7,7>>^ Da tribo de Benjamim, alguns dos que voltaram foram: Salu, filho de Mesulão, filho de Hodavias, filho de Hassenua;

[[v13-9-8]]

^<<v13-9-8,8>>^ Ibneias, filho de Jeroão; Elá, filho de Uzi, filho de Micri; e Mesulão, filho de Sefatias, filho de Reuel, filho de Ibnias.

[[v13-9-9]]

^<<v13-9-9,9>>^ Todos esses homens foram chefes de clãs e estão listados nos registros genealógicos. Ao todo, voltaram 956 famílias da tribo de Benjamim.

[[v13-9-10]]

^<<v13-9-10,10>>^ Dos sacerdotes, alguns dos que voltaram foram: Jedaías, Jeoiaribe, Jaquim,

[[v13-9-11]]

^<<v13-9-11,11>>^ Azarias, filho de Hilquias, filho de Mesulão, filho de Zadoque, filho de Meraiote, filho de Aitube. Azarias era o principal encarregado da casa de Deus.

[[v13-9-12]]

^<<v13-9-12,12>>^ Outros sacerdotes que voltaram foram: Adaías, filho de Jeroão, filho de Pasur, filho de Malquias; e Masai, filho de Adiel, filho de Jazera, filho de Mesulão, filho de Mesilemite, filho de Imer.

[[v13-9-13]]

^<<v13-9-13,13>>^ Ao todo, voltaram 1.760 sacerdotes. Foram chefes de clãs e homens muito capazes. Eram responsáveis por servir na casa de Deus.

[[v13-9-14]]

^<<v13-9-14,14>>^ Dos levitas, os que voltaram foram: Semaías, filho de Hassube, filho de Azricão, filho de Hasabias, descendente de Merari;

[[v13-9-15]]

^<<v13-9-15,15>>^ Baquebacar; Heres; Galal; Matanias, filho de Mica, filho de Zicri, filho de Asafe;

[[v13-9-16]]

^<<v13-9-16,16>>^ Obadias, filho de Semaías, filho de Galal, filho de Jedutum; e Berequias, filho de Asa, filho de Elcana, que morava na região de Netofate.

[[v13-9-17]]

^<<v13-9-17,17>>^ Dos guardas das portas, os que voltaram foram: Salum, Acube, Talmom, Aimã e seus parentes. Salum era o chefe dos guardas.

[[v13-9-18]]

^<<v13-9-18,18>>^ Antes dessa época, eram responsáveis pela Porta do Rei, do lado leste. Eram guardas das portas dos acampamentos dos levitas.

[[v13-9-19]]

^<<v13-9-19,19>>^ Salum era filho de Coré, descendente de Abiasafe, do clã de Corá. Ele e seus parentes, os coraítas, eram responsáveis por guardar a entrada do santuário, como seus antepassados haviam guardado a entrada do tabernáculo.

[[v13-9-20]]

^<<v13-9-20,20>>^ Naquele tempo, Fineias, filho de Eleazar, era o encarregado dos guardas das portas, e o SENHOR estava com ele.

[[v13-9-21]]

^<<v13-9-21,21>>^ Mais tarde, Zacarias, filho de Meselemias, foi o responsável por guardar a entrada.

[[v13-9-22]]

^<<v13-9-22,22>>^ Ao todo, havia 212 guardas das portas naquele tempo, e foram listados nos registros genealógicos de seus povoados. Os antepassados deles haviam sido nomeados por Davi e por Samuel, o vidente, porque eram homens de confiança.

[[v13-9-23]]

^<<v13-9-23,23>>^ Esses guardas das portas e seus descendentes, conforme suas divisões, eram responsáveis por guardar a entrada da casa do SENHOR quando ela era uma tenda.

[[v13-9-24]]

^<<v13-9-24,24>>^ Os guardas das portas ficavam nos quatro lados: leste, oeste, norte e sul.

[[v13-9-25]]

^<<v13-9-25,25>>^ Seus parentes nos povoados vinham de tempo em tempo dividir essa responsabilidade com eles por períodos de sete dias.

[[v13-9-26]]

^<<v13-9-26,26>>^ Os quatro principais guardas das portas, todos levitas, eram oficiais de confiança, pois eram responsáveis pelas salas e pelos tesouros da casa de Deus.

[[v13-9-27]]

^<<v13-9-27,27>>^ Passavam a noite ao redor da casa de Deus, pois era seu dever guardá-la e abrir suas portas todas as manhãs.

[[v13-9-28]]

^<<v13-9-28,28>>^ Alguns dos guardas das portas foram nomeados para cuidar dos diversos objetos usados no culto. Conferiam tudo que era retirado e devolvido, para que nada se perdesse.

[[v13-9-29]]

^<<v13-9-29,29>>^ Outros eram responsáveis pela mobília, pelos utensílios do santuário e pelos suprimentos, como farinha da melhor qualidade, vinho, azeite, incenso e especiarias.

[[v13-9-30]]

^<<v13-9-30,30>>^ Eram os sacerdotes, porém, que misturavam as especiarias.

[[v13-9-31]]

^<<v13-9-31,31>>^ Matitias, levita e filho mais velho de Salum, o coraíta, era encarregado de assar os pães para as ofertas.

[[v13-9-32]]

^<<v13-9-32,32>>^ E alguns membros do clã de Coate eram encarregados de preparar os pães colocados sobre a mesa todos os sábados.

[[v13-9-33]]

^<<v13-9-33,33>>^ Os músicos, todos chefes de famílias levitas, moravam no templo. Eram isentos de outras responsabilidades, pois realizavam seu serviço dia e noite.

[[v13-9-34]]

^<<v13-9-34,34>>^ Todos esses homens moravam em Jerusalém. Eram chefes de famílias levitas, listados como líderes nos registros genealógicos.

[[v13-9-35]]

^<<v13-9-35,35>>^ Jeiel, pai de Gibeom, morava na cidade de Gibeom. Sua esposa se chamava Maaca,

[[v13-9-36]]

^<<v13-9-36,36>>^ e seu filho mais velho, Abdom. Os outros filhos de Jeiel foram: Zur, Quis, Baal, Ner, Nadabe,

[[v13-9-37]]

^<<v13-9-37,37>>^ Gedor, Aiô, Zacarias e Miclote.

[[v13-9-38]]

^<<v13-9-38,38>>^ Miclote gerou Simeão. Todos moravam com suas famílias, próximos uns dos outros, em Jerusalém.

[[v13-9-39]]

^<<v13-9-39,39>>^ Ner gerou Quis. Quis gerou Saul. Os filhos de Saul foram: Jônatas, Malquisua, Abinadabe e Isbosete.

[[v13-9-40]]

^<<v13-9-40,40>>^ Jônatas gerou Mefibosete. Mefibosete gerou Mica.

[[v13-9-41]]

^<<v13-9-41,41>>^ Os filhos de Mica foram: Pitom, Meleque, Tareia e Acaz.

[[v13-9-42]]

^<<v13-9-42,42>>^ Acaz gerou Jadá. Os filhos de Jadá foram: Alemete, Azmavete e Zinri. Zinri gerou Moza.

[[v13-9-43]]

^<<v13-9-43,43>>^ Moza gerou Bineá. O filho de Bineá foi Refaías. O filho de Refaías foi Eleasá. O filho de Eleasá foi Azel.

[[v13-9-44]]

^<<v13-9-44,44>>^ Estes foram os seis filhos de Azel: Azricão, Bocru, Ismael, Searias, Obadias e Hanã. Todos esses foram filhos de Azel.

'''

xref:013-1-cronicas/013-1-cronicas-008.adoc#v13-8-0[&#60; Capítulo Anterior] | <<v13-9-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[Próximo Capítulo &#62;]