include::./index.adoc[]

[[v13-21-0]]
=== 1 Crônicas, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v13-21-1]]

^<<v13-21-1,1>>^ Satanás se levantou contra Israel e incitou Davi a fazer um censo.

[[v13-21-2]]

^<<v13-21-2,2>>^ Davi disse a Joabe e aos comandantes do exército: "Façam uma contagem de todo o Israel, desde Berseba, ao sul, até Dã, ao norte, e tragam-me um relatório para que eu saiba o número exato do povo".

[[v13-21-3]]

^<<v13-21-3,3>>^ Joabe, porém, respondeu: "Que o SENHOR torne a população cem vezes mais numerosa do que é hoje! Mas por que meu senhor, o rei, deseja fazer essa contagem? Eles não são todos seus servos? Por que levar Israel a pecar?".

[[v13-21-4]]

^<<v13-21-4,4>>^ Apesar da objeção de Joabe, o rei insistiu que fizessem o censo. Então Joabe saiu para contar o povo de Israel. Depois, voltou para Jerusalém

[[v13-21-5]]

^<<v13-21-5,5>>^ e informou a Davi o número de pessoas. Havia em Israel 1.100.000 homens aptos para irem à guerra que sabiam manejar a espada e, em Judá, havia 470.000.

[[v13-21-6]]

^<<v13-21-6,6>>^ Mas Joabe não incluiu no censo as tribos de Levi e Benjamim, pois achou absurda a ordem do rei.

[[v13-21-7]]

^<<v13-21-7,7>>^ Deus se desagradou muito do censo e castigou Israel por isso.

[[v13-21-8]]

^<<v13-21-8,8>>^ Então Davi disse a Deus: "Pequei grandemente ao fazer essa contagem. Perdoe meu pecado, pois cometi uma insensatez".

[[v13-21-9]]

^<<v13-21-9,9>>^ O SENHOR falou a Gade, o vidente de Davi. Esta foi a mensagem:

[[v13-21-10]]

^<<v13-21-10,10>>^ "Vá e diga a Davi que assim diz o SENHOR: ‘Darei a você três opções. Escolha um destes castigos, e eu o aplicarei a você’".

[[v13-21-11]]

^<<v13-21-11,11>>^ Gade foi a Davi e disse: "Estas são as três opções que o SENHOR lhe deu:

[[v13-21-12]]

^<<v13-21-12,12>>^ três anos de fome, três meses de destruição pela espada de seus inimigos, ou três dias de praga intensa, durante os quais o anjo do SENHOR trará devastação sobre toda a terra de Israel. Decida o que devo responder àquele que me enviou".

[[v13-21-13]]

^<<v13-21-13,13>>^ "Não tenho para onde correr nesta situação!", respondeu Davi a Gade. "Mas é melhor cair nas mãos do SENHOR, pois sua misericórdia é grande. Que eu não caia nas mãos de homens."

[[v13-21-14]]

^<<v13-21-14,14>>^ Então o SENHOR enviou uma praga sobre Israel, e setenta mil pessoas morreram.

[[v13-21-15]]

^<<v13-21-15,15>>^ E Deus enviou um anjo para destruir Jerusalém. Mas, quando o anjo estava prestes a fazê-lo, o SENHOR teve compaixão e disse ao anjo da morte: "Pare! Já basta!". Naquele momento, o anjo do SENHOR estava perto da eira de Araúna, o jebuseu.

[[v13-21-16]]

^<<v13-21-16,16>>^ Davi olhou para cima e viu o anjo do SENHOR entre o céu e a terra, com a espada desembainhada na mão, estendida sobre Jerusalém. Então Davi e as autoridades de Israel se vestiram de pano de saco e se prostraram com o rosto no chão.

[[v13-21-17]]

^<<v13-21-17,17>>^ Davi disse a Deus: "Fui eu que ordenei o censo! Eu pequei e fiz o que era mau! Mas o povo é inocente, como ovelhas. O que fizeram? Ó SENHOR, meu Deus, que tua ira caia sobre mim e minha família, mas não castigue teu povo!".

[[v13-21-18]]

^<<v13-21-18,18>>^ Então o anjo do SENHOR disse a Gade que mandasse Davi construir um altar ao SENHOR na eira de Araúna, o jebuseu.

[[v13-21-19]]

^<<v13-21-19,19>>^ Davi subiu para lá a fim de cumprir a ordem que o SENHOR deu por meio de Gade.

[[v13-21-20]]

^<<v13-21-20,20>>^ Araúna debulhava o trigo quando virou-se e viu o anjo. Seus quatro filhos, que estavam com ele, fugiram e se esconderam.

[[v13-21-21]]

^<<v13-21-21,21>>^ Quando Araúna viu que o rei se aproximava, saiu da eira e curvou-se diante de Davi com o rosto no chão.

[[v13-21-22]]

^<<v13-21-22,22>>^ Davi disse a Araúna: "Quero comprar de você esta eira pelo preço justo. Construirei nela um altar para o SENHOR, a fim de que ele faça cessar a praga".

[[v13-21-23]]

^<<v13-21-23,23>>^ "Pode ficar com a eira, meu senhor, o rei", disse Araúna. "Use-a como lhe parecer melhor. Eu lhe darei os bois para os holocaustos, as tábuas de trilhar como lenha para o fogo do altar e o trigo como oferta de cereais. Eu lhe darei tudo, ó rei."

[[v13-21-24]]

^<<v13-21-24,24>>^ O rei Davi, porém, respondeu a Araúna: "Não! Faço questão de comprá-la pelo preço justo. Não tomarei o que é seu para oferecer ao SENHOR. Não apresentarei holocaustos que nada me custaram".

[[v13-21-25]]

^<<v13-21-25,25>>^ Então Davi pagou a Araúna seiscentas peças de ouro pela eira.

[[v13-21-26]]

^<<v13-21-26,26>>^ Davi construiu ali um altar ao SENHOR e ofereceu holocaustos e ofertas de paz. E, quando Davi orou, o SENHOR respondeu com fogo do céu para queimar a oferta sobre o altar.

[[v13-21-27]]

^<<v13-21-27,27>>^ Então o SENHOR deu ordem para que o anjo pusesse a espada de volta na bainha.

[[v13-21-28]]

^<<v13-21-28,28>>^ Quando Davi percebeu que o SENHOR havia respondido à sua oração, ofereceu sacrifícios ali na eira de Araúna, o jebuseu.

[[v13-21-29]]

^<<v13-21-29,29>>^ Naquela época, o tabernáculo do SENHOR, que Moisés havia feito no deserto, e o altar de holocaustos estavam no lugar de adoração em Gibeom.

[[v13-21-30]]

^<<v13-21-30,30>>^ Mas Davi não podia ir até lá para consultar Deus, pois tinha pavor da espada do anjo do SENHOR.

'''

xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[Próximo Capítulo &#62;]