include::./index.adoc[]

[[v13-27-0]]
=== 1 Crônicas, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v13-27-1]]

^<<v13-27-1,1>>^ Esta é a lista dos israelitas, chefes de família, generais e capitães que serviam o rei na supervisão das divisões do exército de serviço a cada mês do ano. Cada divisão tinha 24 mil homens e servia durante um mês.

[[v13-27-2]]

^<<v13-27-2,2>>^ Jasobeão, filho de Zabdiel, era comandante da primeira divisão de 24 mil homens, de serviço durante o primeiro mês.

[[v13-27-3]]

^<<v13-27-3,3>>^ Era descendente de Perez e chefe de todos os oficiais do exército para o primeiro mês.

[[v13-27-4]]

^<<v13-27-4,4>>^ Dodai, descendente de Aoí, era comandante da segunda divisão de 24 mil homens, de serviço durante o segundo mês. Miclote era o chefe da divisão.

[[v13-27-5]]

^<<v13-27-5,5>>^ Benaia, filho do sacerdote Joiada, era comandante da terceira divisão de 24 mil homens, de serviço durante o terceiro mês.

[[v13-27-6]]

^<<v13-27-6,6>>^ Esse Benaia comandou o grupo militar de elite de Davi, conhecido como os Trinta. Seu filho Amizabade era o chefe da divisão.

[[v13-27-7]]

^<<v13-27-7,7>>^ Asael, irmão de Joabe, era comandante da quarta divisão de 24 mil homens, de serviço durante o quarto mês. Asael foi sucedido por seu filho Zebadias.

[[v13-27-8]]

^<<v13-27-8,8>>^ Sama, o izraíta, era comandante da quinta divisão de 24 mil homens, de serviço durante o quinto mês.

[[v13-27-9]]

^<<v13-27-9,9>>^ Ira, filho de Iques, de Tecoa, era comandante da sexta divisão de 24 mil homens, de serviço durante o sexto mês.

[[v13-27-10]]

^<<v13-27-10,10>>^ Helez, de Pelom, descendente de Efraim, era comandante da sétima divisão de 24 mil homens, de serviço durante o sétimo mês.

[[v13-27-11]]

^<<v13-27-11,11>>^ Sibecai, de Husate, descendente de Zera, era comandante da oitava divisão de 24 mil homens, de serviço durante o oitavo mês.

[[v13-27-12]]

^<<v13-27-12,12>>^ Abiezer, de Anatote, da tribo de Benjamim, era comandante da nona divisão de 24 mil homens, de serviço durante o nono mês.

[[v13-27-13]]

^<<v13-27-13,13>>^ Maarai, de Netofate, descendente de Zera, era comandante da décima divisão de 24 mil homens, de serviço durante o décimo mês.

[[v13-27-14]]

^<<v13-27-14,14>>^ Benaia, de Piratom, em Efraim, era comandante da décima primeira divisão de 24 mil homens, de serviço durante o décimo primeiro mês.

[[v13-27-15]]

^<<v13-27-15,15>>^ Helede, de Netofate, descendente de Otniel, era comandante da décima segunda divisão de 24 mil homens, de serviço durante o décimo segundo mês.

[[v13-27-16]]

^<<v13-27-16,16>>^ Estas foram as tribos de Israel e seus líderes: da tribo de Rúben: Eliézer, filho de Zicri; da tribo de Simeão: Sefatias, filho de Maaca;

[[v13-27-17]]

^<<v13-27-17,17>>^ da tribo de Levi: Hasabias, filho de Quemuel; da tribo de Arão: o sacerdote, Zadoque;

[[v13-27-18]]

^<<v13-27-18,18>>^ da tribo de Judá: Eliú, irmão de Davi; da tribo de Issacar: Onri, filho de Micael;

[[v13-27-19]]

^<<v13-27-19,19>>^ da tribo de Zebulom: Ismaías, filho de Obadias; da tribo de Naftali: Jeremote, filho de Azriel;

[[v13-27-20]]

^<<v13-27-20,20>>^ da tribo de Efraim: Oseias, filho de Azazias; da tribo de Manassés, a oeste: Joel, filho de Pedaías;

[[v13-27-21]]

^<<v13-27-21,21>>^ da tribo de Manassés, em Gileade, a leste: Ido, filho de Zacarias; da tribo de Benjamim: Jaasiel, filho de Abner;

[[v13-27-22]]

^<<v13-27-22,22>>^ da tribo de Dã: Azareel, filho de Jeroão. Esses foram os líderes das tribos de Israel.

[[v13-27-23]]

^<<v13-27-23,23>>^ Quando Davi fez o censo, não contou os que tinham menos de 20 anos, pois o SENHOR havia prometido que os israelitas seriam numerosos como as estrelas no céu.

[[v13-27-24]]

^<<v13-27-24,24>>^ Joabe, filho de Zeruia, começou o censo, mas nunca o terminou, porque a ira de Deus caiu sobre Israel. O número total nunca foi anotado nos registros oficiais do rei Davi.

[[v13-27-25]]

^<<v13-27-25,25>>^ Azmavete, filho de Adiel, era encarregado dos depósitos do palácio. Jônatas, filho de Uzias, era encarregado dos depósitos nos campos, nas cidades, nos povoados e nas fortalezas.

[[v13-27-26]]

^<<v13-27-26,26>>^ Ezri, filho de Quelube, era encarregado dos trabalhadores nos campos, que cultivavam as terras.

[[v13-27-27]]

^<<v13-27-27,27>>^ Simei, de Ramá, era encarregado dos vinhedos. Zabdi, de Sifá, era encarregado das uvas e do fornecimento de vinho.

[[v13-27-28]]

^<<v13-27-28,28>>^ Baal-Hanã, de Gederá, era encarregado das plantações de oliveiras e figueiras-bravas do rei nas colinas de Judá. Joás era encarregado dos depósitos de azeite.

[[v13-27-29]]

^<<v13-27-29,29>>^ Sitrai, de Sarom, era encarregado do gado na planície de Sarom. Safate, filho de Adlai, era encarregado do gado nos vales.

[[v13-27-30]]

^<<v13-27-30,30>>^ Obil, o ismaelita, era encarregado dos camelos. Jedias, de Meronote, era encarregado dos jumentos.

[[v13-27-31]]

^<<v13-27-31,31>>^ Jaziz, o hagareno, era encarregado das ovelhas. Todos esses oficiais administravam as propriedades do rei Davi.

[[v13-27-32]]

^<<v13-27-32,32>>^ Jônatas, tio de Davi, era conselheiro do rei, homem sábio e também escriba. Jeiel, filho de Hacmoni, era responsável por ensinar os filhos do rei.

[[v13-27-33]]

^<<v13-27-33,33>>^ Aitofel era conselheiro do rei. Husai, o arquita, era amigo do rei.

[[v13-27-34]]

^<<v13-27-34,34>>^ Aitofel foi sucedido por Joiada, filho de Benaia, e por Abiatar. Joabe era comandante do exército do rei.

'''

xref:013-1-cronicas/013-1-cronicas-026.adoc#v13-26-0[&#60; Capítulo Anterior] | <<v13-27-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[Próximo Capítulo &#62;]