include::./index.adoc[]

[[v13-28-0]]
=== 1 Crônicas, 28
// nvt ?, NVT - Nova Versão Transformadora

[[v13-28-1]]

^<<v13-28-1,1>>^ Davi convocou todos os oficiais de Israel para irem a Jerusalém: os líderes das tribos, os comandantes das divisões do exército, os generais e os capitães, os administradores das propriedades e dos rebanhos do rei, os oficiais do palácio, os guerreiros valentes, e todos os outros soldados do reino.

[[v13-28-2]]

^<<v13-28-2,2>>^ Davi se pôs em pé e disse: "Meus irmãos e meu povo! Era meu desejo construir um templo onde a arca da aliança do SENHOR, o lugar de descanso dos pés de nosso Deus, repousasse para sempre. Fiz os preparativos necessários para construí-lo,

[[v13-28-3]]

^<<v13-28-3,3>>^ mas Deus me disse: ‘Você não construirá um templo em honra ao meu nome, pois é homem de guerra e derramou muito sangue’.

[[v13-28-4]]

^<<v13-28-4,4>>^ "Contudo, o SENHOR, o Deus de Israel, me escolheu dentre toda a família de meu pai para ser rei em Israel, para sempre. Escolheu a tribo de Judá para governar e, dentre as famílias de Judá, escolheu a de meu pai. Dentre os filhos de meu pai, agradou-se de me fazer rei sobre todo o Israel.

[[v13-28-5]]

^<<v13-28-5,5>>^ E, dentre os muitos filhos que o SENHOR me deu, escolheu Salomão para ser meu sucessor no trono de Israel e para governar o reino do SENHOR.

[[v13-28-6]]

^<<v13-28-6,6>>^ Ele me disse: ‘Seu filho Salomão construirá meu templo e meus pátios, pois eu o escolhi para ser meu filho, e eu serei seu pai.

[[v13-28-7]]

^<<v13-28-7,7>>^ E, se ele continuar a obedecer a meus mandamentos e estatutos, como obedece hoje, farei seu reino durar para sempre’.

[[v13-28-8]]

^<<v13-28-8,8>>^ "Agora, portanto, com Deus como nossa testemunha, e diante de todo o Israel, a comunidade do SENHOR, eu lhes digo: tenham o cuidado de obedecer a todos os mandamentos do SENHOR, seu Deus, para que continuem a possuir esta boa terra e a deixem para seus filhos como herança permanente.

[[v13-28-9]]

^<<v13-28-9,9>>^ "E você, meu filho Salomão, aprenda a conhecer o Deus de seus antepassados. Sirva-o de todo o coração e com a alma alegre. Pois o SENHOR vê todos os corações e conhece todos os planos e pensamentos. Se você o buscar, o encontrará. Mas, se você o abandonar, ele o rejeitará para sempre.

[[v13-28-10]]

^<<v13-28-10,10>>^ Portanto, leve isto a sério. O SENHOR o escolheu para construir um templo que sirva de santuário. Seja forte e faça o trabalho".

[[v13-28-11]]

^<<v13-28-11,11>>^ Então Davi entregou a seu filho Salomão as plantas do templo e de tudo que ficava ao redor, incluindo a sala de entrada, os depósitos, as salas dos andares superiores, as salas internas e o lugar de expiação.

[[v13-28-12]]

^<<v13-28-12,12>>^ Davi também entregou a Salomão as plantas de tudo que havia planejado para os pátios do templo do SENHOR, das salas externas, dos tesouros e dos depósitos para as ofertas dedicadas ao SENHOR.

[[v13-28-13]]

^<<v13-28-13,13>>^ Deu, ainda, instruções a respeito das divisões dos sacerdotes e dos levitas, além das responsabilidades no templo do SENHOR e das especificações para os objetos usados no serviço do templo.

[[v13-28-14]]

^<<v13-28-14,14>>^ Davi deu instruções a respeito de quanto ouro e quanta prata deviam ser usados para confeccionar esses objetos para o serviço.

[[v13-28-15]]

^<<v13-28-15,15>>^ Informou a quantidade de ouro necessária para os candelabros e as lâmpadas de ouro, e a quantidade de prata necessária para os candelabros e as lâmpadas de prata, de acordo com o uso de cada um.

[[v13-28-16]]

^<<v13-28-16,16>>^ Especificou a quantidade de ouro para a mesa sobre a qual seriam colocados os pães da presença, e a quantidade de prata para as outras mesas.

[[v13-28-17]]

^<<v13-28-17,17>>^ Davi também especificou a quantidade de ouro puro para os garfos, as bacias, os jarros e as tigelas, bem como a quantidade de prata para as tigelas.

[[v13-28-18]]

^<<v13-28-18,18>>^ Especificou, ainda, a quantidade de ouro refinado para o altar de incenso. E, por fim, entregou-lhe o projeto para o trono do SENHOR, os querubins de ouro cujas asas se estendiam sobre a arca da aliança do SENHOR.

[[v13-28-19]]

^<<v13-28-19,19>>^ Davi disse a Salomão: "Todos os detalhes dessas plantas me foram escritos sob a direção do SENHOR".

[[v13-28-20]]

^<<v13-28-20,20>>^ E continuou: "Seja forte e corajoso e faça o trabalho. Não tenha medo nem desanime, pois o SENHOR Deus, meu Deus, está com você. Ele não o deixará nem o abandonará durante toda a construção do templo do SENHOR.

[[v13-28-21]]

^<<v13-28-21,21>>^ As divisões dos sacerdotes e dos levitas servirão no templo do SENHOR. Outros, com todo tipo de habilidade, se oferecerão para ajudar, e os oficiais e todo o povo estarão às suas ordens".

'''

xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[&#60; Capítulo Anterior] | <<v13-28-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-029.adoc#v13-29-0[Próximo Capítulo &#62;]