include::./index.adoc[]

[[v13-5-0]]
=== 1 Crônicas, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v13-5-1]]

^<<v13-5-1,1>>^ O filho mais velho de Israel era Rúben, mas ele teve relações com uma das concubinas de seu pai e o desonrou. Por isso seus direitos de filho mais velho foram dados aos filhos de seu irmão José. Desse modo, Rúben não aparece nos registros genealógicos como filho mais velho.

[[v13-5-2]]

^<<v13-5-2,2>>^ Os descendentes de Judá se tornaram a tribo mais poderosa e dela veio um governante para a nação, mas os direitos de filho mais velho pertenciam a José.

[[v13-5-3]]

^<<v13-5-3,3>>^ Os filhos de Rúben, filho mais velho de Israel, foram: Enoque, Palu, Hezrom e Carmi.

[[v13-5-4]]

^<<v13-5-4,4>>^ Os descendentes de Joel foram: Semaías, Gogue, Simei,

[[v13-5-5]]

^<<v13-5-5,5>>^ Mica, Reaías, Baal

[[v13-5-6]]

^<<v13-5-6,6>>^ e Beera. Beera era o chefe dos rubenitas quando foram levados ao cativeiro por Tiglate-Pileser, rei da Assíria.

[[v13-5-7]]

^<<v13-5-7,7>>^ Os parentes de Beera, listados em seus registros genealógicos de acordo com seus clãs, foram: Jeiel, o chefe, Zacarias

[[v13-5-8]]

^<<v13-5-8,8>>^ e Belá, filho de Azaz, filho de Sema, filho de Joel. Os rubenitas habitavam na região que se estende de Aroer até Nebo e Baal-Meom.

[[v13-5-9]]

^<<v13-5-9,9>>^ Uma vez que tinham tantos rebanhos na terra de Gileade, espalharam-se para o leste, em direção ao limite do deserto que se estende para o rio Eufrates.

[[v13-5-10]]

^<<v13-5-10,10>>^ Durante o reinado de Saul, os rubenitas guerrearam contra os hagarenos e os derrotaram. Então passaram a viver nos acampamentos deles em toda a região a leste de Gileade.

[[v13-5-11]]

^<<v13-5-11,11>>^ Ao lado dos rubenitas, ficaram os descendentes de Gade, que habitavam na terra de Basã até Salcá.

[[v13-5-12]]

^<<v13-5-12,12>>^ Joel foi o chefe na terra de Basã, e Safã, o segundo no poder, seguido de Janai e Safate.

[[v13-5-13]]

^<<v13-5-13,13>>^ Seus parentes, chefes de outros sete clãs, foram: Micael, Mesulão, Seba, Jorai, Jacã, Zia e Héber.

[[v13-5-14]]

^<<v13-5-14,14>>^ Todos esses foram descendentes de Abiail, filho de Huri, filho de Jaroa, filho de Gileade, filho de Micael, filho de Jesisai, filho de Jado, filho de Buz.

[[v13-5-15]]

^<<v13-5-15,15>>^ Aí, filho de Abdiel, filho de Guni, foi o chefe de seus clãs.

[[v13-5-16]]

^<<v13-5-16,16>>^ Os gaditas habitaram na terra de Gileade, em Basã e em seus povoados, e em toda a região de pastagens de Sarom.

[[v13-5-17]]

^<<v13-5-17,17>>^ Todos foram listados nos registros genealógicos no tempo de Jotão, rei de Judá, e de Jeroboão, rei de Israel.

[[v13-5-18]]

^<<v13-5-18,18>>^ Havia 44.760 homens aptos para a guerra nos exércitos de Rúben e Gade e da meia tribo de Manassés. Eram todos hábeis no combate e armados com escudos, espadas e arcos.

[[v13-5-19]]

^<<v13-5-19,19>>^ Guerrearam contra os hagarenos e contra Jetur, Nafis e Nodabe.

[[v13-5-20]]

^<<v13-5-20,20>>^ Durante a batalha, clamaram a Deus e ele atendeu às suas orações, pois confiaram nele. Assim, os hagarenos e todos os seus aliados foram derrotados.

[[v13-5-21]]

^<<v13-5-21,21>>^ Tomaram dos hagarenos como despojo 50 mil camelos, 250 mil ovelhas e 2 mil jumentos, e fizeram 100 mil prisioneiros.

[[v13-5-22]]

^<<v13-5-22,22>>^ Muitos dos hagarenos foram mortos na batalha, pois Deus lutou contra eles. As tribos se estabeleceram na terra deles, até que foram levadas para o exílio.

[[v13-5-23]]

^<<v13-5-23,23>>^ A meia tribo de Manassés era numerosa e se espalhou por toda a terra, desde Basã até Baal-Hermom, Senir e o monte Hermom.

[[v13-5-24]]

^<<v13-5-24,24>>^ Os chefes de seus clãs foram: Éfer, Isi, Eliel, Azriel, Jeremias, Hodavias e Jadiel. Esses homens foram guerreiros valentes de grande reputação e chefes de seus clãs.

[[v13-5-25]]

^<<v13-5-25,25>>^ Contudo, essas tribos foram infiéis ao Deus de seus antepassados. Adoraram os deuses das nações que Deus havia destruído diante deles.

[[v13-5-26]]

^<<v13-5-26,26>>^ Por isso, o Deus de Israel fez Pul, rei da Assíria, também conhecido como Tiglate-Pileser, invadir a terra e levar cativos os membros das tribos de Rúben e Gade e da meia tribo de Manassés. Os assírios os deportaram para Hala, Habor, Hara e para o rio Gozã, onde estão até hoje.

'''

xref:013-1-cronicas/013-1-cronicas-004.adoc#v13-4-0[&#60; Capítulo Anterior] | <<v13-5-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[Próximo Capítulo &#62;]