include::./index.adoc[]

[[v13-11-0]]
=== 1 Crônicas, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v13-11-1]]

^<<v13-11-1,1>>^ Então todo o Israel se reuniu diante de Davi, em Hebrom. "Somos do mesmo povo e raça", disseram.

[[v13-11-2]]

^<<v13-11-2,2>>^ "No passado, quando Saul era rei, era você que liderava o exército de Israel. E o SENHOR, seu Deus, lhe disse: ‘Você será o pastor do meu povo, Israel. Será o líder do meu povo, Israel’."

[[v13-11-3]]

^<<v13-11-3,3>>^ Então, ali em Hebrom, Davi fez um acordo diante do SENHOR com todas as autoridades de Israel, e elas o ungiram rei de Israel, conforme o SENHOR havia anunciado por meio de Samuel.

[[v13-11-4]]

^<<v13-11-4,4>>^ Então Davi e todo o Israel foram a Jerusalém (isto é, Jebus), onde moravam os jebuseus, que viviam naquele lugar.

[[v13-11-5]]

^<<v13-11-5,5>>^ Os jebuseus zombaram de Davi: "Você jamais entrará aqui!", mas Davi tomou a fortaleza de Sião, que hoje é chamada de Cidade de Davi.

[[v13-11-6]]

^<<v13-11-6,6>>^ Davi tinha dito a seus soldados: "O primeiro que atacar os jebuseus se tornará o comandante de meus exércitos!". Joabe, filho de Zeruia, foi o primeiro a atacar, e assim se tornou o comandante dos exércitos de Davi.

[[v13-11-7]]

^<<v13-11-7,7>>^ Davi foi morar na fortaleza, e ela passou a ser chamada de Cidade de Davi.

[[v13-11-8]]

^<<v13-11-8,8>>^ Ampliou a cidade, desde o aterro até a região ao redor, enquanto Joabe reconstruiu o restante da cidade.

[[v13-11-9]]

^<<v13-11-9,9>>^ Davi foi se tornando cada vez mais poderoso, pois o SENHOR dos Exércitos estava com ele.

[[v13-11-10]]

^<<v13-11-10,10>>^ Estes foram os líderes dos guerreiros valentes de Davi. Junto com todo o Israel, apoiaram firmemente o reinado de Davi, conforme o SENHOR havia prometido a respeito de Israel.

[[v13-11-11]]

^<<v13-11-11,11>>^ Este é o registro dos guerreiros mais valentes de Davi. O primeiro era Jasobeão, o hacmonita, líder dos Três, isto é, dos guerreiros mais valentes dentre os soldados de Davi. Certa ocasião, usou sua lança para matar trezentos soldados inimigos numa só batalha.

[[v13-11-12]]

^<<v13-11-12,12>>^ O segundo era Eleazar, filho de Dodai, descendente de Aoí.

[[v13-11-13]]

^<<v13-11-13,13>>^ Estava com Davi quando os filisteus se reuniram para a batalha em Pas-Damim e atacaram os israelitas numa plantação de cevada. O exército israelita fugiu,

[[v13-11-14]]

^<<v13-11-14,14>>^ mas Eleazar e Davi mantiveram sua posição no meio do campo e derrotaram os filisteus. O SENHOR os salvou e lhes deu grande vitória.

[[v13-11-15]]

^<<v13-11-15,15>>^ Certa vez, Davi estava na rocha junto à caverna de Adulão, e o exército filisteu estava acampado no vale de Refaim. Os Três — que faziam parte dos Trinta, um grupo de elite entre os valentes de Davi — desceram para encontrá-lo em Adulão.

[[v13-11-16]]

^<<v13-11-16,16>>^ Nessa ocasião, Davi estava na fortaleza, e um destacamento filisteu havia ocupado a cidade de Belém.

[[v13-11-17]]

^<<v13-11-17,17>>^ Davi comentou: "Ah, como seria bom beber a água pura do poço que fica junto ao portão de Belém!".

[[v13-11-18]]

^<<v13-11-18,18>>^ Então os Três atravessaram as fileiras dos filisteus, tiraram água do poço junto ao portão de Belém e a trouxeram a Davi. Ele, porém, se recusou a bebê-la. Em vez disso, derramou-a no chão como oferta ao SENHOR.

[[v13-11-19]]

^<<v13-11-19,19>>^ "Que Deus não permita que eu beba desta água!", exclamou. "Ela é tão preciosa quanto o sangue destes homens que arriscaram a vida para trazê-la." E Davi não a bebeu. Esses são exemplos dos feitos desses três guerreiros.

[[v13-11-20]]

^<<v13-11-20,20>>^ Abisai, irmão de Joabe, era o líder dos Trinta. Certa ocasião, usou sua lança para matar trezentos soldados inimigos numa só batalha. Foi por causa de feitos como esse que ele se tornou tão famoso quanto os Três.

[[v13-11-21]]

^<<v13-11-21,21>>^ Abisai era o mais conhecido dos Trinta e era seu comandante, embora não fosse um dos Três.

[[v13-11-22]]

^<<v13-11-22,22>>^ Também havia Benaia, filho de Joiada, soldado valente de Cabzeel. Realizou muitos feitos heroicos, como matar dois grandes guerreiros de Moabe. Em outra ocasião, num dia de neve, perseguiu um leão até uma cova e o matou.

[[v13-11-23]]

^<<v13-11-23,23>>^ Uma vez, com apenas um cajado, matou um guerreiro egípcio de 2,25 metros de altura armado com uma lança da grossura de um eixo de tecelão. Benaia arrancou a lança da mão do egípcio e com ela o matou.

[[v13-11-24]]

^<<v13-11-24,24>>^ Feitos como esses tornaram Benaia tão famoso quanto os três guerreiros mais valentes.

[[v13-11-25]]

^<<v13-11-25,25>>^ Foi mais honrado que qualquer outro membro dos Trinta, embora não fosse um dos Três. Davi o nomeou comandante de sua guarda pessoal.

[[v13-11-26]]

^<<v13-11-26,26>>^ Outros guerreiros valentes de Davi foram: Asael, irmão de Joabe; Elanã, filho de Dodô, de Belém;

[[v13-11-27]]

^<<v13-11-27,27>>^ Samá, de Harode; Helez, de Pelom;

[[v13-11-28]]

^<<v13-11-28,28>>^ Ira, filho de Iques, de Tecoa; Abiezer, de Anatote;

[[v13-11-29]]

^<<v13-11-29,29>>^ Sibecai, de Husate; Zalmom, de Aoí;

[[v13-11-30]]

^<<v13-11-30,30>>^ Maarai, de Netofate; Helede, filho de Baaná, de Netofate;

[[v13-11-31]]

^<<v13-11-31,31>>^ Itai, filho de Ribai, de Gibeá, na terra de Benjamim; Benaia, de Piratom;

[[v13-11-32]]

^<<v13-11-32,32>>^ Hurai, de Naal-Gaás; Abi-Albom, de Arbate;

[[v13-11-33]]

^<<v13-11-33,33>>^ Azmavete, de Baurim; Eliaba, de Saalbom;

[[v13-11-34]]

^<<v13-11-34,34>>^ os filhos de Jasém, de Gizom; Jônatas, filho de Sage, de Harar;

[[v13-11-35]]

^<<v13-11-35,35>>^ Aião, filho de Sarar, de Harar; Elifal, filho de Ur;

[[v13-11-36]]

^<<v13-11-36,36>>^ Héfer, de Maquerate; Aías, de Pelom;

[[v13-11-37]]

^<<v13-11-37,37>>^ Hezro, do Carmelo; Paarai, filho de Ezbai;

[[v13-11-38]]

^<<v13-11-38,38>>^ Joel, irmão de Natã; Mibar, filho de Hagri;

[[v13-11-39]]

^<<v13-11-39,39>>^ Zeleque, de Amom; Naarai, de Beerote, escudeiro de Joabe, filho de Zeruia;

[[v13-11-40]]

^<<v13-11-40,40>>^ Ira, de Jatir; Garebe, de Jatir;

[[v13-11-41]]

^<<v13-11-41,41>>^ Urias, o hitita; Zabade, filho de Alai;

[[v13-11-42]]

^<<v13-11-42,42>>^ Adina, filho de Siza, líder rubenita que tinha consigo trinta homens;

[[v13-11-43]]

^<<v13-11-43,43>>^ Hanã, filho de Maaca; Josafá, de Mitene;

[[v13-11-44]]

^<<v13-11-44,44>>^ Uzia, de Asterote; Sama e Jeiel, filhos de Hotão, de Aroer;

[[v13-11-45]]

^<<v13-11-45,45>>^ Jediael, filho de Sinri; Joá, de Tiz;

[[v13-11-46]]

^<<v13-11-46,46>>^ Eliel, de Maave; Jeribai e Josavias, filhos de Elnaão; Itma, de Moabe;

[[v13-11-47]]

^<<v13-11-47,47>>^ Eliel e Obede; Jaasiel, de Zobá.

'''

xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[&#60; Capítulo Anterior] | <<v13-11-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-012.adoc#v13-12-0[Próximo Capítulo &#62;]