include::./index.adoc[]

[[v13-19-0]]
=== 1 Crônicas, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v13-19-1]]

^<<v13-19-1,1>>^ Algum tempo depois, morreu Naás, rei dos amonitas, e seu filho Hanum subiu ao trono.

[[v13-19-2]]

^<<v13-19-2,2>>^ Davi disse: "Vou demonstrar lealdade a Hanum assim como seu pai, Naás, sempre foi leal a mim". Então Davi enviou representantes para expressar seu pesar a Hanum pela morte do pai dele. Mas, quando os representantes de Davi chegaram à terra de Amom,

[[v13-19-3]]

^<<v13-19-3,3>>^ os líderes amonitas disseram a Hanum: "O rei acredita mesmo que esses homens estão aqui para honrar seu pai? Não! Davi os enviou com o objetivo de espionar a terra para vir e conquistá-la!".

[[v13-19-4]]

^<<v13-19-4,4>>^ Então Hanum prendeu os representantes de Davi, raspou a barba de cada um, cortou metade de suas roupas até as nádegas e os mandou de volta a Davi.

[[v13-19-5]]

^<<v13-19-5,5>>^ Quando Davi soube do que havia acontecido, enviou mensageiros ao encontro dos homens, para que lhes dissessem: "Fiquem em Jericó até que sua barba tenha crescido e voltem em seguida", pois estavam muito envergonhados.

[[v13-19-6]]

^<<v13-19-6,6>>^ Quando Hanum e os amonitas perceberam quanto haviam enfurecido Davi, enviaram 35 toneladas de prata para Arã-Naarim, Arã-Maaca e Zobá, a fim de contratarem seus carros de guerra e cavaleiros.

[[v13-19-7]]

^<<v13-19-7,7>>^ Também contrataram 32 mil carros de guerra e obtiveram o apoio do rei de Maaca e de seu exército. Esses soldados acamparam em Medeba, onde se juntaram a eles tropas amonitas que Hanum havia recrutado em suas próprias cidades.

[[v13-19-8]]

^<<v13-19-8,8>>^ Davi foi informado disso e enviou Joabe e todos os seus guerreiros para lutarem contra eles.

[[v13-19-9]]

^<<v13-19-9,9>>^ As tropas amonitas avançaram e formaram sua frente de batalha à entrada da cidade, enquanto os outros reis se posicionaram para lutar nos campos abertos.

[[v13-19-10]]

^<<v13-19-10,10>>^ Joabe viu que teria de lutar em duas frentes ao mesmo tempo, por isso escolheu alguns dos melhores guerreiros de Israel e os pôs sob seu comando pessoal para enfrentar os sírios.

[[v13-19-11]]

^<<v13-19-11,11>>^ Deixou o restante do exército sob o comando de seu irmão Abisai, que atacou os amonitas.

[[v13-19-12]]

^<<v13-19-12,12>>^ Joabe disse a seu irmão: "Se os sírios forem fortes demais para mim, venha me ajudar. E, se os amonitas forem fortes demais para você, eu irei ajudá-lo.

[[v13-19-13]]

^<<v13-19-13,13>>^ Coragem! Lutemos bravamente por nosso povo e pelas cidades de nosso Deus. E que seja feita a vontade do SENHOR!".

[[v13-19-14]]

^<<v13-19-14,14>>^ Joabe e suas tropas atacaram, e os sírios começaram a fugir.

[[v13-19-15]]

^<<v13-19-15,15>>^ Quando os amonitas viram que os sírios batiam em retirada, também fugiram de Abisai e recuaram para dentro da cidade. Então Joabe voltou para Jerusalém.

[[v13-19-16]]

^<<v13-19-16,16>>^ Os sírios viram que não tinham como enfrentar Israel. Assim, enviaram mensageiros para convocar mais soldados do outro lado do rio Eufrates. Essas tropas eram conduzidas por Sobaque, comandante do exército de Hadadezer.

[[v13-19-17]]

^<<v13-19-17,17>>^ Quando Davi foi informado do que estava acontecendo, reuniu todo o Israel, atravessou o Jordão e posicionou suas tropas em formação de batalha. Entrou em combate com os sírios, que lutaram contra ele.

[[v13-19-18]]

^<<v13-19-18,18>>^ Mais uma vez, porém, os sírios fugiram dos israelitas. O exército de Davi matou sete mil homens em carros de guerra e quarenta mil soldados de infantaria, incluindo Sobaque, comandante de seu exército.

[[v13-19-19]]

^<<v13-19-19,19>>^ Quando os aliados de Hadadezer viram que ele havia sido derrotado por Israel, renderam-se a Davi e se tornaram seus súditos. Depois disso, os sírios não quiseram mais ajudar os amonitas.

'''

xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[&#60; Capítulo Anterior] | <<v13-19-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[Próximo Capítulo &#62;]