include::./index.adoc[]

[[v13-2-0]]
=== 1 Crônicas, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v13-2-1]]

^<<v13-2-1,1>>^ Os filhos de Israel foram: Rúben, Simeão, Levi, Judá, Issacar, Zebulom,

[[v13-2-2]]

^<<v13-2-2,2>>^ Dã, José, Benjamim, Naftali, Gade e Aser.

[[v13-2-3]]

^<<v13-2-3,3>>^ Judá teve três filhos com Bate-Suá, uma mulher cananeia: Er, Onã e Selá. Mas o SENHOR viu que Er, o filho mais velho, era perverso, e por isso o matou.

[[v13-2-4]]

^<<v13-2-4,4>>^ Algum tempo depois, Judá teve filhos gêmeos com sua nora, Tamar. Chamavam-se Perez e Zerá. Ao todo, Judá teve cinco filhos.

[[v13-2-5]]

^<<v13-2-5,5>>^ Os filhos de Perez foram: Hezrom e Hamul.

[[v13-2-6]]

^<<v13-2-6,6>>^ Os filhos de Zerá foram: Zinri, Etã, Hemã, Calcol e Darda, cinco ao todo.

[[v13-2-7]]

^<<v13-2-7,7>>^ O filho de Carmi se chamava Acã e trouxe calamidade sobre Israel ao tomar para si despojos consagrados para o SENHOR.

[[v13-2-8]]

^<<v13-2-8,8>>^ O filho de Etã foi Azarias.

[[v13-2-9]]

^<<v13-2-9,9>>^ Os filhos de Hezrom foram: Jerameel, Rão e Calebe.

[[v13-2-10]]

^<<v13-2-10,10>>^ Rão gerou Aminadabe. Aminadabe gerou Naassom, um dos líderes de Judá.

[[v13-2-11]]

^<<v13-2-11,11>>^ Naassom gerou Salmom. Salmom gerou Boaz.

[[v13-2-12]]

^<<v13-2-12,12>>^ Boaz gerou Obede. Obede gerou Jessé.

[[v13-2-13]]

^<<v13-2-13,13>>^ O primeiro filho de Jessé foi Eliabe; o segundo, Abinadabe; o terceiro, Simeia;

[[v13-2-14]]

^<<v13-2-14,14>>^ o quarto, Natanael; o quinto, Radai;

[[v13-2-15]]

^<<v13-2-15,15>>^ o sexto, Ozém; e o sétimo, Davi.

[[v13-2-16]]

^<<v13-2-16,16>>^ As irmãs deles se chamavam Zeruia e Abigail. Os três filhos de Zeruia foram: Abisai, Joabe e Asael.

[[v13-2-17]]

^<<v13-2-17,17>>^ Abigail se casou com Jéter, um ismaelita, e tiveram um filho chamado Amasa.

[[v13-2-18]]

^<<v13-2-18,18>>^ Calebe, filho de Hezrom, teve filhos com sua esposa Azuba e com Jeriote. Os filhos de Azuba foram: Jeser, Sobabe e Ardom.

[[v13-2-19]]

^<<v13-2-19,19>>^ Quando Azuba morreu, Calebe se casou com Efrata, e teve com ela um filho chamado Hur.

[[v13-2-20]]

^<<v13-2-20,20>>^ Hur gerou Uri. Uri gerou Bezalel.

[[v13-2-21]]

^<<v13-2-21,21>>^ Quando Hezrom tinha 60 anos, casou-se com a irmã de Gileade, filha de Maquir. Tiveram um filho chamado Segube.

[[v13-2-22]]

^<<v13-2-22,22>>^ Segube gerou Jair, que governou 23 cidades na terra de Gileade.

[[v13-2-23]]

^<<v13-2-23,23>>^ (Contudo, Gesur e Arã tomaram as Cidades de Jair, além de Quenate e os sessenta povoados ao redor.) Todos esses foram descendentes de Maquir, pai de Gileade.

[[v13-2-24]]

^<<v13-2-24,24>>^ Logo depois que Hezrom morreu na cidade de Calebe-Efrata, sua esposa Abia deu à luz um filho chamado Asur, pai de Tecoa.

[[v13-2-25]]

^<<v13-2-25,25>>^ Os filhos de Jerameel, filho mais velho de Hezrom, foram: Rão, o mais velho, Buna, Orém, Ozém e Aías.

[[v13-2-26]]

^<<v13-2-26,26>>^ Atara, segunda esposa de Jerameel, teve um filho chamado Onã.

[[v13-2-27]]

^<<v13-2-27,27>>^ Os filhos de Rão, filho mais velho de Jerameel, foram: Maaz, Jamim e Equer.

[[v13-2-28]]

^<<v13-2-28,28>>^ Os filhos de Onã foram: Samai e Jada. Os filhos de Samai foram: Nadabe e Abisur.

[[v13-2-29]]

^<<v13-2-29,29>>^ Os filhos de Abisur com sua esposa Abiail foram: Abã e Molide.

[[v13-2-30]]

^<<v13-2-30,30>>^ Os filhos de Nadabe foram Selede e Apaim. Selede morreu sem filhos,

[[v13-2-31]]

^<<v13-2-31,31>>^ mas Apaim teve um filho chamado Isi. O filho de Isi se chamava Sesã, e o filho de Sesã, Alai.

[[v13-2-32]]

^<<v13-2-32,32>>^ Os filhos de Jada, irmão de Samai, foram: Jéter e Jônatas. Jéter morreu sem filhos,

[[v13-2-33]]

^<<v13-2-33,33>>^ mas Jônatas teve dois filhos: Pelete e Zaza. Todos esses foram descendentes de Jerameel.

[[v13-2-34]]

^<<v13-2-34,34>>^ Sesã não teve filhos, mas teve filhas. Tinha também um servo egípcio chamado Jará.

[[v13-2-35]]

^<<v13-2-35,35>>^ Sesã deu uma de suas filhas em casamento a Jará, e eles tiveram um filho chamado Atai.

[[v13-2-36]]

^<<v13-2-36,36>>^ Atai gerou Natã. Natã gerou Zabade.

[[v13-2-37]]

^<<v13-2-37,37>>^ Zabade gerou Eflal. Eflal gerou Obede.

[[v13-2-38]]

^<<v13-2-38,38>>^ Obede gerou Jeú. Jeú gerou Azarias.

[[v13-2-39]]

^<<v13-2-39,39>>^ Azarias gerou Helez. Helez gerou Eleasá.

[[v13-2-40]]

^<<v13-2-40,40>>^ Eleasá gerou Sismai. Sismai gerou Salum.

[[v13-2-41]]

^<<v13-2-41,41>>^ Salum gerou Jecamias. Jecamias gerou Elisama.

[[v13-2-42]]

^<<v13-2-42,42>>^ Um dos descendentes de Calebe, irmão de Jerameel, foi Messa, o filho mais velho. Messa gerou Zife. Outros descendentes de Calebe foram os filhos de Maressa, pai de Hebrom.

[[v13-2-43]]

^<<v13-2-43,43>>^ Os filhos de Hebrom foram: Corá, Tapua, Requém e Sema.

[[v13-2-44]]

^<<v13-2-44,44>>^ Sema gerou Raão. Raão gerou Jorqueão. Requém gerou Samai.

[[v13-2-45]]

^<<v13-2-45,45>>^ O filho de Samai se chamava Maom. Maom foi o pai de Bete-Zur.

[[v13-2-46]]

^<<v13-2-46,46>>^ Efá, concubina de Calebe, deu à luz Harã, Moza e Gazez. Harã gerou Gazez.

[[v13-2-47]]

^<<v13-2-47,47>>^ Os filhos de Jadai foram: Regém, Jotão, Gesã, Pelete, Efá e Saafe.

[[v13-2-48]]

^<<v13-2-48,48>>^ Maaca, outra concubina de Calebe, deu à luz Seber e Tiraná.

[[v13-2-49]]

^<<v13-2-49,49>>^ Também deu à luz Saafe, pai de Madmana, e Seva, pai de Macbena e de Gibeá. Calebe também teve uma filha chamada Acsa.

[[v13-2-50]]

^<<v13-2-50,50>>^ Todos esses foram descendentes de Calebe. Os filhos de Hur, filho mais velho de Efrata, esposa de Calebe, foram: Sobal, fundador de Quiriate-Jearim,

[[v13-2-51]]

^<<v13-2-51,51>>^ Salma, fundador de Belém, e Harefe, fundador de Bete-Gader.

[[v13-2-52]]

^<<v13-2-52,52>>^ Os descendentes de Sobal, fundador de Quiriate-Jearim, foram: o povo de Haroé, metade dos manaatitas,

[[v13-2-53]]

^<<v13-2-53,53>>^ e os clãs de Quiriate-Jearim: os itritas, os fateus, os sumateus e os misraeus, dos quais descenderam os povos de Zorá e Estaol.

[[v13-2-54]]

^<<v13-2-54,54>>^ Os descendentes de Salma foram: o povo de Belém, os netofatitas, o povo de Atarote-Bete-Joabe, a outra metade dos manaatitas, os zoreus,

[[v13-2-55]]

^<<v13-2-55,55>>^ e as famílias dos escribas que viviam em Jabez: os tiratitas, os simeatitas e os sucatitas. Todos esses foram os queneus, descendentes de Hamate, pai do clã de Recabe.

'''

xref:013-1-cronicas/013-1-cronicas-001.adoc#v13-1-0[&#60; Capítulo Anterior] | <<v13-2-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[Próximo Capítulo &#62;]