include::./index.adoc[]

[[v59-2-0]]
=== Tiago, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v59-2-1]]

^<<v59-2-1,1>>^ Meus irmãos, como podem afirmar que têm fé em nosso glorioso Senhor Jesus Cristo se mostram favorecimento a algumas pessoas?

[[v59-2-2]]

^<<v59-2-2,2>>^ Se, por exemplo, alguém chegar a uma de suas reuniões vestido com roupas elegantes e usando joias caras, e também entrar um pobre com roupas sujas,

[[v59-2-3]]

^<<v59-2-3,3>>^ e vocês derem atenção ao que está bem vestido, dizendo-lhe: "Sente-se aqui neste lugar especial", mas disserem ao pobre: "Fique em pé ali ou sente-se aqui no chão",

[[v59-2-4]]

^<<v59-2-4,4>>^ essa discriminação não mostrará que agem como juízes guiados por motivos perversos?

[[v59-2-5]]

^<<v59-2-5,5>>^ Ouçam, meus amados irmãos: não foi Deus que escolheu os pobres deste mundo para serem ricos na fé? Não são eles os herdeiros do reino prometido àqueles que o amam?

[[v59-2-6]]

^<<v59-2-6,6>>^ Mas vocês desprezam os pobres! Não são os ricos que oprimem vocês e os arrastam aos tribunais?

[[v59-2-7]]

^<<v59-2-7,7>>^ Não são eles que difamam aquele cujo nome honroso vocês carregam?

[[v59-2-8]]

^<<v59-2-8,8>>^ Sem dúvida vocês fazem bem quando obedecem à lei do reino conforme dizem as Escrituras: "Ame seu próximo como a si mesmo".

[[v59-2-9]]

^<<v59-2-9,9>>^ Mas, se mostram favorecimento a algumas pessoas, cometem pecado e são culpados de transgredir a lei.

[[v59-2-10]]

^<<v59-2-10,10>>^ Pois quem obedece a todas as leis, exceto uma, torna-se culpado de desobedecer a todas as outras.

[[v59-2-11]]

^<<v59-2-11,11>>^ Pois aquele que disse: "Não cometa adultério", também disse: "Não mate". Logo, mesmo que não cometam adultério, se matarem alguém, transgredirão a lei.

[[v59-2-12]]

^<<v59-2-12,12>>^ Portanto, em tudo que disserem e fizerem, lembrem-se de que serão julgados pela lei que os liberta.

[[v59-2-13]]

^<<v59-2-13,13>>^ Não haverá misericórdia para quem não tiver demonstrado misericórdia. Mas, se forem misericordiosos, haverá misericórdia quando forem julgados.

[[v59-2-14]]

^<<v59-2-14,14>>^ De que adianta, meus irmãos, dizerem que têm fé se não a demonstram por meio de suas ações? Acaso esse tipo de fé pode salvar alguém?

[[v59-2-15]]

^<<v59-2-15,15>>^ Se um irmão ou uma irmã necessitar de alimento ou de roupa,

[[v59-2-16]]

^<<v59-2-16,16>>^ e vocês disserem: "Até logo e tenha um bom dia; aqueça-se e coma bem", mas não lhe derem alimento nem roupa, em que isso ajuda?

[[v59-2-17]]

^<<v59-2-17,17>>^ Como veem, a fé por si mesma, a menos que produza boas obras, está morta.

[[v59-2-18]]

^<<v59-2-18,18>>^ Mas alguém pode argumentar: "Uns têm fé; outros têm obras". Mostre-me sua fé sem obras e eu, pelas minhas obras, lhe mostrarei minha fé!

[[v59-2-19]]

^<<v59-2-19,19>>^ Você diz crer que há um único Deus. Muito bem! Até os demônios creem nisso e tremem de medo.

[[v59-2-20]]

^<<v59-2-20,20>>^ Quanta insensatez! Vocês não entendem que a fé sem as obras é inútil?

[[v59-2-21]]

^<<v59-2-21,21>>^ Não lembram que nosso antepassado Abraão foi declarado justo por suas ações quando ofereceu seu filho Isaque sobre o altar?

[[v59-2-22]]

^<<v59-2-22,22>>^ Como veem, sua fé e suas ações atuaram juntas e, assim, as ações tornaram a fé completa.

[[v59-2-23]]

^<<v59-2-23,23>>^ E aconteceu exatamente como as Escrituras dizem: "Abraão creu em Deus, e assim foi considerado justo". Ele até foi chamado amigo de Deus!

[[v59-2-24]]

^<<v59-2-24,24>>^ Vejam que somos declarados justos pelo que fazemos, e não apenas pela fé.

[[v59-2-25]]

^<<v59-2-25,25>>^ Raabe, a prostituta, é outro exemplo. Ela foi declarada justa por causa de suas ações quando escondeu os mensageiros e os fez sair em segurança por um caminho diferente.

[[v59-2-26]]

^<<v59-2-26,26>>^ Assim como o corpo sem fôlego está morto, também a fé sem obras está morta.

'''

xref:059-tiago/059-tiago-001.adoc#v59-1-0[&#60; Capítulo Anterior] | <<v59-2-0,Topo>> | xref:059-tiago/059-tiago-003.adoc#v59-3-0[Próximo Capítulo &#62;]