include::./index.adoc[]

[[v59-1-0]]
=== Tiago, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v59-1-1]]

^<<v59-1-1,1>>^ Eu, Tiago, escravo de Deus e do Senhor Jesus Cristo, envio esta carta às doze tribos espalhadas pelo mundo. Saudações.

[[v59-1-2]]

^<<v59-1-2,2>>^ Meus irmãos, considerem motivo de grande alegria sempre que passarem por qualquer tipo de provação,

[[v59-1-3]]

^<<v59-1-3,3>>^ pois sabem que, quando sua fé é provada, a perseverança tem a oportunidade de crescer.

[[v59-1-4]]

^<<v59-1-4,4>>^ E é necessário que ela cresça, pois quando estiver plenamente desenvolvida vocês serão maduros e completos, sem que nada lhes falte.

[[v59-1-5]]

^<<v59-1-5,5>>^ Se algum de vocês precisar de sabedoria, peça a nosso Deus generoso, e receberá. Ele não os repreenderá por pedirem.

[[v59-1-6]]

^<<v59-1-6,6>>^ Mas, quando pedirem, façam-no com fé, sem vacilar, pois aquele que duvida é como a onda do mar, empurrada e agitada pelo vento.

[[v59-1-7]]

^<<v59-1-7,7>>^ Ele não deve esperar receber coisa alguma do Senhor,

[[v59-1-8]]

^<<v59-1-8,8>>^ pois tem a mente dividida e é instável em tudo que faz.

[[v59-1-9]]

^<<v59-1-9,9>>^ O irmão que é pobre tem motivo para se orgulhar, porque é digno de honra.

[[v59-1-10]]

^<<v59-1-10,10>>^ E o que é rico deve se orgulhar porque é insignificante. Ele murchará como uma pequena flor do campo.

[[v59-1-11]]

^<<v59-1-11,11>>^ O sol quente se levanta e a grama seca; a flor perde o viço e cai, e sua beleza desaparece. Da mesma forma murchará o rico com todas as suas realizações.

[[v59-1-12]]

^<<v59-1-12,12>>^ Feliz é aquele que suporta com paciência as provações e tentações, porque depois receberá a coroa da vida que Deus prometeu àqueles que o amam.

[[v59-1-13]]

^<<v59-1-13,13>>^ E, quando vocês forem tentados, não digam: "Esta tentação vem de Deus", pois Deus nunca é tentado a fazer o mal, e ele mesmo nunca tenta alguém.

[[v59-1-14]]

^<<v59-1-14,14>>^ A tentação vem de nossos próprios desejos, que nos seduzem e nos arrastam.

[[v59-1-15]]

^<<v59-1-15,15>>^ Esses desejos dão à luz o pecado, e quando o pecado se desenvolve plenamente, gera a morte.

[[v59-1-16]]

^<<v59-1-16,16>>^ Não se deixem enganar, meus amados irmãos.

[[v59-1-17]]

^<<v59-1-17,17>>^ Toda dádiva que é boa e perfeita vem do alto, do Pai que criou as luzes no céu. Nele não há variação nem sombra de mudança.

[[v59-1-18]]

^<<v59-1-18,18>>^ Por sua própria vontade, ele nos gerou por meio de sua palavra verdadeira. E nós, dentre toda a criação, nos tornamos seus primeiros frutos.

[[v59-1-19]]

^<<v59-1-19,19>>^ Entendam isto, meus amados irmãos: estejam todos prontos para ouvir, mas não se apressem em falar nem em se irar.

[[v59-1-20]]

^<<v59-1-20,20>>^ A ira humana não produz a justiça divina.

[[v59-1-21]]

^<<v59-1-21,21>>^ Portanto, removam toda impureza e maldade e aceitem humildemente a palavra que lhes foi implantada no coração, pois ela tem poder para salvá-los.

[[v59-1-22]]

^<<v59-1-22,22>>^ Não se limitem, porém, a ouvir a palavra; ponham-na em prática. Do contrário, só enganarão a si mesmos.

[[v59-1-23]]

^<<v59-1-23,23>>^ Pois, se ouvirem a palavra e não a praticarem, serão como alguém que olha no espelho,

[[v59-1-24]]

^<<v59-1-24,24>>^ vê a si mesmo, mas, assim que se afasta, esquece como era sua aparência.

[[v59-1-25]]

^<<v59-1-25,25>>^ Se, contudo, observarem atentamente a lei perfeita que os liberta, perseverarem nela e a puserem em prática sem esquecer o que ouviram, serão felizes no que fizerem.

[[v59-1-26]]

^<<v59-1-26,26>>^ Se algum de vocês afirma ser religioso, mas não controla a língua, engana a si mesmo e sua religião não tem valor.

[[v59-1-27]]

^<<v59-1-27,27>>^ A religião pura e verdadeira aos olhos de Deus, o Pai, é esta: cuidar dos órfãos e das viúvas em suas dificuldades e não se deixar corromper pelo mundo.

'''

xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[&#60; Capítulo Anterior] | <<v59-1-0,Topo>> | xref:059-tiago/059-tiago-002.adoc#v59-2-0[Próximo Capítulo &#62;]