include::./index.adoc[]

[[v59-5-0]]
=== Tiago, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v59-5-1]]

^<<v59-5-1,1>>^ Prestem atenção, vocês que são ricos. Chorem e gemam de angústia por causa das desgraças que os esperam.

[[v59-5-2]]

^<<v59-5-2,2>>^ Sua riqueza apodreceu, e suas roupas finas são trapos comidos por traças.

[[v59-5-3]]

^<<v59-5-3,3>>^ Seu ouro e sua prata estão corroídos. A mesma riqueza com a qual vocês contavam devorará sua carne como fogo. Esse tesouro corroído que vocês acumularam testemunhará contra vocês nos últimos dias.

[[v59-5-4]]

^<<v59-5-4,4>>^ Por isso, ouçam os clamores dos que trabalharam em seus campos, cujo salário vocês retiveram de modo fraudulento! Sim, os clamores dos que fizeram a colheita em seus campos chegaram aos ouvidos do Senhor dos Exércitos.

[[v59-5-5]]

^<<v59-5-5,5>>^ Vocês levam uma vida de luxo na terra, satisfazendo seus desejos e engordando a si mesmos para o dia do abate.

[[v59-5-6]]

^<<v59-5-6,6>>^ Condenam e matam inocentes, sem que eles resistam.

[[v59-5-7]]

^<<v59-5-7,7>>^ Por isso, irmãos, sejam pacientes enquanto esperam a volta do Senhor. Vejam como os lavradores esperam pacientemente as chuvas do outono e da primavera. Com grande expectativa, aguardam o amadurecimento de sua preciosa colheita.

[[v59-5-8]]

^<<v59-5-8,8>>^ Sejam também pacientes. Fortaleçam-se em seu coração, pois a vinda do Senhor está próxima.

[[v59-5-9]]

^<<v59-5-9,9>>^ Irmãos, não se queixem uns dos outros, para que não sejam julgados. Pois, vejam, o Juiz está à porta!

[[v59-5-10]]

^<<v59-5-10,10>>^ Irmãos, tomem como exemplo de paciência no sofrimento os profetas que falaram em nome do Senhor.

[[v59-5-11]]

^<<v59-5-11,11>>^ Consideramos felizes aqueles que permanecem firmes em meio à aflição. Vocês ouviram falar de Jó, um homem de muita perseverança. Sabem como, no final, o Senhor foi bondoso com ele, pois o Senhor é cheio de compaixão e misericórdia.

[[v59-5-12]]

^<<v59-5-12,12>>^ Acima de tudo, meus irmãos, não jurem pelo céu, nem pela terra, nem por qualquer outra coisa. Que seu "sim" seja de fato sim, e seu "não", não, para que não pequem e sejam condenados.

[[v59-5-13]]

^<<v59-5-13,13>>^ Algum de vocês está passando por dificuldades? Então ore. Alguém está feliz? Cante louvores.

[[v59-5-14]]

^<<v59-5-14,14>>^ Alguém está doente? Chame os presbíteros da igreja para que venham e orem sobre ele e o unjam com óleo, em nome do Senhor.

[[v59-5-15]]

^<<v59-5-15,15>>^ Essa oração de fé curará o enfermo, e o Senhor o restabelecerá. E, se cometeu algum pecado, será perdoado.

[[v59-5-16]]

^<<v59-5-16,16>>^ Portanto, confessem seus pecados uns aos outros e orem uns pelos outros para serem curados. A oração de um justo tem grande poder e produz grandes resultados.

[[v59-5-17]]

^<<v59-5-17,17>>^ Elias era humano como nós e, no entanto, quando orou insistentemente para que não caísse chuva, não choveu durante três anos e meio.

[[v59-5-18]]

^<<v59-5-18,18>>^ Então ele orou outra vez e o céu enviou chuva, e a terra começou a produzir suas colheitas.

[[v59-5-19]]

^<<v59-5-19,19>>^ Meus irmãos, se algum de vocês se desviar da verdade e for trazido de volta,

[[v59-5-20]]

^<<v59-5-20,20>>^ saibam que quem trouxer o pecador de volta de seu desvio o salvará da morte e trará perdão para muitos pecados.

'''

xref:059-tiago/059-tiago-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[Próximo Capítulo &#62;]