include::./index.adoc[]

[[v59-4-0]]
=== Tiago, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v59-4-1]]

^<<v59-4-1,1>>^ De onde vêm as discussões e brigas em seu meio? Acaso não procedem dos prazeres que guerreiam dentro de vocês?

[[v59-4-2]]

^<<v59-4-2,2>>^ Querem o que não têm, e até matam para consegui-lo. Invejam o que outros possuem, lutam e fazem guerra para tomar deles. E, no entanto, não têm o que desejam porque não pedem.

[[v59-4-3]]

^<<v59-4-3,3>>^ E, quando pedem, não recebem, pois seus motivos são errados; pedem apenas o que lhes dará prazer.

[[v59-4-4]]

^<<v59-4-4,4>>^ Adúlteros! Não percebem que a amizade com o mundo os torna inimigos de Deus? Repito: se desejam ser amigos do mundo, tornam-se inimigos de Deus.

[[v59-4-5]]

^<<v59-4-5,5>>^ O que vocês acham que as Escrituras querem dizer quando afirmam que o espírito colocado por Deus em nós tem ciúmes?

[[v59-4-6]]

^<<v59-4-6,6>>^ Contudo, ele generosamente nos concede graça. Como dizem as Escrituras: "Deus se opõe aos orgulhosos, mas concede graça aos humildes".

[[v59-4-7]]

^<<v59-4-7,7>>^ Portanto, submetam-se a Deus. Resistam ao diabo, e ele fugirá de vocês.

[[v59-4-8]]

^<<v59-4-8,8>>^ Aproximem-se de Deus, e ele se aproximará de vocês. Lavem as mãos, pecadores; purifiquem o coração, vocês que têm a mente dividida.

[[v59-4-9]]

^<<v59-4-9,9>>^ Que haja lágrimas, lamentação e profundo pesar. Que haja choro em vez de riso, e tristeza em vez de alegria.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humilhem-se diante do Senhor, e ele os exaltará.

[[v59-4-11]]

^<<v59-4-11,11>>^ Irmãos, não falem mal uns dos outros. Se criticam e julgam uns aos outros, criticam e julgam a lei. Cabe-lhes, porém, praticar a lei, e não julgá-la.

[[v59-4-12]]

^<<v59-4-12,12>>^ Somente aquele que deu a lei é Juiz, e somente ele tem poder de salvar ou destruir. Portanto, que direito vocês têm de julgar o próximo?

[[v59-4-13]]

^<<v59-4-13,13>>^ Prestem atenção, vocês que dizem: "Hoje ou amanhã iremos a determinada cidade e ficaremos lá um ano. Negociaremos ali e teremos lucro".

[[v59-4-14]]

^<<v59-4-14,14>>^ Como sabem o que será de sua vida amanhã? A vida é como a névoa ao amanhecer: aparece por um pouco e logo se dissipa.

[[v59-4-15]]

^<<v59-4-15,15>>^ O que devem dizer é: "Se o Senhor quiser, viveremos e faremos isso ou aquilo".

[[v59-4-16]]

^<<v59-4-16,16>>^ Caso contrário, estarão se orgulhando de seus planos pretensiosos, e toda presunção como essa é maligna.

[[v59-4-17]]

^<<v59-4-17,17>>^ Lembrem-se de que é pecado saber o que devem fazer e não fazê-lo.

'''

xref:059-tiago/059-tiago-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-tiago/059-tiago-005.adoc#v59-5-0[Próximo Capítulo &#62;]