include::./index.adoc[]

[[v59-3-0]]
=== Tiago, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v59-3-1]]

^<<v59-3-1,1>>^ Meus irmãos, não sejam muitos de vocês mestres, pois nós, os que ensinamos, seremos julgados com mais rigor.

[[v59-3-2]]

^<<v59-3-2,2>>^ É verdade que todos nós cometemos muitos erros. Se pudéssemos controlar a língua, seríamos perfeitos, capazes de nos controlar em todos os outros sentidos.

[[v59-3-3]]

^<<v59-3-3,3>>^ Por exemplo, se colocamos um freio na boca do cavalo, podemos conduzi-lo para onde quisermos.

[[v59-3-4]]

^<<v59-3-4,4>>^ Observem também que um pequeno leme faz um grande navio se voltar para onde o piloto deseja, mesmo com ventos fortes.

[[v59-3-5]]

^<<v59-3-5,5>>^ Assim também, a língua é algo pequeno que profere discursos grandiosos. Vejam como uma simples fagulha é capaz de incendiar uma grande floresta.

[[v59-3-6]]

^<<v59-3-6,6>>^ E, entre todas as partes do corpo, a língua é uma chama de fogo. É um mundo de maldade que corrompe todo o corpo. Ateia fogo a uma vida inteira, pois o próprio inferno a acende.

[[v59-3-7]]

^<<v59-3-7,7>>^ O ser humano consegue domar toda espécie de animal, ave, réptil e peixe,

[[v59-3-8]]

^<<v59-3-8,8>>^ mas ninguém consegue domar a língua. Ela é incontrolável e perversa, cheia de veneno mortífero.

[[v59-3-9]]

^<<v59-3-9,9>>^ Às vezes louva nosso Senhor e Pai e, às vezes, amaldiçoa aqueles que Deus criou à sua imagem.

[[v59-3-10]]

^<<v59-3-10,10>>^ E, assim, bênção e maldição saem da mesma boca. Meus irmãos, isso não está certo!

[[v59-3-11]]

^<<v59-3-11,11>>^ Acaso de uma mesma fonte pode jorrar água doce e amarga?

[[v59-3-12]]

^<<v59-3-12,12>>^ Pode a figueira produzir azeitonas ou a videira produzir figos? Da mesma forma, não se pode tirar água doce de uma fonte salgada.

[[v59-3-13]]

^<<v59-3-13,13>>^ Se vocês são sábios e inteligentes, demonstrem isso vivendo honradamente, realizando boas obras com a humildade que vem da sabedoria.

[[v59-3-14]]

^<<v59-3-14,14>>^ Mas, se em seu coração há inveja amarga e ambição egoísta, não encubram a verdade com vanglórias e mentiras.

[[v59-3-15]]

^<<v59-3-15,15>>^ Porque essas coisas não são a espécie de sabedoria que vem do alto; antes, são terrenas, mundanas e demoníacas.

[[v59-3-16]]

^<<v59-3-16,16>>^ Pois onde há inveja e ambição egoísta, também há confusão e males de todo tipo.

[[v59-3-17]]

^<<v59-3-17,17>>^ Mas a sabedoria que vem do alto é, antes de tudo, pura. Também é pacífica, sempre amável e disposta a ceder a outros. É cheia de misericórdia e é o fruto de boas obras. Não mostra favoritismo e é sempre sincera.

[[v59-3-18]]

^<<v59-3-18,18>>^ E aqueles que são pacificadores plantarão sementes de paz e ajuntarão uma colheita de justiça.

'''

xref:059-tiago/059-tiago-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-tiago/059-tiago-004.adoc#v59-4-0[Próximo Capítulo &#62;]