include::./index.adoc[]

[[v56-3-0]]
=== Tito, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v56-3-1]]

^<<v56-3-1,1>>^ Lembre a todos que se sujeitem ao governo e às autoridades. Devem ser obedientes e sempre prontos a fazer o que é bom.

[[v56-3-2]]

^<<v56-3-2,2>>^ Não devem caluniar ninguém, mas evitar brigas. Que sejam amáveis e mostrem a todos verdadeira humildade.

[[v56-3-3]]

^<<v56-3-3,3>>^ Em outros tempos, também éramos insensatos e desobedientes. Vivíamos no engano e nos tornamos escravos de muitas paixões e prazeres. Éramos cheios de maldade e inveja e odiávamos uns aos outros.

[[v56-3-4]]

^<<v56-3-4,4>>^ Mas, Quando Deus, nosso Salvador, revelou sua bondade e seu amor,

[[v56-3-5]]

^<<v56-3-5,5>>^ ele nos salvou não porque tivéssemos feito algo justo, mas por causa de sua misericórdia. Ele nos lavou para remover nossos pecados, nos fez nascer de novo e nos deu nova vida por meio do Espírito Santo.

[[v56-3-6]]

^<<v56-3-6,6>>^ Generosamente, derramou o Espírito sobre nós por meio de Jesus Cristo, nosso Salvador.

[[v56-3-7]]

^<<v56-3-7,7>>^ Por causa de sua graça, nos declarou justos e nos deu a esperança de que herdaremos a vida eterna.

[[v56-3-8]]

^<<v56-3-8,8>>^ Essa é uma afirmação digna de confiança, e quero que você insista nesses ensinamentos, para que todos os que creem em Deus se dediquem a fazer o bem. São ensinamentos bons e benéficos para todos.

[[v56-3-9]]

^<<v56-3-9,9>>^ Não se envolva em discussões tolas sobre genealogias intermináveis, nem em disputas e brigas sobre a obediência às leis judaicas. Essas coisas são inúteis, e perda de tempo.

[[v56-3-10]]

^<<v56-3-10,10>>^ Se alguém tem causado divisões entre vocês, advirta-o uma primeira e uma segunda vez. Depois disso, não se relacione mais com ele.

[[v56-3-11]]

^<<v56-3-11,11>>^ Tais indivíduos se desviaram da verdade e condenaram a si mesmos com seus pecados.

[[v56-3-12]]

^<<v56-3-12,12>>^ Planejo enviar-lhe Ártemas ou Tíquico. Assim que um deles chegar, procure ir ao meu encontro em Nicópolis, pois decidi passar o inverno ali.

[[v56-3-13]]

^<<v56-3-13,13>>^ Faça todo o possível para ajudar Zenas, o advogado, e Apolo na viagem deles. Providencie que tenham tudo de que precisam.

[[v56-3-14]]

^<<v56-3-14,14>>^ Nosso povo deve aprender a fazer o bem ao suprir as necessidades urgentes de outros; assim, ninguém será improdutivo.

[[v56-3-15]]

^<<v56-3-15,15>>^ Todos aqui mandam lembranças. Por favor, envie minhas saudações a todos que nos amam na fé. Que a graça de Deus esteja com todos vocês.

'''

xref:056-tito/056-tito-002.adoc#v56-2-0[&#60; Capítulo Anterior] | <<v56-3-0,Topo>> | xref:057-filemom/057-filemom-001.adoc#v57-1-0[Próximo Capítulo &#62;]