include::./index.adoc[]

[[v56-2-0]]
=== Tito, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v56-2-1]]

^<<v56-2-1,1>>^ Mas, quanto a você, que suas palavras reflitam o ensino verdadeiro.

[[v56-2-2]]

^<<v56-2-2,2>>^ Os homens mais velhos devem exercitar o autocontrole, a fim de que sejam dignos de respeito e vivam com sabedoria. Devem ter uma fé sólida e ser cheios de amor e paciência.

[[v56-2-3]]

^<<v56-2-3,3>>^ Semelhantemente, as mulheres mais velhas devem viver de modo digno. Não devem ser caluniadoras, nem beber vinho em excesso; antes, devem ensinar o que é bom.

[[v56-2-4]]

^<<v56-2-4,4>>^ Devem instruir as mulheres mais jovens a amar o marido e os filhos,

[[v56-2-5]]

^<<v56-2-5,5>>^ a viver com sabedoria e pureza, a trabalhar no lar, a fazer o bem e a ser submissas ao marido. Assim, não envergonharão a palavra de Deus.

[[v56-2-6]]

^<<v56-2-6,6>>^ Da mesma forma, incentive os homens mais jovens a viver com sabedoria.

[[v56-2-7]]

^<<v56-2-7,7>>^ Você mesmo deve ser exemplo da prática de boas obras. Tudo que fizer deve refletir a integridade e a seriedade de seu ensino.

[[v56-2-8]]

^<<v56-2-8,8>>^ Sua mensagem deve ser tão correta a ponto de ninguém a criticar. Então os que se opõem a nós ficarão envergonhados e nada terão de ruim para dizer a nosso respeito.

[[v56-2-9]]

^<<v56-2-9,9>>^ Quanto aos escravos, devem sempre obedecer a seu senhor e fazer todo o possível para agradá-lo. Não devem ser respondões,

[[v56-2-10]]

^<<v56-2-10,10>>^ nem roubar, mas devem mostrar-se bons e inteiramente dignos de confiança. Assim, tornarão atraente em todos os sentidos o ensino a respeito de Deus, nosso Salvador.

[[v56-2-11]]

^<<v56-2-11,11>>^ Pois a graça de Deus foi revelada e a todos traz salvação.

[[v56-2-12]]

^<<v56-2-12,12>>^ Somos instruídos a abandonar o estilo de vida ímpio e os prazeres pecaminosos. Neste mundo perverso, devemos viver com sabedoria, justiça e devoção,

[[v56-2-13]]

^<<v56-2-13,13>>^ enquanto aguardamos esperançosamente o dia em que será revelada a glória de nosso grande Deus e Salvador, Jesus Cristo.

[[v56-2-14]]

^<<v56-2-14,14>>^ Ele entregou sua vida para nos libertar de todo pecado, para nos purificar e fazer de nós seu povo, inteiramente dedicado às boas obras.

[[v56-2-15]]

^<<v56-2-15,15>>^ Ensine essas coisas e encoraje os irmãos a praticá-las. Corrija-os com autoridade. Não deixe que ignorem o que você diz.

'''

xref:056-tito/056-tito-001.adoc#v56-1-0[&#60; Capítulo Anterior] | <<v56-2-0,Topo>> | xref:056-tito/056-tito-003.adoc#v56-3-0[Próximo Capítulo &#62;]