include::./index.adoc[]

[[v56-1-0]]
=== Tito, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v56-1-1]]

^<<v56-1-1,1>>^ Eu, Paulo, escravo de Deus e apóstolo de Jesus Cristo, escrevo esta carta. Fui enviado para fortalecer a fé daqueles que Deus escolheu e para ensinar-lhes a verdade que mostra como viver uma vida de devoção.

[[v56-1-2]]

^<<v56-1-2,2>>^ Essa verdade lhes dá a esperança da vida eterna que Deus, aquele que não mente, prometeu antes dos tempos eternos.

[[v56-1-3]]

^<<v56-1-3,3>>^ E agora, no devido tempo, ele revelou essa mensagem, que anunciamos a todos. Por ordem de Deus, nosso Salvador, fui encarregado de realizar esse trabalho em favor dele.

[[v56-1-4]]

^<<v56-1-4,4>>^ Escrevo a Tito, meu verdadeiro filho na fé que compartilhamos. Que Deus, o Pai, e Cristo Jesus, nosso Salvador, lhe deem graça e paz.

[[v56-1-5]]

^<<v56-1-5,5>>^ Deixei-o na ilha de Creta para que você completasse o trabalho e nomeasse presbíteros em cada cidade, conforme o instruí.

[[v56-1-6]]

^<<v56-1-6,6>>^ O presbítero deve ter uma vida irrepreensível. Deve ser marido de uma só mulher, e seus filhos devem partilhar de sua fé e não ter fama de devassos nem rebeldes.

[[v56-1-7]]

^<<v56-1-7,7>>^ O bispo administra a casa de Deus e, portanto, deve ter uma vida irrepreensível. Não deve ser arrogante nem briguento, não deve beber vinho em excesso, nem ser violento, nem buscar lucro desonesto.

[[v56-1-8]]

^<<v56-1-8,8>>^ Em vez disso, deve ser hospitaleiro e amar o bem. Deve viver sabiamente, ser justo e ter uma vida de devoção e disciplina.

[[v56-1-9]]

^<<v56-1-9,9>>^ Deve estar plenamente convicto da mensagem fiel que lhe foi ensinada, de modo que possa encorajar outros com o verdadeiro ensino e mostrar aos que se opõem onde estão errados.

[[v56-1-10]]

^<<v56-1-10,10>>^ Pois há muitos rebeldes que promovem conversas inúteis e enganam as pessoas. Refiro-me especialmente àqueles que insistem na necessidade da circuncisão.

[[v56-1-11]]

^<<v56-1-11,11>>^ É preciso fazê-los calar, pois, com seus ensinamentos falsos, têm desviado famílias inteiras da verdade. Sua motivação é obter lucro desonesto.

[[v56-1-12]]

^<<v56-1-12,12>>^ Até mesmo um deles, um profeta nascido em Creta, disse: "Os cretenses são mentirosos, animais cruéis e comilões preguiçosos".

[[v56-1-13]]

^<<v56-1-13,13>>^ Isso é verdade. Portanto, repreenda-os severamente, a fim de fortalecê-los na fé.

[[v56-1-14]]

^<<v56-1-14,14>>^ É preciso que deixem de dar ouvidos a mitos judaicos e às ordens daqueles que se desviaram da verdade.

[[v56-1-15]]

^<<v56-1-15,15>>^ Para os que são puros, tudo é puro. Mas, para os corruptos e descrentes, nada é puro, pois têm a mente e a consciência corrompidas.

[[v56-1-16]]

^<<v56-1-16,16>>^ Afirmam que conhecem a Deus, mas o negam por seu modo de viver. São detestáveis e desobedientes, e não servem para fazer nada de bom.

'''

xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[&#60; Capítulo Anterior] | <<v56-1-0,Topo>> | xref:056-tito/056-tito-002.adoc#v56-2-0[Próximo Capítulo &#62;]