include::./index.adoc[]

[[v62-5-0]]
=== 1 João, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v62-5-1]]

^<<v62-5-1,1>>^ Todo aquele que crê que Jesus é o Cristo é nascido de Deus. E todo aquele que ama o Pai também ama os filhos dele.

[[v62-5-2]]

^<<v62-5-2,2>>^ Sabemos que amamos os filhos de Deus se amamos a Deus e obedecemos a seus mandamentos.

[[v62-5-3]]

^<<v62-5-3,3>>^ Amar a Deus significa obedecer a seus mandamentos. E seus mandamentos não são difíceis.

[[v62-5-4]]

^<<v62-5-4,4>>^ Pois todo aquele que é nascido de Deus vence este mundo, e obtemos essa vitória pela fé.

[[v62-5-5]]

^<<v62-5-5,5>>^ Quem vence a batalha contra o mundo? Somente quem crê que Jesus é o Filho de Deus.

[[v62-5-6]]

^<<v62-5-6,6>>^ Jesus Cristo foi revelado por meio de seu batismo na água e pelo derramamento de seu sangue; não só por meio da água, mas pela água e pelo sangue. E o Espírito, que é a verdade, o confirma com seu testemunho.

[[v62-5-7]]

^<<v62-5-7,7>>^ Temos, portanto, três testemunhas,

[[v62-5-8]]

^<<v62-5-8,8>>^ o Espírito, a água e o sangue, e as três concordam entre si.

[[v62-5-9]]

^<<v62-5-9,9>>^ Porque cremos em testemunho humano, certamente podemos crer no testemunho de Deus, que tem ainda mais valor. E Deus dá testemunho acerca de seu Filho.

[[v62-5-10]]

^<<v62-5-10,10>>^ Quem crê no Filho de Deus sabe, em seu coração, que esse testemunho é verdadeiro. Quem não crê nisso, na realidade, chama Deus de mentiroso, porque não crê no testemunho de Deus acerca de seu Filho.

[[v62-5-11]]

^<<v62-5-11,11>>^ E este é o testemunho: Deus nos deu vida eterna, e essa vida está em seu Filho.

[[v62-5-12]]

^<<v62-5-12,12>>^ Quem tem o Filho tem a vida; quem não tem o Filho de Deus não tem a vida.

[[v62-5-13]]

^<<v62-5-13,13>>^ Escrevi estas coisas a vocês que creem no nome do Filho de Deus para que saibam que têm a vida eterna.

[[v62-5-14]]

^<<v62-5-14,14>>^ Estamos certos de que ele nos ouve sempre que lhe pedimos algo conforme sua vontade.

[[v62-5-15]]

^<<v62-5-15,15>>^ E, uma vez que sabemos que ele ouve nossos pedidos, também sabemos que ele nos dará o que pedimos.

[[v62-5-16]]

^<<v62-5-16,16>>^ Se alguém vir um irmão cometer pecado que não leva à morte, ore por ele, e Deus dará vida a esse irmão que pecou de maneira que não leva à morte. Mas há pecado que leva à morte, e não digo que se deva orar por aqueles que o cometem.

[[v62-5-17]]

^<<v62-5-17,17>>^ Toda injustiça é pecado, mas nem todo pecado leva à morte.

[[v62-5-18]]

^<<v62-5-18,18>>^ Sabemos que os nascidos de Deus não vivem no pecado, pois o Filho de Deus os protege e o maligno não os toca.

[[v62-5-19]]

^<<v62-5-19,19>>^ Sabemos que somos filhos de Deus e que o mundo inteiro está sob o controle do maligno.

[[v62-5-20]]

^<<v62-5-20,20>>^ E sabemos que o Filho de Deus veio e nos deu entendimento para que conheçamos ao Deus verdadeiro. Agora, vivemos em comunhão com o Deus verdadeiro, porque vivemos em comunhão com seu Filho, Jesus Cristo. Ele é o Deus verdadeiro e é a vida eterna.

[[v62-5-21]]

^<<v62-5-21,21>>^ Filhinhos, afastem-se dos ídolos.

'''

xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[&#60; Capítulo Anterior] | <<v62-5-0,Topo>> | xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[Próximo Capítulo &#62;]