include::./index.adoc[]

[[v62-3-0]]
=== 1 João, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v62-3-1]]

^<<v62-3-1,1>>^ Vejam como é grande o amor do Pai por nós, pois ele nos chama de filhos, o que de fato somos! Mas quem pertence a este mundo não reconhece que somos filhos de Deus, porque não o conhece.

[[v62-3-2]]

^<<v62-3-2,2>>^ Amados, já somos filhos de Deus, mas ele ainda não nos mostrou o que seremos quando Cristo vier. Sabemos, porém, que seremos semelhantes a ele, pois o veremos como ele realmente é.

[[v62-3-3]]

^<<v62-3-3,3>>^ E todos que têm essa esperança se manterão puros, como ele é puro.

[[v62-3-4]]

^<<v62-3-4,4>>^ Quem vive no pecado transgride a lei, pois todo pecado é contrário à lei.

[[v62-3-5]]

^<<v62-3-5,5>>^ E vocês sabem que ele veio para tirar nossos pecados, e nele não há pecado.

[[v62-3-6]]

^<<v62-3-6,6>>^ Quem permanece nele não continua a pecar. Mas quem continua a pecar não o conhece e não entende quem ele é.

[[v62-3-7]]

^<<v62-3-7,7>>^ Filhinhos, não deixem que ninguém os engane a este respeito: quando uma pessoa faz o que é justo, mostra que é justa, como ele é justo.

[[v62-3-8]]

^<<v62-3-8,8>>^ Mas, quando continua a pecar, mostra que pertence ao diabo, pois o diabo peca desde o início. Por isso o Filho de Deus veio, para destruir as obras do diabo.

[[v62-3-9]]

^<<v62-3-9,9>>^ Aquele que é nascido de Deus não vive no pecado, pois a vida de Deus está nele. Logo, não pode continuar a pecar, pois é nascido de Deus.

[[v62-3-10]]

^<<v62-3-10,10>>^ Assim, podemos identificar quem é filho de Deus e quem é filho do diabo. Quem não pratica a justiça e não ama seus irmãos não pertence a Deus.

[[v62-3-11]]

^<<v62-3-11,11>>^ Esta é a mensagem que vocês ouviram desde o princípio: que amemos uns aos outros.

[[v62-3-12]]

^<<v62-3-12,12>>^ Não sejamos como Caim, que pertencia ao maligno e assassinou seu irmão. E por que o assassinou? Porque Caim praticava o mal, e seu irmão praticava a justiça.

[[v62-3-13]]

^<<v62-3-13,13>>^ Portanto, meus irmãos, não se surpreendam se o mundo os odiar.

[[v62-3-14]]

^<<v62-3-14,14>>^ Se amamos nossos irmãos, significa que passamos da morte para a vida. Mas quem não ama continua morto.

[[v62-3-15]]

^<<v62-3-15,15>>^ Quem odeia seu irmão já é assassino. E vocês sabem que nenhum assassino tem dentro de si a vida eterna.

[[v62-3-16]]

^<<v62-3-16,16>>^ Sabemos o que é o amor porque Jesus deu sua vida por nós. Portanto, também devemos dar nossa vida por nossos irmãos.

[[v62-3-17]]

^<<v62-3-17,17>>^ Se alguém tem recursos suficientes para viver bem e vê um irmão em necessidade, mas não mostra compaixão, como pode estar nele o amor de Deus?

[[v62-3-18]]

^<<v62-3-18,18>>^ Filhinhos, não nos limitemos a dizer que amamos uns aos outros; demonstremos a verdade por meio de nossas ações.

[[v62-3-19]]

^<<v62-3-19,19>>^ Com isso saberemos que pertencemos à verdade, e nos tranquilizaremos quando estivermos diante de Deus.

[[v62-3-20]]

^<<v62-3-20,20>>^ E, ainda que a consciência nos condene, Deus é maior que nossa consciência e sabe todas as coisas.

[[v62-3-21]]

^<<v62-3-21,21>>^ Amados, se a consciência não nos condena, podemos ir a Deus com total confiança

[[v62-3-22]]

^<<v62-3-22,22>>^ e dele receberemos tudo que pedirmos, pois lhe obedecemos e fazemos o que lhe agrada.

[[v62-3-23]]

^<<v62-3-23,23>>^ E este é seu mandamento: que creiamos no nome de seu Filho, Jesus Cristo, e amemos uns aos outros, conforme ele nos ordenou.

[[v62-3-24]]

^<<v62-3-24,24>>^ Aqueles que obedecem a seus mandamentos permanecem nele, e ele permanece neles. E sabemos que ele permanece em nós porque o Espírito que ele nos deu permanece em nós.

'''

xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[&#60; Capítulo Anterior] | <<v62-3-0,Topo>> | xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[Próximo Capítulo &#62;]