include::./index.adoc[]

[[v62-2-0]]
=== 1 João, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v62-2-1]]

^<<v62-2-1,1>>^ Meus filhinhos, escrevo-lhes estas coisas para que vocês não pequem. Se, contudo, alguém pecar, temos um advogado que defende nossa causa diante do Pai: Jesus Cristo, aquele que é justo.

[[v62-2-2]]

^<<v62-2-2,2>>^ Ele mesmo é o sacrifício para o perdão de nossos pecados, e não apenas de nossos pecados, mas dos pecados de todo o mundo.

[[v62-2-3]]

^<<v62-2-3,3>>^ E sabemos que o conhecemos se obedecemos a seus mandamentos.

[[v62-2-4]]

^<<v62-2-4,4>>^ Se alguém diz: "Eu o conheço", mas não obedece a seus mandamentos, é mentiroso e a verdade não está nele.

[[v62-2-5]]

^<<v62-2-5,5>>^ Mas quem obedece à palavra de Deus mostra que o amor que vem dele está se aperfeiçoando em sua vida. Desse modo, sabemos que estamos nele.

[[v62-2-6]]

^<<v62-2-6,6>>^ Quem afirma que permanece nele deve viver como ele viveu.

[[v62-2-7]]

^<<v62-2-7,7>>^ Amados, não lhes escrevo um novo mandamento, mas um antigo, que vocês têm desde o princípio. É a mesma mensagem que ouviram antes.

[[v62-2-8]]

^<<v62-2-8,8>>^ E, no entanto, também é um novo mandamento, cuja verdade ele demonstrou, e vocês também a demonstram. Pois a escuridão está se dissipando, e a verdadeira luz já brilha.

[[v62-2-9]]

^<<v62-2-9,9>>^ Se alguém afirma: "Estou na luz", mas odeia seu irmão, ainda está na escuridão.

[[v62-2-10]]

^<<v62-2-10,10>>^ Quem ama seu irmão permanece na luz e não leva outros a tropeçar.

[[v62-2-11]]

^<<v62-2-11,11>>^ Mas quem odeia seu irmão ainda está na escuridão e anda na escuridão. Não sabe para onde vai, pois a escuridão o cegou.

[[v62-2-12]]

^<<v62-2-12,12>>^ Escrevo a vocês, filhinhos, porque seus pecados foram perdoados pelo nome de Jesus.

[[v62-2-13]]

^<<v62-2-13,13>>^ Escrevo a vocês, pais, porque conhecem aquele que existia desde o princípio. Escrevo a vocês, jovens, porque venceram a batalha contra o maligno.

[[v62-2-14]]

^<<v62-2-14,14>>^ Escrevi a vocês, filhinhos, porque conhecem o Pai. Escrevi a vocês, pais, porque conhecem aquele que existia desde o princípio. Escrevi a vocês, jovens, porque são fortes. A palavra de Deus permanece em seu coração, e vocês venceram o maligno.

[[v62-2-15]]

^<<v62-2-15,15>>^ Não amem este mundo, nem as coisas que ele oferece, pois, quando amam o mundo, o amor do Pai não está em vocês.

[[v62-2-16]]

^<<v62-2-16,16>>^ Porque o mundo oferece apenas o desejo intenso por prazer físico, o desejo intenso por tudo que vemos e o orgulho de nossas realizações e bens. Isso não provém do Pai, mas do mundo.

[[v62-2-17]]

^<<v62-2-17,17>>^ E este mundo passa, e com ele tudo que as pessoas tanto desejam. Mas quem faz o que agrada a Deus vive para sempre.

[[v62-2-18]]

^<<v62-2-18,18>>^ Filhinhos, chegou a hora final. Vocês ouviram que o anticristo está por vir, e muitos anticristos já apareceram. Por isso sabemos que chegou a hora final.

[[v62-2-19]]

^<<v62-2-19,19>>^ Eles saíram de nosso meio, mas, na verdade, nunca foram dos nossos; do contrário, teriam permanecido conosco. Quando saíram, mostraram que não eram dos nossos.

[[v62-2-20]]

^<<v62-2-20,20>>^ Mas vocês não são assim, pois o Santo lhes deu sua unção, e todos vocês conhecem a verdade.

[[v62-2-21]]

^<<v62-2-21,21>>^ Não lhes escrevo porque não conhecem a verdade, mas porque a conhecem e sabem que a verdade não produz mentira alguma.

[[v62-2-22]]

^<<v62-2-22,22>>^ E quem é mentiroso? Aquele que afirma que Jesus não é o Cristo. Quem nega o Pai e o Filho é o anticristo.

[[v62-2-23]]

^<<v62-2-23,23>>^ Aquele que nega o Filho também não tem o Pai. Quem reconhece o Filho tem também o Pai.

[[v62-2-24]]

^<<v62-2-24,24>>^ Portanto, cuidem para que permaneça em vocês o que lhes foi ensinado desde o começo. Se o fizerem, permanecerão em comunhão com o Filho e com o Pai.

[[v62-2-25]]

^<<v62-2-25,25>>^ E, nessa comunhão, desfrutamos a vida eterna que ele nos prometeu.

[[v62-2-26]]

^<<v62-2-26,26>>^ Escrevo estas coisas para adverti-los sobre os que desejam enganá-los.

[[v62-2-27]]

^<<v62-2-27,27>>^ Vocês, porém, receberam dele a unção, e ela permanece em vocês, de modo que não precisam que alguém lhes ensine a verdade. Pois o que a unção lhes ensina é verdade, e não mentira, e é tudo que precisam saber. Portanto, como lhes ensinou a unção, permaneçam nele.

[[v62-2-28]]

^<<v62-2-28,28>>^ Agora, filhinhos, permaneçam nele para que, quando ele voltar, estejamos confiantes e não nos afastemos dele, envergonhados.

[[v62-2-29]]

^<<v62-2-29,29>>^ Porque sabemos que ele é justo, também sabemos que todo o que pratica a justiça é nascido de Deus.

'''

xref:062-1-joao/062-1-joao-001.adoc#v62-1-0[&#60; Capítulo Anterior] | <<v62-2-0,Topo>> | xref:062-1-joao/062-1-joao-003.adoc#v62-3-0[Próximo Capítulo &#62;]