include::./index.adoc[]

[[v62-1-0]]
=== 1 João, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v62-1-1]]

^<<v62-1-1,1>>^ Proclamamos a vocês aquele que existia desde o princípio, aquele que ouvimos e vimos com nossos próprios olhos e tocamos com nossas próprias mãos. Ele é a Palavra da vida.

[[v62-1-2]]

^<<v62-1-2,2>>^ Aquele que é a vida nos foi revelado, e nós o vimos. Agora, testemunhamos e lhes proclamamos que ele é a vida eterna. Ele estava com o Pai e nos foi revelado.

[[v62-1-3]]

^<<v62-1-3,3>>^ Anunciamos-lhes aquilo que nós mesmos vimos e ouvimos, para que tenham comunhão conosco. E nossa comunhão é com o Pai e com seu Filho, Jesus Cristo.

[[v62-1-4]]

^<<v62-1-4,4>>^ Escrevemos estas coisas para que vocês participem plenamente de nossa alegria.

[[v62-1-5]]

^<<v62-1-5,5>>^ Esta é a mensagem que ouvimos dele e que agora lhes transmitimos: Deus é luz, e nele não há escuridão alguma.

[[v62-1-6]]

^<<v62-1-6,6>>^ Portanto, se afirmamos que temos comunhão com ele mas vivemos na escuridão, mentimos e não praticamos a verdade.

[[v62-1-7]]

^<<v62-1-7,7>>^ Mas, se vivemos na luz, como Deus está na luz, temos comunhão uns com os outros, e o sangue de Jesus, seu Filho, nos purifica de todo pecado.

[[v62-1-8]]

^<<v62-1-8,8>>^ Se afirmamos que não temos pecados, enganamos a nós mesmos e não vivemos na verdade.

[[v62-1-9]]

^<<v62-1-9,9>>^ Mas, se confessamos nossos pecados, ele é fiel e justo para perdoar nossos pecados e nos purificar de toda injustiça.

[[v62-1-10]]

^<<v62-1-10,10>>^ Se afirmamos que não pecamos, chamamos Deus de mentiroso e mostramos que não há em nós lugar para sua palavra.

'''

xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[&#60; Capítulo Anterior] | <<v62-1-0,Topo>> | xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[Próximo Capítulo &#62;]