include::./index.adoc[]

[[v16-3-0]]
=== Neemias, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v16-3-1]]

^<<v16-3-1,1>>^ Então o sumo sacerdote Eliasibe e os outros sacerdotes começaram a reconstruir a porta das Ovelhas. Eles a consagraram, colocaram as portas no lugar e reconstruíram o muro até a torre dos Cem, que também consagraram, e até a torre de Hananel.

[[v16-3-2]]

^<<v16-3-2,2>>^ Os habitantes da cidade de Jericó trabalharam ao lado deles, e mais adiante estava Zacur, filho de Inri.

[[v16-3-3]]

^<<v16-3-3,3>>^ A porta do Peixe foi construída pelos filhos de Hassenaá. Colocaram as vigas, levantaram as portas e puseram os ferrolhos e as trancas.

[[v16-3-4]]

^<<v16-3-4,4>>^ Meremote, filho de Urias e neto de Hacoz, consertou o trecho seguinte do muro. Ao seu lado estava Mesulão, filho de Berequias e neto de Mesezabel, e mais adiante, Zadoque, filho de Baaná.

[[v16-3-5]]

^<<v16-3-5,5>>^ Os habitantes de Tecoa consertaram o trecho seguinte, embora seus líderes se recusassem a trabalhar com os supervisores da construção.

[[v16-3-6]]

^<<v16-3-6,6>>^ Os reparos da porta Antiga foram realizados por Joiada, filho de Paseia, e por Mesulão, filho de Besodias. Colocaram as vigas, levantaram as portas e puseram os ferrolhos e as trancas.

[[v16-3-7]]

^<<v16-3-7,7>>^ Ao lado deles estavam Melatias, de Gibeom, Jadom, de Meronote, homens de Gibeom e homens de Mispá, cidades sob a autoridade do governador da província a oeste do rio Eufrates.

[[v16-3-8]]

^<<v16-3-8,8>>^ Uziel, filho de Haraías, ourives de profissão, consertou o trecho seguinte, e mais adiante estava Hananias, fabricante de perfumes. Reconstruíram Jerusalém até o muro Largo.

[[v16-3-9]]

^<<v16-3-9,9>>^ Refaías, filho de Hur, governador de metade do distrito de Jerusalém, trabalhou ao lado deles no muro.

[[v16-3-10]]

^<<v16-3-10,10>>^ No trecho seguinte, Jedaías, filho de Harumafe, consertou o muro em frente de sua própria casa, e ao lado dele estava Hatus, filho de Hasabneias.

[[v16-3-11]]

^<<v16-3-11,11>>^ Em seguida vinham Malquias, filho de Harim, e Hassube, filho de Paate-Moabe, que consertaram outra parte do muro e a torre dos Fornos.

[[v16-3-12]]

^<<v16-3-12,12>>^ Salum, filho de Haloes, e as filhas dele, consertaram o trecho seguinte. Salum era governador da outra metade do distrito de Jerusalém.

[[v16-3-13]]

^<<v16-3-13,13>>^ Os reparos da porta do Vale foram realizados pelos habitantes de Zanoa, sob a liderança de Hanum. Levantaram as portas e puseram os ferrolhos e as trancas. Também consertaram os 450 metros seguintes do muro até a porta do Esterco.

[[v16-3-14]]

^<<v16-3-14,14>>^ Os reparos da porta do Esterco foram realizados por Malquias, filho de Recabe, governador do distrito de Bete-Haquerém. Ele a reconstruiu, levantou as portas e pôs os ferrolhos e as trancas.

[[v16-3-15]]

^<<v16-3-15,15>>^ Os reparos da porta da Fonte foram realizados por Salum, filho de Col-Hozé, governador do distrito de Mispá. Ele a reconstruiu, colocou o telhado, levantou as portas e pôs os ferrolhos e as trancas. Além disso, consertou o muro do tanque de Siloé, perto do jardim do rei, e reconstruiu o muro até os degraus que descem da Cidade de Davi.

[[v16-3-16]]

^<<v16-3-16,16>>^ Ao lado dele estava Neemias, filho de Azbuque, governador de metade do distrito de Bete-Zur. Ele reconstruiu o muro desde o lugar em frente dos túmulos da família de Davi até o reservatório de água e até a Casa dos Guerreiros.

[[v16-3-17]]

^<<v16-3-17,17>>^ Os reparos do trecho seguinte foram realizados por um grupo de levitas que trabalharam sob a supervisão de Reum, filho de Bani. Depois deles vinha Hasabias, governador de metade do distrito de Queila, representando seu distrito.

[[v16-3-18]]

^<<v16-3-18,18>>^ No trecho seguinte trabalharam seus parentes, liderados por Binui, filho de Henadade, governador da outra metade do distrito de Queila.

[[v16-3-19]]

^<<v16-3-19,19>>^ Ézer, filho de Jesua, governador do distrito de Mispá, consertou o trecho seguinte do muro, desde o lugar em frente da subida para a casa das armas até a esquina do muro.

[[v16-3-20]]

^<<v16-3-20,20>>^ Mais adiante, Baruque, filho de Zabai, consertou com grande zelo o trecho desde a esquina do muro até a entrada da casa do sumo sacerdote Eliasibe.

[[v16-3-21]]

^<<v16-3-21,21>>^ Meremote, filho de Urias e neto de Hacoz, reconstruiu o trecho do muro desde a entrada da casa de Eliasibe até o fim da casa.

[[v16-3-22]]

^<<v16-3-22,22>>^ Os reparos do trecho seguinte foram realizados pelos sacerdotes que moravam ao redor da cidade.

[[v16-3-23]]

^<<v16-3-23,23>>^ Ao seu lado, Benjamim e Hassube consertaram o trecho em frente de suas casas, e Azarias, filho de Maaseias e neto de Ananias, consertou o trecho ao lado de sua casa.

[[v16-3-24]]

^<<v16-3-24,24>>^ Em seguida vinha Binui, filho de Henadade, que consertou o trecho desde a casa de Azarias até a esquina do muro.

[[v16-3-25]]

^<<v16-3-25,25>>^ Palal, filho de Uzai, consertou o trecho em frente da esquina do muro e da torre do palácio real, ao lado do pátio da guarda. Ao lado dele estavam Pedaías, filho de Parós,

[[v16-3-26]]

^<<v16-3-26,26>>^ e os servidores do templo que moravam na colina de Ofel, que consertaram o muro até o lugar em frente da porta das Águas, a leste, e da torre do palácio.

[[v16-3-27]]

^<<v16-3-27,27>>^ Mais adiante, os habitantes de Tecoa consertaram outro trecho, desde o lugar em frente da grande torre alta até o muro de Ofel.

[[v16-3-28]]

^<<v16-3-28,28>>^ Os reparos acima da porta dos Cavalos foram realizados pelos sacerdotes; cada um consertou o trecho do muro em frente de sua própria casa.

[[v16-3-29]]

^<<v16-3-29,29>>^ Depois deles, Zadoque, filho de Imer, também consertou o trecho do muro em frente de sua casa. Ao seu lado estava Semaías, filho de Secanias, guarda da porta Oriental.

[[v16-3-30]]

^<<v16-3-30,30>>^ Hananias, filho de Selemias, e Hanum, sexto filho de Zalafe, consertaram o trecho seguinte, enquanto Mesulão, filho de Berequias, consertou o trecho em frente de onde ele morava.

[[v16-3-31]]

^<<v16-3-31,31>>^ Malquias, um dos ourives, consertou o muro até as casas para os servidores do templo e para os negociantes, em frente da porta da Guarda; então continuou o trabalho até a sala superior da esquina.

[[v16-3-32]]

^<<v16-3-32,32>>^ Os outros ourives e negociantes consertaram o muro desde a sala superior da esquina até a porta das Ovelhas.

'''

xref:016-neemias/016-neemias-002.adoc#v16-2-0[&#60; Capítulo Anterior] | <<v16-3-0,Topo>> | xref:016-neemias/016-neemias-004.adoc#v16-4-0[Próximo Capítulo &#62;]