include::./index.adoc[]

[[v16-8-0]]
=== Neemias, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v16-8-1]]

^<<v16-8-1,1>>^ Em outubro, quando os israelitas já haviam se estabelecido em suas cidades, todo o povo se reuniu com um só propósito na praça em frente da porta das Águas. Pediram ao escriba Esdras que trouxesse o Livro da Lei de Moisés, que o SENHOR tinha dado a Israel.

[[v16-8-2]]

^<<v16-8-2,2>>^ Assim, no dia 8 de outubro, o sacerdote Esdras trouxe o Livro da Lei perante a comunidade constituída de homens e mulheres e de todas as crianças com idade suficiente para entender.

[[v16-8-3]]

^<<v16-8-3,3>>^ Ficou de frente para a praça, junto à porta das Águas, desde o amanhecer até o meio-dia, e leu em voz alta para todos que podiam entender. Todo o povo ouviu com atenção a leitura do Livro da Lei.

[[v16-8-4]]

^<<v16-8-4,4>>^ O escriba Esdras estava em pé sobre uma plataforma de madeira feita para a ocasião. À sua direita estavam Matitias, Sema, Anaías, Urias, Hilquias e Maaseias; à sua esquerda, Pedaías, Misael, Malquias, Hasum, Hasbadana, Zacarias e Mesulão.

[[v16-8-5]]

^<<v16-8-5,5>>^ Esdras estava sobre a plataforma, à vista de todo o povo. Quando o viram abrir o Livro da Lei, todos se levantaram.

[[v16-8-6]]

^<<v16-8-6,6>>^ Esdras louvou o SENHOR, o grande Deus, e todo o povo disse: "Amém! Amém!", com as mãos erguidas. Depois, prostraram-se com o rosto no chão e adoraram o SENHOR.

[[v16-8-7]]

^<<v16-8-7,7>>^ Em seguida, os levitas Jesua, Bani, Serebias, Jamim, Acube, Sabetai, Hodias, Maaseias, Quelita, Azarias, Jozabade, Hanã e Pelaías instruíram o povo acerca da Lei, e todos permaneceram em seus lugares.

[[v16-8-8]]

^<<v16-8-8,8>>^ Liam o Livro da Lei de Deus, explicavam com clareza o significado do que era lido e ajudavam o povo a entender cada passagem.

[[v16-8-9]]

^<<v16-8-9,9>>^ Então o governador Neemias, o sacerdote e escriba Esdras e os levitas que instruíam o povo disseram: "Não se lamentem nem chorem num dia como este! Hoje é um dia consagrado ao SENHOR, seu Deus!". Pois todo o povo chorava enquanto ouvia as palavras da Lei.

[[v16-8-10]]

^<<v16-8-10,10>>^ E Neemias prosseguiu: "Vão e comemorem com um banquete de comidas saborosas e bebidas doces e repartam o alimento com aqueles do povo que não prepararam nada. Este é um dia consagrado ao nosso Senhor. Não fiquem tristes, pois a alegria do SENHOR é sua força!".

[[v16-8-11]]

^<<v16-8-11,11>>^ Os levitas também acalmaram o povo, dizendo: "Aquietem-se! Não fiquem tristes! Hoje é um dia santo!".

[[v16-8-12]]

^<<v16-8-12,12>>^ Então o povo saiu para comer e beber numa refeição festiva, para repartir o alimento e celebrar com grande alegria, pois tinham ouvido e entendido as palavras de Deus.

[[v16-8-13]]

^<<v16-8-13,13>>^ No dia 9 de outubro, os chefes de todas as famílias do povo, junto com os sacerdotes e os levitas, reuniram-se com o escriba Esdras para examinar a Lei mais atentamente.

[[v16-8-14]]

^<<v16-8-14,14>>^ Enquanto estudavam a Lei, descobriram que o SENHOR havia ordenado por meio de Moisés que os israelitas morassem em cabanas durante a festa a ser comemorada naquele mês.

[[v16-8-15]]

^<<v16-8-15,15>>^ Ele tinha dito que se devia fazer uma proclamação por todas as suas cidades e em Jerusalém, para que o povo fosse até os montes apanhar ramos de oliveiras cultivadas e oliveiras silvestres, ramos de murtas, de palmeiras e de outras árvores frondosas. Deviam usar esses ramos para construir as cabanas, conforme prescrito pela Lei.

[[v16-8-16]]

^<<v16-8-16,16>>^ O povo saiu, cortou ramos e os usou para construir cabanas nos terraços das casas, nos seus pátios, nos pátios do templo de Deus, na praça junto à porta das Águas e na praça junto à porta de Efraim.

[[v16-8-17]]

^<<v16-8-17,17>>^ Então todos que haviam regressado do cativeiro moraram nessas cabanas durante a festa, e todos estavam cheios de grande alegria. Os israelitas não celebravam a festa dessa maneira desde os dias de Josué, filho de Num.

[[v16-8-18]]

^<<v16-8-18,18>>^ Durante os sete dias da festa, Esdras leu o Livro da Lei de Deus a cada dia. Então, no oitavo dia, realizaram uma reunião solene, conforme prescrito.

'''

xref:016-neemias/016-neemias-007.adoc#v16-7-0[&#60; Capítulo Anterior] | <<v16-8-0,Topo>> | xref:016-neemias/016-neemias-009.adoc#v16-9-0[Próximo Capítulo &#62;]