include::./index.adoc[]

[[v16-12-0]]
=== Neemias, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v16-12-1]]

^<<v16-12-1,1>>^ Os sacerdotes e levitas que regressaram com Zorobabel, filho de Sealtiel, e com Jesua, o sumo sacerdote, foram: Seraías, Jeremias, Esdras,

[[v16-12-2]]

^<<v16-12-2,2>>^ Amarias, Maluque, Hatus,

[[v16-12-3]]

^<<v16-12-3,3>>^ Secanias, Harim, Meremote,

[[v16-12-4]]

^<<v16-12-4,4>>^ Ido, Ginetom, Abias,

[[v16-12-5]]

^<<v16-12-5,5>>^ Miniamim, Moadias, Bilga,

[[v16-12-6]]

^<<v16-12-6,6>>^ Semaías, Joiaribe, Jedaías,

[[v16-12-7]]

^<<v16-12-7,7>>^ Salu, Amoque, Hilquias e Jedaías. Esses foram os líderes dos sacerdotes e seus companheiros nos dias de Jesua.

[[v16-12-8]]

^<<v16-12-8,8>>^ Os levitas que regressaram com eles foram: Jesua, Binui, Cadmiel, Serebias, Judá e também Matanias, que, com seus companheiros, era encarregado dos cânticos de ação de graças.

[[v16-12-9]]

^<<v16-12-9,9>>^ Seus companheiros Baquebuquias e Uni ficavam em frente deles durante o culto.

[[v16-12-10]]

^<<v16-12-10,10>>^ O sumo sacerdote Jesua gerou Joiaquim; Joiaquim gerou Eliasibe; Eliasibe gerou Joiada;

[[v16-12-11]]

^<<v16-12-11,11>>^ Joiada gerou Joanã; Joanã gerou Jadua.

[[v16-12-12]]

^<<v16-12-12,12>>^ Quando Joiaquim era sumo sacerdote, os chefes das famílias dos sacerdotes foram: Meraías, chefe da família de Seraías; Hananias, chefe da família de Jeremias;

[[v16-12-13]]

^<<v16-12-13,13>>^ Mesulão, chefe da família de Esdras; Joanã, chefe da família de Amarias;

[[v16-12-14]]

^<<v16-12-14,14>>^ Jônatas, chefe da família de Maluqui; José, chefe da família de Secanias;

[[v16-12-15]]

^<<v16-12-15,15>>^ Adna, chefe da família de Harim; Helcai, chefe da família de Meremote;

[[v16-12-16]]

^<<v16-12-16,16>>^ Zacarias, chefe da família de Ido; Mesulão, chefe da família de Ginetom;

[[v16-12-17]]

^<<v16-12-17,17>>^ Zicri, chefe da família de Abias; um chefe da família de Miniamin; Piltai, chefe da família de Moadias;

[[v16-12-18]]

^<<v16-12-18,18>>^ Samua, chefe da família de Bilga; Jônatas, chefe da família de Semaías;

[[v16-12-19]]

^<<v16-12-19,19>>^ Matenai, chefe da família de Joiaribe; Uzi, chefe da família de Jedaías;

[[v16-12-20]]

^<<v16-12-20,20>>^ Calai, chefe da família de Salu; Héber, chefe da família de Amoque;

[[v16-12-21]]

^<<v16-12-21,21>>^ Hasabias, chefe da família de Hilquias; Netanel, chefe da família de Jedaías.

[[v16-12-22]]

^<<v16-12-22,22>>^ Nos dias de Eliasibe, Joiada, Joanã e Jadua, manteve-se um registro dos chefes das famílias dos levitas. Durante o reinado de Dario, o persa, manteve-se um registro dos sacerdotes.

[[v16-12-23]]

^<<v16-12-23,23>>^ Até os dias de Joanã, neto de Eliasibe, manteve-se um registro dos chefes das famílias dos levitas no Livro da História .

[[v16-12-24]]

^<<v16-12-24,24>>^ Estes foram os chefes das famílias dos levitas: Hasabias, Serebias, Jesua, Binui, Cadmiel e outros companheiros que ficavam em frente deles durante as cerimônias de louvor e ação de graças; um lado respondia ao outro, conforme ordenado por Davi, homem de Deus.

[[v16-12-25]]

^<<v16-12-25,25>>^ Matanias, Baquebuquias, Obadias, Mesulão, Talmom e Acube eram os guardas das portas encarregados dos depósitos junto às portas.

[[v16-12-26]]

^<<v16-12-26,26>>^ Todos eles serviam nos dias de Joiaquim, filho de Jesua, filho de Jeozadaque, e nos dias do governador Neemias e do sacerdote e escriba Esdras.

[[v16-12-27]]

^<<v16-12-27,27>>^ Para a dedicação do novo muro de Jerusalém, pediu-se que os levitas de toda a terra viessem a Jerusalém para auxiliar nas cerimônias. Deviam participar dessa ocasião alegre com cânticos de ação de graças e com música de címbalos, harpas e liras.

[[v16-12-28]]

^<<v16-12-28,28>>^ Os cantores foram reunidos da região ao redor de Jerusalém e dos povoados dos netofatitas.

[[v16-12-29]]

^<<v16-12-29,29>>^ Também vieram de Bete-Gilgal e das regiões rurais próximas de Geba e de Azmavete, pois os cantores haviam construído seus próprios povoados ao redor de Jerusalém.

[[v16-12-30]]

^<<v16-12-30,30>>^ Primeiro, os sacerdotes e os levitas purificaram a si mesmos; depois, purificaram o povo, as portas e o muro.

[[v16-12-31]]

^<<v16-12-31,31>>^ Eu conduzi os líderes de Judá até o alto do muro e organizei dois grandes coros. Um dos coros foi para o sul pelo alto do muro, até a porta do Esterco.

[[v16-12-32]]

^<<v16-12-32,32>>^ Hosaías e metade dos líderes de Judá seguiram o coro,

[[v16-12-33]]

^<<v16-12-33,33>>^ junto com Azarias, Esdras, Mesulão,

[[v16-12-34]]

^<<v16-12-34,34>>^ Judá, Benjamim, Semaías e Jeremias.

[[v16-12-35]]

^<<v16-12-35,35>>^ Depois deles vinham alguns sacerdotes que tocavam trombetas: Zacarias, filho de Jônatas, filho de Semaías, filho de Matanias, filho de Micaías, filho de Zacur, descendente de Asafe.

[[v16-12-36]]

^<<v16-12-36,36>>^ Os companheiros de Zacarias eram Semaías, Azarel, Milalai, Gilalai, Maai, Natanel, Judá e Hanani. Eles tocavam os instrumentos musicais prescritos por Davi, homem de Deus. O escriba Esdras ia à frente deles.

[[v16-12-37]]

^<<v16-12-37,37>>^ Quando chegaram à porta da Fonte, foram em frente e subiram pelos degraus que levavam até a Cidade de Davi. Passaram pela casa de Davi e, de lá, foram até a porta das Águas, a leste.

[[v16-12-38]]

^<<v16-12-38,38>>^ O segundo coro foi para o norte, no sentido oposto, para encontrar-se com o primeiro coro. Fui com eles e com a outra metade do povo pelo alto do muro, passando pela torre dos Fornos, até o muro Largo,

[[v16-12-39]]

^<<v16-12-39,39>>^ e depois desde a porta de Efraim até a porta Antiga, passando pela porta do Peixe e pela torre de Hananel e prosseguindo até a torre dos Cem. Dali, continuamos para a porta das Ovelhas e paramos junto à porta da Guarda.

[[v16-12-40]]

^<<v16-12-40,40>>^ Os dois corais seguiram, então, para o templo de Deus, onde tomaram seus lugares. Eu fiz o mesmo, junto com os líderes que estavam comigo.

[[v16-12-41]]

^<<v16-12-41,41>>^ Acompanhamos os sacerdotes que tocavam trombetas: Eliaquim, Maaseias, Miniamim, Micaías, Elioenai, Zacarias e Hananias,

[[v16-12-42]]

^<<v16-12-42,42>>^ e os cantores: Maaseias, Semaías, Eleazar, Uzi, Joanã, Malquias, Elão e Ézer. Eles tocavam e cantavam bem alto, sob a direção de Jezraías.

[[v16-12-43]]

^<<v16-12-43,43>>^ Naquele dia alegre, foram oferecidos muitos sacrifícios, pois Deus tinha dado ao povo motivo para se alegrar. As mulheres e as crianças também participaram da celebração, e podia-se ouvir de longe a alegria do povo de Jerusalém.

[[v16-12-44]]

^<<v16-12-44,44>>^ Naquele dia, foram nomeados os homens encarregados dos depósitos para as ofertas e os primeiros frutos da colheita e para os dízimos. Eram responsáveis por recolher dos campos fora das cidades as porções exigidas pela lei para os sacerdotes e os levitas, pois todo o povo estava alegre com os sacerdotes e os levitas e com seu trabalho.

[[v16-12-45]]

^<<v16-12-45,45>>^ Tanto eles como os cantores e os guardas das portas realizavam o serviço de seu Deus e o serviço de purificação, conforme Davi e seu filho Salomão haviam ordenado.

[[v16-12-46]]

^<<v16-12-46,46>>^ O costume de ter regentes do coro para dirigir os hinos de louvor e de ação de graças a Deus havia começado muito tempo antes, nos dias de Davi e Asafe.

[[v16-12-47]]

^<<v16-12-47,47>>^ Por isso, agora, nos dias de Zorobabel e de Neemias, todo o Israel trazia uma provisão diária de alimentos para os cantores, os guardas das portas e os levitas. Os levitas, por sua vez, entregavam uma porção daquilo que recebiam aos sacerdotes, os descendentes de Arão.

'''

xref:016-neemias/016-neemias-011.adoc#v16-11-0[&#60; Capítulo Anterior] | <<v16-12-0,Topo>> | xref:016-neemias/016-neemias-013.adoc#v16-13-0[Próximo Capítulo &#62;]