include::./index.adoc[]

[[v16-5-0]]
=== Neemias, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v16-5-1]]

^<<v16-5-1,1>>^ Por esse tempo, alguns homens e suas esposas fizeram um grande protesto contra seus irmãos judeus.

[[v16-5-2]]

^<<v16-5-2,2>>^ Alguns deles diziam: "Nossas famílias são grandes; precisamos de mais alimento para sobreviver".

[[v16-5-3]]

^<<v16-5-3,3>>^ Outros diziam: "Hipotecamos nossos campos, nossas videiras e nossas casas para conseguir comida durante este período de escassez".

[[v16-5-4]]

^<<v16-5-4,4>>^ Ainda outros diziam: "Tomamos dinheiro emprestado para pagar os impostos do rei sobre nossos campos e vinhedos.

[[v16-5-5]]

^<<v16-5-5,5>>^ Somos da mesma família que os ricos, e nossos filhos são iguais aos filhos deles. Contudo, somos obrigados a vender nossos filhos como escravos só para termos dinheiro suficiente para viver. Já vendemos algumas de nossas filhas, e não há nada que possamos fazer, pois nossos campos e vinhedos agora pertencem a outros".

[[v16-5-6]]

^<<v16-5-6,6>>^ Quando ouvi essas reclamações, fiquei muito indignado.

[[v16-5-7]]

^<<v16-5-7,7>>^ Depois de pensar bem na questão, repreendi os nobres e os oficiais, dizendo: "Vocês estão prejudicando seus próprios irmãos ao cobrar juros quando lhes pedem dinheiro emprestado!". Em seguida, convoquei uma reunião pública para tratar do problema.

[[v16-5-8]]

^<<v16-5-8,8>>^ Na reunião, eu lhes disse: "Temos feito todo o possível para resgatar nossos irmãos judeus que se venderam a estrangeiros, mas agora vocês os vendem de volta à escravidão. Quantas vezes precisaremos resgatá-los?". E eles não tinham nada a dizer em sua defesa.

[[v16-5-9]]

^<<v16-5-9,9>>^ Então prossegui: "O que vocês estão fazendo não é certo! Acaso não deviam andar no temor de nosso Deus, para evitar a zombaria das nações inimigas?

[[v16-5-10]]

^<<v16-5-10,10>>^ Eu, meus irmãos e os homens que trabalham para mim temos emprestado dinheiro e cereal para o povo. Agora, porém, deixemos de cobrar juros!

[[v16-5-11]]

^<<v16-5-11,11>>^ Devolvam-lhes hoje mesmo seus campos, seus vinhedos, seus olivais e suas casas. Devolvam também a centésima parte, os juros que cobraram quando lhes emprestaram dinheiro, cereais, vinho novo e azeite".

[[v16-5-12]]

^<<v16-5-12,12>>^ Eles responderam: "Devolveremos tudo e não exigiremos mais nada do povo. Faremos conforme você diz". Então chamei os sacerdotes e fiz os nobres e os oficiais jurarem que cumpririam sua promessa.

[[v16-5-13]]

^<<v16-5-13,13>>^ Depois, sacudi as dobras de meu manto e disse: "Que Deus assim os sacuda de seus lares e de suas propriedades se vocês não cumprirem o que prometeram! Que fiquem sem absolutamente nada!". Toda a comunidade respondeu: "Amém", e louvaram o SENHOR. E o povo cumpriu o que havia prometido.

[[v16-5-14]]

^<<v16-5-14,14>>^ Durante os doze anos em que fui governador de Judá, do vigésimo ano ao trigésimo segundo ano do reinado do rei Artaxerxes, nem eu nem meus oficiais cobramos o tributo de alimentação ao qual tínhamos direito.

[[v16-5-15]]

^<<v16-5-15,15>>^ Os governadores anteriores, no entanto, haviam colocado cargas pesadas sobre o povo; exigiam uma porção de alimento e de vinho, além de quarenta peças de prata. Até mesmo os oficiais deles se aproveitavam do povo. Mas, por temor a Deus, não agi dessa maneira.

[[v16-5-16]]

^<<v16-5-16,16>>^ Dediquei-me ao trabalho no muro e não adquiri terras. Exigi que todos os meus servos também trabalhassem no muro.

[[v16-5-17]]

^<<v16-5-17,17>>^ Não pedi nada, embora 150 judeus e oficiais comessem com frequência à minha mesa, além de todos os visitantes de outras terras.

[[v16-5-18]]

^<<v16-5-18,18>>^ Os suprimentos pelos quais eu pagava todos os dias eram um boi, seis das melhores ovelhas, e muitas aves. Além disso, a cada dez dias, precisávamos de uma grande quantidade de vinhos de todo tipo. E, no entanto, não cobrei o tributo de alimentação a que o governador tinha direito, pois o trabalho que o povo realizava já representava uma carga pesada.

[[v16-5-19]]

^<<v16-5-19,19>>^ Lembra-te, ó meu Deus, de tudo que tenho feito por este povo, e abençoa-me por isso.

'''

xref:016-neemias/016-neemias-004.adoc#v16-4-0[&#60; Capítulo Anterior] | <<v16-5-0,Topo>> | xref:016-neemias/016-neemias-006.adoc#v16-6-0[Próximo Capítulo &#62;]