include::./index.adoc[]

[[v16-1-0]]
=== Neemias, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v16-1-1]]

^<<v16-1-1,1>>^ Estas são as memórias de Neemias, filho de Hacalias. No mês de quisleu, no vigésimo ano do reinado do rei Artaxerxes, eu estava na fortaleza de Susã.

[[v16-1-2]]

^<<v16-1-2,2>>^ Hanani, um de meus irmãos, veio me visitar com alguns homens que haviam chegado de Judá. Perguntei-lhes a respeito dos judeus que haviam regressado do cativeiro e da situação em Jerusalém.

[[v16-1-3]]

^<<v16-1-3,3>>^ Eles responderam: "As coisas não vão bem para os que regressaram à província de Judá. Eles estão passando por dificuldades e humilhações. O muro de Jerusalém foi derrubado, e suas portas foram destruídas pelo fogo".

[[v16-1-4]]

^<<v16-1-4,4>>^ Quando ouvi isso, sentei-me e chorei. Durante alguns dias, lamentei, jejuei e orei ao Deus dos céus.

[[v16-1-5]]

^<<v16-1-5,5>>^ Então disse: "Ó SENHOR, Deus dos céus, Deus grande e temível, que guardas tua aliança de amor leal para com os que te amam e obedecem a teus mandamentos,

[[v16-1-6]]

^<<v16-1-6,6>>^ ouve minha oração! Olha do alto e vê que oro noite e dia por teu povo, Israel. Confesso que temos pecado contra ti. Sim, minha própria família e eu temos pecado!

[[v16-1-7]]

^<<v16-1-7,7>>^ Temos pecado terrivelmente contra ti. Não temos obedecido a teus mandamentos, decretos e estatutos, que nos deste por meio de teu servo Moisés.

[[v16-1-8]]

^<<v16-1-8,8>>^ "Por favor, lembra-te do que disseste a teu servo Moisés: ‘Se forem infiéis a mim, eu os dispersarei entre as nações,

[[v16-1-9]]

^<<v16-1-9,9>>^ mas, se voltarem para mim e obedecerem a meus mandamentos e viverem de acordo com eles, então, mesmo que estejam exilados nos confins da terra, eu os reunirei e os trarei de volta ao lugar que escolhi para estabelecer meu nome’.

[[v16-1-10]]

^<<v16-1-10,10>>^ "O povo que tu resgataste com teu grande poder e com tua forte mão é teu servo.

[[v16-1-11]]

^<<v16-1-11,11>>^ Ó Senhor, por favor, ouve a oração deste teu servo! Ouve as orações de teus servos que se agradam em te honrar. Peço que me concedas êxito hoje e que o rei me seja favorável". Nesse tempo, eu era copeiro do rei.

'''

xref:015-esdras/015-esdras-010.adoc#v15-10-0[&#60; Capítulo Anterior] | <<v16-1-0,Topo>> | xref:016-neemias/016-neemias-002.adoc#v16-2-0[Próximo Capítulo &#62;]