include::./index.adoc[]

[[v16-2-0]]
=== Neemias, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v16-2-1]]

^<<v16-2-1,1>>^ No mês de nisã, no vigésimo ano do reinado do rei Artaxerxes, eu estava servindo vinho ao rei. Nunca eu tinha estado triste em sua presença.

[[v16-2-2]]

^<<v16-2-2,2>>^ O rei me perguntou: "Por que está com o rosto tão triste? Você não parece doente. Deve estar profundamente angustiado". Fiquei com muito medo,

[[v16-2-3]]

^<<v16-2-3,3>>^ mas respondi: "Que o rei viva para sempre! Como meu rosto não pareceria triste? A cidade onde estão sepultados meus antepassados está em ruínas, e suas portas foram destruídas pelo fogo".

[[v16-2-4]]

^<<v16-2-4,4>>^ "O que você deseja que eu faça?", perguntou o rei. Depois de orar ao Deus dos céus,

[[v16-2-5]]

^<<v16-2-5,5>>^ respondi: "Se lhe parecer bem, e se o rei for favorável a mim, seu servo, peço que me envie a Judá para reconstruir a cidade onde meus antepassados estão sepultados".

[[v16-2-6]]

^<<v16-2-6,6>>^ O rei, com a rainha sentada ao seu lado, perguntou: "Quanto tempo você ficará ausente? Quando voltará?". Respondi ao rei quanto tempo ficaria ausente, e ele atendeu a meu pedido.

[[v16-2-7]]

^<<v16-2-7,7>>^ Disse também: "Se lhe parecer bem, gostaria que o rei me desse cartas para levar aos governadores da província a oeste do rio Eufrates, com instruções para que eles permitam que eu viaje em segurança por seus territórios até chegar a Judá.

[[v16-2-8]]

^<<v16-2-8,8>>^ Peço ainda que o rei me dê uma carta para levar a Asafe, administrador da floresta real, com instruções para que me forneça madeira. Precisarei desse material para as vigas das portas da fortaleza junto ao templo, para o muro da cidade e para minha própria casa". O rei atendeu a esses pedidos, pois a bondosa mão de Deus estava sobre mim.

[[v16-2-9]]

^<<v16-2-9,9>>^ Fui aos governadores da província a oeste do rio Eufrates e lhes entreguei as cartas do rei. Além disso, o rei enviou oficiais do exército e cavaleiros para me protegerem.

[[v16-2-10]]

^<<v16-2-10,10>>^ Mas, quando Sambalate, o horonita, e Tobias, o oficial amonita, souberam de minha chegada, ficaram muito irritados porque alguém veio promover o bem dos israelitas.

[[v16-2-11]]

^<<v16-2-11,11>>^ Assim, cheguei a Jerusalém. Três dias depois,

[[v16-2-12]]

^<<v16-2-12,12>>^ saí discretamente durante a noite, levando comigo uns poucos homens. Não havia contado a ninguém os planos para Jerusalém que Deus tinha colocado em meu coração. Não levamos nenhum animal de carga além daquele que eu montava.

[[v16-2-13]]

^<<v16-2-13,13>>^ Depois que escureceu, saí pela porta do Vale, passei pelo poço do Chacal e fui até a porta do Esterco para inspecionar o muro de Jerusalém, que tinha sido derrubado, e as portas, que haviam sido destruídas pelo fogo.

[[v16-2-14]]

^<<v16-2-14,14>>^ Em seguida, fui à porta da Fonte e ao tanque do Rei, mas, por causa do entulho, não havia espaço para meu animal passar.

[[v16-2-15]]

^<<v16-2-15,15>>^ Por isso, embora ainda estivesse escuro, subi pelo vale de Cedrom e inspecionei os muros ali, antes de voltar e entrar de novo pela porta do Vale.

[[v16-2-16]]

^<<v16-2-16,16>>^ Os oficiais da cidade não sabiam aonde eu tinha ido nem o que estava fazendo, pois não havia contado meus planos a ninguém. Ainda não tinha falado com os líderes judeus: os sacerdotes, os nobres, os oficiais e outros que realizariam o trabalho.

[[v16-2-17]]

^<<v16-2-17,17>>^ Mas, então, eu lhes disse: "Vocês sabem muito bem da terrível situação em que estamos. Jerusalém está em ruínas, e suas portas foram destruídas pelo fogo. Venham, vamos reconstruir o muro de Jerusalém e acabar com essa vergonha!".

[[v16-2-18]]

^<<v16-2-18,18>>^ Então lhes contei como a mão de Deus tinha estado sobre mim e lhes relatei minha conversa com o rei. Eles responderam: "Sim, vamos reconstruir o muro!", e ficaram animados para realizar essa boa obra.

[[v16-2-19]]

^<<v16-2-19,19>>^ Mas, quando Sambalate, o horonita, Tobias, o oficial amonita, e Gesém, o árabe, souberam de nosso plano, zombaram de nós com desprezo e perguntaram: "O que estão fazendo? Estão se rebelando contra o rei?".

[[v16-2-20]]

^<<v16-2-20,20>>^ Eu lhes respondi: "O Deus dos céus nos dará êxito. Nós, seus servos, começaremos a reconstruir este muro. Vocês, porém, não têm nenhuma parte, nenhum direito legal ou histórico sobre Jerusalém".

'''

xref:016-neemias/016-neemias-001.adoc#v16-1-0[&#60; Capítulo Anterior] | <<v16-2-0,Topo>> | xref:016-neemias/016-neemias-003.adoc#v16-3-0[Próximo Capítulo &#62;]