include::./index.adoc[]

[[v16-10-0]]
=== Neemias, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v16-10-1]]

^<<v16-10-1,1>>^ Os que assinaram e selaram o documento foram: O governador Neemias, filho de Hacalias, e Zedequias.

[[v16-10-2]]

^<<v16-10-2,2>>^ Os sacerdotes Seraías, Azarias, Jeremias,

[[v16-10-3]]

^<<v16-10-3,3>>^ Pasur, Amarias, Malquias,

[[v16-10-4]]

^<<v16-10-4,4>>^ Hatus, Sebanias, Maluque,

[[v16-10-5]]

^<<v16-10-5,5>>^ Harim, Meremote, Obadias,

[[v16-10-6]]

^<<v16-10-6,6>>^ Daniel, Ginetom, Baruque,

[[v16-10-7]]

^<<v16-10-7,7>>^ Mesulão, Abias, Miamim,

[[v16-10-8]]

^<<v16-10-8,8>>^ Maazias, Bilgai e Semaías.

[[v16-10-9]]

^<<v16-10-9,9>>^ Os levitas Jesua, filho de Azanias, Binui, dos descendentes de Henadade, Cadmiel,

[[v16-10-10]]

^<<v16-10-10,10>>^ Sebanias, Hodias, Quelita, Pelaías, Hanã,

[[v16-10-11]]

^<<v16-10-11,11>>^ Mica, Reobe, Hasabias,

[[v16-10-12]]

^<<v16-10-12,12>>^ Zacur, Serebias, Sebanias,

[[v16-10-13]]

^<<v16-10-13,13>>^ Hodias, Bani e Beninu.

[[v16-10-14]]

^<<v16-10-14,14>>^ Os líderes do povo Parós, Paate-Moabe, Elão, Zatu, Bani,

[[v16-10-15]]

^<<v16-10-15,15>>^ Buni, Azgade, Bebai,

[[v16-10-16]]

^<<v16-10-16,16>>^ Adonias, Bigvai, Adim,

[[v16-10-17]]

^<<v16-10-17,17>>^ Ater, Ezequias, Azur,

[[v16-10-18]]

^<<v16-10-18,18>>^ Hodias, Hasum, Besai,

[[v16-10-19]]

^<<v16-10-19,19>>^ Harife, Anatote, Nebai,

[[v16-10-20]]

^<<v16-10-20,20>>^ Magpias, Mesulão, Hezir,

[[v16-10-21]]

^<<v16-10-21,21>>^ Mesezabel, Zadoque, Jadua,

[[v16-10-22]]

^<<v16-10-22,22>>^ Pelatias, Hanã, Anaías,

[[v16-10-23]]

^<<v16-10-23,23>>^ Oseias, Hananias, Hassube,

[[v16-10-24]]

^<<v16-10-24,24>>^ Haloes, Pílea, Sobeque,

[[v16-10-25]]

^<<v16-10-25,25>>^ Reum, Hasabná, Maaseias,

[[v16-10-26]]

^<<v16-10-26,26>>^ Aías, Hanã, Anã,

[[v16-10-27]]

^<<v16-10-27,27>>^ Maluque, Harim e Baaná.

[[v16-10-28]]

^<<v16-10-28,28>>^ Então o restante do povo — os sacerdotes, os levitas, os guardas das portas, os cantores, os servidores do templo e todos que haviam se separado dos povos estrangeiros da terra a fim de obedecer à Lei de Deus, na companhia de suas esposas, seus filhos, suas filhas e de todos que tinham idade para entender —

[[v16-10-29]]

^<<v16-10-29,29>>^ uniu-se a seus líderes e assumiu um compromisso solene. Juraram que seriam amaldiçoados se não obedecessem à Lei de Deus, dada por seu servo Moisés, e prometeram obedecer atentamente a todos os mandamentos, estatutos e decretos do SENHOR, nosso Senhor:

[[v16-10-30]]

^<<v16-10-30,30>>^ "Prometemos não permitir que nossas filhas se casem com os habitantes desta terra, nem permitir que as filhas deles se casem com nossos filhos.

[[v16-10-31]]

^<<v16-10-31,31>>^ "Também prometemos que, se os habitantes desta terra trouxerem mercadorias ou cereais para vender no sábado ou em qualquer outro dia santo, não compraremos deles. A cada sete anos, deixaremos a terra descansar e cancelaremos todas as dívidas.

[[v16-10-32]]

^<<v16-10-32,32>>^ "Além disso, prometemos obedecer ao mandamento de pagar o imposto anual de quatro gramas de prata para o serviço do templo de nosso Deus.

[[v16-10-33]]

^<<v16-10-33,33>>^ Esse imposto também será usado para providenciar os pães da presença, as ofertas regulares de cereais e os holocaustos, as ofertas para os sábados, para as celebrações da lua nova e para as festas anuais, as ofertas sagradas e as ofertas pelo pecado para fazer expiação por Israel. Será usado para tudo que for necessário para o trabalho no templo de nosso Deus.

[[v16-10-34]]

^<<v16-10-34,34>>^ "Fizemos um sorteio a fim de definir uma escala anual regular para que as famílias dos sacerdotes, dos levitas e do povo tragam ao templo de nosso Deus a lenha para ser queimada no altar do SENHOR, nosso Deus, conforme prescrito na Lei.

[[v16-10-35]]

^<<v16-10-35,35>>^ "Prometemos trazer anualmente ao templo do SENHOR os primeiros frutos de todas as colheitas, tanto dos produtos da terra como das árvores frutíferas.

[[v16-10-36]]

^<<v16-10-36,36>>^ Concordamos em entregar a Deus nossos filhos mais velhos e as primeiras crias de todos os nossos rebanhos, tanto de bois como de ovelhas, conforme prescrito pela Lei. Nós os apresentaremos aos sacerdotes que ministram no templo de nosso Deus.

[[v16-10-37]]

^<<v16-10-37,37>>^ Armazenaremos os produtos da terra nos depósitos do templo de nosso Deus. Traremos o melhor de nossa farinha e outras ofertas de cereal, o melhor de nossos frutos, de nosso vinho novo e de nosso azeite. Prometemos ainda entregar aos levitas um décimo de tudo que nossa terra produzir, pois são os levitas que recolhem os dízimos em todas as cidades onde trabalhamos.

[[v16-10-38]]

^<<v16-10-38,38>>^ "Um sacerdote descendente de Arão acompanhará os levitas quando receberem esses dízimos. A décima parte de tudo que for recolhido como dízimo será entregue pelos levitas ao templo de nosso Deus e colocada nos depósitos.

[[v16-10-39]]

^<<v16-10-39,39>>^ O povo e os levitas deverão trazer essas ofertas de cereal, de vinho novo e de azeite para os depósitos e colocá-las nos recipientes sagrados perto dos sacerdotes que ali estiverem ministrando, dos guardas das portas e dos cantores. "Prometemos não descuidar do templo de nosso Deus".

'''

xref:016-neemias/016-neemias-009.adoc#v16-9-0[&#60; Capítulo Anterior] | <<v16-10-0,Topo>> | xref:016-neemias/016-neemias-011.adoc#v16-11-0[Próximo Capítulo &#62;]