include::./index.adoc[]

[[v16-6-0]]
=== Neemias, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v16-6-1]]

^<<v16-6-1,1>>^ Sambalate, Tobias, Gesém, o árabe, e o restante de nossos inimigos descobriram que eu havia terminado de reconstruir o muro e que não restavam brechas, embora as portas ainda não tivessem sido colocadas em seus lugares.

[[v16-6-2]]

^<<v16-6-2,2>>^ Então Sambalate e Gesém enviaram uma mensagem pedindo que eu me encontrasse com eles num dos povoados da planície de Ono. Sabendo que eles planejavam me fazer mal,

[[v16-6-3]]

^<<v16-6-3,3>>^ respondi com a seguinte mensagem: "Estou envolvido com uma obra muito importante e não posso ir. Por que eu deveria interromper o trabalho para me encontrar com vocês?".

[[v16-6-4]]

^<<v16-6-4,4>>^ Quatro vezes eles enviaram a mesma mensagem, e cada vez lhes respondi da mesma forma.

[[v16-6-5]]

^<<v16-6-5,5>>^ Na quinta vez, o servo de Sambalate trouxe nas mãos uma carta aberta,

[[v16-6-6]]

^<<v16-6-6,6>>^ que dizia: "Há um boato entre as nações vizinhas, e Gesém o confirma, que você e os judeus planejam se rebelar e, por isso, estão reconstruindo o muro. De acordo com esses relatos, você planeja se tornar o rei deles.

[[v16-6-7]]

^<<v16-6-7,7>>^ Corre a notícia de que você nomeou profetas em Jerusalém para proclamarem a seu respeito: ‘Olhem! Há um rei em Judá!’. "Pode ter certeza de que essa informação chegará ao conhecimento do rei. Sugiro, portanto, que venha conversar comigo".

[[v16-6-8]]

^<<v16-6-8,8>>^ Eu lhe respondi: "Nada do que você diz é verdade. É tudo invenção sua".

[[v16-6-9]]

^<<v16-6-9,9>>^ Estavam apenas tentando nos intimidar e imaginavam que iríamos interromper a obra. Assim, continuei o trabalho com determinação ainda maior.

[[v16-6-10]]

^<<v16-6-10,10>>^ Algum tempo depois, fui visitar Semaías, filho de Delaías e neto de Meetabel, que não podia sair de sua casa. Ele disse: "Vamos nos encontrar no templo de Deus e trancar as portas. Esta noite seus inimigos virão matá-lo".

[[v16-6-11]]

^<<v16-6-11,11>>^ Eu, porém, respondi: "Alguém de minha posição deve fugir do perigo? Alguém como eu deve entrar no templo para salvar a vida? Não farei isso!".

[[v16-6-12]]

^<<v16-6-12,12>>^ Percebi que Deus não tinha falado com Semaías, mas que ele havia sido contratado por Sambalate e Tobias para anunciar essa profecia contra mim.

[[v16-6-13]]

^<<v16-6-13,13>>^ Eles esperavam me intimidar e me fazer pecar. Assim, poderiam me difamar e me desacreditar.

[[v16-6-14]]

^<<v16-6-14,14>>^ Lembra-te, ó meu Deus, de todo mal feito por Tobias e Sambalate. E lembra-te da profetisa Noadia e de todos os outros profetas que tentaram me intimidar.

[[v16-6-15]]

^<<v16-6-15,15>>^ Por fim, no dia 2 de outubro, 52 dias depois de começarmos o trabalho, o muro ficou pronto.

[[v16-6-16]]

^<<v16-6-16,16>>^ Quando nossos inimigos e as nações vizinhas souberam disso, ficaram assustados e sentiram-se humilhados. Perceberam que a obra havia sido realizada com a ajuda de nosso Deus.

[[v16-6-17]]

^<<v16-6-17,17>>^ Durante esses 52 dias, Tobias e os nobres de Judá trocaram várias cartas.

[[v16-6-18]]

^<<v16-6-18,18>>^ Muitos em Judá haviam jurado lealdade a Tobias, pois seu sogro era Secanias, filho de Ará, e seu filho Joanã era casado com a filha de Mesulão, filho de Berequias.

[[v16-6-19]]

^<<v16-6-19,19>>^ Eles sempre me falavam das boas ações de Tobias e lhe contavam tudo que eu dizia. E Tobias continuava a mandar cartas de ameaça para me intimidar.

'''

xref:016-neemias/016-neemias-005.adoc#v16-5-0[&#60; Capítulo Anterior] | <<v16-6-0,Topo>> | xref:016-neemias/016-neemias-007.adoc#v16-7-0[Próximo Capítulo &#62;]