include::./index.adoc[]

[[v4-14-0]]
=== Números, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v4-14-1]]

^<<v4-14-1,1>>^ Então toda a comunidade começou a chorar em voz alta e continuou em prantos a noite toda.

[[v4-14-2]]

^<<v4-14-2,2>>^ Suas vozes se elevaram em grande protesto contra Moisés e Arão. "Ah, se ao menos tivéssemos morrido no Egito, ou mesmo aqui no deserto!", diziam.

[[v4-14-3]]

^<<v4-14-3,3>>^ "Por que o SENHOR está nos levando para essa terra só para morrermos em combate? Nossas esposas e crianças serão capturadas como prisioneiros de guerra! Não seria melhor voltarmos para o Egito?"

[[v4-14-4]]

^<<v4-14-4,4>>^ E disseram uns aos outros: "Vamos escolher um novo líder e voltar para o Egito!".

[[v4-14-5]]

^<<v4-14-5,5>>^ Moisés e Arão se curvaram com o rosto em terra diante de toda a comunidade de Israel.

[[v4-14-6]]

^<<v4-14-6,6>>^ Dois dos homens que tinham feito o reconhecimento da terra, Josué, filho de Num, e Calebe, filho de Jefoné, rasgaram suas roupas

[[v4-14-7]]

^<<v4-14-7,7>>^ e disseram a toda a comunidade de Israel: "A terra da qual fizemos o reconhecimento é muito boa!

[[v4-14-8]]

^<<v4-14-8,8>>^ E, se o SENHOR se agradar de nós, ele nos levará em segurança até ela e a dará a nós. É uma terra que produz leite e mel com fartura.

[[v4-14-9]]

^<<v4-14-9,9>>^ Não se rebelem contra o SENHOR e não tenham medo dos povos da terra. Diante de nós, eles estão indefesos! Não têm quem os proteja, mas o SENHOR está conosco! Não tenham medo deles!".

[[v4-14-10]]

^<<v4-14-10,10>>^ Ainda assim, toda a comunidade começou a falar em apedrejar Josué e Calebe. Então a presença gloriosa do SENHOR apareceu na tenda do encontro a todos os israelitas,

[[v4-14-11]]

^<<v4-14-11,11>>^ e o SENHOR disse a Moisés: "Até quando este povo me tratará com desprezo? Será que nunca confiarão em mim, mesmo depois de todos os sinais que realizei entre eles?

[[v4-14-12]]

^<<v4-14-12,12>>^ Eu os deserdarei e os destruirei com uma praga. Então, farei de você um povo ainda maior e mais poderoso que eles!".

[[v4-14-13]]

^<<v4-14-13,13>>^ Moisés, porém, respondeu ao SENHOR: "O que os egípcios pensarão? Eles sabem muito bem do poder que mostraste ao resgatar o teu povo do meio deles.

[[v4-14-14]]

^<<v4-14-14,14>>^ Os egípcios informarão isso aos habitantes dessa terra, que já ouviram falar que vives entre o teu povo. Sabem, SENHOR, que apareces ao teu povo face a face e que a tua nuvem permanece sobre ele e que vais adiante dele na coluna de nuvem de dia e na coluna de fogo à noite.

[[v4-14-15]]

^<<v4-14-15,15>>^ Se exterminares todo este povo com um só golpe, as nações que ouviram falar de tua fama dirão:

[[v4-14-16]]

^<<v4-14-16,16>>^ ‘O SENHOR não foi capaz de levá-los à terra que jurou lhes dar, por isso os matou no deserto’.

[[v4-14-17]]

^<<v4-14-17,17>>^ "Por favor, Senhor, mostra que o teu poder é tão grande quanto declaraste. Pois disseste:

[[v4-14-18]]

^<<v4-14-18,18>>^ ‘O SENHOR é lento para se irar, é cheio de amor e perdoa todo tipo de pecado e rebeldia. Contudo, não absolve o culpado; traz as consequências do pecado dos pais sobre os filhos até a terceira e quarta geração’.

[[v4-14-19]]

^<<v4-14-19,19>>^ De acordo com o teu grande amor, peço que perdoes os pecados deste povo, como os tens perdoado desde que saíram do Egito".

[[v4-14-20]]

^<<v4-14-20,20>>^ Então o SENHOR disse: "Eu os perdoarei, como você me pediu.

[[v4-14-21]]

^<<v4-14-21,21>>^ Mas, tão certo quanto eu vivo e tão certo quanto a terra está cheia da glória do SENHOR,

[[v4-14-22]]

^<<v4-14-22,22>>^ nenhuma dessas pessoas entrará na terra. Todas elas viram a minha presença gloriosa e os sinais que realizei no Egito e no deserto. Repetidamente, porém, me puseram à prova, recusando-se a ouvir a minha voz.

[[v4-14-23]]

^<<v4-14-23,23>>^ Jamais verão a terra que jurei dar a seus antepassados. Nenhum daqueles que me trataram com desprezo a verá.

[[v4-14-24]]

^<<v4-14-24,24>>^ Meu servo Calebe, no entanto, teve uma atitude diferente dos demais. Permaneceu fiel a mim, por isso eu o farei entrar na terra da qual fez o reconhecimento, e seus descendentes tomarão posse dela.

[[v4-14-25]]

^<<v4-14-25,25>>^ Agora, deem meia-volta e não sigam rumo à terra onde habitam os amalequitas e cananeus. Amanhã partirão para o deserto, em direção ao mar Vermelho".

[[v4-14-26]]

^<<v4-14-26,26>>^ Então o SENHOR disse a Moisés e a Arão:

[[v4-14-27]]

^<<v4-14-27,27>>^ "Até quando precisarei tolerar esta comunidade perversa e suas queixas contra mim? Sim, ouvi as queixas dos israelitas contra mim.

[[v4-14-28]]

^<<v4-14-28,28>>^ Agora, digam-lhes o seguinte: ‘Tão certo quanto eu vivo, declara o SENHOR, farei com vocês exatamente aquilo que os ouvi dizerem.

[[v4-14-29]]

^<<v4-14-29,29>>^ Todos vocês cairão mortos neste deserto! Uma vez que se queixaram contra mim, todos com mais de 20 anos que foram contados no censo morrerão.

[[v4-14-30]]

^<<v4-14-30,30>>^ Não entrarão nem tomarão posse da terra que eu jurei lhes dar, para que nela morassem. As únicas exceções serão Calebe, filho de Jefoné, e Josué, filho de Num.

[[v4-14-31]]

^<<v4-14-31,31>>^ "‘Vocês disseram que seus filhos seriam tomados como prisioneiros de guerra. Pois bem, eu os farei entrar na terra em segurança, e eles desfrutarão daquilo que vocês desprezaram.

[[v4-14-32]]

^<<v4-14-32,32>>^ Mas, quanto a vocês, cairão mortos neste deserto.

[[v4-14-33]]

^<<v4-14-33,33>>^ Seus filhos serão como pastores, andando sem rumo pelo deserto durante quarenta anos. Desse modo, sofrerão a consequência de sua infidelidade, até que o último de vocês morra no deserto.

[[v4-14-34]]

^<<v4-14-34,34>>^ "‘Uma vez que seus espiões passaram quarenta dias fazendo o reconhecimento da terra, vocês andarão sem rumo pelo deserto durante quarenta anos, um ano para cada dia, como punição por sua culpa. Assim, saberão o resultado de se opor a mim’.

[[v4-14-35]]

^<<v4-14-35,35>>^ Eu, o SENHOR, falei! Certamente farei essas coisas a todos os membros da comunidade que conspiraram contra mim. Serão destruídos neste deserto, e aqui morrerão!".

[[v4-14-36]]

^<<v4-14-36,36>>^ Os homens que Moisés tinha enviado para fazer o reconhecimento da terra, aqueles que instigaram a rebelião contra ele com seu relatório negativo,

[[v4-14-37]]

^<<v4-14-37,37>>^ morreram repentinamente de uma praga diante do SENHOR.

[[v4-14-38]]

^<<v4-14-38,38>>^ Dos homens que haviam feito o reconhecimento da terra, apenas Josué e Calebe sobreviveram.

[[v4-14-39]]

^<<v4-14-39,39>>^ Quando Moisés transmitiu essas palavras aos israelitas, eles se encheram de tristeza.

[[v4-14-40]]

^<<v4-14-40,40>>^ No dia seguinte, levantaram-se cedo e subiram em direção ao alto dos montes. "Vamos!", disseram. "Reconhecemos que pecamos, mas agora estamos prontos para entrar na terra que o SENHOR nos prometeu."

[[v4-14-41]]

^<<v4-14-41,41>>^ Moisés, porém, disse: "Por que desobedecem à ordem do SENHOR? Isso não dará certo!

[[v4-14-42]]

^<<v4-14-42,42>>^ Não subam para a terra agora, pois o SENHOR não estará com vocês. Seus inimigos os aniquilarão!

[[v4-14-43]]

^<<v4-14-43,43>>^ Quando enfrentarem os amalequitas e cananeus na batalha, serão massacrados. Porque vocês abandonaram o SENHOR, ele os abandonará".

[[v4-14-44]]

^<<v4-14-44,44>>^ Arrogantemente, os israelitas avançaram até o alto dos montes, apesar de Moisés e a arca da aliança do SENHOR terem ficado no acampamento.

[[v4-14-45]]

^<<v4-14-45,45>>^ Então os amalequitas e cananeus que viviam naqueles montes desceram, derrotaram os israelitas e os perseguiram até Hormá.

'''

xref:004-numeros/004-numeros-013.adoc#v4-13-0[&#60; Capítulo Anterior] | <<v4-14-0,Topo>> | xref:004-numeros/004-numeros-015.adoc#v4-15-0[Próximo Capítulo &#62;]