include::./index.adoc[]

[[v4-4-0]]
=== Números, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v4-4-1]]

^<<v4-4-1,1>>^ Então o SENHOR disse a Moisés e a Arão:

[[v4-4-2]]

^<<v4-4-2,2>>^ "Realizem um censo dos membros dos clãs e das famílias da divisão coatita da tribo de Levi.

[[v4-4-3]]

^<<v4-4-3,3>>^ Façam uma lista de todos os homens de 30 a 50 anos qualificados para servir na tenda do encontro.

[[v4-4-4]]

^<<v4-4-4,4>>^ "Os deveres dos coatitas na tenda do encontro serão relacionados aos objetos mais sagrados.

[[v4-4-5]]

^<<v4-4-5,5>>^ Quando o acampamento se deslocar de um lugar para outro, Arão e seus filhos entrarão primeiro na tenda do encontro para remover a cortina interna e usá-la para cobrir a arca da aliança.

[[v4-4-6]]

^<<v4-4-6,6>>^ Depois, cobrirão a cortina interna com couro fino e, por cima do couro, estenderão uma peça única de pano azul. Por fim, colocarão no devido lugar as varas usadas para transportar a arca.

[[v4-4-7]]

^<<v4-4-7,7>>^ "Em seguida, estenderão um pano azul sobre a mesa onde ficam expostos os pães da presença, e sobre o pano azul colocarão as tigelas, as colheres, as jarras e as vasilhas para as ofertas derramadas e o pão da presença.

[[v4-4-8]]

^<<v4-4-8,8>>^ Sobre tudo isso estenderão um pano vermelho e, por cima dele, uma cobertura de couro fino. Por fim, colocarão no devido lugar as varas usadas para transportar a mesa.

[[v4-4-9]]

^<<v4-4-9,9>>^ "Depois, cobrirão com um pano azul o candelabro, suas lâmpadas, os cortadores de pavio, os apagadores e as vasilhas especiais para o óleo.

[[v4-4-10]]

^<<v4-4-10,10>>^ Cobrirão o candelabro e seus acessórios com couro fino e os colocarão sobre o suporte usado para transportá-los.

[[v4-4-11]]

^<<v4-4-11,11>>^ "Em seguida, estenderão um pano azul sobre o altar de ouro e cobrirão o pano com couro fino. Por fim, colocarão no devido lugar as varas usadas para transportar o altar.

[[v4-4-12]]

^<<v4-4-12,12>>^ Os demais utensílios usados no serviço do santuário serão embrulhados em pano azul, cobertos com couro fino e colocados sobre o suporte usado para transportá-los.

[[v4-4-13]]

^<<v4-4-13,13>>^ "Removerão as cinzas do altar de sacrifícios e o cobrirão com um pano roxo.

[[v4-4-14]]

^<<v4-4-14,14>>^ Colocarão todos os utensílios do altar — os braseiros, os garfos para a carne, as pás, as bacias e todos os recipientes — sobre o pano e os cobrirão com couro fino. Por fim, colocarão no devido lugar as varas usadas para transportar o altar.

[[v4-4-15]]

^<<v4-4-15,15>>^ O acampamento estará pronto para se deslocar quando Arão e seus filhos tiverem terminado de cobrir o santuário e todos os objetos sagrados. Os coatitas virão e transportarão tudo até o lugar de destino. Contudo, não tocarão nos objetos sagrados, pois, se o fizerem, morrerão. Esses são os utensílios da tenda do encontro que os coatitas transportarão.

[[v4-4-16]]

^<<v4-4-16,16>>^ "Eleazar, filho do sacerdote Arão, será responsável pelo óleo usado no candelabro, pelo incenso perfumado, pelas ofertas diárias de cereal e pelo óleo da unção. De fato, será responsável por todo o tabernáculo e tudo que nele há, incluindo o santuário e seus objetos".

[[v4-4-17]]

^<<v4-4-17,17>>^ Então o SENHOR disse a Moisés e a Arão:

[[v4-4-18]]

^<<v4-4-18,18>>^ "Não permitam que os clãs coatitas sejam eliminados do meio dos levitas.

[[v4-4-19]]

^<<v4-4-19,19>>^ Para que eles vivam e não morram quando se aproximarem dos objetos mais sagrados, vocês devem fazer o seguinte: Arão e seus filhos sempre entrarão com os coatitas e dirão a cada um o que deve fazer ou carregar.

[[v4-4-20]]

^<<v4-4-20,20>>^ Os coatitas jamais entrarão para ver os objetos sagrados, nem mesmo por um momento, pois, se o fizerem, morrerão".

[[v4-4-21]]

^<<v4-4-21,21>>^ O SENHOR disse a Moisés:

[[v4-4-22]]

^<<v4-4-22,22>>^ "Realize um censo dos membros dos clãs e das famílias da divisão gersonita da tribo de Levi.

[[v4-4-23]]

^<<v4-4-23,23>>^ Faça uma lista de todos os homens de 30 a 50 anos qualificados para servir na tenda do encontro.

[[v4-4-24]]

^<<v4-4-24,24>>^ "Os clãs gersonitas serão responsáveis pelo serviço geral e pelo transporte de cargas.

[[v4-4-25]]

^<<v4-4-25,25>>^ Levarão as cortinas do tabernáculo, a tenda do encontro com suas coberturas, a cobertura externa de couro fino e a cortina da entrada da tenda do encontro.

[[v4-4-26]]

^<<v4-4-26,26>>^ Levarão também as cortinas divisórias do pátio ao redor do tabernáculo e do altar, a cortina da entrada do pátio, as cordas e todos os objetos relacionados ao seu uso. Os gersonitas são responsáveis por todos esses itens.

[[v4-4-27]]

^<<v4-4-27,27>>^ Arão e seus filhos orientarão os gersonitas a respeito de suas funções, seja o transporte dos objetos ou a execução de outras tarefas. Encarregarão os gersonitas daquilo que devem transportar.

[[v4-4-28]]

^<<v4-4-28,28>>^ Essas são as funções dos clãs gersonitas na tenda do encontro. Prestarão contas de suas responsabilidades diretamente a Itamar, filho do sacerdote Arão."

[[v4-4-29]]

^<<v4-4-29,29>>^ "Registre agora os nomes dos membros dos clãs e das famílias da divisão merarita da tribo de Levi.

[[v4-4-30]]

^<<v4-4-30,30>>^ Faça uma lista de todos os homens de 30 a 50 anos qualificados para servir na tenda do encontro.

[[v4-4-31]]

^<<v4-4-31,31>>^ "Sua única função na tenda do encontro será transportar cargas. Levarão as armações do tabernáculo, os travessões, as colunas e as bases,

[[v4-4-32]]

^<<v4-4-32,32>>^ as colunas das divisórias do pátio com suas bases, estacas e cordas, e todos os utensílios e objetos relacionados ao seu uso. Encarregue cada um, por nome, daquilo que deve transportar.

[[v4-4-33]]

^<<v4-4-33,33>>^ Essa é a função dos clãs meraritas na tenda do encontro. Prestarão contas de sua responsabilidade diretamente a Itamar, filho do sacerdote Arão".

[[v4-4-34]]

^<<v4-4-34,34>>^ Moisés, Arão e os líderes da comunidade fizeram uma lista com os nomes dos membros da divisão coatita de acordo com seus clãs e famílias.

[[v4-4-35]]

^<<v4-4-35,35>>^ A lista incluía todos os homens de 30 a 50 anos qualificados para servir na tenda do encontro,

[[v4-4-36]]

^<<v4-4-36,36>>^ totalizando 2.750, de acordo com seus clãs.

[[v4-4-37]]

^<<v4-4-37,37>>^ Esse foi, portanto, o total dos membros dos clãs coatitas qualificados para servir na tenda do encontro. Moisés e Arão os registraram conforme o SENHOR havia ordenado por meio de Moisés.

[[v4-4-38]]

^<<v4-4-38,38>>^ Fizeram uma lista da divisão gersonita de acordo com seus clãs e famílias.

[[v4-4-39]]

^<<v4-4-39,39>>^ A lista incluía todos os homens de 30 a 50 anos qualificados para servir na tenda do encontro,

[[v4-4-40]]

^<<v4-4-40,40>>^ totalizando 2.630, de acordo com seus clãs e famílias.

[[v4-4-41]]

^<<v4-4-41,41>>^ Esse foi, portanto, o total dos membros dos clãs gersonitas qualificados para servir na tenda do encontro. Moisés e Arão os registraram conforme o SENHOR havia ordenado.

[[v4-4-42]]

^<<v4-4-42,42>>^ Fizeram uma lista da divisão merarita de acordo com seus clãs e famílias.

[[v4-4-43]]

^<<v4-4-43,43>>^ A lista incluía todos os homens de 30 a 50 anos qualificados para servir na tenda do encontro,

[[v4-4-44]]

^<<v4-4-44,44>>^ totalizando 3.200.

[[v4-4-45]]

^<<v4-4-45,45>>^ Esse foi, portanto, o total dos membros dos clãs meraritas. Moisés e Arão os registraram conforme o SENHOR havia ordenado por meio de Moisés.

[[v4-4-46]]

^<<v4-4-46,46>>^ Assim, Moisés, Arão e os líderes de Israel fizeram uma lista de todos os levitas de acordo com seus clãs e famílias.

[[v4-4-47]]

^<<v4-4-47,47>>^ O total de homens de 30 a 50 anos qualificados para servir na tenda do encontro e para transportá-la

[[v4-4-48]]

^<<v4-4-48,48>>^ foi de 8.580.

[[v4-4-49]]

^<<v4-4-49,49>>^ Quando registraram os nomes, conforme o SENHOR havia ordenado, encarregaram cada homem de sua tarefa e lhe disseram o que devia transportar. Desse modo, o registro foi completado, conforme o SENHOR havia ordenado a Moisés.

'''

xref:004-numeros/004-numeros-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numeros/004-numeros-005.adoc#v4-5-0[Próximo Capítulo &#62;]