include::./index.adoc[]

[[v4-22-0]]
=== Números, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v4-22-1]]

^<<v4-22-1,1>>^ Então os israelitas viajaram para as campinas de Moabe e acamparam a leste do rio Jordão, do lado oposto de Jericó.

[[v4-22-2]]

^<<v4-22-2,2>>^ Balaque, filho de Zipor, viu tudo que o povo de Israel havia feito aos amorreus.

[[v4-22-3]]

^<<v4-22-3,3>>^ Quando os moabitas viram como os israelitas eram numerosos, ficaram apavorados.

[[v4-22-4]]

^<<v4-22-4,4>>^ Disseram aos líderes de Midiã: "Essa multidão devorará tudo que estiver à vista, como um boi devora o capim no pasto!". Então Balaque, que era rei de Moabe,

[[v4-22-5]]

^<<v4-22-5,5>>^ enviou mensageiros para chamar Balaão, filho de Beor, que vivia em Petor, sua terra natal, perto do rio Eufrates. Sua mensagem dizia: "Um povo enorme saiu do Egito e cobre a terra, e agora está acampado perto de mim.

[[v4-22-6]]

^<<v4-22-6,6>>^ Venha e amaldiçoe esse povo, pois é poderoso demais para mim. Então, quem sabe, poderei derrotá-lo e expulsá-lo da terra. Sei que bênçãos vêm sobre aqueles que você abençoa, e maldições caem sobre aqueles que você amaldiçoa".

[[v4-22-7]]

^<<v4-22-7,7>>^ Os mensageiros de Balaque, líderes de Moabe e Midiã, partiram levando o valor necessário para pagar Balaão a fim de que ele amaldiçoasse Israel. Chegaram aonde Balaão estava e lhe transmitiram a mensagem de Balaque.

[[v4-22-8]]

^<<v4-22-8,8>>^ "Passem a noite aqui", disse Balaão. "Pela manhã eu lhes direi que orientação recebi do SENHOR." E os oficiais de Moabe permaneceram com Balaão.

[[v4-22-9]]

^<<v4-22-9,9>>^ Naquela noite, Deus veio a Balaão e lhe perguntou: "Quem são seus visitantes?".

[[v4-22-10]]

^<<v4-22-10,10>>^ Balaão respondeu a Deus: "Balaque, filho de Zipor, rei de Moabe, me enviou a seguinte mensagem:

[[v4-22-11]]

^<<v4-22-11,11>>^ ‘Um povo enorme saiu do Egito e cobre a terra. Venha e amaldiçoe esse povo. Então, quem sabe, poderei enfrentá-lo e expulsá-lo da terra’".

[[v4-22-12]]

^<<v4-22-12,12>>^ Mas Deus disse a Balaão: "Não vá com eles nem amaldiçoe esse povo, pois é povo abençoado!".

[[v4-22-13]]

^<<v4-22-13,13>>^ Na manhã seguinte, Balaão se levantou e disse aos oficiais de Balaque: "Voltem para casa! O SENHOR não me permitiu ir com vocês".

[[v4-22-14]]

^<<v4-22-14,14>>^ Os oficiais moabitas voltaram ao rei Balaque e lhe informaram: "Balaão se recusou a vir conosco".

[[v4-22-15]]

^<<v4-22-15,15>>^ Então Balaque fez outra tentativa. Dessa vez, enviou um número maior de oficiais ainda mais importantes que os homens que tinha enviado inicialmente.

[[v4-22-16]]

^<<v4-22-16,16>>^ Eles foram até Balaão e lhe transmitiram a seguinte mensagem: "É isto que diz Balaque, filho de Zipor: Por favor, não se recuse a vir me ajudar.

[[v4-22-17]]

^<<v4-22-17,17>>^ Pagarei muito bem e farei tudo que me pedir. Por favor, venha e amaldiçoe esse povo para mim".

[[v4-22-18]]

^<<v4-22-18,18>>^ Balaão, porém, respondeu aos oficiais de Balaque: "Mesmo que Balaque me desse seu palácio cheio de prata e ouro, eu não poderia fazer coisa alguma, grande ou pequena, contra a vontade do SENHOR, meu Deus.

[[v4-22-19]]

^<<v4-22-19,19>>^ Fiquem, porém, mais esta noite, e eu verei se o SENHOR tem algo mais a me dizer".

[[v4-22-20]]

^<<v4-22-20,20>>^ Naquela noite, Deus veio a Balaão e lhe disse: "Uma vez que estes homens vieram chamá-lo, levante-se e vá com eles. Contudo, faça apenas o que eu mandar".

[[v4-22-21]]

^<<v4-22-21,21>>^ Na manhã seguinte, Balaão se levantou, pôs a sela sobre sua jumenta e partiu com os oficiais moabitas.

[[v4-22-22]]

^<<v4-22-22,22>>^ A ira de Deus se acendeu porque Balaão foi com eles, de modo que enviou o anjo do SENHOR para se pôr no caminho e impedir sua passagem. Enquanto Balaão ia montado na jumenta, acompanhado por dois servos,

[[v4-22-23]]

^<<v4-22-23,23>>^ a jumenta de Balaão viu o anjo do SENHOR em pé no caminho, segurando uma espada. A jumenta se desviou do caminho e saiu para um campo, mas Balaão bateu nela e a fez voltar para o caminho.

[[v4-22-24]]

^<<v4-22-24,24>>^ Então o anjo do SENHOR se pôs num lugar onde o caminho se estreitava, entre os muros de dois vinhedos.

[[v4-22-25]]

^<<v4-22-25,25>>^ Quando a jumenta viu o anjo do SENHOR, tentou passar pelo espaço apertado e espremeu o pé de Balaão contra o muro. Por isso, Balaão bateu nela outra vez.

[[v4-22-26]]

^<<v4-22-26,26>>^ Então o anjo do SENHOR foi mais adiante no caminho e se pôs num lugar estreito demais para a jumenta passar, seja pela direita ou pela esquerda.

[[v4-22-27]]

^<<v4-22-27,27>>^ Quando a jumenta viu o anjo, ela se deitou, apesar de Balaão ainda estar montado. Num ataque de raiva, Balaão a espancou com uma vara.

[[v4-22-28]]

^<<v4-22-28,28>>^ Então o SENHOR fez a jumenta falar. "O que eu lhe fiz para você me bater três vezes?", perguntou ela a Balaão.

[[v4-22-29]]

^<<v4-22-29,29>>^ "Você me fez de tolo!", gritou Balaão. "Se eu tivesse uma espada, mataria você!"

[[v4-22-30]]

^<<v4-22-30,30>>^ "Mas eu sou a mesma jumenta que você montou a vida toda", disse ela. "Alguma vez eu fiz algo parecido?" "Não", respondeu Balaão.

[[v4-22-31]]

^<<v4-22-31,31>>^ Então o SENHOR abriu os olhos de Balaão, e ele viu o anjo do SENHOR em pé no caminho, segurando a espada. Balaão curvou a cabeça e se prostrou diante dele com o rosto em terra.

[[v4-22-32]]

^<<v4-22-32,32>>^ "Por que você bateu três vezes na jumenta?", perguntou o anjo do SENHOR. "Eu vim para impedir sua passagem, pois você insiste em seguir por um caminho que me desagrada.

[[v4-22-33]]

^<<v4-22-33,33>>^ Três vezes a jumenta me viu e se afastou; se ela não tivesse se desviado, certamente eu teria matado você e poupado a vida da jumenta."

[[v4-22-34]]

^<<v4-22-34,34>>^ "Pequei", disse Balaão ao anjo do SENHOR. "Não percebi que estavas no caminho impedindo minha passagem. Se te opões à minha viagem, voltarei para casa."

[[v4-22-35]]

^<<v4-22-35,35>>^ O anjo do SENHOR disse a Balaão: "Vá com os homens, mas fale apenas o que eu lhe disser". Balaão seguiu viagem com os oficiais de Balaque.

[[v4-22-36]]

^<<v4-22-36,36>>^ Quando o rei Balaque soube que Balaão estava a caminho, saiu para se encontrar com ele numa cidade moabita junto ao rio Arnom, na fronteira de seu território.

[[v4-22-37]]

^<<v4-22-37,37>>^ Balaque perguntou a Balaão: "Não mandei chamá-lo com urgência? Por que não veio de imediato? Não acreditou em mim quando eu disse que lhe daria uma grande recompensa?".

[[v4-22-38]]

^<<v4-22-38,38>>^ Balaão respondeu: "Agora estou aqui, mas não posso falar o que bem entender. Transmitirei apenas a mensagem que Deus puser em minha boca".

[[v4-22-39]]

^<<v4-22-39,39>>^ Então Balaão acompanhou Balaque até Quiriate-Huzote.

[[v4-22-40]]

^<<v4-22-40,40>>^ Ali, Balaque sacrificou bois e ovelhas e mandou entregar porções da carne a Balaão e aos oficiais que estavam com ele.

[[v4-22-41]]

^<<v4-22-41,41>>^ Na manhã seguinte, Balaque subiu com Balaão até Bamote-Baal. De lá, podiam ver uma parte do povo.

'''

xref:004-numeros/004-numeros-021.adoc#v4-21-0[&#60; Capítulo Anterior] | <<v4-22-0,Topo>> | xref:004-numeros/004-numeros-023.adoc#v4-23-0[Próximo Capítulo &#62;]