include::./index.adoc[]

[[v4-27-0]]
=== Números, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v4-27-1]]

^<<v4-27-1,1>>^ Certo dia, Maala, Noa, Hogla, Milca e Tirza, as filhas de Zelofeade, fizeram uma petição. Seu pai pertencia a um dos clãs de Manassés, pois era descendente de Héfer, filho de Gileade, filho de Maquir, filho de Manassés, filho de José.

[[v4-27-2]]

^<<v4-27-2,2>>^ Essas mulheres se apresentaram diante de Moisés, do sacerdote Eleazar, dos líderes das tribos e de toda a comunidade à entrada da tenda do encontro e disseram:

[[v4-27-3]]

^<<v4-27-3,3>>^ "Nosso pai morreu no deserto. Não era um dos seguidores de Corá, que se rebelaram contra o SENHOR, mas morreu por causa do seu próprio pecado e não teve filhos.

[[v4-27-4]]

^<<v4-27-4,4>>^ Por que o nome de nosso pai deveria desaparecer de seu clã só porque ele não teve filhos? Dê-nos uma propriedade entre o restante de nossos parentes".

[[v4-27-5]]

^<<v4-27-5,5>>^ Moisés levou o caso ao SENHOR,

[[v4-27-6]]

^<<v4-27-6,6>>^ e o SENHOR respondeu a Moisés:

[[v4-27-7]]

^<<v4-27-7,7>>^ "A reivindicação das filhas de Zelofeade é justa. Dê a elas uma porção de terra entre os parentes de seu pai, a herança que teria sido entregue a seu pai.

[[v4-27-8]]

^<<v4-27-8,8>>^ "Dê as seguintes instruções ao povo de Israel. Se um homem morrer e não deixar filhos, passem a herança às filhas.

[[v4-27-9]]

^<<v4-27-9,9>>^ Se ele também não tiver filhas, transfiram a herança aos irmãos dele.

[[v4-27-10]]

^<<v4-27-10,10>>^ Se ele não tiver irmãos, deem a herança aos irmãos do pai dele.

[[v4-27-11]]

^<<v4-27-11,11>>^ Se seu pai não tiver irmãos, deem a herança ao parente mais próximo de seu clã. Essa é uma prescrição definitiva para os israelitas, conforme o SENHOR ordenou a Moisés".

[[v4-27-12]]

^<<v4-27-12,12>>^ Então o SENHOR disse a Moisés: "Suba a um dos montes de Abarim e olhe para a terra que dou ao povo de Israel.

[[v4-27-13]]

^<<v4-27-13,13>>^ Depois de vê-la, você será reunido a seu povo, como seu irmão Arão,

[[v4-27-14]]

^<<v4-27-14,14>>^ pois vocês desobedeceram às minhas instruções no deserto de Zim. Quando a comunidade se rebelou, vocês não demonstraram minha santidade para eles junto às águas". (Essas águas são as de Meribá, em Cades, no deserto de Zim.)

[[v4-27-15]]

^<<v4-27-15,15>>^ Então Moisés disse ao SENHOR:

[[v4-27-16]]

^<<v4-27-16,16>>^ " SENHOR, tu és o Deus que dá fôlego a todas as criaturas. Por favor, indica um homem para ser o novo líder da comunidade.

[[v4-27-17]]

^<<v4-27-17,17>>^ Dá a eles alguém que os guie aonde quer que forem e os conduza nas batalhas, para que a comunidade do SENHOR não seja como ovelhas sem pastor".

[[v4-27-18]]

^<<v4-27-18,18>>^ O SENHOR respondeu: "Convoque Josué, filho de Num, em quem está o Espírito, e coloque as mãos sobre ele.

[[v4-27-19]]

^<<v4-27-19,19>>^ Apresente-o ao sacerdote Eleazar diante de toda a comunidade e encarregue-o publicamente de liderar.

[[v4-27-20]]

^<<v4-27-20,20>>^ Transfira a ele parte de sua autoridade, para que toda a comunidade de Israel lhe obedeça.

[[v4-27-21]]

^<<v4-27-21,21>>^ Quando for necessário receber orientação do SENHOR, Josué se apresentará diante do sacerdote Eleazar, que usará o Urim perante o SENHOR para determinar sua vontade. É pela palavra de Eleazar que Josué e toda a comunidade de Israel decidirão tudo que devem fazer".

[[v4-27-22]]

^<<v4-27-22,22>>^ Moisés fez o que o SENHOR ordenou. Apresentou Josué ao sacerdote Eleazar e a toda a comunidade,

[[v4-27-23]]

^<<v4-27-23,23>>^ colocou as mãos sobre ele e o encarregou de liderar o povo, exatamente como o SENHOR havia ordenado por meio de Moisés.

'''

xref:004-numeros/004-numeros-026.adoc#v4-26-0[&#60; Capítulo Anterior] | <<v4-27-0,Topo>> | xref:004-numeros/004-numeros-028.adoc#v4-28-0[Próximo Capítulo &#62;]