include::./index.adoc[]

[[v4-5-0]]
=== Números, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v4-5-1]]

^<<v4-5-1,1>>^ O SENHOR disse a Moisés:

[[v4-5-2]]

^<<v4-5-2,2>>^ "Ordene aos israelitas que removam do acampamento todo aquele que sofrer de lepra ou fluxos corporais ou que tiver se tornado cerimonialmente impuro ao tocar num cadáver.

[[v4-5-3]]

^<<v4-5-3,3>>^ Isso se aplica tanto a homens como a mulheres, para que não contaminem seu próprio acampamento, onde eu habito no meio deles".

[[v4-5-4]]

^<<v4-5-4,4>>^ Os israelitas fizeram conforme o SENHOR havia ordenado a Moisés e removeram essas pessoas do acampamento.

[[v4-5-5]]

^<<v4-5-5,5>>^ Então o SENHOR disse a Moisés:

[[v4-5-6]]

^<<v4-5-6,6>>^ "Dê as seguintes instruções ao povo de Israel. Se alguém do povo, homem ou mulher, ofender ao SENHOR prejudicando outra pessoa, será culpado.

[[v4-5-7]]

^<<v4-5-7,7>>^ Confessará seu pecado e pagará indenização completa pelo dano causado, com um acréscimo de um quinto do valor, e entregará o total à pessoa prejudicada.

[[v4-5-8]]

^<<v4-5-8,8>>^ Mas, se a pessoa prejudicada não tiver parentes próximos para receber a indenização, o valor pertencerá ao SENHOR e será entregue ao sacerdote. O culpado também levará um carneiro como sacrifício para fazer expiação por ele.

[[v4-5-9]]

^<<v4-5-9,9>>^ Todas as ofertas sagradas que os israelitas levarem ao sacerdote serão dele.

[[v4-5-10]]

^<<v4-5-10,10>>^ O sacerdote ficará com todas as dádivas sagradas que receber".

[[v4-5-11]]

^<<v4-5-11,11>>^ O SENHOR também disse a Moisés:

[[v4-5-12]]

^<<v4-5-12,12>>^ "Dê as seguintes instruções ao povo de Israel. "Se a esposa de alguém se desviar, for infiel ao marido

[[v4-5-13]]

^<<v4-5-13,13>>^ e tiver relações sexuais com outro homem, sem que o marido ou qualquer outra pessoa fique sabendo, ainda que não haja testemunhas e a esposa não tenha sido pega em flagrante, ela ficará contaminada.

[[v4-5-14]]

^<<v4-5-14,14>>^ Se o marido tiver ciúmes, suspeitar da esposa e precisar saber se ela se contaminou ou não,

[[v4-5-15]]

^<<v4-5-15,15>>^ levará a esposa ao sacerdote. Apresentará em favor dela uma oferta de dois litros de farinha de cevada. Não a misturará com azeite nem incenso, pois é uma oferta pelo ciúme, isto é, uma oferta de testemunho da suspeita, para provar se a mulher é culpada ou não.

[[v4-5-16]]

^<<v4-5-16,16>>^ "O sacerdote a apresentará para ser julgada diante do SENHOR.

[[v4-5-17]]

^<<v4-5-17,17>>^ Numa vasilha de barro, colocará um pouco de água sagrada e a misturará com pó do chão do tabernáculo.

[[v4-5-18]]

^<<v4-5-18,18>>^ Uma vez que o sacerdote tiver apresentado a mulher diante do SENHOR, soltará o cabelo dela e colocará em suas mãos a oferta pelo ciúme como testemunho da suspeita. O sacerdote se colocará diante dela, segurando a vasilha de água amarga que traz maldição sobre os culpados.

[[v4-5-19]]

^<<v4-5-19,19>>^ Em seguida, o sacerdote fará a mulher jurar e lhe dirá: ‘Se nenhum outro homem teve relações sexuais com você, e se você não se desviou nem se contaminou enquanto estava debaixo da autoridade de seu marido, que você permaneça imune aos efeitos desta água amarga que traz a maldição.

[[v4-5-20]]

^<<v4-5-20,20>>^ Mas, se você se desviou sendo infiel a seu marido, e contaminou a si mesma tendo relações sexuais com outro homem…’

[[v4-5-21]]

^<<v4-5-21,21>>^ "Nesse momento, o sacerdote fará a mulher jurar: ‘Que o povo saiba que a maldição do SENHOR está sobre você quando ele a tornar estéril, fizer seu útero encolher e seu abdômen inchar.

[[v4-5-22]]

^<<v4-5-22,22>>^ Que esta água que traz a maldição entre no seu corpo e faça seu abdômen inchar e seu útero encolher’. E a mulher responderá: ‘Amém. Que assim seja’.

[[v4-5-23]]

^<<v4-5-23,23>>^ O sacerdote escreverá essas maldições num pedaço de couro, as raspará de modo que caiam na água amarga,

[[v4-5-24]]

^<<v4-5-24,24>>^ e fará a mulher beber a água amarga que traz a maldição. Se a mulher for culpada, quando a água entrar em seu corpo lhe causará amargo sofrimento.

[[v4-5-25]]

^<<v4-5-25,25>>^ "Em seguida, o sacerdote tirará a oferta pelo ciúme da mão da mulher e a moverá para o alto diante do SENHOR. Depois, levará a oferta até o altar.

[[v4-5-26]]

^<<v4-5-26,26>>^ Tomará um punhado da farinha como oferta simbólica, queimando-a no altar, e exigirá que a mulher beba a água.

[[v4-5-27]]

^<<v4-5-27,27>>^ Se a mulher tiver se contaminado sendo infiel a seu marido, a água que traz a maldição lhe causará amargo sofrimento. Seu abdômen inchará e seu útero encolherá, e ela se tornará maldição entre seu povo.

[[v4-5-28]]

^<<v4-5-28,28>>^ Mas, se ela não tiver se contaminado e estiver pura, não sofrerá castigo e poderá ter filhos.

[[v4-5-29]]

^<<v4-5-29,29>>^ "Essa é a lei ritual para lidar com a suspeita do marido. Se uma esposa se desviar e se contaminar enquanto estiver debaixo da autoridade do marido,

[[v4-5-30]]

^<<v4-5-30,30>>^ ou o marido tiver ciúme e suspeitar que sua esposa foi infiel, ele a apresentará diante do SENHOR, e o sacerdote aplicará em sua totalidade essa lei ritual.

[[v4-5-31]]

^<<v4-5-31,31>>^ O marido será isento de toda a culpa nesse caso, mas a esposa será punida por seu pecado".

'''

xref:004-numeros/004-numeros-004.adoc#v4-4-0[&#60; Capítulo Anterior] | <<v4-5-0,Topo>> | xref:004-numeros/004-numeros-006.adoc#v4-6-0[Próximo Capítulo &#62;]