include::./index.adoc[]

[[v4-16-0]]
=== Números, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v4-16-1]]

^<<v4-16-1,1>>^ Corá, filho de Isar, descendente de Coate, filho de Levi, armou uma conspiração com Datã e Abirão, filhos de Eliabe, e Om, filho de Pelete, da tribo de Rúben.

[[v4-16-2]]

^<<v4-16-2,2>>^ Com outros 250 líderes israelitas, todos membros importantes da comunidade, os três instigaram uma rebelião contra Moisés.

[[v4-16-3]]

^<<v4-16-3,3>>^ Juntaram-se contra Moisés e Arão e disseram: "Vocês foram longe demais! A comunidade foi consagrada pelo SENHOR, e ele está em nosso meio. Que direito vocês têm de agir como se fossem superiores à comunidade do SENHOR?".

[[v4-16-4]]

^<<v4-16-4,4>>^ Quando Moisés ouviu o que disseram, curvou-se com o rosto em terra.

[[v4-16-5]]

^<<v4-16-5,5>>^ Em seguida, disse a Corá e a seus seguidores: "Amanhã cedo o SENHOR nos mostrará quem pertence a ele e quem é consagrado. Só trará à sua presença aqueles que ele escolher.

[[v4-16-6]]

^<<v4-16-6,6>>^ Você, Corá, e todos os seus seguidores, preparem incensários.

[[v4-16-7]]

^<<v4-16-7,7>>^ Amanhã, acendam fogo neles e queimem incenso diante do SENHOR. Então veremos quem o SENHOR escolherá como consagrado a ele. Vocês, levitas, foram longe demais!".

[[v4-16-8]]

^<<v4-16-8,8>>^ Moisés falou novamente a Corá: "Agora ouçam, levitas!

[[v4-16-9]]

^<<v4-16-9,9>>^ Acaso lhes parece de pouca importância que o Deus de Israel os tenha escolhido dentre toda a comunidade de Israel para estar perto dele a fim de trabalharem no tabernáculo do SENHOR e estarem perante a comunidade para servi-la?

[[v4-16-10]]

^<<v4-16-10,10>>^ Ele já deu a você, Corá, e a seus companheiros levitas essa função, e agora exigem também o serviço sacerdotal?

[[v4-16-11]]

^<<v4-16-11,11>>^ Na verdade, é contra o SENHOR que você e seus seguidores estão se rebelando! Afinal, quem é Arão para se queixarem dele?".

[[v4-16-12]]

^<<v4-16-12,12>>^ Então Moisés mandou chamar Datã e Abirão, filhos de Eliabe, mas eles responderam: "Não iremos!

[[v4-16-13]]

^<<v4-16-13,13>>^ Não basta você nos ter tirado do Egito, uma terra que produz leite e mel com fartura, para nos matar aqui no deserto? Agora quer nos tratar como se fosse autoridade sobre nós?

[[v4-16-14]]

^<<v4-16-14,14>>^ Além disso, você não nos levou a outra terra que produz leite e mel com fartura, e não nos deu uma nova propriedade com campos e vinhedos. Está tentando enganar estes homens? Não iremos!".

[[v4-16-15]]

^<<v4-16-15,15>>^ Moisés ficou furioso e disse ao SENHOR: "Não aceites as ofertas de cereais deles! Não tomei deles nem sequer um jumento, e jamais lhes fiz algum mal".

[[v4-16-16]]

^<<v4-16-16,16>>^ E Moisés disse a Corá: "Você e seus seguidores venham aqui amanhã e apresentem-se diante do SENHOR. Arão também virá.

[[v4-16-17]]

^<<v4-16-17,17>>^ Você e cada um de seus 250 seguidores prepararão um incensário e colocarão incenso nele, a fim de apresentá-lo diante do SENHOR. Arão também trará seu incensário".

[[v4-16-18]]

^<<v4-16-18,18>>^ Cada um deles preparou um incensário, acendeu o fogo e colocou incenso nele. Depois, todos se apresentaram à entrada da tenda do encontro com Moisés e Arão.

[[v4-16-19]]

^<<v4-16-19,19>>^ Corá havia instigado toda a comunidade contra Moisés e Arão, e todos se reuniram à entrada da tenda do encontro. Então a presença gloriosa do SENHOR apareceu a toda a comunidade,

[[v4-16-20]]

^<<v4-16-20,20>>^ e o SENHOR disse a Moisés e a Arão:

[[v4-16-21]]

^<<v4-16-21,21>>^ "Afastem-se dessa comunidade, para que eu a destrua agora mesmo!".

[[v4-16-22]]

^<<v4-16-22,22>>^ Moisés e Arão, porém, se prostraram com o rosto em terra e suplicaram. "Ó Deus, tu és aquele que dá fôlego a todas as criaturas. É necessário que fiques irado com toda a comunidade quando somente um homem pecou?".

[[v4-16-23]]

^<<v4-16-23,23>>^ O SENHOR disse a Moisés:

[[v4-16-24]]

^<<v4-16-24,24>>^ "Então diga a toda a comunidade que se afaste das tendas de Corá, Datã e Abirão".

[[v4-16-25]]

^<<v4-16-25,25>>^ Moisés se levantou e foi até as tendas de Datã e Abirão, e as autoridades de Israel o seguiram.

[[v4-16-26]]

^<<v4-16-26,26>>^ "Vamos!", disse ele ao povo. "Afastem-se das tendas destes homens perversos e não toquem em coisa alguma que seja deles. Do contrário, vocês serão destruídos por causa dos pecados deles."

[[v4-16-27]]

^<<v4-16-27,27>>^ Todo o povo se afastou das tendas de Corá, Datã e Abirão, e Datã e Abirão saíram e ficaram em pé à entrada das tendas, junto com suas esposas, seus filhos e suas crianças pequenas.

[[v4-16-28]]

^<<v4-16-28,28>>^ Então Moisés disse: "Assim vocês saberão que o SENHOR me enviou para fazer todas estas coisas que tenho feito, pois não as realizei por minha própria conta.

[[v4-16-29]]

^<<v4-16-29,29>>^ Se estes homens morrerem de causas naturais, ou se nada fora do comum acontecer, então o SENHOR não me enviou.

[[v4-16-30]]

^<<v4-16-30,30>>^ Mas, se o SENHOR fizer algo completamente novo e o chão abrir sua boca e os engolir junto com todos os seus pertences, e eles descerem vivos à sepultura, vocês saberão que estes homens mostraram desprezo pelo SENHOR".

[[v4-16-31]]

^<<v4-16-31,31>>^ Mal ele havia acabado de dizer essas palavras, e o chão debaixo deles rachou.

[[v4-16-32]]

^<<v4-16-32,32>>^ A terra abriu a boca e engoliu os homens, todas as suas famílias, todos os seus seguidores e tudo que possuíam.

[[v4-16-33]]

^<<v4-16-33,33>>^ Desceram vivos à sepultura, junto com todos os seus pertences. A terra se fechou sobre eles, e desapareceram do meio da comunidade.

[[v4-16-34]]

^<<v4-16-34,34>>^ Todo o povo que estava ao redor fugiu quando ouviu os gritos deles. "A terra nos engolirá também!", exclamaram.

[[v4-16-35]]

^<<v4-16-35,35>>^ Em seguida, um fogo ardente saiu do SENHOR e queimou os 250 homens que ofereciam incenso.

[[v4-16-36]]

^<<v4-16-36,36>>^ O SENHOR disse a Moisés:

[[v4-16-37]]

^<<v4-16-37,37>>^ "Ordene a Eleazar, filho do sacerdote Arão, que tire todos os incensários do meio do fogo, pois são santos. Diga-lhe também que espalhe as brasas.

[[v4-16-38]]

^<<v4-16-38,38>>^ Pegue os incensários dos homens que pecaram e pagaram por isso com a própria vida e bata o metal com um martelo, até formar uma lâmina para revestir o altar. Uma vez que esses incensários foram usados na presença do SENHOR, eles se tornaram santos. Que sirvam de advertência para o povo de Israel".

[[v4-16-39]]

^<<v4-16-39,39>>^ O sacerdote Eleazar recolheu os incensários de bronze usados pelos homens que morreram queimados e bateu o metal com um martelo, até formar uma lâmina para revestir o altar.

[[v4-16-40]]

^<<v4-16-40,40>>^ Essa lâmina serviria como recordação aos israelitas; ninguém que não fosse descendente de Arão poderia entrar na presença do SENHOR para queimar incenso. Se alguém o fizesse, aconteceria a ele o mesmo que havia acontecido a Corá e seus seguidores, conforme o SENHOR tinha dito por meio de Moisés.

[[v4-16-41]]

^<<v4-16-41,41>>^ Logo na manhã seguinte, porém, toda a comunidade de Israel começou a se queixar de Moisés e Arão outra vez. "Vocês mataram o povo do SENHOR!", diziam eles.

[[v4-16-42]]

^<<v4-16-42,42>>^ Mas, enquanto se reuniam para protestar contra Moisés e Arão, voltaram-se para a tenda do encontro e viram a nuvem cobri-la, e a presença gloriosa do SENHOR apareceu.

[[v4-16-43]]

^<<v4-16-43,43>>^ Moisés e Arão foram para a frente da tenda do encontro,

[[v4-16-44]]

^<<v4-16-44,44>>^ e o SENHOR disse a Moisés:

[[v4-16-45]]

^<<v4-16-45,45>>^ "Afaste-se desta comunidade, para que eu a destrua agora mesmo!", e Moisés e Arão se prostraram com o rosto em terra.

[[v4-16-46]]

^<<v4-16-46,46>>^ Então Moisés disse a Arão: "Rápido! Pegue um incensário e coloque nele brasas do altar. Acrescente incenso e leve-o para o meio da comunidade, a fim de fazer expiação por ela, pois a ira do SENHOR está acesa, e a praga já começou!".

[[v4-16-47]]

^<<v4-16-47,47>>^ Arão seguiu a ordem de Moisés e correu para o meio da comunidade. A praga já havia começado a matá-los, mas Arão queimou o incenso e fez expiação por eles.

[[v4-16-48]]

^<<v4-16-48,48>>^ Colocou-se entre os mortos e os vivos, e a praga cessou.

[[v4-16-49]]

^<<v4-16-49,49>>^ Ainda assim, 14.700 pessoas morreram da praga, além daqueles que tinham morrido por causa da rebelião de Corá.

[[v4-16-50]]

^<<v4-16-50,50>>^ Uma vez que a praga cessou, Arão voltou a Moisés, que estava à entrada da tenda do encontro.

'''

xref:004-numeros/004-numeros-015.adoc#v4-15-0[&#60; Capítulo Anterior] | <<v4-16-0,Topo>> | xref:004-numeros/004-numeros-017.adoc#v4-17-0[Próximo Capítulo &#62;]