include::./index.adoc[]

[[v4-20-0]]
=== Números, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v4-20-1]]

^<<v4-20-1,1>>^ No primeiro mês do ano, toda a comunidade chegou ao deserto de Zim e acampou em Cades. Enquanto estavam lá, Miriã morreu e foi sepultada.

[[v4-20-2]]

^<<v4-20-2,2>>^ Como não havia água naquele lugar, o povo se rebelou contra Moisés e Arão.

[[v4-20-3]]

^<<v4-20-3,3>>^ Discutiram com Moisés e disseram: "Se ao menos tivéssemos morrido com nossos irmãos diante do SENHOR!

[[v4-20-4]]

^<<v4-20-4,4>>^ Por que vocês trouxeram a comunidade do SENHOR até este deserto? Foi para morrermos, junto com todos os nossos animais?

[[v4-20-5]]

^<<v4-20-5,5>>^ Por que nos obrigaram a sair do Egito e nos trouxeram para este lugar terrível? Esta terra não tem cereais, nem figos, nem uvas, nem romãs, nem água para beber!".

[[v4-20-6]]

^<<v4-20-6,6>>^ Moisés e Arão se afastaram do povo e foram até a frente da tenda do encontro, onde se prostraram com o rosto em terra. Então a presença gloriosa do SENHOR lhes apareceu,

[[v4-20-7]]

^<<v4-20-7,7>>^ e o SENHOR disse a Moisés:

[[v4-20-8]]

^<<v4-20-8,8>>^ "Você e Arão, peguem a vara e reúnam todo o povo. Enquanto eles observam, falem àquela rocha ali, e dela jorrará água. Vocês tirarão água suficiente da rocha para matar a sede de toda a comunidade e de seus animais".

[[v4-20-9]]

^<<v4-20-9,9>>^ Moisés fez conforme o SENHOR havia ordenado. Pegou a vara que ficava guardada diante do SENHOR e,

[[v4-20-10]]

^<<v4-20-10,10>>^ em seguida, ele e Arão mandaram chamar o povo para se reunir em frente da rocha. "Ouçam, seus rebeldes!", gritou Moisés. "Será que é desta rocha que teremos de tirar água para vocês?"

[[v4-20-11]]

^<<v4-20-11,11>>^ Então Moisés levantou a mão e bateu na rocha duas vezes com a vara, e jorrou muita água. Assim, toda a comunidade e todos os seus animais beberam até matar a sede.

[[v4-20-12]]

^<<v4-20-12,12>>^ O SENHOR, porém, disse a Moisés e a Arão: "Uma vez que vocês não confiaram em mim para mostrar minha santidade aos israelitas, não os conduzirão à terra que eu lhes dou!".

[[v4-20-13]]

^<<v4-20-13,13>>^ Por isso aquele lugar ficou conhecido como Meribá, pois ali os israelitas discutiram com o SENHOR, e ali ele mostrou sua santidade entre eles.

[[v4-20-14]]

^<<v4-20-14,14>>^ Enquanto estava em Cades, Moisés enviou representantes ao rei de Edom com a seguinte mensagem: "É isto que dizem seus parentes, o povo de Israel: É de seu conhecimento todas as dificuldades que tivemos.

[[v4-20-15]]

^<<v4-20-15,15>>^ Nossos antepassados desceram ao Egito, onde vivemos por muito tempo. Ali, nós e nossos antepassados fomos maltratados pelos egípcios,

[[v4-20-16]]

^<<v4-20-16,16>>^ mas, quando clamamos ao SENHOR, ele nos ouviu e enviou um anjo que nos tirou do Egito. Agora estamos acampados em Cades, cidade na fronteira de seu território.

[[v4-20-17]]

^<<v4-20-17,17>>^ Pedimos que nos deixe atravessar sua terra. Tomaremos cuidado para não passar por seus campos e vinhedos, e não beberemos água de seus poços. Seguiremos pela estrada real e só a deixaremos quando tivermos atravessado seu território".

[[v4-20-18]]

^<<v4-20-18,18>>^ O rei de Edom, porém, disse: "Fiquem fora do meu território ou irei ao seu encontro com meu exército!".

[[v4-20-19]]

^<<v4-20-19,19>>^ Os israelitas responderam: "Ficaremos na estrada principal. Se nós ou nossos animais bebermos de sua água, pagaremos por ela. Apenas deixe-nos passar por seu território; é só o que pedimos".

[[v4-20-20]]

^<<v4-20-20,20>>^ O rei de Edom retrucou: "Vocês não têm permissão de passar por nossa terra!". Em seguida, mobilizou suas tropas e marchou contra o povo de Israel com um exército poderoso.

[[v4-20-21]]

^<<v4-20-21,21>>^ Uma vez que o povo de Edom se recusou a deixá-los passar por seu território, os israelitas foram obrigados a desviar-se dele.

[[v4-20-22]]

^<<v4-20-22,22>>^ Então toda a comunidade de Israel partiu de Cades e chegou ao monte Hor.

[[v4-20-23]]

^<<v4-20-23,23>>^ Ali, na fronteira com a terra de Edom, o SENHOR disse a Moisés e a Arão:

[[v4-20-24]]

^<<v4-20-24,24>>^ "É chegado o momento de Arão reunir-se a seus antepassados. Não entrará na terra que dou aos israelitas, pois vocês se rebelaram contra minhas instruções a respeito da água em Meribá.

[[v4-20-25]]

^<<v4-20-25,25>>^ Agora, leve Arão e seu filho Eleazar ao monte Hor.

[[v4-20-26]]

^<<v4-20-26,26>>^ Em seguida, tire as roupas sacerdotais de Arão e coloque-as em Eleazar, seu filho. Arão morrerá ali e se reunirá a seus antepassados".

[[v4-20-27]]

^<<v4-20-27,27>>^ Moisés fez conforme o SENHOR lhe ordenou. Os três subiram juntos ao monte Hor, enquanto toda a comunidade observava.

[[v4-20-28]]

^<<v4-20-28,28>>^ No topo, Moisés tirou as roupas sacerdotais de Arão e as colocou em Eleazar, filho de Arão. Então Arão morreu no alto do monte, e Moisés e Eleazar desceram.

[[v4-20-29]]

^<<v4-20-29,29>>^ Quando a comunidade percebeu que Arão havia morrido, todo o povo de Israel lamentou sua morte por trinta dias.

'''

xref:004-numeros/004-numeros-019.adoc#v4-19-0[&#60; Capítulo Anterior] | <<v4-20-0,Topo>> | xref:004-numeros/004-numeros-021.adoc#v4-21-0[Próximo Capítulo &#62;]