include::./index.adoc[]

[[v4-25-0]]
=== Números, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v4-25-1]]

^<<v4-25-1,1>>^ Enquanto estava acampado em Sitim, os homens de Israel começaram a manter relações sexuais com mulheres moabitas da região.

[[v4-25-2]]

^<<v4-25-2,2>>^ Essas mulheres os convidaram para os sacrifícios a seus deuses, e o povo participou da festa e adorou os deuses de Moabe.

[[v4-25-3]]

^<<v4-25-3,3>>^ Assim, os israelitas prestaram culto a Baal em Peor, e a ira do SENHOR se acendeu contra o povo.

[[v4-25-4]]

^<<v4-25-4,4>>^ O SENHOR disse a Moisés: "Prenda todos os chefes do povo e execute-os diante do SENHOR em plena luz do dia, para que sua ira ardente se afaste de Israel".

[[v4-25-5]]

^<<v4-25-5,5>>^ Então Moisés ordenou aos juízes de Israel: "Cada um de vocês executará os homens sob sua autoridade que participaram do culto a Baal em Peor".

[[v4-25-6]]

^<<v4-25-6,6>>^ Nesse momento, enquanto todos choravam à entrada da tenda do encontro, um israelita levou para dentro de sua tenda uma mulher midianita, diante dos olhos de Moisés e de toda a comunidade de Israel.

[[v4-25-7]]

^<<v4-25-7,7>>^ Quando Fineias, filho de Eleazar e neto do sacerdote Arão, viu isso, levantou-se e saiu do meio do povo. Pegou uma lança,

[[v4-25-8]]

^<<v4-25-8,8>>^ correu atrás do homem até o interior de sua tenda e atravessou o corpo do homem e da mulher, na altura do estômago, com um só golpe. Então a praga contra os israelitas cessou.

[[v4-25-9]]

^<<v4-25-9,9>>^ A essa altura, porém, 24 mil pessoas já haviam morrido.

[[v4-25-10]]

^<<v4-25-10,10>>^ Então o SENHOR disse a Moisés:

[[v4-25-11]]

^<<v4-25-11,11>>^ "Fineias, filho de Eleazar e neto do sacerdote Arão, afastou minha ira dos israelitas ao demonstrar tamanho zelo por mim no meio deles, evitando que eu destruísse os israelitas na ira do meu zelo.

[[v4-25-12]]

^<<v4-25-12,12>>^ Agora, diga-lhe que faço com ele minha aliança especial de paz.

[[v4-25-13]]

^<<v4-25-13,13>>^ Por meio dessa aliança, dou a Fineias e a seus descendentes direito permanente ao serviço sacerdotal, pois em seu zelo por mim, seu Deus, ele fez expiação pelo povo de Israel".

[[v4-25-14]]

^<<v4-25-14,14>>^ O homem israelita morto com a mulher midianita se chamava Zinri, filho de Salu, chefe de uma das famílias da tribo de Simeão.

[[v4-25-15]]

^<<v4-25-15,15>>^ A mulher se chamava Cosbi e era filha de Zur, chefe de um clã midianita.

[[v4-25-16]]

^<<v4-25-16,16>>^ O SENHOR disse a Moisés:

[[v4-25-17]]

^<<v4-25-17,17>>^ "Ataque os midianitas e destrua-os,

[[v4-25-18]]

^<<v4-25-18,18>>^ porque eles atacaram vocês, enganando-os no incidente em Peor, e também por causa de Cosbi, filha do chefe midianita, que foi morta durante a praga causada no incidente em Peor".

'''

xref:004-numeros/004-numeros-024.adoc#v4-24-0[&#60; Capítulo Anterior] | <<v4-25-0,Topo>> | xref:004-numeros/004-numeros-026.adoc#v4-26-0[Próximo Capítulo &#62;]