include::./index.adoc[]

[[v4-18-0]]
=== Números, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v4-18-1]]

^<<v4-18-1,1>>^ O SENHOR disse a Arão: "Você, seus filhos e seus parentes da tribo de Levi serão responsabilizados por quaisquer ofensas relacionadas ao santuário. Mas somente você e seus filhos serão responsabilizados por ofensas relacionadas ao serviço sacerdotal.

[[v4-18-2]]

^<<v4-18-2,2>>^ "Traga seus parentes da tribo de Levi, a tribo de seus antepassados, para ajudarem você e seus filhos a cumprir o serviço diante da tenda da aliança.

[[v4-18-3]]

^<<v4-18-3,3>>^ Quando os levitas realizarem as tarefas que lhes foram designadas na tenda, deverão cuidar para que não se aproximem de qualquer dos objetos sagrados nem do altar. Se o fizerem, tanto eles como vocês morrerão.

[[v4-18-4]]

^<<v4-18-4,4>>^ Junto com vocês, os levitas cumprirão as responsabilidades de cuidar da tenda do encontro e trabalhar nela, mas ninguém que não seja autorizado poderá se aproximar.

[[v4-18-5]]

^<<v4-18-5,5>>^ "Vocês se encarregarão pessoalmente do serviço no santuário e no altar, para que minha ira não volte a se acender contra o povo de Israel.

[[v4-18-6]]

^<<v4-18-6,6>>^ Eu mesmo escolhi, dentre todos os israelitas, seus parentes, os levitas, como presente para vocês, consagrados ao SENHOR para o serviço na tenda do encontro.

[[v4-18-7]]

^<<v4-18-7,7>>^ Mas você e seus filhos, os sacerdotes, devem se encarregar pessoalmente de todo o serviço sacerdotal relacionado ao altar e ao que está por trás da cortina interna. Eu lhes dou o serviço sacerdotal como um presente. Qualquer pessoa não autorizada que se aproximar do santuário será morta".

[[v4-18-8]]

^<<v4-18-8,8>>^ O SENHOR disse ainda a Arão: "Eu mesmo o encarreguei de todas as ofertas sagradas que os israelitas trazem a mim. Dou todas essas ofertas consagradas a você e a seus filhos como sua porção permanente.

[[v4-18-9]]

^<<v4-18-9,9>>^ A parte das ofertas santíssimas que não é queimada no fogo é reservada para vocês. Essa porção de todas as ofertas santíssimas trazidas a mim, tanto das ofertas de cereal como das ofertas pelo pecado e das ofertas pela culpa, é santíssima e pertence a você e a seus filhos.

[[v4-18-10]]

^<<v4-18-10,10>>^ Comam-na como oferta santíssima. Todos os sacerdotes a comerão e a considerarão santíssima.

[[v4-18-11]]

^<<v4-18-11,11>>^ "Todas as ofertas sagradas e ofertas movidas que os israelitas apresentarem a mim, movendo-as para o alto diante do altar, também pertencerão a vocês. Eu as dou a você e a seus filhos e filhas como sua porção permanente. Qualquer membro de sua família que estiver cerimonialmente puro comerá dessas ofertas.

[[v4-18-12]]

^<<v4-18-12,12>>^ "Também dou a vocês as primeiras ofertas das colheitas que o povo apresentar ao SENHOR: o melhor do azeite, do vinho novo e dos cereais.

[[v4-18-13]]

^<<v4-18-13,13>>^ Todas as primeiras colheitas da terra que o povo apresentar ao SENHOR pertencem a vocês. Qualquer membro de sua família que estiver cerimonialmente puro comerá desses alimentos.

[[v4-18-14]]

^<<v4-18-14,14>>^ "Tudo que em Israel for consagrado para o SENHOR também pertence a vocês.

[[v4-18-15]]

^<<v4-18-15,15>>^ "O primeiro filho de cada família e a primeira cria de cada animal, oferecidos ao SENHOR, serão seus. Mas o primeiro filho e a primeira cria de animais cerimonialmente impuros serão sempre resgatados.

[[v4-18-16]]

^<<v4-18-16,16>>^ Vocês deverão resgatá-los quando eles tiverem um mês de idade. (O preço do resgate é de cinco peças de prata, com base no siclo do santuário, equivalente a doze gramas cada peça.)

[[v4-18-17]]

^<<v4-18-17,17>>^ "Não deverão resgatar, porém, as primeiras crias das vacas, ovelhas e cabras; elas foram separadas. Aspirja seu sangue sobre o altar e queime a gordura como oferta especial, um aroma agradável ao SENHOR.

[[v4-18-18]]

^<<v4-18-18,18>>^ A carne desses animais pertencerá a vocês, como o peito e a coxa direita que são movidas para o alto como oferta especial diante do altar.

[[v4-18-19]]

^<<v4-18-19,19>>^ Sim, eu dou a você todas essas ofertas sagradas que os israelitas apresentam ao SENHOR. São para você e para seus filhos e filhas, para serem consumidos como sua porção permanente. Essa é uma aliança sem fim e irrevogável entre o SENHOR e você, e também se aplica a seus descendentes".

[[v4-18-20]]

^<<v4-18-20,20>>^ O SENHOR disse mais a Arão: "Vocês, sacerdotes, não receberão herança nem propriedade alguma na terra do povo. Eu sou sua propriedade e sua herança entre os israelitas.

[[v4-18-21]]

^<<v4-18-21,21>>^ Darei aos levitas os dízimos de todo o povo de Israel como herança por seus serviços na tenda do encontro.

[[v4-18-22]]

^<<v4-18-22,22>>^ "De agora em diante, nenhum israelita se aproximará da tenda do encontro. Se alguém se aproximar, será declarado culpado e morrerá.

[[v4-18-23]]

^<<v4-18-23,23>>^ Somente os levitas servirão na tenda do encontro, e serão responsabilizados por quaisquer ofensas contra ela. Essa é uma lei permanente para vocês, a ser cumprida de geração em geração. Os levitas não herdarão porção alguma de terra entre os israelitas,

[[v4-18-24]]

^<<v4-18-24,24>>^ pois eu lhes dou os dízimos dos israelitas, apresentados como ofertas para o SENHOR. Essa será a herança dos levitas. Por isso eu disse que eles não herdariam terra alguma entre os israelitas".

[[v4-18-25]]

^<<v4-18-25,25>>^ O SENHOR disse ainda a Moisés:

[[v4-18-26]]

^<<v4-18-26,26>>^ "Dê as seguintes instruções aos levitas. Quando receberem dos israelitas os dízimos que eu dou a vocês como sua herança, entreguem a décima parte deles — um dízimo dos dízimos — ao SENHOR como oferta.

[[v4-18-27]]

^<<v4-18-27,27>>^ Essa será considerada sua oferta das colheitas, como se fosse o primeiro cereal de sua eira ou do vinho de sua prensa de uvas.

[[v4-18-28]]

^<<v4-18-28,28>>^ Apresentem a décima parte do dízimo recebido dos israelitas como oferta para o SENHOR. Essa é a porção sagrada do SENHOR, e vocês devem apresentá-la ao sacerdote Arão.

[[v4-18-29]]

^<<v4-18-29,29>>^ Entreguem ao SENHOR as melhores porções de todas as ofertas sagradas que receberem.

[[v4-18-30]]

^<<v4-18-30,30>>^ "Dê também as seguintes instruções aos levitas. Quando apresentarem a melhor parte como sua oferta, ela será considerada como se tivesse vindo de sua própria eira ou de sua prensa de uvas.

[[v4-18-31]]

^<<v4-18-31,31>>^ Vocês e suas famílias comerão desse alimento onde quiserem, pois é a recompensa por seu serviço na tenda do encontro.

[[v4-18-32]]

^<<v4-18-32,32>>^ Não serão considerados culpados por aceitarem os dízimos, desde que entreguem a melhor porção aos sacerdotes. Mas tomem cuidado para não tratar as ofertas sagradas dos israelitas como se fosse algo qualquer. Se o fizerem, morrerão".

'''

xref:004-numeros/004-numeros-017.adoc#v4-17-0[&#60; Capítulo Anterior] | <<v4-18-0,Topo>> | xref:004-numeros/004-numeros-019.adoc#v4-19-0[Próximo Capítulo &#62;]