include::./index.adoc[]

[[v4-26-0]]
=== Números, 26
// nvt ?, NVT - Nova Versão Transformadora

[[v4-26-1]]

^<<v4-26-1,1>>^ Depois que a praga cessou, o SENHOR disse a Moisés e a Eleazar, filho do sacerdote Arão:

[[v4-26-2]]

^<<v4-26-2,2>>^ "Realizem um censo de toda a comunidade de Israel, de acordo com suas famílias. Façam uma lista de todos os homens de 20 anos para cima, aptos para irem à guerra".

[[v4-26-3]]

^<<v4-26-3,3>>^ Portanto, ali nas campinas de Moabe, junto ao rio Jordão e do lado oposto de Jericó, Moisés e o sacerdote Eleazar deram as seguintes instruções aos líderes de Israel:

[[v4-26-4]]

^<<v4-26-4,4>>^ "Façam uma lista de todos os homens de Israel de 20 anos para cima, conforme o SENHOR ordenou a Moisés". Este é o registro dos israelitas que saíram do Egito.

[[v4-26-5]]

^<<v4-26-5,5>>^ Estes foram os clãs descendentes dos filhos de Rúben, o filho mais velho de Jacó: O clã enoquita, assim chamado por causa de seu antepassado Enoque. O clã paluíta, assim chamado por causa de seu antepassado Palu.

[[v4-26-6]]

^<<v4-26-6,6>>^ O clã hezronita, assim chamado por causa de seu antepassado Hezrom. O clã carmita, assim chamado por causa de seu antepassado Carmi.

[[v4-26-7]]

^<<v4-26-7,7>>^ Esses foram os clãs de Rúben, que totalizaram 43.730 homens registrados.

[[v4-26-8]]

^<<v4-26-8,8>>^ Palu foi antepassado de Eliabe,

[[v4-26-9]]

^<<v4-26-9,9>>^ e Eliabe foi o pai de Nemuel, Datã e Abirão. Datã e Abirão foram os mesmos líderes da comunidade que conspiraram contra Moisés e Arão e, com os seguidores de Corá, se rebelaram contra o SENHOR.

[[v4-26-10]]

^<<v4-26-10,10>>^ Contudo, a terra abriu sua boca e os engoliu juntamente com Corá, e o fogo devorou 250 de seus seguidores. Isso serviu de advertência a todo o povo.

[[v4-26-11]]

^<<v4-26-11,11>>^ A descendência de Corá, porém, não desapareceu por completo.

[[v4-26-12]]

^<<v4-26-12,12>>^ Estes foram os clãs descendentes dos filhos de Simeão: O clã jemuelita, assim chamado por causa de seu antepassado Jemuel. O clã jaminita, assim chamado por causa de seu antepassado Jamim. O clã jaquinita, assim chamado por causa de seu antepassado Jaquim.

[[v4-26-13]]

^<<v4-26-13,13>>^ O clã zoarita, assim chamado por causa de seu antepassado Zoar. O clã saulita, assim chamado por causa de seu antepassado Saul.

[[v4-26-14]]

^<<v4-26-14,14>>^ Esses foram os clãs de Simeão, que totalizaram 22.200 homens registrados.

[[v4-26-15]]

^<<v4-26-15,15>>^ Estes foram os clãs descendentes dos filhos de Gade: O clã zefonita, assim chamado por causa de seu antepassado Zefom. O clã hagita, assim chamado por causa de seu antepassado Hagi. O clã sunita, assim chamado por causa de seu antepassado Suni.

[[v4-26-16]]

^<<v4-26-16,16>>^ O clã oznita, assim chamado por causa de seu antepassado Ozni. O clã erita, assim chamado por causa de seu antepassado Eri.

[[v4-26-17]]

^<<v4-26-17,17>>^ O clã arodita, assim chamado por causa de seu antepassado Arodi. O clã arelita, assim chamado por causa de seu antepassado Areli.

[[v4-26-18]]

^<<v4-26-18,18>>^ Esses foram os clãs de Gade, que totalizaram 40.500 homens registrados.

[[v4-26-19]]

^<<v4-26-19,19>>^ Judá teve dois filhos, Er e Onã, que morreram na terra de Canaã.

[[v4-26-20]]

^<<v4-26-20,20>>^ Estes foram os clãs descendentes dos filhos sobreviventes de Judá: O clã selanita, assim chamado por causa de seu antepassado Selá. O clã perezita, assim chamado por causa de seu antepassado Perez. O clã zeraíta, assim chamado por causa de seu antepassado Zerá.

[[v4-26-21]]

^<<v4-26-21,21>>^ Estas foram as subdivisões dos descendentes dos perezitas: O clã hezronita, assim chamado por causa de seu antepassado Hezrom. O clã hamulita, assim chamado por causa de seu antepassado Hamul.

[[v4-26-22]]

^<<v4-26-22,22>>^ Esses foram os clãs de Judá, que totalizaram 76.500 homens registrados.

[[v4-26-23]]

^<<v4-26-23,23>>^ Estes foram os clãs descendentes dos filhos de Issacar: O clã tolaíta, assim chamado por causa de seu antepassado Tolá. O clã puíta, assim chamado por causa de seu antepassado Puá.

[[v4-26-24]]

^<<v4-26-24,24>>^ O clã jasubita, assim chamado por causa de seu antepassado Jasube. O clã sinromita, assim chamado por causa de seu antepassado Sinrom.

[[v4-26-25]]

^<<v4-26-25,25>>^ Esses foram os clãs de Issacar, que totalizaram 64.300 homens registrados.

[[v4-26-26]]

^<<v4-26-26,26>>^ Estes foram os clãs descendentes dos filhos de Zebulom: O clã seredita, assim chamado por causa de seu antepassado Serede. O clã elonita, assim chamado por causa de seu antepassado Elom. O clã jaleelita, assim chamado por causa de seu antepassado Jaleel.

[[v4-26-27]]

^<<v4-26-27,27>>^ Esses foram os clãs de Zebulom, que totalizaram 60.500 homens registrados.

[[v4-26-28]]

^<<v4-26-28,28>>^ Os clãs de José descenderam de seus dois filhos, Manassés e Efraim.

[[v4-26-29]]

^<<v4-26-29,29>>^ Estes foram os clãs descendentes de Manassés: O clã maquirita, assim chamado por causa de seu antepassado Maquir. O clã gileadita, assim chamado por causa de seu antepassado Gileade, filho de Maquir.

[[v4-26-30]]

^<<v4-26-30,30>>^ Estas foram as subdivisões de descendentes dos gileaditas: O clã jezerita, assim chamado por causa de seu antepassado Jezer. O clã helequita, assim chamado por causa de seu antepassado Heleque.

[[v4-26-31]]

^<<v4-26-31,31>>^ O clã asrielita, assim chamado por causa de seu antepassado Asriel. O clã siquemita, assim chamado por causa de seu antepassado Siquém.

[[v4-26-32]]

^<<v4-26-32,32>>^ O clã semidaíta, assim chamado por causa de seu antepassado Semida. O clã heferita, assim chamado por causa de seu antepassado Héfer.

[[v4-26-33]]

^<<v4-26-33,33>>^ (Zelofeade, um dos descendentes de Héfer, não teve filhos, mas suas filhas se chamavam Maala, Noa, Hogla, Milca e Tirza.)

[[v4-26-34]]

^<<v4-26-34,34>>^ Esses foram os clãs de Manassés, que totalizaram 52.700 homens registrados.

[[v4-26-35]]

^<<v4-26-35,35>>^ Estes foram os clãs descendentes dos filhos de Efraim: O clã sutelaíta, assim chamado por causa de seu antepassado Sutela. O clã bequerita, assim chamado por causa de seu antepassado Bequer. O clã taanita, assim chamado por causa de seu antepassado Taã.

[[v4-26-36]]

^<<v4-26-36,36>>^ Esta foi a subdivisão de descendentes dos sutelaítas: O clã eranita, assim chamado por causa de seu antepassado Erã.

[[v4-26-37]]

^<<v4-26-37,37>>^ Esses foram os clãs de Efraim, que totalizaram 32.500 homens registrados. Esses foram os descendentes de José, segundo seus clãs.

[[v4-26-38]]

^<<v4-26-38,38>>^ Estes foram os clãs descendentes dos filhos de Benjamim: O clã belaíta, assim chamado por causa de seu antepassado Belá. O clã asbelita, assim chamado por causa de seu antepassado Asbel. O clã airamita, assim chamado por causa de seu antepassado Airã.

[[v4-26-39]]

^<<v4-26-39,39>>^ O clã sufamita, assim chamado por causa de seu antepassado Sufã. O clã hufamita, assim chamado por causa de seu antepassado Hufã.

[[v4-26-40]]

^<<v4-26-40,40>>^ Estas foram as subdivisões de descendentes dos belaítas: O clã ardita, assim chamado por causa de seu antepassado Arde. O clã naamanita, assim chamado por causa de seu antepassado Naamã.

[[v4-26-41]]

^<<v4-26-41,41>>^ Esses foram os clãs de Benjamim, que totalizaram 45.600 homens registrados.

[[v4-26-42]]

^<<v4-26-42,42>>^ Estes foram os clãs descendentes dos filhos de Dã: O clã suamita, assim chamado por causa de seu antepassado Suã.

[[v4-26-43]]

^<<v4-26-43,43>>^ Esses foram os clãs suamitas de Dã, que totalizaram 64.400 homens registrados.

[[v4-26-44]]

^<<v4-26-44,44>>^ Estes foram os clãs descendentes dos filhos de Aser: O clã imnaíta, assim chamado por causa de seu antepassado Imna. O clã isvita, assim chamado por causa de seu antepassado Isvi. O clã beriaíta, assim chamado por causa de seu antepassado Berias.

[[v4-26-45]]

^<<v4-26-45,45>>^ Estas foram as subdivisões de descendentes dos beriaítas: O clã heberita, assim chamado por causa de seu antepassado Héber. O clã malquielita, assim chamado por causa de seu antepassado Malquiel.

[[v4-26-46]]

^<<v4-26-46,46>>^ Aser teve uma filha chamada Sera.

[[v4-26-47]]

^<<v4-26-47,47>>^ Esses foram os clãs de Aser, que totalizaram 53.400 homens registrados.

[[v4-26-48]]

^<<v4-26-48,48>>^ Estes foram os clãs descendentes dos filhos de Naftali: O clã jazeelita, assim chamado por causa de seu antepassado Jazeel. O clã gunita, assim chamado por causa de seu antepassado Guni.

[[v4-26-49]]

^<<v4-26-49,49>>^ O clã jezerita, assim chamado por causa de seu antepassado Jezer. O clã silemita, assim chamado por causa de seu antepassado Silém.

[[v4-26-50]]

^<<v4-26-50,50>>^ Esses foram os clãs de Naftali, que totalizaram 45.400 homens registrados.

[[v4-26-51]]

^<<v4-26-51,51>>^ Os homens registrados em Israel totalizaram 601.730.

[[v4-26-52]]

^<<v4-26-52,52>>^ Então o SENHOR disse a Moisés:

[[v4-26-53]]

^<<v4-26-53,53>>^ "Divida a terra entre as tribos e distribua as porções de terra de acordo com o número de nomes registrados na lista.

[[v4-26-54]]

^<<v4-26-54,54>>^ Dê mais terras às tribos maiores e menos terras às tribos menores, para que cada grupo receba uma herança proporcional ao tamanho de sua população.

[[v4-26-55]]

^<<v4-26-55,55>>^ Distribua a terra por sorteio e dê a cada tribo de seus antepassados a sua porção de acordo com o número de nomes registrados na lista.

[[v4-26-56]]

^<<v4-26-56,56>>^ Cada porção de terra será distribuída por sorteio entre as famílias tribais maiores e menores".

[[v4-26-57]]

^<<v4-26-57,57>>^ Este é o registro dos levitas que foram contados de acordo com seus clãs: O clã gersonita, assim chamado por causa de seu antepassado Gérson. O clã coatita, assim chamado por causa de seu antepassado Coate. O clã merarita, assim chamado por causa de seu antepassado Merari.

[[v4-26-58]]

^<<v4-26-58,58>>^ Os clãs libnita, hebronita, malita, musita e coraíta eram subdivisões de descendentes dos levitas. Coate foi antepassado de Anrão,

[[v4-26-59]]

^<<v4-26-59,59>>^ e a esposa de Anrão se chamava Joquebede. Ela também era descendente de Levi, nascida entre os levitas na terra do Egito. Anrão e Joquebede eram pais de Arão, Moisés e sua irmã Miriã.

[[v4-26-60]]

^<<v4-26-60,60>>^ Os filhos de Arão foram Nadabe, Abiú, Eleazar e Itamar.

[[v4-26-61]]

^<<v4-26-61,61>>^ Nadabe e Abiú morreram quando trouxeram fogo estranho diante do SENHOR.

[[v4-26-62]]

^<<v4-26-62,62>>^ Os homens dos clãs levitas de um mês de idade ou mais totalizaram 23.000. Os levitas, porém, não foram incluídos no registro do restante dos israelitas, pois não receberam propriedades quando a terra foi dividida.

[[v4-26-63]]

^<<v4-26-63,63>>^ Esses foram os resultados do censo dos israelitas realizado por Moisés e pelo sacerdote Eleazar nas campinas de Moabe, junto ao rio Jordão, do lado oposto de Jericó.

[[v4-26-64]]

^<<v4-26-64,64>>^ Ninguém dessa lista estava registrado no censo anterior dos israelitas feito por Moisés e Arão no deserto do Sinai,

[[v4-26-65]]

^<<v4-26-65,65>>^ pois o SENHOR tinha dito a respeito deles: "Todos morrerão no deserto". Nenhum deles sobreviveu, com exceção de Calebe, filho de Jefoné, e de Josué, filho de Num.

'''

xref:004-numeros/004-numeros-025.adoc#v4-25-0[&#60; Capítulo Anterior] | <<v4-26-0,Topo>> | xref:004-numeros/004-numeros-027.adoc#v4-27-0[Próximo Capítulo &#62;]