include::./index.adoc[]

[[v4-31-0]]
=== Números, 31
// nvt ?, NVT - Nova Versão Transformadora

[[v4-31-1]]

^<<v4-31-1,1>>^ O SENHOR disse a Moisés:

[[v4-31-2]]

^<<v4-31-2,2>>^ "Vingue-se dos midianitas pelo que fizeram aos israelitas. Depois disso, você morrerá e será reunido a seus antepassados".

[[v4-31-3]]

^<<v4-31-3,3>>^ Então Moisés disse ao povo: "Escolham e armem alguns homens para lutarem na vingança do SENHOR contra Midiã.

[[v4-31-4]]

^<<v4-31-4,4>>^ De cada tribo de Israel, enviem mil homens para a batalha".

[[v4-31-5]]

^<<v4-31-5,5>>^ Assim, escolheram mil homens de cada tribo de Israel, no total de doze mil homens armados para guerrear.

[[v4-31-6]]

^<<v4-31-6,6>>^ Moisés enviou mil homens de cada tribo, sob o comando de Fineias, filho do sacerdote Eleazar. Fineias levou consigo os objetos sagrados e as trombetas para dar a ordem de ataque.

[[v4-31-7]]

^<<v4-31-7,7>>^ Atacaram Midiã, como o SENHOR havia ordenado a Moisés, e mataram todos os homens.

[[v4-31-8]]

^<<v4-31-8,8>>^ Os cinco reis midianitas morreram na batalha: Evi, Requém, Zur, Hur e Reba. Também mataram à espada Balaão, filho de Beor.

[[v4-31-9]]

^<<v4-31-9,9>>^ Os israelitas capturaram as mulheres e as crianças midianitas e tomaram como despojo o gado, os rebanhos e toda a riqueza deles.

[[v4-31-10]]

^<<v4-31-10,10>>^ Queimaram todas as cidades e acampamentos onde os midianitas moravam.

[[v4-31-11]]

^<<v4-31-11,11>>^ Depois de juntarem todos os despojos, tanto os prisioneiros como os animais,

[[v4-31-12]]

^<<v4-31-12,12>>^ trouxeram tudo a Moisés, ao sacerdote Eleazar e a toda a comunidade de Israel, que estava acampada nas campinas de Moabe, junto ao rio Jordão, do lado oposto de Jericó.

[[v4-31-13]]

^<<v4-31-13,13>>^ Moisés, o sacerdote Eleazar e todos os líderes da comunidade saíram ao encontro deles fora do acampamento.

[[v4-31-14]]

^<<v4-31-14,14>>^ Moisés, porém, se enfureceu com os generais e os capitães que voltaram da batalha.

[[v4-31-15]]

^<<v4-31-15,15>>^ "Por que deixaram viver todas as mulheres?", perguntou ele.

[[v4-31-16]]

^<<v4-31-16,16>>^ "Foram justamente elas que seguiram o conselho de Balaão e fizeram os israelitas se rebelarem contra o SENHOR no incidente em Peor. Foi por causa delas que uma praga feriu o povo do SENHOR.

[[v4-31-17]]

^<<v4-31-17,17>>^ Agora, matem todos os meninos e todas as mulheres que tiveram relações sexuais com algum homem.

[[v4-31-18]]

^<<v4-31-18,18>>^ Deixem viver somente as meninas virgens; tragam-nas para viver entre vocês.

[[v4-31-19]]

^<<v4-31-19,19>>^ E todos que tiverem matado alguém ou tocado em algum cadáver ficarão fora do acampamento por sete dias. Purifiquem a si mesmos e às prisioneiras no terceiro e no sétimo dia.

[[v4-31-20]]

^<<v4-31-20,20>>^ Purifiquem também todas as roupas e todos os objetos de couro, pelo de cabra ou madeira."

[[v4-31-21]]

^<<v4-31-21,21>>^ Então o sacerdote Eleazar disse aos homens que participaram da batalha: "O SENHOR deu a Moisés as seguintes prescrições legais:

[[v4-31-22]]

^<<v4-31-22,22>>^ Tudo que for feito de ouro, prata, bronze, ferro, estanho e chumbo,

[[v4-31-23]]

^<<v4-31-23,23>>^ ou seja, tudo que resiste ao fogo, será passado pelo fogo para se tornar cerimonialmente puro. Em seguida, esses objetos de metal serão purificados com a água da purificação. Mas tudo que não resistir ao fogo será purificado somente com água.

[[v4-31-24]]

^<<v4-31-24,24>>^ No sétimo dia, lavem as roupas e vocês estarão purificados. Então poderão voltar ao acampamento".

[[v4-31-25]]

^<<v4-31-25,25>>^ O SENHOR também disse a Moisés:

[[v4-31-26]]

^<<v4-31-26,26>>^ "Você, o sacerdote Eleazar e os chefes das famílias de cada tribo farão uma lista de todos os despojos tomados na batalha, tanto das pessoas como dos animais.

[[v4-31-27]]

^<<v4-31-27,27>>^ Dividirão o despojo em duas partes e entregarão metade para os homens que lutaram na batalha e metade para o restante do povo.

[[v4-31-28]]

^<<v4-31-28,28>>^ Da metade que pertence ao exército, entreguem primeiro um tributo que cabe ao SENHOR, um de cada quinhentos, tanto das pessoas como do gado, dos jumentos e das ovelhas.

[[v4-31-29]]

^<<v4-31-29,29>>^ Entreguem essa porção tirada da parte do exército ao sacerdote Eleazar como oferta ao SENHOR.

[[v4-31-30]]

^<<v4-31-30,30>>^ Da metade que pertence aos israelitas, separem um de cada cinquenta, tanto das pessoas como do gado, dos jumentos, das ovelhas e dos outros animais. Entreguem essa porção aos levitas, que estão encarregados de cuidar do tabernáculo do SENHOR".

[[v4-31-31]]

^<<v4-31-31,31>>^ Moisés e o sacerdote Eleazar fizeram conforme o SENHOR ordenou a Moisés.

[[v4-31-32]]

^<<v4-31-32,32>>^ O despojo restante de tudo que os soldados haviam tomado totalizou 675.000 ovelhas,

[[v4-31-33]]

^<<v4-31-33,33>>^ 72.000 cabeças de gado,

[[v4-31-34]]

^<<v4-31-34,34>>^ 61.000 jumentos

[[v4-31-35]]

^<<v4-31-35,35>>^ e 32.000 virgens.

[[v4-31-36]]

^<<v4-31-36,36>>^ Metade do despojo foi entregue aos homens que participaram da batalha. Essa parte totalizou 337.500 ovelhas,

[[v4-31-37]]

^<<v4-31-37,37>>^ das quais 675 eram o tributo ao SENHOR;

[[v4-31-38]]

^<<v4-31-38,38>>^ 36.000 cabeças de gado, das quais 72 eram o tributo ao SENHOR;

[[v4-31-39]]

^<<v4-31-39,39>>^ 30.500 jumentos, dos quais 61 eram o tributo ao SENHOR;

[[v4-31-40]]

^<<v4-31-40,40>>^ e 16.000 virgens, das quais 32 eram o tributo ao SENHOR.

[[v4-31-41]]

^<<v4-31-41,41>>^ Moisés entregou ao sacerdote Eleazar o tributo que cabia ao SENHOR como oferta movida, conforme o SENHOR havia ordenado.

[[v4-31-42]]

^<<v4-31-42,42>>^ Metade do despojo pertencia aos israelitas, e Moisés a separou da metade que pertencia aos homens que lutaram.

[[v4-31-43]]

^<<v4-31-43,43>>^ A parte dos israelitas totalizou 337.500 ovelhas,

[[v4-31-44]]

^<<v4-31-44,44>>^ 36.000 cabeças de gado,

[[v4-31-45]]

^<<v4-31-45,45>>^ 30.500 jumentos

[[v4-31-46]]

^<<v4-31-46,46>>^ e 16.000 virgens.

[[v4-31-47]]

^<<v4-31-47,47>>^ Da metade entregue ao povo, Moisés separou um de cada cinquenta, tanto das pessoas como dos animais, e entregou aos levitas encarregados de cuidar do tabernáculo do SENHOR. Tudo foi feito conforme o SENHOR havia ordenado a Moisés.

[[v4-31-48]]

^<<v4-31-48,48>>^ Então os generais e os capitães foram a Moisés

[[v4-31-49]]

^<<v4-31-49,49>>^ e disseram: "Nós, seus servos, contamos todos os homens que saíram para a batalha sob o nosso comando; nenhum de nós está faltando!

[[v4-31-50]]

^<<v4-31-50,50>>^ Por isso, de nossa parte do despojo, apresentamos os objetos de ouro como oferta ao SENHOR: braceletes, pulseiras, anéis, brincos e colares. A oferta fará expiação por nós diante do SENHOR".

[[v4-31-51]]

^<<v4-31-51,51>>^ Moisés e o sacerdote Eleazar receberam deles as joias e os objetos artesanais de ouro.

[[v4-31-52]]

^<<v4-31-52,52>>^ Ao todo, o ouro que os generais e os capitães apresentaram como oferta ao SENHOR pesava por volta de duzentos quilos.

[[v4-31-53]]

^<<v4-31-53,53>>^ Todos os homens que participaram da batalha tomaram para si uma parte do despojo.

[[v4-31-54]]

^<<v4-31-54,54>>^ Moisés e o sacerdote Eleazar aceitaram as ofertas dos generais e dos capitães e levaram o ouro para a tenda do encontro como recordação para que o SENHOR se lembrasse dos israelitas.

'''

xref:004-numeros/004-numeros-030.adoc#v4-30-0[&#60; Capítulo Anterior] | <<v4-31-0,Topo>> | xref:004-numeros/004-numeros-032.adoc#v4-32-0[Próximo Capítulo &#62;]