include::./index.adoc[]

[[v4-33-0]]
=== Números, 33
// nvt ?, NVT - Nova Versão Transformadora

[[v4-33-1]]

^<<v4-33-1,1>>^ Este é o percurso que os israelitas fizeram quando saíram do Egito, organizados segundo suas divisões, sob a liderança de Moisés e Arão.

[[v4-33-2]]

^<<v4-33-2,2>>^ Por ordem do SENHOR, Moisés guardou um registro escrito de seu progresso. Estas são as etapas da jornada, identificadas pelos lugares onde pararam ao longo do caminho.

[[v4-33-3]]

^<<v4-33-3,3>>^ Os israelitas partiram da cidade de Ramessés no décimo quinto dia do primeiro mês, na manhã seguinte à primeira celebração da Páscoa. Partiram triunfantemente, à vista de todos os egípcios.

[[v4-33-4]]

^<<v4-33-4,4>>^ Enquanto isso, os egípcios sepultavam o filho mais velho de suas famílias que o SENHOR havia ferido mortalmente na noite anterior. Naquela noite, o SENHOR derrotou os deuses do Egito com grandes atos de julgamento.

[[v4-33-5]]

^<<v4-33-5,5>>^ Depois de partirem de Ramessés, os israelitas acamparam em Sucote.

[[v4-33-6]]

^<<v4-33-6,6>>^ Saíram de Sucote e acamparam em Etã, à beira do deserto.

[[v4-33-7]]

^<<v4-33-7,7>>^ Saíram de Etã e voltaram para Pi-Hairote, de frente para Baal-Zefom, e acamparam perto de Migdol.

[[v4-33-8]]

^<<v4-33-8,8>>^ Saíram de Pi-Hairote, atravessaram o mar Vermelho e chegaram ao deserto. Viajaram três dias pelo deserto de Etã e acamparam em Mara.

[[v4-33-9]]

^<<v4-33-9,9>>^ Saíram de Mara e acamparam em Elim, onde havia doze fontes de água e setenta palmeiras.

[[v4-33-10]]

^<<v4-33-10,10>>^ Saíram de Elim e acamparam junto ao mar Vermelho.

[[v4-33-11]]

^<<v4-33-11,11>>^ Saíram do mar Vermelho e acamparam no deserto de Sim.

[[v4-33-12]]

^<<v4-33-12,12>>^ Saíram do deserto de Sim e acamparam em Dofca.

[[v4-33-13]]

^<<v4-33-13,13>>^ Saíram de Dofca e acamparam em Alus.

[[v4-33-14]]

^<<v4-33-14,14>>^ Saíram de Alus e acamparam em Refidim, onde não havia água para o povo beber.

[[v4-33-15]]

^<<v4-33-15,15>>^ Saíram de Refidim e acamparam no deserto do Sinai.

[[v4-33-16]]

^<<v4-33-16,16>>^ Saíram do deserto do Sinai e acamparam em Quibrote-Hataavá.

[[v4-33-17]]

^<<v4-33-17,17>>^ Saíram de Quibrote-Hataavá e acamparam em Hazerote.

[[v4-33-18]]

^<<v4-33-18,18>>^ Saíram de Hazerote e acamparam em Ritmá.

[[v4-33-19]]

^<<v4-33-19,19>>^ Saíram de Ritmá e acamparam em Rimom-Perez.

[[v4-33-20]]

^<<v4-33-20,20>>^ Saíram de Rimom-Perez e acamparam em Libna.

[[v4-33-21]]

^<<v4-33-21,21>>^ Saíram de Libna e acamparam em Rissa.

[[v4-33-22]]

^<<v4-33-22,22>>^ Saíram de Rissa e acamparam em Queelata.

[[v4-33-23]]

^<<v4-33-23,23>>^ Saíram de Queelata e acamparam no monte Séfer.

[[v4-33-24]]

^<<v4-33-24,24>>^ Saíram do monte Séfer e acamparam em Harada.

[[v4-33-25]]

^<<v4-33-25,25>>^ Saíram de Harada e acamparam em Maquelote.

[[v4-33-26]]

^<<v4-33-26,26>>^ Saíram de Maquelote e acamparam em Taate.

[[v4-33-27]]

^<<v4-33-27,27>>^ Saíram de Taate e acamparam em Terá.

[[v4-33-28]]

^<<v4-33-28,28>>^ Saíram de Terá e acamparam em Mitca.

[[v4-33-29]]

^<<v4-33-29,29>>^ Saíram de Mitca e acamparam em Hasmona.

[[v4-33-30]]

^<<v4-33-30,30>>^ Saíram de Hasmona e acamparam em Moserote.

[[v4-33-31]]

^<<v4-33-31,31>>^ Saíram de Moserote e acamparam em Bene-Jaacã.

[[v4-33-32]]

^<<v4-33-32,32>>^ Saíram de Bene-Jaacã e acamparam em Hor-Gidgade.

[[v4-33-33]]

^<<v4-33-33,33>>^ Saíram de Hor-Gidgade e acamparam em Jotbatá.

[[v4-33-34]]

^<<v4-33-34,34>>^ Saíram de Jotbatá e acamparam em Abrona.

[[v4-33-35]]

^<<v4-33-35,35>>^ Saíram de Abrona e acamparam em Eziom-Geber.

[[v4-33-36]]

^<<v4-33-36,36>>^ Saíram de Eziom-Geber e acamparam em Cades, no deserto de Zim.

[[v4-33-37]]

^<<v4-33-37,37>>^ Saíram de Cades e acamparam no monte Hor, na fronteira de Edom.

[[v4-33-38]]

^<<v4-33-38,38>>^ Enquanto estavam ao pé do monte Hor, por ordem do SENHOR o sacerdote Arão subiu ao monte e morreu ali. Isso aconteceu no primeiro dia do quinto mês, quarenta anos depois que Israel saiu do Egito.

[[v4-33-39]]

^<<v4-33-39,39>>^ Arão tinha 123 anos quando morreu no monte Hor.

[[v4-33-40]]

^<<v4-33-40,40>>^ O rei cananeu de Arade, que vivia no Neguebe, na terra de Canaã, soube que os israelitas se aproximavam de sua terra.

[[v4-33-41]]

^<<v4-33-41,41>>^ Saíram do monte Hor e acamparam em Zalmona.

[[v4-33-42]]

^<<v4-33-42,42>>^ Saíram de Zalmona e acamparam em Punom.

[[v4-33-43]]

^<<v4-33-43,43>>^ Saíram de Punom e acamparam em Obote.

[[v4-33-44]]

^<<v4-33-44,44>>^ Saíram de Obote e acamparam em Ijé-Abarim, na fronteira de Moabe.

[[v4-33-45]]

^<<v4-33-45,45>>^ Saíram de Ijé-Abarim e acamparam em Dibom-Gade.

[[v4-33-46]]

^<<v4-33-46,46>>^ Saíram de Dibom-Gade e acamparam em Almom-Diblataim.

[[v4-33-47]]

^<<v4-33-47,47>>^ Saíram de Almom-Diblataim e acamparam nos montes de Abarim, perto do monte Nebo.

[[v4-33-48]]

^<<v4-33-48,48>>^ Saíram dos montes de Abarim e acamparam nas campinas de Moabe, junto ao rio Jordão, do lado oposto de Jericó.

[[v4-33-49]]

^<<v4-33-49,49>>^ Junto ao rio Jordão, acamparam desde Bete-Jesimote até Abel-Sitim nas campinas de Moabe.

[[v4-33-50]]

^<<v4-33-50,50>>^ Enquanto estavam acampados perto do rio Jordão, nas campinas de Moabe, do lado oposto de Jericó, o SENHOR disse a Moisés:

[[v4-33-51]]

^<<v4-33-51,51>>^ "Dê as seguintes instruções ao povo de Israel. Quando atravessarem o rio Jordão para entrar na terra de Canaã,

[[v4-33-52]]

^<<v4-33-52,52>>^ expulsem todos os povos que vivem ali. Destruam todas as imagens esculpidas ou fundidas e derrubem todos os santuários idólatras.

[[v4-33-53]]

^<<v4-33-53,53>>^ Tomem posse da terra e estabeleçam-se nela, pois eu lhes dei a terra para a ocuparem.

[[v4-33-54]]

^<<v4-33-54,54>>^ Distribuam a terra entre os clãs por sorteio e de forma proporcional ao tamanho de cada clã. Os clãs maiores receberão uma porção maior, e os clãs menores, uma porção menor. A decisão por sorteio é definitiva. Assim, as porções de terra serão distribuídas entre as tribos de seus antepassados.

[[v4-33-55]]

^<<v4-33-55,55>>^ Mas, se vocês não expulsarem os povos que vivem na terra, aqueles que restarem serão como farpas em seus olhos e espinhos em suas costas. Serão um tormento para vocês na terra em que habitarem.

[[v4-33-56]]

^<<v4-33-56,56>>^ E eu farei a vocês aquilo que planejava fazer a eles".

'''

xref:004-numeros/004-numeros-032.adoc#v4-32-0[&#60; Capítulo Anterior] | <<v4-33-0,Topo>> | xref:004-numeros/004-numeros-034.adoc#v4-34-0[Próximo Capítulo &#62;]