include::./index.adoc[]

[[v4-23-0]]
=== Números, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v4-23-1]]

^<<v4-23-1,1>>^ Balaão disse a Balaque: "Construa aqui sete altares e prepare sete novilhos e sete carneiros".

[[v4-23-2]]

^<<v4-23-2,2>>^ Balaque seguiu as instruções de Balaão, e os dois ofereceram um novilho e um carneiro em cada altar.

[[v4-23-3]]

^<<v4-23-3,3>>^ Então Balaão disse a Balaque: "Fique aqui junto aos holocaustos enquanto eu vejo se o SENHOR virá ao meu encontro. Depois lhe direi o que ele me revelar". Em seguida, subiu sozinho até o topo de um monte sem vegetação,

[[v4-23-4]]

^<<v4-23-4,4>>^ e Deus veio ao encontro dele. Balaão disse: "Preparei sete altares e ofereci um novilho e um carneiro em cada altar".

[[v4-23-5]]

^<<v4-23-5,5>>^ O SENHOR deu a Balaão uma mensagem para o rei Balaque e disse: "Volte até onde Balaque está e transmita-lhe essa mensagem".

[[v4-23-6]]

^<<v4-23-6,6>>^ Balaão voltou e encontrou o rei junto aos holocaustos e, com ele, todos os líderes de Moabe.

[[v4-23-7]]

^<<v4-23-7,7>>^ Esta foi a mensagem que Balaão transmitiu: "Balaque me trouxe desde Arã; o rei de Moabe me trouxe dos montes do leste. ‘Venha’, disse ele, ‘amaldiçoe Jacó para mim! Venha e anuncie a condenação de Israel!’

[[v4-23-8]]

^<<v4-23-8,8>>^ Mas como posso amaldiçoar aqueles que Deus não amaldiçoou? Como posso condenar aqueles que o SENHOR não condenou?

[[v4-23-9]]

^<<v4-23-9,9>>^ Do alto dos rochedos eu os vejo, dos montes os observo. Vejo um povo que vive só, separado das outras nações.

[[v4-23-10]]

^<<v4-23-10,10>>^ Quem pode contar os descendentes de Jacó, tão numerosos quanto o pó? Quem pode contar ao menos um quarto de Israel? Que eu morra como os justos! Que meu fim seja como o deles!".

[[v4-23-11]]

^<<v4-23-11,11>>^ Então o rei Balaque disse a Balaão: "O que você me fez? Eu o trouxe aqui para amaldiçoar meus inimigos; em vez disso, você os abençoou!".

[[v4-23-12]]

^<<v4-23-12,12>>^ Balaão respondeu: "Como eu poderia transmitir algo diferente daquilo que o SENHOR pôs em minha boca?".

[[v4-23-13]]

^<<v4-23-13,13>>^ Então Balaque lhe disse: "Venha comigo a outro lugar. Dali, você verá outra parte do povo, mas não ele todo. Amaldiçoe dali o povo!".

[[v4-23-14]]

^<<v4-23-14,14>>^ Então Balaque levou Balaão ao campo de Zofim, no alto do monte Pisga. Construiu ali sete altares e ofereceu um novilho e um carneiro em cada altar.

[[v4-23-15]]

^<<v4-23-15,15>>^ Balaão disse ao rei: "Fique aqui junto aos holocaustos enquanto eu vou ao encontro do SENHOR".

[[v4-23-16]]

^<<v4-23-16,16>>^ Então o SENHOR veio ao encontro de Balaão e lhe transmitiu uma mensagem, e depois disse: "Volte até onde Balaque está e transmita-lhe essa mensagem".

[[v4-23-17]]

^<<v4-23-17,17>>^ Balaão voltou e encontrou o rei junto aos holocaustos e, com ele, todos os oficiais de Moabe. "O que o SENHOR disse?", perguntou Balaque.

[[v4-23-18]]

^<<v4-23-18,18>>^ Esta foi a mensagem que Balaão transmitiu: "Levante-se, Balaque, e preste atenção! Ouça-me, filho de Zipor!

[[v4-23-19]]

^<<v4-23-19,19>>^ Deus não é homem para mentir, nem ser humano para mudar de ideia. Alguma vez ele falou e não agiu? Alguma vez prometeu e não cumpriu?

[[v4-23-20]]

^<<v4-23-20,20>>^ Ouça, recebi ordem de abençoar; Deus abençoou, e não posso anular sua bênção!

[[v4-23-21]]

^<<v4-23-21,21>>^ Quando ele olha para Jacó, não vê maldade alguma; não vê calamidade à espera de Israel. Pois o SENHOR, seu Deus, está com eles; foi aclamado como seu rei.

[[v4-23-22]]

^<<v4-23-22,22>>^ Deus os tirou do Egito; ele é forte como o boi selvagem.

[[v4-23-23]]

^<<v4-23-23,23>>^ Encantamento algum pode tocar Jacó, magia alguma tem poder contra Israel. Agora se dirá a respeito de Jacó: ‘Vejam o que Deus fez por Israel!’.

[[v4-23-24]]

^<<v4-23-24,24>>^ Este povo se levanta como leoa, como leão majestoso que desperta. Não descansa enquanto não devora a presa e bebe o sangue dos que foram mortos!".

[[v4-23-25]]

^<<v4-23-25,25>>^ Então Balaque disse a Balaão: "Pois bem! Se não os amaldiçoar, pelo menos não os abençoe!".

[[v4-23-26]]

^<<v4-23-26,26>>^ Mas Balaão respondeu: "Não lhe avisei que faria apenas o que o SENHOR me ordenasse?".

[[v4-23-27]]

^<<v4-23-27,27>>^ O rei Balaque disse a Balaão: "Venha, eu o levarei a mais um lugar. Quem sabe Deus se agrade de que você os amaldiçoe dali!".

[[v4-23-28]]

^<<v4-23-28,28>>^ Balaque levou Balaão até o topo do monte Peor, de onde se vê o deserto.

[[v4-23-29]]

^<<v4-23-29,29>>^ Mais uma vez, Balaão disse a Balaque: "Construa sete altares e prepare sete novilhos e sete carneiros".

[[v4-23-30]]

^<<v4-23-30,30>>^ Balaque seguiu as instruções de Balaão e ofereceu um novilho e um carneiro em cada altar.

'''

xref:004-numeros/004-numeros-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numeros/004-numeros-024.adoc#v4-24-0[Próximo Capítulo &#62;]