include::./index.adoc[]

[[v4-21-0]]
=== Números, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v4-21-1]]

^<<v4-21-1,1>>^ Quando o rei cananeu de Arade, que vivia no Neguebe, soube que o povo de Israel se aproximava pelo caminho que atravessava Atarim, ele os atacou e capturou alguns deles.

[[v4-21-2]]

^<<v4-21-2,2>>^ Então o povo de Israel fez o seguinte voto ao SENHOR: "Se entregares este povo em nossas mãos, destruiremos completamente todas as suas cidades".

[[v4-21-3]]

^<<v4-21-3,3>>^ O SENHOR ouviu o pedido do povo de Israel e lhes deu vitória sobre os cananeus. Os israelitas os destruíram completamente e também suas cidades; desde então, aquele lugar passou a ser chamado de Hormá.

[[v4-21-4]]

^<<v4-21-4,4>>^ Em seguida, partiram do monte Hor e tomaram o caminho para o mar Vermelho, a fim de contornar a terra de Edom. Mas o povo ficou impaciente

[[v4-21-5]]

^<<v4-21-5,5>>^ e começou a se queixar contra Deus e contra Moisés: "Por que você nos tirou do Egito para morrermos aqui no deserto? Aqui não há o que comer nem o que beber. E detestamos este maná horrível!".

[[v4-21-6]]

^<<v4-21-6,6>>^ Então o SENHOR enviou serpentes venenosas que morderam o povo, e muitos morreram.

[[v4-21-7]]

^<<v4-21-7,7>>^ O povo clamou a Moisés: "Pecamos ao falar contra o SENHOR e contra você. Ore para que o SENHOR tire as serpentes de nosso meio". E Moisés orou pelo povo.

[[v4-21-8]]

^<<v4-21-8,8>>^ O SENHOR lhe disse: "Faça a réplica de uma serpente venenosa e coloque-a no alto de um poste. Todos que forem mordidos viverão se olharem para ela".

[[v4-21-9]]

^<<v4-21-9,9>>^ Moisés fez uma serpente de bronze e a colocou no alto de um poste. Quem era mordido por uma serpente e olhava para a réplica de bronze era curado.

[[v4-21-10]]

^<<v4-21-10,10>>^ Os israelitas viajaram para Obote e acamparam ali.

[[v4-21-11]]

^<<v4-21-11,11>>^ Depois, seguiram para Ijé-Abarim, no deserto, na fronteira leste de Moabe.

[[v4-21-12]]

^<<v4-21-12,12>>^ De lá, viajaram para o vale do ribeiro de Zerede, onde acamparam.

[[v4-21-13]]

^<<v4-21-13,13>>^ Em seguida, partiram e acamparam do outro lado do rio Arnom, na região deserta junto ao território dos amorreus. O rio Arnom é a fronteira que separa os moabitas dos amorreus.

[[v4-21-14]]

^<<v4-21-14,14>>^ Por isso, o Livro das Guerras do SENHOR fala sobre "… Vaebe, na região de Sufá, e os riachos do rio Arnom,

[[v4-21-15]]

^<<v4-21-15,15>>^ e os riachos que se estendem até o povoado de Ar na fronteira de Moabe".

[[v4-21-16]]

^<<v4-21-16,16>>^ De lá os israelitas viajaram até Beer, o poço onde o SENHOR disse a Moisés: "Reúna o povo, e eu lhe darei água".

[[v4-21-17]]

^<<v4-21-17,17>>^ Ali os israelitas entoaram esta canção: "Jorre, ó poço! Sim, cantem seus louvores!

[[v4-21-18]]

^<<v4-21-18,18>>^ Cantem a respeito deste poço, que príncipes cavaram, que líderes abriram com seus cetros e cajados". Então saíram do deserto e passaram por Mataná,

[[v4-21-19]]

^<<v4-21-19,19>>^ Naaliel e Bamote.

[[v4-21-20]]

^<<v4-21-20,20>>^ Depois, seguiram para o vale em Moabe, onde fica o monte Pisga. Do pico desse monte se vê o deserto.

[[v4-21-21]]

^<<v4-21-21,21>>^ O povo de Israel enviou representantes a Seom, rei dos amorreus, com a seguinte mensagem:

[[v4-21-22]]

^<<v4-21-22,22>>^ "Permita-nos atravessar sua terra. Teremos cuidado de não passar por seus campos e vinhedos, e não beberemos água de seus poços. Seguiremos pela estrada real e só a deixaremos quando tivermos atravessado seu território".

[[v4-21-23]]

^<<v4-21-23,23>>^ O rei Seom, porém, não os deixou atravessar seu território. Em vez disso, mobilizou todo o seu exército e atacou o povo de Israel no deserto. A guerra ocorreu em Jaza,

[[v4-21-24]]

^<<v4-21-24,24>>^ e o povo de Israel massacrou pela espada os amorreus e ocupou seu território desde o rio Arnom até o rio Jaboque. Avançaram apenas até a fronteira com os amonitas, pois a divisa era fortificada.

[[v4-21-25]]

^<<v4-21-25,25>>^ O povo de Israel capturou todas as cidades dos amorreus e se estabeleceu nelas, incluindo Hesbom e os vilarejos ao redor.

[[v4-21-26]]

^<<v4-21-26,26>>^ Hesbom era a capital de Seom, rei dos amorreus. Ele havia derrotado o rei moabita anterior e tomado todas as suas terras até o rio Arnom.

[[v4-21-27]]

^<<v4-21-27,27>>^ Por isso os poetas dizem a seu respeito: "Venham a Hesbom! Que ela seja reconstruída! Que seja restaurada a cidade de Seom!

[[v4-21-28]]

^<<v4-21-28,28>>^ Fogo saiu de Hesbom, uma chama da cidade de Seom. Consumiu a cidade de Ar em Moabe, destruiu os governantes dos altos do Arnom.

[[v4-21-29]]

^<<v4-21-29,29>>^ Que aflição os espera, povo de Moabe! Estão arruinados, adoradores de Camos! Camos entregou seus filhos como refugiados, suas filhas como prisioneiras a Seom, o rei amorreu.

[[v4-21-30]]

^<<v4-21-30,30>>^ Nós os aniquilamos, desde Hesbom até Dibom. Nós os exterminamos até lugares distantes como Nofá e Medeba".

[[v4-21-31]]

^<<v4-21-31,31>>^ Assim, o povo de Israel ocupou o território dos amorreus.

[[v4-21-32]]

^<<v4-21-32,32>>^ Depois que Moisés enviou homens para fazer o reconhecimento de Jazar, os israelitas tomaram todas as cidades da região e expulsaram os amorreus que viviam ali.

[[v4-21-33]]

^<<v4-21-33,33>>^ Em seguida, voltaram e marcharam pelo caminho até Basã, mas o rei Ogue, de Basã, e todo o seu povo os atacaram em Edrei.

[[v4-21-34]]

^<<v4-21-34,34>>^ O SENHOR disse a Moisés: "Não tenha medo dele, pois eu o entreguei a você, junto com todo o seu povo e sua terra. Faça com ele o mesmo que fez com Seom, rei dos amorreus, que vivia em Hesbom".

[[v4-21-35]]

^<<v4-21-35,35>>^ Desse modo, mataram o rei Ogue, seus filhos e todo o seu povo; não restou sobrevivente algum. Então ocuparam seu território.

'''

xref:004-numeros/004-numeros-020.adoc#v4-20-0[&#60; Capítulo Anterior] | <<v4-21-0,Topo>> | xref:004-numeros/004-numeros-022.adoc#v4-22-0[Próximo Capítulo &#62;]