include::./index.adoc[]

[[v4-11-0]]
=== Números, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v4-11-1]]

^<<v4-11-1,1>>^ O povo começou a reclamar de sua situação ao SENHOR, que ouviu tudo que diziam. Então a ira do SENHOR se acendeu, e ele enviou fogo que ardeu entre o povo, devorando alguns que viviam nas extremidades do acampamento.

[[v4-11-2]]

^<<v4-11-2,2>>^ O povo gritou, pedindo ajuda a Moisés, e quando ele orou ao SENHOR, o fogo se apagou.

[[v4-11-3]]

^<<v4-11-3,3>>^ Depois disso, aquele lugar foi chamado de Taberá, pois o fogo do SENHOR ardeu ali entre eles.

[[v4-11-4]]

^<<v4-11-4,4>>^ Então o bando de estrangeiros que viajava com os israelitas começou a desejar intensamente a comida do Egito. E o povo de Israel também começou a se queixar: "Ah, se tivéssemos carne para comer!

[[v4-11-5]]

^<<v4-11-5,5>>^ Que saudade dos peixes que comíamos de graça no Egito! Também tínhamos pepinos, melões, alhos-porós, cebolas e alhos à vontade.

[[v4-11-6]]

^<<v4-11-6,6>>^ Mas, agora, perdemos o apetite. Não vemos outra coisa além desse maná!".

[[v4-11-7]]

^<<v4-11-7,7>>^ O maná era como semente de coentro e tinha aparência de resina.

[[v4-11-8]]

^<<v4-11-8,8>>^ O povo saía e o recolhia do chão. Usava-o para fazer farinha, triturando-o em moinhos manuais ou socando-o em pilões. Depois, cozinhava o maná numa panela e fazia bolos achatados, que tinham gosto de massa folheada assada com azeite.

[[v4-11-9]]

^<<v4-11-9,9>>^ O maná caía sobre o acampamento durante a noite, com o orvalho.

[[v4-11-10]]

^<<v4-11-10,10>>^ Moisés ouviu todas as famílias reclamando à entrada de suas tendas, e a ira do SENHOR se acendeu. Com isso, Moisés se revoltou

[[v4-11-11]]

^<<v4-11-11,11>>^ e disse ao SENHOR: "Por que tratas a mim, teu servo, com tanta crueldade? Tem misericórdia de mim! O que fiz para merecer o peso de todo este povo?

[[v4-11-12]]

^<<v4-11-12,12>>^ Por acaso gerei ou dei à luz este povo? Por que me pedes para carregá-lo nos braços como a mãe carrega o bebê que mama? Como o levarei à terra que juraste dar a seus antepassados?

[[v4-11-13]]

^<<v4-11-13,13>>^ Onde conseguirei carne para todo este povo? Eles vêm a mim reclamando dizendo: ‘Dê-nos carne para comer!’.

[[v4-11-14]]

^<<v4-11-14,14>>^ Sozinho, não sou capaz de carregar todo este povo! O peso é grande demais!

[[v4-11-15]]

^<<v4-11-15,15>>^ Se é assim que pretendes me tratar, mata-me de uma vez; para mim seria um favor, pois eu não veria esta calamidade!".

[[v4-11-16]]

^<<v4-11-16,16>>^ Então o SENHOR disse a Moisés: "Reúna diante de mim setenta homens reconhecidos como autoridades e líderes de Israel. Leve-os à tenda do encontro, para que permaneçam ali com você.

[[v4-11-17]]

^<<v4-11-17,17>>^ Eu descerei e falarei com você. Tomarei um pouco do Espírito que está sobre você e o colocarei sobre eles. Assim, dividirão com você o peso do povo, para que não precise carregá-lo sozinho.

[[v4-11-18]]

^<<v4-11-18,18>>^ "Diga ao povo: ‘Consagrem-se, pois amanhã terão carne para comer. Vocês reclamaram e o SENHOR os ouviu quando disseram: ‘Ah, se tivéssemos carne para comer! Estávamos melhor no Egito!’. Agora o SENHOR lhes dará carne, e vocês terão de comê-la.

[[v4-11-19]]

^<<v4-11-19,19>>^ E não será apenas um dia, ou dois, ou cinco, ou dez ou mesmo vinte.

[[v4-11-20]]

^<<v4-11-20,20>>^ Comerão carne por um mês inteiro, até lhes sair pelo nariz e vocês enjoarem dela, pois rejeitaram o SENHOR que está aqui entre vocês e reclamaram contra ele, dizendo: ‘Por que saímos do Egito?’’".

[[v4-11-21]]

^<<v4-11-21,21>>^ Moisés, porém, respondeu ao SENHOR: "Tenho comigo um exército de seiscentos mil soldados e, no entanto, dizes: ‘Eu lhes darei carne durante um mês inteiro!’.

[[v4-11-22]]

^<<v4-11-22,22>>^ Mesmo que abatêssemos todos os nossos rebanhos, bastaria para satisfazê-los? Mesmo que pegássemos todos os peixes do mar, seria suficiente?".

[[v4-11-23]]

^<<v4-11-23,23>>^ Então o SENHOR disse a Moisés: "Você duvida do meu poder? Agora você verá se minha palavra se cumprirá ou não!".

[[v4-11-24]]

^<<v4-11-24,24>>^ Moisés saiu e transmitiu as palavras do SENHOR ao povo. Reuniu os setenta líderes e os colocou ao redor da tenda da reunião.

[[v4-11-25]]

^<<v4-11-25,25>>^ O SENHOR desceu na nuvem e falou com ele. Depois, deu aos setenta líderes o mesmo Espírito que estava sobre Moisés. E, quando o Espírito pousou sobre eles, os líderes profetizaram, algo que nunca mais aconteceu.

[[v4-11-26]]

^<<v4-11-26,26>>^ Dois homens, Eldade e Medade, haviam permanecido no acampamento. Faziam parte da lista de autoridades, mas não tinham ido à tenda da reunião. E, no entanto, o Espírito também pousou sobre eles, de modo que profetizaram ali no acampamento.

[[v4-11-27]]

^<<v4-11-27,27>>^ Um rapaz correu e contou a Moisés: "Eldade e Medade estão profetizando no acampamento!".

[[v4-11-28]]

^<<v4-11-28,28>>^ Josué, filho de Num, que desde jovem era auxiliar de Moisés, protestou: "Moisés, meu senhor, faça-os parar!".

[[v4-11-29]]

^<<v4-11-29,29>>^ Moisés, porém, respondeu: "Você está com ciúmes por mim? Que bom seria se todos do povo do SENHOR fossem profetas e se o SENHOR colocasse seu Espírito sobre todos eles!".

[[v4-11-30]]

^<<v4-11-30,30>>^ Então Moisés voltou ao acampamento com as autoridades de Israel.

[[v4-11-31]]

^<<v4-11-31,31>>^ O SENHOR mandou um vento que trouxe codornas do lado do mar e as fez voar baixo por todo o acampamento. Numa área de vários quilômetros em todas as direções, voavam a uma altura de quase um metro do chão.

[[v4-11-32]]

^<<v4-11-32,32>>^ O povo saiu e pegou codornas durante todo aquele dia, toda aquela noite e todo o dia seguinte. Ninguém recolheu menos de dez cestos grandes. Em seguida, espalharam as codornas por todo o acampamento para secá-las.

[[v4-11-33]]

^<<v4-11-33,33>>^ Mas, enquanto ainda se empanturravam, com a boca cheia de carne, a ira do SENHOR se acendeu contra o povo, e ele os feriu com uma praga terrível.

[[v4-11-34]]

^<<v4-11-34,34>>^ Por isso, aquele lugar foi chamado de Quibrote-Hataavá, pois ali sepultaram o povo que cobiçou a carne do Egito.

[[v4-11-35]]

^<<v4-11-35,35>>^ De Quibrote-Hataavá o povo viajou para Hazerote, onde ficou algum tempo.

'''

xref:004-numeros/004-numeros-010.adoc#v4-10-0[&#60; Capítulo Anterior] | <<v4-11-0,Topo>> | xref:004-numeros/004-numeros-012.adoc#v4-12-0[Próximo Capítulo &#62;]