include::./index.adoc[]

[[v4-32-0]]
=== Números, 32
// nvt ?, NVT - Nova Versão Transformadora

[[v4-32-1]]

^<<v4-32-1,1>>^ As tribos de Rúben e Gade possuíam rebanhos enormes. Por isso, quando viram que as terras de Jazar e Gileade eram adequadas para os rebanhos,

[[v4-32-2]]

^<<v4-32-2,2>>^ foram a Moisés, ao sacerdote Eleazar e aos outros líderes da comunidade e disseram:

[[v4-32-3]]

^<<v4-32-3,3>>^ "Vejam as cidades de Atarote, Dibom, Jazar, Ninra, Hesbom, Eleale, Sibma, Nebo e Beom.

[[v4-32-4]]

^<<v4-32-4,4>>^ O SENHOR conquistou toda esta região para a comunidade de Israel, e ela é adequada para criar rebanhos e para nós, seus servos, que possuímos rebanhos.

[[v4-32-5]]

^<<v4-32-5,5>>^ Se contamos com o seu favor, pedimos que nos deixem ocupar esta terra como nossa propriedade em vez de nos dar a terra do outro lado do Jordão".

[[v4-32-6]]

^<<v4-32-6,6>>^ Moisés perguntou aos homens de Gade e Rúben: "Então vocês querem que seus irmãos vão à guerra enquanto vocês ficam aqui?

[[v4-32-7]]

^<<v4-32-7,7>>^ Por que querem desanimar o restante dos israelitas de atravessar o rio para a terra que o SENHOR lhes deu?

[[v4-32-8]]

^<<v4-32-8,8>>^ Seus antepassados fizeram a mesma coisa quando eu os enviei de Cades-Barneia para fazer o reconhecimento da terra.

[[v4-32-9]]

^<<v4-32-9,9>>^ Depois que subiram até o vale de Escol e fizeram o reconhecimento da região, desanimaram os israelitas de entrarem na terra que o SENHOR lhes dava.

[[v4-32-10]]

^<<v4-32-10,10>>^ Por isso a ira do SENHOR se acendeu contra eles, e ele jurou:

[[v4-32-11]]

^<<v4-32-11,11>>^ ‘De todos aqueles que eu resgatei do Egito, ninguém com 20 anos para cima verá a terra que eu jurei dar a Abraão, Isaque e Jacó, pois não me obedeceram de todo o coração.

[[v4-32-12]]

^<<v4-32-12,12>>^ As únicas exceções são Calebe, filho do quenezeu Jefoné, e Josué, filho de Num, pois eles seguiram o SENHOR de todo o coração’.

[[v4-32-13]]

^<<v4-32-13,13>>^ "A ira do SENHOR se acendeu contra os israelitas, e ele os fez andar sem rumo pelo deserto durante quarenta anos, até que toda a geração que havia pecado contra o SENHOR tivesse morrido.

[[v4-32-14]]

^<<v4-32-14,14>>^ Mas aqui estão vocês, uma raça de pecadores, fazendo exatamente a mesma coisa, acendendo ainda mais a ira do SENHOR contra Israel.

[[v4-32-15]]

^<<v4-32-15,15>>^ Se vocês se afastarem dele e se ele abandonar o povo no deserto outra vez, vocês serão responsáveis pela destruição de todo este povo!".

[[v4-32-16]]

^<<v4-32-16,16>>^ Eles se aproximaram de Moisés e disseram: "Queremos construir currais para nossos animais e cidades para nossos filhos.

[[v4-32-17]]

^<<v4-32-17,17>>^ Então nos armaremos e sairemos prontamente com os israelitas para a batalha até que os tenhamos levado em segurança para sua terra. Enquanto isso, nossos filhos ficarão nas cidades fortificadas que construirmos aqui e estarão protegidos de ataques dos povos da região.

[[v4-32-18]]

^<<v4-32-18,18>>^ Só voltaremos a nossos lares quando todos os israelitas tiverem recebido suas porções de terra.

[[v4-32-19]]

^<<v4-32-19,19>>^ Não exigimos, porém, terra alguma do outro lado do Jordão. Preferimos viver aqui do lado leste do Jordão e aceitamos esta região como nossa herança na terra".

[[v4-32-20]]

^<<v4-32-20,20>>^ Então Moisés lhes disse: "Se fizerem como prometeram e se, armadas para as batalhas do SENHOR,

[[v4-32-21]]

^<<v4-32-21,21>>^ suas tropas atravessarem o Jordão e continuarem a lutar até que o SENHOR tenha expulsado seus inimigos,

[[v4-32-22]]

^<<v4-32-22,22>>^ então poderão voltar quando o SENHOR tiver conquistado a terra. Assim vocês terão cumprido seu dever para com o SENHOR e para com o povo de Israel. A terra do lado leste do Jordão será sua propriedade da parte do SENHOR.

[[v4-32-23]]

^<<v4-32-23,23>>^ Mas, se não fizerem como prometeram, terão pecado contra o SENHOR e não escaparão das consequências.

[[v4-32-24]]

^<<v4-32-24,24>>^ Vão, construam cidades para suas famílias e currais para seus rebanhos, mas façam tudo que prometeram".

[[v4-32-25]]

^<<v4-32-25,25>>^ Os homens de Gade e Rúben responderam: "Nós, seus servos, seguiremos suas instruções.

[[v4-32-26]]

^<<v4-32-26,26>>^ Nossos filhos, esposas, rebanhos e gado ficarão aqui nas cidades de Gileade.

[[v4-32-27]]

^<<v4-32-27,27>>^ Mas nós, seus servos, todos armados para a guerra, atravessaremos o rio e lutaremos pelo SENHOR, conforme nos ordenou".

[[v4-32-28]]

^<<v4-32-28,28>>^ Moisés deu ordens ao sacerdote Eleazar, a Josué, filho de Num, e aos chefes das famílias das tribos de Israel.

[[v4-32-29]]

^<<v4-32-29,29>>^ Disse ele: "Os homens de Gade e Rúben estão armados para a batalha e atravessarão o Jordão com vocês e lutarão pelo SENHOR. Se o fizerem, depois que a terra for conquistada entregue-lhes o território de Gileade como sua propriedade.

[[v4-32-30]]

^<<v4-32-30,30>>^ Mas, se eles se recusarem a armar-se e atravessar o rio com vocês, serão obrigados a aceitar uma porção de terra com o restante de vocês em Canaã".

[[v4-32-31]]

^<<v4-32-31,31>>^ As tribos de Gade e Rúben disseram outra vez: "Somos seus servos e faremos o que o SENHOR ordenou!

[[v4-32-32]]

^<<v4-32-32,32>>^ Atravessaremos bem armados o Jordão até Canaã e lutaremos para o SENHOR, mas nossa porção de terra estará aqui deste lado do Jordão".

[[v4-32-33]]

^<<v4-32-33,33>>^ Então Moisés distribuiu terras entre as tribos de Gade e Rúben e a meia tribo de Manassés, filho de José. Deu-lhes o território de Seom, rei dos amorreus, o território de Ogue, rei de Basã, toda a terra com suas cidades e o território ao redor delas.

[[v4-32-34]]

^<<v4-32-34,34>>^ Os descendentes de Gade construíram as cidades de Dibom, Atarote, Aroer,

[[v4-32-35]]

^<<v4-32-35,35>>^ Atarote-Sofã, Jazar, Jogbeá,

[[v4-32-36]]

^<<v4-32-36,36>>^ Bete-Ninra e Bete-Harã, e todas eram cidades fortificadas e com currais para os rebanhos.

[[v4-32-37]]

^<<v4-32-37,37>>^ Os descendentes de Rúben construíram as cidades de Hesbom, Eleale, Quiriataim,

[[v4-32-38]]

^<<v4-32-38,38>>^ Nebo, Baal-Meom e Sibma, e mudaram o nome de algumas das cidades que conquistaram e reconstruíram.

[[v4-32-39]]

^<<v4-32-39,39>>^ Os descendentes de Maquir, da tribo de Manassés, foram até Gileade, tomaram posse dela e expulsaram os amorreus que ali viviam.

[[v4-32-40]]

^<<v4-32-40,40>>^ Moisés deu Gileade aos maquiritas, descendentes de Manassés, e eles se estabeleceram ali.

[[v4-32-41]]

^<<v4-32-41,41>>^ O povo de Jair, outro clã da tribo de Manassés, capturou muitos dos povoados de Gileade e mudou o nome da região para Cidades de Jair.

[[v4-32-42]]

^<<v4-32-42,42>>^ Enquanto isso, um homem chamado Noba conquistou a cidade de Quenate e as vilas ao redor e deu seu próprio nome à região, chamando-a de Noba.

'''

xref:004-numeros/004-numeros-031.adoc#v4-31-0[&#60; Capítulo Anterior] | <<v4-32-0,Topo>> | xref:004-numeros/004-numeros-033.adoc#v4-33-0[Próximo Capítulo &#62;]