include::./index.adoc[]

[[v4-12-0]]
=== Números, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v4-12-1]]

^<<v4-12-1,1>>^ Miriã e Arão criticaram Moisés porque ele havia se casado com uma mulher cuxita.

[[v4-12-2]]

^<<v4-12-2,2>>^ Disseram: "Acaso o SENHOR fala apenas por meio de Moisés? Também não falou por meio de nós?". E o SENHOR ouviu isso.

[[v4-12-3]]

^<<v4-12-3,3>>^ (Ora, Moisés era muito humilde, mais que qualquer outra pessoa na terra.)

[[v4-12-4]]

^<<v4-12-4,4>>^ No mesmo instante, o SENHOR chamou Moisés, Arão e Miriã e disse: "Vão à tenda do encontro, vocês três!", e eles foram para lá.

[[v4-12-5]]

^<<v4-12-5,5>>^ Então o SENHOR desceu na coluna de nuvem e parou à entrada da tenda de encontro. "Arão e Miriã!", chamou ele. Os dois se aproximaram,

[[v4-12-6]]

^<<v4-12-6,6>>^ e o SENHOR lhes disse: "Ouçam o que vou dizer: "Se houver profeta entre vocês, eu, o SENHOR, me revelarei em visões; falarei com ele em sonhos.

[[v4-12-7]]

^<<v4-12-7,7>>^ Não é assim, porém, com meu servo Moisés; ele tem sido fiel em toda a minha casa.

[[v4-12-8]]

^<<v4-12-8,8>>^ Falo com ele face a face, claramente, e não por meio de enigmas; ele vê a forma do SENHOR. Como vocês ousaram criticar meu servo Moisés?".

[[v4-12-9]]

^<<v4-12-9,9>>^ A ira do SENHOR se acendeu contra eles, e ele se retirou.

[[v4-12-10]]

^<<v4-12-10,10>>^ Enquanto a nuvem se afastava da tenda, Miriã ficou ali, com a pele branca como a neve, leprosa. Quando Arão viu o que havia acontecido com ela,

[[v4-12-11]]

^<<v4-12-11,11>>^ clamou a Moisés: "Ó meu senhor! Por favor, não nos castigue pelo pecado que insensatamente cometemos.

[[v4-12-12]]

^<<v4-12-12,12>>^ Não permita que ela fique como um bebê que nasce morto, já em decomposição".

[[v4-12-13]]

^<<v4-12-13,13>>^ Então Moisés clamou ao SENHOR: "Ó Deus, eu suplico que a cures!".

[[v4-12-14]]

^<<v4-12-14,14>>^ O SENHOR respondeu a Moisés: "Se o pai de Miriã tivesse apenas cuspido no rosto dela, não ficaria contaminada por sete dias? Portanto, mantenham-na fora do acampamento por sete dias. Depois disso, ela poderá ser aceita de volta".

[[v4-12-15]]

^<<v4-12-15,15>>^ Miriã foi mantida fora do acampamento por sete dias, e o povo esperou até ela ser trazida de volta para seguir viagem.

[[v4-12-16]]

^<<v4-12-16,16>>^ Então saíram de Hazerote e acamparam no deserto de Parã.

'''

xref:004-numeros/004-numeros-011.adoc#v4-11-0[&#60; Capítulo Anterior] | <<v4-12-0,Topo>> | xref:004-numeros/004-numeros-013.adoc#v4-13-0[Próximo Capítulo &#62;]