include::./index.adoc[]

[[v4-30-0]]
=== Números, 30
// nvt ?, NVT - Nova Versão Transformadora

[[v4-30-1]]

^<<v4-30-1,1>>^ Moisés mandou chamar os chefes das tribos de Israel e lhes disse: "Foi isto que o SENHOR ordenou:

[[v4-30-2]]

^<<v4-30-2,2>>^ Se um homem fizer um voto ao SENHOR ou uma promessa sob juramento, jamais deverá voltar atrás em sua palavra. Fará exatamente o que prometeu.

[[v4-30-3]]

^<<v4-30-3,3>>^ "Se uma moça fizer um voto ao SENHOR ou uma promessa sob juramento enquanto ainda estiver morando na casa de seu pai,

[[v4-30-4]]

^<<v4-30-4,4>>^ e se seu pai ficar sabendo do voto e não levantar objeções, todos os seus votos e promessas continuarão a valer.

[[v4-30-5]]

^<<v4-30-5,5>>^ Mas, se no dia em que ficar sabendo seu pai se recusar a deixá-la cumprir o voto ou a promessa, todos os seus votos ou promessas serão anulados. O SENHOR a perdoará, pois o pai não permitiu que ela os cumprisse.

[[v4-30-6]]

^<<v4-30-6,6>>^ "Se uma moça fizer um voto ou assumir um compromisso por meio de uma promessa precipitada e depois se casar,

[[v4-30-7]]

^<<v4-30-7,7>>^ e, no dia em que ficar sabendo do voto ou da promessa, o marido não levantar objeções, os votos e as promessas que ela fez continuarão a valer.

[[v4-30-8]]

^<<v4-30-8,8>>^ Mas, se no dia em que ficar sabendo seu marido se recusar a deixá-la cumprir o voto ou a promessa precipitada, os compromissos dela serão anulados, e o SENHOR a perdoará.

[[v4-30-9]]

^<<v4-30-9,9>>^ A mulher viúva ou divorciada, porém, deverá cumprir todos os seus votos e promessas.

[[v4-30-10]]

^<<v4-30-10,10>>^ "Se uma mulher já for casada e morar na casa do marido quando fizer o voto ou se comprometer por meio de uma promessa,

[[v4-30-11]]

^<<v4-30-11,11>>^ e o marido ficar sabendo e não levantar objeções, os votos ou as promessas que ela fez continuarão a valer.

[[v4-30-12]]

^<<v4-30-12,12>>^ Mas, se no dia em que ficar sabendo o marido se recusar a aceitá-los, o voto ou a promessa dela será anulada, e o SENHOR a perdoará.

[[v4-30-13]]

^<<v4-30-13,13>>^ Portanto, qualquer voto ou promessa que a esposa tenha feito de humilhar-se, o marido poderá confirmar ou anular.

[[v4-30-14]]

^<<v4-30-14,14>>^ Mas, se ele não levantar objeção alguma no dia em que ficar sabendo, indicará desse modo que está de acordo com todos os seus votos ou promessas.

[[v4-30-15]]

^<<v4-30-15,15>>^ Se ele esperar mais de um dia e anular um voto ou uma promessa, sofrerá o castigo que caberia à esposa".

[[v4-30-16]]

^<<v4-30-16,16>>^ Essas são as ordens que o SENHOR deu a Moisés a respeito do relacionamento entre um homem e sua esposa e entre um pai e sua filha moça que ainda mora na casa dele.

'''

xref:004-numeros/004-numeros-029.adoc#v4-29-0[&#60; Capítulo Anterior] | <<v4-30-0,Topo>> | xref:004-numeros/004-numeros-031.adoc#v4-31-0[Próximo Capítulo &#62;]