include::./index.adoc[]

[[v4-17-0]]
=== Números, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v4-17-1]]

^<<v4-17-1,1>>^ O SENHOR disse a Moisés:

[[v4-17-2]]

^<<v4-17-2,2>>^ "Diga aos israelitas que tragam doze varas de madeira, uma para cada líder das tribos de seus antepassados. Escreva o nome de cada líder em sua vara.

[[v4-17-3]]

^<<v4-17-3,3>>^ Na vara da tribo de Levi, escreva o nome de Arão, pois é necessário que haja uma vara para cada chefe das tribos de seus antepassados.

[[v4-17-4]]

^<<v4-17-4,4>>^ Coloque as varas na tenda do encontro, diante da arca que contém as tábuas da aliança, onde eu me encontro com você.

[[v4-17-5]]

^<<v4-17-5,5>>^ A vara daquele que eu escolher florescerá, e eu acabarei de vez com a murmuração e as queixas dos israelitas contra vocês".

[[v4-17-6]]

^<<v4-17-6,6>>^ Moisés transmitiu as instruções ao povo de Israel, e cada um dos doze líderes das tribos, incluindo Arão, levou uma vara para Moisés.

[[v4-17-7]]

^<<v4-17-7,7>>^ Então Moisés colocou as varas na presença do SENHOR na tenda da aliança.

[[v4-17-8]]

^<<v4-17-8,8>>^ No dia seguinte, quando Moisés entrou na tenda da aliança, viu que a vara de Arão, que representava a tribo de Levi, tinha florescido, produzindo brotos, botões, flores e amêndoas maduras.

[[v4-17-9]]

^<<v4-17-9,9>>^ Depois que retirou as varas da presença do SENHOR, Moisés as mostrou para o povo, e cada líder tomou de volta sua vara.

[[v4-17-10]]

^<<v4-17-10,10>>^ O SENHOR disse a Moisés: "Ponha a vara de Arão permanentemente diante da arca da aliança, para que sirva de advertência aos rebeldes. Isso acabará com as queixas deles contra mim e evitará mais mortes".

[[v4-17-11]]

^<<v4-17-11,11>>^ Moisés fez conforme o SENHOR lhe ordenou.

[[v4-17-12]]

^<<v4-17-12,12>>^ Então os israelitas disseram a Moisés: "Estamos condenados! Vamos morrer, vamos todos morrer!

[[v4-17-13]]

^<<v4-17-13,13>>^ Quem se aproximar do tabernáculo do SENHOR morrerá. Será que estamos todos condenados a morrer?".

'''

xref:004-numeros/004-numeros-016.adoc#v4-16-0[&#60; Capítulo Anterior] | <<v4-17-0,Topo>> | xref:004-numeros/004-numeros-018.adoc#v4-18-0[Próximo Capítulo &#62;]