include::./index.adoc[]

[[v4-35-0]]
=== Números, 35
// nvt ?, NVT - Nova Versão Transformadora

[[v4-35-1]]

^<<v4-35-1,1>>^ O SENHOR disse a Moisés junto ao rio Jordão, nas campinas de Moabe, do lado oposto de Jericó:

[[v4-35-2]]

^<<v4-35-2,2>>^ "Ordene aos israelitas que, das propriedades que receberem por herança, deem algumas cidades para os levitas morarem. Entreguem também as pastagens ao redor delas.

[[v4-35-3]]

^<<v4-35-3,3>>^ As cidades serão para moradia dos levitas, e as terras ao redor servirão de pasto para seu gado, suas ovelhas e todos os seus animais.

[[v4-35-4]]

^<<v4-35-4,4>>^ As pastagens reservadas para os levitas ao redor dessas cidades se estenderão em todas as direções por 450 metros a partir dos muros da cidade.

[[v4-35-5]]

^<<v4-35-5,5>>^ Meçam 900 metros fora dos muros da cidade em todas as direções — leste, sul, oeste e norte —, com a cidade no centro. Essa será a área de pastagem das cidades.

[[v4-35-6]]

^<<v4-35-6,6>>^ "Seis das cidades que vocês derem aos levitas serão cidades de refúgio, para onde uma pessoa que tiver matado alguém acidentalmente poderá fugir e ficar a salvo. Além disso, deem a eles 42 cidades.

[[v4-35-7]]

^<<v4-35-7,7>>^ No total, vocês darão aos levitas 48 cidades, com as pastagens ao redor.

[[v4-35-8]]

^<<v4-35-8,8>>^ As cidades virão da herança dos israelitas. As tribos maiores darão mais cidades aos levitas, enquanto as tribos menores darão menos cidades. Cada tribo entregará propriedades de forma proporcional ao tamanho do território que receber".

[[v4-35-9]]

^<<v4-35-9,9>>^ O SENHOR disse a Moisés:

[[v4-35-10]]

^<<v4-35-10,10>>^ "Dê as seguintes instruções ao povo de Israel. "Quando atravessarem o Jordão para entrar na terra de Canaã,

[[v4-35-11]]

^<<v4-35-11,11>>^ escolham cidades de refúgio para onde uma pessoa que tiver matado alguém acidentalmente poderá fugir.

[[v4-35-12]]

^<<v4-35-12,12>>^ Essas cidades serão lugares de proteção contra os parentes da vítima que quiserem vingar sua morte. A pessoa que tirou a vida de alguém não será executada antes de ser julgada pela comunidade.

[[v4-35-13]]

^<<v4-35-13,13>>^ Escolham para si seis cidades de refúgio:

[[v4-35-14]]

^<<v4-35-14,14>>^ três do lado leste do rio Jordão e três do lado oeste, na terra de Canaã.

[[v4-35-15]]

^<<v4-35-15,15>>^ Essas cidades servirão para proteger os israelitas, os estrangeiros que vivem entre vocês e os que estiverem de passagem. Qualquer um que matar alguém acidentalmente poderá fugir para lá.

[[v4-35-16]]

^<<v4-35-16,16>>^ "Se, contudo, alguém atacar uma pessoa e matá-la com um pedaço de ferro, é assassinato e o assassino deverá ser executado.

[[v4-35-17]]

^<<v4-35-17,17>>^ Ou, se alguém com uma pedra na mão atacar e matar outra pessoa, é assassinato e o assassino deverá ser executado.

[[v4-35-18]]

^<<v4-35-18,18>>^ Ou ainda, se alguém atacar outra pessoa e matá-la com um pedaço de madeira, é assassinato e o assassino deverá ser executado.

[[v4-35-19]]

^<<v4-35-19,19>>^ O parente mais próximo da vítima é responsável pela execução do assassino. Quando o encontrar, o vingador deverá executar o assassino.

[[v4-35-20]]

^<<v4-35-20,20>>^ Portanto, se alguém odeia outra pessoa e fica à espreita dela, e a empurra ou joga contra ela um objeto perigoso e ela morre,

[[v4-35-21]]

^<<v4-35-21,21>>^ ou se alguém odeia outra pessoa e a fere com as mãos e ela morre, é assassinato. Nesses casos, o vingador deverá executar o assassino quando o encontrar.

[[v4-35-22]]

^<<v4-35-22,22>>^ "Se, contudo, alguém empurrar outra pessoa sem ter demonstrado anteriormente nenhuma hostilidade, ou jogar algo que acerte a pessoa acidentalmente,

[[v4-35-23]]

^<<v4-35-23,23>>^ ou, sem intenção, deixar cair sobre ela uma pedra grande, embora não fossem inimigos, e a outra pessoa morrer,

[[v4-35-24]]

^<<v4-35-24,24>>^ a comunidade usará as seguintes normas para julgar entre o acusado e o vingador, o parente mais próximo da vítima:

[[v4-35-25]]

^<<v4-35-25,25>>^ a comunidade protegerá o acusado do vingador e cuidará para que ele chegue à cidade de refúgio para onde fugiu. Ali ele ficará até a morte do sumo sacerdote, que foi ungido com o óleo sagrado.

[[v4-35-26]]

^<<v4-35-26,26>>^ "Se, contudo, o acusado sair alguma vez dos limites da cidade de refúgio

[[v4-35-27]]

^<<v4-35-27,27>>^ e o vingador o encontrar fora da cidade e o executar, essa morte não será considerada assassinato.

[[v4-35-28]]

^<<v4-35-28,28>>^ O acusado deveria ter ficado dentro da cidade de refúgio até a morte do sumo sacerdote. Depois da morte do sumo sacerdote, porém, o acusado poderá voltar à sua propriedade.

[[v4-35-29]]

^<<v4-35-29,29>>^ Essas são as prescrições legais a serem cumpridas de geração em geração, onde quer que morarem.

[[v4-35-30]]

^<<v4-35-30,30>>^ "Todos os assassinos deverão ser executados, mas apenas se mais de uma testemunha apresentar provas. Ninguém será executado com base no depoimento de apenas uma testemunha.

[[v4-35-31]]

^<<v4-35-31,31>>^ Jamais aceitem resgate pela vida de alguém que foi declarado culpado de assassinato e condenado à morte. Os assassinos deverão sempre ser executados.

[[v4-35-32]]

^<<v4-35-32,32>>^ E jamais aceitem resgate de alguém que fugiu para uma cidade de refúgio, permitindo, com isso, que o acusado volte à sua propriedade antes da morte do sumo sacerdote.

[[v4-35-33]]

^<<v4-35-33,33>>^ Essa medida garantirá que a terra em que vivem não seja contaminada, pois o assassinato contamina a terra. O único sacrifício que fará expiação pela terra em caso de assassinato é a execução do assassino.

[[v4-35-34]]

^<<v4-35-34,34>>^ Não contaminem a terra onde habitam, pois eu mesmo habito ali. Eu sou o SENHOR e habito entre o povo de Israel".

'''

xref:004-numeros/004-numeros-034.adoc#v4-34-0[&#60; Capítulo Anterior] | <<v4-35-0,Topo>> | xref:004-numeros/004-numeros-036.adoc#v4-36-0[Próximo Capítulo &#62;]