include::./index.adoc[]

[[v4-36-0]]
=== Números, 36
// nvt ?, NVT - Nova Versão Transformadora

[[v4-36-1]]

^<<v4-36-1,1>>^ Os chefes das famílias do clã de Gileade, descendentes de Maquir, filho de Manassés, filho de José, apresentaram uma petição a Moisés e aos líderes de Israel, os chefes das famílias.

[[v4-36-2]]

^<<v4-36-2,2>>^ Disseram eles: "O SENHOR o instruiu a repartir a terra por sorteio entre os israelitas. O SENHOR também o instruiu a entregar a herança que pertencia a nosso irmão Zelofeade às filhas dele.

[[v4-36-3]]

^<<v4-36-3,3>>^ Mas, se elas se casarem com homens de outra tribo de Israel, levarão consigo suas propriedades para a tribo dos homens com quem se casarem. Com isso, a área total do território de nossa tribo será reduzida.

[[v4-36-4]]

^<<v4-36-4,4>>^ Quando chegar o Ano do Jubileu, a porção de terra que elas receberam será anexada à porção dessa nova tribo, e essa propriedade será tirada da tribo de nossos antepassados para sempre".

[[v4-36-5]]

^<<v4-36-5,5>>^ Então Moisés deu aos israelitas a seguinte ordem do SENHOR: "A preocupação dos homens da tribo de José é justa.

[[v4-36-6]]

^<<v4-36-6,6>>^ É isto que o SENHOR ordenou acerca das filhas de Zelofeade: Elas poderão se casar com quem quiserem, desde que seja alguém da tribo de seus antepassados.

[[v4-36-7]]

^<<v4-36-7,7>>^ Nenhuma terra poderá ser transferida de uma tribo para outra, pois a porção entregue a cada tribo deve permanecer com a tribo para a qual foi inicialmente designada.

[[v4-36-8]]

^<<v4-36-8,8>>^ As filhas de todas as tribos de Israel que têm direito a herdar propriedades deverão se casar com homens de um dos clãs de sua própria tribo, para que todos os israelitas mantenham a propriedade de seus antepassados.

[[v4-36-9]]

^<<v4-36-9,9>>^ Nenhuma porção de terra poderá ser transferida de uma tribo para outra; cada tribo de Israel manterá a porção de terra que recebeu como herança".

[[v4-36-10]]

^<<v4-36-10,10>>^ As filhas de Zelofeade fizeram conforme o SENHOR ordenou a Moisés.

[[v4-36-11]]

^<<v4-36-11,11>>^ Maala, Tirza, Hogla, Milca e Noa se casaram com primos da família de seu pai,

[[v4-36-12]]

^<<v4-36-12,12>>^ membros dos clãs de Manassés, filho de José. Assim, sua herança permaneceu no clã e na tribo de seus antepassados.

[[v4-36-13]]

^<<v4-36-13,13>>^ Esses são os mandamentos e os estatutos que o SENHOR deu aos israelitas por meio de Moisés enquanto estavam acampados nas campinas de Moabe junto ao rio Jordão, do lado oposto de Jericó.

'''

xref:004-numeros/004-numeros-035.adoc#v4-35-0[&#60; Capítulo Anterior] | <<v4-36-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[Próximo Capítulo &#62;]