include::./index.adoc[]

[[v4-9-0]]
=== Números, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v4-9-1]]

^<<v4-9-1,1>>^ No primeiro mês do segundo ano desde a saída de Israel do Egito, o SENHOR falou com Moisés no deserto do Sinai e disse:

[[v4-9-2]]

^<<v4-9-2,2>>^ "Instrua os israelitas a celebrarem a Páscoa no tempo determinado,

[[v4-9-3]]

^<<v4-9-3,3>>^ ao entardecer do décimo quarto dia do primeiro mês. Siga todos os meus decretos e estatutos a respeito dessa celebração".

[[v4-9-4]]

^<<v4-9-4,4>>^ Então Moisés instruiu o povo a celebrar a Páscoa

[[v4-9-5]]

^<<v4-9-5,5>>^ no deserto do Sinai, ao entardecer do décimo quarto dia do primeiro mês. Eles celebraram a festa ali, conforme o SENHOR havia ordenado a Moisés.

[[v4-9-6]]

^<<v4-9-6,6>>^ Alguns dos homens, porém, estavam cerimonialmente impuros por terem tocado num cadáver, e não puderam celebrar a Páscoa naquele dia. Eles se dirigiram a Moisés e Arão no mesmo dia

[[v4-9-7]]

^<<v4-9-7,7>>^ e disseram: "Ficamos cerimonialmente impuros, pois tocamos num cadáver. Mas por que estamos impedidos de apresentar a oferta do SENHOR no devido tempo como os demais israelitas?".

[[v4-9-8]]

^<<v4-9-8,8>>^ Moisés respondeu: "Esperem aqui até eu receber instruções do SENHOR para vocês".

[[v4-9-9]]

^<<v4-9-9,9>>^ Então o SENHOR disse a Moisés:

[[v4-9-10]]

^<<v4-9-10,10>>^ "Dê as seguintes instruções ao povo de Israel. Se alguém do povo, agora ou nas gerações futuras, estiver cerimonialmente impuro no tempo da Páscoa por haver tocado num cadáver, ou se estiver viajando e não puder comparecer à cerimônia, ainda assim celebrará a Páscoa do SENHOR.

[[v4-9-11]]

^<<v4-9-11,11>>^ Oferecerá um sacrifício de Páscoa um mês depois, ao entardecer do décimo quarto dia do segundo mês. Nessa ocasião, comerá o cordeiro de Páscoa, acompanhado de folhas verdes amargas e pão sem fermento.

[[v4-9-12]]

^<<v4-9-12,12>>^ Não deixará sobrar coisa alguma do cordeiro até a manhã seguinte, e não quebrará osso algum do animal. Seguirá todos os decretos acerca da Páscoa.

[[v4-9-13]]

^<<v4-9-13,13>>^ "Aquele que estiver cerimonialmente puro e não estiver viajando, mas ainda assim não celebrar a Páscoa, será eliminado do meio do povo. Se não apresentar a oferta do SENHOR no devido tempo, sofrerá as consequências de sua culpa.

[[v4-9-14]]

^<<v4-9-14,14>>^ E, se algum estrangeiro que vive entre vocês desejar celebrar a Páscoa do SENHOR, deverá seguir os mesmos decretos. Esses decretos se aplicam tanto aos israelitas de nascimento como aos estrangeiros que vivem entre vocês".

[[v4-9-15]]

^<<v4-9-15,15>>^ No dia em que foi armado o tabernáculo, a tenda da aliança, a nuvem o cobriu. Desde o entardecer até o amanhecer, a nuvem sobre o tabernáculo parecia uma coluna de fogo.

[[v4-9-16]]

^<<v4-9-16,16>>^ Era assim que sempre acontecia: à noite, a nuvem que cobria o tabernáculo tinha a aparência de fogo.

[[v4-9-17]]

^<<v4-9-17,17>>^ Cada vez que a nuvem se elevava da tenda, o povo de Israel levantava acampamento e a seguia. No lugar onde a nuvem parava, eles acampavam.

[[v4-9-18]]

^<<v4-9-18,18>>^ Assim, viajavam e acampavam por ordem do SENHOR, para onde ele os conduzia. Enquanto a nuvem estava sobre o tabernáculo, permaneciam acampados.

[[v4-9-19]]

^<<v4-9-19,19>>^ Se a nuvem ficava sobre o tabernáculo por muito tempo, os israelitas permaneciam ali e cumpriam suas obrigações para com o SENHOR.

[[v4-9-20]]

^<<v4-9-20,20>>^ Às vezes a nuvem permanecia apenas alguns dias sobre o tabernáculo, de modo que o povo também ficava apenas alguns dias, conforme o SENHOR ordenava. Então, por ordem do SENHOR, levantavam acampamento e seguiam viagem.

[[v4-9-21]]

^<<v4-9-21,21>>^ Às vezes a nuvem parava apenas durante a noite e se elevava na manhã seguinte. Dia ou noite, porém, quando a nuvem se elevava, os israelitas levantavam acampamento e seguiam viagem.

[[v4-9-22]]

^<<v4-9-22,22>>^ Se a nuvem permanecia sobre o tabernáculo por dois dias, um mês ou um ano, ficavam acampados e não seguiam viagem. Mas, assim que a nuvem se elevava, levantavam acampamento e seguiam viagem.

[[v4-9-23]]

^<<v4-9-23,23>>^ Com isso, acampavam por ordem do SENHOR e viajavam por ordem do SENHOR, e cumpriam tudo que o SENHOR lhes ordenava por meio de Moisés.

'''

xref:004-numeros/004-numeros-008.adoc#v4-8-0[&#60; Capítulo Anterior] | <<v4-9-0,Topo>> | xref:004-numeros/004-numeros-010.adoc#v4-10-0[Próximo Capítulo &#62;]