include::./index.adoc[]

[[v4-6-0]]
=== Números, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v4-6-1]]

^<<v4-6-1,1>>^ Então o SENHOR disse a Moisés:

[[v4-6-2]]

^<<v4-6-2,2>>^ "Dê as seguintes instruções ao povo de Israel. "Se alguém do povo, homem ou mulher, fizer o voto especial de nazireu e se consagrar ao SENHOR,

[[v4-6-3]]

^<<v4-6-3,3>>^ deixará de beber vinho e outras bebidas fermentadas. Não usará vinagre feito de vinho nem de outras bebidas fermentadas, e não beberá suco de uva nem comerá uvas ou passas.

[[v4-6-4]]

^<<v4-6-4,4>>^ Enquanto estiver sob o voto de nazireu, não beberá nem comerá coisa alguma que venha da videira, nem mesmo sementes ou cascas de uvas.

[[v4-6-5]]

^<<v4-6-5,5>>^ "Enquanto durar o voto, o nazireu será consagrado ao SENHOR e não cortará o cabelo. Deixará o cabelo crescer até concluir o voto.

[[v4-6-6]]

^<<v4-6-6,6>>^ Não se aproximará de cadáver enquanto estiver consagrado ao SENHOR.

[[v4-6-7]]

^<<v4-6-7,7>>^ Mesmo que o falecido seja seu pai, mãe, irmão ou irmã, o nazireu não se contaminará, pois o cabelo em sua cabeça simboliza sua consagração a Deus.

[[v4-6-8]]

^<<v4-6-8,8>>^ Essa exigência é válida enquanto ele estiver consagrado ao SENHOR.

[[v4-6-9]]

^<<v4-6-9,9>>^ "Se alguém cair morto ao lado do nazireu, o cabelo que ele consagrou ficará contaminado. Esperará sete dias e depois raspará a cabeça. Então, estará purificado de sua contaminação.

[[v4-6-10]]

^<<v4-6-10,10>>^ No oitavo dia, levará duas rolinhas ou dois pombinhos para o sacerdote à entrada da tenda do encontro.

[[v4-6-11]]

^<<v4-6-11,11>>^ O sacerdote oferecerá uma das aves como oferta pelo pecado, e a outra, como holocausto. Desse modo, fará expiação pela culpa resultante do contato com o cadáver. O nazireu reafirmará seu compromisso e deixará o cabelo crescer outra vez.

[[v4-6-12]]

^<<v4-6-12,12>>^ Os dias de voto cumpridos antes da contaminação não serão contados. Ele se consagrará novamente ao SENHOR por todo o período do voto e apresentará um cordeiro de um ano como oferta pela culpa.

[[v4-6-13]]

^<<v4-6-13,13>>^ "Essa é a lei ritual para o nazireu. Quando chegar ao fim do período de consagração, irá até a entrada da tenda do encontro

[[v4-6-14]]

^<<v4-6-14,14>>^ e trará suas ofertas ao SENHOR: um cordeiro de um ano e sem defeito como holocausto, uma cordeira de um ano e sem defeito como oferta pelo pecado, um carneiro sem defeito como oferta de paz,

[[v4-6-15]]

^<<v4-6-15,15>>^ um cesto de pães sem fermento, bolos de farinha da melhor qualidade misturada com azeite e pães finos untados com azeite, junto com as ofertas de cereal e ofertas derramadas.

[[v4-6-16]]

^<<v4-6-16,16>>^ O sacerdote apresentará as ofertas diante do SENHOR: primeiro a oferta pelo pecado e o holocausto,

[[v4-6-17]]

^<<v4-6-17,17>>^ depois o carneiro para a oferta de paz, junto com o cesto de pães sem fermento. O sacerdote também apresentará ao SENHOR as ofertas de cereal e ofertas derramadas.

[[v4-6-18]]

^<<v4-6-18,18>>^ "Em seguida, o nazireu raspará a cabeça à entrada da tenda do encontro. Pegará o cabelo que consagrou e o colocará no fogo embaixo do sacrifício da oferta de paz.

[[v4-6-19]]

^<<v4-6-19,19>>^ Depois que o nazireu tiver raspado a cabeça, o sacerdote pegará um ombro cozido de carneiro e, de dentro do cesto, pegará um bolo e um pão fino sem fermento e colocará tudo nas mãos do nazireu.

[[v4-6-20]]

^<<v4-6-20,20>>^ Por fim, o sacerdote os moverá para o alto como oferta especial diante do SENHOR. Essas são as porções santas para o sacerdote, junto com o peito da oferta movida e a coxa da oferta sagrada movidos diante do SENHOR. Depois dessa cerimônia, o nazireu poderá voltar a beber vinho.

[[v4-6-21]]

^<<v4-6-21,21>>^ "Essa é a lei ritual dos nazireus que fazem o voto de apresentar essas ofertas para o SENHOR. Se tiverem recursos materiais, apresentarão outras ofertas além dessas. Devem cumprir o voto que fizeram quando se consagraram como nazireus".

[[v4-6-22]]

^<<v4-6-22,22>>^ Então o SENHOR disse a Moisés:

[[v4-6-23]]

^<<v4-6-23,23>>^ "Diga a Arão e a seus filhos que abençoem o povo de Israel com esta bênção especial:

[[v4-6-24]]

^<<v4-6-24,24>>^ ‘Que o SENHOR o abençoe e o proteja.

[[v4-6-25]]

^<<v4-6-25,25>>^ Que o SENHOR olhe para você com favor e lhe mostre bondade.

[[v4-6-26]]

^<<v4-6-26,26>>^ Que o SENHOR se agrade de você e lhe dê paz’.

[[v4-6-27]]

^<<v4-6-27,27>>^ Assim, Arão e seus filhos colocarão meu nome sobre os israelitas, e eu mesmo os abençoarei".

'''

xref:004-numeros/004-numeros-005.adoc#v4-5-0[&#60; Capítulo Anterior] | <<v4-6-0,Topo>> | xref:004-numeros/004-numeros-007.adoc#v4-7-0[Próximo Capítulo &#62;]