include::./index.adoc[]

[[v4-3-0]]
=== Números, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v4-3-1]]

^<<v4-3-1,1>>^ Esta é a descendência de Arão e de Moisés, registrada quando o SENHOR falou a Moisés no monte Sinai.

[[v4-3-2]]

^<<v4-3-2,2>>^ Os nomes dos filhos de Arão eram Nadabe, o mais velho, Abiú, Eleazar e Itamar.

[[v4-3-3]]

^<<v4-3-3,3>>^ Esses filhos de Arão foram ungidos e consagrados para o serviço sacerdotal.

[[v4-3-4]]

^<<v4-3-4,4>>^ Nadabe e Abiú, porém, morreram na presença do SENHOR, no deserto do Sinai, quando trouxeram fogo estranho diante do SENHOR. Como não tinham filhos, restaram somente Eleazar e Itamar para servir como sacerdotes junto com seu pai, Arão.

[[v4-3-5]]

^<<v4-3-5,5>>^ Então o SENHOR disse a Moisés:

[[v4-3-6]]

^<<v4-3-6,6>>^ "Chame à frente os membros da tribo de Levi e apresente-os ao sacerdote Arão para serem seus assistentes.

[[v4-3-7]]

^<<v4-3-7,7>>^ Eles servirão a Arão e a todo o povo no desempenho das funções na tenda do encontro e no serviço do tabernáculo.

[[v4-3-8]]

^<<v4-3-8,8>>^ Cuidarão de todos os utensílios da tenda do encontro e servirão no tabernáculo como representantes dos israelitas.

[[v4-3-9]]

^<<v4-3-9,9>>^ Nomeie os levitas como assistentes de Arão e de seus filhos, pois, dentre todos os israelitas, eles foram designados para esse propósito.

[[v4-3-10]]

^<<v4-3-10,10>>^ Encarregue Arão e seus filhos de realizarem as funções do serviço sacerdotal. Qualquer pessoa não autorizada que se aproximar do santuário será executada".

[[v4-3-11]]

^<<v4-3-11,11>>^ O SENHOR também disse a Moisés:

[[v4-3-12]]

^<<v4-3-12,12>>^ "Veja, escolhi os levitas dentre os israelitas como substitutos de todos os filhos mais velhos de Israel. Os levitas me pertencem,

[[v4-3-13]]

^<<v4-3-13,13>>^ pois todos os filhos mais velhos são meus. No dia em que feri mortalmente todos os filhos mais velhos dos egípcios, consagrei para mim todos os filhos mais velhos de Israel e todos os machos das primeiras crias dos animais. Eles são meus. Eu sou o SENHOR".

[[v4-3-14]]

^<<v4-3-14,14>>^ O SENHOR falou ainda a Moisés no deserto do Sinai:

[[v4-3-15]]

^<<v4-3-15,15>>^ "Registre os nomes dos membros da tribo de Levi por famílias e clãs. Faça uma lista de todos os indivíduos do sexo masculino de um mês de idade para cima".

[[v4-3-16]]

^<<v4-3-16,16>>^ Moisés fez a lista, conforme o SENHOR havia ordenado.

[[v4-3-17]]

^<<v4-3-17,17>>^ Levi teve três filhos: Gérson, Coate e Merari.

[[v4-3-18]]

^<<v4-3-18,18>>^ Os clãs de Gérson receberam os nomes de seus descendentes: Libni e Simei.

[[v4-3-19]]

^<<v4-3-19,19>>^ Os clãs de Coate receberam os nomes de seus descendentes: Anrão, Isar, Hebrom e Uziel.

[[v4-3-20]]

^<<v4-3-20,20>>^ Os clãs de Merari receberam os nomes de seus descendentes: Mali e Musi. Esses foram os clãs levitas, registrados de acordo com os grupos de suas famílias.

[[v4-3-21]]

^<<v4-3-21,21>>^ Os descendentes de Gérson eram constituídos dos clãs de Libni e Simei.

[[v4-3-22]]

^<<v4-3-22,22>>^ Nos clãs gersonitas havia 7.500 indivíduos do sexo masculino de um mês de idade para cima.

[[v4-3-23]]

^<<v4-3-23,23>>^ A área designada para seu acampamento ficava no lado oeste, atrás do tabernáculo.

[[v4-3-24]]

^<<v4-3-24,24>>^ O líder dos clãs gersonitas era Eliasafe, filho de Lael.

[[v4-3-25]]

^<<v4-3-25,25>>^ Os dois clãs eram encarregados de cuidar das seguintes partes da tenda do encontro: a tenda com sua cobertura, a cortina da entrada da tenda,

[[v4-3-26]]

^<<v4-3-26,26>>^ as cortinas do pátio ao redor do tabernáculo e do altar, a cortina da entrada do pátio, as cordas e todos os objetos relacionados ao seu uso.

[[v4-3-27]]

^<<v4-3-27,27>>^ Os descendentes de Coate eram constituídos dos clãs de Anrão, Isar, Hebrom e Uziel.

[[v4-3-28]]

^<<v4-3-28,28>>^ Nos clãs coatitas havia 8.600 indivíduos do sexo masculino de um mês de idade para cima. Eram encarregados de cuidar do santuário,

[[v4-3-29]]

^<<v4-3-29,29>>^ e a área designada para seu acampamento ficava no lado sul do tabernáculo.

[[v4-3-30]]

^<<v4-3-30,30>>^ O líder dos clãs coatitas era Elisafã, filho de Uziel.

[[v4-3-31]]

^<<v4-3-31,31>>^ Eram encarregados de cuidar da arca, da mesa, do candelabro, dos dois altares, dos diversos utensílios do santuário, da cortina interna e de todos os objetos relacionados ao seu uso.

[[v4-3-32]]

^<<v4-3-32,32>>^ Eleazar, filho do sacerdote Arão, era o líder principal de todos os levitas e responsável pela supervisão do santuário.

[[v4-3-33]]

^<<v4-3-33,33>>^ Os descendentes de Merari eram constituídos dos clãs de Mali e Musi.

[[v4-3-34]]

^<<v4-3-34,34>>^ Nos clãs meraritas havia 6.200 indivíduos do sexo masculino de um mês de idade para cima.

[[v4-3-35]]

^<<v4-3-35,35>>^ A área designada para seu acampamento ficava no lado norte do tabernáculo. O líder dos clãs meraritas era Zuriel, filho de Abiail.

[[v4-3-36]]

^<<v4-3-36,36>>^ Os meraritas eram encarregados de cuidar das armações que sustentavam o tabernáculo, além dos travessões, das colunas, das bases e de todos os objetos relacionados ao seu uso.

[[v4-3-37]]

^<<v4-3-37,37>>^ Também eram responsáveis pelas colunas do pátio e por todas as suas bases, estacas e cordas.

[[v4-3-38]]

^<<v4-3-38,38>>^ A área na frente do tabernáculo, na direção do nascer do sol, do lado leste da tenda do encontro, era reservada para Moisés, Arão e seus filhos, os responsáveis finais pelo santuário em favor do povo de Israel. Qualquer um que não fosse sacerdote ou levita e se aproximasse do santuário seria executado.

[[v4-3-39]]

^<<v4-3-39,39>>^ Quando Moisés e Arão contaram os clãs levitas, conforme a ordem do SENHOR, chegaram ao total de 22.000 indivíduos do sexo masculino de um mês de idade para cima.

[[v4-3-40]]

^<<v4-3-40,40>>^ Então o SENHOR disse a Moisés: "Conte todos os filhos mais velhos que há em Israel de um mês de idade para cima e registre os nomes numa lista.

[[v4-3-41]]

^<<v4-3-41,41>>^ Os levitas serão reservados para mim como substitutos dos filhos mais velhos dos israelitas. Eu sou o SENHOR. Os animais dos levitas serão reservados para mim como substitutos dos machos das primeiras crias dos animais de todo o povo de Israel".

[[v4-3-42]]

^<<v4-3-42,42>>^ Moisés contou os filhos mais velhos dos israelitas, exatamente conforme o SENHOR havia ordenado.

[[v4-3-43]]

^<<v4-3-43,43>>^ O número de filhos mais velhos de um mês de idade para cima foi de 22.273.

[[v4-3-44]]

^<<v4-3-44,44>>^ O SENHOR também disse a Moisés:

[[v4-3-45]]

^<<v4-3-45,45>>^ "Tome os levitas como substitutos dos filhos mais velhos dos israelitas e tome os animais dos levitas como substitutos dos machos das primeiras crias dos animais de todos os israelitas. Os levitas me pertencem. Eu sou o SENHOR.

[[v4-3-46]]

^<<v4-3-46,46>>^ O número de filhos mais velhos de Israel excede em 273 o número de levitas. Para resgatar o excedente de filhos mais velhos,

[[v4-3-47]]

^<<v4-3-47,47>>^ recolha cinco peças de prata para cada um deles, com base no siclo do santuário, equivalente a doze gramas cada peça.

[[v4-3-48]]

^<<v4-3-48,48>>^ Entregue a prata a Arão e a seus filhos como resgate pelo número excedente de filhos mais velhos".

[[v4-3-49]]

^<<v4-3-49,49>>^ Moisés recolheu a prata para o resgate dos filhos mais velhos de Israel que excediam o número de levitas.

[[v4-3-50]]

^<<v4-3-50,50>>^ Arrecadou 1.365 peças de prata, com base no siclo do santuário, em lugar dos filhos mais velhos de Israel.

[[v4-3-51]]

^<<v4-3-51,51>>^ Moisés entregou a prata do resgate a Arão e a seus filhos, conforme o SENHOR havia ordenado.

'''

xref:004-numeros/004-numeros-002.adoc#v4-2-0[&#60; Capítulo Anterior] | <<v4-3-0,Topo>> | xref:004-numeros/004-numeros-004.adoc#v4-4-0[Próximo Capítulo &#62;]