include::./index.adoc[]

[[v4-13-0]]
=== Números, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v4-13-1]]

^<<v4-13-1,1>>^ O SENHOR disse a Moisés:

[[v4-13-2]]

^<<v4-13-2,2>>^ "Envie homens para fazer o reconhecimento da terra de Canaã, a terra que eu dou aos israelitas. Mande um líder de cada tribo de seus antepassados".

[[v4-13-3]]

^<<v4-13-3,3>>^ Moisés fez conforme o SENHOR ordenou. Do acampamento no deserto de Parã, enviou doze homens, todos eles chefes das tribos de Israel.

[[v4-13-4]]

^<<v4-13-4,4>>^ Estas eram as tribos e os nomes de seus líderes: da tribo de Rúben, Samua, filho de Zacur;

[[v4-13-5]]

^<<v4-13-5,5>>^ da tribo de Simeão, Safate, filho de Hori;

[[v4-13-6]]

^<<v4-13-6,6>>^ da tribo de Judá, Calebe, filho de Jefoné;

[[v4-13-7]]

^<<v4-13-7,7>>^ da tribo de Issacar, Igal, filho de José;

[[v4-13-8]]

^<<v4-13-8,8>>^ da tribo de Efraim, Oseias, filho de Num;

[[v4-13-9]]

^<<v4-13-9,9>>^ da tribo de Benjamim, Palti, filho de Rafu;

[[v4-13-10]]

^<<v4-13-10,10>>^ da tribo de Zebulom, Gadiel, filho de Sodi;

[[v4-13-11]]

^<<v4-13-11,11>>^ da tribo de Manassés, filho de José, Gadi, filho de Susi;

[[v4-13-12]]

^<<v4-13-12,12>>^ da tribo de Dã, Amiel, filho de Gemali;

[[v4-13-13]]

^<<v4-13-13,13>>^ da tribo de Aser, Setur, filho de Micael;

[[v4-13-14]]

^<<v4-13-14,14>>^ da tribo de Naftali, Nabi, filho de Vofsi;

[[v4-13-15]]

^<<v4-13-15,15>>^ da tribo de Gade, Geuel, filho de Maqui.

[[v4-13-16]]

^<<v4-13-16,16>>^ Esses são os nomes dos homens que Moisés enviou para explorar a terra. (Moisés deu a Oseias, filho de Num, o nome de Josué.)

[[v4-13-17]]

^<<v4-13-17,17>>^ Quando Moisés os enviou para fazer o reconhecimento da terra, deu-lhes as seguintes instruções: "Subam pelo Neguebe até a região montanhosa.

[[v4-13-18]]

^<<v4-13-18,18>>^ Vejam como é a terra e descubram se seus habitantes são fortes ou fracos, poucos ou muitos.

[[v4-13-19]]

^<<v4-13-19,19>>^ Observem em que tipo de terra vivem, se é boa ou ruim. As cidades têm muralhas ou são desprotegidas como campos abertos?

[[v4-13-20]]

^<<v4-13-20,20>>^ O solo é fértil ou pobre? A região tem muitas árvores? Façam todo o possível para trazer de volta amostras das colheitas que encontrarem". (Era a época da colheita das primeiras uvas maduras.)

[[v4-13-21]]

^<<v4-13-21,21>>^ Eles subiram e fizeram o reconhecimento da terra, desde o deserto de Zim até Reobe, perto de Lebo-Hamate.

[[v4-13-22]]

^<<v4-13-22,22>>^ Subiram pelo Neguebe e chegaram a Hebrom, onde viviam Aimã, Sesai e Talmai, todos descendentes de Enaque. (A antiga cidade de Hebrom foi fundada sete anos antes da cidade egípcia de Zoã.)

[[v4-13-23]]

^<<v4-13-23,23>>^ Quando chegaram ao vale de Escol, cortaram um ramo com um só cacho de uvas tão grande que dois deles precisaram carregá-lo numa vara. Levaram também amostras de romãs e figos.

[[v4-13-24]]

^<<v4-13-24,24>>^ Aquele lugar recebeu o nome de vale de Escol, por causa do cacho de uvas que os israelitas cortaram ali.

[[v4-13-25]]

^<<v4-13-25,25>>^ Depois de passarem quarenta dias explorando a terra, os homens retornaram

[[v4-13-26]]

^<<v4-13-26,26>>^ a Moisés, a Arão e a toda a comunidade de Israel em Cades, no deserto de Parã. Relataram o que tinham visto a toda a comunidade e mostraram os frutos que trouxeram da terra.

[[v4-13-27]]

^<<v4-13-27,27>>^ Este foi o relatório que deram a Moisés: "Entramos na terra à qual você nos enviou e, de fato, é uma terra que produz leite e mel com fartura. Aqui está o tipo de fruto que nela há.

[[v4-13-28]]

^<<v4-13-28,28>>^ Contudo, o povo que vive ali é poderoso, e suas cidades são grandes e fortificadas. Vimos até os descendentes de Enaque!

[[v4-13-29]]

^<<v4-13-29,29>>^ Os amalequitas vivem no Neguebe, e os hititas, jebuseus e amorreus vivem na região montanhosa. Os cananeus vivem perto do litoral do mar Mediterrâneo e no vale do Jordão".

[[v4-13-30]]

^<<v4-13-30,30>>^ Calebe tentou acalmar o povo que estava diante de Moisés. "Vamos partir agora mesmo para tomar a terra!", disse ele. "Com certeza podemos conquistá-la!"

[[v4-13-31]]

^<<v4-13-31,31>>^ Mas os outros homens que tinham feito com ele o reconhecimento da terra discordaram: "Não podemos enfrentá-los! São mais fortes que nós!".

[[v4-13-32]]

^<<v4-13-32,32>>^ Então espalharam entre os israelitas um relatório negativo sobre a terra, dizendo: "A terra que atravessamos ao fazer o reconhecimento devorará quem for morar ali! Todas as pessoas que vimos são enormes.

[[v4-13-33]]

^<<v4-13-33,33>>^ Vimos até gigantes, os descendentes de Enaque! Perto deles, nos sentimos como gafanhotos, e também era assim que parecíamos para eles".

'''

xref:004-numeros/004-numeros-012.adoc#v4-12-0[&#60; Capítulo Anterior] | <<v4-13-0,Topo>> | xref:004-numeros/004-numeros-014.adoc#v4-14-0[Próximo Capítulo &#62;]