include::./index.adoc[]

[[v4-24-0]]
=== Números, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v4-24-1]]

^<<v4-24-1,1>>^ Quando Balaão percebeu que o SENHOR se agradava de abençoar Israel, não recorreu à adivinhação como antes. Em vez disso, voltou-se em direção ao deserto,

[[v4-24-2]]

^<<v4-24-2,2>>^ onde viu o povo de Israel acampado de acordo com suas tribos. Então o Espírito de Deus veio sobre Balaão,

[[v4-24-3]]

^<<v4-24-3,3>>^ e ele transmitiu a seguinte mensagem: "Esta é a mensagem de Balaão, filho de Beor, a mensagem do homem cujos olhos veem com clareza,

[[v4-24-4]]

^<<v4-24-4,4>>^ a mensagem daquele que ouve as palavras de Deus, que tem uma visão concedida pelo Todo-poderoso, que se curva com os olhos bem abertos:

[[v4-24-5]]

^<<v4-24-5,5>>^ Como são belas suas tendas, ó Jacó! Como são lindas suas moradas, ó Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ Estendem-se diante de mim como palmeiras, como jardins à beira do rio. São como aloés plantados pelo SENHOR, como cedros junto às águas.

[[v4-24-7]]

^<<v4-24-7,7>>^ Águas jorrarão de seus baldes, e suas sementes serão bem regadas. Seu rei será maior que Agague, e seu reino será exaltado.

[[v4-24-8]]

^<<v4-24-8,8>>^ Deus os tirou do Egito; ele é forte como o boi selvagem. Devora todas as nações que se opõem a ele; despedaça seus ossos e com flechas as atravessa.

[[v4-24-9]]

^<<v4-24-9,9>>^ Como leão, Israel se agacha e se deita; como a leoa, quem tem coragem de acordá-lo? Sejam abençoados os que o abençoarem e amaldiçoados os que o amaldiçoarem".

[[v4-24-10]]

^<<v4-24-10,10>>^ O rei Balaque se enfureceu contra Balaão e, batendo as palmas das mãos, gritou: "Eu o chamei para amaldiçoar meus inimigos; em vez disso, você os abençoou três vezes!

[[v4-24-11]]

^<<v4-24-11,11>>^ Vá embora! Volte para casa! Eu lhe prometi uma grande recompensa, mas o SENHOR o impediu de recebê-la!".

[[v4-24-12]]

^<<v4-24-12,12>>^ Balaão disse a Balaque: "Você não se lembra do que expliquei a seus mensageiros? Eu lhes avisei:

[[v4-24-13]]

^<<v4-24-13,13>>^ ‘Mesmo que Balaque me desse seu palácio cheio de prata e ouro, eu não poderia fazer coisa alguma, boa ou má, contra a vontade do SENHOR’! Avisei que só poderia falar aquilo que o SENHOR dissesse!

[[v4-24-14]]

^<<v4-24-14,14>>^ Agora, volto para meu povo, mas primeiro lhe direi o que esse povo fará ao seu povo no futuro".

[[v4-24-15]]

^<<v4-24-15,15>>^ Balaão transmitiu a seguinte mensagem: "Esta é a mensagem de Balaão, filho de Beor, a mensagem do homem cujos olhos veem com clareza,

[[v4-24-16]]

^<<v4-24-16,16>>^ a mensagem daquele que ouve as palavras de Deus, que possui conhecimento dado pelo Altíssimo, que tem uma visão concedida pelo Todo-poderoso, que se curva com os olhos bem abertos:

[[v4-24-17]]

^<<v4-24-17,17>>^ Eu o vejo, mas não agora; eu o avisto, mas não de perto. Uma estrela surgirá de Jacó, um cetro se levantará de Israel. Esmagará a cabeça do povo de Moabe e rachará o crânio dos descendentes de Sete.

[[v4-24-18]]

^<<v4-24-18,18>>^ Tomará posse de Edom e conquistará seu inimigo, Seir, enquanto Israel marcha adiante em triunfo.

[[v4-24-19]]

^<<v4-24-19,19>>^ De Jacó surgirá um governante que destruirá os sobreviventes de Ar".

[[v4-24-20]]

^<<v4-24-20,20>>^ Então Balaão olhou na direção do povo de Amaleque e transmitiu a seguinte mensagem: "Amaleque era a primeira de todas as nações, mas seu destino é a destruição!".

[[v4-24-21]]

^<<v4-24-21,21>>^ Em seguida, Balaão olhou na direção dos queneus e transmitiu a seguinte mensagem: "Sua habitação é segura; seu ninho está apoiado nas rochas.

[[v4-24-22]]

^<<v4-24-22,22>>^ Os queneus, porém, serão destruídos quando Assur os levar prisioneiros".

[[v4-24-23]]

^<<v4-24-23,23>>^ Balaão concluiu sua mensagem com estas palavras: "Ai! Quem pode sobreviver quando Deus fizer essas coisas?

[[v4-24-24]]

^<<v4-24-24,24>>^ Navios virão do litoral de Chipre, oprimirão Assur e afligirão Héber, mas eles também serão destruídos".

[[v4-24-25]]

^<<v4-24-25,25>>^ Então Balaão se levantou e voltou para sua terra, e Balaque também seguiu seu caminho.

'''

xref:004-numeros/004-numeros-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numeros/004-numeros-025.adoc#v4-25-0[Próximo Capítulo &#62;]