include::./index.adoc[]

[[v11-21-0]]
=== 1 Reis, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v11-21-1]]

^<<v11-21-1,1>>^ Naquela época, um homem chamado Nabote, de Jezreel, possuía um vinhedo que ficava ao lado do palácio de Acabe, rei de Samaria.

[[v11-21-2]]

^<<v11-21-2,2>>^ Certo dia, Acabe disse a Nabote: "Como sua videira fica tão próxima do meu palácio, quero comprá-la para fazer uma horta. Em troca, darei a você uma videira melhor, ou, se preferir, pagarei o valor em dinheiro".

[[v11-21-3]]

^<<v11-21-3,3>>^ Nabote, porém, respondeu: "O SENHOR me livre de lhe entregar a herança que recebi de meus antepassados!".

[[v11-21-4]]

^<<v11-21-4,4>>^ Então Acabe foi para casa indignado e aborrecido por causa da resposta de Nabote. O rei foi deitar-se, virou o rosto e não quis comer.

[[v11-21-5]]

^<<v11-21-5,5>>^ "Qual é o problema?", perguntou sua esposa Jezabel. "Por que você está tão aborrecido que nem quer comer?"

[[v11-21-6]]

^<<v11-21-6,6>>^ Acabe respondeu: "Pedi a Nabote, de Jezreel, que me vendesse sua videira ou que a trocasse por outra, mas ele não quis".

[[v11-21-7]]

^<<v11-21-7,7>>^ "Afinal, você é o rei de Israel ou não é?", disse Jezabel. "Levante-se e coma alguma coisa, e não se preocupe com isso. Conseguirei para você a videira de Nabote."

[[v11-21-8]]

^<<v11-21-8,8>>^ Então ela escreveu cartas em nome de Acabe, selou-as com o selo do rei e as enviou para as autoridades e outros líderes da cidade onde Nabote morava.

[[v11-21-9]]

^<<v11-21-9,9>>^ Nas cartas, ela ordenava: "Reúnam os habitantes da cidade para jejuar e coloquem Nabote num lugar onde todos possam vê-lo.

[[v11-21-10]]

^<<v11-21-10,10>>^ Mandem sentar-se em frente dele dois homens de mau caráter que o acusem de amaldiçoar a Deus e o rei. Depois, levem-no para fora e matem-no por apedrejamento".

[[v11-21-11]]

^<<v11-21-11,11>>^ As autoridades e os outros líderes da cidade seguiram as instruções dadas por Jezabel em suas cartas.

[[v11-21-12]]

^<<v11-21-12,12>>^ Convocaram os habitantes da cidade para um jejum e colocaram Nabote num lugar onde todos podiam vê-lo.

[[v11-21-13]]

^<<v11-21-13,13>>^ Então dois homens de mau caráter vieram, sentaram-se de frente para ele e o acusaram diante de todo o povo, dizendo: "Ele amaldiçoou a Deus e o rei!". Em seguida, foi arrastado para fora da cidade e morto por apedrejamento.

[[v11-21-14]]

^<<v11-21-14,14>>^ Os líderes da cidade mandaram avisar Jezabel: "Nabote foi apedrejado e está morto".

[[v11-21-15]]

^<<v11-21-15,15>>^ Quando Jezabel ouviu a notícia, disse a Acabe: "Lembra-se da videira que Nabote se recusou a vender? Agora você pode ficar com ela. Nabote está morto".

[[v11-21-16]]

^<<v11-21-16,16>>^ Acabe desceu de imediato à videira de Nabote para tomar posse dela.

[[v11-21-17]]

^<<v11-21-17,17>>^ Contudo, o SENHOR disse a Elias, de Tisbe:

[[v11-21-18]]

^<<v11-21-18,18>>^ "Vá encontrar-se com Acabe, rei de Israel, que governa em Samaria. Ele estará na videira de Nabote, para tomar posse dela.

[[v11-21-19]]

^<<v11-21-19,19>>^ Transmita-lhe esta mensagem: ‘Assim diz o SENHOR: Não foi suficiente para você matar Nabote? Era preciso que também roubasse a propriedade dele? Por causa do que você fez, os cães lamberão seu sangue no mesmo lugar onde lamberam o sangue de Nabote’".

[[v11-21-20]]

^<<v11-21-20,20>>^ "Quer dizer que você me encontrou, meu inimigo!", disse Acabe a Elias. "Sim", respondeu Elias. "Vim porque você se vendeu para fazer o que é mau aos olhos do SENHOR.

[[v11-21-21]]

^<<v11-21-21,21>>^ Agora o SENHOR diz: ‘Trarei desgraça sobre você e o exterminarei, e destruirei todos os seus descendentes do sexo masculino em Israel, tanto escravos como livres.

[[v11-21-22]]

^<<v11-21-22,22>>^ Acabarei com sua família como fiz com a família de Jeroboão, filho de Nebate, e com a família de Baasa, filho de Aías, pois você provocou minha ira e levou Israel a pecar’.

[[v11-21-23]]

^<<v11-21-23,23>>^ "E quanto a Jezabel, o SENHOR diz: ‘Cães devorarão o corpo de Jezabel no campo em Jezreel’.

[[v11-21-24]]

^<<v11-21-24,24>>^ "Os membros da família de Acabe que morrerem na cidade serão comidos pelos cães, e os que morrerem no campo serão comidos pelos abutres."

[[v11-21-25]]

^<<v11-21-25,25>>^ Não houve ninguém que tenha se vendido tão completamente para fazer o que é mau aos olhos do SENHOR como Acabe, influenciado por sua esposa Jezabel.

[[v11-21-26]]

^<<v11-21-26,26>>^ Sua prática mais repugnante foi adorar ídolos como haviam feito os amorreus, povo que o SENHOR tinha expulsado de diante dos israelitas.

[[v11-21-27]]

^<<v11-21-27,27>>^ Quando Acabe ouviu essa mensagem, rasgou suas roupas, vestiu-se de pano de saco e jejuou. Passou a dormir em cima de panos de saco e a andar cabisbaixo.

[[v11-21-28]]

^<<v11-21-28,28>>^ Então Elias, de Tisbe, recebeu outra mensagem do SENHOR:

[[v11-21-29]]

^<<v11-21-29,29>>^ "Vê como Acabe se humilhou diante de mim? Por isso, não trarei calamidade durante sua vida. Farei cair a calamidade sobre os filhos dele; destruirei sua dinastia".

'''

xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[&#60; Capítulo Anterior] | <<v11-21-0,Topo>> | xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[Próximo Capítulo &#62;]