include::./index.adoc[]

[[v11-19-0]]
=== 1 Reis, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v11-19-1]]

^<<v11-19-1,1>>^ Acabe contou a Jezabel tudo que Elias havia feito, incluindo o modo como havia matado todos os profetas de Baal.

[[v11-19-2]]

^<<v11-19-2,2>>^ Por isso, Jezabel enviou esta mensagem a Elias: "Que os deuses me castiguem severamente se, até amanhã nesta hora, eu não fizer a você o que você fez aos profetas de Baal!".

[[v11-19-3]]

^<<v11-19-3,3>>^ Elias teve medo e fugiu para salvar a vida. Foi para Berseba, uma cidade em Judá, e ali deixou seu servo.

[[v11-19-4]]

^<<v11-19-4,4>>^ Depois, foi sozinho para o deserto, caminhando o dia todo. Sentou-se debaixo de um pé de giesta e orou, pedindo para morrer. "Já basta, SENHOR", disse ele. "Tira minha vida, pois não sou melhor que meus antepassados que já morreram."

[[v11-19-5]]

^<<v11-19-5,5>>^ Então ele se deitou debaixo do pé de giesta e dormiu. Enquanto dormia, um anjo o tocou e disse: "Levante-se e coma!".

[[v11-19-6]]

^<<v11-19-6,6>>^ Elias olhou em redor e viu, perto de sua cabeça, um pão assado sobre pedras quentes e um jarro de água. Ele comeu, bebeu e se deitou novamente.

[[v11-19-7]]

^<<v11-19-7,7>>^ O anjo do SENHOR voltou, tocou-o mais uma vez e disse: "Levante-se e coma um pouco mais, do contrário não aguentará a viagem que tem pela frente".

[[v11-19-8]]

^<<v11-19-8,8>>^ Elias se levantou, comeu e bebeu, e o alimento lhe deu forças para uma jornada de quarenta dias e quarenta noites até o monte Sinai, o monte de Deus.

[[v11-19-9]]

^<<v11-19-9,9>>^ Ali encontrou uma caverna onde passou a noite. Então o SENHOR lhe disse: "O que você faz aqui, Elias?".

[[v11-19-10]]

^<<v11-19-10,10>>^ Ele respondeu: "Tenho servido com zelo ao SENHOR, o Deus dos Exércitos. Contudo, os israelitas quebraram a aliança contigo, derrubaram teus altares e mataram todos os teus profetas. Sou o único que restou, e agora também procuram me matar".

[[v11-19-11]]

^<<v11-19-11,11>>^ "Saia e ponha-se diante de mim no monte", disse o SENHOR. E, enquanto Elias estava ali, o SENHOR passou, e um forte vendaval atingiu o monte. Era tão intenso que as pedras se soltavam do monte diante do SENHOR, mas o SENHOR não estava no vento. Depois do vento houve um terremoto, mas o SENHOR não estava no terremoto.

[[v11-19-12]]

^<<v11-19-12,12>>^ Depois do terremoto houve fogo, mas o SENHOR não estava no fogo. E, depois do fogo, veio um suave sussurro.

[[v11-19-13]]

^<<v11-19-13,13>>^ Quando Elias o ouviu, cobriu o rosto com a capa, saiu e ficou na entrada da caverna. E uma voz disse: "O que você faz aqui, Elias?".

[[v11-19-14]]

^<<v11-19-14,14>>^ Ele respondeu outra vez: "Tenho servido com zelo ao SENHOR, o Deus dos Exércitos. Contudo, os israelitas quebraram a aliança contigo, derrubaram teus altares e mataram todos os teus profetas. Sou o único que restou, e agora também procuram me matar".

[[v11-19-15]]

^<<v11-19-15,15>>^ Então o SENHOR lhe disse: "Volte pelo caminho por onde veio e vá para o deserto de Damasco. Quando chegar lá, unja Hazael para ser rei da Síria.

[[v11-19-16]]

^<<v11-19-16,16>>^ Depois, unja também Jeú, neto de Ninsi, para ser rei de Israel, e unja Eliseu, filho de Safate, da cidade de Abel-Meolá, para substituir você como meu profeta.

[[v11-19-17]]

^<<v11-19-17,17>>^ Quem escapar da espada de Hazael será morto por Jeú, e quem escapar da espada de Jeú será morto por Eliseu.

[[v11-19-18]]

^<<v11-19-18,18>>^ No entanto, preservarei sete mil de Israel que nunca se prostraram diante de Baal nem o beijaram!".

[[v11-19-19]]

^<<v11-19-19,19>>^ Elias partiu e encontrou Eliseu, filho de Safate, arando um campo. Havia doze parelhas de bois no campo, e Eliseu arava com a última parelha. Elias se aproximou de Eliseu, lançou sua capa sobre os ombros dele e continuou a caminhar.

[[v11-19-20]]

^<<v11-19-20,20>>^ Eliseu deixou os bois ali, correu atrás de Elias e disse: "Primeiro deixe-me dar um beijo de despedida em meu pai e em minha mãe; então o seguirei!". Elias respondeu: "Pode voltar, mas pense no que lhe fiz".

[[v11-19-21]]

^<<v11-19-21,21>>^ Eliseu voltou para sua parelha de bois e os matou. Usou a madeira do arado para fazer fogo e assar a carne. Distribuiu a carne para o povo da cidade, e todos eles comeram. Então partiu com Elias, como seu ajudante.

'''

xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[&#60; Capítulo Anterior] | <<v11-19-0,Topo>> | xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[Próximo Capítulo &#62;]