include::./index.adoc[]

[[v11-9-0]]
=== 1 Reis, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v11-9-1]]

^<<v11-9-1,1>>^ Salomão terminou de construir o templo do SENHOR e o palácio real. Concluiu tudo que havia planejado fazer.

[[v11-9-2]]

^<<v11-9-2,2>>^ Então o SENHOR apareceu a Salomão pela segunda vez, como havia aparecido em Gibeom.

[[v11-9-3]]

^<<v11-9-3,3>>^ O SENHOR lhe disse: "Ouvi sua oração e sua súplica. Consagrei este templo que você construiu, onde meu nome será honrado para sempre. Olharei continuamente para ele, com todo o meu coração.

[[v11-9-4]]

^<<v11-9-4,4>>^ "Quanto a você, se me seguir com integridade e retidão, como fez seu pai, Davi, obedecendo a todos os meus mandamentos, decretos e estatutos,

[[v11-9-5]]

^<<v11-9-5,5>>^ estabelecerei o trono de sua dinastia sobre Israel para sempre. Pois fiz esta promessa a seu pai, Davi: ‘Um de seus descendentes sempre se sentará no trono de Israel’.

[[v11-9-6]]

^<<v11-9-6,6>>^ "Mas, se você ou seus descendentes me abandonarem e desobedecerem a meus mandamentos e decretos, seguindo e adorando outros deuses,

[[v11-9-7]]

^<<v11-9-7,7>>^ arrancarei Israel desta terra que lhe dei. Rejeitarei este templo que consagrei em honra ao meu nome, e farei de Israel objeto de zombaria e desprezo entre as nações.

[[v11-9-8]]

^<<v11-9-8,8>>^ E, embora este templo seja agora imponente, todos que passarem perto dele ficarão chocados e horrorizados. Perguntarão: ‘Por que o SENHOR fez coisas tão terríveis com esta terra e com este templo?’.

[[v11-9-9]]

^<<v11-9-9,9>>^ "E a resposta será: ‘Porque os israelitas abandonaram o SENHOR, seu Deus, que tirou seus antepassados da terra do Egito e, em lugar dele, adoraram outros deuses e se prostraram diante deles. Por isso o SENHOR trouxe sobre eles essas calamidades’".

[[v11-9-10]]

^<<v11-9-10,10>>^ Salomão levou vinte anos para construir o templo do SENHOR e o palácio real. Depois desse tempo,

[[v11-9-11]]

^<<v11-9-11,11>>^ Salomão deu a Hirão, rei de Tiro, vinte cidades da Galileia. Hirão havia fornecido toda a madeira de cedro e de cipreste e todo o ouro que Salomão havia pedido.

[[v11-9-12]]

^<<v11-9-12,12>>^ Contudo, quando Hirão veio de Tiro para ver as cidades que Salomão lhe tinha dado, não ficou nada satisfeito com elas.

[[v11-9-13]]

^<<v11-9-13,13>>^ "Que espécie de cidades são essas, meu irmão?", perguntou ele. Então Hirão chamou aquela região de Cabul, como é conhecida até hoje.

[[v11-9-14]]

^<<v11-9-14,14>>^ Hirão tinha enviado a Salomão 4.200 quilos de ouro.

[[v11-9-15]]

^<<v11-9-15,15>>^ Este é o relato do trabalho forçado que o rei Salomão impôs para a construção do templo do SENHOR, do palácio real, do aterro e do muro de Jerusalém, além das cidades de Hazor, Megido e Gezer.

[[v11-9-16]]

^<<v11-9-16,16>>^ (O faraó, rei do Egito, havia atacado e conquistado Gezer. Matou seus habitantes cananeus, incendiou a cidade e a deu como presente à sua filha quando ela se casou com Salomão.

[[v11-9-17]]

^<<v11-9-17,17>>^ Assim, Salomão reconstruiu a cidade de Gezer.) Também construiu Bete-Horom Baixa,

[[v11-9-18]]

^<<v11-9-18,18>>^ Baalate e Tamar, no deserto daquela região.

[[v11-9-19]]

^<<v11-9-19,19>>^ Construiu cidades para servirem como centros de armazenamento e também cidades para seus carros de guerra e cavalos. Construiu tudo que desejou em Jerusalém, no Líbano e em todo o reino.

[[v11-9-20]]

^<<v11-9-20,20>>^ Ainda havia na terra habitantes que não eram israelitas: amorreus, hititas, ferezeus, heveus e jebuseus.

[[v11-9-21]]

^<<v11-9-21,21>>^ Eram descendentes das nações que os israelitas não haviam destruído completamente. Salomão os recrutou para trabalhos forçados, e é nessa condição que trabalham até hoje.

[[v11-9-22]]

^<<v11-9-22,22>>^ Mas Salomão não recrutou nenhum israelita para trabalhos forçados; eles o serviram como soldados, funcionários do governo, oficiais e capitães de seu exército, comandantes de carros de guerra e cavaleiros.

[[v11-9-23]]

^<<v11-9-23,23>>^ Nomeou 550 israelitas para supervisionarem os trabalhadores de seus vários projetos.

[[v11-9-24]]

^<<v11-9-24,24>>^ Salomão transferiu a residência de sua esposa, a filha do faraó, da Cidade de Davi para o novo palácio que ele havia construído para ela. Depois, construiu o aterro.

[[v11-9-25]]

^<<v11-9-25,25>>^ Três vezes por ano, Salomão apresentava holocaustos e ofertas de paz sobre o altar que havia construído para o SENHOR e também queimava incenso perante o SENHOR. Assim, ele terminou o trabalho de construção do templo.

[[v11-9-26]]

^<<v11-9-26,26>>^ O rei Salomão também construiu navios em Eziom-Geber, um porto próximo a Elate, na terra de Edom, às margens do mar Vermelho.

[[v11-9-27]]

^<<v11-9-27,27>>^ Hirão enviou uma frota com marinheiros experientes para servirem nas tripulações dos navios, junto com os marinheiros de Salomão.

[[v11-9-28]]

^<<v11-9-28,28>>^ Navegaram a Ofir e trouxeram para Salomão 14.700 quilos de ouro.

'''

xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[&#60; Capítulo Anterior] | <<v11-9-0,Topo>> | xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[Próximo Capítulo &#62;]