include::./index.adoc[]

[[v11-10-0]]
=== 1 Reis, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v11-10-1]]

^<<v11-10-1,1>>^ Quando a rainha de Sabá ouviu falar da fama de Salomão, que honrava o nome do SENHOR, foi até ele para pô-lo à prova com perguntas difíceis.

[[v11-10-2]]

^<<v11-10-2,2>>^ Chegou a Jerusalém com uma comitiva numerosa e uma imensa caravana de camelos carregados de especiarias, grande quantidade de ouro e pedras preciosas. Quando se encontrou com Salomão, conversou com ele a respeito de tudo que tinha em mente.

[[v11-10-3]]

^<<v11-10-3,3>>^ Salomão respondeu a todas as suas perguntas; nada era difícil demais para o rei explicar.

[[v11-10-4]]

^<<v11-10-4,4>>^ Quando a rainha de Sabá percebeu quanto Salomão era sábio e viu o palácio que ele havia construído,

[[v11-10-5]]

^<<v11-10-5,5>>^ a comida que era servida às mesas do rei, os alojamentos e a organização de seus oficiais e servos, os trajes esplêndidos que vestiam, os copeiros da corte e os holocaustos que Salomão oferecia no templo do SENHOR, ficou muito admirada.

[[v11-10-6]]

^<<v11-10-6,6>>^ Disse ela ao rei: "É verdade tudo que ouvi em meu país a respeito de suas realizações e de sua sabedoria!

[[v11-10-7]]

^<<v11-10-7,7>>^ Não acreditava no que diziam até que cheguei aqui e vi com os próprios olhos. Aliás, não tinham me contado nem a metade! Sua sabedoria e prosperidade vão muito além do que ouvi.

[[v11-10-8]]

^<<v11-10-8,8>>^ Como deve ser feliz o seu povo! Que privilégio para seus oficiais estarem em sua presença todos os dias, ouvindo sua sabedoria!

[[v11-10-9]]

^<<v11-10-9,9>>^ Louvado seja o SENHOR, seu Deus, que se agradou de você e o colocou no trono de Israel. Por causa do amor eterno do SENHOR por Israel, ele o fez rei para governar com justiça e retidão".

[[v11-10-10]]

^<<v11-10-10,10>>^ Então ela presenteou o rei com 4.200 quilos de ouro, especiarias em grande quantidade e pedras preciosas. Nunca mais foram recebidas tantas especiarias quanto as que a rainha de Sabá deu ao rei Salomão.

[[v11-10-11]]

^<<v11-10-11,11>>^ (Além disso, os navios de Hirão trouxeram ouro de Ofir e grandes carregamentos de madeira de sândalo e pedras preciosas.

[[v11-10-12]]

^<<v11-10-12,12>>^ O rei usou a madeira de sândalo para fazer corrimões para o templo e para o palácio real, e também liras e harpas para os músicos. Nunca antes nem depois se viu tamanho suprimento de madeira de sândalo.)

[[v11-10-13]]

^<<v11-10-13,13>>^ O rei Salomão deu à rainha de Sabá tudo que ela pediu, além dos presentes costumeiros que ele já havia entregado com generosidade. Então ela e sua comitiva regressaram para sua terra.

[[v11-10-14]]

^<<v11-10-14,14>>^ A cada ano, Salomão recebia cerca de 23.300 quilos de ouro,

[[v11-10-15]]

^<<v11-10-15,15>>^ sem contar a renda adicional proveniente dos mercadores e comerciantes, de todos os reis da Arábia e dos governadores do país.

[[v11-10-16]]

^<<v11-10-16,16>>^ O rei Salomão fez duzentos escudos grandes de ouro batido, cada um pesando 7,2 quilos.

[[v11-10-17]]

^<<v11-10-17,17>>^ Também fez trezentos escudos menores de ouro batido, cada um pesando 1,8 quilo. O rei colocou esses escudos no Palácio da Floresta do Líbano.

[[v11-10-18]]

^<<v11-10-18,18>>^ Então o rei fez um grande trono de marfim revestido de ouro puro.

[[v11-10-19]]

^<<v11-10-19,19>>^ O trono tinha seis degraus e um encosto arredondado. De cada lado do assento havia um apoio para o braço e, junto de cada apoio, a escultura de um leão.

[[v11-10-20]]

^<<v11-10-20,20>>^ Também havia outros doze leões, um de cada lado dos seis degraus. Nenhum outro trono em todo o mundo se comparava ao de Salomão.

[[v11-10-21]]

^<<v11-10-21,21>>^ Todas as taças do rei Salomão eram de ouro, e todos os utensílios do Palácio da Floresta do Líbano eram de ouro puro. Não eram de prata, pois nos dias de Salomão a prata era considerada um metal sem valor.

[[v11-10-22]]

^<<v11-10-22,22>>^ O rei tinha uma frota de navios mercantes que navegavam com os navios de Hirão. Uma vez a cada três anos, as embarcações voltavam trazendo ouro, prata, marfim, macacos e pavões.

[[v11-10-23]]

^<<v11-10-23,23>>^ Salomão se tornou o mais rico e sábio de todos os reis da terra.

[[v11-10-24]]

^<<v11-10-24,24>>^ Gente de todas as nações vinha consultá-lo e ouvir a sabedoria que Deus lhe tinha dado.

[[v11-10-25]]

^<<v11-10-25,25>>^ A cada ano, os visitantes traziam presentes de prata e ouro, roupas, armas, especiarias, cavalos e mulas.

[[v11-10-26]]

^<<v11-10-26,26>>^ Salomão ajuntou muitos carros de guerra e cavalos. Possuía 1.400 carros de guerra e 12.000 cavalos. Mantinha alguns deles nas cidades designadas para guardar esses carros de guerra e outras perto dele, em Jerusalém.

[[v11-10-27]]

^<<v11-10-27,27>>^ O rei tornou a prata tão comum em Jerusalém como as pedras. E havia tanta madeira valiosa de cedro como as figueiras-bravas que crescem nas colinas de Judá.

[[v11-10-28]]

^<<v11-10-28,28>>^ Os cavalos de Salomão eram importados do Egito e da Cilícia; os comerciantes do rei os adquiriam da Cilícia pelo preço de mercado.

[[v11-10-29]]

^<<v11-10-29,29>>^ Naquela época, um carro de guerra do Egito custava 600 peças de prata, e um cavalo, 150 peças de prata. Depois, eram exportados aos reis dos hititas e aos reis da Síria.

'''

xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[&#60; Capítulo Anterior] | <<v11-10-0,Topo>> | xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[Próximo Capítulo &#62;]