include::./index.adoc[]

[[v11-18-0]]
=== 1 Reis, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v11-18-1]]

^<<v11-18-1,1>>^ Algum tempo depois, no terceiro ano da seca, o SENHOR disse a Elias: "Vá apresentar-se ao rei Acabe. Diga-lhe que enviarei chuva".

[[v11-18-2]]

^<<v11-18-2,2>>^ Elias foi apresentar-se a Acabe. A fome era severa em Samaria.

[[v11-18-3]]

^<<v11-18-3,3>>^ Acabe mandou chamar Obadias, o administrador do palácio. (Obadias temia profundamente o SENHOR.

[[v11-18-4]]

^<<v11-18-4,4>>^ Certa vez, quando Jezabel havia tentado matar todos os profetas do SENHOR, Obadias escondeu cem deles em duas cavernas. Colocou cinquenta em cada caverna e forneceu alimento e água para eles.)

[[v11-18-5]]

^<<v11-18-5,5>>^ Acabe disse a Obadias: "Precisamos ir a todas as fontes e vales na terra. Quem sabe encontraremos pasto suficiente para salvar pelo menos alguns de meus cavalos e mulas!".

[[v11-18-6]]

^<<v11-18-6,6>>^ Então dividiram o território entre si. Acabe foi para um lado, e Obadias, para o outro.

[[v11-18-7]]

^<<v11-18-7,7>>^ Enquanto Obadias caminhava, viu de repente Elias vindo em sua direção. Ao reconhecê-lo, Obadias curvou-se diante dele com o rosto no chão. "É o senhor mesmo, meu senhor Elias?", perguntou.

[[v11-18-8]]

^<<v11-18-8,8>>^ "Sim, sou eu", respondeu Elias. "Agora vá e diga ao rei: ‘Elias está aqui’."

[[v11-18-9]]

^<<v11-18-9,9>>^ Obadias, porém, protestou: "Que mal lhe fiz para que me envie para morrer nas mãos de Acabe?

[[v11-18-10]]

^<<v11-18-10,10>>^ Pois, tão certo como vive o SENHOR, seu Deus, o rei o procurou em todas as nações e reinos da terra, de uma extremidade à outra. E cada vez que lhe diziam: ‘Elias não está aqui’, o rei Acabe fazia o rei daquela nação jurar que tinha falado a verdade.

[[v11-18-11]]

^<<v11-18-11,11>>^ E agora o senhor diz: ‘Vá e diga ao rei: Elias está aqui’.

[[v11-18-12]]

^<<v11-18-12,12>>^ Mas, assim que eu o deixar, o Espírito do SENHOR o levará embora, sabe-se lá para onde, e quando Acabe chegar e não o encontrar, ele me matará. E, no entanto, tenho servido fielmente ao SENHOR toda a minha vida.

[[v11-18-13]]

^<<v11-18-13,13>>^ Ninguém lhe falou da ocasião em que Jezabel tentou matar os profetas do SENHOR? Escondi cem deles em duas cavernas e lhes forneci alimento e água.

[[v11-18-14]]

^<<v11-18-14,14>>^ E agora o senhor diz: ‘Vá e diga ao rei: Elias está aqui’. Se eu fizer isso, certamente Acabe me matará!".

[[v11-18-15]]

^<<v11-18-15,15>>^ Mas Elias disse: "Tão certo como vive o SENHOR dos Exércitos, em cuja presença estou, hoje mesmo me apresentarei ao rei Acabe".

[[v11-18-16]]

^<<v11-18-16,16>>^ Então Obadias foi dizer a Acabe que Elias tinha vindo, e Acabe saiu para encontrar-se com Elias.

[[v11-18-17]]

^<<v11-18-17,17>>^ Quando Acabe o viu, disse: "É você mesmo, perturbador de Israel?".

[[v11-18-18]]

^<<v11-18-18,18>>^ "Não causei problema algum a Israel", respondeu Elias. "O senhor e sua família é que são os perturbadores, pois se recusaram a obedecer aos mandamentos do SENHOR e, em vez disso, adoraram imagens de Baal.

[[v11-18-19]]

^<<v11-18-19,19>>^ Agora, convoque todo o Israel para encontrar-se comigo no monte Carmelo, além dos 450 profetas de Baal e os 400 profetas de Aserá que comem à mesa de Jezabel."

[[v11-18-20]]

^<<v11-18-20,20>>^ Acabe convocou todo o povo de Israel e os profetas para se reunirem no monte Carmelo.

[[v11-18-21]]

^<<v11-18-21,21>>^ Elias se colocou diante do povo e disse: "Até quando ficarão oscilando de um lado para o outro? Se o SENHOR é Deus, sigam-no! Mas, se Baal é Deus, então sigam Baal!". O povo, contudo, ficou em silêncio.

[[v11-18-22]]

^<<v11-18-22,22>>^ Então Elias lhes disse: "Sou o único que resta dos profetas do SENHOR, mas Baal tem 450 profetas.

[[v11-18-23]]

^<<v11-18-23,23>>^ Agora, tragam para cá dois novilhos. Que os profetas de Baal escolham um deles, cortem o animal em pedaços e o coloquem sobre a lenha do altar, mas não ponham fogo na lenha. Eu prepararei o outro novilho e o colocarei sobre a lenha no altar, mas não porei fogo na lenha.

[[v11-18-24]]

^<<v11-18-24,24>>^ Então invoquem o nome de seu deus, e eu invocarei o nome do SENHOR. O deus que responder com fogo, esse é o Deus verdadeiro!". E todo o povo concordou.

[[v11-18-25]]

^<<v11-18-25,25>>^ Então Elias disse aos profetas de Baal: "Comecem vocês, pois são muitos. Escolham um dos novilhos, preparem-no e invoquem o nome de seu deus. Mas não ponham fogo na lenha".

[[v11-18-26]]

^<<v11-18-26,26>>^ Eles prepararam um dos novilhos e o colocaram sobre o altar. Invocaram o nome de Baal desde a manhã até o meio-dia e gritavam: "Ó Baal, responde-nos!", mas não houve resposta alguma. E dançavam em volta do altar que haviam feito.

[[v11-18-27]]

^<<v11-18-27,27>>^ Por volta do meio-dia, Elias começou a zombar deles: "Vocês precisam gritar mais alto", dizia ele. "Sem dúvida ele é um deus! Talvez esteja meditando ou ocupado em outro lugar. Ou talvez esteja viajando, ou dormindo, e precise ser acordado!"

[[v11-18-28]]

^<<v11-18-28,28>>^ Então gritaram mais alto e, como era seu costume, cortaram-se com facas e espadas, até sangrarem.

[[v11-18-29]]

^<<v11-18-29,29>>^ Agitaram-se em transe desde o meio-dia até a hora do sacrifício da tarde, mas não houve sequer um som, nem resposta ou reação alguma.

[[v11-18-30]]

^<<v11-18-30,30>>^ Então Elias disse ao povo: "Venham aqui!". Todos se reuniram em volta dele enquanto ele consertava o altar do SENHOR que havia sido derrubado.

[[v11-18-31]]

^<<v11-18-31,31>>^ Pegou doze pedras, uma para cada tribo dos filhos de Jacó, a quem o SENHOR disse: "Teu nome será Israel",

[[v11-18-32]]

^<<v11-18-32,32>>^ e com elas reconstruiu o altar em nome do SENHOR. Depois, cavou ao redor do altar uma valeta com capacidade suficiente para doze litros de água.

[[v11-18-33]]

^<<v11-18-33,33>>^ Empilhou lenha sobre o altar, cortou o novilho em pedaços e colocou os pedaços sobre a lenha. Em seguida, ordenou: "Encham quatro jarras grandes com água e derramem a água sobre o holocausto e a lenha".

[[v11-18-34]]

^<<v11-18-34,34>>^ Depois que fizeram isso, disse: "Façam a mesma coisa novamente". Quando terminaram, ele disse: "Agora façam o mesmo pela terceira vez". Eles seguiram sua instrução,

[[v11-18-35]]

^<<v11-18-35,35>>^ e a água corria ao redor do altar e encheu a valeta.

[[v11-18-36]]

^<<v11-18-36,36>>^ Na hora costumeira de oferecer o sacrifício da tarde, o profeta Elias se aproximou do altar e orou: "Ó SENHOR, Deus de Abraão, Isaque e Jacó, prova hoje que és Deus em Israel e que sou teu servo. Prova que fiz tudo isso por ordem tua.

[[v11-18-37]]

^<<v11-18-37,37>>^ Ó SENHOR, responde-me! Que este povo saiba que tu, ó SENHOR, és o verdadeiro Deus e estás buscando o povo de volta para ti!".

[[v11-18-38]]

^<<v11-18-38,38>>^ No mesmo instante, fogo do SENHOR desceu do céu e queimou o novilho, a madeira, as pedras e o chão, e secou até a água da valeta.

[[v11-18-39]]

^<<v11-18-39,39>>^ Quando o povo viu isso, todos se prostraram com o rosto no chão e gritaram: "O SENHOR é Deus! Sim, o SENHOR é Deus!".

[[v11-18-40]]

^<<v11-18-40,40>>^ Então Elias ordenou: "Prendam todos os profetas de Baal. Não deixem nenhum escapar!". O povo os prendeu, e Elias os levou para o riacho de Quisom e ali os matou.

[[v11-18-41]]

^<<v11-18-41,41>>^ Em seguida, Elias disse a Acabe: "Vá comer e beber, pois ouço uma forte tempestade chegando".

[[v11-18-42]]

^<<v11-18-42,42>>^ Acabe foi comer e beber. Elias, porém, subiu ao topo do monte Carmelo, prostrou-se até o chão com o rosto entre os joelhos e orou.

[[v11-18-43]]

^<<v11-18-43,43>>^ Depois, disse a seu servo: "Vá e olhe na direção do mar". O servo foi e olhou, depois voltou e disse: "Não vi nada". Sete vezes Elias mandou que ele fosse e olhasse.

[[v11-18-44]]

^<<v11-18-44,44>>^ Por fim, na sétima vez, o servo lhe disse: "Vi subir do mar uma pequena nuvem, do tamanho da mão de um homem". Então Elias lhe disse: "Vá depressa dizer a Acabe: ‘Apronte seu carro e volte para casa. Se não se apressar, a chuva o impedirá!’".

[[v11-18-45]]

^<<v11-18-45,45>>^ Em pouco tempo, o céu ficou escuro com nuvens. Um vento forte trouxe uma grande tempestade, e Acabe partiu em sua carruagem a toda velocidade para Jezreel.

[[v11-18-46]]

^<<v11-18-46,46>>^ Então o SENHOR concedeu força extraordinária a Elias. Ele prendeu a capa no cinto e correu à frente do carro de Acabe até a entrada de Jezreel.

'''

xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[Próximo Capítulo &#62;]