include::./index.adoc[]

[[v11-2-0]]
=== 1 Reis, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v11-2-1]]

^<<v11-2-1,1>>^ Quando se aproximava o momento de sua morte, Davi deu as seguintes instruções a seu filho Salomão:

[[v11-2-2]]

^<<v11-2-2,2>>^ "Vou para onde todos na terra irão algum dia. Seja corajoso e seja homem.

[[v11-2-3]]

^<<v11-2-3,3>>^ Obedeça às ordens do SENHOR, seu Deus, e siga os caminhos dele. Guarde os decretos, mandamentos, estatutos e preceitos escritos na lei de Moisés, para que seja bem-sucedido em tudo que fizer e por onde quer que for.

[[v11-2-4]]

^<<v11-2-4,4>>^ Desse modo, o SENHOR manterá a promessa que me fez: ‘Se seus descendentes viverem como devem e me seguirem fielmente de todo o coração e de toda a alma, sempre haverá um deles no trono de Israel’.

[[v11-2-5]]

^<<v11-2-5,5>>^ "Além disso, você sabe o mal que Joabe, filho de Zeruia, me fez quando assassinou os dois comandantes do exército de Israel, Abner, filho de Ner, e Amasa, filho de Jéter. Ele os matou como se fossem inimigos de guerra, mas era tempo de paz. Assim, manchou seu cinto e sua sandália com sangue inocente.

[[v11-2-6]]

^<<v11-2-6,6>>^ Faça com ele o que lhe parecer melhor, mas não deixe que envelheça e desça à sepultura em paz.

[[v11-2-7]]

^<<v11-2-7,7>>^ "Seja bondoso com os filhos de Barzilai, de Gileade. Faça deles convidados permanentes à sua mesa, pois cuidaram de mim quando eu fugia de seu irmão Absalão.

[[v11-2-8]]

^<<v11-2-8,8>>^ "E lembre-se de Simei, filho de Gera, de Baurim, da tribo de Benjamim. Ele lançou contra mim uma terrível maldição quando fui a Maanaim. Quando ele desceu ao meu encontro no rio Jordão, jurei pelo SENHOR que não o mataria.

[[v11-2-9]]

^<<v11-2-9,9>>^ Contudo, esse juramento não o torna inocente. Você é um homem sábio e saberá providenciar para ele uma morte sangrenta em sua velhice".

[[v11-2-10]]

^<<v11-2-10,10>>^ Então Davi morreu e foi sepultado na Cidade de Davi com seus antepassados.

[[v11-2-11]]

^<<v11-2-11,11>>^ Reinou por quarenta anos sobre Israel: sete em Hebrom e 33 em Jerusalém.

[[v11-2-12]]

^<<v11-2-12,12>>^ Salomão se sentou no trono de seu pai, Davi, e seu reinado foi firmemente estabelecido.

[[v11-2-13]]

^<<v11-2-13,13>>^ Certo dia, Adonias, filho de Hagite, foi falar com Bate-Seba, mãe de Salomão. Ela lhe perguntou: "Você vem em paz?". "Sim, venho em paz", disse ele.

[[v11-2-14]]

^<<v11-2-14,14>>^ "Na verdade, tenho um favor a lhe pedir." "O que é?", perguntou ela.

[[v11-2-15]]

^<<v11-2-15,15>>^ Ele respondeu: "Como você sabe, o reino era meu por direito; todo o Israel esperava que eu fosse o próximo rei. Mas a situação mudou e o reino foi para meu irmão, pois o SENHOR quis assim.

[[v11-2-16]]

^<<v11-2-16,16>>^ Agora, tenho apenas uma coisa a lhe pedir. Por favor, não deixe de me atender". "O que você quer?", perguntou ela.

[[v11-2-17]]

^<<v11-2-17,17>>^ Ele disse: "Fale em meu favor ao rei Salomão, pois sei que ele a atenderá. Peça que ele permita que eu me case com Abisague, a jovem de Suném".

[[v11-2-18]]

^<<v11-2-18,18>>^ "Está bem", respondeu Bate-Seba. "Vou falar com o rei por você."

[[v11-2-19]]

^<<v11-2-19,19>>^ Então Bate-Seba foi até o rei Salomão para falar com ele sobre o pedido de Adonias. O rei se levantou do trono para recebê-la e se curvou diante dela. Depois que o rei voltou a sentar-se, ordenou que trouxessem um trono para sua mãe, e ela se sentou à sua direita.

[[v11-2-20]]

^<<v11-2-20,20>>^ "Tenho um pequeno pedido a lhe fazer", disse ela. "Espero que não deixe de me atender." "O que é, minha mãe?", perguntou ele. "Eu não recusaria um pedido seu."

[[v11-2-21]]

^<<v11-2-21,21>>^ Ela respondeu: "Permita que seu irmão Adonias se case com Abisague, a jovem de Suném".

[[v11-2-22]]

^<<v11-2-22,22>>^ "Como pode me pedir que entregue Abisague a Adonias?", disse o rei Salomão. "Peça de uma vez que eu dê o reino para ele! Sabe bem que ele é meu irmão mais velho e que conta com o apoio do sacerdote Abiatar e de Joabe, filho de Zeruia."

[[v11-2-23]]

^<<v11-2-23,23>>^ Então o rei Salomão fez um juramento diante do SENHOR: "Que Deus me castigue severamente se Adonias não tiver selado seu destino com esse pedido.

[[v11-2-24]]

^<<v11-2-24,24>>^ O SENHOR me confirmou e me colocou no trono de meu pai, Davi, e estabeleceu minha dinastia como prometeu. Portanto, tão certo como vive o SENHOR, Adonias morrerá ainda hoje!".

[[v11-2-25]]

^<<v11-2-25,25>>^ E o rei Salomão ordenou a Benaia, filho de Joiada, que atacasse Adonias, e ele foi morto.

[[v11-2-26]]

^<<v11-2-26,26>>^ Depois, o rei disse ao sacerdote Abiatar: "Volte para sua casa em Anatote. Você merece morrer, mas não o matarei hoje, pois você carregou a arca do SENHOR Soberano para meu pai, Davi, e o acompanhou em todas as dificuldades dele".

[[v11-2-27]]

^<<v11-2-27,27>>^ Então Salomão depôs Abiatar de seu cargo de sacerdote do SENHOR e, desse modo, cumpriu a profecia do SENHOR em Siló a respeito dos descendentes de Eli.

[[v11-2-28]]

^<<v11-2-28,28>>^ Essas notícias chegaram até Joabe. Embora não houvesse apoiado a revolta de Absalão, ele tinha dado seu apoio a Adonias. Por isso, fugiu para a tenda sagrada do SENHOR e se agarrou às pontas do altar.

[[v11-2-29]]

^<<v11-2-29,29>>^ Salomão soube disso e enviou Benaia, filho de Joiada, para executá-lo.

[[v11-2-30]]

^<<v11-2-30,30>>^ Benaia foi à tenda sagrada do SENHOR e disse a Joabe: "O rei ordena que você saia!". "Não", respondeu Joabe. "Vou morrer aqui." Então Benaia voltou ao rei e lhe contou o que Joabe tinha dito.

[[v11-2-31]]

^<<v11-2-31,31>>^ "Faça o que ele diz", respondeu o rei. "Mate-o ali, junto ao altar, e sepulte-o. Assim, removerá de mim e da família de meu pai a culpa pelos crimes injustificados que Joabe cometeu.

[[v11-2-32]]

^<<v11-2-32,32>>^ O SENHOR o punirá por sua culpa no assassinato de dois homens mais justos e melhores que ele. Sem que meu pai soubesse, Joabe matou Abner, filho de Ner, comandante do exército de Israel, e Amasa, filho de Jéter, comandante do exército de Judá.

[[v11-2-33]]

^<<v11-2-33,33>>^ Que o sangue deles recaia sobre Joabe e seus descendentes para sempre, e que o SENHOR conceda paz a Davi, seus descendentes, sua dinastia e seu trono para sempre!"

[[v11-2-34]]

^<<v11-2-34,34>>^ Benaia, filho de Joiada, voltou à tenda sagrada e matou Joabe, que foi sepultado em sua casa no deserto.

[[v11-2-35]]

^<<v11-2-35,35>>^ Então o rei nomeou Benaia, filho de Joiada, comandante do exército em lugar de Joabe, e o sacerdote Zadoque em lugar de Abiatar.

[[v11-2-36]]

^<<v11-2-36,36>>^ Depois, o rei mandou chamar Simei e lhe disse: "Construa uma casa em Jerusalém e more aqui. Não dê um passo fora da cidade para ir a qualquer outro lugar.

[[v11-2-37]]

^<<v11-2-37,37>>^ No dia em que sair e atravessar o vale de Cedrom, certamente morrerá e será responsável por sua própria morte".

[[v11-2-38]]

^<<v11-2-38,38>>^ Simei respondeu: "Sua sentença é justa; farei o que meu senhor, o rei, ordena". E Simei morou em Jerusalém durante muito tempo.

[[v11-2-39]]

^<<v11-2-39,39>>^ Três anos mais tarde, porém, dois escravos de Simei fugiram para a casa de Aquis, filho de Maaca, rei de Gate. Quando alguém disse a Simei onde eles estavam,

[[v11-2-40]]

^<<v11-2-40,40>>^ ele selou um jumento e foi até Gate procurá-los. Ao encontrá-los, levou-os de volta a Jerusalém.

[[v11-2-41]]

^<<v11-2-41,41>>^ Salomão soube que Simei tinha saído de Jerusalém, ido a Gate e voltado.

[[v11-2-42]]

^<<v11-2-42,42>>^ O rei mandou chamá-lo e perguntou: "Não o fiz jurar pelo SENHOR e não o adverti de que não fosse a lugar algum, pois do contrário certamente morreria? E você respondeu: ‘Sua sentença é justa; farei o que ordena’.

[[v11-2-43]]

^<<v11-2-43,43>>^ Então por que não manteve o juramento ao SENHOR e não obedeceu à minha ordem?".

[[v11-2-44]]

^<<v11-2-44,44>>^ O rei também disse a Simei: "Certamente você se lembra de todas as maldades que fez a meu pai, Davi. Que o SENHOR faça esse mal recair sobre sua cabeça.

[[v11-2-45]]

^<<v11-2-45,45>>^ Mas que eu, o rei Salomão, receba as bênçãos do SENHOR e que sempre haja um descendente de Davi neste trono na presença do SENHOR".

[[v11-2-46]]

^<<v11-2-46,46>>^ Então, por ordem do rei, Benaia, filho de Joiada, levou Simei para fora e o matou. Assim, o reino de Salomão foi firmemente estabelecido.

'''

xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[&#60; Capítulo Anterior] | <<v11-2-0,Topo>> | xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[Próximo Capítulo &#62;]