include::./index.adoc[]

[[v11-13-0]]
=== 1 Reis, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v11-13-1]]

^<<v11-13-1,1>>^ Por ordem do SENHOR, um homem de Deus, vindo de Judá, foi até Betel e chegou ali quando Jeroboão se aproximava do altar para queimar incenso.

[[v11-13-2]]

^<<v11-13-2,2>>^ Então, por ordem do SENHOR, ele gritou: "Altar, altar! Assim diz o SENHOR: ‘Um menino chamado Josias nascerá na dinastia de Davi. Sobre você ele sacrificará os sacerdotes dos santuários idólatras que queimam incenso aqui, e sobre você serão queimados ossos humanos!’".

[[v11-13-3]]

^<<v11-13-3,3>>^ Naquele mesmo dia, o homem de Deus deu um sinal. Disse ele: "O SENHOR anunciou este sinal: O altar se rachará, e suas cinzas se derramarão pelo chão".

[[v11-13-4]]

^<<v11-13-4,4>>^ Quando o rei Jeroboão ouviu o homem de Deus falar contra o altar em Betel, apontou para o homem e ordenou: "Prendam-no!". No mesmo instante, porém, a mão do rei ficou paralisada nessa posição, e ele não conseguia fazê-la voltar à posição normal.

[[v11-13-5]]

^<<v11-13-5,5>>^ Ao mesmo tempo, uma grande rachadura apareceu no altar e as cinzas se derramaram, exatamente como o homem de Deus tinha dito na mensagem recebida do SENHOR.

[[v11-13-6]]

^<<v11-13-6,6>>^ O rei disse ao homem de Deus: "Por favor, peça ao SENHOR, seu Deus, que restaure a minha mão!". O homem de Deus orou ao SENHOR e a mão do rei foi restaurada, e ele pôde movimentá-la novamente.

[[v11-13-7]]

^<<v11-13-7,7>>^ Então o rei disse ao homem de Deus: "Venha ao palácio comigo e coma alguma coisa, e eu lhe darei um presente".

[[v11-13-8]]

^<<v11-13-8,8>>^ Mas o homem de Deus respondeu a Jeroboão: "Mesmo que o rei me desse metade de tudo que possui, eu não o acompanharia. Não comeria nem beberia coisa alguma neste lugar,

[[v11-13-9]]

^<<v11-13-9,9>>^ pois o SENHOR me ordenou: ‘Não coma nem beba coisa alguma enquanto estiver lá e não volte pelo mesmo caminho por onde foi’".

[[v11-13-10]]

^<<v11-13-10,10>>^ Então ele partiu de Betel e voltou para casa por outro caminho.

[[v11-13-11]]

^<<v11-13-11,11>>^ Acontece que morava em Betel um profeta idoso. Seus filhos foram até ele e lhe contaram o que o homem de Deus havia feito em Betel naquele dia. Também contaram ao pai o que o homem de Deus tinha dito ao rei.

[[v11-13-12]]

^<<v11-13-12,12>>^ O profeta idoso lhes perguntou: "Por onde ele foi?". Eles mostraram ao pai o caminho por onde o homem de Deus tinha ido.

[[v11-13-13]]

^<<v11-13-13,13>>^ "Selem o jumento", disse o profeta idoso. Eles selaram o jumento para o pai, e ele montou.

[[v11-13-14]]

^<<v11-13-14,14>>^ Foi atrás do homem de Deus e o encontrou sentado debaixo de uma grande árvore. Perguntou-lhe: "Você é o homem de Deus que veio de Judá?". "Sim, sou eu", respondeu ele.

[[v11-13-15]]

^<<v11-13-15,15>>^ Então o profeta disse ao homem de Deus: "Venha para casa comigo e coma alguma coisa".

[[v11-13-16]]

^<<v11-13-16,16>>^ "Não posso ir com você", respondeu ele. "Não tenho permissão para comer nem beber coisa alguma neste lugar,

[[v11-13-17]]

^<<v11-13-17,17>>^ pois o SENHOR me ordenou: ‘Não coma nem beba coisa alguma enquanto estiver lá e não volte pelo mesmo caminho por onde foi’."

[[v11-13-18]]

^<<v11-13-18,18>>^ O profeta idoso, porém, respondeu: "Também sou profeta como você. E um anjo me deu esta ordem da parte do SENHOR: ‘Traga-o para casa com você, para que ele coma pão e beba água’". No entanto, estava mentindo.

[[v11-13-19]]

^<<v11-13-19,19>>^ Eles voltaram juntos, e o homem de Deus comeu e bebeu na casa do profeta.

[[v11-13-20]]

^<<v11-13-20,20>>^ Então, enquanto estavam sentados à mesa, veio uma ordem do SENHOR ao profeta idoso.

[[v11-13-21]]

^<<v11-13-21,21>>^ Ele falou ao homem de Deus que tinha vindo de Judá: "Assim diz o SENHOR: ‘Você desafiou a palavra do SENHOR e desobedeceu à ordem que o SENHOR, seu Deus, lhe deu.

[[v11-13-22]]

^<<v11-13-22,22>>^ Voltou a este lugar e comeu e bebeu onde ele lhe disse que não comesse nem bebesse. Por isso seu corpo não será sepultado no túmulo de seus antepassados’".

[[v11-13-23]]

^<<v11-13-23,23>>^ Quando o homem de Deus terminou de comer e beber, o profeta idoso selou seu próprio jumento para ele,

[[v11-13-24]]

^<<v11-13-24,24>>^ e o homem de Deus partiu. Enquanto estava a caminho, apareceu um leão e o matou. Seu corpo ficou na estrada, com o jumento e o leão parados ao lado dele.

[[v11-13-25]]

^<<v11-13-25,25>>^ Algumas pessoas que passaram viram o corpo estendido ali, com o leão parado ao lado dele, e deram a notícia em Betel, onde morava o profeta idoso.

[[v11-13-26]]

^<<v11-13-26,26>>^ Quando o profeta que o trouxe de volta soube do que havia acontecido, disse: "É o homem de Deus que desafiou a palavra do SENHOR. O SENHOR cumpriu sua palavra ao fazer que o leão o atacasse e matasse".

[[v11-13-27]]

^<<v11-13-27,27>>^ Então o profeta disse a seus filhos: "Selem o jumento para mim". Eles selaram o jumento,

[[v11-13-28]]

^<<v11-13-28,28>>^ e o profeta foi e encontrou o corpo estendido na estrada. O jumento e o leão ainda estavam parados ao lado dele; o leão não havia comido o corpo nem atacado o jumento.

[[v11-13-29]]

^<<v11-13-29,29>>^ O profeta colocou o corpo do homem de Deus sobre o jumento e o levou de volta à cidade para lamentar por ele e sepultá-lo.

[[v11-13-30]]

^<<v11-13-30,30>>^ Pôs o corpo em sua própria sepultura e lamentou por ele, exclamando: "Ah, meu irmão!".

[[v11-13-31]]

^<<v11-13-31,31>>^ Depois de sepultá-lo, o profeta disse a seus filhos: "Quando eu morrer, enterrem-me no túmulo onde está sepultado o homem de Deus. Ponham meus ossos ao lado dos ossos dele,

[[v11-13-32]]

^<<v11-13-32,32>>^ pois a mensagem que o SENHOR ordenou que ele proclamasse contra o altar em Betel e contra os santuários idólatras nas cidades de Samaria certamente se cumprirá".

[[v11-13-33]]

^<<v11-13-33,33>>^ Mesmo depois disso, Jeroboão não se arrependeu de seus maus caminhos. Continuou a nomear sacerdotes dentre o povo comum; qualquer um que desejasse podia se tornar sacerdote dos santuários idólatras.

[[v11-13-34]]

^<<v11-13-34,34>>^ Com isso, por causa desse pecado, a dinastia de Jeroboão foi eliminada da face da terra.

'''

xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[&#60; Capítulo Anterior] | <<v11-13-0,Topo>> | xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[Próximo Capítulo &#62;]