include::./index.adoc[]

[[v11-16-0]]
=== 1 Reis, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v11-16-1]]

^<<v11-16-1,1>>^ Esta mensagem do SENHOR foi transmitida ao rei Baasa pelo profeta Jeú, filho de Hanani:

[[v11-16-2]]

^<<v11-16-2,2>>^ "Eu o levantei do pó a fim de torná-lo líder do meu povo, Israel, mas você seguiu o exemplo de Jeroboão. Provocou minha ira ao fazer meu povo, Israel, pecar.

[[v11-16-3]]

^<<v11-16-3,3>>^ Por isso, destruirei você e sua família, assim como destruí os descendentes de Jeroboão, filho de Nebate.

[[v11-16-4]]

^<<v11-16-4,4>>^ Os membros da família de Baasa que morrerem na cidade serão comidos pelos cães, e os que morrerem no campo serão comidos pelos abutres".

[[v11-16-5]]

^<<v11-16-5,5>>^ Os demais acontecimentos do reinado de Baasa, o que ele fez e a extensão de seu poder estão registrados no Livro da História dos Reis de Israel .

[[v11-16-6]]

^<<v11-16-6,6>>^ Quando Baasa morreu e se reuniu a seus antepassados, foi sepultado em Tirza. Seu filho Elá foi seu sucessor.

[[v11-16-7]]

^<<v11-16-7,7>>^ A mensagem do SENHOR contra Baasa e sua família veio por meio do profeta Jeú, filho de Hanani. Foi transmitida porque Baasa havia feito o que era mau aos olhos do SENHOR, como a família de Jeroboão, e também porque Baasa havia destruído a família de Jeroboão. Os pecados de Baasa provocaram a ira do SENHOR.

[[v11-16-8]]

^<<v11-16-8,8>>^ Elá, filho de Baasa, começou a reinar em Israel no vigésimo sexto ano do reinado de Asa, rei de Judá. Reinou em Tirza por dois anos.

[[v11-16-9]]

^<<v11-16-9,9>>^ Então Zinri, comandante de metade dos carros de guerra do rei, conspirou contra ele. Certo dia, em Tirza, Elá estava se embebedando na casa de Arza, supervisor do palácio.

[[v11-16-10]]

^<<v11-16-10,10>>^ Zinri entrou, feriu Elá e o matou. Isso aconteceu no vigésimo sétimo ano do reinado de Asa, rei de Judá. Zinri se tornou o sucessor de Elá.

[[v11-16-11]]

^<<v11-16-11,11>>^ Logo que Zinri subiu ao poder, matou toda a família de Baasa. Não deixou vivo nenhum filho do sexo masculino. Exterminou até mesmo parentes e amigos.

[[v11-16-12]]

^<<v11-16-12,12>>^ Desse modo, Zinri destruiu a dinastia de Baasa, como o SENHOR havia anunciado por meio do profeta Jeú.

[[v11-16-13]]

^<<v11-16-13,13>>^ Isso aconteceu por causa de todos os pecados que Baasa e seu filho Elá haviam cometido e levado Israel a cometer. Com seus ídolos inúteis, provocaram a ira do SENHOR, Deus de Israel.

[[v11-16-14]]

^<<v11-16-14,14>>^ Os demais acontecimentos do reinado de Elá e tudo que ele fez estão registrados no Livro da História dos Reis de Israel .

[[v11-16-15]]

^<<v11-16-15,15>>^ Zinri começou a reinar em Israel no vigésimo sétimo ano do reinado de Asa, rei de Judá. Reinou em Tirza por apenas sete dias. Nessa ocasião, o exército de Israel estava acampado próximo à cidade filisteia de Gibetom.

[[v11-16-16]]

^<<v11-16-16,16>>^ Quando souberam que Zinri havia traído e assassinado o rei, naquele mesmo dia proclamaram Onri, comandante do exército, o novo rei de Israel.

[[v11-16-17]]

^<<v11-16-17,17>>^ Onri levou todo o exército de Israel de Gibetom a Tirza e cercou a cidade.

[[v11-16-18]]

^<<v11-16-18,18>>^ Quando Zinri viu que a cidade havia sido conquistada, foi para a parte mais protegida do palácio real, ateou fogo ao edifício e morreu no meio das chamas.

[[v11-16-19]]

^<<v11-16-19,19>>^ Ele também havia feito o que era mau aos olhos do SENHOR. Seguiu o exemplo de Jeroboão nos pecados que tinha cometido e levado Israel a cometer.

[[v11-16-20]]

^<<v11-16-20,20>>^ Os demais acontecimentos do reinado de Zinri e sua conspiração estão registrados no Livro da História dos Reis de Israel .

[[v11-16-21]]

^<<v11-16-21,21>>^ O povo de Israel se dividiu em dois partidos. Metade queria proclamar rei Tibni, filho de Ginate, e a outra metade apoiava Onri.

[[v11-16-22]]

^<<v11-16-22,22>>^ Os partidários de Onri derrotaram os de Tibni, filho de Ginate. Tibni morreu, e Onri se tornou rei.

[[v11-16-23]]

^<<v11-16-23,23>>^ Onri começou seu reinado no trigésimo primeiro ano do reinado de Asa, rei de Judá. Ao todo, reinou por doze anos, seis deles em Tirza.

[[v11-16-24]]

^<<v11-16-24,24>>^ Então Onri comprou de Sêmer o monte de Samaria por setenta quilos de prata. Construiu ali uma cidade que chamou de Samaria, em homenagem a Sêmer, o antigo proprietário do monte.

[[v11-16-25]]

^<<v11-16-25,25>>^ Onri fez o que era mau aos olhos do SENHOR, pior que todos os reis antes dele.

[[v11-16-26]]

^<<v11-16-26,26>>^ Seguiu o exemplo de Jeroboão, filho de Nebate, em todos os pecados que tinha cometido e levado Israel a cometer. Com seus ídolos inúteis, o povo provocou a ira do SENHOR, Deus de Israel.

[[v11-16-27]]

^<<v11-16-27,27>>^ Os demais acontecimentos do reinado de Onri, o que ele fez e a extensão de seu poder estão registrados no Livro da História dos Reis de Israel .

[[v11-16-28]]

^<<v11-16-28,28>>^ Quando Onri morreu e se reuniu a seus antepassados, foi sepultado em Samaria. Seu filho Acabe foi seu sucessor.

[[v11-16-29]]

^<<v11-16-29,29>>^ Acabe, filho de Onri, começou a reinar em Israel no trigésimo oitavo ano do reinado de Asa, rei de Judá. Reinou em Samaria por 22 anos.

[[v11-16-30]]

^<<v11-16-30,30>>^ Acabe, filho de Onri, fez o que era mau aos olhos do SENHOR, pior que todos os reis antes dele.

[[v11-16-31]]

^<<v11-16-31,31>>^ E, como se não bastasse seguir o exemplo pecaminoso de Jeroboão, casou-se com Jezabel, filha de Etbaal, rei dos sidônios, e começou a se prostrar diante de Baal e adorá-lo.

[[v11-16-32]]

^<<v11-16-32,32>>^ Primeiro, Acabe construiu um templo e um altar para Baal em Samaria.

[[v11-16-33]]

^<<v11-16-33,33>>^ Depois, levantou um poste para a deusa Aserá. Fez mais coisas para provocar a ira do SENHOR, Deus de Israel, que todos os reis de Israel antes dele.

[[v11-16-34]]

^<<v11-16-34,34>>^ Durante o reinado de Acabe, Hiel, um homem de Betel, reconstruiu Jericó. Quando lançou os alicerces, morreu seu filho mais velho, Abirão. E, quando terminou a reconstrução e colocou as portas, morreu seu filho mais novo, Segube. Tudo isso aconteceu de acordo com a mensagem do SENHOR a respeito de Jericó, transmitida por meio de Josué, filho de Num.

'''

xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[&#60; Capítulo Anterior] | <<v11-16-0,Topo>> | xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[Próximo Capítulo &#62;]