include::./index.adoc[]

[[v11-20-0]]
=== 1 Reis, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v11-20-1]]

^<<v11-20-1,1>>^ Por esse tempo, Ben-Hadade, rei da Síria, mobilizou seu exército com o apoio de 32 reis aliados e seus carros de guerra e cavalos. Eles cercaram Samaria e a atacaram.

[[v11-20-2]]

^<<v11-20-2,2>>^ Ben-Hadade enviou mensageiros à cidade para dizer a Acabe, rei de Israel: "Assim diz Ben-Hadade:

[[v11-20-3]]

^<<v11-20-3,3>>^ ‘Sua prata e seu ouro são meus, bem como suas esposas e os melhores de seus filhos’".

[[v11-20-4]]

^<<v11-20-4,4>>^ "Está bem, ó meu senhor, o rei", respondeu o rei de Israel. "Tudo que tenho é seu."

[[v11-20-5]]

^<<v11-20-5,5>>^ Pouco depois, os mensageiros voltaram e disseram: "Assim diz Ben-Hadade: ‘Já exigi que entregasse sua prata, seu ouro, suas esposas e seus filhos.

[[v11-20-6]]

^<<v11-20-6,6>>^ Mas amanhã, a esta hora, enviarei meus oficiais para vasculharem seu palácio e as casas de seus oficiais e tomarem tudo que considerarem de valor’".

[[v11-20-7]]

^<<v11-20-7,7>>^ Então Acabe convocou todas as autoridades de Israel e lhes disse: "Vejam como esse homem quer nossa desgraça! Já concordei em lhe entregar minhas esposas, meus filhos, minha prata e meu ouro!".

[[v11-20-8]]

^<<v11-20-8,8>>^ "Não ceda a nenhuma outra exigência!", aconselharam as autoridades e o povo.

[[v11-20-9]]

^<<v11-20-9,9>>^ Portanto, Acabe respondeu aos mensageiros de Ben-Hadade: "Digam ao meu senhor, o rei: ‘Eu lhe darei tudo que pediu da primeira vez, mas não posso aceitar sua última exigência’". Os mensageiros voltaram a Ben-Hadade com essa resposta.

[[v11-20-10]]

^<<v11-20-10,10>>^ Então Ben-Hadade enviou a seguinte mensagem a Acabe: "Que os deuses me castiguem severamente se restar pó suficiente de Samaria para dar um punhado a cada um de meus soldados!".

[[v11-20-11]]

^<<v11-20-11,11>>^ O rei de Israel respondeu: "O guerreiro que se arma com sua espada para lutar não deve se vangloriar como o guerreiro que já venceu".

[[v11-20-12]]

^<<v11-20-12,12>>^ A resposta de Acabe chegou a Ben-Hadade e aos outros reis quando bebiam em suas tendas. "Preparem-se para atacar!", ordenou Ben-Hadade a seus oficiais. E eles se prepararam para atacar a cidade.

[[v11-20-13]]

^<<v11-20-13,13>>^ Enquanto isso, um profeta foi a Acabe, rei de Israel, e lhe disse: "Assim diz o SENHOR: ‘Está vendo esse enorme exército inimigo? Hoje eu o entregarei em suas mãos. Com isso, você saberá que eu sou o SENHOR’".

[[v11-20-14]]

^<<v11-20-14,14>>^ Acabe perguntou: "Por meio de quem ele fará isso acontecer?". O profeta respondeu: "Assim diz o SENHOR: ‘Os soldados dos comandantes das províncias o farão’". "Devemos atacar primeiro?", perguntou Acabe. "Sim", respondeu o profeta.

[[v11-20-15]]

^<<v11-20-15,15>>^ Então Acabe convocou os 232 soldados dos comandantes das províncias. Em seguida, reuniu o restante do exército de Israel, cerca de sete mil homens.

[[v11-20-16]]

^<<v11-20-16,16>>^ Por volta do meio-dia, quando Ben-Hadade e os 32 reis aliados ainda estavam em suas tendas, bebendo até ficarem bêbados,

[[v11-20-17]]

^<<v11-20-17,17>>^ o primeiro contingente, formado pelos soldados dos comandantes das províncias, saiu da cidade. Quando eles se aproximavam, os espiões de Ben-Hadade o avisaram: "Há alguns soldados vindo de Samaria".

[[v11-20-18]]

^<<v11-20-18,18>>^ Ele ordenou: "Quer tenham vindo em paz, quer para guerrear, tragam esses soldados com vida!".

[[v11-20-19]]

^<<v11-20-19,19>>^ Os soldados dos comandantes das províncias de Acabe e todo o exército haviam saído para lutar.

[[v11-20-20]]

^<<v11-20-20,20>>^ Cada soldado israelita matou seu adversário sírio e, de repente, todo o exército sírio fugiu. Os israelitas os perseguiram, mas o rei Ben-Hadade e alguns dos cavaleiros fugiram a cavalo.

[[v11-20-21]]

^<<v11-20-21,21>>^ O rei de Israel destruiu os outros cavalos e carros de guerra e massacrou os sírios.

[[v11-20-22]]

^<<v11-20-22,22>>^ Depois disso, o profeta disse ao rei Acabe: "Prepare-se para outro ataque. Comece a planejar desde já, pois o rei da Síria voltará na virada do ano".

[[v11-20-23]]

^<<v11-20-23,23>>^ Depois da derrota, os oficiais de Ben-Hadade lhe disseram: "Os deuses israelitas são deuses dos montes; por isso venceram. Mas podemos derrotá-los com facilidade nas planícies.

[[v11-20-24]]

^<<v11-20-24,24>>^ Desta vez, porém, substitua os reis por outros comandantes.

[[v11-20-25]]

^<<v11-20-25,25>>^ Reúna outro exército como o que o senhor perdeu. Dê-nos o mesmo número de cavalos e carros de guerra, e lutaremos contra os israelitas nas planícies. Certamente os derrotaremos!". O rei Ben-Hadade fez conforme aconselharam.

[[v11-20-26]]

^<<v11-20-26,26>>^ Na virada do ano, convocou o exército sírio e marchou novamente contra Israel, dessa vez em Afeque.

[[v11-20-27]]

^<<v11-20-27,27>>^ Israel reuniu seu exército, organizou linhas de abastecimento e saiu para lutar. Mas, em comparação com o enorme exército sírio que cobria todo o campo, os israelitas pareciam dois pequenos rebanhos de cabras.

[[v11-20-28]]

^<<v11-20-28,28>>^ O homem de Deus foi ao rei de Israel e lhe disse: "Assim diz o SENHOR: ‘Os sírios pensam que o SENHOR é um deus dos montes, e não das planícies. Por isso, entregarei todo o enorme exército sírio em suas mãos. Então vocês saberão que eu sou o SENHOR’".

[[v11-20-29]]

^<<v11-20-29,29>>^ Os dois exércitos acamparam um de frente para o outro durante sete dias e, no sétimo dia, a batalha começou. Os israelitas mataram cem mil soldados de infantaria dos sírios em um só dia.

[[v11-20-30]]

^<<v11-20-30,30>>^ O restante fugiu para a cidade de Afeque, mas o muro caiu sobre eles e matou mais 27 mil. Ben-Hadade fugiu para a cidade e se escondeu num quarto secreto.

[[v11-20-31]]

^<<v11-20-31,31>>^ Os oficiais de Ben-Hadade lhe disseram: "Senhor, ouvimos que os reis de Israel são misericordiosos. Vamos nos humilhar, usar panos de saco na cintura e cordas na cabeça e nos render ao rei de Israel. Talvez ele deixe o senhor viver".

[[v11-20-32]]

^<<v11-20-32,32>>^ Então vestiram panos de saco e cordas, foram ao rei de Israel e suplicaram: "Seu servo Ben-Hadade diz: ‘Peço que me deixe viver!’". O rei de Israel respondeu: "Ele ainda está vivo? Ele é meu irmão!".

[[v11-20-33]]

^<<v11-20-33,33>>^ Os homens interpretaram isso como um bom sinal e, aproveitando essas palavras, responderam: "Sim, seu irmão Ben-Hadade!". "Vão buscá-lo", disse o rei de Israel. E, quando Ben-Hadade chegou, Acabe o convidou para subir em sua carruagem.

[[v11-20-34]]

^<<v11-20-34,34>>^ Ben-Hadade lhe disse: "Devolverei as cidades que meu pai tomou de seu pai, e você poderá estabelecer centros de comércio em Damasco, como meu pai fez em Samaria". Acabe disse: "Sob essas condições, eu o libertarei". Então os dois fizeram um acordo, e Ben-Hadade foi liberto.

[[v11-20-35]]

^<<v11-20-35,35>>^ Enquanto isso, o SENHOR instruiu um dos membros de um grupo de profetas a dizer a outro: "Dê um soco em mim!", mas o homem se recusou a fazê-lo.

[[v11-20-36]]

^<<v11-20-36,36>>^ Então o profeta lhe disse: "Como você não obedeceu à voz do SENHOR, um leão o matará assim que você sair daqui". E, quando ele partiu, um leão o atacou e o matou.

[[v11-20-37]]

^<<v11-20-37,37>>^ Em seguida, o profeta se dirigiu a outro homem e disse: "Dê um soco em mim!". O homem deu um soco no profeta e o feriu.

[[v11-20-38]]

^<<v11-20-38,38>>^ O profeta colocou uma faixa de pano sobre os olhos para se disfarçar e esperou pelo rei junto à estrada.

[[v11-20-39]]

^<<v11-20-39,39>>^ Quando o rei ia passando, o profeta gritou: "Eu, seu servo, estava no meio da batalha acirrada quando, de repente, alguém me trouxe um prisioneiro e disse: ‘Vigie este homem. Se ele escapar, você morrerá ou pagará uma multa de 35 quilos de prata!’.

[[v11-20-40]]

^<<v11-20-40,40>>^ Contudo, enquanto eu estava ocupado fazendo outra coisa, o prisioneiro desapareceu". "A culpa é sua", respondeu o rei. "Você mesmo pronunciou sua condenação."

[[v11-20-41]]

^<<v11-20-41,41>>^ Então, sem demora, o profeta tirou a faixa dos olhos, e o rei de Israel reconheceu que era um dos profetas.

[[v11-20-42]]

^<<v11-20-42,42>>^ O profeta lhe disse: "Assim diz o SENHOR: ‘Uma vez que você poupou o homem que eu havia ordenado que fosse destruído, você deve morrer em lugar dele, e seu povo, em lugar do povo dele’".

[[v11-20-43]]

^<<v11-20-43,43>>^ O rei de Israel foi para casa, em Samaria, indignado e aborrecido.

'''

xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[Próximo Capítulo &#62;]