include::./index.adoc[]

[[v11-8-0]]
=== 1 Reis, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v11-8-1]]

^<<v11-8-1,1>>^ Em seguida, Salomão mandou chamar a Jerusalém todas as autoridades de Israel e todos os líderes das tribos, os chefes das famílias israelitas. Eles levariam a arca da aliança do SENHOR do lugar onde estava, na Cidade de Davi, também conhecida como Sião, para o templo.

[[v11-8-2]]

^<<v11-8-2,2>>^ Todos os homens de Israel se reuniram diante do rei Salomão durante a Festa das Cabanas, celebrada no mês de etanim, o sétimo mês.

[[v11-8-3]]

^<<v11-8-3,3>>^ Quando todos os líderes de Israel chegaram, os sacerdotes ergueram a arca.

[[v11-8-4]]

^<<v11-8-4,4>>^ Os sacerdotes e os levitas levaram a arca do SENHOR, junto com a tenda do encontro e todos os seus utensílios sagrados.

[[v11-8-5]]

^<<v11-8-5,5>>^ Ali, diante da arca, o rei Salomão e toda a comunidade de Israel ofereceram tantos sacrifícios de ovelhas e bois que não puderam ser contados.

[[v11-8-6]]

^<<v11-8-6,6>>^ Então os sacerdotes levaram a arca da aliança do SENHOR para o santuário interno do templo, o lugar santíssimo, e a colocaram sob as asas dos querubins.

[[v11-8-7]]

^<<v11-8-7,7>>^ Os querubins tinham as asas abertas sobre a arca, e elas cobriam a arca e as varas usadas para transportá-la.

[[v11-8-8]]

^<<v11-8-8,8>>^ Essas varas eram tão compridas que suas pontas podiam ser vistas do lugar santo, diante do lugar santíssimo, mas não de fora; e estão ali até hoje.

[[v11-8-9]]

^<<v11-8-9,9>>^ Na arca havia só as duas tábuas de pedra que Moisés tinha colocado dentro dela no monte Sinai, onde o SENHOR fez uma aliança com os israelitas depois que eles saíram da terra do Egito.

[[v11-8-10]]

^<<v11-8-10,10>>^ Quando os sacerdotes saíram do lugar santo, uma densa nuvem encheu o templo do SENHOR.

[[v11-8-11]]

^<<v11-8-11,11>>^ Com isso, os sacerdotes não puderam dar continuidade a seus serviços, pois a presença gloriosa do SENHOR encheu o templo do SENHOR.

[[v11-8-12]]

^<<v11-8-12,12>>^ Então Salomão orou: "Ó SENHOR, tu disseste que habitarias numa densa nuvem.

[[v11-8-13]]

^<<v11-8-13,13>>^ Agora, construí para ti um templo majestoso, um lugar para habitares para sempre!".

[[v11-8-14]]

^<<v11-8-14,14>>^ Então o rei se voltou para toda a comunidade de Israel que estava em pé diante dele e abençoou o povo.

[[v11-8-15]]

^<<v11-8-15,15>>^ Em seguida, orou: "Louvado seja o SENHOR, o Deus de Israel, que cumpriu o que prometeu a meu pai, Davi, pois lhe disse:

[[v11-8-16]]

^<<v11-8-16,16>>^ ‘Desde o dia em que tirei Israel, meu povo, do Egito, não escolhi nenhuma cidade das tribos de Israel como lugar onde deveria ser construído um templo em honra ao meu nome. Contudo, escolhi Davi para reinar sobre meu povo, Israel’".

[[v11-8-17]]

^<<v11-8-17,17>>^ Salomão disse: "Meu pai, Davi, queria construir este templo em honra ao nome do SENHOR, o Deus de Israel.

[[v11-8-18]]

^<<v11-8-18,18>>^ Mas o SENHOR lhe disse: ‘Sua intenção de construir um templo em honra ao meu nome é boa,

[[v11-8-19]]

^<<v11-8-19,19>>^ mas essa tarefa não caberá a você. Um de seus filhos construirá o templo em honra ao meu nome’.

[[v11-8-20]]

^<<v11-8-20,20>>^ "O SENHOR cumpriu sua promessa, pois eu sou o sucessor de meu pai, Davi, e agora ocupo o trono de Israel, como o SENHOR havia prometido. Construí este templo em honra ao nome do SENHOR, o Deus de Israel,

[[v11-8-21]]

^<<v11-8-21,21>>^ e preparei nele um lugar para a arca que contém a aliança que o SENHOR fez com nossos antepassados quando os tirou do Egito".

[[v11-8-22]]

^<<v11-8-22,22>>^ Então Salomão se pôs diante do altar do SENHOR, na presença de toda a comunidade de Israel. Levantou as mãos para o céu

[[v11-8-23]]

^<<v11-8-23,23>>^ e orou: "Ó SENHOR, o Deus de Israel, não há Deus como tu em cima, nos céus, nem embaixo, na terra. Tu guardas a tua aliança e mostras amor leal àqueles que andam diante de ti de todo o coração.

[[v11-8-24]]

^<<v11-8-24,24>>^ Cumpriste tua promessa a teu servo Davi, meu pai. Fizeste essa promessa com a tua própria boca, e hoje a cumpriste com as tuas próprias mãos.

[[v11-8-25]]

^<<v11-8-25,25>>^ "Agora, ó SENHOR, o Deus de Israel, cumpre a outra promessa que fizeste a teu servo Davi, meu pai, quando lhe disseste: ‘Se seus descendentes viverem como devem e me seguirem fielmente como você fez, sempre haverá um deles no trono de Israel’.

[[v11-8-26]]

^<<v11-8-26,26>>^ Agora, ó Deus de Israel, cumpre a promessa que fizeste a teu servo Davi, meu pai.

[[v11-8-27]]

^<<v11-8-27,27>>^ "Contudo, será possível que Deus habite na terra? Nem mesmo os mais altos céus podem contê-lo, muito menos este templo que construí!

[[v11-8-28]]

^<<v11-8-28,28>>^ Ainda assim, ouve minha oração e minha súplica, ó SENHOR, meu Deus. Ouve o clamor e a oração que teu servo te faz hoje.

[[v11-8-29]]

^<<v11-8-29,29>>^ Guarda noite e dia este templo, o lugar do qual disseste: ‘Meu nome estará ali’. Ouve sempre as orações que teu servo fizer voltado para este lugar.

[[v11-8-30]]

^<<v11-8-30,30>>^ Ouve as súplicas de teu servo e de Israel, teu povo, quando orarmos voltados para este lugar. Sim, ouve-nos dos céus onde habitas e, quando ouvires, perdoa-nos.

[[v11-8-31]]

^<<v11-8-31,31>>^ "Se alguém pecar contra outra pessoa e se for exigido que faça um juramento de inocência diante do teu altar neste templo,

[[v11-8-32]]

^<<v11-8-32,32>>^ ouve dos céus e julga entre teus servos, entre o acusador e o acusado. Castiga o culpado e declara justo o inocente, cada um conforme merece.

[[v11-8-33]]

^<<v11-8-33,33>>^ "Se o teu povo, Israel, for derrotado por seus inimigos porque pecou contra ti, e se voltar para ti, invocar o teu nome e orar a ti neste templo,

[[v11-8-34]]

^<<v11-8-34,34>>^ ouve dos céus, perdoa o pecado de teu povo, Israel, e traze-o de volta a esta terra que deste a seus antepassados.

[[v11-8-35]]

^<<v11-8-35,35>>^ "Se o céu se fechar e não houver chuva porque o povo pecou contra ti, e se eles orarem voltados para este templo, invocarem o teu nome e se afastarem de seus pecados porque tu os castigaste,

[[v11-8-36]]

^<<v11-8-36,36>>^ ouve dos céus e perdoa os pecados de teus servos, o teu povo, Israel. Ensina-os a seguir o caminho certo e envia chuva à terra que deste por herança a teu povo.

[[v11-8-37]]

^<<v11-8-37,37>>^ "Se houver fome na terra, ou peste, ou praga nas lavouras, ou se elas forem atacadas por gafanhotos ou lagartas, ou se os inimigos do teu povo invadirem a terra e sitiarem suas cidades, seja qual for o desastre ou epidemia que ocorrer,

[[v11-8-38]]

^<<v11-8-38,38>>^ e se alguém do teu povo, ou toda a nação de Israel, orar a respeito de suas aflições com as mãos levantadas para este templo,

[[v11-8-39]]

^<<v11-8-39,39>>^ ouve dos céus onde habitas e perdoa. Trata o teu povo como ele merece, pois somente tu conheces o coração de cada um.

[[v11-8-40]]

^<<v11-8-40,40>>^ Assim eles te temerão enquanto viverem na terra que deste a nossos antepassados.

[[v11-8-41]]

^<<v11-8-41,41>>^ "No futuro, estrangeiros que não pertencem a teu povo, Israel, ouvirão falar de ti. Virão de terras distantes por causa do teu nome,

[[v11-8-42]]

^<<v11-8-42,42>>^ porque ouvirão falar do teu grande nome, da tua mão forte e do teu braço poderoso. E, quando orarem voltados para este templo,

[[v11-8-43]]

^<<v11-8-43,43>>^ ouve dos céus onde habitas e concede o que pedem. Assim, todos os povos da terra conhecerão teu nome e te temerão, como faz teu povo, Israel. Também saberão que neste templo que construí teu nome é honrado.

[[v11-8-44]]

^<<v11-8-44,44>>^ "Se o teu povo sair para onde o enviares a fim de lutar contra seus inimigos, e se orarem ao SENHOR voltados para esta cidade que escolheste e para este templo que construí em honra ao teu nome,

[[v11-8-45]]

^<<v11-8-45,45>>^ ouve dos céus suas orações e defende sua causa.

[[v11-8-46]]

^<<v11-8-46,46>>^ "Quando pecarem contra ti, pois não há quem não peque, tua ira cairá sobre eles e tu permitirás que seus inimigos os conquistem e os levem como escravos para outras terras, próximas ou distantes.

[[v11-8-47]]

^<<v11-8-47,47>>^ Se caírem em si nessa terra de exílio e se arrependerem, suplicando-te: ‘Pecamos, praticamos o mal e agimos perversamente’,

[[v11-8-48]]

^<<v11-8-48,48>>^ e se voltarem para ti de todo o coração e de toda a alma na terra de seus inimigos e orarem voltados para a terra que deste a seus antepassados, para esta cidade que escolheste e para este templo que construí em honra ao teu nome,

[[v11-8-49]]

^<<v11-8-49,49>>^ ouve dos céus onde habitas suas orações e súplicas e defende sua causa.

[[v11-8-50]]

^<<v11-8-50,50>>^ Perdoa teu povo que pecou contra ti. Perdoa todas as ofensas que cometeram contra ti. Faze que seus conquistadores os tratem com misericórdia,

[[v11-8-51]]

^<<v11-8-51,51>>^ pois são o teu povo, a tua propriedade especial, que libertaste do Egito, uma fornalha de fundir ferro.

[[v11-8-52]]

^<<v11-8-52,52>>^ "Olha atentamente para as súplicas do teu servo e para as súplicas do teu povo, Israel. Ouve e responde sempre que clamarmos a ti.

[[v11-8-53]]

^<<v11-8-53,53>>^ Pois, quando tiraste nossos antepassados do Egito, ó Soberano SENHOR, disseste a teu servo Moisés que separarias Israel de todas as nações da terra para ser tua propriedade especial".

[[v11-8-54]]

^<<v11-8-54,54>>^ Quando Salomão terminou de fazer essas orações e súplicas ao SENHOR, levantou-se de diante do altar do SENHOR, onde havia se ajoelhado com as mãos estendidas para o céu.

[[v11-8-55]]

^<<v11-8-55,55>>^ Ficou em pé e, em alta voz, abençoou toda a comunidade de Israel:

[[v11-8-56]]

^<<v11-8-56,56>>^ "Louvado seja o SENHOR, que deu descanso ao seu povo, Israel, como prometeu. Nenhuma só palavra falhou das maravilhosas promessas que ele fez por meio de seu servo Moisés.

[[v11-8-57]]

^<<v11-8-57,57>>^ Que o SENHOR, nosso Deus, seja conosco assim como foi com nossos antepassados; que ele jamais nos deixe nem nos abandone.

[[v11-8-58]]

^<<v11-8-58,58>>^ Que ele nos dê a disposição de fazer sua vontade e obedecer a todos os seus mandamentos, decretos e estatutos que ele deu a nossos antepassados.

[[v11-8-59]]

^<<v11-8-59,59>>^ E que as palavras dessa minha oração na presença do SENHOR estejam sempre diante dele, dia e noite, para que o SENHOR, nosso Deus, defenda a causa de seu servo e de seu povo, Israel, conforme as necessidades de cada dia.

[[v11-8-60]]

^<<v11-8-60,60>>^ Então os povos de toda a terra saberão que somente o SENHOR é Deus, e que não há nenhum outro.

[[v11-8-61]]

^<<v11-8-61,61>>^ Quanto a vocês, sejam inteiramente fiéis ao SENHOR, nosso Deus, e obedeçam sempre a seus decretos e mandamentos, como fazem hoje".

[[v11-8-62]]

^<<v11-8-62,62>>^ Então o rei e todo o Israel ofereceram sacrifícios ao SENHOR.

[[v11-8-63]]

^<<v11-8-63,63>>^ Salomão apresentou ao SENHOR uma oferta de paz de 22 mil bois e 120 mil ovelhas. Assim, o rei e todo o povo de Israel fizeram a dedicação do templo do SENHOR.

[[v11-8-64]]

^<<v11-8-64,64>>^ Naquele mesmo dia, o rei consagrou a parte central do pátio em frente ao templo do SENHOR. Ali apresentou holocaustos, ofertas de cereal e a gordura das ofertas de paz, pois o altar de bronze, na presença do SENHOR, era pequeno demais para tantos holocaustos, ofertas de cereal e gordura das ofertas de paz.

[[v11-8-65]]

^<<v11-8-65,65>>^ Então Salomão e todo o Israel celebraram a Festa das Cabanas na presença do SENHOR, nosso Deus. Uma grande multidão havia se reunido, de lugares distantes como Lebo-Hamate, ao norte, e o ribeiro do Egito, ao sul. A celebração durou, no total, catorze dias: sete dias para a dedicação do altar e sete dias para a Festa das Cabanas.

[[v11-8-66]]

^<<v11-8-66,66>>^ Terminada a festa, Salomão mandou o povo para casa. Eles abençoaram o rei e foram embora alegres e exultantes, pois o SENHOR tinha mostrado sua bondade a seu servo Davi e a seu povo, Israel.

'''

xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[&#60; Capítulo Anterior] | <<v11-8-0,Topo>> | xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[Próximo Capítulo &#62;]