include::./index.adoc[]

[[v11-17-0]]
=== 1 Reis, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v11-17-1]]

^<<v11-17-1,1>>^ Elias, que era de Tisbe, em Gileade, disse ao rei Acabe: "Tão certo como vive o SENHOR, o Deus de Israel, a quem sirvo, não haverá orvalho nem chuva durante os próximos anos, até que eu ordene!".

[[v11-17-2]]

^<<v11-17-2,2>>^ Então o SENHOR disse a Elias:

[[v11-17-3]]

^<<v11-17-3,3>>^ "Vá para o leste e esconda-se junto ao riacho de Querite, que fica a leste do rio Jordão.

[[v11-17-4]]

^<<v11-17-4,4>>^ Beba água do riacho e coma o que os corvos lhe trouxerem, pois eu dei ordem para levarem alimento até você".

[[v11-17-5]]

^<<v11-17-5,5>>^ Elias fez o que o SENHOR ordenou e acampou junto ao riacho de Querite, a leste do Jordão.

[[v11-17-6]]

^<<v11-17-6,6>>^ Os corvos lhe traziam pão e carne de manhã e à tarde, e ele bebia água do riacho.

[[v11-17-7]]

^<<v11-17-7,7>>^ Depois de algum tempo, porém, o riacho secou, pois não caía chuva em parte alguma da terra.

[[v11-17-8]]

^<<v11-17-8,8>>^ Então o SENHOR disse a Elias:

[[v11-17-9]]

^<<v11-17-9,9>>^ "Vá morar em Sarepta, perto da cidade de Sidom. Dei ordem a uma viúva que mora ali para lhe dar alimento".

[[v11-17-10]]

^<<v11-17-10,10>>^ Elias foi a Sarepta. Quando chegou ao portão da cidade, viu uma viúva apanhando gravetos e lhe perguntou: "Pode me dar um pouco de água para beber, por favor?".

[[v11-17-11]]

^<<v11-17-11,11>>^ Enquanto ela ia buscar a água, ele disse: "Traga também um pedaço de pão".

[[v11-17-12]]

^<<v11-17-12,12>>^ Mas ela respondeu: "Tão certo como vive o SENHOR, seu Deus, não tenho um pedaço sequer de pão em casa. Tenho apenas um punhado de farinha que restou numa vasilha e um pouco de azeite no fundo do jarro. Estava apanhando alguns gravetos para preparar esta última refeição, e depois meu filho e eu morreremos".

[[v11-17-13]]

^<<v11-17-13,13>>^ Elias, porém, disse: "Não tenha medo! Faça o que acabou de dizer, mas primeiro faça um pouco de pão para mim. Depois, use o resto para preparar uma refeição para você e seu filho.

[[v11-17-14]]

^<<v11-17-14,14>>^ Pois assim diz o SENHOR, Deus de Israel: ‘Sempre haverá farinha na vasilha e azeite no jarro, até o dia em que o SENHOR enviar chuva’".

[[v11-17-15]]

^<<v11-17-15,15>>^ Ela fez conforme Elias disse. Assim, Elias, a mulher e a família dela tiveram alimento para muitos dias.

[[v11-17-16]]

^<<v11-17-16,16>>^ Sempre havia farinha na vasilha e azeite no jarro, exatamente como o SENHOR tinha prometido por meio de Elias.

[[v11-17-17]]

^<<v11-17-17,17>>^ Algum tempo depois, o filho da mulher ficou doente. Foi piorando e, por fim, morreu.

[[v11-17-18]]

^<<v11-17-18,18>>^ Disse ela a Elias: "Homem de Deus, o que você me fez? Veio para lembrar-me de meus pecados e matar meu filho?".

[[v11-17-19]]

^<<v11-17-19,19>>^ Elias, porém, respondeu: "Dê-me seu filho". Tomou o corpo do menino dos braços dela, carregou-o para o andar de cima, onde estava hospedado, e o pôs na cama.

[[v11-17-20]]

^<<v11-17-20,20>>^ Então Elias clamou ao SENHOR: "Ó SENHOR, meu Deus, por que trouxeste desgraça a esta viúva que me recebeu em seu lar e fizeste o filho dela morrer?".

[[v11-17-21]]

^<<v11-17-21,21>>^ Em seguida, Elias se deitou sobre o menino três vezes e clamou ao SENHOR: "Ó SENHOR, meu Deus, por favor, permite que a vida volte a este menino!".

[[v11-17-22]]

^<<v11-17-22,22>>^ O SENHOR ouviu a oração de Elias, e o menino voltou a viver.

[[v11-17-23]]

^<<v11-17-23,23>>^ Elias o levou para baixo e o entregou à mãe. "Veja, seu filho está vivo", disse ele.

[[v11-17-24]]

^<<v11-17-24,24>>^ Então a mulher disse a Elias: "Agora tenho certeza de que você é um homem de Deus, e de que o SENHOR verdadeiramente fala por seu intermédio!".

'''

xref:011-1-reis/011-1-reis-016.adoc#v11-16-0[&#60; Capítulo Anterior] | <<v11-17-0,Topo>> | xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[Próximo Capítulo &#62;]