include::./index.adoc[]

[[v11-12-0]]
=== 1 Reis, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v11-12-1]]

^<<v11-12-1,1>>^ Roboão foi a Siquém, onde todo o Israel havia se reunido para proclamá-lo rei.

[[v11-12-2]]

^<<v11-12-2,2>>^ Quando Jeroboão, filho de Nebate, soube disso, voltou do Egito, para onde havia fugido do rei Salomão.

[[v11-12-3]]

^<<v11-12-3,3>>^ Os líderes de Israel convocaram Jeroboão, e ele e toda a comunidade de Israel foram falar com Roboão.

[[v11-12-4]]

^<<v11-12-4,4>>^ "Seu pai foi muito duro conosco", disseram. "Alivie a carga pesada de trabalho e de impostos altos que seu pai nos obrigou a carregar. Então seremos seus súditos leais."

[[v11-12-5]]

^<<v11-12-5,5>>^ Roboão respondeu: "Deem-me três dias para pensar. Depois, voltem para saber minha resposta". E o povo foi embora.

[[v11-12-6]]

^<<v11-12-6,6>>^ O rei Roboão discutiu o assunto com os homens mais velhos que haviam sido conselheiros de seu pai, Salomão. "O que vocês aconselham?", perguntou ele. "Como devo responder a este povo?"

[[v11-12-7]]

^<<v11-12-7,7>>^ Eles disseram: "Se o senhor estiver disposto a servir este povo hoje e lhe der uma resposta favorável, eles serão seus súditos leais para sempre".

[[v11-12-8]]

^<<v11-12-8,8>>^ Mas Roboão rejeitou o conselho dos homens mais velhos e pediu a opinião dos jovens que haviam crescido com ele e agora o acompanhavam.

[[v11-12-9]]

^<<v11-12-9,9>>^ "O que vocês aconselham?", perguntou ele. "Como devo responder a este povo que deseja que eu alivie as cargas impostas por meu pai?"

[[v11-12-10]]

^<<v11-12-10,10>>^ Os jovens responderam: "Você deve dizer o seguinte a essa gente que diz que seu pai foi muito duro com eles e que pede alívio: ‘Meu dedo mínimo é mais grosso que a cintura de meu pai!

[[v11-12-11]]

^<<v11-12-11,11>>^ Sim, meu pai lhes impôs cargas pesadas, mas eu as tornarei ainda mais pesadas! Meu pai os castigou com chicotes comuns, mas eu os castigarei com chicotes de pontas de metal!’".

[[v11-12-12]]

^<<v11-12-12,12>>^ Três dias depois, Jeroboão e todo o povo voltaram para saber a decisão do rei, como ele havia ordenado.

[[v11-12-13]]

^<<v11-12-13,13>>^ Roboão lhes respondeu com aspereza, pois rejeitou o conselho dos homens mais velhos

[[v11-12-14]]

^<<v11-12-14,14>>^ e seguiu o conselho dos mais jovens. Disse ao povo: "Meu pai lhes impôs cargas pesadas, mas eu as tornarei ainda mais pesadas! Meu pai os castigou com chicotes comuns, mas eu os castigarei com chicotes de pontas de metal!".

[[v11-12-15]]

^<<v11-12-15,15>>^ Assim, o rei não atendeu o povo. Essa mudança nos acontecimentos foi da vontade do SENHOR, pois cumpriu a mensagem do SENHOR a Jeroboão, filho de Nebate, por meio do profeta Aías, de Siló.

[[v11-12-16]]

^<<v11-12-16,16>>^ Quando todo o Israel viu que o rei não iria atender a seu pedido, respondeu: "Abaixo a dinastia de Davi! O filho de Jessé nada tem a nos oferecer! Volte para casa, Israel! E você, Davi, cuide de sua própria casa!". Então o povo de Israel voltou para casa.

[[v11-12-17]]

^<<v11-12-17,17>>^ Roboão, porém, continuou a governar sobre os israelitas que moravam nas cidades de Judá.

[[v11-12-18]]

^<<v11-12-18,18>>^ O rei Roboão enviou Adonirão, encarregado dos trabalhos forçados, para restaurar a ordem, mas o povo de Israel o apedrejou até a morte. Quando essa notícia chegou ao rei Roboão, ele subiu rapidamente em sua carruagem e fugiu para Jerusalém.

[[v11-12-19]]

^<<v11-12-19,19>>^ E até hoje as tribos do norte de Israel se recusam a ser governadas por um descendente de Davi.

[[v11-12-20]]

^<<v11-12-20,20>>^ Quando o povo de Israel soube que Jeroboão tinha voltado do Egito, convocou uma assembleia e o proclamou rei sobre todo o Israel. Apenas a tribo de Judá permaneceu leal à família de Davi.

[[v11-12-21]]

^<<v11-12-21,21>>^ Quando Roboão chegou a Jerusalém, mobilizou os homens das tribos de Judá e Benjamim, 180 mil dos melhores soldados, para guerrearem contra Israel e recuperarem o reino.

[[v11-12-22]]

^<<v11-12-22,22>>^ Deus, porém, falou a Semaías, homem de Deus:

[[v11-12-23]]

^<<v11-12-23,23>>^ "Diga a Roboão, filho de Salomão, rei de Judá, e a todo o povo de Judá e Benjamim, e ao restante do povo:

[[v11-12-24]]

^<<v11-12-24,24>>^ ‘Assim diz o SENHOR: Não lutem contra seus compatriotas, os israelitas. Voltem para casa, pois eu mesmo fiz isso acontecer!’". Eles obedeceram à palavra do SENHOR e voltaram para casa, conforme o SENHOR havia ordenado.

[[v11-12-25]]

^<<v11-12-25,25>>^ Então Jeroboão fortificou a cidade de Siquém, na região montanhosa de Efraim, e se estabeleceu ali. Mais tarde, fortificou Peniel.

[[v11-12-26]]

^<<v11-12-26,26>>^ Jeroboão pensou: "Se eu não tiver cuidado, o reino voltará à dinastia de Davi.

[[v11-12-27]]

^<<v11-12-27,27>>^ Quando o povo for a Jerusalém para oferecer sacrifícios no templo do SENHOR, voltará a ser leal a Roboão, rei de Judá. Eles me matarão e o proclamarão rei deles".

[[v11-12-28]]

^<<v11-12-28,28>>^ Então, seguindo a recomendação de seus conselheiros, o rei fez dois bezerros de ouro. Disse ao povo: "É complicado demais ir a Jerusalém para adorar. Veja, Israel, estes são os deuses que tiraram vocês do Egito!".

[[v11-12-29]]

^<<v11-12-29,29>>^ Colocou um dos bezerros em Betel e o outro em Dã, nos dois extremos de seu reino.

[[v11-12-30]]

^<<v11-12-30,30>>^ Isso se tornou um grande pecado, pois o povo viajava até Dã, ao norte, para adorar o ídolo que ficava ali.

[[v11-12-31]]

^<<v11-12-31,31>>^ Jeroboão também construiu santuários idólatras e designou para serem sacerdotes homens do povo, que não eram da tribo sacerdotal de Levi.

[[v11-12-32]]

^<<v11-12-32,32>>^ Instituiu uma festa religiosa em Betel, no décimo quinto dia do oitavo mês, uma imitação da festa celebrada todos os anos em Judá. Ali em Betel, Jeroboão ofereceu sacrifícios aos bezerros que havia feito e designou sacerdotes para os santuários idólatras que havia construído.

[[v11-12-33]]

^<<v11-12-33,33>>^ No décimo quinto dia do oitavo mês, data que ele mesmo tinha definido, ofereceu sacrifícios no altar em Betel. Instituiu, desse modo, uma festa religiosa para Israel e subiu ao altar para queimar incenso.

'''

xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[&#60; Capítulo Anterior] | <<v11-12-0,Topo>> | xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[Próximo Capítulo &#62;]