include::./index.adoc[]

[[v11-1-0]]
=== 1 Reis, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v11-1-1]]

^<<v11-1-1,1>>^ O rei Davi já estava muito idoso e, por mais cobertores que pusessem sobre ele, não se aquecia.

[[v11-1-2]]

^<<v11-1-2,2>>^ Então seus conselheiros lhe disseram: "Vamos procurar uma jovem virgem para servi-lo e cuidar do senhor, o rei. Ela se deitará em seus braços e o manterá aquecido".

[[v11-1-3]]

^<<v11-1-3,3>>^ Então procuraram em toda a terra de Israel uma jovem bonita e encontraram Abisague, de Suném, e a levaram ao rei.

[[v11-1-4]]

^<<v11-1-4,4>>^ A jovem, muito bela, passou a cuidar do rei e a servi-lo. O rei, porém, não teve relações sexuais com ela.

[[v11-1-5]]

^<<v11-1-5,5>>^ Por essa época, Adonias, filho de Davi e Hagite, começou a se gabar: "Eu assumirei o trono". Providenciou carruagens e cavaleiros, e também cinquenta homens que serviam como sua guarda de honra.

[[v11-1-6]]

^<<v11-1-6,6>>^ Seu pai nunca o havia disciplinado, nem sequer lhe perguntava: "Por que está fazendo isso?". Adonias havia nascido depois de Absalão e também era muito bonito.

[[v11-1-7]]

^<<v11-1-7,7>>^ Adonias buscou conselho com Joabe, filho de Zeruia, e com o sacerdote Abiatar, e eles o apoiaram em seu plano.

[[v11-1-8]]

^<<v11-1-8,8>>^ Mas o sacerdote Zadoque, Benaia, filho de Joiada, o profeta Natã, Simei, Reí e a guarda pessoal de Davi se recusaram a apoiar Adonias.

[[v11-1-9]]

^<<v11-1-9,9>>^ Adonias foi à pedra de Zoelete, perto de En-Rogel, onde ofereceu sacrifícios de ovelhas, bois e novilhos gordos. Convidou todos os seus irmãos, os outros filhos do rei Davi, e todos os homens de Judá, oficiais do rei.

[[v11-1-10]]

^<<v11-1-10,10>>^ Mas não convidou o profeta Natã, nem Benaia, nem a guarda pessoal do rei, nem seu irmão Salomão.

[[v11-1-11]]

^<<v11-1-11,11>>^ Então Natã foi falar com Bate-Seba, mãe de Salomão, e lhe perguntou: "Você está sabendo que Adonias, filho de Hagite, se proclamou rei, e nosso senhor Davi nem sabe?

[[v11-1-12]]

^<<v11-1-12,12>>^ Se deseja salvar a sua vida e a de seu filho Salomão, siga meu conselho.

[[v11-1-13]]

^<<v11-1-13,13>>^ Vá depressa ao rei Davi e diga-lhe: ‘Meu senhor, o rei, não jurou a mim que meu filho Salomão certamente seria o próximo rei e se sentaria em seu trono? Então por que Adonias se proclamou rei?’.

[[v11-1-14]]

^<<v11-1-14,14>>^ E, enquanto você ainda estiver falando com ele, eu virei e confirmarei tudo que disse".

[[v11-1-15]]

^<<v11-1-15,15>>^ O rei Davi, já bastante idoso, estava em seu quarto, onde Abisague cuidava dele. Bate-Seba foi até lá

[[v11-1-16]]

^<<v11-1-16,16>>^ e curvou-se diante do rei. "O que você quer?", perguntou ele.

[[v11-1-17]]

^<<v11-1-17,17>>^ Ela respondeu: "Meu senhor jurou diante do SENHOR, seu Deus, que Salomão, o filho de sua serva, certamente seria o próximo rei e se sentaria em seu trono.

[[v11-1-18]]

^<<v11-1-18,18>>^ Mas, agora, Adonias se proclamou rei, e meu senhor, o rei, nem sabe.

[[v11-1-19]]

^<<v11-1-19,19>>^ Ele ofereceu muitos sacrifícios de bois, novilhos gordos e ovelhas, e convidou todos os filhos do rei para a celebração. Também convidou o sacerdote Abiatar e Joabe, o comandante do exército. Mas não convidou seu servo Salomão.

[[v11-1-20]]

^<<v11-1-20,20>>^ Agora, ó meu senhor, o rei, todo o Israel espera que o senhor anuncie quem o sucederá no trono.

[[v11-1-21]]

^<<v11-1-21,21>>^ Se o senhor não tomar uma providência, meu filho Salomão e eu seremos tratados como criminosos quando meu senhor, o rei, morrer".

[[v11-1-22]]

^<<v11-1-22,22>>^ Enquanto ela ainda falava com o rei, chegou o profeta Natã.

[[v11-1-23]]

^<<v11-1-23,23>>^ Os servos do rei lhe disseram: "O profeta Natã deseja vê-lo". Natã entrou, curvou-se com o rosto no chão diante do rei

[[v11-1-24]]

^<<v11-1-24,24>>^ e perguntou: "Meu senhor, o rei, decidiu que Adonias será o próximo rei e se sentará em seu trono?

[[v11-1-25]]

^<<v11-1-25,25>>^ Hoje ele ofereceu muitos sacrifícios de bois, novilhos gordos e ovelhas, e convidou todos os filhos do rei para a celebração. Também convidou os comandantes do exército e o sacerdote Abiatar. Estão comendo e bebendo com ele e gritando: ‘Viva o rei Adonias!’.

[[v11-1-26]]

^<<v11-1-26,26>>^ Mas ele não convidou a mim, seu servo, nem ao sacerdote Zadoque, nem a Benaia, filho de Joiada, nem a seu servo Salomão.

[[v11-1-27]]

^<<v11-1-27,27>>^ Meu senhor, o rei, fez isso sem informar nenhum de seus conselheiros quem será o próximo rei?".

[[v11-1-28]]

^<<v11-1-28,28>>^ O rei Davi respondeu: "Chamem Bate-Seba!". Então ela voltou e ficou em pé diante dele.

[[v11-1-29]]

^<<v11-1-29,29>>^ O rei repetiu seu juramento: "Tão certo como vive o SENHOR, que me livrou de todos os perigos,

[[v11-1-30]]

^<<v11-1-30,30>>^ seu filho Salomão será o próximo rei e se sentará em meu trono hoje mesmo, como jurei a você diante do SENHOR, o Deus de Israel!".

[[v11-1-31]]

^<<v11-1-31,31>>^ Então Bate-Seba se curvou diante do rei com o rosto no chão e exclamou: "Que o rei Davi, meu senhor, viva para sempre!".

[[v11-1-32]]

^<<v11-1-32,32>>^ O rei Davi ordenou: "Chamem o sacerdote Zadoque, o profeta Natã e Benaia, filho de Joiada". Quando eles chegaram à presença do rei,

[[v11-1-33]]

^<<v11-1-33,33>>^ ele lhes disse: "Levem Salomão e meus conselheiros à fonte de Giom. Salomão deve ir montado em minha mula.

[[v11-1-34]]

^<<v11-1-34,34>>^ Ali o sacerdote Zadoque e o profeta Natã o ungirão rei sobre Israel. Toquem a trombeta e gritem: ‘Viva o rei Salomão!’.

[[v11-1-35]]

^<<v11-1-35,35>>^ Em seguida, acompanhem Salomão de volta para cá, e ele se sentará em meu trono. Será meu sucessor, pois eu decretei que ele reinará sobre Israel e Judá".

[[v11-1-36]]

^<<v11-1-36,36>>^ "Amém!", respondeu Benaia, filho de Joiada. "Que o SENHOR, o Deus de meu senhor, o rei, confirme suas palavras.

[[v11-1-37]]

^<<v11-1-37,37>>^ E que o SENHOR esteja com Salomão como esteve com meu senhor, o rei, e que torne o reinado de Salomão ainda maior que o seu!"

[[v11-1-38]]

^<<v11-1-38,38>>^ Então o sacerdote Zadoque, o profeta Natã, Benaia, filho de Joiada, e a guarda pessoal do rei levaram Salomão à fonte de Giom, e Salomão foi montado na mula que pertencia ao rei Davi.

[[v11-1-39]]

^<<v11-1-39,39>>^ Ali o sacerdote Zadoque pegou uma vasilha de óleo da tenda sagrada e ungiu Salomão. Em seguida, tocaram a trombeta, e todo o povo gritou: "Viva o rei Salomão!".

[[v11-1-40]]

^<<v11-1-40,40>>^ E todos acompanharam Salomão, tocando flautas e soltando gritos de alegria. A celebração era tão animada e barulhenta que fazia o chão tremer.

[[v11-1-41]]

^<<v11-1-41,41>>^ Adonias e seus convidados ouviram a celebração bem na hora em que terminavam o banquete. Quando Joabe ouviu o som da trombeta, perguntou: "O que está acontecendo? Por que a cidade está nesse alvoroço?".

[[v11-1-42]]

^<<v11-1-42,42>>^ Enquanto ele ainda falava, chegou Jônatas, filho do sacerdote Abiatar. "Entre", disse-lhe Adonias. "Você é um homem de bem. Com certeza traz boas notícias."

[[v11-1-43]]

^<<v11-1-43,43>>^ "Pelo contrário!", respondeu Jônatas. "O rei Davi, nosso senhor, proclamou Salomão o novo rei!

[[v11-1-44]]

^<<v11-1-44,44>>^ Enviou-o à fonte de Giom acompanhado do sacerdote Zadoque, do profeta Natã e de Benaia, filho de Joiada, sob a proteção da guarda pessoal do rei. Salomão ia montado na mula que pertence ao rei,

[[v11-1-45]]

^<<v11-1-45,45>>^ e Zadoque e Natã o ungiram rei na fonte de Giom. Acabam de voltar, e a cidade inteira está festejando com grande alegria. Esse é o motivo de todo esse alvoroço.

[[v11-1-46]]

^<<v11-1-46,46>>^ Além disso, agora mesmo Salomão está sentado no trono real,

[[v11-1-47]]

^<<v11-1-47,47>>^ e todos os oficiais do rei foram cumprimentar Davi e lhe disseram: ‘Que o seu Deus torne a fama de Salomão ainda maior que a sua, e que o reinado de Salomão seja ainda maior que o seu!’. E, deitado na cama, o rei curvou-se em adoração

[[v11-1-48]]

^<<v11-1-48,48>>^ e disse: ‘Louvado seja o SENHOR, o Deus de Israel, que hoje escolheu um sucessor para sentar-se em meu trono enquanto ainda estou vivo para ver isso acontecer’."

[[v11-1-49]]

^<<v11-1-49,49>>^ Então, em pânico, os convidados de Adonias se levantaram da mesa do banquete e se dispersaram.

[[v11-1-50]]

^<<v11-1-50,50>>^ Adonias, com medo de Salomão, correu para a tenda sagrada e se agarrou às pontas do altar.

[[v11-1-51]]

^<<v11-1-51,51>>^ Salomão soube que Adonias, por medo, estava agarrado às pontas do altar e dizia: "Que o rei Salomão jure hoje que não matará a mim, seu servo!".

[[v11-1-52]]

^<<v11-1-52,52>>^ Salomão respondeu: "Se ele for leal, não se tocará num só fio de cabelo de sua cabeça. Mas, se ele demonstrar más intenções, morrerá".

[[v11-1-53]]

^<<v11-1-53,53>>^ Então o rei Salomão mandou chamar Adonias, e eles o retiraram de junto do altar. Ele veio e se curvou diante do rei Salomão, que lhe disse: "Vá para casa".

'''

xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[&#60; Capítulo Anterior] | <<v11-1-0,Topo>> | xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[Próximo Capítulo &#62;]