include::./index.adoc[]

[[v11-14-0]]
=== 1 Reis, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v11-14-1]]

^<<v11-14-1,1>>^ Por esse tempo, Abias, filho de Jeroboão, ficou doente.

[[v11-14-2]]

^<<v11-14-2,2>>^ Jeroboão disse à sua esposa: "Ponha um disfarce para que ninguém reconheça que você é minha esposa e vá a Siló falar com o profeta Aías, o homem que me disse que eu seria rei sobre este povo.

[[v11-14-3]]

^<<v11-14-3,3>>^ Leve para ele um presente de dez pães, alguns bolos e uma vasilha de mel. Ele lhe dirá o que acontecerá com o menino".

[[v11-14-4]]

^<<v11-14-4,4>>^ A esposa de Jeroboão foi à casa de Aías, em Siló. Ele já estava velho e não podia mais enxergar.

[[v11-14-5]]

^<<v11-14-5,5>>^ O SENHOR, porém, tinha dito a Aías: "A esposa de Jeroboão virá aqui, fingindo que é outra pessoa. Perguntará a respeito do filho dela, pois ele está doente. Transmita-lhe a resposta que eu darei a você".

[[v11-14-6]]

^<<v11-14-6,6>>^ Quando Aías ouviu os passos dela junto à porta, disse: "Entre, esposa de Jeroboão! Por que finge ser outra pessoa? Tenho más notícias para você.

[[v11-14-7]]

^<<v11-14-7,7>>^ Leve a seu marido, Jeroboão, esta mensagem: ‘Assim diz o SENHOR, o Deus de Israel: Eu o exaltei dentre o povo e o fiz líder de Israel, meu povo.

[[v11-14-8]]

^<<v11-14-8,8>>^ Arranquei o reino da família de Davi e o entreguei a você. Mas você não tem sido como meu servo Davi, que obedeceu a meus mandamentos e me seguiu de todo o coração, e sempre fez o que me agrada.

[[v11-14-9]]

^<<v11-14-9,9>>^ Você pecou mais que todos os que vieram antes. Fez para si outros deuses e me enfureceu com seus bezerros de ouro. Sim, você me deu as costas!

[[v11-14-10]]

^<<v11-14-10,10>>^ Por isso, trarei desgraça sobre sua família e destruirei todos os seus descendentes do sexo masculino em Israel, tanto escravos como livres. Queimarei sua dinastia como se queima lixo, até que tenha desaparecido.

[[v11-14-11]]

^<<v11-14-11,11>>^ Os membros da família de Jeroboão que morrerem na cidade serão comidos pelos cães, e os que morrerem no campo serão comidos pelos abutres. Eu, o SENHOR, falei!’".

[[v11-14-12]]

^<<v11-14-12,12>>^ Então Aías disse à esposa de Jeroboão: "Volte para casa; quando você puser os pés na cidade, o menino morrerá.

[[v11-14-13]]

^<<v11-14-13,13>>^ Todo o Israel lamentará a morte dele e o sepultará. Ele será o único membro de sua família que terá um sepultamento digno, pois esse menino é o único de toda a família de Jeroboão do qual o SENHOR, o Deus de Israel, se agradou.

[[v11-14-14]]

^<<v11-14-14,14>>^ "Além disso, o SENHOR levantará um rei sobre Israel que destruirá a família de Jeroboão. Isso acontecerá hoje, agora mesmo!

[[v11-14-15]]

^<<v11-14-15,15>>^ O SENHOR sacudirá Israel como a corrente de água agita as canas de junco. Arrancará os israelitas desta boa terra que deu a seus antepassados e os dispersará além do rio Eufrates, pois enfureceram o SENHOR com os postes que levantaram para adorar a deusa Aserá.

[[v11-14-16]]

^<<v11-14-16,16>>^ Ele abandonará Israel, porque Jeroboão pecou e fez Israel pecar com ele".

[[v11-14-17]]

^<<v11-14-17,17>>^ Então a esposa de Jeroboão voltou a Tirza, e o menino morreu no instante em que ela entrou em casa.

[[v11-14-18]]

^<<v11-14-18,18>>^ E todo o Israel o sepultou e lamentou por ele, conforme o SENHOR havia anunciado por meio do profeta Aías.

[[v11-14-19]]

^<<v11-14-19,19>>^ Os demais acontecimentos do reinado de Jeroboão, as guerras e o modo como governou, estão registrados no Livro da História dos Reis de Israel .

[[v11-14-20]]

^<<v11-14-20,20>>^ Jeroboão reinou em Israel por 22 anos. Quando morreu e se reuniu a seus antepassados, seu filho Nadabe foi seu sucessor.

[[v11-14-21]]

^<<v11-14-21,21>>^ Enquanto isso, Roboão, filho de Salomão, reinava em Judá. Tinha 41 anos quando começou a reinar, e reinou por dezessete anos em Jerusalém, a cidade que o SENHOR havia escolhido dentre todas as tribos de Israel como lugar para o seu nome. A mãe de Roboão era uma mulher amonita chamada Naamá.

[[v11-14-22]]

^<<v11-14-22,22>>^ O povo de Judá fez o que era mau aos olhos do SENHOR e provocou sua ira com os pecados que cometeu, pois foram ainda piores que os de seus antepassados.

[[v11-14-23]]

^<<v11-14-23,23>>^ Construíram santuários idólatras e levantaram colunas sagradas e postes de Aserá em todos os montes e debaixo de toda árvore verdejante.

[[v11-14-24]]

^<<v11-14-24,24>>^ Havia até mesmo prostitutos cultuais por toda a terra. O povo imitava as práticas detestáveis das nações que o SENHOR havia expulsado de diante dos israelitas.

[[v11-14-25]]

^<<v11-14-25,25>>^ No quinto ano do reinado de Roboão, Sisaque, rei do Egito, subiu e atacou Jerusalém.

[[v11-14-26]]

^<<v11-14-26,26>>^ Saqueou os tesouros do templo do SENHOR e do palácio real; roubou tudo, incluindo os escudos de ouro que Salomão havia feito.

[[v11-14-27]]

^<<v11-14-27,27>>^ Mais tarde, o rei Roboão fez escudos de bronze para substituí-los e os confiou aos oficiais da guarda que protegiam a entrada do palácio real.

[[v11-14-28]]

^<<v11-14-28,28>>^ Sempre que o rei ia ao templo do SENHOR, os guardas levavam os escudos e, em seguida, os devolviam à sala da guarda.

[[v11-14-29]]

^<<v11-14-29,29>>^ Os demais acontecimentos do reinado de Roboão e tudo que ele fez estão registrados no Livro da História dos Reis de Judá .

[[v11-14-30]]

^<<v11-14-30,30>>^ Houve guerra constante entre Roboão e Jeroboão.

[[v11-14-31]]

^<<v11-14-31,31>>^ Quando Roboão morreu, foi sepultado com seus antepassados na Cidade de Davi. Sua mãe era uma mulher amonita chamada Naamá. Seu filho Abias foi seu sucessor.

'''

xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]