include::./index.adoc[]

[[v11-4-0]]
=== 1 Reis, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v11-4-1]]

^<<v11-4-1,1>>^ O rei Salomão governou sobre todo o Israel,

[[v11-4-2]]

^<<v11-4-2,2>>^ e estes foram seus oficiais mais importantes: Azarias, filho de Zadoque, era o sacerdote.

[[v11-4-3]]

^<<v11-4-3,3>>^ Eliorefe e Aías, filhos de Sisa, eram os secretários da corte. Josafá, filho de Ailude, era o historiador do reino.

[[v11-4-4]]

^<<v11-4-4,4>>^ Benaia, filho de Joiada, era o comandante do exército. Zadoque e Abiatar eram os sacerdotes.

[[v11-4-5]]

^<<v11-4-5,5>>^ Azarias, filho de Natã, era supervisor dos governadores distritais. Zabude, filho de Natã, era sacerdote e conselheiro pessoal do rei.

[[v11-4-6]]

^<<v11-4-6,6>>^ Aisar era administrador do palácio. Adonirão, filho de Abda, era encarregado dos trabalhos forçados.

[[v11-4-7]]

^<<v11-4-7,7>>^ Salomão tinha também em todo o Israel doze governadores distritais responsáveis por fornecer alimento para a casa do rei. Cada um deles fornecia provisões durante um mês do ano.

[[v11-4-8]]

^<<v11-4-8,8>>^ Estes são os nomes dos doze governadores: Ben-Hur, da região montanhosa de Efraim.

[[v11-4-9]]

^<<v11-4-9,9>>^ Ben-Dequer, em Macaz, Saalbim, Bete-Semes e Elom-Bete-Hanã.

[[v11-4-10]]

^<<v11-4-10,10>>^ Ben-Hesede, em Arubote, Socó e toda a região de Héfer.

[[v11-4-11]]

^<<v11-4-11,11>>^ Ben-Abinadabe, em toda a Nafote-Dor. (Ele era casado com Tafate, uma das filhas de Salomão.)

[[v11-4-12]]

^<<v11-4-12,12>>^ Baaná, filho de Ailude, em Taanaque e em Megido, e em toda a Bete-Seã, próxima de Zaretã, abaixo de Jezreel, e todo o território desde Bete-Seã até Abel-Meolá e para além de Jocmeão.

[[v11-4-13]]

^<<v11-4-13,13>>^ Ben-Geber, em Ramote-Gileade, incluindo as Cidades de Jair (assim chamadas por causa de Jair, da tribo de Manassés), em Gileade, e na região de Argobe, em Basã, incluindo sessenta grandes cidades fortificadas com trancas de bronze nos portões.

[[v11-4-14]]

^<<v11-4-14,14>>^ Ainadabe, filho de Ido, em Maanaim.

[[v11-4-15]]

^<<v11-4-15,15>>^ Aimaás, em Naftali. (Ele era casado com Basemate, outra filha de Salomão.)

[[v11-4-16]]

^<<v11-4-16,16>>^ Baaná, filho de Husai, em Aser e em Bealote.

[[v11-4-17]]

^<<v11-4-17,17>>^ Josafá, filho de Parua, em Issacar.

[[v11-4-18]]

^<<v11-4-18,18>>^ Simei, filho de Elá, em Benjamim.

[[v11-4-19]]

^<<v11-4-19,19>>^ Geber, filho de Uri, na terra de Gileade, incluindo os territórios de Seom, rei dos amorreus, e de Ogue, rei de Basã. Ele era o único governador dessa região.

[[v11-4-20]]

^<<v11-4-20,20>>^ O povo de Judá e Israel era tão numeroso quanto a areia na beira do mar. Todos estavam muito contentes, e tinham comida e bebida com fartura.

[[v11-4-21]]

^<<v11-4-21,21>>^ Salomão governava sobre todos os reinos, desde o rio Eufrates, ao norte, até a terra dos filisteus e a fronteira do Egito, ao sul. Os povos conquistados enviavam tributos a Salomão e continuaram a servi-lo durante toda a vida.

[[v11-4-22]]

^<<v11-4-22,22>>^ Para a provisão diária do palácio de Salomão, eram necessários trinta cestos grandes de farinha da melhor qualidade, sessenta cestos grandes de farinha comum,

[[v11-4-23]]

^<<v11-4-23,23>>^ dez bois dos currais de engorda, vinte bois do pasto, cem ovelhas, e também veados, gazelas, corças e aves seletas.

[[v11-4-24]]

^<<v11-4-24,24>>^ Salomão dominava sobre todos os reinos a oeste do rio Eufrates, desde Tifsa até Gaza, e havia paz em todas as fronteiras.

[[v11-4-25]]

^<<v11-4-25,25>>^ Durante a vida de Salomão, Judá e Israel viveram em paz e segurança. E, desde Dã, ao norte, até Berseba, ao sul, cada família possuía sua própria videira e sua própria figueira.

[[v11-4-26]]

^<<v11-4-26,26>>^ Salomão possuía quatro mil estábulos para os cavalos de seus carros de guerra e doze mil cavalos.

[[v11-4-27]]

^<<v11-4-27,27>>^ Os governadores distritais forneciam, com regularidade, o alimento para o rei Salomão e sua corte: cada um providenciava para que nada faltasse no mês que lhe havia sido designado.

[[v11-4-28]]

^<<v11-4-28,28>>^ Também providenciavam a cevada e a palha necessárias para os cavalos de guerra e os cavalos de carga nos estábulos do rei.

[[v11-4-29]]

^<<v11-4-29,29>>^ Deus concedeu a Salomão grande sabedoria e entendimento, e conhecimento tão vasto quanto a areia na beira do mar.

[[v11-4-30]]

^<<v11-4-30,30>>^ Sua sabedoria era maior que a de todos os sábios do Oriente e de todos os sábios do Egito.

[[v11-4-31]]

^<<v11-4-31,31>>^ Ele era mais sábio que qualquer outra pessoa, incluindo Etã, o ezraíta, e Hemã, Calcol e Darda, filhos de Maol. Sua fama se espalhou por todas as nações vizinhas.

[[v11-4-32]]

^<<v11-4-32,32>>^ Compôs 3.000 provérbios e escreveu 1.005 canções.

[[v11-4-33]]

^<<v11-4-33,33>>^ Podia falar com entendimento sobre plantas de toda espécie, desde o grande cedro do Líbano até o pequeno hissopo que cresce nas fendas dos muros. Também tinha conhecimento de animais, aves, répteis e peixes.

[[v11-4-34]]

^<<v11-4-34,34>>^ Reis de todas as nações enviavam seus representantes para ouvirem a sabedoria de Salomão.

'''

xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[&#60; Capítulo Anterior] | <<v11-4-0,Topo>> | xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[Próximo Capítulo &#62;]