include::./index.adoc[]

[[v11-11-0]]
=== 1 Reis, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v11-11-1]]

^<<v11-11-1,1>>^ O rei Salomão amou muitas mulheres estrangeiras. Além da filha do faraó, ele se casou com mulheres de Moabe, de Amom, de Edom, de Sidom e dos hititas.

[[v11-11-2]]

^<<v11-11-2,2>>^ O SENHOR havia instruído os israelitas claramente: "Não se casem com mulheres dessas nações, pois desviarão seu coração para os deuses delas". E, no entanto, Salomão amou essas mulheres.

[[v11-11-3]]

^<<v11-11-3,3>>^ No total, casou-se com setecentas princesas e teve trezentas concubinas. E elas desviaram seu coração do SENHOR.

[[v11-11-4]]

^<<v11-11-4,4>>^ Quando Salomão era idoso, elas o induziram a adorar outros deuses em vez de ser inteiramente fiel ao SENHOR, seu Deus, como seu pai, Davi, tinha sido.

[[v11-11-5]]

^<<v11-11-5,5>>^ Salomão adorou Astarote, a deusa dos sidônios, e Moloque, o repulsivo deus dos amonitas.

[[v11-11-6]]

^<<v11-11-6,6>>^ Com isso, Salomão fez o que era mau aos olhos do SENHOR; recusou-se a seguir inteiramente o SENHOR, como seu pai, Davi, tinha feito.

[[v11-11-7]]

^<<v11-11-7,7>>^ No monte que fica a leste de Jerusalém, chegou a construir um lugar de culto para Camos, o repulsivo deus de Moabe, e outro para Moloque, o repulsivo deus dos amonitas.

[[v11-11-8]]

^<<v11-11-8,8>>^ Salomão construiu esses lugares de culto para que suas esposas estrangeiras queimassem incenso e oferecessem sacrifícios aos deuses delas.

[[v11-11-9]]

^<<v11-11-9,9>>^ O SENHOR se irou com Salomão, porque o coração dele tinha se desviado do SENHOR, o Deus de Israel, que lhe havia aparecido duas vezes.

[[v11-11-10]]

^<<v11-11-10,10>>^ Ele tinha advertido Salomão especificamente de que não adorasse outros deuses, mas Salomão não obedeceu à ordem do SENHOR.

[[v11-11-11]]

^<<v11-11-11,11>>^ Por isso, o SENHOR lhe disse: "Uma vez que você não cumpriu minha aliança e desobedeceu a meus decretos, certamente tirarei de você o reino e o entregarei a um de seus servos.

[[v11-11-12]]

^<<v11-11-12,12>>^ Mas, por causa de seu pai, Davi, não farei isso enquanto você estiver vivo. Tirarei o reino de seu filho

[[v11-11-13]]

^<<v11-11-13,13>>^ e, ainda assim, não tirarei dele o reino inteiro; deixarei que governe sobre uma tribo, por causa do meu servo Davi e de Jerusalém, a cidade que escolhi".

[[v11-11-14]]

^<<v11-11-14,14>>^ Então o SENHOR levantou o edomita Hadade, da família real de Edom, para ser adversário de Salomão.

[[v11-11-15]]

^<<v11-11-15,15>>^ Anos antes, Davi tinha derrotado Edom. Joabe, comandante do exército de Davi, tinha ficado para trás a fim de enterrar alguns soldados israelitas mortos na batalha. Enquanto estavam ali, mataram todos os homens de Edom.

[[v11-11-16]]

^<<v11-11-16,16>>^ Joabe e o exército de Israel tinham permanecido ali seis meses, até matarem todos os edomitas.

[[v11-11-17]]

^<<v11-11-17,17>>^ Contudo, Hadade e alguns dos oficiais de seu pai conseguiram fugir e seguiram para o Egito. Na época, Hadade ainda era bem jovem.

[[v11-11-18]]

^<<v11-11-18,18>>^ Partiram de Midiã e foram a Parã, onde outros se juntaram a eles. Em seguida, foram ao Egito e se apresentaram ao faraó, o rei do Egito, que lhes ofereceu casas, sustento e terras.

[[v11-11-19]]

^<<v11-11-19,19>>^ O faraó se agradou de Hadade e lhe deu em casamento sua cunhada, a irmã da rainha Tafnes.

[[v11-11-20]]

^<<v11-11-20,20>>^ A esposa de Hadade deu à luz um filho chamado Genubate. Tafnes o criou na casa do faraó, entre os próprios filhos do faraó.

[[v11-11-21]]

^<<v11-11-21,21>>^ Quando chegou a Hadade no Egito a notícia de que Davi e seu comandante Joabe estavam mortos, ele disse ao faraó: "Deixe-me voltar para minha terra".

[[v11-11-22]]

^<<v11-11-22,22>>^ "Por quê?", perguntou o faraó. "O que lhe falta aqui para que você queira voltar para sua terra?" "Não me falta nada", respondeu ele. "Ainda assim, peço que me deixe voltar."

[[v11-11-23]]

^<<v11-11-23,23>>^ Deus também levantou Rezom, filho de Eliada, para ser adversário de Salomão. Rezom havia fugido de seu senhor Hadadezer, rei de Zobá,

[[v11-11-24]]

^<<v11-11-24,24>>^ e se tornado líder de um bando de rebeldes. Depois que Davi derrotou Hadadezer, Rezom e seus homens fugiram para Damasco, onde Rezom se tornou rei.

[[v11-11-25]]

^<<v11-11-25,25>>^ Ele foi inimigo ferrenho de Israel durante o resto do reinado de Salomão e, assim como Hadade, causou muitos problemas. Rezom continuou a reinar na Síria e odiava Israel profundamente.

[[v11-11-26]]

^<<v11-11-26,26>>^ Outro líder rebelde foi Jeroboão, filho de Nebate, um dos próprios oficiais de Salomão. Veio da cidade de Zeredá, em Efraim; sua mãe era viúva e se chamava Zerua.

[[v11-11-27]]

^<<v11-11-27,27>>^ Esta é a história por trás de sua rebelião. Salomão estava construindo o aterro e reparando os muros da Cidade de Davi, seu pai.

[[v11-11-28]]

^<<v11-11-28,28>>^ Jeroboão era um jovem muito capaz e, quando Salomão viu como era diligente, encarregou-o dos trabalhadores das tribos de Efraim e Manassés, os descendentes de José.

[[v11-11-29]]

^<<v11-11-29,29>>^ Certo dia, quando Jeroboão saía de Jerusalém, Aías, profeta de Siló, encontrou-se com ele no caminho. Aías vestia uma capa nova. Enquanto os dois estavam sozinhos no campo,

[[v11-11-30]]

^<<v11-11-30,30>>^ Aías pegou sua capa nova e a rasgou em doze partes.

[[v11-11-31]]

^<<v11-11-31,31>>^ Disse a Jeroboão: "Fique com dez pedaços, pois assim diz o SENHOR, o Deus de Israel: ‘Estou prestes a tirar o reino das mãos de Salomão e entregar dez tribos a você.

[[v11-11-32]]

^<<v11-11-32,32>>^ Contudo, deixarei uma tribo para ele, por causa do meu servo Davi e de Jerusalém, a cidade que escolhi dentre todas as tribos de Israel.

[[v11-11-33]]

^<<v11-11-33,33>>^ Pois Salomão me abandonou e adorou Astarote, a deusa dos sidônios, Camos, o deus de Moabe, e Moloque, o deus dos amonitas. Não seguiu meus caminhos nem fez o que me agrada. Não obedeceu a meus decretos e estatutos, como fez seu pai, Davi.

[[v11-11-34]]

^<<v11-11-34,34>>^ "‘Contudo, não tirarei o reino inteiro de Salomão agora. Por causa do meu servo Davi, a quem escolhi e que obedeceu a meus mandamentos e decretos, manterei Salomão no governo enquanto ele viver.

[[v11-11-35]]

^<<v11-11-35,35>>^ Mas tirarei o reino do filho dele e darei dez tribos a você.

[[v11-11-36]]

^<<v11-11-36,36>>^ O filho de Salomão terá uma tribo, para que os descendentes de meu servo Davi continuem a brilhar como uma lâmpada em Jerusalém, a cidade que escolhi como lugar para o meu nome.

[[v11-11-37]]

^<<v11-11-37,37>>^ Eu o colocarei no trono de Israel, e você governará sobre tudo que seu coração desejar.

[[v11-11-38]]

^<<v11-11-38,38>>^ Se der ouvidos ao que digo, seguir meus caminhos e fizer o que me agrada, e se obedecer a meus estatutos e mandamentos, como fez meu servo Davi, sempre estarei com você. Estabelecerei para você uma dinastia, como fiz com Davi, e lhe darei Israel.

[[v11-11-39]]

^<<v11-11-39,39>>^ Por causa do pecado de Salomão, castigarei os descendentes de Davi, mas não para sempre’".

[[v11-11-40]]

^<<v11-11-40,40>>^ Salomão tentou matar Jeroboão, mas ele fugiu para junto de Sisaque, rei do Egito, e ficou ali até a morte de Salomão.

[[v11-11-41]]

^<<v11-11-41,41>>^ Os demais acontecimentos do reinado de Salomão, incluindo todos os seus feitos e sua sabedoria, estão registrados no Livro dos Atos de Salomão .

[[v11-11-42]]

^<<v11-11-42,42>>^ Salomão reinou por quarenta anos sobre todo o Israel, em Jerusalém.

[[v11-11-43]]

^<<v11-11-43,43>>^ Quando morreu e se reuniu a seus antepassados, foi sepultado na Cidade de Davi, seu pai. Seu filho Roboão foi seu sucessor.

'''

xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[&#60; Capítulo Anterior] | <<v11-11-0,Topo>> | xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[Próximo Capítulo &#62;]