include::./index.adoc[]

[[v42-21-0]]
=== Lucas, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v42-21-1]]

^<<v42-21-1,1>>^ Estando Jesus no templo, observava os ricos depositarem suas contribuições na caixa de ofertas.

[[v42-21-2]]

^<<v42-21-2,2>>^ Então uma viúva pobre veio e colocou duas moedas pequenas.

[[v42-21-3]]

^<<v42-21-3,3>>^ Jesus disse: "Eu lhes digo a verdade: esta viúva pobre deu mais que todos os outros.

[[v42-21-4]]

^<<v42-21-4,4>>^ Eles deram uma parte do que lhes sobrava, mas ela, em sua pobreza, deu tudo que tinha".

[[v42-21-5]]

^<<v42-21-5,5>>^ Alguns de seus discípulos começaram a falar das pedras magníficas e das dádivas que adornavam o templo. Jesus, porém, disse:

[[v42-21-6]]

^<<v42-21-6,6>>^ "Virá o dia em que estas coisas serão completamente demolidas. Não restará pedra sobre pedra!".

[[v42-21-7]]

^<<v42-21-7,7>>^ Então eles perguntaram: "Mestre, quando isso tudo acontecerá? Que sinal indicará que essas coisas estão prestes a se cumprir?".

[[v42-21-8]]

^<<v42-21-8,8>>^ Ele respondeu: "Não deixem que ninguém os engane, pois muitos virão em meu nome, dizendo: ‘Eu sou o Cristo’ e afirmando: ‘Chegou a hora!’, mas não acreditem neles.

[[v42-21-9]]

^<<v42-21-9,9>>^ E, quando ouvirem falar de guerras e rebeliões, não entrem em pânico. Sim, é necessário que essas coisas aconteçam primeiro, mas ainda não será o fim".

[[v42-21-10]]

^<<v42-21-10,10>>^ E continuou: "Uma nação guerreará contra a outra, e um reino contra o outro.

[[v42-21-11]]

^<<v42-21-11,11>>^ Haverá grandes terremotos, fome e peste em vários lugares, e acontecimentos terríveis e grandes sinais no céu.

[[v42-21-12]]

^<<v42-21-12,12>>^ "Antes de tudo isso, porém, haverá um tempo de perseguição. Vocês serão arrastados para sinagogas e prisões e, por minha causa, serão julgados diante de reis e governadores.

[[v42-21-13]]

^<<v42-21-13,13>>^ Essa, contudo, será sua oportunidade de lhes falar sobre mim.

[[v42-21-14]]

^<<v42-21-14,14>>^ Mais uma vez lhes digo que não se preocupem com o modo como responderão às acusações contra vocês,

[[v42-21-15]]

^<<v42-21-15,15>>^ pois eu lhes darei as palavras certas e tanta sabedoria que seus adversários não serão capazes de responder nem contradizer.

[[v42-21-16]]

^<<v42-21-16,16>>^ Até mesmo seus pais, irmãos, parentes e amigos os trairão, e até matarão alguns de vocês.

[[v42-21-17]]

^<<v42-21-17,17>>^ Todos os odiarão por minha causa.

[[v42-21-18]]

^<<v42-21-18,18>>^ Mas nem um fio de cabelo de sua cabeça se perderá!

[[v42-21-19]]

^<<v42-21-19,19>>^ É pela perseverança que obterão a vida.

[[v42-21-20]]

^<<v42-21-20,20>>^ "E, quando virem Jerusalém cercada de exércitos, saberão que chegou a hora de sua destruição.

[[v42-21-21]]

^<<v42-21-21,21>>^ Então, quem estiver na Judeia, fuja para os montes. Quem estiver na cidade, saia. E quem estiver no campo, não volte para a cidade.

[[v42-21-22]]

^<<v42-21-22,22>>^ Pois aqueles serão os dias da vingança, e as palavras proféticas das Escrituras se cumprirão.

[[v42-21-23]]

^<<v42-21-23,23>>^ Que dias terríveis serão aqueles para as grávidas e para as mães que estiverem amamentando! Pois haverá calamidade na terra e grande ira contra este povo.

[[v42-21-24]]

^<<v42-21-24,24>>^ Serão mortos pela espada ou levados como prisioneiros para todas as nações do mundo. E Jerusalém será pisoteada pelos gentios até que o tempo deles chegue ao fim.

[[v42-21-25]]

^<<v42-21-25,25>>^ "Haverá sinais no sol, na lua e nas estrelas. E, na terra, as nações ficarão angustiadas, perplexas com o rugir dos mares e a agitação das ondas.

[[v42-21-26]]

^<<v42-21-26,26>>^ As pessoas ficarão aterrorizadas diante do que estará prestes a acontecer na terra, pois os poderes dos céus serão abalados.

[[v42-21-27]]

^<<v42-21-27,27>>^ Então todos verão o Filho do Homem vindo numa nuvem com poder e grande glória.

[[v42-21-28]]

^<<v42-21-28,28>>^ Portanto, quando todas essas coisas começarem a acontecer, levantem-se e ergam a cabeça, pois a sua salvação estará próxima".

[[v42-21-29]]

^<<v42-21-29,29>>^ Em seguida, deu-lhes esta ilustração: "Observem a figueira, e todas as outras árvores.

[[v42-21-30]]

^<<v42-21-30,30>>^ Quando as folhas aparecem, vocês sabem reconhecer, por conta própria, que o verão está próximo.

[[v42-21-31]]

^<<v42-21-31,31>>^ Da mesma forma, quando virem todas essas coisas acontecerem, saberão que o reino de Deus está próximo.

[[v42-21-32]]

^<<v42-21-32,32>>^ Eu lhes digo a verdade: esta geração não passará até que todas essas coisas tenham acontecido.

[[v42-21-33]]

^<<v42-21-33,33>>^ O céu e a terra desaparecerão, mas as minhas palavras jamais desaparecerão.

[[v42-21-34]]

^<<v42-21-34,34>>^ "Tenham cuidado! Não deixem seu coração se entorpecer com farras e bebedeiras, nem com as preocupações desta vida. Não deixem que esse dia os pegue desprevenidos,

[[v42-21-35]]

^<<v42-21-35,35>>^ como uma armadilha. Pois esse dia virá sobre todos que vivem na terra.

[[v42-21-36]]

^<<v42-21-36,36>>^ Estejam sempre atentos e orem para serem considerados dignos de escapar dos horrores que sucederão e de estar em pé na presença do Filho do Homem".

[[v42-21-37]]

^<<v42-21-37,37>>^ Todos os dias, Jesus ia ao templo ensinar e, à tarde, voltava para passar a noite no monte das Oliveiras.

[[v42-21-38]]

^<<v42-21-38,38>>^ Pela manhã, o povo se reunia bem cedo no templo para ouvi-lo falar.

'''

xref:042-lucas/042-lucas-020.adoc#v42-20-0[&#60; Capítulo Anterior] | <<v42-21-0,Topo>> | xref:042-lucas/042-lucas-022.adoc#v42-22-0[Próximo Capítulo &#62;]