include::./index.adoc[]

[[v42-17-0]]
=== Lucas, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v42-17-1]]

^<<v42-17-1,1>>^ Jesus disse a seus discípulos: "Sempre haverá o que leve as pessoas a cair em pecado, mas que aflição espera quem causa a tentação!

[[v42-17-2]]

^<<v42-17-2,2>>^ Seria melhor ser lançado no mar com uma pedra de moinho amarrada ao pescoço que fazer um destes pequeninos pecar.

[[v42-17-3]]

^<<v42-17-3,3>>^ Portanto, tenham cuidado! "Se um irmão pecar, repreenda-o e, se ele se arrepender, perdoe-o.

[[v42-17-4]]

^<<v42-17-4,4>>^ Mesmo que ele peque contra você sete vezes por dia e, a cada vez, se arrependa e peça perdão, perdoe-o".

[[v42-17-5]]

^<<v42-17-5,5>>^ Os apóstolos disseram ao Senhor: "Faça nossa fé crescer!".

[[v42-17-6]]

^<<v42-17-6,6>>^ O Senhor respondeu: "Se tivessem fé, ainda que tão pequena quanto um grão de mostarda, poderiam dizer a esta amoreira: ‘Arranque-se e plante-se no mar’, e ela lhes obedeceria.

[[v42-17-7]]

^<<v42-17-7,7>>^ "Quando um servo chega do campo depois de arar ou cuidar das ovelhas, o senhor lhe diz: ‘Venha logo para a mesa comer conosco’?

[[v42-17-8]]

^<<v42-17-8,8>>^ Não, ele diz: ‘Prepare minha refeição, apronte-se e sirva-me enquanto como e bebo. Você pode comer depois’.

[[v42-17-9]]

^<<v42-17-9,9>>^ E acaso o senhor agradece ao servo por fazer o que lhe foi ordenado?

[[v42-17-10]]

^<<v42-17-10,10>>^ Da mesma forma, quando vocês obedecem, devem dizer: ‘Somos servos inúteis; apenas cumprimos nosso dever’".

[[v42-17-11]]

^<<v42-17-11,11>>^ Dirigindo-se a Jerusalém, Jesus chegou à fronteira entre a Galileia e Samaria.

[[v42-17-12]]

^<<v42-17-12,12>>^ Ao entrar num povoado dali, dez leprosos, mantendo certa distância,

[[v42-17-13]]

^<<v42-17-13,13>>^ clamaram: "Jesus, Mestre, tenha misericórdia de nós!".

[[v42-17-14]]

^<<v42-17-14,14>>^ Ele olhou para eles e disse: "Vão e apresentem-se aos sacerdotes". E, enquanto eles iam, foram curados da lepra.

[[v42-17-15]]

^<<v42-17-15,15>>^ Um deles, ao ver-se curado, voltou a Jesus, louvando a Deus em alta voz.

[[v42-17-16]]

^<<v42-17-16,16>>^ Lançou-se a seus pés, agradecendo-lhe pelo que havia feito. Esse homem era samaritano.

[[v42-17-17]]

^<<v42-17-17,17>>^ Jesus perguntou: "Não curei dez homens? Onde estão os outros nove?

[[v42-17-18]]

^<<v42-17-18,18>>^ Ninguém voltou para dar glórias a Deus, exceto este estrangeiro?".

[[v42-17-19]]

^<<v42-17-19,19>>^ E disse ao homem: "Levante-se e vá. Sua fé o curou".

[[v42-17-20]]

^<<v42-17-20,20>>^ Certo dia, os fariseus perguntaram a Jesus: "Quando virá o reino de Deus?". Jesus respondeu: "O reino de Deus não é detectado por sinais visíveis.

[[v42-17-21]]

^<<v42-17-21,21>>^ Não se poderá dizer: ‘Está aqui!’ ou ‘Está ali!’, pois o reino de Deus já está entre vocês".

[[v42-17-22]]

^<<v42-17-22,22>>^ Então ele disse a seus discípulos: "Aproximam-se os dias em que desejarão ver o tempo do Filho do Homem, mas não o verão.

[[v42-17-23]]

^<<v42-17-23,23>>^ Dirão a vocês: ‘Vejam, lá está!’ ou ‘Aqui está ele!’, mas não os sigam.

[[v42-17-24]]

^<<v42-17-24,24>>^ Porque, assim como o relâmpago lampeja e ilumina o céu de uma extremidade a outra, assim será no dia em que vier o Filho do Homem.

[[v42-17-25]]

^<<v42-17-25,25>>^ Mas primeiro é necessário que ele sofra terrivelmente e seja rejeitado por esta geração.

[[v42-17-26]]

^<<v42-17-26,26>>^ "Quando o Filho do Homem voltar, será como no tempo de Noé.

[[v42-17-27]]

^<<v42-17-27,27>>^ Naqueles dias, o povo seguia sua rotina de banquetes, festas e casamentos, até o dia em que Noé entrou na arca e veio o dilúvio, que destruiu a todos.

[[v42-17-28]]

^<<v42-17-28,28>>^ "E o mundo será como no tempo de Ló. O povo se ocupava de seus afazeres diários, comendo e bebendo, comprando e vendendo, cultivando e construindo,

[[v42-17-29]]

^<<v42-17-29,29>>^ até o dia em que Ló deixou Sodoma. Então fogo e enxofre ardente caíram do céu e destruíram a todos.

[[v42-17-30]]

^<<v42-17-30,30>>^ Sim, tudo será como sempre foi até o dia em que o Filho do Homem for revelado.

[[v42-17-31]]

^<<v42-17-31,31>>^ Nesse dia, quem estiver na parte de cima da casa, não desça para pegar suas coisas. Quem estiver no campo, não volte para casa.

[[v42-17-32]]

^<<v42-17-32,32>>^ Lembrem-se do que aconteceu à esposa de Ló!

[[v42-17-33]]

^<<v42-17-33,33>>^ Quem se apegar à própria vida a perderá; quem abrir mão de sua vida a salvará.

[[v42-17-34]]

^<<v42-17-34,34>>^ Naquela noite, duas pessoas estarão dormindo na mesma cama; uma será levada, e a outra, deixada.

[[v42-17-35]]

^<<v42-17-35,35>>^ Duas mulheres estarão moendo cereal no moinho; uma será levada, e a outra, deixada.

[[v42-17-36]]

^<<v42-17-36,36>>^ Dois homens estarão trabalhando juntos num campo; um será levado, e o outro, deixado".

[[v42-17-37]]

^<<v42-17-37,37>>^ "Senhor, onde isso acontecerá?", perguntaram os discípulos. Jesus respondeu: "Onde estiver o cadáver, ali se ajuntarão os abutres".

'''

xref:042-lucas/042-lucas-016.adoc#v42-16-0[&#60; Capítulo Anterior] | <<v42-17-0,Topo>> | xref:042-lucas/042-lucas-018.adoc#v42-18-0[Próximo Capítulo &#62;]