include::./index.adoc[]

[[v42-20-0]]
=== Lucas, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v42-20-1]]

^<<v42-20-1,1>>^ Certo dia, quando Jesus ensinava o povo e anunciava as boas-novas no templo, os principais sacerdotes, os mestres da lei e os líderes do povo se aproximaram dele

[[v42-20-2]]

^<<v42-20-2,2>>^ e perguntaram: "Com que autoridade você faz essas coisas? Quem lhe deu esse direito?".

[[v42-20-3]]

^<<v42-20-3,3>>^ "Primeiro, deixe-me fazer uma pergunta", respondeu ele.

[[v42-20-4]]

^<<v42-20-4,4>>^ "A autoridade de João para batizar vinha do céu ou era apenas humana?"

[[v42-20-5]]

^<<v42-20-5,5>>^ Eles discutiram a questão entre si: "Se dissermos que vinha do céu, ele perguntará por que não cremos em João.

[[v42-20-6]]

^<<v42-20-6,6>>^ Mas, se dissermos que era apenas humana, seremos apedrejados pela multidão, pois todos estão convencidos de que João era profeta".

[[v42-20-7]]

^<<v42-20-7,7>>^ Por fim, responderam a Jesus que não sabiam.

[[v42-20-8]]

^<<v42-20-8,8>>^ E Jesus replicou: "Então eu também não direi com que autoridade faço essas coisas".

[[v42-20-9]]

^<<v42-20-9,9>>^ Em seguida, Jesus se voltou para o povo e contou a seguinte parábola: "Um homem plantou um vinhedo e o arrendou a alguns lavradores. Depois, partiu para um lugar distante, onde passou um longo tempo.

[[v42-20-10]]

^<<v42-20-10,10>>^ Na época da colheita da uva, enviou um de seus servos para receber sua parte da produção. Os lavradores atacaram o servo, o espancaram e o mandaram de volta, de mãos vazias.

[[v42-20-11]]

^<<v42-20-11,11>>^ Então o dono da propriedade enviou outro servo, mas eles também o insultaram, o espancaram e o mandaram de volta, de mãos vazias.

[[v42-20-12]]

^<<v42-20-12,12>>^ Enviou ainda um terceiro, e eles o feriram e o expulsaram do vinhedo.

[[v42-20-13]]

^<<v42-20-13,13>>^ "‘Que farei?’, disse o dono do vinhedo. ‘Já sei; enviarei meu filho amado. Certamente eles o respeitarão.’

[[v42-20-14]]

^<<v42-20-14,14>>^ "No entanto, quando os lavradores viram o filho, disseram uns aos outros: ‘Aí vem o herdeiro da propriedade. Vamos matá-lo e tomar posse desta terra!’.

[[v42-20-15]]

^<<v42-20-15,15>>^ Então o arrastaram para fora do vinhedo e o mataram. "O que vocês acham que o dono do vinhedo fará com eles?", perguntou Jesus.

[[v42-20-16]]

^<<v42-20-16,16>>^ "Ele virá, matará os lavradores, e arrendará o vinhedo a outros." "Que isso jamais aconteça!", disseram os que o ouviam.

[[v42-20-17]]

^<<v42-20-17,17>>^ Jesus olhou para eles e perguntou: "Então o que significa esta passagem das Escrituras: ‘A pedra que os construtores rejeitaram se tornou a pedra angular’?

[[v42-20-18]]

^<<v42-20-18,18>>^ Quem tropeçar nessa pedra será despedaçado, e aquele sobre quem ela cair será reduzido a pó".

[[v42-20-19]]

^<<v42-20-19,19>>^ Os mestres da lei e os principais sacerdotes queriam prender Jesus ali mesmo, pois perceberam que eles eram os lavradores maus a que Jesus se referia. No entanto, tinham medo da reação do povo.

[[v42-20-20]]

^<<v42-20-20,20>>^ Esperando uma oportunidade, os líderes enviaram espiões que fingiam ser pessoas sinceras. Tentaram fazer Jesus dizer algo que pudesse ser relatado ao governador romano, de modo que ele fosse preso.

[[v42-20-21]]

^<<v42-20-21,21>>^ Disseram: "Mestre, sabemos que o senhor fala e ensina o que é certo, não se deixa influenciar por outros e ensina o caminho de Deus de acordo com a verdade.

[[v42-20-22]]

^<<v42-20-22,22>>^ Então, diga-nos: É certo pagar impostos a César ou não?".

[[v42-20-23]]

^<<v42-20-23,23>>^ Jesus percebeu a hipocrisia deles e disse:

[[v42-20-24]]

^<<v42-20-24,24>>^ "Mostrem-me uma moeda de prata. De quem são a imagem e o título nela gravados?". "De César", responderam.

[[v42-20-25]]

^<<v42-20-25,25>>^ "Então deem a César o que pertence a César, e deem a Deus o que pertence a Deus", disse ele.

[[v42-20-26]]

^<<v42-20-26,26>>^ Eles não conseguiam apanhá-lo em nada que ele dizia diante do povo. Em vez disso, admiraram-se de sua resposta e se calaram.

[[v42-20-27]]

^<<v42-20-27,27>>^ Então vieram a Jesus alguns saduceus, líderes religiosos que afirmam não haver ressurreição dos mortos,

[[v42-20-28]]

^<<v42-20-28,28>>^ e perguntaram: "Mestre, Moisés nos deu uma lei segundo a qual se um homem morrer e deixar a esposa sem filhos, o irmão dele deve se casar com a viúva e ter um filho que dará continuidade ao nome do irmão.

[[v42-20-29]]

^<<v42-20-29,29>>^ Numa família havia sete irmãos. O mais velho se casou e morreu sem deixar filhos.

[[v42-20-30]]

^<<v42-20-30,30>>^ O segundo irmão se casou com a viúva, mas também morreu.

[[v42-20-31]]

^<<v42-20-31,31>>^ Então o terceiro irmão se casou com ela. O mesmo aconteceu aos sete irmãos, que morreram sem deixar filhos.

[[v42-20-32]]

^<<v42-20-32,32>>^ Por fim, a mulher também morreu.

[[v42-20-33]]

^<<v42-20-33,33>>^ Diga-nos, de quem ela será esposa na ressurreição? Afinal, os sete se casaram com ela".

[[v42-20-34]]

^<<v42-20-34,34>>^ Jesus respondeu: "O casamento é para pessoas deste mundo.

[[v42-20-35]]

^<<v42-20-35,35>>^ Mas, na era futura, aqueles que forem considerados dignos de ser ressuscitados dos mortos não se casarão nem se darão em casamento,

[[v42-20-36]]

^<<v42-20-36,36>>^ e nunca mais morrerão. Nesse sentido, serão como os anjos. São filhos de Deus e filhos da ressurreição.

[[v42-20-37]]

^<<v42-20-37,37>>^ "Agora, quanto a haver ressurreição dos mortos, o próprio Moisés provou isso quando escreveu a respeito do arbusto em chamas. Ele se referiu ao Senhor como ‘o Deus de Abraão, o Deus de Isaque e o Deus de Jacó’.

[[v42-20-38]]

^<<v42-20-38,38>>^ Portanto, ele é o Deus dos vivos, e não dos mortos, pois para ele todos vivem".

[[v42-20-39]]

^<<v42-20-39,39>>^ "Mestre, o senhor disse bem!", comentaram alguns mestres da lei.

[[v42-20-40]]

^<<v42-20-40,40>>^ E ninguém mais teve coragem de lhe fazer perguntas.

[[v42-20-41]]

^<<v42-20-41,41>>^ Então Jesus lhes perguntou: "Por que se diz que o Cristo é filho de Davi?

[[v42-20-42]]

^<<v42-20-42,42>>^ Afinal, o próprio Davi escreveu no Livro de Salmos: ‘O Senhor disse ao meu Senhor, Sente-se no lugar de honra à minha direita

[[v42-20-43]]

^<<v42-20-43,43>>^ até que eu humilhe seus inimigos, e os ponha debaixo de seus pés’.

[[v42-20-44]]

^<<v42-20-44,44>>^ Uma vez que Davi chamou o Cristo de ‘meu Senhor’, como ele pode ser filho de Davi?".

[[v42-20-45]]

^<<v42-20-45,45>>^ Então, enquanto as multidões o ouviam, Jesus se voltou para seus discípulos e disse:

[[v42-20-46]]

^<<v42-20-46,46>>^ "Cuidado com os mestres da lei! Eles gostam de se exibir com vestes longas e de receber saudações respeitosas quando andam pelas praças. E como gostam de sentar-se nos lugares de honra nas sinagogas e à cabeceira da mesa nos banquetes!

[[v42-20-47]]

^<<v42-20-47,47>>^ No entanto, tomam posse dos bens das viúvas de maneira desonesta e, depois, para dar a impressão de piedade, fazem longas orações em público. Por causa disso, serão duramente castigados".

'''

xref:042-lucas/042-lucas-019.adoc#v42-19-0[&#60; Capítulo Anterior] | <<v42-20-0,Topo>> | xref:042-lucas/042-lucas-021.adoc#v42-21-0[Próximo Capítulo &#62;]