include::./index.adoc[]

[[v42-5-0]]
=== Lucas, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v42-5-1]]

^<<v42-5-1,1>>^ Estando Jesus à beira do lago de Genesaré, grandes multidões se apertavam em volta dele para ouvir a palavra de Deus.

[[v42-5-2]]

^<<v42-5-2,2>>^ Ele notou que, junto à praia, havia dois barcos vazios, deixados por pescadores que lavavam suas redes.

[[v42-5-3]]

^<<v42-5-3,3>>^ Entrou num dos barcos e pediu a Simão, seu dono, que o afastasse um pouco da praia. Então sentou-se no barco e dali ensinou as multidões.

[[v42-5-4]]

^<<v42-5-4,4>>^ Quando terminou de falar, disse a Simão: "Agora vá para onde é mais fundo e lancem as redes para pescar".

[[v42-5-5]]

^<<v42-5-5,5>>^ Simão respondeu: "Mestre, trabalhamos duro a noite toda e não pegamos nada. Mas, por ser o senhor quem nos pede, vou lançar as redes novamente".

[[v42-5-6]]

^<<v42-5-6,6>>^ Dessa vez, as redes ficaram tão cheias de peixes que começaram a se rasgar.

[[v42-5-7]]

^<<v42-5-7,7>>^ Então pediram ajuda aos companheiros do outro barco, e logo os dois barcos estavam tão cheios de peixes que quase afundaram.

[[v42-5-8]]

^<<v42-5-8,8>>^ Quando Simão Pedro se deu conta do que havia acontecido, caiu de joelhos diante de Jesus e disse: "Por favor, Senhor, afaste-se de mim, porque sou homem pecador".

[[v42-5-9]]

^<<v42-5-9,9>>^ Pois ele e seus companheiros ficaram espantados com a quantidade de peixes que haviam pescado,

[[v42-5-10]]

^<<v42-5-10,10>>^ assim como seus sócios, Tiago e João, filhos de Zebedeu. Jesus respondeu a Simão: "Não tenha medo! De agora em diante, você será pescador de gente".

[[v42-5-11]]

^<<v42-5-11,11>>^ E, assim que chegaram à praia, deixaram tudo e seguiram Jesus.

[[v42-5-12]]

^<<v42-5-12,12>>^ Num povoado, Jesus encontrou um homem coberto de lepra. Quando o homem viu Jesus, prostrou-se com o rosto em terra e suplicou para ser curado, dizendo: "Se o senhor quiser, pode me curar e me deixar limpo".

[[v42-5-13]]

^<<v42-5-13,13>>^ Jesus estendeu a mão e o tocou. "Eu quero", respondeu. "Seja curado e fique limpo!" No mesmo instante, a lepra desapareceu.

[[v42-5-14]]

^<<v42-5-14,14>>^ Então Jesus o instruiu a não contar a ninguém o que havia acontecido. "Vá e apresente-se ao sacerdote para que ele o examine", ordenou. "Leve a oferta que a lei de Moisés exige pela sua purificação. Isso servirá como testemunho."

[[v42-5-15]]

^<<v42-5-15,15>>^ Mas as notícias a seu respeito se espalhavam ainda mais, e grandes multidões vinham para ouvi-lo e para ser curadas de suas enfermidades.

[[v42-5-16]]

^<<v42-5-16,16>>^ Ele, porém, se retirava para lugares isolados, a fim de orar.

[[v42-5-17]]

^<<v42-5-17,17>>^ Certo dia, enquanto Jesus ensinava, alguns fariseus e mestres da lei estavam sentados por perto. Eles vinham de todos os povoados da Galileia, da Judeia e de Jerusalém. E o poder do Senhor para curar estava sobre Jesus.

[[v42-5-18]]

^<<v42-5-18,18>>^ Alguns homens vieram carregando um paralítico numa maca. Tentaram levá-lo para dentro da casa, até Jesus,

[[v42-5-19]]

^<<v42-5-19,19>>^ mas não conseguiram, por causa da multidão. Então subiram ao topo da casa e removeram uma parte do teto. Em seguida, baixaram o paralítico na maca até o meio da multidão, bem na frente dele.

[[v42-5-20]]

^<<v42-5-20,20>>^ Ao ver a fé que eles tinham, Jesus disse ao paralítico: "Homem, seus pecados estão perdoados".

[[v42-5-21]]

^<<v42-5-21,21>>^ Mas os fariseus e mestres da lei pensavam: "Quem ele pensa que é? Isso é blasfêmia! Somente Deus pode perdoar pecados!".

[[v42-5-22]]

^<<v42-5-22,22>>^ Jesus, sabendo o que pensavam, perguntou: "Por que vocês questionam essas coisas em seu coração?

[[v42-5-23]]

^<<v42-5-23,23>>^ O que é mais fácil dizer: ‘Seus pecados estão perdoados?’ ou ‘Levante-se e ande’?

[[v42-5-24]]

^<<v42-5-24,24>>^ Mas eu lhes mostrarei que o Filho do Homem tem autoridade na terra para perdoar pecados". Então disse ao paralítico: "Levante-se, pegue sua maca e vá para casa".

[[v42-5-25]]

^<<v42-5-25,25>>^ De imediato, à vista de todos, o homem se levantou, pegou sua maca e foi para casa louvando a Deus.

[[v42-5-26]]

^<<v42-5-26,26>>^ Todos ficaram muitos admirados e, cheios de temor, louvaram a Deus, exclamando: "Hoje vimos coisas maravilhosas!".

[[v42-5-27]]

^<<v42-5-27,27>>^ Depois disso, Jesus saiu da cidade e viu um cobrador de impostos chamado Levi sentado no local onde se coletavam impostos. "Siga-me", disse-lhe Jesus,

[[v42-5-28]]

^<<v42-5-28,28>>^ e Levi se levantou, deixou tudo e o seguiu.

[[v42-5-29]]

^<<v42-5-29,29>>^ Mais tarde, Levi ofereceu um banquete em sua casa, em honra de Jesus. Muitos cobradores de impostos e outros convidados comeram com eles,

[[v42-5-30]]

^<<v42-5-30,30>>^ mas os fariseus e mestres da lei se queixaram aos discípulos: "Por que vocês comem e bebem com cobradores de impostos e pecadores?".

[[v42-5-31]]

^<<v42-5-31,31>>^ Jesus lhes respondeu: "As pessoas saudáveis não precisam de médico, mas sim os doentes.

[[v42-5-32]]

^<<v42-5-32,32>>^ Não vim para chamar os justos, mas sim os pecadores, para que se arrependam".

[[v42-5-33]]

^<<v42-5-33,33>>^ Algumas pessoas disseram a Jesus: "Os discípulos de João Batista jejuam e oram com frequência, e os discípulos dos fariseus também. Por que os seus vivem comendo e bebendo?".

[[v42-5-34]]

^<<v42-5-34,34>>^ Jesus respondeu: "Por acaso os convidados de um casamento jejuam enquanto festejam com o noivo?

[[v42-5-35]]

^<<v42-5-35,35>>^ Um dia, porém, o noivo lhes será tirado, e então jejuarão".

[[v42-5-36]]

^<<v42-5-36,36>>^ Jesus também lhes apresentou a seguinte ilustração: "Ninguém rasgaria um pedaço de tecido de uma roupa nova para remendar uma roupa velha. Se o fizesse, estragaria a roupa nova, e o remendo não se ajustaria à roupa velha.

[[v42-5-37]]

^<<v42-5-37,37>>^ "E ninguém colocaria vinho novo em velhos recipientes de couro. Os recipientes velhos se arrebentariam, deixando vazar o vinho e estragando o recipiente.

[[v42-5-38]]

^<<v42-5-38,38>>^ Vinho novo deve ser guardado em recipientes novos.

[[v42-5-39]]

^<<v42-5-39,39>>^ E ninguém que bebe o vinho velho escolhe beber o vinho novo, pois diz: ‘O vinho velho é melhor’".

'''

xref:042-lucas/042-lucas-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-lucas/042-lucas-006.adoc#v42-6-0[Próximo Capítulo &#62;]