include::./index.adoc[]

[[v42-9-0]]
=== Lucas, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v42-9-1]]

^<<v42-9-1,1>>^ Jesus reuniu os Doze e lhes deu poder e autoridade para expulsar todos os demônios e curar enfermidades.

[[v42-9-2]]

^<<v42-9-2,2>>^ Depois, enviou-os para anunciar o reino de Deus e curar os enfermos.

[[v42-9-3]]

^<<v42-9-3,3>>^ Ele os instruiu, dizendo: "Não levem coisa alguma em sua jornada. Não levem cajado, nem bolsa de viagem, nem comida, nem dinheiro, nem mesmo uma muda de roupa extra.

[[v42-9-4]]

^<<v42-9-4,4>>^ Aonde quer que forem, hospedem-se na mesma casa até partirem da cidade.

[[v42-9-5]]

^<<v42-9-5,5>>^ E, se uma cidade se recusar a recebê-los, sacudam a poeira dos pés ao saírem, em sinal de reprovação".

[[v42-9-6]]

^<<v42-9-6,6>>^ Então começaram a percorrer os povoados, anunciando as boas-novas e curando os enfermos.

[[v42-9-7]]

^<<v42-9-7,7>>^ Quando Herodes Antipas ouviu falar de tudo que Jesus fazia, ficou perplexo, pois alguns diziam que João Batista havia ressuscitado dos mortos.

[[v42-9-8]]

^<<v42-9-8,8>>^ Outros acreditavam que Jesus era Elias, ou um dos antigos profetas que tinha voltado à vida.

[[v42-9-9]]

^<<v42-9-9,9>>^ "Eu decapitei João", dizia Herodes. "Então quem é o homem sobre quem ouço essas histórias?" E procurava ver Jesus.

[[v42-9-10]]

^<<v42-9-10,10>>^ Quando os apóstolos voltaram, contaram a Jesus tudo que tinham feito. Em seguida, Jesus se retirou para a cidade de Betsaida, a fim de estar a sós com eles.

[[v42-9-11]]

^<<v42-9-11,11>>^ As multidões descobriram seu paradeiro e o seguiram. Ele as recebeu, ensinou-lhes a respeito do reino de Deus e curou os que estavam enfermos.

[[v42-9-12]]

^<<v42-9-12,12>>^ No fim da tarde, os Doze se aproximaram e lhe disseram: "Mande as multidões aos povoados e campos vizinhos, para que encontrem comida e abrigo para passar a noite, pois estamos num lugar isolado".

[[v42-9-13]]

^<<v42-9-13,13>>^ Jesus, porém, disse: "Providenciem vocês mesmos alimento para eles". "Temos apenas cinco pães e dois peixes", responderam. "Ou o senhor espera que compremos comida para todo esse povo?"

[[v42-9-14]]

^<<v42-9-14,14>>^ Havia ali cerca de cinco mil homens. Jesus respondeu: "Digam a eles que se sentem em grupos de cinquenta".

[[v42-9-15]]

^<<v42-9-15,15>>^ Os discípulos seguiram sua instrução, e todos se sentaram.

[[v42-9-16]]

^<<v42-9-16,16>>^ Jesus tomou os cinco pães e os dois peixes, olhou para o céu e os abençoou. Então, partiu-os em pedaços e os entregou aos discípulos para que distribuíssem ao povo.

[[v42-9-17]]

^<<v42-9-17,17>>^ Todos comeram à vontade, e os discípulos encheram ainda doze cestos com as sobras.

[[v42-9-18]]

^<<v42-9-18,18>>^ Certo dia, Jesus orava em particular, acompanhado apenas dos discípulos. Ele lhes perguntou: "Quem as multidões dizem que eu sou?".

[[v42-9-19]]

^<<v42-9-19,19>>^ Os discípulos responderam: "Alguns dizem que o senhor é João Batista; outros, que é Elias; e outros ainda, que é um dos profetas antigos que ressuscitou".

[[v42-9-20]]

^<<v42-9-20,20>>^ "E vocês?", perguntou ele. "Quem vocês dizem que eu sou?" Pedro respondeu: "O senhor é o Cristo enviado por Deus!".

[[v42-9-21]]

^<<v42-9-21,21>>^ Jesus advertiu severamente seus discípulos de que não dissessem a ninguém quem ele era.

[[v42-9-22]]

^<<v42-9-22,22>>^ "É necessário que o Filho do Homem sofra muitas coisas", disse. "Ele será rejeitado pelos líderes do povo, pelos principais sacerdotes e pelos mestres da lei. Será morto, mas no terceiro dia ressuscitará."

[[v42-9-23]]

^<<v42-9-23,23>>^ Disse ele à multidão: "Se alguém quer ser meu seguidor, negue a si mesmo, tome diariamente sua cruz e siga-me.

[[v42-9-24]]

^<<v42-9-24,24>>^ Se tentar se apegar à sua vida, a perderá. Mas, se abrir mão de sua vida por minha causa, a salvará.

[[v42-9-25]]

^<<v42-9-25,25>>^ Que vantagem há em ganhar o mundo inteiro, mas perder ou destruir a própria vida?

[[v42-9-26]]

^<<v42-9-26,26>>^ Se alguém se envergonhar de mim e de minha mensagem, o Filho do Homem se envergonhará dele quando vier em sua glória e na glória do Pai e dos santos anjos.

[[v42-9-27]]

^<<v42-9-27,27>>^ Eu lhes digo a verdade: alguns que aqui estão não morrerão antes de ver o reino de Deus!".

[[v42-9-28]]

^<<v42-9-28,28>>^ Cerca de oito dias depois, Jesus levou consigo Pedro, João e Tiago a um monte para orar.

[[v42-9-29]]

^<<v42-9-29,29>>^ Enquanto ele orava, a aparência de seu rosto foi transformada, e suas roupas se tornaram brancas e resplandecentes.

[[v42-9-30]]

^<<v42-9-30,30>>^ De repente, Moisés e Elias apareceram e começaram a falar com Jesus.

[[v42-9-31]]

^<<v42-9-31,31>>^ Tinham um aspecto glorioso e falavam sobre a partida de Jesus, que estava para se cumprir em Jerusalém.

[[v42-9-32]]

^<<v42-9-32,32>>^ Pedro e os outros lutavam contra o sono, mas acabaram despertando e viram a glória de Jesus e os dois homens que estavam com ele.

[[v42-9-33]]

^<<v42-9-33,33>>^ Quando Moisés e Elias iam se retirando, Pedro, sem saber o que dizia, falou: "Mestre, é maravilhoso estarmos aqui! Vamos fazer três tendas: uma será sua, uma de Moisés e outra de Elias".

[[v42-9-34]]

^<<v42-9-34,34>>^ Enquanto ele ainda falava, uma nuvem surgiu e os envolveu, enchendo-os de medo.

[[v42-9-35]]

^<<v42-9-35,35>>^ Então uma voz que vinha da nuvem disse: "Este é meu Filho, meu Escolhido. Ouçam-no!".

[[v42-9-36]]

^<<v42-9-36,36>>^ Quando a voz silenciou, só Jesus estava ali. Naquela ocasião, os discípulos não contaram a ninguém o que tinham visto.

[[v42-9-37]]

^<<v42-9-37,37>>^ No dia seguinte, quando desceram do monte, uma grande multidão veio ao encontro de Jesus.

[[v42-9-38]]

^<<v42-9-38,38>>^ Um homem na multidão gritou: "Mestre, suplico-lhe que veja meu filho, o único que tenho!

[[v42-9-39]]

^<<v42-9-39,39>>^ Um espírito impuro se apodera dele e o faz gritar. Lança-o em convulsões e o faz espumar pela boca. Sacode-o violentamente e quase nunca o deixa em paz.

[[v42-9-40]]

^<<v42-9-40,40>>^ Supliquei a seus discípulos que o expulsassem, mas eles não conseguiram".

[[v42-9-41]]

^<<v42-9-41,41>>^ Jesus disse: "Geração incrédula e corrompida! Até quando estarei com vocês e terei de suportá-los?". Então disse ao homem: "Traga-me seu filho".

[[v42-9-42]]

^<<v42-9-42,42>>^ Quando o menino se aproximou, o demônio o derrubou no chão, numa convulsão violenta. Jesus, porém, repreendeu o espírito impuro, curou o menino e o devolveu ao pai.

[[v42-9-43]]

^<<v42-9-43,43>>^ Todos se espantaram com a grandiosidade do poder de Deus. Enquanto todos se maravilhavam com seus feitos, Jesus disse aos discípulos:

[[v42-9-44]]

^<<v42-9-44,44>>^ "Ouçam-me e lembrem-se do que lhes digo: o Filho do Homem será traído e entregue em mãos humanas".

[[v42-9-45]]

^<<v42-9-45,45>>^ Eles, porém, não entendiam essas coisas. O significado estava escondido deles, de modo que não eram capazes de compreender e tinham medo de perguntar.

[[v42-9-46]]

^<<v42-9-46,46>>^ Os discípulos começaram a discutir sobre qual deles seria o maior.

[[v42-9-47]]

^<<v42-9-47,47>>^ Jesus, conhecendo seus pensamentos, trouxe para junto de si uma criança pequena

[[v42-9-48]]

^<<v42-9-48,48>>^ e disse: "Quem recebe uma criança como esta em meu nome recebe a mim, e quem me recebe também recebe aquele que me enviou. Portanto, o menor entre vocês será o maior".

[[v42-9-49]]

^<<v42-9-49,49>>^ João disse a Jesus: "Mestre, vimos alguém usar seu nome para expulsar demônios; nós o proibimos, pois ele não era do nosso grupo".

[[v42-9-50]]

^<<v42-9-50,50>>^ "Não o proíbam!", disse Jesus. "Quem não é contra vocês é a favor de vocês."

[[v42-9-51]]

^<<v42-9-51,51>>^ Como se aproximava o tempo de ser elevado ao céu, Jesus partiu com determinação para Jerusalém.

[[v42-9-52]]

^<<v42-9-52,52>>^ Enviou mensageiros adiante até um povoado samaritano, a fim de fazerem os preparativos para sua chegada.

[[v42-9-53]]

^<<v42-9-53,53>>^ Contudo, os habitantes do povoado não receberam Jesus, porque parecia evidente que ele estava a caminho de Jerusalém.

[[v42-9-54]]

^<<v42-9-54,54>>^ Percebendo isso, Tiago e João disseram a Jesus: "Senhor, quer que mandemos cair fogo do céu para consumi-los?".

[[v42-9-55]]

^<<v42-9-55,55>>^ Jesus, porém, se voltou para eles e os repreendeu.

[[v42-9-56]]

^<<v42-9-56,56>>^ E seguiram para outro povoado.

[[v42-9-57]]

^<<v42-9-57,57>>^ Quando andavam pelo caminho, alguém disse a Jesus: "Eu o seguirei aonde quer que vá".

[[v42-9-58]]

^<<v42-9-58,58>>^ Jesus respondeu: "As raposas têm tocas onde morar e as aves têm ninhos, mas o Filho do Homem não tem sequer um lugar para recostar a cabeça".

[[v42-9-59]]

^<<v42-9-59,59>>^ E a outra pessoa ele disse: "Siga-me". O homem, porém, respondeu: "Senhor, deixe-me primeiro sepultar meu pai".

[[v42-9-60]]

^<<v42-9-60,60>>^ Jesus respondeu: "Deixe que os mortos sepultem seus próprios mortos. Você, porém, deve ir e anunciar o reino de Deus".

[[v42-9-61]]

^<<v42-9-61,61>>^ Outro, ainda, disse: "Senhor, eu o seguirei, mas deixe que antes me despeça de minha família".

[[v42-9-62]]

^<<v42-9-62,62>>^ Mas Jesus lhe disse: "Quem põe a mão no arado e olha para trás não está apto para o reino de Deus".

'''

xref:042-lucas/042-lucas-008.adoc#v42-8-0[&#60; Capítulo Anterior] | <<v42-9-0,Topo>> | xref:042-lucas/042-lucas-010.adoc#v42-10-0[Próximo Capítulo &#62;]