include::./index.adoc[]

[[v42-19-0]]
=== Lucas, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v42-19-1]]

^<<v42-19-1,1>>^ Jesus entrou em Jericó e atravessava a cidade.

[[v42-19-2]]

^<<v42-19-2,2>>^ Havia ali um homem rico chamado Zaqueu, chefe dos cobradores de impostos.

[[v42-19-3]]

^<<v42-19-3,3>>^ Tentava ver Jesus, mas era baixo demais e não conseguia olhar por cima da multidão.

[[v42-19-4]]

^<<v42-19-4,4>>^ Por isso, correu adiante e subiu numa figueira-brava, no caminho por onde Jesus passaria.

[[v42-19-5]]

^<<v42-19-5,5>>^ Quando Jesus chegou ali, olhou para cima e disse: "Zaqueu, desça depressa! Hoje devo hospedar-me em sua casa".

[[v42-19-6]]

^<<v42-19-6,6>>^ Sem demora, Zaqueu desceu e, com alegria, recebeu Jesus em sua casa.

[[v42-19-7]]

^<<v42-19-7,7>>^ Ao ver isso, o povo começou a se queixar: "Ele foi se hospedar na casa de um pecador!".

[[v42-19-8]]

^<<v42-19-8,8>>^ Enquanto isso, Zaqueu se levantou e disse: "Senhor, darei metade das minhas riquezas aos pobres. E, se explorei alguém na cobrança de impostos, devolverei quatro vezes mais!".

[[v42-19-9]]

^<<v42-19-9,9>>^ Jesus respondeu: "Hoje chegou a salvação a esta casa, pois este homem também é filho de Abraão.

[[v42-19-10]]

^<<v42-19-10,10>>^ Porque o Filho do Homem veio buscar e salvar os perdidos".

[[v42-19-11]]

^<<v42-19-11,11>>^ A multidão estava atenta ao que Jesus dizia. Então, como ele se aproximava de Jerusalém, contou-lhes uma parábola, pois o povo achava que o reino de Deus começaria de imediato.

[[v42-19-12]]

^<<v42-19-12,12>>^ Disse ele: "Um nobre foi chamado a um país distante para ser coroado rei e depois voltar.

[[v42-19-13]]

^<<v42-19-13,13>>^ Antes de partir, reuniu dez de seus servos e deu a cada um deles dez moedas de prata, dizendo: ‘Invistam esse dinheiro enquanto eu estiver fora’.

[[v42-19-14]]

^<<v42-19-14,14>>^ Seu povo, porém, o odiava, e enviou uma delegação atrás dele para dizer: ‘Não queremos que ele seja nosso rei’.

[[v42-19-15]]

^<<v42-19-15,15>>^ "Depois de ser coroado, ele voltou e chamou os servos aos quais tinha confiado o dinheiro, pois queria saber quanto haviam lucrado.

[[v42-19-16]]

^<<v42-19-16,16>>^ O primeiro servo informou: ‘Senhor, investi seu dinheiro, e ele rendeu dez vezes a quantia recebida.

[[v42-19-17]]

^<<v42-19-17,17>>^ "‘Muito bem!’, disse o rei. ‘Você é um bom servo. Foi fiel no pouco que lhe confiei e, como recompensa, governará dez cidades.’

[[v42-19-18]]

^<<v42-19-18,18>>^ "O servo seguinte informou: ‘Senhor, investi seu dinheiro, e ele rendeu cinco vezes a quantia recebida’.

[[v42-19-19]]

^<<v42-19-19,19>>^ "‘Muito bem!’, disse o rei. ‘Você governará cinco cidades.’

[[v42-19-20]]

^<<v42-19-20,20>>^ "O terceiro servo, porém, trouxe de volta apenas a quantia recebida e disse: ‘Senhor, escondi seu dinheiro para mantê-lo seguro.

[[v42-19-21]]

^<<v42-19-21,21>>^ Tive medo, pois o senhor é um homem severo. Toma o que não lhe pertence e colhe o que não plantou’.

[[v42-19-22]]

^<<v42-19-22,22>>^ "‘Servo mau!’, exclamou o senhor. ‘Suas próprias palavras o condenam. Se você sabia que sou homem severo, que tomo o que não me pertence e colho o que não plantei,

[[v42-19-23]]

^<<v42-19-23,23>>^ por que não depositou meu dinheiro? Pelo menos eu teria recebido os juros.’

[[v42-19-24]]

^<<v42-19-24,24>>^ "Então, voltando-se para os outros que estavam ali perto, o rei ordenou: ‘Tomem o dinheiro deste servo e deem ao que tem dez moedas.

[[v42-19-25]]

^<<v42-19-25,25>>^ "‘Mas senhor!’, disseram eles. ‘Ele já tem dez!’

[[v42-19-26]]

^<<v42-19-26,26>>^ "Então o rei respondeu: ‘Sim, ao que tem, mais lhe será dado; mas do que nada tem, até o que tem lhe será tomado.

[[v42-19-27]]

^<<v42-19-27,27>>^ E, quanto a esses meus inimigos que não queriam que eu fosse seu rei, tragam-nos aqui e executem-nos na minha presença’".

[[v42-19-28]]

^<<v42-19-28,28>>^ Depois de contar essa história, Jesus prosseguiu rumo a Jerusalém.

[[v42-19-29]]

^<<v42-19-29,29>>^ Quando chegou a Betfagé e Betânia, próximo ao monte das Oliveiras, enviou dois de seus discípulos.

[[v42-19-30]]

^<<v42-19-30,30>>^ "Vão àquele povoado adiante", disse ele. "Assim que entrarem, verão amarrado ali um jumentinho no qual ninguém jamais montou. Desamarrem-no e tragam-no para cá.

[[v42-19-31]]

^<<v42-19-31,31>>^ Se alguém perguntar: ‘Por que estão soltando o jumentinho?’, respondam apenas: ‘O Senhor precisa dele’."

[[v42-19-32]]

^<<v42-19-32,32>>^ Eles foram e encontraram o jumentinho, exatamente como Jesus tinha dito.

[[v42-19-33]]

^<<v42-19-33,33>>^ E, enquanto o desamarravam, seus donos perguntaram: "Por que estão soltando o jumentinho?".

[[v42-19-34]]

^<<v42-19-34,34>>^ Os discípulos responderam: "O Senhor precisa dele".

[[v42-19-35]]

^<<v42-19-35,35>>^ Então trouxeram o jumentinho e lançaram seus mantos sobre o animal, para que Jesus montasse nele.

[[v42-19-36]]

^<<v42-19-36,36>>^ À medida que Jesus ia passando, as multidões espalhavam seus mantos ao longo do caminho diante dele.

[[v42-19-37]]

^<<v42-19-37,37>>^ Quando ele chegou próximo à descida do monte das Oliveiras, seus seguidores começaram a gritar e a cantar enquanto o acompanhavam, louvando a Deus por todos os milagres maravilhosos que tinham visto.

[[v42-19-38]]

^<<v42-19-38,38>>^ "Bendito é o Rei que vem em nome do Senhor! Paz no céu e glória nas maiores alturas!".

[[v42-19-39]]

^<<v42-19-39,39>>^ Alguns dos fariseus que estavam entre a multidão disseram: "Mestre, repreenda seus seguidores por dizerem estas coisas!".

[[v42-19-40]]

^<<v42-19-40,40>>^ Ele, porém, respondeu: "Se eles se calarem, as próprias pedras clamarão!".

[[v42-19-41]]

^<<v42-19-41,41>>^ Quando Jesus se aproximou de Jerusalém e viu a cidade, começou a chorar.

[[v42-19-42]]

^<<v42-19-42,42>>^ "Como eu gostaria que hoje você compreendesse o caminho para a paz!", disse ele. "Agora, porém, isso está oculto a seus olhos.

[[v42-19-43]]

^<<v42-19-43,43>>^ Chegará o tempo em que seus inimigos construirão rampas para atacar seus muros e a rodearão e apertarão o cerco por todos os lados.

[[v42-19-44]]

^<<v42-19-44,44>>^ Esmagarão você e seus filhos e não deixarão pedra sobre pedra, pois você não reconheceu que Deus a visitou."

[[v42-19-45]]

^<<v42-19-45,45>>^ Então Jesus entrou no templo e começou a expulsar os que ali vendiam,

[[v42-19-46]]

^<<v42-19-46,46>>^ dizendo: "As Escrituras declaram: ‘Meu templo será casa de oração’, mas vocês o transformaram num esconderijo de ladrões!".

[[v42-19-47]]

^<<v42-19-47,47>>^ Jesus ensinava todos os dias no templo, mas os principais sacerdotes, os mestres da lei e outros líderes do povo planejavam matá-lo.

[[v42-19-48]]

^<<v42-19-48,48>>^ Contudo, não conseguiam pensar num modo de fazê-lo, pois o povo ouvia atentamente tudo que ele dizia.

'''

xref:042-lucas/042-lucas-018.adoc#v42-18-0[&#60; Capítulo Anterior] | <<v42-19-0,Topo>> | xref:042-lucas/042-lucas-020.adoc#v42-20-0[Próximo Capítulo &#62;]