include::./index.adoc[]

[[v42-24-0]]
=== Lucas, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v42-24-1]]

^<<v42-24-1,1>>^ No primeiro dia da semana, bem cedo, as mulheres foram ao túmulo, levando as especiarias que haviam preparado,

[[v42-24-2]]

^<<v42-24-2,2>>^ e viram que a pedra tinha sido afastada da entrada.

[[v42-24-3]]

^<<v42-24-3,3>>^ Quando entraram no túmulo, não encontraram o corpo do Senhor Jesus.

[[v42-24-4]]

^<<v42-24-4,4>>^ Enquanto estavam ali, perplexas, dois homens apareceram, vestidos com mantos resplandecentes.

[[v42-24-5]]

^<<v42-24-5,5>>^ As mulheres ficaram amedrontadas e se curvaram com o rosto em terra. Então os homens perguntaram: "Por que vocês procuram entre os mortos aquele que vive?

[[v42-24-6]]

^<<v42-24-6,6>>^ Ele não está aqui. Ressuscitou! Lembrem-se do que ele lhes disse na Galileia:

[[v42-24-7]]

^<<v42-24-7,7>>^ ‘É necessário que o Filho do Homem seja traído e entregue nas mãos de pecadores, seja crucificado e ressuscite no terceiro dia’".

[[v42-24-8]]

^<<v42-24-8,8>>^ Então lembraram-se dessas palavras de Jesus

[[v42-24-9]]

^<<v42-24-9,9>>^ e, voltando do túmulo, foram contar aos onze discípulos e a todos os outros o que havia acontecido.

[[v42-24-10]]

^<<v42-24-10,10>>^ Maria Madalena, Joana, Maria, mãe de Tiago, e as outras mulheres que as acompanhavam relataram tudo aos apóstolos.

[[v42-24-11]]

^<<v42-24-11,11>>^ Para eles, porém, a história pareceu absurda, e não acreditaram nelas.

[[v42-24-12]]

^<<v42-24-12,12>>^ Mas Pedro se levantou e correu até o túmulo. Abaixando-se, olhou atentamente para dentro e viu os panos de linho vazios; então voltou para casa, admirado com o que havia acontecido.

[[v42-24-13]]

^<<v42-24-13,13>>^ Naquele mesmo dia, dois dos seguidores de Jesus caminhavam para o povoado de Emaús, a onze quilômetros de Jerusalém.

[[v42-24-14]]

^<<v42-24-14,14>>^ No caminho, falavam a respeito de tudo que havia acontecido.

[[v42-24-15]]

^<<v42-24-15,15>>^ Enquanto conversavam e discutiam, o próprio Jesus se aproximou e começou a andar com eles.

[[v42-24-16]]

^<<v42-24-16,16>>^ Os olhos deles, porém, estavam como que impedidos de reconhecê-lo.

[[v42-24-17]]

^<<v42-24-17,17>>^ Jesus lhes perguntou: "Sobre o que vocês tanto debatem enquanto caminham?". Eles pararam, com o rosto entristecido.

[[v42-24-18]]

^<<v42-24-18,18>>^ Então um deles, chamado Cleopas, respondeu: "Você deve ser a única pessoa em Jerusalém que não sabe das coisas que aconteceram lá nos últimos dias".

[[v42-24-19]]

^<<v42-24-19,19>>^ "Que coisas?", perguntou Jesus. "As coisas que aconteceram com Jesus de Nazaré", responderam eles. "Ele era um profeta de palavras e ações poderosas aos olhos de Deus e de todo o povo.

[[v42-24-20]]

^<<v42-24-20,20>>^ Mas os principais sacerdotes e outros líderes religiosos o entregaram para que fosse condenado à morte e o crucificaram.

[[v42-24-21]]

^<<v42-24-21,21>>^ Tínhamos esperança de que ele fosse aquele que resgataria Israel. Isso tudo aconteceu há três dias.

[[v42-24-22]]

^<<v42-24-22,22>>^ "Algumas mulheres de nosso grupo foram até seu túmulo hoje bem cedo e voltaram contando uma história surpreendente.

[[v42-24-23]]

^<<v42-24-23,23>>^ Disseram que o corpo havia sumido e que viram anjos que lhes disseram que Jesus está vivo.

[[v42-24-24]]

^<<v42-24-24,24>>^ Alguns homens de nosso grupo correram até lá para ver e, de fato, tudo estava como as mulheres disseram, mas não o viram."

[[v42-24-25]]

^<<v42-24-25,25>>^ Então Jesus lhes disse: "Como vocês são tolos! Como custam a entender o que os profetas registraram nas Escrituras!

[[v42-24-26]]

^<<v42-24-26,26>>^ Não percebem que era necessário que o Cristo sofresse essas coisas antes de entrar em sua glória?".

[[v42-24-27]]

^<<v42-24-27,27>>^ Então Jesus os conduziu por todos os escritos de Moisés e dos profetas, explicando o que as Escrituras diziam a respeito dele.

[[v42-24-28]]

^<<v42-24-28,28>>^ Aproximando-se de Emaús, o destino deles, Jesus fez como quem seguiria viagem,

[[v42-24-29]]

^<<v42-24-29,29>>^ mas eles insistiram: "Fique conosco esta noite, pois já é tarde". E Jesus foi para casa com eles.

[[v42-24-30]]

^<<v42-24-30,30>>^ Quando estavam à mesa, ele tomou o pão e o abençoou. Depois, partiu-o e lhes deu.

[[v42-24-31]]

^<<v42-24-31,31>>^ Então os olhos deles foram abertos e o reconheceram. Nesse momento, ele desapareceu.

[[v42-24-32]]

^<<v42-24-32,32>>^ Disseram um ao outro: "Não ardia o nosso coração quando ele falava conosco no caminho e nos explicava as Escrituras?".

[[v42-24-33]]

^<<v42-24-33,33>>^ E, na mesma hora, levantaram-se e voltaram para Jerusalém. Ali, encontraram os onze discípulos e os outros que estavam reunidos com eles,

[[v42-24-34]]

^<<v42-24-34,34>>^ que lhes disseram: "É verdade que o Senhor ressuscitou! Ele apareceu a Pedro!".

[[v42-24-35]]

^<<v42-24-35,35>>^ Então os dois contaram como Jesus tinha aparecido enquanto andavam pelo caminho, e como o haviam reconhecido quando ele partiu o pão.

[[v42-24-36]]

^<<v42-24-36,36>>^ Enquanto contavam isso, o próprio Jesus apareceu entre eles e lhes disse: "Paz seja com vocês!".

[[v42-24-37]]

^<<v42-24-37,37>>^ Eles se assustaram e ficaram amedrontados, pensando que viam um fantasma.

[[v42-24-38]]

^<<v42-24-38,38>>^ "Por que estão perturbados?", perguntou ele. "Por que seu coração está cheio de dúvida?

[[v42-24-39]]

^<<v42-24-39,39>>^ Vejam minhas mãos e meus pés. Sou eu mesmo! Toquem-me e vejam que não sou um fantasma, pois fantasmas não têm carne nem ossos e, como veem, eu tenho."

[[v42-24-40]]

^<<v42-24-40,40>>^ Enquanto falava, mostrou-lhes as mãos e os pés.

[[v42-24-41]]

^<<v42-24-41,41>>^ Eles continuaram sem acreditar, cheios de alegria e espanto. Então Jesus perguntou: "Vocês têm aqui alguma coisa para comer?".

[[v42-24-42]]

^<<v42-24-42,42>>^ Eles lhe deram um pedaço de peixe assado,

[[v42-24-43]]

^<<v42-24-43,43>>^ e ele comeu diante de todos.

[[v42-24-44]]

^<<v42-24-44,44>>^ Em seguida, disse: "Enquanto ainda estava com vocês, eu lhes falei que devia se cumprir tudo que a lei de Moisés, os profetas e os salmos diziam a meu respeito".

[[v42-24-45]]

^<<v42-24-45,45>>^ Então ele lhes abriu a mente para que entendessem as Escrituras,

[[v42-24-46]]

^<<v42-24-46,46>>^ e disse: "Sim, está escrito que o Cristo haveria de sofrer, morrer e ressuscitar no terceiro dia,

[[v42-24-47]]

^<<v42-24-47,47>>^ e que a mensagem de arrependimento para o perdão dos pecados seria proclamada com a autoridade de seu nome a todas as nações, começando por Jerusalém.

[[v42-24-48]]

^<<v42-24-48,48>>^ Vocês são testemunhas dessas coisas.

[[v42-24-49]]

^<<v42-24-49,49>>^ "Agora, envio a vocês a promessa de meu Pai. Mas fiquem na cidade até que sejam revestidos do poder do céu".

[[v42-24-50]]

^<<v42-24-50,50>>^ Depois Jesus os levou a Betânia e, levantando as mãos para o céu, os abençoou.

[[v42-24-51]]

^<<v42-24-51,51>>^ Enquanto ainda os abençoava, deixou-os e foi elevado ao céu.

[[v42-24-52]]

^<<v42-24-52,52>>^ Então eles o adoraram e voltaram para Jerusalém cheios de grande alegria.

[[v42-24-53]]

^<<v42-24-53,53>>^ E estavam sempre no templo, louvando a Deus.

'''

xref:042-lucas/042-lucas-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-joao/043-joao-001.adoc#v43-1-0[Próximo Capítulo &#62;]