include::./index.adoc[]

[[v42-13-0]]
=== Lucas, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v42-13-1]]

^<<v42-13-1,1>>^ Por essa época, Jesus foi informado de que Pilatos havia assassinado algumas pessoas da Galileia enquanto ofereciam sacrifícios.

[[v42-13-2]]

^<<v42-13-2,2>>^ "Vocês pensam que esses galileus eram mais pecadores que todos os outros da Galileia?", perguntou Jesus. "Foi por isso que sofreram?

[[v42-13-3]]

^<<v42-13-3,3>>^ De maneira alguma! Mas, se não se arrependerem, vocês também morrerão.

[[v42-13-4]]

^<<v42-13-4,4>>^ E quanto aos dezoito que morreram quando a torre de Siloé caiu sobre eles? Eram mais pecadores que os demais de Jerusalém?

[[v42-13-5]]

^<<v42-13-5,5>>^ Não! E eu volto a lhes dizer: a menos que se arrependam, todos vocês também morrerão."

[[v42-13-6]]

^<<v42-13-6,6>>^ Então Jesus contou a seguinte parábola: "Um homem tinha uma figueira em seu vinhedo e foi várias vezes procurar frutos nela, sem sucesso.

[[v42-13-7]]

^<<v42-13-7,7>>^ Por fim, disse ao jardineiro: ‘Esperei três anos e não encontrei um figo sequer. Corte a figueira, pois só está ocupando espaço no pomar’.

[[v42-13-8]]

^<<v42-13-8,8>>^ "O jardineiro respondeu: ‘Senhor, deixe-a mais um ano, e eu cuidarei dela e a adubarei.

[[v42-13-9]]

^<<v42-13-9,9>>^ Se der figos no próximo ano, ótimo; se não, mande cortá-la’".

[[v42-13-10]]

^<<v42-13-10,10>>^ Certo sábado, quando Jesus ensinava numa sinagoga,

[[v42-13-11]]

^<<v42-13-11,11>>^ apareceu uma mulher enferma por causa de um espírito impuro. Andava encurvada havia dezoito anos e não conseguia se endireitar.

[[v42-13-12]]

^<<v42-13-12,12>>^ Ao vê-la, Jesus a chamou para perto e disse: "Mulher, você está curada de sua doença!".

[[v42-13-13]]

^<<v42-13-13,13>>^ Então ele a tocou e, no mesmo instante, ela conseguiu se endireitar e começou a louvar a Deus.

[[v42-13-14]]

^<<v42-13-14,14>>^ O chefe da sinagoga ficou indignado porque Jesus a tinha curado no sábado. "Há seis dias na semana para trabalhar", disse ele à multidão. "Venham nesses dias para serem curados, e não no sábado."

[[v42-13-15]]

^<<v42-13-15,15>>^ O Senhor, porém, respondeu: "Hipócritas! Todos vocês trabalham no sábado! Acaso não desamarram no sábado o boi ou o jumento do estábulo e o levam dali para lhe dar água?

[[v42-13-16]]

^<<v42-13-16,16>>^ Esta mulher, uma filha de Abraão, foi mantida presa por Satanás durante dezoito anos. Não deveria ela ser liberta, mesmo que seja no sábado?".

[[v42-13-17]]

^<<v42-13-17,17>>^ As palavras de Jesus envergonharam seus adversários, mas todo o povo se alegrava com as coisas maravilhosas que ele fazia.

[[v42-13-18]]

^<<v42-13-18,18>>^ Então Jesus disse: "Com que se parece o reino de Deus? Com o que posso compará-lo?

[[v42-13-19]]

^<<v42-13-19,19>>^ É como a semente de mostarda que alguém plantou na horta. Ela cresce e se torna uma árvore, e os pássaros fazem ninhos em seus galhos".

[[v42-13-20]]

^<<v42-13-20,20>>^ Disse também: "Com que mais se parece o reino de Deus?

[[v42-13-21]]

^<<v42-13-21,21>>^ É como o fermento que uma mulher usa para fazer pão. Embora ela coloque apenas uma pequena quantidade de fermento em três medidas de farinha, toda a massa fica fermentada".

[[v42-13-22]]

^<<v42-13-22,22>>^ Jesus foi pelas cidades e povoados ensinando ao longo do caminho, em direção a Jerusalém.

[[v42-13-23]]

^<<v42-13-23,23>>^ Alguém lhe perguntou: "Senhor, só alguns poucos serão salvos?". Ele respondeu:

[[v42-13-24]]

^<<v42-13-24,24>>^ "Esforcem-se para entrar pela porta estreita, pois muitos tentarão entrar, mas não conseguirão.

[[v42-13-25]]

^<<v42-13-25,25>>^ Quando o dono da casa tiver trancado a porta, será tarde demais. Vocês ficarão do lado de fora, batendo e pedindo: ‘Senhor, abra a porta para nós!’. Mas ele responderá: ‘Não os conheço, nem sei de onde são’.

[[v42-13-26]]

^<<v42-13-26,26>>^ Então vocês dirão: ‘Nós comemos e bebemos com o senhor, e o senhor ensinou em nossas ruas’.

[[v42-13-27]]

^<<v42-13-27,27>>^ E ele responderá: ‘Não os conheço nem sei de onde são. Afastem-se de mim, todos vocês que praticam o mal!’.

[[v42-13-28]]

^<<v42-13-28,28>>^ "Haverá choro e ranger de dentes, pois verão Abraão, Isaque, Jacó e todos os profetas no reino de Deus, mas vocês serão lançados fora.

[[v42-13-29]]

^<<v42-13-29,29>>^ E virão pessoas de toda parte, do leste e do oeste, do norte e do sul, para ocupar seus lugares à mesa no reino de Deus.

[[v42-13-30]]

^<<v42-13-30,30>>^ E prestem atenção: alguns últimos serão os primeiros, e alguns primeiros serão os últimos".

[[v42-13-31]]

^<<v42-13-31,31>>^ Naquele momento, alguns fariseus lhe disseram: "Vá embora daqui, pois Herodes Antipas quer matá-lo!".

[[v42-13-32]]

^<<v42-13-32,32>>^ Jesus respondeu: "Vão dizer àquela raposa que continuarei a expulsar demônios e a curar hoje e amanhã; e, no terceiro dia, realizarei meu propósito.

[[v42-13-33]]

^<<v42-13-33,33>>^ Sim, hoje, amanhã e depois de amanhã, devo seguir meu caminho. Pois nenhum profeta de Deus deve ser morto fora de Jerusalém!

[[v42-13-34]]

^<<v42-13-34,34>>^ "Jerusalém, Jerusalém, cidade que mata profetas e apedreja os mensageiros de Deus! Quantas vezes eu quis juntar seus filhos como a galinha protege os pintinhos sob as asas, mas você não deixou.

[[v42-13-35]]

^<<v42-13-35,35>>^ E, agora, sua casa foi abandonada, e você nunca mais me verá, até que diga: ‘Bendito é o que vem em nome do Senhor!’".

'''

xref:042-lucas/042-lucas-012.adoc#v42-12-0[&#60; Capítulo Anterior] | <<v42-13-0,Topo>> | xref:042-lucas/042-lucas-014.adoc#v42-14-0[Próximo Capítulo &#62;]