include::./index.adoc[]

[[v42-8-0]]
=== Lucas, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v42-8-1]]

^<<v42-8-1,1>>^ Pouco tempo depois, Jesus começou a percorrer as cidades e os povoados vizinhos, anunciando as boas-novas a respeito do reino de Deus. Iam com ele os Doze

[[v42-8-2]]

^<<v42-8-2,2>>^ e também algumas mulheres que tinham sido curadas de espíritos impuros e enfermidades. Entre elas estavam Maria Madalena, de quem ele havia expulsado sete demônios;

[[v42-8-3]]

^<<v42-8-3,3>>^ Joana, esposa de Cuza, administrador de Herodes; Susana, e muitas outras que contribuíam com seus próprios recursos para o sustento de Jesus e seus discípulos.

[[v42-8-4]]

^<<v42-8-4,4>>^ Certo dia, uma grande multidão, vinda de várias cidades, juntou-se para ouvir Jesus, e ele lhes contou uma parábola:

[[v42-8-5]]

^<<v42-8-5,5>>^ "Um lavrador saiu para semear. Enquanto espalhava as sementes pelo campo, algumas caíram à beira do caminho, onde foram pisadas, e as aves vieram e as comeram.

[[v42-8-6]]

^<<v42-8-6,6>>^ Outras caíram entre as pedras e começaram a crescer, mas as plantas logo murcharam por falta de umidade.

[[v42-8-7]]

^<<v42-8-7,7>>^ Outras sementes caíram entre os espinhos, que cresceram com elas e sufocaram os brotos.

[[v42-8-8]]

^<<v42-8-8,8>>^ Ainda outras caíram em solo fértil e produziram uma colheita cem vezes maior que a quantidade semeada". Quando ele terminou de dizer isso, declarou: "Quem é capaz de ouvir, ouça com atenção!".

[[v42-8-9]]

^<<v42-8-9,9>>^ Seus discípulos lhe perguntaram o que a parábola significava.

[[v42-8-10]]

^<<v42-8-10,10>>^ Ele respondeu: "A vocês é permitido entender os segredos do reino de Deus, mas uso parábolas para ensinar os outros, a fim de que, ‘Quando olharem, não vejam; quando escutarem, não entendam’.

[[v42-8-11]]

^<<v42-8-11,11>>^ "Este é o significado da parábola: As sementes são a palavra de Deus.

[[v42-8-12]]

^<<v42-8-12,12>>^ As sementes que caíram à beira do caminho representam os que ouvem a mensagem, mas o diabo vem e a arranca do coração deles e os impede de crer e ser salvos.

[[v42-8-13]]

^<<v42-8-13,13>>^ As sementes no solo rochoso representam os que ouvem a mensagem e a recebem com alegria. Uma vez, porém, que não têm raízes profundas, creem apenas por um tempo e depois desanimam quando enfrentam provações.

[[v42-8-14]]

^<<v42-8-14,14>>^ As que caíram entre os espinhos representam outros que ouvem a mensagem, mas logo ela é sufocada pelas preocupações, riquezas e prazeres desta vida, de modo que nunca amadurecem.

[[v42-8-15]]

^<<v42-8-15,15>>^ E as que caíram em solo fértil representam os que, com coração bom e receptivo, ouvem a mensagem, a aceitam e, com paciência, produzem uma grande colheita."

[[v42-8-16]]

^<<v42-8-16,16>>^ "Não faz sentido acender uma lâmpada e depois cobri-la com uma vasilha ou escondê-la debaixo da cama. Pelo contrário, ela é colocada num pedestal, de onde sua luz pode ser vista pelos que entram na casa.

[[v42-8-17]]

^<<v42-8-17,17>>^ Da mesma forma, tudo que está escondido será revelado, e tudo que está oculto virá à luz e será conhecido por todos.

[[v42-8-18]]

^<<v42-8-18,18>>^ "Portanto, ouçam com atenção! Pois ao que tem, mais lhe será dado, mas do que não tem, até o que pensa ter lhe será tomado".

[[v42-8-19]]

^<<v42-8-19,19>>^ Então a mãe e os irmãos de Jesus foram vê-lo, mas não conseguiram chegar até ele por causa da multidão.

[[v42-8-20]]

^<<v42-8-20,20>>^ Alguém disse a Jesus: "Sua mãe e seus irmãos estão lá fora e querem vê-lo".

[[v42-8-21]]

^<<v42-8-21,21>>^ Jesus respondeu: "Minha mãe e meus irmãos são aqueles que ouvem a palavra de Deus e a praticam".

[[v42-8-22]]

^<<v42-8-22,22>>^ Certo dia, Jesus disse a seus discípulos: "Vamos para o outro lado do mar". Assim, entraram num barco e partiram.

[[v42-8-23]]

^<<v42-8-23,23>>^ Durante a travessia, Jesus caiu no sono. Logo, porém, veio sobre o mar uma forte tempestade. O barco começou a se encher de água, colocando-os em grande perigo.

[[v42-8-24]]

^<<v42-8-24,24>>^ Os discípulos foram acordá-lo, clamando: "Mestre, Mestre, vamos morrer!". Quando Jesus despertou, repreendeu o vento e as ondas violentas. A tempestade parou, e tudo se acalmou.

[[v42-8-25]]

^<<v42-8-25,25>>^ Então ele lhes perguntou: "Onde está a sua fé?". Admirados e temerosos, os discípulos diziam entre si: "Quem é este homem? Quando ele ordena, até os ventos e o mar lhe obedecem!".

[[v42-8-26]]

^<<v42-8-26,26>>^ Então chegaram à região dos gadarenos, do outro lado do mar da Galileia.

[[v42-8-27]]

^<<v42-8-27,27>>^ Quando Jesus desembarcou, um homem possuído por demônios veio ao seu encontro. Fazia muito tempo que ele não tinha casa nem roupas e vivia num cemitério fora da cidade.

[[v42-8-28]]

^<<v42-8-28,28>>^ Assim que viu Jesus, gritou e caiu diante dele. Então disse em alta voz: "Por que vem me importunar, Jesus, Filho do Deus Altíssimo? Suplico que não me atormente!".

[[v42-8-29]]

^<<v42-8-29,29>>^ Pois Jesus já havia ordenado que o espírito impuro saísse dele. Esse espírito tinha dominado o homem em várias ocasiões. Mesmo quando era colocado sob guarda, com os pés e as mãos acorrentados, ele quebrava as correntes e, sob controle do demônio, corria para o deserto.

[[v42-8-30]]

^<<v42-8-30,30>>^ Jesus lhe perguntou: "Qual é o seu nome?". "Legião", respondeu ele, pois havia muitos demônios dentro do homem.

[[v42-8-31]]

^<<v42-8-31,31>>^ E imploravam que Jesus não os mandasse para o abismo.

[[v42-8-32]]

^<<v42-8-32,32>>^ Ali perto, uma grande manada de porcos pastava na encosta de uma colina, e os demônios suplicaram que ele os deixasse entrar nos porcos. Jesus lhes deu permissão.

[[v42-8-33]]

^<<v42-8-33,33>>^ Os demônios saíram do homem e entraram nos porcos, e toda a manada se atirou pela encosta íngreme para dentro do mar e se afogou.

[[v42-8-34]]

^<<v42-8-34,34>>^ Quando os que cuidavam dos porcos viram isso, fugiram para uma cidade próxima e para seus arredores, espalhando a notícia.

[[v42-8-35]]

^<<v42-8-35,35>>^ O povo correu para ver o que havia ocorrido. Uma multidão se juntou ao redor de Jesus, e eles viram o homem que havia sido liberto dos demônios. Estava sentado aos pés de Jesus, vestido e em perfeito juízo, e todos tiveram medo.

[[v42-8-36]]

^<<v42-8-36,36>>^ Os que presenciaram os acontecimentos contaram aos demais como o homem possuído por demônios tinha sido curado.

[[v42-8-37]]

^<<v42-8-37,37>>^ Todo o povo da região dos gadarenos suplicou que Jesus fosse embora, pois ficaram muito assustados. Então ele voltou ao barco e partiu.

[[v42-8-38]]

^<<v42-8-38,38>>^ O homem que tinha sido liberto dos demônios suplicou para ir com ele, mas Jesus o mandou para casa, dizendo:

[[v42-8-39]]

^<<v42-8-39,39>>^ "Volte para sua família e conte a eles tudo que Deus fez por você". E o homem foi pela cidade inteira, anunciando tudo que Jesus tinha feito por ele.

[[v42-8-40]]

^<<v42-8-40,40>>^ Do outro lado do mar, as multidões receberam Jesus com alegria, pois o estavam esperando.

[[v42-8-41]]

^<<v42-8-41,41>>^ Então um homem chamado Jairo, um dos líderes da sinagoga local, veio e se prostrou aos pés de Jesus, suplicando que ele fosse à sua casa.

[[v42-8-42]]

^<<v42-8-42,42>>^ Sua única filha, de cerca de doze anos, estava à beira da morte. Jesus o acompanhou, cercado pela multidão.

[[v42-8-43]]

^<<v42-8-43,43>>^ Uma mulher no meio do povo sofria havia doze anos de uma hemorragia, sem encontrar cura.

[[v42-8-44]]

^<<v42-8-44,44>>^ Ela se aproximou por trás de Jesus e tocou na borda de seu manto. No mesmo instante, a hemorragia parou.

[[v42-8-45]]

^<<v42-8-45,45>>^ "Quem tocou em mim?", perguntou Jesus. Todos negaram, e Pedro disse: "Mestre, a multidão toda se aperta em volta do senhor".

[[v42-8-46]]

^<<v42-8-46,46>>^ Jesus, no entanto, disse: "Alguém certamente tocou em mim, pois senti que de mim saiu poder".

[[v42-8-47]]

^<<v42-8-47,47>>^ Quando a mulher percebeu que não poderia permanecer despercebida, começou a tremer e caiu de joelhos diante dele. Todos a ouviram explicar por que havia tocado nele e como havia sido curada de imediato.

[[v42-8-48]]

^<<v42-8-48,48>>^ Então ele disse: "Filha, sua fé a curou. Vá em paz".

[[v42-8-49]]

^<<v42-8-49,49>>^ Enquanto Jesus ainda falava com a mulher, chegou um mensageiro da casa de Jairo, o líder da sinagoga, a quem disse: "Sua filha morreu. Não incomode mais o mestre".

[[v42-8-50]]

^<<v42-8-50,50>>^ Ao ouvir isso, Jesus disse a Jairo: "Não tenha medo. Apenas creia, e ela será curada".

[[v42-8-51]]

^<<v42-8-51,51>>^ Quando chegaram à casa de Jairo, Jesus não deixou que ninguém o acompanhasse, exceto Pedro, João, Tiago e o pai e a mãe da menina.

[[v42-8-52]]

^<<v42-8-52,52>>^ A casa estava cheia de gente chorando e se lamentando, mas ele disse: "Parem de chorar! Ela não está morta; está apenas dormindo".

[[v42-8-53]]

^<<v42-8-53,53>>^ A multidão riu dele, pois todos sabiam que ela havia morrido.

[[v42-8-54]]

^<<v42-8-54,54>>^ Então Jesus a tomou pela mão e disse em voz alta: "Menina, levante-se!".

[[v42-8-55]]

^<<v42-8-55,55>>^ Naquele momento, ela voltou à vida e levantou-se de imediato. Então Jesus ordenou que dessem alguma coisa para ela comer.

[[v42-8-56]]

^<<v42-8-56,56>>^ Os pais dela ficaram maravilhados, mas Jesus insistiu que não contassem a ninguém o que havia acontecido.

'''

xref:042-lucas/042-lucas-007.adoc#v42-7-0[&#60; Capítulo Anterior] | <<v42-8-0,Topo>> | xref:042-lucas/042-lucas-009.adoc#v42-9-0[Próximo Capítulo &#62;]