include::./index.adoc[]

[[v42-12-0]]
=== Lucas, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v42-12-1]]

^<<v42-12-1,1>>^ Quando as multidões cresceram a ponto de haver milhares de pessoas atropelando-se e pisando umas nas outras, Jesus concentrou seu ensino nos discípulos, dizendo: "Tenham cuidado com o fermento dos fariseus, que é a hipocrisia.

[[v42-12-2]]

^<<v42-12-2,2>>^ Virá o dia em que tudo que está encoberto será revelado, e tudo que é secreto será divulgado.

[[v42-12-3]]

^<<v42-12-3,3>>^ O que vocês disseram no escuro será ouvido às claras, e o que conversaram a portas fechadas será proclamado dos telhados.

[[v42-12-4]]

^<<v42-12-4,4>>^ "Meus amigos, não tenham medo daqueles que matam o corpo; depois disso, nada mais podem lhes fazer.

[[v42-12-5]]

^<<v42-12-5,5>>^ Mas eu lhes direi a quem devem temer. Temam a Deus, que tem o poder de matar e lançar no inferno. Sim, a esse vocês devem temer.

[[v42-12-6]]

^<<v42-12-6,6>>^ "Qual é o preço de cinco pardais? Duas moedas de cobre? E, no entanto, Deus não se esquece de nenhum deles.

[[v42-12-7]]

^<<v42-12-7,7>>^ Até os cabelos de sua cabeça estão todos contados. Portanto, não tenham medo; vocês são muito mais valiosos que um bando inteiro de pardais.

[[v42-12-8]]

^<<v42-12-8,8>>^ "Eu lhes digo a verdade: quem me reconhecer aqui, diante das pessoas, o Filho do Homem o reconhecerá na presença dos anjos de Deus.

[[v42-12-9]]

^<<v42-12-9,9>>^ Mas quem me negar aqui será negado diante dos anjos de Deus.

[[v42-12-10]]

^<<v42-12-10,10>>^ Quem falar contra o Filho do Homem será perdoado, mas quem blasfemar contra o Espírito Santo não será perdoado.

[[v42-12-11]]

^<<v42-12-11,11>>^ "Quando vocês forem julgados nas sinagogas e diante dos governantes e das autoridades, não se preocupem com o modo como se defenderão nem com o que dirão,

[[v42-12-12]]

^<<v42-12-12,12>>^ pois o Espírito Santo, naquele momento, lhes dará as palavras certas".

[[v42-12-13]]

^<<v42-12-13,13>>^ Então alguém da multidão gritou: "Mestre, por favor, diga a meu irmão que divida comigo a herança de meu pai!".

[[v42-12-14]]

^<<v42-12-14,14>>^ Jesus respondeu: "Amigo, quem me pôs como juiz sobre vocês para decidir essas coisas?".

[[v42-12-15]]

^<<v42-12-15,15>>^ Em seguida, disse: "Cuidado! Guardem-se de todo tipo de ganância. A vida de uma pessoa não é definida pela quantidade de seus bens".

[[v42-12-16]]

^<<v42-12-16,16>>^ Então lhes contou uma parábola: "Um homem rico tinha uma propriedade fértil que produziu boas colheitas.

[[v42-12-17]]

^<<v42-12-17,17>>^ Pensou consigo: ‘O que devo fazer? Não tenho espaço para toda a minha colheita’.

[[v42-12-18]]

^<<v42-12-18,18>>^ Por fim, disse: ‘Já sei! Vou derrubar os celeiros e construir outros maiores. Assim terei espaço suficiente para todo o meu trigo e meus outros bens.

[[v42-12-19]]

^<<v42-12-19,19>>^ Então direi a mim mesmo: Amigo, você guardou o suficiente para muitos anos. Agora descanse! Coma, beba e alegre-se!’.

[[v42-12-20]]

^<<v42-12-20,20>>^ "Mas Deus lhe disse: ‘Louco! Você morrerá esta noite. E, então, quem ficará com o fruto do seu trabalho?’.

[[v42-12-21]]

^<<v42-12-21,21>>^ "Sim, é loucura acumular riquezas terrenas e não ser rico para com Deus".

[[v42-12-22]]

^<<v42-12-22,22>>^ Então, voltando-se para seus discípulos, Jesus disse: "Por isso eu lhes digo que não se preocupem com a vida diária, se terão o suficiente para comer, ou com o corpo, se terão o suficiente para vestir.

[[v42-12-23]]

^<<v42-12-23,23>>^ Pois a vida é mais que comida, e o corpo é mais que roupa.

[[v42-12-24]]

^<<v42-12-24,24>>^ Observem os corvos. Eles não plantam nem colhem, nem guardam comida em celeiros, pois Deus os alimenta. E vocês valem muito mais que qualquer pássaro.

[[v42-12-25]]

^<<v42-12-25,25>>^ Qual de vocês, por mais preocupado que esteja, pode acrescentar ao menos uma hora à sua vida?

[[v42-12-26]]

^<<v42-12-26,26>>^ E, se não podem fazer uma coisa tão pequena, de que adianta se preocupar com as maiores?

[[v42-12-27]]

^<<v42-12-27,27>>^ "Observem como crescem os lírios. Não trabalham nem fazem suas roupas e, no entanto, nem Salomão em toda a sua glória se vestiu como eles.

[[v42-12-28]]

^<<v42-12-28,28>>^ E, se Deus veste com tamanha beleza as flores que hoje estão aqui e amanhã são lançadas ao fogo, não será muito mais generoso com vocês, gente de pequena fé?

[[v42-12-29]]

^<<v42-12-29,29>>^ "Não se inquietem com o que comer e o que beber. Não se preocupem com essas coisas.

[[v42-12-30]]

^<<v42-12-30,30>>^ Elas ocupam os pensamentos dos pagãos de todo o mundo, mas seu Pai já sabe do que vocês precisam.

[[v42-12-31]]

^<<v42-12-31,31>>^ Busquem, acima de tudo, o reino de Deus, e todas essas coisas lhes serão dadas.

[[v42-12-32]]

^<<v42-12-32,32>>^ "Não tenham medo, pequeno rebanho, pois seu Pai tem grande alegria em lhes dar o reino.

[[v42-12-33]]

^<<v42-12-33,33>>^ "Vendam seus bens e deem aos necessitados. Com isso, ajuntarão tesouros no céu, e as bolsas no céu não se desgastam nem se desfazem. Seu tesouro estará seguro; nenhum ladrão o roubará e nenhuma traça o destruirá.

[[v42-12-34]]

^<<v42-12-34,34>>^ Onde seu tesouro estiver, ali também estará seu coração."

[[v42-12-35]]

^<<v42-12-35,35>>^ "Estejam vestidos, prontos para servir, e mantenham suas lâmpadas acesas,

[[v42-12-36]]

^<<v42-12-36,36>>^ como se esperassem o seu senhor voltar do banquete de casamento. Então poderão abrir-lhe a porta e deixá-lo entrar no momento em que ele chegar e bater.

[[v42-12-37]]

^<<v42-12-37,37>>^ Os servos que estiverem prontos, aguardando seu retorno, serão recompensados. Eu lhes digo a verdade: ele mesmo se vestirá como servo, indicará onde vocês se sentarão e os servirá enquanto estão à mesa!

[[v42-12-38]]

^<<v42-12-38,38>>^ Quer ele venha no meio da noite, quer de madrugada, ele recompensará os servos que estiverem prontos.

[[v42-12-39]]

^<<v42-12-39,39>>^ "Entendam isto: se o dono da casa soubesse exatamente a que horas o ladrão viria, não permitiria que a casa fosse arrombada.

[[v42-12-40]]

^<<v42-12-40,40>>^ Estejam também sempre preparados, pois o Filho do Homem virá quando menos esperam".

[[v42-12-41]]

^<<v42-12-41,41>>^ Então Pedro perguntou: "Senhor, essa ilustração se aplica apenas a nós, ou a todos?".

[[v42-12-42]]

^<<v42-12-42,42>>^ O Senhor respondeu: "O servo fiel e sensato é aquele a quem o senhor encarrega de chefiar os demais servos da casa e alimentá-los.

[[v42-12-43]]

^<<v42-12-43,43>>^ Se o senhor voltar e constatar que seu servo fez um bom trabalho,

[[v42-12-44]]

^<<v42-12-44,44>>^ eu lhes digo a verdade: ele colocará todos os seus bens sob os cuidados desse servo.

[[v42-12-45]]

^<<v42-12-45,45>>^ O que acontecerá, porém, se o servo pensar: ‘Meu senhor não voltará tão cedo’, e começar a espancar os outros servos, a comer e a beber e se embriagar?

[[v42-12-46]]

^<<v42-12-46,46>>^ O senhor desse servo voltará em dia em que não se espera e em hora que não se conhece, cortará o servo ao meio e lhe dará o mesmo destino dos incrédulos.

[[v42-12-47]]

^<<v42-12-47,47>>^ "O servo que conhece a vontade do seu senhor e não se prepara nem segue as instruções dele será duramente castigado.

[[v42-12-48]]

^<<v42-12-48,48>>^ Mas aquele que não a conhece e faz algo errado será castigado com menos severidade. A quem muito foi dado, muito será pedido; e a quem muito foi confiado, ainda mais será exigido."

[[v42-12-49]]

^<<v42-12-49,49>>^ "Eu vim para incendiar a terra, e gostaria que já estivesse em chamas!

[[v42-12-50]]

^<<v42-12-50,50>>^ No entanto, tenho de passar por um batismo e estou angustiado até que ele se realize.

[[v42-12-51]]

^<<v42-12-51,51>>^ Vocês pensam que vim trazer paz à terra? Não! Eu vim causar divisão!

[[v42-12-52]]

^<<v42-12-52,52>>^ De agora em diante, numa mesma casa cinco pessoas estarão divididas: três contra duas e duas contra três.

[[v42-12-53]]

^<<v42-12-53,53>>^ "O pai ficará contra o filho e o filho contra o pai; a mãe contra a filha e a filha contra a mãe; a sogra contra a nora e a nora contra a sogra".

[[v42-12-54]]

^<<v42-12-54,54>>^ Então Jesus se voltou para a multidão e disse: "Quando vocês veem nuvens se formando no oeste, dizem: ‘Vai chover’. E têm razão.

[[v42-12-55]]

^<<v42-12-55,55>>^ Quando sopra o vento sul, dizem: ‘Hoje vai fazer calor’. E assim ocorre.

[[v42-12-56]]

^<<v42-12-56,56>>^ Hipócritas! Sabem interpretar as condições do tempo na terra e no céu, mas não sabem interpretar o tempo presente.

[[v42-12-57]]

^<<v42-12-57,57>>^ "Por que não decidem por si mesmos o que é certo?

[[v42-12-58]]

^<<v42-12-58,58>>^ Quando você e seu adversário estiverem a caminho do tribunal, procurem acertar as diferenças antes de chegar lá. Do contrário, pode ser que o acusador o entregue ao juiz, e o juiz, a um oficial que o lançará na prisão.

[[v42-12-59]]

^<<v42-12-59,59>>^ Eu lhe digo: você não será solto enquanto não tiver pago até o último centavo".

'''

xref:042-lucas/042-lucas-011.adoc#v42-11-0[&#60; Capítulo Anterior] | <<v42-12-0,Topo>> | xref:042-lucas/042-lucas-013.adoc#v42-13-0[Próximo Capítulo &#62;]