include::./index.adoc[]

[[v42-1-0]]
=== Lucas, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v42-1-1]]

^<<v42-1-1,1>>^ Muitos se propuseram a escrever uma narração dos acontecimentos que se cumpriram entre nós.

[[v42-1-2]]

^<<v42-1-2,2>>^ Usaram os relatos que nos foram transmitidos por aqueles que, desde o princípio, foram testemunhas oculares e servos da palavra.

[[v42-1-3]]

^<<v42-1-3,3>>^ Depois de investigar tudo detalhadamente desde o início, também decidi escrever-lhe um relato preciso, excelentíssimo Teófilo,

[[v42-1-4]]

^<<v42-1-4,4>>^ para que tenha plena certeza de tudo que lhe foi ensinado.

[[v42-1-5]]

^<<v42-1-5,5>>^ Quando Herodes era rei da Judeia, havia um sacerdote chamado Zacarias, que fazia parte do grupo sacerdotal de Abias. Sua esposa, Isabel, também pertencia à linhagem sacerdotal de Arão.

[[v42-1-6]]

^<<v42-1-6,6>>^ Zacarias e Isabel eram justos aos olhos de Deus e obedeciam cuidadosamente a todos os mandamentos e estatutos do Senhor.

[[v42-1-7]]

^<<v42-1-7,7>>^ Não tinham filhos, pois Isabel era estéril, e ambos já estavam bem velhos.

[[v42-1-8]]

^<<v42-1-8,8>>^ Certo dia, Zacarias estava servindo diante de Deus no templo, pois seu grupo realizava o trabalho sacerdotal, conforme a escala.

[[v42-1-9]]

^<<v42-1-9,9>>^ Foi escolhido por sorteio, como era costume dos sacerdotes, para entrar no santuário do Senhor e queimar incenso.

[[v42-1-10]]

^<<v42-1-10,10>>^ Enquanto o incenso era queimado, uma grande multidão orava do lado de fora.

[[v42-1-11]]

^<<v42-1-11,11>>^ Então um anjo do Senhor lhe apareceu, à direita do altar de incenso.

[[v42-1-12]]

^<<v42-1-12,12>>^ Ao vê-lo, Zacarias ficou muito abalado e assustado.

[[v42-1-13]]

^<<v42-1-13,13>>^ O anjo, porém, lhe disse: "Não tenha medo, Zacarias! Sua oração foi ouvida. Isabel, sua esposa, lhe dará um filho, e você o chamará João.

[[v42-1-14]]

^<<v42-1-14,14>>^ Você terá grande satisfação e alegria, e muitos se alegrarão com o nascimento do menino,

[[v42-1-15]]

^<<v42-1-15,15>>^ pois ele será grande aos olhos do Senhor. Nunca tomará vinho nem outra bebida forte. Será cheio do Espírito Santo, antes mesmo de nascer.

[[v42-1-16]]

^<<v42-1-16,16>>^ Fará muitos israelitas voltarem ao Senhor, seu Deus.

[[v42-1-17]]

^<<v42-1-17,17>>^ Será um homem com o espírito e o poder de Elias, e preparará o povo para a vinda do Senhor. Fará o coração dos pais voltar para seus filhos e levará os rebeldes a aceitarem a sabedoria dos justos".

[[v42-1-18]]

^<<v42-1-18,18>>^ Zacarias disse ao anjo: "Como posso ter certeza de que isso acontecerá? Já sou velho, e minha mulher também é de idade avançada".

[[v42-1-19]]

^<<v42-1-19,19>>^ O anjo respondeu: "Sou Gabriel, e estou sempre na presença de Deus. Foi ele quem me enviou para lhe trazer estas boas-novas.

[[v42-1-20]]

^<<v42-1-20,20>>^ Agora, porém, você ficará mudo até os dias em que essas coisas acontecerão, pois não acreditou em minhas palavras, que se cumprirão no devido tempo".

[[v42-1-21]]

^<<v42-1-21,21>>^ Enquanto isso, o povo esperava Zacarias sair do santuário e se perguntava por que ele demorava tanto.

[[v42-1-22]]

^<<v42-1-22,22>>^ Quando finalmente saiu, não conseguia falar com eles, e perceberam por seus gestos e seu silêncio que ele havia tido uma visão no santuário.

[[v42-1-23]]

^<<v42-1-23,23>>^ Ao fim de seus dias de serviço no templo, Zacarias voltou para casa.

[[v42-1-24]]

^<<v42-1-24,24>>^ Pouco tempo depois, sua esposa, Isabel, engravidou e não saiu de casa por cinco meses.

[[v42-1-25]]

^<<v42-1-25,25>>^ "Como o Senhor foi bom para mim em minha velhice!", exclamou ela. "Tirou de mim a humilhação pública de não ter filhos!"

[[v42-1-26]]

^<<v42-1-26,26>>^ No sexto mês da gestação de Isabel, Deus enviou o anjo Gabriel a Nazaré, uma cidade da Galileia,

[[v42-1-27]]

^<<v42-1-27,27>>^ a uma virgem de nome Maria. Ela estava prometida em casamento a um homem chamado José, descendente do rei Davi.

[[v42-1-28]]

^<<v42-1-28,28>>^ Gabriel apareceu a ela e lhe disse: "Alegre-se, mulher favorecida! O Senhor está com você!".

[[v42-1-29]]

^<<v42-1-29,29>>^ Confusa, Maria tentou imaginar o que o anjo quis dizer.

[[v42-1-30]]

^<<v42-1-30,30>>^ "Não tenha medo, Maria", disse o anjo, "pois você encontrou favor diante de Deus.

[[v42-1-31]]

^<<v42-1-31,31>>^ Ficará grávida e dará à luz um filho, e o chamará Jesus.

[[v42-1-32]]

^<<v42-1-32,32>>^ Ele será grande, e será chamado Filho do Altíssimo. O Senhor Deus lhe dará o trono de seu antepassado Davi,

[[v42-1-33]]

^<<v42-1-33,33>>^ e ele reinará sobre Israel para sempre; seu reino jamais terá fim!"

[[v42-1-34]]

^<<v42-1-34,34>>^ Maria perguntou ao anjo: "Como isso acontecerá? Eu sou virgem!".

[[v42-1-35]]

^<<v42-1-35,35>>^ O anjo respondeu: "O Espírito Santo virá sobre você, e o poder do Altíssimo a cobrirá com sua sombra. Portanto, o bebê que vai nascer será santo, e será chamado Filho de Deus.

[[v42-1-36]]

^<<v42-1-36,36>>^ Além disso, sua parenta, Isabel, ficou grávida em idade avançada. As pessoas diziam que ela era estéril, mas ela concebeu um filho e está no sexto mês de gestação.

[[v42-1-37]]

^<<v42-1-37,37>>^ Pois nada é impossível para Deus".

[[v42-1-38]]

^<<v42-1-38,38>>^ Maria disse: "Sou serva do Senhor. Que aconteça comigo tudo que foi dito a meu respeito". E o anjo a deixou.

[[v42-1-39]]

^<<v42-1-39,39>>^ Alguns dias depois, Maria dirigiu-se apressadamente à região montanhosa da Judeia, à cidade

[[v42-1-40]]

^<<v42-1-40,40>>^ onde Zacarias morava. Ela entrou na casa e saudou Isabel.

[[v42-1-41]]

^<<v42-1-41,41>>^ Ao ouvir a saudação de Maria, o bebê de Isabel se agitou dentro dela, e Isabel ficou cheia do Espírito Santo.

[[v42-1-42]]

^<<v42-1-42,42>>^ Em alta voz, Isabel exclamou: "Você é abençoada entre as mulheres, e abençoada é a criança em seu ventre!

[[v42-1-43]]

^<<v42-1-43,43>>^ Por que tenho a grande honra de receber a visita da mãe do meu Senhor?

[[v42-1-44]]

^<<v42-1-44,44>>^ Quando ouvi sua saudação, o bebê em meu ventre se agitou de alegria.

[[v42-1-45]]

^<<v42-1-45,45>>^ Você é abençoada, pois creu no que o Senhor disse que faria!".

[[v42-1-46]]

^<<v42-1-46,46>>^ Maria respondeu: "Minha alma exalta ao Senhor!

[[v42-1-47]]

^<<v42-1-47,47>>^ Como meu espírito se alegra em Deus, meu Salvador!

[[v42-1-48]]

^<<v42-1-48,48>>^ Pois ele observou sua humilde serva, e, de agora em diante, todas as gerações me chamarão abençoada.

[[v42-1-49]]

^<<v42-1-49,49>>^ Pois o Poderoso é santo, e fez grandes coisas por mim.

[[v42-1-50]]

^<<v42-1-50,50>>^ Demonstra misericórdia a todos que o temem, geração após geração.

[[v42-1-51]]

^<<v42-1-51,51>>^ Seu braço poderoso fez coisas tremendas! Dispersou os orgulhosos e os arrogantes.

[[v42-1-52]]

^<<v42-1-52,52>>^ Derrubou príncipes de seus tronos e exaltou os humildes.

[[v42-1-53]]

^<<v42-1-53,53>>^ Encheu de coisas boas os famintos e despediu de mãos vazias os ricos.

[[v42-1-54]]

^<<v42-1-54,54>>^ Ajudou seu servo Israel e lembrou-se de ser misericordioso.

[[v42-1-55]]

^<<v42-1-55,55>>^ Pois assim prometeu a nossos antepassados, a Abraão e a seus descendentes para sempre".

[[v42-1-56]]

^<<v42-1-56,56>>^ Maria ficou com Isabel cerca de três meses, e então voltou para casa.

[[v42-1-57]]

^<<v42-1-57,57>>^ Chegado o tempo de seu bebê nascer, Isabel deu à luz um filho.

[[v42-1-58]]

^<<v42-1-58,58>>^ Vizinhos e parentes se alegraram ao tomar conhecimento de que o Senhor havia sido tão misericordioso com ela.

[[v42-1-59]]

^<<v42-1-59,59>>^ Quando o bebê estava com oito dias, eles vieram para a cerimônia de circuncisão. Queriam chamar o menino de Zacarias, como o pai,

[[v42-1-60]]

^<<v42-1-60,60>>^ mas Isabel disse: "Não! Seu nome é João!".

[[v42-1-61]]

^<<v42-1-61,61>>^ Então eles lhe disseram: "Não há ninguém em sua família com esse nome",

[[v42-1-62]]

^<<v42-1-62,62>>^ e com gestos perguntaram ao pai como queria chamar o bebê.

[[v42-1-63]]

^<<v42-1-63,63>>^ Ele pediu que lhe dessem uma tabuinha e, para surpresa de todos, escreveu: "Seu nome é João".

[[v42-1-64]]

^<<v42-1-64,64>>^ No mesmo instante, Zacarias voltou a falar e começou a louvar a Deus.

[[v42-1-65]]

^<<v42-1-65,65>>^ Toda a vizinhança se encheu de temor, e a notícia do que havia acontecido se espalhou por toda a região montanhosa da Judeia.

[[v42-1-66]]

^<<v42-1-66,66>>^ Todos que ficavam sabendo meditavam sobre esses acontecimentos e perguntavam: "O que vai ser esse menino?". Pois a mão do Senhor estava sobre ele.

[[v42-1-67]]

^<<v42-1-67,67>>^ Então seu pai, Zacarias, ficou cheio do Espírito Santo e profetizou:

[[v42-1-68]]

^<<v42-1-68,68>>^ "Seja bendito o Senhor, o Deus de Israel, pois visitou e resgatou seu povo.

[[v42-1-69]]

^<<v42-1-69,69>>^ Ele nos enviou poderosa salvação da linhagem real de seu servo Davi,

[[v42-1-70]]

^<<v42-1-70,70>>^ como havia prometido muito tempo atrás por meio de seus santos profetas.

[[v42-1-71]]

^<<v42-1-71,71>>^ Agora seremos salvos de nossos inimigos e de todos que nos odeiam.

[[v42-1-72]]

^<<v42-1-72,72>>^ Ele foi misericordioso com nossos antepassados ao lembrar-se de sua santa aliança,

[[v42-1-73]]

^<<v42-1-73,73>>^ o juramento solene que fez com nosso antepassado Abraão.

[[v42-1-74]]

^<<v42-1-74,74>>^ Prometeu livrar-nos de nossos inimigos para o servirmos sem medo,

[[v42-1-75]]

^<<v42-1-75,75>>^ em santidade e justiça, enquanto vivermos.

[[v42-1-76]]

^<<v42-1-76,76>>^ "E você, meu filhinho, será chamado profeta do Altíssimo, pois preparará o caminho para o Senhor.

[[v42-1-77]]

^<<v42-1-77,77>>^ Dirá a seu povo como encontrar salvação por meio do perdão de seus pecados.

[[v42-1-78]]

^<<v42-1-78,78>>^ Graças à terna misericórdia de nosso Deus, a luz da manhã, vinda do céu, está prestes a raiar sobre nós,

[[v42-1-79]]

^<<v42-1-79,79>>^ para iluminar aqueles que estão na escuridão e na sombra da morte e nos guiar ao caminho da paz".

[[v42-1-80]]

^<<v42-1-80,80>>^ João cresceu e se fortaleceu em espírito. E viveu no deserto até chegar o tempo de se apresentar ao povo de Israel.

'''

xref:041-marcos/041-marcos-016.adoc#v41-16-0[&#60; Capítulo Anterior] | <<v42-1-0,Topo>> | xref:042-lucas/042-lucas-002.adoc#v42-2-0[Próximo Capítulo &#62;]