include::./index.adoc[]

[[v42-15-0]]
=== Lucas, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v42-15-1]]

^<<v42-15-1,1>>^ Cobradores de impostos e outros pecadores vinham ouvir Jesus ensinar.

[[v42-15-2]]

^<<v42-15-2,2>>^ Os fariseus e mestres da lei o criticavam, dizendo: "Ele se reúne com pecadores e até come com eles!".

[[v42-15-3]]

^<<v42-15-3,3>>^ Então Jesus lhes contou esta parábola:

[[v42-15-4]]

^<<v42-15-4,4>>^ "Se um homem tiver cem ovelhas e uma delas se perder, o que acham que ele fará? Não deixará as outras noventa e nove no pasto e buscará a perdida até encontrá-la?

[[v42-15-5]]

^<<v42-15-5,5>>^ E, quando a encontrar, ele a carregará alegremente nos ombros e a levará para casa.

[[v42-15-6]]

^<<v42-15-6,6>>^ Quando chegar, reunirá os amigos e vizinhos e dirá: ‘Alegrem-se comigo, pois encontrei minha ovelha perdida!’.

[[v42-15-7]]

^<<v42-15-7,7>>^ Da mesma forma, há mais alegria no céu por causa do pecador perdido que se arrepende do que por noventa e nove justos que não precisam se arrepender."

[[v42-15-8]]

^<<v42-15-8,8>>^ "Ou suponhamos que uma mulher tenha dez moedas de prata e perca uma. Acaso não acenderá uma lâmpada, varrerá a casa inteira e procurará com cuidado até encontrá-la?

[[v42-15-9]]

^<<v42-15-9,9>>^ E, quando a encontrar, reunirá as amigas e vizinhas e dirá: ‘Alegrem-se comigo, pois encontrei a minha moeda perdida!’.

[[v42-15-10]]

^<<v42-15-10,10>>^ Da mesma forma, há alegria na presença dos anjos de Deus quando um único pecador se arrepende".

[[v42-15-11]]

^<<v42-15-11,11>>^ Jesus continuou: "Um homem tinha dois filhos.

[[v42-15-12]]

^<<v42-15-12,12>>^ O filho mais jovem disse ao pai: ‘Quero a minha parte da herança’, e o pai dividiu seus bens entre os filhos.

[[v42-15-13]]

^<<v42-15-13,13>>^ "Alguns dias depois, o filho mais jovem arrumou suas coisas e se mudou para uma terra distante, onde desperdiçou tudo que tinha por viver de forma desregrada.

[[v42-15-14]]

^<<v42-15-14,14>>^ Quando seu dinheiro acabou, uma grande fome se espalhou pela terra, e ele começou a passar necessidade.

[[v42-15-15]]

^<<v42-15-15,15>>^ Convenceu um fazendeiro da região a empregá-lo, e esse homem o mandou a seus campos para cuidar dos porcos.

[[v42-15-16]]

^<<v42-15-16,16>>^ Embora quisesse saciar a fome com as vagens dadas aos porcos, ninguém lhe dava coisa alguma.

[[v42-15-17]]

^<<v42-15-17,17>>^ "Quando finalmente caiu em si, disse: ‘Até os empregados de meu pai têm comida de sobra, e eu estou aqui, morrendo de fome.

[[v42-15-18]]

^<<v42-15-18,18>>^ Vou retornar à casa de meu pai e dizer: Pai, pequei contra o céu e contra o senhor,

[[v42-15-19]]

^<<v42-15-19,19>>^ e não sou mais digno de ser chamado seu filho. Por favor, trate-me como seu empregado’.

[[v42-15-20]]

^<<v42-15-20,20>>^ "Então voltou para a casa de seu pai. Quando ele ainda estava longe, seu pai o viu. Cheio de compaixão, correu para o filho, o abraçou e o beijou.

[[v42-15-21]]

^<<v42-15-21,21>>^ O filho disse: ‘Pai, pequei contra o céu e contra o senhor, e não sou mais digno de ser chamado seu filho’.

[[v42-15-22]]

^<<v42-15-22,22>>^ "O pai, no entanto, disse aos servos: ‘Depressa! Tragam a melhor roupa da casa e vistam nele. Coloquem-lhe um anel no dedo e sandálias nos pés.

[[v42-15-23]]

^<<v42-15-23,23>>^ Matem o novilho gordo. Faremos um banquete e celebraremos,

[[v42-15-24]]

^<<v42-15-24,24>>^ pois este meu filho estava morto e voltou à vida. Estava perdido e foi achado!’. E começaram a festejar.

[[v42-15-25]]

^<<v42-15-25,25>>^ "Enquanto isso, o filho mais velho trabalhava no campo. Na volta para casa, ouviu música e dança,

[[v42-15-26]]

^<<v42-15-26,26>>^ e perguntou a um dos servos o que estava acontecendo.

[[v42-15-27]]

^<<v42-15-27,27>>^ O servo respondeu: ‘Seu irmão voltou, e seu pai matou o novilho gordo, pois ele voltou são e salvo!’.

[[v42-15-28]]

^<<v42-15-28,28>>^ "O irmão mais velho se irou e não quis entrar. O pai saiu e insistiu com o filho,

[[v42-15-29]]

^<<v42-15-29,29>>^ mas ele respondeu: ‘Todos esses anos, tenho trabalhado como um escravo para o senhor e nunca me recusei a obedecer às suas ordens. E o senhor nunca me deu nem mesmo um cabrito para eu festejar com meus amigos.

[[v42-15-30]]

^<<v42-15-30,30>>^ Mas, quando esse seu filho volta, depois de desperdiçar o seu dinheiro com prostitutas, o senhor comemora matando o novilho!’.

[[v42-15-31]]

^<<v42-15-31,31>>^ "O pai lhe respondeu: ‘Meu filho, você está sempre comigo, e tudo que eu tenho é seu.

[[v42-15-32]]

^<<v42-15-32,32>>^ Mas tínhamos de comemorar este dia feliz, pois seu irmão estava morto e voltou à vida. Estava perdido e foi achado!’".

'''

xref:042-lucas/042-lucas-014.adoc#v42-14-0[&#60; Capítulo Anterior] | <<v42-15-0,Topo>> | xref:042-lucas/042-lucas-016.adoc#v42-16-0[Próximo Capítulo &#62;]