include::./index.adoc[]

[[v42-6-0]]
=== Lucas, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v42-6-1]]

^<<v42-6-1,1>>^ Num sábado, enquanto Jesus caminhava pelos campos de cereal, seus discípulos colheram espigas, removeram a casca com as mãos e comeram os grãos.

[[v42-6-2]]

^<<v42-6-2,2>>^ Alguns fariseus lhes disseram: "Por que vocês desobedecem à lei colhendo cereal no sábado?".

[[v42-6-3]]

^<<v42-6-3,3>>^ Jesus respondeu: "Vocês não leram nas Escrituras o que fez Davi quando ele e seus companheiros tiveram fome?

[[v42-6-4]]

^<<v42-6-4,4>>^ Ele entrou na casa de Deus, comeu os pães sagrados que só os sacerdotes tinham permissão de comer e os deu também a seus companheiros".

[[v42-6-5]]

^<<v42-6-5,5>>^ E acrescentou: "O Filho do Homem é senhor até mesmo do sábado".

[[v42-6-6]]

^<<v42-6-6,6>>^ Em outro sábado, enquanto Jesus ensinava na sinagoga, estava ali um homem cuja mão direita era deformada.

[[v42-6-7]]

^<<v42-6-7,7>>^ Os mestres da lei e os fariseus observavam Jesus atentamente. Se ele curasse aquele homem, eles o acusariam, pois era sábado.

[[v42-6-8]]

^<<v42-6-8,8>>^ Jesus, porém, sabia o que planejavam e disse ao homem com a mão deformada: "Venha e fique aqui, diante de todos", e o homem foi à frente.

[[v42-6-9]]

^<<v42-6-9,9>>^ Então Jesus lhes disse: "Tenho uma pergunta para vocês: O que a lei permite fazer no sábado? O bem ou o mal? Salvar uma vida ou destruí-la?".

[[v42-6-10]]

^<<v42-6-10,10>>^ Depois, olhando para cada um ao redor, disse ao homem: "Estenda a mão". O homem estendeu a mão, e ela foi restaurada.

[[v42-6-11]]

^<<v42-6-11,11>>^ Com isso, os inimigos de Jesus ficaram furiosos e começaram a discutir o que fazer contra ele.

[[v42-6-12]]

^<<v42-6-12,12>>^ Certo dia, pouco depois, Jesus subiu a um monte para orar e passou a noite orando a Deus.

[[v42-6-13]]

^<<v42-6-13,13>>^ Quando amanheceu, reuniu seus discípulos e escolheu doze para serem apóstolos. Estes são seus nomes:

[[v42-6-14]]

^<<v42-6-14,14>>^ Simão, a quem ele chamou Pedro, André, irmão de Pedro, Tiago, João, Filipe, Bartolomeu,

[[v42-6-15]]

^<<v42-6-15,15>>^ Mateus, Tomé, Tiago, filho de Alfeu, Simão, apelidado de zelote,

[[v42-6-16]]

^<<v42-6-16,16>>^ Judas, filho de Tiago, Judas Iscariotes, que se tornou o traidor.

[[v42-6-17]]

^<<v42-6-17,17>>^ Quando Jesus e os discípulos desceram do monte, pararam numa região plana e ampla. Havia ali muitos de seus seguidores e uma grande multidão vinda de todas as partes da Judeia, de Jerusalém e de lugares distantes ao norte, como o litoral de Tiro e Sidom.

[[v42-6-18]]

^<<v42-6-18,18>>^ Tinham vindo para ouvi-lo e para ser curados de suas enfermidades, e os que eram atormentados por espíritos impuros eram curados.

[[v42-6-19]]

^<<v42-6-19,19>>^ Todos procuravam tocar em Jesus, pois dele saía poder, e ele curava a todos.

[[v42-6-20]]

^<<v42-6-20,20>>^ Então Jesus se voltou para seus discípulos e disse: "Felizes são vocês, pobres, pois o reino de Deus lhes pertence.

[[v42-6-21]]

^<<v42-6-21,21>>^ Felizes são vocês que agora estão famintos, pois serão saciados. Felizes são vocês que agora choram, pois no devido tempo rirão.

[[v42-6-22]]

^<<v42-6-22,22>>^ Felizes são vocês quando os odiarem e os excluírem, quando zombarem de vocês e os caluniarem como se fossem maus porque seguem o Filho do Homem.

[[v42-6-23]]

^<<v42-6-23,23>>^ Quando isso acontecer, alegrem-se e exultem, porque uma grande recompensa os espera no céu. E lembrem-se de que os antepassados deles trataram os profetas da mesma forma.

[[v42-6-24]]

^<<v42-6-24,24>>^ "Que aflição espera vocês, ricos, pois já receberam sua consolação!

[[v42-6-25]]

^<<v42-6-25,25>>^ Que aflição espera vocês que agora têm fartura, pois um terrível tempo de fome os espera! Que aflição espera vocês que agora riem, pois em breve seu riso se transformará em lamento e tristeza!

[[v42-6-26]]

^<<v42-6-26,26>>^ Que aflição espera vocês que são elogiados por todos, pois os antepassados deles também elogiaram falsos profetas!"

[[v42-6-27]]

^<<v42-6-27,27>>^ "Mas a vocês que me ouvem, eu digo: amem os seus inimigos, façam o bem a quem os odeia,

[[v42-6-28]]

^<<v42-6-28,28>>^ abençoem quem os amaldiçoa, orem por quem os maltratam.

[[v42-6-29]]

^<<v42-6-29,29>>^ Se alguém lhe der um tapa numa face, ofereça também a outra. Se alguém exigir de você a roupa do corpo, deixe que leve também a capa.

[[v42-6-30]]

^<<v42-6-30,30>>^ Dê a quem pedir e, quando tomarem suas coisas, não tente recuperá-las.

[[v42-6-31]]

^<<v42-6-31,31>>^ Façam aos outros o que vocês desejam que eles lhes façam.

[[v42-6-32]]

^<<v42-6-32,32>>^ "Se vocês amam apenas aqueles que os amam, que mérito têm? Até os pecadores amam quem os ama.

[[v42-6-33]]

^<<v42-6-33,33>>^ E, se fazem o bem apenas aos que fazem o bem a vocês, que mérito têm? Até os pecadores agem desse modo.

[[v42-6-34]]

^<<v42-6-34,34>>^ E, se emprestam dinheiro apenas aos que podem devolver, que mérito têm? Até os pecadores emprestam a outros pecadores, na expectativa de receber tudo de volta.

[[v42-6-35]]

^<<v42-6-35,35>>^ "Portanto, amem os seus inimigos, façam-lhes o bem e emprestem a eles sem esperar nada de volta. Então a recompensa que receberão do céu será grande e estarão agindo, de fato, como filhos do Altíssimo, pois ele é bondoso até mesmo com os ingratos e perversos.

[[v42-6-36]]

^<<v42-6-36,36>>^ Sejam misericordiosos, assim como seu Pai é misericordioso."

[[v42-6-37]]

^<<v42-6-37,37>>^ "Não julguem e não serão julgados. Não condenem e não serão condenados. Perdoem e serão perdoados.

[[v42-6-38]]

^<<v42-6-38,38>>^ Deem e receberão. Sua dádiva lhes retornará em boa medida, compactada, sacudida para caber mais, transbordante e derramada sobre vocês. O padrão de medida que adotarem será usado para medi-los".

[[v42-6-39]]

^<<v42-6-39,39>>^ Jesus deu ainda a seguinte ilustração: "É possível um cego guiar outro cego? Não cairão os dois num buraco?

[[v42-6-40]]

^<<v42-6-40,40>>^ Os discípulos não são maiores que seu mestre. Mas o aluno bem instruído será como o mestre.

[[v42-6-41]]

^<<v42-6-41,41>>^ "Por que você se preocupa com o cisco no olho de seu amigo enquanto há um tronco em seu próprio olho?

[[v42-6-42]]

^<<v42-6-42,42>>^ Como pode dizer: ‘Amigo, deixe-me ajudá-lo a tirar o cisco de seu olho’, se não consegue ver o tronco em seu próprio olho? Hipócrita! Primeiro, livre-se do tronco em seu olho; então você verá o suficiente para tirar o cisco do olho de seu amigo."

[[v42-6-43]]

^<<v42-6-43,43>>^ "Uma árvore boa não produz frutos ruins, e uma árvore ruim não produz frutos bons.

[[v42-6-44]]

^<<v42-6-44,44>>^ Uma árvore é identificada por seus frutos. Ninguém colhe figos de espinheiros, nem uvas de arbustos espinhosos.

[[v42-6-45]]

^<<v42-6-45,45>>^ A pessoa boa tira coisas boas do tesouro de um coração bom, e a pessoa má tira coisas más do tesouro de um coração mau. Pois a boca fala do que o coração está cheio."

[[v42-6-46]]

^<<v42-6-46,46>>^ "Por que vocês me chamam ‘Senhor! Senhor!’, se não fazem o que eu digo?

[[v42-6-47]]

^<<v42-6-47,47>>^ Eu lhes mostrarei como é aquele que vem a mim, ouve as minhas palavras e as pratica.

[[v42-6-48]]

^<<v42-6-48,48>>^ Ele é como a pessoa que está construindo uma casa e que cava fundo e coloca os alicerces em rocha firme. Quando a água das enchentes sobe e bate contra essa casa, ela permanece firme, pois foi bem construída.

[[v42-6-49]]

^<<v42-6-49,49>>^ Mas quem ouve e não obedece é como a pessoa que constrói uma casa sobre o chão, sem alicerces. Quando a água bater nessa casa, ela cairá, deixando uma pilha de ruínas".

'''

xref:042-lucas/042-lucas-005.adoc#v42-5-0[&#60; Capítulo Anterior] | <<v42-6-0,Topo>> | xref:042-lucas/042-lucas-007.adoc#v42-7-0[Próximo Capítulo &#62;]