include::./index.adoc[]

[[v42-4-0]]
=== Lucas, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v42-4-1]]

^<<v42-4-1,1>>^ Jesus, cheio do Espírito Santo, voltou do rio Jordão e foi conduzido pelo Espírito no deserto,

[[v42-4-2]]

^<<v42-4-2,2>>^ onde foi tentado pelo diabo durante quarenta dias. Não comeu nada durante todo esse tempo, e teve fome.

[[v42-4-3]]

^<<v42-4-3,3>>^ Então o diabo lhe disse: "Se você é o Filho de Deus, ordene que esta pedra se transforme em pão".

[[v42-4-4]]

^<<v42-4-4,4>>^ Jesus, porém, respondeu: "As Escrituras dizem: ‘Uma pessoa não vive só de pão’".

[[v42-4-5]]

^<<v42-4-5,5>>^ Então o diabo o levou a um lugar alto e, num momento, lhe mostrou todos os reinos do mundo.

[[v42-4-6]]

^<<v42-4-6,6>>^ "Eu lhe darei a glória destes reinos e autoridade sobre eles, pois são meus e posso dá-los a quem eu quiser", disse o diabo.

[[v42-4-7]]

^<<v42-4-7,7>>^ "Eu lhe darei tudo se me adorar."

[[v42-4-8]]

^<<v42-4-8,8>>^ Jesus respondeu: "As Escrituras dizem: ‘Adore o Senhor, seu Deus, e sirva somente a ele’".

[[v42-4-9]]

^<<v42-4-9,9>>^ Então o diabo o levou a Jerusalém, até o ponto mais alto do templo, e disse: "Se você é o Filho de Deus, salte daqui.

[[v42-4-10]]

^<<v42-4-10,10>>^ Pois as Escrituras dizem: ‘Ele ordenará a seus anjos que o protejam.

[[v42-4-11]]

^<<v42-4-11,11>>^ Eles o sustentarão com as mãos, para que não machuque o pé em alguma pedra’".

[[v42-4-12]]

^<<v42-4-12,12>>^ Jesus respondeu: "As Escrituras dizem: ‘Não ponha à prova o Senhor, seu Deus’".

[[v42-4-13]]

^<<v42-4-13,13>>^ Quando o diabo terminou de tentar Jesus, deixou-o até que surgisse outra oportunidade.

[[v42-4-14]]

^<<v42-4-14,14>>^ Então Jesus, cheio do poder do Espírito, voltou para a Galileia. Relatos a seu respeito se espalharam rapidamente por toda a região.

[[v42-4-15]]

^<<v42-4-15,15>>^ Ele ensinava nas sinagogas, e todos o elogiavam.

[[v42-4-16]]

^<<v42-4-16,16>>^ Quando Jesus chegou a Nazaré, cidade de sua infância, foi à sinagoga no sábado, como de costume, e se levantou para ler as Escrituras.

[[v42-4-17]]

^<<v42-4-17,17>>^ Entregaram-lhe o livro do profeta Isaías, e ele o abriu e encontrou o lugar onde estava escrito:

[[v42-4-18]]

^<<v42-4-18,18>>^ "O Espírito do Senhor está sobre mim, pois ele me ungiu para trazer as boas-novas aos pobres. Ele me enviou para anunciar que os cativos serão soltos, os cegos verão, os oprimidos serão libertos,

[[v42-4-19]]

^<<v42-4-19,19>>^ e que é chegado o tempo do favor do Senhor".

[[v42-4-20]]

^<<v42-4-20,20>>^ Jesus fechou o livro, devolveu-o ao assistente e sentou-se. Todos na sinagoga o olhavam atentamente.

[[v42-4-21]]

^<<v42-4-21,21>>^ Então ele começou a dizer: "Hoje se cumpriram as Escrituras que vocês acabaram de ouvir".

[[v42-4-22]]

^<<v42-4-22,22>>^ Todos falavam bem dele e estavam admirados com as palavras de graça que saíam de seus lábios. Contudo, perguntavam: "Não é esse o filho de José?".

[[v42-4-23]]

^<<v42-4-23,23>>^ Então ele disse: "Sem dúvida, vocês citarão para mim o ditado: ‘Médico, cure a si mesmo’, ou seja, ‘Faça aqui, em sua cidade, o mesmo que fez em Cafarnaum’.

[[v42-4-24]]

^<<v42-4-24,24>>^ Eu, porém, lhes digo a verdade: nenhum profeta é aceito em sua própria cidade.

[[v42-4-25]]

^<<v42-4-25,25>>^ "Por certo havia muitas viúvas necessitadas em Israel no tempo de Elias, quando o céu se fechou por três anos e meio e uma fome terrível devastou a terra.

[[v42-4-26]]

^<<v42-4-26,26>>^ E, no entanto, Elias não foi enviado a nenhuma delas, mas sim a uma estrangeira, uma viúva de Sarepta, na região de Sidom.

[[v42-4-27]]

^<<v42-4-27,27>>^ E havia muitos leprosos em Israel no tempo do profeta Eliseu, mas o único que ele curou foi Naamã, o sírio".

[[v42-4-28]]

^<<v42-4-28,28>>^ Quando ouviram isso, aqueles que estavam na sinagoga ficaram furiosos.

[[v42-4-29]]

^<<v42-4-29,29>>^ Levantaram-se, expulsaram Jesus da cidade e o arrastaram até a beira do monte sobre o qual a cidade tinha sido construída. Pretendiam empurrá-lo precipício abaixo,

[[v42-4-30]]

^<<v42-4-30,30>>^ mas ele passou por entre a multidão e seguiu seu caminho.

[[v42-4-31]]

^<<v42-4-31,31>>^ Então Jesus foi a Cafarnaum, uma cidade na Galileia, onde ensinava na sinagoga aos sábados.

[[v42-4-32]]

^<<v42-4-32,32>>^ Ali também o povo ficou admirado com seu ensino, pois ele falava com autoridade.

[[v42-4-33]]

^<<v42-4-33,33>>^ Certa ocasião, estando ele na sinagoga, um homem possuído por um demônio, um espírito impuro, gritou:

[[v42-4-34]]

^<<v42-4-34,34>>^ "Por que vem nos importunar, Jesus de Nazaré? Veio para nos destruir? Sei quem é você: o Santo de Deus!".

[[v42-4-35]]

^<<v42-4-35,35>>^ Jesus o repreendeu, dizendo: "Cale-se! Saia deste homem!". Então o espírito jogou o homem no chão à vista da multidão e saiu dele, sem machucá-lo.

[[v42-4-36]]

^<<v42-4-36,36>>^ Admirado, o povo exclamava: "Que autoridade e poder ele tem! Até os espíritos impuros lhe obedecem e saem quando ele ordena!".

[[v42-4-37]]

^<<v42-4-37,37>>^ E as notícias a respeito de Jesus se espalharam pelos povoados de toda a região.

[[v42-4-38]]

^<<v42-4-38,38>>^ Depois de sair da sinagoga naquele dia, Jesus foi à casa de Simão, onde encontrou a sogra dele muito doente, com febre alta. Quando os presentes suplicaram por ela,

[[v42-4-39]]

^<<v42-4-39,39>>^ Jesus se pôs ao lado da cama e repreendeu a febre, que a deixou. Ela se levantou de imediato e passou a servi-los.

[[v42-4-40]]

^<<v42-4-40,40>>^ Quando o sol se pôs, as pessoas trouxeram seus familiares enfermos até ele. Qualquer que fosse a doença, ao pôr as mãos sobre eles, Jesus curava a todos.

[[v42-4-41]]

^<<v42-4-41,41>>^ Muitos estavam possuídos por demônios, que saíam gritando: "Você é o Filho de Deus!". Jesus, no entanto, os repreendia e não permitia que falassem, pois sabiam que ele era o Cristo.

[[v42-4-42]]

^<<v42-4-42,42>>^ Logo cedo na manhã seguinte, Jesus retirou-se para um lugar isolado. As multidões o procuravam por toda parte e, quando finalmente o encontraram, suplicaram que não as deixasse.

[[v42-4-43]]

^<<v42-4-43,43>>^ Ele, porém, disse: "Preciso anunciar as boas-novas do reino de Deus também em outras cidades, pois para isso fui enviado".

[[v42-4-44]]

^<<v42-4-44,44>>^ E continuou a anunciar sua mensagem nas sinagogas da Judeia.

'''

xref:042-lucas/042-lucas-003.adoc#v42-3-0[&#60; Capítulo Anterior] | <<v42-4-0,Topo>> | xref:042-lucas/042-lucas-005.adoc#v42-5-0[Próximo Capítulo &#62;]