include::./index.adoc[]

[[v42-22-0]]
=== Lucas, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v42-22-1]]

^<<v42-22-1,1>>^ A Festa dos Pães sem Fermento, também chamada de Páscoa, se aproximava.

[[v42-22-2]]

^<<v42-22-2,2>>^ Os principais sacerdotes e mestres da lei tramavam uma forma de matar Jesus, mas tinham medo da reação do povo.

[[v42-22-3]]

^<<v42-22-3,3>>^ Então Satanás entrou em Judas Iscariotes, um dos Doze,

[[v42-22-4]]

^<<v42-22-4,4>>^ e ele foi aos principais sacerdotes e aos capitães da guarda do templo para combinar a melhor maneira de lhes entregar Jesus.

[[v42-22-5]]

^<<v42-22-5,5>>^ Eles ficaram muito satisfeitos e lhe prometeram dinheiro.

[[v42-22-6]]

^<<v42-22-6,6>>^ Judas concordou e começou a procurar uma oportunidade de trair Jesus, para que o prendessem quando as multidões não estivessem por perto.

[[v42-22-7]]

^<<v42-22-7,7>>^ Chegou o dia da Festa dos Pães sem Fermento, quando o cordeiro pascal era sacrificado.

[[v42-22-8]]

^<<v42-22-8,8>>^ Jesus mandou Pedro e João na frente e disse: "Vão e preparem a refeição da Páscoa, para que a comamos juntos".

[[v42-22-9]]

^<<v42-22-9,9>>^ "Onde o senhor quer que a preparemos?", perguntaram.

[[v42-22-10]]

^<<v42-22-10,10>>^ Ele respondeu: "Logo que vocês entrarem em Jerusalém, um homem carregando uma vasilha de água virá ao seu encontro. Sigam-no. Na casa onde ele entrar,

[[v42-22-11]]

^<<v42-22-11,11>>^ digam ao dono: ‘O Mestre pergunta: Onde fica o aposento no qual comerei a refeição da Páscoa com meus discípulos?’.

[[v42-22-12]]

^<<v42-22-12,12>>^ Ele os levará a uma sala grande no andar superior, que já estará arrumada. Preparem ali a refeição".

[[v42-22-13]]

^<<v42-22-13,13>>^ Eles foram e encontraram tudo como Jesus tinha dito, e ali prepararam a refeição da Páscoa.

[[v42-22-14]]

^<<v42-22-14,14>>^ Quando chegou a hora, Jesus e seus apóstolos tomaram lugar à mesa.

[[v42-22-15]]

^<<v42-22-15,15>>^ Jesus disse: "Estava ansioso para comer a refeição da Páscoa com vocês antes do meu sofrimento.

[[v42-22-16]]

^<<v42-22-16,16>>^ Pois eu lhes digo agora que não voltarei a comê-la até que ela se cumpra no reino de Deus".

[[v42-22-17]]

^<<v42-22-17,17>>^ Então tomou um cálice de vinho e agradeceu a Deus. Depois, disse: "Tomem isto e partilhem entre vocês.

[[v42-22-18]]

^<<v42-22-18,18>>^ Pois não beberei vinho outra vez até que venha o reino de Deus".

[[v42-22-19]]

^<<v42-22-19,19>>^ Tomou o pão e agradeceu a Deus. Depois, partiu-o e o deu aos discípulos, dizendo: "Este é o meu corpo, entregue por vocês. Façam isto em memória de mim".

[[v42-22-20]]

^<<v42-22-20,20>>^ Depois da ceia, Jesus tomou o cálice de vinho e disse: "Este é o cálice da nova aliança, confirmada com o meu sangue, que é derramado como sacrifício por vocês.

[[v42-22-21]]

^<<v42-22-21,21>>^ "Mas aqui, partilhando da mesa conosco, está o homem que vai me trair.

[[v42-22-22]]

^<<v42-22-22,22>>^ Pois foi determinado que o Filho do Homem deve morrer. Mas que aflição espera aquele que o trair!"

[[v42-22-23]]

^<<v42-22-23,23>>^ Os discípulos perguntavam uns aos outros qual deles faria uma coisa dessas.

[[v42-22-24]]

^<<v42-22-24,24>>^ Depois, começaram a discutir entre si qual deles era o mais importante.

[[v42-22-25]]

^<<v42-22-25,25>>^ Jesus lhes disse: "Neste mundo, os reis e os grandes homens exercem poder sobre o povo e, no entanto, são chamados de seus benfeitores.

[[v42-22-26]]

^<<v42-22-26,26>>^ Entre vocês, porém, será diferente. Que o maior entre vocês ocupe a posição inferior, e o líder seja o servo.

[[v42-22-27]]

^<<v42-22-27,27>>^ Quem é mais importante, o que está à mesa ou o que serve? Não é aquele que está à mesa? Mas não aqui! Pois eu estou entre vocês como quem serve.

[[v42-22-28]]

^<<v42-22-28,28>>^ "Vocês permaneceram comigo durante meu tempo de provação.

[[v42-22-29]]

^<<v42-22-29,29>>^ E, assim como meu Pai me concedeu um reino, eu agora lhes concedo o direito de

[[v42-22-30]]

^<<v42-22-30,30>>^ comer e beber à minha mesa, em meu reino. Vocês se sentarão em tronos e julgarão as doze tribos de Israel".

[[v42-22-31]]

^<<v42-22-31,31>>^ Então o Senhor disse: "Simão, Simão, Satanás pediu para peneirar cada um de vocês como trigo.

[[v42-22-32]]

^<<v42-22-32,32>>^ Contudo, supliquei em oração por você, Simão, para que sua fé não vacile. Portanto, quando tiver se arrependido e voltado para mim, fortaleça seus irmãos".

[[v42-22-33]]

^<<v42-22-33,33>>^ Pedro disse: "Senhor, estou pronto a ir para a prisão, e até a morrer ao seu lado".

[[v42-22-34]]

^<<v42-22-34,34>>^ Jesus, porém, respondeu: "Pedro, vou lhe dizer uma coisa: hoje, antes que o galo cante, você negará três vezes que me conhece".

[[v42-22-35]]

^<<v42-22-35,35>>^ Em seguida, Jesus lhes perguntou: "Quando eu os enviei para anunciar as boas-novas sem dinheiro, sem bolsa de viagem e sem sandálias extras, alguma coisa lhes faltou?". "Não", responderam eles.

[[v42-22-36]]

^<<v42-22-36,36>>^ Então ele disse: "Agora, porém, peguem dinheiro e uma bolsa de viagem. E, se não tiverem uma espada, vendam sua capa e comprem uma.

[[v42-22-37]]

^<<v42-22-37,37>>^ Pois é necessário que se cumpra esta profecia a meu respeito: ‘Ele foi contado entre os rebeldes’. Sim, tudo que os profetas escreveram a meu respeito se cumprirá".

[[v42-22-38]]

^<<v42-22-38,38>>^ Eles responderam: "Senhor, temos aqui duas espadas". "É suficiente", disse ele.

[[v42-22-39]]

^<<v42-22-39,39>>^ Então, acompanhado de seus discípulos, Jesus foi, como de costume, ao monte das Oliveiras.

[[v42-22-40]]

^<<v42-22-40,40>>^ Ao chegar, disse: "Orem para que vocês não cedam à tentação".

[[v42-22-41]]

^<<v42-22-41,41>>^ Afastou-se a uma distância como de um arremesso de pedra, ajoelhou-se e orou:

[[v42-22-42]]

^<<v42-22-42,42>>^ "Pai, se queres, afasta de mim este cálice. Contudo, que seja feita a tua vontade, e não a minha".

[[v42-22-43]]

^<<v42-22-43,43>>^ Então apareceu um anjo do céu, que o fortalecia.

[[v42-22-44]]

^<<v42-22-44,44>>^ Ele orou com ainda mais fervor, e sua angústia era tanta que seu suor caía na terra como gotas de sangue.

[[v42-22-45]]

^<<v42-22-45,45>>^ Por fim, ele se levantou, voltou aos discípulos e os encontrou dormindo, exaustos de tristeza.

[[v42-22-46]]

^<<v42-22-46,46>>^ "Por que vocês dormem?", perguntou ele. "Levantem-se e orem para que não cedam à tentação."

[[v42-22-47]]

^<<v42-22-47,47>>^ Enquanto Jesus ainda falava, chegou uma multidão conduzida por Judas, um dos Doze. Ele se aproximou de Jesus e o cumprimentou com um beijo.

[[v42-22-48]]

^<<v42-22-48,48>>^ Jesus, porém, lhe disse: "Judas, com um beijo você trai o Filho do Homem?".

[[v42-22-49]]

^<<v42-22-49,49>>^ Quando aqueles que estavam com Jesus viram o que ia acontecer, disseram: "Senhor, devemos lutar? Trouxemos as espadas!".

[[v42-22-50]]

^<<v42-22-50,50>>^ E um deles feriu o servo do sumo sacerdote, cortando-lhe a orelha direita.

[[v42-22-51]]

^<<v42-22-51,51>>^ Mas Jesus disse: "Basta!". E, tocando a orelha do homem, curou-o.

[[v42-22-52]]

^<<v42-22-52,52>>^ Então Jesus se dirigiu aos principais sacerdotes, aos capitães da guarda do templo e aos líderes do povo que tinham vindo buscá-lo: "Por acaso sou um revolucionário perigoso para que venham me prender com espadas e pedaços de pau?

[[v42-22-53]]

^<<v42-22-53,53>>^ Por que não me prenderam no templo? Todos os dias eu estava ali, ensinando. Mas esta é a hora de vocês, o tempo em que reina o poder das trevas".

[[v42-22-54]]

^<<v42-22-54,54>>^ Então eles o prenderam e o levaram à casa do sumo sacerdote. Pedro o seguiu de longe.

[[v42-22-55]]

^<<v42-22-55,55>>^ Os guardas acenderam uma fogueira no meio do pátio e sentaram-se em volta, e Pedro sentou-se com eles.

[[v42-22-56]]

^<<v42-22-56,56>>^ Uma criada o notou à luz da fogueira e começou a olhar fixamente para ele. Por fim, disse: "Este homem era um dos seguidores de Jesus!".

[[v42-22-57]]

^<<v42-22-57,57>>^ Mas Pedro negou, dizendo: "Mulher, eu nem o conheço!".

[[v42-22-58]]

^<<v42-22-58,58>>^ Pouco depois, um homem olhou para ele e disse: "Você também é um deles!". "Não sou!", retrucou Pedro.

[[v42-22-59]]

^<<v42-22-59,59>>^ Cerca de uma hora mais tarde, outro homem afirmou: "Com certeza esse aí também estava com ele, pois também é galileu!".

[[v42-22-60]]

^<<v42-22-60,60>>^ Pedro, porém, respondeu: "Homem, eu não sei do que você está falando". E, no mesmo instante, o galo cantou.

[[v42-22-61]]

^<<v42-22-61,61>>^ Então o Senhor se voltou e olhou para Pedro. E Pedro se lembrou das palavras dele: "Hoje, antes que o galo cante, você me negará três vezes".

[[v42-22-62]]

^<<v42-22-62,62>>^ E Pedro saiu dali, chorando amargamente.

[[v42-22-63]]

^<<v42-22-63,63>>^ Os guardas encarregados de Jesus começaram a zombar dele e a bater nele.

[[v42-22-64]]

^<<v42-22-64,64>>^ Vendaram seus olhos e diziam: "Profetize para nós! Quem foi que lhe bateu desta vez?".

[[v42-22-65]]

^<<v42-22-65,65>>^ E o insultavam de muitas outras maneiras.

[[v42-22-66]]

^<<v42-22-66,66>>^ Ao amanhecer, todos os líderes do povo se reuniram, incluindo os principais sacerdotes e os mestres da lei. Jesus foi conduzido à presença desse conselho,

[[v42-22-67]]

^<<v42-22-67,67>>^ e eles perguntaram: "Diga-nos, você é o Cristo?". Jesus respondeu: "Se eu lhes disser, de modo algum acreditarão em mim.

[[v42-22-68]]

^<<v42-22-68,68>>^ E, se eu lhes fizer uma pergunta, não responderão.

[[v42-22-69]]

^<<v42-22-69,69>>^ Mas, de agora em diante, o Filho do Homem se sentará à direita do Deus Poderoso".

[[v42-22-70]]

^<<v42-22-70,70>>^ Todos gritaram: "Então você afirma que é o Filho de Deus?". E ele respondeu: "Vocês dizem que eu sou".

[[v42-22-71]]

^<<v42-22-71,71>>^ "Que necessidade temos de outras testemunhas?", disseram eles. "Nós mesmos o ouvimos de sua boca!"

'''

xref:042-lucas/042-lucas-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-lucas/042-lucas-023.adoc#v42-23-0[Próximo Capítulo &#62;]