include::./index.adoc[]

[[v42-10-0]]
=== Lucas, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v42-10-1]]

^<<v42-10-1,1>>^ Depois disso, o Senhor escolheu outros setenta e dois discípulos e os enviou adiante, dois a dois, às cidades e aos lugares que ele planejava visitar.

[[v42-10-2]]

^<<v42-10-2,2>>^ Estas foram suas instruções: "A colheita é grande, mas os trabalhadores são poucos. Orem ao Senhor da colheita; peçam que ele envie mais trabalhadores para seus campos.

[[v42-10-3]]

^<<v42-10-3,3>>^ Agora vão e lembrem-se de que eu os envio como cordeiros no meio de lobos.

[[v42-10-4]]

^<<v42-10-4,4>>^ Não levem dinheiro algum, nem bolsa de viagem, nem um par de sandálias extras. E não se detenham para cumprimentar ninguém pelo caminho.

[[v42-10-5]]

^<<v42-10-5,5>>^ "Quando entrarem numa casa, digam primeiro: ‘Que a paz de Deus esteja nesta casa’.

[[v42-10-6]]

^<<v42-10-6,6>>^ Se os que vivem ali forem gente de paz, a bênção permanecerá; se não forem, a bênção voltará a vocês.

[[v42-10-7]]

^<<v42-10-7,7>>^ Permaneçam naquela casa e comam e bebam o que lhes derem, pois quem trabalha merece seu salário. Não fiquem mudando de casa em casa.

[[v42-10-8]]

^<<v42-10-8,8>>^ "Quando entrarem numa cidade e ela os receber bem, comam o que lhes oferecerem.

[[v42-10-9]]

^<<v42-10-9,9>>^ Curem os enfermos e digam-lhes: ‘Agora o reino de Deus chegou até vocês’.

[[v42-10-10]]

^<<v42-10-10,10>>^ Mas, se uma cidade se recusar a recebê-los, saiam pelas ruas e digam:

[[v42-10-11]]

^<<v42-10-11,11>>^ ‘Limpamos de nossos pés até o pó desta cidade em sinal de reprovação. E saibam disto: o reino de Deus chegou!’.

[[v42-10-12]]

^<<v42-10-12,12>>^ Eu lhes garanto que, no dia do juízo, até Sodoma será tratada com menos rigor que aquela cidade.

[[v42-10-13]]

^<<v42-10-13,13>>^ "Que aflição as espera, Corazim e Betsaida! Porque, se nas cidades de Tiro e Sidom tivessem sido realizados os milagres que realizei em vocês, há muito tempo seus habitantes teriam se arrependido e demonstrado isso vestindo panos de saco e jogando cinzas sobre a cabeça.

[[v42-10-14]]

^<<v42-10-14,14>>^ Eu lhes digo que, no dia do juízo, Tiro e Sidom serão tratadas com menos rigor que vocês.

[[v42-10-15]]

^<<v42-10-15,15>>^ E você, Cafarnaum, será elevada até o céu? Não, descerá até o lugar dos mortos".

[[v42-10-16]]

^<<v42-10-16,16>>^ Então ele disse aos discípulos: "Quem aceita sua mensagem também me aceita, e quem os rejeita também me rejeita. E quem me rejeita também rejeita aquele que me enviou".

[[v42-10-17]]

^<<v42-10-17,17>>^ Quando os setenta e dois discípulos voltaram, relataram com alegria: "Senhor, até os demônios nos obedecem pela sua autoridade!".

[[v42-10-18]]

^<<v42-10-18,18>>^ Então ele lhes disse: "Vi Satanás caindo do céu como um relâmpago!

[[v42-10-19]]

^<<v42-10-19,19>>^ Eu lhes dei autoridade para pisarem sobre cobras e escorpiões, e sobre todo o poder do inimigo. Nada lhes causará dano.

[[v42-10-20]]

^<<v42-10-20,20>>^ Mas não se alegrem porque os espíritos impuros lhes obedecem; alegrem-se porque seus nomes estão registrados no céu".

[[v42-10-21]]

^<<v42-10-21,21>>^ Naquele momento, Jesus foi tomado da alegria do Espírito Santo e disse: "Pai, Senhor dos céus e da terra, eu te agradeço porque escondeste estas coisas dos que se consideram sábios e inteligentes e as revelaste aos que são como crianças. Sim, Pai, foi do teu agrado fazê-lo assim.

[[v42-10-22]]

^<<v42-10-22,22>>^ "Meu Pai me confiou todas as coisas. Ninguém conhece verdadeiramente o Filho, a não ser o Pai, e ninguém conhece verdadeiramente o Pai, a não ser o Filho e aqueles a quem o Filho escolhe revelá-lo".

[[v42-10-23]]

^<<v42-10-23,23>>^ Então, em particular, ele se voltou para os discípulos e disse: "Felizes os olhos que veem o que vocês viram.

[[v42-10-24]]

^<<v42-10-24,24>>^ Eu lhes digo: muitos profetas e reis desejaram ver o que vocês têm visto e ouvir o que vocês têm ouvido, mas não puderam".

[[v42-10-25]]

^<<v42-10-25,25>>^ Certo dia, um especialista da lei se levantou para pôr Jesus à prova com esta pergunta: "Mestre, o que preciso fazer para herdar a vida eterna?".

[[v42-10-26]]

^<<v42-10-26,26>>^ Jesus respondeu: "O que diz a lei de Moisés? Como você a entende?".

[[v42-10-27]]

^<<v42-10-27,27>>^ O homem respondeu: "‘Ame o Senhor, seu Deus, de todo o seu coração, de toda a sua alma, de toda a sua força e de toda a sua mente’ e ‘Ame o seu próximo como a si mesmo’".

[[v42-10-28]]

^<<v42-10-28,28>>^ "Está correto!", disse Jesus. "Faça isso, e você viverá."

[[v42-10-29]]

^<<v42-10-29,29>>^ O homem, porém, querendo justificar suas ações, perguntou a Jesus: "E quem é o meu próximo?".

[[v42-10-30]]

^<<v42-10-30,30>>^ Jesus respondeu com uma história: "Certo homem descia de Jerusalém a Jericó, quando foi atacado por bandidos. Eles lhe tiraram as roupas, o espancaram e o deixaram quase morto à beira da estrada.

[[v42-10-31]]

^<<v42-10-31,31>>^ "Por acaso, descia por ali um sacerdote. Quando viu o homem caído, atravessou para o outro lado da estrada.

[[v42-10-32]]

^<<v42-10-32,32>>^ Um levita fazia o mesmo caminho e viu o homem caído, mas também atravessou e passou longe.

[[v42-10-33]]

^<<v42-10-33,33>>^ "Então veio um samaritano e, ao ver o homem, teve compaixão dele.

[[v42-10-34]]

^<<v42-10-34,34>>^ Foi até ele, tratou de seus ferimentos com óleo e vinho e os enfaixou. Depois, colocou o homem em seu jumento e o levou a uma hospedaria, onde cuidou dele.

[[v42-10-35]]

^<<v42-10-35,35>>^ No dia seguinte, deu duas moedas de prata ao dono da hospedaria e disse: ‘Cuide deste homem. Se você precisar gastar a mais com ele, eu lhe pagarei a diferença quando voltar’.

[[v42-10-36]]

^<<v42-10-36,36>>^ "Qual desses três você diria que foi o próximo do homem atacado pelos bandidos?", perguntou Jesus.

[[v42-10-37]]

^<<v42-10-37,37>>^ O especialista da lei respondeu: "Aquele que teve misericórdia dele". Então Jesus disse: "Vá e faça o mesmo".

[[v42-10-38]]

^<<v42-10-38,38>>^ Jesus e seus discípulos seguiram viagem e chegaram a um povoado onde uma mulher chamada Marta os recebeu em sua casa.

[[v42-10-39]]

^<<v42-10-39,39>>^ Sua irmã, Maria, sentou-se aos pés de Jesus e ouvia o que ele ensinava.

[[v42-10-40]]

^<<v42-10-40,40>>^ Marta, porém, estava ocupada com seus muitos afazeres. Foi a Jesus e disse: "Senhor, não o incomoda que minha irmã fique aí sentada enquanto eu faço todo o trabalho? Diga-lhe que venha me ajudar!".

[[v42-10-41]]

^<<v42-10-41,41>>^ Mas o Senhor respondeu: "Marta, Marta, você se preocupa e se inquieta com todos esses detalhes.

[[v42-10-42]]

^<<v42-10-42,42>>^ Apenas uma coisa é necessária. Quanto a Maria, ela fez a escolha certa, e ninguém tomará isso dela".

'''

xref:042-lucas/042-lucas-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-lucas/042-lucas-011.adoc#v42-11-0[Próximo Capítulo &#62;]