include::./index.adoc[]

[[v20-2-0]]
=== Provérbios, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v20-2-1]]

^<<v20-2-1,1>>^ Meu filho, preste atenção às minhas palavras e guarde meus mandamentos como um tesouro.

[[v20-2-2]]

^<<v20-2-2,2>>^ Dê ouvidos à sabedoria e concentre o coração no entendimento.

[[v20-2-3]]

^<<v20-2-3,3>>^ Clame por inteligência e peça entendimento.

[[v20-2-4]]

^<<v20-2-4,4>>^ Busque-os como a prata, procure-os como a tesouros escondidos.

[[v20-2-5]]

^<<v20-2-5,5>>^ Então entenderá o que é o temor do Senhor e obterá o conhecimento de Deus.

[[v20-2-6]]

^<<v20-2-6,6>>^ Pois o SENHOR concede sabedoria; de sua boca vêm conhecimento e entendimento.

[[v20-2-7]]

^<<v20-2-7,7>>^ Ele reserva bom senso aos honestos e é escudo para os íntegros.

[[v20-2-8]]

^<<v20-2-8,8>>^ Guarda os caminhos dos justos e protege seus fiéis por onde andam.

[[v20-2-9]]

^<<v20-2-9,9>>^ Então você entenderá o que é certo, justo e imparcial e saberá o bom caminho a seguir.

[[v20-2-10]]

^<<v20-2-10,10>>^ Pois a sabedoria entrará em seu coração, e o conhecimento o encherá de alegria.

[[v20-2-11]]

^<<v20-2-11,11>>^ As escolhas sábias o guardarão, e o entendimento o protegerá.

[[v20-2-12]]

^<<v20-2-12,12>>^ A sabedoria o livrará das ações dos maus, daqueles cujas palavras são perversas.

[[v20-2-13]]

^<<v20-2-13,13>>^ Eles se afastam do rumo certo e andam por caminhos sombrios.

[[v20-2-14]]

^<<v20-2-14,14>>^ Têm prazer em praticar o mal e aplaudem a maldade dos perversos.

[[v20-2-15]]

^<<v20-2-15,15>>^ Suas ações são desonestas, e seus caminhos, tortuosos.

[[v20-2-16]]

^<<v20-2-16,16>>^ A sabedoria o livrará da mulher imoral, das palavras sedutoras da promíscua.

[[v20-2-17]]

^<<v20-2-17,17>>^ Ela abandona o marido, o companheiro de sua juventude, e ignora a aliança que fez diante de Deus.

[[v20-2-18]]

^<<v20-2-18,18>>^ Entrar na casa dela leva à morte; é a estrada para a sepultura.

[[v20-2-19]]

^<<v20-2-19,19>>^ O homem que a visita está perdido; jamais alcançará os caminhos da vida.

[[v20-2-20]]

^<<v20-2-20,20>>^ Portanto, siga os passos dos bons e permaneça nos caminhos dos justos.

[[v20-2-21]]

^<<v20-2-21,21>>^ Pois os retos viverão na terra, e os íntegros nela permanecerão.

[[v20-2-22]]

^<<v20-2-22,22>>^ Os perversos, porém, serão eliminados da terra, e os desleais, arrancados dela.

'''

xref:020-proverbios/020-proverbios-001.adoc#v20-1-0[&#60; Capítulo Anterior] | <<v20-2-0,Topo>> | xref:020-proverbios/020-proverbios-003.adoc#v20-3-0[Próximo Capítulo &#62;]