include::./index.adoc[]

[[v20-1-0]]
=== Provérbios, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v20-1-1]]

^<<v20-1-1,1>>^ Estes são os provérbios de Salomão, filho de Davi, rei de Israel.

[[v20-1-2]]

^<<v20-1-2,2>>^ Sua finalidade é ensinar sabedoria e disciplina às pessoas e ajudá-las a compreender as instruções dos sábios.

[[v20-1-3]]

^<<v20-1-3,3>>^ Sua finalidade é ensinar-lhes uma vida disciplinada e bem-sucedida e ajudá-las a fazer o que é certo, justo e imparcial.

[[v20-1-4]]

^<<v20-1-4,4>>^ Estes provérbios darão juízo aos ingênuos e conhecimento e discernimento aos jovens.

[[v20-1-5]]

^<<v20-1-5,5>>^ O sábio que os ouvir se tornará ainda mais sábio. Quem tem entendimento receberá orientação,

[[v20-1-6]]

^<<v20-1-6,6>>^ ao examinar o significado destes provérbios e parábolas, das palavras dos sábios e seus enigmas.

[[v20-1-7]]

^<<v20-1-7,7>>^ O temor do SENHOR é o princípio do conhecimento, mas os tolos desprezam a sabedoria e a disciplina.

[[v20-1-8]]

^<<v20-1-8,8>>^ Meu filho, preste atenção à correção de seu pai e não deixe de lado a instrução de sua mãe.

[[v20-1-9]]

^<<v20-1-9,9>>^ O que aprender com eles será coroa de graça em sua cabeça e colar de honra em seu pescoço.

[[v20-1-10]]

^<<v20-1-10,10>>^ Meu filho, se pecadores quiserem seduzi-lo, não permita que isso aconteça.

[[v20-1-11]]

^<<v20-1-11,11>>^ Talvez lhe digam: "Venha conosco! Vamos nos esconder e matar alguém. Armaremos emboscada contra inocentes, só para passar o tempo.

[[v20-1-12]]

^<<v20-1-12,12>>^ Vamos engoli-los vivos, como a sepultura; vamos engoli-los inteiros, como os que descem à cova.

[[v20-1-13]]

^<<v20-1-13,13>>^ Encontraremos todo tipo de riquezas e encheremos nossas casas com tudo que roubarmos.

[[v20-1-14]]

^<<v20-1-14,14>>^ Venha, junte-se a nós! Dividiremos igualmente os despojos".

[[v20-1-15]]

^<<v20-1-15,15>>^ Meu filho, não vá com eles! Afaste-se de seus caminhos.

[[v20-1-16]]

^<<v20-1-16,16>>^ Eles correm para fazer o mal; apressam-se em derramar sangue.

[[v20-1-17]]

^<<v20-1-17,17>>^ Se um pássaro vê alguém montar a armadilha, sabe que não deve se aproximar.

[[v20-1-18]]

^<<v20-1-18,18>>^ Eles, porém, armam emboscadas para si mesmos; tentam acabar com a própria vida.

[[v20-1-19]]

^<<v20-1-19,19>>^ Esse é o destino de todos os gananciosos; sua própria cobiça os destrói.

[[v20-1-20]]

^<<v20-1-20,20>>^ A Sabedoria grita nas ruas e levanta a voz na praça pública.

[[v20-1-21]]

^<<v20-1-21,21>>^ Sim, proclama nas avenidas e anuncia em frente à porta da cidade:

[[v20-1-22]]

^<<v20-1-22,22>>^ "Até quando vocês, ingênuos, insistirão em sua ingenuidade? Até quando vocês, zombadores, terão prazer na zombaria? Até quando vocês, tolos, detestarão o conhecimento?

[[v20-1-23]]

^<<v20-1-23,23>>^ Venham e ouçam minhas advertências; abrirei meu coração para vocês e os tornarei sábios.

[[v20-1-24]]

^<<v20-1-24,24>>^ "Muitas vezes eu os chamei, mas não quiseram vir; estendi-lhes a mão, mas não me deram atenção.

[[v20-1-25]]

^<<v20-1-25,25>>^ Desprezaram meu conselho e rejeitaram minha repreensão.

[[v20-1-26]]

^<<v20-1-26,26>>^ Por isso, rirei quando estiverem em dificuldades; zombarei quando estiverem em apuros,

[[v20-1-27]]

^<<v20-1-27,27>>^ quando a calamidade lhes sobrevier como a tempestade, e a desgraça os envolver como o furacão, e a angústia e a aflição os dominarem.

[[v20-1-28]]

^<<v20-1-28,28>>^ "Quando clamarem por socorro, não responderei; ainda que me procurem, não me encontrarão.

[[v20-1-29]]

^<<v20-1-29,29>>^ Porque detestaram o conhecimento e escolheram não temer o SENHOR.

[[v20-1-30]]

^<<v20-1-30,30>>^ Rejeitaram meu conselho e ignoraram minha repreensão.

[[v20-1-31]]

^<<v20-1-31,31>>^ Portanto, comerão os frutos amargos de seu estilo de vida e engasgarão em suas próprias intrigas.

[[v20-1-32]]

^<<v20-1-32,32>>^ Pois os ingênuos se afastam de mim e rumam para a morte; os tolos são destruídos por sua própria acomodação.

[[v20-1-33]]

^<<v20-1-33,33>>^ Os que me ouvem, porém, viverão em paz, tranquilos e sem temer o mal".

'''

xref:019-salmos/019-salmos-150.adoc#v19-150-0[&#60; Capítulo Anterior] | <<v20-1-0,Topo>> | xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[Próximo Capítulo &#62;]