include::./index.adoc[]

[[v20-24-0]]
=== Provérbios, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v20-24-1]]

^<<v20-24-1,1>>^ Não tenha inveja dos maus, nem deseje a companhia deles.

[[v20-24-2]]

^<<v20-24-2,2>>^ Pois tramam violência no coração, e suas palavras sempre causam problemas.

[[v20-24-3]]

^<<v20-24-3,3>>^ Com sabedoria se constrói a casa, e com entendimento ela se fortalece.

[[v20-24-4]]

^<<v20-24-4,4>>^ Pelo conhecimento seus cômodos se enchem de toda espécie de bens preciosos e desejáveis.

[[v20-24-5]]

^<<v20-24-5,5>>^ O sábio é mais poderoso que o forte; quem tem conhecimento se fortalece sempre mais.

[[v20-24-6]]

^<<v20-24-6,6>>^ Portanto, não saia para guerrear sem boa orientação; com muitos conselheiros se obtém a vitória.

[[v20-24-7]]

^<<v20-24-7,7>>^ A sabedoria é elevada demais para o insensato; entre os líderes à porta da cidade, nada tem a dizer.

[[v20-24-8]]

^<<v20-24-8,8>>^ Quem planeja o mal se torna conhecido como criador de problemas.

[[v20-24-9]]

^<<v20-24-9,9>>^ Os planos do insensato são pecado; o zombador é detestável para todos.

[[v20-24-10]]

^<<v20-24-10,10>>^ Se você vacilar no momento de dificuldade, sua força será pequena.

[[v20-24-11]]

^<<v20-24-11,11>>^ Liberte os que foram injustamente condenados a morrer; salve-os enquanto vão tropeçando para a morte.

[[v20-24-12]]

^<<v20-24-12,12>>^ Não se desculpe, dizendo: "Não sabia o que estava acontecendo"; lembre-se de que Deus conhece cada coração. Aquele que zela por sua vida sabe que você estava ciente; ele retribuirá a cada um conforme suas ações.

[[v20-24-13]]

^<<v20-24-13,13>>^ Meu filho, coma mel, pois é bom, e o favo é doce ao paladar.

[[v20-24-14]]

^<<v20-24-14,14>>^ Da mesma forma, a sabedoria é doce para a alma; se você a encontrar, terá um futuro brilhante, e suas esperanças não serão frustradas.

[[v20-24-15]]

^<<v20-24-15,15>>^ Não seja como o perverso, que fica de tocaia na frente da casa do justo, nem ataque a moradia dele.

[[v20-24-16]]

^<<v20-24-16,16>>^ Ainda que o justo tropece sete vezes, voltará a se levantar, mas uma só calamidade é suficiente para derrubar o perverso.

[[v20-24-17]]

^<<v20-24-17,17>>^ Não se alegre quando seu inimigo cair; não exulte quando ele tropeçar.

[[v20-24-18]]

^<<v20-24-18,18>>^ Pois o SENHOR se desagradará disso e dele desviará sua ira.

[[v20-24-19]]

^<<v20-24-19,19>>^ Não se perturbe por causa dos maus; não tenha inveja dos perversos.

[[v20-24-20]]

^<<v20-24-20,20>>^ Pois os maus não têm futuro; a luz dos perversos se apagará.

[[v20-24-21]]

^<<v20-24-21,21>>^ Meu filho, tema o SENHOR e o rei e não se associe com os rebeldes,

[[v20-24-22]]

^<<v20-24-22,22>>^ pois serão destruídos repentinamente; quem sabe que castigo virá do SENHOR e do rei?

[[v20-24-23]]

^<<v20-24-23,23>>^ Estes são mais alguns ditados dos sábios: É errado tomar partido quando se julga um caso.

[[v20-24-24]]

^<<v20-24-24,24>>^ O juiz que diz ao perverso: "Você é inocente", será amaldiçoado pelo povo e odiado pelas nações.

[[v20-24-25]]

^<<v20-24-25,25>>^ Mas as coisas irão bem para os que condenam o culpado; eles receberão grandes bênçãos.

[[v20-24-26]]

^<<v20-24-26,26>>^ Uma resposta honesta é como um beijo de amizade.

[[v20-24-27]]

^<<v20-24-27,27>>^ Antes de construir sua casa, planeje-se e prepare os campos.

[[v20-24-28]]

^<<v20-24-28,28>>^ Não testemunhe contra o próximo sem motivo; não minta a respeito dele.

[[v20-24-29]]

^<<v20-24-29,29>>^ E não diga: "Agora vou me vingar do que ele me fez! Vou acertar as contas com ele!".

[[v20-24-30]]

^<<v20-24-30,30>>^ Passei pelo campo do preguiçoso, pelo vinhedo daquele que não tem juízo.

[[v20-24-31]]

^<<v20-24-31,31>>^ Tudo estava cheio de espinhos e coberto de ervas daninhas, e seu muro de pedras, em ruínas.

[[v20-24-32]]

^<<v20-24-32,32>>^ Então, enquanto observava e pensava no que via, aprendi esta lição:

[[v20-24-33]]

^<<v20-24-33,33>>^ Um pouco mais de sono, mais um cochilo, mais um descanso com os braços cruzados,

[[v20-24-34]]

^<<v20-24-34,34>>^ e a pobreza o assaltará como um bandido; a escassez o atacará como um ladrão armado.

'''

xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[&#60; Capítulo Anterior] | <<v20-24-0,Topo>> | xref:020-proverbios/020-proverbios-025.adoc#v20-25-0[Próximo Capítulo &#62;]