include::./index.adoc[]

[[v20-6-0]]
=== Provérbios, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v20-6-1]]

^<<v20-6-1,1>>^ Meu filho, se você aceitou ser fiador de seu amigo ou se concordou em garantir a dívida de um estranho,

[[v20-6-2]]

^<<v20-6-2,2>>^ se caiu numa armadilha por causa do acordo feito e se está preso por suas palavras,

[[v20-6-3]]

^<<v20-6-3,3>>^ siga meu conselho e livre-se dessa obrigação, pois você se colocou nas mãos de seu amigo. Procure-o, humilhe-se e insista com ele.

[[v20-6-4]]

^<<v20-6-4,4>>^ Não deixe para amanhã; não descanse enquanto não resolver essa situação.

[[v20-6-5]]

^<<v20-6-5,5>>^ Livre-se como a gazela que escapa do caçador, como o pássaro que foge da rede.

[[v20-6-6]]

^<<v20-6-6,6>>^ Aprenda com a formiga, preguiçoso! Observe como ela age e seja sábio.

[[v20-6-7]]

^<<v20-6-7,7>>^ Embora não tenha príncipe, nem autoridade, nem governante,

[[v20-6-8]]

^<<v20-6-8,8>>^ ela trabalha duro durante todo o verão, juntando comida para o inverno.

[[v20-6-9]]

^<<v20-6-9,9>>^ Mas você, preguiçoso, até quando dormirá? Quando sairá da cama?

[[v20-6-10]]

^<<v20-6-10,10>>^ Um pouco mais de sono, mais um cochilo, mais um descanso com os braços cruzados,

[[v20-6-11]]

^<<v20-6-11,11>>^ e a pobreza o assaltará como um bandido; a escassez o atacará como um ladrão armado.

[[v20-6-12]]

^<<v20-6-12,12>>^ Como são os desprezíveis e os perversos? Eles vivem mentindo:

[[v20-6-13]]

^<<v20-6-13,13>>^ demonstram sua falsidade com um piscar de olho, com um movimento do pé ou por sinais com os dedos.

[[v20-6-14]]

^<<v20-6-14,14>>^ Seu coração pervertido trama a maldade, e andam sempre criando problemas.

[[v20-6-15]]

^<<v20-6-15,15>>^ Por isso, serão destruídos de repente, despedaçados num instante sem que possam se recuperar.

[[v20-6-16]]

^<<v20-6-16,16>>^ Há seis coisas que o SENHOR odeia, ou melhor, sete coisas que ele considera detestáveis:

[[v20-6-17]]

^<<v20-6-17,17>>^ olhos arrogantes, língua mentirosa, mãos que matam o inocente,

[[v20-6-18]]

^<<v20-6-18,18>>^ coração que trama a maldade, pés que se apressam em fazer o mal,

[[v20-6-19]]

^<<v20-6-19,19>>^ testemunha falsa que diz mentiras, e aquele que semeia desentendimento entre irmãos.

[[v20-6-20]]

^<<v20-6-20,20>>^ Meu filho, obedeça aos mandamentos de seu pai e não deixe de lado a instrução de sua mãe.

[[v20-6-21]]

^<<v20-6-21,21>>^ Guarde as palavras deles em seu coração e amarre-as em seu pescoço.

[[v20-6-22]]

^<<v20-6-22,22>>^ Quando você andar, os conselhos de seus pais o guiarão; quando dormir, eles o protegerão; quando acordar, eles o orientarão.

[[v20-6-23]]

^<<v20-6-23,23>>^ Pois o mandamento é lâmpada, e a instrução é luz; e as correções da disciplina são o caminho que conduz à vida.

[[v20-6-24]]

^<<v20-6-24,24>>^ Eles o protegerão da mulher imoral, das palavras sedutoras da promíscua.

[[v20-6-25]]

^<<v20-6-25,25>>^ Não cobice sua beleza; não deixe que seus olhares o seduzam.

[[v20-6-26]]

^<<v20-6-26,26>>^ Pois a prostituta o levará à pobreza, mas dormir com a esposa de outro homem lhe custará a vida.

[[v20-6-27]]

^<<v20-6-27,27>>^ Pode um homem carregar fogo junto ao peito sem que a roupa se queime?

[[v20-6-28]]

^<<v20-6-28,28>>^ Pode alguém caminhar sobre brasas sem que os pés se queimem?

[[v20-6-29]]

^<<v20-6-29,29>>^ Assim acontece com quem dorme com a mulher de outro; aquele que a toca não ficará sem castigo.

[[v20-6-30]]

^<<v20-6-30,30>>^ Pode-se encontrar desculpa para o ladrão que rouba porque está com fome.

[[v20-6-31]]

^<<v20-6-31,31>>^ Ainda assim, se for apanhado, terá de pagar sete vezes o que roubou, mesmo que precise vender tudo que há em sua casa.

[[v20-6-32]]

^<<v20-6-32,32>>^ Mas o homem que comete adultério não tem juízo, pois destrói a si mesmo.

[[v20-6-33]]

^<<v20-6-33,33>>^ Será ferido e desonrado, e sua vergonha jamais se apagará.

[[v20-6-34]]

^<<v20-6-34,34>>^ Porque o marido ciumento ficará furioso e não terá misericórdia quando se vingar.

[[v20-6-35]]

^<<v20-6-35,35>>^ Não aceitará compensação alguma, nem se satisfará com os presentes mais valiosos.

'''

xref:020-proverbios/020-proverbios-005.adoc#v20-5-0[&#60; Capítulo Anterior] | <<v20-6-0,Topo>> | xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[Próximo Capítulo &#62;]