include::./index.adoc[]

[[v20-22-0]]
=== Provérbios, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v20-22-1]]

^<<v20-22-1,1>>^ A boa reputação vale mais que grandes riquezas; ser estimado é melhor que prata e ouro.

[[v20-22-2]]

^<<v20-22-2,2>>^ O rico e o pobre têm isto em comum: o SENHOR criou os dois.

[[v20-22-3]]

^<<v20-22-3,3>>^ O prudente antevê o perigo e toma precauções; o ingênuo avança às cegas e sofre as consequências.

[[v20-22-4]]

^<<v20-22-4,4>>^ A humildade e o temor do Senhor trazem riquezas, honra e vida longa.

[[v20-22-5]]

^<<v20-22-5,5>>^ O perverso anda por um caminho cheio de espinhos e perigos; quem dá valor à vida se afasta dele.

[[v20-22-6]]

^<<v20-22-6,6>>^ Ensine seus filhos no caminho certo, e, mesmo quando envelhecerem, não se desviarão dele.

[[v20-22-7]]

^<<v20-22-7,7>>^ Assim como o rico domina sobre o pobre, quem toma emprestado se torna servo de quem empresta.

[[v20-22-8]]

^<<v20-22-8,8>>^ Quem semeia injustiça colhe desgraça, e seu reino de terror chegará ao fim.

[[v20-22-9]]

^<<v20-22-9,9>>^ A pessoa generosa será abençoada, pois alimenta o pobre.

[[v20-22-10]]

^<<v20-22-10,10>>^ Mande embora o zombador e cessarão as brigas; não haverá mais contendas nem insultos.

[[v20-22-11]]

^<<v20-22-11,11>>^ Quem ama o coração puro e fala de modo agradável terá o rei como amigo.

[[v20-22-12]]

^<<v20-22-12,12>>^ O SENHOR preserva aquele que tem conhecimento, mas frustra os planos dos desleais.

[[v20-22-13]]

^<<v20-22-13,13>>^ O preguiçoso diz: ‘Há um leão lá fora! Se eu sair, ele me matará!".

[[v20-22-14]]

^<<v20-22-14,14>>^ A conversa da mulher imoral é cova profunda; quem provoca a ira do SENHOR nela cairá.

[[v20-22-15]]

^<<v20-22-15,15>>^ O coração da criança é inclinado à insensatez, mas a vara da disciplina a afastará dela.

[[v20-22-16]]

^<<v20-22-16,16>>^ Quem explora os pobres ou cobre os ricos de presentes para progredir na vida acabará na pobreza.

[[v20-22-17]]

^<<v20-22-17,17>>^ Ouça as palavras dos sábios; dedique o coração à minha instrução.

[[v20-22-18]]

^<<v20-22-18,18>>^ Porque é bom guardar no coração estes ditados e tê-los sempre na ponta da língua.

[[v20-22-19]]

^<<v20-22-19,19>>^ Hoje eu as ensino a você, para que confie no SENHOR.

[[v20-22-20]]

^<<v20-22-20,20>>^ Escrevi para você estes trinta ditados cheios de conselhos e conhecimento.

[[v20-22-21]]

^<<v20-22-21,21>>^ Assim você saberá a verdade e transmitirá um relato preciso àqueles que o enviaram.

[[v20-22-22]]

^<<v20-22-22,22>>^ Não explore o pobre só porque tem oportunidade, nem se aproveite do necessitado no tribunal.

[[v20-22-23]]

^<<v20-22-23,23>>^ Pois o SENHOR defenderá a causa deles; pagará na mesma medida a todos que os exploram.

[[v20-22-24]]

^<<v20-22-24,24>>^ Não faça amizade com os briguentos, nem ande com quem se ira facilmente,

[[v20-22-25]]

^<<v20-22-25,25>>^ pois aprenderá a ser igual a eles e colocará a si mesmo em perigo.

[[v20-22-26]]

^<<v20-22-26,26>>^ Não se comprometa a garantir a dívida de outro, nem aceite servir de fiador.

[[v20-22-27]]

^<<v20-22-27,27>>^ Se você não tiver como pagar a dívida, até a cama em que dorme será tomada.

[[v20-22-28]]

^<<v20-22-28,28>>^ Não mude de lugar os antigos marcadores de divisa estabelecidos pelas gerações anteriores.

[[v20-22-29]]

^<<v20-22-29,29>>^ Você já viu alguém muito competente no que faz? Ele servirá reis em vez de trabalhar para gente comum.

'''

xref:020-proverbios/020-proverbios-021.adoc#v20-21-0[&#60; Capítulo Anterior] | <<v20-22-0,Topo>> | xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[Próximo Capítulo &#62;]