include::./index.adoc[]

[[v20-8-0]]
=== Provérbios, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v20-8-1]]

^<<v20-8-1,1>>^ Escutem, pois a Sabedoria chama! Ouçam, porque o entendimento levanta a voz!

[[v20-8-2]]

^<<v20-8-2,2>>^ No alto dos montes, junto ao caminho, a Sabedoria se coloca nas encruzilhadas.

[[v20-8-3]]

^<<v20-8-3,3>>^ Ao lado das portas da cidade, na entrada, ela anuncia:

[[v20-8-4]]

^<<v20-8-4,4>>^ "A vocês eu clamo, a todos vocês! Levanto minha voz para todo o povo.

[[v20-8-5]]

^<<v20-8-5,5>>^ Vocês, inexperientes, mostrem discernimento! Vocês, tolos, mostrem entendimento!

[[v20-8-6]]

^<<v20-8-6,6>>^ Ouçam, pois tenho coisas importantes a lhes dizer. Tudo que digo é correto,

[[v20-8-7]]

^<<v20-8-7,7>>^ pois falo a verdade, e toda espécie de engano é detestável para mim.

[[v20-8-8]]

^<<v20-8-8,8>>^ Meu conselho é justo; não há nada nele que distorça a verdade ou dela se desvie.

[[v20-8-9]]

^<<v20-8-9,9>>^ Minhas palavras são claras para os que têm entendimento e corretas para os que têm conhecimento.

[[v20-8-10]]

^<<v20-8-10,10>>^ Escolham minha instrução em vez da prata e o conhecimento em vez do ouro puro.

[[v20-8-11]]

^<<v20-8-11,11>>^ Pois a sabedoria vale muito mais que rubis; nada do que você deseja se compara a ela.

[[v20-8-12]]

^<<v20-8-12,12>>^ "Eu, a Sabedoria, moro com a prudência; sei onde encontrar conhecimento e discernimento.

[[v20-8-13]]

^<<v20-8-13,13>>^ Quem teme o SENHOR odeia o mal; portanto, odeio o orgulho e a arrogância, a corrupção e as palavras perversas.

[[v20-8-14]]

^<<v20-8-14,14>>^ O bom senso e o sucesso me pertencem, o discernimento e o poder são meus.

[[v20-8-15]]

^<<v20-8-15,15>>^ Graças a mim, os reis governam e as autoridades emitem decretos justos.

[[v20-8-16]]

^<<v20-8-16,16>>^ Com minha ajuda, as autoridades lideram e os nobres julgam com justiça.

[[v20-8-17]]

^<<v20-8-17,17>>^ "Amo os que me amam; os que me procuram por certo me encontrarão.

[[v20-8-18]]

^<<v20-8-18,18>>^ Tenho riquezas e honra, bens duradouros e justiça.

[[v20-8-19]]

^<<v20-8-19,19>>^ Minha dádiva vale mais que ouro, mais que ouro puro; meu rendimento é melhor que a fina prata.

[[v20-8-20]]

^<<v20-8-20,20>>^ Ando em retidão, nos caminhos da justiça.

[[v20-8-21]]

^<<v20-8-21,21>>^ Os que me amam recebem riquezas como herança; sim, encherei seus tesouros!

[[v20-8-22]]

^<<v20-8-22,22>>^ "O SENHOR me estabeleceu desde o princípio, antes de criar qualquer outra coisa.

[[v20-8-23]]

^<<v20-8-23,23>>^ Fui designada desde eras passadas, logo no início, antes de a terra existir.

[[v20-8-24]]

^<<v20-8-24,24>>^ Nasci antes que os oceanos fossem criados, antes que a água brotasse de suas fontes.

[[v20-8-25]]

^<<v20-8-25,25>>^ Nasci antes de serem formados os montes, antes de existirem as colinas,

[[v20-8-26]]

^<<v20-8-26,26>>^ quando ele ainda não havia feito a terra e os campos, nem o primeiro punhado de terra.

[[v20-8-27]]

^<<v20-8-27,27>>^ Eu estava lá quando ele estabeleceu o céu, quando traçou o horizonte sobre os oceanos.

[[v20-8-28]]

^<<v20-8-28,28>>^ Estava lá quando ele pôs as nuvens no alto, quando estabeleceu fontes nas profundezas da terra.

[[v20-8-29]]

^<<v20-8-29,29>>^ Estava lá quando ele determinou os limites do mar, para que não avançasse além de suas divisas. E, quando ele demarcou os alicerces da terra,

[[v20-8-30]]

^<<v20-8-30,30>>^ eu estava ao seu lado como arquiteta. Eu era sua alegria constante, sempre exultando em sua presença.

[[v20-8-31]]

^<<v20-8-31,31>>^ Como me alegrei com o mundo que ele criou! Como exultei com a humanidade!

[[v20-8-32]]

^<<v20-8-32,32>>^ "Por isso, meus filhos, ouçam-me, pois todos que seguem meus caminhos são felizes.

[[v20-8-33]]

^<<v20-8-33,33>>^ Ouçam minha instrução e sejam sábios; não a desprezem.

[[v20-8-34]]

^<<v20-8-34,34>>^ Felizes os que me ouvem, que ficam à minha porta todos os dias, esperando por mim na entrada de minha casa!

[[v20-8-35]]

^<<v20-8-35,35>>^ Pois quem me encontra, encontra vida e recebe o favor do SENHOR.

[[v20-8-36]]

^<<v20-8-36,36>>^ Quem não me encontra, prejudica a si mesmo; todos que me odeiam amam a morte".

'''

xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[&#60; Capítulo Anterior] | <<v20-8-0,Topo>> | xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[Próximo Capítulo &#62;]