include::./index.adoc[]

[[v20-12-0]]
=== Provérbios, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v20-12-1]]

^<<v20-12-1,1>>^ Para aprender, é preciso amar a disciplina; é estupidez odiar a repreensão.

[[v20-12-2]]

^<<v20-12-2,2>>^ O SENHOR aprova a pessoa de bem, mas condena quem planeja o mal.

[[v20-12-3]]

^<<v20-12-3,3>>^ A perversidade nunca traz estabilidade, mas a raiz dos justos permanecerá firme.

[[v20-12-4]]

^<<v20-12-4,4>>^ A mulher virtuosa coroa de honra seu marido, mas a que age vergonhosamente é como câncer em seus ossos.

[[v20-12-5]]

^<<v20-12-5,5>>^ Os planos do justo são corretos, mas os conselhos do perverso são traiçoeiros.

[[v20-12-6]]

^<<v20-12-6,6>>^ As palavras do perverso são emboscada mortal, mas as palavras dos justos salvam vidas.

[[v20-12-7]]

^<<v20-12-7,7>>^ Os perversos morrem e desaparecem, mas a família dos justos permanece firme.

[[v20-12-8]]

^<<v20-12-8,8>>^ O sensato recebe elogios, mas o perverso de coração é desprezado.

[[v20-12-9]]

^<<v20-12-9,9>>^ É melhor ser uma pessoa simples e ter quem a ajude que aparentar ser quem não é e não ter o que comer.

[[v20-12-10]]

^<<v20-12-10,10>>^ O justo cuida de seus animais, mas os perversos são sempre cruéis.

[[v20-12-11]]

^<<v20-12-11,11>>^ Quem trabalha com dedicação tem fartura de alimento; quem corre atrás de fantasias não tem juízo.

[[v20-12-12]]

^<<v20-12-12,12>>^ Os ladrões invejam o despojo uns dos outros, mas os justos estão bem arraigados e florescem.

[[v20-12-13]]

^<<v20-12-13,13>>^ O perverso é apanhado na armadilha das próprias palavras, mas o justo escapa dessa aflição.

[[v20-12-14]]

^<<v20-12-14,14>>^ As palavras sábias produzem muitos benefícios, e o trabalho árduo é recompensado.

[[v20-12-15]]

^<<v20-12-15,15>>^ O insensato pensa que sua conduta é correta, mas o sábio dá ouvidos aos conselhos.

[[v20-12-16]]

^<<v20-12-16,16>>^ O insensato se ira com facilidade, mas o sábio ignora a ofensa.

[[v20-12-17]]

^<<v20-12-17,17>>^ A testemunha honesta diz a verdade; a testemunha falsa conta mentiras.

[[v20-12-18]]

^<<v20-12-18,18>>^ Os comentários de algumas pessoas ferem, mas as palavras dos sábios trazem cura.

[[v20-12-19]]

^<<v20-12-19,19>>^ Palavras verdadeiras resistem à prova do tempo, mas as mentiras logo ficam evidentes.

[[v20-12-20]]

^<<v20-12-20,20>>^ O engano enche o coração dos que tramam o mal; a alegria enche o coração dos que promovem a paz.

[[v20-12-21]]

^<<v20-12-21,21>>^ Nenhum mal vem sobre o justo, mas os perversos enfrentam todo tipo de dificuldade.

[[v20-12-22]]

^<<v20-12-22,22>>^ Os lábios mentirosos são detestáveis para o SENHOR, mas os que dizem a verdade lhe trazem alegria.

[[v20-12-23]]

^<<v20-12-23,23>>^ O sábio não se gaba de seu conhecimento, mas os tolos mostram a todos sua insensatez.

[[v20-12-24]]

^<<v20-12-24,24>>^ Quem trabalha com dedicação chega a ser líder, mas o preguiçoso se torna escravo.

[[v20-12-25]]

^<<v20-12-25,25>>^ A preocupação deprime a pessoa, mas uma palavra de incentivo a anima.

[[v20-12-26]]

^<<v20-12-26,26>>^ O justo dá bons conselhos a seus amigos, mas os perversos os desencaminham.

[[v20-12-27]]

^<<v20-12-27,27>>^ O preguiçoso nem mesmo cozinha o animal que caçou, mas o que trabalha com dedicação valoriza tudo que possui.

[[v20-12-28]]

^<<v20-12-28,28>>^ O caminho dos justos conduz à vida; é uma estrada que não leva à morte.

'''

xref:020-proverbios/020-proverbios-011.adoc#v20-11-0[&#60; Capítulo Anterior] | <<v20-12-0,Topo>> | xref:020-proverbios/020-proverbios-013.adoc#v20-13-0[Próximo Capítulo &#62;]