include::./index.adoc[]

[[v20-11-0]]
=== Provérbios, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v20-11-1]]

^<<v20-11-1,1>>^ O uso de balanças desonestas é detestável para o SENHOR, mas ele se alegra com pesos exatos.

[[v20-11-2]]

^<<v20-11-2,2>>^ O orgulho leva à desgraça, mas com a humildade vem a sabedoria.

[[v20-11-3]]

^<<v20-11-3,3>>^ A honestidade guia os justos; a desonestidade destrói os desleais.

[[v20-11-4]]

^<<v20-11-4,4>>^ As riquezas de nada ajudarão no dia do juízo, mas uma vida justa livra da morte.

[[v20-11-5]]

^<<v20-11-5,5>>^ A integridade dirige os passos do justo, mas o peso do pecado cai sob os perversos.

[[v20-11-6]]

^<<v20-11-6,6>>^ A justiça dos justos os livra; a ambição dos desleais os apanha numa armadilha.

[[v20-11-7]]

^<<v20-11-7,7>>^ Quando o perverso morre, sua esperança morre com ele, pois confiou na própria força.

[[v20-11-8]]

^<<v20-11-8,8>>^ O justo é salvo da angústia, mas o perverso a recebe em lugar dele.

[[v20-11-9]]

^<<v20-11-9,9>>^ O hipócrita, com suas palavras, destrói seus amigos, mas o conhecimento livra os justos.

[[v20-11-10]]

^<<v20-11-10,10>>^ A cidade inteira comemora o sucesso dos justos; todos gritam de alegria quando morrem os perversos.

[[v20-11-11]]

^<<v20-11-11,11>>^ A cidade prospera pelos benefícios que os justos trazem, mas as palavras dos perversos a destroem.

[[v20-11-12]]

^<<v20-11-12,12>>^ É falta de bom senso desprezar o próximo; a pessoa sensata permanece calada.

[[v20-11-13]]

^<<v20-11-13,13>>^ O fofoqueiro espalha segredos, mas a pessoa confiável sabe guardar confidências.

[[v20-11-14]]

^<<v20-11-14,14>>^ Sem uma liderança sábia, a nação cai; ter muitos conselheiros lhe dá segurança.

[[v20-11-15]]

^<<v20-11-15,15>>^ Quem aceita ser fiador terá problemas; quem evita esse compromisso está seguro.

[[v20-11-16]]

^<<v20-11-16,16>>^ A mulher bondosa ganha respeito; tudo que os homens cruéis obtêm é riqueza.

[[v20-11-17]]

^<<v20-11-17,17>>^ Quem faz o bem beneficia a si mesmo; quem pratica o mal só se prejudica.

[[v20-11-18]]

^<<v20-11-18,18>>^ A riqueza do perverso dura apenas um momento, mas a recompensa do justo é duradoura.

[[v20-11-19]]

^<<v20-11-19,19>>^ O justo encontra a vida; o perverso encontra a morte.

[[v20-11-20]]

^<<v20-11-20,20>>^ Os perversos de coração são detestáveis para o SENHOR, mas ele se alegra com os que andam em integridade.

[[v20-11-21]]

^<<v20-11-21,21>>^ O perverso certamente será castigado, mas os justos serão poupados.

[[v20-11-22]]

^<<v20-11-22,22>>^ A mulher bonita, mas indiscreta, é como anel de ouro em focinho de porco.

[[v20-11-23]]

^<<v20-11-23,23>>^ Os justos têm a expectativa de uma recompensa, enquanto os perversos só podem esperar o juízo.

[[v20-11-24]]

^<<v20-11-24,24>>^ Quem dá com generosidade se torna mais rico, mas o mesquinho perde tudo.

[[v20-11-25]]

^<<v20-11-25,25>>^ O generoso prospera; quem revigora outros será revigorado.

[[v20-11-26]]

^<<v20-11-26,26>>^ O povo amaldiçoa quem esconde os cereais, mas abençoa quem os vende no tempo de necessidade.

[[v20-11-27]]

^<<v20-11-27,27>>^ Quem procura o bem encontra favor; quem procura o mal será encontrado por ele.

[[v20-11-28]]

^<<v20-11-28,28>>^ Quem confia em seu dinheiro cairá, mas o justo floresce como a verde folhagem.

[[v20-11-29]]

^<<v20-11-29,29>>^ Quem causa problemas à família herda o vento; o insensato se torna servo do sábio.

[[v20-11-30]]

^<<v20-11-30,30>>^ O fruto do justo é árvore de vida; o sábio conquista pessoas.

[[v20-11-31]]

^<<v20-11-31,31>>^ Se o justo recebe o que merece aqui na terra, quanto mais o pecador perverso.

'''

xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[&#60; Capítulo Anterior] | <<v20-11-0,Topo>> | xref:020-proverbios/020-proverbios-012.adoc#v20-12-0[Próximo Capítulo &#62;]