include::./index.adoc[]

[[v20-18-0]]
=== Provérbios, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v20-18-1]]

^<<v20-18-1,1>>^ Quem vive isolado se preocupa apenas consigo e rejeita todo bom senso.

[[v20-18-2]]

^<<v20-18-2,2>>^ O tolo não se interessa pelo entendimento; só quer saber de expressar suas opiniões.

[[v20-18-3]]

^<<v20-18-3,3>>^ A prática do mal resulta em desonra; o comportamento vergonhoso causa desprezo.

[[v20-18-4]]

^<<v20-18-4,4>>^ Palavras sábias são como águas profundas; a sabedoria flui do sábio como riacho transbordante.

[[v20-18-5]]

^<<v20-18-5,5>>^ Não é certo absolver o culpado nem negar justiça ao inocente.

[[v20-18-6]]

^<<v20-18-6,6>>^ As palavras do tolo o envolvem em brigas; ele pede para receber uma surra.

[[v20-18-7]]

^<<v20-18-7,7>>^ A boca do tolo é sua ruína; ele cai na armadilha dos próprios lábios.

[[v20-18-8]]

^<<v20-18-8,8>>^ Calúnias são petiscos saborosos que descem até o íntimo de quem ouve.

[[v20-18-9]]

^<<v20-18-9,9>>^ Quem é relaxado em seu trabalho causa tanto estrago quanto aquele que destrói.

[[v20-18-10]]

^<<v20-18-10,10>>^ O nome do SENHOR é fortaleza segura; o justo corre para ele e fica protegido.

[[v20-18-11]]

^<<v20-18-11,11>>^ O rico vê sua riqueza como uma cidade fortificada; imagina que é uma muralha alta e segura.

[[v20-18-12]]

^<<v20-18-12,12>>^ A arrogância precede a destruição; a humildade precede a honra.

[[v20-18-13]]

^<<v20-18-13,13>>^ Falar sem antes ouvir os fatos é vergonhoso e insensato.

[[v20-18-14]]

^<<v20-18-14,14>>^ O espírito da pessoa sustenta seu corpo enfermo, mas quem pode suportar o espírito abatido?

[[v20-18-15]]

^<<v20-18-15,15>>^ Quem tem discernimento está sempre pronto a aprender; seus ouvidos estão abertos para o conhecimento.

[[v20-18-16]]

^<<v20-18-16,16>>^ As portas se abrem para quem dá presentes; eles dão acesso a pessoas importantes.

[[v20-18-17]]

^<<v20-18-17,17>>^ Quem fala primeiro no tribunal parece ter razão, até que seu oponente comece a lhe fazer perguntas.

[[v20-18-18]]

^<<v20-18-18,18>>^ Lançar sortes acaba com discussões e resolve contendas entre adversários poderosos.

[[v20-18-19]]

^<<v20-18-19,19>>^ É mais difícil reconquistar um amigo ofendido que uma cidade fortificada; as discussões separam amigos como um portão trancado.

[[v20-18-20]]

^<<v20-18-20,20>>^ As palavras sábias saciam como uma boa refeição; as palavras certas dão satisfação.

[[v20-18-21]]

^<<v20-18-21,21>>^ A língua tem poder para trazer morte ou vida; quem gosta de falar arcará com as consequências.

[[v20-18-22]]

^<<v20-18-22,22>>^ O homem que encontra uma esposa encontra um bem precioso e recebe o favor do SENHOR.

[[v20-18-23]]

^<<v20-18-23,23>>^ O pobre suplica por misericórdia; o rico responde com insultos.

[[v20-18-24]]

^<<v20-18-24,24>>^ Alguns que se dizem amigos destroem uns aos outros, mas o verdadeiro amigo é mais próximo que um irmão.

'''

xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[&#60; Capítulo Anterior] | <<v20-18-0,Topo>> | xref:020-proverbios/020-proverbios-019.adoc#v20-19-0[Próximo Capítulo &#62;]