include::./index.adoc[]

[[v20-23-0]]
=== Provérbios, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v20-23-1]]

^<<v20-23-1,1>>^ Quando se sentar para comer com uma autoridade, preste atenção a quem está diante de você.

[[v20-23-2]]

^<<v20-23-2,2>>^ Se você costuma comer demais, controle o apetite;

[[v20-23-3]]

^<<v20-23-3,3>>^ não deseje as iguarias que ele lhe oferece, pois talvez queira enganá-lo.

[[v20-23-4]]

^<<v20-23-4,4>>^ Não se desgaste tentando ficar rico; tenha discernimento para saber quando parar.

[[v20-23-5]]

^<<v20-23-5,5>>^ Num piscar de olhos a riqueza desaparecerá; criará asas e voará para longe, como uma águia.

[[v20-23-6]]

^<<v20-23-6,6>>^ Não coma com pessoas mesquinhas, nem deseje suas iguarias.

[[v20-23-7]]

^<<v20-23-7,7>>^ Elas pensam sempre no custo daquilo que oferecem; insistem: "Coma e beba", mas não falam com sinceridade.

[[v20-23-8]]

^<<v20-23-8,8>>^ Você vomitará o pouco que comeu e desperdiçará seus elogios.

[[v20-23-9]]

^<<v20-23-9,9>>^ Não perca tempo falando com o tolo, pois ele despreza até os conselhos mais sensatos.

[[v20-23-10]]

^<<v20-23-10,10>>^ Não mude de lugar os antigos marcadores de divisa; não tome as terras dos órfãos.

[[v20-23-11]]

^<<v20-23-11,11>>^ Pois o Resgatador deles é forte; ele próprio apresentará as acusações contra você.

[[v20-23-12]]

^<<v20-23-12,12>>^ Dedique-se à instrução; ouça atentamente as palavras de conhecimento.

[[v20-23-13]]

^<<v20-23-13,13>>^ Não deixe de disciplinar seus filhos; a vara da disciplina não os matará.

[[v20-23-14]]

^<<v20-23-14,14>>^ Sim, a vara da disciplina pode muito bem salvá-los da morte.

[[v20-23-15]]

^<<v20-23-15,15>>^ Meu filho, se seu coração for sábio, meu coração se alegrará!

[[v20-23-16]]

^<<v20-23-16,16>>^ Sentirei profunda alegria quando seus lábios expressarem o que é certo.

[[v20-23-17]]

^<<v20-23-17,17>>^ Não tenha inveja dos pecadores, mas tema sempre o SENHOR.

[[v20-23-18]]

^<<v20-23-18,18>>^ Você será recompensado por isso; sua esperança não será frustrada.

[[v20-23-19]]

^<<v20-23-19,19>>^ Ouça, meu filho, e seja sábio: mantenha seu coração no rumo certo.

[[v20-23-20]]

^<<v20-23-20,20>>^ Não ande com os beberrões, nem se envolva com os comilões,

[[v20-23-21]]

^<<v20-23-21,21>>^ pois eles caminham para a pobreza e, de tanto dormirem, terão apenas trapos para vestir.

[[v20-23-22]]

^<<v20-23-22,22>>^ Ouça seu pai, que lhe deu vida, e não despreze sua mãe quando ela envelhecer.

[[v20-23-23]]

^<<v20-23-23,23>>^ Adquira a verdade e não a venda; obtenha sabedoria, instrução e discernimento.

[[v20-23-24]]

^<<v20-23-24,24>>^ O pai dos justos tem motivos para se alegrar; é uma grande alegria ter filhos sábios.

[[v20-23-25]]

^<<v20-23-25,25>>^ Portanto, alegre seu pai e sua mãe; que seja feliz aquela que o deu à luz.

[[v20-23-26]]

^<<v20-23-26,26>>^ Meu filho, dê-me seu coração; que seus olhos tenham prazer em seguir meus caminhos.

[[v20-23-27]]

^<<v20-23-27,27>>^ A prostituta é uma cova profunda; a promíscua é perigosa como um poço estreito.

[[v20-23-28]]

^<<v20-23-28,28>>^ Ela se esconde e espera, como ladrão, ansiosa para conduzir mais homens à infidelidade.

[[v20-23-29]]

^<<v20-23-29,29>>^ Quem se sente angustiado e triste? Quem vive brigando e se queixando? Quem sofre ferimentos desnecessários? Quem tem os olhos sempre vermelhos?

[[v20-23-30]]

^<<v20-23-30,30>>^ Aquele que passa horas tomando vinho e experimentando bebidas fortes.

[[v20-23-31]]

^<<v20-23-31,31>>^ Não olhe demoradamente para o vinho, observando quanto ele é vermelho; como brilha no copo e desce suavemente.

[[v20-23-32]]

^<<v20-23-32,32>>^ Pois, no fim, ele morde como cobra venenosa; pica como víbora.

[[v20-23-33]]

^<<v20-23-33,33>>^ Você terá alucinações e dirá coisas sem sentido.

[[v20-23-34]]

^<<v20-23-34,34>>^ Ficará tonto como marinheiro em alto-mar, agarrado ao mastro em meio à tempestade.

[[v20-23-35]]

^<<v20-23-35,35>>^ Dirá: "Bateram em mim, mas não senti; nem percebi quando levei uma surra. Quando acordarei para beber de novo?".

'''

xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[&#60; Capítulo Anterior] | <<v20-23-0,Topo>> | xref:020-proverbios/020-proverbios-024.adoc#v20-24-0[Próximo Capítulo &#62;]