include::./index.adoc[]

[[v20-21-0]]
=== Provérbios, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v20-21-1]]

^<<v20-21-1,1>>^ O coração do rei é como canais de águas controlados pelo SENHOR; ele os conduz para onde quer.

[[v20-21-2]]

^<<v20-21-2,2>>^ Ainda que as pessoas se considerem corretas, o SENHOR examina o coração de cada um.

[[v20-21-3]]

^<<v20-21-3,3>>^ O SENHOR se agrada mais ao fazermos o que é certo e justo do que ao lhe oferecermos sacrifícios.

[[v20-21-4]]

^<<v20-21-4,4>>^ Olhos arrogantes, coração orgulhoso e atos perversos: tudo isso é pecado.

[[v20-21-5]]

^<<v20-21-5,5>>^ Quem planeja bem e trabalha com dedicação prospera; quem se apressa e toma atalhos fica pobre.

[[v20-21-6]]

^<<v20-21-6,6>>^ A riqueza obtida por meio de mentiras é neblina que se dissipa e armadilha mortal.

[[v20-21-7]]

^<<v20-21-7,7>>^ A violência dos perversos os destruirá, pois se recusam a fazer o que é justo.

[[v20-21-8]]

^<<v20-21-8,8>>^ O culpado anda por um caminho tortuoso; o inocente percorre uma estrada reta.

[[v20-21-9]]

^<<v20-21-9,9>>^ É melhor viver sozinho no canto de um sótão que morar com uma esposa briguenta numa bela casa.

[[v20-21-10]]

^<<v20-21-10,10>>^ O perverso deseja o mal e não tem compaixão do próximo.

[[v20-21-11]]

^<<v20-21-11,11>>^ Quando o zombador é castigado, o ingênuo se torna sábio; quando o sábio é instruído, adquire ainda mais conhecimento.

[[v20-21-12]]

^<<v20-21-12,12>>^ Deus, o Justo, sabe o que se passa na casa dos perversos e trará desgraça sobre eles.

[[v20-21-13]]

^<<v20-21-13,13>>^ Quem fecha os ouvidos aos clamores dos pobres será ignorado quando passar necessidade.

[[v20-21-14]]

^<<v20-21-14,14>>^ O presente entregue em segredo acalma a ira; o suborno oferecido às escondidas abranda a fúria.

[[v20-21-15]]

^<<v20-21-15,15>>^ A justiça é alegria para o justo, mas causa pavor nos que praticam o mal.

[[v20-21-16]]

^<<v20-21-16,16>>^ Quem se desvia do caminho da prudência acabará na companhia dos mortos.

[[v20-21-17]]

^<<v20-21-17,17>>^ Quem ama os prazeres ficará pobre; quem ama o vinho e o luxo nunca enriquecerá.

[[v20-21-18]]

^<<v20-21-18,18>>^ Os perversos são castigados em lugar dos justos, e os desleais, em lugar dos honestos.

[[v20-21-19]]

^<<v20-21-19,19>>^ É melhor viver sozinho no deserto que morar com uma esposa briguenta que só sabe reclamar.

[[v20-21-20]]

^<<v20-21-20,20>>^ O sábio possui riqueza e luxo, mas o tolo gasta tudo que tem.

[[v20-21-21]]

^<<v20-21-21,21>>^ Quem busca a justiça e o amor encontra vida, justiça e honra.

[[v20-21-22]]

^<<v20-21-22,22>>^ O sábio conquista a cidade dos fortes e derruba a fortaleza em que eles confiam.

[[v20-21-23]]

^<<v20-21-23,23>>^ Cuide da língua e fique de boca fechada, e você não se meterá em apuros.

[[v20-21-24]]

^<<v20-21-24,24>>^ O zombador é orgulhoso e convencido e age com extrema arrogância.

[[v20-21-25]]

^<<v20-21-25,25>>^ O preguiçoso deseja muitas coisas, mas acaba em ruína, pois suas mãos se recusam a trabalhar.

[[v20-21-26]]

^<<v20-21-26,26>>^ Algumas pessoas cobiçam o tempo todo, mas o justo gosta de repartir o que tem.

[[v20-21-27]]

^<<v20-21-27,27>>^ O sacrifício do perverso é detestável, especialmente quando oferecido com más intenções.

[[v20-21-28]]

^<<v20-21-28,28>>^ A testemunha falsa será morta; a testemunha confiável terá permissão de falar.

[[v20-21-29]]

^<<v20-21-29,29>>^ A teimosia do perverso transparece em seu rosto, mas o justo pensa antes de agir.

[[v20-21-30]]

^<<v20-21-30,30>>^ Não há sabedoria, entendimento, nem conselho humano capaz de resistir ao SENHOR.

[[v20-21-31]]

^<<v20-21-31,31>>^ O cavalo é preparado para o dia da batalha, mas quem dá a vitória é o SENHOR.

'''

xref:020-proverbios/020-proverbios-020.adoc#v20-20-0[&#60; Capítulo Anterior] | <<v20-21-0,Topo>> | xref:020-proverbios/020-proverbios-022.adoc#v20-22-0[Próximo Capítulo &#62;]