include::./index.adoc[]

[[v20-17-0]]
=== Provérbios, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v20-17-1]]

^<<v20-17-1,1>>^ É melhor um pedaço de pão seco e paz que uma casa cheia de banquetes e conflitos.

[[v20-17-2]]

^<<v20-17-2,2>>^ O servo prudente governará sobre o filho que envergonha o pai e terá parte na herança com os filhos de seu senhor.

[[v20-17-3]]

^<<v20-17-3,3>>^ O fogo prova a pureza da prata e do ouro, mas o SENHOR prova o coração.

[[v20-17-4]]

^<<v20-17-4,4>>^ A pessoa má gosta de ouvir maldades; o mentiroso dá atenção a palavras destrutivas.

[[v20-17-5]]

^<<v20-17-5,5>>^ Quem zomba do pobre insulta seu Criador; quem se alegra com a desgraça alheia será castigado.

[[v20-17-6]]

^<<v20-17-6,6>>^ Os netos são coroa de honra para os idosos; os pais são o orgulho de seus filhos.

[[v20-17-7]]

^<<v20-17-7,7>>^ Não convém ao tolo falar com eloquência, e muito menos ao governante mentir.

[[v20-17-8]]

^<<v20-17-8,8>>^ O suborno é como um amuleto da sorte; quem o oferece sempre alcança o que quer.

[[v20-17-9]]

^<<v20-17-9,9>>^ Quem perdoa a ofensa mostra amor, mas quem insiste nela separa amigos.

[[v20-17-10]]

^<<v20-17-10,10>>^ Uma repreensão é mais eficaz para o prudente que cem açoites para o tolo.

[[v20-17-11]]

^<<v20-17-11,11>>^ A pessoa má sempre procura razão para se rebelar, por isso será severamente castigada.

[[v20-17-12]]

^<<v20-17-12,12>>^ É melhor deparar com uma ursa da qual roubaram os filhotes que confrontar um tolo em sua insensatez.

[[v20-17-13]]

^<<v20-17-13,13>>^ Quem paga o bem com o mal sempre terá o mal em sua casa.

[[v20-17-14]]

^<<v20-17-14,14>>^ Começar uma briga é como abrir a comporta de uma represa; portanto, pare antes que irrompa a discussão.

[[v20-17-15]]

^<<v20-17-15,15>>^ Absolver o culpado e condenar o inocente são duas coisas detestáveis para o SENHOR.

[[v20-17-16]]

^<<v20-17-16,16>>^ De nada adianta pagar para instruir o tolo, pois ele não tem vontade de aprender.

[[v20-17-17]]

^<<v20-17-17,17>>^ O amigo é sempre leal, e um irmão nasce na hora da dificuldade.

[[v20-17-18]]

^<<v20-17-18,18>>^ É falta de juízo dar garantia pela dívida de alguém ou aceitar ser fiador de um amigo.

[[v20-17-19]]

^<<v20-17-19,19>>^ Quem gosta de brigar ama o pecado; quem confia em muralhas procura a própria ruína.

[[v20-17-20]]

^<<v20-17-20,20>>^ O coração perverso não prospera; a língua mentirosa se mete em dificuldades.

[[v20-17-21]]

^<<v20-17-21,21>>^ O filho tolo causa tristeza ao pai; não há alegria para o pai de um rebelde.

[[v20-17-22]]

^<<v20-17-22,22>>^ O coração alegre é um bom remédio, mas o espírito abatido consome as forças.

[[v20-17-23]]

^<<v20-17-23,23>>^ O perverso recebe suborno em segredo, para desviar o rumo da justiça.

[[v20-17-24]]

^<<v20-17-24,24>>^ O sensato mantém os olhos fixos na sabedoria, mas os olhos do tolo vagueiam até os confins da terra.

[[v20-17-25]]

^<<v20-17-25,25>>^ O filho tolo causa tristeza a seu pai e amargura àquela que o deu à luz.

[[v20-17-26]]

^<<v20-17-26,26>>^ É errado castigar os justos por serem bons e açoitar os líderes por serem honestos.

[[v20-17-27]]

^<<v20-17-27,27>>^ Quem é verdadeiramente sábio usa poucas palavras; quem tem entendimento controla suas emoções.

[[v20-17-28]]

^<<v20-17-28,28>>^ Até o insensato passa por sábio quando fica calado; de boca fechada, até parece inteligente.

'''

xref:020-proverbios/020-proverbios-016.adoc#v20-16-0[&#60; Capítulo Anterior] | <<v20-17-0,Topo>> | xref:020-proverbios/020-proverbios-018.adoc#v20-18-0[Próximo Capítulo &#62;]