include::./index.adoc[]

[[v20-29-0]]
=== Provérbios, 29
// nvt ?, NVT - Nova Versão Transformadora

[[v20-29-1]]

^<<v20-29-1,1>>^ Quem sempre se recusa a aceitar a repreensão será destruído de repente, sem que possa se recuperar.

[[v20-29-2]]

^<<v20-29-2,2>>^ Quando os justos governam, o povo se alegra; quando os perversos estão no poder, o povo geme.

[[v20-29-3]]

^<<v20-29-3,3>>^ O homem que ama a sabedoria alegra seu pai, mas o que anda com prostitutas desperdiça sua riqueza.

[[v20-29-4]]

^<<v20-29-4,4>>^ O rei justo dá estabilidade à nação, mas o que exige subornos a destrói.

[[v20-29-5]]

^<<v20-29-5,5>>^ Quem bajula os amigos prepara uma armadilha para os pés deles.

[[v20-29-6]]

^<<v20-29-6,6>>^ A pessoa má é pega no laço do próprio pecado, mas o justo escapa e grita de alegria.

[[v20-29-7]]

^<<v20-29-7,7>>^ O justo se preocupa com os direitos dos pobres, mas o perverso não dá a mínima atenção para isso.

[[v20-29-8]]

^<<v20-29-8,8>>^ Os zombadores alvoroçam a cidade inteira, mas os sábios acalmam a ira.

[[v20-29-9]]

^<<v20-29-9,9>>^ Se o sábio levar o insensato ao tribunal, haverá tumulto e zombaria, mas nada se resolverá.

[[v20-29-10]]

^<<v20-29-10,10>>^ Os sanguinários odeiam o íntegro, mas os justos procuram ajudá-lo.

[[v20-29-11]]

^<<v20-29-11,11>>^ O tolo mostra toda a sua ira, mas o sábio a controla em silêncio.

[[v20-29-12]]

^<<v20-29-12,12>>^ Se um governante der atenção aos mentirosos, todos os seus conselheiros serão perversos.

[[v20-29-13]]

^<<v20-29-13,13>>^ O pobre e o opressor têm isto em comum: o SENHOR permite que ambos enxerguem.

[[v20-29-14]]

^<<v20-29-14,14>>^ Se o rei julgar os pobres com justiça, seu trono durará para sempre.

[[v20-29-15]]

^<<v20-29-15,15>>^ A criança que é corrigida se torna sábia, mas o filho indisciplinado envergonha sua mãe.

[[v20-29-16]]

^<<v20-29-16,16>>^ Quando os perversos estão no poder, o pecado se multiplica, mas os justos verão sua queda.

[[v20-29-17]]

^<<v20-29-17,17>>^ Discipline seus filhos, e eles darão paz a seu espírito e alegria a seu coração.

[[v20-29-18]]

^<<v20-29-18,18>>^ O povo que não aceita a orientação divina se corrompe, mas quem obedece à lei é feliz.

[[v20-29-19]]

^<<v20-29-19,19>>^ Para corrigir o servo é preciso mais que palavras; ainda que ele as entenda, não obedecerá.

[[v20-29-20]]

^<<v20-29-20,20>>^ Há mais esperança para o tolo que para alguém que fala sem pensar.

[[v20-29-21]]

^<<v20-29-21,21>>^ O servo mimado desde a infância se tornará rebelde.

[[v20-29-22]]

^<<v20-29-22,22>>^ A pessoa irada provoca conflitos; quem perde a calma facilmente comete muitos pecados.

[[v20-29-23]]

^<<v20-29-23,23>>^ O orgulho termina em humilhação, mas a humildade alcança a honra.

[[v20-29-24]]

^<<v20-29-24,24>>^ Quem ajuda o ladrão prejudica a si mesmo; sob juramento, não ousa testemunhar.

[[v20-29-25]]

^<<v20-29-25,25>>^ Temer as pessoas é uma armadilha perigosa, mas quem confia no SENHOR está seguro.

[[v20-29-26]]

^<<v20-29-26,26>>^ Muitos buscam o favor do governante, mas a justiça vem do SENHOR.

[[v20-29-27]]

^<<v20-29-27,27>>^ O justo despreza o injusto; o perverso despreza o íntegro.

'''

xref:020-proverbios/020-proverbios-028.adoc#v20-28-0[&#60; Capítulo Anterior] | <<v20-29-0,Topo>> | xref:020-proverbios/020-proverbios-030.adoc#v20-30-0[Próximo Capítulo &#62;]