include::./index.adoc[]

[[v40-24-0]]
=== Mateus, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v40-24-1]]

^<<v40-24-1,1>>^ Quando Jesus saía da área do templo, seus discípulos lhe chamaram a atenção para as diversas construções do edifício.

[[v40-24-2]]

^<<v40-24-2,2>>^ Ele, porém, disse: "Estão vendo todas estas construções? Eu lhes digo a verdade: elas serão completamente demolidas. Não restará pedra sobre pedra!".

[[v40-24-3]]

^<<v40-24-3,3>>^ Mais tarde, Jesus sentou-se no monte das Oliveiras. Seus discípulos vieram até ele em particular e perguntaram: "Diga-nos, quando isso tudo vai acontecer? Que sinal indicará sua volta e o fim dos tempos?".

[[v40-24-4]]

^<<v40-24-4,4>>^ Jesus respondeu: "Não deixem que ninguém os engane,

[[v40-24-5]]

^<<v40-24-5,5>>^ pois muitos virão em meu nome, dizendo: ‘Eu sou o Cristo’, e enganarão muitos.

[[v40-24-6]]

^<<v40-24-6,6>>^ Vocês ouvirão falar de guerras e ameaças de guerras, mas não entrem em pânico. Sim, é necessário que essas coisas ocorram, mas ainda não será o fim.

[[v40-24-7]]

^<<v40-24-7,7>>^ Uma nação guerreará contra a outra, e um reino contra o outro. Haverá fome e terremotos em várias partes do mundo.

[[v40-24-8]]

^<<v40-24-8,8>>^ Tudo isso, porém, será apenas o começo das dores de parto.

[[v40-24-9]]

^<<v40-24-9,9>>^ "Então vocês serão presos, perseguidos e mortos. Por minha causa, serão odiados em todo o mundo.

[[v40-24-10]]

^<<v40-24-10,10>>^ Muitos se afastarão de mim, e trairão e odiarão uns aos outros.

[[v40-24-11]]

^<<v40-24-11,11>>^ Falsos profetas surgirão em grande número e enganarão muitos.

[[v40-24-12]]

^<<v40-24-12,12>>^ O pecado aumentará e o amor de muitos esfriará,

[[v40-24-13]]

^<<v40-24-13,13>>^ mas quem se mantiver firme até o fim será salvo.

[[v40-24-14]]

^<<v40-24-14,14>>^ As boas-novas a respeito do reino serão anunciadas em todo o mundo, para que todas as nações as ouçam; então, virá o fim.

[[v40-24-15]]

^<<v40-24-15,15>>^ "Chegará o dia em que vocês verão aquilo de que o profeta Daniel falou, a ‘terrível profanação’ que será colocada no lugar santo. (Leitor, preste atenção!)

[[v40-24-16]]

^<<v40-24-16,16>>^ Quem estiver na Judeia, fuja para os montes.

[[v40-24-17]]

^<<v40-24-17,17>>^ Quem estiver no terraço no alto da casa, não desça para pegar suas coisas.

[[v40-24-18]]

^<<v40-24-18,18>>^ Quem estiver no campo, não volte nem para pegar o manto.

[[v40-24-19]]

^<<v40-24-19,19>>^ Que terríveis serão aqueles dias para as grávidas e para as mães que estiverem amamentando!

[[v40-24-20]]

^<<v40-24-20,20>>^ Orem para que a fuga de vocês não seja no inverno nem no sábado,

[[v40-24-21]]

^<<v40-24-21,21>>^ pois haverá mais angústia que em qualquer outra ocasião desde o começo do mundo, e nunca mais haverá angústia tão grande.

[[v40-24-22]]

^<<v40-24-22,22>>^ De fato, se o tempo de calamidade não tivesse sido limitado, ninguém sobreviveria, mas esse tempo foi limitado por causa dos escolhidos.

[[v40-24-23]]

^<<v40-24-23,23>>^ "Portanto, se alguém lhes disser: ‘Vejam, aqui está o Cristo!’ ou ‘Ali está ele!’, não acreditem,

[[v40-24-24]]

^<<v40-24-24,24>>^ pois falsos cristos e falsos profetas surgirão e realizarão grandes sinais e maravilhas a fim de enganar, se possível, até os escolhidos.

[[v40-24-25]]

^<<v40-24-25,25>>^ Vejam que eu os avisei disso de antemão.

[[v40-24-26]]

^<<v40-24-26,26>>^ "Portanto, se alguém lhes disser: ‘Ele está no deserto!’, nem se deem ao trabalho de sair para procurá-lo. E se disserem: ‘Está escondido aqui!’, não acreditem.

[[v40-24-27]]

^<<v40-24-27,27>>^ Porque, assim como o relâmpago lampeja no leste e brilha no oeste, assim será a vinda do Filho do Homem.

[[v40-24-28]]

^<<v40-24-28,28>>^ Onde estiver o cadáver, ali se ajuntarão os abutres.

[[v40-24-29]]

^<<v40-24-29,29>>^ "Imediatamente depois da angústia daqueles dias, ‘o sol escurecerá, a lua não dará luz, as estrelas cairão do céu e os poderes dos céus serão abalados’.

[[v40-24-30]]

^<<v40-24-30,30>>^ Então, por fim, aparecerá no céu o sinal da vinda do Filho do Homem, e haverá grande lamentação entre todos os povos da terra. Eles verão o Filho do Homem vindo nas nuvens do céu com poder e grande glória.

[[v40-24-31]]

^<<v40-24-31,31>>^ Ele enviará seus anjos com um forte sopro de trombeta, e eles reunirão os escolhidos de todas as partes do mundo, de uma extremidade à outra do céu.

[[v40-24-32]]

^<<v40-24-32,32>>^ "Agora, aprendam a lição da figueira. Quando os ramos surgem e as folhas começam a brotar, vocês sabem que o verão está próximo.

[[v40-24-33]]

^<<v40-24-33,33>>^ Da mesma forma, quando virem todas essas coisas, saberão que o tempo está muito próximo, à porta.

[[v40-24-34]]

^<<v40-24-34,34>>^ Eu lhes digo a verdade: esta geração certamente não passará até que todas essas coisas tenham acontecido.

[[v40-24-35]]

^<<v40-24-35,35>>^ O céu e a terra desaparecerão, mas as minhas palavras jamais desaparecerão.

[[v40-24-36]]

^<<v40-24-36,36>>^ "Contudo, ninguém sabe o dia nem a hora em que essas coisas acontecerão, nem mesmo os anjos no céu, nem o Filho. Somente o Pai sabe.

[[v40-24-37]]

^<<v40-24-37,37>>^ "Quando o Filho do Homem voltar, será como no tempo de Noé.

[[v40-24-38]]

^<<v40-24-38,38>>^ Nos dias antes do dilúvio, o povo seguia sua rotina de banquetes, festas e casamentos, até o dia em que Noé entrou na arca.

[[v40-24-39]]

^<<v40-24-39,39>>^ Não perceberam o que estava para acontecer até que veio o dilúvio e levou todos. Assim será na vinda do Filho do Homem.

[[v40-24-40]]

^<<v40-24-40,40>>^ "Dois homens estarão trabalhando juntos no campo; um será levado, e o outro, deixado.

[[v40-24-41]]

^<<v40-24-41,41>>^ Duas mulheres estarão moendo cereal no moinho; uma será levada, e a outra, deixada.

[[v40-24-42]]

^<<v40-24-42,42>>^ "Portanto, vigiem, pois não sabem em que ocasião o seu Senhor virá.

[[v40-24-43]]

^<<v40-24-43,43>>^ Entendam isto: se o dono da casa soubesse exatamente a que horas viria o ladrão, ficaria atento e não permitiria que a casa fosse arrombada.

[[v40-24-44]]

^<<v40-24-44,44>>^ Estejam também sempre preparados, pois o Filho do Homem virá quando menos esperam.

[[v40-24-45]]

^<<v40-24-45,45>>^ "O servo fiel e sensato é aquele a quem seu senhor encarrega de gerir os outros servos da casa e alimentá-los.

[[v40-24-46]]

^<<v40-24-46,46>>^ Se o senhor voltar e constatar que o servo fez um bom trabalho, haverá recompensa.

[[v40-24-47]]

^<<v40-24-47,47>>^ Eu lhes digo a verdade: ele colocará todos os seus bens sob os cuidados desse servo.

[[v40-24-48]]

^<<v40-24-48,48>>^ O que acontecerá, porém, se o servo for mau e pensar: ‘Meu senhor não voltará tão cedo’,

[[v40-24-49]]

^<<v40-24-49,49>>^ e começar a espancar os outros servos, a comer e a beber e se embriagar?

[[v40-24-50]]

^<<v40-24-50,50>>^ O senhor desse servo voltará em dia que não se espera e em hora que não se conhece,

[[v40-24-51]]

^<<v40-24-51,51>>^ cortará o servo ao meio e lhe dará o mesmo destino dos hipócritas. Ali haverá choro e ranger de dentes."

'''

xref:040-mateus/040-mateus-023.adoc#v40-23-0[&#60; Capítulo Anterior] | <<v40-24-0,Topo>> | xref:040-mateus/040-mateus-025.adoc#v40-25-0[Próximo Capítulo &#62;]