include::./index.adoc[]

[[v40-18-0]]
=== Mateus, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v40-18-1]]

^<<v40-18-1,1>>^ Nessa ocasião, os discípulos vieram a Jesus e perguntaram: "Afinal, quem é o maior no reino dos céus?".

[[v40-18-2]]

^<<v40-18-2,2>>^ Então Jesus chamou uma criança pequena e a colocou no meio deles.

[[v40-18-3]]

^<<v40-18-3,3>>^ Em seguida, disse: "Eu lhes digo a verdade: a menos que vocês se convertam e se tornem como crianças, jamais entrarão no reino dos céus.

[[v40-18-4]]

^<<v40-18-4,4>>^ Quem se torna humilde como esta criança é o maior no reino dos céus,

[[v40-18-5]]

^<<v40-18-5,5>>^ e quem recebe uma criança como esta em meu nome recebe a mim."

[[v40-18-6]]

^<<v40-18-6,6>>^ "Mas, se alguém fizer cair em pecado um destes pequeninos que em mim confiam, teria sido melhor ter amarrado uma grande pedra de moinho ao pescoço e se afogado nas profundezas do mar.

[[v40-18-7]]

^<<v40-18-7,7>>^ "Quanto sofrimento haverá no mundo por causa das tentações para o pecado! Ainda que elas sejam inevitáveis, aquele que as provoca terá sofrimento ainda maior.

[[v40-18-8]]

^<<v40-18-8,8>>^ Portanto, se sua mão ou seu pé o faz pecar, corte-o e jogue-o fora. É melhor entrar na vida eterna com apenas uma das mãos ou apenas um dos pés que ser lançado no fogo eterno com as duas mãos e os dois pés.

[[v40-18-9]]

^<<v40-18-9,9>>^ E, se seu olho o faz pecar, arranque-o e jogue-o fora. É melhor entrar na vida eterna com apenas um dos olhos que ser lançado no inferno de fogo com os dois olhos.

[[v40-18-10]]

^<<v40-18-10,10>>^ "Tomem cuidado para não desprezar nenhum destes pequeninos. Pois eu lhes digo que, no céu, os anjos deles estão sempre na presença de meu Pai celestial.

[[v40-18-11]]

^<<v40-18-11,11>>^ E o Filho do Homem veio para salvar os que estão perdidos."

[[v40-18-12]]

^<<v40-18-12,12>>^ "Se um homem tiver cem ovelhas e uma delas se perder, o que vocês acham que ele fará? Não deixará as outras noventa e nove nos montes e sairá à procura da perdida?

[[v40-18-13]]

^<<v40-18-13,13>>^ E, se a encontrar, eu lhes digo a verdade: ele se alegrará por causa dela mais que pelas noventa e nove que não se perderam.

[[v40-18-14]]

^<<v40-18-14,14>>^ Da mesma forma, não é da vontade de meu Pai, no céu, que nenhum destes pequeninos se perca."

[[v40-18-15]]

^<<v40-18-15,15>>^ "Se um irmão pecar contra você, fale com ele em particular e chame-lhe a atenção para o erro. Se ele o ouvir, você terá recuperado seu irmão.

[[v40-18-16]]

^<<v40-18-16,16>>^ Mas, se ele não o ouvir, leve consigo um ou dois outros e fale com ele novamente, para que tudo que você disser seja confirmado por duas ou três testemunhas.

[[v40-18-17]]

^<<v40-18-17,17>>^ Se ainda assim ele se recusar a ouvir, apresente o caso à igreja. Então, se ele não aceitar nem mesmo a decisão da igreja, trate-o como gentio ou como cobrador de impostos.

[[v40-18-18]]

^<<v40-18-18,18>>^ "Eu lhes digo a verdade: o que vocês ligarem na terra terá sido ligado no céu, e o que desligarem na terra terá sido desligado no céu.

[[v40-18-19]]

^<<v40-18-19,19>>^ "Também lhes digo que, se dois de vocês concordarem aqui na terra a respeito de qualquer coisa que pedirem, meu Pai, no céu, os atenderá.

[[v40-18-20]]

^<<v40-18-20,20>>^ Pois, onde dois ou três se reúnem em meu nome, eu estou no meio deles".

[[v40-18-21]]

^<<v40-18-21,21>>^ Então Pedro se aproximou de Jesus e perguntou: "Senhor, quantas vezes devo perdoar alguém que peca contra mim? Sete vezes?".

[[v40-18-22]]

^<<v40-18-22,22>>^ Jesus respondeu: "Não sete vezes, mas setenta vezes sete.

[[v40-18-23]]

^<<v40-18-23,23>>^ "Portanto, o reino dos céus pode ser comparado a um senhor que decidiu pôr em dia as contas com os servos que lhe deviam.

[[v40-18-24]]

^<<v40-18-24,24>>^ No decorrer do processo, trouxeram diante dele um servo que lhe devia sessenta milhões de moedas.

[[v40-18-25]]

^<<v40-18-25,25>>^ Uma vez que o homem não tinha como pagar, o senhor ordenou que ele, sua esposa, seus filhos e todos os seus bens fossem vendidos para quitar a dívida.

[[v40-18-26]]

^<<v40-18-26,26>>^ "O homem se curvou diante do senhor e suplicou: ‘Por favor, tenha paciência comigo, e eu pagarei tudo’.

[[v40-18-27]]

^<<v40-18-27,27>>^ O senhor teve compaixão dele, soltou-o e perdoou-lhe a dívida.

[[v40-18-28]]

^<<v40-18-28,28>>^ "No entanto, quando o servo saiu da presença do senhor, foi procurar outro servo que trabalhava com ele e que lhe devia cem moedas de prata. Agarrou-o pelo pescoço e exigiu que ele pagasse de imediato.

[[v40-18-29]]

^<<v40-18-29,29>>^ "O servo se curvou diante dele e suplicou: ‘Tenha paciência comigo, e eu pagarei tudo’.

[[v40-18-30]]

^<<v40-18-30,30>>^ O credor, porém, não estava disposto a esperar. Mandou que o homem fosse lançado na prisão até que tivesse pago toda a dívida.

[[v40-18-31]]

^<<v40-18-31,31>>^ "Quando outros servos, companheiros dele, viram isso, ficaram muito tristes. Foram ao senhor e lhe contaram tudo que havia acontecido.

[[v40-18-32]]

^<<v40-18-32,32>>^ Então o senhor chamou o homem cuja dívida ele havia perdoado e disse: ‘Servo mau! Eu perdoei sua imensa dívida porque você me implorou.

[[v40-18-33]]

^<<v40-18-33,33>>^ Acaso não devia ter misericórdia de seu companheiro, como tive misericórdia de você?’.

[[v40-18-34]]

^<<v40-18-34,34>>^ E, irado, o senhor mandou o homem à prisão para ser torturado até que lhe pagasse toda a dívida.

[[v40-18-35]]

^<<v40-18-35,35>>^ "Assim também meu Pai celestial fará com vocês caso se recusem a perdoar de coração a seus irmãos".

'''

xref:040-mateus/040-mateus-017.adoc#v40-17-0[&#60; Capítulo Anterior] | <<v40-18-0,Topo>> | xref:040-mateus/040-mateus-019.adoc#v40-19-0[Próximo Capítulo &#62;]