include::./index.adoc[]

[[v40-19-0]]
=== Mateus, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v40-19-1]]

^<<v40-19-1,1>>^ Quando Jesus terminou de dizer essas coisas, deixou a Galileia e foi para a região da Judeia, a leste do rio Jordão.

[[v40-19-2]]

^<<v40-19-2,2>>^ Grandes multidões o seguiram, e ele curou os enfermos.

[[v40-19-3]]

^<<v40-19-3,3>>^ Alguns fariseus apareceram e tentaram apanhar Jesus numa armadilha, perguntando: "Deve-se permitir que um homem se divorcie de sua mulher por qualquer motivo?".

[[v40-19-4]]

^<<v40-19-4,4>>^ "Vocês não leram as Escrituras?", respondeu Jesus. "Elas registram que, desde o princípio, o Criador ‘os fez homem e mulher’

[[v40-19-5]]

^<<v40-19-5,5>>^ e disse: ‘Por isso o homem deixa pai e mãe e se une à sua mulher, e os dois se tornam um só’.

[[v40-19-6]]

^<<v40-19-6,6>>^ Uma vez que já não são dois, mas um só, que ninguém separe o que Deus uniu."

[[v40-19-7]]

^<<v40-19-7,7>>^ Eles perguntaram: "Então por que Moisés disse na lei que o homem poderia dar à esposa um certificado de divórcio e mandá-la embora?".

[[v40-19-8]]

^<<v40-19-8,8>>^ Jesus respondeu: "Moisés permitiu o divórcio apenas como concessão, pois o coração de vocês é duro, mas não era esse o propósito original.

[[v40-19-9]]

^<<v40-19-9,9>>^ E eu lhes digo o seguinte: quem se divorciar de sua esposa, o que só poderá fazer em caso de imoralidade, e se casar com outra, cometerá adultério".

[[v40-19-10]]

^<<v40-19-10,10>>^ Os discípulos de Jesus disseram: "Se essa é a condição do homem em relação à sua mulher, é melhor não casar!".

[[v40-19-11]]

^<<v40-19-11,11>>^ "Nem todos têm como aceitar esse ensino", disse Jesus. "Só aqueles que recebem a ajuda de Deus.

[[v40-19-12]]

^<<v40-19-12,12>>^ Alguns nascem eunucos, alguns foram feitos eunucos por outros e alguns a si mesmos se fazem eunucos por causa do reino dos céus. Quem puder, que aceite isso."

[[v40-19-13]]

^<<v40-19-13,13>>^ Certo dia, trouxeram crianças para que Jesus pusesse as mãos sobre elas e orasse em seu favor, mas os discípulos repreendiam aqueles que as traziam.

[[v40-19-14]]

^<<v40-19-14,14>>^ Jesus, porém, disse: "Deixem que as crianças venham a mim. Não as impeçam, pois o reino dos céus pertence aos que são como elas".

[[v40-19-15]]

^<<v40-19-15,15>>^ Então, antes de ir embora, pôs as mãos sobre a cabeça delas e as abençoou.

[[v40-19-16]]

^<<v40-19-16,16>>^ Um homem veio a Jesus com a seguinte pergunta: "Mestre, que boas ações devo fazer para obter a vida eterna?".

[[v40-19-17]]

^<<v40-19-17,17>>^ "Por que você me pergunta sobre o que é bom?", perguntou Jesus. "Há somente um que é bom. Se você deseja entrar na vida eterna, guarde os mandamentos."

[[v40-19-18]]

^<<v40-19-18,18>>^ "Quais?", perguntou o homem. Jesus respondeu: "Não mate. Não cometa adultério. Não roube. Não dê falso testemunho.

[[v40-19-19]]

^<<v40-19-19,19>>^ Honre seu pai e sua mãe. Ame o seu próximo como a si mesmo".

[[v40-19-20]]

^<<v40-19-20,20>>^ "Tenho obedecido a todos esses mandamentos", disse o homem. "O que mais devo fazer?"

[[v40-19-21]]

^<<v40-19-21,21>>^ Jesus respondeu: "Se você quer ser perfeito, vá, venda todos os seus bens e dê o dinheiro aos pobres. Então você terá um tesouro no céu. Depois, venha e siga-me".

[[v40-19-22]]

^<<v40-19-22,22>>^ Quando o rapaz ouviu isso, foi embora triste, porque tinha muitos bens.

[[v40-19-23]]

^<<v40-19-23,23>>^ Então Jesus disse a seus discípulos: "Eu lhes digo a verdade: é muito difícil um rico entrar no reino dos céus.

[[v40-19-24]]

^<<v40-19-24,24>>^ Digo também: é mais fácil um camelo passar pelo buraco de uma agulha que um rico entrar no reino de Deus".

[[v40-19-25]]

^<<v40-19-25,25>>^ Ao ouvir isso, os discípulos ficaram perplexos e perguntaram: "Então quem pode ser salvo?".

[[v40-19-26]]

^<<v40-19-26,26>>^ Jesus olhou atentamente para eles e respondeu: "Para as pessoas isso é impossível, mas tudo é possível para Deus".

[[v40-19-27]]

^<<v40-19-27,27>>^ Então Pedro disse: "Deixamos tudo para segui-lo. Qual será nossa recompensa?".

[[v40-19-28]]

^<<v40-19-28,28>>^ Jesus respondeu: "Eu lhes garanto que, quando o mundo for renovado e o Filho do Homem se sentar em seu trono glorioso, vocês, que foram meus seguidores, também se sentarão em doze tronos para julgar as doze tribos de Israel.

[[v40-19-29]]

^<<v40-19-29,29>>^ E todos que tiverem deixado casa, irmãos, irmãs, pai, mãe, filhos ou propriedades por minha causa receberão em troca cem vezes mais e herdarão a vida eterna.

[[v40-19-30]]

^<<v40-19-30,30>>^ Contudo, muitos primeiros serão os últimos, e muitos últimos serão os primeiros."

'''

xref:040-mateus/040-mateus-018.adoc#v40-18-0[&#60; Capítulo Anterior] | <<v40-19-0,Topo>> | xref:040-mateus/040-mateus-020.adoc#v40-20-0[Próximo Capítulo &#62;]