include::./index.adoc[]

[[v40-16-0]]
=== Mateus, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v40-16-1]]

^<<v40-16-1,1>>^ Os fariseus e saduceus vieram pôr Jesus à prova, exigindo que lhes mostrasse um sinal do céu.

[[v40-16-2]]

^<<v40-16-2,2>>^ Ele respondeu: "Vocês conhecem o ditado: ‘Céu vermelho ao entardecer, bom tempo amanhã;

[[v40-16-3]]

^<<v40-16-3,3>>^ céu vermelho e sombrio logo cedo, mau tempo o dia todo’. Vocês sabem identificar as condições do tempo no céu, mas não sabem interpretar os sinais dos tempos!

[[v40-16-4]]

^<<v40-16-4,4>>^ Pedem um sinal porque são uma geração perversa e adúltera, mas o único sinal que lhes darei será o sinal do profeta Jonas". Então Jesus os deixou e se retirou.

[[v40-16-5]]

^<<v40-16-5,5>>^ Mais tarde, depois de atravessar o mar, os discípulos descobriram que tinham se esquecido de levar pães.

[[v40-16-6]]

^<<v40-16-6,6>>^ Jesus os advertiu: "Fiquem atentos! Tenham cuidado com o fermento dos fariseus e saduceus".

[[v40-16-7]]

^<<v40-16-7,7>>^ Os discípulos começaram a discutir entre si por que não tinham trazido pão.

[[v40-16-8]]

^<<v40-16-8,8>>^ Ao tomar conhecimento do que falavam, Jesus disse: "Como é pequena a sua fé! Por que vocês discutem entre si sobre a falta de pão?

[[v40-16-9]]

^<<v40-16-9,9>>^ Ainda não entenderam? Não se lembram dos cinco pães para os cinco mil e dos cestos de sobras que recolheram?

[[v40-16-10]]

^<<v40-16-10,10>>^ Nem dos sete pães para os quatro mil e dos cestos grandes de sobras que recolheram?

[[v40-16-11]]

^<<v40-16-11,11>>^ Como não conseguem entender que não estou falando de pão? Repito: tenham cuidado com o fermento dos fariseus e saduceus".

[[v40-16-12]]

^<<v40-16-12,12>>^ Finalmente entenderam que ele não se referia ao fermento do pão, mas ao ensino dos fariseus e saduceus.

[[v40-16-13]]

^<<v40-16-13,13>>^ Quando Jesus chegou à região de Cesareia de Filipe, perguntou a seus discípulos: "Quem as pessoas dizem que o Filho do Homem é?".

[[v40-16-14]]

^<<v40-16-14,14>>^ Eles responderam: "Alguns dizem que o senhor é João Batista; outros, que é Elias; e outros, ainda, que é Jeremias ou um dos profetas".

[[v40-16-15]]

^<<v40-16-15,15>>^ "E vocês?", perguntou ele. "Quem vocês dizem que eu sou?"

[[v40-16-16]]

^<<v40-16-16,16>>^ Simão Pedro respondeu: "O senhor é o Cristo, o Filho do Deus vivo!".

[[v40-16-17]]

^<<v40-16-17,17>>^ Jesus disse: "Que grande privilégio você teve, Simão, filho de João! Foi meu Pai no céu quem lhe revelou isso. Nenhum ser humano saberia por si só.

[[v40-16-18]]

^<<v40-16-18,18>>^ Agora eu lhe digo que você é Pedro, e sobre esta pedra edificarei minha igreja, e as forças da morte não a conquistarão.

[[v40-16-19]]

^<<v40-16-19,19>>^ Eu lhe darei as chaves do reino dos céus. O que você ligar na terra terá sido ligado no céu, e o que você desligar na terra terá sido desligado no céu".

[[v40-16-20]]

^<<v40-16-20,20>>^ Então ele advertiu a seus discípulos que não dissessem a ninguém que ele era o Cristo.

[[v40-16-21]]

^<<v40-16-21,21>>^ Daquele momento em diante, Jesus começou a falar claramente a seus discípulos que era necessário que ele fosse a Jerusalém e sofresse muitas coisas terríveis nas mãos dos líderes do povo, dos principais sacerdotes e dos mestres da lei. Seria morto, mas no terceiro dia ressuscitaria.

[[v40-16-22]]

^<<v40-16-22,22>>^ Pedro o chamou de lado e começou a repreendê-lo por dizer tais coisas. "Jamais, Senhor!", disse ele. "Isso nunca lhe acontecerá!"

[[v40-16-23]]

^<<v40-16-23,23>>^ Jesus se voltou para Pedro e disse: "Afaste-se de mim, Satanás! Você é uma pedra de tropeço para mim. Considera as coisas apenas do ponto de vista humano, e não da perspectiva de Deus".

[[v40-16-24]]

^<<v40-16-24,24>>^ Então Jesus disse a seus discípulos: "Se alguém quer ser meu seguidor, negue a si mesmo, tome sua cruz e siga-me.

[[v40-16-25]]

^<<v40-16-25,25>>^ Se tentar se apegar à sua vida, a perderá. Mas, se abrir mão de sua vida por minha causa, a encontrará.

[[v40-16-26]]

^<<v40-16-26,26>>^ Que vantagem há em ganhar o mundo inteiro, mas perder a vida? E o que daria o homem em troca de sua vida?

[[v40-16-27]]

^<<v40-16-27,27>>^ Pois o Filho do Homem virá com seus anjos na glória de seu Pai e julgará cada pessoa de acordo com suas ações.

[[v40-16-28]]

^<<v40-16-28,28>>^ Eu lhes digo a verdade: alguns que estão aqui neste momento não morrerão antes de ver o Filho do Homem vindo em seu reino!".

'''

xref:040-mateus/040-mateus-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-mateus/040-mateus-017.adoc#v40-17-0[Próximo Capítulo &#62;]