include::./index.adoc[]

[[v40-25-0]]
=== Mateus, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v40-25-1]]

^<<v40-25-1,1>>^ "Então o reino dos céus será como as dez virgens que pegaram suas lamparinas e saíram para encontrar-se com o noivo.

[[v40-25-2]]

^<<v40-25-2,2>>^ Cinco delas eram insensatas, e cinco, prudentes.

[[v40-25-3]]

^<<v40-25-3,3>>^ As cinco insensatas não levaram óleo suficiente para as lamparinas,

[[v40-25-4]]

^<<v40-25-4,4>>^ mas as outras cinco tiveram o bom senso de levar óleo de reserva.

[[v40-25-5]]

^<<v40-25-5,5>>^ Como o noivo demorou a chegar, todas ficaram sonolentas e adormeceram.

[[v40-25-6]]

^<<v40-25-6,6>>^ "À meia-noite, foram acordadas pelo grito: ‘Vejam, o noivo está chegando! Saiam para recebê-lo!’.

[[v40-25-7]]

^<<v40-25-7,7>>^ "Todas as virgens se levantaram e prepararam suas lamparinas.

[[v40-25-8]]

^<<v40-25-8,8>>^ Então as cinco insensatas pediram às outras: ‘Por favor, deem-nos um pouco de óleo, pois nossas lamparinas estão se apagando’.

[[v40-25-9]]

^<<v40-25-9,9>>^ "As outras, porém, responderam: ‘Não temos o suficiente para todas. Vão e comprem óleo para vocês’.

[[v40-25-10]]

^<<v40-25-10,10>>^ "Quando estavam fora comprando óleo, o noivo chegou. Então as cinco que estavam preparadas entraram com ele no banquete de casamento, e a porta foi trancada.

[[v40-25-11]]

^<<v40-25-11,11>>^ Mais tarde, quando as outras cinco voltaram, ficaram do lado de fora, chamando: ‘Senhor! Senhor! Abra-nos a porta!’.

[[v40-25-12]]

^<<v40-25-12,12>>^ "Mas ele respondeu: ‘A verdade é que não as conheço’.

[[v40-25-13]]

^<<v40-25-13,13>>^ "Portanto, vigiem, pois não sabem o dia nem a hora da volta."

[[v40-25-14]]

^<<v40-25-14,14>>^ "O reino dos céus também pode ser ilustrado com a história de um homem que estava para fazer uma longa viagem. Ele reuniu seus servos e lhes confiou seu dinheiro,

[[v40-25-15]]

^<<v40-25-15,15>>^ dividindo-o de forma proporcional à capacidade deles: ao primeiro entregou cinco talentos; ao segundo, dois talentos; e ao último, um talento. Então foi viajar.

[[v40-25-16]]

^<<v40-25-16,16>>^ "O servo que recebeu cinco talentos começou a investir o dinheiro e ganhou outros cinco.

[[v40-25-17]]

^<<v40-25-17,17>>^ O servo que recebeu dois talentos também se pôs a trabalhar e ganhou outros dois.

[[v40-25-18]]

^<<v40-25-18,18>>^ Mas o servo que recebeu um talento cavou um buraco no chão e ali escondeu o dinheiro de seu senhor.

[[v40-25-19]]

^<<v40-25-19,19>>^ "Depois de muito tempo, o senhor voltou de viagem e os chamou para prestarem contas de como haviam usado o dinheiro.

[[v40-25-20]]

^<<v40-25-20,20>>^ O servo ao qual ele havia confiado cinco talentos se apresentou com mais cinco: ‘O senhor me deu cinco talentos para investir, e eu ganhei mais cinco’.

[[v40-25-21]]

^<<v40-25-21,21>>^ "O senhor disse: ‘Muito bem, meu servo bom e fiel. Você foi fiel na administração dessa quantia pequena, e agora lhe darei muitas outras responsabilidades. Venha celebrar comigo’.

[[v40-25-22]]

^<<v40-25-22,22>>^ "O servo que havia recebido dois talentos se apresentou e disse: ‘O senhor me deu dois talentos para investir, e eu ganhei mais dois’.

[[v40-25-23]]

^<<v40-25-23,23>>^ "O senhor disse: ‘Muito bem, meu servo bom e fiel. Você foi fiel na administração dessa quantia pequena, e agora lhe darei muitas outras responsabilidades. Venha celebrar comigo’.

[[v40-25-24]]

^<<v40-25-24,24>>^ "Por último, o servo que havia recebido um talento veio e disse: ‘Eu sabia que o senhor é homem severo, que colhe onde não plantou e ajunta onde não semeou.

[[v40-25-25]]

^<<v40-25-25,25>>^ Tive medo de perder seu dinheiro, por isso o escondi na terra. Aqui está ele’.

[[v40-25-26]]

^<<v40-25-26,26>>^ "O senhor, porém, respondeu: ‘Servo mau e preguiçoso! Se você sabia que eu colho onde não plantei e ajunto onde não semeei,

[[v40-25-27]]

^<<v40-25-27,27>>^ por que não depositou meu dinheiro? Pelo menos eu teria recebido os juros.

[[v40-25-28]]

^<<v40-25-28,28>>^ "Em seguida, ordenou: ‘Tirem o dinheiro deste servo e deem ao que tem os dez talentos.

[[v40-25-29]]

^<<v40-25-29,29>>^ Pois ao que tem, mais lhe será dado, e terá em grande quantia; mas do que nada tem, mesmo o que não tem lhe será tomado.

[[v40-25-30]]

^<<v40-25-30,30>>^ Agora lancem este servo inútil para fora, na escuridão, onde haverá choro e ranger de dentes’."

[[v40-25-31]]

^<<v40-25-31,31>>^ "Quando o Filho do Homem vier em sua glória, acompanhado de todos os anjos, ele se sentará em seu trono glorioso.

[[v40-25-32]]

^<<v40-25-32,32>>^ Todas as nações serão reunidas em sua presença, e ele separará as pessoas como um pastor separa as ovelhas dos bodes.

[[v40-25-33]]

^<<v40-25-33,33>>^ Colocará as ovelhas à sua direita e os bodes à sua esquerda.

[[v40-25-34]]

^<<v40-25-34,34>>^ "Então o Rei dirá aos que estiverem à sua direita: ‘Venham, vocês que são abençoados por meu Pai. Recebam como herança o reino que ele lhes preparou desde a criação do mundo.

[[v40-25-35]]

^<<v40-25-35,35>>^ Pois tive fome e vocês me deram de comer. Tive sede e me deram de beber. Era estrangeiro e me convidaram para a sua casa.

[[v40-25-36]]

^<<v40-25-36,36>>^ Estava nu e me vestiram. Estava doente e cuidaram de mim. Estava na prisão e me visitaram’.

[[v40-25-37]]

^<<v40-25-37,37>>^ "Então os justos responderão: ‘Senhor, quando foi que o vimos faminto e lhe demos de comer? Ou sedento e lhe demos de beber?

[[v40-25-38]]

^<<v40-25-38,38>>^ Ou como estrangeiro e o convidamos para a nossa casa? Ou nu e o vestimos?

[[v40-25-39]]

^<<v40-25-39,39>>^ Quando foi que o vimos doente ou na prisão e o visitamos?’.

[[v40-25-40]]

^<<v40-25-40,40>>^ "E o Rei dirá: ‘Eu lhes digo a verdade: quando fizeram isso ao menor destes meus irmãos, foi a mim que o fizeram’.

[[v40-25-41]]

^<<v40-25-41,41>>^ "Em seguida, o Rei se voltará para os que estiverem à sua esquerda e dirá: ‘Fora daqui, malditos, para o fogo eterno preparado para o diabo e seus anjos.

[[v40-25-42]]

^<<v40-25-42,42>>^ Pois tive fome, e vocês não me deram de comer. Tive sede, e não me deram de beber.

[[v40-25-43]]

^<<v40-25-43,43>>^ Era estrangeiro, e não me convidaram para a sua casa. Estava nu, e não me vestiram. Estava doente e na prisão, e não me visitaram’.

[[v40-25-44]]

^<<v40-25-44,44>>^ "Então eles dirão: ‘Senhor, quando o vimos faminto, sedento, como estrangeiro, nu, doente ou na prisão, e não o ajudamos?’.

[[v40-25-45]]

^<<v40-25-45,45>>^ "Ele responderá: ‘Eu lhes digo a verdade: quando se recusaram a ajudar o menor destes meus irmãos e irmãs, foi a mim que se recusaram a ajudar’.

[[v40-25-46]]

^<<v40-25-46,46>>^ "E estes irão para o castigo eterno, mas os justos irão para a vida eterna".

'''

xref:040-mateus/040-mateus-024.adoc#v40-24-0[&#60; Capítulo Anterior] | <<v40-25-0,Topo>> | xref:040-mateus/040-mateus-026.adoc#v40-26-0[Próximo Capítulo &#62;]