include::./index.adoc[]

[[v40-28-0]]
=== Mateus, 28
// nvt ?, NVT - Nova Versão Transformadora

[[v40-28-1]]

^<<v40-28-1,1>>^ Depois do sábado, no primeiro dia da semana, bem cedo, Maria Madalena e a outra Maria foram visitar o túmulo.

[[v40-28-2]]

^<<v40-28-2,2>>^ De repente, houve um grande terremoto, pois um anjo do Senhor desceu do céu, rolou a pedra da entrada e sentou-se sobre ela.

[[v40-28-3]]

^<<v40-28-3,3>>^ Seu rosto brilhava como um relâmpago, e suas roupas eram brancas como a neve.

[[v40-28-4]]

^<<v40-28-4,4>>^ Quando os guardas viram o anjo, tremeram de medo e caíram desmaiados, como mortos.

[[v40-28-5]]

^<<v40-28-5,5>>^ Então o anjo falou com as mulheres. "Não tenham medo", disse ele. "Sei que vocês procuram Jesus, que foi crucificado.

[[v40-28-6]]

^<<v40-28-6,6>>^ Ele não está aqui! Ressuscitou, como tinha dito que aconteceria. Venham, vejam onde seu corpo estava.

[[v40-28-7]]

^<<v40-28-7,7>>^ Agora vão depressa e contem aos discípulos que ele ressuscitou e que vai adiante de vocês para a Galileia. Lá vocês o verão. Lembrem-se do que eu lhes disse!"

[[v40-28-8]]

^<<v40-28-8,8>>^ As mulheres saíram apressadas do túmulo e, assustadas mas cheias de alegria, correram para transmitir aos discípulos a mensagem do anjo.

[[v40-28-9]]

^<<v40-28-9,9>>^ No caminho, Jesus as encontrou e as cumprimentou. Elas correram para ele, abraçaram seus pés e o adoraram.

[[v40-28-10]]

^<<v40-28-10,10>>^ Então Jesus lhes disse: "Não tenham medo! Vão e digam a meus irmãos que se dirijam à Galileia. Lá eles me verão".

[[v40-28-11]]

^<<v40-28-11,11>>^ Enquanto as mulheres estavam a caminho, alguns dos guardas entraram na cidade e contaram aos principais sacerdotes o que havia acontecido.

[[v40-28-12]]

^<<v40-28-12,12>>^ Eles convocaram uma reunião com os líderes do povo e decidiram subornar os guardas com uma grande soma de dinheiro.

[[v40-28-13]]

^<<v40-28-13,13>>^ Instruíram os soldados: "Vocês devem dizer o seguinte: ‘Os discípulos de Jesus vieram durante a noite, enquanto dormíamos, e roubaram o corpo’.

[[v40-28-14]]

^<<v40-28-14,14>>^ Se o governador ficar sabendo disso, nós os defenderemos, para que não se compliquem".

[[v40-28-15]]

^<<v40-28-15,15>>^ Os guardas aceitaram o suborno e falaram conforme tinham sido instruídos. Essa versão se espalhou entre os judeus, que continuam a contá-la até hoje.

[[v40-28-16]]

^<<v40-28-16,16>>^ Então os onze discípulos partiram para a Galileia e foram ao monte que Jesus havia indicado.

[[v40-28-17]]

^<<v40-28-17,17>>^ Quando o viram, o adoraram; alguns deles, porém, duvidaram.

[[v40-28-18]]

^<<v40-28-18,18>>^ Jesus se aproximou deles e disse: "Toda a autoridade no céu e na terra me foi dada.

[[v40-28-19]]

^<<v40-28-19,19>>^ Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai, do Filho e do Espírito Santo.

[[v40-28-20]]

^<<v40-28-20,20>>^ Ensinem esses novos discípulos a obedecerem a todas as ordens que eu lhes dei. E lembrem-se disto: estou sempre com vocês, até o fim dos tempos".

'''

xref:040-mateus/040-mateus-027.adoc#v40-27-0[&#60; Capítulo Anterior] | <<v40-28-0,Topo>> | xref:041-marcos/041-marcos-001.adoc#v41-1-0[Próximo Capítulo &#62;]