include::./index.adoc[]

[[v40-12-0]]
=== Mateus, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v40-12-1]]

^<<v40-12-1,1>>^ Por aquele tempo, Jesus estava caminhando pelos campos de cereal, num sábado. Seus discípulos, sentindo fome, começaram a colher espigas e comê-las.

[[v40-12-2]]

^<<v40-12-2,2>>^ Alguns fariseus os viram e protestaram: "Veja, seus discípulos desobedecem à lei colhendo cereal no sábado!".

[[v40-12-3]]

^<<v40-12-3,3>>^ Jesus respondeu: "Vocês não leram nas Escrituras o que fez Davi quando ele e seus companheiros tiveram fome?

[[v40-12-4]]

^<<v40-12-4,4>>^ Ele entrou na casa de Deus e, com seus companheiros, comeram os pães sagrados que só os sacerdotes tinham permissão de comer.

[[v40-12-5]]

^<<v40-12-5,5>>^ E vocês não leram na lei de Moisés que os sacerdotes de serviço no templo podem trabalhar no sábado?

[[v40-12-6]]

^<<v40-12-6,6>>^ Eu lhes digo: há alguém aqui maior que o templo!

[[v40-12-7]]

^<<v40-12-7,7>>^ Vocês não teriam condenado meus discípulos inocentes se soubessem o significado das Escrituras: ‘Quero que demonstrem misericórdia, e não que ofereçam sacrifícios’.

[[v40-12-8]]

^<<v40-12-8,8>>^ Pois o Filho do Homem é senhor até mesmo do sábado".

[[v40-12-9]]

^<<v40-12-9,9>>^ Então Jesus foi à sinagoga local,

[[v40-12-10]]

^<<v40-12-10,10>>^ onde viu um homem que tinha uma das mãos deformada. Os fariseus perguntaram a Jesus: "A lei permite curar no sábado?". Esperavam que ele dissesse "sim", para que pudessem acusá-lo.

[[v40-12-11]]

^<<v40-12-11,11>>^ Jesus respondeu: "Se um de vocês tivesse uma ovelha e ela caísse num poço no sábado, não trabalharia para tirá-la de lá?

[[v40-12-12]]

^<<v40-12-12,12>>^ Quanto mais vale uma pessoa que uma ovelha! Sim, a lei permite que se faça o bem no sábado".

[[v40-12-13]]

^<<v40-12-13,13>>^ Em seguida, disse ao homem: "Estenda a mão". Ele a estendeu, e ela foi restaurada e ficou igual à outra.

[[v40-12-14]]

^<<v40-12-14,14>>^ Então os fariseus convocaram uma reunião para tramar um modo de matá-lo.

[[v40-12-15]]

^<<v40-12-15,15>>^ Jesus, sabendo o que planejavam, retirou-se daquela região. Muitos o seguiram, e ele curou todos os enfermos que havia entre eles.

[[v40-12-16]]

^<<v40-12-16,16>>^ Contudo, advertiu-lhes que não revelassem quem ele era.

[[v40-12-17]]

^<<v40-12-17,17>>^ Cumpriu-se, assim, a profecia de Isaías a seu respeito:

[[v40-12-18]]

^<<v40-12-18,18>>^ "Vejam meu Servo, aquele que escolhi. Ele é meu Amado; nele tenho grande alegria. Porei sobre ele meu Espírito, e ele proclamará justiça às nações.

[[v40-12-19]]

^<<v40-12-19,19>>^ Não lutará nem gritará, nem levantará a voz em público.

[[v40-12-20]]

^<<v40-12-20,20>>^ Não esmagará a cana quebrada, nem apagará a chama que já está fraca. Por fim, ele fará que a justiça seja vitoriosa.

[[v40-12-21]]

^<<v40-12-21,21>>^ E seu nome será a esperança de todo o mundo".

[[v40-12-22]]

^<<v40-12-22,22>>^ Então levaram até Jesus um homem cego e mudo que estava possuído por um demônio. Jesus o curou, e ele passou a falar e ver.

[[v40-12-23]]

^<<v40-12-23,23>>^ Admirada, a multidão perguntou: "Será que este homem é o Filho de Davi?".

[[v40-12-24]]

^<<v40-12-24,24>>^ No entanto, quando os fariseus souberam do milagre, disseram: "Ele só expulsa demônios porque seu poder vem de Belzebu, o príncipe dos demônios".

[[v40-12-25]]

^<<v40-12-25,25>>^ Jesus conhecia os pensamentos deles e respondeu: "Todo reino dividido internamente está condenado à ruína. Uma cidade ou família dividida contra si mesma se desintegrará.

[[v40-12-26]]

^<<v40-12-26,26>>^ Se Satanás expulsa Satanás, está dividido e luta contra si mesmo. Seu reino não sobreviverá.

[[v40-12-27]]

^<<v40-12-27,27>>^ Se eu expulso demônios pelo poder de Belzebu, o que dizer de seus discípulos? Eles também expulsam demônios, de modo que condenarão vocês pelo que acabaram de dizer.

[[v40-12-28]]

^<<v40-12-28,28>>^ Mas, se expulso demônios pelo Espírito de Deus, então o reino de Deus já chegou até vocês.

[[v40-12-29]]

^<<v40-12-29,29>>^ Afinal, quem tem poder para entrar na casa de um homem forte e saquear seus bens? Somente alguém ainda mais forte, alguém capaz de amarrá-lo e saquear sua casa.

[[v40-12-30]]

^<<v40-12-30,30>>^ "Quem não está comigo opõe-se a mim, e quem não trabalha comigo na verdade trabalha contra mim.

[[v40-12-31]]

^<<v40-12-31,31>>^ "Por isso eu lhes digo: todo pecado e toda blasfêmia serão perdoados, mas a blasfêmia contra o Espírito não será perdoada.

[[v40-12-32]]

^<<v40-12-32,32>>^ Quem falar contra o Filho do Homem será perdoado, mas quem falar contra o Espírito Santo não será perdoado, nem neste mundo nem no mundo por vir.

[[v40-12-33]]

^<<v40-12-33,33>>^ "Uma árvore é identificada por seus frutos. Se a árvore é boa, os frutos serão bons. Se a árvore é ruim, os frutos serão ruins.

[[v40-12-34]]

^<<v40-12-34,34>>^ Raça de víboras! Como poderiam homens maus como vocês dizer o que é bom e correto? Pois a boca fala do que o coração está cheio.

[[v40-12-35]]

^<<v40-12-35,35>>^ A pessoa boa tira coisas boas do tesouro de um coração bom, e a pessoa má tira coisas más do tesouro de um coração mau.

[[v40-12-36]]

^<<v40-12-36,36>>^ Eu lhes digo: no dia do juízo, vocês prestarão contas de toda palavra inútil que falarem.

[[v40-12-37]]

^<<v40-12-37,37>>^ Por suas palavras vocês serão absolvidos, e por elas serão condenados".

[[v40-12-38]]

^<<v40-12-38,38>>^ Alguns dos mestres da lei e fariseus vieram a Jesus e disseram: "Mestre, queremos que nos mostre um sinal de sua autoridade".

[[v40-12-39]]

^<<v40-12-39,39>>^ Jesus, porém, respondeu: "Vocês pedem um sinal porque são uma geração perversa e adúltera, mas o único sinal que lhes darei será o do profeta Jonas.

[[v40-12-40]]

^<<v40-12-40,40>>^ Pois, assim como Jonas passou três dias e três noites no ventre do grande peixe, o Filho do Homem ficará três dias e três noites no coração da terra.

[[v40-12-41]]

^<<v40-12-41,41>>^ "No dia do juízo, os habitantes de Nínive se levantarão contra esta geração e a condenarão, pois eles se arrependeram de seus pecados quando ouviram a mensagem anunciada por Jonas; e vocês têm à sua frente alguém maior que Jonas!

[[v40-12-42]]

^<<v40-12-42,42>>^ A rainha de Sabá também se levantará contra esta geração no dia do juízo e a condenará, pois veio de uma terra distante para ouvir a sabedoria de Salomão; e vocês têm à sua frente alguém maior que Salomão!

[[v40-12-43]]

^<<v40-12-43,43>>^ "Quando um espírito impuro deixa uma pessoa, anda por lugares secos à procura de descanso, mas não o encontra.

[[v40-12-44]]

^<<v40-12-44,44>>^ Então, diz: ‘Voltarei à casa da qual saí’. Ele volta para sua antiga casa e a encontra vazia, varrida e arrumada.

[[v40-12-45]]

^<<v40-12-45,45>>^ Então o espírito busca outros sete espíritos, piores que ele, e todos entram na pessoa e passam a morar nela, e a pessoa fica pior que antes. Assim acontecerá com esta geração perversa".

[[v40-12-46]]

^<<v40-12-46,46>>^ Enquanto Jesus falava à multidão, sua mãe e seus irmãos estavam do lado de fora, pedindo para falar com ele.

[[v40-12-47]]

^<<v40-12-47,47>>^ Alguém disse a Jesus: "Sua mãe e seus irmãos estão lá fora e querem falar com o senhor".

[[v40-12-48]]

^<<v40-12-48,48>>^ Jesus respondeu: "Quem é minha mãe? Quem são meus irmãos?".

[[v40-12-49]]

^<<v40-12-49,49>>^ Então apontou para seus discípulos e disse: "Vejam, estes são minha mãe e meus irmãos.

[[v40-12-50]]

^<<v40-12-50,50>>^ Quem faz a vontade de meu Pai no céu é meu irmão, minha irmã e minha mãe".

'''

xref:040-mateus/040-mateus-011.adoc#v40-11-0[&#60; Capítulo Anterior] | <<v40-12-0,Topo>> | xref:040-mateus/040-mateus-013.adoc#v40-13-0[Próximo Capítulo &#62;]