include::./index.adoc[]

[[v40-9-0]]
=== Mateus, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v40-9-1]]

^<<v40-9-1,1>>^ Jesus entrou num barco e atravessou o mar até a cidade onde morava.

[[v40-9-2]]

^<<v40-9-2,2>>^ Algumas pessoas lhe trouxeram um paralítico deitado numa maca. Ao ver a fé que eles tinham, Jesus disse ao paralítico: "Anime-se, filho! Seus pecados estão perdoados".

[[v40-9-3]]

^<<v40-9-3,3>>^ Alguns mestres da lei disseram a si mesmos: "Isso é blasfêmia!".

[[v40-9-4]]

^<<v40-9-4,4>>^ Jesus, percebendo o que pensavam, perguntou: "Por que vocês reagem com tanta maldade em seu coração?

[[v40-9-5]]

^<<v40-9-5,5>>^ O que é mais fácil dizer: ‘Seus pecados estão perdoados’ ou ‘Levante-se e ande’?

[[v40-9-6]]

^<<v40-9-6,6>>^ Mas eu lhes mostrarei que o Filho do Homem tem autoridade na terra para perdoar pecados". Então disse ao paralítico: "Levante-se, pegue sua maca e vá para casa".

[[v40-9-7]]

^<<v40-9-7,7>>^ O homem se levantou e foi para casa.

[[v40-9-8]]

^<<v40-9-8,8>>^ Ao ver isso, a multidão se encheu de temor e louvou a Deus por ele ter dado tal autoridade aos seres humanos.

[[v40-9-9]]

^<<v40-9-9,9>>^ Enquanto Jesus caminhava, viu um homem chamado Mateus sentado onde se coletavam impostos. "Siga-me", disse-lhe Jesus, e Mateus se levantou e o seguiu.

[[v40-9-10]]

^<<v40-9-10,10>>^ Mais tarde, na casa de Mateus, Jesus e seus discípulos estavam à mesa, acompanhados de um grande número de cobradores de impostos e pecadores.

[[v40-9-11]]

^<<v40-9-11,11>>^ Quando os fariseus viram isso, perguntaram aos discípulos: "Por que o seu mestre come com cobradores de impostos e pecadores?".

[[v40-9-12]]

^<<v40-9-12,12>>^ Jesus ouviu o que disseram e respondeu: "As pessoas saudáveis não precisam de médico, mas sim os doentes".

[[v40-9-13]]

^<<v40-9-13,13>>^ E acrescentou: "Agora vão e aprendam o significado desta passagem das Escrituras: ‘Quero que demonstrem misericórdia, e não que ofereçam sacrifícios’. Pois não vim para chamar os justos, mas sim os pecadores".

[[v40-9-14]]

^<<v40-9-14,14>>^ Os discípulos de João Batista foram a Jesus e lhe perguntaram: "Por que seus discípulos não têm o hábito de jejuar, como nós e os fariseus?".

[[v40-9-15]]

^<<v40-9-15,15>>^ Jesus respondeu: "Por acaso os convidados de um casamento ficam de luto enquanto festejam com o noivo? Um dia, porém, o noivo lhes será tirado, e então jejuarão.

[[v40-9-16]]

^<<v40-9-16,16>>^ "Além disso, ninguém remendaria uma roupa velha usando pano novo. O pano rasgaria a roupa, deixando um buraco ainda maior.

[[v40-9-17]]

^<<v40-9-17,17>>^ "E ninguém colocaria vinho novo em velhos recipientes de couro. O couro se arrebentaria, deixando vazar o vinho, e os recipientes velhos se estragariam. Vinho novo é guardado em recipientes novos, para que ambos se conservem".

[[v40-9-18]]

^<<v40-9-18,18>>^ Enquanto Jesus ainda falava, o líder da sinagoga local veio e se ajoelhou diante dele. "Minha filha acaba de morrer", disse. "Mas, se o senhor vier e puser as mãos sobre ela, ela viverá."

[[v40-9-19]]

^<<v40-9-19,19>>^ Então Jesus e seus discípulos se levantaram e foram com ele.

[[v40-9-20]]

^<<v40-9-20,20>>^ Nesse instante, uma mulher que havia doze anos sofria de hemorragia se aproximou por trás dele e tocou na borda de seu manto,

[[v40-9-21]]

^<<v40-9-21,21>>^ pois pensava: "Se eu apenas tocar em seu manto, serei curada".

[[v40-9-22]]

^<<v40-9-22,22>>^ Jesus se voltou e, quando a viu, disse: "Filha, anime-se! Sua fé a curou". A partir daquele momento, a mulher ficou curada.

[[v40-9-23]]

^<<v40-9-23,23>>^ Quando Jesus chegou à casa do líder da sinagoga, viu a multidão agitada e ouviu a música fúnebre.

[[v40-9-24]]

^<<v40-9-24,24>>^ "Saiam daqui!", disse ele. "A menina não está morta; está apenas dormindo." Os que estavam ali riram dele.

[[v40-9-25]]

^<<v40-9-25,25>>^ Depois que a multidão foi colocada para fora, Jesus entrou e tomou a menina pela mão, e ela se levantou.

[[v40-9-26]]

^<<v40-9-26,26>>^ A notícia desse milagre se espalhou por toda a região.

[[v40-9-27]]

^<<v40-9-27,27>>^ Depois que Jesus saiu dali, dois cegos foram atrás dele, gritando: "Filho de Davi, tenha misericórdia de nós!".

[[v40-9-28]]

^<<v40-9-28,28>>^ Quando Jesus entrou em casa, os cegos se aproximaram, e ele lhes perguntou: "Vocês creem que eu posso fazê-los ver?". "Sim, Senhor", responderam eles.

[[v40-9-29]]

^<<v40-9-29,29>>^ Ele tocou nos olhos dos dois e disse: "Seja feito conforme a sua fé".

[[v40-9-30]]

^<<v40-9-30,30>>^ Então os olhos deles se abriram e puderam ver. Jesus os advertiu severamente: "Não contem a ninguém".

[[v40-9-31]]

^<<v40-9-31,31>>^ Eles, porém, saíram e espalharam sua fama por toda a região.

[[v40-9-32]]

^<<v40-9-32,32>>^ Quando partiram, foi levado a Jesus um homem que não conseguia falar porque estava possuído por um demônio.

[[v40-9-33]]

^<<v40-9-33,33>>^ O demônio foi expulso e, em seguida, o homem começou a falar. As multidões ficaram admiradas. "Jamais aconteceu algo parecido em Israel!", exclamavam.

[[v40-9-34]]

^<<v40-9-34,34>>^ Os fariseus, contudo, disseram: "Ele expulsa demônios porque o príncipe dos demônios lhe dá poder".

[[v40-9-35]]

^<<v40-9-35,35>>^ Jesus andava por todas as cidades e todos os povoados da região, ensinando nas sinagogas, anunciando as boas-novas do reino e curando todo tipo de enfermidade e doença.

[[v40-9-36]]

^<<v40-9-36,36>>^ Quando viu as multidões, teve compaixão delas, pois estavam confusas e desamparadas, como ovelhas sem pastor.

[[v40-9-37]]

^<<v40-9-37,37>>^ Disse aos discípulos: "A colheita é grande, mas os trabalhadores são poucos.

[[v40-9-38]]

^<<v40-9-38,38>>^ Orem ao Senhor da colheita; peçam que ele envie mais trabalhadores para seus campos".

'''

xref:040-mateus/040-mateus-008.adoc#v40-8-0[&#60; Capítulo Anterior] | <<v40-9-0,Topo>> | xref:040-mateus/040-mateus-010.adoc#v40-10-0[Próximo Capítulo &#62;]