include::./index.adoc[]

[[v40-27-0]]
=== Mateus, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v40-27-1]]

^<<v40-27-1,1>>^ De manhã cedo, os principais sacerdotes e líderes do povo se reuniram outra vez para planejar uma maneira de levar Jesus à morte.

[[v40-27-2]]

^<<v40-27-2,2>>^ Então o amarraram, o levaram e o entregaram a Pilatos, o governador romano.

[[v40-27-3]]

^<<v40-27-3,3>>^ Quando Judas, que o havia traído, viu que Jesus tinha sido condenado à morte, encheu-se de remorso e devolveu as trinta moedas de prata aos principais sacerdotes e líderes do povo,

[[v40-27-4]]

^<<v40-27-4,4>>^ dizendo: "Pequei, pois traí um homem inocente". "Que nos importa?", retrucaram eles. "Isso é problema seu."

[[v40-27-5]]

^<<v40-27-5,5>>^ Então Judas jogou as moedas de prata no templo, saiu e se enforcou.

[[v40-27-6]]

^<<v40-27-6,6>>^ Os principais sacerdotes juntaram as moedas e disseram: "Não seria certo colocar este dinheiro no tesouro do templo, pois é dinheiro manchado de sangue".

[[v40-27-7]]

^<<v40-27-7,7>>^ Então resolveram comprar o campo do oleiro e transformá-lo num cemitério para estrangeiros.

[[v40-27-8]]

^<<v40-27-8,8>>^ Por isso, até hoje ele se chama Campo de Sangue.

[[v40-27-9]]

^<<v40-27-9,9>>^ Cumpriu-se, assim, a profecia de Jeremias que diz: "Tomaram as trinta peças de prata, preço pelo qual ele foi avaliado pelo povo de Israel,

[[v40-27-10]]

^<<v40-27-10,10>>^ e compraram o campo do oleiro, conforme o Senhor ordenou".

[[v40-27-11]]

^<<v40-27-11,11>>^ Agora Jesus estava diante de Pilatos, o governador romano, que lhe perguntou: "Você é o rei dos judeus?". Jesus respondeu: "É como você diz".

[[v40-27-12]]

^<<v40-27-12,12>>^ No entanto, quando os principais sacerdotes e os líderes do povo fizeram acusações contra ele, Jesus permaneceu calado.

[[v40-27-13]]

^<<v40-27-13,13>>^ Então Pilatos perguntou: "Você não ouve essas acusações que fazem contra você?".

[[v40-27-14]]

^<<v40-27-14,14>>^ Mas, para surpresa do governador, Jesus nada disse.

[[v40-27-15]]

^<<v40-27-15,15>>^ A cada ano, durante a festa da Páscoa, era costume do governador libertar um prisioneiro, qualquer um que a multidão escolhesse.

[[v40-27-16]]

^<<v40-27-16,16>>^ Nesse ano, havia um prisioneiro, famoso por sua maldade, chamado Barrabás.

[[v40-27-17]]

^<<v40-27-17,17>>^ Quando a multidão se reuniu diante de Pilatos naquela manhã, ele perguntou: "Quem vocês querem que eu solte: Barrabás ou Jesus, chamado Cristo?".

[[v40-27-18]]

^<<v40-27-18,18>>^ Pois ele sabia muito bem que os líderes religiosos judeus tinham prendido Jesus por inveja.

[[v40-27-19]]

^<<v40-27-19,19>>^ Nesse momento, enquanto Pilatos estava sentado no tribunal, sua esposa lhe mandou o seguinte recado: "Deixe esse homem inocente em paz. Na noite passada, tive um sonho a respeito dele e fiquei muito perturbada".

[[v40-27-20]]

^<<v40-27-20,20>>^ Enquanto isso, os principais sacerdotes e os líderes do povo convenceram a multidão a pedir que Barrabás fosse solto e Jesus executado.

[[v40-27-21]]

^<<v40-27-21,21>>^ Então o governador perguntou outra vez: "Qual dos dois vocês querem que eu lhes solte?". A multidão gritou em resposta: "Barrabás!".

[[v40-27-22]]

^<<v40-27-22,22>>^ Pilatos perguntou: "E o que farei com Jesus, chamado Cristo?". "Crucifique-o!", gritou a multidão.

[[v40-27-23]]

^<<v40-27-23,23>>^ "Por quê?", quis saber Pilatos. "Que crime ele cometeu?" Mas a multidão gritou ainda mais alto: "Crucifique-o!".

[[v40-27-24]]

^<<v40-27-24,24>>^ Pilatos viu que de nada adiantava insistir e que um tumulto se iniciava. Assim, mandou buscar uma bacia com água, lavou as mãos diante da multidão e disse: "Estou inocente do sangue deste homem. A responsabilidade é de vocês".

[[v40-27-25]]

^<<v40-27-25,25>>^ Todo o povo gritou em resposta: "Que nós e nossos descendentes sejamos responsabilizados pela morte dele!".

[[v40-27-26]]

^<<v40-27-26,26>>^ Então Pilatos lhes soltou Barrabás. E, depois de mandar açoitar Jesus, entregou-o para ser crucificado.

[[v40-27-27]]

^<<v40-27-27,27>>^ Alguns dos soldados do governador levaram Jesus ao quartel e chamaram todo o regimento.

[[v40-27-28]]

^<<v40-27-28,28>>^ Tiraram as roupas de Jesus e puseram nele um manto vermelho.

[[v40-27-29]]

^<<v40-27-29,29>>^ Teceram uma coroa de espinhos e a colocaram em sua cabeça. Em sua mão direita, puseram um caniço, como se fosse um cetro. Ajoelhavam-se diante dele e zombavam: "Salve, rei dos judeus!".

[[v40-27-30]]

^<<v40-27-30,30>>^ Cuspiam nele, tomavam-lhe o caniço da mão e com ele batiam em sua cabeça.

[[v40-27-31]]

^<<v40-27-31,31>>^ Quando se cansaram de zombar dele, tiraram o manto e o vestiram novamente com suas roupas. Então o levaram para ser crucificado.

[[v40-27-32]]

^<<v40-27-32,32>>^ No caminho, encontraram um homem chamado Simão, de Cirene, e os soldados o obrigaram a carregar a cruz.

[[v40-27-33]]

^<<v40-27-33,33>>^ Então saíram para um lugar chamado Gólgota (que quer dizer "Lugar da Caveira").

[[v40-27-34]]

^<<v40-27-34,34>>^ Os soldados lhe deram para beber vinho misturado com fel, mas, quando Jesus o provou, recusou-se a beber.

[[v40-27-35]]

^<<v40-27-35,35>>^ Depois de pregá-lo na cruz, os soldados tiraram sortes para dividir suas roupas.

[[v40-27-36]]

^<<v40-27-36,36>>^ Então, sentaram-se em redor e montaram guarda.

[[v40-27-37]]

^<<v40-27-37,37>>^ Acima de sua cabeça estava presa uma tabuleta com a acusação feita contra ele: "Este é Jesus, o Rei dos judeus".

[[v40-27-38]]

^<<v40-27-38,38>>^ Dois criminosos foram crucificados com ele, um à sua direita e outro à sua esquerda.

[[v40-27-39]]

^<<v40-27-39,39>>^ O povo que passava por ali gritava insultos e sacudia a cabeça, em zombaria:

[[v40-27-40]]

^<<v40-27-40,40>>^ "Você disse que destruiria o templo e o reconstruiria em três dias. Pois bem, se é o Filho de Deus, salve a si mesmo e desça da cruz!".

[[v40-27-41]]

^<<v40-27-41,41>>^ Os principais sacerdotes, os mestres da lei e os líderes do povo também zombavam de Jesus.

[[v40-27-42]]

^<<v40-27-42,42>>^ "Salvou os outros, mas não pode salvar a si mesmo!", diziam. "Quer dizer que ele é o rei de Israel? Que desça da cruz agora mesmo e creremos nele!

[[v40-27-43]]

^<<v40-27-43,43>>^ Ele confiou em Deus, então que Deus o salve agora, se quiser. Pois ele disse: ‘Eu sou o Filho de Deus’."

[[v40-27-44]]

^<<v40-27-44,44>>^ Até os criminosos que tinham sido crucificados com ele o insultavam da mesma forma.

[[v40-27-45]]

^<<v40-27-45,45>>^ Ao meio-dia, desceu sobre toda a terra uma escuridão que durou três horas.

[[v40-27-46]]

^<<v40-27-46,46>>^ Por volta das três da tarde, Jesus clamou em alta voz: " Eli, Eli, lamá sabactâni ?", que quer dizer: "Meu Deus, meu Deus, por que me abandonaste?".

[[v40-27-47]]

^<<v40-27-47,47>>^ Alguns dos que estavam ali pensaram que ele chamava o profeta Elias.

[[v40-27-48]]

^<<v40-27-48,48>>^ Um deles correu, ensopou uma esponja com vinagre e a ergueu num caniço para que ele bebesse.

[[v40-27-49]]

^<<v40-27-49,49>>^ Os outros, porém, disseram: "Esperem! Vamos ver se Elias vem salvá-lo".

[[v40-27-50]]

^<<v40-27-50,50>>^ Então Jesus clamou em alta voz novamente e entregou seu espírito.

[[v40-27-51]]

^<<v40-27-51,51>>^ Naquele momento, a cortina do santuário do templo se rasgou em duas partes, de cima até embaixo. A terra estremeceu, rochas se partiram

[[v40-27-52]]

^<<v40-27-52,52>>^ e sepulturas se abriram. Muitos do povo santo que haviam morrido ressuscitaram.

[[v40-27-53]]

^<<v40-27-53,53>>^ Saíram do cemitério depois da ressurreição de Jesus, entraram na cidade santa de Jerusalém e apareceram a muita gente.

[[v40-27-54]]

^<<v40-27-54,54>>^ O oficial romano e os outros soldados que vigiavam Jesus ficaram aterrorizados com o terremoto e com tudo que havia acontecido, e disseram: "Este homem era verdadeiramente o Filho de Deus!".

[[v40-27-55]]

^<<v40-27-55,55>>^ Muitas mulheres que tinham vindo da Galileia com Jesus para servi-lo olhavam de longe.

[[v40-27-56]]

^<<v40-27-56,56>>^ Entre elas estavam Maria Madalena, Maria, mãe de Tiago e José, e a mãe dos filhos de Zebedeu.

[[v40-27-57]]

^<<v40-27-57,57>>^ Ao entardecer, José, um homem rico de Arimateia que tinha se tornado seguidor de Jesus,

[[v40-27-58]]

^<<v40-27-58,58>>^ foi a Pilatos e pediu o corpo de Jesus. Pilatos ordenou que lhe entregassem o corpo.

[[v40-27-59]]

^<<v40-27-59,59>>^ José tomou o corpo e o envolveu num lençol limpo, feito de linho,

[[v40-27-60]]

^<<v40-27-60,60>>^ e o colocou num túmulo novo, de sua propriedade, escavado na rocha. Então rolou uma grande pedra na entrada do túmulo e foi embora.

[[v40-27-61]]

^<<v40-27-61,61>>^ Maria Madalena e a outra Maria estavam ali, sentadas em frente ao túmulo.

[[v40-27-62]]

^<<v40-27-62,62>>^ No dia seguinte, no sábado, os principais sacerdotes e os fariseus foram a Pilatos

[[v40-27-63]]

^<<v40-27-63,63>>^ e disseram: "Senhor, lembramos que, quando ainda vivia, aquele mentiroso disse: ‘Depois de três dias ressuscitarei’.

[[v40-27-64]]

^<<v40-27-64,64>>^ Por isso, pedimos que lacre o túmulo até o terceiro dia. Isso impedirá que seus discípulos roubem o corpo e depois digam a todos que ele ressuscitou. Se isso acontecer, estaremos em pior situação que antes".

[[v40-27-65]]

^<<v40-27-65,65>>^ Pilatos respondeu: "Levem soldados e guardem o túmulo como acharem melhor".

[[v40-27-66]]

^<<v40-27-66,66>>^ Então eles lacraram o túmulo e puseram guardas para protegê-lo.

'''

xref:040-mateus/040-mateus-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-mateus/040-mateus-028.adoc#v40-28-0[Próximo Capítulo &#62;]