include::./index.adoc[]

[[v40-13-0]]
=== Mateus, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v40-13-1]]

^<<v40-13-1,1>>^ Mais tarde, naquele mesmo dia, Jesus saiu de casa e sentou-se à beira-mar.

[[v40-13-2]]

^<<v40-13-2,2>>^ Logo, uma grande multidão se juntou ao seu redor. Então ele entrou num barco, sentou-se e ensinou o povo que permanecia na praia.

[[v40-13-3]]

^<<v40-13-3,3>>^ Jesus contou várias parábolas, como esta: "Um lavrador saiu para semear.

[[v40-13-4]]

^<<v40-13-4,4>>^ Enquanto espalhava as sementes pelo campo, algumas caíram à beira do caminho, e as aves vieram e as comeram.

[[v40-13-5]]

^<<v40-13-5,5>>^ Outras sementes caíram em solo rochoso e, não havendo muita terra, germinaram rapidamente,

[[v40-13-6]]

^<<v40-13-6,6>>^ mas as plantas logo murcharam sob o calor do sol e secaram, pois não tinham raízes profundas.

[[v40-13-7]]

^<<v40-13-7,7>>^ Outras sementes caíram entre espinhos, que cresceram e sufocaram os brotos.

[[v40-13-8]]

^<<v40-13-8,8>>^ Ainda outras caíram em solo fértil e produziram uma colheita trinta, sessenta e até cem vezes maior que a quantidade semeada.

[[v40-13-9]]

^<<v40-13-9,9>>^ Quem é capaz de ouvir, ouça com atenção!".

[[v40-13-10]]

^<<v40-13-10,10>>^ Os discípulos vieram e lhe perguntaram: "Por que o senhor usa parábolas quando fala ao povo?".

[[v40-13-11]]

^<<v40-13-11,11>>^ Ele respondeu: "A vocês é permitido entender os segredos do reino dos céus, mas a outros não.

[[v40-13-12]]

^<<v40-13-12,12>>^ Pois ao que tem, mais lhe será dado, e terá em grande quantia; mas do que nada tem, até o que tem lhe será tirado.

[[v40-13-13]]

^<<v40-13-13,13>>^ É por isso que uso parábolas: eles olham, mas não veem; escutam, mas não ouvem nem entendem.

[[v40-13-14]]

^<<v40-13-14,14>>^ "Cumpre-se, desse modo, a profecia de Isaías que diz: ‘Quando ouvirem o que digo, não entenderão. Quando virem o que faço, não compreenderão.

[[v40-13-15]]

^<<v40-13-15,15>>^ Pois o coração deste povo está endurecido; ouvem com dificuldade e têm os olhos fechados, de modo que seus olhos não veem, e seus ouvidos não ouvem, e seu coração não entende, e não se voltam para mim, nem permitem que eu os cure’.

[[v40-13-16]]

^<<v40-13-16,16>>^ "Felizes, porém, são seus olhos, pois eles veem; e seus ouvidos, pois eles ouvem.

[[v40-13-17]]

^<<v40-13-17,17>>^ Eu lhes digo a verdade: muitos profetas e justos desejaram ver o que vocês têm visto e ouvir o que vocês têm ouvido, mas não puderam.

[[v40-13-18]]

^<<v40-13-18,18>>^ "Agora, ouçam a explicação da parábola sobre o lavrador que saiu para semear.

[[v40-13-19]]

^<<v40-13-19,19>>^ As sementes que caíram à beira do caminho representam os que ouvem a mensagem sobre o reino e não a entendem. Então o maligno vem e arranca a semente que foi lançada em seu coração.

[[v40-13-20]]

^<<v40-13-20,20>>^ As que caíram no solo rochoso representam aqueles que ouvem a mensagem e, sem demora, a recebem com alegria.

[[v40-13-21]]

^<<v40-13-21,21>>^ Contudo, uma vez que não têm raízes profundas, não duram muito. Assim que enfrentam problemas ou são perseguidos por causa da mensagem, cedo desanimam.

[[v40-13-22]]

^<<v40-13-22,22>>^ As que caíram entre os espinhos representam outros que ouvem a mensagem, mas logo ela é sufocada pelas preocupações desta vida e pela sedução da riqueza, de modo que não produzem fruto.

[[v40-13-23]]

^<<v40-13-23,23>>^ E as que caíram em solo fértil representam os que ouvem e entendem a mensagem e produzem uma colheita trinta, sessenta e até cem vezes maior que a quantidade semeada".

[[v40-13-24]]

^<<v40-13-24,24>>^ Esta foi outra parábola que Jesus contou: "O reino dos céus é como um agricultor que semeou boas sementes em seu campo.

[[v40-13-25]]

^<<v40-13-25,25>>^ Enquanto os servos dormiam, seu inimigo veio, semeou joio no meio do trigo e foi embora.

[[v40-13-26]]

^<<v40-13-26,26>>^ Quando a plantação começou a crescer, o joio também cresceu.

[[v40-13-27]]

^<<v40-13-27,27>>^ "Os servos do agricultor vieram e disseram: ‘O campo em que o senhor semeou as boas sementes está cheio de joio. De onde ele veio?’.

[[v40-13-28]]

^<<v40-13-28,28>>^ "‘Um inimigo fez isso’, respondeu o agricultor. "‘Devemos arrancar o joio?’, perguntaram os servos.

[[v40-13-29]]

^<<v40-13-29,29>>^ "‘Não’, respondeu ele. ‘Se tirarem o joio, pode acontecer de arrancarem também o trigo.

[[v40-13-30]]

^<<v40-13-30,30>>^ Deixem os dois crescerem juntos até a colheita. Então, direi aos ceifeiros que separem o joio, amarrem-no em feixes e queimem-no e, depois, guardem o trigo no celeiro’".

[[v40-13-31]]

^<<v40-13-31,31>>^ Então Jesus contou outra parábola: "O reino dos céus é como a semente de mostarda que alguém semeia num campo.

[[v40-13-32]]

^<<v40-13-32,32>>^ É a menor de todas as sementes, mas se torna a maior das hortaliças; cresce até se transformar em árvore, e vêm as aves e fazem ninho em seus galhos".

[[v40-13-33]]

^<<v40-13-33,33>>^ Jesus também contou a seguinte parábola: "O reino dos céus é como o fermento usado por uma mulher para fazer pão. Embora ela coloque apenas uma pequena quantidade de fermento em três medidas de farinha, toda a massa fica fermentada".

[[v40-13-34]]

^<<v40-13-34,34>>^ Jesus sempre usava histórias e comparações como essas quando falava às multidões. Na verdade, nunca lhes falava sem usar parábolas.

[[v40-13-35]]

^<<v40-13-35,35>>^ Cumpriu-se, desse modo, o que foi dito por meio do profeta: "Eu lhes falarei por meio de parábolas; explicarei coisas escondidas desde a criação do mundo".

[[v40-13-36]]

^<<v40-13-36,36>>^ Em seguida, deixando as multidões do lado de fora, Jesus entrou em casa. Seus discípulos lhe pediram: "Por favor, explique-nos a história do joio no campo".

[[v40-13-37]]

^<<v40-13-37,37>>^ Jesus respondeu: "O Filho do Homem é o agricultor que planta as boas sementes.

[[v40-13-38]]

^<<v40-13-38,38>>^ O campo é o mundo, e as boas sementes são o povo do reino. O joio são as pessoas que pertencem ao maligno,

[[v40-13-39]]

^<<v40-13-39,39>>^ e o inimigo que plantou o joio no meio do trigo é o diabo. A colheita é o fim dos tempos, e os que fazem a colheita são os anjos.

[[v40-13-40]]

^<<v40-13-40,40>>^ "Da mesma forma que o joio é separado e queimado no fogo, assim será no fim dos tempos.

[[v40-13-41]]

^<<v40-13-41,41>>^ O Filho do Homem enviará seus anjos, e eles removerão do reino tudo que produz pecado e todos que praticam o mal

[[v40-13-42]]

^<<v40-13-42,42>>^ e os lançarão numa fornalha ardente, onde haverá choro e ranger de dentes.

[[v40-13-43]]

^<<v40-13-43,43>>^ Então os justos brilharão como o sol no reino de seu Pai. Quem é capaz de ouvir, ouça com atenção!"

[[v40-13-44]]

^<<v40-13-44,44>>^ "O reino dos céus é como um tesouro escondido que um homem descobriu num campo. Em seu entusiasmo, ele o escondeu novamente, vendeu tudo que tinha e, com o dinheiro da venda, comprou aquele campo."

[[v40-13-45]]

^<<v40-13-45,45>>^ "O reino dos céus também é como um negociante que procurava pérolas da melhor qualidade.

[[v40-13-46]]

^<<v40-13-46,46>>^ Quando descobriu uma pérola de grande valor, vendeu tudo que tinha e, com o dinheiro da venda, comprou a tal pérola."

[[v40-13-47]]

^<<v40-13-47,47>>^ "O reino dos céus é, ainda, como uma rede de pesca que foi lançada ao mar e pegou peixes de todo tipo.

[[v40-13-48]]

^<<v40-13-48,48>>^ Quando a rede estava cheia, os pescadores a arrastaram até a praia, sentaram-se e juntaram os peixes bons em cestos, jogando fora os ruins.

[[v40-13-49]]

^<<v40-13-49,49>>^ Assim será no fim dos tempos. Os anjos virão, separarão os perversos dos justos

[[v40-13-50]]

^<<v40-13-50,50>>^ e os lançarão na fornalha ardente, onde haverá choro e ranger de dentes.

[[v40-13-51]]

^<<v40-13-51,51>>^ Vocês entendem todas essas coisas?" "Sim", responderam eles.

[[v40-13-52]]

^<<v40-13-52,52>>^ Então ele acrescentou: "Todo mestre da lei que se torna discípulo no reino dos céus é como o dono de uma casa que tira do seu tesouro verdades preciosas, tanto novas como velhas".

[[v40-13-53]]

^<<v40-13-53,53>>^ Quando Jesus terminou de contar essas parábolas, deixou aquela região

[[v40-13-54]]

^<<v40-13-54,54>>^ e voltou para Nazaré, cidade onde tinha morado. Enquanto ensinava na sinagoga, todos se admiravam e perguntavam: "De onde lhe vêm a sabedoria e o poder para realizar milagres?

[[v40-13-55]]

^<<v40-13-55,55>>^ Não é esse o filho do carpinteiro? Conhecemos Maria, sua mãe, e também seus irmãos, Tiago, José, Simão e Judas.

[[v40-13-56]]

^<<v40-13-56,56>>^ Todas as suas irmãs moram aqui, entre nós. Onde ele aprendeu todas essas coisas?".

[[v40-13-57]]

^<<v40-13-57,57>>^ E sentiam-se muito ofendidos. Então Jesus lhes disse: "Um profeta recebe honra em toda parte, menos em sua cidade e entre sua própria família".

[[v40-13-58]]

^<<v40-13-58,58>>^ E, por causa da incredulidade deles, realizou ali apenas uns poucos milagres.

'''

xref:040-mateus/040-mateus-012.adoc#v40-12-0[&#60; Capítulo Anterior] | <<v40-13-0,Topo>> | xref:040-mateus/040-mateus-014.adoc#v40-14-0[Próximo Capítulo &#62;]