include::./index.adoc[]

[[v40-3-0]]
=== Mateus, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v40-3-1]]

^<<v40-3-1,1>>^ Naqueles dias, João Batista apareceu no deserto da Judeia e começou a anunciar a seguinte mensagem:

[[v40-3-2]]

^<<v40-3-2,2>>^ "Arrependam-se, pois o reino dos céus está próximo".

[[v40-3-3]]

^<<v40-3-3,3>>^ O profeta Isaías se referia a João quando disse: "Ele é uma voz que clama no deserto: ‘Preparem o caminho para a vinda do Senhor! Abram a estrada para ele!’".

[[v40-3-4]]

^<<v40-3-4,4>>^ As roupas de João eram tecidas com pelos de camelo, e ele usava um cinto de couro e alimentava-se de gafanhotos e mel silvestre.

[[v40-3-5]]

^<<v40-3-5,5>>^ Gente de Jerusalém, de toda a Judeia e de todo o vale do Jordão ia até ele.

[[v40-3-6]]

^<<v40-3-6,6>>^ Quando confessavam seus pecados, ele os batizava no rio Jordão.

[[v40-3-7]]

^<<v40-3-7,7>>^ Mas, quando João viu que muitos fariseus e saduceus vinham ao lugar de batismo, ele os repreendeu abertamente. "Raça de víboras!", exclamou. "Quem os convenceu a fugir da ira que está por vir?

[[v40-3-8]]

^<<v40-3-8,8>>^ Provem por suas ações que vocês se arrependeram.

[[v40-3-9]]

^<<v40-3-9,9>>^ Não pensem que podem dizer uns aos outros: ‘Estamos a salvo, pois somos filhos de Abraão’. Isso não significa nada, pois eu lhes digo que até destas pedras Deus pode fazer surgir filhos de Abraão.

[[v40-3-10]]

^<<v40-3-10,10>>^ Agora mesmo o machado do julgamento está pronto para cortar as raízes das árvores. Toda árvore que não produz bons frutos será cortada e lançada ao fogo.

[[v40-3-11]]

^<<v40-3-11,11>>^ "Eu batizo com água aqueles que se arrependem. Depois de mim, porém, virá alguém mais poderoso que eu, alguém muito superior, cujas sandálias não sou digno de carregar. Ele os batizará com o Espírito Santo e com fogo.

[[v40-3-12]]

^<<v40-3-12,12>>^ Ele já tem na mão a pá, e com ela separará a palha do trigo e limpará a área onde os cereais são debulhados. Juntará o trigo no celeiro, mas queimará a palha no fogo que nunca se apaga."

[[v40-3-13]]

^<<v40-3-13,13>>^ Jesus foi da Galileia ao rio Jordão para que João o batizasse.

[[v40-3-14]]

^<<v40-3-14,14>>^ João, porém, tentou impedi-lo. "Eu é que preciso ser batizado pelo senhor", disse ele. "Então por que vem a mim?"

[[v40-3-15]]

^<<v40-3-15,15>>^ Jesus respondeu: "É necessário que seja assim, pois devemos fazer tudo que Deus requer". E João concordou em batizá-lo.

[[v40-3-16]]

^<<v40-3-16,16>>^ Depois do batismo, enquanto Jesus saía da água, o céu se abriu, e ele viu o Espírito de Deus descer como uma pomba e pousar sobre ele.

[[v40-3-17]]

^<<v40-3-17,17>>^ E uma voz do céu disse: "Este é meu Filho amado, que me dá grande alegria".

'''

xref:040-mateus/040-mateus-002.adoc#v40-2-0[&#60; Capítulo Anterior] | <<v40-3-0,Topo>> | xref:040-mateus/040-mateus-004.adoc#v40-4-0[Próximo Capítulo &#62;]