include::./index.adoc[]

[[v40-23-0]]
=== Mateus, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v40-23-1]]

^<<v40-23-1,1>>^ Então Jesus disse às multidões e a seus discípulos:

[[v40-23-2]]

^<<v40-23-2,2>>^ "Os mestres da lei e os fariseus ocuparam o lugar de intérpretes oficiais da lei de Moisés.

[[v40-23-3]]

^<<v40-23-3,3>>^ Portanto, pratiquem tudo que eles dizem e obedeçam-lhes, mas não sigam seu exemplo, pois eles não fazem o que ensinam.

[[v40-23-4]]

^<<v40-23-4,4>>^ Oprimem as pessoas com exigências insuportáveis e não movem um dedo sequer para aliviar seus fardos.

[[v40-23-5]]

^<<v40-23-5,5>>^ "Tudo que fazem é para se exibir. Usam nos braços filactérios mais largos que de costume e vestem mantos com franjas mais longas.

[[v40-23-6]]

^<<v40-23-6,6>>^ Gostam de sentar-se à cabeceira da mesa nos banquetes e de ocupar os lugares de honra nas sinagogas.

[[v40-23-7]]

^<<v40-23-7,7>>^ Gostam de receber saudações respeitosas enquanto andam pelas praças e de ser chamados de ‘Rabi’.

[[v40-23-8]]

^<<v40-23-8,8>>^ "Não deixem que pessoa alguma os chame de ‘Rabi’, pois vocês têm somente um mestre, e todos vocês são irmãos.

[[v40-23-9]]

^<<v40-23-9,9>>^ Não se dirijam a pessoa alguma aqui na terra como ‘Pai’, pois somente Deus no céu é seu Pai.

[[v40-23-10]]

^<<v40-23-10,10>>^ Não deixem que pessoa alguma os chame de ‘Mestre’, pois vocês têm somente um mestre, o Cristo.

[[v40-23-11]]

^<<v40-23-11,11>>^ O mais importante entre vocês deve ser servo dos outros,

[[v40-23-12]]

^<<v40-23-12,12>>^ pois os que se exaltam serão humilhados, e os que se humilham serão exaltados.

[[v40-23-13]]

^<<v40-23-13,13>>^ "Que aflição os espera, mestres da lei e fariseus! Hipócritas! Fecham a porta do reino dos céus na cara das pessoas. Vocês mesmos não entram e não permitem que os outros entrem.

[[v40-23-14]]

^<<v40-23-14,14>>^ "Que aflição os espera, mestres da lei e fariseus! Hipócritas! Tomam posse dos bens das viúvas de maneira desonesta e, depois, para dar a impressão de piedade, fazem longas orações em público. Por causa disso, serão duramente castigados.

[[v40-23-15]]

^<<v40-23-15,15>>^ "Que aflição os espera, mestres da lei e fariseus! Hipócritas! Atravessam terra e mar para converter alguém e depois o tornam um filho do inferno, duas vezes pior que vocês.

[[v40-23-16]]

^<<v40-23-16,16>>^ "Que aflição os espera, guias cegos! Vocês dizem não haver importância se alguém jura ‘pelo templo de Deus’, mas se jurar ‘pelo ouro do templo’ será obrigado a cumprir o juramento.

[[v40-23-17]]

^<<v40-23-17,17>>^ Tolos cegos! O que é mais importante: o ouro ou o templo, que torna o ouro sagrado?

[[v40-23-18]]

^<<v40-23-18,18>>^ Dizem também não haver importância se alguém jura ‘pelo altar’, mas se jurar ‘pelas ofertas sobre o altar’ será obrigado a cumprir o juramento.

[[v40-23-19]]

^<<v40-23-19,19>>^ Cegos! O que é mais importante: a oferta sobre o altar ou o altar, que torna a oferta sagrada?

[[v40-23-20]]

^<<v40-23-20,20>>^ Quando juram ‘pelo altar’, juram por ele e por tudo que está sobre ele.

[[v40-23-21]]

^<<v40-23-21,21>>^ Quando juram ‘pelo templo’, juram por ele e por Deus, que nele habita.

[[v40-23-22]]

^<<v40-23-22,22>>^ Quando juram ‘pelo céu’, juram pelo trono de Deus e por Deus, que se senta no trono.

[[v40-23-23]]

^<<v40-23-23,23>>^ "Que aflição os espera, mestres da lei e fariseus! Hipócritas! Têm o cuidado de dar o dízimo da hortelã, do endro e do cominho, mas negligenciam os aspectos mais importantes da lei: justiça, misericórdia e fé. Sim, vocês deviam fazer essas coisas, mas sem descuidar das mais importantes.

[[v40-23-24]]

^<<v40-23-24,24>>^ Guias cegos! Coam a água para não engolir um mosquito, mas engolem um camelo!

[[v40-23-25]]

^<<v40-23-25,25>>^ "Que aflição os espera, mestres da lei e fariseus! Hipócritas! Têm o cuidado de limpar a parte exterior do copo e do prato, enquanto o interior está imundo, cheio de ganância e falta de domínio próprio.

[[v40-23-26]]

^<<v40-23-26,26>>^ Fariseus cegos! Lavem primeiro o interior do copo e do prato, e o exterior também ficará limpo.

[[v40-23-27]]

^<<v40-23-27,27>>^ "Que aflição os espera, mestres da lei e fariseus! Hipócritas! São como túmulos pintados de branco: bonitos por fora, mas cheios de ossos e de toda espécie de impureza por dentro.

[[v40-23-28]]

^<<v40-23-28,28>>^ Por fora parecem justos, mas por dentro seu coração está cheio de hipocrisia e maldade.

[[v40-23-29]]

^<<v40-23-29,29>>^ "Que aflição os espera, mestres da lei e fariseus! Hipócritas! Constroem túmulos para os profetas, enfeitam os monumentos dos justos

[[v40-23-30]]

^<<v40-23-30,30>>^ e depois dizem: ‘Se tivéssemos vivido no tempo de nossos antepassados, não teríamos participado com eles do derramamento de sangue dos profetas’.

[[v40-23-31]]

^<<v40-23-31,31>>^ "Ao dizer isso, porém, testemunham contra si mesmos que são, de fato, descendentes dos que assassinaram os profetas.

[[v40-23-32]]

^<<v40-23-32,32>>^ Vão e terminem o que seus antepassados começaram.

[[v40-23-33]]

^<<v40-23-33,33>>^ Serpentes! Raça de víboras! Como escaparão do julgamento do inferno?

[[v40-23-34]]

^<<v40-23-34,34>>^ "Por isso eu lhes envio profetas, homens sábios e mestres da lei. Vocês crucificarão alguns e açoitarão outros nas sinagogas, perseguindo-os de cidade em cidade.

[[v40-23-35]]

^<<v40-23-35,35>>^ Como resultado, serão responsabilizados pelo assassinato de todos os justos de todos os tempos, desde o assassinato do justo Abel até o de Zacarias, filho de Baraquias, que vocês mataram no templo, entre o santuário e o altar.

[[v40-23-36]]

^<<v40-23-36,36>>^ Eu lhes digo a verdade: esse julgamento cairá sobre a presente geração."

[[v40-23-37]]

^<<v40-23-37,37>>^ "Jerusalém, Jerusalém, cidade que mata profetas e apedreja os mensageiros de Deus! Quantas vezes eu quis juntar seus filhos como a galinha protege os pintinhos sob as asas, mas você não deixou.

[[v40-23-38]]

^<<v40-23-38,38>>^ E, agora, sua casa foi abandonada e está deserta.

[[v40-23-39]]

^<<v40-23-39,39>>^ Pois eu lhe digo: você nunca mais me verá, até que diga: ‘Bendito é o que vem em nome do Senhor!’".

'''

xref:040-mateus/040-mateus-022.adoc#v40-22-0[&#60; Capítulo Anterior] | <<v40-23-0,Topo>> | xref:040-mateus/040-mateus-024.adoc#v40-24-0[Próximo Capítulo &#62;]