include::./index.adoc[]

[[v40-2-0]]
=== Mateus, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v40-2-1]]

^<<v40-2-1,1>>^ Jesus nasceu em Belém, na Judeia, durante o reinado de Herodes. Por esse tempo, alguns sábios das terras do Oriente chegaram a Jerusalém

[[v40-2-2]]

^<<v40-2-2,2>>^ e perguntaram: "Onde está o recém-nascido rei dos judeus? Vimos sua estrela no Oriente e viemos adorá-lo".

[[v40-2-3]]

^<<v40-2-3,3>>^ Ao ouvir isso, o rei Herodes ficou perturbado, e com ele todo o povo de Jerusalém.

[[v40-2-4]]

^<<v40-2-4,4>>^ Reuniu os principais sacerdotes e os mestres da lei e lhes perguntou: "Onde nascerá o Cristo?".

[[v40-2-5]]

^<<v40-2-5,5>>^ Eles responderam: "Em Belém da Judeia, pois assim escreveu o profeta:

[[v40-2-6]]

^<<v40-2-6,6>>^ ‘E você, Belém, na terra de Judá, não é a menor entre as principais cidades de Judá, pois de você virá um governante que será o pastor do meu povo, Israel’".

[[v40-2-7]]

^<<v40-2-7,7>>^ Então Herodes convocou os sábios em segredo e soube por eles o momento em que a estrela tinha aparecido.

[[v40-2-8]]

^<<v40-2-8,8>>^ "Vão a Belém e procurem o menino com atenção", disse ele. "Quando o encontrarem, voltem e digam-me, para que eu vá e também o adore."

[[v40-2-9]]

^<<v40-2-9,9>>^ Após a conversa com o rei, os sábios seguiram seu caminho, guiados pela estrela que tinham visto no Oriente. Ela ia adiante deles, até que parou acima do lugar onde o menino estava.

[[v40-2-10]]

^<<v40-2-10,10>>^ Quando viram a estrela, ficaram muito alegres.

[[v40-2-11]]

^<<v40-2-11,11>>^ Ao entrar na casa, viram o menino com Maria, sua mãe, e se prostraram e o adoraram. Então abriram seus tesouros e o presentearam com ouro, incenso e mirra.

[[v40-2-12]]

^<<v40-2-12,12>>^ Quando chegou a hora de partir, retornaram para sua terra por outro caminho, pois haviam sido avisados em sonho para não voltar a Herodes.

[[v40-2-13]]

^<<v40-2-13,13>>^ Depois que os sábios partiram, um anjo do Senhor apareceu a José em sonho. "Levante-se", disse o anjo. "Fuja para o Egito com o menino e sua mãe. Fique lá até eu lhe dizer que volte, pois Herodes vai procurar o menino a fim de matá-lo."

[[v40-2-14]]

^<<v40-2-14,14>>^ Naquela mesma noite, José se levantou e partiu com o menino e Maria, sua mãe, para o Egito,

[[v40-2-15]]

^<<v40-2-15,15>>^ onde ficaram até a morte de Herodes. Cumpriu-se, assim, o que o Senhor tinha dito por meio do profeta: "Do Egito chamei meu filho".

[[v40-2-16]]

^<<v40-2-16,16>>^ Quando Herodes se deu conta de que os sábios o haviam enganado, ficou furioso. Enviou soldados para matar todos os meninos de dois anos para baixo em Belém e seus arredores, tomando por base o relato dos sábios acerca da primeira aparição da estrela.

[[v40-2-17]]

^<<v40-2-17,17>>^ Com isso, cumpriu-se o que foi dito por meio do profeta Jeremias:

[[v40-2-18]]

^<<v40-2-18,18>>^ "Ouviu-se um clamor em Ramá, choro e grande lamentação. Raquel chora por seus filhos e se recusa a ser consolada, pois eles já não existem".

[[v40-2-19]]

^<<v40-2-19,19>>^ Quando Herodes morreu, um anjo do Senhor apareceu em sonho a José, no Egito.

[[v40-2-20]]

^<<v40-2-20,20>>^ "Levante-se", disse o anjo. "Leve o menino e a mãe de volta para a terra de Israel, pois já morreram os que tentavam matar o menino."

[[v40-2-21]]

^<<v40-2-21,21>>^ Então José se levantou e se preparou para voltar à terra de Israel com o menino e sua mãe.

[[v40-2-22]]

^<<v40-2-22,22>>^ Soube, porém, que o novo governador da Judeia era Arquelau, filho de Herodes, e teve medo de ir para lá. Depois de ser avisado em sonho, partiu para a região da Galileia.

[[v40-2-23]]

^<<v40-2-23,23>>^ A família foi morar numa cidade chamada Nazaré, cumprindo-se, desse modo, o que os profetas haviam dito, que Jesus seria chamado nazareno.

'''

xref:040-mateus/040-mateus-001.adoc#v40-1-0[&#60; Capítulo Anterior] | <<v40-2-0,Topo>> | xref:040-mateus/040-mateus-003.adoc#v40-3-0[Próximo Capítulo &#62;]