include::./index.adoc[]

[[v40-20-0]]
=== Mateus, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v40-20-1]]

^<<v40-20-1,1>>^ "Pois o reino dos céus é como o dono de uma propriedade que saiu de manhã cedo a fim de contratar trabalhadores para seu vinhedo.

[[v40-20-2]]

^<<v40-20-2,2>>^ Combinou de pagar uma moeda de prata por um dia de serviço e os mandou trabalhar.

[[v40-20-3]]

^<<v40-20-3,3>>^ "Às nove da manhã, estava passando pela praça e viu por ali alguns desocupados.

[[v40-20-4]]

^<<v40-20-4,4>>^ Contratou-os e disse-lhes que, no final do dia, pagaria o que fosse justo.

[[v40-20-5]]

^<<v40-20-5,5>>^ E eles foram trabalhar no vinhedo. Ao meio-dia e às três da tarde, fez a mesma coisa.

[[v40-20-6]]

^<<v40-20-6,6>>^ "Às cinco da tarde, estava outra vez na cidade e viu por ali mais algumas pessoas. ‘Por que vocês não trabalharam hoje?’, perguntou ele.

[[v40-20-7]]

^<<v40-20-7,7>>^ "‘Porque ninguém nos contratou’, responderam. "Então o proprietário disse: ‘Vão e trabalhem com os outros no meu vinhedo’.

[[v40-20-8]]

^<<v40-20-8,8>>^ "Ao entardecer, mandou o capataz chamar os trabalhadores e pagá-los, começando pelos que haviam sido contratados por último.

[[v40-20-9]]

^<<v40-20-9,9>>^ Os que foram contratados às cinco da tarde vieram e receberam uma moeda de prata.

[[v40-20-10]]

^<<v40-20-10,10>>^ Quando chegaram os que foram contratados primeiro, imaginaram que receberiam mais. Contudo, também receberam uma moeda de prata.

[[v40-20-11]]

^<<v40-20-11,11>>^ Ao receber o pagamento, queixaram-se ao proprietário:

[[v40-20-12]]

^<<v40-20-12,12>>^ ‘Aqueles trabalharam apenas uma hora e, no entanto, o senhor lhes pagou a mesma quantia que a nós, que trabalhamos o dia todo no calor intenso’.

[[v40-20-13]]

^<<v40-20-13,13>>^ "O proprietário respondeu a um deles: ‘Amigo, não fui injusto. Você não concordou em trabalhar o dia inteiro por uma moeda de prata?

[[v40-20-14]]

^<<v40-20-14,14>>^ Pegue seu dinheiro e vá. Eu quis pagar ao último trabalhador o mesmo que paguei a você.

[[v40-20-15]]

^<<v40-20-15,15>>^ É contra a lei eu fazer o que quero com o meu dinheiro? Ou você está com inveja porque fui bondoso com os outros?’.

[[v40-20-16]]

^<<v40-20-16,16>>^ "Assim, os últimos serão os primeiros, e os primeiros serão os últimos".

[[v40-20-17]]

^<<v40-20-17,17>>^ Enquanto subia para Jerusalém, Jesus chamou os doze discípulos e lhes disse, em particular, o que aconteceria com ele:

[[v40-20-18]]

^<<v40-20-18,18>>^ "Ouçam, estamos subindo para Jerusalém, onde o Filho do Homem será traído e entregue aos principais sacerdotes e aos mestres da lei. Eles o condenarão à morte

[[v40-20-19]]

^<<v40-20-19,19>>^ e o entregarão aos gentios, para que zombem dele, o açoitem e o crucifiquem. No terceiro dia, porém, ele ressuscitará".

[[v40-20-20]]

^<<v40-20-20,20>>^ Então a mãe dos filhos de Zebedeu veio a Jesus com seus filhos. Ela se ajoelhou diante dele a fim de lhe pedir um favor.

[[v40-20-21]]

^<<v40-20-21,21>>^ "O que você quer?", perguntou ele. Ela respondeu: "Por favor, permita que, no seu reino, meus dois filhos se sentem em lugares de honra ao seu lado, um à sua direita e outro à sua esquerda".

[[v40-20-22]]

^<<v40-20-22,22>>^ Jesus respondeu: "Vocês não sabem o que estão pedindo! São capazes de beber do cálice que estou prestes a beber?". "Somos!", disseram eles.

[[v40-20-23]]

^<<v40-20-23,23>>^ Então Jesus disse: "De fato, vocês beberão do meu cálice. Não cabe a mim, no entanto, dizer quem se sentará à minha direita ou à minha esquerda. Meu Pai preparou esses lugares para aqueles que ele escolheu".

[[v40-20-24]]

^<<v40-20-24,24>>^ Quando os outros dez discípulos souberam o que os dois irmãos haviam pedido, ficaram indignados.

[[v40-20-25]]

^<<v40-20-25,25>>^ Então Jesus os reuniu e disse: "Vocês sabem que os governantes deste mundo têm poder sobre o povo, e que os oficiais exercem sua autoridade sobre os súditos.

[[v40-20-26]]

^<<v40-20-26,26>>^ Entre vocês, porém, será diferente. Quem quiser ser o líder entre vocês, que seja servo,

[[v40-20-27]]

^<<v40-20-27,27>>^ e quem quiser ser o primeiro entre vocês, que se torne escravo.

[[v40-20-28]]

^<<v40-20-28,28>>^ Pois nem mesmo o Filho do Homem veio para ser servido, mas para servir e dar sua vida em resgate por muitos".

[[v40-20-29]]

^<<v40-20-29,29>>^ Quando Jesus e seus discípulos saíam de Jericó, uma grande multidão os seguiu.

[[v40-20-30]]

^<<v40-20-30,30>>^ Dois cegos estavam sentados à beira do caminho e, quando souberam que Jesus vinha naquela direção, começaram a gritar: "Senhor, Filho de Davi, tenha misericórdia de nós!".

[[v40-20-31]]

^<<v40-20-31,31>>^ "Calem-se!", diziam aos brados os que estavam na multidão. Eles, porém, gritavam ainda mais alto: "Senhor, Filho de Davi, tenha misericórdia de nós!".

[[v40-20-32]]

^<<v40-20-32,32>>^ Ao ouvi-los, Jesus parou e perguntou: "O que vocês querem que eu lhes faça?".

[[v40-20-33]]

^<<v40-20-33,33>>^ Eles responderam: "Senhor, nós queremos enxergar!".

[[v40-20-34]]

^<<v40-20-34,34>>^ Jesus teve compaixão deles e tocou-lhes nos olhos. No mesmo instante, passaram a enxergar e o seguiram.

'''

xref:040-mateus/040-mateus-019.adoc#v40-19-0[&#60; Capítulo Anterior] | <<v40-20-0,Topo>> | xref:040-mateus/040-mateus-021.adoc#v40-21-0[Próximo Capítulo &#62;]