include::./index.adoc[]

[[v40-11-0]]
=== Mateus, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v40-11-1]]

^<<v40-11-1,1>>^ Quando Jesus terminou de dar essas instruções a seus doze discípulos, saiu para ensinar e anunciar sua mensagem nas cidades da região.

[[v40-11-2]]

^<<v40-11-2,2>>^ João Batista, que estava na prisão, soube de todas as coisas que o Cristo estava fazendo. Por isso, enviou seus discípulos para perguntarem a Jesus:

[[v40-11-3]]

^<<v40-11-3,3>>^ "O senhor é aquele que haveria de vir, ou devemos esperar algum outro?".

[[v40-11-4]]

^<<v40-11-4,4>>^ Jesus respondeu: "Voltem a João e contem a ele o que vocês veem e ouvem:

[[v40-11-5]]

^<<v40-11-5,5>>^ os cegos veem, os aleijados andam, os leprosos são purificados, os surdos ouvem, os mortos são ressuscitados e as boas-novas são anunciadas aos pobres".

[[v40-11-6]]

^<<v40-11-6,6>>^ E disse ainda: "Felizes são aqueles que não se sentem ofendidos por minha causa".

[[v40-11-7]]

^<<v40-11-7,7>>^ Enquanto os discípulos de João saíam, Jesus começou a falar a respeito dele para as multidões: "Que tipo de homem vocês foram ver no deserto? Um caniço que qualquer brisa agita?

[[v40-11-8]]

^<<v40-11-8,8>>^ Afinal, o que esperavam ver? Um homem vestido com roupas caras? Não, quem veste roupas caras mora em palácios.

[[v40-11-9]]

^<<v40-11-9,9>>^ Acaso procuravam um profeta? Sim, ele é mais que profeta.

[[v40-11-10]]

^<<v40-11-10,10>>^ João é o homem ao qual as Escrituras se referem quando dizem: ‘Envio meu mensageiro adiante de ti, e ele preparará teu caminho à tua frente!’.

[[v40-11-11]]

^<<v40-11-11,11>>^ "Eu lhes digo a verdade: de todos os que nasceram de mulher, nenhum é maior que João Batista. E, no entanto, até o menor no reino dos céus é maior que ele.

[[v40-11-12]]

^<<v40-11-12,12>>^ Desde os dias em que João pregava, o reino dos céus sofre violência, e pessoas violentas o atacam.

[[v40-11-13]]

^<<v40-11-13,13>>^ Pois, antes de João vir, todos os profetas e a lei de Moisés falavam dos dias de João com grande expectativa,

[[v40-11-14]]

^<<v40-11-14,14>>^ e, se vocês estiverem dispostos a aceitar o que eu digo, ele é Elias, aquele que os profetas disseram que viria.

[[v40-11-15]]

^<<v40-11-15,15>>^ Quem é capaz de ouvir, ouça com atenção!

[[v40-11-16]]

^<<v40-11-16,16>>^ "A que posso comparar esta geração? Ela se parece com crianças que brincam na praça. Queixam-se a seus amigos:

[[v40-11-17]]

^<<v40-11-17,17>>^ ‘Tocamos flauta, e vocês não dançaram; entoamos lamentos, e vocês não se entristeceram’.

[[v40-11-18]]

^<<v40-11-18,18>>^ Quando João apareceu, não costumava comer nem beber em público, e vocês disseram: ‘Está possuído por demônio’.

[[v40-11-19]]

^<<v40-11-19,19>>^ O Filho do Homem, por sua vez, come e bebe, e vocês dizem: ‘É comilão e beberrão, amigo de cobradores de impostos e pecadores’. Mas a sabedoria é comprovada pelos resultados que produz".

[[v40-11-20]]

^<<v40-11-20,20>>^ Então Jesus começou a denunciar as cidades onde ele havia feito muitos milagres, pois não tinham se arrependido.

[[v40-11-21]]

^<<v40-11-21,21>>^ "Que aflição as espera, Corazim e Betsaida! Porque, se nas cidades de Tiro e Sidom tivessem sido realizados os milagres que realizei em vocês, há muito tempo seus habitantes teriam se arrependido e demonstrado isso vestindo panos de saco e jogando cinzas sobre a cabeça.

[[v40-11-22]]

^<<v40-11-22,22>>^ Eu lhes digo que, no dia do juízo, Tiro e Sidom serão tratadas com menos rigor que vocês.

[[v40-11-23]]

^<<v40-11-23,23>>^ "E você, Cafarnaum, será elevada até o céu? Não, descerá até o lugar dos mortos. Porque, se na cidade de Sodoma tivessem sido realizados os milagres que realizei em você, ela estaria de pé ainda hoje.

[[v40-11-24]]

^<<v40-11-24,24>>^ Eu lhe digo que, no dia do juízo, Sodoma será tratada com menos rigor que você".

[[v40-11-25]]

^<<v40-11-25,25>>^ Naquela ocasião, Jesus orou da seguinte maneira: "Pai, Senhor dos céus e da terra, eu te agradeço porque escondeste estas coisas dos que se consideram sábios e instruídos e as revelaste aos que são como crianças.

[[v40-11-26]]

^<<v40-11-26,26>>^ Sim, Pai, foi do teu agrado fazê-lo assim.

[[v40-11-27]]

^<<v40-11-27,27>>^ "Meu Pai me confiou todas as coisas. Ninguém conhece verdadeiramente o Filho, a não ser o Pai, e ninguém conhece verdadeiramente o Pai, a não ser o Filho e aqueles a quem o Filho escolhe revelá-lo.

[[v40-11-28]]

^<<v40-11-28,28>>^ "Venham a mim todos vocês que estão cansados e sobrecarregados, e eu lhes darei descanso.

[[v40-11-29]]

^<<v40-11-29,29>>^ Tomem sobre vocês o meu jugo. Deixem que eu lhes ensine, pois sou manso e humilde de coração, e encontrarão descanso para a alma.

[[v40-11-30]]

^<<v40-11-30,30>>^ Meu jugo é fácil de carregar, e o fardo que lhes dou é leve".

'''

xref:040-mateus/040-mateus-010.adoc#v40-10-0[&#60; Capítulo Anterior] | <<v40-11-0,Topo>> | xref:040-mateus/040-mateus-012.adoc#v40-12-0[Próximo Capítulo &#62;]