include::./index.adoc[]

[[v40-14-0]]
=== Mateus, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v40-14-1]]

^<<v40-14-1,1>>^ Quando Herodes Antipas ouviu falar de Jesus,

[[v40-14-2]]

^<<v40-14-2,2>>^ disse a seus conselheiros: "Deve ser João Batista que ressuscitou dos mortos! Por isso ele tem poder para fazer esses milagres".

[[v40-14-3]]

^<<v40-14-3,3>>^ Herodes havia mandado prender e encarcerar João para agradar Herodias, que era esposa de Filipe, seu irmão.

[[v40-14-4]]

^<<v40-14-4,4>>^ João tinha dito repetidamente a Herodes: "É contra a lei que o senhor viva com ela".

[[v40-14-5]]

^<<v40-14-5,5>>^ Herodes queria matá-lo, mas tinha medo de provocar uma revolta, pois o povo acreditava que João era profeta.

[[v40-14-6]]

^<<v40-14-6,6>>^ Contudo, numa festa de aniversário de Herodes, a filha de Herodias dançou diante dos convidados e agradou muito o rei,

[[v40-14-7]]

^<<v40-14-7,7>>^ e ele prometeu, sob juramento, que lhe daria qualquer coisa que ela pedisse.

[[v40-14-8]]

^<<v40-14-8,8>>^ Instigada pela mãe, a moça disse: "Quero a cabeça de João Batista num prato!".

[[v40-14-9]]

^<<v40-14-9,9>>^ O rei se arrependeu do que tinha dito, mas, por causa do juramento feito diante dos convidados, deu as ordens para que atendessem ao pedido.

[[v40-14-10]]

^<<v40-14-10,10>>^ João foi decapitado na prisão,

[[v40-14-11]]

^<<v40-14-11,11>>^ e sua cabeça foi trazida num prato e entregue à moça, que a levou à sua mãe.

[[v40-14-12]]

^<<v40-14-12,12>>^ Os discípulos de João vieram, levaram seu corpo e o sepultaram. Em seguida, foram a Jesus e lhe contaram o que havia acontecido.

[[v40-14-13]]

^<<v40-14-13,13>>^ Logo que Jesus ouviu a notícia, partiu de barco para um lugar isolado, a fim de ficar só. As multidões, porém, descobriram para onde ele ia e o seguiram a pé, vindas de muitas cidades.

[[v40-14-14]]

^<<v40-14-14,14>>^ Quando Jesus saiu do barco, viu a grande multidão, teve compaixão dela e curou os enfermos.

[[v40-14-15]]

^<<v40-14-15,15>>^ Ao entardecer, os discípulos foram até ele e disseram: "Este lugar é isolado, e já está ficando tarde. Mande as multidões embora, para que possam ir aos povoados e comprar comida".

[[v40-14-16]]

^<<v40-14-16,16>>^ "Não há necessidade", disse Jesus. "Providenciem vocês mesmos alimento para elas."

[[v40-14-17]]

^<<v40-14-17,17>>^ Eles responderam: "Temos apenas cinco pães e dois peixes!".

[[v40-14-18]]

^<<v40-14-18,18>>^ "Tragam para cá", disse ele.

[[v40-14-19]]

^<<v40-14-19,19>>^ Em seguida, mandou o povo sentar-se na grama. Tomou os cinco pães e os dois peixes, olhou para o céu e os abençoou. Então, partiu os pães em pedaços e os entregou a seus discípulos, que distribuíram às multidões.

[[v40-14-20]]

^<<v40-14-20,20>>^ Todos comeram à vontade, e os discípulos recolheram doze cestos com as sobras.

[[v40-14-21]]

^<<v40-14-21,21>>^ Os que comeram foram cerca de cinco mil homens, sem contar mulheres e crianças.

[[v40-14-22]]

^<<v40-14-22,22>>^ Logo em seguida, Jesus insistiu com seus discípulos que voltassem ao barco e atravessassem até o outro lado do mar, enquanto ele despedia as multidões.

[[v40-14-23]]

^<<v40-14-23,23>>^ Depois de mandá-las para casa, Jesus subiu sozinho ao monte a fim de orar. Quando anoiteceu, ele ainda estava ali, sozinho.

[[v40-14-24]]

^<<v40-14-24,24>>^ Enquanto isso, os discípulos, distantes da terra firme, lutavam contra as ondas, pois um vento forte havia se levantado.

[[v40-14-25]]

^<<v40-14-25,25>>^ Por volta das três da madrugada, Jesus foi até eles, caminhando sobre as águas.

[[v40-14-26]]

^<<v40-14-26,26>>^ Quando os discípulos o viram caminhando sobre as águas, ficaram aterrorizados. "É um fantasma!", gritaram, cheios de medo.

[[v40-14-27]]

^<<v40-14-27,27>>^ Imediatamente, porém, Jesus lhes disse: "Não tenham medo! Coragem, sou eu!".

[[v40-14-28]]

^<<v40-14-28,28>>^ Então Pedro gritou: "Se é realmente o senhor, ordene que eu vá caminhando sobre as águas até onde está!".

[[v40-14-29]]

^<<v40-14-29,29>>^ "Venha!", respondeu Jesus. Então Pedro desceu do barco e caminhou sobre as águas em direção a Jesus.

[[v40-14-30]]

^<<v40-14-30,30>>^ Mas, quando reparou no vento forte e nas ondas, ficou aterrorizado, começou a afundar e gritou: "Senhor, salva-me!".

[[v40-14-31]]

^<<v40-14-31,31>>^ No mesmo instante, Jesus estendeu a mão e o segurou. "Como é pequena a sua fé!", disse ele. "Por que você duvidou?"

[[v40-14-32]]

^<<v40-14-32,32>>^ Quando entraram no barco, o vento parou.

[[v40-14-33]]

^<<v40-14-33,33>>^ Então os outros discípulos o adoraram e exclamaram: "De fato, o senhor é o Filho de Deus!".

[[v40-14-34]]

^<<v40-14-34,34>>^ Depois de atravessarem o mar, chegaram a Genesaré.

[[v40-14-35]]

^<<v40-14-35,35>>^ Quando o povo reconheceu Jesus, a notícia de sua chegada se espalhou rapidamente por toda a região, e trouxeram os enfermos para que fossem curados.

[[v40-14-36]]

^<<v40-14-36,36>>^ Suplicavam que ele deixasse os enfermos apenas tocar na borda de seu manto, e todos que o tocavam eram curados.

'''

xref:040-mateus/040-mateus-013.adoc#v40-13-0[&#60; Capítulo Anterior] | <<v40-14-0,Topo>> | xref:040-mateus/040-mateus-015.adoc#v40-15-0[Próximo Capítulo &#62;]