include::./index.adoc[]

[[v40-17-0]]
=== Mateus, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v40-17-1]]

^<<v40-17-1,1>>^ Seis dias depois, Jesus levou consigo Pedro e os dois irmãos, Tiago e João, até um monte alto.

[[v40-17-2]]

^<<v40-17-2,2>>^ Enquanto os três observavam, a aparência de Jesus foi transformada de tal modo que seu rosto brilhava como o sol e suas roupas se tornaram brancas como a luz.

[[v40-17-3]]

^<<v40-17-3,3>>^ De repente, Moisés e Elias apareceram e começaram a falar com Jesus.

[[v40-17-4]]

^<<v40-17-4,4>>^ Pedro exclamou: "Senhor, é maravilhoso estarmos aqui! Se quiser, farei três tendas: uma será sua, uma de Moisés e outra de Elias".

[[v40-17-5]]

^<<v40-17-5,5>>^ Enquanto ele ainda falava, uma nuvem brilhante os cobriu, e uma voz que vinha da nuvem disse: "Este é meu Filho amado, que me dá grande alegria. Ouçam-no!".

[[v40-17-6]]

^<<v40-17-6,6>>^ Os discípulos ficaram aterrorizados e caíram com o rosto em terra.

[[v40-17-7]]

^<<v40-17-7,7>>^ Então Jesus veio e os tocou. "Levantem-se", disse ele. "Não tenham medo."

[[v40-17-8]]

^<<v40-17-8,8>>^ E, quando levantaram os olhos, viram apenas Jesus.

[[v40-17-9]]

^<<v40-17-9,9>>^ Enquanto desciam do monte, Jesus lhes ordenou: "Não contem a ninguém o que viram, até que o Filho do Homem ressuscite dos mortos".

[[v40-17-10]]

^<<v40-17-10,10>>^ Os discípulos lhe perguntaram: "Por que os mestres da lei afirmam que é necessário que Elias volte antes que o Cristo venha?".

[[v40-17-11]]

^<<v40-17-11,11>>^ Jesus respondeu: "De fato, Elias vem e restaurará tudo.

[[v40-17-12]]

^<<v40-17-12,12>>^ Eu, porém, lhes digo: Elias já veio, mas não o reconheceram e preferiram maltratá-lo. Da mesma forma, também farão o Filho do Homem sofrer".

[[v40-17-13]]

^<<v40-17-13,13>>^ Então os discípulos entenderam que ele estava falando de João Batista.

[[v40-17-14]]

^<<v40-17-14,14>>^ Ao pé do monte, uma grande multidão os esperava. Um homem veio, ajoelhou-se diante de Jesus e disse:

[[v40-17-15]]

^<<v40-17-15,15>>^ "Senhor, tenha misericórdia de meu filho. Ele tem convulsões e sofre terrivelmente. Muitas vezes, cai no fogo ou na água.

[[v40-17-16]]

^<<v40-17-16,16>>^ Eu o trouxe a seus discípulos, mas eles não puderam curá-lo".

[[v40-17-17]]

^<<v40-17-17,17>>^ Jesus disse: "Geração incrédula e corrompida! Até quando estarei com vocês? Até quando terei de suportá-los? Tragam o menino para cá".

[[v40-17-18]]

^<<v40-17-18,18>>^ Então Jesus repreendeu o demônio, e ele saiu do menino, que ficou curado a partir daquele momento.

[[v40-17-19]]

^<<v40-17-19,19>>^ Mais tarde, os discípulos perguntaram a Jesus em particular: "Por que não conseguimos expulsar aquele demônio?".

[[v40-17-20]]

^<<v40-17-20,20>>^ "Porque a sua fé é muito pequena", respondeu Jesus. "Eu lhes digo a verdade: se tivessem fé, ainda que do tamanho de uma semente de mostarda, poderiam dizer a este monte: ‘Mova-se daqui para lá’, e ele se moveria. Nada seria impossível para vocês,

[[v40-17-21]]

^<<v40-17-21,21>>^ mas essa espécie não sai senão com oração e jejum."

[[v40-17-22]]

^<<v40-17-22,22>>^ Quando voltaram a se reunir na Galileia, Jesus lhes disse: "O Filho do Homem será traído e entregue em mãos humanas.

[[v40-17-23]]

^<<v40-17-23,23>>^ Será morto, mas no terceiro dia ressuscitará". E os discípulos se encheram de tristeza.

[[v40-17-24]]

^<<v40-17-24,24>>^ Quando Jesus e seus discípulos chegaram a Cafarnaum, os cobradores do imposto do templo abordaram Pedro e lhe perguntaram: "Seu mestre não paga o imposto do templo?".

[[v40-17-25]]

^<<v40-17-25,25>>^ "Sim, paga", respondeu Pedro. Em seguida, entrou em casa. Antes que ele tivesse oportunidade de falar, Jesus lhe perguntou: "O que você acha, Simão? O que os reis costumam fazer: cobram impostos de seu povo ou dos povos conquistados?".

[[v40-17-26]]

^<<v40-17-26,26>>^ "Cobram dos povos conquistados", respondeu Pedro. "Pois bem", disse Jesus. "Os cidadãos estão isentos.

[[v40-17-27]]

^<<v40-17-27,27>>^ Mas, como não queremos que se ofendam, desça até o mar e jogue o anzol. Abra a boca do primeiro peixe que pegar e ali encontrará uma moeda de prata. Pegue-a e use-a para pagar os impostos por nós dois."

'''

xref:040-mateus/040-mateus-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-mateus/040-mateus-018.adoc#v40-18-0[Próximo Capítulo &#62;]