include::./index.adoc[]

[[v40-7-0]]
=== Mateus, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v40-7-1]]

^<<v40-7-1,1>>^ "Não julguem para não serem julgados,

[[v40-7-2]]

^<<v40-7-2,2>>^ pois vocês serão julgados pelo modo como julgam os outros. O padrão de medida que adotarem será usado para medi-los.

[[v40-7-3]]

^<<v40-7-3,3>>^ "Por que você se preocupa com o cisco no olho de seu amigo enquanto há um tronco em seu próprio olho?

[[v40-7-4]]

^<<v40-7-4,4>>^ Como pode dizer a seu amigo: ‘Deixe-me ajudá-lo a tirar o cisco de seu olho’, se não consegue ver o tronco em seu próprio olho?

[[v40-7-5]]

^<<v40-7-5,5>>^ Hipócrita! Primeiro, livre-se do tronco em seu olho; então você verá o suficiente para tirar o cisco do olho de seu amigo.

[[v40-7-6]]

^<<v40-7-6,6>>^ "Não deem o que é santo aos cães, nem joguem pérolas aos porcos; pois os porcos pisotearão as pérolas, e os cães se voltarão contra vocês e os atacarão."

[[v40-7-7]]

^<<v40-7-7,7>>^ "Peçam, e receberão. Procurem, e encontrarão. Batam, e a porta lhes será aberta.

[[v40-7-8]]

^<<v40-7-8,8>>^ Pois todos que pedem, recebem. Todos que procuram, encontram. E, para todos que batem, a porta é aberta.

[[v40-7-9]]

^<<v40-7-9,9>>^ "Respondam: Se seu filho lhe pedir pão, você lhe dará uma pedra?

[[v40-7-10]]

^<<v40-7-10,10>>^ Ou, se pedir um peixe, você lhe dará uma cobra?

[[v40-7-11]]

^<<v40-7-11,11>>^ Portanto, se vocês, que são maus, sabem dar bons presentes a seus filhos, quanto mais seu Pai, que está no céu, dará bons presentes aos que lhe pedirem!"

[[v40-7-12]]

^<<v40-7-12,12>>^ "Em todas as coisas façam aos outros o que vocês desejam que eles lhes façam. Essa é a essência de tudo que ensinam a lei e os profetas."

[[v40-7-13]]

^<<v40-7-13,13>>^ "Entrem pela porta estreita. A estrada que conduz à destruição é ampla, e larga é sua porta, e muitos escolhem esse caminho.

[[v40-7-14]]

^<<v40-7-14,14>>^ Mas a porta para a vida é estreita, e o caminho é difícil, e são poucos os que o encontram."

[[v40-7-15]]

^<<v40-7-15,15>>^ "Tomem cuidado com falsos profetas que vêm disfarçados de ovelhas, mas que, na verdade, são lobos esfomeados.

[[v40-7-16]]

^<<v40-7-16,16>>^ Vocês os identificarão por seus frutos. É possível colher uvas de espinheiros ou figos de ervas daninhas?

[[v40-7-17]]

^<<v40-7-17,17>>^ Da mesma forma, a árvore boa produz frutos bons, e a árvore ruim produz frutos ruins.

[[v40-7-18]]

^<<v40-7-18,18>>^ A árvore boa não pode produzir frutos ruins, e a árvore ruim não pode produzir frutos bons.

[[v40-7-19]]

^<<v40-7-19,19>>^ Toda árvore que não produz bons frutos é cortada e lançada ao fogo.

[[v40-7-20]]

^<<v40-7-20,20>>^ Portanto, é possível identificar a pessoa por seus frutos."

[[v40-7-21]]

^<<v40-7-21,21>>^ "Nem todos que me chamam: ‘Senhor! Senhor!’ entrarão no reino dos céus, mas apenas aqueles que, de fato, fazem a vontade de meu Pai, que está no céu.

[[v40-7-22]]

^<<v40-7-22,22>>^ No dia do juízo, muitos me dirão: ‘Senhor! Senhor! Não profetizamos em teu nome, não expulsamos demônios em teu nome e não realizamos muitos milagres em teu nome?’.

[[v40-7-23]]

^<<v40-7-23,23>>^ Eu, porém, responderei: ‘Nunca os conheci. Afastem-se de mim, vocês que desobedecem à lei!’."

[[v40-7-24]]

^<<v40-7-24,24>>^ "Quem ouve minhas palavras e as pratica é tão sábio como a pessoa que constrói sua casa sobre uma rocha firme.

[[v40-7-25]]

^<<v40-7-25,25>>^ Quando vierem as chuvas e as inundações, e os ventos castigarem a casa, ela não cairá, pois foi construída sobre rocha firme.

[[v40-7-26]]

^<<v40-7-26,26>>^ Mas quem ouve meu ensino e não o pratica é tão tolo como a pessoa que constrói sua casa sobre a areia.

[[v40-7-27]]

^<<v40-7-27,27>>^ Quando vierem as chuvas e as inundações e os ventos castigarem a casa, ela cairá com grande estrondo."

[[v40-7-28]]

^<<v40-7-28,28>>^ Quando Jesus acabou de dizer essas coisas, a multidão ficou maravilhada com seu ensino,

[[v40-7-29]]

^<<v40-7-29,29>>^ pois ele ensinava com verdadeira autoridade, diferentemente dos mestres da lei.

'''

xref:040-mateus/040-mateus-006.adoc#v40-6-0[&#60; Capítulo Anterior] | <<v40-7-0,Topo>> | xref:040-mateus/040-mateus-008.adoc#v40-8-0[Próximo Capítulo &#62;]