include::./index.adoc[]

[[v22-7-0]]
=== Cânticos, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v22-7-1]]

^<<v22-7-1,1>>^ Como são lindos seus pés calçados com sandálias, moça com porte de princesa! As curvas de seus quadris são como joias, trabalho de artífice habilidoso.

[[v22-7-2]]

^<<v22-7-2,2>>^ Seu umbigo tem forma perfeita, como taça cheia de vinho de boa mistura. Sua cintura é como um monte de trigo cercado de lírios.

[[v22-7-3]]

^<<v22-7-3,3>>^ Seus dois seios são como duas crias, como filhotes gêmeos da gazela.

[[v22-7-4]]

^<<v22-7-4,4>>^ Seu pescoço é gracioso como uma torre de marfim. Seus olhos são como os açudes cristalinos de Hesbom, junto à porta de Bete-Rabim. Seu nariz é belo como a torre do Líbano, de onde se avista Damasco.

[[v22-7-5]]

^<<v22-7-5,5>>^ Sua cabeça é majestosa como o monte Carmelo, e o brilho de seu cabelo irradia nobreza; o rei é prisioneiro de suas tranças.

[[v22-7-6]]

^<<v22-7-6,6>>^ Como você é linda! Como você é agradável, meu amor, e cheia de delícias!

[[v22-7-7]]

^<<v22-7-7,7>>^ É esbelta como uma palmeira, e seus seios são como os cachos de frutos.

[[v22-7-8]]

^<<v22-7-8,8>>^ Eu disse: "Subirei a palmeira e me apossarei de seus frutos". Que seus seios sejam como cachos de uva, e que o aroma de sua respiração tenha o perfume das maçãs.

[[v22-7-9]]

^<<v22-7-9,9>>^ Que seus beijos sejam como o melhor vinho. Sim, vinho que escorre para meu amado, que flui suave por lábios e dentes.

[[v22-7-10]]

^<<v22-7-10,10>>^ Eu sou de meu amado, e ele me deseja.

[[v22-7-11]]

^<<v22-7-11,11>>^ Venha, meu amor, vamos aos campos, passar a noite entre as flores silvestres.

[[v22-7-12]]

^<<v22-7-12,12>>^ Vamos levantar cedo para ir aos vinhedos ver se as videiras brotaram, se as flores abriram e se as romãs já estão em flor; ali eu lhe darei meu amor.

[[v22-7-13]]

^<<v22-7-13,13>>^ Ali as mandrágoras espalham sua fragrância, e os melhores frutos estão à nossa porta, delícias novas e antigas, que guardei para você, meu amado.

'''

xref:022-canticos/022-canticos-006.adoc#v22-6-0[&#60; Capítulo Anterior] | <<v22-7-0,Topo>> | xref:022-canticos/022-canticos-008.adoc#v22-8-0[Próximo Capítulo &#62;]