include::./index.adoc[]

[[v22-8-0]]
=== Cânticos, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v22-8-1]]

^<<v22-8-1,1>>^ Quem dera você fosse meu irmão, amamentado nos seios de minha mãe. Então eu poderia beijá-lo publicamente, e ninguém me criticaria.

[[v22-8-2]]

^<<v22-8-2,2>>^ Eu o levaria ao lar de minha infância, e ali você me ensinaria. Eu lhe daria de beber vinho com especiarias, o néctar de minhas romãs.

[[v22-8-3]]

^<<v22-8-3,3>>^ Seu braço esquerdo estaria sob a minha cabeça, e o direito me abraçaria.

[[v22-8-4]]

^<<v22-8-4,4>>^ Prometam, ó mulheres de Jerusalém, que não despertarão o amor antes do tempo.

[[v22-8-5]]

^<<v22-8-5,5>>^ Quem é essa que vem subindo do deserto, apoiada em seu amado? Despertei você debaixo da macieira, onde sua mãe o deu à luz, onde, com muitas dores, ela o trouxe ao mundo.

[[v22-8-6]]

^<<v22-8-6,6>>^ Coloque-me como selo sobre seu coração, como selo sobre seu braço. Pois o amor é forte como a morte, e o ciúme, exigente como a sepultura. O amor arde como fogo, como as labaredas mais intensas.

[[v22-8-7]]

^<<v22-8-7,7>>^ As muitas águas não podem apagar o amor, nem os rios podem afogá-lo. Se algum homem tentasse usar todas as suas riquezas para comprar o amor, sua oferta seria por completo desprezada.

[[v22-8-8]]

^<<v22-8-8,8>>^ Temos uma irmãzinha, que ainda é jovem demais para ter seios. O que faremos por nossa irmã, se alguém a pedir em casamento?

[[v22-8-9]]

^<<v22-8-9,9>>^ Se ela for um muro, nós a protegeremos com uma torre de prata. Se ela for uma porta, nós a fecharemos com uma tranca de cedro.

[[v22-8-10]]

^<<v22-8-10,10>>^ Eu sou um muro, e meus seios são suas torres. Quando meu amado olha para mim, ele se agrada do que vê.

[[v22-8-11]]

^<<v22-8-11,11>>^ Salomão tem um vinhedo em Baal-Hamom, que ele arrenda para lavradores. Cada um lhe paga mil peças de prata para colher os frutos.

[[v22-8-12]]

^<<v22-8-12,12>>^ Quanto a meu vinhedo, faço dele o que quero, e Salomão não precisa pagar mil peças de prata. Darei, contudo, duzentas peças aos que cuidam de seus frutos.

[[v22-8-13]]

^<<v22-8-13,13>>^ Minha querida, que mora nos jardins, seus companheiros ouvem atentamente sua voz; deixe-me ouvi-la também!

[[v22-8-14]]

^<<v22-8-14,14>>^ Venha correndo, meu amado! Seja como a gazela, como o jovem cervo sobre os montes de especiarias.

'''

xref:022-canticos/022-canticos-007.adoc#v22-7-0[&#60; Capítulo Anterior] | <<v22-8-0,Topo>> | xref:023-isaias/023-isaias-001.adoc#v23-1-0[Próximo Capítulo &#62;]