include::./index.adoc[]

[[v22-4-0]]
=== Cânticos, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v22-4-1]]

^<<v22-4-1,1>>^ Você é linda, minha querida, como você é linda! Seus olhos por trás do véu são como pombas. Seu cabelo é como um rebanho de cabras que desce pelas encostas de Gileade.

[[v22-4-2]]

^<<v22-4-2,2>>^ Seus dentes são brancos como ovelhas recém-tosquiadas e lavadas. Seu sorriso é perfeito; cada dente tem seu par ideal.

[[v22-4-3]]

^<<v22-4-3,3>>^ Seus lábios são como uma fita vermelha; sua boca é linda. Suas faces por trás do véu são rosadas como romãs.

[[v22-4-4]]

^<<v22-4-4,4>>^ Seu pescoço é belo, como a torre de Davi, enfeitada com escudos de mil guerreiros valentes.

[[v22-4-5]]

^<<v22-4-5,5>>^ Seus dois seios são como duas crias de gazela, filhotes gêmeos que se alimentam entre os lírios.

[[v22-4-6]]

^<<v22-4-6,6>>^ Antes que soprem as brisas do amanhecer, e fujam as sombras da noite, irei ao monte de mirra e à colina de incenso.

[[v22-4-7]]

^<<v22-4-7,7>>^ Você é inteiramente linda, minha querida; não há em você defeito algum!

[[v22-4-8]]

^<<v22-4-8,8>>^ Venha comigo do Líbano, minha noiva, venha comigo do Líbano. Desça do monte Amana, dos cumes do Senir e do Hermom, onde os leões têm suas tocas e os leopardos vivem nas montanhas.

[[v22-4-9]]

^<<v22-4-9,9>>^ Você conquistou meu coração, minha amiga, minha noiva. Você o cativou com um só olhar de relance, com um só enfeite de seu colar.

[[v22-4-10]]

^<<v22-4-10,10>>^ Seu amor é delicioso, minha amiga, minha noiva. Seu amor é melhor que vinho; seu perfume é mais agradável que especiarias.

[[v22-4-11]]

^<<v22-4-11,11>>^ Seus lábios são doces como néctar, minha noiva; debaixo de sua língua há mel e leite. Seus vestidos são perfumados como os cedros do Líbano.

[[v22-4-12]]

^<<v22-4-12,12>>^ Você é meu jardim particular, minha amiga, minha noiva, nascente fechada, fonte escondida.

[[v22-4-13]]

^<<v22-4-13,13>>^ Seus renovos guardam um paraíso de romãs com especiarias raras: hena e nardo,

[[v22-4-14]]

^<<v22-4-14,14>>^ nardo e açafrão, cálamo perfumado e canela, com todas as árvores de incenso, com mirra, aloés e todas as outras especiarias finas.

[[v22-4-15]]

^<<v22-4-15,15>>^ Você é uma fonte de jardim, um poço de água fresca que desce dos montes do Líbano.

[[v22-4-16]]

^<<v22-4-16,16>>^ Desperte, vento norte! Levante-se, vento sul! Soprem em meu jardim e espalhem sua fragrância por toda parte. Entre em seu jardim, meu amor, e saboreie seus melhores frutos.

'''

xref:022-canticos/022-canticos-003.adoc#v22-3-0[&#60; Capítulo Anterior] | <<v22-4-0,Topo>> | xref:022-canticos/022-canticos-005.adoc#v22-5-0[Próximo Capítulo &#62;]