include::./index.adoc[]

[[v22-5-0]]
=== Cânticos, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v22-5-1]]

^<<v22-5-1,1>>^ Entrei em meu jardim, minha amiga, minha noiva! Recolhi mirra com minhas especiarias, comi meu favo com mel, bebi meu vinho com leite. Comam e bebam, amado e amada! Sim, bebam de seu amor quanto puderem!

[[v22-5-2]]

^<<v22-5-2,2>>^ Eu dormia, mas meu coração estava desperto, quando ouvi meu amado bater à porta e chamar: "Abra a porta para mim, minha amiga, minha querida, minha pomba, minha perfeita. Minha cabeça está molhada de orvalho, e meu cabelo, úmido do sereno da noite".

[[v22-5-3]]

^<<v22-5-3,3>>^ Eu respondi: "Já tirei a túnica; vou ter de me vestir de novo? Já lavei os pés; vou ter de sujá-los?".

[[v22-5-4]]

^<<v22-5-4,4>>^ Meu amado tentou destrancar a porta, e meu coração se agitou.

[[v22-5-5]]

^<<v22-5-5,5>>^ Levantei-me de um salto para abrir a porta ao meu amor. Minhas mãos destilavam perfume e de meus dedos pingava mirra, quando puxei o ferrolho.

[[v22-5-6]]

^<<v22-5-6,6>>^ Abri para meu amado, mas ele já havia partido! Meu coração quase parou de tristeza. Procurei por ele, mas não o encontrei. Chamei por ele, mas ele não respondeu.

[[v22-5-7]]

^<<v22-5-7,7>>^ Os guardas me encontraram enquanto faziam a ronda. Bateram-me e feriram-me, arrancaram-me o manto, aqueles guardas dos muros.

[[v22-5-8]]

^<<v22-5-8,8>>^ Prometam, ó mulheres de Jerusalém: Se encontrarem meu amado, digam-lhe que desfaleço de amor.

[[v22-5-9]]

^<<v22-5-9,9>>^ Diga-nos, mulher de beleza incomparável: Por que seu amado é melhor que todos os outros? O que ele tem de tão especial para fazermos a você essa promessa?

[[v22-5-10]]

^<<v22-5-10,10>>^ Meu amado é moreno e fascinante; ele se destaca no meio da multidão!

[[v22-5-11]]

^<<v22-5-11,11>>^ Sua cabeça é como o ouro puro, seu cabelo ondulado, preto como o corvo.

[[v22-5-12]]

^<<v22-5-12,12>>^ Seus olhos são como pombas junto aos riachos, incrustados como joias lavadas em leite.

[[v22-5-13]]

^<<v22-5-13,13>>^ Suas faces são como jardins de especiarias que espalham sua fragrância. Seus lábios são como lírios perfumados com mirra.

[[v22-5-14]]

^<<v22-5-14,14>>^ Seus braços são como barras redondas de ouro, enfeitadas com berilo. Seu ventre é como marfim polido, que resplandece com safiras.

[[v22-5-15]]

^<<v22-5-15,15>>^ Suas pernas são como colunas de mármore apoiadas em bases de ouro puro. Seu porte é majestoso, como o dos cedros do Líbano.

[[v22-5-16]]

^<<v22-5-16,16>>^ Sua voz é a própria doçura; ele é desejável em todos os sentidos. Esse, ó mulheres de Jerusalém, é meu amado, meu amigo.

'''

xref:022-canticos/022-canticos-004.adoc#v22-4-0[&#60; Capítulo Anterior] | <<v22-5-0,Topo>> | xref:022-canticos/022-canticos-006.adoc#v22-6-0[Próximo Capítulo &#62;]