include::./index.adoc[]

[[v22-2-0]]
=== Cânticos, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v22-2-1]]

^<<v22-2-1,1>>^ Eu sou a flor que nasce na planície de Sarom, o lírio que cresce no vale.

[[v22-2-2]]

^<<v22-2-2,2>>^ Como um lírio entre os espinhos, assim é minha querida entre as moças.

[[v22-2-3]]

^<<v22-2-3,3>>^ Como uma macieira entre as árvores do bosque, assim é meu amado entre os rapazes. À sua sombra agradável eu me sento e saboreio seus deliciosos frutos.

[[v22-2-4]]

^<<v22-2-4,4>>^ Ele me trouxe ao salão de banquetes; seu grande amor por mim é evidente.

[[v22-2-5]]

^<<v22-2-5,5>>^ Fortaleçam-me com bolos de passas, revigorem-me com maçãs, pois desfaleço de amor.

[[v22-2-6]]

^<<v22-2-6,6>>^ Seu braço esquerdo está sob a minha cabeça, e o direito me abraça.

[[v22-2-7]]

^<<v22-2-7,7>>^ Prometam, ó mulheres de Jerusalém, pelas gazelas e corças selvagens, que não despertarão o amor antes do tempo.

[[v22-2-8]]

^<<v22-2-8,8>>^ Ah, ouço meu amado chegando! Ele salta sobre os montes, pula sobre as colinas.

[[v22-2-9]]

^<<v22-2-9,9>>^ Meu amado é como a gazela, como o jovem cervo. Vejam, lá está ele atrás do muro, observando pelas janelas, espiando por entre as grades.

[[v22-2-10]]

^<<v22-2-10,10>>^ Meu amado me disse: "Levante-se, minha querida! Venha comigo, minha bela!

[[v22-2-11]]

^<<v22-2-11,11>>^ Veja, o inverno acabou, e as chuvas passaram.

[[v22-2-12]]

^<<v22-2-12,12>>^ As flores estão brotando; chegou a época das canções, e o arrulhar das pombas enche o ar.

[[v22-2-13]]

^<<v22-2-13,13>>^ As figueiras começam a dar frutos, e as videiras perfumadas florescem. Levante-se, minha querida! Venha comigo, minha bela!".

[[v22-2-14]]

^<<v22-2-14,14>>^ Minha pomba está escondida entre as pedras, oculta nas fendas das rochas. Mostre-me seu rosto e deixe-me ouvir sua voz. Pois sua voz é doce, e seu rosto é lindo.

[[v22-2-15]]

^<<v22-2-15,15>>^ Peguem todas as raposas, as raposinhas, antes que destruam o vinhedo do amor, pois as videiras estão em flor!

[[v22-2-16]]

^<<v22-2-16,16>>^ Meu amado é meu, e eu sou dele; ele pastoreia entre os lírios.

[[v22-2-17]]

^<<v22-2-17,17>>^ Antes que soprem as brisas do amanhecer, e fujam as sombras da noite, volte para mim, meu amor, como a gazela, como o jovem cervo nos montes íngremes.

'''

xref:022-canticos/022-canticos-001.adoc#v22-1-0[&#60; Capítulo Anterior] | <<v22-2-0,Topo>> | xref:022-canticos/022-canticos-003.adoc#v22-3-0[Próximo Capítulo &#62;]