include::./index.adoc[]

[[v22-6-0]]
=== Cânticos, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v22-6-1]]

^<<v22-6-1,1>>^ Para onde foi seu amado, ó mulher de beleza incomparável? Diga-nos que caminho ele tomou, e a ajudaremos a encontrá-lo.

[[v22-6-2]]

^<<v22-6-2,2>>^ Meu amado desceu a seu jardim, aos canteiros de especiarias, para pastorear nos jardins e para colher lírios.

[[v22-6-3]]

^<<v22-6-3,3>>^ Eu sou de meu amado, e meu amado é meu; ele pastoreia entre os lírios.

[[v22-6-4]]

^<<v22-6-4,4>>^ Você é linda, minha querida, como a bela cidade de Tirza. Sim, é linda como Jerusalém, majestosa como um exército com bandeiras ao vento.

[[v22-6-5]]

^<<v22-6-5,5>>^ Desvie de mim seus olhos, pois eles me dominam. Seu cabelo é como um rebanho de cabras que desce pelas encostas de Gileade.

[[v22-6-6]]

^<<v22-6-6,6>>^ Seus dentes são brancos como ovelhas recém-lavadas. Seu sorriso é perfeito; cada dente tem seu par ideal.

[[v22-6-7]]

^<<v22-6-7,7>>^ Suas faces por trás do véu são rosadas como romãs.

[[v22-6-8]]

^<<v22-6-8,8>>^ Mesmo entre sessenta rainhas, oitenta concubinas e incontáveis moças,

[[v22-6-9]]

^<<v22-6-9,9>>^ eu ainda escolheria minha pomba, minha perfeita, a predileta de sua mãe, muito amada por aquela que a deu à luz. As moças a veem e dizem que ela é feliz; até mesmo as rainhas e as concubinas do rei a elogiam:

[[v22-6-10]]

^<<v22-6-10,10>>^ "Quem é essa que se levanta como o amanhecer, bela como a lua, brilhante como o sol, majestosa como um exército com bandeiras ao vento?".

[[v22-6-11]]

^<<v22-6-11,11>>^ Desci ao bosque das nogueiras e fui ao vale ver as novas plantas, ver se as videiras tinham brotado e se as romãs tinham florescido.

[[v22-6-12]]

^<<v22-6-12,12>>^ Antes que eu me desse conta, meu desejo me levou à carruagem de um nobre.

[[v22-6-13]]

^<<v22-6-13,13>>^ Volte, volte para junto de nós, sulamita! Volte, volte para que a vejamos outra vez! Por que vocês olham para a sulamita enquanto ela se move com tanta graça entre duas fileiras de dançarinas?

'''

xref:022-canticos/022-canticos-005.adoc#v22-5-0[&#60; Capítulo Anterior] | <<v22-6-0,Topo>> | xref:022-canticos/022-canticos-007.adoc#v22-7-0[Próximo Capítulo &#62;]