include::./index.adoc[]

[[v17-5-0]]
=== Ester, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v17-5-1]]

^<<v17-5-1,1>>^ No terceiro dia do jejum, Ester vestiu seus trajes reais e entrou no pátio interno do palácio, em frente do salão do rei. O rei estava sentado no trono, voltado para a entrada.

[[v17-5-2]]

^<<v17-5-2,2>>^ Quando viu a rainha Ester ali no pátio interno, ele a recebeu de bom grado e lhe estendeu o cetro de ouro. Ester se aproximou e tocou a ponta do cetro.

[[v17-5-3]]

^<<v17-5-3,3>>^ "O que você deseja, rainha Ester?", perguntou o rei. "Qual é seu pedido? Eu atenderei, mesmo que peça metade do reino!"

[[v17-5-4]]

^<<v17-5-4,4>>^ Ester respondeu: "Se lhe parecer bem, venha hoje com Hamã a um banquete que preparei para o rei".

[[v17-5-5]]

^<<v17-5-5,5>>^ O rei se voltou para seus servos e disse: "Digam a Hamã que venha depressa para um banquete, como Ester pediu". Então o rei e Hamã foram ao banquete que Ester havia preparado.

[[v17-5-6]]

^<<v17-5-6,6>>^ Enquanto bebiam vinho, o rei disse a Ester: "Agora diga-me o que você deseja. Qual é seu pedido? Eu atenderei, mesmo que peça metade do reino!".

[[v17-5-7]]

^<<v17-5-7,7>>^ Ester respondeu: "Este é meu pedido e meu desejo:

[[v17-5-8]]

^<<v17-5-8,8>>^ Se conto com o favor do rei e se lhe parecer bem atender a meu pedido, venha amanhã com Hamã ao banquete que lhes prepararei. Então explicarei do que se trata".

[[v17-5-9]]

^<<v17-5-9,9>>^ Hamã saiu do banquete muito feliz e animado. Contudo, ficou furioso quando viu que Mardoqueu, sentado à porta do palácio, não se levantou nem demonstrou nervosismo em sua presença.

[[v17-5-10]]

^<<v17-5-10,10>>^ Hamã, porém, se conteve e foi para casa. Então reuniu seus amigos e sua esposa, Zeres,

[[v17-5-11]]

^<<v17-5-11,11>>^ e gabou-se de sua grande riqueza e de seus muitos filhos. Vangloriou-se das honras que o rei lhe havia concedido e de como havia sido promovido acima de todos os outros nobres e oficiais.

[[v17-5-12]]

^<<v17-5-12,12>>^ Disse também: "Se isso não bastasse, a rainha Ester convidou somente o rei e a mim para um banquete que ela preparou! E ainda me convidou para outro banquete com ela e com o rei amanhã!".

[[v17-5-13]]

^<<v17-5-13,13>>^ Depois, acrescentou: "Nada disso, porém, me satisfará enquanto eu vir o judeu Mardoqueu sentado à porta do palácio".

[[v17-5-14]]

^<<v17-5-14,14>>^ Então Zeres, esposa de Hamã, e todos os amigos dele sugeriram: "Mande fazer uma forca de mais de vinte metros e, pela manhã, peça ao rei que Mardoqueu seja enforcado nela. Depois disso, você poderá ir alegremente ao banquete com o rei". A sugestão agradou Hamã, e ele mandou fazer a forca.

'''

xref:017-ester/017-ester-004.adoc#v17-4-0[&#60; Capítulo Anterior] | <<v17-5-0,Topo>> | xref:017-ester/017-ester-006.adoc#v17-6-0[Próximo Capítulo &#62;]