include::./index.adoc[]

[[v17-1-0]]
=== Ester, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v17-1-1]]

^<<v17-1-1,1>>^ Estes acontecimentos ocorreram nos dias do rei Xerxes, que reinou sobre 127 províncias, desde a Índia até a Etiópia.

[[v17-1-2]]

^<<v17-1-2,2>>^ Do trono real na fortaleza de Susã, Xerxes governava seu império.

[[v17-1-3]]

^<<v17-1-3,3>>^ No terceiro ano de reinado, ofereceu um banquete a todos os seus nobres e oficiais. Convidou todos os oficiais militares da Pérsia e da Média e os príncipes e nobres das províncias.

[[v17-1-4]]

^<<v17-1-4,4>>^ A festa durou 180 dias e foi uma demonstração formidável da grande riqueza do império e da pompa e esplendor de sua majestade.

[[v17-1-5]]

^<<v17-1-5,5>>^ Terminada a celebração, o rei ofereceu um banquete para todo o povo que estava na fortaleza de Susã, desde os mais importantes até os mais humildes. O banquete durou sete dias e foi realizado no pátio do jardim do palácio real.

[[v17-1-6]]

^<<v17-1-6,6>>^ O pátio estava enfeitado com cortinas brancas de algodão e com tapeçarias azuis, presas com cordas de linho branco e fitas vermelhas a argolas de prata fixadas a colunas de mármore. Havia sofás com armação de ouro e de prata sobre um piso de mosaico de pórfiro, mármore, madrepérola e outras pedras preciosas.

[[v17-1-7]]

^<<v17-1-7,7>>^ As bebidas eram servidas em taças de ouro de diversos modelos, e havia grande quantidade de vinho real, para mostrar a generosidade do rei.

[[v17-1-8]]

^<<v17-1-8,8>>^ Por ordem do rei, podia-se beber à vontade, pois ele havia instruído os oficiais de seu palácio a servirem quanto vinho cada convidado quisesse.

[[v17-1-9]]

^<<v17-1-9,9>>^ Na mesma ocasião, a rainha Vasti ofereceu um banquete para as mulheres no palácio do rei Xerxes.

[[v17-1-10]]

^<<v17-1-10,10>>^ No sétimo dia da festa, quando o rei Xerxes estava muito alegre por causa do vinho, ordenou aos sete eunucos que o serviam — Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas —

[[v17-1-11]]

^<<v17-1-11,11>>^ que lhe trouxessem a rainha Vasti, usando a coroa real. Ele queria que os nobres e os demais convidados contemplassem sua beleza, pois era uma mulher muito bonita.

[[v17-1-12]]

^<<v17-1-12,12>>^ Mas, quando transmitiram a ordem do rei à rainha Vasti, ela se recusou a ir. O rei ficou furioso e indignado.

[[v17-1-13]]

^<<v17-1-13,13>>^ Então o rei consultou seus sábios, que entendiam das leis e dos costumes dos persas, e aos quais ele sempre pedia conselhos.

[[v17-1-14]]

^<<v17-1-14,14>>^ Seus nomes eram Carsena, Setar, Admata, Társis, Meres, Marsena e Memucã, sete nobres da Pérsia e da Média. Tinham acesso direto ao rei e ocupavam os cargos mais altos do império.

[[v17-1-15]]

^<<v17-1-15,15>>^ "O que se deve fazer com a rainha Vasti?", perguntou o rei. "De acordo com a lei, qual é o castigo para uma rainha que se recusa a obedecer às ordens do rei, transmitidas pelos eunucos?"

[[v17-1-16]]

^<<v17-1-16,16>>^ Memucã respondeu ao rei e aos nobres: "A rainha Vasti ofendeu não somente o rei, mas todos os nobres e cidadãos das províncias do império.

[[v17-1-17]]

^<<v17-1-17,17>>^ Mulheres de toda parte começarão a desprezar o marido quando souberem que a rainha Vasti se recusou a comparecer diante do rei.

[[v17-1-18]]

^<<v17-1-18,18>>^ Antes de terminar este dia, as esposas dos nobres do rei em toda a Pérsia e a Média saberão o que a rainha fez e começarão a tratar o marido da mesma forma. Haverá grande desprezo e indignação sem fim.

[[v17-1-19]]

^<<v17-1-19,19>>^ "Portanto, se parecer bem ao rei, sugerimos que publique um decreto real, uma lei dos medos e dos persas que não pode ser revogada. Determinará que a rainha Vasti seja expulsa para sempre da presença do rei Xerxes e que o rei escolha outra rainha mais digna que ela.

[[v17-1-20]]

^<<v17-1-20,20>>^ Quando o decreto for publicado em todo o vasto império do rei, maridos de toda parte, seja qual for a posição social, serão respeitados pela esposa".

[[v17-1-21]]

^<<v17-1-21,21>>^ O conselho pareceu razoável ao rei e a seus nobres, e ele aceitou a proposta de Memucã.

[[v17-1-22]]

^<<v17-1-22,22>>^ Enviou cartas a todas as partes do império, a cada província, em sua própria escrita e língua, proclamando que todo homem devia ser o chefe de sua própria casa e ter sempre a última palavra.

'''

xref:016-neemias/016-neemias-013.adoc#v16-13-0[&#60; Capítulo Anterior] | <<v17-1-0,Topo>> | xref:017-ester/017-ester-002.adoc#v17-2-0[Próximo Capítulo &#62;]