include::./index.adoc[]

[[v17-6-0]]
=== Ester, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v17-6-1]]

^<<v17-6-1,1>>^ Naquela noite, o rei não conseguia dormir; então mandou que trouxessem o livro da história de seu reinado e o lessem para ele.

[[v17-6-2]]

^<<v17-6-2,2>>^ Nesses registros ele descobriu que Mardoqueu havia denunciado Bigtana e Teres, os dois eunucos que guardavam a porta dos aposentos reais e que haviam conspirado para matar o rei Xerxes.

[[v17-6-3]]

^<<v17-6-3,3>>^ "Que recompensa ou reconhecimento Mardoqueu recebeu por isso?", quis saber o rei. Seus servos responderam: "Não se fez nada por ele".

[[v17-6-4]]

^<<v17-6-4,4>>^ "Quem está no pátio?", perguntou o rei. Hamã tinha acabado de entrar no pátio externo do palácio para pedir ao rei que Mardoqueu fosse executado na forca que ele havia preparado.

[[v17-6-5]]

^<<v17-6-5,5>>^ Os servos responderam: "É Hamã que está no pátio". "Digam a ele que entre", ordenou o rei.

[[v17-6-6]]

^<<v17-6-6,6>>^ Hamã entrou, e o rei lhe perguntou: "O que devo fazer para honrar um homem que muito me agrada?". Hamã pensou: "A quem o rei desejaria honrar senão a mim?".

[[v17-6-7]]

^<<v17-6-7,7>>^ Por isso, respondeu: "Se o rei deseja honrar alguém,

[[v17-6-8]]

^<<v17-6-8,8>>^ mande trazer um dos mantos que o rei costuma usar, e um cavalo no qual o rei costuma montar, e que tenha o emblema real na cabeça.

[[v17-6-9]]

^<<v17-6-9,9>>^ Ordene que o manto e o cavalo sejam entregues a um dos mais nobres oficiais do rei e que ele ponha o manto sobre o homem que o rei deseja honrar e o conduza pela praça da cidade sobre o cavalo do rei. Mande que o oficial proclame em alta voz: ‘Assim o rei faz a quem ele deseja honrar!’".

[[v17-6-10]]

^<<v17-6-10,10>>^ "Excelente!", disse o rei a Hamã. "Vá depressa pegar meu manto e meu cavalo e faça ao judeu Mardoqueu, que está sentado à porta do palácio, exatamente o que você sugeriu. Não se esqueça de nenhum detalhe!"

[[v17-6-11]]

^<<v17-6-11,11>>^ Então Hamã pegou o manto e o cavalo do rei, vestiu Mardoqueu com o manto e o conduziu sobre o cavalo pela praça da cidade, proclamando em alta voz: "Assim o rei faz a quem ele deseja honrar!".

[[v17-6-12]]

^<<v17-6-12,12>>^ Depois disso, Mardoqueu voltou para a porta do palácio, mas Hamã correu para casa, abatido e humilhado.

[[v17-6-13]]

^<<v17-6-13,13>>^ Quando Hamã contou a Zeres, sua esposa, e a todos os seus amigos o que havia acontecido, seus conselheiros e sua esposa disseram: "Visto que Mardoqueu, diante de quem você foi humilhado, é judeu de nascimento, seus planos contra ele jamais serão bem-sucedidos. Você ficará arruinado se continuar a se opor a ele".

[[v17-6-14]]

^<<v17-6-14,14>>^ Enquanto ainda falavam, os eunucos do rei chegaram e, sem demora, levaram Hamã ao banquete que Ester havia preparado.

'''

xref:017-ester/017-ester-005.adoc#v17-5-0[&#60; Capítulo Anterior] | <<v17-6-0,Topo>> | xref:017-ester/017-ester-007.adoc#v17-7-0[Próximo Capítulo &#62;]