include::./index.adoc[]

[[v17-2-0]]
=== Ester, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v17-2-1]]

^<<v17-2-1,1>>^ Passada a indignação de Xerxes, ele começou a pensar em Vasti, naquilo que ela havia feito e no decreto que ele havia publicado.

[[v17-2-2]]

^<<v17-2-2,2>>^ Então seus conselheiros sugeriram: "Permita que procuremos em todo o império moças belas e virgens para o rei.

[[v17-2-3]]

^<<v17-2-3,3>>^ E que o rei nomeie agentes em cada província para que tragam essas lindas moças ao harém na fortaleza em Susã. Hegai, eunuco do rei e encarregado do harém, providenciará que elas recebam tratamentos de beleza.

[[v17-2-4]]

^<<v17-2-4,4>>^ Depois disso, a moça que mais agradar o rei se tornará rainha em lugar de Vasti". O rei gostou muito desse conselho e o pôs em prática.

[[v17-2-5]]

^<<v17-2-5,5>>^ Nesse tempo, havia na fortaleza de Susã um judeu chamado Mardoqueu, filho de Jair. Era da tribo de Benjamim e descendente de Quis e Simei.

[[v17-2-6]]

^<<v17-2-6,6>>^ Sua família estava entre aqueles que, com Joaquim, rei de Judá, tinham sido deportados de Jerusalém para a Babilônia pelo rei Nabucodonosor.

[[v17-2-7]]

^<<v17-2-7,7>>^ Mardoqueu tinha uma prima jovem, muito bonita e atraente, chamada Hadassa, também conhecida como Ester. Quando o pai e a mãe de Ester morreram, Mardoqueu a criou como sua própria filha.

[[v17-2-8]]

^<<v17-2-8,8>>^ Como resultado do decreto do rei, Ester e muitas outras moças foram trazidas ao palácio real, na fortaleza de Susã, e colocadas sob os cuidados de Hegai, o encarregado do harém.

[[v17-2-9]]

^<<v17-2-9,9>>^ Hegai ficou muito impressionado com a beleza de Ester e a tratou com bondade. Sem demora, providenciou que ela recebesse comida especial e tratamentos de beleza. Também lhe designou sete moças escolhidas do palácio real e a transferiu, com as jovens, para o melhor lugar do harém.

[[v17-2-10]]

^<<v17-2-10,10>>^ Mardoqueu havia instruído Ester a não revelar a ninguém sua nacionalidade nem a origem de sua família.

[[v17-2-11]]

^<<v17-2-11,11>>^ Todos os dias, Mardoqueu caminhava perto do pátio do harém para saber notícias de Ester e descobrir o que estava acontecendo.

[[v17-2-12]]

^<<v17-2-12,12>>^ Antes de ser levada aos aposentos reais, cada moça recebia os doze meses prescritos de tratamentos de beleza: seis meses com óleo de mirra e seis meses com perfumes e cosméticos.

[[v17-2-13]]

^<<v17-2-13,13>>^ Quando chegava sua vez de ir aos aposentos reais, podia escolher do harém as roupas e as joias que quisesse.

[[v17-2-14]]

^<<v17-2-14,14>>^ À tarde, era conduzida aos aposentos reais e, na manhã seguinte, ia para outra parte do harém, onde moravam as mulheres do rei. Ali, ficava sob os cuidados de Saasgaz, eunuco do rei encarregado das concubinas. Ela não voltaria a se encontrar com o rei a menos que ele tivesse gostado muito dela e mandasse chamá-la pelo nome.

[[v17-2-15]]

^<<v17-2-15,15>>^ Ester era filha de Abiail, tio de Mardoqueu. (Mardoqueu havia adotado Ester, sua prima mais nova, como filha.) Quando chegou a vez de Ester se apresentar ao rei, ela aceitou o conselho de Hegai, eunuco encarregado do harém. Não pediu nada além do que ele sugeriu e agradou a todos que a viram.

[[v17-2-16]]

^<<v17-2-16,16>>^ Ester foi levada ao rei Xerxes no palácio real no mês de dezembro, no sétimo ano de seu reinado.

[[v17-2-17]]

^<<v17-2-17,17>>^ O rei gostou mais de Ester que de qualquer outra moça. Agradou-se tanto dela que pôs a coroa real sobre sua cabeça e a declarou rainha em lugar de Vasti.

[[v17-2-18]]

^<<v17-2-18,18>>^ Para comemorar a ocasião, ofereceu a todos os seus nobres e oficiais um grande banquete em homenagem a Ester. Declarou aquele dia feriado em todas as províncias e distribuiu presentes generosos para todos.

[[v17-2-19]]

^<<v17-2-19,19>>^ Mesmo depois que todas as moças haviam sido transferidas para a outra parte do harém e que Mardoqueu tinha se tornado um dos oficiais do palácio,

[[v17-2-20]]

^<<v17-2-20,20>>^ Ester continuou a manter em segredo sua nacionalidade e a origem de sua família. Ainda seguia as instruções de Mardoqueu como havia feito quando vivia sob os seus cuidados.

[[v17-2-21]]

^<<v17-2-21,21>>^ Certo dia, quando Mardoqueu estava de serviço junto à porta do palácio real, dois eunucos do rei, Bigtana e Teres, guardas da porta dos aposentos do rei, se indignaram com Xerxes e conspiraram para matá-lo.

[[v17-2-22]]

^<<v17-2-22,22>>^ Mardoqueu, porém, soube do plano e transmitiu a informação à rainha Ester, que contou ao rei em nome de Mardoqueu.

[[v17-2-23]]

^<<v17-2-23,23>>^ Quando o caso foi investigado e descobriu-se que o relato de Mardoqueu era verdadeiro, os dois homens foram enforcados. Tudo isso está registrado no Livro da História do Reinado do Rei Xerxes .

'''

xref:017-ester/017-ester-001.adoc#v17-1-0[&#60; Capítulo Anterior] | <<v17-2-0,Topo>> | xref:017-ester/017-ester-003.adoc#v17-3-0[Próximo Capítulo &#62;]