include::./index.adoc[]

[[v3-13-0]]
=== Levítico, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v3-13-1]]

^<<v3-13-1,1>>^ O SENHOR disse a Moisés e a Arão:

[[v3-13-2]]

^<<v3-13-2,2>>^ "Se alguém tiver um inchaço, uma erupção ou uma descoloração que possa ser sinal de lepra, essa pessoa será levada ao sacerdote Arão ou a um de seus filhos.

[[v3-13-3]]

^<<v3-13-3,3>>^ O sacerdote examinará a região afetada da pele. Se houver ali pelos que ficaram brancos e parecer que o problema é mais profundo que a pele, é lepra, e o sacerdote que examinar a pessoa a declarará cerimonialmente impura.

[[v3-13-4]]

^<<v3-13-4,4>>^ "Se, contudo, a região afetada da pele apresentar apenas uma descoloração branca e a mancha não for mais profunda que a pele, e se os pelos da região não se tornaram brancos, o sacerdote isolará a pessoa por sete dias.

[[v3-13-5]]

^<<v3-13-5,5>>^ No sétimo dia, ele a examinará novamente. Se constatar que a região afetada não mudou e o problema não se espalhou pela pele, isolará a pessoa por mais sete dias.

[[v3-13-6]]

^<<v3-13-6,6>>^ No sétimo dia, voltará a examiná-la. Se constatar que a área afetada diminuiu e não se espalhou, o sacerdote declarará a pessoa cerimonialmente pura; era apenas uma erupção. A pessoa lavará suas roupas e ficará pura.

[[v3-13-7]]

^<<v3-13-7,7>>^ Mas, se a erupção vier a se espalhar depois de o sacerdote examinar a pessoa e a declarar pura, ela voltará para ser examinada.

[[v3-13-8]]

^<<v3-13-8,8>>^ Se o sacerdote constatar que a erupção se espalhou, declarará a pessoa cerimonialmente impura, pois é, de fato, lepra.

[[v3-13-9]]

^<<v3-13-9,9>>^ "Quem apresentar algum sinal de lepra irá ao sacerdote para ser examinado.

[[v3-13-10]]

^<<v3-13-10,10>>^ Se o sacerdote encontrar um inchaço branco na pele, se alguns pelos sobre a mancha tiverem ficado brancos e se houver uma ferida aberta na região afetada,

[[v3-13-11]]

^<<v3-13-11,11>>^ é um caso crônico de lepra, e o sacerdote declarará a pessoa cerimonialmente impura. Nesses casos, não será necessário isolar a pessoa para avaliá-la, pois é evidente que a pele está contaminada pela doença.

[[v3-13-12]]

^<<v3-13-12,12>>^ "Se a lepra se espalhar por toda a pele da pessoa e cobrir seu corpo da cabeça aos pés, o sacerdote examinará a pessoa infectada.

[[v3-13-13]]

^<<v3-13-13,13>>^ Se constatar que a doença cobre todo o corpo, declarará a pessoa cerimonialmente pura. Uma vez que a pele se tornou completamente branca, a pessoa está pura.

[[v3-13-14]]

^<<v3-13-14,14>>^ Mas, se aparecerem feridas abertas, a pessoa infectada será declarada cerimonialmente impura.

[[v3-13-15]]

^<<v3-13-15,15>>^ O sacerdote fará essa declaração assim que vir uma ferida aberta, pois esse tipo de ferida indica a presença de lepra.

[[v3-13-16]]

^<<v3-13-16,16>>^ Se, contudo, as feridas sararem e se tornarem brancas como o resto da pele, a pessoa voltará ao sacerdote

[[v3-13-17]]

^<<v3-13-17,17>>^ para ser examinada. Se as regiões afetadas tiverem, de fato, se tornado brancas, o sacerdote declarará a pessoa cerimonialmente pura, e assim ela estará.

[[v3-13-18]]

^<<v3-13-18,18>>^ "Se alguém tiver na pele uma ferida purulenta e ela sarar,

[[v3-13-19]]

^<<v3-13-19,19>>^ mas surgir em seu lugar um inchaço branco ou uma mancha branca avermelhada, a pessoa irá ao sacerdote para ser examinada.

[[v3-13-20]]

^<<v3-13-20,20>>^ Se o sacerdote a examinar e constatar que a mancha é mais profunda que a pele, e se os pelos da região afetada tiverem ficado brancos, o sacerdote declarará a pessoa cerimonialmente impura. A ferida purulenta indica lepra.

[[v3-13-21]]

^<<v3-13-21,21>>^ Mas, se o sacerdote não encontrar pelos brancos na região afetada e parecer que a mancha não é mais profunda que a pele, e até diminuiu, o sacerdote isolará a pessoa por sete dias.

[[v3-13-22]]

^<<v3-13-22,22>>^ Se, nesse período, a mancha ou o inchaço se espalharem na pele, o sacerdote declarará a pessoa cerimonialmente impura, pois é sinal de lepra.

[[v3-13-23]]

^<<v3-13-23,23>>^ Se, contudo, a região afetada não aumentar nem se espalhar, é apenas a cicatriz da ferida, e o sacerdote declarará a pessoa cerimonialmente pura.

[[v3-13-24]]

^<<v3-13-24,24>>^ "Se alguém sofrer uma queimadura na pele e aparecerem na região feridas abertas de cor branca avermelhada ou completamente branca,

[[v3-13-25]]

^<<v3-13-25,25>>^ o sacerdote a examinará. Se constatar que os pelos na região afetada ficaram brancos, e se parecer que a mancha é mais profunda que a pele, surgiu lepra na queimadura. O sacerdote declarará a pessoa cerimonialmente impura, pois, sem dúvida, é lepra.

[[v3-13-26]]

^<<v3-13-26,26>>^ Mas, se não encontrar pelos brancos na região afetada, e se parecer que a ferida não é mais profunda que a pele e tiver diminuído, o sacerdote isolará a pessoa por sete dias.

[[v3-13-27]]

^<<v3-13-27,27>>^ No sétimo dia, examinará a pessoa novamente. Se o problema tiver se espalhado na pele, o sacerdote declarará a pessoa cerimonialmente impura, pois, sem dúvida, é lepra.

[[v3-13-28]]

^<<v3-13-28,28>>^ Se, contudo, a região afetada não tiver mudado ou se o problema não tiver se espalhado na pele, mas tiver diminuído, é apenas o inchaço da queimadura. O sacerdote declarará a pessoa cerimonialmente pura, pois é apenas a cicatriz da queimadura.

[[v3-13-29]]

^<<v3-13-29,29>>^ "Se um homem ou uma mulher tiver uma ferida na cabeça ou no queixo,

[[v3-13-30]]

^<<v3-13-30,30>>^ o sacerdote a examinará. Se constatar que a mancha é mais profunda que a pele e tem pelos amarelados e finos, o sacerdote declarará a pessoa cerimonialmente impura. É uma ferida causada por sarna na cabeça ou no queixo.

[[v3-13-31]]

^<<v3-13-31,31>>^ Se o sacerdote examinar a ferida e constatar que não é mais profunda que a pele, mas não tem pelos escuros, isolará a pessoa por sete dias.

[[v3-13-32]]

^<<v3-13-32,32>>^ No sétimo dia, o sacerdote examinará a ferida novamente. Se constatar que ela não se espalhou, que não há pelos amarelados e que não parece mais profunda que a pele,

[[v3-13-33]]

^<<v3-13-33,33>>^ a pessoa raspará todos os pelos, exceto na região afetada. Em seguida, o sacerdote isolará a pessoa infectada por mais sete dias.

[[v3-13-34]]

^<<v3-13-34,34>>^ No sétimo dia, examinará a ferida novamente. Se ela não tiver se espalhado, e se não parecer mais profunda que a pele, o sacerdote declarará a pessoa cerimonialmente pura. A pessoa lavará suas roupas e ficará pura.

[[v3-13-35]]

^<<v3-13-35,35>>^ Mas, se a ferida de sarna começar a se espalhar depois de a pessoa ter sido declarada cerimonialmente pura,

[[v3-13-36]]

^<<v3-13-36,36>>^ o sacerdote a examinará novamente. Se constatar que a ferida se espalhou, não é necessário procurar pelos amarelados; a pessoa infectada está cerimonialmente impura.

[[v3-13-37]]

^<<v3-13-37,37>>^ Se, contudo, a cor da ferida de sarna não mudar e pelos pretos voltarem a crescer na região afetada, a sarna está curada, e o sacerdote declarará a pessoa cerimonialmente pura.

[[v3-13-38]]

^<<v3-13-38,38>>^ "Se um homem ou uma mulher tiver manchas brancas na pele,

[[v3-13-39]]

^<<v3-13-39,39>>^ o sacerdote examinará a região afetada. Se constatar que as manchas brancas são opacas, é uma simples erupção de pele, e a pessoa está cerimonialmente pura.

[[v3-13-40]]

^<<v3-13-40,40>>^ "Se os cabelos de um homem caírem e ele ficar calvo, continua cerimonialmente puro.

[[v3-13-41]]

^<<v3-13-41,41>>^ Se caírem os cabelos da parte da frente da cabeça, ele simplesmente ficou calvo na frente e continua puro.

[[v3-13-42]]

^<<v3-13-42,42>>^ Mas, se uma ferida branca avermelhada aparecer na região calva no alto ou na parte de trás da cabeça, é lepra.

[[v3-13-43]]

^<<v3-13-43,43>>^ O sacerdote o examinará e, se constatar que há inchaço ao redor da ferida branca avermelhada em qualquer parte da calva do homem com aparência de lepra,

[[v3-13-44]]

^<<v3-13-44,44>>^ o homem está, de fato, infectado com lepra e está impuro. O sacerdote o declarará cerimonialmente impuro por causa da ferida na cabeça.

[[v3-13-45]]

^<<v3-13-45,45>>^ "Quem sofrer de lepra rasgará as roupas e deixará o cabelo despenteado. Cobrirá a boca e gritará: ‘Impuro! Impuro!’.

[[v3-13-46]]

^<<v3-13-46,46>>^ Enquanto durar a lepra, ficará cerimonialmente impuro e viverá isolado, fora do acampamento." O procedimento para roupas contaminadas

[[v3-13-47]]

^<<v3-13-47,47>>^ "Quando o mofo contaminar uma peça de roupa de lã ou de linho,

[[v3-13-48]]

^<<v3-13-48,48>>^ um tecido de lã ou de linho, a pele de um animal ou qualquer objeto de couro,

[[v3-13-49]]

^<<v3-13-49,49>>^ e quando a região contaminada da roupa, da pele do animal, do tecido liso ou trançado, ou do artigo de couro se tornar esverdeada ou avermelhada, está contaminada com mofo e deverá ser mostrada ao sacerdote.

[[v3-13-50]]

^<<v3-13-50,50>>^ Depois de examinar a região afetada, o sacerdote isolará o objeto afetado por sete dias.

[[v3-13-51]]

^<<v3-13-51,51>>^ No sétimo dia, examinará o objeto novamente. Se a região afetada tiver se espalhado, a peça de roupa, o tecido liso ou trançado ou o artigo de couro foi, sem dúvida, contaminado por mofo corrosivo e está cerimonialmente impuro.

[[v3-13-52]]

^<<v3-13-52,52>>^ O sacerdote queimará a peça de roupa, o tecido de lã ou de linho ou o artigo de couro, pois foi contaminado por mofo corrosivo. Deve ser completamente destruído com fogo.

[[v3-13-53]]

^<<v3-13-53,53>>^ "Se, contudo, o sacerdote examinar o objeto e constatar que a região contaminada não se espalhou pela peça de roupa, pelo tecido liso ou trançado, ou pelo artigo de couro,

[[v3-13-54]]

^<<v3-13-54,54>>^ ordenará que o objeto seja lavado e, depois, isolado por mais sete dias.

[[v3-13-55]]

^<<v3-13-55,55>>^ O sacerdote examinará novamente o objeto depois de lavado. Se constatar que a região contaminada não mudou de cor depois de ser lavada, mesmo que a mancha não tenha se espalhado, o objeto está contaminado. Deve ser completamente queimado, quer o mofo esteja do lado de dentro ou de fora.

[[v3-13-56]]

^<<v3-13-56,56>>^ Mas, se o sacerdote examinar o objeto e constatar que a região contaminada diminuiu depois de ser lavada, cortará a mancha da peça de roupa, do tecido liso ou trançado, ou do couro.

[[v3-13-57]]

^<<v3-13-57,57>>^ Se a mancha reaparecer na peça de roupa, no tecido liso ou trançado, ou no artigo de couro, é evidente que o mofo está se espalhando, e o objeto contaminado deverá ser queimado.

[[v3-13-58]]

^<<v3-13-58,58>>^ Se, contudo, a mancha desaparecer da peça de roupa, do tecido, ou do artigo de couro depois de ter sido lavado, o objeto será lavado novamente e, por fim, estará cerimonialmente puro.

[[v3-13-59]]

^<<v3-13-59,59>>^ "Essas são as instruções referentes ao mofo que contamina roupas de lã ou linho, tecidos lisos ou trançados ou qualquer objeto de couro. É dessa forma que o sacerdote determinará se os objetos estão cerimonialmente puros ou impuros".

'''

xref:003-levitico/003-levitico-012.adoc#v3-12-0[&#60; Capítulo Anterior] | <<v3-13-0,Topo>> | xref:003-levitico/003-levitico-014.adoc#v3-14-0[Próximo Capítulo &#62;]