include::./index.adoc[]

[[v3-25-0]]
=== Levítico, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v3-25-1]]

^<<v3-25-1,1>>^ Quando Moisés estava no monte Sinai, o SENHOR lhe disse:

[[v3-25-2]]

^<<v3-25-2,2>>^ "Dê as seguintes instruções ao povo de Israel. Quando entrarem na terra que eu lhes dou, a terra deverá observar um sábado para o SENHOR a cada sete anos.

[[v3-25-3]]

^<<v3-25-3,3>>^ Durante seis anos, vocês semearão os campos, podarão os vinhedos e farão a colheita,

[[v3-25-4]]

^<<v3-25-4,4>>^ mas no sétimo ano a terra terá um ano sabático de descanso absoluto. É o sábado do SENHOR. Durante esse ano, não semeiem os campos nem façam a poda dos vinhedos.

[[v3-25-5]]

^<<v3-25-5,5>>^ Não ceifem o que crescer espontaneamente nem colham as uvas dos vinhedos não podados. A terra terá um ano de descanso absoluto.

[[v3-25-6]]

^<<v3-25-6,6>>^ Comam o que a terra produzir espontaneamente durante seu descanso. Isso se aplica a vocês, a seus filhos, a seus servos e servas, e também aos trabalhadores contratados e aos residentes temporários que vivem em seu meio.

[[v3-25-7]]

^<<v3-25-7,7>>^ Seus rebanhos e todos os animais selvagens de sua terra também poderão comer o que a terra produzir." O Ano do Jubileu

[[v3-25-8]]

^<<v3-25-8,8>>^ "Contem sete anos sabáticos, sete vezes sete anos, no total de 49 anos.

[[v3-25-9]]

^<<v3-25-9,9>>^ Então, no Dia da Expiação do ano seguinte, façam soar por toda a terra um toque longo e alto de trombeta.

[[v3-25-10]]

^<<v3-25-10,10>>^ Consagrem esse ano, o quinquagésimo ano, como um tempo de proclamar a liberdade por toda a terra para todos os seus habitantes. Será um ano de jubileu para vocês, no qual cada um poderá voltar à terra que pertencia a seus antepassados e regressar a seu próprio clã.

[[v3-25-11]]

^<<v3-25-11,11>>^ O quinquagésimo ano será um jubileu para vocês. Nesse ano, não semearão os campos, nem ceifarão o que crescer espontaneamente, nem colherão as uvas dos vinhedos não podados.

[[v3-25-12]]

^<<v3-25-12,12>>^ Será um ano de jubileu para vocês e deverão mantê-lo santo. Comam o que a terra produzir espontaneamente.

[[v3-25-13]]

^<<v3-25-13,13>>^ No Ano do Jubileu, cada um poderá retornar à terra que pertencia a seus antepassados.

[[v3-25-14]]

^<<v3-25-14,14>>^ "Quando alguém fizer um acordo com o seu próximo para comprar ou vender uma propriedade, não deverá tirar vantagem do outro.

[[v3-25-15]]

^<<v3-25-15,15>>^ Ao comprar um terreno do seu próximo, o preço a ser pago será baseado no número de anos desde o último jubileu. O vendedor estipulará o preço levando em conta os anos que ainda restam de colheitas.

[[v3-25-16]]

^<<v3-25-16,16>>^ Quanto mais colheitas faltarem para o próximo jubileu, mais alto será o preço; quanto menos anos faltarem, mais baixo será o preço. Afinal, o que ele está vendendo é certo número de colheitas.

[[v3-25-17]]

^<<v3-25-17,17>>^ Mostrem seu temor a Deus não tirando vantagem um do outro. Eu sou o SENHOR, seu Deus.

[[v3-25-18]]

^<<v3-25-18,18>>^ "Se quiserem viver seguros na terra, sigam os meus decretos e obedeçam aos meus estatutos.

[[v3-25-19]]

^<<v3-25-19,19>>^ Então a terra produzirá colheitas fartas, vocês comerão até se saciarem e viverão em segurança.

[[v3-25-20]]

^<<v3-25-20,20>>^ Talvez vocês perguntem: ‘O que comeremos no sétimo ano, uma vez que não temos permissão de semear nem de colher nesse ano?’.

[[v3-25-21]]

^<<v3-25-21,21>>^ Podem ter certeza de que no sexto ano eu lhes enviarei a minha bênção, de modo que a terra produzirá o suficiente para três anos.

[[v3-25-22]]

^<<v3-25-22,22>>^ No oitavo ano, quando semearem seus campos, ainda estarão comendo da colheita farta do sexto ano. De fato, ainda estarão comendo dessa colheita quando fizerem a nova colheita no nono ano." O resgate de propriedades

[[v3-25-23]]

^<<v3-25-23,23>>^ "A terra jamais será vendida em caráter definitivo, pois ela me pertence. Vocês são apenas estrangeiros e arrendatários que trabalham para mim.

[[v3-25-24]]

^<<v3-25-24,24>>^ "Sempre que uma propriedade for negociada, o vendedor deverá ter o direito de comprá-la de volta.

[[v3-25-25]]

^<<v3-25-25,25>>^ Se alguém do seu povo empobrecer e for obrigado a vender parte das terras da família, um parente próximo deverá comprar a propriedade de volta para ele.

[[v3-25-26]]

^<<v3-25-26,26>>^ Se não houver qualquer parente próximo para comprar a propriedade, mas a pessoa que a vendeu conseguir dinheiro suficiente para comprá-la de volta,

[[v3-25-27]]

^<<v3-25-27,27>>^ terá o direito de resgatá-la de quem a comprou. Do preço da terra será descontado um valor proporcional ao número de anos até o próximo Ano do Jubileu. Desse modo, o primeiro dono da propriedade terá condições de retornar à sua terra.

[[v3-25-28]]

^<<v3-25-28,28>>^ Se, contudo, o primeiro dono não tiver condições de comprar de volta a propriedade, ela ficará com o novo dono até o Ano do Jubileu seguinte. Nesse ano, a propriedade será devolvida aos primeiros donos, a fim de que voltem à terra de sua família.

[[v3-25-29]]

^<<v3-25-29,29>>^ "Quem vender uma casa dentro de uma cidade murada terá, por um ano completo, o direito de comprá-la de volta. Durante esse ano, o vendedor poderá resgatar a casa.

[[v3-25-30]]

^<<v3-25-30,30>>^ Mas, se não a comprar de volta durante esse ano, a venda da casa dentro da cidade murada não poderá ser revertida. A casa se tornará propriedade permanente do comprador. Não será devolvida ao primeiro dono no Ano do Jubileu.

[[v3-25-31]]

^<<v3-25-31,31>>^ Já uma casa num povoado, num assentamento sem muros ao redor, será considerada uma propriedade rural. Poderá ser comprada de volta a qualquer momento e será devolvida ao primeiro proprietário no Ano do Jubileu.

[[v3-25-32]]

^<<v3-25-32,32>>^ "Os levitas sempre terão o direito de comprar de volta uma casa que tiverem vendido dentro das cidades reservadas para eles.

[[v3-25-33]]

^<<v3-25-33,33>>^ Qualquer propriedade vendida pelos levitas, ou seja, todas as casas dentro das cidades deles, será devolvida no Ano do Jubileu. Afinal, essas casas são suas únicas propriedades em todo o Israel.

[[v3-25-34]]

^<<v3-25-34,34>>^ As pastagens em volta das cidades dos levitas não serão vendidas. São propriedade permanente deles." O resgate dos pobres e dos escravos

[[v3-25-35]]

^<<v3-25-35,35>>^ "Se alguém do seu povo empobrecer e não puder se sustentar, ajudem-no como ajudariam um estrangeiro ou residente temporário e permitam que ele more com vocês.

[[v3-25-36]]

^<<v3-25-36,36>>^ Não cobrem juros nem tenham lucro à custa dele. Em vez disso, mostrem seu temor a Deus permitindo que ele viva como parente com vocês.

[[v3-25-37]]

^<<v3-25-37,37>>^ Lembrem-se de não cobrar juros sobre o dinheiro que lhe emprestarem nem de ter lucro com o alimento que lhe venderem.

[[v3-25-38]]

^<<v3-25-38,38>>^ Eu sou o SENHOR, seu Deus, que os tirou da terra do Egito para lhes dar a terra de Canaã e ser o seu Deus.

[[v3-25-39]]

^<<v3-25-39,39>>^ "Se alguém do seu povo empobrecer e for obrigado a se vender para vocês, não o tratem como escravo.

[[v3-25-40]]

^<<v3-25-40,40>>^ Tratem-no como empregado ou residente temporário que mora com vocês e os servirá apenas até o Ano do Jubileu.

[[v3-25-41]]

^<<v3-25-41,41>>^ Então ele e seus filhos estarão livres e voltarão aos clãs e à propriedade que pertencia a seus antepassados.

[[v3-25-42]]

^<<v3-25-42,42>>^ Os israelitas são os meus servos que eu tirei da terra do Egito, de modo que jamais devem ser vendidos como escravos.

[[v3-25-43]]

^<<v3-25-43,43>>^ Mostrem seu temor a Deus tratando-os sem violência.

[[v3-25-44]]

^<<v3-25-44,44>>^ "Vocês poderão comprar escravos e escravas de nações vizinhas.

[[v3-25-45]]

^<<v3-25-45,45>>^ Também poderão comprar os filhos de residentes temporários que moram com vocês, incluindo os que nasceram em sua terra. Poderão considerá-los sua propriedade

[[v3-25-46]]

^<<v3-25-46,46>>^ e deixá-los para seus filhos como herança permanente. Poderão tratá-los como escravos, mas jamais oprimirão alguém do seu povo.

[[v3-25-47]]

^<<v3-25-47,47>>^ "Se algum estrangeiro ou residente temporário enriquecer enquanto vive entre vocês, e se algum do seu povo empobrecer e for obrigado a se vender para esse estrangeiro ou para um membro da família dele,

[[v3-25-48]]

^<<v3-25-48,48>>^ continuará a ter o direito de ser resgatado, mesmo depois de comprado. Poderá ser comprado de volta por um irmão,

[[v3-25-49]]

^<<v3-25-49,49>>^ tio ou primo. Aliás, qualquer parente próximo poderá resgatá-lo. Se prosperar, também poderá resgatar a si mesmo.

[[v3-25-50]]

^<<v3-25-50,50>>^ Negociará o preço de sua liberdade com a pessoa que o comprou. O preço será baseado no número de anos transcorridos desde que foi vendido até o próximo Ano do Jubileu, ou seja, o equivalente ao custo de um trabalhador contratado para esse período.

[[v3-25-51]]

^<<v3-25-51,51>>^ Se ainda faltarem muitos anos para o jubileu, pagará na devida proporção aquilo que recebeu quando vendeu a si mesmo.

[[v3-25-52]]

^<<v3-25-52,52>>^ Se faltarem apenas poucos anos até o Ano do Jubileu, pagará proporcionalmente aos anos que faltarem.

[[v3-25-53]]

^<<v3-25-53,53>>^ O estrangeiro o tratará como um empregado com contrato anual. Não permitam que um estrangeiro trate israelitas com violência.

[[v3-25-54]]

^<<v3-25-54,54>>^ Se algum israelita não tiver sido comprado de volta, será liberto quando chegar o Ano do Jubileu, ele e seus filhos,

[[v3-25-55]]

^<<v3-25-55,55>>^ pois os israelitas me pertencem. São meus servos que eu tirei da terra do Egito. Eu sou o SENHOR, seu Deus."

'''

xref:003-levitico/003-levitico-024.adoc#v3-24-0[&#60; Capítulo Anterior] | <<v3-25-0,Topo>> | xref:003-levitico/003-levitico-026.adoc#v3-26-0[Próximo Capítulo &#62;]