include::./index.adoc[]

[[v3-1-0]]
=== Levítico, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v3-1-1]]

^<<v3-1-1,1>>^ Da tenda do encontro, o SENHOR chamou Moisés e lhe disse:

[[v3-1-2]]

^<<v3-1-2,2>>^ "Dê as seguintes instruções ao povo de Israel. Quando você apresentar um animal como oferta para o SENHOR, escolha-o dos rebanhos de gado, ovelhas ou cabras.

[[v3-1-3]]

^<<v3-1-3,3>>^ "Se o animal que apresentar como holocausto for do rebanho de gado, deverá ser um macho sem defeito. Leve-o até a entrada da tenda do encontro, para que seja aceito pelo SENHOR.

[[v3-1-4]]

^<<v3-1-4,4>>^ Coloque a mão sobre a cabeça do animal, para que seja aceito em seu lugar como expiação.

[[v3-1-5]]

^<<v3-1-5,5>>^ Mate o novilho na presença do SENHOR, e os filhos de Arão, os sacerdotes, oferecerão o sangue do animal, derramando-o em todos os lados do altar que está à entrada da tenda do encontro.

[[v3-1-6]]

^<<v3-1-6,6>>^ Depois, tire a pele do animal e corte-o em pedaços.

[[v3-1-7]]

^<<v3-1-7,7>>^ Os filhos do sacerdote Arão acenderão o fogo no altar e ali arrumarão a lenha.

[[v3-1-8]]

^<<v3-1-8,8>>^ Arrumarão também os pedaços da oferta, incluindo a cabeça e a gordura, sobre a lenha acesa no altar,

[[v3-1-9]]

^<<v3-1-9,9>>^ mas os órgãos internos e as pernas serão lavados primeiro com água. Então o sacerdote queimará tudo no altar como holocausto. É uma oferta especial, um aroma agradável ao SENHOR.

[[v3-1-10]]

^<<v3-1-10,10>>^ "Se o animal que apresentar como holocausto for um carneiro ou um cabrito, deverá ser um macho sem defeito.

[[v3-1-11]]

^<<v3-1-11,11>>^ Mate o animal junto ao lado norte do altar, na presença do SENHOR, e os filhos de Arão, os sacerdotes, derramarão o sangue do animal em todos os lados do altar.

[[v3-1-12]]

^<<v3-1-12,12>>^ Depois, corte o animal em pedaços, incluindo a cabeça e a gordura. Os sacerdotes arrumarão os pedaços da oferta sobre a lenha acesa no altar,

[[v3-1-13]]

^<<v3-1-13,13>>^ mas os órgãos internos e as pernas serão lavados primeiro com água. Então o sacerdote queimará tudo no altar como holocausto. É uma oferta especial, um aroma agradável ao SENHOR.

[[v3-1-14]]

^<<v3-1-14,14>>^ "Se apresentar ao SENHOR uma ave como holocausto, deverá ser uma rolinha ou um pombinho.

[[v3-1-15]]

^<<v3-1-15,15>>^ O sacerdote levará a ave até o altar, destroncará a cabeça dela e deixará o sangue escorrer na lateral do altar. Em seguida, queimará a ave.

[[v3-1-16]]

^<<v3-1-16,16>>^ O sacerdote removerá o papo e as penas da cauda da ave e os lançará do lado leste do altar, sobre as cinzas.

[[v3-1-17]]

^<<v3-1-17,17>>^ Depois, segurando a ave pelas asas, o sacerdote a partirá, mas sem despedaçá-la, e a apresentará como holocausto sobre a lenha acesa no altar. É uma oferta especial, um aroma agradável ao SENHOR."

'''

xref:002-exodo/002-exodo-040.adoc#v2-40-0[&#60; Capítulo Anterior] | <<v3-1-0,Topo>> | xref:003-levitico/003-levitico-002.adoc#v3-2-0[Próximo Capítulo &#62;]