include::./index.adoc[]

[[v3-9-0]]
=== Levítico, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v3-9-1]]

^<<v3-9-1,1>>^ No oitavo dia, depois da cerimônia de consagração, Moisés reuniu Arão, seus filhos e os líderes de Israel

[[v3-9-2]]

^<<v3-9-2,2>>^ e disse a Arão: "Escolha um bezerro para a oferta pelo pecado e um carneiro para o holocausto, ambos sem defeito, e apresente-os ao SENHOR.

[[v3-9-3]]

^<<v3-9-3,3>>^ Depois, diga aos israelitas: ‘Escolham um bode para a oferta pelo pecado e um bezerro e um cordeiro, ambos de um ano e sem defeito, para o holocausto.

[[v3-9-4]]

^<<v3-9-4,4>>^ Escolham também um boi e um carneiro para a oferta de paz, além de farinha misturada com azeite para a oferta de cereal. Apresentem todas essas ofertas ao SENHOR, pois hoje o SENHOR aparecerá a vocês’".

[[v3-9-5]]

^<<v3-9-5,5>>^ O povo trouxe todas essas coisas à entrada da tenda do encontro, conforme Moisés tinha ordenado. Assim, toda a comunidade se aproximou e permaneceu em pé diante do SENHOR.

[[v3-9-6]]

^<<v3-9-6,6>>^ Então Moisés disse: "É isto que o SENHOR ordenou que façam para que a glória do SENHOR lhes apareça".

[[v3-9-7]]

^<<v3-9-7,7>>^ Em seguida, Moisés disse a Arão: "Venha até o altar e apresente sua oferta pelo pecado e seu holocausto para fazer expiação por si mesmo e pelo povo. Apresente as ofertas do povo para fazer expiação por eles, conforme o SENHOR ordenou".

[[v3-9-8]]

^<<v3-9-8,8>>^ Arão foi até o altar e matou o bezerro como oferta pelo pecado por si mesmo.

[[v3-9-9]]

^<<v3-9-9,9>>^ Seus filhos lhe trouxeram o sangue, e Arão molhou o dedo nele e o colocou nas pontas do altar. O restante do sangue ele derramou na base do altar.

[[v3-9-10]]

^<<v3-9-10,10>>^ Queimou no altar a gordura, os rins e o lóbulo do fígado da oferta pelo pecado, conforme o SENHOR havia ordenado a Moisés.

[[v3-9-11]]

^<<v3-9-11,11>>^ A carne e o couro, porém, queimou fora do acampamento.

[[v3-9-12]]

^<<v3-9-12,12>>^ Então Arão matou o animal para o holocausto. Seus filhos lhe trouxeram o sangue, e ele o derramou em todos os lados do altar.

[[v3-9-13]]

^<<v3-9-13,13>>^ Entregaram-lhe cada um dos pedaços do holocausto, incluindo a cabeça, e ele os queimou no altar.

[[v3-9-14]]

^<<v3-9-14,14>>^ Lavou os órgãos internos e as pernas e os queimou no altar junto com o restante do holocausto.

[[v3-9-15]]

^<<v3-9-15,15>>^ Em seguida, Arão apresentou as ofertas do povo. Matou o bode do povo e o apresentou como oferta pelo pecado deles, como havia feito com a oferta por seu próprio pecado.

[[v3-9-16]]

^<<v3-9-16,16>>^ Depois, apresentou o holocausto e o ofereceu de acordo com a forma prescrita.

[[v3-9-17]]

^<<v3-9-17,17>>^ Apresentou também a oferta de cereal e queimou no altar um punhado dela, além do holocausto da manhã.

[[v3-9-18]]

^<<v3-9-18,18>>^ Arão matou o boi e o carneiro para a oferta de paz do povo. Seus filhos lhe trouxeram o sangue, e ele o derramou em todos os lados do altar.

[[v3-9-19]]

^<<v3-9-19,19>>^ Depois, pegou a gordura do boi e do carneiro, incluindo a gordura da parte gorda da cauda e a gordura que envolve os órgãos internos, bem como os rins e o lóbulo do fígado de cada animal,

[[v3-9-20]]

^<<v3-9-20,20>>^ colocou as porções de gordura sobre o peito dos animais e as queimou no altar.

[[v3-9-21]]

^<<v3-9-21,21>>^ Arão moveu o peito e a coxa direita dos animais para o alto como oferta especial para o SENHOR, conforme Moisés havia ordenado.

[[v3-9-22]]

^<<v3-9-22,22>>^ Por fim, Arão ergueu as mãos na direção do povo e o abençoou. Depois de apresentar a oferta pelo pecado, o holocausto e a oferta de paz, desceu do altar.

[[v3-9-23]]

^<<v3-9-23,23>>^ Então Moisés e Arão entraram na tenda do encontro e, quando voltaram, abençoaram o povo novamente, e a glória do SENHOR apareceu a todo o povo.

[[v3-9-24]]

^<<v3-9-24,24>>^ Fogo saiu da presença do SENHOR e consumiu o holocausto e a gordura no altar. Quando eles viram isso, gritaram de alegria e se prostraram com o rosto no chão.

'''

xref:003-levitico/003-levitico-008.adoc#v3-8-0[&#60; Capítulo Anterior] | <<v3-9-0,Topo>> | xref:003-levitico/003-levitico-010.adoc#v3-10-0[Próximo Capítulo &#62;]