include::./index.adoc[]

[[v3-4-0]]
=== Levítico, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v3-4-1]]

^<<v3-4-1,1>>^ Então o SENHOR disse a Moisés:

[[v3-4-2]]

^<<v3-4-2,2>>^ "Dê as seguintes instruções ao povo de Israel. É isto que devem fazer aqueles que pecam sem intenção, quebrando algum dos mandamentos do SENHOR.

[[v3-4-3]]

^<<v3-4-3,3>>^ "Se o sacerdote ungido pecar, trazendo culpa sobre todo o povo, apresentará ao SENHOR um novilho sem defeito como oferta pelo pecado que cometeu.

[[v3-4-4]]

^<<v3-4-4,4>>^ Trará o novilho perante o SENHOR à entrada da tenda do encontro, colocará a mão sobre a cabeça do animal e o matará diante do SENHOR.

[[v3-4-5]]

^<<v3-4-5,5>>^ O sacerdote ungido levará um pouco do sangue do novilho para dentro da tenda do encontro,

[[v3-4-6]]

^<<v3-4-6,6>>^ molhará o dedo no sangue e com ele aspergirá sete vezes diante do SENHOR, em frente à cortina interna do santuário.

[[v3-4-7]]

^<<v3-4-7,7>>^ Em seguida, o sacerdote colocará um pouco do sangue nas pontas do altar de incenso perfumado que está na presença do SENHOR, dentro da tenda do encontro. O restante do sangue do novilho ele derramará na base do altar do holocausto, à entrada da tenda do encontro.

[[v3-4-8]]

^<<v3-4-8,8>>^ Depois, removerá toda a gordura do novilho a ser apresentado como oferta pelo pecado, incluindo a gordura que envolve os órgãos internos,

[[v3-4-9]]

^<<v3-4-9,9>>^ os dois rins, a gordura ao redor deles perto dos lombos e o lóbulo do fígado. Removerá todas essas partes junto com os rins,

[[v3-4-10]]

^<<v3-4-10,10>>^ como se faz com os animais apresentados como oferta de paz, e queimará tudo no altar do holocausto.

[[v3-4-11]]

^<<v3-4-11,11>>^ Mas o que restar do novilho — o couro, a carne, a cabeça, as pernas, os órgãos internos e os excrementos —

[[v3-4-12]]

^<<v3-4-12,12>>^ ele tomará e levará para um lugar cerimonialmente puro, fora do acampamento, onde são jogadas as cinzas. Ali, sobre o monte de cinzas, queimará os restos num fogo feito com lenha.

[[v3-4-13]]

^<<v3-4-13,13>>^ "Se toda a comunidade de Israel pecar, quebrando algum dos mandamentos do SENHOR, mas não se der conta disso, ainda assim será culpada.

[[v3-4-14]]

^<<v3-4-14,14>>^ Quando perceber seu pecado, o povo trará um novilho como oferta pelo pecado e o apresentará à entrada da tenda do encontro.

[[v3-4-15]]

^<<v3-4-15,15>>^ As autoridades da comunidade colocarão as mãos sobre a cabeça do novilho e o matarão diante do SENHOR.

[[v3-4-16]]

^<<v3-4-16,16>>^ O sacerdote ungido levará um pouco do sangue do novilho para dentro da tenda do encontro,

[[v3-4-17]]

^<<v3-4-17,17>>^ molhará o dedo no sangue e com ele aspergirá sete vezes diante do SENHOR, em frente à cortina interna.

[[v3-4-18]]

^<<v3-4-18,18>>^ Em seguida, colocará um pouco do sangue nas pontas do altar que está na presença do SENHOR, dentro da tenda do encontro. O restante do sangue do novilho ele derramará na base do altar do holocausto, à entrada da tenda do encontro.

[[v3-4-19]]

^<<v3-4-19,19>>^ Depois, removerá toda a gordura do novilho e a queimará no altar,

[[v3-4-20]]

^<<v3-4-20,20>>^ como se faz com o novilho apresentado como oferta pelo pecado. Desse modo, o sacerdote fará expiação pelo povo, e eles serão perdoados.

[[v3-4-21]]

^<<v3-4-21,21>>^ Então o sacerdote tomará o que restar do novilho, levará para fora do acampamento e o queimará ali, como se faz com a oferta pelo pecado. Essa oferta é pelo pecado de toda a comunidade de Israel.

[[v3-4-22]]

^<<v3-4-22,22>>^ "Se um dos líderes do povo pecar, quebrando algum dos mandamentos do SENHOR, seu Deus, mas não se der conta disso, ainda assim será culpado.

[[v3-4-23]]

^<<v3-4-23,23>>^ Quando perceber seu pecado, o líder apresentará como oferta um bode sem defeito.

[[v3-4-24]]

^<<v3-4-24,24>>^ Colocará a mão sobre a cabeça do bode e o matará diante do SENHOR, no mesmo lugar onde são mortos os animais para os holocaustos. É uma oferta pelo pecado.

[[v3-4-25]]

^<<v3-4-25,25>>^ O sacerdote molhará o dedo no sangue da oferta pelo pecado e o colocará nas pontas do altar do holocausto. O restante do sangue ele derramará na base do altar.

[[v3-4-26]]

^<<v3-4-26,26>>^ Em seguida, queimará no altar toda a gordura do bode, como se faz com a oferta de paz. Desse modo, o sacerdote fará expiação pelo líder, e ele será perdoado.

[[v3-4-27]]

^<<v3-4-27,27>>^ "Se outra pessoa do povo pecar, quebrando algum dos mandamentos do SENHOR, mas não se der conta disso, ainda assim será culpada.

[[v3-4-28]]

^<<v3-4-28,28>>^ Quando perceber seu pecado, ela apresentará como oferta pelo pecado uma cabra sem defeito.

[[v3-4-29]]

^<<v3-4-29,29>>^ Colocará a mão sobre a cabeça do animal da oferta pelo pecado e o matará no mesmo lugar onde são mortos os animais para os holocaustos.

[[v3-4-30]]

^<<v3-4-30,30>>^ O sacerdote molhará o dedo no sangue e o colocará nas pontas do altar do holocausto. O restante do sangue ele derramará na base do altar.

[[v3-4-31]]

^<<v3-4-31,31>>^ Em seguida, removerá toda a gordura da cabra, como se faz com a oferta de paz, e a queimará sobre o altar como um aroma agradável ao SENHOR. Desse modo, o sacerdote fará expiação pela pessoa, e ela será perdoada.

[[v3-4-32]]

^<<v3-4-32,32>>^ "Se alguém trouxer uma ovelha como oferta pelo pecado, deverá ser sem defeito.

[[v3-4-33]]

^<<v3-4-33,33>>^ A pessoa colocará a mão sobre a cabeça do animal da oferta pelo pecado e o matará no mesmo lugar onde são mortos os animais para os holocaustos.

[[v3-4-34]]

^<<v3-4-34,34>>^ O sacerdote molhará o dedo no sangue da oferta pelo pecado e o colocará nas pontas do altar do holocausto. O restante do sangue ele derramará na base do altar.

[[v3-4-35]]

^<<v3-4-35,35>>^ Em seguida, removerá toda a gordura da ovelha, como se faz com a gordura do cordeiro apresentado como oferta de paz, e a queimará no altar como oferta especial apresentada ao SENHOR. Desse modo, o sacerdote fará expiação pela pessoa, e ela será perdoada."

'''

xref:003-levitico/003-levitico-003.adoc#v3-3-0[&#60; Capítulo Anterior] | <<v3-4-0,Topo>> | xref:003-levitico/003-levitico-005.adoc#v3-5-0[Próximo Capítulo &#62;]