include::./index.adoc[]

[[v3-6-0]]
=== Levítico, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v3-6-1]]

^<<v3-6-1,1>>^ Então o SENHOR disse a Moisés:

[[v3-6-2]]

^<<v3-6-2,2>>^ "Quando alguém pecar, enganando seu próximo, também estará cometendo um delito contra o SENHOR. Se esse alguém for desonesto num negócio que envolve depósito como garantia, ou roubar, ou praticar extorsão,

[[v3-6-3]]

^<<v3-6-3,3>>^ ou encontrar um objeto e negar que o encontrou, ou mentir depois de jurar dizer a verdade a respeito desse pecado, ou alguma prática semelhante,

[[v3-6-4]]

^<<v3-6-4,4>>^ será culpado pelo pecado que cometeu. Devolverá o que roubou, ou o valor que extorquiu, ou o depósito feito como garantia, ou o objeto perdido que encontrou,

[[v3-6-5]]

^<<v3-6-5,5>>^ ou qualquer coisa que tenha obtido com juramento falso. Fará restituição pagando à pessoa prejudicada o total, com um acréscimo de um quinto do valor. No mesmo dia, apresentará uma oferta pela culpa.

[[v3-6-6]]

^<<v3-6-6,6>>^ Como oferta pela culpa para o SENHOR, trará ao sacerdote um carneiro sem defeito do próprio rebanho, devidamente avaliado.

[[v3-6-7]]

^<<v3-6-7,7>>^ Desse modo, o sacerdote fará expiação pela pessoa diante do SENHOR, e ela será perdoada de qualquer desses pecados que tenha cometido". Instruções adicionais para os holocaustos

[[v3-6-8]]

^<<v3-6-8,8>>^ Então o SENHOR disse a Moisés:

[[v3-6-9]]

^<<v3-6-9,9>>^ "Dê a Arão e a seus filhos as seguintes instruções para os holocaustos. Os holocaustos serão deixados sobre o altar até a manhã seguinte, e o fogo sobre o altar será mantido aceso a noite toda.

[[v3-6-10]]

^<<v3-6-10,10>>^ Pela manhã, depois que o sacerdote de serviço tiver vestido suas roupas oficiais de linho e as roupas de baixo, também de linho, limpará as cinzas do holocausto e as colocará ao lado do altar.

[[v3-6-11]]

^<<v3-6-11,11>>^ Em seguida, removerá as roupas de linho, vestirá suas roupas habituais e levará as cinzas para fora do acampamento, até um lugar cerimonialmente puro.

[[v3-6-12]]

^<<v3-6-12,12>>^ Enquanto isso, o fogo do altar será mantido aceso; nunca deverá se apagar. A cada manhã, o sacerdote acrescentará mais lenha ao fogo, arrumará sobre ele o holocausto e queimará nele a gordura das ofertas de paz.

[[v3-6-13]]

^<<v3-6-13,13>>^ Lembrem-se de que o fogo deverá ser mantido aceso no altar o tempo todo; nunca deverá se apagar." Instruções adicionais para as ofertas de cereal

[[v3-6-14]]

^<<v3-6-14,14>>^ "Estas são as instruções para as ofertas de cereal. Os filhos de Arão apresentarão esta oferta ao SENHOR diante do altar.

[[v3-6-15]]

^<<v3-6-15,15>>^ O sacerdote de serviço pegará da oferta de cereal um punhado de farinha da melhor qualidade, umedecida com azeite, junto com todo o incenso, e queimará essa porção memorial no altar como aroma agradável ao SENHOR.

[[v3-6-16]]

^<<v3-6-16,16>>^ Arão e seus filhos poderão comer o restante da farinha, mas deverão assá-la sem fermento e comê-la num lugar sagrado dentro do pátio da tenda do encontro.

[[v3-6-17]]

^<<v3-6-17,17>>^ Lembrem-se de que essa oferta nunca deverá ser preparada com fermento. Eu a dei aos sacerdotes como porção das ofertas especiais apresentadas a mim. É santíssima, como a oferta pelo pecado e a oferta pela culpa.

[[v3-6-18]]

^<<v3-6-18,18>>^ Todos os homens descendentes de Arão poderão comer das ofertas especiais apresentadas ao SENHOR. É seu direito permanente, de geração em geração. Qualquer pessoa ou objeto que tocar nessas ofertas se tornará santo". Procedimentos para a oferta de consagração

[[v3-6-19]]

^<<v3-6-19,19>>^ Então o SENHOR disse a Moisés:

[[v3-6-20]]

^<<v3-6-20,20>>^ "No dia em que Arão e seus filhos forem ungidos, apresentarão ao SENHOR a oferta padrão de cereal de dois litros de farinha da melhor qualidade; metade pela manhã e metade à tarde.

[[v3-6-21]]

^<<v3-6-21,21>>^ Misture-a cuidadosamente com azeite e cozinhe-a numa assadeira. Corte em fatias a oferta de cereal e apresente-a como aroma agradável ao SENHOR.

[[v3-6-22]]

^<<v3-6-22,22>>^ A cada geração, o sacerdote ungido que suceder a Arão preparará essa mesma oferta. Ela pertence ao SENHOR e será totalmente queimada. Essa é uma lei permanente.

[[v3-6-23]]

^<<v3-6-23,23>>^ Todas as ofertas de cereal do sacerdote serão totalmente queimadas. Nenhuma parte poderá ser consumida como alimento". Instruções adicionais para a oferta pelo pecado

[[v3-6-24]]

^<<v3-6-24,24>>^ O SENHOR também disse a Moisés:

[[v3-6-25]]

^<<v3-6-25,25>>^ "Dê a Arão e a seus filhos as seguintes instruções para a oferta pelo pecado. O animal apresentado como oferta pelo pecado é oferta santíssima e será morto diante do SENHOR, onde são mortos os animais para os holocaustos.

[[v3-6-26]]

^<<v3-6-26,26>>^ O sacerdote que apresentar o sacrifício como oferta pelo pecado comerá sua porção num lugar sagrado dentro do pátio da tenda do encontro.

[[v3-6-27]]

^<<v3-6-27,27>>^ Qualquer pessoa ou objeto que tocar a carne do sacrifício se tornará santo. Se o sangue do sacrifício respingar na roupa de alguém, a peça manchada será lavada num lugar sagrado.

[[v3-6-28]]

^<<v3-6-28,28>>^ Se for usada uma panela de barro para cozinhar a carne do sacrifício, terá de ser quebrada em seguida. Se for usada uma panela de bronze, terá de ser esfregada e bem enxaguada com água.

[[v3-6-29]]

^<<v3-6-29,29>>^ Qualquer homem da família dos sacerdotes poderá comer dessa oferta. É oferta santíssima.

[[v3-6-30]]

^<<v3-6-30,30>>^ Mas a oferta pelo pecado não poderá ser comida se o sangue for levado à tenda do encontro como oferta para fazer expiação no lugar santo. Nesse caso, será totalmente queimada no fogo."

'''

xref:003-levitico/003-levitico-005.adoc#v3-5-0[&#60; Capítulo Anterior] | <<v3-6-0,Topo>> | xref:003-levitico/003-levitico-007.adoc#v3-7-0[Próximo Capítulo &#62;]