include::./index.adoc[]

[[v3-8-0]]
=== Levítico, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v3-8-1]]

^<<v3-8-1,1>>^ Então o SENHOR disse a Moisés:

[[v3-8-2]]

^<<v3-8-2,2>>^ "Traga Arão e seus filhos, as roupas sagradas, o óleo da unção, o novilho para a oferta pelo pecado, os dois carneiros e o cesto de pães sem fermento,

[[v3-8-3]]

^<<v3-8-3,3>>^ e reúna toda a comunidade à entrada da tenda do encontro".

[[v3-8-4]]

^<<v3-8-4,4>>^ Moisés seguiu as instruções do SENHOR, e toda a comunidade se reuniu à entrada da tenda do encontro.

[[v3-8-5]]

^<<v3-8-5,5>>^ "É isto que o SENHOR ordenou que façamos!", anunciou Moisés.

[[v3-8-6]]

^<<v3-8-6,6>>^ Em seguida, apresentou Arão e seus filhos e os lavou com água.

[[v3-8-7]]

^<<v3-8-7,7>>^ Colocou a túnica oficial em Arão e amarrou o cinturão ao redor de sua cintura. Vestiu-o com o manto, sobre o qual colocou o colete sacerdotal, que prendeu firmemente com o cinturão decorativo.

[[v3-8-8]]

^<<v3-8-8,8>>^ Colocou em Arão o peitoral e, dentro dele, o Urim e o Tumim.

[[v3-8-9]]

^<<v3-8-9,9>>^ Pôs na cabeça de Arão o turbante e, na parte da frente do turbante, prendeu a tiara sagrada, o emblema de santidade, conforme o SENHOR havia ordenado.

[[v3-8-10]]

^<<v3-8-10,10>>^ Depois, Moisés pegou o óleo da unção e ungiu o tabernáculo e tudo que nele havia, a fim de consagrá-los.

[[v3-8-11]]

^<<v3-8-11,11>>^ Aspergiu o altar com óleo sete vezes para ungi-lo, bem como todos os seus utensílios, a bacia e seu suporte, para também consagrá-los.

[[v3-8-12]]

^<<v3-8-12,12>>^ Derramou um pouco do óleo sobre a cabeça de Arão, para ungi-lo e consagrá-lo.

[[v3-8-13]]

^<<v3-8-13,13>>^ Em seguida, Moisés apresentou os filhos de Arão. Vestiu-os com as túnicas, amarrou neles o cinturão e pôs-lhes na cabeça o turbante especial, conforme o SENHOR tinha ordenado.

[[v3-8-14]]

^<<v3-8-14,14>>^ Então Moisés apresentou o novilho para a oferta pelo pecado. Arão e seus filhos colocaram as mãos sobre a cabeça do novilho,

[[v3-8-15]]

^<<v3-8-15,15>>^ e Moisés o matou. Pegou um pouco do sangue e, com o dedo, colocou-o nas quatro pontas do altar, a fim de purificá-lo. O restante do sangue ele derramou na base do altar. Desse modo, consagrou o altar e fez expiação por ele.

[[v3-8-16]]

^<<v3-8-16,16>>^ Depois, pegou toda a gordura que envolvia os órgãos internos, o lóbulo do fígado, os dois rins e a gordura ao redor deles e os queimou no altar.

[[v3-8-17]]

^<<v3-8-17,17>>^ Pegou o restante do novilho, incluindo o couro, a carne e os excrementos, e o queimou num fogo fora do acampamento, conforme o SENHOR tinha ordenado.

[[v3-8-18]]

^<<v3-8-18,18>>^ Então Moisés apresentou o carneiro para o holocausto. Arão e seus filhos colocaram as mãos sobre a cabeça do animal,

[[v3-8-19]]

^<<v3-8-19,19>>^ e Moisés o matou. Pegou o sangue do carneiro e o derramou em todos os lados do altar.

[[v3-8-20]]

^<<v3-8-20,20>>^ Cortou o carneiro em pedaços e o queimou no altar, junto com a cabeça e a gordura.

[[v3-8-21]]

^<<v3-8-21,21>>^ Depois de lavar os órgãos internos e as pernas com água, queimou todo o carneiro sobre o altar como holocausto. Foi um aroma agradável, uma oferta especial apresentada ao SENHOR, conforme o SENHOR tinha ordenado.

[[v3-8-22]]

^<<v3-8-22,22>>^ Então Moisés apresentou o outro carneiro, o carneiro da consagração. Arão e seus filhos colocaram as mãos sobre a cabeça do animal,

[[v3-8-23]]

^<<v3-8-23,23>>^ e Moisés o matou. Pegou um pouco do sangue e o colocou na ponta da orelha direita, no polegar da mão direita e no polegar do pé direito de Arão.

[[v3-8-24]]

^<<v3-8-24,24>>^ Depois, apresentou os filhos de Arão e colocou um pouco do sangue na ponta da orelha direita, no polegar da mão direita e no polegar do pé direito deles. O restante do sangue ele derramou em todos os lados do altar.

[[v3-8-25]]

^<<v3-8-25,25>>^ Em seguida, pegou a gordura, incluindo a gordura da parte gorda da cauda, a gordura que envolve os órgãos internos, o lóbulo do fígado, os dois rins e a gordura ao redor deles, bem como a coxa direita.

[[v3-8-26]]

^<<v3-8-26,26>>^ Sobre essas partes colocou um pão sem fermento, um pão de massa misturada com azeite e um pão fino untado com azeite, que tirou do cesto de pães sem fermento que estava na presença do SENHOR.

[[v3-8-27]]

^<<v3-8-27,27>>^ Colocou tudo nas mãos de Arão e seus filhos e moveu os alimentos para o alto como oferta especial para o SENHOR.

[[v3-8-28]]

^<<v3-8-28,28>>^ Pegou as ofertas de volta das mãos deles e as queimou no altar, sobre o holocausto. Essa foi a oferta de consagração. Foi um aroma agradável, uma oferta especial apresentada ao SENHOR.

[[v3-8-29]]

^<<v3-8-29,29>>^ Moisés pegou o peito e o moveu para o alto como oferta especial para o SENHOR. Era a porção de Moisés do carneiro da consagração, conforme o SENHOR tinha ordenado.

[[v3-8-30]]

^<<v3-8-30,30>>^ Então Moisés pegou um pouco do óleo da unção e um pouco do sangue que estava sobre o altar e aspergiu sobre Arão e suas roupas e sobre seus filhos e suas roupas. Desse modo, consagrou Arão, seus filhos e suas roupas.

[[v3-8-31]]

^<<v3-8-31,31>>^ Por fim, Moisés disse a Arão e a seus filhos: "Cozinhem o restante da carne das ofertas à entrada da tenda do encontro e comam-na ali, junto com os pães que estão no cesto de ofertas para a consagração, conforme ordenei quando disse: ‘Arão e seus filhos os comerão’.

[[v3-8-32]]

^<<v3-8-32,32>>^ Queimem qualquer carne ou pão que sobrar.

[[v3-8-33]]

^<<v3-8-33,33>>^ Não saiam da entrada da tenda do encontro por sete dias, pois só então estará concluída a cerimônia de consagração.

[[v3-8-34]]

^<<v3-8-34,34>>^ Tudo que fizemos hoje foi ordenado pelo SENHOR a fim de fazer expiação por vocês.

[[v3-8-35]]

^<<v3-8-35,35>>^ Agora, permaneçam à entrada da tenda do encontro dia e noite por sete dias e cumpram todas as exigências do SENHOR. Se não o fizerem, morrerão, pois foi isso que o SENHOR me ordenou".

[[v3-8-36]]

^<<v3-8-36,36>>^ Arão e seus filhos fizeram tudo que o SENHOR tinha ordenado por meio de Moisés.

'''

xref:003-levitico/003-levitico-007.adoc#v3-7-0[&#60; Capítulo Anterior] | <<v3-8-0,Topo>> | xref:003-levitico/003-levitico-009.adoc#v3-9-0[Próximo Capítulo &#62;]