include::./index.adoc[]

[[v3-2-0]]
=== Levítico, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v3-2-1]]

^<<v3-2-1,1>>^ "Quando apresentar ao SENHOR uma oferta de cereal, deverá ser de farinha da melhor qualidade. Derrame azeite sobre a farinha, acrescente um pouco de incenso

[[v3-2-2]]

^<<v3-2-2,2>>^ e leve-a aos filhos de Arão, os sacerdotes. O sacerdote pegará um punhado da farinha umedecida com azeite, junto com todo o incenso, e queimará essa porção memorial no altar. É uma oferta especial, um aroma agradável ao SENHOR.

[[v3-2-3]]

^<<v3-2-3,3>>^ O restante da oferta de cereal será entregue a Arão e a seus filhos. Essa oferta será considerada parte santíssima das ofertas especiais apresentadas ao SENHOR.

[[v3-2-4]]

^<<v3-2-4,4>>^ "Se a oferta for de cereal assado no forno, deverá ser de farinha da melhor qualidade, mas sem fermento: bolos misturados com azeite ou pães finos untados com azeite.

[[v3-2-5]]

^<<v3-2-5,5>>^ Se a oferta de cereal for preparada numa assadeira, deverá ser de farinha da melhor qualidade misturada com azeite, mas sem fermento.

[[v3-2-6]]

^<<v3-2-6,6>>^ Divida-a em pedaços e derrame azeite sobre ela. É oferta de cereal.

[[v3-2-7]]

^<<v3-2-7,7>>^ Se a oferta de cereal for preparada numa panela, deverá ser de farinha da melhor qualidade misturada com azeite.

[[v3-2-8]]

^<<v3-2-8,8>>^ "Quando trouxer a oferta de cereal que foi preparada para o SENHOR, entregue-a ao sacerdote, que a apresentará no altar.

[[v3-2-9]]

^<<v3-2-9,9>>^ O sacerdote tomará uma porção memorial da oferta de cereal e a queimará no altar. É uma oferta especial, um aroma agradável ao SENHOR.

[[v3-2-10]]

^<<v3-2-10,10>>^ O restante da oferta de cereal será entregue a Arão e a seus filhos como alimento. Essa oferta será considerada parte santíssima das ofertas especiais apresentadas ao SENHOR.

[[v3-2-11]]

^<<v3-2-11,11>>^ "Não use fermento ao preparar qualquer das ofertas de cereal a ser apresentada ao SENHOR, pois nem fermento nem mel devem ser queimados como oferta especial apresentada ao SENHOR.

[[v3-2-12]]

^<<v3-2-12,12>>^ É permitido acrescentar fermento e mel às ofertas dos primeiros frutos da colheita, mas nunca devem ser oferecidos no altar como aroma agradável ao SENHOR.

[[v3-2-13]]

^<<v3-2-13,13>>^ Tempere com sal todas as suas ofertas de cereal. Não deixe de usar o sal da aliança do seu Deus em todas as suas ofertas de cereal. Todas as ofertas que trouxerem deverão ter sal.

[[v3-2-14]]

^<<v3-2-14,14>>^ "Se apresentar ao SENHOR uma oferta de cereal dos primeiros frutos de sua colheita, apresente grãos frescos moídos grosseiramente e tostados no fogo.

[[v3-2-15]]

^<<v3-2-15,15>>^ Derrame azeite sobre essa oferta de cereal e acrescente um pouco de incenso.

[[v3-2-16]]

^<<v3-2-16,16>>^ O sacerdote tomará uma porção memorial dos grãos umedecidos com azeite, junto com todo o incenso, e queimará como oferta especial apresentada ao SENHOR."

'''

xref:003-levitico/003-levitico-001.adoc#v3-1-0[&#60; Capítulo Anterior] | <<v3-2-0,Topo>> | xref:003-levitico/003-levitico-003.adoc#v3-3-0[Próximo Capítulo &#62;]