include::./index.adoc[]

[[v3-16-0]]
=== Levítico, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v3-16-1]]

^<<v3-16-1,1>>^ O SENHOR falou com Moisés depois que os dois filhos de Arão morreram ao entrar na presença do SENHOR.

[[v3-16-2]]

^<<v3-16-2,2>>^ Disse o SENHOR a Moisés: "Avise seu irmão Arão que não entre quando bem entender no lugar santíssimo, atrás da cortina interna; se o fizer, morrerá. Ali fica a tampa da arca, o lugar de expiação, e eu mesmo estou presente na nuvem sobre a tampa da arca.

[[v3-16-3]]

^<<v3-16-3,3>>^ "Quando Arão entrar no santuário, seguirá todas estas instruções. Levará um novilho para oferta pelo pecado e um carneiro para holocausto.

[[v3-16-4]]

^<<v3-16-4,4>>^ Vestirá a túnica sagrada de linho e a roupa de baixo de linho, diretamente sobre a pele. Amarrará na cintura o cinturão de linho e colocará na cabeça o turbante de linho. As roupas são sagradas, de modo que ele deverá se banhar com água antes de vesti-las.

[[v3-16-5]]

^<<v3-16-5,5>>^ Arão receberá da comunidade de Israel dois bodes para uma oferta pelo pecado e um carneiro para um holocausto.

[[v3-16-6]]

^<<v3-16-6,6>>^ "Arão apresentará seu próprio novilho como oferta pelo pecado para fazer expiação por si mesmo e por sua família.

[[v3-16-7]]

^<<v3-16-7,7>>^ Em seguida, pegará os dois bodes e os apresentará ao SENHOR à entrada da tenda do encontro.

[[v3-16-8]]

^<<v3-16-8,8>>^ Depois, fará um sorteio para determinar qual bode será separado como oferta para o SENHOR e qual levará os pecados do povo para o deserto de Azazel.

[[v3-16-9]]

^<<v3-16-9,9>>^ Então Arão apresentará ao SENHOR o bode escolhido por sorteio e o sacrificará como oferta pelo pecado.

[[v3-16-10]]

^<<v3-16-10,10>>^ O outro animal, o bode escolhido por sorteio para ser enviado para o deserto, será apresentado vivo diante do SENHOR. Ao ser enviado para Azazel no deserto, servirá para fazer expiação pelo povo.

[[v3-16-11]]

^<<v3-16-11,11>>^ "Arão apresentará seu próprio novilho como oferta pelo pecado para fazer expiação por si mesmo e por sua família. Depois de matar o novilho como oferta pelo pecado,

[[v3-16-12]]

^<<v3-16-12,12>>^ pegará um incensário e o encherá com brasas ardentes do altar que está diante do SENHOR. Pegará também dois punhados do incenso perfumado em pó e levará o incensário e o incenso para trás da cortina interna.

[[v3-16-13]]

^<<v3-16-13,13>>^ Ali, na presença do SENHOR, colocará o incenso sobre as brasas ardentes, para que uma nuvem de incenso se eleve sobre a tampa da arca, o lugar de expiação, que está sobre a arca da aliança. Se seguir essas instruções, não morrerá.

[[v3-16-14]]

^<<v3-16-14,14>>^ Depois, pegará um pouco do sangue do novilho, molhará nele o dedo e aspergirá o lado leste da tampa. Então, com o dedo, aspergirá com o sangue sete vezes diante da tampa.

[[v3-16-15]]

^<<v3-16-15,15>>^ "Arão matará o primeiro bode como oferta pelo pecado em favor do povo e levará o sangue para trás da cortina interna. Ali, aspergirá o sangue do bode sobre a tampa e diante dela, como fez com o sangue do novilho.

[[v3-16-16]]

^<<v3-16-16,16>>^ Desse modo, fará expiação pelo lugar santíssimo e fará o mesmo com toda a tenda do encontro por causa da contaminação pelo pecado e da rebeldia do povo.

[[v3-16-17]]

^<<v3-16-17,17>>^ Ninguém mais poderá ficar na tenda do encontro quando Arão entrar para realizar a cerimônia de expiação no lugar santíssimo. Ninguém entrará até que ele saia depois de fazer expiação por si mesmo, por sua família e por toda a comunidade de Israel.

[[v3-16-18]]

^<<v3-16-18,18>>^ "Em seguida, Arão sairá para fazer expiação pelo altar que está diante do SENHOR. Para isso, pegará um pouco do sangue do novilho e do bode e o colocará em cada ponta do altar.

[[v3-16-19]]

^<<v3-16-19,19>>^ Então, com o dedo, aspergirá o sangue sete vezes sobre o altar. Desse modo, ele o purificará da contaminação dos israelitas e o tornará santo.

[[v3-16-20]]

^<<v3-16-20,20>>^ "Quando Arão terminar de fazer expiação pelo lugar santíssimo, pela tenda do encontro e pelo altar, apresentará o bode vivo.

[[v3-16-21]]

^<<v3-16-21,21>>^ Colocará as duas mãos sobre a cabeça do bode e confessará sobre ele toda a maldade, a rebeldia e os pecados dos israelitas. Assim, transferirá os pecados do povo para a cabeça do bode. Depois, um homem escolhido especialmente para essa tarefa levará o bode para o deserto.

[[v3-16-22]]

^<<v3-16-22,22>>^ Ao sair para o deserto, o bode levará sobre si todos os pecados do povo para um lugar distante.

[[v3-16-23]]

^<<v3-16-23,23>>^ "Quando Arão voltar para dentro da tenda do encontro, tirará as roupas de linho que vestia ao entrar no lugar santíssimo e as deixará ali.

[[v3-16-24]]

^<<v3-16-24,24>>^ Ele se banhará com água num lugar sagrado, vestirá suas roupas habituais e sairá para apresentar um holocausto para si mesmo e um holocausto para o povo. Desse modo, fará expiação por si mesmo e pelo povo.

[[v3-16-25]]

^<<v3-16-25,25>>^ Por fim, queimará no altar toda a gordura da oferta pelo pecado.

[[v3-16-26]]

^<<v3-16-26,26>>^ "O homem escolhido para levar o bode expiatório para o deserto de Azazel lavará suas roupas e se banhará com água antes de voltar ao acampamento.

[[v3-16-27]]

^<<v3-16-27,27>>^ "O novilho e o bode apresentados como ofertas pelo pecado, cujo sangue Arão trouxer ao lugar santíssimo para a cerimônia de expiação, serão levados para fora do acampamento. O couro, a carne e os excrementos dos animais serão queimados.

[[v3-16-28]]

^<<v3-16-28,28>>^ O homem que os queimar lavará suas roupas e se banhará com água antes de voltar ao acampamento.

[[v3-16-29]]

^<<v3-16-29,29>>^ "No décimo dia do sétimo mês, vocês se humilharão. Nem os israelitas de nascimento nem os estrangeiros que vivem entre vocês farão qualquer tipo de trabalho. Essa é uma lei permanente para vocês.

[[v3-16-30]]

^<<v3-16-30,30>>^ Nesse dia, serão apresentadas ofertas de expiação por vocês, a fim de purificá-los, e vocês serão purificados de todos os seus pecados na presença do SENHOR.

[[v3-16-31]]

^<<v3-16-31,31>>^ Será um sábado de descanso absoluto, no qual se humilharão. Essa é uma lei permanente para vocês.

[[v3-16-32]]

^<<v3-16-32,32>>^ Nas gerações futuras, a cerimônia de expiação será realizada pelo sacerdote ungido e consagrado para servir como sacerdote no lugar de seu antepassado Arão. Ele vestirá as roupas sagradas de linho

[[v3-16-33]]

^<<v3-16-33,33>>^ e fará expiação pelo lugar santíssimo, pela tenda do encontro, pelo altar, pelos sacerdotes e por toda a comunidade.

[[v3-16-34]]

^<<v3-16-34,34>>^ Essa é uma lei permanente para vocês, para que se faça expiação pelos pecados dos israelitas uma vez por ano". Moisés seguiu todas essas instruções exatamente conforme o SENHOR havia ordenado.

'''

xref:003-levitico/003-levitico-015.adoc#v3-15-0[&#60; Capítulo Anterior] | <<v3-16-0,Topo>> | xref:003-levitico/003-levitico-017.adoc#v3-17-0[Próximo Capítulo &#62;]