include::./index.adoc[]

[[v3-11-0]]
=== Levítico, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v3-11-1]]

^<<v3-11-1,1>>^ O SENHOR disse a Moisés e a Arão:

[[v3-11-2]]

^<<v3-11-2,2>>^ "Deem as seguintes instruções ao povo de Israel. "De todos os animais que vivem em terra, estes são os que vocês poderão consumir como alimento:

[[v3-11-3]]

^<<v3-11-3,3>>^ qualquer animal que tenha os cascos divididos em duas partes e que rumine.

[[v3-11-4]]

^<<v3-11-4,4>>^ Mas, se o animal não apresentar essas duas características, não pode ser consumido. O camelo rumina, mas não tem os cascos divididos, de modo que é impuro para vocês.

[[v3-11-5]]

^<<v3-11-5,5>>^ O coelho silvestre rumina, mas não tem cascos divididos, por isso é impuro.

[[v3-11-6]]

^<<v3-11-6,6>>^ A lebre rumina, mas não tem cascos divididos, de modo que é impura.

[[v3-11-7]]

^<<v3-11-7,7>>^ O porco, embora tenha os cascos divididos, não rumina e, portanto, também é impuro.

[[v3-11-8]]

^<<v3-11-8,8>>^ Não comerão a carne desses animais nem tocarão em seu cadáver. São cerimonialmente impuros para vocês.

[[v3-11-9]]

^<<v3-11-9,9>>^ "De todos os animais que vivem nas águas, estes são os que vocês poderão consumir como alimento: qualquer animal aquático que tenha barbatanas e escamas, seja de água salgada ou de rios.

[[v3-11-10]]

^<<v3-11-10,10>>^ Contudo, jamais comerão animais de mar ou de rio que não tenham barbatanas e escamas. São detestáveis para vocês. Isso se aplica tanto às criaturas pequenas que vivem em águas rasas como a todas as criaturas que vivem em águas profundas.

[[v3-11-11]]

^<<v3-11-11,11>>^ Serão sempre detestáveis para vocês. Não comerão a carne delas nem tocarão em seu cadáver.

[[v3-11-12]]

^<<v3-11-12,12>>^ Qualquer animal aquático que não tem barbatanas e escamas é detestável para vocês.

[[v3-11-13]]

^<<v3-11-13,13>>^ "Estes são os animais voadores que vocês considerarão detestáveis e não comerão: o abutre-fouveiro, o abutre-barbudo, o abutre-fusco,

[[v3-11-14]]

^<<v3-11-14,14>>^ o milhafre e todas as espécies de falcão,

[[v3-11-15]]

^<<v3-11-15,15>>^ todas as espécies de corvos,

[[v3-11-16]]

^<<v3-11-16,16>>^ a coruja-de-chifres, a coruja-do-campo, a gaivota, todas as espécies de gaviões,

[[v3-11-17]]

^<<v3-11-17,17>>^ o mocho-galego, o cormorão, o corujão,

[[v3-11-18]]

^<<v3-11-18,18>>^ a coruja-das-torres, a coruja-do-deserto, o abutre-do-egito,

[[v3-11-19]]

^<<v3-11-19,19>>^ a cegonha, todas as espécies de garças, a poupa e o morcego.

[[v3-11-20]]

^<<v3-11-20,20>>^ "Não comerão insetos alados que rastejam pelo chão, pois são detestáveis para vocês.

[[v3-11-21]]

^<<v3-11-21,21>>^ Contudo, poderão comer insetos alados que andam pelo chão e têm pernas articuladas para saltar.

[[v3-11-22]]

^<<v3-11-22,22>>^ Os insetos que vocês poderão comer incluem todas as espécies de gafanhotos, gafanhotos migradores, grilos e gafanhotos devoradores.

[[v3-11-23]]

^<<v3-11-23,23>>^ Todos os outros insetos alados que andam pelo chão são detestáveis para vocês.

[[v3-11-24]]

^<<v3-11-24,24>>^ "Por causa dessas criaturas vocês se tornarão cerimonialmente impuros. Quem tocar em seus cadáveres ficará contaminado até o entardecer.

[[v3-11-25]]

^<<v3-11-25,25>>^ Quem carregar o cadáver delas deverá lavar as roupas e ficará contaminado até o entardecer.

[[v3-11-26]]

^<<v3-11-26,26>>^ "Todo animal com cascos divididos de forma desigual ou que não rumina é impuro para vocês. Quem tocar em algum desses animais ficará contaminado.

[[v3-11-27]]

^<<v3-11-27,27>>^ Dentre os quadrúpedes, aqueles que andam sobre a planta dos pés são impuros. Se alguém tocar no cadáver de algum desses animais, ficará impuro até o entardecer.

[[v3-11-28]]

^<<v3-11-28,28>>^ Se carregar o cadáver deles, deverá lavar as roupas e ficará contaminado até o entardecer. Esses animais são impuros para vocês.

[[v3-11-29]]

^<<v3-11-29,29>>^ "Dos animais pequenos que rastejam pelo chão, estes são impuros para vocês: a doninha, o rato, todas as espécies de lagartos grandes,

[[v3-11-30]]

^<<v3-11-30,30>>^ a lagartixa, o lagarto pintado, o lagarto comum, o lagarto da areia e o camaleão.

[[v3-11-31]]

^<<v3-11-31,31>>^ Todos esses animais pequenos são impuros para vocês. Se alguém tocar no cadáver de um deles, ficará contaminado até o entardecer.

[[v3-11-32]]

^<<v3-11-32,32>>^ Se um deles morrer e cair sobre algo, tornará impuro esse objeto, seja de madeira, tecido, couro ou pano de saco. Qualquer que seja seu uso, deverá ser colocado de molho em água e ficará impuro até o entardecer. Depois disso, estará cerimonialmente puro e poderá ser usado novamente.

[[v3-11-33]]

^<<v3-11-33,33>>^ "Se um desses animais cair numa vasilha de barro, tudo que estiver dentro da vasilha ficará contaminado, e a vasilha deverá ser despedaçada.

[[v3-11-34]]

^<<v3-11-34,34>>^ Se a água dessa vasilha cair sobre algum alimento, ele ficará contaminado. Qualquer bebida que estiver dentro da vasilha ficará contaminada.

[[v3-11-35]]

^<<v3-11-35,35>>^ Qualquer objeto no qual o cadáver de um desses animais cair ficará contaminado. Se o objeto for um fogão ou um forno de barro, deverá ser destruído, pois está contaminado e deverá ser tratado como tal.

[[v3-11-36]]

^<<v3-11-36,36>>^ "Se o cadáver de um desses animais cair numa fonte ou cisterna, a água continuará pura. Quem tocar no cadáver, porém, ficará cerimonialmente impuro.

[[v3-11-37]]

^<<v3-11-37,37>>^ Se o cadáver cair sobre sementes a serem plantadas no campo, ainda assim as sementes serão consideradas puras.

[[v3-11-38]]

^<<v3-11-38,38>>^ Mas, se já tiverem sido regadas quando o cadáver cair sobre elas, as sementes serão impuras.

[[v3-11-39]]

^<<v3-11-39,39>>^ "Se morrer um animal que vocês têm permissão de comer e alguém tocar no cadáver, ficará impuro até o entardecer.

[[v3-11-40]]

^<<v3-11-40,40>>^ Se alguém comer da carne do animal ou carregar o cadáver, deverá lavar as roupas e ficará impuro até o entardecer.

[[v3-11-41]]

^<<v3-11-41,41>>^ "Todos os animais pequenos que rastejam pelo chão são detestáveis, e vocês jamais devem comê-los.

[[v3-11-42]]

^<<v3-11-42,42>>^ Isso inclui todos os animais que se arrastam sobre o ventre, bem como os que têm quatro pernas e os que têm muitas patas. Todos esses animais que rastejam pelo chão são detestáveis, e vocês jamais devem comê-los.

[[v3-11-43]]

^<<v3-11-43,43>>^ Não se contaminem com eles. Não se tornem cerimonialmente impuros por causa deles,

[[v3-11-44]]

^<<v3-11-44,44>>^ pois eu sou o SENHOR, seu Deus. Consagrem-se e sejam santos, pois eu sou santo. Não se contaminem com nenhum desses animais pequenos que rastejam pelo chão.

[[v3-11-45]]

^<<v3-11-45,45>>^ Eu, o SENHOR, sou aquele que os tirou da terra do Egito para ser o seu Deus. Por isso, sejam santos, pois eu sou santo.

[[v3-11-46]]

^<<v3-11-46,46>>^ "Essas são as instruções acerca dos animais que vivem em terra, dos animais voadores, das criaturas aquáticas e dos animais que rastejam pelo chão.

[[v3-11-47]]

^<<v3-11-47,47>>^ Com essas instruções, vocês saberão o que é impuro e o que é puro, os animais que vocês podem comer e os que não podem".

'''

xref:003-levitico/003-levitico-010.adoc#v3-10-0[&#60; Capítulo Anterior] | <<v3-11-0,Topo>> | xref:003-levitico/003-levitico-012.adoc#v3-12-0[Próximo Capítulo &#62;]