include::./index.adoc[]

[[v3-18-0]]
=== Levítico, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v3-18-1]]

^<<v3-18-1,1>>^ Então o SENHOR disse a Moisés:

[[v3-18-2]]

^<<v3-18-2,2>>^ "Dê as seguintes instruções ao povo de Israel. Eu sou o SENHOR, seu Deus.

[[v3-18-3]]

^<<v3-18-3,3>>^ Portanto, não se comportem como o povo do Egito, onde vocês viviam, nem como o povo de Canaã, para onde os estou levando. Não imitem o estilo de vida deles.

[[v3-18-4]]

^<<v3-18-4,4>>^ Obedeçam aos meus estatutos e cumpram os meus decretos, pois eu sou o SENHOR, seu Deus.

[[v3-18-5]]

^<<v3-18-5,5>>^ Sim, obedeçam aos meus decretos e aos meus estatutos; quem os praticar viverá por eles. Eu sou o SENHOR.

[[v3-18-6]]

^<<v3-18-6,6>>^ "Jamais tenha relações sexuais com uma parenta próxima, pois eu sou o SENHOR.

[[v3-18-7]]

^<<v3-18-7,7>>^ "Não desonre seu pai, tendo relações sexuais com sua mãe. Ela é sua mãe; não tenha relações sexuais com ela.

[[v3-18-8]]

^<<v3-18-8,8>>^ "Não tenha relações sexuais com nenhuma das esposas de seu pai, pois isso desonraria seu pai.

[[v3-18-9]]

^<<v3-18-9,9>>^ "Não tenha relações sexuais com sua irmã ou meia-irmã, filha de seu pai ou de sua mãe, nascida em sua casa ou em outra casa.

[[v3-18-10]]

^<<v3-18-10,10>>^ "Não tenha relações sexuais com sua neta, filha de seu filho ou de sua filha, pois com isso você desonraria a si mesmo.

[[v3-18-11]]

^<<v3-18-11,11>>^ "Não tenha relações sexuais com a filha de nenhuma das esposas de seu pai, pois ela é sua irmã.

[[v3-18-12]]

^<<v3-18-12,12>>^ "Não tenha relações sexuais com sua tia, irmã de seu pai, pois ela é parenta próxima de seu pai.

[[v3-18-13]]

^<<v3-18-13,13>>^ "Não tenha relações sexuais com sua tia, irmã de sua mãe, pois ela é parenta próxima de sua mãe.

[[v3-18-14]]

^<<v3-18-14,14>>^ "Não desonre seu tio, irmão de seu pai, tendo relações sexuais com a mulher dele, pois ela é sua tia.

[[v3-18-15]]

^<<v3-18-15,15>>^ "Não tenha relações sexuais com sua nora; ela é mulher de seu filho, de modo que você não deve ter relações sexuais com ela.

[[v3-18-16]]

^<<v3-18-16,16>>^ "Não tenha relações sexuais com a mulher de seu irmão, pois desonraria seu irmão.

[[v3-18-17]]

^<<v3-18-17,17>>^ "Não tenha relações sexuais com uma mulher e a filha dela. E não tome a neta dela, filha do filho ou da filha dela, e tenha relações sexuais com ela, pois são parentas próximas. Isso é perversão.

[[v3-18-18]]

^<<v3-18-18,18>>^ "Enquanto sua esposa estiver viva, não se case nem tenha relações sexuais com a irmã dela, pois elas se tornariam rivais.

[[v3-18-19]]

^<<v3-18-19,19>>^ "Não tenha relações sexuais com uma mulher durante o período de impureza menstrual dela.

[[v3-18-20]]

^<<v3-18-20,20>>^ "Não tenha relações sexuais com a mulher do seu próximo, contaminando-se com ela.

[[v3-18-21]]

^<<v3-18-21,21>>^ "Não permita que nenhum de seus filhos seja oferecido como sacrifício a Moloque. Não desonre o nome do seu Deus. Eu sou o SENHOR.

[[v3-18-22]]

^<<v3-18-22,22>>^ "Não pratique a homossexualidade, tendo relações sexuais com outro homem como se fosse com uma mulher. Isso é detestável.

[[v3-18-23]]

^<<v3-18-23,23>>^ "Homem nenhum deve se contaminar tendo relações sexuais com um animal. E mulher nenhuma deve se oferecer para um animal macho para ter relações com ele. Isso é depravação.

[[v3-18-24]]

^<<v3-18-24,24>>^ "Não se contaminem de nenhuma dessas formas, pois os povos que expulsarei da presença de vocês se contaminaram com todas essas práticas.

[[v3-18-25]]

^<<v3-18-25,25>>^ Uma vez que a terra toda foi contaminada, castigarei seus habitantes. Farei a terra vomitá-los.

[[v3-18-26]]

^<<v3-18-26,26>>^ Obedeçam aos meus decretos e aos meus estatutos. Não cometam nenhum desses atos detestáveis. Isso se aplica tanto aos israelitas de nascimento como aos estrangeiros que vivem entre vocês.

[[v3-18-27]]

^<<v3-18-27,27>>^ "Todos esses atos detestáveis são praticados pelos povos da terra para onde eu os estou levando, e foi assim que a terra ficou contaminada.

[[v3-18-28]]

^<<v3-18-28,28>>^ Por isso, não contaminem a terra e não lhe deem motivo para vomitá-los, como fará com os povos que agora vivem ali.

[[v3-18-29]]

^<<v3-18-29,29>>^ Quem cometer algum desses pecados detestáveis será eliminado do meio do povo.

[[v3-18-30]]

^<<v3-18-30,30>>^ Portanto, obedeçam às minhas instruções e não se contaminem por adotar alguma dessas práticas detestáveis dos povos que viveram na terra antes de vocês. Eu sou o SENHOR, seu Deus".

'''

xref:003-levitico/003-levitico-017.adoc#v3-17-0[&#60; Capítulo Anterior] | <<v3-18-0,Topo>> | xref:003-levitico/003-levitico-019.adoc#v3-19-0[Próximo Capítulo &#62;]