include::./index.adoc[]

[[v3-12-0]]
=== Levítico, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v3-12-1]]

^<<v3-12-1,1>>^ O SENHOR disse a Moisés:

[[v3-12-2]]

^<<v3-12-2,2>>^ "Dê as seguintes instruções ao povo de Israel. Se uma mulher engravidar e der à luz um filho, ficará cerimonialmente impura por sete dias, como acontece durante a menstruação.

[[v3-12-3]]

^<<v3-12-3,3>>^ No oitavo dia, circuncidem o menino.

[[v3-12-4]]

^<<v3-12-4,4>>^ Depois de esperar 33 dias, a mulher estará purificada do sangramento do parto. Durante o período de purificação, não deverá tocar em coisa alguma que seja consagrada. Também não poderá entrar no santuário enquanto não terminar o período de purificação.

[[v3-12-5]]

^<<v3-12-5,5>>^ Se a mulher der à luz uma filha, ficará cerimonialmente impura por duas semanas, como acontece durante a menstruação. Depois de esperar 66 dias, estará purificada do sangramento do parto.

[[v3-12-6]]

^<<v3-12-6,6>>^ "Quando se completar o tempo de purificação pelo nascimento de um filho ou de uma filha, a mulher levará um cordeiro de um ano como holocausto e um pombinho ou rolinha para a oferta pelo pecado. Levará as ofertas ao sacerdote à entrada da tenda do encontro.

[[v3-12-7]]

^<<v3-12-7,7>>^ O sacerdote as apresentará ao SENHOR para fazer expiação pela mulher. Ela voltará a ficar cerimonialmente pura depois do sangramento do parto. Essas são as instruções para a mulher depois do nascimento de um filho ou de uma filha.

[[v3-12-8]]

^<<v3-12-8,8>>^ "Se a mulher não tiver condições de levar um cordeiro, levará duas rolinhas ou dois pombinhos. Um será para o holocausto, e o outro, para a oferta pelo pecado. O sacerdote os sacrificará para fazer expiação pela mulher, e ela ficará cerimonialmente pura".

'''

xref:003-levitico/003-levitico-011.adoc#v3-11-0[&#60; Capítulo Anterior] | <<v3-12-0,Topo>> | xref:003-levitico/003-levitico-013.adoc#v3-13-0[Próximo Capítulo &#62;]