include::./index.adoc[]

[[v3-23-0]]
=== Levítico, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v3-23-1]]

^<<v3-23-1,1>>^ O SENHOR disse a Moisés:

[[v3-23-2]]

^<<v3-23-2,2>>^ "Dê as seguintes instruções ao povo de Israel. Estas são as festas que o SENHOR estabeleceu e que vocês proclamarão como reuniões sagradas.

[[v3-23-3]]

^<<v3-23-3,3>>^ "Vocês têm seis dias na semana para fazer os trabalhos habituais, mas o sétimo dia é o sábado, o dia de descanso absoluto e de reunião sagrada. Não façam trabalho algum, pois é o sábado do SENHOR e deve ser guardado onde quer que morarem.

[[v3-23-4]]

^<<v3-23-4,4>>^ "Além do sábado, estas são as festas que o SENHOR estabeleceu, as reuniões sagradas que serão celebradas anualmente no devido tempo." A Páscoa e a Festa dos Pães sem Fermento

[[v3-23-5]]

^<<v3-23-5,5>>^ "A Páscoa do SENHOR começa ao entardecer do décimo quarto dia do primeiro mês.

[[v3-23-6]]

^<<v3-23-6,6>>^ No dia seguinte, o décimo quinto dia, comecem a celebrar a Festa dos Pães sem Fermento. Essa celebração em homenagem ao SENHOR continuará por sete dias e, durante esse tempo, o pão que comerem será preparado sem fermento.

[[v3-23-7]]

^<<v3-23-7,7>>^ No primeiro dia da festa, todos suspenderão seus trabalhos habituais e realizarão uma reunião sagrada.

[[v3-23-8]]

^<<v3-23-8,8>>^ Durante sete dias, apresentarão ofertas especiais para o SENHOR. No sétimo dia, suspenderão novamente seus trabalhos habituais para realizar uma reunião sagrada".

[[v3-23-9]]

^<<v3-23-9,9>>^ O SENHOR disse a Moisés:

[[v3-23-10]]

^<<v3-23-10,10>>^ "Dê as seguintes instruções ao povo de Israel. Quando entrarem na terra que eu lhes dou e começarem a primeira colheita, levem ao sacerdote um feixe dos primeiros cereais que colherem.

[[v3-23-11]]

^<<v3-23-11,11>>^ No dia depois do sábado, o sacerdote moverá o feixe para o alto diante do SENHOR, para que seja aceito em favor de vocês.

[[v3-23-12]]

^<<v3-23-12,12>>^ Nesse mesmo dia, ofereçam um cordeiro de um ano, sem defeito, como holocausto para o SENHOR.

[[v3-23-13]]

^<<v3-23-13,13>>^ Junto com o sacrifício, apresentem uma oferta de cereal de quatro litros de farinha da melhor qualidade umedecida com azeite. Será uma oferta especial, um aroma agradável ao SENHOR. Ofereçam também um litro de vinho como oferta derramada.

[[v3-23-14]]

^<<v3-23-14,14>>^ Nesse dia, não comam pão algum, nem cereal torrado ou fresco, enquanto não apresentarem a oferta ao seu Deus. Essa é uma lei permanente para vocês e deve ser cumprida de geração em geração, onde quer que morarem." A Festa da Colheita

[[v3-23-15]]

^<<v3-23-15,15>>^ "A partir do dia seguinte ao sábado, o dia em que levarem o feixe de cereal a fim de ser movido para o alto como oferta especial, contem sete semanas completas.

[[v3-23-16]]

^<<v3-23-16,16>>^ Continuem contando até o dia depois do sétimo sábado, isto é, cinquenta dias depois. Então apresentem uma oferta de cereal novo para o SENHOR.

[[v3-23-17]]

^<<v3-23-17,17>>^ Onde quer que morarem, levem dois pães que serão movidos para o alto como oferta especial diante do SENHOR. Preparem os pães com quatro quilos de farinha da melhor qualidade e assem-nos com fermento. Serão uma oferta para o SENHOR dos primeiros frutos de sua colheita.

[[v3-23-18]]

^<<v3-23-18,18>>^ Junto com o pão, apresentem sete cordeiros de um ano e sem defeito, um novilho e dois carneiros como holocaustos para o SENHOR. Esses holocaustos, junto com as ofertas de cereal e ofertas derramadas, serão uma oferta especial, um aroma agradável ao SENHOR.

[[v3-23-19]]

^<<v3-23-19,19>>^ Em seguida, ofereçam um bode como oferta pelo pecado e dois cordeiros de um ano como ofertas de paz.

[[v3-23-20]]

^<<v3-23-20,20>>^ "O sacerdote levantará os dois cordeiros como oferta especial para o SENHOR, junto com os pães que representam os primeiros frutos de suas colheitas. Essas ofertas, que são santas para o SENHOR, pertencem aos sacerdotes.

[[v3-23-21]]

^<<v3-23-21,21>>^ Esse mesmo dia será declarado dia de reunião sagrada, um dia em que não farão nenhum trabalho habitual. Essa é uma lei permanente para vocês e deve ser cumprida de geração em geração, onde quer que morarem.

[[v3-23-22]]

^<<v3-23-22,22>>^ "Quando fizerem a colheita da sua terra, não colham as espigas nos cantos dos campos e não apanhem aquilo que cair das mãos dos ceifeiros. Deixem esses grãos para os pobres e estrangeiros que vivem entre vocês. Eu sou o SENHOR, seu Deus".

[[v3-23-23]]

^<<v3-23-23,23>>^ O SENHOR disse a Moisés:

[[v3-23-24]]

^<<v3-23-24,24>>^ "Dê as seguintes instruções ao povo de Israel. No primeiro dia do sétimo mês, tenham um dia de descanso absoluto. Será uma reunião sagrada, uma celebração memorial comemorada com toques de trombeta.

[[v3-23-25]]

^<<v3-23-25,25>>^ Não façam nenhum trabalho habitual nesse dia, mas apresentem ofertas especiais para o SENHOR".

[[v3-23-26]]

^<<v3-23-26,26>>^ O SENHOR disse a Moisés:

[[v3-23-27]]

^<<v3-23-27,27>>^ "Comemorem o Dia da Expiação no décimo dia do mesmo sétimo mês. Celebrem-no como uma reunião sagrada, um dia para se humilharem e apresentarem ofertas especiais para o SENHOR.

[[v3-23-28]]

^<<v3-23-28,28>>^ Não façam trabalho algum durante todo esse dia, pois é o Dia da Expiação, no qual se fará expiação em seu favor diante do SENHOR, seu Deus.

[[v3-23-29]]

^<<v3-23-29,29>>^ Todos aqueles que não se humilharem nesse dia serão eliminados do meio do povo.

[[v3-23-30]]

^<<v3-23-30,30>>^ Destruirei aqueles que, dentre vocês, trabalharem em algo nesse dia.

[[v3-23-31]]

^<<v3-23-31,31>>^ Não façam trabalho algum. Essa é uma lei permanente para vocês e deve ser cumprida de geração em geração, onde quer que morarem.

[[v3-23-32]]

^<<v3-23-32,32>>^ Será um sábado de descanso absoluto para vocês e, nesse dia, deverão se humilhar. O dia de descanso começará ao entardecer do nono dia do mês e se estenderá até o entardecer do décimo dia".

[[v3-23-33]]

^<<v3-23-33,33>>^ O SENHOR também disse a Moisés:

[[v3-23-34]]

^<<v3-23-34,34>>^ "Dê as seguintes instruções ao povo de Israel. Comecem a celebrar a Festa das Cabanas no décimo quinto dia do sétimo mês. Essa festa em homenagem ao SENHOR durará sete dias.

[[v3-23-35]]

^<<v3-23-35,35>>^ O primeiro dia da festa será declarado reunião sagrada, na qual não farão nenhum trabalho habitual.

[[v3-23-36]]

^<<v3-23-36,36>>^ Durante sete dias, vocês apresentarão ofertas especiais para o SENHOR. No oitavo dia, haverá outra reunião sagrada, na qual apresentarão ofertas especiais para o SENHOR. Será uma ocasião solene, e ninguém fará nenhum trabalho habitual.

[[v3-23-37]]

^<<v3-23-37,37>>^ ("Essas são as festas que o SENHOR estabeleceu. Celebrem-nas a cada ano como reuniões sagradas, apresentando para o SENHOR, no dia apropriado, as ofertas especiais de sacrifícios queimados, ofertas de cereal, sacrifícios e ofertas derramadas.

[[v3-23-38]]

^<<v3-23-38,38>>^ Celebrem-nas além dos sábados habituais do SENHOR e apresentem as ofertas além das ofertas pessoais que vocês trazem no cumprimento de votos e das ofertas voluntárias para o SENHOR.)

[[v3-23-39]]

^<<v3-23-39,39>>^ "Lembrem-se de que essa festa de sete dias em homenagem ao SENHOR, a Festa das Cabanas, começa no décimo quinto dia do sétimo mês, depois de terem colhido tudo que a terra produziu. Celebrem a festa do SENHOR por sete dias. O primeiro e o oitavo dia da festa serão de descanso absoluto.

[[v3-23-40]]

^<<v3-23-40,40>>^ No primeiro dia, recolham galhos das mais belas árvores, folhagens de palmeiras, ramos de árvores verdejantes e de salgueiros que crescem junto dos riachos. Celebrem com alegria diante do SENHOR, seu Deus, por sete dias.

[[v3-23-41]]

^<<v3-23-41,41>>^ Comemorem essa festa em homenagem ao SENHOR por sete dias a cada ano. Essa é uma lei permanente para vocês e deve ser cumprida no sétimo mês, de geração em geração.

[[v3-23-42]]

^<<v3-23-42,42>>^ Durante sete dias, morarão ao ar livre em pequenas cabanas. Todos os israelitas de nascimento morarão em cabanas.

[[v3-23-43]]

^<<v3-23-43,43>>^ Desse modo, lembrarão cada nova geração de israelitas que eu fiz seus antepassados morarem em cabanas quando os libertei da terra do Egito. Eu sou o SENHOR, seu Deus".

[[v3-23-44]]

^<<v3-23-44,44>>^ Assim, Moisés transmitiu aos israelitas essas instruções sobre as festas anuais do SENHOR.

'''

xref:003-levitico/003-levitico-022.adoc#v3-22-0[&#60; Capítulo Anterior] | <<v3-23-0,Topo>> | xref:003-levitico/003-levitico-024.adoc#v3-24-0[Próximo Capítulo &#62;]