include::./index.adoc[]

[[v3-3-0]]
=== Levítico, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v3-3-1]]

^<<v3-3-1,1>>^ "Se apresentar ao SENHOR um animal do rebanho de gado como oferta de paz, poderá ser macho ou fêmea, desde que seja sem defeito.

[[v3-3-2]]

^<<v3-3-2,2>>^ Coloque a mão sobre a cabeça do animal e mate-o à entrada da tenda do encontro. Os filhos de Arão, os sacerdotes, derramarão o sangue do animal em todos os lados do altar.

[[v3-3-3]]

^<<v3-3-3,3>>^ Dessa oferta de paz, uma parte será apresentada como oferta especial para o SENHOR. Incluirá toda a gordura que envolve os órgãos internos,

[[v3-3-4]]

^<<v3-3-4,4>>^ os dois rins, a gordura ao redor deles perto dos lombos e o lóbulo do fígado. Todas essas partes serão removidas junto com os rins,

[[v3-3-5]]

^<<v3-3-5,5>>^ e os filhos de Arão queimarão tudo sobre a lenha acesa no altar. É uma oferta especial, um aroma agradável ao SENHOR.

[[v3-3-6]]

^<<v3-3-6,6>>^ "Se apresentar ao SENHOR um animal dos rebanhos de ovelhas ou de cabras como oferta de paz, poderá ser macho ou fêmea, desde que seja sem defeito.

[[v3-3-7]]

^<<v3-3-7,7>>^ Se apresentar como oferta um cordeiro, traga-o perante o SENHOR,

[[v3-3-8]]

^<<v3-3-8,8>>^ coloque a mão sobre a cabeça do animal e mate-o à entrada da tenda do encontro. Os filhos de Arão derramarão o sangue do cordeiro em todos os lados do altar.

[[v3-3-9]]

^<<v3-3-9,9>>^ Dessa oferta de paz, a gordura será apresentada como oferta especial para o SENHOR. Incluirá a gordura da parte gorda da cauda, cortada rente à espinha, toda a gordura que envolve os órgãos internos,

[[v3-3-10]]

^<<v3-3-10,10>>^ os dois rins, a gordura ao redor deles perto dos lombos e o lóbulo do fígado. Todas essas partes serão removidas junto com os rins,

[[v3-3-11]]

^<<v3-3-11,11>>^ e o sacerdote queimará tudo no altar. É uma oferta especial de alimento apresentado ao SENHOR.

[[v3-3-12]]

^<<v3-3-12,12>>^ "Se apresentar um cabrito como oferta, traga-o perante o SENHOR,

[[v3-3-13]]

^<<v3-3-13,13>>^ coloque a mão sobre a cabeça do animal e mate-o à entrada da tenda do encontro. Os filhos de Arão derramarão o sangue do cabrito em todos os lados do altar.

[[v3-3-14]]

^<<v3-3-14,14>>^ Dessa oferta, uma parte será apresentada como oferta especial para o SENHOR. Incluirá toda a gordura que envolve os órgãos internos,

[[v3-3-15]]

^<<v3-3-15,15>>^ os dois rins, a gordura ao redor deles perto dos lombos e o lóbulo do fígado. Todas essas partes serão removidas junto com os rins,

[[v3-3-16]]

^<<v3-3-16,16>>^ e o sacerdote queimará tudo no altar. É uma oferta especial de alimento, um aroma agradável ao SENHOR. Toda a gordura pertence ao SENHOR.

[[v3-3-17]]

^<<v3-3-17,17>>^ "Jamais coma a gordura ou o sangue. Essa é uma lei permanente para você e deve ser cumprida de geração em geração, onde quer que morarem".

'''

xref:003-levitico/003-levitico-002.adoc#v3-2-0[&#60; Capítulo Anterior] | <<v3-3-0,Topo>> | xref:003-levitico/003-levitico-004.adoc#v3-4-0[Próximo Capítulo &#62;]