include::./index.adoc[]

[[v3-14-0]]
=== Levítico, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v3-14-1]]

^<<v3-14-1,1>>^ O SENHOR disse a Moisés:

[[v3-14-2]]

^<<v3-14-2,2>>^ "Estas são as instruções a respeito da purificação da pessoa com lepra. Ela deverá comparecer perante o sacerdote,

[[v3-14-3]]

^<<v3-14-3,3>>^ que a levará para fora do acampamento e examinará a infecção. Se o sacerdote constatar que a lepra foi curada,

[[v3-14-4]]

^<<v3-14-4,4>>^ realizará uma cerimônia de purificação usando duas aves vivas cerimonialmente puras, um pedaço de madeira de cedro, um pano vermelho e um ramo de hissopo.

[[v3-14-5]]

^<<v3-14-5,5>>^ O sacerdote mandará matar uma das aves sobre uma vasilha de barro cheia de água limpa.

[[v3-14-6]]

^<<v3-14-6,6>>^ Em seguida, pegará a ave viva, o pedaço de madeira de cedro, o pano vermelho e o ramo de hissopo e os molhará no sangue da ave que foi morta sobre a água limpa.

[[v3-14-7]]

^<<v3-14-7,7>>^ Depois disso, o sacerdote aspergirá sete vezes o sangue da ave morta sobre a pessoa que está sendo purificada da lepra. Quando o sacerdote tiver purificado a pessoa, soltará a ave viva em campo aberto.

[[v3-14-8]]

^<<v3-14-8,8>>^ "A pessoa que está sendo purificada lavará suas roupas, raspará todos os pelos e se banhará com água. Estará cerimonialmente pura e poderá voltar ao acampamento. Contudo, ficará fora de sua tenda por sete dias.

[[v3-14-9]]

^<<v3-14-9,9>>^ No sétimo dia, raspará novamente todos os pelos, cabelos, pelos faciais e sobrancelhas. Lavará também suas roupas e se banhará com água. Desse modo, estará cerimonialmente pura.

[[v3-14-10]]

^<<v3-14-10,10>>^ "No oitavo dia, a pessoa que está sendo purificada trará dois cordeiros sem defeito e uma cordeira de um ano e sem defeito, junto com uma oferta de cereal de seis litros de farinha da melhor qualidade umedecida com azeite e uma caneca de azeite.

[[v3-14-11]]

^<<v3-14-11,11>>^ O sacerdote encarregado da cerimônia apresentará a pessoa a ser purificada, junto com as ofertas, diante do SENHOR, à entrada da tenda do encontro.

[[v3-14-12]]

^<<v3-14-12,12>>^ O sacerdote pegará um dos cordeiros e o azeite e os apresentará como oferta pela culpa, movendo-os para o alto como oferta especial para o SENHOR.

[[v3-14-13]]

^<<v3-14-13,13>>^ Em seguida, matará o cordeiro no lugar sagrado onde são mortos os animais para as ofertas pelo pecado e para os holocaustos. Assim como a oferta pelo pecado, a oferta pela culpa pertence ao sacerdote. É uma oferta santíssima.

[[v3-14-14]]

^<<v3-14-14,14>>^ Depois disso, o sacerdote pegará um pouco do sangue da oferta pela culpa e o colocará na ponta da orelha direita, no polegar da mão direita e no polegar do pé direito da pessoa que está sendo purificada.

[[v3-14-15]]

^<<v3-14-15,15>>^ "O sacerdote também colocará um pouco do azeite na palma de sua mão esquerda.

[[v3-14-16]]

^<<v3-14-16,16>>^ Molhará o dedo direito no azeite na palma da mão esquerda e com ele aspergirá sete vezes diante do SENHOR.

[[v3-14-17]]

^<<v3-14-17,17>>^ Parte do azeite que está em sua mão ele colocará na ponta da orelha direita, no polegar da mão direita e no polegar do pé direito da pessoa que está sendo purificada, em cima do sangue da oferta pela culpa.

[[v3-14-18]]

^<<v3-14-18,18>>^ O sacerdote colocará o azeite restante em sua mão na cabeça da pessoa que está sendo purificada. Desse modo, o sacerdote fará expiação pela pessoa diante do SENHOR.

[[v3-14-19]]

^<<v3-14-19,19>>^ "Então o sacerdote apresentará a oferta pelo pecado para fazer expiação pela pessoa que foi curada da lepra. Em seguida, o sacerdote matará o animal para o holocausto

[[v3-14-20]]

^<<v3-14-20,20>>^ e o apresentará sobre o altar junto com a oferta de cereal. Desse modo, o sacerdote fará expiação pela pessoa que foi curada, e ela ficará cerimonialmente pura.

[[v3-14-21]]

^<<v3-14-21,21>>^ "Quem for muito pobre e não tiver recursos para apresentar essas ofertas poderá levar um cordeiro para a oferta pela culpa, que será movido para o alto como oferta especial para a purificação. Levará também dois litros de farinha da melhor qualidade umedecida com azeite para a oferta de cereal e uma caneca de azeite.

[[v3-14-22]]

^<<v3-14-22,22>>^ A oferta incluirá ainda duas rolinhas ou dois pombinhos, de acordo com os recursos da pessoa. Uma das aves será usada para a oferta pelo pecado, e a outra, para o holocausto.

[[v3-14-23]]

^<<v3-14-23,23>>^ No oitavo dia da cerimônia de purificação, a pessoa que está sendo purificada levará as ofertas ao sacerdote na presença do SENHOR, à entrada da tenda do encontro.

[[v3-14-24]]

^<<v3-14-24,24>>^ O sacerdote pegará o cordeiro para a oferta pela culpa, junto com o azeite, e os moverá para o alto como oferta especial para o SENHOR.

[[v3-14-25]]

^<<v3-14-25,25>>^ Depois disso, o sacerdote matará o cordeiro para a oferta pela culpa. Pegará um pouco do sangue e o colocará na ponta da orelha direita, no polegar da mão direita e no polegar do pé direito da pessoa que está sendo purificada.

[[v3-14-26]]

^<<v3-14-26,26>>^ "O sacerdote também derramará um pouco do azeite na palma de sua mão esquerda.

[[v3-14-27]]

^<<v3-14-27,27>>^ Molhará o dedo direito no azeite na palma de sua mão esquerda e com ele aspergirá sete vezes diante do SENHOR.

[[v3-14-28]]

^<<v3-14-28,28>>^ Parte do azeite que está em sua mão ele colocará na ponta da orelha direita, no polegar da mão direita e no polegar do pé direito da pessoa que está sendo purificada, em cima do sangue da oferta pela culpa.

[[v3-14-29]]

^<<v3-14-29,29>>^ O sacerdote colocará o azeite restante em sua mão na cabeça da pessoa que está sendo purificada. Desse modo, o sacerdote fará expiação pela pessoa diante do SENHOR.

[[v3-14-30]]

^<<v3-14-30,30>>^ "Então o sacerdote oferecerá as duas rolinhas ou os dois pombinhos, de acordo com os recursos da pessoa.

[[v3-14-31]]

^<<v3-14-31,31>>^ Uma das aves é uma oferta pelo pecado, e a outra é um holocausto; serão apresentadas junto com a oferta de cereal. Desse modo, o sacerdote fará expiação pela pessoa diante do SENHOR.

[[v3-14-32]]

^<<v3-14-32,32>>^ Essas são as instruções para a purificação daqueles que se recuperaram da lepra, mas que não têm recursos para levar as ofertas requeridas para a cerimônia de purificação".

[[v3-14-33]]

^<<v3-14-33,33>>^ Então o SENHOR disse a Moisés e a Arão:

[[v3-14-34]]

^<<v3-14-34,34>>^ "Quando chegarem a Canaã, a terra que eu lhes dou como propriedade, e eu contaminar com manchas de mofo algumas das casas de sua terra,

[[v3-14-35]]

^<<v3-14-35,35>>^ o dono de uma dessas casas irá ao sacerdote e dirá: ‘Minha casa parece ter manchas de mofo’.

[[v3-14-36]]

^<<v3-14-36,36>>^ Antes de entrar para examinar a casa, o sacerdote mandará esvaziá-la, a fim de que nada dentro dela seja declarado cerimonialmente impuro. Em seguida, entrará na casa

[[v3-14-37]]

^<<v3-14-37,37>>^ e examinará o mofo nas paredes. Se encontrar manchas esverdeadas ou avermelhadas e a contaminação parecer mais profunda que a superfície da parede,

[[v3-14-38]]

^<<v3-14-38,38>>^ o sacerdote sairá pela porta e isolará a casa por sete dias.

[[v3-14-39]]

^<<v3-14-39,39>>^ No sétimo dia, o sacerdote voltará para examiná-la. Se constatar que as manchas se espalharam nas paredes,

[[v3-14-40]]

^<<v3-14-40,40>>^ o sacerdote ordenará que as pedras das áreas afetadas sejam removidas e levadas para fora da cidade, até um lugar cerimonialmente impuro.

[[v3-14-41]]

^<<v3-14-41,41>>^ Depois disso, as paredes internas da casa serão inteiramente raspadas, e o material raspado será jogado num lugar impuro fora da cidade.

[[v3-14-42]]

^<<v3-14-42,42>>^ Outras pedras serão trazidas para substituir as que foram removidas, e as paredes serão rebocadas com barro novo.

[[v3-14-43]]

^<<v3-14-43,43>>^ "Se, contudo, o mofo reaparecer depois de todas as pedras terem sido substituídas e de a casa ter sido raspada e rebocada de novo,

[[v3-14-44]]

^<<v3-14-44,44>>^ o sacerdote voltará e examinará a casa. Se constatar que as manchas de mofo se espalharam, é evidente que as paredes foram contaminadas por mofo corrosivo, e a casa está impura.

[[v3-14-45]]

^<<v3-14-45,45>>^ Será demolida e suas pedras, madeiras e todo o seu reboco serão levados para fora da cidade, até um lugar cerimonialmente impuro.

[[v3-14-46]]

^<<v3-14-46,46>>^ Quem entrar na casa durante o período de isolamento ficará cerimonialmente impuro até o entardecer.

[[v3-14-47]]

^<<v3-14-47,47>>^ Quem dormir ou comer na casa deverá lavar suas roupas.

[[v3-14-48]]

^<<v3-14-48,48>>^ "Se, contudo, o sacerdote voltar para examinar a casa e constatar que as manchas de mofo não reapareceram depois de colocado o reboco novo, ele a declarará pura, pois é evidente que o mofo desapareceu.

[[v3-14-49]]

^<<v3-14-49,49>>^ A fim de purificar a casa, o sacerdote pegará duas aves, um pedaço de madeira de cedro, um pano vermelho e um ramo de hissopo.

[[v3-14-50]]

^<<v3-14-50,50>>^ Matará uma das aves sobre uma vasilha de barro cheia de água limpa.

[[v3-14-51]]

^<<v3-14-51,51>>^ Pegará o pedaço de madeira de cedro, o ramo de hissopo, o pano vermelho e a ave viva e os molhará no sangue da ave morta e na água limpa. Em seguida, aspergirá a mistura sobre a casa sete vezes.

[[v3-14-52]]

^<<v3-14-52,52>>^ Quando o sacerdote tiver purificado a casa exatamente dessa forma,

[[v3-14-53]]

^<<v3-14-53,53>>^ soltará a ave viva em campo aberto fora da cidade. Desse modo, o sacerdote fará expiação pela casa, e ela ficará cerimonialmente pura.

[[v3-14-54]]

^<<v3-14-54,54>>^ "Essas são as instruções para lidar com a lepra, incluindo feridas de sarna,

[[v3-14-55]]

^<<v3-14-55,55>>^ com manchas de mofo sobre peças de roupa ou numa casa,

[[v3-14-56]]

^<<v3-14-56,56>>^ e com inchaços, erupções ou descolorações da pele.

[[v3-14-57]]

^<<v3-14-57,57>>^ Esse procedimento determinará se a pessoa ou objeto está cerimonialmente puro ou impuro. "Essas são as instruções a respeito da lepra e do mofo".

'''

xref:003-levitico/003-levitico-013.adoc#v3-13-0[&#60; Capítulo Anterior] | <<v3-14-0,Topo>> | xref:003-levitico/003-levitico-015.adoc#v3-15-0[Próximo Capítulo &#62;]