include::./index.adoc[]

[[v3-22-0]]
=== Levítico, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v3-22-1]]

^<<v3-22-1,1>>^ O SENHOR disse a Moisés:

[[v3-22-2]]

^<<v3-22-2,2>>^ "Diga a Arão e a seus filhos que tenham muito respeito pelas ofertas sagradas que os israelitas consagrarem a mim, a fim de não desonrarem meu santo nome. Eu sou o SENHOR.

[[v3-22-3]]

^<<v3-22-3,3>>^ Dê a eles as seguintes instruções. "Nas gerações futuras, se algum de seus descendentes estiver cerimonialmente impuro ao se aproximar das ofertas sagradas que os israelitas consagrarem ao SENHOR, ele será eliminado de minha presença. Eu sou o SENHOR.

[[v3-22-4]]

^<<v3-22-4,4>>^ "Se algum dos descendentes de Arão tiver lepra ou qualquer tipo de fluxo que o torne cerimonialmente impuro, não comerá das ofertas sagradas enquanto não for declarado puro. Também se tornará impuro se tocar num cadáver, expelir sêmen,

[[v3-22-5]]

^<<v3-22-5,5>>^ tocar num animal que rasteja pelo chão e seja impuro ou tocar em alguém que, por qualquer motivo, esteja cerimonialmente impuro.

[[v3-22-6]]

^<<v3-22-6,6>>^ Quem se contaminar de alguma dessas formas ficará impuro até o entardecer. Não comerá das ofertas sagradas enquanto não tiver se banhado com água.

[[v3-22-7]]

^<<v3-22-7,7>>^ Depois do pôr do sol, estará cerimonialmente puro outra vez e poderá comer das ofertas sagradas, pois são seu alimento.

[[v3-22-8]]

^<<v3-22-8,8>>^ Não comerá um animal que morreu de forma natural ou que foi despedaçado por animais selvagens, pois se contaminaria. Eu sou o SENHOR.

[[v3-22-9]]

^<<v3-22-9,9>>^ "Os sacerdotes obedecerão fielmente às minhas ordens. Do contrário, serão culpados de pecado e morrerão, pois menosprezaram o que lhes ordenei. Eu sou o SENHOR, que os santifica.

[[v3-22-10]]

^<<v3-22-10,10>>^ "Ninguém de fora da família do sacerdote comerá das ofertas sagradas. Nem mesmo hóspedes e empregados da casa do sacerdote poderão comê-las.

[[v3-22-11]]

^<<v3-22-11,11>>^ Mas, se o sacerdote comprar um escravo, esse escravo poderá comer das ofertas sagradas. E, se o escravo tiver filhos, eles também poderão comer de seu alimento.

[[v3-22-12]]

^<<v3-22-12,12>>^ Se a filha do sacerdote se casar com alguém de fora da família sacerdotal, não poderá mais comer das ofertas sagradas.

[[v3-22-13]]

^<<v3-22-13,13>>^ Se, contudo, ficar viúva ou divorciar-se, sem ter filhos para sustentá-la, e voltar a morar na casa do pai, como quando era jovem, poderá comer novamente do alimento do pai. Com exceção desses casos, ninguém de fora da família do sacerdote comerá das ofertas sagradas.

[[v3-22-14]]

^<<v3-22-14,14>>^ "Se alguém não autorizado comer das ofertas sagradas por engano, pagará ao sacerdote aquilo que comeu, mais um quinto do valor.

[[v3-22-15]]

^<<v3-22-15,15>>^ Os sacerdotes não contaminarão as ofertas sagradas apresentadas pelos israelitas ao SENHOR,

[[v3-22-16]]

^<<v3-22-16,16>>^ permitindo que sejam consumidas por pessoas não autorizadas. Elas se tornariam culpadas e teriam de fazer reparação. Eu sou o SENHOR, que os santifica".

[[v3-22-17]]

^<<v3-22-17,17>>^ O SENHOR também disse a Moisés:

[[v3-22-18]]

^<<v3-22-18,18>>^ "Dê as seguintes instruções a Arão, a seus filhos e a todo o povo de Israel. Elas se aplicam tanto aos israelitas de nascimento como aos estrangeiros que vivem entre vocês. "Se alguém apresentar ao SENHOR um holocausto, seja como cumprimento de um voto ou como oferta voluntária,

[[v3-22-19]]

^<<v3-22-19,19>>^ só será aceito se o animal oferecido for um macho sem defeito. Poderá ser um boi, um carneiro ou um bode.

[[v3-22-20]]

^<<v3-22-20,20>>^ Não apresentem um animal defeituoso, pois o SENHOR não o aceitará em favor de vocês.

[[v3-22-21]]

^<<v3-22-21,21>>^ "Se alguém apresentar ao SENHOR uma oferta de paz, seja como cumprimento de um voto ou como oferta voluntária, escolha do gado ou do rebanho um animal perfeito, sem defeito algum.

[[v3-22-22]]

^<<v3-22-22,22>>^ Não ofereçam um animal cego, aleijado, ferido, ou que tenha um quisto, um ferimento na pele, ou sarna. Nunca ofereçam nenhum desses animais no altar como ofertas especiais para o SENHOR.

[[v3-22-23]]

^<<v3-22-23,23>>^ Se um boi ou um cordeiro tiver uma perna mais comprida ou mais curta que as outras, poderá ser apresentado como oferta voluntária, mas não como cumprimento de um voto.

[[v3-22-24]]

^<<v3-22-24,24>>^ Se um animal tiver testículos danificados ou for castrado, não poderá ser oferecido ao SENHOR. Nunca façam isso em sua própria terra

[[v3-22-25]]

^<<v3-22-25,25>>^ e não recebam de estrangeiros animais como esses em pagamento, para depois oferecê-los como sacrifício a Deus. Não serão aceitos em seu favor, pois são mutilados ou defeituosos".

[[v3-22-26]]

^<<v3-22-26,26>>^ E o SENHOR disse a Moisés:

[[v3-22-27]]

^<<v3-22-27,27>>^ "Quando nascer um bezerro, cordeiro ou cabrito, ficará sete dias com a mãe. Do oitavo dia em diante, será aceitável como oferta especial para o SENHOR.

[[v3-22-28]]

^<<v3-22-28,28>>^ Não matem a mãe e sua cria no mesmo dia, seja uma vaca, uma ovelha ou uma cabra.

[[v3-22-29]]

^<<v3-22-29,29>>^ Quando levarem uma oferta de gratidão ao SENHOR, sacrifiquem-na corretamente para que sejam aceitos.

[[v3-22-30]]

^<<v3-22-30,30>>^ Comam todo o animal sacrificado no dia em que for apresentado. Não deixem parte alguma do animal até a manhã seguinte. Eu sou o SENHOR.

[[v3-22-31]]

^<<v3-22-31,31>>^ "Guardem fielmente meus mandamentos pondo-os em prática, pois eu sou o SENHOR.

[[v3-22-32]]

^<<v3-22-32,32>>^ Não desonrem meu santo nome, pois demonstrarei minha santidade no meio dos israelitas. Eu sou o SENHOR, que os santifica.

[[v3-22-33]]

^<<v3-22-33,33>>^ Eu os libertei da terra do Egito para ser o seu Deus. Eu sou o SENHOR".

'''

xref:003-levitico/003-levitico-021.adoc#v3-21-0[&#60; Capítulo Anterior] | <<v3-22-0,Topo>> | xref:003-levitico/003-levitico-023.adoc#v3-23-0[Próximo Capítulo &#62;]