include::./index.adoc[]

[[v3-10-0]]
=== Levítico, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v3-10-1]]

^<<v3-10-1,1>>^ Nadabe e Abiú, filhos de Arão, colocaram brasas em seus incensários e as salpicaram com incenso. Com isso, trouxeram fogo estranho diante do SENHOR, diferente do que ele havia ordenado.

[[v3-10-2]]

^<<v3-10-2,2>>^ Por isso, fogo saiu da presença do SENHOR e os devorou, e eles morreram diante do SENHOR.

[[v3-10-3]]

^<<v3-10-3,3>>^ Então Moisés disse a Arão: "Foi isto que o SENHOR declarou: ‘Mostrarei minha santidade entre aqueles que se aproximarem de mim. Mostrarei minha glória diante de todo o povo’". E Arão ficou em silêncio.

[[v3-10-4]]

^<<v3-10-4,4>>^ Moisés chamou Misael e Elzafã, primos de Arão e filhos de Uziel, tio de Arão, e lhes disse: "Venham cá e levem o corpo de seus parentes da frente do santuário para um lugar fora do acampamento".

[[v3-10-5]]

^<<v3-10-5,5>>^ Eles se aproximaram e os puxaram pelas roupas para fora do acampamento, conforme Moisés havia ordenado.

[[v3-10-6]]

^<<v3-10-6,6>>^ Então Moisés disse a Arão e a seus filhos Eleazar e Itamar: "Não deixem o cabelo despenteado nem rasguem suas roupas em sinal de luto. Se o fizerem, morrerão, e a ira do SENHOR ferirá toda a comunidade de Israel. Mas outros israelitas, seus parentes, poderão ficar de luto porque o SENHOR destruiu Nadabe e Abiú com fogo.

[[v3-10-7]]

^<<v3-10-7,7>>^ Não saiam da entrada da tenda do encontro, ou morrerão, pois foram ungidos com o óleo da unção do SENHOR". E fizeram conforme Moisés ordenou. Instruções para a conduta sacerdotal

[[v3-10-8]]

^<<v3-10-8,8>>^ Então o SENHOR disse a Arão:

[[v3-10-9]]

^<<v3-10-9,9>>^ "Você e seus descendentes jamais deverão beber vinho ou qualquer outra bebida fermentada antes de entrar na tenda do encontro. Se o fizerem, morrerão. Essa é uma lei permanente para vocês e deve ser cumprida de geração em geração.

[[v3-10-10]]

^<<v3-10-10,10>>^ Façam distinção entre o que é santo e o que é comum, entre o que é impuro e o que é puro,

[[v3-10-11]]

^<<v3-10-11,11>>^ e ensinem aos israelitas todos os decretos que o SENHOR lhes deu por meio de Moisés".

[[v3-10-12]]

^<<v3-10-12,12>>^ Moisés disse a Arão e aos filhos que lhe restaram, Eleazar e Itamar: "Peguem o que sobrar da oferta de cereal depois que uma porção tiver sido apresentada como oferta especial para o SENHOR e comam-na junto do altar. Não deverá conter fermento, pois é santíssima.

[[v3-10-13]]

^<<v3-10-13,13>>^ Comam-na num lugar sagrado, pois foi dada a vocês e a seus descendentes como sua porção das ofertas especiais apresentadas ao SENHOR. Foram essas as ordens que recebi.

[[v3-10-14]]

^<<v3-10-14,14>>^ Quanto ao peito e à coxa que foram movidos para o alto como oferta especial, poderão comê-los em qualquer lugar cerimonialmente puro. Essas são as partes que foram dadas a você e a seus descendentes como sua porção das ofertas de paz apresentadas pelos israelitas.

[[v3-10-15]]

^<<v3-10-15,15>>^ Movam para o alto o peito e a coxa como oferta especial para o SENHOR, junto com a gordura das ofertas especiais. Essas partes pertencerão a vocês e a seus descendentes como direito permanente, conforme o SENHOR ordenou".

[[v3-10-16]]

^<<v3-10-16,16>>^ Depois, Moisés procurou cuidadosamente pelo bode da oferta pelo pecado. Quando descobriu que tinha sido queimado, ficou furioso com Eleazar e Itamar, os filhos que restaram a Arão, e lhes disse:

[[v3-10-17]]

^<<v3-10-17,17>>^ "Por que não comeram a oferta pelo pecado no lugar sagrado? É uma oferta santíssima! O SENHOR a deu a vocês para remover a culpa da comunidade e fazer expiação por ela.

[[v3-10-18]]

^<<v3-10-18,18>>^ Uma vez que o sangue do animal não foi levado ao lugar santo, vocês tinham a obrigação de comer a carne no lugar sagrado, conforme eu ordenei!".

[[v3-10-19]]

^<<v3-10-19,19>>^ Arão respondeu a Moisés: "Hoje meus filhos apresentaram ao SENHOR sua oferta pelo pecado e seu holocausto. E, no entanto, esta tragédia aconteceu comigo. Será que o SENHOR teria se agradado se eu tivesse comido a oferta pelo pecado do povo num dia como este?".

[[v3-10-20]]

^<<v3-10-20,20>>^ Quando Moisés ouviu isso, deu-se por satisfeito.

'''

xref:003-levitico/003-levitico-009.adoc#v3-9-0[&#60; Capítulo Anterior] | <<v3-10-0,Topo>> | xref:003-levitico/003-levitico-011.adoc#v3-11-0[Próximo Capítulo &#62;]