include::./index.adoc[]

[[v3-27-0]]
=== Levítico, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v3-27-1]]

^<<v3-27-1,1>>^ O SENHOR disse a Moisés:

[[v3-27-2]]

^<<v3-27-2,2>>^ "Dê as seguintes instruções ao povo de Israel. Se alguém fizer um voto especial de dedicar uma pessoa ao SENHOR mediante o pagamento do valor dessa pessoa,

[[v3-27-3]]

^<<v3-27-3,3>>^ deve usar a seguinte escala de valores. Um homem de 20 a 60 anos vale 600 gramas de prata, de acordo com o siclo do santuário;

[[v3-27-4]]

^<<v3-27-4,4>>^ uma mulher da mesma idade vale 360 gramas de prata.

[[v3-27-5]]

^<<v3-27-5,5>>^ Um menino ou rapaz de 5 a 20 anos vale 240 gramas de prata; uma menina ou moça da mesma idade vale 120 gramas de prata.

[[v3-27-6]]

^<<v3-27-6,6>>^ Um menino de 1 mês a 5 anos vale 60 gramas de prata; uma menina da mesma idade vale 36 gramas de prata.

[[v3-27-7]]

^<<v3-27-7,7>>^ Um homem de mais de 60 anos vale 180 gramas de prata; uma mulher da mesma idade vale 120 gramas de prata.

[[v3-27-8]]

^<<v3-27-8,8>>^ Quem desejar fazer o voto, mas não puder pagar a quantia exigida, levará a pessoa ao sacerdote, e ele determinará a quantia a ser paga com base nos recursos de quem fez o voto.

[[v3-27-9]]

^<<v3-27-9,9>>^ "Se alguém fizer o voto de entregar um animal como oferta para o SENHOR, toda oferta ao SENHOR será considerada santa.

[[v3-27-10]]

^<<v3-27-10,10>>^ Não trocará nem substituirá o animal por outro, seja um animal bom por um ruim ou um animal ruim por um bom. Mas, se trocar um animal por outro, tanto o primeiro como o segundo serão considerados santos.

[[v3-27-11]]

^<<v3-27-11,11>>^ Se o voto for a entrega de um animal impuro que não é aceitável como oferta para o SENHOR, levará o animal até o sacerdote,

[[v3-27-12]]

^<<v3-27-12,12>>^ e ele determinará o valor, e sua avaliação, alta ou baixa, será definitiva.

[[v3-27-13]]

^<<v3-27-13,13>>^ Quem desejar comprar de volta o animal pagará o valor estipulado pelo sacerdote, mais um quinto do valor.

[[v3-27-14]]

^<<v3-27-14,14>>^ "Se alguém dedicar uma casa ao SENHOR, o sacerdote a avaliará. Sua avaliação, seja alta ou baixa, será definitiva.

[[v3-27-15]]

^<<v3-27-15,15>>^ Se a pessoa que dedicou a casa quiser comprá-la de volta, pagará o valor estipulado pelo sacerdote, mais um quinto do valor. Desse modo, a casa voltará a ser sua.

[[v3-27-16]]

^<<v3-27-16,16>>^ "Se alguém dedicar ao SENHOR uma parte de sua propriedade familiar, o valor será determinado de acordo com a quantidade de sementes necessária para semeá-la: 600 gramas de prata por um campo semeado com 220 litros de sementes de cevada.

[[v3-27-17]]

^<<v3-27-17,17>>^ Se o campo for dedicado ao SENHOR no Ano do Jubileu, será aplicado o valor total.

[[v3-27-18]]

^<<v3-27-18,18>>^ Mas, se o campo for dedicado depois do Ano do Jubileu, o sacerdote calculará o valor da terra de modo proporcional ao número de colheitas restantes até o próximo Ano do Jubileu. O valor calculado será reduzido a cada ano que passar.

[[v3-27-19]]

^<<v3-27-19,19>>^ Se a pessoa que dedicou o campo desejar comprá-lo de volta, pagará o valor estipulado pelo sacerdote, mais um quinto do valor. O campo voltará a ser legalmente seu.

[[v3-27-20]]

^<<v3-27-20,20>>^ Se, contudo, não quiser reavê-lo e ele for vendido a outra pessoa, o campo não poderá mais ser comprado de volta.

[[v3-27-21]]

^<<v3-27-21,21>>^ Quando o campo for liberado no Ano do Jubileu, será santo, totalmente dedicado ao SENHOR, e se tornará propriedade dos sacerdotes.

[[v3-27-22]]

^<<v3-27-22,22>>^ "Se alguém dedicar ao SENHOR um campo que comprou, mas que não faz parte de sua propriedade familiar,

[[v3-27-23]]

^<<v3-27-23,23>>^ o sacerdote determinará o valor com base no número de colheitas restantes até o próximo Ano do Jubileu. Nesse mesmo dia, a pessoa entregará o valor do campo como doação sagrada para o SENHOR.

[[v3-27-24]]

^<<v3-27-24,24>>^ No Ano do Jubileu, o campo será devolvido a quem o herdou como propriedade familiar.

[[v3-27-25]]

^<<v3-27-25,25>>^ (Todos os pagamentos serão calculados de acordo com o peso do siclo do santuário, equivalente a doze gramas.)

[[v3-27-26]]

^<<v3-27-26,26>>^ "O macho da primeira cria de um animal não poderá ser dedicado ao SENHOR, pois a primeira cria de seu gado, de suas ovelhas e de suas cabras já pertence a ele.

[[v3-27-27]]

^<<v3-27-27,27>>^ É possível, porém, comprar de volta a primeira cria de um animal impuro mediante o pagamento do valor estipulado pelo sacerdote, mais um quinto do valor. Se o animal não for comprado de volta, o sacerdote o venderá pelo valor estipulado.

[[v3-27-28]]

^<<v3-27-28,28>>^ "Contudo, qualquer coisa totalmente dedicada ao SENHOR, seja uma pessoa, um animal ou uma propriedade familiar, jamais será vendida ou comprada de volta. Tudo que é assim consagrado é santíssimo e pertence ao SENHOR.

[[v3-27-29]]

^<<v3-27-29,29>>^ Nenhuma pessoa que tenha sido definitivamente marcada para destruição poderá ser comprada de volta; deverá ser executada.

[[v3-27-30]]

^<<v3-27-30,30>>^ "A décima parte dos produtos da terra, sejam os cereais dos campos ou os frutos das árvores, pertence ao SENHOR e deve ser consagrada a ele.

[[v3-27-31]]

^<<v3-27-31,31>>^ Se você desejar comprar de volta a décima parte dos cereais ou frutos pertencente ao SENHOR, pagará o seu valor, mais um quinto do valor.

[[v3-27-32]]

^<<v3-27-32,32>>^ Conte um de cada dez animais do seu gado e dos seus rebanhos e separe-os para o SENHOR, considerando-os santos.

[[v3-27-33]]

^<<v3-27-33,33>>^ Não faça distinção entre animais bons e ruins nem substitua um pelo outro. Mas, se trocar um animal por outro, tanto o primeiro como o seu substituto serão considerados santos e não poderão ser comprados de volta".

[[v3-27-34]]

^<<v3-27-34,34>>^ Esses são os mandamentos que o SENHOR deu aos israelitas por meio de Moisés no monte Sinai.

'''

xref:003-levitico/003-levitico-026.adoc#v3-26-0[&#60; Capítulo Anterior] | <<v3-27-0,Topo>> | xref:004-numeros/004-numeros-001.adoc#v4-1-0[Próximo Capítulo &#62;]