include::./index.adoc[]

[[v3-7-0]]
=== Levítico, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v3-7-1]]

^<<v3-7-1,1>>^ "Estas são as instruções para a oferta pela culpa. É oferta santíssima.

[[v3-7-2]]

^<<v3-7-2,2>>^ O animal sacrificado como oferta pela culpa será morto onde são mortos os animais para os holocaustos, e seu sangue será derramado em todos os lados do altar.

[[v3-7-3]]

^<<v3-7-3,3>>^ Em seguida, o sacerdote oferecerá toda a gordura sobre o altar, incluindo a gordura da parte gorda da cauda, a gordura que envolve os órgãos internos,

[[v3-7-4]]

^<<v3-7-4,4>>^ os dois rins, a gordura ao redor deles perto dos lombos e o lóbulo do fígado. Ele removerá todas essas partes junto com os rins

[[v3-7-5]]

^<<v3-7-5,5>>^ e queimará tudo no altar como oferta especial apresentada ao SENHOR. É a oferta pela culpa.

[[v3-7-6]]

^<<v3-7-6,6>>^ Qualquer homem da família dos sacerdotes poderá comer a carne. Deverá comê-la num lugar sagrado, pois é santíssima.

[[v3-7-7]]

^<<v3-7-7,7>>^ "As mesmas instruções se aplicam tanto à oferta pela culpa como à oferta pelo pecado. Ambas pertencem ao sacerdote que as utiliza para fazer expiação.

[[v3-7-8]]

^<<v3-7-8,8>>^ No caso dos holocaustos, o sacerdote poderá ficar com o couro do animal sacrificado.

[[v3-7-9]]

^<<v3-7-9,9>>^ Toda oferta de cereal assada no forno, preparada numa panela ou cozida numa assadeira, pertence ao sacerdote que a apresenta.

[[v3-7-10]]

^<<v3-7-10,10>>^ Todas as outras ofertas de cereal, preparadas com farinha seca ou farinha umedecida com azeite, deverão ser divididas em partes iguais entre todos os sacerdotes, os descendentes de Arão." Instruções adicionais para a oferta de paz

[[v3-7-11]]

^<<v3-7-11,11>>^ "Estas são as instruções sobre os diferentes tipos de oferta de paz que podem ser apresentados ao SENHOR.

[[v3-7-12]]

^<<v3-7-12,12>>^ Se alguém apresentar sua oferta de paz para expressar gratidão, o animal que normalmente é oferecido será acompanhado de bolos sem fermento misturados com azeite, pães finos sem fermento untados com azeite e bolos feitos de farinha da melhor qualidade misturada com azeite.

[[v3-7-13]]

^<<v3-7-13,13>>^ Essa oferta de paz para expressar gratidão também será acompanhada de pães preparados com fermento.

[[v3-7-14]]

^<<v3-7-14,14>>^ Um pão de cada tipo será apresentado como oferta para o SENHOR. Os pães serão do sacerdote que derramar o sangue da oferta de paz no altar.

[[v3-7-15]]

^<<v3-7-15,15>>^ A carne da oferta de paz para expressar gratidão será comida no mesmo dia em que for oferecida. Nada poderá ser guardado até a manhã seguinte.

[[v3-7-16]]

^<<v3-7-16,16>>^ "Se alguém apresentar uma oferta como cumprimento de um voto ou como oferta voluntária, a carne será comida no mesmo dia em que o sacrifício for oferecido, mas o que restar poderá ser comido no dia seguinte.

[[v3-7-17]]

^<<v3-7-17,17>>^ A carne que restar até o terceiro dia deverá ser totalmente queimada.

[[v3-7-18]]

^<<v3-7-18,18>>^ Se alguma porção da carne da oferta de paz for comida no terceiro dia, a pessoa que a trouxe não será aceita pelo SENHOR e a oferta não terá valor. A essa altura, a carne estará contaminada, e quem a comer será castigado por causa de seu pecado.

[[v3-7-19]]

^<<v3-7-19,19>>^ "A carne que tocar qualquer coisa cerimonialmente impura não poderá ser comida; deverá ser totalmente queimada. Mas a carne do sacrifício poderá ser comida por quem estiver cerimonialmente puro.

[[v3-7-20]]

^<<v3-7-20,20>>^ Se alguém estiver cerimonialmente impuro e comer a carne da oferta de paz apresentada ao SENHOR, será eliminado do meio do povo.

[[v3-7-21]]

^<<v3-7-21,21>>^ Se tocar em algo impuro, seja contaminação humana, de um animal impuro ou de qualquer outra coisa impura e detestável, e depois comer a carne de uma oferta de paz apresentada ao SENHOR, será eliminado do meio do povo". O sangue e a gordura são proibidos

[[v3-7-22]]

^<<v3-7-22,22>>^ Então o SENHOR disse a Moisés:

[[v3-7-23]]

^<<v3-7-23,23>>^ "Dê as seguintes instruções ao povo de Israel. Jamais comam gordura, seja de boi, carneiro ou cabrito.

[[v3-7-24]]

^<<v3-7-24,24>>^ A gordura de um animal encontrado morto ou despedaçado por animais selvagens jamais deverá ser comida, embora possa ser usada para outros fins.

[[v3-7-25]]

^<<v3-7-25,25>>^ Quem comer a gordura de um animal apresentado como oferta especial para o SENHOR será eliminado do meio do povo.

[[v3-7-26]]

^<<v3-7-26,26>>^ Onde quer que morarem, jamais consumam o sangue de qualquer ave ou animal.

[[v3-7-27]]

^<<v3-7-27,27>>^ Quem consumir sangue será eliminado do meio do povo". A porção dos sacerdotes

[[v3-7-28]]

^<<v3-7-28,28>>^ O SENHOR disse a Moisés:

[[v3-7-29]]

^<<v3-7-29,29>>^ "Dê as seguintes instruções ao povo de Israel. Quando apresentarem uma oferta de paz ao SENHOR, levem uma parte dela como oferta para o SENHOR.

[[v3-7-30]]

^<<v3-7-30,30>>^ Apresentem-na com suas próprias mãos como oferta especial para o SENHOR. Levem a gordura do animal junto com o peito e movam o peito para o alto como oferta especial para o SENHOR.

[[v3-7-31]]

^<<v3-7-31,31>>^ Em seguida, o sacerdote queimará a gordura no altar, mas o peito será de Arão e seus descendentes.

[[v3-7-32]]

^<<v3-7-32,32>>^ Entreguem como oferta ao sacerdote a coxa direita da oferta de paz.

[[v3-7-33]]

^<<v3-7-33,33>>^ A coxa direita será sempre a porção entregue ao sacerdote que apresentar o sangue e a gordura da oferta de paz.

[[v3-7-34]]

^<<v3-7-34,34>>^ Pois reservei para os sacerdotes o peito da oferta especial e a coxa direita da oferta sagrada. Arão e seus descendentes têm o direito permanente de participar das ofertas de paz que os israelitas apresentarem.

[[v3-7-35]]

^<<v3-7-35,35>>^ Essa é sua porção por direito das ofertas especiais apresentadas ao SENHOR, reservada para Arão e seus descendentes desde o dia em que eles foram separados para servir ao SENHOR como sacerdotes.

[[v3-7-36]]

^<<v3-7-36,36>>^ No dia em que foram ungidos, o SENHOR ordenou que os israelitas entregassem essas partes aos sacerdotes como sua porção permanente, de geração em geração".

[[v3-7-37]]

^<<v3-7-37,37>>^ Essas são as instruções para o holocausto, a oferta de cereal, a oferta pelo pecado e a oferta pela culpa e também para a oferta de consagração e a oferta de paz.

[[v3-7-38]]

^<<v3-7-38,38>>^ O SENHOR deu essas instruções a Moisés no monte Sinai, quando ordenou que os israelitas apresentassem suas ofertas ao SENHOR no deserto do Sinai.

'''

xref:003-levitico/003-levitico-006.adoc#v3-6-0[&#60; Capítulo Anterior] | <<v3-7-0,Topo>> | xref:003-levitico/003-levitico-008.adoc#v3-8-0[Próximo Capítulo &#62;]