include::./index.adoc[]

[[v3-19-0]]
=== Levítico, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v3-19-1]]

^<<v3-19-1,1>>^ O SENHOR também disse a Moisés:

[[v3-19-2]]

^<<v3-19-2,2>>^ "Dê as seguintes instruções a toda a comunidade de Israel. Sejam santos, pois eu, o SENHOR, seu Deus, sou santo.

[[v3-19-3]]

^<<v3-19-3,3>>^ "Mostrem respeito, cada um de vocês, por sua mãe e por seu pai; guardem também meus sábados. Eu sou o SENHOR, seu Deus.

[[v3-19-4]]

^<<v3-19-4,4>>^ "Não depositem sua confiança em ídolos nem façam para si imagens de metal representando deuses. Eu sou o SENHOR, seu Deus.

[[v3-19-5]]

^<<v3-19-5,5>>^ "Quando sacrificarem uma oferta de paz ao SENHOR, apresentem-na de forma apropriada, para que sejam aceitos.

[[v3-19-6]]

^<<v3-19-6,6>>^ Comam o sacrifício no mesmo dia em que o oferecerem, ou no dia seguinte. O que restar até o terceiro dia será completamente queimado.

[[v3-19-7]]

^<<v3-19-7,7>>^ Se algo do sacrifício for comido no terceiro dia, estará contaminado e não será aceito.

[[v3-19-8]]

^<<v3-19-8,8>>^ Quem o comer no terceiro dia será castigado, pois contaminou aquilo que é santo ao SENHOR, e será eliminado do meio do povo.

[[v3-19-9]]

^<<v3-19-9,9>>^ "Quando fizerem a colheita de sua terra, não colham as espigas nos cantos dos campos nem apanhem aquilo que os ceifeiros deixarem cair.

[[v3-19-10]]

^<<v3-19-10,10>>^ O mesmo se aplica à colheita da uva. Não cortem até o último cacho de cada videira nem apanhem as uvas que caírem no chão. Deixem-nas para os pobres e estrangeiros que vivem entre vocês. Eu sou o SENHOR, seu Deus.

[[v3-19-11]]

^<<v3-19-11,11>>^ "Não roubem. "Não mintam nem enganem uns aos outros.

[[v3-19-12]]

^<<v3-19-12,12>>^ "Não desonrem o nome do seu Deus, usando-o para jurar falsamente. Eu sou o SENHOR.

[[v3-19-13]]

^<<v3-19-13,13>>^ "Não explorem nem roubem o seu próximo. "Não fiquem até o dia seguinte com o pagamento de seus empregados.

[[v3-19-14]]

^<<v3-19-14,14>>^ "Não insultem o surdo nem façam o cego tropeçar. Temam o seu Deus. Eu sou o SENHOR.

[[v3-19-15]]

^<<v3-19-15,15>>^ "Não distorçam a justiça em questões legais, favorecendo os pobres ou tomando partido dos ricos e poderosos. Julguem sempre com imparcialidade.

[[v3-19-16]]

^<<v3-19-16,16>>^ "Não vivam como difamadores no meio do povo. "Não fiquem de braços cruzados quando a vida do seu próximo correr perigo. Eu sou o SENHOR.

[[v3-19-17]]

^<<v3-19-17,17>>^ "Não alimentem ódio no coração contra algum de seus parentes. Confrontem sem rodeios aqueles que errarem, para não serem responsabilizados pelo pecado deles.

[[v3-19-18]]

^<<v3-19-18,18>>^ "Não procurem se vingar nem guardem rancor de alguém do seu povo, mas cada um ame o seu próximo como a si mesmo. Eu sou o SENHOR.

[[v3-19-19]]

^<<v3-19-19,19>>^ "Obedeçam a todos os meus decretos. "Não cruzem dois animais de espécies diferentes. Não plantem em seu campo duas espécies de sementes. Não usem roupas tecidas com dois tipos de pano.

[[v3-19-20]]

^<<v3-19-20,20>>^ "Se um homem tiver relações sexuais com uma escrava cuja liberdade não foi comprada, mas que está prometida para ser mulher de outro, indenizará totalmente o senhor da escrava. Uma vez que ela não é livre, nem o homem nem a mulher serão mortos.

[[v3-19-21]]

^<<v3-19-21,21>>^ O homem levará um carneiro como oferta pela culpa e o apresentará ao SENHOR à entrada da tenda do encontro.

[[v3-19-22]]

^<<v3-19-22,22>>^ O sacerdote fará expiação por ele com o carneiro da oferta pela culpa, e seu pecado será perdoado.

[[v3-19-23]]

^<<v3-19-23,23>>^ "Quando entrarem na terra e plantarem árvores frutíferas de todo tipo, não colham os frutos nos três primeiros anos. Considerem esses frutos proibidos e não os comam.

[[v3-19-24]]

^<<v3-19-24,24>>^ No quarto ano, consagrem toda a colheita ao SENHOR como uma celebração de louvor.

[[v3-19-25]]

^<<v3-19-25,25>>^ Por fim, no quinto ano, vocês poderão comer os frutos. Se procederem desse modo, sua colheita aumentará. Eu sou o SENHOR, seu Deus.

[[v3-19-26]]

^<<v3-19-26,26>>^ "Não comam carne em que ainda houver sangue. "Não pratiquem adivinhação nem feitiçaria.

[[v3-19-27]]

^<<v3-19-27,27>>^ "Não cortem o cabelo dos lados da cabeça nem raspem a barba rente à pele.

[[v3-19-28]]

^<<v3-19-28,28>>^ "Quando lamentarem a morte de alguém, não façam cortes no corpo nem marcas na pele. Eu sou o SENHOR.

[[v3-19-29]]

^<<v3-19-29,29>>^ "Ninguém contamine sua filha tornando-a uma prostituta, pois a terra ficaria cheia de prostituição e perversão.

[[v3-19-30]]

^<<v3-19-30,30>>^ "Guardem meus sábados e tratem meu santuário com reverência. Eu sou o SENHOR.

[[v3-19-31]]

^<<v3-19-31,31>>^ "Não se contaminem procurando médiuns e os que consultam os espíritos dos mortos. Eu sou o SENHOR, seu Deus.

[[v3-19-32]]

^<<v3-19-32,32>>^ "Levantem-se na presença dos idosos e honrem os anciãos. Temam o seu Deus. Eu sou o SENHOR.

[[v3-19-33]]

^<<v3-19-33,33>>^ "Não se aproveitem dos estrangeiros que vivem entre vocês na terra.

[[v3-19-34]]

^<<v3-19-34,34>>^ Tratem-nos como se fossem israelitas de nascimento e amem-nos como a si mesmos. Lembrem-se de que vocês eram estrangeiros quando moravam na terra do Egito. Eu sou o SENHOR, seu Deus.

[[v3-19-35]]

^<<v3-19-35,35>>^ "Não usem medidas desonestas ao medirem comprimento, peso ou volume.

[[v3-19-36]]

^<<v3-19-36,36>>^ Suas balanças e seus pesos devem ser exatos, assim como suas vasilhas para medir produtos secos ou líquidos. Eu sou o SENHOR, seu Deus, que os tirou da terra do Egito.

[[v3-19-37]]

^<<v3-19-37,37>>^ "Obedeçam a todos os meus decretos e a todos os meus estatutos pondo-os em prática. Eu sou o SENHOR".

'''

xref:003-levitico/003-levitico-018.adoc#v3-18-0[&#60; Capítulo Anterior] | <<v3-19-0,Topo>> | xref:003-levitico/003-levitico-020.adoc#v3-20-0[Próximo Capítulo &#62;]