include::./index.adoc[]

[[v3-5-0]]
=== Levítico, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v3-5-1]]

^<<v3-5-1,1>>^ "Se alguém for chamado para testemunhar a respeito de algo que tenha visto ou que seja de seu conhecimento, mas se recusar a fazê-lo, comete pecado e deverá ser castigado por causa de seu pecado.

[[v3-5-2]]

^<<v3-5-2,2>>^ "Se alguém, mesmo sem saber, tocar em algo cerimonialmente impuro, como o cadáver de um animal impuro, seja um animal selvagem, um animal doméstico ou um animal que rasteja pelo chão, quando perceber o que aconteceu, deverá reconhecer sua contaminação e culpa.

[[v3-5-3]]

^<<v3-5-3,3>>^ "Se alguém, mesmo sem saber, tocar em algo que o torne impuro, quando perceber o que aconteceu, deverá reconhecer sua culpa.

[[v3-5-4]]

^<<v3-5-4,4>>^ "Se alguém, mesmo sem saber, fizer um voto impensado de qualquer tipo, para o bem ou para o mal, quando perceber a imprudência do voto, deverá reconhecer sua culpa.

[[v3-5-5]]

^<<v3-5-5,5>>^ "Quando alguém perceber sua culpa, em qualquer um desses casos, deverá confessar seu pecado.

[[v3-5-6]]

^<<v3-5-6,6>>^ Como castigo pelo pecado, trará ao SENHOR uma ovelha ou uma cabra do rebanho. É uma oferta pelo pecado, com a qual o sacerdote fará expiação pelo pecado da pessoa.

[[v3-5-7]]

^<<v3-5-7,7>>^ "Se a pessoa não tiver recursos para oferecer uma ovelha, trará ao SENHOR duas rolinhas ou dois pombinhos como castigo pelo pecado. Uma das aves será para a oferta pelo pecado, e a outra, para o holocausto.

[[v3-5-8]]

^<<v3-5-8,8>>^ Ela as entregará ao sacerdote, que apresentará a primeira ave como oferta pelo pecado. Ele torcerá o pescoço da ave, mas não arrancará a cabeça.

[[v3-5-9]]

^<<v3-5-9,9>>^ Em seguida, aspergirá os lados do altar com um pouco do sangue da oferta pelo pecado e deixará o sangue restante escorrer para a base do altar. É uma oferta pelo pecado.

[[v3-5-10]]

^<<v3-5-10,10>>^ Depois disso, o sacerdote preparará a segunda ave como holocausto, de acordo com a forma prescrita. Desse modo, o sacerdote fará expiação pelo pecado da pessoa, e ela será perdoada.

[[v3-5-11]]

^<<v3-5-11,11>>^ "Se a pessoa não tiver condições de oferecer sequer duas rolinhas ou dois pombinhos, trará dois litros de farinha da melhor qualidade como oferta pelo pecado. Uma vez que é uma oferta pelo pecado, não misturará azeite com a farinha nem acrescentará incenso.

[[v3-5-12]]

^<<v3-5-12,12>>^ Trará a farinha ao sacerdote, que pegará um punhado como porção memorial e queimará a porção no altar, sobre as ofertas especiais apresentadas ao SENHOR. É uma oferta pelo pecado.

[[v3-5-13]]

^<<v3-5-13,13>>^ Desse modo, o sacerdote fará expiação por aqueles que forem culpados de algum desses pecados, e eles serão perdoados. O restante da farinha será do sacerdote, como se faz com a oferta de cereal". Procedimentos para a oferta pela culpa

[[v3-5-14]]

^<<v3-5-14,14>>^ O SENHOR disse a Moisés:

[[v3-5-15]]

^<<v3-5-15,15>>^ "Se alguém cometer um delito religioso, violando, mesmo sem intenção, algum mandamento sobre as coisas consagradas do SENHOR, deverá trazer ao SENHOR uma oferta pela culpa. A oferta será um carneiro sem defeito do seu próprio rebanho, calculado em prata de acordo com o siclo do santuário.

[[v3-5-16]]

^<<v3-5-16,16>>^ A pessoa pagará uma indenização referente ao delito religioso que cometeu, com um acréscimo de um quinto do valor. Quando entregar o pagamento ao sacerdote, ele fará expiação pela pessoa com o carneiro sacrificado como oferta pela culpa, e ela será perdoada.

[[v3-5-17]]

^<<v3-5-17,17>>^ "Se alguém pecar, quebrando algum dos mandamentos do SENHOR, mesmo que não tenha consciência do que fez, é culpado e será castigado por causa de seu pecado.

[[v3-5-18]]

^<<v3-5-18,18>>^ Como oferta pela culpa, trará ao sacerdote um carneiro sem defeito do próprio rebanho, devidamente avaliado. Desse modo, o sacerdote fará expiação pelo pecado não intencional que a pessoa cometeu, e ela será perdoada.

[[v3-5-19]]

^<<v3-5-19,19>>^ Essa é uma oferta pela culpa, pois a pessoa certamente se tornou culpada diante do SENHOR".

'''

xref:003-levitico/003-levitico-004.adoc#v3-4-0[&#60; Capítulo Anterior] | <<v3-5-0,Topo>> | xref:003-levitico/003-levitico-006.adoc#v3-6-0[Próximo Capítulo &#62;]