include::./index.adoc[]

[[v28-9-0]]
=== Oséias, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v28-9-1]]

^<<v28-9-1,1>>^ Ó povo de Israel, não se alegre como as outras nações. Pois vocês foram infiéis a seu Deus e se venderam como prostituta ao adorar outros deuses em toda eira de cereal.

[[v28-9-2]]

^<<v28-9-2,2>>^ Agora, suas colheitas não bastarão para alimentá-los; não haverá uvas para fazer vinho novo.

[[v28-9-3]]

^<<v28-9-3,3>>^ Vocês não permanecerão na terra do SENHOR; em vez disso, voltarão para o Egito e, na Assíria, comerão alimentos impuros.

[[v28-9-4]]

^<<v28-9-4,4>>^ Ali não apresentarão ofertas de vinho ao SENHOR; seus sacrifícios não o agradarão. Serão impuros, como o alimento tocado por uma pessoa de luto; todos que apresentarem esses sacrifícios se contaminarão. Eles próprios comerão o alimento, mas não poderão oferecê-lo ao SENHOR.

[[v28-9-5]]

^<<v28-9-5,5>>^ O que oferecerão nos feriados sagrados? Como celebrarão as festas do SENHOR?

[[v28-9-6]]

^<<v28-9-6,6>>^ Mesmo que escapem da destruição nas mãos da Assíria, o Egito os conquistará, e Mênfis os sepultará. A urtiga cobrirá seus tesouros de prata, e espinhos invadirão as ruínas de suas casas.

[[v28-9-7]]

^<<v28-9-7,7>>^ Chegou o tempo do castigo de Israel, o dia do acerto de contas; sim, Israel se dará conta disso. Por causa de seu grande pecado e sua hostilidade, vocês dizem: "Os profetas enlouqueceram, e os homens inspirados não passam de tolos!".

[[v28-9-8]]

^<<v28-9-8,8>>^ O profeta é um vigia sobre Israel para meu Deus, mas, por onde vai, encontra armadilhas; até no templo de Deus enfrenta hostilidade.

[[v28-9-9]]

^<<v28-9-9,9>>^ Meu povo faz coisas depravadas como em Gibeá, muito tempo atrás. Deus não esquecerá; certamente os castigará por seus pecados.

[[v28-9-10]]

^<<v28-9-10,10>>^ "Quando encontrei você, Israel, foi como encontrar uvas no deserto. Quando vi seus antepassados, foi como ver os primeiros figos maduros. Mas eles me abandonaram por causa de Baal-Peor e se entregaram à vergonhosa idolatria. Logo se tornaram tão repugnantes quanto o ídolo que adoravam.

[[v28-9-11]]

^<<v28-9-11,11>>^ A glória de Israel fugirá como uma ave, pois não lhes nascerão filhos; não crescerão no ventre, nem sequer serão concebidos.

[[v28-9-12]]

^<<v28-9-12,12>>^ Ainda que alguns de seus filhos cheguem a crescer, eu os tomarei de vocês. Será um dia terrível quando eu me afastar e os deixar sozinhos.

[[v28-9-13]]

^<<v28-9-13,13>>^ Vi Israel se tornar bela como Tiro; agora, porém, entregará seus filhos para o massacre."

[[v28-9-14]]

^<<v28-9-14,14>>^ Ó SENHOR, o que devo pedir para teu povo? Pedirei ventres que não deem à luz e seios que não deem leite.

[[v28-9-15]]

^<<v28-9-15,15>>^ "Toda a perversidade deles começou em Gilgal; ali comecei a odiá-los. Eu os expulsarei de minha terra por causa de suas maldades. Não os amarei mais, porque todos os seus líderes são rebeldes.

[[v28-9-16]]

^<<v28-9-16,16>>^ O povo de Israel está ferido; suas raízes secaram, e eles não darão mais frutos. E, se derem à luz, eu matarei seus filhos queridos."

[[v28-9-17]]

^<<v28-9-17,17>>^ Meu Deus rejeitará os israelitas, pois não lhe obedecem. Andarão sem rumo, errantes entre as nações.

'''

xref:028-oseias/028-oseias-008.adoc#v28-8-0[&#60; Capítulo Anterior] | <<v28-9-0,Topo>> | xref:028-oseias/028-oseias-010.adoc#v28-10-0[Próximo Capítulo &#62;]