include::./index.adoc[]

[[v28-4-0]]
=== Oséias, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v28-4-1]]

^<<v28-4-1,1>>^ Ó israelitas, ouçam a palavra do SENHOR! O SENHOR apresentou acusações contra vocês: "Não há fidelidade, nem bondade, nem conhecimento de Deus em sua terra.

[[v28-4-2]]

^<<v28-4-2,2>>^ Vocês fazem votos e não os cumprem; matam, roubam e cometem adultério. Há violência em toda parte, um homicídio atrás do outro.

[[v28-4-3]]

^<<v28-4-3,3>>^ Por isso sua terra está de luto, e todos desfalecem. Até os animais selvagens, as aves do céu e os peixes do mar estão desaparecendo.

[[v28-4-4]]

^<<v28-4-4,4>>^ "Não apontem o dedo para outra pessoa, não tentem escapar da culpa! Minha queixa é contra vocês, sacerdotes!

[[v28-4-5]]

^<<v28-4-5,5>>^ Vocês tropeçarão em plena luz do dia, e seus profetas cairão com vocês durante a noite; e eu destruirei Israel, sua mãe.

[[v28-4-6]]

^<<v28-4-6,6>>^ Meu povo está sendo destruído porque não me conhece. Porque vocês, sacerdotes, não querem me conhecer, eu não os reconhecerei como meus sacerdotes. Porque se esqueceram da lei de seu Deus, eu me esquecerei de seus filhos.

[[v28-4-7]]

^<<v28-4-7,7>>^ Quanto maior o número de sacerdotes, mais eles pecam contra mim. Trocaram a glória de Deus pela vergonha de ídolos.

[[v28-4-8]]

^<<v28-4-8,8>>^ "Quando o povo traz suas ofertas pelo pecado, os sacerdotes se alimentam. Por isso, eles se alegram quando o povo peca!

[[v28-4-9]]

^<<v28-4-9,9>>^ E, assim como são os sacerdotes, assim é o povo. Por isso, a ambos castigarei por seus atos perversos.

[[v28-4-10]]

^<<v28-4-10,10>>^ Eles comerão, mas ainda sentirão fome; eles se prostituirão, mas nada receberão, pois abandonaram o Senhor

[[v28-4-11]]

^<<v28-4-11,11>>^ para cometer adultério com outros deuses. "O vinho tirou o entendimento de meu povo.

[[v28-4-12]]

^<<v28-4-12,12>>^ Pedem conselho a pedaços de madeira, pensam que uma vara lhes dirá o futuro. Seu desejo de ir atrás de ídolos os tornou insensatos. Prostituíram-se cometendo adultério com outros deuses e abandonando seu Deus.

[[v28-4-13]]

^<<v28-4-13,13>>^ Oferecem sacrifícios a ídolos no alto dos montes; sobem as colinas para queimar incenso à sombra agradável de carvalhos, álamos e terebintos. "Por isso suas filhas se voltam para a prostituição, e suas noras cometem adultério.

[[v28-4-14]]

^<<v28-4-14,14>>^ Mas por que eu as castigaria por sua prostituição e adultério? Pois seus homens fazem a mesma coisa, pecando com prostitutas de rua e dos santuários. Ó povo sem entendimento, você segue rumo à destruição!

[[v28-4-15]]

^<<v28-4-15,15>>^ "Embora você, Israel, se prostitua, que Judá não seja culpado dessas coisas. Não participe da falsa adoração em Gilgal nem em Bete-Áven, não faça juramentos ali em nome do SENHOR.

[[v28-4-16]]

^<<v28-4-16,16>>^ A nação de Israel é rebelde como uma bezerra teimosa. Acaso o SENHOR deve alimentá-la como um cordeiro em pastos verdes?

[[v28-4-17]]

^<<v28-4-17,17>>^ Deixe Israel de lado, pois se apegou à idolatria.

[[v28-4-18]]

^<<v28-4-18,18>>^ Quando os governantes de Israel terminam de beber, saem à procura de prostitutas; amam a vergonha mais que a honra.

[[v28-4-19]]

^<<v28-4-19,19>>^ Por isso, um forte vento os levará para longe; seus sacrifícios idólatras os envergonharão."

'''

xref:028-oseias/028-oseias-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-oseias/028-oseias-005.adoc#v28-5-0[Próximo Capítulo &#62;]