include::./index.adoc[]

[[v28-10-0]]
=== Oséias, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v28-10-1]]

^<<v28-10-1,1>>^ Como Israel é próspero! É uma videira viçosa cheia de frutos. Mas, quanto mais seu povo enriquece, mais altares idólatras constrói. Quanto mais fartas suas colheitas, mais belas suas colunas sagradas.

[[v28-10-2]]

^<<v28-10-2,2>>^ O coração dos israelitas é inconstante; são culpados e devem ser castigados. O SENHOR derrubará seus altares e despedaçará suas colunas.

[[v28-10-3]]

^<<v28-10-3,3>>^ Então eles dirão: "Não temos rei, pois não tememos o SENHOR. Mas, ainda que tivéssemos rei, o que ele poderia fazer por nós?".

[[v28-10-4]]

^<<v28-10-4,4>>^ Proferem palavras vazias e fazem alianças que não pretendem cumprir. Por isso disputas legais brotam em seu meio, como ervas daninhas num campo arado.

[[v28-10-5]]

^<<v28-10-5,5>>^ Os habitantes de Samaria tremem de medo por causa do bezerro em Bete-Áven, e por ele lamentam. Embora seus sacerdotes idólatras se alegrem com o bezerro, será removida a glória de seu ídolo.

[[v28-10-6]]

^<<v28-10-6,6>>^ Será levado para a Assíria, como presente para o grande rei de lá. Efraim será humilhado, e Israel, envergonhado, porque seu povo confiou nesse ídolo.

[[v28-10-7]]

^<<v28-10-7,7>>^ Samaria e seu rei serão cortados fora e ficarão à deriva, como um pedaço de madeira lançado no mar.

[[v28-10-8]]

^<<v28-10-8,8>>^ Os santuários idólatras em Áven, onde Israel pecou, serão destruídos; espinhos e mato crescerão ao redor de seus altares. O povo suplicará aos montes: "Soterrem-nos!" e pedirá às colinas: "Caiam sobre nós!".

[[v28-10-9]]

^<<v28-10-9,9>>^ "Ó Israel, desde o tempo de Gibeá, só houve pecado e mais pecado! Não foi com razão que os perversos de Gibeá foram atacados?

[[v28-10-10]]

^<<v28-10-10,10>>^ Agora, quando me parecer melhor, eu também os atacarei. Convocarei os exércitos das nações para castigá-los por seus muitos pecados.

[[v28-10-11]]

^<<v28-10-11,11>>^ "Israel é como bezerra treinada que pisa o trigo, um trabalho fácil, que ela gosta de fazer. Mas eu colocarei um jugo opressor sobre seu pescoço delicado; obrigarei Judá a arar e farei Israel lavrar o solo endurecido.

[[v28-10-12]]

^<<v28-10-12,12>>^ Eu disse: ‘Plantem boas sementes de justiça e terão uma colheita de amor. Arem o solo endurecido de seu coração, pois é hora de buscar o SENHOR, para que ele venha e faça chover justiça sobre vocês’.

[[v28-10-13]]

^<<v28-10-13,13>>^ "Mas vocês cultivaram a maldade e juntaram uma farta colheita de pecados. Comeram o fruto das mentiras ao confiar em carros de guerra. e em seus grandes exércitos.

[[v28-10-14]]

^<<v28-10-14,14>>^ Agora os horrores da guerra surgirão no meio de seu povo. Todas as suas fortalezas cairão, como quando Salmã destruiu Bete-Arbel. Até mães e crianças foram despedaçadas ali.

[[v28-10-15]]

^<<v28-10-15,15>>^ O mesmo lhe acontecerá, Betel, por causa de sua grande maldade. Quando amanhecer o dia do juízo, o rei de Israel será totalmente destruído."

'''

xref:028-oseias/028-oseias-009.adoc#v28-9-0[&#60; Capítulo Anterior] | <<v28-10-0,Topo>> | xref:028-oseias/028-oseias-011.adoc#v28-11-0[Próximo Capítulo &#62;]