include::./index.adoc[]

[[v28-2-0]]
=== Oséias, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v28-2-1]]

^<<v28-2-1,1>>^ "Nesse dia, vocês chamarão seus irmãos de Ami, ‘Meu Povo’, e chamarão suas irmãs de Ruama, ‘Minhas Amadas’."

[[v28-2-2]]

^<<v28-2-2,2>>^ "Apresentem acusações contra sua mãe, pois ela já não é minha esposa, e eu já não sou seu marido. Digam-lhe que remova do rosto a maquiagem de prostituta e que tire as roupas que deixam os seios à mostra.

[[v28-2-3]]

^<<v28-2-3,3>>^ Do contrário, eu a deixarei nua, como no dia em que nasceu. Permitirei que morra de sede, como numa terra seca e desolada.

[[v28-2-4]]

^<<v28-2-4,4>>^ E não amarei seus filhos, pois foram concebidos em prostituição.

[[v28-2-5]]

^<<v28-2-5,5>>^ Sua mãe é uma prostituta indecente que engravidou de forma vergonhosa. Disse: ‘Irei atrás de outros amantes e me venderei a eles em troca de comida e água, em troca de roupas de lã e de linho, em troca de azeite e bebidas’.

[[v28-2-6]]

^<<v28-2-6,6>>^ "Por isso a cercarei com espinheiros; levantarei um muro à frente dela para fazê-la se perder em seu caminho.

[[v28-2-7]]

^<<v28-2-7,7>>^ Quando correr atrás de seus amantes, não os alcançará. Procurará por eles, mas não os encontrará. Então pensará: ‘Voltarei para meu marido, pois com ele estava melhor que agora’.

[[v28-2-8]]

^<<v28-2-8,8>>^ Ela não entende que tudo que tem foi dado por mim: o trigo, o vinho novo, o azeite. Dei-lhe até mesmo prata e ouro, mas ela ofereceu meus presentes a Baal.

[[v28-2-9]]

^<<v28-2-9,9>>^ "Agora, porém, tomarei de volta o trigo e o vinho que lhe providenciei a cada colheita. Tomarei as roupas de lã e de linho que lhe dei para cobrir sua nudez.

[[v28-2-10]]

^<<v28-2-10,10>>^ Eu a deixarei nua em público, à vista de todos os seus amantes. Ninguém será capaz de livrá-la de minhas mãos.

[[v28-2-11]]

^<<v28-2-11,11>>^ Acabarei com suas celebrações, com suas festas de lua nova e seus sábados, com todos os seus feriados.

[[v28-2-12]]

^<<v28-2-12,12>>^ Destruirei suas videiras e figueiras, que ela diz ter recebido de seus amantes. Farei que se tornem densos matagais, onde animais selvagens comerão os frutos.

[[v28-2-13]]

^<<v28-2-13,13>>^ Eu a castigarei por todas as vezes que queimou incenso a suas imagens de Baal, que colocou brincos e joias e saiu atrás de seus amantes, mas se esqueceu de mim", diz o SENHOR.

[[v28-2-14]]

^<<v28-2-14,14>>^ "Contudo, eu a conquistarei de volta; ao deserto a levarei e lhe falarei com carinho.

[[v28-2-15]]

^<<v28-2-15,15>>^ Devolverei suas videiras e transformarei o vale de Acor numa porta de esperança. Ela se entregará a mim, como fez há muito tempo, quando era jovem, quando eu a libertei da escravidão no Egito.

[[v28-2-16]]

^<<v28-2-16,16>>^ Nesse dia", diz o SENHOR, "você me chamará de ‘meu marido’, e não de ‘meu senhor’.

[[v28-2-17]]

^<<v28-2-17,17>>^ Limparei de seus lábios os nomes de Baal, e você nunca mais os pronunciará.

[[v28-2-18]]

^<<v28-2-18,18>>^ Nesse dia, farei uma aliança com todos os animais selvagens, com as aves do céu e com todos os animais que rastejam pelo chão, para que não lhe façam mal. Removerei da terra todas as armas de guerra, as espadas e os arcos, para que você viva em paz e segurança.

[[v28-2-19]]

^<<v28-2-19,19>>^ Eu me casarei com você para sempre, e lhe mostrarei retidão e justiça, amor e compaixão.

[[v28-2-20]]

^<<v28-2-20,20>>^ Serei fiel a você e a tornarei minha, e você conhecerá a mim, o SENHOR.

[[v28-2-21]]

^<<v28-2-21,21>>^ "Naquele dia, eu responderei", diz o SENHOR. "Responderei aos céus, e os céus responderão à terra.

[[v28-2-22]]

^<<v28-2-22,22>>^ A terra responderá aos clamores do trigo, das videiras e das oliveiras. E eles, por sua vez, responderão: ‘Deus semeia!’.

[[v28-2-23]]

^<<v28-2-23,23>>^ Então semearei uma safra de israelitas e os farei crescer para mim mesmo. Mostrarei amor por aquela que chamei ‘Não Amada’. E àqueles que chamei ‘Não Meu Povo’, direi: ‘Agora vocês são meu povo’. E eles responderão: ‘Tu és nosso Deus!’".

'''

xref:028-oseias/028-oseias-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-oseias/028-oseias-003.adoc#v28-3-0[Próximo Capítulo &#62;]