include::./index.adoc[]

[[v28-12-0]]
=== Oséias, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v28-12-1]]

^<<v28-12-1,1>>^ O povo de Israel se alimenta de vento; corre atrás do vento leste o dia todo. Acumula mentiras e violência, faz acordos com a Assíria e, ao mesmo tempo, envia azeite para comprar o apoio do Egito.

[[v28-12-2]]

^<<v28-12-2,2>>^ Agora o SENHOR apresenta acusações contra Judá; está prestes a castigar Jacó por sua conduta enganosa, e lhe retribuir por tudo que fez.

[[v28-12-3]]

^<<v28-12-3,3>>^ Ainda no ventre, Jacó agarrou o calcanhar de seu irmão; quando se tornou homem, lutou com Deus.

[[v28-12-4]]

^<<v28-12-4,4>>^ Sim, lutou com o anjo e venceu; chorou e suplicou-lhe que o abençoasse. Ali em Betel, encontrou Deus, e Deus falou com ele.

[[v28-12-5]]

^<<v28-12-5,5>>^ O SENHOR Deus dos Exércitos, o SENHOR é seu nome!

[[v28-12-6]]

^<<v28-12-6,6>>^ Portanto, voltem para seu Deus; pratiquem o amor e a justiça e confiem sempre nele.

[[v28-12-7]]

^<<v28-12-7,7>>^ O povo, no entanto, se comporta como comerciantes astutos, que usam balanças desonestas e gostam de explorar.

[[v28-12-8]]

^<<v28-12-8,8>>^ Israel diz: "Fiquei rico! Fiz fortuna com meu próprio esforço! Ninguém descobriu que enganei outros; meu histórico é impecável!".

[[v28-12-9]]

^<<v28-12-9,9>>^ "Mas eu sou o SENHOR, seu Deus, que os tirou do Egito. Eu os farei morar em tendas outra vez, como fazem em feriados sagrados.

[[v28-12-10]]

^<<v28-12-10,10>>^ Enviei meus profetas para adverti-los com muitas visões e parábolas."

[[v28-12-11]]

^<<v28-12-11,11>>^ Mas os habitantes de Gileade não valem nada, por causa de seu pecado. Em Gilgal também sacrificam bois; seus altares são enfileirados como montes de pedras à beira de um campo arado.

[[v28-12-12]]

^<<v28-12-12,12>>^ Jacó fugiu para a terra de Arã e ali cuidou de ovelhas para obter uma esposa.

[[v28-12-13]]

^<<v28-12-13,13>>^ Então, por meio de um profeta, o SENHOR tirou do Egito os descendentes de Jacó; e, por meio de um profeta, eles foram protegidos.

[[v28-12-14]]

^<<v28-12-14,14>>^ Mas o povo de Israel provocou o Senhor amargamente. Agora ele os sentenciará à morte como pagamento por seus pecados.

'''

xref:028-oseias/028-oseias-011.adoc#v28-11-0[&#60; Capítulo Anterior] | <<v28-12-0,Topo>> | xref:028-oseias/028-oseias-013.adoc#v28-13-0[Próximo Capítulo &#62;]