include::./index.adoc[]

[[v28-7-0]]
=== Oséias, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v28-7-1]]

^<<v28-7-1,1>>^ "Desejo curar Israel, mas seus pecados são grandes demais; Samaria está cheia de mentirosos. Há ladrões do lado de dentro e bandidos do lado de fora.

[[v28-7-2]]

^<<v28-7-2,2>>^ Seu povo não percebe que eu o observo. Está cercado por seus atos pecaminosos, e eu vejo todos eles.

[[v28-7-3]]

^<<v28-7-3,3>>^ "Com suas maldades, divertem o rei, e os príncipes riem de suas mentiras.

[[v28-7-4]]

^<<v28-7-4,4>>^ São todos adúlteros, sempre ardendo de paixão. São como o forno mantido quente, enquanto o padeiro bate a massa.

[[v28-7-5]]

^<<v28-7-5,5>>^ No dia da festa do rei, os príncipes se embebedam com vinho e dão as mãos aos zombadores.

[[v28-7-6]]

^<<v28-7-6,6>>^ Seu coração é como um forno que arde com intriga. Sua trama queima a noite toda e, pela manhã, irrompe em chamas abrasadoras.

[[v28-7-7]]

^<<v28-7-7,7>>^ Como um forno ardente, consomem seus líderes. Matam seus reis, um após o outro, e ninguém clama a mim por socorro.

[[v28-7-8]]

^<<v28-7-8,8>>^ "O povo de Israel se mistura com outros povos e se torna imprestável como um bolo mal assado.

[[v28-7-9]]

^<<v28-7-9,9>>^ Estrangeiros consomem suas forças, mas eles não sabem disso. Seus cabelos ficam brancos, mas eles não se dão conta.

[[v28-7-10]]

^<<v28-7-10,10>>^ Sua arrogância testemunha contra eles, e, no entanto, não se voltam para o SENHOR, seu Deus, nem buscam encontrá-lo.

[[v28-7-11]]

^<<v28-7-11,11>>^ "O povo de Israel se tornou como pombas tolas e sem juízo, que primeiro chamam o Egito e depois voam até a Assíria para pedir socorro.

[[v28-7-12]]

^<<v28-7-12,12>>^ Enquanto voam de um lado para o outro, lançarei sobre eles minha rede e os derrubarei como uma ave do céu; eu os castigarei por todo o mal que fizeram.

[[v28-7-13]]

^<<v28-7-13,13>>^ "Que aflição espera os que me abandonaram! Que morram, pois se rebelaram contra mim. Eu desejava resgatá-los, mas contaram mentiras a meu respeito.

[[v28-7-14]]

^<<v28-7-14,14>>^ Não clamam a mim de coração sincero; em vez disso, gemem angustiados em suas camas. Cortam-se ritualmente e suplicam por trigo e vinho novo, mas de mim se afastam.

[[v28-7-15]]

^<<v28-7-15,15>>^ Eu os instruí e os fortaleci, mas agora tramam o mal contra mim.

[[v28-7-16]]

^<<v28-7-16,16>>^ Olham para toda parte, menos para o Altíssimo; são inúteis, como um arco defeituoso. Seus líderes serão mortos por seus inimigos, por causa de sua insolência contra mim. Então o povo do Egito rirá deles."

'''

xref:028-oseias/028-oseias-006.adoc#v28-6-0[&#60; Capítulo Anterior] | <<v28-7-0,Topo>> | xref:028-oseias/028-oseias-008.adoc#v28-8-0[Próximo Capítulo &#62;]