include::./index.adoc[]

[[v28-13-0]]
=== Oséias, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v28-13-1]]

^<<v28-13-1,1>>^ Quando a tribo de Efraim falava, o povo tremia de medo, pois essa tribo era importante em Israel. Mas pecaram ao adorar Baal e, com isso, selaram sua destruição.

[[v28-13-2]]

^<<v28-13-2,2>>^ Agora, continuam a pecar ao fazer ídolos de prata, imagens modeladas por mãos humanas. "Ofereçam-lhes sacrifícios!", eles dizem. "Beijem os ídolos em forma de bezerro!"

[[v28-13-3]]

^<<v28-13-3,3>>^ Por isso, desaparecerão como a neblina da manhã, como o orvalho à luz do sol, como a palha soprada pelo vento, como a fumaça que sai pela chaminé.

[[v28-13-4]]

^<<v28-13-4,4>>^ "Eu sou o SENHOR, seu Deus, que os tirou do Egito. Vocês não reconhecerão outro Deus além de mim, pois não existe outro salvador.

[[v28-13-5]]

^<<v28-13-5,5>>^ Cuidei de vocês no deserto, naquela terra seca e sedenta.

[[v28-13-6]]

^<<v28-13-6,6>>^ Mas depois que comeram e se saciaram, ficaram orgulhosos e se esqueceram de mim.

[[v28-13-7]]

^<<v28-13-7,7>>^ Agora, eu os atacarei como um leão, como um leopardo à espreita no caminho.

[[v28-13-8]]

^<<v28-13-8,8>>^ Como uma ursa da qual roubaram os filhotes, arrancarei seu coração. Como uma leoa faminta os devorarei, e como um animal selvagem os despedaçarei.

[[v28-13-9]]

^<<v28-13-9,9>>^ "Ó Israel, você está prestes a ser destruído por mim, seu único ajudador.

[[v28-13-10]]

^<<v28-13-10,10>>^ Agora, onde está seu rei? Que ele salve suas cidades! Onde estão os líderes da terra, os reis e os príncipes que vocês exigiram de mim?

[[v28-13-11]]

^<<v28-13-11,11>>^ Em minha ira, eu lhes dei reis e, em minha fúria, os tirei.

[[v28-13-12]]

^<<v28-13-12,12>>^ "A culpa de Efraim foi acumulada, e seu pecado, armazenado para o castigo.

[[v28-13-13]]

^<<v28-13-13,13>>^ O povo sentiu dores, como as dores do parto, mas é insensato como uma criança que não quer nascer. A hora do nascimento chegou, mas ele fica no ventre.

[[v28-13-14]]

^<<v28-13-14,14>>^ "Devo resgatá-los da sepultura? Devo redimi-los da morte? Ó morte, traga seus horrores! Ó sepultura, traga suas pragas! Pois não terei compaixão deles.

[[v28-13-15]]

^<<v28-13-15,15>>^ Efraim é o mais próspero de seus irmãos, mas um vento leste, uma rajada do SENHOR, se levantará no deserto. Suas fontes se esgotarão, e seus poços secarão. Todas as suas riquezas serão saqueadas e levadas embora.

[[v28-13-16]]

^<<v28-13-16,16>>^ O povo de Samaria sofrerá as consequências de sua culpa, pois se rebelou contra seu Deus. Serão mortos pela espada inimiga; suas crianças serão despedaçadas, e suas mulheres grávidas, abertas ao meio."

'''

xref:028-oseias/028-oseias-012.adoc#v28-12-0[&#60; Capítulo Anterior] | <<v28-13-0,Topo>> | xref:028-oseias/028-oseias-014.adoc#v28-14-0[Próximo Capítulo &#62;]