include::./index.adoc[]

[[v28-6-0]]
=== Oséias, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v28-6-1]]

^<<v28-6-1,1>>^ "Venham, voltemos para o SENHOR! Ele nos despedaçou, agora irá nos sarar. Ele nos feriu, agora nos fará curativos.

[[v28-6-2]]

^<<v28-6-2,2>>^ Em pouco tempo nos restaurará, e logo viveremos em sua presença.

[[v28-6-3]]

^<<v28-6-3,3>>^ Ah, como precisamos conhecer o SENHOR; busquemos conhecê-lo! Ele nos responderá, tão certo como chega o amanhecer ou vêm as chuvas da primavera."

[[v28-6-4]]

^<<v28-6-4,4>>^ "Ó Israel e Judá, que farei com vocês? Seu amor se dissipa como a neblina da manhã e desaparece como o orvalho à luz do sol.

[[v28-6-5]]

^<<v28-6-5,5>>^ Enviei meus profetas para despedaçar vocês, para matá-los com minhas palavras, com julgamentos inescapáveis como a luz.

[[v28-6-6]]

^<<v28-6-6,6>>^ Quero que demonstrem amor, e não que ofereçam sacrifícios. Quero que me conheçam, mais do que desejo holocaustos.

[[v28-6-7]]

^<<v28-6-7,7>>^ Como Adão, porém, vocês quebraram minha aliança e traíram minha confiança.

[[v28-6-8]]

^<<v28-6-8,8>>^ "Gileade é uma cidade de pecadores, cheia de marcas de sangue.

[[v28-6-9]]

^<<v28-6-9,9>>^ Sacerdotes são como bandos de assaltantes, de tocaia à espera de suas vítimas. Assassinam viajantes ao longo da estrada para Siquém e praticam todo tipo de perversidade.

[[v28-6-10]]

^<<v28-6-10,10>>^ Sim, vi algo horrível em Efraim e em Israel: meu povo se contaminou prostituindo-se com outros deuses!

[[v28-6-11]]

^<<v28-6-11,11>>^ "Ó Judá, uma colheita de castigo também espera por você, embora eu quisesse restaurar a situação de meu povo."

'''

xref:028-oseias/028-oseias-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-oseias/028-oseias-007.adoc#v28-7-0[Próximo Capítulo &#62;]