include::./index.adoc[]

[[v28-5-0]]
=== Oséias, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v28-5-1]]

^<<v28-5-1,1>>^ "Ouçam isto, sacerdotes! Prestem atenção, líderes de Israel! Escutem, membros da família real; foi pronunciada a sentença contra vocês, pois conduziram meu povo a uma armadilha, em Mispá e em Tabor.

[[v28-5-2]]

^<<v28-5-2,2>>^ Os rebeldes promoveram grande matança, mas eu os castigarei pelo que fizeram.

[[v28-5-3]]

^<<v28-5-3,3>>^ Conheço você, Efraim; não pode se esconder de mim, Israel. Você me abandonou e se prostituiu; está inteiramente contaminado.

[[v28-5-4]]

^<<v28-5-4,4>>^ Suas ações não lhe permitem voltar para seu Deus; a prostituição domina seu coração, e você não conhece o SENHOR.

[[v28-5-5]]

^<<v28-5-5,5>>^ "A arrogância de Israel dá testemunho contra ele; Israel e Efraim tropeçarão sob o peso da culpa, e Judá também cairá com eles.

[[v28-5-6]]

^<<v28-5-6,6>>^ Quando vierem com seus rebanhos e gado para oferecer sacrifícios ao SENHOR, não o encontrarão, pois ele se afastou deles.

[[v28-5-7]]

^<<v28-5-7,7>>^ Traíram a honra do Senhor ao gerar filhos que não lhe pertencem. Agora, por ocasião da lua nova, serão devorados, juntamente com sua riqueza.

[[v28-5-8]]

^<<v28-5-8,8>>^ "Soem o alarme em Gibeá! Toquem a trombeta em Ramá! Deem o grito de guerra em Bete-Áven! Entrem na batalha, guerreiros de Benjamim!

[[v28-5-9]]

^<<v28-5-9,9>>^ Uma coisa é certa, Israel: no dia de seu castigo, você se tornará um monte de ruínas.

[[v28-5-10]]

^<<v28-5-10,10>>^ "Os líderes de Judá são trapaceiros e ladrões, por isso derramarei minha ira sobre eles como água.

[[v28-5-11]]

^<<v28-5-11,11>>^ O povo de Israel será esmagado e quebrado por meu juízo, pois está decidido a adorar ídolos.

[[v28-5-12]]

^<<v28-5-12,12>>^ Destruirei Israel como a traça acaba com a lã, tornarei Judá tão fraca quanto madeira podre.

[[v28-5-13]]

^<<v28-5-13,13>>^ "Quando Israel e Judá viram como estavam doentes, Israel se voltou para a Assíria, para seu grande rei, mas ele não foi capaz de curá-lo.

[[v28-5-14]]

^<<v28-5-14,14>>^ Pois serei como um leão para Israel, como um leão novo e forte para Judá, e os despedaçarei. Eu os levarei embora, e não sobrará ninguém para resgatá-los.

[[v28-5-15]]

^<<v28-5-15,15>>^ Então retornarei a meu lugar, até que reconheçam sua culpa e voltem para mim. Pois, assim que vier o sofrimento, eles me buscarão ansiosamente."

'''

xref:028-oseias/028-oseias-004.adoc#v28-4-0[&#60; Capítulo Anterior] | <<v28-5-0,Topo>> | xref:028-oseias/028-oseias-006.adoc#v28-6-0[Próximo Capítulo &#62;]