include::./index.adoc[]

[[v28-3-0]]
=== Oséias, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v28-3-1]]

^<<v28-3-1,1>>^ Então o SENHOR me disse: "Vá e ame sua esposa outra vez, embora ela cometa adultério com um amante. Isso mostrará que o SENHOR ainda ama Israel, ainda que o povo tenha se voltado para outros deuses e sinta prazer em lhes trazer ofertas".

[[v28-3-2]]

^<<v28-3-2,2>>^ Assim, eu a comprei de volta por quinze peças de prata, um barril grande de cevada e um odre de vinho.

[[v28-3-3]]

^<<v28-3-3,3>>^ Então eu lhe disse: "Você viverá em minha casa por muitos dias e deixará de se prostituir. Durante esse tempo, não terá relações sexuais com ninguém, e eu também esperarei por você".

[[v28-3-4]]

^<<v28-3-4,4>>^ Isso mostra que Israel ficará um longo tempo sem rei nem príncipe, sem sacrifícios nem colunas sagradas, sem sacerdotes nem ídolos.

[[v28-3-5]]

^<<v28-3-5,5>>^ Depois disso, porém, o povo retornará e buscará o SENHOR, seu Deus, e o descendente de Davi, seu rei. Naquele tempo, tremerão em reverência ao SENHOR e à sua bondade.

'''

xref:028-oseias/028-oseias-002.adoc#v28-2-0[&#60; Capítulo Anterior] | <<v28-3-0,Topo>> | xref:028-oseias/028-oseias-004.adoc#v28-4-0[Próximo Capítulo &#62;]