include::./index.adoc[]

[[v28-11-0]]
=== Oséias, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v28-11-1]]

^<<v28-11-1,1>>^ "Quando Israel era menino, eu o amei, e do Egito chamei meu filho.

[[v28-11-2]]

^<<v28-11-2,2>>^ Mas, quanto mais o chamava, mais ele se afastava de mim; oferecia sacrifícios às imagens de Baal e queimava incenso aos ídolos.

[[v28-11-3]]

^<<v28-11-3,3>>^ Ensinei Israel a andar, conduzindo-o pela mão. Mas ele não se deu conta de que era eu quem dele cuidava.

[[v28-11-4]]

^<<v28-11-4,4>>^ Guiei Israel com meus laços de amor. Tirei o jugo de seu pescoço e eu mesmo me inclinei para alimentá-lo.

[[v28-11-5]]

^<<v28-11-5,5>>^ "Mas, porque meu povo não quer voltar para mim, voltará para o Egito e será obrigado a viver na Assíria.

[[v28-11-6]]

^<<v28-11-6,6>>^ A guerra devastará suas cidades, e os inimigos derrubarão suas portas. Destruirão os israelitas, por causa de suas tramas.

[[v28-11-7]]

^<<v28-11-7,7>>^ Pois meu povo está decidido a me abandonar; eles me chamam Altíssimo, mas não me honram de verdade.

[[v28-11-8]]

^<<v28-11-8,8>>^ "Como eu poderia desistir de você, Israel? Como poderia deixá-lo? Como poderia destruí-lo como Admá ou arrasá-lo como Zeboim? Meu coração está dilacerado, e minha compaixão transborda.

[[v28-11-9]]

^<<v28-11-9,9>>^ Não enviarei minha ira furiosa, não destruirei Israel, pois sou Deus, e não um simples mortal. Sou o Santo que vive entre vocês, e não virei com minha ira.

[[v28-11-10]]

^<<v28-11-10,10>>^ Pois, um dia, meu povo me seguirá; eu, o SENHOR, rugirei como leão, e, quando eu rugir, meu povo retornará, tremendo, desde o oeste.

[[v28-11-11]]

^<<v28-11-11,11>>^ Como um bando de aves, virão do Egito; tremendo como pombas, voltarão da Assíria. Eu os trarei de volta para casa", diz o SENHOR.

[[v28-11-12]]

^<<v28-11-12,12>>^ Israel me cerca de mentiras e traições, mas Judá ainda obedece a Deus e é fiel ao Santo.

'''

xref:028-oseias/028-oseias-010.adoc#v28-10-0[&#60; Capítulo Anterior] | <<v28-11-0,Topo>> | xref:028-oseias/028-oseias-012.adoc#v28-12-0[Próximo Capítulo &#62;]