include::./index.adoc[]

[[v28-1-0]]
=== Oséias, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v28-1-1]]

^<<v28-1-1,1>>^ O SENHOR revelou esta mensagem a Oseias, filho de Beeri, durante os anos em que Uzias, Jotão, Acaz e Ezequias eram reis de Judá, e Jeroboão, filho de Jeoás, era rei de Israel.

[[v28-1-2]]

^<<v28-1-2,2>>^ Quando o SENHOR começou a falar a Israel por meio de Oseias, disse-lhe: "Vá e case-se com uma prostituta, para que os filhos dela sejam concebidos em prostituição. Isso mostrará como Israel agiu como prostituta ao afastar-se do SENHOR".

[[v28-1-3]]

^<<v28-1-3,3>>^ Então Oseias se casou com Gômer, filha de Diblaim. Ela ficou grávida e deu um filho a Oseias.

[[v28-1-4]]

^<<v28-1-4,4>>^ E o SENHOR disse: "Dê à criança o nome de Jezreel, ‘Deus semeia’, pois estou prestes a castigar a dinastia do rei Jeú para vingar os homicídios que ele cometeu em Jezreel. Sim, acabarei com o reino de Israel.

[[v28-1-5]]

^<<v28-1-5,5>>^ Nesse dia, destruirei seu poder militar no vale de Jezreel".

[[v28-1-6]]

^<<v28-1-6,6>>^ Pouco tempo depois, Gômer engravidou novamente e deu à luz uma filha. O SENHOR disse a Oseias: "Dê à sua filha o nome de Lo-Ruama, ‘Não Amada’, pois não mostrarei mais amor ao povo de Israel, nem lhe perdoarei.

[[v28-1-7]]

^<<v28-1-7,7>>^ Contudo, mostrarei amor ao povo de Judá. Eu, o SENHOR, seu Deus, os livrarei de seus inimigos, não com armas e exércitos, nem com cavalos e carros de guerra, mas por meu poder".

[[v28-1-8]]

^<<v28-1-8,8>>^ Depois de Gômer ter desmamado Lo-Ruama, ficou grávida mais uma vez e deu à luz outro filho.

[[v28-1-9]]

^<<v28-1-9,9>>^ E o SENHOR disse: "Dê-lhe o nome de Lo-Ami, ‘Não Meu Povo’, pois Israel não é meu povo, e eu não sou seu Deus.

[[v28-1-10]]

^<<v28-1-10,10>>^ "Virá o tempo, porém, em que o povo de Israel se tornará como a areia à beira do mar, que não se pode contar. Então, no lugar onde lhes foi dito: ‘Vocês não são meu povo’, se dirá: ‘Vocês são filhos do Deus vivo’.

[[v28-1-11]]

^<<v28-1-11,11>>^ Nesse tempo, o povo de Judá e o povo de Israel se unirão. Escolherão para si um só líder e voltarão juntos do exílio. Que grande dia será o dia em que Deus semear seu povo novamente em sua terra!

'''

xref:027-daniel/027-daniel-012.adoc#v27-12-0[&#60; Capítulo Anterior] | <<v28-1-0,Topo>> | xref:028-oseias/028-oseias-002.adoc#v28-2-0[Próximo Capítulo &#62;]