include::./index.adoc[]

[[v41-12-0]]
=== Marcos, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v41-12-1]]

^<<v41-12-1,1>>^ Então Jesus começou a lhes ensinar por meio de parábolas: "Um homem plantou um vinhedo. Construiu uma cerca ao seu redor, um tanque de prensar e uma torre para o guarda. Depois, arrendou o vinhedo a alguns lavradores e partiu para um lugar distante.

[[v41-12-2]]

^<<v41-12-2,2>>^ No tempo da colheita da uva, enviou um de seus servos para receber sua parte da produção.

[[v41-12-3]]

^<<v41-12-3,3>>^ Os lavradores agarraram o servo, o espancaram e o mandaram de volta de mãos vazias.

[[v41-12-4]]

^<<v41-12-4,4>>^ Então o dono da terra enviou outro servo, mas eles o insultaram e bateram na cabeça dele.

[[v41-12-5]]

^<<v41-12-5,5>>^ O próximo servo que ele mandou foi morto. Outros servos que ele enviou foram espancados ou mortos,

[[v41-12-6]]

^<<v41-12-6,6>>^ até que só restou um: seu filho muito amado. Por fim, o dono o enviou, pois pensou: ‘Certamente respeitarão meu filho’.

[[v41-12-7]]

^<<v41-12-7,7>>^ "Os lavradores, porém, disseram uns aos outros: ‘Aí vem o herdeiro da propriedade. Vamos matá-lo e tomar posse desta terra!’.

[[v41-12-8]]

^<<v41-12-8,8>>^ Então o agarraram, o mataram e jogaram seu corpo para fora do vinhedo.

[[v41-12-9]]

^<<v41-12-9,9>>^ "O que vocês acham que o dono do vinhedo fará?", perguntou Jesus. "Ele virá, matará os lavradores e arrendará o vinhedo a outros.

[[v41-12-10]]

^<<v41-12-10,10>>^ Vocês nunca leram nas Escrituras: ‘A pedra que os construtores rejeitaram se tornou a pedra angular.

[[v41-12-11]]

^<<v41-12-11,11>>^ Isso é obra do Senhor e é maravilhosa de ver’?"

[[v41-12-12]]

^<<v41-12-12,12>>^ Os líderes religiosos queriam prender Jesus, pois perceberam que eram eles os lavradores maus a que Jesus se referia. No entanto, por medo da multidão, deixaram-no e foram embora.

[[v41-12-13]]

^<<v41-12-13,13>>^ Mais tarde, os líderes enviaram alguns fariseus e membros do partido de Herodes com o objetivo de levar Jesus a dizer algo que desse motivo para o prenderem.

[[v41-12-14]]

^<<v41-12-14,14>>^ Disseram: "Mestre, sabemos como o senhor é honesto. É imparcial e não demonstra favoritismo. Ensina o caminho de Deus de acordo com a verdade. Agora, diga-nos: É certo pagar impostos a César ou não?

[[v41-12-15]]

^<<v41-12-15,15>>^ Devemos pagar ou não?". Jesus percebeu a hipocrisia deles e disse: "Por que vocês tentam me apanhar numa armadilha? Mostrem-me uma moeda de prata, e eu lhes direi".

[[v41-12-16]]

^<<v41-12-16,16>>^ Quando lhe deram a moeda, ele disse: "De quem são a imagem e o título nela gravados?". "De César", responderam.

[[v41-12-17]]

^<<v41-12-17,17>>^ "Então deem a César o que pertence a César, e deem a Deus o que pertence a Deus", disse ele. Sua resposta os deixou muito admirados.

[[v41-12-18]]

^<<v41-12-18,18>>^ Depois vieram a Jesus alguns saduceus, líderes religiosos que afirmam não haver ressurreição dos mortos, e perguntaram:

[[v41-12-19]]

^<<v41-12-19,19>>^ "Mestre, Moisés nos deu uma lei segundo a qual se um homem morrer sem deixar filhos, o irmão dele deve se casar com a viúva e ter um filho que dará continuidade ao nome do irmão.

[[v41-12-20]]

^<<v41-12-20,20>>^ Numa família havia sete irmãos. O mais velho se casou e morreu sem deixar filhos.

[[v41-12-21]]

^<<v41-12-21,21>>^ O segundo irmão se casou com a viúva, mas também morreu sem deixar filhos. Então o terceiro irmão se casou com ela.

[[v41-12-22]]

^<<v41-12-22,22>>^ O mesmo aconteceu até o sétimo irmão, e nenhum deixou filhos. Por fim, a mulher também morreu.

[[v41-12-23]]

^<<v41-12-23,23>>^ Diga-nos, de quem ela será esposa na ressurreição? Afinal, os sete se casaram com ela".

[[v41-12-24]]

^<<v41-12-24,24>>^ Jesus respondeu: "O erro de vocês está em não conhecerem as Escrituras nem o poder de Deus.

[[v41-12-25]]

^<<v41-12-25,25>>^ Pois, quando os mortos ressuscitarem, não se casarão nem se darão em casamento. Nesse sentido, serão como os anjos do céu.

[[v41-12-26]]

^<<v41-12-26,26>>^ "Agora, quanto a haver ressurreição dos mortos, vocês não leram a esse respeito nos escritos de Moisés, no relato sobre o arbusto em chamas? Deus disse a Moisés: ‘Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó’.

[[v41-12-27]]

^<<v41-12-27,27>>^ Portanto, ele é o Deus dos vivos, e não dos mortos. Vocês estão completamente enganados!".

[[v41-12-28]]

^<<v41-12-28,28>>^ Um dos mestres da lei estava ali ouvindo a discussão. Ao perceber que Jesus tinha respondido bem, perguntou: "De todos os mandamentos, qual é o mais importante?".

[[v41-12-29]]

^<<v41-12-29,29>>^ Jesus respondeu: "O mandamento mais importante é este: ‘Ouça, ó Israel! O Senhor, nosso Deus, é o único Senhor.

[[v41-12-30]]

^<<v41-12-30,30>>^ Ame o Senhor, seu Deus, de todo o seu coração, de toda a sua alma, de toda a sua mente e de todas as suas forças’.

[[v41-12-31]]

^<<v41-12-31,31>>^ O segundo é igualmente importante: ‘Ame o seu próximo como a si mesmo’. Nenhum outro mandamento é maior que esses".

[[v41-12-32]]

^<<v41-12-32,32>>^ O mestre da lei respondeu: "Muito bem, mestre. O senhor falou a verdade ao dizer que há só um Deus, e nenhum outro.

[[v41-12-33]]

^<<v41-12-33,33>>^ E sei que é importante amá-lo de todo o meu coração, de todo o meu entendimento e de todas as minhas forças, e amar o meu próximo como a mim mesmo. É mais importante que oferecer todos os holocaustos e sacrifícios exigidos pela lei".

[[v41-12-34]]

^<<v41-12-34,34>>^ Ao perceber quanto o homem compreendia, Jesus disse: "Você não está longe do reino de Deus". Depois disso, ninguém se atreveu a lhe fazer mais perguntas.

[[v41-12-35]]

^<<v41-12-35,35>>^ Mais tarde, enquanto ensinava o povo no templo, Jesus fez a seguinte pergunta: "Por que os mestres da lei afirmam que o Cristo é filho de Davi?

[[v41-12-36]]

^<<v41-12-36,36>>^ O próprio Davi, falando por meio do Espírito Santo, disse: ‘O Senhor disse ao meu Senhor: Sente-se no lugar de honra à minha direita até que eu humilhe seus inimigos debaixo de seus pés’.

[[v41-12-37]]

^<<v41-12-37,37>>^ Uma vez que Davi chamou o Cristo de ‘meu Senhor’, como ele pode ser filho de Davi?". E a grande multidão o ouvia com prazer.

[[v41-12-38]]

^<<v41-12-38,38>>^ Jesus também ensinou: "Cuidado com os mestres da lei! Eles gostam de se exibir com vestes longas e de receber saudações respeitosas quando andam pelas praças.

[[v41-12-39]]

^<<v41-12-39,39>>^ E como gostam de sentar-se nos lugares de honra nas sinagogas e à cabeceira da mesa nos banquetes!

[[v41-12-40]]

^<<v41-12-40,40>>^ No entanto, tomam posse dos bens das viúvas de maneira desonesta e, depois, para dar a impressão de piedade, fazem longas orações em público. Por causa disso, serão duramente castigados".

[[v41-12-41]]

^<<v41-12-41,41>>^ Jesus sentou-se perto da caixa de ofertas do templo e ficou observando o povo colocar o dinheiro. Muitos ricos contribuíam com grandes quantias.

[[v41-12-42]]

^<<v41-12-42,42>>^ Então veio uma viúva pobre e colocou duas moedas pequenas.

[[v41-12-43]]

^<<v41-12-43,43>>^ Jesus chamou seus discípulos e disse: "Eu lhes digo a verdade: essa viúva depositou na caixa de ofertas mais que todos os outros.

[[v41-12-44]]

^<<v41-12-44,44>>^ Eles deram uma parte do que lhes sobrava, mas ela, em sua pobreza, deu tudo que tinha".

'''

xref:041-marcos/041-marcos-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-marcos/041-marcos-013.adoc#v41-13-0[Próximo Capítulo &#62;]