include::./index.adoc[]

[[v41-6-0]]
=== Marcos, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v41-6-1]]

^<<v41-6-1,1>>^ Jesus deixou essa região e voltou com seus discípulos para Nazaré, cidade onde tinha morado.

[[v41-6-2]]

^<<v41-6-2,2>>^ No sábado seguinte, começou a ensinar na sinagoga, e muitos dos que o ouviam se admiraram e perguntavam: "De onde vem tanta sabedoria e poder para realizar esses milagres?

[[v41-6-3]]

^<<v41-6-3,3>>^ Não é esse o carpinteiro, filho de Maria e irmão de Tiago, José, Judas e Simão? Suas irmãs moram aqui, entre nós". E sentiam-se muito ofendidos.

[[v41-6-4]]

^<<v41-6-4,4>>^ Então Jesus lhes disse: "Um profeta recebe honra em toda parte, menos em sua cidade e entre seus parentes e sua própria família".

[[v41-6-5]]

^<<v41-6-5,5>>^ Por isso, não pôde realizar milagres ali, exceto pôr as mãos sobre alguns enfermos e curá-los.

[[v41-6-6]]

^<<v41-6-6,6>>^ E ficou admirado com a incredulidade daquele povo. Então Jesus percorreu diversos povoados, ensinando a seus moradores.

[[v41-6-7]]

^<<v41-6-7,7>>^ Reuniu os Doze e começou a enviá-los de dois em dois, dando-lhes autoridade para expulsar espíritos impuros.

[[v41-6-8]]

^<<v41-6-8,8>>^ Instruiu-os a não levar coisa alguma na viagem, exceto um cajado. Não poderiam levar alimento, nem bolsa de viagem, nem dinheiro.

[[v41-6-9]]

^<<v41-6-9,9>>^ Poderiam calçar sandálias, mas não levar uma muda de roupa extra.

[[v41-6-10]]

^<<v41-6-10,10>>^ Disse ele: "Onde quer que forem, fiquem na mesma casa até partirem da cidade.

[[v41-6-11]]

^<<v41-6-11,11>>^ Mas, se algum povoado se recusar a recebê-los ou a ouvi-los, ao saírem, sacudam a poeira dos pés como sinal de reprovação".

[[v41-6-12]]

^<<v41-6-12,12>>^ Então eles partiram, dizendo a todos que encontravam que se arrependessem.

[[v41-6-13]]

^<<v41-6-13,13>>^ Expulsaram muitos demônios e curaram muitos enfermos, ungindo-os com óleo.

[[v41-6-14]]

^<<v41-6-14,14>>^ Logo o rei Herodes ouviu falar de Jesus, pois todos comentavam a seu respeito. Alguns diziam: "João Batista ressuscitou dos mortos. Por isso tem poder para fazer esses milagres".

[[v41-6-15]]

^<<v41-6-15,15>>^ Outros diziam: "É Elias". Ainda outros diziam: "É um profeta, como os profetas de antigamente".

[[v41-6-16]]

^<<v41-6-16,16>>^ Quando Herodes ouviu falar de Jesus, disse: "João, o homem a quem decapitei, voltou dos mortos!".

[[v41-6-17]]

^<<v41-6-17,17>>^ O rei havia mandado prender e encarcerar João para agradar Herodias. Ela era esposa de seu irmão, Filipe, mas Herodes tinha se casado com ela.

[[v41-6-18]]

^<<v41-6-18,18>>^ João dizia a Herodes: "É contra a lei que o senhor viva com a esposa de seu irmão".

[[v41-6-19]]

^<<v41-6-19,19>>^ Por isso Herodias guardava rancor de João e queria matá-lo, mas não podia fazê-lo,

[[v41-6-20]]

^<<v41-6-20,20>>^ pois Herodes o respeitava e o protegia, sabendo que ele era um homem justo e santo. Herodes ficava muito perturbado sempre que falava com João, mas mesmo assim gostava de ouvi-lo.

[[v41-6-21]]

^<<v41-6-21,21>>^ Finalmente, no aniversário de Herodes, Herodias teve a oportunidade que procurava. Ele deu uma festa para os membros do alto escalão do governo, para seus oficiais militares e para os cidadãos mais importantes da Galileia.

[[v41-6-22]]

^<<v41-6-22,22>>^ Sua filha, também chamada Herodias, entrou e apresentou uma dança que agradou muito Herodes e seus convidados. "Peça-me qualquer coisa que deseje, e eu lhe darei", disse o rei à moça.

[[v41-6-23]]

^<<v41-6-23,23>>^ E prometeu, sob juramento: "Eu lhe darei o que pedir, até metade do meu reino!".

[[v41-6-24]]

^<<v41-6-24,24>>^ Ela saiu e perguntou à mãe: "O que devo pedir?". A mãe lhe disse: "Peça a cabeça de João Batista!".

[[v41-6-25]]

^<<v41-6-25,25>>^ A moça voltou depressa ao rei e disse: "Quero a cabeça de João Batista agora mesmo num prato!".

[[v41-6-26]]

^<<v41-6-26,26>>^ O rei muito se entristeceu com isso, mas, por causa do juramento que havia feito na frente dos convidados, não pôde negar o pedido.

[[v41-6-27]]

^<<v41-6-27,27>>^ Assim, enviou no mesmo instante um carrasco com ordens de cortar a cabeça de João e trazê-la. Ele decapitou João na prisão,

[[v41-6-28]]

^<<v41-6-28,28>>^ trouxe a cabeça num prato e a entregou à moça, que a levou à sua mãe.

[[v41-6-29]]

^<<v41-6-29,29>>^ Quando os discípulos de João souberam o que havia acontecido, foram buscar o corpo e o colocaram numa sepultura.

[[v41-6-30]]

^<<v41-6-30,30>>^ Os apóstolos voltaram de sua missão e contaram a Jesus tudo que tinham feito e ensinado.

[[v41-6-31]]

^<<v41-6-31,31>>^ Jesus lhes disse: "Vamos sozinhos até um lugar tranquilo para descansar um pouco", pois tanta gente ia e vinha que eles não tinham tempo nem para comer.

[[v41-6-32]]

^<<v41-6-32,32>>^ Então saíram de barco para um lugar isolado, a fim de ficarem a sós.

[[v41-6-33]]

^<<v41-6-33,33>>^ Contudo, muitos os reconheceram e os viram partir, e pessoas de várias cidades correram e chegaram antes deles.

[[v41-6-34]]

^<<v41-6-34,34>>^ Quando Jesus saiu do barco, viu a grande multidão e teve compaixão dela, pois eram como ovelhas sem pastor. Então começou a lhes ensinar muitas coisas.

[[v41-6-35]]

^<<v41-6-35,35>>^ Ao entardecer, os discípulos foram até ele e disseram: "Este lugar é isolado, e já está tarde.

[[v41-6-36]]

^<<v41-6-36,36>>^ Mande as multidões embora, para que possam ir aos campos e povoados vizinhos e comprar algo para comer".

[[v41-6-37]]

^<<v41-6-37,37>>^ Jesus, porém, disse: "Providenciem vocês mesmos alimento para eles". "Precisaríamos de muito dinheiro para comprar comida para todo esse povo!", responderam.

[[v41-6-38]]

^<<v41-6-38,38>>^ "Quantos pães vocês têm?", perguntou ele. "Vão verificar." Eles voltaram e informaram: "Cinco pães e dois peixes".

[[v41-6-39]]

^<<v41-6-39,39>>^ Então Jesus ordenou que fizessem a multidão sentar-se em grupos na grama verde.

[[v41-6-40]]

^<<v41-6-40,40>>^ Assim, eles se sentaram em grupos de cinquenta e de cem.

[[v41-6-41]]

^<<v41-6-41,41>>^ Jesus tomou os cinco pães e os dois peixes, olhou para o céu e os abençoou. Então, à medida que ia partindo os pães, entregava-os aos discípulos para que os distribuíssem ao povo. Também dividiu os peixes para que todos recebessem uma porção.

[[v41-6-42]]

^<<v41-6-42,42>>^ Todos comeram à vontade,

[[v41-6-43]]

^<<v41-6-43,43>>^ e os discípulos recolheram doze cestos com os pães e peixes que sobraram.

[[v41-6-44]]

^<<v41-6-44,44>>^ Os que comeram foram cinco mil homens.

[[v41-6-45]]

^<<v41-6-45,45>>^ Logo em seguida, Jesus insistiu com seus discípulos que voltassem ao barco e atravessassem o mar até Betsaida, enquanto ele mandava o povo para casa.

[[v41-6-46]]

^<<v41-6-46,46>>^ Depois de se despedir de todos, subiu sozinho ao monte para orar.

[[v41-6-47]]

^<<v41-6-47,47>>^ Durante a noite, os discípulos estavam no barco, no meio do mar, e Jesus, sozinho em terra.

[[v41-6-48]]

^<<v41-6-48,48>>^ Ele viu que estavam em apuros, remando com força e lutando contra o vento e as ondas. Por volta das três da madrugada, Jesus foi até eles caminhando sobre o mar. Sua intenção era passar por eles,

[[v41-6-49]]

^<<v41-6-49,49>>^ mas, quando o avistaram caminhando sobre as águas, gritaram de pavor, pensando que fosse um fantasma.

[[v41-6-50]]

^<<v41-6-50,50>>^ Ficaram todos aterrorizados ao vê-lo. Imediatamente, porém, Jesus lhes disse: "Não tenham medo! Coragem, sou eu!".

[[v41-6-51]]

^<<v41-6-51,51>>^ Em seguida, subiu no barco e o vento parou. Os discípulos ficaram admirados,

[[v41-6-52]]

^<<v41-6-52,52>>^ pois ainda não tinham entendido o milagre dos pães. O coração deles estava endurecido.

[[v41-6-53]]

^<<v41-6-53,53>>^ Depois de atravessarem o mar, chegaram a Genesaré. Levaram o barco até a margem

[[v41-6-54]]

^<<v41-6-54,54>>^ e desceram. As pessoas reconheceram Jesus assim que o viram.

[[v41-6-55]]

^<<v41-6-55,55>>^ Quando ouviam que Jesus estava em algum lugar, corriam por toda a região, levando os enfermos em macas para onde sabiam que ele estava.

[[v41-6-56]]

^<<v41-6-56,56>>^ Aonde quer que ele fosse — aos povoados, às cidades ou aos campos ao redor —, levavam os enfermos para as praças. Suplicavam que ele os deixasse pelo menos tocar na borda de seu manto, e todos que o tocavam eram curados.

'''

xref:041-marcos/041-marcos-005.adoc#v41-5-0[&#60; Capítulo Anterior] | <<v41-6-0,Topo>> | xref:041-marcos/041-marcos-007.adoc#v41-7-0[Próximo Capítulo &#62;]