include::./index.adoc[]

[[v41-4-0]]
=== Marcos, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v41-4-1]]

^<<v41-4-1,1>>^ Mais uma vez, Jesus começou a ensinar à beira-mar. Em pouco tempo, uma grande multidão se juntou ao seu redor. Então ele entrou num barco e sentou-se, enquanto o povo ficou na praia.

[[v41-4-2]]

^<<v41-4-2,2>>^ Ele os ensinou contando várias histórias na forma de parábolas, como esta:

[[v41-4-3]]

^<<v41-4-3,3>>^ "Ouçam! Um lavrador saiu para semear.

[[v41-4-4]]

^<<v41-4-4,4>>^ Enquanto espalhava as sementes pelo campo, algumas caíram à beira do caminho, e as aves vieram e as comeram.

[[v41-4-5]]

^<<v41-4-5,5>>^ Outras sementes caíram em solo rochoso e, não havendo muita terra, germinaram rapidamente,

[[v41-4-6]]

^<<v41-4-6,6>>^ mas as plantas logo murcharam sob o calor do sol e secaram, pois não tinham raízes profundas.

[[v41-4-7]]

^<<v41-4-7,7>>^ Outras sementes caíram entre espinhos, que cresceram e sufocaram os brotos, sem nada produzirem.

[[v41-4-8]]

^<<v41-4-8,8>>^ Ainda outras caíram em solo fértil e germinaram, cresceram e produziram uma colheita trinta, sessenta e até cem vezes maior que a quantidade semeada".

[[v41-4-9]]

^<<v41-4-9,9>>^ Então ele disse: "Quem tem ouvidos para ouvir, ouça com atenção!".

[[v41-4-10]]

^<<v41-4-10,10>>^ Mais tarde, quando Jesus estava sozinho com os Doze e os outros que estavam reunidos ao seu redor, perguntaram-lhe qual era o significado das parábolas.

[[v41-4-11]]

^<<v41-4-11,11>>^ Ele respondeu: "A vocês é permitido entender o segredo do reino de Deus, mas uso parábolas para falar aos de fora,

[[v41-4-12]]

^<<v41-4-12,12>>^ de modo que: ‘Mesmo que vejam o que faço, não perceberão, e ainda que ouçam o que digo, não compreenderão. Do contrário, poderiam voltar-se para mim, e ser perdoados’".

[[v41-4-13]]

^<<v41-4-13,13>>^ Então Jesus disse: "Se vocês não entendem o significado desta parábola, como entenderão as demais?

[[v41-4-14]]

^<<v41-4-14,14>>^ O lavrador lança sementes ao anunciar a mensagem.

[[v41-4-15]]

^<<v41-4-15,15>>^ As sementes que caíram à beira do caminho representam os que ouvem a mensagem, mas Satanás logo vem e a toma deles.

[[v41-4-16]]

^<<v41-4-16,16>>^ As que caíram no solo rochoso representam aqueles que ouvem a mensagem e, sem demora, a recebem com alegria.

[[v41-4-17]]

^<<v41-4-17,17>>^ Contudo, uma vez que não têm raízes profundas, não duram muito. Assim que enfrentam problemas ou são perseguidos por causa da mensagem, cedo desanimam.

[[v41-4-18]]

^<<v41-4-18,18>>^ As que caíram entre os espinhos representam outros que ouvem a mensagem,

[[v41-4-19]]

^<<v41-4-19,19>>^ mas logo ela é sufocada pelas preocupações desta vida, pela sedução da riqueza e pelo desejo por outras coisas, não produzindo fruto.

[[v41-4-20]]

^<<v41-4-20,20>>^ E as que caíram em solo fértil representam os que ouvem e aceitam a mensagem e produzem uma colheita trinta, sessenta ou até cem vezes maior que a quantidade semeada".

[[v41-4-21]]

^<<v41-4-21,21>>^ Em seguida, Jesus lhes perguntou: "Alguém acenderia uma lâmpada e a colocaria sob um cesto ou uma cama? Claro que não! A lâmpada é colocada num pedestal, de onde sua luz brilhará.

[[v41-4-22]]

^<<v41-4-22,22>>^ Da mesma forma, tudo que está escondido será revelado, e tudo que está oculto virá à luz.

[[v41-4-23]]

^<<v41-4-23,23>>^ Quem tem ouvidos para ouvir, ouça com atenção!".

[[v41-4-24]]

^<<v41-4-24,24>>^ Então acrescentou: "Prestem muita atenção ao que vão ouvir. Com o mesmo padrão de medida que adotarem, vocês serão medidos, e mais ainda lhes será acrescentado.

[[v41-4-25]]

^<<v41-4-25,25>>^ Pois ao que tem, mais lhe será dado; mas do que não tem, até o que tem lhe será tirado".

[[v41-4-26]]

^<<v41-4-26,26>>^ Jesus também disse: "O reino de Deus é como um lavrador que lança sementes sobre a terra.

[[v41-4-27]]

^<<v41-4-27,27>>^ Noite e dia, esteja ele dormindo ou acordado, as sementes germinam e crescem, mas ele não sabe como isso acontece.

[[v41-4-28]]

^<<v41-4-28,28>>^ A terra produz as colheitas por si própria. Primeiro aparece uma folha, depois se formam as espigas de trigo e, por fim, o cereal amadurece.

[[v41-4-29]]

^<<v41-4-29,29>>^ E, assim que o cereal está maduro, o lavrador vem e o corta com a foice, pois chegou o tempo da colheita".

[[v41-4-30]]

^<<v41-4-30,30>>^ Jesus disse ainda: "Como posso descrever o reino de Deus? Que comparação devo usar para ilustrá-lo?

[[v41-4-31]]

^<<v41-4-31,31>>^ É como uma semente de mostarda plantada na terra. É a menor das sementes,

[[v41-4-32]]

^<<v41-4-32,32>>^ mas se torna a maior de todas as hortaliças, com ramos tão grandes que as aves fazem ninhos à sua sombra".

[[v41-4-33]]

^<<v41-4-33,33>>^ Jesus usou muitas histórias e ilustrações semelhantes para ensinar o povo, conforme tinham condições de entender.

[[v41-4-34]]

^<<v41-4-34,34>>^ Na verdade, só usava parábolas para ensinar em público. Depois, quando estava sozinho com seus discípulos, explicava tudo para eles.

[[v41-4-35]]

^<<v41-4-35,35>>^ Ao anoitecer, Jesus disse a seus discípulos: "Vamos atravessar para o outro lado do mar".

[[v41-4-36]]

^<<v41-4-36,36>>^ Com ele a bordo, partiram e deixaram a multidão para trás, embora outros barcos os seguissem.

[[v41-4-37]]

^<<v41-4-37,37>>^ Logo uma forte tempestade se levantou. As ondas arrebentavam sobre o barco, que começou a encher-se de água.

[[v41-4-38]]

^<<v41-4-38,38>>^ Jesus dormia na parte de trás do barco, com a cabeça numa almofada. Os discípulos o acordaram, clamando: "Mestre, vamos morrer! O senhor não se importa?".

[[v41-4-39]]

^<<v41-4-39,39>>^ Jesus despertou, repreendeu o vento e disse ao mar: "Silêncio! Aquiete-se!". De repente, o vento parou, e houve grande calmaria.

[[v41-4-40]]

^<<v41-4-40,40>>^ Então Jesus lhes perguntou: "Por que estão com medo? Ainda não têm fé?".

[[v41-4-41]]

^<<v41-4-41,41>>^ Apavorados, os discípulos diziam uns aos outros: "Quem é este homem? Até o vento e o mar lhe obedecem!".

'''

xref:041-marcos/041-marcos-003.adoc#v41-3-0[&#60; Capítulo Anterior] | <<v41-4-0,Topo>> | xref:041-marcos/041-marcos-005.adoc#v41-5-0[Próximo Capítulo &#62;]