include::./index.adoc[]

[[v41-5-0]]
=== Marcos, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v41-5-1]]

^<<v41-5-1,1>>^ Assim, chegaram ao outro lado do mar, à região dos gerasenos.

[[v41-5-2]]

^<<v41-5-2,2>>^ Quando Jesus desembarcou, imediatamente um homem possuído por um espírito impuro saiu do cemitério e veio ao seu encontro.

[[v41-5-3]]

^<<v41-5-3,3>>^ Esse homem morava entre as cavernas usadas como túmulos e ninguém conseguia detê-lo, nem mesmo com correntes.

[[v41-5-4]]

^<<v41-5-4,4>>^ Sempre que era acorrentado e algemado, quebrava as algemas dos pulsos e despedaçava as correntes dos pés. Ninguém era forte o suficiente para dominá-lo.

[[v41-5-5]]

^<<v41-5-5,5>>^ Dia e noite, vagava entre os túmulos e pelos montes, gritando e cortando-se com pedras.

[[v41-5-6]]

^<<v41-5-6,6>>^ Quando o homem viu Jesus, ainda a certa distância, correu ao seu encontro e se curvou diante dele.

[[v41-5-7]]

^<<v41-5-7,7>>^ Então soltou um forte grito: "Por que vem me importunar, Jesus, Filho do Deus Altíssimo? Em nome de Deus, suplico que não me torture!".

[[v41-5-8]]

^<<v41-5-8,8>>^ Pois Jesus já havia falado ao espírito: "Saia deste homem, espírito impuro!".

[[v41-5-9]]

^<<v41-5-9,9>>^ Jesus lhe perguntou: "Qual é o seu nome?". Ele respondeu: "Meu nome é Legião, porque há muitos de nós dentro deste homem".

[[v41-5-10]]

^<<v41-5-10,10>>^ E os espíritos impuros suplicaram repetidamente que ele não os enviasse a algum lugar distante.

[[v41-5-11]]

^<<v41-5-11,11>>^ Havia uma grande manada de porcos pastando num monte ali perto.

[[v41-5-12]]

^<<v41-5-12,12>>^ "Mande-nos para aqueles porcos", imploraram os espíritos. "Deixe que entremos neles."

[[v41-5-13]]

^<<v41-5-13,13>>^ Jesus lhes deu permissão. Os espíritos impuros saíram do homem e entraram nos porcos, e toda a manada, cerca de dois mil porcos, se atirou pela encosta íngreme do monte para dentro do mar e se afogou.

[[v41-5-14]]

^<<v41-5-14,14>>^ Os que cuidavam dos porcos fugiram para uma cidade próxima e para seus arredores, espalhando a notícia. O povo correu para ver o que havia ocorrido.

[[v41-5-15]]

^<<v41-5-15,15>>^ Chegaram até onde Jesus estava e viram o homem que tinha sido possuído pela legião de demônios. Estava sentado ali, vestido e em perfeito juízo, e todos tiveram medo.

[[v41-5-16]]

^<<v41-5-16,16>>^ Então os que presenciaram os acontecimentos contaram aos outros o que havia ocorrido com o homem possuído por demônios e com os porcos.

[[v41-5-17]]

^<<v41-5-17,17>>^ A multidão começou a suplicar que Jesus fosse embora da região.

[[v41-5-18]]

^<<v41-5-18,18>>^ Quando Jesus entrava no barco, o homem que tinha sido possuído por demônios implorou para ir com ele.

[[v41-5-19]]

^<<v41-5-19,19>>^ Jesus, porém, não permitiu e disse: "Volte para sua casa e para sua família e conte-lhes tudo que o Senhor fez por você e como ele foi misericordioso".

[[v41-5-20]]

^<<v41-5-20,20>>^ Então o homem partiu e começou a anunciar pela região das Dez Cidades quanto Jesus havia feito por ele, e todos se admiravam do que ele dizia.

[[v41-5-21]]

^<<v41-5-21,21>>^ Jesus entrou novamente no barco e voltou para o outro lado do mar, onde uma grande multidão se juntou ao seu redor na praia.

[[v41-5-22]]

^<<v41-5-22,22>>^ Então chegou um dos líderes da sinagoga local, chamado Jairo. Quando viu Jesus, prostrou-se a seus pés e

[[v41-5-23]]

^<<v41-5-23,23>>^ suplicou repetidas vezes: "Minha filhinha está morrendo. Por favor, venha e ponha as mãos sobre ela; cure-a para que ela viva!".

[[v41-5-24]]

^<<v41-5-24,24>>^ Jesus foi com ele, e todo o povo o seguiu, apertando-se ao seu redor.

[[v41-5-25]]

^<<v41-5-25,25>>^ No meio da multidão estava uma mulher que havia doze anos sofria de hemorragia.

[[v41-5-26]]

^<<v41-5-26,26>>^ Tinha passado por muitas dificuldades nas mãos de vários médicos e, ao longo dos anos, gastou tudo que possuía, sem melhorar. Na verdade, havia piorado.

[[v41-5-27]]

^<<v41-5-27,27>>^ Tendo ouvido falar de Jesus, aproximou-se por trás dele no meio da multidão e tocou em seu manto,

[[v41-5-28]]

^<<v41-5-28,28>>^ pois pensava: "Se eu apenas tocar em seu manto, serei curada".

[[v41-5-29]]

^<<v41-5-29,29>>^ No mesmo instante, a hemorragia parou, e ela sentiu em seu corpo que tinha sido curada da enfermidade.

[[v41-5-30]]

^<<v41-5-30,30>>^ Jesus imediatamente percebeu que dele havia saído poder; por isso, virou-se para a multidão e perguntou: "Quem tocou em meu manto?".

[[v41-5-31]]

^<<v41-5-31,31>>^ Seus discípulos disseram: "Veja a multidão que o aperta de todos os lados. Como o senhor ainda pergunta: ‘Quem tocou em mim?’".

[[v41-5-32]]

^<<v41-5-32,32>>^ Jesus, porém, continuou a olhar ao redor para ver quem havia feito aquilo.

[[v41-5-33]]

^<<v41-5-33,33>>^ Então a mulher, assustada e tremendo pelo que lhe tinha acontecido, veio e, ajoelhando-se diante dele, contou o que havia feito.

[[v41-5-34]]

^<<v41-5-34,34>>^ Jesus lhe disse: "Filha, sua fé a curou. Vá em paz. Seu sofrimento acabou".

[[v41-5-35]]

^<<v41-5-35,35>>^ Enquanto Jesus ainda falava com a mulher, chegaram mensageiros da casa de Jairo, o líder da sinagoga, e lhe disseram: "Sua filha morreu. Para que continuar incomodando o mestre?".

[[v41-5-36]]

^<<v41-5-36,36>>^ Jesus, porém, ouviu essas palavras e disse a Jairo: "Não tenha medo. Apenas creia".

[[v41-5-37]]

^<<v41-5-37,37>>^ Então Jesus deteve a multidão e não deixou que ninguém o acompanhasse, exceto Pedro, Tiago e João, irmão de Tiago.

[[v41-5-38]]

^<<v41-5-38,38>>^ Quando chegaram à casa do líder da sinagoga, Jesus viu um grande tumulto, com muito choro e lamentação.

[[v41-5-39]]

^<<v41-5-39,39>>^ Então entrou e perguntou: "Por que todo esse tumulto e choro? A criança não morreu; está apenas dormindo".

[[v41-5-40]]

^<<v41-5-40,40>>^ A multidão riu de Jesus. Ele, porém, fez todos saírem e levou o pai e a mãe da menina e os três discípulos para o quarto onde ela estava deitada.

[[v41-5-41]]

^<<v41-5-41,41>>^ Segurando-a pela mão, disse-lhe: " Talita cumi! ", que quer dizer "Menina, levante-se!".

[[v41-5-42]]

^<<v41-5-42,42>>^ A menina, que tinha doze anos, levantou-se de imediato e começou a andar. Todos ficaram muito admirados.

[[v41-5-43]]

^<<v41-5-43,43>>^ Jesus deu ordens claras para que não contassem a ninguém o que havia acontecido e depois mandou que dessem alguma coisa para a menina comer.

'''

xref:041-marcos/041-marcos-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-marcos/041-marcos-006.adoc#v41-6-0[Próximo Capítulo &#62;]