include::./index.adoc[]

[[v41-8-0]]
=== Marcos, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v41-8-1]]

^<<v41-8-1,1>>^ Naqueles dias, outra grande multidão se reuniu e, mais uma vez, o povo ficou sem comida. Jesus chamou os discípulos e disse:

[[v41-8-2]]

^<<v41-8-2,2>>^ "Tenho compaixão dessa gente. Estão aqui comigo há três dias e não têm mais nada para comer.

[[v41-8-3]]

^<<v41-8-3,3>>^ Se eu os mandar embora com fome, desmaiarão no caminho. Alguns vieram de longe".

[[v41-8-4]]

^<<v41-8-4,4>>^ Os discípulos disseram: "Como conseguiremos comida suficiente neste lugar deserto para alimentá-los?".

[[v41-8-5]]

^<<v41-8-5,5>>^ Jesus perguntou: "Quantos pães vocês têm?". "Sete", responderam eles.

[[v41-8-6]]

^<<v41-8-6,6>>^ Então Jesus mandou todo o povo sentar-se no chão. Tomou os sete pães, agradeceu a Deus e os partiu em pedaços. Em seguida, entregou-os aos discípulos, que os distribuíram à multidão.

[[v41-8-7]]

^<<v41-8-7,7>>^ Eles encontraram, ainda, alguns peixinhos; Jesus também os abençoou e mandou que os discípulos os distribuíssem.

[[v41-8-8]]

^<<v41-8-8,8>>^ Todos comeram à vontade. Depois, os discípulos recolheram sete cestos grandes com as sobras.

[[v41-8-9]]

^<<v41-8-9,9>>^ Naquele dia, havia cerca de quatro mil homens na multidão. Após comerem, Jesus os mandou para casa.

[[v41-8-10]]

^<<v41-8-10,10>>^ Em seguida, entrou com seus discípulos num barco e atravessou para a região de Dalmanuta.

[[v41-8-11]]

^<<v41-8-11,11>>^ Alguns fariseus vieram ao encontro de Jesus e começaram a discutir com ele. Para pô-lo à prova, exigiram que lhes mostrasse um sinal do céu.

[[v41-8-12]]

^<<v41-8-12,12>>^ Ao ouvir isso, Jesus suspirou profundamente e disse: "Por que este povo insiste em pedir um sinal? Eu lhes digo a verdade: não darei sinal algum aos homens desta geração".

[[v41-8-13]]

^<<v41-8-13,13>>^ Então ele os deixou, entrou de volta no barco e atravessou para o outro lado do mar.

[[v41-8-14]]

^<<v41-8-14,14>>^ Os discípulos, porém, se esqueceram de levar comida. Tinham no barco apenas um pão.

[[v41-8-15]]

^<<v41-8-15,15>>^ Enquanto atravessavam o mar, Jesus os advertiu: "Fiquem atentos! Tenham cuidado com o fermento dos fariseus e de Herodes".

[[v41-8-16]]

^<<v41-8-16,16>>^ Os discípulos começaram a discutir entre si porque não tinham trazido pão.

[[v41-8-17]]

^<<v41-8-17,17>>^ Ao saber do que estavam falando, Jesus disse: "Por que discutem sobre a falta de pão? Ainda não sabem ou não entenderam? Seu coração está tão endurecido que não compreendem?

[[v41-8-18]]

^<<v41-8-18,18>>^ Vocês têm olhos, mas não veem? Têm ouvidos, mas não ouvem? Não se lembram de nada?

[[v41-8-19]]

^<<v41-8-19,19>>^ Quando reparti os cinco pães entre os cinco mil, quantos cestos cheios de sobras vocês recolheram?". "Doze", responderam eles.

[[v41-8-20]]

^<<v41-8-20,20>>^ "E quando reparti os sete pães entre os quatro mil, quantos cestos grandes cheios de sobras vocês recolheram?" "Sete", responderam.

[[v41-8-21]]

^<<v41-8-21,21>>^ "E vocês ainda não entendem?", perguntou.

[[v41-8-22]]

^<<v41-8-22,22>>^ Quando chegaram a Betsaida, algumas pessoas trouxeram um cego a Jesus e lhe pediram que o tocasse.

[[v41-8-23]]

^<<v41-8-23,23>>^ Ele tomou o cego pela mão e o levou para fora do povoado. Em seguida, cuspiu nos olhos do homem, pôs as mãos sobre ele e perguntou: "Vê alguma coisa?".

[[v41-8-24]]

^<<v41-8-24,24>>^ Recuperando aos poucos a vista, o homem respondeu: "Vejo pessoas, mas não as enxergo claramente. Parecem árvores andando".

[[v41-8-25]]

^<<v41-8-25,25>>^ Jesus pôs as mãos sobre os olhos do homem mais uma vez, e sua visão foi completamente restaurada; ele passou a ver tudo com nitidez.

[[v41-8-26]]

^<<v41-8-26,26>>^ Então Jesus se despediu dele e disse: "Ao voltar para casa, não entre no povoado".

[[v41-8-27]]

^<<v41-8-27,27>>^ Jesus e seus discípulos deixaram a Galileia e foram para os povoados perto de Cesareia de Filipe. Enquanto caminhavam, Jesus lhes perguntou: "Quem as pessoas dizem que eu sou?".

[[v41-8-28]]

^<<v41-8-28,28>>^ Eles responderam: "Alguns dizem que o senhor é João Batista; outros, que é Elias ou um dos profetas".

[[v41-8-29]]

^<<v41-8-29,29>>^ "E vocês?", perguntou ele. "Quem vocês dizem que eu sou?" Pedro respondeu: "O senhor é o Cristo!".

[[v41-8-30]]

^<<v41-8-30,30>>^ Mas Jesus os advertiu de que não falassem a ninguém a seu respeito.

[[v41-8-31]]

^<<v41-8-31,31>>^ Então Jesus começou a lhes ensinar que era necessário que o Filho do Homem sofresse muitas coisas e fosse rejeitado pelos líderes do povo, pelos principais sacerdotes e pelos mestres da lei. Seria morto, mas três dias depois ressuscitaria.

[[v41-8-32]]

^<<v41-8-32,32>>^ Enquanto falava abertamente sobre isso com os discípulos, Pedro o chamou de lado e o repreendeu por dizer tais coisas.

[[v41-8-33]]

^<<v41-8-33,33>>^ Jesus se virou, olhou para seus discípulos e repreendeu Pedro. "Afaste-se de mim, Satanás!", disse ele. "Você considera as coisas apenas do ponto de vista humano, e não da perspectiva de Deus."

[[v41-8-34]]

^<<v41-8-34,34>>^ Depois, chamou a multidão e os discípulos e disse: "Se alguém quer ser meu seguidor, negue a si mesmo, tome sua cruz e siga-me.

[[v41-8-35]]

^<<v41-8-35,35>>^ Se tentar se apegar à sua vida, a perderá. Mas, se abrir mão de sua vida por minha causa e por causa das boas-novas, a salvará.

[[v41-8-36]]

^<<v41-8-36,36>>^ Que vantagem há em ganhar o mundo inteiro, mas perder a vida?

[[v41-8-37]]

^<<v41-8-37,37>>^ E o que daria o homem em troca de sua vida?

[[v41-8-38]]

^<<v41-8-38,38>>^ Se alguém se envergonhar de mim e de minha mensagem nesta época de adultério e pecado, o Filho do Homem se envergonhará dele quando vier na glória de seu Pai com os santos anjos".

'''

xref:041-marcos/041-marcos-007.adoc#v41-7-0[&#60; Capítulo Anterior] | <<v41-8-0,Topo>> | xref:041-marcos/041-marcos-009.adoc#v41-9-0[Próximo Capítulo &#62;]