include::./index.adoc[]

[[v41-15-0]]
=== Marcos, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v41-15-1]]

^<<v41-15-1,1>>^ De manhã bem cedo, os principais sacerdotes, os líderes do povo e os mestres da lei — todo o alto conselho — se reuniram para discutir o que fariam em seguida. Então amarraram Jesus, o levaram e o entregaram a Pilatos.

[[v41-15-2]]

^<<v41-15-2,2>>^ Pilatos lhe perguntou: "Você é o rei dos judeus?". Jesus respondeu: "É como você diz".

[[v41-15-3]]

^<<v41-15-3,3>>^ Os principais sacerdotes o acusaram de vários crimes,

[[v41-15-4]]

^<<v41-15-4,4>>^ e Pilatos perguntou: "Você não vai responder? O que diz de todas essas acusações?".

[[v41-15-5]]

^<<v41-15-5,5>>^ Mas, para surpresa de Pilatos, Jesus não disse coisa alguma.

[[v41-15-6]]

^<<v41-15-6,6>>^ A cada ano, durante a festa da Páscoa, era costume libertar um prisioneiro, qualquer um que a multidão escolhesse.

[[v41-15-7]]

^<<v41-15-7,7>>^ Um dos prisioneiros era Barrabás, um revolucionário que havia cometido assassinato durante uma revolta.

[[v41-15-8]]

^<<v41-15-8,8>>^ A multidão foi a Pilatos e pediu que ele libertasse um prisioneiro, como de costume.

[[v41-15-9]]

^<<v41-15-9,9>>^ Pilatos perguntou: "Querem que eu solte o ‘rei dos judeus’?".

[[v41-15-10]]

^<<v41-15-10,10>>^ (Pois havia percebido que os principais sacerdotes tinham prendido Jesus por inveja.)

[[v41-15-11]]

^<<v41-15-11,11>>^ Nesse momento, os principais sacerdotes instigaram a multidão a pedir a libertação de Barrabás em vez de Jesus.

[[v41-15-12]]

^<<v41-15-12,12>>^ Pilatos lhes perguntou: "Então o que farei com este homem que vocês chamam de ‘rei dos judeus’?".

[[v41-15-13]]

^<<v41-15-13,13>>^ "Crucifique-o!", gritou a multidão.

[[v41-15-14]]

^<<v41-15-14,14>>^ "Por quê?", quis saber Pilatos. "Que crime ele cometeu?" Mas a multidão gritou ainda mais alto: "Crucifique-o!".

[[v41-15-15]]

^<<v41-15-15,15>>^ Para acalmar a multidão, Pilatos lhes soltou Barrabás. Então, depois de mandar açoitar Jesus, entregou-o aos soldados romanos para que fosse crucificado.

[[v41-15-16]]

^<<v41-15-16,16>>^ Os soldados levaram Jesus para o palácio do governador (lugar conhecido como Pretório) e chamaram todo o regimento.

[[v41-15-17]]

^<<v41-15-17,17>>^ Vestiram Jesus com um manto vermelho, teceram uma coroa de espinhos e a colocaram em sua cabeça.

[[v41-15-18]]

^<<v41-15-18,18>>^ Então o saudavam, zombando: "Salve, rei dos judeus!".

[[v41-15-19]]

^<<v41-15-19,19>>^ Batiam em sua cabeça com uma vara, cuspiam nele e ajoelhavam-se, fingindo adorá-lo.

[[v41-15-20]]

^<<v41-15-20,20>>^ Quando se cansaram de zombar dele, tiraram o manto vermelho e o vestiram com suas roupas. Então o levaram para ser crucificado.

[[v41-15-21]]

^<<v41-15-21,21>>^ Um homem chamado Simão, de Cirene, passava ali naquele momento, vindo do campo. Os soldados o obrigaram a carregar a cruz. (Simão era pai de Alexandre e Rufo.)

[[v41-15-22]]

^<<v41-15-22,22>>^ Levaram Jesus a um lugar chamado Gólgota (que quer dizer "Lugar da Caveira").

[[v41-15-23]]

^<<v41-15-23,23>>^ Ofereceram-lhe vinho misturado com mirra, mas ele recusou.

[[v41-15-24]]

^<<v41-15-24,24>>^ Então os soldados o pregaram na cruz. Depois, dividiram as roupas dele e tiraram sortes para decidir quem ficava com cada peça.

[[v41-15-25]]

^<<v41-15-25,25>>^ Eram nove horas da manhã quando o crucificaram.

[[v41-15-26]]

^<<v41-15-26,26>>^ Uma tabuleta anunciava a acusação feita contra ele: "O Rei dos Judeus".

[[v41-15-27]]

^<<v41-15-27,27>>^ Dois criminosos foram crucificados com ele, um à sua direita e outro à sua esquerda.

[[v41-15-28]]

^<<v41-15-28,28>>^ Assim, cumpriram-se as Escrituras que diziam: "Ele foi contado entre os rebeldes".

[[v41-15-29]]

^<<v41-15-29,29>>^ O povo que passava por ali gritava insultos e sacudia a cabeça em zombaria. "Olhe só!", gritavam. "Você disse que destruiria o templo e o reconstruiria em três dias.

[[v41-15-30]]

^<<v41-15-30,30>>^ Pois bem, salve a si mesmo e desça da cruz!"

[[v41-15-31]]

^<<v41-15-31,31>>^ Os principais sacerdotes e os mestres da lei também zombavam de Jesus. "Salvou os outros, mas não pode salvar a si mesmo!", diziam.

[[v41-15-32]]

^<<v41-15-32,32>>^ "Que esse Cristo, o rei de Israel, desça da cruz agora mesmo para que vejamos e creiamos nele!" Até os homens crucificados com Jesus o insultavam.

[[v41-15-33]]

^<<v41-15-33,33>>^ Ao meio-dia, desceu sobre toda a terra uma escuridão que durou três horas.

[[v41-15-34]]

^<<v41-15-34,34>>^ Por volta das três da tarde, Jesus clamou em alta voz: " Eloí, Eloí, lamá sabactâni? ", que quer dizer: "Meu Deus, meu Deus, por que me abandonaste?".

[[v41-15-35]]

^<<v41-15-35,35>>^ Alguns dos que estavam ali, ouvindo isso, disseram: "Ele está chamando Elias".

[[v41-15-36]]

^<<v41-15-36,36>>^ Um deles correu, ensopou uma esponja com vinagre e a ergueu num caniço para que ele bebesse. "Esperem!", disse ele. "Vamos ver se Elias vem tirá-lo daí."

[[v41-15-37]]

^<<v41-15-37,37>>^ Então Jesus clamou em alta voz e deu o último suspiro.

[[v41-15-38]]

^<<v41-15-38,38>>^ A cortina do santuário do templo se rasgou em duas partes, de cima até embaixo.

[[v41-15-39]]

^<<v41-15-39,39>>^ Quando o oficial romano que estava diante dele viu como ele havia morrido, exclamou: "Este homem era verdadeiramente o Filho de Deus!".

[[v41-15-40]]

^<<v41-15-40,40>>^ Algumas mulheres observavam de longe. Entre elas estavam Maria Madalena, Maria, mãe de Tiago, o mais jovem, e de José, e Salomé.

[[v41-15-41]]

^<<v41-15-41,41>>^ Eram seguidoras de Jesus e o haviam servido na Galileia. Também estavam ali muitas mulheres que foram com ele a Jerusalém.

[[v41-15-42]]

^<<v41-15-42,42>>^ Tudo isso aconteceu na sexta-feira, o dia da preparação, antes do sábado. Ao entardecer,

[[v41-15-43]]

^<<v41-15-43,43>>^ José de Arimateia foi corajosamente a Pilatos e pediu o corpo de Jesus. (José era um membro respeitado do conselho dos líderes do povo e esperava a chegada do reino de Deus.)

[[v41-15-44]]

^<<v41-15-44,44>>^ Surpreso com o fato de Jesus já estar morto, Pilatos chamou o oficial romano e perguntou se fazia muito tempo que ele havia morrido.

[[v41-15-45]]

^<<v41-15-45,45>>^ O oficial confirmou que Jesus estava morto, e Pilatos disse a José que podia levar o corpo.

[[v41-15-46]]

^<<v41-15-46,46>>^ José comprou um lençol de linho, desceu o corpo de Jesus da cruz, envolveu-o no lençol e colocou-o num túmulo escavado na rocha. Então rolou uma grande pedra na entrada do túmulo.

[[v41-15-47]]

^<<v41-15-47,47>>^ Maria Madalena e Maria, mãe de José, viram onde o corpo de Jesus tinha sido sepultado.

'''

xref:041-marcos/041-marcos-014.adoc#v41-14-0[&#60; Capítulo Anterior] | <<v41-15-0,Topo>> | xref:041-marcos/041-marcos-016.adoc#v41-16-0[Próximo Capítulo &#62;]