include::./index.adoc[]

[[v41-16-0]]
=== Marcos, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v41-16-1]]

^<<v41-16-1,1>>^ Ao entardecer do dia seguinte, terminado o sábado, Maria Madalena, Maria, mãe de Tiago, e Salomé foram comprar especiarias para ungir o corpo de Jesus.

[[v41-16-2]]

^<<v41-16-2,2>>^ No domingo de manhã, bem cedo, ao nascer do sol, elas foram ao túmulo.

[[v41-16-3]]

^<<v41-16-3,3>>^ No caminho, perguntavam umas às outras: "Quem removerá para nós a pedra da entrada do túmulo?".

[[v41-16-4]]

^<<v41-16-4,4>>^ Mas, quando chegaram, foram verificar e viram que a pedra, que era muito grande, já havia sido removida.

[[v41-16-5]]

^<<v41-16-5,5>>^ Ao entrarem no túmulo, viram um jovem vestido de branco sentado do lado direito. Ficaram assustadas,

[[v41-16-6]]

^<<v41-16-6,6>>^ mas ele disse: "Não tenham medo. Vocês procuram Jesus de Nazaré, que foi crucificado. Ele não está aqui. Ressuscitou! Vejam, este é o lugar onde haviam colocado seu corpo.

[[v41-16-7]]

^<<v41-16-7,7>>^ Agora vão e digam aos discípulos, incluindo Pedro, que Jesus vai adiante deles à Galileia. Vocês o verão lá, como ele lhes disse".

[[v41-16-8]]

^<<v41-16-8,8>>^ Trêmulas e desnorteadas, as mulheres fugiram do túmulo e não disseram coisa alguma a ninguém, pois estavam assustadas demais.

[[v41-16-9]]

^<<v41-16-9,9>>^ Quando Jesus ressuscitou dos mortos, no domingo de manhã, bem cedo, a primeira pessoa que o viu foi Maria Madalena, a mulher de quem ele havia expulsado sete demônios.

[[v41-16-10]]

^<<v41-16-10,10>>^ Ela foi aos discípulos, que lamentavam e choravam, e contou o que havia acontecido.

[[v41-16-11]]

^<<v41-16-11,11>>^ Quando ela disse que Jesus estava vivo e que o tinha visto, eles não acreditaram.

[[v41-16-12]]

^<<v41-16-12,12>>^ Depois, Jesus apareceu em outra forma a dois de seus seguidores, enquanto iam de Jerusalém para o campo.

[[v41-16-13]]

^<<v41-16-13,13>>^ Voltaram correndo para contar aos outros, mas eles não acreditaram.

[[v41-16-14]]

^<<v41-16-14,14>>^ Mais tarde, enquanto os onze discípulos comiam, Jesus lhes apareceu. Ele os repreendeu por sua incredulidade obstinada, pois se recusaram a crer naqueles que o tinham visto depois de sua ressurreição.

[[v41-16-15]]

^<<v41-16-15,15>>^ Jesus lhes disse: "Vão ao mundo inteiro e anunciem as boas-novas a todos.

[[v41-16-16]]

^<<v41-16-16,16>>^ Quem crer e for batizado será salvo, mas quem se recusar a crer será condenado.

[[v41-16-17]]

^<<v41-16-17,17>>^ Os seguintes sinais acompanharão aqueles que crerem: em meu nome expulsarão demônios, falarão em novas línguas,

[[v41-16-18]]

^<<v41-16-18,18>>^ pegarão em serpentes sem correr perigo, se beberem algo venenoso, não lhes fará mal, e colocarão as mãos sobre os enfermos e eles serão curados".

[[v41-16-19]]

^<<v41-16-19,19>>^ Quando o Senhor Jesus acabou de falar com eles, foi levado para o céu e sentou-se à direita de Deus.

[[v41-16-20]]

^<<v41-16-20,20>>^ Os discípulos foram a toda parte e anunciavam a mensagem, e o Senhor cooperava com eles, confirmando-a com muitos sinais.

'''

xref:041-marcos/041-marcos-015.adoc#v41-15-0[&#60; Capítulo Anterior] | <<v41-16-0,Topo>> | xref:042-lucas/042-lucas-001.adoc#v42-1-0[Próximo Capítulo &#62;]