include::./index.adoc[]

[[v41-11-0]]
=== Marcos, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v41-11-1]]

^<<v41-11-1,1>>^ Quando já se aproximavam de Jerusalém, Jesus e seus discípulos chegaram às cidades de Betfagé e Betânia, no monte das Oliveiras. Jesus enviou na frente dois discípulos.

[[v41-11-2]]

^<<v41-11-2,2>>^ "Vão àquele povoado adiante", disse ele. "Assim que entrarem, verão amarrado ali um jumentinho, no qual ninguém jamais montou. Desamarrem-no e tragam-no para cá.

[[v41-11-3]]

^<<v41-11-3,3>>^ Se alguém lhes perguntar: ‘O que estão fazendo?’, digam apenas: ‘O Senhor precisa dele e o devolverá em breve’."

[[v41-11-4]]

^<<v41-11-4,4>>^ Os dois discípulos foram e encontraram o jumentinho na rua, amarrado junto a uma porta.

[[v41-11-5]]

^<<v41-11-5,5>>^ Enquanto o desamarravam, algumas pessoas que estavam ali perguntaram: "O que vocês estão fazendo, desamarrando esse jumentinho?".

[[v41-11-6]]

^<<v41-11-6,6>>^ Responderam conforme Jesus havia instruído, e os deixaram levar o animal.

[[v41-11-7]]

^<<v41-11-7,7>>^ Os discípulos trouxeram o jumentinho, puseram seus mantos sobre o animal, e Jesus montou nele.

[[v41-11-8]]

^<<v41-11-8,8>>^ Muitos da multidão espalharam seus mantos ao longo do caminho diante de Jesus, e outros espalharam ramos que haviam cortado nos campos.

[[v41-11-9]]

^<<v41-11-9,9>>^ E as pessoas, tanto as que iam à frente como as que o seguiam, gritavam: "Hosana! Bendito é o que vem em nome do Senhor!

[[v41-11-10]]

^<<v41-11-10,10>>^ Bendito é o reino que vem, o reino de nosso antepassado Davi! Hosana no mais alto céu!".

[[v41-11-11]]

^<<v41-11-11,11>>^ Jesus entrou em Jerusalém e foi ao templo. Depois de olhar tudo ao redor atentamente, voltou a Betânia com os Doze, porque já era tarde.

[[v41-11-12]]

^<<v41-11-12,12>>^ Na manhã seguinte, quando saíam de Betânia, Jesus teve fome.

[[v41-11-13]]

^<<v41-11-13,13>>^ Viu que, a certa distância, havia uma figueira cheia de folhas e foi ver se encontraria figos. No entanto, só havia folhas, pois ainda não era tempo de dar frutos.

[[v41-11-14]]

^<<v41-11-14,14>>^ Então Jesus disse à árvore: "Nunca mais comam de seu fruto!". E os discípulos ouviram o que ele disse.

[[v41-11-15]]

^<<v41-11-15,15>>^ Quando voltaram a Jerusalém, Jesus entrou no templo e começou a expulsar os que compravam e vendiam animais para os sacrifícios. Derrubou as mesas dos cambistas e as cadeiras dos que vendiam pombas,

[[v41-11-16]]

^<<v41-11-16,16>>^ impediu todos de usarem o templo como mercado

[[v41-11-17]]

^<<v41-11-17,17>>^ e os ensinava, dizendo: "As Escrituras declaram: ‘Meu templo será chamado casa de oração para todas as nações’, mas vocês o transformaram num esconderijo de ladrões!".

[[v41-11-18]]

^<<v41-11-18,18>>^ Quando os principais sacerdotes e mestres da lei souberam o que Jesus tinha feito, começaram a tramar um modo de matá-lo. Contudo, tinham medo dele, pois o povo estava muito admirado com seu ensino.

[[v41-11-19]]

^<<v41-11-19,19>>^ Ao entardecer, Jesus e seus discípulos saíram da cidade.

[[v41-11-20]]

^<<v41-11-20,20>>^ Na manhã seguinte, quando os discípulos passaram pela figueira que Jesus tinha amaldiçoado, notaram que ela estava seca desde a raiz.

[[v41-11-21]]

^<<v41-11-21,21>>^ Pedro se lembrou do que Jesus tinha dito à árvore e exclamou: "Veja, Rabi! A figueira que o senhor amaldiçoou secou!".

[[v41-11-22]]

^<<v41-11-22,22>>^ Então Jesus disse aos discípulos: "Tenham fé em Deus.

[[v41-11-23]]

^<<v41-11-23,23>>^ Eu lhes digo a verdade: vocês poderão dizer a este monte: ‘Levante-se e atire-se no mar’, e isso acontecerá. É preciso, no entanto, crer que acontecerá, e não ter nenhuma dúvida em seu coração.

[[v41-11-24]]

^<<v41-11-24,24>>^ Digo-lhes que, se crerem que já receberam, qualquer coisa que pedirem em oração lhes será concedido.

[[v41-11-25]]

^<<v41-11-25,25>>^ Quando estiverem orando, se tiverem alguma coisa contra alguém, perdoem-no, para que seu Pai no céu também perdoe seus pecados.

[[v41-11-26]]

^<<v41-11-26,26>>^ Mas, se vocês se recusarem a perdoar, seu Pai no céu não perdoará seus pecados".

[[v41-11-27]]

^<<v41-11-27,27>>^ Mais uma vez, voltaram a Jerusalém. Enquanto Jesus passava pelo templo, os principais sacerdotes, os mestres da lei e os líderes do povo vieram até ele

[[v41-11-28]]

^<<v41-11-28,28>>^ e perguntaram: "Com que autoridade você faz essas coisas? Quem lhe deu esse direito?".

[[v41-11-29]]

^<<v41-11-29,29>>^ Jesus respondeu: "Eu lhes direi com que autoridade faço essas coisas se vocês responderem a uma pergunta:

[[v41-11-30]]

^<<v41-11-30,30>>^ A autoridade de João para batizar vinha do céu ou era apenas humana? Respondam-me!".

[[v41-11-31]]

^<<v41-11-31,31>>^ Eles discutiram a questão entre si: "Se dissermos que vinha do céu, ele perguntará por que não cremos em João.

[[v41-11-32]]

^<<v41-11-32,32>>^ Mas será que ousamos dizer que era apenas humana?". Tinham medo do que o povo faria, pois todos acreditavam que João era profeta.

[[v41-11-33]]

^<<v41-11-33,33>>^ Por fim, responderam: "Não sabemos". E Jesus replicou: "Então eu também não direi com que autoridade faço essas coisas".

'''

xref:041-marcos/041-marcos-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-marcos/041-marcos-012.adoc#v41-12-0[Próximo Capítulo &#62;]