include::./index.adoc[]

[[v41-10-0]]
=== Marcos, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v41-10-1]]

^<<v41-10-1,1>>^ Então Jesus deixou Cafarnaum e foi para a região da Judeia, a leste do rio Jordão. Mais uma vez, multidões se juntaram ao seu redor e, como de costume, ele as ensinava.

[[v41-10-2]]

^<<v41-10-2,2>>^ Alguns fariseus vieram e tentaram apanhar Jesus numa armadilha com a seguinte pergunta: "Deve-se permitir que um homem se divorcie de sua mulher?".

[[v41-10-3]]

^<<v41-10-3,3>>^ Jesus respondeu: "O que Moisés disse na lei a respeito do divórcio?".

[[v41-10-4]]

^<<v41-10-4,4>>^ "Ele o permitiu", responderam os fariseus. "Disse que um homem poderia dar à esposa um certificado de divórcio e mandá-la embora."

[[v41-10-5]]

^<<v41-10-5,5>>^ Jesus, porém, disse: "Moisés escreveu esse mandamento porque vocês têm o coração duro,

[[v41-10-6]]

^<<v41-10-6,6>>^ mas ‘Deus os fez homem e mulher’ desde o princípio da criação.

[[v41-10-7]]

^<<v41-10-7,7>>^ ‘Por isso o homem deixa pai e mãe e se une à sua mulher,

[[v41-10-8]]

^<<v41-10-8,8>>^ e os dois se tornam um só’. Uma vez que já não são dois, mas um só,

[[v41-10-9]]

^<<v41-10-9,9>>^ que ninguém separe o que Deus uniu".

[[v41-10-10]]

^<<v41-10-10,10>>^ Mais tarde, quando Jesus estava em casa com seus discípulos, eles tocaram no assunto outra vez.

[[v41-10-11]]

^<<v41-10-11,11>>^ Jesus respondeu: "Quem se divorcia de sua esposa e se casa com outra mulher comete adultério contra ela.

[[v41-10-12]]

^<<v41-10-12,12>>^ E, se a mulher se divorcia do marido e se casa com outro homem, comete adultério".

[[v41-10-13]]

^<<v41-10-13,13>>^ Certo dia, trouxeram crianças para que Jesus pusesse as mãos sobre elas, mas os discípulos repreendiam aqueles que as traziam.

[[v41-10-14]]

^<<v41-10-14,14>>^ Ao ver isso, Jesus ficou indignado com os discípulos e disse: "Deixem que as crianças venham a mim. Não as impeçam, pois o reino de Deus pertence aos que são como elas.

[[v41-10-15]]

^<<v41-10-15,15>>^ Eu lhes digo a verdade: quem não receber o reino de Deus como uma criança de modo algum entrará nele".

[[v41-10-16]]

^<<v41-10-16,16>>^ Então tomou as crianças nos braços, pôs as mãos sobre a cabeça delas e as abençoou.

[[v41-10-17]]

^<<v41-10-17,17>>^ Quando Jesus saía para Jerusalém, um homem veio correndo em sua direção, ajoelhou-se diante dele e perguntou: "Bom mestre, que devo fazer para herdar a vida eterna?".

[[v41-10-18]]

^<<v41-10-18,18>>^ "Por que você me chama de bom?", perguntou Jesus. "Apenas Deus é verdadeiramente bom.

[[v41-10-19]]

^<<v41-10-19,19>>^ Você conhece os mandamentos: ‘Não mate. Não cometa adultério. Não roube. Não dê falso testemunho. Não engane ninguém. Honre seu pai e sua mãe’."

[[v41-10-20]]

^<<v41-10-20,20>>^ O homem respondeu: "Mestre, tenho obedecido a todos esses mandamentos desde a juventude".

[[v41-10-21]]

^<<v41-10-21,21>>^ Com amor, Jesus olhou para o homem e disse: "Ainda há uma coisa que você não fez. Vá, venda todos os seus bens e dê o dinheiro aos pobres. Então você terá um tesouro no céu. Depois, venha e siga-me".

[[v41-10-22]]

^<<v41-10-22,22>>^ Ao ouvir isso, o homem ficou desapontado e foi embora triste, pois tinha muitos bens.

[[v41-10-23]]

^<<v41-10-23,23>>^ Jesus olhou ao redor e disse a seus discípulos: "Como é difícil os ricos entrarem no reino de Deus!".

[[v41-10-24]]

^<<v41-10-24,24>>^ Os discípulos se admiraram de suas palavras. Mas Jesus disse outra vez: "Filhos, entrar no reino de Deus é muito difícil.

[[v41-10-25]]

^<<v41-10-25,25>>^ É mais fácil um camelo passar pelo buraco de uma agulha que um rico entrar no reino de Deus".

[[v41-10-26]]

^<<v41-10-26,26>>^ Perplexos, os discípulos perguntaram: "Então quem pode ser salvo?".

[[v41-10-27]]

^<<v41-10-27,27>>^ Jesus olhou atentamente para eles e respondeu: "Para as pessoas isso é impossível, mas não para Deus. Para Deus, tudo é possível".

[[v41-10-28]]

^<<v41-10-28,28>>^ Então Pedro começou a falar: "Deixamos tudo para segui-lo".

[[v41-10-29]]

^<<v41-10-29,29>>^ Jesus respondeu: "Eu lhes garanto que todos que deixaram casa, irmãos, irmãs, mãe, pai, filhos ou propriedades por minha causa e por causa das boas-novas

[[v41-10-30]]

^<<v41-10-30,30>>^ receberão em troca, neste mundo, cem vezes mais casas, irmãos, irmãs, mães, filhos e propriedades, com perseguição, e, no mundo futuro, terão a vida eterna.

[[v41-10-31]]

^<<v41-10-31,31>>^ Contudo, muitos primeiros serão os últimos, e muitos últimos serão os primeiros".

[[v41-10-32]]

^<<v41-10-32,32>>^ Por esse tempo, subiam para Jerusalém, e Jesus ia à frente. Os discípulos estavam muito admirados, e o povo que os seguia tinha grande temor. Jesus chamou os Doze à parte e, mais uma vez, começou a descrever tudo que estava prestes a lhe acontecer.

[[v41-10-33]]

^<<v41-10-33,33>>^ "Ouçam", disse ele. "Estamos subindo para Jerusalém, onde o Filho do Homem será traído e entregue aos principais sacerdotes e aos mestres da lei. Eles o condenarão à morte e o entregarão aos gentios.

[[v41-10-34]]

^<<v41-10-34,34>>^ Zombarão dele, cuspirão nele, o açoitarão e o matarão, mas depois de três dias ele ressuscitará."

[[v41-10-35]]

^<<v41-10-35,35>>^ Então Tiago e João, filhos de Zebedeu, vieram e falaram com ele: "Mestre, queremos que nos faça um favor".

[[v41-10-36]]

^<<v41-10-36,36>>^ "Que favor é esse?", perguntou ele.

[[v41-10-37]]

^<<v41-10-37,37>>^ Eles responderam: "Quando o senhor se sentar em seu trono glorioso, queremos nos sentar em lugares de honra ao seu lado, um à sua direita e outro à sua esquerda".

[[v41-10-38]]

^<<v41-10-38,38>>^ Jesus lhes disse: "Vocês não sabem o que estão pedindo! São capazes de beber do cálice que beberei? São capazes de ser batizados com o batismo com que serei batizado?".

[[v41-10-39]]

^<<v41-10-39,39>>^ "Somos!", responderam eles. Então Jesus disse: "De fato, vocês beberão do meu cálice e serão batizados com o meu batismo.

[[v41-10-40]]

^<<v41-10-40,40>>^ Não cabe a mim, no entanto, dizer quem se sentará à minha direita ou à minha esquerda. Esses lugares serão daqueles para quem eles foram preparados".

[[v41-10-41]]

^<<v41-10-41,41>>^ Quando os outros dez discípulos ouviram o que Tiago e João haviam pedido, ficaram indignados.

[[v41-10-42]]

^<<v41-10-42,42>>^ Então Jesus os reuniu e disse: "Vocês sabem que os que são considerados líderes neste mundo têm poder sobre o povo, e que os oficiais exercem sua autoridade sobre os súditos.

[[v41-10-43]]

^<<v41-10-43,43>>^ Entre vocês, porém, será diferente. Quem quiser ser o líder entre vocês, que seja servo,

[[v41-10-44]]

^<<v41-10-44,44>>^ e quem quiser ser o primeiro entre vocês, que se torne escravo de todos.

[[v41-10-45]]

^<<v41-10-45,45>>^ Pois nem mesmo o Filho do Homem veio para ser servido, mas para servir e dar sua vida em resgate por muitos".

[[v41-10-46]]

^<<v41-10-46,46>>^ Então chegaram a Jericó. Quando Jesus e seus discípulos saíam da cidade, uma grande multidão os seguiu. Um mendigo cego chamado Bartimeu, filho de Timeu, estava sentado à beira do caminho.

[[v41-10-47]]

^<<v41-10-47,47>>^ Quando Bartimeu soube que Jesus de Nazaré estava perto, começou a gritar: "Jesus, Filho de Davi, tenha misericórdia de mim!".

[[v41-10-48]]

^<<v41-10-48,48>>^ Muitos lhe diziam aos brados: "Cale-se!". Ele, porém, gritava ainda mais alto: "Filho de Davi, tenha misericórdia de mim!".

[[v41-10-49]]

^<<v41-10-49,49>>^ Quando Jesus o ouviu, parou e disse: "Falem para ele vir aqui". Então chamaram o cego. "Anime-se!", disseram. "Venha, ele o está chamando!"

[[v41-10-50]]

^<<v41-10-50,50>>^ Bartimeu jogou sua capa para o lado, levantou-se de um salto e foi até Jesus.

[[v41-10-51]]

^<<v41-10-51,51>>^ "O que você quer que eu lhe faça?", perguntou Jesus. O cego respondeu: "Rabi, quero enxergar".

[[v41-10-52]]

^<<v41-10-52,52>>^ Jesus lhe disse: "Vá, pois sua fé o curou". No mesmo instante, o homem passou a ver e seguiu Jesus pelo caminho.

'''

xref:041-marcos/041-marcos-009.adoc#v41-9-0[&#60; Capítulo Anterior] | <<v41-10-0,Topo>> | xref:041-marcos/041-marcos-011.adoc#v41-11-0[Próximo Capítulo &#62;]