include::./index.adoc[]

[[v41-9-0]]
=== Marcos, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v41-9-1]]

^<<v41-9-1,1>>^ Jesus prosseguiu: "Eu lhes digo a verdade: alguns que estão aqui neste momento não morrerão antes de ver o reino de Deus vindo com grande poder!".

[[v41-9-2]]

^<<v41-9-2,2>>^ Seis dias depois, Jesus levou consigo Pedro, Tiago e João até um monte alto, para estarem a sós. Ali, diante de seus olhos, a aparência de Jesus foi transformada.

[[v41-9-3]]

^<<v41-9-3,3>>^ Suas roupas ficaram brancas e resplandecentes, muito mais claras do que qualquer lavandeiro seria capaz de deixá-las.

[[v41-9-4]]

^<<v41-9-4,4>>^ Então Elias e Moisés apareceram e começaram a falar com Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ Pedro exclamou: "Rabi, é maravilhoso estarmos aqui! Vamos fazer três tendas: uma será sua, uma de Moisés e outra de Elias".

[[v41-9-6]]

^<<v41-9-6,6>>^ Disse isso porque não sabia o que mais falar, pois estavam todos apavorados.

[[v41-9-7]]

^<<v41-9-7,7>>^ Então uma nuvem os cobriu, e uma voz que vinha da nuvem disse: "Este é meu Filho amado. Ouçam-no!".

[[v41-9-8]]

^<<v41-9-8,8>>^ De repente, quando olharam em volta, só Jesus estava com eles.

[[v41-9-9]]

^<<v41-9-9,9>>^ Enquanto desciam o monte, Jesus ordenou que não contassem a ninguém o que tinham visto, até que o Filho do Homem tivesse ressuscitado dos mortos.

[[v41-9-10]]

^<<v41-9-10,10>>^ Eles guardaram segredo, mas conversavam entre si com frequência sobre o que ele queria dizer com "ressuscitar dos mortos".

[[v41-9-11]]

^<<v41-9-11,11>>^ Então eles perguntaram a Jesus: "Por que os mestres da lei afirmam que é necessário que Elias volte antes que o Cristo venha?".

[[v41-9-12]]

^<<v41-9-12,12>>^ Jesus respondeu: "De fato, Elias vem primeiro para restaurar tudo. Então por que as Escrituras dizem que é necessário o Filho do Homem sofrer muito e ser tratado com desprezo?

[[v41-9-13]]

^<<v41-9-13,13>>^ Eu, porém, lhes digo: Elias já veio e eles preferiram maltratá-lo, conforme as Escrituras haviam previsto".

[[v41-9-14]]

^<<v41-9-14,14>>^ Ao voltarem para junto dos outros discípulos, viram que estavam cercados por uma grande multidão e que alguns mestres da lei discutiam com eles.

[[v41-9-15]]

^<<v41-9-15,15>>^ Quando a multidão viu Jesus, ficou muito admirada e correu para cumprimentá-lo.

[[v41-9-16]]

^<<v41-9-16,16>>^ "Sobre o que discutem?", perguntou Jesus.

[[v41-9-17]]

^<<v41-9-17,17>>^ Um dos homens na multidão respondeu: "Mestre, eu lhe trouxe meu filho, que está possuído por um espírito impuro que não o deixa falar.

[[v41-9-18]]

^<<v41-9-18,18>>^ Sempre que o espírito se apodera dele, joga-o no chão, e ele espuma pela boca, range os dentes e fica rígido. Pedi a seus discípulos que expulsassem o espírito impuro, mas eles não conseguiram".

[[v41-9-19]]

^<<v41-9-19,19>>^ Jesus lhes disse: "Geração incrédula! Até quando estarei com vocês? Até quando terei de suportá-los? Tragam o menino para cá".

[[v41-9-20]]

^<<v41-9-20,20>>^ Então o trouxeram. Quando o espírito impuro viu Jesus, causou uma convulsão intensa no menino e ele caiu no chão, contorcendo-se e espumando pela boca.

[[v41-9-21]]

^<<v41-9-21,21>>^ Jesus perguntou ao pai do menino: "Há quanto tempo isso acontece com ele?". "Desde que ele era pequeno", respondeu o pai.

[[v41-9-22]]

^<<v41-9-22,22>>^ "Muitas vezes o espírito o lança no fogo ou na água e tenta matá-lo. Tenha misericórdia de nós e ajude-nos, se puder."

[[v41-9-23]]

^<<v41-9-23,23>>^ "Se puder?", perguntou Jesus. "Tudo é possível para aquele que crê."

[[v41-9-24]]

^<<v41-9-24,24>>^ No mesmo instante, o pai respondeu: "Eu creio, mas ajude-me a superar minha incredulidade".

[[v41-9-25]]

^<<v41-9-25,25>>^ Quando Jesus viu que a multidão aumentava, repreendeu o espírito impuro, dizendo: "Espírito que impede este menino de ouvir e falar, ordeno que saia e nunca mais entre nele!".

[[v41-9-26]]

^<<v41-9-26,26>>^ O espírito gritou, causou outra convulsão intensa no menino e saiu dele. O menino parecia morto. Um murmúrio correu pela multidão: "Ele morreu".

[[v41-9-27]]

^<<v41-9-27,27>>^ Mas Jesus o tomou pela mão e o ajudou a se levantar, e ele ficou em pé.

[[v41-9-28]]

^<<v41-9-28,28>>^ Depois, quando Jesus estava em casa com seus discípulos, eles perguntaram: "Por que não conseguimos expulsar aquele espírito impuro?".

[[v41-9-29]]

^<<v41-9-29,29>>^ Jesus respondeu: "Essa espécie só sai com oração".

[[v41-9-30]]

^<<v41-9-30,30>>^ Ao deixarem aquela região, viajaram pela Galileia. Jesus não queria que ninguém soubesse que ele estava lá,

[[v41-9-31]]

^<<v41-9-31,31>>^ pois queria ensinar a seus discípulos. Ele lhes dizia: "O Filho do Homem será traído e entregue em mãos humanas. Será morto, mas três dias depois ressuscitará".

[[v41-9-32]]

^<<v41-9-32,32>>^ Eles, porém, não entendiam essas coisas e tinham medo de lhe perguntar.

[[v41-9-33]]

^<<v41-9-33,33>>^ Depois que chegaram a Cafarnaum e se acomodaram numa casa, Jesus perguntou a seus discípulos: "Sobre o que vocês discutiam no caminho?".

[[v41-9-34]]

^<<v41-9-34,34>>^ Eles não responderam, pois tinham discutido sobre qual deles era o maior.

[[v41-9-35]]

^<<v41-9-35,35>>^ Jesus se sentou, chamou os Doze e disse: "Quem quiser ser o primeiro, que se torne o último e seja servo de todos".

[[v41-9-36]]

^<<v41-9-36,36>>^ Então colocou uma criança no meio deles, tomou-a nos braços e disse:

[[v41-9-37]]

^<<v41-9-37,37>>^ "Quem recebe uma criança pequena como esta em meu nome recebe a mim, e quem me recebe não recebe apenas a mim, mas também ao Pai, que me enviou".

[[v41-9-38]]

^<<v41-9-38,38>>^ João disse a Jesus: "Mestre, vimos alguém usar seu nome para expulsar demônios; nós o proibimos, pois ele não era do nosso grupo".

[[v41-9-39]]

^<<v41-9-39,39>>^ "Não o proíbam!", disse Jesus. "Ninguém que faça milagres em meu nome falará mal de mim a seguir.

[[v41-9-40]]

^<<v41-9-40,40>>^ Quem não é contra nós é a favor de nós.

[[v41-9-41]]

^<<v41-9-41,41>>^ Eu lhes digo a verdade: se alguém lhes der um simples copo de água porque vocês são seguidores do Cristo, essa pessoa certamente será recompensada.

[[v41-9-42]]

^<<v41-9-42,42>>^ "Mas, se alguém fizer um destes pequeninos que confiam em mim cair em pecado, seria melhor que lhe amarrassem ao pescoço uma grande pedra de moinho e fosse jogado ao mar.

[[v41-9-43]]

^<<v41-9-43,43>>^ Se sua mão o leva a pecar, corte-a fora. É melhor entrar na vida eterna com apenas uma das mãos que ser lançado no fogo inextinguível do inferno com as duas mãos.

[[v41-9-44]]

^<<v41-9-44,44>>^ Lá os vermes nunca morrem e o fogo nunca se apaga.

[[v41-9-45]]

^<<v41-9-45,45>>^ Se seu pé o leva a pecar, corte-o fora. É melhor entrar na vida eterna com apenas um pé que ser lançado no inferno com os dois pés.

[[v41-9-46]]

^<<v41-9-46,46>>^ Lá os vermes nunca morrem e o fogo nunca se apaga.

[[v41-9-47]]

^<<v41-9-47,47>>^ E, se seu olho o leva a pecar, lance-o fora. É melhor entrar no reino de Deus com apenas um dos olhos que ter os dois olhos e ser lançado no inferno.

[[v41-9-48]]

^<<v41-9-48,48>>^ Lá os vermes nunca morrem e o fogo nunca se apaga.

[[v41-9-49]]

^<<v41-9-49,49>>^ "Pois cada um será provado com fogo.

[[v41-9-50]]

^<<v41-9-50,50>>^ O sal é bom para temperar, mas, se perder o sabor, como torná-lo salgado outra vez? Tenham entre vocês as qualidades do bom sal e vivam em paz uns com os outros."

'''

xref:041-marcos/041-marcos-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-marcos/041-marcos-010.adoc#v41-10-0[Próximo Capítulo &#62;]