include::./index.adoc[]

[[v41-13-0]]
=== Marcos, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v41-13-1]]

^<<v41-13-1,1>>^ Quando Jesus saía do templo, um de seus discípulos disse: "Mestre, olhe que construções magníficas! Que pedras impressionantes!".

[[v41-13-2]]

^<<v41-13-2,2>>^ Jesus respondeu: "Está vendo estas grandes construções? Serão completamente destruídas. Não restará pedra sobre pedra!".

[[v41-13-3]]

^<<v41-13-3,3>>^ Mais tarde, Jesus sentou-se no monte das Oliveiras, do outro lado do vale, de frente para o templo. Pedro, Tiago, João e André vieram e lhe perguntaram em particular:

[[v41-13-4]]

^<<v41-13-4,4>>^ "Diga-nos, quando isso tudo vai acontecer? Que sinais indicarão que essas coisas estão prestes a se cumprir?".

[[v41-13-5]]

^<<v41-13-5,5>>^ Jesus respondeu: "Não deixem que ninguém os engane,

[[v41-13-6]]

^<<v41-13-6,6>>^ pois muitos virão em meu nome, dizendo: ‘Eu sou o Cristo’, e enganarão muitos.

[[v41-13-7]]

^<<v41-13-7,7>>^ Vocês ouvirão falar de guerras e ameaças de guerras, mas não entrem em pânico. Sim, é necessário que essas coisas ocorram, mas ainda não será o fim.

[[v41-13-8]]

^<<v41-13-8,8>>^ Uma nação guerreará contra a outra, e um reino contra o outro. Haverá terremotos em vários lugares, e também fome. Tudo isso, porém, será apenas o começo das dores de parto.

[[v41-13-9]]

^<<v41-13-9,9>>^ "Tenham cuidado! Vocês serão entregues aos tribunais e açoitados nas sinagogas. Por minha causa, serão julgados diante de governadores e reis. Essa será sua oportunidade de lhes falar a meu respeito.

[[v41-13-10]]

^<<v41-13-10,10>>^ É necessário, primeiro, que as boas-novas sejam anunciadas a todas as nações.

[[v41-13-11]]

^<<v41-13-11,11>>^ Quando forem presos e julgados, não se preocupem com o que dirão. Falem apenas o que lhes for concedido naquele momento, pois não serão vocês que falarão, mas o Espírito Santo.

[[v41-13-12]]

^<<v41-13-12,12>>^ "O irmão trairá seu irmão e o entregará à morte, e assim também o pai a seu próprio filho. Os filhos se rebelarão contra os pais e os matarão.

[[v41-13-13]]

^<<v41-13-13,13>>^ Todos os odiarão por minha causa, mas quem se mantiver firme até o fim será salvo.

[[v41-13-14]]

^<<v41-13-14,14>>^ "Chegará o dia em que vocês verão a ‘terrível profanação’ no lugar onde não deveria estar. (Leitor, preste atenção!) Então, quem estiver na Judeia, fuja para os montes.

[[v41-13-15]]

^<<v41-13-15,15>>^ Quem estiver na parte de cima da casa, não desça nem entre para pegar coisa alguma.

[[v41-13-16]]

^<<v41-13-16,16>>^ Quem estiver no campo, não volte nem para pegar o manto.

[[v41-13-17]]

^<<v41-13-17,17>>^ Que terríveis serão aqueles dias para as grávidas e para as mães que estiverem amamentando!

[[v41-13-18]]

^<<v41-13-18,18>>^ Orem para que a fuga de vocês não aconteça no inverno,

[[v41-13-19]]

^<<v41-13-19,19>>^ pois haverá mais angústia naqueles dias que em qualquer outra ocasião desde que Deus criou o mundo, e nunca mais haverá angústia tão grande.

[[v41-13-20]]

^<<v41-13-20,20>>^ De fato, se o Senhor não tivesse limitado esse tempo, ninguém sobreviveria, mas, por causa de seus escolhidos, ele limitou aqueles dias.

[[v41-13-21]]

^<<v41-13-21,21>>^ "Portanto, se alguém lhes disser: ‘Vejam, aqui está o Cristo!’ ou ‘Vejam, ali está ele!’, não acreditem,

[[v41-13-22]]

^<<v41-13-22,22>>^ pois falsos cristos e falsos profetas surgirão e realizarão sinais e maravilhas a fim de enganar, se possível, até os escolhidos.

[[v41-13-23]]

^<<v41-13-23,23>>^ Fiquem atentos! Eu os avisei a esse respeito de antemão.

[[v41-13-24]]

^<<v41-13-24,24>>^ "Naquele tempo, depois da angústia daqueles dias, ‘o sol escurecerá, a lua não dará luz,

[[v41-13-25]]

^<<v41-13-25,25>>^ as estrelas cairão do céu, e os poderes dos céus serão abalados’.

[[v41-13-26]]

^<<v41-13-26,26>>^ Então todos verão o Filho do Homem vindo nas nuvens com grande poder e glória.

[[v41-13-27]]

^<<v41-13-27,27>>^ Ele enviará seus anjos para reunir seus escolhidos de todas as partes do mundo, das extremidades da terra às extremidades do céu.

[[v41-13-28]]

^<<v41-13-28,28>>^ "Agora, aprendam a lição da figueira. Quando surgem seus ramos e suas folhas começam a brotar, vocês sabem que o verão está próximo.

[[v41-13-29]]

^<<v41-13-29,29>>^ Da mesma forma, quando virem todas essas coisas, saberão que o tempo está muito próximo, à porta.

[[v41-13-30]]

^<<v41-13-30,30>>^ Eu lhes digo a verdade: esta geração certamente não passará até que todas essas coisas tenham acontecido.

[[v41-13-31]]

^<<v41-13-31,31>>^ O céu e a terra desaparecerão, mas as minhas palavras jamais desaparecerão.

[[v41-13-32]]

^<<v41-13-32,32>>^ "Contudo, ninguém sabe o dia nem a hora em que essas coisas acontecerão, nem mesmo os anjos no céu, nem o Filho. Somente o Pai sabe.

[[v41-13-33]]

^<<v41-13-33,33>>^ E, uma vez que vocês não sabem quando virá esse tempo, vigiem! Fiquem atentos!

[[v41-13-34]]

^<<v41-13-34,34>>^ "A vinda do Filho do Homem pode ser ilustrada pela história de um homem que partiu numa longa viagem. Quando saiu de casa, deu instruções a cada um de seus servos sobre o que fazer e disse ao porteiro que vigiasse, à espera de sua volta.

[[v41-13-35]]

^<<v41-13-35,35>>^ Vocês também devem vigiar! Pois não sabem quando o dono da casa voltará: à tarde, à meia-noite, de madrugada ou ao amanhecer.

[[v41-13-36]]

^<<v41-13-36,36>>^ Que ele não os encontre dormindo quando chegar sem aviso.

[[v41-13-37]]

^<<v41-13-37,37>>^ Eu lhes digo o que digo a todos: vigiem!".

'''

xref:041-marcos/041-marcos-012.adoc#v41-12-0[&#60; Capítulo Anterior] | <<v41-13-0,Topo>> | xref:041-marcos/041-marcos-014.adoc#v41-14-0[Próximo Capítulo &#62;]