include::./index.adoc[]

[[v41-14-0]]
=== Marcos, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v41-14-1]]

^<<v41-14-1,1>>^ Faltavam dois dias para a Páscoa e para a Festa dos Pães sem Fermento. Os principais sacerdotes e mestres da lei ainda procuravam uma oportunidade de prender Jesus em segredo e matá-lo.

[[v41-14-2]]

^<<v41-14-2,2>>^ "Mas não durante a festa da Páscoa, para não haver tumulto entre o povo", concordaram entre eles.

[[v41-14-3]]

^<<v41-14-3,3>>^ Enquanto isso, Jesus estava em Betânia, na casa de Simão, o leproso. Quando ele estava à mesa, uma mulher entrou com um frasco de alabastro contendo um perfume caro, feito de essência de nardo. Ela quebrou o frasco e derramou o perfume sobre a cabeça dele.

[[v41-14-4]]

^<<v41-14-4,4>>^ Alguns dos que estavam à mesa ficaram indignados. "Por que desperdiçar um perfume tão caro?", perguntaram.

[[v41-14-5]]

^<<v41-14-5,5>>^ "Poderia ter sido vendido por trezentas moedas de prata, e o dinheiro, dado aos pobres!" E repreenderam a mulher severamente.

[[v41-14-6]]

^<<v41-14-6,6>>^ Jesus, porém, disse: "Deixem-na em paz. Por que a criticam por ter feito algo tão bom para mim?

[[v41-14-7]]

^<<v41-14-7,7>>^ Vocês sempre terão os pobres em seu meio e poderão ajudá-los sempre que desejarem, mas nem sempre terão a mim.

[[v41-14-8]]

^<<v41-14-8,8>>^ Ela fez o que podia e ungiu meu corpo de antemão para o sepultamento.

[[v41-14-9]]

^<<v41-14-9,9>>^ "Eu lhes digo a verdade: onde quer que as boas-novas sejam anunciadas pelo mundo, o que esta mulher fez será contado, e dela se lembrarão".

[[v41-14-10]]

^<<v41-14-10,10>>^ Então Judas Iscariotes, um dos Doze, foi aos principais sacerdotes para combinar de lhes entregar Jesus.

[[v41-14-11]]

^<<v41-14-11,11>>^ Quando souberam por que ele tinha vindo, ficaram muito satisfeitos e lhe prometeram dinheiro. Então ele começou a procurar uma oportunidade para trair Jesus.

[[v41-14-12]]

^<<v41-14-12,12>>^ No primeiro dia da Festa dos Pães sem Fermento, quando o cordeiro pascal era sacrificado, os discípulos de Jesus lhe perguntaram: "Onde quer que lhe preparemos a refeição da Páscoa?".

[[v41-14-13]]

^<<v41-14-13,13>>^ Então Jesus enviou dois deles a Jerusalém, com as seguintes instruções: "Ao entrarem na cidade, um homem carregando uma vasilha de água virá ao seu encontro. Sigam-no.

[[v41-14-14]]

^<<v41-14-14,14>>^ Digam ao dono da casa em que ele entrar: ‘O Mestre pergunta: Onde fica o aposento no qual comerei a refeição da Páscoa com meus discípulos?’.

[[v41-14-15]]

^<<v41-14-15,15>>^ Ele os levará a uma sala grande no andar superior, que já estará arrumada. Preparem ali a refeição".

[[v41-14-16]]

^<<v41-14-16,16>>^ Então os dois discípulos foram à cidade e encontraram tudo como Jesus tinha dito, e ali prepararam a refeição da Páscoa.

[[v41-14-17]]

^<<v41-14-17,17>>^ Ao anoitecer, Jesus chegou com os Doze.

[[v41-14-18]]

^<<v41-14-18,18>>^ Quando estavam à mesa, comendo, Jesus disse: ‘Eu lhes digo a verdade: um de vocês que está aqui comendo comigo vai me trair".

[[v41-14-19]]

^<<v41-14-19,19>>^ Aflitos, eles protestaram: "Certamente não serei eu!".

[[v41-14-20]]

^<<v41-14-20,20>>^ Jesus respondeu: "É um dos Doze. É alguém que come comigo da mesma tigela.

[[v41-14-21]]

^<<v41-14-21,21>>^ Pois o Filho do Homem deve morrer, como as Escrituras declararam há muito tempo. Mas que terrível será para aquele que o trair! Para esse homem seria melhor não ter nascido".

[[v41-14-22]]

^<<v41-14-22,22>>^ Enquanto comiam, Jesus tomou o pão e o abençoou. Em seguida, partiu-o em pedaços e deu aos discípulos, dizendo: "Tomem, porque este é o meu corpo".

[[v41-14-23]]

^<<v41-14-23,23>>^ Então tomou o cálice de vinho e agradeceu a Deus. Depois, entregou-o aos discípulos, e todos beberam.

[[v41-14-24]]

^<<v41-14-24,24>>^ Então Jesus disse: "Este é o meu sangue, que confirma a aliança. Ele é derramado como sacrifício por muitos.

[[v41-14-25]]

^<<v41-14-25,25>>^ Eu lhes digo a verdade: não voltarei a beber vinho até aquele dia em que beberei um vinho novo no reino de Deus".

[[v41-14-26]]

^<<v41-14-26,26>>^ Então cantaram um hino e saíram para o monte das Oliveiras.

[[v41-14-27]]

^<<v41-14-27,27>>^ No caminho, Jesus disse: "Todos vocês me abandonarão, pois as Escrituras dizem: ‘Deus ferirá o pastor, e as ovelhas serão dispersas’.

[[v41-14-28]]

^<<v41-14-28,28>>^ Mas, depois de ressuscitar, irei adiante de vocês à Galileia".

[[v41-14-29]]

^<<v41-14-29,29>>^ Pedro declarou: "Mesmo que todos os outros o abandonem, eu jamais farei isso".

[[v41-14-30]]

^<<v41-14-30,30>>^ Jesus respondeu: "Eu lhe digo a verdade: esta mesma noite, antes que o galo cante duas vezes, você me negará três vezes".

[[v41-14-31]]

^<<v41-14-31,31>>^ Pedro, no entanto, insistiu enfaticamente: "Mesmo que eu tenha de morrer ao seu lado, jamais o negarei!". E todos os outros discípulos disseram o mesmo.

[[v41-14-32]]

^<<v41-14-32,32>>^ Então foram a um lugar chamado Getsêmani, e Jesus disse a seus discípulos: "Sentem-se aqui enquanto vou orar".

[[v41-14-33]]

^<<v41-14-33,33>>^ Levou consigo Pedro, Tiago e João e começou a sentir grande pavor e angústia.

[[v41-14-34]]

^<<v41-14-34,34>>^ "Minha alma está profundamente triste, a ponto de morrer", disse ele. "Fiquem aqui e vigiem."

[[v41-14-35]]

^<<v41-14-35,35>>^ Ele avançou um pouco e curvou-se até o chão. Então orou para que, se possível, a hora que o esperava fosse afastada dele.

[[v41-14-36]]

^<<v41-14-36,36>>^ E clamou: "Aba, Pai, tudo é possível para ti. Peço que afastes de mim este cálice. Contudo, que seja feita a tua vontade, e não a minha".

[[v41-14-37]]

^<<v41-14-37,37>>^ Depois, voltou aos discípulos e os encontrou dormindo. "Simão, você está dormindo?", disse ele a Pedro. "Não pode vigiar comigo nem por uma hora?

[[v41-14-38]]

^<<v41-14-38,38>>^ Vigiem e orem para que não cedam à tentação, pois o espírito está disposto, mas a carne é fraca."

[[v41-14-39]]

^<<v41-14-39,39>>^ Então os deixou novamente e fez a mesma oração de antes.

[[v41-14-40]]

^<<v41-14-40,40>>^ Quando voltou pela segunda vez, mais uma vez encontrou os discípulos dormindo, pois não conseguiam manter os olhos abertos. Eles não sabiam o que dizer.

[[v41-14-41]]

^<<v41-14-41,41>>^ Ao voltar pela terceira vez, disse: "Vocês ainda dormem e descansam? Basta; chegou a hora. O Filho do Homem está para ser entregue nas mãos de pecadores.

[[v41-14-42]]

^<<v41-14-42,42>>^ Levantem-se e vamos. Meu traidor chegou".

[[v41-14-43]]

^<<v41-14-43,43>>^ No mesmo instante, enquanto Jesus ainda falava, Judas, um dos Doze, chegou com uma multidão armada de espadas e pedaços de pau. Tinham sido enviados pelos principais sacerdotes, mestres da lei e líderes do povo.

[[v41-14-44]]

^<<v41-14-44,44>>^ O traidor havia combinado com eles um sinal: "Vocês saberão a quem devem prender quando eu o cumprimentar com um beijo. Então poderão levá-lo em segurança".

[[v41-14-45]]

^<<v41-14-45,45>>^ Assim que chegaram, Judas se aproximou de Jesus. "Rabi!", exclamou ele, e o beijou.

[[v41-14-46]]

^<<v41-14-46,46>>^ Os outros agarraram Jesus e o prenderam.

[[v41-14-47]]

^<<v41-14-47,47>>^ Mas um dos que estavam com Jesus puxou a espada e feriu o servo do sumo sacerdote, cortando-lhe a orelha.

[[v41-14-48]]

^<<v41-14-48,48>>^ Jesus perguntou: "Por acaso sou um revolucionário perigoso, para que venham me prender com espadas e pedaços de pau?

[[v41-14-49]]

^<<v41-14-49,49>>^ Por que não me prenderam no templo? Todos os dias estive ali, no meio de vocês, ensinando. Mas estas coisas estão acontecendo para que se cumpra o que dizem as Escrituras".

[[v41-14-50]]

^<<v41-14-50,50>>^ Então todos o abandonaram e fugiram.

[[v41-14-51]]

^<<v41-14-51,51>>^ Um jovem que os seguia vestia apenas um lençol de linho. Quando a multidão tentou agarrá-lo,

[[v41-14-52]]

^<<v41-14-52,52>>^ ele deixou para trás o lençol e escapou nu.

[[v41-14-53]]

^<<v41-14-53,53>>^ Levaram Jesus para a casa do sumo sacerdote, onde estavam reunidos os principais sacerdotes, os líderes do povo e os mestres da lei.

[[v41-14-54]]

^<<v41-14-54,54>>^ Pedro seguia Jesus de longe e entrou no pátio do sumo sacerdote. Ali, sentou-se com os guardas para se aquecer junto ao fogo.

[[v41-14-55]]

^<<v41-14-55,55>>^ Lá dentro, os principais sacerdotes e todo o conselho dos líderes do povo tentavam, sem sucesso, encontrar provas contra Jesus, para que pudessem condená-lo à morte.

[[v41-14-56]]

^<<v41-14-56,56>>^ Muitas testemunhas falsas deram depoimentos, mas elas se contradiziam.

[[v41-14-57]]

^<<v41-14-57,57>>^ Por fim, alguns homens se levantaram e apresentaram o seguinte testemunho falso:

[[v41-14-58]]

^<<v41-14-58,58>>^ "Nós o ouvimos dizer: ‘Destruirei este templo feito por mãos humanas e em três dias construirei outro, não feito por mãos humanas’".

[[v41-14-59]]

^<<v41-14-59,59>>^ Mas nem assim seus depoimentos eram coerentes.

[[v41-14-60]]

^<<v41-14-60,60>>^ Então o sumo sacerdote se levantou diante dos demais e perguntou a Jesus: "Você não vai responder a essas acusações? O que tem a dizer em sua defesa?".

[[v41-14-61]]

^<<v41-14-61,61>>^ Jesus, no entanto, permaneceu calado e não deu resposta alguma. Então o sumo sacerdote perguntou: "Você é o Cristo, o Filho do Deus Bendito?".

[[v41-14-62]]

^<<v41-14-62,62>>^ "Eu sou", disse Jesus. "E vocês verão o Filho do Homem sentado à direita do Deus Poderoso e vindo sobre as nuvens do céu."

[[v41-14-63]]

^<<v41-14-63,63>>^ Então o sumo sacerdote rasgou as vestes e disse: "Que necessidade temos de outras testemunhas?

[[v41-14-64]]

^<<v41-14-64,64>>^ Todos ouviram a blasfêmia. Qual é o veredicto?". E todos o julgaram culpado e o condenaram à morte.

[[v41-14-65]]

^<<v41-14-65,65>>^ Então alguns deles começaram a cuspir em Jesus. Vendaram seus olhos e lhe deram socos. "Profetize para nós!", zombavam. E os guardas lhe davam tapas enquanto o levavam.

[[v41-14-66]]

^<<v41-14-66,66>>^ Enquanto isso, Pedro estava lá embaixo, no pátio. Uma das criadas que trabalhava para o sumo sacerdote passou por ali

[[v41-14-67]]

^<<v41-14-67,67>>^ e viu Pedro se aquecendo junto ao fogo. Olhou bem para ele e disse: "Você é um dos que estavam com Jesus de Nazaré".

[[v41-14-68]]

^<<v41-14-68,68>>^ Ele, porém, negou. "Não faço a menor ideia do que você está falando!", disse, e caminhou em direção à saída. Naquele instante, o galo cantou.

[[v41-14-69]]

^<<v41-14-69,69>>^ Quando a criada o viu ali, começou a dizer aos outros: "Este homem com certeza é um deles!".

[[v41-14-70]]

^<<v41-14-70,70>>^ Mas Pedro negou novamente. Um pouco mais tarde, alguns dos que estavam por lá confrontaram Pedro, dizendo: "Você deve ser um deles, pois é galileu".

[[v41-14-71]]

^<<v41-14-71,71>>^ Ele, porém, começou a praguejar e jurou: "Não conheço esse homem de quem vocês estão falando!".

[[v41-14-72]]

^<<v41-14-72,72>>^ E, no mesmo instante, o galo cantou pela segunda vez. Então Pedro se lembrou das palavras de Jesus: "Antes que o galo cante duas vezes, você me negará três vezes". E começou a chorar.

'''

xref:041-marcos/041-marcos-013.adoc#v41-13-0[&#60; Capítulo Anterior] | <<v41-14-0,Topo>> | xref:041-marcos/041-marcos-015.adoc#v41-15-0[Próximo Capítulo &#62;]