include::./index.adoc[]

[[v43-20-0]]
=== João, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v43-20-1]]

^<<v43-20-1,1>>^ No primeiro dia da semana, bem cedo, enquanto ainda estava escuro, Maria Madalena foi ao túmulo e viu que a pedra da entrada tinha sido removida.

[[v43-20-2]]

^<<v43-20-2,2>>^ Correu e encontrou Simão Pedro e o outro discípulo, aquele a quem Jesus amava, e disse: "Tiraram do túmulo o corpo do Senhor, e não sabemos onde o colocaram!".

[[v43-20-3]]

^<<v43-20-3,3>>^ Pedro e o outro discípulo foram ao túmulo.

[[v43-20-4]]

^<<v43-20-4,4>>^ Os dois corriam, mas o outro discípulo foi mais rápido que Pedro e chegou primeiro ao túmulo.

[[v43-20-5]]

^<<v43-20-5,5>>^ Abaixou-se, olhou para dentro e viu ali as faixas de linho, mas não entrou.

[[v43-20-6]]

^<<v43-20-6,6>>^ Então Simão Pedro chegou e entrou. Também viu ali as faixas de linho

[[v43-20-7]]

^<<v43-20-7,7>>^ e notou que o pano que cobria a cabeça de Jesus estava dobrado e colocado à parte.

[[v43-20-8]]

^<<v43-20-8,8>>^ O discípulo que havia chegado primeiro ao túmulo também entrou, viu e creu.

[[v43-20-9]]

^<<v43-20-9,9>>^ Pois até então não haviam compreendido as Escrituras segundo as quais era necessário que Jesus ressuscitasse dos mortos.

[[v43-20-10]]

^<<v43-20-10,10>>^ Os discípulos voltaram para casa.

[[v43-20-11]]

^<<v43-20-11,11>>^ Maria estava do lado de fora do túmulo. Chorando, abaixou-se, olhou para dentro

[[v43-20-12]]

^<<v43-20-12,12>>^ e viu dois anjos vestidos de branco, sentados à cabeceira e aos pés do lugar onde tinha estado o corpo de Jesus.

[[v43-20-13]]

^<<v43-20-13,13>>^ Os anjos lhe perguntaram: "Mulher, por que você está chorando?". Ela respondeu: "Porque levaram o meu Senhor, e não sei onde o colocaram".

[[v43-20-14]]

^<<v43-20-14,14>>^ Então, ao virar-se para sair, viu alguém em pé. Era Jesus, mas ela não o reconheceu.

[[v43-20-15]]

^<<v43-20-15,15>>^ "Mulher, por que está chorando?", perguntou ele. "A quem você procura?" Pensando que fosse o jardineiro, ela disse: "Se o senhor o levou embora, diga-me onde o colocou, e eu irei buscá-lo".

[[v43-20-16]]

^<<v43-20-16,16>>^ "Maria!", disse Jesus. Ela se voltou para ele e exclamou: "Rabôni!" (que, em aramaico, quer dizer "Mestre!").

[[v43-20-17]]

^<<v43-20-17,17>>^ Jesus lhe disse: "Não se agarre a mim, pois ainda não subi ao Pai. Mas vá procurar meus irmãos e diga-lhes: ‘Eu vou subir para meu Pai e Pai de vocês, para meu Deus e Deus de vocês’".

[[v43-20-18]]

^<<v43-20-18,18>>^ Maria Madalena encontrou os discípulos e lhes disse: "Vi o Senhor!". Então contou o que Jesus havia falado.

[[v43-20-19]]

^<<v43-20-19,19>>^ Ao entardecer daquele primeiro dia da semana, os discípulos estavam reunidos com as portas trancadas, por medo dos líderes judeus. De repente, Jesus surgiu no meio deles e disse: "Paz seja com vocês!".

[[v43-20-20]]

^<<v43-20-20,20>>^ Enquanto falava, mostrou-lhes as feridas nas mãos e no lado. Eles se encheram de alegria quando viram o Senhor.

[[v43-20-21]]

^<<v43-20-21,21>>^ Mais uma vez, ele disse: "Paz seja com vocês! Assim como o Pai me enviou, eu os envio".

[[v43-20-22]]

^<<v43-20-22,22>>^ Então soprou sobre eles e disse: "Recebam o Espírito Santo.

[[v43-20-23]]

^<<v43-20-23,23>>^ Se vocês perdoarem os pecados de alguém, eles estarão perdoados. Se não perdoarem, eles não estarão perdoados".

[[v43-20-24]]

^<<v43-20-24,24>>^ Um dos Doze, Tomé, apelidado de Gêmeo, não estava com os outros quando Jesus surgiu no meio deles.

[[v43-20-25]]

^<<v43-20-25,25>>^ Eles lhe disseram: "Vimos o Senhor!". Ele, porém, respondeu: "Não acreditarei se não vir as marcas dos pregos em suas mãos e não puser meus dedos nelas e minha mão na marca em seu lado".

[[v43-20-26]]

^<<v43-20-26,26>>^ Oito dias depois, os discípulos estavam juntos novamente e, dessa vez, Tomé estava com eles. As portas estavam trancadas, mas, de repente, como antes, Jesus surgiu no meio deles. "Paz seja com vocês!", disse ele.

[[v43-20-27]]

^<<v43-20-27,27>>^ Então, disse a Tomé: "Ponha seu dedo aqui, e veja minhas mãos. Ponha sua mão na marca em meu lado. Não seja incrédulo. Creia!".

[[v43-20-28]]

^<<v43-20-28,28>>^ "Meu Senhor e meu Deus!", disse Tomé.

[[v43-20-29]]

^<<v43-20-29,29>>^ Então Jesus lhe disse: "Você crê porque me viu. Felizes são aqueles que creem sem ver".

[[v43-20-30]]

^<<v43-20-30,30>>^ Os discípulos viram Jesus fazer muitos outros sinais além dos que se encontram registrados neste livro.

[[v43-20-31]]

^<<v43-20-31,31>>^ Estes, porém, estão registrados para que vocês creiam que Jesus é o Cristo, o Filho de Deus, e para que, crendo nele, tenham vida pelo poder do seu nome.

'''

xref:043-joao/043-joao-019.adoc#v43-19-0[&#60; Capítulo Anterior] | <<v43-20-0,Topo>> | xref:043-joao/043-joao-021.adoc#v43-21-0[Próximo Capítulo &#62;]