include::./index.adoc[]

[[v43-4-0]]
=== João, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v43-4-1]]

^<<v43-4-1,1>>^ Jesus sabia que os fariseus tinham ouvido dizer que ele batizava e fazia mais discípulos que João,

[[v43-4-2]]

^<<v43-4-2,2>>^ embora Jesus mesmo não os batizasse, e sim seus discípulos.

[[v43-4-3]]

^<<v43-4-3,3>>^ Assim, deixou a Judeia e voltou para a Galileia.

[[v43-4-4]]

^<<v43-4-4,4>>^ No caminho, teve de passar por Samaria.

[[v43-4-5]]

^<<v43-4-5,5>>^ Chegou ao povoado samaritano de Sicar, perto do campo que Jacó tinha dado a seu filho José.

[[v43-4-6]]

^<<v43-4-6,6>>^ O poço de Jacó ficava ali, e Jesus, cansado da longa caminhada, sentou-se junto ao poço, por volta do meio-dia.

[[v43-4-7]]

^<<v43-4-7,7>>^ Pouco depois, uma mulher samaritana veio tirar água, e Jesus lhe disse: "Por favor, dê-me um pouco de água para beber".

[[v43-4-8]]

^<<v43-4-8,8>>^ Naquele momento, seus discípulos tinham ido ao povoado comprar comida.

[[v43-4-9]]

^<<v43-4-9,9>>^ A mulher ficou surpresa, pois os judeus se recusam a ter qualquer contato com os samaritanos. "Você é judeu, e eu sou uma mulher samaritana", disse ela a Jesus. "Como é que me pede água para beber?"

[[v43-4-10]]

^<<v43-4-10,10>>^ Jesus respondeu: "Se ao menos você soubesse que presente Deus tem para você e com quem está falando, você me pediria e eu lhe daria água viva".

[[v43-4-11]]

^<<v43-4-11,11>>^ "Mas você não tem corda nem balde, e o poço é muito fundo", disse ela. "De onde tiraria essa água viva?

[[v43-4-12]]

^<<v43-4-12,12>>^ Além do mais, você se considera mais importante que nosso antepassado Jacó, que nos deu este poço? Como pode oferecer água melhor que esta que Jacó, seus filhos e seus animais bebiam?"

[[v43-4-13]]

^<<v43-4-13,13>>^ Jesus respondeu: "Quem bebe desta água logo terá sede outra vez,

[[v43-4-14]]

^<<v43-4-14,14>>^ mas quem bebe da água que eu dou nunca mais terá sede. Ela se torna uma fonte que brota dentro dele e lhe dá a vida eterna".

[[v43-4-15]]

^<<v43-4-15,15>>^ "Por favor, senhor, dê-me dessa água!", disse a mulher. "Assim eu nunca mais terei sede nem precisarei vir aqui para tirar água."

[[v43-4-16]]

^<<v43-4-16,16>>^ "Vá buscar seu marido", disse Jesus.

[[v43-4-17]]

^<<v43-4-17,17>>^ "Não tenho marido", respondeu a mulher. Jesus disse: "É verdade. Você não tem marido,

[[v43-4-18]]

^<<v43-4-18,18>>^ pois teve cinco maridos e não é casada com o homem com quem vive agora. Certamente você disse a verdade".

[[v43-4-19]]

^<<v43-4-19,19>>^ "O senhor deve ser profeta", disse a mulher.

[[v43-4-20]]

^<<v43-4-20,20>>^ "Então diga-me: por que os judeus insistem que Jerusalém é o único lugar de adoração, enquanto nós, os samaritanos, afirmamos que é aqui, no monte Gerizim, onde nossos antepassados adoraram?"

[[v43-4-21]]

^<<v43-4-21,21>>^ Jesus respondeu: "Creia em mim, mulher, está chegando a hora em que já não importará se você adora o Pai neste monte ou em Jerusalém.

[[v43-4-22]]

^<<v43-4-22,22>>^ Vocês, samaritanos, sabem muito pouco a respeito daquele a quem adoram. Nós adoramos com conhecimento, pois a salvação vem por meio dos judeus.

[[v43-4-23]]

^<<v43-4-23,23>>^ Mas está chegando a hora, e de fato já chegou, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade. O Pai procura pessoas que o adorem desse modo.

[[v43-4-24]]

^<<v43-4-24,24>>^ Pois Deus é Espírito, e é necessário que seus adoradores o adorem em espírito e em verdade".

[[v43-4-25]]

^<<v43-4-25,25>>^ A mulher disse: "Eu sei que o Messias (aquele que é chamado Cristo) virá. Quando vier, ele nos explicará tudo".

[[v43-4-26]]

^<<v43-4-26,26>>^ Então Jesus lhe disse: "Sou eu, o que fala com você!".

[[v43-4-27]]

^<<v43-4-27,27>>^ Naquele momento, seus discípulos voltaram. Ficaram surpresos de encontrá-lo falando com uma mulher, mas nenhum deles se atreveu a perguntar: "O que o senhor quer?" ou "Por que conversa com ela?".

[[v43-4-28]]

^<<v43-4-28,28>>^ A mulher deixou sua vasilha de água junto ao poço e correu de volta para o povoado, dizendo a todos:

[[v43-4-29]]

^<<v43-4-29,29>>^ "Venham ver um homem que me disse tudo que eu já fiz na vida! Será que não é ele o Cristo?".

[[v43-4-30]]

^<<v43-4-30,30>>^ Então as pessoas saíram do povoado para vê-lo.

[[v43-4-31]]

^<<v43-4-31,31>>^ Enquanto isso, os discípulos insistiam com Jesus: "Rabi, coma alguma coisa".

[[v43-4-32]]

^<<v43-4-32,32>>^ Ele, porém, respondeu: "Eu tenho um tipo de alimento que vocês não conhecem".

[[v43-4-33]]

^<<v43-4-33,33>>^ Os discípulos perguntaram uns aos outros: "Será que alguém lhe trouxe comida?".

[[v43-4-34]]

^<<v43-4-34,34>>^ Então Jesus explicou: "Meu alimento consiste em fazer a vontade daquele que me enviou e em terminar a sua obra.

[[v43-4-35]]

^<<v43-4-35,35>>^ Vocês não costumam dizer: ‘Ainda faltam quatro meses para a colheita’? Mas eu lhes digo: despertem e olhem em volta. Os campos estão maduros para a colheita.

[[v43-4-36]]

^<<v43-4-36,36>>^ Os que colhem já recebem salário, e os frutos que ajuntam são as pessoas que passam a ter a vida eterna. Que alegria espera tanto o que semeia como o que colhe!

[[v43-4-37]]

^<<v43-4-37,37>>^ Vocês conhecem o ditado: ‘Um semeia e outro colhe’. E é verdade.

[[v43-4-38]]

^<<v43-4-38,38>>^ Eu envio vocês para colher onde não semearam; outros realizaram o trabalho, e agora vocês ajuntarão a colheita".

[[v43-4-39]]

^<<v43-4-39,39>>^ Muitos samaritanos do povoado creram em Jesus por causa daquilo que a mulher relatou: "Ele me disse tudo que eu já fiz!".

[[v43-4-40]]

^<<v43-4-40,40>>^ Quando saíram para vê-lo, insistiram que ficasse no povoado. Jesus permaneceu ali dois dias,

[[v43-4-41]]

^<<v43-4-41,41>>^ e muitos outros ouviram sua palavra e creram.

[[v43-4-42]]

^<<v43-4-42,42>>^ Então disseram à mulher: "Agora cremos, não apenas por causa do que você nos contou, mas porque nós mesmos o ouvimos. Agora sabemos que ele é, de fato, o Salvador do mundo".

[[v43-4-43]]

^<<v43-4-43,43>>^ Depois daqueles dois dias, Jesus partiu para a Galileia.

[[v43-4-44]]

^<<v43-4-44,44>>^ Ele mesmo tinha dito que um profeta não é honrado em sua própria terra.

[[v43-4-45]]

^<<v43-4-45,45>>^ Mas, uma vez que os galileus haviam estado em Jerusalém para a festa da Páscoa e visto tudo que Jesus fizera, eles o receberam.

[[v43-4-46]]

^<<v43-4-46,46>>^ Enquanto Jesus viajava pela Galileia, chegou a Caná, onde tinha transformado água em vinho. Perto dali, em Cafarnaum, havia um oficial do governo cujo filho estava muito doente.

[[v43-4-47]]

^<<v43-4-47,47>>^ Quando soube que Jesus viera da Judeia para a Galileia, foi até ele e suplicou que fosse a Cafarnaum para curar seu filho, que estava à beira da morte.

[[v43-4-48]]

^<<v43-4-48,48>>^ Jesus exclamou: "Jamais crerão, a menos que vejam sinais e maravilhas!".

[[v43-4-49]]

^<<v43-4-49,49>>^ O oficial implorou: "Senhor, por favor, venha antes que meu filho morra".

[[v43-4-50]]

^<<v43-4-50,50>>^ "Volte!", disse Jesus. "Seu filho viverá." O homem creu nas palavras de Jesus e partiu para casa.

[[v43-4-51]]

^<<v43-4-51,51>>^ Enquanto estava a caminho, alguns de seus servos vieram a seu encontro com a notícia de que seu filho estava vivo e bem.

[[v43-4-52]]

^<<v43-4-52,52>>^ Ele perguntou quando o menino havia começado a melhorar, e eles responderam: "Ontem à tarde, à uma hora, a febre subitamente desapareceu!".

[[v43-4-53]]

^<<v43-4-53,53>>^ Então o pai percebeu que havia sido naquele exato momento que Jesus tinha dito: "Seu filho viverá". E o oficial e todos de sua casa creram em Jesus.

[[v43-4-54]]

^<<v43-4-54,54>>^ Esse foi o segundo sinal que Jesus realizou na Galileia, depois que veio da Judeia.

'''

xref:043-joao/043-joao-003.adoc#v43-3-0[&#60; Capítulo Anterior] | <<v43-4-0,Topo>> | xref:043-joao/043-joao-005.adoc#v43-5-0[Próximo Capítulo &#62;]