include::./index.adoc[]

[[v43-1-0]]
=== João, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v43-1-1]]

^<<v43-1-1,1>>^ No princípio, aquele que é a Palavra já existia. A Palavra estava com Deus, e a Palavra era Deus.

[[v43-1-2]]

^<<v43-1-2,2>>^ Ele existia no princípio com Deus.

[[v43-1-3]]

^<<v43-1-3,3>>^ Por meio dele Deus criou todas as coisas, e sem ele nada foi criado.

[[v43-1-4]]

^<<v43-1-4,4>>^ Aquele que é a Palavra possuía a vida, e sua vida trouxe luz a todos.

[[v43-1-5]]

^<<v43-1-5,5>>^ A luz brilha na escuridão, e a escuridão nunca conseguiu apagá-la.

[[v43-1-6]]

^<<v43-1-6,6>>^ Deus enviou um homem chamado João

[[v43-1-7]]

^<<v43-1-7,7>>^ para falar a respeito da luz, a fim de que, por meio de seu testemunho, todos cressem.

[[v43-1-8]]

^<<v43-1-8,8>>^ Ele não era a luz, mas veio para falar da luz.

[[v43-1-9]]

^<<v43-1-9,9>>^ Aquele que é a verdadeira luz, que ilumina a todos, estava chegando ao mundo.

[[v43-1-10]]

^<<v43-1-10,10>>^ Veio ao mundo que ele criou, mas o mundo não o reconheceu.

[[v43-1-11]]

^<<v43-1-11,11>>^ Veio a seu próprio povo, e eles o rejeitaram.

[[v43-1-12]]

^<<v43-1-12,12>>^ Mas, a todos que creram nele e o aceitaram, ele deu o direito de se tornarem filhos de Deus.

[[v43-1-13]]

^<<v43-1-13,13>>^ Estes não nasceram segundo a ordem natural, nem como resultado da paixão ou da vontade humana, mas nasceram de Deus.

[[v43-1-14]]

^<<v43-1-14,14>>^ Assim, a Palavra se tornou ser humano, carne e osso, e habitou entre nós. Ele era cheio de graça e verdade. E vimos sua glória, a glória do Filho único do Pai.

[[v43-1-15]]

^<<v43-1-15,15>>^ João deu testemunho dele quando disse em alta voz: "Este é aquele a quem eu me referia quando disse: ‘Alguém virá depois de mim, muito mais poderoso que eu, pois existia muito antes de mim’".

[[v43-1-16]]

^<<v43-1-16,16>>^ De sua plenitude todos nós recebemos graça sobre graça.

[[v43-1-17]]

^<<v43-1-17,17>>^ Pois a lei foi dada por meio de Moisés, mas a graça e a verdade vieram por meio de Jesus Cristo.

[[v43-1-18]]

^<<v43-1-18,18>>^ Ninguém jamais viu a Deus, mas o Filho único, que mantém comunhão íntima com o Pai, o revelou.

[[v43-1-19]]

^<<v43-1-19,19>>^ Este foi o testemunho de João quando os líderes judeus enviaram de Jerusalém sacerdotes e levitas para lhe perguntar: "Quem é você?".

[[v43-1-20]]

^<<v43-1-20,20>>^ Ele respondeu com toda franqueza: "Eu não sou o Cristo".

[[v43-1-21]]

^<<v43-1-21,21>>^ "Então quem é você?", perguntaram eles. "É Elias?" "Não", respondeu ele. "É o Profeta por quem temos esperado?" "Não."

[[v43-1-22]]

^<<v43-1-22,22>>^ "Afinal, quem é você? Precisamos de uma resposta para aqueles que nos enviaram. O que você tem a dizer de si mesmo?"

[[v43-1-23]]

^<<v43-1-23,23>>^ João respondeu com as palavras do profeta Isaías: "Eu sou uma voz que clama no deserto: ‘Preparem o caminho para a vinda do Senhor!’".

[[v43-1-24]]

^<<v43-1-24,24>>^ Então os fariseus que tinham sido enviados

[[v43-1-25]]

^<<v43-1-25,25>>^ lhe perguntaram: "Se você não é o Cristo, nem Elias, nem o Profeta, que direito tem de batizar?".

[[v43-1-26]]

^<<v43-1-26,26>>^ João lhes disse: "Eu batizo com água, mas em seu meio há alguém que vocês não reconhecem.

[[v43-1-27]]

^<<v43-1-27,27>>^ Embora ele venha depois de mim, não sou digno de desamarrar as correias de sua sandália".

[[v43-1-28]]

^<<v43-1-28,28>>^ Esse encontro aconteceu em Betânia, um povoado a leste do rio Jordão, onde João estava batizando.

[[v43-1-29]]

^<<v43-1-29,29>>^ No dia seguinte, João viu Jesus caminhando em sua direção e disse: "Vejam! É o Cordeiro de Deus, que tira o pecado do mundo!

[[v43-1-30]]

^<<v43-1-30,30>>^ Era a ele que eu me referia quando disse: ‘Um homem virá depois de mim, muito mais poderoso que eu, pois existia muito antes de mim’.

[[v43-1-31]]

^<<v43-1-31,31>>^ Eu não o conhecia, mas vim batizando com água para que ele fosse revelado a Israel".

[[v43-1-32]]

^<<v43-1-32,32>>^ Então João deu o seguinte testemunho: "Vi o Espírito Santo descer do céu na forma de uma pomba e permanecer sobre ele.

[[v43-1-33]]

^<<v43-1-33,33>>^ Eu não sabia quem ele era, mas, quando Deus me enviou para batizar com água, disse-me: ‘Aquele sobre o qual você vir o Espírito descer e permanecer, esse é o que batizará com o Espírito Santo’.

[[v43-1-34]]

^<<v43-1-34,34>>^ Eu vi isso acontecer e, portanto, dou testemunho de que ele é o Filho de Deus".

[[v43-1-35]]

^<<v43-1-35,35>>^ No dia seguinte, João estava novamente com dois de seus discípulos.

[[v43-1-36]]

^<<v43-1-36,36>>^ Quando viu Jesus passar, olhou para ele e declarou: "Vejam! É o Cordeiro de Deus!".

[[v43-1-37]]

^<<v43-1-37,37>>^ Ao ouvirem isso, os dois discípulos de João seguiram Jesus.

[[v43-1-38]]

^<<v43-1-38,38>>^ Jesus olhou em volta e viu que o seguiam. "O que vocês querem?", perguntou. Eles responderam: "Rabi (que significa ‘Mestre’), onde o senhor está hospedado?".

[[v43-1-39]]

^<<v43-1-39,39>>^ "Venham e vejam", disse ele. Eram cerca de quatro horas da tarde quando o acompanharam até o lugar onde Jesus estava hospedado, e passaram o resto do dia com ele.

[[v43-1-40]]

^<<v43-1-40,40>>^ André, irmão de Simão Pedro, era um dos dois que ouviram o que João tinha dito e seguiram Jesus.

[[v43-1-41]]

^<<v43-1-41,41>>^ André foi procurar seu irmão, Simão, e lhe disse: "Encontramos o Messias (isto é, o Cristo)".

[[v43-1-42]]

^<<v43-1-42,42>>^ Então André levou Simão para conhecer Jesus. Olhando para ele, Jesus disse: "Você é Simão, filho de João, mas será chamado Cefas (isto é, Pedro)".

[[v43-1-43]]

^<<v43-1-43,43>>^ No dia seguinte, Jesus decidiu ir à Galileia. Encontrou Filipe e lhe disse: "Siga-me".

[[v43-1-44]]

^<<v43-1-44,44>>^ Filipe era de Betsaida, cidade natal de André e Pedro.

[[v43-1-45]]

^<<v43-1-45,45>>^ Filipe foi procurar Natanael e lhe disse: "Encontramos aquele sobre quem Moisés, na lei, e os profetas escreveram! Seu nome é Jesus de Nazaré, filho de José".

[[v43-1-46]]

^<<v43-1-46,46>>^ "Nazaré!", exclamou Natanael. "Pode vir alguma coisa boa de Nazaré?" "Venha e veja você mesmo", respondeu Filipe.

[[v43-1-47]]

^<<v43-1-47,47>>^ Jesus viu Natanael se aproximar e disse: "Aí está um verdadeiro filho de Israel, um homem totalmente íntegro".

[[v43-1-48]]

^<<v43-1-48,48>>^ "Como o senhor sabe a meu respeito?", perguntou Natanael. Jesus respondeu: "Vi você sob a figueira antes que Filipe o chamasse".

[[v43-1-49]]

^<<v43-1-49,49>>^ Então Natanael exclamou: "Rabi, o senhor é o Filho de Deus, o Rei de Israel!".

[[v43-1-50]]

^<<v43-1-50,50>>^ Jesus lhe perguntou: "Você crê nisso porque eu disse que o vi sob a figueira? Você verá coisas maiores que essa".

[[v43-1-51]]

^<<v43-1-51,51>>^ E acrescentou: "Eu lhes digo a verdade: vocês verão o céu aberto e os anjos de Deus subindo e descendo sobre o Filho do Homem".

'''

xref:042-lucas/042-lucas-024.adoc#v42-24-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-joao/043-joao-002.adoc#v43-2-0[Próximo Capítulo &#62;]