include::./index.adoc[]

[[v43-12-0]]
=== João, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v43-12-1]]

^<<v43-12-1,1>>^ Seis dias antes de começar a Páscoa, Jesus chegou a Betânia, onde morava Lázaro, o homem que ele havia ressuscitado dos mortos.

[[v43-12-2]]

^<<v43-12-2,2>>^ Prepararam um jantar em homenagem a Jesus; Marta servia, e Lázaro estava à mesa com ele.

[[v43-12-3]]

^<<v43-12-3,3>>^ Então Maria pegou um frasco de perfume caro feito de essência de óleo aromático, ungiu com ele os pés de Jesus e os enxugou com os cabelos. A casa se encheu com a fragrância do perfume.

[[v43-12-4]]

^<<v43-12-4,4>>^ Mas Judas Iscariotes, o discípulo que em breve trairia Jesus, disse:

[[v43-12-5]]

^<<v43-12-5,5>>^ "Este perfume valia trezentas moedas de prata. Deveria ter sido vendido, e o dinheiro, dado aos pobres".

[[v43-12-6]]

^<<v43-12-6,6>>^ Não que ele se importasse com os pobres; na verdade, era ladrão e, como responsável pelo dinheiro dos discípulos, muitas vezes roubava uma parte para si.

[[v43-12-7]]

^<<v43-12-7,7>>^ Jesus respondeu: "Deixe-a em paz. Ela fez isto como preparação para meu sepultamento.

[[v43-12-8]]

^<<v43-12-8,8>>^ Vocês sempre terão os pobres em seu meio, mas nem sempre terão a mim".

[[v43-12-9]]

^<<v43-12-9,9>>^ Quando o povo soube da chegada de Jesus, correu para vê-lo, e também a Lázaro, a quem Jesus havia ressuscitado dos mortos.

[[v43-12-10]]

^<<v43-12-10,10>>^ Então os principais sacerdotes decidiram matar também Lázaro,

[[v43-12-11]]

^<<v43-12-11,11>>^ pois, por causa dele, muitos do povo os haviam abandonado e criam em Jesus.

[[v43-12-12]]

^<<v43-12-12,12>>^ No dia seguinte, correu pela cidade a notícia de que Jesus estava a caminho de Jerusalém. Uma grande multidão de visitantes que tinham vindo para a Páscoa

[[v43-12-13]]

^<<v43-12-13,13>>^ tomou ramos de palmeiras e saiu ao seu encontro, gritando: "Hosana! Bendito é o que vem em nome do Senhor! Bendito é o Rei de Israel!".

[[v43-12-14]]

^<<v43-12-14,14>>^ Jesus conseguiu um jumentinho e montou nele, cumprindo a profecia que dizia:

[[v43-12-15]]

^<<v43-12-15,15>>^ "Não tenha medo, povo de Sião. Vejam, seu Rei se aproxima, montado num jumentinho".

[[v43-12-16]]

^<<v43-12-16,16>>^ Seus discípulos não entenderam, naquele momento, que se tratava do cumprimento de uma profecia. Depois que Jesus foi glorificado, porém, eles se lembraram do que havia acontecido e perceberam que era a respeito dele que essas coisas tinham sido escritas.

[[v43-12-17]]

^<<v43-12-17,17>>^ Muitos tinham visto quando Jesus mandou Lázaro sair do túmulo e o ressuscitou dos mortos, e contavam esse fato a outros.

[[v43-12-18]]

^<<v43-12-18,18>>^ Destes, muitos saíram ao encontro de Jesus, porque tinham ouvido falar desse sinal.

[[v43-12-19]]

^<<v43-12-19,19>>^ Então os fariseus disseram uns aos outros: "Não podemos fazer nada. Vejam, todo mundo o segue!".

[[v43-12-20]]

^<<v43-12-20,20>>^ Alguns gregos que tinham vindo a Jerusalém para adorar durante a festa da Páscoa

[[v43-12-21]]

^<<v43-12-21,21>>^ procuraram Filipe, que era de Betsaida, da Galileia, e lhe disseram: "Por favor, gostaríamos de ver Jesus".

[[v43-12-22]]

^<<v43-12-22,22>>^ Filipe falou a esse respeito com André, e os dois foram juntos falar com Jesus.

[[v43-12-23]]

^<<v43-12-23,23>>^ Jesus respondeu: "Chegou a hora de o Filho do Homem ser glorificado.

[[v43-12-24]]

^<<v43-12-24,24>>^ Eu lhes digo a verdade: se o grão de trigo não for plantado na terra e não morrer, ficará só. Sua morte, porém, produzirá muitos novos grãos.

[[v43-12-25]]

^<<v43-12-25,25>>^ Quem ama sua vida neste mundo a perderá. Quem odeia sua vida neste mundo a conservará por toda a eternidade.

[[v43-12-26]]

^<<v43-12-26,26>>^ Se alguém quer ser meu discípulo, siga-me, pois meus servos devem estar onde eu estou. E o Pai honrará quem me servir.

[[v43-12-27]]

^<<v43-12-27,27>>^ "Agora minha alma está angustiada. Acaso devo orar ‘Pai, salva-me desta hora’? Mas foi exatamente por esse motivo que eu vim!

[[v43-12-28]]

^<<v43-12-28,28>>^ Pai, glorifica teu nome!". Então uma voz falou do céu: "Eu já glorifiquei meu nome, e o farei novamente em breve".

[[v43-12-29]]

^<<v43-12-29,29>>^ Quando a multidão ouviu a voz, alguns pensaram que era um trovão, enquanto outros afirmavam que um anjo havia falado com ele.

[[v43-12-30]]

^<<v43-12-30,30>>^ Então Jesus lhes disse: "A voz foi por causa de vocês, e não por minha causa.

[[v43-12-31]]

^<<v43-12-31,31>>^ Chegou a hora de julgar o mundo; agora, o governante deste mundo será expulso.

[[v43-12-32]]

^<<v43-12-32,32>>^ E, quando eu for levantado da terra, atrairei todos a mim".

[[v43-12-33]]

^<<v43-12-33,33>>^ Ele disse isso para indicar como morreria.

[[v43-12-34]]

^<<v43-12-34,34>>^ A multidão disse: "Entendemos pelas Escrituras que o Cristo viveria para sempre. Como pode dizer que o Filho do Homem morrerá? Afinal, quem é esse Filho do Homem?".

[[v43-12-35]]

^<<v43-12-35,35>>^ Jesus respondeu: "Minha luz brilhará para vocês só mais um pouco. Andem na luz enquanto podem, para que a escuridão não os pegue de surpresa. Quem anda na escuridão não consegue ver aonde vai.

[[v43-12-36]]

^<<v43-12-36,36>>^ Creiam na luz enquanto ainda há tempo; desse modo vocês se tornarão filhos da luz". Depois de dizer essas coisas, Jesus foi embora e se ocultou deles.

[[v43-12-37]]

^<<v43-12-37,37>>^ Apesar de todos os sinais que Jesus havia realizado, não creram nele.

[[v43-12-38]]

^<<v43-12-38,38>>^ Aconteceu conforme o profeta Isaías tinha dito: "Senhor, quem creu em nossa mensagem? A quem o Senhor revelou seu braço forte?".

[[v43-12-39]]

^<<v43-12-39,39>>^ Mas o povo não podia crer, pois como Isaías também disse:

[[v43-12-40]]

^<<v43-12-40,40>>^ "O Senhor cegou seus olhos e endureceu seu coração para que seus olhos não vejam, e seu coração não entenda, e não se voltem para mim, nem permitam que eu os cure".

[[v43-12-41]]

^<<v43-12-41,41>>^ As palavras de Isaías referiam-se a Jesus, pois viu sua glória e falou sobre ele.

[[v43-12-42]]

^<<v43-12-42,42>>^ Ainda assim, muitos creram em Jesus, incluindo alguns dos líderes judeus. Eles, porém, não declararam sua fé abertamente, por medo de que os fariseus os expulsassem da sinagoga.

[[v43-12-43]]

^<<v43-12-43,43>>^ Amaram a aprovação das pessoas mais que a aprovação de Deus.

[[v43-12-44]]

^<<v43-12-44,44>>^ Jesus disse em alta voz às multidões: "Se vocês creem em mim, não creem apenas em mim, mas também naquele que me enviou.

[[v43-12-45]]

^<<v43-12-45,45>>^ Pois, quando veem a mim, veem aquele que me enviou.

[[v43-12-46]]

^<<v43-12-46,46>>^ Eu vim como luz para brilhar neste mundo, a fim de que todo aquele que crê em mim não permaneça na escuridão.

[[v43-12-47]]

^<<v43-12-47,47>>^ Não julgarei aqueles que me ouvem mas não me obedecem, pois vim para salvar o mundo, e não para julgá-lo.

[[v43-12-48]]

^<<v43-12-48,48>>^ Mas todos que me rejeitam e desprezam minha mensagem serão julgados no dia do julgamento pela verdade que tenho falado.

[[v43-12-49]]

^<<v43-12-49,49>>^ Não falo com minha própria autoridade. O Pai, que me enviou, me ordenou o que dizer.

[[v43-12-50]]

^<<v43-12-50,50>>^ E eu sei que o mandamento dele conduz à vida eterna; por isso digo tudo que o Pai me mandou dizer".

'''

xref:043-joao/043-joao-011.adoc#v43-11-0[&#60; Capítulo Anterior] | <<v43-12-0,Topo>> | xref:043-joao/043-joao-013.adoc#v43-13-0[Próximo Capítulo &#62;]