include::./index.adoc[]

[[v43-2-0]]
=== João, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v43-2-1]]

^<<v43-2-1,1>>^ Três dias depois, houve uma festa de casamento no povoado de Caná da Galileia. A mãe de Jesus estava ali,

[[v43-2-2]]

^<<v43-2-2,2>>^ e Jesus e seus discípulos também foram convidados para a celebração.

[[v43-2-3]]

^<<v43-2-3,3>>^ Durante a festa, o vinho acabou, e a mãe de Jesus lhe disse: "Eles não têm mais vinho".

[[v43-2-4]]

^<<v43-2-4,4>>^ "Mulher, isso não me diz respeito", respondeu Jesus. "Minha hora ainda não chegou."

[[v43-2-5]]

^<<v43-2-5,5>>^ Sua mãe, porém, disse aos empregados: "Façam tudo que ele mandar".

[[v43-2-6]]

^<<v43-2-6,6>>^ Havia ali perto seis potes de pedra usados na purificação cerimonial judaica. Cada um tinha capacidade entre 80 e 120 litros.

[[v43-2-7]]

^<<v43-2-7,7>>^ Jesus disse aos empregados: "Encham os potes com água". Quando os potes estavam cheios,

[[v43-2-8]]

^<<v43-2-8,8>>^ disse: "Agora tirem um pouco e levem ao mestre de cerimônias". Os empregados seguiram suas instruções.

[[v43-2-9]]

^<<v43-2-9,9>>^ O mestre de cerimônias provou a água transformada em vinho, sem conhecer sua procedência (embora os empregados obviamente soubessem). Então chamou o noivo.

[[v43-2-10]]

^<<v43-2-10,10>>^ "O anfitrião sempre serve o melhor vinho primeiro", disse ele. "Depois, quando todos já beberam bastante, serve o vinho de menor qualidade. Mas você guardou o melhor vinho até agora!"

[[v43-2-11]]

^<<v43-2-11,11>>^ Esse sinal em Caná da Galileia foi o primeiro milagre que Jesus fez. Com isso ele manifestou sua glória, e seus discípulos creram nele.

[[v43-2-12]]

^<<v43-2-12,12>>^ Depois do casamento, foi a Cafarnaum, onde passou alguns dias com sua mãe, seus irmãos e seus discípulos.

[[v43-2-13]]

^<<v43-2-13,13>>^ Era quase época da festa da Páscoa judaica, de modo que Jesus subiu a Jerusalém.

[[v43-2-14]]

^<<v43-2-14,14>>^ No pátio do templo, viu comerciantes que vendiam bois, ovelhas e pombas para os sacrifícios; também viu negociantes, em mesas, trocando dinheiro estrangeiro.

[[v43-2-15]]

^<<v43-2-15,15>>^ Jesus fez um chicote de cordas e os expulsou a todos do templo. Pôs para fora as ovelhas e os bois, espalhou as moedas dos negociantes no chão e virou as mesas.

[[v43-2-16]]

^<<v43-2-16,16>>^ Depois, foi até aqueles que vendiam pombas e lhes disse: "Tirem essas coisas daqui! Parem de fazer da casa de meu Pai um mercado!".

[[v43-2-17]]

^<<v43-2-17,17>>^ Então os discípulos se lembraram desta profecia das Escrituras: "O zelo pela casa de Deus me consumirá".

[[v43-2-18]]

^<<v43-2-18,18>>^ "O que você está fazendo?", questionaram os líderes judeus. "Que sinal você nos mostra para comprovar que tem autoridade para isso?"

[[v43-2-19]]

^<<v43-2-19,19>>^ "Pois bem", respondeu Jesus. "Destruam este templo, e em três dias eu o levantarei."

[[v43-2-20]]

^<<v43-2-20,20>>^ Eles disseram: "Foram necessários 46 anos para construir este templo, e você o reconstruirá em três dias?".

[[v43-2-21]]

^<<v43-2-21,21>>^ Mas quando Jesus disse "este templo", estava se referindo a seu próprio corpo.

[[v43-2-22]]

^<<v43-2-22,22>>^ Depois que ele ressuscitou dos mortos, seus discípulos se lembraram do que ele tinha dito e creram nas Escrituras e em suas palavras.

[[v43-2-23]]

^<<v43-2-23,23>>^ Por causa dos sinais que Jesus realizou em Jerusalém durante a festa da Páscoa, muitos creram nele.

[[v43-2-24]]

^<<v43-2-24,24>>^ Jesus, porém, não confiava neles, pois conhecia a todos.

[[v43-2-25]]

^<<v43-2-25,25>>^ Ninguém precisava lhe dizer como o ser humano é de fato, pois ele conhecia a natureza humana.

'''

xref:043-joao/043-joao-001.adoc#v43-1-0[&#60; Capítulo Anterior] | <<v43-2-0,Topo>> | xref:043-joao/043-joao-003.adoc#v43-3-0[Próximo Capítulo &#62;]