include::./index.adoc[]

[[v43-21-0]]
=== João, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v43-21-1]]

^<<v43-21-1,1>>^ Depois disso, Jesus apareceu novamente a seus discípulos junto ao mar de Tiberíades. Foi assim que aconteceu:

[[v43-21-2]]

^<<v43-21-2,2>>^ estavam ali Simão Pedro, Tomé, apelidado de Gêmeo, Natanael, de Caná da Galileia, os filhos de Zebedeu e outros dois discípulos.

[[v43-21-3]]

^<<v43-21-3,3>>^ Simão Pedro disse: "Vou pescar". "Nós também vamos", disseram os outros. Assim, entraram no barco e foram, mas não pegaram coisa alguma a noite toda.

[[v43-21-4]]

^<<v43-21-4,4>>^ Ao amanhecer, Jesus estava na praia, mas os discípulos não o reconheceram.

[[v43-21-5]]

^<<v43-21-5,5>>^ Ele perguntou: "Filhos, por acaso vocês têm peixe para comer?". "Não", responderam eles.

[[v43-21-6]]

^<<v43-21-6,6>>^ Então ele disse: "Lancem a rede para o lado direito do barco e pegarão". Fizeram assim e não conseguiam recolher a rede, de tão cheia de peixes que estava.

[[v43-21-7]]

^<<v43-21-7,7>>^ O discípulo a quem Jesus amava disse a Pedro: "É o Senhor!". Quando Simão Pedro ouviu que era o Senhor, vestiu a capa, pois a havia removido para trabalhar, e saltou na água.

[[v43-21-8]]

^<<v43-21-8,8>>^ Os outros ficaram no barco e puxaram até a praia a rede carregada, pois estavam a apenas uns noventa metros de distância.

[[v43-21-9]]

^<<v43-21-9,9>>^ Quando chegaram, encontraram um braseiro, no qual havia um peixe, e pão.

[[v43-21-10]]

^<<v43-21-10,10>>^ Jesus disse: "Tragam alguns dos peixes que vocês acabaram de pegar".

[[v43-21-11]]

^<<v43-21-11,11>>^ Simão Pedro entrou no barco e arrastou a rede para a praia. Havia 153 peixes grandes e, no entanto, a rede não arrebentou.

[[v43-21-12]]

^<<v43-21-12,12>>^ "Venham comer!", disse Jesus. Nenhum dos discípulos tinha coragem de perguntar: "Quem é você?", pois sabiam muito bem que era o Senhor.

[[v43-21-13]]

^<<v43-21-13,13>>^ Então Jesus lhes serviu o pão e o peixe.

[[v43-21-14]]

^<<v43-21-14,14>>^ Foi a terceira vez que Jesus apareceu a seus discípulos depois de ressuscitar dos mortos.

[[v43-21-15]]

^<<v43-21-15,15>>^ Depois da refeição, Jesus perguntou a Simão Pedro: "Simão, filho de João, você me ama mais do que estes?". "Sim, Senhor", respondeu Pedro. "O senhor sabe que eu o amo". "Então alimente meus cordeiros", disse Jesus.

[[v43-21-16]]

^<<v43-21-16,16>>^ Jesus repetiu a pergunta: "Simão, filho de João, você me ama?". "Sim, Senhor", disse Pedro. "O senhor sabe que eu o amo". "Então cuide de minhas ovelhas", disse Jesus.

[[v43-21-17]]

^<<v43-21-17,17>>^ Pela terceira vez, ele perguntou: "Simão, filho de João, você me ama?". Pedro ficou triste porque Jesus fez a pergunta pela terceira vez e disse: "O Senhor sabe todas as coisas. Sabe que eu o amo". Jesus disse: "Então alimente minhas ovelhas.

[[v43-21-18]]

^<<v43-21-18,18>>^ "Eu lhe digo a verdade: quando você era jovem, podia agir como bem entendia; vestia-se e ia aonde queria. Mas, quando for velho, estenderá as mãos e outros o vestirão e o levarão aonde você não quer ir".

[[v43-21-19]]

^<<v43-21-19,19>>^ Jesus disse isso para informá-lo com que tipo de morte ele iria glorificar a Deus. Então Jesus lhe disse: "Siga-me".

[[v43-21-20]]

^<<v43-21-20,20>>^ Pedro se virou e viu atrás deles o discípulo a quem Jesus amava, aquele que havia se reclinado perto de Jesus durante a ceia e perguntado: "Senhor, quem o trairá?".

[[v43-21-21]]

^<<v43-21-21,21>>^ Pedro perguntou a Jesus: "Senhor, e quanto a ele?".

[[v43-21-22]]

^<<v43-21-22,22>>^ Jesus respondeu: "Se eu quiser que ele permaneça vivo até eu voltar, o que lhe importa? Quanto a você, siga-me".

[[v43-21-23]]

^<<v43-21-23,23>>^ Por isso espalhou-se entre a comunidade dos irmãos o rumor de que esse discípulo não morreria. Não foi isso, porém, o que Jesus disse. Ele apenas disse: "Se eu quiser que ele permaneça vivo até eu voltar, o que lhe importa?".

[[v43-21-24]]

^<<v43-21-24,24>>^ Este é o discípulo que dá testemunho destes acontecimentos e que os registrou aqui. E sabemos que seu relato é fiel.

[[v43-21-25]]

^<<v43-21-25,25>>^ Jesus também fez muitas outras coisas. Se todas fossem registradas, suponho que nem o mundo inteiro poderia conter todos os livros que seriam escritos.

'''

xref:043-joao/043-joao-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-atos/044-atos-001.adoc#v44-1-0[Próximo Capítulo &#62;]