include::./index.adoc[]

[[v43-9-0]]
=== João, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v43-9-1]]

^<<v43-9-1,1>>^ Enquanto caminhava, Jesus viu um homem cego de nascença.

[[v43-9-2]]

^<<v43-9-2,2>>^ Seus discípulos perguntaram: "Rabi, por que este homem nasceu cego? Foi por causa de seus próprios pecados ou dos pecados de seus pais?".

[[v43-9-3]]

^<<v43-9-3,3>>^ Jesus respondeu: "Nem uma coisa nem outra. Isso aconteceu para que o poder de Deus se manifestasse nele.

[[v43-9-4]]

^<<v43-9-4,4>>^ Devemos cumprir logo as tarefas que nos foram dadas por aquele que me enviou. A noite se aproxima, quando ninguém pode trabalhar.

[[v43-9-5]]

^<<v43-9-5,5>>^ Mas, enquanto estou aqui no mundo, eu sou a luz do mundo".

[[v43-9-6]]

^<<v43-9-6,6>>^ Depois de dizer isso, Jesus cuspiu no chão, misturou a terra com saliva e aplicou-a nos olhos do cego.

[[v43-9-7]]

^<<v43-9-7,7>>^ Em seguida, disse: "Vá lavar-se no tanque de Siloé" (que significa "enviado"). O homem foi, lavou-se e voltou enxergando.

[[v43-9-8]]

^<<v43-9-8,8>>^ Seus vizinhos e outros que o conheciam como mendigo começaram a perguntar: "Não é este o homem que costumava ficar sentado pedindo esmolas?".

[[v43-9-9]]

^<<v43-9-9,9>>^ Alguns diziam que sim, e outros diziam: "Não, apenas se parece com ele". O mendigo, porém, insistia: "Sim, sou eu mesmo!".

[[v43-9-10]]

^<<v43-9-10,10>>^ "Quem curou você?", perguntaram eles. "O que aconteceu?"

[[v43-9-11]]

^<<v43-9-11,11>>^ Ele respondeu: "O homem chamado Jesus misturou terra com saliva, colocou-a em meus olhos e disse: ‘Vá lavar-se no tanque de Siloé’. Eu fui e me lavei, e agora posso ver!".

[[v43-9-12]]

^<<v43-9-12,12>>^ "Onde está esse homem?", perguntaram. "Não sei", respondeu ele.

[[v43-9-13]]

^<<v43-9-13,13>>^ Então levaram aos fariseus o homem que havia sido cego,

[[v43-9-14]]

^<<v43-9-14,14>>^ pois foi no sábado que Jesus misturou terra com saliva e o curou.

[[v43-9-15]]

^<<v43-9-15,15>>^ Os fariseus encheram o homem de perguntas sobre o que havia acontecido, e ele respondeu: "Ele colocou terra com saliva em meus olhos e, depois que eu me lavei, passei a enxergar!".

[[v43-9-16]]

^<<v43-9-16,16>>^ Alguns dos fariseus disseram: "Esse homem não é de Deus, pois trabalha no sábado". Outros disseram: "Mas como um pecador poderia fazer sinais como esse?". E havia entre eles uma divergência de opiniões.

[[v43-9-17]]

^<<v43-9-17,17>>^ Os fariseus voltaram a perguntar ao homem que havia sido cego: "O que você diz desse homem que o curou?". "Ele deve ser profeta", respondeu o homem.

[[v43-9-18]]

^<<v43-9-18,18>>^ Os líderes judeus se recusavam a crer que ele havia sido cego e estava curado, por isso mandaram chamar os pais dele

[[v43-9-19]]

^<<v43-9-19,19>>^ e perguntaram: "Ele é seu filho? Ele nasceu cego? Se foi, como pode ver agora?".

[[v43-9-20]]

^<<v43-9-20,20>>^ Os pais responderam: "Sabemos que ele é nosso filho e que nasceu cego,

[[v43-9-21]]

^<<v43-9-21,21>>^ mas não sabemos como pode ver agora nem quem o curou. Ele tem idade suficiente para falar por si mesmo. Perguntem a ele".

[[v43-9-22]]

^<<v43-9-22,22>>^ Seus pais disseram isso por medo dos líderes judeus, pois estes haviam anunciado que, se alguém dissesse que Jesus era o Cristo, seria expulso da sinagoga.

[[v43-9-23]]

^<<v43-9-23,23>>^ Por isso disseram: "Ele tem idade suficiente. Perguntem a ele".

[[v43-9-24]]

^<<v43-9-24,24>>^ Então, pela segunda vez, chamaram o homem que havia sido cego e lhe disseram: "Deus é quem deve receber glória por aquilo que aconteceu, pois sabemos que esse Jesus é pecador".

[[v43-9-25]]

^<<v43-9-25,25>>^ "Não sei se ele é pecador", respondeu o homem. "Mas uma coisa sei: eu era cego e agora vejo!"

[[v43-9-26]]

^<<v43-9-26,26>>^ "Mas o que ele fez?", perguntaram. "Como ele o curou?"

[[v43-9-27]]

^<<v43-9-27,27>>^ "Eu já lhes disse!", exclamou o homem. "Vocês não ouviram? Por que querem ouvir outra vez? Por acaso também querem se tornar discípulos dele?"

[[v43-9-28]]

^<<v43-9-28,28>>^ Então eles o insultaram e disseram: "Você é discípulo dele, mas nós somos discípulos de Moisés!

[[v43-9-29]]

^<<v43-9-29,29>>^ Sabemos que Deus falou a Moisés, mas nem sabemos de onde vem esse homem".

[[v43-9-30]]

^<<v43-9-30,30>>^ "Que coisa mais estranha!", respondeu o homem. "Ele curou meus olhos e vocês não sabem de onde ele vem?

[[v43-9-31]]

^<<v43-9-31,31>>^ Sabemos que Deus não atende pecadores, mas está pronto a ouvir aqueles que o adoram e fazem a sua vontade.

[[v43-9-32]]

^<<v43-9-32,32>>^ Desde o princípio do mundo, ninguém foi capaz de abrir os olhos de um cego de nascença.

[[v43-9-33]]

^<<v43-9-33,33>>^ Se esse homem não fosse de Deus, não teria conseguido fazê-lo."

[[v43-9-34]]

^<<v43-9-34,34>>^ "Você nasceu inteiramente pecador!", disseram eles. "E quer ensinar a nós?" Então o expulsaram da sinagoga.

[[v43-9-35]]

^<<v43-9-35,35>>^ Quando Jesus soube do que havia acontecido, procurou o homem e lhe disse: "Você crê no Filho do Homem?".

[[v43-9-36]]

^<<v43-9-36,36>>^ "Quem é ele, senhor?", perguntou o homem. "Eu quero crer nele."

[[v43-9-37]]

^<<v43-9-37,37>>^ Jesus respondeu: "Você o viu, e ele está falando com você!".

[[v43-9-38]]

^<<v43-9-38,38>>^ "Sim, Senhor, eu creio!", declarou o homem. E adorou a Jesus.

[[v43-9-39]]

^<<v43-9-39,39>>^ Então Jesus disse: "Eu vim a este mundo para julgar, para dar visão aos cegos e para fazer que os que veem se tornem cegos".

[[v43-9-40]]

^<<v43-9-40,40>>^ Alguns fariseus que estavam por perto o ouviram e perguntaram: "Você está dizendo que nós somos cegos?".

[[v43-9-41]]

^<<v43-9-41,41>>^ "Se vocês fossem cegos, não seriam culpados", respondeu Jesus. "Mas a culpa de vocês permanece, pois afirmam que podem ver."

'''

xref:043-joao/043-joao-008.adoc#v43-8-0[&#60; Capítulo Anterior] | <<v43-9-0,Topo>> | xref:043-joao/043-joao-010.adoc#v43-10-0[Próximo Capítulo &#62;]