include::./index.adoc[]

[[v43-16-0]]
=== João, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v43-16-1]]

^<<v43-16-1,1>>^ "Eu lhes digo estas coisas para que não desanimem da fé.

[[v43-16-2]]

^<<v43-16-2,2>>^ Pois vocês serão expulsos das sinagogas, e virá o tempo em que aqueles que os matarem pensarão que estão prestando um serviço sagrado a Deus.

[[v43-16-3]]

^<<v43-16-3,3>>^ Farão isso porque nunca conheceram nem o Pai nem a mim.

[[v43-16-4]]

^<<v43-16-4,4>>^ Sim, eu lhes digo estas coisas agora para que, quando elas acontecerem, vocês se lembrem de que os avisei. Eu não lhes disse antes porque ainda estaria com vocês mais um pouco."

[[v43-16-5]]

^<<v43-16-5,5>>^ "Agora, porém, vou para aquele que me enviou, e nenhum de vocês me pergunta para onde vou.

[[v43-16-6]]

^<<v43-16-6,6>>^ Em vez disso, entristecem-se por causa do que eu lhes disse.

[[v43-16-7]]

^<<v43-16-7,7>>^ Mas, na verdade, é melhor para vocês que eu vá, pois, se eu não for, o Encorajador não virá. Se eu for, eu o enviarei a vocês.

[[v43-16-8]]

^<<v43-16-8,8>>^ Quando ele vier, convencerá o mundo do pecado, da justiça e do juízo.

[[v43-16-9]]

^<<v43-16-9,9>>^ Do pecado, porque o mundo se recusou a crer em mim;

[[v43-16-10]]

^<<v43-16-10,10>>^ da justiça, porque eu voltarei para o Pai e não me verão mais;

[[v43-16-11]]

^<<v43-16-11,11>>^ do juízo, porque o governante deste mundo já foi condenado.

[[v43-16-12]]

^<<v43-16-12,12>>^ "Há tanta coisa que ainda quero lhes dizer, mas vocês não podem suportar agora.

[[v43-16-13]]

^<<v43-16-13,13>>^ Quando vier o Espírito da verdade, ele os conduzirá a toda a verdade. Não falará por si mesmo, mas lhes dirá o que ouviu e lhes anunciará o que ainda está para acontecer.

[[v43-16-14]]

^<<v43-16-14,14>>^ Ele me glorificará porque lhes contará tudo que receber de mim.

[[v43-16-15]]

^<<v43-16-15,15>>^ Tudo que pertence ao Pai é meu; por isso eu disse: ‘O Espírito lhes contará tudo que receber de mim’."

[[v43-16-16]]

^<<v43-16-16,16>>^ "Mais um pouco e vocês não me verão mais; algum tempo depois, me verão novamente."

[[v43-16-17]]

^<<v43-16-17,17>>^ Alguns dos discípulos perguntaram entre si: "O que ele quer dizer com ‘Mais um pouco e vocês não me verão’ e ‘algum tempo depois, me verão novamente’ e ‘vou para o Pai’?

[[v43-16-18]]

^<<v43-16-18,18>>^ E o que ele quer dizer com ‘mais um pouco’? Não entendemos".

[[v43-16-19]]

^<<v43-16-19,19>>^ Jesus, percebendo que desejavam lhe perguntar sobre essas coisas, disse: "Vocês perguntam entre si o que eu quis dizer quando falei: ‘Mais um pouco e vocês não me verão; algum tempo depois, me verão novamente’?

[[v43-16-20]]

^<<v43-16-20,20>>^ Eu lhes digo a verdade: vocês chorarão e se lamentarão pelo que acontecerá comigo, mas o mundo se alegrará. Ficarão tristes, mas sua tristeza se transformará em alegria.

[[v43-16-21]]

^<<v43-16-21,21>>^ No trabalho de parto, a mulher sente dores, mas, quando o bebê nasce, sua angústia dá lugar à alegria, pois ela trouxe ao mundo uma criança.

[[v43-16-22]]

^<<v43-16-22,22>>^ Da mesma forma, agora vocês estão tristes, mas eu os verei novamente; então se alegrarão e ninguém lhes poderá tirar essa alegria.

[[v43-16-23]]

^<<v43-16-23,23>>^ Naquele dia, não terão necessidade de me perguntar coisa alguma. Eu lhes digo a verdade: vocês pedirão diretamente ao Pai e ele atenderá, porque pediram em meu nome.

[[v43-16-24]]

^<<v43-16-24,24>>^ Vocês nunca pediram desse modo. Peçam em meu nome e receberão, e terão alegria completa.

[[v43-16-25]]

^<<v43-16-25,25>>^ "Eu lhes falei destas coisas de maneira figurativa, mas em breve deixarei de usar esse tipo de linguagem e lhes falarei claramente a respeito do Pai.

[[v43-16-26]]

^<<v43-16-26,26>>^ Então vocês pedirão em meu nome. Não digo que pedirei ao Pai em seu favor,

[[v43-16-27]]

^<<v43-16-27,27>>^ pois o próprio Pai os ama, porque vocês me amam e creem que eu vim de Deus.

[[v43-16-28]]

^<<v43-16-28,28>>^ Sim, eu vim do Pai e entrei no mundo, e agora deixo o mundo e volto para o Pai".

[[v43-16-29]]

^<<v43-16-29,29>>^ Então os discípulos disseram: "Enfim o senhor fala claramente, e não de maneira figurativa.

[[v43-16-30]]

^<<v43-16-30,30>>^ Agora entendemos que o senhor sabe todas as coisas e não há necessidade de lhe fazer perguntas. Por isso cremos que o senhor veio de Deus".

[[v43-16-31]]

^<<v43-16-31,31>>^ Jesus disse: "Enfim vocês creem?

[[v43-16-32]]

^<<v43-16-32,32>>^ Mas se aproxima o tempo, e de fato já chegou, em que vocês serão espalhados; cada um seguirá seu caminho e me deixará sozinho. Mas não ficarei sozinho, porque o Pai está comigo.

[[v43-16-33]]

^<<v43-16-33,33>>^ Eu lhes falei tudo isso para que tenham paz em mim. Aqui no mundo vocês terão aflições, mas animem-se, pois eu venci o mundo".

'''

xref:043-joao/043-joao-015.adoc#v43-15-0[&#60; Capítulo Anterior] | <<v43-16-0,Topo>> | xref:043-joao/043-joao-017.adoc#v43-17-0[Próximo Capítulo &#62;]