include::./index.adoc[]

[[v43-13-0]]
=== João, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v43-13-1]]

^<<v43-13-1,1>>^ Antes da festa da Páscoa, Jesus sabia que havia chegado sua hora de deixar este mundo e voltar para o Pai. Ele tinha amado seus discípulos durante seu ministério na terra, e os amou até o fim.

[[v43-13-2]]

^<<v43-13-2,2>>^ Estava na hora do jantar, e o diabo já havia instigado Judas, filho de Simão Iscariotes, a trair Jesus.

[[v43-13-3]]

^<<v43-13-3,3>>^ Jesus sabia que o Pai lhe dera autoridade sobre todas as coisas e que viera de Deus e voltaria para Deus.

[[v43-13-4]]

^<<v43-13-4,4>>^ Assim, levantou-se da mesa, tirou a capa e enrolou uma toalha na cintura.

[[v43-13-5]]

^<<v43-13-5,5>>^ Depois, derramou água numa bacia e começou a lavar os pés de seus discípulos, enxugando-os com a toalha que estava em sua cintura.

[[v43-13-6]]

^<<v43-13-6,6>>^ Quando Jesus chegou a Simão Pedro, este lhe disse: "O Senhor vai lavar os meus pés?".

[[v43-13-7]]

^<<v43-13-7,7>>^ Jesus respondeu: "Você não entende agora o que estou fazendo, mas algum dia entenderá".

[[v43-13-8]]

^<<v43-13-8,8>>^ "Lavar os meus pés? De jeito nenhum!", protestou Pedro. Jesus respondeu: "Se eu não os lavar, você não terá comunhão comigo".

[[v43-13-9]]

^<<v43-13-9,9>>^ Simão Pedro exclamou: "Senhor, então lave também minhas mãos e minha cabeça, e não somente os pés!".

[[v43-13-10]]

^<<v43-13-10,10>>^ Jesus respondeu: "A pessoa que tomou banho completo só precisa lavar os pés para ficar totalmente limpa. E vocês estão limpos, mas nem todos".

[[v43-13-11]]

^<<v43-13-11,11>>^ Pois Jesus sabia quem o trairia. Foi a isso que se referiu quando disse: "Nem todos vocês estão limpos".

[[v43-13-12]]

^<<v43-13-12,12>>^ Depois de lavar os pés deles, Jesus vestiu a capa novamente, retornou a seu lugar e perguntou: "Vocês entendem o que fiz?

[[v43-13-13]]

^<<v43-13-13,13>>^ Vocês me chamam ‘Mestre’ e ‘Senhor’, e têm razão, porque eu sou.

[[v43-13-14]]

^<<v43-13-14,14>>^ E uma vez que eu, seu Senhor e Mestre, lavei seus pés, vocês devem lavar os pés uns dos outros.

[[v43-13-15]]

^<<v43-13-15,15>>^ Eu lhes dei um exemplo a ser seguido. Façam como eu fiz a vocês.

[[v43-13-16]]

^<<v43-13-16,16>>^ Eu lhes digo a verdade: o escravo não é maior que o seu senhor, nem o mensageiro é mais importante que aquele que o envia.

[[v43-13-17]]

^<<v43-13-17,17>>^ Agora que vocês sabem estas coisas, serão felizes se as praticarem."

[[v43-13-18]]

^<<v43-13-18,18>>^ "Não digo estas coisas a todos vocês; conheço os que escolhi. Mas isto cumpre as Escrituras que dizem: ‘Aquele que come do meu alimento voltou-se contra mim’.

[[v43-13-19]]

^<<v43-13-19,19>>^ Eu lhes digo isso de antemão, para que, quando acontecer, vocês creiam que eu sou aquele de quem falam as Escrituras.

[[v43-13-20]]

^<<v43-13-20,20>>^ Eu lhes digo a verdade: quem recebe aquele que envio recebe a mim, e quem recebe a mim recebe o Pai, que me enviou".

[[v43-13-21]]

^<<v43-13-21,21>>^ Então Jesus sentiu profunda angústia e exclamou: "Eu lhes digo a verdade: um de vocês vai me trair!".

[[v43-13-22]]

^<<v43-13-22,22>>^ Os discípulos olharam uns para os outros, sem saber a quem ele se referia.

[[v43-13-23]]

^<<v43-13-23,23>>^ O discípulo a quem Jesus amava ocupava o lugar ao lado dele à mesa.

[[v43-13-24]]

^<<v43-13-24,24>>^ Simão Pedro lhe fez um sinal para que perguntasse a quem Jesus se referia.

[[v43-13-25]]

^<<v43-13-25,25>>^ Então o discípulo se inclinou para Jesus e perguntou: "Senhor, quem é?".

[[v43-13-26]]

^<<v43-13-26,26>>^ Jesus respondeu: "É aquele a quem eu der o pedaço de pão que molhei na tigela". E, depois de molhar o pedaço de pão, deu-o a Judas, filho de Simão Iscariotes.

[[v43-13-27]]

^<<v43-13-27,27>>^ Quando Judas comeu o pão, Satanás entrou nele. Então Jesus lhe disse: "O que você vai fazer, faça logo".

[[v43-13-28]]

^<<v43-13-28,28>>^ Nenhum dos outros à mesa entendeu o que Jesus quis dizer.

[[v43-13-29]]

^<<v43-13-29,29>>^ Como Judas era o tesoureiro, alguns imaginaram que Jesus tinha mandado que ele comprasse o necessário para a festa ou desse algum dinheiro aos pobres.

[[v43-13-30]]

^<<v43-13-30,30>>^ Judas saiu depressa, e era noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Assim que Judas saiu, Jesus disse: "Chegou a hora de o Filho do Homem ser glorificado e, por causa dele, Deus será glorificado.

[[v43-13-32]]

^<<v43-13-32,32>>^ Uma vez que Deus recebe glória por causa do Filho, ele dará ao Filho sua glória, de uma vez por todas.

[[v43-13-33]]

^<<v43-13-33,33>>^ Meus filhos, estarei com vocês apenas mais um pouco. E, como eu disse aos líderes judeus, vocês me procurarão, mas não poderão ir para onde eu vou.

[[v43-13-34]]

^<<v43-13-34,34>>^ Por isso, agora eu lhes dou um novo mandamento: Amem uns aos outros. Assim como eu os amei, vocês devem amar uns aos outros.

[[v43-13-35]]

^<<v43-13-35,35>>^ Seu amor uns pelos outros provará ao mundo que são meus discípulos".

[[v43-13-36]]

^<<v43-13-36,36>>^ Simão Pedro perguntou: "Para onde o Senhor vai?". Jesus respondeu: "Para onde vou vocês não podem ir agora, mas me seguirão mais tarde".

[[v43-13-37]]

^<<v43-13-37,37>>^ "Senhor, por que não posso ir agora?", perguntou ele. "Estou disposto a morrer pelo senhor."

[[v43-13-38]]

^<<v43-13-38,38>>^ "Morrer por mim?", disse Jesus. "Eu lhe digo a verdade, Pedro: antes que o galo cante, você me negará três vezes."

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]