include::./index.adoc[]

[[v43-19-0]]
=== João, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v43-19-1]]

^<<v43-19-1,1>>^ Então Pilatos mandou açoitar Jesus.

[[v43-19-2]]

^<<v43-19-2,2>>^ Os soldados fizeram uma coroa de espinhos e a colocaram em sua cabeça, e depois puseram nele um manto vermelho.

[[v43-19-3]]

^<<v43-19-3,3>>^ Zombavam dele, dizendo: "Salve, rei dos judeus!", e batiam em seu rosto.

[[v43-19-4]]

^<<v43-19-4,4>>^ Pilatos saiu outra vez e disse ao povo: "Agora vou trazê-lo aqui para vocês, mas que fique bem claro: eu o considero inocente".

[[v43-19-5]]

^<<v43-19-5,5>>^ Então Jesus saiu com a coroa de espinhos e o manto vermelho. "Vejam, aqui está o homem!", disse Pilatos.

[[v43-19-6]]

^<<v43-19-6,6>>^ Quando os principais sacerdotes e os guardas do templo o viram, começaram a gritar: "Crucifique-o! Crucifique-o!". "Levem-no vocês e crucifiquem-no", disse Pilatos. "Eu o considero inocente."

[[v43-19-7]]

^<<v43-19-7,7>>^ Os líderes judeus responderam: "Pela nossa lei ele deve morrer, pois chamou a si mesmo de Filho de Deus".

[[v43-19-8]]

^<<v43-19-8,8>>^ Quando Pilatos ouviu isso, ficou ainda mais amedrontado.

[[v43-19-9]]

^<<v43-19-9,9>>^ Levou Jesus de volta para dentro do palácio e lhe perguntou: "De onde você vem?". Jesus, porém, não respondeu.

[[v43-19-10]]

^<<v43-19-10,10>>^ "Por que você se nega a falar comigo?", perguntou Pilatos. "Não sabe que tenho autoridade para soltá-lo ou crucificá-lo?"

[[v43-19-11]]

^<<v43-19-11,11>>^ Jesus disse: "Você não teria autoridade alguma sobre mim se esta não lhe fosse dada de cima. Portanto, aquele que me entregou a você tem um pecado maior".

[[v43-19-12]]

^<<v43-19-12,12>>^ Então Pilatos tentou libertá-lo, mas os líderes judeus gritavam: "Se o senhor soltar este homem, não é amigo de César! Quem se declara rei se rebela contra César".

[[v43-19-13]]

^<<v43-19-13,13>>^ Ao ouvir isso, Pilatos trouxe Jesus para fora novamente e se sentou no tribunal, na plataforma chamada "Pavimento de Pedras" (em aramaico, Gábata ).

[[v43-19-14]]

^<<v43-19-14,14>>^ Era por volta de meio-dia, no dia da preparação para a Páscoa. E Pilatos disse ao povo: "Vejam, aqui está o seu rei!".

[[v43-19-15]]

^<<v43-19-15,15>>^ "Fora com ele!", gritaram. "Fora com ele! Crucifique-o!" "O quê? Crucificar o seu rei?", perguntou Pilatos. Em resposta, os principais sacerdotes gritaram: "Não temos outro rei além de César!".

[[v43-19-16]]

^<<v43-19-16,16>>^ Então Pilatos lhes entregou Jesus para ser crucificado. E eles levaram Jesus.

[[v43-19-17]]

^<<v43-19-17,17>>^ Carregando a própria cruz, Jesus foi ao local chamado Lugar da Caveira (em aramaico, Gólgota ).

[[v43-19-18]]

^<<v43-19-18,18>>^ Ali eles o pregaram na cruz. Outros dois foram crucificados com Jesus, um de cada lado e ele no meio.

[[v43-19-19]]

^<<v43-19-19,19>>^ Pilatos colocou no alto da cruz uma placa que dizia: "Jesus, o nazareno, Rei dos judeus".

[[v43-19-20]]

^<<v43-19-20,20>>^ O lugar onde Jesus foi crucificado ficava perto da cidade, e a placa estava escrita em aramaico, latim e grego, de modo que muitos judeus podiam ler a inscrição.

[[v43-19-21]]

^<<v43-19-21,21>>^ Os principais sacerdotes disseram a Pilatos: "Mude a inscrição de ‘Rei dos judeus’ para ‘Ele disse: Eu sou o rei dos judeus’".

[[v43-19-22]]

^<<v43-19-22,22>>^ Pilatos respondeu: "O que escrevi, escrevi".

[[v43-19-23]]

^<<v43-19-23,23>>^ Depois que os soldados crucificaram Jesus, repartiram suas roupas em quatro partes, uma para cada um deles. Também pegaram sua túnica, mas ela era sem costura, tecida numa única peça, de alto a baixo.

[[v43-19-24]]

^<<v43-19-24,24>>^ Por isso disseram: "Em vez de rasgá-la, vamos tirar sortes para ver quem ficará com ela". Isso cumpriu as Escrituras que dizem: "Repartiram minhas roupas entre si e lançaram sortes por minha veste". E foi o que fizeram.

[[v43-19-25]]

^<<v43-19-25,25>>^ Perto da cruz estavam a mãe de Jesus, a irmã dela, Maria, esposa de Clopas, e Maria Madalena.

[[v43-19-26]]

^<<v43-19-26,26>>^ Quando Jesus viu sua mãe ali, ao lado do discípulo a quem ele amava, disse-lhe: "Mulher, este é seu filho".

[[v43-19-27]]

^<<v43-19-27,27>>^ E, ao discípulo, disse: "Esta é sua mãe". Daquele momento em diante, o discípulo a recebeu em sua casa.

[[v43-19-28]]

^<<v43-19-28,28>>^ Jesus sabia que sua missão havia terminado e, para cumprir as Escrituras, disse: "Estou com sede".

[[v43-19-29]]

^<<v43-19-29,29>>^ Havia ali uma vasilha com vinagre, de modo que ensoparam uma esponja no vinagre, a colocaram na ponta de um caniço de hissopo e a ergueram até os lábios de Jesus.

[[v43-19-30]]

^<<v43-19-30,30>>^ Depois de prová-la, Jesus disse: "Está consumado". Então, inclinou a cabeça e entregou o espírito.

[[v43-19-31]]

^<<v43-19-31,31>>^ Era o Dia da Preparação, e os líderes judeus não queriam que os corpos ficassem pendurados ali até o dia seguinte, que seria um sábado muito especial. Por isso pediram a Pilatos que mandasse quebrar as pernas dos crucificados e removê-los.

[[v43-19-32]]

^<<v43-19-32,32>>^ Assim, os soldados vieram e quebraram as pernas dos dois homens crucificados com Jesus.

[[v43-19-33]]

^<<v43-19-33,33>>^ Mas, quando chegaram a Jesus, viram que ele já estava morto e, portanto, não quebraram suas pernas.

[[v43-19-34]]

^<<v43-19-34,34>>^ Um dos soldados, porém, furou seu lado com uma lança e, no mesmo instante, correu sangue com água.

[[v43-19-35]]

^<<v43-19-35,35>>^ Essa informação provém de uma testemunha ocular. Ela diz a verdade para que vocês também creiam.

[[v43-19-36]]

^<<v43-19-36,36>>^ Essas coisas aconteceram para que se cumprissem as Escrituras que dizem: "Nenhum dos seus ossos será quebrado",

[[v43-19-37]]

^<<v43-19-37,37>>^ e "Olharão para aquele a quem transpassaram".

[[v43-19-38]]

^<<v43-19-38,38>>^ Depois disso, José de Arimateia, que tinha sido discípulo secreto de Jesus porque temia os líderes judeus, pediu autorização a Pilatos para tirar da cruz o corpo de Jesus. Quando Pilatos lhe deu permissão, José veio e levou o corpo.

[[v43-19-39]]

^<<v43-19-39,39>>^ Estava com ele Nicodemos, o homem que tinha ido conversar com Jesus à noite. Nicodemos trouxe cerca de 35 litros de óleo perfumado feito com mirra e aloés.

[[v43-19-40]]

^<<v43-19-40,40>>^ Seguindo os costumes judaicos de sepultamento, envolveram o corpo de Jesus em lençóis compridos de linho, junto com essas especiarias.

[[v43-19-41]]

^<<v43-19-41,41>>^ O local da crucificação ficava próximo a um jardim, onde havia um túmulo novo que nunca tinha sido usado.

[[v43-19-42]]

^<<v43-19-42,42>>^ Como era o Dia da Preparação para a Páscoa judaica, e uma vez que o túmulo ficava perto, colocaram Jesus ali.

'''

xref:043-joao/043-joao-018.adoc#v43-18-0[&#60; Capítulo Anterior] | <<v43-19-0,Topo>> | xref:043-joao/043-joao-020.adoc#v43-20-0[Próximo Capítulo &#62;]