include::./index.adoc[]

[[v43-18-0]]
=== João, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v43-18-1]]

^<<v43-18-1,1>>^ Depois de dizer essas coisas, Jesus atravessou com seus discípulos o vale de Cedrom e entrou num bosque de oliveiras.

[[v43-18-2]]

^<<v43-18-2,2>>^ Judas, o traidor, conhecia aquele lugar, pois Jesus tinha ido muitas vezes ali com seus discípulos.

[[v43-18-3]]

^<<v43-18-3,3>>^ Os principais sacerdotes e fariseus tinham dado a Judas um destacamento de soldados e alguns guardas do templo para acompanhá-lo. Eles chegaram ao bosque de oliveiras com tochas, lanternas e armas.

[[v43-18-4]]

^<<v43-18-4,4>>^ Jesus, sabendo tudo que ia lhe acontecer, foi ao encontro deles. "A quem vocês procuram?", perguntou.

[[v43-18-5]]

^<<v43-18-5,5>>^ "A Jesus, o nazareno", responderam. "Sou eu", disse ele. (Judas, o traidor, estava com eles.)

[[v43-18-6]]

^<<v43-18-6,6>>^ Quando Jesus disse: "Sou eu", todos recuaram e caíram para trás, no chão.

[[v43-18-7]]

^<<v43-18-7,7>>^ Mais uma vez, ele perguntou: "A quem vocês procuram?". E, novamente, eles responderam: "A Jesus, o nazareno".

[[v43-18-8]]

^<<v43-18-8,8>>^ "Já lhes disse que sou eu", respondeu ele. "E, uma vez que é a mim que vocês procuram, deixem estes outros irem embora."

[[v43-18-9]]

^<<v43-18-9,9>>^ Ele fez isso para cumprir sua própria declaração: "Não perdi um só de todos que me deste".

[[v43-18-10]]

^<<v43-18-10,10>>^ Então Simão Pedro puxou uma espada e cortou a orelha direita de Malco, o servo do sumo sacerdote.

[[v43-18-11]]

^<<v43-18-11,11>>^ Jesus, porém, disse a Pedro: "Guarde sua espada de volta na bainha. Acaso não beberei o cálice que o Pai me deu?".

[[v43-18-12]]

^<<v43-18-12,12>>^ Assim, os soldados, seu comandante e os guardas do templo prenderam Jesus e o amarraram.

[[v43-18-13]]

^<<v43-18-13,13>>^ Primeiro, levaram Jesus a Anás, pois era sogro de Caifás, o sumo sacerdote naquele ano.

[[v43-18-14]]

^<<v43-18-14,14>>^ Caifás foi quem tinha dito aos outros líderes judeus: "É melhor que um homem morra pelo povo".

[[v43-18-15]]

^<<v43-18-15,15>>^ Simão Pedro e outro discípulo seguiram Jesus. Esse outro discípulo era conhecido do sumo sacerdote, de modo que lhe permitiram entrar com Jesus no pátio do sumo sacerdote.

[[v43-18-16]]

^<<v43-18-16,16>>^ Pedro teve de ficar do lado de fora do portão. Então o discípulo conhecido do sumo sacerdote falou com a moça que tomava conta do portão, e ela deixou Pedro entrar.

[[v43-18-17]]

^<<v43-18-17,17>>^ A moça perguntou a Pedro: "Você não é um dos discípulos daquele homem?". "Não", respondeu ele. "Não sou."

[[v43-18-18]]

^<<v43-18-18,18>>^ Como fazia frio, os servos da casa e os guardas tinham feito uma fogueira com carvão e se esquentavam ao redor dela. Pedro estava ali com eles, esquentando-se também.

[[v43-18-19]]

^<<v43-18-19,19>>^ Lá dentro, o sumo sacerdote começou a interrogar Jesus a respeito de seus discípulos e de seus ensinamentos.

[[v43-18-20]]

^<<v43-18-20,20>>^ Jesus respondeu: "Falei abertamente a todos. Ensinei regularmente nas sinagogas e no templo, onde o povo se reúne.

[[v43-18-21]]

^<<v43-18-21,21>>^ Por que você me interroga? Pergunte aos que me ouviram. Eles sabem o que eu disse".

[[v43-18-22]]

^<<v43-18-22,22>>^ Um dos guardas do templo que estava perto bateu no rosto de Jesus, dizendo: "Isso é maneira de responder ao sumo sacerdote?".

[[v43-18-23]]

^<<v43-18-23,23>>^ Jesus respondeu: "Se eu disse algo errado, prove. Mas, se digo a verdade, por que você me bate?".

[[v43-18-24]]

^<<v43-18-24,24>>^ Então Anás amarrou Jesus e o enviou a Caifás, o sumo sacerdote.

[[v43-18-25]]

^<<v43-18-25,25>>^ Nesse meio-tempo, enquanto Simão Pedro estava perto da fogueira, esquentando-se, perguntaram-lhe novamente: "Você não é um dos discípulos dele?". Ele negou, dizendo: "Não sou".

[[v43-18-26]]

^<<v43-18-26,26>>^ Mas um dos servos da casa do sumo sacerdote, parente do homem de quem Pedro havia cortado a orelha, perguntou: "Eu não vi você no bosque de oliveiras com Jesus?".

[[v43-18-27]]

^<<v43-18-27,27>>^ Mais uma vez, Pedro negou. E, no mesmo instante, o galo cantou.

[[v43-18-28]]

^<<v43-18-28,28>>^ O julgamento de Jesus diante de Caifás terminou nas primeiras horas da manhã. Em seguida, foi levado ao palácio do governador romano. Seus acusadores não entraram, pois se contaminariam e não poderiam celebrar a Páscoa.

[[v43-18-29]]

^<<v43-18-29,29>>^ Então o governador Pilatos foi até eles e perguntou: "Qual é a acusação contra este homem?".

[[v43-18-30]]

^<<v43-18-30,30>>^ Eles responderam: "Não o teríamos entregue ao senhor se ele não fosse um criminoso".

[[v43-18-31]]

^<<v43-18-31,31>>^ "Então levem-no embora e julguem-no de acordo com a lei de vocês", disse Pilatos. "Só os romanos têm direito de executar alguém", responderam os líderes judeus.

[[v43-18-32]]

^<<v43-18-32,32>>^ Assim cumpriu-se a previsão de Jesus sobre como ele morreria.

[[v43-18-33]]

^<<v43-18-33,33>>^ Então Pilatos entrou novamente no palácio e ordenou que trouxessem Jesus. "Você é o rei dos judeus?", perguntou ele.

[[v43-18-34]]

^<<v43-18-34,34>>^ Jesus respondeu: "Essa pergunta é sua ou outros lhe falaram a meu respeito?".

[[v43-18-35]]

^<<v43-18-35,35>>^ "Acaso sou judeu?", disse Pilatos. "Seu próprio povo e os principais sacerdotes o trouxeram a mim para ser julgado. Por quê? O que você fez?"

[[v43-18-36]]

^<<v43-18-36,36>>^ Jesus respondeu: "Meu reino não é deste mundo. Se fosse, meus seguidores lutariam para impedir que eu fosse entregue aos líderes judeus. Mas meu reino não procede deste mundo".

[[v43-18-37]]

^<<v43-18-37,37>>^ Pilatos disse: "Então você é rei?". "Você diz que sou rei", respondeu Jesus. "De fato, nasci e vim ao mundo para testemunhar a verdade. Todos que amam a verdade ouvem minha voz."

[[v43-18-38]]

^<<v43-18-38,38>>^ Pilatos perguntou: "Que é a verdade?". Depois que disse isso, Pilatos saiu outra vez para onde estava o povo e declarou: "Ele não é culpado de crime algum.

[[v43-18-39]]

^<<v43-18-39,39>>^ Mas vocês têm o costume de pedir que eu solte um prisioneiro cada ano, na Páscoa. Vocês querem que eu solte o ‘rei dos judeus’?".

[[v43-18-40]]

^<<v43-18-40,40>>^ Eles, porém, gritaram: "Não! Esse homem, não! Queremos Barrabás!". Esse Barrabás era um criminoso.

'''

xref:043-joao/043-joao-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-joao/043-joao-019.adoc#v43-19-0[Próximo Capítulo &#62;]