include::./index.adoc[]

[[v43-10-0]]
=== João, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v43-10-1]]

^<<v43-10-1,1>>^ "Eu lhes digo a verdade: quem entra no curral das ovelhas às escondidas, por sobre a cerca, em vez de passar pela porta, é certamente ladrão e assaltante!

[[v43-10-2]]

^<<v43-10-2,2>>^ Mas quem entra pela porta é o pastor das ovelhas.

[[v43-10-3]]

^<<v43-10-3,3>>^ O porteiro lhe abre a porta, e as ovelhas reconhecem sua voz e se aproximam. Ele chama suas ovelhas pelo nome e as conduz para fora.

[[v43-10-4]]

^<<v43-10-4,4>>^ Depois de reuni-las, vai adiante delas, e elas o seguem porque conhecem sua voz.

[[v43-10-5]]

^<<v43-10-5,5>>^ Nunca seguirão um desconhecido; antes, fugirão dele, pois não reconhecem sua voz."

[[v43-10-6]]

^<<v43-10-6,6>>^ Os que ouviram Jesus usar essa ilustração não entenderam o que ele quis dizer,

[[v43-10-7]]

^<<v43-10-7,7>>^ por isso ele a explicou: "Eu lhes digo a verdade: eu sou a porta das ovelhas.

[[v43-10-8]]

^<<v43-10-8,8>>^ Todos que vieram antes de mim eram ladrões e assaltantes, mas as ovelhas não os ouviram.

[[v43-10-9]]

^<<v43-10-9,9>>^ Sim, eu sou a porta. Quem entrar por mim será salvo. Entrará e sairá e encontrará pasto.

[[v43-10-10]]

^<<v43-10-10,10>>^ O ladrão vem para roubar, matar e destruir. Eu vim para lhes dar vida, uma vida plena, que satisfaz.

[[v43-10-11]]

^<<v43-10-11,11>>^ "Eu sou o bom pastor. O bom pastor sacrifica sua vida pelas ovelhas.

[[v43-10-12]]

^<<v43-10-12,12>>^ O empregado foge quando vê um lobo se aproximar. Abandona as ovelhas porque elas não lhe pertencem e ele não é seu pastor. Então o lobo as ataca e dispersa o rebanho.

[[v43-10-13]]

^<<v43-10-13,13>>^ O empregado foge porque trabalha apenas por dinheiro e não se importa de fato com as ovelhas.

[[v43-10-14]]

^<<v43-10-14,14>>^ "Eu sou o bom pastor. Conheço minhas ovelhas, e elas me conhecem,

[[v43-10-15]]

^<<v43-10-15,15>>^ assim como meu Pai me conhece e eu o conheço; e eu sacrifico minha vida pelas ovelhas.

[[v43-10-16]]

^<<v43-10-16,16>>^ Tenho outras ovelhas, que não estão neste curral. Devo trazê-las também. Elas ouvirão minha voz, e haverá um só rebanho e um só pastor.

[[v43-10-17]]

^<<v43-10-17,17>>^ "O Pai me ama, pois sacrifico minha vida para tomá-la de volta.

[[v43-10-18]]

^<<v43-10-18,18>>^ Ninguém a tira de mim, mas eu mesmo a dou. Tenho autoridade para entregá-la e também para tomá-la de volta, pois foi isso que meu Pai ordenou".

[[v43-10-19]]

^<<v43-10-19,19>>^ Quando Jesus disse essas coisas, as opiniões dos judeus a respeito dele se dividiram outra vez.

[[v43-10-20]]

^<<v43-10-20,20>>^ Alguns diziam: "Ele está possuído por demônio e está louco. Por que ouvi-lo?".

[[v43-10-21]]

^<<v43-10-21,21>>^ Outros diziam: "Ele não fala como alguém que está possuído por demônio. Pode um demônio abrir os olhos dos cegos?".

[[v43-10-22]]

^<<v43-10-22,22>>^ Era inverno, e Jesus estava em Jerusalém na celebração da Festa da Dedicação.

[[v43-10-23]]

^<<v43-10-23,23>>^ Ele caminhava pelo templo, na parte conhecida como Pórtico de Salomão,

[[v43-10-24]]

^<<v43-10-24,24>>^ quando os líderes judeus o rodearam e perguntaram: "Quanto tempo vai nos deixar em suspense? Se você é o Cristo, diga-nos claramente".

[[v43-10-25]]

^<<v43-10-25,25>>^ Jesus respondeu: "Eu já lhes disse, e vocês não creram em mim. A prova são as obras que realizo em nome de meu Pai.

[[v43-10-26]]

^<<v43-10-26,26>>^ Mas vocês não creem em mim porque não são minhas ovelhas.

[[v43-10-27]]

^<<v43-10-27,27>>^ Minhas ovelhas ouvem a minha voz; eu as conheço, e elas me seguem.

[[v43-10-28]]

^<<v43-10-28,28>>^ Eu lhes dou a vida eterna, e elas nunca morrerão. Ninguém pode arrancá-las de minha mão,

[[v43-10-29]]

^<<v43-10-29,29>>^ pois meu Pai as deu a mim, e ele é mais poderoso que todos. Ninguém pode arrancá-las da mão de meu Pai.

[[v43-10-30]]

^<<v43-10-30,30>>^ O Pai e eu somos um".

[[v43-10-31]]

^<<v43-10-31,31>>^ Mais uma vez, os líderes judeus pegaram pedras para atirar nele.

[[v43-10-32]]

^<<v43-10-32,32>>^ Jesus disse: "Por orientação de meu Pai, eu fiz muitas boas obras. Por qual delas vocês querem me apedrejar?".

[[v43-10-33]]

^<<v43-10-33,33>>^ Eles responderam: "Não vamos apedrejá-lo por nenhuma boa obra, mas por blasfêmia. Você, um simples homem, afirma que é Deus!".

[[v43-10-34]]

^<<v43-10-34,34>>^ Jesus respondeu: "As próprias Escrituras de vocês afirmam que Deus disse a certos líderes do povo: ‘Eu digo: vocês são deuses!’.

[[v43-10-35]]

^<<v43-10-35,35>>^ E vocês sabem que as Escrituras não podem ser alteradas. Portanto, se aqueles que receberam a mensagem de Deus foram chamados de ‘deuses’,

[[v43-10-36]]

^<<v43-10-36,36>>^ por que vocês consideram blasfêmia quando eu digo: ‘Eu sou o Filho de Deus’? Afinal, o Pai me consagrou e me enviou ao mundo.

[[v43-10-37]]

^<<v43-10-37,37>>^ Não creiam em mim se não realizo as obras de meu Pai.

[[v43-10-38]]

^<<v43-10-38,38>>^ Mas, se as realizo, creiam na prova, que são as obras, mesmo que não creiam em mim. Então vocês saberão e entenderão que o Pai está em mim, e que eu estou no Pai".

[[v43-10-39]]

^<<v43-10-39,39>>^ Novamente, tentaram prendê-lo, mas ele escapou e os deixou.

[[v43-10-40]]

^<<v43-10-40,40>>^ Foi para o outro lado do rio Jordão, perto do lugar onde João batizava no início, e ficou ali por algum tempo.

[[v43-10-41]]

^<<v43-10-41,41>>^ Muitos o seguiram, comentando entre si: "João não realizou sinais, mas tudo que ele disse a respeito deste homem se cumpriu".

[[v43-10-42]]

^<<v43-10-42,42>>^ E muitos ali creram em Jesus.

'''

xref:043-joao/043-joao-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-joao/043-joao-011.adoc#v43-11-0[Próximo Capítulo &#62;]