include::./index.adoc[]

[[v43-8-0]]
=== João, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v43-8-1]]

^<<v43-8-1,1>>^ Jesus voltou ao monte das Oliveiras,

[[v43-8-2]]

^<<v43-8-2,2>>^ mas na manhã seguinte, bem cedo, estava outra vez no templo. Logo se reuniu uma multidão, e ele se sentou e a ensinou.

[[v43-8-3]]

^<<v43-8-3,3>>^ Então os mestres da lei e os fariseus lhe trouxeram uma mulher pega em adultério e a colocaram diante da multidão.

[[v43-8-4]]

^<<v43-8-4,4>>^ "Mestre, esta mulher foi pega no ato de adultério", disseram eles a Jesus.

[[v43-8-5]]

^<<v43-8-5,5>>^ "A lei de Moisés ordena que ela seja apedrejada. O que o senhor diz?"

[[v43-8-6]]

^<<v43-8-6,6>>^ Procuravam apanhá-lo numa armadilha, ao fazê-lo dizer algo que pudessem usar contra ele. Jesus, porém, apenas se inclinou e começou a escrever com o dedo na terra.

[[v43-8-7]]

^<<v43-8-7,7>>^ Eles continuaram a exigir uma resposta, de modo que ele se levantou e disse: "Aquele de vocês que nunca pecou atire a primeira pedra".

[[v43-8-8]]

^<<v43-8-8,8>>^ Então inclinou-se novamente e voltou a escrever na terra.

[[v43-8-9]]

^<<v43-8-9,9>>^ Quando ouviram isso, foram saindo, um de cada vez, começando pelos mais velhos, até que só restaram Jesus e a mulher no meio da multidão.

[[v43-8-10]]

^<<v43-8-10,10>>^ Então Jesus se levantou de novo e disse à mulher: "Onde estão seus acusadores? Nenhum deles a condenou?".

[[v43-8-11]]

^<<v43-8-11,11>>^ "Não, Senhor", respondeu ela. E Jesus disse: "Eu também não a condeno. Vá e não peque mais".

[[v43-8-12]]

^<<v43-8-12,12>>^ Jesus voltou a falar ao povo e disse: "Eu sou a luz do mundo. Se vocês me seguirem, não andarão no escuro, pois terão a luz da vida".

[[v43-8-13]]

^<<v43-8-13,13>>^ Os fariseus disseram: "Você faz essas declarações a respeito de si mesmo! Seu testemunho não é válido".

[[v43-8-14]]

^<<v43-8-14,14>>^ Jesus respondeu: "Meu testemunho é válido, embora eu mesmo o dê, pois eu sei de onde vim e para onde vou, mas vocês não sabem de onde vim nem para onde vou.

[[v43-8-15]]

^<<v43-8-15,15>>^ Vocês julgam por padrões humanos, mas eu não julgo ninguém.

[[v43-8-16]]

^<<v43-8-16,16>>^ E, mesmo que o fizesse, meu julgamento seria correto, pois não estou sozinho. O Pai, que me enviou, está comigo.

[[v43-8-17]]

^<<v43-8-17,17>>^ A lei de vocês diz que, se duas pessoas concordarem sobre alguma coisa, seu testemunho é aceito como fato.

[[v43-8-18]]

^<<v43-8-18,18>>^ Eu sou uma testemunha, e meu Pai, que me enviou, é a outra".

[[v43-8-19]]

^<<v43-8-19,19>>^ "Onde está seu Pai?", perguntaram eles. Jesus respondeu: "Uma vez que vocês não sabem quem sou eu, não sabem quem é meu Pai. Se vocês me conhecessem, também conheceriam meu Pai".

[[v43-8-20]]

^<<v43-8-20,20>>^ Jesus fez essas declarações enquanto ensinava na parte do templo onde eram colocadas as ofertas. No entanto, não foi preso, pois ainda não havia chegado sua hora.

[[v43-8-21]]

^<<v43-8-21,21>>^ Mais tarde, Jesus lhes disse outra vez: "Eu vou embora. Vocês procurarão por mim, mas morrerão em seus pecados. Não podem ir para onde eu vou".

[[v43-8-22]]

^<<v43-8-22,22>>^ Os judeus perguntaram: "Será que ele está planejando cometer suicídio? A que ele se refere quando diz: ‘Não podem ir para onde eu vou’?".

[[v43-8-23]]

^<<v43-8-23,23>>^ Jesus prosseguiu: "Vocês são daqui de baixo; eu sou lá de cima. Vocês pertencem a este mundo; eu não.

[[v43-8-24]]

^<<v43-8-24,24>>^ Foi por isso que eu disse que vocês morrerão em seus pecados, pois a menos que creiam que eu sou lá de cima, morrerão em seus pecados".

[[v43-8-25]]

^<<v43-8-25,25>>^ "Quem é você?", perguntaram eles. Jesus respondeu: "Sou aquele que sempre afirmei ser.

[[v43-8-26]]

^<<v43-8-26,26>>^ Tenho muito que dizer e julgar a respeito de vocês, mas não o farei. Digo ao mundo apenas o que ouvi daquele que me enviou, e ele é inteiramente verdadeiro".

[[v43-8-27]]

^<<v43-8-27,27>>^ Ainda assim, não entenderam que ele lhes falava a respeito do Pai.

[[v43-8-28]]

^<<v43-8-28,28>>^ Então Jesus disse: "Quando vocês me levantarem, entenderão que eu sou o Filho do Homem. Não faço coisa alguma por minha própria conta; digo apenas o que o Pai me ensinou.

[[v43-8-29]]

^<<v43-8-29,29>>^ E aquele que me enviou está comigo; ele não me abandonou, pois sempre faço o que lhe agrada".

[[v43-8-30]]

^<<v43-8-30,30>>^ Muitos que o ouviram dizer essas coisas creram nele.

[[v43-8-31]]

^<<v43-8-31,31>>^ Jesus disse aos judeus que creram nele: "Vocês são verdadeiramente meus discípulos se permanecerem fiéis a meus ensinamentos.

[[v43-8-32]]

^<<v43-8-32,32>>^ Então conhecerão a verdade, e a verdade os libertará".

[[v43-8-33]]

^<<v43-8-33,33>>^ "Mas somos descendentes de Abraão", disseram eles. "Nunca fomos escravos de ninguém. O que quer dizer com ‘Vocês serão libertos’?"

[[v43-8-34]]

^<<v43-8-34,34>>^ Jesus respondeu: "Eu lhes digo a verdade: todo o que peca é escravo do pecado.

[[v43-8-35]]

^<<v43-8-35,35>>^ O escravo não é membro permanente da família, mas o filho faz parte da família, para sempre.

[[v43-8-36]]

^<<v43-8-36,36>>^ Portanto, se o Filho os libertar, vocês serão livres de fato.

[[v43-8-37]]

^<<v43-8-37,37>>^ Sim, eu sei que vocês são descendentes de Abraão. E, no entanto, procuram me matar, pois não há lugar em seu coração para a minha mensagem.

[[v43-8-38]]

^<<v43-8-38,38>>^ Eu lhes digo o que vi quando estava com meu Pai, mas vocês seguem o conselho do pai de vocês".

[[v43-8-39]]

^<<v43-8-39,39>>^ "Nosso pai é Abraão!", declararam eles. Jesus respondeu: "Se vocês fossem, de fato, filhos de Abraão, seguiriam o exemplo dele.

[[v43-8-40]]

^<<v43-8-40,40>>^ Em vez disso, procuram me matar porque eu lhes disse a verdade que ouvi de Deus. Abraão nunca fez isso.

[[v43-8-41]]

^<<v43-8-41,41>>^ Vocês estão imitando seu verdadeiro pai". "Não somos filhos ilegítimos!", retrucaram. "O próprio Deus é nosso verdadeiro Pai!"

[[v43-8-42]]

^<<v43-8-42,42>>^ Jesus lhes disse: "Se Deus fosse seu Pai, vocês me amariam, porque eu venho até vocês da parte de Deus. Não estou aqui por minha própria conta, mas ele me enviou.

[[v43-8-43]]

^<<v43-8-43,43>>^ Por que vocês não entendem o que eu digo? É porque nem sequer conseguem me ouvir!

[[v43-8-44]]

^<<v43-8-44,44>>^ Pois são filhos de seu pai, o diabo, e gostam de fazer as coisas perversas que ele deseja. Ele foi assassino desde o princípio. Sempre odiou a verdade, pois não há verdade alguma nele. Quando ele mente, age de acordo com seu caráter, pois é mentiroso e pai da mentira.

[[v43-8-45]]

^<<v43-8-45,45>>^ Portanto, quando eu digo a verdade, é natural que não creiam em mim!

[[v43-8-46]]

^<<v43-8-46,46>>^ Qual de vocês pode me acusar de pecado? E, uma vez que lhes digo a verdade, por que não creem em mim?

[[v43-8-47]]

^<<v43-8-47,47>>^ Quem pertence a Deus ouve as palavras de Deus. Mas vocês não ouvem, pois não pertencem a Deus".

[[v43-8-48]]

^<<v43-8-48,48>>^ "Samaritano endemoninhado!", responderam os líderes judeus. "Não temos dito desde o início que está possuído por demônio?"

[[v43-8-49]]

^<<v43-8-49,49>>^ "Não tenho em mim demônio algum", disse Jesus. "Pelo contrário, honro meu Pai, e vocês me desonram.

[[v43-8-50]]

^<<v43-8-50,50>>^ Eu não procuro minha própria glória; há quem a procure para mim, e ele é o Juiz.

[[v43-8-51]]

^<<v43-8-51,51>>^ Eu lhes digo a verdade: quem obedecer a meu ensino jamais morrerá!"

[[v43-8-52]]

^<<v43-8-52,52>>^ Os líderes judeus disseram: "Agora sabemos que você está possuído por demônio. Até Abraão e os profetas morreram, mas você diz: ‘Quem obedecer a meu ensino jamais morrerá!’.

[[v43-8-53]]

^<<v43-8-53,53>>^ Por acaso você é maior que nosso pai Abraão? Ele morreu, assim como os profetas. Quem você pensa que é?".

[[v43-8-54]]

^<<v43-8-54,54>>^ Jesus respondeu: "Se eu quisesse glória para mim mesmo, essa glória não contaria. Mas é meu Pai quem me glorifica. Vocês dizem: ‘Ele é nosso Deus’,

[[v43-8-55]]

^<<v43-8-55,55>>^ mas nem o conhecem. Eu o conheço. Se eu dissesse que não o conheço, seria tão mentiroso quanto vocês! Mas eu o conheço e lhe obedeço.

[[v43-8-56]]

^<<v43-8-56,56>>^ Seu pai Abraão exultou com a expectativa da minha vinda. Ele a viu e se alegrou".

[[v43-8-57]]

^<<v43-8-57,57>>^ Os líderes judeus disseram: "Você não tem nem cinquenta anos. Como pode dizer que viu Abraão?".

[[v43-8-58]]

^<<v43-8-58,58>>^ Jesus respondeu: "Eu lhes digo a verdade: antes mesmo de Abraão nascer, Eu Sou!".

[[v43-8-59]]

^<<v43-8-59,59>>^ Então apanharam pedras para atirar em Jesus, mas ele se ocultou deles e saiu do templo.

'''

xref:043-joao/043-joao-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-joao/043-joao-009.adoc#v43-9-0[Próximo Capítulo &#62;]