include::./index.adoc[]

[[v43-5-0]]
=== João, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v43-5-1]]

^<<v43-5-1,1>>^ Depois disso, Jesus voltou a Jerusalém para uma das festas religiosas dos judeus.

[[v43-5-2]]

^<<v43-5-2,2>>^ Dentro da cidade, junto à porta das Ovelhas, ficava o tanque de Betesda, com cinco pátios cobertos.

[[v43-5-3]]

^<<v43-5-3,3>>^ Ficavam ali cegos, mancos e paralíticos, uma multidão de enfermos, esperando um movimento da água,

[[v43-5-4]]

^<<v43-5-4,4>>^ pois um anjo do Senhor descia de vez em quando e agitava a água. O primeiro que entrava no tanque após a água ser agitada era curado de qualquer enfermidade que tivesse.

[[v43-5-5]]

^<<v43-5-5,5>>^ Um dos homens ali estava doente havia 38 anos.

[[v43-5-6]]

^<<v43-5-6,6>>^ Quando Jesus o viu e soube que estava enfermo por tanto tempo, perguntou-lhe: "Você gostaria de ser curado?".

[[v43-5-7]]

^<<v43-5-7,7>>^ O homem respondeu: "Não consigo, senhor, pois não tenho quem me coloque no tanque quando a água se agita. Alguém sempre chega antes de mim".

[[v43-5-8]]

^<<v43-5-8,8>>^ Jesus lhe disse: "Levante-se, pegue sua maca e ande!".

[[v43-5-9]]

^<<v43-5-9,9>>^ No mesmo instante, o homem ficou curado. Ele pegou sua maca e começou a andar. Uma vez que esse milagre aconteceu no sábado,

[[v43-5-10]]

^<<v43-5-10,10>>^ os líderes judeus disseram ao homem que havia sido curado: "Hoje é sábado! A lei não permite que você carregue essa maca!".

[[v43-5-11]]

^<<v43-5-11,11>>^ Mas ele respondeu: "O homem que me curou disse: ‘Pegue sua maca e ande’".

[[v43-5-12]]

^<<v43-5-12,12>>^ "Quem foi que lhe disse uma coisa dessas?", perguntaram eles.

[[v43-5-13]]

^<<v43-5-13,13>>^ O homem não sabia, pois Jesus havia desaparecido no meio da multidão.

[[v43-5-14]]

^<<v43-5-14,14>>^ Mais tarde, Jesus o encontrou no templo e lhe disse: "Agora você está curado; deixe de pecar, para que nada pior lhe aconteça".

[[v43-5-15]]

^<<v43-5-15,15>>^ O homem foi até os líderes judeus e lhes disse que tinha sido Jesus quem o havia curado.

[[v43-5-16]]

^<<v43-5-16,16>>^ Então os líderes judeus começaram a perseguir Jesus por não respeitar as regras do sábado.

[[v43-5-17]]

^<<v43-5-17,17>>^ Jesus, porém, disse: "Meu Pai sempre trabalha, e eu também".

[[v43-5-18]]

^<<v43-5-18,18>>^ Assim, os líderes judeus se empenharam ainda mais em encontrar um modo de matá-lo, pois ele não apenas violava o sábado, mas afirmava que Deus era seu Pai e, portanto, se igualava a Deus.

[[v43-5-19]]

^<<v43-5-19,19>>^ Jesus respondeu: "Eu lhes digo a verdade: o Filho não pode fazer coisa alguma por sua própria conta. Ele faz apenas o que vê o Pai fazer. Aquilo que o Pai faz, o Filho também faz.

[[v43-5-20]]

^<<v43-5-20,20>>^ Pois o Pai ama o Filho e lhe mostra tudo que faz. Na verdade, o Pai lhe mostrará obras ainda maiores que estas, para que vocês fiquem admirados.

[[v43-5-21]]

^<<v43-5-21,21>>^ Pois assim como o Pai dá vida àqueles que ele ressuscita dos mortos, também o Filho dá vida a quem ele quer.

[[v43-5-22]]

^<<v43-5-22,22>>^ Além disso, o Pai não julga ninguém, mas deu ao Filho autoridade absoluta para julgar,

[[v43-5-23]]

^<<v43-5-23,23>>^ para que todos honrem o Filho como honram o Pai. Quem não honra o Filho certamente não honra o Pai, que o enviou.

[[v43-5-24]]

^<<v43-5-24,24>>^ "Eu lhes digo a verdade: quem ouve minha mensagem e crê naquele que me enviou tem a vida eterna. Jamais será condenado, mas já passou da morte para a vida.

[[v43-5-25]]

^<<v43-5-25,25>>^ "E eu lhes asseguro que está chegando a hora, e de fato já chegou, em que os mortos ouvirão minha voz, a voz do Filho de Deus. E aqueles que a ouvirem viverão.

[[v43-5-26]]

^<<v43-5-26,26>>^ O Pai tem a vida em si mesmo, e concedeu a seu Filho igual poder de dar vida,

[[v43-5-27]]

^<<v43-5-27,27>>^ e lhe deu autoridade para julgar a todos, porque ele é o Filho do Homem.

[[v43-5-28]]

^<<v43-5-28,28>>^ Não fiquem tão surpresos! Na verdade, vem o tempo em que todos os mortos ouvirão, em seus túmulos, a voz do Filho de Deus

[[v43-5-29]]

^<<v43-5-29,29>>^ e ressuscitarão. Aqueles que fizeram o bem ressuscitarão para terem vida eterna, e aqueles que continuaram a fazer o mal ressuscitarão para serem julgados.

[[v43-5-30]]

^<<v43-5-30,30>>^ Não posso fazer coisa alguma por minha própria conta. Julgo conforme aquilo que Deus me diz. Logo, meu julgamento é justo, pois não faço minha própria vontade, mas a vontade do Pai, que me enviou."

[[v43-5-31]]

^<<v43-5-31,31>>^ "Se eu testemunhasse a respeito de mim mesmo, meu testemunho não seria válido.

[[v43-5-32]]

^<<v43-5-32,32>>^ Mas há outro que também testemunha sobre mim, e eu lhes asseguro que tudo que ele diz a meu respeito é verdadeiro.

[[v43-5-33]]

^<<v43-5-33,33>>^ Vocês enviaram investigadores para ouvir João, e o testemunho dele sobre mim é verdadeiro.

[[v43-5-34]]

^<<v43-5-34,34>>^ Claro que não tenho necessidade alguma de testemunhas humanas, mas digo estas coisas para que vocês sejam salvos.

[[v43-5-35]]

^<<v43-5-35,35>>^ João era como uma lâmpada que queimava e brilhava e, por algum tempo, vocês se empolgaram com a mensagem dele.

[[v43-5-36]]

^<<v43-5-36,36>>^ Mas eu tenho um testemunho maior que o de João: as obras que realizo. O Pai me deu essas obras para concluir, e elas provam que ele me enviou.

[[v43-5-37]]

^<<v43-5-37,37>>^ E o Pai, que me enviou, testemunhou, ele próprio, a meu respeito. Vocês nunca ouviram sua voz, nem o viram pessoalmente,

[[v43-5-38]]

^<<v43-5-38,38>>^ e não têm sua mensagem no coração, pois não creem em mim, aquele que foi enviado por ele.

[[v43-5-39]]

^<<v43-5-39,39>>^ "Vocês estudam minuciosamente as Escrituras porque creem que elas lhes dão vida eterna. Mas as Escrituras apontam para mim!

[[v43-5-40]]

^<<v43-5-40,40>>^ E, no entanto, vocês se recusam a vir a mim para receber essa vida.

[[v43-5-41]]

^<<v43-5-41,41>>^ "Sua aprovação não vale nada para mim,

[[v43-5-42]]

^<<v43-5-42,42>>^ pois eu sei que o amor a Deus não está em vocês.

[[v43-5-43]]

^<<v43-5-43,43>>^ Eu vim em nome de meu Pai, e vocês me rejeitaram. Se outro vier em seu próprio nome, vocês o receberão.

[[v43-5-44]]

^<<v43-5-44,44>>^ Não é de admirar que não possam crer, pois vocês honram uns aos outros, mas não se importam com a honra que vem do único Deus!

[[v43-5-45]]

^<<v43-5-45,45>>^ "Mas não sou eu quem os acusará diante do Pai. Moisés os acusará! Sim, Moisés, em quem vocês põem sua esperança.

[[v43-5-46]]

^<<v43-5-46,46>>^ Se cressem, de fato, em Moisés, creriam em mim, pois ele escreveu a meu respeito.

[[v43-5-47]]

^<<v43-5-47,47>>^ Contudo, uma vez que não creem naquilo que ele escreveu, como crerão no que eu digo?".

'''

xref:043-joao/043-joao-004.adoc#v43-4-0[&#60; Capítulo Anterior] | <<v43-5-0,Topo>> | xref:043-joao/043-joao-006.adoc#v43-6-0[Próximo Capítulo &#62;]