include::./index.adoc[]

[[v43-3-0]]
=== João, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v43-3-1]]

^<<v43-3-1,1>>^ Havia um fariseu chamado Nicodemos, líder religioso entre os judeus.

[[v43-3-2]]

^<<v43-3-2,2>>^ Certa noite, veio falar com Jesus e disse: "Rabi, todos nós sabemos que Deus enviou o senhor para nos ensinar. Seus sinais são prova de que Deus está com o senhor".

[[v43-3-3]]

^<<v43-3-3,3>>^ Jesus respondeu: "Eu lhe digo a verdade: quem não nascer de novo, não verá o reino de Deus".

[[v43-3-4]]

^<<v43-3-4,4>>^ "Como pode um homem velho nascer de novo?", perguntou Nicodemos. "Acaso ele pode voltar ao ventre da mãe e nascer uma segunda vez?"

[[v43-3-5]]

^<<v43-3-5,5>>^ Jesus respondeu: "Eu lhe digo a verdade: ninguém pode entrar no reino de Deus sem nascer da água e do Espírito.

[[v43-3-6]]

^<<v43-3-6,6>>^ Os seres humanos podem gerar apenas vida humana, mas o Espírito dá à luz vida espiritual.

[[v43-3-7]]

^<<v43-3-7,7>>^ Portanto, não se surpreenda quando eu digo: ‘É necessário nascer de novo’.

[[v43-3-8]]

^<<v43-3-8,8>>^ O vento sopra onde quer. Assim como você ouve o vento, mas não é capaz de dizer de onde ele vem nem para onde vai, também é incapaz de explicar como as pessoas nascem do Espírito".

[[v43-3-9]]

^<<v43-3-9,9>>^ "Como pode ser isso?", perguntou Nicodemos.

[[v43-3-10]]

^<<v43-3-10,10>>^ Jesus respondeu: "Você é um mestre respeitado em Israel e não entende essas coisas?

[[v43-3-11]]

^<<v43-3-11,11>>^ Eu lhe digo a verdade: falamos daquilo que sabemos e vimos e, no entanto, vocês não creem em nosso testemunho.

[[v43-3-12]]

^<<v43-3-12,12>>^ Se vocês não creem em mim quando falo de coisas terrenas, como crerão se eu falar de coisas celestiais?

[[v43-3-13]]

^<<v43-3-13,13>>^ Ninguém jamais subiu ao céu, exceto aquele que de lá desceu, o Filho do Homem.

[[v43-3-14]]

^<<v43-3-14,14>>^ E, como Moisés, no deserto, levantou a serpente de bronze numa estaca, também é necessário que o Filho do Homem seja levantado,

[[v43-3-15]]

^<<v43-3-15,15>>^ para que todo o que nele crer tenha a vida eterna.

[[v43-3-16]]

^<<v43-3-16,16>>^ "Porque Deus amou tanto o mundo que deu seu Filho único, para que todo o que nele crer não pereça, mas tenha a vida eterna.

[[v43-3-17]]

^<<v43-3-17,17>>^ Deus enviou seu Filho ao mundo não para condenar o mundo, mas para salvá-lo por meio dele.

[[v43-3-18]]

^<<v43-3-18,18>>^ "Não há condenação alguma para quem crê nele. Mas quem não crê nele já está condenado por não crer no Filho único de Deus.

[[v43-3-19]]

^<<v43-3-19,19>>^ E a condenação se baseia nisto: a luz de Deus veio ao mundo, mas as pessoas amaram mais a escuridão que a luz, porque seus atos eram maus.

[[v43-3-20]]

^<<v43-3-20,20>>^ Quem pratica o mal odeia a luz e não se aproxima dela, pois teme que seus pecados sejam expostos.

[[v43-3-21]]

^<<v43-3-21,21>>^ Mas quem pratica a verdade se aproxima da luz, para que outros vejam que ele faz a vontade de Deus".

[[v43-3-22]]

^<<v43-3-22,22>>^ Então Jesus e seus discípulos saíram de Jerusalém e foram à região da Judeia. Jesus passou um tempo ali com eles, batizando.

[[v43-3-23]]

^<<v43-3-23,23>>^ Nessa época, João também batizava em Enom, perto de Salim, pois havia ali bastante água, e o povo ia até ele para ser batizado.

[[v43-3-24]]

^<<v43-3-24,24>>^ Isso aconteceu antes de João ser preso.

[[v43-3-25]]

^<<v43-3-25,25>>^ Surgiu uma discussão entre os discípulos de João e certo judeu a respeito da purificação cerimonial.

[[v43-3-26]]

^<<v43-3-26,26>>^ Os discípulos de João foram falar com ele e lhe disseram: "Rabi, o homem que o senhor encontrou no outro lado do rio Jordão, aquele de quem o senhor deu testemunho, também está batizando. Todos vão até ele".

[[v43-3-27]]

^<<v43-3-27,27>>^ João respondeu: "Ninguém pode receber coisa alguma, a menos que lhe seja concedida do céu.

[[v43-3-28]]

^<<v43-3-28,28>>^ Vocês sabem que eu lhes disse claramente: ‘Eu não sou o Cristo. Estou aqui apenas para preparar o caminho para ele’.

[[v43-3-29]]

^<<v43-3-29,29>>^ É o noivo que se casa com a noiva; o amigo do noivo simplesmente se alegra de estar ao lado dele e ouvir seus votos. Portanto, muito me alegro com o destaque dele.

[[v43-3-30]]

^<<v43-3-30,30>>^ Ele deve se tornar cada vez maior, e eu, cada vez menor".

[[v43-3-31]]

^<<v43-3-31,31>>^ Aquele que veio do alto é superior a todos. Nós somos da terra e falamos de coisas terrenas, mas ele veio do céu e é superior a todos.

[[v43-3-32]]

^<<v43-3-32,32>>^ Ele dá testemunho daquilo que viu e ouviu, mas como são poucos os que creem no que ele diz!

[[v43-3-33]]

^<<v43-3-33,33>>^ Todo aquele que aceita seu testemunho confirma que Deus é verdadeiro.

[[v43-3-34]]

^<<v43-3-34,34>>^ Pois ele foi enviado por Deus e fala as palavras de Deus, porque Deus lhe dá, sem limites, o Espírito.

[[v43-3-35]]

^<<v43-3-35,35>>^ O Pai ama o Filho e pôs tudo em suas mãos.

[[v43-3-36]]

^<<v43-3-36,36>>^ E quem crê no Filho de Deus tem a vida eterna. Quem não obedece ao Filho não tem a vida eterna, mas a ira de Deus permanece sobre ele.

'''

xref:043-joao/043-joao-002.adoc#v43-2-0[&#60; Capítulo Anterior] | <<v43-3-0,Topo>> | xref:043-joao/043-joao-004.adoc#v43-4-0[Próximo Capítulo &#62;]