include::./index.adoc[]

[[v43-6-0]]
=== João, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v43-6-1]]

^<<v43-6-1,1>>^ Depois disso, Jesus atravessou o mar da Galileia, conhecido também como mar de Tiberíades.

[[v43-6-2]]

^<<v43-6-2,2>>^ Uma grande multidão o seguia por toda parte, pois tinham visto os sinais que ele havia realizado ao curar os enfermos.

[[v43-6-3]]

^<<v43-6-3,3>>^ Então Jesus subiu a um monte e sentou-se com seus discípulos.

[[v43-6-4]]

^<<v43-6-4,4>>^ Era quase tempo da festa judaica da Páscoa.

[[v43-6-5]]

^<<v43-6-5,5>>^ Jesus logo viu uma grande multidão que vinha a seu encontro. Voltando-se para Filipe, perguntou: "Onde podemos comprar pão para alimentar toda essa gente?".

[[v43-6-6]]

^<<v43-6-6,6>>^ Disse isso para pôr Filipe à prova, pois já sabia o que ia fazer.

[[v43-6-7]]

^<<v43-6-7,7>>^ Filipe respondeu: "Mesmo que trabalhássemos vários meses, não teríamos dinheiro suficiente para dar alimento a todos!".

[[v43-6-8]]

^<<v43-6-8,8>>^ Então um de seus discípulos, André, irmão de Simão Pedro, falou:

[[v43-6-9]]

^<<v43-6-9,9>>^ "Aqui está um rapaz com cinco pães de cevada e dois peixes. Mas que adianta isso para tanta gente?".

[[v43-6-10]]

^<<v43-6-10,10>>^ Jesus respondeu: "Digam ao povo que se sente". Todos se sentaram na grama que cobria o monte. Só os homens eram cerca de cinco mil.

[[v43-6-11]]

^<<v43-6-11,11>>^ Então Jesus tomou os pães, agradeceu a Deus e os repartiu entre o povo. Em seguida, fez o mesmo com os peixes. E todos comeram à vontade.

[[v43-6-12]]

^<<v43-6-12,12>>^ Depois que todos estavam satisfeitos, Jesus disse a seus discípulos: "Agora juntem os pedaços que sobraram, para que nada se desperdice".

[[v43-6-13]]

^<<v43-6-13,13>>^ Eles juntaram o que restou e encheram doze cestos com as sobras.

[[v43-6-14]]

^<<v43-6-14,14>>^ Quando o povo viu Jesus fazer esse sinal, exclamou: "Sem dúvida ele é o profeta que haveria de vir ao mundo!".

[[v43-6-15]]

^<<v43-6-15,15>>^ Jesus sabia que pretendiam obrigá-lo a ser rei deles, de modo que se retirou, sozinho, para o monte.

[[v43-6-16]]

^<<v43-6-16,16>>^ Ao entardecer, os discípulos de Jesus desceram à praia,

[[v43-6-17]]

^<<v43-6-17,17>>^ entraram no barco e atravessaram o mar em direção a Cafarnaum. Quando escureceu, porém, Jesus ainda não tinha vindo se encontrar com eles.

[[v43-6-18]]

^<<v43-6-18,18>>^ Logo, um vento forte veio sobre eles, e o mar ficou muito agitado.

[[v43-6-19]]

^<<v43-6-19,19>>^ Depois de remarem cinco ou seis quilômetros, de repente viram Jesus caminhando sobre o mar, em direção ao barco. Ficaram aterrorizados,

[[v43-6-20]]

^<<v43-6-20,20>>^ mas ele lhes disse: "Sou eu! Não tenham medo".

[[v43-6-21]]

^<<v43-6-21,21>>^ Eles o receberam no barco e, logo em seguida, chegaram a seu destino.

[[v43-6-22]]

^<<v43-6-22,22>>^ No dia seguinte, a multidão que tinha ficado do outro lado do mar viu que os discípulos haviam pegado o único barco dali e que Jesus não fora com eles.

[[v43-6-23]]

^<<v43-6-23,23>>^ Alguns barcos de Tiberíades se aproximaram do lugar onde o povo tinha comido os pães depois que o Senhor os abençoou.

[[v43-6-24]]

^<<v43-6-24,24>>^ Quando a multidão viu que nem Jesus nem os discípulos estavam ali, todos entraram nos barcos e atravessaram para Cafarnaum, a fim de procurá-lo.

[[v43-6-25]]

^<<v43-6-25,25>>^ Encontraram-no do outro lado do mar e lhe perguntaram: "Rabi, quando o senhor chegou aqui?".

[[v43-6-26]]

^<<v43-6-26,26>>^ Jesus respondeu: "Eu lhes digo a verdade: vocês querem estar comigo não porque entenderam os sinais, mas porque lhes dei alimento.

[[v43-6-27]]

^<<v43-6-27,27>>^ Não se preocupem tanto com coisas que se estragam, como a comida, mas usem suas energias buscando o alimento que permanece para a vida eterna, o qual o Filho do Homem pode lhes dar. Pois Deus, o Pai, colocou em mim seu selo de aprovação".

[[v43-6-28]]

^<<v43-6-28,28>>^ "Nós também queremos realizar as obras de Deus", disseram eles. "O que devemos fazer?"

[[v43-6-29]]

^<<v43-6-29,29>>^ Jesus lhes disse: "Esta é a única obra que Deus quer de vocês: creiam naquele que ele enviou".

[[v43-6-30]]

^<<v43-6-30,30>>^ Eles responderam: "Se deseja que creiamos no senhor, mostre-nos um sinal. O que o senhor pode fazer?

[[v43-6-31]]

^<<v43-6-31,31>>^ Afinal, nossos antepassados comeram maná no deserto! As Escrituras dizem: ‘Moisés lhes deu de comer pão do céu’".

[[v43-6-32]]

^<<v43-6-32,32>>^ Jesus disse: "Eu lhes digo a verdade: não foi Moisés quem lhes deu pão do céu. É meu Pai quem dá o verdadeiro pão do céu a vocês.

[[v43-6-33]]

^<<v43-6-33,33>>^ O verdadeiro pão de Deus é aquele que desce do céu e dá vida ao mundo".

[[v43-6-34]]

^<<v43-6-34,34>>^ "Senhor, dê-nos desse pão todos os dias", disseram eles.

[[v43-6-35]]

^<<v43-6-35,35>>^ Jesus respondeu: "Eu sou o pão da vida. Quem vem a mim nunca mais terá fome. Quem crê em mim nunca mais terá sede.

[[v43-6-36]]

^<<v43-6-36,36>>^ Mas vocês não creram em mim, embora me tenham visto.

[[v43-6-37]]

^<<v43-6-37,37>>^ Contudo, aqueles que o Pai me dá virão a mim, e eu jamais os rejeitarei.

[[v43-6-38]]

^<<v43-6-38,38>>^ Pois desci do céu para fazer a vontade daquele que me enviou, e não minha própria vontade.

[[v43-6-39]]

^<<v43-6-39,39>>^ E esta é a vontade de Deus: que eu não perca um sequer de todos que ele me deu, mas que ressuscite todos no último dia.

[[v43-6-40]]

^<<v43-6-40,40>>^ Pois é a vontade de meu Pai que todo aquele que olhar para o Filho e nele crer tenha a vida eterna, e eu o ressuscitarei no último dia".

[[v43-6-41]]

^<<v43-6-41,41>>^ Então os judeus começaram a criticá-lo, pois ele havia afirmado: "Eu sou o pão que desceu do céu".

[[v43-6-42]]

^<<v43-6-42,42>>^ Diziam: "Este não é Jesus, filho de José? Conhecemos seu pai e sua mãe. Como ele pode dizer: ‘Desci do céu?’".

[[v43-6-43]]

^<<v43-6-43,43>>^ Jesus, porém, respondeu: "Parem de me criticar.

[[v43-6-44]]

^<<v43-6-44,44>>^ Pois ninguém pode vir a mim se o Pai, que me enviou, não o trouxer a mim; e no último dia eu o ressuscitarei.

[[v43-6-45]]

^<<v43-6-45,45>>^ Como dizem as Escrituras: ‘Todos eles serão ensinados por Deus’. Todo aquele que ouve o Pai e aprende dele vem a mim.

[[v43-6-46]]

^<<v43-6-46,46>>^ Não que alguém tenha visto o Pai; somente eu, que fui enviado por Deus, o vi.

[[v43-6-47]]

^<<v43-6-47,47>>^ "Eu lhes digo a verdade: quem crê tem a vida eterna.

[[v43-6-48]]

^<<v43-6-48,48>>^ Sim, eu sou o pão da vida!

[[v43-6-49]]

^<<v43-6-49,49>>^ Seus antepassados comeram maná no deserto, mas morreram;

[[v43-6-50]]

^<<v43-6-50,50>>^ quem comer o pão do céu, no entanto, jamais morrerá.

[[v43-6-51]]

^<<v43-6-51,51>>^ Eu sou o pão vivo que desceu do céu. Quem comer deste pão viverá para sempre; e este pão, que eu oferecerei para que o mundo viva, é a minha carne".

[[v43-6-52]]

^<<v43-6-52,52>>^ Então os judeus começaram a discutir entre si a respeito do que ele queria dizer. "Como pode esse homem nos dar sua carne para comer?", perguntavam.

[[v43-6-53]]

^<<v43-6-53,53>>^ Então Jesus disse novamente: "Eu lhes digo a verdade: se vocês não comerem a carne do Filho do Homem e não beberem o seu sangue, não terão a vida em si mesmos.

[[v43-6-54]]

^<<v43-6-54,54>>^ Mas quem come minha carne e bebe meu sangue terá a vida eterna, e eu o ressuscitarei no último dia.

[[v43-6-55]]

^<<v43-6-55,55>>^ Pois minha carne é a verdadeira comida, e meu sangue é a verdadeira bebida.

[[v43-6-56]]

^<<v43-6-56,56>>^ Quem come minha carne e bebe meu sangue permanece em mim, e eu nele.

[[v43-6-57]]

^<<v43-6-57,57>>^ Eu vivo por causa do Pai, que vive e me enviou; da mesma forma, quem se alimenta de mim viverá por minha causa.

[[v43-6-58]]

^<<v43-6-58,58>>^ Eu sou o verdadeiro pão que desceu do céu. Seus antepassados comeram maná e morreram; quem comer este pão não morrerá, mas viverá para sempre".

[[v43-6-59]]

^<<v43-6-59,59>>^ Ele disse essas coisas quando ensinava na sinagoga de Cafarnaum.

[[v43-6-60]]

^<<v43-6-60,60>>^ Muitos de seus discípulos disseram: "Sua mensagem é dura. Quem é capaz de aceitá-la?".

[[v43-6-61]]

^<<v43-6-61,61>>^ Jesus, sabendo que seus discípulos reclamavam, disse: "Isso os ofende?

[[v43-6-62]]

^<<v43-6-62,62>>^ Então o que pensarão se virem o Filho do Homem subir ao céu, onde estava antes?

[[v43-6-63]]

^<<v43-6-63,63>>^ Somente o Espírito dá vida. A natureza humana não realiza coisa alguma. E as palavras que eu lhes disse são espírito e vida.

[[v43-6-64]]

^<<v43-6-64,64>>^ Mas alguns de vocês não creem em mim". Pois Jesus sabia, desde o princípio, quem não acreditava nele e quem iria traí-lo.

[[v43-6-65]]

^<<v43-6-65,65>>^ E acrescentou: "Por isso eu disse que ninguém pode vir a mim a menos que o Pai o dê a mim".

[[v43-6-66]]

^<<v43-6-66,66>>^ Nesse momento, muitos de seus discípulos se afastaram dele e o abandonaram.

[[v43-6-67]]

^<<v43-6-67,67>>^ Então Jesus se voltou para os Doze e perguntou: "Vocês também vão embora?".

[[v43-6-68]]

^<<v43-6-68,68>>^ Simão Pedro respondeu: "Senhor, para quem iremos? O senhor tem as palavras da vida eterna.

[[v43-6-69]]

^<<v43-6-69,69>>^ Nós cremos e sabemos que o senhor é o Santo de Deus".

[[v43-6-70]]

^<<v43-6-70,70>>^ Então Jesus disse: "Eu escolhi vocês doze, mas um de vocês é um diabo".

[[v43-6-71]]

^<<v43-6-71,71>>^ Ele se referia a Judas, filho de Simão Iscariotes, um dos Doze, que mais tarde o trairia.

'''

xref:043-joao/043-joao-005.adoc#v43-5-0[&#60; Capítulo Anterior] | <<v43-6-0,Topo>> | xref:043-joao/043-joao-007.adoc#v43-7-0[Próximo Capítulo &#62;]