include::./index.adoc[]

[[v43-15-0]]
=== João, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v43-15-1]]

^<<v43-15-1,1>>^ "Eu sou a videira verdadeira, e meu Pai é o lavrador.

[[v43-15-2]]

^<<v43-15-2,2>>^ Todo ramo que, estando em mim, não dá fruto, ele corta. Todo ramo que dá fruto, ele poda, para que produza ainda mais.

[[v43-15-3]]

^<<v43-15-3,3>>^ Vocês já foram limpos pela mensagem que eu lhes dei.

[[v43-15-4]]

^<<v43-15-4,4>>^ Permaneçam em mim, e eu permanecerei em vocês. Pois, assim como um ramo não pode produzir fruto se não estiver na videira, vocês também não poderão produzir frutos a menos que permaneçam em mim.

[[v43-15-5]]

^<<v43-15-5,5>>^ "Sim, eu sou a videira; vocês são os ramos. Quem permanece em mim, e eu nele, produz muito fruto. Pois, sem mim, vocês não podem fazer coisa alguma.

[[v43-15-6]]

^<<v43-15-6,6>>^ Quem não permanece em mim é jogado fora, como um ramo imprestável, e seca. Esses ramos são ajuntados num monte para serem queimados.

[[v43-15-7]]

^<<v43-15-7,7>>^ Mas, se vocês permanecerem em mim e minhas palavras permanecerem em vocês, pedirão o que quiserem, e isso lhes será concedido!

[[v43-15-8]]

^<<v43-15-8,8>>^ Quando vocês produzem muitos frutos, trazem grande glória a meu Pai e demonstram que são meus discípulos de verdade.

[[v43-15-9]]

^<<v43-15-9,9>>^ "Eu os amei como o Pai me amou. Permaneçam no meu amor.

[[v43-15-10]]

^<<v43-15-10,10>>^ Quando vocês obedecem a meus mandamentos, permanecem no meu amor, assim como eu obedeço aos mandamentos de meu Pai e permaneço no amor dele.

[[v43-15-11]]

^<<v43-15-11,11>>^ Eu lhes disse estas coisas para que fiquem repletos da minha alegria. Sim, sua alegria transbordará!

[[v43-15-12]]

^<<v43-15-12,12>>^ Este é meu mandamento: Amem uns aos outros como eu amo vocês.

[[v43-15-13]]

^<<v43-15-13,13>>^ Não existe amor maior do que dar a vida por seus amigos.

[[v43-15-14]]

^<<v43-15-14,14>>^ Vocês serão meus amigos se fizerem o que eu ordeno.

[[v43-15-15]]

^<<v43-15-15,15>>^ Já não os chamo de escravos, pois o senhor não faz confidências a seus escravos. Agora vocês são meus amigos, pois eu lhes disse tudo que o Pai me disse.

[[v43-15-16]]

^<<v43-15-16,16>>^ Vocês não me escolheram; eu os escolhi. Eu os chamei para irem e produzirem frutos duradouros, para que o Pai lhes dê tudo que pedirem em meu nome.

[[v43-15-17]]

^<<v43-15-17,17>>^ Este é meu mandamento: Amem uns aos outros."

[[v43-15-18]]

^<<v43-15-18,18>>^ "Se o mundo os odeia, lembrem-se de que primeiro odiou a mim.

[[v43-15-19]]

^<<v43-15-19,19>>^ O mundo os amaria se pertencessem a ele, mas vocês já não fazem parte do mundo. Eu os escolhi para que não mais pertençam ao mundo, e por isso o mundo os odeia.

[[v43-15-20]]

^<<v43-15-20,20>>^ Vocês se lembram do que eu lhes disse: ‘O escravo não é maior que o seu senhor’? Uma vez que eles me perseguiram, também os perseguirão. E, se obedeceram à minha palavra, também obedecerão à sua.

[[v43-15-21]]

^<<v43-15-21,21>>^ Farão tudo isso a vocês por minha causa, pois rejeitaram aquele que me enviou.

[[v43-15-22]]

^<<v43-15-22,22>>^ Eles não seriam culpados se eu não tivesse vindo nem lhes falado. Agora, porém, não têm desculpa por seu pecado.

[[v43-15-23]]

^<<v43-15-23,23>>^ Quem me odeia também odeia meu Pai.

[[v43-15-24]]

^<<v43-15-24,24>>^ Se eu não tivesse realizado no meio deles sinais que ninguém mais pode realizar, eles não seriam culpados. Agora, porém, viram tudo que fiz e, no entanto, ainda odeiam a mim e a meu Pai.

[[v43-15-25]]

^<<v43-15-25,25>>^ Isso cumpre o que está registrado nas Escrituras deles: ‘Odiaram-me sem motivo’.

[[v43-15-26]]

^<<v43-15-26,26>>^ "Mas eu enviarei a vocês o Encorajador, o Espírito da verdade. Ele virá do Pai e testemunhará a meu respeito.

[[v43-15-27]]

^<<v43-15-27,27>>^ E vocês também devem testemunhar a meu respeito, porque estão comigo desde o início."

'''

xref:043-joao/043-joao-014.adoc#v43-14-0[&#60; Capítulo Anterior] | <<v43-15-0,Topo>> | xref:043-joao/043-joao-016.adoc#v43-16-0[Próximo Capítulo &#62;]