include::./index.adoc[]

[[v43-14-0]]
=== João, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v43-14-1]]

^<<v43-14-1,1>>^ "Não deixem que seu coração fique aflito. Creiam em Deus; creiam também em mim.

[[v43-14-2]]

^<<v43-14-2,2>>^ Na casa de meu Pai há muitas moradas. Se não fosse assim, eu lhes teria dito. Vou preparar lugar para vocês

[[v43-14-3]]

^<<v43-14-3,3>>^ e, quando tudo estiver pronto, virei buscá-los, para que estejam sempre comigo, onde eu estiver.

[[v43-14-4]]

^<<v43-14-4,4>>^ Vocês conhecem o caminho para onde vou."

[[v43-14-5]]

^<<v43-14-5,5>>^ "Não sabemos para onde o Senhor vai", disse Tomé. "Como podemos conhecer o caminho?"

[[v43-14-6]]

^<<v43-14-6,6>>^ Jesus disse: "Eu sou o caminho, a verdade e a vida. Ninguém pode vir ao Pai senão por mim.

[[v43-14-7]]

^<<v43-14-7,7>>^ Se vocês realmente me conhecessem, saberiam quem é meu Pai. Mas, de agora em diante, vão conhecer e ver o Pai".

[[v43-14-8]]

^<<v43-14-8,8>>^ Filipe disse: "Senhor, mostre-nos o Pai, e ficaremos satisfeitos".

[[v43-14-9]]

^<<v43-14-9,9>>^ Jesus respondeu: "Filipe, estive com vocês todo esse tempo e você ainda não sabe quem eu sou? Quem me vê, vê o Pai! Então por que me pede para mostrar o Pai?

[[v43-14-10]]

^<<v43-14-10,10>>^ Você não crê que eu estou no Pai e o Pai está em mim? As palavras que eu digo não são minhas, mas de meu Pai, que permanece em mim e realiza suas obras por meu intermédio.

[[v43-14-11]]

^<<v43-14-11,11>>^ Apenas creiam que eu estou no Pai e que o Pai está em mim. Ou creiam pelo menos por causa das obras que vocês me viram realizar.

[[v43-14-12]]

^<<v43-14-12,12>>^ "Eu lhes digo a verdade: quem crê em mim fará as mesmas obras que tenho realizado, e até maiores, pois eu vou para o Pai.

[[v43-14-13]]

^<<v43-14-13,13>>^ Vocês podem pedir qualquer coisa em meu nome, e eu o farei, para que o Filho glorifique o Pai.

[[v43-14-14]]

^<<v43-14-14,14>>^ Sim, peçam qualquer coisa em meu nome, e eu o farei!"

[[v43-14-15]]

^<<v43-14-15,15>>^ "Se vocês me amam, obedeçam a meus mandamentos.

[[v43-14-16]]

^<<v43-14-16,16>>^ E eu pedirei ao Pai, e ele lhes dará outro Encorajador, que nunca os deixará.

[[v43-14-17]]

^<<v43-14-17,17>>^ É o Espírito da verdade. O mundo não o pode receber, pois não o vê e não o conhece. Mas vocês o conhecem, pois ele habita com vocês agora e depois estará em vocês.

[[v43-14-18]]

^<<v43-14-18,18>>^ Não os deixarei órfãos; voltarei para vocês.

[[v43-14-19]]

^<<v43-14-19,19>>^ Em breve o mundo não me verá mais, mas vocês me verão. Porque eu vivo, vocês também viverão.

[[v43-14-20]]

^<<v43-14-20,20>>^ No dia em que eu for ressuscitado, vocês saberão que eu estou em meu Pai, vocês em mim, e eu em vocês.

[[v43-14-21]]

^<<v43-14-21,21>>^ Aqueles que aceitam meus mandamentos e lhes obedecem são os que me amam. E, porque me amam, serão amados por meu Pai. E eu também os amarei e me revelarei a cada um deles."

[[v43-14-22]]

^<<v43-14-22,22>>^ Judas (não o Iscariotes) disse: "Por que o Senhor vai se revelar somente a nós, e não ao mundo em geral?".

[[v43-14-23]]

^<<v43-14-23,23>>^ Jesus respondeu: "Quem me ama faz o que eu ordeno. Meu Pai o amará, e nós viremos para morar nele.

[[v43-14-24]]

^<<v43-14-24,24>>^ Quem não me ama não me obedece. E lembrem-se, estas palavras não são minhas; elas vêm do Pai, que me enviou.

[[v43-14-25]]

^<<v43-14-25,25>>^ Eu digo estas coisas enquanto ainda estou com vocês.

[[v43-14-26]]

^<<v43-14-26,26>>^ Mas quando o Pai enviar o Encorajador, o Espírito Santo, como meu representante, ele lhes ensinará todas as coisas e os fará lembrar tudo que eu lhes disse.

[[v43-14-27]]

^<<v43-14-27,27>>^ "Eu lhes deixo um presente, a minha plena paz. E essa paz que eu lhes dou é um presente que o mundo não pode dar. Portanto, não se aflijam nem tenham medo.

[[v43-14-28]]

^<<v43-14-28,28>>^ Lembrem-se do que eu lhes disse: ‘Vou embora, mas voltarei para vocês’. Se o seu amor por mim é real, vocês deveriam estar felizes porque eu vou para o Pai, que é maior que eu.

[[v43-14-29]]

^<<v43-14-29,29>>^ Eu lhes disse estas coisas antes que aconteçam para que, quando acontecerem, vocês creiam.

[[v43-14-30]]

^<<v43-14-30,30>>^ "Não tenho muito tempo mais para falar com vocês, pois o governante deste mundo se aproxima. Ele não tem poder algum sobre mim,

[[v43-14-31]]

^<<v43-14-31,31>>^ mas farei o que o Pai requer de mim, para que o mundo saiba que eu amo o Pai. Levantem-se e vamos embora!"

'''

xref:043-joao/043-joao-013.adoc#v43-13-0[&#60; Capítulo Anterior] | <<v43-14-0,Topo>> | xref:043-joao/043-joao-015.adoc#v43-15-0[Próximo Capítulo &#62;]