include::./index.adoc[]

[[v43-17-0]]
=== João, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v43-17-1]]

^<<v43-17-1,1>>^ Depois de dizer todas essas coisas, Jesus olhou para o céu e orou: "Pai, chegou a hora. Glorifica teu Filho, para que ele te glorifique,

[[v43-17-2]]

^<<v43-17-2,2>>^ pois tu lhe deste autoridade sobre toda a humanidade. Ele concede vida eterna a cada um daqueles que lhe deste.

[[v43-17-3]]

^<<v43-17-3,3>>^ E a vida eterna é isto: conhecer a ti, o único Deus verdadeiro, e a Jesus Cristo, a quem enviaste ao mundo.

[[v43-17-4]]

^<<v43-17-4,4>>^ Eu te glorifiquei aqui na terra, completando a obra que me deste para realizar.

[[v43-17-5]]

^<<v43-17-5,5>>^ Agora, Pai, glorifica-me e leva-me para junto de ti, para a glória que tive a teu lado antes do princípio do mundo.

[[v43-17-6]]

^<<v43-17-6,6>>^ "Eu revelei teu nome àqueles que me deste do mundo. Eles sempre foram teus. Tu os deste a mim, e eles obedeceram à tua palavra.

[[v43-17-7]]

^<<v43-17-7,7>>^ Agora eles sabem que tudo que eu tenho vem de ti,

[[v43-17-8]]

^<<v43-17-8,8>>^ pois lhes transmiti a mensagem que me deste. Eles a aceitaram e sabem que eu vim de ti, e creem que tu me enviaste.

[[v43-17-9]]

^<<v43-17-9,9>>^ "Minha oração não é por este mundo, mas por aqueles que me deste, pois eles pertencem a ti.

[[v43-17-10]]

^<<v43-17-10,10>>^ Tudo que é meu pertence a ti, e tudo que é teu pertence a mim, e eu sou glorificado por meio deles.

[[v43-17-11]]

^<<v43-17-11,11>>^ Agora deixo este mundo; eles ficam aqui, mas eu vou para tua presença. Pai santo, tu me deste teu nome; agora protege-os com o poder do teu nome para que eles estejam unidos, assim como nós estamos.

[[v43-17-12]]

^<<v43-17-12,12>>^ Durante meu tempo aqui com eles, eu os protegi com o poder do nome que me deste. Eu os guardei de modo que nenhum deles se perdeu, exceto aquele que estava a caminho da destruição, como as Escrituras haviam predito.

[[v43-17-13]]

^<<v43-17-13,13>>^ "Agora vou para tua presença. Enquanto ainda estou no mundo, digo estas coisas para que eles tenham minha plena alegria em si mesmos.

[[v43-17-14]]

^<<v43-17-14,14>>^ Eu lhes dei tua palavra. E o mundo os odeia, porque eles não são do mundo, como eu também não sou.

[[v43-17-15]]

^<<v43-17-15,15>>^ Não peço que os tires do mundo, mas que os protejas do maligno.

[[v43-17-16]]

^<<v43-17-16,16>>^ Eles não são deste mundo, como eu também não sou.

[[v43-17-17]]

^<<v43-17-17,17>>^ Consagra-os na verdade, que é a tua palavra.

[[v43-17-18]]

^<<v43-17-18,18>>^ Assim como tu me enviaste ao mundo, eu os envio ao mundo.

[[v43-17-19]]

^<<v43-17-19,19>>^ E eu me entrego como sacrifício santo por eles, para que sejam consagrados na verdade.

[[v43-17-20]]

^<<v43-17-20,20>>^ "Não te peço apenas por estes discípulos, mas também por todos que crerão em mim por meio da mensagem deles.

[[v43-17-21]]

^<<v43-17-21,21>>^ Minha oração é que todos eles sejam um, como nós somos um, como tu estás em mim, Pai, e eu estou em ti. Que eles estejam em nós, para que o mundo creia que tu me enviaste.

[[v43-17-22]]

^<<v43-17-22,22>>^ "Eu dei a eles a glória que tu me deste, para que sejam um, como nós somos um.

[[v43-17-23]]

^<<v43-17-23,23>>^ Eu estou neles e tu estás em mim. Que eles experimentem unidade perfeita, para que todo o mundo saiba que tu me enviaste e que os amas tanto quanto me amas.

[[v43-17-24]]

^<<v43-17-24,24>>^ Pai, quero que os que me deste estejam comigo onde estou. Então eles verão toda a glória que me deste, porque me amaste antes mesmo do princípio do mundo.

[[v43-17-25]]

^<<v43-17-25,25>>^ "Pai justo, o mundo não te conhece, mas eu te conheço; e estes discípulos sabem que tu me enviaste.

[[v43-17-26]]

^<<v43-17-26,26>>^ Eu revelei teu nome a eles, e continuarei a fazê-lo. Então teu amor por mim estará neles, e eu estarei neles".

'''

xref:043-joao/043-joao-016.adoc#v43-16-0[&#60; Capítulo Anterior] | <<v43-17-0,Topo>> | xref:043-joao/043-joao-018.adoc#v43-18-0[Próximo Capítulo &#62;]