include::./index.adoc[]

[[v43-11-0]]
=== João, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v43-11-1]]

^<<v43-11-1,1>>^ Um homem chamado Lázaro estava doente. Ele morava em Betânia com suas irmãs, Maria e Marta.

[[v43-11-2]]

^<<v43-11-2,2>>^ Foi Maria, a irmã de Lázaro, que mais tarde derramou perfume caro nos pés do Senhor e os enxugou com os cabelos.

[[v43-11-3]]

^<<v43-11-3,3>>^ As duas irmãs enviaram um recado a Jesus, dizendo: "Senhor, seu amigo querido está muito doente".

[[v43-11-4]]

^<<v43-11-4,4>>^ Quando Jesus ouviu isso, disse: "A doença de Lázaro não acabará em morte. Ela aconteceu para a glória de Deus, para que o Filho de Deus receba glória por meio dela".

[[v43-11-5]]

^<<v43-11-5,5>>^ Jesus amava Marta, Maria e Lázaro.

[[v43-11-6]]

^<<v43-11-6,6>>^ Ouvindo, portanto, que Lázaro estava doente, ficou mais dois dias onde estava.

[[v43-11-7]]

^<<v43-11-7,7>>^ Depois, disse a seus discípulos: "Vamos voltar para a Judeia".

[[v43-11-8]]

^<<v43-11-8,8>>^ Os discípulos se opuseram, dizendo: "Rabi, apenas alguns dias atrás o povo da Judeia tentou apedrejá-lo. Ainda assim, o senhor vai voltar para lá?".

[[v43-11-9]]

^<<v43-11-9,9>>^ Jesus respondeu: "Há doze horas de claridade todos os dias. Durante o dia, as pessoas podem andar com segurança. Conseguem enxergar, pois têm a luz deste mundo.

[[v43-11-10]]

^<<v43-11-10,10>>^ À noite, porém, correm o risco de tropeçar, pois não há luz".

[[v43-11-11]]

^<<v43-11-11,11>>^ E acrescentou: "Nosso amigo Lázaro adormeceu, mas agora vou despertá-lo".

[[v43-11-12]]

^<<v43-11-12,12>>^ Os discípulos disseram: "Senhor, se ele dorme é porque logo vai melhorar!".

[[v43-11-13]]

^<<v43-11-13,13>>^ Pensavam que Jesus falava apenas do repouso do sono, mas ele se referia à morte de Lázaro.

[[v43-11-14]]

^<<v43-11-14,14>>^ Então ele disse claramente: "Lázaro está morto.

[[v43-11-15]]

^<<v43-11-15,15>>^ E, por causa de vocês, eu me alegro por não ter estado lá, pois agora vocês vão crer de fato. Venham, vamos até ele".

[[v43-11-16]]

^<<v43-11-16,16>>^ Tomé, apelidado de Gêmeo, disse aos outros discípulos: "Vamos até lá também para morrer com Jesus".

[[v43-11-17]]

^<<v43-11-17,17>>^ Quando Jesus chegou a Betânia, disseram-lhe que Lázaro estava no túmulo havia quatro dias.

[[v43-11-18]]

^<<v43-11-18,18>>^ Betânia ficava a cerca de três quilômetros de Jerusalém,

[[v43-11-19]]

^<<v43-11-19,19>>^ e muitos moradores da região tinham vindo consolar Marta e Maria pela perda do irmão.

[[v43-11-20]]

^<<v43-11-20,20>>^ Quando Marta soube que Jesus estava chegando, foi ao seu encontro. Maria, porém, ficou em casa.

[[v43-11-21]]

^<<v43-11-21,21>>^ Marta disse a Jesus: "Se o Senhor estivesse aqui, meu irmão não teria morrido.

[[v43-11-22]]

^<<v43-11-22,22>>^ Mas sei que, mesmo agora, Deus lhe dará tudo que pedir".

[[v43-11-23]]

^<<v43-11-23,23>>^ Jesus lhe disse: "Seu irmão vai ressuscitar".

[[v43-11-24]]

^<<v43-11-24,24>>^ "Sim", respondeu Marta. "Ele vai ressuscitar quando todos ressuscitarem, no último dia."

[[v43-11-25]]

^<<v43-11-25,25>>^ Então Jesus disse: "Eu sou a ressurreição e a vida. Quem crê em mim viverá, mesmo depois de morrer.

[[v43-11-26]]

^<<v43-11-26,26>>^ Quem vive e crê em mim jamais morrerá. Você crê nisso, Marta?".

[[v43-11-27]]

^<<v43-11-27,27>>^ "Sim, Senhor", respondeu ela. "Eu creio que o senhor é o Cristo, o Filho de Deus, aquele que veio ao mundo da parte de Deus."

[[v43-11-28]]

^<<v43-11-28,28>>^ Em seguida, voltou para casa. Chamou Maria à parte e disse: "O Mestre está aqui e quer ver você".

[[v43-11-29]]

^<<v43-11-29,29>>^ Maria se levantou de imediato e foi até ele.

[[v43-11-30]]

^<<v43-11-30,30>>^ Jesus tinha ficado fora do povoado, no lugar onde Marta havia se encontrado com ele.

[[v43-11-31]]

^<<v43-11-31,31>>^ Quando as pessoas que estavam na casa viram Maria sair apressadamente, imaginaram que ela ia ao túmulo de Lázaro chorar e a seguiram.

[[v43-11-32]]

^<<v43-11-32,32>>^ Assim que chegou ao lugar onde Jesus estava e o viu, caiu a seus pés e disse: "Se o Senhor estivesse aqui, meu irmão não teria morrido".

[[v43-11-33]]

^<<v43-11-33,33>>^ Quando Jesus viu Maria chorar, e o povo também, sentiu profunda indignação e grande angústia.

[[v43-11-34]]

^<<v43-11-34,34>>^ "Onde vocês o colocaram?", perguntou. Eles responderam: "Senhor, venha e veja".

[[v43-11-35]]

^<<v43-11-35,35>>^ Jesus chorou.

[[v43-11-36]]

^<<v43-11-36,36>>^ As pessoas que estavam por perto disseram: "Vejam como ele o amava!".

[[v43-11-37]]

^<<v43-11-37,37>>^ Outros, porém, disseram: "Este homem curou um cego. Não poderia ter impedido que Lázaro morresse?".

[[v43-11-38]]

^<<v43-11-38,38>>^ Jesus, sentindo-se novamente indignado, chegou ao túmulo, uma gruta com uma pedra fechando a entrada.

[[v43-11-39]]

^<<v43-11-39,39>>^ "Rolem a pedra para o lado", ordenou. "Senhor, ele está morto há quatro dias", disse Marta, a irmã do falecido. "O mau cheiro será terrível."

[[v43-11-40]]

^<<v43-11-40,40>>^ Jesus respondeu: "Eu não lhe disse que, se você cresse, veria a glória de Deus?".

[[v43-11-41]]

^<<v43-11-41,41>>^ Então rolaram a pedra para o lado. Jesus olhou para o céu e disse: "Pai, eu te agradeço porque me ouviste.

[[v43-11-42]]

^<<v43-11-42,42>>^ Tu sempre me ouves, mas eu disse isso por causa de todas as pessoas que estão aqui, para que elas creiam que tu me enviaste".

[[v43-11-43]]

^<<v43-11-43,43>>^ Então Jesus gritou: "Lázaro, venha para fora!".

[[v43-11-44]]

^<<v43-11-44,44>>^ E o morto saiu, com as mãos e os pés presos com faixas e o rosto envolto num pano. Jesus disse: "Desamarrem as faixas e deixem-no ir!".

[[v43-11-45]]

^<<v43-11-45,45>>^ Muitos dos judeus que estavam com Maria creram em Jesus quando viram isso.

[[v43-11-46]]

^<<v43-11-46,46>>^ Alguns, no entanto, foram aos fariseus e contaram o que Jesus tinha feito.

[[v43-11-47]]

^<<v43-11-47,47>>^ Então os principais sacerdotes e fariseus reuniram o conselho dos líderes do povo. "Que vamos fazer?", perguntavam uns aos outros. "Sem dúvida, este homem realiza muitos sinais.

[[v43-11-48]]

^<<v43-11-48,48>>^ Se permitirmos que continue assim, logo todos crerão nele. Então o exército romano virá e destruirá nosso templo e nossa nação."

[[v43-11-49]]

^<<v43-11-49,49>>^ Caifás, o sumo sacerdote naquele ano, disse: "Vocês não sabem o que estão dizendo!

[[v43-11-50]]

^<<v43-11-50,50>>^ Não percebem que é melhor para vocês que um homem morra pelo povo em vez de a nação inteira ser destruída?".

[[v43-11-51]]

^<<v43-11-51,51>>^ Não disse isso por si mesmo, mas, sendo o sumo sacerdote naquele ano, profetizou que Jesus morreria pela nação inteira.

[[v43-11-52]]

^<<v43-11-52,52>>^ E não apenas por aquela nação, mas para reunir em um só corpo todos os filhos de Deus espalhados ao redor do mundo.

[[v43-11-53]]

^<<v43-11-53,53>>^ Daquele dia em diante, começaram a tramar a morte de Jesus.

[[v43-11-54]]

^<<v43-11-54,54>>^ Por essa razão, Jesus parou de andar no meio do povo. Foi para um lugar próximo do deserto, para o povoado de Efraim, onde permaneceu com seus discípulos.

[[v43-11-55]]

^<<v43-11-55,55>>^ Faltava pouco tempo para a festa judaica da Páscoa, e muita gente de toda a região chegou a Jerusalém para participar da cerimônia de purificação, antes que a Páscoa começasse.

[[v43-11-56]]

^<<v43-11-56,56>>^ Continuavam procurando Jesus e, estando eles no templo, perguntavam uns aos outros: "O que vocês acham? Será que ele virá para a Páscoa?".

[[v43-11-57]]

^<<v43-11-57,57>>^ Enquanto isso, os principais sacerdotes e fariseus deram ordem para que, se alguém soubesse onde Jesus estava, o denunciasse de imediato, a fim de que o prendessem.

'''

xref:043-joao/043-joao-010.adoc#v43-10-0[&#60; Capítulo Anterior] | <<v43-11-0,Topo>> | xref:043-joao/043-joao-012.adoc#v43-12-0[Próximo Capítulo &#62;]