include::./index.adoc[]

[[v36-1-0]]
=== Sofonias, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v36-1-1]]

^<<v36-1-1,1>>^ O SENHOR deu esta mensagem a Sofonias quando Josias, filho de Amom, era rei de Judá. Sofonias era filho de Cuchi, filho de Gedalias, filho de Amarias, filho de Ezequias.

[[v36-1-2]]

^<<v36-1-2,2>>^ "Destruirei todas as coisas sobre a face da terra", diz o SENHOR.

[[v36-1-3]]

^<<v36-1-3,3>>^ "Destruirei tanto pessoas como animais, destruirei as aves do céu e os peixes do mar. Reduzirei os perversos a montes de escombros e exterminarei a humanidade da face da terra", diz o SENHOR.

[[v36-1-4]]

^<<v36-1-4,4>>^ "Esmagarei Judá e Jerusalém com meu punho e eliminarei até o último vestígio de seu culto a Baal. Acabarei com os sacerdotes idólatras, de modo que todos se esquecerão deles.

[[v36-1-5]]

^<<v36-1-5,5>>^ Pois eles sobem a seus terraços e se curvam para as estrelas e os astros. Juram pelo nome do SENHOR, mas também adoram Moloque.

[[v36-1-6]]

^<<v36-1-6,6>>^ Destruirei os que antes seguiam o SENHOR, mas agora já não o fazem. Não pedem a direção do SENHOR, nem o buscam mais."

[[v36-1-7]]

^<<v36-1-7,7>>^ Fiquem em silêncio na presença do SENHOR Soberano, pois se aproxima o dia do SENHOR. O SENHOR preparou seu povo para uma grande matança e escolheu seus carrascos.

[[v36-1-8]]

^<<v36-1-8,8>>^ "Naquele dia de julgamento", diz o SENHOR, "castigarei os líderes e os príncipes de Judá e todos que seguem costumes estrangeiros.

[[v36-1-9]]

^<<v36-1-9,9>>^ Sim, castigarei os que participam de cultos idólatras e enchem a casa de seus senhores de violência e engano."

[[v36-1-10]]

^<<v36-1-10,10>>^ "Naquele dia", diz o SENHOR, "um grito de alarme virá do portão dos Peixes e ressoará em todo o bairro novo da cidade; um grande estrondo virá das colinas.

[[v36-1-11]]

^<<v36-1-11,11>>^ Lamentem, vocês que moram na região do mercado, pois todos os comerciantes e negociantes serão destruídos.

[[v36-1-12]]

^<<v36-1-12,12>>^ "Vasculharei com lamparinas os cantos mais escuros de Jerusalém, para castigar os que vivem acomodados em seus pecados. Pensam que o SENHOR não lhes fará coisa alguma, nem boa nem má.

[[v36-1-13]]

^<<v36-1-13,13>>^ Por isso, seus bens serão saqueados, e suas casas, destruídas. Construirão casas novas, mas não habitarão nelas. Plantarão videiras, mas não beberão de seu vinho.

[[v36-1-14]]

^<<v36-1-14,14>>^ "Esse dia terrível do SENHOR se aproxima; ele virá depressa. Será um dia de amargura em que até os homens fortes gritarão.

[[v36-1-15]]

^<<v36-1-15,15>>^ Será um dia em que o SENHOR derramará sua ira, dia de sofrimento e angústia, dia de ruína e desolação, dia de escuridão e trevas, dia de nuvens sombrias e densas,

[[v36-1-16]]

^<<v36-1-16,16>>^ dia de toque de trombetas e gritos de batalha. Caem as cidades cercadas por muros e as fortalezas mais poderosas!

[[v36-1-17]]

^<<v36-1-17,17>>^ "Porque pecaram contra o SENHOR, eu os farei tatear no escuro como cegos. Seu sangue será derramado no pó, e seus corpos apodrecerão sobre a terra."

[[v36-1-18]]

^<<v36-1-18,18>>^ Seu ouro e sua prata não os salvarão no dia da ira do SENHOR. Pois toda a terra será consumida pelo fogo de seu zelo. Ele dará um fim assustador a todos que habitam a terra.

'''

xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[&#60; Capítulo Anterior] | <<v36-1-0,Topo>> | xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[Próximo Capítulo &#62;]