include::./index.adoc[]

[[v36-2-0]]
=== Sofonias, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v36-2-1]]

^<<v36-2-1,1>>^ Reúna-se, ajunte-se, ó nação desavergonhada!

[[v36-2-2]]

^<<v36-2-2,2>>^ Reúna-se antes que comece o julgamento, antes que o tempo passe como palha levada pelo vento. Tome uma providência agora, antes que caia a terrível fúria do Senhor e comece o dia da ira do SENHOR.

[[v36-2-3]]

^<<v36-2-3,3>>^ Todos vocês, humildes, busquem o Senhor e sigam suas ordens. Busquem a justiça e vivam com humildade; talvez o SENHOR os proteja no dia de sua ira.

[[v36-2-4]]

^<<v36-2-4,4>>^ Gaza e Ascalom serão abandonadas, Asdode e Ecrom, demolidas.

[[v36-2-5]]

^<<v36-2-5,5>>^ Que aflição espera vocês, filisteus, que vivem no litoral e na terra de Canaã, pois este julgamento também é contra vocês! O SENHOR os destruirá, até que não reste ninguém em seu meio.

[[v36-2-6]]

^<<v36-2-6,6>>^ O litoral filisteu se transformará em pasto, lugar de acampamento de pastores e de currais para os rebanhos.

[[v36-2-7]]

^<<v36-2-7,7>>^ O remanescente da tribo de Judá ali se alimentará e, à noite, descansará nas casas abandonadas de Ascalom. Pois o SENHOR, seu Deus, visitará seu povo e, em sua bondade, os restaurará.

[[v36-2-8]]

^<<v36-2-8,8>>^ "Ouvi a zombaria dos moabitas e os insultos dos amonitas, que riem de meu povo e invadem suas fronteiras.

[[v36-2-9]]

^<<v36-2-9,9>>^ Agora, tão certo como eu vivo", diz o SENHOR dos Exércitos, o Deus de Israel, "Moabe e Amom serão destruídas, como Sodoma e Gomorra. Sua terra será um lugar de urtigas, de poços de sal e desolação sem fim. O remanescente de meu povo os saqueará e tomará sua terra."

[[v36-2-10]]

^<<v36-2-10,10>>^ Eles receberão o castigo merecido por seu orgulho, pois zombaram do povo do SENHOR dos Exércitos.

[[v36-2-11]]

^<<v36-2-11,11>>^ O SENHOR os encherá de terror quando destruir todos os deuses da terra. Então nações de todo o mundo adorarão o SENHOR, cada uma em sua terra.

[[v36-2-12]]

^<<v36-2-12,12>>^ "Vocês, etíopes, também serão mortos por minha espada", diz o SENHOR.

[[v36-2-13]]

^<<v36-2-13,13>>^ E, com sua mão, ele ferirá as terras do norte e destruirá a terra da Assíria. Fará de Nínive uma terra vazia e desolada, seca como um deserto.

[[v36-2-14]]

^<<v36-2-14,14>>^ A cidade orgulhosa se tornará pasto para rebanhos e gado, e toda espécie de animal selvagem ali descansará. A coruja do deserto e o mocho se alojarão no alto de suas colunas arruinadas, e pelas janelas se ouvirá o som das aves. O entulho fechará as entradas, e os painéis de cedro ficarão expostos.

[[v36-2-15]]

^<<v36-2-15,15>>^ Essa é a cidade barulhenta, que antes vivia em segurança. Dizia com orgulho: "Sou a mais poderosa das cidades! Não há outra igual a mim!". Agora, porém, vejam como ficou em ruínas, morada de animais selvagens. Todos que passarem por ela rirão de desprezo e sacudirão o punho em provocação.

'''

xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[&#60; Capítulo Anterior] | <<v36-2-0,Topo>> | xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[Próximo Capítulo &#62;]