include::./index.adoc[]

[[v36-3-0]]
=== Sofonias, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v36-3-1]]

^<<v36-3-1,1>>^ Que aflição espera Jerusalém, cidade rebelde e impura, cheia de violência e opressão!

[[v36-3-2]]

^<<v36-3-2,2>>^ Ninguém pode lhe dizer coisa alguma; ela recusa toda correção. Não confia no SENHOR, nem se aproxima de seu Deus.

[[v36-3-3]]

^<<v36-3-3,3>>^ Seus líderes são como leões que rugem, caçando suas vítimas. Seus juízes são como lobos ao cair da noite, que não deixam vestígio de suas presas ao amanhecer.

[[v36-3-4]]

^<<v36-3-4,4>>^ Seus profetas são mentirosos arrogantes que buscam os próprios interesses. Seus sacerdotes profanam o templo ao transgredir a lei de Deus.

[[v36-3-5]]

^<<v36-3-5,5>>^ Mas o SENHOR ainda está na cidade e não pratica o mal. A cada dia, ele faz justiça e nunca falha; os perversos, porém, não se envergonham.

[[v36-3-6]]

^<<v36-3-6,6>>^ "Exterminei as nações, destruí suas torres. Suas ruas ficaram desertas, suas cidades são ruínas caladas. Não há sobreviventes, nem um sequer.

[[v36-3-7]]

^<<v36-3-7,7>>^ Pensei: ‘Agora eles me temerão! Certamente ouvirão minhas advertências! Então não precisarei feri-los outra vez, nem destruir suas casas’. Mas eles continuam a se levantar cedo para praticar todo tipo de maldade.

[[v36-3-8]]

^<<v36-3-8,8>>^ Portanto, sejam pacientes", diz o SENHOR, "pois em breve me levantarei para acusar essas nações. Resolvi juntar os reinos da terra e derramar sobre eles minha ira ardente. Toda a terra será consumida pelo fogo de meu zelo.

[[v36-3-9]]

^<<v36-3-9,9>>^ "Então purificarei os lábios dos povos, para que possam se reunir e adorar o SENHOR.

[[v36-3-10]]

^<<v36-3-10,10>>^ Meu povo dispersado, que vive além dos rios da Etiópia, virá para apresentar suas ofertas.

[[v36-3-11]]

^<<v36-3-11,11>>^ Naquele dia, vocês não precisarão se envergonhar, pois já não serão rebeldes contra mim. Removerei de seu meio os orgulhosos; não haverá mais arrogância em meu santo monte.

[[v36-3-12]]

^<<v36-3-12,12>>^ Só restarão os pobres e os humildes, pois eles confiam no nome do SENHOR.

[[v36-3-13]]

^<<v36-3-13,13>>^ O remanescente de Israel não cometerá injustiça; não mentirão nem enganarão uns aos outros. Comerão e dormirão em segurança, e não haverá quem os atemorize."

[[v36-3-14]]

^<<v36-3-14,14>>^ Cante, ó filha de Sião! Grite bem alto, ó Israel! Alegre-se e exulte de todo coração, ó preciosa Jerusalém!

[[v36-3-15]]

^<<v36-3-15,15>>^ Pois o SENHOR removerá as acusações contra você e dispersará os exércitos de seu inimigo. O SENHOR, o rei de Israel, estará em seu meio, e você nunca mais temerá a calamidade.

[[v36-3-16]]

^<<v36-3-16,16>>^ Naquele dia, se anunciará em Jerusalém: "Anime-se, ó Sião! Não tenha medo!

[[v36-3-17]]

^<<v36-3-17,17>>^ Pois o SENHOR, seu Deus, está em seu meio; ele é um Salvador poderoso. Ele se agradará de vocês com exultação e acalmará todos os seus medos com amor; ele se alegrará em vocês com gritos de alegria!".

[[v36-3-18]]

^<<v36-3-18,18>>^ "Juntarei os que choram por não participarem das festas sagradas; nunca mais serão envergonhados.

[[v36-3-19]]

^<<v36-3-19,19>>^ Tratarei severamente todos que os oprimiram; salvarei os fracos e indefesos. Aos que antes foram exilados, darei reconhecimento e honra nas terras em que sofreram humilhação.

[[v36-3-20]]

^<<v36-3-20,20>>^ Naquele dia, reunirei vocês e os trarei para casa. Eu lhes darei honra e reconhecimento entre todas as nações da terra, e os restaurarei diante dos olhos delas. Eu, o SENHOR, falei!"

'''

xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[&#60; Capítulo Anterior] | <<v36-3-0,Topo>> | xref:037-ageu/037-ageu-001.adoc#v37-1-0[Próximo Capítulo &#62;]