include::./index.adoc[]

[[v32-1-0]]
=== Jonas, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v32-1-1]]

^<<v32-1-1,1>>^ O SENHOR deu esta mensagem a Jonas, filho de Amitai:

[[v32-1-2]]

^<<v32-1-2,2>>^ "Apronte-se e vá à grande cidade de Nínive. Anuncie meu julgamento contra ela, pois vi como seu povo é perverso".

[[v32-1-3]]

^<<v32-1-3,3>>^ Jonas se aprontou, mas foi na direção contrária, a fim de fugir do SENHOR. Desceu ao porto de Jope, onde encontrou um navio que estava de partida para Társis. Comprou a passagem e embarcou para Társis, a fim de fugir do SENHOR.

[[v32-1-4]]

^<<v32-1-4,4>>^ O SENHOR, porém, enviou sobre o mar um vento forte, e caiu uma tempestade tão violenta que o navio estava prestes a se despedaçar.

[[v32-1-5]]

^<<v32-1-5,5>>^ Com muito medo, os marinheiros clamavam a seus deuses para que os socorressem e lançavam a carga ao mar para deixar o navio mais leve. Enquanto isso, Jonas dormia profundamente no porão.

[[v32-1-6]]

^<<v32-1-6,6>>^ Então o capitão desceu para falar com ele. "Como pode dormir numa situação dessas?", disse. "Levante-se e ore a seu deus! Quem sabe ele prestará atenção em nós e poupará nossa vida!"

[[v32-1-7]]

^<<v32-1-7,7>>^ Então a tripulação tirou sortes para ver qual deles havia ofendido os deuses e causado a terrível tempestade. Quando tiraram as sortes, elas indicaram que Jonas era o culpado.

[[v32-1-8]]

^<<v32-1-8,8>>^ "Por que essa terrível tempestade veio sobre nós?", perguntaram. "Quem é você? Qual é sua profissão? De onde vem? Qual é sua nacionalidade?"

[[v32-1-9]]

^<<v32-1-9,9>>^ Jonas respondeu: "Sou hebreu e adoro o SENHOR, o Deus dos céus, que fez o mar e a terra".

[[v32-1-10]]

^<<v32-1-10,10>>^ Os marinheiros ficaram apavorados quando ouviram isso, pois Jonas já havia lhes contado que estava fugindo do SENHOR. "Por que fez uma coisa dessas?", disseram.

[[v32-1-11]]

^<<v32-1-11,11>>^ E, visto que a tempestade piorava cada vez mais, perguntaram-lhe: "O que devemos fazer com você para que a tempestade se acalme?".

[[v32-1-12]]

^<<v32-1-12,12>>^ Jonas respondeu: "Joguem-me ao mar, e ele voltará a ficar calmo. Eu sei que esta terrível tempestade é culpa minha".

[[v32-1-13]]

^<<v32-1-13,13>>^ Em vez disso, os marinheiros remaram com ainda mais força para levar a embarcação à terra, mas não conseguiram, pois o mar tempestuoso havia se tornado muito violento.

[[v32-1-14]]

^<<v32-1-14,14>>^ Então clamaram ao SENHOR e disseram: "Ó SENHOR, não nos deixes morrer por causa deste homem, e não nos responsabilizes pela morte dele! Ó SENHOR, tu sabes os motivos por que enviaste esta tempestade sobre ele!".

[[v32-1-15]]

^<<v32-1-15,15>>^ Depois, os marinheiros pegaram Jonas e o lançaram ao mar e, no mesmo instante, a furiosa tempestade se aquietou.

[[v32-1-16]]

^<<v32-1-16,16>>^ Espantados com o grande poder do SENHOR, os marinheiros lhe ofereceram um sacrifício e firmaram o compromisso de servi-lo.

[[v32-1-17]]

^<<v32-1-17,17>>^ O SENHOR fez que um grande peixe engolisse Jonas. E Jonas ficou dentro do peixe por três dias e três noites.

'''

xref:031-obadias/031-obadias-001.adoc#v31-1-0[&#60; Capítulo Anterior] | <<v32-1-0,Topo>> | xref:032-jonas/032-jonas-002.adoc#v32-2-0[Próximo Capítulo &#62;]