include::./index.adoc[]

[[v32-2-0]]
=== Jonas, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v32-2-1]]

^<<v32-2-1,1>>^ Então, de dentro do peixe, Jonas orou ao SENHOR, seu Deus,

[[v32-2-2]]

^<<v32-2-2,2>>^ e disse: "Em minha angústia, clamei ao SENHOR, e ele me respondeu. Gritei da terra dos mortos, e tu me ouviste.

[[v32-2-3]]

^<<v32-2-3,3>>^ Nas profundezas do oceano me lançaste, e afundei até o coração do mar. As águas me envolveram; fui encoberto por tuas tempestuosas ondas.

[[v32-2-4]]

^<<v32-2-4,4>>^ Então eu disse: ‘Tu me expulsaste de tua presença e, no entanto, olharei de novo para teu santo templo’.

[[v32-2-5]]

^<<v32-2-5,5>>^ "Afundei debaixo das ondas, e as águas se fecharam sobre mim; algas marinhas se enrolaram em minha cabeça.

[[v32-2-6]]

^<<v32-2-6,6>>^ Afundei até os alicerces dos montes; fiquei preso na terra, cujas portas se fecharam para sempre. Mas tu, ó SENHOR, meu Deus, me resgataste da morte!

[[v32-2-7]]

^<<v32-2-7,7>>^ Quando minha vida se esvaía, me lembrei do SENHOR, e minha oração subiu a ti em teu santo templo.

[[v32-2-8]]

^<<v32-2-8,8>>^ Os que adoram falsos deuses dão as costas para as misericórdias de Deus.

[[v32-2-9]]

^<<v32-2-9,9>>^ Eu, porém, oferecerei sacrifícios a ti com cânticos de gratidão e cumprirei todos os meus votos, pois somente do SENHOR vem o livramento".

[[v32-2-10]]

^<<v32-2-10,10>>^ Então o SENHOR ordenou que o peixe vomitasse Jonas na praia.

'''

xref:032-jonas/032-jonas-001.adoc#v32-1-0[&#60; Capítulo Anterior] | <<v32-2-0,Topo>> | xref:032-jonas/032-jonas-003.adoc#v32-3-0[Próximo Capítulo &#62;]