include::./index.adoc[]

[[v47-11-0]]
=== 2 Coríntios, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v47-11-1]]

^<<v47-11-1,1>>^ Espero que vocês suportem um pouco mais de minha insensatez. Por favor, continuem a ser pacientes comigo,

[[v47-11-2]]

^<<v47-11-2,2>>^ pois o cuidado que tenho com vocês vem do próprio Deus. Eu os prometi como noiva pura a um único marido, Cristo.

[[v47-11-3]]

^<<v47-11-3,3>>^ No entanto, temo que sua devoção pura e completa a Cristo seja corrompida de algum modo, como Eva foi enganada pela astúcia da serpente.

[[v47-11-4]]

^<<v47-11-4,4>>^ Vocês aceitam de boa vontade o que qualquer um lhes diz, mesmo que anuncie um Jesus diferente daquele que lhes anunciamos, ou um espírito diferente daquele que vocês receberam, ou boas-novas diferentes daquelas em que vocês creram.

[[v47-11-5]]

^<<v47-11-5,5>>^ Contudo, não me considero em nada inferior aos tais "superapóstolos" que ensinam essas coisas.

[[v47-11-6]]

^<<v47-11-6,6>>^ Posso não ter a técnica de um grande orador, mas não me falta conhecimento. Deixamos isso bem claro a vocês de todas as formas possíveis.

[[v47-11-7]]

^<<v47-11-7,7>>^ Será que fiz mal quando me humilhei e os honrei anunciando-lhes as boas-novas de Deus sem esperar nada em troca?

[[v47-11-8]]

^<<v47-11-8,8>>^ Para servir vocês sem lhes ser pesado, tomei contribuições de outras igrejas que eram mais pobres que vocês.

[[v47-11-9]]

^<<v47-11-9,9>>^ E, quando estive com vocês e não tinha o suficiente para me sustentar, não fui um peso para ninguém, pois os irmãos que vieram da Macedônia trouxeram tudo de que eu precisava. Nunca fui um peso para vocês, e nunca serei.

[[v47-11-10]]

^<<v47-11-10,10>>^ Tão certo como a verdade de Cristo está em mim, ninguém em toda a Acaia jamais me impedirá de me orgulhar disso.

[[v47-11-11]]

^<<v47-11-11,11>>^ Por quê? Por que não os amo? Deus sabe quanto os amo!

[[v47-11-12]]

^<<v47-11-12,12>>^ Assim, continuarei a fazer o que sempre tenho feito. Com isso, frustrarei aqueles que procuram uma oportunidade de se orgulhar de realizar um trabalho como o nosso.

[[v47-11-13]]

^<<v47-11-13,13>>^ Esses indivíduos são falsos apóstolos, obreiros enganosos disfarçados de apóstolos de Cristo.

[[v47-11-14]]

^<<v47-11-14,14>>^ Mas não me surpreendo. Até mesmo Satanás se disfarça de anjo de luz.

[[v47-11-15]]

^<<v47-11-15,15>>^ Portanto, não é de admirar que seus servos também finjam ser servos da justiça. No fim, receberão o castigo que suas obras merecem.

[[v47-11-16]]

^<<v47-11-16,16>>^ Volto a dizer: não pensem que sou insensato, mas, se o fizerem, aceitem-me como insensato, para que eu também me orgulhe um pouco.

[[v47-11-17]]

^<<v47-11-17,17>>^ Não expresso esse meu orgulho como algo que vem do Senhor, mas como um insensato o faria.

[[v47-11-18]]

^<<v47-11-18,18>>^ Uma vez que outros se orgulham de suas realizações humanas, farei o mesmo.

[[v47-11-19]]

^<<v47-11-19,19>>^ Afinal, vocês se consideram sábios, mas suportam de boa vontade os insensatos.

[[v47-11-20]]

^<<v47-11-20,20>>^ Aceitam que outros os escravizem, devorem seus bens, se aproveitem de vocês, os menosprezem e lhes batam no rosto.

[[v47-11-21]]

^<<v47-11-21,21>>^ Envergonho-me de dizer que fomos "fracos" demais para agir desse modo! Em qualquer coisa que eles se atrevem a se orgulhar (mais uma vez falo como insensato), eu também me atrevo.

[[v47-11-22]]

^<<v47-11-22,22>>^ Eles são hebreus? Eu também sou. São israelitas? Eu também sou. São descendentes de Abraão? Eu também sou.

[[v47-11-23]]

^<<v47-11-23,23>>^ São servos de Cristo? Sei que dou a impressão de estar louco, mas digo que tenho servido muito mais. Trabalhei com mais dedicação, fui encarcerado com mais frequência, perdi a conta de quantas vezes fui açoitado e, em várias ocasiões, enfrentei a morte.

[[v47-11-24]]

^<<v47-11-24,24>>^ Cinco vezes recebi dos líderes judeus os trinta e nove açoites.

[[v47-11-25]]

^<<v47-11-25,25>>^ Três vezes fui golpeado com varas. Fui apedrejado uma vez. Três vezes sofri naufrágio. Certa ocasião, passei uma noite e um dia no mar, à deriva.

[[v47-11-26]]

^<<v47-11-26,26>>^ Realizei várias jornadas longas. Enfrentei perigos em rios e com assaltantes. Enfrentei perigos de meu próprio povo, bem como dos gentios. Enfrentei perigos em cidades, em desertos e no mar. E enfrentei perigos por causa de homens que se diziam irmãos, mas não eram.

[[v47-11-27]]

^<<v47-11-27,27>>^ Tenho trabalhado arduamente, horas a fio, e passei muitas noites sem dormir. Passei fome e senti sede, e muitas vezes fiquei em jejum. Tremi de frio por não ter roupa suficiente para me agasalhar.

[[v47-11-28]]

^<<v47-11-28,28>>^ Além disso tudo, sobre mim pesa diariamente a preocupação com todas as igrejas.

[[v47-11-29]]

^<<v47-11-29,29>>^ Quem está fraco, que eu também não sinta fraqueza? Quem se deixa levar pelo caminho errado, que a indignação não me consuma?

[[v47-11-30]]

^<<v47-11-30,30>>^ Portanto, se devo me orgulhar, prefiro que seja das coisas que mostram como sou fraco.

[[v47-11-31]]

^<<v47-11-31,31>>^ Deus, o Pai de nosso Senhor Jesus, que é digno de louvor eterno, sabe que não estou mentindo.

[[v47-11-32]]

^<<v47-11-32,32>>^ Quando estava em Damasco, o governador sob o rei Aretas pôs guardas às portas da cidade para me capturar.

[[v47-11-33]]

^<<v47-11-33,33>>^ Para escapar dele, tive de ser baixado num cesto grande, de uma janela no muro da cidade.

'''

xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[Próximo Capítulo &#62;]