include::./index.adoc[]

[[v47-6-0]]
=== 2 Coríntios, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v47-6-1]]

^<<v47-6-1,1>>^ Como cooperadores de Deus, suplicamos a vocês que não recebam em vão a graça de Deus.

[[v47-6-2]]

^<<v47-6-2,2>>^ Pois Deus diz: "No tempo certo, eu o ouvi; no dia da salvação, eu lhe dei socorro". De fato, agora é o "tempo certo". Hoje é o dia da salvação!

[[v47-6-3]]

^<<v47-6-3,3>>^ Vivemos de forma que ninguém tropece por nossa causa, nem tenha motivo para criticar nosso ministério.

[[v47-6-4]]

^<<v47-6-4,4>>^ Em tudo que fazemos, mostramos que somos verdadeiros servos de Deus. Suportamos pacientemente aflições, privações e calamidades de todo tipo.

[[v47-6-5]]

^<<v47-6-5,5>>^ Fomos espancados e encarcerados, enfrentamos multidões furiosas, trabalhamos até a exaustão, suportamos noites sem dormir e passamos fome.

[[v47-6-6]]

^<<v47-6-6,6>>^ Mostramos quem somos por nossa pureza, nosso entendimento, nossa paciência e nossa bondade, pelo Espírito Santo que vive em nós e por nosso amor sincero.

[[v47-6-7]]

^<<v47-6-7,7>>^ Proclamamos a verdade fielmente, e o poder de Deus opera em nós. Usamos as armas da justiça, com a mão direita para atacar e com a mão esquerda para defender.

[[v47-6-8]]

^<<v47-6-8,8>>^ Servimos quer as pessoas nos honrem, quer nos desprezem, quer nos difamem, quer nos elogiem. Somos chamados de impostores, apesar de sermos honestos.

[[v47-6-9]]

^<<v47-6-9,9>>^ Somos tratados como desconhecidos, embora sejamos bem conhecidos. Vivemos à beira da morte, mas ainda estamos vivos. Fomos espancados, mas não mortos.

[[v47-6-10]]

^<<v47-6-10,10>>^ Nosso coração se entristece, mas sempre temos alegria. Somos pobres, mas enriquecemos a muitos outros. Não possuímos nada e, no entanto, temos tudo.

[[v47-6-11]]

^<<v47-6-11,11>>^ Queridos coríntios, falamos a vocês com toda honestidade e lhes abrimos o coração.

[[v47-6-12]]

^<<v47-6-12,12>>^ Não falta amor da nossa parte, mas vocês nos negaram seu afeto.

[[v47-6-13]]

^<<v47-6-13,13>>^ Peço que retribuam esse amor como se fossem meus próprios filhos. Abram o coração para nós!

[[v47-6-14]]

^<<v47-6-14,14>>^ Não se ponham em jugo desigual com os descrentes. Como pode a justiça ser parceira da maldade? Como pode a luz conviver com as trevas?

[[v47-6-15]]

^<<v47-6-15,15>>^ Que harmonia pode haver entre Cristo e o diabo? Como alguém que crê pode se ligar a quem não crê?

[[v47-6-16]]

^<<v47-6-16,16>>^ E que união pode haver entre o templo de Deus e os ídolos? Pois somos o templo do Deus vivo. Como ele próprio disse: "Habitarei e andarei no meio deles. Serei o seu Deus, e eles serão o meu povo.

[[v47-6-17]]

^<<v47-6-17,17>>^ Portanto, afastem-se e separem-se deles, diz o Senhor. Não toquem em coisas impuras, e eu os receberei.

[[v47-6-18]]

^<<v47-6-18,18>>^ Eu serei seu Pai, e vocês serão meus filhos e minhas filhas, diz o Senhor Todo-poderoso".

'''

xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[Próximo Capítulo &#62;]