include::./index.adoc[]

[[v47-5-0]]
=== 2 Coríntios, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v47-5-1]]

^<<v47-5-1,1>>^ Sabemos que, quando nosso corpo terreno, esta tenda em que vivemos, se desfizer, teremos um corpo eterno, uma casa no céu feita para nós pelo próprio Deus, e não por mãos humanas.

[[v47-5-2]]

^<<v47-5-2,2>>^ Na tenda terrena, gememos e desejamos ansiosamente nos vestir com nosso lar celestial, como se fosse uma roupa nova.

[[v47-5-3]]

^<<v47-5-3,3>>^ Porque de fato nos vestiremos com um corpo celestial, e não ficaremos despidos.

[[v47-5-4]]

^<<v47-5-4,4>>^ Enquanto vivemos nesta tenda que é o corpo terreno, gememos e suspiramos, mas isso não significa que queremos ser despidos. Na verdade, queremos vestir nosso corpo novo, para que este corpo mortal seja engolido pela vida.

[[v47-5-5]]

^<<v47-5-5,5>>^ Deus nos preparou para isso e, como garantia, nos deu o Espírito.

[[v47-5-6]]

^<<v47-5-6,6>>^ Portanto, temos sempre confiança, apesar de sabermos que, enquanto vivemos neste corpo, não estamos em nosso lar com o Senhor.

[[v47-5-7]]

^<<v47-5-7,7>>^ Porque vivemos por fé, e não pelo que vemos.

[[v47-5-8]]

^<<v47-5-8,8>>^ Sim, temos confiança absoluta e preferíamos deixar este corpo terreno, pois então estaríamos em nosso lar com o Senhor.

[[v47-5-9]]

^<<v47-5-9,9>>^ Assim, quer estejamos neste corpo, quer o deixemos, nosso objetivo é agradar ao Senhor.

[[v47-5-10]]

^<<v47-5-10,10>>^ Pois todos nós teremos de comparecer diante do tribunal de Cristo, para que cada um receba o que merecer pelo bem ou pelo mal que tiver feito neste corpo terreno.

[[v47-5-11]]

^<<v47-5-11,11>>^ Assim, conhecendo o temor ao Senhor, procuramos persuadir outros. Deus sabe que somos sinceros, e espero que vocês também o saibam.

[[v47-5-12]]

^<<v47-5-12,12>>^ Estamos mais uma vez nos recomendando a vocês? Nada disso, estamos apenas lhes dando motivos para que se orgulhem de nós, a fim de que possam responder àqueles que se orgulham nas aparências, e não no coração.

[[v47-5-13]]

^<<v47-5-13,13>>^ Se parecemos loucos, é para dar glória a Deus, e se mantemos o juízo, é para o bem de vocês.

[[v47-5-14]]

^<<v47-5-14,14>>^ De qualquer forma, o amor de Cristo nos impulsiona. Porque cremos que ele morreu por todos, também cremos que todos morreram.

[[v47-5-15]]

^<<v47-5-15,15>>^ Ele morreu por todos, para que os que recebem sua nova vida não vivam mais para si mesmos, mas para Cristo, que morreu e ressuscitou por eles.

[[v47-5-16]]

^<<v47-5-16,16>>^ Portanto, não avaliamos mais ninguém do ponto de vista humano. Em outros tempos, pensávamos em Cristo apenas do ponto de vista humano, mas agora o conhecemos de modo bem diferente.

[[v47-5-17]]

^<<v47-5-17,17>>^ Logo, todo aquele que está em Cristo se tornou nova criação. A velha vida acabou, e uma nova vida teve início!

[[v47-5-18]]

^<<v47-5-18,18>>^ E tudo isso vem de Deus, aquele que nos trouxe de volta para si por meio de Cristo e nos encarregou de reconciliar outros com ele.

[[v47-5-19]]

^<<v47-5-19,19>>^ Pois, em Cristo, Deus estava reconciliando consigo o mundo, não levando mais em conta os pecados das pessoas. E ele nos deu esta mensagem maravilhosa de reconciliação.

[[v47-5-20]]

^<<v47-5-20,20>>^ Agora, portanto, somos embaixadores de Cristo; Deus faz seu apelo por nosso intermédio. Falamos em nome de Cristo quando dizemos: "Reconciliem-se com Deus!".

[[v47-5-21]]

^<<v47-5-21,21>>^ Pois Deus fez de Cristo, aquele que nunca pecou, a oferta por nosso pecado, para que por meio dele fôssemos declarados justos diante de Deus.

'''

xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[Próximo Capítulo &#62;]