include::./index.adoc[]

[[v47-13-0]]
=== 2 Coríntios, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v47-13-1]]

^<<v47-13-1,1>>^ Esta é a terceira vez que irei visitá-los. "Os fatos a respeito de cada caso devem ser confirmados pelo depoimento de duas ou três testemunhas."

[[v47-13-2]]

^<<v47-13-2,2>>^ Em minha segunda visita, já adverti aqueles que estavam em pecado. Agora, como naquela ocasião, volto a adverti-los e também os demais de que, da próxima vez, não os pouparei.

[[v47-13-3]]

^<<v47-13-3,3>>^ Eu lhes darei todas as provas que desejarem de que Cristo fala por meu intermédio. Ele não é fraco ao tratar com vocês. Ao contrário, é poderoso entre vocês.

[[v47-13-4]]

^<<v47-13-4,4>>^ Embora ele tenha sido crucificado em fraqueza, agora vive pelo poder de Deus. Nós também somos fracos, como Cristo foi, mas, quando tratarmos com vocês, estaremos vivos com ele e teremos o poder de Deus.

[[v47-13-5]]

^<<v47-13-5,5>>^ Examinem a si mesmos. Verifiquem se estão praticando o que afirmam crer. Assim, poderão ser aprovados. Certamente sabem que Jesus Cristo está entre vocês; do contrário, já foram reprovados.

[[v47-13-6]]

^<<v47-13-6,6>>^ Minha expectativa é que, uma vez que se examinarem, reconheçam que não fomos reprovados.

[[v47-13-7]]

^<<v47-13-7,7>>^ Oramos a Deus para que vocês não façam o que é mau, não para que pareça que fomos aprovados em nosso serviço, mas para que façam o que é certo, mesmo que pareça que fomos reprovados ao repreendê-los.

[[v47-13-8]]

^<<v47-13-8,8>>^ Pois não podemos resistir à verdade, mas devemos sempre defendê-la.

[[v47-13-9]]

^<<v47-13-9,9>>^ Ficamos alegres quando estamos fracos, se isso ajudar a mostrar que, na realidade, vocês estão fortes. Oramos para que sejam restaurados.

[[v47-13-10]]

^<<v47-13-10,10>>^ Escrevo-lhes essas coisas antes de visitá-los, na esperança de que, ao chegar, não precise tratá-los severamente. Meu desejo é usar a autoridade que o Senhor me deu para fortalecê-los, e não para destruí-los.

[[v47-13-11]]

^<<v47-13-11,11>>^ Irmãos, encerro minha carta com estas últimas palavras: Alegrem-se. Cresçam até alcançar a maturidade. Encorajem-se mutuamente. Vivam em harmonia e paz. Então o Deus de amor e paz estará com vocês.

[[v47-13-12]]

^<<v47-13-12,12>>^ Saúdem uns aos outros com beijo santo.

[[v47-13-13]]

^<<v47-13-13,13>>^ Todo o povo santo lhes envia saudações.

[[v47-13-14]]

^<<v47-13-14,14>>^ Que a graça do Senhor Jesus Cristo, o amor de Deus e a comunhão do Espírito Santo sejam com todos vocês.

'''

xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[&#60; Capítulo Anterior] | <<v47-13-0,Topo>> | xref:048-galatas/048-galatas-001.adoc#v48-1-0[Próximo Capítulo &#62;]