include::./index.adoc[]

[[v47-2-0]]
=== 2 Coríntios, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v47-2-1]]

^<<v47-2-1,1>>^ Por isso resolvi não entristecê-los com outra visita dolorosa.

[[v47-2-2]]

^<<v47-2-2,2>>^ Pois, se eu lhes causar tristeza, quem me alegrará? Certamente não serão aqueles a quem entristeci.

[[v47-2-3]]

^<<v47-2-3,3>>^ Esse foi o motivo de eu ter escrito como o fiz, para que, quando eu for, não seja entristecido por aqueles que deveriam me alegrar. Sem dúvida, vocês sabem que minha alegria vem do fato de vocês estarem alegres.

[[v47-2-4]]

^<<v47-2-4,4>>^ Escrevi aquela carta com grande angústia, com o coração aflito e muitas lágrimas. Minha intenção não era entristecê-los, mas mostrar-lhes quanto amo vocês.

[[v47-2-5]]

^<<v47-2-5,5>>^ Não exagero quando digo que o homem que causou tantos problemas magoou não somente a mim, mas, até certo ponto, a todos vocês.

[[v47-2-6]]

^<<v47-2-6,6>>^ A maioria de vocês se opôs a ele, e isso já foi castigo suficiente.

[[v47-2-7]]

^<<v47-2-7,7>>^ Agora, porém, é hora de perdoá-lo e confortá-lo; do contrário, pode acontecer de ele ser vencido pela tristeza excessiva.

[[v47-2-8]]

^<<v47-2-8,8>>^ Peço, portanto, que reafirmem seu amor por ele.

[[v47-2-9]]

^<<v47-2-9,9>>^ Eu lhes escrevi daquela forma para testá-los e ver se seguiriam todas as minhas instruções.

[[v47-2-10]]

^<<v47-2-10,10>>^ Se vocês perdoam esse homem, eu também o perdoo. E, quando eu perdoo o que precisa ser perdoado, faço-o na presença de Cristo, em favor de vocês,

[[v47-2-11]]

^<<v47-2-11,11>>^ para que Satanás não tenha vantagem sobre nós, pois conhecemos seus planos malignos.

[[v47-2-12]]

^<<v47-2-12,12>>^ Quando cheguei à cidade de Trôade para anunciar as boas-novas de Cristo, o Senhor me abriu uma porta de oportunidade.

[[v47-2-13]]

^<<v47-2-13,13>>^ Contudo, não tive paz em meu espírito, pois meu querido irmão Tito ainda não havia chegado com notícias de vocês. Assim, despedi-me dos irmãos dali e fui à Macedônia para procurá-lo.

[[v47-2-14]]

^<<v47-2-14,14>>^ Mas graças a Deus, que, em Cristo, sempre nos conduz triunfantemente. Agora, por nosso intermédio, ele espalha o conhecimento de Cristo por toda parte, como um doce perfume.

[[v47-2-15]]

^<<v47-2-15,15>>^ Somos o aroma de Cristo que se eleva até Deus. Mas esse aroma é percebido de forma diferente por aqueles que estão sendo salvos e por aqueles que estão perecendo.

[[v47-2-16]]

^<<v47-2-16,16>>^ Para os que estão perecendo, somos cheiro terrível de morte e condenação. Mas, para os que estão sendo salvos, somos perfume que dá vida. E quem está à altura de uma tarefa como essa?

[[v47-2-17]]

^<<v47-2-17,17>>^ Não somos como muitos que fazem da palavra de Deus um artigo de comércio. Pregamos a palavra de Deus com sinceridade e com a autoridade de Cristo, sabendo que Deus nos observa.

'''

xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[Próximo Capítulo &#62;]