include::./index.adoc[]

[[v47-4-0]]
=== 2 Coríntios, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v47-4-1]]

^<<v47-4-1,1>>^ Portanto, visto que Deus, em sua misericórdia, nos deu a tarefa de ministrar nesse novo sistema, nunca desistimos.

[[v47-4-2]]

^<<v47-4-2,2>>^ Rejeitamos todos os atos vergonhosos e métodos dissimulados. Não procuramos enganar ninguém nem distorcemos a palavra de Deus. Em vez disso, dizemos a verdade diante de Deus, e todos que são honestos sabem disso.

[[v47-4-3]]

^<<v47-4-3,3>>^ Se as boas-novas que anunciamos estão encobertas atrás de um véu, é apenas para aqueles que estão perecendo.

[[v47-4-4]]

^<<v47-4-4,4>>^ O deus deste mundo cegou a mente dos que não creem, para que não consigam ver a luz das boas-novas, não entendendo esta mensagem a respeito da glória de Cristo, que é a imagem de Deus.

[[v47-4-5]]

^<<v47-4-5,5>>^ Não andamos por aí falando de nós mesmos, mas proclamamos que Jesus Cristo é Senhor e que nós mesmos somos servos de vocês por causa de Jesus.

[[v47-4-6]]

^<<v47-4-6,6>>^ Pois Deus, que disse: "Haja luz na escuridão", é quem brilhou em nosso coração, para que conhecêssemos a glória de Deus na face de Jesus Cristo.

[[v47-4-7]]

^<<v47-4-7,7>>^ Agora nós mesmos somos como vasos frágeis de barro que contêm esse grande tesouro. Assim, fica evidente que esse grande poder vem de Deus, e não de nós.

[[v47-4-8]]

^<<v47-4-8,8>>^ De todos os lados somos pressionados por aflições, mas não esmagados. Ficamos perplexos, mas não desesperados.

[[v47-4-9]]

^<<v47-4-9,9>>^ Somos perseguidos, mas não abandonados. Somos derrubados, mas não destruídos.

[[v47-4-10]]

^<<v47-4-10,10>>^ Pelo sofrimento, nosso corpo continua a participar da morte de Jesus, para que a vida de Jesus também se manifeste em nosso corpo.

[[v47-4-11]]

^<<v47-4-11,11>>^ Sim, vivemos sob constante perigo de morte, porque servimos a Jesus, para que a vida de Jesus se manifeste em nosso corpo mortal.

[[v47-4-12]]

^<<v47-4-12,12>>^ Assim, enfrentamos a morte, mas isso resulta em vida para vocês.

[[v47-4-13]]

^<<v47-4-13,13>>^ Continuamos a pregar porque temos o mesmo tipo de fé mencionada nas Escrituras: "Cri em Deus, por isso falei".

[[v47-4-14]]

^<<v47-4-14,14>>^ Sabemos que Deus, que ressuscitou o Senhor Jesus, também nos ressuscitará com Jesus e nos apresentará a ele junto com vocês.

[[v47-4-15]]

^<<v47-4-15,15>>^ Tudo isso é para o bem de vocês. E, à medida que a graça alcançar mais pessoas, haverá muitas ações de graças, e Deus receberá cada vez mais glória.

[[v47-4-16]]

^<<v47-4-16,16>>^ Por isso, nunca desistimos. Ainda que nosso exterior esteja morrendo, nosso interior está sendo renovado a cada dia.

[[v47-4-17]]

^<<v47-4-17,17>>^ Pois estas aflições pequenas e momentâneas que agora enfrentamos produzem para nós uma glória que pesa mais que todas as angústias e durará para sempre.

[[v47-4-18]]

^<<v47-4-18,18>>^ Portanto, não olhamos para aquilo que agora podemos ver; em vez disso, fixamos o olhar naquilo que não se pode ver. Pois as coisas que agora vemos logo passarão, mas as que não podemos ver durarão para sempre.

'''

xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[&#60; Capítulo Anterior] | <<v47-4-0,Topo>> | xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[Próximo Capítulo &#62;]