include::./index.adoc[]

[[v47-3-0]]
=== 2 Coríntios, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v47-3-1]]

^<<v47-3-1,1>>^ Será que estamos começando a nos recomendar outra vez? Somos como aqueles que precisam entregar-lhes ou pedir-lhes cartas de recomendação?

[[v47-3-2]]

^<<v47-3-2,2>>^ Vocês mesmos são nossa carta, escrita em nosso coração, para ser conhecida e lida por todos!

[[v47-3-3]]

^<<v47-3-3,3>>^ Sem dúvida, vocês são uma carta de Cristo, que mostra os resultados de nosso trabalho em seu meio, escrita não com pena e tinta, mas com o Espírito do Deus vivo, e gravada não em tábuas de pedra, mas em corações humanos.

[[v47-3-4]]

^<<v47-3-4,4>>^ Estamos certos disso tudo por causa da grande confiança que temos em Deus por meio de Cristo.

[[v47-3-5]]

^<<v47-3-5,5>>^ Não que nos consideremos capazes de fazer qualquer coisa por conta própria; nossa capacitação vem de Deus.

[[v47-3-6]]

^<<v47-3-6,6>>^ Ele nos capacitou para sermos ministros da nova aliança, não da lei escrita, mas do Espírito. A lei escrita termina em morte, mas o Espírito dá vida.

[[v47-3-7]]

^<<v47-3-7,7>>^ O antigo sistema, com suas leis gravadas em pedra, terminava em morte, embora tivesse começado com tamanha glória que os israelitas não conseguiam olhar para o rosto de Moisés, por causa da glória que brilhava em seu rosto, ainda que esse brilho já estivesse se desvanecendo.

[[v47-3-8]]

^<<v47-3-8,8>>^ Acaso não deveríamos esperar uma glória muito maior no novo sistema, que se baseia na obra do Espírito?

[[v47-3-9]]

^<<v47-3-9,9>>^ Se o antigo sistema, que traz condenação, era glorioso, muito mais glorioso é o novo sistema, que nos torna justos diante de Deus!

[[v47-3-10]]

^<<v47-3-10,10>>^ De fato, a glória do passado não era nada gloriosa em comparação com a glória magnífica de agora.

[[v47-3-11]]

^<<v47-3-11,11>>^ Portanto, se o antigo sistema, que foi substituído, era cheio de glória, muito mais glorioso é o novo, que permanece para sempre!

[[v47-3-12]]

^<<v47-3-12,12>>^ Uma vez que o novo sistema nos dá tal esperança, podemos falar com grande coragem.

[[v47-3-13]]

^<<v47-3-13,13>>^ Não somos como Moisés, que cobria o rosto com um véu para que os israelitas não vissem a glória, embora ela já estivesse se desvanecendo.

[[v47-3-14]]

^<<v47-3-14,14>>^ Mas a mente do povo estava endurecida e, até hoje, toda vez que a antiga aliança é lida, o mesmo véu lhes cobre a mente, e esse véu só pode ser removido em Cristo.

[[v47-3-15]]

^<<v47-3-15,15>>^ Até hoje, quando eles leem os escritos de Moisés, seu coração está coberto por esse véu.

[[v47-3-16]]

^<<v47-3-16,16>>^ Contudo, sempre que alguém se volta para o Senhor, o véu é removido.

[[v47-3-17]]

^<<v47-3-17,17>>^ Pois o Senhor é o Espírito, e onde está o Espírito do Senhor, ali há liberdade.

[[v47-3-18]]

^<<v47-3-18,18>>^ Portanto, todos nós, dos quais o véu foi removido, podemos ver e refletir a glória do Senhor, e o Senhor, que é o Espírito, nos transforma gradativamente à sua imagem gloriosa, deixando-nos cada vez mais parecidos com ele.

'''

xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[Próximo Capítulo &#62;]