include::./index.adoc[]

[[v47-8-0]]
=== 2 Coríntios, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v47-8-1]]

^<<v47-8-1,1>>^ Agora, irmãos, queremos que saibam o que Deus, em sua graça, tem feito por meio das igrejas da Macedônia.

[[v47-8-2]]

^<<v47-8-2,2>>^ Elas têm sido provadas com muitas aflições, mas sua grande alegria e extrema pobreza transbordaram em rica generosidade.

[[v47-8-3]]

^<<v47-8-3,3>>^ Posso testemunhar que deram não apenas o que podiam, mas muito além disso, e o fizeram por iniciativa própria.

[[v47-8-4]]

^<<v47-8-4,4>>^ Eles nos suplicaram repetidamente o privilégio de participar da oferta ao povo santo.

[[v47-8-5]]

^<<v47-8-5,5>>^ Fizeram até mais do que esperávamos, pois seu primeiro passo foi entregar-se ao Senhor e a nós, como era desejo de Deus.

[[v47-8-6]]

^<<v47-8-6,6>>^ Por isso pedimos a Tito, que inicialmente encorajou vocês a contribuírem, que os visitasse outra vez e os animasse a completar esse serviço de generosidade.

[[v47-8-7]]

^<<v47-8-7,7>>^ Visto que vocês se destacam em tantos aspectos — na fé, nos discursos eloquentes, no conhecimento, no entusiasmo e no amor que receberam de nós —, queríamos que também se destacassem no generoso ato de contribuir.

[[v47-8-8]]

^<<v47-8-8,8>>^ Não estou ordenando que o façam, mas sim testando a sinceridade de seu amor ao compará-lo com a dedicação de outros.

[[v47-8-9]]

^<<v47-8-9,9>>^ Vocês conhecem a graça de nosso Senhor Jesus Cristo. Embora fosse rico, por amor a vocês ele se fez pobre, para que por meio da pobreza dele vocês se tornassem ricos.

[[v47-8-10]]

^<<v47-8-10,10>>^ Este é meu conselho: seria bom que terminassem o que começaram há um ano, quando foram os primeiros a querer contribuir e a efetivamente fazê-lo.

[[v47-8-11]]

^<<v47-8-11,11>>^ Assim, completem o que começaram. Que a boa vontade demonstrada no princípio seja igualada, agora, por sua contribuição. Doem proporcionalmente àquilo que possuem.

[[v47-8-12]]

^<<v47-8-12,12>>^ Tudo que derem será aceitável, desde que o façam de boa vontade, de acordo com o que têm, e não com o que não têm.

[[v47-8-13]]

^<<v47-8-13,13>>^ Não que sua contribuição deva facilitar a vida dos outros e dificultar a de vocês. Quero dizer apenas que deve haver igualdade.

[[v47-8-14]]

^<<v47-8-14,14>>^ No momento, vocês têm fartura e podem ajudar os que passam por necessidades. Em outra ocasião, eles terão fartura e poderão compartilhar com vocês quando for necessário. Assim, haverá igualdade.

[[v47-8-15]]

^<<v47-8-15,15>>^ Como dizem as Escrituras: "Para aqueles que muito recolheram nada sobrou, e para aqueles que pouco recolheram nada faltou".

[[v47-8-16]]

^<<v47-8-16,16>>^ Agradeço a Deus porque ele concedeu a Tito a mesma dedicação que eu tenho por vocês.

[[v47-8-17]]

^<<v47-8-17,17>>^ Tito recebeu com prazer nosso pedido para que os visitasse outra vez. Na verdade, ele mesmo estava ansioso para ir vê-los.

[[v47-8-18]]

^<<v47-8-18,18>>^ Com ele estamos enviando outro irmão, que é elogiado por todas as igrejas como pregador das boas-novas.

[[v47-8-19]]

^<<v47-8-19,19>>^ Ele foi nomeado pelas igrejas para nos acompanhar quando levarmos a oferta, um serviço que visa glorificar o Senhor e mostrar nossa disposição de ajudar.

[[v47-8-20]]

^<<v47-8-20,20>>^ Com isso, queremos evitar qualquer crítica à nossa maneira de administrar essa oferta generosa.

[[v47-8-21]]

^<<v47-8-21,21>>^ Tomamos o cuidado de agir honradamente não só aos olhos do Senhor, mas também diante das pessoas.

[[v47-8-22]]

^<<v47-8-22,22>>^ Além disso, estamos enviando com eles outro irmão que muitas vezes deu provas de seu bom caráter e que, em várias ocasiões e de diversas maneiras, demonstrou enorme dedicação. E, por causa da grande confiança que ele tem em vocês, agora está ainda mais empolgado.

[[v47-8-23]]

^<<v47-8-23,23>>^ Se alguém lhes perguntar a respeito de Tito, digam que ele é meu colaborador, que trabalha comigo para ajudar vocês. Quanto aos irmãos que o acompanham, foram enviados pelas igrejas e trazem honra a Cristo.

[[v47-8-24]]

^<<v47-8-24,24>>^ Portanto, mostrem diante deles seu amor e provem para todas as igrejas que temos razão ao elogiar vocês.

'''

xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[Próximo Capítulo &#62;]