include::./index.adoc[]

[[v47-12-0]]
=== 2 Coríntios, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v47-12-1]]

^<<v47-12-1,1>>^ É necessário prosseguir com meus motivos de orgulho. Mesmo que isso não me sirva de nada, vou lhes falar agora das visões e revelações que recebi do Senhor.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um homem em Cristo que, há catorze anos, foi arrebatado ao terceiro céu. Se foi no corpo ou fora do corpo, não sei; só Deus o sabe.

[[v47-12-3]]

^<<v47-12-3,3>>^ Sim, somente Deus sabe se foi no corpo ou fora do corpo. Mas eu sei

[[v47-12-4]]

^<<v47-12-4,4>>^ que tal homem foi arrebatado ao paraíso e ouviu coisas tão maravilhosas que não podem ser expressas em palavras, coisas que a nenhum homem é permitido relatar.

[[v47-12-5]]

^<<v47-12-5,5>>^ Da experiência desse homem eu teria razão de me orgulhar, mas não o farei; na verdade, minhas fraquezas são minha única razão de orgulho.

[[v47-12-6]]

^<<v47-12-6,6>>^ Se quisesse me orgulhar, não seria insensato de fazê-lo, pois estaria dizendo a verdade. Mas não o farei, pois não quero que ninguém me dê crédito além do que pode ver em minha vida ou ouvir em minha mensagem,

[[v47-12-7]]

^<<v47-12-7,7>>^ ainda que eu tenha recebido revelações tão maravilhosas. Portanto, para evitar que eu me tornasse arrogante, foi-me dado um espinho na carne, um mensageiro de Satanás para me atormentar e impedir qualquer arrogância.

[[v47-12-8]]

^<<v47-12-8,8>>^ Em três ocasiões, supliquei ao Senhor que o removesse,

[[v47-12-9]]

^<<v47-12-9,9>>^ mas ele disse: "Minha graça é tudo de que você precisa. Meu poder opera melhor na fraqueza". Portanto, agora fico feliz de me orgulhar de minhas fraquezas, para que o poder de Deus opere por meu intermédio.

[[v47-12-10]]

^<<v47-12-10,10>>^ Por isso aceito com prazer fraquezas e insultos, privações, perseguições e aflições que sofro por Cristo. Pois, quando sou fraco, então é que sou forte.

[[v47-12-11]]

^<<v47-12-11,11>>^ Vocês me obrigaram a agir como insensato. Vocês é que deveriam me elogiar, pois, embora eu nada seja, não sou inferior a esses "superapóstolos".

[[v47-12-12]]

^<<v47-12-12,12>>^ Quando estive com vocês, certamente dei provas de que sou apóstolo, pois com grande paciência realizei sinais, maravilhas e milagres entre vocês.

[[v47-12-13]]

^<<v47-12-13,13>>^ A única coisa que não fiz, e que faço nas outras igrejas, foi me tornar um peso para vocês. Perdoem-me por essa injustiça!

[[v47-12-14]]

^<<v47-12-14,14>>^ Agora irei visitá-los pela terceira vez e não serei um peso para vocês. Não quero seus bens; quero vocês. Afinal, os filhos não ajuntam riquezas para os pais. Ao contrário, são os pais que ajuntam riquezas para os filhos.

[[v47-12-15]]

^<<v47-12-15,15>>^ Por vocês, de boa vontade me desgastarei e gastarei tudo que tenho, embora pareça que, quanto mais eu os ame, menos vocês me amam.

[[v47-12-16]]

^<<v47-12-16,16>>^ Talvez reconheçam que não fui um peso para vocês, mas pensem que, mesmo assim, fui astuto e usei de artimanhas para tirar proveito de vocês.

[[v47-12-17]]

^<<v47-12-17,17>>^ Mas como? Algum dos homens que lhes enviei se aproveitou de vocês?

[[v47-12-18]]

^<<v47-12-18,18>>^ Quando insisti com Tito para que fosse visitá-los e enviei com ele outro irmão, por acaso Tito os explorou? Não temos nós o mesmo espírito e andamos nos passos um do outro, agindo do mesmo modo?

[[v47-12-19]]

^<<v47-12-19,19>>^ Talvez vocês pensem que estamos apresentando desculpas. Não é verdade. Dizemos tais coisas como servos de Cristo, tendo Deus como testemunha. Tudo que fazemos, amados, é para fortalecê-los.

[[v47-12-20]]

^<<v47-12-20,20>>^ Pois temo que, ao visitá-los, não goste daquilo que encontrarei e vocês não gostem de minha reação. Temo que encontre brigas, inveja, ira, egoísmo, calúnia, intrigas, arrogância e desordem.

[[v47-12-21]]

^<<v47-12-21,21>>^ Sim, temo que, ao visitá-los outra vez, Deus me humilhe diante de vocês e eu venha a me entristecer porque muitos de vocês não abandonaram os pecados que cometiam no passado e não se arrependeram de sua impureza, sua imoralidade sexual e seu anseio por prazeres sensuais.

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]