include::./index.adoc[]

[[v47-10-0]]
=== 2 Coríntios, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v47-10-1]]

^<<v47-10-1,1>>^ Agora eu, Paulo, apelo a vocês com a mansidão e a bondade de Cristo, mesmo ciente de que vocês me consideram fraco pessoalmente e duro apenas a distância, quando lhes escrevo.

[[v47-10-2]]

^<<v47-10-2,2>>^ Pois bem, suplico-lhes que, quando eu for visitá-los, não precise ser duro com aqueles que pensam que agimos segundo motivações humanas.

[[v47-10-3]]

^<<v47-10-3,3>>^ Embora sejamos humanos, não lutamos conforme os padrões humanos.

[[v47-10-4]]

^<<v47-10-4,4>>^ Usamos as armas poderosas de Deus, e não as armas do mundo, para derrubar as fortalezas do raciocínio humano e acabar com os falsos argumentos.

[[v47-10-5]]

^<<v47-10-5,5>>^ Destruímos todas as opiniões arrogantes que impedem as pessoas de conhecer a Deus. Levamos cativo todo pensamento rebelde e o ensinamos a obedecer a Cristo.

[[v47-10-6]]

^<<v47-10-6,6>>^ E, depois que vocês se tornarem inteiramente obedientes, estaremos prontos para punir todos que insistirem em desobedecer.

[[v47-10-7]]

^<<v47-10-7,7>>^ Vocês se preocupam apenas com o que é aparente. Aqueles que afirmam pertencer a Cristo devem reconhecer que pertencemos a Cristo tanto quanto eles.

[[v47-10-8]]

^<<v47-10-8,8>>^ Pode parecer que estou me orgulhando além do que deveria da autoridade que o Senhor nos deu, mas nossa autoridade visa edificar vocês, e não destruí-los. Portanto, não me envergonharei de usá-la.

[[v47-10-9]]

^<<v47-10-9,9>>^ Não é minha intenção assustar vocês com minhas cartas.

[[v47-10-10]]

^<<v47-10-10,10>>^ Pois alguns dizem: "As cartas de Paulo são exigentes e enérgicas, mas em pessoa ele é fraco e seus discursos de nada valem".

[[v47-10-11]]

^<<v47-10-11,11>>^ Essa gente deveria perceber que, quando estivermos presentes em pessoa, nossas ações serão tão enérgicas quanto aquilo que dizemos a distância, em nossas cartas.

[[v47-10-12]]

^<<v47-10-12,12>>^ Não nos atreveríamos a nos classificar como esses indivíduos nem a nos comparar com eles, que se julgam tão importantes. Ao se compararem apenas uns com os outros, usando a si mesmos como medida, só mostram como são ignorantes.

[[v47-10-13]]

^<<v47-10-13,13>>^ Não nos orgulharemos do que se fez fora de nosso campo de autoridade. Antes, nos orgulharemos apenas do que aconteceu dentro dos limites da obra que Deus nos confiou, que inclui nosso trabalho com vocês.

[[v47-10-14]]

^<<v47-10-14,14>>^ Quando afirmamos ter autoridade sobre vocês, não ultrapassamos esses limites, pois fomos os primeiros a chegar até vocês com as boas-novas de Cristo.

[[v47-10-15]]

^<<v47-10-15,15>>^ Também não nos orgulhamos do trabalho realizado por outros nem assumimos o crédito por ele. Pelo contrário, esperamos que sua fé cresça de tal modo que se ampliem os limites de nosso trabalho entre vocês.

[[v47-10-16]]

^<<v47-10-16,16>>^ Então poderemos anunciar as boas-novas em outros lugares, para além de sua região, onde ninguém esteja trabalhando. Assim, ninguém pensará que estamos nos orgulhando do trabalho feito em território de outros.

[[v47-10-17]]

^<<v47-10-17,17>>^ Como dizem as Escrituras: "Quem quiser orgulhar-se, orgulhe-se somente no Senhor".

[[v47-10-18]]

^<<v47-10-18,18>>^ Quando alguém elogia a si mesmo, esse elogio não tem valor algum. O importante mesmo é ser aprovado pelo Senhor.

'''

xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[Próximo Capítulo &#62;]