include::./index.adoc[]

[[v47-9-0]]
=== 2 Coríntios, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v47-9-1]]

^<<v47-9-1,1>>^ Na verdade, quanto a esse serviço ao povo santo, não preciso lhes escrever.

[[v47-9-2]]

^<<v47-9-2,2>>^ Sei quanto estão ansiosos para ajudar e expressei às igrejas da Macedônia meu orgulho de que vocês, na Acaia, estão prontos para enviar uma oferta desde o ano passado. De fato, foi sua dedicação que incentivou muitos a também contribuir.

[[v47-9-3]]

^<<v47-9-3,3>>^ Ainda assim, envio esses irmãos para me certificar de que vocês estão preparados, como tenho dito a eles. Não quero elogiar vocês sem razão.

[[v47-9-4]]

^<<v47-9-4,4>>^ Que vexame seria para nós, e ainda mais para vocês, se alguns macedônios chegassem comigo e descobrissem que vocês não estão preparados, depois de tudo que eu disse a eles!

[[v47-9-5]]

^<<v47-9-5,5>>^ Portanto, considerei apropriado enviar esses irmãos antes de mim. Eles cuidarão para que a oferta que vocês prometeram esteja pronta. Que seja, porém, uma oferta voluntária, e não entregue de má vontade.

[[v47-9-6]]

^<<v47-9-6,6>>^ Lembrem-se: quem lança apenas algumas sementes obtém uma colheita pequena, mas quem semeia com fartura obtém uma colheita farta.

[[v47-9-7]]

^<<v47-9-7,7>>^ Cada um deve decidir em seu coração quanto dar. Não contribuam com relutância ou por obrigação. "Pois Deus ama quem dá com alegria."

[[v47-9-8]]

^<<v47-9-8,8>>^ Deus é capaz de lhes conceder todo tipo de bênçãos, para que, em todo tempo, vocês tenham tudo de que precisam, e muito mais ainda, para repartir com outros.

[[v47-9-9]]

^<<v47-9-9,9>>^ Como dizem as Escrituras: "Compartilha generosamente com os necessitados; seus atos de justiça serão lembrados para sempre".

[[v47-9-10]]

^<<v47-9-10,10>>^ Pois é Deus quem supre a semente para o que semeia e depois o pão para seu alimento. Da mesma forma, ele proverá e multiplicará sua semente e produzirá por meio de vocês muitos frutos de justiça.

[[v47-9-11]]

^<<v47-9-11,11>>^ Em tudo vocês serão enriquecidos a fim de que possam ser sempre generosos. E, quando levarmos sua oferta para aqueles que precisam dela, eles darão graças a Deus.

[[v47-9-12]]

^<<v47-9-12,12>>^ Logo, duas coisas boas resultarão desse ministério de auxílio: as necessidades do povo santo serão supridas, e eles expressarão com alegria sua gratidão a Deus.

[[v47-9-13]]

^<<v47-9-13,13>>^ Como resultado do serviço de vocês, eles darão glória a Deus. Pois sua generosidade com eles e com todos os que creem mostrará que vocês são obedientes às boas-novas de Cristo.

[[v47-9-14]]

^<<v47-9-14,14>>^ E eles orarão por vocês com profundo afeto, por causa da graça transbordante que Deus concedeu a vocês.

[[v47-9-15]]

^<<v47-9-15,15>>^ Graças a Deus por essa dádiva tão maravilhosa que nem as palavras conseguem expressar!

'''

xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[Próximo Capítulo &#62;]