include::./index.adoc[]

[[v10-13-0]]
=== 2 Samuel, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v10-13-1]]

^<<v10-13-1,1>>^ Absalão, filho de Davi, tinha uma irmã muito bonita chamada Tamar. Amnom, outro filho de Davi, apaixonou-se por ela.

[[v10-13-2]]

^<<v10-13-2,2>>^ Amnom ficou tão obcecado por Tamar que adoeceu. Ela era virgem, e Amnom imaginou que seria impossível possuí-la.

[[v10-13-3]]

^<<v10-13-3,3>>^ Contudo, Amnom tinha um amigo muito astuto, seu primo Jonadabe. Ele era filho de Simeia, irmão de Davi.

[[v10-13-4]]

^<<v10-13-4,4>>^ Certo dia, Jonadabe disse a Amnom: "Qual é o problema? Por que o filho do rei parece tão abatido todos os dias?". Amnom lhe respondeu: "Estou apaixonado por Tamar, irmã de meu irmão Absalão".

[[v10-13-5]]

^<<v10-13-5,5>>^ "Faça o seguinte", disse Jonadabe. "Deite-se e finja que está doente. Quando seu pai o visitar, peça-lhe que deixe Tamar vir e preparar algo para você comer. Peça que ela prepare o alimento aqui mesmo, para que você a veja e ela o sirva."

[[v10-13-6]]

^<<v10-13-6,6>>^ Então Amnom se deitou e fingiu que estava doente. Quando o rei foi vê-lo, Amnom lhe pediu: "Por favor, permita que minha irmã Tamar venha e prepare dois bolos aqui mesmo, para que eu a veja e ela os sirva para mim".

[[v10-13-7]]

^<<v10-13-7,7>>^ Davi concordou e mandou Tamar ir à casa de Amnom preparar algo para ele comer.

[[v10-13-8]]

^<<v10-13-8,8>>^ Quando Tamar chegou à casa de Amnom, foi até o lugar onde ele estava deitado, para que ele pudesse vê-la preparar a massa. Então ela assou os bolos, conforme ele tinha pedido.

[[v10-13-9]]

^<<v10-13-9,9>>^ Contudo, quando ela colocou a bandeja diante de Amnom, ele se recusou a comer. "Saiam todos daqui", disse ele a seus servos. E todos saíram.

[[v10-13-10]]

^<<v10-13-10,10>>^ Então Amnom disse a Tamar: "Agora traga os bolos ao meu quarto e dê-me de comer". Tamar fez conforme ele pediu.

[[v10-13-11]]

^<<v10-13-11,11>>^ Quando, porém, ela lhe ofereceu a comida, ele a agarrou e exigiu: "Venha para a cama comigo, minha irmã!".

[[v10-13-12]]

^<<v10-13-12,12>>^ "Não, meu irmão! Não me violente!", exclamou Tamar. "Isso não se faz em Israel! Não faça essa loucura!

[[v10-13-13]]

^<<v10-13-13,13>>^ Como eu poderia viver com tamanha vergonha? E você cairia em desgraça em Israel! Por favor, fale com o rei, e ele permitirá que você se case comigo!"

[[v10-13-14]]

^<<v10-13-14,14>>^ Mas Amnom não quis ouvi-la e, como era mais forte que ela, violentou-a.

[[v10-13-15]]

^<<v10-13-15,15>>^ Então a paixão de Amnom se transformou em profundo desprezo, e seu desprezo por ela foi mais intenso que a paixão que havia sentido. "Saia daqui!", gritou para ela.

[[v10-13-16]]

^<<v10-13-16,16>>^ "Não, não!", respondeu Tamar. "Mandar-me embora agora seria pior do que o mal que você me fez." Amnom, porém, não quis ouvi-la.

[[v10-13-17]]

^<<v10-13-17,17>>^ Chamou seu servo e ordenou: "Ponha esta mulher para fora daqui e tranque a porta!".

[[v10-13-18]]

^<<v10-13-18,18>>^ O servo a pôs para fora e trancou a porta. Tamar vestia uma túnica longa, como era costume naqueles dias entre as filhas virgens do rei.

[[v10-13-19]]

^<<v10-13-19,19>>^ Então rasgou sua túnica, jogou cinzas sobre a cabeça e, cobrindo o rosto com as mãos, foi embora chorando.

[[v10-13-20]]

^<<v10-13-20,20>>^ Seu irmão Absalão a viu e perguntou: "É verdade que Amnom esteve com você? Bem, minha irmã, é melhor ficar quieta, pois Amnom é seu irmão. Não se aflija com isso". Então Tamar, como uma mulher desolada, foi morar na casa de seu irmão Absalão.

[[v10-13-21]]

^<<v10-13-21,21>>^ Quando o rei Davi soube o que havia acontecido, ficou furioso.

[[v10-13-22]]

^<<v10-13-22,22>>^ E, embora Absalão não tivesse dito nada a Amnom a esse respeito, odiou Amnom profundamente pelo que ele havia feito à sua irmã.

[[v10-13-23]]

^<<v10-13-23,23>>^ Dois anos depois, quando as ovelhas de Absalão estavam sendo tosquiadas em Baal-Hazor, perto de Efraim, Absalão convidou todos os filhos do rei para uma festa.

[[v10-13-24]]

^<<v10-13-24,24>>^ Foi até o rei e disse: "Meus tosquiadores estão trabalhando. Gostaria que o rei e seus servos celebrassem essa ocasião comigo".

[[v10-13-25]]

^<<v10-13-25,25>>^ Mas o rei respondeu: "Não, meu filho. Se todos nós fôssemos, seria um peso para você". Embora Absalão insistisse, o rei se recusou a ir, mas abençoou Absalão.

[[v10-13-26]]

^<<v10-13-26,26>>^ "Está bem", disse Absalão. "Se o senhor não pode vir, permita que meu irmão Amnom vá conosco." "Por que Amnom?", perguntou o rei.

[[v10-13-27]]

^<<v10-13-27,27>>^ Mas Absalão continuou a insistir até que, finalmente, o rei concordou em deixar seus filhos, incluindo Amnom, irem à festa.

[[v10-13-28]]

^<<v10-13-28,28>>^ Absalão disse a seus homens: "Esperem até Amnom estar bêbado; então, quando eu ordenar, matem-no. Não tenham medo. A responsabilidade é minha. Sejam corajosos e valentes!".

[[v10-13-29]]

^<<v10-13-29,29>>^ Assim, quando Absalão deu o sinal, eles mataram Amnom. Os outros filhos do rei montaram em suas mulas e fugiram.

[[v10-13-30]]

^<<v10-13-30,30>>^ Quando ainda estavam a caminho de Jerusalém, a notícia chegou a Davi: "Absalão matou todos os filhos do rei; não restou um sequer com vida!".

[[v10-13-31]]

^<<v10-13-31,31>>^ O rei se levantou, rasgou suas roupas e lançou-se no chão. Seus conselheiros também rasgaram suas roupas.

[[v10-13-32]]

^<<v10-13-32,32>>^ Nesse momento, Jonadabe, filho de Simeia, irmão de Davi, chegou e disse: "Não pense, meu senhor, que todos os filhos do rei foram mortos! Foi apenas Amnom! Absalão tramava isso desde que Amnom violentou sua irmã Tamar.

[[v10-13-33]]

^<<v10-13-33,33>>^ O meu senhor, o rei, não deve acreditar que todos os seus filhos estão mortos! Apenas Amnom morreu".

[[v10-13-34]]

^<<v10-13-34,34>>^ Enquanto isso, Absalão fugiu. Então a sentinela sobre o muro de Jerusalém viu muita gente descendo o monte pela estrada que vinha do oeste.

[[v10-13-35]]

^<<v10-13-35,35>>^ E Jonadabe disse ao rei: "Veja! Lá estão eles! São os filhos do rei voltando, como eu tinha dito".

[[v10-13-36]]

^<<v10-13-36,36>>^ Logo eles chegaram, chorando e soluçando, e o rei e todos os seus servos choraram amargamente com eles.

[[v10-13-37]]

^<<v10-13-37,37>>^ Davi chorou muitos dias por seu filho Amnom. Absalão fugiu para a terra de Talmai, filho de Amiúde, rei de Gesur,

[[v10-13-38]]

^<<v10-13-38,38>>^ onde permaneceu por três anos.

[[v10-13-39]]

^<<v10-13-39,39>>^ E o rei Davi, conformado com a morte de Amnom, abandonou a ideia de perseguir Absalão.

'''

xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[&#60; Capítulo Anterior] | <<v10-13-0,Topo>> | xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[Próximo Capítulo &#62;]