include::./index.adoc[]

[[v10-15-0]]
=== 2 Samuel, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v10-15-1]]

^<<v10-15-1,1>>^ Algum tempo depois, Absalão providenciou para si uma carruagem com cavalos e contratou cinquenta guardas para servirem como sua guarda de honra.

[[v10-15-2]]

^<<v10-15-2,2>>^ Todas as manhãs, ele se levantava cedo e ia até o portão da cidade. Quando alguém trazia uma causa para ser julgada pelo rei, Absalão perguntava de que cidade a pessoa era, e ela lhe respondia a qual tribo de Israel pertencia.

[[v10-15-3]]

^<<v10-15-3,3>>^ Então Absalão dizia: "Sua causa é justa e legítima. É pena que o rei não tenha ninguém para ouvi-la".

[[v10-15-4]]

^<<v10-15-4,4>>^ E dizia ainda: "Quem me dera ser juiz. Então todos me apresentariam suas questões legais, e eu lhes faria justiça!".

[[v10-15-5]]

^<<v10-15-5,5>>^ Quando alguém ia se prostrar diante dele, Absalão não o permitia. Ao contrário, tomava-o pela mão e o beijava.

[[v10-15-6]]

^<<v10-15-6,6>>^ Fazia isso com todos que vinham ao rei pedir justiça e, desse modo, ia conquistando o coração de todos em Israel.

[[v10-15-7]]

^<<v10-15-7,7>>^ Passados quatro anos, Absalão disse ao rei: "Deixe-me ir a Hebrom para cumprir o voto que fiz ao SENHOR.

[[v10-15-8]]

^<<v10-15-8,8>>^ Enquanto eu estava em Gesur, na Síria, prometi oferecer sacrifícios ao SENHOR em Hebrom caso ele me trouxesse de volta a Jerusalém".

[[v10-15-9]]

^<<v10-15-9,9>>^ "Está bem", disse o rei. "Vá e cumpra seu voto." Então Absalão foi a Hebrom.

[[v10-15-10]]

^<<v10-15-10,10>>^ Enquanto estava lá, porém, enviou em segredo mensageiros para todas as tribos de Israel. Eles diziam às pessoas: "Assim que ouvirem as trombetas, digam: ‘Absalão foi coroado rei em Hebrom!’".

[[v10-15-11]]

^<<v10-15-11,11>>^ Absalão levou consigo duzentos homens de Jerusalém como seus convidados, mas eles não faziam ideia de suas intenções.

[[v10-15-12]]

^<<v10-15-12,12>>^ Enquanto Absalão oferecia os sacrifícios, mandou chamar Aitofel, um dos conselheiros de Davi que vivia na cidade de Gilo. Em pouco tempo, muitos outros se uniram a Absalão, e a conspiração ganhou força.

[[v10-15-13]]

^<<v10-15-13,13>>^ Logo, um mensageiro chegou a Jerusalém para informar Davi: "Todo o Israel se uniu a Absalão!".

[[v10-15-14]]

^<<v10-15-14,14>>^ "Então devemos fugir de imediato, ou será tarde demais!", disse Davi a seus conselheiros. "Rápido! Se sairmos de Jerusalém antes que Absalão chegue, escaparemos e impediremos que ele mate todos os moradores da cidade."

[[v10-15-15]]

^<<v10-15-15,15>>^ "O senhor tem o nosso apoio", responderam seus conselheiros. "Faça o que lhe parecer melhor."

[[v10-15-16]]

^<<v10-15-16,16>>^ Então o rei e toda a sua família partiram de imediato. Ele deixou para trás apenas dez concubinas para cuidarem do palácio.

[[v10-15-17]]

^<<v10-15-17,17>>^ O rei e todos que o acompanhavam foram a pé e pararam na última casa da cidade,

[[v10-15-18]]

^<<v10-15-18,18>>^ a fim de deixar os soldados do rei passarem e tomarem a dianteira. Também iam com Davi sua guarda pessoal e seiscentos homens de Gate.

[[v10-15-19]]

^<<v10-15-19,19>>^ Então o rei se voltou para Itai, comandante dos homens de Gate, e disse: "Por que você está vindo conosco? Volte para o novo rei, pois Israel não é sua pátria; você é um estrangeiro no exílio.

[[v10-15-20]]

^<<v10-15-20,20>>^ Chegou faz pouco tempo, e não seria certo eu obrigá-lo a vir conosco. Nem sei para onde vamos. Volte e leve consigo seus parentes, e que a bondade e a fidelidade o acompanhem!".

[[v10-15-21]]

^<<v10-15-21,21>>^ Itai, porém, disse ao rei: "Tão certo como vive o SENHOR e como vive o rei, eu juro que, não importa o que aconteça, irei aonde for o meu senhor, o rei, seja para viver ou para morrer!".

[[v10-15-22]]

^<<v10-15-22,22>>^ Davi respondeu: "Muito bem, venha conosco". E Itai, todos os seus homens e suas famílias acompanharam Davi.

[[v10-15-23]]

^<<v10-15-23,23>>^ Por onde passavam o rei e os que o seguiam, todo o povo chorava em alta voz. Atravessaram o vale de Cedrom e foram em direção ao deserto.

[[v10-15-24]]

^<<v10-15-24,24>>^ Zadoque e todos os levitas também os acompanharam, carregando a arca da aliança de Deus. Puseram a arca no chão, e Abiatar ofereceu sacrifícios até que todos tivessem saído da cidade.

[[v10-15-25]]

^<<v10-15-25,25>>^ Então Davi ordenou a Zadoque: "Leve a arca de Deus de volta para a cidade. Se for da vontade do SENHOR, ele me trará de volta para ver novamente a arca e o santuário.

[[v10-15-26]]

^<<v10-15-26,26>>^ Mas, se ele não se agradar mais de mim, que faça comigo o que lhe parecer melhor".

[[v10-15-27]]

^<<v10-15-27,27>>^ O rei também disse ao sacerdote Zadoque: "Preste atenção. Você deve voltar à cidade, com seu filho Aimaás e com Jônatas, filho de Abiatar.

[[v10-15-28]]

^<<v10-15-28,28>>^ Farei uma parada em um dos pontos de travessia do Jordão e ficarei ali esperando notícias suas".

[[v10-15-29]]

^<<v10-15-29,29>>^ Então Zadoque e Abiatar levaram a arca de Deus de volta para Jerusalém e ali permaneceram.

[[v10-15-30]]

^<<v10-15-30,30>>^ Davi prosseguiu pelo caminho para o monte das Oliveiras, chorando enquanto andava. Estava com a cabeça coberta e os pés descalços. Os que iam com ele também tinham a cabeça coberta e choravam enquanto subiam ao monte.

[[v10-15-31]]

^<<v10-15-31,31>>^ Quando alguém informou a Davi que Aitofel, seu conselheiro, agora apoiava Absalão, Davi orou: "Ó SENHOR, faze que Aitofel dê conselhos errados a Absalão!".

[[v10-15-32]]

^<<v10-15-32,32>>^ Quando Davi chegou ao alto do monte, onde o povo costumava adorar a Deus, Husai, o arquita, o esperava ali. Husai havia rasgado suas roupas e colocado terra sobre a cabeça.

[[v10-15-33]]

^<<v10-15-33,33>>^ Mas Davi lhe disse: "Se você vier comigo, será apenas um peso.

[[v10-15-34]]

^<<v10-15-34,34>>^ Volte à cidade e diga a Absalão: ‘Agora serei seu conselheiro, ó rei, como no passado fui conselheiro de seu pai’. Assim, você poderá frustrar os conselhos de Aitofel.

[[v10-15-35]]

^<<v10-15-35,35>>^ Os sacerdotes Zadoque e Abiatar estarão lá. Informe-os dos planos feitos no palácio,

[[v10-15-36]]

^<<v10-15-36,36>>^ e eles enviarão seus filhos Aimaás e Jônatas para me contar o que se passa".

[[v10-15-37]]

^<<v10-15-37,37>>^ Assim, Husai, amigo de Davi, voltou para Jerusalém e ali chegou na mesma hora em que Absalão entrava na cidade.

'''

xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[&#60; Capítulo Anterior] | <<v10-15-0,Topo>> | xref:010-2-samuel/010-2-samuel-016.adoc#v10-16-0[Próximo Capítulo &#62;]