include::./index.adoc[]

[[v10-11-0]]
=== 2 Samuel, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v10-11-1]]

^<<v10-11-1,1>>^ No começo do ano, época em que os reis costumavam ir à guerra, Davi enviou Joabe e as tropas israelitas para lutarem contra os amonitas. Eles destruíram o exército inimigo e cercaram a cidade de Rabá. Mas Davi ficou em Jerusalém.

[[v10-11-2]]

^<<v10-11-2,2>>^ Certa tarde, Davi se levantou da cama depois de seu descanso e foi caminhar pelo terraço do palácio. Enquanto olhava do terraço, reparou numa mulher muito bonita que tomava banho.

[[v10-11-3]]

^<<v10-11-3,3>>^ Davi mandou alguém para descobrir quem era a mulher. Disseram-lhe: "É Bate-Seba, filha de Eliã e esposa de Urias, o hitita".

[[v10-11-4]]

^<<v10-11-4,4>>^ Então Davi enviou mensageiros para que a trouxessem, e teve relações com ela. Bate-Seba havia acabado de completar o ritual de purificação depois da menstruação. E ela voltou para casa.

[[v10-11-5]]

^<<v10-11-5,5>>^ Passado algum tempo, quando Bate-Seba descobriu que estava grávida, enviou um mensageiro a Davi para lhe dizer: "Estou grávida".

[[v10-11-6]]

^<<v10-11-6,6>>^ Então Davi mandou uma mensagem para Joabe: "Envie-me Urias, o hitita", e Joabe o enviou a Davi.

[[v10-11-7]]

^<<v10-11-7,7>>^ Quando Urias chegou, Davi perguntou como estavam Joabe e o exército e como ia a guerra.

[[v10-11-8]]

^<<v10-11-8,8>>^ Então disse a Urias: "Vá para casa e descanse". Depois que Urias deixou o palácio, Davi lhe enviou um presente.

[[v10-11-9]]

^<<v10-11-9,9>>^ Urias, porém, não foi para casa. Passou a noite na entrada do palácio com os guardas do rei.

[[v10-11-10]]

^<<v10-11-10,10>>^ Quando Davi soube que Urias não tinha ido para casa, mandou chamá-lo e perguntou: "O que aconteceu? Depois de ter ficado tanto tempo fora, por que você não foi para casa ontem à noite?".

[[v10-11-11]]

^<<v10-11-11,11>>^ Urias respondeu: "A arca e os exércitos de Israel e de Judá estão em tendas, e Joabe, meu comandante, e seus soldados estão acampados ao ar livre. Como eu poderia ir para casa para beber, comer e dormir com minha mulher? Juro diante do rei que jamais faria uma coisa dessas".

[[v10-11-12]]

^<<v10-11-12,12>>^ Então Davi lhe disse: "Pois bem. Fique aqui hoje, e amanhã poderá retornar". Urias ficou em Jerusalém aquele dia e o dia seguinte.

[[v10-11-13]]

^<<v10-11-13,13>>^ Davi o convidou para jantar e o embriagou. Outra vez, porém, ele dormiu numa esteira, com os guardas do rei, e não foi para sua casa.

[[v10-11-14]]

^<<v10-11-14,14>>^ Na manhã seguinte, Davi escreveu uma carta para Joabe e mandou Urias entregá-la.

[[v10-11-15]]

^<<v10-11-15,15>>^ A carta continha a seguinte instrução: "Coloque Urias na linha de frente, onde o combate estiver mais intenso. Depois, recue para que ele seja morto".

[[v10-11-16]]

^<<v10-11-16,16>>^ Então Joabe colocou Urias numa posição próxima do muro da cidade, onde sabia que estavam os principais guerreiros do inimigo.

[[v10-11-17]]

^<<v10-11-17,17>>^ Quando os soldados inimigos saíram da cidade para lutar, Urias, o hitita, foi morto junto com muitos outros soldados israelitas.

[[v10-11-18]]

^<<v10-11-18,18>>^ Joabe enviou a Davi um relatório da batalha.

[[v10-11-19]]

^<<v10-11-19,19>>^ Disse a seu mensageiro: "Conte ao rei tudo que aconteceu na batalha.

[[v10-11-20]]

^<<v10-11-20,20>>^ Pode ser que ele fique irado e pergunte: ‘Por que as tropas se aproximaram tanto da cidade? Não sabiam que atirariam contra eles dos muros?

[[v10-11-21]]

^<<v10-11-21,21>>^ Acaso Abimeleque, filho de Gideão, não foi morto em Tebes por uma mulher que atirou uma pedra de moinho do alto da muralha? Por que chegaram tão perto dos muros?’. Então diga-lhe: ‘Seu soldado Urias, o hitita, também foi morto’".

[[v10-11-22]]

^<<v10-11-22,22>>^ O mensageiro foi a Jerusalém e deu um relatório completo a Davi.

[[v10-11-23]]

^<<v10-11-23,23>>^ "O inimigo saiu contra nós em campo aberto", disse o mensageiro. "Quando os perseguíamos de volta até o portão da cidade,

[[v10-11-24]]

^<<v10-11-24,24>>^ os arqueiros no alto do muro atiraram flechas contra nós. Alguns dos homens do rei foram mortos; entre eles estava Urias, o hitita."

[[v10-11-25]]

^<<v10-11-25,25>>^ Davi respondeu: "Diga a Joabe que não desanime. A espada devora este hoje e aquele amanhã. Lutem bravamente e conquistem a cidade!".

[[v10-11-26]]

^<<v10-11-26,26>>^ Quando a esposa de Urias soube que seu marido havia morrido, chorou por ele.

[[v10-11-27]]

^<<v10-11-27,27>>^ Terminado o período de luto, Davi mandou trazê-la para o palácio. Ela se tornou uma de suas esposas e deu à luz um filho. Mas o que Davi fez desagradou o SENHOR.

'''

xref:010-2-samuel/010-2-samuel-010.adoc#v10-10-0[&#60; Capítulo Anterior] | <<v10-11-0,Topo>> | xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[Próximo Capítulo &#62;]