include::./index.adoc[]

[[v10-3-0]]
=== 2 Samuel, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v10-3-1]]

^<<v10-3-1,1>>^ Assim começou uma longa guerra entre a família de Saul e a família de Davi. Com o tempo, Davi se fortaleceu cada vez mais, e a família de Saul foi se enfraquecendo.

[[v10-3-2]]

^<<v10-3-2,2>>^ Estes são os filhos de Davi que nasceram em Hebrom: O mais velho era Amnom, filho de Ainoã, de Jezreel.

[[v10-3-3]]

^<<v10-3-3,3>>^ O segundo era Daniel, filho de Abigail, a viúva de Nabal, do Carmelo. O terceiro era Absalão, filho de Maaca, filha de Talmai, rei de Gesur.

[[v10-3-4]]

^<<v10-3-4,4>>^ O quarto era Adonias, filho de Hagite. O quinto era Sefatias, filho de Abital.

[[v10-3-5]]

^<<v10-3-5,5>>^ O sexto era Itreão, filho de Eglá, esposa de Davi. Todos esses filhos de Davi nasceram em Hebrom.

[[v10-3-6]]

^<<v10-3-6,6>>^ Enquanto continuava a guerra entre as famílias de Saul e de Davi, Abner se tornou um líder cada vez mais influente entre a família de Saul.

[[v10-3-7]]

^<<v10-3-7,7>>^ Um dia, Isbosete, filho de Saul, acusou Abner de ter relações com uma das concubinas de Saul, uma mulher chamada Rispa, filha de Aiá.

[[v10-3-8]]

^<<v10-3-8,8>>^ Abner ficou furioso com as palavras de Isbosete. "Por acaso sou um cão de Judá para ser tratado dessa maneira?", gritou ele. "Depois de tudo que fiz por seu pai, Saul, e pela família e os amigos dele ao não entregar você a Davi, minha recompensa é ser acusado por causa dessa mulher?

[[v10-3-9]]

^<<v10-3-9,9>>^ Que Deus me castigue severamente se eu não fizer por Davi tudo que o SENHOR prometeu a ele!

[[v10-3-10]]

^<<v10-3-10,10>>^ Tomarei o reino da família de Saul e o entregarei a Davi. Estabelecerei o trono de Davi tanto sobre Israel como sobre Judá, desde Dã, ao norte, até Berseba, ao sul!"

[[v10-3-11]]

^<<v10-3-11,11>>^ Isbosete não se atreveu a dizer nem mais uma palavra, pois teve medo do que Abner poderia fazer.

[[v10-3-12]]

^<<v10-3-12,12>>^ Então Abner enviou mensageiros para dizer a Davi: "Afinal, a quem pertence esta terra? Faça um acordo comigo, e eu o ajudarei a conseguir o apoio de todo o Israel".

[[v10-3-13]]

^<<v10-3-13,13>>^ "Está bem", respondeu Davi. "Mas só farei acordo com você se, quando vier para cá, trouxer de volta minha esposa Mical, filha de Saul."

[[v10-3-14]]

^<<v10-3-14,14>>^ Davi enviou a seguinte mensagem a Isbosete, filho de Saul: "Devolva minha esposa Mical, pois eu conquistei o direito de me casar com ela com os prepúcios de cem filisteus".

[[v10-3-15]]

^<<v10-3-15,15>>^ Então Isbosete mandou tirar Mical de seu marido, Palti, filho de Laís.

[[v10-3-16]]

^<<v10-3-16,16>>^ Palti a seguiu até Baurim, chorando ao longo de todo o caminho, até que Abner lhe disse: "Volte para casa!", e ele voltou.

[[v10-3-17]]

^<<v10-3-17,17>>^ Abner reuniu as autoridades de Israel e lhes disse: "Faz algum tempo que vocês querem declarar Davi seu rei.

[[v10-3-18]]

^<<v10-3-18,18>>^ Chegou a hora de agir! Pois o SENHOR disse: ‘Escolhi meu servo Davi para livrar meu povo, Israel, das mãos dos filisteus e de todos os seus inimigos’".

[[v10-3-19]]

^<<v10-3-19,19>>^ Abner também falou com os homens de Benjamim. Depois, foi a Hebrom para dizer a Davi que todo o povo de Israel e de Benjamim tinha concordado em apoiá-lo.

[[v10-3-20]]

^<<v10-3-20,20>>^ Quando Abner, acompanhado de vinte homens, chegou a Hebrom, Davi os recebeu com um grande banquete.

[[v10-3-21]]

^<<v10-3-21,21>>^ Então Abner disse a Davi: "Deixe que eu vá e convoque uma reunião de todo o Israel para apoiar meu senhor, o rei. Farão uma aliança com o senhor para que reine sobre eles, e o senhor governará sobre tudo que seu coração desejar". Davi se despediu dele, e Abner partiu em paz.

[[v10-3-22]]

^<<v10-3-22,22>>^ Contudo, logo depois que Davi despediu Abner em paz, Joabe e alguns dos soldados de Davi retornaram de um ataque, trazendo muitos despojos.

[[v10-3-23]]

^<<v10-3-23,23>>^ Quando Joabe chegou, foi informado de que Abner, filho de Ner, tinha acabado de visitar o rei, que o havia despedido em paz.

[[v10-3-24]]

^<<v10-3-24,24>>^ Joabe foi até o rei e perguntou: "O que foi que o senhor fez? Por que deixou Abner escapar?

[[v10-3-25]]

^<<v10-3-25,25>>^ O senhor conhece muito bem Abner, filho de Ner! Sabe que ele veio espioná-lo e descobrir tudo que o senhor anda fazendo!".

[[v10-3-26]]

^<<v10-3-26,26>>^ Então Joabe saiu da presença de Davi e enviou mensageiros para alcançar Abner. Eles o encontraram perto do poço de Sirá e o trouxeram de volta, sem que Davi soubesse.

[[v10-3-27]]

^<<v10-3-27,27>>^ Quando Abner chegou a Hebrom, Joabe o chamou para um lado, junto ao portão da cidade, como se fosse falar com ele em particular. Então, apunhalou-o no estômago e o matou para vingar a morte de Asael, seu irmão.

[[v10-3-28]]

^<<v10-3-28,28>>^ Quando Davi soube o que havia acontecido, declarou: "Juro pelo SENHOR que eu e meu reino somos para sempre inocentes desse crime contra Abner, filho de Ner.

[[v10-3-29]]

^<<v10-3-29,29>>^ Que essa culpa permaneça sobre Joabe e sua família! Que em todas as gerações da família de Joabe nunca falte um homem que tenha fluxo ou lepra, que use muletas, que morra pela espada, ou que tenha de mendigar o alimento!".

[[v10-3-30]]

^<<v10-3-30,30>>^ Assim, Joabe e seu irmão Abisai assassinaram Abner, pois ele havia matado Asael, irmão deles, na batalha em Gibeom.

[[v10-3-31]]

^<<v10-3-31,31>>^ Então Davi disse a Joabe e a todos que estavam com ele: "Rasguem suas roupas e vistam pano de saco. Lamentem a morte de Abner", e o próprio rei seguiu o cortejo fúnebre.

[[v10-3-32]]

^<<v10-3-32,32>>^ Sepultaram Abner em Hebrom, e o rei chorou em alta voz junto ao túmulo, e todo o povo lamentou com ele.

[[v10-3-33]]

^<<v10-3-33,33>>^ Então o rei entoou esta canção fúnebre: "Acaso Abner devia morrer como um vilão?

[[v10-3-34]]

^<<v10-3-34,34>>^ Suas mãos não estavam atadas, nem seus pés acorrentados. Não, você foi assassinado, vítima de uma trama perversa". Todo o povo lamentou uma vez mais por Abner.

[[v10-3-35]]

^<<v10-3-35,35>>^ Davi tinha se recusado a comer no dia do funeral, e todos insistiram para que ele se alimentasse. Mas ele havia feito um voto: "Que Deus me castigue severamente se eu comer alguma coisa antes do pôr do sol".

[[v10-3-36]]

^<<v10-3-36,36>>^ Seu voto agradou muito o povo. De fato, aprovavam tudo que o rei fazia.

[[v10-3-37]]

^<<v10-3-37,37>>^ Assim, todos em Judá e em Israel entenderam que Davi não era responsável pelo assassinato de Abner, filho de Ner.

[[v10-3-38]]

^<<v10-3-38,38>>^ Então o rei disse a seus oficiais: "Não percebem que um grande comandante caiu hoje em Israel?

[[v10-3-39]]

^<<v10-3-39,39>>^ E, embora eu seja o rei ungido, esses dois filhos de Zeruia, Joabe e Abisai, são fortes demais para que eu os controle. Que o SENHOR retribua a esses homens maus por sua maldade".

'''

xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[&#60; Capítulo Anterior] | <<v10-3-0,Topo>> | xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[Próximo Capítulo &#62;]