include::./index.adoc[]

[[v10-24-0]]
=== 2 Samuel, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v10-24-1]]

^<<v10-24-1,1>>^ Mais uma vez, a ira do SENHOR ardeu contra Israel e incitou Davi contra eles. "Vá e conte o povo de Israel e de Judá", disse-lhe o SENHOR.

[[v10-24-2]]

^<<v10-24-2,2>>^ Então o rei disse a Joabe, comandante de seu exército: "Faça uma contagem de todas as tribos de Israel, desde Dã, ao norte, até Berseba, ao sul, para que eu saiba o número exato do povo".

[[v10-24-3]]

^<<v10-24-3,3>>^ Joabe, porém, respondeu ao rei: "Que o SENHOR, seu Deus, dê ao rei vida longa para ver a população cem vezes mais numerosa do que é hoje! Mas por que meu senhor, o rei, deseja fazer essa contagem?".

[[v10-24-4]]

^<<v10-24-4,4>>^ Apesar da objeção de Joabe, o rei insistiu que fizessem o censo. Então Joabe e os comandantes do exército saíram para contar o povo de Israel.

[[v10-24-5]]

^<<v10-24-5,5>>^ Primeiro atravessaram o Jordão e acamparam em Aroer, ao sul da cidade, no meio do vale de Gade. Em seguida, foram a Jazer,

[[v10-24-6]]

^<<v10-24-6,6>>^ depois, a Gileade, na terra de Tatim-Hodsi e a Dã-Jaã, e deram a volta para Sidom.

[[v10-24-7]]

^<<v10-24-7,7>>^ Então chegaram à fortaleza de Tiro, e a todas as cidades dos heveus e dos cananeus. Por fim, dirigiram-se ao sul de Judá, até Berseba.

[[v10-24-8]]

^<<v10-24-8,8>>^ Tendo percorrido toda a terra em nove meses e vinte dias, voltaram para Jerusalém.

[[v10-24-9]]

^<<v10-24-9,9>>^ Joabe informou ao rei o total da contagem. Havia em Israel oitocentos mil homens aptos para irem à guerra que sabiam manejar a espada e, em Judá, havia quinhentos mil.

[[v10-24-10]]

^<<v10-24-10,10>>^ Depois que Davi fez o censo, sua consciência começou a incomodá-lo. Ele disse ao SENHOR: "Pequei grandemente ao fazer essa contagem. Perdoe meu pecado, ó SENHOR, pois cometi uma insensatez".

[[v10-24-11]]

^<<v10-24-11,11>>^ Na manhã seguinte, a palavra do SENHOR veio ao profeta Gade, vidente de Davi. Esta foi a mensagem:

[[v10-24-12]]

^<<v10-24-12,12>>^ "Vá e diga a Davi que assim diz o SENHOR: ‘Darei a você três opções. Escolha um destes castigos, e eu o aplicarei a você’".

[[v10-24-13]]

^<<v10-24-13,13>>^ Gade foi a Davi e lhe perguntou: "Qual destas opções você escolhe: três anos de fome por toda a terra, três meses fugindo de seus inimigos, ou três dias de praga intensa por toda a terra? Pense bem e decida o que devo responder àquele que me enviou".

[[v10-24-14]]

^<<v10-24-14,14>>^ "Não tenho para onde correr nesta situação!", respondeu Davi a Gade. "Mas é melhor cair nas mãos do SENHOR, pois sua misericórdia é grande. Que eu não caia nas mãos de homens."

[[v10-24-15]]

^<<v10-24-15,15>>^ Então, naquela manhã, o SENHOR enviou sobre Israel uma praga que durou o tempo determinado. Morreram setenta mil pessoas em todo o Israel, desde Dã, ao norte, até Berseba, ao sul.

[[v10-24-16]]

^<<v10-24-16,16>>^ Mas, quando o anjo estava pronto para destruir Jerusalém, o SENHOR teve compaixão e disse ao anjo da morte: "Pare! Já basta!". Naquele momento, o anjo do SENHOR estava perto da eira de Araúna, o jebuseu.

[[v10-24-17]]

^<<v10-24-17,17>>^ Quando Davi viu o anjo, disse ao SENHOR: "Fui eu que pequei e fiz o que era mau! O povo é inocente. O que fizeram? Que tua ira caia sobre mim e minha família".

[[v10-24-18]]

^<<v10-24-18,18>>^ Naquele dia, Gade foi a Davi e disse: "Vá e construa um altar para o SENHOR na eira de Araúna, o jebuseu".

[[v10-24-19]]

^<<v10-24-19,19>>^ Então Davi subiu até lá para cumprir a ordem do SENHOR.

[[v10-24-20]]

^<<v10-24-20,20>>^ Quando Araúna viu o rei e seus servos se aproximando, saiu e curvou-se diante do rei com o rosto no chão.

[[v10-24-21]]

^<<v10-24-21,21>>^ "Por que meu senhor, o rei, veio aqui?", perguntou Araúna. Davi respondeu: "Vim comprar sua eira e construir nela um altar para o SENHOR, a fim de que ele faça cessar a praga".

[[v10-24-22]]

^<<v10-24-22,22>>^ "Pode ficar com a eira, meu senhor, o rei", disse Araúna. "Use-a como lhe parecer melhor. Aqui estão os bois para o holocausto, e o senhor pode usar as tábuas de trilhar e as cangas dos bois como lenha para o fogo do altar.

[[v10-24-23]]

^<<v10-24-23,23>>^ Eu lhe darei tudo, ó rei. E que o SENHOR, seu Deus, aceite seu sacrifício."

[[v10-24-24]]

^<<v10-24-24,24>>^ O rei, porém, respondeu a Araúna: "Não! Faço questão de pagar por tudo. Não apresentarei ao SENHOR, meu Deus, holocaustos que nada me custaram". Então Davi pagou cinquenta peças de prata pela eira e pelos bois.

[[v10-24-25]]

^<<v10-24-25,25>>^ Davi construiu ali um altar ao SENHOR e ofereceu holocaustos e ofertas de paz. O SENHOR respondeu à sua oração em favor da terra, e a praga sobre Israel cessou.

'''

xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[&#60; Capítulo Anterior] | <<v10-24-0,Topo>> | xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[Próximo Capítulo &#62;]