include::./index.adoc[]

[[v10-18-0]]
=== 2 Samuel, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v10-18-1]]

^<<v10-18-1,1>>^ Davi passou em revista os soldados que estavam com ele e nomeou generais e capitães para liderá-los.

[[v10-18-2]]

^<<v10-18-2,2>>^ Em seguida, enviou-os em três grupos: um sob o comando de Joabe; outro sob o comando de Abisai, irmão de Joabe, filho de Zeruia; e o outro sob o comando de Itai, de Gate. O rei disse a seus soldados: "Também vou com vocês".

[[v10-18-3]]

^<<v10-18-3,3>>^ Os homens, porém, se opuseram. "O senhor não deve ir", disseram. "Se tivermos de recuar ou fugir, ou mesmo se metade de nós morrer, para eles não fará diferença. O senhor vale por dez mil de nós; por isso, é melhor que fique na cidade e nos envie ajuda, se for necessário."

[[v10-18-4]]

^<<v10-18-4,4>>^ "Farei o que acharem melhor", disse o rei. Assim, ficou junto ao portão da cidade, enquanto os soldados saíam marchando em grupos de cem e de mil.

[[v10-18-5]]

^<<v10-18-5,5>>^ O rei deu a seguinte ordem a Joabe, Abisai e Itai: "Por minha causa, tratem o jovem Absalão com bondade". Todas as tropas ouviram o rei dar essa ordem a seus comandantes.

[[v10-18-6]]

^<<v10-18-6,6>>^ Então saíram para o campo, e a batalha começou no bosque de Efraim.

[[v10-18-7]]

^<<v10-18-7,7>>^ Os soldados israelitas foram derrotados pelos homens de Davi. Houve grande matança naquele dia, e vinte mil homens perderam a vida.

[[v10-18-8]]

^<<v10-18-8,8>>^ A batalha se espalhou por toda a região, e morreram mais homens no bosque do que os que foram mortos pela espada.

[[v10-18-9]]

^<<v10-18-9,9>>^ Durante a batalha, Absalão deparou com alguns homens de Davi. Tentou fugir montado numa mula, mas, ao passar debaixo dos galhos espessos de uma grande árvore, ficou enroscado neles pela cabeça. A mula continuou a correr e o deixou ali, pendurado na árvore.

[[v10-18-10]]

^<<v10-18-10,10>>^ Um dos soldados de Davi presenciou a cena e disse a Joabe: "Vi Absalão pendurado numa árvore".

[[v10-18-11]]

^<<v10-18-11,11>>^ "Você o viu?", perguntou Joabe. "E por que não o matou ali mesmo? Eu o teria recompensado com dez peças de prata e um cinturão de guerreiro!"

[[v10-18-12]]

^<<v10-18-12,12>>^ Mas o soldado respondeu a Joabe: "Eu não mataria o filho do rei nem por mil peças de prata! Todos nós ouvimos o rei dizer ao senhor, a Abisai e a Itai: ‘Por minha causa, poupem o jovem Absalão’.

[[v10-18-13]]

^<<v10-18-13,13>>^ E, se eu tivesse traído o rei e matado seu filho, certamente ele ficaria sabendo, e o senhor seria o primeiro a ficar contra mim".

[[v10-18-14]]

^<<v10-18-14,14>>^ "Não vou perder mais tempo discutindo com você!", disse Joabe. Então pegou três dardos e atravessou com eles o peito de Absalão quando ele ainda estava vivo, pendurado na árvore.

[[v10-18-15]]

^<<v10-18-15,15>>^ Em seguida, dez jovens escudeiros de Joabe cercaram Absalão e o mataram.

[[v10-18-16]]

^<<v10-18-16,16>>^ Então Joabe tocou a trombeta, e seus homens pararam de perseguir o exército de Israel.

[[v10-18-17]]

^<<v10-18-17,17>>^ Atiraram o corpo de Absalão numa cova profunda no bosque e sobre ela colocaram um monte de pedras. E todos os israelitas fugiram para suas casas.

[[v10-18-18]]

^<<v10-18-18,18>>^ Quando ainda estava vivo, Absalão havia construído para si um monumento no vale do Rei, pois disse: "Não tenho filho para dar continuidade a meu nome". Chamou-o de Monumento de Absalão, como é conhecido até hoje.

[[v10-18-19]]

^<<v10-18-19,19>>^ Então Aimaás, filho de Zadoque, disse: "Deixe-me ir correndo dar ao rei a boa notícia de que o SENHOR o livrou de seus inimigos!".

[[v10-18-20]]

^<<v10-18-20,20>>^ "Não", disse Joabe. "Não será uma boa notícia para o rei saber que o filho dele morreu. Você pode servir de mensageiro em outra ocasião, mas não hoje."

[[v10-18-21]]

^<<v10-18-21,21>>^ Então Joabe disse a um etíope: "Vá e conte ao rei o que você viu". O homem se curvou diante de Joabe e partiu correndo.

[[v10-18-22]]

^<<v10-18-22,22>>^ Contudo, Aimaás, filho de Zadoque, insistiu com Joabe: "Não importa o que aconteça, deixe-me ir também". "Por que você quer ir, meu filho?", disse Joabe. "Não haverá recompensa alguma pela notícia."

[[v10-18-23]]

^<<v10-18-23,23>>^ "Eu sei, mas deixe-me ir mesmo assim", implorou. Por fim, Joabe disse: "Está bem, pode ir". Então Aimaás pegou o caminho mais fácil, pela planície, e correu até Maanaim à frente do etíope.

[[v10-18-24]]

^<<v10-18-24,24>>^ Enquanto Davi estava entre os portões interno e externo da cidade, o guarda subiu até o terraço sobre a porta, junto ao muro. Ao olhar dali, viu um homem correndo na direção deles.

[[v10-18-25]]

^<<v10-18-25,25>>^ Gritou para avisar Davi, e o rei respondeu: "Se está sozinho, traz boas notícias". Quando o mensageiro se aproximou,

[[v10-18-26]]

^<<v10-18-26,26>>^ o guarda viu outro homem correndo na direção deles e avisou: "Outro homem se aproxima!". E disse o rei: "Também traz boas notícias".

[[v10-18-27]]

^<<v10-18-27,27>>^ "O primeiro homem corre como Aimaás, filho de Zadoque", disse o guarda. "Ele é um homem bom e traz boas notícias", respondeu o rei.

[[v10-18-28]]

^<<v10-18-28,28>>^ Então Aimaás gritou para o rei: "Tudo está bem!". Curvou-se diante do rei com o rosto no chão e disse: "Louvado seja o SENHOR, seu Deus, que entregou os rebeldes que ousaram se levantar contra o meu senhor, o rei!".

[[v10-18-29]]

^<<v10-18-29,29>>^ "E quanto a Absalão?", perguntou o rei. "Ele está bem?" Aimaás respondeu: "Quando Joabe me enviou, havia grande confusão, mas não sei o que aconteceu".

[[v10-18-30]]

^<<v10-18-30,30>>^ "Espere aqui", disse o rei. E Aimaás ficou esperando ao lado.

[[v10-18-31]]

^<<v10-18-31,31>>^ Então chegou o etíope e disse: "Tenho boas notícias para o meu senhor, o rei. Hoje o SENHOR o livrou de todos que se rebelaram contra o rei".

[[v10-18-32]]

^<<v10-18-32,32>>^ "E quanto ao jovem Absalão?", perguntou o rei. "Ele está bem?" O etíope respondeu: "Que todos os inimigos do meu senhor, o rei, e todos os que se levantam para lhe fazer mal tenham o mesmo destino daquele jovem!".

[[v10-18-33]]

^<<v10-18-33,33>>^ O rei ficou muito abalado. Foi para o quarto que ficava sobre o portão da cidade e começou a chorar. Andando de um lado para o outro, clamava: "Ah, meu filho Absalão! Meu filho, meu filho Absalão! Quem me dera eu tivesse morrido em seu lugar! Ah, Absalão, meu filho, meu filho!".

'''

xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[&#60; Capítulo Anterior] | <<v10-18-0,Topo>> | xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[Próximo Capítulo &#62;]