include::./index.adoc[]

[[v10-5-0]]
=== 2 Samuel, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v10-5-1]]

^<<v10-5-1,1>>^ Então todas as tribos de Israel vieram a Hebrom para encontrar-se com Davi. "Somos do mesmo povo e raça", disseram.

[[v10-5-2]]

^<<v10-5-2,2>>^ "No passado, quando Saul era nosso rei, era você que liderava o exército de Israel. E o SENHOR lhe disse: ‘Você será o pastor do meu povo, Israel. Será o líder de Israel’."

[[v10-5-3]]

^<<v10-5-3,3>>^ Então, ali em Hebrom, o rei Davi fez um acordo diante do SENHOR com todas as autoridades de Israel, e elas o ungiram rei de Israel.

[[v10-5-4]]

^<<v10-5-4,4>>^ Davi tinha 30 anos quando começou a reinar e, ao todo, reinou por quarenta anos.

[[v10-5-5]]

^<<v10-5-5,5>>^ Havia reinado sobre Judá sete anos e seis meses e, em Jerusalém, reinou sobre todo o Israel e Judá por 33 anos.

[[v10-5-6]]

^<<v10-5-6,6>>^ Então o rei partiu com seus soldados para Jerusalém, a fim de lutar contra os jebuseus, que viviam naquele lugar. Os jebuseus zombavam de Davi: "Você jamais entrará aqui! Até os cegos e aleijados são capazes de impedi-lo!". Diziam isso porque imaginavam estar seguros,

[[v10-5-7]]

^<<v10-5-7,7>>^ mas Davi tomou a fortaleza de Sião, que hoje é chamada de Cidade de Davi.

[[v10-5-8]]

^<<v10-5-8,8>>^ No dia do ataque, Davi disse a seus soldados: "Odeio esses jebuseus ‘cegos’ e ‘aleijados’. Quem os atacar deve entrar na cidade pelo túnel de água". Essa é a origem do ditado: "Os cegos e os aleijados não entrarão na casa".

[[v10-5-9]]

^<<v10-5-9,9>>^ Então Davi foi morar na fortaleza de Sião e a chamou de Cidade de Davi. Ampliou a cidade, desde o aterro até a parte interna.

[[v10-5-10]]

^<<v10-5-10,10>>^ Davi foi se tornando cada vez mais poderoso, pois o SENHOR, o Deus dos Exércitos, estava com ele.

[[v10-5-11]]

^<<v10-5-11,11>>^ Hirão, rei de Tiro, enviou a Davi mensageiros com madeira de cedro, carpinteiros e pedreiros, que construíram um palácio para Davi.

[[v10-5-12]]

^<<v10-5-12,12>>^ E Davi compreendeu que o SENHOR o havia confirmado como rei sobre Israel e exaltado seu reino por causa de seu povo, Israel.

[[v10-5-13]]

^<<v10-5-13,13>>^ Depois de mudar-se de Hebrom para Jerusalém, Davi tomou mais concubinas e esposas e teve mais filhos e filhas.

[[v10-5-14]]

^<<v10-5-14,14>>^ Estes são os nomes dos filhos de Davi que nasceram em Jerusalém: Samua, Sobabe, Natã, Salomão,

[[v10-5-15]]

^<<v10-5-15,15>>^ Ibar, Elisua, Nefegue, Jafia,

[[v10-5-16]]

^<<v10-5-16,16>>^ Elisama, Eliada e Elifelete.

[[v10-5-17]]

^<<v10-5-17,17>>^ Quando os filisteus souberam que Davi tinha sido ungido rei de Israel, mobilizaram suas tropas para capturá-lo. Davi, porém, foi informado disso e desceu para a fortaleza.

[[v10-5-18]]

^<<v10-5-18,18>>^ Os filisteus chegaram e se espalharam pelo vale de Refaim.

[[v10-5-19]]

^<<v10-5-19,19>>^ Então Davi perguntou ao SENHOR: "Devo sair e lutar contra os filisteus? Tu os entregarás em minhas mãos?". O SENHOR respondeu a Davi: "Sim, vá, pois eu certamente os entregarei em suas mãos".

[[v10-5-20]]

^<<v10-5-20,20>>^ Então Davi foi a Baal-Perazim e ali derrotou os filisteus, e exclamou: "O SENHOR irrompeu no meio de meus inimigos como uma violenta inundação!". Por isso, chamou aquele lugar de Baal-Perazim.

[[v10-5-21]]

^<<v10-5-21,21>>^ Davi e seus homens levaram os ídolos que os filisteus haviam abandonado ali.

[[v10-5-22]]

^<<v10-5-22,22>>^ Pouco tempo depois, os filisteus voltaram a se espalhar pelo vale de Refaim.

[[v10-5-23]]

^<<v10-5-23,23>>^ Mais uma vez, Davi consultou o SENHOR. "Não os ataque pela frente", respondeu o SENHOR. "Em vez disso, dê a volta por trás deles e ataque-os perto dos álamos.

[[v10-5-24]]

^<<v10-5-24,24>>^ Quando ouvir um som como de pés marchando por cima dos álamos, ataque! É o sinal de que o SENHOR vai à sua frente para derrotar o exército filisteu."

[[v10-5-25]]

^<<v10-5-25,25>>^ Davi fez como o SENHOR ordenou e derrotou os filisteus por todo o caminho, desde Gibeom até Gezer.

'''

xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[&#60; Capítulo Anterior] | <<v10-5-0,Topo>> | xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[Próximo Capítulo &#62;]