include::./index.adoc[]

[[v10-6-0]]
=== 2 Samuel, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v10-6-1]]

^<<v10-6-1,1>>^ Davi reuniu novamente todos os melhores guerreiros de Israel, trinta mil ao todo.

[[v10-6-2]]

^<<v10-6-2,2>>^ Partiu com eles para Baalá de Judá a fim de buscar a arca de Deus, junto à qual era invocado o nome do SENHOR dos Exércitos, que está entronizado entre os querubins.

[[v10-6-3]]

^<<v10-6-3,3>>^ Puseram a arca de Deus num carro novo e a levaram da casa de Abinadabe, que ficava num monte. Saindo da casa, Uzá e Aiô, filhos de Abinadabe, a carroça nova

[[v10-6-4]]

^<<v10-6-4,4>>^ que transportava a arca de Deus. Aiô estava à frente da arca.

[[v10-6-5]]

^<<v10-6-5,5>>^ Davi e todo o povo de Israel celebravam diante do SENHOR, entoando cânticos e tocando todo tipo de instrumentos musicais: liras, harpas, tamborins, chocalhos e címbalos.

[[v10-6-6]]

^<<v10-6-6,6>>^ Quando chegaram à eira de Nacom, os bois tropeçaram, e Uzá estendeu a mão e segurou a arca.

[[v10-6-7]]

^<<v10-6-7,7>>^ A ira do SENHOR se acendeu contra Uzá, e Deus o feriu por causa disso. E ele morreu ali mesmo, ao lado da arca de Deus.

[[v10-6-8]]

^<<v10-6-8,8>>^ Davi ficou indignado porque a ira do SENHOR irrompeu contra Uzá e chamou aquele lugar de Perez-Uzá, como é conhecido até hoje.

[[v10-6-9]]

^<<v10-6-9,9>>^ Davi teve medo do SENHOR e perguntou: "Como poderei levar a arca do SENHOR?".

[[v10-6-10]]

^<<v10-6-10,10>>^ Então resolveu não transferir mais a arca do SENHOR para a Cidade de Davi. Em vez disso, levou-a para a casa de Obede-Edom, na cidade de Gate.

[[v10-6-11]]

^<<v10-6-11,11>>^ A arca do SENHOR ficou na casa de Obede-Edom, em Gate, por três meses, e o SENHOR abençoou Obede-Edom e toda a sua família.

[[v10-6-12]]

^<<v10-6-12,12>>^ Disseram ao rei Davi: "O SENHOR tem abençoado a família de Obede-Edom e tudo que ele possui por causa da arca de Deus". Então Davi foi até lá e, com grande festa, levou a arca de Deus da casa de Obede-Edom para a Cidade de Davi.

[[v10-6-13]]

^<<v10-6-13,13>>^ Quando os homens que carregavam a arca do SENHOR davam seis passos, Davi sacrificava um boi e um novilho gordo.

[[v10-6-14]]

^<<v10-6-14,14>>^ Davi usava um colete sacerdotal de linho e dançava diante do SENHOR com todas as suas forças.

[[v10-6-15]]

^<<v10-6-15,15>>^ Assim, Davi e todo o povo de Israel levaram a arca do SENHOR com gritos de alegria e ao som de trombetas.

[[v10-6-16]]

^<<v10-6-16,16>>^ Enquanto a arca do SENHOR entrava na Cidade de Davi, Mical, filha de Saul, olhava pela janela. Quando viu o rei Davi saltando e dançando diante do SENHOR, encheu-se de desprezo por ele.

[[v10-6-17]]

^<<v10-6-17,17>>^ Trouxeram a arca do SENHOR e a colocaram em seu lugar, dentro de uma tenda especial que Davi tinha preparado para ela. E Davi ofereceu ao SENHOR holocaustos e ofertas de paz.

[[v10-6-18]]

^<<v10-6-18,18>>^ Depois que terminou de oferecer os sacrifícios, abençoou o povo em nome do SENHOR dos Exércitos.

[[v10-6-19]]

^<<v10-6-19,19>>^ Para cada homem e mulher israelita na multidão, ele deu um pão, um bolo de tâmaras e um bolo de passas. Então todos voltaram para casa.

[[v10-6-20]]

^<<v10-6-20,20>>^ Quando Davi voltou para casa a fim de abençoar sua família, Mical, filha de Saul, saiu ao encontro dele e disse: "Como o rei de Israel se mostrou digno de honra hoje, exibindo-se sem qualquer vergonha diante das servas, como um homem vulgar!".

[[v10-6-21]]

^<<v10-6-21,21>>^ Davi respondeu a Mical: "Eu dançava diante do SENHOR, que me escolheu em lugar de seu pai e de toda a sua família! Ele me nomeou líder de Israel, o povo do SENHOR, por isso continuarei a celebrar diante do SENHOR.

[[v10-6-22]]

^<<v10-6-22,22>>^ Estou disposto a me tornar ainda mais desprezível e até mesmo a ser humilhado aos meus próprios olhos! Mas as servas que você mencionou certamente me considerarão digno de honra".

[[v10-6-23]]

^<<v10-6-23,23>>^ E Mical, filha de Saul, não teve filhos até o final de sua vida.

'''

xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[&#60; Capítulo Anterior] | <<v10-6-0,Topo>> | xref:010-2-samuel/010-2-samuel-007.adoc#v10-7-0[Próximo Capítulo &#62;]