include::./index.adoc[]

[[v10-10-0]]
=== 2 Samuel, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v10-10-1]]

^<<v10-10-1,1>>^ Algum tempo depois, morreu Naás, rei dos amonitas, e seu filho Hanum subiu ao trono.

[[v10-10-2]]

^<<v10-10-2,2>>^ Davi disse: "Vou demonstrar lealdade a Hanum, assim como seu pai, Naás, sempre foi leal a mim". Então Davi enviou representantes para expressar seu pesar a Hanum pela morte do pai dele. Mas, quando os representantes de Davi chegaram à terra de Amom,

[[v10-10-3]]

^<<v10-10-3,3>>^ os líderes amonitas disseram a Hanum, seu senhor: "O rei acredita mesmo que esses homens estão aqui para honrar seu pai? Não! Davi os enviou com o objetivo de espionar a cidade para vir e conquistá-la!".

[[v10-10-4]]

^<<v10-10-4,4>>^ Então Hanum prendeu os representantes de Davi e raspou metade da barba de cada um, cortou metade de suas roupas até as nádegas e os expulsou de sua terra.

[[v10-10-5]]

^<<v10-10-5,5>>^ Quando Davi soube o que havia acontecido, enviou mensageiros ao encontro dos homens, para que lhes dissessem: "Fiquem em Jericó até que sua barba tenha crescido e voltem em seguida", pois estavam muito envergonhados.

[[v10-10-6]]

^<<v10-10-6,6>>^ Quando os amonitas perceberam quanto haviam enfurecido Davi, contrataram vinte mil soldados de infantaria dos sírios das terras de Bete-Reobe e Zobá, mil homens do rei de Maaca e doze mil da terra de Tobe.

[[v10-10-7]]

^<<v10-10-7,7>>^ Davi foi informado disso e enviou Joabe e todos os seus guerreiros para lutarem contra eles.

[[v10-10-8]]

^<<v10-10-8,8>>^ As tropas amonitas avançaram e formaram sua frente de batalha à entrada da cidade, enquanto os sírios de Zobá e Reobe e os homens de Tobe e Maaca se posicionaram para lutar nos campos abertos.

[[v10-10-9]]

^<<v10-10-9,9>>^ Joabe viu que teria de lutar em duas frentes ao mesmo tempo, por isso escolheu alguns dos melhores guerreiros de Israel e os pôs sob seu comando pessoal para enfrentar os sírios.

[[v10-10-10]]

^<<v10-10-10,10>>^ Deixou o restante do exército sob o comando de seu irmão Abisai, que atacou os amonitas.

[[v10-10-11]]

^<<v10-10-11,11>>^ Joabe disse a seu irmão: "Se os sírios forem fortes demais para mim, venha me ajudar. E, se os amonitas forem fortes demais para você, eu irei ajudá-lo.

[[v10-10-12]]

^<<v10-10-12,12>>^ Coragem! Lutemos bravamente por nosso povo e pelas cidades de nosso Deus. E que seja feita a vontade do SENHOR!".

[[v10-10-13]]

^<<v10-10-13,13>>^ Joabe e suas tropas atacaram, e os sírios começaram a fugir.

[[v10-10-14]]

^<<v10-10-14,14>>^ Quando os amonitas viram que os sírios batiam em retirada, também fugiram de Abisai e recuaram para dentro da cidade. Terminada a batalha, Joabe voltou para Jerusalém.

[[v10-10-15]]

^<<v10-10-15,15>>^ Os sírios viram que não tinham como enfrentar Israel. Assim, ao se reagrupar,

[[v10-10-16]]

^<<v10-10-16,16>>^ receberam o reforço de soldados sírios convocados por Hadadezer do outro lado do rio Eufrates. Essas tropas chegaram a Helã conduzidas por Sobaque, comandante das forças de Hadadezer.

[[v10-10-17]]

^<<v10-10-17,17>>^ Quando Davi foi informado do que estava acontecendo, reuniu todo o Israel, atravessou o Jordão e levou o exército até Helã. Os sírios se posicionaram para a batalha e lutaram contra Davi.

[[v10-10-18]]

^<<v10-10-18,18>>^ Mais uma vez, porém, os sírios fugiram dos israelitas. O exército de Davi matou setecentos homens em carros de guerra e quarenta mil soldados de infantaria, incluindo Sobaque, comandante de seu exército.

[[v10-10-19]]

^<<v10-10-19,19>>^ Quando todos os reis aliados a Hadadezer viram que ele havia sido derrotado pelos israelitas, renderam-se a Israel e se tornaram súditos de Davi. Depois disso, os sírios tiveram medo de voltar a ajudar os amonitas.

'''

xref:010-2-samuel/010-2-samuel-009.adoc#v10-9-0[&#60; Capítulo Anterior] | <<v10-10-0,Topo>> | xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[Próximo Capítulo &#62;]