include::./index.adoc[]

[[v10-21-0]]
=== 2 Samuel, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v10-21-1]]

^<<v10-21-1,1>>^ Durante o reinado de Davi, houve uma terrível fome que durou três anos, e o rei consultou o SENHOR a esse respeito. O SENHOR disse: "A fome veio porque Saul e sua família são culpados de terem matado os gibeonitas".

[[v10-21-2]]

^<<v10-21-2,2>>^ Então o rei mandou chamar os gibeonitas. Eles não faziam parte do povo de Israel, mas eram tudo que restava dos amorreus. Os israelitas tinham jurado que não os matariam, mas Saul, em seu zelo por Israel e Judá, havia tentado exterminá-los.

[[v10-21-3]]

^<<v10-21-3,3>>^ Davi lhes perguntou: "O que posso fazer por vocês? Como posso reparar o mal que lhes foi feito, para que vocês abençoem o povo do SENHOR?".

[[v10-21-4]]

^<<v10-21-4,4>>^ Os gibeonitas responderam: "Prata e ouro não resolverão a questão entre nós e a família de Saul. Também não temos o direito de exigir a vida de ninguém em Israel". "Que farei por vocês, então?", perguntou Davi.

[[v10-21-5]]

^<<v10-21-5,5>>^ Eles responderam: "Saul planejava nos destruir; queria nos impedir de ter um lugar no território de Israel.

[[v10-21-6]]

^<<v10-21-6,6>>^ Portanto, entregue-nos sete dos filhos de Saul, para que os executemos diante do SENHOR em Gibeá, no monte do SENHOR". "Está bem", disse o rei. "Farei o que me pedem."

[[v10-21-7]]

^<<v10-21-7,7>>^ O rei poupou a vida de Mefibosete, filho de Jônatas, filho de Saul, por causa do juramento que Davi e Jônatas haviam feito diante do SENHOR.

[[v10-21-8]]

^<<v10-21-8,8>>^ Contudo, entregou-lhes Armoni e Mefibosete, os dois filhos de Saul com Rispa, filha de Aiá. Também entregou-lhes os cinco filhos de Merabe, filha de Saul, esposa de Adriel, filho de Barzilai, de Meolá.

[[v10-21-9]]

^<<v10-21-9,9>>^ Os homens de Gibeom os executaram no monte, diante do SENHOR. Os sete foram mortos ao mesmo tempo, no início da colheita da cevada.

[[v10-21-10]]

^<<v10-21-10,10>>^ Então Rispa, filha de Aiá, estendeu um pano de saco sobre uma rocha e ficou ali todo o período da colheita. Não deixou que as aves de rapina despedaçassem os corpos deles durante o dia e impediu os animais selvagens de os devorarem durante a noite.

[[v10-21-11]]

^<<v10-21-11,11>>^ Quando Davi soube o que Rispa, concubina de Saul, havia feito,

[[v10-21-12]]

^<<v10-21-12,12>>^ foi até o povo de Jabes-Gileade para reaver os ossos de Saul e de seu filho Jônatas. (Quando os filisteus mataram Saul e Jônatas no monte Gilboa, o povo de Jabes-Gileade tinha roubado os corpos deles da praça de Bete-Seã, onde os filisteus os haviam pendurado.)

[[v10-21-13]]

^<<v10-21-13,13>>^ Davi trouxe os ossos de Saul e de Jônatas, e também os ossos dos homens que os gibeonitas haviam executado.

[[v10-21-14]]

^<<v10-21-14,14>>^ O rei ordenou que os ossos de Saul e de Jônatas fossem enterrados na sepultura de Quis, pai de Saul, na cidade de Zela, na terra de Benjamim. Depois disso, Deus atendeu às orações em favor do povo.

[[v10-21-15]]

^<<v10-21-15,15>>^ Mais uma vez, houve guerra entre os filisteus e Israel. Quando Davi e seus soldados estavam no meio de uma batalha, Davi perdeu as forças e ficou exausto.

[[v10-21-16]]

^<<v10-21-16,16>>^ Isbibenobe era descendente de gigantes, e a ponta de sua lança de bronze pesava cerca de 3,5 quilos. Ele estava armado com uma espada nova e jurou que ia matar Davi.

[[v10-21-17]]

^<<v10-21-17,17>>^ Mas Abisai, filho de Zeruia, veio socorrer Davi e matou o filisteu. Então os homens de Davi exigiram: "O senhor não vai mais sair conosco para lutar! Por que correr o risco de apagar a lâmpada de Israel?".

[[v10-21-18]]

^<<v10-21-18,18>>^ Depois disso, houve outra batalha contra os filisteus, em Gobe. Enquanto lutavam, Sibecai, de Husate, matou Safe, outro descendente de gigantes.

[[v10-21-19]]

^<<v10-21-19,19>>^ Durante uma batalha em Gobe, Elanã, filho de Jair, de Belém, matou o irmão de Golias, de Gate. O cabo de sua lança era da grossura de um eixo de tecelão.

[[v10-21-20]]

^<<v10-21-20,20>>^ Em outra batalha com os filisteus em Gate, havia um homem de grande estatura com seis dedos em cada mão e seis dedos em cada pé, 24 dedos ao todo, que também era descendente de gigantes.

[[v10-21-21]]

^<<v10-21-21,21>>^ Mas, quando ele desafiou os israelitas e zombou deles, foi morto por Jônatas, filho de Simeia, irmão de Davi.

[[v10-21-22]]

^<<v10-21-22,22>>^ Esses quatro filisteus eram descendentes dos gigantes de Gate, mas Davi e seus guerreiros os mataram.

'''

xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[&#60; Capítulo Anterior] | <<v10-21-0,Topo>> | xref:010-2-samuel/010-2-samuel-022.adoc#v10-22-0[Próximo Capítulo &#62;]