include::./index.adoc[]

[[v10-2-0]]
=== 2 Samuel, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v10-2-1]]

^<<v10-2-1,1>>^ Depois disso, Davi perguntou ao SENHOR: "Devo voltar para alguma das cidades de Judá?". "Sim", respondeu o SENHOR. Então Davi perguntou: "Para que cidade devo ir?". "Para Hebrom", disse o SENHOR.

[[v10-2-2]]

^<<v10-2-2,2>>^ Entao Davi partiu com suas duas esposas, Ainoã, de Jezreel, e Abigail, a viúva de Nabal, do Carmelo,

[[v10-2-3]]

^<<v10-2-3,3>>^ e também com os homens que o acompanhavam e suas famílias. Eles se estabeleceram nos povoados vizinhos a Hebrom.

[[v10-2-4]]

^<<v10-2-4,4>>^ Então vieram os homens de Judá e ungiram Davi rei do povo de Judá. Quando Davi soube que os moradores de Jabes-Gileade haviam sepultado Saul,

[[v10-2-5]]

^<<v10-2-5,5>>^ enviou-lhes a seguinte mensagem: "Que o SENHOR os abençoe por terem sido tão fiéis a Saul, seu senhor, e lhe terem dado um sepultamento digno.

[[v10-2-6]]

^<<v10-2-6,6>>^ Que, em troca, o SENHOR seja fiel a vocês e os recompense com sua bondade. E eu também os recompensarei pelo que fizeram.

[[v10-2-7]]

^<<v10-2-7,7>>^ Agora que Saul está morto, peço que continuem a ser fortes e corajosos. E saibam que o povo de Judá me ungiu para ser seu novo rei".

[[v10-2-8]]

^<<v10-2-8,8>>^ Contudo, Abner, filho de Ner, comandante do exército de Saul, já havia levado Isbosete, filho de Saul, para Maanaim.

[[v10-2-9]]

^<<v10-2-9,9>>^ Ali, proclamou Isbosete rei sobre Gileade, Jezreel, Efraim, Benjamim e sobre a terra dos assuritas e todo o restante de Israel.

[[v10-2-10]]

^<<v10-2-10,10>>^ Isbosete, filho de Saul, tinha 40 anos quando começou a reinar sobre Israel, e reinou por dois anos. Enquanto isso, o povo de Judá permaneceu leal a Davi,

[[v10-2-11]]

^<<v10-2-11,11>>^ que fez de Hebrom sua capital e reinou sobre Judá por sete anos e meio.

[[v10-2-12]]

^<<v10-2-12,12>>^ Certo dia, Abner, filho de Ner, conduziu as tropas de Isbosete, filho de Saul, de Maanaim para Gibeom.

[[v10-2-13]]

^<<v10-2-13,13>>^ Ao mesmo tempo, Joabe, filho de Zeruia, saiu com as tropas de Davi e foi ao encontro deles na represa de Gibeom, onde os dois exércitos ficaram frente a frente, posicionando-se em lados opostos da represa.

[[v10-2-14]]

^<<v10-2-14,14>>^ Então Abner disse a Joabe: "Proponho que alguns de nossos guerreiros lutem em confronto direto diante de nós". "Está bem", respondeu Joabe.

[[v10-2-15]]

^<<v10-2-15,15>>^ Então foram escolhidos doze soldados de Benjamim para representar Isbosete, filho de Saul, e doze soldados para representar Davi.

[[v10-2-16]]

^<<v10-2-16,16>>^ Cada um agarrou seu adversário pela cabeça e cravou a espada um no lado do outro, e todos morreram juntos. Por isso, desde então, esse lugar em Gibeom é conhecido como Helcate-Hazurim.

[[v10-2-17]]

^<<v10-2-17,17>>^ Seguiu-se nesse dia uma violenta batalha, na qual Abner e os homens de Israel foram derrotados pelos soldados de Davi.

[[v10-2-18]]

^<<v10-2-18,18>>^ Joabe, Abisai e Asael, os três filhos de Zeruia, participaram da batalha nesse dia. Asael, que era rápido como uma gazela,

[[v10-2-19]]

^<<v10-2-19,19>>^ começou a perseguir Abner. Continuou decididamente em seu encalço, sem perdê-lo de vista.

[[v10-2-20]]

^<<v10-2-20,20>>^ Quando Abner olhou para trás e viu que ele se aproximava, perguntou: "É você, Asael?".

[[v10-2-21]]

^<<v10-2-21,21>>^ "Saia do meu encalço!", disse Abner. "Enfrente um dos soldados mais jovens e tome suas armas." Mas Asael continuou a persegui-lo.

[[v10-2-22]]

^<<v10-2-22,22>>^ Mais uma vez, Abner o advertiu: "Pare de me perseguir! Não quero matá-lo. Como poderia encarar seu irmão Joabe?".

[[v10-2-23]]

^<<v10-2-23,23>>^ Asael, porém, se recusou a dar meia-volta, e Abner lhe cravou no estômago a parte de trás da lança, que saiu pelas costas. Asael caiu morto no chão. E todos que passavam por ali paravam ao ver Asael caído e morto.

[[v10-2-24]]

^<<v10-2-24,24>>^ Então Joabe e Abisai saíram em perseguição a Abner. O sol estava se pondo quando chegaram ao monte Amá, perto de Gia, no caminho para o deserto de Gibeom.

[[v10-2-25]]

^<<v10-2-25,25>>^ Os soldados de Abner, da tribo de Benjamim, se reuniram no alto do monte para resistir ao ataque.

[[v10-2-26]]

^<<v10-2-26,26>>^ Então Abner gritou para Joabe: "Será que não há como evitar matarmos uns aos outros? Não vê que isso só resultará em amargura? Quando você vai ordenar que seus homens parem de perseguir seus irmãos israelitas?".

[[v10-2-27]]

^<<v10-2-27,27>>^ Joabe respondeu: "Só Deus sabe o que teria acontecido se você não tivesse falado, pois, se fosse preciso, nós os teríamos perseguido a noite toda".

[[v10-2-28]]

^<<v10-2-28,28>>^ Então Joabe tocou a trombeta e seus homens pararam de perseguir os soldados de Israel, e a batalha cessou.

[[v10-2-29]]

^<<v10-2-29,29>>^ Durante toda aquela noite, Abner e seus homens recuaram pelo vale do Jordão. Atravessaram o rio, marcharam a manhã inteira e só pararam quando chegaram a Maanaim.

[[v10-2-30]]

^<<v10-2-30,30>>^ Enquanto isso, Joabe e seus homens também voltaram da perseguição a Abner. Quando Joabe fez a contagem, viu que faltavam apenas dezenove homens, além de Asael.

[[v10-2-31]]

^<<v10-2-31,31>>^ Os soldados de Davi, por sua vez, haviam matado 360 homens da tribo de Benjamim e dos demais soldados de Abner.

[[v10-2-32]]

^<<v10-2-32,32>>^ Joabe e seus homens levaram o corpo de Asael para Belém e o sepultaram no túmulo de seu pai. Então caminharam a noite toda e chegaram a Hebrom ao amanhecer.

'''

xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[&#60; Capítulo Anterior] | <<v10-2-0,Topo>> | xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[Próximo Capítulo &#62;]