include::./index.adoc[]

[[v10-12-0]]
=== 2 Samuel, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v10-12-1]]

^<<v10-12-1,1>>^ Então o SENHOR enviou o profeta Natã a Davi. Ele foi até o rei e lhe disse: "Havia dois homens em certa cidade. Um era rico, e o outro, pobre.

[[v10-12-2]]

^<<v10-12-2,2>>^ O rico era dono de muitas ovelhas e muito gado.

[[v10-12-3]]

^<<v10-12-3,3>>^ O pobre não tinha nada, exceto uma cordeirinha que ele havia comprado. Ele criou a cordeirinha, e ela cresceu com os filhos dele. Comia de seu prato, bebia de seu copo e até dormia em seus braços; ela era como sua filha.

[[v10-12-4]]

^<<v10-12-4,4>>^ Certo dia, um visitante chegou à casa do rico. Em vez de matar um dos animais de seu próprio rebanho, o rico tomou a cordeirinha do pobre, a matou e a preparou para seu visitante".

[[v10-12-5]]

^<<v10-12-5,5>>^ Davi ficou furioso com esse homem rico e jurou: "Tão certo como vive o SENHOR, o homem que faz uma coisa dessas merece morrer!

[[v10-12-6]]

^<<v10-12-6,6>>^ Deve restituir quatro ovelhas ao pobre por ter roubado a cordeirinha e não ter mostrado compaixão".

[[v10-12-7]]

^<<v10-12-7,7>>^ Então Natã disse a Davi: "Você é esse homem! Assim diz o SENHOR, o Deus de Israel: ‘Eu o ungi rei de Israel e o livrei das mãos de Saul.

[[v10-12-8]]

^<<v10-12-8,8>>^ Dei-lhe a casa e as mulheres de seu senhor e os reinos de Israel e Judá. E, se isso não bastasse, teria lhe dado muito mais.

[[v10-12-9]]

^<<v10-12-9,9>>^ Por que, então, você desprezou a palavra do SENHOR e fez algo tão horrível? Você assassinou Urias, o hitita, com a espada dos amonitas e roubou a esposa dele!

[[v10-12-10]]

^<<v10-12-10,10>>^ De agora em diante, a espada não se afastará de sua família, pois você me desprezou ao tomar para si a mulher de Urias’.

[[v10-12-11]]

^<<v10-12-11,11>>^ "Assim diz o SENHOR: ‘De sua própria família farei surgir seu castigo. Tomarei suas mulheres diante de seus olhos e as darei a outro homem; ele se deitará com elas à vista de todos.

[[v10-12-12]]

^<<v10-12-12,12>>^ O que você fez em segredo, eu farei acontecer abertamente, diante de todo o Israel’".

[[v10-12-13]]

^<<v10-12-13,13>>^ Então Davi confessou a Natã: "Pequei contra o SENHOR". Natã respondeu: "Sim, mas o SENHOR o perdoou, e você não morrerá por causa do seu pecado.

[[v10-12-14]]

^<<v10-12-14,14>>^ Contudo, uma vez que você demonstrou o mais absoluto desprezo pela palavra do SENHOR ao agir desse modo, seu filho morrerá".

[[v10-12-15]]

^<<v10-12-15,15>>^ Depois que Natã voltou para casa, o SENHOR fez adoecer gravemente o filho de Davi com a mulher de Urias.

[[v10-12-16]]

^<<v10-12-16,16>>^ Davi suplicou ao SENHOR que poupasse a criança. Jejuou e passou a noite prostrado no chão.

[[v10-12-17]]

^<<v10-12-17,17>>^ Os oficiais do palácio insistiram para que ele se levantasse e comesse com eles, mas Davi se recusou.

[[v10-12-18]]

^<<v10-12-18,18>>^ No sétimo dia, a criança morreu. Os servos de Davi ficaram com medo de contar para ele. "Não ouviu nossos conselhos quando a criança estava doente", disseram. "Se lhe contarmos que a criança morreu, poderá cometer uma insanidade."

[[v10-12-19]]

^<<v10-12-19,19>>^ Davi percebeu que estavam cochichando e compreendeu o que havia acontecido. "A criança morreu?", perguntou. "Sim", responderam eles. "Está morta."

[[v10-12-20]]

^<<v10-12-20,20>>^ Então Davi levantou-se do chão, lavou-se, perfumou-se e trocou de roupa. Foi ao santuário e adorou o SENHOR. Depois, voltou ao palácio, pediu que lhe trouxessem alimento e comeu.

[[v10-12-21]]

^<<v10-12-21,21>>^ Seus servos ficaram perplexos. "Não o entendemos", disseram. "Enquanto a criança estava viva, o senhor chorou e jejuou. Agora que a criança morreu, o senhor parou de lamentar e voltou a comer."

[[v10-12-22]]

^<<v10-12-22,22>>^ Davi respondeu: "Enquanto a criança estava viva, jejuei e chorei, pois pensava: ‘Quem sabe o SENHOR terá compaixão de mim e deixará a criança viver’.

[[v10-12-23]]

^<<v10-12-23,23>>^ Mas por que jejuar agora que ela morreu? Poderia eu fazê-la voltar? Um dia irei até ela, mas ela não voltará a mim".

[[v10-12-24]]

^<<v10-12-24,24>>^ Então Davi consolou Bate-Seba, sua mulher, e teve relações com ela. Bate-Seba engravidou e deu à luz um filho, a quem Davi chamou Salomão. O SENHOR amou a criança

[[v10-12-25]]

^<<v10-12-25,25>>^ e enviou uma mensagem por meio do profeta Natã, dizendo que o menino devia se chamar Jedidias, conforme o SENHOR havia ordenado.

[[v10-12-26]]

^<<v10-12-26,26>>^ Enquanto isso, Joabe continuou a lutar contra Rabá, a capital de Amom, e tomou a cidade real.

[[v10-12-27]]

^<<v10-12-27,27>>^ Joabe enviou mensageiros a Davi para lhe dizer: "Lutei contra Rabá e capturei seus reservatórios de água.

[[v10-12-28]]

^<<v10-12-28,28>>^ Traga o restante do exército aqui e conquiste a cidade. De outro modo, eu a tomarei e levarei o crédito pela vitória".

[[v10-12-29]]

^<<v10-12-29,29>>^ Então Davi reuniu o restante do exército e foi a Rabá. Eles atacaram a cidade e a conquistaram.

[[v10-12-30]]

^<<v10-12-30,30>>^ Davi removeu a coroa da cabeça do rei, e ela foi colocada sobre sua cabeça. A coroa era feita de ouro, enfeitada com pedras preciosas, e pesava cerca de 35 quilos. Davi tomou grande quantidade de despojos da cidade.

[[v10-12-31]]

^<<v10-12-31,31>>^ Também tornou os habitantes de Rabá seus escravos e os obrigou a trabalhar com serras, picaretas e machados de ferro, e também nos fornos de tijolos. Foi assim que Davi tratou o povo de todas as cidades amonitas. Então ele e todo o exército voltaram para Jerusalém.

'''

xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[&#60; Capítulo Anterior] | <<v10-12-0,Topo>> | xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[Próximo Capítulo &#62;]