include::./index.adoc[]

[[v10-1-0]]
=== 2 Samuel, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v10-1-1]]

^<<v10-1-1,1>>^ Depois da morte de Saul, Davi retornou de sua vitória sobre os amalequitas e passou dois dias em Ziclague.

[[v10-1-2]]

^<<v10-1-2,2>>^ No terceiro dia, apareceu um homem do exército de Saul. Ele havia rasgado as roupas e colocado terra sobre a cabeça. Ao chegar, curvou-se diante de Davi com o rosto no chão.

[[v10-1-3]]

^<<v10-1-3,3>>^ "De onde você vem?", perguntou Davi. O homem respondeu: "Escapei do acampamento israelita".

[[v10-1-4]]

^<<v10-1-4,4>>^ "O que aconteceu?", disse Davi. "Conte-me como foi a batalha." "Todo o nosso exército fugiu do conflito", disse o homem. "Muitos morreram, e Saul e seu filho Jônatas também estão mortos."

[[v10-1-5]]

^<<v10-1-5,5>>^ "Como você sabe que Saul e Jônatas estão mortos?", perguntou Davi.

[[v10-1-6]]

^<<v10-1-6,6>>^ O homem respondeu: "Aconteceu de eu chegar ao monte Gilboa e ver Saul apoiado em sua lança, enquanto carros de guerra e cavaleiros inimigos se aproximavam dele.

[[v10-1-7]]

^<<v10-1-7,7>>^ Quando ele se virou e me viu, gritou para que eu me aproximasse dele. ‘Aqui estou, senhor’, eu lhe disse.

[[v10-1-8]]

^<<v10-1-8,8>>^ Ele perguntou: ‘Quem é você?’. E eu respondi: ‘Sou amalequita’.

[[v10-1-9]]

^<<v10-1-9,9>>^ Então ele me suplicou: ‘Venha cá e mate-me, pois a dor é terrível e quero morrer’.

[[v10-1-10]]

^<<v10-1-10,10>>^ Então o matei, pois sabia que ele não sobreviveria. Em seguida, tomei sua coroa e seu bracelete e os trouxe para cá, para o meu senhor".

[[v10-1-11]]

^<<v10-1-11,11>>^ Quando ouviram a notícia, Davi e seus homens rasgaram as vestes.

[[v10-1-12]]

^<<v10-1-12,12>>^ Lamentaram, choraram e jejuaram o dia todo por Saul e seu filho Jônatas, pelo exército do SENHOR e pela nação de Israel, pois naquele dia muitos haviam morrido pela espada.

[[v10-1-13]]

^<<v10-1-13,13>>^ Depois, Davi disse ao jovem que havia trazido a notícia: "De onde você é?". Ele respondeu: "Sou filho de um estrangeiro, um amalequita que vive em sua terra".

[[v10-1-14]]

^<<v10-1-14,14>>^ Davi perguntou: "Como você não teve medo de matar o ungido do SENHOR?".

[[v10-1-15]]

^<<v10-1-15,15>>^ Então Davi chamou um de seus soldados e lhe ordenou: "Mate-o!". O soldado feriu o amalequita com sua espada e o matou.

[[v10-1-16]]

^<<v10-1-16,16>>^ Davi disse: "Você condenou a si mesmo ao confessar que matou o ungido do SENHOR".

[[v10-1-17]]

^<<v10-1-17,17>>^ Davi entoou uma canção fúnebre para Saul e Jônatas

[[v10-1-18]]

^<<v10-1-18,18>>^ e ordenou que fosse ensinada ao povo de Judá. Ela é conhecida como Cântico do Arco e está registrada no Livro de Jasar .

[[v10-1-19]]

^<<v10-1-19,19>>^ Seu esplendor, ó Israel, está morto sobre os montes! Como caíram os valentes!

[[v10-1-20]]

^<<v10-1-20,20>>^ Não contem essa notícia em Gate, não a proclamem nas ruas de Asquelom, para que não se alegrem as filhas dos filisteus, para que as filhas dos incircuncisos não festejem em triunfo.

[[v10-1-21]]

^<<v10-1-21,21>>^ Ó montes de Gilboa, que não haja orvalho nem chuva sobre vocês, nem campos férteis que produzam ofertas de cereais. Pois ali foram profanados os escudos de valentes; o escudo de Saul não será mais ungido com óleo.

[[v10-1-22]]

^<<v10-1-22,22>>^ O arco de Jônatas não recuava, e a espada de Saul era invencível. Derramaram o sangue de seus inimigos e atravessaram o corpo de guerreiros.

[[v10-1-23]]

^<<v10-1-23,23>>^ Quão amados e estimados eram Saul e Jônatas! Estiveram juntos na vida e na morte. Eram mais velozes que as águias, mais fortes que os leões.

[[v10-1-24]]

^<<v10-1-24,24>>^ Ó filhas de Israel, chorem por Saul, pois ele as vestia com finos trajes vermelhos, com roupas adornadas de ouro.

[[v10-1-25]]

^<<v10-1-25,25>>^ Como caíram os valentes na batalha! Jônatas está morto sobre os montes.

[[v10-1-26]]

^<<v10-1-26,26>>^ Como choro por você, meu irmão Jônatas, quanto eu o estimava! Seu amor por mim era precioso, mais que o amor das mulheres.

[[v10-1-27]]

^<<v10-1-27,27>>^ Como caíram os valentes! Estão mortos, despojados de suas armas.

'''

xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[&#60; Capítulo Anterior] | <<v10-1-0,Topo>> | xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[Próximo Capítulo &#62;]