include::./index.adoc[]

[[v10-14-0]]
=== 2 Samuel, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v10-14-1]]

^<<v10-14-1,1>>^ Joabe, filho de Zeruia, percebeu que o rei agora desejava ver Absalão.

[[v10-14-2]]

^<<v10-14-2,2>>^ Por isso, mandou trazer de Tecoa uma mulher conhecida por sua sabedoria. Disse-lhe: "Finja que está de luto; vista roupas de luto e não se perfume. Aja como uma mulher que está lamentando a morte de alguém há muito tempo.

[[v10-14-3]]

^<<v10-14-3,3>>^ Depois, vá até o rei e apresente a história que vou lhe contar". Então Joabe disse o que ela deveria falar.

[[v10-14-4]]

^<<v10-14-4,4>>^ Quando a mulher de Tecoa se aproximou do rei, curvou-se com o rosto no chão e disse: "Ó rei! Ajude-me!".

[[v10-14-5]]

^<<v10-14-5,5>>^ "Qual é o problema?", perguntou o rei. "Pobre de mim, sou viúva!", respondeu ela. "Meu marido morreu.

[[v10-14-6]]

^<<v10-14-6,6>>^ Meus dois filhos brigaram no campo. Como não havia ninguém por perto para separá-los, um deles acabou matando o outro.

[[v10-14-7]]

^<<v10-14-7,7>>^ Agora, o resto da família está exigindo de sua serva: ‘Entregue-nos seu filho. Vamos executá-lo por ter matado o irmão. Ele não merece herdar a propriedade da família’. Querem apagar a última brasa que me restou; se o fizerem, o nome e a família de meu marido desaparecerão da face da terra."

[[v10-14-8]]

^<<v10-14-8,8>>^ "Eu cuidarei disso", disse o rei. "Vá para casa."

[[v10-14-9]]

^<<v10-14-9,9>>^ A mulher de Tecoa respondeu: "Ó meu senhor, o rei, que a culpa caia sobre mim e sobre a família de meu pai, e que o rei e seu trono sejam inocentes!".

[[v10-14-10]]

^<<v10-14-10,10>>^ "Se alguém criar problemas, traga-o a mim", disse o rei. "Eu lhe garanto que ele nunca mais a incomodará."

[[v10-14-11]]

^<<v10-14-11,11>>^ Então ela disse: "Por favor, prometa pelo SENHOR, seu Deus, que não deixará o vingador da vítima matar meu filho. Não quero mais derramamento de sangue". Ele respondeu: "Tão certo como vive o SENHOR, ninguém tocará num fio de cabelo da cabeça de seu filho!".

[[v10-14-12]]

^<<v10-14-12,12>>^ "Permita-me pedir mais uma coisa ao meu senhor, o rei", disse a mulher. "Fale", respondeu ele.

[[v10-14-13]]

^<<v10-14-13,13>>^ Então ela disse: "Por que o senhor não faz pelo povo de Deus o mesmo que prometeu fazer por mim? Ao tomar essa decisão, o senhor condenou a si mesmo, pois se recusou a trazer para casa seu filho banido.

[[v10-14-14]]

^<<v10-14-14,14>>^ Um dia, todos nós morreremos. Nossa vida é como água que, depois de derramada na terra, não pode mais ser recolhida. Mas Deus não apaga a vida; ao contrário, ele cria meios de trazer de volta aqueles que foram banidos de sua presença.

[[v10-14-15]]

^<<v10-14-15,15>>^ "Vim suplicar ao meu senhor, o rei, porque outros me ameaçaram. Pensei: ‘Talvez o rei me escute

[[v10-14-16]]

^<<v10-14-16,16>>^ e nos livre daqueles que desejam nos eliminar da herança que Deus nos deu.

[[v10-14-17]]

^<<v10-14-17,17>>^ Sim, o meu senhor, o rei, restaurará nossa paz de espírito’. Sei que o senhor é como um anjo de Deus, capaz de discernir entre o bem e o mal. Que o SENHOR, seu Deus, esteja com o rei".

[[v10-14-18]]

^<<v10-14-18,18>>^ "Preciso saber uma coisa", disse o rei. "Diga-me a verdade." "Sim, ó meu senhor, o rei", disse a mulher.

[[v10-14-19]]

^<<v10-14-19,19>>^ "Foi Joabe quem a mandou aqui?", perguntou o rei. A mulher respondeu: "Ó meu senhor, o rei, como posso negar? Ninguém é capaz de esconder coisa alguma do senhor. Sim, foi Joabe, servo do rei, que me enviou e me disse o que falar.

[[v10-14-20]]

^<<v10-14-20,20>>^ Agiu desse modo para que o senhor pudesse ver a questão com outros olhos. Mas o senhor é sábio como um anjo de Deus e entende tudo que acontece em nosso meio!".

[[v10-14-21]]

^<<v10-14-21,21>>^ Então o rei mandou chamar Joabe e lhe disse: "Muito bem, vá e traga de volta o jovem Absalão".

[[v10-14-22]]

^<<v10-14-22,22>>^ Joabe se curvou com o rosto no chão e disse: "Finalmente sei que obtive o favor do meu senhor, o rei, pois atendeu a meu pedido!".

[[v10-14-23]]

^<<v10-14-23,23>>^ Joabe foi a Gesur e trouxe Absalão de volta a Jerusalém.

[[v10-14-24]]

^<<v10-14-24,24>>^ O rei, porém, deu a seguinte ordem: "Absalão pode ir para casa, mas não deve vir à minha presença". Portanto, Absalão não viu o rei.

[[v10-14-25]]

^<<v10-14-25,25>>^ Não havia nenhum homem em todo o Israel tão elogiado por sua beleza como Absalão; era perfeito da cabeça aos pés.

[[v10-14-26]]

^<<v10-14-26,26>>^ Cortava o cabelo uma vez por ano por causa de seu peso: 2,4 quilos, segundo o peso real.

[[v10-14-27]]

^<<v10-14-27,27>>^ Tinha três filhos e uma filha. Sua filha se chamava Tamar e era muito bonita.

[[v10-14-28]]

^<<v10-14-28,28>>^ Absalão morou dois anos em Jerusalém sem ver o rei.

[[v10-14-29]]

^<<v10-14-29,29>>^ Então mandou chamar Joabe para pedir que intercedesse por ele, mas Joabe não quis vir. Mandou chamá-lo de novo e, mais uma vez, ele se recusou a vir.

[[v10-14-30]]

^<<v10-14-30,30>>^ Então Absalão disse a seus servos: "Vão e ponham fogo no campo de cevada de Joabe que fica junto de minha propriedade". Os servos foram e puseram fogo no campo, como Absalão havia ordenado.

[[v10-14-31]]

^<<v10-14-31,31>>^ Então Joabe foi à casa de Absalão e lhe perguntou: "Por que seus servos puseram fogo em meu campo?".

[[v10-14-32]]

^<<v10-14-32,32>>^ Absalão respondeu: "Eu quero que você pergunte ao rei por que ele me trouxe de Gesur se não pretendia me receber. Teria sido melhor eu ficar onde estava. Quero ver o rei; se ele me considera culpado de algo, então que mande me matar".

[[v10-14-33]]

^<<v10-14-33,33>>^ Joabe contou ao rei o que Absalão tinha dito. Por fim, Davi mandou chamar Absalão. Ele veio, curvou-se com o rosto no chão diante do rei, e o rei o beijou.

'''

xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[&#60; Capítulo Anterior] | <<v10-14-0,Topo>> | xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[Próximo Capítulo &#62;]