include::./index.adoc[]

[[v30-1-0]]
=== Amós, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v30-1-1]]

^<<v30-1-1,1>>^ Esta mensagem acerca de Israel foi dada a Amós, pastor de ovelhas da cidade de Tecoa, em Judá. Ele a recebeu em visões dois anos antes do terremoto, quando Uzias era rei de Judá, e Jeroboão, filho de Jeoás, era rei de Israel.

[[v30-1-2]]

^<<v30-1-2,2>>^ Foi isto que ele viu e ouviu: "A voz do SENHOR rugirá desde Sião e trovejará desde Jerusalém! Os pastos verdes dos pastores secarão, e o capim no monte Carmelo murchará e morrerá".

[[v30-1-3]]

^<<v30-1-3,3>>^ Assim diz o SENHOR: "Os habitantes de Damasco pecaram repetidamente; não deixarei que fiquem impunes! Feriram meu povo em Gileade, como o cereal é debulhado com trilhos de ferro.

[[v30-1-4]]

^<<v30-1-4,4>>^ Por isso enviarei fogo sobre o palácio do rei Hazael, e as fortalezas do rei Ben-Hadade serão destruídas.

[[v30-1-5]]

^<<v30-1-5,5>>^ Derrubarei os portões de Damasco e matarei todos que habitam no vale de Áven. Destruirei o governante em Bete-Éden, e o povo da Síria será levado como escravo para Quir", diz o SENHOR.

[[v30-1-6]]

^<<v30-1-6,6>>^ Assim diz o SENHOR: "Os habitantes de Gaza pecaram repetidamente; não deixarei que fiquem impunes! Enviaram todo o povo para o exílio e o entregaram como escravos para Edom.

[[v30-1-7]]

^<<v30-1-7,7>>^ Por isso enviarei fogo sobre os muros de Gaza, e suas fortalezas serão destruídas.

[[v30-1-8]]

^<<v30-1-8,8>>^ Matarei os que habitam em Asdode e destruirei o governante de Ascalom. Então me voltarei para atacar Ecrom, e os filisteus que restarem serão mortos", diz o SENHOR Soberano.

[[v30-1-9]]

^<<v30-1-9,9>>^ Assim diz o SENHOR: "Os habitantes de Tiro pecaram repetidamente; não deixarei que fiquem impunes! Quebraram o pacto de irmãos com Israel e entregaram todo o povo como escravo para Edom.

[[v30-1-10]]

^<<v30-1-10,10>>^ Por isso enviarei fogo sobre os muros de Tiro, e suas fortalezas serão destruídas".

[[v30-1-11]]

^<<v30-1-11,11>>^ Assim diz o SENHOR: "Os habitantes de Edom pecaram repetidamente; não deixarei que fiquem impunes! Com espadas perseguiram seus parentes, os israelitas, e não tiveram compaixão deles. Em sua fúria, os despedaçaram sem parar e foram implacáveis em sua ira.

[[v30-1-12]]

^<<v30-1-12,12>>^ Por isso enviarei fogo sobre Temã, e as fortalezas de Bozra serão destruídas".

[[v30-1-13]]

^<<v30-1-13,13>>^ Assim diz o SENHOR: "Os habitantes de Amom pecaram repetidamente; não deixarei que fiquem impunes! Quando atacaram Gileade para ampliar suas fronteiras, abriram as mulheres grávidas ao meio com espadas.

[[v30-1-14]]

^<<v30-1-14,14>>^ Por isso enviarei fogo sobre os muros de Rabá, e suas fortalezas serão destruídas. A batalha virá sobre eles com gritos, como um redemoinho numa forte tempestade.

[[v30-1-15]]

^<<v30-1-15,15>>^ Seu rei e seus príncipes irão juntos para o exílio", diz o SENHOR.

'''

xref:029-joel/029-joel-003.adoc#v29-3-0[&#60; Capítulo Anterior] | <<v30-1-0,Topo>> | xref:030-amos/030-amos-002.adoc#v30-2-0[Próximo Capítulo &#62;]