include::./index.adoc[]

[[v30-2-0]]
=== Amós, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v30-2-1]]

^<<v30-2-1,1>>^ Assim diz o SENHOR: "Os habitantes de Moabe pecaram repetidamente; não deixarei que fiquem impunes! Queimaram os ossos do rei de Edom até reduzi-los a cinzas.

[[v30-2-2]]

^<<v30-2-2,2>>^ Por isso enviarei fogo sobre a terra de Moabe, e as fortalezas de Queriote serão destruídas. Os que habitam nela cairão em meio ao ruído da batalha, aos gritos dos guerreiros e ao som da trombeta.

[[v30-2-3]]

^<<v30-2-3,3>>^ Destruirei seu rei e matarei seus príncipes", diz o SENHOR.

[[v30-2-4]]

^<<v30-2-4,4>>^ Assim diz o SENHOR: "Os habitantes de Judá pecaram repetidamente; não deixarei que fiquem impunes! Rejeitaram a lei do Senhor e não obedeceram a seus decretos. Foram desviados pelas mesmas mentiras que enganaram seus antepassados.

[[v30-2-5]]

^<<v30-2-5,5>>^ Por isso enviarei fogo sobre Judá, e as fortalezas de Jerusalém serão destruídas".

[[v30-2-6]]

^<<v30-2-6,6>>^ Assim diz o SENHOR: "Os habitantes de Israel pecaram repetidamente; não deixarei que fiquem impunes! Vendem por prata o justo e, por um par de sandálias, o pobre.

[[v30-2-7]]

^<<v30-2-7,7>>^ Pisoteiam a cabeça dos indefesos no pó e empurram os oprimidos para fora do caminho. Pai e filho dormem com a mesma mulher e assim profanam meu santo nome.

[[v30-2-8]]

^<<v30-2-8,8>>^ Aos pés dos altares reclinam-se com roupas que seus devedores lhes deram como garantia. Na casa de seus deuses, bebem vinho comprado com multas injustas.

[[v30-2-9]]

^<<v30-2-9,9>>^ "Diante dos olhos de meu povo, destruí os amorreus, embora fossem altos como cedros e fortes como carvalhos. Destruí os frutos de seus galhos e arranquei suas raízes.

[[v30-2-10]]

^<<v30-2-10,10>>^ Trouxe vocês do Egito e os guiei quarenta anos pelo deserto, para que possuíssem a terra dos amorreus.

[[v30-2-11]]

^<<v30-2-11,11>>^ Escolhi alguns de seus filhos para serem profetas e outros, para serem nazireus. Acaso podem negar isso, israelitas?", diz o SENHOR.

[[v30-2-12]]

^<<v30-2-12,12>>^ "Mas vocês deram vinho para os nazireus beberem e ordenaram a seus profetas: ‘Chega de profecias!’.

[[v30-2-13]]

^<<v30-2-13,13>>^ "Por isso eu os esmagarei, como uma carroça sobrecarregada de trigo amassa a terra.

[[v30-2-14]]

^<<v30-2-14,14>>^ O que corre mais rápido não escapará, o mais forte em seu meio se enfraquecerá, nem o guerreiro valente se salvará.

[[v30-2-15]]

^<<v30-2-15,15>>^ O arqueiro não manterá sua posição, o corredor mais veloz não conseguirá escapar, nem o que estiver a cavalo se salvará.

[[v30-2-16]]

^<<v30-2-16,16>>^ Naquele dia, seus guerreiros mais corajosos largarão as armas e fugirão", diz o SENHOR.

'''

xref:030-amos/030-amos-001.adoc#v30-1-0[&#60; Capítulo Anterior] | <<v30-2-0,Topo>> | xref:030-amos/030-amos-003.adoc#v30-3-0[Próximo Capítulo &#62;]