include::./index.adoc[]

[[v30-8-0]]
=== Amós, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v30-8-1]]

^<<v30-8-1,1>>^ Em outra visão, o SENHOR Soberano me mostrou um cesto cheio de frutas maduras

[[v30-8-2]]

^<<v30-8-2,2>>^ e perguntou: "Amós, o que você vê?". Respondi: "Um cesto cheio de frutas maduras". Então o SENHOR disse: "Assim como essas frutas, o povo de Israel já está maduro; não voltarei a adiar seu castigo.

[[v30-8-3]]

^<<v30-8-3,3>>^ Naquele dia, os cânticos no templo se transformarão em lamentos. Haverá cadáveres espalhados por toda parte, e serão levados em silêncio para fora da cidade. Eu, o SENHOR Soberano, falei!".

[[v30-8-4]]

^<<v30-8-4,4>>^ Ouçam isto, vocês que roubam dos pobres e oprimem os necessitados!

[[v30-8-5]]

^<<v30-8-5,5>>^ Não veem a hora de o sábado acabar e as festas religiosas terminarem para que voltem a fazer negócios. Usam medidas falsas para medir o trigo e enganam o comprador com balanças desonestas.

[[v30-8-6]]

^<<v30-8-6,6>>^ Misturam o trigo que vendem com palha varrida do chão. Escravizam os pobres por uma moeda de prata ou um par de sandálias.

[[v30-8-7]]

^<<v30-8-7,7>>^ O SENHOR, a Glória de Israel, jurou por seu próprio nome: "Jamais esquecerei tudo que vocês fizeram!

[[v30-8-8]]

^<<v30-8-8,8>>^ A terra tremerá por causa de suas maldades, e todos que nela habitam lamentarão. A terra se levantará como o Nilo, o rio do Egito, na época das enchentes; ela se erguerá e depois afundará.

[[v30-8-9]]

^<<v30-8-9,9>>^ "Naquele dia", diz o SENHOR Soberano, "farei o sol se pôr ao meio-dia e em plena luz do dia escurecerei a terra.

[[v30-8-10]]

^<<v30-8-10,10>>^ Transformarei suas festas em tempos de lamento e seus cânticos, em canções fúnebres. Vocês se vestirão de luto e rasparão a cabeça, como se seu único filho tivesse morrido; será um dia de muita amargura!

[[v30-8-11]]

^<<v30-8-11,11>>^ "Está chegando o tempo", diz o SENHOR Soberano, "em que enviarei fome sobre a terra, não fome de pão nem sede de água, mas de ouvir as palavras do SENHOR.

[[v30-8-12]]

^<<v30-8-12,12>>^ As pessoas andarão sem rumo, de mar em mar e de um extremo ao outro, em busca da palavra do SENHOR, mas não a encontrarão.

[[v30-8-13]]

^<<v30-8-13,13>>^ Naquele dia, moças belas e rapazes fortes desmaiarão de sede.

[[v30-8-14]]

^<<v30-8-14,14>>^ E aqueles que juram pelos ídolos de Samaria, que fazem juramentos em nome do deus de Dã e votos em nome do deus de Berseba, todos eles cairão e nunca mais se levantarão."

'''

xref:030-amos/030-amos-007.adoc#v30-7-0[&#60; Capítulo Anterior] | <<v30-8-0,Topo>> | xref:030-amos/030-amos-009.adoc#v30-9-0[Próximo Capítulo &#62;]