include::./index.adoc[]

[[v30-4-0]]
=== Amós, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v30-4-1]]

^<<v30-4-1,1>>^ Ouçam, vacas gordas que vivem em Samaria, mulheres que oprimem os pobres, esmagam os necessitados e pedem aos maridos: "Tragam-nos mais bebida!".

[[v30-4-2]]

^<<v30-4-2,2>>^ O SENHOR Soberano jurou por sua santidade: "Chegará o dia em que serão levadas com ganchos no nariz. Até a última de vocês será arrastada como peixe no anzol!

[[v30-4-3]]

^<<v30-4-3,3>>^ Serão levadas para fora pelas ruínas do muro e expulsas de suas fortalezas", diz o SENHOR.

[[v30-4-4]]

^<<v30-4-4,4>>^ "Andem, vão a Betel cometer pecados! Continuem a desobedecer em Gilgal! Ofereçam sacrifícios todas as manhãs e tragam seus dízimos a cada três dias.

[[v30-4-5]]

^<<v30-4-5,5>>^ Apresentem seu pão com fermento como oferta de gratidão. Entreguem suas ofertas voluntárias para saírem se gabando delas! É o tipo de coisa que vocês, israelitas, gostam de fazer", diz o SENHOR Soberano.

[[v30-4-6]]

^<<v30-4-6,6>>^ "Eu trouxe fome sobre toda cidade, escassez de alimento sobre todo lugar. Nem assim vocês voltaram para mim", diz o SENHOR.

[[v30-4-7]]

^<<v30-4-7,7>>^ "Segurei as chuvas quando suas plantações mais precisavam delas. Enviei chuva para uma cidade, mas a retive em outra. Chovia sobre um campo, enquanto outro secava.

[[v30-4-8]]

^<<v30-4-8,8>>^ Andavam de cidade em cidade em busca de água, mas nunca havia suficiente. Nem assim vocês voltaram para mim", diz o SENHOR.

[[v30-4-9]]

^<<v30-4-9,9>>^ "Castiguei suas plantações e videiras com pragas e ferrugem; gafanhotos devoraram suas figueiras e oliveiras. Nem assim vocês voltaram para mim", diz o SENHOR.

[[v30-4-10]]

^<<v30-4-10,10>>^ "Enviei pragas contra vocês, como as pragas que enviei contra o Egito. Matei seus jovens na guerra e levei todos os seus cavalos; o mau cheiro dos mortos encheu o ar. Nem assim vocês voltaram para mim", diz o SENHOR.

[[v30-4-11]]

^<<v30-4-11,11>>^ "Destruí algumas de suas cidades, como destruí Sodoma e Gomorra. Os que sobreviveram pareciam gravetos chamuscados, tirados do fogo. Nem assim vocês voltaram para mim", diz o SENHOR.

[[v30-4-12]]

^<<v30-4-12,12>>^ "Portanto, farei tudo isso com você, ó Israel! Prepare-se para encontrar seu Deus!"

[[v30-4-13]]

^<<v30-4-13,13>>^ Pois aquele que formou os montes agita os ventos e revela seus pensamentos à humanidade. Ele transforma a luz do amanhecer em escuridão e pisa sobre os lugares altos da terra; seu nome é SENHOR, o Deus dos Exércitos!

'''

xref:030-amos/030-amos-003.adoc#v30-3-0[&#60; Capítulo Anterior] | <<v30-4-0,Topo>> | xref:030-amos/030-amos-005.adoc#v30-5-0[Próximo Capítulo &#62;]