include::./index.adoc[]

[[v30-3-0]]
=== Amós, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v30-3-1]]

^<<v30-3-1,1>>^ Povo de Israel, ouça esta mensagem que o SENHOR pronunciou contra você, contra toda a família que ele trouxe do Egito:

[[v30-3-2]]

^<<v30-3-2,2>>^ "De todas as famílias da terra, só escolhi vocês. Por isso devo castigá-los por todos os seus pecados".

[[v30-3-3]]

^<<v30-3-3,3>>^ Acaso duas pessoas podem andar juntas se não estiverem de acordo?

[[v30-3-4]]

^<<v30-3-4,4>>^ Acaso o leão ruge na floresta sem antes encontrar sua presa? O leão forte rosna em sua toca se nada tiver caçado?

[[v30-3-5]]

^<<v30-3-5,5>>^ A ave é pega na armadilha se não houver isca? A armadilha se fecha se nada for apanhado?

[[v30-3-6]]

^<<v30-3-6,6>>^ Quando a trombeta soa o alarme, o povo não fica assustado? Acaso a calamidade sobrevém a uma cidade sem que o SENHOR a tenha planejado?

[[v30-3-7]]

^<<v30-3-7,7>>^ Certamente o SENHOR Soberano não fará coisa alguma sem antes revelar seu plano a seus servos, os profetas.

[[v30-3-8]]

^<<v30-3-8,8>>^ O leão rugiu, quem não temerá? O SENHOR Soberano falou, quem não profetizará?

[[v30-3-9]]

^<<v30-3-9,9>>^ Anunciem aos líderes da Filístia e aos poderosos do Egito: "Reúnam-se nas colinas ao redor de Samaria e sejam testemunhas do caos e da opressão em Israel".

[[v30-3-10]]

^<<v30-3-10,10>>^ "Meu povo esqueceu como fazer o que é certo", diz o SENHOR. "Suas fortalezas estão cheias de bens obtidos por meio de roubo e violência.

[[v30-3-11]]

^<<v30-3-11,11>>^ Por isso", diz o SENHOR Soberano, "um inimigo se aproxima. Ele os cercará e acabará com suas defesas, e depois saqueará suas fortalezas."

[[v30-3-12]]

^<<v30-3-12,12>>^ Assim diz o SENHOR: "Como o pastor que tenta arrancar uma ovelha da boca do leão e só consegue recuperar duas pernas ou um pedaço da orelha, assim será o destino dos israelitas em Samaria, deitados em camas luxuosas e recostados em sofás com lençóis de Damasco.

[[v30-3-13]]

^<<v30-3-13,13>>^ "Agora ouçam estas palavras e anunciem-nas em todo o Israel", diz o SENHOR Soberano, o Deus dos Exércitos.

[[v30-3-14]]

^<<v30-3-14,14>>^ "No mesmo dia em que eu castigar Israel por seus pecados, destruirei os altares idólatras em Betel. As pontas do altar serão cortadas e cairão no chão.

[[v30-3-15]]

^<<v30-3-15,15>>^ Destruirei as belas casas dos ricos, suas mansões de inverno e suas residências de verão, todos os seus palácios cheios de marfim", diz o SENHOR.

'''

xref:030-amos/030-amos-002.adoc#v30-2-0[&#60; Capítulo Anterior] | <<v30-3-0,Topo>> | xref:030-amos/030-amos-004.adoc#v30-4-0[Próximo Capítulo &#62;]