include::./index.adoc[]

[[v30-9-0]]
=== Amós, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v30-9-1]]

^<<v30-9-1,1>>^ Então vi o Senhor em pé junto ao altar. Ele disse: "Golpeie o alto das colunas do templo, para que os alicerces tremam. Derrube o telhado sobre a cabeça do povo que estiver embaixo. Matarei à espada os que sobreviverem; ninguém escapará!

[[v30-9-2]]

^<<v30-9-2,2>>^ "Ainda que cavem até o lugar dos mortos, estenderei a mão e os arrancarei de lá. Ainda que subam até os céus, os farei descer.

[[v30-9-3]]

^<<v30-9-3,3>>^ Ainda que se escondam no topo do monte Carmelo, os buscarei e de lá os tirarei. Ainda que se escondam no fundo do mar, enviarei a serpente marinha para que os morda.

[[v30-9-4]]

^<<v30-9-4,4>>^ Ainda que seus inimigos os levem para o exílio, ordenarei que a espada os mate ali. Estou decidido a trazer calamidade sobre eles, e não o bem".

[[v30-9-5]]

^<<v30-9-5,5>>^ O Soberano SENHOR dos Exércitos toca a terra e ela se derrete, e todos que nela habitam lamentam. A terra se levanta como o Nilo, o rio do Egito, na época das enchentes e depois afunda.

[[v30-9-6]]

^<<v30-9-6,6>>^ O SENHOR constrói sua casa até os céus e estabelece seus alicerces sobre a terra. Ele tira água dos oceanos e a derrama sobre a terra; SENHOR é o seu nome!

[[v30-9-7]]

^<<v30-9-7,7>>^ "Acaso vocês, israelitas, são mais importantes para mim que os etíopes?", diz o SENHOR. "Tirei Israel do Egito, mas também tirei os filisteus de Creta e os sírios de Quir.

[[v30-9-8]]

^<<v30-9-8,8>>^ "Eu, o SENHOR Soberano, vigio a nação pecaminosa de Israel. Eu a varrerei da face da terra, mas jamais destruirei por completo o povo de Israel", diz o SENHOR.

[[v30-9-9]]

^<<v30-9-9,9>>^ "Pois darei ordens e sacudirei Israel com as outras nações, como o trigo é sacudido na peneira; mas nenhum grão se perderá.

[[v30-9-10]]

^<<v30-9-10,10>>^ Todos os pecadores, porém, morrerão pela espada, todos que dizem: ‘Nenhuma calamidade virá sobre nós."

[[v30-9-11]]

^<<v30-9-11,11>>^ "Naquele dia, restaurarei a tenda caída de Davi e consertarei seus muros quebrados. Das ruínas a reconstruirei e restaurarei sua antiga glória.

[[v30-9-12]]

^<<v30-9-12,12>>^ Israel possuirá o que restar de Edom e de todas as nações que chamei para serem minhas". O SENHOR falou e fará essas coisas.

[[v30-9-13]]

^<<v30-9-13,13>>^ "Virá o tempo", diz o SENHOR, "em que o trigo e as uvas crescerão tão rápido que o povo não dará conta de colhê-los. Vinho doce gotejará das videiras no alto das colinas de Israel.

[[v30-9-14]]

^<<v30-9-14,14>>^ Trarei meu povo exilado de Israel de volta de terras distantes, e eles reconstruirão as cidades destruídas e voltarão a morar nelas. Plantarão vinhedos e jardins, comerão de suas colheitas e beberão de seu vinho.

[[v30-9-15]]

^<<v30-9-15,15>>^ Eu os plantarei firmemente ali, em sua própria terra. Nunca mais serão arrancados da terra que lhes dei", diz o SENHOR, seu Deus.

'''

xref:030-amos/030-amos-008.adoc#v30-8-0[&#60; Capítulo Anterior] | <<v30-9-0,Topo>> | xref:031-obadias/031-obadias-001.adoc#v31-1-0[Próximo Capítulo &#62;]