include::./index.adoc[]

[[v30-7-0]]
=== Amós, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v30-7-1]]

^<<v30-7-1,1>>^ Foi isto que o SENHOR Soberano me mostrou numa visão: ele se preparava para enviar sobre a terra um exército de gafanhotos. Isso foi depois que a porção do rei havia sido colhida dos campos, quando brotava a colheita principal.

[[v30-7-2]]

^<<v30-7-2,2>>^ Em minha visão, os gafanhotos comeram todas as plantas da terra. Então eu disse: "Ó SENHOR Soberano, perdoa-nos! Do contrário, não sobreviveremos, pois Israel é muito pequeno".

[[v30-7-3]]

^<<v30-7-3,3>>^ Então o SENHOR voltou atrás e disse: "O que você viu não acontecerá".

[[v30-7-4]]

^<<v30-7-4,4>>^ Foi isto que o SENHOR Soberano me mostrou em outra visão: ele se preparava para castigar seu povo com um grande fogo. O fogo havia consumido as profundezas do mar e devorava toda a terra.

[[v30-7-5]]

^<<v30-7-5,5>>^ Então eu disse: "Ó SENHOR Soberano, imploro-te que pares. Do contrário, não sobreviveremos, pois Israel é muito pequeno".

[[v30-7-6]]

^<<v30-7-6,6>>^ Então o SENHOR Soberano voltou atrás e disse: "Isso também não acontecerá".

[[v30-7-7]]

^<<v30-7-7,7>>^ Foi isto que ele me mostrou em outra visão: o Senhor estava em pé, junto a um muro que havia sido construído usando-se um prumo, e segurava o prumo em sua mão.

[[v30-7-8]]

^<<v30-7-8,8>>^ O SENHOR me perguntou: "Amós, o que você vê?". Respondi: "Um prumo". Então o Senhor disse: "Provarei meu povo com este prumo. Não fecharei mais os olhos para o que fazem.

[[v30-7-9]]

^<<v30-7-9,9>>^ Os santuários idólatras de seus antepassados ficarão em ruínas, e os lugares de adoração de Israel serão destruídos; trarei a espada contra a dinastia de Jeroboão".

[[v30-7-10]]

^<<v30-7-10,10>>^ Então Amazias, sacerdote de Betel, enviou uma mensagem a Jeroboão, rei de Israel: "Amós conspira contra o rei aqui mesmo, no meio do povo, falando coisas intoleráveis!

[[v30-7-11]]

^<<v30-7-11,11>>^ Assim diz ele: ‘Em breve Jeroboão será morto pela espada, e o povo de Israel será enviado para o exílio’".

[[v30-7-12]]

^<<v30-7-12,12>>^ Então Amazias ordenou a Amós: "Vá embora daqui, profeta! Volte para a terra de Judá e ganhe a vida profetizando ali!

[[v30-7-13]]

^<<v30-7-13,13>>^ Não nos incomode com suas profecias aqui em Betel. Este é o santuário do rei e o lugar de adoração de todo o reino!".

[[v30-7-14]]

^<<v30-7-14,14>>^ Amós respondeu: "Não sou profeta e nunca fui treinado para ser profeta. Sou apenas um boiadeiro e colhedor de figos.

[[v30-7-15]]

^<<v30-7-15,15>>^ Mas o SENHOR me tirou de junto de meu rebanho e disse: ‘Vá e profetize a meu povo, Israel’.

[[v30-7-16]]

^<<v30-7-16,16>>^ Agora, portanto, ouça esta mensagem do SENHOR: "Você diz: ‘Não profetize contra Israel; pare de pregar contra meu povo’.

[[v30-7-17]]

^<<v30-7-17,17>>^ Mas assim diz o SENHOR: ‘Sua esposa se tornará prostituta nesta cidade, e seus filhos e filhas serão mortos pela espada. Sua terra será dividida, e você morrerá em terra estrangeira. E o povo de Israel certamente será levado para o exílio, para longe de sua terra natal’".

'''

xref:030-amos/030-amos-006.adoc#v30-6-0[&#60; Capítulo Anterior] | <<v30-7-0,Topo>> | xref:030-amos/030-amos-008.adoc#v30-8-0[Próximo Capítulo &#62;]