include::./index.adoc[]

[[v66-5-0]]
=== Apocalipse, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v66-5-1]]

^<<v66-5-1,1>>^ Então, na mão direita daquele que estava sentado no trono, vi um livro, escrito por dentro e por fora e lacrado com sete selos.

[[v66-5-2]]

^<<v66-5-2,2>>^ Vi um anjo poderoso que perguntava em alta voz: "Quem é digno de romper os selos deste livro e abri-lo?".

[[v66-5-3]]

^<<v66-5-3,3>>^ Mas não havia ninguém no céu, nem na terra, nem debaixo da terra, que pudesse abrir o livro e lê-lo.

[[v66-5-4]]

^<<v66-5-4,4>>^ Comecei a chorar muito, pois não se encontrou ninguém digno de abrir o livro e lê-lo.

[[v66-5-5]]

^<<v66-5-5,5>>^ Então um dos 24 anciãos me disse: "Não chore! Veja, o Leão da tribo de Judá, o herdeiro do trono de Davi, conquistou a vitória. Ele é digno de abrir o livro e os setes selos".

[[v66-5-6]]

^<<v66-5-6,6>>^ Então vi um Cordeiro que parecia ter sido sacrificado, mas que agora estava em pé entre o trono e os quatro seres vivos e no meio dos 24 anciãos. Tinha sete chifres e sete olhos, que representam os sete espíritos de Deus enviados a todas as partes da terra.

[[v66-5-7]]

^<<v66-5-7,7>>^ Ele deu um passo à frente e recebeu o livro da mão direita daquele que está sentado no trono.

[[v66-5-8]]

^<<v66-5-8,8>>^ Quando o Cordeiro recebeu o livro, os quatro seres vivos e os 24 anciãos se prostraram diante dele. Cada um tinha uma harpa e taças de ouro cheias de incenso, que são as orações do povo santo,

[[v66-5-9]]

^<<v66-5-9,9>>^ e entoavam um cântico novo com estas palavras: "Tu és digno de receber o livro, abrir os selos e lê-lo. Pois foste sacrificado e com teu sangue compraste para Deus pessoas de toda tribo, língua, povo e nação.

[[v66-5-10]]

^<<v66-5-10,10>>^ Tu fizeste delas um reino de sacerdotes para nosso Deus, e elas reinarão sobre a terra".

[[v66-5-11]]

^<<v66-5-11,11>>^ Então olhei novamente e ouvi as vozes de milhares e milhões de anjos ao redor do trono, e também dos seres vivos e dos anciãos.

[[v66-5-12]]

^<<v66-5-12,12>>^ Cantavam com forte voz: "Digno é o Cordeiro que foi sacrificado de receber poder e riqueza, sabedoria e força, honra, glória e louvor!".

[[v66-5-13]]

^<<v66-5-13,13>>^ Depois, ouvi todas as criaturas no céu, na terra, debaixo da terra e no mar, cantarem: "Louvor e honra, glória e poder pertencem àquele que está sentado no trono e ao Cordeiro para todo o sempre!".

[[v66-5-14]]

^<<v66-5-14,14>>^ E os quatro seres vivos disseram: "Amém!". E os 24 anciãos se prostraram e adoraram.

'''

xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[&#60; Capítulo Anterior] | <<v66-5-0,Topo>> | xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[Próximo Capítulo &#62;]