include::./index.adoc[]

[[v66-6-0]]
=== Apocalipse, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v66-6-1]]

^<<v66-6-1,1>>^ Enquanto eu observava, o Cordeiro abriu o primeiro dos sete selos do livro. Então ouvi um dos quatro seres vivos dizer com voz de trovão: "Venha!".

[[v66-6-2]]

^<<v66-6-2,2>>^ Quando olhei, vi um cavalo branco. Seu cavaleiro carregava um arco, e sobre sua cabeça foi colocada uma coroa. Ele saiu batalhando para conquistar vitórias.

[[v66-6-3]]

^<<v66-6-3,3>>^ Quando o Cordeiro abriu o segundo selo, ouvi o segundo ser vivo dizer: "Venha!".

[[v66-6-4]]

^<<v66-6-4,4>>^ Então surgiu um cavalo vermelho. Seu cavaleiro recebeu uma grande espada e autoridade para tirar a paz da terra. E houve guerra e matança em toda parte.

[[v66-6-5]]

^<<v66-6-5,5>>^ Quando o Cordeiro abriu o terceiro selo, ouvi o terceiro ser vivo dizer: "Venha!". Quando olhei, vi um cavalo preto. Seu cavaleiro tinha na mão uma balança.

[[v66-6-6]]

^<<v66-6-6,6>>^ E ouvi uma voz dentre os quatro seres vivos dizer: "Uma medida de trigo ou três medidas de cevada custarão o salário de um dia, mas não desperdice o azeite nem o vinho".

[[v66-6-7]]

^<<v66-6-7,7>>^ Quando o Cordeiro abriu o quarto selo, ouvi o quarto ser vivo dizer: "Venha!".

[[v66-6-8]]

^<<v66-6-8,8>>^ Quando olhei, vi um cavalo amarelo. Seu cavaleiro se chamava Morte, e o mundo dos mortos o seguia. Eles receberam autoridade sobre um quarto da terra para matar pela espada, pela fome e pela doença e por meio de animais selvagens.

[[v66-6-9]]

^<<v66-6-9,9>>^ Quando o Cordeiro abriu o quinto selo, vi sob o altar as almas de todos que haviam sido mortos por causa da palavra de Deus e por seu testemunho fiel.

[[v66-6-10]]

^<<v66-6-10,10>>^ Clamavam ao Senhor em alta voz e diziam: "Ó Soberano Senhor, santo e verdadeiro, quanto tempo passará até que julgues os habitantes da terra e vingues nosso sangue?".

[[v66-6-11]]

^<<v66-6-11,11>>^ Então a cada um deles foi dada uma veste branca, e lhes foi dito que descansassem mais um pouco até que se completasse o número de seus irmãos, seus companheiros no serviço, que se juntariam a eles depois de serem mortos.

[[v66-6-12]]

^<<v66-6-12,12>>^ Enquanto eu observava, o Cordeiro abriu o sexto selo, e houve um grande terremoto. O sol ficou escuro como pano negro, e a lua inteira se tornou vermelha como sangue.

[[v66-6-13]]

^<<v66-6-13,13>>^ Então as estrelas caíram do céu como figos verdes de uma figueira sacudida por um forte vento.

[[v66-6-14]]

^<<v66-6-14,14>>^ O céu foi enrolado como pergaminho, e todas as montanhas e ilhas foram movidas de seu lugar.

[[v66-6-15]]

^<<v66-6-15,15>>^ Então os reis da terra, os governantes, os generais, os ricos, os poderosos, os escravos e os livres, todos se esconderam em cavernas e entre as rochas das montanhas.

[[v66-6-16]]

^<<v66-6-16,16>>^ E gritavam às montanhas e às rochas: "Caiam sobre nós e escondam-nos da face daquele que está sentado no trono e da ira do Cordeiro!

[[v66-6-17]]

^<<v66-6-17,17>>^ Pois chegou o grande dia de sua ira, e quem poderá sobreviver?".

'''

xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[&#60; Capítulo Anterior] | <<v66-6-0,Topo>> | xref:066-apocalipse/066-apocalipse-007.adoc#v66-7-0[Próximo Capítulo &#62;]