include::./index.adoc[]

[[v66-18-0]]
=== Apocalipse, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v66-18-1]]

^<<v66-18-1,1>>^ Depois disso, vi outro anjo descer do céu com grande autoridade, e a terra se iluminou com seu esplendor.

[[v66-18-2]]

^<<v66-18-2,2>>^ Ele deu um forte grito: "Caiu a Babilônia! A grande cidade caiu! Tornou-se habitação de demônios, esconderijo de todo espírito impuro, covil de toda ave impura e de todo animal impuro e detestável.

[[v66-18-3]]

^<<v66-18-3,3>>^ Porque todas as nações caíram por causa do vinho da fúria de sua imoralidade. Os reis da terra cometeram adultério com ela. Por ela tanto desejar luxo extravagante, os comerciantes da terra enriqueceram".

[[v66-18-4]]

^<<v66-18-4,4>>^ Então ouvi outra voz do céu, que disse: "Saiam dela, meu povo! Não participem de seus pecados, ou serão castigados com ela.

[[v66-18-5]]

^<<v66-18-5,5>>^ Pois os pecados dela se amontoaram até o céu, e Deus se lembrou de seus atos perversos.

[[v66-18-6]]

^<<v66-18-6,6>>^ Façam com ela o que ela tem feito; deem-lhe em dobro o castigo por seus atos. Ela preparou um cálice de terror para os outros, por isso preparem-lhe uma porção dobrada.

[[v66-18-7]]

^<<v66-18-7,7>>^ Glorificou a si mesma e viveu em luxo, agora retribuam com igual quantidade de tormento e tristeza. Ela se vangloriou em seu coração: ‘Sou rainha em meu trono. Não sou uma viúva desamparada, e não tenho motivo para me lamentar’.

[[v66-18-8]]

^<<v66-18-8,8>>^ Por isso, estas pragas a alcançarão num só dia: morte, pranto e fome. O fogo a consumirá por completo, pois o Senhor Deus, que a julga, é poderoso".

[[v66-18-9]]

^<<v66-18-9,9>>^ Os reis da terra que cometeram adultério com ela e desfrutaram seu luxo lamentarão por ela quando virem subir a fumaça de seus restos carbonizados.

[[v66-18-10]]

^<<v66-18-10,10>>^ Ficarão de longe, aterrorizados com seu tormento, e clamarão: "Que terrível, que terrível, ó Babilônia, grande cidade! Num só instante, o julgamento caiu sobre você!".

[[v66-18-11]]

^<<v66-18-11,11>>^ Os comerciantes da terra chorarão e lamentarão por ela, pois não restou ninguém para comprar suas mercadorias.

[[v66-18-12]]

^<<v66-18-12,12>>^ Ela comprava grandes quantidades de ouro, prata, joias e pérolas; linho fino, púrpura, seda e tecido vermelho; produtos feitos de perfumada madeira de cedro, de marfim e de madeira preciosa; bronze, ferro e mármore.

[[v66-18-13]]

^<<v66-18-13,13>>^ Também comprava canela, especiarias, incenso, mirra, bálsamo, vinho, azeite de oliva, farinha fina, trigo, gado, ovelhas, cavalos, carroças, escravos e vidas humanas.

[[v66-18-14]]

^<<v66-18-14,14>>^ "Acabaram as coisas extravagantes de que você tanto gostava", dizem eles. "Todo o seu luxo e esplendor se foram para sempre, e nunca mais serão seus."

[[v66-18-15]]

^<<v66-18-15,15>>^ Os comerciantes que enriqueceram vendendo-lhe essas coisas ficarão de longe, aterrorizados com seu tormento. Chorarão e clamarão:

[[v66-18-16]]

^<<v66-18-16,16>>^ "Que terrível, que terrível para essa grande cidade! Ela se vestia da mais fina púrpura e de linho vermelho, adornada com ouro, pedras preciosas e pérolas!

[[v66-18-17]]

^<<v66-18-17,17>>^ Num só instante, toda a sua riqueza se foi!". E todos os capitães dos navios mercantes, e também seus passageiros, marinheiros e tripulantes, ficarão de longe.

[[v66-18-18]]

^<<v66-18-18,18>>^ Quando virem subir a fumaça, gritarão e dirão: "Onde há outra cidade tão grande como essa?".

[[v66-18-19]]

^<<v66-18-19,19>>^ Chorarão, jogarão pó sobre a cabeça e clamarão: "Que terrível, que terrível para essa grande cidade! Os donos dos navios se enriqueceram, transportando pelos mares sua imensa riqueza. Num só instante, tudo se foi!".

[[v66-18-20]]

^<<v66-18-20,20>>^ Alegrem-se com o destino dela, ó céus, ó povo santo, apóstolos e profetas! Porque finalmente Deus a julgou, por causa de vocês.

[[v66-18-21]]

^<<v66-18-21,21>>^ Então um anjo poderoso levantou uma pedra enorme, do tamanho de uma grande pedra de moinho, a lançou no mar e gritou: "Assim, Babilônia, a grande cidade, será derrubada com violência e nunca mais será encontrada!

[[v66-18-22]]

^<<v66-18-22,22>>^ Nunca mais se ouvirá em seu meio o som de harpas, cantores, flautas e trombetas. Nunca mais se achará em seu meio qualquer artífice em algum ofício. Nunca mais se ouvirá em seu meio o som do moinho.

[[v66-18-23]]

^<<v66-18-23,23>>^ Nunca mais brilhará em seu meio a luz da lâmpada. Nunca mais se ouvirão em seu meio as vozes alegres de noivas e noivos. Pois seus comerciantes eram os poderosos do mundo, e suas feitiçarias enganavam nações.

[[v66-18-24]]

^<<v66-18-24,24>>^ Em suas ruas corria o sangue de profetas e do povo santo, e o sangue dos que no mundo inteiro foram mortos".

'''

xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[&#60; Capítulo Anterior] | <<v66-18-0,Topo>> | xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[Próximo Capítulo &#62;]