include::./index.adoc[]

[[v66-17-0]]
=== Apocalipse, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v66-17-1]]

^<<v66-17-1,1>>^ Um dos sete anjos que derramaram as sete taças se aproximou e disse: "Venha comigo, e eu lhe mostrarei o julgamento da grande prostituta que governa sobre muitas águas.

[[v66-17-2]]

^<<v66-17-2,2>>^ Os reis da terra cometeram adultério com ela, e os habitantes da terra se embriagaram com o vinho de sua imoralidade".

[[v66-17-3]]

^<<v66-17-3,3>>^ Então o anjo me levou no Espírito para o deserto, onde vi uma mulher montada numa besta vermelha, coberta de blasfêmias e com sete cabeças e dez chifres.

[[v66-17-4]]

^<<v66-17-4,4>>^ A mulher estava vestida de púrpura e vermelho e enfeitada com joias de ouro, pedras preciosas e pérolas. Tinha na mão um cálice de ouro cheio de abominações e das impurezas de sua imoralidade.

[[v66-17-5]]

^<<v66-17-5,5>>^ Em sua testa estava escrito um nome misterioso: "Babilônia, a Grande, a Mãe das Prostitutas e das Abominações da Terra".

[[v66-17-6]]

^<<v66-17-6,6>>^ Vi que ela estava embriagada com o sangue do povo santo, o sangue das testemunhas de Jesus. Tomado de espanto, olhei fixamente para ela.

[[v66-17-7]]

^<<v66-17-7,7>>^ "Por que você está tão espantado?", o anjo perguntou. "Eu lhe explicarei o mistério desta mulher e da besta com sete cabeças e dez chifres na qual ela está montada.

[[v66-17-8]]

^<<v66-17-8,8>>^ A besta que você viu esteve viva, mas agora não está mais. E, no entanto, em breve subirá do abismo e irá para a destruição. Os habitantes da terra, cujos nomes não foram escritos no Livro da Vida desde a criação do mundo, ficarão admirados com o reaparecimento da besta que havia morrido.

[[v66-17-9]]

^<<v66-17-9,9>>^ "Aqui é preciso pensar com sabedoria. As sete cabeças da besta representam os sete montes onde a mulher governa, e também representam sete reis.

[[v66-17-10]]

^<<v66-17-10,10>>^ Cinco deles já caíram, o sexto está governando e o sétimo ainda não veio, mas seu reinado será breve.

[[v66-17-11]]

^<<v66-17-11,11>>^ "A besta que esteve viva, mas agora não está mais, é o oitavo rei. É como os outros sete, e também caminha para a destruição.

[[v66-17-12]]

^<<v66-17-12,12>>^ Os dez chifres da besta são dez reis que ainda não subiram ao poder. Serão nomeados para seus reinos por um breve período, para reinarem com a besta,

[[v66-17-13]]

^<<v66-17-13,13>>^ e concordarão em entregar a ela seu poder e sua autoridade.

[[v66-17-14]]

^<<v66-17-14,14>>^ Juntos, guerrearão contra o Cordeiro, mas o Cordeiro os derrotará, pois é Senhor dos senhores e Rei dos reis. E com ele estarão seus chamados, escolhidos e fiéis."

[[v66-17-15]]

^<<v66-17-15,15>>^ Em seguida, o anjo me disse: "As águas que você viu, onde a prostituta governa, representam multidões de todas as nações e línguas.

[[v66-17-16]]

^<<v66-17-16,16>>^ A besta e os dez chifres que você viu odiarão a prostituta. Eles a deixarão nua, comerão sua carne e destruirão o restante com fogo.

[[v66-17-17]]

^<<v66-17-17,17>>^ Porque Deus colocou no coração deles um plano que executará sua vontade. Eles concordarão em entregar a autoridade à besta, cumprindo-se assim as palavras de Deus.

[[v66-17-18]]

^<<v66-17-18,18>>^ E a mulher que você viu representa a grande cidade que governa sobre os reis da terra".

'''

xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[Próximo Capítulo &#62;]