include::./index.adoc[]

[[v66-2-0]]
=== Apocalipse, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v66-2-1]]

^<<v66-2-1,1>>^ "Escreva esta carta ao anjo da igreja em Éfeso. Esta é a mensagem daquele que segura na mão direita as sete estrelas, daquele que anda entre os sete candelabros de ouro:

[[v66-2-2]]

^<<v66-2-2,2>>^ "Sei de tudo que você faz. Vi seu trabalho árduo e sua perseverança, e sei que não tolera os perversos. Examinou as pretensões dos que se dizem apóstolos, mas não são, e descobriu que são mentirosos.

[[v66-2-3]]

^<<v66-2-3,3>>^ Sofreu por meu nome com paciência, sem desistir.

[[v66-2-4]]

^<<v66-2-4,4>>^ "Contudo, tenho contra você uma queixa: você abandonou o amor que tinha no princípio.

[[v66-2-5]]

^<<v66-2-5,5>>^ Veja até onde você caiu! Arrependa-se e volte a praticar as obras que no início praticava. Do contrário, virei até você e tirarei seu candelabro de seu lugar entre as igrejas.

[[v66-2-6]]

^<<v66-2-6,6>>^ Mas há isto a seu favor: você odeia as obras dos nicolaítas, como eu também odeio.

[[v66-2-7]]

^<<v66-2-7,7>>^ "Quem tem ouvidos para ouvir, ouça o que o Espírito diz às igrejas. Ao vitorioso, darei o fruto da árvore da vida que está no paraíso de Deus."

[[v66-2-8]]

^<<v66-2-8,8>>^ "Escreva esta carta ao anjo da igreja em Esmirna. Esta é a mensagem daquele que é o Primeiro e o Último, que esteve morto mas agora vive:

[[v66-2-9]]

^<<v66-2-9,9>>^ "Conheço suas aflições e sua pobreza, mas você é rico. Sei da blasfêmia dos que se opõem a você. Eles se dizem judeus, mas não são, pois a sinagoga deles pertence a Satanás.

[[v66-2-10]]

^<<v66-2-10,10>>^ Não tenha medo do que está prestes a sofrer. O diabo lançará alguns de vocês na prisão a fim de prová-los, e terão aflições por dez dias. Mas, se você permanecer fiel mesmo diante da morte, eu lhe darei a coroa da vida.

[[v66-2-11]]

^<<v66-2-11,11>>^ "Quem tem ouvidos para ouvir, ouça o que o Espírito diz às igrejas. Quem for vitorioso não sofrerá o dano da segunda morte."

[[v66-2-12]]

^<<v66-2-12,12>>^ "Escreva esta carta ao anjo da igreja em Pérgamo. Esta é a mensagem daquele que tem a espada afiada dos dois lados:

[[v66-2-13]]

^<<v66-2-13,13>>^ "Conheço o lugar onde você vive, a cidade onde está o trono de Satanás. Ainda assim, você permanece leal a meu nome. Recusou-se a negar sua fé em mim até mesmo quando Antipas, minha testemunha fiel, foi morto onde vocês vivem, o lugar de habitação de Satanás.

[[v66-2-14]]

^<<v66-2-14,14>>^ "Contudo, tenho contra você algumas queixas. Você tolera em seu meio pessoas cujo ensino é semelhante ao de Balaão, que mostrou a Balaque como fazer o povo de Israel tropeçar. Ele os instigou a comer alimentos oferecidos a ídolos e a praticar imoralidade sexual.

[[v66-2-15]]

^<<v66-2-15,15>>^ De igual modo, há entre vocês alguns que seguem o ensino dos nicolaítas.

[[v66-2-16]]

^<<v66-2-16,16>>^ Portanto, arrependa-se ou virei subitamente até você e lutarei contra eles com a espada de minha boca.

[[v66-2-17]]

^<<v66-2-17,17>>^ "Quem tem ouvidos para ouvir, ouça o que o Espírito diz às igrejas. Ao vitorioso, darei do maná escondido. Também lhe darei uma pedra branca, e nela estará gravado um nome novo, que ninguém conhece, a não ser aquele que o recebe."

[[v66-2-18]]

^<<v66-2-18,18>>^ "Escreva esta carta ao anjo da igreja em Tiatira. Esta é a mensagem do Filho de Deus, cujos olhos são como chamas de fogo e cujos pés são como bronze polido:

[[v66-2-19]]

^<<v66-2-19,19>>^ "Sei de tudo que você faz. Vi seu amor, sua fé, seu serviço e sua perseverança, e observei como você tem crescido em todas essas coisas.

[[v66-2-20]]

^<<v66-2-20,20>>^ "Contudo, tenho contra você uma queixa. Você tem permitido que essa mulher, Jezabel, que se diz profetisa, faça meus servos se desviarem. Ela os ensina a cometer imoralidade sexual e a comer alimentos oferecidos a ídolos.

[[v66-2-21]]

^<<v66-2-21,21>>^ Dei a ela tempo para que se arrependesse, mas não quer se arrepender de sua imoralidade.

[[v66-2-22]]

^<<v66-2-22,22>>^ "Portanto, eu a lançarei doente numa cama, e aqueles que cometerem adultério com ela sofrerão terrivelmente, a menos que se arrependam e abandonem a prática de tais atos.

[[v66-2-23]]

^<<v66-2-23,23>>^ Matarei seus filhos, e então todas as igrejas saberão que eu sou aquele que sonda mente e coração. Darei a cada um de vocês aquilo que seus atos merecem.

[[v66-2-24]]

^<<v66-2-24,24>>^ "Tenho também uma mensagem para o restante de vocês em Tiatira que não seguiram esse falso ensino (‘as verdades mais profundas’, como eles dizem, e que na realidade vêm de Satanás). Não lhes pedirei coisa alguma,

[[v66-2-25]]

^<<v66-2-25,25>>^ senão que se apeguem firmemente ao que já têm até que eu venha.

[[v66-2-26]]

^<<v66-2-26,26>>^ Ao vitorioso que me obedecer até o fim, Eu darei autoridade sobre as nações.

[[v66-2-27]]

^<<v66-2-27,27>>^ Ele as governará com cetro de ferro e as despedaçará como vasos de barro.

[[v66-2-28]]

^<<v66-2-28,28>>^ Ele terá a mesma autoridade que recebi de meu Pai, e também lhe darei a estrela da manhã.

[[v66-2-29]]

^<<v66-2-29,29>>^ "Quem tem ouvidos para ouvir, ouça o que o Espírito diz às igrejas."

'''

xref:066-apocalipse/066-apocalipse-001.adoc#v66-1-0[&#60; Capítulo Anterior] | <<v66-2-0,Topo>> | xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[Próximo Capítulo &#62;]