include::./index.adoc[]

[[v66-15-0]]
=== Apocalipse, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v66-15-1]]

^<<v66-15-1,1>>^ Vi no céu outro sinal grande e maravilhoso. Sete anjos seguravam as últimas sete pragas que completariam a fúria de Deus.

[[v66-15-2]]

^<<v66-15-2,2>>^ Vi diante de mim algo semelhante a um mar de vidro misturado com fogo. Nele estavam em pé todos os que haviam vencido a besta, sua estátua e o número que representa seu nome. Todos seguravam harpas que Deus lhes tinha dado

[[v66-15-3]]

^<<v66-15-3,3>>^ e entoavam o cântico de Moisés, servo de Deus, e o cântico do Cordeiro: "Grandes e maravilhosas são as tuas obras, ó Senhor Deus, o Todo-poderoso. Justos e verdadeiros são os teus caminhos, ó Rei das nações.

[[v66-15-4]]

^<<v66-15-4,4>>^ Quem não te temerá, Senhor? Quem não glorificará teu nome? Pois só tu és santo. Todas as nações virão e adorarão diante de ti, pois teus feitos de justiça foram revelados".

[[v66-15-5]]

^<<v66-15-5,5>>^ Então olhei e vi que se abriu o templo no céu, o tabernáculo da aliança.

[[v66-15-6]]

^<<v66-15-6,6>>^ Os sete anjos que seguravam as sete pragas saíram do templo. Vestiam linho branco, sem mancha alguma, com uma faixa de ouro sobre o peito.

[[v66-15-7]]

^<<v66-15-7,7>>^ Um dos quatro seres vivos entregou a cada um dos sete anjos uma taça de ouro cheia da fúria de Deus, que vive para todo o sempre.

[[v66-15-8]]

^<<v66-15-8,8>>^ O templo se encheu da fumaça da glória e do poder de Deus, e ninguém podia entrar no templo enquanto os anjos não tivessem terminado de derramar as sete pragas.

'''

xref:066-apocalipse/066-apocalipse-014.adoc#v66-14-0[&#60; Capítulo Anterior] | <<v66-15-0,Topo>> | xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[Próximo Capítulo &#62;]