include::./index.adoc[]

[[v66-7-0]]
=== Apocalipse, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v66-7-1]]

^<<v66-7-1,1>>^ Então vi quatro anjos em pé nos quatro cantos da terra, impedindo os quatro ventos de soprarem na terra, no mar e em qualquer árvore.

[[v66-7-2]]

^<<v66-7-2,2>>^ E vi outro anjo que subia do leste e trazia o selo do Deus vivo. Ele gritou aos quatro anjos que haviam recebido poder para danificar a terra e o mar:

[[v66-7-3]]

^<<v66-7-3,3>>^ "Esperem! Não façam mal à terra, nem ao mar, nem às árvores, até que tenhamos colocado o selo de Deus na testa de seus servos".

[[v66-7-4]]

^<<v66-7-4,4>>^ E ouvi o número dos que foram marcados com o selo de Deus. Eram 144 mil, de todas as tribos de Israel:

[[v66-7-5]]

^<<v66-7-5,5>>^ da tribo de Judá, foram selados doze mil, da tribo de Rúben, doze mil, da tribo de Gade, doze mil,

[[v66-7-6]]

^<<v66-7-6,6>>^ da tribo de Aser, doze mil, da tribo de Naftali, doze mil, da tribo de Manassés, doze mil,

[[v66-7-7]]

^<<v66-7-7,7>>^ da tribo de Simeão, doze mil, da tribo de Levi, doze mil, da tribo de Issacar, doze mil,

[[v66-7-8]]

^<<v66-7-8,8>>^ da tribo de Zebulom, doze mil, da tribo de José, doze mil, da tribo de Benjamim, foram selados doze mil.

[[v66-7-9]]

^<<v66-7-9,9>>^ Depois disso, vi uma imensa multidão, grande demais para ser contada, de todas as nações, tribos, povos e línguas, em pé diante do trono e diante do Cordeiro. Usavam vestes brancas e seguravam ramos de palmeiras.

[[v66-7-10]]

^<<v66-7-10,10>>^ E gritavam com grande estrondo: "A salvação vem de nosso Deus, que está sentado no trono, e do Cordeiro!".

[[v66-7-11]]

^<<v66-7-11,11>>^ E todos os anjos estavam em pé ao redor do trono, dos anciãos e dos quatro seres vivos. Prostraram-se com o rosto em terra diante do trono e adoraram a Deus,

[[v66-7-12]]

^<<v66-7-12,12>>^ cantando: "Amém! Louvor e glória e sabedoria, gratidão e honra, força e poder pertencem a nosso Deus, para todo o sempre. Amém!".

[[v66-7-13]]

^<<v66-7-13,13>>^ Então um dos anciãos me perguntou: "Quem são estes vestidos de branco? De onde vieram?".

[[v66-7-14]]

^<<v66-7-14,14>>^ Eu lhe respondi: "Senhor, tu sabes". E ele disse: "São aqueles que vieram da grande tribulação. Lavaram e branquearam suas vestes no sangue do Cordeiro.

[[v66-7-15]]

^<<v66-7-15,15>>^ "Por isso estão diante do trono de Deus e dia e noite o servem em seu templo. E aquele que se senta no trono lhes dará abrigo.

[[v66-7-16]]

^<<v66-7-16,16>>^ Nunca mais terão fome, nem sede, e o calor do sol nunca mais os queimará.

[[v66-7-17]]

^<<v66-7-17,17>>^ Pois o Cordeiro que está no centro do trono será seu Pastor. Ele os guiará às fontes de água viva, e Deus enxugará de seus olhos toda lágrima".

'''

xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[&#60; Capítulo Anterior] | <<v66-7-0,Topo>> | xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[Próximo Capítulo &#62;]