include::./index.adoc[]

[[v66-1-0]]
=== Apocalipse, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v66-1-1]]

^<<v66-1-1,1>>^ Revelação de Jesus Cristo, que Deus lhe deu para mostrar a seus servos os acontecimentos que ocorrerão em breve. Ele enviou um anjo para apresentá-la a seu servo João,

[[v66-1-2]]

^<<v66-1-2,2>>^ que relatou fielmente tudo que viu. Este é seu relato da palavra de Deus e do testemunho de Jesus Cristo.

[[v66-1-3]]

^<<v66-1-3,3>>^ Feliz é aquele que lê as palavras desta profecia, e felizes são aqueles que ouvem sua mensagem e obedecem ao que ela diz, pois o tempo está próximo.

[[v66-1-4]]

^<<v66-1-4,4>>^ Eu, João, escrevo às sete igrejas na província da Ásia. Graça e paz a vocês da parte daquele que é, que era e que ainda virá, dos sete espíritos que estão diante de seu trono,

[[v66-1-5]]

^<<v66-1-5,5>>^ e de Jesus Cristo. Ele é a testemunha fiel destas coisas, o primeiro a ressuscitar dos mortos e o governante de todos os reis da terra. Toda a glória seja àquele que nos ama e nos libertou de nossos pecados por meio de seu sangue.

[[v66-1-6]]

^<<v66-1-6,6>>^ Ele fez de nós um reino de sacerdotes para Deus, seu Pai. A ele sejam a glória e o poder para todo o sempre! Amém.

[[v66-1-7]]

^<<v66-1-7,7>>^ Vejam! Ele vem com as nuvens do céu, e todos o verão, até mesmo aqueles que o transpassaram. E todas as nações da terra se lamentarão por causa dele. Sim! Amém!

[[v66-1-8]]

^<<v66-1-8,8>>^ "Eu sou o Alfa e o Ômega", diz o Senhor Deus. "Eu sou aquele que é, que era e que ainda virá, o Todo-poderoso."

[[v66-1-9]]

^<<v66-1-9,9>>^ Eu, João, irmão e companheiro de vocês no sofrimento, no reino e na perseverança para a qual Jesus nos chama, estava exilado na ilha de Patmos por pregar a palavra de Deus e testemunhar a respeito de Jesus.

[[v66-1-10]]

^<<v66-1-10,10>>^ Era o dia do Senhor, e me vi tomado pelo Espírito. De repente, ouvi atrás de mim uma forte voz, como um toque de trombeta,

[[v66-1-11]]

^<<v66-1-11,11>>^ e a voz dizia: "Escreva num livro tudo que você vê e envie-o às sete igrejas nas cidades de Éfeso, Esmirna, Pérgamo, Tiatira, Sardes, Filadélfia e Laodiceia".

[[v66-1-12]]

^<<v66-1-12,12>>^ Quando me voltei para ver quem falava comigo, vi sete candelabros de ouro

[[v66-1-13]]

^<<v66-1-13,13>>^ e, em pé entre eles, havia alguém semelhante ao Filho do Homem. Vestia um manto comprido, com uma faixa de ouro sobre o peito.

[[v66-1-14]]

^<<v66-1-14,14>>^ A cabeça e os cabelos eram brancos como a lã e a neve, e os olhos, como chamas de fogo.

[[v66-1-15]]

^<<v66-1-15,15>>^ Os pés eram como bronze polido, refinado numa fornalha, e a voz ressoava como fortes ondas do mar.

[[v66-1-16]]

^<<v66-1-16,16>>^ Na mão direita tinha sete estrelas, e de sua boca saía uma espada afiada dos dois lados. A face brilhava como o sol em todo o seu esplendor.

[[v66-1-17]]

^<<v66-1-17,17>>^ Quando o vi, caí a seus pés, como morto. Ele, porém, colocou a mão direita sobre mim e disse: "Não tenha medo! Eu sou o Primeiro e o Último.

[[v66-1-18]]

^<<v66-1-18,18>>^ Sou aquele que vive. Estive morto, mas agora vivo para todo o sempre! E tenho as chaves da morte e do mundo dos mortos.

[[v66-1-19]]

^<<v66-1-19,19>>^ "Portanto, escreva o que viu, tanto as coisas que estão acontecendo agora como as que acontecerão depois.

[[v66-1-20]]

^<<v66-1-20,20>>^ Este é o significado do mistério das sete estrelas que você viu em minha mão direita e dos sete candelabros de ouro: as sete estrelas são os anjos das sete igrejas, e os sete candelabros são as sete igrejas."

'''

xref:065-judas/065-judas-001.adoc#v65-1-0[&#60; Capítulo Anterior] | <<v66-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[Próximo Capítulo &#62;]