include::./index.adoc[]

[[v66-8-0]]
=== Apocalipse, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v66-8-1]]

^<<v66-8-1,1>>^ Quando o Cordeiro abriu o sétimo selo, houve silêncio no céu por cerca de meia hora.

[[v66-8-2]]

^<<v66-8-2,2>>^ Vi os sete anjos que estão em pé diante de Deus, e a eles foram dadas sete trombetas.

[[v66-8-3]]

^<<v66-8-3,3>>^ Então veio outro anjo com um incensário de ouro e ficou em pé junto ao altar. Recebeu muito incenso para misturar às orações do povo santo como oferta sobre o altar de ouro diante do trono.

[[v66-8-4]]

^<<v66-8-4,4>>^ A fumaça do incenso, misturada às orações do povo santo, subiu do altar onde o anjo havia derramado o incenso até a presença de Deus.

[[v66-8-5]]

^<<v66-8-5,5>>^ Então o anjo encheu o incensário com fogo do altar e o lançou sobre a terra, e houve trovões, estrondos, relâmpagos e um grande terremoto.

[[v66-8-6]]

^<<v66-8-6,6>>^ Em seguida, os sete anjos com as sete trombetas se prepararam para tocá-las.

[[v66-8-7]]

^<<v66-8-7,7>>^ O primeiro anjo tocou sua trombeta, e foram lançados sobre a terra granizo e fogo misturados com sangue. Um terço da terra pegou fogo, e foi queimado um terço das árvores, além de toda relva verde.

[[v66-8-8]]

^<<v66-8-8,8>>^ O segundo anjo tocou sua trombeta, e foi lançado sobre o mar algo parecido com uma grande montanha em chamas. Um terço da água do mar se transformou em sangue,

[[v66-8-9]]

^<<v66-8-9,9>>^ morreu um terço de todos os seres vivos do mar, e foi destruído um terço de todos os navios.

[[v66-8-10]]

^<<v66-8-10,10>>^ O terceiro anjo tocou sua trombeta, e caiu do céu uma grande estrela, queimando como uma tocha, sobre um terço dos rios e sobre as fontes de água.

[[v66-8-11]]

^<<v66-8-11,11>>^ O nome da estrela era Amargor, pois tornou amargo um terço das águas, e muita gente morreu ao beber dessas águas amargas.

[[v66-8-12]]

^<<v66-8-12,12>>^ O quarto anjo tocou sua trombeta, e foi ferido um terço do sol, da lua e das estrelas, que escureceram. Um terço do dia ficou sem luz, e também um terço da noite.

[[v66-8-13]]

^<<v66-8-13,13>>^ Então vi e ouvi uma águia que voava no ponto mais alto do céu e gritava em alta voz: "Terror, terror, terror sobre todos os habitantes da terra, pelo que acontecerá quando os três últimos anjos tocarem suas trombetas!".

'''

xref:066-apocalipse/066-apocalipse-007.adoc#v66-7-0[&#60; Capítulo Anterior] | <<v66-8-0,Topo>> | xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[Próximo Capítulo &#62;]