include::./index.adoc[]

[[v66-21-0]]
=== Apocalipse, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v66-21-1]]

^<<v66-21-1,1>>^ Então vi um novo céu e uma nova terra, pois o primeiro céu e a primeira terra já não existiam, e o mar também não mais existia.

[[v66-21-2]]

^<<v66-21-2,2>>^ E vi a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, como uma noiva belamente vestida para seu marido.

[[v66-21-3]]

^<<v66-21-3,3>>^ Ouvi uma forte voz que vinha do trono e dizia: "Vejam, o tabernáculo de Deus está no meio de seu povo! Deus habitará com eles, e eles serão seu povo. O próprio Deus estará com eles.

[[v66-21-4]]

^<<v66-21-4,4>>^ Ele lhes enxugará dos olhos toda lágrima, e não haverá mais morte, nem tristeza, nem choro, nem dor. Todas essas coisas passaram para sempre".

[[v66-21-5]]

^<<v66-21-5,5>>^ E aquele que estava sentado no trono disse: "Vejam, faço novas todas as coisas!". Em seguida, disse: "Escreva isto, pois o que lhe digo é digno de confiança e verdadeiro".

[[v66-21-6]]

^<<v66-21-6,6>>^ E disse ainda: "Está terminado! Eu sou o Alfa e o Ômega, o Princípio e o Fim. A quem tiver sede, darei de beber gratuitamente das fontes da água da vida.

[[v66-21-7]]

^<<v66-21-7,7>>^ O vitorioso herdará todas essas bênçãos, e eu serei seu Deus, e ele será meu filho.

[[v66-21-8]]

^<<v66-21-8,8>>^ "Mas os covardes, os incrédulos, os corruptos, os assassinos, os sexualmente impuros, os que praticam feitiçaria, os adoradores de ídolos e todos os mentirosos estão destinados ao lago de fogo que arde com enxofre. Esta é a segunda morte".

[[v66-21-9]]

^<<v66-21-9,9>>^ Então um dos sete anjos que seguravam as sete taças com as últimas sete pragas se aproximou e me disse: "Venha comigo, e eu lhe mostrarei a noiva, a esposa do Cordeiro".

[[v66-21-10]]

^<<v66-21-10,10>>^ Ele me levou no Espírito até um grande e alto monte e me mostrou a cidade santa, Jerusalém, que descia do céu da parte de Deus.

[[v66-21-11]]

^<<v66-21-11,11>>^ Brilhava com a glória de Deus e cintilava como uma pedra preciosa, como jaspe, transparente como cristal.

[[v66-21-12]]

^<<v66-21-12,12>>^ O muro da cidade era grande e alto, com doze portas guardadas por doze anjos, e nelas estavam escritos os nomes das doze tribos de Israel.

[[v66-21-13]]

^<<v66-21-13,13>>^ Havia três portas de cada lado: leste, norte, sul e oeste.

[[v66-21-14]]

^<<v66-21-14,14>>^ O muro da cidade tinha doze pedras de alicerce, e nelas estavam escritos os nomes dos doze apóstolos do Cordeiro.

[[v66-21-15]]

^<<v66-21-15,15>>^ O anjo que falava comigo tinha na mão uma vara de ouro para medir a cidade, suas portas e seu muro.

[[v66-21-16]]

^<<v66-21-16,16>>^ A cidade tinha o formato de um quadrado, de comprimento e largura iguais. De fato, tinha 2.200 quilômetros de comprimento, de largura e de altura.

[[v66-21-17]]

^<<v66-21-17,17>>^ Então ele mediu o muro e descobriu que tinha quase 65 metros de espessura (de acordo com a medida humana usada pelo anjo).

[[v66-21-18]]

^<<v66-21-18,18>>^ O muro era feito de jaspe, e a cidade era de ouro puro, transparente como vidro.

[[v66-21-19]]

^<<v66-21-19,19>>^ O muro da cidade era construído sobre alicerces ornamentados com doze pedras preciosas: a primeira com jaspe, a segunda com safira, a terceira com ágata, a quarta com esmeralda,

[[v66-21-20]]

^<<v66-21-20,20>>^ a quinta com ônix, a sexta com cornalina, a sétima com crisólito, a oitava com berilo, a nona com topázio, a décima com crisópraso, a décima primeira com jacinto, e a décima segunda com ametista.

[[v66-21-21]]

^<<v66-21-21,21>>^ As doze portas eram feitas de pérolas, cada porta de uma única pérola. E a rua principal era de ouro puro, transparente como vidro.

[[v66-21-22]]

^<<v66-21-22,22>>^ Não vi templo algum na cidade, pois o Senhor Deus, o Todo-poderoso, e o Cordeiro são seu templo.

[[v66-21-23]]

^<<v66-21-23,23>>^ A cidade não precisa de sol nem de lua, pois a glória de Deus a ilumina, e o Cordeiro é sua lâmpada.

[[v66-21-24]]

^<<v66-21-24,24>>^ As nações andarão em sua luz, e os reis, em toda a sua glória, entrarão na cidade.

[[v66-21-25]]

^<<v66-21-25,25>>^ Suas portas nunca se fecharão, pois ali não haverá noite.

[[v66-21-26]]

^<<v66-21-26,26>>^ E todas as nações trarão sua glória e honra à cidade.

[[v66-21-27]]

^<<v66-21-27,27>>^ Nenhum mal terá permissão de entrar, nem pessoa alguma que pratique o que é vergonhoso ou enganoso, mas somente aqueles cujos nomes estão escritos no Livro da Vida do Cordeiro.

'''

xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[&#60; Capítulo Anterior] | <<v66-21-0,Topo>> | xref:066-apocalipse/066-apocalipse-022.adoc#v66-22-0[Próximo Capítulo &#62;]