include::./index.adoc[]

[[v66-22-0]]
=== Apocalipse, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v66-22-1]]

^<<v66-22-1,1>>^ Então o anjo me mostrou o rio da água da vida, transparente como cristal, que fluía do trono de Deus e do Cordeiro

[[v66-22-2]]

^<<v66-22-2,2>>^ e passava no meio da rua principal. De cada lado do rio estava a árvore da vida, que produz doze colheitas de frutos por ano, uma em cada mês, e cujas folhas servem como remédio para curar as nações.

[[v66-22-3]]

^<<v66-22-3,3>>^ Não haverá mais maldição sobre coisa alguma, porque o trono de Deus e do Cordeiro estará ali, e seus servos o adorarão.

[[v66-22-4]]

^<<v66-22-4,4>>^ Verão seu rosto, e seu nome estará escrito na testa de cada um.

[[v66-22-5]]

^<<v66-22-5,5>>^ E não haverá noite; não será necessária a luz da lâmpada nem a luz do sol, pois o Senhor Deus brilhará sobre eles. E reinarão para todo o sempre.

[[v66-22-6]]

^<<v66-22-6,6>>^ Então o anjo me disse: "Tudo que você ouviu e viu é digno de confiança e verdadeiro. O Senhor, o Deus dos espíritos dos profetas, enviou seu anjo para dizer a seus servos o que acontecerá em breve".

[[v66-22-7]]

^<<v66-22-7,7>>^ "Vejam, eu venho em breve! Felizes aqueles que obedecem às palavras da profecia registrada neste livro."

[[v66-22-8]]

^<<v66-22-8,8>>^ Eu, João, sou aquele que ouviu e viu todas essas coisas. E, quando as ouvi e vi, caí aos pés do anjo que as mostrou a mim, a fim de adorá-lo.

[[v66-22-9]]

^<<v66-22-9,9>>^ Mas ele disse: "Não faça isso! Sou um servo, como você e seus irmãos, os profetas, e como todos os que obedecem ao que está escrito neste livro. Adore somente a Deus!".

[[v66-22-10]]

^<<v66-22-10,10>>^ Em seguida, disse: "Não lacre com um selo as palavras proféticas deste livro, porque o tempo está próximo.

[[v66-22-11]]

^<<v66-22-11,11>>^ Que o mau continue a praticar a maldade; que o impuro continue a ser impuro; que o justo continue a viver de forma justa; que o santo continue a ser santo".

[[v66-22-12]]

^<<v66-22-12,12>>^ "Vejam, eu venho em breve e trago comigo a recompensa para retribuir a cada um de acordo com seus atos.

[[v66-22-13]]

^<<v66-22-13,13>>^ Eu sou o Alfa e o Ômega, o Primeiro e o Último, o Princípio e o Fim."

[[v66-22-14]]

^<<v66-22-14,14>>^ Felizes aqueles que lavam suas vestes. A eles será permitido entrar pelas portas da cidade e comer do fruto da árvore da vida.

[[v66-22-15]]

^<<v66-22-15,15>>^ Do lado de fora da cidade ficam os cães: os feiticeiros, os sexualmente impuros, os assassinos, os adoradores de ídolos e todos que gostam de praticar a mentira.

[[v66-22-16]]

^<<v66-22-16,16>>^ "Eu, Jesus, enviei meu anjo a fim de lhes dar esta mensagem para as igrejas. Eu sou a origem de Davi e o herdeiro de seu trono. Sou a brilhante estrela da manhã."

[[v66-22-17]]

^<<v66-22-17,17>>^ O Espírito e a noiva dizem: "Vem!". Que todo aquele que ouve diga: "Vem!". Quem tiver sede, venha. Quem quiser, beba de graça da água da vida.

[[v66-22-18]]

^<<v66-22-18,18>>^ Declaro solenemente a todos que ouvem as palavras da profecia registrada neste livro: Se alguém acrescentar algo ao que está escrito aqui, Deus acrescentará a essa pessoa as pragas descritas neste livro.

[[v66-22-19]]

^<<v66-22-19,19>>^ E, se alguém retirar qualquer uma das palavras deste livro de profecia, Deus lhe retirará a participação na árvore da vida e na cidade santa descritas neste livro.

[[v66-22-20]]

^<<v66-22-20,20>>^ Aquele que é testemunha fiel de todas essas coisas diz: "Sim, venho em breve!". Amém! Vem, Senhor Jesus!

[[v66-22-21]]

^<<v66-22-21,21>>^ Que a graça do Senhor Jesus esteja com todos.

'''

xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[&#60; Capítulo Anterior] | <<v66-22-0,Topo>> | **Próximo Capítulo &#62;**