include::./index.adoc[]

[[v66-19-0]]
=== Apocalipse, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v66-19-1]]

^<<v66-19-1,1>>^ Depois disso, ouvi algo semelhante ao som de uma grande multidão clamando: "Aleluia! Salvação, glória e poder pertencem a nosso Deus.

[[v66-19-2]]

^<<v66-19-2,2>>^ Seus julgamentos são verdadeiros e justos. Ele castigou a grande prostituta, que corrompia a terra com sua imoralidade, e vingou o assassinato de seus servos".

[[v66-19-3]]

^<<v66-19-3,3>>^ E, mais uma vez, as vozes ressoaram: "Aleluia! A fumaça dessa cidade sobe para todo o sempre!".

[[v66-19-4]]

^<<v66-19-4,4>>^ Então os 24 anciãos e os quatro seres vivos se prostraram e adoraram a Deus, que estava sentado no trono. Disseram: "Amém! Aleluia!".

[[v66-19-5]]

^<<v66-19-5,5>>^ E do trono veio uma voz que dizia: "Louvem nosso Deus, todos os seus servos, todos os que o temem, pequenos e grandes".

[[v66-19-6]]

^<<v66-19-6,6>>^ Em seguida, ouvi outra vez algo semelhante ao som do clamor de uma grande multidão, como o som de fortes ondas do mar, como o som de violentos trovões: "Aleluia! Porque o Senhor, nosso Deus, o Todo-poderoso, reina.

[[v66-19-7]]

^<<v66-19-7,7>>^ Alegremo-nos, exultemos e a ele demos glória, pois chegou a hora do casamento do Cordeiro, e sua noiva já se preparou.

[[v66-19-8]]

^<<v66-19-8,8>>^ Ela recebeu um vestido do linho mais fino, puro e branco". Porque o linho fino representa os atos justos do povo santo.

[[v66-19-9]]

^<<v66-19-9,9>>^ E o anjo me disse: "Escreva isto: Felizes os que são convidados para o banquete de casamento do Cordeiro". E acrescentou: "Essas são as palavras verdadeiras de Deus".

[[v66-19-10]]

^<<v66-19-10,10>>^ Então caí aos pés do anjo para adorá-lo, mas ele me disse: "Não faça isso! Sou um servo, como você e seus irmãos que dão testemunho de sua fé em Jesus. Adore somente a Deus, pois o testemunho a respeito de Jesus é a essência da mensagem revelada aos profetas".

[[v66-19-11]]

^<<v66-19-11,11>>^ Vi o céu aberto, e surgiu um cavalo branco. Seu cavaleiro se chama Fiel e Verdadeiro, pois julga e guerreia com justiça.

[[v66-19-12]]

^<<v66-19-12,12>>^ Seus olhos eram como chamas de fogo, e em sua cabeça havia muitas coroas. Nele estava escrito um nome que ninguém conhece, a não ser ele mesmo.

[[v66-19-13]]

^<<v66-19-13,13>>^ Vestia um manto encharcado de sangue, e seu nome era a Palavra de Deus.

[[v66-19-14]]

^<<v66-19-14,14>>^ Os exércitos do céu, vestidos do linho mais fino, puro e branco, seguiam-no em cavalos brancos.

[[v66-19-15]]

^<<v66-19-15,15>>^ De sua boca saía uma espada afiada para ferir as nações. Ele as governará com cetro de ferro e esmagará as uvas no tanque de prensar da furiosa ira de Deus, o Todo-poderoso.

[[v66-19-16]]

^<<v66-19-16,16>>^ Em seu manto, na altura da coxa, estava escrito o nome: Rei dos reis e Senhor dos senhores.

[[v66-19-17]]

^<<v66-19-17,17>>^ Então vi um anjo em pé no sol. Gritava para as aves que voavam no ponto mais alto do céu: "Venham! Reúnam-se para o grande banquete que Deus preparou!

[[v66-19-18]]

^<<v66-19-18,18>>^ Venham e comam a carne dos reis, dos generais e dos fortes guerreiros; dos cavalos e de seus cavaleiros; de toda a humanidade, escravos e livres, pequenos e grandes".

[[v66-19-19]]

^<<v66-19-19,19>>^ Depois vi a besta e os reis da terra e seus exércitos reunidos para lutarem contra aquele que montava no cavalo e contra seu exército.

[[v66-19-20]]

^<<v66-19-20,20>>^ Mas a besta foi presa e, com ela, o falso profeta que fazia sinais em seu nome, sinais que enganaram todos que haviam recebido a marca da besta e adoravam sua estátua. Tanto a besta como seu falso profeta foram lançados vivos no lago de fogo que arde com enxofre.

[[v66-19-21]]

^<<v66-19-21,21>>^ Todo o seu exército foi morto com a espada afiada que saía da boca daquele que montava no cavalo branco. E todas as aves se fartaram com a carne dos cadáveres.

'''

xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[&#60; Capítulo Anterior] | <<v66-19-0,Topo>> | xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[Próximo Capítulo &#62;]