include::./index.adoc[]

[[v66-11-0]]
=== Apocalipse, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v66-11-1]]

^<<v66-11-1,1>>^ Depois disso, recebi uma vara de medir e me foi dito: "Vá e tire as medidas do templo de Deus e do altar, e conte o número de adoradores.

[[v66-11-2]]

^<<v66-11-2,2>>^ Mas não meça o pátio exterior, porque ele foi entregue às nações. Elas pisotearão a cidade santa durante 42 meses.

[[v66-11-3]]

^<<v66-11-3,3>>^ Darei autoridade a minhas duas testemunhas, e elas se vestirão de pano de saco e profetizarão durante 1.260 dias".

[[v66-11-4]]

^<<v66-11-4,4>>^ Essas duas testemunhas são as duas oliveiras e os dois candelabros que estão diante do Senhor de toda a terra.

[[v66-11-5]]

^<<v66-11-5,5>>^ Se alguém tentar lhes fazer mal, da boca lhes sairá fogo e consumirá seus inimigos. Assim deve morrer quem tentar lhes fazer mal.

[[v66-11-6]]

^<<v66-11-6,6>>^ Elas têm poder para fechar o céu, a fim de que não chova durante o tempo que profetizarem, e têm poder para transformar as águas em sangue e para ferir a terra com pragas de toda espécie, quantas vezes desejarem.

[[v66-11-7]]

^<<v66-11-7,7>>^ Quando tiverem concluído seu testemunho, a besta que vem do abismo lutará contra elas, e ela as vencerá e as matará.

[[v66-11-8]]

^<<v66-11-8,8>>^ Os corpos ficarão estendidos na rua principal da grande cidade, chamada figuradamente "Sodoma" e "Egito", onde seu Senhor foi crucificado.

[[v66-11-9]]

^<<v66-11-9,9>>^ Durante três dias e meio, todos os povos, tribos, línguas e nações olharão para esses corpos, e ninguém terá permissão de sepultá-los.

[[v66-11-10]]

^<<v66-11-10,10>>^ Os habitantes da terra festejarão e trocarão presentes entre si para comemorar a morte dos dois profetas que os haviam atormentado.

[[v66-11-11]]

^<<v66-11-11,11>>^ Depois de três dias e meio, porém, Deus soprou vida nos dois profetas, e eles se levantaram, enchendo de terror os que os viram.

[[v66-11-12]]

^<<v66-11-12,12>>^ Então uma forte voz do céu disse aos dois: "Subam aqui!". E eles subiram ao céu numa nuvem, sob o olhar de seus inimigos.

[[v66-11-13]]

^<<v66-11-13,13>>^ Nesse momento, houve um grande terremoto que destruiu um décimo da cidade. Sete mil pessoas morreram, e as que restaram ficaram aterrorizadas e deram glória ao Deus do céu.

[[v66-11-14]]

^<<v66-11-14,14>>^ O segundo terror passou, mas logo vem o terceiro.

[[v66-11-15]]

^<<v66-11-15,15>>^ O sétimo anjo tocou sua trombeta, e fortes vozes gritaram no céu: "O reino do mundo se tornou de nosso Senhor e de seu Cristo, e ele reinará para todo o sempre".

[[v66-11-16]]

^<<v66-11-16,16>>^ Os 24 anciãos que estavam sentados em seus tronos diante de Deus se prostraram com o rosto em terra e o adoraram,

[[v66-11-17]]

^<<v66-11-17,17>>^ dizendo: "Nós te agradecemos, Senhor Deus, o Todo-poderoso, que és e que eras, pois agora assumiste teu grande poder e começaste a reinar.

[[v66-11-18]]

^<<v66-11-18,18>>^ As nações se enfureceram, mas agora chegou o tempo de tua ira. É tempo de julgar os mortos e de recompensar teus servos, os profetas, assim como teu povo santo e todos que temem o teu nome, desde os pequenos até os grandes. É tempo de destruir todos que causaram destruição na terra".

[[v66-11-19]]

^<<v66-11-19,19>>^ Então se abriu no céu o templo de Deus, e dentro do templo foi vista a arca de sua aliança. Houve relâmpagos, estrondos e trovões, um terremoto e uma grande tempestade de granizo.

'''

xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[&#60; Capítulo Anterior] | <<v66-11-0,Topo>> | xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[Próximo Capítulo &#62;]