include::./index.adoc[]

[[v66-10-0]]
=== Apocalipse, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v66-10-1]]

^<<v66-10-1,1>>^ Então vi outro anjo poderoso descendo do céu, envolto numa nuvem, com um arco-íris sobre a cabeça. Seu rosto brilhava como o sol, e seus pés eram como colunas de fogo.

[[v66-10-2]]

^<<v66-10-2,2>>^ Tinha na mão um livrinho aberto. O anjo pôs o pé direito no mar e o pé esquerdo na terra.

[[v66-10-3]]

^<<v66-10-3,3>>^ Deu um forte grito, como o rugido de um leão, e os sete trovões responderam.

[[v66-10-4]]

^<<v66-10-4,4>>^ No momento em que os sete trovões falaram, eu estava prestes a escrever, mas ouvi uma voz do céu que disse: "Guarde em segredo as coisas que os sete trovões disseram, e não as escreva".

[[v66-10-5]]

^<<v66-10-5,5>>^ Então o anjo que vi em pé sobre o mar e sobre a terra levantou a mão direita para o céu.

[[v66-10-6]]

^<<v66-10-6,6>>^ Jurou em nome daquele que vive para todo o sempre, que criou os céus, a terra, o mar e tudo que neles há. "Não haverá mais demora", disse ele.

[[v66-10-7]]

^<<v66-10-7,7>>^ "Quando o sétimo anjo tocar sua trombeta, o plano que Deus manteve em segredo se cumprirá, conforme ele anunciou a seus servos, os profetas."

[[v66-10-8]]

^<<v66-10-8,8>>^ A voz do céu falou novamente comigo: "Vá e pegue o livro aberto da mão do anjo que está em pé sobre o mar e sobre a terra".

[[v66-10-9]]

^<<v66-10-9,9>>^ Então me aproximei do anjo e lhe pedi o livrinho. "Pegue-o e coma-o!", disse ele. "Ele será amargo em seu estômago, embora tenha um sabor doce como mel em sua boca."

[[v66-10-10]]

^<<v66-10-10,10>>^ Peguei o livrinho da mão do anjo e o comi. Em minha boca, era doce como mel, mas, quando o engoli, tornou-se amargo em meu estômago.

[[v66-10-11]]

^<<v66-10-11,11>>^ Então me foi dito: "É necessário que você profetize outra vez a respeito de muitos povos, nações, línguas e reis".

'''

xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[&#60; Capítulo Anterior] | <<v66-10-0,Topo>> | xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[Próximo Capítulo &#62;]