include::./index.adoc[]

[[v66-16-0]]
=== Apocalipse, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v66-16-1]]

^<<v66-16-1,1>>^ Então ouvi uma poderosa voz que vinha do templo dizer aos sete anjos: "Vão e derramem sobre a terra as sete taças da fúria de Deus".

[[v66-16-2]]

^<<v66-16-2,2>>^ O primeiro anjo saiu do templo e derramou sua taça sobre a terra, e se abriram feridas horríveis e malignas naqueles que tinham a marca da besta e adoravam sua estátua.

[[v66-16-3]]

^<<v66-16-3,3>>^ O segundo anjo derramou sua taça sobre o mar, que se transformou em sangue como de um cadáver, e morreram todas as criaturas do mar.

[[v66-16-4]]

^<<v66-16-4,4>>^ O terceiro anjo derramou sua taça sobre os rios e as fontes, que se transformaram em sangue.

[[v66-16-5]]

^<<v66-16-5,5>>^ E ouvi o anjo que tinha autoridade sobre a água dizer: "Tu és justo, ó Santo, que és e que eras, pois enviaste estes julgamentos.

[[v66-16-6]]

^<<v66-16-6,6>>^ Porque eles derramaram o sangue de teu povo santo e de teus profetas, tu lhes deste sangue para beber; é sua justa retribuição".

[[v66-16-7]]

^<<v66-16-7,7>>^ E ouvi uma voz que vinha do altar dizer: "Sim, Senhor Deus, o Todo-poderoso, teus julgamentos são verdadeiros e justos".

[[v66-16-8]]

^<<v66-16-8,8>>^ O quarto anjo derramou sua taça sobre o sol, que com seu fogo fez queimar as pessoas.

[[v66-16-9]]

^<<v66-16-9,9>>^ Todos foram queimados pelo intenso calor e blasfemaram contra o nome de Deus, que tinha controle sobre essas pragas. E não se arrependeram nem deram glória a Deus.

[[v66-16-10]]

^<<v66-16-10,10>>^ O quinto anjo derramou sua taça sobre o trono da besta, e seu reino foi lançado na escuridão. Angustiados, seus súditos rangiam os dentes

[[v66-16-11]]

^<<v66-16-11,11>>^ e, por causa de suas dores e feridas, blasfemavam contra o Deus do céu. E não se arrependeram de seus atos perversos.

[[v66-16-12]]

^<<v66-16-12,12>>^ O sexto anjo derramou sua taça sobre o grande rio Eufrates, e ele secou, abrindo caminho para os reis que vêm do Oriente.

[[v66-16-13]]

^<<v66-16-13,13>>^ Então vi saltarem da boca do dragão, da boca da besta e da boca do falso profeta três espíritos impuros semelhantes a sapos.

[[v66-16-14]]

^<<v66-16-14,14>>^ São espíritos demoníacos que realizam sinais e vão aos governantes da terra a fim de reuni-los para a batalha contra o Senhor, no grande dia de Deus, o Todo-poderoso.

[[v66-16-15]]

^<<v66-16-15,15>>^ "Eu virei inesperadamente, como ladrão! Feliz é aquele que me espera alerta e mantém puras suas vestes, para que não precise andar nu e envergonhado."

[[v66-16-16]]

^<<v66-16-16,16>>^ E os espíritos reuniram todos os governantes e seus exércitos no lugar que, em hebraico, se chama Armagedom .

[[v66-16-17]]

^<<v66-16-17,17>>^ O sétimo anjo derramou sua taça no ar, e do trono do templo veio um forte grito: "Está terminado!".

[[v66-16-18]]

^<<v66-16-18,18>>^ Então houve relâmpagos, estrondos e trovões, e um forte terremoto, o mais violento desde a criação da humanidade.

[[v66-16-19]]

^<<v66-16-19,19>>^ A grande cidade, Babilônia, se dividiu em três partes, e as cidades de muitas nações tombaram. Deus se lembrou de todos os pecados da Babilônia e a fez beber do cálice cheio do vinho de sua furiosa ira.

[[v66-16-20]]

^<<v66-16-20,20>>^ Todas as ilhas desapareceram, e todos os montes foram arrasados.

[[v66-16-21]]

^<<v66-16-21,21>>^ Houve uma forte tempestade de granizo, com pedras que pesavam até 35 quilos caindo do céu sobre as pessoas. E elas blasfemaram contra Deus por causa da terrível praga de granizo.

'''

xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[&#60; Capítulo Anterior] | <<v66-16-0,Topo>> | xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[Próximo Capítulo &#62;]