include::./index.adoc[]

[[v66-12-0]]
=== Apocalipse, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v66-12-1]]

^<<v66-12-1,1>>^ Então foi visto no céu um grande sinal: uma mulher vestida do sol, com a lua sob os pés e uma coroa de doze estrelas na cabeça.

[[v66-12-2]]

^<<v66-12-2,2>>^ Estava grávida e gritava por causa das dores de parto e da agonia de dar à luz.

[[v66-12-3]]

^<<v66-12-3,3>>^ Outro sinal foi visto no céu: um enorme dragão vermelho com sete cabeças e dez chifres, e sete coroas nas cabeças.

[[v66-12-4]]

^<<v66-12-4,4>>^ Com a cauda, arrastou um terço das estrelas do céu e as lançou na terra. E, quando a mulher estava para dar à luz, o dragão parou diante dela, pronto para devorar a criança tão logo ela nascesse.

[[v66-12-5]]

^<<v66-12-5,5>>^ A mulher deu à luz um filho, que governará todas as nações com cetro de ferro, e ele foi arrebatado para junto de Deus e de seu trono.

[[v66-12-6]]

^<<v66-12-6,6>>^ A mulher fugiu para o deserto, onde Deus havia preparado um lugar para cuidar dela durante 1.260 dias.

[[v66-12-7]]

^<<v66-12-7,7>>^ Houve guerra no céu. Miguel e seus anjos lutaram contra o dragão e seus anjos.

[[v66-12-8]]

^<<v66-12-8,8>>^ O dragão perdeu a batalha, e ele e seus anjos foram expulsos do céu.

[[v66-12-9]]

^<<v66-12-9,9>>^ Esse enorme dragão, a antiga serpente chamada diabo ou Satanás, que engana o mundo todo, foi lançado na terra com seus anjos.

[[v66-12-10]]

^<<v66-12-10,10>>^ Então ouvi uma forte voz que bradava pelos céus: "Finalmente chegaram a salvação, o poder, o reino de nosso Deus e a autoridade de seu Cristo. Porque foi lançado para a terra o acusador de nossos irmãos, aquele que dia e noite os acusa diante de nosso Deus.

[[v66-12-11]]

^<<v66-12-11,11>>^ Eles o derrotaram pelo sangue do Cordeiro e pelo testemunho deles. Não amaram a própria vida nem mesmo diante da morte.

[[v66-12-12]]

^<<v66-12-12,12>>^ Portanto, alegrem-se, ó céus, e vocês que habitam nos céus! Sobre a terra e o mar, porém, virá terror, pois o diabo desceu até vocês com grande fúria, sabendo que lhe resta pouco tempo".

[[v66-12-13]]

^<<v66-12-13,13>>^ Quando o dragão percebeu que havia sido lançado na terra, perseguiu a mulher que tinha dado à luz o menino.

[[v66-12-14]]

^<<v66-12-14,14>>^ Ela, porém, recebeu duas asas como as de uma grande águia, para que voasse ao lugar preparado para ela no deserto. Ali, será sustentada e protegida da serpente durante um tempo, tempos e metade de um tempo.

[[v66-12-15]]

^<<v66-12-15,15>>^ Então a serpente, com uma torrente de água que fez sair de sua boca, tentou afogar a mulher.

[[v66-12-16]]

^<<v66-12-16,16>>^ Mas a terra ajudou a mulher, abrindo a boca e engolindo o rio que havia jorrado da boca do dragão.

[[v66-12-17]]

^<<v66-12-17,17>>^ O dragão se enfureceu com a mulher e passou a lutar contra o restante de seus filhos, todos os que obedecem aos mandamentos de Deus e se mantêm fiéis no testemunho de Jesus.

[[v66-12-18]]

^<<v66-12-18,18>>^ Então o dragão se colocou em pé na praia, junto ao mar.

'''

xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[Próximo Capítulo &#62;]