include::./index.adoc[]

[[v66-4-0]]
=== Apocalipse, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v66-4-1]]

^<<v66-4-1,1>>^ Então, quando olhei, vi uma porta aberta no céu, e a mesma voz que eu tinha ouvido antes falou comigo como um toque de trombeta. A voz disse: "Suba para cá, e eu lhe mostrarei o que acontecerá depois destas coisas".

[[v66-4-2]]

^<<v66-4-2,2>>^ E, no mesmo instante, fui tomado pelo Espírito e vi um trono no céu e alguém sentado nele.

[[v66-4-3]]

^<<v66-4-3,3>>^ Aquele que estava sentado no trono brilhava como pedras preciosas, como jaspe e sardônio. Um arco-íris, com brilho semelhante ao da esmeralda, circundava seu trono.

[[v66-4-4]]

^<<v66-4-4,4>>^ Ao redor do trono havia 24 tronos, nos quais estavam sentados 24 anciãos. Estavam todos vestidos de branco e usando coroas de ouro na cabeça.

[[v66-4-5]]

^<<v66-4-5,5>>^ Do trono saíam relâmpagos, estrondos e trovões, e na frente dele havia sete tochas com chamas ardentes, que são os sete espíritos de Deus.

[[v66-4-6]]

^<<v66-4-6,6>>^ Diante do trono havia algo como um mar de vidro, cintilante como cristal. No centro e ao redor do trono havia quatro seres vivos, cada um coberto de olhos na frente e atrás.

[[v66-4-7]]

^<<v66-4-7,7>>^ O primeiro deles era semelhante a um leão; o segundo, semelhante a um boi; o terceiro tinha rosto de homem; e o quarto era como uma águia em voo.

[[v66-4-8]]

^<<v66-4-8,8>>^ Cada um dos seres vivos tinha seis asas, inteiramente cobertas de olhos, por dentro e por fora. Dia e noite, repetem sem parar: "Santo, santo, santo é o Senhor Deus, o Todo-poderoso, que era, que é e que ainda virá".

[[v66-4-9]]

^<<v66-4-9,9>>^ Cada vez que os seres vivos dão glória, honra e graças ao que está sentado no trono, àquele que vive para todo o sempre,

[[v66-4-10]]

^<<v66-4-10,10>>^ os 24 anciãos se prostram e adoram o que está sentado no trono, aquele que vive para todo o sempre. Colocam suas coroas diante do trono e dizem:

[[v66-4-11]]

^<<v66-4-11,11>>^ "Tu és digno, ó Senhor e nosso Deus, de receber glória, honra e poder. Pois criaste todas as coisas, e elas existem porque as criaste segundo a tua vontade".

'''

xref:066-apocalipse/066-apocalipse-003.adoc#v66-3-0[&#60; Capítulo Anterior] | <<v66-4-0,Topo>> | xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[Próximo Capítulo &#62;]