include::./index.adoc[]

[[v66-3-0]]
=== Apocalipse, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v66-3-1]]

^<<v66-3-1,1>>^ "Escreva esta carta ao anjo da igreja em Sardes. Esta é a mensagem daquele que tem os sete espíritos de Deus e as sete estrelas: "Sei de tudo que você faz. Você tem fama de estar vivo, mas está morto.

[[v66-3-2]]

^<<v66-3-2,2>>^ Desperte! Fortaleça o pouco que resta, pois até mesmo isso está quase morto. Vejo que suas ações não atendem aos requisitos de meu Deus.

[[v66-3-3]]

^<<v66-3-3,3>>^ Lembre-se do que ouviu e no que acreditou no princípio; agarre-se a isso com firmeza. Arrependa-se. Se não despertar, virei subitamente até você, como um ladrão.

[[v66-3-4]]

^<<v66-3-4,4>>^ "Há alguns em Sardes, no entanto, que não mancharam suas roupas com o mal. Eles andarão comigo vestidos de branco, pois são dignos.

[[v66-3-5]]

^<<v66-3-5,5>>^ O vitorioso será vestido de branco. Jamais apagarei seu nome do Livro da Vida e confirmarei, diante de meu Pai e de seus anjos, que ele me pertence.

[[v66-3-6]]

^<<v66-3-6,6>>^ "Quem tem ouvidos para ouvir, ouça o que o Espírito diz às igrejas."

[[v66-3-7]]

^<<v66-3-7,7>>^ "Escreva esta carta ao anjo da igreja em Filadélfia. Esta é a mensagem daquele que é santo e verdadeiro, que tem a chave de Davi. O que ele abre ninguém pode fechar, e o que ele fecha ninguém pode abrir:

[[v66-3-8]]

^<<v66-3-8,8>>^ "Sei de tudo que você faz. Abri para você uma porta que ninguém pode fechar. Você tem pouca força, mas ainda assim obedeceu à minha palavra e não negou meu nome.

[[v66-3-9]]

^<<v66-3-9,9>>^ Veja, obrigarei aqueles que pertencem à sinagoga de Satanás — os mentirosos que se dizem judeus, mas não são — a virem, prostrarem-se a seus pés e reconhecerem que amo você.

[[v66-3-10]]

^<<v66-3-10,10>>^ "Porque obedeceu à minha ordem para perseverar, eu o protegerei do grande tempo de provação que virá sobre todo o mundo para pôr à prova os habitantes da terra.

[[v66-3-11]]

^<<v66-3-11,11>>^ Venho em breve. Apegue-se ao que você tem, para que ninguém tome sua coroa.

[[v66-3-12]]

^<<v66-3-12,12>>^ O vitorioso se tornará coluna do templo de meu Deus, de onde jamais sairá. Escreverei nele o nome de meu Deus, e ele será cidadão da cidade de meu Deus, a nova Jerusalém que desce do céu, da parte de meu Deus. E também escreverei nele o meu novo nome.

[[v66-3-13]]

^<<v66-3-13,13>>^ "Quem tem ouvidos para ouvir, ouça o que o Espírito diz às igrejas."

[[v66-3-14]]

^<<v66-3-14,14>>^ "Escreva esta carta ao anjo da igreja em Laodiceia. Esta é a mensagem daquele que é o Amém, a testemunha fiel e verdadeira, a origem da criação de Deus:

[[v66-3-15]]

^<<v66-3-15,15>>^ "Sei de tudo que você faz. Você não é frio nem quente. Desejaria que fosse um ou o outro!

[[v66-3-16]]

^<<v66-3-16,16>>^ Mas, porque é como água morna, nem quente nem fria, eu o vomitarei de minha boca.

[[v66-3-17]]

^<<v66-3-17,17>>^ Você diz: ‘Sou rico e próspero, não preciso de coisa alguma’. E não percebe que é infeliz, miserável, pobre, cego e está nu.

[[v66-3-18]]

^<<v66-3-18,18>>^ Eu o aconselho a comprar de mim ouro purificado pelo fogo, e então será rico. Compre também roupas brancas, para que não se envergonhe de sua nudez, e colírio para aplicar nos olhos, a fim de enxergar.

[[v66-3-19]]

^<<v66-3-19,19>>^ Eu corrijo e disciplino aqueles que amo. Por isso, seja zeloso e arrependa-se.

[[v66-3-20]]

^<<v66-3-20,20>>^ "Preste atenção! Estou à porta e bato. Se você ouvir minha voz e abrir a porta, entrarei e, juntos, faremos uma refeição, como amigos.

[[v66-3-21]]

^<<v66-3-21,21>>^ O vitorioso se sentará comigo em meu trono, assim como eu fui vitorioso e me sentei com meu Pai em seu trono.

[[v66-3-22]]

^<<v66-3-22,22>>^ "Quem tem ouvidos para ouvir, ouça o que o Espírito diz às igrejas".

'''

xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[&#60; Capítulo Anterior] | <<v66-3-0,Topo>> | xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[Próximo Capítulo &#62;]