include::./index.adoc[]

[[v66-13-0]]
=== Apocalipse, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v66-13-1]]

^<<v66-13-1,1>>^ Então vi sair do mar uma besta. Tinha dez chifres e sete cabeças, e uma coroa em cada chifre. Em cada cabeça estavam escritos nomes de blasfêmias.

[[v66-13-2]]

^<<v66-13-2,2>>^ A besta parecia um leopardo, mas tinha pés como de urso e boca como de leão. E o dragão deu à besta seu poder, seu trono e grande autoridade.

[[v66-13-3]]

^<<v66-13-3,3>>^ Vi que uma das cabeças da besta parecia mortalmente ferida, mas o ferimento mortal foi curado. O mundo inteiro se maravilhou e seguiu a besta.

[[v66-13-4]]

^<<v66-13-4,4>>^ Adoraram o dragão por ter dado à besta tamanho poder, e também a adoraram. "Quem é tão grande como a besta?", diziam. "Quem é capaz de lutar contra ela?"

[[v66-13-5]]

^<<v66-13-5,5>>^ Então foi permitido à besta falar grandes blasfêmias, e lhe foi dada autoridade para fazer o que quisesse durante 42 meses.

[[v66-13-6]]

^<<v66-13-6,6>>^ Ela blasfemou terrivelmente contra Deus, difamando seu nome, seu tabernáculo e os que habitam no céu.

[[v66-13-7]]

^<<v66-13-7,7>>^ Foi permitido à besta guerrear contra o povo santo e vencê-lo, e ela recebeu autoridade para governar sobre toda tribo, povo, língua e nação.

[[v66-13-8]]

^<<v66-13-8,8>>^ E todos os habitantes da terra adoraram a besta. São eles os que não têm os nomes escritos no Livro da Vida que pertence ao Cordeiro, que foi morto antes da criação do mundo.

[[v66-13-9]]

^<<v66-13-9,9>>^ Quem é capaz de ouvir, ouça com atenção!

[[v66-13-10]]

^<<v66-13-10,10>>^ Quem estiver destinado à prisão será preso. Quem estiver destinado a morrer pela espada morrerá pela espada. Isso significa que o povo santo deve ser perseverante e permanecer fiel.

[[v66-13-11]]

^<<v66-13-11,11>>^ Então vi outra besta que saiu da terra. Tinha dois chifres, como de cordeiro, mas falava com voz de dragão.

[[v66-13-12]]

^<<v66-13-12,12>>^ Exercia toda a autoridade da primeira besta e exigia que a terra e seus habitantes adorassem a primeira besta, cujo ferimento mortal havia sido curado.

[[v66-13-13]]

^<<v66-13-13,13>>^ Realizava sinais espantosos, chegando a fazer fogo descer do céu sobre a terra, à vista de todos.

[[v66-13-14]]

^<<v66-13-14,14>>^ Enganou os habitantes da terra com os sinais que lhe foi permitido realizar em nome da primeira besta. Ordenou que fizessem uma grande estátua da primeira besta, que havia sido mortalmente ferida e sobrevivido.

[[v66-13-15]]

^<<v66-13-15,15>>^ Então lhe foi permitido dar vida a essa estátua, para que ela falasse, e a estátua da besta ordenou que fossem mortos todos que se recusassem a adorá-la.

[[v66-13-16]]

^<<v66-13-16,16>>^ Exigiu que grandes e pequenos, ricos e pobres, escravos e livres, todos recebessem uma marca na mão direita ou na testa.

[[v66-13-17]]

^<<v66-13-17,17>>^ E ninguém podia comprar nem vender coisa alguma sem essa marca, que era o nome da besta ou o número que representa seu nome.

[[v66-13-18]]

^<<v66-13-18,18>>^ Aqui é preciso sabedoria. Quem tem discernimento, trate de entender o significado do número da besta, pois é número de homem. Seu número é 666.

'''

xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[&#60; Capítulo Anterior] | <<v66-13-0,Topo>> | xref:066-apocalipse/066-apocalipse-014.adoc#v66-14-0[Próximo Capítulo &#62;]