include::./index.adoc[]

[[v66-20-0]]
=== Apocalipse, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v66-20-1]]

^<<v66-20-1,1>>^ Então vi um anjo descer do céu trazendo na mão a chave do abismo e uma grande corrente.

[[v66-20-2]]

^<<v66-20-2,2>>^ Ele prendeu o dragão, a antiga serpente que é o diabo, Satanás, e o acorrentou por mil anos.

[[v66-20-3]]

^<<v66-20-3,3>>^ O anjo o lançou no abismo, o fechou e pôs um lacre na porta, de modo que ele não pudesse mais enganar as nações até que terminassem os mil anos. Depois disso, é necessário que ele seja solto por um pouco de tempo.

[[v66-20-4]]

^<<v66-20-4,4>>^ Vi tronos, e os que estavam sentados neles haviam recebido autoridade para julgar. Vi também as almas daqueles que haviam sido decapitados por testemunharem a respeito de Jesus e por proclamarem a palavra de Deus. Não tinham adorado a besta nem sua estátua, nem aceitado sua marca na testa ou nas mãos. Eles ressuscitaram e reinaram com Cristo por mil anos.

[[v66-20-5]]

^<<v66-20-5,5>>^ Esta é a primeira ressurreição. (O restante dos mortos só voltou à vida depois que terminaram os mil anos.)

[[v66-20-6]]

^<<v66-20-6,6>>^ Felizes e santos são aqueles que participam da primeira ressurreição. A segunda morte não tem poder algum sobre eles, pois serão sacerdotes de Deus e de Cristo e reinarão com ele por mil anos.

[[v66-20-7]]

^<<v66-20-7,7>>^ Quando terminarem os mil anos, Satanás será solto da prisão

[[v66-20-8]]

^<<v66-20-8,8>>^ e sairá para enganar as nações, Gogue e Magogue, em todas as extremidades da terra. Ele as reunirá para a batalha, um exército poderoso, incontável como a areia da praia.

[[v66-20-9]]

^<<v66-20-9,9>>^ Subiram pela vasta planície da terra e cercaram o acampamento do povo santo e a cidade amada. Mas fogo desceu do céu e os consumiu.

[[v66-20-10]]

^<<v66-20-10,10>>^ O diabo, que os havia enganado, foi lançado no lago de fogo que arde com enxofre, onde já estavam a besta e o falso profeta. Ali serão atormentados dia e noite, para todo o sempre.

[[v66-20-11]]

^<<v66-20-11,11>>^ Vi um grande trono e aquele que estava sentado nele. A terra e o céu fugiram de sua presença, mas não encontraram lugar para se esconder.

[[v66-20-12]]

^<<v66-20-12,12>>^ Vi os mortos, pequenos e grandes, em pé diante do trono de Deus. E foram abertos os livros, incluindo o Livro da Vida. Os mortos foram julgados segundo o que haviam feito, conforme o que estava registrado nos livros.

[[v66-20-13]]

^<<v66-20-13,13>>^ O mar entregou seus mortos, e a morte e o mundo dos mortos também entregaram seus mortos. E todos foram julgados de acordo com seus atos.

[[v66-20-14]]

^<<v66-20-14,14>>^ Então a morte e o mundo dos mortos foram lançados no lago de fogo. Esse lago de fogo é a segunda morte.

[[v66-20-15]]

^<<v66-20-15,15>>^ E quem não tinha o nome registrado no Livro da Vida foi lançado no lago de fogo.

'''

xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[&#60; Capítulo Anterior] | <<v66-20-0,Topo>> | xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[Próximo Capítulo &#62;]