include::./index.adoc[]

[[v46-16-0]]
=== 1 Coríntios, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v46-16-1]]

^<<v46-16-1,1>>^ Quanto à pergunta sobre o dinheiro que vocês estão coletando para o povo santo, sigam as mesmas instruções que dei às igrejas na Galácia.

[[v46-16-2]]

^<<v46-16-2,2>>^ No primeiro dia de cada semana, separem uma parte de sua renda. Não esperem até que eu chegue para então coletar tudo de uma vez.

[[v46-16-3]]

^<<v46-16-3,3>>^ Quando eu chegar, entregarei cartas de recomendação aos mensageiros que vocês escolherem para levar sua oferta a Jerusalém.

[[v46-16-4]]

^<<v46-16-4,4>>^ E, se for conveniente que eu também vá, eles viajarão comigo.

[[v46-16-5]]

^<<v46-16-5,5>>^ Eu os visitarei depois de ir à Macedônia, pois devo passar por lá.

[[v46-16-6]]

^<<v46-16-6,6>>^ Talvez permaneça um tempo com vocês, quem sabe todo o inverno. Depois vocês poderão me encaminhar para meu próximo destino.

[[v46-16-7]]

^<<v46-16-7,7>>^ Desta vez, não quero visitá-los apenas de passagem; quero ficar algum tempo, se o Senhor o permitir.

[[v46-16-8]]

^<<v46-16-8,8>>^ Por enquanto, permanecerei em Éfeso até a festa de Pentecostes.

[[v46-16-9]]

^<<v46-16-9,9>>^ Há uma porta inteiramente aberta para realizar um grande trabalho aqui, ainda que muitos se oponham a mim.

[[v46-16-10]]

^<<v46-16-10,10>>^ Quando Timóteo chegar, não deve se sentir intimidado por vocês. Ele está realizando a obra do Senhor, assim como eu.

[[v46-16-11]]

^<<v46-16-11,11>>^ Não deixem que ninguém o trate com desprezo. Enviem-no de volta para mim com sua bênção. Espero que ele venha junto com os demais irmãos.

[[v46-16-12]]

^<<v46-16-12,12>>^ Quanto a nosso irmão Apolo, insisti que ele os visitasse com os outros irmãos, mas ele não estava disposto a ir agora. Ele o fará mais tarde, quando tiver oportunidade.

[[v46-16-13]]

^<<v46-16-13,13>>^ Estejam vigilantes. Permaneçam firmes na fé. Sejam corajosos. Sejam fortes.

[[v46-16-14]]

^<<v46-16-14,14>>^ Façam tudo com amor.

[[v46-16-15]]

^<<v46-16-15,15>>^ Vocês sabem que Estéfanas e sua família foram os primeiros convertidos na Acaia e têm dedicado a vida ao serviço do povo de Deus. Peço, irmãos,

[[v46-16-16]]

^<<v46-16-16,16>>^ que se sujeitem a eles e a outros que, como eles, servem com tanta devoção.

[[v46-16-17]]

^<<v46-16-17,17>>^ Estou muito contente com a vinda de Estéfanas, Fortunato e Acaico. Eles proveram a ajuda que vocês, por não estarem aqui, não puderam me dar.

[[v46-16-18]]

^<<v46-16-18,18>>^ Eles têm sido um grande estímulo para mim, como foram para vocês. Valorizem todos que servem tão bem.

[[v46-16-19]]

^<<v46-16-19,19>>^ As igrejas aqui na província da Ásia enviam saudações no Senhor. Também os saúdam Áquila e Priscila e todos da igreja que se reúne na casa deles.

[[v46-16-20]]

^<<v46-16-20,20>>^ Todos os irmãos daqui lhes enviam saudações. Saúdem uns aos outros com beijo santo.

[[v46-16-21]]

^<<v46-16-21,21>>^ Esta é minha saudação de próprio punho: Paulo.

[[v46-16-22]]

^<<v46-16-22,22>>^ Se alguém não ama o Senhor, essa pessoa é maldita. Vem, nosso Senhor!

[[v46-16-23]]

^<<v46-16-23,23>>^ Que a graça do Senhor Jesus esteja com vocês.

[[v46-16-24]]

^<<v46-16-24,24>>^ Envio meu amor a todos vocês em Cristo Jesus.

'''

xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[&#60; Capítulo Anterior] | <<v46-16-0,Topo>> | xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[Próximo Capítulo &#62;]