include::./index.adoc[]

[[v46-7-0]]
=== 1 Coríntios, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v46-7-1]]

^<<v46-7-1,1>>^ Agora, quanto às perguntas que vocês me fizeram em sua carta, digo que é bom que o homem não toque em mulher.

[[v46-7-2]]

^<<v46-7-2,2>>^ Mas, uma vez que há tanta imoralidade sexual, cada homem deve ter sua própria esposa, e cada mulher, seu próprio marido.

[[v46-7-3]]

^<<v46-7-3,3>>^ O marido deve satisfazer as necessidades conjugais de sua esposa, e a esposa deve fazer o mesmo por seu marido.

[[v46-7-4]]

^<<v46-7-4,4>>^ A esposa não tem autoridade sobre seu corpo, mas sim o marido. Da mesma forma, não é o marido que tem autoridade sobre seu corpo, mas sim a esposa.

[[v46-7-5]]

^<<v46-7-5,5>>^ Não privem um ao outro de terem relações, a menos que ambos concordem em abster-se da intimidade sexual por certo tempo, a fim de se dedicarem de modo mais pleno à oração. Depois disso, unam-se novamente, para que Satanás não os tente por causa de sua falta de domínio próprio.

[[v46-7-6]]

^<<v46-7-6,6>>^ Digo isso como concessão, e não como mandamento.

[[v46-7-7]]

^<<v46-7-7,7>>^ Gostaria que todos fossem como eu, mas cada um tem seu próprio dom, concedido por Deus: um tem este tipo de dom, o outro, aquele.

[[v46-7-8]]

^<<v46-7-8,8>>^ Portanto, digo aos solteiros e às viúvas: é melhor que permaneçam como eu.

[[v46-7-9]]

^<<v46-7-9,9>>^ Mas, se não conseguirem se controlar, devem se casar. É melhor se casar que arder em desejo.

[[v46-7-10]]

^<<v46-7-10,10>>^ Para os casados, porém, tenho uma ordem que não vem de mim, mas do Senhor: a esposa não deve se separar do marido.

[[v46-7-11]]

^<<v46-7-11,11>>^ Mas, se o fizer, que permaneça solteira ou se reconcilie com ele. E o marido não deve se separar da esposa.

[[v46-7-12]]

^<<v46-7-12,12>>^ Agora me dirijo aos demais, embora o Senhor não tenha dado instrução específica a respeito. Se um irmão for casado com uma mulher descrente e ela estiver disposta a continuar vivendo com ele, não se separe dela.

[[v46-7-13]]

^<<v46-7-13,13>>^ E, se uma irmã for casada com um homem descrente e ele estiver disposto a continuar vivendo com ela, não se separe dele.

[[v46-7-14]]

^<<v46-7-14,14>>^ Pois o marido descrente é santificado pela esposa, e a esposa descrente é santificada pelo marido. Do contrário, os filhos seriam impuros, mas eles são santos.

[[v46-7-15]]

^<<v46-7-15,15>>^ Se, porém, o cônjuge descrente insistir em se separar, deixe-o ir. Nesses casos, o irmão ou a irmã não está mais preso à outra pessoa, pois Deus os chamou para viver em paz.

[[v46-7-16]]

^<<v46-7-16,16>>^ Você, esposa, como sabe que seu marido poderia ser salvo por sua causa? E você, marido, como sabe que sua esposa poderia ser salva por sua causa?

[[v46-7-17]]

^<<v46-7-17,17>>^ Cada um continue a viver na situação em que o Senhor o colocou, e cada um permaneça como estava quando Deus o chamou. Essa é minha regra para todas as igrejas.

[[v46-7-18]]

^<<v46-7-18,18>>^ Se um homem foi circuncidado antes de crer, não deve tentar mudar sua condição. E, se um homem não foi circuncidado antes de crer, não o deve ser agora.

[[v46-7-19]]

^<<v46-7-19,19>>^ Pois não faz diferença se ele foi circuncidado ou não. O importante é que obedeça aos mandamentos de Deus.

[[v46-7-20]]

^<<v46-7-20,20>>^ Sim, cada um deve permanecer como estava quando Deus o chamou.

[[v46-7-21]]

^<<v46-7-21,21>>^ Você foi chamado sendo escravo? Não deixe que isso o preocupe, mas, se tiver a oportunidade de ficar livre, aproveite-a.

[[v46-7-22]]

^<<v46-7-22,22>>^ E, se você era escravo quando o Senhor o chamou, agora é livre no Senhor. E, se você era livre quando o Senhor o chamou, agora é escravo de Cristo.

[[v46-7-23]]

^<<v46-7-23,23>>^ Vocês foram comprados por alto preço, portanto não se deixem escravizar pelo mundo.

[[v46-7-24]]

^<<v46-7-24,24>>^ Cada um de vocês, irmãos, deve permanecer como estava quando Deus os chamou.

[[v46-7-25]]

^<<v46-7-25,25>>^ Quanto à pergunta sobre as moças que ainda não se casaram, não tenho para elas um mandamento do Senhor. Em sua misericórdia, porém, o Senhor me deu sabedoria confiável, e eu a compartilharei com vocês.

[[v46-7-26]]

^<<v46-7-26,26>>^ Tendo em vista as dificuldades de nosso tempo, creio que é melhor que permaneçam como estão.

[[v46-7-27]]

^<<v46-7-27,27>>^ Se você já tem esposa, não procure se separar. Se não tem esposa, não procure se casar.

[[v46-7-28]]

^<<v46-7-28,28>>^ Se, contudo, vier a se casar, não é pecado. E, se uma moça se casar, também não é pecado. No entanto, aqueles que se casarem em tempos como os atuais terão de enfrentar dificuldades, e minha intenção é poupá-los disso.

[[v46-7-29]]

^<<v46-7-29,29>>^ Irmãos, isto é o que quero dizer: o tempo que resta é muito curto. Portanto, de agora em diante, aqueles que têm esposa devem agir como se não fossem casados.

[[v46-7-30]]

^<<v46-7-30,30>>^ Aqueles que choram, que se alegram ou que compram coisas não devem se entregar totalmente à tristeza, à alegria ou aos bens.

[[v46-7-31]]

^<<v46-7-31,31>>^ Aqueles que usam as coisas deste mundo não devem se apegar a elas, pois este mundo, como o conhecemos, logo passará.

[[v46-7-32]]

^<<v46-7-32,32>>^ Quero que estejam livres das preocupações desta vida. O homem que não é casado tem mais tempo para se dedicar à obra do Senhor e pensar em como agradá-lo.

[[v46-7-33]]

^<<v46-7-33,33>>^ Mas o homem casado precisa pensar em suas responsabilidades neste mundo e em como agradar sua esposa.

[[v46-7-34]]

^<<v46-7-34,34>>^ Seus interesses estão divididos. Da mesma forma, a mulher que não é casada ou que nunca se casou pode se dedicar ao Senhor e ser santa de corpo e espírito. Mas a mulher casada precisa pensar em suas responsabilidades aqui na terra e em como agradar seu marido.

[[v46-7-35]]

^<<v46-7-35,35>>^ Digo isso para seu bem, e não para lhes impor restrições. Quero que façam aquilo que os ajudará a servir melhor ao Senhor, com o mínimo possível de distrações.

[[v46-7-36]]

^<<v46-7-36,36>>^ Se, contudo, um homem acredita que está tratando sua noiva de forma inapropriada e que seus impulsos vão além de suas forças, que se case com ela, como é desejo dele. Não é pecado.

[[v46-7-37]]

^<<v46-7-37,37>>^ Mas, se tiver assumido um compromisso firme, e não houver urgência, e ele for capaz de controlar sua paixão, faz bem em não se casar.

[[v46-7-38]]

^<<v46-7-38,38>>^ Portanto, quem se casa com sua noiva faz bem, e quem não se casa faz melhor ainda.

[[v46-7-39]]

^<<v46-7-39,39>>^ A esposa está ligada ao marido enquanto ele viver. Se o marido morrer, ela está livre para se casar com quem quiser, desde que seja um irmão no Senhor.

[[v46-7-40]]

^<<v46-7-40,40>>^ Em minha opinião, porém, seria melhor que ela não se casasse novamente, e creio que, ao dizer isso, lhes dou o conselho do Espírito de Deus.

'''

xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[&#60; Capítulo Anterior] | <<v46-7-0,Topo>> | xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[Próximo Capítulo &#62;]