include::./index.adoc[]

[[v46-11-0]]
=== 1 Coríntios, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v46-11-1]]

^<<v46-11-1,1>>^ Sejam meus imitadores, como eu sou imitador de Cristo.

[[v46-11-2]]

^<<v46-11-2,2>>^ Eu os elogio porque vocês sempre têm se lembrado de mim e têm seguido os ensinamentos que lhes transmiti.

[[v46-11-3]]

^<<v46-11-3,3>>^ Mas quero que saibam de uma coisa: o cabeça de todo homem é Cristo, o cabeça da mulher é o homem, e o cabeça de Cristo é Deus.

[[v46-11-4]]

^<<v46-11-4,4>>^ O homem desonra sua cabeça se a cobre para orar ou profetizar.

[[v46-11-5]]

^<<v46-11-5,5>>^ Mas a mulher desonra sua cabeça se ora ou profetiza sem cobri-la, pois é como se tivesse raspado a cabeça.

[[v46-11-6]]

^<<v46-11-6,6>>^ Se ela se recusa a cobrir a cabeça, deve também cortar todo o cabelo! Mas, uma vez que é vergonhoso a mulher cortar o cabelo ou raspar a cabeça, deve cobri-la.

[[v46-11-7]]

^<<v46-11-7,7>>^ O homem não deve cobrir a cabeça, pois ele foi criado à imagem de Deus e reflete a glória de Deus. A mulher, porém, reflete a glória do homem.

[[v46-11-8]]

^<<v46-11-8,8>>^ Pois o homem não veio da mulher, mas a mulher veio do homem.

[[v46-11-9]]

^<<v46-11-9,9>>^ E o homem não foi criado para a mulher, mas a mulher foi criada para o homem.

[[v46-11-10]]

^<<v46-11-10,10>>^ Por esse motivo, e também por causa dos anjos, a mulher deve cobrir a cabeça, para mostrar que está debaixo de autoridade.

[[v46-11-11]]

^<<v46-11-11,11>>^ Entre o povo do Senhor, porém, as mulheres não são independentes dos homens, e os homens não são independentes das mulheres.

[[v46-11-12]]

^<<v46-11-12,12>>^ Pois, embora a mulher tenha vindo do homem, o homem nasce da mulher, e tudo vem de Deus.

[[v46-11-13]]

^<<v46-11-13,13>>^ Julguem por si mesmos: é correto uma mulher orar a Deus em público sem cobrir a cabeça?

[[v46-11-14]]

^<<v46-11-14,14>>^ A natureza não deixa claro que é vergonhoso o homem ter cabelo comprido?

[[v46-11-15]]

^<<v46-11-15,15>>^ E as mulheres não se orgulham de seu cabelo comprido? Pois ele lhes foi dado como manto.

[[v46-11-16]]

^<<v46-11-16,16>>^ Mas, se alguém quiser discutir a esse respeito, digo simplesmente que não temos outro costume. E as outras igrejas de Deus pensam da mesma forma.

[[v46-11-17]]

^<<v46-11-17,17>>^ Nas instruções a seguir, porém, não posso elogiá-los, pois, quando vocês se reúnem, fazem mais mal que bem.

[[v46-11-18]]

^<<v46-11-18,18>>^ Primeiro, ouço que há divisões quando vocês se reúnem como igreja e, até certo ponto, eu o creio.

[[v46-11-19]]

^<<v46-11-19,19>>^ Suponho que seja necessário haver divisões entre vocês para que se reconheçam os que são aprovados!

[[v46-11-20]]

^<<v46-11-20,20>>^ Quando vocês se reúnem, não estão interessados de fato na ceia do Senhor.

[[v46-11-21]]

^<<v46-11-21,21>>^ Alguns de vocês se apressam em comer a própria refeição; como resultado, alguns passam fome, enquanto outros ficam embriagados.

[[v46-11-22]]

^<<v46-11-22,22>>^ Será que vocês não têm casa onde comer e beber? Ou querem mesmo envergonhar a igreja de Deus e humilhar os pobres? Que devo dizer? Querem que eu os elogie? Certamente não os elogiarei por isso!

[[v46-11-23]]

^<<v46-11-23,23>>^ Pois eu lhes transmiti aquilo que recebi do Senhor. Na noite em que o Senhor Jesus foi traído, ele tomou o pão,

[[v46-11-24]]

^<<v46-11-24,24>>^ agradeceu a Deus, partiu-o e disse: "Este é meu corpo, que é entregue por vocês. Façam isto em memória de mim".

[[v46-11-25]]

^<<v46-11-25,25>>^ Da mesma forma, depois da ceia, tomou o cálice e disse: "Este cálice é a nova aliança, confirmada com meu sangue. Façam isto em memória de mim, sempre que o beberem".

[[v46-11-26]]

^<<v46-11-26,26>>^ Porque cada vez que vocês comem desse pão e bebem desse cálice, anunciam a morte do Senhor até que ele venha.

[[v46-11-27]]

^<<v46-11-27,27>>^ Assim, quem come do pão ou bebe do cálice do Senhor indignamente é culpado de pecar contra o corpo e o sangue do Senhor.

[[v46-11-28]]

^<<v46-11-28,28>>^ Portanto, examinem-se antes de comer do pão e beber do cálice,

[[v46-11-29]]

^<<v46-11-29,29>>^ pois, se comem do pão ou bebem do cálice sem honrar o corpo de Cristo, comem e bebem julgamento contra si mesmos.

[[v46-11-30]]

^<<v46-11-30,30>>^ Por isso muitos de vocês estão fracos e doentes e alguns até adormeceram.

[[v46-11-31]]

^<<v46-11-31,31>>^ Se examinássemos a nós mesmos, não seríamos julgados dessa maneira.

[[v46-11-32]]

^<<v46-11-32,32>>^ Mas, quando somos julgados pelo Senhor, estamos sendo disciplinados para que não sejamos condenados com o mundo.

[[v46-11-33]]

^<<v46-11-33,33>>^ Portanto, meus irmãos, quando se reunirem para comer, esperem uns pelos outros.

[[v46-11-34]]

^<<v46-11-34,34>>^ Se estiverem com fome, comam em casa, a fim de não trazer julgamento sobre si mesmos ao se reunirem. Eu lhes darei instruções a respeito de outros assuntos depois que chegar aí.

'''

xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[Próximo Capítulo &#62;]