include::./index.adoc[]

[[v46-4-0]]
=== 1 Coríntios, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v46-4-1]]

^<<v46-4-1,1>>^ Portanto, devemos ser considerados simples servos de Cristo, encarregados de explicar os mistérios de Deus.

[[v46-4-2]]

^<<v46-4-2,2>>^ De um encarregado espera-se que seja fiel.

[[v46-4-3]]

^<<v46-4-3,3>>^ Quanto a mim, pouco importa como sou avaliado por vocês ou por qualquer autoridade humana. Na verdade, nem minha própria avaliação é importante.

[[v46-4-4]]

^<<v46-4-4,4>>^ Minha consciência está limpa, mas isso não prova que estou certo. O Senhor é quem me avaliará e decidirá.

[[v46-4-5]]

^<<v46-4-5,5>>^ Portanto, não julguem ninguém antes do tempo, antes que o Senhor volte. Pois ele trará à luz nossos segredos mais obscuros e revelará nossas intenções mais íntimas. Então Deus dará a cada um a devida aprovação.

[[v46-4-6]]

^<<v46-4-6,6>>^ Irmãos, usei a mim mesmo e a Apolo para ilustrar o que lhes tenho dito. Se aprenderem a não ir além daquilo que está escrito, não se orgulharão de um à custa de outro.

[[v46-4-7]]

^<<v46-4-7,7>>^ Pois que direito vocês têm de julgar desse modo? O que vocês têm que Deus não lhes tenha dado? E, se tudo que temos vem de Deus, por que nos orgulharmos como se não fosse uma dádiva?

[[v46-4-8]]

^<<v46-4-8,8>>^ Vocês consideram que já têm tudo de que precisam. Pensam que já são ricos e até já começaram a reinar sem nós! Gostaria que, de fato, já estivessem reinando, pois então eu reinaria com vocês.

[[v46-4-9]]

^<<v46-4-9,9>>^ Por vezes me parece que Deus colocou a nós, os apóstolos, em último lugar, como condenados à morte, espetáculo para o mundo inteiro, tanto para as pessoas como para os anjos.

[[v46-4-10]]

^<<v46-4-10,10>>^ Nossa dedicação a Cristo nos faz parecer loucos, mas vocês afirmam ser sábios em Cristo. Nós somos fracos, mas vocês são fortes. Vocês são respeitados, mas nós somos ridicularizados.

[[v46-4-11]]

^<<v46-4-11,11>>^ Até agora passamos fome e sede, e não temos roupa necessária para nos manter aquecidos. Somos espancados e não temos casa.

[[v46-4-12]]

^<<v46-4-12,12>>^ Trabalhamos arduamente com as próprias mãos para obter sustento. Abençoamos quem nos amaldiçoa. Somos pacientes com quem nos maltrata.

[[v46-4-13]]

^<<v46-4-13,13>>^ Respondemos com bondade quando falam mal de nós. E, no entanto, até o momento, temos sido tratados como a escória do mundo, como o lixo de todos.

[[v46-4-14]]

^<<v46-4-14,14>>^ Não escrevo estas coisas para envergonhá-los, mas para adverti-los como meus filhos amados.

[[v46-4-15]]

^<<v46-4-15,15>>^ Pois, ainda que tivessem dez mil mestres em Cristo, vocês não têm muitos pais, pois eu me tornei seu pai espiritual em Cristo Jesus por meio das boas-novas que lhes anunciei.

[[v46-4-16]]

^<<v46-4-16,16>>^ Portanto, suplico-lhes que sejam meus imitadores.

[[v46-4-17]]

^<<v46-4-17,17>>^ Por isso enviei Timóteo, meu filho amado e fiel no Senhor. Ele os lembrará de como sigo Cristo Jesus, de acordo com o que ensino em todas as igrejas, em qualquer lugar aonde vou.

[[v46-4-18]]

^<<v46-4-18,18>>^ Alguns de vocês se tornaram arrogantes, pensando que não irei mais visitá-los.

[[v46-4-19]]

^<<v46-4-19,19>>^ Mas eu irei, e logo, se o Senhor permitir, e então verei se esses arrogantes apenas fazem discursos pretensiosos ou se têm, de fato, o poder de Deus.

[[v46-4-20]]

^<<v46-4-20,20>>^ Pois o reino de Deus não consiste apenas em palavras, mas em poder.

[[v46-4-21]]

^<<v46-4-21,21>>^ O que vocês escolhem? Devo ir com vara para castigá-los ou com amor e espírito de mansidão?

'''

xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[&#60; Capítulo Anterior] | <<v46-4-0,Topo>> | xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[Próximo Capítulo &#62;]