include::./index.adoc[]

[[v46-3-0]]
=== 1 Coríntios, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v46-3-1]]

^<<v46-3-1,1>>^ Irmãos, quando estive com vocês, não pude lhes falar como a pessoas espirituais, mas como se pertencessem a este mundo ou fossem criancinhas em Cristo.

[[v46-3-2]]

^<<v46-3-2,2>>^ Tive de alimentá-los com leite, e não com alimento sólido, pois não estavam aptos para recebê-lo. E ainda não estão,

[[v46-3-3]]

^<<v46-3-3,3>>^ porque ainda são controlados por sua natureza humana. Têm ciúme uns dos outros, discutem e brigam entre si. Acaso isso não mostra que são controlados por sua natureza humana e que vivem como pessoas do mundo?

[[v46-3-4]]

^<<v46-3-4,4>>^ Quando um de vocês diz: "Eu sigo Paulo", e o outro diz: "Eu sigo Apolo", não estão agindo exatamente como as pessoas do mundo?

[[v46-3-5]]

^<<v46-3-5,5>>^ Afinal, quem é Paulo? Quem é Apolo? Somos apenas servos de Deus por meio dos quais vocês vieram a crer. Cada um de nós fez o trabalho do qual o Senhor nos encarregou.

[[v46-3-6]]

^<<v46-3-6,6>>^ Eu plantei e Apolo regou, mas quem fez crescer foi Deus.

[[v46-3-7]]

^<<v46-3-7,7>>^ Não importa quem planta ou quem rega, mas sim Deus, que faz crescer.

[[v46-3-8]]

^<<v46-3-8,8>>^ Quem planta e quem rega trabalham para o mesmo fim, e ambos serão recompensados por seu árduo trabalho.

[[v46-3-9]]

^<<v46-3-9,9>>^ Pois nós somos colaboradores de Deus, e vocês são lavoura de Deus e edifício de Deus.

[[v46-3-10]]

^<<v46-3-10,10>>^ Pela graça que me foi dada, lancei o alicerce como um construtor competente, e agora outros estão construindo sobre ele. Mas quem constrói sobre o alicerce precisa ter muito cuidado,

[[v46-3-11]]

^<<v46-3-11,11>>^ pois ninguém pode lançar outro alicerce além daquele que já foi posto, isto é, Jesus Cristo.

[[v46-3-12]]

^<<v46-3-12,12>>^ Aqueles que constroem sobre esse alicerce podem usar vários materiais: ouro, prata, pedras preciosas, madeira, feno ou palha.

[[v46-3-13]]

^<<v46-3-13,13>>^ No dia do juízo, porém, o fogo revelará que tipo de obra cada construtor realizou, e o fogo mostrará se a obra tem algum valor.

[[v46-3-14]]

^<<v46-3-14,14>>^ Se ela sobreviver, o construtor receberá recompensa.

[[v46-3-15]]

^<<v46-3-15,15>>^ Se ela queimar, o construtor sofrerá grande prejuízo, mas será salvo como alguém que é resgatado do meio do fogo.

[[v46-3-16]]

^<<v46-3-16,16>>^ Vocês não entendem que são o templo de Deus e que o Espírito de Deus habita em vocês?

[[v46-3-17]]

^<<v46-3-17,17>>^ Deus destruirá quem destruir seu templo. Pois o templo de Deus é santo, e vocês são esse templo.

[[v46-3-18]]

^<<v46-3-18,18>>^ Que ninguém se engane. Se algum de vocês pensa que é sábio conforme os padrões desta era, deve tornar-se louco a fim de ser verdadeiramente sábio.

[[v46-3-19]]

^<<v46-3-19,19>>^ Pois a sabedoria deste mundo é loucura para Deus. Como dizem as Escrituras: "Ele apanha os sábios na armadilha da própria astúcia deles".

[[v46-3-20]]

^<<v46-3-20,20>>^ E também: "O Senhor conhece os pensamentos dos sábios; sabe que nada valem".

[[v46-3-21]]

^<<v46-3-21,21>>^ Portanto, não se orgulhem de seguir líderes humanos, pois tudo lhes pertence:

[[v46-3-22]]

^<<v46-3-22,22>>^ Paulo, Apolo ou Pedro, o mundo, a vida e a morte, o presente e o futuro. Tudo é de vocês,

[[v46-3-23]]

^<<v46-3-23,23>>^ e vocês são de Cristo, e Cristo é de Deus.

'''

xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[&#60; Capítulo Anterior] | <<v46-3-0,Topo>> | xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[Próximo Capítulo &#62;]