include::./index.adoc[]

[[v46-5-0]]
=== 1 Coríntios, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v46-5-1]]

^<<v46-5-1,1>>^ Comenta-se por toda parte que há imoralidade sexual em seu meio, imoralidade que nem mesmo os pagãos praticam. Soube de um homem entre vocês que mantém relações sexuais com a própria madrasta.

[[v46-5-2]]

^<<v46-5-2,2>>^ Como podem se orgulhar disso? Deveriam lamentar-se e excluir de sua comunhão o homem que cometeu tamanha ofensa.

[[v46-5-3]]

^<<v46-5-3,3>>^ Embora eu não esteja com vocês em pessoa, estou presente em espírito. E, como se estivesse aí, já condenei esse homem

[[v46-5-4]]

^<<v46-5-4,4>>^ em nome do Senhor Jesus. Convoquem uma reunião. Estarei com vocês em meu espírito, e o poder de nosso Senhor Jesus também estará presente.

[[v46-5-5]]

^<<v46-5-5,5>>^ Entreguem esse homem a Satanás, para que o corpo seja punido e o espírito seja salvo no dia do Senhor.

[[v46-5-6]]

^<<v46-5-6,6>>^ Não é nada bom se orgulharem disso. Não percebem que esse pecado é como um pouco de fermento que leveda toda a massa?

[[v46-5-7]]

^<<v46-5-7,7>>^ Livrem-se do fermento velho, para que sejam massa nova, sem fermento, o que de fato são. Cristo, nosso Cordeiro pascal, foi sacrificado.

[[v46-5-8]]

^<<v46-5-8,8>>^ Por isso, celebremos a festa não com o velho pão, fermentado com maldade e perversidade, mas com o novo pão da sinceridade e da verdade, sem nenhum fermento.

[[v46-5-9]]

^<<v46-5-9,9>>^ Quando lhes escrevi antes, disse que não deviam se associar com pessoas que se entregam à imoralidade sexual.

[[v46-5-10]]

^<<v46-5-10,10>>^ Com isso, porém, não me referia a descrentes que vivem em imoralidade sexual, ou são avarentos, ou exploram os outros, ou adoram ídolos. Vocês teriam de sair deste mundo para evitar pessoas desse tipo.

[[v46-5-11]]

^<<v46-5-11,11>>^ O que eu queria dizer era que vocês não devem se associar a alguém que afirma ser irmão mas vive em imoralidade sexual, ou é avarento, ou adora ídolos, ou insulta as pessoas, ou é bêbado ou explora os outros. Nem ao menos comam com gente assim.

[[v46-5-12]]

^<<v46-5-12,12>>^ Não cabe a mim julgar os de fora, mas certamente cabe a vocês julgar os que estão dentro.

[[v46-5-13]]

^<<v46-5-13,13>>^ Deus julgará os de fora. Portanto, eliminem o mal do meio de vocês.

'''

xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[&#60; Capítulo Anterior] | <<v46-5-0,Topo>> | xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[Próximo Capítulo &#62;]