include::./index.adoc[]

[[v46-9-0]]
=== 1 Coríntios, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v46-9-1]]

^<<v46-9-1,1>>^ Acaso não sou livre como qualquer outro? Não sou apóstolo? Não vi Jesus, nosso Senhor, com meus próprios olhos? Não são vocês resultado de meu trabalho no Senhor?

[[v46-9-2]]

^<<v46-9-2,2>>^ Mesmo que outros pensem que não sou apóstolo, certamente o sou para vocês. Vocês mesmos são prova de que sou apóstolo do Senhor.

[[v46-9-3]]

^<<v46-9-3,3>>^ Esta é minha resposta aos que questionam minha autoridade.

[[v46-9-4]]

^<<v46-9-4,4>>^ Acaso não temos o direito de receber comida e bebida por nosso trabalho?

[[v46-9-5]]

^<<v46-9-5,5>>^ Não temos o direito de levar conosco uma esposa crente, como fazem os outros apóstolos, e como fazem os irmãos do Senhor e Pedro?

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou será que só Barnabé e eu precisamos trabalhar para nos sustentarmos?

[[v46-9-7]]

^<<v46-9-7,7>>^ Que soldado precisa pagar pelas próprias despesas? Que agricultor planta uma videira e não tem direito de comer de seus frutos? Que pastor cuida de um rebanho e não tem permissão de tomar de seu leite?

[[v46-9-8]]

^<<v46-9-8,8>>^ Será que expresso apenas uma opinião humana ou a lei diz o mesmo?

[[v46-9-9]]

^<<v46-9-9,9>>^ Pois está escrito na lei de Moisés: "Não amordacem o boi para impedir que ele coma enquanto trilha os cereais". Deus estava pensando apenas nos bois quando disse isso?

[[v46-9-10]]

^<<v46-9-10,10>>^ Será que, na verdade, não estava se referindo a nós? Sim, essas palavras foram escritas a nosso respeito e, portanto, quem ara e quem trilha o cereal deve ter a esperança de receber uma parte da colheita.

[[v46-9-11]]

^<<v46-9-11,11>>^ Se plantamos sementes espirituais entre vocês, não temos direito a uma colheita material?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se vocês sustentam outros que pregam a vocês, não temos ainda mais direito de receber o mesmo sustento? Mas nunca fizemos uso desse direito. Preferimos suportar qualquer coisa a fim de não sermos obstáculo para as boas-novas a respeito de Cristo.

[[v46-9-13]]

^<<v46-9-13,13>>^ Vocês não sabem que os que trabalham no templo se alimentam das ofertas levadas ao templo, e os que servem diante do altar recebem uma parte dos sacrifícios oferecidos no altar?

[[v46-9-14]]

^<<v46-9-14,14>>^ Da mesma forma, o Senhor ordenou que os que anunciam as boas-novas vivam pelas boas-novas.

[[v46-9-15]]

^<<v46-9-15,15>>^ Contudo, nunca usei de nenhum desses direitos. Não escrevo isso para sugerir que desejo agora começar a fazê-lo. De fato, prefiro morrer a perder o privilégio de me orgulhar de pregar sem cobrar nada.

[[v46-9-16]]

^<<v46-9-16,16>>^ E, no entanto, não posso me orgulhar de anunciar as boas-novas, pois sou impelido por Deus a fazê-lo. Ai de mim se não anunciar as boas-novas!

[[v46-9-17]]

^<<v46-9-17,17>>^ Se o fizesse por minha própria iniciativa, mereceria pagamento. Mas não tenho escolha, pois Deus me confiou essa responsabilidade.

[[v46-9-18]]

^<<v46-9-18,18>>^ Qual é, então, minha recompensa? É a oportunidade de anunciar as boas-novas sem cobrar nada de ninguém, de modo a não desfrutar os direitos que tenho por anunciar as boas-novas.

[[v46-9-19]]

^<<v46-9-19,19>>^ Embora eu seja um homem livre, fiz-me escravo de todos para levar muitos a Cristo.

[[v46-9-20]]

^<<v46-9-20,20>>^ Quando estive com os judeus, vivi como os judeus para levá-los a Cristo. Quando estive com os que seguem a lei judaica, vivi debaixo dessa lei. Embora não esteja sujeito à lei, agi desse modo para levar a Cristo aqueles que estão debaixo da lei.

[[v46-9-21]]

^<<v46-9-21,21>>^ Quando estou com os que não seguem a lei judaica, também vivo de modo independente da lei para levá-los a Cristo. Não ignoro, porém, a lei de Deus, pois obedeço à lei de Cristo.

[[v46-9-22]]

^<<v46-9-22,22>>^ Quando estou com os fracos, também me torno fraco, pois quero levar os fracos a Cristo. Sim, tento encontrar algum ponto em comum com todos, fazendo todo o possível para salvar alguns.

[[v46-9-23]]

^<<v46-9-23,23>>^ Faço tudo isso para espalhar as boas-novas e participar de suas bênçãos.

[[v46-9-24]]

^<<v46-9-24,24>>^ Vocês não sabem que, numa corrida, todos competem, mas apenas um ganha o prêmio? Portanto, corram para vencer.

[[v46-9-25]]

^<<v46-9-25,25>>^ O atleta precisa ser disciplinado sob todos os aspectos. Ele se esforça para ganhar um prêmio perecível. Nós, porém, o fazemos para ganhar um prêmio eterno.

[[v46-9-26]]

^<<v46-9-26,26>>^ Por isso não corro sem objetivo nem luto como quem dá golpes no ar.

[[v46-9-27]]

^<<v46-9-27,27>>^ Disciplino meu corpo como um atleta, treinando-o para fazer o que deve, de modo que, depois de ter pregado a outros, eu mesmo não seja desqualificado.

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]