include::./index.adoc[]

[[v46-15-0]]
=== 1 Coríntios, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v46-15-1]]

^<<v46-15-1,1>>^ Agora, irmãos, quero lembrá-los das boas-novas que lhes anunciei anteriormente. Vocês as receberam e nelas permanecem firmes.

[[v46-15-2]]

^<<v46-15-2,2>>^ São essas boas-novas que os salvam, se continuarem a crer na mensagem como lhes anunciei; do contrário, sua fé é inútil.

[[v46-15-3]]

^<<v46-15-3,3>>^ Eu lhes transmiti o que era mais importante e o que também me foi transmitido: Cristo morreu por nossos pecados, como dizem as Escrituras.

[[v46-15-4]]

^<<v46-15-4,4>>^ Ele foi sepultado e ressuscitou no terceiro dia, como dizem as Escrituras.

[[v46-15-5]]

^<<v46-15-5,5>>^ Apareceu a Pedro e, mais tarde, aos Doze.

[[v46-15-6]]

^<<v46-15-6,6>>^ Depois disso, apareceu a mais de quinhentos irmãos de uma só vez, a maioria dos quais ainda está viva, embora alguns já tenham adormecido.

[[v46-15-7]]

^<<v46-15-7,7>>^ Mais tarde, apareceu a Tiago e, posteriormente, a todos os apóstolos.

[[v46-15-8]]

^<<v46-15-8,8>>^ Por último, apareceu também a mim, como se eu tivesse nascido fora de tempo.

[[v46-15-9]]

^<<v46-15-9,9>>^ Pois sou o mais insignificante dos apóstolos. Aliás, nem sou digno de ser chamado apóstolo, pois persegui a igreja de Deus.

[[v46-15-10]]

^<<v46-15-10,10>>^ O que agora sou, porém, deve-se inteiramente à graça que Deus derramou sobre mim, e que não foi inútil. Trabalhei com mais dedicação que qualquer outro apóstolo e, no entanto, não fui eu, mas Deus que, em sua graça, operou por meu intermédio.

[[v46-15-11]]

^<<v46-15-11,11>>^ Logo, não faz diferença se eu prego ou se eles pregam, pois todos nós anunciamos a mesma mensagem na qual vocês já creram.

[[v46-15-12]]

^<<v46-15-12,12>>^ Pois bem, se proclamamos que Cristo ressuscitou dos mortos, por que alguns de vocês afirmam não haver ressurreição dos mortos?

[[v46-15-13]]

^<<v46-15-13,13>>^ Pois, se não existe ressurreição dos mortos, Cristo não ressuscitou.

[[v46-15-14]]

^<<v46-15-14,14>>^ E, se Cristo não ressuscitou, nossa pregação é inútil, e a fé que vocês têm também é inútil.

[[v46-15-15]]

^<<v46-15-15,15>>^ Então estamos todos mentindo a respeito de Deus, pois afirmamos que ele ressuscitou a Cristo. Mas, se não existe ressurreição dos mortos, isso não pode ser verdade.

[[v46-15-16]]

^<<v46-15-16,16>>^ E, se não existe ressurreição dos mortos, então Cristo também não ressuscitou.

[[v46-15-17]]

^<<v46-15-17,17>>^ E, se Cristo não ressuscitou, a fé que vocês têm é inútil, e vocês ainda estão em seus pecados.

[[v46-15-18]]

^<<v46-15-18,18>>^ Nesse caso, todos que adormeceram crendo em Cristo estão perdidos!

[[v46-15-19]]

^<<v46-15-19,19>>^ Se nossa esperança em Cristo vale apenas para esta vida, somos os mais dignos de pena em todo o mundo.

[[v46-15-20]]

^<<v46-15-20,20>>^ Mas Cristo de fato ressuscitou dos mortos. Ele é o primeiro fruto da colheita de todos que adormeceram.

[[v46-15-21]]

^<<v46-15-21,21>>^ Uma vez que a morte entrou no mundo por meio de um único homem, agora a ressurreição dos mortos começou por meio de um só homem.

[[v46-15-22]]

^<<v46-15-22,22>>^ Assim como todos morremos em Adão, todos que são de Cristo receberão nova vida.

[[v46-15-23]]

^<<v46-15-23,23>>^ Mas essa ressurreição tem uma sequência: Cristo ressuscitou como o primeiro fruto da colheita, e depois todos que são de Cristo ressuscitarão quando ele voltar.

[[v46-15-24]]

^<<v46-15-24,24>>^ Então virá o fim, quando ele entregará o reino a Deus, o Pai, depois de ter destruído todos os governantes e autoridades e todo poder.

[[v46-15-25]]

^<<v46-15-25,25>>^ Pois é necessário que Cristo reine até que tenha colocado todos os seus inimigos debaixo de seus pés.

[[v46-15-26]]

^<<v46-15-26,26>>^ E o último inimigo a ser destruído é a morte.

[[v46-15-27]]

^<<v46-15-27,27>>^ Pois as Escrituras dizem: "Deus pôs todas as coisas sob a autoridade dele". Claro que, quando se diz que "todas as coisas estão sob a autoridade dele", isso não inclui aquele que conferiu essa autoridade a Cristo.

[[v46-15-28]]

^<<v46-15-28,28>>^ Então, quando todas as coisas estiverem sob a autoridade do Filho, ele se colocará sob a autoridade de Deus, para que Deus, que deu a seu Filho autoridade sobre todas as coisas, seja absolutamente supremo sobre todas as coisas em toda parte.

[[v46-15-29]]

^<<v46-15-29,29>>^ E o que dizer dos que se batizam em favor dos mortos? Se os mortos não ressuscitam, como dizem eles, por que se batizam em favor dos que já morreram?

[[v46-15-30]]

^<<v46-15-30,30>>^ E nós, por que arriscamos a vida o tempo todo?

[[v46-15-31]]

^<<v46-15-31,31>>^ Pois eu afirmo, irmãos, que enfrento a morte diariamente, assim como afirmo meu orgulho daquilo que Cristo Jesus, nosso Senhor, fez em vocês.

[[v46-15-32]]

^<<v46-15-32,32>>^ E, se não haverá ressurreição dos mortos, de que me adiantou ter lutado contra feras, isto é, aquela gente de Éfeso? Se não há ressurreição, "comamos e bebamos, porque amanhã morreremos!".

[[v46-15-33]]

^<<v46-15-33,33>>^ Não se deixem enganar pelos que dizem essas coisas, pois "as más companhias corrompem o bom caráter".

[[v46-15-34]]

^<<v46-15-34,34>>^ Pensem bem sobre o que é certo e parem de pecar. Pois, para sua vergonha, eu lhes digo que alguns de vocês não têm o menor conhecimento de Deus.

[[v46-15-35]]

^<<v46-15-35,35>>^ Alguém pode perguntar: "Como os mortos ressuscitarão? Que tipo de corpo terão?".

[[v46-15-36]]

^<<v46-15-36,36>>^ Que perguntas tolas! A semente só cresce e se transforma em planta depois que morre.

[[v46-15-37]]

^<<v46-15-37,37>>^ E aquilo que se coloca no solo não é a planta que crescerá, mas apenas uma semente de trigo ou de alguma outra planta.

[[v46-15-38]]

^<<v46-15-38,38>>^ Então Deus lhe dá o novo corpo como ele quer. Um tipo diferente de planta cresce de cada tipo de semente.

[[v46-15-39]]

^<<v46-15-39,39>>^ Da mesma forma, há tipos diferentes de carne: um tipo para os seres humanos, outro para os animais, outro para as aves e outro para os peixes.

[[v46-15-40]]

^<<v46-15-40,40>>^ Também há corpos celestes e corpos terrestres. A glória dos corpos celestes é diferente da glória dos corpos terrestres.

[[v46-15-41]]

^<<v46-15-41,41>>^ O sol tem um tipo de glória, enquanto a lua e as estrelas têm outro. E até mesmo as estrelas diferem em glória umas das outras.

[[v46-15-42]]

^<<v46-15-42,42>>^ O mesmo acontece com a ressurreição dos mortos. Quando morremos, o corpo terreno é plantado no solo, mas ressuscitará para viver para sempre.

[[v46-15-43]]

^<<v46-15-43,43>>^ Nosso corpo é enterrado em desonra, mas ressuscitará em glória. É enterrado em fraqueza, mas ressuscitará em força.

[[v46-15-44]]

^<<v46-15-44,44>>^ É enterrado como corpo humano natural, mas ressuscitará como corpo espiritual. Pois, assim como há corpos naturais, também há corpos espirituais.

[[v46-15-45]]

^<<v46-15-45,45>>^ As Escrituras nos dizem: "O primeiro homem, Adão, se tornou ser vivo". Mas o último Adão é espírito que dá vida.

[[v46-15-46]]

^<<v46-15-46,46>>^ Primeiro vem o corpo natural, depois o corpo espiritual.

[[v46-15-47]]

^<<v46-15-47,47>>^ O primeiro homem foi feito do pó da terra, enquanto o segundo homem veio do céu.

[[v46-15-48]]

^<<v46-15-48,48>>^ Os que são da terra são como o homem terreno, e os que são do céu são como o homem celestial.

[[v46-15-49]]

^<<v46-15-49,49>>^ Da mesma forma que agora somos como o homem terreno, algum dia seremos como o homem celestial.

[[v46-15-50]]

^<<v46-15-50,50>>^ Estou dizendo, irmãos, que nosso corpo físico não pode herdar o reino de Deus. Este corpo mortal não pode herdar aquilo que durará para sempre.

[[v46-15-51]]

^<<v46-15-51,51>>^ Mas eu lhes revelarei um segredo maravilhoso: nem todos dormiremos, mas todos seremos transformados!

[[v46-15-52]]

^<<v46-15-52,52>>^ Acontecerá num instante, num piscar de olhos, ao som da última trombeta. Pois, quando a última trombeta soar, aqueles que morreram ressuscitarão a fim de viver para sempre. E nós que estivermos vivos também seremos transformados.

[[v46-15-53]]

^<<v46-15-53,53>>^ Pois nosso corpo mortal precisa ser transformado em corpo imortal.

[[v46-15-54]]

^<<v46-15-54,54>>^ Então, quando nosso corpo mortal tiver sido transformado em corpo imortal, se cumprirá a passagem das Escrituras que diz: "A morte foi engolida na vitória.

[[v46-15-55]]

^<<v46-15-55,55>>^ Ó morte, onde está sua vitória? Ó morte, onde está seu aguilhão?".

[[v46-15-56]]

^<<v46-15-56,56>>^ O pecado é o aguilhão da morte que nos fere, e a lei é o que torna o pecado mais forte.

[[v46-15-57]]

^<<v46-15-57,57>>^ Mas graças a Deus, que nos dá vitória sobre o pecado e sobre a morte por meio de nosso Senhor Jesus Cristo!

[[v46-15-58]]

^<<v46-15-58,58>>^ Portanto, meus amados irmãos, sejam fortes e firmes. Trabalhem sempre para o Senhor com entusiasmo, pois vocês sabem que nada do que fazem para o Senhor é inútil.

'''

xref:046-1-corintios/046-1-corintios-014.adoc#v46-14-0[&#60; Capítulo Anterior] | <<v46-15-0,Topo>> | xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[Próximo Capítulo &#62;]