include::./index.adoc[]

[[v46-10-0]]
=== 1 Coríntios, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v46-10-1]]

^<<v46-10-1,1>>^ Irmãos, não quero que vocês se esqueçam do que aconteceu muito tempo atrás, quando nossos antepassados foram guiados por uma nuvem que ia adiante deles e atravessaram o mar.

[[v46-10-2]]

^<<v46-10-2,2>>^ Na nuvem e no mar, todos foram batizados como seguidores de Moisés.

[[v46-10-3]]

^<<v46-10-3,3>>^ Todos comeram do mesmo alimento espiritual

[[v46-10-4]]

^<<v46-10-4,4>>^ e todos beberam da mesma água espiritual, pois beberam da rocha espiritual que os acompanhava, e essa rocha era Cristo.

[[v46-10-5]]

^<<v46-10-5,5>>^ No entanto, Deus não se agradou da maioria deles, e seus corpos ficaram espalhados pelo deserto.

[[v46-10-6]]

^<<v46-10-6,6>>^ Tais coisas aconteceram como advertência para nós, a fim de que não cobicemos o que é mau, como eles cobiçaram,

[[v46-10-7]]

^<<v46-10-7,7>>^ nem adoremos ídolos, como alguns deles adoraram. Segundo as Escrituras, "todos comeram e beberam e se entregaram à farra".

[[v46-10-8]]

^<<v46-10-8,8>>^ E não devemos praticar a imoralidade sexual, como alguns deles praticaram, e morreram 23 mil pessoas num só dia.

[[v46-10-9]]

^<<v46-10-9,9>>^ Também não devemos pôr Cristo à prova, como alguns deles puseram, e foram mortos por serpentes.

[[v46-10-10]]

^<<v46-10-10,10>>^ E não se queixem como alguns deles se queixaram, e foram destruídos pelo anjo da morte.

[[v46-10-11]]

^<<v46-10-11,11>>^ Essas coisas que aconteceram a eles nos servem como exemplo. Foram escritas como advertência para nós, que vivemos no fim dos tempos.

[[v46-10-12]]

^<<v46-10-12,12>>^ Portanto, se vocês pensam que estão de pé, cuidem para que não caiam.

[[v46-10-13]]

^<<v46-10-13,13>>^ As tentações em sua vida não são diferentes daquelas que outros enfrentaram. Deus é fiel, e ele não permitirá tentações maiores do que vocês podem suportar. Quando forem tentados, ele mostrará uma saída para que consigam resistir.

[[v46-10-14]]

^<<v46-10-14,14>>^ Portanto, meus amados, fujam do culto aos ídolos.

[[v46-10-15]]

^<<v46-10-15,15>>^ Vocês são pessoas sensatas. Julguem por si mesmos se o que digo é verdade.

[[v46-10-16]]

^<<v46-10-16,16>>^ Quando abençoamos o cálice à mesa, não participamos do sangue de Cristo? E, quando partimos o pão, não participamos do corpo de Cristo?

[[v46-10-17]]

^<<v46-10-17,17>>^ E, embora sejamos muitos, todos comemos do mesmo pão, mostrando que somos um só corpo.

[[v46-10-18]]

^<<v46-10-18,18>>^ Pensem no povo de Israel. Acaso os que comiam dos sacrifícios não partilhavam do mesmo altar?

[[v46-10-19]]

^<<v46-10-19,19>>^ Então, o que estou tentando dizer? Que a comida oferecida a ídolos tem alguma importância, ou que os ídolos são deuses de verdade?

[[v46-10-20]]

^<<v46-10-20,20>>^ De maneira nenhuma! Estou dizendo que esses sacrifícios são oferecidos a demônios, e não a Deus. E não quero que vocês tenham parte com demônios.

[[v46-10-21]]

^<<v46-10-21,21>>^ Vocês não podem beber do cálice do Senhor e também do cálice de demônios. Não podem participar da mesa do Senhor e também da mesa de demônios.

[[v46-10-22]]

^<<v46-10-22,22>>^ Acaso nos atreveremos a despertar o ciúme do Senhor? Somos mais fortes que ele?

[[v46-10-23]]

^<<v46-10-23,23>>^ "Tudo é permitido", mas nem tudo convém. "Tudo é permitido", mas nem tudo traz benefícios.

[[v46-10-24]]

^<<v46-10-24,24>>^ Não se preocupem com seu próprio bem, mas com o bem dos outros.

[[v46-10-25]]

^<<v46-10-25,25>>^ Portanto, vocês podem comer qualquer carne que é vendida no mercado sem questionar nada por motivo de consciência.

[[v46-10-26]]

^<<v46-10-26,26>>^ Pois "do Senhor é a terra e tudo que nela há".

[[v46-10-27]]

^<<v46-10-27,27>>^ Se um descrente os convidar para uma refeição, aceitem o convite se desejarem. Comam o que lhes oferecerem, sem questionar nada por motivo de consciência.

[[v46-10-28]]

^<<v46-10-28,28>>^ (Mas, se alguém lhes disser: "Esta carne foi oferecida a um ídolo", não a comam por respeito à consciência da pessoa que os avisou.

[[v46-10-29]]

^<<v46-10-29,29>>^ Talvez não seja uma questão de consciência para vocês, mas o é para a outra pessoa.) Afinal, por que minha liberdade deve ser limitada por aquilo que outros pensam?

[[v46-10-30]]

^<<v46-10-30,30>>^ Por que serei eu condenado se comer algo pelo qual dei graças a Deus?

[[v46-10-31]]

^<<v46-10-31,31>>^ Portanto, quer vocês comam, quer bebam, quer façam qualquer outra coisa, façam para a glória de Deus.

[[v46-10-32]]

^<<v46-10-32,32>>^ Não ofendam nem os judeus, nem os gentios, nem a igreja de Deus,

[[v46-10-33]]

^<<v46-10-33,33>>^ assim como também eu procuro agradar a todos em tudo que faço. Não faço apenas o que é melhor para mim; faço o que é melhor para os outros, a fim de que muitos sejam salvos.

'''

xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[&#60; Capítulo Anterior] | <<v46-10-0,Topo>> | xref:046-1-corintios/046-1-corintios-011.adoc#v46-11-0[Próximo Capítulo &#62;]