include::./index.adoc[]

[[v46-12-0]]
=== 1 Coríntios, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v46-12-1]]

^<<v46-12-1,1>>^ Agora, irmãos, quanto à sua pergunta sobre os dons espirituais, não quero que continuem confusos.

[[v46-12-2]]

^<<v46-12-2,2>>^ Vocês sabem que, quando ainda eram pagãos, foram conduzidos pelo caminho errado e levados a adorar ídolos mudos.

[[v46-12-3]]

^<<v46-12-3,3>>^ Por isso, quero que compreendam que ninguém que fala pelo Espírito de Deus amaldiçoa Jesus, e ninguém pode dizer que Jesus é Senhor a não ser pelo Espírito Santo.

[[v46-12-4]]

^<<v46-12-4,4>>^ Existem tipos diferentes de dons espirituais, mas o mesmo Espírito é a fonte de todos eles.

[[v46-12-5]]

^<<v46-12-5,5>>^ Existem tipos diferentes de serviço, mas o Senhor a quem servimos é o mesmo.

[[v46-12-6]]

^<<v46-12-6,6>>^ Deus trabalha de maneiras diferentes, mas é o mesmo Deus que opera em todos nós.

[[v46-12-7]]

^<<v46-12-7,7>>^ A cada um de nós é concedida a manifestação do Espírito para o benefício de todos.

[[v46-12-8]]

^<<v46-12-8,8>>^ A um o Espírito dá a capacidade de oferecer conselhos sábios, a outro o mesmo Espírito dá uma mensagem de conhecimento especial.

[[v46-12-9]]

^<<v46-12-9,9>>^ A um o mesmo Espírito dá grande fé, a outro o único Espírito concede o dom de cura.

[[v46-12-10]]

^<<v46-12-10,10>>^ A um ele dá o poder de realizar milagres, a outro, a capacidade de profetizar. A outro ele dá a capacidade de discernir se uma mensagem é do Espírito de Deus ou de outro espírito. A outro, ainda, dá a capacidade de falar em diferentes línguas, enquanto a um outro dá a capacidade de interpretar o que está sendo dito.

[[v46-12-11]]

^<<v46-12-11,11>>^ Tudo isso é distribuído pelo mesmo e único Espírito, que concede o que deseja a cada um.

[[v46-12-12]]

^<<v46-12-12,12>>^ O corpo humano tem muitas partes, mas elas formam um só corpo. O mesmo acontece com relação a Cristo.

[[v46-12-13]]

^<<v46-12-13,13>>^ Alguns de nós são judeus, alguns são gentios, alguns são escravos e alguns são livres, mas todos nós fomos batizados em um só corpo pelo único Espírito, e todos recebemos o privilégio de beber do mesmo Espírito.

[[v46-12-14]]

^<<v46-12-14,14>>^ De fato, o corpo não é feito de uma só parte, mas de muitas partes diferentes.

[[v46-12-15]]

^<<v46-12-15,15>>^ Se o pé diz: "Não sou parte do corpo porque não sou mão", acaso, por isso, deixa de ser parte do corpo?

[[v46-12-16]]

^<<v46-12-16,16>>^ E se a orelha diz: "Não sou parte do corpo porque não sou olho", será que, por isso, deixa de ser parte do corpo?

[[v46-12-17]]

^<<v46-12-17,17>>^ Se o corpo todo fosse olho, como vocês ouviriam? E, se o corpo todo fosse orelha, como sentiriam o cheiro de algo?

[[v46-12-18]]

^<<v46-12-18,18>>^ Mas nosso corpo tem muitas partes, e Deus colocou cada uma delas onde ele quis.

[[v46-12-19]]

^<<v46-12-19,19>>^ O corpo deixaria de ser corpo se tivesse apenas uma parte.

[[v46-12-20]]

^<<v46-12-20,20>>^ Assim, há muitas partes, mas um só corpo.

[[v46-12-21]]

^<<v46-12-21,21>>^ O olho não pode dizer à mão: "Não preciso de você". E a cabeça não pode dizer aos pés: "Não preciso de vocês".

[[v46-12-22]]

^<<v46-12-22,22>>^ Ao contrário, algumas partes do corpo que parecem mais fracas são as mais necessárias.

[[v46-12-23]]

^<<v46-12-23,23>>^ E as partes que consideramos menos honrosas são as que tratamos com mais atenção. Assim, protegemos cuidadosamente as partes que não devem ser vistas,

[[v46-12-24]]

^<<v46-12-24,24>>^ enquanto as mais honrosas não precisam dessa atenção especial. Deus estruturou o corpo de maneira a conceder mais honra e cuidado às partes que recebem menos atenção.

[[v46-12-25]]

^<<v46-12-25,25>>^ Isso faz que haja harmonia entre os membros, de modo que todos cuidem uns dos outros.

[[v46-12-26]]

^<<v46-12-26,26>>^ Se uma parte sofre, todas as outras sofrem com ela, e se uma parte é honrada, todas as outras com ela se alegram.

[[v46-12-27]]

^<<v46-12-27,27>>^ Juntos, todos vocês são o corpo de Cristo, e cada um é uma parte dele.

[[v46-12-28]]

^<<v46-12-28,28>>^ Deus estabeleceu para a igreja: em primeiro lugar, os apóstolos; em segundo, os profetas; em terceiro, os mestres; depois, os que fazem milagres, os que têm o dom de cura, os que ajudam outros, os que têm o dom de liderança, os que falam em diferentes línguas.

[[v46-12-29]]

^<<v46-12-29,29>>^ Somos todos apóstolos? Somos todos profetas? Somos todos mestres? Todos nós temos o poder de fazer milagres?

[[v46-12-30]]

^<<v46-12-30,30>>^ Todos temos o dom de cura? Todos temos a capacidade de falar em diferentes línguas? Todos temos a capacidade de interpretar o que é dito?

[[v46-12-31]]

^<<v46-12-31,31>>^ Portanto, desejem intensamente os dons mais úteis. Agora, porém, vou lhes mostrar um estilo de vida que supera os demais.

'''

xref:046-1-corintios/046-1-corintios-011.adoc#v46-11-0[&#60; Capítulo Anterior] | <<v46-12-0,Topo>> | xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[Próximo Capítulo &#62;]