include::./index.adoc[]

[[v46-6-0]]
=== 1 Coríntios, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v46-6-1]]

^<<v46-6-1,1>>^ Quando algum de vocês tem um desentendimento com outro irmão, como se atreve a recorrer a um tribunal e pedir que injustos decidam a questão em vez de levá-la ao povo santo?

[[v46-6-2]]

^<<v46-6-2,2>>^ Vocês não sabem que um dia nós, os santos, julgaremos o mundo? E, uma vez que vocês julgarão o mundo, acaso não são capazes de decidir entre vocês nem mesmo essas pequenas causas?

[[v46-6-3]]

^<<v46-6-3,3>>^ Não sabem que julgaremos os anjos? Que dizer, então, dos desentendimentos corriqueiros desta vida?

[[v46-6-4]]

^<<v46-6-4,4>>^ Se vocês têm conflitos legais, por que levá-los para fora da igreja, a juízes que não fazem parte dela?

[[v46-6-5]]

^<<v46-6-5,5>>^ Digo isso para envergonhá-los. Ninguém entre vocês tem sabedoria suficiente para resolver essas questões?

[[v46-6-6]]

^<<v46-6-6,6>>^ Em vez disso, um irmão processa outro irmão diante dos descrentes!

[[v46-6-7]]

^<<v46-6-7,7>>^ O simples fato de terem essas ações judiciais entre si já é uma derrota para vocês. Por que não aceitar a injustiça sofrida? Por que não arcar com o prejuízo?

[[v46-6-8]]

^<<v46-6-8,8>>^ Em vez disso, vocês mesmos cometem injustiças e causam prejuízos até contra os próprios irmãos.

[[v46-6-9]]

^<<v46-6-9,9>>^ Vocês não sabem que os injustos não herdarão o reino de Deus? Não se enganem: aqueles que se envolvem em imoralidade sexual, adoram ídolos, cometem adultério, se entregam a práticas homossexuais,

[[v46-6-10]]

^<<v46-6-10,10>>^ são ladrões, avarentos, bêbados, insultam as pessoas ou exploram os outros não herdarão o reino de Deus.

[[v46-6-11]]

^<<v46-6-11,11>>^ Alguns de vocês eram assim, mas foram purificados e santificados, declarados justos diante de Deus no nome do Senhor Jesus Cristo e pelo Espírito de nosso Deus.

[[v46-6-12]]

^<<v46-6-12,12>>^ "Tudo me é permitido", mas nem tudo convém. "Tudo me é permitido", mas não devo me tornar escravo de nada.

[[v46-6-13]]

^<<v46-6-13,13>>^ "Os alimentos foram feitos para o estômago, e o estômago para os alimentos." É verdade, mas um dia Deus acabará com os dois. Vocês, contudo, não podem dizer que nosso corpo foi feito para a imoralidade sexual. Ele foi feito para o Senhor, e o relacionamento que o Senhor tem conosco inclui nosso corpo.

[[v46-6-14]]

^<<v46-6-14,14>>^ Portanto, Deus nos ressuscitará dos mortos por seu poder, assim como ressuscitou o Senhor.

[[v46-6-15]]

^<<v46-6-15,15>>^ Vocês não sabem que seu corpo é, na realidade, membro de Cristo? Acaso um homem deve tomar seu corpo, que faz parte de Cristo, e uni-lo a uma prostituta? De maneira nenhuma!

[[v46-6-16]]

^<<v46-6-16,16>>^ E vocês não sabem que se um homem se une a uma prostituta ele se torna um corpo com ela? Pois as Escrituras dizem: "Os dois se tornam um só".

[[v46-6-17]]

^<<v46-6-17,17>>^ Mas a pessoa que se une ao Senhor tem com ele uma união de espírito.

[[v46-6-18]]

^<<v46-6-18,18>>^ Fujam da imoralidade sexual! Nenhum outro pecado afeta o corpo como esse, pois a imoralidade sexual é um pecado contra o próprio corpo.

[[v46-6-19]]

^<<v46-6-19,19>>^ Vocês não sabem que seu corpo é o templo do Espírito Santo, que habita em vocês e lhes foi dado por Deus? Vocês não pertencem a si mesmos,

[[v46-6-20]]

^<<v46-6-20,20>>^ pois foram comprados por alto preço. Portanto, honrem a Deus com seu corpo.

'''

xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[Próximo Capítulo &#62;]