include::./index.adoc[]

[[v46-8-0]]
=== 1 Coríntios, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v46-8-1]]

^<<v46-8-1,1>>^ Quanto à pergunta sobre a comida sacrificada a ídolos, sabemos que todos temos conhecimento a esse respeito. Contudo, o conhecimento traz orgulho, enquanto o amor fortalece.

[[v46-8-2]]

^<<v46-8-2,2>>^ Se alguém pensa que sabe tudo sobre algo, ainda não aprendeu como deveria.

[[v46-8-3]]

^<<v46-8-3,3>>^ Mas quem ama a Deus é conhecido por ele.

[[v46-8-4]]

^<<v46-8-4,4>>^ Então, o que dizer quanto ao alimento oferecido a ídolos? Bem, todos nós sabemos que, na verdade, o ídolo nada vale neste mundo, e que há somente um Deus.

[[v46-8-5]]

^<<v46-8-5,5>>^ Sim, é fato que existem os que são chamados de deuses, por assim dizer, nos céus e na terra, e há pessoas que adoram muitos deuses e muitos senhores.

[[v46-8-6]]

^<<v46-8-6,6>>^ Para nós, porém, Há somente um Deus, o Pai, por meio de quem todas as coisas foram criadas e para quem vivemos. E há somente um Senhor, Jesus Cristo, por meio de quem todas as coisas foram criadas e por meio de quem recebemos vida.

[[v46-8-7]]

^<<v46-8-7,7>>^ No entanto, nem todos sabem disso. Alguns estão acostumados a pensar que os ídolos são de verdade, de modo que, ao comer alimentos oferecidos a eles, imaginam que estão adorando deuses de verdade, e sua consciência fraca é contaminada.

[[v46-8-8]]

^<<v46-8-8,8>>^ Não obtemos a aprovação de Deus pelo que comemos. Não perdemos nada se não comemos, e se comemos, nada ganhamos.

[[v46-8-9]]

^<<v46-8-9,9>>^ Contudo, tenham cuidado para que sua liberdade não leve outros de consciência mais fraca a tropeçarem.

[[v46-8-10]]

^<<v46-8-10,10>>^ Pois, se alguém vir você, que diz ter um conhecimento superior, comer no templo de um ídolo, acaso não será induzido a contaminar a própria consciência ao ingerir alimentos oferecidos a ídolos?

[[v46-8-11]]

^<<v46-8-11,11>>^ Assim, por causa do seu conhecimento superior, um irmão fraco pelo qual Cristo morreu acaba se perdendo.

[[v46-8-12]]

^<<v46-8-12,12>>^ E quando vocês pecam contra outros irmãos, incentivando-os a fazer algo que eles consideram errado, pecam contra Cristo.

[[v46-8-13]]

^<<v46-8-13,13>>^ Portanto, se aquilo que eu como faz um irmão pecar, nunca mais comerei carne, pois não quero fazer meu irmão tropeçar.

'''

xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[&#60; Capítulo Anterior] | <<v46-8-0,Topo>> | xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[Próximo Capítulo &#62;]