include::./index.adoc[]

[[v46-14-0]]
=== 1 Coríntios, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v46-14-1]]

^<<v46-14-1,1>>^ Que o amor seja seu maior objetivo! Contudo, desejem também os dons espirituais, especialmente a capacidade de profetizar.

[[v46-14-2]]

^<<v46-14-2,2>>^ Pois quem fala em línguas fala apenas com Deus, pois ninguém mais o entende, e em espírito fala verdades ocultas.

[[v46-14-3]]

^<<v46-14-3,3>>^ Mas aquele que profetiza fortalece, anima e conforta os outros.

[[v46-14-4]]

^<<v46-14-4,4>>^ Quem fala em línguas fortalece a si mesmo, mas quem profetiza fortalece toda a igreja.

[[v46-14-5]]

^<<v46-14-5,5>>^ Gostaria que todos vocês falassem em línguas, mas gostaria ainda mais que todos profetizassem. Pois a profecia é superior a falar em línguas, a menos que alguém interprete o que vocês dizem para que toda a igreja seja fortalecida.

[[v46-14-6]]

^<<v46-14-6,6>>^ Irmãos, se eu for visitá-los e falar em línguas, em que isso os ajudará? Mas, se eu lhes trouxer uma revelação, um conhecimento especial, uma profecia ou um ensinamento, isso lhes será proveitoso.

[[v46-14-7]]

^<<v46-14-7,7>>^ Até mesmo instrumentos inanimados como a flauta ou a harpa precisam soar as notas com clareza; do contrário, ninguém reconhecerá a melodia.

[[v46-14-8]]

^<<v46-14-8,8>>^ E, se a trombeta não emitir um toque nítido, como os soldados saberão que estão sendo convocados para a batalha?

[[v46-14-9]]

^<<v46-14-9,9>>^ O mesmo acontece com vocês. Se usarem palavras incompreensíveis, como alguém saberá o que estão dizendo? Será o mesmo que falar ao vento.

[[v46-14-10]]

^<<v46-14-10,10>>^ Há muitos idiomas no mundo, e todos têm sentido.

[[v46-14-11]]

^<<v46-14-11,11>>^ Mas, se eu não entendo um idioma, sou estrangeiro para quem o fala, e ele é estrangeiro para mim.

[[v46-14-12]]

^<<v46-14-12,12>>^ O mesmo se aplica a vocês. Uma vez que estão ansiosos para ter os dons espirituais, busquem os dons que fortalecerão a igreja toda.

[[v46-14-13]]

^<<v46-14-13,13>>^ Portanto, quem fala em línguas deve orar pedindo também a capacidade de interpretar o que é dito.

[[v46-14-14]]

^<<v46-14-14,14>>^ Pois, se oro em línguas, meu espírito ora, mas eu não entendo o que estou dizendo.

[[v46-14-15]]

^<<v46-14-15,15>>^ Então, o que devo fazer? Orarei no espírito e também orarei em palavras que entendo. Cantarei no espírito e também cantarei em palavras que entendo.

[[v46-14-16]]

^<<v46-14-16,16>>^ Pois, se louvarem apenas no espírito, como poderão louvar com vocês aqueles que não os entendem? Como poderão agradecer com vocês se não entendem o que estão dizendo?

[[v46-14-17]]

^<<v46-14-17,17>>^ Vocês darão graças muito bem, mas não fortalecerão aqueles que os ouvem.

[[v46-14-18]]

^<<v46-14-18,18>>^ Dou graças a Deus porque falo em línguas mais que qualquer um de vocês.

[[v46-14-19]]

^<<v46-14-19,19>>^ Contudo, numa reunião da igreja, prefiro dizer cinco palavras compreensíveis que ajudem os outros a falar dez mil palavras em outra língua.

[[v46-14-20]]

^<<v46-14-20,20>>^ Irmãos, não sejam infantis no entendimento dessas coisas. Sejam inocentes como bebês com relação ao mal, mas sejam maduros no entendimento.

[[v46-14-21]]

^<<v46-14-21,21>>^ Pois as Escrituras dizem: "Falarei a este povo em línguas estranhas e por meio de lábios estrangeiros. Mesmo assim, este povo não me ouvirá, diz o Senhor".

[[v46-14-22]]

^<<v46-14-22,22>>^ Portanto, falar em línguas é um sinal não para os que creem, mas para os descrentes. A profecia, contudo, é para os que creem, e não para os descrentes.

[[v46-14-23]]

^<<v46-14-23,23>>^ Ainda assim, se descrentes ou pessoas que não entendem essas coisas entrarem na reunião de sua igreja e ouvirem todos falarem em línguas, pensarão que vocês são loucos.

[[v46-14-24]]

^<<v46-14-24,24>>^ Mas, se todos vocês estiverem profetizando e descrentes ou pessoas que não entendem essas coisas entrarem na reunião, serão convencidos do pecado e julgados por aquilo que vocês disserem.

[[v46-14-25]]

^<<v46-14-25,25>>^ Ao ouvirem, os pensamentos secretos deles serão revelados, e eles cairão de joelhos e adorarão a Deus, declarando: "De fato, Deus está aqui no meio de vocês".

[[v46-14-26]]

^<<v46-14-26,26>>^ Pois bem, irmãos, o que fazer, então? Quando vocês se reunirem, um cantará, o outro ensinará, o outro revelará, um falará em línguas e outro interpretará o que for dito. Tudo que for feito, porém, deverá fortalecer a todos.

[[v46-14-27]]

^<<v46-14-27,27>>^ Não mais que dois ou três devem falar em línguas. Devem se pronunciar um de cada vez, e alguém deve interpretar o que disserem.

[[v46-14-28]]

^<<v46-14-28,28>>^ Mas, se não houver alguém que possa interpretar, devem permanecer calados na reunião da igreja, falando com Deus em particular.

[[v46-14-29]]

^<<v46-14-29,29>>^ Que dois ou três profetizem e os outros avaliem o que for dito.

[[v46-14-30]]

^<<v46-14-30,30>>^ Se alguém estiver profetizando e outra pessoa receber uma revelação, quem está falando deve se calar.

[[v46-14-31]]

^<<v46-14-31,31>>^ Desse modo, todos que profetizam terão sua vez de falar, um depois do outro, para que todos sejam instruídos e encorajados.

[[v46-14-32]]

^<<v46-14-32,32>>^ Aqueles que profetizam têm controle de seu espírito e podem falar um por vez.

[[v46-14-33]]

^<<v46-14-33,33>>^ Pois Deus não é Deus de desordem, mas de paz, como em todas as reuniões do povo santo.

[[v46-14-34]]

^<<v46-14-34,34>>^ As mulheres devem permanecer em silêncio durante as reuniões da igreja. Não é apropriado que falem. Devem ser submissas, como diz a lei.

[[v46-14-35]]

^<<v46-14-35,35>>^ Se tiverem alguma pergunta, devem fazê-la ao marido, em casa, pois não é apropriado que as mulheres falem nas reuniões da igreja.

[[v46-14-36]]

^<<v46-14-36,36>>^ Ou vocês pensam que a palavra de Deus se originou entre vocês? Acaso são os únicos aos quais ela foi entregue?

[[v46-14-37]]

^<<v46-14-37,37>>^ Se alguém afirma ser profeta ou se considera espiritual, será o primeiro a reconhecer que o que lhes digo é uma ordem do Senhor.

[[v46-14-38]]

^<<v46-14-38,38>>^ Se alguém ignorar esse fato, ele mesmo será ignorado.

[[v46-14-39]]

^<<v46-14-39,39>>^ Portanto, meus irmãos, anseiem profetizar e não proíbam o falar em línguas,

[[v46-14-40]]

^<<v46-14-40,40>>^ mas cuidem para que tudo seja feito com decência e ordem.

'''

xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[Próximo Capítulo &#62;]