include::./index.adoc[]

[[v9-21-0]]
=== 1 Samuel, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v9-21-1]]

^<<v9-21-1,1>>^ Davi foi à cidade de Nobe para encontrar-se com o sacerdote Aimeleque. Ao vê-lo, Aimeleque tremeu. "Por que você está sozinho?", perguntou. "Por que ninguém o acompanhou?"

[[v9-21-2]]

^<<v9-21-2,2>>^ "O rei me enviou para tratar de um assunto secreto", respondeu Davi. "Pediu que eu não contasse a ninguém por que estou aqui. Eu disse a meus homens onde podem me encontrar depois.

[[v9-21-3]]

^<<v9-21-3,3>>^ Agora, o que tem para comer? Dê-me cinco pães, ou qualquer outra coisa que tiver."

[[v9-21-4]]

^<<v9-21-4,4>>^ "Não temos pão comum", respondeu o sacerdote. "Mas há o pão sagrado, que vocês podem comer, desde que seus homens não tenham se deitado com mulheres recentemente."

[[v9-21-5]]

^<<v9-21-5,5>>^ Davi respondeu: "Nunca permito que meus homens toquem em mulheres quando saímos numa campanha. E, se eles permanecem puros em viagens comuns, quanto mais nesta missão!".

[[v9-21-6]]

^<<v9-21-6,6>>^ Uma vez que não havia outro alimento disponível, o sacerdote lhe deu os pães sagrados, chamados de pães da presença, que eram colocados diante do SENHOR no santuário. Naquele dia, tinham sido substituídos por pães frescos.

[[v9-21-7]]

^<<v9-21-7,7>>^ Doegue, o edomita, chefe dos pastores de Saul, estava lá naquela ocasião, pois estava cumprindo um ritual diante do SENHOR.

[[v9-21-8]]

^<<v9-21-8,8>>^ Davi perguntou a Aimeleque: "Você tem uma lança ou espada? O assunto do rei era tão urgente que não tive tempo nem de pegar uma espada ou outra arma!".

[[v9-21-9]]

^<<v9-21-9,9>>^ O sacerdote respondeu: "Tenho apenas a espada de Golias, o gigante filisteu que você matou no vale de Elá. Está enrolada num pano atrás do colete sacerdotal. Pode levá-la, pois não há nenhuma outra arma aqui". "Dê-me essa espada", respondeu Davi. "Não há outra melhor que ela."

[[v9-21-10]]

^<<v9-21-10,10>>^ Então Davi fugiu de Saul e foi até Aquis, rei de Gate.

[[v9-21-11]]

^<<v9-21-11,11>>^ Os oficiais de Aquis, porém, disseram: "Não é este Davi, o rei da terra de Israel? Não é a ele que o povo honra com danças e cânticos, dizendo: ‘Saul matou milhares, e Davi, dezenas de milhares’?".

[[v9-21-12]]

^<<v9-21-12,12>>^ Davi ouviu esses comentários e teve muito medo do que Aquis, rei de Gate, poderia fazer com ele.

[[v9-21-13]]

^<<v9-21-13,13>>^ Por isso, agiu de modo estranho, fingindo estar louco, arranhando as portas e deixando saliva escorrer pela barba.

[[v9-21-14]]

^<<v9-21-14,14>>^ Por fim, Aquis disse a seus homens: "Precisavam me trazer um doido?

[[v9-21-15]]

^<<v9-21-15,15>>^ Temos doidos suficientes aqui! Por que trouxeram alguém assim ao meu palácio?".

'''

xref:009-1-samuel/009-1-samuel-020.adoc#v9-20-0[&#60; Capítulo Anterior] | <<v9-21-0,Topo>> | xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[Próximo Capítulo &#62;]