include::./index.adoc[]

[[v9-13-0]]
=== 1 Samuel, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v9-13-1]]

^<<v9-13-1,1>>^ Saul tinha 30 anos quando se tornou rei, e reinou por 42 anos.

[[v9-13-2]]

^<<v9-13-2,2>>^ Saul escolheu três mil soldados do exército de Israel e mandou o restante dos homens para casa. Levou consigo dois mil desses homens a Micmás e à região montanhosa de Betel. Os outros mil foram com Jônatas, filho de Saul, para Gibeá, na terra de Benjamim.

[[v9-13-3]]

^<<v9-13-3,3>>^ Logo depois disso, Jônatas atacou e derrotou o destacamento dos filisteus em Geba. A notícia se espalhou entre os filisteus. Então Saul tocou a trombeta por toda a terra, anunciando: "Ouçam bem, hebreus!".

[[v9-13-4]]

^<<v9-13-4,4>>^ E todo o Israel ouviu que Saul tinha destruído o destacamento dos filisteus e que agora eles odiavam os israelitas mais que nunca. Então os soldados israelitas foram convocados para se unir a Saul em Gilgal.

[[v9-13-5]]

^<<v9-13-5,5>>^ Os filisteus reuniram um exército de três mil carros de guerra, seis mil cavaleiros e tantos guerreiros como os grãos de areia na praia. Acamparam em Micmás, a leste de Bete-Áven.

[[v9-13-6]]

^<<v9-13-6,6>>^ Os homens de Israel se viram em apuros e, como estavam sendo fortemente pressionados pelo inimigo, tentaram se esconder em cavernas, em matagais, entre rochas, em buracos e em cisternas.

[[v9-13-7]]

^<<v9-13-7,7>>^ Alguns dos hebreus atravessaram o rio Jordão e fugiram para a terra de Gade e de Gileade. Enquanto isso, Saul permaneceu em Gilgal, e os homens que estavam com ele tremiam de medo.

[[v9-13-8]]

^<<v9-13-8,8>>^ Saul esperou ali por Samuel durante sete dias, conforme Samuel o havia instruído, mas ele não chegou. Vendo que os soldados debandavam rapidamente,

[[v9-13-9]]

^<<v9-13-9,9>>^ Saul ordenou: "Tragam-me o holocausto e as ofertas de paz!". E ele próprio ofereceu o holocausto.

[[v9-13-10]]

^<<v9-13-10,10>>^ No exato instante em que Saul terminava de oferecer o holocausto, Samuel chegou. Saul foi ao seu encontro para cumprimentá-lo,

[[v9-13-11]]

^<<v9-13-11,11>>^ mas Samuel disse: "O que você fez?". Saul respondeu: "Vi que meus homens estavam debandando, e que o senhor não chegou no prazo que havia prometido. Além disso, os filisteus estavam em Micmás, prontos para a batalha.

[[v9-13-12]]

^<<v9-13-12,12>>^ Assim, pensei: ‘Os filisteus estão prontos para lutar contra nós em Gilgal, e eu não pedi ajuda ao SENHOR’. Por isso me senti na obrigação de oferecer o holocausto".

[[v9-13-13]]

^<<v9-13-13,13>>^ "Você agiu como um tolo!", exclamou Samuel. "Não guardou o mandamento que o SENHOR, seu Deus, lhe deu. Se tivesse obedecido, o SENHOR teria estabelecido para sempre seu reinado sobre Israel.

[[v9-13-14]]

^<<v9-13-14,14>>^ Agora, porém, seu reinado não permanecerá, pois o SENHOR escolheu um homem segundo o coração dele. O SENHOR já designou esse homem para ser líder de seu povo, pois você não obedeceu ao mandamento do SENHOR."

[[v9-13-15]]

^<<v9-13-15,15>>^ Então Samuel partiu de Gilgal e subiu para Gibeá, na terra de Benjamim. Quando Saul contou os soldados que ainda estavam com ele, viu que havia cerca de seiscentos homens.

[[v9-13-16]]

^<<v9-13-16,16>>^ Saul, Jônatas e os soldados que estavam com eles ficaram em Geba, na terra de Benjamim. Os filisteus acamparam em Micmás.

[[v9-13-17]]

^<<v9-13-17,17>>^ Três grupos de ataque deixaram o acampamento filisteu: um foi para o norte, em direção a Ofra, na região de Sual,

[[v9-13-18]]

^<<v9-13-18,18>>^ outro foi para oeste, a Bete-Horom, e o terceiro rumou para a fronteira acima do vale de Zeboim, na direção do deserto.

[[v9-13-19]]

^<<v9-13-19,19>>^ Naqueles dias, não havia ferreiros na terra de Israel, pois os filisteus não permitiam que os hebreus fizessem espadas ou lanças.

[[v9-13-20]]

^<<v9-13-20,20>>^ Assim, sempre que o povo de Israel precisava afiar seus arados, enxadas, machados e foices, tinha de levá-los a um ferreiro filisteu.

[[v9-13-21]]

^<<v9-13-21,21>>^ O custo para afiar um arado ou uma enxada era de oito gramas de prata, e, para afiar um machado, uma foice ou a ponta de ferro de uma vara de tocar bois, quatro gramas.

[[v9-13-22]]

^<<v9-13-22,22>>^ Por isso, no dia da batalha, ninguém em Israel tinha espada ou lança, exceto Saul e Jônatas.

[[v9-13-23]]

^<<v9-13-23,23>>^ Nesse meio-tempo, os filisteus mandaram um destacamento para o desfiladeiro de Micmás.

'''

xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[&#60; Capítulo Anterior] | <<v9-13-0,Topo>> | xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[Próximo Capítulo &#62;]