include::./index.adoc[]

[[v9-23-0]]
=== 1 Samuel, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v9-23-1]]

^<<v9-23-1,1>>^ Um dia, Davi recebeu a notícia de que os filisteus estavam atacando a cidade de Queila e roubando cereais das eiras.

[[v9-23-2]]

^<<v9-23-2,2>>^ Davi perguntou ao SENHOR: "Devo ir e atacá-los?". E o SENHOR lhe respondeu: "Sim, vá, lute contra os filisteus e liberte Queila".

[[v9-23-3]]

^<<v9-23-3,3>>^ Contudo, os homens de Davi disseram: "Estamos com medo mesmo aqui, em Judá. Imagine como seria em Queila para lutar contra os exércitos filisteus!".

[[v9-23-4]]

^<<v9-23-4,4>>^ Davi consultou o SENHOR novamente e, mais uma vez, o SENHOR respondeu: "Vá a Queila, pois eu entregarei os filisteus em suas mãos".

[[v9-23-5]]

^<<v9-23-5,5>>^ Então Davi e seus homens foram a Queila. Massacraram os filisteus, tomaram todos os seus rebanhos e libertaram o povo daquela cidade.

[[v9-23-6]]

^<<v9-23-6,6>>^ Quando Abiatar, filho de Aimeleque, fugiu para juntar-se a Davi em Queila, trouxe consigo o colete sacerdotal.

[[v9-23-7]]

^<<v9-23-7,7>>^ Saul soube que Davi estava em Queila. "Agora ele não tem como escapar de nós!", exclamou. "Deus o entregou em minhas mãos, pois ele se enfiou numa cidade com portões e trancas!"

[[v9-23-8]]

^<<v9-23-8,8>>^ Saul reuniu todo o seu exército para marchar até Queila e cercar Davi e seus homens.

[[v9-23-9]]

^<<v9-23-9,9>>^ Contudo, Davi soube do plano de Saul e pediu a Abiatar, o sacerdote: "Traga o colete sacerdotal!".

[[v9-23-10]]

^<<v9-23-10,10>>^ Então Davi orou: "Ó SENHOR, Deus de Israel, ouvi que Saul planeja vir e destruir Queila porque estou aqui.

[[v9-23-11]]

^<<v9-23-11,11>>^ Será que os líderes de Queila vão me trair e me entregar a ele? E Saul virá, de fato, conforme ouvi? Ó SENHOR, Deus de Israel, por favor, responde-me!". E o SENHOR respondeu: "Ele virá".

[[v9-23-12]]

^<<v9-23-12,12>>^ Mais uma vez, Davi perguntou: "Os líderes de Queila entregarão a mim e a meus homens a Saul?". E o SENHOR respondeu: "Sim, entregarão".

[[v9-23-13]]

^<<v9-23-13,13>>^ Então Davi e seus homens, que agora eram cerca de seiscentos, partiram de Queila e começaram a andar sem rumo por aquela região. Quando Saul foi informado de que Davi tinha escapado, desistiu de ir a Queila.

[[v9-23-14]]

^<<v9-23-14,14>>^ Davi permaneceu nas fortalezas do deserto e na região montanhosa de Zife. Saul o perseguia continuamente, mas Deus não permitiu que o encontrasse.

[[v9-23-15]]

^<<v9-23-15,15>>^ Então, perto de Horesa, Davi recebeu a notícia de que Saul estava a caminho do deserto de Zife para procurá-lo e matá-lo.

[[v9-23-16]]

^<<v9-23-16,16>>^ Jônatas, o filho de Saul, foi encontrar Davi e o animou a permanecer firme em Deus.

[[v9-23-17]]

^<<v9-23-17,17>>^ "Não tenha medo!", disse Jônatas. "Meu pai jamais o encontrará! Você será o rei de Israel, e eu serei o segundo no comando, como meu pai, Saul, sabe muito bem."

[[v9-23-18]]

^<<v9-23-18,18>>^ Então os dois renovaram seu compromisso solene diante do SENHOR. Depois Jônatas voltou para casa, enquanto Davi ficou em Horesa.

[[v9-23-19]]

^<<v9-23-19,19>>^ Os habitantes de Zife, porém, foram até Saul em Gibeá e disseram: "Sabemos onde Davi está escondido. Está nas fortalezas de Horesa, na colina de Haquilá, no sul de Jesimom.

[[v9-23-20]]

^<<v9-23-20,20>>^ Desça quando estiver preparado, ó rei, e nós apanharemos Davi e o entregaremos em suas mãos!".

[[v9-23-21]]

^<<v9-23-21,21>>^ "Que o SENHOR os abençoe!", disse Saul. "Finalmente alguém se preocupou comigo.

[[v9-23-22]]

^<<v9-23-22,22>>^ Vão e verifiquem onde ele está e quem o viu ali, pois dizem que ele é muito astuto.

[[v9-23-23]]

^<<v9-23-23,23>>^ Descubram o esconderijo dele e voltem quando tiverem certeza. Então irei com vocês. E, se ele estiver naquela região, eu o encontrarei, mesmo que precise procurar por todo canto de Judá!"

[[v9-23-24]]

^<<v9-23-24,24>>^ Os homens de Zife voltaram para casa à frente de Saul. Enquanto isso, Davi e seus homens foram para o deserto de Maom, no vale de Arabá, ao sul de Jesimom.

[[v9-23-25]]

^<<v9-23-25,25>>^ Quando Davi soube que Saul e seus homens o procuravam, foi ainda mais para o interior do deserto, até a grande rocha, e permaneceu no deserto de Maom. Saul, porém, continuou a persegui-lo naquela região.

[[v9-23-26]]

^<<v9-23-26,26>>^ Saul e Davi agora estavam em lados opostos de uma montanha, e Davi fugia apressadamente de Saul. No mesmo instante que Saul e seus homens cercaram Davi e seus homens para prendê-los,

[[v9-23-27]]

^<<v9-23-27,27>>^ chegou uma mensagem urgente para o rei, informando que os filisteus estavam atacando Israel outra vez.

[[v9-23-28]]

^<<v9-23-28,28>>^ Então Saul deixou de perseguir Davi e voltou para lutar contra os filisteus. A partir dessa ocasião, o lugar onde Davi estava acampado passou a ser chamado de Selá-Hamalecote.

[[v9-23-29]]

^<<v9-23-29,29>>^ Depois, Davi saiu dali e foi viver nas fortalezas da região de En-Gedi.

'''

xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[&#60; Capítulo Anterior] | <<v9-23-0,Topo>> | xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[Próximo Capítulo &#62;]