include::./index.adoc[]

[[v9-30-0]]
=== 1 Samuel, 30
// nvt ?, NVT - Nova Versão Transformadora

[[v9-30-1]]

^<<v9-30-1,1>>^ Três dias depois, quando Davi e seus homens chegaram à cidade de Ziclague, viram que os amalequitas haviam invadido o Neguebe e atacado Ziclague; tinham destruído e queimado a cidade.

[[v9-30-2]]

^<<v9-30-2,2>>^ Não mataram ninguém, mas tomaram como prisioneiros as mulheres, as crianças e os demais e foram embora.

[[v9-30-3]]

^<<v9-30-3,3>>^ Quando Davi e seus homens viram a cidade queimada e se deram conta do que havia acontecido com suas mulheres, seus filhos e suas filhas,

[[v9-30-4]]

^<<v9-30-4,4>>^ lamentaram e choraram em alta voz até não aguentar mais.

[[v9-30-5]]

^<<v9-30-5,5>>^ As duas esposas de Davi, Ainoã, de Jezreel, e Abigail, viúva de Nabal, do Carmelo, estavam entre os que foram capturados.

[[v9-30-6]]

^<<v9-30-6,6>>^ Davi ficou muito aflito, pois os homens estavam amargurados por terem perdido seus filhos e suas filhas e começaram a falar em apedrejá-lo. Mas Davi encontrou forças no SENHOR, seu Deus.

[[v9-30-7]]

^<<v9-30-7,7>>^ Então disse ao sacerdote Abiatar: "Traga o colete sacerdotal!", e Abiatar, filho de Aimeleque, o trouxe.

[[v9-30-8]]

^<<v9-30-8,8>>^ Davi perguntou ao SENHOR: "Devo perseguir esse bando de saqueadores? Conseguirei apanhá-los?". E o SENHOR lhe respondeu: "Sim, vá atrás deles. Certamente conseguirá recuperar tudo que foi tomado de vocês".

[[v9-30-9]]

^<<v9-30-9,9>>^ Davi e os seiscentos homens partiram e chegaram ao ribeiro de Besor, onde ficaram alguns deles.

[[v9-30-10]]

^<<v9-30-10,10>>^ Duzentos dos homens estavam exaustos demais para atravessar o ribeiro, e Davi continuou a perseguição com quatrocentos homens.

[[v9-30-11]]

^<<v9-30-11,11>>^ No caminho, encontraram um rapaz egípcio num campo e o levaram até Davi. Deram-lhe um pouco de pão para comer e água para beber.

[[v9-30-12]]

^<<v9-30-12,12>>^ Também lhe deram um pedaço de bolo de figo e dois bolos de passas, pois fazia três dias e três noites que não comia nem bebia nada. Em pouco tempo, recuperou as forças.

[[v9-30-13]]

^<<v9-30-13,13>>^ Davi lhe perguntou: "A quem você pertence e de onde veio?". "Sou egípcio, escravo de um amalequita", respondeu ele. "Meu senhor me abandonou três dias atrás porque fiquei doente.

[[v9-30-14]]

^<<v9-30-14,14>>^ Estávamos voltando de um ataque aos queretitas, no Neguebe, ao território de Judá e à terra de Calebe, e tínhamos queimado Ziclague."

[[v9-30-15]]

^<<v9-30-15,15>>^ "Você pode me levar até esse bando de saqueadores?", perguntou Davi. O rapaz respondeu: "Se o senhor jurar por Deus que não me matará nem me entregará ao meu senhor, eu o levarei até eles".

[[v9-30-16]]

^<<v9-30-16,16>>^ O rapaz o levou até os amalequitas. Estavam espalhados pelos campos, comendo, bebendo e festejando por causa da grande quantidade de bens que haviam tomado da terra dos filisteus e da terra de Judá.

[[v9-30-17]]

^<<v9-30-17,17>>^ Davi e seus homens massacraram os amalequitas, atacando-os durante toda a noite e todo o dia seguinte, até o entardecer. Nenhum deles escapou, exceto quatrocentos rapazes que fugiram montados em camelos.

[[v9-30-18]]

^<<v9-30-18,18>>^ Davi recuperou tudo que os amalequitas haviam tomado e resgatou suas duas esposas.

[[v9-30-19]]

^<<v9-30-19,19>>^ Não faltava coisa alguma: nem pequena nem grande, nem filho nem filha, nem qualquer outra coisa que havia sido tomada. Davi trouxe tudo de volta.

[[v9-30-20]]

^<<v9-30-20,20>>^ Também recuperou todos os rebanhos, e seus companheiros os levaram à frente dos outros animais. "Este despojo pertence a Davi!", disseram.

[[v9-30-21]]

^<<v9-30-21,21>>^ Então Davi voltou ao ribeiro de Besor, onde estavam os duzentos homens que tinham sido deixados para trás porque estavam exaustos demais para acompanhá-los. Saíram ao encontro de Davi e seus companheiros, e ele os cumprimentou com alegria.

[[v9-30-22]]

^<<v9-30-22,22>>^ Contudo, entre os que tinham acompanhado Davi havia alguns homens perversos que disseram: "Como eles não foram conosco, não devem receber nada dos despojos que recuperamos. Devolvam as esposas e os filhos deles e mandem todos embora".

[[v9-30-23]]

^<<v9-30-23,23>>^ Davi, porém, disse: "Não, meus irmãos! Não sejam egoístas com aquilo que o SENHOR nos deu. Ele nos guardou e nos ajudou a derrotar o bando de saqueadores que nos atacou.

[[v9-30-24]]

^<<v9-30-24,24>>^ Quem lhes dará ouvidos quando falam desse modo? Dividiremos igualmente entre os que foram à batalha e os que guardaram a bagagem".

[[v9-30-25]]

^<<v9-30-25,25>>^ A partir daquele dia, Davi fez disso decreto e estatuto em Israel, e assim é até hoje.

[[v9-30-26]]

^<<v9-30-26,26>>^ Quando Davi chegou a Ziclague, enviou parte dos despojos aos líderes de Judá, que eram seus amigos. Disse: "Eis um presente para vocês, tirado dos inimigos do SENHOR!".

[[v9-30-27]]

^<<v9-30-27,27>>^ Os presentes foram enviados ao povo das seguintes cidades: Betel, Ramote do Neguebe, Jatir,

[[v9-30-28]]

^<<v9-30-28,28>>^ Aroer, Sifmote, Estemoa,

[[v9-30-29]]

^<<v9-30-29,29>>^ Racal, as cidades dos jerameelitas e as cidades dos queneus,

[[v9-30-30]]

^<<v9-30-30,30>>^ Hormá, Borasã, Atace,

[[v9-30-31]]

^<<v9-30-31,31>>^ Hebrom e todos os outros lugares por onde Davi e seus homens haviam passado.

'''

xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[&#60; Capítulo Anterior] | <<v9-30-0,Topo>> | xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[Próximo Capítulo &#62;]