include::./index.adoc[]

[[v9-3-0]]
=== 1 Samuel, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v9-3-1]]

^<<v9-3-1,1>>^ Enquanto isso, o menino Samuel servia ao SENHOR ajudando Eli. Naqueles dias, as mensagens do SENHOR eram muito raras, e visões não eram comuns.

[[v9-3-2]]

^<<v9-3-2,2>>^ Certa noite, Eli, que estava quase cego, tinha ido se deitar.

[[v9-3-3]]

^<<v9-3-3,3>>^ A lâmpada de Deus ainda não havia se apagado, e Samuel dormia na casa do SENHOR, onde estava a arca de Deus.

[[v9-3-4]]

^<<v9-3-4,4>>^ De repente, o SENHOR chamou: "Samuel!". O menino respondeu: "Estou aqui!".

[[v9-3-5]]

^<<v9-3-5,5>>^ Ele se levantou e correu até onde estava Eli. "Estou aqui! O senhor me chamou?" "Não o chamei", respondeu Eli. "Volte para a cama." E Samuel voltou a se deitar.

[[v9-3-6]]

^<<v9-3-6,6>>^ Então o SENHOR o chamou novamente: "Samuel!". Mais uma vez, Samuel se levantou e foi até Eli. "Estou aqui! O senhor me chamou?" Mas Eli respondeu: "Meu filho, não o chamei. Volte para a cama".

[[v9-3-7]]

^<<v9-3-7,7>>^ Samuel ainda não conhecia o SENHOR, porque nunca havia recebido uma mensagem dele.

[[v9-3-8]]

^<<v9-3-8,8>>^ O SENHOR o chamou pela terceira vez, e novamente Samuel se levantou e foi até Eli. "Estou aqui! O senhor me chamou?" Então Eli entendeu que era o SENHOR que chamava o menino.

[[v9-3-9]]

^<<v9-3-9,9>>^ Por isso, disse a Samuel: "Vá e deite-se novamente. Se alguém o chamar, diga: ‘Fala, SENHOR, pois teu servo está ouvindo’". E Samuel voltou para a cama.

[[v9-3-10]]

^<<v9-3-10,10>>^ Então o SENHOR veio e o chamou, como antes: "Samuel! Samuel!". Samuel respondeu: "Fala, pois teu servo está ouvindo".

[[v9-3-11]]

^<<v9-3-11,11>>^ Então o SENHOR disse a Samuel: "Estou prestes a realizar algo em Israel que fará tinir os ouvidos daqueles que ouvirem a respeito.

[[v9-3-12]]

^<<v9-3-12,12>>^ Cumprirei do começo ao fim todas as ameaças que fiz contra Eli e sua família.

[[v9-3-13]]

^<<v9-3-13,13>>^ Eu o adverti de que castigaria sua família para sempre, pois seus filhos blasfemaram contra Deus, e ele não os repreendeu por seus pecados.

[[v9-3-14]]

^<<v9-3-14,14>>^ Por isso, jurei que os pecados de Eli e de seus filhos jamais serão perdoados por meio de sacrifícios nem de ofertas".

[[v9-3-15]]

^<<v9-3-15,15>>^ Samuel ficou deitado até de manhã, e então se levantou e abriu as portas da casa do SENHOR. Estava com medo de contar para Eli a visão que tivera.

[[v9-3-16]]

^<<v9-3-16,16>>^ Mas Eli o chamou: "Samuel, meu filho". "Estou aqui", respondeu Samuel.

[[v9-3-17]]

^<<v9-3-17,17>>^ "O que o SENHOR lhe disse?", perguntou Eli. "Conte-me tudo. E que o SENHOR o castigue severamente se você esconder de mim alguma coisa do que ele disse!"

[[v9-3-18]]

^<<v9-3-18,18>>^ Então Samuel contou tudo a Eli e não escondeu nada. Eli respondeu: "É a vontade do SENHOR. Que ele faça o que lhe parecer melhor".

[[v9-3-19]]

^<<v9-3-19,19>>^ À medida que Samuel crescia, o SENHOR estava com ele, e todas as suas palavras se cumpriam.

[[v9-3-20]]

^<<v9-3-20,20>>^ E todo o Israel, desde Dã, ao norte, até Berseba, ao sul, sabia que Samuel havia sido confirmado como profeta do SENHOR.

[[v9-3-21]]

^<<v9-3-21,21>>^ O SENHOR continuou a aparecer em Siló e a transmitir mensagens a Samuel ali.

'''

xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[&#60; Capítulo Anterior] | <<v9-3-0,Topo>> | xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[Próximo Capítulo &#62;]