include::./index.adoc[]

[[v9-18-0]]
=== 1 Samuel, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v9-18-1]]

^<<v9-18-1,1>>^ Depois que Davi terminou de falar com Saul, formou-se de imediato um forte laço de amizade entre ele e Jônatas, filho do rei, por causa do amor que Jônatas tinha por Davi.

[[v9-18-2]]

^<<v9-18-2,2>>^ A partir daquele dia, Saul manteve Davi consigo e não o deixou voltar para a casa de seu pai.

[[v9-18-3]]

^<<v9-18-3,3>>^ Jônatas assumiu um compromisso solene com Davi, pois o amava como a si mesmo.

[[v9-18-4]]

^<<v9-18-4,4>>^ Para selar essa aliança, Jônatas tirou seu manto e o entregou a Davi, junto com sua armadura, sua espada, seu arco e seu cinturão.

[[v9-18-5]]

^<<v9-18-5,5>>^ Davi cumpria com êxito todas as missões de que Saul o encarregava. Então Saul lhe deu uma posição de comando no exército, o que agradou tanto ao povo como aos oficiais de Saul.

[[v9-18-6]]

^<<v9-18-6,6>>^ Quando o exército israelita regressou vitorioso, depois que Davi matou o gigante filisteu, mulheres de todas as cidades saíram ao encontro do rei Saul. Cantavam e dançavam de alegria, com tamborins e címbalos.

[[v9-18-7]]

^<<v9-18-7,7>>^ Esta era a canção: "Saul matou milhares, e Davi, dezenas de milhares!".

[[v9-18-8]]

^<<v9-18-8,8>>^ Saul ficou indignado com essas palavras. "O que é isso?", disse ele. "Atribuem a Davi dezenas de milhares, e a mim, apenas milhares? Só falta o declararem rei!"

[[v9-18-9]]

^<<v9-18-9,9>>^ Daquele momento em diante, Saul começou a olhar para Davi com suspeita.

[[v9-18-10]]

^<<v9-18-10,10>>^ No dia seguinte, um espírito maligno enviado por Deus se apoderou de Saul, e ele começou a delirar em sua casa, como se fosse louco. Davi tocava a harpa, como fazia todos os dias. Mas Saul tinha uma lança na mão

[[v9-18-11]]

^<<v9-18-11,11>>^ e, de repente, atirou-a contra Davi, com a intenção de encravá-lo na parede. Davi, porém, escapou duas vezes.

[[v9-18-12]]

^<<v9-18-12,12>>^ Saul tinha medo de Davi, pois o SENHOR o havia abandonado e agora estava com Davi.

[[v9-18-13]]

^<<v9-18-13,13>>^ Por fim, Saul o afastou de sua presença e o nomeou comandante de mil soldados, e Davi conduzia as tropas vitoriosamente nas batalhas.

[[v9-18-14]]

^<<v9-18-14,14>>^ Davi continuou a ter êxito em tudo que fazia, pois o SENHOR estava com ele.

[[v9-18-15]]

^<<v9-18-15,15>>^ Quando Saul viu isso, teve ainda mais medo.

[[v9-18-16]]

^<<v9-18-16,16>>^ Mas todo o Israel e todo o Judá amavam Davi, porque ele conduzia as tropas vitoriosamente nas batalhas.

[[v9-18-17]]

^<<v9-18-17,17>>^ Certo dia, Saul disse a Davi: "Estou pronto a lhe dar minha filha mais velha, Merabe, por esposa. Mas antes, sirva-me como um guerreiro valente, lutando nas batalhas do SENHOR". Pois Saul pensou: "Em vez de matá-lo eu mesmo, vou enviá-lo aos filisteus, e eles o matarão".

[[v9-18-18]]

^<<v9-18-18,18>>^ Davi, porém, respondeu a Saul: "Quem sou eu, e quem é minha família em Israel para que eu me torne genro do rei?".

[[v9-18-19]]

^<<v9-18-19,19>>^ Assim, quando chegou o tempo de Saul dar sua filha Merabe em casamento a Davi, ele a deu a Adriel, um homem de Meolá.

[[v9-18-20]]

^<<v9-18-20,20>>^ Contudo, a outra filha de Saul, Mical, amava Davi, e Saul ficou contente quando soube disso.

[[v9-18-21]]

^<<v9-18-21,21>>^ "É mais uma oportunidade de os filisteus matarem Davi!", pensou ele. Para Davi, porém, ele disse: "Você tem mais uma oportunidade de se tornar meu genro".

[[v9-18-22]]

^<<v9-18-22,22>>^ Então Saul instruiu seus servos a dizerem a Davi, em particular: "O rei gosta muito de você, e nós também. Por que não aceita a oferta do rei e se torna genro dele?".

[[v9-18-23]]

^<<v9-18-23,23>>^ Quando disseram isso a Davi, ele respondeu: "Como um homem pobre e de família humilde terá condições de pagar o dote da filha de um rei?".

[[v9-18-24]]

^<<v9-18-24,24>>^ Então os homens de Saul contaram-lhe o que Davi disse,

[[v9-18-25]]

^<<v9-18-25,25>>^ e Saul respondeu: "Digam a Davi que o único dote que quero são cem prepúcios de filisteus! Desejo apenas me vingar de meus inimigos". Mas Saul planejava que Davi fosse morto na luta.

[[v9-18-26]]

^<<v9-18-26,26>>^ Quando os servos de Saul trouxeram essa notícia a Davi, ele aceitou a oferta de bom grado. Antes do prazo estipulado,

[[v9-18-27]]

^<<v9-18-27,27>>^ ele e seus homens saíram e mataram duzentos filisteus. Davi cumpriu a exigência para tornar-se genro do rei, trazendo-lhe os prepúcios. Então Saul deu sua filha Mical por esposa a Davi.

[[v9-18-28]]

^<<v9-18-28,28>>^ Quando Saul percebeu que o SENHOR estava com Davi, e viu como sua filha Mical o amava,

[[v9-18-29]]

^<<v9-18-29,29>>^ temeu Davi ainda mais e continuou a ser inimigo dele pelo resto de sua vida.

[[v9-18-30]]

^<<v9-18-30,30>>^ Sempre que os comandantes dos filisteus atacavam, Davi era mais bem-sucedido contra eles que todos os outros oficiais de Saul. Assim, o nome de Davi se tornou muito famoso.

'''

xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[&#60; Capítulo Anterior] | <<v9-18-0,Topo>> | xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[Próximo Capítulo &#62;]