include::./index.adoc[]

[[v9-10-0]]
=== 1 Samuel, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v9-10-1]]

^<<v9-10-1,1>>^ Samuel pegou uma vasilha de óleo e o derramou sobre a cabeça de Saul. Depois, beijou Saul e disse: "Faço isto porque o SENHOR o nomeou como líder de Israel, sua propriedade especial.

[[v9-10-2]]

^<<v9-10-2,2>>^ Hoje, quando você partir, verá dois homens ao lado do túmulo de Raquel, em Zelza, na divisa de Benjamim. Eles lhe dirão que as jumentas foram encontradas e que seu pai deixou de se preocupar com elas e agora está preocupado com vocês, perguntando: ‘Que farei para encontrar meu filho?’.

[[v9-10-3]]

^<<v9-10-3,3>>^ "Quando você chegar ao carvalho de Tabor, encontrará três homens vindo em sua direção; estão a caminho de Betel, onde vão adorar a Deus. Um deles estará levando três cabritos, outro, três pães, e o terceiro, uma vasilha de couro cheia de vinho.

[[v9-10-4]]

^<<v9-10-4,4>>^ Eles o cumprimentarão e lhe oferecerão dois pães, que você deve aceitar.

[[v9-10-5]]

^<<v9-10-5,5>>^ "Quando chegar a Gibeá-Eloim, onde fica o destacamento dos filisteus, encontrará um grupo de profetas descendo do lugar de adoração. Virão tocando harpa, tamborim, flauta e lira, e estarão profetizando.

[[v9-10-6]]

^<<v9-10-6,6>>^ Nesse momento, o Espírito do SENHOR virá poderosamente sobre você, e você profetizará com eles. Será transformado numa pessoa diferente.

[[v9-10-7]]

^<<v9-10-7,7>>^ Depois que esses sinais se cumprirem, faça o que tiver de fazer, pois Deus está com você.

[[v9-10-8]]

^<<v9-10-8,8>>^ Em seguida, vá a Gilgal adiante de mim. Eu o encontrarei ali para sacrificar holocaustos e ofertas de paz. Espere lá durante sete dias, até eu chegar e lhe dar mais instruções".

[[v9-10-9]]

^<<v9-10-9,9>>^ Assim que Saul se virou para partir, Deus lhe deu um novo coração, e todos os sinais anunciados por Samuel se cumpriram naquele dia.

[[v9-10-10]]

^<<v9-10-10,10>>^ Ao chegarem a Gibeá, Saul e o servo viram um grupo de profetas vindo em sua direção. Então o Espírito de Deus veio poderosamente sobre Saul, e ele começou a profetizar com eles.

[[v9-10-11]]

^<<v9-10-11,11>>^ Quando aqueles que o conheciam souberam disso, perguntaram uns aos outros: "O que aconteceu com o filho de Quis? Acaso Saul também é profeta?".

[[v9-10-12]]

^<<v9-10-12,12>>^ Um dos que estavam ali perguntou: "Qualquer um pode se tornar profeta, seja quem for seu pai?". Essa é a origem do ditado: "Acaso Saul também é profeta?".

[[v9-10-13]]

^<<v9-10-13,13>>^ Depois que Saul terminou de profetizar, subiu ao lugar de adoração.

[[v9-10-14]]

^<<v9-10-14,14>>^ O tio de Saul perguntou a ele e ao servo: "Onde vocês estavam?". Saul respondeu: "Saímos para procurar as jumentas, mas não conseguimos encontrá-las. Então fomos a Samuel para lhe perguntar onde elas estavam".

[[v9-10-15]]

^<<v9-10-15,15>>^ "E o que foi que Samuel lhe disse?", perguntou o tio.

[[v9-10-16]]

^<<v9-10-16,16>>^ "Disse que as jumentas já haviam sido encontradas", respondeu Saul. Contudo, não contou ao tio o que Samuel tinha dito sobre o reino.

[[v9-10-17]]

^<<v9-10-17,17>>^ Algum tempo depois, Samuel convocou todo o povo para se reunir diante do SENHOR em Mispá.

[[v9-10-18]]

^<<v9-10-18,18>>^ Disse ele aos israelitas: "Assim diz o SENHOR, o Deus de Israel: Eu os tirei do Egito e os livrei dos egípcios e de todas as nações que os oprimiam.

[[v9-10-19]]

^<<v9-10-19,19>>^ Mas, apesar de eu ter resgatado vocês de suas angústias e aflições, hoje vocês rejeitaram seu Deus e disseram: ‘Queremos um rei!’. Agora, portanto, apresentem-se diante do SENHOR, de acordo com suas tribos e seus clãs".

[[v9-10-20]]

^<<v9-10-20,20>>^ Então Samuel reuniu todas as tribos de Israel, e a tribo de Benjamim foi escolhida por sorteio.

[[v9-10-21]]

^<<v9-10-21,21>>^ Em seguida, Samuel reuniu cada família da tribo de Benjamim, e a família de Matri foi sorteada. Por fim, Saul, filho de Quis foi escolhido dentre eles. Quando o procuraram, porém, não o encontraram.

[[v9-10-22]]

^<<v9-10-22,22>>^ Por isso, perguntaram ao SENHOR: "Ele já chegou?". O SENHOR respondeu: "Está escondido no meio da bagagem".

[[v9-10-23]]

^<<v9-10-23,23>>^ Eles correram até lá e o trouxeram. Era tão alto que os outros chegavam apenas a seus ombros.

[[v9-10-24]]

^<<v9-10-24,24>>^ Samuel disse ao povo: "Este é o homem que o SENHOR escolheu para ser seu rei. Não há ninguém semelhante a ele em todo o Israel". E todo o povo gritou: "Viva o rei!".

[[v9-10-25]]

^<<v9-10-25,25>>^ Então Samuel explicou ao povo os direitos e deveres do rei. Escreveu-os num rolo e o colocou diante do SENHOR. Depois, mandou todo o povo para casa.

[[v9-10-26]]

^<<v9-10-26,26>>^ Saul também voltou para sua casa, em Gibeá, acompanhado por um grupo de homens cujo coração Deus tinha tocado.

[[v9-10-27]]

^<<v9-10-27,27>>^ Havia, no entanto, alguns desocupados que debochavam: "Esse sujeito nunca nos salvará!". Desprezaram Saul e se recusaram a lhe trazer presentes. Mas Saul não lhes deu atenção.

'''

xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[&#60; Capítulo Anterior] | <<v9-10-0,Topo>> | xref:009-1-samuel/009-1-samuel-011.adoc#v9-11-0[Próximo Capítulo &#62;]