include::./index.adoc[]

[[v9-14-0]]
=== 1 Samuel, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v9-14-1]]

^<<v9-14-1,1>>^ Certo dia, Jônatas, filho de Saul, disse a seu escudeiro: "Venha, vamos ao lugar onde fica o destacamento dos filisteus". Mas Jônatas não contou a seu pai o que pretendia fazer.

[[v9-14-2]]

^<<v9-14-2,2>>^ Enquanto isso, Saul estava acampado nos arredores de Gibeá, em volta da árvore de romãs em Migrom, junto com cerca de seiscentos homens.

[[v9-14-3]]

^<<v9-14-3,3>>^ Entre eles estava Aías, o sacerdote, que levava o colete sacerdotal. Aías era filho de Aitube, irmão de Icabode, filho de Fineias, filho de Eli, que tinha servido como sacerdote do SENHOR em Siló. Ninguém percebeu que Jônatas havia saído do acampamento.

[[v9-14-4]]

^<<v9-14-4,4>>^ Para chegar ao destacamento dos filisteus, teve de passar por entre dois penhascos; um se chamava Bozez, e o outro, Sené.

[[v9-14-5]]

^<<v9-14-5,5>>^ Um ficava ao norte, de frente para Micmás, e o outro, ao sul, de frente para Geba.

[[v9-14-6]]

^<<v9-14-6,6>>^ Jônatas disse a seu escudeiro: "Vamos atravessar até o destacamento daqueles incircuncisos! Quem sabe o SENHOR nos ajudará, pois nada pode deter o SENHOR. Ele pode vencer com muitos guerreiros e, também, com apenas uns poucos!".

[[v9-14-7]]

^<<v9-14-7,7>>^ "Faça o que lhe parecer melhor", respondeu o escudeiro. "Eu o seguirei para onde o senhor for!"

[[v9-14-8]]

^<<v9-14-8,8>>^ "Pois bem", disse Jônatas. "Vamos atravessar e deixar que nos vejam.

[[v9-14-9]]

^<<v9-14-9,9>>^ Se disserem: ‘Fiquem onde estão, ou mataremos vocês’, ficaremos parados e não iremos até eles.

[[v9-14-10]]

^<<v9-14-10,10>>^ Mas, se disserem: ‘Subam até aqui e lutem’, então subiremos. Será sinal de que o SENHOR os entregará em nossas mãos."

[[v9-14-11]]

^<<v9-14-11,11>>^ Quando os filisteus os viram chegando, gritaram: "Vejam! Os hebreus estão saindo dos buracos onde estavam escondidos!".

[[v9-14-12]]

^<<v9-14-12,12>>^ Então os homens do destacamento gritaram para Jônatas e seu escudeiro: "Subam até aqui, e nós lhes daremos uma lição!". "Venha, suba logo atrás de mim", disse Jônatas a seu escudeiro. "O SENHOR entregou os filisteus nas mãos de Israel!"

[[v9-14-13]]

^<<v9-14-13,13>>^ Então subiram usando os pés e as mãos. Jônatas derrubava os filisteus e, atrás dele, seu escudeiro os matava.

[[v9-14-14]]

^<<v9-14-14,14>>^ Mataram, no total, cerca de vinte homens, numa pequena porção de terra.

[[v9-14-15]]

^<<v9-14-15,15>>^ De repente, o pânico tomou conta do exército filisteu, tanto no acampamento como no campo, e também nos destacamentos e nos grupos de ataque. Naquele instante, houve um terremoto, e todos se encheram de terror.

[[v9-14-16]]

^<<v9-14-16,16>>^ As sentinelas de Saul em Gibeá de Benjamim viram que o imenso exército dos filisteus começou a debandar em todas as direções.

[[v9-14-17]]

^<<v9-14-17,17>>^ Saul ordenou ao povo: "Façam a chamada e verifiquem quem está faltando!". Quando fizeram a chamada, descobriram que Jônatas e seu escudeiro não estavam ali.

[[v9-14-18]]

^<<v9-14-18,18>>^ Então Saul gritou para Aías: "Traga o colete sacerdotal!", pois, naquele tempo, Aías usava o colete sacerdotal diante dos israelitas.

[[v9-14-19]]

^<<v9-14-19,19>>^ Enquanto Saul falava com o sacerdote, o tumulto e a gritaria no acampamento dos filisteus aumentaram. Então Saul disse ao sacerdote: "Não precisa mais usar o colete!".

[[v9-14-20]]

^<<v9-14-20,20>>^ Então Saul e todos os soldados correram para a batalha e encontraram os filisteus matando uns aos outros. Havia grande confusão por toda parte.

[[v9-14-21]]

^<<v9-14-21,21>>^ Até os hebreus que antes haviam desertado para o lado dos filisteus se rebelaram e se uniram a Saul, a Jônatas e ao restante dos israelitas.

[[v9-14-22]]

^<<v9-14-22,22>>^ Quando os homens de Israel que haviam se escondido na região montanhosa de Efraim ouviram que os filisteus fugiam, também os perseguiram.

[[v9-14-23]]

^<<v9-14-23,23>>^ Assim, o SENHOR livrou Israel naquele dia, e a batalha continuou até além de Bete-Áven.

[[v9-14-24]]

^<<v9-14-24,24>>^ Os homens de Israel estavam exaustos naquele dia, pois Saul lhes havia imposto este juramento: "Maldito seja aquele que comer antes do anoitecer, antes de eu ter me vingado inteiramente de meus inimigos". Por isso, ninguém comeu nada o dia todo,

[[v9-14-25]]

^<<v9-14-25,25>>^ embora tivessem encontrado favos de mel no chão do bosque.

[[v9-14-26]]

^<<v9-14-26,26>>^ Não se atreveram a provar o mel, pois temiam o juramento exigido por Saul.

[[v9-14-27]]

^<<v9-14-27,27>>^ Jônatas, porém, não sabendo do juramento de seu pai, enfiou a ponta de uma vara num favo e comeu o mel. Depois de comer, recuperou as forças.

[[v9-14-28]]

^<<v9-14-28,28>>^ Vendo isso, um dos soldados lhe disse: "Seu pai obrigou o exército a fazer um juramento severo, pelo qual quem comer alguma coisa hoje será maldito. Por isso todos estão exaustos".

[[v9-14-29]]

^<<v9-14-29,29>>^ "Meu pai trouxe desgraça sobre o povo!", exclamou Jônatas. "Vejam como recuperei as forças depois de provar um pouco de mel.

[[v9-14-30]]

^<<v9-14-30,30>>^ Se os homens tivessem recebido permissão para comer à vontade do alimento que encontraram entre os inimigos, imaginem quantos filisteus mais teríamos matado!"

[[v9-14-31]]

^<<v9-14-31,31>>^ Os israelitas perseguiram e mataram filisteus o dia todo, desde Micmás até Aijalom, e ficaram cada vez mais enfraquecidos.

[[v9-14-32]]

^<<v9-14-32,32>>^ Naquela noite, tomaram apressadamente os despojos da batalha; mataram ovelhas, bois e bezerros e comeram a carne com sangue.

[[v9-14-33]]

^<<v9-14-33,33>>^ Alguém foi dizer a Saul: "Veja, os soldados estão pecando contra o SENHOR, comendo carne com sangue". "Vocês cometeram um grande pecado!", disse Saul. "Procurem uma pedra grande e tragam-na para cá.

[[v9-14-34]]

^<<v9-14-34,34>>^ Depois, saiam entre os soldados e digam-lhes: ‘Tragam os bois e as ovelhas até aqui! Abatam os animais e deixem o sangue escorrer antes de comer. Não pequem contra o SENHOR, comendo carne ainda com sangue’." Naquela noite, portanto, todos os soldados levaram os animais e os abateram ali.

[[v9-14-35]]

^<<v9-14-35,35>>^ Então Saul construiu um altar para o SENHOR; foi o primeiro altar que ele construiu para o SENHOR.

[[v9-14-36]]

^<<v9-14-36,36>>^ Depois Saul disse: "Vamos perseguir os filisteus a noite toda, saqueá-los até o amanhecer e destruir até o último deles". Seus homens responderam: "Faremos o que o rei achar melhor". O sacerdote, porém, disse: "Primeiro vamos consultar Deus".

[[v9-14-37]]

^<<v9-14-37,37>>^ Então Saul perguntou a Deus: "Devemos ir atrás dos filisteus? Tu os entregarás nas mãos de Israel?". Mas Deus não lhe respondeu naquele dia.

[[v9-14-38]]

^<<v9-14-38,38>>^ Então Saul ordenou: "Todos os comandantes do exército, apresentem-se a mim! Descubram como e por que aconteceu esse pecado!

[[v9-14-39]]

^<<v9-14-39,39>>^ Tão certo como vive o SENHOR, aquele que resgatou Israel, o culpado morrerá, mesmo que seja meu filho Jônatas!". Contudo, ninguém lhe disse nada.

[[v9-14-40]]

^<<v9-14-40,40>>^ Saul disse a todo o Israel: "Jônatas e eu ficaremos aqui, e todos vocês ficarão ali". E os homens responderam: "Faça o que o rei achar melhor".

[[v9-14-41]]

^<<v9-14-41,41>>^ Em seguida, Saul orou: "Ó SENHOR, o Deus de Israel, mostra-nos quem é culpado e quem é inocente". Por sorteio, Jônatas e Saul foram escolhidos como sendo os culpados, e o povo foi declarado inocente.

[[v9-14-42]]

^<<v9-14-42,42>>^ Saul disse: "Façam outro sorteio entre mim e Jônatas". E Jônatas foi escolhido como o culpado.

[[v9-14-43]]

^<<v9-14-43,43>>^ "Diga-me o que você fez", ordenou Saul. "Provei um pouco de mel", confessou Jônatas. "Foi apenas uma pequena porção, na ponta de minha vara. Estou pronto para morrer!"

[[v9-14-44]]

^<<v9-14-44,44>>^ Então Saul disse: "Sim, Jônatas, você deve morrer. Que Deus me castigue severamente se você não for morto por isso".

[[v9-14-45]]

^<<v9-14-45,45>>^ Os soldados, porém, disseram a Saul: "Jônatas conquistou esta grande vitória para Israel. Acaso ele deve morrer? De maneira nenhuma! Tão certo como o SENHOR vive, ninguém tocará num fio de cabelo da cabeça dele, pois hoje Deus o ajudou a realizar um grande feito". E assim o povo salvou Jônatas da morte.

[[v9-14-46]]

^<<v9-14-46,46>>^ Então Saul deixou de perseguir os filisteus, e eles voltaram para sua terra.

[[v9-14-47]]

^<<v9-14-47,47>>^ Depois que Saul havia se firmado como rei de Israel, lutou contra seus inimigos ao redor: contra Moabe, Amom e Edom, contra os reis de Zobá e contra os filisteus. E, para qualquer lado que se voltava, era vitorioso.

[[v9-14-48]]

^<<v9-14-48,48>>^ Realizou grandes feitos e derrotou os amalequitas, livrando Israel de todos que o haviam saqueado.

[[v9-14-49]]

^<<v9-14-49,49>>^ Os filhos de Saul eram Jônatas, Isbosete e Malquisua. Também tinha duas filhas: Merabe, a mais velha, e Mical, a mais nova.

[[v9-14-50]]

^<<v9-14-50,50>>^ A esposa de Saul se chamava Ainoã, filha de Aimaás. O comandante do exército de Saul era Abner, filho de Ner, tio de Saul.

[[v9-14-51]]

^<<v9-14-51,51>>^ Quis, pai de Saul, e Ner, pai de Abner, eram filhos de Abiel.

[[v9-14-52]]

^<<v9-14-52,52>>^ Os israelitas lutaram ferrenhamente contra os filisteus durante toda a vida de Saul. Por isso, sempre que Saul via um jovem forte e valente, logo o convocava para seu exército.

'''

xref:009-1-samuel/009-1-samuel-013.adoc#v9-13-0[&#60; Capítulo Anterior] | <<v9-14-0,Topo>> | xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[Próximo Capítulo &#62;]