include::./index.adoc[]

[[v9-1-0]]
=== 1 Samuel, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v9-1-1]]

^<<v9-1-1,1>>^ Havia um homem chamado Elcana, que vivia em Ramá, na região de Zufe, na região montanhosa de Efraim. Era filho de Jeroão, filho de Eliú, filho de Toú, filho de Zufe, da tribo de Efraim.

[[v9-1-2]]

^<<v9-1-2,2>>^ Elcana tinha duas esposas: a primeira se chamava Ana, e a segunda, Penina. Penina tinha filhos; Ana, porém, não os tinha.

[[v9-1-3]]

^<<v9-1-3,3>>^ Todos os anos, Elcana subia de sua cidade até Siló para adorar o SENHOR dos Exércitos e oferecer sacrifícios a ele. Nesse tempo, os sacerdotes do SENHOR eram Hofni e Fineias, os dois filhos de Eli.

[[v9-1-4]]

^<<v9-1-4,4>>^ Quando Elcana apresentava seu sacrifício, dava porções de carne à sua esposa Penina e a cada um dos filhos e filhas dela.

[[v9-1-5]]

^<<v9-1-5,5>>^ A Ana, porém, dava uma porção especial, porque a amava, apesar de o SENHOR não lhe ter dado filhos.

[[v9-1-6]]

^<<v9-1-6,6>>^ E sua rival a provocava e zombava dela, porque o SENHOR não lhe tinha dado filhos.

[[v9-1-7]]

^<<v9-1-7,7>>^ Todos os anos era a mesma coisa: Penina provocava Ana quando iam à casa do SENHOR e, a cada vez, Ana chorava muito e ficava sem comer.

[[v9-1-8]]

^<<v9-1-8,8>>^ "Ana, por que você chora?", perguntava Elcana, seu marido. "Por que não come? Por que está tão triste? Será que não sou melhor para você do que dez filhos?"

[[v9-1-9]]

^<<v9-1-9,9>>^ Certa vez, depois que comeram e beberam em Siló, Ana se levantou. O sacerdote Eli estava sentado ao lado da entrada do templo do SENHOR.

[[v9-1-10]]

^<<v9-1-10,10>>^ Ana estava muito angustiada e chorava sem parar enquanto orava ao SENHOR.

[[v9-1-11]]

^<<v9-1-11,11>>^ Então fez o seguinte voto: "Ó SENHOR dos Exércitos, se olhares com atenção para o sofrimento de tua serva, se responderes à minha oração e me deres um filho, eu o dedicarei para sempre ao SENHOR, e o cabelo dele nunca será cortado".

[[v9-1-12]]

^<<v9-1-12,12>>^ Enquanto ela fazia sua oração ao SENHOR, Eli a observava.

[[v9-1-13]]

^<<v9-1-13,13>>^ Viu que os lábios dela se moviam, mas, como não ouvia som algum, pensou que ela estivesse bêbada.

[[v9-1-14]]

^<<v9-1-14,14>>^ "Até quando vai se embriagar?", disse ele. "Largue esse vinho!"

[[v9-1-15]]

^<<v9-1-15,15>>^ Ana respondeu: "Meu senhor, não bebi vinho, nem outra coisa mais forte. Eu estava derramando meu coração diante do SENHOR, pois sou uma mulher profundamente triste.

[[v9-1-16]]

^<<v9-1-16,16>>^ Não pense que sou uma mulher sem caráter! Estava apenas orando por causa de minha grande angústia e aflição".

[[v9-1-17]]

^<<v9-1-17,17>>^ "Nesse caso, vá em paz", disse Eli. "Que o Deus de Israel lhe conceda o que você pediu."

[[v9-1-18]]

^<<v9-1-18,18>>^ "Muito obrigada!", exclamou ela. Então Ana voltou e começou a se alimentar novamente, e seu rosto já não estava triste.

[[v9-1-19]]

^<<v9-1-19,19>>^ Na manhã seguinte, a família toda se levantou bem cedo e foi adorar o SENHOR novamente. Depois, voltaram para casa, em Ramá. Elcana teve relações com Ana, e o SENHOR se lembrou dela.

[[v9-1-20]]

^<<v9-1-20,20>>^ No devido tempo, Ana engravidou e teve um filho. Ela lhe deu o nome de Samuel, e disse: "Eu o pedi ao SENHOR".

[[v9-1-21]]

^<<v9-1-21,21>>^ No ano seguinte, Elcana e sua família fizeram a viagem anual para oferecer sacrifícios ao SENHOR e cumprir seu voto.

[[v9-1-22]]

^<<v9-1-22,22>>^ Ana, porém, não foi. "Vamos esperar até o menino ser desmamado", disse ela ao marido. "Então o levarei ao SENHOR e o deixarei lá para sempre."

[[v9-1-23]]

^<<v9-1-23,23>>^ "Faça como lhe parecer melhor", respondeu Elcana. "Fique aqui até ele desmamar, e que o SENHOR a ajude a cumprir sua promessa." Então ela ficou em casa e cuidou de seu filho até desmamá-lo.

[[v9-1-24]]

^<<v9-1-24,24>>^ Quando o menino foi desmamado, Ana o levou à casa do SENHOR em Siló, embora ele ainda fosse pequeno. Também levou um novilho de três anos para o sacrifício, um cesto de farinha e uma vasilha de couro cheia de vinho.

[[v9-1-25]]

^<<v9-1-25,25>>^ Depois que sacrificaram o novilho, levaram o menino a Eli,

[[v9-1-26]]

^<<v9-1-26,26>>^ e Ana lhe disse: "Com certeza o senhor se lembra de mim. Sou a mulher que esteve aqui anos atrás, orando ao SENHOR.

[[v9-1-27]]

^<<v9-1-27,27>>^ Pedi ao SENHOR que me desse este menino, e o SENHOR atendeu a meu pedido.

[[v9-1-28]]

^<<v9-1-28,28>>^ Agora, eu o dedico ao SENHOR. Por toda a sua vida ele pertencerá ao SENHOR". E ali adoraram o SENHOR.

'''

xref:008-rute/008-rute-004.adoc#v8-4-0[&#60; Capítulo Anterior] | <<v9-1-0,Topo>> | xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[Próximo Capítulo &#62;]