include::./index.adoc[]

[[v9-22-0]]
=== 1 Samuel, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v9-22-1]]

^<<v9-22-1,1>>^ Davi fugiu de Gate e se escondeu na caverna de Adulão. Quando souberam disso, seus irmãos e parentes foram encontrá-lo ali.

[[v9-22-2]]

^<<v9-22-2,2>>^ Logo, outros começaram a chegar, pessoas aflitas, endividadas e descontentes. Davi acabou se tornando o líder de cerca de quatrocentos homens.

[[v9-22-3]]

^<<v9-22-3,3>>^ Mais tarde, Davi foi a Mispá, em Moabe, e pediu ao rei: "Por favor, permita que meu pai e minha mãe morem aqui até que eu saiba o que Deus fará comigo".

[[v9-22-4]]

^<<v9-22-4,4>>^ Assim, os pais de Davi permaneceram com o rei de Moabe por todo o tempo que Davi ficou na fortaleza.

[[v9-22-5]]

^<<v9-22-5,5>>^ Certo dia, o profeta Gade disse a Davi: "Deixe a fortaleza e volte à terra de Judá". Então Davi foi para o bosque de Herete.

[[v9-22-6]]

^<<v9-22-6,6>>^ Saul logo soube da chegada de Davi e dos homens que o acompanhavam. Nessa ocasião, o rei estava sentado com a lança na mão, cercado por seus oficiais, sob uma tamargueira na colina em Gibeá.

[[v9-22-7]]

^<<v9-22-7,7>>^ Quando ouviu a notícia, Saul gritou a seus oficiais: "Escutem, homens de Benjamim! Por acaso aquele filho de Jessé prometeu campos e videiras a todos vocês? Prometeu torná-los generais e capitães de seu exército?

[[v9-22-8]]

^<<v9-22-8,8>>^ Foi por isso que conspiraram contra mim? Pois nenhum de vocês me informou quando meu filho assumiu um compromisso solene com o filho de Jessé. Não tiveram pena de mim. Sim, meu próprio filho, instigando Davi a me matar, como ele procura fazer hoje mesmo!".

[[v9-22-9]]

^<<v9-22-9,9>>^ Então Doegue, o edomita, que estava ali com os oficiais de Saul, disse: "Quando estava em Nobe, vi o filho de Jessé falar com o sacerdote Aimeleque, filho de Aitube.

[[v9-22-10]]

^<<v9-22-10,10>>^ Aimeleque consultou o SENHOR em favor dele. Depois, deu-lhe alimento e a espada de Golias, o filisteu".

[[v9-22-11]]

^<<v9-22-11,11>>^ Então o rei Saul mandou chamar Aimeleque e toda a sua família, que serviam como sacerdotes em Nobe, e todos vieram até o rei.

[[v9-22-12]]

^<<v9-22-12,12>>^ Quando chegaram, Saul gritou: "Escute, filho de Aitube!". "Sim, meu senhor", respondeu Aimeleque.

[[v9-22-13]]

^<<v9-22-13,13>>^ "Por que você e o filho de Jessé conspiraram contra mim?", perguntou Saul. "Por que você lhe deu alimento e uma espada? Por que consultou Deus em favor dele? Por que o instigou a me matar, como ele procura fazer hoje mesmo?"

[[v9-22-14]]

^<<v9-22-14,14>>^ Aimeleque respondeu: "Ó rei, não existe entre todos os seus servos alguém tão fiel quanto Davi, seu genro. Ele é capitão de sua guarda pessoal e membro muito honrado de sua casa.

[[v9-22-15]]

^<<v9-22-15,15>>^ Com certeza essa não foi a primeira vez que consultei a Deus em favor dele. Que o rei não me acuse nesta questão, nem à minha família, pois eu não sabia de conspiração alguma contra o senhor!".

[[v9-22-16]]

^<<v9-22-16,16>>^ O rei, porém, disse: "Certamente você será morto, junto com toda a família de seu pai!".

[[v9-22-17]]

^<<v9-22-17,17>>^ Então ordenou à sua guarda pessoal: "Matem estes sacerdotes do SENHOR, pois eles são aliados de Davi e conspiraram com ele! Sabiam que ele estava fugindo de mim, mas não me avisaram!". Contudo, os homens de Saul se recusaram a matar os sacerdotes do SENHOR.

[[v9-22-18]]

^<<v9-22-18,18>>^ Então o rei disse a Doegue: "Mate-os você". E, naquele dia, Doegue, o edomita, os atacou e, ao todo, matou 85 sacerdotes, ainda vestidos com suas túnicas sacerdotais de linho.

[[v9-22-19]]

^<<v9-22-19,19>>^ Depois foi a Nobe, a cidade dos sacerdotes, e matou as famílias deles: homens, mulheres, crianças e recém-nascidos, além de todo o gado, jumentos e ovelhas.

[[v9-22-20]]

^<<v9-22-20,20>>^ Somente Abiatar, um dos filhos de Aimeleque, filho de Aitube, escapou e fugiu para juntar-se a Davi.

[[v9-22-21]]

^<<v9-22-21,21>>^ Quando contou a Davi que Saul havia matado os sacerdotes do SENHOR,

[[v9-22-22]]

^<<v9-22-22,22>>^ Davi exclamou: "Eu sabia! Quando vi Doegue, o edomita, naquele dia, sabia que ele contaria a Saul. Agora sou responsável pela morte de toda a família de seu pai.

[[v9-22-23]]

^<<v9-22-23,23>>^ Fique aqui comigo, e não tenha medo. Eu o protegerei, pois a mesma pessoa quer matar nós dois. Comigo você estará seguro".

'''

xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[&#60; Capítulo Anterior] | <<v9-22-0,Topo>> | xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[Próximo Capítulo &#62;]