include::./index.adoc[]

[[v9-20-0]]
=== 1 Samuel, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v9-20-1]]

^<<v9-20-1,1>>^ Davi fugiu de Naiote, em Ramá, e se encontrou com Jônatas. "O que eu fiz?", disse Davi. "Qual é meu crime? Que pecado cometi contra seu pai para que ele esteja tão decidido a me matar?"

[[v9-20-2]]

^<<v9-20-2,2>>^ "Isso não vai acontecer!", respondeu Jônatas. "Você não será morto. Ele sempre me conta tudo que pretende fazer, até mesmo as coisas de pouca importância. Sei que meu pai não esconderia de mim algo dessa natureza. Não é assim!"

[[v9-20-3]]

^<<v9-20-3,3>>^ Então Davi fez um juramento diante de Jônatas: "Seu pai, sabendo muito bem de nossa amizade, disse a si mesmo: ‘Não contarei a Jônatas. Ele ficaria magoado’. Mas, tão certo como vive o SENHOR e como você mesmo vive, eu estou a apenas um passo da morte!".

[[v9-20-4]]

^<<v9-20-4,4>>^ Jônatas perguntou: "O que posso fazer para ajudá-lo?".

[[v9-20-5]]

^<<v9-20-5,5>>^ Davi respondeu: "Amanhã celebraremos a festa da lua nova. Sempre me sentei com o rei para comer nessa ocasião, mas amanhã me esconderei no campo e ficarei ali até o entardecer do terceiro dia.

[[v9-20-6]]

^<<v9-20-6,6>>^ Se seu pai perguntar onde estou, diga a ele: ‘Davi insistiu que eu o deixasse ir para casa, em Belém, participar do sacrifício que toda a família dele oferece a cada ano’.

[[v9-20-7]]

^<<v9-20-7,7>>^ Se ele disser: ‘Está bem’, então você saberá que não corro perigo. Mas, se ele se enfurecer, você saberá que ele está decidido a me fazer mal.

[[v9-20-8]]

^<<v9-20-8,8>>^ Mostre-me sua lealdade como amigo, pois assumimos um compromisso solene diante do SENHOR. Se, por acaso, você acha que cometi alguma ofensa contra seu pai, mate-me você mesmo, aqui e agora! Não é necessário me entregar a seu pai".

[[v9-20-9]]

^<<v9-20-9,9>>^ "Nunca!", exclamou Jônatas. "Você sabe que, se eu tivesse qualquer suspeita de que meu pai planeja matá-lo, avisaria você no mesmo instante."

[[v9-20-10]]

^<<v9-20-10,10>>^ Então Davi perguntou: "Como saberei se seu pai ficou irado?".

[[v9-20-11]]

^<<v9-20-11,11>>^ Jônatas respondeu: "Venha ao campo comigo", e os dois foram juntos para lá.

[[v9-20-12]]

^<<v9-20-12,12>>^ Então Jônatas disse a Davi: "Prometo diante do SENHOR, o Deus de Israel, que amanhã ou, no máximo, depois de amanhã, a esta hora, conversarei com meu pai e avisarei você logo em seguida do que ele pensa a seu respeito. Se ele falar a seu respeito de modo favorável, informarei você.

[[v9-20-13]]

^<<v9-20-13,13>>^ Mas, se ele estiver irado e quiser matá-lo, que o SENHOR me castigue severamente se eu não avisar você, para que possa escapar em segurança. Que o SENHOR esteja com você como esteve com meu pai.

[[v9-20-14]]

^<<v9-20-14,14>>^ E que você me trate com o amor leal do SENHOR enquanto eu viver. Mas, se eu morrer,

[[v9-20-15]]

^<<v9-20-15,15>>^ trate minha família com esse amor leal, mesmo quando o SENHOR eliminar da face da terra todos os seus inimigos".

[[v9-20-16]]

^<<v9-20-16,16>>^ Então Jônatas assumiu um compromisso solene com Davi e sua descendência e disse: "Que o SENHOR destrua todos os inimigos de Davi!".

[[v9-20-17]]

^<<v9-20-17,17>>^ E Jônatas fez Davi reafirmar seu juramento de amizade, pois Jônatas o amava como a si mesmo.

[[v9-20-18]]

^<<v9-20-18,18>>^ Então Jônatas disse: "Amanhã celebraremos a festa da lua nova. Darão por sua falta quando virem que seu lugar à mesa está vazio.

[[v9-20-19]]

^<<v9-20-19,19>>^ Depois de amanhã, ao entardecer, vá ao lugar onde você se escondeu antes e espere ali, junto à pedra de Ezel.

[[v9-20-20]]

^<<v9-20-20,20>>^ Eu sairei e atirarei três flechas para o lado da pedra, como se atirasse num alvo.

[[v9-20-21]]

^<<v9-20-21,21>>^ Então mandarei um ajudante trazer de volta as flechas. Se você me ouvir dizer a ele: ‘As flechas estão deste lado’, saberá, tão certo como vive o SENHOR, que tudo está bem e que não há perigo algum.

[[v9-20-22]]

^<<v9-20-22,22>>^ Mas, se eu disser a ele: ‘Vá mais para frente; as flechas estão adiante’, significará que você deve partir de imediato, pois o SENHOR o manda ir embora.

[[v9-20-23]]

^<<v9-20-23,23>>^ E que o SENHOR nos ajude a preservar para sempre o forte laço de amizade que existe entre nós".

[[v9-20-24]]

^<<v9-20-24,24>>^ Então Davi se escondeu no campo e, quando começou a festa da lua nova, o rei sentou-se para comer.

[[v9-20-25]]

^<<v9-20-25,25>>^ Ocupou seu lugar de costume, encostado à parede, com Jônatas sentado diante dele e Abner ao seu lado. O lugar de Davi, porém, ficou vazio.

[[v9-20-26]]

^<<v9-20-26,26>>^ Saul não disse nada sobre isso naquele dia, pois pensou: "Deve ter acontecido algo que deixou Davi cerimonialmente impuro".

[[v9-20-27]]

^<<v9-20-27,27>>^ Mas, quando o lugar de Davi também ficou vazio no dia seguinte, Saul perguntou a Jônatas: "Por que o filho de Jessé não veio para a refeição nem ontem nem hoje?".

[[v9-20-28]]

^<<v9-20-28,28>>^ Jônatas respondeu: "Davi me pediu, com insistência, para ir a Belém.

[[v9-20-29]]

^<<v9-20-29,29>>^ Disse: ‘Por favor, deixe-me ir, pois nossa família oferecerá um sacrifício na cidade. Meu irmão exigiu que eu estivesse presente. Portanto, peço que me deixe ir ver meus irmãos’. Por isso ele não está aqui, à mesa do rei".

[[v9-20-30]]

^<<v9-20-30,30>>^ Saul se enfureceu com Jônatas e disse: "Seu traidor, filho de uma prostituta! Pensa que não sei que você quer que ele seja rei, para sua própria vergonha e de sua mãe?

[[v9-20-31]]

^<<v9-20-31,31>>^ Enquanto esse filho de Jessé viver, você jamais será rei. Agora vá buscá-lo para que eu o mate!".

[[v9-20-32]]

^<<v9-20-32,32>>^ "Por que ele deve morrer?", perguntou Jônatas a seu pai. "O que ele fez?"

[[v9-20-33]]

^<<v9-20-33,33>>^ Então Saul atirou sua lança contra Jônatas, com a intenção de matá-lo. Com isso, Jônatas viu que seu pai estava mesmo decidido a matar Davi.

[[v9-20-34]]

^<<v9-20-34,34>>^ Enfurecido, Jônatas levantou-se da mesa e, durante o segundo dia da festa, recusou-se a comer, frustrado pelo modo como seu pai havia desonrado Davi publicamente.

[[v9-20-35]]

^<<v9-20-35,35>>^ Na manhã seguinte, como combinado, Jônatas foi ao campo e levou consigo um ajudante para apanhar as flechas.

[[v9-20-36]]

^<<v9-20-36,36>>^ Disse ao ajudante: "Comece a correr, para que possa encontrar as flechas quando eu as atirar". O ajudante correu, e Jônatas atirou uma flecha para além dele.

[[v9-20-37]]

^<<v9-20-37,37>>^ Quando o ajudante estava quase chegando ao lugar onde a flecha havia caído, Jônatas gritou: "A flecha está mais à frente!

[[v9-20-38]]

^<<v9-20-38,38>>^ Rápido! Não fique aí parado!". Então o ajudante apanhou a flecha e correu de volta para seu senhor.

[[v9-20-39]]

^<<v9-20-39,39>>^ O ajudante não suspeitava de nada; apenas Jônatas e Davi entenderam o sinal.

[[v9-20-40]]

^<<v9-20-40,40>>^ Então Jônatas entregou o arco e as flechas ao ajudante e ordenou que os levasse de volta à cidade.

[[v9-20-41]]

^<<v9-20-41,41>>^ Assim que o ajudante foi embora, Davi saiu de seu esconderijo no lado sul da pedra de Ezel. Davi se curvou diante de Jônatas três vezes, com o rosto em terra. E, quando se beijaram e se despediram, ambos choravam, especialmente Davi.

[[v9-20-42]]

^<<v9-20-42,42>>^ Por fim, Jônatas disse a Davi: "Vá em paz, pois juramos lealdade um ao outro em nome do SENHOR. Que o SENHOR nos ajude a preservar para sempre o forte laço de amizade entre nós e entre nossos descendentes". Então Davi partiu, e Jônatas voltou à cidade.

'''

xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[&#60; Capítulo Anterior] | <<v9-20-0,Topo>> | xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[Próximo Capítulo &#62;]