include::./index.adoc[]

[[v9-2-0]]
=== 1 Samuel, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v9-2-1]]

^<<v9-2-1,1>>^ Então Ana orou: "Meu coração se alegra no SENHOR; o SENHOR me fortaleceu! Agora dou risada de meus inimigos; sim, eu me alegro porque me libertaste!

[[v9-2-2]]

^<<v9-2-2,2>>^ Ninguém é santo como o SENHOR; não há outro além de ti, não há Rocha como o nosso Deus!

[[v9-2-3]]

^<<v9-2-3,3>>^ "Deixem de ser tão orgulhosos e soberbos! Não falem com tamanha arrogância! Pois o SENHOR é um Deus que tudo sabe; ele julgará as ações de todos.

[[v9-2-4]]

^<<v9-2-4,4>>^ O arco dos poderosos foi quebrado, e os que tropeçavam agora estão firmes.

[[v9-2-5]]

^<<v9-2-5,5>>^ Os que tinham fartura de comida agora passam fome, e os que passavam fome estão saciados. A mulher que não tinha filhos agora tem sete, e a que tinha muitos desfalece.

[[v9-2-6]]

^<<v9-2-6,6>>^ O SENHOR tira a vida e dá a vida, faz descer à sepultura e de lá faz subir.

[[v9-2-7]]

^<<v9-2-7,7>>^ O SENHOR empobrece alguns e enriquece outros, humilha e também exalta.

[[v9-2-8]]

^<<v9-2-8,8>>^ Levanta o pobre do pó e do monte de cinzas tira o necessitado. Coloca-os entre príncipes e os faz sentar em lugares de honra. Ao SENHOR pertencem os alicerces da terra, e sobre eles firmou o mundo.

[[v9-2-9]]

^<<v9-2-9,9>>^ "Ele protegerá os fiéis, mas os perversos desaparecerão nas trevas, pois ninguém vencerá só pela força.

[[v9-2-10]]

^<<v9-2-10,10>>^ Os que lutam contra o Senhor serão despedaçados. Do céu ele troveja contra eles; o SENHOR julga em toda a terra. Ele dá poder a seu rei, concede força a seu ungido".

[[v9-2-11]]

^<<v9-2-11,11>>^ Então Elcana voltou para casa em Ramá. E o menino servia ao SENHOR ajudando o sacerdote Eli.

[[v9-2-12]]

^<<v9-2-12,12>>^ Os filhos de Eli eram homens perversos, que não tinham nenhuma consideração pelo SENHOR,

[[v9-2-13]]

^<<v9-2-13,13>>^ nem por seus deveres de sacerdotes. Cada vez que alguém oferecia um sacrifício, vinha um servo do sacerdote com um garfo grande, de três dentes. Enquanto a carne do animal sacrificado ainda estava cozinhando,

[[v9-2-14]]

^<<v9-2-14,14>>^ o servo colocava o garfo na panela, no tacho ou no caldeirão, e exigia que tudo que viesse com o garfo fosse entregue aos filhos de Eli. Assim eles tratavam todos os israelitas que iam adorar em Siló.

[[v9-2-15]]

^<<v9-2-15,15>>^ Às vezes, o servo chegava antes mesmo que a gordura do animal fosse queimada no altar, exigindo: "Não dê a carne cozida, mas sim a carne crua, para que o sacerdote a asse".

[[v9-2-16]]

^<<v9-2-16,16>>^ Se o homem que oferecia o sacrifício dizia: "Leve quanto quiser, mas antes é preciso queimar a gordura", o servo retrucava: "Não! Entregue a carne agora, ou eu a tomarei à força".

[[v9-2-17]]

^<<v9-2-17,17>>^ O pecado desses homens era muito sério aos olhos do SENHOR, pois eles tratavam com desprezo as ofertas para o SENHOR.

[[v9-2-18]]

^<<v9-2-18,18>>^ Samuel, porém, embora ainda fosse apenas um menino, servia ao SENHOR. Ele usava uma veste de linho semelhante à do sacerdote.

[[v9-2-19]]

^<<v9-2-19,19>>^ Cada ano, sua mãe lhe fazia uma pequena túnica e a levava quando ia com o marido oferecer o sacrifício anual.

[[v9-2-20]]

^<<v9-2-20,20>>^ Antes de Elcana e sua esposa voltarem para casa, Eli os abençoava e dizia: "Que o SENHOR lhes dê outros filhos em lugar deste que foi dedicado ao SENHOR".

[[v9-2-21]]

^<<v9-2-21,21>>^ E o SENHOR abençoou Ana, e ela engravidou e deu à luz três filhos e duas filhas. Enquanto isso, Samuel crescia na presença do SENHOR.

[[v9-2-22]]

^<<v9-2-22,22>>^ Eli já estava muito idoso, mas sabia o que seus filhos faziam ao povo de Israel, e que eles seduziam as moças que serviam junto à entrada da tenda do encontro.

[[v9-2-23]]

^<<v9-2-23,23>>^ Por isso lhes disse: "Ouvi de todo o povo o mal que vocês praticam. Por que continuam a agir assim?

[[v9-2-24]]

^<<v9-2-24,24>>^ Parem com isso, meus filhos! Não são bons os comentários que escuto entre o povo do SENHOR.

[[v9-2-25]]

^<<v9-2-25,25>>^ Se alguém peca contra outra pessoa, Deus poderá intervir em favor do culpado. Mas, se alguém peca contra o SENHOR, quem poderá interceder?". Contudo, os filhos de Eli não deram atenção ao pai, pois o SENHOR já havia decidido matá-los.

[[v9-2-26]]

^<<v9-2-26,26>>^ Enquanto isso, o menino Samuel crescia e era cada vez mais estimado pelo SENHOR e pelo povo.

[[v9-2-27]]

^<<v9-2-27,27>>^ Certo dia, veio a Eli um homem de Deus e lhe transmitiu a seguinte mensagem: "Assim diz o SENHOR: Eu me revelei a seus antepassados quando eles eram escravos do faraó, no Egito.

[[v9-2-28]]

^<<v9-2-28,28>>^ Escolhi seus antepassados dentre todas as tribos de Israel para serem meus sacerdotes, oferecerem sacrifícios sobre meu altar, queimarem incenso e usarem o colete sacerdotal em minha presença. Além disso, designei as ofertas queimadas dos israelitas a vocês, sacerdotes.

[[v9-2-29]]

^<<v9-2-29,29>>^ Então por que você despreza meus sacrifícios e ofertas? Por que honra seus filhos mais que a mim? Pois você e eles engordaram com as melhores partes das ofertas de meu povo, Israel!

[[v9-2-30]]

^<<v9-2-30,30>>^ "Portanto, assim declara o SENHOR, Deus de Israel: Prometi que membros de sua família, da tribo de Levi, sempre seriam meus sacerdotes. Agora, porém, declara o SENHOR: Isso não acontecerá! Honrarei aqueles que me honram, e desprezarei aqueles que me desprezam.

[[v9-2-31]]

^<<v9-2-31,31>>^ Está chegando o tempo em que acabarei com a força de sua família, e nenhum de seus descendentes chegará à velhice.

[[v9-2-32]]

^<<v9-2-32,32>>^ Você verá a aflição de minha casa, e, quando eu trouxer todo o bem sobre Israel, ninguém em sua família chegará à velhice para testemunhar!

[[v9-2-33]]

^<<v9-2-33,33>>^ Sobreviverão os poucos que eu não eliminar do serviço em meu altar, mas seus olhos ficarão cegos e seu coração se partirá, e seus filhos morrerão pela espada.

[[v9-2-34]]

^<<v9-2-34,34>>^ E, para provar que minhas palavras se cumprirão, farei que seus dois filhos, Hofni e Fineias, morram no mesmo dia!

[[v9-2-35]]

^<<v9-2-35,35>>^ "Então levantarei um sacerdote fiel que me servirá e fará tudo que desejo. Estabelecerei a família dele, e eles serão sacerdotes diante do meu ungido para sempre.

[[v9-2-36]]

^<<v9-2-36,36>>^ Então todos que restarem de sua família se curvarão diante dele, mendigando dinheiro e alimento e pedindo: ‘Por favor, consiga para nós algum trabalho entre os sacerdotes, para termos o que comer’".

'''

xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[&#60; Capítulo Anterior] | <<v9-2-0,Topo>> | xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[Próximo Capítulo &#62;]