include::./index.adoc[]

[[v9-7-0]]
=== 1 Samuel, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v9-7-1]]

^<<v9-7-1,1>>^ Então os homens de Quiriate-Jearim foram buscar a arca do SENHOR. Eles a levaram até a casa de Abinadabe, numa colina, e consagraram seu filho Eleazar para tomar conta da arca do SENHOR.

[[v9-7-2]]

^<<v9-7-2,2>>^ A arca permaneceu em Quiriate-Jearim por muito tempo: vinte anos no total. Durante esse período, todo o Israel lamentava à espera de alguma ação do SENHOR.

[[v9-7-3]]

^<<v9-7-3,3>>^ Então Samuel disse a todo o povo de Israel: "Se, de fato, vocês desejam de todo o coração voltar ao SENHOR, livrem-se de seus deuses estrangeiros e de suas imagens de Astarote. Voltem o coração para o SENHOR e obedeçam somente a ele; então ele os livrará das mãos dos filisteus".

[[v9-7-4]]

^<<v9-7-4,4>>^ Assim, os israelitas se desfizeram de suas imagens de Baal e de Astarote e serviram somente ao SENHOR.

[[v9-7-5]]

^<<v9-7-5,5>>^ Então Samuel lhes disse: "Reúnam todo o Israel em Mispá, e eu orarei ao SENHOR por vocês".

[[v9-7-6]]

^<<v9-7-6,6>>^ Eles se reuniram em Mispá e tiraram água do poço e a derramaram diante do SENHOR. Também jejuaram o dia todo e confessaram que haviam pecado contra o SENHOR. (Foi em Mispá que Samuel se tornou juiz em Israel.)

[[v9-7-7]]

^<<v9-7-7,7>>^ Quando os governantes filisteus ouviram que os israelitas haviam se reunido em Mispá, mobilizaram seu exército e avançaram. Ao saber que os filisteus se aproximavam, os israelitas ficaram muito assustados.

[[v9-7-8]]

^<<v9-7-8,8>>^ "Não pare de clamar ao SENHOR, nosso Deus, para que ele nos salve dos filisteus!", imploraram a Samuel.

[[v9-7-9]]

^<<v9-7-9,9>>^ Então Samuel escolheu um cordeiro que ainda mamava e o ofereceu ao SENHOR como holocausto. Suplicou ao SENHOR em favor de Israel, e o SENHOR o atendeu.

[[v9-7-10]]

^<<v9-7-10,10>>^ Enquanto Samuel oferecia o holocausto, os filisteus chegaram para atacar Israel. Naquele dia, porém, o SENHOR falou do céu com voz poderosa de trovão, provocando pânico entre os filisteus, e eles foram derrotados diante dos israelitas.

[[v9-7-11]]

^<<v9-7-11,11>>^ Os soldados de Israel os perseguiram desde Mispá até um lugar abaixo de Bete-Car, matando-os ao longo do caminho.

[[v9-7-12]]

^<<v9-7-12,12>>^ Então Samuel pegou uma pedra grande e a colocou entre as cidades de Mispá e Jesana. Deu à pedra o nome de Ebenézer, pois disse: "Até aqui o SENHOR nos ajudou!".

[[v9-7-13]]

^<<v9-7-13,13>>^ Assim, os filisteus foram derrotados e não voltaram a invadir Israel por algum tempo. Durante toda a vida de Samuel, a mão do SENHOR esteve contra os filisteus.

[[v9-7-14]]

^<<v9-7-14,14>>^ As cidades israelitas que os filisteus tinham conquistado entre Ecrom e Gate foram devolvidas a Israel, junto com o restante do território que os filisteus haviam tomado. E houve paz entre Israel e os amorreus naqueles dias.

[[v9-7-15]]

^<<v9-7-15,15>>^ Samuel continuou como juiz em Israel pelo resto de sua vida.

[[v9-7-16]]

^<<v9-7-16,16>>^ A cada ano, viajava pelo território e julgava o povo de Israel em três locais: primeiro em Betel, depois em Gilgal e, por fim, em Mispá.

[[v9-7-17]]

^<<v9-7-17,17>>^ Então voltava para sua casa em Ramá, de onde liderava Israel como juiz. Ali Samuel construiu um altar ao SENHOR.

'''

xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[&#60; Capítulo Anterior] | <<v9-7-0,Topo>> | xref:009-1-samuel/009-1-samuel-008.adoc#v9-8-0[Próximo Capítulo &#62;]