include::./index.adoc[]

[[v9-8-0]]
=== 1 Samuel, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v9-8-1]]

^<<v9-8-1,1>>^ Quando Samuel ficou idoso, nomeou seus filhos para serem juízes sobre Israel.

[[v9-8-2]]

^<<v9-8-2,2>>^ Joel, seu filho mais velho, e Abias, o segundo mais velho, julgavam em Berseba,

[[v9-8-3]]

^<<v9-8-3,3>>^ mas não eram como seu pai. Eram gananciosos, aceitavam subornos e pervertiam a justiça.

[[v9-8-4]]

^<<v9-8-4,4>>^ Por fim, as autoridades de Israel se reuniram em Ramá para discutir essa questão com Samuel.

[[v9-8-5]]

^<<v9-8-5,5>>^ Eles disseram: "Olhe, o senhor está idoso e seus filhos não seguem seu exemplo. Escolha um rei para nos julgar, como ocorre com todas as outras nações".

[[v9-8-6]]

^<<v9-8-6,6>>^ Samuel não gostou de que lhe tivessem pedido um rei e buscou a orientação do SENHOR.

[[v9-8-7]]

^<<v9-8-7,7>>^ O SENHOR lhe respondeu: "Faça tudo que eles pedem, pois é a mim que rejeitam, e não a você. Eles me rejeitaram como seu rei.

[[v9-8-8]]

^<<v9-8-8,8>>^ Desde que os tirei do Egito até hoje, eles têm me abandonado e seguido outros deuses. Agora, tratam você da mesma forma.

[[v9-8-9]]

^<<v9-8-9,9>>^ Faça o que eles pedem, mas advirta-os solenemente a respeito de como o rei os governará".

[[v9-8-10]]

^<<v9-8-10,10>>^ Então Samuel transmitiu a advertência do SENHOR ao povo que lhe pedia um rei.

[[v9-8-11]]

^<<v9-8-11,11>>^ Disse ele: "Este é o modo como o rei governará sobre vocês. Ele convocará seus filhos para servi-lo em seus carros de guerra e como seus cavaleiros e os fará correr à frente dos carros dele.

[[v9-8-12]]

^<<v9-8-12,12>>^ Colocará alguns como generais e capitães de seu exército, obrigará outros a arar seus campos e a fazer as colheitas e forçará outros mais a fabricar armas e equipamentos para os carros de guerra.

[[v9-8-13]]

^<<v9-8-13,13>>^ Tomará suas filhas e as obrigará a cozinhar, assar pães e fazer perfumes para ele.

[[v9-8-14]]

^<<v9-8-14,14>>^ Tomará de vocês o melhor de seus campos, vinhedos e olivais e os dará aos servos dele.

[[v9-8-15]]

^<<v9-8-15,15>>^ Tomará um décimo de sua colheita de cereais e uvas para distribuir entre seus oficiais e servos.

[[v9-8-16]]

^<<v9-8-16,16>>^ Tomará seus escravos e escravas e o melhor do gado e dos jumentos para uso próprio.

[[v9-8-17]]

^<<v9-8-17,17>>^ Exigirá um décimo de seus rebanhos, e vocês se tornarão escravos dele.

[[v9-8-18]]

^<<v9-8-18,18>>^ Quando esse dia chegar, lamentarão por causa desse rei que agora pedem, mas o SENHOR não lhes dará ouvidos".

[[v9-8-19]]

^<<v9-8-19,19>>^ Mas o povo se recusou a ouvir a advertência de Samuel. "Mesmo assim, queremos um rei", disseram.

[[v9-8-20]]

^<<v9-8-20,20>>^ "Queremos ser como todas as nações ao nosso redor. Nosso rei nos julgará e nos conduzirá nas batalhas."

[[v9-8-21]]

^<<v9-8-21,21>>^ Samuel repetiu para o SENHOR aquilo que o povo tinha dito,

[[v9-8-22]]

^<<v9-8-22,22>>^ e o SENHOR lhe respondeu: "Faça o que eles pedem e dê-lhes um rei". Então Samuel ordenou aos israelitas que voltassem cada um para sua cidade.

'''

xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[&#60; Capítulo Anterior] | <<v9-8-0,Topo>> | xref:009-1-samuel/009-1-samuel-009.adoc#v9-9-0[Próximo Capítulo &#62;]