include::./index.adoc[]

[[v9-11-0]]
=== 1 Samuel, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v9-11-1]]

^<<v9-11-1,1>>^ Cerca de um mês depois, Naás, rei de Amom, avançou com seu exército contra a cidade de Jabes-Gileade. Mas os habitantes de Jabes clamaram: "Faça um tratado conosco, e o serviremos!".

[[v9-11-2]]

^<<v9-11-2,2>>^ Então Naás disse: "Está bem, mas só com uma condição. Arrancarei o olho direito de cada um de vocês como humilhação para todo o Israel!".

[[v9-11-3]]

^<<v9-11-3,3>>^ As autoridades de Jabes pediram: "Dê-nos sete dias para que enviemos mensageiros a todo o Israel. Se ninguém vier nos salvar, nós nos entregaremos ao rei".

[[v9-11-4]]

^<<v9-11-4,4>>^ Os mensageiros chegaram a Gibeá, cidade onde Saul morava, e relataram ao povo a difícil situação em Jabes-Gileade. Todos choraram em alta voz.

[[v9-11-5]]

^<<v9-11-5,5>>^ Quando Saul voltou à cidade, trazendo seus bois do campo, perguntou: "O que está acontecendo? Por que todos estão chorando?". Então contaram-lhe sobre a mensagem de Jabes.

[[v9-11-6]]

^<<v9-11-6,6>>^ O Espírito de Deus veio poderosamente sobre Saul, e ele se enfureceu.

[[v9-11-7]]

^<<v9-11-7,7>>^ Pegou dois bois, cortou-os em pedaços e enviou mensageiros para levá-los a todo o Israel com o seguinte aviso: "Isto é o que acontecerá aos bois de quem se recusar a seguir Saul e Samuel na batalha!". E o terror do SENHOR caiu sobre o povo, de modo que todos saíram para guerrear como um só homem.

[[v9-11-8]]

^<<v9-11-8,8>>^ Quando Saul os reuniu em Bezeque, viu que havia trezentos mil homens de Israel e trinta mil homens de Judá.

[[v9-11-9]]

^<<v9-11-9,9>>^ Então Saul enviou os mensageiros de volta a Jabes-Gileade com o seguinte aviso: "Salvaremos vocês amanhã, antes do meio-dia". Quando os habitantes de Jabes receberam a mensagem, houve grande alegria em toda a cidade.

[[v9-11-10]]

^<<v9-11-10,10>>^ Então os homens de Jabes disseram a seus inimigos: "Amanhã nos entregaremos a vocês, e poderão fazer conosco o que desejarem".

[[v9-11-11]]

^<<v9-11-11,11>>^ No dia seguinte, porém, antes do amanhecer, Saul chegou com seu exército dividido em três destacamentos. Atacou os amonitas de surpresa e, na hora mais quente do dia, já os tinha derrotado completamente. O restante do exército amonita se dispersou de tal modo que não ficaram dois soldados juntos.

[[v9-11-12]]

^<<v9-11-12,12>>^ Então o povo disse a Samuel: "Onde estão aqueles que perguntaram: ‘Por que Saul deveria nos governar?’ Tragam esses homens aqui, e os mataremos".

[[v9-11-13]]

^<<v9-11-13,13>>^ Saul, porém, respondeu: "Ninguém será morto hoje, pois neste dia o SENHOR livrou Israel".

[[v9-11-14]]

^<<v9-11-14,14>>^ Então Samuel disse ao povo: "Venham, vamos todos a Gilgal renovar o compromisso do reino".

[[v9-11-15]]

^<<v9-11-15,15>>^ Então todos foram a Gilgal e, numa cerimônia solene diante do SENHOR, proclamaram Saul como rei. Depois, trouxeram ao SENHOR ofertas de paz, e Saul e todos os israelitas muito se alegraram.

'''

xref:009-1-samuel/009-1-samuel-010.adoc#v9-10-0[&#60; Capítulo Anterior] | <<v9-11-0,Topo>> | xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[Próximo Capítulo &#62;]