include::./index.adoc[]

[[v9-31-0]]
=== 1 Samuel, 31
// nvt ?, NVT - Nova Versão Transformadora

[[v9-31-1]]

^<<v9-31-1,1>>^ Enquanto isso, os filisteus atacaram Israel, e os israelitas fugiram deles. Muitos foram mortos nas encostas do monte Gilboa.

[[v9-31-2]]

^<<v9-31-2,2>>^ Os filisteus cercaram Saul e seus filhos e mataram três deles: Jônatas, Abinadabe e Malquisua.

[[v9-31-3]]

^<<v9-31-3,3>>^ O combate se tornou cada vez mais intenso em volta de Saul, e os arqueiros filisteus o alcançaram e o feriram gravemente.

[[v9-31-4]]

^<<v9-31-4,4>>^ Saul disse a seu escudeiro: "Pegue sua espada e mate-me antes que esses filisteus incircuncisos venham, me torturem e zombem de mim". Mas o escudeiro teve medo e não quis matá-lo. Então Saul pegou sua própria espada e se lançou sobre ela.

[[v9-31-5]]

^<<v9-31-5,5>>^ Quando viu que Saul estava morto, o escudeiro se lançou sobre sua espada e morreu ao lado do rei.

[[v9-31-6]]

^<<v9-31-6,6>>^ Foi assim que Saul e seus três filhos, seu escudeiro e seus soldados morreram juntos naquele mesmo dia.

[[v9-31-7]]

^<<v9-31-7,7>>^ Quando os israelitas do outro lado do vale de Jezreel e além do Jordão souberam que o exército israelita havia fugido e que Saul e seus filhos estavam mortos, abandonaram suas cidades e fugiram. Então os filisteus vieram e ocuparam essas cidades.

[[v9-31-8]]

^<<v9-31-8,8>>^ No dia seguinte, quando os filisteus foram saquear os mortos, encontraram os corpos de Saul e seus três filhos no monte Gilboa.

[[v9-31-9]]

^<<v9-31-9,9>>^ Cortaram a cabeça de Saul e removeram sua armadura. Então anunciaram o ocorrido no templo de seus ídolos e ao povo de toda a terra da Filístia.

[[v9-31-10]]

^<<v9-31-10,10>>^ Colocaram a armadura de Saul no templo de Astarote e penduraram o corpo no muro da cidade de Bete-Seã.

[[v9-31-11]]

^<<v9-31-11,11>>^ Quando os habitantes de Jabes-Gileade souberam o que os filisteus haviam feito a Saul,

[[v9-31-12]]

^<<v9-31-12,12>>^ todos os seus guerreiros mais valentes viajaram a noite toda para Bete-Seã e baixaram do muro os corpos de Saul e seus filhos. Levaram os corpos para Jabes, onde os queimaram.

[[v9-31-13]]

^<<v9-31-13,13>>^ Depois, enterraram os ossos debaixo de uma tamargueira em Jabes e jejuaram durante sete dias.

'''

xref:009-1-samuel/009-1-samuel-030.adoc#v9-30-0[&#60; Capítulo Anterior] | <<v9-31-0,Topo>> | xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[Próximo Capítulo &#62;]