include::./index.adoc[]

[[v9-5-0]]
=== 1 Samuel, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v9-5-1]]

^<<v9-5-1,1>>^ Depois que tomaram a arca de Deus, os filisteus a levaram do campo de batalha em Ebenézer para a cidade de Asdode.

[[v9-5-2]]

^<<v9-5-2,2>>^ Levaram a arca de Deus para o templo de Dagom e a colocaram ao lado de uma estátua de Dagom.

[[v9-5-3]]

^<<v9-5-3,3>>^ Contudo, na manhã seguinte, quando os moradores de Asdode se levantaram, viram que Dagom estava caído com o rosto em terra diante da arca do SENHOR. Então levantaram Dagom e o puseram de volta em seu lugar.

[[v9-5-4]]

^<<v9-5-4,4>>^ Na manhã do outro dia, porém, viram que tinha acontecido a mesma coisa: Dagom estava caído novamente com o rosto em terra diante da arca do SENHOR. Dessa vez, a cabeça e as mãos de Dagom tinham se quebrado e estavam junto à porta de entrada. Somente o corpo permaneceu intacto.

[[v9-5-5]]

^<<v9-5-5,5>>^ Por isso, até hoje os sacerdotes de Dagom e aqueles que entram em seu templo, em Asdode, não pisam na soleira da porta.

[[v9-5-6]]

^<<v9-5-6,6>>^ Então a mão do SENHOR pesou sobre os moradores de Asdode e dos povoados vizinhos e os feriu com uma praga de tumores.

[[v9-5-7]]

^<<v9-5-7,7>>^ Quando o povo de Asdode viu o que estava acontecendo, exclamou: "Não podemos mais ficar com a arca do Deus de Israel! A mão dele pesou sobre nós e sobre Dagom, nosso deus!".

[[v9-5-8]]

^<<v9-5-8,8>>^ Então reuniram os governantes das cidades dos filisteus e lhes perguntaram: "O que devemos fazer com a arca do Deus de Israel?". Os governantes responderam: "Levem a arca para a cidade de Gate". Então levaram a arca do Deus de Israel para Gate.

[[v9-5-9]]

^<<v9-5-9,9>>^ Mas, quando a arca chegou a Gate, a mão do SENHOR pesou sobre a cidade, ferindo com uma praga de tumores os homens de lá, tanto os jovens como os velhos, e houve grande pânico.

[[v9-5-10]]

^<<v9-5-10,10>>^ Por isso, enviaram a arca de Deus para a cidade de Ecrom, mas quando os habitantes dali viram que ela entrava na cidade, exclamaram: "Por que estão trazendo a arca do Deus de Israel para cá? Querem matar todo o nosso povo?".

[[v9-5-11]]

^<<v9-5-11,11>>^ Reuniram mais uma vez os governantes filisteus e suplicaram: "Mandem a arca do Deus de Israel de volta para sua própria terra, para que não mate todo o nosso povo!". Pois a mão de Deus já pesava sobre a cidade, e um pavor mortal se espalhava por todo o lugar.

[[v9-5-12]]

^<<v9-5-12,12>>^ Os que não morreram foram afligidos com tumores, e o clamor da cidade subiu até o céu.

'''

xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[&#60; Capítulo Anterior] | <<v9-5-0,Topo>> | xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[Próximo Capítulo &#62;]