include::./index.adoc[]

[[v9-25-0]]
=== 1 Samuel, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v9-25-1]]

^<<v9-25-1,1>>^ Samuel morreu, e todo o Israel se reuniu para lamentar sua morte. Foi sepultado em Ramá, onde tinha vivido. Então Davi desceu para o deserto de Maom.

[[v9-25-2]]

^<<v9-25-2,2>>^ Havia um homem rico em Maom, que tinha propriedades perto da região do Carmelo. Possuía três mil ovelhas e mil cabras, e era época da tosquia das ovelhas.

[[v9-25-3]]

^<<v9-25-3,3>>^ O homem se chamava Nabal; sua esposa, Abigail, era uma mulher inteligente e bonita. Mas Nabal, descendente de Calebe, era um homem rude e perverso em tudo que fazia.

[[v9-25-4]]

^<<v9-25-4,4>>^ Quando Davi soube que Nabal estava tosquiando as ovelhas,

[[v9-25-5]]

^<<v9-25-5,5>>^ chamou dez rapazes e lhes disse: "Subam ao Carmelo e vão a Nabal; enviem saudações em meu nome.

[[v9-25-6]]

^<<v9-25-6,6>>^ E digam a ele: ‘Paz e prosperidade ao senhor e à sua família, e a tudo que é seu.

[[v9-25-7]]

^<<v9-25-7,7>>^ Disseram-me que é época da tosquia. Enquanto seus pastores estiveram entre nós perto do Carmelo, nunca lhes fizemos mal, e nada foi roubado deles.

[[v9-25-8]]

^<<v9-25-8,8>>^ Pergunte a seus homens, e eles lhe dirão que isso é verdade. Diante disso, pedimos que o senhor seja bondoso conosco, pois chegamos numa época de celebração. Por favor, reparta conosco e com seu amigo Davi o que puder dos seus mantimentos’".

[[v9-25-9]]

^<<v9-25-9,9>>^ Os rapazes transmitiram essa mensagem a Nabal em nome de Davi e esperaram pela resposta.

[[v9-25-10]]

^<<v9-25-10,10>>^ "Quem é esse tal de Davi?", perguntou-lhes Nabal. "Quem esse filho de Jessé pensa que é? Hoje em dia, há muitos servos que fogem de seus senhores.

[[v9-25-11]]

^<<v9-25-11,11>>^ Devo pegar meu pão, minha água e a carne dos animais que abati para meus tosquiadores e entregar a um bando que vem não se sabe de onde?"

[[v9-25-12]]

^<<v9-25-12,12>>^ Então os rapazes enviados por Davi voltaram e lhe contaram tudo que Nabal tinha dito.

[[v9-25-13]]

^<<v9-25-13,13>>^ "Peguem suas espadas!", disse Davi, e pôs sua espada à cintura, e seus homens fizeram a mesma coisa. Quatrocentos deles partiram com Davi, enquanto duzentos ficaram para guardar a bagagem.

[[v9-25-14]]

^<<v9-25-14,14>>^ Enquanto isso, um dos servos de Nabal foi até Abigail e lhe disse: "Davi enviou mensageiros do deserto para saudar nosso senhor, mas ele lhes respondeu com insultos.

[[v9-25-15]]

^<<v9-25-15,15>>^ Os homens de Davi foram muito bons conosco e nunca nos fizeram mal. Nada foi roubado de nós durante o tempo em que estiveram conosco no campo.

[[v9-25-16]]

^<<v9-25-16,16>>^ Na verdade, dia e noite eles foram como um muro de proteção para nós e para as ovelhas.

[[v9-25-17]]

^<<v9-25-17,17>>^ É bom que a senhora leve esses fatos em consideração e resolva o que fazer, pois haverá problemas para nosso senhor e para toda a sua família. Nabal é um homem tão cruel que ninguém consegue conversar com ele!".

[[v9-25-18]]

^<<v9-25-18,18>>^ Sem perder tempo, Abigail providenciou duzentos pães, duas vasilhas de couro cheias de vinho, cinco ovelhas preparadas, cinco cestos de grãos tostados, cem bolos de passas e duzentos bolos de figo. Colocou tudo em jumentos

[[v9-25-19]]

^<<v9-25-19,19>>^ e disse aos servos: "Vão adiante, e logo os seguirei". Mas não contou a seu marido, Nabal, o que estava fazendo.

[[v9-25-20]]

^<<v9-25-20,20>>^ Quando Abigail entrava num desfiladeiro montada em seu jumento, avistou Davi e seus homens vindo em sua direção.

[[v9-25-21]]

^<<v9-25-21,21>>^ Davi tinha acabado de dizer: "De nada adiantou ajudarmos esse sujeito. Protegemos seus rebanhos no deserto, e nenhum de seus bens se perdeu ou foi roubado. Mas ele me pagou o bem com o mal.

[[v9-25-22]]

^<<v9-25-22,22>>^ Que Deus me castigue severamente se eu deixar um homem ou menino vivo na casa de Nabal até amanhã de manhã!".

[[v9-25-23]]

^<<v9-25-23,23>>^ Quando Abigail viu Davi, desceu depressa do jumento e se curvou diante de Davi com o rosto em terra.

[[v9-25-24]]

^<<v9-25-24,24>>^ Caiu a seus pés e disse: "A culpa é toda minha, meu senhor! Por favor, ouça o que sua serva tem a dizer.

[[v9-25-25]]

^<<v9-25-25,25>>^ Nabal é um homem perverso; não dê atenção ao que ele disse. Ele é um insensato, como seu nome indica. Mas eu nem sequer vi os rapazes que o senhor enviou.

[[v9-25-26]]

^<<v9-25-26,26>>^ "Agora, meu senhor, tenha certeza de que, tão certo como vive o SENHOR, e tão certo como a sua própria vida, foi o SENHOR que o impediu de matar e se vingar com as próprias mãos! Que todos os seus inimigos e os que procuram matá-lo acabem como Nabal!

[[v9-25-27]]

^<<v9-25-27,27>>^ Aqui está um presente que sua serva trouxe para o senhor e seus companheiros.

[[v9-25-28]]

^<<v9-25-28,28>>^ Por favor, perdoe-me se o ofendi de algum modo. Que o SENHOR lhe conceda uma dinastia duradoura, pois está lutando as batalhas do SENHOR. Que ele o livre de fazer o mal durante toda a sua vida!

[[v9-25-29]]

^<<v9-25-29,29>>^ "Mesmo quando for perseguido por aqueles que procuram matá-lo, sua vida estará segura sob o cuidado do SENHOR, seu Deus, protegida como um tesouro. Mas a vida de seus inimigos desaparecerá como pedras atiradas de uma funda!

[[v9-25-30]]

^<<v9-25-30,30>>^ Quando o SENHOR tiver feito tudo que prometeu e o tiver colocado como líder de Israel,

[[v9-25-31]]

^<<v9-25-31,31>>^ não haverá em sua consciência a tristeza e o peso de ter derramado sangue e se vingado sem necessidade. E, quando o SENHOR tiver feito grandes coisas em seu favor, lembre-se de sua serva!".

[[v9-25-32]]

^<<v9-25-32,32>>^ Davi respondeu a Abigail: "Louvado seja o SENHOR, Deus de Israel, que hoje a enviou ao meu encontro!

[[v9-25-33]]

^<<v9-25-33,33>>^ Graças a Deus por seu bom senso! Que você seja abençoada por me impedir de matar e me vingar com minhas próprias mãos.

[[v9-25-34]]

^<<v9-25-34,34>>^ Pois, tão certo como vive o SENHOR, o Deus de Israel, que me impediu de lhe fazer mal, se você não tivesse vindo depressa ao meu encontro, amanhã pela manhã não haveria nenhum homem ou menino vivo na casa de Nabal".

[[v9-25-35]]

^<<v9-25-35,35>>^ Então Davi aceitou o presente de Abigail e lhe disse: "Volte para casa em paz. Ouvi o que você disse e farei o que me pediu".

[[v9-25-36]]

^<<v9-25-36,36>>^ Quando Abigail chegou em casa, viu que Nabal estava oferecendo um banquete digno de rei. Ele se divertia e já estava muito bêbado, de modo que ela só lhe contou sobre o encontro com Davi na manhã seguinte.

[[v9-25-37]]

^<<v9-25-37,37>>^ Pela manhã, quando Nabal estava sóbrio, sua esposa lhe contou o que havia acontecido. Como consequência, ele teve um mal súbito e ficou completamente paralisado.

[[v9-25-38]]

^<<v9-25-38,38>>^ Passados cerca de dez dias, o SENHOR o feriu, e ele morreu.

[[v9-25-39]]

^<<v9-25-39,39>>^ Quando Davi soube que Nabal estava morto, disse: "Louvado seja o SENHOR, que vingou o insulto que recebi de Nabal e me impediu de fazer o mal. O SENHOR retribuiu a Nabal o castigo por seu pecado". Então Davi enviou mensageiros a Abigail para pedir que se tornasse sua esposa.

[[v9-25-40]]

^<<v9-25-40,40>>^ Quando os mensageiros chegaram ao Carmelo, disseram a Abigail: "Davi mandou buscá-la para que se case com ele".

[[v9-25-41]]

^<<v9-25-41,41>>^ Ela se curvou com o rosto em terra e respondeu: "Eu, sua serva, ficarei contente em me casar com Davi e, como uma serva, lavar os pés de seus servos!".

[[v9-25-42]]

^<<v9-25-42,42>>^ Sem demora, Abigail montou num jumento e, levando consigo cinco moças que a serviam, voltou com os mensageiros de Davi. E assim se tornou esposa dele.

[[v9-25-43]]

^<<v9-25-43,43>>^ Davi também se casou com Ainoã, de Jezreel, e ambas foram suas esposas.

[[v9-25-44]]

^<<v9-25-44,44>>^ Nesse meio-tempo, Saul tinha dado sua filha Mical, esposa de Davi, a um homem de Galim chamado Palti, filho de Laís.

'''

xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[&#60; Capítulo Anterior] | <<v9-25-0,Topo>> | xref:009-1-samuel/009-1-samuel-026.adoc#v9-26-0[Próximo Capítulo &#62;]