include::./index.adoc[]

[[v8-2-0]]
=== Rute, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v8-2-1]]

^<<v8-2-1,1>>^ Havia em Belém um homem rico e respeitado chamado Boaz. Ele era parente de Elimeleque, o marido de Noemi.

[[v8-2-2]]

^<<v8-2-2,2>>^ Certo dia, Rute, a moabita, disse a Noemi: "Deixe-me ir ao campo ver se alguém, em sua bondade, me permite recolher as espigas de cereal que sobrarem". Noemi respondeu: "Está bem, minha filha, pode ir".

[[v8-2-3]]

^<<v8-2-3,3>>^ Rute saiu para colher espigas após os ceifeiros. Aconteceu de ela ir trabalhar num campo que pertencia a Boaz, parente de seu sogro, Elimeleque.

[[v8-2-4]]

^<<v8-2-4,4>>^ Enquanto Rute estava ali, Boaz chegou de Belém e saudou os ceifeiros: "O SENHOR esteja com vocês!". "O SENHOR o abençoe!", responderam os ceifeiros.

[[v8-2-5]]

^<<v8-2-5,5>>^ Então Boaz perguntou a seu capataz: "Quem é aquela moça? A quem ela pertence?".

[[v8-2-6]]

^<<v8-2-6,6>>^ O capataz respondeu: "É a moça que veio de Moabe com Noemi.

[[v8-2-7]]

^<<v8-2-7,7>>^ Hoje de manhã ela me pediu permissão para colher espigas após os ceifeiros. Desde que chegou, não parou de trabalhar um instante sequer, a não ser por alguns minutos de descanso no abrigo".

[[v8-2-8]]

^<<v8-2-8,8>>^ Boaz foi até Rute e disse: "Ouça, minha filha. Quando for colher espigas, fique conosco; não vá a nenhum outro campo. Acompanhe as moças que trabalham para mim.

[[v8-2-9]]

^<<v8-2-9,9>>^ Observe em que parte do campo estão colhendo e vá atrás delas. Avisei os homens para não a tratarem mal. E, quando tiver sede, sirva-se da água que os servos tiram do poço".

[[v8-2-10]]

^<<v8-2-10,10>>^ Rute se curvou diante dele, com o rosto no chão, e disse: "O que fiz para merecer tanta bondade? Sou apenas uma estrangeira!".

[[v8-2-11]]

^<<v8-2-11,11>>^ "Eu sei", respondeu Boaz. "Mas também sei de tudo que você fez por sua sogra desde a morte de seu marido. Ouvi falar de como você deixou seu pai, sua mãe e sua própria terra para viver aqui no meio de desconhecidos.

[[v8-2-12]]

^<<v8-2-12,12>>^ Que o SENHOR, o Deus de Israel, sob cujas asas você veio se refugiar, a recompense ricamente pelo que você fez."

[[v8-2-13]]

^<<v8-2-13,13>>^ Ela respondeu: "Espero que eu continue a receber sua bondade, meu senhor, pois me animou com suas palavras gentis, embora eu nem seja uma de suas servas".

[[v8-2-14]]

^<<v8-2-14,14>>^ Na hora da refeição, Boaz lhe disse: "Venha cá e sirva-se de comida; também pode molhar o pão no vinagre". Rute sentou-se junto aos ceifeiros, e Boaz lhe deu grãos tostados. Ela comeu até ficar satisfeita, e ainda sobrou alimento.

[[v8-2-15]]

^<<v8-2-15,15>>^ Quando Rute voltou ao trabalho, Boaz ordenou a seus servos: "Permitam que ela colha espigas entre os feixes e não a incomodem.

[[v8-2-16]]

^<<v8-2-16,16>>^ Tirem dos feixes algumas espigas de cevada e deixem-nas cair para que ela as recolha. Não a atrapalhem!".

[[v8-2-17]]

^<<v8-2-17,17>>^ Assim, Rute colheu cevada o dia todo e, à tarde, quando debulhou o cereal, encheu quase um cesto inteiro.

[[v8-2-18]]

^<<v8-2-18,18>>^ Carregou tudo para a cidade e mostrou à sua sogra. Também lhe deu o que havia sobrado da refeição.

[[v8-2-19]]

^<<v8-2-19,19>>^ "Onde você colheu todo esse cereal?", perguntou Noemi. "Onde você trabalhou hoje? Que seja abençoado quem a ajudou!" Então Rute contou à sogra com quem havia trabalhado: "O homem com quem trabalhei hoje se chama Boaz".

[[v8-2-20]]

^<<v8-2-20,20>>^ "O SENHOR o abençoe!", disse Noemi à nora. "O SENHOR não deixou de lado sua bondade tanto pelos vivos como pelos mortos. Esse homem é um de nossos parentes mais próximos, o resgatador de nossa família."

[[v8-2-21]]

^<<v8-2-21,21>>^ Rute, a moabita, acrescentou: "Boaz disse que devo voltar e trabalhar com seus ceifeiros até que terminem toda a colheita".

[[v8-2-22]]

^<<v8-2-22,22>>^ "Muito bom!", exclamou Noemi. "Faça o que ele disse, minha filha. Fique com as servas dele até o final da colheita. Em outros campos, poderiam maltratá-la."

[[v8-2-23]]

^<<v8-2-23,23>>^ Assim, Rute trabalhou com as servas nos campos de Boaz e recolheu espigas com elas até o final das colheitas da cevada e do trigo. Nesse tempo, ficou morando com sua sogra.

'''

xref:008-rute/008-rute-001.adoc#v8-1-0[&#60; Capítulo Anterior] | <<v8-2-0,Topo>> | xref:008-rute/008-rute-003.adoc#v8-3-0[Próximo Capítulo &#62;]