include::./index.adoc[]

[[v8-3-0]]
=== Rute, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v8-3-1]]

^<<v8-3-1,1>>^ Certo dia, Noemi disse a Rute: "Minha filha, é hora de eu encontrar para você um lar seguro e feliz.

[[v8-3-2]]

^<<v8-3-2,2>>^ Esse Boaz, senhor das moças com quem você trabalhou, é nosso parente próximo. Hoje à noite, ele estará na eira, onde se debulha a cevada.

[[v8-3-3]]

^<<v8-3-3,3>>^ Faça o que lhe direi: tome banho, perfume-se e vista sua melhor roupa. Depois vá até lá, mas não deixe que Boaz a veja enquanto ele não tiver terminado de comer e beber.

[[v8-3-4]]

^<<v8-3-4,4>>^ Repare bem no lugar onde ele se deitar. Então vá, descubra os pés dele e deite-se ali. Ele lhe dirá o que fazer".

[[v8-3-5]]

^<<v8-3-5,5>>^ "Farei tudo que você disse", respondeu Rute.

[[v8-3-6]]

^<<v8-3-6,6>>^ Assim, naquela noite, ela desceu até a eira e seguiu as instruções de sua sogra.

[[v8-3-7]]

^<<v8-3-7,7>>^ Quando Boaz terminou de comer e beber e estava alegre, foi deitar-se perto de um monte de grãos e pegou no sono. Rute se aproximou em silêncio, descobriu os pés dele e se deitou.

[[v8-3-8]]

^<<v8-3-8,8>>^ Por volta da meia-noite, Boaz acordou de repente. Ele se virou e ficou admirado de encontrar uma mulher deitada a seus pés.

[[v8-3-9]]

^<<v8-3-9,9>>^ "Quem é você?", perguntou ele. "Sou sua serva Rute", respondeu ela. "Estenda as abas de sua capa sobre mim, pois o senhor é o resgatador de minha família."

[[v8-3-10]]

^<<v8-3-10,10>>^ Então Boaz exclamou: "O SENHOR a abençoe, minha filha! Você demonstra agora ainda mais lealdade por sua família que antes, pois não foi atrás de um homem mais jovem, seja rico ou pobre.

[[v8-3-11]]

^<<v8-3-11,11>>^ Não se preocupe com nada, minha filha. Farei o que me pediu, pois toda a cidade sabe que você é uma mulher virtuosa.

[[v8-3-12]]

^<<v8-3-12,12>>^ Mas, embora eu seja de fato um dos resgatadores de sua família, há outro homem que é parente mais próximo que eu.

[[v8-3-13]]

^<<v8-3-13,13>>^ Fique aqui esta noite e pela manhã conversarei com ele. Se ele estiver disposto a resgatá-la, muito bem; que ele se case com você. Se não quiser, tão certo como vive o SENHOR, eu mesmo a resgatarei".

[[v8-3-14]]

^<<v8-3-14,14>>^ Rute ficou deitada aos pés de Boaz até de manhã, mas levantou-se antes de raiar o dia, pois Boaz tinha dito: "Ninguém deve saber que uma mulher esteve na eira".

[[v8-3-15]]

^<<v8-3-15,15>>^ Então Boaz lhe disse: "Traga-me sua capa e estenda-a aqui". Ele despejou sobre a capa seis medidas de cevada e a pôs sobre as costas de Rute. Depois ele retornou à cidade.

[[v8-3-16]]

^<<v8-3-16,16>>^ Quando Rute voltou à sua sogra, ela lhe perguntou: "Como foi, minha filha?". Rute contou a Noemi tudo que Boaz havia feito

[[v8-3-17]]

^<<v8-3-17,17>>^ e acrescentou: "Ele me deu estas seis medidas de cevada e disse: ‘Não volte para sua sogra de mãos vazias’".

[[v8-3-18]]

^<<v8-3-18,18>>^ Então Noemi disse: "Tenha paciência, minha filha, até sabermos o que vai acontecer. Boaz não descansará enquanto não resolver esta questão ainda hoje".

'''

xref:008-rute/008-rute-002.adoc#v8-2-0[&#60; Capítulo Anterior] | <<v8-3-0,Topo>> | xref:008-rute/008-rute-004.adoc#v8-4-0[Próximo Capítulo &#62;]