include::./index.adoc[]

[[v12-21-0]]
=== 2 Reis, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v12-21-1]]

^<<v12-21-1,1>>^ Manassés tinha 12 anos quando começou a reinar, e reinou em Jerusalém por 55 anos. Sua mãe se chamava Hefzibá.

[[v12-21-2]]

^<<v12-21-2,2>>^ Manassés fez o que era mau aos olhos do SENHOR e seguiu as práticas detestáveis das nações que o SENHOR havia expulsado de diante dos israelitas.

[[v12-21-3]]

^<<v12-21-3,3>>^ Reconstruiu os santuários idólatras que seu pai, Ezequias, havia destruído. Construiu altares para Baal e ergueu um poste de Aserá, como Acabe, rei de Israel, havia feito. Também se curvou diante de todos os astros dos céus e lhes prestou culto.

[[v12-21-4]]

^<<v12-21-4,4>>^ Construiu altares idólatras no templo do SENHOR, sobre o qual o SENHOR tinha dito: "Meu nome permanecerá em Jerusalém para sempre".

[[v12-21-5]]

^<<v12-21-5,5>>^ Nos dois pátios do templo do SENHOR, construiu altares para os astros do céu.

[[v12-21-6]]

^<<v12-21-6,6>>^ Manassés também sacrificou seu filho no fogo. Praticou feitiçaria e adivinhação e consultou médiuns e praticantes do ocultismo. Fez muitas coisas perversas aos olhos do SENHOR e, com isso, provocou sua ira.

[[v12-21-7]]

^<<v12-21-7,7>>^ Manassés chegou a fazer uma imagem esculpida da deusa Aserá e colocá-la no templo, sobre o qual o SENHOR tinha dito a Davi e a seu filho Salomão: "Meu nome será honrado para sempre neste templo em Jerusalém, a cidade que escolhi dentre todas as tribos de Israel.

[[v12-21-8]]

^<<v12-21-8,8>>^ Se os israelitas tiverem o cuidado de obedecer a meus mandamentos, todas as leis que meu servo Moisés lhes deu, não os expulsarei desta terra que dei a seus antepassados".

[[v12-21-9]]

^<<v12-21-9,9>>^ Mas o povo se recusou a ouvir, e Manassés os levou a fazer coisas piores do que as nações que o SENHOR tinha destruído quando os israelitas entraram na terra.

[[v12-21-10]]

^<<v12-21-10,10>>^ Então o SENHOR disse por meio de seus servos, os profetas:

[[v12-21-11]]

^<<v12-21-11,11>>^ "Manassés, rei de Judá, fez muitas coisas detestáveis. É ainda mais perverso que os amorreus que habitavam nesta terra antes de Israel e fez o povo de Judá pecar com seus ídolos.

[[v12-21-12]]

^<<v12-21-12,12>>^ Portanto, assim diz o SENHOR, o Deus de Israel: Trarei desgraça tão grande sobre Jerusalém e Judá que fará tinir os ouvidos daqueles que ouvirem a respeito.

[[v12-21-13]]

^<<v12-21-13,13>>^ Julgarei Jerusalém de acordo com o mesmo critério que usei para julgar Samaria e a família de Acabe. Limparei Jerusalém como quem limpa um prato e depois o vira de cabeça para baixo.

[[v12-21-14]]

^<<v12-21-14,14>>^ Rejeitarei até mesmo o remanescente de meu povo e o entregarei a seus inimigos como despojo.

[[v12-21-15]]

^<<v12-21-15,15>>^ Pois eles fizeram o que era mau aos meus olhos e provocaram minha ira desde que seus antepassados saíram do Egito".

[[v12-21-16]]

^<<v12-21-16,16>>^ Além de levar o povo de Judá a pecar e fazer o que era mau aos olhos do SENHOR, Manassés assassinou muitos inocentes, até encher Jerusalém do sangue deles, de uma extremidade à outra.

[[v12-21-17]]

^<<v12-21-17,17>>^ Os demais acontecimentos do reinado de Manassés e tudo que ele fez, incluindo os pecados que cometeu, estão registrados no Livro da História dos Reis de Judá .

[[v12-21-18]]

^<<v12-21-18,18>>^ Quando Manassés morreu e se reuniu a seus antepassados, foi sepultado no jardim de seu palácio, o jardim de Uzá. Seu filho Amom foi seu sucessor.

[[v12-21-19]]

^<<v12-21-19,19>>^ Amom tinha 22 anos quando começou a reinar, e reinou em Jerusalém por dois anos. Sua mãe se chamava Mesulemete e era filha de Haruz, de Jotbá.

[[v12-21-20]]

^<<v12-21-20,20>>^ Fez o que era mau aos olhos do SENHOR, como seu pai, Manassés, havia feito.

[[v12-21-21]]

^<<v12-21-21,21>>^ Seguiu o exemplo de seu pai e adorou os mesmos ídolos que ele.

[[v12-21-22]]

^<<v12-21-22,22>>^ Abandonou o SENHOR, o Deus de seus antepassados, e não andou nos caminhos do SENHOR.

[[v12-21-23]]

^<<v12-21-23,23>>^ Os próprios oficiais de Amom conspiraram contra ele e o assassinaram em seu palácio.

[[v12-21-24]]

^<<v12-21-24,24>>^ Mas o povo da terra matou todos que haviam conspirado contra o rei Amom e proclamou rei seu filho Josias.

[[v12-21-25]]

^<<v12-21-25,25>>^ Os demais acontecimentos do reinado de Amom e tudo que ele fez estão registrados no Livro da História dos Reis de Judá .

[[v12-21-26]]

^<<v12-21-26,26>>^ Ele foi sepultado em seu túmulo no jardim de Uzá. Seu filho Josias foi seu sucessor.

'''

xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[&#60; Capítulo Anterior] | <<v12-21-0,Topo>> | xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[Próximo Capítulo &#62;]