include::./index.adoc[]

[[v12-9-0]]
=== 2 Reis, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v12-9-1]]

^<<v12-9-1,1>>^ Enquanto isso, o profeta Eliseu chamou um membro do grupo de profetas e lhe disse: "Prepare-se para viajar e leve esta vasilha de óleo. Vá a Ramote-Gileade

[[v12-9-2]]

^<<v12-9-2,2>>^ e procure Jeú, filho de Josafá, filho de Ninsi. Chame-o a uma sala à parte, longe de seus companheiros,

[[v12-9-3]]

^<<v12-9-3,3>>^ e derrame o óleo sobre a cabeça dele. Diga-lhe: ‘Assim diz o SENHOR: Eu o ungi rei de Israel’. Depois, abra a porta e saia correndo".

[[v12-9-4]]

^<<v12-9-4,4>>^ O jovem profeta fez o que Eliseu ordenou e foi a Ramote-Gileade.

[[v12-9-5]]

^<<v12-9-5,5>>^ Quando chegou lá, encontrou Jeú sentado com outros oficiais do exército. "Comandante, tenho uma mensagem para o senhor", disse o profeta. "Para qual de nós?", perguntou Jeú. "Para o senhor, comandante", respondeu ele.

[[v12-9-6]]

^<<v12-9-6,6>>^ Jeú se levantou e entrou na casa. O jovem profeta derramou o óleo sobre a cabeça de Jeú e disse: "Assim diz o SENHOR, o Deus de Israel: ‘Eu o ungi rei de Israel, o povo do SENHOR.

[[v12-9-7]]

^<<v12-9-7,7>>^ Destrua a família de Acabe, seu senhor. Desse modo, vingarei o assassinato de meus profetas e de todos os servos do SENHOR mortos por Jezabel.

[[v12-9-8]]

^<<v12-9-8,8>>^ Toda a família de Acabe deve ser exterminada. Destruirei todos os seus descendentes do sexo masculino em Israel, tanto escravos como livres.

[[v12-9-9]]

^<<v12-9-9,9>>^ Destruirei a família de Acabe como destruí as famílias de Jeroboão, filho de Nebate, e de Baasa, filho de Aías.

[[v12-9-10]]

^<<v12-9-10,10>>^ Cães comerão Jezabel no campo em Jezreel, e ninguém a sepultará’". Então o jovem profeta abriu a porta e saiu correndo.

[[v12-9-11]]

^<<v12-9-11,11>>^ Jeú voltou aos outros oficiais do rei, e um deles lhe perguntou: "O que esse louco queria? Está tudo bem?". "Vocês conhecem gente desse tipo e as coisas que eles dizem", respondeu Jeú.

[[v12-9-12]]

^<<v12-9-12,12>>^ "Você está escondendo algo", disseram. "Conte-nos o que ele disse." Então Jeú lhes contou: "Ele me disse: ‘Assim diz o SENHOR: Eu o ungi rei de Israel’".

[[v12-9-13]]

^<<v12-9-13,13>>^ No mesmo instante, eles estenderam suas capas sobre os degraus para Jeú passar, tocaram a trombeta e gritaram: "Jeú é rei!".

[[v12-9-14]]

^<<v12-9-14,14>>^ Assim, Jeú, filho de Josafá, filho de Ninsi, liderou uma conspiração contra o rei Jorão. (O rei Jorão havia estado com o exército em Ramote-Gileade, onde defendeu Israel do exército de Hazael, rei da Síria.

[[v12-9-15]]

^<<v12-9-15,15>>^ Contudo, o rei Jorão tinha sido ferido na batalha e voltou a Jezreel para se recuperar dos ferimentos causados pelos sírios.) Jeú disse aos homens que estavam com ele: "Se querem que eu seja rei, não deixem que ninguém saia da cidade e vá a Jezreel contar o que fizemos".

[[v12-9-16]]

^<<v12-9-16,16>>^ Em seguida, Jeú subiu numa carruagem e foi a Jezreel, onde o rei Jorão se recuperava de seus ferimentos. Acazias, rei de Judá, também estava ali, pois tinha ido visitar Jorão.

[[v12-9-17]]

^<<v12-9-17,17>>^ Quando a sentinela na torre de Jezreel viu Jeú e sua tropa se aproximarem, gritou: "Uma tropa se aproxima!". O rei Jorão ordenou: "Envie um cavaleiro para perguntar se eles vêm em paz".

[[v12-9-18]]

^<<v12-9-18,18>>^ O cavaleiro foi ao encontro de Jeú e disse: "O rei quer saber se vocês vêm em paz". Jeú respondeu: "O que lhe interessa a paz? Junte-se a nós!". A sentinela informou: "O mensageiro se encontrou com eles, mas não está voltando!".

[[v12-9-19]]

^<<v12-9-19,19>>^ Então o rei enviou outro cavaleiro. Ele foi ao encontro deles e disse: "O rei quer saber se vocês vêm em paz". Jeú respondeu novamente: "O que lhe interessa a paz? Junte-se a nós!".

[[v12-9-20]]

^<<v12-9-20,20>>^ A sentinela exclamou: "O mensageiro se encontrou com eles, mas também não está voltando! Deve ser Jeú, filho de Ninsi, pois conduz seu carro de guerra como um louco!".

[[v12-9-21]]

^<<v12-9-21,21>>^ "Rápido! Prepare meu carro de guerra!", ordenou o rei Jorão. Jorão, rei de Israel, e Acazias, rei de Judá, cada um em seu carro, saíram ao encontro de Jeú e o acharam no campo de Nabote, em Jezreel.

[[v12-9-22]]

^<<v12-9-22,22>>^ O rei Jorão perguntou: "Você vem em paz, Jeú?". Jeú respondeu: "Como pode haver paz enquanto estamos cercados da idolatria e da feitiçaria de sua mãe, Jezabel?".

[[v12-9-23]]

^<<v12-9-23,23>>^ Então o rei Jorão deu meia-volta com seus cavalos e fugiu, gritando para o rei Acazias: "Traição, Acazias!".

[[v12-9-24]]

^<<v12-9-24,24>>^ Jeú disparou seu arco com toda a força e atingiu Jorão entre os ombros. A flecha atravessou seu coração, e ele caiu morto dentro do carro de guerra.

[[v12-9-25]]

^<<v12-9-25,25>>^ Jeú disse a Bidcar, seu oficial: "Jogue-o no campo que pertencia a Nabote de Jezreel. Lembra-se de quando você e eu acompanhávamos a cavalo o pai dele, Acabe? O SENHOR pronunciou esta mensagem contra ele:

[[v12-9-26]]

^<<v12-9-26,26>>^ ‘Assim diz o SENHOR: Ontem vi o assassinato de Nabote e seus filhos. Juro solenemente que o farei pagar por ele neste campo’. Portanto, jogue-o na propriedade de Nabote, como o SENHOR disse".

[[v12-9-27]]

^<<v12-9-27,27>>^ Quando Acazias, rei de Judá, viu o que estava acontecendo, fugiu pela estrada para Bete-Hagã. Jeú foi atrás dele, gritando: "Atirem nele também!". E atingiram Acazias em seu carro de guerra, na subida para Gur, perto de Ibleã. Ele conseguiu ir até Megido, mas morreu ali.

[[v12-9-28]]

^<<v12-9-28,28>>^ Os servos de Acazias levaram seu corpo no carro de guerra para Jerusalém, onde o sepultaram com seus antepassados na Cidade de Davi.

[[v12-9-29]]

^<<v12-9-29,29>>^ Acazias havia começado a reinar em Judá no décimo primeiro ano do reinado de Jorão, filho de Acabe.

[[v12-9-30]]

^<<v12-9-30,30>>^ Quando Jezabel soube que Jeú tinha chegado a Jezreel, pintou os olhos, arrumou os cabelos e sentou-se em frente a uma janela.

[[v12-9-31]]

^<<v12-9-31,31>>^ Quando Jeú entrou pela porta do palácio, ela gritou para ele: "Veio em paz, assassino? Você é como Zinri, que matou seu senhor!".

[[v12-9-32]]

^<<v12-9-32,32>>^ Jeú olhou para cima, viu Jezabel na janela e gritou: "Quem está do meu lado?". Dois ou três eunucos olharam para ele.

[[v12-9-33]]

^<<v12-9-33,33>>^ "Joguem-na para baixo!", ordenou Jeú. Eles a jogaram pela janela, e o sangue espirrou na parede e nos cavalos. E Jeú atropelou o corpo com as patas de seus cavalos.

[[v12-9-34]]

^<<v12-9-34,34>>^ Em seguida, Jeú entrou no palácio, comeu e bebeu. Depois, disse: "Alguém vá sepultar aquela maldita mulher, pois era filha de rei".

[[v12-9-35]]

^<<v12-9-35,35>>^ Mas, quando foram sepultá-la, só encontraram o crânio, os pés e as mãos.

[[v12-9-36]]

^<<v12-9-36,36>>^ Quando voltaram e contaram a Jeú, ele disse: "Isso cumpre a mensagem do SENHOR, anunciada por meio de seu servo Elias, de Tisbe: ‘Cães devorarão o corpo de Jezabel no campo em Jezreel.

[[v12-9-37]]

^<<v12-9-37,37>>^ Seus restos serão espalhados como esterco no campo, de modo que ninguém será capaz de reconhecê-la’".

'''

xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[&#60; Capítulo Anterior] | <<v12-9-0,Topo>> | xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[Próximo Capítulo &#62;]