include::./index.adoc[]

[[v12-22-0]]
=== 2 Reis, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v12-22-1]]

^<<v12-22-1,1>>^ Josias tinha 8 anos quando começou a reinar, e reinou por 31 anos em Jerusalém. Sua mãe se chamava Jedida e era filha de Adaías, de Bozcate.

[[v12-22-2]]

^<<v12-22-2,2>>^ Josias fez o que era certo aos olhos do SENHOR e seguiu o exemplo de seu antepassado Davi, não se desviando nem para um lado nem para o outro.

[[v12-22-3]]

^<<v12-22-3,3>>^ No décimo oitavo ano de seu reinado, o rei Josias enviou Safã, secretário da corte, filho de Azalias, filho de Mesulão, ao templo do SENHOR. Disse-lhe:

[[v12-22-4]]

^<<v12-22-4,4>>^ "Vá ao sumo sacerdote Hilquias e peça-lhe que pese a prata que os guardas das portas recolheram do povo no templo do SENHOR.

[[v12-22-5]]

^<<v12-22-5,5>>^ Entregue a prata aos homens encarregados de supervisionar a reforma do templo. Eles a usarão para pagar os trabalhadores que farão reparos no templo do SENHOR.

[[v12-22-6]]

^<<v12-22-6,6>>^ Precisarão de carpinteiros, construtores e pedreiros. Também deverão comprar a madeira e as pedras cortadas necessárias para os reparos no templo.

[[v12-22-7]]

^<<v12-22-7,7>>^ Contudo, não exija que os supervisores prestem contas do valor que receberam, pois são homens de confiança".

[[v12-22-8]]

^<<v12-22-8,8>>^ O sumo sacerdote Hilquias disse a Safã, secretário da corte: "Encontrei o Livro da Lei no templo do SENHOR!". E Hilquias entregou o livro a Safã, que o leu.

[[v12-22-9]]

^<<v12-22-9,9>>^ Safã voltou ao rei e relatou: "Seus oficiais entregaram a prata recolhida no templo do SENHOR aos trabalhadores e supervisores no templo".

[[v12-22-10]]

^<<v12-22-10,10>>^ Safã também disse ao rei: "O sacerdote Hilquias me entregou um livro". E Safã leu o livro para o rei.

[[v12-22-11]]

^<<v12-22-11,11>>^ Quando o rei ouviu o que estava escrito no Livro da Lei, rasgou suas roupas.

[[v12-22-12]]

^<<v12-22-12,12>>^ Em seguida, deu estas ordens ao sacerdote Hilquias, a Aicam, filho de Safã, a Acbor, filho de Micaías, a Safã, o secretário da corte, e a Asaías, conselheiro pessoal do rei:

[[v12-22-13]]

^<<v12-22-13,13>>^ "Vão consultar o SENHOR por mim, pelo povo e por todo o Judá. Perguntem a respeito das palavras escritas neste livro que foi encontrado. A grande ira do SENHOR arde contra nós, pois nossos antepassados não obedeceram às palavras deste livro. Eles não fizeram tudo que ele diz que devemos fazer".

[[v12-22-14]]

^<<v12-22-14,14>>^ Então o sacerdote Hilquias, Aicam, Acbor, Safã e Asaías foram ao Bairro Novo de Jerusalém consultar a profetisa Hulda. Ela era esposa de Salum, filho de Ticvá, filho de Harás, responsável pelo guarda-roupa do templo.

[[v12-22-15]]

^<<v12-22-15,15>>^ Ela lhes disse: "O SENHOR, o Deus de Israel, falou! Voltem e digam ao homem que os enviou

[[v12-22-16]]

^<<v12-22-16,16>>^ que assim diz o SENHOR: ‘Trarei desgraça sobre esta cidade e sobre seus habitantes. Todas as palavras escritas no livro que o rei de Judá leu se cumprirão.

[[v12-22-17]]

^<<v12-22-17,17>>^ Pois meu povo me abandonou e queimou incenso a outros deuses, e estou grandemente irado com eles por tudo que fizeram. Minha ira arderá contra este lugar e não será apagada’.

[[v12-22-18]]

^<<v12-22-18,18>>^ "Mas vão ao rei de Judá que os enviou para consultarem o SENHOR e digam-lhe que assim diz o SENHOR a respeito da mensagem que acabaram de ouvir:

[[v12-22-19]]

^<<v12-22-19,19>>^ ‘Você se arrependeu e se humilhou diante do SENHOR quando ouviu o que eu disse contra esta cidade e contra seus habitantes, que esta terra seria amaldiçoada e se tornaria desolada. Você rasgou as roupas e chorou diante de mim. E eu certamente o ouvi, diz o SENHOR.

[[v12-22-20]]

^<<v12-22-20,20>>^ Portanto, só enviarei a calamidade anunciada depois que você tiver se reunido a seus antepassados e tiver sido sepultado em paz. Você não verá a desgraça que trarei sobre esta cidade’". Então eles levaram a mensagem ao rei.

'''

xref:012-2-reis/012-2-reis-021.adoc#v12-21-0[&#60; Capítulo Anterior] | <<v12-22-0,Topo>> | xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[Próximo Capítulo &#62;]