include::./index.adoc[]

[[v12-2-0]]
=== 2 Reis, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v12-2-1]]

^<<v12-2-1,1>>^ Quando o SENHOR estava para levar Elias ao céu num redemoinho, Elias e Eliseu partiram de Gilgal.

[[v12-2-2]]

^<<v12-2-2,2>>^ No caminho, Elias disse a Eliseu: "Fique aqui, pois o SENHOR me mandou ir a Betel". Eliseu, porém, respondeu: "Tão certo como vive o SENHOR, e tão certo como a sua própria vida, não o deixarei!". E desceram juntos a Betel.

[[v12-2-3]]

^<<v12-2-3,3>>^ O grupo de profetas de Betel foi ao encontro de Eliseu e lhe perguntou: "Você sabe que o SENHOR levará seu mestre hoje?". "Sim, eu sei", respondeu Eliseu. "Mas não falem sobre isso."

[[v12-2-4]]

^<<v12-2-4,4>>^ Então Elias disse a Eliseu: "Fique aqui, pois o SENHOR me mandou ir a Jericó". Mas Eliseu respondeu novamente: "Tão certo como vive o SENHOR, e tão certo como a sua própria vida, não o deixarei". E foram juntos a Jericó.

[[v12-2-5]]

^<<v12-2-5,5>>^ O grupo de profetas de Jericó foi ao encontro de Eliseu e lhe perguntou: "Você sabe que o SENHOR levará seu mestre hoje?". "Sim, eu sei", respondeu Eliseu. "Mas não falem sobre isso."

[[v12-2-6]]

^<<v12-2-6,6>>^ Então Elias disse a Eliseu: "Fique aqui, pois o SENHOR me mandou ir ao rio Jordão". Mais uma vez, porém, Eliseu respondeu: "Tão certo como vive o SENHOR, e tão certo como a sua própria vida, não o deixarei". E seguiram juntos pelo caminho.

[[v12-2-7]]

^<<v12-2-7,7>>^ Cinquenta homens do grupo de profetas também foram e observaram de longe quando Elias e Eliseu pararam junto ao rio Jordão.

[[v12-2-8]]

^<<v12-2-8,8>>^ Elias dobrou seu manto e bateu com ele nas águas. O rio se abriu, e os dois atravessaram em terra seca.

[[v12-2-9]]

^<<v12-2-9,9>>^ Quando chegaram à outra margem, Elias disse a Eliseu: "Diga-me, o que posso fazer por você antes de ser levado embora?". Eliseu respondeu: "Peço-lhe que eu receba uma porção dobrada do seu espírito e me torne seu sucessor".

[[v12-2-10]]

^<<v12-2-10,10>>^ Elias respondeu: "O que você pediu é uma tarefa difícil, mas, se me vir quando eu for separado de você, receberá o que pediu; caso contrário, não será atendido".

[[v12-2-11]]

^<<v12-2-11,11>>^ De repente, enquanto caminhavam e conversavam, surgiu uma carruagem de fogo, puxada por cavalos de fogo. Passou entre os dois e os separou, e Elias foi levado para o céu num redemoinho.

[[v12-2-12]]

^<<v12-2-12,12>>^ Eliseu viu isso e gritou: "Meu pai, meu pai! Você era como os carros de guerra de Israel e seus cavaleiros!". E, quando ele sumiu de vista, Eliseu rasgou as roupas ao meio.

[[v12-2-13]]

^<<v12-2-13,13>>^ Em seguida, pegou o manto de Elias, que tinha caído, e voltou à margem do Jordão.

[[v12-2-14]]

^<<v12-2-14,14>>^ Bateu nas águas com o manto e gritou: "Onde está o SENHOR, o Deus de Elias?". Então o rio se dividiu, e Eliseu o atravessou.

[[v12-2-15]]

^<<v12-2-15,15>>^ Quando os membros do grupo de profetas de Jericó viram o que havia acontecido, exclamaram: "O espírito de Elias repousa sobre Eliseu!". Então foram encontrar-se com Eliseu e se curvaram com o rosto no chão diante dele.

[[v12-2-16]]

^<<v12-2-16,16>>^ Disseram: "Nós, seus servos, temos cinquenta homens corajosos que podem procurar seu mestre no deserto. Talvez o Espírito do SENHOR o tenha deixado em algum monte ou em algum vale". "Não enviem ninguém", disse Eliseu.

[[v12-2-17]]

^<<v12-2-17,17>>^ Mas insistiram tanto que, por fim, constrangido, ele consentiu: "Está bem, enviem os homens". Os cinquenta homens procuraram por três dias, mas não encontraram Elias.

[[v12-2-18]]

^<<v12-2-18,18>>^ Eliseu ainda estava em Jericó quando eles voltaram, e disse: "Não lhes falei que não fossem?".

[[v12-2-19]]

^<<v12-2-19,19>>^ Certo dia, alguns moradores de Jericó disseram a Eliseu: "Temos um problema, meu senhor. A cidade está situada numa boa região, como o senhor pode ver. Contudo, a água não é boa, e a terra é improdutiva".

[[v12-2-20]]

^<<v12-2-20,20>>^ Eliseu disse: "Tragam-me uma tigela nova cheia de sal", e fizeram o que ele pediu.

[[v12-2-21]]

^<<v12-2-21,21>>^ Eliseu foi à nascente que abastecia a cidade com água e jogou ali o sal. Disse ele: "Assim diz o SENHOR: ‘Purifiquei esta água. Ela não causará mais morte nem tornará a terra improdutiva’".

[[v12-2-22]]

^<<v12-2-22,22>>^ E, desde então, a água permanece pura, conforme a palavra de Eliseu.

[[v12-2-23]]

^<<v12-2-23,23>>^ Eliseu saiu dali e foi a Betel. Enquanto subia pelo caminho, um grupo de adolescentes da cidade começou a zombar dele. "Vá embora, careca! Vá embora, careca!", gritavam.

[[v12-2-24]]

^<<v12-2-24,24>>^ Eliseu se voltou para trás, olhou para eles e os amaldiçoou em nome do SENHOR. Então duas ursas saíram do bosque e despedaçaram 42 adolescentes.

[[v12-2-25]]

^<<v12-2-25,25>>^ Dali Eliseu foi para o monte Carmelo e, por fim, voltou a Samaria.

'''

xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[&#60; Capítulo Anterior] | <<v12-2-0,Topo>> | xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[Próximo Capítulo &#62;]