include::./index.adoc[]

[[v12-1-0]]
=== 2 Reis, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v12-1-1]]

^<<v12-1-1,1>>^ Depois da morte do rei Acabe, a terra de Moabe se rebelou contra Israel.

[[v12-1-2]]

^<<v12-1-2,2>>^ Certo dia, Acazias caiu pela grade de um cômodo no terraço de seu palácio em Samaria e ficou gravemente ferido. Ele enviou mensageiros ao templo de Baal-Zebube, deus de Ecrom, para saber se iria se recuperar.

[[v12-1-3]]

^<<v12-1-3,3>>^ O anjo do SENHOR, porém, disse a Elias, de Tisbe: "Vá ao encontro dos mensageiros do rei de Samaria e diga-lhes: ‘Acaso não há Deus em Israel? Por que vão consultar Baal-Zebube, o deus de Ecrom?

[[v12-1-4]]

^<<v12-1-4,4>>^ Por isso, assim diz o SENHOR: Você nunca mais se levantará da cama onde está; certamente morrerá!’". Então Elias partiu.

[[v12-1-5]]

^<<v12-1-5,5>>^ Quando os mensageiros voltaram ao rei, ele lhes perguntou: "Por que voltaram tão depressa?".

[[v12-1-6]]

^<<v12-1-6,6>>^ Eles responderam: "Um homem veio ao nosso encontro e nos instruiu a voltarmos ao rei e lhe darmos esta mensagem: ‘Assim diz o SENHOR: Acaso não há Deus em Israel? Por que enviou seus homens para consultar Baal-Zebube, o deus de Ecrom? Por isso, nunca mais se levantará da cama onde está; certamente morrerá’".

[[v12-1-7]]

^<<v12-1-7,7>>^ "Como era o homem que lhes anunciou essa mensagem?", perguntou o rei.

[[v12-1-8]]

^<<v12-1-8,8>>^ Eles responderam: "Vestia roupas feitas de pelos e usava um cinto de couro". "Era Elias, de Tisbe!", exclamou o rei.

[[v12-1-9]]

^<<v12-1-9,9>>^ Em seguida, enviou um capitão de seu exército com cinquenta soldados para prender Elias. Eles o encontraram sentado no alto de um monte. O capitão lhe disse: "Homem de Deus, o rei ordena que você desça conosco".

[[v12-1-10]]

^<<v12-1-10,10>>^ Elias respondeu ao capitão: "Se sou homem de Deus, que desça fogo do céu e destrua você e seus cinquenta soldados!". Então desceu fogo do céu e matou todos eles.

[[v12-1-11]]

^<<v12-1-11,11>>^ O rei enviou outro capitão com cinquenta soldados. O capitão disse a Elias: "Homem de Deus, o rei ordena que você desça imediatamente".

[[v12-1-12]]

^<<v12-1-12,12>>^ Elias, porém, respondeu: "Se sou homem de Deus, que desça fogo do céu e destrua você e seus cinquenta soldados!". Novamente desceu fogo do céu e matou todos eles.

[[v12-1-13]]

^<<v12-1-13,13>>^ Pela terceira vez, o rei enviou um capitão com cinquenta soldados. Esse capitão, porém, subiu o monte todo, ajoelhou-se diante de Elias e implorou: "Ó homem de Deus, por favor, poupe minha vida e a vida destes seus cinquenta servos.

[[v12-1-14]]

^<<v12-1-14,14>>^ Sabemos que desceu fogo do céu e destruiu os outros dois capitães e seus grupos de soldados. Mas, agora, peço que poupe minha vida!".

[[v12-1-15]]

^<<v12-1-15,15>>^ Então o anjo do SENHOR disse a Elias: "Desça com ele e não tenha medo". Assim, Elias se levantou, desceu e foi falar com o rei.

[[v12-1-16]]

^<<v12-1-16,16>>^ Elias disse ao rei: "Assim diz o SENHOR: ‘Por que enviou mensageiros para consultar Baal-Zebube, o deus de Ecrom? Acaso não há Deus em Israel? Por isso, você nunca mais se levantará da cama onde está; certamente morrerá".

[[v12-1-17]]

^<<v12-1-17,17>>^ Então Acazias morreu, conforme o SENHOR havia anunciado por meio de Elias. Acazias não tinha nenhum filho para reinar em seu lugar, de modo que seu irmão Jorão foi seu sucessor. Isso aconteceu no segundo ano do reinado de Jeorão, filho de Josafá, rei de Judá.

[[v12-1-18]]

^<<v12-1-18,18>>^ Os demais acontecimentos do reinado de Acazias e tudo que ele fez estão registrados no Livro da História dos Reis de Israel .

'''

xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[&#60; Capítulo Anterior] | <<v12-1-0,Topo>> | xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[Próximo Capítulo &#62;]