include::./index.adoc[]

[[v12-7-0]]
=== 2 Reis, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v12-7-1]]

^<<v12-7-1,1>>^ Eliseu respondeu: "Ouçam esta mensagem do SENHOR! Assim diz o SENHOR: ‘Amanhã a esta hora, na porta de Samaria, seis litros de farinha fina custarão apenas doze gramas de prata, e doze litros de cevada também custarão apenas doze gramas de prata’".

[[v12-7-2]]

^<<v12-7-2,2>>^ O oficial que auxiliava o rei disse ao homem de Deus: "Ainda que o SENHOR abrisse as janelas do céu, isso não poderia acontecer!". Eliseu, porém, respondeu: "Você verá com os próprios olhos, mas não comerá coisa alguma!".

[[v12-7-3]]

^<<v12-7-3,3>>^ Havia quatro homens com lepra sentados junto à porta da cidade. "Por que ficarmos sentados aqui, esperando a morte?", perguntaram uns aos outros.

[[v12-7-4]]

^<<v12-7-4,4>>^ "Morreremos de fome se ficarmos aqui, mas também morreremos de fome se entrarmos na cidade, pois não há alimento lá. Vamos sair e nos render ao exército sírio. Se eles nos deixarem viver, melhor. Mas, se nos matarem, de qualquer maneira teríamos morrido."

[[v12-7-5]]

^<<v12-7-5,5>>^ Ao anoitecer, partiram para o acampamento dos sírios. Quando chegaram às extremidades do acampamento, viram que não havia ninguém ali.

[[v12-7-6]]

^<<v12-7-6,6>>^ Pois o Senhor havia feito o exército sírio ouvir o ruído de carros de guerra e o galope de cavalos e os sons de um grande exército que se aproximava. Disseram uns aos outros: "O rei de Israel contratou mercenários hititas e egípcios para nos atacarem!".

[[v12-7-7]]

^<<v12-7-7,7>>^ Por isso, fugiram ao anoitecer, abandonando tendas, cavalos, jumentos e tudo mais, e correram para salvar a vida.

[[v12-7-8]]

^<<v12-7-8,8>>^ Quando os leprosos chegaram às extremidades do acampamento, foram de uma tenda à outra, comendo e bebendo. Pegaram a prata, o ouro e as roupas que encontraram e esconderam tudo.

[[v12-7-9]]

^<<v12-7-9,9>>^ Por fim, disseram uns aos outros: "Isto não está certo. Este é um dia de boas notícias e não contamos a ninguém! Se esperarmos até o amanhecer, seremos castigados. Venham! Vamos voltar e dar as notícias no palácio".

[[v12-7-10]]

^<<v12-7-10,10>>^ Então voltaram à cidade e relataram aos guardas do portão o que havia acontecido. "Fomos ao acampamento sírio e não havia ninguém!", disseram eles. "Os cavalos e os jumentos estavam amarrados, e as tendas, todas armadas, mas não havia ninguém por ali."

[[v12-7-11]]

^<<v12-7-11,11>>^ Os guardas gritaram, anunciando a notícia no palácio.

[[v12-7-12]]

^<<v12-7-12,12>>^ O rei se levantou no meio da noite e disse a seus oficiais: "Vou explicar o que aconteceu. Os sírios sabem que estamos morrendo de fome, por isso deixaram o acampamento e se esconderam nos campos. Estão à nossa espera para nos capturar com vida e conquistar a cidade quando sairmos".

[[v12-7-13]]

^<<v12-7-13,13>>^ Um de seus oficiais disse: "Seria melhor que enviássemos espiões para ver. Eles podem usar cinco dos cavalos que sobraram. Se acontecer alguma coisa com eles, não será pior que se ficarem aqui e morrerem com o restante de nós".

[[v12-7-14]]

^<<v12-7-14,14>>^ Assim, prepararam dois carros de guerra com cavalos, e o rei enviou espiões para ver o que havia acontecido ao acampamento sírio.

[[v12-7-15]]

^<<v12-7-15,15>>^ Foram até o rio Jordão, seguindo o rastro de roupas e equipamentos que os sírios tinham abandonado em sua fuga desesperada. Os espiões voltaram e contaram tudo ao rei.

[[v12-7-16]]

^<<v12-7-16,16>>^ Então o povo correu e saqueou o acampamento sírio. E, de fato, naquele dia seis litros de farinha fina foram vendidos por apenas doze gramas de prata, e doze litros de cevada também foram vendidos por apenas doze gramas de prata, como o SENHOR tinha dito.

[[v12-7-17]]

^<<v12-7-17,17>>^ O rei colocou o oficial que o auxiliava para controlar o movimento à porta da cidade, mas ele foi derrubado, pisoteado e morto quando a multidão correu para fora. Tudo aconteceu, portanto, conforme o homem de Deus tinha dito quando o rei foi à sua casa.

[[v12-7-18]]

^<<v12-7-18,18>>^ O homem de Deus tinha dito ao rei: "Amanhã a esta hora, na porta de Samaria, seis litros de farinha fina custarão apenas doze gramas de prata, e doze litros de cevada também custarão apenas doze gramas de prata".

[[v12-7-19]]

^<<v12-7-19,19>>^ O oficial do rei havia respondido: "Ainda que o SENHOR abrisse as janelas do céu, isso não poderia acontecer!". E o homem de Deus tinha dito: "Você verá com os próprios olhos, mas não comerá coisa alguma!".

[[v12-7-20]]

^<<v12-7-20,20>>^ E assim aconteceu, pois ele foi pisoteado pelo povo à porta da cidade e morreu.

'''

xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[Próximo Capítulo &#62;]