include::./index.adoc[]

[[v12-17-0]]
=== 2 Reis, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v12-17-1]]

^<<v12-17-1,1>>^ Oseias, filho de Elá, começou a reinar em Israel no décimo segundo ano do reinado de Acaz, rei de Judá. Reinou em Samaria por nove anos.

[[v12-17-2]]

^<<v12-17-2,2>>^ Fez o que era mau aos olhos do SENHOR, mas não tanto quanto os reis que governaram Israel antes dele.

[[v12-17-3]]

^<<v12-17-3,3>>^ Salmaneser, rei da Assíria, atacou o rei Oseias e o obrigou a lhe pagar tributos.

[[v12-17-4]]

^<<v12-17-4,4>>^ Oseias, porém, conspirou contra o rei da Assíria. Deixou de pagar o tributo anual e pediu ajuda a Sô, rei do Egito. Quando o rei da Assíria descobriu a traição de Oseias, mandou colocá-lo na prisão.

[[v12-17-5]]

^<<v12-17-5,5>>^ O rei da Assíria ocupou todo o território de Israel e, durante três anos, cercou a cidade de Samaria.

[[v12-17-6]]

^<<v12-17-6,6>>^ Por fim, no nono ano do reinado de Oseias, o rei assírio conquistou Samaria e exilou os israelitas na Assíria. Criou assentamentos para eles em Hala, ao longo das margens do rio Habor, em Gozã, e nas cidades da Média.

[[v12-17-7]]

^<<v12-17-7,7>>^ Isso aconteceu porque os israelitas adoraram outros deuses. Pecaram contra o SENHOR, seu Deus, que os havia tirado da terra do Egito e os livrado do poder do faraó, o rei do Egito.

[[v12-17-8]]

^<<v12-17-8,8>>^ Seguiram as práticas das nações que o SENHOR tinha expulsado de diante deles, bem como as práticas introduzidas pelos reis de Israel.

[[v12-17-9]]

^<<v12-17-9,9>>^ Os israelitas também fizeram, em segredo, muitas coisas que não eram corretas diante do SENHOR, seu Deus. Construíram santuários idólatras em todas as cidades, desde o menor posto de vigilância até a maior cidade murada.

[[v12-17-10]]

^<<v12-17-10,10>>^ Ergueram colunas sagradas e postes de Aserá no alto de todo monte e debaixo de toda árvore verdejante.

[[v12-17-11]]

^<<v12-17-11,11>>^ Queimaram incenso no topo dos montes, como faziam as nações que o SENHOR havia expulsado de diante deles. Os israelitas praticaram muitos atos perversos que provocaram a ira do SENHOR.

[[v12-17-12]]

^<<v12-17-12,12>>^ Adoraram ídolos, apesar das advertências claras do SENHOR contra isso.

[[v12-17-13]]

^<<v12-17-13,13>>^ Repetidamente, o SENHOR enviou profetas e videntes para advertirem Israel e Judá, com esta mensagem: "Afastem-se de seus maus caminhos. Obedeçam a meus mandamentos e decretos, a toda a lei que ordenei a seus antepassados e que lhes entreguei por meio de meus servos, os profetas".

[[v12-17-14]]

^<<v12-17-14,14>>^ Mas os israelitas se recusaram a ouvir. Foram tão teimosos quanto seus antepassados que não quiseram crer no SENHOR, seu Deus.

[[v12-17-15]]

^<<v12-17-15,15>>^ Rejeitaram seus decretos e a aliança que ele havia feito com seus antepassados e desprezaram todas as suas advertências. Adoraram ídolos inúteis, de modo que eles próprios se tornaram inúteis. Seguiram o exemplo das nações ao redor e desobedeceram à ordem do SENHOR para que não as imitassem.

[[v12-17-16]]

^<<v12-17-16,16>>^ Rejeitaram todos os mandamentos do SENHOR, seu Deus, e fizeram dois bezerros de metal. Ergueram um poste de Aserá e adoraram Baal e todos os astros do céu.

[[v12-17-17]]

^<<v12-17-17,17>>^ Chegaram a sacrificar os próprios filhos e filhas no fogo. Consultaram adivinhos, praticaram feitiçaria, venderam-se para fazer o que é mau aos olhos do SENHOR e provocaram sua ira.

[[v12-17-18]]

^<<v12-17-18,18>>^ O SENHOR se indignou muito com Israel e o expulsou de sua presença. Com isso, restou somente a tribo de Judá.

[[v12-17-19]]

^<<v12-17-19,19>>^ Mesmo o povo de Judá, porém, não obedeceu aos mandamentos do SENHOR, seu Deus, pois seguiu as práticas perversas introduzidas por Israel.

[[v12-17-20]]

^<<v12-17-20,20>>^ O SENHOR rejeitou todos os descendentes de Israel. Como castigo, entregou-os a seus inimigos, até que expulsou Israel de sua presença.

[[v12-17-21]]

^<<v12-17-21,21>>^ Pois quando o SENHOR arrancou Israel do reino de Davi, os israelitas escolheram Jeroboão, filho de Nebate, como rei. Mas Jeroboão afastou Israel do SENHOR e os levou a cometer grande pecado.

[[v12-17-22]]

^<<v12-17-22,22>>^ E os israelitas continuaram a seguir todos os caminhos maus de Jeroboão. Não se afastaram desses pecados,

[[v12-17-23]]

^<<v12-17-23,23>>^ até que, por fim, o SENHOR os expulsou de sua presença, como todos os seus profetas haviam advertido. Assim, Israel foi deportado de sua terra para a Assíria, onde permanece até hoje.

[[v12-17-24]]

^<<v12-17-24,24>>^ O rei da Assíria trouxe povos da Babilônia, de Cuta, de Ava, de Hamate e de Sefarvaim e os estabeleceu nas cidades de Samaria, em lugar dos israelitas. Eles tomaram posse de Samaria e habitaram em suas cidades.

[[v12-17-25]]

^<<v12-17-25,25>>^ Assim que chegaram, esses estrangeiros não adoravam o SENHOR, de modo que o SENHOR mandou leões, que mataram alguns deles.

[[v12-17-26]]

^<<v12-17-26,26>>^ Por isso, enviaram uma mensagem ao rei da Assíria: "O povo que o senhor deportou para as cidades de Samaria não conhece os costumes do deus da terra. Ele mandou leões para destruí-los, porque não conhecem suas exigências".

[[v12-17-27]]

^<<v12-17-27,27>>^ Então o rei da Assíria deu esta ordem: "Enviem um dos sacerdotes exilados de volta a Samaria. Ele viverá ali e ensinará aos novos habitantes os costumes do deus da terra".

[[v12-17-28]]

^<<v12-17-28,28>>^ Um dos sacerdotes exilados de Samaria voltou a Betel e ensinava os novos habitantes a adorarem corretamente o SENHOR.

[[v12-17-29]]

^<<v12-17-29,29>>^ Contudo, cada um desses povos estrangeiros continuou a fazer seus deuses e adorá-los. Em todas as cidades onde habitavam, colocaram seus ídolos nos santuários idólatras que o povo de Samaria havia construído.

[[v12-17-30]]

^<<v12-17-30,30>>^ Os da Babilônia adoravam as imagens do deus Sucote-Benote. Os de Cuta adoravam o deus Nergal. Os de Hamate adoravam o deus Asima.

[[v12-17-31]]

^<<v12-17-31,31>>^ Os aveus adoravam os deuses Nibaz e Tartaque. E o povo de Sefarvaim até queimava os próprios filhos como sacrifício aos deuses Adrameleque e Anameleque.

[[v12-17-32]]

^<<v12-17-32,32>>^ Esses novos habitantes adoravam o SENHOR, mas também nomeavam qualquer pessoa como sacerdote para oferecer sacrifícios nos lugares de culto.

[[v12-17-33]]

^<<v12-17-33,33>>^ E, embora adorassem o SENHOR, continuavam a seguir seus próprios deuses, de acordo com os costumes de suas nações de origem.

[[v12-17-34]]

^<<v12-17-34,34>>^ Até hoje, continuam com suas antigas práticas em vez de adorar verdadeiramente o SENHOR e obedecer aos decretos, estatutos, leis e mandamentos que o SENHOR deu aos descendentes de Jacó, cujo nome ele mudou para Israel.

[[v12-17-35]]

^<<v12-17-35,35>>^ Pois o SENHOR havia feito uma aliança com eles e ordenado: "Não adorem outros deuses, nem se prostrem diante deles, não os sirvam, nem lhes ofereçam sacrifícios.

[[v12-17-36]]

^<<v12-17-36,36>>^ Adorem somente o SENHOR, que os tirou do Egito com grande força e com braço poderoso. Curvem-se somente diante dele e ofereçam sacrifícios a ele somente.

[[v12-17-37]]

^<<v12-17-37,37>>^ Tomem sempre o cuidado de obedecer aos decretos, estatutos, leis e mandamentos que ele lhes prescreveu. Não adorem outros deuses.

[[v12-17-38]]

^<<v12-17-38,38>>^ Não se esqueçam da aliança que fiz com vocês e não adorem outros deuses.

[[v12-17-39]]

^<<v12-17-39,39>>^ Adorem somente o SENHOR, seu Deus. Ele os livrará de todos os seus inimigos".

[[v12-17-40]]

^<<v12-17-40,40>>^ Mas o povo se recusou a ouvir e continuou com suas antigas práticas.

[[v12-17-41]]

^<<v12-17-41,41>>^ Assim, embora os novos habitantes adorassem o SENHOR, também adoravam seus ídolos. E até hoje seus descendentes fazem a mesma coisa.

'''

xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[&#60; Capítulo Anterior] | <<v12-17-0,Topo>> | xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[Próximo Capítulo &#62;]