include::./index.adoc[]

[[v12-15-0]]
=== 2 Reis, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v12-15-1]]

^<<v12-15-1,1>>^ Uzias, filho de Amazias, começou a reinar em Judá no vigésimo sétimo ano do reinado de Jeroboão II, rei de Israel.

[[v12-15-2]]

^<<v12-15-2,2>>^ Tinha 16 anos quando começou a reinar, e reinou em Jerusalém por 52 anos. Sua mãe se chamava Jecolias e era de Jerusalém.

[[v12-15-3]]

^<<v12-15-3,3>>^ Fez o que era certo aos olhos do SENHOR, como seu pai, Amazias.

[[v12-15-4]]

^<<v12-15-4,4>>^ Contudo, não destruiu os santuários idólatras, e o povo continuou a oferecer sacrifícios e a queimar incenso nesses lugares.

[[v12-15-5]]

^<<v12-15-5,5>>^ O SENHOR feriu o rei com lepra, enfermidade que durou até o dia de sua morte. Vivia isolado, numa casa separada. Jotão, filho do rei, tomava conta do palácio e governava o povo.

[[v12-15-6]]

^<<v12-15-6,6>>^ Os demais acontecimentos do reinado de Uzias e tudo que ele fez estão registrados no Livro da História dos Reis de Judá .

[[v12-15-7]]

^<<v12-15-7,7>>^ Quando Uzias morreu, foi sepultado com seus antepassados na Cidade de Davi. Seu filho Jotão foi seu sucessor.

[[v12-15-8]]

^<<v12-15-8,8>>^ Zacarias, filho de Jeroboão II, começou a reinar em Israel no trigésimo oitavo ano do reinado de Uzias, rei de Judá. Reinou em Samaria por seis meses.

[[v12-15-9]]

^<<v12-15-9,9>>^ Fez o que era mau aos olhos do SENHOR, como seus antepassados. Não se afastou dos pecados que Jeroboão, filho de Nebate, havia levado Israel a cometer.

[[v12-15-10]]

^<<v12-15-10,10>>^ Então Salum, filho de Jabes, conspirou contra Zacarias, matou-o diante do povo e se tornou seu sucessor.

[[v12-15-11]]

^<<v12-15-11,11>>^ Os demais acontecimentos do reinado de Zacarias estão registrados no Livro da História dos Reis de Israel .

[[v12-15-12]]

^<<v12-15-12,12>>^ Assim se cumpriu a mensagem do SENHOR a Jeú: "Seus descendentes serão reis de Israel até a quarta geração".

[[v12-15-13]]

^<<v12-15-13,13>>^ Salum, filho de Jabes, começou a reinar em Israel no trigésimo nono ano do reinado de Uzias, rei de Judá. Reinou em Samaria por apenas um mês.

[[v12-15-14]]

^<<v12-15-14,14>>^ Então Menaém, filho de Gadi, veio de Tirza a Samaria, matou Salum, filho de Jabes, e se tornou seu sucessor.

[[v12-15-15]]

^<<v12-15-15,15>>^ Os demais acontecimentos do reinado de Salum, incluindo a conspiração que liderou, estão registrados no Livro da História dos Reis de Israel .

[[v12-15-16]]

^<<v12-15-16,16>>^ Nessa ocasião, Menaém destruiu a cidade de Tapua e seus arredores, até Tirza, pois seus habitantes se recusaram a entregar a cidade. Matou toda a população e rasgou o ventre das mulheres grávidas.

[[v12-15-17]]

^<<v12-15-17,17>>^ Menaém, filho de Gadi, começou a reinar em Israel no trigésimo nono ano do reinado de Uzias, rei de Judá. Reinou em Samaria por dez anos.

[[v12-15-18]]

^<<v12-15-18,18>>^ Fez o que era mau aos olhos do SENHOR. Durante todo o seu reinado, não se afastou dos pecados que Jeroboão, filho de Nebate, havia levado Israel a cometer.

[[v12-15-19]]

^<<v12-15-19,19>>^ Então Tiglate-Pileser, rei da Assíria, invadiu a terra de Israel. Contudo, Menaém lhe pagou 35 toneladas de prata a fim de obter seu apoio e firmar-se no poder.

[[v12-15-20]]

^<<v12-15-20,20>>^ Menaém extorquiu esse valor dos ricos de Israel e exigiu que cada um contribuísse com seiscentos gramas de prata para o tributo pago ao rei da Assíria. Assim, o rei da Assíria parou de atacar Israel e foi embora.

[[v12-15-21]]

^<<v12-15-21,21>>^ Os demais acontecimentos do reinado de Menaém e tudo que ele fez estão registrados no Livro da História dos Reis de Israel .

[[v12-15-22]]

^<<v12-15-22,22>>^ Quando Menaém morreu e se reuniu a seus antepassados, seu filho Pecaías se tornou seu sucessor.

[[v12-15-23]]

^<<v12-15-23,23>>^ Pecaías, filho de Menaém, começou a reinar em Israel no quinquagésimo ano do reinado de Uzias, rei de Judá. Reinou em Samaria por dois anos.

[[v12-15-24]]

^<<v12-15-24,24>>^ Fez o que era mau aos olhos do SENHOR. Não se afastou dos pecados que Jeroboão, filho de Nebate, havia levado Israel a cometer.

[[v12-15-25]]

^<<v12-15-25,25>>^ Então Peca, filho de Remalias e comandante do exército de Pecaías, conspirou contra ele. Acompanhado de cinquenta homens de Gileade, assassinou o rei, e também Argobe e Arié, na fortaleza do palácio em Samaria. E Peca se tornou seu sucessor.

[[v12-15-26]]

^<<v12-15-26,26>>^ Os demais acontecimentos do reinado de Pecaías e tudo que ele fez estão registrados no Livro da História dos Reis de Israel .

[[v12-15-27]]

^<<v12-15-27,27>>^ Peca, filho de Remalias, começou a reinar em Israel no quinquagésimo segundo ano do reinado de Uzias, rei de Judá. Reinou em Samaria por vinte anos.

[[v12-15-28]]

^<<v12-15-28,28>>^ Fez o que era mau aos olhos do SENHOR. Não se afastou dos pecados que Jeroboão, filho de Nebate, havia levado Israel a cometer.

[[v12-15-29]]

^<<v12-15-29,29>>^ Durante o reinado de Peca, Tiglate-Pileser, rei da Assíria, atacou Israel novamente e conquistou as cidades de Ijom, Abel-Bete-Maaca, Janoa, Quedes e Hazor. Também conquistou as regiões de Gileade e da Galileia, e todo o território de Naftali, e levou os habitantes cativos para a Assíria.

[[v12-15-30]]

^<<v12-15-30,30>>^ Então Oseias, filho de Elá, conspirou contra Peca, filho de Remalias, e o assassinou. Começou a reinar em Israel no vigésimo ano do reinado de Jotão, filho de Uzias.

[[v12-15-31]]

^<<v12-15-31,31>>^ Os demais acontecimentos do reinado de Peca e tudo que ele fez estão registrados no Livro da História dos Reis de Israel .

[[v12-15-32]]

^<<v12-15-32,32>>^ Jotão, filho de Uzias, começou a reinar em Judá no segundo ano do reinado de Peca, filho de Remalias, rei de Israel.

[[v12-15-33]]

^<<v12-15-33,33>>^ Tinha 25 anos quando começou a reinar, e reinou em Jerusalém por dezesseis anos. Sua mãe se chamava Jerusa e era filha de Zadoque.

[[v12-15-34]]

^<<v12-15-34,34>>^ Jotão fez o que era certo aos olhos do SENHOR, como seu pai, Uzias.

[[v12-15-35]]

^<<v12-15-35,35>>^ Contudo, não destruiu os santuários idólatras, e o povo continuou a oferecer sacrifícios e a queimar incenso nesse lugares. Jotão reconstruiu a porta superior do templo do SENHOR.

[[v12-15-36]]

^<<v12-15-36,36>>^ Os demais acontecimentos do reinado de Jotão e tudo que ele fez estão registrados no Livro da História dos Reis de Judá .

[[v12-15-37]]

^<<v12-15-37,37>>^ Naqueles dias, o SENHOR começou a instigar Rezim, rei da Síria, e Peca, filho de Remalias, a atacarem Judá.

[[v12-15-38]]

^<<v12-15-38,38>>^ Quando Jotão morreu, foi sepultado com seus antepassados na Cidade de Davi. Seu filho Acaz foi seu sucessor.

'''

xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[&#60; Capítulo Anterior] | <<v12-15-0,Topo>> | xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[Próximo Capítulo &#62;]