include::./index.adoc[]

[[v12-20-0]]
=== 2 Reis, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v12-20-1]]

^<<v12-20-1,1>>^ Por esse tempo, Ezequias ficou doente e estava para morrer. O profeta Isaías, filho de Amoz, foi visitá-lo e transmitiu-lhe a seguinte mensagem: "Assim diz o SENHOR: ‘Ponha suas coisas em ordem, pois você vai morrer. Não se recuperará dessa doença’".

[[v12-20-2]]

^<<v12-20-2,2>>^ Quando Ezequias ouviu isso, virou o rosto para a parede e orou ao SENHOR:

[[v12-20-3]]

^<<v12-20-3,3>>^ "Ó SENHOR, lembra-te de como sempre te servi com fidelidade e devoção, e de como sempre fiz o que é certo aos teus olhos". Depois, o rei chorou amargamente.

[[v12-20-4]]

^<<v12-20-4,4>>^ Então, antes que Isaías deixasse o pátio intermediário, recebeu esta mensagem do SENHOR:

[[v12-20-5]]

^<<v12-20-5,5>>^ "Volte a Ezequias, líder de meu povo, e diga-lhe: Assim diz o SENHOR, o Deus de seu antepassado Davi: ‘Ouvi sua oração e vi suas lágrimas. Vou curá-lo e, daqui a três dias, você sairá da cama e irá ao templo do SENHOR.

[[v12-20-6]]

^<<v12-20-6,6>>^ Acrescentarei quinze anos à sua vida e livrarei você e esta cidade do rei da Assíria. Defenderei esta cidade por causa de minha honra e por causa de meu servo Davi’".

[[v12-20-7]]

^<<v12-20-7,7>>^ Então Isaías disse: "Preparem uma pasta de figos". Os servos de Ezequias fizeram a pasta e a espalharam sobre a ferida, e Ezequias se recuperou.

[[v12-20-8]]

^<<v12-20-8,8>>^ Ezequias tinha perguntado a Isaías: "Que sinal o SENHOR dará como prova de que ele vai me curar e de que irei ao templo do SENHOR daqui a três dias?".

[[v12-20-9]]

^<<v12-20-9,9>>^ Isaías respondeu: "Este é o sinal do SENHOR de que cumprirá o que prometeu. Você prefere que a sombra do relógio de sol avance dez graus ou recue dez graus?".

[[v12-20-10]]

^<<v12-20-10,10>>^ "É natural que a sombra avance", disse Ezequias. "Isso seria fácil. Faça-a voltar dez graus."

[[v12-20-11]]

^<<v12-20-11,11>>^ O profeta Isaías orou ao SENHOR, e ele fez a sombra recuar dez graus no relógio de sol de Acaz.

[[v12-20-12]]

^<<v12-20-12,12>>^ Pouco tempo depois, Merodaque-Baladã, filho de Baladã, rei da Babilônia, enviou cartas e um presente para Ezequias, pois soube que o rei tinha estado muito doente.

[[v12-20-13]]

^<<v12-20-13,13>>^ Ezequias recebeu os mensageiros babilônios e lhes mostrou tudo que havia na casa do tesouro: a prata, o ouro, as especiarias e os óleos aromáticos. Também os levou para conhecer seu arsenal e lhes mostrou tudo que havia nos tesouros do rei. Não houve nada em seu palácio nem em seu reino que Ezequias não lhes mostrasse.

[[v12-20-14]]

^<<v12-20-14,14>>^ Então o profeta Isaías foi ver o rei Ezequias e lhe perguntou: "O que esses homens queriam? De onde vieram?". Ezequias respondeu: "Vieram da Babilônia, uma terra distante".

[[v12-20-15]]

^<<v12-20-15,15>>^ "O que viram em seu palácio?", perguntou Isaías. "Viram tudo", Ezequias respondeu. "Eu lhes mostrei tudo que possuo, todos os meus tesouros."

[[v12-20-16]]

^<<v12-20-16,16>>^ Então Isaías disse a Ezequias: "Ouça esta mensagem do SENHOR:

[[v12-20-17]]

^<<v12-20-17,17>>^ ‘Está chegando o dia em que tudo em seu palácio, todos os tesouros que seus antepassados acumularam até agora, será levado para a Babilônia. Não ficará coisa alguma’, diz o SENHOR.

[[v12-20-18]]

^<<v12-20-18,18>>^ ‘Até mesmo alguns de seus descendentes serão levados para o exílio. Eles se tornarão eunucos e servirão no palácio do rei da Babilônia’".

[[v12-20-19]]

^<<v12-20-19,19>>^ Ezequias disse a Isaías: "A mensagem do SENHOR que você transmitiu é boa". Pois o rei pensava: "Pelo menos haverá paz e segurança durante minha vida".

[[v12-20-20]]

^<<v12-20-20,20>>^ Os demais acontecimentos do reinado de Ezequias, incluindo a extensão de seu poder e como construiu uma represa e cavou um túnel para abastecer a cidade com água, estão registrados no Livro da História dos Reis de Judá .

[[v12-20-21]]

^<<v12-20-21,21>>^ Ezequias morreu e se reuniu a seus antepassados, e seu filho Manassés foi seu sucessor.

'''

xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[&#60; Capítulo Anterior] | <<v12-20-0,Topo>> | xref:012-2-reis/012-2-reis-021.adoc#v12-21-0[Próximo Capítulo &#62;]