include::./index.adoc[]

[[v12-14-0]]
=== 2 Reis, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v12-14-1]]

^<<v12-14-1,1>>^ Amazias, filho de Joás, começou a reinar em Judá no segundo ano do reinado de Jeoás, filho de Jeoacaz, rei de Israel.

[[v12-14-2]]

^<<v12-14-2,2>>^ Amazias tinha 25 anos quando começou a reinar, e reinou em Jerusalém por 29 anos. Sua mãe se chamava Jeoadã e era de Jerusalém.

[[v12-14-3]]

^<<v12-14-3,3>>^ Amazias fez o que era certo aos olhos do SENHOR, mas não como seu antepassado Davi. Seguiu o exemplo de seu pai, Joás.

[[v12-14-4]]

^<<v12-14-4,4>>^ Amazias não destruiu os santuários idólatras, e o povo continuou a oferecer sacrifícios e a queimar incenso nesses lugares.

[[v12-14-5]]

^<<v12-14-5,5>>^ Quando Amazias se firmou no poder, executou os oficiais que haviam assassinado seu pai.

[[v12-14-6]]

^<<v12-14-6,6>>^ Contudo, não matou os filhos dos assassinos, em obediência ao mandamento do SENHOR registrado por Moisés no Livro da Lei: "Os pais não serão executados por causa do pecado dos filhos, nem os filhos por causa do pecado dos pais. Aqueles que merecem morrer deverão ser executados por causa de seus próprios crimes".

[[v12-14-7]]

^<<v12-14-7,7>>^ Amazias também matou dez mil edomitas no vale do Sal. Conquistou a cidade de Selá e mudou seu nome para Jocteel, como se chama até hoje.

[[v12-14-8]]

^<<v12-14-8,8>>^ Certo dia, ele enviou mensageiros a Jeoás, filho de Jeoacaz, filho de Jeú, rei de Israel, com este desafio: "Venha enfrentar-me numa batalha!".

[[v12-14-9]]

^<<v12-14-9,9>>^ Mas Jeoás, rei de Israel, respondeu a Amazias, rei de Judá, com a seguinte história: "Nos montes do Líbano, o espinheiro enviou esta mensagem ao poderoso cedro: ‘Dê sua filha em casamento a meu filho’. No entanto, um animal selvagem do Líbano veio, pisoteou o espinheiro e o esmagou.

[[v12-14-10]]

^<<v12-14-10,10>>^ "De fato, você derrotou Edom e está orgulhoso disso. Mas contente-se com sua vitória e fique em casa! Por que trazer desgraça sobre você e o povo de Judá?".

[[v12-14-11]]

^<<v12-14-11,11>>^ Amazias, porém, se recusou a ouvir. Então Jeoás, rei de Israel, mobilizou seu exército contra Amazias, rei de Judá. Os dois exércitos se enfrentaram em Bete-Semes, em Judá.

[[v12-14-12]]

^<<v12-14-12,12>>^ O exército de Judá foi derrotado pelo exército de Israel, e os soldados fugiram para casa.

[[v12-14-13]]

^<<v12-14-13,13>>^ Jeoás, rei de Israel, capturou Amazias, filho de Joás, filho de Acazias, rei de Judá, em Bete-Semes. Em seguida, marchou para Jerusalém, onde destruiu 180 metros do muro da cidade, desde a porta de Efraim até a porta da Esquina.

[[v12-14-14]]

^<<v12-14-14,14>>^ Levou embora todo o ouro, toda a prata e todos os utensílios do templo do SENHOR. Também levou os tesouros do palácio real e fez reféns; depois, voltou para Samaria.

[[v12-14-15]]

^<<v12-14-15,15>>^ Os demais acontecimentos do reinado de Jeoás e tudo que ele fez, incluindo a extensão de seu poder e sua guerra contra Amazias, rei de Judá, estão registrados no Livro da História dos Reis de Israel .

[[v12-14-16]]

^<<v12-14-16,16>>^ Quando Jeoás morreu e se reuniu a seus antepassados, foi sepultado em Samaria, com os reis de Israel. Seu filho Jeroboão II foi seu sucessor.

[[v12-14-17]]

^<<v12-14-17,17>>^ Amazias, filho de Joás, rei de Judá, viveu ainda mais quinze anos depois da morte de Jeoás, filho de Jeoacaz, rei de Israel.

[[v12-14-18]]

^<<v12-14-18,18>>^ Os demais acontecimentos do reinado de Amazias estão registrados no Livro da História dos Reis de Judá .

[[v12-14-19]]

^<<v12-14-19,19>>^ Houve uma conspiração contra Amazias em Jerusalém, e ele fugiu para Laquis. Seus inimigos, porém, mandaram assassinos atrás dele e o mataram ali.

[[v12-14-20]]

^<<v12-14-20,20>>^ Seu corpo foi trazido de volta para Jerusalém num cavalo, e ele foi sepultado com seus antepassados na Cidade de Davi.

[[v12-14-21]]

^<<v12-14-21,21>>^ Todo o povo de Judá proclamou rei seu filho Uzias, de 16 anos, como sucessor de seu pai, Amazias.

[[v12-14-22]]

^<<v12-14-22,22>>^ Depois que seu pai morreu e se reuniu a seus antepassados, Uzias reconstruiu a cidade de Elate e a recuperou para Judá.

[[v12-14-23]]

^<<v12-14-23,23>>^ Jeroboão II, filho de Jeoás, começou a reinar em Israel no décimo quinto ano do reinado de Amazias, filho de Joás, rei de Judá. Reinou em Samaria por 41 anos.

[[v12-14-24]]

^<<v12-14-24,24>>^ Fez o que era mau aos olhos do SENHOR. Não se afastou dos pecados que Jeroboão, filho de Nebate, havia levado Israel a cometer.

[[v12-14-25]]

^<<v12-14-25,25>>^ Jeroboão II recuperou os territórios de Israel entre Lebo-Hamate e o mar Morto, conforme o SENHOR, o Deus de Israel, havia anunciado por meio de Jonas, filho de Amitai, profeta de Gate-Héfer.

[[v12-14-26]]

^<<v12-14-26,26>>^ O SENHOR viu como era grande o sofrimento em Israel, tanto para escravos como para livres, e não havia ninguém em Israel que pudesse socorrê-los.

[[v12-14-27]]

^<<v12-14-27,27>>^ E, porque o SENHOR não tinha dito que apagaria completamente o nome de Israel, usou Jeroboão II, filho de Jeoás, para socorrê-los.

[[v12-14-28]]

^<<v12-14-28,28>>^ Os demais acontecimentos do reinado de Jeroboão II, tudo que ele fez, a extensão de seu poder, as guerras que travou e como ele recuperou para Israel as cidades de Damasco e de Hamate, que haviam pertencido a Judá, estão registrados no Livro da História dos Reis de Israel .

[[v12-14-29]]

^<<v12-14-29,29>>^ Quando Jeroboão II morreu e se reuniu a seus antepassados, foi sepultado em Samaria, com os reis de Israel. Seu filho Zacarias foi seu sucessor.

'''

xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[&#60; Capítulo Anterior] | <<v12-14-0,Topo>> | xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[Próximo Capítulo &#62;]