include::./index.adoc[]

[[v12-8-0]]
=== 2 Reis, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v12-8-1]]

^<<v12-8-1,1>>^ Eliseu tinha dito à mulher cujo filho ele havia ressuscitado: "Reúna sua família e mude-se para outro lugar, pois o SENHOR proclamou sobre a terra de Israel uma fome que durará sete anos".

[[v12-8-2]]

^<<v12-8-2,2>>^ A mulher seguiu a instrução do homem de Deus. Reuniu sua família e mudou-se para a terra dos filisteus, onde ficou sete anos.

[[v12-8-3]]

^<<v12-8-3,3>>^ Ao final dos sete anos, a mulher voltou da terra dos filisteus e foi ao rei para reaver sua casa e suas terras.

[[v12-8-4]]

^<<v12-8-4,4>>^ Quando ela chegou, o rei falava com Geazi, o servo do homem de Deus. O rei havia acabado de dizer: "Conte-me alguns dos grandes feitos de Eliseu",

[[v12-8-5]]

^<<v12-8-5,5>>^ e Geazi lhe falava sobre a ocasião em que Eliseu havia ressuscitado um menino. Naquele exato momento, a mãe do menino entrou e apresentou ao rei sua petição para reaver a casa e as terras. "Veja, ó meu senhor, o rei!", exclamou Geazi. "Esta é a mulher, e este é o filho dela, que Eliseu ressuscitou!"

[[v12-8-6]]

^<<v12-8-6,6>>^ "É verdade?", perguntou o rei à mulher. E ela lhe contou o que havia acontecido. Então o rei ordenou a um de seus oficiais: "Providencie que tudo seja devolvido a ela, incluindo o valor das colheitas realizadas durante o tempo em que esteve ausente".

[[v12-8-7]]

^<<v12-8-7,7>>^ Eliseu foi a Damasco, capital da Síria, onde o rei Ben-Hadade estava doente. Quando alguém disse ao rei que o homem de Deus tinha chegado,

[[v12-8-8]]

^<<v12-8-8,8>>^ o rei disse a Hazael: "Leve um presente para o homem de Deus. Depois, peça que ele pergunte ao SENHOR se vou me recuperar desta doença".

[[v12-8-9]]

^<<v12-8-9,9>>^ Hazael levou consigo o presente, quarenta camelos carregados com os melhores produtos de Damasco. Foi vê-lo e disse: "Seu servo Ben-Hadade, rei da Síria, me enviou para perguntar se ele vai se recuperar de sua doença".

[[v12-8-10]]

^<<v12-8-10,10>>^ Eliseu respondeu: "Vá e diga-lhe: ‘Certamente se recuperará’. Na verdade, porém, o SENHOR me mostrou que ele certamente morrerá".

[[v12-8-11]]

^<<v12-8-11,11>>^ Eliseu olhou fixamente para Hazael até deixá-lo constrangido. Então o homem de Deus começou a chorar.

[[v12-8-12]]

^<<v12-8-12,12>>^ "Por que o senhor está chorando?", perguntou Hazael. Eliseu respondeu: "Sei das coisas terríveis que você fará com os israelitas. Queimará as cidades fortificadas, matará os jovens à espada, esmagará as criancinhas e rasgará o ventre das mulheres grávidas!".

[[v12-8-13]]

^<<v12-8-13,13>>^ Hazael disse: "Como é que alguém tão sem importância como eu poderia fazer coisas tão grandes?". Eliseu respondeu: "O SENHOR me mostrou que você será rei da Síria".

[[v12-8-14]]

^<<v12-8-14,14>>^ Hazael se despediu de Eliseu e, quando voltou, o rei lhe perguntou: "O que Eliseu lhe disse?". Hazael respondeu: "Disse que o senhor certamente se recuperará".

[[v12-8-15]]

^<<v12-8-15,15>>^ Mas, no dia seguinte, Hazael pegou uma coberta, encharcou-a em água e a segurou sobre o rosto do rei, até que morresse. E Hazael foi seu sucessor na Síria.

[[v12-8-16]]

^<<v12-8-16,16>>^ No quinto ano de Jorão, filho de Acabe, rei de Israel, enquanto Josafá ainda reinava em Judá, Jeorão, filho de Josafá, começou a reinar em Judá.

[[v12-8-17]]

^<<v12-8-17,17>>^ Jeorão tinha 32 anos quando começou a reinar, e reinou em Jerusalém por oito anos.

[[v12-8-18]]

^<<v12-8-18,18>>^ Seguiu o exemplo dos reis de Israel e foi tão perverso quanto a família do rei Acabe, pois se casou com uma das filhas de Acabe. Jeorão fez o que era mau aos olhos do SENHOR.

[[v12-8-19]]

^<<v12-8-19,19>>^ Mas o SENHOR não quis destruir Judá, pois havia prometido a seu servo Davi que os descendentes dele continuariam a brilhar como uma lâmpada para sempre.

[[v12-8-20]]

^<<v12-8-20,20>>^ Durante o reinado de Jeorão, os edomitas se rebelaram contra Judá e proclamaram seu próprio rei.

[[v12-8-21]]

^<<v12-8-21,21>>^ Então Jeorão saiu com todos os seus carros de guerra para atacar a cidade de Zair. Os edomitas cercaram o rei e os comandantes de seus carros, mas ele saiu à noite e os atacou. Contudo, o exército de Jeorão desertou e voltou para casa.

[[v12-8-22]]

^<<v12-8-22,22>>^ Até hoje, portanto, Edom é independente de Judá. A cidade de Libna também se rebelou nessa ocasião.

[[v12-8-23]]

^<<v12-8-23,23>>^ Os demais acontecimentos do reinado de Jeorão e tudo que ele fez estão registrados no Livro da História dos Reis de Judá .

[[v12-8-24]]

^<<v12-8-24,24>>^ Quando Jeorão morreu, foi sepultado com seus antepassados na Cidade de Davi. Seu filho Acazias foi seu sucessor.

[[v12-8-25]]

^<<v12-8-25,25>>^ Acazias, filho de Jeorão, começou a reinar em Judá no décimo segundo ano do reinado de Jorão, filho de Acabe, rei de Israel.

[[v12-8-26]]

^<<v12-8-26,26>>^ Acazias tinha 22 anos quando começou a reinar, e reinou em Jerusalém por um ano. Sua mãe era Atalia, neta de Onri, rei de Israel.

[[v12-8-27]]

^<<v12-8-27,27>>^ Acazias seguiu o exemplo da família do rei Acabe. Fez o que era mau aos olhos do SENHOR, como a família de Acabe, pois se casou com uma mulher dessa família.

[[v12-8-28]]

^<<v12-8-28,28>>^ Acazias se uniu a Jorão, filho de Acabe, na guerra contra Hazael, rei da Síria, em Ramote-Gileade. Quando os sírios feriram o rei Jorão na batalha,

[[v12-8-29]]

^<<v12-8-29,29>>^ ele voltou a Jezreel para se recuperar dos ferimentos sofridos em Ramote. Acazias, filho de Jeorão, rei de Judá, foi visitar Jorão, filho de Acabe, em Jezreel, pois ele ainda se recuperava de seus ferimentos.

'''

xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[Próximo Capítulo &#62;]