include::./index.adoc[]

[[v12-10-0]]
=== 2 Reis, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v12-10-1]]

^<<v12-10-1,1>>^ Acabe tinha setenta filhos que moravam na cidade de Samaria. Jeú escreveu uma carta às autoridades e aos oficiais da cidade e aos guardiões dos filhos do rei Acabe, em que dizia:

[[v12-10-2]]

^<<v12-10-2,2>>^ "Os filhos do rei estão sob seus cuidados, e vocês têm carros de guerra, cavalos, uma cidade fortificada e armas. Assim que receberem esta carta,

[[v12-10-3]]

^<<v12-10-3,3>>^ escolham para ser rei o melhor e mais capaz dos filhos de seu senhor e preparem-se para lutar pela dinastia de Acabe".

[[v12-10-4]]

^<<v12-10-4,4>>^ Eles ficaram apavorados e disseram: "Dois reis não foram capazes de enfrentar esse homem! O que podemos fazer?".

[[v12-10-5]]

^<<v12-10-5,5>>^ Então os administradores do palácio e da cidade, juntamente com as autoridades e os guardiões dos filhos do rei, enviaram esta mensagem a Jeú: "Somos seus servos e faremos o que o senhor ordenar. Não proclamaremos nenhum rei; faça o que lhe parecer melhor".

[[v12-10-6]]

^<<v12-10-6,6>>^ Jeú respondeu com outra carta: "Se estão do meu lado e vão me obedecer, tragam-me as cabeças dos filhos de seu senhor a Jezreel, amanhã a esta hora". Os setenta filhos de Acabe estavam sob os cuidados dos líderes de Samaria, onde haviam sido criados desde a infância.

[[v12-10-7]]

^<<v12-10-7,7>>^ Quando a carta chegou, os líderes mataram os setenta filhos do rei. Colocaram as cabeças em cestos e as entregaram a Jeú, em Jezreel.

[[v12-10-8]]

^<<v12-10-8,8>>^ Um mensageiro foi a Jeú e disse: "Eles trouxeram as cabeças dos filhos do rei". Então Jeú ordenou: "Façam com elas dois montões junto ao portão de entrada da cidade e deixem que fiquem lá até amanhã cedo".

[[v12-10-9]]

^<<v12-10-9,9>>^ Na manhã seguinte, ele saiu e se dirigiu à multidão que havia se reunido ali. "Vocês não têm culpa", disse ele. "Eu conspirei contra meu senhor e o matei. Mas quem matou todos estes?

[[v12-10-10]]

^<<v12-10-10,10>>^ Podem ter certeza de que a mensagem do SENHOR a respeito da família de Acabe se cumprirá. O SENHOR declarou por meio de seu servo Elias que isso aconteceria."

[[v12-10-11]]

^<<v12-10-11,11>>^ Então Jeú matou todos os parentes de Acabe que restavam em Jezreel e todos os seus oficiais mais importantes, seus amigos pessoais e seus sacerdotes. Nenhum descendente de Acabe sobreviveu.

[[v12-10-12]]

^<<v12-10-12,12>>^ Depois, Jeú partiu para Samaria. No caminho, em Bete-Equede dos Pastores,

[[v12-10-13]]

^<<v12-10-13,13>>^ encontrou alguns parentes de Acazias, rei de Judá. "Quem são vocês?", perguntou. Eles responderam: "Somos parentes do rei Acazias. Vamos visitar a família do rei Acabe e da rainha-mãe".

[[v12-10-14]]

^<<v12-10-14,14>>^ "Prendam-nos vivos!", ordenou Jeú a seus homens. Eles os capturaram, 42 pessoas ao todo, e os mataram junto ao poço de Bete-Equede. Nenhum deles escapou.

[[v12-10-15]]

^<<v12-10-15,15>>^ Quando Jeú partiu dali, encontrou Jonadabe, filho de Recabe, que vinha falar com ele. Depois de cumprimentá-lo, Jeú lhe disse: "Você é leal a mim como sou a você?". "Sim, eu sou", respondeu Jonadabe. "Então dê-me sua mão", disse Jeú. Jonadabe estendeu a mão, e Jeú o ajudou a subir à carruagem.

[[v12-10-16]]

^<<v12-10-16,16>>^ E lhe disse: "Venha comigo, e você verá a minha dedicação ao SENHOR". Jonadabe foi com ele.

[[v12-10-17]]

^<<v12-10-17,17>>^ Quando Jeú chegou a Samaria, matou todos que restavam ali da família de Acabe, como o SENHOR havia anunciado por meio de Elias.

[[v12-10-18]]

^<<v12-10-18,18>>^ Jeú reuniu todo o povo da cidade e lhes disse: "A adoração de Acabe a Baal não foi nada comparado ao modo como eu o adorarei!

[[v12-10-19]]

^<<v12-10-19,19>>^ Portanto, convoquem todos os profetas e adoradores de Baal e reúnam todos os seus sacerdotes. Todos devem vir, pois vou oferecer um grande sacrifício a Baal. Quem não comparecer será morto". O plano astuto de Jeú, porém, era destruir todos os adoradores de Baal.

[[v12-10-20]]

^<<v12-10-20,20>>^ Então Jeú ordenou: "Preparem uma reunião solene para prestar culto a Baal!". A convocação foi feita,

[[v12-10-21]]

^<<v12-10-21,21>>^ e ele enviou mensageiros por todo o Israel. Todos os adoradores de Baal vieram, e ninguém faltou. Encheram o templo de Baal de uma extremidade à outra.

[[v12-10-22]]

^<<v12-10-22,22>>^ Jeú instruiu o responsável pela sala de vestimentas: "Todos os adoradores de Baal devem usar estas roupas". E as roupas foram distribuídas.

[[v12-10-23]]

^<<v12-10-23,23>>^ Em seguida, Jeú entrou no templo de Baal com Jonadabe, filho de Recabe. Disse aos adoradores de Baal: "Certifiquem-se de que ninguém que adora o SENHOR esteja aqui, mas somente aqueles que adoram Baal".

[[v12-10-24]]

^<<v12-10-24,24>>^ Estavam todos dentro do templo para oferecer sacrifícios e holocaustos. Jeú havia colocado oitenta homens do lado de fora do edifício e os avisado: "Se deixarem alguém escapar, pagarão com a própria vida".

[[v12-10-25]]

^<<v12-10-25,25>>^ Assim que Jeú terminou de oferecer o holocausto, deu ordem a seus guardas e oficiais: "Entrem e matem todos. Não deixem ninguém escapar!". Os guardas e os oficiais mataram todos e arrastaram os corpos para fora. Então os homens de Jeú entraram na câmara mais interna do templo de Baal.

[[v12-10-26]]

^<<v12-10-26,26>>^ Levaram para fora a coluna sagrada usada no culto a Baal e a jogaram no fogo.

[[v12-10-27]]

^<<v12-10-27,27>>^ Despedaçaram a coluna sagrada, demoliram o templo de Baal e o transformaram em banheiros públicos, como é até hoje.

[[v12-10-28]]

^<<v12-10-28,28>>^ Desse modo, Jeú destruiu todos os vestígios do culto a Baal em Israel.

[[v12-10-29]]

^<<v12-10-29,29>>^ Contudo, não destruiu os bezerros de ouro em Betel e Dã com os quais Jeroboão, filho de Nebate, havia levado Israel a pecar.

[[v12-10-30]]

^<<v12-10-30,30>>^ Ainda assim, o SENHOR disse a Jeú: "Você fez bem em seguir minhas instruções e destruir a família de Acabe. Por isso, seus descendentes serão reis de Israel até a quarta geração".

[[v12-10-31]]

^<<v12-10-31,31>>^ Mas Jeú não obedeceu de todo o coração à lei do SENHOR, o Deus de Israel. Não se afastou dos pecados que Jeroboão havia levado Israel a cometer.

[[v12-10-32]]

^<<v12-10-32,32>>^ Naquele tempo, o SENHOR começou a reduzir o território de Israel. O rei Hazael conquistou várias regiões do reino

[[v12-10-33]]

^<<v12-10-33,33>>^ a leste do rio Jordão, incluindo toda a terra de Gileade, de Gade, de Rúben e de Manassés. Conquistou a região desde a cidade de Aroer, perto do vale do Arnom, até Gileade e Basã, ao norte.

[[v12-10-34]]

^<<v12-10-34,34>>^ Os demais acontecimentos do reinado de Jeú, tudo que ele fez e a extensão de seu poder, estão registrados no Livro da História dos Reis de Israel .

[[v12-10-35]]

^<<v12-10-35,35>>^ Quando Jeú morreu e se reuniu a seus antepassados, foi sepultado em Samaria. Seu filho Jeoacaz foi seu sucessor.

[[v12-10-36]]

^<<v12-10-36,36>>^ Ao todo, Jeú reinou por 28 anos sobre Israel em Samaria.

'''

xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[&#60; Capítulo Anterior] | <<v12-10-0,Topo>> | xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[Próximo Capítulo &#62;]