include::./index.adoc[]

[[v12-24-0]]
=== 2 Reis, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v12-24-1]]

^<<v12-24-1,1>>^ Durante o reinado de Jeoaquim, Nabucodonosor, rei da Babilônia, invadiu a terra de Judá. Jeoaquim se rendeu e lhe pagou tributo por três anos, mas depois se rebelou.

[[v12-24-2]]

^<<v12-24-2,2>>^ Então o SENHOR enviou bandos de saqueadores babilônios, sírios, moabitas e amonitas contra o reino de Judá para destruí-lo, como tinha anunciado por meio de seus profetas.

[[v12-24-3]]

^<<v12-24-3,3>>^ Essas desgraças aconteceram a Judá por ordem do SENHOR. Ele havia resolvido expulsar Judá de sua presença por causa dos muitos pecados de Manassés,

[[v12-24-4]]

^<<v12-24-4,4>>^ que havia enchido Jerusalém de sangue inocente. O SENHOR não perdoou esse pecado.

[[v12-24-5]]

^<<v12-24-5,5>>^ Os demais acontecimentos do reinado de Jeoaquim e tudo que ele fez estão registrados no Livro da História dos Reis de Judá .

[[v12-24-6]]

^<<v12-24-6,6>>^ Quando Jeoaquim morreu e se reuniu a seus antepassados, seu filho Joaquim foi seu sucessor.

[[v12-24-7]]

^<<v12-24-7,7>>^ Depois disso, o rei do Egito não se atreveu a sair de suas fronteiras, pois o rei da Babilônia conquistou toda a região que antes havia pertencido ao Egito, desde o ribeiro do Egito até o rio Eufrates.

[[v12-24-8]]

^<<v12-24-8,8>>^ Joaquim tinha 18 anos quando começou a reinar, e reinou em Jerusalém por três meses. Sua mãe se chamava Neústa e era filha de Elnatã, de Jerusalém.

[[v12-24-9]]

^<<v12-24-9,9>>^ Fez o que era mau aos olhos do SENHOR, como seus antepassados.

[[v12-24-10]]

^<<v12-24-10,10>>^ Durante o reinado de Joaquim, os oficiais de Nabucodonosor, rei da Babilônia, subiram contra Jerusalém e a cercaram.

[[v12-24-11]]

^<<v12-24-11,11>>^ O próprio Nabucodonosor chegou à cidade durante o cerco.

[[v12-24-12]]

^<<v12-24-12,12>>^ Então Joaquim, rei de Judá, a rainha-mãe, os conselheiros, os comandantes e os oficiais se renderam aos babilônios. No oitavo ano de seu reinado, Nabucodonosor levou Joaquim como prisioneiro.

[[v12-24-13]]

^<<v12-24-13,13>>^ Conforme o SENHOR havia declarado de antemão, Nabucodonosor levou embora todos os tesouros do templo do SENHOR e do palácio real. Removeu todos os utensílios de ouro que Salomão, rei de Israel, havia colocado no templo.

[[v12-24-14]]

^<<v12-24-14,14>>^ O rei Nabucodonosor deportou gente de toda a cidade de Jerusalém, incluindo todos os comandantes e os melhores soldados, artífices e ferreiros, dez mil pessoas ao todo. Só ficaram na terra os mais pobres.

[[v12-24-15]]

^<<v12-24-15,15>>^ Nabucodonosor levou cativos para a Babilônia o rei Joaquim, a rainha-mãe, as esposas e os oficiais do rei e todos os nobres de Jerusalém.

[[v12-24-16]]

^<<v12-24-16,16>>^ Também deportou sete mil soldados, todos fortes e aptos para a guerra, além de mil artífices e ferreiros.

[[v12-24-17]]

^<<v12-24-17,17>>^ Então o rei da Babilônia escolheu Matanias, tio de Joaquim, como rei de Judá e mudou o nome dele para Zedequias.

[[v12-24-18]]

^<<v12-24-18,18>>^ Zedequias tinha 21 anos quando começou a reinar, e reinou em Jerusalém por onze anos. Sua mãe se chamava Hamutal e era filha de Jeremias, de Libna.

[[v12-24-19]]

^<<v12-24-19,19>>^ Fez o que era mau aos olhos do SENHOR, como Jeoaquim antes dele.

[[v12-24-20]]

^<<v12-24-20,20>>^ Estas coisas aconteceram por causa da ira do SENHOR contra o povo de Jerusalém e de Judá. Por fim, ele os expulsou de sua presença e os mandou para o exílio. Zedequias se rebelou contra o rei da Babilônia.

'''

xref:012-2-reis/012-2-reis-023.adoc#v12-23-0[&#60; Capítulo Anterior] | <<v12-24-0,Topo>> | xref:012-2-reis/012-2-reis-025.adoc#v12-25-0[Próximo Capítulo &#62;]