include::./index.adoc[]

[[v12-3-0]]
=== 2 Reis, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v12-3-1]]

^<<v12-3-1,1>>^ Jorão, filho de Acabe, começou a reinar em Israel no décimo oitavo ano do reinado de Josafá, rei de Judá. Reinou em Samaria por doze anos.

[[v12-3-2]]

^<<v12-3-2,2>>^ Fez o que era mau aos olhos do SENHOR, mas não tanto quanto seu pai e sua mãe. Pelo menos derrubou a coluna sagrada de Baal que seu pai havia levantado.

[[v12-3-3]]

^<<v12-3-3,3>>^ Contudo, persistiu nos pecados que Jeroboão, filho de Nebate, havia cometido e levado o povo de Israel a cometer.

[[v12-3-4]]

^<<v12-3-4,4>>^ Messa, rei de Moabe, era criador de ovelhas. Costumava pagar ao rei de Israel um tributo anual de cem mil cordeiros e a lã de cem mil carneiros.

[[v12-3-5]]

^<<v12-3-5,5>>^ Depois da morte de Acabe, porém, o rei de Moabe se rebelou contra o rei de Israel.

[[v12-3-6]]

^<<v12-3-6,6>>^ Então, sem demora, o rei Jorão partiu de Samaria e reuniu o exército de Israel.

[[v12-3-7]]

^<<v12-3-7,7>>^ No caminho, enviou esta mensagem a Josafá, rei de Judá: "O rei de Moabe se rebelou contra mim. Você sairá comigo para batalhar contra ele?". Josafá respondeu: "Claro que sim! Meus soldados são seus soldados, e meus cavalos são seus cavalos".

[[v12-3-8]]

^<<v12-3-8,8>>^ E perguntou: "Que caminho vamos tomar?". "Vamos atacar pelo deserto de Edom", respondeu o rei de Israel.

[[v12-3-9]]

^<<v12-3-9,9>>^ O rei de Edom e seus soldados se uniram ao rei de Israel e ao rei de Judá, e os três exércitos seguiram pelo caminho. Depois que andaram sete dias pelo deserto, já não havia água para os homens nem para os animais.

[[v12-3-10]]

^<<v12-3-10,10>>^ "O que vamos fazer?", exclamou o rei de Israel. "Será que o SENHOR trouxe os três reis até aqui só para permitir que o rei de Moabe nos derrote?"

[[v12-3-11]]

^<<v12-3-11,11>>^ Então Josafá perguntou: "Não há aqui um profeta do SENHOR? Se houver, podemos consultar o SENHOR por meio dele". Um dos oficiais do rei de Israel respondeu: "Eliseu, filho de Safate, está aqui. Ele era o ajudante de Elias".

[[v12-3-12]]

^<<v12-3-12,12>>^ "Sim, o SENHOR fala por meio dele", disse Josafá. Então o rei de Israel, Josafá, o rei de Judá, e o rei de Edom foram consultar Eliseu.

[[v12-3-13]]

^<<v12-3-13,13>>^ "Por que veio me procurar?", perguntou Eliseu ao rei de Israel. "Vá consultar os profetas idólatras de seu pai e de sua mãe!"

[[v12-3-14]]

^<<v12-3-14,14>>^ Eliseu respondeu: "Tão certo como vive o SENHOR dos Exércitos, a quem sirvo, eu não lhe daria atenção alguma se não fosse por respeito a Josafá, rei de Judá.

[[v12-3-15]]

^<<v12-3-15,15>>^ Agora, tragam-me alguém que saiba tocar harpa". Enquanto o músico tocava, a mão do SENHOR veio sobre Eliseu,

[[v12-3-16]]

^<<v12-3-16,16>>^ e ele disse: "Assim diz o SENHOR: ‘Este vale seco se encherá de poços de água!’.

[[v12-3-17]]

^<<v12-3-17,17>>^ Pois assim diz o SENHOR: ‘Vocês não verão vento nem chuva, mas o vale se encherá de água. Terão o suficiente para vocês, seus rebanhos e outros animais’.

[[v12-3-18]]

^<<v12-3-18,18>>^ E, como se isso não bastasse, o SENHOR ainda entregará o exército de Moabe em suas mãos!

[[v12-3-19]]

^<<v12-3-19,19>>^ Vocês conquistarão as melhores cidades deles, até mesmo as fortificadas. Cortarão as árvores frutíferas, taparão todas as fontes e entulharão com pedras as terras de plantio".

[[v12-3-20]]

^<<v12-3-20,20>>^ No dia seguinte, por volta da hora em que se oferecia o sacrifício da manhã, começou a aparecer água, descendo desde Edom, e, em pouco tempo, havia água por toda parte.

[[v12-3-21]]

^<<v12-3-21,21>>^ Enquanto isso, o povo de Moabe soube que os três exércitos marchavam contra eles, e todos os homens com idade suficiente para lutar foram convocados e se posicionaram ao longo da fronteira.

[[v12-3-22]]

^<<v12-3-22,22>>^ Quando se levantaram na manhã seguinte, o sol brilhava sobre a água. Para os moabitas, ela parecia vermelha como sangue.

[[v12-3-23]]

^<<v12-3-23,23>>^ "É sangue!", exclamaram. "Os três exércitos atacaram uns aos outros e se mataram! Venha, povo de Moabe, vamos tomar os despojos!"

[[v12-3-24]]

^<<v12-3-24,24>>^ Mas, quando os moabitas chegaram ao acampamento de Israel, o exército israelita se levantou e os atacou até que deram meia-volta e fugiram. Os israelitas os perseguiram até Moabe, avançando pelo território e derrotando Moabe definitivamente.

[[v12-3-25]]

^<<v12-3-25,25>>^ Arrasaram as cidades, entulharam com pedras as terras de plantio, taparam as fontes de água e cortaram as árvores frutíferas. Por fim, só restou Quir-Haresete com suas muralhas de pedra, mas atiradores com fundas a cercaram e a atacaram.

[[v12-3-26]]

^<<v12-3-26,26>>^ Quando o rei de Moabe percebeu que estava perdendo a batalha, liderou setecentos homens com espadas, numa tentativa de romper as linhas inimigas próximas do rei de Edom, mas fracassou.

[[v12-3-27]]

^<<v12-3-27,27>>^ Então o rei de Moabe pegou seu filho mais velho, que devia sucedê-lo, e o ofereceu como holocausto sobre o muro da cidade. Por isso, houve grande ira contra Israel, e os israelitas se retiraram e voltaram para sua terra.

'''

xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[&#60; Capítulo Anterior] | <<v12-3-0,Topo>> | xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[Próximo Capítulo &#62;]