include::./index.adoc[]

[[v12-25-0]]
=== 2 Reis, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v12-25-1]]

^<<v12-25-1,1>>^ Assim, em 15 de janeiro, durante o nono ano do reinado de Zedequias, Nabucodonosor, rei da Babilônia, e todo o seu exército cercaram Jerusalém e construíram rampas de ataque contra os muros.

[[v12-25-2]]

^<<v12-25-2,2>>^ Jerusalém permaneceu cercada até o décimo primeiro ano do reinado de Zedequias.

[[v12-25-3]]

^<<v12-25-3,3>>^ Em 18 de julho, no décimo primeiro ano do reinado de Zedequias, a fome na cidade tinha se tornado tão severa que não havia mais nenhum alimento.

[[v12-25-4]]

^<<v12-25-4,4>>^ Assim, abriram uma brecha no muro da cidade. Como a cidade estava cercada pelos babilônios, os soldados esperaram até o anoitecer e fugiram pelo portão entre os dois muros atrás do jardim do rei. Então seguiram em direção ao vale do Jordão.

[[v12-25-5]]

^<<v12-25-5,5>>^ Contudo, o exército babilônio perseguiu o rei e o alcançou nas planícies de Jericó, pois todos os seus soldados o haviam abandonado e se dispersado.

[[v12-25-6]]

^<<v12-25-6,6>>^ Capturaram Zedequias e o levaram ao rei da Babilônia, em Ribla, onde ele recebeu sua sentença.

[[v12-25-7]]

^<<v12-25-7,7>>^ Mataram seus filhos diante dele, depois lhe arrancaram os olhos, o prenderam com correntes de bronze e o levaram para a Babilônia.

[[v12-25-8]]

^<<v12-25-8,8>>^ Em 14 de agosto daquele ano, o décimo nono do reinado de Nabucodonosor, Nebuzaradã, capitão da guarda e oficial do rei da Babilônia, chegou a Jerusalém.

[[v12-25-9]]

^<<v12-25-9,9>>^ Queimou o templo do SENHOR, o palácio real e todas as casas de Jerusalém. Pôs fogo em todos os edifícios importantes da cidade.

[[v12-25-10]]

^<<v12-25-10,10>>^ Depois supervisionou o exército babilônio na demolição de todos os muros de Jerusalém.

[[v12-25-11]]

^<<v12-25-11,11>>^ Em seguida, Nebuzaradã, capitão da guarda, deportou o povo que havia ficado na cidade, os desertores que se entregaram ao rei da Babilônia e o restante da população.

[[v12-25-12]]

^<<v12-25-12,12>>^ Permitiu, no entanto, que alguns dos mais pobres ficassem para cuidar das videiras e dos campos.

[[v12-25-13]]

^<<v12-25-13,13>>^ Os babilônios despedaçaram as colunas de bronze na frente do templo do SENHOR, as bases móveis de bronze e o grande tanque de bronze chamado Mar, e levaram todo o bronze para a Babilônia.

[[v12-25-14]]

^<<v12-25-14,14>>^ Também levaram os baldes para cinzas, as pás, os cortadores de pavios, as colheres e todos os outros utensílios de bronze usados para o serviço no templo.

[[v12-25-15]]

^<<v12-25-15,15>>^ O capitão da guarda levou ainda os incensários e as bacias e todos os outros utensílios de ouro puro ou prata.

[[v12-25-16]]

^<<v12-25-16,16>>^ Era impossível calcular o peso do bronze das duas colunas, do Mar e das bases móveis para levar água. Esses objetos tinham sido feitos para o templo do SENHOR nos dias de Salomão.

[[v12-25-17]]

^<<v12-25-17,17>>^ Cada coluna media 8,1 metros de altura. O capitel de bronze no alto de cada coluna media cerca de 2,25 metros de altura e era enfeitado ao redor com correntes entrelaçadas de romãs feitas de bronze.

[[v12-25-18]]

^<<v12-25-18,18>>^ O capitão da guarda levou como prisioneiros o sumo sacerdote Seraías, o sacerdote auxiliar Sofonias e três dos principais guardas das portas.

[[v12-25-19]]

^<<v12-25-19,19>>^ Dentre o povo que ainda estava escondido na cidade, levou um oficial responsável pelo exército de Judá, cinco dos conselheiros pessoais do rei; o secretário do comandante do exército, que era encarregado do alistamento de soldados, e outros sessenta homens do povo.

[[v12-25-20]]

^<<v12-25-20,20>>^ Nebuzaradã, capitão da guarda, levou-os ao rei da Babilônia, em Ribla.

[[v12-25-21]]

^<<v12-25-21,21>>^ E ali em Ribla, na terra de Hamate, o rei da Babilônia mandou executá-los. Assim, o povo de Judá foi enviado para o exílio, para longe de sua terra.

[[v12-25-22]]

^<<v12-25-22,22>>^ Nabucodonosor, rei da Babilônia, nomeou Gedalias, filho de Aicam, filho de Safã, como governador do povo que ele havia deixado em Judá.

[[v12-25-23]]

^<<v12-25-23,23>>^ Quando os comandantes do exército e seus homens souberam que o rei da Babilônia havia nomeado Gedalias governador, foram vê-lo em Mispá. Entre eles estavam Ismael, filho de Netanias, Joanã, filho de Careá, Seraías, filho do netofatita Tanumete, Jezanias, filho do maacatita, e todos os seus homens.

[[v12-25-24]]

^<<v12-25-24,24>>^ Gedalias jurou a eles que os oficiais babilônios não tinham intenção de lhes fazer nenhum mal. "Não tenham medo deles", disse. "Vivam na terra e sirvam ao rei da Babilônia, e tudo lhes irá bem."

[[v12-25-25]]

^<<v12-25-25,25>>^ Mas, no sétimo mês desse mesmo ano, Ismael, filho de Netanias, filho de Elisama, que era da família real, foi com dez homens a Mispá e matou Gedalias. Também matou todos os judeus e babilônios que estavam com ele em Mispá.

[[v12-25-26]]

^<<v12-25-26,26>>^ Então todo o povo de Judá, dos mais simples até os mais importantes, bem como os comandantes do exército, fugiu para o Egito, com medo do que os babilônios lhe fariam.

[[v12-25-27]]

^<<v12-25-27,27>>^ No trigésimo sétimo ano do exílio de Joaquim, rei de Judá, Evil-Merodaque começou a reinar na Babilônia. Foi bondoso com Joaquim e o libertou da prisão em 2 de abril daquele ano.

[[v12-25-28]]

^<<v12-25-28,28>>^ Falou com ele gentilmente e o colocou num lugar mais elevado que o de outros reis exilados na Babilônia.

[[v12-25-29]]

^<<v12-25-29,29>>^ Providenciou roupas novas para Joaquim, no lugar das roupas de prisioneiro, e permitiu que ele comesse na presença do rei enquanto vivesse.

[[v12-25-30]]

^<<v12-25-30,30>>^ Assim o rei lhe deu uma provisão diária de alimento pelo resto de sua vida.

'''

xref:012-2-reis/012-2-reis-024.adoc#v12-24-0[&#60; Capítulo Anterior] | <<v12-25-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-001.adoc#v13-1-0[Próximo Capítulo &#62;]