include::./index.adoc[]

[[v12-6-0]]
=== 2 Reis, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v12-6-1]]

^<<v12-6-1,1>>^ Certo dia, os membros do grupo de profetas disseram a Eliseu: "Como vê, este lugar onde nos reunimos é pequeno demais.

[[v12-6-2]]

^<<v12-6-2,2>>^ Vamos descer ao rio Jordão, onde há muitos troncos, e construir ali um lugar para nos reunirmos". "Está bem", disse Eliseu. "Podem ir."

[[v12-6-3]]

^<<v12-6-3,3>>^ "Venha conosco", sugeriu um deles. "Eu irei", disse ele.

[[v12-6-4]]

^<<v12-6-4,4>>^ E foi com eles. Quando chegaram ao Jordão, começaram a derrubar árvores.

[[v12-6-5]]

^<<v12-6-5,5>>^ Enquanto um deles cortava um tronco, a parte de ferro do machado caiu no rio. "Ai, meu senhor!", gritou. "O machado era emprestado!"

[[v12-6-6]]

^<<v12-6-6,6>>^ "Onde caiu?", perguntou o homem de Deus. Quando mostraram o lugar para Eliseu, ele cortou um galho e o jogou na água, e fez o ferro do machado flutuar.

[[v12-6-7]]

^<<v12-6-7,7>>^ "Pegue-o", disse Eliseu. E o homem estendeu a mão e o pegou.

[[v12-6-8]]

^<<v12-6-8,8>>^ Quando o rei da Síria estava em guerra contra Israel, consultava seus oficiais e dizia: "Posicionaremos nossas tropas em tal lugar".

[[v12-6-9]]

^<<v12-6-9,9>>^ De imediato, o homem de Deus advertia o rei de Israel: "Não se aproxime de tal lugar, pois os sírios planejam posicionar suas tropas ali".

[[v12-6-10]]

^<<v12-6-10,10>>^ E o rei de Israel mandava um aviso para o lugar indicado pelo homem de Deus. Várias vezes ele advertiu o rei de que ficasse alerta naqueles lugares.

[[v12-6-11]]

^<<v12-6-11,11>>^ Furioso com essa situação, o rei sírio reuniu seus oficiais e perguntou: "Qual de vocês anda informando o rei de Israel sobre meus planos?".

[[v12-6-12]]

^<<v12-6-12,12>>^ "Ó meu senhor, o rei, não somos nós", respondeu um dos oficiais. "Eliseu, o profeta de Israel, revela ao rei de Israel até as palavras que o senhor diz em seus aposentos!"

[[v12-6-13]]

^<<v12-6-13,13>>^ O rei ordenou: "Vão e descubram onde ele está, para que eu mande capturá-lo!". Então lhe informaram: "Eliseu está em Dotã".

[[v12-6-14]]

^<<v12-6-14,14>>^ Assim, certa noite, o rei da Síria mandou um grande exército com muitos carros de guerra e cavalos para cercar a cidade.

[[v12-6-15]]

^<<v12-6-15,15>>^ Na manhã seguinte, o servo do homem de Deus se levantou bem cedo. Ao sair, viu que havia soldados, cavalos e carros de guerra por toda parte. "Ai, meu senhor, o que faremos agora?", exclamou o servo.

[[v12-6-16]]

^<<v12-6-16,16>>^ "Não tenha medo!", disse Eliseu. "Pois do nosso lado há muitos mais que do lado deles!"

[[v12-6-17]]

^<<v12-6-17,17>>^ Então Eliseu orou: "Ó SENHOR, abre os olhos dele, para que veja". O SENHOR abriu os olhos do servo, e ele viu as colinas ao redor de Eliseu cheias de cavalos e carruagens de fogo.

[[v12-6-18]]

^<<v12-6-18,18>>^ Quando os sírios avançaram na direção de Eliseu, ele orou: "Ó SENHOR, faze que fiquem cegos". E o SENHOR fez que ficassem cegos, conforme Eliseu havia pedido.

[[v12-6-19]]

^<<v12-6-19,19>>^ Então Eliseu saiu e lhes disse: "Vocês tomaram o caminho errado! Esta não é a cidade certa! Sigam-me, e eu os levarei até o homem que procuram". Então ele os guiou à cidade de Samaria.

[[v12-6-20]]

^<<v12-6-20,20>>^ Assim que entraram em Samaria, Eliseu orou: "Ó SENHOR, agora abre os olhos deles, para que vejam". O SENHOR abriu os olhos deles, e descobriram que estavam no meio de Samaria.

[[v12-6-21]]

^<<v12-6-21,21>>^ Quando o rei de Israel os viu, perguntou a Eliseu: "Devo matá-los, meu senhor? Devo matá-los?".

[[v12-6-22]]

^<<v12-6-22,22>>^ "Claro que não!", respondeu Eliseu. "Eles não são prisioneiros que você capturou na batalha. Dê-lhes comida e bebida e mande-os de volta para casa, para o senhor deles."

[[v12-6-23]]

^<<v12-6-23,23>>^ Então o rei lhes ofereceu um grande banquete e os mandou de volta para casa, para o senhor deles. Depois disso, os invasores sírios não invadiram mais a terra de Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ Algum tempo depois, porém, Ben-Hadade, rei da Síria, reuniu todo o seu exército e cercou Samaria.

[[v12-6-25]]

^<<v12-6-25,25>>^ Como resultado, houve grande fome na cidade. O cerco durou tanto tempo que uma cabeça de jumento era vendida por 960 gramas de prata, e um terço de litro de esterco de pombo, por 60 gramas de prata.

[[v12-6-26]]

^<<v12-6-26,26>>^ Um dia, quando o rei de Israel caminhava pelos muros da cidade, uma mulher gritou para ele: "Ó meu senhor, o rei! Por favor, ajude-me!".

[[v12-6-27]]

^<<v12-6-27,27>>^ Ele respondeu: "Se o SENHOR não a ajudar, o que poderei fazer? Não tenho alimento na eira, nem vinho na prensa de uvas".

[[v12-6-28]]

^<<v12-6-28,28>>^ Mas depois o rei perguntou: "Qual é o problema?". Ela respondeu: "Esta mulher me disse: ‘Vamos comer o seu filho hoje, e amanhã comeremos o meu’.

[[v12-6-29]]

^<<v12-6-29,29>>^ Então cozinhamos meu filho e o comemos. No dia seguinte, eu disse a ela: ‘Mate seu filho para que o comamos’, mas ela o havia escondido".

[[v12-6-30]]

^<<v12-6-30,30>>^ Quando o rei ouviu isso, rasgou as roupas. E, enquanto ele caminhava pelos muros, o povo viu que, por baixo do manto, ele usava pano de saco junto à pele.

[[v12-6-31]]

^<<v12-6-31,31>>^ Então o rei jurou: "Que Deus me castigue severamente se eu não separar a cabeça de Eliseu de seus ombros ainda hoje!".

[[v12-6-32]]

^<<v12-6-32,32>>^ Eliseu estava sentado em sua casa com as autoridades de Israel quando o rei mandou um mensageiro até ele. Antes, porém, que o mensageiro chegasse, Eliseu disse às autoridades: "O filho do assassino enviou um homem para cortar minha cabeça. Quando o mensageiro chegar, fechem a porta e não o deixem entrar. Logo ouviremos os passos de seu senhor atrás dele".

[[v12-6-33]]

^<<v12-6-33,33>>^ Enquanto Eliseu ainda falava, o mensageiro chegou e comunicou a mensagem do rei: "Toda essa desgraça vem do SENHOR! Por que devo continuar a esperar no SENHOR?".

'''

xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[Próximo Capítulo &#62;]