include::./index.adoc[]

[[v12-18-0]]
=== 2 Reis, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v12-18-1]]

^<<v12-18-1,1>>^ Ezequias, filho de Acaz, começou a reinar em Judá no terceiro ano do reinado de Oseias, filho de Elá, rei de Israel.

[[v12-18-2]]

^<<v12-18-2,2>>^ Tinha 25 anos quando começou a reinar, e reinou em Jerusalém por 29 anos. Sua mãe se chamava Abi e era filha de Zacarias.

[[v12-18-3]]

^<<v12-18-3,3>>^ Ezequias fez o que era certo aos olhos do SENHOR, como seu antepassado Davi.

[[v12-18-4]]

^<<v12-18-4,4>>^ Removeu os santuários idólatras, quebrou as colunas sagradas e derrubou os postes de Aserá. Despedaçou a serpente de bronze que Moisés havia feito, pois os israelitas queimavam incenso para ela. A serpente de bronze se chamava Neustã.

[[v12-18-5]]

^<<v12-18-5,5>>^ Ezequias confiava no SENHOR, o Deus de Israel. Não houve ninguém como ele entre todos os reis de Judá, nem antes nem depois.

[[v12-18-6]]

^<<v12-18-6,6>>^ Ezequias se apegou ao SENHOR, não se afastou dele e teve o cuidado de obedecer a todos os mandamentos que o SENHOR tinha ordenado por meio de Moisés.

[[v12-18-7]]

^<<v12-18-7,7>>^ Assim, o SENHOR estava com Ezequias, e ele era bem-sucedido em tudo que fazia. Rebelou-se contra o rei da Assíria e não lhe pagou tributo.

[[v12-18-8]]

^<<v12-18-8,8>>^ Derrotou os filisteus até Gaza e seu território, desde o menor posto de vigilância até a maior cidade fortificada.

[[v12-18-9]]

^<<v12-18-9,9>>^ No quarto ano do reinado de Ezequias, o sétimo ano do reinado de Oseias, filho de Elá, rei de Israel, Salmaneser, rei da Assíria, atacou a cidade de Samaria e a cercou.

[[v12-18-10]]

^<<v12-18-10,10>>^ Três anos depois, no sexto ano do reinado de Ezequias e no nono ano do reinado de Oseias, rei de Israel, Samaria foi conquistada.

[[v12-18-11]]

^<<v12-18-11,11>>^ O rei assírio deportou os israelitas para a Assíria e os colocou em assentamentos em Hala, ao longo das margens do rio Habor, em Gozã, e nas cidades da Média.

[[v12-18-12]]

^<<v12-18-12,12>>^ Isso aconteceu porque eles não ouviram nem obedeceram ao SENHOR, seu Deus. Em vez disso, violaram sua aliança, todas as leis às quais Moisés, servo do SENHOR, havia ordenado que obedecessem.

[[v12-18-13]]

^<<v12-18-13,13>>^ No décimo quarto ano do reinado de Ezequias, Senaqueribe, rei da Assíria, atacou as cidades fortificadas de Judá e as conquistou.

[[v12-18-14]]

^<<v12-18-14,14>>^ Ezequias, rei de Judá, enviou esta mensagem ao rei da Assíria, em Laquis: "Cometi um erro. Se você se retirar, eu lhe pagarei qualquer tributo que exigir". O rei da Assíria exigiu 10.500 quilos de prata e 1.050 quilos de ouro.

[[v12-18-15]]

^<<v12-18-15,15>>^ Para juntar essa quantia, Ezequias usou toda a prata guardada no templo do SENHOR e nos tesouros do palácio.

[[v12-18-16]]

^<<v12-18-16,16>>^ Arrancou até o ouro das portas e dos batentes do templo do SENHOR que ele havia coberto com ouro e entregou tudo ao rei da Assíria.

[[v12-18-17]]

^<<v12-18-17,17>>^ Apesar disso, o rei da Assíria enviou, de Laquis, seu comandante em chefe, seu comandante de campo e seu porta-voz, juntamente com um grande exército, para confrontarem o rei Ezequias em Jerusalém. Os assírios se posicionaram ao lado do aqueduto que abastece o tanque superior, perto do caminho para o campo onde se lava roupa.

[[v12-18-18]]

^<<v12-18-18,18>>^ Mandaram chamar o rei Ezequias, mas ele enviou os seguintes oficiais ao encontro deles: Eliaquim, filho de Hilquias, o administrador do palácio; Sebna, o secretário da corte; e Joá, filho de Asafe, o historiador do reino.

[[v12-18-19]]

^<<v12-18-19,19>>^ O porta-voz do rei assírio mandou que transmitissem esta mensagem a Ezequias: "Assim diz o grande rei da Assíria: Em que você confia, que lhe dá tanta segurança?

[[v12-18-20]]

^<<v12-18-20,20>>^ Pensa que meras palavras podem substituir experiência e força militar? Com quem você conta para se rebelar contra mim?

[[v12-18-21]]

^<<v12-18-21,21>>^ Com o Egito? Se você se apoiar no Egito, ele será como um junco que se quebra sob seu peso e perfura sua mão. O faraó, rei do Egito, não é digno de nenhuma confiança!

[[v12-18-22]]

^<<v12-18-22,22>>^ "Talvez vocês digam: ‘Confiamos no SENHOR, nosso Deus!’. Mas não foi a ele que Ezequias insultou? Ezequias não destruiu os santuários e altares dele e obrigou todos em Judá e Jerusalém a adorarem somente no altar em Jerusalém?

[[v12-18-23]]

^<<v12-18-23,23>>^ "Vou lhes dizer uma coisa: Façam um acordo com meu senhor, o rei da Assíria. Eu lhes darei dois mil cavalos se forem capazes de encontrar homens em número suficiente para montá-los!

[[v12-18-24]]

^<<v12-18-24,24>>^ Com seu exército minúsculo, como podem pensar em desafiar até o contingente mais fraco do exército de meu senhor, mesmo com a ajuda dos carros de guerra e dos cavaleiros do Egito?

[[v12-18-25]]

^<<v12-18-25,25>>^ Além disso, imaginam que invadimos sua terra sem a direção do SENHOR? Foi o próprio SENHOR que nos disse: ‘Ataquem essa terra e destruam-na!’".

[[v12-18-26]]

^<<v12-18-26,26>>^ Então Eliaquim, filho de Hilquias, Sebna e Joá disseram ao porta-voz: "Por favor, fale conosco em aramaico, pois entendemos bem essa língua. Não fale em hebraico, pois o povo sobre o muro o ouvirá".

[[v12-18-27]]

^<<v12-18-27,27>>^ O porta-voz, no entanto, respondeu: "Vocês pensam que meu senhor enviou essa mensagem apenas para vocês e para seu senhor? Ele quer que todo o povo a ouça, pois, quando cercarmos esta cidade, eles sofrerão junto com vocês. Ficarão tão famintos e sedentos que comerão as próprias fezes e beberão a própria urina!".

[[v12-18-28]]

^<<v12-18-28,28>>^ Então o porta-voz se levantou e gritou em hebraico: "Ouçam esta mensagem do grande rei da Assíria!

[[v12-18-29]]

^<<v12-18-29,29>>^ Assim diz o rei: Não deixem que Ezequias os engane. Ele jamais será capaz de livrá-los de meu poder.

[[v12-18-30]]

^<<v12-18-30,30>>^ Não deixem que ele os convença a confiar no SENHOR, dizendo: ‘Certamente o SENHOR nos livrará; esta cidade jamais cairá nas mãos do rei da Assíria!’.

[[v12-18-31]]

^<<v12-18-31,31>>^ "Não deem ouvidos a Ezequias! Estas são as condições que o rei da Assíria oferece: Façam as pazes comigo, abram as portas e saiam. Então, cada um de vocês continuará a comer de sua própria videira e de sua própria figueira e a beber de seu próprio poço.

[[v12-18-32]]

^<<v12-18-32,32>>^ Depois, providenciarei que sejam levados a outra terra como esta, uma terra com cereais e vinho novo, com pão e vinhedos, com olivais e mel. Escolham a vida, e não a morte! "Não deem ouvidos a Ezequias quando ele tentar enganá-los, dizendo: ‘O SENHOR nos livrará!’.

[[v12-18-33]]

^<<v12-18-33,33>>^ Acaso os deuses de alguma outra nação livraram seu povo do rei da Assíria?

[[v12-18-34]]

^<<v12-18-34,34>>^ O que aconteceu aos deuses de Hamate e de Arpade? E quanto aos deuses de Sefarvaim, de Hena e de Iva? Acaso algum deus livrou Samaria de meu poder?

[[v12-18-35]]

^<<v12-18-35,35>>^ Qual dos deuses de qualquer nação foi capaz de livrar seu povo de meu poder? O que os faz pensar que o SENHOR pode livrar Jerusalém de minhas mãos?".

[[v12-18-36]]

^<<v12-18-36,36>>^ Mas o povo permaneceu em silêncio e não disse uma palavra sequer, pois Ezequias havia ordenado: "Não lhe respondam".

[[v12-18-37]]

^<<v12-18-37,37>>^ Então Eliaquim, filho de Hilquias, administrador do palácio, Sebna, secretário da corte, e Joá, filho de Asafe, historiador do reino, voltaram a Ezequias. Rasgaram suas roupas e foram contar ao rei o que o porta-voz tinha dito.

'''

xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[&#60; Capítulo Anterior] | <<v12-18-0,Topo>> | xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[Próximo Capítulo &#62;]