include::./index.adoc[]

[[v12-13-0]]
=== 2 Reis, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v12-13-1]]

^<<v12-13-1,1>>^ Jeoacaz, filho de Jeú, começou a reinar em Israel no vigésimo terceiro ano do reinado de Joás, filho de Acazias, rei de Judá. Reinou em Samaria por dezessete anos.

[[v12-13-2]]

^<<v12-13-2,2>>^ Fez o que era mau aos olhos do SENHOR; seguiu o exemplo de Jeroboão, filho de Nebate, e persistiu nos pecados que Jeroboão havia levado Israel a cometer.

[[v12-13-3]]

^<<v12-13-3,3>>^ O SENHOR se irou grandemente com Israel e permitiu que Hazael, rei da Síria, e seu filho Ben-Hadade, derrotassem os israelitas repetidas vezes.

[[v12-13-4]]

^<<v12-13-4,4>>^ Então Jeoacaz orou ao SENHOR pedindo ajuda, e o SENHOR atendeu à sua oração, pois viu como o rei da Síria oprimia Israel cruelmente.

[[v12-13-5]]

^<<v12-13-5,5>>^ O SENHOR providenciou um libertador para salvar os israelitas da tirania dos sírios, e Israel voltou a viver em segurança, como em outros tempos.

[[v12-13-6]]

^<<v12-13-6,6>>^ Ainda assim, continuaram a seguir o mau exemplo de Jeroboão. Também permitiram que o poste de Aserá permanecesse em pé em Samaria.

[[v12-13-7]]

^<<v12-13-7,7>>^ Por fim, o exército de Jeoacaz foi reduzido a cinquenta cavaleiros, dez carros de guerra e dez mil soldados de infantaria. O rei da Síria havia destruído o restante, como se fosse pó debaixo de seus pés.

[[v12-13-8]]

^<<v12-13-8,8>>^ Os demais acontecimentos do reinado de Jeoacaz, tudo que ele fez e a extensão de seu poder, estão registrados no Livro da História dos Reis de Israel .

[[v12-13-9]]

^<<v12-13-9,9>>^ Quando Jeoacaz morreu e se reuniu a seus antepassados, foi sepultado em Samaria. Seu filho Jeoás foi seu sucessor.

[[v12-13-10]]

^<<v12-13-10,10>>^ Jeoás, filho de Jeoacaz, começou a reinar em Israel no trigésimo sétimo ano do reinado de Joás, rei de Judá. Reinou em Samaria por dezesseis anos.

[[v12-13-11]]

^<<v12-13-11,11>>^ Fez o que era mau aos olhos do SENHOR. Não se afastou dos pecados que Jeroboão, filho de Nebate, havia levado Israel a cometer.

[[v12-13-12]]

^<<v12-13-12,12>>^ Os demais acontecimentos do reinado de Jeoás e tudo que ele fez, incluindo a extensão de seu poder e a guerra contra Amazias, estão registrados no Livro da História dos Reis de Israel .

[[v12-13-13]]

^<<v12-13-13,13>>^ Quando Jeoás morreu e se reuniu a seus antepassados, foi sepultado em Samaria, com os reis de Israel. Seu filho Jeroboão II foi seu sucessor.

[[v12-13-14]]

^<<v12-13-14,14>>^ Quando Eliseu estava sofrendo da doença da qual morreria, Jeoás, rei de Israel, o visitou e chorou por ele, dizendo: "Meu pai, meu pai! Você era como os carros de guerra de Israel e seus cavaleiros!".

[[v12-13-15]]

^<<v12-13-15,15>>^ Eliseu lhe disse: "Pegue um arco e algumas flechas", e o rei fez o que ele pediu.

[[v12-13-16]]

^<<v12-13-16,16>>^ Então Eliseu lhe disse: "Ponha a mão sobre o arco", e pôs suas mãos sobre as mãos do rei.

[[v12-13-17]]

^<<v12-13-17,17>>^ Em seguida, ordenou: "Abra a janela que dá para o leste", e o rei a abriu. Depois, Eliseu disse: "Atire!", e o rei atirou uma flecha. "Essa é a flecha do SENHOR", anunciou Eliseu. "É uma flecha de vitória sobre a Síria, pois você conquistará completamente os sírios em Afeque."

[[v12-13-18]]

^<<v12-13-18,18>>^ Depois, Eliseu disse: "Agora pegue as outras flechas e atire-as contra o chão". O rei pegou as flechas e atirou-as contra o chão três vezes.

[[v12-13-19]]

^<<v12-13-19,19>>^ O homem de Deus se irou com ele. "Você deveria ter atirado contra o chão cinco ou seis vezes!", exclamou. "Assim, teria ferido os sírios até que fossem completamente destruídos. Agora você será vitorioso apenas três vezes."

[[v12-13-20]]

^<<v12-13-20,20>>^ Eliseu morreu e foi sepultado. Grupos de saqueadores moabitas costumavam invadir a terra na virada do ano.

[[v12-13-21]]

^<<v12-13-21,21>>^ Certa vez, enquanto alguns israelitas sepultavam um homem, viram um desses bandos. Rapidamente, jogaram o corpo no túmulo de Eliseu e fugiram. Assim que o corpo tocou os ossos de Eliseu, o homem voltou à vida e se pôs em pé.

[[v12-13-22]]

^<<v12-13-22,22>>^ Hazael, rei da Síria, oprimiu Israel durante todo o reinado de Jeoacaz.

[[v12-13-23]]

^<<v12-13-23,23>>^ O SENHOR, porém, foi bondoso e misericordioso com os israelitas, e eles não foram totalmente destruídos. Teve compaixão deles por causa da aliança que havia feito com Abraão, Isaque e Jacó. Naquela ocasião, como até hoje, não quis destruí-los completamente nem expulsá-los de sua presença.

[[v12-13-24]]

^<<v12-13-24,24>>^ Hazael, rei da Síria, morreu, e seu filho Ben-Hadade foi seu sucessor.

[[v12-13-25]]

^<<v12-13-25,25>>^ Então Jeoás, filho de Jeoacaz, reconquistou as cidades que Ben-Hadade havia tomado de seu pai, Jeoacaz. Jeoás derrotou Ben-Hadade em três ocasiões e recuperou as cidades israelitas.

'''

xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[&#60; Capítulo Anterior] | <<v12-13-0,Topo>> | xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[Próximo Capítulo &#62;]