include::./index.adoc[]

[[v1-38-0]]
=== Gênesis, 38
// nvt ?, NVT - Nova Versão Transformadora

[[v1-38-1]]

^<<v1-38-1,1>>^ Por essa época, Judá saiu de casa e se mudou para Adulão, onde foi morar na casa de um homem chamado Hira.

[[v1-38-2]]

^<<v1-38-2,2>>^ Ali, Judá viu uma mulher cananita, filha de Suá, e se casou com ela. Teve relações com a mulher,

[[v1-38-3]]

^<<v1-38-3,3>>^ e ela engravidou e deu à luz um filho, que ele chamou de Er.

[[v1-38-4]]

^<<v1-38-4,4>>^ Ela engravidou novamente e deu à luz outro filho, que chamou de Onã.

[[v1-38-5]]

^<<v1-38-5,5>>^ Quando estavam morando em Quezibe, ela deu à luz o terceiro filho e o chamou de Selá.

[[v1-38-6]]

^<<v1-38-6,6>>^ No devido tempo, Judá arranjou o casamento de Er, seu filho mais velho, com uma moça chamada Tamar.

[[v1-38-7]]

^<<v1-38-7,7>>^ Mas Er era um homem perverso aos olhos do SENHOR, por isso o SENHOR lhe tirou a vida.

[[v1-38-8]]

^<<v1-38-8,8>>^ Então Judá disse a Onã, irmão de Er: "Case-se com Tamar, como é exigido para com a viúva do irmão. Você deve gerar um herdeiro para seu irmão".

[[v1-38-9]]

^<<v1-38-9,9>>^ Onã, porém, não estava disposto a ter um filho que não seria seu herdeiro. Por isso, cada vez que tinha relações com a mulher de seu irmão, derramava o sêmen no chão. Desse modo, evitava que Tamar tivesse um filho que pertenceria ao irmão dele.

[[v1-38-10]]

^<<v1-38-10,10>>^ O SENHOR, porém, considerou maldade a sua atitude e, por isso, também tirou a vida de Onã.

[[v1-38-11]]

^<<v1-38-11,11>>^ Então Judá disse à sua nora Tamar: "Volte para a casa de seus pais e permaneça viúva até que meu filho Selá tenha idade suficiente para se casar com você". (Na verdade, Judá disse isso apenas porque temia que Selá também morresse, como seus dois irmãos.) Assim, Tamar voltou para a casa do pai.

[[v1-38-12]]

^<<v1-38-12,12>>^ Alguns anos depois, a mulher de Judá morreu. Quando terminou o período de luto, Judá e seu amigo Hira, o adulamita, subiram a Timna para supervisionar a tosquia das ovelhas de Judá.

[[v1-38-13]]

^<<v1-38-13,13>>^ Alguém disse a Tamar: "Seu sogro está subindo a Timna para tosquiar as ovelhas".

[[v1-38-14]]

^<<v1-38-14,14>>^ Tamar sabia que Selá já era adulto, mas nenhuma providência havia sido tomada para que ela se casasse com ele. Por isso, trocou suas roupas de viúva e, para disfarçar-se, cobriu-se com um véu. Depois, foi sentar-se junto à entrada da vila de Enaim, no caminho para Timna.

[[v1-38-15]]

^<<v1-38-15,15>>^ Judá a viu e pensou que fosse uma prostituta, pois ela estava com o rosto coberto.

[[v1-38-16]]

^<<v1-38-16,16>>^ Ele parou à beira da estrada e, sem saber que era sua própria nora, disse: "Quero me deitar com você". "Quanto você me pagará para deitar-se comigo?", perguntou Tamar.

[[v1-38-17]]

^<<v1-38-17,17>>^ "Eu lhe mandarei um cabrito do meu rebanho", prometeu Judá. "Mas o que me dá como garantia de que mandará o cabrito?", perguntou ela.

[[v1-38-18]]

^<<v1-38-18,18>>^ "Que tipo de garantia você quer?", replicou ele. Ela disse: "Deixe comigo seu selo pessoal, junto com o cordão dele e o cajado que você está segurando". Judá entregou os objetos. Depois, teve relações com Tamar, e ela engravidou.

[[v1-38-19]]

^<<v1-38-19,19>>^ Em seguida, Tamar voltou para casa, tirou o véu e tornou a vestir as roupas de viúva, como de costume.

[[v1-38-20]]

^<<v1-38-20,20>>^ Mais tarde, Judá pediu que seu amigo Hira, o adulamita, levasse o cabrito para a mulher e pegasse de volta as coisas que ele havia deixado como garantia. Hira, porém, não conseguiu encontrá-la.

[[v1-38-21]]

^<<v1-38-21,21>>^ Perguntou aos homens que moravam lá: "Onde posso encontrar a prostituta do templo que estava sentada junto à entrada de Enaim?". "Aqui nunca houve uma prostituta do templo", responderam eles.

[[v1-38-22]]

^<<v1-38-22,22>>^ Então Hira voltou para onde Judá estava e lhe disse: "Não consegui encontrá-la em lugar algum, e os homens da vila disseram que lá nunca houve uma prostituta do templo".

[[v1-38-23]]

^<<v1-38-23,23>>^ "Que ela fique com as minhas coisas", disse Judá. "Mandei o cabrito como tínhamos combinado, mas você não a encontrou. Se voltássemos para procurá-la, o povo da vila zombaria de nós."

[[v1-38-24]]

^<<v1-38-24,24>>^ Uns três meses depois, disseram a Judá: "Sua nora, Tamar, se comportou como prostituta e, por isso, está grávida". Judá ordenou: "Tragam-na para fora e queimem-na!".

[[v1-38-25]]

^<<v1-38-25,25>>^ Quando a estavam tirando de casa para matá-la, ela enviou a seguinte mensagem a seu sogro: "Estou grávida do homem que é dono destes objetos. Olhe com atenção. De quem são este selo, este cordão e este cajado?".

[[v1-38-26]]

^<<v1-38-26,26>>^ Judá os reconheceu de imediato e disse: "Ela é mais justa que eu, pois não tomei as providências para que ela se casasse com meu filho Selá". E Judá nunca mais teve relações com Tamar.

[[v1-38-27]]

^<<v1-38-27,27>>^ Quando chegou a época de Tamar dar à luz, descobriu que teria gêmeos.

[[v1-38-28]]

^<<v1-38-28,28>>^ Durante o trabalho de parto, um dos bebês pôs a mão para fora. A parteira segurou a mão do bebê, amarrou um fio vermelho no pulso e anunciou: "Este saiu primeiro".

[[v1-38-29]]

^<<v1-38-29,29>>^ O bebê, porém, recolheu a mão, e seu irmão saiu. Então a parteira disse: "Como você conseguiu sair primeiro?". Por isso, ele recebeu o nome de Perez.

[[v1-38-30]]

^<<v1-38-30,30>>^ Logo depois, o bebê com o fio vermelho no pulso nasceu e recebeu o nome de Zerá.

'''

xref:001-genesis/001-genesis-037.adoc#v1-37-0[&#60; Capítulo Anterior] | <<v1-38-0,Topo>> | xref:001-genesis/001-genesis-039.adoc#v1-39-0[Próximo Capítulo &#62;]