include::./index.adoc[]

[[v1-3-0]]
=== Gênesis, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v1-3-1]]

^<<v1-3-1,1>>^ A serpente era o mais astuto de todos os animais selvagens que o SENHOR Deus havia criado. Certa vez, ela perguntou à mulher: "Deus realmente disse que vocês não devem comer do fruto de nenhuma das árvores do jardim?".

[[v1-3-2]]

^<<v1-3-2,2>>^ "Podemos comer do fruto das árvores do jardim", respondeu a mulher.

[[v1-3-3]]

^<<v1-3-3,3>>^ "É só do fruto da árvore que está no meio do jardim que não podemos comer. Deus disse: ‘Não comam e nem sequer toquem no fruto daquela árvore; se o fizerem, morrerão’."

[[v1-3-4]]

^<<v1-3-4,4>>^ "É claro que vocês não morrerão!", a serpente respondeu à mulher.

[[v1-3-5]]

^<<v1-3-5,5>>^ "Deus sabe que, no momento em que comerem do fruto, seus olhos se abrirão e, como Deus, conhecerão o bem e o mal."

[[v1-3-6]]

^<<v1-3-6,6>>^ A mulher viu que a árvore era linda e que seu fruto parecia delicioso, e desejou a sabedoria que ele lhe daria. Assim, tomou do fruto e o comeu. Depois, deu ao marido, que estava com ela, e ele também comeu.

[[v1-3-7]]

^<<v1-3-7,7>>^ Naquele momento, seus olhos se abriram, e eles perceberam que estavam nus. Por isso, costuraram folhas de figueira umas às outras para se cobrirem.

[[v1-3-8]]

^<<v1-3-8,8>>^ Quando soprava a brisa do entardecer, o homem e sua mulher ouviram o SENHOR Deus caminhando pelo jardim e se esconderam dele entre as árvores.

[[v1-3-9]]

^<<v1-3-9,9>>^ Então o SENHOR Deus chamou o homem e perguntou: "Onde você está?".

[[v1-3-10]]

^<<v1-3-10,10>>^ Ele respondeu: "Ouvi que estavas andando pelo jardim e me escondi. Tive medo, pois eu estava nu".

[[v1-3-11]]

^<<v1-3-11,11>>^ "Quem lhe disse que você estava nu?", perguntou Deus. "Você comeu do fruto da árvore que eu lhe ordenei que não comesse?"

[[v1-3-12]]

^<<v1-3-12,12>>^ O homem respondeu: "Foi a mulher que me deste! Ela me ofereceu do fruto, e eu comi".

[[v1-3-13]]

^<<v1-3-13,13>>^ Então o SENHOR Deus perguntou à mulher: "O que foi que você fez?". "A serpente me enganou", respondeu a mulher. "Foi por isso que comi do fruto."

[[v1-3-14]]

^<<v1-3-14,14>>^ Então o SENHOR Deus disse à serpente: "Uma vez que fez isso, maldita é você entre todos os animais, domésticos e selvagens. Você se arrastará sobre o próprio ventre, rastejará no pó enquanto viver.

[[v1-3-15]]

^<<v1-3-15,15>>^ Farei que haja inimizade entre você e a mulher, e entre a sua descendência e o descendente dela. Ele lhe ferirá a cabeça, e você lhe ferirá o calcanhar".

[[v1-3-16]]

^<<v1-3-16,16>>^ À mulher ele disse: "Farei mais intensas as dores de sua gravidez, e com dor você dará à luz. Seu desejo será para seu marido, e ele a dominará".

[[v1-3-17]]

^<<v1-3-17,17>>^ E ao homem ele disse: "Uma vez que você deu ouvidos à sua mulher e comeu da árvore cujo fruto ordenei que não comesse, maldita é a terra por sua causa; por toda a vida, terá muito trabalho para tirar da terra seu sustento.

[[v1-3-18]]

^<<v1-3-18,18>>^ Ela produzirá espinhos e ervas daninhas, mas você comerá de seus frutos e grãos.

[[v1-3-19]]

^<<v1-3-19,19>>^ Com o suor do rosto você obterá alimento, até que volte à terra da qual foi formado. Pois você foi feito do pó, e ao pó voltará".

[[v1-3-20]]

^<<v1-3-20,20>>^ O homem, Adão, deu à sua mulher o nome de Eva, pois ela seria a mãe de toda a humanidade.

[[v1-3-21]]

^<<v1-3-21,21>>^ E o SENHOR Deus fez roupas de peles de animais para Adão e sua mulher.

[[v1-3-22]]

^<<v1-3-22,22>>^ Então o SENHOR Deus disse: "Vejam, agora os seres humanos se tornaram semelhantes a nós, pois conhecem o bem e o mal. Se eles tomarem do fruto da árvore da vida e dele comerem, viverão para sempre".

[[v1-3-23]]

^<<v1-3-23,23>>^ Para impedir que isso acontecesse, o SENHOR Deus os expulsou do jardim do Éden, e Adão passou a cultivar a terra da qual tinha sido formado.

[[v1-3-24]]

^<<v1-3-24,24>>^ Depois de expulsá-los, colocou querubins a leste do jardim do Éden e uma espada flamejante que se movia de um lado para o outro, a fim de guardar o caminho até a árvore da vida.

'''

xref:001-genesis/001-genesis-002.adoc#v1-2-0[&#60; Capítulo Anterior] | <<v1-3-0,Topo>> | xref:001-genesis/001-genesis-004.adoc#v1-4-0[Próximo Capítulo &#62;]