include::./index.adoc[]

[[v1-17-0]]
=== Gênesis, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v1-17-1]]

^<<v1-17-1,1>>^ Quando Abrão estava com 99 anos, o SENHOR lhe apareceu e disse: "Eu sou o Deus Todo-poderoso. Seja fiel a mim e tenha uma vida íntegra.

[[v1-17-2]]

^<<v1-17-2,2>>^ Farei uma aliança com você e lhe darei uma descendência incontável".

[[v1-17-3]]

^<<v1-17-3,3>>^ Ao ouvir essas palavras, Abrão se prostrou com o rosto no chão, e Deus lhe disse:

[[v1-17-4]]

^<<v1-17-4,4>>^ "Esta é a minha aliança com você: farei de você o pai de numerosas nações!

[[v1-17-5]]

^<<v1-17-5,5>>^ Além disso, mudarei seu nome. Você já não será chamado Abrão, mas sim Abraão, pois será o pai de muitas nações.

[[v1-17-6]]

^<<v1-17-6,6>>^ Eu o tornarei extremamente fértil. Seus descendentes formarão muitas nações, e haverá reis entre eles.

[[v1-17-7]]

^<<v1-17-7,7>>^ "Confirmarei a minha aliança com você e seus descendentes, de geração em geração. Esta é a aliança sem fim: serei sempre o seu Deus e o Deus de seus descendentes.

[[v1-17-8]]

^<<v1-17-8,8>>^ Darei a você e a seus descendentes toda a terra de Canaã, onde hoje você vive como estrangeiro. Será propriedade deles para sempre, e eu serei o seu Deus".

[[v1-17-9]]

^<<v1-17-9,9>>^ Então Deus disse a Abraão: "É sua responsabilidade permanente, e de seus descendentes, obedecer aos termos da aliança.

[[v1-17-10]]

^<<v1-17-10,10>>^ Este é o sinal da aliança que você e seus descendentes devem guardar: todo indivíduo do sexo masculino entre vocês deve ser circuncidado.

[[v1-17-11]]

^<<v1-17-11,11>>^ Cortem a carne do prepúcio como sinal da aliança entre mim e vocês.

[[v1-17-12]]

^<<v1-17-12,12>>^ Todo menino deve ser circuncidado no oitavo dia depois do nascimento, de geração em geração. Isso se aplica não apenas aos membros de sua família, mas também aos servos nascidos em sua casa e aos servos estrangeiros que você comprou.

[[v1-17-13]]

^<<v1-17-13,13>>^ Quer sejam nascidos em sua casa, quer os tenha comprado, todos devem ser circuncidados. Terão no corpo o sinal da minha aliança sem fim.

[[v1-17-14]]

^<<v1-17-14,14>>^ O indivíduo do sexo masculino que não for circuncidado será excluído do seu povo, pois quebrou a minha aliança".

[[v1-17-15]]

^<<v1-17-15,15>>^ Deus também disse a Abraão: "Quanto à sua mulher, não se chamará mais Sarai. De agora em diante ela se chamará Sara.

[[v1-17-16]]

^<<v1-17-16,16>>^ Eu a abençoarei e por meio dela darei a você um filho! Sim, eu a abençoarei, e ela se tornará mãe de muitas nações. Haverá reis de nações entre seus descendentes".

[[v1-17-17]]

^<<v1-17-17,17>>^ Abraão se prostrou com o rosto no chão e riu consigo. Pensou: "Como eu, aos 100 anos, poderia ser pai? E como Sara, aos 90 anos, teria um filho?".

[[v1-17-18]]

^<<v1-17-18,18>>^ Então Abraão disse a Deus: "Que Ismael viva sob a tua bênção!".

[[v1-17-19]]

^<<v1-17-19,19>>^ Mas Deus respondeu: "Na verdade, Sara, sua mulher, lhe dará um filho. Você o chamará Isaque, e eu confirmarei com ele e com seus descendentes, para sempre, a minha aliança.

[[v1-17-20]]

^<<v1-17-20,20>>^ Quanto a Ismael, também o abençoarei, como você pediu. Eu o tornarei extremamente fértil e multiplicarei seus descendentes. Ele será pai de doze príncipes, e farei dele uma grande nação.

[[v1-17-21]]

^<<v1-17-21,21>>^ Minha aliança, porém, será confirmada com Isaque, filho que Sara lhe dará por esta época, no ano que vem".

[[v1-17-22]]

^<<v1-17-22,22>>^ Quando Deus terminou de falar, retirou-se da presença de Abraão.

[[v1-17-23]]

^<<v1-17-23,23>>^ Naquele mesmo dia, Abraão tomou Ismael, seu filho, e todos os indivíduos do sexo masculino em sua casa, tanto os nascidos ali como os comprados, e os circuncidou, removendo o prepúcio, como Deus havia ordenado.

[[v1-17-24]]

^<<v1-17-24,24>>^ Abraão tinha 99 anos quando foi circuncidado,

[[v1-17-25]]

^<<v1-17-25,25>>^ e Ismael, seu filho, tinha 13 anos.

[[v1-17-26]]

^<<v1-17-26,26>>^ Ambos foram circuncidados naquele mesmo dia,

[[v1-17-27]]

^<<v1-17-27,27>>^ junto com todos os outros homens e meninos da casa, tanto os nascidos ali como os comprados. Todos foram circuncidados com Abraão.

'''

xref:001-genesis/001-genesis-016.adoc#v1-16-0[&#60; Capítulo Anterior] | <<v1-17-0,Topo>> | xref:001-genesis/001-genesis-018.adoc#v1-18-0[Próximo Capítulo &#62;]