include::./index.adoc[]

[[v1-6-0]]
=== Gênesis, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v1-6-1]]

^<<v1-6-1,1>>^ Os seres humanos começaram a se multiplicar na terra e tiveram filhas.

[[v1-6-2]]

^<<v1-6-2,2>>^ Os filhos de Deus perceberam que as filhas dos homens eram belas, tomaram para si as que os agradaram e se casaram com elas.

[[v1-6-3]]

^<<v1-6-3,3>>^ Então o SENHOR disse: "Meu Espírito não tolerará os humanos por muito tempo, pois são apenas carne mortal. Seus dias serão limitados a 120 anos".

[[v1-6-4]]

^<<v1-6-4,4>>^ Naqueles dias, e por algum tempo depois, havia na terra gigantes, pois quando os filhos de Deus tiveram relações com as filhas dos homens, elas deram à luz filhos que se tornaram os guerreiros famosos da antiguidade.

[[v1-6-5]]

^<<v1-6-5,5>>^ O SENHOR observou quanto havia aumentado a perversidade dos seres humanos na terra e viu que todos os seus pensamentos e seus propósitos eram sempre inteiramente maus.

[[v1-6-6]]

^<<v1-6-6,6>>^ E o SENHOR se arrependeu de tê-los criado e colocado na terra. Isso lhe causou imensa tristeza.

[[v1-6-7]]

^<<v1-6-7,7>>^ O SENHOR disse: "Eliminarei da face da terra esta raça humana que criei. Sim, e também destruirei todos os seres vivos: as pessoas, os grandes animais, os animais que rastejam pelo chão e até as aves do céu. Arrependo-me de tê-los criado".

[[v1-6-8]]

^<<v1-6-8,8>>^ Noé, porém, encontrou favor diante do SENHOR.

[[v1-6-9]]

^<<v1-6-9,9>>^ Este é o relato de Noé e sua família. Noé era um homem justo, a única pessoa íntegra naquele tempo, e andava em comunhão com Deus.

[[v1-6-10]]

^<<v1-6-10,10>>^ Noé gerou três filhos: Sem, Cam e Jafé.

[[v1-6-11]]

^<<v1-6-11,11>>^ Deus viu que a terra tinha se corrompido e estava cheia de violência.

[[v1-6-12]]

^<<v1-6-12,12>>^ Deus observou a grande maldade no mundo, pois todos na terra haviam se corrompido.

[[v1-6-13]]

^<<v1-6-13,13>>^ Assim, Deus disse a Noé: "Decidi acabar com todos os seres vivos, pois encheram a terra de violência. Sim, destruirei todos eles e também a terra!

[[v1-6-14]]

^<<v1-6-14,14>>^ "Construa uma grande embarcação, uma arca de madeira de cipreste, e cubra-a com betume por dentro e por fora, para que não entre água. Divida toda a parte interna em pisos e compartimentos.

[[v1-6-15]]

^<<v1-6-15,15>>^ A arca deve ter 135 metros de comprimento, 22,5 metros de largura e 13,5 metros de altura.

[[v1-6-16]]

^<<v1-6-16,16>>^ Deixe uma abertura de 45 centímetros debaixo do teto ao redor de toda a arca. Coloque uma porta lateral e construa três pisos na parte interna: inferior, médio e superior.

[[v1-6-17]]

^<<v1-6-17,17>>^ "Preste atenção! Em breve, cobrirei a terra com um dilúvio que destruirá todos os seres vivos que respiram. Tudo que há na terra morrerá.

[[v1-6-18]]

^<<v1-6-18,18>>^ Com você, porém, firmarei minha aliança. Portanto, entre na arca com sua mulher, seus filhos e as mulheres deles.

[[v1-6-19]]

^<<v1-6-19,19>>^ Leve na arca com você um casal de cada espécie de animal selvagem e doméstico, um macho e uma fêmea, para mantê-los com vida.

[[v1-6-20]]

^<<v1-6-20,20>>^ Um casal de cada espécie de ave, de cada espécie de animal e de cada espécie de animal que rasteja pelo chão virá até você, para que os mantenha com vida.

[[v1-6-21]]

^<<v1-6-21,21>>^ Cuide bem para que haja alimento suficiente para sua família e para todos os animais".

[[v1-6-22]]

^<<v1-6-22,22>>^ Noé fez tudo exatamente como Deus lhe havia ordenado.

'''

xref:001-genesis/001-genesis-005.adoc#v1-5-0[&#60; Capítulo Anterior] | <<v1-6-0,Topo>> | xref:001-genesis/001-genesis-007.adoc#v1-7-0[Próximo Capítulo &#62;]