include::./index.adoc[]

[[v1-18-0]]
=== Gênesis, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v1-18-1]]

^<<v1-18-1,1>>^ O SENHOR apareceu novamente a Abraão junto ao bosque de carvalhos que pertencia a Manre. Abraão estava sentado à entrada de sua tenda na hora mais quente do dia.

[[v1-18-2]]

^<<v1-18-2,2>>^ Olhando para fora, viu três homens em pé, próximos à tenda. Quando os viu, correu até onde estavam e lhes deu as boas-vindas, curvando-se até o chão.

[[v1-18-3]]

^<<v1-18-3,3>>^ Abraão disse: "Meu senhor, se assim desejar, pare aqui um pouco.

[[v1-18-4]]

^<<v1-18-4,4>>^ Descanse à sombra desta árvore enquanto mando trazer água para lavarem os pés.

[[v1-18-5]]

^<<v1-18-5,5>>^ E, uma vez que honraram seu servo com esta visita, prepararei uma refeição para restaurar suas forças antes de seguirem viagem". "Está bem", responderam eles. "Faça como você disse."

[[v1-18-6]]

^<<v1-18-6,6>>^ Abraão voltou correndo para a tenda e disse a Sara: "Rápido! Pegue três medidas da melhor farinha, amasse-a e faça alguns pães".

[[v1-18-7]]

^<<v1-18-7,7>>^ Em seguida, Abraão correu ao rebanho, escolheu um novilho tenro e o entregou a seu servo, que o preparou rapidamente.

[[v1-18-8]]

^<<v1-18-8,8>>^ Quando a comida estava pronta, Abraão pegou coalhada, leite e a carne assada e os serviu aos visitantes. Enquanto comiam, Abraão permaneceu à disposição deles, à sombra das árvores.

[[v1-18-9]]

^<<v1-18-9,9>>^ "Onde está Sara, sua mulher?", perguntaram os visitantes. "Está dentro da tenda", respondeu Abraão.

[[v1-18-10]]

^<<v1-18-10,10>>^ Então um deles disse: "Voltarei a visitar você por esta época, no ano que vem, e sua mulher, Sara, terá um filho". Sara estava ouvindo a conversa de dentro da tenda.

[[v1-18-11]]

^<<v1-18-11,11>>^ Abraão e Sara já eram bem velhos, e Sara tinha passado, havia muito tempo, da idade de ter filhos.

[[v1-18-12]]

^<<v1-18-12,12>>^ Por isso, riu consigo e disse: "Como poderia uma mulher da minha idade ter esse prazer, ainda mais quando meu senhor, meu marido, também é idoso?".

[[v1-18-13]]

^<<v1-18-13,13>>^ Então o SENHOR disse a Abraão: "Por que Sara riu? Por que disse: ‘Pode uma mulher da minha idade ter um filho’?

[[v1-18-14]]

^<<v1-18-14,14>>^ Existe alguma coisa difícil demais para o SENHOR? Voltarei por esta época, no ano que vem, e Sara terá um filho".

[[v1-18-15]]

^<<v1-18-15,15>>^ Sara teve medo e, por isso, mentiu: "Eu não ri". Mas ele disse: "Não é verdade. Você riu".

[[v1-18-16]]

^<<v1-18-16,16>>^ Depois da refeição, os visitantes se levantaram e olharam em direção a Sodoma. Quando partiram, Abraão os acompanhou para despedir-se deles.

[[v1-18-17]]

^<<v1-18-17,17>>^ Então o SENHOR disse: "Devo esconder meu plano de Abraão?

[[v1-18-18]]

^<<v1-18-18,18>>^ Afinal, Abraão certamente se tornará uma grande e poderosa nação, e todas as nações da terra serão abençoadas por meio dele.

[[v1-18-19]]

^<<v1-18-19,19>>^ Eu o escolhi para que ordene a seus filhos e às famílias deles que guardem o caminho do SENHOR, praticando o que é certo e justo. Então farei por Abraão tudo que prometi".

[[v1-18-20]]

^<<v1-18-20,20>>^ Portanto, o SENHOR disse a Abraão: "Ouvi um grande clamor vindo de Sodoma e Gomorra, porque o pecado dessas duas cidades é extremamente grave.

[[v1-18-21]]

^<<v1-18-21,21>>^ Descerei para investigar se seus atos são, de fato, tão perversos quanto tenho ouvido. Se não forem, quero saber".

[[v1-18-22]]

^<<v1-18-22,22>>^ Os outros visitantes partiram para Sodoma, mas Abraão permaneceu diante do SENHOR.

[[v1-18-23]]

^<<v1-18-23,23>>^ Aproximou-se dele e disse: "Exterminarás tanto os justos como os perversos?

[[v1-18-24]]

^<<v1-18-24,24>>^ Suponhamos que haja cinquenta justos na cidade. Mesmo assim os exterminarás e não a pouparás por causa deles?

[[v1-18-25]]

^<<v1-18-25,25>>^ Claro que não farias tal coisa: destruir o justo com o perverso. Afinal, estarias tratando o justo e o perverso da mesma maneira! Certamente não farias isso! Acaso o Juiz de toda a terra não faria o que é certo?".

[[v1-18-26]]

^<<v1-18-26,26>>^ O SENHOR respondeu: "Se eu encontrar cinquenta justos em Sodoma, pouparei a cidade toda por causa deles".

[[v1-18-27]]

^<<v1-18-27,27>>^ Abraão voltou a falar: "Embora eu seja apenas pó e cinza, permita-me dizer mais uma coisa ao meu Senhor.

[[v1-18-28]]

^<<v1-18-28,28>>^ Suponhamos que haja apenas quarenta e cinco justos, e não cinquenta. Destruirás a cidade toda por falta de cinco justos?". O SENHOR disse: "Se encontrar ali quarenta e cinco justos, não a destruirei".

[[v1-18-29]]

^<<v1-18-29,29>>^ Abraão levou seu pedido ainda mais longe: "Suponhamos que haja apenas quarenta". O SENHOR respondeu: "Por causa dos quarenta, não a destruirei".

[[v1-18-30]]

^<<v1-18-30,30>>^ "Por favor, não fiques irado comigo, meu Senhor", suplicou Abraão. "Permita-me falar. Suponhamos que haja apenas trinta justos." O SENHOR disse: "Se encontrar ali trinta justos, não a destruirei".

[[v1-18-31]]

^<<v1-18-31,31>>^ Abraão prosseguiu: "Uma vez que tive a ousadia de falar ao Senhor, permita-me continuar. Suponhamos que haja apenas vinte". O SENHOR respondeu: "Por causa dos vinte, não a destruirei".

[[v1-18-32]]

^<<v1-18-32,32>>^ Por fim, Abraão disse: "Senhor, não fiques irado comigo por eu falar mais uma vez. Suponhamos que haja apenas dez". O SENHOR respondeu: "Por causa dos dez, não a destruirei".

[[v1-18-33]]

^<<v1-18-33,33>>^ Quando terminou a conversa com Abraão, o SENHOR partiu, e Abraão voltou para sua tenda.

'''

xref:001-genesis/001-genesis-017.adoc#v1-17-0[&#60; Capítulo Anterior] | <<v1-18-0,Topo>> | xref:001-genesis/001-genesis-019.adoc#v1-19-0[Próximo Capítulo &#62;]