include::./index.adoc[]

[[v1-10-0]]
=== Gênesis, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v1-10-1]]

^<<v1-10-1,1>>^ Este é o relato das famílias de Sem, Cam e Jafé, os três filhos de Noé, que geraram muitos filhos depois do dilúvio.

[[v1-10-2]]

^<<v1-10-2,2>>^ Os descendentes de Jafé foram: Gômer, Magogue, Madai, Javã, Tubal, Meseque e Tirás.

[[v1-10-3]]

^<<v1-10-3,3>>^ Os descendentes de Gômer foram: Asquenaz, Rifate e Togarma.

[[v1-10-4]]

^<<v1-10-4,4>>^ Os descendentes de Javã foram: Elisá, Társis, Quitim e Rodanim.

[[v1-10-5]]

^<<v1-10-5,5>>^ Seus descendentes se espalharam por vários territórios junto ao mar, formando nações de acordo com suas línguas, seus clãs e seus povos.

[[v1-10-6]]

^<<v1-10-6,6>>^ Os descendentes de Cam foram: Cuxe, Mizraim, Pute e Canaã.

[[v1-10-7]]

^<<v1-10-7,7>>^ Os descendentes de Cuxe foram: Sebá, Havilá, Sabtá, Raamá e Sabtecá. Os descendentes de Raamá foram: Sabá e Dedã.

[[v1-10-8]]

^<<v1-10-8,8>>^ Cuxe também foi o antepassado de Ninrode, o primeiro guerreiro valente da terra.

[[v1-10-9]]

^<<v1-10-9,9>>^ Porque era o mais corajoso dos caçadores, seu nome deu origem ao provérbio: "Este homem é como Ninrode, o mais corajoso dos caçadores".

[[v1-10-10]]

^<<v1-10-10,10>>^ Ninrode construiu seu reino na terra da Babilônia, fundando as cidades de Babel, Ereque, Acade e Calné.

[[v1-10-11]]

^<<v1-10-11,11>>^ Expandiu seu território até a Assíria, onde construiu as cidades de Nínive, Reobote-Ir, Calá

[[v1-10-12]]

^<<v1-10-12,12>>^ e Resém, a grande cidade situada entre Nínive e Calá.

[[v1-10-13]]

^<<v1-10-13,13>>^ Mizraim foi o antepassado dos luditas, anamitas, leabitas, naftuítas,

[[v1-10-14]]

^<<v1-10-14,14>>^ patrusitas, casluítas e dos caftoritas, dos quais descendem os filisteus.

[[v1-10-15]]

^<<v1-10-15,15>>^ O filho mais velho de Canaã foi Sidom, antepassado dos sidônios. Canaã foi o antepassado dos hititas,

[[v1-10-16]]

^<<v1-10-16,16>>^ jebuseus, amorreus, girgaseus,

[[v1-10-17]]

^<<v1-10-17,17>>^ heveus, arqueus, sineus,

[[v1-10-18]]

^<<v1-10-18,18>>^ arvadeus, zemareus e hamateus. Com o tempo, os clãs cananeus se espalharam.

[[v1-10-19]]

^<<v1-10-19,19>>^ O território de Canaã se estendia desde Sidom, ao norte, até Gerar e Gaza, ao sul, e, a leste, até Sodoma, Gomorra, Admá e Zeboim, próximo a Lasa.

[[v1-10-20]]

^<<v1-10-20,20>>^ Esses foram os descendentes de Cam, de acordo com seus clãs, línguas, territórios e povos.

[[v1-10-21]]

^<<v1-10-21,21>>^ Sem, irmão mais velho de Jafé, também teve filhos. Sem foi o antepassado de todos os descendentes de Héber.

[[v1-10-22]]

^<<v1-10-22,22>>^ Os descendentes de Sem foram: Elão, Assur, Arfaxade, Lude e Arã.

[[v1-10-23]]

^<<v1-10-23,23>>^ Os descendentes de Arã foram: Uz, Hul, Géter e Más.

[[v1-10-24]]

^<<v1-10-24,24>>^ Arfaxade gerou Salá, e Salá gerou Héber.

[[v1-10-25]]

^<<v1-10-25,25>>^ Héber teve dois filhos. O primeiro recebeu o nome de Pelegue, pois em sua época a terra foi dividida. O irmão de Pelegue recebeu o nome de Joctã.

[[v1-10-26]]

^<<v1-10-26,26>>^ Joctã foi o antepassado de Almodá, Salefe, Hazarmavé, Jerá,

[[v1-10-27]]

^<<v1-10-27,27>>^ Adorão, Uzal, Dicla,

[[v1-10-28]]

^<<v1-10-28,28>>^ Obal, Abimael, Sabá,

[[v1-10-29]]

^<<v1-10-29,29>>^ Ofir, Havilá e Jobabe. Todos eles foram descendentes de Joctã.

[[v1-10-30]]

^<<v1-10-30,30>>^ O território que ocupavam se estendia desde Messa até Sefar, nas montanhas ao leste.

[[v1-10-31]]

^<<v1-10-31,31>>^ Esses foram os descendentes de Sem, de acordo com seus clãs, línguas, territórios e povos.

[[v1-10-32]]

^<<v1-10-32,32>>^ Esses foram os clãs descendentes dos filhos de Noé, de acordo com suas linhagens. Todas as nações da terra vieram desses clãs depois do dilúvio.

'''

xref:001-genesis/001-genesis-009.adoc#v1-9-0[&#60; Capítulo Anterior] | <<v1-10-0,Topo>> | xref:001-genesis/001-genesis-011.adoc#v1-11-0[Próximo Capítulo &#62;]