include::./index.adoc[]

[[v1-2-0]]
=== Gênesis, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v1-2-1]]

^<<v1-2-1,1>>^ Desse modo, completou-se a criação dos céus e da terra e de tudo que neles há.

[[v1-2-2]]

^<<v1-2-2,2>>^ No sétimo dia, Deus havia terminado sua obra de criação e descansou de todo o seu trabalho.

[[v1-2-3]]

^<<v1-2-3,3>>^ Deus abençoou o sétimo dia e o declarou santo, pois foi o dia em que ele descansou de toda a sua obra de criação.

[[v1-2-4]]

^<<v1-2-4,4>>^ Esse é o relato da criação dos céus e da terra. Quando o SENHOR Deus criou a terra e os céus,

[[v1-2-5]]

^<<v1-2-5,5>>^ nenhuma planta silvestre nem grãos haviam brotado na terra, pois o SENHOR Deus ainda não tinha mandado chuva para regar a terra, e não havia quem a cultivasse.

[[v1-2-6]]

^<<v1-2-6,6>>^ Mas do solo brotava água, que regava toda a terra.

[[v1-2-7]]

^<<v1-2-7,7>>^ Então o SENHOR Deus formou o homem do pó da terra. Soprou o fôlego da vida em suas narinas, e o homem se tornou ser vivo.

[[v1-2-8]]

^<<v1-2-8,8>>^ O SENHOR Deus plantou um jardim no Éden, para os lados do leste, e ali colocou o homem que havia criado.

[[v1-2-9]]

^<<v1-2-9,9>>^ O SENHOR Deus fez brotar do solo árvores de todas as espécies, árvores lindas que produziam frutos deliciosos. No meio do jardim, colocou a árvore da vida e a árvore do conhecimento do bem e do mal.

[[v1-2-10]]

^<<v1-2-10,10>>^ Da terra do Éden nascia um rio que regava o jardim e depois se dividia em quatro braços.

[[v1-2-11]]

^<<v1-2-11,11>>^ O primeiro braço, chamado Pisom, rodeava toda a terra de Havilá, onde existe ouro.

[[v1-2-12]]

^<<v1-2-12,12>>^ O ouro dessa terra é de grande pureza; lá também há resina aromática e pedra de ônix.

[[v1-2-13]]

^<<v1-2-13,13>>^ O segundo braço, chamado Giom, rodeava toda a terra de Cuxe.

[[v1-2-14]]

^<<v1-2-14,14>>^ O terceiro braço, chamado Tigre, corria para o leste da terra da Assíria. O quarto braço era chamado de Eufrates.

[[v1-2-15]]

^<<v1-2-15,15>>^ O SENHOR Deus colocou o homem no jardim do Éden para cultivá-lo e tomar conta dele,

[[v1-2-16]]

^<<v1-2-16,16>>^ mas o SENHOR Deus lhe ordenou: "Coma à vontade dos frutos de todas as árvores do jardim,

[[v1-2-17]]

^<<v1-2-17,17>>^ exceto da árvore do conhecimento do bem e do mal. Se você comer desse fruto, com certeza morrerá".

[[v1-2-18]]

^<<v1-2-18,18>>^ O SENHOR Deus disse: "Não é bom que o homem esteja sozinho. Farei alguém que o ajude e o complete".

[[v1-2-19]]

^<<v1-2-19,19>>^ O SENHOR Deus formou da terra todos os animais selvagens e todas as aves do céu. Trouxe-os ao homem para ver como os chamaria, e o homem escolheu um nome para cada um deles.

[[v1-2-20]]

^<<v1-2-20,20>>^ Deu nome a todos os animais domésticos, a todas as aves do céu e a todos os animais selvagens. O homem, porém, continuava sem alguém que o ajudasse e o completasse.

[[v1-2-21]]

^<<v1-2-21,21>>^ Então o SENHOR Deus o fez cair num sono profundo. Enquanto o homem dormia, tirou dele uma das costelas e fechou o espaço que ela ocupava.

[[v1-2-22]]

^<<v1-2-22,22>>^ Dessa costela o SENHOR Deus fez uma mulher e a trouxe ao homem.

[[v1-2-23]]

^<<v1-2-23,23>>^ "Finalmente!", exclamou o homem. "Esta é osso dos meus ossos, e carne da minha carne! Será chamada ‘mulher’, porque foi tirada do ‘homem’".

[[v1-2-24]]

^<<v1-2-24,24>>^ Por isso o homem deixa pai e mãe e se une à sua mulher, e os dois se tornam um só.

[[v1-2-25]]

^<<v1-2-25,25>>^ O homem e a mulher estavam nus, mas não sentiam vergonha.

'''

xref:001-genesis/001-genesis-001.adoc#v1-1-0[&#60; Capítulo Anterior] | <<v1-2-0,Topo>> | xref:001-genesis/001-genesis-003.adoc#v1-3-0[Próximo Capítulo &#62;]