include::./index.adoc[]

[[v1-26-0]]
=== Gênesis, 26
// nvt ?, NVT - Nova Versão Transformadora

[[v1-26-1]]

^<<v1-26-1,1>>^ Uma fome terrível atingiu a região, como havia acontecido antes no tempo de Abraão. Por isso, Isaque se mudou para Gerar, onde vivia Abimeleque, rei dos filisteus.

[[v1-26-2]]

^<<v1-26-2,2>>^ O SENHOR apareceu a Isaque e disse: "Não desça ao Egito. Faça o que eu mandar.

[[v1-26-3]]

^<<v1-26-3,3>>^ Habite aqui como estrangeiro, e eu estarei com você e o abençoarei. Com isso, confirmo que darei todas estas terras a você e a seus descendentes, conforme prometi solenemente a Abraão, seu pai.

[[v1-26-4]]

^<<v1-26-4,4>>^ Farei que seus descendentes sejam tão numerosos quanto as estrelas do céu e darei a eles todas estas terras. Por meio de sua descendência, todas as nações da terra serão abençoadas.

[[v1-26-5]]

^<<v1-26-5,5>>^ Farei isso porque Abraão me deu ouvidos e obedeceu ao que lhe ordenei: meus mandamentos, decretos e instruções".

[[v1-26-6]]

^<<v1-26-6,6>>^ Portanto, Isaque ficou em Gerar.

[[v1-26-7]]

^<<v1-26-7,7>>^ Quando os homens que viviam na região perguntaram a Isaque sobre Rebeca, sua mulher, ele disse: "É minha irmã". Teve medo de dizer "É minha mulher", pois pensou: "Ela é tão bonita que os homens vão me matar por causa dela".

[[v1-26-8]]

^<<v1-26-8,8>>^ Algum tempo depois, porém, Abimeleque, rei dos filisteus, olhou pela janela e viu Isaque acariciar Rebeca.

[[v1-26-9]]

^<<v1-26-9,9>>^ No mesmo instante, Abimeleque mandou chamar Isaque e exclamou: "É evidente que ela é sua mulher! Por que você disse que era sua irmã?". "Porque tive medo que alguém me matasse por causa dela", respondeu Isaque.

[[v1-26-10]]

^<<v1-26-10,10>>^ "Como você pôde fazer uma coisa dessas conosco?", exclamou Abimeleque. "Um dos meus homens poderia ter tomado sua mulher e dormido com ela e, por sua causa, seríamos culpados de grande pecado!"

[[v1-26-11]]

^<<v1-26-11,11>>^ Então Abimeleque declarou a todo o povo: "Quem tocar neste homem ou em sua mulher será executado!".

[[v1-26-12]]

^<<v1-26-12,12>>^ Naquele ano, quando Isaque plantou lavouras, colheu cem vezes mais cereais do que havia semeado, pois o SENHOR o abençoou.

[[v1-26-13]]

^<<v1-26-13,13>>^ Isaque prosperou e se tornou rico e influente.

[[v1-26-14]]

^<<v1-26-14,14>>^ Adquiriu tantos rebanhos de ovelhas e bois e tantos servos que os filisteus o invejaram.

[[v1-26-15]]

^<<v1-26-15,15>>^ Por isso, os filisteus fecharam com terra todos os poços de Isaque, que tinham sido cavados pelos servos de seu pai, Abraão.

[[v1-26-16]]

^<<v1-26-16,16>>^ Por fim, Abimeleque ordenou que Isaque deixasse aquela terra. "Vá para outro lugar", disse ele. "Você se tornou poderoso demais para nós."

[[v1-26-17]]

^<<v1-26-17,17>>^ Então Isaque partiu de onde estava e se estabeleceu no vale de Gerar, onde armou suas tendas.

[[v1-26-18]]

^<<v1-26-18,18>>^ Reabriu os poços que seu pai havia cavado e que os filisteus haviam fechado depois da morte de Abraão e lhes deu os mesmos nomes que Abraão tinha dado.

[[v1-26-19]]

^<<v1-26-19,19>>^ Os servos de Isaque também cavaram no vale de Gerar e encontraram uma fonte de água corrente.

[[v1-26-20]]

^<<v1-26-20,20>>^ Contudo, os pastores de Gerar entraram em conflito com os pastores de Isaque. "Esta água é nossa!", diziam eles. Por isso, Isaque chamou o poço de Eseque.

[[v1-26-21]]

^<<v1-26-21,21>>^ Em seguida, os homens de Isaque cavaram outro poço, mas, novamente, houve conflito por causa dele. Por isso, Isaque o chamou de Sitna.

[[v1-26-22]]

^<<v1-26-22,22>>^ Isaque abandonou esse poço e mandou cavar outro mais adiante. Dessa vez, ninguém discutiu por causa dele, de modo que Isaque o chamou de Reobote, pois disse: "Finalmente o SENHOR criou espaço suficiente para prosperarmos nesta terra!".

[[v1-26-23]]

^<<v1-26-23,23>>^ Dali, Isaque se mudou para Berseba,

[[v1-26-24]]

^<<v1-26-24,24>>^ onde o SENHOR lhe apareceu na noite de sua chegada e disse: "Eu sou o Deus de seu pai, Abraão. Não tenha medo, pois estou com você e o abençoarei. Multiplicarei seus descendentes, e eles se tornarão uma grande nação. Farei isso por causa da minha promessa ao meu servo, Abraão".

[[v1-26-25]]

^<<v1-26-25,25>>^ Isaque construiu ali um altar e invocou o nome do SENHOR. Armou acampamento naquele local, e seus servos cavaram outro poço.

[[v1-26-26]]

^<<v1-26-26,26>>^ Certo dia, o rei Abimeleque veio de Gerar com Auzate, seu conselheiro, e com Ficol, comandante do seu exército.

[[v1-26-27]]

^<<v1-26-27,27>>^ "Por que vocês vieram?", perguntou Isaque. "É evidente que me odeiam, já que me expulsaram de sua terra."

[[v1-26-28]]

^<<v1-26-28,28>>^ Eles responderam: "Podemos ver claramente que o SENHOR está com você. Por isso, queremos fazer com você um acordo sob juramento, uma aliança.

[[v1-26-29]]

^<<v1-26-29,29>>^ Jure que não nos fará mal, assim como nós nunca lhe fizemos mal. Sempre o tratamos bem e o despedimos em paz. E agora, veja como o SENHOR o abençoou!".

[[v1-26-30]]

^<<v1-26-30,30>>^ Então Isaque lhes preparou um banquete, e eles comeram e beberam juntos.

[[v1-26-31]]

^<<v1-26-31,31>>^ Logo cedo, na manhã seguinte, cada um fez o juramento solene de não interferir com o outro. Isaque se despediu deles, e partiram em paz.

[[v1-26-32]]

^<<v1-26-32,32>>^ Naquele mesmo dia, os servos de Isaque vieram lhe falar de um novo poço que tinham cavado. "Encontramos água!", exclamaram.

[[v1-26-33]]

^<<v1-26-33,33>>^ Por isso, Isaque chamou o poço de Seba. E, até hoje, a cidade que se formou ali é conhecida como Berseba.

[[v1-26-34]]

^<<v1-26-34,34>>^ Quando Esaú tinha 40 anos, casou-se com duas mulheres hititas: Judite, filha de Beeri, e Basemate, filha de Elom.

[[v1-26-35]]

^<<v1-26-35,35>>^ Essas duas mulheres causaram grande desgosto a Isaque e Rebeca.

'''

xref:001-genesis/001-genesis-025.adoc#v1-25-0[&#60; Capítulo Anterior] | <<v1-26-0,Topo>> | xref:001-genesis/001-genesis-027.adoc#v1-27-0[Próximo Capítulo &#62;]