include::./index.adoc[]

[[v1-37-0]]
=== Gênesis, 37
// nvt ?, NVT - Nova Versão Transformadora

[[v1-37-1]]

^<<v1-37-1,1>>^ Jacó passou a morar na terra de Canaã, onde seu pai tinha vivido como estrangeiro.

[[v1-37-2]]

^<<v1-37-2,2>>^ Este é o relato de Jacó e sua família. Quando José tinha 17 anos, cuidava dos rebanhos de seu pai. Trabalhava com seus meios-irmãos, os filhos de Bila e Zilpa, mulheres de seu pai, e contava para seu pai algumas das coisas erradas que seus irmãos faziam.

[[v1-37-3]]

^<<v1-37-3,3>>^ Jacó amava José mais que a qualquer outro de seus filhos, pois José havia nascido quando Jacó era idoso. Por isso, certo dia Jacó encomendou um presente especial para José: uma linda túnica.

[[v1-37-4]]

^<<v1-37-4,4>>^ Os irmãos de José, por sua vez, o odiavam, pois o pai deles o amava mais que a todos os outros filhos. Não eram capazes de lhe dizer uma única palavra amigável.

[[v1-37-5]]

^<<v1-37-5,5>>^ Certa noite, José teve um sonho e, quando o contou a seus irmãos, eles o odiaram ainda mais.

[[v1-37-6]]

^<<v1-37-6,6>>^ "Ouçam este sonho que tive", disse ele.

[[v1-37-7]]

^<<v1-37-7,7>>^ "Estávamos no campo, amarrando feixes de trigo. De repente, meu feixe se levantou e ficou em pé, e seus feixes se juntaram ao redor do meu e se curvaram diante dele!"

[[v1-37-8]]

^<<v1-37-8,8>>^ Seus irmãos responderam: "Você imagina que será nosso rei? Pensa mesmo que nos governará?". E o odiaram ainda mais por causa de seus sonhos e da maneira como os contava.

[[v1-37-9]]

^<<v1-37-9,9>>^ Pouco tempo depois, José teve outro sonho e, mais uma vez, contou-o a seus irmãos. "Ouçam, tive outro sonho", disse ele. "O sol, a lua e onze estrelas se curvavam diante de mim!"

[[v1-37-10]]

^<<v1-37-10,10>>^ Dessa vez, contou o sonho não apenas aos irmãos, mas também ao pai, que o repreendeu, dizendo: "Que sonho é esse? Por acaso eu, sua mãe e seus irmãos viremos e nos curvaremos até o chão diante de você?".

[[v1-37-11]]

^<<v1-37-11,11>>^ Os irmãos de José ficaram com inveja dele, mas seu pai se perguntou qual seria o significado dos sonhos.

[[v1-37-12]]

^<<v1-37-12,12>>^ Pouco depois, os irmãos de José levaram os rebanhos de seu pai para pastar junto de Siquém.

[[v1-37-13]]

^<<v1-37-13,13>>^ Então Jacó disse a José: "Seus irmãos estão cuidando das ovelhas em Siquém. Apronte-se, e eu o enviarei até eles". "Estou pronto para ir", respondeu José.

[[v1-37-14]]

^<<v1-37-14,14>>^ "Vá ver como estão seus irmãos e os rebanhos", disse Jacó. "E traga-me notícias deles." Jacó o enviou, e José viajou de sua casa no vale de Hebrom até Siquém.

[[v1-37-15]]

^<<v1-37-15,15>>^ Quando José chegou a Siquém, um homem da região notou que ele andava perdido pelos campos. "O que você está procurando?", perguntou o homem.

[[v1-37-16]]

^<<v1-37-16,16>>^ "Estou procurando meus irmãos", respondeu José. "O senhor sabe onde eles estão cuidando dos rebanhos?"

[[v1-37-17]]

^<<v1-37-17,17>>^ O homem lhe disse: "Sim, eles foram embora daqui, mas eu os ouvi dizer: ‘Vamos a Dotã’". Então José foi atrás de seus irmãos e os encontrou em Dotã.

[[v1-37-18]]

^<<v1-37-18,18>>^ Quando os irmãos de José o viram, o reconheceram de longe. Antes que ele se aproximasse, planejaram uma forma de matá-lo.

[[v1-37-19]]

^<<v1-37-19,19>>^ "Lá vem o sonhador!", disseram uns aos outros.

[[v1-37-20]]

^<<v1-37-20,20>>^ "Vamos matá-lo e jogá-lo numa dessas cisternas. Diremos a nosso pai: ‘Um animal selvagem o devorou’. Então veremos o que será dos seus sonhos!"

[[v1-37-21]]

^<<v1-37-21,21>>^ Mas, quando Rúben ouviu o plano, tratou de livrar José. "Não o matemos", disse ele.

[[v1-37-22]]

^<<v1-37-22,22>>^ "Por que derramar sangue? Joguem-no nesta cisterna vazia aqui no deserto e não toquemos nele." Rúben planejava resgatar José e levá-lo de volta ao pai.

[[v1-37-23]]

^<<v1-37-23,23>>^ Assim, quando José chegou, os irmãos lhe arrancaram a linda túnica que ele estava usando,

[[v1-37-24]]

^<<v1-37-24,24>>^ o agarraram e o jogaram na cisterna vazia, ou seja, sem água.

[[v1-37-25]]

^<<v1-37-25,25>>^ Mais tarde, quando se sentaram para comer, viram ao longe uma caravana de camelos vindo em sua direção. Era um grupo de negociantes ismaelitas, que transportavam especiarias, bálsamo e mirra de Gileade para o Egito.

[[v1-37-26]]

^<<v1-37-26,26>>^ Judá disse a seus irmãos: "O que ganharemos se matarmos nosso irmão e encobrirmos o crime?

[[v1-37-27]]

^<<v1-37-27,27>>^ Em vez de matá-lo, vamos vendê-lo aos negociantes ismaelitas. Afinal, ele é nosso irmão, sangue do nosso sangue!". Seus irmãos concordaram.

[[v1-37-28]]

^<<v1-37-28,28>>^ Então, quando os ismaelitas, que eram negociantes midianitas, se aproximaram, os irmãos de José o tiraram da cisterna e o venderam para eles por vinte peças de prata. E os negociantes o levaram para o Egito.

[[v1-37-29]]

^<<v1-37-29,29>>^ Algum tempo depois, Rúben voltou para tirar José da cisterna. Quando descobriu que seu irmão não estava lá, rasgou as roupas.

[[v1-37-30]]

^<<v1-37-30,30>>^ Voltou a seus irmãos e lamentou-se: "O menino sumiu! E agora, o que farei?".

[[v1-37-31]]

^<<v1-37-31,31>>^ Então os irmãos mataram um bode e mergulharam a túnica de José no sangue do animal.

[[v1-37-32]]

^<<v1-37-32,32>>^ Enviaram a linda túnica para o pai, com a seguinte mensagem: "Veja o que encontramos. Não é a túnica de seu filho?".

[[v1-37-33]]

^<<v1-37-33,33>>^ O pai a reconheceu de imediato e disse: "Sim, é a túnica de meu filho. Um animal selvagem o deve ter devorado. Com certeza José morreu despedaçado!".

[[v1-37-34]]

^<<v1-37-34,34>>^ Jacó rasgou suas roupas e vestiu-se de pano de saco. Por longo tempo, lamentou profundamente a morte do filho.

[[v1-37-35]]

^<<v1-37-35,35>>^ A família toda tentou consolá-lo, mas ele se recusava. "Descerei à sepultura lamentando a morte de meu filho", dizia, e continuou a lamentar-se.

[[v1-37-36]]

^<<v1-37-36,36>>^ Enquanto isso, os negociantes midianitas chegaram ao Egito, onde venderam José a Potifar, oficial e capitão da guarda do faraó.

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]