include::./index.adoc[]

[[v1-46-0]]
=== Gênesis, 46
// nvt ?, NVT - Nova Versão Transformadora

[[v1-46-1]]

^<<v1-46-1,1>>^ Jacó partiu para o Egito com todos os seus bens. Quando chegou a Berseba, ofereceu sacrifícios ao Deus de Isaque, seu pai.

[[v1-46-2]]

^<<v1-46-2,2>>^ Durante a noite, Deus lhe falou numa visão. "Jacó! Jacó!", chamou ele. "Aqui estou!", respondeu Jacó.

[[v1-46-3]]

^<<v1-46-3,3>>^ "Eu sou Deus, o Deus de seu pai", disse a voz. "Não tenha medo de descer ao Egito, pois lá farei de sua família uma grande nação.

[[v1-46-4]]

^<<v1-46-4,4>>^ Descerei com você ao Egito e certamente o trarei de volta. E José estará ao seu lado quando você morrer."

[[v1-46-5]]

^<<v1-46-5,5>>^ Então Jacó saiu de Berseba, e seus filhos o levaram para o Egito. Transportaram o pai, as crianças e as mulheres nas carruagens que o faraó lhes havia providenciado.

[[v1-46-6]]

^<<v1-46-6,6>>^ Também levaram todos os seus rebanhos e os bens que haviam adquirido na terra de Canaã. Assim, Jacó e toda a sua família foram para o Egito:

[[v1-46-7]]

^<<v1-46-7,7>>^ filhos e netos, filhas e netas, todos os seus descendentes.

[[v1-46-8]]

^<<v1-46-8,8>>^ Estes são os nomes dos descendentes de Israel, os filhos de Jacó, que foram ao Egito: Rúben foi o filho mais velho de Jacó.

[[v1-46-9]]

^<<v1-46-9,9>>^ Os filhos de Rúben foram: Enoque, Palu, Hezrom e Carmi.

[[v1-46-10]]

^<<v1-46-10,10>>^ Os filhos de Simeão foram: Jemuel, Jamim, Oade, Jaquim, Zoar e Saul. (A mãe de Saul era cananita.)

[[v1-46-11]]

^<<v1-46-11,11>>^ Os filhos de Levi foram: Gérson, Coate e Merari.

[[v1-46-12]]

^<<v1-46-12,12>>^ Os filhos de Judá foram: Er, Onã, Selá, Perez e Zerá (embora Er e Onã tivessem morrido na terra de Canaã). Os filhos de Perez foram: Hezrom e Hamul.

[[v1-46-13]]

^<<v1-46-13,13>>^ Os filhos de Issacar foram: Tolá, Puá, Jasube e Sinrom.

[[v1-46-14]]

^<<v1-46-14,14>>^ Os filhos de Zebulom foram: Serede, Elom e Jaleel.

[[v1-46-15]]

^<<v1-46-15,15>>^ Esses foram os filhos de Lia e Jacó nascidos em Padã-Arã, além de sua filha Diná. Por meio de Lia, Jacó teve 33 descendentes, tanto homens quanto mulheres.

[[v1-46-16]]

^<<v1-46-16,16>>^ Os filhos de Gade foram: Zefom, Hagi, Suni, Esbom, Eri, Arodi e Areli.

[[v1-46-17]]

^<<v1-46-17,17>>^ Os filhos de Aser foram: Imná, Isvá, Isvi e Berias. A irmã deles se chamava Sera. Os filhos de Berias foram: Héber e Malquiel.

[[v1-46-18]]

^<<v1-46-18,18>>^ Esses foram os filhos de Zilpa, serva dada a Lia por Labão, seu pai. Por meio de Zilpa, Jacó teve dezesseis descendentes.

[[v1-46-19]]

^<<v1-46-19,19>>^ Os filhos de Raquel, mulher de Jacó, foram: José e Benjamim.

[[v1-46-20]]

^<<v1-46-20,20>>^ Os filhos de José, nascidos no Egito, foram: Manassés e Efraim. Sua mãe foi Azenate, filha de Potífera, sacerdote de Om.

[[v1-46-21]]

^<<v1-46-21,21>>^ Os filhos de Benjamim foram: Belá, Bequer, Asbel, Gera, Naamã, Eí, Rôs, Mupim, Hupim e Arde.

[[v1-46-22]]

^<<v1-46-22,22>>^ Esses foram os filhos de Raquel e Jacó. Por meio de Raquel, Jacó teve catorze descendentes.

[[v1-46-23]]

^<<v1-46-23,23>>^ O filho de Dã foi Husim.

[[v1-46-24]]

^<<v1-46-24,24>>^ Os filhos de Naftali foram: Jazeel, Guni, Jezer e Silém.

[[v1-46-25]]

^<<v1-46-25,25>>^ Esses foram os filhos de Bila, serva dada a Raquel por Labão, seu pai. Por meio de Bila, Jacó teve sete descendentes.

[[v1-46-26]]

^<<v1-46-26,26>>^ No total, 66 descendentes diretos de Jacó foram com ele para o Egito, sem contar as esposas de seus filhos.

[[v1-46-27]]

^<<v1-46-27,27>>^ Além deles, José teve dois filhos que nasceram no Egito, totalizando setenta membros da família de Jacó no Egito.

[[v1-46-28]]

^<<v1-46-28,28>>^ Quando estavam quase chegando, Jacó enviou Judá adiante para encontrar-se com José e pedir-lhe informações sobre o caminho para Gósen.

[[v1-46-29]]

^<<v1-46-29,29>>^ José mandou preparar sua carruagem e partiu para Gósen, a fim de encontrar-se com seu pai, Jacó. Quando José chegou, abraçou fortemente seu pai e, sem soltá-lo, chorou por longo tempo.

[[v1-46-30]]

^<<v1-46-30,30>>^ Por fim, Jacó disse a José: "Agora estou pronto para morrer, pois vi seu rosto novamente e sei que você está vivo".

[[v1-46-31]]

^<<v1-46-31,31>>^ José disse a seus irmãos e a toda a família de seu pai: "Irei ao faraó e lhe direi: ‘Meus irmãos e toda a família de meu pai chegaram da terra de Canaã.

[[v1-46-32]]

^<<v1-46-32,32>>^ Eles são pastores e criadores de gado. Trouxeram consigo seus rebanhos, seu gado e todos os seus bens’".

[[v1-46-33]]

^<<v1-46-33,33>>^ Disse também: "Quando o faraó mandar chamá-los e perguntar-lhes em que vocês trabalham,

[[v1-46-34]]

^<<v1-46-34,34>>^ digam o seguinte: ‘Durante toda a vida, nós, seus servos, criamos rebanhos e gado, como sempre fizeram nossos antepassados’. Quando lhe disserem isso, ele permitirá que vivam aqui na região de Gósen, pois os egípcios desprezam os pastores".

'''

xref:001-genesis/001-genesis-045.adoc#v1-45-0[&#60; Capítulo Anterior] | <<v1-46-0,Topo>> | xref:001-genesis/001-genesis-047.adoc#v1-47-0[Próximo Capítulo &#62;]