include::./index.adoc[]

[[v1-50-0]]
=== Gênesis, 50
// nvt ?, NVT - Nova Versão Transformadora

[[v1-50-1]]

^<<v1-50-1,1>>^ José atirou-se sobre seu pai, chorou sobre ele e o beijou.

[[v1-50-2]]

^<<v1-50-2,2>>^ Em seguida, deu ordens aos médicos que o serviam para que embalsamassem o corpo de seu pai, e Jacó foi embalsamado.

[[v1-50-3]]

^<<v1-50-3,3>>^ O processo de embalsamamento levou os quarenta dias habituais. E os egípcios lamentaram sua morte durante setenta dias.

[[v1-50-4]]

^<<v1-50-4,4>>^ Quando terminou o período de luto, José procurou os conselheiros do faraó e lhes disse: "Por gentileza, peço que falem com o faraó em meu favor.

[[v1-50-5]]

^<<v1-50-5,5>>^ Digam-lhe que meu pai me fez prestar um juramento. Disse: ‘Morrerei em breve. Leve meu corpo de volta para a terra de Canaã e coloque-me na sepultura que preparei para mim’. Portanto, peço que me deixe ir sepultar meu pai; depois, voltarei sem demora".

[[v1-50-6]]

^<<v1-50-6,6>>^ O faraó atendeu ao pedido de José e disse: "Vá e sepulte seu pai, como ele o fez prometer".

[[v1-50-7]]

^<<v1-50-7,7>>^ Então José partiu para sepultar seu pai. Foi acompanhado de todos os oficiais do faraó, todos os membros mais importantes da casa do faraó e todos os oficiais de alto escalão do Egito.

[[v1-50-8]]

^<<v1-50-8,8>>^ José também levou consigo toda a sua família, seus irmãos e a família deles. As crianças pequenas, os rebanhos e o gado, porém, deixaram na terra de Gósen.

[[v1-50-9]]

^<<v1-50-9,9>>^ Muitas carruagens e seus condutores acompanharam José, formando um grande cortejo.

[[v1-50-10]]

^<<v1-50-10,10>>^ Quando chegaram à eira de Atade, perto do rio Jordão, realizaram uma grande cerimônia fúnebre, com um período de sete dias de luto pelo pai de José.

[[v1-50-11]]

^<<v1-50-11,11>>^ Os cananeus que moravam na região os viram chorar na eira de Atade e mudaram o nome do lugar (que fica próximo ao Jordão) para Abel-Mizraim, pois disseram: "Este é um lugar de lamento profundo para esses egípcios".

[[v1-50-12]]

^<<v1-50-12,12>>^ Assim, os filhos de Jacó fizeram o que ele lhes havia ordenado.

[[v1-50-13]]

^<<v1-50-13,13>>^ Levaram seu corpo para a terra de Canaã e o sepultaram na caverna no campo de Macpela, perto de Manre. Essa é a caverna que Abraão havia comprado de Efrom, o hitita, como sepultura permanente.

[[v1-50-14]]

^<<v1-50-14,14>>^ Depois de sepultar Jacó, José voltou para o Egito com seus irmãos e com todos que o haviam acompanhado.

[[v1-50-15]]

^<<v1-50-15,15>>^ Uma vez que seu pai estava morto, porém, os irmãos de José ficaram temerosos e disseram: "Agora José mostrará sua ira e se vingará de todo o mal que lhe fizemos".

[[v1-50-16]]

^<<v1-50-16,16>>^ Por isso, enviaram a seguinte mensagem a José: "Antes de morrer, nosso pai mandou

[[v1-50-17]]

^<<v1-50-17,17>>^ que lhe disséssemos: ‘Por favor, perdoe seus irmãos pelo grande mal que eles lhe fizeram, pelo pecado que cometeram ao tratá-lo com tanta crueldade’. Por isso, nós, servos do Deus de seu pai, suplicamos que você perdoe nosso pecado". Quando José recebeu a mensagem, começou a chorar.

[[v1-50-18]]

^<<v1-50-18,18>>^ Depois, seus irmãos chegaram e se curvaram com o rosto no chão diante de José. "Somos seus escravos!", disseram eles.

[[v1-50-19]]

^<<v1-50-19,19>>^ José, porém, respondeu: "Não tenham medo de mim. Por acaso sou Deus para castigá-los?

[[v1-50-20]]

^<<v1-50-20,20>>^ Vocês pretendiam me fazer o mal, mas Deus planejou tudo para o bem. Colocou-me neste cargo para que eu pudesse salvar a vida de muitos.

[[v1-50-21]]

^<<v1-50-21,21>>^ Não tenham medo. Continuarei a cuidar de vocês e de seus filhos". Desse modo, ele os tranquilizou ao tratá-los com bondade.

[[v1-50-22]]

^<<v1-50-22,22>>^ José, seus irmãos e suas famílias continuaram a viver no Egito. José viveu 110 anos.

[[v1-50-23]]

^<<v1-50-23,23>>^ Chegou a ver três gerações de descendentes de seu filho Efraim e o nascimento dos filhos de Maquir, filho de Manassés, os quais ele tomou para si como se fossem seus.

[[v1-50-24]]

^<<v1-50-24,24>>^ José disse a seus irmãos: "Em breve morrerei, mas certamente Deus os ajudará e os tirará desta terra. Ele os levará de volta para a terra que prometeu solenemente dar a Abraão, Isaque e Jacó".

[[v1-50-25]]

^<<v1-50-25,25>>^ Então José fez os filhos de Israel prestarem um juramento e disse: "Quando Deus vier ajudá-los e conduzi-los de volta, levem meus ossos com vocês".

[[v1-50-26]]

^<<v1-50-26,26>>^ José morreu com 110 anos. Os egípcios o embalsamaram e o colocaram em um caixão no Egito.

'''

xref:001-genesis/001-genesis-049.adoc#v1-49-0[&#60; Capítulo Anterior] | <<v1-50-0,Topo>> | xref:002-exodo/002-exodo-001.adoc#v2-1-0[Próximo Capítulo &#62;]