include::./index.adoc[]

[[v1-25-0]]
=== Gênesis, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v1-25-1]]

^<<v1-25-1,1>>^ Abraão se casou outra vez, com uma mulher chamada Quetura.

[[v1-25-2]]

^<<v1-25-2,2>>^ Ela deu à luz Zinrã, Jocsã, Medã, Midiã, Isbaque e Suá.

[[v1-25-3]]

^<<v1-25-3,3>>^ Jocsã gerou Sabá e Dedã. Os descendentes de Dedã foram os assuritas, os letusitas e os leumitas.

[[v1-25-4]]

^<<v1-25-4,4>>^ Os filhos de Midiã foram Efá, Éfer, Enoque, Abida e Elda. Todos eles foram descendentes de Abraão por meio de Quetura.

[[v1-25-5]]

^<<v1-25-5,5>>^ Abraão deu tudo que possuía a seu filho Isaque.

[[v1-25-6]]

^<<v1-25-6,6>>^ Antes de morrer, porém, deu presentes aos filhos de suas concubinas e os separou de Isaque, enviando-os para as terras do leste.

[[v1-25-7]]

^<<v1-25-7,7>>^ Abraão viveu 175 anos

[[v1-25-8]]

^<<v1-25-8,8>>^ e morreu em boa velhice, depois de uma vida longa e feliz. Deu o último suspiro e, ao morrer, reuniu-se a seus antepassados.

[[v1-25-9]]

^<<v1-25-9,9>>^ Seus filhos Isaque e Ismael o sepultaram na caverna de Macpela, perto de Manre, no campo de Efrom, filho de Zoar, o hitita.

[[v1-25-10]]

^<<v1-25-10,10>>^ Esse era o campo que Abraão havia comprado dos hititas e onde havia sepultado Sara, sua mulher.

[[v1-25-11]]

^<<v1-25-11,11>>^ Depois da morte de Abraão, Deus abençoou Isaque, e ele se estabeleceu perto de Beer-Laai-Roi, no Neguebe.

[[v1-25-12]]

^<<v1-25-12,12>>^ Este é o relato da família de Ismael, filho de Abraão com Hagar, serva egípcia de Sara.

[[v1-25-13]]

^<<v1-25-13,13>>^ São estes os descendentes de Ismael por nome e clã: Nebaiote, o mais velho, seguido de Quedar, Adbeel, Misbão,

[[v1-25-14]]

^<<v1-25-14,14>>^ Misma, Dumá, Massá,

[[v1-25-15]]

^<<v1-25-15,15>>^ Hadade, Temá, Jetur, Nafis e Quedemá.

[[v1-25-16]]

^<<v1-25-16,16>>^ Esses doze filhos de Ismael deram origem a doze tribos, cada uma com o nome de seu fundador, relacionadas de acordo com o lugar onde se estabeleceram e acamparam.

[[v1-25-17]]

^<<v1-25-17,17>>^ Ismael viveu 137 anos. Deu o último suspiro e, ao morrer, reuniu-se a seus antepassados.

[[v1-25-18]]

^<<v1-25-18,18>>^ Os descendentes de Ismael ocuparam a região que vai de Havilá a Sur, a leste do Egito, na direção de Assur. Ali, viveram em franca oposição a todos os seus parentes.

[[v1-25-19]]

^<<v1-25-19,19>>^ Este é o relato da família de Isaque, filho de Abraão.

[[v1-25-20]]

^<<v1-25-20,20>>^ Quando Isaque tinha 40 anos, casou-se com Rebeca, filha de Betuel, o arameu de Padã-Arã, e irmã de Labão, o arameu.

[[v1-25-21]]

^<<v1-25-21,21>>^ Isaque orou ao SENHOR em favor de sua mulher, pois ela não podia ter filhos. O SENHOR ouviu a oração de Isaque, e Rebeca ficou grávida de gêmeos.

[[v1-25-22]]

^<<v1-25-22,22>>^ Os dois bebês lutavam um com o outro no ventre da mãe, de modo que ela consultou o SENHOR a esse respeito. "Por que isso está acontecendo comigo?", perguntou ela.

[[v1-25-23]]

^<<v1-25-23,23>>^ O SENHOR respondeu: "Os filhos em seu ventre se tornarão duas nações. Desde o começo, elas serão rivais. Uma nação será mais forte que a outra, e seu filho mais velho servirá a seu filho mais novo".

[[v1-25-24]]

^<<v1-25-24,24>>^ Quando chegou a hora de dar à luz, Rebeca descobriu que, de fato, eram gêmeos.

[[v1-25-25]]

^<<v1-25-25,25>>^ O primeiro a nascer era ruivo e coberto de pelos; por isso o chamaram de Esaú.

[[v1-25-26]]

^<<v1-25-26,26>>^ Depois, nasceu o outro gêmeo, com a mão agarrada ao calcanhar de Esaú; por isso o chamaram de Jacó. Isaque tinha 60 anos quando os gêmeos nasceram.

[[v1-25-27]]

^<<v1-25-27,27>>^ Os meninos cresceram. Esaú se tornou um caçador habilidoso que vivia ao ar livre, enquanto Jacó era mais pacato e preferia ficar em casa.

[[v1-25-28]]

^<<v1-25-28,28>>^ Isaque amava Esaú porque gostava de comer a carne de caça que ele trazia, mas Rebeca amava Jacó.

[[v1-25-29]]

^<<v1-25-29,29>>^ Certo dia, quando Jacó preparava um ensopado, Esaú chegou do deserto, exausto e faminto.

[[v1-25-30]]

^<<v1-25-30,30>>^ "Estou faminto!", disse ele a Jacó. "Dê-me um pouco desse ensopado vermelho!" (Por isso Esaú também ficou conhecido como Edom.)

[[v1-25-31]]

^<<v1-25-31,31>>^ "Está bem", respondeu Jacó. "Mas, em troca, dê-me seus direitos de filho mais velho."

[[v1-25-32]]

^<<v1-25-32,32>>^ "Estou morrendo de fome!", disse Esaú. "De que me servem meus direitos de filho mais velho?"

[[v1-25-33]]

^<<v1-25-33,33>>^ Mas Jacó disse: "Primeiro, jure que seus direitos de filho mais velho agora são meus". Esaú fez um juramento e, desse modo, vendeu todos os seus direitos de filho mais velho a seu irmão, Jacó.

[[v1-25-34]]

^<<v1-25-34,34>>^ Então Jacó deu a Esaú um pedaço de pão e o ensopado de lentilhas. Esaú comeu, levantou-se e foi embora. Assim, ele desprezou seu direito de filho mais velho.

'''

xref:001-genesis/001-genesis-024.adoc#v1-24-0[&#60; Capítulo Anterior] | <<v1-25-0,Topo>> | xref:001-genesis/001-genesis-026.adoc#v1-26-0[Próximo Capítulo &#62;]