include::./index.adoc[]

[[v1-44-0]]
=== Gênesis, 44
// nvt ?, NVT - Nova Versão Transformadora

[[v1-44-1]]

^<<v1-44-1,1>>^ Então José deu a seguinte ordem ao administrador do palácio: "Coloque nos sacos que eles trouxeram todo o cereal que puderem carregar, e coloque o dinheiro de cada um de volta no saco.

[[v1-44-2]]

^<<v1-44-2,2>>^ Depois, coloque meu copo de prata na boca do saco de mantimento do mais novo, junto com o dinheiro dele". O administrador fez tudo conforme José ordenou.

[[v1-44-3]]

^<<v1-44-3,3>>^ Assim que amanheceu, os irmãos se levantaram e partiram com os jumentos carregados.

[[v1-44-4]]

^<<v1-44-4,4>>^ Quando haviam percorrido apenas uma distância curta e mal haviam saído da cidade, José disse ao administrador do palácio: "Vá atrás deles e detenha-os. Quando os alcançar, diga-lhes: ‘Por que retribuíram o bem com o mal?

[[v1-44-5]]

^<<v1-44-5,5>>^ Por que roubaram o copo de prata do meu senhor, que ele usa para prever o futuro? Vocês agiram muito mal!’".

[[v1-44-6]]

^<<v1-44-6,6>>^ Quando o administrador do palácio alcançou os homens, repetiu para eles as palavras de José.

[[v1-44-7]]

^<<v1-44-7,7>>^ "Do que o senhor está falando?", disseram os irmãos. "Somos seus servos e jamais faríamos uma coisa dessas!

[[v1-44-8]]

^<<v1-44-8,8>>^ Por acaso não devolvemos o dinheiro que encontramos nos sacos? Nós o trouxemos de volta da terra de Canaã. Por que roubaríamos ouro ou prata da casa do seu senhor?

[[v1-44-9]]

^<<v1-44-9,9>>^ Se encontrar o copo de prata com um de nós, que morra quem estiver com ele! E nós, os restantes, seremos seus escravos."

[[v1-44-10]]

^<<v1-44-10,10>>^ "Sua proposta é justa", respondeu ele. "Mas apenas aquele que roubou o copo de prata se tornará meu escravo. Os outros estarão livres."

[[v1-44-11]]

^<<v1-44-11,11>>^ Sem demora, eles descarregaram os sacos e os abriram.

[[v1-44-12]]

^<<v1-44-12,12>>^ O administrador do palácio examinou a bagagem de cada um, começando pelo mais velho até o mais novo. E o copo foi encontrado no saco de mantimento de Benjamim.

[[v1-44-13]]

^<<v1-44-13,13>>^ Quando os irmãos viram isso, rasgaram as roupas. Depois, colocaram a carga de volta sobre os jumentos e retornaram à cidade.

[[v1-44-14]]

^<<v1-44-14,14>>^ José ainda estava em seu palácio quando Judá e seus irmãos chegaram, e eles se curvaram até o chão diante dele.

[[v1-44-15]]

^<<v1-44-15,15>>^ "O que vocês fizeram?", exigiu ele. "Não sabem que um homem como eu é capaz de prever o que vai acontecer?"

[[v1-44-16]]

^<<v1-44-16,16>>^ Judá respondeu: "Meu senhor, o que podemos dizer? Que explicação podemos dar? Como podemos provar nossa inocência? Deus está nos castigando por causa de nossa maldade. Todos nós voltamos para ser seus escravos, todos nós, e não apenas nosso irmão com quem foi encontrado o copo de prata".

[[v1-44-17]]

^<<v1-44-17,17>>^ José, no entanto, disse: "Eu jamais faria uma coisa dessas! Apenas o homem que roubou o copo será meu escravo. Os outros podem voltar em paz para a casa de seu pai".

[[v1-44-18]]

^<<v1-44-18,18>>^ Então Judá deu um passo à frente e disse: "Por favor, meu senhor, permita que seu servo lhe diga apenas uma palavra. Peço que não perca a paciência comigo, embora o senhor seja tão poderoso quanto o próprio faraó.

[[v1-44-19]]

^<<v1-44-19,19>>^ "Meu senhor perguntou a nós, seus servos: ‘Vocês têm pai ou irmão?’.

[[v1-44-20]]

^<<v1-44-20,20>>^ E nós respondemos: ‘Sim, meu senhor, nosso pai é idoso e tem um filho mais novo, nascido em sua velhice. O irmão desse filho, por parte de pai e mãe, morreu. Ele é o único filho de sua mãe, e nosso pai o ama muito’.

[[v1-44-21]]

^<<v1-44-21,21>>^ "O senhor nos disse: ‘Tragam-no aqui para que eu possa vê-lo com os próprios olhos’.

[[v1-44-22]]

^<<v1-44-22,22>>^ E nós respondemos: ‘Meu senhor, o rapaz não pode deixar o pai, pois, se o fizesse, o pai morreria’.

[[v1-44-23]]

^<<v1-44-23,23>>^ Mas o senhor nos disse: ‘Vocês não me verão novamente se não trouxerem seu irmão’.

[[v1-44-24]]

^<<v1-44-24,24>>^ "Assim, voltamos para seu servo, nosso pai, e contamos a ele o que o senhor tinha dito.

[[v1-44-25]]

^<<v1-44-25,25>>^ Passado algum tempo, quando ele disse: ‘Voltem e comprem mais mantimentos’,

[[v1-44-26]]

^<<v1-44-26,26>>^ nós respondemos: ‘Só poderemos voltar se nosso irmão mais novo nos acompanhar. Não temos como ver o homem outra vez, a menos que nosso irmão mais novo esteja conosco’.

[[v1-44-27]]

^<<v1-44-27,27>>^ "Então meu pai nos disse: ‘Como vocês sabem, minha mulher teve dois filhos,

[[v1-44-28]]

^<<v1-44-28,28>>^ e um deles foi embora e nunca mais voltou. Sem dúvida, foi despedaçado por algum animal selvagem, e eu nunca mais o vi.

[[v1-44-29]]

^<<v1-44-29,29>>^ Se agora vocês levarem de mim o irmão dele e lhe acontecer algum mal, vocês me mandarão velho e infeliz para a sepultura’.

[[v1-44-30]]

^<<v1-44-30,30>>^ "E agora, meu senhor, não posso voltar para a casa de meu pai sem o rapaz. A vida de nosso pai está ligada à vida do rapaz.

[[v1-44-31]]

^<<v1-44-31,31>>^ Quando ele vir que o rapaz não está conosco, morrerá. Nós, seus servos, seremos, de fato, responsáveis por mandar para a sepultura seu servo, nosso pai, em profunda tristeza.

[[v1-44-32]]

^<<v1-44-32,32>>^ Meu senhor, garanti a meu pai que levaria o rapaz de volta. Disse-lhe: ‘Se não o trouxer de volta, carregarei a culpa para sempre’.

[[v1-44-33]]

^<<v1-44-33,33>>^ "Por isso, peço ao senhor que me permita ficar aqui como escravo no lugar do rapaz e que o deixe voltar com os irmãos dele.

[[v1-44-34]]

^<<v1-44-34,34>>^ Pois, como poderei voltar a meu pai sem o rapaz? Não suportaria ver a angústia que isso lhe causaria!".

'''

xref:001-genesis/001-genesis-043.adoc#v1-43-0[&#60; Capítulo Anterior] | <<v1-44-0,Topo>> | xref:001-genesis/001-genesis-045.adoc#v1-45-0[Próximo Capítulo &#62;]