include::./index.adoc[]

[[v1-45-0]]
=== Gênesis, 45
// nvt ?, NVT - Nova Versão Transformadora

[[v1-45-1]]

^<<v1-45-1,1>>^ José não conseguiu mais se conter. Havia muita gente na sala, e ele disse a seus assistentes: "Saiam todos daqui!". Assim, ficou a sós com seus irmãos e lhes revelou sua identidade.

[[v1-45-2]]

^<<v1-45-2,2>>^ José se emocionou e começou a chorar. Chorou tão alto que os egípcios o ouviram, e logo a notícia chegou ao palácio do faraó.

[[v1-45-3]]

^<<v1-45-3,3>>^ "Sou eu, José!", disse a seus irmãos. "Meu pai ainda está vivo?" Mas seus irmãos ficaram espantados ao se dar conta de que o homem diante deles era José e perderam a fala.

[[v1-45-4]]

^<<v1-45-4,4>>^ "Cheguem mais perto", disse José. Quando eles se aproximaram, José continuou: "Eu sou José, o irmão que vocês venderam como escravo ao Egito.

[[v1-45-5]]

^<<v1-45-5,5>>^ Agora, não fiquem aflitos ou furiosos uns com os outros por terem me vendido para cá. Foi Deus quem me enviou adiante de vocês para lhes preservar a vida.

[[v1-45-6]]

^<<v1-45-6,6>>^ A fome que assola a terra há dois anos continuará por mais cinco anos, e não haverá plantio nem colheita.

[[v1-45-7]]

^<<v1-45-7,7>>^ Deus me enviou adiante para salvar a vida de vocês e de suas famílias, e para salvar muitas vidas.

[[v1-45-8]]

^<<v1-45-8,8>>^ Portanto, foi Deus quem me mandou para cá, e não vocês! E foi ele quem me fez conselheiro do faraó, administrador de todo o seu palácio e governador de todo o Egito.

[[v1-45-9]]

^<<v1-45-9,9>>^ "Agora, voltem depressa a meu pai e digam-lhe: ‘Assim diz seu filho José: Deus me fez senhor de toda a terra do Egito. Venha para cá sem demora!

[[v1-45-10]]

^<<v1-45-10,10>>^ O senhor poderá viver na região de Gósen, onde estará perto de mim com todos os seus filhos e netos, rebanhos e gado, e todos os seus bens.

[[v1-45-11]]

^<<v1-45-11,11>>^ Ali eu cuidarei do senhor, pois ainda haverá cinco anos de escassez. Do contrário, o senhor e toda a sua família perderão tudo que têm’".

[[v1-45-12]]

^<<v1-45-12,12>>^ José acrescentou: "Vejam! Vocês podem comprovar com seus próprios olhos, e também meu irmão Benjamim, que sou eu mesmo, José, que falo com vocês!

[[v1-45-13]]

^<<v1-45-13,13>>^ Contem a meu pai a posição de honra que ocupo aqui no Egito. Descrevam para ele tudo que viram e tragam-no para cá o mais rápido possível".

[[v1-45-14]]

^<<v1-45-14,14>>^ Chorando de alegria, ele abraçou Benjamim, e Benjamim também o abraçou e chorou.

[[v1-45-15]]

^<<v1-45-15,15>>^ Então José beijou cada um de seus irmãos e chorou com eles; depois os irmãos conversaram à vontade com ele.

[[v1-45-16]]

^<<v1-45-16,16>>^ A notícia não demorou a chegar ao palácio do faraó: "Os irmãos de José estão aqui!". O faraó e seus oficiais se alegraram muito quando souberam disso.

[[v1-45-17]]

^<<v1-45-17,17>>^ O faraó disse a José: "Diga a seus irmãos: ‘Coloquem as cargas em seus animais e voltem depressa à terra de Canaã.

[[v1-45-18]]

^<<v1-45-18,18>>^ Tragam seu pai e todas as suas famílias para cá. Eu lhes darei a melhor terra do Egito, e vocês comerão do que esta terra produz de melhor’".

[[v1-45-19]]

^<<v1-45-19,19>>^ O faraó prosseguiu: "Diga a seus irmãos: ‘Levem carruagens do Egito para transportar as crianças pequenas, as mulheres e também seu pai.

[[v1-45-20]]

^<<v1-45-20,20>>^ Não se preocupem com seus pertences, pois o melhor de toda a terra do Egito será de vocês’".

[[v1-45-21]]

^<<v1-45-21,21>>^ Os filhos de Jacó seguiram essas instruções. José providenciou carruagens, conforme o faraó havia ordenado, e lhes deu mantimentos para a viagem.

[[v1-45-22]]

^<<v1-45-22,22>>^ Também presenteou cada irmão com um traje novo, mas a Benjamim deu cinco roupas novas e trezentas peças de prata.

[[v1-45-23]]

^<<v1-45-23,23>>^ E, a seu pai, enviou dez jumentos carregados com os melhores produtos do Egito e dez jumentas carregadas com cereais, pães e outros mantimentos para a viagem.

[[v1-45-24]]

^<<v1-45-24,24>>^ Depois, José se despediu de seus irmãos e, enquanto partiam, disse a eles: "Não briguem no caminho por causa do que aconteceu".

[[v1-45-25]]

^<<v1-45-25,25>>^ Eles saíram do Egito e voltaram a seu pai, Jacó, na terra de Canaã.

[[v1-45-26]]

^<<v1-45-26,26>>^ "José ainda está vivo!", eles disseram a seu pai. "É o governador de toda a terra do Egito!" Jacó ficou atônito com a notícia. Não podia acreditar.

[[v1-45-27]]

^<<v1-45-27,27>>^ Quando, porém, repetiram para Jacó tudo que José lhes tinha dito, e quando ele viu as carruagens que José havia mandado para levá-lo, encheu-se de ânimo.

[[v1-45-28]]

^<<v1-45-28,28>>^ Então Jacó exclamou: "Deve ser verdade! Meu filho José está vivo! Preciso ir e vê-lo antes que eu morra!".

'''

xref:001-genesis/001-genesis-044.adoc#v1-44-0[&#60; Capítulo Anterior] | <<v1-45-0,Topo>> | xref:001-genesis/001-genesis-046.adoc#v1-46-0[Próximo Capítulo &#62;]