include::./index.adoc[]

[[v1-27-0]]
=== Gênesis, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v1-27-1]]

^<<v1-27-1,1>>^ Certo dia, quando Isaque era velho e estava ficando cego, chamou Esaú, seu filho mais velho: "Meu filho!". Esaú respondeu: "Aqui estou!".

[[v1-27-2]]

^<<v1-27-2,2>>^ Isaque disse: "Estou velho e não sei quando vou morrer.

[[v1-27-3]]

^<<v1-27-3,3>>^ Pegue suas armas, o arco e as flechas, e vá ao campo caçar um animal para mim.

[[v1-27-4]]

^<<v1-27-4,4>>^ Depois, prepare meu prato favorito e traga-o aqui para eu comer. Então pronunciarei a bênção que pertence a você, meu filho mais velho, antes de eu morrer".

[[v1-27-5]]

^<<v1-27-5,5>>^ Rebeca, porém, ouviu o que Isaque tinha dito a seu filho Esaú. Quando Esaú saiu para caçar,

[[v1-27-6]]

^<<v1-27-6,6>>^ ela disse a seu filho Jacó: "Ouvi seu pai dizer a Esaú:

[[v1-27-7]]

^<<v1-27-7,7>>^ ‘Traga-me uma carne de caça e prepare-me uma refeição saborosa. Então abençoarei você na presença do SENHOR antes de eu morrer’.

[[v1-27-8]]

^<<v1-27-8,8>>^ Agora, meu filho, preste atenção e faça exatamente o que lhe direi.

[[v1-27-9]]

^<<v1-27-9,9>>^ Vá ao rebanho e traga-me dois dos melhores cabritos. Eu os usarei para preparar o prato favorito de seu pai.

[[v1-27-10]]

^<<v1-27-10,10>>^ Depois, leve a comida para seu pai, para que ele a coma e o abençoe antes de morrer".

[[v1-27-11]]

^<<v1-27-11,11>>^ Jacó respondeu a Rebeca: "Mas meu irmão Esaú é peludo, enquanto eu tenho pele lisa.

[[v1-27-12]]

^<<v1-27-12,12>>^ E se meu pai me tocar? Perceberá que estou tentando enganá-lo e, em vez de me abençoar, me amaldiçoará!".

[[v1-27-13]]

^<<v1-27-13,13>>^ Sua mãe, porém, respondeu: "Que caia sobre mim essa maldição, meu filho! Apenas faça o que lhe digo. Vá e traga-me os cabritos".

[[v1-27-14]]

^<<v1-27-14,14>>^ Jacó foi e trouxe os cabritos para sua mãe. Rebeca os usou para preparar uma refeição saborosa, do jeito que Isaque gostava.

[[v1-27-15]]

^<<v1-27-15,15>>^ Em seguida, pegou as roupas prediletas de Esaú que estavam na casa dela e as entregou a Jacó, seu filho mais novo.

[[v1-27-16]]

^<<v1-27-16,16>>^ Com a pele dos cabritos, cobriu-lhe os braços e a parte lisa do pescoço.

[[v1-27-17]]

^<<v1-27-17,17>>^ Depois, entregou-lhe a refeição saborosa, acompanhada do pão que havia acabado de assar.

[[v1-27-18]]

^<<v1-27-18,18>>^ Jacó levou a comida para o pai e disse: "Meu pai?". "Sim, meu filho", respondeu Isaque. "Quem é você, Esaú ou Jacó?"

[[v1-27-19]]

^<<v1-27-19,19>>^ Jacó disse: "Sou Esaú, seu filho mais velho. Fiz o que o senhor mandou. Aqui está a carne de caça. Sente-se e coma, para que me dê sua bênção".

[[v1-27-20]]

^<<v1-27-20,20>>^ Isaque perguntou: "Como encontrou a caça tão depressa, meu filho?". Jacó respondeu: "O SENHOR, seu Deus, a colocou no meu caminho".

[[v1-27-21]]

^<<v1-27-21,21>>^ Então Isaque disse a Jacó: "Chegue mais perto, para que eu possa tocá-lo e ter certeza de que você é mesmo Esaú".

[[v1-27-22]]

^<<v1-27-22,22>>^ Jacó se aproximou do pai, e Isaque o tocou e disse: "A voz é de Jacó, mas as mãos são de Esaú".

[[v1-27-23]]

^<<v1-27-23,23>>^ Não o reconheceu, porém, pois as mãos de Jacó estavam peludas, como as de Esaú. Assim, Isaque se preparou para abençoar Jacó.

[[v1-27-24]]

^<<v1-27-24,24>>^ "Mas você é mesmo meu filho Esaú?", perguntou ele. "Sim, eu sou", respondeu Jacó.

[[v1-27-25]]

^<<v1-27-25,25>>^ Então Isaque disse: "Agora, meu filho, traga-me a carne de caça. Depois que comer, eu lhe darei a minha bênção". Jacó trouxe a comida para o pai, e Isaque comeu. Também bebeu o vinho que Jacó lhe serviu.

[[v1-27-26]]

^<<v1-27-26,26>>^ Por fim, Isaque disse a Jacó: "Aproxime-se, por favor, e dê-me um beijo, meu filho".

[[v1-27-27]]

^<<v1-27-27,27>>^ Jacó se aproximou e o beijou. Quando Isaque sentiu o cheiro das roupas, finalmente abençoou o filho. Disse: "Ah! O cheiro de meu filho é como o cheiro do campo que o SENHOR abençoou!

[[v1-27-28]]

^<<v1-27-28,28>>^ "Do orvalho do céu e da riqueza da terra, Deus lhe conceda fartas colheitas de cereais e vinho novo de sobra.

[[v1-27-29]]

^<<v1-27-29,29>>^ Que muitas nações o sirvam e se curvem à sua frente. Que você seja senhor de seus irmãos e os filhos de sua mãe se curvem à sua frente. Todos que o amaldiçoarem serão amaldiçoados, e todos que o abençoarem serão abençoados".

[[v1-27-30]]

^<<v1-27-30,30>>^ Assim que Isaque terminou de abençoar Jacó, e logo depois de Jacó ter saído da presença de seu pai, Esaú voltou da caçada.

[[v1-27-31]]

^<<v1-27-31,31>>^ Preparou uma refeição saborosa, levou-a para seu pai e disse: "Sente-se, meu pai, e coma da minha caça, para me abençoar".

[[v1-27-32]]

^<<v1-27-32,32>>^ Isaque lhe perguntou: "Quem é você?". Ele respondeu: "Sou Esaú, seu filho mais velho".

[[v1-27-33]]

^<<v1-27-33,33>>^ Isaque começou a tremer incontrolavelmente e disse: "Então quem me serviu a carne de caça? Acabei de comê-la, pouco antes de você chegar, e abençoei quem a trouxe. Essa bênção deve permanecer!".

[[v1-27-34]]

^<<v1-27-34,34>>^ Quando Esaú ouviu as palavras do pai, soltou um forte grito amargurado e suplicou: "Ah, meu pai, e eu? Abençoe-me também!".

[[v1-27-35]]

^<<v1-27-35,35>>^ Mas Isaque disse: "Seu irmão esteve aqui e me enganou. Levou embora a bênção que pertencia a você!".

[[v1-27-36]]

^<<v1-27-36,36>>^ Esaú exclamou: "Não é de admirar que ele se chame Jacó, pois é a segunda vez que me engana. Primeiro, tomou meus direitos de filho mais velho e, agora, roubou minha bênção. O senhor não guardou uma bênção sequer para mim?".

[[v1-27-37]]

^<<v1-27-37,37>>^ Isaque disse a Esaú: "Fiz de Jacó o seu senhor e declarei que todos os irmãos dele o servirão. Garanti a ele fartura de cereais e vinho. O que me resta para dar a você, meu filho?".

[[v1-27-38]]

^<<v1-27-38,38>>^ Esaú suplicou: "Por acaso o senhor tem apenas uma bênção? Ah, meu pai, abençoe-me também!". Então Esaú chorou em alta voz.

[[v1-27-39]]

^<<v1-27-39,39>>^ Por fim, seu pai, Isaque, lhe disse: "Você viverá longe das riquezas da terra e longe do orvalho do alto céu.

[[v1-27-40]]

^<<v1-27-40,40>>^ Viverá por sua espada e servirá a seu irmão. Quando, porém, conseguir se libertar, sacudirá do pescoço esse jugo".

[[v1-27-41]]

^<<v1-27-41,41>>^ Daquele momento em diante, Esaú passou a odiar Jacó porque seu pai o havia abençoado. Começou a tramar: "Em breve meu pai morrerá. Então, matarei meu irmão Jacó".

[[v1-27-42]]

^<<v1-27-42,42>>^ Quando Rebeca soube das intenções de Esaú, mandou chamar Jacó e lhe disse: "Ouça, Esaú se consola com planos para matar você.

[[v1-27-43]]

^<<v1-27-43,43>>^ Portanto, preste atenção, meu filho. Apronte-se e fuja para a casa de meu irmão Labão, em Harã.

[[v1-27-44]]

^<<v1-27-44,44>>^ Fique lá até que diminua a fúria de seu irmão.

[[v1-27-45]]

^<<v1-27-45,45>>^ Quando ele se acalmar e se esquecer do que você lhe fez, mandarei buscá-lo. Por que eu perderia meus dois filhos no mesmo dia?".

[[v1-27-46]]

^<<v1-27-46,46>>^ Depois, Rebeca disse a Isaque: "Estou cansada dessas mulheres hititas que vivem aqui! Prefiro morrer a ver Jacó se casar com uma delas!".

'''

xref:001-genesis/001-genesis-026.adoc#v1-26-0[&#60; Capítulo Anterior] | <<v1-27-0,Topo>> | xref:001-genesis/001-genesis-028.adoc#v1-28-0[Próximo Capítulo &#62;]