include::./index.adoc[]

[[v1-49-0]]
=== Gênesis, 49
// nvt ?, NVT - Nova Versão Transformadora

[[v1-49-1]]

^<<v1-49-1,1>>^ Então Jacó mandou chamar todos os seus filhos e lhes disse: "Reúnam-se ao meu redor, e eu direi o que acontecerá a cada um de vocês nos dias que virão.

[[v1-49-2]]

^<<v1-49-2,2>>^ "Venham e ouçam, filhos de Jacó, ouçam Israel, seu pai!

[[v1-49-3]]

^<<v1-49-3,3>>^ "Rúben, você é meu filho mais velho, minha força, o filho da minha juventude vigorosa; é o primeiro em importância e o primeiro em poder.

[[v1-49-4]]

^<<v1-49-4,4>>^ É, contudo, impetuoso como uma enchente, e não será mais o primeiro. Pois deitou-se em minha cama, desonrou meu leito conjugal.

[[v1-49-5]]

^<<v1-49-5,5>>^ "Simeão e Levi são iguais em tudo; suas armas são instrumentos de violência.

[[v1-49-6]]

^<<v1-49-6,6>>^ Que eu jamais esteja presente em suas reuniões e nunca participe de seus planos. Pois, em sua ira, mataram homens e, por diversão, aleijaram bois.

[[v1-49-7]]

^<<v1-49-7,7>>^ Maldita seja sua ira, pois é feroz; maldita sua fúria, pois é cruel. Eu os espalharei entre os descendentes de Jacó, eu os dispersarei por todo o Israel.

[[v1-49-8]]

^<<v1-49-8,8>>^ "Judá, seus irmãos o louvarão; você agarrará seus inimigos pelo pescoço, e todos os seus parentes se curvarão à sua frente.

[[v1-49-9]]

^<<v1-49-9,9>>^ Judá, meu filho, é um leão novo que acabou de comer sua presa. Como o leão, ele se agacha, e como a leoa, se deita; quem tem coragem de acordá-lo?

[[v1-49-10]]

^<<v1-49-10,10>>^ O cetro não se afastará de Judá, nem o bastão de autoridade de seus descendentes, até que venha aquele a quem pertence, aquele que todas as nações honrarão.

[[v1-49-11]]

^<<v1-49-11,11>>^ Ele amarra seu potro a uma videira, seu jumentinho a uma videira seleta. Lava suas roupas em vinho, suas vestes, no sangue das uvas.

[[v1-49-12]]

^<<v1-49-12,12>>^ Seus olhos são mais escuros que o vinho, seus dentes, mais brancos que o leite.

[[v1-49-13]]

^<<v1-49-13,13>>^ "Zebulom se estabelecerá à beira-mar e será um porto para os navios; suas fronteiras se estenderão até Sidom.

[[v1-49-14]]

^<<v1-49-14,14>>^ "Issacar é um jumento forte, que descansa entre dois sacos de carga.

[[v1-49-15]]

^<<v1-49-15,15>>^ Quando vir como o campo é bom e como a terra é agradável, curvará seus ombros para a carga e se sujeitará a trabalhos forçados.

[[v1-49-16]]

^<<v1-49-16,16>>^ "Dã governará seu povo, como qualquer outra tribo de Israel.

[[v1-49-17]]

^<<v1-49-17,17>>^ Dã será uma serpente à beira da estrada, uma víbora junto ao caminho que morde o calcanhar do cavalo e faz o cavaleiro cair.

[[v1-49-18]]

^<<v1-49-18,18>>^ Ó SENHOR, espero pelo teu livramento!

[[v1-49-19]]

^<<v1-49-19,19>>^ "Gade será atacado por bandos de saqueadores, mas os atacará quando baterem em retirada.

[[v1-49-20]]

^<<v1-49-20,20>>^ "Aser se alimentará de comidas deliciosas e produzirá iguarias dignas de reis.

[[v1-49-21]]

^<<v1-49-21,21>>^ "Naftali é uma gazela solta que dá à luz lindos filhotes.

[[v1-49-22]]

^<<v1-49-22,22>>^ "José é árvore frutífera, árvore frutífera junto à fonte; seus ramos se estendem por cima do muro.

[[v1-49-23]]

^<<v1-49-23,23>>^ Arqueiros o atacaram brutalmente; atiraram nele e o atormentaram.

[[v1-49-24]]

^<<v1-49-24,24>>^ Seu arco, porém, permaneceu esticado, e seus braços foram fortalecidos pelas mãos do Poderoso de Jacó, pelo Pastor, a Rocha de Israel.

[[v1-49-25]]

^<<v1-49-25,25>>^ Que o Deus de seu pai o ajude; o Todo-poderoso o abençoe com bênçãos dos altos céus, bênçãos das profundezas das águas, bênçãos dos seios e do ventre.

[[v1-49-26]]

^<<v1-49-26,26>>^ Que as bênçãos de seu pai ultrapassem as bênçãos de meus antepassados e alcancem as alturas das antigas colinas. Que essas bênçãos descansem sobre a cabeça de José, que é príncipe entre seus irmãos.

[[v1-49-27]]

^<<v1-49-27,27>>^ "Benjamim é um lobo voraz; pela manhã devora seus inimigos, ao entardecer divide o despojo".

[[v1-49-28]]

^<<v1-49-28,28>>^ Essas são as doze tribos de Israel, e foi isso que seu pai disse ao despedir-se de seus filhos. Deu a cada um deles a bênção que lhe era adequada.

[[v1-49-29]]

^<<v1-49-29,29>>^ Em seguida, Jacó lhes deu a seguinte instrução: "Em breve morrerei e me reunirei a meus antepassados. Sepultem-me com meu pai e com meu avô na caverna no campo de Efrom, o hitita.

[[v1-49-30]]

^<<v1-49-30,30>>^ É a caverna de Macpela, perto de Manre, em Canaã, que Abraão comprou do hitita como sepultura permanente.

[[v1-49-31]]

^<<v1-49-31,31>>^ Ali estão sepultados Abraão e sua mulher, Sara. Ali também estão sepultados Isaque e sua mulher, Rebeca. E ali sepultei Lia.

[[v1-49-32]]

^<<v1-49-32,32>>^ É o campo e a caverna que meu avô, Abraão, comprou dos hititas".

[[v1-49-33]]

^<<v1-49-33,33>>^ Quando Jacó terminou de dar essa instrução a seus filhos, deitou-se em sua cama, deu o último suspiro e, ao morrer, reuniu-se a seus antepassados.

'''

xref:001-genesis/001-genesis-048.adoc#v1-48-0[&#60; Capítulo Anterior] | <<v1-49-0,Topo>> | xref:001-genesis/001-genesis-050.adoc#v1-50-0[Próximo Capítulo &#62;]