include::./index.adoc[]

[[v1-1-0]]
=== Gênesis, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v1-1-1]]

^<<v1-1-1,1>>^ No princípio, Deus criou os céus e a terra.

[[v1-1-2]]

^<<v1-1-2,2>>^ A terra era sem forma e vazia, a escuridão cobria as águas profundas, e o Espírito de Deus se movia sobre a superfície das águas.

[[v1-1-3]]

^<<v1-1-3,3>>^ Então Deus disse: "Haja luz", e houve luz.

[[v1-1-4]]

^<<v1-1-4,4>>^ E Deus viu que a luz era boa, e separou a luz da escuridão.

[[v1-1-5]]

^<<v1-1-5,5>>^ Deus chamou a luz de "dia" e a escuridão de "noite". A noite passou e veio a manhã, encerrando o primeiro dia.

[[v1-1-6]]

^<<v1-1-6,6>>^ Então Deus disse: "Haja um espaço entre as águas, para separar as águas dos céus das águas da terra".

[[v1-1-7]]

^<<v1-1-7,7>>^ E assim aconteceu. Deus criou um espaço para separar as águas da terra das águas dos céus.

[[v1-1-8]]

^<<v1-1-8,8>>^ Deus chamou o espaço de "céu". A noite passou e veio a manhã, encerrando o segundo dia.

[[v1-1-9]]

^<<v1-1-9,9>>^ Então Deus disse: "Juntem-se as águas que estão debaixo do céu num só lugar, para que apareça uma parte seca". E assim aconteceu.

[[v1-1-10]]

^<<v1-1-10,10>>^ Deus chamou a parte seca de "terra" e as águas de "mares". E Deus viu que isso era bom.

[[v1-1-11]]

^<<v1-1-11,11>>^ Então Deus disse: "Produza a terra vegetação: toda espécie de plantas com sementes e árvores que dão frutos com sementes. As sementes produzirão plantas e árvores, cada uma conforme a sua espécie". E assim aconteceu.

[[v1-1-12]]

^<<v1-1-12,12>>^ A terra produziu vegetação: toda espécie de plantas com sementes e árvores que dão frutos com sementes. As sementes produziram plantas e árvores, cada uma conforme a sua espécie. E Deus viu que isso era bom.

[[v1-1-13]]

^<<v1-1-13,13>>^ A noite passou e veio a manhã, encerrando o terceiro dia.

[[v1-1-14]]

^<<v1-1-14,14>>^ Então Deus disse: "Haja luzes no céu para separar o dia da noite e marcar as estações, os dias e os anos.

[[v1-1-15]]

^<<v1-1-15,15>>^ Que essas luzes brilhem no céu para iluminar a terra". E assim aconteceu.

[[v1-1-16]]

^<<v1-1-16,16>>^ Deus criou duas grandes luzes: a maior para governar o dia e a menor para governar a noite, e criou também as estrelas.

[[v1-1-17]]

^<<v1-1-17,17>>^ Deus colocou essas luzes no céu para iluminar a terra,

[[v1-1-18]]

^<<v1-1-18,18>>^ para governar o dia e a noite e para separar a luz da escuridão. E Deus viu que isso era bom.

[[v1-1-19]]

^<<v1-1-19,19>>^ A noite passou e veio a manhã, encerrando o quarto dia.

[[v1-1-20]]

^<<v1-1-20,20>>^ Então Deus disse: "Encham-se as águas de seres vivos, e voem as aves no céu acima da terra".

[[v1-1-21]]

^<<v1-1-21,21>>^ Assim, Deus criou os grandes animais marinhos e todos os seres vivos que se movem em grande número pelas águas, bem como uma grande variedade de aves, cada um conforme a sua espécie. E Deus viu que isso era bom.

[[v1-1-22]]

^<<v1-1-22,22>>^ Então Deus os abençoou: "Sejam férteis e multipliquem-se. Que os seres encham os mares e as aves se multipliquem na terra".

[[v1-1-23]]

^<<v1-1-23,23>>^ A noite passou e veio a manhã, encerrando o quinto dia.

[[v1-1-24]]

^<<v1-1-24,24>>^ Então Deus disse: "Produza a terra grande variedade de animais, cada um conforme a sua espécie: animais domésticos, animais que rastejam pelo chão e animais selvagens". E assim aconteceu.

[[v1-1-25]]

^<<v1-1-25,25>>^ Deus criou grande variedade de animais selvagens, animais domésticos e animais que rastejam pelo chão, cada um conforme a sua espécie. E Deus viu que isso era bom.

[[v1-1-26]]

^<<v1-1-26,26>>^ Então Deus disse: "Façamos o ser humano à nossa imagem; ele será semelhante a nós. Dominará sobre os peixes do mar, sobre as aves do céu, sobre os animais domésticos, sobre todos os animais selvagens da terra e sobre os animais que rastejam pelo chão".

[[v1-1-27]]

^<<v1-1-27,27>>^ Assim, Deus criou os seres humanos à sua própria imagem, à imagem de Deus os criou; homem e mulher os criou.

[[v1-1-28]]

^<<v1-1-28,28>>^ Então Deus os abençoou e disse: "Sejam férteis e multipliquem-se. Encham e governem a terra. Dominem sobre os peixes do mar, sobre as aves do céu e sobre todos os animais que rastejam pelo chão".

[[v1-1-29]]

^<<v1-1-29,29>>^ Então Deus disse: "Vejam! Eu lhes dou todas as plantas com sementes em toda a terra e todas as árvores frutíferas, para que lhes sirvam de alimento.

[[v1-1-30]]

^<<v1-1-30,30>>^ E dou todas as plantas verdes como alimento a todos os seres vivos: aos animais selvagens, às aves do céu e aos animais que rastejam pelo chão". E assim aconteceu.

[[v1-1-31]]

^<<v1-1-31,31>>^ Então Deus olhou para tudo que havia feito e viu que era muito bom. A noite passou e veio a manhã, encerrando o sexto dia.

'''

**&#60; Capítulo Anterior** | <<v1-1-0,Topo>> | xref:001-genesis/001-genesis-002.adoc#v1-2-0[Próximo Capítulo &#62;]