include::./index.adoc[]

[[v1-39-0]]
=== Gênesis, 39
// nvt ?, NVT - Nova Versão Transformadora

[[v1-39-1]]

^<<v1-39-1,1>>^ Quando José foi levado para o Egito pelos negociantes ismaelitas, eles o venderam a Potifar, um oficial egípcio. Potifar era capitão da guarda do faraó, o rei do Egito.

[[v1-39-2]]

^<<v1-39-2,2>>^ O SENHOR estava com José, por isso ele era bem-sucedido em tudo que fazia no serviço da casa de seu senhor egípcio.

[[v1-39-3]]

^<<v1-39-3,3>>^ Potifar percebeu que o SENHOR estava com José e lhe dava sucesso em tudo que ele fazia.

[[v1-39-4]]

^<<v1-39-4,4>>^ Satisfeito com isso, nomeou José seu assistente pessoal e o encarregou de toda a sua casa e de todos os seus bens.

[[v1-39-5]]

^<<v1-39-5,5>>^ A partir do dia em que José foi encarregado de toda a casa e de todas as propriedades de Potifar, o SENHOR começou a abençoar a casa do egípcio por causa de José. Tudo corria bem na casa, e as plantações e os animais prosperavam.

[[v1-39-6]]

^<<v1-39-6,6>>^ Assim, Potifar entregou tudo que possuía aos cuidados de José e, tendo-o como administrador, não se preocupava com nada, exceto com o que iria comer. José era um rapaz muito bonito, de bela aparência,

[[v1-39-7]]

^<<v1-39-7,7>>^ e logo a esposa de Potifar começou a olhar para ele com desejo. "Venha e deite-se comigo", ordenou ela.

[[v1-39-8]]

^<<v1-39-8,8>>^ José recusou e disse: "Meu senhor me confiou todos os bens de sua casa e não precisa se preocupar com nada.

[[v1-39-9]]

^<<v1-39-9,9>>^ Ninguém aqui tem mais autoridade que eu. Ele não me negou coisa alguma, exceto a senhora, pois é mulher dele. Como poderia eu cometer tamanha maldade? Estaria pecando contra Deus!".

[[v1-39-10]]

^<<v1-39-10,10>>^ A mulher continuava a assediar José diariamente, mas ele se recusava a deitar-se com ela.

[[v1-39-11]]

^<<v1-39-11,11>>^ Certo dia, porém, quando José entrou para fazer seu trabalho, não havia mais ninguém na casa.

[[v1-39-12]]

^<<v1-39-12,12>>^ Ela se aproximou, agarrou-o pelo manto e exigiu: "Venha, deite-se comigo!". José se desvencilhou e fugiu da casa, mas o manto ficou na mão da mulher.

[[v1-39-13]]

^<<v1-39-13,13>>^ Quando ela viu que José tinha fugido, mas que o manto havia ficado na mão dela,

[[v1-39-14]]

^<<v1-39-14,14>>^ chamou seus servos. "Vejam!", disse ela. "Meu marido trouxe esse escravo hebreu para nos fazer de bobos! Ele entrou no meu quarto para me violentar, mas eu gritei.

[[v1-39-15]]

^<<v1-39-15,15>>^ Quando ele me ouviu gritar, saiu correndo e escapou, mas largou seu manto comigo."

[[v1-39-16]]

^<<v1-39-16,16>>^ Ela guardou o manto até o marido voltar para casa.

[[v1-39-17]]

^<<v1-39-17,17>>^ Então, contou-lhe sua versão da história. "O escravo hebreu que você trouxe para nossa casa tentou aproveitar-se de mim", disse ela.

[[v1-39-18]]

^<<v1-39-18,18>>^ "Mas, quando eu gritei, ele saiu correndo e largou seu manto comigo!"

[[v1-39-19]]

^<<v1-39-19,19>>^ Ao ouvir a mulher contar como José a havia tratado, Potifar se enfureceu.

[[v1-39-20]]

^<<v1-39-20,20>>^ Pegou José e o lançou na prisão onde ficavam os prisioneiros do rei, e ali José permaneceu.

[[v1-39-21]]

^<<v1-39-21,21>>^ Mas o SENHOR estava com ele na prisão e o tratou com bondade. Fez José conquistar a simpatia do carcereiro, que,

[[v1-39-22]]

^<<v1-39-22,22>>^ em pouco tempo, encarregou José de todos os outros presos e de todas as tarefas da prisão.

[[v1-39-23]]

^<<v1-39-23,23>>^ O carcereiro não precisava mais se preocupar com nada, pois José cuidava de tudo. O SENHOR estava com ele e lhe dava sucesso em tudo que ele fazia.

'''

xref:001-genesis/001-genesis-038.adoc#v1-38-0[&#60; Capítulo Anterior] | <<v1-39-0,Topo>> | xref:001-genesis/001-genesis-040.adoc#v1-40-0[Próximo Capítulo &#62;]