include::./index.adoc[]

[[v1-33-0]]
=== Gênesis, 33
// nvt ?, NVT - Nova Versão Transformadora

[[v1-33-1]]

^<<v1-33-1,1>>^ Jacó levantou os olhos e viu Esaú aproximando-se com seus quatrocentos homens. Assim, dividiu os filhos entre Lia, Raquel e as duas servas.

[[v1-33-2]]

^<<v1-33-2,2>>^ Colocou as servas e os filhos delas à frente, Lia e seus filhos em seguida, e Raquel e José por último.

[[v1-33-3]]

^<<v1-33-3,3>>^ Jacó passou à frente e, ao aproximar-se de seu irmão, curvou-se até o chão sete vezes.

[[v1-33-4]]

^<<v1-33-4,4>>^ Esaú correu ao encontro de Jacó e o abraçou; pôs os braços em volta do pescoço do irmão e o beijou. E os dois choraram.

[[v1-33-5]]

^<<v1-33-5,5>>^ Então Esaú viu as mulheres e as crianças e perguntou: "Quem são estas pessoas que estão com você?". Jacó respondeu: "São os filhos que Deus, em sua bondade, concedeu a seu servo".

[[v1-33-6]]

^<<v1-33-6,6>>^ As servas e seus filhos se aproximaram e se curvaram diante de Esaú.

[[v1-33-7]]

^<<v1-33-7,7>>^ Em seguida, Lia e seus filhos vieram e se curvaram diante dele. Por fim, José e Raquel se aproximaram e se curvaram diante dele.

[[v1-33-8]]

^<<v1-33-8,8>>^ "E o que eram todos aqueles rebanhos que encontrei no caminho?", perguntou Esaú. Jacó respondeu: "São presentes, meu senhor, para garantir sua amizade".

[[v1-33-9]]

^<<v1-33-9,9>>^ "Meu irmão, eu já tenho muitos bens", disse Esaú. "Guarde para você o que é seu."

[[v1-33-10]]

^<<v1-33-10,10>>^ Mas Jacó insistiu: "Não! Se obtive seu favor, peço que aceite meu presente. E que alívio é ver seu sorriso amigável! É como ver a face de Deus!

[[v1-33-11]]

^<<v1-33-11,11>>^ Por favor, aceite o presente que eu lhe trouxe, pois Deus tem sido muito bondoso comigo. Tenho mais que suficiente". Diante da insistência de Jacó, Esaú acabou aceitando o presente.

[[v1-33-12]]

^<<v1-33-12,12>>^ Então Esaú disse: "Vamos andando. Eu o acompanharei".

[[v1-33-13]]

^<<v1-33-13,13>>^ Jacó, porém, respondeu: "Como meu senhor pode ver, algumas das crianças são bem pequenas, e os rebanhos também têm crias. Se os forçarmos demais, mesmo que por um dia, pode ser que os animais morram.

[[v1-33-14]]

^<<v1-33-14,14>>^ Por favor, meu senhor, vá adiante do seu servo. Seguiremos mais devagar, em um ritmo que os rebanhos e as crianças possam acompanhar. Encontrarei com meu senhor em Seir".

[[v1-33-15]]

^<<v1-33-15,15>>^ "Está bem", disse Esaú. "Mas, pelo menos, permita-me deixar alguns dos meus homens para acompanhá-lo." Jacó respondeu: "Não é necessário. Para mim, ter sido bem recebido por meu senhor já é o bastante!".

[[v1-33-16]]

^<<v1-33-16,16>>^ Esaú deu meia-volta e regressou a Seir naquele mesmo dia.

[[v1-33-17]]

^<<v1-33-17,17>>^ Jacó, por sua vez, viajou até Sucote, onde construiu uma casa para si e abrigos para seus rebanhos. Por isso, aquele lugar é chamado de Sucote.

[[v1-33-18]]

^<<v1-33-18,18>>^ Depois de percorrer todo o caminho desde Padã-Arã, Jacó chegou em segurança à cidade de Siquém, na terra de Canaã, e acampou em seus arredores.

[[v1-33-19]]

^<<v1-33-19,19>>^ Jacó comprou da família de Hamor, pai de Siquém, o terreno onde estava acampado, por cem peças de prata.

[[v1-33-20]]

^<<v1-33-20,20>>^ Ali, construiu um altar e o chamou de El-Elohe-Israel.

'''

xref:001-genesis/001-genesis-032.adoc#v1-32-0[&#60; Capítulo Anterior] | <<v1-33-0,Topo>> | xref:001-genesis/001-genesis-034.adoc#v1-34-0[Próximo Capítulo &#62;]