include::./index.adoc[]

[[v1-36-0]]
=== Gênesis, 36
// nvt ?, NVT - Nova Versão Transformadora

[[v1-36-1]]

^<<v1-36-1,1>>^ Este é o relato dos descendentes de Esaú (também chamado Edom).

[[v1-36-2]]

^<<v1-36-2,2>>^ Esaú se casou com duas moças de Canaã: Ada, filha de Elom, o hitita, e Oolibama, filha de Aná e neta de Zibeão, o heveu.

[[v1-36-3]]

^<<v1-36-3,3>>^ Também se casou com sua prima Basemate, que era filha de Ismael e irmã de Nebaiote.

[[v1-36-4]]

^<<v1-36-4,4>>^ Ada deu à luz um filho chamado Elifaz. Basemate deu à luz um filho chamado Reuel.

[[v1-36-5]]

^<<v1-36-5,5>>^ Oolibama deu à luz filhos chamados Jeús, Jalão e Corá. Todos esses filhos nasceram a Esaú na terra de Canaã.

[[v1-36-6]]

^<<v1-36-6,6>>^ Esaú tomou suas mulheres, seus filhos e filhas e todos os de sua casa, além de seus rebanhos e o gado, toda a riqueza que havia adquirido na terra de Canaã, e se mudou para longe de seu irmão, Jacó.

[[v1-36-7]]

^<<v1-36-7,7>>^ Seus rebanhos e bens eram tantos que a terra onde moravam não era suficiente para sustentá-los.

[[v1-36-8]]

^<<v1-36-8,8>>^ Portanto, Esaú (também chamado Edom) se estabeleceu na região montanhosa de Seir.

[[v1-36-9]]

^<<v1-36-9,9>>^ Este é o relato dos descendentes de Esaú, os edomitas, que viviam na região montanhosa de Seir.

[[v1-36-10]]

^<<v1-36-10,10>>^ Estes são os nomes dos filhos de Esaú: Elifaz, filho de Ada, mulher de Esaú; e Reuel, filho de Basemate, mulher de Esaú.

[[v1-36-11]]

^<<v1-36-11,11>>^ Os descendentes de Elifaz foram: Temã, Omar, Zefô, Gaetã e Quenaz.

[[v1-36-12]]

^<<v1-36-12,12>>^ Timna, concubina de Elifaz, filho de Esaú, deu à luz um filho chamado Amaleque. Esses são os descendentes de Ada, mulher de Esaú.

[[v1-36-13]]

^<<v1-36-13,13>>^ Os descendentes de Reuel foram: Naate, Zerá, Samá e Mizá. Esses são os descendentes de Basemate, mulher de Esaú.

[[v1-36-14]]

^<<v1-36-14,14>>^ Esaú também teve filhos com Oolibama, filha de Aná, neta de Zibeão. Seus nomes eram: Jeús, Jalão e Corá.

[[v1-36-15]]

^<<v1-36-15,15>>^ Estes são os descendentes de Esaú que se tornaram chefes de vários clãs: Os descendentes de Elifaz, filho mais velho de Esaú, se tornaram chefes dos clãs de Temã, Omar, Zefô, Quenaz,

[[v1-36-16]]

^<<v1-36-16,16>>^ Corá, Gaetã e Amaleque. Esses são os chefes de clãs descendentes de Elifaz na terra de Edom. Todos eles foram descendentes de Ada, mulher de Esaú.

[[v1-36-17]]

^<<v1-36-17,17>>^ Os descendentes de Reuel, filho de Esaú, se tornaram chefes dos clãs de Naate, Zaerá, Samá e Mizá. Esses são os chefes dos clãs descendentes de Reuel na terra de Edom. Todos eles foram descendentes de Basemate, mulher de Esaú.

[[v1-36-18]]

^<<v1-36-18,18>>^ Os descendentes de Esaú e sua mulher Oolibama se tornaram os chefes dos clãs de Jeús, Jalão e Corá. Esses são os chefes dos clãs descendentes de Oolibama, mulher de Esaú, filha de Aná.

[[v1-36-19]]

^<<v1-36-19,19>>^ Esses são os clãs que descenderam de Esaú (também chamado de Edom), cada um identificado pelo nome de seu chefe.

[[v1-36-20]]

^<<v1-36-20,20>>^ Estes são os nomes das tribos que descenderam de Seir, o horeu, que habitavam na terra de Edom: Lotã, Sobal, Zibeão e Aná,

[[v1-36-21]]

^<<v1-36-21,21>>^ Disom, Ézer e Disã. Estes são os chefes dos clãs horeus, descendentes de Seir, que habitavam na terra de Edom.

[[v1-36-22]]

^<<v1-36-22,22>>^ Os descendentes de Lotã foram: Hori e Hemã. A irmã de Lotã se chamava Timna.

[[v1-36-23]]

^<<v1-36-23,23>>^ Os descendentes de Sobal foram: Alvã, Manaate, Ebal, Sefô e Onã.

[[v1-36-24]]

^<<v1-36-24,24>>^ Os descendentes de Zibeão foram: Aiá e Aná. (Foi este Aná que descobriu as fontes de águas quentes no deserto enquanto levava os jumentos de seu pai para pastar.)

[[v1-36-25]]

^<<v1-36-25,25>>^ Os descendentes de Aná foram: seu filho Disom e sua filha Oolibama.

[[v1-36-26]]

^<<v1-36-26,26>>^ Os descendentes de Disom foram: Hendã, Esbã, Itrã e Querã.

[[v1-36-27]]

^<<v1-36-27,27>>^ Os descendentes de Ézer foram: Bilã, Zaavã e Acã.

[[v1-36-28]]

^<<v1-36-28,28>>^ Os descendentes de Disã foram Uz e Arã.

[[v1-36-29]]

^<<v1-36-29,29>>^ Estes, portanto, foram os chefes dos clãs horeus: Lotã, Sobal, Zibeão, Aná,

[[v1-36-30]]

^<<v1-36-30,30>>^ Disom, Ézer e Disã. Os clãs horeus são identificados pelo nome de seus chefes, que habitavam na terra de Seir.

[[v1-36-31]]

^<<v1-36-31,31>>^ Estes são os reis que governaram na terra de Edom antes de os israelitas terem rei:

[[v1-36-32]]

^<<v1-36-32,32>>^ Belá, filho de Beor, reinou em Edom, na cidade de Dinabá.

[[v1-36-33]]

^<<v1-36-33,33>>^ Quando Belá morreu, Jobabe, filho de Zerá, de Bozra, foi seu sucessor.

[[v1-36-34]]

^<<v1-36-34,34>>^ Quando Jobabe morreu, Husã, da terra dos temanitas, foi seu sucessor.

[[v1-36-35]]

^<<v1-36-35,35>>^ Quando Husã morreu, Hadade, filho de Bedade, foi seu sucessor na cidade de Avite. Foi Hadade quem derrotou os midianitas na terra de Moabe.

[[v1-36-36]]

^<<v1-36-36,36>>^ Quando Hadade morreu, Samlá, da cidade de Masreca, foi seu sucessor.

[[v1-36-37]]

^<<v1-36-37,37>>^ Quando Samlá morreu, Saul, da cidade de Reobote, próxima ao Eufrates, foi seu sucessor.

[[v1-36-38]]

^<<v1-36-38,38>>^ Quando Saul morreu, Baal-Hanã, filho de Acbor, foi seu sucessor.

[[v1-36-39]]

^<<v1-36-39,39>>^ Quando Baal-Hanã, filho de Acbor, morreu, Hadade foi seu sucessor na cidade de Paú. Sua mulher era Meetabel, filha de Matrede e neta de Mezaabe.

[[v1-36-40]]

^<<v1-36-40,40>>^ Estes são os nomes dos chefes dos clãs descendentes de Esaú, que habitavam nos lugares que têm seus nomes: Timna, Alvá, Jetete,

[[v1-36-41]]

^<<v1-36-41,41>>^ Oolibama, Elá, Pinom,

[[v1-36-42]]

^<<v1-36-42,42>>^ Quenaz, Temã, Mibzar,

[[v1-36-43]]

^<<v1-36-43,43>>^ Magdiel e Irã. Esses são os chefes dos clãs de Edom, relacionados de acordo com seus assentamentos na terra que ocupavam. Todos eles foram descendentes de Esaú, antepassado dos edomitas.

'''

xref:001-genesis/001-genesis-035.adoc#v1-35-0[&#60; Capítulo Anterior] | <<v1-36-0,Topo>> | xref:001-genesis/001-genesis-037.adoc#v1-37-0[Próximo Capítulo &#62;]