include::./index.adoc[]

[[v1-22-0]]
=== Gênesis, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v1-22-1]]

^<<v1-22-1,1>>^ Algum tempo depois, Deus pôs Abraão à prova. "Abraão!", Deus chamou. "Sim", respondeu Abraão. "Aqui estou!"

[[v1-22-2]]

^<<v1-22-2,2>>^ Deus disse: "Tome seu filho, seu único filho, Isaque, a quem você tanto ama, e vá à terra de Moriá. Lá, em um dos montes que eu lhe mostrarei, ofereça-o como holocausto".

[[v1-22-3]]

^<<v1-22-3,3>>^ Na manhã seguinte, Abraão se levantou cedo e preparou seu jumento. Levou consigo dois de seus servos e seu filho Isaque. Cortou lenha para o fogo do holocausto e partiu para o lugar que Deus tinha indicado.

[[v1-22-4]]

^<<v1-22-4,4>>^ No terceiro dia da viagem, Abraão levantou os olhos e viu o lugar de longe.

[[v1-22-5]]

^<<v1-22-5,5>>^ "Fiquem aqui com o jumento", disse ele aos servos. "O rapaz e eu iremos mais adiante. Vamos adorar e depois voltaremos."

[[v1-22-6]]

^<<v1-22-6,6>>^ Abraão pôs a lenha para o holocausto nos ombros de Isaque, e ele próprio levou o fogo e a faca. Enquanto os dois caminhavam juntos,

[[v1-22-7]]

^<<v1-22-7,7>>^ Isaque se virou para Abraão e disse: "Pai?". "Sim, meu filho", respondeu Abraão. "Temos fogo e lenha", disse Isaque. "Mas onde está o cordeiro para o holocausto?"

[[v1-22-8]]

^<<v1-22-8,8>>^ "Deus providenciará o cordeiro para o holocausto, meu filho", respondeu Abraão. E continuaram a caminhar juntos.

[[v1-22-9]]

^<<v1-22-9,9>>^ Quando chegaram ao lugar que Deus havia indicado, Abraão construiu um altar e arrumou a lenha sobre ele. Em seguida, amarrou seu filho Isaque e o colocou no altar, sobre a lenha.

[[v1-22-10]]

^<<v1-22-10,10>>^ Então, pegou a faca para sacrificar o filho.

[[v1-22-11]]

^<<v1-22-11,11>>^ Nesse momento, o anjo do SENHOR o chamou do céu: "Abraão! Abraão!". "Aqui estou!", respondeu Abraão.

[[v1-22-12]]

^<<v1-22-12,12>>^ "Não toque no rapaz", disse o anjo. "Não lhe faça mal algum. Agora sei que você teme a Deus de fato. Não me negou nem mesmo seu filho, seu único filho!"

[[v1-22-13]]

^<<v1-22-13,13>>^ Então Abraão levantou os olhos e viu um carneiro preso pelos chifres num arbusto. Pegou o carneiro e o ofereceu como holocausto em lugar do filho.

[[v1-22-14]]

^<<v1-22-14,14>>^ Abraão chamou aquele lugar de Javé-Jiré. Até hoje, as pessoas usam esse nome como provérbio: "No monte do SENHOR se providenciará".

[[v1-22-15]]

^<<v1-22-15,15>>^ Então o anjo do SENHOR chamou Abraão novamente do céu:

[[v1-22-16]]

^<<v1-22-16,16>>^ "Assim diz o SENHOR: Uma vez que você me obedeceu e não me negou nem mesmo seu filho, seu único filho, juro pelo meu nome que

[[v1-22-17]]

^<<v1-22-17,17>>^ certamente o abençoarei. Multiplicarei grandemente seus descendentes, e eles serão como as estrelas no céu e a areia na beira do mar. Seus descendentes conquistarão as cidades de seus inimigos

[[v1-22-18]]

^<<v1-22-18,18>>^ e, por meio deles, todas as nações da terra serão abençoadas. Tudo isso porque você me obedeceu".

[[v1-22-19]]

^<<v1-22-19,19>>^ Então voltaram até onde estavam os servos e partiram para Berseba, onde Abraão continuou a morar.

[[v1-22-20]]

^<<v1-22-20,20>>^ Pouco tempo depois, Abraão ficou sabendo que Milca, mulher de Naor, irmão dele, lhe tinha dado filhos.

[[v1-22-21]]

^<<v1-22-21,21>>^ O mais velho recebeu o nome de Uz, o segundo mais velho, Buz, seguido de Quemuel (antepassado dos arameus),

[[v1-22-22]]

^<<v1-22-22,22>>^ Quésede, Hazo, Pildás, Jidlafe e Betuel

[[v1-22-23]]

^<<v1-22-23,23>>^ (que foi o pai de Rebeca). Esses foram os oito filhos que Milca deu a Naor, irmão de Abraão.

[[v1-22-24]]

^<<v1-22-24,24>>^ Além desses, Reumá, sua concubina, lhe deu quatro filhos: Tebá, Gaã, Taás e Maaca.

'''

xref:001-genesis/001-genesis-021.adoc#v1-21-0[&#60; Capítulo Anterior] | <<v1-22-0,Topo>> | xref:001-genesis/001-genesis-023.adoc#v1-23-0[Próximo Capítulo &#62;]