include::./index.adoc[]

[[v1-13-0]]
=== Gênesis, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v1-13-1]]

^<<v1-13-1,1>>^ Abrão saiu do Egito e subiu para o Neguebe, junto com sua mulher, com Ló e com tudo que possuíam.

[[v1-13-2]]

^<<v1-13-2,2>>^ (Abrão era muito rico e tinha muitos rebanhos, prata e ouro.)

[[v1-13-3]]

^<<v1-13-3,3>>^ Do Neguebe, prosseguiram em sua jornada, acampando ao longo do caminho em direção a Betel. Por fim, armaram as tendas entre Betel e Ai, onde haviam acampado anteriormente,

[[v1-13-4]]

^<<v1-13-4,4>>^ e onde Abrão havia construído um altar. Ali, Abrão invocou o nome do SENHOR outra vez.

[[v1-13-5]]

^<<v1-13-5,5>>^ Ló, que viajava com Abrão, também havia enriquecido e possuía rebanhos de ovelhas, gado e muitas tendas.

[[v1-13-6]]

^<<v1-13-6,6>>^ Os recursos da terra, porém, não eram suficientes para sustentar Abrão e Ló, com todos os seus rebanhos, vivendo tão próximos um do outro.

[[v1-13-7]]

^<<v1-13-7,7>>^ Logo, surgiram desentendimentos entre os pastores de Abrão e os de Ló. (Naquele tempo, os cananeus e os ferezeus também viviam na terra.)

[[v1-13-8]]

^<<v1-13-8,8>>^ Então Abrão disse a Ló: "Não haja conflito entre nós, ou entre nossos pastores. Afinal, somos parentes próximos!

[[v1-13-9]]

^<<v1-13-9,9>>^ A região inteira está à sua disposição. Escolha a parte da terra que desejar e nos separaremos. Se você escolher as terras à esquerda, ficarei com as terras à direita. Se preferir as terras à direita, ficarei com as terras à esquerda".

[[v1-13-10]]

^<<v1-13-10,10>>^ Ló olhou demoradamente para as planícies férteis do vale do Jordão, na direção de Zoar. A região toda era bem irrigada, como o jardim do SENHOR, ou como a terra do Egito. (Isso foi antes de o SENHOR destruir Sodoma e Gomorra.)

[[v1-13-11]]

^<<v1-13-11,11>>^ Ló escolheu para si todo o vale do Jordão a leste de onde estavam. Partiu para lá e se separou de seu tio Abrão.

[[v1-13-12]]

^<<v1-13-12,12>>^ Assim, Abrão continuou na terra de Canaã, e Ló mudou suas tendas para um lugar próximo de Sodoma e se estabeleceu entre as cidades da planície.

[[v1-13-13]]

^<<v1-13-13,13>>^ O povo dessa região, porém, era extremamente perverso e vivia pecando contra o SENHOR.

[[v1-13-14]]

^<<v1-13-14,14>>^ Depois que Ló partiu, o SENHOR disse a Abrão: "Olhe até onde sua vista alcançar, em todas as direções: norte e sul, leste e oeste.

[[v1-13-15]]

^<<v1-13-15,15>>^ Toda esta terra que você está vendo, até onde sua vista alcança, eu dou a você e a seus descendentes como propriedade para sempre.

[[v1-13-16]]

^<<v1-13-16,16>>^ Eu lhe darei tantos descendentes quanto o pó da terra, de modo que, se fosse possível contar o pó da terra, seria possível contar seus descendentes!

[[v1-13-17]]

^<<v1-13-17,17>>^ Vá e percorra a terra em todas as direções, porque eu a dou a você".

[[v1-13-18]]

^<<v1-13-18,18>>^ Então Abrão mudou seu acampamento para Hebrom e se estabeleceu junto ao bosque de carvalhos que pertencia a Manre. Ali, construiu mais um altar ao SENHOR.

'''

xref:001-genesis/001-genesis-012.adoc#v1-12-0[&#60; Capítulo Anterior] | <<v1-13-0,Topo>> | xref:001-genesis/001-genesis-014.adoc#v1-14-0[Próximo Capítulo &#62;]