include::./index.adoc[]

[[v1-35-0]]
=== Gênesis, 35
// nvt ?, NVT - Nova Versão Transformadora

[[v1-35-1]]

^<<v1-35-1,1>>^ Deus disse a Jacó: "Apronte-se, mude-se para Betel e estabeleça-se ali. Ao chegar, construa um altar para o Deus que lhe apareceu quando você estava fugindo de seu irmão, Esaú".

[[v1-35-2]]

^<<v1-35-2,2>>^ Jacó disse à sua família e a todos que estavam com ele: "Joguem fora todos os seus ídolos pagãos, purifiquem-se e vistam roupas limpas.

[[v1-35-3]]

^<<v1-35-3,3>>^ Vamos a Betel, onde construirei um altar para o Deus que respondeu às minhas orações quando eu estava angustiado. Ele tem estado comigo por onde ando".

[[v1-35-4]]

^<<v1-35-4,4>>^ Então entregaram a Jacó todos os ídolos pagãos e as argolas que usavam nas orelhas, e ele os enterrou ao pé da grande árvore perto de Siquém.

[[v1-35-5]]

^<<v1-35-5,5>>^ Quando partiram, o terror de Deus se espalhou de tal forma entre os moradores das cidades próximas que ninguém atacou a família de Jacó.

[[v1-35-6]]

^<<v1-35-6,6>>^ Por fim, Jacó e todos que estavam com ele chegaram a Luz (também chamada Betel), em Canaã.

[[v1-35-7]]

^<<v1-35-7,7>>^ Jacó construiu um altar ali e chamou o lugar de El-Betel, pois Deus lhe havia aparecido em Betel quando ele estava fugindo de seu irmão.

[[v1-35-8]]

^<<v1-35-8,8>>^ Pouco tempo depois, Débora, a serva que havia amamentado Rebeca, morreu e foi sepultada ao pé do carvalho no vale perto de Betel. Desde então, a árvore é chamada de Alom-Bacute.

[[v1-35-9]]

^<<v1-35-9,9>>^ Agora que Jacó havia regressado de Padã-Arã, Deus lhe apareceu outra vez em Betel e o abençoou:

[[v1-35-10]]

^<<v1-35-10,10>>^ "Seu nome é Jacó, mas você não se chamará mais Jacó. De agora em diante, seu nome será Israel". Assim, Deus deu a ele o nome de Israel.

[[v1-35-11]]

^<<v1-35-11,11>>^ Deus também lhe disse: "Eu sou o Deus Todo-poderoso. Seja fértil e multiplique-se. Você se tornará uma grande nação, até mesmo muitas nações. Haverá reis entre seus descendentes.

[[v1-35-12]]

^<<v1-35-12,12>>^ Eu lhe darei a terra que dei a Abraão e Isaque. Sim, eu a darei a você e a seus descendentes".

[[v1-35-13]]

^<<v1-35-13,13>>^ Em seguida, Deus se elevou do lugar onde havia falado a Jacó.

[[v1-35-14]]

^<<v1-35-14,14>>^ Jacó levantou uma coluna de pedra para marcar o lugar onde Deus lhe havia falado. Depois, derramou vinho sobre a coluna, como oferta a Deus, e a ungiu com azeite de oliva.

[[v1-35-15]]

^<<v1-35-15,15>>^ Chamou o lugar de Betel, pois ali Deus lhe havia falado.

[[v1-35-16]]

^<<v1-35-16,16>>^ Depois que partiram de Betel, rumaram para Efrata. Raquel, porém, sentiu fortes dores e entrou em trabalho de parto quando ainda estavam a certa distância da cidade.

[[v1-35-17]]

^<<v1-35-17,17>>^ As dores de parto aumentaram, e a parteira lhe disse: "Não tenha medo! Você terá outro menino!".

[[v1-35-18]]

^<<v1-35-18,18>>^ Raquel estava quase morrendo, mas, com seu último suspiro, chamou o menino de Benoni. O pai do bebê, no entanto, o chamou de Benjamim.

[[v1-35-19]]

^<<v1-35-19,19>>^ Assim, Raquel morreu e foi sepultada junto ao caminho para Efrata (ou seja, Belém).

[[v1-35-20]]

^<<v1-35-20,20>>^ Sobre o túmulo de Raquel, Jacó levantou um monumento de pedra, que está lá até hoje.

[[v1-35-21]]

^<<v1-35-21,21>>^ Então Jacó seguiu viagem e acampou além de Migdal-Éder.

[[v1-35-22]]

^<<v1-35-22,22>>^ Enquanto moravam ali, Rúben teve relações com Bila, concubina de seu pai, e Jacó ficou sabendo disso. Estes são os nomes dos doze filhos de Jacó:

[[v1-35-23]]

^<<v1-35-23,23>>^ Os filhos de Lia foram Rúben (o filho mais velho de Jacó), Simeão, Levi, Judá, Issacar e Zebulom.

[[v1-35-24]]

^<<v1-35-24,24>>^ Os filhos de Raquel foram José e Benjamim.

[[v1-35-25]]

^<<v1-35-25,25>>^ Os filhos de Bila, serva de Raquel, foram Dã e Naftali.

[[v1-35-26]]

^<<v1-35-26,26>>^ Os filhos de Zilpa, serva de Lia, foram Gade e Aser. Esses são os filhos que nasceram a Jacó em Padã-Arã.

[[v1-35-27]]

^<<v1-35-27,27>>^ Então Jacó voltou à casa de seu pai, Isaque, em Manre, perto de Quiriate-Arba (hoje chamada Hebrom), onde Abraão e Isaque viveram como estrangeiros.

[[v1-35-28]]

^<<v1-35-28,28>>^ Isaque viveu 180 anos.

[[v1-35-29]]

^<<v1-35-29,29>>^ Deu o último suspiro e, ao morrer em boa velhice, reuniu-se a seus antepassados. Seus filhos, Esaú e Jacó, o sepultaram.

'''

xref:001-genesis/001-genesis-034.adoc#v1-34-0[&#60; Capítulo Anterior] | <<v1-35-0,Topo>> | xref:001-genesis/001-genesis-036.adoc#v1-36-0[Próximo Capítulo &#62;]