include::./index.adoc[]

[[v1-12-0]]
=== Gênesis, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v1-12-1]]

^<<v1-12-1,1>>^ O SENHOR tinha dito a Abrão: "Deixe sua terra natal, seus parentes e a família de seu pai e vá à terra que eu lhe mostrarei.

[[v1-12-2]]

^<<v1-12-2,2>>^ Farei de você uma grande nação, o abençoarei e o tornarei famoso, e você será uma bênção para outros.

[[v1-12-3]]

^<<v1-12-3,3>>^ Abençoarei os que o abençoarem e amaldiçoarei os que o amaldiçoarem. Por meio de você, todas as famílias da terra serão abençoadas".

[[v1-12-4]]

^<<v1-12-4,4>>^ Então Abrão partiu, como o SENHOR havia instruído, e Ló foi com ele. Abrão tinha 75 anos quando saiu de Harã.

[[v1-12-5]]

^<<v1-12-5,5>>^ Tomou sua mulher, Sarai, seu sobrinho Ló e todos os seus bens, os rebanhos e os servos que havia agregado à sua casa em Harã, e seguiu para a terra de Canaã. Quando chegaram a Canaã,

[[v1-12-6]]

^<<v1-12-6,6>>^ Abrão atravessou a terra até Siquém, onde acampou junto ao carvalho de Moré. Naquele tempo, os cananeus habitavam a região.

[[v1-12-7]]

^<<v1-12-7,7>>^ Então o SENHOR apareceu a Abrão e disse: "Darei esta terra a seus descendentes". Abrão construiu um altar ali e o dedicou ao SENHOR, que lhe havia aparecido.

[[v1-12-8]]

^<<v1-12-8,8>>^ Dali, Abrão viajou para o sul e acampou na região montanhosa, entre Betel, a oeste, e Ai, a leste. Construiu ali mais um altar dedicado ao SENHOR e invocou o nome do SENHOR.

[[v1-12-9]]

^<<v1-12-9,9>>^ Abrão prosseguiu em sua jornada para o sul, acampando ao longo do caminho em direção ao Neguebe.

[[v1-12-10]]

^<<v1-12-10,10>>^ Naquele tempo, uma fome terrível atingiu a terra de Canaã, e Abrão foi obrigado a descer ao Egito, onde viveu como estrangeiro.

[[v1-12-11]]

^<<v1-12-11,11>>^ Aproximando-se da fronteira do Egito, Abrão disse a Sarai, sua mulher: "Você é muito bonita.

[[v1-12-12]]

^<<v1-12-12,12>>^ Quando os egípcios a virem, dirão: ‘É mulher dele. Vamos matá-lo para ficarmos com ela’.

[[v1-12-13]]

^<<v1-12-13,13>>^ Diga, portanto, que é minha irmã. Eles pouparão minha vida e, por sua causa, me tratarão bem".

[[v1-12-14]]

^<<v1-12-14,14>>^ De fato, chegando Abrão ao Egito, todos notaram a grande beleza de sua mulher.

[[v1-12-15]]

^<<v1-12-15,15>>^ Quando os oficiais do palácio a viram, falaram maravilhas dela ao faraó e a levaram para o palácio.

[[v1-12-16]]

^<<v1-12-16,16>>^ Por causa de Sarai, o faraó deu muitos presentes a Abrão: ovelhas, bois, jumentos e jumentas, servos e servas, e camelos.

[[v1-12-17]]

^<<v1-12-17,17>>^ Mas, por causa de Sarai, mulher de Abrão, o SENHOR enviou pragas terríveis sobre o faraó e sobre os membros de sua casa.

[[v1-12-18]]

^<<v1-12-18,18>>^ Por isso, o faraó mandou chamar Abrão e disse: "O que você fez comigo? Por que não me disse que ela era sua mulher?

[[v1-12-19]]

^<<v1-12-19,19>>^ Por que disse que era sua irmã e permitiu que eu a tomasse como esposa? Aqui está sua mulher. Tome-a e vá embora daqui!".

[[v1-12-20]]

^<<v1-12-20,20>>^ O faraó ordenou que alguns de seus homens escoltassem Abrão, com sua mulher e todos os seus bens, para fora de sua terra.

'''

xref:001-genesis/001-genesis-011.adoc#v1-11-0[&#60; Capítulo Anterior] | <<v1-12-0,Topo>> | xref:001-genesis/001-genesis-013.adoc#v1-13-0[Próximo Capítulo &#62;]