include::./index.adoc[]

[[v1-21-0]]
=== Gênesis, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v1-21-1]]

^<<v1-21-1,1>>^ O SENHOR agiu em favor de Sara e cumpriu o que lhe tinha prometido.

[[v1-21-2]]

^<<v1-21-2,2>>^ Ela engravidou e deu à luz um filho para Abraão na velhice dele, exatamente no tempo indicado por Deus.

[[v1-21-3]]

^<<v1-21-3,3>>^ Abraão deu o nome Isaque ao filho que Sara lhe deu.

[[v1-21-4]]

^<<v1-21-4,4>>^ No oitavo dia depois do nascimento de Isaque, Abraão o circuncidou, como Deus havia ordenado.

[[v1-21-5]]

^<<v1-21-5,5>>^ Abraão tinha 100 anos quando Isaque nasceu.

[[v1-21-6]]

^<<v1-21-6,6>>^ Sara declarou: "Deus me fez sorrir. Todos que ficarem sabendo do que aconteceu vão rir comigo!".

[[v1-21-7]]

^<<v1-21-7,7>>^ E disse mais: "Quem diria a Abraão que sua mulher amamentaria um bebê? E, no entanto, em sua velhice, eu lhe dei um filho!".

[[v1-21-8]]

^<<v1-21-8,8>>^ Quando Isaque cresceu e estava para ser desmamado, Abraão preparou uma grande festa para comemorar a ocasião.

[[v1-21-9]]

^<<v1-21-9,9>>^ Sara, porém, viu Ismael, filho de Abraão e da serva egípcia Hagar, caçoar de seu filho, Isaque,

[[v1-21-10]]

^<<v1-21-10,10>>^ e disse a Abraão: "Livre-se da escrava e do filho dela! Ele jamais será herdeiro junto com meu filho, Isaque!".

[[v1-21-11]]

^<<v1-21-11,11>>^ Abraão ficou muito perturbado com isso, pois Ismael era seu filho.

[[v1-21-12]]

^<<v1-21-12,12>>^ Deus, porém, lhe disse: "Não se perturbe por causa do menino e da serva. Faça tudo que Sara lhe pedir, pois Isaque é o filho de quem depende a sua descendência.

[[v1-21-13]]

^<<v1-21-13,13>>^ Contudo, também farei uma nação dos descendentes do filho de Hagar, pois ele é seu filho".

[[v1-21-14]]

^<<v1-21-14,14>>^ Na manhã seguinte, Abraão se levantou cedo, preparou mantimentos e uma vasilha cheia de água e os pôs sobre os ombros de Hagar. Então, mandou-a embora com seu filho, e ela andou sem rumo pelo deserto de Berseba.

[[v1-21-15]]

^<<v1-21-15,15>>^ Quando acabou a água, Hagar colocou o menino à sombra de um arbusto

[[v1-21-16]]

^<<v1-21-16,16>>^ e foi sentar-se sozinha, uns cem metros adiante. "Não quero ver o menino morrer", disse ela, chorando sem parar.

[[v1-21-17]]

^<<v1-21-17,17>>^ Mas Deus ouviu o choro do menino e, do céu, o anjo de Deus chamou Hagar: "Que foi, Hagar? Não tenha medo! Deus ouviu o menino chorar, dali onde ele está.

[[v1-21-18]]

^<<v1-21-18,18>>^ Levante-o e anime-o, pois farei dos descendentes dele uma grande nação".

[[v1-21-19]]

^<<v1-21-19,19>>^ Então Deus abriu os olhos de Hagar, e ela viu um poço cheio de água. Sem demora, encheu a vasilha de água e deu para o menino beber.

[[v1-21-20]]

^<<v1-21-20,20>>^ Deus estava com o menino enquanto ele crescia no deserto. Ismael se tornou flecheiro

[[v1-21-21]]

^<<v1-21-21,21>>^ e se estabeleceu no deserto de Parã, e sua mãe conseguiu para ele uma esposa egípcia.

[[v1-21-22]]

^<<v1-21-22,22>>^ Por esse tempo, Abimeleque, acompanhado de Ficol, comandante do seu exército, foi visitar Abraão. "É evidente que Deus está com você, ajudando-o em tudo que faz", disse Abimeleque.

[[v1-21-23]]

^<<v1-21-23,23>>^ "Jure, em nome de Deus, que não enganará nem a mim, nem a meus filhos, nem a nenhum de meus descendentes. Tenho sido leal a você, por isso jure que será leal a mim e a esta terra onde vive como estrangeiro."

[[v1-21-24]]

^<<v1-21-24,24>>^ Abraão respondeu: "Eu juro!".

[[v1-21-25]]

^<<v1-21-25,25>>^ Contudo, Abraão reclamou com Abimeleque sobre um poço que os servos de Abimeleque lhe haviam tomado à força.

[[v1-21-26]]

^<<v1-21-26,26>>^ "Eu não sabia disso", respondeu Abimeleque. "Não faço ideia de quem seja o responsável. Você nunca se queixou a esse respeito."

[[v1-21-27]]

^<<v1-21-27,27>>^ Então Abraão deu ovelhas e bois a Abimeleque, e os dois fizeram um acordo.

[[v1-21-28]]

^<<v1-21-28,28>>^ Quando Abraão também separou do rebanho mais sete cordeirinhas,

[[v1-21-29]]

^<<v1-21-29,29>>^ Abimeleque lhe perguntou: "Por que você separou estas sete das demais?".

[[v1-21-30]]

^<<v1-21-30,30>>^ Abraão respondeu: "Por favor, aceite estas sete cordeirinhas como testemunho de que eu cavei este poço".

[[v1-21-31]]

^<<v1-21-31,31>>^ Por isso Abraão chamou o lugar de Berseba, porque ali os dois fizeram o juramento.

[[v1-21-32]]

^<<v1-21-32,32>>^ Depois de firmarem a aliança em Berseba, Abimeleque e Ficol, comandante do seu exército, voltaram para a terra dos filisteus.

[[v1-21-33]]

^<<v1-21-33,33>>^ Abraão plantou uma tamargueira em Berseba e ali invocou o nome do SENHOR, o Deus Eterno.

[[v1-21-34]]

^<<v1-21-34,34>>^ E Abraão morou na terra dos filisteus como estrangeiro por longo tempo.

'''

xref:001-genesis/001-genesis-020.adoc#v1-20-0[&#60; Capítulo Anterior] | <<v1-21-0,Topo>> | xref:001-genesis/001-genesis-022.adoc#v1-22-0[Próximo Capítulo &#62;]