include::./index.adoc[]

[[v1-29-0]]
=== Gênesis, 29
// nvt ?, NVT - Nova Versão Transformadora

[[v1-29-1]]

^<<v1-29-1,1>>^ Jacó seguiu viagem e, por fim, chegou à terra do leste.

[[v1-29-2]]

^<<v1-29-2,2>>^ Viu um poço ao longe e, junto ao poço, no campo, três rebanhos de ovelhas, à espera de que lhes dessem água. Uma pedra pesada cobria a boca do poço.

[[v1-29-3]]

^<<v1-29-3,3>>^ Era costume naquele lugar esperar que todos os rebanhos chegassem para, então, remover a pedra e dar água aos animais. Depois, a pedra era recolocada na boca do poço.

[[v1-29-4]]

^<<v1-29-4,4>>^ Jacó se aproximou dos pastores e perguntou: "De onde vocês são, amigos?". "Somos de Harã", disseram eles.

[[v1-29-5]]

^<<v1-29-5,5>>^ "Conhecem um homem chamado Labão, neto de Naor?", perguntou Jacó. "Sim, conhecemos", responderam eles.

[[v1-29-6]]

^<<v1-29-6,6>>^ "Ele vai bem?", perguntou Jacó. "Sim, vai bem", disseram. "Olhe, ali vem Raquel, filha dele, com o rebanho."

[[v1-29-7]]

^<<v1-29-7,7>>^ Jacó disse: "Ainda é dia claro, cedo demais para recolher os animais. Por que vocês não dão de beber às ovelhas, para que elas possam voltar a pastar?".

[[v1-29-8]]

^<<v1-29-8,8>>^ "Não podemos dar de beber aos animais enquanto não chegarem todos os rebanhos", responderam. "Só então os pastores removem a pedra da boca do poço e damos de beber a todas as ovelhas."

[[v1-29-9]]

^<<v1-29-9,9>>^ Jacó ainda conversava com eles quando Raquel chegou com o rebanho de seu pai, pois era pastora.

[[v1-29-10]]

^<<v1-29-10,10>>^ Uma vez que Raquel era sua prima, filha de Labão, irmão de sua mãe, e as ovelhas pertenciam a seu tio Labão, Jacó foi até o poço, removeu a pedra que o cobria e deu de beber ao rebanho de seu tio.

[[v1-29-11]]

^<<v1-29-11,11>>^ Então Jacó beijou Raquel e chorou em alta voz.

[[v1-29-12]]

^<<v1-29-12,12>>^ Explicou para Raquel que era seu primo por parte do pai dela e filho de Rebeca, tia dela. Raquel foi correndo contar a seu pai, Labão.

[[v1-29-13]]

^<<v1-29-13,13>>^ Assim que Labão soube que seu sobrinho Jacó havia chegado, correu ao seu encontro. Ele o abraçou, o beijou e o levou para casa. Depois que Jacó lhe contou sua história,

[[v1-29-14]]

^<<v1-29-14,14>>^ Labão exclamou: "Você é, de fato, sangue do meu sangue!". Quando Jacó estava na casa de Labão havia cerca de um mês,

[[v1-29-15]]

^<<v1-29-15,15>>^ Labão lhe disse: "Você não deve trabalhar de graça para mim só porque somos parentes. Diga-me qual deve ser o seu salário".

[[v1-29-16]]

^<<v1-29-16,16>>^ Labão tinha duas filhas. A mais velha se chamava Lia, e a mais nova, Raquel.

[[v1-29-17]]

^<<v1-29-17,17>>^ Os olhos de Lia eram sem brilho, mas Raquel tinha bela aparência e rosto atraente.

[[v1-29-18]]

^<<v1-29-18,18>>^ Visto que Jacó estava apaixonado por Raquel, disse a Labão: "Trabalharei para o senhor por sete anos se me der Raquel, sua filha mais nova, para ser minha esposa".

[[v1-29-19]]

^<<v1-29-19,19>>^ "Melhor entregá-la a você do que a qualquer outro", respondeu Labão. "Fique aqui e trabalhe comigo."

[[v1-29-20]]

^<<v1-29-20,20>>^ Então Jacó trabalhou sete anos por Raquel. Ele a amava tanto que lhe pareceram apenas alguns dias.

[[v1-29-21]]

^<<v1-29-21,21>>^ Chegada a hora, Jacó disse a Labão. "Cumpri minha parte do acordo. Agora, dê-me minha esposa, para que eu me deite com ela."

[[v1-29-22]]

^<<v1-29-22,22>>^ Labão convidou toda a vizinhança e preparou uma grande festa de casamento.

[[v1-29-23]]

^<<v1-29-23,23>>^ À noite, porém, quando estava escuro, Labão tomou Lia e a entregou a Jacó, e Jacó se deitou com ela.

[[v1-29-24]]

^<<v1-29-24,24>>^ (Labão deu sua serva Zilpa a Lia para servi-la.)

[[v1-29-25]]

^<<v1-29-25,25>>^ Na manhã seguinte, quando Jacó acordou, viu que era Lia. Então Jacó perguntou a Labão: "O que o senhor fez comigo? Trabalhei sete anos por Raquel! Por que o senhor me enganou?".

[[v1-29-26]]

^<<v1-29-26,26>>^ Labão respondeu: "Aqui não é costume casar a filha mais nova antes da mais velha.

[[v1-29-27]]

^<<v1-29-27,27>>^ Espere, contudo, até terminar a semana de núpcias, e eu também lhe entregarei Raquel, desde que você prometa trabalhar mais sete anos para mim".

[[v1-29-28]]

^<<v1-29-28,28>>^ Jacó concordou em trabalhar mais sete anos. Uma semana depois de Jacó ter se casado com Lia, Labão lhe entregou Raquel.

[[v1-29-29]]

^<<v1-29-29,29>>^ (Labão deu sua serva Bila a Raquel para servi-la.)

[[v1-29-30]]

^<<v1-29-30,30>>^ Jacó se deitou também com Raquel, a quem ele amava muito mais que a Lia. Então permaneceu ali e trabalhou mais sete anos para Labão.

[[v1-29-31]]

^<<v1-29-31,31>>^ Quando o SENHOR viu que Lia não era amada, permitiu que ela tivesse filhos; Raquel, porém, era estéril.

[[v1-29-32]]

^<<v1-29-32,32>>^ Lia engravidou e deu à luz um filho. Chamou-o de Rúben, pois disse: "O SENHOR viu minha infelicidade, e agora meu marido me amará".

[[v1-29-33]]

^<<v1-29-33,33>>^ Pouco tempo depois, Lia engravidou novamente e deu à luz outro filho. Chamou-o de Simeão, pois disse: "O SENHOR ouviu que eu não era amada e me deu outro filho".

[[v1-29-34]]

^<<v1-29-34,34>>^ Lia engravidou pela terceira vez e deu à luz outro filho. Chamou-o de Levi, pois disse: "Certamente, desta vez meu marido terá afeição por mim, pois lhe dei três filhos!".

[[v1-29-35]]

^<<v1-29-35,35>>^ Lia engravidou mais uma vez e deu à luz outro filho. Chamou-o de Judá, pois disse: "Agora louvarei ao SENHOR!". Então, parou de ter filhos.

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]