include::./index.adoc[]

[[v1-48-0]]
=== Gênesis, 48
// nvt ?, NVT - Nova Versão Transformadora

[[v1-48-1]]

^<<v1-48-1,1>>^ Certo dia, não muito tempo depois, avisaram José: "Seu pai está bastante doente". José foi visitá-lo e levou consigo seus dois filhos, Manassés e Efraim.

[[v1-48-2]]

^<<v1-48-2,2>>^ Quando José chegou, anunciaram a Jacó: "Seu filho José está aqui para vê-lo". Com as forças que lhe restavam, Jacó se sentou na cama.

[[v1-48-3]]

^<<v1-48-3,3>>^ Jacó disse a José: "O Deus Todo-poderoso me apareceu em Luz, na terra de Canaã, e me abençoou.

[[v1-48-4]]

^<<v1-48-4,4>>^ Ele me disse: ‘Eu o tornarei fértil e multiplicarei seus descendentes. Farei de você muitas nações e darei esta terra de Canaã a seus descendentes como propriedade permanente’.

[[v1-48-5]]

^<<v1-48-5,5>>^ "Agora, tomo para mim, como meus próprios filhos, seus dois rapazes, Efraim e Manassés, nascidos aqui na terra do Egito antes de minha chegada. Eles serão meus filhos, como são Rúben e Simeão.

[[v1-48-6]]

^<<v1-48-6,6>>^ Os filhos que você tiver depois deles, porém, serão seus e herdarão propriedades dentro do território dos irmãos deles, Efraim e Manassés.

[[v1-48-7]]

^<<v1-48-7,7>>^ "Muito tempo atrás, quando eu voltava de Padã-Arã, Raquel morreu na terra de Canaã. Ainda estávamos viajando, a certa distância de Efrata (ou seja, Belém). Com grande tristeza, sepultei-a ali mesmo, junto ao caminho para Efrata".

[[v1-48-8]]

^<<v1-48-8,8>>^ Em seguida, Jacó olhou para os dois rapazes e perguntou: "Quem são estes?".

[[v1-48-9]]

^<<v1-48-9,9>>^ José respondeu: "Estes são os filhos que Deus me deu aqui no Egito". Jacó disse: "Traga-os mais perto, para que eu os abençoe".

[[v1-48-10]]

^<<v1-48-10,10>>^ Os olhos de Jacó estavam enfraquecidos por causa da idade, e ele quase não conseguia enxergar. José levou os rapazes para perto dele, e Jacó os beijou e abraçou.

[[v1-48-11]]

^<<v1-48-11,11>>^ Então Jacó disse a José: "Nunca imaginei que voltaria a ver seu rosto, mas agora Deus me permitiu ver também seus filhos!".

[[v1-48-12]]

^<<v1-48-12,12>>^ José tirou os rapazes de junto dos joelhos do avô e se curvou com o rosto no chão.

[[v1-48-13]]

^<<v1-48-13,13>>^ Em seguida, colocou os rapazes na frente de Jacó. Com a mão direita, colocou Efraim diante da mão esquerda de Jacó e, com a mão esquerda, colocou Manassés sob a mão direita de Jacó.

[[v1-48-14]]

^<<v1-48-14,14>>^ Mas, ao estender as mãos para colocá-las sobre a cabeça dos rapazes, Jacó cruzou os braços. Pôs a mão direita sobre a cabeça de Efraim, embora fosse o mais novo, e a mão esquerda sobre a cabeça de Manassés, embora fosse o mais velho.

[[v1-48-15]]

^<<v1-48-15,15>>^ Em seguida, abençoou José, dizendo: "Que o Deus diante do qual andaram meu avô, Abraão, e meu pai, Isaque, o Deus que tem sido meu pastor toda a minha vida, até o dia de hoje,

[[v1-48-16]]

^<<v1-48-16,16>>^ o Anjo que me resgatou de todo o mal, abençoe estes rapazes. Que eles preservem meu nome e o nome de Abraão e Isaque, e seus descendentes se multipliquem grandemente na terra".

[[v1-48-17]]

^<<v1-48-17,17>>^ José, porém, não se agradou quando viu o pai colocar a mão direita sobre a cabeça de Efraim. Por isso, levantou-a para passá-la da cabeça de Efraim para a cabeça de Manassés.

[[v1-48-18]]

^<<v1-48-18,18>>^ "Não, meu pai", disse ele. "Este é o mais velho; coloque a mão direita sobre a cabeça dele."

[[v1-48-19]]

^<<v1-48-19,19>>^ Mas seu pai se recusou e disse: "Eu sei, meu filho; eu sei. Manassés também se tornará um grande povo, mas seu irmão mais novo será ainda maior. E seus descendentes se tornarão muitas nações".

[[v1-48-20]]

^<<v1-48-20,20>>^ Assim, Jacó abençoou os rapazes naquele dia com a seguinte bênção: "O povo de Israel usará seus nomes quando pronunciarem uma bênção. Dirão: ‘Deus os faça prosperar como Efraim e Manassés!’". Desse modo, Jacó pôs Efraim adiante de Manassés.

[[v1-48-21]]

^<<v1-48-21,21>>^ Então Jacó disse a José: "Morrerei em breve, mas Deus estará com vocês e os levará de volta a Canaã, a terra de seus antepassados.

[[v1-48-22]]

^<<v1-48-22,22>>^ Em razão de sua autoridade sobre seus irmãos, eu lhe dou uma porção a mais da terra, que tomei dos amorreus com a minha espada e o meu arco".

'''

xref:001-genesis/001-genesis-047.adoc#v1-47-0[&#60; Capítulo Anterior] | <<v1-48-0,Topo>> | xref:001-genesis/001-genesis-049.adoc#v1-49-0[Próximo Capítulo &#62;]