include::./index.adoc[]

[[v1-19-0]]
=== Gênesis, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v1-19-1]]

^<<v1-19-1,1>>^ Ao anoitecer, os dois anjos chegaram à entrada da cidade de Sodoma. Ló estava sentado ali. Ao avistá-los, levantou-se para recebê-los. Deu-lhes boas-vindas, curvou-se com o rosto no chão

[[v1-19-2]]

^<<v1-19-2,2>>^ e disse: "Meus senhores, venham à minha casa para lavar os pés e sejam meus hóspedes esta noite. Amanhã, poderão levantar-se cedo e seguir viagem". "Não", responderam eles. "Passaremos a noite aqui, na praça da cidade."

[[v1-19-3]]

^<<v1-19-3,3>>^ Mas Ló insistiu muito e, por fim, eles o acompanharam até sua casa. Ló lhes preparou um banquete completo, com pão fresco sem fermento, e eles comeram.

[[v1-19-4]]

^<<v1-19-4,4>>^ Ainda não tinham ido se deitar quando todos os homens de Sodoma, jovens e velhos, chegaram de toda parte da cidade e cercaram a casa.

[[v1-19-5]]

^<<v1-19-5,5>>^ Gritaram para Ló: "Onde estão os homens que vieram passar a noite em sua casa? Traga-os aqui fora para nós, para que tenhamos relações com eles!".

[[v1-19-6]]

^<<v1-19-6,6>>^ Ló saiu para conversar com os homens e fechou a porta atrás de si.

[[v1-19-7]]

^<<v1-19-7,7>>^ "Por favor, meus irmãos, não cometam tamanha maldade", suplicou.

[[v1-19-8]]

^<<v1-19-8,8>>^ "Escutem, tenho duas filhas virgens. Deixem-me trazê-las para fora, e vocês poderão fazer com elas o que desejarem. Mas, por favor, deixem os homens em paz, pois são meus hóspedes e estão sob minha proteção."

[[v1-19-9]]

^<<v1-19-9,9>>^ "Saia da frente!", gritaram eles. "Esse sujeito é um estrangeiro que se mudou para a cidade e, agora, age como se fosse nosso juiz! Faremos a você coisas bem piores do que a seus hóspedes!" Então partiram para cima de Ló, tentando arrombar a porta.

[[v1-19-10]]

^<<v1-19-10,10>>^ Os dois anjos, porém, estenderam a mão, puxaram Ló para dentro da casa e trancaram a porta.

[[v1-19-11]]

^<<v1-19-11,11>>^ Depois, cegaram todos os homens, jovens e velhos, que estavam à porta, de modo que eles se cansaram e desistiram de invadir a casa.

[[v1-19-12]]

^<<v1-19-12,12>>^ Os anjos perguntaram a Ló: "Você tem outros parentes na cidade? Tire-os todos daqui: genros, filhos, filhas ou qualquer outro parente,

[[v1-19-13]]

^<<v1-19-13,13>>^ pois estamos prestes a destruir toda a cidade. O clamor contra ela é tão grande que chegou ao SENHOR, e ele nos enviou para destruí-la".

[[v1-19-14]]

^<<v1-19-14,14>>^ Então Ló correu para avisar os noivos de suas filhas: "Saiam depressa da cidade! O SENHOR está prestes a destruí-la". Os rapazes, porém, pensaram que ele estava brincando.

[[v1-19-15]]

^<<v1-19-15,15>>^ No dia seguinte, ao amanhecer, os anjos insistiram: "Rápido! Tome sua mulher e suas duas filhas que estão aqui! Saia agora mesmo, ou também morrerá quando a cidade for castigada!".

[[v1-19-16]]

^<<v1-19-16,16>>^ Visto que Ló ainda hesitava, os anjos o tomaram pela mão, e também sua mulher e as duas filhas, e correram com eles para um lugar seguro, fora da cidade, pois o SENHOR foi misericordioso.

[[v1-19-17]]

^<<v1-19-17,17>>^ Quando estavam em segurança, fora da cidade, um dos anjos ordenou: "Corram e salvem-se! Não olhem para trás nem parem no vale! Fujam para as montanhas, ou serão destruídos!".

[[v1-19-18]]

^<<v1-19-18,18>>^ Mas Ló suplicou: "Não, meu senhor!

[[v1-19-19]]

^<<v1-19-19,19>>^ Os senhores foram muito bondosos comigo, salvaram minha vida e mostraram grande compaixão. Não posso, contudo, ir para as montanhas. A calamidade também me alcançaria ali, e bem depressa eu morreria.

[[v1-19-20]]

^<<v1-19-20,20>>^ Vejam, aqui perto há um vilarejo. É um lugar bem pequeno. Por favor, deixem-me ir para lá, e minha vida será salva".

[[v1-19-21]]

^<<v1-19-21,21>>^ "Está bem", disse o anjo. "Atenderei a seu pedido. Não destruirei o vilarejo.

[[v1-19-22]]

^<<v1-19-22,22>>^ Mas vá logo! Fuja para ele, pois não posso fazer nada enquanto você não chegar lá." (Isso explica por que a vila era conhecida como Zoar.)

[[v1-19-23]]

^<<v1-19-23,23>>^ Ló chegou a Zoar quando o sol aparecia no horizonte.

[[v1-19-24]]

^<<v1-19-24,24>>^ Então o SENHOR fez chover do céu fogo e enxofre sobre Sodoma e Gomorra.

[[v1-19-25]]

^<<v1-19-25,25>>^ Destruiu-as completamente, além de outras cidades e vilas da planície, e exterminou todos os habitantes e toda a vegetação.

[[v1-19-26]]

^<<v1-19-26,26>>^ A mulher de Ló, porém, olhou para trás enquanto o seguia e se transformou numa coluna de sal.

[[v1-19-27]]

^<<v1-19-27,27>>^ Naquela manhã, Abraão se levantou cedo e correu para o lugar onde tinha estado na presença do SENHOR.

[[v1-19-28]]

^<<v1-19-28,28>>^ Olhou para a planície, em direção a Sodoma e Gomorra, e viu colunas de fumaça subindo do lugar onde antes ficavam as cidades, como fumaça de uma fornalha.

[[v1-19-29]]

^<<v1-19-29,29>>^ Contudo, Deus atendeu ao pedido de Abraão e salvou Ló, tirando-o do meio da destruição que engoliu as cidades da planície.

[[v1-19-30]]

^<<v1-19-30,30>>^ Algum tempo depois, Ló deixou Zoar, pois tinha medo do povo de lá, e foi morar numa caverna nas montanhas com suas duas filhas.

[[v1-19-31]]

^<<v1-19-31,31>>^ Certo dia, a filha mais velha disse à irmã: "Nesta região não resta homem algum com quem possamos ter relações, como fazem todas as pessoas. E logo nosso pai será velho demais para ter filhos.

[[v1-19-32]]

^<<v1-19-32,32>>^ Vamos embebedá-lo com vinho e então nos deitaremos com ele. Com isso, preservaremos nossa descendência por meio de nosso pai".

[[v1-19-33]]

^<<v1-19-33,33>>^ Naquela noite, portanto, embebedaram o pai com vinho, e a filha mais velha teve relações com ele. E ele não percebeu quando ela se deitou nem quando se levantou.

[[v1-19-34]]

^<<v1-19-34,34>>^ Na manhã seguinte, a filha mais velha disse à irmã mais nova: "Ontem à noite, tive relações com nosso pai. Vamos embebedá-lo com vinho outra vez hoje à noite, e você terá relações com ele. Com isso, preservaremos nossa descendência por meio de nosso pai".

[[v1-19-35]]

^<<v1-19-35,35>>^ Naquela noite, portanto, voltaram a embebedar o pai com vinho, e a filha mais nova teve relações com ele. Mais uma vez, ele não percebeu quando ela se deitou nem quando se levantou.

[[v1-19-36]]

^<<v1-19-36,36>>^ Como resultado, as duas filhas de Ló engravidaram do próprio pai.

[[v1-19-37]]

^<<v1-19-37,37>>^ Quando a filha mais velha deu à luz um menino, chamou-o de Moabe. Ele se tornou o antepassado do povo conhecido até hoje como moabitas.

[[v1-19-38]]

^<<v1-19-38,38>>^ Quando a filha mais nova deu à luz um menino, chamou-o de Ben-Ami. Ele se tornou o antepassado do povo conhecido até hoje como amonitas.

'''

xref:001-genesis/001-genesis-018.adoc#v1-18-0[&#60; Capítulo Anterior] | <<v1-19-0,Topo>> | xref:001-genesis/001-genesis-020.adoc#v1-20-0[Próximo Capítulo &#62;]