include::./index.adoc[]

[[v1-28-0]]
=== Gênesis, 28
// nvt ?, NVT - Nova Versão Transformadora

[[v1-28-1]]

^<<v1-28-1,1>>^ Então Isaque mandou chamar Jacó, o abençoou e disse: "Não se case com uma mulher cananita.

[[v1-28-2]]

^<<v1-28-2,2>>^ Em vez disso, vá de imediato a Padã-Arã, à casa de seu avô Betuel, e case-se com uma das filhas de seu tio Labão.

[[v1-28-3]]

^<<v1-28-3,3>>^ Que o Deus Todo-poderoso o abençoe e lhe dê muitos filhos, e que eles se multipliquem e venham a ser muitas nações.

[[v1-28-4]]

^<<v1-28-4,4>>^ Que Deus dê a você e a seus descendentes as bênçãos que ele prometeu a Abraão. Que você venha a possuir esta terra na qual vive agora como estrangeiro, pois Deus entregou esta terra a Abraão".

[[v1-28-5]]

^<<v1-28-5,5>>^ Assim, Isaque se despediu de Jacó, que foi a Padã-Arã morar com seu tio Labão, irmão de Rebeca, filho de Betuel, o arameu.

[[v1-28-6]]

^<<v1-28-6,6>>^ Esaú soube que seu pai, Isaque, havia abençoado Jacó e o enviado a Padã-Arã para encontrar uma esposa e que, ao abençoá-lo, tinha advertido a seu irmão: "Não se case com uma mulher cananita".

[[v1-28-7]]

^<<v1-28-7,7>>^ Também soube que Jacó havia obedecido aos pais e ido a Padã-Arã.

[[v1-28-8]]

^<<v1-28-8,8>>^ Quando ficou evidente que seu pai não aprovava as mulheres cananitas,

[[v1-28-9]]

^<<v1-28-9,9>>^ Esaú foi visitar a família de seu tio Ismael e, além das duas mulheres cananitas com as quais havia se casado, tomou para si uma das filhas de Ismael. O nome de sua nova mulher era Maalate, irmã de Nebaiote e filha de Ismael, filho de Abraão.

[[v1-28-10]]

^<<v1-28-10,10>>^ Nesse meio-tempo, Jacó partiu de Berseba e rumou para Harã.

[[v1-28-11]]

^<<v1-28-11,11>>^ Quando o sol se pôs, chegou a um bom local para acampar e ali passou a noite. Encontrou uma pedra para descansar a cabeça e se deitou para dormir.

[[v1-28-12]]

^<<v1-28-12,12>>^ Enquanto dormia, sonhou com uma escada que ia da terra ao céu e viu os anjos de Deus, que subiam e desciam pela escada.

[[v1-28-13]]

^<<v1-28-13,13>>^ No topo da escada estava o SENHOR, que lhe disse: "Eu sou o SENHOR, o Deus de seu avô, Abraão, e o Deus de seu pai, Isaque. A terra na qual você está deitado lhe pertence. Eu a darei a você e a seus descendentes.

[[v1-28-14]]

^<<v1-28-14,14>>^ Seus descendentes serão tão numerosos quanto o pó da terra! Eles se espalharão por todas as direções: leste e oeste, norte e sul. E todas as famílias da terra serão abençoadas por seu intermédio e de sua descendência.

[[v1-28-15]]

^<<v1-28-15,15>>^ Além disso, estarei com você e o protegerei aonde quer que vá. Um dia, trarei você de volta a esta terra. Não o deixarei enquanto não tiver terminado de lhe dar tudo que prometi".

[[v1-28-16]]

^<<v1-28-16,16>>^ Então Jacó acordou e disse: "Certamente o SENHOR está neste lugar, e eu não havia percebido!".

[[v1-28-17]]

^<<v1-28-17,17>>^ Contudo, também teve medo e disse: "Como é temível este lugar! Não é outro, senão a casa de Deus; é a porta para os céus!".

[[v1-28-18]]

^<<v1-28-18,18>>^ Na manhã seguinte, Jacó se levantou bem cedo. Pegou a pedra na qual havia descansado a cabeça, colocou-a em pé, como coluna memorial, e derramou azeite de oliva sobre ela.

[[v1-28-19]]

^<<v1-28-19,19>>^ Chamou o lugar de Betel, embora anteriormente se chamasse Luz.

[[v1-28-20]]

^<<v1-28-20,20>>^ Então Jacó fez o seguinte voto: "Se, de fato, Deus for comigo e me proteger nesta jornada, se ele me providenciar alimento e roupa,

[[v1-28-21]]

^<<v1-28-21,21>>^ e se eu voltar são e salvo à casa de meu pai, então o SENHOR certamente será o meu Deus.

[[v1-28-22]]

^<<v1-28-22,22>>^ E esta coluna memorial que eu levantei será um lugar de adoração a Deus, e eu entregarei a Deus a décima parte de tudo que ele me der".

'''

xref:001-genesis/001-genesis-027.adoc#v1-27-0[&#60; Capítulo Anterior] | <<v1-28-0,Topo>> | xref:001-genesis/001-genesis-029.adoc#v1-29-0[Próximo Capítulo &#62;]