include::./index.adoc[]

[[v1-20-0]]
=== Gênesis, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v1-20-1]]

^<<v1-20-1,1>>^ Abraão se mudou para o Neguebe, ao sul. Permaneceu por algum tempo entre Cades e Sur e depois seguiu até Gerar. Enquanto morava ali como estrangeiro,

[[v1-20-2]]

^<<v1-20-2,2>>^ Abraão apresentava Sara, sua mulher, dizendo: "Ela é minha irmã". Por isso, o rei Abimeleque, de Gerar, mandou buscar Sara para seu palácio.

[[v1-20-3]]

^<<v1-20-3,3>>^ Naquela noite, Deus apareceu a Abimeleque num sonho e lhe disse: "Você vai morrer! A mulher que tomou já é casada!".

[[v1-20-4]]

^<<v1-20-4,4>>^ Abimeleque, porém, ainda não havia dormido com ela. Assim, disse: "Senhor, castigarás uma nação inocente?

[[v1-20-5]]

^<<v1-20-5,5>>^ Não foi Abraão quem me disse: ‘Ela é minha irmã’? E ela própria afirmou: ‘Sim, ele é meu irmão’? Agi com total inocência. Minhas mãos estão limpas!".

[[v1-20-6]]

^<<v1-20-6,6>>^ No sonho, Deus respondeu: "Sim, eu sei que você é inocente. Por isso o impedi de pecar e não deixei que a tocasse.

[[v1-20-7]]

^<<v1-20-7,7>>^ Agora, devolva a mulher ao marido dela, e ele orará por você, pois é profeta. Então você viverá. Mas, se não a devolver, esteja certo de que você e todo o seu povo morrerão".

[[v1-20-8]]

^<<v1-20-8,8>>^ Na manhã seguinte, Abimeleque se levantou cedo e, sem demora, reuniu todos os seus servos. Quando contou o que havia acontecido, seus homens se encheram de medo.

[[v1-20-9]]

^<<v1-20-9,9>>^ Então Abimeleque mandou chamar Abraão. "O que você fez conosco?", perguntou. "Que crime cometi para merecer este tratamento que nos torna, a mim e ao meu reino, culpados deste grande pecado? O que você me fez não se faz a ninguém!

[[v1-20-10]]

^<<v1-20-10,10>>^ O que deu em você para agir desse jeito?"

[[v1-20-11]]

^<<v1-20-11,11>>^ Abraão respondeu: "Pensei comigo: ‘Este é um lugar onde ninguém teme a Deus, e vão me matar para ficarem com minha mulher’.

[[v1-20-12]]

^<<v1-20-12,12>>^ Além do mais, ela é, de fato, minha irmã por parte de pai, mas não de mãe, e eu me casei com ela.

[[v1-20-13]]

^<<v1-20-13,13>>^ Quando Deus me chamou para deixar a casa de meu pai e viajar de um lugar para outro, eu disse a ela: ‘Faça-me este favor: por onde formos, diga que eu sou seu irmão’".

[[v1-20-14]]

^<<v1-20-14,14>>^ Então Abimeleque pegou ovelhas e bois, servos e servas, e os deu de presente a Abraão. Também lhe devolveu Sara, sua mulher.

[[v1-20-15]]

^<<v1-20-15,15>>^ Abimeleque disse: "Veja, minha terra está à sua disposição. More onde lhe parecer melhor".

[[v1-20-16]]

^<<v1-20-16,16>>^ E disse a Sara: "Estou dando a seu irmão mil peças de prata diante de todas estas testemunhas para reparar qualquer dano que eu lhe tenha causado. Assim, todos saberão que você é inocente".

[[v1-20-17]]

^<<v1-20-17,17>>^ Então Abraão orou a Deus, e Deus curou Abimeleque, sua mulher e suas servas, de modo que pudessem ter filhos,

[[v1-20-18]]

^<<v1-20-18,18>>^ pois o SENHOR havia tornado estéreis todas as mulheres do harém de Abimeleque por causa do que tinha acontecido com Sara, mulher de Abraão.

'''

xref:001-genesis/001-genesis-019.adoc#v1-19-0[&#60; Capítulo Anterior] | <<v1-20-0,Topo>> | xref:001-genesis/001-genesis-021.adoc#v1-21-0[Próximo Capítulo &#62;]