include::./index.adoc[]

[[v1-24-0]]
=== Gênesis, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v1-24-1]]

^<<v1-24-1,1>>^ Abraão estava bem velho, e o SENHOR o havia abençoado em tudo.

[[v1-24-2]]

^<<v1-24-2,2>>^ Certo dia, Abraão disse a seu servo mais antigo, o homem encarregado de sua casa: "Faça um juramento colocando a mão debaixo da minha coxa.

[[v1-24-3]]

^<<v1-24-3,3>>^ Jure pelo SENHOR, o Deus dos céus e da terra, que não deixará meu filho se casar com uma das mulheres cananitas que aqui vivem,

[[v1-24-4]]

^<<v1-24-4,4>>^ mas irá à minha terra natal, aos meus parentes, procurar uma mulher para meu filho Isaque".

[[v1-24-5]]

^<<v1-24-5,5>>^ O servo perguntou: "E se eu não encontrar uma moça disposta a viajar para um lugar tão distante de sua terra? Devo levar Isaque para morar entre seus parentes na terra de onde o senhor veio?".

[[v1-24-6]]

^<<v1-24-6,6>>^ "Não!", respondeu Abraão. "Cuidado! Não leve meu filho para lá de jeito nenhum.

[[v1-24-7]]

^<<v1-24-7,7>>^ O SENHOR, o Deus dos céus, que me tirou da casa de meu pai e de minha terra natal, prometeu solenemente dar esta terra a meus descendentes. Ele enviará um anjo à sua frente e providenciará para que você encontre ali uma mulher para meu filho.

[[v1-24-8]]

^<<v1-24-8,8>>^ Se ela não estiver disposta a acompanhá-lo de volta, você estará livre do seu juramento. Mas não leve meu filho para lá, de maneira nenhuma."

[[v1-24-9]]

^<<v1-24-9,9>>^ Então o servo colocou a mão debaixo da coxa de Abraão, seu senhor, e jurou seguir suas instruções.

[[v1-24-10]]

^<<v1-24-10,10>>^ Em seguida, pegou dez camelos de Abraão, carregou-os com presentes valiosos de todo tipo da parte de seu senhor e viajou para a terra distante de Arã-Naaraim. Chegando lá, dirigiu-se à cidade onde Naor, irmão de Abraão, havia se estabelecido.

[[v1-24-11]]

^<<v1-24-11,11>>^ Ao entardecer, quando as mulheres saíam para tirar água, ele fez os camelos se ajoelharem perto de um poço nos arredores da cidade.

[[v1-24-12]]

^<<v1-24-12,12>>^ Então o servo orou: "Ó SENHOR, Deus do meu senhor Abraão, por favor, dá-me sucesso hoje e sê bondoso com o meu senhor Abraão.

[[v1-24-13]]

^<<v1-24-13,13>>^ Como vês, estou aqui junto desta fonte, e as moças da cidade estão vindo tirar água.

[[v1-24-14]]

^<<v1-24-14,14>>^ Esta é minha súplica. Pedirei a uma delas: ‘Por favor, dê-me um pouco de água do seu cântaro para eu beber’. Se ela disser: ‘Sim, beba. Também darei água a seus camelos’, que seja ela a moça que escolheste para ser mulher do teu servo Isaque. Desse modo, saberei que foste bondoso com o meu senhor".

[[v1-24-15]]

^<<v1-24-15,15>>^ Antes de terminar a oração, o servo viu aproximar-se uma moça chamada Rebeca, que trazia um cântaro no ombro. Ela era filha de Betuel, filho do irmão de Abraão, Naor, e de sua mulher, Milca.

[[v1-24-16]]

^<<v1-24-16,16>>^ Rebeca era muito bonita, tinha idade para casar e era virgem. Ela desceu à fonte, encheu o cântaro e voltou.

[[v1-24-17]]

^<<v1-24-17,17>>^ O servo de Abraão correu até ela e lhe pediu: "Por favor, dê-me um pouco de água do seu cântaro para eu beber".

[[v1-24-18]]

^<<v1-24-18,18>>^ "Sim, meu senhor, beba", respondeu ela e, prontamente, baixou o cântaro do ombro e lhe deu de beber.

[[v1-24-19]]

^<<v1-24-19,19>>^ Depois que lhe deu de beber, disse: "Tirarei água para seus camelos também, até que estejam satisfeitos".

[[v1-24-20]]

^<<v1-24-20,20>>^ Esvaziou depressa o cântaro no bebedouro e correu de volta ao poço a fim de tirar água para todos os camelos.

[[v1-24-21]]

^<<v1-24-21,21>>^ O homem a observou em silêncio, pensando se o SENHOR lhe tinha dado sucesso em sua missão.

[[v1-24-22]]

^<<v1-24-22,22>>^ Por fim, quando os camelos terminaram de beber, o servo deu à moça uma argola de ouro para o nariz e duas pulseiras grandes de ouro para os braços.

[[v1-24-23]]

^<<v1-24-23,23>>^ "De quem você é filha?", perguntou ele. "Diga-me, por favor, se seu pai tem lugar para nos hospedar esta noite."

[[v1-24-24]]

^<<v1-24-24,24>>^ "Sou filha de Betuel, e meus avós são Naor e Milca", respondeu ela.

[[v1-24-25]]

^<<v1-24-25,25>>^ "Temos bastante palha e forragem para os camelos e espaço para hóspedes."

[[v1-24-26]]

^<<v1-24-26,26>>^ O homem se prostrou e adorou o SENHOR.

[[v1-24-27]]

^<<v1-24-27,27>>^ "Louvado seja o SENHOR, Deus do meu senhor Abraão!", disse ele. "O SENHOR demonstrou bondade e fidelidade ao meu senhor, pois me conduziu até seus parentes."

[[v1-24-28]]

^<<v1-24-28,28>>^ A moça correu para casa e contou à família tudo que havia acontecido.

[[v1-24-29]]

^<<v1-24-29,29>>^ Rebeca tinha um irmão chamado Labão, que foi prontamente à fonte para conhecer o homem.

[[v1-24-30]]

^<<v1-24-30,30>>^ Ele havia visto a argola para o nariz e as pulseiras nos braços da irmã, e tinha ouvido Rebeca contar o que o homem dissera. Assim, apressou-se até a fonte, onde o homem ainda estava parado perto dos camelos.

[[v1-24-31]]

^<<v1-24-31,31>>^ Labão lhe disse: "Venha e fique conosco, abençoado do SENHOR! Por que ficar aí fora? Já mandei arrumar acomodações para você e seus homens e lugar para os camelos".

[[v1-24-32]]

^<<v1-24-32,32>>^ Então o homem foi com ele para casa. Labão mandou descarregar os camelos, dar palha para os animais se deitarem e forragem para comerem, e água para o homem e seus ajudantes lavarem os pés.

[[v1-24-33]]

^<<v1-24-33,33>>^ Quando a refeição foi servida, porém, o servo de Abraão disse: "Não comerei enquanto não explicar o motivo da minha vinda". "Está bem", disse Labão. "Fale."

[[v1-24-34]]

^<<v1-24-34,34>>^ "Sou servo de Abraão", explicou ele.

[[v1-24-35]]

^<<v1-24-35,35>>^ "O SENHOR abençoou grandemente o meu senhor, e ele se tornou um homem rico. O SENHOR lhe deu rebanhos de ovelhas e bois, uma fortuna em prata e ouro, e muitos servos e servas, camelos e jumentos.

[[v1-24-36]]

^<<v1-24-36,36>>^ "Quando Sara, mulher do meu senhor, era muito idosa, deu à luz o filho dele. Meu senhor deu tudo que possui a esse filho

[[v1-24-37]]

^<<v1-24-37,37>>^ e me fez jurar, dizendo: ‘Não permita que meu filho se case com uma das mulheres cananitas que aqui vivem.

[[v1-24-38]]

^<<v1-24-38,38>>^ Vá à casa de meu pai, aos meus parentes, procurar uma mulher para meu filho’.

[[v1-24-39]]

^<<v1-24-39,39>>^ "Mas eu perguntei ao meu senhor: ‘E se eu não encontrar uma moça disposta a voltar comigo?’.

[[v1-24-40]]

^<<v1-24-40,40>>^ Ele respondeu: ‘O SENHOR, em cuja presença tenho vivido, enviará um anjo com você e lhe dará sucesso em sua missão. Encontre uma mulher para meu filho entre os meus parentes, da família de meu pai.

[[v1-24-41]]

^<<v1-24-41,41>>^ Então você terá cumprido sua obrigação. Se, porém, você for aos meus parentes e eles não deixarem a moça acompanhá-lo, estará livre do juramento’.

[[v1-24-42]]

^<<v1-24-42,42>>^ "Hoje, quando cheguei à fonte, fiz a seguinte oração: ‘Ó SENHOR, Deus do meu senhor Abraão, por favor, dá-me sucesso em minha missão.

[[v1-24-43]]

^<<v1-24-43,43>>^ Como vês, estou aqui junto desta fonte. Esta é minha súplica. Quando uma jovem vier tirar água, eu lhe direi: ‘Por favor, dê-me um pouco de água do seu cântaro’.

[[v1-24-44]]

^<<v1-24-44,44>>^ Se ela disser: ‘Sim, beba. Também darei água a seus camelos’, que seja ela a moça que escolheste para ser mulher do filho do meu senhor’.

[[v1-24-45]]

^<<v1-24-45,45>>^ "Antes de terminar de orar em meu coração, vi Rebeca vindo com o cântaro no ombro. Ela desceu à fonte e tirou água. Eu lhe disse: ‘Por favor, dê-me um pouco de água do seu cântaro para eu beber’.

[[v1-24-46]]

^<<v1-24-46,46>>^ Prontamente, ela baixou o cântaro do ombro e disse: ‘Sim, beba. Também darei água aos seus camelos’. Eu bebi, e ela deu água aos camelos.

[[v1-24-47]]

^<<v1-24-47,47>>^ "Em seguida, perguntei-lhe: ‘De quem você é filha?’. Ela respondeu: ‘Sou filha de Betuel, e meus avós são Naor e Milca’. Então coloquei a argola em seu nariz e as pulseiras em seus braços.

[[v1-24-48]]

^<<v1-24-48,48>>^ "Depois, prostrei-me e adorei o SENHOR. Louvei o SENHOR, Deus do meu senhor Abraão, pois ele havia me conduzido até a sobrinha-neta do meu senhor, para que ela seja mulher do filho do meu senhor.

[[v1-24-49]]

^<<v1-24-49,49>>^ Agora, digam-me se mostrarão bondade e fidelidade ao meu senhor. Por favor, respondam-me ‘sim’ ou ‘não’, para que eu saiba o que fazer em seguida."

[[v1-24-50]]

^<<v1-24-50,50>>^ Labão e Betuel responderam: "É evidente que o SENHOR o trouxe até aqui. Sendo assim, não há nada que possamos dizer.

[[v1-24-51]]

^<<v1-24-51,51>>^ Aqui está Rebeca; tome-a e leve-a com você. Que ela seja mulher do filho do seu senhor, como disse o SENHOR".

[[v1-24-52]]

^<<v1-24-52,52>>^ Quando o servo de Abraão ouviu a resposta, prostrou-se no chão e adorou o SENHOR.

[[v1-24-53]]

^<<v1-24-53,53>>^ Em seguida, entregou a Rebeca joias de prata e ouro e vestidos. Também deu presentes valiosos ao irmão e à mãe de Rebeca.

[[v1-24-54]]

^<<v1-24-54,54>>^ Então o servo e os homens que o acompanhavam comeram e passaram a noite ali. Logo cedo na manhã seguinte, o servo de Abraão disse: "Enviem-me de volta ao meu senhor".

[[v1-24-55]]

^<<v1-24-55,55>>^ Mas o irmão e a mãe de Rebeca disseram: "Queremos que Rebeca fique conosco pelo menos dez dias; depois, ela poderá partir".

[[v1-24-56]]

^<<v1-24-56,56>>^ O servo, porém, disse: "Não me detenham. O SENHOR me deu sucesso em minha missão; agora, enviem-me de volta ao meu senhor".

[[v1-24-57]]

^<<v1-24-57,57>>^ "Pois bem", disseram eles. "Chamaremos Rebeca e pediremos a opinião dela."

[[v1-24-58]]

^<<v1-24-58,58>>^ Chamaram Rebeca e lhe perguntaram: "Você está disposta a ir com este homem?". E ela respondeu: "Sim, estou".

[[v1-24-59]]

^<<v1-24-59,59>>^ Com isso, eles se despediram de Rebeca e a enviaram com o servo de Abraão e seus homens. A serva que havia amamentado Rebeca a acompanhou.

[[v1-24-60]]

^<<v1-24-60,60>>^ Na hora da partida, abençoaram Rebeca, dizendo: "Nossa irmã, que você se torne mãe de muitos milhares! Que seus descendentes conquistem as cidades de seus inimigos!".

[[v1-24-61]]

^<<v1-24-61,61>>^ Então Rebeca e suas servas montaram nos camelos e seguiram o homem. Assim, o servo de Abraão partiu levando Rebeca.

[[v1-24-62]]

^<<v1-24-62,62>>^ Nesse meio-tempo, Isaque, que morava no Neguebe, havia regressado de Beer-Laai-Roi.

[[v1-24-63]]

^<<v1-24-63,63>>^ Ao entardecer, enquanto caminhava pelo campo e meditava, levantou os olhos e viu que camelos se aproximavam.

[[v1-24-64]]

^<<v1-24-64,64>>^ Quando Rebeca levantou os olhos e viu Isaque, desceu do camelo no mesmo instante

[[v1-24-65]]

^<<v1-24-65,65>>^ e perguntou ao servo: "Quem é aquele homem que vem pelo campo ao nosso encontro?". Quando ele respondeu: "É meu senhor", Rebeca cobriu o rosto com o véu.

[[v1-24-66]]

^<<v1-24-66,66>>^ Depois, o servo contou a Isaque tudo que havia feito.

[[v1-24-67]]

^<<v1-24-67,67>>^ Isaque a levou para a tenda de Sara, sua mãe, e Rebeca se tornou sua mulher. Ele a amava profundamente e nela encontrou consolação depois que sua mãe morreu.

'''

xref:001-genesis/001-genesis-023.adoc#v1-23-0[&#60; Capítulo Anterior] | <<v1-24-0,Topo>> | xref:001-genesis/001-genesis-025.adoc#v1-25-0[Próximo Capítulo &#62;]