include::./index.adoc[]

[[v1-43-0]]
=== Gênesis, 43
// nvt ?, NVT - Nova Versão Transformadora

[[v1-43-1]]

^<<v1-43-1,1>>^ A fome se agravou na terra de Canaã.

[[v1-43-2]]

^<<v1-43-2,2>>^ Quando os cereais que eles haviam trazido do Egito estavam para acabar, Jacó disse a seus filhos: "Voltem e comprem um pouco mais de mantimento para nós".

[[v1-43-3]]

^<<v1-43-3,3>>^ Judá, porém, respondeu: "O homem estava falando sério quando nos advertiu: ‘Vocês não me verão novamente se não trouxerem seu irmão’.

[[v1-43-4]]

^<<v1-43-4,4>>^ Se o senhor enviar Benjamim conosco, desceremos e compraremos mais mantimento,

[[v1-43-5]]

^<<v1-43-5,5>>^ mas, se não deixar Benjamim ir, nós também não iremos. Lembre-se de que o homem disse: ‘Vocês não me verão novamente se não trouxerem seu irmão’".

[[v1-43-6]]

^<<v1-43-6,6>>^ "Por que vocês foram tão cruéis comigo?", lamentou-se Jacó. "Por que disseram ao homem que tinham outro irmão?"

[[v1-43-7]]

^<<v1-43-7,7>>^ "Ele fez uma porção de perguntas sobre nossa família", responderam. "Quis saber: ‘Seu pai ainda está vivo? Vocês têm outro irmão?’. Nós apenas respondemos às perguntas dele. Como poderíamos imaginar que ele diria: ‘Tragam seu irmão’?"

[[v1-43-8]]

^<<v1-43-8,8>>^ Judá disse a seu pai: "Deixe o rapaz ir comigo e partiremos. Do contrário, todos nós morreremos de fome, e não apenas nós, mas também nossos pequeninos.

[[v1-43-9]]

^<<v1-43-9,9>>^ Garanto pessoalmente a segurança dele. O senhor pode me responsabilizar se eu não o trouxer de volta. Carregarei a culpa para sempre.

[[v1-43-10]]

^<<v1-43-10,10>>^ Se não tivéssemos perdido todo esse tempo, poderíamos ter ido e voltado duas vezes".

[[v1-43-11]]

^<<v1-43-11,11>>^ Por fim, Jacó, seu pai, lhes disse: "Se não há outro jeito, pelo menos façam o seguinte. Coloquem na bagagem os melhores produtos desta terra: bálsamo, mel, especiarias e mirra, pistache e amêndoas, e levem de presente para o homem.

[[v1-43-12]]

^<<v1-43-12,12>>^ Levem também o dobro do dinheiro que foi devolvido, pois alguém deve tê-lo colocado nos sacos por engano.

[[v1-43-13]]

^<<v1-43-13,13>>^ Depois, peguem seu irmão e voltem àquele homem.

[[v1-43-14]]

^<<v1-43-14,14>>^ Que o Deus Todo-poderoso lhes conceda misericórdia quando estiverem diante daquele homem, para que ele liberte Simeão e deixe Benjamim voltar. Mas, se devo perder meus filhos, que assim seja".

[[v1-43-15]]

^<<v1-43-15,15>>^ Então os homens pegaram os presentes de Jacó e o dobro do dinheiro e partiram com Benjamim. Por fim, chegaram ao Egito e se apresentaram a José.

[[v1-43-16]]

^<<v1-43-16,16>>^ Quando José viu Benjamim com eles, disse ao administrador de sua casa: "Estes homens almoçarão comigo ao meio-dia. Leve-os ao palácio, mate um animal e prepare um grande banquete".

[[v1-43-17]]

^<<v1-43-17,17>>^ O homem fez conforme José ordenou e os levou ao palácio de José.

[[v1-43-18]]

^<<v1-43-18,18>>^ Quando os irmãos viram que estavam sendo levados à casa de José, ficaram apavorados. "É por causa do dinheiro que alguém colocou de volta nos sacos da outra vez que estivemos aqui", disseram uns aos outros. "Ele planeja nos acusar de roubo e, depois, nos prender, nos tornar escravos e tomar nossos jumentos."

[[v1-43-19]]

^<<v1-43-19,19>>^ À entrada do palácio, os irmãos se dirigiram ao administrador de José e lhe disseram:

[[v1-43-20]]

^<<v1-43-20,20>>^ "Ouça, senhor. Viemos ao Egito anteriormente para comprar mantimentos.

[[v1-43-21]]

^<<v1-43-21,21>>^ No caminho de volta para casa, paramos para pernoitar e abrimos os sacos. Descobrimos que o dinheiro de cada um, a quantia exata que havíamos pago, estava na boca do saco. Trouxemos o dinheiro de volta. Aqui está.

[[v1-43-22]]

^<<v1-43-22,22>>^ Também trouxemos mais dinheiro para comprar mantimentos. Não fazemos ideia de quem colocou o dinheiro nos sacos".

[[v1-43-23]]

^<<v1-43-23,23>>^ "Fiquem tranquilos", disse o administrador. "Não tenham medo. Seu Deus, o Deus de seu pai, deve ter colocado esse tesouro nos sacos. Tenho certeza de que recebi seu pagamento." Depois disso, soltou Simeão e o levou até onde eles estavam.

[[v1-43-24]]

^<<v1-43-24,24>>^ Em seguida, o administrador os conduziu para dentro do palácio de José. Deu-lhes água para lavar os pés e providenciou ração para seus jumentos.

[[v1-43-25]]

^<<v1-43-25,25>>^ Quando foram avisados que almoçariam lá, os irmãos prepararam os presentes para a chegada de José ao meio-dia.

[[v1-43-26]]

^<<v1-43-26,26>>^ Assim que José chegou em casa, entregaram-lhe os presentes que haviam trazido e curvaram-se até o chão diante dele.

[[v1-43-27]]

^<<v1-43-27,27>>^ Depois de cumprimentá-los, José quis saber: "Como está seu pai, o senhor idoso do qual me falaram? Ainda está vivo?".

[[v1-43-28]]

^<<v1-43-28,28>>^ "Sim", responderam eles. "Nosso pai, seu servo, ainda está vivo e vai bem." E curvaram-se mais uma vez.

[[v1-43-29]]

^<<v1-43-29,29>>^ Então José olhou para seu irmão Benjamim, o filho de sua mãe, e perguntou: "Este é o irmão mais novo de que vocês me falaram?". E disse a Benjamim: "Deus seja bondoso com você, meu filho".

[[v1-43-30]]

^<<v1-43-30,30>>^ Muito emocionado por causa do irmão, José saiu depressa da sala. Foi para o quarto, onde chorou.

[[v1-43-31]]

^<<v1-43-31,31>>^ Depois de lavar o rosto, voltou mais controlado e ordenou: "Tragam a comida!".

[[v1-43-32]]

^<<v1-43-32,32>>^ José foi servido em sua própria mesa, e seus irmãos, em uma mesa separada. Os egípcios que comiam com José, por sua vez, foram servidos em outra mesa, pois os egípcios desprezavam os hebreus e se recusavam a comer com eles.

[[v1-43-33]]

^<<v1-43-33,33>>^ José disse a cada um dos irmãos onde deviam sentar-se e, para espanto deles, colocou-os ao redor da mesa em ordem de idade, do mais velho para o mais novo.

[[v1-43-34]]

^<<v1-43-34,34>>^ Mandou encher os pratos deles com comida de sua própria mesa, e deram a Benjamim uma porção cinco vezes maior que a dos outros. E eles comeram e beberam à vontade com José.

'''

xref:001-genesis/001-genesis-042.adoc#v1-42-0[&#60; Capítulo Anterior] | <<v1-43-0,Topo>> | xref:001-genesis/001-genesis-044.adoc#v1-44-0[Próximo Capítulo &#62;]