include::./index.adoc[]

[[v1-31-0]]
=== Gênesis, 31
// nvt ?, NVT - Nova Versão Transformadora

[[v1-31-1]]

^<<v1-31-1,1>>^ Logo, porém, Jacó percebeu que os filhos de Labão estavam reclamando dele: "Jacó roubou tudo que era de nosso pai! À custa de nosso pai, adquiriu toda a sua riqueza!".

[[v1-31-2]]

^<<v1-31-2,2>>^ Jacó também começou a notar uma mudança na atitude de Labão para com ele.

[[v1-31-3]]

^<<v1-31-3,3>>^ Então o SENHOR disse a Jacó: "Volte para a terra de seu pai e de seu avô, a terra de seus parentes, e eu estarei com você".

[[v1-31-4]]

^<<v1-31-4,4>>^ Jacó mandou chamar Raquel e Lia ao campo onde ele cuidava de seus rebanhos

[[v1-31-5]]

^<<v1-31-5,5>>^ e disse a elas: "Notei que seu pai mudou de atitude em relação a mim. O Deus de meu pai, porém, tem estado comigo.

[[v1-31-6]]

^<<v1-31-6,6>>^ Vocês sabem como tenho trabalhado arduamente a serviço de seu pai.

[[v1-31-7]]

^<<v1-31-7,7>>^ Contudo, ele me enganou e mudou meu salário dez vezes. Mas Deus não permitiu que ele me prejudicasse.

[[v1-31-8]]

^<<v1-31-8,8>>^ Se ele dizia: ‘Os salpicados serão o seu salário’, o rebanho começava a dar crias salpicadas. E, quando mudava de ideia e dizia: ‘Os listrados serão o seu salário’, então o rebanho inteiro dava crias listradas.

[[v1-31-9]]

^<<v1-31-9,9>>^ Desse modo, Deus tirou os animais de seu pai e os deu a mim.

[[v1-31-10]]

^<<v1-31-10,10>>^ "Certa vez, na época do acasalamento, tive um sonho e vi que os bodes que se acasalavam com as cabras eram listrados, salpicados e malhados.

[[v1-31-11]]

^<<v1-31-11,11>>^ Então, em meu sonho, o anjo de Deus me disse: ‘Jacó!’. E eu respondi: ‘Aqui estou!’.

[[v1-31-12]]

^<<v1-31-12,12>>^ "E o anjo disse: ‘Levante os olhos e você verá que apenas os machos listrados, salpicados e malhados estão se acasalando com as fêmeas de seu rebanho, pois vejo como Labão tem tratado você.

[[v1-31-13]]

^<<v1-31-13,13>>^ Eu sou o Deus que lhe apareceu em Betel, o lugar onde você ungiu a coluna de pedra e fez seu voto a mim. Agora, apronte-se, saia desta terra e volte à sua terra natal’".

[[v1-31-14]]

^<<v1-31-14,14>>^ Raquel e Lia responderam: "Da nossa parte, tudo bem! Afinal, não herdaremos coisa alguma da riqueza de nosso pai.

[[v1-31-15]]

^<<v1-31-15,15>>^ Ele reduziu nossos direitos aos mesmos que têm as mulheres estrangeiras. Depois que nos vendeu, desperdiçou todo o dinheiro que você pagou por nós.

[[v1-31-16]]

^<<v1-31-16,16>>^ Toda a riqueza que Deus tirou de nosso pai e deu a você é, por direito, nossa e de nossos filhos. Por isso, faça o que Deus ordenou".

[[v1-31-17]]

^<<v1-31-17,17>>^ Então Jacó montou suas mulheres e seus filhos em camelos

[[v1-31-18]]

^<<v1-31-18,18>>^ e conduziu adiante todos os seus rebanhos. Juntou todos os bens que havia adquirido em Padã-Arã e partiu para a terra de Canaã, onde vivia Isaque, seu pai.

[[v1-31-19]]

^<<v1-31-19,19>>^ Quando partiram, Labão estava num lugar afastado, tosquiando suas ovelhas. Raquel roubou os ídolos da casa que pertenciam a seu pai e os levou consigo.

[[v1-31-20]]

^<<v1-31-20,20>>^ Assim, Jacó enganou Labão, o arameu, partindo sem avisá-lo de que iam embora.

[[v1-31-21]]

^<<v1-31-21,21>>^ Jacó levou todos os seus bens e atravessou o rio Eufrates, rumo à região montanhosa de Gileade.

[[v1-31-22]]

^<<v1-31-22,22>>^ Três dias depois, Labão foi informado de que Jacó havia fugido.

[[v1-31-23]]

^<<v1-31-23,23>>^ Reuniu um grupo de parentes e saiu em perseguição a Jacó. Sete dias depois o alcançou, na região montanhosa de Gileade.

[[v1-31-24]]

^<<v1-31-24,24>>^ Na noite anterior, porém, Deus havia aparecido em sonho a Labão, o arameu, e dito a ele: "Estou avisando: deixe Jacó em paz!".

[[v1-31-25]]

^<<v1-31-25,25>>^ Labão o alcançou enquanto Jacó estava acampado na região montanhosa de Gileade e armou seu acampamento ali perto.

[[v1-31-26]]

^<<v1-31-26,26>>^ "O que você fez?", perguntou Labão. "Como ousou me enganar e levar minhas filhas embora, como se fossem prisioneiras de guerra?

[[v1-31-27]]

^<<v1-31-27,27>>^ Por que fugiu em segredo? Por que me enganou? E por que não avisou que desejava partir? Eu lhe teria dado uma festa de despedida, com canções e música, ao som de tamborins e harpas.

[[v1-31-28]]

^<<v1-31-28,28>>^ Por que não me deixou beijar minhas filhas e meus netos e me despedir deles? Você agiu de forma extremamente tola!

[[v1-31-29]]

^<<v1-31-29,29>>^ Eu poderia destruí-lo, mas o Deus de seu pai me apareceu ontem à noite e me advertiu: ‘Deixe Jacó em paz!’.

[[v1-31-30]]

^<<v1-31-30,30>>^ Entendo sua vontade de partir e seu desejo de voltar à casa de seu pai. Mas por que roubou meus deuses?"

[[v1-31-31]]

^<<v1-31-31,31>>^ Jacó respondeu: "Fugi porque tive medo. Pensei que o senhor tiraria suas filhas de mim à força.

[[v1-31-32]]

^<<v1-31-32,32>>^ Quanto a seus deuses, veja se consegue encontrá-los, e quem os tiver roubado deve morrer! Se encontrar qualquer outra coisa que lhe pertença, identifique-a diante de todos estes nossos parentes, e eu a devolverei". Jacó, porém, não sabia que Raquel havia roubado os ídolos da casa.

[[v1-31-33]]

^<<v1-31-33,33>>^ Labão foi procurar primeiro na tenda de Jacó e, depois, nas tendas de Lia e das duas servas, mas nada encontrou. Por fim, entrou na tenda de Raquel.

[[v1-31-34]]

^<<v1-31-34,34>>^ Acontece que Raquel havia pego os ídolos da casa e os escondido na sela do seu camelo, e estava sentada em cima deles. Quando Labão terminou de vasculhar toda a sua tenda sem encontrar os ídolos,

[[v1-31-35]]

^<<v1-31-35,35>>^ Raquel disse ao pai: "Por favor, perdoe-me por não me levantar para o senhor, mas estou em meu período menstrual". Labão continuou a busca, mas não encontrou os ídolos da casa.

[[v1-31-36]]

^<<v1-31-36,36>>^ Jacó se enfureceu e discutiu com Labão. "Qual foi o meu crime?", perguntou ele. "O que fiz de errado para o senhor me perseguir como se eu fosse um criminoso?

[[v1-31-37]]

^<<v1-31-37,37>>^ O senhor vasculhou todos os meus bens. Por acaso encontrou algum objeto que lhe pertença? Coloque-o aqui, diante de nossos parentes, para que todos vejam. Que eles julguem entre nós dois!

[[v1-31-38]]

^<<v1-31-38,38>>^ "Estive vinte anos com o senhor, cuidando de seus rebanhos. Ao longo de todo esse tempo, suas ovelhas e cabras nunca abortaram. Não me servi de um carneiro sequer de seu rebanho para alimento.

[[v1-31-39]]

^<<v1-31-39,39>>^ Quando algum deles era despedaçado por um animal selvagem, eu nunca lhe mostrava a carcaça. Não, eu mesmo arcava com o prejuízo! O senhor me obrigava a pagar por todo animal roubado, quer à plena luz do dia, quer na escuridão da noite.

[[v1-31-40]]

^<<v1-31-40,40>>^ "Trabalhei para o senhor em dias de calor escaldante e também em noites frias e insones.

[[v1-31-41]]

^<<v1-31-41,41>>^ Sim, por vinte anos trabalhei feito um escravo em sua casa! Trabalhei catorze anos por suas duas filhas e, depois, mais seis anos para formar meu rebanho. E dez vezes o senhor mudou meu salário.

[[v1-31-42]]

^<<v1-31-42,42>>^ De fato, se o Deus de meu pai não estivesse comigo, o Deus de Abraão e o Deus temível de Isaque, o senhor teria me mandado embora de mãos vazias. Mas Deus viu como fui maltratado, apesar de meu árduo trabalho. Por isso ele lhe apareceu na noite passada e o repreendeu!"

[[v1-31-43]]

^<<v1-31-43,43>>^ Labão respondeu a Jacó: "Essas mulheres são minhas filhas, as crianças são meus netos, e os rebanhos são meus rebanhos. Na verdade, tudo que você vê é meu. Mas o que posso fazer agora por minhas filhas e pelos filhos delas?

[[v1-31-44]]

^<<v1-31-44,44>>^ Façamos, portanto, você e eu, uma aliança que sirva de testemunho do nosso compromisso".

[[v1-31-45]]

^<<v1-31-45,45>>^ Então Jacó pegou uma pedra e a colocou em pé como monumento.

[[v1-31-46]]

^<<v1-31-46,46>>^ Em seguida, disse aos membros de sua família: "Juntem algumas pedras". Eles pegaram as pedras e as amontoaram. Jacó e Labão se sentaram perto do monte de pedras e fizeram uma refeição para selar a aliança.

[[v1-31-47]]

^<<v1-31-47,47>>^ A fim de comemorar a ocasião, Labão chamou o lugar de Jegar-Saaduta, e Jacó o chamou de Galeede.

[[v1-31-48]]

^<<v1-31-48,48>>^ Labão declarou: "Este monte de pedras servirá de testemunha para nos lembrar da aliança que fizemos hoje". Isso explica por que o lugar foi chamado de Galeede.

[[v1-31-49]]

^<<v1-31-49,49>>^ Também foi chamado de Mispá, pois Labão disse: "Vigie o SENHOR a você e a mim para garantir que guardaremos esta aliança quando estivermos longe um do outro.

[[v1-31-50]]

^<<v1-31-50,50>>^ Se você maltratar minhas filhas ou se casar com outras mulheres, mesmo que ninguém mais veja, Deus verá. Ele é testemunha desta aliança entre nós."

[[v1-31-51]]

^<<v1-31-51,51>>^ "Veja este monte de pedras", prosseguiu Labão. "Veja também este monumento que levantei entre nós dois.

[[v1-31-52]]

^<<v1-31-52,52>>^ Estão entre mim e você como testemunhas dos nossos votos. Nunca atravessarei para o lado de lá do monte de pedras a fim de prejudicá-lo, e você jamais deve atravessar para o lado de cá a fim de prejudicar-me.

[[v1-31-53]]

^<<v1-31-53,53>>^ Invoco o Deus de nossos antepassados, o Deus de seu avô Abraão e o Deus de meu avô Naor, para que sirva de juiz entre nós." Assim, diante do Deus temível de seu pai Isaque, Jacó jurou respeitar a linha divisória.

[[v1-31-54]]

^<<v1-31-54,54>>^ Então Jacó ofereceu sacrifício a Deus na montanha e convidou todos para a refeição comemorativa. Depois de comerem, passaram a noite ali.

[[v1-31-55]]

^<<v1-31-55,55>>^ Na manhã seguinte, Labão se levantou cedo, beijou seus netos e suas filhas e os abençoou. Depois, partiu e voltou para casa.

'''

xref:001-genesis/001-genesis-030.adoc#v1-30-0[&#60; Capítulo Anterior] | <<v1-31-0,Topo>> | xref:001-genesis/001-genesis-032.adoc#v1-32-0[Próximo Capítulo &#62;]