include::./index.adoc[]

[[v1-47-0]]
=== Gênesis, 47
// nvt ?, NVT - Nova Versão Transformadora

[[v1-47-1]]

^<<v1-47-1,1>>^ José foi ver o faraó e lhe disse: "Meus pais e meus irmãos chegaram da terra de Canaã. Trouxeram seus rebanhos, seu gado e todos os seus bens, e agora estão na região de Gósen".

[[v1-47-2]]

^<<v1-47-2,2>>^ José levou consigo cinco de seus irmãos e os apresentou ao faraó.

[[v1-47-3]]

^<<v1-47-3,3>>^ "Em que vocês trabalham?", o faraó perguntou aos irmãos. Eles responderam: "Nós, seus servos, somos pastores, como nossos antepassados.

[[v1-47-4]]

^<<v1-47-4,4>>^ Viemos morar no Egito por algum tempo, pois não há pastagem para nossos rebanhos em Canaã. A fome é terrível naquela região. Por isso, pedimos sua permissão para morar na região de Gósen".

[[v1-47-5]]

^<<v1-47-5,5>>^ Então o faraó disse a José: "Agora que seu pai e seus irmãos estão com você,

[[v1-47-6]]

^<<v1-47-6,6>>^ escolha qualquer lugar em todo o Egito para morarem. Dê-lhes a melhor terra do Egito. Que vivam na região de Gósen. Se você descobrir entre eles homens capazes, coloque-os para cuidar de meus rebanhos".

[[v1-47-7]]

^<<v1-47-7,7>>^ Em seguida, José trouxe seu pai, Jacó, e o apresentou ao faraó. E Jacó abençoou o faraó.

[[v1-47-8]]

^<<v1-47-8,8>>^ "Quantos anos o senhor tem?", perguntou o faraó.

[[v1-47-9]]

^<<v1-47-9,9>>^ Jacó respondeu: "Tenho andado por este mundo há 130 árduos anos. Comparada à vida de meus antepassados, minha vida foi curta".

[[v1-47-10]]

^<<v1-47-10,10>>^ Então Jacó abençoou o faraó novamente antes de deixar a corte.

[[v1-47-11]]

^<<v1-47-11,11>>^ José deu a seu pai e a seus irmãos a melhor terra do Egito, a região de Ramessés, e os acomodou ali, conforme o faraó havia ordenado.

[[v1-47-12]]

^<<v1-47-12,12>>^ José também providenciou mantimentos para seu pai e seus irmãos, em quantidades proporcionais ao número de seus dependentes, incluindo as crianças pequenas.

[[v1-47-13]]

^<<v1-47-13,13>>^ A essa altura, a escassez era tanta que se esgotaram todos os mantimentos, e havia gente passando fome em toda a terra do Egito e de Canaã.

[[v1-47-14]]

^<<v1-47-14,14>>^ Com o tempo, vendendo cereais para o povo, José arrecadou todo o dinheiro do Egito e de Canaã e o depositou no tesouro do faraó.

[[v1-47-15]]

^<<v1-47-15,15>>^ Quando acabou o dinheiro do povo do Egito e de Canaã, todos os egípcios foram implorar a José: "Não temos mais dinheiro! Mas, por favor, dê-nos alimento, ou morreremos de fome diante dos seus olhos!".

[[v1-47-16]]

^<<v1-47-16,16>>^ José respondeu: "Visto que seu dinheiro acabou, tragam-me seus animais. Eu lhes darei alimento em troca".

[[v1-47-17]]

^<<v1-47-17,17>>^ Então eles entregaram seus animais a José em troca de alimento. José lhes forneceu mantimentos para mais um ano em troca de seus cavalos, rebanhos de ovelhas, bois e jumentos.

[[v1-47-18]]

^<<v1-47-18,18>>^ Mas aquele ano chegou ao fim e, no ano seguinte, o povo voltou a José, dizendo: "Não podemos esconder a verdade. Nosso dinheiro acabou, e nossos rebanhos e gado lhe pertencem. Não nos resta coisa alguma para oferecer além de nosso corpo e nossas terras.

[[v1-47-19]]

^<<v1-47-19,19>>^ Por que morreríamos de fome diante dos seus olhos? Compre nossas terras em troca de mantimento; oferecemos nossas propriedades e a nós mesmos como servos do faraó. Dê-nos cereais para que vivamos e não morramos, e para que a terra não fique vazia e desolada".

[[v1-47-20]]

^<<v1-47-20,20>>^ Assim, José comprou toda a terra do Egito para o faraó. Todos os egípcios venderam seus campos, pois a fome era terrível, e em pouco tempo todas as terras passaram a ser propriedade do faraó.

[[v1-47-21]]

^<<v1-47-21,21>>^ Quanto ao povo, José os tornou todos escravos, de uma extremidade do Egito à outra.

[[v1-47-22]]

^<<v1-47-22,22>>^ As únicas terras que ele não comprou foram as dos sacerdotes. Eles recebiam do faraó uma porção regular de mantimentos, por isso não precisaram vender suas terras.

[[v1-47-23]]

^<<v1-47-23,23>>^ Então José disse ao povo: "Hoje eu comprei vocês e suas terras para o faraó. Em troca, fornecerei sementes para cultivarem os campos.

[[v1-47-24]]

^<<v1-47-24,24>>^ Quando vocês os ceifarem, um quinto da colheita será do faraó. Fiquem com os outros quatro quintos e usem como alimento para vocês, para os membros de sua casa e para suas crianças".

[[v1-47-25]]

^<<v1-47-25,25>>^ "O senhor salvou nossa vida!", exclamaram. "Permita-nos servir ao faraó."

[[v1-47-26]]

^<<v1-47-26,26>>^ Então José mandou publicar um decreto que vale até hoje na terra do Egito, segundo o qual um quinto de todas as colheitas pertence ao faraó. Apenas as terras dos sacerdotes não foram entregues ao faraó.

[[v1-47-27]]

^<<v1-47-27,27>>^ Enquanto isso, o povo de Israel se estabeleceu na região de Gósen, no Egito. Ali, adquiriram propriedades e tiveram muitos filhos, e sua população cresceu rapidamente.

[[v1-47-28]]

^<<v1-47-28,28>>^ Depois de chegar ao Egito, Jacó viveu mais dezessete anos; portanto, viveu ao todo 147 anos.

[[v1-47-29]]

^<<v1-47-29,29>>^ Quando se aproximava a hora de sua morte, Jacó chamou seu filho José e lhe disse: "Peço que me faça um favor. Coloque sua mão debaixo da minha coxa e jure que mostrará sua bondade e lealdade a mim atendendo a este último desejo: não me sepulte no Egito.

[[v1-47-30]]

^<<v1-47-30,30>>^ Quando eu morrer, leve meu corpo para fora do Egito e sepulte-me com meus antepassados". José prometeu: "Farei como o senhor me pede".

[[v1-47-31]]

^<<v1-47-31,31>>^ "Jure que o fará", insistiu. José fez o juramento, e Jacó se curvou humildemente à cabeceira de sua cama.

'''

xref:001-genesis/001-genesis-046.adoc#v1-46-0[&#60; Capítulo Anterior] | <<v1-47-0,Topo>> | xref:001-genesis/001-genesis-048.adoc#v1-48-0[Próximo Capítulo &#62;]