include::./index.adoc[]

[[v51-3-0]]
=== Colossenses, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v51-3-1]]

^<<v51-3-1,1>>^ Uma vez que vocês ressuscitaram para uma nova vida com Cristo, mantenham os olhos fixos nas realidades do alto, onde Cristo está sentado no lugar de honra, à direita de Deus.

[[v51-3-2]]

^<<v51-3-2,2>>^ Pensem nas coisas do alto, e não nas coisas da terra.

[[v51-3-3]]

^<<v51-3-3,3>>^ Pois vocês morreram para esta vida, e agora sua verdadeira vida está escondida com Cristo em Deus.

[[v51-3-4]]

^<<v51-3-4,4>>^ E quando Cristo, que é sua vida, for revelado ao mundo inteiro, vocês participarão de sua glória.

[[v51-3-5]]

^<<v51-3-5,5>>^ Portanto, façam morrer as coisas pecaminosas e terrenas que estão dentro de vocês. Fiquem longe da imoralidade sexual, da impureza, da paixão sensual, dos desejos maus e da ganância, que é idolatria.

[[v51-3-6]]

^<<v51-3-6,6>>^ É por causa desses pecados que vem a ira de Deus.

[[v51-3-7]]

^<<v51-3-7,7>>^ Vocês costumavam praticá-los quando sua vida ainda fazia parte deste mundo,

[[v51-3-8]]

^<<v51-3-8,8>>^ mas agora é o momento de se livrarem da ira, da raiva, da maldade, da maledicência e da linguagem obscena.

[[v51-3-9]]

^<<v51-3-9,9>>^ Não mintam uns aos outros, pois vocês se despiram de sua antiga natureza e de todas as suas práticas perversas.

[[v51-3-10]]

^<<v51-3-10,10>>^ Revistam-se da nova natureza e sejam renovados à medida que aprendem a conhecer seu Criador e se tornam semelhantes a ele.

[[v51-3-11]]

^<<v51-3-11,11>>^ Nessa nova vida, não importa se você é judeu ou gentio, se é circuncidado ou incircuncidado, se é inculto ou incivilizado, se é escravo ou livre. Cristo é tudo que importa, e ele vive em todos.

[[v51-3-12]]

^<<v51-3-12,12>>^ Visto que Deus os escolheu para ser seu povo santo e amado, revistam-se de compaixão, bondade, humildade, mansidão e paciência.

[[v51-3-13]]

^<<v51-3-13,13>>^ Sejam compreensivos uns com os outros e perdoem quem os ofender. Lembrem-se de que o Senhor os perdoou, de modo que vocês também devem perdoar.

[[v51-3-14]]

^<<v51-3-14,14>>^ Acima de tudo, revistam-se do amor que une todos nós em perfeita harmonia.

[[v51-3-15]]

^<<v51-3-15,15>>^ Permitam que a paz de Cristo governe o seu coração, pois, como membros do mesmo corpo, vocês são chamados a viver em paz. E sejam sempre agradecidos.

[[v51-3-16]]

^<<v51-3-16,16>>^ Que a mensagem a respeito de Cristo, em toda a sua riqueza, preencha a vida de vocês. Ensinem e aconselhem uns aos outros com toda a sabedoria. Cantem a Deus salmos, hinos e cânticos espirituais com o coração agradecido.

[[v51-3-17]]

^<<v51-3-17,17>>^ E tudo que fizerem ou disserem, façam em nome do Senhor Jesus, dando graças a Deus, o Pai, por meio dele.

[[v51-3-18]]

^<<v51-3-18,18>>^ Esposas, sujeite-se cada uma a seu marido, como é próprio a quem está no Senhor.

[[v51-3-19]]

^<<v51-3-19,19>>^ Maridos, ame cada um a sua esposa e nunca a trate com aspereza.

[[v51-3-20]]

^<<v51-3-20,20>>^ Filhos, obedeçam sempre a seus pais, pois isso agrada ao Senhor.

[[v51-3-21]]

^<<v51-3-21,21>>^ Pais, não irritem seus filhos, para que eles não desanimem.

[[v51-3-22]]

^<<v51-3-22,22>>^ Escravos, em tudo obedeçam a seus senhores terrenos. Procurem agradá-los sempre, e não apenas quando eles estiverem observando. Sirvam-nos com sinceridade, por causa de seu temor ao Senhor.

[[v51-3-23]]

^<<v51-3-23,23>>^ Em tudo que fizerem, trabalhem de bom ânimo, como se fosse para o Senhor, e não para os homens.

[[v51-3-24]]

^<<v51-3-24,24>>^ Lembrem-se de que o Senhor lhes dará uma herança como recompensa e de que o Senhor a quem servem é Cristo.

[[v51-3-25]]

^<<v51-3-25,25>>^ Mas, se fizerem o mal, receberão de volta o mal, pois Deus não age com favoritismo.

'''

xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[&#60; Capítulo Anterior] | <<v51-3-0,Topo>> | xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[Próximo Capítulo &#62;]