include::./index.adoc[]

[[v51-1-0]]
=== Colossenses, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v51-1-1]]

^<<v51-1-1,1>>^ Eu, Paulo, apóstolo de Jesus Cristo pela vontade de Deus, escrevo esta carta, junto com nosso irmão Timóteo,

[[v51-1-2]]

^<<v51-1-2,2>>^ aos irmãos fiéis em Cristo, o povo santo na cidade de Colossos. Que Deus, nosso Pai, lhes dê graça e paz.

[[v51-1-3]]

^<<v51-1-3,3>>^ Sempre oramos por vocês e damos graças a Deus, o Pai de nosso Senhor Jesus Cristo,

[[v51-1-4]]

^<<v51-1-4,4>>^ pois temos ouvido falar de sua fé em Cristo Jesus e de seu amor por todo o povo santo,

[[v51-1-5]]

^<<v51-1-5,5>>^ que vêm da esperança confiante naquilo que lhes está reservado no céu. Vocês têm essa expectativa desde que ouviram pela primeira vez a verdade das boas-novas.

[[v51-1-6]]

^<<v51-1-6,6>>^ Agora, as mesmas boas-novas que chegaram até vocês estão se propagando pelo mundo todo. Elas têm crescido e dado frutos em toda parte, como ocorre entre vocês desde o dia em que ouviram e compreenderam a verdade sobre a graça de Deus.

[[v51-1-7]]

^<<v51-1-7,7>>^ Vocês aprenderam as boas-novas por meio de Epafras, nosso amado colaborador. Ele é servo fiel de Cristo e nos tem ajudado em favor de vocês.

[[v51-1-8]]

^<<v51-1-8,8>>^ Ele nos contou do amor que o Espírito lhes tem dado.

[[v51-1-9]]

^<<v51-1-9,9>>^ Por isso, desde que ouvimos falar a seu respeito, não deixamos de orar por vocês. Pedimos a Deus que lhes conceda pleno conhecimento de sua vontade e também sabedoria e entendimento espiritual.

[[v51-1-10]]

^<<v51-1-10,10>>^ Então vocês viverão de modo a sempre honrar e agradar ao Senhor, dando todo tipo de bom fruto e aprendendo a conhecer a Deus cada vez mais.

[[v51-1-11]]

^<<v51-1-11,11>>^ Oramos também para que sejam fortalecidos com o poder glorioso de Deus, a fim de que tenham toda a perseverança e paciência de que necessitam. Que sejam cheios de alegria

[[v51-1-12]]

^<<v51-1-12,12>>^ e sempre deem graças ao Pai. Ele os capacitou para participarem da herança que pertence ao seu povo santo, aqueles que vivem na luz.

[[v51-1-13]]

^<<v51-1-13,13>>^ Ele nos resgatou do poder das trevas e nos trouxe para o reino de seu Filho amado,

[[v51-1-14]]

^<<v51-1-14,14>>^ que comprou nossa liberdade e perdoou nossos pecados.

[[v51-1-15]]

^<<v51-1-15,15>>^ O Filho é a imagem do Deus invisível e é supremo sobre toda a criação.

[[v51-1-16]]

^<<v51-1-16,16>>^ Pois, por meio dele, todas as coisas foram criadas, tanto nos céus como na terra, todas as coisas que podemos ver e as que não podemos, como os tronos, reinos, governantes e as autoridades do mundo invisível. Tudo foi criado por meio dele e para ele.

[[v51-1-17]]

^<<v51-1-17,17>>^ Ele existia antes de todas as coisas e mantém tudo em harmonia.

[[v51-1-18]]

^<<v51-1-18,18>>^ Ele é a cabeça do corpo, que é a igreja. Ele é o princípio, supremo sobre os que ressuscitam dos mortos; portanto, ele é primeiro em tudo.

[[v51-1-19]]

^<<v51-1-19,19>>^ Pois foi do agrado do Pai que toda a plenitude habitasse no Filho,

[[v51-1-20]]

^<<v51-1-20,20>>^ e, por meio dele, o Pai reconciliou consigo todas as coisas. Por meio do sangue do Filho na cruz, o Pai fez as pazes com todas as coisas, tanto nos céus como na terra.

[[v51-1-21]]

^<<v51-1-21,21>>^ Isso inclui vocês, que antes estavam longe de Deus. Eram seus inimigos, dele separados por seus maus pensamentos e ações.

[[v51-1-22]]

^<<v51-1-22,22>>^ Agora, porém, ele os reconciliou consigo por meio da morte do Filho no corpo físico. Como resultado, vocês podem se apresentar diante dele santos, sem culpa e livres de qualquer acusação.

[[v51-1-23]]

^<<v51-1-23,23>>^ É preciso, porém, que continuem a crer nessa verdade e nela permaneçam firmes. Não se afastem da esperança que receberam quando ouviram as boas-novas, que foram anunciadas em todo o mundo e que eu, Paulo, fui designado servo para proclamar.

[[v51-1-24]]

^<<v51-1-24,24>>^ Alegro-me quando sofro por vocês em meu corpo, pois participo dos sofrimentos de Cristo, que continuam em favor de seu corpo, a igreja.

[[v51-1-25]]

^<<v51-1-25,25>>^ Deus me deu a responsabilidade de servir seu povo, anunciando-lhes sua mensagem completa.

[[v51-1-26]]

^<<v51-1-26,26>>^ Essa mensagem foi mantida em segredo por séculos e gerações, mas agora foi revelada ao seu povo santo,

[[v51-1-27]]

^<<v51-1-27,27>>^ pois Deus queria que eles soubessem que as riquezas gloriosas desse segredo também são para vocês, os gentios. E o segredo é este: Cristo está em vocês, o que lhes dá a confiante esperança de participar de sua glória!

[[v51-1-28]]

^<<v51-1-28,28>>^ Portanto, proclamamos a Cristo, advertindo a todos e ensinando a cada um com toda a sabedoria, para apresentá-los maduros em Cristo.

[[v51-1-29]]

^<<v51-1-29,29>>^ Por isso trabalho e luto com tanto esforço, na dependência de seu poder que atua em mim.

'''

xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v51-1-0,Topo>> | xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[Próximo Capítulo &#62;]