include::./index.adoc[]

[[v51-4-0]]
=== Colossenses, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v51-4-1]]

^<<v51-4-1,1>>^ Senhores, sejam justos e imparciais com seus escravos. Lembrem-se de que vocês também têm um Senhor no céu.

[[v51-4-2]]

^<<v51-4-2,2>>^ Dediquem-se à oração com a mente alerta e o coração agradecido.

[[v51-4-3]]

^<<v51-4-3,3>>^ Orem também por nós, para que Deus nos dê muitas oportunidades de falar do segredo a respeito de Cristo. É por esse motivo que sou prisioneiro.

[[v51-4-4]]

^<<v51-4-4,4>>^ Orem para que eu proclame essa mensagem com a devida clareza.

[[v51-4-5]]

^<<v51-4-5,5>>^ Vivam com sabedoria entre os que são de fora e aproveitem bem todas as oportunidades.

[[v51-4-6]]

^<<v51-4-6,6>>^ Que suas conversas sejam amistosas e agradáveis, a fim de que tenham a resposta certa para cada pessoa.

[[v51-4-7]]

^<<v51-4-7,7>>^ Tíquico, irmão amado e colaborador fiel que trabalha comigo na obra do Senhor, lhes dará um relatório completo de como tenho passado.

[[v51-4-8]]

^<<v51-4-8,8>>^ Eu o envio a vocês exatamente com o propósito de informá-los do que se passa conosco e de animá-los.

[[v51-4-9]]

^<<v51-4-9,9>>^ Envio também Onésimo, irmão fiel e amado, que é um de vocês. Ele e Tíquico lhes contarão tudo que tem acontecido aqui.

[[v51-4-10]]

^<<v51-4-10,10>>^ Aristarco, que é prisioneiro comigo, lhes envia saudações, e assim também Marcos, primo de Barnabé. Conforme vocês foram instruídos, se Marcos passar por aí, recebam-no bem.

[[v51-4-11]]

^<<v51-4-11,11>>^ Jesus, chamado Justo, também manda lembranças. Esses são os únicos irmãos judeus entre meus colaboradores. Eles trabalham comigo para o reino de Deus e têm sido um grande conforto para mim.

[[v51-4-12]]

^<<v51-4-12,12>>^ Epafras, que é um de vocês e servo de Cristo Jesus, lhes envia saudações. Ele sempre ora por vocês com fervor, pedindo que sejam maduros e plenamente confiantes de que praticam toda a vontade de Deus.

[[v51-4-13]]

^<<v51-4-13,13>>^ Posso lhes assegurar que ele tem se esforçado grandemente por vocês e pelos que estão em Laodiceia e em Hierápolis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Lucas, o médico amado, lhes envia saudações, assim como Demas.

[[v51-4-15]]

^<<v51-4-15,15>>^ Mandem minhas saudações a nossos irmãos em Laodiceia, e também a Ninfa e à igreja que se reúne em sua casa.

[[v51-4-16]]

^<<v51-4-16,16>>^ Depois que tiverem lido esta carta, enviem-na à igreja em Laodiceia, a fim de que eles também possam lê-la. E vocês, leiam a carta que eu escrevi para eles.

[[v51-4-17]]

^<<v51-4-17,17>>^ E digam a Arquipo: "Cuide em realizar o ministério que o Senhor lhe deu".

[[v51-4-18]]

^<<v51-4-18,18>>^ Esta é minha saudação de próprio punho: Paulo. Lembrem-se de que estou na prisão. Que a graça de Deus esteja com vocês.

'''

xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[Próximo Capítulo &#62;]