include::./index.adoc[]

[[v35-3-0]]
=== Habacuque, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v35-3-1]]

^<<v35-3-1,1>>^ O profeta Habacuque entoou esta oração:

[[v35-3-2]]

^<<v35-3-2,2>>^ Ouvi a teu respeito, SENHOR; estou maravilhado com tuas obras. Neste momento de tanta necessidade, ajuda-nos outra vez, como fizeste no passado. E, em tua ira, lembra-te de tua misericórdia.

[[v35-3-3]]

^<<v35-3-3,3>>^ Vejo Deus atravessar os desertos, vindo de Edom; o Santo vem do monte Parã. Interlúdio Seu esplendor envolve os céus, e a terra se enche de seu louvor.

[[v35-3-4]]

^<<v35-3-4,4>>^ Sua vinda é radiante como o nascer do sol; raios de luz saem de suas mãos, onde está escondido seu poder.

[[v35-3-5]]

^<<v35-3-5,5>>^ A peste marcha adiante dele, e a praga vem logo atrás.

[[v35-3-6]]

^<<v35-3-6,6>>^ Quando ele para, a terra estremece; quando ele olha, as nações tremem. Ele derruba os montes perpétuos e arrasa as colinas antigas; dele são os caminhos eternos.

[[v35-3-7]]

^<<v35-3-7,7>>^ Vejo o povo de Cusã em aflição, e a nação de Midiã treme de terror.

[[v35-3-8]]

^<<v35-3-8,8>>^ Foi com ira, SENHOR, que feriste os rios e dividiste o mar? Estavas furioso com eles? Não! Vinhas em tuas carruagens vitoriosas!

[[v35-3-9]]

^<<v35-3-9,9>>^ Pegaste teu arco e tua aljava cheia de flechas e dividiste a terra com rios. Interlúdio

[[v35-3-10]]

^<<v35-3-10,10>>^ Os montes viram e tremeram, e as águas avançaram com violência. O grande abismo clamou e levantou bem alto as mãos.

[[v35-3-11]]

^<<v35-3-11,11>>^ O sol e a lua pararam no céu enquanto tuas flechas brilhantes voavam e tua lança reluzente faiscava.

[[v35-3-12]]

^<<v35-3-12,12>>^ Marchaste pela terra com ira e, furioso, pisaste as nações.

[[v35-3-13]]

^<<v35-3-13,13>>^ Saíste para resgatar teu povo, para libertar teus ungidos. Esmagaste a cabeça dos perversos e os descobriste até os ossos.

[[v35-3-14]]

^<<v35-3-14,14>>^ Com tuas armas destruíste o líder dos que avançaram como um vendaval, pensando que o povo fosse presa fácil.

[[v35-3-15]]

^<<v35-3-15,15>>^ Marchaste sobre o mar com teus cavalos, e as águas poderosas se agitaram.

[[v35-3-16]]

^<<v35-3-16,16>>^ Estremeci por dentro quando ouvi isso; meus lábios tremeram de medo. Minhas pernas vacilaram, e tremi de terror. Esperarei em silêncio pelo dia em que a calamidade virá sobre nossos invasores.

[[v35-3-17]]

^<<v35-3-17,17>>^ Ainda que a figueira não floresça e não haja frutos nas videiras, ainda que a colheita de azeitonas não dê em nada e os campos fiquem vazios e improdutivos, ainda que os rebanhos morram nos campos e os currais fiquem vazios,

[[v35-3-18]]

^<<v35-3-18,18>>^ mesmo assim me alegrarei no SENHOR; exultarei no Deus de minha salvação!

[[v35-3-19]]

^<<v35-3-19,19>>^ O SENHOR Soberano é minha força! Ele torna meus pés firmes como os da corça, para que eu possa andar em lugares altos. (Ao regente do coral: Essa oração deve ser acompanhada por instrumentos de corda.)

'''

xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[&#60; Capítulo Anterior] | <<v35-3-0,Topo>> | xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[Próximo Capítulo &#62;]