include::./index.adoc[]

[[v35-2-0]]
=== Habacuque, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v35-2-1]]

^<<v35-2-1,1>>^ Subirei até minha torre de vigia e ficarei de guarda. Ali esperarei para ver o que ele diz, que resposta dará à minha queixa.

[[v35-2-2]]

^<<v35-2-2,2>>^ Então o SENHOR me disse: "Escreva minha resposta em tábuas, para que se possa ler depressa e com clareza.

[[v35-2-3]]

^<<v35-2-3,3>>^ Esta é uma visão do futuro; descreve o fim, e tudo se cumprirá. Se parecer que demora a vir, espere com paciência, pois certamente acontecerá; não se atrasará.

[[v35-2-4]]

^<<v35-2-4,4>>^ "Olhe para os arrogantes, os perversos que em si mesmos confiam; o justo, porém, viverá por sua fidelidade a Deus.

[[v35-2-5]]

^<<v35-2-5,5>>^ A riqueza é traiçoeira, e os arrogantes nunca descansam. Escancaram a boca como a sepultura e, como a morte, nunca se saciam. Em sua cobiça, ajuntaram muitas nações e engoliram muitos povos.

[[v35-2-6]]

^<<v35-2-6,6>>^ "Em breve, porém, seus cativos os insultarão; zombarão deles, dizendo: ‘Que aflição espera vocês, ladrões! Ficaram ricos pela extorsão; até quando continuarão desse modo?’.

[[v35-2-7]]

^<<v35-2-7,7>>^ De repente, seus credores tomarão providências; eles se voltarão contra vocês e levarão tudo que têm, enquanto vocês olham, trêmulos e indefesos.

[[v35-2-8]]

^<<v35-2-8,8>>^ Porque saquearam muitas nações, agora todos os sobreviventes os saquearão. Cometeram homicídio nos campos e encheram as cidades de violência.

[[v35-2-9]]

^<<v35-2-9,9>>^ "Que aflição espera vocês que constroem casas enormes com dinheiro obtido por meio de opressão! Acreditam que a riqueza comprará segurança e manterá sua família afastada do perigo.

[[v35-2-10]]

^<<v35-2-10,10>>^ Mas, com os homicídios que cometeram, envergonharam seu nome e condenaram a própria vida.

[[v35-2-11]]

^<<v35-2-11,11>>^ As pedras das paredes clamam contra vocês, e as vigas dos telhados também se queixam.

[[v35-2-12]]

^<<v35-2-12,12>>^ "Que aflição espera vocês que constroem cidades com dinheiro obtido por meio de homicídio e corrupção!

[[v35-2-13]]

^<<v35-2-13,13>>^ Acaso o SENHOR dos Exércitos não transformará em cinzas as riquezas das nações? Elas trabalham com afinco, mas de nada adianta.

[[v35-2-14]]

^<<v35-2-14,14>>^ Pois, assim como as águas enchem o mar, a terra se encherá do conhecimento da glória do SENHOR.

[[v35-2-15]]

^<<v35-2-15,15>>^ "Que aflição espera vocês que dão bebidas a seus companheiros! Vocês os obrigam a se embriagar e depois se alegram, maldosos, quando eles ficam nus e envergonhados.

[[v35-2-16]]

^<<v35-2-16,16>>^ Em breve, porém, será sua vez de serem humilhados; venham, bebam e fiquem despidos e expostos! Bebam do cálice do SENHOR, e toda a sua glória será transformada em desonra.

[[v35-2-17]]

^<<v35-2-17,17>>^ Derrubaram as florestas do Líbano, agora vocês serão derrubados. Destruíram os animais selvagens, agora o terror deles virá sobre vocês. Cometeram homicídio nos campos e encheram as cidades de violência.

[[v35-2-18]]

^<<v35-2-18,18>>^ "De que vale o ídolo esculpido por mãos humanas, ou a imagem de metal que só os engana? Como é tolo confiar em sua própria criação, num deus que nem sequer é capaz de falar!

[[v35-2-19]]

^<<v35-2-19,19>>^ Que aflição espera vocês que dizem a ídolos de madeira: ‘Despertem!’, e que dizem a imagens mudas de pedra: ‘Levantem-se!’. Acaso um ídolo pode lhes dizer o que fazer? Apesar de serem revestidos de ouro e prata, não há vida dentro deles.

[[v35-2-20]]

^<<v35-2-20,20>>^ O SENHOR, porém, está em seu santo templo; toda a terra cale-se diante dele."

'''

xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[&#60; Capítulo Anterior] | <<v35-2-0,Topo>> | xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[Próximo Capítulo &#62;]