include::./index.adoc[]

[[v33-3-0]]
=== Miquéias, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v33-3-1]]

^<<v33-3-1,1>>^ Eu disse: "Ouçam, líderes de Israel! Vocês deveriam saber o que é certo,

[[v33-3-2]]

^<<v33-3-2,2>>^ mas odeiam o bem e amam o mal. Esfolam meu povo e arrancam a carne de seus ossos.

[[v33-3-3]]

^<<v33-3-3,3>>^ Sim, comem a carne de meu povo; arrancam sua pele e quebram seus ossos. Cortam-no em pedaços, como carne para a panela.

[[v33-3-4]]

^<<v33-3-4,4>>^ Então, na hora da aflição, clamam ao SENHOR; esperam mesmo que ele responda? Depois de todo o mal que fizeram, ele nem olhará para vocês!".

[[v33-3-5]]

^<<v33-3-5,5>>^ Assim diz o SENHOR: "Vocês, falsos profetas, fazem meu povo se desviar! Prometem paz aos que lhes dão comida, mas anunciam guerra aos que não os alimentam.

[[v33-3-6]]

^<<v33-3-6,6>>^ Agora, a noite se fechará ao seu redor e acabará com suas visões. A escuridão os cobrirá e dará fim a suas predições. O sol se porá para os profetas, e seu dia chegará ao fim.

[[v33-3-7]]

^<<v33-3-7,7>>^ Então vocês, videntes, serão envergonhados, e vocês, adivinhos, serão humilhados. Cobrirão a boca, porque não há resposta de Deus".

[[v33-3-8]]

^<<v33-3-8,8>>^ Quanto a mim, estou cheio de poder, cheio do Espírito do SENHOR. Estou cheio de justiça e força para anunciar o pecado e a rebeldia de Israel.

[[v33-3-9]]

^<<v33-3-9,9>>^ Escutem, líderes de Israel! Vocês odeiam a justiça e distorcem o que é certo.

[[v33-3-10]]

^<<v33-3-10,10>>^ Constroem Jerusalém sobre um alicerce de homicídio e corrupção.

[[v33-3-11]]

^<<v33-3-11,11>>^ Os governantes julgam conforme os subornos que recebem, os sacerdotes cobram para ensinar a lei, os profetas só profetizam quando são pagos, e, no entanto, todos afirmam depender do SENHOR. Dizem: "Nenhum mal nos acontecerá, pois o SENHOR está em nosso meio".

[[v33-3-12]]

^<<v33-3-12,12>>^ Por causa de vocês, o monte Sião será arado como um campo; Jerusalém será transformada num monte de ruínas. Crescerá mato na colina, onde hoje fica o templo.

'''

xref:033-miqueias/033-miqueias-002.adoc#v33-2-0[&#60; Capítulo Anterior] | <<v33-3-0,Topo>> | xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[Próximo Capítulo &#62;]