include::./index.adoc[]

[[v33-1-0]]
=== Miquéias, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v33-1-1]]

^<<v33-1-1,1>>^ O SENHOR deu esta mensagem a Miqueias, de Moresete, durante os anos em que Jotão, Acaz e Ezequias foram reis de Judá. As visões diziam respeito a Samaria e a Jerusalém.

[[v33-1-2]]

^<<v33-1-2,2>>^ Prestem atenção, todos os povos! Que a terra e tudo que nela há ouçam! O SENHOR Soberano faz acusações contra vocês; de seu santo templo o Senhor fala.

[[v33-1-3]]

^<<v33-1-3,3>>^ Vejam, o SENHOR se aproxima! Ele deixa seu trono nos céus e pisa sobre os lugares altos da terra.

[[v33-1-4]]

^<<v33-1-4,4>>^ Os montes se derretem sob seus pés e escorrem para os vales, como cera no fogo, como água que desce pela encosta.

[[v33-1-5]]

^<<v33-1-5,5>>^ E por que isso acontece? Por causa da rebeldia de Israel, dos pecados dos descendentes de Jacó. Quem é responsável pela rebeldia de Israel? Samaria, sua capital! Onde fica o centro de idolatria de Judá? Em Jerusalém, sua capital!

[[v33-1-6]]

^<<v33-1-6,6>>^ "Por isso, transformarei a cidade de Samaria num monte de ruínas. Farei de suas ruas um campo para plantar videiras. Atirarei no vale as pedras de seus muros, até que os alicerces fiquem descobertos.

[[v33-1-7]]

^<<v33-1-7,7>>^ Todas as suas imagens esculpidas serão despedaçadas, todos os seus tesouros sagrados serão queimados. Isso tudo foi comprado com o pagamento de sua prostituição e será levado embora para pagar prostitutas em outro lugar."

[[v33-1-8]]

^<<v33-1-8,8>>^ Por isso, chorarei e lamentarei; andarei descalço e nu. Uivarei como o chacal e gemerei como a coruja.

[[v33-1-9]]

^<<v33-1-9,9>>^ Pois a ferida de meu povo não tem cura. Chegou a Judá, até as portas de Jerusalém.

[[v33-1-10]]

^<<v33-1-10,10>>^ Não contem isso a nossos inimigos em Gate; não chorem. Vocês, habitantes de Bete-Leafra, rolem no pó.

[[v33-1-11]]

^<<v33-1-11,11>>^ Vocês, habitantes de Safir, vão para o exílio, nus e envergonhados. Os habitantes de Zaanã não se atrevem a sair da cidade. Os habitantes de Bete-Ezel estão em prantos, pois não têm proteção.

[[v33-1-12]]

^<<v33-1-12,12>>^ Os habitantes de Marote anseiam por alívio, mas a calamidade do SENHOR chega até os portões de Jerusalém.

[[v33-1-13]]

^<<v33-1-13,13>>^ Atrelem os cavalos a suas carruagens e fujam, habitantes de Laquis. Você foi a primeira cidade em Judá a seguir Israel em sua rebeldia, e levou a bela Sião a pecar.

[[v33-1-14]]

^<<v33-1-14,14>>^ Deem presentes de despedida a Moresete-Gate; a cidade de Aczibe enganou os reis de Israel.

[[v33-1-15]]

^<<v33-1-15,15>>^ Ó habitantes de Maressa, trarei um conquistador para tomar sua cidade. E a liderança de Israel irá a Adulão.

[[v33-1-16]]

^<<v33-1-16,16>>^ Ó habitantes de Judá, raspem a cabeça, pois seus filhos queridos serão levados para longe. Fiquem calvos como a águia, pois seus pequenos serão exilados em terras distantes.

'''

xref:032-jonas/032-jonas-004.adoc#v32-4-0[&#60; Capítulo Anterior] | <<v33-1-0,Topo>> | xref:033-miqueias/033-miqueias-002.adoc#v33-2-0[Próximo Capítulo &#62;]