include::./index.adoc[]

[[v33-2-0]]
=== Miquéias, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v33-2-1]]

^<<v33-2-1,1>>^ Que aflição espera vocês que ficam acordados à noite fazendo planos perversos! Levantam-se ao amanhecer para realizá-los, só porque têm poder para isso.

[[v33-2-2]]

^<<v33-2-2,2>>^ Quando desejam um terreno, encontram um modo de se apropriar dele. Quando querem a casa de alguém, tomam-na por meio de violência. Oprimem um homem para que lhes entregue sua propriedade e deixam a família dele sem herança.

[[v33-2-3]]

^<<v33-2-3,3>>^ Portanto, assim diz o SENHOR: "Eu retribuirei sua maldade com maldade; não conseguirão livrar o pescoço do laço. Não andarão mais com arrogância, pois será um tempo de calamidade".

[[v33-2-4]]

^<<v33-2-4,4>>^ Naquele dia, seus inimigos zombarão de vocês e entoarão canções de lamento a seu respeito: "Estamos acabados, totalmente arruinados! Deus confiscou nossa terra, ele a tomou de nós. Entregou nossos campos àqueles que nos levaram cativos".

[[v33-2-5]]

^<<v33-2-5,5>>^ Então outros estabelecerão suas divisas, e o povo do SENHOR será ignorado na hora de repartir a terra.

[[v33-2-6]]

^<<v33-2-6,6>>^ "Não diga uma coisa dessas", o povo responde. "Não profetize dessa maneira; essa desgraça jamais nos acontecerá!"

[[v33-2-7]]

^<<v33-2-7,7>>^ Acaso deve falar desse modo, ó povo de Israel? O Espírito do SENHOR terá paciência com essa conduta? Se fizesse o que é certo, minhas palavras lhe trariam consolo.

[[v33-2-8]]

^<<v33-2-8,8>>^ Até agora, porém, meu povo se rebela contra mim, como se fosse um inimigo. Roubam a túnica daqueles que confiaram em vocês e os deixam aos farrapos, como quem volta da batalha.

[[v33-2-9]]

^<<v33-2-9,9>>^ Expulsaram mulheres de seus lares confortáveis e tomaram para sempre de seus filhos tudo que Deus lhes deu.

[[v33-2-10]]

^<<v33-2-10,10>>^ Levantem-se! Vão embora! Esta não é mais sua terra nem seu lar, pois vocês a encheram de pecado e a arruinaram por completo.

[[v33-2-11]]

^<<v33-2-11,11>>^ Se um profeta que vive a mentir lhes dissesse: "Proclamarei para vocês as alegrias do vinho e da bebida forte", de um profeta assim vocês se alegrariam!

[[v33-2-12]]

^<<v33-2-12,12>>^ "Algum dia, ó Israel, reunirei os que restaram. Juntarei vocês novamente, como ovelhas no curral, como rebanho em seu pasto. Sim, sua terra voltará a se encher do ruído das multidões.

[[v33-2-13]]

^<<v33-2-13,13>>^ Seu líder abrirá o caminho e os conduzirá para fora do exílio, pelas portas das cidades inimigas, de volta para sua terra. Seu rei os conduzirá; o próprio SENHOR os guiará."

'''

xref:033-miqueias/033-miqueias-001.adoc#v33-1-0[&#60; Capítulo Anterior] | <<v33-2-0,Topo>> | xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[Próximo Capítulo &#62;]