include::./index.adoc[]

[[v33-5-0]]
=== Miquéias, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v33-5-1]]

^<<v33-5-1,1>>^ Mobilizem-se! Reúnam suas tropas! O inimigo cerca Jerusalém. Com uma vara ferirá o rosto do líder de Israel.

[[v33-5-2]]

^<<v33-5-2,2>>^ Mas você, ó Belém Efrata, é apenas uma pequena vila entre todo o povo de Judá. E, no entanto, um governante de Israel, cujas origens são do passado distante, sairá de você em meu favor.

[[v33-5-3]]

^<<v33-5-3,3>>^ O povo de Israel será entregue a seus inimigos, até que a mulher em trabalho de parto dê à luz. Por fim, seus compatriotas voltarão do exílio para sua própria terra.

[[v33-5-4]]

^<<v33-5-4,4>>^ Ele se levantará para conduzir seu rebanho com a força do Senhor e a majestade do nome do SENHOR, seu Deus. Então seu povo viverá tranquilo, pois ele será exaltado em todo o mundo

[[v33-5-5]]

^<<v33-5-5,5>>^ e será a fonte de paz. Quando os assírios invadirem nossa terra e romperem nossas defesas, nomearemos sete pastores para nos proteger, oito príncipes para nos conduzir.

[[v33-5-6]]

^<<v33-5-6,6>>^ Eles conquistarão a Assíria com a espada e entrarão pelas portas da terra de Ninrode. Ele nos livrará dos assírios, quando eles passarem pelas fronteiras para invadir nossa terra.

[[v33-5-7]]

^<<v33-5-7,7>>^ Então o remanescente de Israel ocupará seu lugar entre as nações. Será como o orvalho enviado pelo SENHOR, como a chuva que cai sobre a grama, que ninguém é capaz de conter e ninguém consegue deter.

[[v33-5-8]]

^<<v33-5-8,8>>^ Sim, o remanescente de Israel ocupará seu lugar entre as nações. Será como o leão entre os animais no bosque, como o leão forte no meio de rebanhos de ovelhas, que as ataca e as despedaça quando passam, sem que ninguém as livre.

[[v33-5-9]]

^<<v33-5-9,9>>^ O povo de Israel enfrentará seus adversários, e todos os seus inimigos serão exterminados.

[[v33-5-10]]

^<<v33-5-10,10>>^ "Naquele dia", diz o SENHOR, "matarei seus cavalos e destruirei seus carros de guerra.

[[v33-5-11]]

^<<v33-5-11,11>>^ Derrubarei seus muros e demolirei suas fortalezas.

[[v33-5-12]]

^<<v33-5-12,12>>^ Acabarei com a prática da feitiçaria, e não haverá mais adivinhos.

[[v33-5-13]]

^<<v33-5-13,13>>^ Destruirei seus ídolos e suas colunas sagradas, para que vocês nunca mais adorem as obras de suas mãos.

[[v33-5-14]]

^<<v33-5-14,14>>^ Acabarei com seus santuários e postes de Aserá e destruirei suas cidades.

[[v33-5-15]]

^<<v33-5-15,15>>^ Com terrível ira, derramarei minha vingança sobre todas as nações que não me obedeceram."

'''

xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[&#60; Capítulo Anterior] | <<v33-5-0,Topo>> | xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[Próximo Capítulo &#62;]