include::./index.adoc[]

[[v33-7-0]]
=== Miquéias, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v33-7-1]]

^<<v33-7-1,1>>^ Pobre de mim! Sinto-me como quem apanha frutas depois da colheita e nada encontra para comer. Não há um cacho de uvas sequer, nem um único figo novo para saciar minha fome.

[[v33-7-2]]

^<<v33-7-2,2>>^ Os fiéis desapareceram; não resta uma só pessoa honesta na terra. São todos assassinos, que preparam armadilhas até para os próprios irmãos;

[[v33-7-3]]

^<<v33-7-3,3>>^ suas mãos são hábeis para fazer o mal. Governantes e juízes exigem subornos; os mais influentes conseguem o que querem e tramam juntos para perverter a justiça.

[[v33-7-4]]

^<<v33-7-4,4>>^ Até o melhor deles é como um espinheiro, e o mais honesto é perigoso como uma cerca de espinhos. Mas o dia anunciado se aproxima; está chegando a hora de seu castigo, um tempo de confusão.

[[v33-7-5]]

^<<v33-7-5,5>>^ Não confie em ninguém, nem mesmo em seu melhor amigo, nem sequer em sua esposa.

[[v33-7-6]]

^<<v33-7-6,6>>^ Pois o filho despreza o pai, a filha se rebela contra a mãe, a nora se rebela contra a sogra; seus inimigos estão em sua própria casa!

[[v33-7-7]]

^<<v33-7-7,7>>^ Quanto a mim, busco o Senhor e espero confiante que Deus me salve; certamente meu Deus me ouvirá!

[[v33-7-8]]

^<<v33-7-8,8>>^ Não se alegrem, meus inimigos; pois, mesmo que eu caia, voltarei a me levantar. Ainda que eu esteja em trevas, o SENHOR será minha luz.

[[v33-7-9]]

^<<v33-7-9,9>>^ Serei paciente enquanto o SENHOR me castiga, pois pequei contra ele. Depois disso, ele defenderá minha causa e fará o que é direito. O SENHOR me levará para a luz, e verei sua justiça.

[[v33-7-10]]

^<<v33-7-10,10>>^ Então meus inimigos verão que o SENHOR está do meu lado e se envergonharão de ter dito: "Onde está o SENHOR, seu Deus?". Com os próprios olhos eu os verei cair; serão pisados como lama nas ruas.

[[v33-7-11]]

^<<v33-7-11,11>>^ Naquele dia, Israel, seus muros serão reconstruídos, e suas fronteiras, ampliadas.

[[v33-7-12]]

^<<v33-7-12,12>>^ Gente de muitas terras virá até você: desde a Assíria até as cidades do Egito, desde o Egito até o rio Eufrates, e de mares e montes distantes.

[[v33-7-13]]

^<<v33-7-13,13>>^ A terra, porém, ficará vazia e desolada, por causa da maldade dos que nela habitam.

[[v33-7-14]]

^<<v33-7-14,14>>^ Ó SENHOR, protege teu povo com teu cajado de pastor; conduz este rebanho que pertence a ti! Embora vivam sozinhos num bosque no alto do monte Carmelo, leva-os para pastar nos campos verdes de Basã e Gileade, como faziam muito tempo atrás.

[[v33-7-15]]

^<<v33-7-15,15>>^ "Sim, realizarei grandes milagres em seu favor, como fiz quando os resgatei da terra do Egito."

[[v33-7-16]]

^<<v33-7-16,16>>^ Todas as nações ficarão admiradas do que o SENHOR fará por vocês. Elas terão vergonha de seu pequeno poder; cobrirão a boca com as mãos e taparão os ouvidos.

[[v33-7-17]]

^<<v33-7-17,17>>^ Como serpentes que rastejam para fora de seus esconderijos, sairão ao encontro do SENHOR, nosso Deus. Terão muito temor dele e tremerão em sua presença.

[[v33-7-18]]

^<<v33-7-18,18>>^ Que outro Deus há semelhante a ti, que perdoas a culpa do remanescente e esqueces os pecados dos que te pertencem? Não permanecerás irado com teu povo para sempre, pois tens prazer em mostrar teu amor.

[[v33-7-19]]

^<<v33-7-19,19>>^ Voltarás a ter compaixão de nós; pisarás nossas maldades sob teus pés e lançarás nossos pecados nas profundezas do mar.

[[v33-7-20]]

^<<v33-7-20,20>>^ Tu nos mostrarás tua fidelidade e teu amor como prometeste há muito tempo a Abraão e a Jacó, nossos antepassados.

'''

xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[&#60; Capítulo Anterior] | <<v33-7-0,Topo>> | xref:034-naum/034-naum-001.adoc#v34-1-0[Próximo Capítulo &#62;]