include::./index.adoc[]

[[v49-2-0]]
=== Efésios, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v49-2-1]]

^<<v49-2-1,1>>^ Vocês estavam mortos por causa de sua desobediência e de seus muitos pecados,

[[v49-2-2]]

^<<v49-2-2,2>>^ nos quais costumavam viver, como o resto do mundo, obedecendo ao comandante dos poderes do mundo invisível. Ele é o espírito que opera no coração dos que se recusam a obedecer.

[[v49-2-3]]

^<<v49-2-3,3>>^ Todos nós vivíamos desse modo, seguindo os desejos ardentes e as inclinações de nossa natureza humana. Éramos, por natureza, merecedores da ira, como os demais.

[[v49-2-4]]

^<<v49-2-4,4>>^ Mas Deus é tão rico em misericórdia e nos amou tanto

[[v49-2-5]]

^<<v49-2-5,5>>^ que, embora estivéssemos mortos por causa de nossos pecados, ele nos deu vida juntamente com Cristo. É pela graça que vocês são salvos!

[[v49-2-6]]

^<<v49-2-6,6>>^ Pois ele nos ressuscitou com Cristo e nos fez sentar com ele nos domínios celestiais, porque agora estamos em Cristo Jesus.

[[v49-2-7]]

^<<v49-2-7,7>>^ Portanto, nas eras futuras, Deus poderá apontar-nos como exemplos da riqueza insuperável de sua graça, revelada na bondade que ele demonstrou por nós em Cristo Jesus.

[[v49-2-8]]

^<<v49-2-8,8>>^ Vocês são salvos pela graça, por meio da fé. Isso não vem de vocês; é uma dádiva de Deus.

[[v49-2-9]]

^<<v49-2-9,9>>^ Não é uma recompensa pela prática de boas obras, para que ninguém venha a se orgulhar.

[[v49-2-10]]

^<<v49-2-10,10>>^ Pois somos obra-prima de Deus, criados em Cristo Jesus a fim de realizar as boas obras que ele de antemão planejou para nós.

[[v49-2-11]]

^<<v49-2-11,11>>^ Não esqueçam que vocês, gentios, eram chamados de "incircuncidados" pelos judeus que se orgulhavam da circuncisão, embora ela fosse apenas um ritual exterior e humano.

[[v49-2-12]]

^<<v49-2-12,12>>^ Naquele tempo, vocês viviam afastados de Cristo. Não tinham os privilégios do povo de Israel e não conheciam as promessas da aliança. Viviam no mundo sem Deus e sem esperança.

[[v49-2-13]]

^<<v49-2-13,13>>^ Agora, porém, estão em Cristo Jesus. Antigamente, estavam distantes de Deus, mas agora foram trazidos para perto dele por meio do sangue de Cristo.

[[v49-2-14]]

^<<v49-2-14,14>>^ Porque Cristo é nossa paz. Ele uniu judeus e gentios em um só povo ao derrubar o muro de inimizade que nos separava.

[[v49-2-15]]

^<<v49-2-15,15>>^ Ele acabou com o sistema da lei, com seus mandamentos e ordenanças, promovendo a paz ao criar para si, desses dois grupos, uma nova humanidade.

[[v49-2-16]]

^<<v49-2-16,16>>^ Assim, ele os reconciliou com Deus em um só corpo por meio de sua morte na cruz, eliminando a inimizade que havia entre eles.

[[v49-2-17]]

^<<v49-2-17,17>>^ Ele trouxe essas boas-novas de paz tanto a vocês que estavam distantes dele como aos que estavam perto.

[[v49-2-18]]

^<<v49-2-18,18>>^ Agora, por causa do que Cristo fez, todos temos acesso ao Pai pelo mesmo Espírito.

[[v49-2-19]]

^<<v49-2-19,19>>^ Portanto, vocês já não são estranhos e forasteiros, mas concidadãos do povo santo e membros da família de Deus.

[[v49-2-20]]

^<<v49-2-20,20>>^ Juntos, somos sua casa, edificados sobre os alicerces dos apóstolos e dos profetas. E a pedra angular é o próprio Cristo Jesus.

[[v49-2-21]]

^<<v49-2-21,21>>^ Nele somos firmemente unidos, constituindo um templo santo para o Senhor.

[[v49-2-22]]

^<<v49-2-22,22>>^ Por meio dele, vocês também estão sendo edificados como parte dessa habitação, onde Deus vive por seu Espírito.

'''

xref:049-efesios/049-efesios-001.adoc#v49-1-0[&#60; Capítulo Anterior] | <<v49-2-0,Topo>> | xref:049-efesios/049-efesios-003.adoc#v49-3-0[Próximo Capítulo &#62;]