include::./index.adoc[]

[[v49-6-0]]
=== Efésios, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v49-6-1]]

^<<v49-6-1,1>>^ Filhos, obedeçam a seus pais no Senhor, porque isso é o certo a fazer.

[[v49-6-2]]

^<<v49-6-2,2>>^ "Honre seu pai e sua mãe." Esse é o primeiro mandamento com promessa.

[[v49-6-3]]

^<<v49-6-3,3>>^ Se honrar pai e mãe, "tudo lhe irá bem e terá vida longa na terra".

[[v49-6-4]]

^<<v49-6-4,4>>^ Pais, não tratem seus filhos de modo a irritá-los; antes, eduquem-nos com a disciplina e a instrução que vêm do Senhor.

[[v49-6-5]]

^<<v49-6-5,5>>^ Escravos, obedeçam a seus senhores terrenos com respeito e temor. Sirvam com sinceridade, como serviriam a Cristo.

[[v49-6-6]]

^<<v49-6-6,6>>^ Procurem agradá-los sempre, e não apenas quando eles estiverem observando. Como escravos de Cristo, façam a vontade de Deus de todo o coração.

[[v49-6-7]]

^<<v49-6-7,7>>^ Trabalhem com entusiasmo, como se servissem ao Senhor, e não a homens.

[[v49-6-8]]

^<<v49-6-8,8>>^ Lembrem-se de que o Senhor recompensará cada um de nós pelo bem que fizermos, quer sejamos escravos, quer livres.

[[v49-6-9]]

^<<v49-6-9,9>>^ Senhores, assim também tratem seus escravos. Não os ameacem; lembrem-se de que vocês e eles têm o mesmo Senhor no céu, e ele não age com favoritismo.

[[v49-6-10]]

^<<v49-6-10,10>>^ Uma palavra final: Sejam fortes no Senhor e em seu grande poder.

[[v49-6-11]]

^<<v49-6-11,11>>^ Vistam toda a armadura de Deus, para que possam permanecer firmes contra as estratégias do diabo.

[[v49-6-12]]

^<<v49-6-12,12>>^ Pois nós não lutamos contra inimigos de carne e sangue, mas contra governantes e autoridades do mundo invisível, contra grandes poderes neste mundo de trevas e contra espíritos malignos nas esferas celestiais.

[[v49-6-13]]

^<<v49-6-13,13>>^ Portanto, vistam toda a armadura de Deus, para que possam resistir ao inimigo no tempo do mal. Então, depois da batalha, vocês continuarão de pé e firmes.

[[v49-6-14]]

^<<v49-6-14,14>>^ Assim, mantenham sua posição, colocando o cinto da verdade e a couraça da justiça.

[[v49-6-15]]

^<<v49-6-15,15>>^ Como calçados, usem a paz das boas-novas, para que estejam inteiramente preparados.

[[v49-6-16]]

^<<v49-6-16,16>>^ Em todas as situações, levantem o escudo da fé, para deter as flechas de fogo do maligno.

[[v49-6-17]]

^<<v49-6-17,17>>^ Usem a salvação como capacete e empunhem a espada do Espírito, que é a palavra de Deus.

[[v49-6-18]]

^<<v49-6-18,18>>^ Orem no Espírito em todos os momentos e ocasiões. Permaneçam atentos e sejam persistentes em suas orações por todo o povo santo.

[[v49-6-19]]

^<<v49-6-19,19>>^ E orem também por mim. Peçam que Deus me conceda as palavras certas, para que eu possa explicar corajosamente o segredo revelado pelas boas-novas.

[[v49-6-20]]

^<<v49-6-20,20>>^ Agora estou preso em correntes, mas continuo a anunciar essa mensagem como embaixador de Deus. Portanto, orem para que eu siga falando corajosamente em nome dele, como é meu dever.

[[v49-6-21]]

^<<v49-6-21,21>>^ Tíquico lhes dará um relatório completo do que tenho feito e de como tenho passado. Ele é um irmão amado e um colaborador fiel na obra do Senhor.

[[v49-6-22]]

^<<v49-6-22,22>>^ Eu o enviei a vocês com esse propósito, para que saibam como estamos e para animá-los.

[[v49-6-23]]

^<<v49-6-23,23>>^ A paz seja com vocês, irmãos, e que Deus, o Pai, e o Senhor Jesus Cristo lhes deem amor e fidelidade.

[[v49-6-24]]

^<<v49-6-24,24>>^ Que a graça de Deus esteja eternamente sobre todos que amam nosso Senhor Jesus Cristo.

'''

xref:049-efesios/049-efesios-005.adoc#v49-5-0[&#60; Capítulo Anterior] | <<v49-6-0,Topo>> | xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[Próximo Capítulo &#62;]