include::./index.adoc[]

[[v49-4-0]]
=== Efésios, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v49-4-1]]

^<<v49-4-1,1>>^ Portanto, como prisioneiro no Senhor, suplico-lhes que vivam de modo digno do chamado que receberam.

[[v49-4-2]]

^<<v49-4-2,2>>^ Sejam sempre humildes e amáveis, tolerando pacientemente uns aos outros em amor.

[[v49-4-3]]

^<<v49-4-3,3>>^ Façam todo o possível para se manterem unidos no Espírito, ligados pelo vínculo da paz.

[[v49-4-4]]

^<<v49-4-4,4>>^ Pois há um só corpo e um só Espírito, assim como vocês foram chamados para uma só esperança.

[[v49-4-5]]

^<<v49-4-5,5>>^ Há um só Senhor, uma só fé, um só batismo,

[[v49-4-6]]

^<<v49-4-6,6>>^ um só Deus e Pai de tudo, o qual está sobre todos, em todos, e vive por meio de todos.

[[v49-4-7]]

^<<v49-4-7,7>>^ A cada um de nós, porém, ele concedeu uma dádiva, por meio da generosidade de Cristo.

[[v49-4-8]]

^<<v49-4-8,8>>^ Por isso as Escrituras dizem: "Quando ele subiu às alturas, levou muitos prisioneiros e concedeu dádivas ao povo".

[[v49-4-9]]

^<<v49-4-9,9>>^ Notem que diz que "ele subiu". Por certo, isso significa que Cristo também desceu ao mundo inferior.

[[v49-4-10]]

^<<v49-4-10,10>>^ E aquele que desceu é o mesmo que subiu acima de todos os céus, a fim de encher consigo mesmo todas as coisas.

[[v49-4-11]]

^<<v49-4-11,11>>^ Ele designou alguns para apóstolos, outros para profetas, outros para evangelistas, outros para pastores e mestres.

[[v49-4-12]]

^<<v49-4-12,12>>^ Eles são responsáveis por preparar o povo santo para realizar sua obra e edificar o corpo de Cristo,

[[v49-4-13]]

^<<v49-4-13,13>>^ até que todos alcancemos a unidade que a fé e o conhecimento do Filho de Deus produzem e amadureçamos, chegando à completa medida da estatura de Cristo.

[[v49-4-14]]

^<<v49-4-14,14>>^ Então não seremos mais imaturos como crianças, nem levados de um lado para outro, empurrados por qualquer vento de novos ensinamentos, e também não seremos influenciados quando nos tentarem enganar com mentiras astutas.

[[v49-4-15]]

^<<v49-4-15,15>>^ Em vez disso, falaremos a verdade em amor, tornando-nos, em todos os aspectos, cada vez mais parecidos com Cristo, que é a cabeça.

[[v49-4-16]]

^<<v49-4-16,16>>^ Ele faz que todo o corpo se encaixe perfeitamente. E cada parte, ao cumprir sua função específica, ajuda as demais a crescer, para que todo o corpo se desenvolva e seja saudável em amor.

[[v49-4-17]]

^<<v49-4-17,17>>^ Assim, eu lhes digo com a autoridade do Senhor: não vivam mais como os gentios, levados por pensamentos vazios e inúteis.

[[v49-4-18]]

^<<v49-4-18,18>>^ A mente deles está mergulhada na escuridão. Andam sem rumo, alienados da vida que Deus dá, pois são ignorantes e endureceram o coração para ele.

[[v49-4-19]]

^<<v49-4-19,19>>^ Tornaram-se insensíveis, vivem em função dos prazeres sensuais e praticam avidamente toda espécie de impureza.

[[v49-4-20]]

^<<v49-4-20,20>>^ Mas não foi isso que vocês aprenderam de Cristo.

[[v49-4-21]]

^<<v49-4-21,21>>^ Uma vez que ouviram falar de Jesus e foram ensinados sobre a verdade que vem dele,

[[v49-4-22]]

^<<v49-4-22,22>>^ livrem-se de sua antiga natureza e de seu velho modo de viver, corrompido pelos desejos impuros e pelo engano.

[[v49-4-23]]

^<<v49-4-23,23>>^ Deixem que o Espírito renove seus pensamentos e atitudes

[[v49-4-24]]

^<<v49-4-24,24>>^ e revistam-se de sua nova natureza, criada para ser verdadeiramente justa e santa como Deus.

[[v49-4-25]]

^<<v49-4-25,25>>^ Portanto, abandonem a mentira e digam a verdade a seu próximo, pois somos todos parte do mesmo corpo.

[[v49-4-26]]

^<<v49-4-26,26>>^ E "não pequem ao permitir que a ira os controle". Acalmem a ira antes que o sol se ponha,

[[v49-4-27]]

^<<v49-4-27,27>>^ pois ela cria oportunidades para o diabo.

[[v49-4-28]]

^<<v49-4-28,28>>^ Quem é ladrão, pare de roubar. Em vez disso, use as mãos para trabalhar com empenho e honestidade e, assim, ajudar generosamente os necessitados.

[[v49-4-29]]

^<<v49-4-29,29>>^ Evitem o linguajar sujo e insultante. Que todas as suas palavras sejam boas e úteis, a fim de dar ânimo àqueles que as ouvirem.

[[v49-4-30]]

^<<v49-4-30,30>>^ Não entristeçam o Espírito Santo de Deus, o selo que ele colocou sobre vocês para o dia em que nos resgatará como sua propriedade.

[[v49-4-31]]

^<<v49-4-31,31>>^ Livrem-se de toda amargura, raiva, ira, das palavras ásperas e da calúnia, e de todo tipo de maldade.

[[v49-4-32]]

^<<v49-4-32,32>>^ Em vez disso, sejam bondosos e tenham compaixão uns dos outros, perdoando-se como Deus os perdoou em Cristo.

'''

xref:049-efesios/049-efesios-003.adoc#v49-3-0[&#60; Capítulo Anterior] | <<v49-4-0,Topo>> | xref:049-efesios/049-efesios-005.adoc#v49-5-0[Próximo Capítulo &#62;]