include::./index.adoc[]

[[v49-1-0]]
=== Efésios, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v49-1-1]]

^<<v49-1-1,1>>^ Eu, Paulo, apóstolo de Cristo Jesus pela vontade de Deus, escrevo esta carta ao povo santo em Éfeso, seguidores fiéis de Cristo Jesus.

[[v49-1-2]]

^<<v49-1-2,2>>^ Que Deus, nosso Pai, e o Senhor Jesus Cristo lhes deem graça e paz.

[[v49-1-3]]

^<<v49-1-3,3>>^ Todo louvor seja a Deus, o Pai de nosso Senhor Jesus Cristo, que nos abençoou em Cristo com todas as bênçãos espirituais nos domínios celestiais.

[[v49-1-4]]

^<<v49-1-4,4>>^ Mesmo antes de criar o mundo, Deus nos amou e nos escolheu em Cristo para sermos santos e sem culpa diante dele.

[[v49-1-5]]

^<<v49-1-5,5>>^ Ele nos predestinou para si, para nos adotar como filhos por meio de Jesus Cristo, conforme o bom propósito de sua vontade.

[[v49-1-6]]

^<<v49-1-6,6>>^ Deus assim o fez para o louvor de sua graça gloriosa, que ele derramou sobre nós em seu Filho amado.

[[v49-1-7]]

^<<v49-1-7,7>>^ Ele é tão rico em graça que comprou nossa liberdade com o sangue de seu Filho e perdoou nossos pecados.

[[v49-1-8]]

^<<v49-1-8,8>>^ Generosamente, derramou sua graça sobre nós e, com ela, toda sabedoria e todo entendimento.

[[v49-1-9]]

^<<v49-1-9,9>>^ Agora Deus nos revelou sua vontade secreta a respeito de Cristo, isto é, o cumprimento de seu bom propósito.

[[v49-1-10]]

^<<v49-1-10,10>>^ E o plano é este: no devido tempo, ele reunirá sob a autoridade de Cristo tudo que existe nos céus e na terra.

[[v49-1-11]]

^<<v49-1-11,11>>^ Além disso, em Cristo nós nos tornamos herdeiros de Deus, pois ele nos predestinou conforme seu plano e faz que tudo ocorra de acordo com sua vontade.

[[v49-1-12]]

^<<v49-1-12,12>>^ O propósito de Deus era que nós, os primeiros a confiar em Cristo, louvássemos a Deus e lhe déssemos glória.

[[v49-1-13]]

^<<v49-1-13,13>>^ Agora vocês também ouviram a verdade, as boas-novas da salvação. E, quando creram em Cristo, ele colocou sobre vocês o selo do Espírito Santo que havia prometido.

[[v49-1-14]]

^<<v49-1-14,14>>^ O Espírito é a garantia de nossa herança, até o dia em que Deus nos resgatará como sua propriedade, para o louvor de sua glória.

[[v49-1-15]]

^<<v49-1-15,15>>^ Desde que eu soube de sua fé no Senhor Jesus e de seu amor pelo povo santo em toda parte,

[[v49-1-16]]

^<<v49-1-16,16>>^ não deixo de agradecer a Deus por vocês. Em minhas orações,

[[v49-1-17]]

^<<v49-1-17,17>>^ peço que Deus, o Pai glorioso de nosso Senhor Jesus Cristo, lhes dê sabedoria espiritual e entendimento para que cresçam no conhecimento dele.

[[v49-1-18]]

^<<v49-1-18,18>>^ Oro para que seu coração seja iluminado, a fim de que compreendam a esperança concedida àqueles que ele chamou e a rica e gloriosa herança que ele deu a seu povo santo.

[[v49-1-19]]

^<<v49-1-19,19>>^ Também oro para que entendam a grandeza insuperável do poder de Deus para conosco, os que cremos. É o mesmo poder grandioso

[[v49-1-20]]

^<<v49-1-20,20>>^ que ressuscitou Cristo dos mortos e o fez sentar-se no lugar de honra, à direita de Deus, nos domínios celestiais.

[[v49-1-21]]

^<<v49-1-21,21>>^ Agora ele está muito acima de qualquer governante, autoridade, poder, líder ou qualquer outro nome não apenas neste mundo, mas também no futuro.

[[v49-1-22]]

^<<v49-1-22,22>>^ Deus submeteu todas as coisas à autoridade de Cristo e o fez cabeça de tudo, para o bem da igreja.

[[v49-1-23]]

^<<v49-1-23,23>>^ E a igreja é seu corpo; ela é preenchida e completada por Cristo, que enche consigo mesmo todas as coisas em toda parte.

'''

xref:048-galatas/048-galatas-006.adoc#v48-6-0[&#60; Capítulo Anterior] | <<v49-1-0,Topo>> | xref:049-efesios/049-efesios-002.adoc#v49-2-0[Próximo Capítulo &#62;]