include::./index.adoc[]

[[v49-3-0]]
=== Efésios, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v49-3-1]]

^<<v49-3-1,1>>^ Quando penso em tudo isso, eu, Paulo, prisioneiro de Cristo Jesus para o bem de vocês, gentios…

[[v49-3-2]]

^<<v49-3-2,2>>^ Tomando por certo, a propósito, que vocês sabem que Deus me deu essa responsabilidade especial de estender sua graça a vocês.

[[v49-3-3]]

^<<v49-3-3,3>>^ Como lhes escrevi anteriormente em poucas palavras, o próprio Deus revelou esse segredo a mim.

[[v49-3-4]]

^<<v49-3-4,4>>^ Ao lerem o que escrevi, entenderão minha compreensão desse segredo a respeito de Cristo,

[[v49-3-5]]

^<<v49-3-5,5>>^ que não foi revelado às gerações anteriores, mas agora foi revelado, pelo Espírito, aos santos apóstolos e profetas.

[[v49-3-6]]

^<<v49-3-6,6>>^ E este é o segredo revelado: tanto os gentios como os judeus que creem nas boas-novas participam igualmente das riquezas herdadas pelos filhos de Deus. Ambos são membros do mesmo corpo e desfrutam a promessa em Cristo Jesus.

[[v49-3-7]]

^<<v49-3-7,7>>^ Pela graça e pelo grande poder de Deus, recebi o privilégio de servir anunciando essas boas-novas.

[[v49-3-8]]

^<<v49-3-8,8>>^ Ainda que eu seja o menos digno de todo o povo santo, recebi, pela graça, o privilégio de falar aos gentios sobre os tesouros infindáveis que estão disponíveis a eles em Cristo

[[v49-3-9]]

^<<v49-3-9,9>>^ e de explicar a todos esse segredo que Deus, o Criador de todas as coisas, manteve oculto desde o princípio.

[[v49-3-10]]

^<<v49-3-10,10>>^ O plano de Deus era mostrar a todos os governantes e autoridades nos domínios celestiais, por meio da igreja, as muitas formas da sabedoria divina.

[[v49-3-11]]

^<<v49-3-11,11>>^ Esse era seu propósito eterno, que ele realizou por meio de Cristo Jesus, nosso Senhor.

[[v49-3-12]]

^<<v49-3-12,12>>^ Por meio da fé em Cristo, agora nós, com ousadia e confiança, temos acesso à presença de Deus.

[[v49-3-13]]

^<<v49-3-13,13>>^ Portanto, peço-lhes que não desanimem por causa de minhas provações. É por vocês que sofro; a honra é de vocês.

[[v49-3-14]]

^<<v49-3-14,14>>^ Quando penso em tudo isso, caio de joelhos e oro ao Pai,

[[v49-3-15]]

^<<v49-3-15,15>>^ o Criador de todas as coisas nos céus e na terra.

[[v49-3-16]]

^<<v49-3-16,16>>^ Peço que, da riqueza de sua glória, ele os fortaleça com poder interior por meio de seu Espírito.

[[v49-3-17]]

^<<v49-3-17,17>>^ Então Cristo habitará em seu coração à medida que vocês confiarem nele. Suas raízes se aprofundarão em amor e os manterão fortes.

[[v49-3-18]]

^<<v49-3-18,18>>^ Também peço que, como convém a todo o povo santo, vocês possam compreender a largura, o comprimento, a altura e a profundidade do amor de Cristo.

[[v49-3-19]]

^<<v49-3-19,19>>^ Que vocês experimentem esse amor, ainda que seja grande demais para ser inteiramente compreendido. Então vocês serão preenchidos com toda a plenitude de vida e poder que vêm de Deus.

[[v49-3-20]]

^<<v49-3-20,20>>^ Toda a glória seja a Deus que, por seu grandioso poder que atua em nós, é capaz de realizar infinitamente mais do que poderíamos pedir ou imaginar.

[[v49-3-21]]

^<<v49-3-21,21>>^ A ele seja a glória na igreja e em Cristo Jesus por todas as gerações, para todo o sempre! Amém.

'''

xref:049-efesios/049-efesios-002.adoc#v49-2-0[&#60; Capítulo Anterior] | <<v49-3-0,Topo>> | xref:049-efesios/049-efesios-004.adoc#v49-4-0[Próximo Capítulo &#62;]