include::./index.adoc[]

[[v49-5-0]]
=== Efésios, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v49-5-1]]

^<<v49-5-1,1>>^ Portanto, como filhos amados de Deus, imitem-no em tudo que fizerem.

[[v49-5-2]]

^<<v49-5-2,2>>^ Vivam em amor, seguindo o exemplo de Cristo, que nos amou e se entregou por nós como oferta e sacrifício de aroma agradável a Deus.

[[v49-5-3]]

^<<v49-5-3,3>>^ Que não haja entre vocês imoralidade sexual, impureza ou ganância. Esses pecados não têm lugar no meio do povo santo.

[[v49-5-4]]

^<<v49-5-4,4>>^ As histórias obscenas, as conversas tolas e as piadas vulgares não são para vocês. Em vez disso, sejam agradecidos a Deus.

[[v49-5-5]]

^<<v49-5-5,5>>^ Podem estar certos de que nenhum imoral, impuro ou ganancioso, que é idólatra, herdará o reino de Cristo e de Deus.

[[v49-5-6]]

^<<v49-5-6,6>>^ Não se deixem enganar por palavras vazias, pois a ira de Deus virá sobre os que lhe desobedecerem.

[[v49-5-7]]

^<<v49-5-7,7>>^ Não participem do que essas pessoas fazem.

[[v49-5-8]]

^<<v49-5-8,8>>^ Pois antigamente vocês estavam mergulhados na escuridão, mas agora têm a luz no Senhor. Vivam, portanto, como filhos da luz!

[[v49-5-9]]

^<<v49-5-9,9>>^ Pois o fruto da luz produz apenas o que é bom, justo e verdadeiro.

[[v49-5-10]]

^<<v49-5-10,10>>^ Procurem descobrir o que agrada ao Senhor.

[[v49-5-11]]

^<<v49-5-11,11>>^ Não participem dos feitos inúteis do mal e da escuridão; antes, mostrem sua reprovação expondo-os à luz.

[[v49-5-12]]

^<<v49-5-12,12>>^ É vergonhoso até mesmo falar daquilo que os maus fazem em segredo.

[[v49-5-13]]

^<<v49-5-13,13>>^ Suas más intenções, porém, ficarão evidentes quando a luz brilhar sobre elas,

[[v49-5-14]]

^<<v49-5-14,14>>^ pois a luz torna visíveis todas as coisas. Por isso se diz: "Desperte, você que dorme, levante-se dentre os mortos, e Cristo o iluminará".

[[v49-5-15]]

^<<v49-5-15,15>>^ Portanto, sejam cuidadosos em seu modo de vida. Não vivam como insensatos, mas como sábios.

[[v49-5-16]]

^<<v49-5-16,16>>^ Aproveitem ao máximo todas as oportunidades nestes dias maus.

[[v49-5-17]]

^<<v49-5-17,17>>^ Não ajam de forma impensada, mas procurem entender a vontade do Senhor.

[[v49-5-18]]

^<<v49-5-18,18>>^ Não se embriaguem com vinho, pois ele os levará ao descontrole. Em vez disso, sejam cheios do Espírito,

[[v49-5-19]]

^<<v49-5-19,19>>^ cantando salmos, hinos e cânticos espirituais entre si e louvando o Senhor de coração com música.

[[v49-5-20]]

^<<v49-5-20,20>>^ Por tudo deem graças a Deus, o Pai, em nome de nosso Senhor Jesus Cristo.

[[v49-5-21]]

^<<v49-5-21,21>>^ Sujeitem-se uns aos outros por temor a Cristo.

[[v49-5-22]]

^<<v49-5-22,22>>^ Esposas, sujeite-se cada uma a seu marido, como ao Senhor.

[[v49-5-23]]

^<<v49-5-23,23>>^ Pois o marido é o cabeça da esposa, como Cristo é o cabeça da igreja. Ele é o Salvador de seu corpo, a igreja.

[[v49-5-24]]

^<<v49-5-24,24>>^ Assim como a igreja se sujeita a Cristo, também vocês, esposas, devem se sujeitar em tudo a seu marido.

[[v49-5-25]]

^<<v49-5-25,25>>^ Maridos, ame cada um a sua esposa, como Cristo amou a igreja. Ele entregou a vida por ela,

[[v49-5-26]]

^<<v49-5-26,26>>^ a fim de torná-la santa, purificando-a ao lavá-la com água por meio da palavra.

[[v49-5-27]]

^<<v49-5-27,27>>^ Assim o fez para apresentá-la a si mesmo como igreja gloriosa, sem mancha, ruga ou qualquer outro defeito, mas santa e sem culpa.

[[v49-5-28]]

^<<v49-5-28,28>>^ Da mesma forma, os maridos devem amar cada um a sua esposa, como amam o próprio corpo, pois o homem que ama sua esposa na verdade ama a si mesmo.

[[v49-5-29]]

^<<v49-5-29,29>>^ Ninguém odeia o próprio corpo, mas o alimenta e cuida dele, como Cristo cuida da igreja.

[[v49-5-30]]

^<<v49-5-30,30>>^ E nós somos membros de seu corpo.

[[v49-5-31]]

^<<v49-5-31,31>>^ "Por isso o homem deixa pai e mãe e se une à sua mulher, e os dois se tornam um só."

[[v49-5-32]]

^<<v49-5-32,32>>^ Esse é um grande mistério, mas ilustra a união entre Cristo e a igreja.

[[v49-5-33]]

^<<v49-5-33,33>>^ Portanto, volto a dizer: cada homem deve amar a esposa como ama a si mesmo, e a esposa deve respeitar o marido.

'''

xref:049-efesios/049-efesios-004.adoc#v49-4-0[&#60; Capítulo Anterior] | <<v49-5-0,Topo>> | xref:049-efesios/049-efesios-006.adoc#v49-6-0[Próximo Capítulo &#62;]