include::./index.adoc[]

[[v37-2-0]]
=== Ageu, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v37-2-1]]

^<<v37-2-1,1>>^ Então, em 17 de outubro desse mesmo ano, o SENHOR transmitiu outra mensagem por meio do profeta Ageu:

[[v37-2-2]]

^<<v37-2-2,2>>^ "Diga ao governador de Judá, Zorobabel, filho de Sealtiel, e ao sumo sacerdote Josué, filho de Jeozadaque, e ao remanescente do povo:

[[v37-2-3]]

^<<v37-2-3,3>>^ ‘Algum de vocês se lembra deste templo em sua antiga glória? Como ele lhes parece agora, em comparação com o anterior? Deve parecer insignificante!

[[v37-2-4]]

^<<v37-2-4,4>>^ Mas assim diz o SENHOR: Seja forte, Zorobabel! Seja forte, sumo sacerdote Josué, filho de Jeozadaque! Sejam fortes, todos vocês que restam na terra! Mãos à obra, pois eu estou com vocês, diz o SENHOR dos Exércitos.

[[v37-2-5]]

^<<v37-2-5,5>>^ Meu Espírito habita em seu meio, como prometi quando vocês saíram do Egito. Portanto, não tenham medo’.

[[v37-2-6]]

^<<v37-2-6,6>>^ "Pois assim diz o SENHOR dos Exércitos: Em pouco tempo sacudirei novamente os céus e a terra, os mares e a terra seca.

[[v37-2-7]]

^<<v37-2-7,7>>^ Sacudirei todas as nações, e os tesouros das nações virão para este templo. Encherei este lugar de glória, diz o SENHOR dos Exércitos.

[[v37-2-8]]

^<<v37-2-8,8>>^ A prata e o ouro me pertencem, diz o SENHOR dos Exércitos.

[[v37-2-9]]

^<<v37-2-9,9>>^ A glória deste novo templo será maior que a glória do antigo, diz o SENHOR dos Exércitos, e neste lugar estabelecerei a paz. Eu, o SENHOR dos Exércitos, falei!".

[[v37-2-10]]

^<<v37-2-10,10>>^ Em 18 de dezembro do segundo ano do reinado de Dario, o SENHOR enviou esta mensagem ao profeta Ageu:

[[v37-2-11]]

^<<v37-2-11,11>>^ "Assim diz o SENHOR dos Exércitos. Pergunte aos sacerdotes sobre a lei:

[[v37-2-12]]

^<<v37-2-12,12>>^ ‘Se alguém levar em sua roupa a carne consagrada de um sacrifício, e se, por acaso, a roupa tocar num pão, num ensopado, em vinho, em azeite ou em qualquer outro tipo de alimento, esse alimento também se tornará consagrado?’". "Não", responderam os sacerdotes.

[[v37-2-13]]

^<<v37-2-13,13>>^ Em seguida, Ageu perguntou: "Se alguém se tornar cerimonialmente impuro ao tocar num cadáver e depois tocar num desses alimentos, o alimento ficará contaminado?". "Sim", responderam os sacerdotes.

[[v37-2-14]]

^<<v37-2-14,14>>^ Então Ageu disse: "É o que acontece com este povo e com esta nação, diz o SENHOR. Tudo que fazem e oferecem é contaminado por seu pecado.

[[v37-2-15]]

^<<v37-2-15,15>>^ Vejam o que estava acontecendo com vocês antes de começarem a lançar os alicerces do templo do SENHOR.

[[v37-2-16]]

^<<v37-2-16,16>>^ Quando esperavam uma colheita de vinte medidas, colhiam apenas dez. Quando esperavam tirar cinquenta medidas da prensa de uvas, tiravam apenas vinte.

[[v37-2-17]]

^<<v37-2-17,17>>^ Enviei ferrugem, mofo e granizo para destruir tudo que vocês trabalharam para produzir. E, no entanto, vocês não voltaram para mim, diz o SENHOR.

[[v37-2-18]]

^<<v37-2-18,18>>^ "Pensem neste 18 de dezembro, o dia em que foram lançados os alicerces do templo do SENHOR. Sim, pensem bem.

[[v37-2-19]]

^<<v37-2-19,19>>^ Eu lhes faço uma promessa agora, enquanto a semente ainda está no celeiro e suas videiras, figueiras, romãzeiras e oliveiras ainda não deram frutos. Mas, de hoje em diante, eu os abençoarei".

[[v37-2-20]]

^<<v37-2-20,20>>^ Naquele mesmo dia, 18 de dezembro, o SENHOR enviou mais uma mensagem a Ageu:

[[v37-2-21]]

^<<v37-2-21,21>>^ "Diga ao governador de Judá, Zorobabel, que estou prestes a sacudir os céus e a terra.

[[v37-2-22]]

^<<v37-2-22,22>>^ Derrubarei tronos e destruirei o poder de reinos estrangeiros. Derrubarei os carros de guerra e seus condutores; os cavalos cairão, e seus cavaleiros matarão uns aos outros.

[[v37-2-23]]

^<<v37-2-23,23>>^ "Naquele dia, diz o SENHOR dos Exércitos, honrarei você, meu servo Zorobabel, filho de Sealtiel. Farei que você seja como um anel de selar em meu dedo, diz o SENHOR, pois eu o escolhi. Eu, o SENHOR dos Exércitos, falei!".

'''

xref:037-ageu/037-ageu-001.adoc#v37-1-0[&#60; Capítulo Anterior] | <<v37-2-0,Topo>> | xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[Próximo Capítulo &#62;]