include::./index.adoc[]

[[v37-1-0]]
=== Ageu, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v37-1-1]]

^<<v37-1-1,1>>^ Em 29 de agosto do segundo ano do reinado de Dario, o SENHOR transmitiu esta mensagem por meio do profeta Ageu ao governador de Judá, Zorobabel, filho de Sealtiel, e ao sumo sacerdote Josué, filho de Jeozadaque.

[[v37-1-2]]

^<<v37-1-2,2>>^ "Assim diz o SENHOR dos Exércitos: Este povo diz: ‘Ainda não chegou a hora de reconstruir a casa do SENHOR’".

[[v37-1-3]]

^<<v37-1-3,3>>^ Então o SENHOR enviou esta mensagem por meio do profeta Ageu:

[[v37-1-4]]

^<<v37-1-4,4>>^ "Por que vocês vivem em casas luxuosas enquanto minha casa continua em ruínas?

[[v37-1-5]]

^<<v37-1-5,5>>^ Assim diz o SENHOR dos Exércitos: Vejam o que tem acontecido com vocês!

[[v37-1-6]]

^<<v37-1-6,6>>^ Plantam muito, mas colhem pouco. Comem, mas não se saciam. Bebem, mas ainda têm sede. Vestem-se, mas não se aquecem. Seus salários desaparecem como se vocês os colocassem em bolsos furados.

[[v37-1-7]]

^<<v37-1-7,7>>^ "Assim diz o SENHOR dos Exércitos: Vejam o que tem acontecido com vocês!

[[v37-1-8]]

^<<v37-1-8,8>>^ Agora, subam as colinas, tragam madeira e reconstruam minha casa. Então me alegrarei nela e serei honrado, diz o SENHOR.

[[v37-1-9]]

^<<v37-1-9,9>>^ Vocês esperavam colheitas fartas, mas elas foram escassas. E, quando trouxeram esse pouco para casa, eu o fiz desaparecer com um sopro. Por quê? Porque minha casa continua em ruínas, diz o SENHOR dos Exércitos, enquanto vocês estão ocupados construindo suas casas.

[[v37-1-10]]

^<<v37-1-10,10>>^ É por causa de vocês que os céus retêm o orvalho e a terra não produz colheitas.

[[v37-1-11]]

^<<v37-1-11,11>>^ Enviei uma seca sobre seus campos e sobre as colinas, uma seca que fará murchar o trigo, as uvas, as azeitonas e todas as suas plantações, que fará vocês e seus animais passarem fome e destruirá tudo que vocês trabalharam para conseguir".

[[v37-1-12]]

^<<v37-1-12,12>>^ Então Zorobabel, filho de Sealtiel, e o sumo sacerdote Josué, filho de Jeozadaque, e todo o remanescente do povo obedeceram à mensagem do SENHOR, seu Deus. Quando o povo ouviu as palavras do profeta Ageu, que o SENHOR, seu Deus, tinha enviado, temeu o SENHOR.

[[v37-1-13]]

^<<v37-1-13,13>>^ Então Ageu, o mensageiro do SENHOR, transmitiu ao povo esta mensagem do SENHOR: "Estou com vocês, diz o SENHOR!".

[[v37-1-14]]

^<<v37-1-14,14>>^ E o SENHOR deu ânimo ao governador de Judá, Zorobabel, filho de Sealtiel, ao sumo sacerdote Josué, filho de Jeozadaque, e a todo o remanescente do povo. Começaram a trabalhar na casa de seu Deus, o SENHOR dos Exércitos,

[[v37-1-15]]

^<<v37-1-15,15>>^ em 21 de setembro do segundo ano do reinado de Dario.

'''

xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[&#60; Capítulo Anterior] | <<v37-1-0,Topo>> | xref:037-ageu/037-ageu-002.adoc#v37-2-0[Próximo Capítulo &#62;]