include::./index.adoc[]

[[v60-2-0]]
=== 1 Pedro, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v60-2-1]]

^<<v60-2-1,1>>^ Portanto, livrem-se de toda maldade, todo engano, toda hipocrisia, toda inveja e todo tipo de difamação.

[[v60-2-2]]

^<<v60-2-2,2>>^ Como bebês recém-nascidos, desejem intensamente o puro leite espiritual, para que, por meio dele, cresçam e experimentem plenamente a salvação,

[[v60-2-3]]

^<<v60-2-3,3>>^ agora que provaram da bondade do Senhor.

[[v60-2-4]]

^<<v60-2-4,4>>^ Vocês têm se aproximado de Cristo, a pedra viva. As pessoas o rejeitaram, mas Deus o escolheu para lhe conceder grande honra.

[[v60-2-5]]

^<<v60-2-5,5>>^ E vocês também são pedras vivas, com as quais um templo espiritual é edificado. Além disso, são sacerdotes santos. Por meio de Jesus Cristo, oferecem sacrifícios espirituais que agradam a Deus.

[[v60-2-6]]

^<<v60-2-6,6>>^ Como dizem as Escrituras: "Ponho em Sião uma pedra angular, escolhida para grande honra; quem confiar nela jamais será envergonhado".

[[v60-2-7]]

^<<v60-2-7,7>>^ Sim, vocês, os que creem, reconhecem a honra que lhe é devida. Mas, para os que não creem, "A pedra que os construtores rejeitaram se tornou a pedra angular".

[[v60-2-8]]

^<<v60-2-8,8>>^ E também, "Ele é a pedra de tropeço, rocha que faz as pessoas caírem". Tropeçam porque não obedecem à palavra e, portanto, deparam com o destino planejado para elas.

[[v60-2-9]]

^<<v60-2-9,9>>^ Vocês, porém, são povo escolhido, reino de sacerdotes, nação santa, propriedade exclusiva de Deus. Assim, vocês podem mostrar às pessoas como é admirável aquele que os chamou das trevas para sua maravilhosa luz.

[[v60-2-10]]

^<<v60-2-10,10>>^ "Antes vocês não tinham identidade como povo, agora são povo de Deus. Antes não haviam recebido misericórdia, agora receberam misericórdia de Deus."

[[v60-2-11]]

^<<v60-2-11,11>>^ Amados, eu os advirto, como peregrinos e estrangeiros que são, a manter distância dos desejos carnais que lutam contra a alma.

[[v60-2-12]]

^<<v60-2-12,12>>^ Procurem viver de maneira exemplar entre os que não creem. Assim, mesmo que eles os acusem de praticar o mal, verão seu comportamento correto e darão glória a Deus quando ele julgar o mundo.

[[v60-2-13]]

^<<v60-2-13,13>>^ Por causa do Senhor, submetam-se a todas as autoridades humanas, seja o rei como autoridade máxima,

[[v60-2-14]]

^<<v60-2-14,14>>^ sejam os oficiais nomeados e enviados por ele para castigar os que fazem o mal e honrar os que fazem o bem.

[[v60-2-15]]

^<<v60-2-15,15>>^ É da vontade de Deus que, pela prática do bem, vocês calem os ignorantes que os acusam falsamente.

[[v60-2-16]]

^<<v60-2-16,16>>^ Pois vocês são livres e, no entanto, são escravos de Deus; não usem sua liberdade como desculpa para fazer o mal.

[[v60-2-17]]

^<<v60-2-17,17>>^ Tratem todos com respeito e amem seus irmãos em Cristo. Temam a Deus e respeitem o rei.

[[v60-2-18]]

^<<v60-2-18,18>>^ Vocês, escravos, submetam-se a seu senhor com todo o respeito. Façam o que ele mandar, não apenas se for bondoso e amável, mas até mesmo se for cruel.

[[v60-2-19]]

^<<v60-2-19,19>>^ Porque Deus se agrada de vocês quando, conscientes da vontade dele, suportam com paciência o tratamento injusto.

[[v60-2-20]]

^<<v60-2-20,20>>^ Claro que não há mérito algum em ser paciente quando são açoitados por terem feito o mal. Mas, se sofrem por terem feito o bem e suportam com paciência, Deus se agrada de vocês.

[[v60-2-21]]

^<<v60-2-21,21>>^ Porque Deus os chamou para fazerem o bem, mesmo que isso resulte em sofrimento, pois Cristo sofreu por vocês. Ele é seu exemplo; sigam seus passos.

[[v60-2-22]]

^<<v60-2-22,22>>^ Ele nunca pecou, nem enganou ninguém.

[[v60-2-23]]

^<<v60-2-23,23>>^ Não revidou quando foi insultado, nem ameaçou se vingar quando sofreu, mas deixou seu caso nas mãos de Deus, que sempre julga com justiça.

[[v60-2-24]]

^<<v60-2-24,24>>^ Ele mesmo carregou nossos pecados em seu corpo na cruz, a fim de que morrêssemos para o pecado e vivêssemos para a justiça; por suas feridas somos curados.

[[v60-2-25]]

^<<v60-2-25,25>>^ Vocês eram como ovelhas desgarradas, mas agora voltaram para o Pastor, o Guardião de sua alma.

'''

xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[Próximo Capítulo &#62;]