include::./index.adoc[]

[[v60-3-0]]
=== 1 Pedro, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v60-3-1]]

^<<v60-3-1,1>>^ Da mesma forma, vocês, esposas, sujeitem-se à autoridade de seu marido. Assim, mesmo que ele se recuse a obedecer à palavra, será conquistado por sua conduta, sem palavra alguma,

[[v60-3-2]]

^<<v60-3-2,2>>^ mas por observar seu modo de viver puro e reverente.

[[v60-3-3]]

^<<v60-3-3,3>>^ Não se preocupem com a beleza exterior obtida com penteados extravagantes, joias caras e roupas bonitas.

[[v60-3-4]]

^<<v60-3-4,4>>^ Em vez disso, vistam-se com a beleza que vem de dentro e que não desaparece, a beleza de um espírito amável e sereno, tão precioso para Deus.

[[v60-3-5]]

^<<v60-3-5,5>>^ Era assim que se adornavam as mulheres santas do passado. Elas depositavam sua confiança em Deus e se sujeitavam à autoridade do marido.

[[v60-3-6]]

^<<v60-3-6,6>>^ Sara, por exemplo, obedecia a Abraão e o chamava de senhor. Vocês são filhas dela quando praticam o bem, sem medo algum.

[[v60-3-7]]

^<<v60-3-7,7>>^ Da mesma forma, vocês, maridos, honrem sua esposa. Sejam compreensivos no convívio com ela, pois, ainda que seja mais frágil que vocês, ela é igualmente participante da dádiva de nova vida concedida por Deus. Tratem-na de maneira correta, para que nada atrapalhe suas orações.

[[v60-3-8]]

^<<v60-3-8,8>>^ Por fim, tenham todos o mesmo modo de pensar. Sejam cheios de compaixão uns pelos outros. Amem uns aos outros como irmãos. Mostrem misericórdia e humildade.

[[v60-3-9]]

^<<v60-3-9,9>>^ Não retribuam mal por mal, nem insulto com insulto. Ao contrário, retribuam com uma bênção. Foi para isso que vocês foram chamados, e a bênção lhes será concedida.

[[v60-3-10]]

^<<v60-3-10,10>>^ Pois, "Se quiser desfrutar a vida e ver muitos dias felizes, refreie a língua de falar maldades e os lábios de dizerem mentiras.

[[v60-3-11]]

^<<v60-3-11,11>>^ Afaste-se do mal e faça o bem; busque a paz e esforce-se para mantê-la.

[[v60-3-12]]

^<<v60-3-12,12>>^ Os olhos do Senhor estão sobre os justos, e seus ouvidos, abertos para suas orações. O Senhor, porém, volta o rosto contra os que praticam o mal".

[[v60-3-13]]

^<<v60-3-13,13>>^ Quem é que desejará lhes fazer mal se vocês se dedicarem a fazer o bem?

[[v60-3-14]]

^<<v60-3-14,14>>^ Mas, ainda que sofram por fazer o que é certo, vocês serão abençoados. Portanto, não se preocupem e não tenham medo de ameaças.

[[v60-3-15]]

^<<v60-3-15,15>>^ Em vez disso, consagrem a Cristo como o Senhor de sua vida. E, se alguém lhes perguntar a respeito de sua esperança, estejam sempre preparados para explicá-la.

[[v60-3-16]]

^<<v60-3-16,16>>^ Façam-no, porém, de modo amável e respeitoso. Mantenham sempre a consciência limpa. Então, se as pessoas falarem mal de vocês, ficarão envergonhadas ao ver como vocês vivem corretamente em Cristo.

[[v60-3-17]]

^<<v60-3-17,17>>^ Lembrem-se de que é melhor sofrer por fazer o bem, se for da vontade de Deus, do que por fazer o mal.

[[v60-3-18]]

^<<v60-3-18,18>>^ Pois Cristo também sofreu por nossos pecados, de uma vez por todas. Embora nunca tenha pecado, morreu pelos pecadores a fim de conduzi-los a Deus. Sofreu morte física, mas foi ressuscitado pelo Espírito,

[[v60-3-19]]

^<<v60-3-19,19>>^ por meio do qual pregou aos espíritos em prisão,

[[v60-3-20]]

^<<v60-3-20,20>>^ àqueles que, muito tempo atrás, desobedeceram a Deus quando ele esperou pacientemente enquanto Noé construía sua embarcação. Apenas oito pessoas foram salvas por meio da água do dilúvio,

[[v60-3-21]]

^<<v60-3-21,21>>^ e aquela água simboliza o batismo que agora os salva, não pela remoção da sujeira do corpo, mas porque no batismo vocês declaram ter boa consciência diante de Deus. Ela é eficaz por meio da ressurreição de Jesus Cristo.

[[v60-3-22]]

^<<v60-3-22,22>>^ Agora, Cristo foi para o céu e está sentado no lugar de honra à direita de Deus, e todos os anjos, autoridades e poderes se sujeitam a ele.

'''

xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[&#60; Capítulo Anterior] | <<v60-3-0,Topo>> | xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[Próximo Capítulo &#62;]