include::./index.adoc[]

[[v60-1-0]]
=== 1 Pedro, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v60-1-1]]

^<<v60-1-1,1>>^ Eu, Pedro, apóstolo de Jesus Cristo, escrevo esta carta aos escolhidos que vivem como estrangeiros nas províncias de Ponto, Galácia, Capadócia, Ásia e Bitínia.

[[v60-1-2]]

^<<v60-1-2,2>>^ Deus, o Pai, os conhecia de antemão e os escolheu, e o Espírito os santificou para a obediência e a purificação pelo sangue de Jesus Cristo. Que vocês tenham cada vez mais graça e paz.

[[v60-1-3]]

^<<v60-1-3,3>>^ Todo louvor seja a Deus, o Pai de nosso Senhor Jesus Cristo. Por sua grande misericórdia, ele nos fez nascer de novo, por meio da ressurreição de Jesus Cristo dentre os mortos. Agora temos uma viva esperança

[[v60-1-4]]

^<<v60-1-4,4>>^ e uma herança imperecível, pura e imaculada, que não muda nem se deteriora, guardada para vocês no céu.

[[v60-1-5]]

^<<v60-1-5,5>>^ Por meio da fé que vocês têm, Deus os protege com seu poder até que recebam essa salvação, pronta para ser revelada nos últimos tempos.

[[v60-1-6]]

^<<v60-1-6,6>>^ Portanto, alegrem-se com isso, ainda que agora, por algum tempo, vocês precisem suportar muitas provações.

[[v60-1-7]]

^<<v60-1-7,7>>^ Elas mostrarão que sua fé é autêntica. Como o fogo prova e purifica o ouro, assim sua fé está sendo experimentada, e ela é muito mais preciosa que o simples ouro. Isso resultará em louvor, glória e honra no dia em que Jesus Cristo for revelado.

[[v60-1-8]]

^<<v60-1-8,8>>^ Embora nunca o tenham visto, vocês o amam. E, ainda que não o vejam agora, creem nele e se regozijam com alegria inexprimível e gloriosa,

[[v60-1-9]]

^<<v60-1-9,9>>^ pois estão alcançando o alvo de sua fé, a sua salvação.

[[v60-1-10]]

^<<v60-1-10,10>>^ Até mesmo os profetas queriam saber mais sobre essa salvação e investigaram a respeito, quando profetizaram acerca da graça preparada para vocês.

[[v60-1-11]]

^<<v60-1-11,11>>^ Buscavam descobrir a que tempo ou ocasião se referia o Espírito de Cristo, que neles estava, ao predizer o sofrimento de Cristo e sua grande glória posterior.

[[v60-1-12]]

^<<v60-1-12,12>>^ Foi-lhes dito que suas mensagens não eram para eles, mas para vocês. E, agora, essas boas-novas lhes foram anunciadas por aqueles que pregaram pelo poder do Espírito Santo enviado do céu. É algo tão maravilhoso que até os anjos anseiam observar.

[[v60-1-13]]

^<<v60-1-13,13>>^ Portanto, preparem sua mente para a ação e exercitem o autocontrole. Depositem toda a sua esperança na graça que receberão quando Jesus Cristo for revelado.

[[v60-1-14]]

^<<v60-1-14,14>>^ Sejam filhos obedientes. Não voltem ao seu antigo modo de viver, quando satisfaziam os próprios desejos e viviam na ignorância.

[[v60-1-15]]

^<<v60-1-15,15>>^ Agora, porém, sejam santos em tudo que fizerem, como é santo aquele que os chamou.

[[v60-1-16]]

^<<v60-1-16,16>>^ Pois as Escrituras dizem: "Sejam santos, porque eu sou santo".

[[v60-1-17]]

^<<v60-1-17,17>>^ Lembrem-se de que o Pai celestial, a quem vocês oram, não mostra favorecimento. Ele os julgará de acordo com suas ações. Por isso, vivam com temor durante seu tempo como residentes na terra.

[[v60-1-18]]

^<<v60-1-18,18>>^ Pois vocês sabem que o resgate para salvá-los do estilo de vida vazio que herdaram de seus antepassados não foi pago com simples ouro ou prata, que perdem seu valor,

[[v60-1-19]]

^<<v60-1-19,19>>^ mas com o sangue precioso de Cristo, o Cordeiro de Deus, sem pecado nem mancha.

[[v60-1-20]]

^<<v60-1-20,20>>^ Ele foi escolhido antes da criação do mundo, mas agora, nestes últimos tempos, foi revelado por causa de vocês.

[[v60-1-21]]

^<<v60-1-21,21>>^ Por meio de Cristo, vocês vieram a crer em Deus. Depositam sua fé e esperança em Deus porque ele ressuscitou Cristo dos mortos e lhe deu grande glória.

[[v60-1-22]]

^<<v60-1-22,22>>^ Uma vez que vocês foram purificados de seus pecados quando obedeceram à verdade, tenham como alvo agora o amor fraternal sem fingimento. Amem uns aos outros sinceramente, de todo o coração.

[[v60-1-23]]

^<<v60-1-23,23>>^ Pois vocês nasceram de novo, não para uma vida que pode ser destruída, mas para uma vida que durará para sempre, porque vem da eterna e viva palavra de Deus.

[[v60-1-24]]

^<<v60-1-24,24>>^ Pois, "Os seres humanos são como o capim; sua beleza é como as flores do campo. O capim seca e as flores murcham,

[[v60-1-25]]

^<<v60-1-25,25>>^ mas a palavra do Senhor permanece para sempre". E essa palavra é a mensagem das boas-novas que lhes foi anunciada.

'''

xref:059-tiago/059-tiago-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[Próximo Capítulo &#62;]