include::./index.adoc[]

[[v60-4-0]]
=== 1 Pedro, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v60-4-1]]

^<<v60-4-1,1>>^ Portanto, uma vez que Cristo sofreu fisicamente, armem-se com a mesma atitude que ele teve e estejam prontos para também sofrer. Porque, se vocês sofreram fisicamente por Cristo, deixaram o pecado para trás.

[[v60-4-2]]

^<<v60-4-2,2>>^ Não passarão o resto da vida buscando os próprios desejos, mas fazendo a vontade de Deus.

[[v60-4-3]]

^<<v60-4-3,3>>^ No passado, vocês desperdiçaram muito tempo praticando o que gostam de fazer aqueles que não creem: imoralidade e desejos carnais, farras, bebedeiras e festanças desregradas, além da detestável adoração de ídolos.

[[v60-4-4]]

^<<v60-4-4,4>>^ Agora, essas pessoas ficam surpresas quando vocês deixam de participar de suas práticas desregradas e destrutivas e, por isso, os difamam.

[[v60-4-5]]

^<<v60-4-5,5>>^ Lembrem-se, porém, de que eles terão de prestar contas àquele que está pronto para julgar a todos, vivos e mortos.

[[v60-4-6]]

^<<v60-4-6,6>>^ Por isso as boas-novas foram anunciadas até mesmo aos mortos, pois, embora estivessem destinados a morrer como todo ser humano, agora vivem para sempre com Deus pelo Espírito.

[[v60-4-7]]

^<<v60-4-7,7>>^ O fim de todas as coisas está próximo. Portanto, sejam sensatos e disciplinados em suas orações.

[[v60-4-8]]

^<<v60-4-8,8>>^ Acima de tudo, amem uns aos outros sinceramente, pois o amor cobre muitos pecados.

[[v60-4-9]]

^<<v60-4-9,9>>^ Abram sua casa de bom grado para os que necessitam de um lugar para se hospedar.

[[v60-4-10]]

^<<v60-4-10,10>>^ Deus concedeu um dom a cada um, e vocês devem usá-lo para servir uns aos outros, fazendo bom uso da múltipla e variada graça divina.

[[v60-4-11]]

^<<v60-4-11,11>>^ Você tem o dom de falar? Então faça-o de acordo com as palavras de Deus. Tem o dom de ajudar? Faça-o com a força que Deus lhe dá. Assim, tudo que você realizar trará glória a Deus por meio de Jesus Cristo. A ele sejam a glória e o poder para todo o sempre! Amém.

[[v60-4-12]]

^<<v60-4-12,12>>^ Amados, não se surpreendam com as provações de fogo ardente pelas quais estão passando, como se algo estranho lhes estivesse acontecendo.

[[v60-4-13]]

^<<v60-4-13,13>>^ Pelo contrário, alegrem-se muito, pois essas provações os tornam participantes dos sofrimentos de Cristo, a fim de que tenham a maravilhosa alegria de ver sua glória quando ela for revelada.

[[v60-4-14]]

^<<v60-4-14,14>>^ Se vocês forem insultados por causa do nome de Cristo, abençoados serão, pois o glorioso Espírito de Deus repousa sobre vocês.

[[v60-4-15]]

^<<v60-4-15,15>>^ Se sofrerem, porém, que não seja por matar, roubar, causar confusão ou intrometer-se em assuntos alheios.

[[v60-4-16]]

^<<v60-4-16,16>>^ Mas, se sofrerem por ser cristãos, não se envergonhem; louvem a Deus por serem chamados por esse nome!

[[v60-4-17]]

^<<v60-4-17,17>>^ Pois chegou a hora do julgamento, que deve começar pela casa de Deus. E, se o julgamento começa conosco, que destino terrível aguarda aqueles que nunca obedeceram às boas-novas de Deus!

[[v60-4-18]]

^<<v60-4-18,18>>^ E, "Se o justo é salvo por um triz, o que será do pecador perverso?".

[[v60-4-19]]

^<<v60-4-19,19>>^ Portanto, se vocês sofrem porque cumprem a vontade de Deus, continuem a fazer o que é certo e confiem sua vida àquele que os criou, pois ele é fiel.

'''

xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[&#60; Capítulo Anterior] | <<v60-4-0,Topo>> | xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[Próximo Capítulo &#62;]