include::./index.adoc[]

[[v60-5-0]]
=== 1 Pedro, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v60-5-1]]

^<<v60-5-1,1>>^ E agora, uma palavra aos presbíteros em seu meio. Eu, que também sou presbítero, testemunhei os sofrimentos de Cristo e também participarei de sua glória quando ela for revelada. Assim, peço-lhes

[[v60-5-2]]

^<<v60-5-2,2>>^ que cuidem do rebanho que Deus lhes confiou com disposição, e não de má vontade; não pelo que lucrarão com isso, mas pelo desejo de servir a Deus.

[[v60-5-3]]

^<<v60-5-3,3>>^ Não abusem de sua autoridade com aqueles que foram colocados sob seus cuidados, mas guiem-nos com seu bom exemplo.

[[v60-5-4]]

^<<v60-5-4,4>>^ E, quando vier o Grande Pastor, vocês receberão uma coroa de glória sem fim.

[[v60-5-5]]

^<<v60-5-5,5>>^ Da mesma forma, vocês, que são mais jovens, aceitem a autoridade dos presbíteros. E todos vocês vistam-se de humildade no relacionamento uns com os outros. Pois, "Deus se opõe aos orgulhosos, mas concede graça aos humildes".

[[v60-5-6]]

^<<v60-5-6,6>>^ Portanto, humilhem-se sob o grande poder de Deus e, no tempo certo, ele os exaltará.

[[v60-5-7]]

^<<v60-5-7,7>>^ Entreguem-lhe todas as suas ansiedades, pois ele cuida de vocês.

[[v60-5-8]]

^<<v60-5-8,8>>^ Estejam atentos! Tomem cuidado com seu grande inimigo, o diabo, que anda como um leão rugindo à sua volta, à procura de alguém para devorar.

[[v60-5-9]]

^<<v60-5-9,9>>^ Permaneçam firmes contra ele e sejam fortes na fé. Lembrem-se de que seus irmãos em Cristo em todo o mundo estão passando pelos mesmos sofrimentos.

[[v60-5-10]]

^<<v60-5-10,10>>^ Deus, em toda a sua graça, os chamou para participarem de sua glória eterna por meio de Cristo Jesus. Assim, depois que tiverem sofrido por um pouco de tempo, ele os restaurará, os sustentará e os fortalecerá, e os colocará sobre um firme alicerce.

[[v60-5-11]]

^<<v60-5-11,11>>^ A ele seja o poder para sempre! Amém.

[[v60-5-12]]

^<<v60-5-12,12>>^ Escrevi e enviei esta breve carta com a ajuda de Silas, a quem lhes recomendo como irmão fiel. Meu objetivo ao escrever é encorajá-los e garantir-lhes que as experiências pelas quais vocês têm passado são, verdadeiramente, parte da graça de Deus. Permaneçam firmes nessa graça.

[[v60-5-13]]

^<<v60-5-13,13>>^ Aquela que está na Babilônia, escolhida assim como vocês, lhes envia saudações, e também meu filho Marcos.

[[v60-5-14]]

^<<v60-5-14,14>>^ Cumprimentem uns aos outros com um beijo de amor. Paz seja com todos vocês que estão em Cristo.

'''

xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[&#60; Capítulo Anterior] | <<v60-5-0,Topo>> | xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[Próximo Capítulo &#62;]