include::./index.adoc[]

[[v45-10-0]]
=== Romanos, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v45-10-1]]

^<<v45-10-1,1>>^ Irmãos, o desejo de meu coração e minha oração a Deus é que o povo de Israel seja salvo.

[[v45-10-2]]

^<<v45-10-2,2>>^ Sei da dedicação deles por Deus, mas é entusiasmo sem entendimento.

[[v45-10-3]]

^<<v45-10-3,3>>^ Pois, não entendendo a maneira como Deus declara as pessoas justas diante dele, apegam-se a seu próprio modo de se tornar justos tentando seguir a lei, e recusam a maneira de Deus.

[[v45-10-4]]

^<<v45-10-4,4>>^ Pois Cristo é o propósito para o qual a lei foi dada. Como resultado, todo o que nele crê é declarado justo.

[[v45-10-5]]

^<<v45-10-5,5>>^ Moisés escreve que o modo pelo qual a lei torna alguém justo exige obediência a todos os seus mandamentos.

[[v45-10-6]]

^<<v45-10-6,6>>^ Mas o modo pelo qual a fé torna alguém justo diz: "Não diga em seu coração: ‘Quem subirá ao céu?’ (para trazer Cristo para a terra).

[[v45-10-7]]

^<<v45-10-7,7>>^ E não diga: ‘Quem descerá ao lugar dos mortos?’ (para trazer Cristo de volta à vida)".

[[v45-10-8]]

^<<v45-10-8,8>>^ Na verdade, diz: "A mensagem está bem perto; está em seus lábios e em seu coração". E essa mensagem é a mesma que anunciamos a respeito da fé:

[[v45-10-9]]

^<<v45-10-9,9>>^ se você declarar com sua boca que Jesus é Senhor e crer em seu coração que Deus o ressuscitou dos mortos, será salvo.

[[v45-10-10]]

^<<v45-10-10,10>>^ Pois é crendo de coração que você é declarado justo, e é declarando com a boca que você é salvo.

[[v45-10-11]]

^<<v45-10-11,11>>^ Como dizem as Escrituras: "Quem confiar nele jamais será envergonhado".

[[v45-10-12]]

^<<v45-10-12,12>>^ Nesse sentido, não há diferença entre judeus e gentios, uma vez que ambos têm o mesmo Senhor, que abençoa generosamente todos que o invocam.

[[v45-10-13]]

^<<v45-10-13,13>>^ Pois "todo aquele que invocar o nome do Senhor será salvo".

[[v45-10-14]]

^<<v45-10-14,14>>^ Mas como poderão invocá-lo se não crerem nele? E como crerão nele se jamais tiverem ouvido a seu respeito? E como ouvirão a seu respeito se ninguém lhes falar?

[[v45-10-15]]

^<<v45-10-15,15>>^ E como alguém falará se não for enviado? Por isso as Escrituras dizem: "Como são belos os pés dos mensageiros que trazem boas-novas!".

[[v45-10-16]]

^<<v45-10-16,16>>^ Nem todos, porém, aceitam as boas-novas, pois o profeta Isaías disse: "Senhor, quem creu em nossa mensagem?".

[[v45-10-17]]

^<<v45-10-17,17>>^ Portanto, a fé vem por ouvir, isto é, por ouvir as boas-novas a respeito de Cristo.

[[v45-10-18]]

^<<v45-10-18,18>>^ Mas eu pergunto: o povo de Israel ouviu, de fato, a mensagem? Sim, eles ouviram: "Sua mensagem chegou a toda a terra, e suas palavras alcançaram os confins do mundo".

[[v45-10-19]]

^<<v45-10-19,19>>^ Volto a perguntar: será que o povo de Israel entendeu? Sim, eles entenderam, pois, já no tempo de Moisés, Deus disse: "Provocarei seu ciúme por meio de um povo que nem sequer é nação. Provocarei sua ira por meio de gentios insensatos".

[[v45-10-20]]

^<<v45-10-20,20>>^ E, mais tarde, Isaías se pronunciou com ousadia: "Fui encontrado por aqueles que não me procuravam. Revelei-me àqueles que não perguntavam por mim".

[[v45-10-21]]

^<<v45-10-21,21>>^ A respeito de Israel, porém, diz: "O dia todo abri meus braços para eles, mas foram desobedientes e rebeldes".

'''

xref:045-romanos/045-romanos-009.adoc#v45-9-0[&#60; Capítulo Anterior] | <<v45-10-0,Topo>> | xref:045-romanos/045-romanos-011.adoc#v45-11-0[Próximo Capítulo &#62;]