include::./index.adoc[]

[[v45-13-0]]
=== Romanos, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v45-13-1]]

^<<v45-13-1,1>>^ Todos devem sujeitar-se às autoridades, pois toda autoridade vem de Deus, e aqueles que ocupam cargos de autoridade foram ali colocados por ele.

[[v45-13-2]]

^<<v45-13-2,2>>^ Portanto, quem se rebela contra a autoridade se rebela contra o Deus que a instituiu e será punido.

[[v45-13-3]]

^<<v45-13-3,3>>^ Pois as autoridades não causam temor naqueles que fazem o que é certo, mas sim nos que fazem o que é errado. Você deseja viver livre do medo das autoridades? Faça o que é certo, e elas o honrarão.

[[v45-13-4]]

^<<v45-13-4,4>>^ As autoridades são servos de Deus, para o seu bem. Mas, se você estiver fazendo algo errado, é evidente que deve temer, pois elas têm o poder de puni-lo, pois estão a serviço de Deus para castigar os que praticam o mal.

[[v45-13-5]]

^<<v45-13-5,5>>^ Portanto, sujeitem-se a elas, não apenas para evitar a punição, mas também para manter a consciência limpa.

[[v45-13-6]]

^<<v45-13-6,6>>^ É por esse motivo também que vocês pagam impostos, pois as autoridades estão a serviço de Deus no trabalho que realizam.

[[v45-13-7]]

^<<v45-13-7,7>>^ Deem a cada um o que lhe é devido: paguem os impostos e tributos àqueles que os recolhem e honrem e respeitem as autoridades.

[[v45-13-8]]

^<<v45-13-8,8>>^ Não devam nada a ninguém, a não ser o amor de uns pelos outros. Quem ama seu próximo cumpre os requisitos da lei de Deus.

[[v45-13-9]]

^<<v45-13-9,9>>^ Pois os mandamentos dizem: "Não cometa adultério. Não mate. Não roube. Não cobice". Esses e outros mandamentos semelhantes se resumem num só: "Ame o seu próximo como a si mesmo".

[[v45-13-10]]

^<<v45-13-10,10>>^ O amor não faz o mal ao próximo, portanto o amor cumpre todas as exigências da lei de Deus.

[[v45-13-11]]

^<<v45-13-11,11>>^ Tudo isso é ainda mais urgente porque vocês sabem como é tarde; o tempo está se esgotando. Despertem, pois nossa salvação está mais próxima agora do que quando cremos no início.

[[v45-13-12]]

^<<v45-13-12,12>>^ A noite está quase acabando, e logo vem o dia. Portanto, deixem de lado as obras das trevas como se fossem roupas sujas e vistam a armadura da luz.

[[v45-13-13]]

^<<v45-13-13,13>>^ Uma vez que pertencemos ao dia, vivamos com decência, à vista de todos. Não participem de festanças desregradas, de bebedeiras, de promiscuidade sexual e de práticas imorais, e não se envolvam em brigas nem em invejas.

[[v45-13-14]]

^<<v45-13-14,14>>^ Em vez disso, revistam-se do Senhor Jesus Cristo e não fiquem imaginando formas de satisfazer seus desejos pecaminosos.

'''

xref:045-romanos/045-romanos-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romanos/045-romanos-014.adoc#v45-14-0[Próximo Capítulo &#62;]