include::./index.adoc[]

[[v45-8-0]]
=== Romanos, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v45-8-1]]

^<<v45-8-1,1>>^ Agora, portanto, já não há nenhuma condenação para os que estão em Cristo Jesus.

[[v45-8-2]]

^<<v45-8-2,2>>^ Pois em Cristo Jesus a lei do Espírito que dá vida os libertou da lei do pecado, que leva à morte.

[[v45-8-3]]

^<<v45-8-3,3>>^ A lei não era capaz de nos salvar por causa da fraqueza de nossa natureza humana, por isso Deus fez o que a lei era incapaz de fazer ao enviar seu Filho na semelhança de nossa natureza humana pecaminosa e apresentá-lo como sacrifício por nosso pecado. Com isso, declarou o fim do domínio do pecado sobre nós,

[[v45-8-4]]

^<<v45-8-4,4>>^ de modo que nós, que agora não seguimos mais nossa natureza humana, mas sim o Espírito, possamos cumprir as justas exigências da lei.

[[v45-8-5]]

^<<v45-8-5,5>>^ Aqueles que são dominados pela natureza humana pensam em coisas da natureza humana, mas os que são controlados pelo Espírito pensam em coisas que agradam o Espírito.

[[v45-8-6]]

^<<v45-8-6,6>>^ Portanto, permitir que a natureza humana controle a mente resulta em morte, mas permitir que o Espírito controle a mente resulta em vida e paz.

[[v45-8-7]]

^<<v45-8-7,7>>^ Pois a mentalidade da natureza humana é sempre inimiga de Deus. Nunca obedeceu às leis de Deus, e nunca obedecerá.

[[v45-8-8]]

^<<v45-8-8,8>>^ Por isso aqueles que ainda estão sob o domínio de sua natureza humana não podem agradar a Deus.

[[v45-8-9]]

^<<v45-8-9,9>>^ Vocês, porém, não são controlados pela natureza humana, mas pelo Espírito, se de fato o Espírito de Deus habita em vocês. E, se alguém não tem o Espírito de Cristo, a ele não pertence.

[[v45-8-10]]

^<<v45-8-10,10>>^ Uma vez que Cristo habita em vocês, embora o corpo morra por causa do pecado, o Espírito lhes dá vida porque vocês foram declarados justos diante de Deus.

[[v45-8-11]]

^<<v45-8-11,11>>^ E, se o Espírito de Deus que ressuscitou Jesus dos mortos habita em vocês, o Deus que ressuscitou Cristo Jesus dos mortos dará vida a seu corpo mortal, por meio desse mesmo Espírito que habita em vocês.

[[v45-8-12]]

^<<v45-8-12,12>>^ Portanto, irmãos, vocês não têm de fazer o que sua natureza humana lhes pede,

[[v45-8-13]]

^<<v45-8-13,13>>^ porque, se viverem de acordo com as exigências dela, morrerão. Se, contudo, pelo poder do Espírito, fizerem morrer as obras do corpo, viverão,

[[v45-8-14]]

^<<v45-8-14,14>>^ porque todos que são guiados pelo Espírito de Deus são filhos de Deus.

[[v45-8-15]]

^<<v45-8-15,15>>^ Pois vocês não receberam um espírito que os torne, de novo, escravos medrosos, mas sim o Espírito de Deus, que os adotou como seus próprios filhos. Agora nós o chamamos " Aba , Pai",

[[v45-8-16]]

^<<v45-8-16,16>>^ pois o seu Espírito confirma a nosso espírito que somos filhos de Deus.

[[v45-8-17]]

^<<v45-8-17,17>>^ Se somos seus filhos, então somos seus herdeiros e, portanto, co-herdeiros com Cristo. Se de fato participamos de seu sofrimento, participaremos também de sua glória.

[[v45-8-18]]

^<<v45-8-18,18>>^ Considero que nosso sofrimento de agora não é nada comparado com a glória que ele nos revelará mais tarde.

[[v45-8-19]]

^<<v45-8-19,19>>^ Pois toda a criação aguarda com grande expectativa o dia em que os filhos de Deus serão revelados.

[[v45-8-20]]

^<<v45-8-20,20>>^ Toda a criação, não por vontade própria, foi submetida por Deus a uma existência fútil,

[[v45-8-21]]

^<<v45-8-21,21>>^ na esperança de que, com os filhos de Deus, a criação seja gloriosamente liberta da decadência que a escraviza.

[[v45-8-22]]

^<<v45-8-22,22>>^ Pois sabemos que, até agora, toda a criação geme, como em dores de parto.

[[v45-8-23]]

^<<v45-8-23,23>>^ E nós, os que cremos, também gememos, embora tenhamos o Espírito em nós como antecipação da glória futura, pois aguardamos ansiosos pelo dia em que desfrutaremos nossos direitos de adoção, incluindo a redenção de nosso corpo.

[[v45-8-24]]

^<<v45-8-24,24>>^ Recebemos essa esperança quando fomos salvos. (Se já temos alguma coisa, não há necessidade de esperar por ela,

[[v45-8-25]]

^<<v45-8-25,25>>^ mas, se esperamos por algo que ainda não temos, devemos fazê-lo com paciência e confiança.)

[[v45-8-26]]

^<<v45-8-26,26>>^ E o Espírito nos ajuda em nossa fraqueza, pois não sabemos orar segundo a vontade de Deus, mas o próprio Espírito intercede por nós com gemidos que não podem ser expressos em palavras.

[[v45-8-27]]

^<<v45-8-27,27>>^ E o Pai, que conhece cada coração, sabe quais são as intenções do Espírito, pois o Espírito intercede por nós, o povo santo, segundo a vontade de Deus.

[[v45-8-28]]

^<<v45-8-28,28>>^ E sabemos que Deus faz todas as coisas cooperarem para o bem daqueles que o amam e que são chamados de acordo com seu propósito.

[[v45-8-29]]

^<<v45-8-29,29>>^ Pois Deus conheceu de antemão os seus e os predestinou para se tornarem semelhantes à imagem de seu Filho, a fim de que ele fosse o primeiro entre muitos irmãos.

[[v45-8-30]]

^<<v45-8-30,30>>^ Depois de predestiná-los ele os chamou, e depois de chamá-los, os declarou justos, e depois de declará-los justos, lhes deu sua glória.

[[v45-8-31]]

^<<v45-8-31,31>>^ Que podemos dizer diante de coisas tão maravilhosas? Se Deus é por nós, quem será contra nós?

[[v45-8-32]]

^<<v45-8-32,32>>^ Se ele não poupou nem mesmo seu próprio Filho, mas o entregou por todos nós, acaso não nos dará todas as outras coisas?

[[v45-8-33]]

^<<v45-8-33,33>>^ Quem se atreve a acusar os escolhidos de Deus? Ninguém, pois o próprio Deus nos declara justos diante dele.

[[v45-8-34]]

^<<v45-8-34,34>>^ Quem nos condenará, então? Ninguém, pois Cristo Jesus morreu e ressuscitou e está sentado no lugar de honra, à direita de Deus, intercedendo por nós.

[[v45-8-35]]

^<<v45-8-35,35>>^ O que nos separará do amor de Cristo? Serão aflições ou calamidades, perseguições ou fome, miséria, perigo ou ameaças de morte?

[[v45-8-36]]

^<<v45-8-36,36>>^ Como dizem as Escrituras: "Por causa de ti, enfrentamos a morte todos os dias; somos como ovelhas levadas para o matadouro".

[[v45-8-37]]

^<<v45-8-37,37>>^ Mas, apesar de tudo isso, somos mais que vencedores por meio daquele que nos amou.

[[v45-8-38]]

^<<v45-8-38,38>>^ E estou convencido de que nem morte nem vida, nem anjos nem demônios, nem o que existe hoje nem o que virá no futuro, nem poderes,

[[v45-8-39]]

^<<v45-8-39,39>>^ nem altura nem profundidade, nada, em toda a criação, jamais poderá nos separar do amor de Deus revelado em Cristo Jesus, nosso Senhor.

'''

xref:045-romanos/045-romanos-007.adoc#v45-7-0[&#60; Capítulo Anterior] | <<v45-8-0,Topo>> | xref:045-romanos/045-romanos-009.adoc#v45-9-0[Próximo Capítulo &#62;]