include::./index.adoc[]

[[v45-5-0]]
=== Romanos, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v45-5-1]]

^<<v45-5-1,1>>^ Portanto, uma vez que pela fé fomos declarados justos, temos paz com Deus por causa daquilo que Jesus Cristo, nosso Senhor, fez por nós.

[[v45-5-2]]

^<<v45-5-2,2>>^ Foi por meio da fé que Cristo nos concedeu esta graça que agora desfrutamos com segurança e alegria, pois temos a esperança de participar da glória de Deus.

[[v45-5-3]]

^<<v45-5-3,3>>^ Também nos alegramos ao enfrentar dificuldades e provações, pois sabemos que contribuem para desenvolvermos perseverança,

[[v45-5-4]]

^<<v45-5-4,4>>^ e a perseverança produz caráter aprovado, e o caráter aprovado fortalece nossa esperança,

[[v45-5-5]]

^<<v45-5-5,5>>^ e essa esperança não nos decepcionará, pois sabemos quanto Deus nos ama, uma vez que ele nos deu o Espírito Santo para nos encher o coração com seu amor.

[[v45-5-6]]

^<<v45-5-6,6>>^ Quando estávamos completamente desamparados, Cristo veio na hora certa e morreu por nós, pecadores.

[[v45-5-7]]

^<<v45-5-7,7>>^ É pouco provável que alguém morresse por um justo, embora talvez alguém se dispusesse a morrer por uma pessoa boa.

[[v45-5-8]]

^<<v45-5-8,8>>^ Mas Deus nos prova seu grande amor ao enviar Cristo para morrer por nós quando ainda éramos pecadores.

[[v45-5-9]]

^<<v45-5-9,9>>^ E, uma vez que fomos declarados justos por seu sangue, certamente seremos salvos da ira de Deus por meio dele.

[[v45-5-10]]

^<<v45-5-10,10>>^ Pois, se quando ainda éramos inimigos de Deus nosso relacionamento com ele foi restaurado pela morte de seu Filho, agora que já estamos reconciliados certamente seremos salvos por sua vida.

[[v45-5-11]]

^<<v45-5-11,11>>^ Agora, portanto, podemos nos alegrar em Deus, com quem fomos reconciliados por meio de nosso Senhor Jesus Cristo.

[[v45-5-12]]

^<<v45-5-12,12>>^ Quando Adão pecou, o pecado entrou no mundo, e com ele a morte, que se estendeu a todos, porque todos pecaram.

[[v45-5-13]]

^<<v45-5-13,13>>^ É fato que as pessoas pecaram antes que a lei fosse concedida, mas, porque ela não existia, seus pecados não foram levados em conta.

[[v45-5-14]]

^<<v45-5-14,14>>^ Mesmo assim, do tempo de Adão até o de Moisés, todos morreram, incluindo os que não desobedeceram a uma ordem explícita de Deus, como Adão desobedeceu. Na verdade, Adão é um símbolo, uma representação daquele que ainda haveria de vir.

[[v45-5-15]]

^<<v45-5-15,15>>^ Mas há uma grande diferença entre o pecado de Adão e a dádiva de Deus. Pois o pecado de um único homem trouxe morte para muitos. Ainda maior, porém, é a graça de Deus e sua dádiva que veio sobre muitos por meio de um único homem, Jesus Cristo.

[[v45-5-16]]

^<<v45-5-16,16>>^ E o resultado da dádiva de Deus é bem diferente do resultado do pecado de um único homem, pois enquanto o pecado de Adão levou à condenação, a dádiva de Deus nos possibilita ser declarados justos diante dele, apesar de nossos muitos pecados.

[[v45-5-17]]

^<<v45-5-17,17>>^ A morte reinou sobre muitos por meio do pecado de um único homem. Ainda maior, porém, é a graça de Deus e sua dádiva de justiça, e todos que a recebem reinarão em vida por meio de um único homem, Jesus Cristo.

[[v45-5-18]]

^<<v45-5-18,18>>^ É verdade que um só pecado de Adão trouxe condenação a todos, mas um só ato de justiça de Cristo removeu a culpa e trouxe vida a todos.

[[v45-5-19]]

^<<v45-5-19,19>>^ Por causa da desobediência a Deus de uma só pessoa, muitos se tornaram pecadores. Mas, por causa da obediência de uma só pessoa a Deus, muitos serão declarados justos.

[[v45-5-20]]

^<<v45-5-20,20>>^ A lei foi concedida para que todos percebessem a gravidade do pecado. Mas, à medida que o pecado aumentou, a graça se tornou ainda maior.

[[v45-5-21]]

^<<v45-5-21,21>>^ Portanto, assim como o pecado reinou sobre todos e os levou à morte, agora reina a graça, que nos declara justos diante de Deus e resulta na vida eterna por meio de Jesus Cristo, nosso Senhor.

'''

xref:045-romanos/045-romanos-004.adoc#v45-4-0[&#60; Capítulo Anterior] | <<v45-5-0,Topo>> | xref:045-romanos/045-romanos-006.adoc#v45-6-0[Próximo Capítulo &#62;]