include::./index.adoc[]

[[v45-9-0]]
=== Romanos, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v45-9-1]]

^<<v45-9-1,1>>^ Digo-lhes a verdade, tendo Cristo como testemunha, e minha consciência e o Espírito Santo a confirmam.

[[v45-9-2]]

^<<v45-9-2,2>>^ Meu coração está cheio de amarga tristeza e angústia sem fim

[[v45-9-3]]

^<<v45-9-3,3>>^ por meu povo, meus irmãos judeus. Eu estaria disposto a ser amaldiçoado para sempre, separado de Cristo, se isso pudesse salvá-los.

[[v45-9-4]]

^<<v45-9-4,4>>^ Eles são o povo de Israel, escolhidos para serem filhos adotivos de Deus. Ele lhes revelou sua glória, fez uma aliança com eles e lhes deu sua lei e o privilégio de adorá-lo e receber suas promessas.

[[v45-9-5]]

^<<v45-9-5,5>>^ Do povo de Israel vêm os patriarcas, e o próprio Cristo, quanto à sua natureza humana, era israelita. E ele é Deus, aquele que governa sobre todas as coisas e é digno de louvor eterno! Amém.

[[v45-9-6]]

^<<v45-9-6,6>>^ Acaso Deus deixou de cumprir sua promessa a Israel? Não, pois nem todos os descendentes de Israel pertencem, de fato, ao povo de Deus.

[[v45-9-7]]

^<<v45-9-7,7>>^ Só porque são descendentes de Abraão não significa que são, verdadeiramente, filhos de Abraão. Pois as Escrituras dizem: "Isaque é o filho de quem depende a sua descendência".

[[v45-9-8]]

^<<v45-9-8,8>>^ Isso significa que os descendentes físicos de Abraão não são, necessariamente, filhos de Deus. Apenas os filhos da promessa são considerados filhos de Abraão.

[[v45-9-9]]

^<<v45-9-9,9>>^ Pois Deus havia prometido: "Voltarei por esta época, e Sara terá um filho".

[[v45-9-10]]

^<<v45-9-10,10>>^ Esse fato não é único. Também Rebeca ficou grávida de nosso antepassado Isaque e deu à luz gêmeos.

[[v45-9-11]]

^<<v45-9-11,11>>^ Antes de eles nascerem, porém, antes mesmo de terem feito qualquer coisa boa ou má, ela recebeu uma mensagem de Deus. (Essa mensagem mostra que Deus escolhe as pessoas conforme os propósitos dele

[[v45-9-12]]

^<<v45-9-12,12>>^ e as chama sem levar em conta as obras que praticam.) Foi dito a Rebeca: "Seu filho mais velho servirá a seu filho mais novo".

[[v45-9-13]]

^<<v45-9-13,13>>^ Nas palavras das Escrituras: "Amei Jacó, mas rejeitei Esaú".

[[v45-9-14]]

^<<v45-9-14,14>>^ Estamos dizendo, então, que Deus foi injusto? Claro que não!

[[v45-9-15]]

^<<v45-9-15,15>>^ Pois Deus disse a Moisés: "Terei misericórdia de quem eu quiser, e mostrarei compaixão a quem eu quiser".

[[v45-9-16]]

^<<v45-9-16,16>>^ Portanto, a misericórdia depende apenas de Deus, e não de nosso desejo nem de nossos esforços.

[[v45-9-17]]

^<<v45-9-17,17>>^ Pois as Escrituras afirmam que Deus disse ao faraó: "Eu o coloquei em posição de autoridade com o propósito de mostrar em você meu poder e propagar meu nome por toda a terra".

[[v45-9-18]]

^<<v45-9-18,18>>^ Como podem ver, ele escolhe ter misericórdia de alguns e endurecer o coração de outros.

[[v45-9-19]]

^<<v45-9-19,19>>^ Mas algum de vocês dirá: "Então por que Deus os culpa? Não estão apenas cumprindo a vontade dele?".

[[v45-9-20]]

^<<v45-9-20,20>>^ Ora, quem é você, mero ser humano, para discutir com Deus? Acaso o objeto criado pode dizer àquele que o criou: "Por que você me fez assim?"

[[v45-9-21]]

^<<v45-9-21,21>>^ O oleiro não tem o direito de usar o mesmo barro para fazer um vaso para uso especial e outro para uso comum?

[[v45-9-22]]

^<<v45-9-22,22>>^ Da mesma forma, Deus tem o direito de mostrar sua ira e seu poder, suportando com muita paciência aqueles que são objeto de sua ira, preparados para a destruição.

[[v45-9-23]]

^<<v45-9-23,23>>^ Ele age desse modo para que as riquezas de sua glória brilhem com esplendor ainda maior sobre aqueles dos quais ele tem misericórdia, aqueles que ele preparou previamente para a glória.

[[v45-9-24]]

^<<v45-9-24,24>>^ E nós estamos entre os que ele chamou, tanto dentre os judeus como dentre os gentios.

[[v45-9-25]]

^<<v45-9-25,25>>^ A esse respeito, Deus diz na profecia de Oseias: "Chamarei ‘meu povo’ aqueles que não eram meu povo, e amarei aqueles que antes eu não amava".

[[v45-9-26]]

^<<v45-9-26,26>>^ E também: "No lugar onde lhes foi dito: ‘Vocês não são meu povo’, eles serão chamados ‘filhos do Deus vivo’".

[[v45-9-27]]

^<<v45-9-27,27>>^ E, a respeito de Israel, o profeta Isaías clamou: "Embora o povo de Israel seja numeroso como a areia do mar, apenas um remanescente será salvo.

[[v45-9-28]]

^<<v45-9-28,28>>^ Pois o Senhor executará sua sentença sobre a terra de modo rápido e decisivo".

[[v45-9-29]]

^<<v45-9-29,29>>^ E, como Isaías tinha dito em outra passagem: "Se o Senhor dos Exércitos não houvesse poupado alguns de nossos filhos, teríamos sido exterminados como Sodoma e destruídos como Gomorra".

[[v45-9-30]]

^<<v45-9-30,30>>^ Que significa tudo isso? Embora os gentios não buscassem seguir as normas de Deus, foram declarados justos, e isso aconteceu pela fé.

[[v45-9-31]]

^<<v45-9-31,31>>^ Já o povo de Israel, que se esforçou tanto para cumprir a lei a fim de se tornar justo, nunca teve sucesso.

[[v45-9-32]]

^<<v45-9-32,32>>^ Por que não? Porque tentaram se tornar justos por meio de suas obras, e não pela fé. Tropeçaram na grande pedra em seu caminho,

[[v45-9-33]]

^<<v45-9-33,33>>^ e a esse respeito as Escrituras afirmam: "Ponho em Sião uma pedra que os faz tropeçar, uma rocha que os faz cair. Mas quem confiar nele jamais será envergonhado".

'''

xref:045-romanos/045-romanos-008.adoc#v45-8-0[&#60; Capítulo Anterior] | <<v45-9-0,Topo>> | xref:045-romanos/045-romanos-010.adoc#v45-10-0[Próximo Capítulo &#62;]