include::./index.adoc[]

[[v45-7-0]]
=== Romanos, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v45-7-1]]

^<<v45-7-1,1>>^ Agora, irmãos, vocês que conhecem a lei, não sabem que ela se aplica apenas enquanto a pessoa vive?

[[v45-7-2]]

^<<v45-7-2,2>>^ Por exemplo, quando uma mulher se casa, a lei a une a seu marido enquanto ele estiver vivo. No entanto, se ele morrer, as leis do casamento já não se aplicarão à mulher.

[[v45-7-3]]

^<<v45-7-3,3>>^ Portanto, enquanto o marido estiver vivo, se ela se casar com outro homem, cometerá adultério. Mas, se o marido morrer, ela ficará livre dessa lei e não cometerá adultério ao se casar novamente.

[[v45-7-4]]

^<<v45-7-4,4>>^ Assim, meus irmãos, vocês morreram para o poder da lei quando morreram com Cristo, e agora estão unidos com aquele que foi ressuscitado dos mortos. Como resultado, podemos produzir uma colheita de boas obras para Deus.

[[v45-7-5]]

^<<v45-7-5,5>>^ Quando éramos controlados pela natureza humana, desejos pecaminosos atuavam dentro de nós, e a lei despertava esses desejos maus, que produziam uma colheita de obras pecaminosas cujo resultado era a morte.

[[v45-7-6]]

^<<v45-7-6,6>>^ Agora, porém, fomos libertos da lei, pois morremos para ela e já não estamos presos a seu poder. Podemos servir a Deus não da maneira antiga, obedecendo à letra da lei, mas da maneira nova, vivendo no Espírito.

[[v45-7-7]]

^<<v45-7-7,7>>^ Por acaso estou dizendo que a lei de Deus é pecaminosa? Claro que não! Na verdade, foi a lei que me mostrou meu pecado. Eu jamais saberia que cobiçar é errado se a lei não dissesse: "Não cobice".

[[v45-7-8]]

^<<v45-7-8,8>>^ Mas o pecado usou esse mandamento para despertar dentro de mim todo tipo de desejo cobiçoso. Se não houvesse lei, o pecado não teria esse poder.

[[v45-7-9]]

^<<v45-7-9,9>>^ Houve um tempo em que eu vivia sem a lei. No entanto, quando tomei conhecimento do mandamento, o pecado ganhou vida,

[[v45-7-10]]

^<<v45-7-10,10>>^ e eu morri. Assim, descobri que os mandamentos da lei, que deveriam trazer vida, trouxeram, em vez disso, morte.

[[v45-7-11]]

^<<v45-7-11,11>>^ O pecado se aproveitou desses mandamentos e me enganou, e fez uso deles para me matar.

[[v45-7-12]]

^<<v45-7-12,12>>^ Isso, porém, só demonstra que a lei em si é santa, e santos, justos e bons são seus mandamentos.

[[v45-7-13]]

^<<v45-7-13,13>>^ Mas, então, a lei, que é boa, foi responsável por minha morte? Claro que não! O pecado usou o que era bom para me condenar à morte. Vemos, com isso, como o pecado é terrível, usando os bons mandamentos de Deus para seus próprios fins perversos.

[[v45-7-14]]

^<<v45-7-14,14>>^ O problema não está na lei, pois ela é espiritual e boa. O problema está em mim, pois sou humano, escravo do pecado.

[[v45-7-15]]

^<<v45-7-15,15>>^ Não entendo a mim mesmo, pois quero fazer o que é certo, mas não o faço. Em vez disso, faço aquilo que odeio.

[[v45-7-16]]

^<<v45-7-16,16>>^ Mas, se eu sei que o que faço é errado, isso mostra que concordo que a lei é boa.

[[v45-7-17]]

^<<v45-7-17,17>>^ Portanto, não sou eu quem faz o que é errado, mas o pecado que habita em mim.

[[v45-7-18]]

^<<v45-7-18,18>>^ E eu sei que em mim, isto é, em minha natureza humana, não há nada de bom, pois quero fazer o que é certo, mas não consigo.

[[v45-7-19]]

^<<v45-7-19,19>>^ Quero fazer o bem, mas não o faço. Não quero fazer o que é errado, mas, ainda assim, o faço.

[[v45-7-20]]

^<<v45-7-20,20>>^ Então, se faço o que não quero, na verdade não sou eu quem o faz, mas o pecado que habita em mim.

[[v45-7-21]]

^<<v45-7-21,21>>^ Assim, descobri esta lei em minha vida: quando quero fazer o que é certo, percebo que o mal está presente em mim.

[[v45-7-22]]

^<<v45-7-22,22>>^ Amo a lei de Deus de todo o coração.

[[v45-7-23]]

^<<v45-7-23,23>>^ Contudo, há outra lei dentro de mim que está em guerra com minha mente e me torna escravo do pecado que permanece dentro de mim.

[[v45-7-24]]

^<<v45-7-24,24>>^ Como sou miserável! Quem me libertará deste corpo mortal dominado pelo pecado?

[[v45-7-25]]

^<<v45-7-25,25>>^ Graças a Deus, a resposta está em Jesus Cristo, nosso Senhor. Na mente, quero, de fato, obedecer à lei de Deus, mas, por causa de minha natureza humana, sou escravo do pecado.

'''

xref:045-romanos/045-romanos-006.adoc#v45-6-0[&#60; Capítulo Anterior] | <<v45-7-0,Topo>> | xref:045-romanos/045-romanos-008.adoc#v45-8-0[Próximo Capítulo &#62;]