include::./index.adoc[]

[[v45-14-0]]
=== Romanos, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v45-14-1]]

^<<v45-14-1,1>>^ Aceitem os que são fracos na fé e não discutam sobre as opiniões deles acerca do que é certo ou errado.

[[v45-14-2]]

^<<v45-14-2,2>>^ Por exemplo, um irmão crê que não é errado comer qualquer coisa. Outro, porém, que é mais fraco, come somente legumes e verduras.

[[v45-14-3]]

^<<v45-14-3,3>>^ Quem se sente à vontade para comer de tudo não deve desprezar quem não o faz. E quem não come certos alimentos não deve condenar quem o faz, pois Deus os aceitou.

[[v45-14-4]]

^<<v45-14-4,4>>^ Quem são vocês para condenar os servos de outra pessoa? O senhor deles julgará se estão em pé ou se caíram. E, com a ajuda de Deus, ficarão em pé e receberão a aprovação dele.

[[v45-14-5]]

^<<v45-14-5,5>>^ Da mesma forma, há quem considere um dia mais sagrado que outro, enquanto outros acreditam que todos os dias são iguais. Cada um deve estar plenamente convicto do que faz.

[[v45-14-6]]

^<<v45-14-6,6>>^ Quem adora a Deus num dia especial o faz para honrá-lo. Quem come qualquer tipo de alimento também o faz para honrar o Senhor, uma vez que dá graças a Deus antes de comer. E quem se recusa a comer certos alimentos deseja, igualmente, agradar ao Senhor e por isso dá graças a Deus.

[[v45-14-7]]

^<<v45-14-7,7>>^ Pois não vivemos nem morremos para nós mesmos.

[[v45-14-8]]

^<<v45-14-8,8>>^ Se vivemos, é para honrar o Senhor. E, se morremos, é para honrar o Senhor. Portanto, quer vivamos, quer morramos, pertencemos ao Senhor.

[[v45-14-9]]

^<<v45-14-9,9>>^ Por isso Cristo morreu e ressuscitou, para ser Senhor tanto dos vivos como dos mortos.

[[v45-14-10]]

^<<v45-14-10,10>>^ Então por que você julga outro irmão? Por que o despreza? Lembre-se de que todos nós compareceremos diante do tribunal de Deus,

[[v45-14-11]]

^<<v45-14-11,11>>^ pois as Escrituras dizem: "‘Tão certo como eu vivo’, diz o Senhor, ‘todo joelho se dobrará para mim, e toda língua declarará lealdade a Deus’".

[[v45-14-12]]

^<<v45-14-12,12>>^ Assim, cada um de nós será responsável por sua vida diante de Deus.

[[v45-14-13]]

^<<v45-14-13,13>>^ Portanto, deixemos de julgar uns aos outros. Em vez disso, resolvam viver de modo a nunca fazer um irmão tropeçar e cair.

[[v45-14-14]]

^<<v45-14-14,14>>^ Eu sei, e estou convencido com base na autoridade do Senhor Jesus, que nenhum alimento é por si mesmo impuro. Mas, se alguém considera errado ingerir determinado alimento, para essa pessoa ele é impuro.

[[v45-14-15]]

^<<v45-14-15,15>>^ E, se outro irmão se aflige em razão do que você come, ao ingerir esse alimento você não age com amor. Não deixe que sua comida seja a causa da perdição de alguém por quem Cristo morreu.

[[v45-14-16]]

^<<v45-14-16,16>>^ Desse modo, você não será criticado por fazer algo que, a seu ver, é bom.

[[v45-14-17]]

^<<v45-14-17,17>>^ Pois o reino de Deus não diz respeito ao que comemos ou bebemos, mas a uma vida de justiça, paz e alegria no Espírito Santo.

[[v45-14-18]]

^<<v45-14-18,18>>^ Se servirem a Cristo com essa atitude, agradarão a Deus e também receberão a aprovação das pessoas.

[[v45-14-19]]

^<<v45-14-19,19>>^ Portanto, tenhamos como alvo a harmonia e procuremos edificar uns aos outros.

[[v45-14-20]]

^<<v45-14-20,20>>^ Não destruam a obra de Deus por causa da comida. Embora todos os alimentos sejam aceitáveis, é errado comer algo que leve alguém a tropeçar.

[[v45-14-21]]

^<<v45-14-21,21>>^ É melhor deixar de comer carne, ou de beber vinho, ou de fazer qualquer outra coisa que leve um irmão a tropeçar.

[[v45-14-22]]

^<<v45-14-22,22>>^ Você tem direito a suas convicções, mas guarde isso entre você e Deus. Felizes são aqueles que não se sentem culpados por fazer algo que consideram correto.

[[v45-14-23]]

^<<v45-14-23,23>>^ Mas, se você tem dúvidas quanto ao que deve ou não comer, será culpado se comer, pois vai contra suas convicções. Se faz qualquer coisa sem convicção, está pecando.

'''

xref:045-romanos/045-romanos-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romanos/045-romanos-015.adoc#v45-15-0[Próximo Capítulo &#62;]