include::./index.adoc[]

[[v45-12-0]]
=== Romanos, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v45-12-1]]

^<<v45-12-1,1>>^ Portanto, irmãos, suplico-lhes que entreguem seu corpo a Deus, por causa de tudo que ele fez por vocês. Que seja um sacrifício vivo e santo, do tipo que Deus considera agradável. Essa é a verdadeira forma de adorá-lo.

[[v45-12-2]]

^<<v45-12-2,2>>^ Não imitem o comportamento e os costumes deste mundo, mas deixem que Deus os transforme por meio de uma mudança em seu modo de pensar, a fim de que experimentem a boa, agradável e perfeita vontade de Deus para vocês.

[[v45-12-3]]

^<<v45-12-3,3>>^ Com base na graça que recebi, dou a cada um de vocês a seguinte advertência: não se considerem melhores do que realmente são. Antes, sejam honestos em sua autoavaliação, medindo-se de acordo com a fé que Deus nos deu.

[[v45-12-4]]

^<<v45-12-4,4>>^ Da mesma forma que nosso corpo tem vários membros e cada membro, uma função específica,

[[v45-12-5]]

^<<v45-12-5,5>>^ assim é também com o corpo de Cristo. Somos membros diferentes do mesmo corpo, e todos pertencemos uns aos outros.

[[v45-12-6]]

^<<v45-12-6,6>>^ Deus, em sua graça, nos concedeu diferentes dons. Portanto, se você tiver a capacidade de profetizar, faça-o de acordo com a proporção de fé que recebeu.

[[v45-12-7]]

^<<v45-12-7,7>>^ Se tiver o dom de servir, sirva com dedicação. Se for mestre, ensine bem.

[[v45-12-8]]

^<<v45-12-8,8>>^ Se seu dom consistir em encorajar pessoas, encoraje-as. Se for o dom de contribuir, dê com generosidade. Se for o de exercer liderança, lidere de forma responsável. E, se for o de demonstrar misericórdia, pratique-o com alegria.

[[v45-12-9]]

^<<v45-12-9,9>>^ Amem as pessoas sem fingimento. Odeiem tudo que é mau. Apeguem-se firmemente ao que é bom.

[[v45-12-10]]

^<<v45-12-10,10>>^ Amem-se com amor fraternal e tenham prazer em honrar uns aos outros.

[[v45-12-11]]

^<<v45-12-11,11>>^ Jamais sejam preguiçosos, mas trabalhem com dedicação e sirvam ao Senhor com entusiasmo.

[[v45-12-12]]

^<<v45-12-12,12>>^ Alegrem-se em nossa esperança. Sejam pacientes nas dificuldades e não parem de orar.

[[v45-12-13]]

^<<v45-12-13,13>>^ Quando membros do povo santo passarem por necessidade, ajudem com prontidão. Estejam sempre dispostos a praticar a hospitalidade.

[[v45-12-14]]

^<<v45-12-14,14>>^ Abençoem aqueles que os perseguem. Não os amaldiçoem, mas orem para que Deus os abençoe.

[[v45-12-15]]

^<<v45-12-15,15>>^ Alegrem-se com os que se alegram e chorem com os que choram.

[[v45-12-16]]

^<<v45-12-16,16>>^ Vivam em harmonia uns com os outros. Não sejam orgulhosos, mas tenham amizade com gente de condição humilde. E não pensem que sabem tudo.

[[v45-12-17]]

^<<v45-12-17,17>>^ Nunca paguem o mal com o mal. Pensem sempre em fazer o que é melhor aos olhos de todos.

[[v45-12-18]]

^<<v45-12-18,18>>^ No que depender de vocês, vivam em paz com todos.

[[v45-12-19]]

^<<v45-12-19,19>>^ Amados, nunca se vinguem; deixem que a ira de Deus se encarregue disso, pois assim dizem as Escrituras: "A vingança cabe a mim, eu lhes darei o troco, diz o Senhor".

[[v45-12-20]]

^<<v45-12-20,20>>^ Pelo contrário: "Se seu inimigo estiver com fome, dê-lhe de comer; se estiver com sede, dê-lhe de beber. Ao fazer isso, amontoará brasas vivas sobre a cabeça dele".

[[v45-12-21]]

^<<v45-12-21,21>>^ Não deixem que o mal os vença, mas vençam o mal praticando o bem.

'''

xref:045-romanos/045-romanos-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-romanos/045-romanos-013.adoc#v45-13-0[Próximo Capítulo &#62;]