include::./index.adoc[]

[[v45-1-0]]
=== Romanos, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v45-1-1]]

^<<v45-1-1,1>>^ Eu, Paulo, escravo de Cristo Jesus, chamado para ser apóstolo e enviado para anunciar as boas-novas de Deus, escrevo esta carta.

[[v45-1-2]]

^<<v45-1-2,2>>^ Deus prometeu as boas-novas muito tempo atrás nas Escrituras Sagradas, por meio de seus profetas.

[[v45-1-3]]

^<<v45-1-3,3>>^ Elas se referem a seu Filho, que, como homem, nasceu da linhagem do rei Davi,

[[v45-1-4]]

^<<v45-1-4,4>>^ e, quando o poder do Espírito Santo o ressuscitou dos mortos, foi demonstrado que ele era o Filho de Deus. Ele é Jesus Cristo, nosso Senhor.

[[v45-1-5]]

^<<v45-1-5,5>>^ Por meio dele recebemos a graça e a autoridade, como apóstolos, de chamar os gentios em toda parte a crer nele e lhe obedecer, em honra de seu nome.

[[v45-1-6]]

^<<v45-1-6,6>>^ E vocês estão entre esses gentios chamados para pertencer a Jesus Cristo.

[[v45-1-7]]

^<<v45-1-7,7>>^ Escrevo a todos vocês que estão em Roma, amados por Deus e chamados para ser seu povo santo. Que Deus, nosso Pai, e o Senhor Jesus Cristo lhes deem graça e paz.

[[v45-1-8]]

^<<v45-1-8,8>>^ Antes de tudo, quero dizer que, por meio de Jesus Cristo, agradeço a meu Deus por todos vocês, pois sua fé nele é comentada em todo o mundo.

[[v45-1-9]]

^<<v45-1-9,9>>^ O Deus a quem sirvo em meu espírito, anunciando as boas-novas a respeito de seu Filho, sabe como nunca deixo de me lembrar de vocês

[[v45-1-10]]

^<<v45-1-10,10>>^ em minhas orações, sempre pedindo, se for da vontade de Deus, uma oportunidade de ir vê-los.

[[v45-1-11]]

^<<v45-1-11,11>>^ Desejo muito visitá-los, a fim de compartilhar com vocês alguma dádiva espiritual que os ajude a se fortalecerem.

[[v45-1-12]]

^<<v45-1-12,12>>^ Quando nos encontrarmos, quero encorajá-los na fé, e também quero ser encorajado por sua fé.

[[v45-1-13]]

^<<v45-1-13,13>>^ Quero que saibam, irmãos, que muitas vezes planejei visitá-los, mas até agora fui impedido. Meu desejo é trabalhar entre vocês e ver frutos espirituais como tenho visto entre outros gentios,

[[v45-1-14]]

^<<v45-1-14,14>>^ pois sinto grande obrigação tanto para com os gregos como os bárbaros, tanto para com os instruídos como os não instruídos.

[[v45-1-15]]

^<<v45-1-15,15>>^ Por isso, aguardo com expectativa para visitá-los, a fim de anunciar as boas-novas também a vocês, em Roma.

[[v45-1-16]]

^<<v45-1-16,16>>^ Pois não me envergonho das boas-novas a respeito de Cristo, que são o poder de Deus em ação para salvar todos os que creem, primeiro os judeus, e também os gentios.

[[v45-1-17]]

^<<v45-1-17,17>>^ As boas-novas revelam como Deus nos declara justos diante dele, o que, do começo ao fim, é algo que se dá pela fé. Como dizem as Escrituras: "O justo viverá pela fé".

[[v45-1-18]]

^<<v45-1-18,18>>^ Assim, Deus mostra do céu sua ira contra todos que são pecadores e perversos, que por sua maldade impedem que a verdade seja conhecida.

[[v45-1-19]]

^<<v45-1-19,19>>^ Sabem a verdade a respeito de Deus, pois ele a tornou evidente.

[[v45-1-20]]

^<<v45-1-20,20>>^ Por meio de tudo que ele fez desde a criação do mundo, podem perceber claramente seus atributos invisíveis: seu poder eterno e sua natureza divina. Portanto, não têm desculpa alguma.

[[v45-1-21]]

^<<v45-1-21,21>>^ Sim, eles conheciam algo sobre Deus, mas não o adoraram nem lhe agradeceram. Em vez disso, começaram a inventar ideias tolas e, com isso, sua mente ficou obscurecida e confusa.

[[v45-1-22]]

^<<v45-1-22,22>>^ Dizendo-se sábios, tornaram-se tolos.

[[v45-1-23]]

^<<v45-1-23,23>>^ Trocaram a grandeza do Deus imortal por imagens de seres humanos mortais, bem como de aves, animais e répteis.

[[v45-1-24]]

^<<v45-1-24,24>>^ Por isso, Deus os entregou aos desejos pecaminosos de seu coração. Como resultado, praticaram entre si coisas desprezíveis e degradantes com o próprio corpo.

[[v45-1-25]]

^<<v45-1-25,25>>^ Trocaram a verdade sobre Deus pela mentira. Desse modo, adoraram e serviram coisas que Deus criou, em lugar do Criador, que é digno de louvor eterno! Amém.

[[v45-1-26]]

^<<v45-1-26,26>>^ Por isso, Deus os entregou a desejos vergonhosos. Até as mulheres trocaram sua forma natural de ter relações sexuais por práticas não naturais.

[[v45-1-27]]

^<<v45-1-27,27>>^ E os homens, em vez de ter relações sexuais normais com mulheres, arderam de desejo uns pelos outros. Homens praticaram atos indecentes com outros homens e, em decorrência desse pecado, sofreram em si mesmos o castigo que mereciam.

[[v45-1-28]]

^<<v45-1-28,28>>^ Uma vez que consideraram que conhecer a Deus era algo inútil, o próprio Deus os entregou a um inútil modo de pensar, deixando que fizessem coisas que jamais deveriam ser feitas.

[[v45-1-29]]

^<<v45-1-29,29>>^ A vida deles se encheu de toda espécie de perversidade, pecado, ganância, ódio, inveja, homicídio, discórdia, engano, malícia e fofocas.

[[v45-1-30]]

^<<v45-1-30,30>>^ Espalham calúnias, odeiam a Deus, são insolentes, orgulhosos e arrogantes. Inventam novas maneiras de pecar e desobedecem a seus pais.

[[v45-1-31]]

^<<v45-1-31,31>>^ Não têm entendimento, quebram suas promessas, não mostram afeição nem misericórdia.

[[v45-1-32]]

^<<v45-1-32,32>>^ Sabem que, de acordo com a justiça de Deus, quem pratica essas coisas merece morrer, mas ainda assim continuam a praticá-las. E, o que é pior, incentivam outros a também fazê-lo.

'''

xref:044-atos/044-atos-028.adoc#v44-28-0[&#60; Capítulo Anterior] | <<v45-1-0,Topo>> | xref:045-romanos/045-romanos-002.adoc#v45-2-0[Próximo Capítulo &#62;]