include::./index.adoc[]

[[v45-2-0]]
=== Romanos, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v45-2-1]]

^<<v45-2-1,1>>^ Talvez você pense que pode condenar esses indivíduos, mas é igual a eles e não tem desculpa! Quando diz que eles deveriam ser castigados, condena a si mesmo, porque você, que julga os outros, pratica as mesmas coisas.

[[v45-2-2]]

^<<v45-2-2,2>>^ E sabemos que Deus, em sua justiça, castigará todos que praticam tais coisas.

[[v45-2-3]]

^<<v45-2-3,3>>^ Uma vez que você julga outros por fazerem essas coisas, o que o leva a pensar que evitará o julgamento de Deus ao agir da mesma forma?

[[v45-2-4]]

^<<v45-2-4,4>>^ Não percebe quanto ele é bondoso, tolerante e paciente com você? Não vê que essas manifestações da bondade de Deus visam levá-lo ao arrependimento?

[[v45-2-5]]

^<<v45-2-5,5>>^ Mas, por causa de seu coração rebelde, você se recusa a abandonar o pecado, acumulando ira sobre si mesmo. Pois o dia da ira se aproxima, quando o justo juízo de Deus se revelará.

[[v45-2-6]]

^<<v45-2-6,6>>^ Ele julgará cada um de acordo com seus atos.

[[v45-2-7]]

^<<v45-2-7,7>>^ Dará vida eterna àqueles que, persistindo em fazer o bem, buscam glória, honra e imortalidade.

[[v45-2-8]]

^<<v45-2-8,8>>^ Mas derramará ira e indignação sobre os que vivem para si mesmos, que se recusam a obedecer à verdade e preferem entregar-se a uma vida de perversidade.

[[v45-2-9]]

^<<v45-2-9,9>>^ A todos que praticam o mal, ele trará aflição e calamidade: primeiro para os judeus, e também para os gentios.

[[v45-2-10]]

^<<v45-2-10,10>>^ Mas, a todos que fazem o bem, ele dará glória, honra e paz: primeiro para os judeus, e também para os gentios.

[[v45-2-11]]

^<<v45-2-11,11>>^ Pois Deus não age com favoritismo.

[[v45-2-12]]

^<<v45-2-12,12>>^ Assim, todos os que pecarem, mesmo não tendo a lei escrita de Deus, serão destruídos. E todos os que pecarem estando sob a lei de Deus, de acordo com essa lei serão julgados.

[[v45-2-13]]

^<<v45-2-13,13>>^ Pois o simples ato de ouvir a lei não nos torna justos diante de Deus, mas sim a obediência à lei é que nos torna justos aos olhos dele.

[[v45-2-14]]

^<<v45-2-14,14>>^ Até mesmo os gentios, que não têm a lei escrita, quando obedecem a ela instintivamente, mostram que conhecem a lei, mesmo não a tendo.

[[v45-2-15]]

^<<v45-2-15,15>>^ Demonstram que a lei está gravada em seu coração, pois sua consciência e seus pensamentos os acusam ou lhes dizem que estão agindo corretamente.

[[v45-2-16]]

^<<v45-2-16,16>>^ Isso se confirmará no dia em que Deus julgar os segredos de cada um por meio de Cristo Jesus, de acordo com as boas-novas que anuncio.

[[v45-2-17]]

^<<v45-2-17,17>>^ Você, que se diz judeu, se apoia na lei de Deus e se orgulha de seu relacionamento especial com ele.

[[v45-2-18]]

^<<v45-2-18,18>>^ Conhece a vontade de Deus: sabe o que é certo, porque foi instruído em sua lei.

[[v45-2-19]]

^<<v45-2-19,19>>^ Está convencido de que é guia para os cegos e luz para os que estão perdidos na escuridão.

[[v45-2-20]]

^<<v45-2-20,20>>^ Considera-se capaz de instruir os ignorantes e ensinar os caminhos de Deus às crianças. Está certo de que a lei de Deus lhe dá pleno conhecimento e verdade.

[[v45-2-21]]

^<<v45-2-21,21>>^ Pois bem, se você ensina a outros, por que não ensina a si mesmo? Diz a outros que não roubem, mas você mesmo rouba?

[[v45-2-22]]

^<<v45-2-22,22>>^ Afirma que é errado cometer adultério, mas você mesmo adultera? Condena a idolatria, mas rouba objetos dos templos?

[[v45-2-23]]

^<<v45-2-23,23>>^ Você, que tanto se orgulha de conhecer a lei, desonra a Deus, desobedecendo à lei?

[[v45-2-24]]

^<<v45-2-24,24>>^ Não é de admirar que as Escrituras digam: "Os gentios blasfemam o nome de Deus por causa de vocês".

[[v45-2-25]]

^<<v45-2-25,25>>^ A prática judaica da circuncisão só tem valor se você obedece à lei de Deus. Mas se você, que é circuncidado, não obedece à lei de Deus, não é diferente de um gentio incircuncidado.

[[v45-2-26]]

^<<v45-2-26,26>>^ E, se os incircuncidados obedecerem à lei de Deus, acaso não serão também considerados circuncidados?

[[v45-2-27]]

^<<v45-2-27,27>>^ De fato, os gentios incircuncidados que cumprem a lei de Deus condenarão você, judeu, que é circuncidado e tem a lei de Deus, mas não obedece a ela.

[[v45-2-28]]

^<<v45-2-28,28>>^ Pois ser judeu exteriormente ou ser circuncidado não torna ninguém judeu de fato.

[[v45-2-29]]

^<<v45-2-29,29>>^ Judeu verdadeiro é quem o é no íntimo, e circuncisão verdadeira é a do coração, feita pelo Espírito, e não pela letra da lei, recebendo assim a aprovação de Deus, e não das pessoas.

'''

xref:045-romanos/045-romanos-001.adoc#v45-1-0[&#60; Capítulo Anterior] | <<v45-2-0,Topo>> | xref:045-romanos/045-romanos-003.adoc#v45-3-0[Próximo Capítulo &#62;]