include::./index.adoc[]

[[v45-15-0]]
=== Romanos, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v45-15-1]]

^<<v45-15-1,1>>^ Nós que somos fortes devemos ter consideração pelos fracos, e não agradar a nós mesmos.

[[v45-15-2]]

^<<v45-15-2,2>>^ Devemos agradar ao próximo visando ao que é certo, com a edificação deles como alvo.

[[v45-15-3]]

^<<v45-15-3,3>>^ Pois Cristo não viveu para agradar a si mesmo. Como dizem as Escrituras: "Os insultos dos que te insultam caem sobre mim".

[[v45-15-4]]

^<<v45-15-4,4>>^ Essas coisas foram registradas há muito tempo para nos ensinar, e as Escrituras nos dão paciência e ânimo para mantermos a esperança.

[[v45-15-5]]

^<<v45-15-5,5>>^ Que Deus, aquele que concede paciência e ânimo, os ajude a viver em completa harmonia uns com os outros, como convém aos seguidores de Cristo Jesus.

[[v45-15-6]]

^<<v45-15-6,6>>^ Então todos vocês poderão se unir em uma só voz para louvar e glorificar a Deus, o Pai de nosso Senhor Jesus Cristo.

[[v45-15-7]]

^<<v45-15-7,7>>^ Portanto, aceitem-se uns aos outros como Cristo os aceitou, para que Deus seja glorificado.

[[v45-15-8]]

^<<v45-15-8,8>>^ Lembrem-se de que Cristo veio para servir aos judeus, a fim de mostrar que Deus é fiel às promessas feitas a seus patriarcas,

[[v45-15-9]]

^<<v45-15-9,9>>^ e também para que os gentios glorifiquem a Deus por suas misericórdias, como dizem as Escrituras: "Por isso eu te louvarei entre os gentios; sim, cantarei louvores ao teu nome".

[[v45-15-10]]

^<<v45-15-10,10>>^ E dizem também: "Alegrem-se com o povo dele, ó gentios".

[[v45-15-11]]

^<<v45-15-11,11>>^ E ainda: "Louvem o Senhor, todos vocês, gentios; louvem-no, todos os povos".

[[v45-15-12]]

^<<v45-15-12,12>>^ E, em outra parte, o profeta Isaías disse: "Virá o herdeiro do trono de Davi e reinará sobre os gentios. Nele depositarão sua esperança".

[[v45-15-13]]

^<<v45-15-13,13>>^ Que Deus, a fonte de esperança, os encha inteiramente de alegria e paz, em vista da fé que vocês depositam nele, de modo que vocês transbordem de esperança, pelo poder do Espírito Santo.

[[v45-15-14]]

^<<v45-15-14,14>>^ Meus irmãos, estou plenamente convencido de que vocês estão cheios de bondade. Conhecem essas coisas tão bem que podem ensiná-las uns aos outros.

[[v45-15-15]]

^<<v45-15-15,15>>^ Ainda assim, atrevi-me a escrever a vocês sobre alguns desses assuntos, certo de que só precisam de um lembrete. Pois, pela graça de Deus,

[[v45-15-16]]

^<<v45-15-16,16>>^ sou um mensageiro da parte de Cristo Jesus a vocês, os gentios. Anuncio-lhes as boas-novas para que se tornem oferta aceitável a Deus, separados pelo Espírito Santo.

[[v45-15-17]]

^<<v45-15-17,17>>^ Tenho motivo, portanto, para me entusiasmar com o que Cristo Jesus tem feito por meio de meu serviço a Deus.

[[v45-15-18]]

^<<v45-15-18,18>>^ E, no entanto, não ouso me vangloriar de nada, exceto do que Cristo fez por meu intermédio a fim de conduzir os gentios a Deus, por minha mensagem e pelo meu trabalho,

[[v45-15-19]]

^<<v45-15-19,19>>^ convencendo-os pelo poder de sinais e maravilhas e pelo poder do Espírito de Deus. Assim, apresentei plenamente as boas-novas de Cristo desde Jerusalém até o Ilírico.

[[v45-15-20]]

^<<v45-15-20,20>>^ Sempre me propus a anunciar as boas-novas onde o nome de Cristo nunca foi ouvido, para não construir sobre alicerce alheio.

[[v45-15-21]]

^<<v45-15-21,21>>^ Pois, conforme dizem as Escrituras: "Aqueles aos quais ele nunca foi anunciado verão, e os que nunca ouviram falar dele entenderão".

[[v45-15-22]]

^<<v45-15-22,22>>^ É por isso, aliás, que há tanto tempo tenho adiado minha visita a vocês, porque estava pregando nesses lugares.

[[v45-15-23]]

^<<v45-15-23,23>>^ Mas, agora que terminei meu trabalho nessas regiões, e depois de tantos anos de espera, estou ansioso para visitá-los.

[[v45-15-24]]

^<<v45-15-24,24>>^ Planejo ir à Espanha e, quando for, espero passar por Roma. E, depois de ter desfrutado um pouco de sua companhia, vocês poderão me ajudar com a viagem.

[[v45-15-25]]

^<<v45-15-25,25>>^ Antes de visitá-los, porém, devo ir a Jerusalém, para servir ao povo santo de lá.

[[v45-15-26]]

^<<v45-15-26,26>>^ Pois os irmãos da Macedônia e da Acaia juntaram, de boa vontade, uma oferta para os pobres dentre o povo santo em Jerusalém.

[[v45-15-27]]

^<<v45-15-27,27>>^ Ficaram contentes em fazê-lo, pois se sentem devedores deles. Porque os gentios receberam as bênçãos espirituais das boas-novas dos irmãos em Jerusalém, consideram que no mínimo podem retribuir ajudando-os financeiramente.

[[v45-15-28]]

^<<v45-15-28,28>>^ Assim que eu tiver entregado o dinheiro e completado essa boa ação dos gentios, irei à Espanha, visitando vocês de passagem.

[[v45-15-29]]

^<<v45-15-29,29>>^ E estou certo de que, quando for, Cristo abençoará ricamente nosso tempo juntos.

[[v45-15-30]]

^<<v45-15-30,30>>^ Irmãos, peço-lhes em nome de nosso Senhor Jesus Cristo e pelo amor que lhes foi dado pelo Espírito Santo que se unam a mim em minha luta, orando a Deus em meu favor.

[[v45-15-31]]

^<<v45-15-31,31>>^ Orem para que eu me livre dos que estão na Judeia e que se recusam a crer. Orem também para que o povo santo em Jerusalém se disponha a aceitar a oferta que estou levando.

[[v45-15-32]]

^<<v45-15-32,32>>^ Então, pela vontade de Deus, poderei visitar vocês com o coração alegre e teremos um tempo de descanso juntos.

[[v45-15-33]]

^<<v45-15-33,33>>^ Que o Deus que nos dá sua paz esteja com todos vocês. Amém.

'''

xref:045-romanos/045-romanos-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romanos/045-romanos-016.adoc#v45-16-0[Próximo Capítulo &#62;]