include::./index.adoc[]

[[v45-3-0]]
=== Romanos, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v45-3-1]]

^<<v45-3-1,1>>^ Então qual é a vantagem de ser judeu? A circuncisão tem algum valor?

[[v45-3-2]]

^<<v45-3-2,2>>^ Sim, há muitos benefícios. Em primeiro lugar, aos judeus foi confiada toda a revelação de Deus.

[[v45-3-3]]

^<<v45-3-3,3>>^ É verdade que alguns deles foram infiéis, mas isso significa que Deus será infiel?

[[v45-3-4]]

^<<v45-3-4,4>>^ De maneira nenhuma! Ainda que todos sejam mentirosos, Deus é verdadeiro. E as Escrituras dizem a seu respeito: "Será provado que tens razão no que dizes, e ganharás tua causa no juízo".

[[v45-3-5]]

^<<v45-3-5,5>>^ Alguém poderia dizer: "Mas nosso pecado não cumpre um bom propósito, ajudando os outros a verem como Deus é justo? Não é uma injustiça, portanto, Deus nos castigar?". (Estou seguindo o ponto de vista humano.)

[[v45-3-6]]

^<<v45-3-6,6>>^ Claro que não! Se fosse assim, como Deus poderia julgar o mundo?

[[v45-3-7]]

^<<v45-3-7,7>>^ Alguém poderia argumentar, ainda: "Mas por que Deus me condena como pecador se minha mentira ressalta sua verdade e lhe traz mais glória?".

[[v45-3-8]]

^<<v45-3-8,8>>^ E alguns até nos difamam, afirmando que dizemos: "Quanto mais pecarmos, melhor!". Quem diz essas coisas merece condenação.

[[v45-3-9]]

^<<v45-3-9,9>>^ Pois bem, devemos concluir que nós, judeus, somos melhores que os outros? Não, de maneira nenhuma, pois já mostramos que todos, judeus ou gentios, estão sob o poder do pecado.

[[v45-3-10]]

^<<v45-3-10,10>>^ Como afirmam as Escrituras: "Ninguém é justo, nem um sequer.

[[v45-3-11]]

^<<v45-3-11,11>>^ Ninguém é sábio, ninguém busca a Deus.

[[v45-3-12]]

^<<v45-3-12,12>>^ Todos se desviaram, todos se tornaram inúteis. Ninguém faz o bem, nem um sequer."

[[v45-3-13]]

^<<v45-3-13,13>>^ "Sua conversa é repulsiva, como o odor de um túmulo aberto; sua língua é cheia de mentiras." "Veneno de serpentes goteja de seus lábios."

[[v45-3-14]]

^<<v45-3-14,14>>^ "Sua boca é cheia de maldição e amargura."

[[v45-3-15]]

^<<v45-3-15,15>>^ "Apressam-se em cometer homicídio;

[[v45-3-16]]

^<<v45-3-16,16>>^ por onde passam, deixam destruição e sofrimento.

[[v45-3-17]]

^<<v45-3-17,17>>^ Não sabem onde encontrar paz."

[[v45-3-18]]

^<<v45-3-18,18>>^ "Não têm o menor temor de Deus."

[[v45-3-19]]

^<<v45-3-19,19>>^ É evidente que a lei se aplica àqueles a quem ela foi entregue, pois seu propósito é evitar desculpas e mostrar que todo o mundo é culpado diante de Deus.

[[v45-3-20]]

^<<v45-3-20,20>>^ Pois ninguém será declarado justo diante de Deus por fazer o que a lei ordena. A lei simplesmente mostra quanto somos pecadores.

[[v45-3-21]]

^<<v45-3-21,21>>^ Agora, porém, conforme prometido na lei de Moisés e nos profetas, Deus nos mostrou como somos declarados justos diante dele sem as exigências da lei:

[[v45-3-22]]

^<<v45-3-22,22>>^ somos declarados justos diante de Deus por meio da fé em Jesus Cristo, e isso se aplica a todos que creem, sem nenhuma distinção.

[[v45-3-23]]

^<<v45-3-23,23>>^ Pois todos pecaram e não alcançam o padrão da glória de Deus,

[[v45-3-24]]

^<<v45-3-24,24>>^ mas ele, em sua graça, nos declara justos por meio de Cristo Jesus, que nos resgatou do castigo por nossos pecados.

[[v45-3-25]]

^<<v45-3-25,25>>^ Deus apresentou Jesus como sacrifício pelo pecado, com o sangue que ele derramou, mostrando assim sua justiça em favor dos que creem. No passado ele se conteve e não castigou os pecados antes cometidos,

[[v45-3-26]]

^<<v45-3-26,26>>^ pois planejava revelar sua justiça no tempo presente. Com isso, Deus se mostrou justo, condenando o pecado, e justificador, declarando justo o pecador que crê em Jesus.

[[v45-3-27]]

^<<v45-3-27,27>>^ Podemos então nos vangloriar de ter feito algo para sermos aceitos por Deus? Não, pois nossa absolvição não vem pela obediência à lei, mas pela fé.

[[v45-3-28]]

^<<v45-3-28,28>>^ Portanto, somos declarados justos por meio da fé, e não pela obediência à lei.

[[v45-3-29]]

^<<v45-3-29,29>>^ Afinal, Deus é Deus apenas dos judeus? Não é também Deus dos gentios? Claro que sim!

[[v45-3-30]]

^<<v45-3-30,30>>^ Existe um só Deus, e ele declara justos tanto judeus como gentios somente pela fé.

[[v45-3-31]]

^<<v45-3-31,31>>^ Então, se enfatizamos a fé, quer dizer que podemos abolir a lei? Claro que não! Na realidade, é só quando temos fé que cumprimos verdadeiramente a lei.

'''

xref:045-romanos/045-romanos-002.adoc#v45-2-0[&#60; Capítulo Anterior] | <<v45-3-0,Topo>> | xref:045-romanos/045-romanos-004.adoc#v45-4-0[Próximo Capítulo &#62;]