include::./index.adoc[]

[[v45-6-0]]
=== Romanos, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v45-6-1]]

^<<v45-6-1,1>>^ Pois bem, devemos continuar pecando para que Deus mostre cada vez mais sua graça?

[[v45-6-2]]

^<<v45-6-2,2>>^ Claro que não! Uma vez que morremos para o pecado, como podemos continuar vivendo nele?

[[v45-6-3]]

^<<v45-6-3,3>>^ Ou acaso se esqueceram de que, quando fomos unidos a Cristo Jesus no batismo, nos unimos a ele em sua morte?

[[v45-6-4]]

^<<v45-6-4,4>>^ Pois, pelo batismo, morremos e fomos sepultados com Cristo. E, assim como ele foi ressuscitado dos mortos pelo poder glorioso do Pai, agora nós também podemos viver uma nova vida.

[[v45-6-5]]

^<<v45-6-5,5>>^ Uma vez que nossa união com ele se assemelhou à sua morte, assim também nossa ressurreição será semelhante à dele.

[[v45-6-6]]

^<<v45-6-6,6>>^ Sabemos que nossa velha natureza humana foi crucificada com Cristo, para que o pecado não tivesse mais poder sobre nossa vida e dele deixássemos de ser escravos.

[[v45-6-7]]

^<<v45-6-7,7>>^ Pois, quando morremos com Cristo, fomos libertos do poder do pecado.

[[v45-6-8]]

^<<v45-6-8,8>>^ Então, uma vez que morremos com Cristo, cremos que também com ele viveremos.

[[v45-6-9]]

^<<v45-6-9,9>>^ Temos certeza disso, pois Cristo foi ressuscitado dos mortos e não mais morrerá. A morte já não tem nenhum poder sobre ele.

[[v45-6-10]]

^<<v45-6-10,10>>^ Quando ele morreu, foi de uma vez por todas, para quebrar o poder do pecado. Mas agora que ele vive, é para a glória de Deus.

[[v45-6-11]]

^<<v45-6-11,11>>^ Da mesma forma, considerem-se mortos para o poder do pecado e vivos para Deus em Cristo Jesus.

[[v45-6-12]]

^<<v45-6-12,12>>^ Não deixem que o pecado reine sobre seu corpo, que está sujeito à morte, cedendo aos desejos pecaminosos.

[[v45-6-13]]

^<<v45-6-13,13>>^ Não deixem que nenhuma parte de seu corpo se torne instrumento do mal para servir ao pecado, mas em vez disso entreguem-se inteiramente a Deus, pois vocês estavam mortos e agora têm nova vida. Portanto, ofereçam seu corpo como instrumento para fazer o que é certo para a glória de Deus.

[[v45-6-14]]

^<<v45-6-14,14>>^ O pecado não é mais seu senhor, pois vocês já não vivem sob a lei, mas sob a graça de Deus.

[[v45-6-15]]

^<<v45-6-15,15>>^ Pois bem, uma vez que a graça nos libertou da lei, quer dizer que podemos continuar pecando? Claro que não!

[[v45-6-16]]

^<<v45-6-16,16>>^ Vocês não sabem que se tornam escravos daquilo a que escolhem obedecer? Podem ser escravos do pecado, que conduz à morte, ou podem escolher obedecer a Deus, que conduz à vida de justiça.

[[v45-6-17]]

^<<v45-6-17,17>>^ Graças a Deus, porque antes vocês eram escravos do pecado, mas agora obedecem de todo o coração a este ensino que lhes transmitimos.

[[v45-6-18]]

^<<v45-6-18,18>>^ Estão livres da escravidão do pecado e se tornaram escravos da justiça.

[[v45-6-19]]

^<<v45-6-19,19>>^ Uso o exemplo da escravidão para ajudá-los a entender isso tudo, pois sua natureza humana é fraca. No passado, vocês se deixaram escravizar pela impureza e pela maldade, o que os fez afundar ainda mais no pecado. Agora, devem se entregar como escravos à vida de justiça, para que se tornem santos.

[[v45-6-20]]

^<<v45-6-20,20>>^ Quando eram escravos do pecado, estavam livres da obrigação de fazer o que é certo.

[[v45-6-21]]

^<<v45-6-21,21>>^ E qual foi o resultado? Hoje vocês se envergonham das coisas que costumavam fazer, coisas que acabam em morte.

[[v45-6-22]]

^<<v45-6-22,22>>^ Agora, porém, estão livres do poder do pecado e se tornaram escravos de Deus. Fazem aquilo que conduz à santidade e resulta na vida eterna.

[[v45-6-23]]

^<<v45-6-23,23>>^ Pois o salário do pecado é a morte, mas a dádiva de Deus é a vida eterna em Cristo Jesus, nosso Senhor.

'''

xref:045-romanos/045-romanos-005.adoc#v45-5-0[&#60; Capítulo Anterior] | <<v45-6-0,Topo>> | xref:045-romanos/045-romanos-007.adoc#v45-7-0[Próximo Capítulo &#62;]