include::./index.adoc[]

[[v52-5-0]]
=== 1 Tessalonicenses, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v52-5-1]]

^<<v52-5-1,1>>^ Não é necessário, irmãos, que eu lhes escreva sobre quando e como tudo isso acontecerá,

[[v52-5-2]]

^<<v52-5-2,2>>^ pois vocês sabem muito bem que o dia do Senhor virá inesperadamente, como ladrão à noite.

[[v52-5-3]]

^<<v52-5-3,3>>^ Quando as pessoas disserem: "Tudo está em paz e seguro", então o desastre lhes sobrevirá tão repentinamente como iniciam as dores de parto de uma mulher grávida, e não haverá como escapar.

[[v52-5-4]]

^<<v52-5-4,4>>^ Mas vocês, irmãos, não estão na escuridão a respeito dessas coisas e não devem se surpreender quando o dia do Senhor vier como ladrão.

[[v52-5-5]]

^<<v52-5-5,5>>^ Porque todos vocês são filhos da luz e do dia. Não pertencemos à escuridão e à noite.

[[v52-5-6]]

^<<v52-5-6,6>>^ Portanto, fiquem atentos; não durmam como os outros. Permaneçam atentos e sejam sóbrios.

[[v52-5-7]]

^<<v52-5-7,7>>^ À noite, as pessoas dormem e os bêbados se embriagam.

[[v52-5-8]]

^<<v52-5-8,8>>^ Mas nós, que vivemos na luz, devemos ser sóbrios, protegidos pela armadura da fé e do amor, usando o capacete da esperança da salvação.

[[v52-5-9]]

^<<v52-5-9,9>>^ Porque Deus decidiu nos salvar por meio de nosso Senhor Jesus Cristo, em vez de derramar sua ira sobre nós.

[[v52-5-10]]

^<<v52-5-10,10>>^ Cristo morreu por nós para que, quer estejamos despertos, quer dormindo, vivamos com ele para sempre.

[[v52-5-11]]

^<<v52-5-11,11>>^ Portanto, animem e edifiquem uns aos outros, como têm feito.

[[v52-5-12]]

^<<v52-5-12,12>>^ Irmãos, honrem seus líderes na obra do Senhor. Eles trabalham arduamente entre vocês e lhes dão orientações.

[[v52-5-13]]

^<<v52-5-13,13>>^ Tenham grande respeito e amor sincero por eles, por causa do trabalho que realizam. E vivam em paz uns com os outros.

[[v52-5-14]]

^<<v52-5-14,14>>^ Irmãos, pedimos que advirtam os indisciplinados. Encorajem os desanimados. Ajudem os fracos. Sejam pacientes com todos.

[[v52-5-15]]

^<<v52-5-15,15>>^ Cuidem que ninguém retribua o mal com o mal, mas procurem sempre fazer o bem uns aos outros e a todos.

[[v52-5-16]]

^<<v52-5-16,16>>^ Estejam sempre alegres.

[[v52-5-17]]

^<<v52-5-17,17>>^ Nunca deixem de orar.

[[v52-5-18]]

^<<v52-5-18,18>>^ Sejam gratos em todas as circunstâncias, pois essa é a vontade de Deus para vocês em Cristo Jesus.

[[v52-5-19]]

^<<v52-5-19,19>>^ Não apaguem o Espírito.

[[v52-5-20]]

^<<v52-5-20,20>>^ Não desprezem as profecias,

[[v52-5-21]]

^<<v52-5-21,21>>^ mas ponham à prova tudo que é dito e fiquem com o que é bom.

[[v52-5-22]]

^<<v52-5-22,22>>^ Mantenham-se afastados de toda forma de mal.

[[v52-5-23]]

^<<v52-5-23,23>>^ E, agora, que o Deus da paz os torne santos em todos os aspectos, e que o espírito, a alma e o corpo de vocês sejam mantidos irrepreensíveis até a volta de nosso Senhor Jesus Cristo.

[[v52-5-24]]

^<<v52-5-24,24>>^ Aquele que os chama fará isso acontecer, pois ele é fiel.

[[v52-5-25]]

^<<v52-5-25,25>>^ Irmãos, orem por nós.

[[v52-5-26]]

^<<v52-5-26,26>>^ Cumprimentem todos os irmãos com beijo santo.

[[v52-5-27]]

^<<v52-5-27,27>>^ Encarrego-os em nome do Senhor de lerem esta carta a todos os irmãos.

[[v52-5-28]]

^<<v52-5-28,28>>^ Que a graça de nosso Senhor Jesus Cristo esteja com vocês.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[&#60; Capítulo Anterior] | <<v52-5-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[Próximo Capítulo &#62;]