include::./index.adoc[]

[[v52-4-0]]
=== 1 Tessalonicenses, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v52-4-1]]

^<<v52-4-1,1>>^ Finalmente, irmãos, pedimos e incentivamos em nome do Senhor Jesus que vivam para agradar a Deus, conforme lhes instruímos. Vocês já vivem desse modo, e os incentivamos a fazê-lo ainda mais,

[[v52-4-2]]

^<<v52-4-2,2>>^ pois se lembram das instruções que lhes demos pela autoridade do Senhor Jesus.

[[v52-4-3]]

^<<v52-4-3,3>>^ A vontade de Deus é que vocês vivam em santidade; por isso, mantenham-se afastados de todo pecado sexual.

[[v52-4-4]]

^<<v52-4-4,4>>^ Cada um deve aprender a controlar o próprio corpo e assim viver em santidade e honra,

[[v52-4-5]]

^<<v52-4-5,5>>^ não em paixões sensuais, como os gentios que não conhecem a Deus.

[[v52-4-6]]

^<<v52-4-6,6>>^ Nesse assunto, não prejudiquem nem enganem um irmão, pois o Senhor punirá todas essas práticas, como já os advertimos solenemente.

[[v52-4-7]]

^<<v52-4-7,7>>^ Pois Deus nos chamou para uma vida santa, e não impura.

[[v52-4-8]]

^<<v52-4-8,8>>^ Portanto, quem se recusa a viver de acordo com essas regras não desobedece a ensinamentos humanos, mas rejeita a Deus, que lhes dá seu Espírito Santo.

[[v52-4-9]]

^<<v52-4-9,9>>^ Não precisamos lhes escrever sobre a importância do amor fraternal, pois o próprio Deus os ensinou a amarem uns aos outros.

[[v52-4-10]]

^<<v52-4-10,10>>^ De fato, vocês já demonstram amor por todos os irmãos em toda a Macedônia. Ainda assim, irmãos, pedimos que os amem ainda mais.

[[v52-4-11]]

^<<v52-4-11,11>>^ Tenham como objetivo uma vida tranquila, ocupando-se com seus próprios assuntos e trabalhando com suas próprias mãos, conforme os instruímos anteriormente.

[[v52-4-12]]

^<<v52-4-12,12>>^ Assim, os que são de fora respeitarão seu modo de viver, e vocês não terão de depender de outros.

[[v52-4-13]]

^<<v52-4-13,13>>^ Agora, irmãos, não queremos que ignorem o que acontecerá aos que já morreram, para que não se entristeçam como aqueles que não têm esperança.

[[v52-4-14]]

^<<v52-4-14,14>>^ Porque cremos que Jesus morreu e foi ressuscitado, também cremos que Deus trará de volta à vida, com Jesus, todos os que morreram.

[[v52-4-15]]

^<<v52-4-15,15>>^ Dizemos a vocês, pela palavra do Senhor: nós, os que ainda estivermos vivos quando o Senhor voltar, não iremos ao encontro dele antes daqueles que já morreram.

[[v52-4-16]]

^<<v52-4-16,16>>^ Pois o Senhor mesmo descerá do céu com um brado de comando, com a voz do arcanjo e com o toque da trombeta de Deus. Primeiro, os mortos em Cristo ressuscitarão.

[[v52-4-17]]

^<<v52-4-17,17>>^ Depois, com eles, nós, os que ainda estivermos vivos, seremos arrebatados nas nuvens ao encontro do Senhor, nos ares. Então, estaremos com o Senhor para sempre.

[[v52-4-18]]

^<<v52-4-18,18>>^ Portanto, animem uns aos outros com essas palavras.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[&#60; Capítulo Anterior] | <<v52-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[Próximo Capítulo &#62;]