include::./index.adoc[]

[[v52-2-0]]
=== 1 Tessalonicenses, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v52-2-1]]

^<<v52-2-1,1>>^ Vocês mesmos sabem, irmãos, que a visita que lhes fizemos não foi inútil.

[[v52-2-2]]

^<<v52-2-2,2>>^ Sabem como fomos maltratados e quanto sofremos em Filipos, antes de chegarmos aí. E, no entanto, com confiança em nosso Deus, anunciamos a vocês as boas-novas de Deus, apesar de grande oposição.

[[v52-2-3]]

^<<v52-2-3,3>>^ Portanto, como veem, não pregamos com a intenção de enganá-los, nem com motivos impuros, nem com artimanhas.

[[v52-2-4]]

^<<v52-2-4,4>>^ Em vez disso, falamos como mensageiros aprovados por Deus, aos quais foram confiadas as boas-novas. Nosso propósito não é agradar as pessoas, mas a Deus, que examina as intenções de nosso coração.

[[v52-2-5]]

^<<v52-2-5,5>>^ Como bem sabem, nunca tentamos conquistá-los com bajulação, e Deus é nossa testemunha de que não agimos motivados pela ganância.

[[v52-2-6]]

^<<v52-2-6,6>>^ Quanto ao reconhecimento humano, nunca o buscamos de vocês, nem de nenhum outro.

[[v52-2-7]]

^<<v52-2-7,7>>^ Ainda que, como apóstolos de Cristo, tivéssemos o direito de fazer certas exigências, agimos como crianças entre vocês. Ou melhor, fomos como a mãe que alimenta os filhos e deles cuida.

[[v52-2-8]]

^<<v52-2-8,8>>^ Nós os amamos tanto que compartilhamos com vocês não apenas as boas-novas de Deus, mas também nossa própria vida.

[[v52-2-9]]

^<<v52-2-9,9>>^ Não se lembram, irmãos, de como trabalhamos arduamente entre vocês? Noite e dia nos esforçamos para obter sustento, a fim de não sermos um peso para ninguém enquanto lhes anunciávamos as boas-novas de Deus.

[[v52-2-10]]

^<<v52-2-10,10>>^ Vocês mesmos são nossas testemunhas, e Deus também é, de que fomos dedicados, honestos e irrepreensíveis com todos vocês, os que creem.

[[v52-2-11]]

^<<v52-2-11,11>>^ E sabem que tratamos a cada um como um pai trata seus filhos.

[[v52-2-12]]

^<<v52-2-12,12>>^ Aconselhamos, incentivamos e insistimos para que vivam de modo que Deus considere digno, pois ele os chamou para terem parte em seu reino e em sua glória.

[[v52-2-13]]

^<<v52-2-13,13>>^ Portanto, nunca deixamos de agradecer a Deus, pois, quando vocês receberam de nós a mensagem dele, não consideraram nossas palavras meras ideias humanas, mas as aceitaram como palavra de Deus, o que sem dúvida são. E essa mensagem continua a atuar em vocês, os que creem.

[[v52-2-14]]

^<<v52-2-14,14>>^ E então, irmãos, vocês foram perseguidos por seus próprios compatriotas, tornando-se assim imitadores das igrejas de Deus em Cristo Jesus na Judeia, que também sofreram nas mãos de seu próprio povo, os judeus.

[[v52-2-15]]

^<<v52-2-15,15>>^ Eles mataram o Senhor Jesus e os profetas, e agora também nos perseguem. Não agradam a Deus e trabalham contra toda a humanidade,

[[v52-2-16]]

^<<v52-2-16,16>>^ procurando impedir-nos de anunciar a salvação aos gentios. Com isso, continuam a acumular pecados, mas a ira de Deus finalmente os alcançou.

[[v52-2-17]]

^<<v52-2-17,17>>^ Irmãos, depois de um breve tempo separados de vocês, embora nosso coração nunca os tenha deixado, esforçamo-nos por voltar a vê-los, pela grande saudade que sentimos.

[[v52-2-18]]

^<<v52-2-18,18>>^ Queríamos muito visitá-los, e eu, Paulo, tentei não apenas uma vez, mas duas; Satanás, porém, nos impediu.

[[v52-2-19]]

^<<v52-2-19,19>>^ Afinal, o que nos dá esperança e alegria? E qual será nossa magnífica recompensa e coroa diante do Senhor Jesus quando ele voltar? Serão vocês!

[[v52-2-20]]

^<<v52-2-20,20>>^ Sim, vocês são nosso orgulho e nossa alegria.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[&#60; Capítulo Anterior] | <<v52-2-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[Próximo Capítulo &#62;]