include::./index.adoc[]

[[v52-1-0]]
=== 1 Tessalonicenses, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v52-1-1]]

^<<v52-1-1,1>>^ Nós, Paulo, Silas e Timóteo, escrevemos esta carta à igreja em Tessalônica, a vocês que estão em Deus, o Pai, e no Senhor Jesus Cristo. Que Deus lhes dê graça e paz.

[[v52-1-2]]

^<<v52-1-2,2>>^ Sempre damos graças a Deus por todos vocês e os mencionamos constantemente em nossas orações.

[[v52-1-3]]

^<<v52-1-3,3>>^ Quando oramos por vocês diante de nosso Deus e Pai, relembramos seu trabalho fiel, seus atos em amor e sua firme esperança em nosso Senhor Jesus Cristo.

[[v52-1-4]]

^<<v52-1-4,4>>^ Sabemos, irmãos, que Deus os ama e os escolheu.

[[v52-1-5]]

^<<v52-1-5,5>>^ Pois, quando lhes apresentamos as boas-novas, não o fizemos apenas com palavras, mas também com poder, visto que o Espírito Santo lhes deu plena certeza de que era verdade o que lhes dizíamos. E vocês sabem como nos comportamos entre vocês e em seu favor.

[[v52-1-6]]

^<<v52-1-6,6>>^ Assim, apesar do sofrimento que isso lhes trouxe, vocês receberam a mensagem com a alegria que vem do Espírito Santo e se tornaram imitadores nossos e do Senhor.

[[v52-1-7]]

^<<v52-1-7,7>>^ Com isso, tornaram-se exemplo para todos os irmãos na Grécia, tanto na Macedônia como na Acaia.

[[v52-1-8]]

^<<v52-1-8,8>>^ Agora, partindo de vocês, a palavra do Senhor tem se espalhado por toda parte, até mesmo além da Macedônia e da Acaia, pois sua fé em Deus se tornou conhecida em todo lugar. Não precisamos sequer mencioná-la,

[[v52-1-9]]

^<<v52-1-9,9>>^ pois as pessoas têm comentado sobre como vocês nos acolheram e como deixaram os ídolos a fim de servir ao Deus vivo e verdadeiro.

[[v52-1-10]]

^<<v52-1-10,10>>^ Também comentam como vocês esperam do céu a vinda de Jesus, o Filho de Deus, a quem ele ressuscitou dos mortos e que nos livrará da ira que está para vir.

'''

xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[&#60; Capítulo Anterior] | <<v52-1-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[Próximo Capítulo &#62;]