include::./index.adoc[]

[[v18-22-0]]
=== Jó, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v18-22-1]]

^<<v18-22-1,1>>^ Então Elifaz, de Temã, respondeu:

[[v18-22-2]]

^<<v18-22-2,2>>^ "Pode alguém fazer algo para ajudar a Deus? Pode alguém, ainda que sábio, lhe ser útil?

[[v18-22-3]]

^<<v18-22-3,3>>^ Que vantagem há para o Todo-poderoso em você ser justo? Ele ganharia alguma coisa se você fosse perfeito?

[[v18-22-4]]

^<<v18-22-4,4>>^ É por causa de seu temor que ele o acusa e traz juízo contra você?

[[v18-22-5]]

^<<v18-22-5,5>>^ Não! É por causa de sua perversidade; seus pecados não têm limites!

[[v18-22-6]]

^<<v18-22-6,6>>^ "Por certo você emprestou dinheiro a seu amigo e exigiu roupas dele como garantia; sim, você o deixou sem ter o que vestir.

[[v18-22-7]]

^<<v18-22-7,7>>^ Recusou-se a dar água ao sedento e comida ao faminto.

[[v18-22-8]]

^<<v18-22-8,8>>^ Pensou que a terra pertencia aos poderosos e que somente os privilegiados tinham direito a ela.

[[v18-22-9]]

^<<v18-22-9,9>>^ Mandou a viúva embora de mãos vazias e acabou com as esperanças dos órfãos.

[[v18-22-10]]

^<<v18-22-10,10>>^ Por isso está cercado de armadilhas e estremece com temores repentinos.

[[v18-22-11]]

^<<v18-22-11,11>>^ Por isso está em trevas e não consegue ver, e ondas de águas o cobrem.

[[v18-22-12]]

^<<v18-22-12,12>>^ "Deus é grande, mais alto que os céus, mais alto que as estrelas mais distantes.

[[v18-22-13]]

^<<v18-22-13,13>>^ Você, porém, responde: ‘Por isso Deus não vê o que faço! Como pode julgar através da densa escuridão?

[[v18-22-14]]

^<<v18-22-14,14>>^ Nuvens espessas se movem ao seu redor, e ele não pode nos ver; está lá no alto, caminhando pela abóbada do céu!’.

[[v18-22-15]]

^<<v18-22-15,15>>^ "Você continuará nos velhos caminhos, nos quais sempre andaram os perversos?

[[v18-22-16]]

^<<v18-22-16,16>>^ Eles foram levados embora em tenra idade; os alicerces de sua vida foram arrastados pela correnteza.

[[v18-22-17]]

^<<v18-22-17,17>>^ Pois disseram a Deus: ‘Deixa-nos em paz! O que o Todo-poderoso pode fazer conosco?’.

[[v18-22-18]]

^<<v18-22-18,18>>^ E, no entanto, foi ele que lhes encheu o lar de coisas boas; por isso quero distância desse modo de pensar.

[[v18-22-19]]

^<<v18-22-19,19>>^ "Os justos se alegrarão ao ver a destruição dos perversos, e, com desprezo, os inocentes zombarão deles.

[[v18-22-20]]

^<<v18-22-20,20>>^ Dirão: ‘Vejam, nossos inimigos foram destruídos, e suas riquezas, consumidas pelo fogo’.

[[v18-22-21]]

^<<v18-22-21,21>>^ "Sujeite-se a Deus, e terá paz; então as coisas lhe irão bem.

[[v18-22-22]]

^<<v18-22-22,22>>^ Ouça as instruções de Deus e guarde-as no coração.

[[v18-22-23]]

^<<v18-22-23,23>>^ Se voltar para o Todo-poderoso, será restaurado; portanto, coloque sua vida em ordem.

[[v18-22-24]]

^<<v18-22-24,24>>^ Se abrir mão de sua cobiça por dinheiro e lançar no rio seu ouro precioso,

[[v18-22-25]]

^<<v18-22-25,25>>^ o Todo-poderoso será seu tesouro; ele será sua prata de grande valor!

[[v18-22-26]]

^<<v18-22-26,26>>^ "Então você se alegrará no Todo-poderoso e levantará os olhos para ele.

[[v18-22-27]]

^<<v18-22-27,27>>^ Orará a Deus, e ele o ouvirá, e você cumprirá seus votos.

[[v18-22-28]]

^<<v18-22-28,28>>^ Será bem-sucedido em tudo que decidir fazer, e a luz brilhará em seu caminho.

[[v18-22-29]]

^<<v18-22-29,29>>^ Se outros estiverem em dificuldade e você disser: ‘Ajuda-os’, Deus os salvará.

[[v18-22-30]]

^<<v18-22-30,30>>^ Até mesmo pecadores serão resgatados; sim, serão resgatados porque você tem mãos puras".

'''

xref:018-jo/018-jo-021.adoc#v18-21-0[&#60; Capítulo Anterior] | <<v18-22-0,Topo>> | xref:018-jo/018-jo-023.adoc#v18-23-0[Próximo Capítulo &#62;]