include::./index.adoc[]

[[v18-37-0]]
=== Jó, 37
// nvt ?, NVT - Nova Versão Transformadora

[[v18-37-1]]

^<<v18-37-1,1>>^ "Quando penso nisso, meu coração bate mais depressa e estremece dentro de mim.

[[v18-37-2]]

^<<v18-37-2,2>>^ Ouça com atenção o estrondo da voz de Deus, que da boca dele troveja.

[[v18-37-3]]

^<<v18-37-3,3>>^ Ressoa pelo céu, e seus relâmpagos brilham em todas as direções.

[[v18-37-4]]

^<<v18-37-4,4>>^ Depois vem o rugido de trovões, a voz tremenda de sua majestade; quando ele fala, não a refreia.

[[v18-37-5]]

^<<v18-37-5,5>>^ A voz de Deus é gloriosa no trovão; é impossível imaginar a grandeza de seu poder!

[[v18-37-6]]

^<<v18-37-6,6>>^ "Ele diz à neve: ‘Venha sobre a terra!’, e ordena à chuva: ‘Caia em torrentes!’.

[[v18-37-7]]

^<<v18-37-7,7>>^ Todos param de trabalhar, a fim de observar seu poder.

[[v18-37-8]]

^<<v18-37-8,8>>^ Os animais selvagens buscam abrigo e ficam em suas tocas.

[[v18-37-9]]

^<<v18-37-9,9>>^ A tempestade sai de seus aposentos, e ventos fortes trazem o frio.

[[v18-37-10]]

^<<v18-37-10,10>>^ O sopro de Deus envia o gelo e congela grandes extensões de água.

[[v18-37-11]]

^<<v18-37-11,11>>^ Ele carrega de umidade as nuvens e espalha entre elas seus relâmpagos.

[[v18-37-12]]

^<<v18-37-12,12>>^ As nuvens se agitam sob sua direção e cumprem suas ordens sobre toda a terra.

[[v18-37-13]]

^<<v18-37-13,13>>^ Deus faz tudo isso para castigar as pessoas, ou para mostrar seu amor.

[[v18-37-14]]

^<<v18-37-14,14>>^ "Preste atenção, Jó! Pare e pense nos feitos maravilhosos de Deus!

[[v18-37-15]]

^<<v18-37-15,15>>^ Você sabe como Deus controla a tempestade e faz os relâmpagos brilharem nas nuvens?

[[v18-37-16]]

^<<v18-37-16,16>>^ Você entende como ele move as nuvens com perfeição e conhecimento maravilhosos?

[[v18-37-17]]

^<<v18-37-17,17>>^ Enquanto você fica sufocado de calor em sua roupa, e o vento sul perde a força e tudo se acalma,

[[v18-37-18]]

^<<v18-37-18,18>>^ ele faz o céu refletir o calor como um espelho de bronze; acaso você pode fazer o mesmo?

[[v18-37-19]]

^<<v18-37-19,19>>^ "Ensina-nos, então, o que dizer a Deus; somos ignorantes demais para apresentar nossos argumentos.

[[v18-37-20]]

^<<v18-37-20,20>>^ Deus deve ser avisado de que desejo falar? É possível falar quando se está confuso?

[[v18-37-21]]

^<<v18-37-21,21>>^ Não podemos olhar para o sol, pois ele brilha intensamente no céu, quando o vento dispersa as nuvens.

[[v18-37-22]]

^<<v18-37-22,22>>^ Da mesma forma, dourado esplendor vem do monte de Deus; ele está vestido de tremenda majestade.

[[v18-37-23]]

^<<v18-37-23,23>>^ O Todo-poderoso está além de nossa compreensão; apesar de seu grande poder, a ninguém oprime em sua justiça e retidão.

[[v18-37-24]]

^<<v18-37-24,24>>^ Por isso em toda parte as pessoas o temem; todos os sábios lhe mostram devoção".

'''

xref:018-jo/018-jo-036.adoc#v18-36-0[&#60; Capítulo Anterior] | <<v18-37-0,Topo>> | xref:018-jo/018-jo-038.adoc#v18-38-0[Próximo Capítulo &#62;]