include::./index.adoc[]

[[v18-23-0]]
=== Jó, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v18-23-1]]

^<<v18-23-1,1>>^ Então Jó falou novamente:

[[v18-23-2]]

^<<v18-23-2,2>>^ "Minha queixa hoje ainda é amarga, e me esforço para não gemer.

[[v18-23-3]]

^<<v18-23-3,3>>^ Se ao menos eu soubesse onde encontrar a Deus, iria a seu tribunal.

[[v18-23-4]]

^<<v18-23-4,4>>^ Exporia minha causa e apresentaria meus argumentos.

[[v18-23-5]]

^<<v18-23-5,5>>^ Ouviria sua resposta e entenderia o que ele me dissesse.

[[v18-23-6]]

^<<v18-23-6,6>>^ Acaso ele usaria seu grande poder para discutir comigo? Não! Ele me ouviria com imparcialidade.

[[v18-23-7]]

^<<v18-23-7,7>>^ Os justos podem lhe apresentar sua causa; meu Juiz me absolveria de uma vez por todas.

[[v18-23-8]]

^<<v18-23-8,8>>^ Se vou para o leste, lá ele não está; sigo para o oeste, mas não consigo encontrá-lo.

[[v18-23-9]]

^<<v18-23-9,9>>^ Não o vejo no norte, pois está escondido; quando olho para o sul, ele está oculto.

[[v18-23-10]]

^<<v18-23-10,10>>^ "E, no entanto, ele sabe aonde vou; quando ele me provar, sairei puro como o ouro.

[[v18-23-11]]

^<<v18-23-11,11>>^ Pois permaneci nos caminhos de Deus; segui seus passos e nunca me desviei.

[[v18-23-12]]

^<<v18-23-12,12>>^ Não me afastei de seus mandamentos; dei mais valor a suas palavras que ao alimento diário.

[[v18-23-13]]

^<<v18-23-13,13>>^ Mas, quando ele toma sua decisão, quem pode fazê-lo mudar de ideia? Ele faz o que bem deseja.

[[v18-23-14]]

^<<v18-23-14,14>>^ Portanto, fará comigo tudo que planejou; ele controla meu destino.

[[v18-23-15]]

^<<v18-23-15,15>>^ Não é de admirar que eu me apavore em sua presença; quando penso nisso, entro em pânico.

[[v18-23-16]]

^<<v18-23-16,16>>^ Deus fez meu coração desfalecer; o Todo-poderoso me encheu de medo.

[[v18-23-17]]

^<<v18-23-17,17>>^ A escuridão me cerca; há trevas densas e impenetráveis por toda parte."

'''

xref:018-jo/018-jo-022.adoc#v18-22-0[&#60; Capítulo Anterior] | <<v18-23-0,Topo>> | xref:018-jo/018-jo-024.adoc#v18-24-0[Próximo Capítulo &#62;]