include::./index.adoc[]

[[v18-31-0]]
=== Jó, 31
// nvt ?, NVT - Nova Versão Transformadora

[[v18-31-1]]

^<<v18-31-1,1>>^ "Fiz uma aliança com meus olhos de não olhar com cobiça para nenhuma jovem.

[[v18-31-2]]

^<<v18-31-2,2>>^ Pois o que Deus, lá de cima, escolheu para nós? Qual é nossa herança do Todo-poderoso, que está lá no alto?

[[v18-31-3]]

^<<v18-31-3,3>>^ Não é calamidade para os perversos e desgraça para os que praticam o mal?

[[v18-31-4]]

^<<v18-31-4,4>>^ Afinal, ele não vê tudo que faço e cada passo que dou?

[[v18-31-5]]

^<<v18-31-5,5>>^ "Se minha conduta foi falsa, e se procurei enganar alguém,

[[v18-31-6]]

^<<v18-31-6,6>>^ que Deus me pese numa balança justa, pois conhecerá minha integridade.

[[v18-31-7]]

^<<v18-31-7,7>>^ Se me desviei de seu caminho, se meu coração cobiçou o que os olhos viram, ou se sou culpado de algum outro pecado,

[[v18-31-8]]

^<<v18-31-8,8>>^ que outros comam o que semeei; que minhas plantações sejam arrancadas pela raiz.

[[v18-31-9]]

^<<v18-31-9,9>>^ "Se meu coração foi seduzido por uma mulher, ou se cobicei a esposa de meu próximo,

[[v18-31-10]]

^<<v18-31-10,10>>^ que minha esposa se torne serva de outro homem; que outros durmam com ela.

[[v18-31-11]]

^<<v18-31-11,11>>^ Pois a cobiça é um pecado vergonhoso, um crime que merece castigo.

[[v18-31-12]]

^<<v18-31-12,12>>^ É fogo que tudo consome, levando à destruição, capaz de destruir tudo que tenho.

[[v18-31-13]]

^<<v18-31-13,13>>^ "Se fui injusto com meus servos e servas quando me apresentaram suas queixas,

[[v18-31-14]]

^<<v18-31-14,14>>^ que farei quando Deus me confrontar? Que direi quando ele me chamar para prestar contas?

[[v18-31-15]]

^<<v18-31-15,15>>^ Pois o mesmo Deus que me criou, também criou meus servos; formou no ventre materno tanto eles como eu.

[[v18-31-16]]

^<<v18-31-16,16>>^ "Acaso me recusei a ajudar os pobres ou acabei com a esperança da viúva?

[[v18-31-17]]

^<<v18-31-17,17>>^ Fui mesquinho com meu alimento e me recusei a compartilhá-lo com os órfãos?

[[v18-31-18]]

^<<v18-31-18,18>>^ Não! Desde a juventude, tenho cuidado dos órfãos como um pai e, por toda a vida, tenho ajudado as viúvas.

[[v18-31-19]]

^<<v18-31-19,19>>^ Sempre que via alguém passar frio por falta de roupa, e o pobre que não tinha o que vestir,

[[v18-31-20]]

^<<v18-31-20,20>>^ acaso eles não me abençoavam por lhes prover roupas de lã para aquecê-los?

[[v18-31-21]]

^<<v18-31-21,21>>^ "Se levantei a mão contra o órfão, certo de que os juízes tomariam meu partido,

[[v18-31-22]]

^<<v18-31-22,22>>^ que meu ombro seja deslocado e meu braço, arrancado da articulação!

[[v18-31-23]]

^<<v18-31-23,23>>^ Seria melhor que enfrentar o castigo de Deus; pois, se a majestade de Deus é contra mim, que esperança resta?

[[v18-31-24]]

^<<v18-31-24,24>>^ "Acaso confiei no dinheiro ou me senti seguro por causa de meu ouro?

[[v18-31-25]]

^<<v18-31-25,25>>^ Acaso me vangloriei de minha riqueza e de tudo que possuo?

[[v18-31-26]]

^<<v18-31-26,26>>^ "Olhei para o sol, que brilha no céu, ou para a lua, que percorre seu resplendor,

[[v18-31-27]]

^<<v18-31-27,27>>^ e, em segredo, meu coração foi seduzido a lhes lançar beijos de adoração?

[[v18-31-28]]

^<<v18-31-28,28>>^ Se o fiz, devo ser castigado pelos juízes, pois significa que neguei o Deus que está lá no alto.

[[v18-31-29]]

^<<v18-31-29,29>>^ "Alguma vez me alegrei com a desgraça de meus inimigos, ou exultei porque lhes aconteceu algum mal?

[[v18-31-30]]

^<<v18-31-30,30>>^ Não, jamais cometi o pecado de amaldiçoar alguém ou de pedir sua morte como vingança.

[[v18-31-31]]

^<<v18-31-31,31>>^ "Meus servos nunca disseram: ‘Ele deixa os outros passar fome’.

[[v18-31-32]]

^<<v18-31-32,32>>^ Nunca deixei o estrangeiro dormir na rua; minha porta sempre esteve aberta para todos.

[[v18-31-33]]

^<<v18-31-33,33>>^ "Acaso procurei encobrir meus pecados, como outros fazem, e esconder a culpa em meu coração?

[[v18-31-34]]

^<<v18-31-34,34>>^ Mantive-me calado e não saí de casa, por medo da multidão ou do desprezo do povo?

[[v18-31-35]]

^<<v18-31-35,35>>^ "Se ao menos alguém me ouvisse! Vejam, aqui está minha defesa assinada. Que o Todo-poderoso me responda; que meu adversário registre sua denúncia por escrito.

[[v18-31-36]]

^<<v18-31-36,36>>^ Eu enfrentaria a acusação de peito aberto e a usaria como coroa.

[[v18-31-37]]

^<<v18-31-37,37>>^ Pois eu diria a Deus exatamente o que tenho feito; compareceria diante dele como um príncipe.

[[v18-31-38]]

^<<v18-31-38,38>>^ "Se a terra protestar contra mim, se todos os seus sulcos clamarem,

[[v18-31-39]]

^<<v18-31-39,39>>^ se roubei suas colheitas, ou se matei seus donos,

[[v18-31-40]]

^<<v18-31-40,40>>^ que cresçam espinhos em lugar de trigo e ervas daninhas em lugar de cevada". Assim terminam as palavras de Jó.

'''

xref:018-jo/018-jo-030.adoc#v18-30-0[&#60; Capítulo Anterior] | <<v18-31-0,Topo>> | xref:018-jo/018-jo-032.adoc#v18-32-0[Próximo Capítulo &#62;]