include::./index.adoc[]

[[v18-36-0]]
=== Jó, 36
// nvt ?, NVT - Nova Versão Transformadora

[[v18-36-1]]

^<<v18-36-1,1>>^ Eliú continuou a falar:

[[v18-36-2]]

^<<v18-36-2,2>>^ "Deixe-me prosseguir e lhe mostrarei a verdade, pois ainda não terminei de defender a Deus!

[[v18-36-3]]

^<<v18-36-3,3>>^ Apresentarei argumentos profundos em favor da justiça de meu Criador.

[[v18-36-4]]

^<<v18-36-4,4>>^ Digo somente a verdade, pois sou homem de pleno conhecimento.

[[v18-36-5]]

^<<v18-36-5,5>>^ "Deus é poderoso, mas não despreza ninguém; ele é grande em força e entendimento.

[[v18-36-6]]

^<<v18-36-6,6>>^ Não permite que os perversos vivam, mas faz justiça aos aflitos.

[[v18-36-7]]

^<<v18-36-7,7>>^ Observa atentamente os justos, coloca-os em tronos com reis e exalta-os para sempre.

[[v18-36-8]]

^<<v18-36-8,8>>^ Se estão acorrentados e amarrados com cordas de aflição,

[[v18-36-9]]

^<<v18-36-9,9>>^ ele faz que vejam o motivo; mostra-lhes que pecaram, sendo orgulhosos.

[[v18-36-10]]

^<<v18-36-10,10>>^ Chama-lhes a atenção e ordena que se afastem do mal.

[[v18-36-11]]

^<<v18-36-11,11>>^ "Se obedecerem e servirem a Deus, serão abençoados com prosperidade a vida inteira; todos os seus dias serão agradáveis.

[[v18-36-12]]

^<<v18-36-12,12>>^ Se, porém, não o ouvirem, serão atravessados pela espada e perecerão por falta de entendimento.

[[v18-36-13]]

^<<v18-36-13,13>>^ Pois os ímpios são cheios de ressentimento; mesmo quando Deus os castiga, não clamam por socorro.

[[v18-36-14]]

^<<v18-36-14,14>>^ Morrem em plena juventude, depois de desperdiçar a vida em imoralidade.

[[v18-36-15]]

^<<v18-36-15,15>>^ Mas, por meio do sofrimento, ele livra os que sofrem e, por meio da adversidade, obtém sua atenção.

[[v18-36-16]]

^<<v18-36-16,16>>^ "Jó, Deus também quer afastá-lo do sofrimento e levá-lo a um lugar onde não há aflição; quer pôr em sua mesa as comidas mais saborosas.

[[v18-36-17]]

^<<v18-36-17,17>>^ Você, porém, insiste em saber se os perversos serão julgados; só consegue pensar no juízo e na justiça.

[[v18-36-18]]

^<<v18-36-18,18>>^ Tome cuidado, para que a riqueza não o seduza; não deixe que o suborno o leve a pecar.

[[v18-36-19]]

^<<v18-36-19,19>>^ Acaso toda a sua riqueza ou todos os seus grandes esforços poderiam guardá-lo da aflição?

[[v18-36-20]]

^<<v18-36-20,20>>^ Não deseje a proteção da noite, pois é quando as pessoas serão destruídas.

[[v18-36-21]]

^<<v18-36-21,21>>^ Fique atento! Afaste-se do mal, pois Deus enviou este sofrimento para guardá-lo de uma vida de maldade."

[[v18-36-22]]

^<<v18-36-22,22>>^ "Deus é muito poderoso; quem é mestre como ele?

[[v18-36-23]]

^<<v18-36-23,23>>^ Ninguém pode lhe ordenar o que fazer, nem lhe dizer: ‘Agiste mal’.

[[v18-36-24]]

^<<v18-36-24,24>>^ Você deve, sim, dar glória a Deus por suas obras poderosas e entoar cânticos de louvor.

[[v18-36-25]]

^<<v18-36-25,25>>^ Todos viram suas obras, ainda que apenas de longe.

[[v18-36-26]]

^<<v18-36-26,26>>^ "Deus é tão grande que não podemos compreender; não há como calcular os anos de sua existência.

[[v18-36-27]]

^<<v18-36-27,27>>^ Ele faz a água subir como vapor e depois a destila em chuva.

[[v18-36-28]]

^<<v18-36-28,28>>^ As nuvens derramam a chuva, e a humanidade toda se beneficia.

[[v18-36-29]]

^<<v18-36-29,29>>^ Quem pode entender a extensão das nuvens e o trovão que ressoa do céu?

[[v18-36-30]]

^<<v18-36-30,30>>^ Deus espalha relâmpagos em volta de si e cobre as profundezas do mar.

[[v18-36-31]]

^<<v18-36-31,31>>^ Com esses atos poderosos, governa os povos e lhes dá comida com fartura.

[[v18-36-32]]

^<<v18-36-32,32>>^ Enche as mãos de relâmpagos e atira cada um em seu alvo.

[[v18-36-33]]

^<<v18-36-33,33>>^ O trovão anuncia sua presença, e a tempestade, sua ira indignada."

'''

xref:018-jo/018-jo-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-jo/018-jo-037.adoc#v18-37-0[Próximo Capítulo &#62;]