include::./index.adoc[]

[[v18-32-0]]
=== Jó, 32
// nvt ?, NVT - Nova Versão Transformadora

[[v18-32-1]]

^<<v18-32-1,1>>^ Os três amigos de Jó pararam de lhe responder, pois ele insistia em dizer que era inocente.

[[v18-32-2]]

^<<v18-32-2,2>>^ Então Eliú, filho de Baraquel, o buzita, da família de Rão, ficou irado. Indignou-se porque Jó se achava mais justo que Deus.

[[v18-32-3]]

^<<v18-32-3,3>>^ Também indignou-se com os três amigos de Jó, pois não conseguiram responder a seus argumentos, a fim de demonstrar que Jó estava errado.

[[v18-32-4]]

^<<v18-32-4,4>>^ Eliú havia esperado os outros falarem, pois eram mais velhos que ele.

[[v18-32-5]]

^<<v18-32-5,5>>^ Mas, quando viu que não tinham mais nada a dizer, expressou sua indignação.

[[v18-32-6]]

^<<v18-32-6,6>>^ Assim, Eliú, filho de Baraquel, o buzita, disse: "Eu sou jovem, e vocês são idosos; por isso me contive e não dei minha opinião.

[[v18-32-7]]

^<<v18-32-7,7>>^ Pensei: ‘Os mais velhos devem falar, pois a sabedoria vem com o tempo’.

[[v18-32-8]]

^<<v18-32-8,8>>^ Contudo, há um espírito dentro de cada um, o sopro do Todo-poderoso, que lhe dá entendimento.

[[v18-32-9]]

^<<v18-32-9,9>>^ Nem sempre os de mais idade são sábios; às vezes, os velhos não entendem o que é justo.

[[v18-32-10]]

^<<v18-32-10,10>>^ Portanto, ouçam-me, e eu lhes direi o que penso.

[[v18-32-11]]

^<<v18-32-11,11>>^ "Esperei todo esse tempo, ouvindo seus argumentos atentamente, observando enquanto procuravam palavras.

[[v18-32-12]]

^<<v18-32-12,12>>^ Dei-lhes toda a atenção, mas nenhum de vocês provou que Jó está errado, nem respondeu a seus argumentos.

[[v18-32-13]]

^<<v18-32-13,13>>^ Não venham me dizer: ‘Ele é sábio demais para nós; só Deus pode convencê-lo’.

[[v18-32-14]]

^<<v18-32-14,14>>^ Se Jó tivesse discutido comigo, eu não teria respondido como vocês.

[[v18-32-15]]

^<<v18-32-15,15>>^ Estão aí perplexos, sem resposta, sem terem mais o que dizer.

[[v18-32-16]]

^<<v18-32-16,16>>^ Devo continuar a esperar, agora que se calaram? Devo também permanecer em silêncio?

[[v18-32-17]]

^<<v18-32-17,17>>^ Não! Darei minha resposta; também expressarei minha opinião.

[[v18-32-18]]

^<<v18-32-18,18>>^ Pois tenho muito a dizer, e o espírito em mim me impulsiona a falar.

[[v18-32-19]]

^<<v18-32-19,19>>^ Sou como um barril de vinho sem respiradouro, como uma vasilha de couro prestes a romper.

[[v18-32-20]]

^<<v18-32-20,20>>^ Preciso falar para ter alívio; sim, deixem-me responder!

[[v18-32-21]]

^<<v18-32-21,21>>^ Não tomarei partido, nem tentarei bajular ninguém.

[[v18-32-22]]

^<<v18-32-22,22>>^ Pois, se tentasse usar de bajulação, meu Criador logo me destruiria."

'''

xref:018-jo/018-jo-031.adoc#v18-31-0[&#60; Capítulo Anterior] | <<v18-32-0,Topo>> | xref:018-jo/018-jo-033.adoc#v18-33-0[Próximo Capítulo &#62;]