include::./index.adoc[]

[[v18-15-0]]
=== Jó, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v18-15-1]]

^<<v18-15-1,1>>^ Então Elifaz, de Temã, respondeu:

[[v18-15-2]]

^<<v18-15-2,2>>^ "Um homem sábio não responderia com esse falatório! Suas palavras não passam de vento.

[[v18-15-3]]

^<<v18-15-3,3>>^ O sábio não se envolve em conversas sem propósito, nem usa palavras sem sentido.

[[v18-15-4]]

^<<v18-15-4,4>>^ De fato, você não tem temor a Deus e não lhe mostra reverência.

[[v18-15-5]]

^<<v18-15-5,5>>^ Seus pecados dizem à boca o que ela deve falar; suas palavras se baseiam em engano astuto.

[[v18-15-6]]

^<<v18-15-6,6>>^ Sua própria boca o condena, não eu; seus próprios lábios depõem contra você.

[[v18-15-7]]

^<<v18-15-7,7>>^ "Acaso você foi o primeiro ser humano a nascer? Veio ao mundo antes de serem criados os montes?

[[v18-15-8]]

^<<v18-15-8,8>>^ Estava presente no conselho secreto de Deus? Só você é dono da sabedoria?

[[v18-15-9]]

^<<v18-15-9,9>>^ O que você sabe que nós não sabemos? Que compreensão tem que nós não temos?

[[v18-15-10]]

^<<v18-15-10,10>>^ Homens idosos, de cabelo grisalho, mais velhos que seu pai, pensam exatamente como nós!

[[v18-15-11]]

^<<v18-15-11,11>>^ "A consolação de Deus não é suficiente para você? Palavras amáveis não lhe bastam?

[[v18-15-12]]

^<<v18-15-12,12>>^ O que o fez perder a razão? Por que seus olhos chegam a faiscar

[[v18-15-13]]

^<<v18-15-13,13>>^ quando você se volta contra Deus e diz tais absurdos?

[[v18-15-14]]

^<<v18-15-14,14>>^ O que é o ser humano, para se considerar puro? Pode alguém nascido de mulher ser justo?

[[v18-15-15]]

^<<v18-15-15,15>>^ Deus não confia nem nos anjos! Aos olhos dele, nem mesmo os céus são puros.

[[v18-15-16]]

^<<v18-15-16,16>>^ Quanto menos um ser humano detestável e corrupto, que tem sede de perversidade!

[[v18-15-17]]

^<<v18-15-17,17>>^ "Escute, e eu lhe mostrarei; falarei com base em minha experiência.

[[v18-15-18]]

^<<v18-15-18,18>>^ Ela é confirmada pelo relato de homens sábios, que ouviram as mesmas verdades de seus antepassados,

[[v18-15-19]]

^<<v18-15-19,19>>^ daqueles aos quais foi dada a terra, muito antes de chegar qualquer estrangeiro.

[[v18-15-20]]

^<<v18-15-20,20>>^ "Os perversos se contorcem de dor a vida toda; aos cruéis estão reservados tempos de sofrimento.

[[v18-15-21]]

^<<v18-15-21,21>>^ Em seus ouvidos ressoam sons de terror, e mesmo em dias tranquilos temem o ataque do destruidor.

[[v18-15-22]]

^<<v18-15-22,22>>^ Não se atrevem a sair no escuro, por medo de serem mortos pela espada.

[[v18-15-23]]

^<<v18-15-23,23>>^ Ficam perambulando e dizendo: ‘Onde posso encontrar pão?’; sabem que o dia de sua destruição se aproxima.

[[v18-15-24]]

^<<v18-15-24,24>>^ Vivem angustiados e aflitos, cheios de terror, como um rei que se prepara para a batalha,

[[v18-15-25]]

^<<v18-15-25,25>>^ pois agitam os punhos contra Deus e desafiam arrogantemente o Todo-poderoso.

[[v18-15-26]]

^<<v18-15-26,26>>^ Com seus fortes escudos levantados, avançam contra ele em rebeldia.

[[v18-15-27]]

^<<v18-15-27,27>>^ "Em sua prosperidade, o rosto dos perversos inchou, e sua barriga acumulou gordura.

[[v18-15-28]]

^<<v18-15-28,28>>^ Suas cidades, porém, serão arruinadas; habitarão em casas abandonadas, prestes a desabar.

[[v18-15-29]]

^<<v18-15-29,29>>^ Suas riquezas não durarão, seus bens não permanecerão, e suas propriedades não se estenderão pela terra.

[[v18-15-30]]

^<<v18-15-30,30>>^ "Não escaparão das trevas; o sol abrasador queimará seus ramos, e o sopro de Deus os destruirá.

[[v18-15-31]]

^<<v18-15-31,31>>^ Que não se iludam mais ao confiar em riquezas vazias, pois o vazio será sua única recompensa.

[[v18-15-32]]

^<<v18-15-32,32>>^ Serão cortados na flor da idade; seus ramos jamais voltarão a verdejar.

[[v18-15-33]]

^<<v18-15-33,33>>^ Serão como a videira cujas uvas são colhidas cedo demais, como a oliveira que perde as flores antes que se formem os frutos.

[[v18-15-34]]

^<<v18-15-34,34>>^ Pois os ímpios não têm futuro; o fogo destruirá suas casas enriquecidas com subornos.

[[v18-15-35]]

^<<v18-15-35,35>>^ Concebem desgraça e dão à luz maldade; seu ventre só gera engano".

'''

xref:018-jo/018-jo-014.adoc#v18-14-0[&#60; Capítulo Anterior] | <<v18-15-0,Topo>> | xref:018-jo/018-jo-016.adoc#v18-16-0[Próximo Capítulo &#62;]