include::./index.adoc[]

[[v18-24-0]]
=== Jó, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v18-24-1]]

^<<v18-24-1,1>>^ "Por que o Todo-poderoso não marca uma data para seu juízo? Por que os que o conhecem esperam por ele em vão?

[[v18-24-2]]

^<<v18-24-2,2>>^ Os perversos mudam os marcos das divisas, roubam rebanhos e os trazem para seus pastos.

[[v18-24-3]]

^<<v18-24-3,3>>^ Levam o jumento que pertence ao órfão e exigem o boi da viúva como penhor.

[[v18-24-4]]

^<<v18-24-4,4>>^ Os pobres são empurrados para fora do caminho, e os necessitados se escondem para se proteger.

[[v18-24-5]]

^<<v18-24-5,5>>^ Como jumentos selvagens nas regiões áridas, passam todo o tempo em busca de comida; até no deserto procuram alimento para os filhos.

[[v18-24-6]]

^<<v18-24-6,6>>^ Fazem a colheita de um campo que não semearam e recolhem as uvas nas videiras dos perversos.

[[v18-24-7]]

^<<v18-24-7,7>>^ Passam a noite nus e com frio, pois não têm roupas nem cobertas.

[[v18-24-8]]

^<<v18-24-8,8>>^ Encharcados pelas chuvas das montanhas, encolhem-se junto às rochas por falta de abrigo.

[[v18-24-9]]

^<<v18-24-9,9>>^ "Os perversos arrancam o filho da viúva do seio dela; tomam o bebê como garantia por um empréstimo.

[[v18-24-10]]

^<<v18-24-10,10>>^ Os pobres andam nus por falta de roupas; colhem alimento para outros, enquanto passam fome.

[[v18-24-11]]

^<<v18-24-11,11>>^ Espremem azeitonas para obter azeite, mas não podem prová-lo; pisam uvas para fazer vinho, enquanto passam sede.

[[v18-24-12]]

^<<v18-24-12,12>>^ Os gemidos dos que estão para morrer sobem da cidade, e os feridos clamam por socorro, mas Deus não faz caso de seus lamentos.

[[v18-24-13]]

^<<v18-24-13,13>>^ "Os perversos se revoltam contra a luz; não reconhecem os caminhos dela, nem permanecem em suas estradas.

[[v18-24-14]]

^<<v18-24-14,14>>^ O assassino se levanta bem cedo, para matar os pobres e os necessitados; à noite ele se torna ladrão.

[[v18-24-15]]

^<<v18-24-15,15>>^ O adúltero espera o cair da noite, pois pensa: ‘Ninguém me verá’; esconde o rosto para ninguém o reconhecer.

[[v18-24-16]]

^<<v18-24-16,16>>^ Os bandidos arrombam casas à noite e dormem durante o dia; não estão acostumados com a luz.

[[v18-24-17]]

^<<v18-24-17,17>>^ A noite escura é sua manhã; aliam-se aos terrores da escuridão.

[[v18-24-18]]

^<<v18-24-18,18>>^ "Mas, como espuma num rio, desaparecem; tudo que possuem é amaldiçoado, e temem entrar nas próprias videiras.

[[v18-24-19]]

^<<v18-24-19,19>>^ A sepultura consome os pecadores, como a seca e o calor consomem a neve.

[[v18-24-20]]

^<<v18-24-20,20>>^ Sua própria mãe se esquecerá deles; para os vermes, terão sabor doce. Ninguém se lembrará deles; os perversos serão derrubados como árvores.

[[v18-24-21]]

^<<v18-24-21,21>>^ Enganam a mulher que não tem filhos para defendê-la; não socorrem a viúva necessitada.

[[v18-24-22]]

^<<v18-24-22,22>>^ "Deus, em seu poder, leva embora os ricos; ainda que prosperem, não têm garantia de que viverão.

[[v18-24-23]]

^<<v18-24-23,23>>^ Talvez lhes seja permitido ficar em segurança, mas Deus os vigia sem cessar.

[[v18-24-24]]

^<<v18-24-24,24>>^ Ainda que sejam importantes agora, depressa desaparecerão, como todos os outros, cortados como espigas de cereal.

[[v18-24-25]]

^<<v18-24-25,25>>^ Acaso alguém pode afirmar o contrário? Quem pode provar que estou errado?".

'''

xref:018-jo/018-jo-023.adoc#v18-23-0[&#60; Capítulo Anterior] | <<v18-24-0,Topo>> | xref:018-jo/018-jo-025.adoc#v18-25-0[Próximo Capítulo &#62;]