include::./index.adoc[]

[[v18-28-0]]
=== Jó, 28
// nvt ?, NVT - Nova Versão Transformadora

[[v18-28-1]]

^<<v18-28-1,1>>^ "As pessoas sabem de onde extrair a prata e onde refinar o ouro.

[[v18-28-2]]

^<<v18-28-2,2>>^ Sabem de onde tirar o ferro da terra e como separar o cobre da rocha.

[[v18-28-3]]

^<<v18-28-3,3>>^ Sabem fazer brilhar luz na escuridão e procurar minério nas regiões mais distantes, em meio às trevas profundas.

[[v18-28-4]]

^<<v18-28-4,4>>^ Cavam entradas para minas, em lugares onde ninguém vive. Descem por meio de cordas, balançando de um lado para o outro.

[[v18-28-5]]

^<<v18-28-5,5>>^ O alimento cresce na superfície, mas, abaixo dela, a terra é derretida como que por fogo.

[[v18-28-6]]

^<<v18-28-6,6>>^ Ali, as rochas contêm safiras, e, no pó, se encontra ouro.

[[v18-28-7]]

^<<v18-28-7,7>>^ São tesouros que nenhuma ave de rapina consegue enxergar, nem o olho do falcão pode ver.

[[v18-28-8]]

^<<v18-28-8,8>>^ Nenhum animal selvagem pisou nessas riquezas, nenhum leão pôs a pata sobre elas.

[[v18-28-9]]

^<<v18-28-9,9>>^ As pessoas sabem como despedaçar as rochas mais duras e como revirar até as raízes dos montes.

[[v18-28-10]]

^<<v18-28-10,10>>^ Abrem túneis nas rochas e encontram pedras preciosas.

[[v18-28-11]]

^<<v18-28-11,11>>^ Represam a água dos ribeiros e trazem à luz tesouros ocultos.

[[v18-28-12]]

^<<v18-28-12,12>>^ "Mas onde se pode encontrar sabedoria? Onde se pode achar entendimento?

[[v18-28-13]]

^<<v18-28-13,13>>^ Ninguém sabe onde encontrá-la, pois ela não se acha entre os vivos.

[[v18-28-14]]

^<<v18-28-14,14>>^ ‘Não está aqui’, diz o abismo, ‘Nem aqui’, diz o mar.

[[v18-28-15]]

^<<v18-28-15,15>>^ Não se pode comprá-la com ouro, nem adquiri-la com prata.

[[v18-28-16]]

^<<v18-28-16,16>>^ Vale mais que todo o ouro de Ofir, mais que o ônix precioso e a safira.

[[v18-28-17]]

^<<v18-28-17,17>>^ A sabedoria é mais valiosa que ouro e cristal; não se pode comprá-la com joias de ouro fino.

[[v18-28-18]]

^<<v18-28-18,18>>^ Coral e jaspe não se comparam a ela; o preço da sabedoria ultrapassa o dos rubis.

[[v18-28-19]]

^<<v18-28-19,19>>^ Não se pode trocá-la pelo precioso topázio da Etiópia; ela vale mais que o ouro puríssimo.

[[v18-28-20]]

^<<v18-28-20,20>>^ "Onde, afinal, está a sabedoria? Onde está o entendimento?

[[v18-28-21]]

^<<v18-28-21,21>>^ Está escondida dos olhos de toda a humanidade; nem mesmo as aves do céu conseguem descobri-la.

[[v18-28-22]]

^<<v18-28-22,22>>^ A Destruição e a Morte dizem: ‘Ouvimos apenas rumores de onde encontrá-la’.

[[v18-28-23]]

^<<v18-28-23,23>>^ "Somente Deus conhece o caminho para a sabedoria; ele sabe onde encontrá-la.

[[v18-28-24]]

^<<v18-28-24,24>>^ Pois ele enxerga toda a terra; vê tudo que há debaixo do céu.

[[v18-28-25]]

^<<v18-28-25,25>>^ Determina a força dos ventos e o volume das águas.

[[v18-28-26]]

^<<v18-28-26,26>>^ Fez as leis para controlar a chuva e definiu o caminho dos relâmpagos.

[[v18-28-27]]

^<<v18-28-27,27>>^ Então viu a sabedoria e a avaliou; em seu lugar a pôs e cuidadosamente a examinou.

[[v18-28-28]]

^<<v18-28-28,28>>^ É isto que ele diz a toda a humanidade: ‘O temor do Senhor é a verdadeira sabedoria; afastar-se do mal é o verdadeiro entendimento’".

'''

xref:018-jo/018-jo-027.adoc#v18-27-0[&#60; Capítulo Anterior] | <<v18-28-0,Topo>> | xref:018-jo/018-jo-029.adoc#v18-29-0[Próximo Capítulo &#62;]