include::./index.adoc[]

[[v18-18-0]]
=== Jó, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v18-18-1]]

^<<v18-18-1,1>>^ Então Bildade, de Suá, respondeu:

[[v18-18-2]]

^<<v18-18-2,2>>^ "Até onde você vai com suas palavras? Mostre sensatez, se deseja que respondamos!

[[v18-18-3]]

^<<v18-18-3,3>>^ Imagina que somos animais? Pensa que somos ignorantes?

[[v18-18-4]]

^<<v18-18-4,4>>^ Ainda que arranque os cabelos de raiva, acaso isso destruirá a terra? Fará as rochas mudarem de lugar?

[[v18-18-5]]

^<<v18-18-5,5>>^ "Por certo, a luz do perverso se apagará; as faíscas de seu fogo deixarão de brilhar.

[[v18-18-6]]

^<<v18-18-6,6>>^ A luz de sua tenda se escurecerá; a lâmpada pendurada sobre ele se extinguirá.

[[v18-18-7]]

^<<v18-18-7,7>>^ Os passos confiantes do perverso serão encurtados; será arruinado pelas próprias tramas.

[[v18-18-8]]

^<<v18-18-8,8>>^ O perverso caminha direto para a rede; cai num alçapão.

[[v18-18-9]]

^<<v18-18-9,9>>^ Uma armadilha o pega pelo calcanhar, um laço o prende com força.

[[v18-18-10]]

^<<v18-18-10,10>>^ Há uma cilada escondida na terra, uma corda estendida em seu caminho.

[[v18-18-11]]

^<<v18-18-11,11>>^ "Terrores cercam o perverso e o perseguem a cada passo.

[[v18-18-12]]

^<<v18-18-12,12>>^ A fome esgota suas forças, e a calamidade aguarda seu tropeço.

[[v18-18-13]]

^<<v18-18-13,13>>^ A doença consumirá sua pele, e uma morte horrível devorará seus membros.

[[v18-18-14]]

^<<v18-18-14,14>>^ É arrancado da segurança de seu lar e levado ao rei dos terrores.

[[v18-18-15]]

^<<v18-18-15,15>>^ O lar do perverso será consumido pelo fogo, e enxofre se espalhará sobre sua casa.

[[v18-18-16]]

^<<v18-18-16,16>>^ Por baixo, suas raízes secarão; por cima, seus ramos murcharão.

[[v18-18-17]]

^<<v18-18-17,17>>^ Toda lembrança de sua existência desaparecerá da terra; ninguém recordará seu nome.

[[v18-18-18]]

^<<v18-18-18,18>>^ Será lançado da luz para as trevas, expulso do mundo.

[[v18-18-19]]

^<<v18-18-19,19>>^ Não terá filhos nem netos, nem haverá sobreviventes no lugar onde morava.

[[v18-18-20]]

^<<v18-18-20,20>>^ No oeste, ficarão espantados com seu destino; no leste, serão tomados de horror.

[[v18-18-21]]

^<<v18-18-21,21>>^ Dirão: ‘Esta era a habitação do perverso, o lugar de alguém que não conheceu a Deus’".

'''

xref:018-jo/018-jo-017.adoc#v18-17-0[&#60; Capítulo Anterior] | <<v18-18-0,Topo>> | xref:018-jo/018-jo-019.adoc#v18-19-0[Próximo Capítulo &#62;]