include::./index.adoc[]

[[v18-5-0]]
=== Jó, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v18-5-1]]

^<<v18-5-1,1>>^ "Grite por socorro, mas alguém responderá? Qual dos anjos o ajudará?

[[v18-5-2]]

^<<v18-5-2,2>>^ Por certo, o ressentimento destrói o insensato, e a inveja mata o tolo.

[[v18-5-3]]

^<<v18-5-3,3>>^ Observei que os insensatos têm sucesso por um tempo, mas desgraça repentina vem sobre eles.

[[v18-5-4]]

^<<v18-5-4,4>>^ Seus filhos perdem toda e qualquer segurança; são oprimidos no tribunal, e não há quem os defenda.

[[v18-5-5]]

^<<v18-5-5,5>>^ Os famintos devoram sua colheita, mesmo quando protegida por espinheiros, e os sedentos anseiam por sua riqueza.

[[v18-5-6]]

^<<v18-5-6,6>>^ Embora o mal não surja do solo, nem as dificuldades brotem da terra,

[[v18-5-7]]

^<<v18-5-7,7>>^ o ser humano nasce para enfrentar aflições, tão certo como as faíscas do fogo voam para o alto.

[[v18-5-8]]

^<<v18-5-8,8>>^ "Se eu fosse você, buscaria a Deus e lhe apresentaria minha causa.

[[v18-5-9]]

^<<v18-5-9,9>>^ Ele faz grandes coisas, maravilhosas demais para entender, e realiza milagres incontáveis.

[[v18-5-10]]

^<<v18-5-10,10>>^ Dá chuva à terra e água aos campos.

[[v18-5-11]]

^<<v18-5-11,11>>^ Exalta os humildes e protege os que sofrem.

[[v18-5-12]]

^<<v18-5-12,12>>^ Frustra os planos dos maliciosos, para que as obras de suas mãos fracassem.

[[v18-5-13]]

^<<v18-5-13,13>>^ Apanha os sábios em sua própria astúcia e frustra as intrigas dos ardilosos.

[[v18-5-14]]

^<<v18-5-14,14>>^ Ficam na escuridão em pleno dia e tateiam ao meio-dia como se fosse noite.

[[v18-5-15]]

^<<v18-5-15,15>>^ Ele salva os pobres das ofensas dos fortes e os livra das garras dos poderosos.

[[v18-5-16]]

^<<v18-5-16,16>>^ Por fim, os desamparados têm esperança, e a boca dos perversos é fechada.

[[v18-5-17]]

^<<v18-5-17,17>>^ "Mas como são felizes os que Deus corrige! Não despreze, portanto, a disciplina do Todo-poderoso.

[[v18-5-18]]

^<<v18-5-18,18>>^ Pois ele fere, mas enfaixa a ferida; bate, mas suas mãos curam.

[[v18-5-19]]

^<<v18-5-19,19>>^ Ele o livrará de seis desgraças, e até mesmo na sétima o guardará do mal.

[[v18-5-20]]

^<<v18-5-20,20>>^ Ele o livrará da morte no tempo de fome e do poder da espada no tempo de guerra.

[[v18-5-21]]

^<<v18-5-21,21>>^ Você estará protegido das calúnias e não terá medo quando vier a destruição.

[[v18-5-22]]

^<<v18-5-22,22>>^ Rirá da destruição e da fome, e animais selvagens não o assustarão.

[[v18-5-23]]

^<<v18-5-23,23>>^ Fará um pacto com as pedras do campo, e os animais selvagens estarão em paz com você.

[[v18-5-24]]

^<<v18-5-24,24>>^ Saberá que seu lar está seguro; ao contar seus bens, de nada achará falta.

[[v18-5-25]]

^<<v18-5-25,25>>^ Terá muitos filhos, tantos descendentes como o capim no pasto.

[[v18-5-26]]

^<<v18-5-26,26>>^ Em boa velhice irá para a sepultura, como um feixe de cereal colhido no tempo certo.

[[v18-5-27]]

^<<v18-5-27,27>>^ "Observamos a vida e vimos que tudo isso é verdade; ouça meu conselho e aplique-o à sua vida".

'''

xref:018-jo/018-jo-004.adoc#v18-4-0[&#60; Capítulo Anterior] | <<v18-5-0,Topo>> | xref:018-jo/018-jo-006.adoc#v18-6-0[Próximo Capítulo &#62;]