include::./index.adoc[]

[[v18-6-0]]
=== Jó, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v18-6-1]]

^<<v18-6-1,1>>^ Então Jó falou novamente:

[[v18-6-2]]

^<<v18-6-2,2>>^ "Se fosse possível pesar minha aflição e pôr numa balança meu sofrimento,

[[v18-6-3]]

^<<v18-6-3,3>>^ pesariam mais que toda a areia do mar; por isso falei de modo impulsivo.

[[v18-6-4]]

^<<v18-6-4,4>>^ Pois o Todo-poderoso me derrubou com suas flechas, e minha alma bebe o veneno delas; os terrores de Deus se alinham contra mim.

[[v18-6-5]]

^<<v18-6-5,5>>^ Os jumentos selvagens não zurram ao não encontrar capim? Os bois não mugem quando não têm alimento?

[[v18-6-6]]

^<<v18-6-6,6>>^ As pessoas não se queixam quando falta sal na comida? Alguém gosta da clara de ovo, que não tem sabor?

[[v18-6-7]]

^<<v18-6-7,7>>^ Perco o apetite só de olhar para ela; tenho enjoo só de pensar em comê-la!

[[v18-6-8]]

^<<v18-6-8,8>>^ "Quem dera meu pedido fosse atendido, e Deus concedesse meu desejo.

[[v18-6-9]]

^<<v18-6-9,9>>^ Quem dera ele me esmagasse, estendesse a mão e acabasse comigo.

[[v18-6-10]]

^<<v18-6-10,10>>^ Ao menos tenho este consolo e alegria: apesar da dor, não neguei as palavras do Santo.

[[v18-6-11]]

^<<v18-6-11,11>>^ Contudo, faltam-me forças para prosseguir; não vejo motivo para viver.

[[v18-6-12]]

^<<v18-6-12,12>>^ Acaso tenho a força de uma pedra? Meu corpo é feito de bronze?

[[v18-6-13]]

^<<v18-6-13,13>>^ Não! Estou completamente desamparado, sem chance alguma de sucesso.

[[v18-6-14]]

^<<v18-6-14,14>>^ "É preciso ter compaixão de um amigo abatido, mas vocês me acusam sem nenhum temor do Todo-poderoso.

[[v18-6-15]]

^<<v18-6-15,15>>^ Meus irmãos, vocês se mostraram indignos de confiança, como um riacho intermitente que transborda sobre as margens,

[[v18-6-16]]

^<<v18-6-16,16>>^ quando fica turvo por causa do gelo, e a neve sobre ele se amontoa.

[[v18-6-17]]

^<<v18-6-17,17>>^ Mas, chegado o tempo de seca, a água desaparece, e o riacho some no calor.

[[v18-6-18]]

^<<v18-6-18,18>>^ As caravanas saem de suas rotas, mas não há o que beber, e morrem ali.

[[v18-6-19]]

^<<v18-6-19,19>>^ As caravanas de Temá procuram essa água, e os viajantes de Sabá esperam encontrá-la.

[[v18-6-20]]

^<<v18-6-20,20>>^ Contam com ela, mas se decepcionam; quando chegam, suas esperanças são frustradas.

[[v18-6-21]]

^<<v18-6-21,21>>^ Da mesma forma, vocês não me ajudaram; viram minha desgraça e ficaram com medo.

[[v18-6-22]]

^<<v18-6-22,22>>^ Mas, por quê? Alguma vez lhes pedi presentes? Supliquei que me dessem algo seu?

[[v18-6-23]]

^<<v18-6-23,23>>^ Pedi que me livrassem de meus inimigos ou que me resgatassem de meus opressores?

[[v18-6-24]]

^<<v18-6-24,24>>^ Ensinem-me, e eu me calarei; mostrem-me onde errei.

[[v18-6-25]]

^<<v18-6-25,25>>^ Palavras honestas são dolorosas, mas de que servem suas críticas?

[[v18-6-26]]

^<<v18-6-26,26>>^ Consideram suas palavras convincentes, enquanto ignoram meu clamor de desespero?

[[v18-6-27]]

^<<v18-6-27,27>>^ Seriam capazes de apostar um órfão num jogo de azar; sim, venderiam até mesmo um amigo.

[[v18-6-28]]

^<<v18-6-28,28>>^ Olhem para mim! Acaso eu mentiria para vocês?

[[v18-6-29]]

^<<v18-6-29,29>>^ Não pressuponham que sou culpado, pois nada fiz de errado.

[[v18-6-30]]

^<<v18-6-30,30>>^ Pensam que sou mentiroso? Acaso não sei mais distinguir entre bem e mal?"

'''

xref:018-jo/018-jo-005.adoc#v18-5-0[&#60; Capítulo Anterior] | <<v18-6-0,Topo>> | xref:018-jo/018-jo-007.adoc#v18-7-0[Próximo Capítulo &#62;]