include::./index.adoc[]

[[v18-33-0]]
=== Jó, 33
// nvt ?, NVT - Nova Versão Transformadora

[[v18-33-1]]

^<<v18-33-1,1>>^ "Jó, ouça minhas palavras, preste atenção ao que vou dizer.

[[v18-33-2]]

^<<v18-33-2,2>>^ Chegou minha vez de falar; as palavras estão na ponta da língua.

[[v18-33-3]]

^<<v18-33-3,3>>^ Falo com toda a sinceridade, digo a pura verdade.

[[v18-33-4]]

^<<v18-33-4,4>>^ O Espírito de Deus me criou, o sopro do Todo-poderoso me dá vida.

[[v18-33-5]]

^<<v18-33-5,5>>^ Responda-me, se puder; apresente seus argumentos e defina sua posição.

[[v18-33-6]]

^<<v18-33-6,6>>^ Você e eu somos iguais diante de Deus; eu também fui formado do barro.

[[v18-33-7]]

^<<v18-33-7,7>>^ Portanto, não tenha medo de mim; não serei severo demais com você.

[[v18-33-8]]

^<<v18-33-8,8>>^ "Você falou em minha presença, e ouvi bem suas palavras.

[[v18-33-9]]

^<<v18-33-9,9>>^ Você disse: ‘Sou puro e não tenho pecado; sou inocente e não tenho culpa.

[[v18-33-10]]

^<<v18-33-10,10>>^ Deus procura motivos para se opor a mim e me considera seu inimigo.

[[v18-33-11]]

^<<v18-33-11,11>>^ Prende meus pés no tronco e vigia todos os meus movimentos’.

[[v18-33-12]]

^<<v18-33-12,12>>^ "Mas você está enganado, e eu lhe mostrarei o motivo, pois Deus é maior que qualquer ser humano.

[[v18-33-13]]

^<<v18-33-13,13>>^ Sendo assim, por que você o acusa? Por que diz que ele não responde às queixas humanas?

[[v18-33-14]]

^<<v18-33-14,14>>^ Pois Deus fala repetidamente, embora as pessoas não prestem atenção.

[[v18-33-15]]

^<<v18-33-15,15>>^ Fala em sonhos, em visões durante a noite, quando o sono profundo cai sobre todos, enquanto dormem em suas camas.

[[v18-33-16]]

^<<v18-33-16,16>>^ Sussurra em seus ouvidos e aterroriza-os com advertências.

[[v18-33-17]]

^<<v18-33-17,17>>^ Faz que deixem de praticar o mal e livra-os do orgulho.

[[v18-33-18]]

^<<v18-33-18,18>>^ Preserva-os do túmulo e de serem atravessados pela espada.

[[v18-33-19]]

^<<v18-33-19,19>>^ "Deus os disciplina no leito de enfermidade, com dores constantes nos ossos.

[[v18-33-20]]

^<<v18-33-20,20>>^ Eles perdem a vontade de comer; nem mesmo o alimento mais delicioso lhes apetece.

[[v18-33-21]]

^<<v18-33-21,21>>^ Sua carne definha a olhos nus, e seus ossos ficam à vista.

[[v18-33-22]]

^<<v18-33-22,22>>^ Estão cada vez mais perto do túmulo; os mensageiros da morte os esperam.

[[v18-33-23]]

^<<v18-33-23,23>>^ "Mas, se um dos milhares de anjos do céu aparecer, para interceder por alguém e declará-lo justo,

[[v18-33-24]]

^<<v18-33-24,24>>^ Deus terá compaixão e dirá: ‘Livre-o do túmulo, pois encontrei resgate por sua vida’.

[[v18-33-25]]

^<<v18-33-25,25>>^ Então seu corpo se tornará saudável como o de um menino; será forte e jovem outra vez.

[[v18-33-26]]

^<<v18-33-26,26>>^ Quando ele orar a Deus, será aceito. Deus o receberá com alegria e o restituirá à condição de justo.

[[v18-33-27]]

^<<v18-33-27,27>>^ Ele declarará a seus amigos: ‘Pequei e perverti o que é correto, mas não valeu a pena.

[[v18-33-28]]

^<<v18-33-28,28>>^ Deus me livrou do túmulo; agora minha vida contempla a luz’.

[[v18-33-29]]

^<<v18-33-29,29>>^ "Sim, Deus faz essas coisas acontecerem repetidas vezes com as pessoas.

[[v18-33-30]]

^<<v18-33-30,30>>^ Ele as livra da sepultura, para que desfrutem a luz da vida.

[[v18-33-31]]

^<<v18-33-31,31>>^ Preste atenção, Jó; fique quieto e ouça-me, pois tenho mais coisas para falar.

[[v18-33-32]]

^<<v18-33-32,32>>^ Mas, se você tem algo a dizer, responda; fale, pois quero que seja absolvido.

[[v18-33-33]]

^<<v18-33-33,33>>^ Se não tem nada a dizer, fique quieto e ouça-me, e eu lhe ensinarei a sabedoria".

'''

xref:018-jo/018-jo-032.adoc#v18-32-0[&#60; Capítulo Anterior] | <<v18-33-0,Topo>> | xref:018-jo/018-jo-034.adoc#v18-34-0[Próximo Capítulo &#62;]