include::./index.adoc[]

[[v18-42-0]]
=== Jó, 42
// nvt ?, NVT - Nova Versão Transformadora

[[v18-42-1]]

^<<v18-42-1,1>>^ Então Jó respondeu ao SENHOR:

[[v18-42-2]]

^<<v18-42-2,2>>^ "Sei que podes fazer todas as coisas, e ninguém pode frustrar teus planos.

[[v18-42-3]]

^<<v18-42-3,3>>^ Perguntaste: ‘Quem é esse que, com tanta ignorância, questiona minha sabedoria?’. Sou eu; falei de coisas de que eu não entendia, coisas maravilhosas demais que eu não conhecia.

[[v18-42-4]]

^<<v18-42-4,4>>^ Disseste: ‘Ouça, e eu falarei! Eu lhe farei algumas perguntas, e você responderá’.

[[v18-42-5]]

^<<v18-42-5,5>>^ Antes, eu só te conhecia de ouvir falar; agora, eu te vi com meus próprios olhos.

[[v18-42-6]]

^<<v18-42-6,6>>^ Retiro tudo que disse e me sento arrependido no pó e nas cinzas".

[[v18-42-7]]

^<<v18-42-7,7>>^ Depois que o SENHOR terminou de falar com Jó, disse a Elifaz, de Temã: "Estou muito irado com você e com seus dois amigos, pois não falaram o que é certo a meu respeito, como fez meu servo Jó.

[[v18-42-8]]

^<<v18-42-8,8>>^ Por isso, peguem sete novilhos e sete carneiros, levem os animais a meu servo Jó e ofereçam holocaustos em favor de si mesmos. Meu servo Jó orará por vocês, e eu aceitarei a oração dele. Não tratarei vocês como merecem por sua insensatez, pois não falaram o que é certo a meu respeito, como fez meu servo Jó".

[[v18-42-9]]

^<<v18-42-9,9>>^ Então Elifaz, de Temã, Bildade, de Suá, e Zofar, de Naamá, fizeram o que o SENHOR havia ordenado, e o SENHOR aceitou a oração de Jó.

[[v18-42-10]]

^<<v18-42-10,10>>^ Quando Jó orou por seus amigos, o SENHOR o tornou próspero de novo. Na verdade, o SENHOR lhe deu o dobro do que tinha antes.

[[v18-42-11]]

^<<v18-42-11,11>>^ Todos os seus irmãos, suas irmãs e seus amigos de outros tempos vieram e festejaram com ele à mesa de sua casa. Eles o consolaram e o confortaram por todas as provações que o SENHOR tinha enviado contra ele, e cada um lhe trouxe um presente de prata e um anel de ouro.

[[v18-42-12]]

^<<v18-42-12,12>>^ O SENHOR abençoou Jó na segunda parte de sua vida ainda mais que na primeira. Ele teve catorze mil ovelhas, seis mil camelos, mil juntas de bois e mil jumentas.

[[v18-42-13]]

^<<v18-42-13,13>>^ Deus também deu a Jó sete filhos e três filhas.

[[v18-42-14]]

^<<v18-42-14,14>>^ Jó chamou a primeira filha de Jemima, a segunda, de Quézia, e a terceira, de Quéren-Hapuque.

[[v18-42-15]]

^<<v18-42-15,15>>^ Em toda a terra, não havia mulheres tão lindas como as filhas de Jó. E seu pai lhes deu herança junto com os irmãos delas.

[[v18-42-16]]

^<<v18-42-16,16>>^ Depois disso, Jó viveu 140 anos e viu quatro gerações de filhos e netos.

[[v18-42-17]]

^<<v18-42-17,17>>^ Então, morreu, depois de uma vida longa e plena.

'''

xref:018-jo/018-jo-041.adoc#v18-41-0[&#60; Capítulo Anterior] | <<v18-42-0,Topo>> | xref:019-salmos/019-salmos-001.adoc#v19-1-0[Próximo Capítulo &#62;]