include::./index.adoc[]

[[v18-13-0]]
=== Jó, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v18-13-1]]

^<<v18-13-1,1>>^ "Vi tudo isso com os próprios olhos; ouvi com os próprios ouvidos, e agora entendo.

[[v18-13-2]]

^<<v18-13-2,2>>^ O que vocês sabem, eu também sei; não são melhores que eu.

[[v18-13-3]]

^<<v18-13-3,3>>^ Quero falar diretamente com o Todo-poderoso, quero defender minha causa diante de Deus.

[[v18-13-4]]

^<<v18-13-4,4>>^ Vocês me difamam com mentiras; são médicos incapazes de curar.

[[v18-13-5]]

^<<v18-13-5,5>>^ Se ao menos se calassem! É a atitude mais sábia que poderiam tomar.

[[v18-13-6]]

^<<v18-13-6,6>>^ Ouçam minha defesa, prestem atenção a meus argumentos.

[[v18-13-7]]

^<<v18-13-7,7>>^ "Vocês querem defender Deus com mentiras? Apresentam argumentos desonestos em nome dele?

[[v18-13-8]]

^<<v18-13-8,8>>^ Distorcem seu testemunho em favor dele? Acaso são advogados de Deus?

[[v18-13-9]]

^<<v18-13-9,9>>^ O que acontecerá quando ele decidir investigá-los? Conseguirão enganá-lo como enganam qualquer pessoa?

[[v18-13-10]]

^<<v18-13-10,10>>^ Não! Certamente ele os repreenderá se distorcerem às escondidas seu testemunho em favor dele.

[[v18-13-11]]

^<<v18-13-11,11>>^ Acaso a majestade dele não os aterrorizará? O terror dele não cairá sobre vocês?

[[v18-13-12]]

^<<v18-13-12,12>>^ Suas frases feitas valem tanto quanto cinzas; sua defesa é fraca como um pote de barro.

[[v18-13-13]]

^<<v18-13-13,13>>^ "Calem-se e deixem-me em paz! Permitam-me falar, e eu arcarei com as consequências.

[[v18-13-14]]

^<<v18-13-14,14>>^ Sim, porei minha vida em risco e direi o que penso de fato.

[[v18-13-15]]

^<<v18-13-15,15>>^ Ainda que Deus me mate, ele é minha única esperança; apresentarei a ele minha causa.

[[v18-13-16]]

^<<v18-13-16,16>>^ Isto, porém, é o que me salvará: não sou ímpio; se o fosse, não poderia me colocar diante dele.

[[v18-13-17]]

^<<v18-13-17,17>>^ "Escutem bem o que vou dizer, ouçam-me com atenção.

[[v18-13-18]]

^<<v18-13-18,18>>^ Preparei minha defesa; serei declarado inocente.

[[v18-13-19]]

^<<v18-13-19,19>>^ Quem pode discutir comigo a esse respeito? E, se provarem que estou errado, me calarei e morrerei."

[[v18-13-20]]

^<<v18-13-20,20>>^ "Ó Deus, concede-me estas duas coisas, e não me esconderei de ti.

[[v18-13-21]]

^<<v18-13-21,21>>^ Remove tua mão de cima de mim e não me assustes com tua temível presença.

[[v18-13-22]]

^<<v18-13-22,22>>^ Chama-me, e eu responderei; ou permita que eu fale e responde-me.

[[v18-13-23]]

^<<v18-13-23,23>>^ Diga-me, o que fiz de errado? Mostra-me minha rebeldia e meu pecado.

[[v18-13-24]]

^<<v18-13-24,24>>^ Por que te afastas de mim? Por que me tratas como teu inimigo?

[[v18-13-25]]

^<<v18-13-25,25>>^ Atormentarias uma folha soprada pelo vento? Perseguirias a palha seca?

[[v18-13-26]]

^<<v18-13-26,26>>^ "Escreves acusações amargas contra mim e trazes à tona os pecados de minha juventude.

[[v18-13-27]]

^<<v18-13-27,27>>^ Prendes meus pés com correntes, vigias todos os meus caminhos e examinas todas as minhas pegadas.

[[v18-13-28]]

^<<v18-13-28,28>>^ Eu me consumo como madeira que apodrece, como roupa comida pela traça."

'''

xref:018-jo/018-jo-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-jo/018-jo-014.adoc#v18-14-0[Próximo Capítulo &#62;]