include::./index.adoc[]

[[v18-1-0]]
=== Jó, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v18-1-1]]

^<<v18-1-1,1>>^ Havia um homem chamado Jó que vivia na terra de Uz. Ele era íntegro e correto, temia a Deus e se mantinha afastado do mal.

[[v18-1-2]]

^<<v18-1-2,2>>^ Tinha sete filhos e três filhas.

[[v18-1-3]]

^<<v18-1-3,3>>^ Era dono de sete mil ovelhas, três mil camelos, quinhentas juntas de bois e quinhentas jumentas. Também tinha muitos servos. Na verdade, era o homem mais rico de toda aquela região.

[[v18-1-4]]

^<<v18-1-4,4>>^ Os filhos de Jó se revezavam em preparar banquetes em suas casas e convidavam suas três irmãs para celebrar com eles.

[[v18-1-5]]

^<<v18-1-5,5>>^ Quando terminavam esses dias de festas, Jó mandava chamar seus filhos, a fim de purificá-los. Levantava-se de manhã bem cedo e oferecia um holocausto em favor de cada um deles, pois pensava: "Pode ser que meus filhos tenham pecado e amaldiçoado a Deus em seu coração". Essa era a prática habitual de Jó.

[[v18-1-6]]

^<<v18-1-6,6>>^ Certo dia, os anjos vieram à presença do SENHOR, e Satanás, o acusador, veio com eles.

[[v18-1-7]]

^<<v18-1-7,7>>^ "De onde você vem?", perguntou o SENHOR. Satanás respondeu: "Estive rodeando a terra, observando o que nela acontece".

[[v18-1-8]]

^<<v18-1-8,8>>^ Então o SENHOR perguntou: "Você reparou em meu servo Jó? Não há ninguém na terra como ele. É homem íntegro e correto, teme a Deus e se mantém afastado do mal".

[[v18-1-9]]

^<<v18-1-9,9>>^ Satanás respondeu: "É verdade, mas Jó tem bons motivos para temer a Deus.

[[v18-1-10]]

^<<v18-1-10,10>>^ Tu puseste um muro de proteção ao redor dele, de sua família e de seus bens e o abençoaste em tudo que ele faz. Vê como ele é rico!

[[v18-1-11]]

^<<v18-1-11,11>>^ Estende tua mão e toma tudo que ele tem, e certamente ele te amaldiçoará na tua face!".

[[v18-1-12]]

^<<v18-1-12,12>>^ "Pois bem, você pode prová-lo", disse o SENHOR. "Faça o que quiser com tudo que ele possui, mas não lhe cause nenhum dano físico." Então Satanás saiu da presença do SENHOR.

[[v18-1-13]]

^<<v18-1-13,13>>^ Certo dia, quando os filhos e as filhas de Jó estavam num banquete na casa do irmão mais velho,

[[v18-1-14]]

^<<v18-1-14,14>>^ chegou à casa de Jó um mensageiro com esta notícia: "Seus bois estavam arando, e os jumentos, pastando perto deles,

[[v18-1-15]]

^<<v18-1-15,15>>^ quando os sabeus nos atacaram. Roubaram todos os animais e mataram todos os empregados. Só eu escapei para lhe contar".

[[v18-1-16]]

^<<v18-1-16,16>>^ Enquanto ele falava, outro mensageiro chegou com esta notícia: "O fogo de Deus caiu do céu e queimou suas ovelhas e todos os seus pastores. Só eu escapei para lhe contar".

[[v18-1-17]]

^<<v18-1-17,17>>^ Enquanto ele falava, outro mensageiro chegou com esta notícia: "Três bandos de saqueadores caldeus roubaram seus camelos e mataram seus servos. Só eu escapei para lhe contar".

[[v18-1-18]]

^<<v18-1-18,18>>^ Enquanto ele falava, ainda outro mensageiro chegou com esta notícia: "Seus filhos e suas filhas estavam num banquete na casa do irmão mais velho.

[[v18-1-19]]

^<<v18-1-19,19>>^ De repente, veio do deserto um vendaval terrível e atingiu a casa de todos os lados. A casa desabou, e todos os seus filhos morreram. Só eu escapei para lhe contar".

[[v18-1-20]]

^<<v18-1-20,20>>^ Então Jó se levantou e rasgou seu manto. Depois, raspou a cabeça, prostrou-se com o rosto no chão em adoração

[[v18-1-21]]

^<<v18-1-21,21>>^ e disse: "Saí nu do ventre de minha mãe, e estarei nu quando partir. O SENHOR me deu o que eu tinha, e o SENHOR o tomou. Louvado seja o nome do SENHOR!".

[[v18-1-22]]

^<<v18-1-22,22>>^ Em tudo isso, Jó não pecou nem culpou a Deus.

'''

xref:017-ester/017-ester-010.adoc#v17-10-0[&#60; Capítulo Anterior] | <<v18-1-0,Topo>> | xref:018-jo/018-jo-002.adoc#v18-2-0[Próximo Capítulo &#62;]