include::./index.adoc[]

[[v18-9-0]]
=== Jó, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v18-9-1]]

^<<v18-9-1,1>>^ Então Jó falou novamente:

[[v18-9-2]]

^<<v18-9-2,2>>^ "Sim, eu sei que tudo isso é verdade de modo geral, mas como alguém pode ser inocente aos olhos de Deus?

[[v18-9-3]]

^<<v18-9-3,3>>^ Se uma pessoa quisesse levar Deus ao tribunal, acaso poderia lhe responder uma vez em mil?

[[v18-9-4]]

^<<v18-9-4,4>>^ Pois Deus é muito sábio e poderoso: quem alguma vez o enfrentou e saiu vencedor?

[[v18-9-5]]

^<<v18-9-5,5>>^ "Ele move montanhas sem dar aviso, e, em sua ira, as põe abaixo.

[[v18-9-6]]

^<<v18-9-6,6>>^ Sacode a terra de seu lugar e faz tremer seus alicerces.

[[v18-9-7]]

^<<v18-9-7,7>>^ Se ele ordena, o sol não nasce e as estrelas não brilham.

[[v18-9-8]]

^<<v18-9-8,8>>^ Ele, sozinho, estendeu os céus e marcha sobre as ondas do mar.

[[v18-9-9]]

^<<v18-9-9,9>>^ Criou todas as estrelas: a Ursa e o Órion, as Plêiades e as constelações do sul.

[[v18-9-10]]

^<<v18-9-10,10>>^ Ele faz grandes coisas, maravilhosas demais para entender, e realiza milagres incontáveis.

[[v18-9-11]]

^<<v18-9-11,11>>^ "Quando se aproxima de mim, não posso vê-lo; quando passa, não percebo sua presença.

[[v18-9-12]]

^<<v18-9-12,12>>^ Se ele toma à força, quem o fará devolver? Quem ousa perguntar: ‘O que estás fazendo?’.

[[v18-9-13]]

^<<v18-9-13,13>>^ E Deus não refreia sua ira; até os monstros marinhos são esmagados sob os seus pés.

[[v18-9-14]]

^<<v18-9-14,14>>^ "Quem sou eu, então, para tentar responder a Deus, ou mesmo argumentar com ele?

[[v18-9-15]]

^<<v18-9-15,15>>^ Ainda que fosse inocente, seria incapaz de me defender; poderia apenas implorar por misericórdia ao meu Juiz.

[[v18-9-16]]

^<<v18-9-16,16>>^ E, mesmo que eu o chamasse e ele me respondesse, não acredito que me daria atenção.

[[v18-9-17]]

^<<v18-9-17,17>>^ Pois ele me ataca com uma tempestade e, sem motivo, me fere repetidas vezes.

[[v18-9-18]]

^<<v18-9-18,18>>^ Não permite que eu recupere o fôlego, mas enche minha vida de amargura.

[[v18-9-19]]

^<<v18-9-19,19>>^ Se é uma questão de força, ele é o forte; se é uma questão de justiça, quem ousa levá-lo ao tribunal?

[[v18-9-20]]

^<<v18-9-20,20>>^ Embora eu seja inocente, minha própria boca me declararia culpado; embora eu seja íntegro, ela provaria que sou perverso.

[[v18-9-21]]

^<<v18-9-21,21>>^ "Sou íntegro, mas isso não faz diferença para mim; desprezo minha vida.

[[v18-9-22]]

^<<v18-9-22,22>>^ Íntegro ou perverso, é tudo a mesma coisa; por isso digo: ‘Ele destrói tanto o íntegro como o perverso’.

[[v18-9-23]]

^<<v18-9-23,23>>^ Quando uma praga vem repentinamente, ele ri da morte dos inocentes.

[[v18-9-24]]

^<<v18-9-24,24>>^ A terra está nas mãos dos perversos, e ele cega os olhos dos juízes; se não é Deus quem faz isso, então quem é?

[[v18-9-25]]

^<<v18-9-25,25>>^ "Minha vida corre mais depressa que um atleta, foge sem jamais ver a alegria.

[[v18-9-26]]

^<<v18-9-26,26>>^ Desaparece como um barco veloz de papiro, como a águia que se lança sobre a presa.

[[v18-9-27]]

^<<v18-9-27,27>>^ Se eu decidisse esquecer minhas queixas, deixar de lado a tristeza e exibir um rosto alegre,

[[v18-9-28]]

^<<v18-9-28,28>>^ ainda assim temeria todos os meus sofrimentos, pois sei, ó Deus, que não me considerarás inocente.

[[v18-9-29]]

^<<v18-9-29,29>>^ Não importa o que aconteça, serei considerado culpado; então de que adianta continuar lutando?

[[v18-9-30]]

^<<v18-9-30,30>>^ Mesmo que eu me lave com sabão e limpe as mãos com soda,

[[v18-9-31]]

^<<v18-9-31,31>>^ tu me lançarás num poço de lodo, e até minhas roupas terão nojo de mim.

[[v18-9-32]]

^<<v18-9-32,32>>^ "Deus não é ser humano, como eu; não posso discutir com ele nem levá-lo ao tribunal.

[[v18-9-33]]

^<<v18-9-33,33>>^ Se ao menos houvesse um mediador entre nós, alguém que nos aproximasse um do outro!

[[v18-9-34]]

^<<v18-9-34,34>>^ Ele afastaria de mim o castigo de Deus, e eu já não viveria aterrorizado.

[[v18-9-35]]

^<<v18-9-35,35>>^ Então falaria com ele sem medo, mas, sozinho, não consigo fazê-lo."

'''

xref:018-jo/018-jo-008.adoc#v18-8-0[&#60; Capítulo Anterior] | <<v18-9-0,Topo>> | xref:018-jo/018-jo-010.adoc#v18-10-0[Próximo Capítulo &#62;]