include::./index.adoc[]

[[v18-11-0]]
=== Jó, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v18-11-1]]

^<<v18-11-1,1>>^ Então Zofar, de Naamá, respondeu a Jó:

[[v18-11-2]]

^<<v18-11-2,2>>^ "Não haverá resposta a essa torrente de palavras? Uma pessoa é inocentada só por falar muito?

[[v18-11-3]]

^<<v18-11-3,3>>^ Devem todos calar-se enquanto você continua a tagarelar? Quando zomba de Deus, ninguém o repreenderá?

[[v18-11-4]]

^<<v18-11-4,4>>^ Você afirma: ‘Minhas crenças são puras’ e ‘Sou limpo aos olhos de Deus’.

[[v18-11-5]]

^<<v18-11-5,5>>^ Se ao menos Deus se pronunciasse e lhe dissesse o que pensa!

[[v18-11-6]]

^<<v18-11-6,6>>^ Se ao menos lhe revelasse os segredos da sabedoria, pois a verdadeira sabedoria não é coisa simples! Escute! Deus sem dúvida o está castigando muito menos do que você merece.

[[v18-11-7]]

^<<v18-11-7,7>>^ "Acaso você pode desvendar os mistérios de Deus e descobrir tudo sobre o Todo-poderoso?

[[v18-11-8]]

^<<v18-11-8,8>>^ Esse conhecimento é mais alto que os céus, e o que você pode fazer? É mais profundo que o abismo, e o que você pode saber?

[[v18-11-9]]

^<<v18-11-9,9>>^ É mais vasto que a terra e mais amplo que o mar.

[[v18-11-10]]

^<<v18-11-10,10>>^ Se Deus passa e prende alguém ou convoca o tribunal, quem pode detê-lo?

[[v18-11-11]]

^<<v18-11-11,11>>^ Pois ele conhece os falsos e registra seus pecados.

[[v18-11-12]]

^<<v18-11-12,12>>^ É tão impossível um tolo tornar-se sábio como um jumento selvagem dar à luz uma criança.

[[v18-11-13]]

^<<v18-11-13,13>>^ "Se ao menos você preparasse o coração e levantasse as mãos a Deus em oração!

[[v18-11-14]]

^<<v18-11-14,14>>^ Livre-se de seus pecados e deixe toda a maldade para trás.

[[v18-11-15]]

^<<v18-11-15,15>>^ Então seu rosto se iluminará com a inocência; você será forte e não terá medo.

[[v18-11-16]]

^<<v18-11-16,16>>^ Você se esquecerá de seus sofrimentos; serão como águas passadas.

[[v18-11-17]]

^<<v18-11-17,17>>^ Sua vida será mais luminosa que o meio-dia; até a escuridão será clara como a manhã.

[[v18-11-18]]

^<<v18-11-18,18>>^ Você se sentirá seguro, pois terá esperança; estará protegido e descansará tranquilo.

[[v18-11-19]]

^<<v18-11-19,19>>^ Sem medo se deitará, e muitos buscarão sua ajuda.

[[v18-11-20]]

^<<v18-11-20,20>>^ Os perversos, porém, ficarão cegos, sem ter para onde fugir; sua única esperança será a morte".

'''

xref:018-jo/018-jo-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-jo/018-jo-012.adoc#v18-12-0[Próximo Capítulo &#62;]