include::./index.adoc[]

[[v18-34-0]]
=== Jó, 34
// nvt ?, NVT - Nova Versão Transformadora

[[v18-34-1]]

^<<v18-34-1,1>>^ Então Eliú disse:

[[v18-34-2]]

^<<v18-34-2,2>>^ "Ouçam-me, vocês que são sábios; prestem atenção, vocês que têm conhecimento.

[[v18-34-3]]

^<<v18-34-3,3>>^ Jó disse: ‘O ouvido prova as palavras que ouve, assim como a língua distingue os sabores’.

[[v18-34-4]]

^<<v18-34-4,4>>^ Portanto, vamos discernir para nós mesmos o que é certo; vamos descobrir juntos o que é bom.

[[v18-34-5]]

^<<v18-34-5,5>>^ Pois Jó também disse: ‘Sou inocente, mas Deus tirou de mim meus direitos.

[[v18-34-6]]

^<<v18-34-6,6>>^ Sou inocente, mas eles me chamam de mentiroso; minha dor é incurável, embora eu não tenha pecado’.

[[v18-34-7]]

^<<v18-34-7,7>>^ "Digam-me, alguma vez houve um homem como Jó, com sua sede por palavras irreverentes?

[[v18-34-8]]

^<<v18-34-8,8>>^ Escolhe como companheiros os que praticam o mal e anda com homens perversos.

[[v18-34-9]]

^<<v18-34-9,9>>^ Chegou até a dizer: ‘Por que desperdiçar meu tempo tentando agradar a Deus?’.

[[v18-34-10]]

^<<v18-34-10,10>>^ "Ouçam-me, vocês que têm entendimento: Deus não peca de forma alguma! O Todo-poderoso não pratica o mal!

[[v18-34-11]]

^<<v18-34-11,11>>^ Ele retribui a cada um de acordo com seus atos; trata as pessoas como merecem.

[[v18-34-12]]

^<<v18-34-12,12>>^ Na verdade, Deus não fará o mal; o Todo-poderoso não cometerá injustiça.

[[v18-34-13]]

^<<v18-34-13,13>>^ Quem entregou a terra aos cuidados de Deus? Quem o fez responsável por todo o mundo?

[[v18-34-14]]

^<<v18-34-14,14>>^ Se Deus retirasse seu espírito e removesse seu sopro,

[[v18-34-15]]

^<<v18-34-15,15>>^ toda a vida cessaria, e a humanidade voltaria ao pó.

[[v18-34-16]]

^<<v18-34-16,16>>^ "Portanto, se você é sábio, ouça-me; preste atenção ao que digo.

[[v18-34-17]]

^<<v18-34-17,17>>^ Acaso Deus poderia governar se odiasse a justiça? Você pretende condenar o Juiz todo-poderoso?

[[v18-34-18]]

^<<v18-34-18,18>>^ Ele diz aos reis: ‘Vocês são perversos’, e aos nobres: ‘Vocês são injustos’.

[[v18-34-19]]

^<<v18-34-19,19>>^ Para Deus, não importa a posição da pessoa; ele não dá mais atenção aos ricos que aos pobres, pois todos foram criados por ele.

[[v18-34-20]]

^<<v18-34-20,20>>^ Morrem de repente, falecem no meio da noite; os poderosos são removidos sem a ajuda de mãos humanas.

[[v18-34-21]]

^<<v18-34-21,21>>^ "Pois Deus observa como as pessoas vivem; ele vê tudo que fazem.

[[v18-34-22]]

^<<v18-34-22,22>>^ Não há escuridão densa o bastante onde os perversos possam se esconder de seus olhos.

[[v18-34-23]]

^<<v18-34-23,23>>^ Não são as pessoas que decidem o momento em que comparecerão diante de Deus para ser julgadas.

[[v18-34-24]]

^<<v18-34-24,24>>^ Ele destrói os poderosos sem consultar ninguém e põe outros em seu lugar.

[[v18-34-25]]

^<<v18-34-25,25>>^ Ele sabe o que fazem e à noite os derruba e os destrói.

[[v18-34-26]]

^<<v18-34-26,26>>^ Ele os fere porque são perversos e os castiga em público, para que todos vejam.

[[v18-34-27]]

^<<v18-34-27,27>>^ Pois deixaram de segui-lo e não têm respeito algum por seus caminhos.

[[v18-34-28]]

^<<v18-34-28,28>>^ Fazem os pobres clamar e chamar a atenção de Deus, e ele ouve os gritos dos aflitos.

[[v18-34-29]]

^<<v18-34-29,29>>^ Mas, se ele permanecer calado, quem o criticará? Quando ele esconde seu rosto, ninguém pode encontrá-lo, nem indivíduo nem nação.

[[v18-34-30]]

^<<v18-34-30,30>>^ Ele impede que os ímpios governem, para que não sejam uma cilada para o povo.

[[v18-34-31]]

^<<v18-34-31,31>>^ "Por que ninguém diz a Deus: ‘Pequei, mas não voltarei a pecar’?

[[v18-34-32]]

^<<v18-34-32,32>>^ Ou: ‘Não sei qual foi meu erro; mostra-me se fiz o mal, e deixarei de fazê-lo de imediato’?

[[v18-34-33]]

^<<v18-34-33,33>>^ "Acaso Deus deve adaptar a justiça dele a suas exigências? Você o rejeitou! A escolha é sua, não minha; compartilhe sua sabedoria conosco.

[[v18-34-34]]

^<<v18-34-34,34>>^ Afinal, pessoas inteligentes me dirão, e os sábios que me ouvem falarão:

[[v18-34-35]]

^<<v18-34-35,35>>^ ‘Jó fala por ignorância; suas palavras não fazem sentido’.

[[v18-34-36]]

^<<v18-34-36,36>>^ Jó, você merece o castigo mais severo pelo modo perverso como falou.

[[v18-34-37]]

^<<v18-34-37,37>>^ Pois, ao seu pecado, acrescentou a rebeldia; não mostra respeito e não para de falar contra Deus".

'''

xref:018-jo/018-jo-033.adoc#v18-33-0[&#60; Capítulo Anterior] | <<v18-34-0,Topo>> | xref:018-jo/018-jo-035.adoc#v18-35-0[Próximo Capítulo &#62;]