include::./index.adoc[]

[[v18-4-0]]
=== Jó, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v18-4-1]]

^<<v18-4-1,1>>^ Então Elifaz, de Temã, respondeu a Jó:

[[v18-4-2]]

^<<v18-4-2,2>>^ "Você terá paciência e me permitirá dizer algo? Afinal, quem poderia permanecer calado?

[[v18-4-3]]

^<<v18-4-3,3>>^ Você já deu ânimo a muita gente e deu força aos fracos.

[[v18-4-4]]

^<<v18-4-4,4>>^ Suas palavras sustentaram os que tropeçavam, e você deu apoio aos vacilantes.

[[v18-4-5]]

^<<v18-4-5,5>>^ Mas agora, quando vem a aflição, você desanima; quando é atingido por ela, entra em pânico.

[[v18-4-6]]

^<<v18-4-6,6>>^ Seu temor a Deus não lhe dá confiança? Sua vida íntegra não lhe traz esperança?

[[v18-4-7]]

^<<v18-4-7,7>>^ "Pense bem! Acaso os inocentes morrem? Quando os justos foram destruídos?

[[v18-4-8]]

^<<v18-4-8,8>>^ Pelo que tenho observado, os que cultivam a maldade e semeiam a opressão, isso também é o que colhem.

[[v18-4-9]]

^<<v18-4-9,9>>^ Um sopro de Deus os destrói; desaparecem com uma rajada de sua ira.

[[v18-4-10]]

^<<v18-4-10,10>>^ O leão ruge e seu filhote rosna, mas os dentes dos leões jovens são quebrados.

[[v18-4-11]]

^<<v18-4-11,11>>^ O leão feroz morre de fome porque não há presa, e os filhotes da leoa se dispersam.

[[v18-4-12]]

^<<v18-4-12,12>>^ "Esta verdade me foi revelada em segredo, como que sussurrada em meu ouvido.

[[v18-4-13]]

^<<v18-4-13,13>>^ Ela veio à noite, numa visão perturbadora, quando todos estão em sono profundo.

[[v18-4-14]]

^<<v18-4-14,14>>^ O medo e o terror se apoderaram de mim e fizeram estremecer meus ossos.

[[v18-4-15]]

^<<v18-4-15,15>>^ Um espírito passou diante de meu rosto, e os pelos de meu corpo se arrepiaram.

[[v18-4-16]]

^<<v18-4-16,16>>^ O espírito parou, mas não pude ver sua forma; um vulto estava diante de meus olhos. No silêncio, ouvi uma voz dizer:

[[v18-4-17]]

^<<v18-4-17,17>>^ ‘Pode algum mortal ser inocente perante Deus? Pode o homem ser puro diante do Criador?’.

[[v18-4-18]]

^<<v18-4-18,18>>^ "Se Deus não confia nos próprios anjos e acusa seus mensageiros de insensatez,

[[v18-4-19]]

^<<v18-4-19,19>>^ quanto menos confiará em pessoas feitas de barro! Vêm do pó e são facilmente destruídas, como traças.

[[v18-4-20]]

^<<v18-4-20,20>>^ Estão vivas pela manhã e mortas ao entardecer; desaparecem para sempre, sem deixar vestígio.

[[v18-4-21]]

^<<v18-4-21,21>>^ As cordas de sua tenda são arrancadas e a tenda desaba, e na ignorância morrem."

'''

xref:018-jo/018-jo-003.adoc#v18-3-0[&#60; Capítulo Anterior] | <<v18-4-0,Topo>> | xref:018-jo/018-jo-005.adoc#v18-5-0[Próximo Capítulo &#62;]