include::./index.adoc[]

[[v18-21-0]]
=== Jó, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v18-21-1]]

^<<v18-21-1,1>>^ Então Jó falou novamente:

[[v18-21-2]]

^<<v18-21-2,2>>^ "Escutem com atenção o que eu digo; essa é a consolação que podem me dar.

[[v18-21-3]]

^<<v18-21-3,3>>^ Enquanto eu estiver falando, tenham paciência; depois que tiver falado, podem continuar a zombar de mim.

[[v18-21-4]]

^<<v18-21-4,4>>^ "Minha queixa não é contra seres humanos; tenho bons motivos para estar impaciente.

[[v18-21-5]]

^<<v18-21-5,5>>^ Olhem para mim, e ficarão pasmos; assustados, colocarão a mão sobre a boca.

[[v18-21-6]]

^<<v18-21-6,6>>^ Quando penso no que estou dizendo, fico arrepiado; todo o meu corpo estremece.

[[v18-21-7]]

^<<v18-21-7,7>>^ "Por que os perversos continuam com vida, chegam à velhice e se tornam poderosos?

[[v18-21-8]]

^<<v18-21-8,8>>^ Veem seus filhos crescer e se estabelecer e desfrutam a companhia de seus netos.

[[v18-21-9]]

^<<v18-21-9,9>>^ Seus lares são seguros e livres de todo medo, e Deus não os castiga.

[[v18-21-10]]

^<<v18-21-10,10>>^ Seus touros nunca deixam de procriar, suas vacas dão crias e não abortam.

[[v18-21-11]]

^<<v18-21-11,11>>^ Deixam seus filhos brincar como cordeiros; seus pequeninos saltam e dançam.

[[v18-21-12]]

^<<v18-21-12,12>>^ Cantam com tamborins e harpas e celebram ao som da flauta.

[[v18-21-13]]

^<<v18-21-13,13>>^ Passam os dias em prosperidade e descem à sepultura em paz.

[[v18-21-14]]

^<<v18-21-14,14>>^ E, no entanto, dizem a Deus: ‘Deixa-nos em paz! Não queremos saber de ti nem de teus caminhos.

[[v18-21-15]]

^<<v18-21-15,15>>^ Quem é o Todo-poderoso e por que deveríamos lhe obedecer? De que nos adiantará orar?’.

[[v18-21-16]]

^<<v18-21-16,16>>^ Acreditam que a prosperidade depende de si mesmos, mas eu quero distância desse modo de pensar.

[[v18-21-17]]

^<<v18-21-17,17>>^ "Quantas vezes a luz dos perversos se apaga? Quantas vezes sofrem desgraças? Acaso Deus, em sua ira, lhes reparte tristezas?

[[v18-21-18]]

^<<v18-21-18,18>>^ Quantas vezes são carregados pelo vento, como palha, ou levados embora pela tempestade, como ciscos?

[[v18-21-19]]

^<<v18-21-19,19>>^ "Vocês dizem: ‘Ao menos Deus castiga os filhos deles!’. Mas eu digo que ele deveria castigar os pais, para que entendam seu juízo.

[[v18-21-20]]

^<<v18-21-20,20>>^ Que seus próprios olhos vejam sua destruição; que eles mesmos bebam da ira do Todo-poderoso!

[[v18-21-21]]

^<<v18-21-21,21>>^ Afinal, depois de mortos, não se importarão com o que acontece à sua família.

[[v18-21-22]]

^<<v18-21-22,22>>^ "Mas quem pode dar lições a Deus, uma vez que ele julga até os mais poderosos?

[[v18-21-23]]

^<<v18-21-23,23>>^ Um morre em prosperidade, confortável e seguro,

[[v18-21-24]]

^<<v18-21-24,24>>^ um retrato perfeito de boa saúde, em excelente forma e cheio de vigor.

[[v18-21-25]]

^<<v18-21-25,25>>^ Outro morre em amarga pobreza, sem nunca ter experimentado as coisas boas da vida.

[[v18-21-26]]

^<<v18-21-26,26>>^ Ambos, porém, são enterrados no mesmo pó; ambos são comidos pelos mesmos vermes.

[[v18-21-27]]

^<<v18-21-27,27>>^ "Sei o que estão pensando, sei dos planos que tramam contra mim.

[[v18-21-28]]

^<<v18-21-28,28>>^ ‘Onde está a casa dos ricos?’, vocês me dirão. ‘Onde está a casa dos perversos?’

[[v18-21-29]]

^<<v18-21-29,29>>^ Perguntem, porém, àqueles que viajam, e eles lhes dirão a verdade.

[[v18-21-30]]

^<<v18-21-30,30>>^ Os perversos são poupados no dia da calamidade e socorridos no dia da fúria.

[[v18-21-31]]

^<<v18-21-31,31>>^ Ninguém os critica abertamente, nem lhes dá o que merecem por seus atos.

[[v18-21-32]]

^<<v18-21-32,32>>^ Quando são levados à sepultura, uma guarda de honra vigia seu túmulo.

[[v18-21-33]]

^<<v18-21-33,33>>^ A terra lhes dá doce repouso, e uma grande multidão acompanha o funeral e presta homenagens enquanto o corpo é sepultado.

[[v18-21-34]]

^<<v18-21-34,34>>^ "Como podem suas palavras vazias me consolar? Suas explicações não passam de mentiras!".

'''

xref:018-jo/018-jo-020.adoc#v18-20-0[&#60; Capítulo Anterior] | <<v18-21-0,Topo>> | xref:018-jo/018-jo-022.adoc#v18-22-0[Próximo Capítulo &#62;]