include::./index.adoc[]

[[v18-20-0]]
=== Jó, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v18-20-1]]

^<<v18-20-1,1>>^ Então Zofar, de Naamá, respondeu:

[[v18-20-2]]

^<<v18-20-2,2>>^ "Preciso falar, pois é profundo meu incômodo.

[[v18-20-3]]

^<<v18-20-3,3>>^ Tive de suportar seus insultos, mas agora meu espírito me leva a responder.

[[v18-20-4]]

^<<v18-20-4,4>>^ "Você não sabe que, desde a antiguidade, desde que o ser humano foi posto na terra,

[[v18-20-5]]

^<<v18-20-5,5>>^ o triunfo dos perversos dura pouco, e a alegria dos ímpios é apenas temporária?

[[v18-20-6]]

^<<v18-20-6,6>>^ Embora seu orgulho chegue aos céus, e sua cabeça toque as nuvens,

[[v18-20-7]]

^<<v18-20-7,7>>^ eles desaparecerão para sempre, lançados fora como seu próprio excremento. Seus conhecidos perguntarão: ‘Onde estão eles?’.

[[v18-20-8]]

^<<v18-20-8,8>>^ Passarão como um sonho e não serão encontrados; desaparecerão como uma visão na noite.

[[v18-20-9]]

^<<v18-20-9,9>>^ Aqueles que os viram, não os verão mais; suas famílias não os reconhecerão.

[[v18-20-10]]

^<<v18-20-10,10>>^ Seus filhos pedirão esmolas aos pobres, pois terão de devolver as riquezas que roubaram.

[[v18-20-11]]

^<<v18-20-11,11>>^ Embora sejam jovens e vigorosos, seus ossos serão deitados no pó.

[[v18-20-12]]

^<<v18-20-12,12>>^ "Desfrutaram o doce gosto da perversidade e a deixaram derreter sob a língua.

[[v18-20-13]]

^<<v18-20-13,13>>^ Ficaram com ela na boca, para melhor saboreá-la.

[[v18-20-14]]

^<<v18-20-14,14>>^ De repente, a comida azeda em seu estômago; torna-se veneno de serpente em seu interior.

[[v18-20-15]]

^<<v18-20-15,15>>^ Vomitarão a riqueza que engoliram; Deus não permitirá que a retenham.

[[v18-20-16]]

^<<v18-20-16,16>>^ Sugarão veneno de cobra; a língua da víbora os matará.

[[v18-20-17]]

^<<v18-20-17,17>>^ Nunca mais desfrutarão os ribeiros, os rios de onde emanam leite e mel.

[[v18-20-18]]

^<<v18-20-18,18>>^ Devolverão tudo pelo que trabalharam; sua riqueza não lhes trará alegria.

[[v18-20-19]]

^<<v18-20-19,19>>^ Pois oprimiram os pobres e os deixaram desamparados; tomaram casas que não haviam construído.

[[v18-20-20]]

^<<v18-20-20,20>>^ Sempre gananciosos, nunca satisfeitos; perderam tudo com que sonharam.

[[v18-20-21]]

^<<v18-20-21,21>>^ Comem até se fartar e, depois, não sobra coisa alguma; por isso, sua prosperidade não durará.

[[v18-20-22]]

^<<v18-20-22,22>>^ "Em meio à fartura, enfrentarão aflições, e o sofrimento os dominará.

[[v18-20-23]]

^<<v18-20-23,23>>^ Que Deus lhes encha o estômago de problemas; que Deus faça chover sobre eles sua ira ardente!

[[v18-20-24]]

^<<v18-20-24,24>>^ Quando tentarem escapar da arma de ferro, a flecha com ponta de bronze os atravessará.

[[v18-20-25]]

^<<v18-20-25,25>>^ Quando a flecha lhes for arrancada das costas, a ponta brilhará com sangue. O terror da morte virá sobre eles;

[[v18-20-26]]

^<<v18-20-26,26>>^ seus tesouros serão lançados em profunda escuridão. Um fogo descontrolado os devorará e consumirá tudo que lhes resta.

[[v18-20-27]]

^<<v18-20-27,27>>^ Os céus revelarão a culpa dos perversos; a terra se levantará contra eles.

[[v18-20-28]]

^<<v18-20-28,28>>^ Uma inundação arrastará suas casas; a ira de Deus cairá sobre eles como chuva torrencial.

[[v18-20-29]]

^<<v18-20-29,29>>^ Essa é a recompensa que Deus dá aos perversos; é a herança decretada por Deus".

'''

xref:018-jo/018-jo-019.adoc#v18-19-0[&#60; Capítulo Anterior] | <<v18-20-0,Topo>> | xref:018-jo/018-jo-021.adoc#v18-21-0[Próximo Capítulo &#62;]