include::./index.adoc[]

[[v54-6-0]]
=== 1 Timóteo, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v54-6-1]]

^<<v54-6-1,1>>^ Os escravos devem ter todo o respeito por seus senhores, para não envergonharem o nome de Deus e seus ensinamentos.

[[v54-6-2]]

^<<v54-6-2,2>>^ O fato de o senhor ser irmão na fé não é desculpa para deixarem de respeitá-lo. Pelo contrário, devem trabalhar ainda mais arduamente, pois seus esforços beneficiam outros irmãos amados. Ensine estas coisas e incentive todos a obedecer-lhes.

[[v54-6-3]]

^<<v54-6-3,3>>^ Talvez alguns nos contradigam, mas estes são os verdadeiros ensinamentos do Senhor Jesus Cristo, que conduzem a uma vida de devoção. Quem ensina algo diferente

[[v54-6-4]]

^<<v54-6-4,4>>^ é arrogante e sem entendimento. Vive com o desejo doentio de discutir o significado das palavras e provoca contendas que resultam em inveja, divisão, difamação e suspeitas malignas.

[[v54-6-5]]

^<<v54-6-5,5>>^ Pessoas assim sempre causam problemas. Têm a mente corrompida e deram as costas à verdade. Para elas, a vida de devoção é apenas uma forma de enriquecer.

[[v54-6-6]]

^<<v54-6-6,6>>^ No entanto, a devoção acompanhada de contentamento é, em si mesma, grande riqueza.

[[v54-6-7]]

^<<v54-6-7,7>>^ Afinal, não trouxemos nada conosco quando viemos ao mundo, e nada levaremos quando o deixarmos.

[[v54-6-8]]

^<<v54-6-8,8>>^ Portanto, se temos alimento e roupa, estejamos contentes.

[[v54-6-9]]

^<<v54-6-9,9>>^ Mas aqueles que desejam enriquecer caem em tentações e armadilhas e em muitos desejos tolos e nocivos, que os levam à ruína e destruição.

[[v54-6-10]]

^<<v54-6-10,10>>^ Pois o amor ao dinheiro é a raiz de todo mal. E alguns, por tanto desejarem dinheiro, desviaram-se da fé e afligiram a si mesmos com muitos sofrimentos.

[[v54-6-11]]

^<<v54-6-11,11>>^ Você, porém, que é um homem de Deus, fuja de todas essas coisas más. Busque a justiça, a devoção e também a fé, o amor, a perseverança e a mansidão.

[[v54-6-12]]

^<<v54-6-12,12>>^ Lute o bom combate da fé. Apegue-se firmemente à vida eterna para a qual foi chamado e que tão bem você declarou na presença de muitas testemunhas.

[[v54-6-13]]

^<<v54-6-13,13>>^ Diante de Deus, que a todos dá vida, e de Cristo Jesus, que deu bom testemunho perante Pôncio Pilatos, encarrego-o

[[v54-6-14]]

^<<v54-6-14,14>>^ de obedecer a esta ordem sem vacilar. Assim, ninguém poderá acusá-lo de coisa alguma, desde agora até a volta de nosso Senhor Jesus Cristo.

[[v54-6-15]]

^<<v54-6-15,15>>^ Pois: No devido tempo ele será revelado do céu pelo bendito e único Deus todo-poderoso, o Rei dos reis e Senhor dos senhores.

[[v54-6-16]]

^<<v54-6-16,16>>^ Somente a ele pertence a imortalidade, e ele habita em luz tão resplandecente que nenhum ser humano pode se aproximar dele. Ninguém jamais o viu, nem pode ver. A ele sejam honra e poder para sempre! Amém.

[[v54-6-17]]

^<<v54-6-17,17>>^ Ensine aos ricos deste mundo que não se orgulhem nem confiem em seu dinheiro, que é incerto. Sua confiança deve estar em Deus, que provê ricamente tudo de que necessitamos para nossa satisfação.

[[v54-6-18]]

^<<v54-6-18,18>>^ Diga-lhes que usem seu dinheiro para fazer o bem. Devem ser ricos em boas obras e generosos com os necessitados, sempre prontos a repartir.

[[v54-6-19]]

^<<v54-6-19,19>>^ Desse modo, acumularão tesouros para si como um alicerce firme para o futuro, a fim de experimentarem a verdadeira vida.

[[v54-6-20]]

^<<v54-6-20,20>>^ Timóteo, guarde aquilo que Deus lhe confiou. Evite discussões profanas e tolas com aqueles que se opõem a você com suposto conhecimento.

[[v54-6-21]]

^<<v54-6-21,21>>^ Alguns se desviaram da fé por seguirem essas tolices. Que a graça de Deus esteja com vocês.

'''

xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[Próximo Capítulo &#62;]