include::./index.adoc[]

[[v54-5-0]]
=== 1 Timóteo, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v54-5-1]]

^<<v54-5-1,1>>^ Nunca fale com dureza a um homem mais velho, mas aconselhe-o como faria com seu próprio pai. Quanto aos mais jovens, aconselhe-os como a irmãos.

[[v54-5-2]]

^<<v54-5-2,2>>^ Trate as mulheres mais velhas como trataria sua mãe, e as mais jovens, com toda pureza, como se fossem suas irmãs.

[[v54-5-3]]

^<<v54-5-3,3>>^ Cuide das viúvas que não têm ninguém para ajudá-las.

[[v54-5-4]]

^<<v54-5-4,4>>^ Mas, se elas tiverem filhos ou netos, a primeira responsabilidade deles é mostrar devoção no lar e retribuir aos pais o cuidado recebido. Isso é algo que agrada a Deus.

[[v54-5-5]]

^<<v54-5-5,5>>^ A verdadeira viúva, uma mulher sozinha no mundo, põe sua esperança em Deus. Dia e noite, faz súplicas e orações.

[[v54-5-6]]

^<<v54-5-6,6>>^ Mas a viúva que vive apenas para o prazer está morta, ainda que esteja viva.

[[v54-5-7]]

^<<v54-5-7,7>>^ Dê essas instruções, para que ninguém fique sujeito a críticas.

[[v54-5-8]]

^<<v54-5-8,8>>^ Aqueles que não cuidam dos seus, especialmente dos de sua própria família, negaram a fé e são piores que os descrentes.

[[v54-5-9]]

^<<v54-5-9,9>>^ A viúva incluída na lista para receber sustento deve ter pelo menos sessenta anos e ter sido esposa de um só marido.

[[v54-5-10]]

^<<v54-5-10,10>>^ Deve ser respeitada pelo bem que praticou, como alguém que soube criar os filhos, foi hospitaleira, serviu o povo santo com humildade, ajudou os que estavam em dificuldade e sempre se dedicou a fazer o bem.

[[v54-5-11]]

^<<v54-5-11,11>>^ As viúvas mais jovens não devem fazer parte dessa lista, pois, quando seus desejos físicos forem mais fortes que sua devoção a Cristo, desejarão se casar novamente.

[[v54-5-12]]

^<<v54-5-12,12>>^ Assim se tornarão culpadas de quebrar o compromisso que fizeram.

[[v54-5-13]]

^<<v54-5-13,13>>^ Além disso, aprenderão a se tornar ociosas e a andar de casa em casa, fazendo fofoca, intrometendo-se em assuntos alheios e falando do que não devem.

[[v54-5-14]]

^<<v54-5-14,14>>^ Portanto, aconselho que essas viúvas mais jovens se casem de novo, tenham filhos e tomem conta do próprio lar. Então o inimigo não poderá dizer coisa alguma contra elas.

[[v54-5-15]]

^<<v54-5-15,15>>^ Pois, de fato, algumas já se desviaram e agora seguem Satanás.

[[v54-5-16]]

^<<v54-5-16,16>>^ Se alguma irmã na fé tem viúvas na família, deve tomar conta delas e não sobrecarregar a igreja, que assim poderá cuidar das viúvas que estiverem verdadeiramente sozinhas.

[[v54-5-17]]

^<<v54-5-17,17>>^ Os presbíteros que fazem bem seu trabalho devem receber honra redobrada, especialmente os que se dedicam arduamente à pregação e ao ensino.

[[v54-5-18]]

^<<v54-5-18,18>>^ Pois as Escrituras dizem: "Não amordacem o boi para impedir que ele coma enquanto debulha os cereais", e também: "Aqueles que trabalham merecem seu salário".

[[v54-5-19]]

^<<v54-5-19,19>>^ Não aceite acusação contra um presbítero sem que seja confirmada por duas ou três testemunhas.

[[v54-5-20]]

^<<v54-5-20,20>>^ Aqueles que pecarem devem ser repreendidos diante de todos, o que servirá de forte advertência para os demais.

[[v54-5-21]]

^<<v54-5-21,21>>^ Ordeno solenemente, na presença de Deus, de Cristo Jesus e dos anjos eleitos que você obedeça a estas instruções sem tomar partido nem demonstrar favoritismo.

[[v54-5-22]]

^<<v54-5-22,22>>^ Não se apresse em nomear um líder. Não participe dos pecados alheios. Mantenha-se puro.

[[v54-5-23]]

^<<v54-5-23,23>>^ Não beba apenas água. Uma vez que você fica doente com frequência, tome um pouco de vinho por causa de seu estômago.

[[v54-5-24]]

^<<v54-5-24,24>>^ Lembre-se de que os pecados de alguns são evidentes, e seu julgamento é inevitável. Há outros, porém, cujos pecados só serão revelados mais tarde.

[[v54-5-25]]

^<<v54-5-25,25>>^ Da mesma forma, as boas obras de alguns são evidentes, e outras, feitas em segredo, um dia serão conhecidas.

'''

xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[&#60; Capítulo Anterior] | <<v54-5-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[Próximo Capítulo &#62;]