include::./index.adoc[]

[[v54-4-0]]
=== 1 Timóteo, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v54-4-1]]

^<<v54-4-1,1>>^ O Espírito afirma claramente que nos últimos tempos alguns se desviarão da fé, dando ouvidos a espíritos enganadores e a ensinamentos de demônios,

[[v54-4-2]]

^<<v54-4-2,2>>^ que vêm de indivíduos hipócritas e mentirosos, cuja consciência está morta.

[[v54-4-3]]

^<<v54-4-3,3>>^ Tais pessoas afirmam que é errado se casar e proíbem que se comam certos alimentos, que Deus criou para serem recebidos com ação de graças pelos que são fiéis e conhecedores da verdade.

[[v54-4-4]]

^<<v54-4-4,4>>^ Porque tudo que Deus fez é bom, não devemos rejeitar nada, mas a tudo receber com ação de graças,

[[v54-4-5]]

^<<v54-4-5,5>>^ pois sabemos que se torna aceitável pela palavra de Deus e pela oração.

[[v54-4-6]]

^<<v54-4-6,6>>^ Se você explicar estas coisas aos irmãos, será um bom servo de Cristo Jesus, nutrido pela mensagem da fé e pelo bom ensino que tem seguido.

[[v54-4-7]]

^<<v54-4-7,7>>^ Não perca tempo discutindo mitos profanos e crendices absurdas. Em vez disso, exercite-se na devoção.

[[v54-4-8]]

^<<v54-4-8,8>>^ "O exercício físico tem algum valor, mas exercitar-se na devoção é muito melhor, pois promete benefícios não apenas nesta vida, mas também na vida futura."

[[v54-4-9]]

^<<v54-4-9,9>>^ Essa é uma afirmação digna de confiança, e todos devem aceitá-la.

[[v54-4-10]]

^<<v54-4-10,10>>^ Trabalhamos arduamente e continuamos a lutar porque nossa esperança está no Deus vivo, o Salvador de todos, especialmente dos que creem.

[[v54-4-11]]

^<<v54-4-11,11>>^ Ensine estas coisas e insista nelas.

[[v54-4-12]]

^<<v54-4-12,12>>^ Não deixe que ninguém o menospreze porque você é jovem. Seja exemplo para todos os fiéis nas palavras, na conduta, no amor, na fé e na pureza.

[[v54-4-13]]

^<<v54-4-13,13>>^ Até minha chegada, dedique-se à leitura pública das Escrituras, ao encorajamento e ao ensino.

[[v54-4-14]]

^<<v54-4-14,14>>^ Não descuide do dom que recebeu por meio de profecia quando os presbíteros impuseram as mãos sobre você.

[[v54-4-15]]

^<<v54-4-15,15>>^ Dedique total atenção a essas questões. Entregue-se inteiramente a suas tarefas, para que todos vejam seu progresso.

[[v54-4-16]]

^<<v54-4-16,16>>^ Fique atento a seu modo de viver e a seus ensinamentos. Permaneça fiel ao que é certo, e assim salvará a si mesmo e àqueles que o ouvem.

'''

xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[&#60; Capítulo Anterior] | <<v54-4-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[Próximo Capítulo &#62;]