include::./index.adoc[]

[[v54-2-0]]
=== 1 Timóteo, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v54-2-1]]

^<<v54-2-1,1>>^ Em primeiro lugar, recomendo que sejam feitas petições, orações, intercessões e ações de graça em favor de todos,

[[v54-2-2]]

^<<v54-2-2,2>>^ em favor dos reis e de todos que exercem autoridade, para que tenhamos uma vida pacífica e tranquila, caracterizada por devoção e dignidade.

[[v54-2-3]]

^<<v54-2-3,3>>^ Isso é bom e agrada a Deus, nosso Salvador,

[[v54-2-4]]

^<<v54-2-4,4>>^ cujo desejo é que todos sejam salvos e conheçam a verdade.

[[v54-2-5]]

^<<v54-2-5,5>>^ Pois: Há um só Deus e um só Mediador entre Deus e a humanidade: o homem Cristo Jesus.

[[v54-2-6]]

^<<v54-2-6,6>>^ Ele deu sua vida para comprar a liberdade de todos. Essa é a mensagem que foi entregue ao mundo no momento oportuno.

[[v54-2-7]]

^<<v54-2-7,7>>^ E eu fui escolhido como pregador e apóstolo para ensinar aos gentios essa mensagem a respeito da fé e da verdade. Não estou mentindo; digo a verdade.

[[v54-2-8]]

^<<v54-2-8,8>>^ Quero, portanto, que em todo lugar de culto os homens orem com mãos santas levantadas, livres de ira e de controvérsias.

[[v54-2-9]]

^<<v54-2-9,9>>^ Da mesma forma, quero que as mulheres tenham discrição em sua aparência. Que usem roupas decentes e apropriadas, sem chamar a atenção pela maneira como arrumam o cabelo ou por usarem ouro, pérolas ou roupas caras.

[[v54-2-10]]

^<<v54-2-10,10>>^ Pois as mulheres que afirmam ser devotas a Deus devem se embelezar com as boas obras que praticam.

[[v54-2-11]]

^<<v54-2-11,11>>^ As mulheres devem aprender em silêncio e com toda submissão.

[[v54-2-12]]

^<<v54-2-12,12>>^ Não permito que as mulheres ensinem aos homens, nem que tenham autoridade sobre eles. Antes, devem ouvir em silêncio.

[[v54-2-13]]

^<<v54-2-13,13>>^ Porque primeiro Deus fez Adão e, depois, Eva.

[[v54-2-14]]

^<<v54-2-14,14>>^ E não foi Adão o enganado. A mulher é que foi enganada, e o resultado foi o pecado.

[[v54-2-15]]

^<<v54-2-15,15>>^ Mas as mulheres serão salvas dando à luz filhos, desde que continuem a viver na fé, no amor e na santidade, com discrição.

'''

xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[Próximo Capítulo &#62;]