include::./index.adoc[]

[[v44-19-0]]
=== Atos, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v44-19-1]]

^<<v44-19-1,1>>^ Enquanto Apolo estava em Corinto, Paulo viajou pelas regiões do interior até chegar a Éfeso, no litoral, onde encontrou alguns discípulos.

[[v44-19-2]]

^<<v44-19-2,2>>^ Ele lhes perguntou: "Vocês receberam o Espírito Santo quando creram?". "Não", responderam eles. "Nem sequer ouvimos que existe o Espírito Santo."

[[v44-19-3]]

^<<v44-19-3,3>>^ "Então que batismo vocês receberam?", perguntou ele. "O batismo de João", responderam.

[[v44-19-4]]

^<<v44-19-4,4>>^ Paulo disse: "João batizava com o batismo de arrependimento, dizendo ao povo que cresse naquele que viria depois, isto é, em Jesus".

[[v44-19-5]]

^<<v44-19-5,5>>^ Assim que ouviram isso, foram batizados em nome do Senhor Jesus.

[[v44-19-6]]

^<<v44-19-6,6>>^ Paulo lhes impôs as mãos e o Espírito Santo veio sobre eles, e falaram em línguas e profetizaram.

[[v44-19-7]]

^<<v44-19-7,7>>^ Eram ao todo uns doze homens.

[[v44-19-8]]

^<<v44-19-8,8>>^ Em seguida, Paulo foi à sinagoga e ali pregou corajosamente durante três meses, argumentando de modo convincente sobre o reino de Deus.

[[v44-19-9]]

^<<v44-19-9,9>>^ Mas alguns deles se mostraram endurecidos, rejeitaram a mensagem e falaram publicamente contra o Caminho. Paulo, então, deixou a sinagoga e levou consigo os discípulos, passando a realizar discussões diárias na escola de Tirano.

[[v44-19-10]]

^<<v44-19-10,10>>^ Isso continuou durante os dois anos seguintes, e gente de toda a província da Ásia, tanto judeus como gregos, ouviu a palavra do Senhor.

[[v44-19-11]]

^<<v44-19-11,11>>^ Deus concedeu a Paulo o poder de realizar milagres extraordinários.

[[v44-19-12]]

^<<v44-19-12,12>>^ Quando lenços ou aventais usados por ele eram colocados sobre enfermos, estes eram curados de suas doenças e deles saíam espíritos malignos.

[[v44-19-13]]

^<<v44-19-13,13>>^ Alguns judeus viajavam pelas cidades expulsando espíritos malignos. Tentavam usar o nome do Senhor Jesus, dizendo: "Ordeno que saia em nome de Jesus, a quem Paulo anuncia!".

[[v44-19-14]]

^<<v44-19-14,14>>^ Os homens que faziam isso eram os sete filhos de Ceva, um dos principais sacerdotes.

[[v44-19-15]]

^<<v44-19-15,15>>^ Certa ocasião, o espírito maligno respondeu: "Eu conheço Jesus e conheço Paulo, mas quem são vocês?".

[[v44-19-16]]

^<<v44-19-16,16>>^ O homem possuído pelo espírito maligno saltou em cima deles e os atacou com tanta violência que fugiram da casa, despidos e feridos.

[[v44-19-17]]

^<<v44-19-17,17>>^ A notícia do ocorrido se espalhou rapidamente por toda a cidade de Éfeso, tanto entre judeus como entre gregos, e sobre eles veio um temor reverente, e o nome do Senhor Jesus era engrandecido.

[[v44-19-18]]

^<<v44-19-18,18>>^ Muitos dos que creram confessaram suas obras pecaminosas.

[[v44-19-19]]

^<<v44-19-19,19>>^ Vários deles, que haviam praticado feitiçaria, trouxeram seus livros de encantamentos e os queimaram publicamente. O valor dos livros totalizou cinquenta mil moedas de prata.

[[v44-19-20]]

^<<v44-19-20,20>>^ Assim, a mensagem a respeito do Senhor se espalhou amplamente e teve efeito poderoso.

[[v44-19-21]]

^<<v44-19-21,21>>^ Depois disso, Paulo se sentiu impelido pelo Espírito a passar pela Macedônia e a Acaia antes de ir a Jerusalém. "E, de lá, devo prosseguir para Roma!", disse ele.

[[v44-19-22]]

^<<v44-19-22,22>>^ Então, enviou adiante dele à Macedônia dois assistentes, Timóteo e Erasto, e permaneceu um pouco mais na província da Ásia.

[[v44-19-23]]

^<<v44-19-23,23>>^ Por essa época, houve enorme tumulto em Éfeso por causa do Caminho.

[[v44-19-24]]

^<<v44-19-24,24>>^ Começou com Demétrio, ourives que fabricava modelos de prata do templo da deusa grega Ártemis e que empregava muitos artífices.

[[v44-19-25]]

^<<v44-19-25,25>>^ Ele os reuniu a outros que trabalhavam em ofícios semelhantes e disse: "Senhores, vocês sabem que nossa prosperidade vem deste empreendimento.

[[v44-19-26]]

^<<v44-19-26,26>>^ Mas, como vocês viram e ouviram, esse sujeito, Paulo, convenceu muita gente de que deuses feitos por mãos humanas não são deuses de verdade. Fez isso não apenas aqui em Éfeso, mas em toda a província.

[[v44-19-27]]

^<<v44-19-27,27>>^ Claro que não me refiro apenas à perda do respeito público por nossa atividade. Também me preocupa que o templo da grande deusa Ártemis perca sua influência e que esta deusa magnífica, adorada em toda a província da Ásia e ao redor do mundo, seja destituída de seu grande prestígio!".

[[v44-19-28]]

^<<v44-19-28,28>>^ Ao ouvir isso, ficaram furiosos e começaram a gritar: "Grande é Ártemis dos efésios!".

[[v44-19-29]]

^<<v44-19-29,29>>^ Em pouco tempo, a cidade toda estava uma confusão. O povo correu para o anfiteatro, arrastando os macedônios Gaio e Aristarco, companheiros de viagem de Paulo.

[[v44-19-30]]

^<<v44-19-30,30>>^ Ele também quis entrar, mas os discípulos não permitiram.

[[v44-19-31]]

^<<v44-19-31,31>>^ Alguns amigos de Paulo, oficiais da província, também lhe enviaram um recado no qual suplicaram que não arriscasse a vida entrando no anfiteatro.

[[v44-19-32]]

^<<v44-19-32,32>>^ Lá dentro, em polvorosa, o povo todo gritava, e cada um dizia uma coisa. Na verdade, a maioria nem sabia por que estava ali.

[[v44-19-33]]

^<<v44-19-33,33>>^ Entre a multidão, os judeus empurraram Alexandre para a frente e ordenaram que explicasse a situação. Ele fez sinal pedindo silêncio e tentou falar.

[[v44-19-34]]

^<<v44-19-34,34>>^ No entanto, quando a multidão percebeu que ele era judeu, começou a gritar novamente e continuou por cerca de duas horas: "Grande é Ártemis dos efésios!".

[[v44-19-35]]

^<<v44-19-35,35>>^ Por fim, o escrivão da cidade conseguiu acalmar a multidão e disse: "Cidadãos de Éfeso, todos sabem que Éfeso é a guardiã do templo da grande Ártemis, cuja imagem caiu do céu para nós.

[[v44-19-36]]

^<<v44-19-36,36>>^ Portanto, sendo este um fato inegável, acalmem-se e não façam nada precipitadamente.

[[v44-19-37]]

^<<v44-19-37,37>>^ Vocês trouxeram estes homens aqui, mas eles não roubaram nada do templo nem disseram coisa alguma contra nossa deusa.

[[v44-19-38]]

^<<v44-19-38,38>>^ "Se Demétrio e seus artífices têm alguma queixa contra eles, os tribunais estão abertos e há oficiais disponíveis para ouvir o caso. Que façam acusações formais.

[[v44-19-39]]

^<<v44-19-39,39>>^ E, se há outras queixas que desejam apresentar, elas podem ser resolvidas em assembleia, conforme a lei.

[[v44-19-40]]

^<<v44-19-40,40>>^ Corremos o perigo de ser acusados de provocar desordem, pois não há motivo para este tumulto. E, se exigirem de nós uma explicação, não teremos o que dizer".

[[v44-19-41]]

^<<v44-19-41,41>>^ Então os despediu, e a multidão se dispersou.

'''

xref:044-atos/044-atos-018.adoc#v44-18-0[&#60; Capítulo Anterior] | <<v44-19-0,Topo>> | xref:044-atos/044-atos-020.adoc#v44-20-0[Próximo Capítulo &#62;]