include::./index.adoc[]

[[v44-27-0]]
=== Atos, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v44-27-1]]

^<<v44-27-1,1>>^ Quando chegou a hora, zarpamos para a Itália. Paulo e muitos outros prisioneiros foram colocados sob a guarda de um oficial romano chamado Júlio, capitão do Regimento Imperial.

[[v44-27-2]]

^<<v44-27-2,2>>^ Aristarco, um macedônio de Tessalônica, nos acompanhou. Partimos num navio que tinha vindo do porto de Adramítio, no litoral noroeste da província da Ásia. Estavam previstas diversas paradas em portos ao longo da costa.

[[v44-27-3]]

^<<v44-27-3,3>>^ No dia seguinte, quando ancoramos em Sidom, Júlio demonstrou bondade a Paulo permitindo-lhe que desembarcasse para visitar amigos e receber ajuda material deles.

[[v44-27-4]]

^<<v44-27-4,4>>^ Quando partimos de lá, fomos costeando a ilha de Chipre, devido aos ventos contrários que tornavam difícil manter o rumo.

[[v44-27-5]]

^<<v44-27-5,5>>^ Prosseguindo por mar aberto, passamos pelo litoral da Cilícia e da Panfília, chegando a Mirra, na província de Lícia.

[[v44-27-6]]

^<<v44-27-6,6>>^ Ali, o oficial no comando encontrou um navio egípcio de Alexandria que estava de partida para a Itália e nos fez embarcar.

[[v44-27-7]]

^<<v44-27-7,7>>^ Navegamos vagarosamente por vários dias e, depois de muita dificuldade, nos aproximamos de Cnido. Por causa dos ventos contrários, atravessamos para Creta, acompanhando o litoral menos exposto da ilha, defronte ao cabo de Salmona.

[[v44-27-8]]

^<<v44-27-8,8>>^ Costeamos a ilha com grande esforço, até que chegamos a Bons Portos, perto da cidade de Laseia.

[[v44-27-9]]

^<<v44-27-9,9>>^ Havíamos perdido muito tempo. As condições climáticas estavam se tornando perigosas para a navegação, pois se aproximava o fim do outono, e Paulo tratou dessa questão com os oficiais do navio.

[[v44-27-10]]

^<<v44-27-10,10>>^ Disse ele: "Senhores, se prosseguirmos, vejo que teremos problemas adiante. Haverá grande prejuízo para o navio e para a carga, e perigo para nossa vida".

[[v44-27-11]]

^<<v44-27-11,11>>^ Mas o oficial encarregado dos prisioneiros deu mais ouvidos ao capitão e ao proprietário do navio que a Paulo.

[[v44-27-12]]

^<<v44-27-12,12>>^ E, uma vez que Bons Portos era uma enseada aberta, um péssimo lugar para passar o inverno, a maioria da tripulação desejava ir a Fenice, que ficava mais adiante na costa de Creta, e passar o inverno ali. Fenice era um bom porto, com abertura apenas para o sudoeste e o noroeste.

[[v44-27-13]]

^<<v44-27-13,13>>^ Quando um vento leve começou a soprar do sul, os marinheiros pensaram que conseguiriam chegar lá a salvo. Por isso, levantaram âncora e foram costeando Creta.

[[v44-27-14]]

^<<v44-27-14,14>>^ Mas o tempo mudou de repente, e um vento com força de furacão, chamado Nordeste, soprou sobre a ilha e nos empurrou para o mar aberto.

[[v44-27-15]]

^<<v44-27-15,15>>^ Como os marinheiros não conseguiam manobrar o navio para ficar de frente para o vento, desistiram e deixaram que fosse levado pela tempestade.

[[v44-27-16]]

^<<v44-27-16,16>>^ Navegamos pelo lado menos exposto de uma pequena ilha chamada Cauda, onde, com muito custo, conseguimos içar para bordo o barco salva-vidas que viajava rebocado.

[[v44-27-17]]

^<<v44-27-17,17>>^ Então os marinheiros amarraram cordas em volta do casco do navio para reforçá-lo. Temiam ser arrastados para os bancos de areia de Sirte, diante do litoral africano, por isso baixaram a âncora flutuante para desacelerar o navio e deixaram que fosse levado pelo vento.

[[v44-27-18]]

^<<v44-27-18,18>>^ No dia seguinte, como ventos com força de vendaval continuavam a castigar o navio, a tripulação começou a lançar a carga ao mar.

[[v44-27-19]]

^<<v44-27-19,19>>^ No terceiro dia, removeram até mesmo parte do equipamento do navio e o jogaram fora.

[[v44-27-20]]

^<<v44-27-20,20>>^ A tempestade terrível prosseguiu por muitos dias, escondendo o sol e as estrelas, até que perdemos todas as esperanças.

[[v44-27-21]]

^<<v44-27-21,21>>^ Fazia tempo que ninguém comia. Por fim, Paulo reuniu a tripulação e disse: "Os senhores deveriam ter me dado ouvidos no princípio e não ter deixado Bons Portos. Teriam evitado todo este prejuízo e esta perda.

[[v44-27-22]]

^<<v44-27-22,22>>^ Mas tenham bom ânimo! O navio afundará, mas nenhum de vocês perderá a vida.

[[v44-27-23]]

^<<v44-27-23,23>>^ Pois, ontem à noite, um anjo do Deus a quem pertenço e sirvo se pôs ao meu lado

[[v44-27-24]]

^<<v44-27-24,24>>^ e disse: ‘Não tenha medo, Paulo! É preciso que você compareça diante de César. E Deus, em sua bondade, concedeu proteção a todos que navegam com você’.

[[v44-27-25]]

^<<v44-27-25,25>>^ Portanto, tenham bom ânimo! Creio em Deus; tudo ocorrerá exatamente como ele disse.

[[v44-27-26]]

^<<v44-27-26,26>>^ É necessário, porém, que sejamos impulsionados para uma ilha".

[[v44-27-27]]

^<<v44-27-27,27>>^ Por volta da meia-noite, na décima quarta noite de tempestade, enquanto éramos levados de um lado para o outro no mar Adriático, os marinheiros perceberam que estávamos perto de terra firme.

[[v44-27-28]]

^<<v44-27-28,28>>^ Lançaram a sonda e verificaram que a água tinha 37 metros de profundidade. Um pouco depois, lançaram a sonda novamente e encontraram apenas 27 metros.

[[v44-27-29]]

^<<v44-27-29,29>>^ Temiam que, se continuássemos assim, seríamos atirados contra as rochas na praia. Por isso, lançaram quatro âncoras da parte de trás do navio e ansiavam para que o dia chegasse logo.

[[v44-27-30]]

^<<v44-27-30,30>>^ Dando a entender que iriam lançar as âncoras da parte da frente, os marinheiros baixaram o barco salva-vidas, na tentativa de abandonar o navio.

[[v44-27-31]]

^<<v44-27-31,31>>^ Paulo, então, disse ao oficial no comando e aos soldados: "Se os marinheiros não permanecerem a bordo, vocês não conseguirão se salvar".

[[v44-27-32]]

^<<v44-27-32,32>>^ Então os soldados cortaram as cordas do barco salva-vidas e o deixaram à deriva.

[[v44-27-33]]

^<<v44-27-33,33>>^ Enquanto amanhecia, Paulo insistiu que todos comessem. "De tão preocupados, vocês não se alimentam há duas semanas", disse ele.

[[v44-27-34]]

^<<v44-27-34,34>>^ "Por favor, comam alguma coisa agora, para seu próprio bem. Pois nem um fio de cabelo de sua cabeça se perderá."

[[v44-27-35]]

^<<v44-27-35,35>>^ Em seguida, tomou um pão, deu graças a Deus na presença de todos, partiu-o em pedaços e comeu.

[[v44-27-36]]

^<<v44-27-36,36>>^ Todos se animaram e começaram a comer.

[[v44-27-37]]

^<<v44-27-37,37>>^ Havia um total de 276 pessoas a bordo.

[[v44-27-38]]

^<<v44-27-38,38>>^ Depois de se alimentar, a tripulação aliviou o peso do navio mais um pouco, atirando ao mar toda a carga de trigo.

[[v44-27-39]]

^<<v44-27-39,39>>^ Ao amanhecer, não reconheceram a terra, mas viram uma enseada com uma praia e cogitaram se seria possível chegar ali e atracar o navio.

[[v44-27-40]]

^<<v44-27-40,40>>^ Então cortaram as âncoras e as deixaram no mar. Depois, afrouxaram as cordas que controlavam os lemes, levantaram a vela da frente e foram rumo à praia,

[[v44-27-41]]

^<<v44-27-41,41>>^ mas o navio foi apanhado entre duas correntezas contrárias e encalhou antes do esperado. A parte da frente se encravou e ficou imóvel, enquanto a parte de trás, atingida pela força das ondas, começou a se partir.

[[v44-27-42]]

^<<v44-27-42,42>>^ Os soldados queriam matar os prisioneiros para que não nadassem até a praia e depois fugissem.

[[v44-27-43]]

^<<v44-27-43,43>>^ O oficial no comando, porém, desejava poupar a vida de Paulo e não permitiu que executassem seu plano. Ordenou aos que sabiam nadar que saltassem ao mar primeiro e fossem em direção a terra.

[[v44-27-44]]

^<<v44-27-44,44>>^ Os outros se agarraram a tábuas ou pedaços do navio destruído. Assim, todos chegaram à praia em segurança.

'''

xref:044-atos/044-atos-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-atos/044-atos-028.adoc#v44-28-0[Próximo Capítulo &#62;]