include::./index.adoc[]

[[v44-5-0]]
=== Atos, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v44-5-1]]

^<<v44-5-1,1>>^ Havia, porém, um homem chamado Ananias que, com sua esposa, Safira, vendeu uma propriedade.

[[v44-5-2]]

^<<v44-5-2,2>>^ Levou apenas parte do dinheiro aos apóstolos, mas, com aprovação da esposa, afirmou que aquele era o valor total e ficou com o resto.

[[v44-5-3]]

^<<v44-5-3,3>>^ Então Pedro disse: "Ananias, por que você deixou Satanás encher seu coração? Você mentiu para o Espírito Santo quando guardou parte do dinheiro para si.

[[v44-5-4]]

^<<v44-5-4,4>>^ A propriedade era sua para vender ou não, como quisesse. E, depois de vendê-la, o dinheiro também era seu, para entregar ou não. Como pôde fazer uma coisa dessas? Você não mentiu para nós, mas para Deus!".

[[v44-5-5]]

^<<v44-5-5,5>>^ Assim que Ananias ouviu essas palavras, caiu no chão e morreu. Um grande temor se apoderou de todos que souberam o que havia acontecido.

[[v44-5-6]]

^<<v44-5-6,6>>^ Então alguns jovens se levantaram, envolveram o corpo num lençol e o levaram para fora, e depois o sepultaram.

[[v44-5-7]]

^<<v44-5-7,7>>^ Cerca de três horas depois, sua esposa entrou, sem saber o que havia acontecido.

[[v44-5-8]]

^<<v44-5-8,8>>^ Pedro lhe perguntou: "Foi esse o valor que você e seu marido receberam pelo terreno?". Ela respondeu: "Sim, foi esse o valor".

[[v44-5-9]]

^<<v44-5-9,9>>^ Então Pedro disse: "Como vocês puderam conspirar para pôr à prova o Espírito do Senhor? Veja, os jovens que sepultaram seu marido estão logo ali, perto da porta, e também levarão você".

[[v44-5-10]]

^<<v44-5-10,10>>^ No mesmo instante, ela caiu no chão e morreu. Quando os jovens entraram e viram que ela estava morta, levaram seu corpo para fora e a sepultaram ao lado do marido.

[[v44-5-11]]

^<<v44-5-11,11>>^ Um grande temor se apoderou de toda a igreja e de todos que souberam desse acontecimento.

[[v44-5-12]]

^<<v44-5-12,12>>^ Os apóstolos realizavam muitos sinais e maravilhas entre o povo. Todos se reuniam regularmente no templo, na parte conhecida como Pórtico de Salomão.

[[v44-5-13]]

^<<v44-5-13,13>>^ Quando se reuniam ali, ninguém mais tinha coragem de juntar-se a eles, embora o povo os tivesse em alta consideração.

[[v44-5-14]]

^<<v44-5-14,14>>^ Cada vez mais pessoas, multidões de homens e mulheres, criam no Senhor.

[[v44-5-15]]

^<<v44-5-15,15>>^ Como resultado, o povo levava os doentes às ruas em camas e macas para que a sombra de Pedro cobrisse alguns deles enquanto ele passava.

[[v44-5-16]]

^<<v44-5-16,16>>^ Muita gente vinha das cidades ao redor de Jerusalém, trazendo doentes e atormentados por espíritos impuros, e todos eram curados.

[[v44-5-17]]

^<<v44-5-17,17>>^ Tomados de inveja, o sumo sacerdote e seus oficiais, que eram saduceus,

[[v44-5-18]]

^<<v44-5-18,18>>^ prenderam os apóstolos e os colocaram numa prisão pública.

[[v44-5-19]]

^<<v44-5-19,19>>^ Um anjo do Senhor, porém, veio durante a noite, abriu as portas do cárcere e os levou para fora.

[[v44-5-20]]

^<<v44-5-20,20>>^ "Vão ao templo e transmitam ao povo esta mensagem de vida!", disse ele.

[[v44-5-21]]

^<<v44-5-21,21>>^ Desse modo, ao amanhecer, os apóstolos entraram no templo, conforme haviam sido instruídos, e, sem demora, começaram a ensinar. Mais tarde, o sumo sacerdote e seus oficiais chegaram, reuniram o conselho, isto é, toda a assembleia dos líderes de Israel, e mandaram buscar os apóstolos na prisão.

[[v44-5-22]]

^<<v44-5-22,22>>^ Mas, quando os guardas do templo chegaram à prisão, os homens não estavam lá. Então voltaram e contaram:

[[v44-5-23]]

^<<v44-5-23,23>>^ "A prisão estava bem trancada, com os guardas vigiando do lado de fora, mas, quando abrimos as portas, não havia ninguém!".

[[v44-5-24]]

^<<v44-5-24,24>>^ Ao ouvir isso, o capitão da guarda do templo e os principais sacerdotes ficaram perplexos e se perguntavam o que aconteceria em seguida.

[[v44-5-25]]

^<<v44-5-25,25>>^ Então alguém chegou com a seguinte notícia: "Os homens que os senhores puseram na cadeia estão no templo, ensinando o povo!".

[[v44-5-26]]

^<<v44-5-26,26>>^ O capitão e seus guardas foram e prenderam os apóstolos, mas sem violência, pois temiam que o povo os apedrejasse.

[[v44-5-27]]

^<<v44-5-27,27>>^ Em seguida, levaram os apóstolos e os apresentaram ao conselho de líderes do povo, onde o sumo sacerdote os confrontou.

[[v44-5-28]]

^<<v44-5-28,28>>^ "Nós lhes ordenamos firmemente que nunca mais ensinassem em nome desse homem", disse ele. "E, mesmo assim, vocês encheram Jerusalém com esse seu ensino e querem nos responsabilizar pela morte dele!"

[[v44-5-29]]

^<<v44-5-29,29>>^ Pedro e os apóstolos responderam: "Devemos obedecer a Deus antes de qualquer autoridade humana.

[[v44-5-30]]

^<<v44-5-30,30>>^ O Deus de nossos antepassados ressuscitou Jesus dos mortos depois que os senhores o mataram, pendurando-o numa cruz.

[[v44-5-31]]

^<<v44-5-31,31>>^ Deus o colocou no lugar de honra, à sua direita, como Príncipe e Salvador, para que o povo de Israel se arrependesse de seus pecados e fosse perdoado.

[[v44-5-32]]

^<<v44-5-32,32>>^ Somos testemunhas dessas coisas, e assim é também o Espírito Santo, que Deus dá àqueles que lhe obedecem".

[[v44-5-33]]

^<<v44-5-33,33>>^ Quando ouviram isso, os membros do conselho se enfureceram e decidiram matá-los.

[[v44-5-34]]

^<<v44-5-34,34>>^ Um deles, porém, um fariseu chamado Gamaliel, especialista na lei e respeitado por todo o povo, levantou-se e ordenou que eles fossem retirados da sala do conselho por um momento.

[[v44-5-35]]

^<<v44-5-35,35>>^ Em seguida, disse aos demais: "Israelitas, cuidado com o que planejam fazer a esses homens!

[[v44-5-36]]

^<<v44-5-36,36>>^ Algum tempo atrás, surgiu um certo Teudas, que afirmava ser alguém importante. Umas quatrocentas pessoas se juntaram a ele, mas foi morto e seus seguidores se dispersaram, e o movimento deu em nada.

[[v44-5-37]]

^<<v44-5-37,37>>^ Depois dele, na época do censo, apareceu Judas, da Galileia, que fez muitos seguidores. Ele também foi morto, e seu grupo se dispersou.

[[v44-5-38]]

^<<v44-5-38,38>>^ "Portanto, meu conselho é que deixem esses homens em paz e os soltem. Se o que planejam e fazem é meramente humano, logo serão frustrados.

[[v44-5-39]]

^<<v44-5-39,39>>^ Mas, se é de Deus, vocês não serão capazes de impedi-los. Pode até acontecer de vocês acabarem lutando contra Deus".

[[v44-5-40]]

^<<v44-5-40,40>>^ Os demais membros aceitaram o conselho de Gamaliel. Chamaram os apóstolos e mandaram açoitá-los. Depois, ordenaram que nunca mais falassem em nome de Jesus e, por fim, os soltaram.

[[v44-5-41]]

^<<v44-5-41,41>>^ Quando os apóstolos saíram da reunião do conselho, estavam alegres porque Deus os havia considerado dignos de sofrer humilhação pelo nome de Jesus.

[[v44-5-42]]

^<<v44-5-42,42>>^ E todos os dias, no templo e de casa em casa, continuavam a ensinar e anunciar que Jesus é o Cristo.

'''

xref:044-atos/044-atos-004.adoc#v44-4-0[&#60; Capítulo Anterior] | <<v44-5-0,Topo>> | xref:044-atos/044-atos-006.adoc#v44-6-0[Próximo Capítulo &#62;]