include::./index.adoc[]

[[v44-8-0]]
=== Atos, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v44-8-1]]

^<<v44-8-1,1>>^ E Saulo concordou inteiramente com a morte de Estêvão. Uma grande onda de perseguição começou naquele dia e varreu a igreja de Jerusalém. Todos eles, com exceção dos apóstolos, foram dispersos pelas regiões da Judeia e de Samaria.

[[v44-8-2]]

^<<v44-8-2,2>>^ (Alguns homens devotos vieram e, com grande tristeza, sepultaram Estêvão.)

[[v44-8-3]]

^<<v44-8-3,3>>^ Saulo, porém, procurava destruir a igreja. Ia de casa em casa, arrastava para fora homens e mulheres e os lançava na prisão.

[[v44-8-4]]

^<<v44-8-4,4>>^ Os que haviam sido dispersos, porém, anunciavam as boas-novas a respeito de Jesus por onde quer que fossem.

[[v44-8-5]]

^<<v44-8-5,5>>^ Filipe foi para a cidade de Samaria e ali falou ao povo sobre o Cristo.

[[v44-8-6]]

^<<v44-8-6,6>>^ Quando as multidões ouviram sua mensagem e viram os sinais que ele realizava, deram total atenção às suas palavras.

[[v44-8-7]]

^<<v44-8-7,7>>^ Muitos espíritos impuros eram expulsos e, aos gritos, deixavam suas vítimas, e muitos paralíticos e aleijados eram curados.

[[v44-8-8]]

^<<v44-8-8,8>>^ Por isso, houve grande alegria naquela cidade.

[[v44-8-9]]

^<<v44-8-9,9>>^ Um homem chamado Simão praticava feitiçaria ali havia anos. Ele deixava o povo de Samaria admirado, e afirmava ser alguém importante.

[[v44-8-10]]

^<<v44-8-10,10>>^ Todos, dos mais simples aos mais importantes, se referiam a ele como "o Grande Poder de Deus".

[[v44-8-11]]

^<<v44-8-11,11>>^ Ouviam-no com atenção, pois, durante muito tempo, ele os tinha deixado admirados com sua magia.

[[v44-8-12]]

^<<v44-8-12,12>>^ No entanto, quando Filipe lhes levou a mensagem sobre as boas-novas do reino de Deus e sobre o nome de Jesus Cristo, eles creram e, como resultado, muitos homens e mulheres foram batizados.

[[v44-8-13]]

^<<v44-8-13,13>>^ O próprio Simão creu e foi batizado. Começou a seguir Filipe por toda parte, admirando-se dos sinais e milagres que ele realizava.

[[v44-8-14]]

^<<v44-8-14,14>>^ Quando os apóstolos em Jerusalém souberam que o povo de Samaria havia aceitado a mensagem de Deus, enviaram para lá Pedro e João.

[[v44-8-15]]

^<<v44-8-15,15>>^ Assim que os dois chegaram, oraram para que aqueles convertidos recebessem o Espírito Santo,

[[v44-8-16]]

^<<v44-8-16,16>>^ pois, apesar de terem sido batizados em nome do Senhor Jesus, o Espírito Santo ainda não havia descido sobre nenhum deles.

[[v44-8-17]]

^<<v44-8-17,17>>^ Então Pedro e João impuseram as mãos sobre eles, e receberam o Espírito Santo.

[[v44-8-18]]

^<<v44-8-18,18>>^ Simão viu que as pessoas recebiam o Espírito quando os apóstolos impunham as mãos sobre elas. Então ofereceu-lhes dinheiro,

[[v44-8-19]]

^<<v44-8-19,19>>^ dizendo: "Deem-me este poder também, para que, quando eu impuser as mãos sobre as pessoas, elas recebam o Espírito Santo!".

[[v44-8-20]]

^<<v44-8-20,20>>^ Pedro, porém, respondeu: "Que seu dinheiro seja destruído com você, por imaginar que o dom de Deus pode ser comprado!

[[v44-8-21]]

^<<v44-8-21,21>>^ Você não tem parte nem direito neste ministério, pois seu coração não é justo diante de Deus.

[[v44-8-22]]

^<<v44-8-22,22>>^ Arrependa-se de sua maldade e ore ao Senhor. Talvez ele perdoe esses seus maus pensamentos,

[[v44-8-23]]

^<<v44-8-23,23>>^ pois vejo que você está cheio de amarga inveja e é prisioneiro do pecado".

[[v44-8-24]]

^<<v44-8-24,24>>^ Simão exclamou: "Orem ao Senhor por mim, para que essas coisas terríveis não me aconteçam!".

[[v44-8-25]]

^<<v44-8-25,25>>^ Depois de terem testemunhado e proclamado a palavra do Senhor em Samaria, Pedro e João voltaram a Jerusalém. Ao longo do caminho, pararam em muitas vilas samaritanas para anunciar as boas-novas.

[[v44-8-26]]

^<<v44-8-26,26>>^ Um anjo do Senhor disse a Filipe: "Vá para o sul, para a estrada no deserto que liga Jerusalém a Gaza".

[[v44-8-27]]

^<<v44-8-27,27>>^ Filipe partiu e encontrou no caminho um alto oficial etíope, o eunuco responsável pelos tesouros de Candace, rainha da Etiópia. Ele tinha ido a Jerusalém para participar da adoração

[[v44-8-28]]

^<<v44-8-28,28>>^ e estava no caminho de volta. Sentado em sua carruagem, lia em voz alta o livro do profeta Isaías.

[[v44-8-29]]

^<<v44-8-29,29>>^ Então o Espírito disse a Filipe: "Aproxime-se e acompanhe a carruagem".

[[v44-8-30]]

^<<v44-8-30,30>>^ Filipe correu até a carruagem e, ouvindo que o homem lia o profeta Isaías, perguntou-lhe: "O senhor compreende o que lê?".

[[v44-8-31]]

^<<v44-8-31,31>>^ O homem respondeu: "Como posso entender sem que alguém me explique?". E convidou Filipe a subir na carruagem e sentar-se ao seu lado.

[[v44-8-32]]

^<<v44-8-32,32>>^ Era esta a passagem das Escrituras que ele estava lendo: "Ele foi levado como ovelha para o matadouro; como cordeiro mudo diante dos tosquiadores, não abriu a boca.

[[v44-8-33]]

^<<v44-8-33,33>>^ Foi humilhado e a justiça lhe foi negada. Quem pode falar de seus descendentes? Pois sua vida foi tirada da terra".

[[v44-8-34]]

^<<v44-8-34,34>>^ O eunuco perguntou a Filipe: "Diga-me, o profeta estava falando de si mesmo ou de outro?".

[[v44-8-35]]

^<<v44-8-35,35>>^ Então Filipe, começando com essa mesma passagem das Escrituras, anunciou-lhe as boas-novas a respeito de Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ Prosseguindo, chegaram a um lugar onde havia água. Então o eunuco disse: "Veja, aqui tem água! O que me impede de ser batizado?".

[[v44-8-37]]

^<<v44-8-37,37>>^ Filipe disse: "Nada o impede, se você crê de todo o coração". O eunuco respondeu: "Creio que Jesus Cristo é o Filho de Deus".

[[v44-8-38]]

^<<v44-8-38,38>>^ Então mandou parar a carruagem, os dois desceram até a água e Filipe o batizou.

[[v44-8-39]]

^<<v44-8-39,39>>^ Quando saíram da água, o Espírito do Senhor tomou Filipe e o levou. O eunuco não tornou a vê-lo, mas seguiu viagem cheio de alegria.

[[v44-8-40]]

^<<v44-8-40,40>>^ Então Filipe apareceu mais ao norte, na cidade de Azoto. Anunciou as boas-novas ali e em todas as cidades ao longo do caminho, até chegar a Cesareia.

'''

xref:044-atos/044-atos-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-atos/044-atos-009.adoc#v44-9-0[Próximo Capítulo &#62;]