include::./index.adoc[]

[[v44-10-0]]
=== Atos, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v44-10-1]]

^<<v44-10-1,1>>^ Morava em Cesareia um oficial do exército romano chamado Cornélio, capitão do Regimento Italiano.

[[v44-10-2]]

^<<v44-10-2,2>>^ Era um homem devoto e temente a Deus, como era também toda a sua família. Dava aos pobres esmolas generosas e sempre orava ao Senhor.

[[v44-10-3]]

^<<v44-10-3,3>>^ Certa tarde, por volta das três horas, teve uma visão na qual viu um anjo de Deus vir em sua direção e dizer: "Cornélio!".

[[v44-10-4]]

^<<v44-10-4,4>>^ Temeroso, Cornélio olhou fixamente para o anjo e perguntou: "Que é, senhor?". E o anjo respondeu: "Suas orações e esmolas subiram até Deus, e ele as guarda na memória.

[[v44-10-5]]

^<<v44-10-5,5>>^ Agora, envie alguns homens a Jope e mande buscar Simão, também chamado Pedro.

[[v44-10-6]]

^<<v44-10-6,6>>^ Ele está hospedado com Simão, um homem que trabalha com couro e mora à beira do mar".

[[v44-10-7]]

^<<v44-10-7,7>>^ Assim que o anjo foi embora, Cornélio chamou dois servos de sua casa e um soldado devoto de seu grupo de auxiliares.

[[v44-10-8]]

^<<v44-10-8,8>>^ Ele lhes contou o que havia acontecido e os enviou a Jope.

[[v44-10-9]]

^<<v44-10-9,9>>^ No dia seguinte, quando os mensageiros de Cornélio se aproximavam da cidade, Pedro subiu ao terraço para orar. Era cerca de meio-dia,

[[v44-10-10]]

^<<v44-10-10,10>>^ e ele estava com fome. Enquanto a refeição era preparada, entrou num êxtase.

[[v44-10-11]]

^<<v44-10-11,11>>^ Viu o céu aberto e algo semelhante a um grande lençol ser baixado por suas quatro pontas.

[[v44-10-12]]

^<<v44-10-12,12>>^ No lençol havia toda espécie de animais, répteis e aves.

[[v44-10-13]]

^<<v44-10-13,13>>^ Então uma voz lhe disse: "Levante-se, Pedro; mate e coma".

[[v44-10-14]]

^<<v44-10-14,14>>^ "De modo nenhum, Senhor!", respondeu Pedro. "Jamais comi coisa alguma que fosse considerada impura e imprópria."

[[v44-10-15]]

^<<v44-10-15,15>>^ Mas a voz falou novamente: "Não chame de impuro o que Deus purificou".

[[v44-10-16]]

^<<v44-10-16,16>>^ A mesma visão se repetiu três vezes. Então, subitamente, o lençol foi recolhido ao céu.

[[v44-10-17]]

^<<v44-10-17,17>>^ Pedro ficou perplexo, pensando em qual seria o significado da visão. Nesse momento, os homens que Cornélio tinha enviado encontraram a casa de Simão. Eles se aproximaram do portão

[[v44-10-18]]

^<<v44-10-18,18>>^ e perguntaram se estava hospedado ali Simão, também chamado Pedro.

[[v44-10-19]]

^<<v44-10-19,19>>^ Enquanto Pedro ainda refletia sobre a visão, o Espírito lhe disse: "Três homens vieram procurá-lo.

[[v44-10-20]]

^<<v44-10-20,20>>^ Levante-se, desça e vá encontrar-se com eles. Não hesite em acompanhá-los, pois eu os enviei".

[[v44-10-21]]

^<<v44-10-21,21>>^ Pedro desceu e disse aos homens: "Eu sou quem vocês procuram. Por que vieram?".

[[v44-10-22]]

^<<v44-10-22,22>>^ Eles responderam: "Cornélio, um oficial romano, nos enviou. Ele é um homem devoto e temente a Deus, respeitado por todos os judeus. Um santo anjo o instruiu a chamar o senhor à casa dele para que ele ouça sua mensagem".

[[v44-10-23]]

^<<v44-10-23,23>>^ Então Pedro convidou os homens para se hospedarem ali aquela noite. No dia seguinte, foi com eles, acompanhado de alguns irmãos de Jope.

[[v44-10-24]]

^<<v44-10-24,24>>^ Chegaram a Cesareia no dia seguinte. Cornélio os esperava e havia reunido seus parentes e amigos íntimos.

[[v44-10-25]]

^<<v44-10-25,25>>^ Quando Pedro chegou à casa, Cornélio veio ao seu encontro e prostrou-se diante dele, adorando-o.

[[v44-10-26]]

^<<v44-10-26,26>>^ Mas Pedro o levantou e disse: "Fique de pé! Eu sou apenas um homem como você".

[[v44-10-27]]

^<<v44-10-27,27>>^ Os dois conversaram e depois entraram na casa, onde muitos outros estavam reunidos.

[[v44-10-28]]

^<<v44-10-28,28>>^ Pedro lhes disse: "Vocês sabem que nossas leis proíbem que um judeu entre num lar gentio como este ou se associe com os gentios. No entanto, Deus me mostrou que não devo mais considerar ninguém impuro ou impróprio.

[[v44-10-29]]

^<<v44-10-29,29>>^ Por isso, vim assim que fui chamado, sem levantar objeções. Agora digam por que vocês mandaram me buscar".

[[v44-10-30]]

^<<v44-10-30,30>>^ Cornélio respondeu: "Quatro dias atrás, eu estava orando em casa por volta deste mesmo horário, às três da tarde. De repente, um homem vestido com roupas resplandecentes apareceu diante de mim.

[[v44-10-31]]

^<<v44-10-31,31>>^ Ele me disse: ‘Cornélio, Deus ouviu sua oração e se lembrou de suas esmolas.

[[v44-10-32]]

^<<v44-10-32,32>>^ Agora, envie mensageiros a Jope e mande buscar Simão, também chamado Pedro. Ele está hospedado na casa de Simão, um homem que trabalha com couro e mora à beira do mar’.

[[v44-10-33]]

^<<v44-10-33,33>>^ Assim, mandei buscá-lo de imediato, e foi bom que tenha vindo. Agora estamos todos aqui, esperando diante de Deus para ouvir a mensagem que o Senhor mandou que você nos trouxesse".

[[v44-10-34]]

^<<v44-10-34,34>>^ Então Pedro respondeu: "Vejo claramente que Deus não mostra nenhum favoritismo.

[[v44-10-35]]

^<<v44-10-35,35>>^ Em todas as nações ele aceita aqueles que o temem e fazem o que é certo.

[[v44-10-36]]

^<<v44-10-36,36>>^ Esta é a mensagem de boas-novas para o povo de Israel: Há paz com Deus por meio de Jesus Cristo, que é Senhor de todos.

[[v44-10-37]]

^<<v44-10-37,37>>^ Vocês sabem o que aconteceu em toda a Judeia, começando na Galileia, depois do batismo que João proclamou.

[[v44-10-38]]

^<<v44-10-38,38>>^ Sabem também que Deus ungiu Jesus de Nazaré com o Espírito Santo e com poder. Então Jesus foi por toda parte fazendo o bem e curando todos os oprimidos pelo diabo, porque Deus estava com ele.

[[v44-10-39]]

^<<v44-10-39,39>>^ "E nós somos testemunhas de tudo que ele fez em toda a Judeia e em Jerusalém, onde o mataram. Penduraram-no numa cruz,

[[v44-10-40]]

^<<v44-10-40,40>>^ mas Deus o ressuscitou no terceiro dia e permitiu que ele fosse visto,

[[v44-10-41]]

^<<v44-10-41,41>>^ não por todo o povo, mas por nós que fomos escolhidos por Deus de antemão para sermos suas testemunhas. Nós fomos os que comemos e bebemos com ele depois que ele ressuscitou dos mortos.

[[v44-10-42]]

^<<v44-10-42,42>>^ E ele nos mandou anunciar sua mensagem em toda parte e testemunhar que Deus o designou juiz dos vivos e dos mortos.

[[v44-10-43]]

^<<v44-10-43,43>>^ É a respeito dele que todos os profetas dão testemunho, dizendo que todo o que nele crer receberá o perdão de seus pecados por meio de seu nome".

[[v44-10-44]]

^<<v44-10-44,44>>^ Enquanto Pedro ainda falava, o Espírito Santo desceu sobre todos que ouviam a mensagem.

[[v44-10-45]]

^<<v44-10-45,45>>^ Os discípulos judeus que acompanhavam Pedro ficaram admirados de que o dom do Espírito Santo também fosse derramado sobre os gentios,

[[v44-10-46]]

^<<v44-10-46,46>>^ pois os ouviram falar em outras línguas e louvar a Deus. Pedro perguntou:

[[v44-10-47]]

^<<v44-10-47,47>>^ "Pode alguém se opor a que eles sejam batizados agora que, como nós, também receberam o Espírito Santo?".

[[v44-10-48]]

^<<v44-10-48,48>>^ Então ordenou que fossem batizados em nome de Jesus Cristo. Depois, pediram que Pedro ficasse com eles alguns dias.

'''

xref:044-atos/044-atos-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-atos/044-atos-011.adoc#v44-11-0[Próximo Capítulo &#62;]