include::./index.adoc[]

[[v44-18-0]]
=== Atos, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v44-18-1]]

^<<v44-18-1,1>>^ Algum tempo depois, Paulo deixou Atenas e foi para Corinto.

[[v44-18-2]]

^<<v44-18-2,2>>^ Ali encontrou um judeu chamado Áquila, natural do Ponto, que havia chegado recentemente da Itália com sua esposa, Priscila, depois que Cláudio César expulsou todos os judeus de Roma.

[[v44-18-3]]

^<<v44-18-3,3>>^ Paulo foi morar e trabalhar com eles, pois eram fabricantes de tendas, como ele.

[[v44-18-4]]

^<<v44-18-4,4>>^ Todos os sábados, Paulo ia à sinagoga e buscava convencer tanto judeus como gregos.

[[v44-18-5]]

^<<v44-18-5,5>>^ Depois que Silas e Timóteo chegaram da Macedônia, Paulo se dedicou totalmente à pregação da palavra e testemunhava aos judeus que Jesus era o Cristo.

[[v44-18-6]]

^<<v44-18-6,6>>^ Mas, quando eles se opuseram a Paulo e o insultaram, ele sacudiu o pó da roupa e disse: "Vocês são responsáveis por sua própria destruição! Eu sou inocente. De agora em diante, pregarei aos gentios".

[[v44-18-7]]

^<<v44-18-7,7>>^ Então saiu dali e foi à casa de Tício Justo, um gentio temente a Deus que morava ao lado da sinagoga.

[[v44-18-8]]

^<<v44-18-8,8>>^ Crispo, o líder da sinagoga, e toda a sua família creram no Senhor. Muitos outros em Corinto também ouviram Paulo, creram e foram batizados.

[[v44-18-9]]

^<<v44-18-9,9>>^ Certa noite, o Senhor falou a Paulo numa visão: "Não tenha medo! Continue a falar e não se cale,

[[v44-18-10]]

^<<v44-18-10,10>>^ pois estou com você, e ninguém o atacará nem lhe fará mal, porque muita gente nesta cidade me pertence".

[[v44-18-11]]

^<<v44-18-11,11>>^ Então Paulo permaneceu ali um ano e meio, ensinando a palavra de Deus.

[[v44-18-12]]

^<<v44-18-12,12>>^ Quando Gálio se tornou governador da Acaia, alguns judeus se levantaram contra Paulo e o levaram diante do governador para ser julgado.

[[v44-18-13]]

^<<v44-18-13,13>>^ Eles o acusaram de convencer as pessoas a adorar a Deus de maneira contrária à lei judaica.

[[v44-18-14]]

^<<v44-18-14,14>>^ Mas, assim que Paulo começou a apresentar sua defesa, Gálio se voltou para os acusadores e disse: "Ouçam, judeus! Se sua queixa envolvesse algum delito ou crime grave, eu teria motivo para aceitar o caso.

[[v44-18-15]]

^<<v44-18-15,15>>^ Mas, como se trata apenas de uma questão de palavras e nomes e da sua lei, resolvam isso vocês mesmos. Recuso-me a julgar essas coisas".

[[v44-18-16]]

^<<v44-18-16,16>>^ E os expulsou do tribunal.

[[v44-18-17]]

^<<v44-18-17,17>>^ A multidão agarrou Sóstenes, o novo líder da sinagoga, e o espancou ali mesmo, no tribunal. Gálio, no entanto, não se importou com isso.

[[v44-18-18]]

^<<v44-18-18,18>>^ Paulo ainda permaneceu em Corinto por algum tempo. Então se despediu dos irmãos e foi a Cencreia, onde raspou a cabeça, de acordo com o costume judaico para marcar o fim de um voto. Em seguida, partiu de navio para a Síria, levando consigo Priscila e Áquila.

[[v44-18-19]]

^<<v44-18-19,19>>^ Chegaram ao porto de Éfeso, onde Paulo os deixou. Enquanto estava ali, foi à sinagoga para debater com os judeus.

[[v44-18-20]]

^<<v44-18-20,20>>^ Eles pediram que ficasse mais tempo, mas ele recusou.

[[v44-18-21]]

^<<v44-18-21,21>>^ Ao despedir-se, Paulo disse: "Voltarei depois, se Deus quiser". Então zarpou de Éfeso.

[[v44-18-22]]

^<<v44-18-22,22>>^ A parada seguinte foi no porto de Cesareia, de onde subiu a Jerusalém e visitou a igreja. Em seguida, voltou para Antioquia.

[[v44-18-23]]

^<<v44-18-23,23>>^ Depois de passar algum tempo ali, voltou pela Galácia e pela Frígia, visitando e fortalecendo todos os discípulos.

[[v44-18-24]]

^<<v44-18-24,24>>^ Enquanto isso, chegou a Éfeso vindo de Alexandria, no Egito, um judeu chamado Apolo. Era um orador eloquente que conhecia bem as Escrituras.

[[v44-18-25]]

^<<v44-18-25,25>>^ Tinha sido instruído no caminho do Senhor e ensinava a respeito de Jesus com profundo entusiasmo e exatidão, embora só conhecesse o batismo de João.

[[v44-18-26]]

^<<v44-18-26,26>>^ Quando o ouviram falar corajosamente na sinagoga, Priscila e Áquila o chamaram de lado e lhe explicaram com mais exatidão o caminho de Deus.

[[v44-18-27]]

^<<v44-18-27,27>>^ Apolo queria percorrer a Acaia, e os irmãos de Éfeso o incentivaram. Escreveram uma carta aos discípulos de lá, pedindo que o recebessem bem. Ao chegar, foi de grande ajuda àqueles que, pela graça, haviam crido,

[[v44-18-28]]

^<<v44-18-28,28>>^ pois, em debates públicos, refutava os judeus com fortes argumentos. Usando as Escrituras, demonstrava-lhes que Jesus é o Cristo.

'''

xref:044-atos/044-atos-017.adoc#v44-17-0[&#60; Capítulo Anterior] | <<v44-18-0,Topo>> | xref:044-atos/044-atos-019.adoc#v44-19-0[Próximo Capítulo &#62;]