include::./index.adoc[]

[[v44-1-0]]
=== Atos, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v44-1-1]]

^<<v44-1-1,1>>^ Em meu primeiro livro, relatei a você, Teófilo, tudo que Jesus começou a fazer e a ensinar

[[v44-1-2]]

^<<v44-1-2,2>>^ até o dia em que foi levado para o céu, depois de dar a seus apóstolos escolhidos mais instruções por meio do Espírito Santo.

[[v44-1-3]]

^<<v44-1-3,3>>^ Durante os quarenta dias após seu sofrimento e morte, Jesus apareceu aos apóstolos diversas vezes. Ele lhes apresentou muitas provas claras de que estava vivo e lhes falou do reino de Deus.

[[v44-1-4]]

^<<v44-1-4,4>>^ Certa ocasião, enquanto comia com eles, deu-lhes a seguinte ordem: "Não saiam de Jerusalém até o Pai enviar a promessa, conforme eu lhes disse antes.

[[v44-1-5]]

^<<v44-1-5,5>>^ João batizou com água, mas dentro de poucos dias vocês serão batizados com o Espírito Santo".

[[v44-1-6]]

^<<v44-1-6,6>>^ Então os que estavam com Jesus lhe perguntaram: "Senhor, será esse o momento em que restaurará o reino a Israel?".

[[v44-1-7]]

^<<v44-1-7,7>>^ Ele respondeu: "O Pai já determinou o tempo e a ocasião para que isso aconteça, e não cabe a vocês saber.

[[v44-1-8]]

^<<v44-1-8,8>>^ Vocês receberão poder quando o Espírito Santo descer sobre vocês, e serão minhas testemunhas em toda parte: em Jerusalém, em toda a Judeia, em Samaria e nos lugares mais distantes da terra".

[[v44-1-9]]

^<<v44-1-9,9>>^ Depois de ter dito isso, foi elevado numa nuvem, e os discípulos não conseguiram mais vê-lo.

[[v44-1-10]]

^<<v44-1-10,10>>^ Continuaram a olhar atentamente para o céu, até que dois homens vestidos de branco apareceram de repente no meio deles

[[v44-1-11]]

^<<v44-1-11,11>>^ e disseram: "Homens da Galileia, por que estão aí parados, olhando para o céu? Esse Jesus, que foi elevado do meio de vocês ao céu, voltará do mesmo modo como o viram subir!".

[[v44-1-12]]

^<<v44-1-12,12>>^ Então voltaram do monte das Oliveiras para Jerusalém, cerca de um quilômetro de distância.

[[v44-1-13]]

^<<v44-1-13,13>>^ Quando chegaram, subiram à sala no andar superior da casa onde estavam hospedados. Estavam ali Pedro, João, Tiago, André, Filipe, Tomé, Bartolomeu, Mateus, Tiago, filho de Alfeu, Simão, o zelote, e Judas, filho de Tiago.

[[v44-1-14]]

^<<v44-1-14,14>>^ Todos eles se reuniam em oração com um só propósito, acompanhados de algumas mulheres e também de Maria, mãe de Jesus, e os irmãos dele.

[[v44-1-15]]

^<<v44-1-15,15>>^ Por esse tempo, quando cerca de 120 discípulos estavam reunidos num só lugar, Pedro se levantou e disse:

[[v44-1-16]]

^<<v44-1-16,16>>^ "Irmãos, era necessário que se cumprissem as Escrituras a respeito de Judas, que serviu de guia aos que prenderam Jesus. Esse acontecimento havia sido predito pelo Espírito Santo, por meio do rei Davi.

[[v44-1-17]]

^<<v44-1-17,17>>^ Judas era um de nós e participava do ministério conosco".

[[v44-1-18]]

^<<v44-1-18,18>>^ (Ele comprou um campo com o dinheiro que recebeu por sua perversidade. Ao cair ali de cabeça, seu corpo se partiu ao meio, e seus intestinos se derramaram.

[[v44-1-19]]

^<<v44-1-19,19>>^ A notícia se espalhou entre todos os habitantes de Jerusalém, e eles deram ao lugar o nome aramaico Aceldama , que significa "Campo de Sangue".)

[[v44-1-20]]

^<<v44-1-20,20>>^ Pedro continuou: "Estava escrito no livro de Salmos: ‘Que sua casa fique desolada, sem ninguém morando nela’. Também diz: ‘Que outro ocupe seu lugar’.

[[v44-1-21]]

^<<v44-1-21,21>>^ "Agora, portanto, devemos escolher um dentre os homens que estiveram conosco durante todo o tempo em que o Senhor Jesus andou entre nós,

[[v44-1-22]]

^<<v44-1-22,22>>^ desde que ele foi batizado por João até o dia em que foi tirado de nosso meio e elevado ao céu. O escolhido se juntará a nós como testemunha da ressurreição".

[[v44-1-23]]

^<<v44-1-23,23>>^ Então indicaram dois homens: José, chamado Barsabás e conhecido também como Justo, e Matias.

[[v44-1-24]]

^<<v44-1-24,24>>^ Em seguida, oraram: "Senhor, tu conheces cada coração. Mostra-nos qual destes homens escolheste

[[v44-1-25]]

^<<v44-1-25,25>>^ como apóstolo para substituir Judas neste ministério, pois ele se desviou e foi para seu devido lugar".

[[v44-1-26]]

^<<v44-1-26,26>>^ Então lançaram sortes e Matias foi escolhido como apóstolo, juntando-se aos outros onze.

'''

xref:043-joao/043-joao-021.adoc#v43-21-0[&#60; Capítulo Anterior] | <<v44-1-0,Topo>> | xref:044-atos/044-atos-002.adoc#v44-2-0[Próximo Capítulo &#62;]