include::./index.adoc[]

[[v44-16-0]]
=== Atos, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v44-16-1]]

^<<v44-16-1,1>>^ Paulo foi primeiro a Derbe e depois a Listra, onde havia um jovem discípulo chamado Timóteo. A mãe dele era uma judia convertida, e o pai era grego.

[[v44-16-2]]

^<<v44-16-2,2>>^ Os irmãos em Listra e em Icônio o tinham em alta consideração,

[[v44-16-3]]

^<<v44-16-3,3>>^ de modo que Paulo pediu que ele os acompanhasse em sua viagem. Em respeito aos judeus da região, providenciou que Timóteo fosse circuncidado antes de partirem, pois todos sabiam que o pai dele era grego.

[[v44-16-4]]

^<<v44-16-4,4>>^ Em toda cidade por onde passavam, instruíam os irmãos a seguirem as decisões tomadas pelos apóstolos e presbíteros em Jerusalém.

[[v44-16-5]]

^<<v44-16-5,5>>^ Assim, as igrejas eram fortalecidas na fé e cresciam em número a cada dia.

[[v44-16-6]]

^<<v44-16-6,6>>^ Em seguida, Paulo e Silas viajaram pela região da Frígia e da Galácia, pois o Espírito Santo os impediu de pregar a palavra na província da Ásia.

[[v44-16-7]]

^<<v44-16-7,7>>^ Então, chegando à fronteira da Mísia, tentaram ir para o norte, em direção à Bitínia, mas o Espírito de Jesus não permitiu.

[[v44-16-8]]

^<<v44-16-8,8>>^ Assim, seguiram viagem pela Mísia até o porto de Trôade.

[[v44-16-9]]

^<<v44-16-9,9>>^ Naquela noite, Paulo teve uma visão, na qual um homem da Macedônia em pé lhe suplicava: "Venha para a Macedônia e ajude-nos!".

[[v44-16-10]]

^<<v44-16-10,10>>^ Então decidimos partir de imediato para a Macedônia, concluindo que Deus nos havia chamado para anunciar ali as boas-novas.

[[v44-16-11]]

^<<v44-16-11,11>>^ Embarcamos em Trôade e navegamos diretamente para a ilha de Samotrácia e, no dia seguinte, chegamos a Neápolis.

[[v44-16-12]]

^<<v44-16-12,12>>^ Dali, alcançamos Filipos, cidade importante dessa região da Macedônia e colônia romana, e ali permanecemos vários dias.

[[v44-16-13]]

^<<v44-16-13,13>>^ No sábado, saímos da cidade e fomos à margem do rio, onde esperávamos encontrar um lugar de oração. Sentamo-nos e começamos a conversar com algumas mulheres ali reunidas.

[[v44-16-14]]

^<<v44-16-14,14>>^ Uma delas era uma mulher temente a Deus chamada Lídia, da cidade de Tiatira, comerciante de tecido de púrpura. Enquanto ela nos ouvia, o Senhor lhe abriu o coração, e ela aceitou aquilo que Paulo estava dizendo.

[[v44-16-15]]

^<<v44-16-15,15>>^ Foi batizada, junto com sua família, e pediu que nos hospedássemos em sua casa. "Se concordam que creio de fato no Senhor, venham ficar em minha casa", disse ela, e insistiu até que aceitamos.

[[v44-16-16]]

^<<v44-16-16,16>>^ Certo dia, enquanto íamos ao lugar de oração, veio ao nosso encontro uma escrava possuída por um espírito pelo qual ela predizia o futuro. Com suas adivinhações, ganhava muito dinheiro para seus senhores.

[[v44-16-17]]

^<<v44-16-17,17>>^ Ela seguia Paulo e a nós, gritando: "Estes homens são servos do Deus Altíssimo e vieram anunciar como vocês podem ser salvos!".

[[v44-16-18]]

^<<v44-16-18,18>>^ Isso continuou por vários dias, até que Paulo, indignado, se voltou e disse ao espírito dentro da jovem: "Eu ordeno em nome de Jesus Cristo que saia dela". E, no mesmo instante, o espírito a deixou.

[[v44-16-19]]

^<<v44-16-19,19>>^ Quando os senhores da escrava viram que suas expectativas de lucro haviam sido frustradas, agarraram Paulo e Silas e os arrastaram à presença das autoridades, na praça do mercado.

[[v44-16-20]]

^<<v44-16-20,20>>^ "Estes judeus estão tumultuando a cidade!", gritaram para os magistrados.

[[v44-16-21]]

^<<v44-16-21,21>>^ "Eles ensinam costumes que nós, romanos, não podemos seguir, pois contrariam nossas leis!"

[[v44-16-22]]

^<<v44-16-22,22>>^ Logo, uma multidão revoltada se juntou contra Paulo e Silas, e os magistrados ordenaram que os dois fossem despidos e açoitados com varas.

[[v44-16-23]]

^<<v44-16-23,23>>^ Depois de serem severamente açoitados, foram lançados na prisão. O carcereiro recebeu ordens para não os deixar escapar,

[[v44-16-24]]

^<<v44-16-24,24>>^ por isso os colocou no cárcere interno, prendendo-lhes os pés no tronco.

[[v44-16-25]]

^<<v44-16-25,25>>^ Por volta da meia-noite, Paulo e Silas oravam e cantavam hinos a Deus, e os outros presos ouviam.

[[v44-16-26]]

^<<v44-16-26,26>>^ De repente, houve um forte terremoto, e até os alicerces da prisão foram sacudidos. No mesmo instante, todas as portas se abriram e as correntes de todos os presos se soltaram.

[[v44-16-27]]

^<<v44-16-27,27>>^ Quando o carcereiro acordou, viu as portas da prisão escancaradas. Imaginando que os prisioneiros haviam escapado, puxou a espada para se matar.

[[v44-16-28]]

^<<v44-16-28,28>>^ Paulo, porém, gritou: "Não se mate! Estamos todos aqui!".

[[v44-16-29]]

^<<v44-16-29,29>>^ O carcereiro mandou que trouxessem luz e correu até o cárcere, onde se prostrou, tremendo de medo, diante de Paulo e Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ Então ele os levou para fora e perguntou: "Senhores, que devo fazer para ser salvo?".

[[v44-16-31]]

^<<v44-16-31,31>>^ Eles responderam: "Creia no Senhor Jesus, e você e sua família serão salvos".

[[v44-16-32]]

^<<v44-16-32,32>>^ Então pregaram a palavra do Senhor a ele e a toda a sua família.

[[v44-16-33]]

^<<v44-16-33,33>>^ Mesmo sendo tarde da noite, o carcereiro cuidou deles e lavou suas feridas. Em seguida, ele e todos os seus foram batizados.

[[v44-16-34]]

^<<v44-16-34,34>>^ Depois, levou-os para sua casa e lhes serviu uma refeição, e ele e toda a sua família se alegraram porque creram em Deus.

[[v44-16-35]]

^<<v44-16-35,35>>^ Na manhã seguinte, os magistrados mandaram os guardas ordenarem ao carcereiro: "Solte estes homens!".

[[v44-16-36]]

^<<v44-16-36,36>>^ Então o carcereiro mandou dizer a Paulo: "Os magistrados disseram que você e Silas estão livres. Vão em paz".

[[v44-16-37]]

^<<v44-16-37,37>>^ Paulo, no entanto, respondeu: "Eles nos açoitaram publicamente sem julgamento e nos colocaram na prisão, e nós somos cidadãos romanos. Agora querem que vamos embora às escondidas? De maneira nenhuma! Que venham eles mesmos e nos soltem".

[[v44-16-38]]

^<<v44-16-38,38>>^ Os guardas relataram isso aos magistrados, que ficaram assustados por saber que Paulo e Silas eram cidadãos romanos.

[[v44-16-39]]

^<<v44-16-39,39>>^ Foram até a prisão e lhes pediram desculpas. Então os trouxeram para fora e suplicaram que deixassem a cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ Quando Paulo e Silas saíram da prisão, voltaram à casa de Lídia. Ali se encontraram com os irmãos e os encorajaram mais uma vez. Depois, partiram.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]