include::./index.adoc[]

[[v44-17-0]]
=== Atos, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v44-17-1]]

^<<v44-17-1,1>>^ Então Paulo e Silas passaram pelas cidades de Anfípolis e Apolônia e chegaram a Tessalônica, onde havia uma sinagoga judaica.

[[v44-17-2]]

^<<v44-17-2,2>>^ Como era seu costume, Paulo foi à sinagoga e, durante três sábados seguidos, discutiu as Escrituras com o povo.

[[v44-17-3]]

^<<v44-17-3,3>>^ Explicou as profecias e provou que era necessário o Cristo sofrer e ressuscitar dos mortos. "Esse Jesus de que lhes falo é o Cristo", disse ele.

[[v44-17-4]]

^<<v44-17-4,4>>^ Alguns dos judeus que o ouviam foram convencidos e se uniram a Paulo e Silas, bem como muitos gregos tementes a Deus e várias mulheres de alta posição.

[[v44-17-5]]

^<<v44-17-5,5>>^ Alguns judeus, porém, ficaram com inveja, reuniram alguns desordeiros e desocupados e, com a multidão, começaram um tumulto. Invadiram a casa de Jasom em busca de Paulo e Silas para entregá-los ao conselho da cidade,

[[v44-17-6]]

^<<v44-17-6,6>>^ mas, como não os encontraram, arrastaram para fora Jasom e alguns outros irmãos e os levaram diante do conselho. Gritavam: "Aqueles que têm causado transtornos no mundo todo agora estão aqui, perturbando nossa cidade,

[[v44-17-7]]

^<<v44-17-7,7>>^ e Jasom os recebeu em sua casa! São todos culpados de traição contra César, pois afirmam que existe um outro rei, um tal de Jesus".

[[v44-17-8]]

^<<v44-17-8,8>>^ Ao ouvir isso, o povo da cidade e o conselho se agitaram.

[[v44-17-9]]

^<<v44-17-9,9>>^ Então os oficiais obrigaram Jasom e os outros irmãos a pagarem fiança, e depois os soltaram.

[[v44-17-10]]

^<<v44-17-10,10>>^ Ao anoitecer, os irmãos enviaram Paulo e Silas a Bereia. Quando lá chegaram, foram à sinagoga judaica.

[[v44-17-11]]

^<<v44-17-11,11>>^ Os judeus que moravam em Bereia tinham a mente mais aberta que os de Tessalônica e ouviram a mensagem de Paulo com grande interesse. Todos os dias, examinavam as Escrituras para ver se Paulo e Silas ensinavam a verdade.

[[v44-17-12]]

^<<v44-17-12,12>>^ Como resultado, muitos judeus creram, assim como vários gregos de alta posição, tanto homens como mulheres.

[[v44-17-13]]

^<<v44-17-13,13>>^ Mas, quando os judeus de Tessalônica souberam que Paulo estava pregando a palavra de Deus em Bereia, foram até lá e criaram um alvoroço.

[[v44-17-14]]

^<<v44-17-14,14>>^ Os irmãos agiram de imediato e enviaram Paulo para o litoral, enquanto Silas e Timóteo permaneceram na cidade.

[[v44-17-15]]

^<<v44-17-15,15>>^ Os que acompanharam Paulo o levaram até Atenas e, depois, voltaram a Bereia com instruções para Silas e Timóteo irem ao encontro dele o mais depressa possível.

[[v44-17-16]]

^<<v44-17-16,16>>^ Enquanto Paulo esperava por eles em Atenas, ficou muito indignado ao ver ídolos por toda a cidade.

[[v44-17-17]]

^<<v44-17-17,17>>^ Por isso, ia à sinagoga debater com os judeus e com os gentios tementes a Deus e falava diariamente na praça pública a todos que ali estavam.

[[v44-17-18]]

^<<v44-17-18,18>>^ Paulo também debateu com alguns dos filósofos epicureus e estoicos. Quando lhes falou de Jesus e da ressurreição, eles perguntaram: "O que esse tagarela está querendo dizer?". Outros disseram: "Parece estar falando de deuses estrangeiros".

[[v44-17-19]]

^<<v44-17-19,19>>^ Então levaram Paulo ao conselho da cidade e disseram: "Pode nos dizer que novo ensino é esse?

[[v44-17-20]]

^<<v44-17-20,20>>^ Você diz coisas um tanto estranhas, e queremos saber o que significam".

[[v44-17-21]]

^<<v44-17-21,21>>^ (Convém explicar que os atenienses, bem como os estrangeiros que viviam em Atenas, pareciam não fazer outra coisa senão discutir as últimas novidades.)

[[v44-17-22]]

^<<v44-17-22,22>>^ Então Paulo se levantou diante do conselho e assim se dirigiu a seus membros: "Homens de Atenas, vejo que em todos os aspectos vocês são muito religiosos,

[[v44-17-23]]

^<<v44-17-23,23>>^ pois, enquanto andava pela cidade, reparei em seus diversos altares. Um deles trazia a seguinte inscrição: ‘Ao Deus Desconhecido’. Esse Deus que vocês adoram sem conhecer é exatamente aquele de que lhes falo.

[[v44-17-24]]

^<<v44-17-24,24>>^ "Ele é o Deus que fez o mundo e tudo que nele há. Uma vez que é Senhor dos céus e da terra, não habita em templos feitos por homens

[[v44-17-25]]

^<<v44-17-25,25>>^ e não é servido por mãos humanas, pois não necessita de coisa alguma. Ele mesmo dá vida e fôlego a tudo, e supre cada necessidade.

[[v44-17-26]]

^<<v44-17-26,26>>^ De um só homem ele criou todas as nações da terra, tendo decidido de antemão onde se estabeleceriam e por quanto tempo.

[[v44-17-27]]

^<<v44-17-27,27>>^ "Seu propósito era que as nações buscassem a Deus e, tateando, talvez viessem a encontrá-lo, embora ele não esteja longe de nenhum de nós.

[[v44-17-28]]

^<<v44-17-28,28>>^ Pois nele vivemos, nos movemos e existimos. Como disseram alguns de seus próprios poetas: ‘Somos descendência dele’.

[[v44-17-29]]

^<<v44-17-29,29>>^ E, por ser isso verdade, não devemos imaginar Deus como um ídolo de ouro, prata ou pedra, projetado por artesãos.

[[v44-17-30]]

^<<v44-17-30,30>>^ "No passado, Deus não levou em conta a ignorância das pessoas acerca dessas coisas, mas agora ele ordena que todos, em todo lugar, se arrependam.

[[v44-17-31]]

^<<v44-17-31,31>>^ Pois ele estabeleceu um dia para julgar o mundo com justiça, por meio do homem que ele designou, e mostrou a todos quem é esse homem ao ressuscitá-lo dos mortos".

[[v44-17-32]]

^<<v44-17-32,32>>^ Quando ouviram Paulo falar da ressurreição dos mortos, alguns riram com desprezo. Outros, porém, disseram: "Queremos ouvir mais sobre isso em outra ocasião".

[[v44-17-33]]

^<<v44-17-33,33>>^ Então Paulo se retirou do conselho,

[[v44-17-34]]

^<<v44-17-34,34>>^ mas alguns se juntaram a ele e creram. Entre eles estavam Dionísio, membro do conselho, uma mulher chamada Dâmaris, e alguns outros.

'''

xref:044-atos/044-atos-016.adoc#v44-16-0[&#60; Capítulo Anterior] | <<v44-17-0,Topo>> | xref:044-atos/044-atos-018.adoc#v44-18-0[Próximo Capítulo &#62;]