include::./index.adoc[]

[[v44-14-0]]
=== Atos, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v44-14-1]]

^<<v44-14-1,1>>^ Em Icônio, Paulo e Barnabé também foram à sinagoga judaica e falaram de tal modo que muitos creram, tanto judeus como gentios.

[[v44-14-2]]

^<<v44-14-2,2>>^ Alguns dos judeus que não creram, porém, incitaram os gentios e envenenaram a mente deles contra Paulo e Barnabé.

[[v44-14-3]]

^<<v44-14-3,3>>^ Ainda assim, os apóstolos passaram bastante tempo ali, falando corajosamente da graça do Senhor, que confirmava a mensagem deles concedendo-lhes poder para realizar sinais e maravilhas.

[[v44-14-4]]

^<<v44-14-4,4>>^ Com isso, o povo da cidade ficou dividido: alguns tomaram partido dos judeus, e outros, dos apóstolos.

[[v44-14-5]]

^<<v44-14-5,5>>^ Então um grupo de gentios, judeus e seus líderes resolveu atacá-los e apedrejá-los.

[[v44-14-6]]

^<<v44-14-6,6>>^ Quando os apóstolos souberam disso, fugiram para a região da Licaônia, para as cidades de Listra e Derbe e seus arredores.

[[v44-14-7]]

^<<v44-14-7,7>>^ E ali anunciaram as boas-novas.

[[v44-14-8]]

^<<v44-14-8,8>>^ Enquanto estavam em Listra, Paulo e Barnabé encontraram um homem com os pés aleijados. Sofria desse problema desde o nascimento e, portanto, nunca tinha andado. Estava sentado

[[v44-14-9]]

^<<v44-14-9,9>>^ e ouvia Paulo pregar. Paulo olhou diretamente para ele e, vendo que ele tinha fé para ser curado,

[[v44-14-10]]

^<<v44-14-10,10>>^ disse em alta voz: "Levante-se!". O homem se levantou de um salto e começou a andar.

[[v44-14-11]]

^<<v44-14-11,11>>^ A multidão, vendo o que Paulo havia feito, gritou no dialeto local: "Os deuses vieram até nós em forma de homens!".

[[v44-14-12]]

^<<v44-14-12,12>>^ Concluíram que Barnabé era o deus grego Zeus, e Paulo, o deus Hermes, pois era ele quem proclamava a mensagem.

[[v44-14-13]]

^<<v44-14-13,13>>^ O sacerdote do templo de Zeus, que ficava na entrada da cidade, trouxe touros e coroas de flores até as portas da cidade, pois ele e a multidão queriam oferecer sacrifícios aos apóstolos.

[[v44-14-14]]

^<<v44-14-14,14>>^ Quando Barnabé e Paulo ouviram o que estava acontecendo, rasgaram as roupas e correram para o meio do povo, gritando:

[[v44-14-15]]

^<<v44-14-15,15>>^ "Amigos, por que vocês estão fazendo isso? Somos homens como vocês! Viemos lhes anunciar as boas-novas, para que abandonem estas coisas sem valor e se voltem para o Deus vivo, que fez os céus e a terra, o mar e tudo que neles há.

[[v44-14-16]]

^<<v44-14-16,16>>^ No passado, ele permitiu que as nações seguissem seus próprios caminhos,

[[v44-14-17]]

^<<v44-14-17,17>>^ mas nunca as deixou sem evidências de sua existência e de sua bondade. Ele lhes concede chuvas e boas colheitas, e também alimento e um coração alegre".

[[v44-14-18]]

^<<v44-14-18,18>>^ Apesar dessas palavras, Paulo e Barnabé tiveram dificuldade para impedir que o povo lhes oferecesse sacrifícios.

[[v44-14-19]]

^<<v44-14-19,19>>^ Então alguns judeus chegaram de Antioquia e Icônio e instigaram a multidão. Apedrejaram Paulo e o arrastaram para fora da cidade, pensando que ele estivesse morto.

[[v44-14-20]]

^<<v44-14-20,20>>^ No entanto, quando os discípulos o rodearam, ele se levantou e entrou novamente na cidade. No dia seguinte, partiu com Barnabé para Derbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ Depois de terem anunciado as boas-novas em Derbe e feito muitos discípulos, Paulo e Barnabé voltaram a Listra, Icônio e Antioquia da Pisídia,

[[v44-14-22]]

^<<v44-14-22,22>>^ onde fortaleceram os discípulos. Eles os encorajaram a permanecer na fé, lembrando-os de que é necessário passar por muitos sofrimentos até entrar no reino de Deus.

[[v44-14-23]]

^<<v44-14-23,23>>^ Paulo e Barnabé também escolheram presbíteros em cada igreja e, com orações e jejuns, os entregaram aos cuidados do Senhor, em quem haviam crido.

[[v44-14-24]]

^<<v44-14-24,24>>^ Então viajaram de volta pela Pisídia até a Panfília.

[[v44-14-25]]

^<<v44-14-25,25>>^ Pregaram a palavra em Perge e desceram para Atália.

[[v44-14-26]]

^<<v44-14-26,26>>^ Por fim, voltaram de navio para Antioquia, onde sua viagem tinha começado e onde haviam sido entregues à graça de Deus para realizar o trabalho que agora completavam.

[[v44-14-27]]

^<<v44-14-27,27>>^ Quando chegaram a Antioquia, reuniram a igreja e relataram tudo que Deus tinha feito por meio deles e como tinha aberto a porta da fé também para os gentios.

[[v44-14-28]]

^<<v44-14-28,28>>^ E permaneceram ali com os discípulos por muito tempo.

'''

xref:044-atos/044-atos-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-atos/044-atos-015.adoc#v44-15-0[Próximo Capítulo &#62;]