include::./index.adoc[]

[[v44-25-0]]
=== Atos, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v44-25-1]]

^<<v44-25-1,1>>^ Três dias depois que Festo chegou a Cesareia para assumir suas novas responsabilidades no governo da província, partiu para Jerusalém,

[[v44-25-2]]

^<<v44-25-2,2>>^ onde os principais sacerdotes e outros líderes judeus se reuniram com ele e lhe apresentaram as acusações contra Paulo.

[[v44-25-3]]

^<<v44-25-3,3>>^ Pediram a Festo, como favor, que transferisse Paulo para Jerusalém, pois planejavam armar uma emboscada para matá-lo no caminho.

[[v44-25-4]]

^<<v44-25-4,4>>^ Festo respondeu que Paulo estava em Cesareia e que ele próprio voltaria para lá em breve.

[[v44-25-5]]

^<<v44-25-5,5>>^ "Alguns de vocês que têm autoridade voltem comigo", disse ele. "Se Paulo tiver feito algo de errado, vocês poderão apresentar suas acusações."

[[v44-25-6]]

^<<v44-25-6,6>>^ Oito ou dez dias depois, Festo voltou a Cesareia e, no dia seguinte, convocou o tribunal e mandou que trouxessem Paulo.

[[v44-25-7]]

^<<v44-25-7,7>>^ Quando Paulo chegou, os líderes judeus vindos de Jerusalém se juntaram ao seu redor e fizeram várias acusações graves que não podiam provar.

[[v44-25-8]]

^<<v44-25-8,8>>^ Paulo se defendeu: "Não sou culpado de nenhum crime contra as leis judaicas, nem contra o templo, nem contra o governo romano".

[[v44-25-9]]

^<<v44-25-9,9>>^ Então Festo, querendo agradar aos judeus, perguntou: "Você está disposto a ir a Jerusalém e ali ser julgado diante de mim?".

[[v44-25-10]]

^<<v44-25-10,10>>^ Paulo respondeu: "Este é um tribunal oficial romano, portanto devo ser julgado aqui mesmo. O senhor sabe muito bem que não fiz nenhum mal aos judeus.

[[v44-25-11]]

^<<v44-25-11,11>>^ Se fiz algo para merecer a pena de morte, não me recuso a morrer. Mas, se sou inocente, ninguém tem o direito de me entregar a estes homens. Eu apelo para César".

[[v44-25-12]]

^<<v44-25-12,12>>^ Festo consultou seus conselheiros e, por fim, respondeu: "Muito bem, você apelou para César, então irá para César".

[[v44-25-13]]

^<<v44-25-13,13>>^ Alguns dias depois, o rei Agripa chegou com sua irmã, Berenice, para visitar Festo.

[[v44-25-14]]

^<<v44-25-14,14>>^ Durante a estada deles, que durou vários dias, Festo discutiu o caso de Paulo com o rei. "Tenho aqui um prisioneiro que Félix deixou para mim", disse ele.

[[v44-25-15]]

^<<v44-25-15,15>>^ "Quando estive em Jerusalém, os principais sacerdotes e líderes judeus apresentaram acusações contra ele e pediram que eu o condenasse.

[[v44-25-16]]

^<<v44-25-16,16>>^ Eu lhes disse que a lei romana não condena ninguém sem julgamento. O acusado deve ter a oportunidade de confrontar seus acusadores e se defender.

[[v44-25-17]]

^<<v44-25-17,17>>^ "Quando eles vieram aqui para o julgamento, não me demorei. Convoquei o tribunal logo no dia seguinte e mandei chamar Paulo.

[[v44-25-18]]

^<<v44-25-18,18>>^ Os judeus, porém, não o acusaram de nenhum dos crimes que eu esperava.

[[v44-25-19]]

^<<v44-25-19,19>>^ Ao contrário, era algo relacionado à sua religião e a um morto chamado Jesus, que Paulo insiste que está vivo.

[[v44-25-20]]

^<<v44-25-20,20>>^ Sem saber como investigar essas questões, perguntei a Paulo se estava disposto a ir a Jerusalém e ali ser julgado por essas acusações,

[[v44-25-21]]

^<<v44-25-21,21>>^ mas ele apelou ao imperador para que julgue seu caso. Por isso, ordenei que fosse mantido sob custódia até eu tomar as providências necessárias para enviá-lo a César."

[[v44-25-22]]

^<<v44-25-22,22>>^ Então Agripa disse a Festo: "Gostaria de ouvir esse homem pessoalmente". E Festo respondeu: "Amanhã poderá ouvi-lo!".

[[v44-25-23]]

^<<v44-25-23,23>>^ No dia seguinte, Agripa e Berenice chegaram à sala de audiência com grande pompa, acompanhados de oficiais militares e homens importantes da cidade. Festo mandou trazer Paulo e,

[[v44-25-24]]

^<<v44-25-24,24>>^ em seguida, disse: "Rei Agripa e demais presentes, este é o homem cuja morte é exigida pelos judeus tanto daqui como de Jerusalém.

[[v44-25-25]]

^<<v44-25-25,25>>^ Em minha opinião, ele não fez coisa alguma para merecer a morte. Contudo, uma vez que apelou ao imperador para que julgue seu caso, decidi enviá-lo a Roma.

[[v44-25-26]]

^<<v44-25-26,26>>^ "Não sei, porém, o que escrever ao imperador, pois não há nenhuma acusação clara contra ele. Por isso eu o trouxe hoje diante dos senhores, especialmente do rei Agripa, para que, depois de o interrogarmos, eu tenha algo para escrever.

[[v44-25-27]]

^<<v44-25-27,27>>^ Pois não faz sentido enviar um prisioneiro ao imperador sem especificar as acusações contra ele".

'''

xref:044-atos/044-atos-024.adoc#v44-24-0[&#60; Capítulo Anterior] | <<v44-25-0,Topo>> | xref:044-atos/044-atos-026.adoc#v44-26-0[Próximo Capítulo &#62;]