include::./index.adoc[]

[[v44-13-0]]
=== Atos, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v44-13-1]]

^<<v44-13-1,1>>^ Entre os profetas e mestres da igreja de Antioquia da Síria estavam Barnabé e Simeão, chamado Negro, Lúcio de Cirene, Manaém, que tinha sido criado com o rei Herodes Antipas, e Saulo.

[[v44-13-2]]

^<<v44-13-2,2>>^ Certo dia, enquanto adoravam o Senhor e jejuavam, o Espírito Santo disse: "Separem Barnabé e Saulo para realizarem o trabalho para o qual os chamei".

[[v44-13-3]]

^<<v44-13-3,3>>^ Então, depois de mais jejuns e orações, impuseram as mãos sobre eles e os enviaram em sua missão.

[[v44-13-4]]

^<<v44-13-4,4>>^ Enviados pelo Espírito Santo, eles desceram ao porto de Selêucia, de onde navegaram para a ilha de Chipre.

[[v44-13-5]]

^<<v44-13-5,5>>^ Ali, na cidade de Salamina, foram às sinagogas judaicas e pregaram a palavra de Deus. João Marcos os acompanhava como assistente.

[[v44-13-6]]

^<<v44-13-6,6>>^ Viajaram por toda a ilha até que, por fim, chegaram a Pafos, onde encontraram um feiticeiro judeu, um falso profeta chamado Barjesus.

[[v44-13-7]]

^<<v44-13-7,7>>^ Ele acompanhava o governador Sérgio Paulo, um homem inteligente que convidou Barnabé e Saulo para visitá-lo, pois desejava ouvir a palavra de Deus.

[[v44-13-8]]

^<<v44-13-8,8>>^ Mas Elimas, o feiticeiro (esse é o significado de seu nome), opôs-se a eles, na tentativa de impedir que o governador viesse a crer.

[[v44-13-9]]

^<<v44-13-9,9>>^ Cheio do Espírito Santo, Saulo, também conhecido como Paulo, encarou Elimas nos olhos

[[v44-13-10]]

^<<v44-13-10,10>>^ e disse: "Filho do diabo, cheio de toda espécie de engano e maldade e inimigo de tudo que é certo! Quando deixará de distorcer os caminhos retos do Senhor?

[[v44-13-11]]

^<<v44-13-11,11>>^ Preste atenção, pois o Senhor colocou a mão sobre você para castigá-lo, e você ficará cego, sem conseguir ver a luz do sol por algum tempo". No mesmo instante, neblina e escuridão cobriram-lhe os olhos e ele começou a tatear, suplicando que alguém o tomasse pela mão e o guiasse.

[[v44-13-12]]

^<<v44-13-12,12>>^ Quando o governador viu o que havia acontecido, creu, muito admirado com o ensino a respeito do Senhor.

[[v44-13-13]]

^<<v44-13-13,13>>^ Paulo e seus companheiros saíram de Pafos num navio e foram à Panfília, onde aportaram em Perge. Ali, João Marcos os deixou e voltou para Jerusalém.

[[v44-13-14]]

^<<v44-13-14,14>>^ Paulo e Barnabé prosseguiram para o interior, até Antioquia da Pisídia. No sábado, foram à sinagoga.

[[v44-13-15]]

^<<v44-13-15,15>>^ Depois da leitura dos livros da lei e dos profetas, os chefes da sinagoga lhes mandaram um recado: "Irmãos, se vocês têm uma palavra de encorajamento para o povo, podem falar".

[[v44-13-16]]

^<<v44-13-16,16>>^ Então Paulo ficou em pé, levantou a mão para pedir silêncio e começou a falar: "Homens de Israel e gentios tementes a Deus, ouçam-me!

[[v44-13-17]]

^<<v44-13-17,17>>^ "O Deus desta nação de Israel escolheu nossos antepassados e fez que se multiplicassem e se fortalecessem durante o tempo em que ficaram no Egito. Então, com braço poderoso, ele os tirou da escravidão.

[[v44-13-18]]

^<<v44-13-18,18>>^ Ele suportou seu comportamento durante os quarenta anos em que andaram sem rumo pelo deserto.

[[v44-13-19]]

^<<v44-13-19,19>>^ Destruiu sete nações em Canaã e deu seu território a Israel como herança.

[[v44-13-20]]

^<<v44-13-20,20>>^ Tudo isso levou cerca de quatrocentos e cinquenta anos. "Depois, Deus lhes deu juízes para governá-los até o tempo do profeta Samuel.

[[v44-13-21]]

^<<v44-13-21,21>>^ Então o povo pediu um rei, e ele lhes deu Saul, filho de Quis, homem da tribo de Benjamim, e ele reinou por quarenta anos.

[[v44-13-22]]

^<<v44-13-22,22>>^ Mas Deus removeu Saul e colocou em seu lugar Davi, a respeito de quem Deus disse: ‘Davi, filho de Jessé, é um homem segundo o meu coração; fará tudo que for da minha vontade’.

[[v44-13-23]]

^<<v44-13-23,23>>^ "E Jesus, um dos descendentes de Davi, é o salvador que Deus concedeu a Israel, conforme sua promessa!

[[v44-13-24]]

^<<v44-13-24,24>>^ Antes da vinda de Jesus, João Batista anunciou que todo o povo de Israel precisava se arrepender e ser batizado.

[[v44-13-25]]

^<<v44-13-25,25>>^ Quando João estava concluindo seu trabalho, perguntou: ‘Vocês pensam que eu sou o Cristo? Não sou! Mas ele vem em breve, e não sou digno sequer de desamarrar as correias de suas sandálias’.

[[v44-13-26]]

^<<v44-13-26,26>>^ "Irmãos, vocês que são filhos de Abraão e também vocês gentios tementes a Deus, esta mensagem de salvação foi enviada a nós.

[[v44-13-27]]

^<<v44-13-27,27>>^ O povo de Jerusalém e seus líderes não reconheceram que Jesus era aquele a respeito de quem os profetas haviam falado. Em vez disso, eles o condenaram e, ao fazê-lo, cumpriram as palavras dos profetas, que são lidas todos os sábados.

[[v44-13-28]]

^<<v44-13-28,28>>^ Não encontraram motivo legal para executá-lo, mas, ainda assim, pediram a Pilatos que o matasse.

[[v44-13-29]]

^<<v44-13-29,29>>^ "Depois de cumprirem tudo que as profecias diziam a respeito dele, eles o tiraram da cruz e o colocaram num túmulo,

[[v44-13-30]]

^<<v44-13-30,30>>^ mas Deus o ressuscitou dos mortos.

[[v44-13-31]]

^<<v44-13-31,31>>^ E, por muitos dias, ele apareceu àqueles que o tinham acompanhado da Galileia para Jerusalém. Agora eles são suas testemunhas diante do povo.

[[v44-13-32]]

^<<v44-13-32,32>>^ "Estamos aqui para trazer a vocês esta boa-nova. A promessa foi feita a nossos antepassados,

[[v44-13-33]]

^<<v44-13-33,33>>^ e agora Deus a cumpriu para nós, os descendentes deles, ao ressuscitar Jesus. É isto que o segundo salmo diz a respeito dele: ‘Você é meu Filho; hoje eu o gerei’.

[[v44-13-34]]

^<<v44-13-34,34>>^ Pois Deus havia prometido ressuscitá-lo dos mortos, para que jamais apodrecesse no túmulo. Ele disse: ‘Eu lhes darei as bênçãos sagradas que prometi a Davi’.

[[v44-13-35]]

^<<v44-13-35,35>>^ Em outro salmo, ele explicou de modo mais direto: ‘Não permitirás que o teu Santo apodreça no túmulo’.

[[v44-13-36]]

^<<v44-13-36,36>>^ Não se trata de uma referência a Davi, porque, depois que Davi fez a vontade de Deus em sua geração, morreu e foi sepultado com seus antepassados, e seu corpo apodreceu.

[[v44-13-37]]

^<<v44-13-37,37>>^ É uma referência a outra pessoa, a alguém a quem Deus ressuscitou e cujo corpo não apodreceu.

[[v44-13-38]]

^<<v44-13-38,38>>^ "Ouçam, irmãos! Estamos aqui para proclamar que, por meio de Jesus, há perdão para os pecados.

[[v44-13-39]]

^<<v44-13-39,39>>^ Todo o que nele crê é declarado justo diante de Deus, algo que a lei de Moisés jamais pôde fazer.

[[v44-13-40]]

^<<v44-13-40,40>>^ Por isso, tomem cuidado para que não se apliquem a vocês as palavras dos profetas:

[[v44-13-41]]

^<<v44-13-41,41>>^ ‘Olhem, zombadores; fiquem admirados e morram! Pois faço algo em seus dias, algo em que vocês não acreditariam mesmo que lhes contassem’".

[[v44-13-42]]

^<<v44-13-42,42>>^ Quando Paulo e Barnabé estavam saindo da sinagoga, o povo pediu que voltassem a falar dessas coisas na semana seguinte.

[[v44-13-43]]

^<<v44-13-43,43>>^ Muitos judeus e gentios devotos convertidos ao judaísmo seguiram Paulo e Barnabé, que insistiam com eles para que continuassem a confiar na graça de Deus.

[[v44-13-44]]

^<<v44-13-44,44>>^ No sábado seguinte, quase toda a cidade compareceu para ouvir a palavra do Senhor.

[[v44-13-45]]

^<<v44-13-45,45>>^ Quando alguns dos judeus viram as multidões, ficaram com inveja, de modo que difamaram Paulo e contestavam tudo que ele dizia.

[[v44-13-46]]

^<<v44-13-46,46>>^ Então Paulo e Barnabé se pronunciaram corajosamente, dizendo: "Era necessário que pregássemos a palavra de Deus primeiro a vocês, judeus. Mas, uma vez que vocês a rejeitaram e não se consideraram dignos da vida eterna, agora vamos oferecê-la aos gentios.

[[v44-13-47]]

^<<v44-13-47,47>>^ Pois foi isso que o Senhor nos ordenou quando disse: ‘Fiz de você uma luz para os gentios, para levar a salvação até os lugares mais distantes da terra’".

[[v44-13-48]]

^<<v44-13-48,48>>^ Quando ouviram isso, os gentios se alegraram e agradeceram ao Senhor por essa mensagem, e todos que haviam sido escolhidos para a vida eterna creram.

[[v44-13-49]]

^<<v44-13-49,49>>^ Assim, a palavra do Senhor se espalhou por toda aquela região.

[[v44-13-50]]

^<<v44-13-50,50>>^ Então os judeus, instigando as mulheres religiosas influentes e as autoridades da cidade, provocaram uma multidão contra Paulo e Barnabé e os expulsaram dali.

[[v44-13-51]]

^<<v44-13-51,51>>^ Eles, porém, sacudiram o pó dos pés em sinal de reprovação e foram à cidade de Icônio.

[[v44-13-52]]

^<<v44-13-52,52>>^ E os discípulos estavam cheios de alegria e do Espírito Santo.

'''

xref:044-atos/044-atos-012.adoc#v44-12-0[&#60; Capítulo Anterior] | <<v44-13-0,Topo>> | xref:044-atos/044-atos-014.adoc#v44-14-0[Próximo Capítulo &#62;]