include::./index.adoc[]

[[v44-24-0]]
=== Atos, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v44-24-1]]

^<<v44-24-1,1>>^ Cinco dias depois, o sumo sacerdote Ananias chegou com alguns dos líderes do povo e um advogado chamado Tértulo para exporem ao governador sua causa contra Paulo.

[[v44-24-2]]

^<<v44-24-2,2>>^ Quando Paulo foi chamado, Tértulo apresentou as acusações: "Excelentíssimo Félix, o senhor tem proporcionado a nós, judeus, um longo período de paz e, com perspicácia, tem realizado reformas que muito nos beneficiam.

[[v44-24-3]]

^<<v44-24-3,3>>^ Por todas essas coisas nós lhe somos extremamente gratos.

[[v44-24-4]]

^<<v44-24-4,4>>^ Contudo, não desejo tomar seu tempo, por isso peço sua atenção apenas por um momento.

[[v44-24-5]]

^<<v44-24-5,5>>^ Constatamos que este homem é um perturbador, que vive causando tumultos entre os judeus de todo o mundo. É o principal líder da seita conhecida como os Nazarenos.

[[v44-24-6]]

^<<v44-24-6,6>>^ Quando o prendemos, estava tentando profanar o templo. Nós queríamos julgá-lo de acordo com nossa lei,

[[v44-24-7]]

^<<v44-24-7,7>>^ mas Lísias, o comandante do regimento, usou de força e o tirou de nossas mãos,

[[v44-24-8]]

^<<v44-24-8,8>>^ e ordenou a nós, os acusadores, que nos apresentássemos perante o senhor. Nossas acusações poderão ser confirmadas quando o senhor interrogar Paulo pessoalmente".

[[v44-24-9]]

^<<v44-24-9,9>>^ Os outros judeus concordaram e declararam ser verdadeiro o que Tértulo tinha dito.

[[v44-24-10]]

^<<v44-24-10,10>>^ Quando Paulo recebeu um sinal do governador para falar, disse: "Sei que o senhor tem julgado questões dos judeus há muitos anos e, portanto, apresento-lhe minha defesa de bom grado.

[[v44-24-11]]

^<<v44-24-11,11>>^ O senhor poderá verificar com facilidade que cheguei a Jerusalém não mais que doze dias atrás para adorar no templo.

[[v44-24-12]]

^<<v44-24-12,12>>^ Meus acusadores não me encontraram discutindo com ninguém no templo, nem causando tumulto em nenhuma sinagoga, nem nas ruas da cidade.

[[v44-24-13]]

^<<v44-24-13,13>>^ Eles não podem provar as acusações que fazem contra mim.

[[v44-24-14]]

^<<v44-24-14,14>>^ "Reconheço, porém, que sou seguidor do Caminho, que eles chamam de seita. Adoro o Deus de nossos antepassados e creio firmemente na lei judaica e em tudo que está escrito nos profetas.

[[v44-24-15]]

^<<v44-24-15,15>>^ Tenho em Deus a mesma esperança destes homens, de que ele ressuscitará tanto os justos como os injustos.

[[v44-24-16]]

^<<v44-24-16,16>>^ Por isso, procuro sempre manter a consciência limpa diante de Deus e dos homens.

[[v44-24-17]]

^<<v44-24-17,17>>^ "Depois de estar ausente por vários anos, voltei a Jerusalém com dinheiro para ajudar meu povo e apresentar ofertas.

[[v44-24-18]]

^<<v44-24-18,18>>^ Meus acusadores me viram no templo depois que completei minha cerimônia de purificação. Não havia multidão nenhuma ao meu redor e nenhum tumulto.

[[v44-24-19]]

^<<v44-24-19,19>>^ Só estavam ali alguns judeus da Ásia, e são eles que deveriam estar aqui diante do senhor para me acusar, se têm algo contra mim.

[[v44-24-20]]

^<<v44-24-20,20>>^ Pergunte a estes homens que aqui estão de que crimes o conselho dos líderes do povo me considerou culpado,

[[v44-24-21]]

^<<v44-24-21,21>>^ exceto pela ocasião em que gritei: ‘Estou sendo julgado diante dos senhores porque creio na ressurreição dos mortos!’".

[[v44-24-22]]

^<<v44-24-22,22>>^ Nesse momento, Félix, que tinha bastante conhecimento sobre o Caminho, interrompeu a audiência e disse: "Esperem até Lísias, o comandante do regimento, chegar. Então decidirei o caso de vocês".

[[v44-24-23]]

^<<v44-24-23,23>>^ Ordenou que um oficial mantivesse Paulo sob custódia, mas lhe deu certa liberdade e permitiu que seus amigos o visitassem e providenciassem aquilo de que ele precisava.

[[v44-24-24]]

^<<v44-24-24,24>>^ Alguns dias depois, Félix voltou com sua esposa, Drusila, que era judia. Mandou chamar Paulo, e os dois ouviram enquanto ele lhes falava a respeito da fé em Cristo Jesus.

[[v44-24-25]]

^<<v44-24-25,25>>^ Quando Paulo passou a falar da justiça divina, do domínio próprio e do dia do juízo que estava por vir, Félix teve medo e disse: "Pode ir, por enquanto. Quando for mais conveniente, mandarei chamá-lo outra vez".

[[v44-24-26]]

^<<v44-24-26,26>>^ Félix também esperava que Paulo lhe oferecesse dinheiro, de modo que mandava buscá-lo com frequência e conversava com ele.

[[v44-24-27]]

^<<v44-24-27,27>>^ Assim se passaram dois anos, e Félix foi sucedido por Pórcio Festo. E, uma vez que Félix desejava obter a simpatia dos judeus, manteve Paulo na prisão.

'''

xref:044-atos/044-atos-023.adoc#v44-23-0[&#60; Capítulo Anterior] | <<v44-24-0,Topo>> | xref:044-atos/044-atos-025.adoc#v44-25-0[Próximo Capítulo &#62;]