include::./index.adoc[]

[[v44-21-0]]
=== Atos, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v44-21-1]]

^<<v44-21-1,1>>^ Depois de nos despedirmos, navegamos em direção à ilha de Cós. No dia seguinte, chegamos a Rodes e, então, a Pátara.

[[v44-21-2]]

^<<v44-21-2,2>>^ Ali, embarcamos num navio que partia para a Fenícia.

[[v44-21-3]]

^<<v44-21-3,3>>^ Avistamos a ilha de Chipre, passamos por ela à nossa esquerda e aportamos em Tiro, na Síria, onde o navio deixaria sua carga.

[[v44-21-4]]

^<<v44-21-4,4>>^ No desembarque, encontramos os discípulos que ali viviam e ficamos com eles por uma semana. Pelo Espírito, eles advertiam Paulo de que não fosse a Jerusalém.

[[v44-21-5]]

^<<v44-21-5,5>>^ Ao fim de nosso tempo ali, voltamos ao navio, e toda a congregação, incluindo mulheres e crianças, saiu da cidade e nos acompanhou até a praia. Ali nos ajoelhamos, oramos

[[v44-21-6]]

^<<v44-21-6,6>>^ e nos despedimos. Então subimos a bordo, e eles voltaram para casa.

[[v44-21-7]]

^<<v44-21-7,7>>^ Depois que partimos de Tiro, chegamos a Ptolemaida, onde saudamos os irmãos e passamos um dia.

[[v44-21-8]]

^<<v44-21-8,8>>^ No dia seguinte, prosseguimos para Cesareia e nos hospedamos na casa de Filipe, o evangelista, um dos sete que tinham servido na igreja em Jerusalém.

[[v44-21-9]]

^<<v44-21-9,9>>^ Ele tinha quatro filhas solteiras que profetizavam.

[[v44-21-10]]

^<<v44-21-10,10>>^ Muitos dias depois, chegou da Judeia um profeta chamado Ágabo.

[[v44-21-11]]

^<<v44-21-11,11>>^ Ele veio ao nosso encontro, tomou o cinto de Paulo e com ele amarrou os próprios pés e as mãos. Em seguida, disse: "O Espírito Santo declara: ‘Assim o dono deste cinto será amarrado pelos judeus, em Jerusalém, e entregue aos gentios’".

[[v44-21-12]]

^<<v44-21-12,12>>^ Ao ouvir isso, nós e os irmãos dali suplicamos a Paulo que não fosse a Jerusalém.

[[v44-21-13]]

^<<v44-21-13,13>>^ Ele, porém, disse: "Por que todo esse choro? Assim vocês me partem o coração! Estou pronto não apenas para ser preso em Jerusalém, mas para morrer pelo Senhor Jesus".

[[v44-21-14]]

^<<v44-21-14,14>>^ Quando ficou evidente que não conseguiríamos fazê-lo mudar de ideia, desistimos e dissemos: "Que seja feita a vontade do Senhor".

[[v44-21-15]]

^<<v44-21-15,15>>^ Depois disso, arrumamos nossas coisas e partimos para Jerusalém.

[[v44-21-16]]

^<<v44-21-16,16>>^ Alguns discípulos de Cesareia nos acompanharam e nos levaram à casa de Mnasom, nascido em Chipre e um dos primeiros discípulos.

[[v44-21-17]]

^<<v44-21-17,17>>^ Quando chegamos a Jerusalém, os irmãos nos deram calorosas boas-vindas.

[[v44-21-18]]

^<<v44-21-18,18>>^ No dia seguinte, Paulo foi conosco a um encontro com Tiago, e todos os presbíteros da igreja de Jerusalém estavam presentes.

[[v44-21-19]]

^<<v44-21-19,19>>^ Depois que Paulo os cumprimentou, relatou em detalhes o que Deus havia realizado entre os gentios por meio de seu ministério.

[[v44-21-20]]

^<<v44-21-20,20>>^ Quando ouviram isso, louvaram a Deus e disseram: "Você sabe, irmão, quantos milhares de judeus também creram, e todos eles seguem à risca a lei de Moisés.

[[v44-21-21]]

^<<v44-21-21,21>>^ Mas eles foram informados de que você ensina todos os judeus que vivem entre os gentios a abandonarem a lei de Moisés. Ouviram que você os instrui a não circuncidarem os filhos nem seguirem os costumes judaicos.

[[v44-21-22]]

^<<v44-21-22,22>>^ Que faremos? Certamente eles saberão que você chegou.

[[v44-21-23]]

^<<v44-21-23,23>>^ "Queremos que você faça o seguinte. Temos aqui quatro homens que cumpriram um voto.

[[v44-21-24]]

^<<v44-21-24,24>>^ Vá com eles ao templo e participe da cerimônia de purificação. Pague as despesas para realizarem o ritual de raspar a cabeça. Então todos saberão que os rumores são falsos e que você mesmo cumpre as leis judaicas.

[[v44-21-25]]

^<<v44-21-25,25>>^ "Quanto aos convertidos gentios, devem fazer aquilo que pedimos por carta: abster-se de comer alimentos oferecidos a ídolos, de consumir o sangue ou a carne de animais estrangulados e de praticar a imoralidade sexual".

[[v44-21-26]]

^<<v44-21-26,26>>^ No dia seguinte, Paulo se purificou junto com aqueles homens e entrou no templo. Declarou quando terminariam os dias da purificação e quando seria oferecido o sacrifício em favor deles.

[[v44-21-27]]

^<<v44-21-27,27>>^ Estando os sete dias quase no fim, alguns judeus da província da Ásia viram Paulo no templo e incitaram a multidão contra ele. Agarraram-no,

[[v44-21-28]]

^<<v44-21-28,28>>^ gritando: "Homens de Israel, ajudem-nos! Este é o homem que fala contra nosso povo em toda parte e ensina todos a desobedecerem às leis judaicas. Fala contra o templo e até profana este santo lugar, trazendo gentios para dentro dele".

[[v44-21-29]]

^<<v44-21-29,29>>^ Antes tinham visto Paulo na cidade com Trófimo, um gentio de Éfeso, e concluíram que Paulo o havia levado para dentro do templo.

[[v44-21-30]]

^<<v44-21-30,30>>^ Toda a cidade se agitou com essas acusações, e houve grande tumulto. A multidão agarrou Paulo e o arrastou para fora do templo, e imediatamente foram fechadas as portas.

[[v44-21-31]]

^<<v44-21-31,31>>^ Quando procuravam matar Paulo, chegou ao comandante do regimento romano a notícia de que toda a Jerusalém estava em rebuliço.

[[v44-21-32]]

^<<v44-21-32,32>>^ No mesmo instante, ele chamou seus soldados e oficiais e correu para o meio da multidão. Quando viram o comandante e os soldados se aproximarem, pararam de espancar Paulo.

[[v44-21-33]]

^<<v44-21-33,33>>^ Então o comandante o prendeu e mandou que o amarrassem com duas correntes. Em seguida, perguntou à multidão quem era ele e o que havia feito.

[[v44-21-34]]

^<<v44-21-34,34>>^ Uns gritavam uma coisa, outros gritavam outra. Não conseguindo descobrir a verdade no meio de todo o tumulto, ordenou que Paulo fosse levado à fortaleza.

[[v44-21-35]]

^<<v44-21-35,35>>^ Quando Paulo chegou às escadas, o povo se tornou tão violento que os soldados tiveram de levantá-lo nos ombros para protegê-lo.

[[v44-21-36]]

^<<v44-21-36,36>>^ E a multidão foi atrás, gritando: "Matem-no! Matem-no!".

[[v44-21-37]]

^<<v44-21-37,37>>^ Quando Paulo estava para ser levado à fortaleza, disse ao comandante: "Posso ter uma palavra com o senhor?". Surpreso, o comandante perguntou: "Você fala grego?

[[v44-21-38]]

^<<v44-21-38,38>>^ Não é você o egípcio que liderou uma rebelião algum tempo atrás e levou consigo ao deserto quatro mil assassinos?".

[[v44-21-39]]

^<<v44-21-39,39>>^ "Não", respondeu Paulo. "Sou judeu e cidadão de Tarso, cidade importante da Cilícia. Por favor, permita-me falar a esta gente."

[[v44-21-40]]

^<<v44-21-40,40>>^ O comandante concordou, de modo que Paulo ficou em pé na escadaria e fez sinal para o povo se calar. Logo, um silêncio profundo envolveu a multidão, e ele lhes falou em aramaico, o idioma deles.

'''

xref:044-atos/044-atos-020.adoc#v44-20-0[&#60; Capítulo Anterior] | <<v44-21-0,Topo>> | xref:044-atos/044-atos-022.adoc#v44-22-0[Próximo Capítulo &#62;]