include::./index.adoc[]

[[v44-2-0]]
=== Atos, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v44-2-1]]

^<<v44-2-1,1>>^ No dia de Pentecostes, todos estavam reunidos num só lugar.

[[v44-2-2]]

^<<v44-2-2,2>>^ De repente, veio do céu um som como o de um poderoso vendaval e encheu a casa onde estavam sentados.

[[v44-2-3]]

^<<v44-2-3,3>>^ Então surgiu algo semelhante a chamas ou línguas de fogo que pousaram sobre cada um deles.

[[v44-2-4]]

^<<v44-2-4,4>>^ Todos ficaram cheios do Espírito Santo e começaram a falar em outras línguas, conforme o Espírito os habilitava.

[[v44-2-5]]

^<<v44-2-5,5>>^ Naquela época, judeus devotos de todas as nações viviam em Jerusalém.

[[v44-2-6]]

^<<v44-2-6,6>>^ Quando ouviram o som das vozes, vieram correndo e ficaram espantados, pois cada um deles ouvia em seu próprio idioma.

[[v44-2-7]]

^<<v44-2-7,7>>^ Muito admirados, exclamavam: "Como isto é possível? Estes homens são todos galileus

[[v44-2-8]]

^<<v44-2-8,8>>^ e, no entanto, cada um de nós os ouve falar em nosso próprio idioma!

[[v44-2-9]]

^<<v44-2-9,9>>^ Estão aqui partos, medos, elamitas, habitantes da Mesopotâmia, da Judeia, da Capadócia, do Ponto, da província da Ásia,

[[v44-2-10]]

^<<v44-2-10,10>>^ da Frígia, da Panfília, do Egito e de regiões da Líbia próximas a Cirene, visitantes de Roma

[[v44-2-11]]

^<<v44-2-11,11>>^ (tanto judeus como convertidos ao judaísmo), cretenses e árabes, e todos nós ouvimos estas pessoas falarem em nossa própria língua sobre as coisas maravilhosas que Deus fez!".

[[v44-2-12]]

^<<v44-2-12,12>>^ Admirados e perplexos, perguntavam uns aos outros: "Que significa isto?".

[[v44-2-13]]

^<<v44-2-13,13>>^ Outros, porém, zombavam e diziam: "Eles estão bêbados!".

[[v44-2-14]]

^<<v44-2-14,14>>^ Então Pedro deu um passo à frente com os onze apóstolos e dirigiu-se em alta voz à multidão: "Ouçam com atenção, todos vocês, povo da Judeia e habitantes de Jerusalém! Escutem o que lhes digo!

[[v44-2-15]]

^<<v44-2-15,15>>^ Estas pessoas não estão bêbadas, como alguns de vocês pensam, pois são apenas nove horas da manhã.

[[v44-2-16]]

^<<v44-2-16,16>>^ Pelo contrário! O que vocês estão vendo foi predito há tempos pelo profeta Joel:

[[v44-2-17]]

^<<v44-2-17,17>>^ ‘Nos últimos dias’, disse Deus, ‘derramarei meu Espírito sobre todo tipo de pessoa. Seus filhos e suas filhas profetizarão; os jovens terão visões, e os velhos terão sonhos.

[[v44-2-18]]

^<<v44-2-18,18>>^ Naqueles dias, derramarei meu Espírito até mesmo sobre servos e servas, e eles profetizarão.

[[v44-2-19]]

^<<v44-2-19,19>>^ Farei maravilhas em cima, no céu, e sinais embaixo, na terra: sangue e fogo, e nuvens de fumaça.

[[v44-2-20]]

^<<v44-2-20,20>>^ O sol se escurecerá, e a lua se tornará vermelha como sangue, antes que chegue o grande e glorioso dia do Senhor.

[[v44-2-21]]

^<<v44-2-21,21>>^ Mas todo aquele que invocar o nome do Senhor será salvo’.

[[v44-2-22]]

^<<v44-2-22,22>>^ "Povo de Israel, escute! Deus aprovou publicamente Jesus, o nazareno, ao realizar milagres, maravilhas e sinais por meio dele, como vocês bem sabem.

[[v44-2-23]]

^<<v44-2-23,23>>^ Ele foi entregue conforme o plano preestabelecido por Deus e seu conhecimento prévio daquilo que aconteceria. Com a ajuda de gentios que desconheciam a lei, vocês o pregaram na cruz e o mataram.

[[v44-2-24]]

^<<v44-2-24,24>>^ Mas Deus o ressuscitou, libertando-o dos horrores da morte, pois ela não pôde mantê-lo sob seu domínio.

[[v44-2-25]]

^<<v44-2-25,25>>^ A respeito dele disse o rei Davi: ‘Vejo que o Senhor está sempre comigo; não serei abalado, pois ele está à minha direita.

[[v44-2-26]]

^<<v44-2-26,26>>^ Não é de admirar que meu coração esteja alegre e que minha língua o louve; meu corpo repousa em esperança.

[[v44-2-27]]

^<<v44-2-27,27>>^ Pois tu não deixarás minha alma entre os mortos, nem permitirás que o teu Santo apodreça no túmulo.

[[v44-2-28]]

^<<v44-2-28,28>>^ Tu me mostraste o caminho da vida, e me encherás com a alegria de tua presença’.

[[v44-2-29]]

^<<v44-2-29,29>>^ "Irmãos, permitam-me dizer com toda convicção que o patriarca Davi não estava se referindo a si mesmo, pois ele morreu e foi sepultado, e seu túmulo ainda está aqui, entre nós.

[[v44-2-30]]

^<<v44-2-30,30>>^ Mas ele era profeta e sabia que Deus havia prometido sob juramento que um de seus descendentes se sentaria em seu trono.

[[v44-2-31]]

^<<v44-2-31,31>>^ Davi estava olhando para o futuro e falando da ressurreição do Cristo, que não foi deixado entre os mortos nem seu corpo apodreceu no túmulo.

[[v44-2-32]]

^<<v44-2-32,32>>^ "Foi esse Jesus que Deus ressuscitou, e todos nós somos testemunhas disso.

[[v44-2-33]]

^<<v44-2-33,33>>^ Ele foi exaltado ao lugar de honra, à direita de Deus. E, conforme havia prometido, o Pai lhe deu o Espírito Santo, que ele derramou sobre nós, como vocês estão vendo e ouvindo hoje.

[[v44-2-34]]

^<<v44-2-34,34>>^ Pois Davi não subiu ao céu e, no entanto, disse: ‘O Senhor disse ao meu Senhor: Sente-se no lugar de honra à minha direita,

[[v44-2-35]]

^<<v44-2-35,35>>^ até que eu humilhe seus inimigos e os ponha debaixo de seus pés’.

[[v44-2-36]]

^<<v44-2-36,36>>^ "Portanto, saibam com certeza todos em Israel que a esse Jesus, que vocês crucificaram, Deus fez Senhor e Cristo!".

[[v44-2-37]]

^<<v44-2-37,37>>^ As palavras partiram o coração dos que ouviam, e eles perguntaram a Pedro e aos outros apóstolos: "Irmãos, o que devemos fazer?".

[[v44-2-38]]

^<<v44-2-38,38>>^ Pedro respondeu: "Vocês devem se arrepender, para o perdão de seus pecados, e cada um deve ser batizado em nome de Jesus Cristo. Então receberão a dádiva do Espírito Santo.

[[v44-2-39]]

^<<v44-2-39,39>>^ Essa promessa é para vocês, para seus filhos e para os que estão longe, isto é, para todos que forem chamados pelo Senhor, nosso Deus".

[[v44-2-40]]

^<<v44-2-40,40>>^ Pedro continuou a pregar, advertindo com insistência a seus ouvintes: "Salvem-se desta geração corrompida!".

[[v44-2-41]]

^<<v44-2-41,41>>^ Os que acreditaram nas palavras de Pedro foram batizados, e naquele dia houve um acréscimo de cerca de três mil pessoas.

[[v44-2-42]]

^<<v44-2-42,42>>^ Todos se dedicavam de coração ao ensino dos apóstolos, à comunhão, ao partir do pão e à oração.

[[v44-2-43]]

^<<v44-2-43,43>>^ Havia em todos eles um profundo temor, e os apóstolos realizavam muitos sinais e maravilhas.

[[v44-2-44]]

^<<v44-2-44,44>>^ Os que criam se reuniam num só lugar e compartilhavam tudo que possuíam.

[[v44-2-45]]

^<<v44-2-45,45>>^ Vendiam propriedades e bens e repartiam o dinheiro com os necessitados,

[[v44-2-46]]

^<<v44-2-46,46>>^ adoravam juntos no templo diariamente, reuniam-se nos lares para comer e partiam o pão com grande alegria e generosidade,

[[v44-2-47]]

^<<v44-2-47,47>>^ sempre louvando a Deus e desfrutando a simpatia de todo o povo. E, a cada dia, o Senhor lhes acrescentava aqueles que iam sendo salvos.

'''

xref:044-atos/044-atos-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:044-atos/044-atos-003.adoc#v44-3-0[Próximo Capítulo &#62;]