include::./index.adoc[]

[[v44-26-0]]
=== Atos, 26
// nvt ?, NVT - Nova Versão Transformadora

[[v44-26-1]]

^<<v44-26-1,1>>^ Então Agripa disse a Paulo: "Você pode falar em sua defesa". Paulo fez um sinal com a mão e começou sua defesa:

[[v44-26-2]]

^<<v44-26-2,2>>^ "Rei Agripa, considero-me feliz de ter hoje a oportunidade de lhe apresentar minha defesa contra todas as acusações feitas pelos líderes judeus,

[[v44-26-3]]

^<<v44-26-3,3>>^ pois sei que conhece bem todos os costumes e controvérsias dos judeus. Portanto, peço que me ouça com paciência.

[[v44-26-4]]

^<<v44-26-4,4>>^ "Como os líderes judeus sabem muito bem, recebi educação judaica completa desde a infância entre meu povo e depois em Jerusalém.

[[v44-26-5]]

^<<v44-26-5,5>>^ Também sabem, e talvez estejam dispostos a confirmar, que vivi como fariseu, a seita mais rígida de nossa religião.

[[v44-26-6]]

^<<v44-26-6,6>>^ Agora estou sendo julgado por causa de minha esperança no cumprimento da promessa feita por Deus a nossos antepassados.

[[v44-26-7]]

^<<v44-26-7,7>>^ De fato, é por isso que as doze tribos de Israel adoram a Deus fervorosamente, dia e noite, e compartilham da mesma esperança que eu. E, no entanto, ó rei, acusam-me por causa dessa esperança!

[[v44-26-8]]

^<<v44-26-8,8>>^ Por que lhes parece tão incrível que Deus ressuscite os mortos?

[[v44-26-9]]

^<<v44-26-9,9>>^ "Eu costumava pensar que era minha obrigação empenhar-me em me opor ao nome de Jesus, o nazareno.

[[v44-26-10]]

^<<v44-26-10,10>>^ Foi exatamente o que fiz em Jerusalém. Com autorização dos principais sacerdotes, fui responsável pela prisão de muitos dentre o povo santo. E eu votava contra eles quando eram condenados à morte.

[[v44-26-11]]

^<<v44-26-11,11>>^ Muitas vezes providenciei que fossem castigados nas sinagogas, a fim de obrigá-los a blasfemar. Eu me opunha a eles com tanta violência que os perseguia até em cidades estrangeiras.

[[v44-26-12]]

^<<v44-26-12,12>>^ "Certo dia, numa dessas missões, dirigia-me a Damasco, autorizado e incumbido pelos principais sacerdotes.

[[v44-26-13]]

^<<v44-26-13,13>>^ Por volta do meio-dia, ó rei, ainda a caminho, uma luz do céu, mais intensa que o sol, brilhou sobre mim e meus companheiros.

[[v44-26-14]]

^<<v44-26-14,14>>^ Todos nós caímos no chão, e eu ouvi uma voz que me dizia em aramaico: ‘Saulo, Saulo, por que você me persegue? Não adianta lutar contra minha vontade’.

[[v44-26-15]]

^<<v44-26-15,15>>^ "‘Quem és tu, Senhor?’, perguntei. "E o Senhor respondeu: ‘Sou Jesus, a quem você persegue.

[[v44-26-16]]

^<<v44-26-16,16>>^ Agora levante-se, pois eu apareci para nomeá-lo meu servo e minha testemunha. Conte o que viu e o que eu lhe mostrarei no futuro.

[[v44-26-17]]

^<<v44-26-17,17>>^ E eu o livrarei tanto de seu povo como dos gentios. Sim, eu o envio aos gentios

[[v44-26-18]]

^<<v44-26-18,18>>^ para abrir os olhos deles a fim de que se voltem das trevas para a luz, e do poder de Satanás para Deus. Então receberão o perdão dos pecados e a herança entre o povo de Deus, separado pela fé em mim’.

[[v44-26-19]]

^<<v44-26-19,19>>^ "Portanto, rei Agripa, obedeci à visão celestial.

[[v44-26-20]]

^<<v44-26-20,20>>^ Anunciei a mensagem primeiro em Damasco, depois em Jerusalém e em toda a Judeia, e também aos gentios, dizendo que todos devem arrepender-se, voltar-se para Deus e mostrar, por meio de suas boas obras, que mudaram de rumo.

[[v44-26-21]]

^<<v44-26-21,21>>^ Alguns judeus me prenderam no templo por anunciar essa mensagem e tentaram me matar.

[[v44-26-22]]

^<<v44-26-22,22>>^ Mas Deus tem me protegido até este momento, para que eu dê testemunho a todos, dos mais simples até os mais importantes. Não ensino nada além daquilo que os profetas e Moisés disseram que haveria de acontecer,

[[v44-26-23]]

^<<v44-26-23,23>>^ que o Cristo sofreria e seria o primeiro a ressuscitar dos mortos e, desse modo, anunciaria a luz de Deus tanto aos judeus como aos gentios".

[[v44-26-24]]

^<<v44-26-24,24>>^ De repente, Festo gritou: "Paulo, você está louco! O excesso de estudo o fez perder o juízo!".

[[v44-26-25]]

^<<v44-26-25,25>>^ Mas Paulo respondeu: "Não estou louco, excelentíssimo Festo. Digo a mais sensata verdade,

[[v44-26-26]]

^<<v44-26-26,26>>^ e o rei Agripa sabe dessas coisas. Expresso-me com ousadia porque tenho certeza de que esses acontecimentos são todos de conhecimento dele, pois não se passaram em algum canto escondido.

[[v44-26-27]]

^<<v44-26-27,27>>^ Rei Agripa, o senhor crê nos profetas? Eu sei que sim".

[[v44-26-28]]

^<<v44-26-28,28>>^ Então Agripa o interrompeu: "Você acredita que pode me convencer a tornar-me cristão em tão pouco tempo?".

[[v44-26-29]]

^<<v44-26-29,29>>^ Paulo respondeu: "Em pouco ou em muito tempo, peço a Deus que tanto o senhor como os demais aqui presentes se tornem como eu, exceto por estas correntes".

[[v44-26-30]]

^<<v44-26-30,30>>^ Então o rei, o governador, Berenice e todos os outros se levantaram e se retiraram.

[[v44-26-31]]

^<<v44-26-31,31>>^ Enquanto saíam, conversavam entre si e concordaram: "Esse homem não fez nada que mereça morte ou prisão".

[[v44-26-32]]

^<<v44-26-32,32>>^ E Agripa disse a Festo: "Ele poderia ser posto em liberdade se não tivesse apelado a César".

'''

xref:044-atos/044-atos-025.adoc#v44-25-0[&#60; Capítulo Anterior] | <<v44-26-0,Topo>> | xref:044-atos/044-atos-027.adoc#v44-27-0[Próximo Capítulo &#62;]