include::./index.adoc[]

[[v44-9-0]]
=== Atos, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v44-9-1]]

^<<v44-9-1,1>>^ Enquanto isso, Saulo, motivado pela ânsia de matar os discípulos do Senhor, procurou o sumo sacerdote.

[[v44-9-2]]

^<<v44-9-2,2>>^ Pediu cartas para as sinagogas em Damasco, solicitando que cooperassem com a prisão de todos os seguidores do Caminho, homens e mulheres, que ali encontrasse, para levá-los como prisioneiros a Jerusalém.

[[v44-9-3]]

^<<v44-9-3,3>>^ Quando se aproximava de Damasco, de repente uma luz do céu brilhou ao seu redor.

[[v44-9-4]]

^<<v44-9-4,4>>^ Ele caiu no chão e ouviu uma voz lhe dizer: "Saulo, Saulo, por que você me persegue?".

[[v44-9-5]]

^<<v44-9-5,5>>^ "Quem és tu, Senhor?", perguntou Saulo. E a voz respondeu: "Sou Jesus, a quem você persegue!

[[v44-9-6]]

^<<v44-9-6,6>>^ Agora levante-se e entre na cidade, onde lhe dirão o que fazer".

[[v44-9-7]]

^<<v44-9-7,7>>^ Os homens que estavam com Saulo ficaram calados de espanto, pois ouviam uma voz, mas não viam ninguém.

[[v44-9-8]]

^<<v44-9-8,8>>^ Saulo levantou-se do chão, mas, ao abrir os olhos, estava cego. Então o conduziram pela mão até Damasco.

[[v44-9-9]]

^<<v44-9-9,9>>^ Lá ele permaneceu, cego, por três dias, e não comeu nem bebeu coisa alguma.

[[v44-9-10]]

^<<v44-9-10,10>>^ Havia em Damasco um discípulo chamado Ananias. O Senhor o chamou numa visão: "Ananias!". "Sim, Senhor!", respondeu ele.

[[v44-9-11]]

^<<v44-9-11,11>>^ O Senhor disse: "Vá à rua Direita, à casa de Judas. Ao chegar, pergunte por um homem de Tarso chamado Saulo. Ele está orando neste momento.

[[v44-9-12]]

^<<v44-9-12,12>>^ Mostrei-lhe numa visão um homem chamado Ananias chegando e impondo as mãos sobre ele para que voltasse a enxergar".

[[v44-9-13]]

^<<v44-9-13,13>>^ Ananias, porém, respondeu: "Senhor, ouvi muita gente falar das coisas horríveis que esse homem vem fazendo ao teu povo santo em Jerusalém.

[[v44-9-14]]

^<<v44-9-14,14>>^ E ele tem autorização dos principais sacerdotes para prender todos que invocam o teu nome!".

[[v44-9-15]]

^<<v44-9-15,15>>^ O Senhor, no entanto, disse: "Vá, pois Saulo é o instrumento que escolhi para levar minha mensagem aos gentios e aos reis, bem como ao povo de Israel.

[[v44-9-16]]

^<<v44-9-16,16>>^ E eu mostrarei a ele quanto deve sofrer por meu nome".

[[v44-9-17]]

^<<v44-9-17,17>>^ Ananias foi e encontrou Saulo. Ao impor as mãos sobre ele, disse: "Irmão Saulo, o Senhor Jesus, que lhe apareceu no caminho para cá, me enviou para que você volte a enxergar e fique cheio do Espírito Santo".

[[v44-9-18]]

^<<v44-9-18,18>>^ No mesmo instante, algo semelhante a escamas caiu dos olhos de Saulo, e sua visão foi restaurada. Então ele se levantou, foi batizado

[[v44-9-19]]

^<<v44-9-19,19>>^ e, depois de comer, recuperou as forças. Saulo permaneceu alguns dias em Damasco, com os discípulos.

[[v44-9-20]]

^<<v44-9-20,20>>^ Logo, começou a falar de Jesus nas sinagogas, dizendo: "Ele é o Filho de Deus!".

[[v44-9-21]]

^<<v44-9-21,21>>^ Todos que o ouviam ficavam admirados. "Não é esse o homem que causou tanta destruição entre os que invocavam o nome de Jesus em Jerusalém?", perguntavam. "E não veio aqui para levá-los como prisioneiros aos principais sacerdotes?"

[[v44-9-22]]

^<<v44-9-22,22>>^ A pregação de Saulo tornou-se cada vez mais poderosa, pois ele deixava os judeus de Damasco perplexos, provando que Jesus é o Cristo.

[[v44-9-23]]

^<<v44-9-23,23>>^ Depois de certo tempo, alguns judeus conspiraram para matá-lo.

[[v44-9-24]]

^<<v44-9-24,24>>^ Dia e noite, vigiavam a porta da cidade com a intenção de assassiná-lo, mas ele foi informado desse plano.

[[v44-9-25]]

^<<v44-9-25,25>>^ Então, durante a noite, alguns de seus discípulos o baixaram pela muralha da cidade num grande cesto.

[[v44-9-26]]

^<<v44-9-26,26>>^ Quando Saulo chegou a Jerusalém, tentou se encontrar com os discípulos, mas todos estavam com medo dele, pois não acreditavam que ele tivesse de fato se tornado discípulo.

[[v44-9-27]]

^<<v44-9-27,27>>^ Então Barnabé o levou aos apóstolos e lhes contou como Saulo tinha visto o Senhor no caminho para Damasco e como ele lhe havia falado. Contou também que, em Damasco, Saulo havia pregado corajosamente em nome de Jesus.

[[v44-9-28]]

^<<v44-9-28,28>>^ Saulo permaneceu com os apóstolos e andava com eles por Jerusalém, pregando corajosamente em nome do Senhor.

[[v44-9-29]]

^<<v44-9-29,29>>^ Também conversava e discutia com alguns judeus de fala grega, mas estes procuravam matá-lo.

[[v44-9-30]]

^<<v44-9-30,30>>^ Quando os irmãos souberam disso, levaram Saulo a Cesareia e de lá o enviaram a Tarso.

[[v44-9-31]]

^<<v44-9-31,31>>^ A igreja tinha paz em toda a Judeia, Galileia e Samaria e ia se fortalecendo à medida que andava no temor do Senhor. E, encorajada pelo Espírito Santo, crescia em número.

[[v44-9-32]]

^<<v44-9-32,32>>^ Pedro viajava por toda parte, e foi visitar o povo santo que vivia na cidade de Lida.

[[v44-9-33]]

^<<v44-9-33,33>>^ Ali encontrou um paralítico chamado Eneias, que permanecia de cama havia oito anos.

[[v44-9-34]]

^<<v44-9-34,34>>^ Pedro lhe disse: "Eneias, Jesus Cristo cura você! Levante-se e arrume sua maca!". E, no mesmo instante, ele se levantou.

[[v44-9-35]]

^<<v44-9-35,35>>^ Todos os moradores de Lida e de Sarona viram Eneias e se converteram ao Senhor.

[[v44-9-36]]

^<<v44-9-36,36>>^ Havia em Jope uma discípula chamada Tabita (que em grego é Dorcas). Sempre fazia o bem às pessoas e ajudava os pobres.

[[v44-9-37]]

^<<v44-9-37,37>>^ Por esse tempo, ficou doente e morreu. Seu corpo foi lavado para o sepultamento e colocado numa sala no andar superior.

[[v44-9-38]]

^<<v44-9-38,38>>^ Quando os discípulos souberam que Pedro estava perto de Lida, enviaram dois homens para lhe suplicar: "Por favor, venha o mais rápido possível!".

[[v44-9-39]]

^<<v44-9-39,39>>^ Então Pedro voltou com eles e, assim que chegou, foi levado para a sala do andar superior. O cômodo estava cheio de viúvas que choravam e lhe mostravam os vestidos e outras roupas que Dorcas havia feito para elas.

[[v44-9-40]]

^<<v44-9-40,40>>^ Pedro pediu que todos saíssem do quarto. Então, ajoelhou-se e orou. Voltando-se para o corpo da mulher, disse: "Tabita, levante-se", e ela abriu os olhos. Quando ela viu Pedro, sentou-se.

[[v44-9-41]]

^<<v44-9-41,41>>^ Ele lhe deu a mão e a ajudou a levantar-se. Em seguida, chamou os discípulos e as viúvas e a apresentou viva.

[[v44-9-42]]

^<<v44-9-42,42>>^ A notícia se espalhou por toda a cidade, e muitos creram no Senhor.

[[v44-9-43]]

^<<v44-9-43,43>>^ Pedro ficou em Jope algum tempo, hospedado na casa de Simão, um homem que trabalhava com couro.

'''

xref:044-atos/044-atos-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-atos/044-atos-010.adoc#v44-10-0[Próximo Capítulo &#62;]