include::./index.adoc[]

[[v44-4-0]]
=== Atos, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v44-4-1]]

^<<v44-4-1,1>>^ Enquanto falavam ao povo, Pedro e João foram confrontados pelos sacerdotes, pelo capitão da guarda do templo e por alguns saduceus.

[[v44-4-2]]

^<<v44-4-2,2>>^ Os líderes estavam muito perturbados porque Pedro e João ensinavam ao povo que em Jesus há ressurreição dos mortos.

[[v44-4-3]]

^<<v44-4-3,3>>^ Eles os prenderam e, como já anoitecia, os colocaram na prisão até a manhã seguinte.

[[v44-4-4]]

^<<v44-4-4,4>>^ Muitos que tinham ouvido a mensagem creram, totalizando, agora, cerca de cinco mil homens.

[[v44-4-5]]

^<<v44-4-5,5>>^ No dia seguinte, o conselho das autoridades, dos líderes do povo e dos mestres da lei se reuniu em Jerusalém.

[[v44-4-6]]

^<<v44-4-6,6>>^ Estavam ali Anás, o sumo sacerdote, e também Caifás, João, Alexandre e outros parentes do sumo sacerdote.

[[v44-4-7]]

^<<v44-4-7,7>>^ Mandaram trazer Pedro e João e os interrogaram: "Com que poder, ou em nome de quem, vocês fizeram isso?".

[[v44-4-8]]

^<<v44-4-8,8>>^ Cheio do Espírito Santo, Pedro lhes respondeu: "Autoridades e líderes do povo,

[[v44-4-9]]

^<<v44-4-9,9>>^ estamos sendo interrogados hoje porque realizamos uma boa ação em favor de um aleijado, e os senhores querem saber como ele foi curado.

[[v44-4-10]]

^<<v44-4-10,10>>^ Saibam os senhores e todo o povo de Israel que ele foi curado pelo nome de Jesus Cristo, o nazareno, a quem os senhores crucificaram, mas a quem Deus ressuscitou dos mortos.

[[v44-4-11]]

^<<v44-4-11,11>>^ Pois é a respeito desse Jesus que se diz: ‘A pedra que vocês, os construtores, rejeitaram se tornou a pedra angular’.

[[v44-4-12]]

^<<v44-4-12,12>>^ Não há salvação em nenhum outro! Não há nenhum outro nome debaixo do céu, em toda a humanidade, por meio do qual devamos ser salvos".

[[v44-4-13]]

^<<v44-4-13,13>>^ Quando os membros do conselho viram a coragem de Pedro e João, ficaram admirados, pois perceberam que eram homens comuns, sem instrução religiosa formal. Reconheceram também que eles haviam estado com Jesus.

[[v44-4-14]]

^<<v44-4-14,14>>^ Mas não havia nada que pudessem fazer, pois o homem que tinha sido curado estava ali diante deles.

[[v44-4-15]]

^<<v44-4-15,15>>^ Assim, ordenaram que Pedro e João fossem retirados da sala do conselho e começaram a discutir entre si.

[[v44-4-16]]

^<<v44-4-16,16>>^ "Que faremos com esses homens?", perguntavam uns aos outros. "Não podemos negar que realizaram um sinal, como todos em Jerusalém sabem.

[[v44-4-17]]

^<<v44-4-17,17>>^ Mas, para evitar que espalhem sua mensagem, devemos adverti-los de que não falem nesse nome a mais ninguém."

[[v44-4-18]]

^<<v44-4-18,18>>^ Então os chamaram de volta e ordenaram que nunca mais falassem nem ensinassem em nome de Jesus.

[[v44-4-19]]

^<<v44-4-19,19>>^ Pedro e João, porém, responderam: "Os senhores acreditam que Deus quer que obedeçamos a vocês, e não a ele?

[[v44-4-20]]

^<<v44-4-20,20>>^ Não podemos deixar de falar do que vimos e ouvimos!".

[[v44-4-21]]

^<<v44-4-21,21>>^ Os membros do conselho fizeram novas ameaças, mas, por fim, os soltaram. Não sabiam como castigá-los sem provocar um tumulto, visto que todos louvavam a Deus pelo ocorrido,

[[v44-4-22]]

^<<v44-4-22,22>>^ pois o aleijado que havia sido curado milagrosamente tinha mais de quarenta anos de idade.

[[v44-4-23]]

^<<v44-4-23,23>>^ Assim que foram libertos, Pedro e João voltaram ao lugar onde estavam os outros irmãos e lhes contaram o que os principais sacerdotes e líderes tinham dito.

[[v44-4-24]]

^<<v44-4-24,24>>^ Ao ouvir o relato, todos os presentes levantaram juntos a voz e oraram a Deus: "Ó Soberano Senhor, Criador dos céus e da terra, do mar e de tudo que neles há,

[[v44-4-25]]

^<<v44-4-25,25>>^ falaste muito tempo atrás pelo Espírito Santo, nas palavras de nosso antepassado Davi, teu servo: ‘Por que as nações se enfureceram tanto? Por que perderam tempo com planos inúteis?

[[v44-4-26]]

^<<v44-4-26,26>>^ Os reis da terra se prepararam para guerrear; os governantes se uniram contra o Senhor e contra seu Cristo’.

[[v44-4-27]]

^<<v44-4-27,27>>^ "De fato, isso aconteceu aqui, nesta cidade, pois Herodes Antipas, o governador Pôncio Pilatos, os gentios e o povo de Israel se uniram contra Jesus, teu santo Servo, a quem ungiste.

[[v44-4-28]]

^<<v44-4-28,28>>^ Tudo que fizeram, porém, havia sido decidido de antemão pela tua vontade.

[[v44-4-29]]

^<<v44-4-29,29>>^ E agora, Senhor, ouve as ameaças deles e concede a teus servos coragem para anunciar tua palavra.

[[v44-4-30]]

^<<v44-4-30,30>>^ Estende tua mão com poder para curar, e que sinais e maravilhas sejam realizados por meio do nome de teu santo Servo Jesus".

[[v44-4-31]]

^<<v44-4-31,31>>^ Depois dessa oração, o lugar onde estavam reunidos tremeu, e todos ficaram cheios do Espírito Santo e pregavam corajosamente a palavra de Deus.

[[v44-4-32]]

^<<v44-4-32,32>>^ Todos os que creram estavam unidos em coração e mente. Não se consideravam donos de seus bens, de modo que compartilhavam tudo que tinham.

[[v44-4-33]]

^<<v44-4-33,33>>^ Com grande poder, os apóstolos davam testemunho da ressurreição do Senhor Jesus, e sobre todos eles havia grande graça.

[[v44-4-34]]

^<<v44-4-34,34>>^ Entre eles não havia necessitados, pois quem possuía terras ou casas vendia o que era seu

[[v44-4-35]]

^<<v44-4-35,35>>^ e levava o dinheiro aos apóstolos, para que dessem aos que precisavam de ajuda.

[[v44-4-36]]

^<<v44-4-36,36>>^ José, a quem os apóstolos deram o nome Barnabé, que significa "Filho do encorajamento", era da tribo de Levi e tinha nascido na ilha de Chipre.

[[v44-4-37]]

^<<v44-4-37,37>>^ Ele vendeu um campo que possuía e entregou o dinheiro aos apóstolos.

'''

xref:044-atos/044-atos-003.adoc#v44-3-0[&#60; Capítulo Anterior] | <<v44-4-0,Topo>> | xref:044-atos/044-atos-005.adoc#v44-5-0[Próximo Capítulo &#62;]