include::./index.adoc[]

[[v44-12-0]]
=== Atos, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v44-12-1]]

^<<v44-12-1,1>>^ Por essa época, o rei Herodes Agripa começou a perseguir violentamente algumas pessoas da igreja.

[[v44-12-2]]

^<<v44-12-2,2>>^ Mandou matar à espada Tiago, irmão de João.

[[v44-12-3]]

^<<v44-12-3,3>>^ Quando Herodes viu quanto isso agradava os judeus, também prendeu Pedro durante a celebração da Festa dos Pães sem Fermento.

[[v44-12-4]]

^<<v44-12-4,4>>^ Depois, lançou-o na cadeia, sob a guarda de quatro escoltas, cada uma com quatro soldados. A intenção de Herodes era apresentar Pedro aos judeus para julgamento público depois da Páscoa.

[[v44-12-5]]

^<<v44-12-5,5>>^ Enquanto Pedro estava no cárcere, a igreja orava fervorosamente a Deus por ele.

[[v44-12-6]]

^<<v44-12-6,6>>^ Na noite antes de Pedro ser levado a julgamento, ele dormia, preso com duas correntes entre dois soldados, e outros montavam guarda na porta da prisão.

[[v44-12-7]]

^<<v44-12-7,7>>^ De repente, uma luz intensa brilhou na cela, e um anjo do Senhor apareceu. Tocou no lado de Pedro para acordá-lo e disse: "Depressa! Levante-se!", e as correntes caíram dos pulsos de Pedro.

[[v44-12-8]]

^<<v44-12-8,8>>^ Então o anjo lhe disse: "Vista-se e calce as sandálias", e Pedro obedeceu. "Agora vista a capa e siga-me", ordenou o anjo.

[[v44-12-9]]

^<<v44-12-9,9>>^ Pedro deixou a cela, seguindo o anjo. O tempo todo, porém, pensava que era uma visão, sem entender que era real o que ocorria.

[[v44-12-10]]

^<<v44-12-10,10>>^ Passaram o primeiro e o segundo postos de guarda e, quando chegaram ao portão de ferro que dava para a cidade, o portão se abriu sozinho para eles. Os dois passaram e foram caminhando ao longo da rua até que, subitamente, o anjo o deixou.

[[v44-12-11]]

^<<v44-12-11,11>>^ Por fim, Pedro caiu em si. "É verdade mesmo!", disse ele. "O Senhor enviou seu anjo para me salvar daquilo que Herodes e os judeus planejavam me fazer!"

[[v44-12-12]]

^<<v44-12-12,12>>^ Quando Pedro se deu conta disso, foi à casa de Maria, mãe de João Marcos, onde muitos estavam reunidos para orar.

[[v44-12-13]]

^<<v44-12-13,13>>^ Ele bateu à porta da frente, e uma serva chamada Rode foi atender.

[[v44-12-14]]

^<<v44-12-14,14>>^ Ao reconhecer a voz de Pedro, ficou tão contente que, em vez de abrir a porta, correu de volta para dentro dizendo a todos: "Pedro está à porta!".

[[v44-12-15]]

^<<v44-12-15,15>>^ Eles, porém, disseram: "Você está fora de si!". Diante da insistência dela, concluíram: "Deve ser o anjo dele".

[[v44-12-16]]

^<<v44-12-16,16>>^ Enquanto isso, Pedro continuava a bater. Quando, por fim, abriram a porta e o viram, ficaram admirados.

[[v44-12-17]]

^<<v44-12-17,17>>^ Ele fez um sinal para se acalmarem e lhes contou como o Senhor o havia tirado da prisão. "Contem a Tiago e aos outros irmãos o que aconteceu", disse ele. Então foi para outro lugar.

[[v44-12-18]]

^<<v44-12-18,18>>^ Ao amanhecer, houve grande alvoroço entre os soldados a respeito do que tinha acontecido a Pedro.

[[v44-12-19]]

^<<v44-12-19,19>>^ Herodes ordenou que fosse feita uma busca completa por ele. Não conseguindo encontrá-lo, interrogou os guardas e mandou executá-los. Depois disso, Herodes partiu da Judeia e foi passar algum tempo em Cesareia.

[[v44-12-20]]

^<<v44-12-20,20>>^ O rei Herodes estava muito irado com o povo de Tiro e Sidom. Assim, as duas cidades se uniram na tentativa de se reconciliar com o rei, pois dependiam de suas terras para obter alimento. Então, tendo conquistado o apoio de Blasto, assistente pessoal do rei,

[[v44-12-21]]

^<<v44-12-21,21>>^ conseguiram uma audiência. No dia marcado, Herodes, vestindo seus trajes reais, sentou-se em seu trono e fez um discurso para eles.

[[v44-12-22]]

^<<v44-12-22,22>>^ O povo o ovacionava, gritando: "É a voz de um deus, e não de um homem!".

[[v44-12-23]]

^<<v44-12-23,23>>^ No mesmo instante, um anjo do Senhor feriu Herodes com uma enfermidade, pois ele não ofereceu a glória a Deus. Foi comido por vermes e morreu.

[[v44-12-24]]

^<<v44-12-24,24>>^ Enquanto isso, a palavra de Deus continuava a se espalhar, e havia muitos novos convertidos.

[[v44-12-25]]

^<<v44-12-25,25>>^ Quando Barnabé e Saulo terminaram sua missão em Jerusalém, voltaram levando consigo João Marcos.

'''

xref:044-atos/044-atos-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-atos/044-atos-013.adoc#v44-13-0[Próximo Capítulo &#62;]