include::./index.adoc[]

[[v44-11-0]]
=== Atos, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v44-11-1]]

^<<v44-11-1,1>>^ Logo chegou aos apóstolos e a outros irmãos da Judeia a notícia de que os gentios haviam recebido a palavra de Deus.

[[v44-11-2]]

^<<v44-11-2,2>>^ Mas, quando Pedro voltou a Jerusalém, os discípulos judeus o criticaram,

[[v44-11-3]]

^<<v44-11-3,3>>^ dizendo: "Você entrou na casa de gentios e até comeu com eles!".

[[v44-11-4]]

^<<v44-11-4,4>>^ Então Pedro lhes contou exatamente o que havia acontecido.

[[v44-11-5]]

^<<v44-11-5,5>>^ Disse: "Eu estava na cidade de Jope e, enquanto orava, num êxtase, tive uma visão. Algo semelhante a um lençol grande foi baixado do céu, preso pelas quatro pontas, vindo até onde eu estava.

[[v44-11-6]]

^<<v44-11-6,6>>^ Quando olhei dentro do lençol, vi toda espécie de animais domésticos e selvagens, répteis e aves.

[[v44-11-7]]

^<<v44-11-7,7>>^ E ouvi uma voz dizer: ‘Levante-se, Pedro; mate e coma’.

[[v44-11-8]]

^<<v44-11-8,8>>^ "Eu respondi: ‘De modo nenhum, Senhor! Jamais comi coisa alguma que fosse considerada impura ou imprópria’.

[[v44-11-9]]

^<<v44-11-9,9>>^ "Mas a voz do céu falou novamente: ‘Não chame de impuro o que Deus purificou’.

[[v44-11-10]]

^<<v44-11-10,10>>^ Isso aconteceu três vezes, antes que o lençol, com tudo que ele continha, fosse recolhido ao céu.

[[v44-11-11]]

^<<v44-11-11,11>>^ "Nesse momento, três homens que haviam sido enviados de Cesareia chegaram à casa onde eu estava hospedado.

[[v44-11-12]]

^<<v44-11-12,12>>^ O Espírito me disse que eu fosse com eles, sem nada questionar. Esses seis irmãos me acompanharam, e logo entramos na casa do homem que havia mandado nos buscar.

[[v44-11-13]]

^<<v44-11-13,13>>^ Ele nos contou como um anjo havia aparecido em sua casa e dito: ‘Envie mensageiros a Jope e mande buscar Simão, também chamado Pedro.

[[v44-11-14]]

^<<v44-11-14,14>>^ Ele lhe dirá como você e toda a sua casa podem ser salvos’.

[[v44-11-15]]

^<<v44-11-15,15>>^ "Quando comecei a falar, o Espírito Santo desceu sobre eles, como ocorreu conosco, no princípio.

[[v44-11-16]]

^<<v44-11-16,16>>^ Então me lembrei das palavras do Senhor, quando ele disse: ‘João batizou com água, mas vocês serão batizados com o Espírito Santo’.

[[v44-11-17]]

^<<v44-11-17,17>>^ E, uma vez que Deus deu a esses gentios a mesma dádiva que concedeu a nós quando cremos no Senhor Jesus Cristo, quem era eu para me opor a Deus?".

[[v44-11-18]]

^<<v44-11-18,18>>^ Ao ouvirem isso, pararam de levantar objeções e começaram a louvar a Deus, dizendo: "Vemos que Deus deu aos gentios o mesmo privilégio de se arrepender e receber a vida eterna!".

[[v44-11-19]]

^<<v44-11-19,19>>^ Enquanto isso, os discípulos que haviam sido dispersos na perseguição depois da morte de Estêvão chegaram até a Fenícia, Chipre e Antioquia da Síria. Pregaram a palavra, mas somente aos judeus.

[[v44-11-20]]

^<<v44-11-20,20>>^ Contudo, alguns dos discípulos que foram de Chipre e Cirene até Antioquia começaram a anunciar aos gentios as boas-novas a respeito do Senhor Jesus.

[[v44-11-21]]

^<<v44-11-21,21>>^ A mão do Senhor estava com eles, e muitos desses gentios creram e se converteram ao Senhor.

[[v44-11-22]]

^<<v44-11-22,22>>^ Quando a igreja de Jerusalém soube do que havia acontecido, enviou Barnabé a Antioquia.

[[v44-11-23]]

^<<v44-11-23,23>>^ Ao chegar ali e ver essa demonstração da graça de Deus, alegrou-se muito e incentivou os irmãos a permanecerem fiéis ao Senhor.

[[v44-11-24]]

^<<v44-11-24,24>>^ Barnabé era um homem bom, cheio do Espírito Santo e de fé. E uma grande multidão se converteu ao Senhor.

[[v44-11-25]]

^<<v44-11-25,25>>^ Então Barnabé foi a Tarso procurar Saulo.

[[v44-11-26]]

^<<v44-11-26,26>>^ Quando o encontrou, levou-o para Antioquia. Ali permaneceram com a igreja um ano inteiro, ensinando a muitas pessoas. Foi em Antioquia que os discípulos foram chamados de cristãos pela primeira vez.

[[v44-11-27]]

^<<v44-11-27,27>>^ Durante esse tempo, alguns profetas viajaram de Jerusalém a Antioquia.

[[v44-11-28]]

^<<v44-11-28,28>>^ Um deles, chamado Ágabo, pôs-se em pé numa das reuniões e predisse, pelo Espírito, que uma grande fome viria sobre todo o mundo romano. (Isso se cumpriu durante o reinado de Cláudio.)

[[v44-11-29]]

^<<v44-11-29,29>>^ Então os discípulos de Antioquia decidiram enviar uma ajuda aos irmãos na Judeia, cada um de acordo com suas possibilidades.

[[v44-11-30]]

^<<v44-11-30,30>>^ Foi o que fizeram, enviando as doações aos presbíteros por meio de Barnabé e Saulo.

'''

xref:044-atos/044-atos-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-atos/044-atos-012.adoc#v44-12-0[Próximo Capítulo &#62;]