include::./index.adoc[]

[[v44-6-0]]
=== Atos, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v44-6-1]]

^<<v44-6-1,1>>^ À medida que o número de discípulos crescia, surgiam murmúrios de descontentamento. Os judeus de fala grega se queixavam dos de fala hebraica, dizendo que suas viúvas estavam sendo negligenciadas na distribuição diária de alimento.

[[v44-6-2]]

^<<v44-6-2,2>>^ Por isso, os Doze convocaram uma reunião com todos os discípulos e disseram: "Nós, apóstolos, devemos nos dedicar ao ensino da palavra de Deus, e não à distribuição de alimentos.

[[v44-6-3]]

^<<v44-6-3,3>>^ Sendo assim, irmãos, escolham sete homens respeitados, cheios do Espírito e de sabedoria, e nós os encarregaremos desse serviço.

[[v44-6-4]]

^<<v44-6-4,4>>^ Então nós nos dedicaremos à oração e ao ensino da palavra".

[[v44-6-5]]

^<<v44-6-5,5>>^ A ideia agradou a todos, e escolheram Estêvão, homem cheio de fé e do Espírito Santo, e também Filipe, Prócoro, Nicanor, Timom, Pármenas e Nicolau de Antioquia, que antes havia se convertido ao judaísmo.

[[v44-6-6]]

^<<v44-6-6,6>>^ Esses sete foram apresentados aos apóstolos, que oraram por eles e lhes impuseram as mãos.

[[v44-6-7]]

^<<v44-6-7,7>>^ Assim, a mensagem de Deus continuou a se espalhar. O número de discípulos se multiplicava em Jerusalém, e muitos sacerdotes também se converteram.

[[v44-6-8]]

^<<v44-6-8,8>>^ Estêvão, homem cheio de graça e poder, realizava milagres e sinais entre o povo.

[[v44-6-9]]

^<<v44-6-9,9>>^ Um dia, porém, alguns homens da chamada Sinagoga dos Escravos Libertos começaram a discutir com ele. Eram judeus de Cirene, de Alexandria, da Cilícia e da província da Ásia.

[[v44-6-10]]

^<<v44-6-10,10>>^ Nenhum deles era capaz de resistir à sabedoria e ao Espírito pelo qual Estêvão falava.

[[v44-6-11]]

^<<v44-6-11,11>>^ Então convenceram alguns homens a mentir a respeito dele, dizendo: "Ouvimos Estêvão blasfemar contra Moisés, e até contra Deus".

[[v44-6-12]]

^<<v44-6-12,12>>^ Com isso, agitaram o povo, os líderes religiosos e os mestres da lei, e Estêvão foi preso e levado ao conselho dos líderes do povo.

[[v44-6-13]]

^<<v44-6-13,13>>^ As falsas testemunhas declararam: "Este homem vive falando contra o santo templo e a lei de Moisés.

[[v44-6-14]]

^<<v44-6-14,14>>^ Nós o ouvimos dizer que esse Jesus de Nazaré destruirá o templo e mudará os costumes que Moisés nos deixou".

[[v44-6-15]]

^<<v44-6-15,15>>^ Nesse momento, todos os membros do conselho olharam para Estêvão e viram que seu rosto parecia o rosto de um anjo.

'''

xref:044-atos/044-atos-005.adoc#v44-5-0[&#60; Capítulo Anterior] | <<v44-6-0,Topo>> | xref:044-atos/044-atos-007.adoc#v44-7-0[Próximo Capítulo &#62;]