include::./index.adoc[]

[[v14-16-0]]
=== 2 Crônicas, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v14-16-1]]

^<<v14-16-1,1>>^ No trigésimo sexto ano do reinado de Asa, Baasa, rei de Israel, invadiu Judá e fortificou Ramá, a fim de impedir que qualquer um entrasse ou saísse do território de Asa, rei de Judá.

[[v14-16-2]]

^<<v14-16-2,2>>^ Em resposta, Asa removeu a prata e o ouro dos tesouros do templo do SENHOR e do palácio real. Enviou a prata e o ouro a Ben-Hadade, rei da Síria, que governava em Damasco, com a seguinte mensagem:

[[v14-16-3]]

^<<v14-16-3,3>>^ "Façamos um acordo, você e eu, como aquele que houve entre seu pai e o meu. Envio-lhe prata e ouro. Rompa seu acordo com Baasa, rei de Israel, para que ele me deixe em paz".

[[v14-16-4]]

^<<v14-16-4,4>>^ Ben-Hadade aceitou a proposta do rei Asa e enviou os comandantes de seu exército para atacarem as cidades de Israel. Eles conquistaram Ijom, Dã, Abel-Bete-Maaca e todas as cidades de Naftali que serviam como centros de armazenamento.

[[v14-16-5]]

^<<v14-16-5,5>>^ Quando Baasa, rei de Israel, soube o que havia acontecido, abandonou seu projeto de fortificar Ramá e parou todas as obras ali.

[[v14-16-6]]

^<<v14-16-6,6>>^ Então o rei Asa ordenou aos homens de Judá que levassem embora as pedras e a madeira usadas por Baasa para fortificar Ramá. Asa empregou esses materiais para fortificar as cidades de Geba e Mispá.

[[v14-16-7]]

^<<v14-16-7,7>>^ Por esse tempo, o vidente Hanani foi a Asa, rei de Judá, e lhe disse: "Uma vez que você confiou no rei da Síria, em vez de confiar no SENHOR, seu Deus, perdeu a oportunidade de destruir o exército do rei da Síria.

[[v14-16-8]]

^<<v14-16-8,8>>^ Você não se lembra do que aconteceu aos etíopes, aos líbios e a seu exército enorme, com todos os seus carros de guerra e cavaleiros? Naquela ocasião, você confiou no SENHOR, e ele os entregou em suas mãos.

[[v14-16-9]]

^<<v14-16-9,9>>^ Os olhos do SENHOR passam por toda a terra para mostrar sua força àqueles cujo coração é inteiramente dedicado a ele. Como você foi tolo! De agora em diante, haverá guerras contra você".

[[v14-16-10]]

^<<v14-16-10,10>>^ Asa se irou tanto com o vidente por lhe ter dito isso que mandou prendê-lo e colocá-lo no tronco. Nessa época, Asa também começou a oprimir duramente alguns do povo.

[[v14-16-11]]

^<<v14-16-11,11>>^ Os demais acontecimentos do reinado de Asa, do início ao fim, estão registrados no Livro dos Reis de Judá e de Israel .

[[v14-16-12]]

^<<v14-16-12,12>>^ No trigésimo nono ano de seu reinado, Asa foi atacado por uma doença nos pés. Embora a doença fosse muito grave, ele não buscou a ajuda do SENHOR, mas só dos médicos.

[[v14-16-13]]

^<<v14-16-13,13>>^ Então, no quadragésimo primeiro ano de seu reinado, morreu e se reuniu a seus antepassados.

[[v14-16-14]]

^<<v14-16-14,14>>^ Foi sepultado no túmulo que havia mandado abrir na Cidade de Davi. Foi colocado num leito perfumado com especiarias e vários óleos aromáticos, e o povo fez uma imensa fogueira em sua honra.

'''

xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[&#60; Capítulo Anterior] | <<v14-16-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[Próximo Capítulo &#62;]