include::./index.adoc[]

[[v14-20-0]]
=== 2 Crônicas, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v14-20-1]]

^<<v14-20-1,1>>^ Depois disso, os exércitos dos moabitas e dos amonitas e alguns meunitas declararam guerra a Josafá.

[[v14-20-2]]

^<<v14-20-2,2>>^ Mensageiros informaram a Josafá: "Um exército enorme de Edom vem de além do mar Morto contra o rei. Já está em Hazazom-Tamar (isto é, em En-Gedi)".

[[v14-20-3]]

^<<v14-20-3,3>>^ Josafá ficou amedrontado com essa notícia e pediu orientação ao SENHOR. Ordenou um jejum em todo o Judá,

[[v14-20-4]]

^<<v14-20-4,4>>^ e habitantes de todas as cidades de Judá vieram a Jerusalém para buscar a ajuda do SENHOR.

[[v14-20-5]]

^<<v14-20-5,5>>^ Josafá se pôs em pé diante da comunidade de Judá e de Jerusalém, em frente ao pátio novo do templo do SENHOR,

[[v14-20-6]]

^<<v14-20-6,6>>^ e orou: "Ó SENHOR, o Deus de nossos antepassados, somente tu és o Deus que está nos céus. Tu governas todos os reinos da terra. És forte e poderoso, e ninguém pode resistir a ti!

[[v14-20-7]]

^<<v14-20-7,7>>^ Ó nosso Deus, acaso não expulsaste os habitantes desta terra quando Israel, teu povo, chegou? Não deste esta terra para sempre aos descendentes de teu amigo Abraão?

[[v14-20-8]]

^<<v14-20-8,8>>^ Teu povo se estabeleceu aqui e construiu este templo em honra ao teu nome.

[[v14-20-9]]

^<<v14-20-9,9>>^ Disseram: ‘Se enfrentarmos alguma calamidade, como guerra, praga ou fome, nos colocaremos em tua presença diante deste templo onde teu nome é honrado. Clamaremos a ti em nossa angústia, e tu nos ouvirás e nos salvarás’.

[[v14-20-10]]

^<<v14-20-10,10>>^ "Agora, vê o que fazem os exércitos de Amom, Moabe e do monte Seir. Tu não permitiste que nossos antepassados invadissem essas nações quando Israel saiu do Egito, por isso os israelitas se desviaram deles e não os destruíram.

[[v14-20-11]]

^<<v14-20-11,11>>^ Vê como nos retribuem! Vieram nos expulsar de nossa terra, que nos deste por herança.

[[v14-20-12]]

^<<v14-20-12,12>>^ Ó nosso Deus, não os castigarás por isso? Não temos forças para lutar com esse exército imenso que está prestes a nos atacar. Não sabemos o que fazer, mas esperamos o socorro que vem de ti".

[[v14-20-13]]

^<<v14-20-13,13>>^ Enquanto todos os homens de Judá estavam diante do SENHOR com suas crianças de colo, suas esposas e seus filhos,

[[v14-20-14]]

^<<v14-20-14,14>>^ o Espírito do SENHOR veio sobre um homem ali no meio. Seu nome era Jaaziel, filho de Zacarias, filho de Benaia, filho de Jeiel, filho de Matanias, levita descendente de Asafe.

[[v14-20-15]]

^<<v14-20-15,15>>^ Ele disse: "Escutem-me, todos vocês, povo de Judá e de Jerusalém! Escute, rei Josafá! Assim diz o SENHOR: Não tenham medo! Não fiquem desanimados por causa desse exército imenso, pois a batalha não é sua, mas de Deus.

[[v14-20-16]]

^<<v14-20-16,16>>^ Amanhã, marchem contra eles. Vocês os encontrarão vindo pela subida de Ziz, no fim do vale que abre para o deserto de Jeruel.

[[v14-20-17]]

^<<v14-20-17,17>>^ Quando os encontrarem, porém, não terão de lutar. Tomem suas posições; depois, fiquem parados e vejam o livramento do SENHOR. Ele está com vocês, povo de Judá e de Jerusalém. Não tenham medo nem desanimem. Saiam para enfrentá-los amanhã, pois o SENHOR está com vocês!".

[[v14-20-18]]

^<<v14-20-18,18>>^ Então o rei Josafá se prostrou com o rosto no chão, e todo o povo de Judá e de Jerusalém fez o mesmo, em adoração ao SENHOR.

[[v14-20-19]]

^<<v14-20-19,19>>^ Em seguida, os levitas dos clãs de Coate e de Coré se levantaram para louvar em alta voz o SENHOR, o Deus de Israel.

[[v14-20-20]]

^<<v14-20-20,20>>^ Bem cedo, na manhã seguinte, o exército de Judá saiu para o deserto de Tecoa. No caminho, Josafá parou e disse: "Escutem-me, povo de Judá e de Jerusalém! Creiam no SENHOR, seu Deus, e permanecerão firmes. Creiam em seus profetas e terão êxito".

[[v14-20-21]]

^<<v14-20-21,21>>^ Depois de consultar o povo, o rei nomeou cantores para irem adiante do exército, cantando e louvando o SENHOR por sua santa majestade. Cantavam assim: "Deem graças ao SENHOR; seu amor dura para sempre!".

[[v14-20-22]]

^<<v14-20-22,22>>^ No momento em que começaram a cantar e louvar, o SENHOR trouxe confusão sobre os exércitos de Amom, Moabe e do monte Seir, e eles começaram a lutar entre si.

[[v14-20-23]]

^<<v14-20-23,23>>^ Os exércitos de Moabe e Amom se voltaram contra seus aliados do monte Seir e mataram todos eles. Depois que haviam destruído o exército de Seir, começaram a atacar uns aos outros.

[[v14-20-24]]

^<<v14-20-24,24>>^ Quando os homens de Judá chegaram ao local de onde se avista o deserto, viram apenas cadáveres no chão, até onde se podia enxergar. Não escapou nem um só dos inimigos.

[[v14-20-25]]

^<<v14-20-25,25>>^ O rei Josafá e seus homens saíram para recolher os despojos. Encontraram grande quantidade de suprimentos, roupas e outros objetos de valor, mais do que eram capazes de carregar. Havia tantos despojos que levaram três dias para recolher tudo.

[[v14-20-26]]

^<<v14-20-26,26>>^ No quarto dia, reuniram-se no vale de Beracá, que recebeu esse nome depois daquele dia, pois louvaram o SENHOR ali. Por isso, até hoje é chamado de vale de Beracá.

[[v14-20-27]]

^<<v14-20-27,27>>^ Então todos os soldados de Judá e de Jerusalém voltaram, com Josafá à frente, muito alegres porque o SENHOR lhes tinha dado vitória sobre seus inimigos.

[[v14-20-28]]

^<<v14-20-28,28>>^ Entraram marchando em Jerusalém, ao som de harpas, liras e trombetas, e foram ao templo do SENHOR.

[[v14-20-29]]

^<<v14-20-29,29>>^ Quando todos os reinos vizinhos souberam que o próprio SENHOR havia lutado contra os inimigos de Israel, o temor de Deus veio sobre eles.

[[v14-20-30]]

^<<v14-20-30,30>>^ E o reino de Josafá teve paz, pois seu Deus lhe deu descanso de todos os lados.

[[v14-20-31]]

^<<v14-20-31,31>>^ Assim, Josafá reinou sobre a terra de Judá. Tinha 35 anos quando começou a reinar, e reinou em Jerusalém por 25 anos. Sua mãe se chamava Azuba e era filha de Sili.

[[v14-20-32]]

^<<v14-20-32,32>>^ Josafá foi um bom rei, que seguiu o exemplo de seu pai, Asa, e fez o que era certo aos olhos do SENHOR.

[[v14-20-33]]

^<<v14-20-33,33>>^ Contudo, não removeu todos os santuários idólatras, e o povo não se comprometeu a seguir o Deus de seus antepassados.

[[v14-20-34]]

^<<v14-20-34,34>>^ Os demais acontecimentos do reinado de Josafá, do início ao fim, estão anotados nos Registros de Jeú, filho de Hanani , e foram incluídos no Livro dos Reis de Israel .

[[v14-20-35]]

^<<v14-20-35,35>>^ Algum tempo depois, Josafá, rei de Judá, fez um acordo com Acazias, rei de Israel, que era um homem muito perverso.

[[v14-20-36]]

^<<v14-20-36,36>>^ Juntos, construíram uma frota de navios mercantes no porto em Eziom-Geber.

[[v14-20-37]]

^<<v14-20-37,37>>^ Então Eliézer, filho de Dodava, de Maressa, profetizou contra Josafá, dizendo: "Porque você se aliou ao rei Acazias, o SENHOR destruirá o que você construiu". Assim, as embarcações naufragaram e nunca chegaram a navegar.

'''

xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[&#60; Capítulo Anterior] | <<v14-20-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[Próximo Capítulo &#62;]