include::./index.adoc[]

[[v14-31-0]]
=== 2 Crônicas, 31
// nvt ?, NVT - Nova Versão Transformadora

[[v14-31-1]]

^<<v14-31-1,1>>^ Quando a festa terminou, os israelitas que haviam participado saíram pelas cidades de Judá, Benjamim, Efraim e Manassés e despedaçaram todas as colunas sagradas, derrubaram os postes de Aserá e removeram os santuários e altares idólatras. Depois disso, voltaram para suas cidades e casas.

[[v14-31-2]]

^<<v14-31-2,2>>^ Ezequias organizou os sacerdotes e os levitas em divisões, para oferecerem os holocaustos e as ofertas de paz e para servirem, darem graças e louvarem ao SENHOR junto às portas da habitação do SENHOR.

[[v14-31-3]]

^<<v14-31-3,3>>^ O rei também contribuiu pessoalmente com animais para os holocaustos diários da manhã e da tarde e para os holocaustos dos sábados, das festas da lua nova e das festas anuais prescritas pela lei do SENHOR.

[[v14-31-4]]

^<<v14-31-4,4>>^ Além disso, ordenou ao povo de Jerusalém que trouxesse uma parte de seus bens para os sacerdotes e os levitas, a fim de que pudessem se dedicar inteiramente à lei do SENHOR.

[[v14-31-5]]

^<<v14-31-5,5>>^ Quando os israelitas souberam dessa exigência, responderam generosamente e trouxeram a primeira porção de seus cereais, do vinho novo, do azeite, do mel e de tudo que os campos produziam. Trouxeram uma grande quantidade, o dízimo de tudo que haviam produzido.

[[v14-31-6]]

^<<v14-31-6,6>>^ Os habitantes de Israel que tinham se mudado para Judá, e os próprios habitantes de Judá, trouxeram o dízimo do gado, das ovelhas, bem como das coisas que haviam sido consagradas ao SENHOR, seu Deus, e juntaram tudo em vários montões.

[[v14-31-7]]

^<<v14-31-7,7>>^ Começaram a amontoar as ofertas no terceiro mês e terminaram no sétimo.

[[v14-31-8]]

^<<v14-31-8,8>>^ Quando Ezequias e seus oficiais viram esses montões, agradeceram ao SENHOR e a seu povo, Israel.

[[v14-31-9]]

^<<v14-31-9,9>>^ "De onde veio tudo isto?", perguntou Ezequias aos sacerdotes e aos levitas.

[[v14-31-10]]

^<<v14-31-10,10>>^ Azarias, o sumo sacerdote, da família de Zadoque, respondeu: "Desde que o povo começou a trazer ofertas para o templo do SENHOR, temos alimento suficiente e ainda tem sobrado muito. O SENHOR abençoou seu povo, e tudo isto é o que sobra".

[[v14-31-11]]

^<<v14-31-11,11>>^ Ezequias mandou preparar depósitos no templo do SENHOR. Quando estavam prontos,

[[v14-31-12]]

^<<v14-31-12,12>>^ o povo trouxe fielmente as ofertas, os dízimos e os objetos consagrados para serem usados no templo. O levita Conanias foi encarregado desses depósitos, e seu irmão Simei era seu auxiliar.

[[v14-31-13]]

^<<v14-31-13,13>>^ Os supervisores subordinados a eles eram Jeiel, Azazias, Naate, Asael, Jerimote, Jozabade, Eliel, Ismaquias, Maate e Benaia. As nomeações foram feitas pelo rei Ezequias e por Azarias, o principal encarregado do templo de Deus.

[[v14-31-14]]

^<<v14-31-14,14>>^ Coré, filho do levita Imna, guarda da porta do Leste, foi encarregado de distribuir as ofertas voluntárias feitas a Deus, as contribuições e os objetos consagrados ao SENHOR.

[[v14-31-15]]

^<<v14-31-15,15>>^ Seus assistentes fiéis eram Éden, Miniamim, Jesua, Semaías, Amarias e Secanias. Distribuíam as ofertas entre as famílias dos sacerdotes em suas cidades, de acordo com suas divisões, e as repartiam por igual entre idosos e jovens.

[[v14-31-16]]

^<<v14-31-16,16>>^ Distribuíam as ofertas a todos os homens e meninos, de 3 anos para cima, que constavam dos registros genealógicos. A distribuição incluía todos que vinham ao templo do SENHOR para realizar suas tarefas diárias, de acordo com suas divisões.

[[v14-31-17]]

^<<v14-31-17,17>>^ Repartiam as ofertas entre os sacerdotes que estavam listados nos registros genealógicos, de acordo com suas famílias, e entre os levitas de 20 anos para cima, anotados de acordo com suas tarefas e divisões.

[[v14-31-18]]

^<<v14-31-18,18>>^ Também entregavam porções de alimento às famílias de todos que estavam listados nos registros genealógicos, incluindo as crianças pequenas, as esposas, os filhos e as filhas, pois toda a comunidade havia sido fiel ao se purificar.

[[v14-31-19]]

^<<v14-31-19,19>>^ Quanto aos sacerdotes, os descendentes de Arão, que viviam nos campos ao redor das cidades, foram nomeados homens para distribuir em porções a todos os sacerdotes e a todos os levitas listados nos registros genealógicos.

[[v14-31-20]]

^<<v14-31-20,20>>^ Assim, o rei Ezequias organizou a distribuição em todo o Judá, e fez o que era bom, certo e verdadeiro aos olhos do SENHOR, seu Deus.

[[v14-31-21]]

^<<v14-31-21,21>>^ Em tudo que fez no serviço do templo de Deus e em seus esforços para obedecer à lei e aos mandamentos de Deus, Ezequias buscou seu Deus de todo o coração. Como resultado, foi muito bem-sucedido.

'''

xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[&#60; Capítulo Anterior] | <<v14-31-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[Próximo Capítulo &#62;]