include::./index.adoc[]

[[v14-25-0]]
=== 2 Crônicas, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v14-25-1]]

^<<v14-25-1,1>>^ Amazias tinha 25 anos quando começou a reinar, e reinou em Jerusalém por 29 anos. Sua mãe se chamava Jeoadã e era de Jerusalém.

[[v14-25-2]]

^<<v14-25-2,2>>^ Amazias fez o que era certo aos olhos do SENHOR, mas não de todo o coração.

[[v14-25-3]]

^<<v14-25-3,3>>^ Quando Amazias se firmou no poder, executou os oficiais que haviam assassinado seu pai.

[[v14-25-4]]

^<<v14-25-4,4>>^ Contudo, não matou os filhos dos assassinos, em obediência ao mandamento do SENHOR registrado por Moisés no Livro da Lei: "Os pais não serão executados por causa do pecado dos filhos, nem os filhos por causa do pecado dos pais. Aqueles que merecem morrer deverão ser executados por causa de seus próprios crimes".

[[v14-25-5]]

^<<v14-25-5,5>>^ Amazias organizou o exército e nomeou generais e capitães para todo o Judá e para Benjamim. Fez um censo e constatou que tinha um exército de trezentos mil soldados de elite, com mais de 20 anos, todos treinados no uso da espada e do escudo.

[[v14-25-6]]

^<<v14-25-6,6>>^ Também pagou 3.500 quilos de prata para contratar cem mil guerreiros experientes de Israel.

[[v14-25-7]]

^<<v14-25-7,7>>^ Então um homem de Deus foi até ele e lhe disse: "Ó rei, não contrate soldados de Israel, pois o SENHOR não está com Israel. Ele não ajudará o povo de Efraim!

[[v14-25-8]]

^<<v14-25-8,8>>^ Se deixar que acompanhem seus soldados na batalha, mesmo que lutem com coragem, serão derrotados pelo inimigo. Deus o derrubará, pois ele tem poder para ajudá-lo ou fazê-lo tropeçar".

[[v14-25-9]]

^<<v14-25-9,9>>^ Amazias perguntou ao homem de Deus: "E quanto à prata que paguei para contratar o exército de Israel?". O homem de Deus respondeu: "O SENHOR pode lhe dar muito mais que isso!".

[[v14-25-10]]

^<<v14-25-10,10>>^ Então Amazias dispensou os soldados que havia contratado e os mandou de volta para Efraim. Eles ficaram furiosos com Judá e voltaram para casa indignados.

[[v14-25-11]]

^<<v14-25-11,11>>^ Amazias criou coragem e conduziu seu exército até o vale do Sal, onde mataram dez mil soldados edomitas da região de Seir.

[[v14-25-12]]

^<<v14-25-12,12>>^ Capturaram outros dez mil e os levaram para o alto de um penhasco, de onde os atiraram, e eles se despedaçaram.

[[v14-25-13]]

^<<v14-25-13,13>>^ Enquanto isso, os soldados que Amazias havia contratado e depois mandado de volta atacaram muitas cidades de Judá entre Samaria e Bete-Horom. Mataram três mil pessoas e levaram grande quantidade de despojos.

[[v14-25-14]]

^<<v14-25-14,14>>^ Quando o rei Amazias voltou da matança dos edomitas, trouxe os deuses que havia tomado do povo de Seir. Estabeleceu-os como seus próprios deuses, prostrou-se diante deles e ofereceu-lhes sacrifícios.

[[v14-25-15]]

^<<v14-25-15,15>>^ O SENHOR se irou grandemente e lhe enviou um profeta para perguntar: "Por que você se volta para deuses que não foram capazes nem de salvar de suas mãos o próprio povo deles?".

[[v14-25-16]]

^<<v14-25-16,16>>^ O rei, porém, o interrompeu e disse: "Desde quando você é conselheiro do rei? Cale-se antes que eu mande matá-lo!". O profeta parou, mas o advertiu: "Sei que Deus resolveu destruí-lo, porque você fez isso e porque não quis aceitar meu conselho".

[[v14-25-17]]

^<<v14-25-17,17>>^ Depois de consultar seus conselheiros, Amazias, rei de Judá, enviou este desafio a Jeoás, filho de Jeoacaz e neto de Jeú, rei de Israel: "Venha enfrentar-me numa batalha!".

[[v14-25-18]]

^<<v14-25-18,18>>^ Mas Jeoás, rei de Israel, respondeu a Amazias, rei de Judá, com a seguinte história: "Nos montes do Líbano, o espinheiro enviou esta mensagem ao poderoso cedro: ‘Dê sua filha em casamento a meu filho’. No entanto, um animal selvagem do Líbano veio, pisoteou o espinheiro e o esmagou.

[[v14-25-19]]

^<<v14-25-19,19>>^ "Você diz: ‘Derrotei Edom’, e está muito orgulhoso disso. Mas meu conselho é que fique em casa. Por que causar problemas que só trarão desgraça sobre você e o povo de Judá?".

[[v14-25-20]]

^<<v14-25-20,20>>^ Amazias, porém, se recusou a ouvir, pois Deus havia resolvido destruí-lo por ter se voltado para os deuses de Edom.

[[v14-25-21]]

^<<v14-25-21,21>>^ Então Jeoás, rei de Israel, mobilizou seu exército contra Amazias, rei de Judá. Os dois exércitos se enfrentaram em Bete-Semes, em Judá.

[[v14-25-22]]

^<<v14-25-22,22>>^ O exército de Judá foi derrotado pelo exército de Israel, e os soldados fugiram para casa.

[[v14-25-23]]

^<<v14-25-23,23>>^ Jeoás, rei de Israel, capturou Amazias, filho de Joás e neto de Acazias, em Bete-Semes. Trouxe-o para Jerusalém, onde destruiu 180 metros do muro da cidade, desde a porta de Efraim até a porta da Esquina.

[[v14-25-24]]

^<<v14-25-24,24>>^ Levou embora todo o ouro, toda a prata e todos os utensílios do templo de Deus guardados por Obede-Edom. Também levou os tesouros do palácio real e fez reféns; depois, voltou para Samaria.

[[v14-25-25]]

^<<v14-25-25,25>>^ Amazias, filho de Joás, rei de Judá, viveu ainda mais quinze anos depois da morte de Jeoás, filho de Jeoacaz, rei de Israel.

[[v14-25-26]]

^<<v14-25-26,26>>^ Os demais acontecimentos do reinado de Amazias, do início ao fim, estão registrados no Livro dos Reis de Judá e de Israel .

[[v14-25-27]]

^<<v14-25-27,27>>^ Depois que Amazias se afastou do SENHOR, houve uma conspiração contra ele em Jerusalém, e ele fugiu para Laquis. Seus inimigos, porém, mandaram assassinos atrás dele e o mataram ali.

[[v14-25-28]]

^<<v14-25-28,28>>^ Seu corpo foi trazido de volta para Jerusalém num cavalo, e ele foi sepultado com seus antepassados na Cidade de Davi.

'''

xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[Próximo Capítulo &#62;]