include::./index.adoc[]

[[v14-12-0]]
=== 2 Crônicas, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v14-12-1]]

^<<v14-12-1,1>>^ Quando Roboão havia se fortalecido e se estabelecido firmemente, ele e todo o Israel abandonaram a lei do SENHOR.

[[v14-12-2]]

^<<v14-12-2,2>>^ Por causa dessa infidelidade ao SENHOR, no quinto ano do reinado de Roboão, Sisaque, rei do Egito, subiu e atacou Jerusalém.

[[v14-12-3]]

^<<v14-12-3,3>>^ Veio com 1.200 carros de guerra, 60.000 cavaleiros e um exército incontável de soldados de infantaria líbios, suquitas e etíopes.

[[v14-12-4]]

^<<v14-12-4,4>>^ Sisaque conquistou as cidades fortificadas de Judá e avançou para atacar Jerusalém.

[[v14-12-5]]

^<<v14-12-5,5>>^ Então o profeta Semaías foi ao encontro de Roboão e dos líderes de Judá, que haviam todos fugido para Jerusalém por causa de Sisaque. Semaías lhes disse: "Assim diz o SENHOR: ‘Vocês me abandonaram, por isso agora eu os abandonei, entregando-os nas mãos de Sisaque’".

[[v14-12-6]]

^<<v14-12-6,6>>^ Então os líderes de Israel e o rei se humilharam e disseram: "O SENHOR é justo!".

[[v14-12-7]]

^<<v14-12-7,7>>^ Quando o SENHOR viu que eles se humilharam, deu a Semaías esta mensagem: "Visto que se humilharam, não os destruirei completamente, mas logo lhes darei algum alívio. Não usarei Sisaque para derramar minha ira sobre Jerusalém.

[[v14-12-8]]

^<<v14-12-8,8>>^ Eles, contudo, se tornarão servos dele, para que aprendam a diferença entre servir a mim e servir aos governantes da terra".

[[v14-12-9]]

^<<v14-12-9,9>>^ Então Sisaque, rei do Egito, subiu e atacou Jerusalém. Saqueou os tesouros do templo do SENHOR e do palácio real; levou tudo, incluindo os escudos de ouro que Salomão havia feito.

[[v14-12-10]]

^<<v14-12-10,10>>^ Mais tarde, o rei Roboão fez escudos de bronze para substituí-los e os confiou aos oficiais da guarda que protegiam a entrada do palácio real.

[[v14-12-11]]

^<<v14-12-11,11>>^ Sempre que o rei ia ao templo do SENHOR, os guardas levavam os escudos e, em seguida, os devolviam à sala da guarda.

[[v14-12-12]]

^<<v14-12-12,12>>^ Porque Roboão se humilhou, a ira do SENHOR se afastou dele, e ele não foi completamente destruído. Ainda havia coisas boas na terra de Judá.

[[v14-12-13]]

^<<v14-12-13,13>>^ O rei Roboão se estabeleceu firmemente em Jerusalém e continuou a reinar. Tinha 41 anos quando começou a reinar, e reinou por dezessete anos em Jerusalém, a cidade que o SENHOR havia escolhido dentre todas as tribos de Israel como lugar para o seu nome. A mãe de Roboão se chamava Naamá e era de Amom.

[[v14-12-14]]

^<<v14-12-14,14>>^ Ele foi um rei perverso, pois não buscou o SENHOR de todo o coração.

[[v14-12-15]]

^<<v14-12-15,15>>^ Os demais acontecimentos do reinado de Roboão, do início ao fim, estão anotados no Registro do Profeta Semaías  e no Registro do Vidente Ido , que fazem parte do registro genealógico. Houve guerra constante entre Roboão e Jeroboão.

[[v14-12-16]]

^<<v14-12-16,16>>^ Quando Roboão morreu e se reuniu a seus antepassados, foi sepultado na Cidade de Davi. Seu filho Abias foi seu sucessor.

'''

xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[&#60; Capítulo Anterior] | <<v14-12-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[Próximo Capítulo &#62;]