include::./index.adoc[]

[[v14-1-0]]
=== 2 Crônicas, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v14-1-1]]

^<<v14-1-1,1>>^ Salomão, filho de Davi, estabeleceu firme controle sobre seu reino, pois o SENHOR, seu Deus, estava com ele e o tornou muito poderoso.

[[v14-1-2]]

^<<v14-1-2,2>>^ Salomão convocou todas as autoridades de Israel: os generais e capitães do exército, os juízes e todos os líderes e chefes dos clãs.

[[v14-1-3]]

^<<v14-1-3,3>>^ Então conduziu toda a comunidade ao lugar de culto em Gibeom, pois ali ficava a tenda do encontro. Essa era a tenda que Moisés, servo do SENHOR, havia feito no deserto.

[[v14-1-4]]

^<<v14-1-4,4>>^ Davi tinha transportado a arca de Deus de Quiriate-Jearim para a tenda que ele havia preparado para ela em Jerusalém.

[[v14-1-5]]

^<<v14-1-5,5>>^ Mas o altar de bronze feito por Bezalel, filho de Uri e neto de Hur, ainda estava ali em Gibeom, em frente ao tabernáculo do SENHOR. Então Salomão e o povo se reuniram nesse local para consultar o SENHOR.

[[v14-1-6]]

^<<v14-1-6,6>>^ Na presença do SENHOR, Salomão ofereceu mil holocaustos sobre o altar de bronze, que estava na tenda do encontro.

[[v14-1-7]]

^<<v14-1-7,7>>^ Naquela noite, Deus apareceu a Salomão e lhe disse: "Peça o que quiser, e eu lhe darei".

[[v14-1-8]]

^<<v14-1-8,8>>^ Salomão respondeu a Deus: "Tu mostraste grande amor leal a meu pai, Davi, e agora me fizeste rei em seu lugar.

[[v14-1-9]]

^<<v14-1-9,9>>^ Ó SENHOR Deus, cumpre a promessa que fizeste a meu pai, Davi, pois me fizeste rei sobre um povo tão numeroso como o pó da terra!

[[v14-1-10]]

^<<v14-1-10,10>>^ Dá-me sabedoria e conhecimento para que eu os lidere bem, pois quem é capaz de governar este teu grande povo?".

[[v14-1-11]]

^<<v14-1-11,11>>^ Deus disse a Salomão: "Uma vez que esse é seu desejo, e não pediu riqueza, nem bens, nem fama, nem a morte de seus inimigos, nem vida longa, mas sabedoria e conhecimento para governar bem meu povo, sobre o qual o fiz rei,

[[v14-1-12]]

^<<v14-1-12,12>>^ certamente lhe darei a sabedoria e o conhecimento que pediu. Também lhe darei riqueza, bens e fama como nenhum rei teve nem jamais terá".

[[v14-1-13]]

^<<v14-1-13,13>>^ Então Salomão voltou da tenda do encontro, no lugar de culto em Gibeom, para Jerusalém, e reinou sobre todo o Israel.

[[v14-1-14]]

^<<v14-1-14,14>>^ Salomão ajuntou muitos carros de guerra e cavalos. Possuía 1.400 carros de guerra e 12.000 cavalos. Mantinha alguns deles nas cidades designadas para guardar esses carros de guerra e outros perto dele, em Jerusalém.

[[v14-1-15]]

^<<v14-1-15,15>>^ O rei tornou a prata e o ouro tão comuns em Jerusalém como as pedras. E havia tanta madeira valiosa de cedro como as figueiras-bravas que crescem nas colinas de Judá.

[[v14-1-16]]

^<<v14-1-16,16>>^ Os cavalos de Salomão eram importados do Egito e da Cilícia; os comerciantes do rei os adquiriam da Cilícia pelo preço de mercado.

[[v14-1-17]]

^<<v14-1-17,17>>^ Naquela época, um carro de guerra do Egito custava 600 peças de prata, e um cavalo, 150 peças de prata. Depois, eram exportados aos reis dos hititas e aos reis da Síria.

'''

xref:013-1-cronicas/013-1-cronicas-029.adoc#v13-29-0[&#60; Capítulo Anterior] | <<v14-1-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-002.adoc#v14-2-0[Próximo Capítulo &#62;]