include::./index.adoc[]

[[v14-23-0]]
=== 2 Crônicas, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v14-23-1]]

^<<v14-23-1,1>>^ No sétimo ano do reinado de Atalia, o sacerdote Joiada decidiu agir. Criou coragem e fez um acordo com os comandantes dos batalhões: Azarias, filho de Jeroão; Ismael, filho de Joanã; Azarias, filho de Obede; Maaseias, filho de Adaías; e Elisafate, filho de Zicri.

[[v14-23-2]]

^<<v14-23-2,2>>^ Esses homens viajaram por todo o reino de Judá e convocaram os levitas e os chefes das famílias de todas as cidades para irem a Jerusalém.

[[v14-23-3]]

^<<v14-23-3,3>>^ Todos se reuniram no templo de Deus, onde firmaram um pacto solene com o jovem rei Joás. Joiada lhes disse: "Aqui está o filho do rei! Chegou a hora de ele governar! O SENHOR prometeu que um descendente de Davi seria nosso rei.

[[v14-23-4]]

^<<v14-23-4,4>>^ Vocês devem fazer o seguinte: quando os sacerdotes e os levitas entrarem em serviço no sábado, uma terça parte de vocês ficará de guarda nas portas.

[[v14-23-5]]

^<<v14-23-5,5>>^ Outra terça parte irá ao palácio real. E a última terça parte ficará de guarda na Porta do Alicerce. Os demais permanecerão nos pátios do templo do SENHOR.

[[v14-23-6]]

^<<v14-23-6,6>>^ Lembrem-se: apenas os sacerdotes e os levitas de serviço podem entrar no templo do SENHOR, pois foram consagrados. O restante do povo deve obedecer às instruções do SENHOR e ficar do lado de fora.

[[v14-23-7]]

^<<v14-23-7,7>>^ Vocês, levitas, posicionem-se em volta do rei, de armas na mão. Matem qualquer pessoa que tentar entrar no templo. Permaneçam com o rei aonde ele for".

[[v14-23-8]]

^<<v14-23-8,8>>^ Então os levitas e o povo de Judá fizeram tudo que o sacerdote Joiada ordenou. Os comandantes se encarregaram dos homens que iam entrar em serviço naquele sábado e dos que iam sair. O sacerdote Joiada não deixou ninguém ir para casa no fim do turno.

[[v14-23-9]]

^<<v14-23-9,9>>^ Depois, Joiada forneceu aos comandantes as lanças e os escudos grandes e pequenos que haviam pertencido ao rei Davi e que estavam guardados no templo de Deus.

[[v14-23-10]]

^<<v14-23-10,10>>^ Posicionou todos os homens em volta do rei, de armas na mão. Formaram uma fileira desde o lado sul do templo até o lado norte e ao redor do altar.

[[v14-23-11]]

^<<v14-23-11,11>>^ Então Joiada e seus filhos trouxeram Joás, o filho do rei, para fora, puseram a coroa em sua cabeça e lhe entregaram uma cópia da lei. Depois, ungiram Joás e o proclamaram rei, e todos gritaram: "Viva o rei!".

[[v14-23-12]]

^<<v14-23-12,12>>^ Quando Atalia ouviu o barulho do povo correndo e os gritos de louvor ao rei, foi para o templo do SENHOR, onde o povo estava reunido.

[[v14-23-13]]

^<<v14-23-13,13>>^ Ao chegar, viu o rei em pé, no lugar de honra junto à coluna na entrada do templo. Estava rodeado pelos comandantes e tocadores de trombeta, e gente de toda a terra se alegrava e tocava trombetas. Cantores com instrumentos musicais dirigiam o povo numa grande celebração. Quando Atalia viu tudo isso, rasgou suas roupas e gritou: "Traição! Traição!".

[[v14-23-14]]

^<<v14-23-14,14>>^ Então o sacerdote Joiada ordenou aos comandantes encarregados das tropas: "Levem-na aos soldados que estão na frente do templo e matem qualquer pessoa que a seguir". Pois o sacerdote tinha dito: "Ela não deve ser morta dentro do templo do SENHOR".

[[v14-23-15]]

^<<v14-23-15,15>>^ Eles a prenderam e a levaram à porta dos Cavalos, no terreno do palácio, e a mataram ali.

[[v14-23-16]]

^<<v14-23-16,16>>^ Joiada fez uma aliança entre ele, o povo e o rei, estabelecendo que eles seriam o povo do SENHOR.

[[v14-23-17]]

^<<v14-23-17,17>>^ Todo o povo foi ao templo de Baal e o derrubou. Demoliram os altares, despedaçaram os ídolos e executaram Matã, sacerdote de Baal, em frente aos altares.

[[v14-23-18]]

^<<v14-23-18,18>>^ Joiada encarregou os sacerdotes e os levitas de cuidarem do templo do SENHOR, segundo as instruções de Davi. Ordenou que apresentassem holocaustos ao SENHOR, como ordenava a lei de Moisés, com cânticos e alegria, conforme Davi tinha instruído.

[[v14-23-19]]

^<<v14-23-19,19>>^ Também pôs guardas às portas do templo do SENHOR, para que não entrasse ninguém que, por algum motivo, estivesse cerimonialmente impuro.

[[v14-23-20]]

^<<v14-23-20,20>>^ Então os comandantes dos batalhões, os nobres, os governantes e todo o povo da terra escoltaram o rei para fora do templo do SENHOR. Passaram pela porta Superior e entraram no palácio, onde o rei se sentou no trono real.

[[v14-23-21]]

^<<v14-23-21,21>>^ Todo o povo do reino se alegrou e a cidade ficou em paz, pois Atalia tinha sido morta.

'''

xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[&#60; Capítulo Anterior] | <<v14-23-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[Próximo Capítulo &#62;]