include::./index.adoc[]

[[v14-4-0]]
=== 2 Crônicas, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v14-4-1]]

^<<v14-4-1,1>>^ Salomão também fez um altar de bronze com 9 metros de comprimento, 9 metros de largura e 4,5 metros de altura.

[[v14-4-2]]

^<<v14-4-2,2>>^ Depois, fundiu um grande tanque redondo, chamado Mar. O tanque media 4,5 metros de uma borda à outra, 2,25 metros de profundidade e 13,5 metros de circunferência.

[[v14-4-3]]

^<<v14-4-3,3>>^ Logo abaixo da borda, tinha ao seu redor duas fileiras de figuras semelhantes a touros. Havia cerca de vinte figuras por metro em toda a circunferência, formando uma única peça de fundição com o tanque.

[[v14-4-4]]

^<<v14-4-4,4>>^ O tanque ficava apoiado sobre doze touros, todos voltados para fora: três voltados para o norte, três para o oeste, três para o sul e três para o leste.

[[v14-4-5]]

^<<v14-4-5,5>>^ As paredes do tanque tinham oito centímetros de espessura, e sua borda se projetava para fora como uma taça, semelhante a um lírio. Tinha capacidade para cerca de sessenta mil litros de água.

[[v14-4-6]]

^<<v14-4-6,6>>^ Fez também dez pias menores para lavar os utensílios para os holocaustos. Colocou cinco do lado sul e cinco do lado norte. Os sacerdotes, porém, se lavavam no tanque chamado Mar.

[[v14-4-7]]

^<<v14-4-7,7>>^ Fez dez candelabros de ouro, de acordo com as especificações que havia recebido, e os colocou no templo, cinco do lado sul e cinco do lado norte.

[[v14-4-8]]

^<<v14-4-8,8>>^ Fez dez mesas e as colocou no templo, cinco do lado sul e cinco do lado norte. Também fez cem bacias de ouro.

[[v14-4-9]]

^<<v14-4-9,9>>^ Depois, construiu o pátio dos sacerdotes e o grande pátio externo. Fez portas para as entradas dos pátios e as revestiu com bronze.

[[v14-4-10]]

^<<v14-4-10,10>>^ O grande tanque de bronze chamado Mar foi colocado perto do canto sudeste do templo.

[[v14-4-11]]

^<<v14-4-11,11>>^ Hurão-Abi também fez as bacias, pás e tigelas necessárias. Assim, Hurão-Abi terminou tudo que o rei Salomão havia ordenado que ele fizesse para o templo de Deus:

[[v14-4-12]]

^<<v14-4-12,12>>^ as duas colunas; os dois capitéis em forma de taça no alto das colunas; os dois conjuntos de correntes entrelaçadas que enfeitavam os capitéis;

[[v14-4-13]]

^<<v14-4-13,13>>^ as quatrocentas romãs penduradas nas correntes dos capitéis (duas fileiras de romãs para cada conjunto de correntes que enfeitavam os capitéis no alto das colunas);

[[v14-4-14]]

^<<v14-4-14,14>>^ as bases móveis para levar água com as pias;

[[v14-4-15]]

^<<v14-4-15,15>>^ o Mar e os doze bois debaixo dele;

[[v14-4-16]]

^<<v14-4-16,16>>^ os baldes das cinzas, as pás, os garfos de carne e os demais utensílios. Hurão-Abi fez todos esses utensílios de bronze polido para o templo do SENHOR, conforme as instruções do rei Salomão.

[[v14-4-17]]

^<<v14-4-17,17>>^ O rei ordenou que fossem fundidos em moldes de barro no vale do Jordão, entre Sucote e Zaretã.

[[v14-4-18]]

^<<v14-4-18,18>>^ Salomão usou uma quantidade tão grande de bronze que seu peso não pôde ser medido.

[[v14-4-19]]

^<<v14-4-19,19>>^ Salomão também fez toda a mobília para o templo de Deus: o altar de ouro; as mesas para os pães da presença;

[[v14-4-20]]

^<<v14-4-20,20>>^ os candelabros e suas lâmpadas de ouro maciço, para serem acesas diante do lugar santíssimo, conforme determinado;

[[v14-4-21]]

^<<v14-4-21,21>>^ os enfeites de flores, as lâmpadas e as tenazes, todos do ouro mais puro;

[[v14-4-22]]

^<<v14-4-22,22>>^ os cortadores de pavio, as tigelas, as colheres e os incensários, todos de ouro maciço; as dobradiças das portas de entrada do lugar santíssimo e do salão principal do templo, revestidas com ouro.

'''

xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[Próximo Capítulo &#62;]