include::./index.adoc[]

[[v14-10-0]]
=== 2 Crônicas, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v14-10-1]]

^<<v14-10-1,1>>^ Roboão foi a Siquém, onde todo o Israel havia se reunido para proclamá-lo rei.

[[v14-10-2]]

^<<v14-10-2,2>>^ Quando Jeroboão, filho de Nebate, soube disso, voltou do Egito, para onde havia fugido do rei Salomão.

[[v14-10-3]]

^<<v14-10-3,3>>^ Os líderes de Israel convocaram Jeroboão, e ele e todo o Israel foram falar com Roboão.

[[v14-10-4]]

^<<v14-10-4,4>>^ "Seu pai foi muito duro conosco", disseram. "Alivie a carga pesada de trabalho e de impostos altos que seu pai nos obrigou a carregar. Então seremos seus súditos leais."

[[v14-10-5]]

^<<v14-10-5,5>>^ Roboão respondeu: "Voltem daqui três dias para saber minha resposta". E o povo foi embora.

[[v14-10-6]]

^<<v14-10-6,6>>^ O rei Roboão discutiu o assunto com os homens mais velhos que haviam sido conselheiros de seu pai, Salomão. "O que vocês aconselham?", perguntou ele. "Como devo responder a este povo?"

[[v14-10-7]]

^<<v14-10-7,7>>^ Eles disseram: "Se o senhor tratar este povo com bondade, se agradá-los e lhes der uma resposta favorável, eles serão seus súditos leais para sempre".

[[v14-10-8]]

^<<v14-10-8,8>>^ Mas Roboão rejeitou o conselho dos homens mais velhos e pediu a opinião dos jovens que haviam crescido com ele e agora o acompanhavam.

[[v14-10-9]]

^<<v14-10-9,9>>^ "O que vocês aconselham?", perguntou ele. "Como devemos responder a este povo que deseja que eu alivie as cargas impostas por meu pai?"

[[v14-10-10]]

^<<v14-10-10,10>>^ Os jovens responderam: "Você deve dizer o seguinte a essa gente que diz que seu pai foi muito duro com eles e que pede alívio: ‘Meu dedo mínimo é mais grosso que a cintura de meu pai!

[[v14-10-11]]

^<<v14-10-11,11>>^ Sim, meu pai lhes impôs cargas pesadas, mas eu as tornarei ainda mais pesadas! Meu pai os castigou com chicotes comuns, mas eu os castigarei com chicotes de pontas de metal!’".

[[v14-10-12]]

^<<v14-10-12,12>>^ Três dias depois, Jeroboão e todo o povo voltaram para saber a decisão do rei, como ele havia ordenado.

[[v14-10-13]]

^<<v14-10-13,13>>^ Roboão lhes respondeu com aspereza, pois rejeitou o conselho dos homens mais velhos

[[v14-10-14]]

^<<v14-10-14,14>>^ e seguiu o conselho dos mais jovens. Disse ao povo: "Meu pai lhes impôs cargas pesadas, mas eu as tornarei ainda mais pesadas! Meu pai os castigou com chicotes comuns, mas eu os castigarei com chicotes de pontas de metal!".

[[v14-10-15]]

^<<v14-10-15,15>>^ Assim, o rei não atendeu o povo. Essa mudança nos acontecimentos foi da vontade de Deus, pois cumpriu a mensagem do SENHOR a Jeroboão, filho de Nebate, por meio do profeta Aías, de Siló.

[[v14-10-16]]

^<<v14-10-16,16>>^ Quando todo o Israel viu que o rei não iria atender a seu pedido, respondeu: "Abaixo a dinastia de Davi! O filho de Jessé nada tem a nos oferecer! Volte para casa, Israel! E você, Davi, cuide de sua própria casa!". Então todo o povo de Israel voltou para casa.

[[v14-10-17]]

^<<v14-10-17,17>>^ Roboão, porém, continuou a governar sobre os israelitas que moravam nas cidades de Judá.

[[v14-10-18]]

^<<v14-10-18,18>>^ O rei Roboão enviou Adonirão, encarregado dos trabalhos forçados, para restaurar a ordem, mas o povo de Israel o apedrejou até a morte. Quando essa notícia chegou ao rei Roboão, subiu rapidamente em sua carruagem e fugiu para Jerusalém.

[[v14-10-19]]

^<<v14-10-19,19>>^ E até hoje as tribos do norte de Israel se recusam a ser governadas por um descendente de Davi.

'''

xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[&#60; Capítulo Anterior] | <<v14-10-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-011.adoc#v14-11-0[Próximo Capítulo &#62;]