include::./index.adoc[]

[[v14-26-0]]
=== 2 Crônicas, 26
// nvt ?, NVT - Nova Versão Transformadora

[[v14-26-1]]

^<<v14-26-1,1>>^ Todo o povo de Judá proclamou Uzias, de 16 anos, rei, como sucessor de seu pai, Amazias.

[[v14-26-2]]

^<<v14-26-2,2>>^ Depois que seu pai morreu e se reuniu a seus antepassados, Uzias reconstruiu a cidade de Elate e a recuperou para Judá.

[[v14-26-3]]

^<<v14-26-3,3>>^ Uzias tinha 16 anos quando começou a reinar, e reinou em Jerusalém por 52 anos. Sua mãe se chamava Jecolias e era de Jerusalém.

[[v14-26-4]]

^<<v14-26-4,4>>^ Fez o que era certo aos olhos do SENHOR, como seu pai, Amazias.

[[v14-26-5]]

^<<v14-26-5,5>>^ Uzias buscou a Deus durante a vida de Zacarias, que o ensinou a temer a Deus. Enquanto o rei buscou a direção do SENHOR, Deus lhe deu êxito.

[[v14-26-6]]

^<<v14-26-6,6>>^ Uzias declarou guerra contra os filisteus e derrubou os muros de Gate, Jabne e Asdode. Ele construiu novas cidades na região de Asdode e em outras partes da Filístia.

[[v14-26-7]]

^<<v14-26-7,7>>^ Deus o ajudou nas guerras contra os filisteus, nas batalhas contra os árabes de Gur e nas guerras contra os meunitas.

[[v14-26-8]]

^<<v14-26-8,8>>^ Os meunitas lhe pagavam tributo anual, e sua fama se espalhou até o Egito, pois ele havia se tornado muito poderoso.

[[v14-26-9]]

^<<v14-26-9,9>>^ Uzias construiu torres fortificadas em Jerusalém, junto à porta da Esquina, à porta do Vale e no canto do muro.

[[v14-26-10]]

^<<v14-26-10,10>>^ Também construiu fortalezas no deserto e cavou muitas cisternas, pois tinha grandes rebanhos nas colinas de Judá e na planície. Era um homem que amava a terra. Tinha muitos trabalhadores que cuidavam de seus campos e vinhedos, tanto nas colinas como nos vales férteis.

[[v14-26-11]]

^<<v14-26-11,11>>^ Uzias tinha um exército de guerreiros bem treinados, prontos para irem à batalha, divididos em tropas. Esse exército havia sido convocado e organizado pelo secretário Jeiel e pelo oficial Maaseias. Estavam sob o comando de Hananias, um dos oficiais do rei.

[[v14-26-12]]

^<<v14-26-12,12>>^ As tropas de guerreiros valentes eram comandadas por 2.600 chefes de famílias.

[[v14-26-13]]

^<<v14-26-13,13>>^ O exército era formado por uma elite de 307.500 homens, preparados para ajudar o rei contra qualquer inimigo.

[[v14-26-14]]

^<<v14-26-14,14>>^ Uzias providenciou para todo o exército escudos, lanças, capacetes, couraças, arcos e fundas de atirar pedras.

[[v14-26-15]]

^<<v14-26-15,15>>^ Construiu sobre os muros de Jerusalém máquinas de guerra criadas por peritos; elas atiravam flechas e lançavam grandes pedras das torres e dos cantos dos muros. Sua fama se espalhou até lugares distantes, pois o SENHOR o ajudou extraordinariamente e ele se tornou muito poderoso.

[[v14-26-16]]

^<<v14-26-16,16>>^ Quando Uzias se tornou poderoso, também se encheu de orgulho, o que o levou à ruína. Pecou contra o SENHOR, seu Deus, ao entrar no santuário do templo do SENHOR para queimar incenso no altar de incenso.

[[v14-26-17]]

^<<v14-26-17,17>>^ O sacerdote Azarias foi atrás dele com outros oitenta sacerdotes do SENHOR, todos homens corajosos.

[[v14-26-18]]

^<<v14-26-18,18>>^ Confrontaram o rei Uzias e disseram: "Não cabe a você, Uzias, queimar incenso ao SENHOR. Isso é tarefa somente dos sacerdotes, os descendentes de Arão, consagrados para esse trabalho. Saia do santuário, pois você pecou. O SENHOR Deus não o honrará".

[[v14-26-19]]

^<<v14-26-19,19>>^ Uzias, que segurava um incensário, ficou indignado. Enquanto ele demonstrava sua raiva contra os sacerdotes diante do altar de incenso no templo do SENHOR, apareceu lepra em sua testa.

[[v14-26-20]]

^<<v14-26-20,20>>^ Quando viram a lepra, o sumo sacerdote Azarias e todos os outros sacerdotes o expulsaram imediatamente do templo. O próprio rei se apressou em sair dali, pois o SENHOR o havia ferido.

[[v14-26-21]]

^<<v14-26-21,21>>^ O rei Uzias ficou leproso até o dia de sua morte. Vivia isolado, numa casa separada, e havia sido excluído do templo do SENHOR. Seu filho Jotão tomava conta do palácio e governava o povo.

[[v14-26-22]]

^<<v14-26-22,22>>^ Os demais acontecimentos do reinado de Uzias, do início ao fim, foram registrados pelo profeta Isaías, filho de Amoz.

[[v14-26-23]]

^<<v14-26-23,23>>^ Quando Uzias morreu, foi sepultado com seus antepassados. Seu túmulo ficava num campo próximo que pertencia aos reis, pois o povo disse: "Era leproso". Seu filho Jotão foi seu sucessor.

'''

xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[Próximo Capítulo &#62;]