include::./index.adoc[]

[[v14-17-0]]
=== 2 Crônicas, 17
// nvt ?, NVT - Nova Versão Transformadora

[[v14-17-1]]

^<<v14-17-1,1>>^ Josafá, filho de Asa, foi seu sucessor. Ele fortaleceu Judá, para que pudesse resistir a Israel.

[[v14-17-2]]

^<<v14-17-2,2>>^ Colocou tropas em todas as cidades fortificadas de Judá e designou guarnições adicionais para a terra de Judá e para as cidades de Efraim que seu pai, Asa, havia conquistado.

[[v14-17-3]]

^<<v14-17-3,3>>^ O SENHOR esteve com Josafá, pois ele seguiu o exemplo dos primeiros anos de seu pai e não adorou as imagens de Baal.

[[v14-17-4]]

^<<v14-17-4,4>>^ Buscou o Deus de seu pai e obedeceu a seus mandamentos, em vez de seguir as práticas perversas do reino de Israel.

[[v14-17-5]]

^<<v14-17-5,5>>^ Por isso, o SENHOR estabeleceu o controle de Josafá sobre o reino de Judá. Todo o povo de Judá trazia tributos a Josafá, e ele se tornou muito rico e respeitado.

[[v14-17-6]]

^<<v14-17-6,6>>^ Comprometeu-se de coração a seguir os caminhos do SENHOR. Removeu de Judá os santuários idólatras e os postes de Aserá.

[[v14-17-7]]

^<<v14-17-7,7>>^ No terceiro ano de seu reinado, enviou seus oficiais Ben-Hail, Obadias, Zacarias, Natanael e Micaías para ensinarem em todas as cidades de Judá.

[[v14-17-8]]

^<<v14-17-8,8>>^ Com eles foram os levitas Semaías, Netanias, Zebadias, Asael, Semiramote, Jônatas, Adonias, Tobias e Tobe-Adonias e os sacerdotes Elisama e Jeorão.

[[v14-17-9]]

^<<v14-17-9,9>>^ Eles levaram consigo cópias do Livro da Lei do SENHOR e foram por todas as cidades de Judá, ensinando o povo.

[[v14-17-10]]

^<<v14-17-10,10>>^ Então o temor do SENHOR caiu sobre todos os reinos vizinhos, de modo que nenhum deles declarou guerra a Josafá.

[[v14-17-11]]

^<<v14-17-11,11>>^ Alguns filisteus trouxeram presentes e prata como tributo, e os árabes trouxeram 7.700 carneiros e 7.700 bodes.

[[v14-17-12]]

^<<v14-17-12,12>>^ Josafá se tornou cada vez mais poderoso e construiu fortalezas e cidades para servirem como centros de armazenamento em toda a terra de Judá.

[[v14-17-13]]

^<<v14-17-13,13>>^ Guardou muitos suprimentos nas cidades de Judá e colocou em Jerusalém um exército com guerreiros experientes.

[[v14-17-14]]

^<<v14-17-14,14>>^ Seu exército foi registrado de acordo com os clãs. De Judá havia 300 mil soldados organizados em grupos de mil, sob o comando de Adna.

[[v14-17-15]]

^<<v14-17-15,15>>^ Em seguida, vinha Joanã, que comandava 280 mil soldados.

[[v14-17-16]]

^<<v14-17-16,16>>^ Depois dele vinha Amazias, filho de Zicri, que se apresentou voluntariamente para o serviço do SENHOR e que comandava 200 mil soldados.

[[v14-17-17]]

^<<v14-17-17,17>>^ De Benjamim havia 200 mil soldados equipados com arcos e escudos. Seu comandante era Eliada, guerreiro experiente.

[[v14-17-18]]

^<<v14-17-18,18>>^ Em seguida, vinha Jozabade, que comandava 180 mil homens armados.

[[v14-17-19]]

^<<v14-17-19,19>>^ Essas eram as tropas que estavam à disposição do rei, além daquelas que ele havia colocado nas cidades fortificadas em toda a terra de Judá.

'''

xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[&#60; Capítulo Anterior] | <<v14-17-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[Próximo Capítulo &#62;]