include::./index.adoc[]

[[v14-11-0]]
=== 2 Crônicas, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v14-11-1]]

^<<v14-11-1,1>>^ Quando Roboão chegou a Jerusalém, mobilizou os homens das tribos de Judá e Benjamim, 180 mil dos melhores soldados, para guerrearem contra Israel e recuperarem o reino.

[[v14-11-2]]

^<<v14-11-2,2>>^ O SENHOR, porém, disse a Semaías, homem de Deus:

[[v14-11-3]]

^<<v14-11-3,3>>^ "Diga a Roboão, filho de Salomão, rei de Judá, e a todos os israelitas em Judá e Benjamim:

[[v14-11-4]]

^<<v14-11-4,4>>^ ‘Assim diz o SENHOR: Não lutem contra seus compatriotas. Voltem para casa, pois eu mesmo fiz isto acontecer!’". Eles obedeceram à palavra do SENHOR e não lutaram contra Jeroboão.

[[v14-11-5]]

^<<v14-11-5,5>>^ Roboão permaneceu em Jerusalém e fortificou várias cidades para defender Judá.

[[v14-11-6]]

^<<v14-11-6,6>>^ Fortificou Belém, Etã, Tecoa,

[[v14-11-7]]

^<<v14-11-7,7>>^ Bete-Zur, Socó, Adulão,

[[v14-11-8]]

^<<v14-11-8,8>>^ Gate, Maressa, Zife,

[[v14-11-9]]

^<<v14-11-9,9>>^ Adoraim, Laquis, Azeca,

[[v14-11-10]]

^<<v14-11-10,10>>^ Zorá, Aijalom e Hebrom. Essas cidades foram fortificadas em Judá e em Benjamim.

[[v14-11-11]]

^<<v14-11-11,11>>^ Roboão fortaleceu suas defesas, colocou nelas comandantes e armazenou provisões de alimento, azeite e vinho.

[[v14-11-12]]

^<<v14-11-12,12>>^ Também colocou nessas cidades escudos e lanças, fortalecendo-as ainda mais. Assim, apenas Judá e Benjamim permaneceram sob seu controle.

[[v14-11-13]]

^<<v14-11-13,13>>^ Todos os sacerdotes e levitas que moravam nas tribos do norte de Israel apoiaram Roboão.

[[v14-11-14]]

^<<v14-11-14,14>>^ Os levitas abandonaram suas pastagens e seus bens e se mudaram para Judá e Jerusalém, pois Jeroboão e seus filhos não permitiam que eles servissem ao SENHOR como sacerdotes.

[[v14-11-15]]

^<<v14-11-15,15>>^ Jeroboão nomeou seus próprios sacerdotes para servirem nos santuários idólatras, onde prestavam culto aos ídolos em forma de bodes e bezerros que ele havia feito.

[[v14-11-16]]

^<<v14-11-16,16>>^ De todas as tribos de Israel, aqueles que desejavam sinceramente adorar o SENHOR, o Deus de Israel, acompanharam os levitas até Jerusalém, onde podiam oferecer sacrifícios ao SENHOR, o Deus de seus antepassados.

[[v14-11-17]]

^<<v14-11-17,17>>^ Fortaleceram o reino de Judá e, durante três anos, apoiaram Roboão, filho de Salomão, pois durante esse tempo seguiram fielmente os passos de Davi e de Salomão.

[[v14-11-18]]

^<<v14-11-18,18>>^ Roboão se casou com sua prima Maalate, filha de Jerimote, filho de Davi. A mãe dela era Abiail, filha de Eliabe, filho de Jessé.

[[v14-11-19]]

^<<v14-11-19,19>>^ Maalate deu à luz três filhos: Jeús, Semarias e Zaão.

[[v14-11-20]]

^<<v14-11-20,20>>^ Depois Roboão se casou com Maaca, neta de Absalão. Maaca deu à luz Abias, Atai, Ziza e Selomite.

[[v14-11-21]]

^<<v14-11-21,21>>^ Roboão amava Maaca mais que a qualquer outra de suas esposas e concubinas. Ao todo, teve 18 esposas e 60 concubinas, que deram à luz 28 filhos e 60 filhas.

[[v14-11-22]]

^<<v14-11-22,22>>^ Roboão nomeou Abias, filho de Maaca, como líder entre seus irmãos e, desse modo, deixou claro que ele seria seu sucessor.

[[v14-11-23]]

^<<v14-11-23,23>>^ Com inteligência, espalhou os outros filhos por toda a terra de Judá e de Benjamim e por todas as cidades fortificadas. Deu-lhes grande quantidade de suprimentos e arranjou muitas esposas para eles.

'''

xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[&#60; Capítulo Anterior] | <<v14-11-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[Próximo Capítulo &#62;]