include::./index.adoc[]

[[v14-13-0]]
=== 2 Crônicas, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v14-13-1]]

^<<v14-13-1,1>>^ No décimo oitavo ano do reinado de Jeroboão em Israel, Abias começou a reinar em Judá.

[[v14-13-2]]

^<<v14-13-2,2>>^ Reinou por três anos em Jerusalém. Sua mãe se chamava Maaca e era filha de Uriel, de Gibeá. Houve guerra entre Abias e Jeroboão.

[[v14-13-3]]

^<<v14-13-3,3>>^ Judá, sob o comando do rei Abias, foi à batalha com quatrocentos mil de seus melhores soldados, e Jeroboão reuniu oitocentos mil dos melhores soldados de Israel.

[[v14-13-4]]

^<<v14-13-4,4>>^ Quando o exército de Judá chegou à região montanhosa de Efraim, Abias ficou em pé no alto do monte Zemaraim e gritou para Jeroboão e todo o Israel: "Ouçam-me!

[[v14-13-5]]

^<<v14-13-5,5>>^ Não sabem que o SENHOR, o Deus de Israel, fez uma aliança permanente com Davi e deu o trono de Israel a seus descendentes para sempre?

[[v14-13-6]]

^<<v14-13-6,6>>^ Mesmo assim, Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, rebelou-se contra seu senhor.

[[v14-13-7]]

^<<v14-13-7,7>>^ Homens desocupados e perversos se juntaram a ele e conspiraram contra Roboão, filho de Salomão, quando ele era jovem, inexperiente e incapaz de enfrentá-los.

[[v14-13-8]]

^<<v14-13-8,8>>^ "Vocês acreditam, de fato, que podem resistir ao reino do SENHOR, que ele entregou aos descendentes de Davi? Seu exército é enorme, e vocês têm os bezerros de ouro que Jeroboão fez para serem seus deuses.

[[v14-13-9]]

^<<v14-13-9,9>>^ No entanto, expulsaram os sacerdotes do SENHOR, descendentes de Arão, e os levitas e nomearam seus próprios sacerdotes, como fazem as outras nações. Qualquer um que se apresente com um novilho ou sete carneiros para ser consagrado pode se tornar sacerdote de seus falsos deuses!

[[v14-13-10]]

^<<v14-13-10,10>>^ "Quanto a nós, o SENHOR é nosso Deus, e não o abandonamos. Somente os descendentes de Arão servem ao SENHOR como sacerdotes, e somente os levitas os ajudam em seu trabalho.

[[v14-13-11]]

^<<v14-13-11,11>>^ Eles apresentam holocaustos e incenso aromático ao SENHOR todas as manhãs e todas as tardes. Colocam os pães da presença sobre a mesa sagrada e todas as tardes acendem o candelabro de ouro. Nós seguimos as instruções do SENHOR, nosso Deus, mas vocês o abandonaram.

[[v14-13-12]]

^<<v14-13-12,12>>^ Podem ver, portanto, que Deus está conosco. Ele é nosso líder. Os sacerdotes dele tocam as trombetas e nos conduzem à batalha contra vocês. Ó israelitas, não lutem contra o SENHOR, o Deus de seus antepassados, pois não serão bem-sucedidos!".

[[v14-13-13]]

^<<v14-13-13,13>>^ Enquanto isso, Jeroboão tinha mandado uma parte de seu exército dar a volta por trás do exército de Judá, formando uma emboscada.

[[v14-13-14]]

^<<v14-13-14,14>>^ Quando os homens de Judá perceberam que eram atacados pela frente e por trás, clamaram ao SENHOR. Então os sacerdotes tocaram as trombetas,

[[v14-13-15]]

^<<v14-13-15,15>>^ e os homens de Judá gritaram. Ao som desse brado de guerra, Deus derrotou Jeroboão e dispersou todo o Israel diante de Abias e do exército de Judá.

[[v14-13-16]]

^<<v14-13-16,16>>^ Os israelitas fugiram dos soldados de Judá, e Deus os entregou em suas mãos.

[[v14-13-17]]

^<<v14-13-17,17>>^ Abias e seu exército lhes infligiram grandes perdas; quinhentos mil dos melhores soldados de Israel foram mortos naquele dia.

[[v14-13-18]]

^<<v14-13-18,18>>^ Nessa ocasião, portanto, o exército de Judá derrotou os israelitas, pois confiou no SENHOR, o Deus de seus antepassados.

[[v14-13-19]]

^<<v14-13-19,19>>^ Abias e seu exército perseguiram os soldados de Jeroboão e conquistaram as cidades de Betel, Jesana e Efrom, e os povoados ao redor.

[[v14-13-20]]

^<<v14-13-20,20>>^ Jeroboão, rei de Israel, não recuperou seu poder enquanto Abias viveu; por fim, o SENHOR feriu Jeroboão, e ele morreu.

[[v14-13-21]]

^<<v14-13-21,21>>^ Enquanto isso, Abias de Judá se tornou cada vez mais poderoso. Casou-se com 14 mulheres e teve 22 filhos e 16 filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ Os demais acontecimentos do reinado de Abias, incluindo suas palavras e seus atos, estão registrados no Comentário do Profeta Ido .

'''

xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]