include::./index.adoc[]

[[v14-8-0]]
=== 2 Crônicas, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v14-8-1]]

^<<v14-8-1,1>>^ Salomão levou vinte anos para construir o templo do SENHOR e o palácio real. Depois desse tempo,

[[v14-8-2]]

^<<v14-8-2,2>>^ voltou sua atenção para a reconstrução das cidades que o rei Hirão lhe tinha dado e nelas estabeleceu israelitas.

[[v14-8-3]]

^<<v14-8-3,3>>^ Salomão também lutou contra a cidade de Hamate-Zobá e a conquistou.

[[v14-8-4]]

^<<v14-8-4,4>>^ Reconstruiu Tadmor, no deserto, e construiu na região de Hamate cidades para servirem como centros de armazenamento.

[[v14-8-5]]

^<<v14-8-5,5>>^ Fortificou as cidades de Bete-Horom Alta e Bete-Horom Baixa, reconstruindo seus muros e colocando portões com trancas.

[[v14-8-6]]

^<<v14-8-6,6>>^ Também reconstruiu Baalate e outros centros de armazenamento e construiu cidades para seus carros de guerra e cavalos. Construiu tudo que desejou em Jerusalém, no Líbano e em todo o reino.

[[v14-8-7]]

^<<v14-8-7,7>>^ Ainda havia na terra habitantes que não eram israelitas: hititas, amorreus, ferezeus, heveus e jebuseus.

[[v14-8-8]]

^<<v14-8-8,8>>^ Eram descendentes das nações que os israelitas não haviam destruído completamente. Salomão os recrutou para trabalhos forçados, e é nessa condição que trabalham até hoje.

[[v14-8-9]]

^<<v14-8-9,9>>^ Mas Salomão não recrutou nenhum israelita para trabalhos forçados; eles o serviram como soldados, oficiais de seu exército, comandantes de carros de guerra e cavaleiros.

[[v14-8-10]]

^<<v14-8-10,10>>^ Nomeou 250 oficiais para supervisionarem os trabalhadores.

[[v14-8-11]]

^<<v14-8-11,11>>^ Salomão transferiu a residência de sua esposa, a filha do faraó, da Cidade de Davi para o novo palácio que ele havia construído para ela. Disse: "Minha esposa não deve morar no palácio de Davi, rei de Israel, pois a arca do SENHOR esteve ali, e é lugar sagrado".

[[v14-8-12]]

^<<v14-8-12,12>>^ Depois, Salomão ofereceu holocaustos ao SENHOR sobre o altar que havia construído para ele diante da sala de entrada do templo.

[[v14-8-13]]

^<<v14-8-13,13>>^ Conforme Moisés havia ordenado, oferecia sacrifícios aos sábados, nas festas de lua nova e nas três festas anuais: a Páscoa, a Festa da Colheita e a Festa das Cabanas.

[[v14-8-14]]

^<<v14-8-14,14>>^ Segundo as instruções de seu pai, Davi, designou os turnos dos sacerdotes. Também encarregou os levitas de dirigirem o louvor e ajudarem os sacerdotes em suas responsabilidades diárias. Designou, por divisões, os guardas das portas, de acordo com as ordens de Davi, homem de Deus.

[[v14-8-15]]

^<<v14-8-15,15>>^ Todas as ordens de Davi com respeito aos sacerdotes, aos levitas e aos tesouros foram cumpridas à risca.

[[v14-8-16]]

^<<v14-8-16,16>>^ Salomão certificou-se de que fosse realizado todo o trabalho relacionado à construção do templo do SENHOR, desde o dia em que foram lançados os alicerces até a conclusão das obras.

[[v14-8-17]]

^<<v14-8-17,17>>^ Por fim, Salomão foi a Eziom-Geber e a Elate, portos às margens do mar Vermelho, na terra de Edom.

[[v14-8-18]]

^<<v14-8-18,18>>^ Hirão lhe enviou embarcações comandadas por seus próprios oficiais, com uma tripulação de marinheiros experientes. Essas embarcações navegaram com os marinheiros de Salomão para Ofir e trouxeram de volta para o rei Salomão 15.750 quilos de ouro.

'''

xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[&#60; Capítulo Anterior] | <<v14-8-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[Próximo Capítulo &#62;]