include::./index.adoc[]

[[v14-22-0]]
=== 2 Crônicas, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v14-22-1]]

^<<v14-22-1,1>>^ Então o povo de Jerusalém proclamou Acazias, filho mais novo de Jeorão, o novo rei, pois os bandos de saqueadores que vieram com os árabes tinham matado todos os filhos mais velhos de Jeorão. Assim, Acazias, filho de Jeorão, reinou em Judá.

[[v14-22-2]]

^<<v14-22-2,2>>^ Acazias tinha 22 anos quando começou a reinar, e reinou em Jerusalém por um ano. Sua mãe era Atalia, neta do rei Onri.

[[v14-22-3]]

^<<v14-22-3,3>>^ Acazias também seguiu o exemplo da família do rei Acabe, pois sua mãe o incentivou a praticar o mal.

[[v14-22-4]]

^<<v14-22-4,4>>^ Fez o que era mau aos olhos do SENHOR, como a família de Acabe. Depois da morte de seu pai, eles se tornaram seus conselheiros e o levaram à ruína.

[[v14-22-5]]

^<<v14-22-5,5>>^ Seguindo o conselho deles, Acazias se uniu a Jorão, filho de Acabe, rei de Israel, na guerra contra Hazael, rei da Síria, em Ramote-Gileade. Quando os sírios feriram Jorão na batalha,

[[v14-22-6]]

^<<v14-22-6,6>>^ ele voltou a Jezreel para se recuperar dos ferimentos sofridos em Ramote. Visto que Jorão estava ferido, Acazias, rei de Judá, foi visitá-lo em Jezreel.

[[v14-22-7]]

^<<v14-22-7,7>>^ Deus havia decidido que essa visita seria a ruína de Acazias. Enquanto Acazias estava em Jezreel, saiu com Jorão ao encontro de Jeú, neto de Ninsi, a quem o SENHOR havia escolhido para destruir a dinastia de Acabe.

[[v14-22-8]]

^<<v14-22-8,8>>^ Quando Jeú executava o juízo contra a família de Acabe, encontrou alguns oficiais de Judá e parentes de Acazias que o serviam, e os matou.

[[v14-22-9]]

^<<v14-22-9,9>>^ Então os homens de Jeú partiram em busca de Acazias e o encontraram escondido na cidade de Samaria. Eles o trouxeram a Jeú e o mataram. Acazias recebeu um sepultamento digno, pois o povo disse: "Ele era neto de Josafá, homem que buscou o SENHOR de todo o coração". Contudo, nenhum dos membros da família de Acazias que sobreviveram conseguiu reinar em seu lugar.

[[v14-22-10]]

^<<v14-22-10,10>>^ Quando Atalia, mãe de Acazias, rei de Judá, soube que seu filho estava morto, mandou exterminar o restante da família real de Judá.

[[v14-22-11]]

^<<v14-22-11,11>>^ Mas Jeoseba, filha do rei Jeorão, pegou Joás, o filho ainda pequeno de Acazias, dentre os outros filhos do rei que estavam para ser mortos, e o colocou num quarto com sua ama. Assim, Jeoseba, esposa do sacerdote Joiada e irmã de Acazias, escondeu o menino para que Atalia não o matasse.

[[v14-22-12]]

^<<v14-22-12,12>>^ Joás ficou escondido com eles no templo de Deus durante seis anos, enquanto Atalia governava o país.

'''

xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[&#60; Capítulo Anterior] | <<v14-22-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[Próximo Capítulo &#62;]