include::./index.adoc[]

[[v14-34-0]]
=== 2 Crônicas, 34
// nvt ?, NVT - Nova Versão Transformadora

[[v14-34-1]]

^<<v14-34-1,1>>^ Josias tinha 8 anos quando começou a reinar, e reinou em Jerusalém por 31 anos.

[[v14-34-2]]

^<<v14-34-2,2>>^ Fez o que era certo aos olhos do SENHOR e seguiu o exemplo de seu antepassado Davi, não se desviando nem para um lado nem para o outro.

[[v14-34-3]]

^<<v14-34-3,3>>^ No oitavo ano de seu reinado, enquanto ainda era jovem, começou a buscar o Deus de seu antepassado Davi. Então, no décimo segundo ano, começou a purificar Judá e Jerusalém, destruindo os santuários idólatras, os postes de Aserá, os ídolos esculpidos e as imagens de metal.

[[v14-34-4]]

^<<v14-34-4,4>>^ Deu ordens para que fossem destruídos os altares de Baal e despedaçados os altares de incenso que ficavam acima deles. Também ordenou que os postes de Aserá, os ídolos esculpidos e as imagens de metal fossem despedaçados e espalhados sobre os túmulos daqueles que lhes haviam oferecido sacrifícios.

[[v14-34-5]]

^<<v14-34-5,5>>^ Queimou os ossos dos sacerdotes idólatras sobre seus próprios altares e, com isso, purificou Judá e Jerusalém.

[[v14-34-6]]

^<<v14-34-6,6>>^ Fez a mesma coisa nas cidades de Manassés, Efraim e Simeão, e até na distante Naftali, bem como nas ruínas ao seu redor.

[[v14-34-7]]

^<<v14-34-7,7>>^ Destruiu os santuários idólatras e os postes de Aserá, reduziu os ídolos a pó e despedaçou todos os altares de incenso em toda a terra de Israel. Por fim, voltou a Jerusalém.

[[v14-34-8]]

^<<v14-34-8,8>>^ No décimo oitavo ano do reinado de Josias, depois de ele purificar a terra e o templo, nomeou Safã, filho de Azalias, Maaseias, governador de Jerusalém, e Joá, filho de Joacaz, o historiador do reino, para restaurarem o templo do SENHOR, seu Deus.

[[v14-34-9]]

^<<v14-34-9,9>>^ Eles entregaram ao sumo sacerdote Hilquias a prata recolhida pelos levitas que guardavam as portas do templo de Deus. As ofertas foram trazidas pelo povo de Manassés, de Efraim e de todo o remanescente de Israel, bem como de Judá e de Benjamim, e pelos habitantes de Jerusalém.

[[v14-34-10]]

^<<v14-34-10,10>>^ Hilquias e os outros líderes entregaram a prata aos homens encarregados de supervisionar a reforma do templo do SENHOR. Eles pagaram os trabalhadores que faziam os reparos e a restauração do templo.

[[v14-34-11]]

^<<v14-34-11,11>>^ Também contrataram carpinteiros e construtores que compraram pedras cortadas para as paredes e madeira para os suportes e as vigas. Restauraram aquilo que reis anteriores de Judá haviam deixado ficar em ruínas.

[[v14-34-12]]

^<<v14-34-12,12>>^ Os trabalhadores realizaram a obra com fidelidade, sob a liderança de Jaate e Obadias, levitas do clã de Merari, e de Zacarias e Mesulão, levitas do clã de Coate. Outros levitas, todos músicos talentosos,

[[v14-34-13]]

^<<v14-34-13,13>>^ ficaram responsáveis pelos carregadores e pelos trabalhadores em várias funções. Ainda outros auxiliavam como secretários, oficiais e guardas das portas.

[[v14-34-14]]

^<<v14-34-14,14>>^ Enquanto estavam retirando a prata recolhida no templo do SENHOR, o sacerdote Hilquias encontrou o Livro da Lei do SENHOR, escrito por Moisés.

[[v14-34-15]]

^<<v14-34-15,15>>^ Hilquias disse a Safã, secretário da corte: "Encontrei o Livro da Lei no templo do SENHOR!". E Hilquias entregou o livro a Safã.

[[v14-34-16]]

^<<v14-34-16,16>>^ Safã levou o livro ao rei e relatou: "Seus oficiais estão fazendo tudo que lhes foi ordenado.

[[v14-34-17]]

^<<v14-34-17,17>>^ A prata recolhida no templo do SENHOR foi entregue aos supervisores e trabalhadores".

[[v14-34-18]]

^<<v14-34-18,18>>^ Safã também disse ao rei: "O sacerdote Hilquias me entregou um livro". E Safã leu o livro para o rei.

[[v14-34-19]]

^<<v14-34-19,19>>^ Quando o rei ouviu o que estava escrito na Lei, rasgou suas roupas.

[[v14-34-20]]

^<<v14-34-20,20>>^ Em seguida, deu estas ordens a Hilquias, a Aicam, filho de Safã, a Acbor, filho de Micaías, a Safã, secretário da corte, e a Asaías, conselheiro pessoal do rei:

[[v14-34-21]]

^<<v14-34-21,21>>^ "Vão consultar o SENHOR por mim e por todo o remanescente de Israel e de Judá. Perguntem a respeito das palavras escritas no livro que foi encontrado. A grande ira do SENHOR foi derramada sobre nós, pois nossos antepassados não obedeceram à palavra do SENHOR. Não temos feito o que este livro ordena".

[[v14-34-22]]

^<<v14-34-22,22>>^ Então Hilquias e os outros homens foram ao Bairro Novo de Jerusalém consultar a profetisa Hulda. Ela era esposa de Salum, filho de Tocate, filho de Harás, responsável pelo guarda-roupa do templo.

[[v14-34-23]]

^<<v14-34-23,23>>^ Ela lhes disse: "O SENHOR, o Deus de Israel, falou! Voltem e digam ao homem que os enviou

[[v14-34-24]]

^<<v14-34-24,24>>^ que assim diz o SENHOR: ‘Trarei desgraça sobre esta cidade e sobre seus habitantes. Todas as maldições escritas no livro que foi lido para o rei de Judá se cumprirão.

[[v14-34-25]]

^<<v14-34-25,25>>^ Pois o meu povo me abandonou e queimou incenso a outros deuses, e estou grandemente irado com eles por tudo que fizeram. Minha ira será derramada sobre este lugar e não será apagada’.

[[v14-34-26]]

^<<v14-34-26,26>>^ "Mas vão ao rei de Judá que os enviou para consultarem o SENHOR e digam-lhe que assim diz o SENHOR, o Deus de Israel, a respeito da mensagem que acabaram de ouvir:

[[v14-34-27]]

^<<v14-34-27,27>>^ ‘Você se arrependeu e se humilhou diante de Deus quando ouviu as palavras dele contra esta cidade e contra seus habitantes. Você se humilhou, rasgou suas roupas e chorou diante de mim. E eu certamente o ouvi, diz o SENHOR.

[[v14-34-28]]

^<<v14-34-28,28>>^ Portanto, só enviarei a calamidade anunciada depois que você tiver se reunido a seus antepassados e tiver sido sepultado em paz. Você não verá a desgraça que trarei sobre esta cidade e sobre seus habitantes’". Então eles levaram a mensagem ao rei.

[[v14-34-29]]

^<<v14-34-29,29>>^ Josias mandou chamar todas as autoridades de Judá e de Jerusalém.

[[v14-34-30]]

^<<v14-34-30,30>>^ Subiu ao templo do SENHOR com os sacerdotes e os levitas e com todo o povo de Judá e de Jerusalém, dos mais importantes até os mais simples. Leu para eles todo o Livro da Aliança encontrado no templo do SENHOR.

[[v14-34-31]]

^<<v14-34-31,31>>^ O rei tomou seu lugar de honra junto à coluna e renovou a aliança na presença do SENHOR. Comprometeu-se a obedecer ao SENHOR e a cumprir seus mandamentos, preceitos e decretos de todo o coração e de toda a alma. Prometeu cumprir todos os termos da aliança escritos no livro.

[[v14-34-32]]

^<<v14-34-32,32>>^ Exigiu o mesmo de todos em Jerusalém e do povo de Benjamim. Os habitantes de Jerusalém fizeram essa promessa e renovaram sua aliança com Deus, o Deus de seus antepassados.

[[v14-34-33]]

^<<v14-34-33,33>>^ Josias removeu todos os ídolos repulsivos de toda a terra de Israel e exigiu que todos adorassem o SENHOR, seu Deus. E, pelo restante da vida do rei, eles não se afastaram do SENHOR, o Deus de seus antepassados.

'''

xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[&#60; Capítulo Anterior] | <<v14-34-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[Próximo Capítulo &#62;]