include::./index.adoc[]

[[v14-2-0]]
=== 2 Crônicas, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v14-2-1]]

^<<v14-2-1,1>>^ Salomão resolveu construir um templo em honra ao nome do SENHOR, e um palácio para si próprio.

[[v14-2-2]]

^<<v14-2-2,2>>^ Convocou 70.000 carregadores, 80.000 homens para cortarem pedras na região montanhosa e 3.600 chefes para supervisionarem as obras.

[[v14-2-3]]

^<<v14-2-3,3>>^ Salomão enviou a seguinte mensagem a Hirão, rei de Tiro: "Peço que me forneça madeira de cedro, como fez com meu pai, Davi, quando ele construiu seu palácio.

[[v14-2-4]]

^<<v14-2-4,4>>^ Estou para construir um templo em honra ao nome do SENHOR, meu Deus. Será um lugar consagrado para queimar incenso aromático diante dele, para apresentar os pães da presença e para oferecer holocaustos todas as manhãs e todas as tardes, nos sábados, nas luas novas e nas festas fixas estabelecidas pelo SENHOR, nosso Deus. Ele ordenou que Israel fizesse isso para sempre.

[[v14-2-5]]

^<<v14-2-5,5>>^ "O templo que vou construir será imponente, pois nosso Deus é maior que todos os outros deuses.

[[v14-2-6]]

^<<v14-2-6,6>>^ Contudo, quem poderia construir uma casa digna dele? Nem mesmo os mais altos céus seriam capazes de contê-lo! E quem sou eu para pensar em construir um templo para ele, a não ser como lugar para queimar sacrifícios diante dele?

[[v14-2-7]]

^<<v14-2-7,7>>^ "Portanto, envie-me um mestre artífice competente, que saiba trabalhar com ouro, prata, bronze, ferro, com tecido púrpura, vermelho e azul, que seja habilidoso para fazer entalhes e que trabalhe com os artífices de Judá e Jerusalém que meu pai, Davi, escolheu.

[[v14-2-8]]

^<<v14-2-8,8>>^ "Mande-me, também, madeira de cedro, cipreste e sândalo do Líbano, pois sei que ninguém no Líbano corta madeira como seus servos. Enviarei meus servos para ajudá-los.

[[v14-2-9]]

^<<v14-2-9,9>>^ Será necessária muita madeira, pois o templo que vou construir será grande e imponente.

[[v14-2-10]]

^<<v14-2-10,10>>^ Como pagamento a seus cortadores de madeira, enviarei vinte mil cestos grandes de trigo batido, vinte mil cestos grandes de cevada, vinte mil tonéis de vinho e vinte mil tonéis de azeite".

[[v14-2-11]]

^<<v14-2-11,11>>^ Hirão, rei de Tiro, enviou esta resposta a Salomão: "O SENHOR ama seu povo, por isso o fez rei sobre ele!

[[v14-2-12]]

^<<v14-2-12,12>>^ Louvado seja o SENHOR, o Deus de Israel, que criou os céus e a terra! Ele deu ao rei Davi um filho sábio, que tem inteligência e entendimento, e que construirá um templo para o SENHOR e um palácio para si próprio.

[[v14-2-13]]

^<<v14-2-13,13>>^ "Envio-lhe Hurão-Abi, mestre artífice muito talentoso.

[[v14-2-14]]

^<<v14-2-14,14>>^ Sua mãe é da tribo de Dã, em Israel, e seu pai é de Tiro. Ele tem habilidade para trabalhar com ouro, prata, bronze e ferro, e também com pedra, madeira, tecido púrpura, vermelho e azul e linho fino. É habilidoso para fazer entalhes e capaz de executar qualquer projeto que você lhe der. Ele trabalhará com seus artífices e com os homens indicados por meu senhor Davi, seu pai.

[[v14-2-15]]

^<<v14-2-15,15>>^ "Agora, envie o trigo, a cevada, o azeite e o vinho, conforme meu senhor mencionou.

[[v14-2-16]]

^<<v14-2-16,16>>^ Cortaremos toda a madeira necessária das montanhas do Líbano, colocaremos as toras em balsas e as faremos flutuar ao longo da costa do mar Mediterrâneo até Jope. Dali você as transportará até Jerusalém".

[[v14-2-17]]

^<<v14-2-17,17>>^ Salomão fez um censo de todos os estrangeiros na terra de Israel, como o censo que seu pai, Davi, havia feito, e descobriu que eram 153.600.

[[v14-2-18]]

^<<v14-2-18,18>>^ Designou 70.000 deles como carregadores, 80.000 como cortadores de pedra na região montanhosa e 3.600 como chefes para supervisionar a obra.

'''

xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[&#60; Capítulo Anterior] | <<v14-2-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[Próximo Capítulo &#62;]