include::./index.adoc[]

[[v14-24-0]]
=== 2 Crônicas, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v14-24-1]]

^<<v14-24-1,1>>^ Joás tinha 7 anos quando começou a reinar, e reinou em Jerusalém por quarenta anos. Sua mãe se chamava Zíbia e era de Berseba.

[[v14-24-2]]

^<<v14-24-2,2>>^ Joás fez o que era certo aos olhos do SENHOR enquanto o sacerdote Joiada estava vivo.

[[v14-24-3]]

^<<v14-24-3,3>>^ Joiada escolheu duas esposas para Joás, e ele teve filhos e filhas.

[[v14-24-4]]

^<<v14-24-4,4>>^ Algum tempo depois, Joás resolveu fazer reparos no templo do SENHOR.

[[v14-24-5]]

^<<v14-24-5,5>>^ Reuniu os sacerdotes e os levitas e lhes deu as seguintes instruções: "Vão a todas as cidades de Judá e recolham o imposto anual para fazer os reparos no templo do SENHOR. Façam isso logo!". Os levitas, porém, não se apressaram.

[[v14-24-6]]

^<<v14-24-6,6>>^ Então o rei mandou chamar o sumo sacerdote Joiada e lhe perguntou: "Por que você não exigiu que os levitas saíssem e recolhessem os impostos que as cidades de Judá e a cidade de Jerusalém devem pagar para o templo? Moisés, servo do SENHOR, estabeleceu que a comunidade de Israel pagasse esse imposto para a manutenção do tabernáculo da aliança".

[[v14-24-7]]

^<<v14-24-7,7>>^ Ao longo dos anos, os seguidores da perversa Atalia haviam arrombado o templo de Deus e usado os objetos sagrados do templo do SENHOR para adorar as imagens de Baal.

[[v14-24-8]]

^<<v14-24-8,8>>^ Por isso, o rei ordenou que fizessem uma caixa grande e a colocassem do lado de fora da porta do templo do SENHOR.

[[v14-24-9]]

^<<v14-24-9,9>>^ Então foi proclamado em Judá e em Jerusalém que o povo devia trazer ao SENHOR o imposto que Moisés, servo de Deus, havia requerido dos israelitas no deserto.

[[v14-24-10]]

^<<v14-24-10,10>>^ Isso agradou todos os líderes e o povo, e eles trouxeram de bom grado suas contribuições e as colocaram na caixa até enchê-la.

[[v14-24-11]]

^<<v14-24-11,11>>^ Sempre que a caixa ficava cheia, os levitas a levavam aos oficiais do rei. O secretário da corte e um oficial do sumo sacerdote a esvaziavam e a levavam de volta ao templo. Assim faziam diariamente e reuniram muitos recursos.

[[v14-24-12]]

^<<v14-24-12,12>>^ O rei e Joiada entregavam o valor aos supervisores da construção, que contratavam pedreiros, carpinteiros e artífices que trabalhavam com ferro e bronze para reformar o templo do SENHOR.

[[v14-24-13]]

^<<v14-24-13,13>>^ Os homens encarregados da reforma trabalhavam com dedicação, e a obra foi progredindo. Restauraram o templo de Deus de acordo com o modelo original e o reforçaram.

[[v14-24-14]]

^<<v14-24-14,14>>^ Quando todos os reparos foram concluídos, trouxeram ao rei e a Joiada os recursos que sobraram. O valor foi usado para fazer diversos objetos para o templo do SENHOR, utensílios para o serviço e para os holocaustos, além de vasilhas e outros objetos de ouro e de prata. Enquanto o sacerdote Joiada viveu, os holocaustos eram oferecidos continuamente no templo do SENHOR.

[[v14-24-15]]

^<<v14-24-15,15>>^ Joiada viveu muitos anos e morreu em idade avançada, com 130 anos.

[[v14-24-16]]

^<<v14-24-16,16>>^ Foi sepultado entre os reis na Cidade de Davi, pois havia feito o bem em Israel para Deus e seu templo.

[[v14-24-17]]

^<<v14-24-17,17>>^ Depois da morte de Joiada, os líderes de Judá vieram ao rei Joás e se curvaram diante dele, e ele ouviu seus conselhos.

[[v14-24-18]]

^<<v14-24-18,18>>^ Abandonaram o templo do SENHOR, o Deus de seus antepassados, e adoraram postes de Aserá e ídolos. Por causa desse pecado, a ira de Deus veio sobre Judá e Jerusalém.

[[v14-24-19]]

^<<v14-24-19,19>>^ Ainda assim, o SENHOR enviou profetas para trazê-los de volta para ele. Os profetas os advertiram, mas o povo não quis ouvir.

[[v14-24-20]]

^<<v14-24-20,20>>^ Então o Espírito de Deus veio sobre Zacarias, filho do sacerdote Joiada. Ele se pôs em pé diante do povo e disse: "Isto é o que Deus diz: ‘Por que vocês desobedecem aos mandamentos do SENHOR e, com isso, deixam de prosperar? Visto que abandonaram o SENHOR, agora ele os abandonou!’".

[[v14-24-21]]

^<<v14-24-21,21>>^ Então os líderes conspiraram contra Zacarias, e o rei ordenou que ele fosse morto por apedrejamento no pátio do templo do SENHOR.

[[v14-24-22]]

^<<v14-24-22,22>>^ O rei Joás não levou em conta a lealdade que Joiada, pai de Zacarias, lhe havia demonstrado, e matou seu filho. As últimas palavras de Zacarias antes de morrer foram: "Que o SENHOR veja o que estão fazendo e vingue a minha morte!".

[[v14-24-23]]

^<<v14-24-23,23>>^ Na virada do ano, o exército sírio marchou contra Joás. Invadiram Judá e Jerusalém e mataram todos os líderes do povo. Enviaram para seu rei em Damasco tudo que haviam saqueado.

[[v14-24-24]]

^<<v14-24-24,24>>^ Embora os sírios tivessem atacado com apenas um exército pequeno, o SENHOR entregou em suas mãos o exército muito maior de Judá. O povo de Judá havia abandonado o SENHOR, o Deus de seus antepassados, por isso o juízo foi executado contra Joás.

[[v14-24-25]]

^<<v14-24-25,25>>^ Os sírios se retiraram e deixaram Joás gravemente ferido. Seus próprios oficiais conspiraram contra ele porque havia assassinado o filho do sacerdote Joiada e o mataram em sua cama. Ele foi sepultado na Cidade de Davi, mas não no cemitério dos reis.

[[v14-24-26]]

^<<v14-24-26,26>>^ Os assassinos foram Jozacar, filho de uma amonita chamada Simeate, e Jeozabade, filho de uma moabita chamada Somer.

[[v14-24-27]]

^<<v14-24-27,27>>^ O relato sobre os filhos de Joás, as muitas profecias a respeito dele e o registro da reforma do templo de Deus estão registrados no Comentário sobre o Livro dos Reis . Seu filho Amazias foi seu sucessor.

'''

xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[&#60; Capítulo Anterior] | <<v14-24-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[Próximo Capítulo &#62;]