include::./index.adoc[]

[[v14-35-0]]
=== 2 Crônicas, 35
// nvt ?, NVT - Nova Versão Transformadora

[[v14-35-1]]

^<<v14-35-1,1>>^ Então Josias celebrou a Páscoa do SENHOR em Jerusalém, e assim o cordeiro pascal foi abatido no décimo quarto dia do primeiro mês.

[[v14-35-2]]

^<<v14-35-2,2>>^ Josias também nomeou os sacerdotes para suas atribuições e os encorajou a realizar seu trabalho no templo do SENHOR.

[[v14-35-3]]

^<<v14-35-3,3>>^ Deu a seguinte ordem aos levitas encarregados de instruir todo o Israel e consagrados para servir ao SENHOR: "Coloquem a arca sagrada no templo construído por Salomão, filho de Davi, rei de Israel. Não precisam mais levá-la de um lado para outro sobre os ombros. Agora, dediquem seu tempo a servir ao SENHOR, seu Deus, e a seu povo, Israel.

[[v14-35-4]]

^<<v14-35-4,4>>^ Apresentem-se para o serviço de acordo com as divisões de seus antepassados por famílias, conforme as instruções de Davi, rei de Israel, e de seu filho Salomão.

[[v14-35-5]]

^<<v14-35-5,5>>^ "Fiquem no santuário, no lugar indicado para cada divisão, e ajudem as famílias das quais foram encarregados quando elas trouxerem suas ofertas ao templo.

[[v14-35-6]]

^<<v14-35-6,6>>^ Abatam os cordeiros pascais, consagrem-se e preparem-se para ajudar os que chegarem. Sigam todas as instruções que o SENHOR deu por meio de Moisés".

[[v14-35-7]]

^<<v14-35-7,7>>^ Então Josias deu ao povo 30.000 cordeiros e cabritos para as ofertas de Páscoa, além de 3.000 bois, todos dos rebanhos e do gado do rei.

[[v14-35-8]]

^<<v14-35-8,8>>^ Os oficiais do rei também deram contribuições voluntárias para o povo, para os sacerdotes e para os levitas. Hilquias, Zacarias e Jeiel, os chefes do templo de Deus, deram aos sacerdotes 2.600 cordeiros e cabritos e 300 bois como ofertas de Páscoa.

[[v14-35-9]]

^<<v14-35-9,9>>^ Os líderes dos levitas — Conanias e seus irmãos Semaías e Natanael, bem como Hasabias, Jeiel e Jozabade — deram 5.000 cordeiros e cabritos e 500 bois aos levitas para suas ofertas de Páscoa.

[[v14-35-10]]

^<<v14-35-10,10>>^ Quando tudo estava pronto para a comemoração da Páscoa, os sacerdotes e os levitas tomaram seus lugares, organizados de acordo com suas divisões, conforme o rei havia ordenado.

[[v14-35-11]]

^<<v14-35-11,11>>^ Então os levitas abateram os cordeiros da Páscoa e apresentaram o sangue aos sacerdotes, que o aspergiram sobre o altar enquanto os levitas preparavam os animais.

[[v14-35-12]]

^<<v14-35-12,12>>^ Repartiram os holocaustos entre o povo de acordo com suas divisões, para que as famílias os oferecessem ao SENHOR conforme prescrito no Livro de Moisés, e fizeram o mesmo com os bois.

[[v14-35-13]]

^<<v14-35-13,13>>^ Assaram os cordeiros da Páscoa, como prescrito, cozinharam as ofertas sagradas em potes, caldeirões e panelas e os levaram depressa ao povo.

[[v14-35-14]]

^<<v14-35-14,14>>^ Em seguida, os levitas prepararam as ofertas de Páscoa para si mesmos e para os sacerdotes, os descendentes de Arão, pois os sacerdotes haviam ficado ocupados desde a manhã até a noite, oferecendo os holocaustos e as porções de gordura. Os levitas se encarregaram de todos os preparativos.

[[v14-35-15]]

^<<v14-35-15,15>>^ Os músicos, descendentes de Asafe, estavam em seus lugares, segundo as ordens de Davi, Asafe, Hemã e Jedutum, vidente do rei. Os guardas das portas não precisaram deixar seus postos, pois seus parentes, os levitas, também lhes prepararam as ofertas de Páscoa.

[[v14-35-16]]

^<<v14-35-16,16>>^ Toda a cerimônia para a Páscoa do SENHOR foi realizada naquele dia. Os holocaustos foram sacrificados no altar do SENHOR, como o rei Josias havia ordenado.

[[v14-35-17]]

^<<v14-35-17,17>>^ Todos os israelitas presentes em Jerusalém celebraram a Páscoa e a Festa dos Pães sem Fermento por sete dias.

[[v14-35-18]]

^<<v14-35-18,18>>^ A Páscoa não havia sido celebrada dessa maneira desde o tempo do profeta Samuel. Nenhum dos reis de Israel havia comemorado a Páscoa como o rei Josias, com todos os sacerdotes e os levitas, os habitantes de Jerusalém e o povo de todo o Judá e Israel que estavam presentes na cidade.

[[v14-35-19]]

^<<v14-35-19,19>>^ Essa comemoração de Páscoa ocorreu no décimo oitavo ano do reinado de Josias.

[[v14-35-20]]

^<<v14-35-20,20>>^ Depois que Josias terminou de restaurar o templo, Neco, rei do Egito, levou seu exército para Carquemis, junto ao rio Eufrates, e Josias e seu exército saíram para lutar contra ele.

[[v14-35-21]]

^<<v14-35-21,21>>^ O rei Neco, porém, enviou mensageiros a Josias para lhe dizer: "O que quer comigo, rei de Judá? Hoje não tenho nada contra você! Estou a caminho da batalha contra outra nação, e Deus ordenou que eu me apressasse! Não interfira com Deus, que está comigo, ou ele o destruirá".

[[v14-35-22]]

^<<v14-35-22,22>>^ Josias, porém, não deu ouvidos às palavras de Neco, que ele havia falado a mando de Deus, e não quis voltar atrás. Em vez disso, disfarçou-se e levou seu exército para a batalha na planície de Megido.

[[v14-35-23]]

^<<v14-35-23,23>>^ Arqueiros do inimigo atingiram o rei Josias com suas flechas, e ele gritou para seus homens: "Tirem-me da batalha, pois estou gravemente ferido!".

[[v14-35-24]]

^<<v14-35-24,24>>^ Então tiraram Josias de sua carruagem e o colocaram em outra. Levaram-no de volta para Jerusalém, onde morreu e foi sepultado no cemitério dos reis. Todo o Judá e Jerusalém lamentaram por ele.

[[v14-35-25]]

^<<v14-35-25,25>>^ O profeta Jeremias compôs cânticos fúnebres em homenagem a Josias, e até hoje os cantores e cantoras ainda entoam esses lamentos sobre sua morte. Eles se tornaram uma tradição e estão registrados no Livro das Lamentações .

[[v14-35-26]]

^<<v14-35-26,26>>^ Os demais acontecimentos do reinado de Josias e seus atos de devoção, realizados de acordo com a lei do SENHOR,

[[v14-35-27]]

^<<v14-35-27,27>>^ do início ao fim, estão registrados no Livro dos Reis de Israel e de Judá .

'''

xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[&#60; Capítulo Anterior] | <<v14-35-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[Próximo Capítulo &#62;]