include::./index.adoc[]

[[v14-28-0]]
=== 2 Crônicas, 28
// nvt ?, NVT - Nova Versão Transformadora

[[v14-28-1]]

^<<v14-28-1,1>>^ Acaz tinha 20 anos quando começou a reinar, e reinou em Jerusalém por dezesseis anos. Ao contrário de seu antepassado Davi, não fez o que era certo aos olhos do SENHOR.

[[v14-28-2]]

^<<v14-28-2,2>>^ Em vez disso, seguiu o exemplo dos reis de Israel. Fez ídolos de metal para adorar Baal,

[[v14-28-3]]

^<<v14-28-3,3>>^ queimou incenso no vale de Ben-Hinom e chegou a sacrificar os próprios filhos no fogo. Desse modo, seguiu as práticas detestáveis das nações que o SENHOR havia expulsado da terra diante dos israelitas.

[[v14-28-4]]

^<<v14-28-4,4>>^ Ofereceu sacrifícios e queimou incenso nos santuários idólatras, nos montes e debaixo de toda árvore verdejante.

[[v14-28-5]]

^<<v14-28-5,5>>^ Por isso, o SENHOR, seu Deus, entregou Acaz nas mãos do rei da Síria, que o derrotou e levou muitos de seu povo para o exílio em Damasco. Também o entregou nas mãos do rei de Israel, que derrotou Acaz e matou muitos de seus soldados.

[[v14-28-6]]

^<<v14-28-6,6>>^ Em um só dia, Peca, filho de Remalias, matou 120 mil soldados de Judá, todos guerreiros experientes, pois haviam abandonado o SENHOR, o Deus de seus antepassados.

[[v14-28-7]]

^<<v14-28-7,7>>^ Então Zicri, um guerreiro de Efraim, matou Maaseias, filho do rei, Azricão, oficial encarregado do palácio do rei, e Elcana, o segundo no comando depois do rei.

[[v14-28-8]]

^<<v14-28-8,8>>^ Os soldados de Israel capturaram duzentas mil mulheres e crianças de Judá e tomaram enormes quantidades de despojos, que levaram para Samaria.

[[v14-28-9]]

^<<v14-28-9,9>>^ Odede, profeta do SENHOR, estava em Samaria quando o exército de Israel voltou. Saiu ao encontro deles e lhes disse: "O SENHOR, o Deus de seus antepassados, estava irado com Judá e o entregou em suas mãos, mas vocês foram longe demais e os mataram com fúria que chegou até os céus.

[[v14-28-10]]

^<<v14-28-10,10>>^ Agora, pretendem escravizar esse povo de Judá e de Jerusalém. E quanto a seus próprios pecados contra o SENHOR, seu Deus?

[[v14-28-11]]

^<<v14-28-11,11>>^ Ouçam-me e mandem de volta esses prisioneiros que vocês capturaram, pois são seus parentes. Tenham cuidado, pois a ira ardente do SENHOR se voltou contra vocês!".

[[v14-28-12]]

^<<v14-28-12,12>>^ Então alguns dos líderes de Israel — Azarias, filho de Joanã, Berequias, filho de Mesilemote, Jeizquias, filho de Salum, e Amasa, filho de Hadlai — confrontaram os homens que voltavam da batalha.

[[v14-28-13]]

^<<v14-28-13,13>>^ "Não tragam os prisioneiros para cá!", disseram. "Se o fizerem, aumentaremos nossos pecados e nossa culpa diante do SENHOR. Nossa culpa já é grande, e a ira ardente do SENHOR se voltou contra Israel!"

[[v14-28-14]]

^<<v14-28-14,14>>^ Então os guerreiros libertaram os prisioneiros e colocaram os despojos diante dos líderes do povo.

[[v14-28-15]]

^<<v14-28-15,15>>^ Os quatro homens já mencionados por nome vieram à frente e deram roupas dos despojos aos presos que estavam nus. Vestiram-nos, deram-lhes sandálias, providenciaram comida e bebida para eles e aplicaram bálsamo sobre seus ferimentos. Puseram sobre jumentos aqueles que estavam fracos e levaram todos os prisioneiros de volta para seu povo em Jericó, a cidade das palmeiras. Depois, voltaram para Samaria.

[[v14-28-16]]

^<<v14-28-16,16>>^ Nessa época, o rei Acaz pediu ajuda ao rei da Assíria.

[[v14-28-17]]

^<<v14-28-17,17>>^ Os exércitos de Edom tinham invadido Judá outra vez e levado prisioneiros.

[[v14-28-18]]

^<<v14-28-18,18>>^ Os filisteus haviam atacado cidades nas colinas de Judá e no Neguebe. Conquistaram e ocuparam Bete-Semes, Aijalom e Gederote, além de Socó, Timna e Ginzo, com seus povoados.

[[v14-28-19]]

^<<v14-28-19,19>>^ O SENHOR humilhou Judá por causa de Acaz, rei de Judá, pois ele havia incentivado o povo a pecar e havia sido inteiramente infiel ao SENHOR.

[[v14-28-20]]

^<<v14-28-20,20>>^ Quando Tiglate-Pileser, rei da Assíria, chegou, atacou Acaz em vez de ajudá-lo.

[[v14-28-21]]

^<<v14-28-21,21>>^ Acaz tomou objetos de valor do templo do SENHOR, do palácio real e das casas de seus oficiais e os entregou ao rei da Assíria como tributo, mas de nada adiantou.

[[v14-28-22]]

^<<v14-28-22,22>>^ Mesmo nesse tempo de grande dificuldade, o rei Acaz foi ainda mais infiel ao SENHOR.

[[v14-28-23]]

^<<v14-28-23,23>>^ Ofereceu sacrifícios aos deuses de Damasco que o haviam derrotado, pois disse: "Visto que esses deuses ajudaram o rei da Síria, também me ajudarão se eu lhes oferecer sacrifícios". Em vez disso, porém, eles foram a causa de sua ruína e da ruína de todo o Judá.

[[v14-28-24]]

^<<v14-28-24,24>>^ Acaz pegou os utensílios do templo de Deus e os despedaçou. Trancou as portas do templo do SENHOR para que ninguém pudesse adorar ali e fez altares idólatras em cada esquina de Jerusalém.

[[v14-28-25]]

^<<v14-28-25,25>>^ Colocou santuários idólatras em todas as cidades de Judá para queimar incenso a outros deuses. Com isso, provocou a ira do SENHOR, o Deus de seus antepassados.

[[v14-28-26]]

^<<v14-28-26,26>>^ Os demais acontecimentos do reinado de Acaz e tudo que ele fez, do início ao fim, estão registrados no Livro dos Reis de Judá e de Israel .

[[v14-28-27]]

^<<v14-28-27,27>>^ Quando Acaz morreu e se reuniu a seus antepassados, foi sepultado em Jerusalém, mas não no cemitério dos reis de Judá. Seu filho Ezequias foi seu sucessor.

'''

xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[Próximo Capítulo &#62;]