include::./index.adoc[]

[[v14-30-0]]
=== 2 Crônicas, 30
// nvt ?, NVT - Nova Versão Transformadora

[[v14-30-1]]

^<<v14-30-1,1>>^ O rei Ezequias enviou uma mensagem a todo o Israel e Judá e escreveu cartas para o povo de Efraim e Manassés. Convidou todos a virem ao templo do SENHOR em Jerusalém para celebrar a Páscoa do SENHOR, o Deus de Israel.

[[v14-30-2]]

^<<v14-30-2,2>>^ O rei, seus oficiais e toda a comunidade de Jerusalém decidiram celebrar a Páscoa um mês depois da data estabelecida.

[[v14-30-3]]

^<<v14-30-3,3>>^ Não conseguiram celebrá-la na data prescrita, porque não havia como purificar sacerdotes em número suficiente até esse dia, e o povo ainda não tinha se reunido em Jerusalém.

[[v14-30-4]]

^<<v14-30-4,4>>^ Esse plano para celebrar a Páscoa pareceu bom ao rei e a toda a comunidade.

[[v14-30-5]]

^<<v14-30-5,5>>^ Assim, fizeram uma proclamação em todo o Israel, desde Berseba, ao sul, até Dã, ao norte, convidando todos a virem a Jerusalém para celebrar a Páscoa do SENHOR, o Deus de Israel. Fazia tempo que essa festa não era celebrada por um grande número de pessoas, como a lei exigia.

[[v14-30-6]]

^<<v14-30-6,6>>^ Por ordem do rei, mensageiros foram enviados a todo o Israel e Judá. Levavam cartas que diziam: "Ó israelitas, voltem para o SENHOR, o Deus de Abraão, Isaque e Israel, para que ele se volte para nós, os poucos que sobrevivemos à conquista pelos reis assírios.

[[v14-30-7]]

^<<v14-30-7,7>>^ Não sejam como seus antepassados e parentes que foram infiéis ao SENHOR, o Deus de seus antepassados, e se tornaram objeto de desprezo, como vocês mesmos podem ver.

[[v14-30-8]]

^<<v14-30-8,8>>^ Não sejam teimosos, como eles foram, mas submetam-se ao SENHOR. Venham a este templo que ele consagrou para sempre. Adorem o SENHOR, seu Deus, para que sua ira ardente se desvie de vocês.

[[v14-30-9]]

^<<v14-30-9,9>>^ "Pois, se voltarem para o SENHOR, seus parentes e seus filhos serão tratados com bondade por aqueles que os capturaram e voltarão a esta terra. Pois o SENHOR, seu Deus, é cheio de graça e compaixão. Não os rejeitará se voltarem para ele".

[[v14-30-10]]

^<<v14-30-10,10>>^ Os mensageiros foram de cidade em cidade em Efraim e Manassés e até o território de Zebulom, mas a maioria do povo riu e zombou deles.

[[v14-30-11]]

^<<v14-30-11,11>>^ Contudo, alguns de Aser, Manassés e Zebulom se humilharam e vieram a Jerusalém.

[[v14-30-12]]

^<<v14-30-12,12>>^ Ao mesmo tempo, a mão de Deus estava sobre o povo da terra de Judá, dando-lhes um só coração para obedecer às ordens do rei e de seus oficiais, conforme a palavra do SENHOR.

[[v14-30-13]]

^<<v14-30-13,13>>^ Assim, uma grande multidão se reuniu em Jerusalém no segundo mês, para comemorar a Festa dos Pães sem Fermento.

[[v14-30-14]]

^<<v14-30-14,14>>^ Começaram a trabalhar e removeram os santuários idólatras de Jerusalém. Também removeram todos os altares de incenso e os jogaram no vale de Cedrom.

[[v14-30-15]]

^<<v14-30-15,15>>^ No décimo quarto dia do segundo mês, o povo abateu o cordeiro pascal. Isso deixou os sacerdotes e levitas envergonhados, por isso se purificaram e trouxeram holocaustos ao templo do SENHOR.

[[v14-30-16]]

^<<v14-30-16,16>>^ Tomaram seus lugares no templo, conforme a instrução da lei de Moisés, homem de Deus. Os levitas trouxeram sangue dos sacrifícios para os sacerdotes, que o aspergiram sobre o altar.

[[v14-30-17]]

^<<v14-30-17,17>>^ Visto que muitas pessoas não haviam se purificado, os levitas tiveram de abater para elas o cordeiro pascal, a fim de consagrá-las ao SENHOR.

[[v14-30-18]]

^<<v14-30-18,18>>^ A maioria dos que vieram de Efraim, Manassés, Issacar e Zebulom não havia se purificado. Mas o rei Ezequias orou por eles e foi permitido que comessem a refeição pascal, embora isso fosse contrário aos requisitos da lei. Pois Ezequias orou: "Que o SENHOR, que é bondoso, perdoe

[[v14-30-19]]

^<<v14-30-19,19>>^ aqueles que resolveram buscar o SENHOR, o Deus de seus antepassados, mesmo que não estejam devidamente purificados conforme os padrões do santuário".

[[v14-30-20]]

^<<v14-30-20,20>>^ E o SENHOR ouviu a oração de Ezequias e perdoou o povo.

[[v14-30-21]]

^<<v14-30-21,21>>^ Então os israelitas que estavam em Jerusalém comemoraram com grande alegria durante sete dias a Festa dos Pães sem Fermento. A cada dia, os levitas e os sacerdotes louvavam o SENHOR com instrumentos ressoantes.

[[v14-30-22]]

^<<v14-30-22,22>>^ Ezequias elogiou todos os levitas pela aptidão que demonstraram no serviço ao SENHOR. A celebração prosseguiu por sete dias. Apresentaram ofertas de paz, e o povo agradeceu ao SENHOR, o Deus de seus antepassados.

[[v14-30-23]]

^<<v14-30-23,23>>^ Toda a comunidade resolveu continuar com a festa por mais sete dias, de modo que celebraram com alegria por mais uma semana.

[[v14-30-24]]

^<<v14-30-24,24>>^ Ezequias, rei de Judá, deu à comunidade mil novilhos e sete mil ovelhas para as ofertas, e os oficiais deram mil novilhos e dez mil ovelhas e cabras. Nesse meio-tempo, muitos outros sacerdotes se purificaram.

[[v14-30-25]]

^<<v14-30-25,25>>^ Toda a comunidade de Judá se alegrou, incluindo os sacerdotes, os levitas, todos que vieram da terra de Israel, os estrangeiros residentes em Israel que vieram para a festa e todos que moravam em Judá.

[[v14-30-26]]

^<<v14-30-26,26>>^ Houve grande alegria em Jerusalém, pois a cidade não via uma celebração como essa desde os dias de Salomão, filho do rei Davi.

[[v14-30-27]]

^<<v14-30-27,27>>^ Então os sacerdotes e os levitas se levantaram e abençoaram o povo, e Deus, de sua santa habitação nos céus, ouviu sua oração.

'''

xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[&#60; Capítulo Anterior] | <<v14-30-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[Próximo Capítulo &#62;]