include::./index.adoc[]

[[v14-15-0]]
=== 2 Crônicas, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v14-15-1]]

^<<v14-15-1,1>>^ Então o Espírito de Deus veio sobre Azarias, filho de Odede,

[[v14-15-2]]

^<<v14-15-2,2>>^ e ele foi ao encontro do rei Asa. "Ouça-me, Asa!", disse ele. "Ouça-me todo o povo de Judá e de Benjamim! O SENHOR estará com vocês enquanto estiverem com ele! Sempre que o buscarem, o encontrarão. Mas, se o abandonarem, ele os abandonará.

[[v14-15-3]]

^<<v14-15-3,3>>^ Durante muito tempo, Israel esteve sem o verdadeiro Deus, sem sacerdote para ensiná-los e sem lei para instruí-los.

[[v14-15-4]]

^<<v14-15-4,4>>^ No entanto, sempre que se viram em dificuldades e se voltaram para o SENHOR, o Deus de Israel, e o buscaram, eles o encontraram.

[[v14-15-5]]

^<<v14-15-5,5>>^ "Naquele tempo, não era seguro viajar. Problemas afligiam os habitantes de todas as terras.

[[v14-15-6]]

^<<v14-15-6,6>>^ Uma nação lutava contra outra, e uma cidade contra outra, pois Deus os afligia com todo tipo de angústia.

[[v14-15-7]]

^<<v14-15-7,7>>^ Quanto a vocês, porém, sejam fortes e corajosos, pois seu trabalho será recompensado."

[[v14-15-8]]

^<<v14-15-8,8>>^ Quando Asa ouviu essa mensagem do profeta Azarias, encheu-se de coragem e removeu todos os ídolos repulsivos da terra de Judá e de Benjamim e das cidades que ele havia capturado na região montanhosa de Efraim. Além disso, restaurou o altar do SENHOR, que ficava na frente da sala de entrada do templo do SENHOR.

[[v14-15-9]]

^<<v14-15-9,9>>^ Depois, Asa reuniu todo o povo de Judá e de Benjamim, e também o povo de Efraim, de Manassés e de Simeão que havia se estabelecido entre eles. Muita gente de Israel tinha se mudado para Judá no reinado de Asa, quando viu que o SENHOR, seu Deus, estava com ele.

[[v14-15-10]]

^<<v14-15-10,10>>^ Reuniram-se em Jerusalém no terceiro mês do décimo quinto ano do reinado de Asa.

[[v14-15-11]]

^<<v14-15-11,11>>^ Naquele dia, sacrificaram ao SENHOR setecentos bois e sete mil ovelhas dos despojos que haviam tomado na batalha.

[[v14-15-12]]

^<<v14-15-12,12>>^ Então fizeram um acordo de buscar o SENHOR, o Deus de seus antepassados, de todo o coração e de toda a alma.

[[v14-15-13]]

^<<v14-15-13,13>>^ Concordaram que qualquer um que não buscasse o SENHOR, o Deus de Israel, deveria morrer, jovem ou idoso, homem ou mulher.

[[v14-15-14]]

^<<v14-15-14,14>>^ Fizeram esse juramento de lealdade ao SENHOR em alta voz, ao som de trombetas e clarins.

[[v14-15-15]]

^<<v14-15-15,15>>^ Todo o Judá se alegrou com esse acordo, pois o fizeram de todo o coração. Buscaram o SENHOR com sinceridade e o encontraram. E o SENHOR lhes deu descanso de todos os lados.

[[v14-15-16]]

^<<v14-15-16,16>>^ O rei Asa chegou a depor sua avó Maaca da posição de rainha-mãe, pois ela havia feito um poste obsceno para a deusa Aserá. Derrubou esse poste obsceno, o quebrou e o queimou no vale de Cedrom.

[[v14-15-17]]

^<<v14-15-17,17>>^ Embora os santuários idólatras não tivessem sido removidos de Israel, o coração de Asa permaneceu inteiramente fiel durante toda a sua vida.

[[v14-15-18]]

^<<v14-15-18,18>>^ Ele trouxe para o templo de Deus a prata, o ouro e os diversos utensílios que ele e seu pai haviam consagrado.

[[v14-15-19]]

^<<v14-15-19,19>>^ Não houve mais guerra até o trigésimo quinto ano do reinado de Asa.

'''

xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[&#60; Capítulo Anterior] | <<v14-15-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[Próximo Capítulo &#62;]