include::./index.adoc[]

[[v14-5-0]]
=== 2 Crônicas, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v14-5-1]]

^<<v14-5-1,1>>^ Assim, o rei Salomão concluiu toda a sua obra no templo do SENHOR. Então trouxe todos os presentes que seu pai, Davi, havia consagrado — a prata, o ouro e os diversos objetos — e os guardou na tesouraria do templo de Deus.

[[v14-5-2]]

^<<v14-5-2,2>>^ Em seguida, Salomão mandou chamar a Jerusalém todas as autoridades de Israel e todos os líderes das tribos, os chefes das famílias israelitas. Eles levariam a arca da aliança do SENHOR do lugar onde estava, na Cidade de Davi, também conhecida como Sião, para o templo.

[[v14-5-3]]

^<<v14-5-3,3>>^ Todos os homens de Israel se reuniram diante do rei durante a Festa das Cabanas, celebrada anualmente no sétimo mês.

[[v14-5-4]]

^<<v14-5-4,4>>^ Quando todos os líderes de Israel chegaram, os levitas ergueram a arca.

[[v14-5-5]]

^<<v14-5-5,5>>^ Os sacerdotes e os levitas levaram a arca do SENHOR, junto com a tenda do encontro e todos os seus utensílios sagrados.

[[v14-5-6]]

^<<v14-5-6,6>>^ Ali, diante da arca, o rei Salomão e toda a comunidade de Israel ofereceram tantos sacrifícios de ovelhas e bois que não puderam ser contados.

[[v14-5-7]]

^<<v14-5-7,7>>^ Então os sacerdotes levaram a arca da aliança do SENHOR para o santuário interno do templo, o lugar santíssimo, e a colocaram sob as asas dos querubins.

[[v14-5-8]]

^<<v14-5-8,8>>^ Os querubins tinham as asas abertas sobre a arca, e elas cobriam a arca e as varas usadas para transportá-la.

[[v14-5-9]]

^<<v14-5-9,9>>^ Essas varas eram tão compridas que suas pontas podiam ser vistas do lugar santo, diante do lugar santíssimo, mas não de fora; e estão ali até hoje.

[[v14-5-10]]

^<<v14-5-10,10>>^ Na arca havia só as duas tábuas de pedra que Moisés tinha colocado dentro dela no monte Sinai, onde o SENHOR fez uma aliança com os israelitas depois que eles saíram da terra do Egito.

[[v14-5-11]]

^<<v14-5-11,11>>^ Então os sacerdotes saíram do lugar santo. Todos eles haviam se purificado, estivessem ou não de serviço naquele dia.

[[v14-5-12]]

^<<v14-5-12,12>>^ E os levitas que eram músicos — Asafe, Hemã, Jedutum, e todos os seus filhos e parentes — vestiam roupas de linho fino e estavam em pé do lado leste do altar, tocando címbalos, liras e harpas. Cento e vinte sacerdotes tocando trombetas os acompanhavam.

[[v14-5-13]]

^<<v14-5-13,13>>^ Os que tocavam trombetas e os cantores, em uníssono, louvaram e agradeceram ao SENHOR. Acompanhados de trombetas, címbalos e outros instrumentos, levantaram as vozes e louvaram o SENHOR com estas palavras: "Ele é bom! Seu amor dura para sempre!". Nesse momento, uma densa nuvem encheu o templo do SENHOR.

[[v14-5-14]]

^<<v14-5-14,14>>^ Com isso, os sacerdotes não puderam dar continuidade a seus serviços, pois a presença gloriosa do SENHOR encheu o templo de Deus.

'''

xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[&#60; Capítulo Anterior] | <<v14-5-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[Próximo Capítulo &#62;]