include::./index.adoc[]

[[v14-7-0]]
=== 2 Crônicas, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v14-7-1]]

^<<v14-7-1,1>>^ Quando Salomão terminou de orar, desceu fogo do céu e queimou os holocaustos e os sacrifícios, e a presença gloriosa do SENHOR encheu o templo.

[[v14-7-2]]

^<<v14-7-2,2>>^ Os sacerdotes não podiam entrar no templo do SENHOR, pois a presença gloriosa do SENHOR havia enchido o templo

[[v14-7-3]]

^<<v14-7-3,3>>^ Quando todos os israelitas viram o fogo descer e a presença gloriosa do SENHOR encher o templo, prostraram-se com o rosto no chão, adoraram e louvaram o SENHOR, dizendo: "Ele é bom! Seu amor dura para sempre!".

[[v14-7-4]]

^<<v14-7-4,4>>^ Então o rei e todo o povo ofereceram sacrifícios ao SENHOR.

[[v14-7-5]]

^<<v14-7-5,5>>^ O rei Salomão apresentou um sacrifício de 22 mil bois e 120 mil ovelhas. Assim, o rei e todo o povo fizeram a dedicação do templo do SENHOR.

[[v14-7-6]]

^<<v14-7-6,6>>^ Os sacerdotes tomaram seus lugares designados, bem como os levitas, que cantavam: "Seu amor dura para sempre!". Os levitas acompanhavam o cântico com os instrumentos musicais que o rei Davi tinha feito para louvar o SENHOR. Os sacerdotes, de frente para os levitas, tocavam as trombetas, e todo o Israel estava em pé.

[[v14-7-7]]

^<<v14-7-7,7>>^ Em seguida, Salomão consagrou a parte central do pátio em frente ao templo do SENHOR. Ali apresentou holocaustos e a gordura das ofertas de paz, pois o altar de bronze que ele havia construído era pequeno demais para tantos holocaustos, ofertas de cereal e gordura das ofertas de paz.

[[v14-7-8]]

^<<v14-7-8,8>>^ Durante os sete dias seguintes, Salomão e todo o Israel celebraram a Festa das Cabanas. Uma grande multidão havia se reunido, de lugares distantes como Lebo-Hamate, ao norte, e o ribeiro do Egito, ao sul.

[[v14-7-9]]

^<<v14-7-9,9>>^ No oitavo dia, foi realizada uma cerimônia de encerramento, pois haviam comemorado a dedicação do altar por sete dias e a Festa das Cabanas por mais sete dias.

[[v14-7-10]]

^<<v14-7-10,10>>^ Terminada a festa, Salomão mandou o povo para casa. Foram embora alegres e exultantes, pois o SENHOR tinha mostrado toda a sua bondade a Davi, a Salomão e a seu povo, Israel.

[[v14-7-11]]

^<<v14-7-11,11>>^ Salomão terminou o templo do SENHOR e o palácio real. Concluiu tudo que havia planejado fazer na construção do templo e do palácio.

[[v14-7-12]]

^<<v14-7-12,12>>^ Então, certa noite, o SENHOR lhe apareceu e disse: "Ouvi sua oração e escolhi este templo como o lugar para se fazer sacrifícios.

[[v14-7-13]]

^<<v14-7-13,13>>^ Se, por vezes, eu fechar o céu para que não chova, ou ordenar que gafanhotos devorem suas colheitas, ou enviar pragas entre meu povo,

[[v14-7-14]]

^<<v14-7-14,14>>^ então, se meu povo, que se chama pelo meu nome, humilhar-se e orar, buscar minha presença e afastar-se de seus maus caminhos, eu os ouvirei dos céus, perdoarei seus pecados e restaurarei sua terra.

[[v14-7-15]]

^<<v14-7-15,15>>^ Olharei e ouvirei atentamente cada oração feita neste lugar.

[[v14-7-16]]

^<<v14-7-16,16>>^ Pois escolhi e consagrei este templo, onde meu nome será honrado para sempre. Olharei continuamente para ele, com todo o meu coração.

[[v14-7-17]]

^<<v14-7-17,17>>^ "Quanto a você, se me seguir fielmente, como fez seu pai, Davi, obedecendo a todos os meus mandamentos, decretos e estatutos,

[[v14-7-18]]

^<<v14-7-18,18>>^ estabelecerei o trono de sua dinastia. Pois fiz esta aliança com seu pai, Davi: ‘Um de seus descendentes sempre governará Israel’.

[[v14-7-19]]

^<<v14-7-19,19>>^ "Mas, se você ou seus descendentes me abandonarem e desobedecerem a meus decretos e mandamentos, seguindo e adorando outros deuses,

[[v14-7-20]]

^<<v14-7-20,20>>^ arrancarei o povo desta terra que lhe dei. Rejeitarei este templo que consagrei em honra ao meu nome, e farei dele objeto de zombaria e desprezo entre as nações.

[[v14-7-21]]

^<<v14-7-21,21>>^ E, embora este templo seja agora imponente, todos que passarem perto dele ficarão chocados. Perguntarão: ‘Por que o SENHOR fez coisas tão terríveis com esta terra e com este templo?’.

[[v14-7-22]]

^<<v14-7-22,22>>^ "E a resposta será: ‘Porque os israelitas abandonaram o SENHOR, o Deus de seus antepassados, que os tirou da terra do Egito e, em lugar dele, adoraram outros deuses e se prostraram diante deles. Por isso ele trouxe sobre eles todas essas calamidades’".

'''

xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[&#60; Capítulo Anterior] | <<v14-7-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[Próximo Capítulo &#62;]