include::./index.adoc[]

[[v14-14-0]]
=== 2 Crônicas, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v14-14-1]]

^<<v14-14-1,1>>^ Quando Abias morreu e se reuniu a seus antepassados, foi sepultado na Cidade de Davi. Seu filho Asa foi seu sucessor. Houve paz na terra durante dez anos.

[[v14-14-2]]

^<<v14-14-2,2>>^ Asa fez o que era bom e certo aos olhos do SENHOR, seu Deus.

[[v14-14-3]]

^<<v14-14-3,3>>^ Removeu os altares estrangeiros e os santuários idólatras, despedaçou as colunas sagradas e derrubou os postes de Aserá.

[[v14-14-4]]

^<<v14-14-4,4>>^ Ordenou ao povo de Judá que buscasse o SENHOR, o Deus de seus antepassados, e obedecesse a suas leis e a seus mandamentos.

[[v14-14-5]]

^<<v14-14-5,5>>^ Asa também removeu os santuários idólatras e os altares de incenso de todas as cidades de Judá. Assim, o reino de Asa desfrutou um tempo de paz.

[[v14-14-6]]

^<<v14-14-6,6>>^ Nesse período, ele construiu cidades fortificadas em toda a terra de Judá. Ninguém lutou contra ele durante esses anos, pois o SENHOR lhe deu descanso.

[[v14-14-7]]

^<<v14-14-7,7>>^ Asa disse ao povo de Judá: "Vamos construir essas cidades e fortificá-las com muros, torres, portões e trancas. A terra ainda é nossa porque buscamos o SENHOR, nosso Deus, e ele nos deu descanso de todos os lados". Assim, eles prosseguiram com os projetos e os concluíram com êxito.

[[v14-14-8]]

^<<v14-14-8,8>>^ O rei Asa tinha um exército de 300 mil guerreiros da tribo de Judá, armados com escudos grandes e lanças. Também tinha um exército de 280 mil guerreiros da tribo de Benjamim, armados com escudos pequenos e arcos. Os dois exércitos eram formados por homens valentes.

[[v14-14-9]]

^<<v14-14-9,9>>^ Certa vez, um etíope chamado Zerá atacou Judá com um exército de um milhão de soldados e trezentos carros de guerra. Avançaram até a cidade de Maressa,

[[v14-14-10]]

^<<v14-14-10,10>>^ de modo que Asa saiu com seu exército para a batalha no vale ao norte de Maressa.

[[v14-14-11]]

^<<v14-14-11,11>>^ Então Asa clamou ao SENHOR, seu Deus: "Ó SENHOR, ninguém além de ti pode ajudar os fracos contra os poderosos! Ajuda-nos, ó SENHOR, nosso Deus, pois em ti confiamos. Em teu nome enfrentamos esse exército imenso. Ó SENHOR, tu és nosso Deus; não permitas que simples homens prevaleçam contra ti!".

[[v14-14-12]]

^<<v14-14-12,12>>^ Então o SENHOR derrotou os etíopes diante de Asa e do exército de Judá, e eles fugiram.

[[v14-14-13]]

^<<v14-14-13,13>>^ Asa e seu exército os perseguiram até Gerar, e caíram tantos etíopes que não conseguiram se recuperar. Foram destruídos pelo SENHOR e por seu exército, e os soldados de Judá levaram grande quantidade de despojos.

[[v14-14-14]]

^<<v14-14-14,14>>^ Enquanto estavam em Gerar, atacaram todas as cidades da região, e o terror do SENHOR veio sobre o povo dali. Como resultado, os soldados de Judá levaram muitos despojos também dessas cidades.

[[v14-14-15]]

^<<v14-14-15,15>>^ Atacaram, ainda, os acampamentos onde havia rebanhos e levaram muitas ovelhas e camelos. Em seguida, voltaram para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[&#60; Capítulo Anterior] | <<v14-14-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[Próximo Capítulo &#62;]