include::./index.adoc[]

[[v14-18-0]]
=== 2 Crônicas, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v14-18-1]]

^<<v14-18-1,1>>^ Josafá, muito rico e respeitado, aliou-se a Acabe por meio do casamento de seu filho com a filha de Acabe.

[[v14-18-2]]

^<<v14-18-2,2>>^ Alguns anos depois, foi a Samaria visitar Acabe, que ofereceu a ele e a seus oficiais um enorme banquete, para o qual abateu um grande número de ovelhas e bois. Então Acabe persuadiu Josafá a unir forças com ele para recuperar Ramote-Gileade.

[[v14-18-3]]

^<<v14-18-3,3>>^ Acabe, rei de Israel, perguntou a Josafá, rei de Judá: "Você irá comigo a Ramote-Gileade?". Josafá respondeu: "Claro que sim! Você e eu somos como um só. Meus soldados são seus soldados. Certamente iremos com você à batalha!".

[[v14-18-4]]

^<<v14-18-4,4>>^ E acrescentou: "Antes, porém, consulte o SENHOR".

[[v14-18-5]]

^<<v14-18-5,5>>^ Então o rei de Israel convocou os profetas, cerca de quatrocentos no total, e perguntou: "Devemos ir à guerra contra Ramote-Gileade ou não?". Todos eles responderam: "Sim, devem! Deus entregará o inimigo nas mãos do rei".

[[v14-18-6]]

^<<v14-18-6,6>>^ Josafá, porém perguntou: "Acaso não há aqui um profeta do SENHOR? Devemos consultá-lo também".

[[v14-18-7]]

^<<v14-18-7,7>>^ O rei de Israel respondeu a Josafá: "Há mais um homem que pode consultar o SENHOR para nós, mas eu o odeio, pois nunca profetiza nada de bom a meu respeito, só coisas ruins! Chama-se Micaías, filho de Inlá". "O rei não devia falar assim", respondeu Josafá.

[[v14-18-8]]

^<<v14-18-8,8>>^ Então o rei de Israel chamou um de seus oficiais e disse: "Traga Micaías, filho de Inlá. Rápido!".

[[v14-18-9]]

^<<v14-18-9,9>>^ Vestidos com seus trajes reais, o rei de Israel e Josafá, rei de Judá, estavam sentados cada um em seu trono na eira junto à porta de Samaria. Todos os profetas estavam profetizando diante deles.

[[v14-18-10]]

^<<v14-18-10,10>>^ Um dos profetas, Zedequias, filho de Quenaaná, fez chifres de ferro e declarou: "Assim diz o SENHOR: ‘Com estes chifres o rei ferirá os sírios até a morte!’".

[[v14-18-11]]

^<<v14-18-11,11>>^ Todos os outros profetas concordaram, dizendo: "Sim, suba a Ramote-Gileade e seja vitorioso, pois o SENHOR a entregará nas mãos do rei!".

[[v14-18-12]]

^<<v14-18-12,12>>^ Enquanto isso, o mensageiro que foi buscar Micaías lhe disse: "Veja, todos os profetas prometem vitória para o rei. Concorde com eles e também prometa sucesso".

[[v14-18-13]]

^<<v14-18-13,13>>^ Micaías, porém, respondeu: "Tão certo como vive o SENHOR, direi apenas o que meu Deus ordenar".

[[v14-18-14]]

^<<v14-18-14,14>>^ Quando Micaías chegou, o rei lhe perguntou: "Micaías, devemos ir à guerra contra Ramote-Gileade ou não?". Micaías respondeu: "Sim, suba e será vitorioso, pois eles serão entregues em suas mãos!".

[[v14-18-15]]

^<<v14-18-15,15>>^ Mas o rei disse: "Quantas vezes preciso exigir que diga somente a verdade quando falar em nome do SENHOR?".

[[v14-18-16]]

^<<v14-18-16,16>>^ Então Micaías respondeu: "Vi todo o Israel espalhado pelos montes, como ovelhas sem pastor. E o SENHOR disse: ‘Seu líder foi morto. Mande-os para casa em paz’".

[[v14-18-17]]

^<<v14-18-17,17>>^ O rei de Israel disse a Josafá: "Não falei? Ele nunca profetiza nada de bom a meu respeito, mas apenas coisas ruins".

[[v14-18-18]]

^<<v14-18-18,18>>^ Micaías prosseguiu: "Ouça o que o SENHOR diz! Vi o SENHOR sentado em seu trono, com todo o exército do céu ao redor, à sua direita e à sua esquerda.

[[v14-18-19]]

^<<v14-18-19,19>>^ E o SENHOR perguntou: ‘Quem enganará Acabe, rei de Israel, para que vá à guerra contra Ramote-Gileade e seja morto ali?’. "Houve muitas sugestões,

[[v14-18-20]]

^<<v14-18-20,20>>^ até que, por fim, um espírito se aproximou do SENHOR e disse: ‘Eu o enganarei!’. "‘De que maneira?’, perguntou o SENHOR.

[[v14-18-21]]

^<<v14-18-21,21>>^ "E o espírito respondeu: ‘Sairei e porei um espírito mentiroso na boca de todos os seus profetas’. "O SENHOR disse: ‘Você conseguirá enganá-lo. Vá e faça isso!’.

[[v14-18-22]]

^<<v14-18-22,22>>^ "Como vê, o SENHOR pôs um espírito mentiroso na boca de todos os seus profetas, pois o SENHOR decretou sua desgraça".

[[v14-18-23]]

^<<v14-18-23,23>>^ Então Zedequias, filho de Quenaaná, se aproximou de Micaías e lhe deu uma bofetada. "Como foi que o Espírito do SENHOR me deixou para falar com você?", perguntou ele.

[[v14-18-24]]

^<<v14-18-24,24>>^ Micaías respondeu: "Você descobrirá em breve, quando tentar se esconder em algum quarto secreto!".

[[v14-18-25]]

^<<v14-18-25,25>>^ Então o rei de Israel ordenou: "Prendam Micaías e levem-no de volta a Amom, governador da cidade, e a meu filho Joás,

[[v14-18-26]]

^<<v14-18-26,26>>^ com a seguinte ordem: ‘Ponham este homem na prisão e deem-lhe apenas pão e água até que eu volte da batalha em segurança!’".

[[v14-18-27]]

^<<v14-18-27,27>>^ Micaías, porém, respondeu: "Se voltar em segurança, significará que o SENHOR não falou por meu intermédio!". E acrescentou aos que estavam ao redor: "Todos vocês, prestem atenção às minhas palavras!".

[[v14-18-28]]

^<<v14-18-28,28>>^ Então o rei de Israel e Josafá, rei de Judá, levaram seus exércitos para atacar Ramote-Gileade.

[[v14-18-29]]

^<<v14-18-29,29>>^ O rei de Israel disse a Josafá: "Quando entrarmos no combate, usarei um disfarce para que ninguém me reconheça, mas você vestirá seus trajes reais". O rei de Israel se disfarçou, e os dois foram à batalha.

[[v14-18-30]]

^<<v14-18-30,30>>^ Enquanto isso, o rei da Síria tinha dado as seguintes ordens aos comandantes dos carros de guerra: "Ataquem somente o rei de Israel. Não lutem contra ninguém mais!".

[[v14-18-31]]

^<<v14-18-31,31>>^ Quando os comandantes dos carros de guerra sírios viram Josafá em seus trajes reais, foram atrás dele. "É o rei de Israel!", disseram. Contudo, Josafá clamou, e o SENHOR o salvou. Deus o ajudou e afastou dele seus inimigos.

[[v14-18-32]]

^<<v14-18-32,32>>^ Assim que os comandantes dos carros perceberam que ele não era o rei de Israel, pararam de persegui-lo.

[[v14-18-33]]

^<<v14-18-33,33>>^ Então um soldado sírio disparou uma flecha a esmo e acertou o rei de Israel entre as juntas de sua armadura. "Dê a volta e tire-me daqui!", exclamou Acabe para o condutor de seu carro. "Estou gravemente ferido!"

[[v14-18-34]]

^<<v14-18-34,34>>^ A batalha, cada vez mais violenta, prosseguiu durante todo o dia, e o rei permaneceu em pé, apoiado em seu carro, de frente para os sírios. Ao entardecer, quando o sol se punha, ele morreu.

'''

xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[&#60; Capítulo Anterior] | <<v14-18-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[Próximo Capítulo &#62;]