include::./index.adoc[]

[[v14-29-0]]
=== 2 Crônicas, 29
// nvt ?, NVT - Nova Versão Transformadora

[[v14-29-1]]

^<<v14-29-1,1>>^ Ezequias tinha 25 anos quando começou a reinar, e reinou em Jerusalém por 29 anos. Sua mãe se chamava Abia e era filha de Zacarias.

[[v14-29-2]]

^<<v14-29-2,2>>^ Fez o que era certo aos olhos do SENHOR, como seu antepassado Davi.

[[v14-29-3]]

^<<v14-29-3,3>>^ Logo no primeiro mês do primeiro ano de seu reinado, Ezequias reabriu as portas do templo do SENHOR e as consertou.

[[v14-29-4]]

^<<v14-29-4,4>>^ Mandou chamar os sacerdotes e os levitas para se encontrarem com ele na praça do lado leste do templo.

[[v14-29-5]]

^<<v14-29-5,5>>^ "Ouçam-me, levitas!", disse ele. "Purifiquem-se e purifiquem o templo do SENHOR, o Deus de seus antepassados. Removam do santuário todos os objetos impuros.

[[v14-29-6]]

^<<v14-29-6,6>>^ Nossos antepassados foram infiéis e fizeram o que era mau aos olhos do SENHOR, nosso Deus. Abandonaram o SENHOR e seu lugar de habitação; deram as costas para ele.

[[v14-29-7]]

^<<v14-29-7,7>>^ Também fecharam as portas da sala de entrada do templo e apagaram as lâmpadas. Deixaram de queimar incenso e de apresentar holocaustos no santuário do Deus de Israel.

[[v14-29-8]]

^<<v14-29-8,8>>^ "Por isso a ira do SENHOR veio sobre Judá e sobre Jerusalém. Ele fez deles objeto de espanto, horror e zombaria, como vocês veem com os próprios olhos.

[[v14-29-9]]

^<<v14-29-9,9>>^ Por causa disso, nossos pais foram mortos pela espada, e nossos filhos, filhas e esposas foram capturados.

[[v14-29-10]]

^<<v14-29-10,10>>^ Agora, porém, farei uma aliança com o SENHOR, o Deus de Israel, para que sua ira ardente se afaste de nós.

[[v14-29-11]]

^<<v14-29-11,11>>^ Meus filhos, não sejam mais negligentes quanto a seus deveres! O SENHOR os escolheu para estarem diante dele, para o servirem, para dirigirem o povo no culto e para lhe queimarem incenso."

[[v14-29-12]]

^<<v14-29-12,12>>^ Os levitas que começaram a trabalhar de imediato foram: Do clã de Coate: Maate, filho de Amasai, e Joel, filho de Azarias. Do clã de Merari: Quis, filho de Abdi, e Azarias, filho de Jealelel. Do clã de Gérson: Joá, filho de Zima, e Éden, filho de Joá.

[[v14-29-13]]

^<<v14-29-13,13>>^ Da família de Elisafã: Sinri e Jeuel. Da família de Asafe: Zacarias e Matanias.

[[v14-29-14]]

^<<v14-29-14,14>>^ Da família de Hemã: Jeuel e Simei. Da família de Jedutum: Semaías e Uziel.

[[v14-29-15]]

^<<v14-29-15,15>>^ Esses homens reuniram seus parentes levitas, e todos se purificaram. Em seguida, começaram a purificar o templo do SENHOR, obedecendo às ordens do rei, de acordo com as instruções do SENHOR.

[[v14-29-16]]

^<<v14-29-16,16>>^ Os sacerdotes foram até o interior do templo do SENHOR para purificá-lo e trouxeram para fora, ao pátio do templo, todas as coisas impuras que encontraram. Os levitas as levaram dali para o vale de Cedrom.

[[v14-29-17]]

^<<v14-29-17,17>>^ Começaram o trabalho no primeiro dia do primeiro mês e, em oito dias, haviam chegado à sala de entrada do templo do SENHOR. Depois, levaram oito dias para purificar o templo do SENHOR, de modo que todo o trabalho foi completado em dezesseis dias.

[[v14-29-18]]

^<<v14-29-18,18>>^ Então os levitas foram ao rei Ezequias e lhe relataram: "Purificamos todo o templo do SENHOR, o altar de holocaustos com todos os seus utensílios e a mesa dos pães da presença com todos os seus utensílios.

[[v14-29-19]]

^<<v14-29-19,19>>^ Recuperamos todos os objetos que o rei Acaz jogou fora quando foi infiel e fechou o templo. Agora estão diante do altar do SENHOR, purificados e prontos para o uso".

[[v14-29-20]]

^<<v14-29-20,20>>^ Logo cedo na manhã seguinte, o rei Ezequias reuniu os líderes da cidade e subiu ao templo do SENHOR.

[[v14-29-21]]

^<<v14-29-21,21>>^ Trouxeram sete novilhos, sete carneiros e sete cordeiros como holocausto e sete bodes como oferta pelo pecado em favor do reino, do templo e de Judá. O rei ordenou que os sacerdotes, descendentes de Arão, sacrificassem os animais no altar do SENHOR.

[[v14-29-22]]

^<<v14-29-22,22>>^ Os sacerdotes abateram os novilhos, pegaram o sangue e o aspergiram no altar. Em seguida, abateram os carneiros e aspergiram o sangue sobre o altar. Por fim, fizeram o mesmo com os cordeiros.

[[v14-29-23]]

^<<v14-29-23,23>>^ Os bodes para a oferta pelo pecado foram levados para diante do rei e da comunidade, que impuseram as mãos sobre eles.

[[v14-29-24]]

^<<v14-29-24,24>>^ Depois disso, os sacerdotes abateram os bodes como oferta pelo pecado e aspergiram o sangue sobre o altar para fazer expiação pelos pecados de todo o Israel. O rei havia ordenado que o holocausto e a oferta pelo pecado fossem apresentados em favor de todo o Israel.

[[v14-29-25]]

^<<v14-29-25,25>>^ O rei Ezequias colocou os levitas no templo do SENHOR, com címbalos, harpas e liras. Ele obedeceu a todas as instruções que o SENHOR tinha dado ao rei Davi por meio de Gade, o vidente do rei, e por meio do profeta Natã.

[[v14-29-26]]

^<<v14-29-26,26>>^ Os levitas tomaram seus lugares com os instrumentos musicais de Davi, e os sacerdotes tomaram seus lugares com as trombetas.

[[v14-29-27]]

^<<v14-29-27,27>>^ Ezequias ordenou que o holocausto fosse oferecido sobre o altar. Enquanto o sacrifício era oferecido, tiveram início os cânticos de louvor ao SENHOR, acompanhados das trombetas e dos outros instrumentos musicais de Davi, rei de Israel.

[[v14-29-28]]

^<<v14-29-28,28>>^ Toda a comunidade adorou ao som dos cânticos dos músicos e do toque das trombetas, até que terminaram todos os holocaustos.

[[v14-29-29]]

^<<v14-29-29,29>>^ Em seguida, o rei e todos ali presentes se prostraram em adoração.

[[v14-29-30]]

^<<v14-29-30,30>>^ O rei Ezequias e os oficiais ordenaram aos levitas que louvassem o SENHOR com os cânticos escritos por Davi e pelo vidente Asafe. Eles o louvaram com alegria e se prostraram em adoração.

[[v14-29-31]]

^<<v14-29-31,31>>^ Então Ezequias declarou: "Agora que vocês se consagraram ao SENHOR, tragam seus sacrifícios e ofertas de gratidão ao templo do SENHOR". E a comunidade trouxe sacrifícios e ofertas de gratidão, e alguns, voluntariamente, também trouxeram holocaustos.

[[v14-29-32]]

^<<v14-29-32,32>>^ No total, a comunidade ofereceu ao SENHOR setenta novilhos, cem carneiros e duzentos cordeiros como holocaustos.

[[v14-29-33]]

^<<v14-29-33,33>>^ Também trouxeram seiscentos bois e três mil ovelhas como ofertas consagradas.

[[v14-29-34]]

^<<v14-29-34,34>>^ Não havia, porém, sacerdotes em número suficiente para preparar todos os holocaustos. Então seus parentes, os levitas, os ajudaram até que o trabalho fosse concluído e mais sacerdotes fossem purificados, pois os levitas haviam respondido mais depressa que os sacerdotes à ordem para se purificarem.

[[v14-29-35]]

^<<v14-29-35,35>>^ Houve grande quantidade de holocaustos, além das ofertas derramadas que os acompanhavam e da gordura das muitas ofertas de paz. Assim, o templo do SENHOR foi restaurado para o culto.

[[v14-29-36]]

^<<v14-29-36,36>>^ Ezequias e todo o povo se alegraram com o que Deus havia feito pelo povo, pois tudo foi realizado sem demora.

'''

xref:014-2-cronicas/014-2-cronicas-028.adoc#v14-28-0[&#60; Capítulo Anterior] | <<v14-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[Próximo Capítulo &#62;]