include::./index.adoc[]

[[v14-19-0]]
=== 2 Crônicas, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v14-19-1]]

^<<v14-19-1,1>>^ Quando Josafá, rei de Judá, voltou em segurança a seu palácio, em Jerusalém,

[[v14-19-2]]

^<<v14-19-2,2>>^ o vidente Jeú, filho de Hanani, saiu ao encontro dele. "Por que o rei ajuda os perversos e ama os que odeiam o SENHOR?", perguntou-lhe Hanani. "Por causa disso, o SENHOR está muito irado com você.

[[v14-19-3]]

^<<v14-19-3,3>>^ Mas ainda há algo de bom em você, pois removeu os postes de Aserá de toda a terra e buscou a Deus de todo o coração."

[[v14-19-4]]

^<<v14-19-4,4>>^ Josafá morava em Jerusalém, mas saía para visitar o povo por todo o território, desde Berseba até a região montanhosa de Efraim, a fim de animar todos a voltarem para o SENHOR, o Deus de seus antepassados.

[[v14-19-5]]

^<<v14-19-5,5>>^ Nomeou juízes na terra, em todas as cidades fortificadas,

[[v14-19-6]]

^<<v14-19-6,6>>^ e lhes disse: "Sejam cuidadosos! Lembrem-se de que não estão julgando para agradar as pessoas, mas para agradar o SENHOR. Ele estará com vocês sempre que derem um veredito.

[[v14-19-7]]

^<<v14-19-7,7>>^ Temam o SENHOR e julguem com integridade, pois o SENHOR, nosso Deus, não tolera injustiça, nem parcialidade, nem suborno".

[[v14-19-8]]

^<<v14-19-8,8>>^ Em Jerusalém, Josafá nomeou alguns levitas, sacerdotes e chefes de famílias de Israel para julgarem os casos que envolvessem a lei do SENHOR e questões civis.

[[v14-19-9]]

^<<v14-19-9,9>>^ Estas foram suas ordens para eles: "Ajam sempre no temor do SENHOR, com fidelidade e coração íntegro.

[[v14-19-10]]

^<<v14-19-10,10>>^ Toda vez que chegar até vocês uma causa de seus compatriotas israelitas de outras cidades, seja de homicídio, seja de outra violação da lei, dos mandamentos, dos decretos ou dos estatutos de Deus, advirtam-nos para que eles não pequem contra o SENHOR, a fim de que a ira dele não venha sobre vocês e sobre eles. Se agirem desse modo, estarão livres de culpa.

[[v14-19-11]]

^<<v14-19-11,11>>^ "Amarias, o sumo sacerdote, terá a última palavra nos casos relacionados ao SENHOR. Zebadias, filho de Ismael, líder da tribo de Judá, terá a última palavra em todas as questões relativas ao reino. Os levitas os ajudarão nesses trabalhos. Sejam corajosos no cumprimento de seus deveres, e que o SENHOR esteja com aqueles que agirem corretamente!".

'''

xref:014-2-cronicas/014-2-cronicas-018.adoc#v14-18-0[&#60; Capítulo Anterior] | <<v14-19-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[Próximo Capítulo &#62;]