include::./index.adoc[]

[[v14-33-0]]
=== 2 Crônicas, 33
// nvt ?, NVT - Nova Versão Transformadora

[[v14-33-1]]

^<<v14-33-1,1>>^ Manassés tinha 12 anos quando começou a reinar, e reinou em Jerusalém por 55 anos.

[[v14-33-2]]

^<<v14-33-2,2>>^ Fez o que era mau aos olhos do SENHOR e seguiu as práticas detestáveis das nações que o SENHOR havia expulsado de diante dos israelitas.

[[v14-33-3]]

^<<v14-33-3,3>>^ Reconstruiu os santuários idólatras que seu pai, Ezequias, havia destruído. Construiu altares para Baal e ergueu postes de Aserá. Também se curvou diante de todos os astros dos céus e lhes prestou culto.

[[v14-33-4]]

^<<v14-33-4,4>>^ Construiu altares idólatras no templo do SENHOR, sobre o qual o SENHOR tinha dito: "Meu nome permanecerá em Jerusalém para sempre".

[[v14-33-5]]

^<<v14-33-5,5>>^ Nos dois pátios do templo do SENHOR, construiu altares para os astros do céu.

[[v14-33-6]]

^<<v14-33-6,6>>^ Manassés também sacrificou seus filhos no fogo no vale de Ben-Hinom. Praticou feitiçaria, adivinhação e magia e consultou médiuns e praticantes do ocultismo. Fez muitas coisas perversas aos olhos do SENHOR e, com isso, provocou sua ira.

[[v14-33-7]]

^<<v14-33-7,7>>^ Manassés chegou a fazer uma imagem esculpida e colocá-la no templo de Deus, sobre o qual Deus tinha dito a Davi e a seu filho Salomão: "Meu nome será honrado para sempre neste templo e em Jerusalém, a cidade que escolhi dentre todas as tribos de Israel.

[[v14-33-8]]

^<<v14-33-8,8>>^ Se os israelitas tiverem o cuidado de obedecer a meus mandamentos, todas as leis, estatutos e decretos que meu servo Moisés lhes deu, não os expulsarei desta terra que dei a seus antepassados".

[[v14-33-9]]

^<<v14-33-9,9>>^ Manassés, porém, levou o povo de Judá e de Jerusalém a fazer coisas piores do que as nações que o SENHOR tinha destruído diante dos israelitas.

[[v14-33-10]]

^<<v14-33-10,10>>^ O SENHOR falou a Manassés e a seu povo, mas eles ignoraram seus avisos.

[[v14-33-11]]

^<<v14-33-11,11>>^ Por isso, o SENHOR enviou os comandantes dos exércitos assírios, e eles capturaram Manassés. Puseram um gancho em seu nariz, o prenderam com correntes de bronze e o levaram para a Babilônia.

[[v14-33-12]]

^<<v14-33-12,12>>^ Em sua angústia, Manassés buscou o SENHOR, seu Deus, e se humilhou com sinceridade diante do Deus de seus antepassados.

[[v14-33-13]]

^<<v14-33-13,13>>^ Quando ele orou, Deus ouviu sua súplica, atendeu a seu pedido e o trouxe de volta a Jerusalém e a seu reino. Então Manassés reconheceu que o SENHOR é Deus.

[[v14-33-14]]

^<<v14-33-14,14>>^ Depois disso, Manassés reconstruiu o muro externo da Cidade de Davi, bem alto, desde o oeste da fonte de Giom, no vale de Cedrom, até a porta do Peixe e ao redor da colina de Ofel. Colocou comandantes militares em todas as cidades fortificadas de Judá.

[[v14-33-15]]

^<<v14-33-15,15>>^ Manassés também removeu do templo do SENHOR os deuses estrangeiros e o ídolo que havia colocado ali. Derrubou todos os altares que havia construído na colina do templo e todos os altares em Jerusalém e os jogou fora da cidade.

[[v14-33-16]]

^<<v14-33-16,16>>^ Depois, restaurou o altar do SENHOR e apresentou sobre ele sacrifícios de paz e ofertas de gratidão. Também incentivou o povo de Judá a adorar o SENHOR, o Deus de Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ O povo continuou a sacrificar naqueles lugares de adoração, mas somente ao SENHOR, seu Deus.

[[v14-33-18]]

^<<v14-33-18,18>>^ Os demais acontecimentos do reinado de Manassés, sua oração a Deus e as palavras que os videntes lhe disseram em nome do SENHOR, o Deus de Israel, estão registrados no Livro dos Reis de Israel .

[[v14-33-19]]

^<<v14-33-19,19>>^ A oração de Manassés, o modo como Deus lhe respondeu e um relato de todos os seus pecados e de sua infidelidade se encontram no Registro dos Videntes . Inclui uma lista dos locais onde ele construiu altares idólatras e levantou postes de Aserá e ídolos antes de se humilhar e se arrepender.

[[v14-33-20]]

^<<v14-33-20,20>>^ Quando Manassés morreu e se reuniu a seus antepassados, foi sepultado em seu palácio. Seu filho Amom foi seu sucessor.

[[v14-33-21]]

^<<v14-33-21,21>>^ Amom tinha 22 anos quando começou a reinar, e reinou em Jerusalém por dois anos.

[[v14-33-22]]

^<<v14-33-22,22>>^ Fez o que era mau aos olhos do SENHOR, como seu pai, Manassés. Adorou todos os ídolos que seu pai havia feito e lhes ofereceu sacrifícios.

[[v14-33-23]]

^<<v14-33-23,23>>^ Mas, ao contrário de seu pai, não se humilhou diante do SENHOR. Em vez disso, Amom pecou ainda mais.

[[v14-33-24]]

^<<v14-33-24,24>>^ Os próprios oficiais de Amom conspiraram contra ele e o assassinaram em seu palácio.

[[v14-33-25]]

^<<v14-33-25,25>>^ O povo de Judá, porém, matou todos que haviam conspirado contra o rei Amom e proclamou seu filho Josias como rei em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[Próximo Capítulo &#62;]