include::./index.adoc[]

[[v14-3-0]]
=== 2 Crônicas, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v14-3-1]]

^<<v14-3-1,1>>^ Então Salomão começou a construir o templo do SENHOR em Jerusalém, no monte Moriá, onde o SENHOR havia aparecido a seu pai, Davi. O templo foi construído na eira de Araúna, o jebuseu, o local escolhido por Davi.

[[v14-3-2]]

^<<v14-3-2,2>>^ A construção começou no segundo dia do segundo mês do quarto ano do reinado de Salomão.

[[v14-3-3]]

^<<v14-3-3,3>>^ O alicerce do templo de Deus construído por Salomão tinha 27 metros de comprimento e 9 metros de largura, conforme a medida antiga.

[[v14-3-4]]

^<<v14-3-4,4>>^ A sala de entrada na frente do templo media 9 metros de largura, a mesma largura do templo, e 9 metros de altura. Salomão revestiu seu interior com ouro puro.

[[v14-3-5]]

^<<v14-3-5,5>>^ Cobriu todas as paredes do salão principal do templo com madeira de cipreste revestida com ouro puro e enfeitada com entalhes de palmeiras e de correntes.

[[v14-3-6]]

^<<v14-3-6,6>>^ Enfeitou as paredes do templo com pedras preciosas e com ouro da terra de Parvaim.

[[v14-3-7]]

^<<v14-3-7,7>>^ Revestiu com ouro as vigas, os batentes, as paredes e as portas de todo o templo e entalhou nas paredes figuras de querubins.

[[v14-3-8]]

^<<v14-3-8,8>>^ Fez o lugar santíssimo com 9 metros de largura, a mesma largura do templo, e 9 metros de comprimento. Revestiu seu interior com 21 toneladas de ouro puro.

[[v14-3-9]]

^<<v14-3-9,9>>^ Cada um dos pregos de ouro pesava 600 gramas. Também revestiu com ouro as paredes das salas superiores.

[[v14-3-10]]

^<<v14-3-10,10>>^ Fez duas figuras em forma de querubins, as revestiu com ouro e as colocou no lugar santíssimo.

[[v14-3-11]]

^<<v14-3-11,11>>^ As asas abertas dos querubins mediam, juntas, 9 metros. Uma das asas do primeiro querubim media 2,25 metros e tocava a parede do templo. A outra asa, que também media 2,25 metros, tocava a asa do segundo querubim.

[[v14-3-12]]

^<<v14-3-12,12>>^ De igual modo, uma das asas do segundo querubim media 2,25 metros e tocava a parede oposta. A outra asa, que também media 2,25 metros, tocava a asa do primeiro querubim.

[[v14-3-13]]

^<<v14-3-13,13>>^ Portanto, as asas abertas dos querubins mediam, juntas, 9 metros. Os querubins ficavam em pé, de frente para o salão principal do templo.

[[v14-3-14]]

^<<v14-3-14,14>>^ Na entrada do lugar santíssimo, colocou uma cortina de linho fino, enfeitada com fio azul, púrpura e vermelho, e bordada com figuras de querubins.

[[v14-3-15]]

^<<v14-3-15,15>>^ Para a frente do templo, fez duas colunas, cada uma com 8,1 metros de altura e com um capitel de 2,25 metros de altura.

[[v14-3-16]]

^<<v14-3-16,16>>^ Fez conjuntos de correntes entrelaçadas e os colocou para enfeitar o alto das colunas. Também fez cem romãs decorativas e as prendeu às correntes.

[[v14-3-17]]

^<<v14-3-17,17>>^ Depois, levantou as duas colunas na frente do templo, uma ao sul da entrada e outra ao norte. Chamou a coluna ao sul de Jaquim, e a coluna ao norte, de Boaz.

'''

xref:014-2-cronicas/014-2-cronicas-002.adoc#v14-2-0[&#60; Capítulo Anterior] | <<v14-3-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[Próximo Capítulo &#62;]