include::./index.adoc[]

[[v2-36-0]]
=== Êxodo, 36
// nvt ?, NVT - Nova Versão Transformadora

[[v2-36-1]]

^<<v2-36-1,1>>^ "O SENHOR deu sabedoria a Bezalel, a Aoliabe e aos demais artesãos talentosos e os capacitou com habilidade e entendimento para realizarem todas as tarefas relacionadas à construção do tabernáculo. Eles o construirão conforme o SENHOR ordenou".

[[v2-36-2]]

^<<v2-36-2,2>>^ Moisés chamou Bezalel, Aoliabe e os demais artesãos especialmente capacitados pelo SENHOR e que estavam dispostos a realizar a obra.

[[v2-36-3]]

^<<v2-36-3,3>>^ Moisés lhes deu os materiais doados pelos israelitas como ofertas para a construção do santuário. O povo, porém, continuava a trazer voluntariamente mais ofertas todas as manhãs.

[[v2-36-4]]

^<<v2-36-4,4>>^ Por fim, os artesãos que estavam trabalhando no santuário interromperam a obra

[[v2-36-5]]

^<<v2-36-5,5>>^ e informaram a Moisés: "O povo trouxe mais que o suficiente para completarmos o trabalho que o SENHOR nos ordenou!".

[[v2-36-6]]

^<<v2-36-6,6>>^ Então Moisés deu a seguinte ordem, que foi transmitida a todo o acampamento: "Homens e mulheres, não preparem mais ofertas para o santuário. Temos o suficiente!". Assim, o povo parou de trazer suas ofertas.

[[v2-36-7]]

^<<v2-36-7,7>>^ Suas contribuições foram mais que suficientes para completar todo o projeto.

[[v2-36-8]]

^<<v2-36-8,8>>^ Os artesãos habilidosos fizeram para o tabernáculo dez cortinas de linho finamente tecido. Bezalel enfeitou as cortinas com fios de tecido azul, roxo e vermelho e com querubins bordados com habilidade.

[[v2-36-9]]

^<<v2-36-9,9>>^ As dez cortinas eram exatamente do mesmo tamanho, com 12,6 metros de comprimento e 1,8 metro de largura.

[[v2-36-10]]

^<<v2-36-10,10>>^ Juntaram cinco das cortinas para formar uma cortina longa e depois juntaram as cinco restantes para formar outra cortina longa.

[[v2-36-11]]

^<<v2-36-11,11>>^ Bezalel fez cinquenta laços de tecido azul e prendeu-os ao longo da borda da última cortina de cada conjunto.

[[v2-36-12]]

^<<v2-36-12,12>>^ Os cinquenta laços ao longo da borda de uma cortina coincidiam com os cinquenta laços ao longo da borda da outra cortina.

[[v2-36-13]]

^<<v2-36-13,13>>^ Em seguida, fez cinquenta colchetes de ouro e prendeu as cortinas longas uma à outra. Desse modo, o tabernáculo foi formado de uma só peça contínua.

[[v2-36-14]]

^<<v2-36-14,14>>^ Fez também onze cortinas de tecido de pelo de cabra para cobrir o tabernáculo.

[[v2-36-15]]

^<<v2-36-15,15>>^ Essas onze cortinas eram todas exatamente do mesmo tamanho, com 13,5 metros de comprimento e 1,8 metro de largura.

[[v2-36-16]]

^<<v2-36-16,16>>^ Bezalel juntou cinco das cortinas para formar uma cortina longa e depois juntou as seis restantes para formar outra cortina longa.

[[v2-36-17]]

^<<v2-36-17,17>>^ Fez cinquenta laços para a borda de cada cortina longa.

[[v2-36-18]]

^<<v2-36-18,18>>^ Fez ainda cinquenta colchetes de bronze para prender as cortinas longas uma à outra. Desse modo, a cobertura da tenda foi formada de uma só peça contínua.

[[v2-36-19]]

^<<v2-36-19,19>>^ Por fim, completou a cobertura da tenda com uma camada protetora feita de peles de carneiro tingidas de vermelho e uma camada de couro fino.

[[v2-36-20]]

^<<v2-36-20,20>>^ Para a estrutura do tabernáculo, Bezalel construiu armações de madeira de acácia.

[[v2-36-21]]

^<<v2-36-21,21>>^ Cada armação tinha 4,5 metros de altura e 67,5 centímetros de largura,

[[v2-36-22]]

^<<v2-36-22,22>>^ com duas hastes na parte inferior de cada armação. Todas as armações eram idênticas.

[[v2-36-23]]

^<<v2-36-23,23>>^ Construiu vinte armações para sustentar as cortinas do lado sul do tabernáculo.

[[v2-36-24]]

^<<v2-36-24,24>>^ Fez também quarenta bases de prata, duas para cada armação, de modo que as hastes se encaixavam firmemente nas bases.

[[v2-36-25]]

^<<v2-36-25,25>>^ Para o lado norte do tabernáculo, construiu outras vinte armações,

[[v2-36-26]]

^<<v2-36-26,26>>^ com quarenta bases de prata, duas bases para cada armação.

[[v2-36-27]]

^<<v2-36-27,27>>^ Fez seis armações para a parte de trás, o lado oeste do tabernáculo,

[[v2-36-28]]

^<<v2-36-28,28>>^ junto com mais duas armações para reforçar os cantos das duas extremidades do tabernáculo.

[[v2-36-29]]

^<<v2-36-29,29>>^ As armações dos cantos foram emparelhadas na parte inferior e firmemente ligadas uma à outra na parte superior com uma argola, formando um só suporte de canto. Ambos os suportes de canto foram feitos dessa maneira.

[[v2-36-30]]

^<<v2-36-30,30>>^ Havia, portanto, oito armações na parte de trás do tabernáculo, encaixadas sobre dezesseis bases de prata, duas bases debaixo de cada armação.

[[v2-36-31]]

^<<v2-36-31,31>>^ Em seguida, fez travessões de madeira de acácia para ligar as armações, cinco travessões para o lado norte do tabernáculo

[[v2-36-32]]

^<<v2-36-32,32>>^ e cinco travessões para o lado sul. Fez também cinco travessões para a parte de trás do tabernáculo, que ficava virada para o oeste.

[[v2-36-33]]

^<<v2-36-33,33>>^ Fez o travessão central ligado a meia altura às armações, estendendo-se de uma ponta à outra do tabernáculo.

[[v2-36-34]]

^<<v2-36-34,34>>^ Revestiu as armações com ouro e fez argolas de ouro para sustentar os travessões. Depois, revestiu com ouro os travessões.

[[v2-36-35]]

^<<v2-36-35,35>>^ Para o interior do tabernáculo, Bezalel confeccionou uma cortina especial de linho fino, trançado com fios de tecido azul, roxo e vermelho e com querubins bordados com habilidade.

[[v2-36-36]]

^<<v2-36-36,36>>^ Fez para a cortina quatro colunas de madeira de acácia e quatro ganchos de ouro. Revestiu as colunas com ouro e apoiou-as sobre quatro bases de prata.

[[v2-36-37]]

^<<v2-36-37,37>>^ Em seguida, fez outra cortina para a entrada da tenda. Confeccionou-a com linho finamente tecido e bordou-a artisticamente, usando fios de tecido azul, roxo e vermelho.

[[v2-36-38]]

^<<v2-36-38,38>>^ Pendurou a cortina em ganchos de ouro presos a cinco colunas. Revestiu com ouro as colunas, seus capitéis e seus ganchos e mandou fundir para elas cinco bases de bronze.

'''

xref:002-exodo/002-exodo-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodo/002-exodo-037.adoc#v2-37-0[Próximo Capítulo &#62;]