include::./index.adoc[]

[[v2-7-0]]
=== Êxodo, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v2-7-1]]

^<<v2-7-1,1>>^ Então o SENHOR disse a Moisés: "Preste atenção ao que vou dizer. Eu o farei parecer Deus para o faraó, e Arão, seu irmão, será seu profeta.

[[v2-7-2]]

^<<v2-7-2,2>>^ Diga a Arão tudo que eu lhe ordenar, e Arão mandará o faraó deixar o povo de Israel sair de sua terra.

[[v2-7-3]]

^<<v2-7-3,3>>^ Contudo, endurecerei o coração do faraó e depois multiplicarei meus sinais e maravilhas na terra do Egito.

[[v2-7-4]]

^<<v2-7-4,4>>^ Mesmo assim, o faraó se recusará a ouvi-lo, de modo que farei minha mão pesar sobre o Egito. Então resgatarei meu exército — meu povo, os israelitas — da terra do Egito com grandes atos de julgamento.

[[v2-7-5]]

^<<v2-7-5,5>>^ Quando eu levantar minha mão e tirar os israelitas do meio deles, os egípcios saberão que eu sou o SENHOR".

[[v2-7-6]]

^<<v2-7-6,6>>^ Moisés e Arão fizeram conforme o SENHOR lhes ordenou.

[[v2-7-7]]

^<<v2-7-7,7>>^ Quando falaram com o faraó, Moisés tinha 80 anos, e Arão, 83.

[[v2-7-8]]

^<<v2-7-8,8>>^ O SENHOR disse a Moisés e a Arão:

[[v2-7-9]]

^<<v2-7-9,9>>^ "O faraó exigirá: ‘Mostre-me um milagre’. Quando ele o fizer, diga a Arão: ‘Tome sua vara e jogue-a no chão, na frente do faraó, e ela se transformará numa serpente’".

[[v2-7-10]]

^<<v2-7-10,10>>^ Então Moisés e Arão foram ver o faraó e fizeram conforme o SENHOR havia ordenado. Arão jogou a vara no chão, diante do faraó e de seus oficiais, e ela se transformou numa serpente.

[[v2-7-11]]

^<<v2-7-11,11>>^ O faraó mandou chamar seus sábios e feiticeiros e, por meio de suas artes mágicas, esses magos egípcios fizeram a mesma coisa:

[[v2-7-12]]

^<<v2-7-12,12>>^ jogaram suas varas no chão, e elas também se transformaram em serpentes. Mas a vara de Arão engoliu as varas dos magos.

[[v2-7-13]]

^<<v2-7-13,13>>^ O coração do faraó, porém, permaneceu endurecido. Ele continuou se recusando a ouvir, exatamente como o SENHOR tinha dito.

[[v2-7-14]]

^<<v2-7-14,14>>^ O SENHOR disse a Moisés: "O coração do faraó é duro, e ele continua se recusando a deixar o povo sair.

[[v2-7-15]]

^<<v2-7-15,15>>^ Portanto, vá ao faraó pela manhã, quando ele estiver descendo até o rio. Pare à margem do Nilo e encontre-se com ele ali. Não se esqueça de levar a vara que se transformou em serpente.

[[v2-7-16]]

^<<v2-7-16,16>>^ Então diga-lhe: ‘O SENHOR, o Deus dos hebreus, me enviou para lhe falar: ‘Deixe meu povo sair para me adorar no deserto’. Até agora, você se recusou a ouvi-lo,

[[v2-7-17]]

^<<v2-7-17,17>>^ por isso, assim diz o SENHOR: ‘Eu lhe mostrarei que sou o SENHOR’. Veja! Com esta vara que tenho na mão, baterei nas águas do Nilo, e elas se transformarão em sangue.

[[v2-7-18]]

^<<v2-7-18,18>>^ Os peixes do rio morrerão, e o rio ficará malcheiroso. Os egípcios não poderão beber de sua água’".

[[v2-7-19]]

^<<v2-7-19,19>>^ O SENHOR disse a Moisés: "Diga a Arão: ‘Tome sua vara e estenda a mão sobre as águas do Egito, sobre todos os seus rios, canais, açudes e reservatórios. Toda a água se transformará em sangue, até mesmo a água armazenada em vasilhas de madeira e pedra’".

[[v2-7-20]]

^<<v2-7-20,20>>^ Moisés e Arão fizeram conforme o SENHOR ordenou. Diante dos olhos do faraó e de todos os seus oficiais, Arão levantou a vara e bateu nas águas do Nilo, e o rio inteiro se transformou em sangue.

[[v2-7-21]]

^<<v2-7-21,21>>^ Os peixes do rio morreram, e a água ficou tão malcheirosa que os egípcios não podiam bebê-la. Havia sangue em toda a terra do Egito.

[[v2-7-22]]

^<<v2-7-22,22>>^ Mais uma vez, porém, os magos do Egito usaram sua mágica e também transformaram água em sangue, e o coração do faraó continuou endurecido. Ele se recusou a ouvir Moisés e Arão, como o SENHOR tinha dito.

[[v2-7-23]]

^<<v2-7-23,23>>^ O faraó voltou para seu palácio e não pensou mais no assunto.

[[v2-7-24]]

^<<v2-7-24,24>>^ Todos os egípcios cavaram às margens do rio para encontrar água potável, pois não podiam beber da água do Nilo.

[[v2-7-25]]

^<<v2-7-25,25>>^ Sete dias se passaram desde o momento em que o SENHOR feriu o Nilo.

'''

xref:002-exodo/002-exodo-006.adoc#v2-6-0[&#60; Capítulo Anterior] | <<v2-7-0,Topo>> | xref:002-exodo/002-exodo-008.adoc#v2-8-0[Próximo Capítulo &#62;]