include::./index.adoc[]

[[v2-18-0]]
=== Êxodo, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v2-18-1]]

^<<v2-18-1,1>>^ Jetro, sogro de Moisés e sacerdote de Midiã, soube de tudo que Deus havia feito por Moisés e seu povo, os israelitas, e de como o SENHOR os havia tirado do Egito.

[[v2-18-2]]

^<<v2-18-2,2>>^ Moisés tinha mandado Zípora, sua mulher, e seus dois filhos de volta para a casa de Jetro, que os acolheu.

[[v2-18-3]]

^<<v2-18-3,3>>^ (O primeiro filho de Moisés se chamava Gérson, pois quando o menino nasceu, Moisés disse: "Sou forasteiro em terra alheia".

[[v2-18-4]]

^<<v2-18-4,4>>^ O segundo filho se chamava Eliézer, pois Moisés disse: "O Deus de meus antepassados foi meu ajudador e me livrou da espada do faraó".)

[[v2-18-5]]

^<<v2-18-5,5>>^ Jetro, sogro de Moisés, foi visitá-lo no deserto, levando consigo a mulher e os dois filhos de Moisés. Quando chegaram, Moisés e o povo estavam acampados perto do monte de Deus.

[[v2-18-6]]

^<<v2-18-6,6>>^ Jetro havia mandado um recado a Moisés, dizendo: "Eu, seu sogro Jetro, estou indo vê-lo com sua mulher e seus dois filhos".

[[v2-18-7]]

^<<v2-18-7,7>>^ Então Moisés saiu ao encontro de seu sogro, curvou-se e o beijou. Depois de perguntarem um ao outro se estavam bem, entraram na tenda de Moisés.

[[v2-18-8]]

^<<v2-18-8,8>>^ Ele contou ao sogro tudo que o SENHOR havia feito ao faraó e aos egípcios em favor de Israel. Contou também dos apuros que tinham passado ao longo do caminho e de como o SENHOR os tinha livrado de todas as dificuldades.

[[v2-18-9]]

^<<v2-18-9,9>>^ Jetro se alegrou imensamente ao ouvir tudo de bom que o SENHOR havia feito por Israel ao libertar o povo das mãos dos egípcios.

[[v2-18-10]]

^<<v2-18-10,10>>^ "Louvado seja o SENHOR!", disse Jetro. "Ele os libertou da mão dos egípcios e do faraó!

[[v2-18-11]]

^<<v2-18-11,11>>^ Agora sei que o SENHOR é maior que todos os outros deuses, pois libertou seu povo da opressão dos arrogantes egípcios."

[[v2-18-12]]

^<<v2-18-12,12>>^ Em seguida, Jetro, sogro de Moisés, ofereceu um holocausto e outros sacrifícios a Deus. Arão e os líderes de Israel vieram e, na presença de Deus, participaram com ele da refeição.

[[v2-18-13]]

^<<v2-18-13,13>>^ No dia seguinte, Moisés sentou-se para resolver problemas que surgiram entre os israelitas. O povo esperou diante dele, em pé, desde a manhã ate a tarde.

[[v2-18-14]]

^<<v2-18-14,14>>^ Quando o sogro de Moisés viu tudo que ele tentava fazer pelo povo, perguntou: "O que você está fazendo com este povo? Por que você se senta sozinho para julgar e os obriga a ficarem de pé diante de você o dia inteiro?".

[[v2-18-15]]

^<<v2-18-15,15>>^ Moisés respondeu: "O povo me procura para conhecer as decisões de Deus.

[[v2-18-16]]

^<<v2-18-16,16>>^ Quando surge algum problema, eles me procuram e eu resolvo a questão entre as partes em conflito. Informo o povo sobre os decretos de Deus e transmito suas instruções".

[[v2-18-17]]

^<<v2-18-17,17>>^ "O que você está fazendo não é bom", disse o sogro de Moisés.

[[v2-18-18]]

^<<v2-18-18,18>>^ "Você ficará esgotado e deixará o povo exausto. É um trabalho pesado demais para uma pessoa só.

[[v2-18-19]]

^<<v2-18-19,19>>^ Agora ouça-me e escute meu conselho, e Deus esteja com você. Continue a ser o representante do povo diante de Deus, apresentando-lhe as questões trazidas pelo povo.

[[v2-18-20]]

^<<v2-18-20,20>>^ Ensine a eles os decretos e as instruções de Deus. Mostre aos israelitas como devem viver e o que devem fazer.

[[v2-18-21]]

^<<v2-18-21,21>>^ No entanto, escolha dentre todo o povo homens capazes e honestos que temam a Deus e odeiem suborno. Nomeie-os líderes de grupos de mil, cem, cinquenta e dez pessoas.

[[v2-18-22]]

^<<v2-18-22,22>>^ Eles deverão estar sempre disponíveis para resolver os problemas cotidianos do povo e só lhe trarão os casos mais difíceis. Deixe que os líderes decidam as questões mais simples por conta própria. Eles dividirão com você o peso da responsabilidade e facilitarão seu trabalho.

[[v2-18-23]]

^<<v2-18-23,23>>^ Se você seguir esse conselho, e se Deus assim lhe ordenar, poderá suportar as pressões, e todo este povo voltará para casa em paz."

[[v2-18-24]]

^<<v2-18-24,24>>^ Moisés aceitou o conselho do sogro e seguiu todas as suas recomendações.

[[v2-18-25]]

^<<v2-18-25,25>>^ Escolheu homens capazes dentre todo o povo de Israel e os nomeou líderes de grupos de mil, cem, cinquenta e dez pessoas.

[[v2-18-26]]

^<<v2-18-26,26>>^ Os homens ficavam à disposição para resolver os problemas cotidianos do povo. Traziam para Moisés os casos mais difíceis, mas cuidavam, eles mesmos, das questões mais simples.

[[v2-18-27]]

^<<v2-18-27,27>>^ Pouco tempo depois, Moisés se despediu de seu sogro, que voltou para sua terra.

'''

xref:002-exodo/002-exodo-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodo/002-exodo-019.adoc#v2-19-0[Próximo Capítulo &#62;]