include::./index.adoc[]

[[v2-38-0]]
=== Êxodo, 38
// nvt ?, NVT - Nova Versão Transformadora

[[v2-38-1]]

^<<v2-38-1,1>>^ Usando madeira de acácia, Bezalel construiu um altar quadrado para o holocausto, com 2,25 metros de largura e comprimento e 1,35 metro de altura.

[[v2-38-2]]

^<<v2-38-2,2>>^ Fez uma ponta em forma de chifre para cada um dos quatro cantos, de modo que as pontas e o altar formavam uma só peça. Revestiu o altar com bronze.

[[v2-38-3]]

^<<v2-38-3,3>>^ Depois, fez os utensílios do altar: baldes para recolher as cinzas, pás, bacias, garfos para a carne e braseiros, todos de bronze.

[[v2-38-4]]

^<<v2-38-4,4>>^ Fez também uma grelha de bronze e a colocou a meia altura do altar, debaixo da borda.

[[v2-38-5]]

^<<v2-38-5,5>>^ Fez quatro argolas de bronze e prendeu-as aos cantos da grelha de bronze, para sustentar as varas usadas para carregar o altar.

[[v2-38-6]]

^<<v2-38-6,6>>^ Fez as varas de madeira de acácia e as revestiu com bronze.

[[v2-38-7]]

^<<v2-38-7,7>>^ Por dentro das argolas dos dois lados do altar, passou as varas usadas para transportá-lo. O altar era oco e feito de tábuas.

[[v2-38-8]]

^<<v2-38-8,8>>^ Bezalel fez a bacia de bronze e seu suporte de bronze com espelhos doados pelas mulheres que serviam à entrada da tenda do encontro.

[[v2-38-9]]

^<<v2-38-9,9>>^ Bezalel fez ainda o pátio, que era fechado com cortinas de linho finamente tecido. As cortinas do lado sul tinham 45 metros de comprimento

[[v2-38-10]]

^<<v2-38-10,10>>^ e eram penduradas em vinte colunas apoiadas firmemente em vinte bases de bronze. Pendurou as cortinas com ganchos e argolas de prata.

[[v2-38-11]]

^<<v2-38-11,11>>^ Colocou do lado norte cortinas idênticas a essas, com 45 metros de comprimento, penduradas em vinte colunas apoiadas firmemente em bases de bronze. Pendurou as cortinas com ganchos e argolas de prata.

[[v2-38-12]]

^<<v2-38-12,12>>^ As cortinas do lado oeste do pátio tinham 22,5 metros de comprimento e eram penduradas com ganchos e argolas de prata em dez colunas apoiadas em dez bases.

[[v2-38-13]]

^<<v2-38-13,13>>^ O lado leste do pátio também tinha 22,5 metros de comprimento.

[[v2-38-14]]

^<<v2-38-14,14>>^ A entrada do pátio ficava do lado leste, situada entre duas cortinas. A cortina do lado sul tinha 6,75 metros de comprimento e era pendurada em três colunas apoiadas em três bases.

[[v2-38-15]]

^<<v2-38-15,15>>^ A cortina do lado norte também tinha 6,75 metros de comprimento e era pendurada em três colunas apoiadas em três bases.

[[v2-38-16]]

^<<v2-38-16,16>>^ Todas as cortinas ao redor do pátio eram de linho finamente tecido.

[[v2-38-17]]

^<<v2-38-17,17>>^ Cada uma das colunas tinha uma base de bronze, e todos os ganchos e argolas eram de prata. Os capitéis das colunas do pátio eram revestidos de prata, e as argolas usadas para pendurar as cortinas eram de prata.

[[v2-38-18]]

^<<v2-38-18,18>>^ Para a entrada do pátio, confeccionou uma cortina de linho finamente tecido e a enfeitou com lindos bordados de fios de tecido azul, roxo e vermelho. A cortina tinha 9 metros de comprimento e 2,25 metros de altura, como as cortinas das divisórias do pátio.

[[v2-38-19]]

^<<v2-38-19,19>>^ Era pendurada em quatro colunas, cada uma apoiada firmemente em sua própria base de bronze. Os capitéis das colunas eram revestidos de prata, e os ganchos e argolas também eram de prata.

[[v2-38-20]]

^<<v2-38-20,20>>^ Todas as estacas usadas para sustentar o tabernáculo e o pátio eram de bronze.

[[v2-38-21]]

^<<v2-38-21,21>>^ Esta é uma relação dos materiais usados na construção do tabernáculo, o santuário da aliança. Os levitas registraram os valores totais conforme Moisés os havia instruído, e Itamar, filho do sacerdote Arão, supervisionou esse trabalho.

[[v2-38-22]]

^<<v2-38-22,22>>^ Bezalel, filho de Uri e neto de Hur, da tribo de Judá, fez tudo exatamente conforme o SENHOR havia ordenado a Moisés.

[[v2-38-23]]

^<<v2-38-23,23>>^ Recebeu a ajuda de Aoliabe, filho de Aisamaque, da tribo de Dã, artesão perito em gravar, projetar e bordar em linho fino com fios de tecido azul, roxo e vermelho.

[[v2-38-24]]

^<<v2-38-24,24>>^ O povo contribuiu com ofertas especiais de ouro que totalizaram 1.024 quilos, calculados de acordo com o siclo do santuário. Esse ouro foi usado em toda a construção do santuário.

[[v2-38-25]]

^<<v2-38-25,25>>^ A comunidade toda de Israel contribuiu com 3.520 quilos de prata, calculados de acordo com o siclo do santuário.

[[v2-38-26]]

^<<v2-38-26,26>>^ Essa prata veio do imposto recolhido de cada homem registrado no censo (o imposto era de uma beca, isto é, meio siclo, conforme o siclo do santuário). O imposto foi arrecadado de 603.550 homens de 20 anos para cima.

[[v2-38-27]]

^<<v2-38-27,27>>^ Para fazer as cem bases para as armações das paredes do santuário e das colunas que sustentavam a cortina interna foram necessários 3.500 quilos de prata, cerca de 35 quilos para cada base.

[[v2-38-28]]

^<<v2-38-28,28>>^ Os 20 quilos de prata restantes foram usados para fazer os ganchos e argolas e para revestir os capitéis das colunas.

[[v2-38-29]]

^<<v2-38-29,29>>^ O povo também contribuiu com uma oferta especial de 2.480 quilos de bronze,

[[v2-38-30]]

^<<v2-38-30,30>>^ usados para fundir as bases das colunas à entrada da tenda do encontro e para o altar de bronze com sua grelha de bronze e todos os utensílios do altar.

[[v2-38-31]]

^<<v2-38-31,31>>^ O bronze também foi usado para fazer as bases das colunas nas quais era pendurada a cortina da entrada do pátio e para todas as estacas ao redor do tabernáculo e o pátio.

'''

xref:002-exodo/002-exodo-037.adoc#v2-37-0[&#60; Capítulo Anterior] | <<v2-38-0,Topo>> | xref:002-exodo/002-exodo-039.adoc#v2-39-0[Próximo Capítulo &#62;]