include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v2-14-1]]

^<<v2-14-1,1>>^ O SENHOR disse a Moisés:

[[v2-14-2]]

^<<v2-14-2,2>>^ "Ordene aos israelitas que deem a volta e acampem em Pi-Hairote, entre Migdol e o mar. Acampem ali, à beira do mar, em frente a Baal-Zefom.

[[v2-14-3]]

^<<v2-14-3,3>>^ O faraó pensará: ‘Os israelitas estão vagando perdidos, prisioneiros do deserto!’.

[[v2-14-4]]

^<<v2-14-4,4>>^ Mais uma vez, endurecerei o coração do faraó, e ele os perseguirá. Planejei tudo isso para mostrar minha glória por meio do faraó e de todo o seu exército. Então os egípcios saberão que eu sou o SENHOR". E os israelitas assim fizeram.

[[v2-14-5]]

^<<v2-14-5,5>>^ Quando o rei do Egito soube que o povo de Israel havia fugido, ele e seus oficiais mudaram de ideia. "O que fizemos?", perguntavam. "Como pudemos deixar todos os escravos israelitas escaparem?"

[[v2-14-6]]

^<<v2-14-6,6>>^ Então o faraó mandou preparar sua carruagem e convocou suas tropas.

[[v2-14-7]]

^<<v2-14-7,7>>^ Levou consigo seiscentos dos melhores carros de guerra, além das demais carruagens de batalha do Egito, cada uma com seu comandante.

[[v2-14-8]]

^<<v2-14-8,8>>^ O SENHOR endureceu o coração do faraó, rei do Egito, para que ele perseguisse os israelitas, que haviam partido triunfantemente.

[[v2-14-9]]

^<<v2-14-9,9>>^ Os egípcios os perseguiram com todas as forças do exército do faraó — todos os seus cavalos e carros de guerra, cavaleiros e tropas — e os alcançaram no acampamento em Pi-Hairote, à beira do mar, em frente a Baal-Zefom.

[[v2-14-10]]

^<<v2-14-10,10>>^ Quando o faraó se aproximava, os israelitas levantaram os olhos e viram os egípcios marchando contra eles. Em pânico, clamaram ao Senhor

[[v2-14-11]]

^<<v2-14-11,11>>^ e disseram a Moisés: "Por que você nos trouxe ao deserto para morrer? Não havia sepulturas no Egito? O que você fez conosco? Por que nos forçou a sair do Egito?

[[v2-14-12]]

^<<v2-14-12,12>>^ Quando ainda estávamos no Egito, não lhe avisamos que isso aconteceria? Dissemos: ‘Deixe-nos em paz! Continuaremos a servir os egípcios. Afinal, é melhor ser escravo no Egito que ser um cadáver no deserto!’".

[[v2-14-13]]

^<<v2-14-13,13>>^ Moisés, porém, disse: "Não tenham medo. Apenas permaneçam firmes e vejam como o SENHOR os resgatará neste dia. Vocês nunca mais verão os egípcios que estão vendo hoje.

[[v2-14-14]]

^<<v2-14-14,14>>^ O próprio SENHOR lutará por vocês. Fiquem calmos!".

[[v2-14-15]]

^<<v2-14-15,15>>^ Então o SENHOR disse a Moisés: "Por que você está clamando a mim? Diga ao povo que marche!

[[v2-14-16]]

^<<v2-14-16,16>>^ Tome sua vara e estenda a mão sobre o mar. Divida as águas para que os israelitas atravessem pelo meio do mar, em terra seca.

[[v2-14-17]]

^<<v2-14-17,17>>^ Endurecerei o coração dos egípcios, e eles virão atrás de vocês. Mostrarei minha glória por meio do faraó e de suas tropas, seus carros de guerra e seus cavaleiros.

[[v2-14-18]]

^<<v2-14-18,18>>^ Quando minha glória se manifestar por meio do faraó e de seus carros de guerra e seus cavaleiros, todo o Egito a verá e saberá que eu sou o SENHOR".

[[v2-14-19]]

^<<v2-14-19,19>>^ Então o anjo de Deus que ia adiante do acampamento de Israel se posicionou atrás do povo. A coluna de nuvem também mudou de lugar; foi para a retaguarda

[[v2-14-20]]

^<<v2-14-20,20>>^ e ficou entre o acampamento egípcio e o acampamento de Israel. A nuvem escura trouxe trevas para os egípcios, mas luz para os israelitas. Com isso, os dois grupos não se aproximaram durante toda a noite.

[[v2-14-21]]

^<<v2-14-21,21>>^ Então Moisés estendeu a mão sobre o mar e, com um forte vento leste, o SENHOR abriu caminho no meio das águas. O vento soprou a noite toda, transformando o fundo do mar em terra seca.

[[v2-14-22]]

^<<v2-14-22,22>>^ E o povo de Israel atravessou pelo meio do mar, caminhando em terra seca, com uma parede de água de cada lado.

[[v2-14-23]]

^<<v2-14-23,23>>^ Os egípcios, com todos os seus cavalos, carros de guerra e cavaleiros, perseguiram o povo até o meio do mar.

[[v2-14-24]]

^<<v2-14-24,24>>^ Mas, pouco antes de amanhecer, do alto da coluna de fogo e de nuvem o SENHOR olhou para o exército dos egípcios e causou grande confusão entre eles.

[[v2-14-25]]

^<<v2-14-25,25>>^ Ele travou as rodas dos carros, dificultando sua condução. "Fujamos daqui, para longe do povo de Israel!", gritaram os egípcios. "O SENHOR está lutando por eles e contra o Egito!"

[[v2-14-26]]

^<<v2-14-26,26>>^ Então o SENHOR disse a Moisés: "Estenda a mão sobre o mar outra vez, e as águas correrão fortemente de volta a seu lugar e cobrirão os egípcios, seus carros de guerra e seus cavaleiros".

[[v2-14-27]]

^<<v2-14-27,27>>^ Assim, ao amanhecer, Moisés estendeu a mão sobre o mar, e as águas voltaram fortemente a seu lugar. Quando os egípcios tentaram escapar, foram de encontro às águas, e o SENHOR os arrastou para dentro do mar.

[[v2-14-28]]

^<<v2-14-28,28>>^ As águas voltaram e cobriram todos os carros de guerra e cavaleiros, todo o exército do faraó. Nenhum dos egípcios que havia perseguido os israelitas até o meio do mar sobreviveu.

[[v2-14-29]]

^<<v2-14-29,29>>^ O povo de Israel, por sua vez, atravessou pelo meio do mar, em terra seca, enquanto as águas formavam uma parede de cada lado.

[[v2-14-30]]

^<<v2-14-30,30>>^ Foi assim que o SENHOR libertou Israel das mãos dos egípcios naquele dia, e os israelitas conseguiam ver os cadáveres dos egípcios na praia.

[[v2-14-31]]

^<<v2-14-31,31>>^ Quando o povo de Israel viu o grande poder do SENHOR contra os egípcios, encheu-se de temor diante dele e passou a confiar no SENHOR e em seu servo Moisés.

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]