include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// nvt ?, NVT - Nova Versão Transformadora

[[v2-35-1]]

^<<v2-35-1,1>>^ Moisés reuniu toda a comunidade de Israel e disse: "Estas são as instruções que o SENHOR mandou que seguissem.

[[v2-35-2]]

^<<v2-35-2,2>>^ Vocês têm seis dias na semana para fazer o trabalho habitual, mas o sétimo dia será um sábado de descanso total, um dia consagrado ao SENHOR. Quem trabalhar no sábado será executado.

[[v2-35-3]]

^<<v2-35-3,3>>^ Nem sequer acendam fogo em suas casas no sábado".

[[v2-35-4]]

^<<v2-35-4,4>>^ Então Moisés disse a toda a comunidade de Israel: "Foi isto que o SENHOR ordenou:

[[v2-35-5]]

^<<v2-35-5,5>>^ entreguem uma oferta ao SENHOR. Todas as pessoas de coração generoso apresentem as seguintes ofertas ao SENHOR: ouro, prata e bronze;

[[v2-35-6]]

^<<v2-35-6,6>>^ fios de tecido azul, roxo e vermelho; linho fino e pelos de cabra para confeccionar tecidos;

[[v2-35-7]]

^<<v2-35-7,7>>^ peles de carneiro tingidas de vermelho e couro fino; madeira de acácia;

[[v2-35-8]]

^<<v2-35-8,8>>^ óleo de oliva para as lâmpadas; especiarias para o óleo da unção e para o incenso perfumado;

[[v2-35-9]]

^<<v2-35-9,9>>^ pedras de ônix e outras pedras preciosas para serem fixadas no colete e no peitoral do sacerdote.

[[v2-35-10]]

^<<v2-35-10,10>>^ "Todos que são artesãos talentosos, venham e façam tudo que o SENHOR ordenou:

[[v2-35-11]]

^<<v2-35-11,11>>^ o tabernáculo, tanto a tenda como a cobertura, os colchetes, as armações, os travessões, as colunas e as bases;

[[v2-35-12]]

^<<v2-35-12,12>>^ a arca e as varas para transportá-la; a tampa da arca, que é o lugar de expiação; a cortina interna que protege a arca;

[[v2-35-13]]

^<<v2-35-13,13>>^ a mesa, as varas para transportá-la e todos os seus utensílios; os pães da presença;

[[v2-35-14]]

^<<v2-35-14,14>>^ o candelabro, seus acessórios, as lâmpadas e o óleo de oliva para a iluminação;

[[v2-35-15]]

^<<v2-35-15,15>>^ o altar de incenso e as varas para transportá-lo; o óleo da unção e o incenso perfumado; a cortina para a entrada do tabernáculo;

[[v2-35-16]]

^<<v2-35-16,16>>^ o altar do holocausto; a grelha de bronze do altar, as varas para transportá-lo e seus utensílios; a bacia de bronze e seu suporte;

[[v2-35-17]]

^<<v2-35-17,17>>^ a cortina para as divisórias do pátio; as colunas e suas bases; a cortina para a entrada do pátio;

[[v2-35-18]]

^<<v2-35-18,18>>^ as estacas do tabernáculo e do pátio e suas cordas;

[[v2-35-19]]

^<<v2-35-19,19>>^ as roupas finamente confeccionadas para os sacerdotes vestirem durante o serviço no lugar santo, as roupas sagradas do sacerdote Arão e de seus filhos que também são sacerdotes".

[[v2-35-20]]

^<<v2-35-20,20>>^ Então toda a comunidade de Israel se despediu de Moisés.

[[v2-35-21]]

^<<v2-35-21,21>>^ Todos aqueles cujo coração foi movido e cujo espírito foi tocado voltaram com ofertas para o SENHOR. Trouxeram todos os materiais necessários para a construção da tenda do encontro, para a realização das cerimônias e para a confecção das roupas sagradas.

[[v2-35-22]]

^<<v2-35-22,22>>^ Todos os que tinham o coração disposto, tanto homens como mulheres, vieram e trouxeram para o SENHOR suas ofertas de ouro na forma de argolas, brincos, anéis e colares. Apresentaram todo tipo de objeto de ouro como oferta especial para o SENHOR.

[[v2-35-23]]

^<<v2-35-23,23>>^ Todos os que tinham fios de tecido azul, roxo e vermelho, linho fino e pelo de cabra para fazer tecidos, peles de carneiro tingidas de vermelho e couro fino os trouxeram.

[[v2-35-24]]

^<<v2-35-24,24>>^ Todos os que tinham objetos de prata e bronze os entregaram como oferta para o SENHOR. E todos os que tinham madeira de acácia a trouxeram para ser usada na obra.

[[v2-35-25]]

^<<v2-35-25,25>>^ Todas as mulheres com habilidade para costurar e fiar prepararam fios de tecido azul, roxo e vermelho e tecido de linho fino.

[[v2-35-26]]

^<<v2-35-26,26>>^ Todas as mulheres que se dispuseram usaram sua habilidade para fiar o pelo de cabra.

[[v2-35-27]]

^<<v2-35-27,27>>^ Os líderes trouxeram pedras de ônix e as outras pedras preciosas para serem colocadas no colete sacerdotal e no peitoral das decisões.

[[v2-35-28]]

^<<v2-35-28,28>>^ Trouxeram também especiarias e óleo de oliva para a iluminação, para o óleo da unção e para o incenso perfumado.

[[v2-35-29]]

^<<v2-35-29,29>>^ Assim, todos os israelitas, todos os homens e mulheres dispostos a ajudar no trabalho que o SENHOR havia ordenado por meio de Moisés, trouxeram suas ofertas e as entregaram de bom grado ao SENHOR.

[[v2-35-30]]

^<<v2-35-30,30>>^ Então Moisés disse ao povo de Israel: "O SENHOR escolheu especificamente Bezalel, filho de Uri e neto de Hur, da tribo de Judá.

[[v2-35-31]]

^<<v2-35-31,31>>^ O SENHOR encheu Bezalel com o Espírito de Deus e lhe deu grande sabedoria, habilidade e perícia para trabalhos artísticos de todo tipo.

[[v2-35-32]]

^<<v2-35-32,32>>^ Ele é exímio artesão, perito no trabalho com ouro, prata e bronze.

[[v2-35-33]]

^<<v2-35-33,33>>^ Tem aptidão para gravar e encravar pedras preciosas e entalhar madeira. É mestre em todo trabalho artístico.

[[v2-35-34]]

^<<v2-35-34,34>>^ O SENHOR capacitou tanto Bezalel como Aoliabe, filho de Aisamaque, da tribo de Dã, para ensinarem suas aptidões a outros.

[[v2-35-35]]

^<<v2-35-35,35>>^ O SENHOR lhes deu habilidade especial para gravar, projetar, tecer e bordar linho fino com fios de tecido azul, roxo e vermelho. São excelentes artesãos e projetistas."

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]