include::./index.adoc[]

[[v2-30-0]]
=== Êxodo, 30
// nvt ?, NVT - Nova Versão Transformadora

[[v2-30-1]]

^<<v2-30-1,1>>^ "Construa um altar de madeira de acácia para queimar incenso.

[[v2-30-2]]

^<<v2-30-2,2>>^ Faça-o quadrado, com 45 centímetros de lado e 90 centímetros de altura, com pontas em forma de chifre nos cantos entalhados da mesma peça de madeira que o altar.

[[v2-30-3]]

^<<v2-30-3,3>>^ Revista o topo, os lados e as pontas do altar com ouro puro e coloque uma moldura de ouro ao seu redor.

[[v2-30-4]]

^<<v2-30-4,4>>^ Faça duas argolas de ouro e prenda-as nos lados opostos do altar, debaixo da moldura de ouro, para sustentar as varas usadas para transportá-lo.

[[v2-30-5]]

^<<v2-30-5,5>>^ Faça as varas de madeira de acácia e revista-as com ouro.

[[v2-30-6]]

^<<v2-30-6,6>>^ Coloque o altar de incenso diante da cortina que protege a arca da aliança, em frente à tampa da arca, o lugar de expiação, que cobre as tábuas da aliança. Ali eu me encontrarei com você.

[[v2-30-7]]

^<<v2-30-7,7>>^ "Todas as manhãs, quando cuidar das lâmpadas, Arão queimará incenso perfumado no altar.

[[v2-30-8]]

^<<v2-30-8,8>>^ E todas as noites, quando acender as lâmpadas, ele queimará incenso novamente na presença do SENHOR. Esse ato deverá ser repetido de geração em geração.

[[v2-30-9]]

^<<v2-30-9,9>>^ Não ofereçam sobre o altar incenso algum que não seja sagrado e não o usem para holocaustos, ofertas de cereal ou ofertas derramadas.

[[v2-30-10]]

^<<v2-30-10,10>>^ "Uma vez por ano, Arão fará expiação pelo altar, aplicando em suas pontas o sangue da oferta realizada para a expiação pelo pecado do povo. Essa cerimônia será realizada todos os anos de geração em geração, pois esse é o altar santíssimo do SENHOR".

[[v2-30-11]]

^<<v2-30-11,11>>^ Então o SENHOR disse a Moisés:

[[v2-30-12]]

^<<v2-30-12,12>>^ "Toda vez que você fizer o censo dos israelitas, cada homem que for contado pagará ao SENHOR um resgate por si mesmo. Com isso, nenhuma praga ferirá o povo quando você o contar.

[[v2-30-13]]

^<<v2-30-13,13>>^ Cada pessoa contada entregará uma pequena quantidade de prata como oferta sagrada ao SENHOR. (O pagamento corresponderá a meio siclo, com base no siclo padrão do santuário, equivalente a doze gramas.)

[[v2-30-14]]

^<<v2-30-14,14>>^ Todos os homens de 20 anos para cima entregarão ao SENHOR essa oferta sagrada.

[[v2-30-15]]

^<<v2-30-15,15>>^ Quando entregarem ao SENHOR a oferta para fazer expiação pela vida deles, os ricos não darão mais que a quantia especificada, e os pobres não darão menos.

[[v2-30-16]]

^<<v2-30-16,16>>^ Receba o dinheiro de resgate dos israelitas e use-o para cuidar da tenda do encontro. Será uma lembrança diante do SENHOR em favor dos israelitas e fará expiação pela vida deles".

[[v2-30-17]]

^<<v2-30-17,17>>^ O SENHOR também disse a Moisés:

[[v2-30-18]]

^<<v2-30-18,18>>^ "Faça uma bacia de bronze com um suporte de bronze para a lavagem cerimonial. Coloque-a entre a tenda do encontro e o altar e encha-a de água.

[[v2-30-19]]

^<<v2-30-19,19>>^ Ali, Arão e seus filhos lavarão as mãos e os pés.

[[v2-30-20]]

^<<v2-30-20,20>>^ Cada vez que entrarem na tenda do encontro, deverão se lavar com água; do contrário, morrerão. Cada vez que se aproximarem do altar para servir ao SENHOR e queimar ofertas especiais para ele,

[[v2-30-21]]

^<<v2-30-21,21>>^ deverão lavar as mãos e os pés; do contrário, morrerão. Essa é uma lei permanente para Arão e seus descendentes e deve ser cumprida de geração em geração".

[[v2-30-22]]

^<<v2-30-22,22>>^ O SENHOR disse ainda a Moisés:

[[v2-30-23]]

^<<v2-30-23,23>>^ "Junte as seguintes especiarias da melhor qualidade: seis quilos de mirra líquida, três quilos de canela perfumada, três quilos de cálamo perfumado,

[[v2-30-24]]

^<<v2-30-24,24>>^ e seis quilos de cássia, medidos de acordo com o siclo do santuário. Junte também quatro litros de azeite.

[[v2-30-25]]

^<<v2-30-25,25>>^ Usando as técnicas de um perfumista habilidoso, misture esses ingredientes para fazer o óleo sagrado para a unção.

[[v2-30-26]]

^<<v2-30-26,26>>^ Use esse óleo sagrado para ungir a tenda do encontro, a arca da aliança,

[[v2-30-27]]

^<<v2-30-27,27>>^ a mesa e todos os seus utensílios, o candelabro e todos os seus acessórios, o altar de incenso,

[[v2-30-28]]

^<<v2-30-28,28>>^ o altar do holocausto e todos os seus utensílios, e a bacia com o seu suporte.

[[v2-30-29]]

^<<v2-30-29,29>>^ Consagre-os para que sejam absolutamente santos. Depois disso, tudo que tiver contato com eles também se tornará santo.

[[v2-30-30]]

^<<v2-30-30,30>>^ "Unja também Arão e seus filhos e consagre-os para que me sirvam como sacerdotes.

[[v2-30-31]]

^<<v2-30-31,31>>^ E diga ao povo de Israel: ‘Este óleo sagrado é reservado para mim de geração em geração.

[[v2-30-32]]

^<<v2-30-32,32>>^ Jamais usem o óleo para ungir qualquer outra pessoa e nunca preparem uma mistura igual a essa para si mesmos. Ele é sagrado e deve ser tratado como tal.

[[v2-30-33]]

^<<v2-30-33,33>>^ Quem preparar uma mistura igual a essa ou ungir com ela alguém que não seja sacerdote será eliminado do meio do povo’".

[[v2-30-34]]

^<<v2-30-34,34>>^ Em seguida, o SENHOR disse a Moisés: "Junte especiarias perfumadas: gotas de resina, conchas de moluscos e gálbano. Misture-as com incenso puro, tudo em quantidades iguais.

[[v2-30-35]]

^<<v2-30-35,35>>^ Usando as técnicas de um perfumista, misture as especiarias e acrescente um pouco de sal, a fim de produzir um incenso puro e santo.

[[v2-30-36]]

^<<v2-30-36,36>>^ Moa uma parte da mistura até formar um pó bem fino e coloque-o diante da arca da aliança, na tenda do encontro, onde me encontrarei com você. Considerem o incenso algo santíssimo.

[[v2-30-37]]

^<<v2-30-37,37>>^ Jamais usem essa fórmula para preparar incenso para si mesmos. Ele é reservado para o SENHOR e deve ser considerado santo.

[[v2-30-38]]

^<<v2-30-38,38>>^ Quem fizer incenso igual a esse para uso pessoal será eliminado do meio do povo".

'''

xref:002-exodo/002-exodo-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodo/002-exodo-031.adoc#v2-31-0[Próximo Capítulo &#62;]