include::./index.adoc[]

[[v2-31-0]]
=== Êxodo, 31
// nvt ?, NVT - Nova Versão Transformadora

[[v2-31-1]]

^<<v2-31-1,1>>^ O SENHOR disse a Moisés:

[[v2-31-2]]

^<<v2-31-2,2>>^ "Veja, escolhi especificamente Bezalel, filho de Uri e neto de Hur, da tribo de Judá.

[[v2-31-3]]

^<<v2-31-3,3>>^ Enchi-o do Espírito de Deus e lhe dei grande sabedoria, habilidade e perícia para trabalhos artísticos de todo tipo.

[[v2-31-4]]

^<<v2-31-4,4>>^ Ele é exímio artesão, perito no trabalho com ouro, prata e bronze.

[[v2-31-5]]

^<<v2-31-5,5>>^ Tem aptidão para gravar e encravar pedras preciosas e entalhar madeira. É mestre em todo trabalho artístico.

[[v2-31-6]]

^<<v2-31-6,6>>^ "Para ajudá-lo, designei pessoalmente Aoliabe, filho de Aisamaque, da tribo de Dã. Além disso, conferi habilidade especial a todos os artesãos de talento para que façam tudo que lhe ordenei:

[[v2-31-7]]

^<<v2-31-7,7>>^ a tenda do encontro; a arca da aliança; a tampa da arca, que é o lugar de expiação; todos os objetos do tabernáculo;

[[v2-31-8]]

^<<v2-31-8,8>>^ a mesa e seus utensílios; o candelabro de ouro puro e todos os seus acessórios; o altar de incenso;

[[v2-31-9]]

^<<v2-31-9,9>>^ o altar do holocausto e todos os seus utensílios; a bacia de bronze e seu suporte;

[[v2-31-10]]

^<<v2-31-10,10>>^ o vestuário finamente confeccionado: as roupas sagradas para o sacerdote Arão e as roupas para seus filhos usarem em seu serviço como sacerdotes;

[[v2-31-11]]

^<<v2-31-11,11>>^ o óleo da unção; o incenso perfumado para o lugar santo. Os artesãos deverão fazer tudo conforme eu lhe ordenei".

[[v2-31-12]]

^<<v2-31-12,12>>^ Em seguida, o SENHOR disse a Moisés:

[[v2-31-13]]

^<<v2-31-13,13>>^ "Diga ao povo de Israel: ‘Guardem o meu sábado, pois ele é um sinal entre mim e vocês de geração em geração, para que saibam que eu sou o SENHOR, que os santifica.

[[v2-31-14]]

^<<v2-31-14,14>>^ Guardem o sábado, pois é dia santo para vocês. Quem o profanar será executado; quem trabalhar nesse dia será eliminado do meio do povo.

[[v2-31-15]]

^<<v2-31-15,15>>^ Vocês têm seis dias na semana para fazer os trabalhos habituais, mas o sétimo dia será um sábado de descanso total, um dia consagrado ao SENHOR. Quem trabalhar no sábado será executado.

[[v2-31-16]]

^<<v2-31-16,16>>^ Os israelitas guardarão o sábado, celebrando-o de geração em geração, como uma aliança para sempre.

[[v2-31-17]]

^<<v2-31-17,17>>^ É um sinal permanente entre mim e o povo de Israel, pois em seis dias o SENHOR fez os céus e a terra, mas no sétimo dia descansou e se revigorou".

[[v2-31-18]]

^<<v2-31-18,18>>^ Quando o SENHOR terminou de falar com Moisés no monte Sinai, entregou-lhe as duas tábuas de pedra gravadas com os termos da aliança, escritas pelo dedo de Deus.

'''

xref:002-exodo/002-exodo-030.adoc#v2-30-0[&#60; Capítulo Anterior] | <<v2-31-0,Topo>> | xref:002-exodo/002-exodo-032.adoc#v2-32-0[Próximo Capítulo &#62;]