include::./index.adoc[]

[[v2-11-0]]
=== Êxodo, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v2-11-1]]

^<<v2-11-1,1>>^ Então o SENHOR disse a Moisés: "Atingirei o faraó e a terra do Egito com mais uma praga. Depois disso, o faraó os deixará sair de seu território. Quando, por fim, ele permitir que saiam, praticamente os expulsará.

[[v2-11-2]]

^<<v2-11-2,2>>^ Diga a todos os homens e mulheres israelitas que peçam objetos de prata e ouro a seus vizinhos egípcios".

[[v2-11-3]]

^<<v2-11-3,3>>^ (O SENHOR havia feito os egípcios verem o povo com bons olhos. Moisés era tido em alta consideração na terra do Egito e respeitado tanto pelos oficiais do faraó como pelo povo egípcio.)

[[v2-11-4]]

^<<v2-11-4,4>>^ Moisés disse: "Assim diz o SENHOR: À meia-noite de hoje, passarei pelo meio do Egito.

[[v2-11-5]]

^<<v2-11-5,5>>^ Morrerão todos os filhos mais velhos do sexo masculino, em todas as famílias do Egito, desde o filho mais velho do faraó, sentado em seu trono, até o filho mais velho da serva mais humilde que trabalha no moinho. Até mesmo os primeiros machos dentre todos os animais morrerão.

[[v2-11-6]]

^<<v2-11-6,6>>^ Então se ouvirá um grande lamento na terra do Egito, um lamento como nunca houve e nunca mais haverá.

[[v2-11-7]]

^<<v2-11-7,7>>^ Quanto aos israelitas, porém, nem um cão latirá contra eles ou seus animais. Com isso vocês saberão que o SENHOR faz distinção entre os egípcios e os israelitas.

[[v2-11-8]]

^<<v2-11-8,8>>^ Todos os oficiais do Egito virão até mim e se curvarão, suplicando: ‘Por favor, vá embora! Saia logo do Egito e leve com você todo este povo que o segue!’. Só então eu sairei!". E, ardendo de ira, Moisés saiu da presença do faraó.

[[v2-11-9]]

^<<v2-11-9,9>>^ O SENHOR tinha avisado a Moisés: "O faraó não lhe dará ouvidos, por isso farei milagres ainda mais poderosos na terra do Egito".

[[v2-11-10]]

^<<v2-11-10,10>>^ Moisés e Arão fizeram todos esses milagres na presença do faraó, mas o SENHOR lhe endureceu o coração, e ele se recusou a deixar o povo de Israel sair de sua terra.

'''

xref:002-exodo/002-exodo-010.adoc#v2-10-0[&#60; Capítulo Anterior] | <<v2-11-0,Topo>> | xref:002-exodo/002-exodo-012.adoc#v2-12-0[Próximo Capítulo &#62;]