include::./index.adoc[]

[[v2-25-0]]
=== Êxodo, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v2-25-1]]

^<<v2-25-1,1>>^ O SENHOR disse a Moisés:

[[v2-25-2]]

^<<v2-25-2,2>>^ "Diga ao povo de Israel que me traga suas ofertas. Aceite as contribuições de todos cujo coração os dispuser a doar.

[[v2-25-3]]

^<<v2-25-3,3>>^ Aqui está uma lista das ofertas que você aceitará deles: ouro, prata e bronze;

[[v2-25-4]]

^<<v2-25-4,4>>^ fios de tecido azul, roxo e vermelho; linho fino e pelos de cabra para confeccionar tecido;

[[v2-25-5]]

^<<v2-25-5,5>>^ peles de carneiro tingidas de vermelho e couro fino; madeira de acácia;

[[v2-25-6]]

^<<v2-25-6,6>>^ óleo de oliva para as lâmpadas; especiarias para o óleo da unção e para o incenso perfumado;

[[v2-25-7]]

^<<v2-25-7,7>>^ pedras de ônix e outras pedras preciosas para serem fixadas no colete e no peitoral do sacerdote.

[[v2-25-8]]

^<<v2-25-8,8>>^ "Instrua os israelitas a construírem para mim um santuário, para que eu viva no meio deles.

[[v2-25-9]]

^<<v2-25-9,9>>^ Devem fazer esse tabernáculo e sua mobília de acordo com o modelo que eu lhe mostrarei."

[[v2-25-10]]

^<<v2-25-10,10>>^ "Faça para mim uma arca de madeira de acácia, com 1,15 metro de comprimento, 67,5 centímetros de largura e 67,5 centímetros de altura.

[[v2-25-11]]

^<<v2-25-11,11>>^ Revista-a com ouro puro por dentro e por fora e coloque uma moldura de ouro ao seu redor.

[[v2-25-12]]

^<<v2-25-12,12>>^ Mande fundir quatro argolas de ouro e prenda-as aos quatro pés da arca, duas argolas de cada lado.

[[v2-25-13]]

^<<v2-25-13,13>>^ Faça varas de madeira de acácia e revista-as com ouro.

[[v2-25-14]]

^<<v2-25-14,14>>^ Passe-as por dentro das argolas dos lados da arca para transportá-la.

[[v2-25-15]]

^<<v2-25-15,15>>^ Essas varas ficarão dentro das argolas; nunca as remova.

[[v2-25-16]]

^<<v2-25-16,16>>^ Coloque dentro da arca as tábuas da aliança que eu lhe darei.

[[v2-25-17]]

^<<v2-25-17,17>>^ "Faça a tampa da arca, que é o lugar de expiação, de ouro puro. Deve medir 1,15 metro de comprimento e 67,5 centímetros de largura.

[[v2-25-18]]

^<<v2-25-18,18>>^ Em seguida, faça dois querubins de ouro batido e coloque um em cada extremidade da tampa.

[[v2-25-19]]

^<<v2-25-19,19>>^ Modele um querubim em cada extremidade da tampa, para formar uma só peça de ouro com a tampa.

[[v2-25-20]]

^<<v2-25-20,20>>^ Os querubins ficarão de frente um para o outro, com o rosto voltado para a tampa da arca. Estenderão as asas sobre a tampa para protegê-la.

[[v2-25-21]]

^<<v2-25-21,21>>^ Coloque dentro da arca as tábuas da aliança que eu lhe darei. Ponha a tampa sobre a arca.

[[v2-25-22]]

^<<v2-25-22,22>>^ Ali, sobre a tampa, que é o lugar de expiação, entre os querubins de ouro que estão sobre a arca da aliança, virei ao seu encontro e falarei com você. Dali eu lhe darei meus mandamentos para o povo de Israel."

[[v2-25-23]]

^<<v2-25-23,23>>^ "Faça também uma mesa de madeira de acácia com 90 centímetros de comprimento, 45 centímetros de largura e 67,5 centímetros de altura.

[[v2-25-24]]

^<<v2-25-24,24>>^ Revista-a com ouro puro e coloque uma moldura de ouro ao seu redor.

[[v2-25-25]]

^<<v2-25-25,25>>^ Enfeite-a com uma borda de 8 centímetros de largura e com uma moldura de ouro ao redor da borda.

[[v2-25-26]]

^<<v2-25-26,26>>^ Faça quatro argolas de ouro para a mesa e prenda-as aos quatro cantos, junto aos quatro pés.

[[v2-25-27]]

^<<v2-25-27,27>>^ Prenda as argolas junto à borda para sustentar as varas que serão usadas para transportar a mesa.

[[v2-25-28]]

^<<v2-25-28,28>>^ Faça essas varas de madeira de acácia e revista-as com ouro; com elas a mesa será carregada.

[[v2-25-29]]

^<<v2-25-29,29>>^ Faça recipientes especiais de ouro puro para a mesa: tigelas, colheres, vasilhas e jarras, que serão usados para as ofertas derramadas.

[[v2-25-30]]

^<<v2-25-30,30>>^ Coloque sobre a mesa os pães da presença, de modo que fiquem diante de mim o tempo todo."

[[v2-25-31]]

^<<v2-25-31,31>>^ "Faça um candelabro de ouro puro batido. Todo o candelabro e seus enfeites formarão uma só peça: a base, a haste central, as lâmpadas, os botões e as flores.

[[v2-25-32]]

^<<v2-25-32,32>>^ Da haste central sairão seis ramos, três de cada lado.

[[v2-25-33]]

^<<v2-25-33,33>>^ Cada um dos seis ramos terá três lâmpadas em forma de flor de amendoeira, com botões e pétalas.

[[v2-25-34]]

^<<v2-25-34,34>>^ A haste central do candelabro terá quatro lâmpadas em forma de flor de amendoeira, cada uma com botões e flores.

[[v2-25-35]]

^<<v2-25-35,35>>^ Também haverá um botão de amendoeira debaixo de cada par dos seis ramos que saem da haste central.

[[v2-25-36]]

^<<v2-25-36,36>>^ Os botões de amendoeira e os ramos formarão uma só peça com a haste central e serão feitos de ouro puro batido.

[[v2-25-37]]

^<<v2-25-37,37>>^ Em seguida, faça sete lâmpadas para o candelabro e posicione-as de modo que reflitam a luz para a frente.

[[v2-25-38]]

^<<v2-25-38,38>>^ Os cortadores de pavio e os apagadores também serão de ouro puro.

[[v2-25-39]]

^<<v2-25-39,39>>^ Serão necessários 35 quilos de ouro puro para o candelabro e seus acessórios.

[[v2-25-40]]

^<<v2-25-40,40>>^ "Cuide para que tudo seja feito de acordo com o modelo que eu lhe mostrei aqui no monte."

'''

xref:002-exodo/002-exodo-024.adoc#v2-24-0[&#60; Capítulo Anterior] | <<v2-25-0,Topo>> | xref:002-exodo/002-exodo-026.adoc#v2-26-0[Próximo Capítulo &#62;]