include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// nvt ?, NVT - Nova Versão Transformadora

[[v2-37-1]]

^<<v2-37-1,1>>^ Em seguida, Bezalel fez uma arca de madeira de acácia, com 1,15 metro de comprimento, 67,5 centímetros de largura e 67,5 centímetros de altura.

[[v2-37-2]]

^<<v2-37-2,2>>^ Revestiu-a com ouro puro por dentro e por fora e fez uma moldura de ouro ao seu redor.

[[v2-37-3]]

^<<v2-37-3,3>>^ Mandou fundir quatro argolas de ouro e prendeu-as aos quatro pés da arca, duas argolas de cada lado.

[[v2-37-4]]

^<<v2-37-4,4>>^ Fez varas de madeira de acácia e revestiu-as com ouro.

[[v2-37-5]]

^<<v2-37-5,5>>^ Passou-as por dentro das argolas dos lados da arca para transportá-la.

[[v2-37-6]]

^<<v2-37-6,6>>^ Fez ainda a tampa da arca, o lugar de expiação, de ouro puro. Media 1,15 metro de comprimento e 67,5 centímetros de largura.

[[v2-37-7]]

^<<v2-37-7,7>>^ Fez dois querubins de ouro batido e colocou um em cada extremidade da tampa.

[[v2-37-8]]

^<<v2-37-8,8>>^ Modelou o querubim em cada extremidade da tampa de modo a formar uma só peça de ouro com a tampa.

[[v2-37-9]]

^<<v2-37-9,9>>^ Os querubins ficavam de frente um para o outro, com o rosto voltado para a tampa da arca. Estendiam suas asas sobre a tampa para cobri-la.

[[v2-37-10]]

^<<v2-37-10,10>>^ Bezalel fez a mesa de madeira de acácia com 90 centímetros de comprimento, 45 centímetros de largura e 67,5 centímetros de altura.

[[v2-37-11]]

^<<v2-37-11,11>>^ Revestiu-a com ouro puro e colocou uma moldura de ouro ao seu redor.

[[v2-37-12]]

^<<v2-37-12,12>>^ Enfeitou-a com uma borda de 8 centímetros de largura e com uma moldura de ouro ao redor da borda.

[[v2-37-13]]

^<<v2-37-13,13>>^ Fez quatro argolas de ouro para a mesa e prendeu-as aos quatro cantos, junto aos quatro pés.

[[v2-37-14]]

^<<v2-37-14,14>>^ Prendeu as argolas junto da borda para sustentar as varas usadas para transportar a mesa.

[[v2-37-15]]

^<<v2-37-15,15>>^ Fez essas varas de madeira de acácia e revestiu-as com ouro.

[[v2-37-16]]

^<<v2-37-16,16>>^ Fez ainda recipientes especiais de ouro puro para a mesa: tigelas, colheres, vasilhas e jarras para as ofertas derramadas.

[[v2-37-17]]

^<<v2-37-17,17>>^ Bezalel fez um candelabro de ouro puro batido. Todo o candelabro e seus enfeites formavam uma só peça: a base, a haste central, as lâmpadas, os botões e as flores.

[[v2-37-18]]

^<<v2-37-18,18>>^ Da haste central saíam seis ramos, três de cada lado.

[[v2-37-19]]

^<<v2-37-19,19>>^ Cada um dos seis ramos tinha três lâmpadas em forma de flor de amendoeira, com botões e flores.

[[v2-37-20]]

^<<v2-37-20,20>>^ A haste central do candelabro tinha quatro lâmpadas em forma de flor de amendoeira, cada uma com botões e flores.

[[v2-37-21]]

^<<v2-37-21,21>>^ Havia um botão de amendoeira debaixo de cada par dos seis ramos que saíam da haste central.

[[v2-37-22]]

^<<v2-37-22,22>>^ Os botões de amendoeira e os ramos formavam uma só peça com a haste central e eram feitos de ouro puro batido.

[[v2-37-23]]

^<<v2-37-23,23>>^ Fez também sete lâmpadas para o candelabro, cortadores de pavio e apagadores, todos de ouro puro.

[[v2-37-24]]

^<<v2-37-24,24>>^ Foram necessários 35 quilos de ouro puro para o candelabro e seus acessórios.

[[v2-37-25]]

^<<v2-37-25,25>>^ Depois, Bezalel usou madeira de acácia para construir o altar de incenso. Ele o fez quadrado, com 45 centímetros de lado e 90 centímetros de altura, com pontas em forma de chifre nos cantos entalhados da mesma peça de madeira que o altar.

[[v2-37-26]]

^<<v2-37-26,26>>^ Revestiu o topo, os lados e as pontas do altar com ouro puro e fez uma moldura de ouro ao seu redor.

[[v2-37-27]]

^<<v2-37-27,27>>^ Fez duas argolas de ouro e prendeu-as nos lados opostos do altar, debaixo da moldura de ouro, para sustentar as varas usadas para transportá-lo.

[[v2-37-28]]

^<<v2-37-28,28>>^ Fez as varas de madeira de acácia e revestiu-as com ouro.

[[v2-37-29]]

^<<v2-37-29,29>>^ Em seguida, preparou o óleo sagrado da unção e o incenso perfumado usando as técnicas de um perfumista.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]