include::./index.adoc[]

[[v2-8-0]]
=== Êxodo, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v2-8-1]]

^<<v2-8-1,1>>^ Então o SENHOR disse a Moisés: "Volte ao faraó e anuncie: ‘Assim diz o SENHOR: Deixe meu povo sair para me adorar.

[[v2-8-2]]

^<<v2-8-2,2>>^ Se você se recusar a deixá-lo sair, enviarei uma praga de rãs sobre todo o seu território.

[[v2-8-3]]

^<<v2-8-3,3>>^ O rio Nilo fervilhará de rãs. Elas subirão do rio e invadirão seu palácio, e até mesmo seu quarto e sua cama. Entrarão nas casas de seus oficiais e de seu povo. Saltarão para dentro dos fornos e das tigelas de amassar pão.

[[v2-8-4]]

^<<v2-8-4,4>>^ As rãs avançarão sobre você, sobre seu povo e sobre todos os seus oficiais’".

[[v2-8-5]]

^<<v2-8-5,5>>^ O SENHOR também disse a Moisés: "Diga a Arão: ‘Estenda a vara que traz em sua mão sobre todos os rios, canais e açudes do Egito e faça subir rãs sobre toda a terra’".

[[v2-8-6]]

^<<v2-8-6,6>>^ Arão estendeu a mão sobre as águas do Egito, e as rãs subiram e cobriram toda a terra.

[[v2-8-7]]

^<<v2-8-7,7>>^ Os magos, porém, usaram suas artes mágicas para imitar a praga e também fizeram aparecer rãs sobre a terra do Egito.

[[v2-8-8]]

^<<v2-8-8,8>>^ Então o faraó convocou Moisés e Arão e disse: "Supliquem ao SENHOR que afaste as rãs de mim e de meu povo. Deixarei seu povo sair para oferecer sacrifícios ao SENHOR".

[[v2-8-9]]

^<<v2-8-9,9>>^ "Pois escolha a hora!", respondeu Moisés. "Diga-me quando deseja que eu suplique pelo faraó, por seus oficiais e por seu povo. Então o faraó e suas casas ficarão livres das rãs, e elas permanecerão apenas no rio Nilo."

[[v2-8-10]]

^<<v2-8-10,10>>^ "Que seja amanhã", disse o faraó. "Será como o faraó disse", respondeu Moisés. "Então saberá que não há ninguém como o SENHOR, nosso Deus.

[[v2-8-11]]

^<<v2-8-11,11>>^ As rãs deixarão o faraó e suas casas, seus oficiais e seu povo e permanecerão apenas no rio Nilo."

[[v2-8-12]]

^<<v2-8-12,12>>^ Moisés e Arão saíram do palácio do faraó, e Moisés clamou ao SENHOR a respeito das rãs que ele havia mandado para afligir o faraó.

[[v2-8-13]]

^<<v2-8-13,13>>^ O SENHOR fez exatamente conforme Moisés tinha dito. Todas as rãs nas casas, nos pátios e nos campos morreram.

[[v2-8-14]]

^<<v2-8-14,14>>^ Os egípcios as juntaram em montões, e um fedor terrível encheu a terra.

[[v2-8-15]]

^<<v2-8-15,15>>^ Mas, quando o faraó percebeu que a situação havia melhorado, seu coração se endureceu, e ele se recusou a dar ouvidos a Moisés e a Arão, como o SENHOR tinha dito.

[[v2-8-16]]

^<<v2-8-16,16>>^ Então o SENHOR disse a Moisés: "Diga a Arão: ‘Estenda a vara e bata no chão. O pó se transformará em enxames de piolhos em toda a terra do Egito’".

[[v2-8-17]]

^<<v2-8-17,17>>^ Moisés e Arão assim fizeram. Quando Arão estendeu a mão e bateu no chão com a vara, piolhos infestaram toda a terra e cobriram os egípcios e seus animais. Todo o pó da terra do Egito se transformou em piolhos.

[[v2-8-18]]

^<<v2-8-18,18>>^ Os magos do faraó tentaram fazer o mesmo com suas artes mágicas, mas não conseguiram. E os piolhos cobriram tudo, tanto as pessoas como os animais.

[[v2-8-19]]

^<<v2-8-19,19>>^ "Isso é o dedo de Deus!", exclamaram os magos ao faraó. Mas o coração do faraó continuou endurecido. Recusou-se a ouvi-los, como o SENHOR tinha dito.

[[v2-8-20]]

^<<v2-8-20,20>>^ Em seguida, o SENHOR disse a Moisés: "Levante-se cedo amanhã e coloque-se diante do faraó quando ele descer ao rio. Diga-lhe: ‘Assim diz o SENHOR: Deixe meu povo sair para me adorar.

[[v2-8-21]]

^<<v2-8-21,21>>^ Se você se recusar, enviarei enxames de moscas sobre você, seus oficiais, seu povo e sobre todas as casas. Os lares dos egípcios e todo o chão ficarão cheios de moscas.

[[v2-8-22]]

^<<v2-8-22,22>>^ Desta vez, porém, pouparei a região de Gósen, onde meu povo vive. Lá, não aparecerão moscas. Então você saberá que eu sou o SENHOR e que estou presente até mesmo no meio de sua terra.

[[v2-8-23]]

^<<v2-8-23,23>>^ Farei clara distinção entre o meu povo e o seu. Esse sinal acontecerá amanhã’".

[[v2-8-24]]

^<<v2-8-24,24>>^ O SENHOR fez exatamente o que disse. Um denso enxame de moscas encheu o palácio do faraó e as casas de seus oficiais. Todo o Egito ficou em estado de calamidade por causa das moscas.

[[v2-8-25]]

^<<v2-8-25,25>>^ O faraó mandou chamar Moisés e Arão e disse: "Vão e ofereçam sacrifícios ao seu Deus. Mas façam-no aqui mesmo, nesta terra".

[[v2-8-26]]

^<<v2-8-26,26>>^ "Não seria certo", respondeu Moisés. "Os sacrifícios que oferecemos ao SENHOR, nosso Deus, são detestáveis aos egípcios. Se apresentarmos aqui mesmo nossos sacrifícios, que os egípcios consideram detestáveis, eles nos apedrejarão.

[[v2-8-27]]

^<<v2-8-27,27>>^ Para oferecer sacrifícios ao SENHOR, nosso Deus, precisamos fazer uma viagem de três dias ao deserto, como ele ordenou."

[[v2-8-28]]

^<<v2-8-28,28>>^ "Podem ir", respondeu o faraó. "Deixarei que viajem ao deserto para oferecer sacrifícios ao SENHOR, seu Deus, mas não se afastem demais. E supliquem por mim."

[[v2-8-29]]

^<<v2-8-29,29>>^ Moisés respondeu: "Assim que sairmos de sua presença, suplicaremos ao SENHOR, e amanhã os enxames de moscas deixarão o faraó, seus oficiais e todo o seu povo. Mas fique avisado, ó faraó, de que não deve mentir novamente, recusando-se a deixar o povo sair para sacrificar ao SENHOR".

[[v2-8-30]]

^<<v2-8-30,30>>^ Moisés saiu do palácio do faraó e suplicou ao SENHOR que removesse todas as moscas.

[[v2-8-31]]

^<<v2-8-31,31>>^ O SENHOR atendeu Moisés e fez os enxames de moscas deixarem o faraó, seus oficiais e seu povo. Não restou uma só mosca.

[[v2-8-32]]

^<<v2-8-32,32>>^ Mas o coração do faraó se endureceu outra vez, e ele se recusou a deixar o povo sair.

'''

xref:002-exodo/002-exodo-007.adoc#v2-7-0[&#60; Capítulo Anterior] | <<v2-8-0,Topo>> | xref:002-exodo/002-exodo-009.adoc#v2-9-0[Próximo Capítulo &#62;]