include::./index.adoc[]

[[v2-23-0]]
=== Êxodo, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v2-23-1]]

^<<v2-23-1,1>>^ "Não espalhe boatos falsos. Não coopere com pessoas perversas sendo falsa testemunha.

[[v2-23-2]]

^<<v2-23-2,2>>^ "Não se deixe levar pela maioria na prática do mal. Quando o chamarem para testemunhar em um processo legal, não permita que a multidão o influencie a perverter a justiça.

[[v2-23-3]]

^<<v2-23-3,3>>^ E não incline seu testemunho em favor de uma pessoa só porque ela é pobre.

[[v2-23-4]]

^<<v2-23-4,4>>^ "Se você deparar com o boi ou o jumento perdido de seu inimigo, leve-o de volta ao dono.

[[v2-23-5]]

^<<v2-23-5,5>>^ Se vir o jumento de alguém que o odeia cair sob o peso de sua carga, não faça de conta que não viu. Pare e ajude o dono a levantá-lo.

[[v2-23-6]]

^<<v2-23-6,6>>^ "Não negue a justiça ao pobre em um processo legal.

[[v2-23-7]]

^<<v2-23-7,7>>^ "Jamais acuse alguém falsamente. Jamais condene à morte uma pessoa inocente ou íntegra, pois eu nunca declaro inocente aquele que é culpado.

[[v2-23-8]]

^<<v2-23-8,8>>^ "Não aceite subornos, pois eles o levam a fazer vista grossa para algo que se pode ver claramente. O suborno faz até o justo distorcer a verdade.

[[v2-23-9]]

^<<v2-23-9,9>>^ "Não explore os estrangeiros. Vocês sabem o que significa viver em terra estranha, pois foram estrangeiros no Egito.

[[v2-23-10]]

^<<v2-23-10,10>>^ "Plantem e colham os produtos da terra por seis anos,

[[v2-23-11]]

^<<v2-23-11,11>>^ mas, no sétimo ano, deixem que ela se renove e descanse sem cultivo. Permitam que os pobres do povo colham o que crescer espontaneamente durante esse ano. Deixem o resto para servir de alimento aos animais selvagens. Façam o mesmo com os vinhedos e os olivais.

[[v2-23-12]]

^<<v2-23-12,12>>^ "Vocês têm seis dias da semana para realizar suas tarefas habituais, mas não devem trabalhar no sétimo. Desse modo, seu boi e seu jumento descansarão, e os escravos e estrangeiros que vivem entre vocês recuperarão as forças.

[[v2-23-13]]

^<<v2-23-13,13>>^ "Prestem muita atenção a todas as minhas instruções. Não invoquem o nome de outros deuses; nem mesmo mencionem o nome deles."

[[v2-23-14]]

^<<v2-23-14,14>>^ "A cada ano, celebrem três festas em minha honra.

[[v2-23-15]]

^<<v2-23-15,15>>^ Primeiro, celebrem a Festa dos Pães sem Fermento. Durante sete dias, o pão que vocês comerem será preparado sem fermento, conforme eu lhes ordenei. Celebrem essa festa anualmente no tempo determinado, no mês de abibe, pois é o aniversário de sua partida do Egito. Ninguém deve se apresentar diante de mim de mãos vazias.

[[v2-23-16]]

^<<v2-23-16,16>>^ "Celebrem também a Festa da Colheita, quando me trarão os primeiros frutos de suas colheitas. "Por fim, celebrem a Festa da Última Colheita no final da safra, quando tiverem colhido todos os produtos de seus campos.

[[v2-23-17]]

^<<v2-23-17,17>>^ A cada ano, nessas três ocasiões, todos os homens de Israel devem comparecer diante do Soberano, o SENHOR.

[[v2-23-18]]

^<<v2-23-18,18>>^ "Não ofereçam o sangue de meus sacrifícios com pão que contenha fermento. E não guardem até a manhã seguinte a gordura das ofertas da festa.

[[v2-23-19]]

^<<v2-23-19,19>>^ "Quando fizerem a colheita, levem à casa do SENHOR, seu Deus, o melhor de seus primeiros frutos. "Não cozinhem o cabrito no leite da mãe dele."

[[v2-23-20]]

^<<v2-23-20,20>>^ "Vejam, eu enviarei um anjo à sua frente para protegê-los ao longo da jornada e conduzi-los em segurança ao lugar que lhes preparei.

[[v2-23-21]]

^<<v2-23-21,21>>^ Prestem muita atenção nele e obedeçam a suas instruções. Não se rebelem contra ele, pois é meu representante e não perdoará sua rebeldia.

[[v2-23-22]]

^<<v2-23-22,22>>^ Mas, se tiverem o cuidado de lhe obedecer e de seguir todas as minhas instruções, serei inimigo de seus inimigos e farei oposição aos que se opuserem a vocês.

[[v2-23-23]]

^<<v2-23-23,23>>^ Meu anjo irá à sua frente e os conduzirá à terra dos amorreus, hititas, ferezeus, cananeus, heveus e jebuseus, e eu destruirei todas essas nações.

[[v2-23-24]]

^<<v2-23-24,24>>^ Não adorem seus deuses, nem os sirvam de maneira alguma, e nem sequer imitem suas práticas. Antes, destruam-nas completamente e despedacem suas colunas sagradas.

[[v2-23-25]]

^<<v2-23-25,25>>^ "Sirvam somente ao SENHOR, seu Deus, e eu os abençoarei com alimento e água e os protegerei de doenças.

[[v2-23-26]]

^<<v2-23-26,26>>^ Em sua terra, nenhuma grávida sofrerá aborto e nenhuma mulher será estéril. Eu lhes darei vida longa e plena.

[[v2-23-27]]

^<<v2-23-27,27>>^ "Enviarei pavor à sua frente e criarei pânico entre os povos cujas terras vocês invadirem. Farei todos os seus inimigos darem meia-volta e fugirem.

[[v2-23-28]]

^<<v2-23-28,28>>^ Sim, enviarei terror adiante de vocês para expulsar os heveus, os cananeus e os hititas,

[[v2-23-29]]

^<<v2-23-29,29>>^ mas não os expulsarei num só ano, pois a terra ficaria deserta e os animais se multiplicariam e se tornariam uma ameaça para vocês.

[[v2-23-30]]

^<<v2-23-30,30>>^ Eu os expulsarei aos poucos, até que sua população tenha aumentado o suficiente para tomar posse da terra.

[[v2-23-31]]

^<<v2-23-31,31>>^ Estabelecerei os limites de seu território desde o mar Vermelho até o mar Mediterrâneo, e do deserto do leste até o rio Eufrates. Entregarei em suas mãos os povos que hoje vivem na terra e os expulsarei de diante de vocês.

[[v2-23-32]]

^<<v2-23-32,32>>^ "Não façam tratados com eles nem com seus deuses.

[[v2-23-33]]

^<<v2-23-33,33>>^ Esses povos não devem habitar em sua terra, pois os fariam pecar contra mim. Se vocês servirem aos deuses deles, cairão na armadilha da idolatria".

'''

xref:002-exodo/002-exodo-022.adoc#v2-22-0[&#60; Capítulo Anterior] | <<v2-23-0,Topo>> | xref:002-exodo/002-exodo-024.adoc#v2-24-0[Próximo Capítulo &#62;]