include::./index.adoc[]

[[v2-39-0]]
=== Êxodo, 39
// nvt ?, NVT - Nova Versão Transformadora

[[v2-39-1]]

^<<v2-39-1,1>>^ Os artesãos confeccionaram belas roupas sagradas de tecido azul, roxo e vermelho para Arão vestir ao servir no lugar santo, conforme o SENHOR havia ordenado a Moisés.

[[v2-39-2]]

^<<v2-39-2,2>>^ Bezalel fez o colete sacerdotal de linho finamente tecido e bordou-o usando fios de ouro e fios de tecido azul, roxo e vermelho.

[[v2-39-3]]

^<<v2-39-3,3>>^ Para fazer os fios de ouro, bateu o metal até formar lâminas finas e as cortou em fios. Com grande habilidade e cuidado, bordou os fios de ouro no linho fino, com fios de tecido azul, roxo e vermelho.

[[v2-39-4]]

^<<v2-39-4,4>>^ O colete sacerdotal tinha duas peças, unidas nos ombros por duas ombreiras.

[[v2-39-5]]

^<<v2-39-5,5>>^ O cinturão decorativo era feito dos mesmos materiais: linho finamente tecido bordado com fios de ouro e fios de tecido azul, roxo e vermelho, conforme o SENHOR havia ordenado a Moisés.

[[v2-39-6]]

^<<v2-39-6,6>>^ Duas pedras de ônix foram presas em suportes de filigranas de ouro. Nas pedras tinham sido gravados os nomes das tribos de Israel, da mesma forma que se grava um selo.

[[v2-39-7]]

^<<v2-39-7,7>>^ Bezalel prendeu as pedras às ombreiras do colete como recordação de que o sacerdote representa os israelitas. Tudo isso foi feito conforme o SENHOR havia ordenado a Moisés.

[[v2-39-8]]

^<<v2-39-8,8>>^ Bezalel fez o peitoral com grande habilidade e cuidado. Confeccionou-o de modo que combinasse com o colete sacerdotal, usando linho finamente tecido, bordado com ouro e com fios de tecido azul, roxo e vermelho.

[[v2-39-9]]

^<<v2-39-9,9>>^ Fez o peitoral de uma só peça dobrada de tecido, formando um bolso quadrado com 22,5 centímetros de lado.

[[v2-39-10]]

^<<v2-39-10,10>>^ Fixou no peitoral quatro fileiras de pedras preciosas. A primeira fileira tinha um rubi, um topázio e um berilo.

[[v2-39-11]]

^<<v2-39-11,11>>^ A segunda fileira era composta de uma turquesa, uma safira e uma esmeralda.

[[v2-39-12]]

^<<v2-39-12,12>>^ A terceira fileira era composta de um jacinto, uma ágata e uma ametista.

[[v2-39-13]]

^<<v2-39-13,13>>^ A quarta fileira tinha um crisólito, um ônix e um jaspe. Todas essas pedras eram presas a suportes de filigranas de ouro.

[[v2-39-14]]

^<<v2-39-14,14>>^ Cada pedra representava um dos doze filhos de Israel e trazia gravado o nome da tribo correspondente, como em um selo.

[[v2-39-15]]

^<<v2-39-15,15>>^ Para prender o peitoral ao colete sacerdotal, fizeram correntes de fios trançados de ouro puro.

[[v2-39-16]]

^<<v2-39-16,16>>^ Fizeram também dois suportes de filigranas de ouro e duas argolas de ouro, que foram presas aos cantos superiores do peitoral.

[[v2-39-17]]

^<<v2-39-17,17>>^ Amarraram as duas correntes de ouro nas duas argolas do peitoral.

[[v2-39-18]]

^<<v2-39-18,18>>^ Amarraram as outras pontas das correntes aos suportes de filigrana de ouro sobre as ombreiras do colete.

[[v2-39-19]]

^<<v2-39-19,19>>^ Em seguida, fizeram mais duas argolas de ouro e as prenderam às bordas interiores do peitoral, junto ao colete.

[[v2-39-20]]

^<<v2-39-20,20>>^ Fizeram outras duas argolas de ouro e as prenderam à parte da frente do colete, abaixo das ombreiras e logo acima do nó que amarrava o cinturão decorativo ao colete.

[[v2-39-21]]

^<<v2-39-21,21>>^ Prenderam as argolas inferiores do peitoral às argolas do colete com cordões azuis, para que o peitoral ficasse firmemente preso ao colete acima do cinturão. Tudo isso foi feito conforme o SENHOR havia ordenado a Moisés.

[[v2-39-22]]

^<<v2-39-22,22>>^ Bezalel fez de uma só peça de tecido azul o manto que é usado com o colete sacerdotal,

[[v2-39-23]]

^<<v2-39-23,23>>^ com uma abertura no meio da peça para a cabeça de Arão. A abertura foi reforçada com uma gola, para que não se rasgasse.

[[v2-39-24]]

^<<v2-39-24,24>>^ Fizeram romãs de fios de tecido azul, roxo e vermelho e as prenderam à borda do manto.

[[v2-39-25]]

^<<v2-39-25,25>>^ Fizeram também sinos de ouro puro e os prenderam entre as romãs à borda do manto,

[[v2-39-26]]

^<<v2-39-26,26>>^ intercalando sinos e romãs por toda a volta da borda. Esse manto deveria ser usado sempre que o sacerdote realizasse seu serviço, conforme o SENHOR havia ordenado a Moisés.

[[v2-39-27]]

^<<v2-39-27,27>>^ Confeccionaram para Arão e seus filhos túnicas de linho fino.

[[v2-39-28]]

^<<v2-39-28,28>>^ O turbante especial e os outros turbantes também foram confeccionados de linho fino, e as roupas de baixo foram feitas de linho finamente tecido.

[[v2-39-29]]

^<<v2-39-29,29>>^ Os cinturões foram feitos de linho finamente tecido e bordados com fios de tecido azul, roxo e vermelho, conforme o SENHOR havia ordenado a Moisés.

[[v2-39-30]]

^<<v2-39-30,30>>^ Fizeram de ouro puro a tiara sagrada, o emblema de santidade. Gravaram nela, como em um selo, as palavras Santo para o SENHOR.

[[v2-39-31]]

^<<v2-39-31,31>>^ Prenderam a tiara com um cordão azul à parte da frente do turbante de Arão, conforme o SENHOR havia ordenado a Moisés.

[[v2-39-32]]

^<<v2-39-32,32>>^ Assim, a construção do tabernáculo, a tenda do encontro, foi concluída. Os israelitas fizeram tudo conforme o SENHOR havia ordenado a Moisés.

[[v2-39-33]]

^<<v2-39-33,33>>^ Então apresentaram a Moisés o tabernáculo completo: a tenda com toda a sua mobília, os colchetes, as armações, os travessões, as colunas e as bases;

[[v2-39-34]]

^<<v2-39-34,34>>^ as coberturas da tenda, feitas de peles de carneiro tingidas de vermelho e couro fino; a cortina interna que protegia a arca;

[[v2-39-35]]

^<<v2-39-35,35>>^ a arca da aliança e as varas para transportá-la; a tampa da arca, que é o lugar de expiação;

[[v2-39-36]]

^<<v2-39-36,36>>^ a mesa e todos os seus utensílios; os pães da presença;

[[v2-39-37]]

^<<v2-39-37,37>>^ o candelabro de ouro puro, com suas lâmpadas simétricas, todos os seus acessórios e o óleo de oliva para a iluminação;

[[v2-39-38]]

^<<v2-39-38,38>>^ o altar de ouro; o óleo da unção e o incenso perfumado; a cortina para a entrada da tenda;

[[v2-39-39]]

^<<v2-39-39,39>>^ o altar de bronze com a grelha de bronze, as varas para transportá-lo e seus utensílios; a bacia de bronze e seu suporte;

[[v2-39-40]]

^<<v2-39-40,40>>^ a cortina para as divisórias do pátio; as colunas e suas bases; a cortina para a entrada do pátio; as cordas e as estacas; todos os utensílios a serem usados durante as cerimônias no tabernáculo, a tenda do encontro;

[[v2-39-41]]

^<<v2-39-41,41>>^ as roupas finamente confeccionadas para os sacerdotes vestirem enquanto estiverem servindo no lugar santo, as roupas sacerdotais sagradas de Arão e as roupas que seus filhos vestiriam durante o serviço.

[[v2-39-42]]

^<<v2-39-42,42>>^ Os israelitas seguiram todas as instruções que o SENHOR tinha dado a Moisés acerca da obra.

[[v2-39-43]]

^<<v2-39-43,43>>^ Então Moisés inspecionou todo o trabalho. Quando verificou que tinha sido feito conforme o SENHOR havia ordenado, abençoou o povo.

'''

xref:002-exodo/002-exodo-038.adoc#v2-38-0[&#60; Capítulo Anterior] | <<v2-39-0,Topo>> | xref:002-exodo/002-exodo-040.adoc#v2-40-0[Próximo Capítulo &#62;]