include::./index.adoc[]

[[v2-28-0]]
=== Êxodo, 28
// nvt ?, NVT - Nova Versão Transformadora

[[v2-28-1]]

^<<v2-28-1,1>>^ "Mande chamar seu irmão Arão e os filhos dele, Nadabe, Abiú, Eleazar e Itamar. Separe-os dos demais israelitas para que me sirvam e sejam meus sacerdotes.

[[v2-28-2]]

^<<v2-28-2,2>>^ Faça para Arão roupas sagradas, trajes de grande beleza e esplendor.

[[v2-28-3]]

^<<v2-28-3,3>>^ Instrua todos os artesãos habilidosos que eu enchi de espírito de sabedoria a fim de que confeccionem para Arão roupas que o consagrarão como sacerdote para o meu serviço.

[[v2-28-4]]

^<<v2-28-4,4>>^ Estas são as roupas que devem confeccionar: um peitoral, um colete, um manto, uma túnica bordada, um turbante e um cinturão. Devem fazer essas roupas sagradas para seu irmão Arão e para os filhos deles vestirem quando me servirem como sacerdotes.

[[v2-28-5]]

^<<v2-28-5,5>>^ Dê a eles, portanto, linho finamente tecido com fios de ouro e de tecido azul, roxo e vermelho."

[[v2-28-6]]

^<<v2-28-6,6>>^ "Os artesãos devem fazer o colete sacerdotal de linho finamente tecido e artisticamente bordado, usando fios de ouro e fios de tecido azul, roxo e vermelho.

[[v2-28-7]]

^<<v2-28-7,7>>^ O colete terá duas peças, unidas nos ombros por duas ombreiras.

[[v2-28-8]]

^<<v2-28-8,8>>^ O cinturão decorativo será feito dos mesmos materiais: linho finamente tecido bordado com fios de ouro e fios de tecido azul, roxo e vermelho.

[[v2-28-9]]

^<<v2-28-9,9>>^ "Grave em duas pedras de ônix os nomes das tribos de Israel,

[[v2-28-10]]

^<<v2-28-10,10>>^ seis nomes em cada pedra, organizados de acordo com a ordem de nascimento dos filhos de Israel.

[[v2-28-11]]

^<<v2-28-11,11>>^ Grave esses nomes nas duas pedras da mesma forma que o ourives grava um selo. Em seguida, encrave-as em suportes de filigranas de ouro.

[[v2-28-12]]

^<<v2-28-12,12>>^ Prenda-as às ombreiras do colete sacerdotal como recordação de que Arão representa os israelitas. Arão levará esses nomes sobre seus ombros como lembrança contínua sempre que se apresentar diante do SENHOR.

[[v2-28-13]]

^<<v2-28-13,13>>^ Faça suportes para as pedras com filigranas de ouro,

[[v2-28-14]]

^<<v2-28-14,14>>^ trance duas correntes de ouro puro e prenda-as aos suportes de filigrana sobre as ombreiras do colete."

[[v2-28-15]]

^<<v2-28-15,15>>^ "Em seguida, faça com grande habilidade o peitoral para decisões. Confeccione-o de modo que combine com o colete sacerdotal, usando linho finamente tecido com fios de ouro e fios de tecido azul, roxo e vermelho.

[[v2-28-16]]

^<<v2-28-16,16>>^ Faça o peitoral de uma só peça dobrada de tecido, formando um bolso quadrado com 22,5 centímetros de lado.

[[v2-28-17]]

^<<v2-28-17,17>>^ Fixe no peitoral quatro fileiras de pedras preciosas. A primeira fileira terá um rubi, um topázio e um berilo.

[[v2-28-18]]

^<<v2-28-18,18>>^ A segunda fileira será composta de uma turquesa, uma safira e uma esmeralda.

[[v2-28-19]]

^<<v2-28-19,19>>^ A terceira fileira será composta de um jacinto, uma ágata e uma ametista.

[[v2-28-20]]

^<<v2-28-20,20>>^ A quarta fileira terá um crisólito, um ônix e um jaspe. Todas essas pedras serão presas a suportes de filigranas de ouro.

[[v2-28-21]]

^<<v2-28-21,21>>^ Cada pedra representará um dos doze filhos de Israel, e o nome da tribo correspondente será gravado na pedra como um selo.

[[v2-28-22]]

^<<v2-28-22,22>>^ "Para prender o peitoral ao colete sacerdotal, faça correntes de fios trançados de ouro puro.

[[v2-28-23]]

^<<v2-28-23,23>>^ Faça também duas argolas de ouro e prenda-as aos cantos superiores do peitoral.

[[v2-28-24]]

^<<v2-28-24,24>>^ Amarre as duas correntes de ouro nas duas argolas dos cantos superiores do peitoral.

[[v2-28-25]]

^<<v2-28-25,25>>^ Amarre as outras pontas das correntes às filigranas de ouro sobre as ombreiras do colete.

[[v2-28-26]]

^<<v2-28-26,26>>^ Em seguida, faça mais duas argolas de ouro e prenda-as às bordas interiores do peitoral, junto ao colete.

[[v2-28-27]]

^<<v2-28-27,27>>^ Faça outras duas argolas de ouro e prenda-as à parte da frente do colete, abaixo das ombreiras e logo acima do nó com o qual o cinturão decorativo é amarrado ao colete.

[[v2-28-28]]

^<<v2-28-28,28>>^ Depois, prenda as argolas inferiores do peitoral às argolas do colete com cordões azuis, para que o peitoral fique firmemente preso ao colete acima do cinturão decorativo.

[[v2-28-29]]

^<<v2-28-29,29>>^ "Com isso, Arão levará os nomes das tribos de Israel sobre seu coração no peitoral para decisões quando entrar no lugar santo. Essa será uma lembrança contínua de que ele representa o povo diante do SENHOR.

[[v2-28-30]]

^<<v2-28-30,30>>^ Dentro do peitoral para decisões, coloque o Urim e o Tumim para que Arão os leve sobre o coração quando se apresentar diante do SENHOR. Assim, sempre que se apresentar diante do SENHOR, Arão levará sobre o coração os objetos usados para determinar as decisões a respeito do povo de Israel."

[[v2-28-31]]

^<<v2-28-31,31>>^ "De uma só peça de tecido azul, confeccione o manto que é usado com o colete sacerdotal.

[[v2-28-32]]

^<<v2-28-32,32>>^ Faça uma abertura para a cabeça de Arão no meio da peça e reforce a abertura com uma gola, para que não se rasgue.

[[v2-28-33]]

^<<v2-28-33,33>>^ Faça romãs de fios de tecido azul, roxo e vermelho e prenda-as à borda do manto, com sinos de ouro entre elas.

[[v2-28-34]]

^<<v2-28-34,34>>^ Os sinos de ouro e as romãs serão intercalados por toda a volta da borda.

[[v2-28-35]]

^<<v2-28-35,35>>^ Arão vestirá esse manto sempre que servir diante do SENHOR, e os sinos tocarão quando ele entrar na presença do SENHOR no lugar santo e também quando sair. Se ele usar o manto, não morrerá.

[[v2-28-36]]

^<<v2-28-36,36>>^ "Em seguida, faça uma tiara de ouro puro e grave nela, como em um selo, as palavras Santo para o SENHOR.

[[v2-28-37]]

^<<v2-28-37,37>>^ Prenda a tiara com um cordão azul à parte da frente do turbante de Arão.

[[v2-28-38]]

^<<v2-28-38,38>>^ Arão a usará na testa, para que tome sobre si toda a culpa dos israelitas quando consagrarem suas ofertas sagradas. Terá de usá-la sempre na testa para que o SENHOR aceite seu povo.

[[v2-28-39]]

^<<v2-28-39,39>>^ "Teça a túnica bordada de Arão com linho fino. Com o mesmo linho, faça o turbante. Confeccione também um cinturão e enfeite-o com bordados coloridos.

[[v2-28-40]]

^<<v2-28-40,40>>^ "Para os filhos de Arão, confeccione túnicas, cinturões e turbantes especiais, trajes de grande beleza e esplendor.

[[v2-28-41]]

^<<v2-28-41,41>>^ Vista seu irmão Arão e os filhos dele com essas roupas e, em seguida, unja-os e consagre-os. Santifique-os para que sirvam como meus sacerdotes.

[[v2-28-42]]

^<<v2-28-42,42>>^ Faça também roupas de baixo de linho para serem usadas diretamente sobre a pele, indo da cintura até as coxas.

[[v2-28-43]]

^<<v2-28-43,43>>^ Arão e seus filhos deverão usar esses calções sempre que entrarem na tenda do encontro ou se aproximarem do altar para servir no lugar santo. Desse modo, não levarão culpa alguma sobre si e não morrerão. Essa é uma lei permanente para Arão e todos os seus descendentes."

'''

xref:002-exodo/002-exodo-027.adoc#v2-27-0[&#60; Capítulo Anterior] | <<v2-28-0,Topo>> | xref:002-exodo/002-exodo-029.adoc#v2-29-0[Próximo Capítulo &#62;]