include::./index.adoc[]

[[v2-32-0]]
=== Êxodo, 32
// nvt ?, NVT - Nova Versão Transformadora

[[v2-32-1]]

^<<v2-32-1,1>>^ Quando o povo viu que Moisés demorava a descer do monte, reuniu-se ao redor de Arão e disse: "Tome uma providência! Faça para nós deuses que nos guiem. Não sabemos o que aconteceu com esse Moisés, que nos trouxe da terra do Egito para cá".

[[v2-32-2]]

^<<v2-32-2,2>>^ Arão respondeu: "Tirem as argolas de ouro das orelhas de suas mulheres e de seus filhos e filhas e tragam-nas para mim".

[[v2-32-3]]

^<<v2-32-3,3>>^ Todos tiraram as argolas de ouro e as levaram a Arão.

[[v2-32-4]]

^<<v2-32-4,4>>^ Ele recebeu o ouro, derreteu-o e trabalhou nele, dando-lhe a forma de um bezerro. Quando o povo viu o bezerro, começou a exclamar: "Ó Israel, estes são os seus deuses que o tiraram da terra do Egito!".

[[v2-32-5]]

^<<v2-32-5,5>>^ Percebendo o entusiasmo do povo, Arão construiu um altar diante do bezerro e anunciou: "Amanhã haverá uma festa para o SENHOR!".

[[v2-32-6]]

^<<v2-32-6,6>>^ Na manhã seguinte, o povo se levantou cedo para apresentar holocaustos e ofertas de paz. Depois, todos comeram e beberam e se entregaram à farra.

[[v2-32-7]]

^<<v2-32-7,7>>^ O SENHOR disse a Moisés: "Rápido! Desça do monte! Seu povo, que você tirou da terra do Egito, se corrompeu.

[[v2-32-8]]

^<<v2-32-8,8>>^ Como se desviaram depressa do caminho que eu lhes havia ordenado! Derreteram ouro e fizeram um bezerro, curvaram-se diante dele e lhe ofereceram sacrifícios. Dizem: ‘Ó Israel, estes são os seus deuses que o tiraram da terra do Egito!’".

[[v2-32-9]]

^<<v2-32-9,9>>^ Então o SENHOR declarou: "Vi como este povo é teimoso e rebelde.

[[v2-32-10]]

^<<v2-32-10,10>>^ Agora fique de lado, e eu lançarei contra eles minha ira ardente e os destruirei. Depois, farei de você, Moisés, uma grande nação".

[[v2-32-11]]

^<<v2-32-11,11>>^ Moisés, porém, tentou apaziguar o SENHOR, seu Deus. "Ó SENHOR!", exclamou ele. "Por que estás tão irado com teu próprio povo, que tiraste do Egito com tão grande poder e mão forte?

[[v2-32-12]]

^<<v2-32-12,12>>^ Por que deixar os egípcios dizerem: ‘O Deus deles os resgatou com a má intenção de exterminá-los nos montes e apagá-los da face da terra’? Deixa de lado tua ira ardente! Arrepende-te quanto a esta calamidade terrível que ameaçaste enviar sobre teu povo!

[[v2-32-13]]

^<<v2-32-13,13>>^ Lembra-te dos teus servos Abraão, Isaque e Jacó. Assumiste um compromisso com eles por meio de juramento, dizendo: ‘Tornarei seus descendentes tão numerosos quanto as estrelas do céu. Eu lhes darei toda esta terra que lhes prometi, e eles a possuirão para sempre’."

[[v2-32-14]]

^<<v2-32-14,14>>^ Então o SENHOR se arrependeu da calamidade terrível que havia ameaçado enviar sobre seu povo.

[[v2-32-15]]

^<<v2-32-15,15>>^ Em seguida, Moisés se virou e desceu o monte. Trazia nas mãos as duas tábuas da aliança, que estavam escritas dos dois lados, frente e verso.

[[v2-32-16]]

^<<v2-32-16,16>>^ As tábuas eram obra de Deus; cada palavra tinha sido gravada pelo próprio Deus.

[[v2-32-17]]

^<<v2-32-17,17>>^ Quando Josué ouviu o alvoroço do povo que gritava lá embaixo, disse a Moisés: "Parece que há guerra no acampamento!".

[[v2-32-18]]

^<<v2-32-18,18>>^ Moisés respondeu: "Não são gritos de vitória nem lamentos de derrota. Ouço barulho de festa".

[[v2-32-19]]

^<<v2-32-19,19>>^ Quando se aproximaram do acampamento, Moisés viu o bezerro e as danças e ficou furioso. Jogou as tábuas de pedra no chão e as despedaçou ao pé do monte.

[[v2-32-20]]

^<<v2-32-20,20>>^ Tomou o bezerro que haviam feito e o queimou. Moeu-o até virar pó, jogou-o na água e obrigou os israelitas a bebê-la.

[[v2-32-21]]

^<<v2-32-21,21>>^ Por fim, dirigiu-se a Arão e perguntou: "O que este povo lhe fez para que você os levasse a cometer tamanho pecado?".

[[v2-32-22]]

^<<v2-32-22,22>>^ "Não fique tão furioso comigo, meu senhor", respondeu Arão. "Você sabe como este povo é mau.

[[v2-32-23]]

^<<v2-32-23,23>>^ Eles me disseram: ‘Faça para nós deuses que nos guiem. Não sabemos o que aconteceu com esse Moisés, que nos trouxe da terra do Egito para cá’.

[[v2-32-24]]

^<<v2-32-24,24>>^ Então eu lhes disse: ‘Quem tiver joias de ouro, tire-as’. Quando eles as trouxeram para mim, simplesmente as joguei no fogo e saiu este bezerro!"

[[v2-32-25]]

^<<v2-32-25,25>>^ Moisés viu que Arão havia permitido que o povo se descontrolasse completamente, dando motivo de zombaria a seus inimigos.

[[v2-32-26]]

^<<v2-32-26,26>>^ Portanto, colocou-se à entrada do acampamento e gritou: "Todos que estiverem do lado do SENHOR, venham até aqui e juntem-se a mim!". E todos os levitas se reuniram ao redor dele.

[[v2-32-27]]

^<<v2-32-27,27>>^ Moisés lhes disse: "Assim diz o SENHOR, o Deus de Israel: ‘Cada um de vocês pegue sua espada e vão e voltem de uma extremidade à outra do acampamento. Matem todos, até mesmo seus irmãos, amigos e vizinhos’".

[[v2-32-28]]

^<<v2-32-28,28>>^ Os levitas obedeceram à ordem de Moisés, e cerca de três mil pessoas morreram naquele dia.

[[v2-32-29]]

^<<v2-32-29,29>>^ Então Moisés disse aos levitas: "Hoje vocês se consagraram para o serviço do SENHOR, pois lhe obedeceram mesmo quando tiveram de matar seus próprios filhos e irmãos. Hoje vocês receberam dele uma bênção".

[[v2-32-30]]

^<<v2-32-30,30>>^ No dia seguinte, Moisés disse ao povo: "Vocês cometeram um pecado terrível, mas eu subirei ao monte e me encontrarei com o SENHOR outra vez. Talvez eu consiga fazer expiação por este pecado!".

[[v2-32-31]]

^<<v2-32-31,31>>^ Moisés voltou ao SENHOR e disse: "Que pecado terrível este povo cometeu! Fizeram para si deuses de ouro.

[[v2-32-32]]

^<<v2-32-32,32>>^ Agora, porém, eu te suplico que lhes perdoes o pecado; do contrário, apaga meu nome do registro que escreveste!".

[[v2-32-33]]

^<<v2-32-33,33>>^ O SENHOR, porém, respondeu a Moisés: "Apagarei o nome de todos que pecaram contra mim.

[[v2-32-34]]

^<<v2-32-34,34>>^ Agora vá e leve o povo ao lugar do qual eu lhe falei. Veja, meu anjo irá à sua frente. E, no dia do acerto de contas, certamente eu castigarei este povo pelo pecado que cometeram".

[[v2-32-35]]

^<<v2-32-35,35>>^ Então o SENHOR castigou severamente o povo, por causa do que fizeram com o bezerro que Arão lhes tinha construído.

'''

xref:002-exodo/002-exodo-031.adoc#v2-31-0[&#60; Capítulo Anterior] | <<v2-32-0,Topo>> | xref:002-exodo/002-exodo-033.adoc#v2-33-0[Próximo Capítulo &#62;]