include::./index.adoc[]

[[v2-34-0]]
=== Êxodo, 34
// nvt ?, NVT - Nova Versão Transformadora

[[v2-34-1]]

^<<v2-34-1,1>>^ O SENHOR disse a Moisés: "Corte duas tábuas de pedra como as primeiras. Nelas escreverei as mesmas palavras que estavam nas tábuas que você despedaçou.

[[v2-34-2]]

^<<v2-34-2,2>>^ Esteja pronto amanhã cedo para subir ao Sinai e apresentar-se diante de mim no topo do monte.

[[v2-34-3]]

^<<v2-34-3,3>>^ Ninguém deve acompanhá-lo. Aliás, ninguém deve aparecer em parte alguma do monte. Não permita sequer que os rebanhos pastem próximo ao monte".

[[v2-34-4]]

^<<v2-34-4,4>>^ Moisés cortou as duas tábuas de pedra como as primeiras. Logo de manhã, subiu ao monte Sinai conforme o SENHOR havia ordenado, levando nas mãos as duas tábuas de pedra.

[[v2-34-5]]

^<<v2-34-5,5>>^ Então o SENHOR desceu em uma nuvem, ficou ali com Moisés e anunciou seu nome, Javé.

[[v2-34-6]]

^<<v2-34-6,6>>^ O SENHOR passou diante de Moisés, proclamando: "Javé! O SENHOR! O Deus de compaixão e misericórdia! Sou lento para me irar e cheio de amor e fidelidade.

[[v2-34-7]]

^<<v2-34-7,7>>^ Cubro de amor mil gerações e perdoo o mal, a rebeldia e o pecado. Contudo, não absolvo o culpado; trago as consequências do pecado dos pais sobre os filhos até a terceira e quarta geração".

[[v2-34-8]]

^<<v2-34-8,8>>^ No mesmo instante, Moisés se prostrou com o rosto no chão e adorou.

[[v2-34-9]]

^<<v2-34-9,9>>^ Em seguida, disse: "Senhor, se é verdade que te agradas de mim, peço que nos acompanhes na jornada. É verdade que o povo é teimoso e rebelde, mas eu te peço que perdoes nossa maldade e nosso pecado. Toma-nos como tua propriedade especial".

[[v2-34-10]]

^<<v2-34-10,10>>^ O SENHOR respondeu: "Faço hoje uma aliança com você na presença de todo o seu povo. Realizarei maravilhas jamais vistas em nação alguma ou lugar algum da terra. E todos ao seu redor verão o poder do SENHOR, o poder temível que demonstrarei em seu favor.

[[v2-34-11]]

^<<v2-34-11,11>>^ Observe com atenção, porém, tudo que eu lhe ordeno hoje. Irei à sua frente e expulsarei os amorreus, os cananeus, os hititas, os ferezeus, os heveus e os jebuseus.

[[v2-34-12]]

^<<v2-34-12,12>>^ "Tenha muito cuidado para não assinar tratados com os povos que vivem na terra para a qual você está indo. Se o fizer, seguirá pelos maus caminhos deles e cairá numa armadilha.

[[v2-34-13]]

^<<v2-34-13,13>>^ Em vez disso, destrua os altares idólatras, despedace as colunas sagradas e derrube os postes dedicados à deusa Aserá.

[[v2-34-14]]

^<<v2-34-14,14>>^ Não adore outros deuses, pois o SENHOR, cujo nome é Zeloso, é Deus zeloso de seu relacionamento com vocês.

[[v2-34-15]]

^<<v2-34-15,15>>^ "Não faça tratado algum com os povos que vivem na terra. No culto a seus deuses, eles se prostituem e oferecem sacrifícios. Eles o convidarão para comer dessas ofertas, e você aceitará o convite.

[[v2-34-16]]

^<<v2-34-16,16>>^ Depois, aceitará que as filhas deles, as quais sacrificam a outros deuses, se casem com seus filhos. Elas seduzirão seus filhos para que se prostituam adorando outros deuses.

[[v2-34-17]]

^<<v2-34-17,17>>^ Não faça para si deuses de metal fundido.

[[v2-34-18]]

^<<v2-34-18,18>>^ "Celebre a Festa dos Pães sem Fermento. Durante sete dias, coma seu pão sem fermento, conforme eu lhe ordenei. Celebre essa festa anualmente no tempo determinado, no mês de abibe, pois é o aniversário de sua partida do Egito.

[[v2-34-19]]

^<<v2-34-19,19>>^ "As primeiras crias de todos os animais me pertencem, incluindo os machos das primeiras crias de seus rebanhos de bois e ovelhas.

[[v2-34-20]]

^<<v2-34-20,20>>^ Para resgatar a primeira cria de uma jumenta, entregue ao SENHOR, como substituto, um cordeiro ou um cabrito. Caso você não resgate o animal, terá de quebrar o pescoço dele. Quanto aos primeiros filhos homens, será obrigatório resgatá-los. "Ninguém deve se apresentar diante de mim de mãos vazias.

[[v2-34-21]]

^<<v2-34-21,21>>^ "Você tem seis dias na semana para fazer os trabalhos habituais, mas no sétimo dia não deve trabalhar, mesmo nas épocas de arar e colher.

[[v2-34-22]]

^<<v2-34-22,22>>^ "Celebre a Festa da Colheita com os primeiros frutos da colheita do trigo. Celebre também a Festa da Última Colheita no final da safra.

[[v2-34-23]]

^<<v2-34-23,23>>^ Três vezes por ano, todos os homens de Israel comparecerão diante do Soberano, o SENHOR, o Deus de Israel.

[[v2-34-24]]

^<<v2-34-24,24>>^ Expulsarei as outras nações de diante de você e aumentarei seu território, para que ninguém cobice sua terra enquanto você comparece diante do SENHOR, seu Deus, três vezes por ano.

[[v2-34-25]]

^<<v2-34-25,25>>^ "Não ofereça o sangue de meus sacrifícios com pão que contenha fermento. Não guarde até a manhã seguinte carne alguma do sacrifício de Páscoa.

[[v2-34-26]]

^<<v2-34-26,26>>^ "Quando fizer a colheita, leve à casa do SENHOR, seu Deus, o melhor de seus primeiros frutos. "Não cozinhe o cabrito no leite da mãe dele".

[[v2-34-27]]

^<<v2-34-27,27>>^ O SENHOR também disse a Moisés: "Escreva todas essas palavras, pois elas representam os termos da aliança que eu faço com você e com Israel".

[[v2-34-28]]

^<<v2-34-28,28>>^ Moisés permaneceu no monte com o SENHOR quarenta dias e quarenta noites. Durante todo esse tempo, não comeu pão nem bebeu água. E escreveu os termos da aliança, os dez mandamentos, nas tábuas de pedra.

[[v2-34-29]]

^<<v2-34-29,29>>^ Quando Moisés desceu do monte Sinai carregando as duas tábuas da aliança, não percebeu que seu rosto brilhava, pois ele havia falado com o SENHOR.

[[v2-34-30]]

^<<v2-34-30,30>>^ Quando Arão e os israelitas viram o brilho do rosto de Moisés, tiveram medo de se aproximar dele.

[[v2-34-31]]

^<<v2-34-31,31>>^ Moisés, porém, chamou Arão e os líderes da comunidade, que se aproximaram, e Moisés falou com eles.

[[v2-34-32]]

^<<v2-34-32,32>>^ Em seguida, todo o povo se aproximou, e Moisés lhes transmitiu todas as instruções que o SENHOR lhe tinha dado no monte Sinai.

[[v2-34-33]]

^<<v2-34-33,33>>^ Quando Moisés terminou de falar com eles, cobriu o rosto com um véu.

[[v2-34-34]]

^<<v2-34-34,34>>^ No entanto, sempre que entrava na tenda da reunião para falar com o SENHOR, tirava o véu até sair. Depois, transmitia ao povo as instruções que o SENHOR lhe dava,

[[v2-34-35]]

^<<v2-34-35,35>>^ e os israelitas viam o brilho de seu rosto. Então Moisés cobria novamente o rosto com o véu até voltar para falar com o SENHOR.

'''

xref:002-exodo/002-exodo-033.adoc#v2-33-0[&#60; Capítulo Anterior] | <<v2-34-0,Topo>> | xref:002-exodo/002-exodo-035.adoc#v2-35-0[Próximo Capítulo &#62;]