include::./index.adoc[]

[[v2-33-0]]
=== Êxodo, 33
// nvt ?, NVT - Nova Versão Transformadora

[[v2-33-1]]

^<<v2-33-1,1>>^ O SENHOR disse a Moisés: "Ponha-se a caminho, junto com o povo que você tirou da terra do Egito. Subam à terra que eu jurei dar a Abraão, Isaque e Jacó, dizendo: ‘Darei esta terra a seus descendentes’.

[[v2-33-2]]

^<<v2-33-2,2>>^ Enviarei um anjo à sua frente para expulsar os cananeus, os amorreus, os hititas, os ferezeus, os heveus e os jebuseus.

[[v2-33-3]]

^<<v2-33-3,3>>^ Subam à terra que produz leite e mel com fartura. Mas eu não viajarei no meio de vocês, pois são um povo teimoso e rebelde. Se eu os acompanhasse, certamente os destruiria ao longo do caminho".

[[v2-33-4]]

^<<v2-33-4,4>>^ Quando o povo ouviu essas palavras severas, chorou e deixou de usar seus ornamentos.

[[v2-33-5]]

^<<v2-33-5,5>>^ Pois o SENHOR havia ordenado a Moisés: "Diga ao povo de Israel: ‘Vocês são um povo teimoso e rebelde. Se eu os acompanhasse, mesmo que só por um momento, eu os destruiria. Deixem de usar seus ornamentos enquanto decido o que fazer com vocês’".

[[v2-33-6]]

^<<v2-33-6,6>>^ Assim, desde quando partiram do monte Sinai, os israelitas deixaram de usar ornamentos.

[[v2-33-7]]

^<<v2-33-7,7>>^ Moisés costumava montar uma tenda fora do acampamento, a certa distância dele, e a chamava de tenda da reunião. Quem quisesse fazer uma petição ao SENHOR ia até essa tenda, fora do acampamento.

[[v2-33-8]]

^<<v2-33-8,8>>^ Sempre que Moisés se dirigia a essa tenda, todo o povo se levantava e permanecia em pé, cada um junto à entrada de sua própria tenda. Observavam Moisés até ele entrar na tenda.

[[v2-33-9]]

^<<v2-33-9,9>>^ Logo que Moisés entrava, uma coluna de nuvem descia e ficava suspensa no ar, à entrada da tenda, enquanto o SENHOR falava com ele.

[[v2-33-10]]

^<<v2-33-10,10>>^ Quando o povo via a nuvem à entrada da tenda, cada um permanecia em frente à própria tenda e se curvava.

[[v2-33-11]]

^<<v2-33-11,11>>^ Ali o SENHOR falava com Moisés face a face, como quem fala com um amigo. Depois Moisés voltava ao acampamento, mas seu jovem auxiliar Josué, filho de Num, ficava na tenda.

[[v2-33-12]]

^<<v2-33-12,12>>^ Então Moisés disse ao SENHOR: "Tu me ordenaste: ‘Leve este povo’, mas não disseste quem enviarias comigo. Declaraste: ‘Eu o conheço pelo nome e me agrado de você’.

[[v2-33-13]]

^<<v2-33-13,13>>^ Se é verdade que te agradas de mim, permita-me conhecer teus caminhos para que eu te conheça melhor e continue a contar com teu favor. E lembra-te de que esta nação é teu povo".

[[v2-33-14]]

^<<v2-33-14,14>>^ O SENHOR respondeu: "Acompanharei você pessoalmente e lhe darei descanso".

[[v2-33-15]]

^<<v2-33-15,15>>^ Então Moisés disse: "Se não nos acompanhares pessoalmente, não nos faças sair deste lugar.

[[v2-33-16]]

^<<v2-33-16,16>>^ Se não nos acompanhares, como os outros saberão que meu povo e eu contamos com teu favor? Pois é tua presença em nosso meio que nos distingue, teu povo e eu, de todos os outros povos da terra".

[[v2-33-17]]

^<<v2-33-17,17>>^ O SENHOR respondeu a Moisés: "Certamente farei o que me pede, pois me agrado de você e o conheço pelo nome".

[[v2-33-18]]

^<<v2-33-18,18>>^ Moisés disse: "Então peço que me mostres tua presença gloriosa".

[[v2-33-19]]

^<<v2-33-19,19>>^ O SENHOR respondeu: "Farei passar diante de você toda a minha bondade e anunciarei diante de você o meu nome, Javé. Pois terei misericórdia de quem eu quiser, e mostrarei compaixão a quem eu quiser.

[[v2-33-20]]

^<<v2-33-20,20>>^ Mas você não poderá olhar diretamente para minha face, pois ninguém pode me ver e continuar vivo".

[[v2-33-21]]

^<<v2-33-21,21>>^ O SENHOR disse ainda: "Fique nesta rocha, perto de mim.

[[v2-33-22]]

^<<v2-33-22,22>>^ Quando minha presença gloriosa passar, eu o colocarei numa abertura da rocha e o cobrirei com minha mão até que eu tenha passado.

[[v2-33-23]]

^<<v2-33-23,23>>^ Depois, tirarei minha mão e você me verá pelas costas. Meu rosto, porém, ninguém poderá ver".

'''

xref:002-exodo/002-exodo-032.adoc#v2-32-0[&#60; Capítulo Anterior] | <<v2-33-0,Topo>> | xref:002-exodo/002-exodo-034.adoc#v2-34-0[Próximo Capítulo &#62;]