include::./index.adoc[]

[[v2-24-0]]
=== Êxodo, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v2-24-1]]

^<<v2-24-1,1>>^ Então o SENHOR disse a Moisés: "Suba ao monte para encontrar-se comigo e traga Arão, Nadabe, Abiú e setenta líderes de Israel. Todos devem adorar de longe.

[[v2-24-2]]

^<<v2-24-2,2>>^ Somente Moisés está autorizado a se aproximar do SENHOR. Os outros não devem chegar perto, e ninguém mais do povo tem permissão de subir ao monte com ele".

[[v2-24-3]]

^<<v2-24-3,3>>^ Moisés desceu e transmitiu ao povo todas as instruções e ordens do SENHOR, e todo o povo respondeu em uma só voz: "Faremos tudo que o SENHOR ordenou!".

[[v2-24-4]]

^<<v2-24-4,4>>^ Moisés anotou com exatidão todas as instruções do SENHOR. Logo cedo na manhã seguinte, levantou-se e construiu um altar ao pé do monte. Também ergueu doze colunas, uma para cada tribo de Israel.

[[v2-24-5]]

^<<v2-24-5,5>>^ Em seguida, enviou alguns rapazes israelitas para apresentarem ao SENHOR holocaustos e touros sacrificados como ofertas de paz.

[[v2-24-6]]

^<<v2-24-6,6>>^ Moisés colocou em vasilhas metade do sangue desses animais e aspergiu a outra metade sobre o altar.

[[v2-24-7]]

^<<v2-24-7,7>>^ Depois, pegou o Livro da Aliança e o leu em voz alta para o povo. Mais uma vez, todos responderam: "Obedeceremos ao SENHOR! Faremos tudo que ele ordenou!".

[[v2-24-8]]

^<<v2-24-8,8>>^ Moisés pegou o sangue das vasilhas, aspergiu-o sobre o povo e declarou: "Este sangue confirma a aliança que o SENHOR fez com vocês quando lhes deu estas instruções".

[[v2-24-9]]

^<<v2-24-9,9>>^ Depois, Moisés, Arão, Nadabe, Abiú e os setenta líderes de Israel subiram ao monte,

[[v2-24-10]]

^<<v2-24-10,10>>^ onde viram o Deus de Israel, e sob os pés dele havia uma superfície azulada como a safira e clara como o céu.

[[v2-24-11]]

^<<v2-24-11,11>>^ E, embora esses nobres de Israel tenham visto Deus, ele não os destruiu, e eles participaram de uma refeição na presença dele.

[[v2-24-12]]

^<<v2-24-12,12>>^ Então o SENHOR disse a Moisés: "Suba ao monte para encontrar-se comigo. Fique lá e eu lhe darei tábuas de pedra nas quais gravei a lei e os mandamentos para ensinar ao povo".

[[v2-24-13]]

^<<v2-24-13,13>>^ Moisés e seu auxiliar, Josué, partiram e subiram ao monte de Deus.

[[v2-24-14]]

^<<v2-24-14,14>>^ "Esperem aqui até voltarmos", disse Moisés aos líderes. "Arão e Hur ficarão com vocês. Quem tiver algum problema para resolver durante minha ausência poderá consultá-los."

[[v2-24-15]]

^<<v2-24-15,15>>^ Então Moisés subiu ao monte, e a nuvem cobriu o monte.

[[v2-24-16]]

^<<v2-24-16,16>>^ A glória do SENHOR pousou sobre o monte Sinai, e a nuvem o cobriu por seis dias. No sétimo dia, o SENHOR chamou Moisés de dentro da nuvem.

[[v2-24-17]]

^<<v2-24-17,17>>^ Para os israelitas que estavam ao pé do monte, a glória do SENHOR no alto do Sinai parecia um fogo consumidor.

[[v2-24-18]]

^<<v2-24-18,18>>^ Moisés desapareceu na nuvem ao subir ao monte e ali permaneceu quarenta dias e quarenta noites.

'''

xref:002-exodo/002-exodo-023.adoc#v2-23-0[&#60; Capítulo Anterior] | <<v2-24-0,Topo>> | xref:002-exodo/002-exodo-025.adoc#v2-25-0[Próximo Capítulo &#62;]