include::./index.adoc[]

[[v2-9-0]]
=== Êxodo, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v2-9-1]]

^<<v2-9-1,1>>^ O SENHOR ordenou a Moisés: "Volte ao faraó e diga-lhe: ‘Assim diz o SENHOR, o Deus dos hebreus: Deixe meu povo sair para me adorar.

[[v2-9-2]]

^<<v2-9-2,2>>^ Se você continuar a detê-lo e a recusar-se a deixá-lo sair,

[[v2-9-3]]

^<<v2-9-3,3>>^ a mão do SENHOR ferirá com uma praga mortal todos os seus animais: cavalos, jumentos, camelos, bois e ovelhas.

[[v2-9-4]]

^<<v2-9-4,4>>^ Mais uma vez, porém, o SENHOR fará distinção entre os animais dos israelitas e os dos egípcios. Não morrerá um só animal de Israel.

[[v2-9-5]]

^<<v2-9-5,5>>^ O SENHOR já definiu quando a praga começará: amanhã o SENHOR ferirá a terra’".

[[v2-9-6]]

^<<v2-9-6,6>>^ O SENHOR fez como tinha dito. Na manhã seguinte, todos os animais dos egípcios morreram, mas os israelitas não perderam um só animal.

[[v2-9-7]]

^<<v2-9-7,7>>^ O faraó mandou investigar e confirmou que o povo de Israel não havia perdido um só animal. Ainda assim, o coração do faraó permaneceu endurecido, e ele continuou se recusando a deixar o povo sair.

[[v2-9-8]]

^<<v2-9-8,8>>^ O SENHOR disse a Moisés e a Arão: "Peguem um punhado de cinzas de um forno de olaria. Moisés deve lançá-las no ar, diante dos olhos do faraó.

[[v2-9-9]]

^<<v2-9-9,9>>^ As cinzas se espalharão sobre a terra do Egito como poeira fina e provocarão feridas purulentas nas pessoas e nos animais em todo o Egito".

[[v2-9-10]]

^<<v2-9-10,10>>^ Então Moisés e Arão pegaram um punhado de cinzas de um forno de olaria e se colocaram diante do faraó. Moisés lançou as cinzas no ar, e surgiram feridas tanto nas pessoas como nos animais.

[[v2-9-11]]

^<<v2-9-11,11>>^ Nem mesmo os magos conseguiram permanecer diante de Moisés, pois surgiram feridas neles, e também em todos os egípcios.

[[v2-9-12]]

^<<v2-9-12,12>>^ Mas o SENHOR endureceu o coração do faraó e, como o SENHOR tinha dito a Moisés, o faraó se recusou a ouvir.

[[v2-9-13]]

^<<v2-9-13,13>>^ O SENHOR disse a Moisés: "Amanhã, levante-se cedo, vá até o faraó e diga-lhe: ‘Assim diz o SENHOR, o Deus dos hebreus: Deixe meu povo sair para me adorar.

[[v2-9-14]]

^<<v2-9-14,14>>^ Do contrário, enviarei mais pragas sobre você, sobre seus oficiais e sobre seu povo. Então você saberá que não há ninguém como eu em toda a terra.

[[v2-9-15]]

^<<v2-9-15,15>>^ A esta altura, eu poderia ter estendido minha mão e ferido você e seu povo com uma praga que os apagaria da face da terra.

[[v2-9-16]]

^<<v2-9-16,16>>^ Mas eu o poupei a fim de lhe mostrar meu poder e propagar meu nome por toda a terra.

[[v2-9-17]]

^<<v2-9-17,17>>^ Ainda assim, você se exalta sobre meu povo, recusando-se a deixá-lo sair.

[[v2-9-18]]

^<<v2-9-18,18>>^ Por isso, amanhã, a esta hora, enviarei a tempestade de granizo mais devastadora de toda a história do Egito.

[[v2-9-19]]

^<<v2-9-19,19>>^ Rápido! Mande seus animais e servos deixarem os campos e procurarem abrigo. Quando o granizo cair, todas as pessoas e animais que estiverem ao ar livre morrerão’".

[[v2-9-20]]

^<<v2-9-20,20>>^ Alguns dos oficiais do faraó se atemorizaram com o que o SENHOR tinha dito. Sem demora, recolheram seus servos e animais dos campos.

[[v2-9-21]]

^<<v2-9-21,21>>^ Mas aqueles que não deram atenção à palavra do SENHOR deixaram seus rebanhos e servos no campo.

[[v2-9-22]]

^<<v2-9-22,22>>^ Então o SENHOR disse a Moisés: "Estenda a mão em direção ao céu para que caia granizo sobre toda a terra do Egito, sobre as pessoas, sobre os animais e sobre todas as plantas em toda a terra do Egito".

[[v2-9-23]]

^<<v2-9-23,23>>^ Moisés estendeu a vara em direção ao céu, e o SENHOR mandou trovões e granizo, além de raios que caíam sobre a terra. O SENHOR enviou uma horrível tempestade de granizo sobre todo o Egito.

[[v2-9-24]]

^<<v2-9-24,24>>^ Nunca em toda a história do Egito houve uma tempestade como aquela, com granizo tão devastador e raios tão constantes.

[[v2-9-25]]

^<<v2-9-25,25>>^ A chuva de granizo deixou toda a terra do Egito em ruínas. Destruiu tudo que estava no campo, tanto pessoas como animais e plantas, e até mesmo as árvores foram despedaçadas.

[[v2-9-26]]

^<<v2-9-26,26>>^ O único lugar em que não caiu granizo foi a região de Gósen, onde vivia o povo de Israel.

[[v2-9-27]]

^<<v2-9-27,27>>^ Então o faraó mandou chamar Moisés e Arão. "Desta vez eu pequei", disse ele. "O SENHOR é justo, e eu e meu povo somos culpados.

[[v2-9-28]]

^<<v2-9-28,28>>^ Por favor, supliquem ao SENHOR que ele ponha fim à tempestade horrível de trovões e granizo. Já chega! Eu os deixarei ir. Não precisam mais ficar aqui."

[[v2-9-29]]

^<<v2-9-29,29>>^ Moisés respondeu: "Assim que eu sair da cidade, estenderei as mãos ao SENHOR. Os trovões e o granizo cessarão, e o faraó saberá que a terra pertence ao SENHOR.

[[v2-9-30]]

^<<v2-9-30,30>>^ Mas sei que o faraó e seus oficiais ainda não temem o SENHOR Deus."

[[v2-9-31]]

^<<v2-9-31,31>>^ (Todo o linho e a cevada foram destruídos pelo granizo, pois a cevada estava na espiga, e o linho, em flor.

[[v2-9-32]]

^<<v2-9-32,32>>^ O trigo comum e o trigo candeal, porém, foram poupados, pois ainda não tinham brotado do solo.)

[[v2-9-33]]

^<<v2-9-33,33>>^ Moisés deixou a corte do faraó e saiu da cidade. Quando estendeu as mãos ao SENHOR, os trovões e o granizo cessaram, e a chuva torrencial parou.

[[v2-9-34]]

^<<v2-9-34,34>>^ Ao perceber que a chuva, o granizo e os trovões haviam cessado, o faraó voltou a pecar, e seu coração mais uma vez se endureceu, assim como o de seus oficiais.

[[v2-9-35]]

^<<v2-9-35,35>>^ Uma vez que seu coração continuava endurecido, o faraó se recusou a deixar o povo sair, como o SENHOR tinha dito por meio de Moisés.

'''

xref:002-exodo/002-exodo-008.adoc#v2-8-0[&#60; Capítulo Anterior] | <<v2-9-0,Topo>> | xref:002-exodo/002-exodo-010.adoc#v2-10-0[Próximo Capítulo &#62;]