include::./index.adoc[]

[[v2-6-0]]
=== Êxodo, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v2-6-1]]

^<<v2-6-1,1>>^ Então o SENHOR disse a Moisés: "Agora você verá o que vou fazer ao faraó. Quando ele sentir o peso de minha mão forte, deixará o povo sair. Sim, pelo peso de minha mão forte, fará o povo ir embora de sua terra!".

[[v2-6-2]]

^<<v2-6-2,2>>^ Deus também disse a Moisés: "Eu sou Javé, ‘o SENHOR’.

[[v2-6-3]]

^<<v2-6-3,3>>^ Apareci a Abraão, Isaque e Jacó como El-Shaddai, ‘o Deus Todo-poderoso’, mas não lhes revelei meu nome, Javé.

[[v2-6-4]]

^<<v2-6-4,4>>^ Estabeleci com eles a minha aliança, mediante a qual prometi lhes dar a terra de Canaã, onde viviam como estrangeiros.

[[v2-6-5]]

^<<v2-6-5,5>>^ Esteja certo de que ouvi os gemidos dos israelitas, que agora são escravos dos egípcios, e me lembrei da aliança que fiz com eles.

[[v2-6-6]]

^<<v2-6-6,6>>^ "Portanto, diga ao povo de Israel: ‘Eu sou o SENHOR. Eu os libertarei da opressão e os livrarei da escravidão no Egito. Eu os resgatarei com meu braço poderoso e com grandes atos de julgamento.

[[v2-6-7]]

^<<v2-6-7,7>>^ Eu os tomarei como meu povo e serei o seu Deus. Então vocês saberão que eu sou o SENHOR, seu Deus, que os libertou da opressão no Egito.

[[v2-6-8]]

^<<v2-6-8,8>>^ Eu os levarei à terra que jurei dar a Abraão, Isaque e Jacó. Eu a darei a vocês como propriedade. Eu sou o SENHOR!’".

[[v2-6-9]]

^<<v2-6-9,9>>^ Moisés transmitiu ao povo essa mensagem do SENHOR, mas eles já não quiseram lhe dar ouvidos. Estavam desanimados demais por causa da escravidão brutal que sofriam.

[[v2-6-10]]

^<<v2-6-10,10>>^ Então o SENHOR disse a Moisés:

[[v2-6-11]]

^<<v2-6-11,11>>^ "Volte ao faraó, o rei do Egito, e diga a ele que deixe o povo de Israel sair de sua terra".

[[v2-6-12]]

^<<v2-6-12,12>>^ "Mas SENHOR!", retrucou Moisés. "Os israelitas já não querem me dar ouvidos. Como posso esperar que o faraó me escute? Tenho tanta dificuldade para falar!"

[[v2-6-13]]

^<<v2-6-13,13>>^ O SENHOR, porém, falou com Moisés e Arão e lhes deu ordens, sobre os israelitas e sobre o faraó, rei do Egito, para tirarem o povo de Israel do Egito.

[[v2-6-14]]

^<<v2-6-14,14>>^ Estes são os chefes de clãs dos antepassados de Israel: Os filhos de Rúben, o filho mais velho de Israel, foram: Enoque, Palu, Hezrom e Carmi. Seus descendentes formaram os clãs de Rúben.

[[v2-6-15]]

^<<v2-6-15,15>>^ Os filhos de Simeão foram: Jemuel, Jamim, Oade, Jaquim, Zoar e Saul. (A mãe de Saul era cananeia.) Seus descendentes se tornaram os clãs de Simeão.

[[v2-6-16]]

^<<v2-6-16,16>>^ Estes são os descendentes de Levi, conforme relacionados nos registros de família. Os filhos de Levi foram Gérson, Coate e Merari. (Levi viveu 137 anos.)

[[v2-6-17]]

^<<v2-6-17,17>>^ Os descendentes de Gérson foram: Libni e Simei; cada um deles se tornou antepassado de um clã.

[[v2-6-18]]

^<<v2-6-18,18>>^ Os descendentes de Coate foram: Anrão, Isar, Hebrom e Uziel. (Coate viveu 133 anos.)

[[v2-6-19]]

^<<v2-6-19,19>>^ Os descendentes de Merari foram: Mali e Musi. Estes são os clãs dos levitas, conforme relacionados nos registros de família.

[[v2-6-20]]

^<<v2-6-20,20>>^ Anrão se casou com Joquebede, irmã de seu pai, e ela deu à luz dois filhos: Arão e Moisés. (Anrão viveu 137 anos.)

[[v2-6-21]]

^<<v2-6-21,21>>^ Os filhos de Isar foram: Corá, Nefegue e Zicri.

[[v2-6-22]]

^<<v2-6-22,22>>^ Os filhos de Uziel foram: Misael, Elzafã e Sitri.

[[v2-6-23]]

^<<v2-6-23,23>>^ Arão se casou com Eliseba, filha de Aminadabe e irmã de Naassom. Ela deu à luz seus filhos Nadabe, Abiú, Eleazar e Itamar.

[[v2-6-24]]

^<<v2-6-24,24>>^ Os filhos de Corá foram: Assir, Elcana e Abiasafe.

[[v2-6-25]]

^<<v2-6-25,25>>^ Eleazar, filho de Arão, se casou com uma das filhas de Putiel, e ela deu à luz seu filho Fineias. Esses são os chefes dentre os antepassados das famílias levitas, relacionados de acordo com seus clãs.

[[v2-6-26]]

^<<v2-6-26,26>>^ Foi a estes dois, Arão e Moisés, que o SENHOR disse: "Tirem os israelitas do Egito, organizados segundo seus clãs".

[[v2-6-27]]

^<<v2-6-27,27>>^ Foram eles, Moisés e Arão, que se dirigiram ao faraó, rei do Egito, para falar sobre a saída dos israelitas daquela terra.

[[v2-6-28]]

^<<v2-6-28,28>>^ Quando o SENHOR falou com Moisés na terra do Egito,

[[v2-6-29]]

^<<v2-6-29,29>>^ disse-lhe: "Eu sou o SENHOR! Transmita ao faraó, rei do Egito, tudo que eu lhe disser".

[[v2-6-30]]

^<<v2-6-30,30>>^ Contudo, Moisés questionou o SENHOR e disse: "Não posso fazer isso! Tenho tanta dificuldade para falar! Por que o faraó me daria ouvidos?".

'''

xref:002-exodo/002-exodo-005.adoc#v2-5-0[&#60; Capítulo Anterior] | <<v2-6-0,Topo>> | xref:002-exodo/002-exodo-007.adoc#v2-7-0[Próximo Capítulo &#62;]