include::./index.adoc[]

[[v2-27-0]]
=== Êxodo, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v2-27-1]]

^<<v2-27-1,1>>^ "Usando madeira de acácia, construa um altar quadrado com 2,25 metros de largura e comprimento e 1,35 metro de altura.

[[v2-27-2]]

^<<v2-27-2,2>>^ Faça uma ponta em forma de chifre para cada um dos quatro cantos, de modo que as pontas e o altar formem uma só peça. Revista o altar com bronze.

[[v2-27-3]]

^<<v2-27-3,3>>^ Faça baldes para recolher as cinzas, e também pás, bacias, garfos para a carne e braseiros, todos de bronze.

[[v2-27-4]]

^<<v2-27-4,4>>^ Faça ainda uma grelha de bronze e quatro argolas de bronze, uma para cada canto da grelha.

[[v2-27-5]]

^<<v2-27-5,5>>^ Coloque-a a meia altura do altar, debaixo da borda.

[[v2-27-6]]

^<<v2-27-6,6>>^ Para transportar o altar, faça varas de madeira de acácia e revista-as com bronze.

[[v2-27-7]]

^<<v2-27-7,7>>^ Passe as varas por dentro das argolas dos dois lados do altar quando ele for transportado.

[[v2-27-8]]

^<<v2-27-8,8>>^ O altar deve ser oco e feito de tábuas. Faça-o de acordo com o que lhe foi mostrado no monte."

[[v2-27-9]]

^<<v2-27-9,9>>^ "Em seguida, faça um pátio para o tabernáculo, fechado com cortinas de linho finamente tecido. As cortinas do lado sul terão 45 metros de comprimento

[[v2-27-10]]

^<<v2-27-10,10>>^ e serão penduradas em vinte colunas apoiadas firmemente em vinte bases de bronze. Pendure as cortinas com ganchos e argolas de prata.

[[v2-27-11]]

^<<v2-27-11,11>>^ Coloque do lado norte cortinas idênticas a essas, com 45 metros de comprimento, penduradas em vinte colunas apoiadas firmemente em vinte bases de bronze. Pendure as cortinas com ganchos e argolas de prata.

[[v2-27-12]]

^<<v2-27-12,12>>^ As cortinas do lado oeste do pátio terão 22,5 metros de comprimento e serão penduradas em dez colunas apoiadas em dez bases.

[[v2-27-13]]

^<<v2-27-13,13>>^ No lado leste do pátio, ou seja, na parte da frente, as cortinas também terão 22,5 metros de comprimento.

[[v2-27-14]]

^<<v2-27-14,14>>^ A entrada do pátio ficará do lado leste, situada entre duas cortinas. A cortina do lado direito terá 6,75 metros de comprimento e será pendurada em três colunas apoiadas em três bases.

[[v2-27-15]]

^<<v2-27-15,15>>^ A cortina do lado esquerdo também terá 6,75 metros de comprimento e será pendurada em três colunas apoiadas em três bases.

[[v2-27-16]]

^<<v2-27-16,16>>^ Para a entrada do pátio, confeccione uma cortina com 9 metros de comprimento. Faça-a de linho finamente tecido e enfeite-a com lindos bordados de fio azul, roxo e vermelho. Pendure-a em quatro colunas, cada uma firmemente apoiada em sua própria base.

[[v2-27-17]]

^<<v2-27-17,17>>^ Todas as colunas ao redor do pátio devem ter argolas e ganchos de prata e bases de bronze.

[[v2-27-18]]

^<<v2-27-18,18>>^ No total, o pátio terá 45 metros de comprimento e 22,5 metros de largura, com divisórias feitas de cortinas de linho finamente tecido com 2,25 metros de altura. As bases das colunas serão de bronze.

[[v2-27-19]]

^<<v2-27-19,19>>^ "Serão de bronze todos os utensílios para as cerimônias do tabernáculo, além das estacas usadas para sustentar o santuário e as cortinas do pátio."

[[v2-27-20]]

^<<v2-27-20,20>>^ "Ordene aos israelitas que lhe tragam óleo puro de oliva para a iluminação, a fim de manter as lâmpadas sempre acesas.

[[v2-27-21]]

^<<v2-27-21,21>>^ O candelabro ficará na tenda do encontro, do lado de fora da cortina interna que protege a arca da aliança. Arão e seus filhos manterão as lâmpadas acesas na presença do SENHOR a noite toda. Essa é uma lei permanente para o povo de Israel e deve ser cumprida de geração em geração."

'''

xref:002-exodo/002-exodo-026.adoc#v2-26-0[&#60; Capítulo Anterior] | <<v2-27-0,Topo>> | xref:002-exodo/002-exodo-028.adoc#v2-28-0[Próximo Capítulo &#62;]