include::./index.adoc[]

[[v2-26-0]]
=== Êxodo, 26
// nvt ?, NVT - Nova Versão Transformadora

[[v2-26-1]]

^<<v2-26-1,1>>^ "Faça o tabernáculo com dez cortinas de linho finamente tecido. Enfeite as cortinas com fios de tecido azul, roxo e vermelho e com querubins bordados com habilidade.

[[v2-26-2]]

^<<v2-26-2,2>>^ Essas dez cortinas devem ser todas exatamente do mesmo tamanho, com 12,6 metros de comprimento e 1,8 metro de largura.

[[v2-26-3]]

^<<v2-26-3,3>>^ Junte cinco cortinas para formar uma cortina longa e depois junte as cinco restantes para formar outra cortina longa.

[[v2-26-4]]

^<<v2-26-4,4>>^ Faça laços de tecido azul na borda da última cortina de cada conjunto.

[[v2-26-5]]

^<<v2-26-5,5>>^ Os cinquenta laços ao longo da borda da cortina do primeiro conjunto devem coincidir com os cinquenta laços da cortina do outro conjunto.

[[v2-26-6]]

^<<v2-26-6,6>>^ Em seguida, faça cinquenta colchetes de ouro e use-os para prender as cortinas longas uma à outra. Desse modo, o tabernáculo será formado de uma só peça contínua.

[[v2-26-7]]

^<<v2-26-7,7>>^ "Faça onze cortinas de tecido de pelo de cabra para cobrir o tabernáculo.

[[v2-26-8]]

^<<v2-26-8,8>>^ Essas onze cortinas devem ser todas exatamente do mesmo tamanho, com 13,5 metros de comprimento e 1,8 metro de largura.

[[v2-26-9]]

^<<v2-26-9,9>>^ Junte cinco cortinas para formar uma cortina longa e depois junte as seis restantes para formar outra cortina longa. No segundo conjunto de cortinas, deixe uma sobra de 90 centímetros de tecido pendurada sobre a parte da frente da tenda.

[[v2-26-10]]

^<<v2-26-10,10>>^ Faça cinquenta laços para a borda de cada cortina longa.

[[v2-26-11]]

^<<v2-26-11,11>>^ Em seguida, faça cinquenta colchetes de bronze e prenda com eles os laços das cortinas longas. Assim, a cobertura da tenda será formada de uma só peça contínua.

[[v2-26-12]]

^<<v2-26-12,12>>^ Os 90 centímetros restantes do tecido da cobertura ficarão pendurados na parte de trás do tabernáculo.

[[v2-26-13]]

^<<v2-26-13,13>>^ Deixe pendurados de cada lado os 45 centímetros restantes de tecido, para que o tabernáculo fique inteiramente coberto.

[[v2-26-14]]

^<<v2-26-14,14>>^ Complete a cobertura da tenda com uma camada protetora feita de peles de carneiro tingidas de vermelho e uma camada de couro fino.

[[v2-26-15]]

^<<v2-26-15,15>>^ "Para a estrutura do tabernáculo, construa armações de madeira de acácia.

[[v2-26-16]]

^<<v2-26-16,16>>^ Cada armação deve ter 4,5 metros de altura e 67,5 centímetros de largura,

[[v2-26-17]]

^<<v2-26-17,17>>^ com duas hastes na parte inferior de cada armação. Todas as armações devem ser idênticas.

[[v2-26-18]]

^<<v2-26-18,18>>^ Construa vinte armações para sustentar as cortinas do lado sul do tabernáculo.

[[v2-26-19]]

^<<v2-26-19,19>>^ Faça também quarenta bases de prata, duas para cada armação, para que as hastes se encaixem firmemente nas bases.

[[v2-26-20]]

^<<v2-26-20,20>>^ Para o lado norte do tabernáculo, construa outras vinte armações,

[[v2-26-21]]

^<<v2-26-21,21>>^ com quarenta bases de prata, duas bases para cada armação.

[[v2-26-22]]

^<<v2-26-22,22>>^ Construa seis armações para a parte de trás, o lado oeste do tabernáculo,

[[v2-26-23]]

^<<v2-26-23,23>>^ junto com mais duas armações para reforçar os cantos das duas extremidades do tabernáculo.

[[v2-26-24]]

^<<v2-26-24,24>>^ As armações dos cantos serão emparelhadas na parte inferior e firmemente ligadas uma à outra na parte superior com uma argola, formando um só suporte de canto. Siga o mesmo procedimento para ambos os suportes de canto.

[[v2-26-25]]

^<<v2-26-25,25>>^ O tabernáculo, portanto, terá oito armações na parte de trás, encaixadas sobre dezesseis bases de prata, duas bases para cada armação.

[[v2-26-26]]

^<<v2-26-26,26>>^ "Faça travessões de madeira de acácia para ligar as armações, cinco travessões para o lado norte do tabernáculo

[[v2-26-27]]

^<<v2-26-27,27>>^ e cinco travessões para o lado sul. Faça também cinco travessões para a parte de trás do tabernáculo, que ficará virada para o oeste.

[[v2-26-28]]

^<<v2-26-28,28>>^ O travessão central, ligado a meia altura às armações, se estenderá de uma ponta à outra do tabernáculo.

[[v2-26-29]]

^<<v2-26-29,29>>^ Revista as armações com ouro e faça argolas de ouro para sustentar os travessões. Também revista com ouro os travessões.

[[v2-26-30]]

^<<v2-26-30,30>>^ "Arme o tabernáculo de acordo com o modelo que lhe foi mostrado no monte.

[[v2-26-31]]

^<<v2-26-31,31>>^ "Para o interior do tabernáculo, confeccione uma cortina especial de linho finamente tecido. Enfeite-a com fios de tecido azul, roxo e vermelho e com querubins bordados com habilidade.

[[v2-26-32]]

^<<v2-26-32,32>>^ Pendure a cortina em ganchos de ouro presos em quatro colunas de madeira de acácia revestidas de ouro e apoiadas sobre quatro bases de prata.

[[v2-26-33]]

^<<v2-26-33,33>>^ Pendure a cortina interna com colchetes e coloque a arca da aliança atrás da cortina. Essa cortina separará o lugar santo do lugar santíssimo.

[[v2-26-34]]

^<<v2-26-34,34>>^ "Coloque a tampa, o lugar de expiação, sobre a arca da aliança, dentro do lugar santíssimo.

[[v2-26-35]]

^<<v2-26-35,35>>^ Coloque a mesa do lado de fora da cortina interna, no lado norte do tabernáculo, e posicione o candelabro em frente à mesa, ou seja, no lado sul.

[[v2-26-36]]

^<<v2-26-36,36>>^ "Confeccione outra cortina para a entrada da tenda. Ela deve ser de linho finamente tecido e artisticamente bordada com fios de tecido azul, roxo e vermelho.

[[v2-26-37]]

^<<v2-26-37,37>>^ Faça cinco colunas de madeira de acácia, revista-as com ouro e pendure nelas a cortina com ganchos de ouro. Mande fundir cinco bases de bronze para as colunas."

'''

xref:002-exodo/002-exodo-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodo/002-exodo-027.adoc#v2-27-0[Próximo Capítulo &#62;]