include::./index.adoc[]

[[v2-21-0]]
=== Êxodo, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v2-21-1]]

^<<v2-21-1,1>>^ "Estes são os decretos que você apresentará a Israel:

[[v2-21-2]]

^<<v2-21-2,2>>^ "Se você comprar um escravo hebreu, ele não poderá servi-lo por mais de seis anos. Liberte-o no sétimo ano, e ele nada lhe deverá pela liberdade.

[[v2-21-3]]

^<<v2-21-3,3>>^ Se ele era solteiro quando se tornou seu escravo, partirá solteiro. Mas, se era casado antes de se tornar seu escravo, a esposa deverá ser liberta com ele.

[[v2-21-4]]

^<<v2-21-4,4>>^ "Se seu senhor lhe deu uma mulher em casamento enquanto ele era escravo, e se o casal teve filhos e filhas, somente o homem será liberto no sétimo ano. A mulher e os filhos continuarão a pertencer ao senhor.

[[v2-21-5]]

^<<v2-21-5,5>>^ O escravo, contudo, poderá declarar: ‘Amo meu senhor, minha esposa e meus filhos. Não desejo ser liberto’.

[[v2-21-6]]

^<<v2-21-6,6>>^ Nesse caso, seu senhor o apresentará aos juízes. Em seguida, o levará até a porta ou até o batente da porta e furará a orelha dele com um furador. Depois disso, o escravo servirá a seu senhor pelo resto da vida.

[[v2-21-7]]

^<<v2-21-7,7>>^ "Quando um homem vender a filha como escrava, ela não será liberta como os homens.

[[v2-21-8]]

^<<v2-21-8,8>>^ Se ela não agradar seu senhor, ele permitirá que alguém lhe pague o resgate, mas não poderá vendê-la a estrangeiros, pois rompeu o contrato com ela.

[[v2-21-9]]

^<<v2-21-9,9>>^ Mas, se o senhor da escrava a entregar como mulher ao filho dele, não a tratará mais como escrava, mas sim como filha.

[[v2-21-10]]

^<<v2-21-10,10>>^ "Se um homem que se casou com uma escrava tomar para si outra esposa, não deverá descuidar dos direitos da primeira mulher com respeito a alimentação, vestuário e intimidade sexual.

[[v2-21-11]]

^<<v2-21-11,11>>^ Se ele não cumprir alguma dessas obrigações, ela poderá sair livre, sem pagar coisa alguma."

[[v2-21-12]]

^<<v2-21-12,12>>^ "Quem agredir e matar outra pessoa será executado,

[[v2-21-13]]

^<<v2-21-13,13>>^ mas se for apenas um acidente permitido por Deus, definirei um lugar de refúgio para onde o responsável pela morte possa fugir.

[[v2-21-14]]

^<<v2-21-14,14>>^ Se, contudo, alguém matar outra pessoa intencionalmente, o assassino será preso e executado, mesmo que tenha buscado refúgio em meu altar.

[[v2-21-15]]

^<<v2-21-15,15>>^ "Quem agredir seu pai ou sua mãe será executado.

[[v2-21-16]]

^<<v2-21-16,16>>^ "Quem sequestrar alguém será executado, quer a vítima seja encontrada em seu poder, quer ele a tenha vendido como escrava.

[[v2-21-17]]

^<<v2-21-17,17>>^ "Quem ofender a honra de seu pai ou de sua mãe será executado.

[[v2-21-18]]

^<<v2-21-18,18>>^ "Se dois homens brigarem e um deles acertar o outro com uma pedra ou com o punho e o outro não morrer, mas ficar de cama,

[[v2-21-19]]

^<<v2-21-19,19>>^ o agressor não será castigado se, posteriormente, o que foi ferido conseguir voltar a andar fora de casa, mesmo que precise de muletas; o agressor indenizará a vítima pelos salários que ela perder e se responsabilizará por sua total recuperação.

[[v2-21-20]]

^<<v2-21-20,20>>^ "Se um senhor espancar seu escravo ou sua escrava com uma vara e, como resultado, o escravo morrer, o senhor será castigado.

[[v2-21-21]]

^<<v2-21-21,21>>^ Mas, se o escravo se recuperar em um ou dois dias, o senhor não receberá castigo algum, pois o escravo é sua propriedade.

[[v2-21-22]]

^<<v2-21-22,22>>^ "Se dois homens brigarem e um deles atingir, por acidente, uma mulher grávida e ela der à luz prematuramente, sem que haja outros danos, o homem que atingiu a mulher pagará a indenização que o marido dela exigir e os juízes aprovarem.

[[v2-21-23]]

^<<v2-21-23,23>>^ Mas, se houver outros danos, o castigo deverá corresponder à gravidade do dano causado: vida por vida,

[[v2-21-24]]

^<<v2-21-24,24>>^ olho por olho, mão por mão, pé por pé,

[[v2-21-25]]

^<<v2-21-25,25>>^ queimadura por queimadura, ferida por ferida, contusão por contusão.

[[v2-21-26]]

^<<v2-21-26,26>>^ "Se um senhor ferir seu escravo ou sua escrava no olho e o cegar, libertará o escravo como compensação pelo olho.

[[v2-21-27]]

^<<v2-21-27,27>>^ Se quebrar o dente de seu escravo ou de sua escrava, libertará o escravo como compensação pelo dente.

[[v2-21-28]]

^<<v2-21-28,28>>^ "Se um boi matar a chifradas um homem ou uma mulher, o boi será apedrejado, e não será permitido comer sua carne. Nesse caso, porém, o dono do boi não será responsabilizado.

[[v2-21-29]]

^<<v2-21-29,29>>^ Mas, se o boi costumava chifrar pessoas e o dono havia sido informado, porém não manteve o animal sob controle, se o boi matar alguém, será apedrejado, e o dono também será executado.

[[v2-21-30]]

^<<v2-21-30,30>>^ Os parentes do morto, no entanto, poderão aceitar uma indenização pela vida perdida. O dono do boi poderá resgatar a própria vida ao pagar o que for exigido.

[[v2-21-31]]

^<<v2-21-31,31>>^ "A mesma lei se aplica se o boi chifrar um menino ou uma menina.

[[v2-21-32]]

^<<v2-21-32,32>>^ Mas, se o boi chifrar um escravo ou uma escrava, o dono do boi pagará trinta moedas de prata ao senhor do escravo, e o boi será apedrejado.

[[v2-21-33]]

^<<v2-21-33,33>>^ "Se alguém cavar ou destampar um poço e um boi ou jumento cair dentro dele,

[[v2-21-34]]

^<<v2-21-34,34>>^ o proprietário do poço indenizará totalmente o dono do animal, mas poderá ficar com o animal morto.

[[v2-21-35]]

^<<v2-21-35,35>>^ "Se o boi de alguém ferir o boi do vizinho e o animal ferido morrer, os dois donos venderão o animal vivo e dividirão o dinheiro entre si em partes iguais; também dividirão entre si o animal morto.

[[v2-21-36]]

^<<v2-21-36,36>>^ Mas, se o boi costumava chifrar e o dono não manteve o animal sob controle, o dono entregará um boi vivo como indenização pelo boi morto e poderá ficar com o animal morto."

'''

xref:002-exodo/002-exodo-020.adoc#v2-20-0[&#60; Capítulo Anterior] | <<v2-21-0,Topo>> | xref:002-exodo/002-exodo-022.adoc#v2-22-0[Próximo Capítulo &#62;]