include::./index.adoc[]

[[v2-16-0]]
=== Êxodo, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v2-16-1]]

^<<v2-16-1,1>>^ A comunidade de Israel partiu de Elim e chegou ao deserto de Sim, entre Elim e o monte Sinai, no décimo quinto dia do segundo mês, após a saída do Egito.

[[v2-16-2]]

^<<v2-16-2,2>>^ Também ali, toda a comunidade de Israel se queixou de Moisés e Arão.

[[v2-16-3]]

^<<v2-16-3,3>>^ "Se ao menos o SENHOR tivesse nos matado no Egito!", lamentavam-se. "Lá, nós nos sentávamos em volta de panelas cheias de carne e comíamos pão à vontade. Mas agora vocês nos trouxeram a este deserto para nos matar de fome!"

[[v2-16-4]]

^<<v2-16-4,4>>^ Então o SENHOR disse a Moisés: "Vejam, farei chover comida do céu para vocês. Diariamente o povo sairá e recolherá a quantidade de alimento que precisar para aquele dia. Com isso, eu os provarei para ver se seguirão ou não minhas instruções.

[[v2-16-5]]

^<<v2-16-5,5>>^ No sexto dia, quando recolherem o alimento e o prepararem, haverá o dobro do normal".

[[v2-16-6]]

^<<v2-16-6,6>>^ Assim, Moisés e Arão disseram a todos os israelitas: "Ao entardecer, vocês saberão que foi o SENHOR quem os tirou da terra do Egito.

[[v2-16-7]]

^<<v2-16-7,7>>^ Pela manhã, verão a glória do SENHOR, pois ele ouviu suas queixas, que são contra ele, e não contra nós. O que fizemos para vocês se queixarem de nós?".

[[v2-16-8]]

^<<v2-16-8,8>>^ E Moisés acrescentou: "O SENHOR lhes dará carne para comer à tarde e os saciará com pão pela manhã, pois ouviu suas queixas contra ele. O que fizemos? Sim, suas queixas são contra o SENHOR, e não contra nós".

[[v2-16-9]]

^<<v2-16-9,9>>^ Em seguida, Moisés disse a Arão: "Anuncie a toda a comunidade de Israel: ‘Apresentem-se diante do SENHOR, pois ele ouviu suas queixas’".

[[v2-16-10]]

^<<v2-16-10,10>>^ Enquanto Arão falava a toda a comunidade de Israel, o povo olhou em direção ao deserto e viu a glória do SENHOR na nuvem.

[[v2-16-11]]

^<<v2-16-11,11>>^ O SENHOR disse a Moisés:

[[v2-16-12]]

^<<v2-16-12,12>>^ "Ouvi as queixas dos israelitas. Agora diga-lhes: ‘Ao entardecer, vocês terão carne para comer e, pela manhã, pão à vontade. Assim, saberão que eu sou o SENHOR, seu Deus’".

[[v2-16-13]]

^<<v2-16-13,13>>^ Ao entardecer, muitas codornas apareceram, cobrindo o acampamento. Na manhã seguinte, os arredores do acampamento estavam úmidos de orvalho.

[[v2-16-14]]

^<<v2-16-14,14>>^ Quando o orvalho se evaporou, havia sobre o chão uma camada de flocos finos como geada.

[[v2-16-15]]

^<<v2-16-15,15>>^ Quando os israelitas viram aquilo, perguntaram uns aos outros: "O que é isso?", pois não faziam ideia do que era. Moisés lhes disse: "Este é o alimento que o SENHOR lhes deu para comer.

[[v2-16-16]]

^<<v2-16-16,16>>^ E estas são as instruções do SENHOR: ‘Cada família deve recolher a quantidade necessária, dois litros para cada pessoa de sua tenda’".

[[v2-16-17]]

^<<v2-16-17,17>>^ Os israelitas seguiram as instruções. Alguns recolheram mais, outros menos.

[[v2-16-18]]

^<<v2-16-18,18>>^ Contudo, quando mediram, cada um tinha o suficiente. Não sobrou alimento para os que recolheram mais nem faltou para os que recolheram menos. Cada família recolheu exatamente a quantidade necessária.

[[v2-16-19]]

^<<v2-16-19,19>>^ Moisés lhes disse: "Não guardem coisa alguma para o dia seguinte".

[[v2-16-20]]

^<<v2-16-20,20>>^ Alguns deles, porém, não deram ouvidos e guardaram um pouco de alimento até a manhã seguinte. A essa altura, a comida estava cheia de vermes e cheirava muito mal. Moisés ficou furioso com eles.

[[v2-16-21]]

^<<v2-16-21,21>>^ Depois disso, as famílias passaram a recolher, a cada manhã, a quantidade necessária de alimento. E, quando o sol esquentava, os flocos que não tinham sido recolhidos derretiam e desapareciam.

[[v2-16-22]]

^<<v2-16-22,22>>^ No sexto dia, recolheram o dobro do habitual, ou seja, quatro litros para cada pessoa. Então todos os líderes da comunidade se dirigiram a Moisés e o informaram a esse respeito.

[[v2-16-23]]

^<<v2-16-23,23>>^ Moisés lhes disse: "Foi o que o SENHOR ordenou: ‘Amanhã será um dia de descanso, o sábado consagrado para o SENHOR. Portanto, assem ou cozinhem hoje a quantidade que desejarem e guardem o restante para amanhã’".

[[v2-16-24]]

^<<v2-16-24,24>>^ Eles separaram uma porção para o dia seguinte, como Moisés havia ordenado. Pela manhã, a comida restante não tinha mau cheiro nem vermes.

[[v2-16-25]]

^<<v2-16-25,25>>^ Moisés disse: "Comam o alimento hoje, pois é o sábado do SENHOR. Hoje não haverá alimento no chão para recolher.

[[v2-16-26]]

^<<v2-16-26,26>>^ Durante seis dias vocês podem recolher alimento, mas o sétimo dia é o sábado, quando não haverá alimento algum no chão".

[[v2-16-27]]

^<<v2-16-27,27>>^ Ainda assim, algumas pessoas saíram para recolhê-lo no sétimo dia, mas não o encontraram.

[[v2-16-28]]

^<<v2-16-28,28>>^ O SENHOR disse a Moisés: "Até quando este povo se recusará a obedecer às minhas ordens e instruções?

[[v2-16-29]]

^<<v2-16-29,29>>^ Entendam que o sábado é um presente do SENHOR para vocês. Por isso, no sexto dia, ele lhes dá uma porção dobrada de alimento, suficiente para dois dias. No sábado, cada um deve ficar onde está. Não saiam para recolher alimento no sétimo dia".

[[v2-16-30]]

^<<v2-16-30,30>>^ No sétimo dia, portanto, o povo descansou.

[[v2-16-31]]

^<<v2-16-31,31>>^ Os israelitas chamaram aquela comida de maná. Era branco como a semente de coentro e tinha gosto de massa folhada de mel.

[[v2-16-32]]

^<<v2-16-32,32>>^ Então Moisés disse: "É isto que o SENHOR ordenou: ‘Encham uma vasilha de dois litros com maná e preservem-no para seus descendentes. Assim, as gerações futuras poderão ver o alimento que eu lhes dei no deserto quando os libertei do Egito’".

[[v2-16-33]]

^<<v2-16-33,33>>^ Moisés disse a Arão: "Pegue uma vasilha e encha-a com dois litros de maná. Em seguida, coloque-a diante do SENHOR, a fim de preservar o maná para as gerações futuras".

[[v2-16-34]]

^<<v2-16-34,34>>^ Arão fez conforme o SENHOR havia ordenado a Moisés e colocou a vasilha de maná diante das tábuas da aliança, para guardá-la.

[[v2-16-35]]

^<<v2-16-35,35>>^ Os israelitas comeram maná durante quarenta anos, até chegarem à terra onde se estabeleceriam. Comeram maná até chegarem à fronteira da terra de Canaã.

[[v2-16-36]]

^<<v2-16-36,36>>^ (A vasilha usada para medir o maná continha um ômer, que era a décima parte da medida padrão.)

'''

xref:002-exodo/002-exodo-015.adoc#v2-15-0[&#60; Capítulo Anterior] | <<v2-16-0,Topo>> | xref:002-exodo/002-exodo-017.adoc#v2-17-0[Próximo Capítulo &#62;]