include::./index.adoc[]

[[v2-15-0]]
=== Êxodo, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v2-15-1]]

^<<v2-15-1,1>>^ Então Moisés e o povo de Israel entoaram este cântico ao SENHOR: "Cantarei ao SENHOR, pois ele triunfou gloriosamente; lançou no mar o cavalo e seu cavaleiro.

[[v2-15-2]]

^<<v2-15-2,2>>^ O SENHOR é minha força e minha canção; ele é meu salvador. É o meu Deus e eu o louvarei; é o Deus de meu pai e eu o exaltarei.

[[v2-15-3]]

^<<v2-15-3,3>>^ O SENHOR é guerreiro; Javé é seu nome!

[[v2-15-4]]

^<<v2-15-4,4>>^ Lançou no mar os carros de guerra e as tropas do faraó; os melhores oficiais egípcios se afogaram no mar Vermelho.

[[v2-15-5]]

^<<v2-15-5,5>>^ Águas profundas os encobriram, e afundaram como pedra.

[[v2-15-6]]

^<<v2-15-6,6>>^ "Tua mão direita, ó SENHOR, é gloriosa em poder. Tua mão direita, ó SENHOR, despedaça o adversário.

[[v2-15-7]]

^<<v2-15-7,7>>^ Na grandeza de tua majestade, derrubas os que se levantam contra ti. Envias tua fúria ardente, que os consome como palha.

[[v2-15-8]]

^<<v2-15-8,8>>^ Com o forte sopro de tuas narinas, as águas se amontoaram; como muralhas se levantaram e no coração do mar se endureceram.

[[v2-15-9]]

^<<v2-15-9,9>>^ "O inimigo dizia: ‘Eu os perseguirei e os alcançarei; eu os saquearei e deles me vingarei. Puxarei minha espada e com forte mão os destruirei’.

[[v2-15-10]]

^<<v2-15-10,10>>^ Mas tu sopraste com teu fôlego, e o mar os encobriu. Afundaram como chumbo nas águas poderosas.

[[v2-15-11]]

^<<v2-15-11,11>>^ "Quem entre os deuses é semelhante a ti, ó SENHOR, glorioso em santidade, temível em esplendor, autor de grandes maravilhas?

[[v2-15-12]]

^<<v2-15-12,12>>^ Estendeste tua mão direita, e a terra engoliu nossos inimigos.

[[v2-15-13]]

^<<v2-15-13,13>>^ "Com o teu fiel amor, conduzes o povo que resgataste. Com teu poder, o guias à tua santa habitação.

[[v2-15-14]]

^<<v2-15-14,14>>^ Os povos ouvem e estremecem, a angústia se apodera dos que vivem na Filístia.

[[v2-15-15]]

^<<v2-15-15,15>>^ Aterrorizam-se os líderes de Edom, estremecem os nobres de Moabe. Desfalecem os habitantes de Canaã;

[[v2-15-16]]

^<<v2-15-16,16>>^ espanto e terror caem sobre eles. O poder do teu braço os deixa paralisados, como pedra, até teu povo passar, ó SENHOR, até passar o povo que compraste.

[[v2-15-17]]

^<<v2-15-17,17>>^ Tu os trarás e os plantarás em teu próprio monte, no lugar reservado, ó SENHOR, para tua habitação: o santuário, ó Soberano, que tuas mãos estabeleceram.

[[v2-15-18]]

^<<v2-15-18,18>>^ O SENHOR reinará para todo o sempre!".

[[v2-15-19]]

^<<v2-15-19,19>>^ Quando os cavalos, os carros de guerra e os cavaleiros do faraó entraram no mar, o SENHOR fez as águas do mar voltarem sobre eles. Mas o povo de Israel atravessou pelo meio do mar em terra seca.

[[v2-15-20]]

^<<v2-15-20,20>>^ Então a profetisa Miriã, irmã de Arão, pegou um tamborim e todas as mulheres a seguiram, tocando tamborins e dançando.

[[v2-15-21]]

^<<v2-15-21,21>>^ E Miriã entoava esta canção: "Cantem ao SENHOR, pois ele triunfou gloriosamente; lançou no mar o cavalo e seu cavaleiro".

[[v2-15-22]]

^<<v2-15-22,22>>^ Em seguida, Moisés conduziu o povo de Israel do mar Vermelho para o deserto de Sur. Caminharam pelo deserto por três dias sem encontrar água.

[[v2-15-23]]

^<<v2-15-23,23>>^ Quando chegaram a Mara, descobriram que a água era amarga demais para beber. Por isso chamaram aquele lugar de Mara.

[[v2-15-24]]

^<<v2-15-24,24>>^ O povo começou a se queixar e se voltou contra Moisés. "O que beberemos?", perguntavam.

[[v2-15-25]]

^<<v2-15-25,25>>^ Então Moisés clamou ao SENHOR, e o SENHOR lhe mostrou um pedaço de madeira. Moisés o jogou na água, e ela se tornou boa para beber. Foi em Mara que o SENHOR instituiu o seguinte decreto como norma, para provar a fidelidade do povo.

[[v2-15-26]]

^<<v2-15-26,26>>^ Ele disse: "Se ouvirem com atenção a voz do SENHOR, seu Deus, e fizerem o que é certo aos olhos dele, obedecendo a seus mandamentos e cumprindo todos os seus decretos, não os farei sofrer nenhuma das doenças que enviei sobre o Egito, pois eu sou o SENHOR que os cura".

[[v2-15-27]]

^<<v2-15-27,27>>^ Depois que saíram de Mara, os israelitas viajaram até Elim, onde encontraram doze fontes de água e setenta palmeiras, e acamparam ali, junto às águas.

'''

xref:002-exodo/002-exodo-014.adoc#v2-14-0[&#60; Capítulo Anterior] | <<v2-15-0,Topo>> | xref:002-exodo/002-exodo-016.adoc#v2-16-0[Próximo Capítulo &#62;]