include::./index.adoc[]

[[v2-5-0]]
=== Êxodo, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v2-5-1]]

^<<v2-5-1,1>>^ Depois disso, Moisés e Arão foram ver o faraó e declararam: "Assim diz o SENHOR, o Deus de Israel: ‘Deixe meu povo sair para celebrar uma festa em minha honra no deserto’".

[[v2-5-2]]

^<<v2-5-2,2>>^ "Quem é o SENHOR?", retrucou o faraó. "Por que devo dar ouvidos a ele e deixar Israel sair? Não conheço o SENHOR e não deixarei Israel sair."

[[v2-5-3]]

^<<v2-5-3,3>>^ Então Arão e Moisés disseram: "O Deus dos hebreus se encontrou conosco. Portanto, deixe-nos fazer uma viagem de três dias ao deserto para oferecermos sacrifícios ao SENHOR, nosso Deus. Do contrário, ele nos castigará com alguma praga ou pela espada".

[[v2-5-4]]

^<<v2-5-4,4>>^ O rei do Egito respondeu: "Moisés e Arão, por que distraem o povo de suas tarefas? Voltem ao trabalho!

[[v2-5-5]]

^<<v2-5-5,5>>^ Olhem! Há muitos do seu povo nesta terra, e vocês os estão impedindo de trabalhar!".

[[v2-5-6]]

^<<v2-5-6,6>>^ Naquele mesmo dia, o faraó deu a seguinte ordem aos capatazes egípcios e aos supervisores israelitas:

[[v2-5-7]]

^<<v2-5-7,7>>^ "Não forneçam mais palha para o povo fazer tijolos. De agora em diante, eles mesmos devem juntá-la!

[[v2-5-8]]

^<<v2-5-8,8>>^ No entanto, continuem a exigir que produzam a mesma quantidade de tijolos que antes. Não reduzam a cota. Eles são preguiçosos e, por isso, clamam: ‘Deixe-nos sair para sacrificar ao nosso Deus’.

[[v2-5-9]]

^<<v2-5-9,9>>^ Aumentem a carga de trabalho deles e cobrem o cumprimento das tarefas. Isso os ensinará a não dar ouvidos a mentiras!".

[[v2-5-10]]

^<<v2-5-10,10>>^ Os capatazes e os supervisores saíram e informaram o povo: "Assim diz o faraó: ‘Vocês não receberão mais palha.

[[v2-5-11]]

^<<v2-5-11,11>>^ Saiam e juntem-na onde puderem encontrá-la. No entanto, continuarão a produzir a mesma quantidade de tijolos que antes’".

[[v2-5-12]]

^<<v2-5-12,12>>^ Então o povo se espalhou por toda a terra do Egito para juntar a palha que sobrava das colheitas.

[[v2-5-13]]

^<<v2-5-13,13>>^ Enquanto isso, os capatazes egípcios continuavam a pressioná-los: "Completem sua cota diária de tijolos, como faziam quando nós lhes fornecíamos palha!".

[[v2-5-14]]

^<<v2-5-14,14>>^ E açoitavam os supervisores israelitas que haviam sido encarregados das equipes de trabalhadores. "Por que não completaram as cotas nem ontem nem hoje?", perguntavam.

[[v2-5-15]]

^<<v2-5-15,15>>^ Então os supervisores israelitas foram suplicar ao faraó: "Por favor, não trate seus servos desse modo.

[[v2-5-16]]

^<<v2-5-16,16>>^ Não recebemos palha, mas os capatazes continuam a exigir: ‘Façam tijolos!’. Somos açoitados constantemente, mas a culpa é do seu próprio povo!".

[[v2-5-17]]

^<<v2-5-17,17>>^ O faraó, porém, gritou: "Vocês são preguiçosos! Preguiçosos! Por isso, andam dizendo: ‘Deixe-nos sair para oferecer sacrifícios ao SENHOR’.

[[v2-5-18]]

^<<v2-5-18,18>>^ Voltem agora mesmo ao trabalho! Não receberão palha, mas terão de produzir a mesma cota de tijolos".

[[v2-5-19]]

^<<v2-5-19,19>>^ Quando os supervisores israelitas ouviram: "Vocês não poderão reduzir a quantidade de tijolos produzidos por dia", perceberam que estavam em sérios apuros.

[[v2-5-20]]

^<<v2-5-20,20>>^ Ao sair do palácio do faraó, encontraram Moisés e Arão, que os esperavam do lado de fora.

[[v2-5-21]]

^<<v2-5-21,21>>^ Eles disseram aos dois irmãos: "O SENHOR os julgue e os castigue por terem feito o faraó e seus oficiais nos odiarem. Vocês colocaram uma espada na mão deles e lhes deram uma desculpa para nos matar!".

[[v2-5-22]]

^<<v2-5-22,22>>^ Moisés voltou ao SENHOR e disse: "Por que trouxeste toda essa desgraça sobre este povo, Senhor? Por que me enviaste?

[[v2-5-23]]

^<<v2-5-23,23>>^ Desde que me apresentei ao faraó como teu porta-voz, ele passou a tratar teu povo com ainda mais crueldade. E tu não fizeste coisa alguma para libertá-lo!".

'''

xref:002-exodo/002-exodo-004.adoc#v2-4-0[&#60; Capítulo Anterior] | <<v2-5-0,Topo>> | xref:002-exodo/002-exodo-006.adoc#v2-6-0[Próximo Capítulo &#62;]