include::./index.adoc[]

[[v2-40-0]]
=== Êxodo, 40
// nvt ?, NVT - Nova Versão Transformadora

[[v2-40-1]]

^<<v2-40-1,1>>^ O SENHOR disse a Moisés:

[[v2-40-2]]

^<<v2-40-2,2>>^ "Arme o tabernáculo, a tenda do encontro, no primeiro dia do primeiro mês.

[[v2-40-3]]

^<<v2-40-3,3>>^ Coloque a arca da aliança dentro dele e pendure a cortina interna para proteger a arca.

[[v2-40-4]]

^<<v2-40-4,4>>^ Depois, traga a mesa para dentro e coloque sobre ela os utensílios. Traga também o candelabro e instale suas lâmpadas.

[[v2-40-5]]

^<<v2-40-5,5>>^ "Ponha o altar de ouro para o incenso diante da arca da aliança e pendure a cortina à entrada do tabernáculo.

[[v2-40-6]]

^<<v2-40-6,6>>^ Coloque o altar do holocausto diante da entrada do tabernáculo, a tenda do encontro.

[[v2-40-7]]

^<<v2-40-7,7>>^ Ponha a bacia entre a tenda do encontro e o altar e encha-a de água.

[[v2-40-8]]

^<<v2-40-8,8>>^ Em seguida, arme o pátio ao redor da tenda e pendure a cortina da entrada do pátio.

[[v2-40-9]]

^<<v2-40-9,9>>^ "Pegue o óleo da unção e unja o tabernáculo e toda a sua mobília, para consagrá-los; assim, ele será santo.

[[v2-40-10]]

^<<v2-40-10,10>>^ Unja o altar do holocausto e seus utensílios para consagrá-los; assim, ele será santíssimo.

[[v2-40-11]]

^<<v2-40-11,11>>^ Depois, unja a bacia e seu suporte para consagrá-los.

[[v2-40-12]]

^<<v2-40-12,12>>^ "Traga Arão e seus filhos até a entrada da tenda do encontro e lave-os com água.

[[v2-40-13]]

^<<v2-40-13,13>>^ Vista Arão com as roupas sagradas, unja-o e consagre-o, para que me sirva como sacerdote.

[[v2-40-14]]

^<<v2-40-14,14>>^ Traga os filhos de Arão e vista-os com as túnicas.

[[v2-40-15]]

^<<v2-40-15,15>>^ Unja-os como ungiu o pai deles, para que também me sirvam como sacerdotes. Com a unção, os descendentes de Arão são separados para o sacerdócio para sempre, de geração em geração".

[[v2-40-16]]

^<<v2-40-16,16>>^ Moisés fez tudo que o SENHOR lhe havia ordenado.

[[v2-40-17]]

^<<v2-40-17,17>>^ O tabernáculo foi armado no primeiro dia do primeiro mês do segundo ano.

[[v2-40-18]]

^<<v2-40-18,18>>^ Para armar o tabernáculo, Moisés colocou as bases em seus lugares, encaixou as armações, prendeu os travessões e levantou as colunas.

[[v2-40-19]]

^<<v2-40-19,19>>^ Em seguida, estendeu a tenda sobre a estrutura do tabernáculo e, por cima, colocou a cobertura, conforme o SENHOR havia ordenado.

[[v2-40-20]]

^<<v2-40-20,20>>^ Pegou as tábuas da aliança e as colocou dentro da arca. Prendeu à arca as varas para transportá-la e a cobriu com a tampa, o lugar de expiação.

[[v2-40-21]]

^<<v2-40-21,21>>^ Depois, trouxe a arca da aliança para dentro da tenda do encontro e pendurou a cortina interna que a protegia, conforme o SENHOR havia ordenado.

[[v2-40-22]]

^<<v2-40-22,22>>^ Em seguida, Moisés colocou a mesa da tenda do encontro do lado norte do lugar santo, do lado de fora da cortina interna.

[[v2-40-23]]

^<<v2-40-23,23>>^ Arrumou sobre a mesa os pães da presença diante do SENHOR, conforme o SENHOR havia ordenado.

[[v2-40-24]]

^<<v2-40-24,24>>^ Pôs o candelabro dentro da tenda do encontro, em frente à mesa, do lado sul do lugar santo.

[[v2-40-25]]

^<<v2-40-25,25>>^ Acendeu as lâmpadas na presença do SENHOR, conforme o SENHOR havia ordenado.

[[v2-40-26]]

^<<v2-40-26,26>>^ Colocou também o altar de ouro para o incenso na tenda do encontro diante da cortina interna

[[v2-40-27]]

^<<v2-40-27,27>>^ e queimou sobre ele incenso perfumado, conforme o SENHOR havia ordenado.

[[v2-40-28]]

^<<v2-40-28,28>>^ Pendurou a cortina à entrada do tabernáculo

[[v2-40-29]]

^<<v2-40-29,29>>^ e colocou o altar do holocausto perto da entrada do tabernáculo, a tenda do encontro. Apresentou sobre o altar um holocausto e uma oferta de cereal, conforme o SENHOR havia ordenado.

[[v2-40-30]]

^<<v2-40-30,30>>^ Em seguida, Moisés colocou a bacia entre a tenda do encontro e o altar e encheu-a de água para que os sacerdotes pudessem se lavar.

[[v2-40-31]]

^<<v2-40-31,31>>^ Moisés, Arão e os filhos de Arão usavam a água da bacia para lavar as mãos e os pés.

[[v2-40-32]]

^<<v2-40-32,32>>^ Lavavam-se cada vez que se aproximavam do altar e entravam na tenda do encontro, conforme o SENHOR havia ordenado.

[[v2-40-33]]

^<<v2-40-33,33>>^ Moisés pendurou as cortinas que cercavam o pátio ao redor do tabernáculo e do altar e colocou a cortina à entrada do pátio. Assim, Moisés finalmente terminou o trabalho.

[[v2-40-34]]

^<<v2-40-34,34>>^ Então a nuvem cobriu a tenda do encontro, e a glória do SENHOR encheu o tabernáculo.

[[v2-40-35]]

^<<v2-40-35,35>>^ Moisés não podia mais entrar na tenda do encontro, pois a nuvem estava sobre ela, e a glória do SENHOR a enchia.

[[v2-40-36]]

^<<v2-40-36,36>>^ Sempre que a nuvem se levantava de cima do tabernáculo, os israelitas seguiam viagem.

[[v2-40-37]]

^<<v2-40-37,37>>^ Mas, se a nuvem não se levantava, permaneciam onde estavam até a nuvem se elevar.

[[v2-40-38]]

^<<v2-40-38,38>>^ Durante o dia, a nuvem do SENHOR pairava no ar acima do tabernáculo e, à noite, fogo ardia dentro da nuvem, de modo que todo o povo de Israel podia vê-la. E isso ocorreu ao longo de todas as jornadas dos israelitas.

'''

xref:002-exodo/002-exodo-039.adoc#v2-39-0[&#60; Capítulo Anterior] | <<v2-40-0,Topo>> | xref:003-levitico/003-levitico-001.adoc#v3-1-0[Próximo Capítulo &#62;]