include::./index.adoc[]

[[v7-9-0]]
=== Juízes, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v7-9-1]]

^<<v7-9-1,1>>^ Certo dia, Abimeleque, filho de Gideão, foi a Siquém visitar os irmãos de sua mãe e disse a eles e aos demais membros do seu clã materno:

[[v7-9-2]]

^<<v7-9-2,2>>^ "Perguntem aos líderes de Siquém se preferem ser governados por todos os setenta filhos de Gideão ou por um só homem. E lembrem-se de que eu sou da mesma carne e do mesmo sangue de vocês!".

[[v7-9-3]]

^<<v7-9-3,3>>^ Então os tios de Abimeleque transmitiram sua mensagem a todos os líderes de Siquém, que, depois de ouvirem a proposta, decidiram em favor de Abimeleque, pois era parente deles.

[[v7-9-4]]

^<<v7-9-4,4>>^ Deram-lhe setenta moedas de prata do templo de Baal-Berite, que ele usou para contratar indivíduos desocupados e desordeiros que concordaram em segui-lo.

[[v7-9-5]]

^<<v7-9-5,5>>^ Ele foi à casa de seu pai em Ofra e ali, sobre uma pedra, matou todos os seus setenta meios-irmãos, os filhos de Gideão, exceto Jotão, o filho mais novo, que fugiu e se escondeu.

[[v7-9-6]]

^<<v7-9-6,6>>^ Então os líderes de Siquém e Bete-Milo convocaram uma reunião debaixo do carvalho perto da coluna em Siquém e proclamaram Abimeleque rei.

[[v7-9-7]]

^<<v7-9-7,7>>^ Quando Jotão soube disso, subiu ao topo do monte Gerizim e gritou: "Ouçam-me, cidadãos de Siquém! Ouçam-me se querem que Deus os ouça!

[[v7-9-8]]

^<<v7-9-8,8>>^ Certa vez as árvores resolveram ungir um rei. Primeiro disseram à oliveira: ‘Seja nosso rei!’.

[[v7-9-9]]

^<<v7-9-9,9>>^ Mas a oliveira se recusou e disse: ‘Devo deixar de produzir o óleo que agrada a Deus e às pessoas, só para ser a mais alta das árvores que o vento agita?’.

[[v7-9-10]]

^<<v7-9-10,10>>^ "Então disseram à figueira: ‘Seja nosso rei!’.

[[v7-9-11]]

^<<v7-9-11,11>>^ Mas a figueira também se recusou e disse: ‘Devo deixar de produzir meus frutos doces e deliciosos, só para ser a mais alta das árvores que o vento agita?’.

[[v7-9-12]]

^<<v7-9-12,12>>^ "Então disseram à videira: ‘Seja nosso rei!’.

[[v7-9-13]]

^<<v7-9-13,13>>^ Mas a videira também se recusou e disse: ‘Devo deixar de produzir o vinho que alegra a Deus e às pessoas, só para ser a mais alta das árvores que o vento agita?’.

[[v7-9-14]]

^<<v7-9-14,14>>^ "Por fim, todas as árvores se voltaram para o espinheiro e disseram: ‘Seja nosso rei!’.

[[v7-9-15]]

^<<v7-9-15,15>>^ E o espinheiro respondeu às árvores: ‘Se querem mesmo ungir-me seu rei, venham abrigar-se à minha sombra. Se não, que saia fogo de mim e queime os cedros do Líbano’".

[[v7-9-16]]

^<<v7-9-16,16>>^ Jotão prosseguiu: "Será que vocês de fato agiram de forma honrada e íntegra ao proclamar Abimeleque seu rei? Será que foram justos com Gideão e seus descendentes? Vocês o trataram como ele merece, tendo em vista tudo que realizou?

[[v7-9-17]]

^<<v7-9-17,17>>^ Meu pai lutou por vocês e arriscou a vida para libertá-los dos midianitas.

[[v7-9-18]]

^<<v7-9-18,18>>^ Mas hoje vocês se rebelaram contra ele e seus descendentes e mataram seus setenta filhos sobre uma pedra. Escolheram Abimeleque, filho da escrava dele, para ser rei só porque ele é seu parente.

[[v7-9-19]]

^<<v7-9-19,19>>^ "Se hoje agiram de forma honrada e íntegra com Gideão e seus descendentes, então que sejam felizes com Abimeleque, e ele seja feliz com vocês.

[[v7-9-20]]

^<<v7-9-20,20>>^ Mas, se não o fizeram, então que saia fogo de Abimeleque e queime os líderes de Siquém e Bete-Milo, e saia fogo dos líderes de Siquém e Bete-Milo e queime Abimeleque!".

[[v7-9-21]]

^<<v7-9-21,21>>^ Então Jotão fugiu e foi morar em Beer, pois tinha medo de seu irmão Abimeleque.

[[v7-9-22]]

^<<v7-9-22,22>>^ Depois que Abimeleque havia governado Israel por três anos,

[[v7-9-23]]

^<<v7-9-23,23>>^ Deus enviou um espírito que gerou discórdia entre Abimeleque e os líderes de Siquém, que se rebelaram.

[[v7-9-24]]

^<<v7-9-24,24>>^ Foi um castigo para Abimeleque por ele ter assassinado os setenta filhos de Gideão e para os líderes de Siquém por terem apoiado Abimeleque no assassinato de seus irmãos.

[[v7-9-25]]

^<<v7-9-25,25>>^ Os líderes de Siquém prepararam uma emboscada para Abimeleque no alto dos montes e assaltavam todos os que passavam por ali. Contudo, alguém alertou Abimeleque sobre essa conspiração.

[[v7-9-26]]

^<<v7-9-26,26>>^ Nessa época, Gaal, filho de Ebede, se mudou para Siquém com seus irmãos e ganhou a confiança dos líderes da cidade.

[[v7-9-27]]

^<<v7-9-27,27>>^ Depois de irem ao campo, colherem as uvas e pisarem nelas, realizaram uma festa da colheita, no templo do deus local. Foi servido vinho à vontade, e todos começaram a amaldiçoar Abimeleque.

[[v7-9-28]]

^<<v7-9-28,28>>^ "Quem é Abimeleque?", disse em alta voz Gaal, filho de Ebede. "Se não é um verdadeiro filho de Siquém, por que devemos servi-lo? É apenas filho de Gideão, e esse Zebul é apenas seu ajudante. Sirvam aos verdadeiros filhos de Hamor, o fundador de Siquém! Por que devemos servir a Abimeleque?

[[v7-9-29]]

^<<v7-9-29,29>>^ Se eu estivesse no comando, me livraria de Abimeleque. Diria a ele: ‘Convoque seus soldados e venha lutar!’."

[[v7-9-30]]

^<<v7-9-30,30>>^ Mas, quando Zebul, que governava a cidade, tomou conhecimento das palavras de Gaal, ficou furioso.

[[v7-9-31]]

^<<v7-9-31,31>>^ Enviou mensageiros a Abimeleque em Arumá para lhe dizer: "Gaal, filho de Ebede, e seus irmãos se mudaram para Siquém e estão instigando a cidade a se rebelar contra você.

[[v7-9-32]]

^<<v7-9-32,32>>^ Venha de noite com seu exército e esconda-se nos campos.

[[v7-9-33]]

^<<v7-9-33,33>>^ Pela manhã, assim que o sol nascer, ataque a cidade. Quando Gaal e aqueles que o acompanham saírem para lutar contra você, faça com eles o que desejar".

[[v7-9-34]]

^<<v7-9-34,34>>^ Então Abimeleque e todos os seus homens saíram de noite, dividiram-se em quatro grupos e armaram uma emboscada ao redor de Siquém.

[[v7-9-35]]

^<<v7-9-35,35>>^ Gaal, filho de Ebede, estava à porta da cidade quando Abimeleque e seu exército saíram de seus esconderijos.

[[v7-9-36]]

^<<v7-9-36,36>>^ Quando Gaal os viu, disse a Zebul: "Olhe, há pessoas descendo do alto das colinas!". Zebul respondeu: "São apenas as sombras dos montes que se parecem com homens".

[[v7-9-37]]

^<<v7-9-37,37>>^ Mas Gaal insistiu: "Não! São pessoas descendo das colinas. E outro grupo vem pela estrada que passa pelo Carvalho dos Adivinhos".

[[v7-9-38]]

^<<v7-9-38,38>>^ Zebul se voltou para ele e perguntou: "Onde foi parar toda a sua conversa? Não foi você que disse: ‘Quem é Abimeleque e por que deveríamos servi-lo?’. Os homens dos quais você zombou estão logo ali do lado de fora da cidade! Saia e lute contra eles!".

[[v7-9-39]]

^<<v7-9-39,39>>^ Então Gaal marchou à frente dos líderes de Siquém para a batalha contra Abimeleque.

[[v7-9-40]]

^<<v7-9-40,40>>^ Abimeleque perseguiu Gaal, e muitos homens de Siquém foram feridos e caíram pelo caminho enquanto recuavam até o portão da cidade.

[[v7-9-41]]

^<<v7-9-41,41>>^ Abimeleque voltou a Arumá, e Zebul expulsou Gaal e seus irmãos de Siquém.

[[v7-9-42]]

^<<v7-9-42,42>>^ No dia seguinte, o povo de Siquém saiu para guerrear nos campos. Abimeleque soube disso,

[[v7-9-43]]

^<<v7-9-43,43>>^ dividiu seus homens em três grupos e armou emboscadas nos campos. Quando Abimeleque viu o povo sair da cidade, ele e seus homens saíram de seus esconderijos e atacaram.

[[v7-9-44]]

^<<v7-9-44,44>>^ Abimeleque e seu grupo tomaram de assalto o portão da cidade para impedir que os homens de Siquém voltassem para dentro. Enquanto isso, os outros dois grupos atacaram e mataram aqueles que estavam nos campos.

[[v7-9-45]]

^<<v7-9-45,45>>^ A batalha durou o dia inteiro. Por fim, Abimeleque tomou Siquém e matou seus habitantes. Depois, destruiu a cidade e espalhou sal em todo o solo.

[[v7-9-46]]

^<<v7-9-46,46>>^ Ao tomarem conhecimento do que havia acontecido, os líderes que viviam na torre de Siquém correram e se esconderam na fortaleza do templo de Baal-Berite.

[[v7-9-47]]

^<<v7-9-47,47>>^ Quando alguém informou Abimeleque de que esses habitantes estavam reunidos ali,

[[v7-9-48]]

^<<v7-9-48,48>>^ ele levou seu exército ao monte Zalmom. Pegou um machado, cortou alguns galhos de uma árvore e os pôs sobre os ombros. "Rápido! Façam como eu!", disse a seus homens.

[[v7-9-49]]

^<<v7-9-49,49>>^ Assim, cada um cortou alguns galhos e fez como Abimeleque. Então amontoaram os galhos junto às paredes do templo e puseram fogo. Todos que viviam na torre de Siquém morreram, cerca de mil homens e mulheres.

[[v7-9-50]]

^<<v7-9-50,50>>^ Em seguida, Abimeleque atacou a cidade de Tebes e a conquistou.

[[v7-9-51]]

^<<v7-9-51,51>>^ No meio da cidade, porém, havia uma torre forte, e toda a população, homens e mulheres, fugiu para lá. Trancaram-se por dentro e subiram até o terraço.

[[v7-9-52]]

^<<v7-9-52,52>>^ Abimeleque foi até a torre e a atacou. Mas, quando se preparava para incendiar a entrada da torre,

[[v7-9-53]]

^<<v7-9-53,53>>^ uma mulher que estava no terraço jogou na cabeça de Abimeleque uma pedra de moinho, que rachou seu crânio.

[[v7-9-54]]

^<<v7-9-54,54>>^ Sem demora, ele disse a seu jovem escudeiro: "Tire a espada e mate-me! Assim ninguém dirá que uma mulher matou Abimeleque!". O jovem o atravessou com sua espada, e ele morreu.

[[v7-9-55]]

^<<v7-9-55,55>>^ Quando os israelitas viram que Abimeleque estava morto, debandaram e voltaram para casa.

[[v7-9-56]]

^<<v7-9-56,56>>^ Desse modo, Deus castigou Abimeleque pelo mal que ele havia feito a seu pai, matando os setenta irmãos.

[[v7-9-57]]

^<<v7-9-57,57>>^ Deus também castigou os homens de Siquém por toda a sua maldade. Assim cumpriu-se a maldição de Jotão, filho de Gideão.

'''

xref:007-juizes/007-juizes-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-juizes/007-juizes-010.adoc#v7-10-0[Próximo Capítulo &#62;]