include::./index.adoc[]

[[v7-8-0]]
=== Juízes, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v7-8-1]]

^<<v7-8-1,1>>^ Então os homens da tribo de Efraim perguntaram a Gideão: "Por que você nos tratou dessa forma? Por que não nos chamou quando foi lutar com os midianitas?". E o repreenderam duramente.

[[v7-8-2]]

^<<v7-8-2,2>>^ Gideão, porém, respondeu: "O que eu fiz em comparação com vocês? A sobra das uvas da colheita de Efraim não são melhores que toda a colheita do pequeno clã de Abiezer?

[[v7-8-3]]

^<<v7-8-3,3>>^ Deus entregou em suas mãos Orebe e Zeebe, os comandantes do exército midianita. O que eu fiz em comparação com isso?". Quando ouviram a resposta de Gideão, a indignação dos homens de Efraim diminuiu.

[[v7-8-4]]

^<<v7-8-4,4>>^ Então Gideão atravessou o rio Jordão com os trezentos homens e, embora estivessem exaustos, continuaram a perseguir o inimigo.

[[v7-8-5]]

^<<v7-8-5,5>>^ Quando chegaram a Sucote, Gideão pediu ao povo da cidade: "Por favor, deem um pouco de comida aos meus guerreiros. Eles estão muito cansados. Estou perseguindo Zeba e Zalmuna, reis de Midiã".

[[v7-8-6]]

^<<v7-8-6,6>>^ Mas os líderes de Sucote responderam: "Primeiro capture Zeba e Zalmuna, e então daremos comida ao seu exército".

[[v7-8-7]]

^<<v7-8-7,7>>^ "Muito bem", disse Gideão. "Depois que o SENHOR entregar Zeba e Zalmuna em minhas mãos, voltarei e rasgarei a carne de vocês com espinhos e com espinheiros do deserto."

[[v7-8-8]]

^<<v7-8-8,8>>^ Dali Gideão subiu a Peniel, onde também pediu comida e recebeu a mesma resposta.

[[v7-8-9]]

^<<v7-8-9,9>>^ Disse ele ao povo de Peniel: "Quando eu voltar vitorioso, derrubarei esta torre".

[[v7-8-10]]

^<<v7-8-10,10>>^ A essa altura, Zeba e Zalmuna estavam em Carcor com cerca de quinze mil guerreiros. Era tudo que restava dos exércitos aliados do leste, pois 120 mil já haviam sido mortos.

[[v7-8-11]]

^<<v7-8-11,11>>^ Gideão subiu pela rota das caravanas, a leste de Noba e Jogbeá, e atacou de surpresa o exército midianita.

[[v7-8-12]]

^<<v7-8-12,12>>^ Zeba e Zalmuna, os dois reis midianitas, fugiram, mas Gideão os perseguiu e os capturou, derrotando seu exército.

[[v7-8-13]]

^<<v7-8-13,13>>^ Gideão, filho de Joás, voltou da batalha pelo desfiladeiro de Heres.

[[v7-8-14]]

^<<v7-8-14,14>>^ Ali, capturou um jovem de Sucote e exigiu que ele escrevesse o nome dos 77 oficiais e autoridades da cidade.

[[v7-8-15]]

^<<v7-8-15,15>>^ Então Gideão retornou a Sucote e disse ao povo: "Aqui estão Zeba e Zalmuna. Quando estivemos aqui antes, vocês zombaram de mim e disseram: ‘Primeiro capture Zeba e Zalmuna, e então daremos comida aos seus guerreiros exaustos’".

[[v7-8-16]]

^<<v7-8-16,16>>^ Gideão prendeu as autoridades da cidade e os castigou com espinhos e espinheiros do deserto.

[[v7-8-17]]

^<<v7-8-17,17>>^ Também derrubou a torre de Peniel e matou os homens da cidade.

[[v7-8-18]]

^<<v7-8-18,18>>^ Depois disso, Gideão perguntou a Zeba e a Zalmuna: "Como eram os homens que vocês mataram em Tabor?". "Como você", responderam eles. "Todos pareciam filhos de rei."

[[v7-8-19]]

^<<v7-8-19,19>>^ "Eram meus irmãos, filhos de minha mãe!", exclamou Gideão. "Tão certo como vive o SENHOR, eu não mataria vocês se tivessem poupado a vida deles!"

[[v7-8-20]]

^<<v7-8-20,20>>^ Gideão se voltou para Jéter, seu filho mais velho, e disse: "Mate-os!". Mas Jéter não tirou sua espada, pois ainda era jovem e teve medo.

[[v7-8-21]]

^<<v7-8-21,21>>^ Então Zeba e Zalmuna disseram a Gideão: "Seja homem! Mate-nos você mesmo!". Gideão os matou e tirou os enfeites que estavam no pescoço dos camelos deles.

[[v7-8-22]]

^<<v7-8-22,22>>^ Então os israelitas disseram a Gideão: "Seja nosso governante! Você, seu filho e seu neto nos governarão, pois nos libertou de Midiã".

[[v7-8-23]]

^<<v7-8-23,23>>^ Gideão, porém, respondeu: "Nem eu nem meu filho governaremos vocês. O SENHOR os governará!

[[v7-8-24]]

^<<v7-8-24,24>>^ Mas tenho um pedido a fazer. Cada um de vocês me dê uma argola de ouro que tomou de seus inimigos como despojo". (Uma vez que os inimigos eram ismaelitas, todos usavam argolas de ouro.)

[[v7-8-25]]

^<<v7-8-25,25>>^ "Com todo o prazer!", responderam eles. Estenderam uma capa, e cada um jogou ali uma argola de ouro que havia tomado como despojo.

[[v7-8-26]]

^<<v7-8-26,26>>^ O peso das argolas de ouro totalizou pouco mais de vinte quilos, sem contar os enfeites, os pendentes e as roupas de púrpura que os reis de Midiã usavam, além das correntes que estavam no pescoço de seus camelos.

[[v7-8-27]]

^<<v7-8-27,27>>^ Com esse ouro, Gideão fez um colete sacerdotal e o colocou em Ofra, sua cidade. Todo o Israel, porém, se prostituiu, fazendo do colete objeto de adoração, e ele se tornou uma armadilha para Gideão e sua família.

[[v7-8-28]]

^<<v7-8-28,28>>^ Esse é o relato de como os israelitas derrotaram Midiã, que nunca se recuperou. Durante quarenta anos do restante da vida de Gideão, houve paz na terra.

[[v7-8-29]]

^<<v7-8-29,29>>^ Então Gideão, filho de Joás, voltou para casa.

[[v7-8-30]]

^<<v7-8-30,30>>^ Gerou setenta filhos do sexo masculino, pois teve muitas esposas.

[[v7-8-31]]

^<<v7-8-31,31>>^ Também teve uma concubina em Siquém que deu à luz um filho seu, a quem ele chamou Abimeleque.

[[v7-8-32]]

^<<v7-8-32,32>>^ Gideão, filho de Joás, morreu quando era muito idoso e foi sepultado no túmulo de seu pai, Joás, em Ofra, no território do clã de Abiezer.

[[v7-8-33]]

^<<v7-8-33,33>>^ Logo depois da morte de Gideão, os israelitas se prostituíram, adorando imagens de Baal e fazendo de Baal-Berite seu deus.

[[v7-8-34]]

^<<v7-8-34,34>>^ Os israelitas se esqueceram do SENHOR, seu Deus, que os havia livrado de todos os inimigos em redor.

[[v7-8-35]]

^<<v7-8-35,35>>^ Também não demonstraram lealdade alguma para com a família de Jerubaal (isto é, Gideão), apesar de todo o bem que ele havia feito a Israel.

'''

xref:007-juizes/007-juizes-007.adoc#v7-7-0[&#60; Capítulo Anterior] | <<v7-8-0,Topo>> | xref:007-juizes/007-juizes-009.adoc#v7-9-0[Próximo Capítulo &#62;]