include::./index.adoc[]

[[v7-7-0]]
=== Juízes, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v7-7-1]]

^<<v7-7-1,1>>^ Jerubaal (isto é, Gideão) e todo o seu exército se levantaram de madrugada e acamparam junto à fonte de Harode. Os exércitos de Midiã estavam acampados ao norte deles, no vale perto da colina de Moré.

[[v7-7-2]]

^<<v7-7-2,2>>^ O SENHOR disse a Gideão: "Você tem guerreiros demais. Se eu deixar todos vocês lutarem contra os midianitas, Israel se vangloriará diante de mim, dizendo que se libertou por sua própria força.

[[v7-7-3]]

^<<v7-7-3,3>>^ Portanto, diga ao povo: ‘Quem estiver com medo e assustado pode deixar este monte e voltar para casa’". Vinte e dois mil homens voltaram para casa, restando apenas dez mil.

[[v7-7-4]]

^<<v7-7-4,4>>^ O SENHOR, porém, disse a Gideão: "Seu exército ainda está grande demais. Desça com eles até a fonte, e eu os provarei para determinar quem irá com você e quem não irá".

[[v7-7-5]]

^<<v7-7-5,5>>^ Quando Gideão desceu com os guerreiros até a fonte, o SENHOR lhe disse: "Separe os homens em dois grupos. Num grupo, coloque todos que bebem água das mãos, lambendo-a como fazem os cães. No outro grupo, coloque todos que se ajoelham e põem a boca na água para beber".

[[v7-7-6]]

^<<v7-7-6,6>>^ Apenas trezentos homens beberam água das mãos; os demais se ajoelharam e puseram a boca na água.

[[v7-7-7]]

^<<v7-7-7,7>>^ O SENHOR disse a Gideão: "Com estes trezentos homens eu livrarei Israel e entregarei os midianitas em suas mãos. Mande para casa os demais".

[[v7-7-8]]

^<<v7-7-8,8>>^ Gideão ordenou que recolhessem as provisões e as trombetas de chifre de carneiro dos outros guerreiros e os mandou para casa, mas manteve consigo os trezentos homens. O acampamento midianita ficava à frente de Gideão, descendo o vale.

[[v7-7-9]]

^<<v7-7-9,9>>^ Naquela noite, o SENHOR lhe disse: "Levante-se! Desça ao acampamento dos midianitas, pois eu os entreguei em suas mãos!

[[v7-7-10]]

^<<v7-7-10,10>>^ Mas, se você tem medo de atacá-los, desça até o acampamento com seu servo Purá.

[[v7-7-11]]

^<<v7-7-11,11>>^ Ouça o que os midianitas estão dizendo e você se encherá de coragem e terá ânimo para atacar". Então Gideão e seu servo Purá desceram até os limites do acampamento inimigo.

[[v7-7-12]]

^<<v7-7-12,12>>^ Os exércitos de Midiã, de Amaleque e dos povos do leste cobriam o vale como uma nuvem de gafanhotos. Seus camelos eram tão numerosos como os grãos de areia da praia, impossíveis de contar.

[[v7-7-13]]

^<<v7-7-13,13>>^ Gideão se aproximou no exato momento em que um homem contava um sonho a seu amigo. O homem disse: "Tive um sonho, no qual um pão de cevada veio rolando para dentro do acampamento midianita; então, bateu numa tenda e ela virou, desmontando-se!".

[[v7-7-14]]

^<<v7-7-14,14>>^ O amigo respondeu: "O sonho só pode significar uma coisa: a espada de Gideão, filho de Joás, o israelita. Deus entregou todo o exército midianita nas mãos dele!".

[[v7-7-15]]

^<<v7-7-15,15>>^ Quando Gideão ouviu o sonho e sua interpretação, prostrou-se em adoração. Voltou para o acampamento de Israel e gritou: "Levantem-se! O SENHOR entregou o exército midianita em suas mãos!".

[[v7-7-16]]

^<<v7-7-16,16>>^ Em seguida, dividiu os trezentos homens em três grupos e deu a cada homem uma trombeta e um vaso de barro com uma tocha dentro.

[[v7-7-17]]

^<<v7-7-17,17>>^ "Olhem para mim", disse ele. "Quando chegarmos à beira do acampamento, façam o que eu fizer.

[[v7-7-18]]

^<<v7-7-18,18>>^ Assim que eu e todos os que estiverem comigo tocarmos nossas trombetas, toquem as suas também ao redor de todo o acampamento e gritem: ‘Pelo SENHOR e por Gideão!’"

[[v7-7-19]]

^<<v7-7-19,19>>^ Pouco depois da meia-noite e da troca da guarda inimiga, Gideão e seus cem homens chegaram aos limites do acampamento midianita. De repente, tocaram as trombetas e quebraram os vasos de barro.

[[v7-7-20]]

^<<v7-7-20,20>>^ Então os três grupos tocaram as trombetas e quebraram os vasos. Segurando a tocha na mão esquerda e a trombeta na direita, todos gritaram: "À espada, pelo SENHOR e por Gideão!".

[[v7-7-21]]

^<<v7-7-21,21>>^ Cada homem manteve sua posição ao redor do acampamento e viu todos os midianitas correrem de um lado para o outro, gritando apavorados enquanto fugiam.

[[v7-7-22]]

^<<v7-7-22,22>>^ Quando os trezentos israelitas tocaram as trombetas, o SENHOR fez os guerreiros que estavam no acampamento lutarem uns contra os outros com suas espadas. Os que sobreviveram fugiram para lugares distantes como Bete-Sita, perto de Zererá, e para a divisa de Abel-Meolá, perto de Tabate.

[[v7-7-23]]

^<<v7-7-23,23>>^ Então Gideão convocou os guerreiros de Naftali, Aser e Manassés, que se juntaram aos demais para perseguir o exército midianita.

[[v7-7-24]]

^<<v7-7-24,24>>^ Gideão também enviou mensageiros a toda a região montanhosa de Efraim, dizendo: "Desçam e ataquem os midianitas! Não permitam que eles cheguem aos pontos mais rasos de travessia do Jordão em Bete-Bara". Todos os homens de Efraim obedeceram.

[[v7-7-25]]

^<<v7-7-25,25>>^ Capturaram Orebe e Zeebe, os dois comandantes midianitas, e mataram Orebe na rocha de Orebe e Zeebe na prensa de uvas de Zeebe. Depois, continuaram a perseguir os midianitas. Por fim, levaram a cabeça de Orebe e a de Zeebe para Gideão, que estava do outro lado do Jordão.

'''

xref:007-juizes/007-juizes-006.adoc#v7-6-0[&#60; Capítulo Anterior] | <<v7-7-0,Topo>> | xref:007-juizes/007-juizes-008.adoc#v7-8-0[Próximo Capítulo &#62;]