include::./index.adoc[]

[[v7-15-0]]
=== Juízes, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v7-15-1]]

^<<v7-15-1,1>>^ Algum tempo depois, durante a colheita do trigo, Sansão levou um cabrito de presente para sua esposa. "Vou ao quarto de minha esposa para dormir com ela", disse ele. Mas o pai dela não o deixou entrar.

[[v7-15-2]]

^<<v7-15-2,2>>^ "Eu tinha certeza de que você a odiava", explicou ele. "Por isso eu a dei como esposa a seu acompanhante de casamento. Mas veja, a irmã mais nova dela é ainda mais bonita. Case-se com ela."

[[v7-15-3]]

^<<v7-15-3,3>>^ Sansão disse: "Desta vez ninguém poderá me culpar de tudo que eu fizer a vocês, filisteus".

[[v7-15-4]]

^<<v7-15-4,4>>^ Então saiu e capturou trezentas raposas. Amarrou-as em pares pela cauda e prendeu uma tocha em cada par de caudas.

[[v7-15-5]]

^<<v7-15-5,5>>^ Depois, acendeu as tochas e soltou as raposas no meio das plantações de cereais dos filisteus. Assim, queimou tudo, tanto os feixes já ceifados como o cereal que ainda seria colhido. Também destruiu os vinhedos e os olivais.

[[v7-15-6]]

^<<v7-15-6,6>>^ "Quem fez isto?", perguntaram os filisteus. E responderam: "Foi Sansão, pois seu sogro, de Timna, deu a esposa de Sansão a seu acompanhante de casamento". Então os filisteus queimaram vivos a mulher e seu pai.

[[v7-15-7]]

^<<v7-15-7,7>>^ Sansão disse aos filisteus: "Não descansarei enquanto não me vingar de vocês pelo que fizeram!".

[[v7-15-8]]

^<<v7-15-8,8>>^ Ele os atacou com grande violência e matou muitos deles. Depois, foi morar numa caverna na rocha de Etã.

[[v7-15-9]]

^<<v7-15-9,9>>^ Então os filisteus acamparam em Judá e se espalharam pelos arredores da cidade de Leí.

[[v7-15-10]]

^<<v7-15-10,10>>^ Os homens de Judá perguntaram aos filisteus: "Por que vieram nos atacar?". Os filisteus responderam: "Viemos capturar Sansão e nos vingar dele".

[[v7-15-11]]

^<<v7-15-11,11>>^ Então três mil homens de Judá desceram para buscar Sansão na caverna da rocha de Etã. "Você não sabe que os filisteus nos dominam?", disseram a Sansão. "O que você está fazendo conosco?" Sansão respondeu: "Só fiz a eles o que fizeram a mim".

[[v7-15-12]]

^<<v7-15-12,12>>^ Mas os homens de Judá lhe disseram: "Viemos amarrá-lo e entregá-lo aos filisteus". "Está bem", disse Sansão. "Mas prometam que vocês mesmos não me farão mal."

[[v7-15-13]]

^<<v7-15-13,13>>^ "Vamos apenas amarrá-lo e entregá-lo aos filisteus", responderam eles. "Não vamos matá-lo." Então o amarraram com duas cordas novas e o fizeram sair da rocha.

[[v7-15-14]]

^<<v7-15-14,14>>^ Quando Sansão chegou a Leí, os filisteus vieram ao seu encontro, dando gritos de vitória. Mas o Espírito do SENHOR veio com poder sobre Sansão, e ele rompeu as cordas em seus braços como se fossem barbantes de linho queimados, e as amarras caíram de suas mãos.

[[v7-15-15]]

^<<v7-15-15,15>>^ Sansão encontrou a queixada de um jumento que tinha sido morto havia pouco tempo. Ele a pegou e a usou para matar mil filisteus.

[[v7-15-16]]

^<<v7-15-16,16>>^ Então disse: "Com uma queixada de jumento, fiz deles montões! Com uma queixada de jumento, matei mil homens!".

[[v7-15-17]]

^<<v7-15-17,17>>^ Quando acabou de celebrar sua vitória, jogou fora a queixada; e aquele lugar foi chamado de Ramate-Leí.

[[v7-15-18]]

^<<v7-15-18,18>>^ Sansão sentiu muita sede e clamou ao SENHOR: "Por meio da força de teu servo, concedeste este grande livramento. Acaso devo morrer de sede e cair nas mãos desses incircuncisos?".

[[v7-15-19]]

^<<v7-15-19,19>>^ Então Deus fez jorrar água de um buraco no chão em Leí. Sansão bebeu e se reanimou. Chamou aquele lugar de En-Hacoré, que existe em Leí até hoje.

[[v7-15-20]]

^<<v7-15-20,20>>^ Sansão julgou Israel durante vinte anos, no período em que os filisteus dominavam a terra.

'''

xref:007-juizes/007-juizes-014.adoc#v7-14-0[&#60; Capítulo Anterior] | <<v7-15-0,Topo>> | xref:007-juizes/007-juizes-016.adoc#v7-16-0[Próximo Capítulo &#62;]