include::./index.adoc[]

[[v7-5-0]]
=== Juízes, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v7-5-1]]

^<<v7-5-1,1>>^ Naquele dia, Débora e Baraque, filho de Abinoão, entoaram este cântico:

[[v7-5-2]]

^<<v7-5-2,2>>^ "Os líderes de Israel assumiram o comando, e o povo os seguiu de boa vontade. Louvem a SENHOR!

[[v7-5-3]]

^<<v7-5-3,3>>^ "Ouçam, reis! Prestem atenção, governantes! Pois eu cantarei ao SENHOR; sim, tocarei música para o SENHOR, o Deus de Israel!

[[v7-5-4]]

^<<v7-5-4,4>>^ " SENHOR, quando saíste de Seir e marchaste desde os campos de Edom, a terra tremeu, e as nuvens do céu despejaram chuva.

[[v7-5-5]]

^<<v7-5-5,5>>^ Os montes estremeceram na presença do SENHOR, o Deus do monte Sinai, na presença do SENHOR, o Deus de Israel.

[[v7-5-6]]

^<<v7-5-6,6>>^ "Nos dias de Sangar, filho de Anate, e nos dias de Jael, ninguém passava pelas estradas, e os viajantes tomavam caminhos tortuosos.

[[v7-5-7]]

^<<v7-5-7,7>>^ Restavam poucos nos povoados de Israel, até que Débora se levantou como mãe para Israel.

[[v7-5-8]]

^<<v7-5-8,8>>^ Quando Israel escolheu novos deuses, a guerra chegou às portas das cidades. Mas não se via um só escudo ou lança, entre quarenta mil guerreiros de Israel.

[[v7-5-9]]

^<<v7-5-9,9>>^ Meu coração está com os comandantes de Israel, com aqueles que se ofereceram para lutar. Louvem o SENHOR!

[[v7-5-10]]

^<<v7-5-10,10>>^ "Considerem estas coisas, vocês que montam em jumentas brancas, que se sentam em finas mantas, vocês que caminham pela estrada.

[[v7-5-11]]

^<<v7-5-11,11>>^ Ouçam os músicos dos povoados, reunidos junto aos bebedouros. Ali relatam as justas vitórias do SENHOR, as justas vitórias de seus camponeses em Israel. Então o povo do Senhor desceu às portas da cidade.

[[v7-5-12]]

^<<v7-5-12,12>>^ "Desperte, Débora, desperte! Desperte, desperte e entoe um cântico! Levante-se, Baraque! Leve embora seus cativos, filho de Abinoão!

[[v7-5-13]]

^<<v7-5-13,13>>^ "Então os sobreviventes desceram contra os poderosos; o povo do SENHOR marchou por mim contra os guerreiros.

[[v7-5-14]]

^<<v7-5-14,14>>^ Desceram de Efraim, terra que antes pertencia aos amalequitas; seguiram você, Benjamim, com seus soldados. De Maquir, desceram os comandantes; de Zebulom, os que levam a vara de comando.

[[v7-5-15]]

^<<v7-5-15,15>>^ Os príncipes de Issacar estavam com Débora e Baraque; sob suas ordens, desceram ao vale. Mas, na tribo de Rúben, houve grande indecisão.

[[v7-5-16]]

^<<v7-5-16,16>>^ Por que ficaram entre os currais, ouvindo os pastores assobiarem para seus rebanhos? Sim, na tribo de Rúben houve grande indecisão.

[[v7-5-17]]

^<<v7-5-17,17>>^ Gileade continuou a leste do Jordão, e por que Dã ficou junto aos navios? Aser sentou-se inerte na praia e permaneceu em seus portos.

[[v7-5-18]]

^<<v7-5-18,18>>^ Mas Zebulom arriscou a vida, assim como fez Naftali, nas regiões altas do campo.

[[v7-5-19]]

^<<v7-5-19,19>>^ "Os reis de Canaã vieram e lutaram em Taanaque, perto das águas de Megido, mas não levaram despojos de prata.

[[v7-5-20]]

^<<v7-5-20,20>>^ Desde o céu as estrelas lutaram; as estrelas, em suas órbitas, lutaram contra Sísera.

[[v7-5-21]]

^<<v7-5-21,21>>^ O rio Quisom os arrastou, o antigo ribeiro, o Quisom; que eu marche adiante com coragem!

[[v7-5-22]]

^<<v7-5-22,22>>^ Os cascos dos cavalos martelavam o chão; galopavam, galopavam seus poderosos cavalos de guerra.

[[v7-5-23]]

^<<v7-5-23,23>>^ ‘Amaldiçoem os habitantes de Meroz’, disse o anjo do SENHOR. ‘Amaldiçoem duramente, pois não vieram ajudar o SENHOR, ajudar o SENHOR contra fortes guerreiros.’

[[v7-5-24]]

^<<v7-5-24,24>>^ "Jael, esposa de Héber, o queneu, é a mais abençoada entre as mulheres. Que ela seja a mais abençoada das mulheres que vivem em tendas!

[[v7-5-25]]

^<<v7-5-25,25>>^ Sísera lhe pediu água, e ela lhe deu leite. Numa vasilha digna dos nobres, trouxe-lhe coalhada.

[[v7-5-26]]

^<<v7-5-26,26>>^ Com a mão esquerda, pegou uma estaca de tenda; com a direita, o martelo de trabalhador. Com eles atacou Sísera e esmagou sua cabeça; de um só golpe, rachou e atravessou seu crânio.

[[v7-5-27]]

^<<v7-5-27,27>>^ Ele se curvou, caiu e ali ficou, estirado aos pés de Jael. E, no lugar onde se curvou, ali caiu e morreu.

[[v7-5-28]]

^<<v7-5-28,28>>^ "Da janela, a mãe de Sísera olhava para fora; atrás da treliça da janela, clamava: ‘Por que seu carro de guerra demora tanto? Por que não se ouve o som de suas carruagens?’.

[[v7-5-29]]

^<<v7-5-29,29>>^ "Suas acompanhantes mais sábias respondiam, e ela repetia estas palavras a si mesma:

[[v7-5-30]]

^<<v7-5-30,30>>^ ‘Devem estar repartindo os despojos que tomaram; uma ou duas moças para cada homem. Haverá túnicas coloridas para Sísera, túnicas coloridas e bordadas. Sem dúvida, no despojo haverá túnicas coloridas e bordadas dos dois lados’.

[[v7-5-31]]

^<<v7-5-31,31>>^ " SENHOR, que todos os teus inimigos assim sejam destruídos! Mas, aqueles que te amam, que se levantem como o sol com toda a sua força!". Então houve paz na terra durante quarenta anos.

'''

xref:007-juizes/007-juizes-004.adoc#v7-4-0[&#60; Capítulo Anterior] | <<v7-5-0,Topo>> | xref:007-juizes/007-juizes-006.adoc#v7-6-0[Próximo Capítulo &#62;]