include::./index.adoc[]

[[v7-6-0]]
=== Juízes, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v7-6-1]]

^<<v7-6-1,1>>^ Os israelitas fizeram o que era mau aos olhos do SENHOR. Por isso, o SENHOR os entregou nas mãos dos midianitas durante sete anos.

[[v7-6-2]]

^<<v7-6-2,2>>^ Os midianitas eram tão cruéis que os israelitas fizeram para si esconderijos nas montanhas, nas cavernas e nas fortalezas.

[[v7-6-3]]

^<<v7-6-3,3>>^ Sempre que os israelitas faziam o plantio, saqueadores de Midiã, de Amaleque e de outros povos do leste atacavam Israel,

[[v7-6-4]]

^<<v7-6-4,4>>^ acampavam na terra e destruíam as plantações até Gaza. Levavam ovelhas, bois e jumentos, e não deixavam coisa alguma para Israel comer.

[[v7-6-5]]

^<<v7-6-5,5>>^ Esses bandos inimigos, que vinham com seus rebanhos e tendas, eram como uma praga de gafanhotos. Chegavam em camelos, tão numerosos que era impossível contá-los, e só partiam quando a terra estava devastada.

[[v7-6-6]]

^<<v7-6-6,6>>^ Os midianitas reduziram Israel à mais absoluta pobreza, e o povo pediu socorro ao SENHOR.

[[v7-6-7]]

^<<v7-6-7,7>>^ Quando os israelitas clamaram ao SENHOR por causa de Midiã,

[[v7-6-8]]

^<<v7-6-8,8>>^ o SENHOR lhes enviou um profeta, que disse: "Assim diz o SENHOR, Deus de Israel: Eu os tirei da escravidão no Egito.

[[v7-6-9]]

^<<v7-6-9,9>>^ Eu os livrei dos egípcios e de todos que os oprimiam. Expulsei seus inimigos e dei a vocês a terra deles.

[[v7-6-10]]

^<<v7-6-10,10>>^ Disse a vocês: ‘Eu sou o SENHOR, seu Deus. Não adorem os deuses dos amorreus, em cujas terras agora vivem’. Mas vocês não me deram ouvidos".

[[v7-6-11]]

^<<v7-6-11,11>>^ Então o anjo do SENHOR veio e sentou-se debaixo do grande carvalho em Ofra que pertencia a Joás, do clã de Abiezer. Gideão, filho de Joás, estava debulhando trigo no fundo de uma prensa de uvas, a fim de não ser descoberto pelos midianitas.

[[v7-6-12]]

^<<v7-6-12,12>>^ O anjo do SENHOR apareceu a Gideão e disse: "O SENHOR está com você, guerreiro corajoso!".

[[v7-6-13]]

^<<v7-6-13,13>>^ Gideão respondeu: "Meu senhor, se o SENHOR está conosco, por que nos aconteceu tudo isso? E onde estão os milagres de que nossos antepassados nos falaram? Acaso não disseram: ‘O SENHOR nos tirou do Egito’? Agora, porém, o SENHOR nos abandonou e nos entregou nas mãos dos midianitas!".

[[v7-6-14]]

^<<v7-6-14,14>>^ Então o SENHOR se voltou para ele e disse: "Vá com a força que você tem e liberte Israel dos midianitas. Sou eu quem o envia!".

[[v7-6-15]]

^<<v7-6-15,15>>^ "Mas, Senhor, como posso libertar Israel?", perguntou Gideão. "Meu clã é o mais fraco de toda a tribo de Manassés, e eu sou o menos importante de minha família!"

[[v7-6-16]]

^<<v7-6-16,16>>^ "Certamente estarei com você", disse o SENHOR. "E você destruirá os midianitas como se estivesse lutando contra um só homem."

[[v7-6-17]]

^<<v7-6-17,17>>^ Gideão respondeu: "Se, de fato, posso contar com tua ajuda, dá-me um sinal de que é mesmo o SENHOR quem fala comigo.

[[v7-6-18]]

^<<v7-6-18,18>>^ Por favor, não vás embora até que eu te traga a minha oferta". Ele respondeu: "Ficarei aqui até você voltar".

[[v7-6-19]]

^<<v7-6-19,19>>^ Gideão foi depressa para casa. Cozinhou um cabrito e, com cerca de vinte litros de farinha, preparou pães sem fermento. Depois, colocou a carne num cesto e o caldo numa panela, os levou para fora e os ofereceu ao anjo que estava debaixo da grande árvore.

[[v7-6-20]]

^<<v7-6-20,20>>^ O anjo de Deus lhe disse: "Coloque a carne e os pães sem fermento sobre esta pedra e derrame neles o caldo". Gideão obedeceu.

[[v7-6-21]]

^<<v7-6-21,21>>^ Então o anjo do SENHOR tocou na carne e nos pães com a ponta da vara que estava em sua mão, e fogo subiu da pedra e consumiu tudo que Gideão havia trazido. E o anjo do SENHOR desapareceu.

[[v7-6-22]]

^<<v7-6-22,22>>^ Quando Gideão percebeu que era o anjo do SENHOR, exclamou: "Ó Soberano SENHOR, estou perdido! Vi o anjo do SENHOR face a face!".

[[v7-6-23]]

^<<v7-6-23,23>>^ "Fique em paz", respondeu o SENHOR. "Não tenha medo; você não morrerá."

[[v7-6-24]]

^<<v7-6-24,24>>^ Então Gideão construiu um altar para o SENHOR naquele local e o chamou de Javé-Shalom. Até hoje o altar está em Ofra, no território do clã de Abiezer.

[[v7-6-25]]

^<<v7-6-25,25>>^ Naquela noite, o SENHOR disse a Gideão: "Tome o segundo touro do rebanho de seu pai, aquele de sete anos. Derrube o altar que seu pai fez para Baal e corte o poste de Aserá que fica ao lado do altar.

[[v7-6-26]]

^<<v7-6-26,26>>^ Depois, construa um altar para o SENHOR, seu Deus, no alto desta colina, arrumando as pedras com cuidado. Sacrifique o touro sobre o altar como holocausto e use como lenha a madeira do poste de Aserá que você cortará".

[[v7-6-27]]

^<<v7-6-27,27>>^ Gideão levou dez de seus servos e fez o que o SENHOR mandou. Porém, fez tudo de noite, com medo de sua família e do povo da cidade.

[[v7-6-28]]

^<<v7-6-28,28>>^ Logo cedo no dia seguinte, quando os habitantes da cidade começaram a despertar, alguém descobriu que o altar de Baal havia sido derrubado e que o poste de Aserá ao lado dele tinha sido cortado. Em seu lugar, havia um novo altar, sobre o qual estavam os restos do touro sacrificado.

[[v7-6-29]]

^<<v7-6-29,29>>^ Os habitantes perguntaram uns aos outros: "Quem fez isso?". Depois de uma investigação cuidadosa, descobriram que tinha sido Gideão, filho de Joás.

[[v7-6-30]]

^<<v7-6-30,30>>^ "Traga seu filho para fora", os homens da cidade exigiram de Joás. "Ele deve morrer, pois derrubou o altar de Baal e cortou o poste de Aserá!"

[[v7-6-31]]

^<<v7-6-31,31>>^ Joás, porém, gritou para a multidão que o confrontava: "Por que vocês defendem Baal? Acaso pretendem salvá-lo? Quem lutar pela causa dele será morto pela manhã! Se Baal é realmente um deus, que ele próprio se defenda e destrua quem derrubou seu altar!".

[[v7-6-32]]

^<<v7-6-32,32>>^ Dali em diante, Gideão foi chamado de Jerubaal (isto é, "Que Baal lute com ele"), pois derrubou o altar de Baal.

[[v7-6-33]]

^<<v7-6-33,33>>^ Pouco tempo depois, os exércitos de Midiã, de Amaleque e de outros povos do leste se uniram. Eles atravessaram o Jordão e acamparam no vale de Jezreel.

[[v7-6-34]]

^<<v7-6-34,34>>^ Então o Espírito do SENHOR veio sobre Gideão, que tocou a trombeta de chifre de carneiro, convocando para a batalha, e os homens do clã de Abiezer o seguiram.

[[v7-6-35]]

^<<v7-6-35,35>>^ Também enviou mensageiros às tribos de Manassés, Aser, Zebulom e Naftali, convocando seus guerreiros, e todos atenderam ao chamado.

[[v7-6-36]]

^<<v7-6-36,36>>^ Então Gideão disse a Deus: "Se de fato vais me usar para salvar Israel, como prometeste,

[[v7-6-37]]

^<<v7-6-37,37>>^ dá-me uma prova da seguinte forma. Hoje à noite, deixarei um pouco de lã na eira, onde se peneiram os grãos. Se pela manhã a lã estiver molhada de orvalho, mas o chão estiver seco, saberei que vais me ajudar a salvar Israel, como prometeste".

[[v7-6-38]]

^<<v7-6-38,38>>^ E foi exatamente o que aconteceu. Na manhã seguinte, bem cedo, Gideão se levantou, espremeu a lã e recolheu uma tigela cheia de água.

[[v7-6-39]]

^<<v7-6-39,39>>^ Então Gideão disse a Deus: "Peço que não fiques irado comigo, mas que me permitas fazer mais um pedido. Deixa-me usar esta lã para mais uma prova. Desta vez, que a lã fique seca e o chão ao redor dela fique coberto de orvalho".

[[v7-6-40]]

^<<v7-6-40,40>>^ Naquela noite, Deus fez o que Gideão havia pedido. Pela manhã, a lã estava seca, mas o chão estava coberto de orvalho.

'''

xref:007-juizes/007-juizes-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-juizes/007-juizes-007.adoc#v7-7-0[Próximo Capítulo &#62;]