include::./index.adoc[]

[[v7-12-0]]
=== Juízes, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v7-12-1]]

^<<v7-12-1,1>>^ Então os homens de Efraim mobilizaram um exército e atravessaram o Jordão para Zafom. Enviaram a seguinte mensagem a Jefté: "Por que você não pediu nossa ajuda para lutar contra os amonitas? Vamos queimar sua casa, com você dentro!".

[[v7-12-2]]

^<<v7-12-2,2>>^ Jefté respondeu: "Eu os convoquei no início do conflito, mas vocês se recusaram a vir! Não nos ajudaram na luta contra Amom.

[[v7-12-3]]

^<<v7-12-3,3>>^ Por isso, quando vi que vocês não viriam, arrisquei a vida e saí para a batalha sem vocês, e o SENHOR entregou os amonitas em minhas mãos. Por que agora vocês vêm lutar contra mim?".

[[v7-12-4]]

^<<v7-12-4,4>>^ Os homens de Efraim responderam: "Vocês, de Gileade, não passam de fugitivos de Efraim e Manassés". Então Jefté reuniu todos os guerreiros de Gileade, atacou os homens de Efraim e os derrotou.

[[v7-12-5]]

^<<v7-12-5,5>>^ Os homens de Gileade tomaram os pontos mais rasos de travessia do Jordão, e sempre que um fugitivo de Efraim tentava voltar para a outra margem, eles o confrontavam. "Você pertence à tribo de Efraim?", perguntavam. Se o homem negasse,

[[v7-12-6]]

^<<v7-12-6,6>>^ eles o mandavam dizer "Chibolete". Se ele era de Efraim, dizia "Sibolete", pois o povo de Efraim não consegue pronunciar essa palavra corretamente. Então eles o capturavam e o matavam no lugar de travessia do Jordão. Ao todo, foram mortos 42 mil homens de Efraim naquela ocasião.

[[v7-12-7]]

^<<v7-12-7,7>>^ Jefté julgou Israel durante seis anos. Quando morreu, foi sepultado numa das cidades de Gileade.

[[v7-12-8]]

^<<v7-12-8,8>>^ Depois que Jefté morreu, Ibsã, de Belém, julgou Israel.

[[v7-12-9]]

^<<v7-12-9,9>>^ Ele teve trinta filhos e trinta filhas. Deu suas filhas em casamento a homens de fora de seu clã, e trouxe trinta moças de fora de seu clã para se casarem com seus filhos. Ibsã julgou Israel durante sete anos.

[[v7-12-10]]

^<<v7-12-10,10>>^ Quando morreu, foi sepultado em Belém.

[[v7-12-11]]

^<<v7-12-11,11>>^ Depois que Ibsã morreu, Elom, da tribo de Zebulom, julgou Israel durante dez anos.

[[v7-12-12]]

^<<v7-12-12,12>>^ Quando morreu, foi sepultado em Aijalom, no território de Zebulom.

[[v7-12-13]]

^<<v7-12-13,13>>^ Depois que Elom morreu, Abdom, filho de Hilel, de Piratom, julgou Israel.

[[v7-12-14]]

^<<v7-12-14,14>>^ Ele teve quarenta filhos e trinta netos que montavam setenta jumentos. Abdom julgou Israel durante oito anos.

[[v7-12-15]]

^<<v7-12-15,15>>^ Quando morreu, foi sepultado em Piratom, no território de Efraim, na região montanhosa dos amalequitas.

'''

xref:007-juizes/007-juizes-011.adoc#v7-11-0[&#60; Capítulo Anterior] | <<v7-12-0,Topo>> | xref:007-juizes/007-juizes-013.adoc#v7-13-0[Próximo Capítulo &#62;]