include::./index.adoc[]

[[v7-1-0]]
=== Juízes, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v7-1-1]]

^<<v7-1-1,1>>^ Depois da morte de Josué, os israelitas perguntaram ao SENHOR: "Qual das tribos deve ser a primeira a atacar os cananeus?".

[[v7-1-2]]

^<<v7-1-2,2>>^ O SENHOR respondeu: "Judá, pois eu entreguei a terra em suas mãos".

[[v7-1-3]]

^<<v7-1-3,3>>^ Os homens de Judá disseram a seus parentes da tribo de Simeão: "Venham conosco lutar contra os cananeus que vivem no território que nos foi designado como herança. Depois ajudaremos vocês a conquistar o seu território". Os homens de Simeão foram com Judá.

[[v7-1-4]]

^<<v7-1-4,4>>^ Quando os homens de Judá atacaram, o SENHOR entregou os cananeus e os ferezeus em suas mãos, e eles mataram dez mil guerreiros inimigos em Bezeque.

[[v7-1-5]]

^<<v7-1-5,5>>^ Naquela cidade, encontraram o rei Adoni-Bezeque, lutaram contra ele e derrotaram os cananeus e os ferezeus.

[[v7-1-6]]

^<<v7-1-6,6>>^ Adoni-Bezeque fugiu, mas os israelitas o capturaram e cortaram os polegares de suas mãos e de seus pés.

[[v7-1-7]]

^<<v7-1-7,7>>^ Adoni-Bezeque disse: "Setenta reis com os polegares das mãos e dos pés cortados comiam migalhas debaixo de minha mesa. Agora Deus me retribuiu aquilo que fiz com eles". E o levaram a Jerusalém, onde ele morreu.

[[v7-1-8]]

^<<v7-1-8,8>>^ Os homens de Judá atacaram Jerusalém e a conquistaram. Mataram todos os seus habitantes e puseram fogo na cidade.

[[v7-1-9]]

^<<v7-1-9,9>>^ Depois disso, desceram para lutar contra os cananeus que viviam na região montanhosa do Neguebe e nas colinas do oeste.

[[v7-1-10]]

^<<v7-1-10,10>>^ Judá marchou contra os cananeus que habitavam em Hebrom (antes chamada de Quiriate-Arba), e derrotou os exércitos de Sesai, Aimã e Talmai.

[[v7-1-11]]

^<<v7-1-11,11>>^ Dali avançaram contra os habitantes de Debir (antes chamada de Quiriate-Sefer).

[[v7-1-12]]

^<<v7-1-12,12>>^ Calebe disse: "Darei minha filha Acsa em casamento a quem atacar e tomar Quiriate-Sefer".

[[v7-1-13]]

^<<v7-1-13,13>>^ Otoniel, filho de Quenaz, irmão mais novo de Calebe, tomou a cidade, e Calebe lhe deu Acsa como esposa.

[[v7-1-14]]

^<<v7-1-14,14>>^ Quando Acsa se casou com Otoniel, ela insistiu para que ele pedisse um campo ao pai dela. Assim que ela desceu do jumento, Calebe lhe perguntou: "O que você quer?".

[[v7-1-15]]

^<<v7-1-15,15>>^ Ela respondeu: "Quero mais um presente. O senhor me deu terras no deserto do Neguebe; agora, peço que também me dê fontes de água". Então Calebe lhe deu as fontes superiores e as fontes inferiores.

[[v7-1-16]]

^<<v7-1-16,16>>^ Quando a tribo de Judá deixou Jericó, a cidade das palmeiras, os queneus, descendentes do sogro de Moisés, os acompanharam até o deserto de Judá. Eles se estabeleceram no meio do povo dali, perto da cidade de Arade, no Neguebe.

[[v7-1-17]]

^<<v7-1-17,17>>^ Então a tribo de Judá se uniu com seus parentes da tribo de Simeão para lutar contra os cananeus que habitavam em Zefate, e destruíram completamente a cidade. Por isso, agora ela se chama Hormá.

[[v7-1-18]]

^<<v7-1-18,18>>^ A tribo de Judá também conquistou as cidades de Gaza, Ascalom e Ecrom e os territórios ao redor.

[[v7-1-19]]

^<<v7-1-19,19>>^ O SENHOR estava com a tribo de Judá. Ela tomou posse da região montanhosa, mas não conseguiu expulsar os habitantes da planície, pois eles tinham carros de guerra com rodas de ferro.

[[v7-1-20]]

^<<v7-1-20,20>>^ A cidade de Hebrom foi entregue a Calebe, conforme Moisés havia prometido, e ele expulsou seus habitantes, descendentes dos três filhos de Enaque.

[[v7-1-21]]

^<<v7-1-21,21>>^ A tribo de Benjamim, porém, não conseguiu expulsar os jebuseus que moravam em Jerusalém. Por isso, até hoje os jebuseus vivem no meio do povo de Benjamim.

[[v7-1-22]]

^<<v7-1-22,22>>^ Os descendentes de José atacaram a cidade de Betel, e o SENHOR estava com eles.

[[v7-1-23]]

^<<v7-1-23,23>>^ Enviaram espiões a Betel (antes conhecida como Luz),

[[v7-1-24]]

^<<v7-1-24,24>>^ e eles abordaram um homem que saía da cidade e lhe disseram: "Mostre-nos como entrar na cidade e teremos misericórdia de você".

[[v7-1-25]]

^<<v7-1-25,25>>^ Ele mostrou a entrada, e eles mataram todos os habitantes de Betel, exceto aquele homem e sua família.

[[v7-1-26]]

^<<v7-1-26,26>>^ Mais tarde, o homem se mudou para a terra dos hititas, onde construiu uma cidade e a chamou de Luz, que é seu nome até hoje.

[[v7-1-27]]

^<<v7-1-27,27>>^ A tribo de Manassés, porém, não expulsou os habitantes de Bete-Sã, Taanaque, Dor, Ibleã e Megido, nem dos povoados ao seu redor, pois os cananeus estavam decididos a permanecer naquela região.

[[v7-1-28]]

^<<v7-1-28,28>>^ Quando Israel se fortaleceu, submeteu os cananeus a trabalhos forçados, mas não os expulsou completamente da terra.

[[v7-1-29]]

^<<v7-1-29,29>>^ A tribo de Efraim também não expulsou os habitantes de Gezer, de modo que os cananeus continuaram a viver no meio deles.

[[v7-1-30]]

^<<v7-1-30,30>>^ A tribo de Zebulom não expulsou os habitantes de Quitrom e de Naalol, de modo que os cananeus continuaram a viver no meio deles, mas foram submetidos a trabalhos forçados.

[[v7-1-31]]

^<<v7-1-31,31>>^ A tribo de Aser não expulsou os habitantes de Aco, Sidom, Alabe, Aczibe, Helba, Afeque e Reobe.

[[v7-1-32]]

^<<v7-1-32,32>>^ Estabeleceu-se no meio dos cananeus que habitavam a terra, pois não conseguiu expulsá-los.

[[v7-1-33]]

^<<v7-1-33,33>>^ Da mesma forma, a tribo de Naftali não expulsou os habitantes de Bete-Semes e de Bete-Anate. Estabeleceu-se no meio dos cananeus que habitavam a terra, mas submeteu os habitantes de Bete-Semes e de Bete-Anate a trabalhos forçados.

[[v7-1-34]]

^<<v7-1-34,34>>^ Quanto à tribo de Dã, os amorreus a obrigaram a voltar para a região montanhosa e não permitiram que descesse à planície.

[[v7-1-35]]

^<<v7-1-35,35>>^ Os amorreus estavam decididos a ficar no monte Heres, em Aijalom e em Saalbim, mas quando os descendentes de José se fortaleceram, submeteram os amorreus a trabalhos forçados.

[[v7-1-36]]

^<<v7-1-36,36>>^ A divisa dos amorreus se estendia da ladeira do Escorpião até Selá, continuando dali para cima.

'''

xref:006-josue/006-josue-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-juizes/007-juizes-002.adoc#v7-2-0[Próximo Capítulo &#62;]