include::./index.adoc[]

[[v7-2-0]]
=== Juízes, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v7-2-1]]

^<<v7-2-1,1>>^ O anjo do SENHOR subiu de Gilgal a Boquim e disse aos israelitas: "Tirei vocês do Egito e os trouxe a esta terra que jurei dar a seus antepassados, e afirmei que jamais quebraria a minha aliança com vocês.

[[v7-2-2]]

^<<v7-2-2,2>>^ De sua parte, vocês não deviam fazer aliança alguma com os habitantes desta terra, mas sim, destruir seus altares. Por que vocês desobedeceram à minha ordem?

[[v7-2-3]]

^<<v7-2-3,3>>^ Agora, portanto, declaro que não expulsarei mais os povos que habitam em sua terra. Eles serão como espinhos em suas costas, e os deuses deles serão uma armadilha para vocês".

[[v7-2-4]]

^<<v7-2-4,4>>^ Quando o anjo do SENHOR acabou de falar a todos os israelitas, o povo chorou em alta voz.

[[v7-2-5]]

^<<v7-2-5,5>>^ Por isso, chamaram aquele lugar de Boquim, e ali ofereceram sacrifícios ao SENHOR.

[[v7-2-6]]

^<<v7-2-6,6>>^ Depois que Josué se despediu do povo, cada tribo de Israel partiu para tomar posse do território que havia recebido como herança.

[[v7-2-7]]

^<<v7-2-7,7>>^ O povo serviu ao SENHOR durante toda a vida de Josué, e também dos líderes que sobreviveram depois dele e que tinham visto as grandes coisas que o SENHOR havia feito por Israel.

[[v7-2-8]]

^<<v7-2-8,8>>^ Josué, filho de Num, servo do SENHOR, morreu aos 110 anos.

[[v7-2-9]]

^<<v7-2-9,9>>^ Foi sepultado na terra que havia recebido como herança, em Timnate-Sera, na região montanhosa de Efraim, ao norte do monte Gaás.

[[v7-2-10]]

^<<v7-2-10,10>>^ Depois que aquela geração morreu e se reuniu a seus antepassados, surgiu uma nova geração que não conhecia o SENHOR nem tinha visto as grandes coisas que ele havia feito por Israel.

[[v7-2-11]]

^<<v7-2-11,11>>^ Os israelitas fizeram o que era mau aos olhos do SENHOR e serviram às imagens de Baal.

[[v7-2-12]]

^<<v7-2-12,12>>^ Abandonaram o SENHOR, o Deus de seus antepassados, que os havia tirado do Egito. Seguiram e adoraram os deuses dos povos ao redor e, com isso, provocaram a ira do SENHOR.

[[v7-2-13]]

^<<v7-2-13,13>>^ Abandonaram o SENHOR para servir a Baal e às imagens de Astarote.

[[v7-2-14]]

^<<v7-2-14,14>>^ Com isso, a ira do SENHOR ardeu contra Israel, e ele os entregou nas mãos de saqueadores que tomaram seus bens. Entregou-os aos inimigos ao seu redor, aos quais já não conseguiam resistir.

[[v7-2-15]]

^<<v7-2-15,15>>^ Toda vez que saíam para a batalha, o SENHOR lutava contra eles e provocava sua derrota, conforme lhes havia advertido com juramento. Por isso, o povo vivia em grande angústia.

[[v7-2-16]]

^<<v7-2-16,16>>^ Então o SENHOR levantou juízes para livrar o povo de seus agressores.

[[v7-2-17]]

^<<v7-2-17,17>>^ Contudo, não quiseram ouvir os juízes, mas se prostituíram, adorando outros deuses. Como se desviaram depressa do caminho de seus antepassados, que haviam andado em obediência aos mandamentos do SENHOR!

[[v7-2-18]]

^<<v7-2-18,18>>^ Sempre que o SENHOR levantava um juiz sobre os israelitas, o SENHOR estava com ele e livrava o povo de seus inimigos enquanto o juiz vivia; pois o SENHOR tinha compaixão de seu povo, que sofria sob o peso da aflição provocada por seus opressores.

[[v7-2-19]]

^<<v7-2-19,19>>^ Quando o juiz morria, porém, eles voltavam a seus caminhos corruptos e se comportavam ainda pior que seus antepassados. Seguiam outros deuses, servindo-os e adorando-os. Não abandonavam suas práticas perversas e seus caminhos teimosos.

[[v7-2-20]]

^<<v7-2-20,20>>^ Por isso, a ira do SENHOR ardeu contra Israel. Disse ele: "Uma vez que este povo violou a minha aliança, que fiz com seus antepassados, e não me deu ouvidos,

[[v7-2-21]]

^<<v7-2-21,21>>^ não expulsarei mais as nações que Josué deixou por conquistar quando morreu.

[[v7-2-22]]

^<<v7-2-22,22>>^ Fiz isso para pôr Israel à prova, para ver se seguiria os caminhos do SENHOR, como fizeram seus antepassados".

[[v7-2-23]]

^<<v7-2-23,23>>^ Assim, o SENHOR deixou aquelas nações na terra. Não as expulsou de imediato nem permitiu que Josué conquistasse todas elas.

'''

xref:007-juizes/007-juizes-001.adoc#v7-1-0[&#60; Capítulo Anterior] | <<v7-2-0,Topo>> | xref:007-juizes/007-juizes-003.adoc#v7-3-0[Próximo Capítulo &#62;]