include::./index.adoc[]

[[v7-16-0]]
=== Juízes, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v7-16-1]]

^<<v7-16-1,1>>^ Certo dia, Sansão foi à cidade filisteia de Gaza e conheceu uma prostituta, com quem passou a noite.

[[v7-16-2]]

^<<v7-16-2,2>>^ Logo correu a notícia de que Sansão estava lá, e os homens de Gaza se reuniram e esperaram a noite toda junto aos portões da cidade. Ficaram em silêncio a noite inteira, pois pensavam: "Quando o dia clarear, vamos matá-lo".

[[v7-16-3]]

^<<v7-16-3,3>>^ Mas Sansão ficou deitado só até a meia-noite. Então levantou-se, agarrou os portões da cidade, com os dois batentes, e os ergueu, junto com a tranca. Colocou-as sobre os ombros e as levou para o alto da colina que fica em frente de Hebrom.

[[v7-16-4]]

^<<v7-16-4,4>>^ Algum tempo depois, Sansão se apaixonou por uma mulher chamada Dalila, que morava no vale de Soreque.

[[v7-16-5]]

^<<v7-16-5,5>>^ Os governantes dos filisteus foram vê-la e disseram: "Seduza Sansão para que ele lhe diga o que o torna tão forte e como podemos dominá-lo e amarrá-lo sem que consiga se soltar. Então cada um de nós dará a você 1.100 peças de prata".

[[v7-16-6]]

^<<v7-16-6,6>>^ Assim, Dalila disse a Sansão: "Conte-me, por favor, o que o torna tão forte e como poderia ser amarrado sem conseguir se soltar".

[[v7-16-7]]

^<<v7-16-7,7>>^ Sansão respondeu: "Se eu fosse amarrado com sete cordas de arco novas, ainda não secas, ficaria tão fraco como qualquer outro homem".

[[v7-16-8]]

^<<v7-16-8,8>>^ Então os governantes filisteus levaram para Dalila sete cordas de arco novas, e ela amarrou Sansão.

[[v7-16-9]]

^<<v7-16-9,9>>^ Ela havia escondido alguns homens num dos quartos interiores da casa e gritou: "Sansão! Os filisteus vieram atacá-lo!". Mas Sansão arrebentou as cordas de arco de uma vez, como se rompe um pedaço de barbante queimado. E não descobriram o segredo de sua força.

[[v7-16-10]]

^<<v7-16-10,10>>^ Mais tarde, Dalila disse a Sansão: "Você zombou de mim e mentiu! Agora conte-me, por favor, como poderia ser amarrado".

[[v7-16-11]]

^<<v7-16-11,11>>^ Sansão respondeu: "Se eu fosse amarrado firmemente com cordas novas em folha, que nunca foram usadas, ficaria tão fraco como qualquer outro homem".

[[v7-16-12]]

^<<v7-16-12,12>>^ Assim, Dalila pegou cordas novas e o amarrou com elas. Os homens estavam escondidos no quarto interior como antes e, de novo, Dalila gritou: "Sansão! Os filisteus vieram atacá-lo!". Mais uma vez, porém, Sansão arrebentou as cordas em seus braços como se fossem fios.

[[v7-16-13]]

^<<v7-16-13,13>>^ Então Dalila disse: "Você zombou de mim e mentiu! Agora conte-me, por favor, como poderia ser amarrado". Sansão respondeu: "Se você tecesse as sete tranças de meu cabelo no pano de seu tear e o prendesse com o pino do tear, eu ficaria tão fraco como qualquer outro homem". Enquanto Sansão dormia, Dalila teceu as sete tranças do cabelo dele no pano.

[[v7-16-14]]

^<<v7-16-14,14>>^ Depois, prendeu-o com o pino do tear. De novo, ela gritou: "Sansão! Os filisteus vieram atacá-lo!". Mas Sansão acordou e soltou, de uma vez, o cabelo do tear e do pano.

[[v7-16-15]]

^<<v7-16-15,15>>^ Então Dalila disse: "Como você pode dizer que me ama, se não me conta seus segredos? Zombou de mim três vezes e ainda não me disse o que o torna tão forte!".

[[v7-16-16]]

^<<v7-16-16,16>>^ Todos os dias ela o atormentava com sua importunação, até ele não suportar mais.

[[v7-16-17]]

^<<v7-16-17,17>>^ Por fim, contou-lhe seu segredo: "Meu cabelo nunca foi cortado, pois fui consagrado a Deus como nazireu desde o nascimento. Se minha cabeça fosse raspada, eu perderia as forças e ficaria tão fraco como qualquer outro homem".

[[v7-16-18]]

^<<v7-16-18,18>>^ Dalila percebeu que, finalmente, Sansão havia lhe contado a verdade e mandou chamar os governantes filisteus. "Venham mais uma vez!", disse ela. "Sansão finalmente me contou seu segredo." Os governantes foram ao encontro dela e lhe deram o dinheiro.

[[v7-16-19]]

^<<v7-16-19,19>>^ Dalila fez Sansão dormir com a cabeça em seu colo e então chamou um homem para cortar as sete tranças do cabelo dele. Desse modo, começou a enfraquecê-lo, e suas forças o deixaram.

[[v7-16-20]]

^<<v7-16-20,20>>^ Então ela gritou: "Sansão! Os filisteus vieram atacá-lo!". Ao acordar, ele pensou: "Farei como das outras vezes e me livrarei deles". Não sabia, porém, que o SENHOR o havia deixado.

[[v7-16-21]]

^<<v7-16-21,21>>^ Os filisteus o capturaram e furaram seus olhos. Levaram-no para Gaza, onde o prenderam com duas correntes de bronze, obrigando-o a moer cereais na prisão.

[[v7-16-22]]

^<<v7-16-22,22>>^ Não demorou muito, porém, e seu cabelo começou a crescer de novo.

[[v7-16-23]]

^<<v7-16-23,23>>^ Os governantes filisteus realizaram uma grande festa, na qual ofereceram sacrifícios e louvaram seu deus, Dagom. "Nosso deus nos deu a vitória sobre nosso inimigo Sansão!", diziam eles.

[[v7-16-24]]

^<<v7-16-24,24>>^ Ao ver Sansão, o povo louvou o seu deus. "Nosso deus nos entregou nosso inimigo!", diziam. "Aquele que destruía a nossa terra e matou muitos de nós agora está em nosso poder!"

[[v7-16-25]]

^<<v7-16-25,25>>^ A essa altura, já estavam muito bêbados e começaram a gritar: "Tragam Sansão para que nos divirta!". Assim, trouxeram Sansão da prisão para diverti-los e o fizeram ficar em pé entre as duas colunas que sustentavam o teto.

[[v7-16-26]]

^<<v7-16-26,26>>^ Sansão disse ao jovem servo que o guiava pela mão: "Ponha minhas mãos nas duas colunas que sustentam o templo. Quero me apoiar nelas".

[[v7-16-27]]

^<<v7-16-27,27>>^ O templo estava lotado. Todos os governantes filisteus estavam presentes, e havia cerca de três mil homens e mulheres na cobertura vendo Sansão e se divertindo às custas dele.

[[v7-16-28]]

^<<v7-16-28,28>>^ Então Sansão orou ao SENHOR: "Soberano SENHOR, lembra-te de mim novamente. Por favor, ó Deus, fortalece-me só mais esta vez. Permite que, com um só golpe, eu me vingue dos filisteus pela perda de meus dois olhos".

[[v7-16-29]]

^<<v7-16-29,29>>^ Então Sansão se apoiou nas colunas centrais que sustentavam o templo, empurrou-as com as duas mãos

[[v7-16-30]]

^<<v7-16-30,30>>^ e exclamou: "Que eu morra com os filisteus!". E o templo desabou sobre os governantes filisteus e sobre todo o povo. Assim, Sansão matou mais pessoas quando morreu do que em toda a sua vida.

[[v7-16-31]]

^<<v7-16-31,31>>^ Mais tarde, seus irmãos e outros parentes desceram para buscar o corpo. Eles o levaram de volta para casa e o sepultaram entre Zorá e Estaol, onde seu pai, Manoá, estava enterrado. Sansão julgou Israel durante vinte anos.

'''

xref:007-juizes/007-juizes-015.adoc#v7-15-0[&#60; Capítulo Anterior] | <<v7-16-0,Topo>> | xref:007-juizes/007-juizes-017.adoc#v7-17-0[Próximo Capítulo &#62;]