include::./index.adoc[]

[[v7-13-0]]
=== Juízes, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v7-13-1]]

^<<v7-13-1,1>>^ Mais uma vez, os israelitas fizeram o que era mau aos olhos do SENHOR. Por isso, o SENHOR os entregou nas mãos dos filisteus, que os oprimiram durante quarenta anos.

[[v7-13-2]]

^<<v7-13-2,2>>^ Naqueles dias, um homem chamado Manoá, da tribo de Dã, vivia na cidade de Zorá. Sua esposa era estéril, e eles não tinham filhos.

[[v7-13-3]]

^<<v7-13-3,3>>^ O anjo do SENHOR apareceu à esposa de Manoá e disse: "Embora você não tenha conseguido ter filhos até agora, ficará grávida e dará à luz um filho.

[[v7-13-4]]

^<<v7-13-4,4>>^ Portanto, tenha cuidado; não beba vinho e nenhuma outra bebida fermentada, nem coma nenhum alimento que seja impuro.

[[v7-13-5]]

^<<v7-13-5,5>>^ Você ficará grávida e dará à luz um filho, do qual jamais cortará o cabelo, porque ele será consagrado a Deus como nazireu desde o nascimento. Ele começará a libertar Israel das mãos dos filisteus".

[[v7-13-6]]

^<<v7-13-6,6>>^ A mulher foi correndo contar ao marido: "Um homem de Deus apareceu para mim! Era como um dos anjos de Deus, e sua aparência era assustadora. Não perguntei de onde era, e ele não me disse seu nome.

[[v7-13-7]]

^<<v7-13-7,7>>^ Mas ele me disse: ‘Você ficará grávida e dará à luz um filho. Não beba vinho e nenhuma outra bebida fermentada, nem coma nenhum alimento que seja impuro. Seu filho será consagrado a Deus como nazireu desde o nascimento até o dia de sua morte’".

[[v7-13-8]]

^<<v7-13-8,8>>^ Então Manoá orou ao SENHOR: "Senhor, eu peço que o homem de Deus que enviaste volte e nos dê mais instruções a respeito desse filho que vai nascer".

[[v7-13-9]]

^<<v7-13-9,9>>^ Deus atendeu à oração de Manoá, e o anjo de Deus apareceu outra vez à esposa quando ela estava sentada no campo. Seu marido, Manoá, não estava com ela.

[[v7-13-10]]

^<<v7-13-10,10>>^ Então ela foi correndo contar ao marido: "O homem que apareceu outro dia está aqui de novo!".

[[v7-13-11]]

^<<v7-13-11,11>>^ Manoá voltou depressa com sua esposa e perguntou: "O senhor é o homem que falou com minha esposa outro dia?". "Sim, sou eu", respondeu ele.

[[v7-13-12]]

^<<v7-13-12,12>>^ Então Manoá perguntou: "Quando suas palavras se cumprirem, como devemos criar o menino? Qual será o trabalho dele?".

[[v7-13-13]]

^<<v7-13-13,13>>^ O anjo do SENHOR respondeu: "Sua esposa deverá seguir as instruções que lhe dei.

[[v7-13-14]]

^<<v7-13-14,14>>^ Ela não deve comer uvas nem passas, não deve beber vinho e nenhuma outra bebida fermentada, nem deve comer nenhum alimento que seja impuro. Ela deverá fazer tudo que ordenei".

[[v7-13-15]]

^<<v7-13-15,15>>^ Manoá disse ao anjo do SENHOR: "Por favor, fique aqui até prepararmos um cabrito para o senhor".

[[v7-13-16]]

^<<v7-13-16,16>>^ "Está bem, só que não comerei nada", respondeu o anjo do SENHOR. "Mas você pode preparar um holocausto como sacrifício ao SENHOR." Manoá ainda não havia percebido que era o anjo do SENHOR.

[[v7-13-17]]

^<<v7-13-17,17>>^ Manoá perguntou ao anjo do SENHOR: "Qual é seu nome? Queremos lhe prestar homenagem quando isso tudo se cumprir".

[[v7-13-18]]

^<<v7-13-18,18>>^ "Por que quer saber meu nome?", disse o anjo do SENHOR. "Ele é tão maravilhoso que você não conseguiria entender!"

[[v7-13-19]]

^<<v7-13-19,19>>^ Então Manoá tomou um cabrito e uma oferta de cereal e os apresentou sobre uma rocha como sacrifício ao SENHOR. Enquanto Manoá e sua esposa observavam, o SENHOR fez algo extraordinário.

[[v7-13-20]]

^<<v7-13-20,20>>^ Quando as chamas do altar subiram ao céu, o anjo do SENHOR subiu nas chamas. Ao verem isso, Manoá e sua esposa se curvaram com o rosto no chão.

[[v7-13-21]]

^<<v7-13-21,21>>^ O anjo do SENHOR não voltou a aparecer a Manoá e sua esposa. Então Manoá finalmente percebeu que era o anjo do Senhor

[[v7-13-22]]

^<<v7-13-22,22>>^ e disse à sua esposa: "Com certeza vamos morrer, pois vimos a Deus!".

[[v7-13-23]]

^<<v7-13-23,23>>^ Sua esposa, porém, disse: "Se o SENHOR quisesse nos matar, não teria aceitado o holocausto e a oferta de cereal. Não teria aparecido a nós, nem nos teria revelado essas coisas maravilhosas!".

[[v7-13-24]]

^<<v7-13-24,24>>^ Quando o menino nasceu, ela o chamou de Sansão. O SENHOR o abençoou enquanto ele crescia,

[[v7-13-25]]

^<<v7-13-25,25>>^ e o Espírito do SENHOR começou a agir nele quando ele morava em Maané-Dã, entre Zorá e Estaol.

'''

xref:007-juizes/007-juizes-012.adoc#v7-12-0[&#60; Capítulo Anterior] | <<v7-13-0,Topo>> | xref:007-juizes/007-juizes-014.adoc#v7-14-0[Próximo Capítulo &#62;]