include::./index.adoc[]

[[v7-14-0]]
=== Juízes, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v7-14-1]]

^<<v7-14-1,1>>^ Certo dia, Sansão estava em Timna e viu uma moça do povo filisteu.

[[v7-14-2]]

^<<v7-14-2,2>>^ Quando voltou para casa, disse a seu pai e a sua mãe: "Vi uma moça filisteia em Timna. Quero me casar com ela. Consigam aquela moça para mim".

[[v7-14-3]]

^<<v7-14-3,3>>^ Seu pai e sua mãe se opuseram: "Não há uma moça sequer em nossa tribo ou entre todo o nosso povo com quem você possa se casar? Por que tem de procurar uma esposa entre os filisteus pagãos?". Mas Sansão disse a seu pai: "Consiga a moça para mim. É ela que eu quero".

[[v7-14-4]]

^<<v7-14-4,4>>^ Seus pais não sabiam que o SENHOR estava agindo no meio disso tudo, para criar uma oportunidade de agir contra os filisteus que, na época, dominavam Israel.

[[v7-14-5]]

^<<v7-14-5,5>>^ Quando Sansão e seus pais estavam descendo a Timna, de repente um jovem leão atacou Sansão perto dos vinhedos de Timna.

[[v7-14-6]]

^<<v7-14-6,6>>^ Naquele momento, o Espírito do SENHOR veio sobre Sansão com tamanho poder que ele rasgou o animal pelas mandíbulas usando as próprias mãos, com a mesma facilidade que se despedaça um cabrito. Contudo, não contou a seus pais o que havia acontecido.

[[v7-14-7]]

^<<v7-14-7,7>>^ Quando chegou a Timna, conversou com a moça e se agradou muito dela.

[[v7-14-8]]

^<<v7-14-8,8>>^ Algum tempo depois, quando voltou a Timna para o casamento, saiu do caminho para ver o cadáver do leão. Descobriu que um enxame de abelhas havia feito mel dentro da carcaça.

[[v7-14-9]]

^<<v7-14-9,9>>^ Pegou um pouco de mel com as mãos e foi comendo pelo caminho. Também deu um pouco a seu pai e a sua mãe, e eles comeram. Mas Sansão não lhes contou que havia tirado o mel da carcaça do leão.

[[v7-14-10]]

^<<v7-14-10,10>>^ Enquanto seu pai estava em Timna para o casamento, Sansão ofereceu uma festa ali, como era costume entre os noivos.

[[v7-14-11]]

^<<v7-14-11,11>>^ Quando os pais da noiva o viram, escolheram trinta rapazes da cidade para o acompanharem na festa.

[[v7-14-12]]

^<<v7-14-12,12>>^ Sansão lhes disse: "Vou lhes propor um enigma. Se conseguirem decifrá-lo durante estes sete dias de celebração, darei a vocês trinta camisas de linho fino e trinta conjuntos de roupa.

[[v7-14-13]]

^<<v7-14-13,13>>^ Mas, se não conseguirem decifrá-lo, vocês me darão trinta camisas de linho fino e trinta conjuntos de roupa". "Está bem", concordaram eles. "Proponha seu enigma."

[[v7-14-14]]

^<<v7-14-14,14>>^ Ele disse: "Do que come veio algo para comer, do que é forte veio algo doce". Três dias depois, eles ainda tentavam encontrar a resposta.

[[v7-14-15]]

^<<v7-14-15,15>>^ No quarto dia, disseram à esposa de Sansão: "Convença seu marido a explicar o enigma; caso contrário, queimaremos vivos você e sua família! Você nos convidou à festa só para nos deixar pobres?".

[[v7-14-16]]

^<<v7-14-16,16>>^ Então a esposa de Sansão lhe disse, aos prantos: "Você não me ama! Você me odeia! Propôs um enigma ao meu povo, mas não me contou a resposta!". Ele respondeu: "Não revelei o enigma nem a meu pai e minha mãe. Por que deveria contá-lo a você?".

[[v7-14-17]]

^<<v7-14-17,17>>^ Ela chorava cada vez que estava com ele, e assim continuou até o último dia da festa. Por fim, de tanto importunar Sansão, no sétimo dia ele lhe contou a resposta. Então ela explicou o enigma aos rapazes.

[[v7-14-18]]

^<<v7-14-18,18>>^ Antes do pôr do sol do sétimo dia, os homens da cidade vieram dar a resposta a Sansão: "O que é mais doce que o mel? O que é mais forte que o leão?". Sansão respondeu: "Se vocês não tivessem arado com minha novilha, não teriam resolvido meu enigma!".

[[v7-14-19]]

^<<v7-14-19,19>>^ Então o Espírito do SENHOR veio com poder sobre Sansão. Ele desceu à cidade de Ascalom, matou trinta homens, tomou seus pertences e deu as roupas deles aos homens que haviam resolvido o enigma. Contudo, ficou furioso com o que tinha acontecido e voltou a morar na casa de seus pais.

[[v7-14-20]]

^<<v7-14-20,20>>^ A noiva de Sansão foi dada como esposa ao rapaz que o havia acompanhado na cerimônia.

'''

xref:007-juizes/007-juizes-013.adoc#v7-13-0[&#60; Capítulo Anterior] | <<v7-14-0,Topo>> | xref:007-juizes/007-juizes-015.adoc#v7-15-0[Próximo Capítulo &#62;]