include::./index.adoc[]

[[v7-10-0]]
=== Juízes, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v7-10-1]]

^<<v7-10-1,1>>^ Depois da morte de Abimeleque, Tolá, filho de Puá, filho de Dodô, foi o próximo libertador de Israel. Era da tribo de Issacar, mas morava na cidade de Samir, na região montanhosa de Efraim.

[[v7-10-2]]

^<<v7-10-2,2>>^ Julgou Israel por 23 anos. Quando morreu, foi sepultado em Samir.

[[v7-10-3]]

^<<v7-10-3,3>>^ Depois que Tolá morreu, Jair, de Gileade, julgou Israel por 22 anos.

[[v7-10-4]]

^<<v7-10-4,4>>^ Seus trinta filhos montavam trinta jumentos e possuíam na terra de Gileade trinta cidades que até hoje são chamadas de Cidades de Jair.

[[v7-10-5]]

^<<v7-10-5,5>>^ Quando morreu, foi sepultado em Camom.

[[v7-10-6]]

^<<v7-10-6,6>>^ Mais uma vez, os israelitas fizeram o que era mau aos olhos do SENHOR. Serviram às imagens de Baal e Astarote e aos deuses da Síria, de Sidom, Moabe, Amom e da Filístia. Abandonaram o SENHOR e deixaram de servi-lo.

[[v7-10-7]]

^<<v7-10-7,7>>^ Então a ira do SENHOR se acendeu contra Israel, e ele os entregou nas mãos dos filisteus e dos amonitas,

[[v7-10-8]]

^<<v7-10-8,8>>^ que começaram a oprimi-los cruelmente naquele mesmo ano. Durante dezoito anos, oprimiram todos os israelitas a leste do Jordão na terra dos amorreus (isto é, em Gileade).

[[v7-10-9]]

^<<v7-10-9,9>>^ Os amonitas também atravessaram para o lado oeste do Jordão e atacaram as tribos de Judá, Benjamim e Efraim. Os israelitas ficaram muito angustiados

[[v7-10-10]]

^<<v7-10-10,10>>^ e, por fim, pediram socorro ao SENHOR. "Pecamos contra ti", disseram, "pois abandonamos nosso Deus e servimos às imagens de Baal!"

[[v7-10-11]]

^<<v7-10-11,11>>^ O SENHOR respondeu: "Acaso não os livrei dos egípcios, dos amorreus, dos amonitas, dos filisteus,

[[v7-10-12]]

^<<v7-10-12,12>>^ dos sidônios, dos amalequitas e dos maonitas? Quando eles os oprimiram, vocês me pediram socorro, e eu os livrei.

[[v7-10-13]]

^<<v7-10-13,13>>^ E, no entanto, vocês me abandonaram e serviram a outros deuses. Por isso, não os livrarei mais.

[[v7-10-14]]

^<<v7-10-14,14>>^ Vão e clamem aos deuses que vocês escolheram! Que eles os livrem neste momento de angústia!".

[[v7-10-15]]

^<<v7-10-15,15>>^ Mas os israelitas suplicaram ao SENHOR: "Sim, pecamos! Castiga-nos como te parecer melhor, mas livra-nos hoje de nossos inimigos".

[[v7-10-16]]

^<<v7-10-16,16>>^ Então eles se desfizeram dos deuses estrangeiros e serviram ao SENHOR. E ele teve compaixão deles por causa de seu sofrimento.

[[v7-10-17]]

^<<v7-10-17,17>>^ Quando os exércitos de Amom foram convocados para guerrear e acamparam em Gileade, os israelitas se reuniram e acamparam em Mispá.

[[v7-10-18]]

^<<v7-10-18,18>>^ Os líderes de Gileade disseram uns aos outros: "O primeiro que atacar os amonitas governará todo o povo de Gileade".

'''

xref:007-juizes/007-juizes-009.adoc#v7-9-0[&#60; Capítulo Anterior] | <<v7-10-0,Topo>> | xref:007-juizes/007-juizes-011.adoc#v7-11-0[Próximo Capítulo &#62;]