include::./index.adoc[]

[[v7-21-0]]
=== Juízes, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v7-21-1]]

^<<v7-21-1,1>>^ Os israelitas haviam jurado em Mispá: "Jamais entregaremos nossas filhas em casamento a homens da tribo de Benjamim".

[[v7-21-2]]

^<<v7-21-2,2>>^ Então o povo foi a Betel e permaneceu na presença de Deus até a tarde, chorando sem parar em alta voz:

[[v7-21-3]]

^<<v7-21-3,3>>^ "Ó SENHOR, Deus de Israel, por que aconteceu isso com Israel?", diziam. "Agora está faltando uma de nossas tribos!"

[[v7-21-4]]

^<<v7-21-4,4>>^ Na manhã seguinte, bem cedo, construíram um altar e ali apresentaram holocaustos e ofertas de paz.

[[v7-21-5]]

^<<v7-21-5,5>>^ Então os israelitas disseram: "Quem dentre as tribos de Israel não participou da reunião sagrada que realizamos em Mispá, na presença do SENHOR?". Naquela ocasião, haviam feito um juramento solene na presença do SENHOR de que matariam quem se recusasse a comparecer.

[[v7-21-6]]

^<<v7-21-6,6>>^ Os israelitas tiveram pena de seu irmão Benjamim e disseram: "Hoje foi eliminada uma das tribos de Israel.

[[v7-21-7]]

^<<v7-21-7,7>>^ Como conseguiremos esposas para os poucos que restam, se juramos pelo SENHOR que não lhes daríamos nossas filhas em casamento?".

[[v7-21-8]]

^<<v7-21-8,8>>^ Então perguntaram: "Quem dentre as tribos de Israel não compareceu conosco a Mispá quando nos reunimos na presença do SENHOR?". E descobriram que ninguém de Jabes-Gileade havia participado da reunião sagrada.

[[v7-21-9]]

^<<v7-21-9,9>>^ Ao contarem o povo, verificaram que ninguém de Jabes-Gileade estava presente.

[[v7-21-10]]

^<<v7-21-10,10>>^ Então a comunidade enviou doze mil de seus melhores guerreiros a Jabes-Gileade com ordens para matar seus habitantes, incluindo mulheres e crianças.

[[v7-21-11]]

^<<v7-21-11,11>>^ "É isto que vocês devem fazer", disseram. "Destruam completamente todos os homens e também todas as mulheres que não forem virgens."

[[v7-21-12]]

^<<v7-21-12,12>>^ Entre os habitantes de Jabes-Gileade, encontraram quatrocentas moças que nunca haviam se deitado com um homem e as levaram para o acampamento em Siló, na terra de Canaã.

[[v7-21-13]]

^<<v7-21-13,13>>^ Toda a comunidade enviou uma delegação de paz aos homens restantes de Benjamim que estavam na rocha de Rimom.

[[v7-21-14]]

^<<v7-21-14,14>>^ Os homens de Benjamim voltaram e receberam como esposas as quatrocentas mulheres de Jabes-Gileade que tinham sido poupadas. Mas não havia mulheres em número suficiente para todos eles.

[[v7-21-15]]

^<<v7-21-15,15>>^ O povo teve pena de Benjamim, pois o SENHOR havia aberto uma lacuna entre as tribos de Israel.

[[v7-21-16]]

^<<v7-21-16,16>>^ Então os líderes da comunidade perguntaram: "Como conseguiremos esposas para os poucos homens que restam, uma vez que as mulheres da tribo de Benjamim foram mortas?

[[v7-21-17]]

^<<v7-21-17,17>>^ Os sobreviventes precisam ter herdeiros, para que não seja eliminada uma tribo inteira de Israel.

[[v7-21-18]]

^<<v7-21-18,18>>^ Contudo, não podemos lhes dar nossas filhas em casamento, pois juramos solenemente que quem o fizer ficará sob a maldição de Deus".

[[v7-21-19]]

^<<v7-21-19,19>>^ Então eles se lembraram da festa anual do SENHOR, em Siló, ao sul de Lebona e ao norte de Betel, do lado leste da estrada que vai de Betel a Siquém.

[[v7-21-20]]

^<<v7-21-20,20>>^ Disseram aos homens de Benjamim que ainda precisavam de esposas: "Vão e escondam-se nos vinhedos.

[[v7-21-21]]

^<<v7-21-21,21>>^ Quando virem as moças de Siló irem para as danças, saiam correndo dos esconderijos e cada um leve uma delas para a terra de Benjamim, para ser sua esposa.

[[v7-21-22]]

^<<v7-21-22,22>>^ E quando os pais e os irmãos delas vierem se queixar a nós, diremos: ‘Por favor, tenham compaixão. Deixem que fiquem com suas filhas, pois não encontramos esposas para todos eles quando destruímos Jabes-Gileade. E vocês não são culpados de quebrarem seu juramento, pois, na verdade, não deram suas filhas para eles em casamento’".

[[v7-21-23]]

^<<v7-21-23,23>>^ Os homens de Benjamim seguiram essas instruções. Cada um pegou uma das moças que dançavam na comemoração e a levou para ser sua esposa. Voltaram para sua terra, reconstruíram suas cidades e habitaram nelas.

[[v7-21-24]]

^<<v7-21-24,24>>^ Então os israelitas partiram, por tribos e famílias, e cada um voltou para sua terra.

[[v7-21-25]]

^<<v7-21-25,25>>^ Naqueles dias, Israel não tinha rei; cada um fazia o que parecia certo a seus próprios olhos.

'''

xref:007-juizes/007-juizes-020.adoc#v7-20-0[&#60; Capítulo Anterior] | <<v7-21-0,Topo>> | xref:008-rute/008-rute-001.adoc#v8-1-0[Próximo Capítulo &#62;]