include::./index.adoc[]

[[v7-4-0]]
=== Juízes, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v7-4-1]]

^<<v7-4-1,1>>^ Depois da morte de Eúde, os israelitas voltaram a fazer o que era mau aos olhos do SENHOR.

[[v7-4-2]]

^<<v7-4-2,2>>^ Por isso, o SENHOR os entregou nas mãos de Jabim, rei cananeu de Hazor. O comandante de seu exército era Sísera, que habitava em Harosete-Hagoim.

[[v7-4-3]]

^<<v7-4-3,3>>^ Sísera, que tinha novecentos carros de guerra com rodas de ferro, oprimiu cruelmente os israelitas durante vinte anos. Então o povo pediu socorro ao SENHOR.

[[v7-4-4]]

^<<v7-4-4,4>>^ Quem julgava Israel nessa época era Débora, uma profetisa, mulher de Lapidote.

[[v7-4-5]]

^<<v7-4-5,5>>^ Ela costumava sentar-se debaixo da Palmeira de Débora, entre Ramá e Betel, na região montanhosa de Efraim, e os israelitas a procuravam para que ela julgasse suas questões.

[[v7-4-6]]

^<<v7-4-6,6>>^ Certo dia, mandou chamar Baraque, filho de Abinoão, que morava em Quedes, no território de Naftali, e lhe disse: "O SENHOR, o Deus de Israel, lhe dá a seguinte ordem: ‘Convoque dez mil guerreiros das tribos de Naftali e Zebulom para irem ao monte Tabor.

[[v7-4-7]]

^<<v7-4-7,7>>^ Eu farei Sísera, comandante do exército de Jabim, ir com seus carros de guerra e guerreiros até o rio Quisom. Ali eu os entregarei em suas mãos’".

[[v7-4-8]]

^<<v7-4-8,8>>^ Baraque disse a Débora: "Só irei se você for comigo; senão, não irei".

[[v7-4-9]]

^<<v7-4-9,9>>^ Débora respondeu: "Está bem, eu irei, mas você não receberá a honra nesta missão, pois o SENHOR entregará Sísera nas mãos de uma mulher". Então Débora foi com Baraque a Quedes.

[[v7-4-10]]

^<<v7-4-10,10>>^ Ali, Baraque convocou as tribos de Zebulom e Naftali, e dez mil guerreiros subiram com ele. Débora também o acompanhou.

[[v7-4-11]]

^<<v7-4-11,11>>^ Héber, queneu descendente de Hobabe, cunhado de Moisés, havia se separado dos outros membros de sua tribo e armado suas tendas junto ao carvalho de Zaanim, perto de Quedes.

[[v7-4-12]]

^<<v7-4-12,12>>^ Quando disseram a Sísera que Baraque, filho de Abinoão, havia subido ao monte Tabor,

[[v7-4-13]]

^<<v7-4-13,13>>^ ele mandou trazer seus novecentos carros de guerra com rodas de ferro e todos os seus guerreiros, e eles marcharam de Harosete-Hagoim até o rio Quisom.

[[v7-4-14]]

^<<v7-4-14,14>>^ Então Débora disse a Baraque: "Prepare-se! Este é o dia em que o SENHOR entregará Sísera em suas mãos, pois o SENHOR marcha adiante de você". Baraque desceu a encosta do monte Tabor à frente de seus dez mil guerreiros para combater.

[[v7-4-15]]

^<<v7-4-15,15>>^ Quando Baraque atacou, o SENHOR trouxe pânico sobre os carros de guerra e sobre os soldados de Sísera, que abandonou sua carruagem e fugiu a pé.

[[v7-4-16]]

^<<v7-4-16,16>>^ Baraque perseguiu os carros de guerra e o exército inimigo até Harosete-Hagoim e matou todos os guerreiros de Sísera. Nenhum deles escapou.

[[v7-4-17]]

^<<v7-4-17,17>>^ Enquanto isso, Sísera correu para a tenda de Jael, esposa de Héber, o queneu, pois havia paz entre a família de Héber e Jabim, rei de Hazor.

[[v7-4-18]]

^<<v7-4-18,18>>^ Jael saiu ao encontro de Sísera e disse: "Venha para minha tenda, senhor. Entre; não tenha medo". Ele entrou na tenda de Jael, e ela o cobriu com uma manta.

[[v7-4-19]]

^<<v7-4-19,19>>^ "Por favor, dê-me um pouco de água", disse ele. "Estou com sede." Ela lhe deu leite de uma vasilha de couro e o cobriu novamente.

[[v7-4-20]]

^<<v7-4-20,20>>^ Sísera disse a ela: "Fique à porta da tenda. Se alguém chegar e perguntar se há alguém aqui, diga que não".

[[v7-4-21]]

^<<v7-4-21,21>>^ Mas, quando Sísera, exausto, dormia um sono profundo, Jael, a esposa de Heber, se aproximou silenciosamente com um martelo e uma estaca de tenda na mão e atravessou o crânio dele com a estaca, que ficou presa ao chão. Foi assim que Sísera morreu.

[[v7-4-22]]

^<<v7-4-22,22>>^ Quando Baraque passou por lá à procura de Sísera, Jael saiu ao seu encontro e disse: "Venha! Eu lhe mostrarei o homem que o senhor está procurando". Ele a seguiu até a tenda, onde encontrou o cadáver de Sísera, com o crânio atravessado pela estaca.

[[v7-4-23]]

^<<v7-4-23,23>>^ Naquele dia, o povo de Israel viu Deus derrotar Jabim, o rei cananeu.

[[v7-4-24]]

^<<v7-4-24,24>>^ Dali em diante, os israelitas se fortaleceram cada vez mais contra o rei Jabim, até que o eliminaram por completo.

'''

xref:007-juizes/007-juizes-003.adoc#v7-3-0[&#60; Capítulo Anterior] | <<v7-4-0,Topo>> | xref:007-juizes/007-juizes-005.adoc#v7-5-0[Próximo Capítulo &#62;]