include::./index.adoc[]

[[v7-11-0]]
=== Juízes, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v7-11-1]]

^<<v7-11-1,1>>^ Jefté era um guerreiro corajoso. Era filho de Gileade, mas sua mãe era uma prostituta.

[[v7-11-2]]

^<<v7-11-2,2>>^ A esposa de Gileade teve muitos filhos, e quando esses meios-irmãos cresceram, expulsaram Jefté, dizendo: "Você não receberá parte alguma da herança de nosso pai, pois é filho de outra mulher".

[[v7-11-3]]

^<<v7-11-3,3>>^ Então Jefté fugiu de seus irmãos e foi viver na terra de Tobe. Em pouco tempo, passou a chefiar um bando de desocupados que se uniram a ele.

[[v7-11-4]]

^<<v7-11-4,4>>^ Por essa época, os amonitas começaram a guerrear contra Israel.

[[v7-11-5]]

^<<v7-11-5,5>>^ Quando os amonitas atacaram, os líderes de Gileade mandaram buscar Jefté na terra de Tobe.

[[v7-11-6]]

^<<v7-11-6,6>>^ "Venha e seja nosso comandante!", disseram. "Ajude-nos a lutar contra os amonitas!"

[[v7-11-7]]

^<<v7-11-7,7>>^ Mas Jefté lhes disse: "Não são vocês os mesmos que me odiavam e que me expulsaram da casa de meu pai? Por que me chamam agora que estão em apuros?".

[[v7-11-8]]

^<<v7-11-8,8>>^ "Porque precisamos de você", responderam os líderes. "Se você nos comandar na batalha contra os amonitas, nós o proclamaremos governante de todo o povo de Gileade."

[[v7-11-9]]

^<<v7-11-9,9>>^ Jefté lhes disse: "Quer dizer que se eu for com vocês e o SENHOR me der a vitória sobre os amonitas, governarei todo o povo?".

[[v7-11-10]]

^<<v7-11-10,10>>^ Os líderes de Gileade responderam: "O SENHOR é nossa testemunha de que faremos exatamente como você disse".

[[v7-11-11]]

^<<v7-11-11,11>>^ Então Jefté foi com os líderes de Gileade, e o povo o fez governante e comandante do exército. Em Mispá, na presença do SENHOR, Jefté repetiu o que tinha dito aos líderes.

[[v7-11-12]]

^<<v7-11-12,12>>^ Jefté enviou mensageiros ao rei de Amom para perguntar: "Por que você saiu para guerrear contra minha terra?".

[[v7-11-13]]

^<<v7-11-13,13>>^ O rei de Amom respondeu aos mensageiros de Jefté: "Quando saíram do Egito, os israelitas roubaram minhas terras desde o rio Arnom até o rio Jaboque, e até o Jordão. Agora, devolva-nos pacificamente esse território".

[[v7-11-14]]

^<<v7-11-14,14>>^ Jefté enviou a seguinte mensagem em resposta ao rei amonita:

[[v7-11-15]]

^<<v7-11-15,15>>^ "Assim diz Jefté: Israel não roubou terra alguma de Moabe nem de Amom.

[[v7-11-16]]

^<<v7-11-16,16>>^ Quando o povo de Israel veio do Egito e chegou a Cades, depois de atravessar o mar Vermelho,

[[v7-11-17]]

^<<v7-11-17,17>>^ enviou mensageiros ao rei de Edom e pediu: ‘Deixe-nos passar por sua terra’. Contudo, seu pedido foi negado. Então fizeram o mesmo pedido ao rei de Moabe, mas ele também não os deixou passar. Por isso, o povo de Israel ficou em Cades.

[[v7-11-18]]

^<<v7-11-18,18>>^ "Depois, passaram pelo deserto, contornando Edom e Moabe. Acompanharam a divisa de Moabe a leste e acamparam do outro lado do rio Arnom. Em momento algum atravessaram o Arnom para entrar em Moabe, pois o Arnom era a divisa de Moabe.

[[v7-11-19]]

^<<v7-11-19,19>>^ "Então Israel enviou mensageiros a Seom, rei dos amorreus, que governava em Hesbom, e pediu: ‘Deixe-nos passar por sua terra, para chegarmos ao nosso destino’.

[[v7-11-20]]

^<<v7-11-20,20>>^ O rei Seom, porém, não confiava em Israel o suficiente para deixar o povo passar por seu território. Em vez disso, mobilizou seu exército em Jaza e atacou Israel.

[[v7-11-21]]

^<<v7-11-21,21>>^ Mas o SENHOR, o Deus de Israel, entregou o rei Seom nas mãos de seu povo, que derrotou os amorreus. Israel tomou posse de toda a terra dos amorreus que viviam naquela região,

[[v7-11-22]]

^<<v7-11-22,22>>^ desde o Arnom até o Jaboque, e desde o deserto até o Jordão.

[[v7-11-23]]

^<<v7-11-23,23>>^ "Como você vê, foi o SENHOR, o Deus de Israel, que tirou a terra dos amorreus e a entregou a Israel. Por que, então, haveríamos de devolvê-la?

[[v7-11-24]]

^<<v7-11-24,24>>^ Fique com o que seu deus Camos lhe der, e nós ficaremos com o que o SENHOR, nosso Deus, nos der.

[[v7-11-25]]

^<<v7-11-25,25>>^ Acaso você é melhor que Balaque, filho de Zipor, rei de Moabe? Ele tentou disputar esses territórios com Israel? Entrou em guerra contra os israelitas?

[[v7-11-26]]

^<<v7-11-26,26>>^ "Israel vive aqui há trezentos anos. Habita em Hesbom e nos povoados ao redor, até Aroer e seus povoados, e todas as cidades às margens do rio Arnom. Por que, até agora, vocês não fizeram esforço algum para reaver esse território?

[[v7-11-27]]

^<<v7-11-27,27>>^ Portanto, não pequei contra você. Pelo contrário, você fez mal ao me atacar. Que o SENHOR, o Juiz, decida hoje qual de nós está certo: Israel ou Amom".

[[v7-11-28]]

^<<v7-11-28,28>>^ Mas o rei de Amom não deu atenção à mensagem de Jefté.

[[v7-11-29]]

^<<v7-11-29,29>>^ Então o Espírito do SENHOR veio sobre Jefté. Ele atravessou o território de Gileade e Manassés, incluindo Mispá em Gileade, e dali avançou contra os amonitas.

[[v7-11-30]]

^<<v7-11-30,30>>^ Jefté fez um voto ao SENHOR: "Se entregares os amonitas em minhas mãos,

[[v7-11-31]]

^<<v7-11-31,31>>^ darei ao SENHOR o que sair primeiro de minha casa quando eu regressar vitorioso. Eu o oferecerei como holocausto".

[[v7-11-32]]

^<<v7-11-32,32>>^ Jefté saiu com seu exército para combater os amonitas, e o SENHOR os entregou em suas mãos.

[[v7-11-33]]

^<<v7-11-33,33>>^ Ele aniquilou os amonitas e destruiu vinte cidades, desde Aroer até os arredores de Minite, chegando até Abel-Queramim. Assim, os israelitas derrotaram os amonitas.

[[v7-11-34]]

^<<v7-11-34,34>>^ Quando Jefté voltou para casa em Mispá, sua filha saiu ao seu encontro, tocando tamborim e dançando. Era sua única filha; ele não tinha nenhum outro filho nem filha.

[[v7-11-35]]

^<<v7-11-35,35>>^ Quando Jefté a viu, rasgou as próprias roupas e gritou. "Ah, minha filha! Você acabou comigo! Trouxe desgraça sobre mim! Fiz um voto ao SENHOR e não posso voltar atrás!".

[[v7-11-36]]

^<<v7-11-36,36>>^ Ela disse: "Pai, se fez um voto ao SENHOR, faça comigo o que prometeu, pois o SENHOR lhe deu grande vitória sobre seus inimigos, os amonitas.

[[v7-11-37]]

^<<v7-11-37,37>>^ Mas, primeiro, permita que eu ande pelos montes e chore com minhas amigas por dois meses, pois morrerei virgem".

[[v7-11-38]]

^<<v7-11-38,38>>^ "Pode ir", disse Jefté, e deixou que ela se ausentasse por dois meses. Ela e suas amigas foram para os montes e lamentaram, pois ela jamais teria filhos.

[[v7-11-39]]

^<<v7-11-39,39>>^ Quando ela voltou para casa, seu pai cumpriu o voto que havia feito, e ela morreu sem ter tido relações com homem algum. Por isso, tornou-se costume em Israel

[[v7-11-40]]

^<<v7-11-40,40>>^ as moças israelitas saírem por quatro dias todos os anos para lamentar o destino da filha de Jefté, de Gileade.

'''

xref:007-juizes/007-juizes-010.adoc#v7-10-0[&#60; Capítulo Anterior] | <<v7-11-0,Topo>> | xref:007-juizes/007-juizes-012.adoc#v7-12-0[Próximo Capítulo &#62;]