include::./index.adoc[]

[[v29-1-0]]
=== Joel, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v29-1-1]]

^<<v29-1-1,1>>^ O SENHOR deu esta mensagem a Joel, filho de Petuel.

[[v29-1-2]]

^<<v29-1-2,2>>^ Ouçam isto, líderes do povo! Ouçam todos que habitam na terra! Em toda a sua história, já ocorreu algo semelhante?

[[v29-1-3]]

^<<v29-1-3,3>>^ Contem a seus filhos o que aconteceu, e que seus filhos contem aos filhos deles; transmitam esta história de geração em geração.

[[v29-1-4]]

^<<v29-1-4,4>>^ Depois que os gafanhotos cortadores devoraram as colheitas, os gafanhotos migradores comeram o que restava; então vieram os gafanhotos saltadores e, depois deles, os gafanhotos destruidores!

[[v29-1-5]]

^<<v29-1-5,5>>^ Despertem e chorem, bêbados! Lamentem, vocês que tomam vinho! Todas as uvas estão arruinadas, todo o seu vinho doce acabou.

[[v29-1-6]]

^<<v29-1-6,6>>^ Uma nação imensa invadiu minha terra, um exército terrível, tão numeroso que não se pode contar. Seus dentes são como os de leões, suas presas, como as da leoa.

[[v29-1-7]]

^<<v29-1-7,7>>^ Destruiu minhas videiras e arruinou minhas figueiras. Arrancou sua casca e as destruiu; seus galhos ficaram desfolhados.

[[v29-1-8]]

^<<v29-1-8,8>>^ Chorem como a moça vestida de luto, que lamenta a morte do noivo.

[[v29-1-9]]

^<<v29-1-9,9>>^ Pois não há cereal nem vinho para oferecer no templo do SENHOR. Por isso os sacerdotes estão de luto; aqueles que servem na casa do SENHOR choram.

[[v29-1-10]]

^<<v29-1-10,10>>^ Os campos estão arruinados, a terra está desolada. O trigo está destruído, as uvas secaram e o azeite acabou.

[[v29-1-11]]

^<<v29-1-11,11>>^ Desesperem-se, agricultores! Lamentem, vocês que cuidam das videiras! Chorem, pois o trigo e a cevada, todas as colheitas nos campos, estão arruinados.

[[v29-1-12]]

^<<v29-1-12,12>>^ As videiras secaram, e as figueiras murcharam. As romãzeiras, as palmeiras e as macieiras, todas as árvores frutíferas secaram, e com elas murchou a alegria do povo.

[[v29-1-13]]

^<<v29-1-13,13>>^ Vistam-se de pano de saco e chorem, sacerdotes! Lamentem, vocês que servem diante do altar! Venham, passem a noite vestidos de pano de saco, vocês que servem ao meu Deus. Pois não há cereal nem vinho para oferecer no templo de seu Deus.

[[v29-1-14]]

^<<v29-1-14,14>>^ Convoquem um tempo de jejum, juntem o povo para uma reunião solene. Tragam os líderes e todos que habitam na terra para o templo do SENHOR, seu Deus, e ali clamem a ele.

[[v29-1-15]]

^<<v29-1-15,15>>^ O dia do SENHOR está próximo, o dia em que virá destruição da parte do Todo-poderoso; que dia terrível será!

[[v29-1-16]]

^<<v29-1-16,16>>^ Nosso alimento desaparece diante dos olhos; já não há alegria e exultação na casa de nosso Deus.

[[v29-1-17]]

^<<v29-1-17,17>>^ As sementes morrem na terra seca, as colheitas de cereal se perdem. Os celeiros estão vazios, os armazéns, abandonados.

[[v29-1-18]]

^<<v29-1-18,18>>^ Como os animais gemem de fome! As manadas de gado vagam confusas, pois não encontram pasto; os rebanhos de ovelhas sofrem.

[[v29-1-19]]

^<<v29-1-19,19>>^ Socorro, SENHOR! O fogo devorou os pastos do deserto, e as chamas queimaram as árvores do campo.

[[v29-1-20]]

^<<v29-1-20,20>>^ Até os animais selvagens clamam a ti, pois os riachos secaram, e o fogo devorou os pastos do deserto.

'''

xref:028-oseias/028-oseias-014.adoc#v28-14-0[&#60; Capítulo Anterior] | <<v29-1-0,Topo>> | xref:029-joel/029-joel-002.adoc#v29-2-0[Próximo Capítulo &#62;]