include::./index.adoc[]

[[v29-2-0]]
=== Joel, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v29-2-1]]

^<<v29-2-1,1>>^ Toquem a trombeta em Sião! Soem o alarme em meu santo monte! Que todos tremam de medo, pois está chegando o dia do SENHOR.

[[v29-2-2]]

^<<v29-2-2,2>>^ É um dia de escuridão e trevas, um dia de densas nuvens e sombras profundas. Como o amanhecer se estende pelos montes, assim surge um grande e poderoso exército. Nunca se viu algo parecido, e nunca mais se verá.

[[v29-2-3]]

^<<v29-2-3,3>>^ À frente deles o fogo arde, atrás deles vêm chamas. Diante deles a terra se estende, bela como o jardim do Éden. Atrás deles só há desolação; nada escapa.

[[v29-2-4]]

^<<v29-2-4,4>>^ Parecem cavalos, atacam como cavalos de guerra.

[[v29-2-5]]

^<<v29-2-5,5>>^ Olhem para eles, saltando sobre o topo dos montes; ouçam o barulho que fazem, como o estrondo de carros de guerra, como o fogo crepitante que devora um campo cheio de palha, como um exército poderoso que avança para a batalha.

[[v29-2-6]]

^<<v29-2-6,6>>^ O medo toma conta do povo; todo rosto fica pálido de terror.

[[v29-2-7]]

^<<v29-2-7,7>>^ Os agressores marcham como guerreiros e, como soldados, escalam os muros da cidade. Marcham sempre em frente, sem deixar suas fileiras.

[[v29-2-8]]

^<<v29-2-8,8>>^ Não empurram uns aos outros; cada um se move na posição correta. Rompem as linhas de defesa, sem desfazer a formação.

[[v29-2-9]]

^<<v29-2-9,9>>^ Atacam a cidade e correm ao longo de seus muros. Entram em todas as casas e sobem pelas janelas, como ladrões.

[[v29-2-10]]

^<<v29-2-10,10>>^ A terra treme com seu avanço, e os céus estremecem. O sol e a lua escurecem, e as estrelas deixam de brilhar.

[[v29-2-11]]

^<<v29-2-11,11>>^ O SENHOR está à frente de seu exército; com um grito, ele o comanda. É seu exército poderoso e segue suas ordens. O dia do SENHOR é espantoso e terrível; quem poderá sobreviver?

[[v29-2-12]]

^<<v29-2-12,12>>^ Por isso, o SENHOR diz: "Voltem para mim de todo o coração, venham a mim com jejum, choro e lamento!

[[v29-2-13]]

^<<v29-2-13,13>>^ Não rasguem as roupas em sinal de tristeza; rasguem o coração!". Voltem para o SENHOR, seu Deus, pois ele é misericordioso e compassivo, lento para se irar e cheio de amor; está sempre pronto a voltar atrás e não castigar.

[[v29-2-14]]

^<<v29-2-14,14>>^ Quem sabe ele mude de ideia e lhes envie bênção em lugar desse castigo. Talvez possam apresentar ofertas de cereal e vinho ao SENHOR, seu Deus, como faziam antes.

[[v29-2-15]]

^<<v29-2-15,15>>^ Toquem a trombeta em Sião! Convoquem um tempo de jejum, juntem o povo para uma reunião solene.

[[v29-2-16]]

^<<v29-2-16,16>>^ Reúnam e consagrem todo o povo, os anciãos, as crianças e até os bebês. Chamem o noivo de seu aposento e a noiva, de seu quarto.

[[v29-2-17]]

^<<v29-2-17,17>>^ Que os sacerdotes, que servem na presença do SENHOR, chorem entre o pórtico do templo e o altar. Que façam esta oração: "Poupa teu povo, SENHOR! Não permitas que a nação que pertence a ti se torne objeto de zombaria. Não deixes que seja motivo de piada para as nações que dizem: ‘Onde está o seu Deus?’".

[[v29-2-18]]

^<<v29-2-18,18>>^ Então o SENHOR teve compaixão de seu povo e com zelo guardou sua terra.

[[v29-2-19]]

^<<v29-2-19,19>>^ O SENHOR respondeu: "Vejam! Eu lhes envio cereal, vinho novo e azeite, suficientes para saciá-los. Vocês não serão mais objeto de zombaria entre as nações vizinhas.

[[v29-2-20]]

^<<v29-2-20,20>>^ Expulsarei esses exércitos que vêm do norte e os enviarei para uma terra seca e desolada. Os que estão na vanguarda serão empurrados para o mar Morto, e os da retaguarda, para o Mediterrâneo. O mau cheiro dos corpos em decomposição se espalhará sobre a terra". Certamente o SENHOR tem feito grandes coisas!

[[v29-2-21]]

^<<v29-2-21,21>>^ Não tema, ó terra; alegre-se e exulte, pois o SENHOR tem feito grandes coisas.

[[v29-2-22]]

^<<v29-2-22,22>>^ Não tenham medo, animais do campo, pois os pastos do deserto ficarão verdes. As árvores voltarão a dar frutos, as figueiras e as videiras ficarão carregadas.

[[v29-2-23]]

^<<v29-2-23,23>>^ Alegrem-se, vocês que habitam em Sião! Exultem no SENHOR, seu Deus! Pois ele envia as chuvas na medida certa; as chuvas de outono voltarão a cair, e também as chuvas de primavera.

[[v29-2-24]]

^<<v29-2-24,24>>^ As eiras voltarão a se encher de trigo, e os tanques de prensar transbordarão de vinho novo e azeite.

[[v29-2-25]]

^<<v29-2-25,25>>^ "Eu lhes devolverei o que perderam por causa dos gafanhotos migradores, dos saltadores, dos destruidores e dos cortadores; enviei esse grande exército devastador contra vocês.

[[v29-2-26]]

^<<v29-2-26,26>>^ Vocês voltarão a ter alimento até se saciar e louvarão o SENHOR, seu Deus, que realiza esses milagres em seu favor; nunca mais meu povo será envergonhado.

[[v29-2-27]]

^<<v29-2-27,27>>^ Então vocês saberão que estou no meio de Israel, que sou o SENHOR, seu Deus, e não há nenhum outro; nunca mais meu povo será envergonhado."

[[v29-2-28]]

^<<v29-2-28,28>>^ "Então, depois que eu tiver feito essas coisas, derramarei meu Espírito sobre todo tipo de pessoa. Seus filhos e suas filhas profetizarão; os velhos terão sonhos, e os jovens terão visões.

[[v29-2-29]]

^<<v29-2-29,29>>^ Naqueles dias, derramarei meu Espírito até mesmo sobre servos e servas.

[[v29-2-30]]

^<<v29-2-30,30>>^ Farei maravilhas nos céus e na terra: sangue e fogo, e colunas de fumaça.

[[v29-2-31]]

^<<v29-2-31,31>>^ O sol se escurecerá, a lua se tornará vermelha como sangue antes que chegue o grande e terrível dia do SENHOR.

[[v29-2-32]]

^<<v29-2-32,32>>^ Mas todo aquele que invocar o nome do Senhor será salvo, pois alguns no monte Sião, em Jerusalém, escaparão, como o SENHOR prometeu. Estarão entre os sobreviventes que o SENHOR chamou."

'''

xref:029-joel/029-joel-001.adoc#v29-1-0[&#60; Capítulo Anterior] | <<v29-2-0,Topo>> | xref:029-joel/029-joel-003.adoc#v29-3-0[Próximo Capítulo &#62;]