include::./index.adoc[]

[[v23-19-0]]
=== Isaías, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v23-19-1]]

^<<v23-19-1,1>>^ Recebi esta mensagem acerca do Egito: Vejam, o SENHOR avança contra o Egito, montado em uma nuvem veloz! Os ídolos do Egito estremecem diante dele; o coração dos egípcios se derrete de medo.

[[v23-19-2]]

^<<v23-19-2,2>>^ "Farei egípcio lutar contra egípcio, irmão contra irmão, vizinho contra vizinho, cidade contra cidade, província contra província.

[[v23-19-3]]

^<<v23-19-3,3>>^ Os egípcios se desesperarão, e eu confundirei seus planos. Pedirão sabedoria a seus ídolos e invocarão espíritos; consultarão médiuns e praticantes do ocultismo.

[[v23-19-4]]

^<<v23-19-4,4>>^ Entregarei o Egito a um senhor cruel; um rei feroz os governará", declara o Soberano SENHOR dos Exércitos.

[[v23-19-5]]

^<<v23-19-5,5>>^ As águas do Nilo deixarão de inundar os campos; o leito do rio ficará seco e árido.

[[v23-19-6]]

^<<v23-19-6,6>>^ Os canais do Nilo secarão; os ribeiros do Egito terão mau cheiro, e juncos e canas apodrecerão.

[[v23-19-7]]

^<<v23-19-7,7>>^ Toda a vegetação às margens do rio, todas as plantações junto a ele, secarão e serão levadas pelo vento.

[[v23-19-8]]

^<<v23-19-8,8>>^ Os pescadores lamentarão, os que lançam anzóis no Nilo gemerão, e os que usam redes perderão o ânimo.

[[v23-19-9]]

^<<v23-19-9,9>>^ Não haverá linho para os ceifeiros, nem fio para os tecelões.

[[v23-19-10]]

^<<v23-19-10,10>>^ Ficarão todos desesperados; os trabalhadores se encherão de tristeza.

[[v23-19-11]]

^<<v23-19-11,11>>^ Como são tolos os oficiais de Zoã; seus conselhos ao rei do Egito são absurdos! Ainda assim, contarão vantagem ao faraó? Ousarão se gabar da sabedoria de seus antepassados?

[[v23-19-12]]

^<<v23-19-12,12>>^ Onde estão seus grandes conselheiros, faraó? Que lhe informem os planos de Deus, o que o SENHOR dos Exércitos fará ao Egito.

[[v23-19-13]]

^<<v23-19-13,13>>^ Os oficiais de Zoã são tolos, os oficiais de Mênfis foram enganados. As autoridades do povo fizeram o Egito se desviar.

[[v23-19-14]]

^<<v23-19-14,14>>^ O SENHOR enviou sobre eles um espírito de confusão; estão equivocados em tudo que dizem. Fazem o Egito cambalear, como um bêbado em seu vômito.

[[v23-19-15]]

^<<v23-19-15,15>>^ Não há nada que o Egito possa fazer; todos estão indefesos: a cabeça e a cauda, o ramo da palmeira e o junco.

[[v23-19-16]]

^<<v23-19-16,16>>^ Naquele dia, os egípcios serão frágeis como mulheres. Eles se encolherão de medo debaixo da mão levantada do SENHOR dos Exércitos.

[[v23-19-17]]

^<<v23-19-17,17>>^ A simples menção à terra de Judá os encherá de terror, pois o SENHOR dos Exércitos traçou seus planos contra eles.

[[v23-19-18]]

^<<v23-19-18,18>>^ Naquele dia, cinco cidades egípcias seguirão o SENHOR dos Exércitos e até começarão a falar a língua de Canaã. Uma dessas cidades será Heliópolis, a Cidade do Sol.

[[v23-19-19]]

^<<v23-19-19,19>>^ Naquele dia, haverá um altar ao SENHOR no centro do Egito e um monumento ao SENHOR em sua fronteira.

[[v23-19-20]]

^<<v23-19-20,20>>^ Serão sinal e testemunho de que o SENHOR dos Exércitos é adorado na terra do Egito. Quando o povo clamar ao SENHOR por causa de seus opressores, ele enviará um salvador que lutará por eles e os livrará.

[[v23-19-21]]

^<<v23-19-21,21>>^ Naquele dia, o SENHOR se revelará aos egípcios. Sim, eles conhecerão o SENHOR e lhe apresentarão sacrifícios e ofertas. Farão um voto ao SENHOR e o cumprirão.

[[v23-19-22]]

^<<v23-19-22,22>>^ O SENHOR ferirá o Egito, mas depois trará cura. Pois os egípcios se voltarão para o SENHOR, e ele ouvirá suas súplicas e lhes dará cura.

[[v23-19-23]]

^<<v23-19-23,23>>^ Naquele dia, o Egito e a Assíria serão ligados por uma estrada. Os egípcios e os assírios viajarão livremente entre seus países e adorarão juntos.

[[v23-19-24]]

^<<v23-19-24,24>>^ Naquele dia, Israel será o terceiro, junto com o Egito e a Assíria, uma bênção no meio da terra.

[[v23-19-25]]

^<<v23-19-25,25>>^ Porque o SENHOR dos Exércitos dirá: "Bendito seja o Egito, meu povo. Bendita seja a Assíria, a terra que criei. Bendito seja Israel, minha propriedade especial".

'''

xref:023-isaias/023-isaias-018.adoc#v23-18-0[&#60; Capítulo Anterior] | <<v23-19-0,Topo>> | xref:023-isaias/023-isaias-020.adoc#v23-20-0[Próximo Capítulo &#62;]