include::./index.adoc[]

[[v23-53-0]]
=== Isaías, 53
// nvt ?, NVT - Nova Versão Transformadora

[[v23-53-1]]

^<<v23-53-1,1>>^ Quem creu em nossa mensagem? A quem o SENHOR revelou seu braço forte?

[[v23-53-2]]

^<<v23-53-2,2>>^ Meu servo cresceu em sua presença, como tenro broto verde, como raiz em terra seca. Não havia nada de belo nem majestoso em sua aparência, nada que nos atraísse.

[[v23-53-3]]

^<<v23-53-3,3>>^ Foi desprezado e rejeitado, homem de dores, que conhece o sofrimento mais profundo. Demos as costas para ele e desviamos o olhar; ele foi desprezado, e não nos importamos.

[[v23-53-4]]

^<<v23-53-4,4>>^ Apesar disso, foram as nossas enfermidades que ele tomou sobre si, e foram as nossas doenças que pesaram sobre ele. Pensamos que seu sofrimento era castigo de Deus, castigo por sua culpa.

[[v23-53-5]]

^<<v23-53-5,5>>^ Mas ele foi ferido por causa de nossa rebeldia e esmagado por causa de nossos pecados. Sofreu o castigo para que fôssemos restaurados e recebeu açoites para que fôssemos curados.

[[v23-53-6]]

^<<v23-53-6,6>>^ Todos nós nos desviamos como ovelhas; deixamos os caminhos de Deus para seguir os nossos caminhos. E, no entanto, o SENHOR fez cair sobre ele os pecados de todos nós.

[[v23-53-7]]

^<<v23-53-7,7>>^ Ele foi oprimido e humilhado, mas não disse uma só palavra. Foi levado como cordeiro para o matadouro; como ovelha muda diante dos tosquiadores, não abriu a boca.

[[v23-53-8]]

^<<v23-53-8,8>>^ Condenado injustamente, foi levado embora. Ninguém se importou de ele morrer sem deixar descendentes, de sua vida ser cortada no meio do caminho. Mas ele foi ferido mortalmente por causa da rebeldia do meu povo.

[[v23-53-9]]

^<<v23-53-9,9>>^ Não havia cometido nenhuma injustiça e jamais havia enganado alguém. Ainda assim, foi sepultado como criminoso, colocado no túmulo de um homem rico.

[[v23-53-10]]

^<<v23-53-10,10>>^ Fazia parte do plano do SENHOR esmagá-lo e causar-lhe dor. Quando, porém, sua vida for entregue como oferta pelo pecado, ele terá muitos descendentes. Terá vida longa, e o plano do SENHOR prosperará em suas mãos.

[[v23-53-11]]

^<<v23-53-11,11>>^ Quando ele vir tudo que resultar de sua angústia, ficará satisfeito. E, por causa de tudo que meu servo justo passou, ele fará que muitos sejam considerados justos, pois levará sobre si os pecados deles.

[[v23-53-12]]

^<<v23-53-12,12>>^ Eu lhe darei as honras de um soldado vitorioso, pois ele se expôs à morte. Foi contado entre os rebeldes; levou sobre si a culpa de muitos e intercedeu pelos pecadores.

'''

xref:023-isaias/023-isaias-052.adoc#v23-52-0[&#60; Capítulo Anterior] | <<v23-53-0,Topo>> | xref:023-isaias/023-isaias-054.adoc#v23-54-0[Próximo Capítulo &#62;]