include::./index.adoc[]

[[v23-64-0]]
=== Isaías, 64
// nvt ?, NVT - Nova Versão Transformadora

[[v23-64-1]]

^<<v23-64-1,1>>^ Quem dera abrisses os céus e descesses! Os montes tremeriam em tua presença!

[[v23-64-2]]

^<<v23-64-2,2>>^ Assim como o fogo faz a lenha queimar e a água ferver, tua vinda faria as nações estremecerem; então seus inimigos entenderiam a razão de tua fama!

[[v23-64-3]]

^<<v23-64-3,3>>^ Quando desceste muito tempo atrás, realizaste coisas maravilhosas que não esperávamos; ah, como os montes tremeram diante de ti!

[[v23-64-4]]

^<<v23-64-4,4>>^ Porque desde o começo do mundo, nenhum ouvido ouviu e nenhum olho viu um Deus semelhante a ti, que trabalha em favor dos que nele esperam.

[[v23-64-5]]

^<<v23-64-5,5>>^ Recebes de braços abertos os que praticam a justiça com alegria, os que seguem teus caminhos. Mas ficaste muito irado conosco, pois pecamos constantemente; como seremos salvos?

[[v23-64-6]]

^<<v23-64-6,6>>^ Estamos todos impuros por causa de nosso pecado; quando mostramos nossos atos de justiça, não passam de trapos imundos. Como as folhas das árvores, murchamos e caímos, e nossos pecados nos levam embora como o vento.

[[v23-64-7]]

^<<v23-64-7,7>>^ Ainda assim, ninguém invoca teu nome nem suplica por tua misericórdia. Por isso te afastaste de nós e nos entregaste a nossos pecados.

[[v23-64-8]]

^<<v23-64-8,8>>^ Apesar de tudo, ó SENHOR, és nosso Pai. Nós somos o barro, e tu és o oleiro; somos todos formados por tua mão.

[[v23-64-9]]

^<<v23-64-9,9>>^ Não te ires tanto conosco, SENHOR, não te lembres para sempre de nossos pecados. Pedimos que olhes para nós e vejas que somos teu povo.

[[v23-64-10]]

^<<v23-64-10,10>>^ Tuas cidades santas estão destruídas; Sião é um deserto, sim, Jerusalém é uma ruína desolada.

[[v23-64-11]]

^<<v23-64-11,11>>^ O santo e belo templo, onde nossos antepassados te louvavam, foi queimado; tudo que era precioso foi destruído.

[[v23-64-12]]

^<<v23-64-12,12>>^ Depois disso tudo, SENHOR, ainda te recusarás a nos ajudar? Permanecerás calado e continuarás a nos castigar?

'''

xref:023-isaias/023-isaias-063.adoc#v23-63-0[&#60; Capítulo Anterior] | <<v23-64-0,Topo>> | xref:023-isaias/023-isaias-065.adoc#v23-65-0[Próximo Capítulo &#62;]