include::./index.adoc[]

[[v23-52-0]]
=== Isaías, 52
// nvt ?, NVT - Nova Versão Transformadora

[[v23-52-1]]

^<<v23-52-1,1>>^ Desperte, desperte, ó Sião! Vista-se de força! Ponha suas lindas roupas, ó cidade santa de Jerusalém, pois os incircuncisos e os impuros não entrarão mais por seus portões.

[[v23-52-2]]

^<<v23-52-2,2>>^ Levante-se do pó, ó Jerusalém, sente-se no lugar de honra. Tire de seu pescoço as correntes de escravidão, ó cativa Sião.

[[v23-52-3]]

^<<v23-52-3,3>>^ Pois assim diz o SENHOR: "Quando eu a vendi ao exílio, não recebi pagamento algum. Agora a resgatarei sem ter de pagar por você".

[[v23-52-4]]

^<<v23-52-4,4>>^ Assim diz o SENHOR Soberano: "Há muito tempo, meu povo escolheu morar no Egito. Agora, a Assíria os oprime sem nenhuma razão.

[[v23-52-5]]

^<<v23-52-5,5>>^ O que é isso?", pergunta o SENHOR. "Por que meu povo foi escravizado novamente? Aqueles que os dominam gritam de alegria. Meu nome é blasfemado o dia inteiro.

[[v23-52-6]]

^<<v23-52-6,6>>^ Mas eu revelarei meu nome ao meu povo, e eles, por fim, reconhecerão que sou eu quem fala com eles."

[[v23-52-7]]

^<<v23-52-7,7>>^ Como são belos sobre os montes os pés do mensageiro que traz boas-novas, boas-novas de paz e salvação, de que o Deus de Israel reina!

[[v23-52-8]]

^<<v23-52-8,8>>^ Os vigias gritam e cantam de alegria, pois, com os próprios olhos, veem o SENHOR voltar a Sião.

[[v23-52-9]]

^<<v23-52-9,9>>^ Que as ruínas de Jerusalém gritem de alegria, pois o SENHOR consolou seu povo; ele resgatou Jerusalém.

[[v23-52-10]]

^<<v23-52-10,10>>^ O SENHOR mostrou seu santo poder diante dos olhos de todas as nações. Todos os confins da terra verão a salvação de nosso Deus.

[[v23-52-11]]

^<<v23-52-11,11>>^ Saiam! Saiam e deixem para trás o cativeiro, não toquem no que é impuro. Saiam daí e purifiquem-se, vocês que levam de volta os objetos sagrados do SENHOR.

[[v23-52-12]]

^<<v23-52-12,12>>^ Não partirão às pressas, como quem foge para salvar a vida, pois o SENHOR irá à sua frente; sim, o Deus de Israel os protegerá na retaguarda.

[[v23-52-13]]

^<<v23-52-13,13>>^ Vejam, meu servo terá êxito; será muito exaltado.

[[v23-52-14]]

^<<v23-52-14,14>>^ Muitos, porém, ficaram espantados quando o viram: seu rosto estava tão desfigurado que mal parecia humano; por seu aspecto, quase não era possível reconhecê-lo como homem.

[[v23-52-15]]

^<<v23-52-15,15>>^ Ele causará assombro em muitas nações; reis ficarão mudos diante dele, pois verão aquilo que ninguém lhes havia falado, entenderão aquilo que nunca tinham ouvido.

'''

xref:023-isaias/023-isaias-051.adoc#v23-51-0[&#60; Capítulo Anterior] | <<v23-52-0,Topo>> | xref:023-isaias/023-isaias-053.adoc#v23-53-0[Próximo Capítulo &#62;]