include::./index.adoc[]

[[v23-42-0]]
=== Isaías, 42
// nvt ?, NVT - Nova Versão Transformadora

[[v23-42-1]]

^<<v23-42-1,1>>^ "Vejam meu servo, que eu fortaleço; ele é meu escolhido, que me dá alegria. Pus sobre ele meu Espírito; ele trará justiça às nações.

[[v23-42-2]]

^<<v23-42-2,2>>^ Não gritará, nem levantará a voz em público.

[[v23-42-3]]

^<<v23-42-3,3>>^ Não esmagará a cana quebrada, nem apagará a chama que já está fraca; fará justiça a todos os injustiçados.

[[v23-42-4]]

^<<v23-42-4,4>>^ Não vacilará nem desanimará, enquanto não fizer a justiça prevalecer em toda a terra. Até mesmo terras distantes, do outro lado do mar, aguardarão suas instruções."

[[v23-42-5]]

^<<v23-42-5,5>>^ Deus, o SENHOR, criou os céus e os estendeu; criou a terra e tudo que nela há. Dá fôlego a cada um e vida a todos que caminham sobre a terra. É ele quem diz:

[[v23-42-6]]

^<<v23-42-6,6>>^ "Eu, o SENHOR, o chamei para mostrar minha justiça; eu o tomarei pela mão e o protegerei. Eu o darei a meu povo, Israel, como símbolo de minha aliança com eles, e você será luz para guiar as nações:

[[v23-42-7]]

^<<v23-42-7,7>>^ abrirá os olhos dos cegos, libertará da prisão os cativos, livrará os que estão em calabouços escuros.

[[v23-42-8]]

^<<v23-42-8,8>>^ "Eu sou o SENHOR; este é meu nome! Não darei minha glória a ninguém, não repartirei meu louvor com ídolos esculpidos.

[[v23-42-9]]

^<<v23-42-9,9>>^ Tudo que profetizei se cumpriu, e agora profetizarei novamente; eu lhes falarei do futuro antes que aconteça".

[[v23-42-10]]

^<<v23-42-10,10>>^ Cantem um novo cântico ao SENHOR, cantem seu louvor desde os confins da terra! Cantem, vocês que navegam pelos mares, todos vocês que moram em litorais distantes!

[[v23-42-11]]

^<<v23-42-11,11>>^ Levantem a voz, cidades do deserto, alegrem-se as vilas de Quedar! Exultem, habitantes de Sela, aclamem do alto dos montes!

[[v23-42-12]]

^<<v23-42-12,12>>^ Que o mundo inteiro glorifique o Senhor e cante seu louvor!

[[v23-42-13]]

^<<v23-42-13,13>>^ O SENHOR marchará como herói poderoso; sairá como guerreiro, cheio de fúria. Dará seu grito de guerra e esmagará todos os seus inimigos.

[[v23-42-14]]

^<<v23-42-14,14>>^ "Durante muito tempo, fiquei em silêncio; sim, me contive. Agora, porém, como a mulher no parto, gritarei, gemerei e ficarei ofegante.

[[v23-42-15]]

^<<v23-42-15,15>>^ Arrasarei os montes e as colinas e acabarei com sua vegetação. Tornarei os rios em terra seca e secarei os açudes.

[[v23-42-16]]

^<<v23-42-16,16>>^ Conduzirei este povo cego por um novo caminho e o guiarei por um rumo desconhecido. Transformarei em luz a escuridão diante dele e tornarei planos os trechos acidentados. Sim, farei estas coisas; não o abandonarei.

[[v23-42-17]]

^<<v23-42-17,17>>^ Mas os que confiam em ídolos e dizem: ‘Vocês são nossos deuses’, sofrerão vergonhosa derrota."

[[v23-42-18]]

^<<v23-42-18,18>>^ "Ouçam, surdos! Olhem e vejam, cegos!

[[v23-42-19]]

^<<v23-42-19,19>>^ Quem é cego como meu povo, meu servo? Quem é surdo como meu mensageiro? Quem é cego como meu povo escolhido, o servo do SENHOR?

[[v23-42-20]]

^<<v23-42-20,20>>^ Vocês veem e reconhecem o que é certo, mas se recusam a fazê-lo. Ouvem com os ouvidos, mas não prestam atenção."

[[v23-42-21]]

^<<v23-42-21,21>>^ Porque o SENHOR é justo, ele exaltou sua lei gloriosa.

[[v23-42-22]]

^<<v23-42-22,22>>^ Seu povo, porém, foi roubado e saqueado, escravizado, aprisionado e apanhado numa armadilha. São presa fácil para qualquer um e não têm quem os proteja, ninguém que os leve de volta para casa.

[[v23-42-23]]

^<<v23-42-23,23>>^ Quem ouvirá essas lições do passado e verá a ruína que os espera no futuro?

[[v23-42-24]]

^<<v23-42-24,24>>^ Quem permitiu que Israel fosse roubado e ferido? Foi o SENHOR, contra quem pecamos, pois seu povo não andou em seu caminho, nem obedeceu à sua lei.

[[v23-42-25]]

^<<v23-42-25,25>>^ Por isso ele derramou sobre eles sua ira ardente e os destruiu na batalha. Ficaram envoltos em chamas, mas se recusaram a entender. Foram consumidos pelo fogo, mas não aprenderam a lição.

'''

xref:023-isaias/023-isaias-041.adoc#v23-41-0[&#60; Capítulo Anterior] | <<v23-42-0,Topo>> | xref:023-isaias/023-isaias-043.adoc#v23-43-0[Próximo Capítulo &#62;]