include::./index.adoc[]

[[v23-62-0]]
=== Isaías, 62
// nvt ?, NVT - Nova Versão Transformadora

[[v23-62-1]]

^<<v23-62-1,1>>^ Por causa de Sião, não permanecerei quieto. Por causa de Jerusalém, não ficarei calado, até sua justiça brilhar como o amanhecer e sua salvação resplandecer como uma tocha acesa.

[[v23-62-2]]

^<<v23-62-2,2>>^ As nações verão sua justiça, reis de todo o mundo contemplarão sua glória. E você receberá um novo nome, da boca do SENHOR.

[[v23-62-3]]

^<<v23-62-3,3>>^ Será uma esplêndida coroa na mão do SENHOR, erguida na mão de Deus para que todos a vejam.

[[v23-62-4]]

^<<v23-62-4,4>>^ Nunca mais será chamada de "Cidade Abandonada" nem de "Terra Desolada". Seu novo nome será "Cidade do Prazer de Deus" e "Esposa de Deus", pois o SENHOR tem prazer em você e a tomará como esposa.

[[v23-62-5]]

^<<v23-62-5,5>>^ Seus filhos se comprometerão com você, como o jovem se compromete com sua noiva. Então Deus se alegrará por você, como o noivo se alegra por sua noiva.

[[v23-62-6]]

^<<v23-62-6,6>>^ Ó Jerusalém, coloquei vigias sobre seus muros; eles vigiarão continuamente, dia e noite. Não descansem, vocês que oram ao SENHOR!

[[v23-62-7]]

^<<v23-62-7,7>>^ Não deem descanso ao SENHOR até que ele complete sua obra, até que ele torne Jerusalém motivo de orgulho de toda a terra.

[[v23-62-8]]

^<<v23-62-8,8>>^ O SENHOR jurou a Jerusalém por sua própria força: "Nunca mais a entregarei a seus inimigos; nunca mais virão guerreiros de outras nações para levar seu cereal e seu vinho novo.

[[v23-62-9]]

^<<v23-62-9,9>>^ Vocês que colherem o cereal o comerão e louvarão o SENHOR. Nos pátios do templo beberão o vinho que prensaram".

[[v23-62-10]]

^<<v23-62-10,10>>^ Saiam pelos portões! Saiam pelos portões! Preparem o caminho para meu povo retornar! Aplanem, aplanem a estrada e removam as pedras, levantem uma bandeira para que todas as nações a vejam!

[[v23-62-11]]

^<<v23-62-11,11>>^ O SENHOR enviou esta mensagem até os confins da terra: "Digam ao povo de Sião: Vejam, seu Salvador se aproxima! Olhem, ele traz consigo sua recompensa!".

[[v23-62-12]]

^<<v23-62-12,12>>^ Eles serão chamados de "Povo Santo" e "Povo que o SENHOR Resgatou". E Jerusalém será conhecida como "Lugar Desejável" e "Cidade Não Abandonada".

'''

xref:023-isaias/023-isaias-061.adoc#v23-61-0[&#60; Capítulo Anterior] | <<v23-62-0,Topo>> | xref:023-isaias/023-isaias-063.adoc#v23-63-0[Próximo Capítulo &#62;]