include::./index.adoc[]

[[v23-22-0]]
=== Isaías, 22
// nvt ?, NVT - Nova Versão Transformadora

[[v23-22-1]]

^<<v23-22-1,1>>^ Recebi esta mensagem acerca de Jerusalém, o vale da Visão: O que está acontecendo? Por que todos correm para os terraços?

[[v23-22-2]]

^<<v23-22-2,2>>^ A cidade inteira está em grande agitação. O que vejo nesta cidade festiva? Há cadáveres por toda parte; não morreram pela espada, nem na batalha.

[[v23-22-3]]

^<<v23-22-3,3>>^ Todos os seus líderes fugiram; renderam-se sem resistir. O povo tentou escapar, mas também foi capturado.

[[v23-22-4]]

^<<v23-22-4,4>>^ Por isso eu disse: "Deixem-me chorar em paz; não tentem me consolar. Deixem-me chorar por meu povo, enquanto vejo sua destruição".

[[v23-22-5]]

^<<v23-22-5,5>>^ Que dia de grande aflição! Que dia de confusão e terror enviado pelo Soberano SENHOR dos Exércitos sobre o vale da Visão! Os muros de Jerusalém foram derrubados; lamentos ressoam das encostas dos montes.

[[v23-22-6]]

^<<v23-22-6,6>>^ Os elamitas são arqueiros, com seus carros e cavaleiros; os homens de Quir levantam os escudos.

[[v23-22-7]]

^<<v23-22-7,7>>^ Carros de guerra enchem seus lindos vales, cavaleiros atacam seus portões.

[[v23-22-8]]

^<<v23-22-8,8>>^ As defesas de Judá foram removidas; vocês correm ao arsenal para pegar suas armas.

[[v23-22-9]]

^<<v23-22-9,9>>^ Inspecionam as brechas nos muros de Jerusalém; guardam água no tanque inferior.

[[v23-22-10]]

^<<v23-22-10,10>>^ Examinam as casas e derrubam algumas; usam suas pedras para reforçar os muros.

[[v23-22-11]]

^<<v23-22-11,11>>^ Entre os muros da cidade constroem um reservatório, para guardar a água do tanque velho. Em nenhum momento, pedem ajuda àquele que fez tudo isso; não levam em conta aquele que há muito planejou essas coisas.

[[v23-22-12]]

^<<v23-22-12,12>>^ Naquele dia, o Soberano SENHOR dos Exércitos, os chamou para que chorassem e lamentassem. Disse-lhes que raspassem a cabeça e vestissem pano de saco.

[[v23-22-13]]

^<<v23-22-13,13>>^ Em vez disso, vocês dançam e brincam; abatem gado e matam ovelhas, comem carne e bebem vinho. Dizem: "Comamos e bebamos, porque amanhã morreremos!".

[[v23-22-14]]

^<<v23-22-14,14>>^ O SENHOR dos Exércitos me revelou o seguinte: "Até o dia em que vocês morrerem, esse terrível pecado não será perdoado. Eu, o Soberano SENHOR dos Exércitos, falei!".

[[v23-22-15]]

^<<v23-22-15,15>>^ O Soberano SENHOR dos Exércitos me disse: "Confronte Sebna, administrador do palácio, e transmita-lhe esta mensagem:

[[v23-22-16]]

^<<v23-22-16,16>>^ "Quem você pensa que é, e o que está fazendo aqui, construindo uma bela sepultura para si, um monumento no alto da rocha?

[[v23-22-17]]

^<<v23-22-17,17>>^ Pois o SENHOR está prestes a lançá-lo para longe, ó homem poderoso! Ele o pegará com firmeza,

[[v23-22-18]]

^<<v23-22-18,18>>^ o embrulhará como uma bola e o atirará para uma terra distante. Você morrerá naquele lugar, e seus gloriosos carros de guerra lá ficarão. Você é uma vergonha para seu senhor!

[[v23-22-19]]

^<<v23-22-19,19>>^ "Sim, eu o expulsarei de seu cargo", diz o SENHOR. "Eu o removerei de sua posição.

[[v23-22-20]]

^<<v23-22-20,20>>^ Então chamarei meu servo Eliaquim, filho de Hilquias, para ocupar seu lugar.

[[v23-22-21]]

^<<v23-22-21,21>>^ Vestirei Eliaquim com as roupas oficiais que você usava e lhe darei seu título e autoridade. Ele será como um pai para o povo de Jerusalém e de Judá.

[[v23-22-22]]

^<<v23-22-22,22>>^ Darei a ele a chave da casa de Davi, o cargo mais elevado da corte. Quando ele abrir portas, ninguém poderá fechá-las; quando fechar portas, ninguém poderá abri-las.

[[v23-22-23]]

^<<v23-22-23,23>>^ Trará honra ao nome de seus familiares, pois o colocarei firmemente no lugar, como um prego na parede.

[[v23-22-24]]

^<<v23-22-24,24>>^ A família toda dependerá dele, e ele honrará até o membro mais humilde de sua casa."

[[v23-22-25]]

^<<v23-22-25,25>>^ Contudo, o SENHOR dos Exércitos também disse: "Chegará o dia em que arrancarei o prego que parecia tão firme. Ele será derrubado e cairá no chão. Tudo que nele se apoia cairá com ele. Eu, o SENHOR, falei!".

'''

xref:023-isaias/023-isaias-021.adoc#v23-21-0[&#60; Capítulo Anterior] | <<v23-22-0,Topo>> | xref:023-isaias/023-isaias-023.adoc#v23-23-0[Próximo Capítulo &#62;]