include::./index.adoc[]

[[v23-47-0]]
=== Isaías, 47
// nvt ?, NVT - Nova Versão Transformadora

[[v23-47-1]]

^<<v23-47-1,1>>^ "Desça, ó Babilônia, e sente-se no pó, pois chegaram ao fim seus dias no trono. A bela Babilônia nunca voltará a ser princesa encantadora e delicada.

[[v23-47-2]]

^<<v23-47-2,2>>^ Pegue as pedras de moer e faça farinha, remova seu véu e tire seu manto; exponha-se à vista de todos.

[[v23-47-3]]

^<<v23-47-3,3>>^ Você ficará nua e envergonhada; eu me vingarei e não terei compaixão."

[[v23-47-4]]

^<<v23-47-4,4>>^ Nosso Redentor, cujo nome é SENHOR dos Exércitos, é o Santo de Israel.

[[v23-47-5]]

^<<v23-47-5,5>>^ "Ó bela Babilônia, sente-se na escuridão e no silêncio; nunca mais será conhecida como rainha de reinos.

[[v23-47-6]]

^<<v23-47-6,6>>^ Pois eu estava irado com meu povo escolhido e, para castigá-los, os entreguei em suas mãos. Mas você não teve compaixão deles e oprimiu até os idosos.

[[v23-47-7]]

^<<v23-47-7,7>>^ Disse: ‘Serei rainha para sempre!’. Não refletiu sobre suas ações, nem pensou nas consequências.

[[v23-47-8]]

^<<v23-47-8,8>>^ "Ouça isto, você que ama o prazer, que vive despreocupada, sentindo-se segura. Você diz: ‘Sou a única, e não há outra; nunca serei viúva nem perderei meus filhos’.

[[v23-47-9]]

^<<v23-47-9,9>>^ Estas duas coisas lhe acontecerão no mesmo instante: ficará viúva e perderá seus filhos. Sim, essas calamidades virão sobre você, apesar de toda a sua feitiçaria e magia.

[[v23-47-10]]

^<<v23-47-10,10>>^ "Sentia-se segura em sua maldade e dizia: ‘Ninguém me vê’. Sua sabedoria e seu conhecimento a enganavam, e pensava: ‘Sou a única, não há outra’.

[[v23-47-11]]

^<<v23-47-11,11>>^ Por isso a desgraça a alcançará, e você não poderá evitá-la com encantamentos. A calamidade cairá sobre você, e não terá como comprar seu livramento. Uma catástrofe a atingirá de repente, e não estará preparada para ela.

[[v23-47-12]]

^<<v23-47-12,12>>^ "Use sua magia! Use os encantamentos a que se dedicou todos esses anos! Talvez eles tenham algum proveito, talvez assustem alguém.

[[v23-47-13]]

^<<v23-47-13,13>>^ Você está cansada de tantos conselhos; onde estão seus astrólogos, que observam as estrelas e fazem previsões todos os meses? Que se levantem e a salvem do que o futuro lhe reserva!

[[v23-47-14]]

^<<v23-47-14,14>>^ Mas eles são como palha que queima no fogo; não podem salvar a si mesmos das chamas. Você não receberá deles ajuda alguma; a fogueira deles não aquece ninguém.

[[v23-47-15]]

^<<v23-47-15,15>>^ Seus amigos, com quem você negociou desde a juventude, seguirão cada um o próprio caminho, e não haverá ninguém que a salve."

'''

xref:023-isaias/023-isaias-046.adoc#v23-46-0[&#60; Capítulo Anterior] | <<v23-47-0,Topo>> | xref:023-isaias/023-isaias-048.adoc#v23-48-0[Próximo Capítulo &#62;]