include::./index.adoc[]

[[v23-24-0]]
=== Isaías, 24
// nvt ?, NVT - Nova Versão Transformadora

[[v23-24-1]]

^<<v23-24-1,1>>^ Vejam, o SENHOR está prestes a destruir a terra e transformá-la num enorme deserto! Ele devasta sua superfície e dispersa seus habitantes.

[[v23-24-2]]

^<<v23-24-2,2>>^ Sacerdotes e povo, servos e senhores, servas e senhoras, os que compram e os que vendem, os que emprestam e os que tomam emprestado, credores e devedores, ninguém será poupado.

[[v23-24-3]]

^<<v23-24-3,3>>^ A terra será completamente esvaziada e saqueada. O SENHOR falou!

[[v23-24-4]]

^<<v23-24-4,4>>^ A terra lamenta e seca, sim, o mundo definha e murcha; até mesmo os mais nobres da terra definham.

[[v23-24-5]]

^<<v23-24-5,5>>^ A terra sofre por causa do pecado de seus habitantes, pois transgrediram as leis de Deus, violaram seus decretos e quebraram sua aliança eterna.

[[v23-24-6]]

^<<v23-24-6,6>>^ Por isso, a maldição consome a terra; seus habitantes pagam por seus pecados. São destruídos pelo fogo, e apenas alguns sobrevivem.

[[v23-24-7]]

^<<v23-24-7,7>>^ O vinho novo seca, e as videiras murcham; os que festejavam agora gemem.

[[v23-24-8]]

^<<v23-24-8,8>>^ O som animado dos tamborins cessou, e já não se ouvem os gritos alegres de celebração; os acordes melodiosos da harpa se calaram.

[[v23-24-9]]

^<<v23-24-9,9>>^ Acabaram-se as alegrias do vinho e das canções; a bebida forte tem gosto amargo.

[[v23-24-10]]

^<<v23-24-10,10>>^ A cidade se contorce em meio ao caos; todas as casas estão trancadas, para que ninguém entre.

[[v23-24-11]]

^<<v23-24-11,11>>^ Nas ruas, multidões clamam por vinho; a alegria se transformou em tristeza, a celebração foi expulsa da terra.

[[v23-24-12]]

^<<v23-24-12,12>>^ A cidade foi deixada em ruínas; seus portões foram despedaçados.

[[v23-24-13]]

^<<v23-24-13,13>>^ Assim é em toda a terra: sobrou apenas um remanescente, como as azeitonas que sobram quando a árvore é sacudida, como as uvas que restam na videira depois da colheita.

[[v23-24-14]]

^<<v23-24-14,14>>^ Mas todos que restaram gritam e cantam de alegria; os que moram no oeste louvam a majestade do SENHOR.

[[v23-24-15]]

^<<v23-24-15,15>>^ Nas terras do leste, deem glória ao SENHOR; nas terras além do mar, louvem o nome do SENHOR, o Deus de Israel!

[[v23-24-16]]

^<<v23-24-16,16>>^ Ouvimos cânticos de louvor desde os confins da terra, cânticos que glorificam o Justo! Meu coração, porém, está pesado de angústia; chorem por mim, pois desfaleço. O engano ainda prevalece; há traição por toda parte.

[[v23-24-17]]

^<<v23-24-17,17>>^ Terror, armadilhas e laços esperam por vocês, habitantes da terra.

[[v23-24-18]]

^<<v23-24-18,18>>^ Os que fogem apavorados cairão numa armadilha; os que escaparem da armadilha serão pegos num laço. Destruição cai dos céus como chuva; os alicerces da terra estremecem.

[[v23-24-19]]

^<<v23-24-19,19>>^ A terra se despedaçou; está totalmente destruída e é sacudida com violência.

[[v23-24-20]]

^<<v23-24-20,20>>^ A terra cambaleia como um bêbado, estremece como uma tenda na tempestade. Cai e não voltará a se levantar, pois a culpa de sua rebelião é pesada demais.

[[v23-24-21]]

^<<v23-24-21,21>>^ Naquele dia, o SENHOR castigará os poderes celestiais nos céus e os governantes das nações na terra.

[[v23-24-22]]

^<<v23-24-22,22>>^ Serão reunidos e presos, trancados na prisão e, por fim, castigados.

[[v23-24-23]]

^<<v23-24-23,23>>^ Então o esplendor da lua minguará, e o brilho do sol se apagará, pois o SENHOR dos Exércitos reinará no monte Sião; reinará com grande glória em Jerusalém, diante das autoridades do povo.

'''

xref:023-isaias/023-isaias-023.adoc#v23-23-0[&#60; Capítulo Anterior] | <<v23-24-0,Topo>> | xref:023-isaias/023-isaias-025.adoc#v23-25-0[Próximo Capítulo &#62;]