include::./index.adoc[]

[[v23-8-0]]
=== Isaías, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v23-8-1]]

^<<v23-8-1,1>>^ Então o SENHOR me disse: "Faça uma grande placa e escreva de modo bem claro o seguinte nome: Maher-Shalal-Hash-Baz".

[[v23-8-2]]

^<<v23-8-2,2>>^ Pedi ao sacerdote Urias e a Zacarias, filho de Jeberequias, dois homens conhecidos por sua honestidade, que fossem testemunhas do que fiz.

[[v23-8-3]]

^<<v23-8-3,3>>^ Então deitei-me com minha esposa, e ela ficou grávida e deu à luz um filho. E o SENHOR disse: "Dê-lhe o nome Maher-Shalal-Hash-Baz.

[[v23-8-4]]

^<<v23-8-4,4>>^ Pois, antes que esse menino tenha idade suficiente para dizer ‘papai’ ou ‘mamãe’, o rei da Assíria levará embora os bens de Damasco e as riquezas de Samaria".

[[v23-8-5]]

^<<v23-8-5,5>>^ Mais uma vez, o SENHOR falou comigo e disse:

[[v23-8-6]]

^<<v23-8-6,6>>^ "Meu cuidado pelo povo de Judá é como as águas de Siloé, que fluem suavemente. Contudo, eles me rejeitaram e agora se alegram com o que acontecerá aos reis Rezim e Peca.

[[v23-8-7]]

^<<v23-8-7,7>>^ Portanto, o Senhor fará vir sobre eles uma grande inundação do rio Eufrates: o rei da Assíria com toda a sua glória. A inundação fará transbordar todos os seus canais

[[v23-8-8]]

^<<v23-8-8,8>>^ e cobrirá Judá até o pescoço. Abrirá as asas e submergirá sua terra de um extremo ao outro, ó Emanuel.

[[v23-8-9]]

^<<v23-8-9,9>>^ "Reúnam-se, nações, e fiquem aterrorizadas; prestem atenção, todas as terras distantes. Preparem-se para a batalha, mas serão destruídas; sim, preparem-se para a batalha, mas serão destruídas.

[[v23-8-10]]

^<<v23-8-10,10>>^ Convoquem conselhos de guerra, mas de nada adiantará; desenvolvam estratégias, mas não terão sucesso. Pois Deus está conosco!"

[[v23-8-11]]

^<<v23-8-11,11>>^ O SENHOR me advertiu firmemente de que não pensasse como todos os outros. Disse ele:

[[v23-8-12]]

^<<v23-8-12,12>>^ "Não chame tudo de conspiração, como eles fazem; não viva com medo do que eles temem.

[[v23-8-13]]

^<<v23-8-13,13>>^ Considere o SENHOR dos Exércitos santo em sua vida; é a ele que você deve temer. Ele é quem deve fazê-lo estremecer;

[[v23-8-14]]

^<<v23-8-14,14>>^ ele o manterá seguro. Mas, para Israel e Judá, ele será pedra de tropeço, rocha que os faz cair. Para o povo de Jerusalém, será armadilha e laço.

[[v23-8-15]]

^<<v23-8-15,15>>^ Muitos tropeçarão e cairão e nunca mais se levantarão; serão presos no laço e capturados".

[[v23-8-16]]

^<<v23-8-16,16>>^ Preserve os ensinamentos de Deus; confie a lei àqueles que me seguem.

[[v23-8-17]]

^<<v23-8-17,17>>^ Esperarei pelo SENHOR, que se afastou dos descendentes de Jacó; porei nele minha esperança.

[[v23-8-18]]

^<<v23-8-18,18>>^ Eu e os filhos que o SENHOR me deu serviremos de sinal e advertência para Israel da parte do SENHOR dos Exércitos, que habita no monte Sião.

[[v23-8-19]]

^<<v23-8-19,19>>^ Talvez alguém lhes diga: "Vamos perguntar aos médiuns e aos que consultam os espíritos dos mortos. Com sussurros e murmúrios eles nos dirão o que fazer". Mas será que o povo não deve pedir orientação a Deus? Será que os vivos devem buscar a orientação de mortos?

[[v23-8-20]]

^<<v23-8-20,20>>^ Consultem a lei e os ensinamentos de Deus! Aqueles que contradizem sua palavra jamais verão a luz.

[[v23-8-21]]

^<<v23-8-21,21>>^ Andam sem rumo, cansados e famintos. E, por causa da fome, amaldiçoam seu rei e seu Deus. Olharão para o céu,

[[v23-8-22]]

^<<v23-8-22,22>>^ depois olharão para a terra, mas para onde voltarem os olhos só haverá problemas, angústia e sombrio desespero. Serão lançados nas trevas.

'''

xref:023-isaias/023-isaias-007.adoc#v23-7-0[&#60; Capítulo Anterior] | <<v23-8-0,Topo>> | xref:023-isaias/023-isaias-009.adoc#v23-9-0[Próximo Capítulo &#62;]