include::./index.adoc[]

[[v23-15-0]]
=== Isaías, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v23-15-1]]

^<<v23-15-1,1>>^ Recebi esta mensagem acerca de Moabe: Em uma só noite, a cidade de Ar será arrasada, e a cidade de Quir, destruída.

[[v23-15-2]]

^<<v23-15-2,2>>^ Seu povo irá ao templo em Dibom para lamentar, aos lugares de culto nos montes para chorar. Chorarão pelo destino de Nebo e Medeba, rasparão a cabeça e cortarão a barba.

[[v23-15-3]]

^<<v23-15-3,3>>^ Vestirão pano de saco e vagarão pelas ruas; de todas as casas e praças públicas virão gemidos de lamento.

[[v23-15-4]]

^<<v23-15-4,4>>^ Os habitantes de Hesbom e Eleale clamarão; suas vozes serão ouvidas até em Jaaz. Os guerreiros mais valentes de Moabe gritarão de terror; indefesos, tremerão de medo.

[[v23-15-5]]

^<<v23-15-5,5>>^ Meu coração chora por Moabe; seus habitantes fogem para Zoar e para Eglate-Selisia. Sobem chorando pelo caminho de Luíte; seus clamores de angústia são ouvidos por toda a estrada de Horonaim.

[[v23-15-6]]

^<<v23-15-6,6>>^ Até as águas de Ninrim secaram; a vegetação às suas margens murchou. As plantas morreram; todo verde desapareceu.

[[v23-15-7]]

^<<v23-15-7,7>>^ O povo reúne seus bens e os carrega para o outro lado do riacho dos Salgueiros.

[[v23-15-8]]

^<<v23-15-8,8>>^ Um clamor de angústia ecoa pela terra de Moabe, de uma extremidade à outra, de Eglaim até Beer-Elim.

[[v23-15-9]]

^<<v23-15-9,9>>^ O riacho perto de Dibom está vermelho de sangue, mas ainda não terminei de castigar Dibom! Leões caçarão os sobreviventes, tanto os que tentarem fugir como os que ficarem para trás.

'''

xref:023-isaias/023-isaias-014.adoc#v23-14-0[&#60; Capítulo Anterior] | <<v23-15-0,Topo>> | xref:023-isaias/023-isaias-016.adoc#v23-16-0[Próximo Capítulo &#62;]