include::./index.adoc[]

[[v23-18-0]]
=== Isaías, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v23-18-1]]

^<<v23-18-1,1>>^ Que aflição espera você, Etiópia, terra de velas tremulantes junto à nascente do Nilo,

[[v23-18-2]]

^<<v23-18-2,2>>^ que envia embaixadores pelo rio em rápidas embarcações! Vão, velozes mensageiros! Levem a mensagem a um povo alto, de pele lisa, temido em toda parte por suas conquistas e destruição, cuja terra é dividida por rios.

[[v23-18-3]]

^<<v23-18-3,3>>^ Todos vocês, povos do mundo, todos os habitantes da terra, olhem quando eu erguer sobre o monte minha bandeira de guerra; ouçam quando eu soar a trombeta!

[[v23-18-4]]

^<<v23-18-4,4>>^ Pois o SENHOR me disse: "Do lugar onde habito observarei quieto, como sobe o calor num dia de verão, como se forma o orvalho da manhã durante a colheita".

[[v23-18-5]]

^<<v23-18-5,5>>^ Antes de começarem a atacar, enquanto seus planos amadurecem como uvas, o SENHOR cortará seus brotos com a podadeira; removerá os ramos que se espalharam e os lançará fora.

[[v23-18-6]]

^<<v23-18-6,6>>^ Seu exército poderoso será deixado morto nos campos, para os abutres dos montes e para os animais selvagens. Abutres despedaçarão os cadáveres no verão, e animais selvagens roerão os ossos no inverno.

[[v23-18-7]]

^<<v23-18-7,7>>^ Naquele tempo, o SENHOR dos Exércitos receberá presentes dessa terra dividida por rios, desse povo alto, de pele lisa, temido em toda parte por suas conquistas e destruição. Levarão presentes ao monte Sião, onde habita o SENHOR dos Exércitos.

'''

xref:023-isaias/023-isaias-017.adoc#v23-17-0[&#60; Capítulo Anterior] | <<v23-18-0,Topo>> | xref:023-isaias/023-isaias-019.adoc#v23-19-0[Próximo Capítulo &#62;]