include::./index.adoc[]

[[v23-23-0]]
=== Isaías, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v23-23-1]]

^<<v23-23-1,1>>^ Recebi esta mensagem acerca de Tiro: Lamentem, navios de Társis, pois o porto e as casas de Tiro foram destruídos! Os boatos que vocês ouviram em Chipre são verdadeiros.

[[v23-23-2]]

^<<v23-23-2,2>>^ Chorem em silêncio, moradores do litoral e comerciantes de Sidom! Seus negociantes atravessavam o mar

[[v23-23-3]]

^<<v23-23-3,3>>^ e navegavam em águas profundas. Traziam-lhe os cereais do Egito e as colheitas do Nilo. Você era o mercado das nações.

[[v23-23-4]]

^<<v23-23-4,4>>^ Agora, porém, será envergonhada, cidade de Sidom, pois Tiro, a fortaleza do mar, diz: "Nunca tive dores de parto nem dei à luz; não tenho filhos nem filhas".

[[v23-23-5]]

^<<v23-23-5,5>>^ Quando o Egito receber a notícia sobre Tiro, haverá grande tristeza.

[[v23-23-6]]

^<<v23-23-6,6>>^ Avisem Társis! Lamentem, moradores do litoral!

[[v23-23-7]]

^<<v23-23-7,7>>^ Essas ruínas são tudo que resta de sua cidade antes tão alegre? Como foi longa sua história! Quantos colonizadores enviaram para lugares distantes!

[[v23-23-8]]

^<<v23-23-8,8>>^ Quem trouxe essa calamidade sobre Tiro, a grande fundadora de reinos? Seus comerciantes eram todos príncipes, seus negociantes eram os nobres da terra.

[[v23-23-9]]

^<<v23-23-9,9>>^ O SENHOR dos Exércitos fez isso para acabar com seu orgulho, para rebaixar os nobres da terra.

[[v23-23-10]]

^<<v23-23-10,10>>^ Venham, habitantes de Társis, percorram a terra como faz o Nilo, pois Tiro está indefesa.

[[v23-23-11]]

^<<v23-23-11,11>>^ O SENHOR estendeu a mão sobre o mar e sacudiu os reinos da terra. Pronunciou-se contra a Fenícia e ordenou que suas fortalezas fossem destruídas.

[[v23-23-12]]

^<<v23-23-12,12>>^ Disse: "Você nunca mais se alegrará, ó filha de Sidom, pois foi esmagada. Mesmo que fuja para Chipre, não encontrará descanso".

[[v23-23-13]]

^<<v23-23-13,13>>^ Olhem para a terra da Babilônia; seu povo não existe mais! Os assírios entregaram a Babilônia aos animais selvagens do deserto. Construíram rampas de ataque junto a seus muros, demoliram seus palácios e transformaram a cidade num monte de ruínas.

[[v23-23-14]]

^<<v23-23-14,14>>^ Lamentem, navios de Társis, pois seu porto está destruído!

[[v23-23-15]]

^<<v23-23-15,15>>^ Durante setenta anos, o tempo de vida de um rei, Tiro ficará esquecida. Depois disso, porém, a cidade voltará à vida, como na canção sobre a prostituta:

[[v23-23-16]]

^<<v23-23-16,16>>^ Pegue a harpa e ande pelas ruas, ó prostituta esquecida. Cante uma doce melodia e entoe suas canções, para que voltem a lembrar-se de você.

[[v23-23-17]]

^<<v23-23-17,17>>^ Depois de setenta anos, o SENHOR fará Tiro renascer. Contudo, não será diferente do que era antes. Voltará a ser prostituta de todos os reinos do mundo.

[[v23-23-18]]

^<<v23-23-18,18>>^ No final, porém, seu lucro será entregue ao SENHOR. Suas riquezas não serão acumuladas, mas proverão comida farta e roupas finas para os servos do SENHOR.

'''

xref:023-isaias/023-isaias-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaias/023-isaias-024.adoc#v23-24-0[Próximo Capítulo &#62;]