include::./index.adoc[]

[[v23-66-0]]
=== Isaías, 66
// nvt ?, NVT - Nova Versão Transformadora

[[v23-66-1]]

^<<v23-66-1,1>>^ Assim diz o SENHOR: "O céu é meu trono, e a terra é o suporte de meus pés. Acaso construiriam para mim um templo assim tão bom? Que lugar de descanso me poderiam fazer?

[[v23-66-2]]

^<<v23-66-2,2>>^ Minhas mãos criaram os céus e a terra; eles e tudo que neles há são meus. Eu, o SENHOR, falei! "Abençoarei os de coração humilde e oprimido, os que tremem diante de minha palavra.

[[v23-66-3]]

^<<v23-66-3,3>>^ Quanto aos que escolhem seguir os próprios caminhos, que têm prazer em seus pecados detestáveis, não aceitarei suas ofertas. Quando oferecem um boi, é tão inaceitável quanto um sacrifício humano. Quando sacrificam um cordeiro, é como se tivessem oferecido um cão. Quando trazem uma oferta de cereal, é como uma oferta de sangue de porco. Quando queimam incenso, é como se tivessem abençoado um ídolo.

[[v23-66-4]]

^<<v23-66-4,4>>^ Enviarei sobre eles grande aflição, tudo que mais temem. Pois, quando chamei, não responderam; quando falei, não ouviram. Praticaram o mal, bem diante dos meus olhos, e escolheram fazer o que desprezo".

[[v23-66-5]]

^<<v23-66-5,5>>^ Ouçam esta mensagem do SENHOR, todos vocês que tremem diante de suas palavras: "Seu próprio povo os odeia e os expulsa porque são leais ao meu nome. Zombam: ‘Que o SENHOR seja glorificado! Alegrem-se nele!’, mas eles serão envergonhados.

[[v23-66-6]]

^<<v23-66-6,6>>^ Que tumulto é esse na cidade? Que barulho é esse que vem do templo? É a voz do SENHOR, vingando-se de seus inimigos.

[[v23-66-7]]

^<<v23-66-7,7>>^ "Antes mesmo que comecem as dores de parto, Jerusalém dá à luz um filho.

[[v23-66-8]]

^<<v23-66-8,8>>^ Quem ouviu falar de algo tão estranho? Quem viu uma coisa dessas? Acaso algum país nasceu em um só dia? Alguma nação veio a existir num instante? Mas, quando começarem as dores de parto de Sião, seus filhos já terão nascido.

[[v23-66-9]]

^<<v23-66-9,9>>^ Acaso eu levaria esta nação à hora do parto e não a faria nascer?", diz o SENHOR. "Não! Jamais a impediria de nascer", diz o seu Deus.

[[v23-66-10]]

^<<v23-66-10,10>>^ "Alegrem-se com Jerusalém! Exultem por ela, todos que a amam e todos que por ela choraram!

[[v23-66-11]]

^<<v23-66-11,11>>^ Bebam de sua glória até se fartarem, como a criancinha mama e é confortada no seio da mãe."

[[v23-66-12]]

^<<v23-66-12,12>>^ Assim diz o SENHOR: "Darei a Jerusalém um rio de paz e prosperidade; as riquezas das nações fluirão para ela. Seus filhos serão amamentados em seus seios, levados em seus braços e acalentados em seus joelhos.

[[v23-66-13]]

^<<v23-66-13,13>>^ Eu os consolarei em Jerusalém, como a mãe consola seu filho".

[[v23-66-14]]

^<<v23-66-14,14>>^ Quando virem essas coisas, seu coração se alegrará; vocês florescerão como uma planta viçosa! Todos verão a mão do SENHOR abençoar seus servos e sua ira pesar contra seus inimigos.

[[v23-66-15]]

^<<v23-66-15,15>>^ Vejam, o SENHOR vem com fogo, e seus carros de guerra são velozes como um vendaval. Trará castigo com a fúria de sua ira e com o fogo ardente de sua repreensão.

[[v23-66-16]]

^<<v23-66-16,16>>^ O SENHOR julgará o mundo com fogo e sua espada, e muitos serão mortos por ele.

[[v23-66-17]]

^<<v23-66-17,17>>^ "Os que se consagram e se purificam num jardim sagrado com um ídolo no centro, que comem carne de porco e de rato e outras carnes detestáveis, terão um fim terrível", diz o SENHOR.

[[v23-66-18]]

^<<v23-66-18,18>>^ "Eu vejo o que fazem e sei o que pensam. Por isso, reunirei todas as nações e todos os povos, e eles verão minha glória.

[[v23-66-19]]

^<<v23-66-19,19>>^ Realizarei um sinal no meio deles. Enviarei os sobreviventes como mensageiros às nações: a Társis, aos líbios, aos lídios (flecheiros famosos), a Tubal e à Grécia e a todas as terras além do mar que não ouviram falar de minha fama nem viram minha glória. Ali, anunciarão minha glória às nações.

[[v23-66-20]]

^<<v23-66-20,20>>^ Trarão de volta das nações os remanescentes do povo e os levarão ao meu santo monte em Jerusalém, como se fossem ofertas de cereais levadas ao templo do SENHOR. Virão em cavalos, em carruagens e em carroças, em mulas e em camelos", diz o SENHOR.

[[v23-66-21]]

^<<v23-66-21,21>>^ "E eu nomearei alguns deles para serem meus sacerdotes e levitas. Eu, o SENHOR, falei!

[[v23-66-22]]

^<<v23-66-22,22>>^ "Tão certo como meus novos céus e minha nova terra permanecerão, vocês sempre serão meu povo, com um nome que jamais desaparecerá", diz o SENHOR.

[[v23-66-23]]

^<<v23-66-23,23>>^ "Toda a humanidade virá me adorar uma semana após a outra, um mês após o outro.

[[v23-66-24]]

^<<v23-66-24,24>>^ Quando saírem, verão os cadáveres dos que se rebelaram contra mim. Pois os vermes que os devoram nunca morrerão, e o fogo que os queima nunca se apagará. Todos que passarem por ali os verão com o mais absoluto horror."

'''

xref:023-isaias/023-isaias-065.adoc#v23-65-0[&#60; Capítulo Anterior] | <<v23-66-0,Topo>> | xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[Próximo Capítulo &#62;]