include::./index.adoc[]

[[v23-43-0]]
=== Isaías, 43
// nvt ?, NVT - Nova Versão Transformadora

[[v23-43-1]]

^<<v23-43-1,1>>^ Mas agora, ó Jacó, ouça o SENHOR que o criou; ó Israel, assim diz aquele que o formou: "Não tema, pois eu o resgatei; eu o chamei pelo nome, você é meu.

[[v23-43-2]]

^<<v23-43-2,2>>^ Quando passar por águas profundas, estarei a seu lado. Quando atravessar rios, não se afogará. Quando passar pelo fogo, não se queimará; as chamas não lhe farão mal.

[[v23-43-3]]

^<<v23-43-3,3>>^ Pois eu sou o SENHOR, seu Deus, o Santo de Israel, seu Salvador. Dei o Egito como resgate por sua liberdade; em troca de você, dei a Etiópia e Sebá.

[[v23-43-4]]

^<<v23-43-4,4>>^ Outros foram entregues em seu lugar, troquei a vida deles pela sua. Pois você é precioso para mim, é honrado e eu o amo.

[[v23-43-5]]

^<<v23-43-5,5>>^ "Não tema, pois estou com você; reunirei você e seus descendentes desde o leste e o oeste.

[[v23-43-6]]

^<<v23-43-6,6>>^ Direi ao norte e ao sul: ‘Tragam de volta meus filhos e filhas, desde os confins da terra.

[[v23-43-7]]

^<<v23-43-7,7>>^ Tragam todos que me reconhecem como seu Deus, pois eu os criei para minha glória; fui eu quem os formou’".

[[v23-43-8]]

^<<v23-43-8,8>>^ Tragam o povo que tem olhos, mas é cego, que tem ouvidos, mas é surdo.

[[v23-43-9]]

^<<v23-43-9,9>>^ Reúnam as nações! Juntem os povos do mundo! Qual de seus ídolos predisse coisas semelhantes a estas? Qual deles pode prever o que acontecerá amanhã? Onde estão as testemunhas dessas previsões? Quem pode comprovar que disseram a verdade?

[[v23-43-10]]

^<<v23-43-10,10>>^ "Você é minha testemunha, ó Israel!", diz o SENHOR. "Você é meu servo. Foi escolhido para me conhecer, para crer em mim, para entender que somente eu sou Deus. Não há outro Deus, nunca houve e nunca haverá.

[[v23-43-11]]

^<<v23-43-11,11>>^ Eu, somente eu, sou o SENHOR, e não há outro Salvador.

[[v23-43-12]]

^<<v23-43-12,12>>^ Primeiro, previ sua salvação, então o salvei e proclamei isso ao mundo. Nenhum deus estrangeiro jamais fez algo assim; você, Israel, é testemunha de que sou o único Deus", diz o SENHOR.

[[v23-43-13]]

^<<v23-43-13,13>>^ "Desde a eternidade, eu sou Deus; não há quem possa livrar alguém de minha mão, não há quem possa desfazer o que eu fiz."

[[v23-43-14]]

^<<v23-43-14,14>>^ Assim diz o SENHOR, seu Redentor, o Santo de Israel: "Por sua causa, enviarei um exército contra a Babilônia; obrigarei os babilônios a fugir nos navios de que tanto se orgulham.

[[v23-43-15]]

^<<v23-43-15,15>>^ Eu sou o SENHOR, seu Santo, Criador e Rei de Israel.

[[v23-43-16]]

^<<v23-43-16,16>>^ Eu sou o SENHOR, que abriu uma passagem no meio das águas, um caminho seco pelo mar.

[[v23-43-17]]

^<<v23-43-17,17>>^ Chamei o exército poderoso do Egito, com seus carros e cavalos. Eu os submergi nas ondas, e eles se afogaram; sua vida se apagou como um pavio fumegante.

[[v23-43-18]]

^<<v23-43-18,18>>^ "Esqueçam tudo isso, não é nada comparado ao que vou fazer.

[[v23-43-19]]

^<<v23-43-19,19>>^ Pois estou prestes a realizar algo novo. Vejam, já comecei! Não percebem? Abrirei um caminho no meio do deserto, farei rios na terra seca.

[[v23-43-20]]

^<<v23-43-20,20>>^ Os animais selvagens nos campos me glorificarão, e também os chacais e as corujas, por lhes dar água no deserto. Sim, farei rios na terra seca, para que meu povo escolhido se refresque.

[[v23-43-21]]

^<<v23-43-21,21>>^ Formei este povo para mim mesmo; um dia, ele me honrará perante o mundo.

[[v23-43-22]]

^<<v23-43-22,22>>^ "Mas você, ó Jacó, não clama por mim; você se cansou de mim, ó Israel!

[[v23-43-23]]

^<<v23-43-23,23>>^ Não me trouxe ovelhas nem bodes para holocaustos, não me honrou com sacrifícios, embora eu não o tenha sobrecarregado nem cansado com exigências de ofertas de cereal e incenso.

[[v23-43-24]]

^<<v23-43-24,24>>^ Você não me trouxe cálamo perfumado, nem me agradou com a gordura de sacrifícios. Em vez disso, me sobrecarregou com seus pecados e me cansou com suas maldades.

[[v23-43-25]]

^<<v23-43-25,25>>^ "Eu, somente eu, por minha própria causa, apagarei seus pecados e nunca mais voltarei a pensar neles.

[[v23-43-26]]

^<<v23-43-26,26>>^ Relembremos juntos a situação, apresente sua defesa para provar inocência.

[[v23-43-27]]

^<<v23-43-27,27>>^ Desde o princípio, seu primeiro antepassado pecou, e seus líderes se rebelaram contra mim.

[[v23-43-28]]

^<<v23-43-28,28>>^ Por isso, humilhei seus sacerdotes; decretei destruição total para Jacó, vergonha para Israel."

'''

xref:023-isaias/023-isaias-042.adoc#v23-42-0[&#60; Capítulo Anterior] | <<v23-43-0,Topo>> | xref:023-isaias/023-isaias-044.adoc#v23-44-0[Próximo Capítulo &#62;]