include::./index.adoc[]

[[v23-30-0]]
=== Isaías, 30
// nvt ?, NVT - Nova Versão Transformadora

[[v23-30-1]]

^<<v23-30-1,1>>^ "Que aflição espera meus filhos rebeldes!", diz o SENHOR. "Vocês fazem planos contrários aos meus, acordos não dirigidos por mim; com isso, amontoam pecado sobre pecado.

[[v23-30-2]]

^<<v23-30-2,2>>^ Pois, sem me consultar, desceram ao Egito em busca de ajuda. Puseram sua confiança na proteção do faraó; tentaram esconder-se na sombra dele.

[[v23-30-3]]

^<<v23-30-3,3>>^ Mas, ao confiar no faraó, serão envergonhados; ao esconder-se nele, serão humilhados.

[[v23-30-4]]

^<<v23-30-4,4>>^ Pois, embora o poder dele se estenda até Zoã, e seus embaixadores tenham chegado a Hanes,

[[v23-30-5]]

^<<v23-30-5,5>>^ todos que confiam nele serão envergonhados; ele de nada os ajudará, mas sim lhes trará humilhação e desonra."

[[v23-30-6]]

^<<v23-30-6,6>>^ Recebi esta mensagem acerca dos animais do Neguebe: As caravanas se movem lentamente pelo terrível deserto, lugar de leoas e leões, de serpentes e cobras venenosas. Seguem em direção ao Egito, com jumentos carregados de riquezas, camelos levando muitos tesouros, pagamentos em troca de proteção. O Egito nada dará como retribuição;

[[v23-30-7]]

^<<v23-30-7,7>>^ as promessas do Egito não têm valor algum! Por isso eu o chamo de Raabe, o Dragão Inofensivo.

[[v23-30-8]]

^<<v23-30-8,8>>^ Agora vá e escreva estas palavras; registre-as num livro. Elas permanecerão até o fim dos tempos como testemunha

[[v23-30-9]]

^<<v23-30-9,9>>^ de que esse povo é rebelde e teimoso e se recusa a ouvir a lei do SENHOR.

[[v23-30-10]]

^<<v23-30-10,10>>^ Dizem aos videntes: "Não tenham mais visões!", e aos profetas: "Não nos digam o que é certo. Falem de coisas agradáveis, contem-nos mentiras.

[[v23-30-11]]

^<<v23-30-11,11>>^ Esqueçam a verdade, saiam do caminho estreito. Parem de nos falar do Santo de Israel".

[[v23-30-12]]

^<<v23-30-12,12>>^ Esta é a resposta do Santo de Israel: "Porque desprezam o que lhes digo e preferem confiar em opressão e mentiras,

[[v23-30-13]]

^<<v23-30-13,13>>^ a calamidade virá sobre vocês de repente, como um muro inclinado que se rompe e desmorona. Num instante desabará e cairá por terra.

[[v23-30-14]]

^<<v23-30-14,14>>^ Serão despedaçados como vasilha de barro, esmigalhados tão completamente que não sobrará um caco grande o suficiente para tirar brasas da lareira ou um pouco de água do poço".

[[v23-30-15]]

^<<v23-30-15,15>>^ Assim diz o SENHOR Soberano, o Santo de Israel: "Vocês só serão salvos se voltarem para mim e em mim descansarem. Na tranquilidade e na confiança está sua força, mas vocês não quiseram saber.

[[v23-30-16]]

^<<v23-30-16,16>>^ Disseram: ‘Nada disso! Entraremos na batalha, montados em cavalos velozes’. A única velocidade que verão, porém, será a de seus inimigos os perseguindo!

[[v23-30-17]]

^<<v23-30-17,17>>^ Cada um deles perseguirá mil de vocês; cinco deles farão todos vocês fugirem. Serão deixados como mastro solitário numa colina, como bandeira no alto de um monte distante".

[[v23-30-18]]

^<<v23-30-18,18>>^ Portanto, o SENHOR esperará até que voltem para ele, para lhes mostrar seu amor e compaixão. Pois o SENHOR é Deus fiel; felizes os que nele esperam.

[[v23-30-19]]

^<<v23-30-19,19>>^ Ó povo de Sião, que mora em Jerusalém, você não chorará mais! Ele será bondoso quando lhe pedirem ajuda; certamente atenderá a seus clamores.

[[v23-30-20]]

^<<v23-30-20,20>>^ Embora o Senhor lhes tenha dado angústia como alimento e aflição como bebida, ele permanecerá com vocês para lhes ensinar. Vocês verão seu mestre com os próprios olhos,

[[v23-30-21]]

^<<v23-30-21,21>>^ e seus ouvidos o ouvirão. Uma voz atrás de vocês dirá: "Este é o caminho pelo qual devem andar", quer se voltem para a direita, quer para a esquerda.

[[v23-30-22]]

^<<v23-30-22,22>>^ Então vocês destruirão todos os seus ídolos de prata e suas valiosas imagens de ouro. Jogarão tudo fora como se fossem trapos imundos e dirão: "Já vai tarde!".

[[v23-30-23]]

^<<v23-30-23,23>>^ Então o SENHOR os abençoará com chuva na época de plantar. Terão colheitas fartas e muita pastagem para seus animais.

[[v23-30-24]]

^<<v23-30-24,24>>^ Os bois e os jumentos que lavram a terra comerão cereais de boa qualidade, e o vento levará a palha.

[[v23-30-25]]

^<<v23-30-25,25>>^ No dia em que seus inimigos forem massacrados e as torres caírem, haverá riachos correndo em todos os montes e colinas.

[[v23-30-26]]

^<<v23-30-26,26>>^ A lua será tão brilhante quanto o sol, e o sol será sete vezes mais claro, como a luz de sete dias em um só! Assim será quando o SENHOR começar a sarar seu povo e a curar as feridas que lhe causou.

[[v23-30-27]]

^<<v23-30-27,27>>^ Vejam, o SENHOR vem de longe, ardendo de ira, cercado de densas nuvens de fumaça! Seus lábios estão cheios de fúria, suas palavras consomem como fogo.

[[v23-30-28]]

^<<v23-30-28,28>>^ Seu sopro é como inundação que sobe até o pescoço de seus inimigos. Com sua peneira, separará as nações para a destruição; colocará nelas um freio e as levará à ruína.

[[v23-30-29]]

^<<v23-30-29,29>>^ Mas vocês entoarão um cântico de alegria, como os cânticos das festas sagradas. Vocês se alegrarão, como quando o flautista conduz um grupo de peregrinos a Jerusalém, o monte do SENHOR, a Rocha de Israel.

[[v23-30-30]]

^<<v23-30-30,30>>^ O SENHOR fará ouvir sua voz majestosa e mostrará a força de seu braço poderoso. Em sua ira, descerá com chamas devoradoras, chuvas torrenciais, tempestades e pedras de granizo.

[[v23-30-31]]

^<<v23-30-31,31>>^ Por ordem do SENHOR, os assírios serão despedaçados; ele os ferirá mortalmente com seu cetro.

[[v23-30-32]]

^<<v23-30-32,32>>^ Quando o SENHOR os ferir com sua vara de castigo, seu povo celebrará com tamborins e harpas. Ele levantará seu braço poderoso e lutará contra seus inimigos.

[[v23-30-33]]

^<<v23-30-33,33>>^ Tofete, o lugar de fogo, há muito está pronto para o rei assírio; um monte de lenha aguarda sobre a fogueira. O sopro do SENHOR, como fogo de um vulcão, a acenderá.

'''

xref:023-isaias/023-isaias-029.adoc#v23-29-0[&#60; Capítulo Anterior] | <<v23-30-0,Topo>> | xref:023-isaias/023-isaias-031.adoc#v23-31-0[Próximo Capítulo &#62;]