include::./index.adoc[]

[[v23-37-0]]
=== Isaías, 37
// nvt ?, NVT - Nova Versão Transformadora

[[v23-37-1]]

^<<v23-37-1,1>>^ Quando o rei Ezequias ouviu esse relato, rasgou as roupas, vestiu-se com panos de saco e entrou no templo do SENHOR.

[[v23-37-2]]

^<<v23-37-2,2>>^ Enviou Eliaquim, o administrador do palácio, Sebna, o secretário da corte, e os principais sacerdotes, todos vestidos com panos de saco, ao profeta Isaías, filho de Amoz.

[[v23-37-3]]

^<<v23-37-3,3>>^ Eles lhe disseram: "Assim diz o rei Ezequias: ‘Hoje é um dia de angústia, insulto e humilhação. É como quando a criança está prestes a nascer, mas a mãe não tem forças para dar à luz.

[[v23-37-4]]

^<<v23-37-4,4>>^ Contudo, talvez o SENHOR, seu Deus, tenha ouvido o porta-voz que o rei da Assíria enviou para desafiar o Deus vivo e o castigue por suas palavras. Por favor, ore por nós que restamos!’".

[[v23-37-5]]

^<<v23-37-5,5>>^ Depois que os oficiais do rei Ezequias transmitiram a mensagem ao profeta Isaías,

[[v23-37-6]]

^<<v23-37-6,6>>^ ele respondeu: "Digam ao rei que assim diz o SENHOR: ‘Não se assuste com os insultos que os mensageiros do rei da Assíria lançaram contra mim.

[[v23-37-7]]

^<<v23-37-7,7>>^ Ouça! Eu mesmo agirei contra o rei da Assíria, e ele receberá notícias que o farão voltar para sua terra. Ali eu providenciarei que ele seja morto à espada’".

[[v23-37-8]]

^<<v23-37-8,8>>^ Enquanto isso, o porta-voz partiu de Jerusalém e foi consultar o rei da Assíria, pois tinha sido informado de que o rei havia deixado Laquis e estava atacando Libna.

[[v23-37-9]]

^<<v23-37-9,9>>^ Logo depois, o rei Senaqueribe recebeu a notícia de que Tiraca, rei da Etiópia, havia saído com seu exército para lutar contra ele. Então enviou seus homens de volta a Ezequias em Jerusalém com a seguinte mensagem:

[[v23-37-10]]

^<<v23-37-10,10>>^ "Esta é uma mensagem para Ezequias, rei de Judá. Não deixe que seu Deus, em quem você confia, o engane com promessas de que Jerusalém não será conquistada pelo rei da Assíria.

[[v23-37-11]]

^<<v23-37-11,11>>^ Você sabe muito bem o que os reis da Assíria fizeram por onde passaram. Destruíram completamente todos que atravessaram seu caminho! Quem é você para escapar?

[[v23-37-12]]

^<<v23-37-12,12>>^ Acaso os deuses de outras nações, como Gozã, Harã, Rezefe, e o povo de Éden, que estava em Telassar, as livraram? Meus antecessores destruíram todos eles!

[[v23-37-13]]

^<<v23-37-13,13>>^ O que aconteceu ao rei de Hamate e ao rei de Arpade? O que aconteceu aos reis de Sefarvaim, de Hena e de Iva?".

[[v23-37-14]]

^<<v23-37-14,14>>^ Depois que Ezequias recebeu a carta dos mensageiros e a leu, subiu ao templo do SENHOR e a estendeu diante do SENHOR.

[[v23-37-15]]

^<<v23-37-15,15>>^ Então Ezequias fez esta oração na presença do SENHOR:

[[v23-37-16]]

^<<v23-37-16,16>>^ "Ó SENHOR dos Exércitos, o Deus de Israel, que estás entronizado entre os querubins! Só tu és Deus de todos os reinos da terra. Sim, tu criaste os céus e a terra.

[[v23-37-17]]

^<<v23-37-17,17>>^ Inclina teus ouvidos, ó SENHOR, e ouve! Abre teus olhos, ó SENHOR, e vê! Ouve as palavras com as quais Senaqueribe desafia o Deus vivo!

[[v23-37-18]]

^<<v23-37-18,18>>^ "É verdade, SENHOR, que os reis da Assíria destruíram todas essas nações.

[[v23-37-19]]

^<<v23-37-19,19>>^ Lançaram os deuses dessas nações no fogo e os queimaram. É claro que os assírios conseguiram destruí-los! Não eram deuses de verdade, mas apenas ídolos de madeira e pedra moldados por mãos humanas.

[[v23-37-20]]

^<<v23-37-20,20>>^ Agora, SENHOR, nosso Deus, salva-nos do poder desse rei; então todos os reinos da terra saberão que somente tu, SENHOR, és Deus".

[[v23-37-21]]

^<<v23-37-21,21>>^ Então Isaías, filho de Amoz, enviou esta mensagem a Ezequias: "Assim diz o SENHOR, o Deus de Israel: Visto que você orou a mim a respeito de Senaqueribe, rei da Assíria,

[[v23-37-22]]

^<<v23-37-22,22>>^ o SENHOR proferiu esta palavra contra ele: "A filha virgem de Sião o despreza e ri de você. A filha de Jerusalém balança a cabeça com desdém enquanto você foge.

[[v23-37-23]]

^<<v23-37-23,23>>^ "A quem você desafiou e de quem zombou? Contra quem levantou a voz? Para quem olhou com arrogância? Para o Santo de Israel!

[[v23-37-24]]

^<<v23-37-24,24>>^ Por meio de seus mensageiros, desafiou o Senhor. Disse: ‘Com meus numerosos carros de guerra, conquistei os montes mais elevados, sim, os picos mais remotos do Líbano. Cortei seus cedros mais altos e seus melhores ciprestes. Cheguei a suas maiores alturas e explorei suas florestas mais densas.

[[v23-37-25]]

^<<v23-37-25,25>>^ Cavei poços em muitas terras estrangeiras e me refresquei com sua água. Com a sola de meu pé, sequei todos os rios do Egito!’.

[[v23-37-26]]

^<<v23-37-26,26>>^ "Mas você não sabe? Eu decidi tudo isso há muito tempo. Planejei essas coisas no passado distante, e agora as realizo. Planejei que você transformaria cidades fortificadas em montes de escombros.

[[v23-37-27]]

^<<v23-37-27,27>>^ Por isso, seus habitantes perdem as forças e ficam assustados e envergonhados. São frágeis como a relva, indefesos como brotos verdes e tenros. São como capim que surge no telhado, queimado antes de crescer.

[[v23-37-28]]

^<<v23-37-28,28>>^ "Mas eu o conheço bem; sei onde está e sei de suas idas e vindas; sei como se enfureceu contra mim.

[[v23-37-29]]

^<<v23-37-29,29>>^ E, por causa de sua raiva contra mim e de sua arrogância, que eu mesmo ouvi, porei minha argola em seu nariz e meu freio em sua boca. Eu o farei voltar pelo mesmo caminho por onde veio".

[[v23-37-30]]

^<<v23-37-30,30>>^ Então Isaías disse a Ezequias: "Esta é a prova de que minhas palavras são verdadeiras: "Neste ano vocês comerão somente o que crescer por si, e no ano seguinte, o que brotar disso. Mas, no terceiro ano, semeiem e colham, cuidem de suas videiras e comam de seus frutos.

[[v23-37-31]]

^<<v23-37-31,31>>^ Vocês que restarem em Judá, os que escaparem da destruição, lançarão raízes em seu próprio solo, crescerão e darão frutos.

[[v23-37-32]]

^<<v23-37-32,32>>^ Pois um remanescente de meu povo sairá de Jerusalém, um grupo de sobreviventes partirá do monte Sião. O zelo do SENHOR dos Exércitos fará que isso aconteça!

[[v23-37-33]]

^<<v23-37-33,33>>^ "E assim diz o SENHOR a respeito do rei da Assíria: "Seus exércitos não entrarão em Jerusalém, nem dispararão contra ela uma só flecha. Não marcharão com escudos fora de seus portões, nem construirão rampas de terra contra seus muros.

[[v23-37-34]]

^<<v23-37-34,34>>^ O rei voltará à terra dele pelo mesmo caminho por onde veio. Não entrará na cidade diz o SENHOR.

[[v23-37-35]]

^<<v23-37-35,35>>^ Por minha própria honra e por causa de meu servo Davi, defenderei esta cidade e a libertarei".

[[v23-37-36]]

^<<v23-37-36,36>>^ Naquela noite, o anjo do SENHOR foi ao acampamento assírio e matou 185 mil soldados assírios. Quando os sobreviventes acordaram na manhã seguinte, encontraram cadáveres por toda parte.

[[v23-37-37]]

^<<v23-37-37,37>>^ Então Senaqueribe, rei da Assíria, levantou acampamento e partiu para sua terra. Voltou para Nínive e ali ficou.

[[v23-37-38]]

^<<v23-37-38,38>>^ Certo dia, enquanto ele adorava no templo de seu deus Nisroque, seus filhos Adrameleque e Sarezer o mataram à espada. Fugiram para a terra de Arate, e outro filho, Esar-Hadom, se tornou seu sucessor na Assíria.

'''

xref:023-isaias/023-isaias-036.adoc#v23-36-0[&#60; Capítulo Anterior] | <<v23-37-0,Topo>> | xref:023-isaias/023-isaias-038.adoc#v23-38-0[Próximo Capítulo &#62;]