include::./index.adoc[]

[[v23-49-0]]
=== Isaías, 49
// nvt ?, NVT - Nova Versão Transformadora

[[v23-49-1]]

^<<v23-49-1,1>>^ Ouçam-me, vocês em terras distantes! Prestem atenção, vocês que estão longe! O SENHOR me chamou antes de meu nascimento; desde o ventre ele me chamou pelo nome.

[[v23-49-2]]

^<<v23-49-2,2>>^ Tornou minhas palavras de juízo afiadas como espada, escondeu-me na sombra de sua mão; sou como flecha afiada em sua aljava.

[[v23-49-3]]

^<<v23-49-3,3>>^ Ele me disse: "Você é meu servo, Israel, e me trará glória".

[[v23-49-4]]

^<<v23-49-4,4>>^ Respondi: "Mas meu trabalho parece tão inútil! Esforcei-me em vão, sem propósito algum. No entanto, deixo tudo nas mãos do SENHOR; confio que Deus me recompensará".

[[v23-49-5]]

^<<v23-49-5,5>>^ Agora, fala o SENHOR, aquele que no ventre me formou para ser seu servo, que me encarregou de trazer Israel de volta para ele. O SENHOR me honrou, meu Deus me fortaleceu.

[[v23-49-6]]

^<<v23-49-6,6>>^ Ele diz: "Você fará mais que restaurar o povo de Israel para mim; eu o farei luz para os gentios, e você levará minha salvação aos confins da terra".

[[v23-49-7]]

^<<v23-49-7,7>>^ O SENHOR, o Redentor e o Santo de Israel, diz àquele que é desprezado e rejeitado pelas nações, àquele que é servo dos governantes: "Reis se levantarão quando você passar, príncipes se curvarão até o chão, por causa do SENHOR, que é fiel, por causa do Santo de Israel, que o escolheu".

[[v23-49-8]]

^<<v23-49-8,8>>^ Assim diz o SENHOR: "No tempo certo, eu lhe responderei; no dia da salvação, o ajudarei. Eu o protegerei e o darei ao povo, para que seja símbolo da minha aliança com eles. Por seu intermédio, restabelecerei a terra de Israel e a devolverei a seu povo.

[[v23-49-9]]

^<<v23-49-9,9>>^ Direi aos prisioneiros: ‘Saiam em liberdade!’, e aos que estão na escuridão: ‘Venham para a luz!’. Serão minhas ovelhas e se alimentarão em pastos verdes e nas colinas que antes eram estéreis.

[[v23-49-10]]

^<<v23-49-10,10>>^ Não terão fome nem sede, e o sol ardente não os atingirá. Pois o SENHOR, em sua misericórdia, os guiará; ele os conduzirá a águas frescas.

[[v23-49-11]]

^<<v23-49-11,11>>^ Transformará os montes em caminhos planos, e as estradas serão erguidas acima dos vales.

[[v23-49-12]]

^<<v23-49-12,12>>^ Vejam, meu povo retornará de longe, de terras ao norte e a oeste, e de lugares distantes ao sul, como o Egito".

[[v23-49-13]]

^<<v23-49-13,13>>^ Cantem, ó céus! Alegre-se, ó terra! Irrompam em cânticos, ó montes! Pois o SENHOR consolou seu povo e terá compaixão dele em meio ao sofrimento.

[[v23-49-14]]

^<<v23-49-14,14>>^ Sião, porém, diz: "O SENHOR nos abandonou, o Senhor se esqueceu de nós".

[[v23-49-15]]

^<<v23-49-15,15>>^ "Pode a mãe se esquecer do filho que ainda mama? Pode deixar de sentir amor pelo filho que ela deu à luz? Mesmo que isso fosse possível, eu não me esqueceria de vocês!

[[v23-49-16]]

^<<v23-49-16,16>>^ Vejam, escrevi seu nome na palma de minhas mãos; seus muros em ruínas estão sempre em minha mente.

[[v23-49-17]]

^<<v23-49-17,17>>^ Em breve, seus descendentes voltarão, e todos que procuram destruí-la irão embora.

[[v23-49-18]]

^<<v23-49-18,18>>^ Olhe ao redor e veja, pois todos os seus filhos voltarão para você. Tão certo como eu vivo", diz o SENHOR, "eles serão como joias, e você se enfeitará com eles, como uma noiva se enfeita.

[[v23-49-19]]

^<<v23-49-19,19>>^ "Seu povo logo encherá até as regiões mais desoladas de sua terra abandonada. Seus inimigos, que a escravizaram, estarão bem longe.

[[v23-49-20]]

^<<v23-49-20,20>>^ As gerações nascidas no exílio voltarão e dirão: ‘Precisamos de mais espaço! Esta terra é pequena demais!’.

[[v23-49-21]]

^<<v23-49-21,21>>^ Então você pensará: ‘Quem me deu todos esses descendentes? Quase todos os meus filhos foram mortos, e os que restaram foram levados para o exílio; fiquei aqui sozinha. De onde veio tanta gente? Quem os criou para mim?’"

[[v23-49-22]]

^<<v23-49-22,22>>^ Assim diz o SENHOR Soberano: "Vejam, darei um sinal às nações; elas trarão os filhos pequenos de Israel de volta nos braços e carregarão as filhas nos ombros.

[[v23-49-23]]

^<<v23-49-23,23>>^ Reis e rainhas os servirão e atenderão a todas as suas necessidades. Eles se curvarão diante de você com o rosto no chão e lamberão o pó de seus pés. Então você saberá que eu sou o SENHOR; quem confia em mim jamais será envergonhado".

[[v23-49-24]]

^<<v23-49-24,24>>^ Quem pode tirar o despojo das mãos de um guerreiro? Quem pode exigir que um tirano liberte seus prisioneiros?

[[v23-49-25]]

^<<v23-49-25,25>>^ Mas o SENHOR diz: "Os cativos dos guerreiros serão libertos, e o despojo dos tiranos será retomado. Pois lutarei contra os que lutam contra você e salvarei seus filhos.

[[v23-49-26]]

^<<v23-49-26,26>>^ Alimentarei seus inimigos com a própria carne deles, ficarão bêbados com rios do próprio sangue. Todo o mundo saberá que eu, o SENHOR, sou seu Salvador e seu Redentor, o Poderoso de Israel".

'''

xref:023-isaias/023-isaias-048.adoc#v23-48-0[&#60; Capítulo Anterior] | <<v23-49-0,Topo>> | xref:023-isaias/023-isaias-050.adoc#v23-50-0[Próximo Capítulo &#62;]