include::./index.adoc[]

[[v23-34-0]]
=== Isaías, 34
// nvt ?, NVT - Nova Versão Transformadora

[[v23-34-1]]

^<<v23-34-1,1>>^ Venham e escutem, nações da terra; o mundo e tudo que nele há, ouçam minhas palavras!

[[v23-34-2]]

^<<v23-34-2,2>>^ Pois é grande a ira do SENHOR com as nações; está furioso com todos os seus exércitos. Ele as destruirá por completo, ele as condenará à matança.

[[v23-34-3]]

^<<v23-34-3,3>>^ Seus mortos não serão sepultados; o fedor de seus cadáveres encherá a terra, e o sangue escorrerá pelos montes.

[[v23-34-4]]

^<<v23-34-4,4>>^ Os céus lá no alto se dissolverão e desaparecerão como pergaminho enrolado. As estrelas cairão do céu, como folhas secas da videira, como figos murchos da figueira.

[[v23-34-5]]

^<<v23-34-5,5>>^ E, quando minha espada tiver terminado seu trabalho nos céus, cairá sobre Edom, a nação que condenei à destruição.

[[v23-34-6]]

^<<v23-34-6,6>>^ A espada do SENHOR está banhada em sangue e coberta de gordura, de sangue de cordeiros e bodes, de gordura de carneiros. Sim, o SENHOR oferecerá um sacrifício na cidade de Bozra, fará grande matança em Edom.

[[v23-34-7]]

^<<v23-34-7,7>>^ Até homens fortes como bois morrerão, tanto os mais jovens como os mais velhos. A terra ficará ensopada de sangue, e o solo, cheio de gordura.

[[v23-34-8]]

^<<v23-34-8,8>>^ Pois é o dia da vingança do SENHOR, o ano em que retribuirá a Edom por tudo que fez a Israel.

[[v23-34-9]]

^<<v23-34-9,9>>^ Os riachos de Edom se encherão de piche ardente, e a terra ficará coberta de fogo e enxofre.

[[v23-34-10]]

^<<v23-34-10,10>>^ Esse julgamento sobre Edom jamais terá fim; sua fumaça subirá para sempre. A terra ficará deserta de geração em geração; ninguém voltará a habitar nela.

[[v23-34-11]]

^<<v23-34-11,11>>^ Ali viverão a coruja do deserto e o mocho, o corujão e o corvo. Pois Deus medirá aquela terra com cuidado; ele a medirá para o caos e para a destruição.

[[v23-34-12]]

^<<v23-34-12,12>>^ Ela se chamará Terra do Nada, e logo seus nobres desaparecerão.

[[v23-34-13]]

^<<v23-34-13,13>>^ Espinhos invadirão seus palácios, urtigas e cardos crescerão em suas fortalezas. As ruínas serão morada de chacais e habitação de corujas.

[[v23-34-14]]

^<<v23-34-14,14>>^ Animais do deserto se misturarão ali com hienas, bodes selvagens berrarão uns para os outros entre as ruínas, criaturas da noite irão até lá para descansar.

[[v23-34-15]]

^<<v23-34-15,15>>^ Ali a coruja fará seu ninho e porá seus ovos; chocará os filhotinhos e os cobrirá com suas asas. Os abutres também irão para lá, cada um com seu par.

[[v23-34-16]]

^<<v23-34-16,16>>^ Procurem no livro do Senhor e vejam o que ele fará. Não faltará nenhum desses animais, nenhum deles ficará sem par, pois o SENHOR assim prometeu; seu Espírito fará tudo se realizar.

[[v23-34-17]]

^<<v23-34-17,17>>^ Ele lançou sortes e dividiu a terra e a entregou a essas criaturas como propriedade. Elas a possuirão para sempre, de geração em geração.

'''

xref:023-isaias/023-isaias-033.adoc#v23-33-0[&#60; Capítulo Anterior] | <<v23-34-0,Topo>> | xref:023-isaias/023-isaias-035.adoc#v23-35-0[Próximo Capítulo &#62;]