include::./index.adoc[]

[[v23-40-0]]
=== Isaías, 40
// nvt ?, NVT - Nova Versão Transformadora

[[v23-40-1]]

^<<v23-40-1,1>>^ "Consolem, consolem meu povo", diz o seu Deus.

[[v23-40-2]]

^<<v23-40-2,2>>^ "Falem com carinho a Jerusalém; digam-lhe que seus dias de luta acabaram e que seus pecados foram perdoados. Sim, o SENHOR a castigou em dobro por todos os seus pecados."

[[v23-40-3]]

^<<v23-40-3,3>>^ Ouçam! Uma voz clama: "Abram caminho no deserto para o SENHOR! Preparem para nosso Deus uma estrada reta na terra desolada!

[[v23-40-4]]

^<<v23-40-4,4>>^ Aterrem os vales, nivelem os montes e as colinas. Endireitem as curvas, tornem planos os trechos acidentados.

[[v23-40-5]]

^<<v23-40-5,5>>^ Então a glória do SENHOR será revelada, e todos a verão. O SENHOR falou!".

[[v23-40-6]]

^<<v23-40-6,6>>^ Uma voz disse: "Clame!". Eu perguntei: "O que devo clamar?". "Anuncie que os seres humanos são como capim; sua beleza passa depressa, como as flores do campo.

[[v23-40-7]]

^<<v23-40-7,7>>^ O capim seca e as flores murcham quando o SENHOR sopra sobre elas; o mesmo acontece aos seres humanos.

[[v23-40-8]]

^<<v23-40-8,8>>^ O capim seca e as flores murcham, mas a palavra de nosso Deus permanece para sempre."

[[v23-40-9]]

^<<v23-40-9,9>>^ Ó Sião, mensageiro de boas notícias, grite do alto dos montes! Grite mais forte, ó Jerusalém, grite sem medo! Diga às cidades de Judá: "Seu Deus está chegando!".

[[v23-40-10]]

^<<v23-40-10,10>>^ Sim, o SENHOR Soberano vem com poder; com braço forte governará. Vejam, ele traz consigo sua recompensa!

[[v23-40-11]]

^<<v23-40-11,11>>^ Como pastor, ele alimentará seu rebanho; levará os cordeirinhos nos braços e os carregará junto ao coração; conduzirá ternamente as ovelhas com suas crias.

[[v23-40-12]]

^<<v23-40-12,12>>^ Quem mais segurou os oceanos nas mãos? Quem mediu os céus com os dedos? Quem mais sabe o peso da terra ou pesou na balança os montes e as colinas?

[[v23-40-13]]

^<<v23-40-13,13>>^ Quem pode orientar o Espírito do SENHOR? Quem sabe o suficiente para aconselhá-lo ou instruí-lo?

[[v23-40-14]]

^<<v23-40-14,14>>^ Acaso o SENHOR já precisou do conselho de alguém? Necessita que o instruam a respeito do que é bom? Alguém lhe ensinou o que é certo ou lhe mostrou o caminho da sabedoria?

[[v23-40-15]]

^<<v23-40-15,15>>^ Não, pois todas as nações do mundo não passam de uma gota num balde. Não são nada mais que pó sobre a balança. Ele levanta toda a terra como se fosse um grão de areia.

[[v23-40-16]]

^<<v23-40-16,16>>^ Nem toda a madeira nos bosques do Líbano nem todos os seus animais seriam suficientes para um holocausto digno de nosso Deus.

[[v23-40-17]]

^<<v23-40-17,17>>^ As nações do mundo não têm valor para ele; aos seus olhos, valem menos que nada, são apenas vazio.

[[v23-40-18]]

^<<v23-40-18,18>>^ A quem vocês podem comparar Deus? Que imagem usarão para representá-lo?

[[v23-40-19]]

^<<v23-40-19,19>>^ Acaso pode ser comparado a um ídolo feito num molde, coberto de ouro e enfeitado com correntes de prata?

[[v23-40-20]]

^<<v23-40-20,20>>^ Quem é pobre demais para ter um ídolo desses pode escolher madeira que não apodrece e um artesão habilidoso para entalhar uma imagem que não tombe!

[[v23-40-21]]

^<<v23-40-21,21>>^ Acaso não ouviram? Não entendem? Estão surdos para as palavras de Deus, palavras que ele falou antes que o mundo existisse? Será que são tão ignorantes?

[[v23-40-22]]

^<<v23-40-22,22>>^ Deus se senta acima do círculo da terra; para ele, as pessoas lá embaixo parecem gafanhotos. Estende os céus como uma cortina e faz com eles sua tenda.

[[v23-40-23]]

^<<v23-40-23,23>>^ Julga os poderosos do mundo e reduz todos eles a nada.

[[v23-40-24]]

^<<v23-40-24,24>>^ Mal são plantados, mal chegam a criar raízes, logo murcham, quando sopra sobre eles; o vento os leva embora como palha.

[[v23-40-25]]

^<<v23-40-25,25>>^ "A quem vocês me compararão? Quem é igual a mim?", pergunta o Santo.

[[v23-40-26]]

^<<v23-40-26,26>>^ Olhem para os céus; quem criou as estrelas? Ele as faz sair como um exército, uma após a outra, e chama cada uma pelo nome. Por causa de seu grande poder e sua força incomparável, nenhuma delas ousa se ausentar.

[[v23-40-27]]

^<<v23-40-27,27>>^ Ó Jacó, como pode dizer que o SENHOR não vê o que se passa? Ó Israel, como pode dizer que Deus não se importa com seus direitos?

[[v23-40-28]]

^<<v23-40-28,28>>^ Você não ouviu? Não entendeu? O SENHOR é o Deus eterno, o Criador de toda a terra. Ele nunca perde as forças nem se cansa, e ninguém pode medir a profundidade de sua sabedoria.

[[v23-40-29]]

^<<v23-40-29,29>>^ Dá forças aos cansados e vigor aos fracos.

[[v23-40-30]]

^<<v23-40-30,30>>^ Até os jovens perdem as forças e se cansam, e os rapazes tropeçam de tão exaustos.

[[v23-40-31]]

^<<v23-40-31,31>>^ Mas os que confiam no SENHOR renovam suas forças; voam alto, como águias. Correm e não se cansam, caminham e não desfalecem.

'''

xref:023-isaias/023-isaias-039.adoc#v23-39-0[&#60; Capítulo Anterior] | <<v23-40-0,Topo>> | xref:023-isaias/023-isaias-041.adoc#v23-41-0[Próximo Capítulo &#62;]