include::./index.adoc[]

[[v23-20-0]]
=== Isaías, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v23-20-1]]

^<<v23-20-1,1>>^ No ano em que Sargom, rei da Assíria, enviou seu comandante em chefe para conquistar a cidade de Asdode, na Filístia,

[[v23-20-2]]

^<<v23-20-2,2>>^ o SENHOR disse a Isaías, filho de Amoz: "Tire o pano de saco que você está vestindo e as sandálias que está calçando". Isaías obedeceu e passou a andar nu e descalço.

[[v23-20-3]]

^<<v23-20-3,3>>^ Então o SENHOR disse: "Meu servo Isaías andou nu e descalço durante três anos como sinal e advertência das dificuldades terríveis que trarei sobre o Egito e a Etiópia.

[[v23-20-4]]

^<<v23-20-4,4>>^ O rei da Assíria levará como prisioneiros os egípcios e os etíopes, tanto jovens como velhos. Ele os fará andar nus e descalços, com as nádegas descobertas, para vergonha do Egito.

[[v23-20-5]]

^<<v23-20-5,5>>^ Então os filisteus entrarão em pânico, pois contavam com o poder da Etiópia e se gabavam de seus aliados no Egito.

[[v23-20-6]]

^<<v23-20-6,6>>^ Dirão: ‘Se isso aconteceu com aqueles que eram nossa esperança de socorro, o que será de nós? Confiávamos que eles nos protegeriam do rei da Assíria!’".

'''

xref:023-isaias/023-isaias-019.adoc#v23-19-0[&#60; Capítulo Anterior] | <<v23-20-0,Topo>> | xref:023-isaias/023-isaias-021.adoc#v23-21-0[Próximo Capítulo &#62;]