include::./index.adoc[]

[[v23-21-0]]
=== Isaías, 21
// nvt ?, NVT - Nova Versão Transformadora

[[v23-21-1]]

^<<v23-21-1,1>>^ Recebi esta mensagem acerca da Babilônia, o deserto junto ao mar: O desastre se aproxima, vindo do deserto, como um vendaval impetuoso que chega do Neguebe.

[[v23-21-2]]

^<<v23-21-2,2>>^ Tenho uma visão assustadora: vejo o traidor trair, o destruidor destruir. Prossigam, elamitas e medos, ataquem e cerquem as cidades. Porei fim a todos os gemidos que ela causou.

[[v23-21-3]]

^<<v23-21-3,3>>^ Sinto pontadas intensas no estômago; sou tomado de dores agudas, como as dores da mulher em trabalho de parto. Desfaleço quando ouço o que Deus planeja fazer; não consigo olhar de tanto medo.

[[v23-21-4]]

^<<v23-21-4,4>>^ Minha mente está confusa e meu coração dispara; desejava que a noite chegasse, mas agora a escuridão me aterroriza.

[[v23-21-5]]

^<<v23-21-5,5>>^ Eles preparam um grande banquete, estendem tapetes para que os convidados se sentem; todos comem e bebem. Rápido, levantem-se! Peguem seus escudos e preparem-se para a batalha!

[[v23-21-6]]

^<<v23-21-6,6>>^ Enquanto isso, o Senhor me disse: "Coloque um vigia no muro da cidade; ele deve anunciar em alta voz o que vê.

[[v23-21-7]]

^<<v23-21-7,7>>^ Deve ficar atento a carros de guerra puxados por pares de cavalos, e a cavaleiros montados em jumentos e em camelos. Que o vigia permaneça bem alerta!".

[[v23-21-8]]

^<<v23-21-8,8>>^ Então o vigia gritou: "Meu senhor, todos os dias fico na torre de vigia, todas as noites permaneço em meu posto.

[[v23-21-9]]

^<<v23-21-9,9>>^ Agora, veja! Finalmente! Aí vem um homem num carro de guerra, com um par de cavalos!". Então o vigia disse: "Ela caiu! A Babilônia caiu! Todos os ídolos da Babilônia estão despedaçados no chão".

[[v23-21-10]]

^<<v23-21-10,10>>^ Ó meu povo, moído e peneirado, eu lhes anunciei tudo que o SENHOR dos Exércitos disse, tudo que o Deus de Israel me falou.

[[v23-21-11]]

^<<v23-21-11,11>>^ Recebi esta mensagem acerca de Edom: Alguém em Edom grita para mim: "Guarda, quanto falta para amanhecer? Quando terminará a noite?".

[[v23-21-12]]

^<<v23-21-12,12>>^ O guarda responde: "O amanhecer está próximo, mas logo a noite voltará; se quiser perguntar de novo, volte e pergunte".

[[v23-21-13]]

^<<v23-21-13,13>>^ Recebi esta mensagem acerca da Arábia: Ó caravanas de Dedã, escondam-se nos bosques da Arábia.

[[v23-21-14]]

^<<v23-21-14,14>>^ Ó habitantes de Temã, tragam água para essa gente sedenta, alimento para esses refugiados exaustos.

[[v23-21-15]]

^<<v23-21-15,15>>^ Fugiram da espada, da espada desembainhada, do arco preparado e dos terrores da batalha.

[[v23-21-16]]

^<<v23-21-16,16>>^ O Senhor me disse: "Dentro de um ano, contando cada dia, toda a glória de Quedar chegará ao fim.

[[v23-21-17]]

^<<v23-21-17,17>>^ Somente alguns de seus arqueiros valentes sobreviverão. Eu, o SENHOR, o Deus de Israel, falei!".

'''

xref:023-isaias/023-isaias-020.adoc#v23-20-0[&#60; Capítulo Anterior] | <<v23-21-0,Topo>> | xref:023-isaias/023-isaias-022.adoc#v23-22-0[Próximo Capítulo &#62;]