include::./index.adoc[]

[[v23-6-0]]
=== Isaías, 6
// nvt ?, NVT - Nova Versão Transformadora

[[v23-6-1]]

^<<v23-6-1,1>>^ No ano em que o rei Uzias morreu, eu vi o Senhor. Ele estava sentado em um trono alto, e a borda de seu manto enchia o templo.

[[v23-6-2]]

^<<v23-6-2,2>>^ Acima dele havia serafins, cada um com seis asas: com duas asas cobriam o rosto, com duas cobriam os pés e com duas voavam.

[[v23-6-3]]

^<<v23-6-3,3>>^ Diziam em alta voz uns aos outros: "Santo, santo, santo é o SENHOR dos Exércitos; toda a terra está cheia de sua glória!"

[[v23-6-4]]

^<<v23-6-4,4>>^ Suas vozes sacudiam o templo até os alicerces, e todo o edifício estava cheio de fumaça.

[[v23-6-5]]

^<<v23-6-5,5>>^ Então eu disse: "Estou perdido! É o meu fim, pois sou um homem de lábios impuros e vivo no meio de pessoas de lábios impuros. Meus olhos, porém, viram o Rei, o SENHOR dos Exércitos!".

[[v23-6-6]]

^<<v23-6-6,6>>^ Então um dos serafins voou em minha direção, trazendo uma brasa ardente que ele havia tirado do altar com uma tenaz.

[[v23-6-7]]

^<<v23-6-7,7>>^ Tocou meus lábios com a brasa e disse: "Veja, esta brasa tocou seus lábios. Sua culpa foi removida, e seus pecados foram perdoados".

[[v23-6-8]]

^<<v23-6-8,8>>^ Então ouvi o Senhor perguntar: "Quem enviarei como mensageiro a este povo? Quem irá por nós?". E eu respondi: "Aqui estou; envia-me".

[[v23-6-9]]

^<<v23-6-9,9>>^ Ele disse: "Vá e diga a este povo: ‘Ouçam com atenção, mas não entendam; observem bem, mas não aprendam’.

[[v23-6-10]]

^<<v23-6-10,10>>^ Endureça o coração deste povo; tape os ouvidos e feche os olhos deles. Assim, não verão com os olhos, nem ouvirão com os ouvidos, não entenderão com o coração, nem se voltarão para mim a fim de serem curados".

[[v23-6-11]]

^<<v23-6-11,11>>^ Então eu disse: "Senhor, até quando isso vai durar?", e ele respondeu: "Até que as cidades fiquem vazias, e as casas, abandonadas, e toda a terra seja devastada;

[[v23-6-12]]

^<<v23-6-12,12>>^ até que o SENHOR tenha mandado todos embora, e toda a terra de Israel esteja deserta.

[[v23-6-13]]

^<<v23-6-13,13>>^ Se ainda sobreviver uma décima parte, um remanescente, ela será invadida outra vez e queimada. Mas, assim como o terebinto e o carvalho deixam um toco quando cortados, o toco de Israel será uma semente santa".

'''

xref:023-isaias/023-isaias-005.adoc#v23-5-0[&#60; Capítulo Anterior] | <<v23-6-0,Topo>> | xref:023-isaias/023-isaias-007.adoc#v23-7-0[Próximo Capítulo &#62;]