include::./index.adoc[]

[[v23-65-0]]
=== Isaías, 65
// nvt ?, NVT - Nova Versão Transformadora

[[v23-65-1]]

^<<v23-65-1,1>>^ O SENHOR diz: "Estava pronto para atender, mas ninguém pediu ajuda; estava pronto para ser encontrado, mas ninguém me procurou. A uma nação que não invocava meu nome, eu disse: ‘Aqui estou! Aqui estou!’.

[[v23-65-2]]

^<<v23-65-2,2>>^ O dia todo abri os braços para um povo rebelde, mas eles seguiram seus caminhos perversos e suas ideias distorcidas.

[[v23-65-3]]

^<<v23-65-3,3>>^ O dia todo me insultam abertamente, ao adorarem ídolos em seus jardins e queimarem incenso em seus altares.

[[v23-65-4]]

^<<v23-65-4,4>>^ À noite, andam no meio das sepulturas e consultam os mortos. Comem carne de porco e fazem ensopados com outros alimentos proibidos.

[[v23-65-5]]

^<<v23-65-5,5>>^ Apesar disso, dizem uns aos outros: ‘Não se aproxime, pois vai me contaminar! Sou mais santo que você!’. Essa gente é fedor em minhas narinas, fumaça irritante que nunca passa.

[[v23-65-6]]

^<<v23-65-6,6>>^ "Vejam, meu decreto está escrito diante de mim: Não permanecerei calado; retribuirei conforme merecem! Sim, eu lhes darei o que merecem,

[[v23-65-7]]

^<<v23-65-7,7>>^ tanto por seus pecados como pelos pecados de seus antepassados", diz o SENHOR. "Pois eles também queimaram incenso nos montes e me insultaram nas colinas; eu lhes darei o que merecem!

[[v23-65-8]]

^<<v23-65-8,8>>^ "Contudo, não destruirei todos eles", diz o SENHOR. "É possível encontrar uvas boas num cacho de uvas podres; pois alguém dirá: ‘Não jogue todas fora, algumas ainda estão boas!’. Assim também não destruirei todo o Israel, pois ainda tenho ali servos fiéis.

[[v23-65-9]]

^<<v23-65-9,9>>^ Preservarei um remanescente do povo de Israel e de Judá para possuir minha terra. Aqueles que eu escolhi a herdarão, e meus servos ali habitarão.

[[v23-65-10]]

^<<v23-65-10,10>>^ A planície de Sarom voltará a ficar cheia de rebanhos para meu povo que me buscou, e o vale de Acor servirá de pasto para o gado.

[[v23-65-11]]

^<<v23-65-11,11>>^ "Mas, porque vocês abandonaram o Senhor e se esqueceram de seu santo monte, e porque prepararam banquetes para honrar a deusa Sorte e oferecer vinho misturado ao deus Destino,

[[v23-65-12]]

^<<v23-65-12,12>>^ hoje eu os destinarei à espada; todos vocês se curvarão diante do carrasco. Pois, quando chamei, não responderam; quando falei, não ouviram. Praticaram o mal, bem diante dos meus olhos, e escolheram fazer o que desprezo."

[[v23-65-13]]

^<<v23-65-13,13>>^ Portanto, assim diz o SENHOR Soberano: "Meus servos comerão, mas vocês passarão fome. Meus servos beberão, mas vocês terão sede. Meus servos se alegrarão, mas vocês serão humilhados.

[[v23-65-14]]

^<<v23-65-14,14>>^ Meus servos cantarão de alegria, mas vocês gritarão de tristeza e desespero.

[[v23-65-15]]

^<<v23-65-15,15>>^ Seu nome será maldição entre meu povo escolhido, pois o SENHOR Soberano os destruirá e chamará seus servos por outro nome.

[[v23-65-16]]

^<<v23-65-16,16>>^ Todos que pedem uma bênção ou fazem um juramento o farão pelo Deus da verdade. Pois deixarei de lado minha ira e me esquecerei das maldades cometidas no passado.

[[v23-65-17]]

^<<v23-65-17,17>>^ "Vejam! Crio novos céus e nova terra, e ninguém mais pensará nas coisas passadas.

[[v23-65-18]]

^<<v23-65-18,18>>^ Alegrem-se e exultem para sempre em minha criação! Vejam! Criarei Jerusalém para ser um lugar de celebração; seu povo será fonte de alegria.

[[v23-65-19]]

^<<v23-65-19,19>>^ Eu me alegrarei por Jerusalém e terei prazer em meu povo. Nela não se ouvirá mais o som de pranto e clamor.

[[v23-65-20]]

^<<v23-65-20,20>>^ "Nunca mais morrerão bebês de poucos dias, nunca mais morrerão adultos antes de terem uma vida plena. Ninguém mais será considerado velho aos cem anos; somente os amaldiçoados morrerão jovens.

[[v23-65-21]]

^<<v23-65-21,21>>^ Naqueles dias, habitarão nas casas que construíram e comerão dos frutos de suas próprias videiras.

[[v23-65-22]]

^<<v23-65-22,22>>^ Invasores não habitarão em suas casas, nem lhes tomarão suas videiras. Pois meu povo terá vida longa como as árvores; meus escolhidos terão tempo para desfrutar tudo que conseguiram com grande esforço.

[[v23-65-23]]

^<<v23-65-23,23>>^ Não trabalharão inutilmente, e seus filhos não serão condenados à desgraça. Pois são um povo abençoado pelo SENHOR, e seus filhos também serão abençoados.

[[v23-65-24]]

^<<v23-65-24,24>>^ Eu os atenderei antes mesmo de clamarem a mim; enquanto ainda estiverem falando de suas necessidades, responderei a suas orações!

[[v23-65-25]]

^<<v23-65-25,25>>^ O lobo e o cordeiro comerão juntos, o leão se alimentará de palha como o boi, mas as serpentes comerão pó. Em meu santo monte, ninguém será ferido nem destruído; eu, o SENHOR falei!".

'''

xref:023-isaias/023-isaias-064.adoc#v23-64-0[&#60; Capítulo Anterior] | <<v23-65-0,Topo>> | xref:023-isaias/023-isaias-066.adoc#v23-66-0[Próximo Capítulo &#62;]