include::./index.adoc[]

[[v23-58-0]]
=== Isaías, 58
// nvt ?, NVT - Nova Versão Transformadora

[[v23-58-1]]

^<<v23-58-1,1>>^ "Grite alto, com todas as suas forças! Grite alto, como o som da trombeta! Fale ao meu povo, Israel, sobre sua rebeldia e seus pecados!

[[v23-58-2]]

^<<v23-58-2,2>>^ Apesar disso, agem como se fossem piedosos! Vêm ao templo todos os dias e parecem ter prazer em aprender a meu respeito. Agem como nação justa que jamais abandonaria as leis de seu Deus. Pedem que eu atue em favor deles e fingem querer estar perto de mim.

[[v23-58-3]]

^<<v23-58-3,3>>^ Dizem: ‘Jejuamos diante de ti! Por que não prestas atenção? Nós nos humilhamos com severidade, e tu nem reparas!’. "Vou lhes dizer por quê", eu respondo. "É porque jejuam para satisfazer a si mesmos. Enquanto isso, oprimem seus empregados.

[[v23-58-4]]

^<<v23-58-4,4>>^ De que adianta jejuar, se continuam a brigar e discutir? Com esse tipo de jejum, não ouvirei suas orações.

[[v23-58-5]]

^<<v23-58-5,5>>^ Vocês se humilham ao cumprir os rituais: curvam a cabeça, como junco ao vento, vestem-se de pano de saco e cobrem-se de cinzas. É isso que chamam de jejum? Acreditam mesmo que agradará o SENHOR?

[[v23-58-6]]

^<<v23-58-6,6>>^ "Este é o tipo de jejum que desejo: Soltem os que foram presos injustamente, aliviem as cargas de seus empregados. Libertem os oprimidos, removam as correntes que prendem as pessoas.

[[v23-58-7]]

^<<v23-58-7,7>>^ Repartam seu alimento com os famintos, ofereçam abrigo aos que não têm casa. Deem roupas aos que precisam, não se escondam dos que carecem de ajuda.

[[v23-58-8]]

^<<v23-58-8,8>>^ "Então sua luz virá como o amanhecer, e suas feridas sararão num instante. Sua justiça os conduzirá adiante, e a glória do SENHOR os protegerá na retaguarda.

[[v23-58-9]]

^<<v23-58-9,9>>^ Então vocês clamarão, e o SENHOR responderá. ‘Aqui estou’, ele dirá. "Removam o jugo pesado de opressão, parem de fazer acusações e espalhar boatos maldosos.

[[v23-58-10]]

^<<v23-58-10,10>>^ Deem alimento aos famintos e ajudem os aflitos. Então sua luz brilhará na escuridão, e a escuridão ao redor se tornará clara como o meio-dia.

[[v23-58-11]]

^<<v23-58-11,11>>^ O SENHOR os guiará continuamente, lhes dará água quando tiverem sede e restaurará suas forças. Vocês serão como um jardim bem regado, como a fonte que não para de jorrar.

[[v23-58-12]]

^<<v23-58-12,12>>^ Reconstruirão as ruínas desertas de suas cidades e serão conhecidos como reparadores de muros e restauradores de ruas e casas.

[[v23-58-13]]

^<<v23-58-13,13>>^ "Guardem o sábado como dia santo; não usem esse dia para cuidar de seus interesses. Desfrutem o sábado e falem dele com prazer, como dia santo do SENHOR. Honrem o sábado com tudo que fizerem nesse dia; não sigam seus desejos, nem falem coisas inúteis.

[[v23-58-14]]

^<<v23-58-14,14>>^ Então o SENHOR será sua alegria; grande honra lhes darei e os sustentarei com a propriedade que prometi a seu antepassado Jacó. Eu, o SENHOR, falei!"

'''

xref:023-isaias/023-isaias-057.adoc#v23-57-0[&#60; Capítulo Anterior] | <<v23-58-0,Topo>> | xref:023-isaias/023-isaias-059.adoc#v23-59-0[Próximo Capítulo &#62;]