include::./index.adoc[]

[[v23-56-0]]
=== Isaías, 56
// nvt ?, NVT - Nova Versão Transformadora

[[v23-56-1]]

^<<v23-56-1,1>>^ Assim diz o SENHOR: "Sejam justos e façam o que é certo, pois logo virei para livrá-los e para mostrar minha justiça entre vocês.

[[v23-56-2]]

^<<v23-56-2,2>>^ Feliz é aquele que tiver o cuidado de agir desse modo. Feliz é aquele que honrar meus sábados e evitar fazer o mal.

[[v23-56-3]]

^<<v23-56-3,3>>^ "Não permitam que o estrangeiro comprometido com o SENHOR diga: ‘O SENHOR jamais me deixará fazer parte de seu povo’. E não permitam que o eunuco diga: ‘Sou uma árvore seca, sem filhos e sem futuro’.

[[v23-56-4]]

^<<v23-56-4,4>>^ Pois assim diz o SENHOR: Eu abençoarei os eunucos que guardarem meus sábados e fizerem o que me agrada e se apegarem à minha aliança.

[[v23-56-5]]

^<<v23-56-5,5>>^ Eu lhes darei, dentro dos muros de minha casa, um memorial e um nome muito maior que filhos e filhas. Pois o nome que lhes darei é permanente; nunca desaparecerá!

[[v23-56-6]]

^<<v23-56-6,6>>^ "Abençoarei também os estrangeiros comprometidos com o SENHOR, que o servem e amam seu nome, que o adoram e não profanam o sábado e que se apegam firmemente à minha aliança.

[[v23-56-7]]

^<<v23-56-7,7>>^ Eu os levarei ao meu santo monte e os encherei de alegria em minha casa de oração. Aceitarei seus holocaustos e sacrifícios, pois meu templo será chamado casa de oração para todas as nações.

[[v23-56-8]]

^<<v23-56-8,8>>^ Pois o SENHOR Soberano, que traz de volta os exilados, diz: Também trarei outros de volta, além do meu povo, Israel".

[[v23-56-9]]

^<<v23-56-9,9>>^ Venham, animais do campo! Venham, animais do bosque! Venham e devorem!

[[v23-56-10]]

^<<v23-56-10,10>>^ Pois os vigias do meu povo são cegos e ignorantes. São como cães de guarda mudos, que não avisam quando o perigo se aproxima. Gostam de ficar deitados, dormindo e sonhando;

[[v23-56-11]]

^<<v23-56-11,11>>^ como cães gulosos, nunca estão satisfeitos. São pastores ignorantes; cada um segue seu caminho e procura seus interesses.

[[v23-56-12]]

^<<v23-56-12,12>>^ Dizem: "Venham, vamos arranjar vinho e dar uma festa; vamos nos embebedar. Amanhã faremos a mesma coisa, e daremos uma festa ainda maior!".

'''

xref:023-isaias/023-isaias-055.adoc#v23-55-0[&#60; Capítulo Anterior] | <<v23-56-0,Topo>> | xref:023-isaias/023-isaias-057.adoc#v23-57-0[Próximo Capítulo &#62;]