include::./index.adoc[]

[[v23-29-0]]
=== Isaías, 29
// nvt ?, NVT - Nova Versão Transformadora

[[v23-29-1]]

^<<v23-29-1,1>>^ "Que aflição espera Ariel, a cidade de Davi! Ano após ano celebram suas festas.

[[v23-29-2]]

^<<v23-29-2,2>>^ Contudo, trarei calamidade sobre vocês; haverá muito choro e tristeza. Ariel se tornará exatamente o que significa seu nome: um altar coberto de sangue.

[[v23-29-3]]

^<<v23-29-3,3>>^ Serei seu inimigo, cercarei Jerusalém e atacarei seus muros. Levantarei torres de cerco e a destruirei.

[[v23-29-4]]

^<<v23-29-4,4>>^ Então, das profundezas da terra, você falará; suas palavras virão do pó. Sua voz sussurrará do chão, como um fantasma chamado da sepultura.

[[v23-29-5]]

^<<v23-29-5,5>>^ "De repente, porém, seus inimigos cruéis serão esmagados como o mais fino pó. Seus muitos agressores serão expulsos como palha ao vento. De repente, num instante,

[[v23-29-6]]

^<<v23-29-6,6>>^ eu, o SENHOR dos Exércitos, entrarei em ação com trovão, terremoto e grande estrondo, com vendaval, tempestade e fogo consumidor.

[[v23-29-7]]

^<<v23-29-7,7>>^ Todas as nações que lutam contra Ariel desaparecerão como um sonho. Os que atacam seus muros sumirão como uma visão noturna.

[[v23-29-8]]

^<<v23-29-8,8>>^ O faminto sonha que está comendo, mas ao acordar ainda sente fome. O sedento sonha que está bebendo, mas ao amanhecer ainda sente sede. Assim será com seus muitos inimigos, aqueles que atacam o monte Sião".

[[v23-29-9]]

^<<v23-29-9,9>>^ Estão espantados? Não acreditam? Continuem cegos, se quiserem. Estão entorpecidos, mas não é pelo vinho; cambaleiam, mas não é por bebida forte.

[[v23-29-10]]

^<<v23-29-10,10>>^ É porque o SENHOR derramou sobre vocês um espírito de sono profundo; fechou os olhos de seus profetas e videntes.

[[v23-29-11]]

^<<v23-29-11,11>>^ Para eles, todos os acontecimentos futuros desta visão são um livro selado. Quando você o entregar aos que sabem ler, dirão: "Não podemos ler, pois está selado".

[[v23-29-12]]

^<<v23-29-12,12>>^ Quando o entregar aos que não sabem ler, dirão: "Não sabemos ler".

[[v23-29-13]]

^<<v23-29-13,13>>^ Portanto, o Senhor diz: "Este povo fala que me pertence; honra-me com os lábios, mas o coração está longe de mim. A adoração que me prestam não passa de regras ensinadas por homens.

[[v23-29-14]]

^<<v23-29-14,14>>^ Por isso, mais uma vez deixarei este povo maravilhado com obras maravilhosas. A sabedoria dos sábios passará, e a inteligência dos inteligentes desaparecerá".

[[v23-29-15]]

^<<v23-29-15,15>>^ Que aflição espera os que procuram esconder seus planos do SENHOR, que realizam seus atos perversos na escuridão! Dizem: "O SENHOR não nos vê; não sabe o que se passa".

[[v23-29-16]]

^<<v23-29-16,16>>^ Como são tolos! Ele é o oleiro e certamente é maior que vocês, o barro. Pode o objeto criado dizer sobre aquele que o criou: "Ele não me fez"? Pode o vaso dizer: "O oleiro não sabe o que faz"?

[[v23-29-17]]

^<<v23-29-17,17>>^ Logo, em pouco tempo, os bosques do Líbano se tornarão campo fértil, e o campo fértil produzirá colheitas fartas.

[[v23-29-18]]

^<<v23-29-18,18>>^ Naquele dia, os surdos ouvirão as palavras lidas de um livro, e os cegos verão no meio da escuridão e das trevas.

[[v23-29-19]]

^<<v23-29-19,19>>^ Os humildes ficarão cheios de alegria do SENHOR, e os pobres exultarão no Santo de Israel.

[[v23-29-20]]

^<<v23-29-20,20>>^ O opressor já não existirá, o arrogante desaparecerá, e os que tramam o mal serão destruídos.

[[v23-29-21]]

^<<v23-29-21,21>>^ Os que condenam os inocentes com testemunhos falsos desaparecerão. O mesmo acontecerá aos que trapaceiam para perverter a justiça e contam mentiras para destruir os inocentes.

[[v23-29-22]]

^<<v23-29-22,22>>^ Por isso o SENHOR, que resgatou Abraão, diz ao povo de Israel: "Meu povo não será mais envergonhado, nem ficará pálido de medo.

[[v23-29-23]]

^<<v23-29-23,23>>^ Quando virem seus muitos filhos e todas as bênçãos que lhes dei, reconhecerão a santidade do Santo de Jacó e temerão o Deus de Israel.

[[v23-29-24]]

^<<v23-29-24,24>>^ Os que se desviam terão discernimento, e os que se queixam aceitarão instrução."

'''

xref:023-isaias/023-isaias-028.adoc#v23-28-0[&#60; Capítulo Anterior] | <<v23-29-0,Topo>> | xref:023-isaias/023-isaias-030.adoc#v23-30-0[Próximo Capítulo &#62;]