include::./index.adoc[]

[[v23-27-0]]
=== Isaías, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v23-27-1]]

^<<v23-27-1,1>>^ Naquele dia, o SENHOR tomará sua veloz e terrível espada e castigará o Leviatã, a serpente que se move com rapidez, a serpente que se enrola e se contorce. Ele matará o dragão do mar.

[[v23-27-2]]

^<<v23-27-2,2>>^ "Naquele dia, cantem sobre a videira frutífera.

[[v23-27-3]]

^<<v23-27-3,3>>^ Eu, o SENHOR, a vigiarei e a regarei com cuidado. Dia e noite a vigiarei, para que ninguém lhe cause dano.

[[v23-27-4]]

^<<v23-27-4,4>>^ Minha ira terá passado; se houver espinhos e mato crescendo ali, eu os atacarei e os queimarei,

[[v23-27-5]]

^<<v23-27-5,5>>^ a menos que se voltem para mim e me peçam ajuda. Que façam as pazes comigo, sim, que façam as pazes comigo."

[[v23-27-6]]

^<<v23-27-6,6>>^ Está chegando o tempo em que os descendentes de Jacó criarão raízes; Israel brotará e florescerá e encherá de frutos toda a terra!

[[v23-27-7]]

^<<v23-27-7,7>>^ Acaso o SENHOR feriu Israel como feriu seus inimigos? Destruiu o povo como destruiu seus adversários?

[[v23-27-8]]

^<<v23-27-8,8>>^ Não, mas os exilou para que lhe prestassem contas; foram exilados de sua terra, como se um vento oriental os tivesse soprado para longe.

[[v23-27-9]]

^<<v23-27-9,9>>^ O SENHOR fez isso para purificar Israel de sua perversidade, para remover todo o seu pecado. Por isso, todos os santuários idólatras serão reduzidos a pó; nenhum poste de Aserá ou altar de incenso continuará em pé.

[[v23-27-10]]

^<<v23-27-10,10>>^ As cidades fortificadas ficarão silenciosas e vazias, as casas, abandonadas, as ruas, cobertas de ervas daninhas. Bezerros pastarão ali e mastigarão brotos e ramos.

[[v23-27-11]]

^<<v23-27-11,11>>^ Israel é como os ramos secos de uma árvore, quebrados e usados para acender o fogo sob as panelas; é nação tola e insensata. Por isso, aquele que os criou não terá compaixão nem misericórdia.

[[v23-27-12]]

^<<v23-27-12,12>>^ Chegará o dia, porém, em que o SENHOR os ajuntará como grãos colhidos à mão. Um por um, ele os reunirá, desde o rio Eufrates, no leste, até o ribeiro do Egito, no oeste.

[[v23-27-13]]

^<<v23-27-13,13>>^ Naquele dia, soará a grande trombeta. Muitos que estavam perecendo no exílio na Assíria e no Egito voltarão a Jerusalém para adorar o SENHOR em seu santo monte.

'''

xref:023-isaias/023-isaias-026.adoc#v23-26-0[&#60; Capítulo Anterior] | <<v23-27-0,Topo>> | xref:023-isaias/023-isaias-028.adoc#v23-28-0[Próximo Capítulo &#62;]