include::./index.adoc[]

[[v23-45-0]]
=== Isaías, 45
// nvt ?, NVT - Nova Versão Transformadora

[[v23-45-1]]

^<<v23-45-1,1>>^ É isto que diz o SENHOR a Ciro, seu ungido, cuja mão direita ele fortalecerá. Diante dele, reis poderosos ficarão paralisados de medo; os portões de suas fortalezas se abrirão e nunca mais se fecharão.

[[v23-45-2]]

^<<v23-45-2,2>>^ Assim diz ele: "Irei à sua frente, Ciro, e tornarei planos os montes; quebrarei os portões de bronze e destruirei as trancas de ferro.

[[v23-45-3]]

^<<v23-45-3,3>>^ Eu lhe darei tesouros escondidos na escuridão, sim, riquezas secretas. Farei isso para que saiba que eu sou o SENHOR, o Deus de Israel, que chama você pelo nome.

[[v23-45-4]]

^<<v23-45-4,4>>^ "Foi por causa de Jacó, meu servo, Israel, meu escolhido, que o chamei para realizar essa tarefa. Por isso o chamei pelo nome, quando você não me conhecia.

[[v23-45-5]]

^<<v23-45-5,5>>^ Eu sou o SENHOR; não há outro Deus. Eu o preparei para a batalha, embora você não me conheça,

[[v23-45-6]]

^<<v23-45-6,6>>^ para que todo o mundo, de leste a oeste, saiba que não há outro Deus; eu sou o SENHOR, e não há outro.

[[v23-45-7]]

^<<v23-45-7,7>>^ Formo a luz e crio as trevas, trago a paz e crio a calamidade; eu, o SENHOR, faço essas coisas.

[[v23-45-8]]

^<<v23-45-8,8>>^ "Abram-se, ó céus, e derramem justiça. Abra-se a terra, para que brote a salvação e, com ela, a justiça; eu, o SENHOR, as criei.

[[v23-45-9]]

^<<v23-45-9,9>>^ "Que aflição espera quem contesta seu Criador! Acaso o pote de barro discute com o oleiro? O barro argumenta com aquele que lhe dá forma e diz: ‘Você não está fazendo direito!’ ou exclama: ‘Você não sabe trabalhar!’?

[[v23-45-10]]

^<<v23-45-10,10>>^ Que terrível seria se uma criança dissesse ao pai: ‘Por que você me gerou?’, e à mãe: ‘Por que me trouxe ao mundo?’".

[[v23-45-11]]

^<<v23-45-11,11>>^ Assim diz o SENHOR, o Santo de Israel e seu Criador: "Querem questionar o que farei por meus filhos? Querem dar ordens a respeito do que minhas mãos fizeram?

[[v23-45-12]]

^<<v23-45-12,12>>^ Eu fiz a terra e criei os seres humanos para nela habitarem. Com minhas mãos, estendi os céus, e todas as estrelas estão às minhas ordens.

[[v23-45-13]]

^<<v23-45-13,13>>^ Levantarei esse homem para que cumpra meu justo propósito e guiarei suas ações. Ele restaurará minha cidade e libertará meu povo cativo, sem exigir recompensa nem tributo. Eu, o SENHOR dos Exércitos, falei!".

[[v23-45-14]]

^<<v23-45-14,14>>^ Assim diz o SENHOR: "Você governará os egípcios, os etíopes e os sabeus. Eles lhe trarão toda a sua mercadoria, e ela será sua. Caminharão atrás de você, como prisioneiros acorrentados; cairão de joelhos à sua frente e dirão: ‘Deus está com você, e ele é o único Deus; não há outro além dele’".

[[v23-45-15]]

^<<v23-45-15,15>>^ De fato, ó Deus de Israel, nosso Salvador, tu ages de formas misteriosas.

[[v23-45-16]]

^<<v23-45-16,16>>^ Todos os artesãos que fazem ídolos serão humilhados; juntos, serão envergonhados.

[[v23-45-17]]

^<<v23-45-17,17>>^ Mas o SENHOR salvará o povo de Israel com salvação permanente; nunca mais serão humilhados e envergonhados.

[[v23-45-18]]

^<<v23-45-18,18>>^ Pois o SENHOR é Deus; criou os céus e a terra e pôs todas as coisas no devido lugar. Fez o mundo para ser habitado, e não para ser um lugar de vazio e caos. Ele diz: "Eu sou o SENHOR, e não há outro.

[[v23-45-19]]

^<<v23-45-19,19>>^ Não sussurro coisas obscuras em algum canto escondido, nem teria dito ao povo de Israel que me buscasse se não fosse possível me encontrar. Eu, o SENHOR falo apenas a verdade e declaro somente o que é certo.

[[v23-45-20]]

^<<v23-45-20,20>>^ "Reúnam-se e venham, fugitivos de nações vizinhas! Como são tolos os que levam consigo seus ídolos de madeira e oram a deuses que não podem salvar!

[[v23-45-21]]

^<<v23-45-21,21>>^ Consultem uns aos outros e defendam sua causa, juntem-se e decidam o que dizer. Quem anunciou essas coisas tanto tempo atrás? Quem lhes disse o que aconteceria? Não fui eu, o SENHOR? Pois não há outro Deus além de mim, Deus justo e Salvador; não há outro além de mim.

[[v23-45-22]]

^<<v23-45-22,22>>^ Que todo o mundo se volte para mim para ser salvo! Pois eu sou Deus, e não há nenhum outro.

[[v23-45-23]]

^<<v23-45-23,23>>^ Jurei por meu próprio nome, disse o que é justo e não voltarei atrás em minha palavra: Diante de mim todo joelho se dobrará, e toda língua me declarará lealdade".

[[v23-45-24]]

^<<v23-45-24,24>>^ O povo dirá: "O SENHOR é a única fonte de minha justiça e força". E todos que contra ele se iraram virão até ele e serão envergonhados.

[[v23-45-25]]

^<<v23-45-25,25>>^ No SENHOR, todas as gerações de Israel serão justificadas e nele se gloriarão.

'''

xref:023-isaias/023-isaias-044.adoc#v23-44-0[&#60; Capítulo Anterior] | <<v23-45-0,Topo>> | xref:023-isaias/023-isaias-046.adoc#v23-46-0[Próximo Capítulo &#62;]