include::./index.adoc[]

[[v23-26-0]]
=== Isaías, 26
// nvt ?, NVT - Nova Versão Transformadora

[[v23-26-1]]

^<<v23-26-1,1>>^ Naquele dia, todos na terra de Judá entoarão este cântico: Nossa cidade é forte; estamos cercados pelos muros da salvação de Deus!

[[v23-26-2]]

^<<v23-26-2,2>>^ Abram os portões para os justos, deixem entrar os fiéis.

[[v23-26-3]]

^<<v23-26-3,3>>^ Tu guardarás em perfeita paz todos que em ti confiam, aqueles cujos propósitos estão firmes em ti.

[[v23-26-4]]

^<<v23-26-4,4>>^ Confiem sempre no SENHOR, pois o SENHOR Deus é a Rocha eterna.

[[v23-26-5]]

^<<v23-26-5,5>>^ Ele humilha os orgulhosos; rebaixa a cidade arrogante e a lança ao pó.

[[v23-26-6]]

^<<v23-26-6,6>>^ Os pobres a pisoteiam, e os necessitados caminham sobre ela.

[[v23-26-7]]

^<<v23-26-7,7>>^ Para os justos, porém, o caminho é reto. Tu, que ages com retidão, tornas plano o caminho adiante deles.

[[v23-26-8]]

^<<v23-26-8,8>>^ SENHOR, ao seguir tuas justas decisões, depositamos em ti nossa esperança; o desejo de nosso coração é glorificar teu nome.

[[v23-26-9]]

^<<v23-26-9,9>>^ À noite eu te procuro, ó Deus; pela manhã te busco de todo o coração. Pois só quando vens julgar a terra as pessoas aprendem a justiça.

[[v23-26-10]]

^<<v23-26-10,10>>^ Tua bondade com os perversos não os leva a fazer o bem. Embora outros pratiquem a justiça, eles continuam a fazer o mal; não levam em conta a majestade do SENHOR.

[[v23-26-11]]

^<<v23-26-11,11>>^ Ó SENHOR, eles não prestam atenção à tua mão levantada; mostra-lhes teu zelo em defender teu povo. Então serão envergonhados; que o fogo de tua ira consuma teus inimigos!

[[v23-26-12]]

^<<v23-26-12,12>>^ SENHOR, tu nos concederás paz; sim, tudo que realizamos vem de ti.

[[v23-26-13]]

^<<v23-26-13,13>>^ Ó SENHOR, nosso Deus, outros senhores nos governaram, mas só a ti adoramos.

[[v23-26-14]]

^<<v23-26-14,14>>^ Aqueles a quem servimos estão mortos; seus espíritos jamais voltarão a viver. Tu os atacaste e os destruíste; há muito caíram no esquecimento.

[[v23-26-15]]

^<<v23-26-15,15>>^ Ó SENHOR, engrandeceste nosso povo; sim, tu nos tornaste grandes. Expandiste nossas fronteiras e foste glorificado.

[[v23-26-16]]

^<<v23-26-16,16>>^ SENHOR, em angústia te buscamos; oramos sob o peso de tua disciplina.

[[v23-26-17]]

^<<v23-26-17,17>>^ Como a mulher grávida que se contorce e grita de dor quando dá à luz, assim estávamos em tua presença, SENHOR.

[[v23-26-18]]

^<<v23-26-18,18>>^ Nós também nos contorcemos de dor intensa, mas nosso sofrimento em nada resultou. Não trouxemos salvação à terra, nem vida ao mundo.

[[v23-26-19]]

^<<v23-26-19,19>>^ Teus mortos, porém, viverão; seus corpos ressuscitarão. Aqueles que dormem na terra se levantarão e cantarão de alegria. Pois tua luz que dá vida descerá como o orvalho sobre teu povo no lugar dos mortos.

[[v23-26-20]]

^<<v23-26-20,20>>^ Vá para casa, meu povo, e tranque as portas! Esconda-se por um breve tempo, até que tenha passado a ira do SENHOR.

[[v23-26-21]]

^<<v23-26-21,21>>^ Vejam, o SENHOR vem dos céus para castigar os habitantes da terra por seus pecados! A terra já não esconderá os que foram mortos; ela os mostrará para que todos os vejam.

'''

xref:023-isaias/023-isaias-025.adoc#v23-25-0[&#60; Capítulo Anterior] | <<v23-26-0,Topo>> | xref:023-isaias/023-isaias-027.adoc#v23-27-0[Próximo Capítulo &#62;]