include::./index.adoc[]

[[v23-35-0]]
=== Isaías, 35
// nvt ?, NVT - Nova Versão Transformadora

[[v23-35-1]]

^<<v23-35-1,1>>^ As regiões desabitadas e o deserto exultarão; a terra desolada se alegrará e florescerá como o açafrão.

[[v23-35-2]]

^<<v23-35-2,2>>^ Haverá muitas flores, cânticos e alegria! Os desertos se tornarão verdes como os montes do Líbano, belos como o monte Carmelo e a planície de Sarom. Ali o SENHOR mostrará sua glória, o esplendor de nosso Deus.

[[v23-35-3]]

^<<v23-35-3,3>>^ Fortaleçam os de mãos cansadas, apoiem os de joelhos fracos.

[[v23-35-4]]

^<<v23-35-4,4>>^ Digam aos de coração temeroso: "Sejam fortes e não temam, pois seu Deus vem para vingar-se de seus inimigos; ele vem para salvá-los".

[[v23-35-5]]

^<<v23-35-5,5>>^ Quando ele vier, abrirá os olhos dos cegos e os ouvidos dos surdos.

[[v23-35-6]]

^<<v23-35-6,6>>^ Os aleijados pularão como o cervo, e os mudos cantarão de alegria. Fontes brotarão no deserto, e rios correrão na região desolada.

[[v23-35-7]]

^<<v23-35-7,7>>^ O solo ressecado se tornará um açude, e a terra sedenta, mananciais de água. O capim, a cana e o junco florescerão onde antes viviam os chacais do deserto.

[[v23-35-8]]

^<<v23-35-8,8>>^ Um caminho largo atravessará a terra antes desabitada e será chamado Caminho de Santidade; os impuros jamais passarão por ele. Será somente para os que andam nos caminhos de Deus; os tolos jamais andarão por ele.

[[v23-35-9]]

^<<v23-35-9,9>>^ Ao longo desse trajeto, leões não ficarão à espreita, nem qualquer outro animal feroz. Não haverá nenhum perigo; somente os redimidos andarão por ele.

[[v23-35-10]]

^<<v23-35-10,10>>^ Os que foram resgatados pelo SENHOR voltarão; entrarão cantando em Sião, coroados com alegria sem fim. A tristeza e o lamento desaparecerão, e eles ficarão cheios de alegria e felicidade.

'''

xref:023-isaias/023-isaias-034.adoc#v23-34-0[&#60; Capítulo Anterior] | <<v23-35-0,Topo>> | xref:023-isaias/023-isaias-036.adoc#v23-36-0[Próximo Capítulo &#62;]