include::./index.adoc[]

[[v23-14-0]]
=== Isaías, 14
// nvt ?, NVT - Nova Versão Transformadora

[[v23-14-1]]

^<<v23-14-1,1>>^ O SENHOR, porém, terá misericórdia dos descendentes de Jacó. Mais uma vez, escolherá Israel para ser seu povo. Ele os trará de volta e os estabelecerá em sua própria terra. Gente de muitas nações virá, se juntará a eles ali e se unirá ao povo de Israel.

[[v23-14-2]]

^<<v23-14-2,2>>^ As nações do mundo ajudarão o povo de Israel a retornar, e aqueles que vierem morar na terra do SENHOR os servirão. Os que conquistaram Israel serão conquistados, e Israel dominará seus opressores.

[[v23-14-3]]

^<<v23-14-3,3>>^ Naquele dia, quando o SENHOR der a seu povo descanso da tristeza, do medo e da terrível escravidão a que foram submetidos,

[[v23-14-4]]

^<<v23-14-4,4>>^ vocês zombarão do rei da Babilônia e dirão: "O homem poderoso foi destruído; acabou sua insolência.

[[v23-14-5]]

^<<v23-14-5,5>>^ O SENHOR esmagou seu poder perverso e derrubou seu reino de maldade.

[[v23-14-6]]

^<<v23-14-6,6>>^ Você feriu o povo com incontáveis golpes de fúria; cheio de ira, dominou as nações com tirania implacável.

[[v23-14-7]]

^<<v23-14-7,7>>^ Mas, por fim, a terra descansa tranquila; agora pode voltar a cantar!

[[v23-14-8]]

^<<v23-14-8,8>>^ Até as árvores do bosque, os ciprestes e os cedros do Líbano, entoam esta alegre canção: ‘Agora que você foi derrubado, ninguém virá nos derrubar!’.

[[v23-14-9]]

^<<v23-14-9,9>>^ "O lugar dos mortos se empolga com a sua chegada. Líderes e reis mortos há muito tempo se levantam para vê-lo.

[[v23-14-10]]

^<<v23-14-10,10>>^ A uma só voz eles clamam: ‘Agora você é tão fraco quanto nós!

[[v23-14-11]]

^<<v23-14-11,11>>^ Seu orgulho foi enterrado com você; o som da harpa em seu palácio cessou. Agora larvas são seu lençol, e vermes, sua coberta’.

[[v23-14-12]]

^<<v23-14-12,12>>^ "Como você caiu dos céus, ó estrela brilhante, filho da alvorada! Foi lançado à terra, você que destruía as nações.

[[v23-14-13]]

^<<v23-14-13,13>>^ Pois dizia consigo: ‘Subirei aos céus e colocarei meu trono acima das estrelas de Deus. Dominarei no monte dos deuses, nos lugares distantes do norte.

[[v23-14-14]]

^<<v23-14-14,14>>^ Subirei aos mais altos céus e serei como o Altíssimo’.

[[v23-14-15]]

^<<v23-14-15,15>>^ Em vez disso, será lançado ao lugar dos mortos, ao mais profundo abismo.

[[v23-14-16]]

^<<v23-14-16,16>>^ Todos olharão para você e perguntarão: ‘É esse o homem que fazia a terra tremer e abalava os reinos do mundo?

[[v23-14-17]]

^<<v23-14-17,17>>^ É esse o rei que destruiu a terra e a transformou em deserto? É ele que arrasava as grandes cidades e não tinha misericórdia de seus prisioneiros?’.

[[v23-14-18]]

^<<v23-14-18,18>>^ "Os reis das nações foram sepultados em glória majestosa, cada um em seu túmulo,

[[v23-14-19]]

^<<v23-14-19,19>>^ mas você será lançado fora de sua sepultura, como um galho inútil. Como um cadáver pisoteado, será jogado numa vala comum, com os que foram mortos na batalha. Descerá ao abismo

[[v23-14-20]]

^<<v23-14-20,20>>^ e não terá um sepultamento digno, pois destruiu sua nação e massacrou seu povo. Os descendentes de alguém tão perverso nunca mais receberão honras.

[[v23-14-21]]

^<<v23-14-21,21>>^ Matem os filhos desse homem! Que morram por causa dos pecados do pai, para que não se levantem a fim de conquistar a terra e encher o mundo com suas cidades".

[[v23-14-22]]

^<<v23-14-22,22>>^ Assim diz o SENHOR dos Exércitos: "Eu mesmo me levantei contra a Babilônia! Destruirei seus filhos e os filhos de seus filhos", diz o SENHOR.

[[v23-14-23]]

^<<v23-14-23,23>>^ "Transformarei a Babilônia em lugar para corujas, cheio de pântanos e brejos; varrerei a terra com a vassoura da destruição. Eu, o SENHOR dos Exércitos, falei!"

[[v23-14-24]]

^<<v23-14-24,24>>^ O SENHOR dos Exércitos jurou: "Tudo acontecerá como planejei; será conforme decidi.

[[v23-14-25]]

^<<v23-14-25,25>>^ Derrubarei os assírios quando estiverem em Israel e os pisotearei em meus montes. Meu povo não será mais seu escravo, nem se curvará sob o peso de suas cargas.

[[v23-14-26]]

^<<v23-14-26,26>>^ Tenho um plano para toda a terra; minha mão está sobre todas as nações.

[[v23-14-27]]

^<<v23-14-27,27>>^ O SENHOR dos Exércitos falou; quem pode mudar seus planos? Quando levanta sua mão, quem pode detê-la?".

[[v23-14-28]]

^<<v23-14-28,28>>^ Recebi esta mensagem no ano em que o rei Acaz morreu:

[[v23-14-29]]

^<<v23-14-29,29>>^ Não se alegrem, filisteus, por estar morto o rei que os feriu. Pois dessa cobra nascerá outra mais venenosa, uma serpente terrível e abrasadora!

[[v23-14-30]]

^<<v23-14-30,30>>^ Alimentarei os pobres em meus pastos, e os necessitados se deitarão em paz. Quanto a vocês, eu os matarei de fome e destruirei os poucos que restarem.

[[v23-14-31]]

^<<v23-14-31,31>>^ Lamentem junto aos portões! Chorem alto nas cidades! Derretam-se de medo, filisteus! Um exército poderoso vem do norte, como fumaça; cada soldado avança depressa, ansioso para lutar.

[[v23-14-32]]

^<<v23-14-32,32>>^ Que diremos aos mensageiros filisteus? Digam-lhes: "O SENHOR reconstruiu Sião; dentro de seus muros seu povo oprimido encontrará refúgio".

'''

xref:023-isaias/023-isaias-013.adoc#v23-13-0[&#60; Capítulo Anterior] | <<v23-14-0,Topo>> | xref:023-isaias/023-isaias-015.adoc#v23-15-0[Próximo Capítulo &#62;]