include::./index.adoc[]

[[v23-11-0]]
=== Isaías, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v23-11-1]]

^<<v23-11-1,1>>^ Do tronco da linhagem de Jessé brotará um renovo; sim, um novo Ramo que de suas raízes dará frutos.

[[v23-11-2]]

^<<v23-11-2,2>>^ E o Espírito do SENHOR estará sobre ele, o Espírito de sabedoria e discernimento, o Espírito de conselho e poder, o Espírito de conhecimento e temor do SENHOR.

[[v23-11-3]]

^<<v23-11-3,3>>^ Ele terá prazer em obedecer ao SENHOR; não julgará pela aparência, nem acusará com base em rumores.

[[v23-11-4]]

^<<v23-11-4,4>>^ Fará justiça aos pobres e tomará decisões imparciais em favor dos oprimidos. A terra estremecerá com a força de sua palavra, e o sopro de sua boca destruirá os perversos.

[[v23-11-5]]

^<<v23-11-5,5>>^ Vestirá a justiça como um cinto e a verdade como uma cinta nos quadris.

[[v23-11-6]]

^<<v23-11-6,6>>^ Naquele dia, o lobo viverá com o cordeiro, e o leopardo se deitará junto ao cabrito. O bezerro estará seguro perto do leão, e uma criança os guiará.

[[v23-11-7]]

^<<v23-11-7,7>>^ A vaca pastará perto do urso, e seus filhotes descansarão juntos; o leão comerá capim, como a vaca.

[[v23-11-8]]

^<<v23-11-8,8>>^ O bebê brincará em segurança perto da toca da cobra; sim, a criancinha colocará a mão num ninho de víboras.

[[v23-11-9]]

^<<v23-11-9,9>>^ Em todo o meu santo monte, não se fará mal nem haverá destruição, pois, como as águas enchem o mar, a terra estará cheia de gente que conhece o SENHOR.

[[v23-11-10]]

^<<v23-11-10,10>>^ Naquele dia, o descendente de Jessé será uma bandeira de salvação para todo o mundo. As nações se reunirão junto a ele, e a terra onde ele habita será um lugar glorioso.

[[v23-11-11]]

^<<v23-11-11,11>>^ Naquele dia, o Senhor estenderá a mão pela segunda vez, para trazer de volta o remanescente de seu povo, aqueles que restarem na Assíria e no norte do Egito, no sul do Egito, na Etiópia e em Elão, na Babilônia, em Hamate e nas distantes terras costeiras.

[[v23-11-12]]

^<<v23-11-12,12>>^ Levantará uma bandeira entre as nações e reunirá os exilados de Israel. Ajuntará o povo disperso de Judá, desde os confins da terra.

[[v23-11-13]]

^<<v23-11-13,13>>^ Então, por fim, acabará o ciúme entre Israel e Judá, e deixarão de ser rivais.

[[v23-11-14]]

^<<v23-11-14,14>>^ Unirão forças para vir sobre a Filístia no oeste; juntos, atacarão e saquearão as nações do leste. Ocuparão as terras de Edom e Moabe, e Amom lhes obedecerá.

[[v23-11-15]]

^<<v23-11-15,15>>^ O SENHOR abrirá um caminho seco no golfo do mar Vermelho, moverá a mão sobre o rio Eufrates e enviará um vento forte que o dividirá em sete riachos, para que possa ser atravessado a pé.

[[v23-11-16]]

^<<v23-11-16,16>>^ Fará uma estrada para o remanescente de seu povo, o remanescente que virá da Assíria, como fez por Israel muito tempo atrás, quando o povo voltou do Egito.

'''

xref:023-isaias/023-isaias-010.adoc#v23-10-0[&#60; Capítulo Anterior] | <<v23-11-0,Topo>> | xref:023-isaias/023-isaias-012.adoc#v23-12-0[Próximo Capítulo &#62;]