include::./index.adoc[]

[[v23-16-0]]
=== Isaías, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v23-16-1]]

^<<v23-16-1,1>>^ Enviem cordeiros desde Selá, como tributo ao governante da terra. Enviem-nos pelo deserto, para o monte da bela Sião.

[[v23-16-2]]

^<<v23-16-2,2>>^ As mulheres de Moabe foram abandonadas, como aves sem ninho, nas partes rasas do rio Arnom.

[[v23-16-3]]

^<<v23-16-3,3>>^ "Ajudem-nos!", elas clamam. "Defendam-nos como uma sombra ao meio-dia! Protejam os fugitivos; não nos traiam agora que escapamos.

[[v23-16-4]]

^<<v23-16-4,4>>^ Deixem que o povo de Moabe more com vocês; escondam nossos refugiados do inimigo, até que passe o terror." Quando a opressão e a destruição tiverem terminado, quando os invasores inimigos tiverem partido,

[[v23-16-5]]

^<<v23-16-5,5>>^ Deus estabelecerá como rei um dos descendentes de Davi. Ele reinará com misericórdia e verdade, julgará sempre com imparcialidade e buscará fazer o que é justo.

[[v23-16-6]]

^<<v23-16-6,6>>^ Ouvimos falar da arrogante Moabe, de seu orgulho, sua altivez e sua fúria, mas toda essa soberba desapareceu.

[[v23-16-7]]

^<<v23-16-7,7>>^ Toda a terra de Moabe chora, sim, todos em Moabe lamentam ao lembrar dos bolos de passas de Quir-Haresete; não resta um sequer.

[[v23-16-8]]

^<<v23-16-8,8>>^ As plantações de Hesbom estão abandonadas, os vinhedos de Sibma, desertos. Os governantes das nações derrubaram Moabe, essa bela videira. Seus ramos se estendiam para o norte, até a cidade de Jazar, e se espalhavam para o leste, até o deserto. Seus brotos se estendiam tão longe para o oeste que atravessavam o mar Morto.

[[v23-16-9]]

^<<v23-16-9,9>>^ Por isso, agora choro por Jazar e pelos vinhedos de Sibma; minhas lágrimas correrão por Hesbom e por Eleale. Não há mais gritos de alegria por seus frutos de verão e suas colheitas.

[[v23-16-10]]

^<<v23-16-10,10>>^ Encerrou-se a alegria, acabou-se a celebração pela colheita. Já não haverá cânticos nos vinhedos, nem gritos de exultação, ninguém pisará as uvas nos tanques de prensar; acabei com toda a alegria de suas colheitas.

[[v23-16-11]]

^<<v23-16-11,11>>^ O clamor de meu coração por Moabe é como o lamento de uma harpa; estou cheio de angústia por Quir-Haresete.

[[v23-16-12]]

^<<v23-16-12,12>>^ O povo de Moabe adorará em seus santuários idólatras, mas de nada lhe adiantará. Clamarão aos deuses em seus templos, mas ninguém poderá salvá-los.

[[v23-16-13]]

^<<v23-16-13,13>>^ O SENHOR já havia anunciado essas coisas sobre Moabe no passado.

[[v23-16-14]]

^<<v23-16-14,14>>^ Agora, porém, o SENHOR diz: "Dentro de três anos, contando cada dia, a glória de Moabe chegará ao fim. De sua grande população, restarão uns poucos sobreviventes".

'''

xref:023-isaias/023-isaias-015.adoc#v23-15-0[&#60; Capítulo Anterior] | <<v23-16-0,Topo>> | xref:023-isaias/023-isaias-017.adoc#v23-17-0[Próximo Capítulo &#62;]