include::./index.adoc[]

[[v23-5-0]]
=== Isaías, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v23-5-1]]

^<<v23-5-1,1>>^ Agora, cantarei a meu amado uma canção sobre seu vinhedo: Meu amado tinha um vinhedo numa colina muito fértil.

[[v23-5-2]]

^<<v23-5-2,2>>^ Ele arou a terra, tirou as pedras e plantou as melhores videiras. No meio do vinhedo, construiu uma torre de vigia e, junto às rochas, fez um tanque de prensar. Então esperou pela colheita de uvas doces, mas o vinhedo só produziu uvas amargas.

[[v23-5-3]]

^<<v23-5-3,3>>^ Agora, habitantes de Jerusalém e Judá, julguem entre mim e meu vinhedo.

[[v23-5-4]]

^<<v23-5-4,4>>^ O que mais poderia ter feito por meu vinhedo que já não fiz? Por que, quando esperava uvas doces, ele produziu uvas amargas?

[[v23-5-5]]

^<<v23-5-5,5>>^ Agora lhes digo o que farei com meu vinhedo: Removerei suas cercas e deixarei que seja destruído. Derrubarei seus muros e deixarei que seja pisoteado.

[[v23-5-6]]

^<<v23-5-6,6>>^ Farei dele um lugar desolado, onde as videiras não são podadas e a terra não é capinada, um lugar cheio de espinhos e mato. Darei ordem às nuvens para que não derramem chuva sobre ele.

[[v23-5-7]]

^<<v23-5-7,7>>^ A nação de Israel é o vinhedo do SENHOR dos Exércitos, o povo de Judá é seu jardim agradável. Ele esperava colher justiça, mas encontrou opressão. Esperava colher retidão, mas ouviu gritos de angústia.

[[v23-5-8]]

^<<v23-5-8,8>>^ Que aflição espera vocês que compram casas e mais casas, campos e mais campos, até não haver lugar para outros e vocês se tornarem os únicos donos da terra!

[[v23-5-9]]

^<<v23-5-9,9>>^ Mas eu ouvi o SENHOR dos Exércitos fazer um juramento solene: "Muitas casas ficarão desertas; até as belas mansões ficarão vazias.

[[v23-5-10]]

^<<v23-5-10,10>>^ Um vinhedo de dez jeiras não produzirá vinte litros de vinho; dez cestos grandes de sementes só produzirão um cesto de cereais".

[[v23-5-11]]

^<<v23-5-11,11>>^ Que aflição espera os que se levantam cedo pela manhã, para começar a beber, e passam a noite tomando vinho, para ficar embriagados.

[[v23-5-12]]

^<<v23-5-12,12>>^ Em suas festas sempre há vinho e belas músicas, de lira e harpa, tamborim e flauta, mas nunca pensam no SENHOR, não se dão conta do que ele faz.

[[v23-5-13]]

^<<v23-5-13,13>>^ Por isso meu povo irá para o exílio num lugar distante, pois não me conhece. Os nobres morrerão de fome, e a multidão morrerá de sede.

[[v23-5-14]]

^<<v23-5-14,14>>^ A sepultura saliva de ansiedade, com a boca bem aberta. Os mais importantes e os mais simples e toda a multidão embriagada serão devorados.

[[v23-5-15]]

^<<v23-5-15,15>>^ A humanidade será abatida, o povo será rebaixado; até os arrogantes baixarão o olhar em humilhação.

[[v23-5-16]]

^<<v23-5-16,16>>^ O SENHOR dos Exércitos, porém, será exaltado em sua justiça; a santidade de Deus será demonstrada em sua retidão.

[[v23-5-17]]

^<<v23-5-17,17>>^ Naquele dia, os cordeiros encontrarão bons pastos; as ovelhas gordas e os cabritos comerão entre as ruínas.

[[v23-5-18]]

^<<v23-5-18,18>>^ Que aflição espera os que arrastam sua perversidade com cordas feitas de mentiras, que arrastam atrás de si o pecado como quem puxa uma carroça!

[[v23-5-19]]

^<<v23-5-19,19>>^ Zombam de Deus e dizem: "Anda logo! Toma uma providência! Queremos ver o que és capaz de fazer. Que o Santo de Israel realize seu plano, pois queremos saber o que é".

[[v23-5-20]]

^<<v23-5-20,20>>^ Que aflição espera os que chamam o mal de bem e o bem de mal, a escuridão de luz e a luz de escuridão, o amargo de doce e o doce de amargo!

[[v23-5-21]]

^<<v23-5-21,21>>^ Que aflição espera os que são sábios aos próprios olhos e pensam ter entendimento!

[[v23-5-22]]

^<<v23-5-22,22>>^ Que aflição espera os que são heróis em tomar vinho e se gabam de quanta bebida conseguem ingerir!

[[v23-5-23]]

^<<v23-5-23,23>>^ Aceitam subornos para deixar o perverso em liberdade e negam justiça ao inocente.

[[v23-5-24]]

^<<v23-5-24,24>>^ Portanto, assim como o fogo consome a palha e o capim seco se desfaz com a chama, suas raízes apodrecerão e suas flores murcharão. Pois rejeitaram a lei do SENHOR dos Exércitos, desprezaram a palavra do Santo de Israel.

[[v23-5-25]]

^<<v23-5-25,25>>^ Por isso a ira do SENHOR se acende contra seu povo, por isso ele levantou sua mão para esmagá-los. Os montes estremecem, e os cadáveres do povo estão espalhados pelas ruas como lixo. Mesmo assim, a ira do SENHOR não se satisfará; sua mão ainda está levantada para castigar.

[[v23-5-26]]

^<<v23-5-26,26>>^ Ele enviará um sinal a nações distantes, assobiará para os que estão nos confins da terra; eles virão correndo.

[[v23-5-27]]

^<<v23-5-27,27>>^ Não se cansarão nem tropeçarão; ninguém descansará nem dormirá. Nenhum cinto estará solto, nenhuma correia de sandália se arrebentará.

[[v23-5-28]]

^<<v23-5-28,28>>^ Suas flechas estarão afiadas, seus arcos, prontos para a batalha. Os cascos de seus cavalos soltarão faíscas, as rodas de seus carros girarão como um turbilhão.

[[v23-5-29]]

^<<v23-5-29,29>>^ Rugirão como leões, como os leões mais fortes. Rosnarão e se lançarão sobre suas vítimas, e as levarão embora; ninguém poderá livrá-las.

[[v23-5-30]]

^<<v23-5-30,30>>^ Naquele dia, rugirão sobre suas vítimas como ruge o mar. Se alguém olhar por toda a terra, só verá trevas e aflição; até a luz será obscurecida pelas nuvens.

'''

xref:023-isaias/023-isaias-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaias/023-isaias-006.adoc#v23-6-0[Próximo Capítulo &#62;]