include::./index.adoc[]

[[v23-9-0]]
=== Isaías, 9
// nvt ?, NVT - Nova Versão Transformadora

[[v23-9-1]]

^<<v23-9-1,1>>^ Esse tempo de escuridão e desespero, no entanto, não durará para sempre. A terra de Zebulom e de Naftali será humilhada, mas no futuro a Galileia dos gentios, localizada junto à estrada entre o Jordão e o mar, se encherá de glória.

[[v23-9-2]]

^<<v23-9-2,2>>^ O povo que anda na escuridão verá grande luz. Para os que vivem na terra de trevas profundas, uma luz brilhará.

[[v23-9-3]]

^<<v23-9-3,3>>^ Tu multiplicarás a nação de Israel, e seu povo se alegrará. Eles se alegrarão diante de ti como os camponeses se alegram na colheita, como os guerreiros ao repartir os despojos.

[[v23-9-4]]

^<<v23-9-4,4>>^ Pois tu quebrarás o jugo de escravidão que os oprimia e levantarás o fardo que lhes pesava sobre os ombros. Quebrarás a vara do opressor, como fizeste ao destruir o exército de Midiã.

[[v23-9-5]]

^<<v23-9-5,5>>^ As botas dos guerreiros e os uniformes manchados de sangue das batalhas serão queimados; servirão de lenha para o fogo.

[[v23-9-6]]

^<<v23-9-6,6>>^ Pois um menino nos nasceu, um filho nos foi dado. O governo estará sobre seus ombros, e ele será chamado de Maravilhoso Conselheiro, Deus Poderoso, Pai Eterno e Príncipe da Paz.

[[v23-9-7]]

^<<v23-9-7,7>>^ Seu governo e sua paz jamais terão fim. Reinará com imparcialidade e justiça no trono de Davi, para todo o sempre. O zelo do SENHOR dos Exércitos fará que isso aconteça!

[[v23-9-8]]

^<<v23-9-8,8>>^ O Senhor se pronunciou contra Jacó, seu julgamento caiu sobre Israel.

[[v23-9-9]]

^<<v23-9-9,9>>^ Os habitantes de Israel e de Samaria, que falaram com tanto orgulho e arrogância, logo ficarão sabendo.

[[v23-9-10]]

^<<v23-9-10,10>>^ Disseram: "No lugar dos tijolos quebrados de nossas ruínas, colocaremos pedras trabalhadas, e no lugar das figueiras-bravas derrubadas, plantaremos cedros".

[[v23-9-11]]

^<<v23-9-11,11>>^ O SENHOR, porém, trará os inimigos de Rezim contra Israel e instigará seus adversários.

[[v23-9-12]]

^<<v23-9-12,12>>^ Os sírios do leste e os filisteus do oeste mostrarão suas presas e devorarão Israel. Mesmo assim, a ira do SENHOR não se satisfará; sua mão ainda está levantada para castigar.

[[v23-9-13]]

^<<v23-9-13,13>>^ Pois mesmo depois do castigo, o povo não se arrependerá; não buscará o SENHOR dos Exércitos.

[[v23-9-14]]

^<<v23-9-14,14>>^ Portanto, em um só dia, o SENHOR destruirá a cabeça e a cauda, o ramo da palmeira e o junco.

[[v23-9-15]]

^<<v23-9-15,15>>^ Os líderes de Israel são a cabeça, os profetas mentirosos são a cauda.

[[v23-9-16]]

^<<v23-9-16,16>>^ Pois esses líderes enganaram o povo e o conduziram pelo caminho da destruição.

[[v23-9-17]]

^<<v23-9-17,17>>^ Por isso o Senhor não se agrada dos jovens, nem mostra compaixão pelas viúvas e pelos órfãos. Pois todos são hipócritas perversos; todos falam tolices. Mesmo assim, a ira do SENHOR não se satisfará; sua mão ainda está levantada para castigar.

[[v23-9-18]]

^<<v23-9-18,18>>^ Essa maldade é como incêndio num matagal; consome não apenas os espinhos e o mato, mas também queima os bosques e faz subir nuvens de fumaça.

[[v23-9-19]]

^<<v23-9-19,19>>^ A terra ficará ressecada, por causa da fúria do SENHOR dos Exércitos. O povo servirá de lenha para o fogo, e ninguém poupará sequer seu irmão.

[[v23-9-20]]

^<<v23-9-20,20>>^ Atacarão o vizinho à direita, mas continuarão com fome. Devorarão o vizinho à esquerda, mas não se saciarão; por fim, comerão os próprios filhos.

[[v23-9-21]]

^<<v23-9-21,21>>^ Manassés se alimentará de Efraim, Efraim se alimentará de Manassés, ambos devorarão Judá. Mesmo assim, a ira do SENHOR não se satisfará; sua mão ainda está levantada para castigar.

'''

xref:023-isaias/023-isaias-008.adoc#v23-8-0[&#60; Capítulo Anterior] | <<v23-9-0,Topo>> | xref:023-isaias/023-isaias-010.adoc#v23-10-0[Próximo Capítulo &#62;]