include::./index.adoc[]

[[v23-57-0]]
=== Isaías, 57
// nvt ?, NVT - Nova Versão Transformadora

[[v23-57-1]]

^<<v23-57-1,1>>^ O justo perece, e o fiel muitas vezes morre cedo, mas ninguém parece se importar nem se perguntar por quê. Ninguém parece entender que Deus os poupa do mal que virá.

[[v23-57-2]]

^<<v23-57-2,2>>^ Pois quem anda por caminhos íntegros descansará em paz quando morrer.

[[v23-57-3]]

^<<v23-57-3,3>>^ "Mas vocês, filhos de feiticeiras, venham cá! Aproximem-se, filhos de adúlteros e de prostitutas!

[[v23-57-4]]

^<<v23-57-4,4>>^ De quem vocês zombam, fazendo caretas e mostrando a língua? Vocês são filhos de pecadores e de mentirosos!

[[v23-57-5]]

^<<v23-57-5,5>>^ Adoram seus ídolos com ardente paixão, debaixo dos carvalhos e de toda árvore verdejante. Sacrificam os filhos nos vales, entre as rochas dos desfiladeiros.

[[v23-57-6]]

^<<v23-57-6,6>>^ Seus deuses são as pedras lisas nos vales; vocês os adoram com ofertas derramadas e ofertas de cereais. Eles, e não eu, são sua herança; pensam que tudo isso me agrada?

[[v23-57-7]]

^<<v23-57-7,7>>^ Cometeram adultério em todos os montes altos; ali adoraram seus ídolos e foram infiéis a mim.

[[v23-57-8]]

^<<v23-57-8,8>>^ Puseram símbolos pagãos nos batentes e atrás das portas. Abandonaram-me e foram para a cama com esses deuses detestáveis. Comprometeram-se com eles e gostam de olhar seus corpos nus.

[[v23-57-9]]

^<<v23-57-9,9>>^ Foram até Moloque, com óleo de azeite e muitos perfumes, e enviaram para longe seus mensageiros, até mesmo ao mundo dos mortos.

[[v23-57-10]]

^<<v23-57-10,10>>^ Cansaram-se de tanto procurar, mas nunca desistiram. O desejo renovou suas forças, de modo que não ficaram exaustos.

[[v23-57-11]]

^<<v23-57-11,11>>^ "Vocês temem esses ídolos? Eles os apavoram? Foi por isso que mentiram para mim e se esqueceram de mim e de minhas palavras? Foi por causa do meu longo silêncio que deixaram de me temer?

[[v23-57-12]]

^<<v23-57-12,12>>^ Agora mostrarei a todos essas suas boas obras; nenhuma delas os ajudará.

[[v23-57-13]]

^<<v23-57-13,13>>^ Vejamos se seus ídolos os salvarão quando clamarem por socorro. Até um sopro de vento é capaz de derrubá-los; basta alguém respirar sobre eles para que tombem! Mas quem confia em mim herdará a terra e possuirá meu santo monte."

[[v23-57-14]]

^<<v23-57-14,14>>^ Deus diz: "Preparem o caminho! Tirem do meio da estrada as rochas e as pedras, para que meu povo passe!".

[[v23-57-15]]

^<<v23-57-15,15>>^ O Alto e Sublime, que vive na eternidade, o Santo diz: "Habito nos lugares altos e santos, e também com os de espírito oprimido e humilde. Dou novo ânimo aos abatidos e coragem aos de coração arrependido.

[[v23-57-16]]

^<<v23-57-16,16>>^ Porque não lutarei contra vocês para sempre, nem ficarei eternamente irado. Se o fizesse, todos morreriam, sim, todos os seres que eu criei.

[[v23-57-17]]

^<<v23-57-17,17>>^ Por causa da cobiça do meu povo, fiquei furioso e os castiguei. Afastei-me deles, mas continuaram a seguir seu caminho obstinado.

[[v23-57-18]]

^<<v23-57-18,18>>^ Tenho visto o que fazem, mas ainda assim irei curá-los. Eu os guiarei, consolarei os que choram,

[[v23-57-19]]

^<<v23-57-19,19>>^ porei em seus lábios palavras de louvor. Que eles tenham muita paz, tanto os que estão perto como os que estão longe", diz o SENHOR, que os cura.

[[v23-57-20]]

^<<v23-57-20,20>>^ "Os perversos, porém, são como o mar agitado que nunca se aquieta e revolve lama e sujeira sem parar.

[[v23-57-21]]

^<<v23-57-21,21>>^ Para os perversos não há paz", diz o meu Deus.

'''

xref:023-isaias/023-isaias-056.adoc#v23-56-0[&#60; Capítulo Anterior] | <<v23-57-0,Topo>> | xref:023-isaias/023-isaias-058.adoc#v23-58-0[Próximo Capítulo &#62;]