include::./index.adoc[]

[[v23-38-0]]
=== Isaías, 38
// nvt ?, NVT - Nova Versão Transformadora

[[v23-38-1]]

^<<v23-38-1,1>>^ Por esse tempo, Ezequias ficou doente e estava para morrer. O profeta Isaías, filho de Amoz, foi visitá-lo e transmitiu-lhe a seguinte mensagem: "Assim diz o SENHOR: ‘Ponha suas coisas em ordem, pois você vai morrer. Não se recuperará dessa doença’".

[[v23-38-2]]

^<<v23-38-2,2>>^ Quando Ezequias ouviu isso, virou o rosto para a parede e orou ao SENHOR:

[[v23-38-3]]

^<<v23-38-3,3>>^ "Ó SENHOR, lembra-te de como sempre te servi com fidelidade e devoção, e de como sempre fiz o que é certo aos teus olhos". Depois, o rei chorou amargamente.

[[v23-38-4]]

^<<v23-38-4,4>>^ Então Isaías recebeu esta mensagem do SENHOR:

[[v23-38-5]]

^<<v23-38-5,5>>^ "Volte a Ezequias e diga-lhe: Assim diz o SENHOR, o Deus de seu antepassado Davi: ‘Ouvi sua oração e vi suas lágrimas. Acrescentarei quinze anos à sua vida

[[v23-38-6]]

^<<v23-38-6,6>>^ e livrarei você e esta cidade do rei da Assíria. Sim, defenderei esta cidade.

[[v23-38-7]]

^<<v23-38-7,7>>^ "‘Este é o sinal do SENHOR de que cumprirá o que prometeu.

[[v23-38-8]]

^<<v23-38-8,8>>^ Farei a sombra do sol recuar dez graus no relógio de sol de Acaz’". Então a sombra no relógio de sol de Acaz recuou dez graus.

[[v23-38-9]]

^<<v23-38-9,9>>^ Quando o rei Ezequias se recuperou, escreveu este poema:

[[v23-38-10]]

^<<v23-38-10,10>>^ Eu disse: "No pleno vigor de minha vida, devo entrar no lugar dos mortos? Serei roubado do restante de meus anos?".

[[v23-38-11]]

^<<v23-38-11,11>>^ Eu disse: "Nunca mais verei o SENHOR Deus na terra dos vivos. Nunca mais verei pessoa alguma, nem estarei com os que vivem neste mundo.

[[v23-38-12]]

^<<v23-38-12,12>>^ Minha vida foi levada embora, como uma tenda de pastor na tempestade. Foi cortada como o tecelão corta o tecido do tear; de repente, minha vida se acabou.

[[v23-38-13]]

^<<v23-38-13,13>>^ Esperei a noite inteira com paciência, mas era como se leões me despedaçassem; de repente, minha vida se acabou.

[[v23-38-14]]

^<<v23-38-14,14>>^ Delirante, chilreava como a andorinha ou como o grou, depois gemia como a pomba. Meus olhos se cansaram de olhar para o céu à espera de socorro. Estou aflito, Senhor; responde-me!".

[[v23-38-15]]

^<<v23-38-15,15>>^ Mas o que posso dizer? Ele mesmo enviou esta doença. Agora, andarei humildemente toda a vida, por causa da angústia que senti.

[[v23-38-16]]

^<<v23-38-16,16>>^ Senhor, tua disciplina é boa, pois conduz à vida e à saúde. Tu restauras minha saúde e permites que eu viva!

[[v23-38-17]]

^<<v23-38-17,17>>^ Sim, a angústia me fez bem, pois tu me livraste da morte e perdoaste todos os meus pecados.

[[v23-38-18]]

^<<v23-38-18,18>>^ Pois os mortos não podem exaltar-te; não podem entoar louvores. Aqueles que descem à cova já não podem esperar em tua fidelidade.

[[v23-38-19]]

^<<v23-38-19,19>>^ Somente os vivos te louvam como faço hoje; cada geração fala de tua fidelidade à geração seguinte.

[[v23-38-20]]

^<<v23-38-20,20>>^ Sim, o SENHOR está disposto a me curar! Com instrumentos de cordas, entoarei louvores todos os dias de minha vida, no templo do SENHOR.

[[v23-38-21]]

^<<v23-38-21,21>>^ Isaías tinha dito aos servos de Ezequias: "Preparem uma pasta de figos e coloquem-na sobre a ferida, e Ezequias se recuperará".

[[v23-38-22]]

^<<v23-38-22,22>>^ Ezequias tinha perguntado: "Que sinal o SENHOR dará como prova de que irei ao templo do SENHOR?".

'''

xref:023-isaias/023-isaias-037.adoc#v23-37-0[&#60; Capítulo Anterior] | <<v23-38-0,Topo>> | xref:023-isaias/023-isaias-039.adoc#v23-39-0[Próximo Capítulo &#62;]