include::./index.adoc[]

[[v23-48-0]]
=== Isaías, 48
// nvt ?, NVT - Nova Versão Transformadora

[[v23-48-1]]

^<<v23-48-1,1>>^ "Ouça-me, ó família de Jacó, vocês que são chamados pelo nome de Israel e vieram da linhagem de Judá. Escutem, vocês que juram em nome do Senhor e invocam o Deus de Israel, mas não em verdade e em justiça.

[[v23-48-2]]

^<<v23-48-2,2>>^ Vocês se chamam de habitantes da cidade santa e dizem que confiam no Deus de Israel, cujo nome é SENHOR dos Exércitos.

[[v23-48-3]]

^<<v23-48-3,3>>^ Muito tempo atrás, eu lhes disse o que aconteceria; então agi de modo repentino, e todas as minhas previsões se cumpriram.

[[v23-48-4]]

^<<v23-48-4,4>>^ Pois sei como vocês são teimosos; seu pescoço é rígido como ferro, e sua cabeça, dura como bronze.

[[v23-48-5]]

^<<v23-48-5,5>>^ Por isso lhes falei o que aconteceria, anunciei de antemão o que faria, para que vocês não dissessem: ‘Meus ídolos fizeram isso; minha imagem de madeira e meu deus de metal ordenaram que acontecesse!’.

[[v23-48-6]]

^<<v23-48-6,6>>^ Vocês ouviram minhas previsões e as viram se cumprir, mas não querem admitir. Agora lhes anuncio coisas novas, segredos que vocês ainda não conheciam.

[[v23-48-7]]

^<<v23-48-7,7>>^ São coisas novíssimas, não do passado, para que não digam: ‘Já sabíamos disso!’.

[[v23-48-8]]

^<<v23-48-8,8>>^ "Sim, eu lhes falarei de coisas totalmente novas, sobre as quais nunca ouviram. Pois sei muito bem que são traidores, rebeldes desde que nasceram.

[[v23-48-9]]

^<<v23-48-9,9>>^ Contudo, por causa do meu nome e minha honra, refrearei minha ira e não os exterminarei.

[[v23-48-10]]

^<<v23-48-10,10>>^ Eu os purifiquei, não como a prata é purificada, mas na fornalha do sofrimento.

[[v23-48-11]]

^<<v23-48-11,11>>^ Faço isso por minha própria causa, sim, por minha própria causa. Não permitirei que meu nome seja manchado e não repartirei minha glória com outros."

[[v23-48-12]]

^<<v23-48-12,12>>^ "Ouça-me, ó família de Jacó, Israel, meu escolhido! Somente eu sou Deus, o Primeiro e o Último.

[[v23-48-13]]

^<<v23-48-13,13>>^ Minha mão lançou os alicerces da terra, minha mão direita estendeu os céus lá no alto. Quando chamo as estrelas, elas aparecem todas em ordem."

[[v23-48-14]]

^<<v23-48-14,14>>^ Acaso algum de seus ídolos lhes disse isso? Venham todos vocês e ouçam: O SENHOR escolheu seu aliado e o usará para acabar com o império da Babilônia e destruir os exércitos babilônios.

[[v23-48-15]]

^<<v23-48-15,15>>^ "Eu disse: Eu o chamei! Sim, eu o enviarei nesta missão e o ajudarei a ter êxito.

[[v23-48-16]]

^<<v23-48-16,16>>^ Cheguem mais perto e ouçam; desde o princípio, eu lhes disse claramente o que aconteceria." Agora, o SENHOR Soberano e seu Espírito me enviaram com esta mensagem:

[[v23-48-17]]

^<<v23-48-17,17>>^ Assim diz o SENHOR, seu Redentor, o Santo de Israel: "Eu sou o SENHOR, seu Deus, que lhe ensina o que é bom e o conduz pelo caminho que deve seguir.

[[v23-48-18]]

^<<v23-48-18,18>>^ Quem dera tivesse prestado atenção às minhas ordens! Teria experimentado paz que flui como um rio, justiça que o cobriria como as ondas do mar.

[[v23-48-19]]

^<<v23-48-19,19>>^ Seus descendentes seriam incontáveis, como a areia da praia! Não teria sido necessário destruí-lo, nem eliminar o nome de sua família".

[[v23-48-20]]

^<<v23-48-20,20>>^ Saiam do cativeiro! Deixem a Babilônia e os babilônios! Proclamem esta mensagem! Anunciem-na em alta voz para os confins da terra! O SENHOR resgatou seus servos, o povo de Israel.

[[v23-48-21]]

^<<v23-48-21,21>>^ Não passaram sede quando ele os guiou pelo deserto. Ele partiu a rocha, e água jorrou para que bebessem.

[[v23-48-22]]

^<<v23-48-22,22>>^ "Mas para os perversos não há paz", diz o SENHOR.

'''

xref:023-isaias/023-isaias-047.adoc#v23-47-0[&#60; Capítulo Anterior] | <<v23-48-0,Topo>> | xref:023-isaias/023-isaias-049.adoc#v23-49-0[Próximo Capítulo &#62;]