include::./index.adoc[]

[[v23-32-0]]
=== Isaías, 32
// nvt ?, NVT - Nova Versão Transformadora

[[v23-32-1]]

^<<v23-32-1,1>>^ Vejam, aí vem um rei justo! Seus príncipes governarão com retidão.

[[v23-32-2]]

^<<v23-32-2,2>>^ Cada um será como abrigo contra o vento e refúgio contra a tempestade, como riacho no deserto e sombra de uma grande pedra em terra seca.

[[v23-32-3]]

^<<v23-32-3,3>>^ Então todos que têm olhos verão a verdade, e todos que têm ouvidos a ouvirão.

[[v23-32-4]]

^<<v23-32-4,4>>^ Até os que se iram depressa terão bom senso e entendimento, e os que gaguejam falarão com clareza.

[[v23-32-5]]

^<<v23-32-5,5>>^ Naquele dia, os tolos não serão considerados heróis, e as pessoas sem caráter não serão respeitadas.

[[v23-32-6]]

^<<v23-32-6,6>>^ Pois os tolos dizem tolices e planejam o mal. Praticam a perversidade e espalham falsos ensinamentos a respeito do SENHOR. Negam comida aos famintos e não dão água aos sedentos.

[[v23-32-7]]

^<<v23-32-7,7>>^ As artimanhas dessa gente sem caráter são perversas; tramam planos maldosos e mentem para condenar os pobres, mesmo quando a causa dos pobres é justa.

[[v23-32-8]]

^<<v23-32-8,8>>^ Os generosos, porém, planejam fazer o que é generoso e permanecem firmes em sua generosidade.

[[v23-32-9]]

^<<v23-32-9,9>>^ Ouçam, mulheres negligentes; prestem atenção, vocês que são tão arrogantes.

[[v23-32-10]]

^<<v23-32-10,10>>^ Em breve, pouco mais de um ano, vocês, presunçosas, ficarão apavoradas. Suas plantações de frutas nada produzirão, e não haverá colheitas.

[[v23-32-11]]

^<<v23-32-11,11>>^ Tremam, mulheres negligentes, deixem de lado sua arrogância. Arranquem suas lindas roupas e vistam-se de pano de saco.

[[v23-32-12]]

^<<v23-32-12,12>>^ Batam no peito em lamento por suas belas propriedades e videiras frutíferas.

[[v23-32-13]]

^<<v23-32-13,13>>^ Pois suas terras ficarão cobertas de espinhos e mato; seus lares alegres e suas cidades felizes desaparecerão.

[[v23-32-14]]

^<<v23-32-14,14>>^ O palácio será abandonado, e a cidade, sempre agitada, ficará vazia. Jumentos selvagens andarão soltos, e rebanhos pastarão nas fortalezas e nas torres de vigia,

[[v23-32-15]]

^<<v23-32-15,15>>^ até que, por fim, o Espírito seja derramado do céu sobre nós. Então o deserto se tornará campo fértil, e o campo fértil produzirá colheitas fartas.

[[v23-32-16]]

^<<v23-32-16,16>>^ A retidão governará no deserto, e a justiça, no campo fértil.

[[v23-32-17]]

^<<v23-32-17,17>>^ E essa justiça trará paz; haverá sossego e confiança para sempre.

[[v23-32-18]]

^<<v23-32-18,18>>^ Meu povo viverá em paz, tranquilo em seu lar; terá descanso e segurança.

[[v23-32-19]]

^<<v23-32-19,19>>^ Ainda que os bosques sejam destruídos e a cidade seja arrasada,

[[v23-32-20]]

^<<v23-32-20,20>>^ o povo será abençoado. Onde quer que semeiem, terão colheitas fartas; seu gado e seus jumentos pastarão livremente.

'''

xref:023-isaias/023-isaias-031.adoc#v23-31-0[&#60; Capítulo Anterior] | <<v23-32-0,Topo>> | xref:023-isaias/023-isaias-033.adoc#v23-33-0[Próximo Capítulo &#62;]