include::./index.adoc[]

[[v23-7-0]]
=== Isaías, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v23-7-1]]

^<<v23-7-1,1>>^ Quando Acaz, filho de Jotão e neto de Uzias, era rei de Judá, Rezim, rei da Síria, e Peca, filho de Remalias, rei de Israel, saíram para atacar Jerusalém. Contudo, não conseguiram executar seu plano.

[[v23-7-2]]

^<<v23-7-2,2>>^ Havia chegado à corte de Judá a seguinte notícia: "A Síria se aliou com Israel contra nós!". O coração do rei e de seu povo estremeceu de medo, como árvores se agitam numa tempestade.

[[v23-7-3]]

^<<v23-7-3,3>>^ Então o SENHOR disse a Isaías: "Pegue seu filho, Sear-Jasube, e vá encontrar-se com o rei Acaz. Ele estará no final do aqueduto que abastece o tanque superior, perto do caminho para o campo onde se lava roupa.

[[v23-7-4]]

^<<v23-7-4,4>>^ Diga a Acaz que pare de se preocupar e que não precisa ter medo da ira ardente daquelas duas brasas apagadas, Rezim, rei da Síria, e Peca, filho de Remalias.

[[v23-7-5]]

^<<v23-7-5,5>>^ É verdade que os reis da Síria e de Israel tramam contra ele e dizem:

[[v23-7-6]]

^<<v23-7-6,6>>^ ‘Atacaremos Judá e a conquistaremos; então colocaremos o filho de Tabeal para reinar sobre Judá’.

[[v23-7-7]]

^<<v23-7-7,7>>^ Mas assim diz o SENHOR Soberano: "Essa invasão não acontecerá; jamais ocorrerá,

[[v23-7-8]]

^<<v23-7-8,8>>^ pois a Síria não é mais forte que sua capital, Damasco, e Damasco não é mais forte que seu rei, Rezim. Quanto a Israel, em sessenta e cinco anos, será esmagada e completamente destruída.

[[v23-7-9]]

^<<v23-7-9,9>>^ Israel não é mais forte que sua capital, Samaria, e Samaria não é mais forte que seu rei, Peca, filho de Remalias. Se vocês não crerem com firmeza, não permanecerão firmes".

[[v23-7-10]]

^<<v23-7-10,10>>^ Depois, o SENHOR enviou esta mensagem ao rei Acaz:

[[v23-7-11]]

^<<v23-7-11,11>>^ "Peça ao SENHOR, seu Deus, um sinal de confirmação. Pode ser algo difícil, alto como os céus ou profundo como o lugar dos mortos".

[[v23-7-12]]

^<<v23-7-12,12>>^ O rei Acaz, porém, respondeu: "Não porei o SENHOR à prova desse modo".

[[v23-7-13]]

^<<v23-7-13,13>>^ Então o profeta disse: "Ouçam bem, descendentes de Davi! Não basta esgotarem a paciência das pessoas? Agora também querem esgotar a paciência de meu Deus?

[[v23-7-14]]

^<<v23-7-14,14>>^ Por isso, o Senhor mesmo lhes dará um sinal. Vejam! A virgem ficará grávida! Ela dará à luz um filho e o chamará de Emanuel.

[[v23-7-15]]

^<<v23-7-15,15>>^ Quando essa criança tiver idade suficiente para escolher o bem e rejeitar o mal, comerá coalhada e mel.

[[v23-7-16]]

^<<v23-7-16,16>>^ Pois, antes de a criança chegar a essa idade, as terras dos dois reis que vocês tanto temem ficarão desertas.

[[v23-7-17]]

^<<v23-7-17,17>>^ "Então o SENHOR trará sobre vocês, sua nação e sua família, coisas como nunca houve desde que Israel se separou de Judá; trará contra vocês o rei da Assíria!".

[[v23-7-18]]

^<<v23-7-18,18>>^ Naquele dia, o SENHOR assobiará para chamar o exército do sul do Egito e o exército da Assíria, e eles os cercarão como enxames de moscas e abelhas.

[[v23-7-19]]

^<<v23-7-19,19>>^ Virão em grandes multidões e ocuparão as regiões férteis e também os vales desolados, as cavernas e os lugares tomados de espinhos.

[[v23-7-20]]

^<<v23-7-20,20>>^ Naquele dia, o Senhor alugará uma "navalha" que virá de além do rio Eufrates — o rei da Assíria — e a usará para raspar tudo: sua terra, suas plantações e seu povo.

[[v23-7-21]]

^<<v23-7-21,21>>^ Naquele dia, o camponês terá sorte se lhe sobrarem uma vaca e duas ovelhas.

[[v23-7-22]]

^<<v23-7-22,22>>^ Ainda assim, haverá leite suficiente para todos, pois restarão poucas pessoas na terra. Comerão coalhada e mel até ficarem satisfeitos.

[[v23-7-23]]

^<<v23-7-23,23>>^ Naquele dia, os vinhedos prósperos, que hoje valem mil peças de prata, se tornarão terrenos cheios de espinhos e mato.

[[v23-7-24]]

^<<v23-7-24,24>>^ Toda a terra ficará coberta de espinhos e mato, e será uma região de caça cheia de animais selvagens.

[[v23-7-25]]

^<<v23-7-25,25>>^ Ninguém irá às encostas férteis das colinas, onde antes cresciam jardins, pois estarão tomadas de espinhos e mato. Ali bois e ovelhas pastarão.

'''

xref:023-isaias/023-isaias-006.adoc#v23-6-0[&#60; Capítulo Anterior] | <<v23-7-0,Topo>> | xref:023-isaias/023-isaias-008.adoc#v23-8-0[Próximo Capítulo &#62;]