include::./index.adoc[]

[[v23-25-0]]
=== Isaías, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v23-25-1]]

^<<v23-25-1,1>>^ Ó SENHOR, honrarei e louvarei teu nome, pois és meu Deus. Fazes coisas maravilhosas! Tu as planejaste há muito tempo e agora as realizaste.

[[v23-25-2]]

^<<v23-25-2,2>>^ Transformas cidades poderosas em montes de ruínas; cidades com muros fortes se tornam escombros. Belos palácios em terras distantes são destruídos e jamais serão reconstruídos.

[[v23-25-3]]

^<<v23-25-3,3>>^ Por isso, nações fortes declararão tua glória; povos cruéis te temerão.

[[v23-25-4]]

^<<v23-25-4,4>>^ Mas tu, SENHOR, és fortaleza para os pobres, torre de refúgio para os necessitados em sua angústia. És abrigo contra a tempestade e sombra contra o calor. Pois os atos opressores dos cruéis são como tempestade que açoita um muro,

[[v23-25-5]]

^<<v23-25-5,5>>^ como o calor implacável do deserto. Tu, porém, calas o rugido das nações estrangeiras; como a sombra de uma nuvem diminui o calor implacável, assim os cânticos de soberba dos cruéis são silenciados.

[[v23-25-6]]

^<<v23-25-6,6>>^ Em Jerusalém, o SENHOR dos Exércitos oferecerá um grande banquete para todos os povos do mundo. Será um banquete delicioso, com vinho puro e envelhecido e carne da melhor qualidade.

[[v23-25-7]]

^<<v23-25-7,7>>^ Ali removerá a nuvem de tristeza, a sombra escura que cobre toda a terra.

[[v23-25-8]]

^<<v23-25-8,8>>^ Ele engolirá a morte para sempre; o SENHOR Soberano enxugará todas as lágrimas! Removerá para sempre todo insulto, contra sua terra e seu povo. O SENHOR falou!

[[v23-25-9]]

^<<v23-25-9,9>>^ Naquele dia, o povo dirá: "Este é nosso Deus! Confiamos nele, e ele nos salvou! Este é o SENHOR, em quem confiamos; alegremo-nos em seu livramento!".

[[v23-25-10]]

^<<v23-25-10,10>>^ Pois a mão do SENHOR descansará sobre Jerusalém. Moabe, porém, será esmagada; será como palha pisada e deixada para apodrecer.

[[v23-25-11]]

^<<v23-25-11,11>>^ Deus empurrará para baixo o povo de Moabe, como um nadador empurra a água para baixo com as mãos. Acabará com seu orgulho e com todas as suas obras perversas.

[[v23-25-12]]

^<<v23-25-12,12>>^ Os muros altos de Moabe serão demolidos; serão derrubados por terra, até o pó.

'''

xref:023-isaias/023-isaias-024.adoc#v23-24-0[&#60; Capítulo Anterior] | <<v23-25-0,Topo>> | xref:023-isaias/023-isaias-026.adoc#v23-26-0[Próximo Capítulo &#62;]