include::./index.adoc[]

[[v23-61-0]]
=== Isaías, 61
// nvt ?, NVT - Nova Versão Transformadora

[[v23-61-1]]

^<<v23-61-1,1>>^ O Espírito do SENHOR Soberano está sobre mim, pois o SENHOR me ungiu para levar boas-novas aos pobres. Ele me enviou para consolar os de coração quebrantado e para proclamar que os cativos serão soltos e os prisioneiros, libertos.

[[v23-61-2]]

^<<v23-61-2,2>>^ Ele me enviou para dizer aos que choram que é chegado o tempo do favor do Senhor e o dia da ira de Deus contra seus inimigos.

[[v23-61-3]]

^<<v23-61-3,3>>^ A todos que choram em Sião ele dará uma bela coroa em vez de cinzas, uma alegre bênção em vez de lamento, louvores festivos em vez de desespero. Em sua justiça, serão como grandes carvalhos que o SENHOR plantou para sua glória.

[[v23-61-4]]

^<<v23-61-4,4>>^ Reconstruirão as antigas ruínas, restaurarão os lugares desde muito destruídos e renovarão as cidades devastadas há gerações e gerações.

[[v23-61-5]]

^<<v23-61-5,5>>^ Estrangeiros serão seus servos; alimentarão seus rebanhos, lavrarão seus campos e cuidarão de suas videiras.

[[v23-61-6]]

^<<v23-61-6,6>>^ Vocês serão chamados de sacerdotes do SENHOR, ministros de nosso Deus. Das riquezas das nações se alimentarão e se orgulharão de possuírem os tesouros delas.

[[v23-61-7]]

^<<v23-61-7,7>>^ Em lugar de vergonha e desonra, desfrutarão uma porção dupla de honra. Terão prosperidade em dobro em sua terra e alegria sem fim.

[[v23-61-8]]

^<<v23-61-8,8>>^ "Pois eu, o SENHOR, amo a justiça e odeio o roubo e a maldade. Recompensarei meu povo fielmente e farei com ele aliança permanente.

[[v23-61-9]]

^<<v23-61-9,9>>^ Seus descendentes serão reconhecidos e honrados entre as nações. Todos saberão que eles são um povo abençoado pelo SENHOR."

[[v23-61-10]]

^<<v23-61-10,10>>^ É imensa a minha alegria no SENHOR, meu Deus! Pois ele me vestiu com roupas de salvação e pôs sobre mim um manto de justiça. Sou como o noivo com suas vestes de casamento, como a noiva com suas joias.

[[v23-61-11]]

^<<v23-61-11,11>>^ O SENHOR Soberano mostrará sua justiça às nações do mundo; todos o louvarão! Será como um jardim no começo da primavera, quando as plantas brotam por toda parte.

'''

xref:023-isaias/023-isaias-060.adoc#v23-60-0[&#60; Capítulo Anterior] | <<v23-61-0,Topo>> | xref:023-isaias/023-isaias-062.adoc#v23-62-0[Próximo Capítulo &#62;]