include::./index.adoc[]

[[v23-51-0]]
=== Isaías, 51
// nvt ?, NVT - Nova Versão Transformadora

[[v23-51-1]]

^<<v23-51-1,1>>^ "Ouçam-me, todos que procuram justiça, todos que buscam o SENHOR! Olhem para a rocha da qual foram cortados, para a pedreira de onde foram extraídos.

[[v23-51-2]]

^<<v23-51-2,2>>^ Sim, pensem em Abraão, seu antepassado, e em Sara, que deu à luz sua nação. Abraão era apenas um quando eu o chamei, mas o abençoei e o tornei uma grande nação."

[[v23-51-3]]

^<<v23-51-3,3>>^ O SENHOR voltará a consolar Sião e terá compaixão de suas ruínas. Seu deserto florescerá como o Éden, sua terra desolada, como o jardim do SENHOR. Ali haverá alegria e exultação, e cânticos de gratidão encherão o ar.

[[v23-51-4]]

^<<v23-51-4,4>>^ "Ouça-me, povo meu; escute-me, nação minha, pois minha lei será proclamada, e meu juízo se tornará luz para as nações.

[[v23-51-5]]

^<<v23-51-5,5>>^ Minha justiça logo virá, minha salvação está a caminho; meu braço forte julgará as nações. Todas as terras distantes olharão para mim e aguardarão com esperança meu braço poderoso.

[[v23-51-6]]

^<<v23-51-6,6>>^ Levantem os olhos para os céus lá no alto e olhem para a terra embaixo. Os céus desaparecerão como fumaça, e a terra se gastará como uma peça de roupa. Os habitantes da terra morrerão como moscas, mas minha salvação é permanente; meu governo justo não terá fim!

[[v23-51-7]]

^<<v23-51-7,7>>^ "Ouçam-me, vocês que sabem a diferença entre certo e errado, que têm minha lei no coração. Não se assustem com o desprezo das pessoas, nem temam seus insultos.

[[v23-51-8]]

^<<v23-51-8,8>>^ Pois a traça os comerá como se fossem uma roupa; o verme os devorará como se fossem lã. Minha justiça, porém, durará para sempre; minha salvação continuará de geração em geração!"

[[v23-51-9]]

^<<v23-51-9,9>>^ Desperta, desperta, ó SENHOR! Veste-te de força! Move teu braço poderoso! Levanta-te como fizeste nos dias passados, quando mataste o Egito, o dragão do Nilo.

[[v23-51-10]]

^<<v23-51-10,10>>^ Não és o mesmo hoje, aquele que secou as águas e fez um caminho no fundo do mar para que seu povo atravessasse?

[[v23-51-11]]

^<<v23-51-11,11>>^ Os que foram resgatados pelo SENHOR voltarão; entrarão em Sião cantando, coroados de alegria sem fim. Tristeza e lamento desaparecerão, e eles se encherão de alegria e exultação.

[[v23-51-12]]

^<<v23-51-12,12>>^ "Sim, sou eu quem os consola; por que, então, temem simples mortais, que murcham como o capim e desaparecem?

[[v23-51-13]]

^<<v23-51-13,13>>^ Vocês, porém, se esqueceram do SENHOR, seu Criador, aquele que estendeu os céus e lançou os alicerces da terra. Viverão com medo de opressores humanos? Continuarão a temer a ira de seus inimigos? Onde está a fúria deles agora?

[[v23-51-14]]

^<<v23-51-14,14>>^ Em breve, todos vocês cativos serão libertos; prisão, fome e morte não serão seu destino!

[[v23-51-15]]

^<<v23-51-15,15>>^ Pois eu sou o SENHOR, seu Deus, que agita os mares e faz as ondas rugirem; meu nome é SENHOR dos Exércitos.

[[v23-51-16]]

^<<v23-51-16,16>>^ Pus minhas palavras em sua boca e o escondi em segurança em minha mão. Estendi os céus e lancei os alicerces da terra. Sou eu quem diz a Israel: ‘Tu és meu povo!’."

[[v23-51-17]]

^<<v23-51-17,17>>^ Desperte, desperte, ó Jerusalém! Você bebeu do cálice da ira do SENHOR, bebeu do cálice do terror, virou-o até a última gota.

[[v23-51-18]]

^<<v23-51-18,18>>^ Não sobrou nenhum de seus filhos para pegá-la pela mão e guiá-la.

[[v23-51-19]]

^<<v23-51-19,19>>^ Duas calamidades a atingiram: desolação e destruição, fome e guerra. E quem restou para ter compaixão de você? Quem restou para consolá-la?

[[v23-51-20]]

^<<v23-51-20,20>>^ Seus filhos desmaiaram e estão caídos pelas ruas, indefesos como antílopes pegos numa rede. O SENHOR derramou sua ira, sim, Deus os repreendeu.

[[v23-51-21]]

^<<v23-51-21,21>>^ Agora, porém, ouçam isto, vocês que estão aflitos e completamente embriagados, mas não com vinho.

[[v23-51-22]]

^<<v23-51-22,22>>^ Assim diz o SENHOR Soberano, seu Deus e Defensor: "Vejam, tirei de suas mãos o cálice terrível; não beberão mais de minha ira.

[[v23-51-23]]

^<<v23-51-23,23>>^ Agora, darei esse cálice aos que os atormentaram e lhes disseram: ‘Pisaremos em vocês no pó e andaremos sobre suas costas’".

'''

xref:023-isaias/023-isaias-050.adoc#v23-50-0[&#60; Capítulo Anterior] | <<v23-51-0,Topo>> | xref:023-isaias/023-isaias-052.adoc#v23-52-0[Próximo Capítulo &#62;]