include::./index.adoc[]

[[v23-44-0]]
=== Isaías, 44
// nvt ?, NVT - Nova Versão Transformadora

[[v23-44-1]]

^<<v23-44-1,1>>^ "Agora ouça-me, meu servo Jacó, Israel, meu escolhido.

[[v23-44-2]]

^<<v23-44-2,2>>^ O SENHOR, que o criou e que o ajuda, diz: Não tema, ó Jacó, meu servo, ó querido Israel, meu escolhido.

[[v23-44-3]]

^<<v23-44-3,3>>^ Pois eu derramarei água para matar sua sede e regar seus campos secos. Derramarei meu Espírito sobre seus descendentes e minha bênção sobre suas futuras gerações.

[[v23-44-4]]

^<<v23-44-4,4>>^ Eles crescerão como capim regado, como salgueiros à beira do rio.

[[v23-44-5]]

^<<v23-44-5,5>>^ Alguns afirmarão: ‘Pertenço ao SENHOR’, outros dirão: ‘Sou descendente de Jacó’. Alguns escreverão nas mãos o nome do Senhor e tomarão para si o nome Israel."

[[v23-44-6]]

^<<v23-44-6,6>>^ Assim diz o SENHOR, Rei e Redentor de Israel, o SENHOR dos Exércitos: "Eu sou o Primeiro e o Último; não há outro Deus.

[[v23-44-7]]

^<<v23-44-7,7>>^ Quem é semelhante a mim? Que se apresente à minha frente! Que faça o que eu fiz desde os tempos antigos, quando estabeleci um povo e anunciei seu futuro.

[[v23-44-8]]

^<<v23-44-8,8>>^ Não tremam, não tenham medo; acaso não lhes anunciei meus propósitos há muito tempo? Vocês são minhas testemunhas: há outro Deus além de mim? Não! Não há nenhuma outra Rocha, nenhuma sequer!".

[[v23-44-9]]

^<<v23-44-9,9>>^ Como são tolos os que fabricam ídolos! Esses objetos que tanto estimam não têm valor algum. Os que adoram ídolos não sabem disso, por isso serão envergonhados.

[[v23-44-10]]

^<<v23-44-10,10>>^ Quem senão um tolo faria seu próprio deus, um ídolo que em nada pode ajudá-lo?

[[v23-44-11]]

^<<v23-44-11,11>>^ Todos que adoram ídolos serão envergonhados, bem como todos esses artesãos, simples mortais que se dizem capazes de fazer um deus. Ainda que unam forças, estarão unidos em terror e vergonha.

[[v23-44-12]]

^<<v23-44-12,12>>^ O ferreiro trabalha na forja para criar uma ferramenta afiada; martela e modela com toda a força. De tanto trabalhar, sente fome e fraqueza, fica sedento e desfalece.

[[v23-44-13]]

^<<v23-44-13,13>>^ O escultor, por sua vez, mede um bloco de madeira e nele desenha um esboço. Trabalha com cinzel e plaina e entalha a imagem de uma pessoa. Dá à imagem beleza humana e a coloca num pequeno santuário.

[[v23-44-14]]

^<<v23-44-14,14>>^ Corta cedros, escolhe cipreste e carvalho, planta um pinheiro no bosque, para que a chuva o faça crescer.

[[v23-44-15]]

^<<v23-44-15,15>>^ Então, usa parte da madeira para fazer fogo e com ele se aquece e assa o pão. Depois, pega o que resta e faz para si um deus para adorar. Faz um ídolo e se curva diante dele.

[[v23-44-16]]

^<<v23-44-16,16>>^ Queima parte da árvore para assar carne, come e se mantém aquecido. "Que fogo bom!", diz. "Já não sinto frio!"

[[v23-44-17]]

^<<v23-44-17,17>>^ Então, pega o que resta e faz seu deus: um ídolo esculpido. Curva-se diante dele e o adora, ora a ele e diz: "Livra-me, pois tu és meu deus!".

[[v23-44-18]]

^<<v23-44-18,18>>^ Quanta estupidez e ignorância! Seus olhos estão fechados, e ele não consegue ver, sua mente está fechada, e não consegue compreender.

[[v23-44-19]]

^<<v23-44-19,19>>^ Aquele que fez o ídolo não para e pensa: "Queimei metade da madeira para me aquecer e para assar o pão e a carne; como é possível o restante ser um deus? Vou me curvar para adorar um pedaço de madeira?".

[[v23-44-20]]

^<<v23-44-20,20>>^ Tal pessoa se alimenta de cinzas e engana a si mesma, confia em algo que em nada pode ajudá-la. E, no entanto, não é capaz de perguntar: "Será que este ídolo que tenho em mãos não é uma mentira?".

[[v23-44-21]]

^<<v23-44-21,21>>^ "Preste atenção, ó Jacó, pois você é meu servo, ó Israel. Eu, o SENHOR, o formei e não me esquecerei de você.

[[v23-44-22]]

^<<v23-44-22,22>>^ Afastei seus pecados para longe, como uma nuvem; dispersei suas maldades, como a névoa da manhã. Volte para mim, pois paguei o preço do seu resgate."

[[v23-44-23]]

^<<v23-44-23,23>>^ Cantem, ó céus, pois o SENHOR fez esta maravilha! Gritem de alegria, ó profundezas da terra! Irrompam em cânticos, ó montes, bosques e todas as árvores! Pois o SENHOR resgatou Jacó e é glorificado em Israel.

[[v23-44-24]]

^<<v23-44-24,24>>^ Assim diz o SENHOR, seu Redentor e Criador: "Eu sou o SENHOR, que fiz todas as coisas; sozinho estendi os céus. Quem estava comigo quando criei a terra?

[[v23-44-25]]

^<<v23-44-25,25>>^ Mostro que os falsos profetas são mentirosos e faço os adivinhos parecerem tolos. Faço os sábios errarem suas previsões e assim provo que são insensatos.

[[v23-44-26]]

^<<v23-44-26,26>>^ Mas cumpro as previsões de meus profetas! Por meio deles, digo a Jerusalém: ‘Este lugar voltará a ser habitado’, e às cidades de Judá: ‘Vocês serão reconstruídas; restaurarei todas as suas ruínas’.

[[v23-44-27]]

^<<v23-44-27,27>>^ Quando eu falar aos rios: ‘Sequem’, eles secarão.

[[v23-44-28]]

^<<v23-44-28,28>>^ Quando disser a respeito de Ciro: ‘Ele é meu pastor’, ele certamente fará tudo que eu quiser. Ele dirá: ‘Reconstruam Jerusalém!’ e ordenará: ‘Restaurem o templo!’".

'''

xref:023-isaias/023-isaias-043.adoc#v23-43-0[&#60; Capítulo Anterior] | <<v23-44-0,Topo>> | xref:023-isaias/023-isaias-045.adoc#v23-45-0[Próximo Capítulo &#62;]