include::./index.adoc[]

[[v23-13-0]]
=== Isaías, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v23-13-1]]

^<<v23-13-1,1>>^ Isaías, filho de Amoz, recebeu esta mensagem acerca da Babilônia:

[[v23-13-2]]

^<<v23-13-2,2>>^ "Levantem uma bandeira no topo descoberto de uma colina; convoquem um exército contra a Babilônia. Quando eles entrarem nos palácios dos grandes e poderosos, acenem com a mão para encorajá-los.

[[v23-13-3]]

^<<v23-13-3,3>>^ Eu, o SENHOR, consagrei esses soldados; sim, chamei guerreiros valentes para executar minha ira, e eles se alegrarão quando eu for exaltado".

[[v23-13-4]]

^<<v23-13-4,4>>^ Ouçam o barulho nos montes! Escutem os grandes exércitos marchando! São ruídos e gritos de muitas nações; o SENHOR dos Exércitos reuniu essas tropas.

[[v23-13-5]]

^<<v23-13-5,5>>^ Vêm de países distantes, dos mais longínquos horizontes. São as armas do SENHOR para executar sua ira; com elas destruirá toda a terra.

[[v23-13-6]]

^<<v23-13-6,6>>^ Gritem de terror, pois o dia do SENHOR chegou, o dia em que o Todo-poderoso virá para destruir.

[[v23-13-7]]

^<<v23-13-7,7>>^ Todo braço está paralisado de medo, todo coração se derrete,

[[v23-13-8]]

^<<v23-13-8,8>>^ todos estão apavorados. São tomados de dores agudas de aflição, como as dores da mulher no parto. Apavorados, olham uns para os outros, com o rosto ardendo de medo.

[[v23-13-9]]

^<<v23-13-9,9>>^ Vejam, o dia do SENHOR está chegando, o dia terrível de sua fúria e ira ardente! A terra ficará desolada, e os pecadores serão destruídos.

[[v23-13-10]]

^<<v23-13-10,10>>^ Os céus acima deles escurecerão, e as estrelas deixarão de brilhar. O sol estará escuro ao nascer, e a lua não iluminará.

[[v23-13-11]]

^<<v23-13-11,11>>^ "Eu, o SENHOR, castigarei o mundo por sua maldade, os perversos por seu pecado. Esmagarei a pretensão dos arrogantes, humilharei o orgulho dos poderosos.

[[v23-13-12]]

^<<v23-13-12,12>>^ Tornarei as pessoas mais escassas que o ouro, mais raras que o ouro puro de Ofir.

[[v23-13-13]]

^<<v23-13-13,13>>^ Pois sacudirei os céus; a terra se moverá de seu lugar, quando o SENHOR dos Exércitos mostrar sua fúria, no dia de sua ira ardente."

[[v23-13-14]]

^<<v23-13-14,14>>^ Todos na Babilônia correrão como uma gazela perseguida, como ovelhas sem pastor. Tentarão encontrar seu povo e fugir para sua terra.

[[v23-13-15]]

^<<v23-13-15,15>>^ Quem for capturado será morto, atravessado com a espada.

[[v23-13-16]]

^<<v23-13-16,16>>^ Suas crianças serão massacradas diante de seus olhos; suas casas serão saqueadas, e suas esposas, violentadas.

[[v23-13-17]]

^<<v23-13-17,17>>^ "Vejam, instigarei o reino da Média contra a Babilônia; não se poderá comprá-lo com prata, nem suborná-lo com ouro.

[[v23-13-18]]

^<<v23-13-18,18>>^ Matarão os jovens com flechas, não terão misericórdia dos bebês indefesos, nem compaixão das crianças."

[[v23-13-19]]

^<<v23-13-19,19>>^ A Babilônia, o mais glorioso dos reinos, o esplendor e o orgulho dos caldeus, será devastada como Sodoma e Gomorra, quando Deus as destruiu.

[[v23-13-20]]

^<<v23-13-20,20>>^ A Babilônia jamais voltará a ser habitada; permanecerá vazia geração após geração. Nômades não acamparão ali, pastores não levarão suas ovelhas para passar a noite.

[[v23-13-21]]

^<<v23-13-21,21>>^ Animais do deserto habitarão na cidade arruinada, criaturas uivantes rondarão as casas. Corujas viverão entre as ruínas, bodes selvagens ali saltarão.

[[v23-13-22]]

^<<v23-13-22,22>>^ Hienas uivarão nas fortalezas, chacais farão tocas nos palácios luxuosos. Os dias da Babilônia estão contados; logo chegará a hora de sua destruição.

'''

xref:023-isaias/023-isaias-012.adoc#v23-12-0[&#60; Capítulo Anterior] | <<v23-13-0,Topo>> | xref:023-isaias/023-isaias-014.adoc#v23-14-0[Próximo Capítulo &#62;]