include::./index.adoc[]

[[v23-50-0]]
=== Isaías, 50
// nvt ?, NVT - Nova Versão Transformadora

[[v23-50-1]]

^<<v23-50-1,1>>^ Assim diz o SENHOR: "Acaso sua mãe foi mandada embora porque me divorciei dela? Vendi vocês como escravos para meus credores? Não, foram vendidos por causa de seus pecados, e sua mãe se foi por causa da rebeldia de vocês.

[[v23-50-2]]

^<<v23-50-2,2>>^ Por que ninguém apareceu quando eu vim? Por que ninguém respondeu quando chamei? É porque não tenho poder para libertar? Pois eu, com uma simples palavra, seco o mar e transformo rios em desertos cheios de peixes mortos.

[[v23-50-3]]

^<<v23-50-3,3>>^ Visto os céus com escuridão e cubro-os com roupas de luto".

[[v23-50-4]]

^<<v23-50-4,4>>^ O SENHOR Soberano me deu suas palavras de sabedoria, para que eu saiba consolar os cansados. Todas as manhãs ele me acorda e abre meu entendimento para ouvi-lo.

[[v23-50-5]]

^<<v23-50-5,5>>^ O SENHOR Soberano falou comigo, e eu ouvi; não me rebelei nem me afastei.

[[v23-50-6]]

^<<v23-50-6,6>>^ Ofereci as costas aos que me batiam e a face aos que me arrancavam a barba. Não escondi o rosto daqueles que zombavam de mim e em mim cuspiam.

[[v23-50-7]]

^<<v23-50-7,7>>^ Porque o SENHOR Soberano me ajuda, não serei envergonhado. Por isso, firmei o rosto como uma pedra e sei que não serei envergonhado.

[[v23-50-8]]

^<<v23-50-8,8>>^ Aquele que me faz justiça está perto; quem se atreverá a se queixar de mim? Onde estão meus acusadores? Que se apresentem!

[[v23-50-9]]

^<<v23-50-9,9>>^ Vejam, o SENHOR Soberano está do meu lado! Quem me declarará culpado? Todos os meus inimigos serão destruídos como roupas velhas, comidas pelas traças.

[[v23-50-10]]

^<<v23-50-10,10>>^ Quem entre vocês teme o Senhor e obedece a seu servo? Se vocês caminham na escuridão, sem um raio de luz sequer, confiem no Senhor e apoiem-se em seu Deus.

[[v23-50-11]]

^<<v23-50-11,11>>^ Mas tenham cuidado, vocês que vivem em sua própria luz e se aquecem em seu próprio fogo. Esta é a recompensa que receberão de mim: em breve cairão em grande tormento.

'''

xref:023-isaias/023-isaias-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaias/023-isaias-051.adoc#v23-51-0[Próximo Capítulo &#62;]