include::./index.adoc[]

[[v23-31-0]]
=== Isaías, 31
// nvt ?, NVT - Nova Versão Transformadora

[[v23-31-1]]

^<<v23-31-1,1>>^ Que aflição espera os que buscam a ajuda do Egito, que confiam em seus cavalos, carros e cavaleiros e dependem da força de exércitos humanos em vez de olhar para o SENHOR, o Santo de Israel!

[[v23-31-2]]

^<<v23-31-2,2>>^ Em sua sabedoria, o SENHOR enviará grande calamidade; não mudará de ideia. Ele se levantará contra os perversos e contra aqueles que os ajudam.

[[v23-31-3]]

^<<v23-31-3,3>>^ Pois os egípcios são simples mortais, e não Deus! Seus cavalos são apenas carne, e não espírito! Quando o SENHOR levantar a mão contra eles, tropeçarão aqueles que ajudam e aqueles que são ajudados; todos cairão e morrerão juntos.

[[v23-31-4]]

^<<v23-31-4,4>>^ Pois o SENHOR me disse: "Quando um leão jovem e forte ruge sobre a ovelha que ele matou, não se assusta com os gritos nem com os ruídos de um bando de pastores. De igual modo, o SENHOR dos Exércitos descerá e lutará sobre o monte Sião.

[[v23-31-5]]

^<<v23-31-5,5>>^ O SENHOR dos Exércitos sobrevoará Jerusalém e a protegerá como uma ave protege o ninho. Defenderá e livrará a cidade, passará sobre ela e a salvará".

[[v23-31-6]]

^<<v23-31-6,6>>^ Ó israelitas, embora sejam rebeldes e perversos, voltem para o SENHOR.

[[v23-31-7]]

^<<v23-31-7,7>>^ Chegará o dia em que cada um de vocês jogará fora os ídolos de ouro e as imagens de prata que suas mãos pecaminosas fizeram.

[[v23-31-8]]

^<<v23-31-8,8>>^ "Os assírios serão destruídos, mas não por espadas de homens. A espada de Deus os ferirá; entrarão em pânico e fugirão. Os jovens assírios serão levados como escravos.

[[v23-31-9]]

^<<v23-31-9,9>>^ Até os mais fortes tremerão de pavor, e os príncipes fugirão ao ver suas bandeiras de guerra." Assim diz o SENHOR, cujo fogo queima em Sião, cujas chamas ardem em Jerusalém.

'''

xref:023-isaias/023-isaias-030.adoc#v23-30-0[&#60; Capítulo Anterior] | <<v23-31-0,Topo>> | xref:023-isaias/023-isaias-032.adoc#v23-32-0[Próximo Capítulo &#62;]