include::./index.adoc[]

[[v23-46-0]]
=== Isaías, 46
// nvt ?, NVT - Nova Versão Transformadora

[[v23-46-1]]

^<<v23-46-1,1>>^ Bel e Nebo, os deuses da Babilônia, se curvam enquanto são postos no chão. São transportados em carros de boi, e os pobres animais tropeçam por causa do peso;

[[v23-46-2]]

^<<v23-46-2,2>>^ tanto os ídolos como seus donos se curvam. Os deuses não podem proteger o povo, e o povo não pode proteger os deuses; vão juntos para o cativeiro.

[[v23-46-3]]

^<<v23-46-3,3>>^ "Ouçam-me, descendentes de Jacó, todos vocês que restam em Israel. Eu os carreguei desde que nasceram, cuidei de vocês desde que estavam no ventre.

[[v23-46-4]]

^<<v23-46-4,4>>^ Serei o seu Deus por toda a sua vida, até que seus cabelos fiquem brancos. Eu os criei e cuidarei de vocês, eu os carregarei e os salvarei.

[[v23-46-5]]

^<<v23-46-5,5>>^ "A quem vocês me compararão? Que imagem usarão para me representar?

[[v23-46-6]]

^<<v23-46-6,6>>^ Alguns gastam seu ouro e sua prata e contratam um artesão para lhes fazer um deus; então se curvam diante dele e o adoram!

[[v23-46-7]]

^<<v23-46-7,7>>^ Levam-no consigo sobre os ombros e, quando o põem no lugar, ali ele fica; não pode nem mesmo se mexer! Quando alguém lhe faz uma oração, ele não responde; não pode livrar as pessoas de suas aflições.

[[v23-46-8]]

^<<v23-46-8,8>>^ "Não se esqueçam disto; tenham-no em mente! Lembrem-se bem, ó rebeldes!

[[v23-46-9]]

^<<v23-46-9,9>>^ Lembrem-se do que fiz no passado, pois somente eu sou Deus; eu sou Deus, e não há outro semelhante a mim.

[[v23-46-10]]

^<<v23-46-10,10>>^ Só eu posso lhes anunciar, desde já, o que acontecerá no futuro. Todos os meus planos se cumprirão, pois faço tudo que desejo.

[[v23-46-11]]

^<<v23-46-11,11>>^ Chamarei do leste uma ave de rapina veloz, um líder de uma terra distante, para que cumpra minhas ordens. O que eu disse, isso farei.

[[v23-46-12]]

^<<v23-46-12,12>>^ "Ouça-me, povo teimoso que está longe da justiça.

[[v23-46-13]]

^<<v23-46-13,13>>^ Pois estou pronto para endireitar as coisas, não no futuro distante, mas agora! Estou pronto para salvar Sião e para mostrar minha glória a Israel."

'''

xref:023-isaias/023-isaias-045.adoc#v23-45-0[&#60; Capítulo Anterior] | <<v23-46-0,Topo>> | xref:023-isaias/023-isaias-047.adoc#v23-47-0[Próximo Capítulo &#62;]