include::./index.adoc[]

[[v24-37-0]]
=== Jeremias, 37
// nvt ?, NVT - Nova Versão Transformadora

[[v24-37-1]]

^<<v24-37-1,1>>^ Zedequias, filho de Josias, foi sucessor de Joaquim, filho de Jeoaquim, no trono de Judá. Foi nomeado por Nabucodonosor, rei da Babilônia.

[[v24-37-2]]

^<<v24-37-2,2>>^ Mas nem Zedequias, nem seus servos, nem o povo que restou na terra de Judá deram ouvidos ao que o SENHOR tinha dito por intermédio do profeta Jeremias.

[[v24-37-3]]

^<<v24-37-3,3>>^ Ainda assim, o rei Zedequias enviou Jucal, filho de Selemias, e o sacerdote Sofonias, filho de Maseeias, para pedirem a Jeremias: "Ore por nós ao SENHOR, nosso Deus".

[[v24-37-4]]

^<<v24-37-4,4>>^ Jeremias ainda não havia sido preso, de modo que podia circular livremente entre o povo.

[[v24-37-5]]

^<<v24-37-5,5>>^ Nessa época, o exército do faraó do Egito partiu de sua terra, preparado para guerrear. Quando o exército babilônio soube disso, suspendeu o cerco de Jerusalém.

[[v24-37-6]]

^<<v24-37-6,6>>^ Então o SENHOR deu esta mensagem a Jeremias:

[[v24-37-7]]

^<<v24-37-7,7>>^ "Assim diz o SENHOR, o Deus de Israel: O rei de Judá os enviou para me consultar a respeito do que acontecerá. Digam-lhe: ‘Embora o exército do faraó tenha vindo para ajudá-los, logo voltará ao Egito.

[[v24-37-8]]

^<<v24-37-8,8>>^ Os babilônios retornarão, conquistarão esta cidade e a queimarão de alto a baixo’.

[[v24-37-9]]

^<<v24-37-9,9>>^ "Assim diz o SENHOR: Não se iludam, imaginando que os babilônios foram embora para sempre. Eles voltarão!

[[v24-37-10]]

^<<v24-37-10,10>>^ Ainda que vocês destruíssem todo o exército babilônio e restasse apenas um punhado de sobreviventes feridos, eles sairiam de suas tendas e queimariam esta cidade de alto a baixo".

[[v24-37-11]]

^<<v24-37-11,11>>^ Quando o exército babilônio se retirou de Jerusalém por causa do exército do faraó, que se aproximava,

[[v24-37-12]]

^<<v24-37-12,12>>^ Jeremias resolveu sair da cidade para ir ao território de Benjamim e tomar posse de sua propriedade ali, entre seus parentes.

[[v24-37-13]]

^<<v24-37-13,13>>^ Quando passava pelo portão de Benjamim, um guarda o prendeu e disse: "Você está desertando para o lado dos babilônios!". O guarda que o prendeu foi Jerias, filho de Selemias e neto de Hananias.

[[v24-37-14]]

^<<v24-37-14,14>>^ "Não é verdade!", disse Jeremias. "Não estou desertando para o lado dos babilônios." Jerias, porém, não deu ouvidos e levou Jeremias aos oficiais.

[[v24-37-15]]

^<<v24-37-15,15>>^ Eles ficaram furiosos com Jeremias e mandaram açoitá-lo e prendê-lo na casa do secretário Jônatas, que havia sido transformada em prisão.

[[v24-37-16]]

^<<v24-37-16,16>>^ Jeremias foi colocado numa cela do calabouço e ali ficou por muitos dias.

[[v24-37-17]]

^<<v24-37-17,17>>^ Mais tarde, em segredo, o rei Zedequias mandou buscar Jeremias e levá-lo ao palácio, onde lhe perguntou: "Você tem alguma mensagem do SENHOR?". "Sim, tenho", disse Jeremias. "Você será entregue ao rei da Babilônia."

[[v24-37-18]]

^<<v24-37-18,18>>^ Então Jeremias perguntou ao rei: "Que crime cometi? O que fiz contra o rei, contra seus servos ou contra o povo para ser preso?

[[v24-37-19]]

^<<v24-37-19,19>>^ Onde estão seus profetas, que lhe disseram que o rei da Babilônia não atacaria nem o rei nem esta terra?

[[v24-37-20]]

^<<v24-37-20,20>>^ Suplico que me ouça, ó meu senhor, o rei. Não me mande de volta para o calabouço na casa do secretário Jônatas, pois morrerei naquele lugar".

[[v24-37-21]]

^<<v24-37-21,21>>^ Então o rei Zedequias ordenou que Jeremias fosse levado ao pátio da guarda do palácio e ficasse preso ali. O rei também ordenou que Jeremias recebesse um pão fresco diariamente enquanto houvesse pão na cidade. Assim, Jeremias foi colocado na prisão do palácio.

'''

xref:024-jeremias/024-jeremias-036.adoc#v24-36-0[&#60; Capítulo Anterior] | <<v24-37-0,Topo>> | xref:024-jeremias/024-jeremias-038.adoc#v24-38-0[Próximo Capítulo &#62;]