include::./index.adoc[]

[[v24-28-0]]
=== Jeremias, 28
// nvt ?, NVT - Nova Versão Transformadora

[[v24-28-1]]

^<<v24-28-1,1>>^ Naquele mesmo ano, o quarto ano do reinado de Zedequias, rei de Judá, no mês de agosto, Hananias, filho de Azur, um profeta de Gibeom, se dirigiu a mim publicamente no templo, diante de todos os sacerdotes e do povo, e disse:

[[v24-28-2]]

^<<v24-28-2,2>>^ "Assim diz o SENHOR dos Exércitos, o Deus de Israel: ‘Removerei do seu pescoço o jugo do rei da Babilônia.

[[v24-28-3]]

^<<v24-28-3,3>>^ Dentro de dois anos, trarei de volta todos os objetos preciosos do templo que o rei Nabucodonosor levou para a Babilônia.

[[v24-28-4]]

^<<v24-28-4,4>>^ Também trarei de volta Joaquim, filho de Jeoaquim, rei de Judá, e todos os outros exilados de Judá levados para a Babilônia. Certamente quebrarei o jugo que o rei da Babilônia colocou sobre seu pescoço. Eu, o SENHOR, falei!’".

[[v24-28-5]]

^<<v24-28-5,5>>^ Jeremias respondeu a Hananias diante de todos os sacerdotes e do povo que estava no templo do SENHOR:

[[v24-28-6]]

^<<v24-28-6,6>>^ "Amém! Que sua profecia se cumpra! Espero que o SENHOR faça tudo que você anunciou. Espero que ele traga de volta da Babilônia os objetos preciosos do templo e todos os exilados.

[[v24-28-7]]

^<<v24-28-7,7>>^ Agora, porém, ouça as palavras que lhe digo na presença de todo o povo.

[[v24-28-8]]

^<<v24-28-8,8>>^ Os antigos profetas, que vieram antes de você e de mim, falaram contra muitas nações e grandes reinos, e sempre advertiram a respeito de guerra, calamidade e doença.

[[v24-28-9]]

^<<v24-28-9,9>>^ Portanto, um profeta que anuncia paz precisa esperar que suas previsões se cumpram antes de ser considerado, de fato, enviado pelo SENHOR".

[[v24-28-10]]

^<<v24-28-10,10>>^ Então o profeta Hananias tirou do pescoço de Jeremias o jugo e o quebrou em pedaços.

[[v24-28-11]]

^<<v24-28-11,11>>^ E disse novamente a todo o povo: "Assim diz o SENHOR: ‘Assim como este jugo foi quebrado, dentro de dois anos quebrarei o jugo de opressão de todas as nações que agora estão sujeitas a Nabucodonosor, rei da Babilônia’". Depois disso, Jeremias saiu dali.

[[v24-28-12]]

^<<v24-28-12,12>>^ Logo após o confronto com Hananias, o SENHOR deu esta mensagem a Jeremias:

[[v24-28-13]]

^<<v24-28-13,13>>^ "Vá e diga a Hananias: ‘Assim diz o SENHOR: Você quebrou o jugo de madeira, mas em seu lugar colocou um jugo de ferro.

[[v24-28-14]]

^<<v24-28-14,14>>^ O SENHOR dos Exércitos, o Deus de Israel, diz: Coloquei um jugo de ferro sobre o pescoço de todas essas nações para serem escravas de Nabucodonosor, rei da Babilônia. Coloquei tudo debaixo de seu controle, até os animais selvagens’".

[[v24-28-15]]

^<<v24-28-15,15>>^ Então Jeremias disse a Hananias: "Ouça, Hananias! O SENHOR não enviou você, mas o povo acredita em suas mentiras.

[[v24-28-16]]

^<<v24-28-16,16>>^ Por isso, assim diz o SENHOR: ‘Você morrerá. Sua vida chegará ao fim ainda este ano, pois você se rebelou contra o SENHOR’".

[[v24-28-17]]

^<<v24-28-17,17>>^ Naquele mesmo ano, dois meses depois, o profeta Hananias morreu.

'''

xref:024-jeremias/024-jeremias-027.adoc#v24-27-0[&#60; Capítulo Anterior] | <<v24-28-0,Topo>> | xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[Próximo Capítulo &#62;]