include::./index.adoc[]

[[v24-10-0]]
=== Jeremias, 10
// nvt ?, NVT - Nova Versão Transformadora

[[v24-10-1]]

^<<v24-10-1,1>>^ Ó Israel, ouça esta palavra do SENHOR para você!

[[v24-10-2]]

^<<v24-10-2,2>>^ Assim diz o SENHOR: "Não se comportem como as outras nações, que tentam ler seu futuro nas estrelas. Não tenham medo de suas previsões, ainda que elas encham outras nações de terror.

[[v24-10-3]]

^<<v24-10-3,3>>^ Os costumes dessas nações são inúteis: cortam uma árvore, e dela o artesão esculpe um ídolo.

[[v24-10-4]]

^<<v24-10-4,4>>^ Enfeitam-no com ouro e prata e fixam-no com martelo e pregos, para que não tombe.

[[v24-10-5]]

^<<v24-10-5,5>>^ Seus deuses são como espantalhos numa plantação de pepinos. Não são capazes de falar e precisam ser carregados, pois não conseguem andar. Não tenham medo desses deuses, pois não podem lhes fazer nem mal, nem bem".

[[v24-10-6]]

^<<v24-10-6,6>>^ SENHOR, não há ninguém semelhante a ti! Tu és grande, e teu nome é poderoso.

[[v24-10-7]]

^<<v24-10-7,7>>^ Quem não te temeria, ó Rei das nações? Esse título pertence a ti somente! Entre todos os sábios da terra e em todos os reinos do mundo, não há ninguém semelhante a ti.

[[v24-10-8]]

^<<v24-10-8,8>>^ Os que adoram ídolos são tolos e insensatos; adoram objetos feitos de madeira.

[[v24-10-9]]

^<<v24-10-9,9>>^ Trazem placas de prata batida de Társis e ouro de Ufaz e entregam a artesãos habilidosos, que fazem seus ídolos. Vestem-nos com mantos azuis e roxos, feitos por hábeis alfaiates.

[[v24-10-10]]

^<<v24-10-10,10>>^ Mas o SENHOR é o único Deus verdadeiro; ele é o Deus vivo e o Rei eterno! A terra treme com sua ira; as nações não podem suportar sua fúria.

[[v24-10-11]]

^<<v24-10-11,11>>^ Diga isto àqueles que adoram outros deuses: "Esses deuses, que não fizeram os céus nem a terra, desaparecerão da terra e de debaixo dos céus".

[[v24-10-12]]

^<<v24-10-12,12>>^ O SENHOR, porém, fez a terra com seu poder e a estabeleceu com sua sabedoria. Com seu entendimento, estendeu os céus.

[[v24-10-13]]

^<<v24-10-13,13>>^ Quando fala no meio do trovão, as chuvas rugem nos céus. Eleva as nuvens acima da terra, envia relâmpagos com a chuva e ordena que o vento saia de seus depósitos.

[[v24-10-14]]

^<<v24-10-14,14>>^ Todo ser humano é tolo e não tem conhecimento! Os artesãos são envergonhados pelos ídolos que fazem, pois as imagens que esculpiram são uma fraude; não têm fôlego nem poder.

[[v24-10-15]]

^<<v24-10-15,15>>^ Os ídolos são inúteis, são mentiras ridículas; no dia do acerto de contas, serão todos destruídos.

[[v24-10-16]]

^<<v24-10-16,16>>^ Mas o Deus de Israel não é como esses ídolos; ele é o Criador de todas as coisas, incluindo Israel, a nação que lhe pertence. Seu nome é SENHOR dos Exércitos!

[[v24-10-17]]

^<<v24-10-17,17>>^ Reúnam seus pertences e preparem-se para partir; o cerco está para começar.

[[v24-10-18]]

^<<v24-10-18,18>>^ Pois assim diz o SENHOR: "Lançarei fora repentinamente todos vocês que vivem nesta terra. Derramarei sobre vocês grandes aflições; finalmente sentirão minha ira".

[[v24-10-19]]

^<<v24-10-19,19>>^ Minha ferida é grave, e minha dor é grande. Minha doença não tem cura, mas devo suportá-la.

[[v24-10-20]]

^<<v24-10-20,20>>^ Destruíram minha casa, e não resta ninguém que me ajude a reconstruí-la. Levaram meus filhos; nunca mais os verei.

[[v24-10-21]]

^<<v24-10-21,21>>^ Os pastores do meu povo perderam a razão; não buscam mais o SENHOR. Por isso fracassaram, e seus rebanhos estão espalhados.

[[v24-10-22]]

^<<v24-10-22,22>>^ Ouçam o ruído assustador dos grandes exércitos que avançam do norte! As cidades de Judá serão destruídas e se tornarão morada de chacais.

[[v24-10-23]]

^<<v24-10-23,23>>^ Eu sei, ó SENHOR, que nossa vida não nos pertence; não somos capazes de planejar o próprio caminho.

[[v24-10-24]]

^<<v24-10-24,24>>^ Por isso, SENHOR, corrige-me, mas não sejas severo demais; não uses tua ira, pois se o fizesses eu morreria.

[[v24-10-25]]

^<<v24-10-25,25>>^ Derrama tua fúria sobre as nações que não te conhecem, sobre os povos que não invocam teu nome. Pois devoraram teu povo, Israel; sim, o devoraram e o consumiram, transformando a terra num lugar desolado.

'''

xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[&#60; Capítulo Anterior] | <<v24-10-0,Topo>> | xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[Próximo Capítulo &#62;]