include::./index.adoc[]

[[v24-12-0]]
=== Jeremias, 12
// nvt ?, NVT - Nova Versão Transformadora

[[v24-12-1]]

^<<v24-12-1,1>>^ SENHOR, tu sempre me fazes justiça quando apresento uma causa diante de ti. Portanto, desejo te fazer esta queixa: Por que os perversos são tão prósperos? Por que os desonestos vivem em paz?

[[v24-12-2]]

^<<v24-12-2,2>>^ Tu os plantaste, e eles criaram raízes e deram frutos. Teu nome está em seus lábios, mas tu estás longe de seu coração.

[[v24-12-3]]

^<<v24-12-3,3>>^ Quanto a mim, SENHOR, tu me conheces; tu me vês e provas meus pensamentos. Arrasta essa gente como ovelhas para o matadouro; separa-os para a matança!

[[v24-12-4]]

^<<v24-12-4,4>>^ Até quando esta terra ficará de luto? Até o capim nos campos secou. Os animais selvagens e as aves desapareceram por causa da maldade dos que nela habitam. Pois o povo disse: "O SENHOR não vê o que o futuro nos reserva!".

[[v24-12-5]]

^<<v24-12-5,5>>^ "Se correr com homens o deixa cansado, como poderá competir com cavalos? Se tropeça e cai em campo aberto, o que fará nas matas junto ao Jordão?

[[v24-12-6]]

^<<v24-12-6,6>>^ Até seus irmãos, membros de sua família, se voltaram contra você; conspiram e se queixam a seu respeito. Não confie neles, por mais agradáveis que sejam suas palavras.

[[v24-12-7]]

^<<v24-12-7,7>>^ "Abandonei meu povo, a nação que me pertence; entreguei aqueles que eu mais amo a seus inimigos.

[[v24-12-8]]

^<<v24-12-8,8>>^ Meu povo escolhido rugiu contra mim como leão no bosque, por isso os tratei com desprezo.

[[v24-12-9]]

^<<v24-12-9,9>>^ Meu povo escolhido age como ave de rapina, mas ele próprio será cercado por abutres; tragam os animais selvagens para devorar os cadáveres!

[[v24-12-10]]

^<<v24-12-10,10>>^ "Muitos governantes destruíram meu vinhedo; pisotearam minha propriedade e transformaram sua beleza em deserto.

[[v24-12-11]]

^<<v24-12-11,11>>^ Fizeram dela uma terra devastada; ouço seu triste lamento. Toda a terra está desolada, e ninguém se importa.

[[v24-12-12]]

^<<v24-12-12,12>>^ Pode-se ver exércitos destruidores no alto dos montes. A espada do SENHOR devora o povo de uma extremidade à outra da terra; ninguém escapará!

[[v24-12-13]]

^<<v24-12-13,13>>^ Meu povo semeou trigo, mas colhe espinhos. Esforçou-se muito, mas de nada adiantou. Terá uma colheita de vergonha por causa da ira ardente do SENHOR."

[[v24-12-14]]

^<<v24-12-14,14>>^ Assim diz o SENHOR: "Arrancarei de suas terras todas as nações perversas que se apossam da herança que dei ao meu povo, Israel. E arrancarei Judá do meio delas.

[[v24-12-15]]

^<<v24-12-15,15>>^ Depois disso, porém, voltarei e terei compaixão de todos eles. Eu os trarei de volta às suas terras, cada nação à sua herança.

[[v24-12-16]]

^<<v24-12-16,16>>^ E se, verdadeiramente, essas nações aprenderem os caminhos do meu povo e jurarem por meu nome: ‘Tão certo como vive o SENHOR’ — como ensinaram meu povo a jurar pelo nome de Baal —, elas receberão um lugar no meio do meu povo.

[[v24-12-17]]

^<<v24-12-17,17>>^ Mas qualquer nação que não quiser me obedecer será arrancada e destruída. Eu, o SENHOR, falei!".

'''

xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[&#60; Capítulo Anterior] | <<v24-12-0,Topo>> | xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[Próximo Capítulo &#62;]