include::./index.adoc[]

[[v24-46-0]]
=== Jeremias, 46
// nvt ?, NVT - Nova Versão Transformadora

[[v24-46-1]]

^<<v24-46-1,1>>^ O profeta Jeremias recebeu do SENHOR estas mensagens acerca das nações.

[[v24-46-2]]

^<<v24-46-2,2>>^ Esta mensagem acerca do Egito foi anunciada no quarto ano do reinado de Jeoaquim, filho de Josias, rei de Judá, quando o faraó Neco, rei do Egito, e seu exército foram derrotados junto ao rio Eufrates por Nabucodonosor, rei da Babilônia, na batalha de Carquemis.

[[v24-46-3]]

^<<v24-46-3,3>>^ "Preparem seus escudos e avancem para a batalha!

[[v24-46-4]]

^<<v24-46-4,4>>^ Selem os cavalos e montem neles, cavaleiros! Tomem suas posições e coloquem os capacetes. Afiem as lanças e vistam as armaduras.

[[v24-46-5]]

^<<v24-46-5,5>>^ Mas o que vejo? O exército egípcio foge, apavorado. Seus guerreiros mais valentes correm sem olhar para trás. Estão cercados de terror", diz o SENHOR.

[[v24-46-6]]

^<<v24-46-6,6>>^ "Os mais velozes não conseguem fugir, os mais fortes não podem escapar. No norte, junto ao rio Eufrates, tropeçam e caem.

[[v24-46-7]]

^<<v24-46-7,7>>^ "Quem é este que sobe como o Nilo no tempo das cheias e inunda toda a terra?

[[v24-46-8]]

^<<v24-46-8,8>>^ É o exército egípcio que inunda toda a terra. Conta vantagem de que a cobrirá como uma enchente e destruirá as cidades e seus habitantes.

[[v24-46-9]]

^<<v24-46-9,9>>^ Avancem, cavalos e carros de guerra, ataquem, guerreiros valentes do Egito! Venham todos vocês, aliados da Etiópia, da Líbia e da Lídia, hábeis com o escudo e o arco.

[[v24-46-10]]

^<<v24-46-10,10>>^ Porque este é o dia do Soberano SENHOR dos Exércitos, dia de vingar-se de seus inimigos. A espada devorará até se fartar, sim, até se embriagar com seu sangue. O Soberano SENHOR dos Exércitos receberá hoje um sacrifício na terra do norte, junto ao rio Eufrates.

[[v24-46-11]]

^<<v24-46-11,11>>^ "Suba a Gileade para buscar remédio, ó filha virgem do Egito! Mas de nada adiantarão seus muitos medicamentos, pois não há cura para você.

[[v24-46-12]]

^<<v24-46-12,12>>^ As nações ouviram falar de sua humilhação, a terra está cheia de seus gritos de desespero. Seus guerreiros mais valentes tropeçarão uns nos outros e juntos cairão."

[[v24-46-13]]

^<<v24-46-13,13>>^ Então o SENHOR deu ao profeta Jeremias esta mensagem acerca dos planos de Nabucodonosor, rei da Babilônia, para atacar o Egito.

[[v24-46-14]]

^<<v24-46-14,14>>^ "Anunciem esta mensagem no Egito, proclamem-na em Migdol, Mênfis e Tafnes! Preparem-se para a batalha, pois a espada devorará todos ao seu redor.

[[v24-46-15]]

^<<v24-46-15,15>>^ Por que seus guerreiros caíram? Não conseguem ficar em pé, pois o SENHOR os derrubou.

[[v24-46-16]]

^<<v24-46-16,16>>^ Tropeçam e caem uns sobre os outros e dizem entre si: ‘Venham, vamos voltar ao nosso povo, à nossa terra natal; vamos fugir da espada do inimigo!’.

[[v24-46-17]]

^<<v24-46-17,17>>^ Ali eles dirão: ‘O faraó, o rei do Egito, só faz barulho; perdeu sua oportunidade!’.

[[v24-46-18]]

^<<v24-46-18,18>>^ "Tão certo como eu vivo", diz o Rei, cujo nome é SENHOR dos Exércitos, "vem contra o Egito alguém alto como o monte Tabor, como o monte Carmelo junto ao mar.

[[v24-46-19]]

^<<v24-46-19,19>>^ Arrume a bagagem! Prepare-se para ir ao exílio, povo do Egito! A cidade de Mênfis será destruída, e não restará um só habitante.

[[v24-46-20]]

^<<v24-46-20,20>>^ O Egito é formoso como uma bela novilha, mas uma grande mosca do norte está a caminho.

[[v24-46-21]]

^<<v24-46-21,21>>^ Os mercenários do Egito são fortes como bezerros gordos, mas eles também darão meia-volta e fugirão, pois este é um dia de grande calamidade para o Egito, o tempo de seu castigo.

[[v24-46-22]]

^<<v24-46-22,22>>^ O Egito foge como uma serpente que desliza para longe; os exércitos invasores avançam e vêm contra ele com machados, como se fossem lenhadores.

[[v24-46-23]]

^<<v24-46-23,23>>^ Cortarão seu povo como árvores", diz o SENHOR, "pois são mais numerosos que gafanhotos.

[[v24-46-24]]

^<<v24-46-24,24>>^ O Egito será humilhado; será entregue ao povo do norte."

[[v24-46-25]]

^<<v24-46-25,25>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: "Castigarei Amom, o deus de Tebas, e todos os outros deuses do Egito. Castigarei seus governantes, o faraó e todos que nele confiam.

[[v24-46-26]]

^<<v24-46-26,26>>^ Eu os entregarei àqueles que desejam matá-los, a Nabucodonosor, rei da Babilônia, e a seu exército. Depois disso, porém, a terra voltará a ser habitada, como no passado. Eu, o SENHOR, falei!

[[v24-46-27]]

^<<v24-46-27,27>>^ "Mas não tenha medo, meu servo Jacó; não desanime, ó Israel. Pois eu o trarei de volta de terras distantes, e seus descendentes retornarão do exílio. Israel voltará a ter uma vida de paz e sossego, e ninguém o assustará.

[[v24-46-28]]

^<<v24-46-28,28>>^ Não tenha medo, meu servo Jacó, pois estou com você", diz o SENHOR. "Destruirei completamente todas as nações entre as quais o espalhei, mas você não será completamente destruído. Eu o disciplinarei, mas com justiça; não posso permitir que fique impune."

'''

xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[&#60; Capítulo Anterior] | <<v24-46-0,Topo>> | xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[Próximo Capítulo &#62;]