include::./index.adoc[]

[[v24-33-0]]
=== Jeremias, 33
// nvt ?, NVT - Nova Versão Transformadora

[[v24-33-1]]

^<<v24-33-1,1>>^ Enquanto Jeremias estava preso no pátio da guarda, o SENHOR lhe deu outra mensagem:

[[v24-33-2]]

^<<v24-33-2,2>>^ "Assim diz o SENHOR, o SENHOR que fez a terra, que a formou e a estabeleceu; o SENHOR é seu nome:

[[v24-33-3]]

^<<v24-33-3,3>>^ Pergunte-me e eu lhe contarei coisas maravilhosas, segredos que você não sabe, a respeito do que está por vir.

[[v24-33-4]]

^<<v24-33-4,4>>^ Pois assim diz o SENHOR, o Deus de Israel: Vocês derrubaram as casas desta cidade e até o palácio do rei a fim de obter material para fortalecer os muros contra as rampas de cerco e as espadas dos inimigos.

[[v24-33-5]]

^<<v24-33-5,5>>^ Esperam lutar contra os babilônios, mas os homens desta cidade já estão praticamente mortos, pois, em minha ira ardente, decidi destruí-los. Abandonei-os por causa de toda a sua maldade.

[[v24-33-6]]

^<<v24-33-6,6>>^ "Virá o dia, porém, em que curarei as feridas de Jerusalém e lhe darei prosperidade e paz verdadeira.

[[v24-33-7]]

^<<v24-33-7,7>>^ Restaurarei o povo de Judá e de Israel à sua terra e reconstruirei suas cidades.

[[v24-33-8]]

^<<v24-33-8,8>>^ Eu as purificarei de suas maldades contra mim e perdoarei todos os seus pecados de rebeldia.

[[v24-33-9]]

^<<v24-33-9,9>>^ Então esta cidade me trará louvor, glória e honra diante de todas as nações da terra! Os povos do mundo verão todo o bem que faço por meu povo e tremerão de espanto diante da paz e da prosperidade que lhes dou.

[[v24-33-10]]

^<<v24-33-10,10>>^ "Assim diz o SENHOR: Vocês disseram: ‘Esta é uma terra desolada, onde não há mais pessoas nem animais’. Contudo, nas ruas vazias de Jerusalém e das outras cidades de Judá serão ouvidos novamente

[[v24-33-11]]

^<<v24-33-11,11>>^ os sons de alegria e de riso. As vozes felizes de noivos e de noivas voltarão a ser ouvidas, e também os cânticos alegres dos que trazem ofertas de gratidão ao SENHOR. Cantarão: ‘Deem graças ao SENHOR dos Exércitos, porque o SENHOR é bom; seu amor dura para sempre!’. Pois eu restaurarei a situação desta terra ao que era no passado, diz o SENHOR.

[[v24-33-12]]

^<<v24-33-12,12>>^ "Assim diz o SENHOR dos Exércitos: Embora hoje esta terra esteja desolada e não tenha pessoas nem animais, um dia voltará a ter pastos para os quais os pastores levarão seus rebanhos.

[[v24-33-13]]

^<<v24-33-13,13>>^ Os pastores voltarão a contar seus rebanhos nas cidades da região montanhosa, nas colinas de Judá, no Neguebe, na terra de Benjamim, nos arredores de Jerusalém e em todas as cidades de Judá. Eu, o SENHOR, falei!

[[v24-33-14]]

^<<v24-33-14,14>>^ "Virá o dia, diz o SENHOR, em que farei por Israel e por Judá todo o bem que lhes prometi.

[[v24-33-15]]

^<<v24-33-15,15>>^ "Naquele dia e naquele tempo, levantarei um Renovo, um descendente justo da linhagem do rei Davi. Ele fará o que é justo e certo em toda a terra.

[[v24-33-16]]

^<<v24-33-16,16>>^ Nesse dia, Judá será salvo, e Jerusalém viverá em segurança. E este será seu nome: ‘O SENHOR é nossa justiça’.

[[v24-33-17]]

^<<v24-33-17,17>>^ Porque assim diz o SENHOR: Sempre haverá um descendente de Davi no trono de Israel.

[[v24-33-18]]

^<<v24-33-18,18>>^ E sempre haverá sacerdotes levitas para me oferecer holocaustos, ofertas de cereais e sacrifícios".

[[v24-33-19]]

^<<v24-33-19,19>>^ Então Jeremias recebeu esta mensagem do SENHOR:

[[v24-33-20]]

^<<v24-33-20,20>>^ "Assim diz o SENHOR: Se alguém conseguisse anular minha aliança com o dia e com a noite, de modo que um não viesse depois do outro,

[[v24-33-21]]

^<<v24-33-21,21>>^ então se anularia minha aliança com meu servo Davi. Só então deixaria de haver um descendente para reinar em seu trono. O mesmo se aplica à minha aliança com os sacerdotes levitas que me servem.

[[v24-33-22]]

^<<v24-33-22,22>>^ Como não se pode contar as estrelas no céu nem medir a areia na beira do mar, assim também tornarei incontáveis os descendentes de meu servo Davi e os levitas que me servem".

[[v24-33-23]]

^<<v24-33-23,23>>^ O SENHOR deu outra mensagem a Jeremias:

[[v24-33-24]]

^<<v24-33-24,24>>^ "Você observou o que o povo anda dizendo? ‘O SENHOR escolheu Judá e Israel e depois os abandonou!’ Desprezam meu povo e dizem que não deve ser considerada nação.

[[v24-33-25]]

^<<v24-33-25,25>>^ Mas assim diz o SENHOR: Como não anularei minhas leis que governam o dia e a noite, o céu e a terra, assim também não rejeitarei meu povo.

[[v24-33-26]]

^<<v24-33-26,26>>^ Jamais abandonarei os descendentes de Jacó e de meu servo Davi, nem mudarei o plano de que os descendentes de Davi governem os descendentes de Abraão, Isaque e Jacó. Pelo contrário, eu os restaurarei à sua terra e terei compaixão deles".

'''

xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[&#60; Capítulo Anterior] | <<v24-33-0,Topo>> | xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[Próximo Capítulo &#62;]