include::./index.adoc[]

[[v24-2-0]]
=== Jeremias, 2
// nvt ?, NVT - Nova Versão Transformadora

[[v24-2-1]]

^<<v24-2-1,1>>^ O SENHOR me deu outra mensagem:

[[v24-2-2]]

^<<v24-2-2,2>>^ "Vá e proclame esta mensagem para Jerusalém. Assim diz o SENHOR: "Lembro-me de como você desejava me agradar, quando era uma jovem noiva, muito tempo atrás. Você me amava e me seguia até mesmo no deserto.

[[v24-2-3]]

^<<v24-2-3,3>>^ Naqueles dias, Israel era santo para o SENHOR, era como os primeiros frutos de sua colheita. Todos que faziam mal a seu povo eram declarados culpados, e sobre eles vinha calamidade. Eu, o SENHOR, falei!".

[[v24-2-4]]

^<<v24-2-4,4>>^ Ouçam a palavra do SENHOR, descendentes de Jacó e todas as famílias de Israel!

[[v24-2-5]]

^<<v24-2-5,5>>^ Assim diz o SENHOR: "Que defeito seus antepassados encontraram em mim, para que se afastassem tanto? Foram atrás de ídolos inúteis, e eles próprios se tornaram inúteis.

[[v24-2-6]]

^<<v24-2-6,6>>^ Não perguntaram: ‘Onde está o SENHOR, que nos tirou do Egito em segurança e nos conduziu pelo deserto, uma terra árida e cheia de covas, terra de seca e densa escuridão, onde ninguém vive e pela qual ninguém passa?’.

[[v24-2-7]]

^<<v24-2-7,7>>^ "E, quando eu os trouxe para uma terra fértil, para desfrutar sua fartura e as coisas boas que ela produzia, vocês contaminaram minha terra e corromperam a herança que eu lhes tinha dado.

[[v24-2-8]]

^<<v24-2-8,8>>^ Os sacerdotes não perguntaram: ‘Onde está o SENHOR?’. Os que ensinavam minha lei não me deram atenção, os governantes se voltaram contra mim, os profetas falaram em nome de Baal e foram atrás de ídolos inúteis.

[[v24-2-9]]

^<<v24-2-9,9>>^ Portanto, apresentarei minha acusação contra vocês", diz o SENHOR. "Também apresentarei acusações contra seus descendentes.

[[v24-2-10]]

^<<v24-2-10,10>>^ "Vão para a terra de Chipre, no oeste, e vejam; vão para a terra de Quedar, no leste, e prestem atenção. Alguém já ouviu falar de algo parecido?

[[v24-2-11]]

^<<v24-2-11,11>>^ Alguma vez uma nação trocou seus deuses por outros, mesmo que não sejam deuses de verdade? Meu povo, no entanto, trocou seu Deus glorioso por ídolos inúteis!

[[v24-2-12]]

^<<v24-2-12,12>>^ Os céus se espantam diante disso, ficam horrorizados e abalados", diz o SENHOR.

[[v24-2-13]]

^<<v24-2-13,13>>^ "Pois meu povo cometeu duas maldades: Abandonaram a mim, a fonte de água viva, e cavaram para si cisternas rachadas, que não podem reter água."

[[v24-2-14]]

^<<v24-2-14,14>>^ "Por que Israel se tornou escravo? Por que foi levado como despojo?

[[v24-2-15]]

^<<v24-2-15,15>>^ Leões rugiram contra ele, e a terra foi destruída. As cidades estão arruinadas, e ninguém mais vive nelas.

[[v24-2-16]]

^<<v24-2-16,16>>^ Egípcios vindos de Mênfis e de Tafnes destruíram o orgulho de Israel.

[[v24-2-17]]

^<<v24-2-17,17>>^ E você mesmo é responsável por isso, pois abandonou o SENHOR, seu Deus, embora ele o guiasse pelo caminho!

[[v24-2-18]]

^<<v24-2-18,18>>^ "Que lucro você teve com seus tratados com o Egito e seus acordos com a Assíria? De que lhe adiantam as águas do Nilo ou as águas do Eufrates?

[[v24-2-19]]

^<<v24-2-19,19>>^ Sua maldade trará seu próprio castigo; será envergonhado por ter se afastado de mim e verá como é mau e amargo abandonar o SENHOR, seu Deus, e não o temer. Eu, o Soberano SENHOR dos Exércitos, falei!

[[v24-2-20]]

^<<v24-2-20,20>>^ "Há muito tempo, quebrei o jugo que o oprimia e despedacei as correntes de sua escravidão. Ainda assim, você disse: ‘Jamais o servirei’. No alto dos montes e debaixo de toda árvore verdejante, você se prostituiu ao se curvar para ídolos.

[[v24-2-21]]

^<<v24-2-21,21>>^ Contudo, eu o plantei, como videira de origem pura, da melhor qualidade; como você se transformou em videira silvestre e degenerada?

[[v24-2-22]]

^<<v24-2-22,22>>^ Por mais sabão ou soda que use, não consegue se limpar; ainda vejo a mancha de sua culpa. Eu, o SENHOR Soberano, falei!"

[[v24-2-23]]

^<<v24-2-23,23>>^ "Você diz: ‘Não tenho mancha nenhuma! Não adorei as imagens de Baal!’. Mas como pode dizer isso? Vá a qualquer vale da terra e veja como agiu! Reconheça o que fez! Você é como a fêmea do camelo, inquieta e desesperada para encontrar um macho.

[[v24-2-24]]

^<<v24-2-24,24>>^ É como a jumenta selvagem, que fareja o vento na época do acasalamento. Quem é capaz de conter seu desejo? Os que a desejam não precisam procurá-la, pois você vai correndo até eles!

[[v24-2-25]]

^<<v24-2-25,25>>^ Quando parará de correr? Quando deixará de ofegar por outros deuses? Mas você diz: ‘Não adianta falar comigo; estou apaixonada pelos deuses estrangeiros e irei atrás deles’.

[[v24-2-26]]

^<<v24-2-26,26>>^ "A nação de Israel é como ladrão que só fica envergonhado quando é pego em flagrante. O povo, seus reis, oficiais, sacerdotes e profetas são todos iguais.

[[v24-2-27]]

^<<v24-2-27,27>>^ Dizem a um pedaço de madeira: ‘Você é meu pai’, e a um bloco de pedra: ‘Você é minha mãe’. Dão as costas para mim, mas, em tempos de aflição, clamam: ‘Vem nos salvar!’.

[[v24-2-28]]

^<<v24-2-28,28>>^ Por que não clamam aos deuses que vocês mesmos fizeram? Que eles os salvem quando vier a aflição! Pois seus deuses são tão numerosos quanto as cidades de Judá.

[[v24-2-29]]

^<<v24-2-29,29>>^ Por que me acusam de fazer o mal? Foram vocês que se rebelaram", diz o SENHOR.

[[v24-2-30]]

^<<v24-2-30,30>>^ "Eu castiguei seus filhos, mas eles não aceitaram minha disciplina. Vocês mesmos mataram seus profetas, como um leão mata sua presa.

[[v24-2-31]]

^<<v24-2-31,31>>^ "Ó meu povo, ouça as palavras do SENHOR! Acaso tenho sido como um deserto para Israel? Tenho sido como uma terra de profunda escuridão? Por que, então, meu povo diz: ‘Finalmente nos livramos de Deus! Não precisamos mais dele!’?

[[v24-2-32]]

^<<v24-2-32,32>>^ Acaso uma jovem se esquece de suas joias ou a noiva esconde seu vestido? Contudo, por anos a fio, meu povo se esqueceu de mim.

[[v24-2-33]]

^<<v24-2-33,33>>^ "Você trama a melhor forma de conquistar seus amantes; até uma prostituta poderia aprender com você!

[[v24-2-34]]

^<<v24-2-34,34>>^ Suas roupas estão manchadas com o sangue dos inocentes e dos pobres, embora você não os tenha pego arrombando sua casa.

[[v24-2-35]]

^<<v24-2-35,35>>^ Ainda assim, você diz: ‘Não fiz nada de errado; certamente Deus não está irado comigo’. Agora, porém, eu a julgarei severamente, pois você afirma que não pecou.

[[v24-2-36]]

^<<v24-2-36,36>>^ Primeiro aqui, depois ali, vai de um aliado a outro pedindo ajuda. Mas seus novos amigos no Egito a decepcionarão, como fez a Assíria.

[[v24-2-37]]

^<<v24-2-37,37>>^ Em desespero, será levada para o exílio com as mãos sobre a cabeça, pois o SENHOR rejeitou as nações em que você confia; elas em nada a ajudarão."

'''

xref:024-jeremias/024-jeremias-001.adoc#v24-1-0[&#60; Capítulo Anterior] | <<v24-2-0,Topo>> | xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[Próximo Capítulo &#62;]