include::./index.adoc[]

[[v24-44-0]]
=== Jeremias, 44
// nvt ?, NVT - Nova Versão Transformadora

[[v24-44-1]]

^<<v24-44-1,1>>^ Jeremias recebeu esta mensagem acerca dos judeus que viviam no norte do Egito, nas cidades de Migdol, Tafnes e Mênfis, e também no sul do Egito:

[[v24-44-2]]

^<<v24-44-2,2>>^ "Assim diz o SENHOR dos Exércitos, o Deus de Israel: Vocês viram a calamidade que eu trouxe sobre Jerusalém e sobre todas as cidades de Judá. Hoje elas estão desertas e em ruínas,

[[v24-44-3]]

^<<v24-44-3,3>>^ porque provocaram minha ira com sua perversidade. Queimaram incenso e adoraram outros deuses que nem eles, nem vocês, nem seus antepassados jamais conheceram.

[[v24-44-4]]

^<<v24-44-4,4>>^ "Repetidamente, enviei meu servos, os profetas, para lhes dizer: ‘Não façam essas coisas terríveis que eu tanto detesto!’.

[[v24-44-5]]

^<<v24-44-5,5>>^ Mas eles não deram ouvidos nem abandonaram sua perversidade, e continuaram a queimar incenso para esses deuses.

[[v24-44-6]]

^<<v24-44-6,6>>^ Por isso minha fúria transbordou e caiu como fogo sobre as cidades de Judá e as ruas de Jerusalém, que até hoje são ruínas desoladas.

[[v24-44-7]]

^<<v24-44-7,7>>^ "Agora, o SENHOR dos Exércitos, o Deus de Israel, lhes pergunta: Por que destroem a si mesmos? Nenhum de vocês sobreviverá: nenhum homem, mulher, criança ou recém-nascido que veio de Judá.

[[v24-44-8]]

^<<v24-44-8,8>>^ Por que provocar minha ira queimando incenso para os ídolos que vocês fizeram aqui no Egito? Destruirão a si mesmos e se tornarão objeto de maldição e zombaria para todas as nações.

[[v24-44-9]]

^<<v24-44-9,9>>^ Acaso se esqueceram dos pecados de seus antepassados, dos pecados dos reis e das rainhas de Judá, e dos pecados que vocês e suas esposas cometeram em Judá e em Jerusalém?

[[v24-44-10]]

^<<v24-44-10,10>>^ Até hoje, não mostraram remorso nem temor. Ninguém escolheu obedecer à minha lei e aos decretos que dei a vocês e a seus antepassados.

[[v24-44-11]]

^<<v24-44-11,11>>^ "Portanto, assim diz o SENHOR dos Exércitos, o Deus de Israel: Estou decidido a destruir cada um de vocês!

[[v24-44-12]]

^<<v24-44-12,12>>^ Tomarei o remanescente de Judá, aqueles que teimaram em vir para o Egito e morar aqui, e os consumirei. Cairão no Egito, mortos por guerra e fome. Todos morrerão, desde o mais humilde até o mais importante. Serão objeto de condenação, horror, maldição e zombaria.

[[v24-44-13]]

^<<v24-44-13,13>>^ Eu os castigarei no Egito como os castiguei em Jerusalém, com guerra, fome e doença.

[[v24-44-14]]

^<<v24-44-14,14>>^ Desse remanescente que fugiu para o Egito, na esperança de um dia voltar para Judá, ninguém sobreviverá. Embora anseiem voltar para sua terra, apenas uns poucos retornarão".

[[v24-44-15]]

^<<v24-44-15,15>>^ Então todas as mulheres que estavam presentes e todos os homens que sabiam que suas esposas haviam queimado incenso para ídolos, uma grande multidão de todos os judeus que viviam no norte e no sul do Egito, responderam a Jeremias:

[[v24-44-16]]

^<<v24-44-16,16>>^ "Não ouviremos as mensagens que você transmite em nome do SENHOR!

[[v24-44-17]]

^<<v24-44-17,17>>^ Faremos o que bem entendermos. Queimaremos incenso e apresentaremos ofertas derramadas para a Rainha do Céu, como nós, nossos antepassados e nossos reis e oficiais sempre fizemos nas cidades de Judá e nas ruas de Jerusalém. Naqueles dias, havia alimento com fartura, éramos prósperos e não tínhamos problemas!

[[v24-44-18]]

^<<v24-44-18,18>>^ Mas desde que paramos de queimar incenso para a Rainha do Céu e deixamos de adorá-la com ofertas derramadas, temos enfrentado grandes aflições e morrido por guerra e fome".

[[v24-44-19]]

^<<v24-44-19,19>>^ "Além disso", acrescentaram as mulheres, "você imagina que queimávamos incenso, apresentávamos ofertas derramadas à Rainha do Céu e fazíamos bolos que retratavam sua imagem sem o conhecimento e a ajuda de nossos maridos?"

[[v24-44-20]]

^<<v24-44-20,20>>^ Então Jeremias disse a todos, tanto homens como mulheres, que lhe tinham dado essa resposta:

[[v24-44-21]]

^<<v24-44-21,21>>^ "Vocês pensam que o SENHOR não sabia que vocês, seus antepassados, seus reis e oficiais e todo o povo queimavam incenso a ídolos nas cidades de Judá e nas ruas de Jerusalém?

[[v24-44-22]]

^<<v24-44-22,22>>^ O SENHOR fez de sua terra objeto de maldição, ruína desolada e sem habitantes, como está hoje, porque não suportava mais suas práticas detestáveis.

[[v24-44-23]]

^<<v24-44-23,23>>^ Todas essas coisas terríveis aconteceram a vocês porque queimaram incenso a ídolos e pecaram contra o SENHOR. Não obedeceram à sua voz nem seguiram sua lei, seus decretos e seus preceitos!".

[[v24-44-24]]

^<<v24-44-24,24>>^ Então Jeremias disse a todos, inclusive às mulheres: "Ouçam esta mensagem do SENHOR, todos vocês judeus que agora vivem no Egito.

[[v24-44-25]]

^<<v24-44-25,25>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: ‘Vocês e suas esposas disseram: ‘Cumpriremos nossa promessa de queimar incenso e apresentar ofertas derramadas à Rainha do Céu’, e provaram com suas ações que estavam falando sério. Portanto, cumpram as promessas e votos que fizeram para ela’.

[[v24-44-26]]

^<<v24-44-26,26>>^ "Ouçam, porém, esta mensagem do SENHOR, todos vocês judeus que agora vivem no Egito: ‘Jurei por meu grande nome’, diz o SENHOR, ‘que nenhum judeu na terra do Egito pronunciará meu nome. Nenhum de vocês invocará meu nome nem o usará para jurar: ‘Tão certo como vive o SENHOR Soberano’.

[[v24-44-27]]

^<<v24-44-27,27>>^ Pois eu os vigiarei para trazer sobre vocês calamidade, e não bem. Os judeus que hoje vivem no Egito sofrerão guerra e fome até que estejam todos mortos.

[[v24-44-28]]

^<<v24-44-28,28>>^ Apenas uns poucos escaparão da morte e voltarão do Egito para Judá. Então todos que vieram para o Egito saberão quais palavras são verdadeiras: as minhas ou as deles!

[[v24-44-29]]

^<<v24-44-29,29>>^ "‘E esta é a prova que lhes dou’, diz o SENHOR, ‘de que todas as minhas palavras se cumprirão e de que eu os castigarei aqui.’

[[v24-44-30]]

^<<v24-44-30,30>>^ Assim diz o SENHOR: ‘Entregarei o faraó Hofra, rei do Egito, nas mãos de seus inimigos que desejam matá-lo, assim como entreguei Zedequias, rei de Judá, a Nabucodonosor, rei da Babilônia’".

'''

xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[&#60; Capítulo Anterior] | <<v24-44-0,Topo>> | xref:024-jeremias/024-jeremias-045.adoc#v24-45-0[Próximo Capítulo &#62;]