include::./index.adoc[]

[[v24-18-0]]
=== Jeremias, 18
// nvt ?, NVT - Nova Versão Transformadora

[[v24-18-1]]

^<<v24-18-1,1>>^ O SENHOR deu outra mensagem a Jeremias:

[[v24-18-2]]

^<<v24-18-2,2>>^ "Desça até a casa do oleiro, e eu lhe falarei ali".

[[v24-18-3]]

^<<v24-18-3,3>>^ Fui à casa do oleiro e o encontrei trabalhando na roda.

[[v24-18-4]]

^<<v24-18-4,4>>^ Mas o vaso de barro que ele estava fazendo não saiu como desejava, por isso ele amassou o barro e começou novamente.

[[v24-18-5]]

^<<v24-18-5,5>>^ Então o SENHOR me deu esta mensagem:

[[v24-18-6]]

^<<v24-18-6,6>>^ "Ó Israel, acaso não posso fazer com vocês o mesmo que o oleiro fez com o barro? Como o barro está nas mãos do oleiro, vocês estão em minhas mãos.

[[v24-18-7]]

^<<v24-18-7,7>>^ Se eu anunciar que uma nação ou reino será arrancado, derrubado e destruído,

[[v24-18-8]]

^<<v24-18-8,8>>^ mas essa nação abandonar seus maus caminhos, não a destruirei como havia planejado.

[[v24-18-9]]

^<<v24-18-9,9>>^ E, se eu anunciar que plantarei e edificarei uma nação ou reino,

[[v24-18-10]]

^<<v24-18-10,10>>^ mas essa nação praticar o mal e não quiser me obedecer, não a abençoarei como havia declarado.

[[v24-18-11]]

^<<v24-18-11,11>>^ "Portanto, Jeremias, vá e proclame a todo o povo de Judá e aos habitantes de Jerusalém: ‘Assim diz o SENHOR: Planejo calamidade para vocês, e não o bem. Por isso, cada um abandone seus maus caminhos e faça o que é certo’".

[[v24-18-12]]

^<<v24-18-12,12>>^ "Não perca seu tempo", o povo respondeu. "Continuaremos a viver como quisermos e a seguir os desejos teimosos de nosso coração perverso."

[[v24-18-13]]

^<<v24-18-13,13>>^ Portanto, assim diz o SENHOR: "Quem ouviu coisa igual a essa, mesmo entre as outras nações? Israel, minha filha virgem, fez algo terrível!

[[v24-18-14]]

^<<v24-18-14,14>>^ Pode a neve desaparecer do alto dos montes do Líbano? Podem secar-se os riachos que correm desses montes distantes?

[[v24-18-15]]

^<<v24-18-15,15>>^ Meu povo, contudo, me abandonou e queima incenso para ídolos inúteis. Tropeçaram e saíram dos caminhos antigos e andam por trilhas lamacentas.

[[v24-18-16]]

^<<v24-18-16,16>>^ Portanto, sua terra ficará desolada; será um monumento à sua tolice. Todos que passarem por lá ficarão pasmos e balançarão a cabeça em espanto.

[[v24-18-17]]

^<<v24-18-17,17>>^ Espalharei meu povo diante de seus inimigos, como o vento leste espalha o pó. Darei as costas para eles e não os ajudarei em sua calamidade".

[[v24-18-18]]

^<<v24-18-18,18>>^ Então o povo disse: "Venham, vamos planejar um jeito de nos livrarmos de Jeremias. Temos vários sacerdotes, e também homens sábios e profetas. Não precisamos que ele nos ensine a lei, e não precisamos de seus conselhos e profecias. Vamos espalhar boatos a seu respeito e ignorar o que ele diz".

[[v24-18-19]]

^<<v24-18-19,19>>^ SENHOR, olha para mim! Ouve o que dizem meus inimigos!

[[v24-18-20]]

^<<v24-18-20,20>>^ Acaso se paga o bem com o mal? Cavaram um buraco para me matar, mesmo eu tendo intercedido por eles e tentado protegê-los de tua ira.

[[v24-18-21]]

^<<v24-18-21,21>>^ Portanto, que os filhos deles morram de fome! Que morram pela espada! Que suas esposas se tornem viúvas e fiquem sem filhos! Que os mais velhos sejam mortos por uma praga, e os jovens, na batalha!

[[v24-18-22]]

^<<v24-18-22,22>>^ Que se ouçam gritos vindos de suas casas quando guerreiros atacarem repentinamente, pois cavaram um buraco para mim e esconderam armadilhas ao longo do meu caminho.

[[v24-18-23]]

^<<v24-18-23,23>>^ SENHOR, tu conheces os planos que fizeram para me matar; não os perdoes por seus crimes nem apagues seus pecados. Que eles morram diante de ti; trata-os de acordo com a tua ira.

'''

xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[&#60; Capítulo Anterior] | <<v24-18-0,Topo>> | xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[Próximo Capítulo &#62;]