include::./index.adoc[]

[[v24-30-0]]
=== Jeremias, 30
// nvt ?, NVT - Nova Versão Transformadora

[[v24-30-1]]

^<<v24-30-1,1>>^ O SENHOR deu outra mensagem a Jeremias:

[[v24-30-2]]

^<<v24-30-2,2>>^ "Assim diz o SENHOR, o Deus de Israel: Jeremias, registre por escrito tudo que eu lhe disse.

[[v24-30-3]]

^<<v24-30-3,3>>^ Porque está chegando o dia em que restaurarei meu povo de Israel e de Judá. Eu os trarei para casa, para esta terra que dei a seus antepassados, e eles voltarão a possuí-la. Eu, o SENHOR, falei!".

[[v24-30-4]]

^<<v24-30-4,4>>^ Esta é a mensagem do SENHOR acerca de Israel e de Judá.

[[v24-30-5]]

^<<v24-30-5,5>>^ Assim diz o SENHOR: "Ouço gritos de medo; há terror, e não paz.

[[v24-30-6]]

^<<v24-30-6,6>>^ Parem e pensem: Acaso homens dão à luz? Então por que estão aí, com o rosto pálido e as mãos na barriga, como a mulher em trabalho de parto?

[[v24-30-7]]

^<<v24-30-7,7>>^ Em toda a história, nunca houve uma ocasião de tanto terror; será um tempo de angústia para Israel. No final, porém, ele será resgatado!

[[v24-30-8]]

^<<v24-30-8,8>>^ Pois naquele dia", diz o SENHOR dos Exércitos, "quebrarei o jugo que está sobre seu pescoço e arrebentarei suas correntes; não serão mais escravizados por estrangeiros.

[[v24-30-9]]

^<<v24-30-9,9>>^ Pois meu povo servirá ao SENHOR, seu Deus, e ao descendente de Davi, o rei que estabelecerei para eles.

[[v24-30-10]]

^<<v24-30-10,10>>^ "Portanto, não tenha medo, meu servo Jacó; não desanime, ó Israel", diz o SENHOR. "Pois o trarei de volta de terras distantes, e seus descendentes retornarão do exílio. Israel voltará a ter uma vida de paz e sossego, e ninguém o assustará.

[[v24-30-11]]

^<<v24-30-11,11>>^ Porque estou com você e o resgatarei", diz o SENHOR. "Destruirei completamente todas as nações entre as quais o espalhei, mas você não será completamente destruído. Eu o disciplinarei, mas com justiça; não posso permitir que fique impune."

[[v24-30-12]]

^<<v24-30-12,12>>^ Assim diz o SENHOR: "Seu ferimento é incurável; é uma ferida grave.

[[v24-30-13]]

^<<v24-30-13,13>>^ Não há ninguém para socorrê-la, não há remédio que cure sua ferida.

[[v24-30-14]]

^<<v24-30-14,14>>^ Todos os seus amantes a abandonaram; não se importam com você. Eu a feri cruelmente, como se fosse meu inimigo. Pois seus pecados são muitos, e sua culpa é grande.

[[v24-30-15]]

^<<v24-30-15,15>>^ Por que se queixa de seu castigo, dessa ferida que não tem cura? Tive de castigá-la, pois seus pecados são muitos, e sua culpa é grande.

[[v24-30-16]]

^<<v24-30-16,16>>^ "Mas todos que a devorarem serão devorados, todos os seus inimigos serão enviados para o exílio. Todos que a saquearem serão saqueados, todos que a despojarem serão despojados.

[[v24-30-17]]

^<<v24-30-17,17>>^ Restaurarei sua saúde e curarei suas feridas", diz o SENHOR. "Pois a chamam de rejeitada, ‘Sião, cidade com que ninguém se importa’."

[[v24-30-18]]

^<<v24-30-18,18>>^ Assim diz o SENHOR: "Quando eu trouxer Israel de volta do exílio e restaurar sua situação, Jerusalém será reconstruída sobre suas ruínas, e o palácio voltará a ser habitado.

[[v24-30-19]]

^<<v24-30-19,19>>^ Haverá alegria e cânticos de gratidão, e eu farei meu povo se multiplicar, e não diminuir; eu os honrarei, e não os humilharei.

[[v24-30-20]]

^<<v24-30-20,20>>^ Seus filhos prosperarão, como no passado; eu os estabelecerei como nação diante de mim e castigarei quem lhes fizer mal.

[[v24-30-21]]

^<<v24-30-21,21>>^ Voltarão a ter o próprio governante, e ele virá do meio deles. Eu o aproximarei de mim", diz o SENHOR, "pois quem ousaria se aproximar por conta própria?

[[v24-30-22]]

^<<v24-30-22,22>>^ Vocês serão o meu povo, e eu serei o seu Deus."

[[v24-30-23]]

^<<v24-30-23,23>>^ Vejam, a ira do SENHOR irrompe como uma tempestade, um vendaval sobre a cabeça dos perversos!

[[v24-30-24]]

^<<v24-30-24,24>>^ A ira ardente do SENHOR não passará até que ele cumpra tudo que planejou. Em dias futuros, vocês entenderão tudo isso.

'''

xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[&#60; Capítulo Anterior] | <<v24-30-0,Topo>> | xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[Próximo Capítulo &#62;]