include::./index.adoc[]

[[v24-15-0]]
=== Jeremias, 15
// nvt ?, NVT - Nova Versão Transformadora

[[v24-15-1]]

^<<v24-15-1,1>>^ Então o SENHOR me disse: "Mesmo que Moisés e Samuel intercedessem diante de mim em favor deste povo, eu não ajudaria. Fora com eles! Expulse-os de minha presença!

[[v24-15-2]]

^<<v24-15-2,2>>^ E se lhe perguntarem: ‘Para onde iremos?’, diga-lhes: ‘Assim diz o SENHOR: "‘Os destinados à morte, para a morte; os destinados à guerra, para a guerra; os destinados à fome, para a fome; os destinados ao cativeiro, para o cativeiro’.

[[v24-15-3]]

^<<v24-15-3,3>>^ "Enviarei contra eles quatro tipos de destruidores", diz o SENHOR. "Enviarei espada para matá-los, cães para arrastá-los, abutres para devorá-los e animais selvagens para acabar com o que tiver sobrado.

[[v24-15-4]]

^<<v24-15-4,4>>^ Por causa das maldades que Manassés, filho de Ezequias, rei de Judá, fez em Jerusalém, farei de meu povo objeto de horror para todos os reinos da terra.

[[v24-15-5]]

^<<v24-15-5,5>>^ "Quem terá compaixão de você, Jerusalém? Quem chorará por você? Quem se dará o trabalho de perguntar se está bem?

[[v24-15-6]]

^<<v24-15-6,6>>^ Você me abandonou e me deu as costas", diz o SENHOR. "Portanto, levantarei a mão para destruí-la; estou cansado de mostrar compaixão.

[[v24-15-7]]

^<<v24-15-7,7>>^ Às portas das cidades, eu os espalharei ao vento, como palha separada do cereal, e levarei seus filhos queridos. Destruirei meu próprio povo, pois não querem abandonar seus maus caminhos.

[[v24-15-8]]

^<<v24-15-8,8>>^ Haverá mais viúvas que grãos de areia do mar. Ao meio-dia, trarei um destruidor contra as mães dos jovens. Farei cair sobre elas angústia e terror repentinos.

[[v24-15-9]]

^<<v24-15-9,9>>^ A mãe de sete filhos desmaia e respira com dificuldade; para ela, o sol se pôs enquanto ainda era dia. Agora está sem filhos, envergonhada e humilhada. Entregarei os que restarem para serem mortos pelo inimigo. Eu, o SENHOR falei!"

[[v24-15-10]]

^<<v24-15-10,10>>^ Então eu disse: "Como estou aflito, minha mãe! Quem dera eu tivesse morrido ao nascer! Sou odiado em todo lugar. Não sou um credor que ameaça cobrar a dívida, nem um devedor que se recusa a pagá-la; ainda assim, todos me amaldiçoam".

[[v24-15-11]]

^<<v24-15-11,11>>^ O SENHOR respondeu: "Eu cuidarei de você; em tempos de calamidade e aflição, seus inimigos lhe pedirão que interceda por eles.

[[v24-15-12]]

^<<v24-15-12,12>>^ Alguém é capaz de quebrar uma barra de ferro do norte ou uma barra de bronze?

[[v24-15-13]]

^<<v24-15-13,13>>^ Entregarei de graça sua riqueza e seus tesouros como despojo a seus inimigos, pois o pecado corre solto pela terra.

[[v24-15-14]]

^<<v24-15-14,14>>^ Farei que seus inimigos os levem como prisioneiros para uma terra estrangeira. Pois minha ira se acendeu como fogo e arderá contra vocês".

[[v24-15-15]]

^<<v24-15-15,15>>^ Então eu disse: " SENHOR, tu sabes o que me tem acontecido; intervém, ajuda-me e castiga meus perseguidores! Dá-me tempo, não permitas que eu morra ainda jovem; é por teu nome que tenho sofrido humilhações.

[[v24-15-16]]

^<<v24-15-16,16>>^ Quando descobri tuas palavras, devorei-as; são minha alegria e dão prazer a meu coração, pois pertenço a ti, ó SENHOR, Deus dos Exércitos.

[[v24-15-17]]

^<<v24-15-17,17>>^ Nunca participei dos banquetes alegres do povo; sentei-me sozinho, porque tua mão pesava sobre mim, e enchi-me de indignação com os pecados deles.

[[v24-15-18]]

^<<v24-15-18,18>>^ Por que, então, continuo a sofrer? Por que minha ferida não tem cura? Teu socorro parece incerto como um riacho inconstante; é como uma fonte que secou".

[[v24-15-19]]

^<<v24-15-19,19>>^ Assim diz o SENHOR: "Se voltar para mim, eu o restaurarei, para que possa continuar a me servir. Se disser palavras de valor, em vez de palavras inúteis, será meu porta-voz. Você os influenciará, mas não deixará que o influenciem.

[[v24-15-20]]

^<<v24-15-20,20>>^ Lutarão contra você como um exército, mas o tornarei invencível como uma muralha de bronze. Não o vencerão, pois estou com você para protegê-lo e livrá-lo. Eu, o SENHOR, falei!

[[v24-15-21]]

^<<v24-15-21,21>>^ Certamente o livrarei desses homens perversos e o resgatarei de suas mãos cruéis".

'''

xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[&#60; Capítulo Anterior] | <<v24-15-0,Topo>> | xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[Próximo Capítulo &#62;]