include::./index.adoc[]

[[v24-45-0]]
=== Jeremias, 45
// nvt ?, NVT - Nova Versão Transformadora

[[v24-45-1]]

^<<v24-45-1,1>>^ O profeta Jeremias transmitiu esta mensagem a Baruque, filho de Nerias, no quarto ano do reinado de Jeoaquim, filho de Josias, depois que Baruque escreveu tudo que Jeremias havia ditado:

[[v24-45-2]]

^<<v24-45-2,2>>^ "Assim diz o SENHOR, o Deus de Israel, a você, Baruque:

[[v24-45-3]]

^<<v24-45-3,3>>^ Você disse: ‘Estou cercado de aflições! Será que já não sofri o suficiente? E agora o SENHOR acrescentou ainda mais dor! Estou exausto de tanto gemer e não encontro descanso’.

[[v24-45-4]]

^<<v24-45-4,4>>^ "Baruque, assim diz o SENHOR: ‘Destruirei esta nação que edifiquei; arrancarei o que plantei.

[[v24-45-5]]

^<<v24-45-5,5>>^ Você procura grandes coisas para si mesmo? Não faça isso! Trarei calamidade sobre todo este povo; a você, porém, darei sua vida como recompensa aonde quer que vá. Eu, o SENHOR, falei!’".

'''

xref:024-jeremias/024-jeremias-044.adoc#v24-44-0[&#60; Capítulo Anterior] | <<v24-45-0,Topo>> | xref:024-jeremias/024-jeremias-046.adoc#v24-46-0[Próximo Capítulo &#62;]