include::./index.adoc[]

[[v24-35-0]]
=== Jeremias, 35
// nvt ?, NVT - Nova Versão Transformadora

[[v24-35-1]]

^<<v24-35-1,1>>^ O SENHOR deu esta mensagem a Jeremias quando Jeoaquim, filho de Josias, era rei de Judá:

[[v24-35-2]]

^<<v24-35-2,2>>^ "Vá ao local onde moram os recabitas e convide-os para vir ao templo do SENHOR. Leve-os para uma das salas internas e ofereça-lhes vinho".

[[v24-35-3]]

^<<v24-35-3,3>>^ Então fui buscar Jazanias, filho de Jeremias e neto de Habazinias, e todos os seus irmãos e filhos, que representavam todas as famílias dos recabitas.

[[v24-35-4]]

^<<v24-35-4,4>>^ Levei-os ao templo do SENHOR e fomos à sala dos filhos de Hanã, filho de Jigdalias, homem de Deus. Ficava ao lado da sala usada pelos oficiais do templo, logo acima da sala de Maaseias, filho de Salum, porteiro do templo.

[[v24-35-5]]

^<<v24-35-5,5>>^ Coloquei diante deles taças e jarras cheias de vinho e os convidei a beber,

[[v24-35-6]]

^<<v24-35-6,6>>^ mas eles recusaram, dizendo: "Não bebemos vinho, pois nosso antepassado, Jonadabe, filho de Recabe, nos deu esta ordem: ‘Nunca bebam vinho, nem vocês nem seus descendentes.

[[v24-35-7]]

^<<v24-35-7,7>>^ Não construam casas, não plantem lavouras nem possuam vinhedos; vivam sempre em tendas. Com isso, terão vida longa e feliz nesta terra’.

[[v24-35-8]]

^<<v24-35-8,8>>^ Assim, temos obedecido a tudo que ele nos ordenou. Nunca bebemos vinho, nem nós, nem nossas esposas, nem nossos filhos e filhas.

[[v24-35-9]]

^<<v24-35-9,9>>^ Não construímos casas, nem possuímos vinhedos e campos, nem plantamos lavouras.

[[v24-35-10]]

^<<v24-35-10,10>>^ Temos vivido em tendas e obedecido fielmente a todas as ordens de nosso antepassado Jonadabe.

[[v24-35-11]]

^<<v24-35-11,11>>^ Mas, quando Nabucodonosor, rei da Babilônia, atacou esta terra, tivemos medo dos exércitos babilônios e sírios e resolvemos nos mudar para Jerusalém. Por isso estamos aqui".

[[v24-35-12]]

^<<v24-35-12,12>>^ Então o SENHOR deu esta mensagem a Jeremias:

[[v24-35-13]]

^<<v24-35-13,13>>^ "Assim diz o SENHOR dos Exércitos, o Deus de Israel: Vá e diga aos habitantes de Judá e de Jerusalém: ‘Venham e aprendam uma lição sobre como obedecer às minhas palavras, diz o SENHOR.

[[v24-35-14]]

^<<v24-35-14,14>>^ Os recabitas não bebem vinho até hoje em obediência à ordem de seu antepassado Jonadabe, filho de Recabe. Mas eu tenho falado a vocês repetidamente e se recusam a obedecer.

[[v24-35-15]]

^<<v24-35-15,15>>^ Tenho enviado meus profetas vez após vez para lhes dizer: ‘Abandonem seus maus caminhos e façam o que é certo. Deixem de adorar outros deuses. Assim, viverão em paz nesta terra que dei a vocês e a seus antepassados’. Mas vocês não quiseram ouvir nem obedecer.

[[v24-35-16]]

^<<v24-35-16,16>>^ Os descendentes de Jonadabe, filho de Recabe, têm obedecido fielmente a seu antepassado, mas este povo se recusa a me ouvir’.

[[v24-35-17]]

^<<v24-35-17,17>>^ "Portanto, assim diz o SENHOR Deus dos Exércitos, o Deus de Israel: ‘Porque não querem me ouvir nem responder quando os chamo, enviarei sobre Judá e sobre Jerusalém todas as calamidades que prometi’".

[[v24-35-18]]

^<<v24-35-18,18>>^ Então Jeremias se voltou para os recabitas e disse: "Assim diz o SENHOR dos Exércitos, o Deus de Israel: ‘Vocês obedeceram a todas as ordens de seu antepassado Jonadabe e seguiram todas as suas instruções’.

[[v24-35-19]]

^<<v24-35-19,19>>^ Por isso, assim diz o SENHOR dos Exércitos, o Deus de Israel: ‘Sempre haverá descendentes de Jonadabe, filho de Recabe, para me servir’".

'''

xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[&#60; Capítulo Anterior] | <<v24-35-0,Topo>> | xref:024-jeremias/024-jeremias-036.adoc#v24-36-0[Próximo Capítulo &#62;]