include::./index.adoc[]

[[v24-27-0]]
=== Jeremias, 27
// nvt ?, NVT - Nova Versão Transformadora

[[v24-27-1]]

^<<v24-27-1,1>>^ Jeremias recebeu esta mensagem do SENHOR no início do reinado de Zedequias, filho de Josias, rei de Judá.

[[v24-27-2]]

^<<v24-27-2,2>>^ Assim me disse o SENHOR: "Faça um jugo, ponha-o sobre o pescoço e prenda-o com cordas de couro.

[[v24-27-3]]

^<<v24-27-3,3>>^ Depois, envie mensagens aos reis de Edom, Moabe, Amom, Tiro e Sidom por meio dos embaixadores que vieram ver o rei Zedequias em Jerusalém.

[[v24-27-4]]

^<<v24-27-4,4>>^ Diga-lhes que transmitam esta mensagem a seus senhores: ‘Assim diz o SENHOR dos Exércitos, o Deus de Israel:

[[v24-27-5]]

^<<v24-27-5,5>>^ Com minha grande força e meu braço poderoso, fiz a terra, todas as pessoas e todos os animais. Isso tudo é meu, e posso entregá-lo a quem eu quiser.

[[v24-27-6]]

^<<v24-27-6,6>>^ Agora, entregarei suas nações a meu servo, Nabucodonosor, rei da Babilônia. Coloquei tudo debaixo de seu controle, até os animais selvagens.

[[v24-27-7]]

^<<v24-27-7,7>>^ Todas as nações servirão a ele, seu filho e seu neto, até terminar o tempo deles. Então, muitas nações e grandes reis conquistarão e dominarão a Babilônia.

[[v24-27-8]]

^<<v24-27-8,8>>^ Submetam-se, portanto, ao rei da Babilônia e sirvam-no. Coloquem o pescoço debaixo do jugo da Babilônia. Eu castigarei qualquer nação que se recusar a servi-lo. Enviarei guerra, fome e doença sobre essa nação até que a Babilônia a conquiste.

[[v24-27-9]]

^<<v24-27-9,9>>^ "‘Não deem ouvidos a seus falsos profetas, adivinhos, intérpretes de sonhos, médiuns e feiticeiros, que dizem: ‘O rei da Babilônia não os dominará’.

[[v24-27-10]]

^<<v24-27-10,10>>^ São todos mentirosos, e suas mentiras os levarão a ser expulsos da terra. Eu os expulsarei e os enviarei para longe, e vocês morrerão.

[[v24-27-11]]

^<<v24-27-11,11>>^ Mas a nação que se sujeitar ao rei da Babilônia poderá continuar em sua terra e cultivá-la. Eu, o SENHOR, falei!’".

[[v24-27-12]]

^<<v24-27-12,12>>^ Depois, repeti a mesma mensagem a Zedequias, rei de Judá: "Submeta-se ao jugo do rei da Babilônia e de seu povo, e vocês viverão.

[[v24-27-13]]

^<<v24-27-13,13>>^ Por que você e seu povo morreriam? Por que escolher guerra, fome e doença que o SENHOR trará contra toda nação que não se submeter ao rei da Babilônia?

[[v24-27-14]]

^<<v24-27-14,14>>^ Não deem ouvidos aos falsos profetas que lhes dizem: ‘O rei da Babilônia não os dominará’. São mentirosos.

[[v24-27-15]]

^<<v24-27-15,15>>^ Assim diz o SENHOR: ‘Não enviei esses profetas. Eles contam mentiras em meu nome. Por isso expulsarei vocês desta terra. Todos vocês morrerão, junto com todos esses profetas’".

[[v24-27-16]]

^<<v24-27-16,16>>^ Então falei aos sacerdotes e ao povo e disse: "Assim diz o SENHOR: ‘Não deem ouvidos aos profetas que afirmam que, em breve, serão devolvidos os objetos preciosos que foram tirados do meu templo e levados para a Babilônia. É tudo mentira.

[[v24-27-17]]

^<<v24-27-17,17>>^ Não lhes deem ouvidos. Submetam-se ao rei da Babilônia, e viverão. Por que provocar a destruição desta cidade inteira?

[[v24-27-18]]

^<<v24-27-18,18>>^ Se, de fato, eles são profetas e transmitem mensagens do SENHOR, que orem ao SENHOR dos Exércitos e supliquem que os objetos que restam no templo do SENHOR, no palácio do rei e em Jerusalém não sejam levados para a Babilônia’.

[[v24-27-19]]

^<<v24-27-19,19>>^ "Pois assim diz o SENHOR dos Exércitos acerca das colunas à entrada do templo, do tanque de bronze chamado Mar, das bases móveis e de todos os outros objetos cerimoniais.

[[v24-27-20]]

^<<v24-27-20,20>>^ Nabucodonosor, rei da Babilônia, os deixou aqui quando levou Joaquim, filho de Jeoaquim, rei de Judá, para o exílio na Babilônia com todos os nobres de Judá e Jerusalém.

[[v24-27-21]]

^<<v24-27-21,21>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel, a respeito dos objetos preciosos que restaram no templo e no palácio do rei de Judá:

[[v24-27-22]]

^<<v24-27-22,22>>^ ‘Todos eles serão levados para a Babilônia e ali ficarão até que eu mande buscá-los’, diz o SENHOR. ‘Então os trarei de volta a Jerusalém’".

'''

xref:024-jeremias/024-jeremias-026.adoc#v24-26-0[&#60; Capítulo Anterior] | <<v24-27-0,Topo>> | xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[Próximo Capítulo &#62;]