include::./index.adoc[]

[[v24-42-0]]
=== Jeremias, 42
// nvt ?, NVT - Nova Versão Transformadora

[[v24-42-1]]

^<<v24-42-1,1>>^ Então todos os comandantes dos grupos de soldados, incluindo Joanã, filho de Careá, e Jezanias, filho de Hosaías, e todo o povo, desde o mais humilde até o mais importante, procuraram

[[v24-42-2]]

^<<v24-42-2,2>>^ o profeta Jeremias e disseram: "Ore por nós ao SENHOR, seu Deus. Como pode ver, somos apenas um pequeno e humilde remanescente comparado ao que éramos antes.

[[v24-42-3]]

^<<v24-42-3,3>>^ Ore para que o SENHOR, seu Deus, nos mostre o que devemos fazer e para onde devemos ir".

[[v24-42-4]]

^<<v24-42-4,4>>^ "Está bem", disse Jeremias. "Orarei ao SENHOR, seu Deus, como vocês pediram, e lhes direi tudo que ele responder. Não esconderei nada de vocês."

[[v24-42-5]]

^<<v24-42-5,5>>^ Então disseram a Jeremias: "Que o SENHOR, seu Deus, seja testemunha verdadeira e fiel contra nós se não obedecermos a tudo que ele nos ordenar!

[[v24-42-6]]

^<<v24-42-6,6>>^ Quer suas ordens nos agradem quer não, obedeceremos ao SENHOR, nosso Deus, a quem o enviamos com nossa súplica. Pois, se obedecermos ao SENHOR, nosso Deus, tudo irá bem para nós".

[[v24-42-7]]

^<<v24-42-7,7>>^ Dez dias depois, o SENHOR enviou sua resposta a Jeremias.

[[v24-42-8]]

^<<v24-42-8,8>>^ Então o profeta chamou Joanã, filho de Careá, os outros comandantes e todo o povo, desde o mais humilde até o mais importante,

[[v24-42-9]]

^<<v24-42-9,9>>^ e disse-lhes: "Vocês me enviaram ao SENHOR, o Deus de Israel, com seu pedido, e esta é a resposta:

[[v24-42-10]]

^<<v24-42-10,10>>^ ‘Se ficarem nesta terra, eu os edificarei, e não os derrubarei; eu os plantarei, e não os arrancarei. Pois lamento pela calamidade que trouxe sobre vocês.

[[v24-42-11]]

^<<v24-42-11,11>>^ Não precisam mais ter medo do rei da Babilônia’, diz o SENHOR. ‘Pois eu estou com vocês; eu os salvarei e os livrarei das mãos dele.

[[v24-42-12]]

^<<v24-42-12,12>>^ Terei compaixão de vocês e farei que ele também tenha e permita que fiquem nesta terra.’

[[v24-42-13]]

^<<v24-42-13,13>>^ "Mas, se vocês se recusarem a obedecer ao SENHOR, seu Deus, e se disserem: ‘Não ficaremos nesta terra;

[[v24-42-14]]

^<<v24-42-14,14>>^ iremos para o Egito onde não há guerra, nem convocação para lutar, nem fome, e ali viveremos’,

[[v24-42-15]]

^<<v24-42-15,15>>^ então ouçam a mensagem do SENHOR para o remanescente de Judá. Assim diz o SENHOR dos Exércitos, o Deus de Israel: ‘Se vocês estão decididos a ir para o Egito e morar lá,

[[v24-42-16]]

^<<v24-42-16,16>>^ a guerra e a fome que tanto temem os alcançarão e ali vocês morrerão.

[[v24-42-17]]

^<<v24-42-17,17>>^ Isso é o que espera todos que insistirem em partir e morar no Egito. Sim, morrerão por guerra, fome e doença. Ninguém escapará da calamidade que trarei sobre vocês’.

[[v24-42-18]]

^<<v24-42-18,18>>^ "Assim diz o SENHOR dos Exércitos, o Deus de Israel: ‘Assim como derramei minha ira e minha fúria sobre os habitantes de Jerusalém, também as derramarei sobre vocês quando entrarem no Egito. Serão objeto de condenação, horror, maldição e zombaria. Nunca mais verão sua terra natal’.

[[v24-42-19]]

^<<v24-42-19,19>>^ "Ouça, ó remanescente de Judá. O SENHOR lhes disse: ‘Não vão para o Egito!’. Não se esqueçam dessa advertência que hoje lhes dei.

[[v24-42-20]]

^<<v24-42-20,20>>^ Pois vocês não foram honestos quando me enviaram para orar ao SENHOR, seu Deus, por vocês. Disseram: ‘Diga-nos tudo que o SENHOR, nosso Deus, falar, e nós o faremos’.

[[v24-42-21]]

^<<v24-42-21,21>>^ Hoje lhes disse exatamente o que ele falou, mas vocês não obedecerão ao SENHOR, seu Deus, como não lhe obedeceram no passado.

[[v24-42-22]]

^<<v24-42-22,22>>^ Estejam certos, portanto, de que morrerão por guerra, fome e doença no Egito, para onde insistem em ir".

'''

xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[&#60; Capítulo Anterior] | <<v24-42-0,Topo>> | xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[Próximo Capítulo &#62;]