include::./index.adoc[]

[[v24-34-0]]
=== Jeremias, 34
// nvt ?, NVT - Nova Versão Transformadora

[[v24-34-1]]

^<<v24-34-1,1>>^ Nabucodonosor, rei da Babilônia, veio com todos os exércitos dos reinos que ele governava e lutou contra Jerusalém e contra as cidades de Judá. Naquela ocasião, Jeremias recebeu esta mensagem do SENHOR:

[[v24-34-2]]

^<<v24-34-2,2>>^ "Vá a Zedequias, rei de Judá, e diga-lhe: ‘Assim diz o SENHOR, o Deus de Israel: Estou prestes a entregar esta cidade ao rei da Babilônia, e ele a queimará de alto a baixo.

[[v24-34-3]]

^<<v24-34-3,3>>^ Você não escapará das mãos dele, mas será capturado e levado para falar face a face com o rei da Babilônia. Então será enviado para o exílio na Babilônia.

[[v24-34-4]]

^<<v24-34-4,4>>^ "‘Ouça, porém, esta promessa do SENHOR, ó Zedequias, rei de Judá. Assim diz o SENHOR: Você não morrerá na guerra,

[[v24-34-5]]

^<<v24-34-5,5>>^ mas em paz. O povo queimará incenso em sua honra, como fizeram em honra de seus antepassados, os reis que o precederam. Chorarão por você e lamentarão: ‘Que tristeza! Nosso rei morreu!’. Eu decretei isso, diz o SENHOR’".

[[v24-34-6]]

^<<v24-34-6,6>>^ O profeta Jeremias transmitiu essa mensagem a Zedequias, rei de Judá.

[[v24-34-7]]

^<<v24-34-7,7>>^ Nessa época, o exército babilônio cercava Jerusalém, Laquis e Azeca, as únicas cidades fortificadas de Judá que ainda não tinham sido conquistadas.

[[v24-34-8]]

^<<v24-34-8,8>>^ Jeremias recebeu esta mensagem do SENHOR depois que o rei Zedequias fez uma aliança com o povo para libertar os escravos.

[[v24-34-9]]

^<<v24-34-9,9>>^ Ele havia ordenado que todo o povo libertasse suas escravas e seus escravos hebreus. Ninguém devia manter em escravidão alguém de seu próprio povo.

[[v24-34-10]]

^<<v24-34-10,10>>^ Os oficiais e todo o povo tinham obedecido à ordem do rei e libertado cada um de seus escravos,

[[v24-34-11]]

^<<v24-34-11,11>>^ mas depois mudaram de ideia. Tomaram de volta os homens e as mulheres que haviam libertado e os obrigaram a ser escravos novamente.

[[v24-34-12]]

^<<v24-34-12,12>>^ Então o SENHOR lhes deu esta mensagem por meio de Jeremias:

[[v24-34-13]]

^<<v24-34-13,13>>^ "Assim diz o SENHOR, o Deus de Israel: Fiz uma aliança com seus antepassados muito tempo atrás, quando os livrei da escravidão no Egito.

[[v24-34-14]]

^<<v24-34-14,14>>^ Disse-lhes que todo escravo hebreu deveria ser liberto depois de servir durante seis anos. Contudo, seus antepassados não me deram ouvidos nem me obedeceram.

[[v24-34-15]]

^<<v24-34-15,15>>^ Há pouco tempo, vocês se arrependeram e fizeram o que era certo aos meus olhos. Libertaram os escravos e fizeram comigo uma aliança solene no templo que leva meu nome.

[[v24-34-16]]

^<<v24-34-16,16>>^ Agora, porém, voltaram atrás em seu juramento e profanaram meu nome ao pegar de volta os homens e as mulheres que haviam libertado e os obrigar a ser escravos novamente.

[[v24-34-17]]

^<<v24-34-17,17>>^ "Portanto, assim diz o SENHOR: Vocês não me obedeceram e não libertaram seu povo. Por isso lhes darei liberdade para serem destruídos por guerra, doença e fome. Vocês serão objeto de horror para todas as nações da terra.

[[v24-34-18]]

^<<v24-34-18,18>>^ Porque não cumpriram os termos de minha aliança, eu os cortarei ao meio, como vocês cortaram o bezerro e caminharam entre as duas partes para confirmar seus votos.

[[v24-34-19]]

^<<v24-34-19,19>>^ Sim, cortarei ao meio todos que se comprometeram com a aliança, quer sejam oficiais de Judá e de Jerusalém, oficiais do palácio, sacerdotes ou gente comum.

[[v24-34-20]]

^<<v24-34-20,20>>^ Eu os entregarei a seus inimigos, e eles os matarão. Seus corpos servirão de alimento para os abutres e os animais selvagens.

[[v24-34-21]]

^<<v24-34-21,21>>^ "Entregarei Zedequias, rei de Judá, e seus oficiais ao exército do rei da Babilônia. E, embora tenham se retirado de Jerusalém por um tempo,

[[v24-34-22]]

^<<v24-34-22,22>>^ chamarei de volta os exércitos babilônios. Eles lutarão contra a cidade, a conquistarão e a queimarão de alto a baixo. Farei que todas as cidades de Judá sejam destruídas e que ninguém more nelas".

'''

xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[&#60; Capítulo Anterior] | <<v24-34-0,Topo>> | xref:024-jeremias/024-jeremias-035.adoc#v24-35-0[Próximo Capítulo &#62;]