include::./index.adoc[]

[[v24-47-0]]
=== Jeremias, 47
// nvt ?, NVT - Nova Versão Transformadora

[[v24-47-1]]

^<<v24-47-1,1>>^ O SENHOR deu esta mensagem ao profeta Jeremias acerca dos filisteus de Gaza, antes de ela ser derrotada pelo exército egípcio.

[[v24-47-2]]

^<<v24-47-2,2>>^ Assim diz o SENHOR: "Do norte se aproxima uma enchente para inundar a terra. Destruirá a terra e tudo que nela há, tanto as cidades como seus habitantes. O povo gritará de terror, e todos na terra se lamentarão.

[[v24-47-3]]

^<<v24-47-3,3>>^ Ouçam o ruído dos cascos de cavalos, o barulho dos carros de guerra e o estrondo de suas rodas. Os pais fogem apavorados, sem olhar para trás, para seus filhos indefesos.

[[v24-47-4]]

^<<v24-47-4,4>>^ "Chegou o dia de destruir os filisteus e seus aliados de Tiro e de Sidom. Sim, o SENHOR destruirá os filisteus, o remanescente da ilha de Creta.

[[v24-47-5]]

^<<v24-47-5,5>>^ Gaza será humilhada, e sua cabeça será raspada; Ascalom ficará em silêncio. E você, remanescente da planície costeira, até quando cortará a si mesmo em sinal de lamento?

[[v24-47-6]]

^<<v24-47-6,6>>^ "Ó espada do SENHOR, quando descansará? Volte para sua bainha; repouse e aquiete-se.

[[v24-47-7]]

^<<v24-47-7,7>>^ "Mas como pode se aquietar se o SENHOR a enviou numa missão? Deve destruir a cidade de Ascalom e o povo que vive no litoral".

'''

xref:024-jeremias/024-jeremias-046.adoc#v24-46-0[&#60; Capítulo Anterior] | <<v24-47-0,Topo>> | xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[Próximo Capítulo &#62;]