include::./index.adoc[]

[[v24-19-0]]
=== Jeremias, 19
// nvt ?, NVT - Nova Versão Transformadora

[[v24-19-1]]

^<<v24-19-1,1>>^ Assim me disse o SENHOR: "Vá e compre um vaso de barro. Depois, peça a alguns líderes do povo e dos sacerdotes que o acompanhem.

[[v24-19-2]]

^<<v24-19-2,2>>^ Vá ao depósito de lixo no vale de Ben-Hinom, que fica junto ao portão dos Cacos, e proclame esta mensagem:

[[v24-19-3]]

^<<v24-19-3,3>>^ ‘Ouçam esta mensagem do SENHOR, reis de Judá e habitantes de Jerusalém! Assim diz o SENHOR dos Exércitos, o Deus de Israel: Trarei calamidade sobre este lugar, calamidade tão terrível que fará tinir os ouvidos de quem ouvir a respeito!

[[v24-19-4]]

^<<v24-19-4,4>>^ "‘Pois o povo me abandonou e transformou este vale num lugar de perversidade. Queimam incenso a deuses estrangeiros, ídolos até então desconhecidos desta geração, de seus antepassados e dos reis de Judá. Encheram este lugar com o sangue de crianças inocentes.

[[v24-19-5]]

^<<v24-19-5,5>>^ Construíram lugares de adoração a Baal e lhe queimaram os filhos como sacrifício. Jamais ordenei tamanha maldade; nunca me passou pela mente!

[[v24-19-6]]

^<<v24-19-6,6>>^ Portanto, tomem cuidado, diz o SENHOR, pois está chegando o dia em que este lugar não se chamará mais Tofete, nem vale de Ben-Hinom, mas vale da Matança.

[[v24-19-7]]

^<<v24-19-7,7>>^ "‘Pois eu transtornarei os planos minuciosos de Judá e Jerusalém. Permitirei que seu povo seja massacrado por exércitos invasores e deixarei seus cadáveres para servirem de alimento para os abutres e os animais selvagens.

[[v24-19-8]]

^<<v24-19-8,8>>^ Transformarei Jerusalém em um monte de escombros; será um monumento à sua tolice. Todos que passarem por lá ficarão pasmos e abrirão a boca de espanto quando virem suas ruínas.

[[v24-19-9]]

^<<v24-19-9,9>>^ Farei os inimigos cercarem a cidade, até que acabe toda a comida. Então, os que estiverem presos dentro dela comerão os próprios filhos, filhas e amigos. Serão levados ao mais absoluto desespero’.

[[v24-19-10]]

^<<v24-19-10,10>>^ "Então, Jeremias, você quebrará o vaso à vista desses homens

[[v24-19-11]]

^<<v24-19-11,11>>^ e lhes dirá: ‘Assim diz o SENHOR dos Exércitos: Como este vaso está despedaçado, assim despedaçarei o povo de Judá e o povo de Jerusalém, e não haverá quem possa restaurá-los. Enterrarão os corpos aqui em Tofete, até que não haja mais espaço.

[[v24-19-12]]

^<<v24-19-12,12>>^ Assim farei a este lugar e a seu povo, diz o SENHOR. Farei a cidade ficar contaminada como Tofete.

[[v24-19-13]]

^<<v24-19-13,13>>^ Sim, todas as casas de Jerusalém, incluindo o palácio dos reis de Judá, se tornarão como Tofete, todas as casas em que vocês queimaram incenso nos terraços para adorar as estrelas e apresentaram ofertas derramadas para seus ídolos’".

[[v24-19-14]]

^<<v24-19-14,14>>^ Então Jeremias voltou de Tofete, onde havia anunciado essa mensagem, e parou diante do templo do SENHOR. Ali, disse ao povo:

[[v24-19-15]]

^<<v24-19-15,15>>^ "Assim diz o SENHOR dos Exércitos, o Deus de Israel: Trarei calamidade sobre esta cidade e sobre os povoados ao redor conforme prometi, pois vocês se recusaram teimosamente a me ouvir".

'''

xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[&#60; Capítulo Anterior] | <<v24-19-0,Topo>> | xref:024-jeremias/024-jeremias-020.adoc#v24-20-0[Próximo Capítulo &#62;]