include::./index.adoc[]

[[v24-5-0]]
=== Jeremias, 5
// nvt ?, NVT - Nova Versão Transformadora

[[v24-5-1]]

^<<v24-5-1,1>>^ "Corram por todas as ruas de Jerusalém", diz o SENHOR. "Procurem por toda parte, busquem em cada lugar! Se encontrarem ao menos uma pessoa justa e honesta, não destruirei a cidade.

[[v24-5-2]]

^<<v24-5-2,2>>^ Contudo, mesmo quando estão sob juramento e declaram: ‘Tão certo como vive o SENHOR’, continuam a mentir!"

[[v24-5-3]]

^<<v24-5-3,3>>^ SENHOR, tu procuras honestidade; feriste teu povo, mas eles não se importaram. Tu os esmagaste, mas eles se recusaram a ser corrigidos. São teimosos, duros como pedra; não querem se arrepender.

[[v24-5-4]]

^<<v24-5-4,4>>^ Então eu pensei: "O que se pode esperar dos pobres? Eles nada sabem. Não conhecem os caminhos do SENHOR, não entendem o que a justiça de Deus exige.

[[v24-5-5]]

^<<v24-5-5,5>>^ Portanto, irei a seus líderes e falarei com eles; por certo conhecem os caminhos do Senhor e entendem o que a justiça de Deus exige. Mas os líderes também, de comum acordo, livraram-se do jugo de Deus e quebraram suas correntes.

[[v24-5-6]]

^<<v24-5-6,6>>^ Agora, um leão do bosque os atacará; um lobo do deserto os destruirá. Um leopardo ficará à espreita nos arredores de suas cidades e despedaçará qualquer um que se arriscar a sair. Pois sua rebeldia é grande, e muitos são seus pecados.

[[v24-5-7]]

^<<v24-5-7,7>>^ "Como posso perdoá-los? Até mesmo seus filhos se afastaram de mim; juram por deuses que, na verdade, não são deuses! Eu os alimentei até que estivessem satisfeitos, e, no entanto, cometeram adultério e se reuniram para ir a prostíbulos!

[[v24-5-8]]

^<<v24-5-8,8>>^ São garanhões bem alimentados e cheios de desejo, cada um relinchando para a esposa de seu próximo.

[[v24-5-9]]

^<<v24-5-9,9>>^ Acaso não devo castigá-los por isso?", diz o SENHOR. "Não devo me vingar de uma nação como esta?

[[v24-5-10]]

^<<v24-5-10,10>>^ "Vão por entre as fileiras dos vinhedos e destruam as videiras, mas deixem algumas vivas. Cortem os ramos das videiras, pois essa gente não pertence ao SENHOR.

[[v24-5-11]]

^<<v24-5-11,11>>^ O povo de Israel e o povo de Judá têm me traído", diz o SENHOR.

[[v24-5-12]]

^<<v24-5-12,12>>^ "Mentiram a respeito do Senhor e disseram: ‘Ele não vai nos incomodar! Nenhuma calamidade virá sobre nós; não haverá guerra nem fome.

[[v24-5-13]]

^<<v24-5-13,13>>^ Os profetas que ele envia são uns tagarelas que não falam em nome dele. Que suas previsões de calamidade caiam sobre eles mesmos!’."

[[v24-5-14]]

^<<v24-5-14,14>>^ Portanto, assim me diz o SENHOR, o Deus dos Exércitos: "Porque meu povo fala desse modo, minhas mensagens sairão de sua boca como chamas de fogo e queimarão o povo como lenha.

[[v24-5-15]]

^<<v24-5-15,15>>^ Ó Israel, trarei uma nação distante para atacá-lo", diz o SENHOR. "É uma nação poderosa, nação antiga, cuja língua você não conhece, cuja fala você não entende.

[[v24-5-16]]

^<<v24-5-16,16>>^ Suas armas são mortais, seus guerreiros são valentes.

[[v24-5-17]]

^<<v24-5-17,17>>^ Devorarão suas colheitas e seu alimento, seus filhos e suas filhas. Devorarão seus rebanhos e seu gado, suas uvas e seus figos. Destruirão suas cidades fortificadas, que vocês consideram tão seguras.

[[v24-5-18]]

^<<v24-5-18,18>>^ "Mesmo naqueles dias, porém, eu não os destruirei completamente", diz o SENHOR.

[[v24-5-19]]

^<<v24-5-19,19>>^ "E, quando o povo lhe perguntar: ‘Por que o SENHOR, nosso Deus, fez tudo isso conosco?’, responda: ‘Vocês o rejeitaram e se entregaram a deuses estrangeiros em sua própria terra. Agora, servirão estrangeiros numa terra que não é de vocês’."

[[v24-5-20]]

^<<v24-5-20,20>>^ "Anuncie a Israel, diga a Judá:

[[v24-5-21]]

^<<v24-5-21,21>>^ Ouça, povo tolo e insensato, que tem olhos, mas não vê, que tem ouvidos, mas não ouve.

[[v24-5-22]]

^<<v24-5-22,22>>^ Acaso não me temem? Por que não tremem diante de mim? Eu, o SENHOR, pus a areia como limite do mar, limite permanente que as águas não podem atravessar. Ainda que as ondas se levantem e se agitem, não ultrapassam os limites que estabeleci.

[[v24-5-23]]

^<<v24-5-23,23>>^ Mas este povo tem coração teimoso e rebelde; afastaram-se de mim e me abandonaram.

[[v24-5-24]]

^<<v24-5-24,24>>^ Não dizem com sinceridade: ‘Vivamos com temor do SENHOR, nosso Deus, pois ele nos dá as chuvas de outono e de primavera e nos garante a colheita no tempo certo’.

[[v24-5-25]]

^<<v24-5-25,25>>^ Sua perversidade afastou de vocês essas bênçãos maravilhosas; seu pecado lhes tomou todas essas coisas boas.

[[v24-5-26]]

^<<v24-5-26,26>>^ "No meio do meu povo existem homens perversos que espreitam suas vítimas como o caçador de tocaia. Estão sempre colocando armadilhas para apanhar as pessoas.

[[v24-5-27]]

^<<v24-5-27,27>>^ Como uma gaiola cheia de pássaros, a casa deles é cheia de tramas perversas. Por isso, são poderosos e ricos,

[[v24-5-28]]

^<<v24-5-28,28>>^ gordos e de aparência saudável. Suas maldades não têm limites; não querem fazer justiça aos órfãos e negam os direitos dos pobres.

[[v24-5-29]]

^<<v24-5-29,29>>^ Acaso não devo castigá-los por isso?", diz o SENHOR. "Não devo me vingar de uma nação como esta?

[[v24-5-30]]

^<<v24-5-30,30>>^ Algo horrível e espantoso ocorre nesta terra:

[[v24-5-31]]

^<<v24-5-31,31>>^ os profetas fazem profecias falsas, os sacerdotes governam com mão de ferro, e, pior ainda, meu povo fica feliz com isso! O que farão, porém, quando o fim chegar?"

'''

xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[Próximo Capítulo &#62;]