include::./index.adoc[]

[[v24-41-0]]
=== Jeremias, 41
// nvt ?, NVT - Nova Versão Transformadora

[[v24-41-1]]

^<<v24-41-1,1>>^ Em outubro daquele ano, Ismael, filho de Netanias e neto de Elisama, que era da família real e que havia sido um alto oficial do rei, foi a Mispá com dez homens para se encontrar com Gedalias, filho de Aicam e neto de Safã. Enquanto faziam uma refeição juntos,

[[v24-41-2]]

^<<v24-41-2,2>>^ Ismael e os dez homens se levantaram de um salto, puxaram suas espadas e mataram Gedalias, que o rei da Babilônia havia nomeado governador.

[[v24-41-3]]

^<<v24-41-3,3>>^ Ismael também matou todos os soldados judeus e babilônios que estavam com Gedalias em Mispá.

[[v24-41-4]]

^<<v24-41-4,4>>^ No dia seguinte, antes que alguém soubesse do assassinato de Gedalias,

[[v24-41-5]]

^<<v24-41-5,5>>^ oitenta homens chegaram de Siquém, Siló e Samaria para adorar no templo do SENHOR. Tinham raspado a cabeça, rasgado as roupas e se cortado e traziam ofertas de cereal e incenso.

[[v24-41-6]]

^<<v24-41-6,6>>^ Ismael, filho de Netanias, saiu de Mispá e foi ao encontro deles, chorando ao longo do caminho. Quando os encontrou, disse: "Venham e vejam o que aconteceu a Gedalias, filho de Aicam".

[[v24-41-7]]

^<<v24-41-7,7>>^ Assim que todos entraram na cidade, Ismael e os homens que o acompanhavam mataram setenta deles e jogaram os corpos numa cisterna.

[[v24-41-8]]

^<<v24-41-8,8>>^ Os outros dez sobreviveram, pois haviam convencido Ismael a soltá-los ao prometer lhes trazer os suprimentos de trigo, cevada, azeite e mel que haviam escondido.

[[v24-41-9]]

^<<v24-41-9,9>>^ A cisterna em que Ismael jogou os corpos dos homens que ele assassinou era a grande cisterna cavada pelo rei Asa, quando ele fortificou a cidade para se defender de Baasa, rei de Israel. Ismael, filho de Netanias, a encheu de cadáveres.

[[v24-41-10]]

^<<v24-41-10,10>>^ Então Ismael prendeu as filhas do rei e outras pessoas que Nebuzaradã, capitão da guarda, havia deixado em Mispá aos cuidados de Gedalias. Ismael partiu para a terra de Amom levando os prisioneiros.

[[v24-41-11]]

^<<v24-41-11,11>>^ Quando Joanã, filho de Careá, e os outros comandantes que o acompanhavam souberam dos crimes de Ismael,

[[v24-41-12]]

^<<v24-41-12,12>>^ reuniram todos os seus soldados e partiram para lutar contra ele. Eles o alcançaram no grande açude perto de Gibeom.

[[v24-41-13]]

^<<v24-41-13,13>>^ O povo que Ismael tinha capturado gritou de alegria quando viu Joanã e os outros comandantes.

[[v24-41-14]]

^<<v24-41-14,14>>^ Todos os prisioneiros de Mispá escaparam e começaram a ajudar Joanã.

[[v24-41-15]]

^<<v24-41-15,15>>^ Enquanto isso, Ismael e oito dos homens que estavam com ele escaparam de Joanã e foram para a terra de Amom.

[[v24-41-16]]

^<<v24-41-16,16>>^ Então Joanã, filho de Careá, e os outros comandantes levaram todo o povo que tinham resgatado em Gibeom: os soldados, as mulheres, as crianças e os oficiais do palácio que Ismael havia capturado em Mispá depois de matar Gedalias.

[[v24-41-17]]

^<<v24-41-17,17>>^ Foram todos para o povoado de Gerute-Quimã, perto de Belém, de onde planejavam fugir para o Egito.

[[v24-41-18]]

^<<v24-41-18,18>>^ Tinham medo daquilo que os babilônios fariam quando soubessem que Ismael havia assassinado Gedalias, o governador nomeado pelo rei da Babilônia.

'''

xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[&#60; Capítulo Anterior] | <<v24-41-0,Topo>> | xref:024-jeremias/024-jeremias-042.adoc#v24-42-0[Próximo Capítulo &#62;]