include::./index.adoc[]

[[v24-49-0]]
=== Jeremias, 49
// nvt ?, NVT - Nova Versão Transformadora

[[v24-49-1]]

^<<v24-49-1,1>>^ Esta é a mensagem acerca dos amonitas. Assim diz o SENHOR: "Acaso não há descendentes de Israel para herdar a terra de Gade? Por que vocês, que adoram Moloque, habitam nas cidades de Gade?

[[v24-49-2]]

^<<v24-49-2,2>>^ Está chegando o dia", diz o SENHOR, "em que farei soar o grito de guerra contra a cidade de Rabá. Ela se tornará um monte de ruínas, e os povoados vizinhos serão queimados. Então Israel tomará de volta as terras que vocês tiraram dele", diz o SENHOR.

[[v24-49-3]]

^<<v24-49-3,3>>^ "Grite, ó Hesbom, pois a cidade de Ai está destruída. Chorem, ó habitantes de Rabá, e vistam roupas de luto. Lamentem e escondam-se entre os muros, pois seu deus, Moloque, será levado para terras distantes, junto com seus sacerdotes e oficiais.

[[v24-49-4]]

^<<v24-49-4,4>>^ Você se orgulha de seus vales férteis, ó filha rebelde. Confiou em suas riquezas e pensou que ninguém jamais lhe faria mal.

[[v24-49-5]]

^<<v24-49-5,5>>^ Mas eu trarei terror sobre você", diz o Soberano, o SENHOR dos Exércitos. "Seus vizinhos a expulsarão de sua terra, e ninguém ajudará seus habitantes quando fugirem.

[[v24-49-6]]

^<<v24-49-6,6>>^ No futuro, porém, restaurarei a situação dos amonitas. Eu, o SENHOR, falei."

[[v24-49-7]]

^<<v24-49-7,7>>^ Esta é a mensagem acerca de Edom. Assim diz o SENHOR dos Exércitos: "Não há sabedoria em Temã? Não resta ninguém para dar bons conselhos? Sua sabedoria desapareceu?

[[v24-49-8]]

^<<v24-49-8,8>>^ Deem meia-volta e fujam! Escondam-se em cavernas profundas, ó habitantes de Dedã! Pois, quando eu trouxer calamidade sobre Edom, castigarei vocês também.

[[v24-49-9]]

^<<v24-49-9,9>>^ Aqueles que colhem uvas sempre deixam algumas para os pobres. Se ladrões viessem à noite, não levariam tudo.

[[v24-49-10]]

^<<v24-49-10,10>>^ Mas eu despojarei completamente a terra de Edom, e não restará lugar algum para se esconder. Seus filhos, irmãos e vizinhos serão todos destruídos, e Edom deixará de existir.

[[v24-49-11]]

^<<v24-49-11,11>>^ Protegerei, contudo, os órfãos que restarem em seu meio, e as viúvas também podem esperar minha ajuda".

[[v24-49-12]]

^<<v24-49-12,12>>^ Assim diz o SENHOR: "Se os inocentes têm de sofrer, quanto mais vocês! Não ficarão impunes; também beberão deste cálice.

[[v24-49-13]]

^<<v24-49-13,13>>^ Pois jurei por meu próprio nome", diz o SENHOR, "que Bozra se tornará objeto de horror e um monte de ruínas; será motivo de zombaria e maldição. Todas as suas cidades ficarão desoladas para sempre."

[[v24-49-14]]

^<<v24-49-14,14>>^ Ouvi uma mensagem do SENHOR, que um embaixador foi enviado às nações para dizer: "Formem uma coalizão contra Edom e preparem-se para a batalha!".

[[v24-49-15]]

^<<v24-49-15,15>>^ Assim diz o SENHOR a Edom: "Eu a tornarei pequena entre as nações; será desprezada por todos.

[[v24-49-16]]

^<<v24-49-16,16>>^ Você foi iludida pelo medo que provoca e por seu orgulho. Vive numa fortaleza de pedra e controla os altos dos montes. Mas ainda que faça seu ninho nas alturas com as águias, eu a derrubarei", diz o SENHOR.

[[v24-49-17]]

^<<v24-49-17,17>>^ "Edom será objeto de horror; todos que passarem por ela ficarão pasmos e abrirão a boca de espanto quando virem suas ruínas.

[[v24-49-18]]

^<<v24-49-18,18>>^ Será como a destruição de Sodoma e Gomorra e de suas cidades vizinhas", diz o SENHOR. "Ninguém viverá ali, ninguém habitará nela.

[[v24-49-19]]

^<<v24-49-19,19>>^ Virei como um leão da mata do Jordão que ataca as ovelhas no pasto. Expulsarei Edom de sua terra e ali colocarei o líder que eu escolher. Pois quem é semelhante a mim e quem pode me desafiar? Que governante pode se opor à minha vontade?"

[[v24-49-20]]

^<<v24-49-20,20>>^ Ouçam o que o SENHOR planejou contra Edom e contra os habitantes de Temã. Até as crianças serão arrastadas como ovelhas, e suas casas, destruídas.

[[v24-49-21]]

^<<v24-49-21,21>>^ A terra tremerá com o estrondo da queda de Edom, e até do mar Vermelho se ouvirá seu clamor.

[[v24-49-22]]

^<<v24-49-22,22>>^ Veja, o inimigo desce veloz, como águia, e abre suas asas sobre Bozra! Até os guerreiros mais valentes ficarão em agonia, como a mulher em trabalho de parto.

[[v24-49-23]]

^<<v24-49-23,23>>^ Esta é a mensagem acerca de Damasco: "O medo tomou conta das cidades de Hamate e Arpade, pois ouviram a notícia de sua destruição. Seu coração está agitado, como o mar numa tempestade.

[[v24-49-24]]

^<<v24-49-24,24>>^ Damasco se enfraqueceu, e todos os seus habitantes se preparam para fugir. Medo, angústia e dor se apoderam dela, como da mulher em trabalho de parto.

[[v24-49-25]]

^<<v24-49-25,25>>^ A cidade famosa, antes tão alegre, será abandonada.

[[v24-49-26]]

^<<v24-49-26,26>>^ Seus jovens cairão nas ruas, todos os seus soldados serão mortos", diz o SENHOR dos Exércitos.

[[v24-49-27]]

^<<v24-49-27,27>>^ "Acenderei fogo nos muros de Damasco, e ele queimará os palácios de Ben-Hadade."

[[v24-49-28]]

^<<v24-49-28,28>>^ Esta é a mensagem acerca de Quedar e dos reinos de Hazor, que Nabucodonosor, rei da Babilônia, atacou. Assim diz o SENHOR: "Avancem contra Quedar! Destruam o povo do Oriente!

[[v24-49-29]]

^<<v24-49-29,29>>^ Tomarão seus rebanhos e tendas e levarão seus bens e camelos. Por toda parte se ouvirão gritos de pânico: ‘Estamos cercados de terror!’.

[[v24-49-30]]

^<<v24-49-30,30>>^ Corram para salvar a vida", diz o SENHOR. "Escondam-se em cavernas profundas, habitantes de Hazor, pois Nabucodonosor, rei da Babilônia, está se preparando para destruí-los.

[[v24-49-31]]

^<<v24-49-31,31>>^ "Subam e ataquem essa nação confiante", diz o SENHOR. "Seu povo vive sozinho no deserto; não tem muros nem portões.

[[v24-49-32]]

^<<v24-49-32,32>>^ Vocês tomarão como despojo os camelos e todos os outros animais deles. Espalharei ao vento essa gente que vive em lugares distantes. Trarei calamidade sobre eles de todos os lados", diz o SENHOR.

[[v24-49-33]]

^<<v24-49-33,33>>^ "Hazor se tornará morada de chacais e ficará desolada para sempre. Ninguém viverá ali, ninguém habitará nela."

[[v24-49-34]]

^<<v24-49-34,34>>^ O profeta Jeremias recebeu esta mensagem do SENHOR acerca de Elão no início do reinado de Zedequias, rei de Judá.

[[v24-49-35]]

^<<v24-49-35,35>>^ Assim diz o SENHOR dos Exércitos: "Destruirei os arqueiros de Elão, os melhores soldados de seus exércitos.

[[v24-49-36]]

^<<v24-49-36,36>>^ Trarei inimigos de todos os lados e espalharei os habitantes de Elão aos quatro ventos; serão exilados em nações do mundo inteiro.

[[v24-49-37]]

^<<v24-49-37,37>>^ Irei com os inimigos de Elão para despedaçá-la; em minha ira ardente, trarei calamidade sobre os elamitas", diz o SENHOR. "Seus inimigos os perseguirão com a espada até que os tenham destruído completamente.

[[v24-49-38]]

^<<v24-49-38,38>>^ Colocarei meu trono em Elão", diz o SENHOR, "e destruirei seu rei e seus oficiais.

[[v24-49-39]]

^<<v24-49-39,39>>^ No futuro, porém, restaurarei a situação de Elão. Eu, o SENHOR, falei!"

'''

xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[&#60; Capítulo Anterior] | <<v24-49-0,Topo>> | xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[Próximo Capítulo &#62;]