include::./index.adoc[]

[[v24-1-0]]
=== Jeremias, 1
// nvt ?, NVT - Nova Versão Transformadora

[[v24-1-1]]

^<<v24-1-1,1>>^ Estas são as palavras de Jeremias, filho de Hilquias, um dos sacerdotes da cidade de Anatote, na terra de Benjamim.

[[v24-1-2]]

^<<v24-1-2,2>>^ O SENHOR lhe deu esta mensagem no décimo terceiro ano do reinado de Josias, filho de Amom, rei de Judá.

[[v24-1-3]]

^<<v24-1-3,3>>^ Também lhe deu outras mensagens durante todo o reinado de Jeoaquim, filho de Josias, rei de Judá, até o décimo primeiro ano do reinado de Zedequias, outro filho de Josias. Em agosto daquele ano, o povo de Jerusalém foi levado para o exílio.

[[v24-1-4]]

^<<v24-1-4,4>>^ O SENHOR me deu esta mensagem:

[[v24-1-5]]

^<<v24-1-5,5>>^ "Eu o conheci antes de formá-lo no ventre de sua mãe; antes de você nascer, eu o separei e o nomeei para ser meu profeta às nações".

[[v24-1-6]]

^<<v24-1-6,6>>^ Então eu disse: "Ó Soberano SENHOR, não sou capaz de falar em teu nome! Sou jovem demais para isso!".

[[v24-1-7]]

^<<v24-1-7,7>>^ O SENHOR respondeu: "Não diga: ‘Sou jovem demais’, pois você irá aonde eu o enviar e dirá o que eu lhe ordenar.

[[v24-1-8]]

^<<v24-1-8,8>>^ E não tenha medo do povo, pois estarei com você e o protegerei. Eu, o SENHOR, falei!".

[[v24-1-9]]

^<<v24-1-9,9>>^ Então o SENHOR estendeu a mão, tocou minha boca e disse: "Veja, coloquei minhas palavras em sua boca!

[[v24-1-10]]

^<<v24-1-10,10>>^ Hoje lhe dou autoridade para enfrentar nações e reinos, para arrancar e derrubar, para destruir e arrasar, para edificar e plantar".

[[v24-1-11]]

^<<v24-1-11,11>>^ Então o SENHOR me disse: "O que você vê, Jeremias?". Eu respondi: "Vejo o ramo de uma amendoeira".

[[v24-1-12]]

^<<v24-1-12,12>>^ "Você viu bem", disse o SENHOR. "Isso significa que estou vigiando e certamente realizarei todos os meus planos."

[[v24-1-13]]

^<<v24-1-13,13>>^ Então o SENHOR falou comigo outra vez e perguntou: "O que vê agora?". Respondi: "Vejo uma panela fervendo, derramando-se do norte para cá".

[[v24-1-14]]

^<<v24-1-14,14>>^ O SENHOR disse: "Terror vindo do norte ferverá e se derramará sobre o povo desta terra.

[[v24-1-15]]

^<<v24-1-15,15>>^ Ouça! Estou convocando todos os exércitos dos reinos do norte. Eu, o SENHOR, falei! "Eles colocarão seus tronos junto aos portões de Jerusalém. Atacarão seus muros e todas as outras cidades de Judá.

[[v24-1-16]]

^<<v24-1-16,16>>^ Pronunciarei julgamento contra meu povo por toda a sua maldade, por terem me abandonado e queimado incenso para outros deuses; adoram ídolos que fizeram com as próprias mãos!

[[v24-1-17]]

^<<v24-1-17,17>>^ "Levante-se e prepare-se para agir; diga-lhes tudo que eu ordenar. Não tenha medo deles, senão o farei parecer medroso diante deles.

[[v24-1-18]]

^<<v24-1-18,18>>^ Pois hoje eu o fortaleci como uma cidade fortificada, como uma coluna de ferro ou um muro de bronze. Você enfrentará toda esta terra: os reis, os oficiais, os sacerdotes e o povo de Judá.

[[v24-1-19]]

^<<v24-1-19,19>>^ Eles lutarão contra você, mas não vencerão, pois estou com você e o protegerei. Eu, o SENHOR, falei!".

'''

xref:023-isaias/023-isaias-066.adoc#v23-66-0[&#60; Capítulo Anterior] | <<v24-1-0,Topo>> | xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[Próximo Capítulo &#62;]