include::./index.adoc[]

[[v24-23-0]]
=== Jeremias, 23
// nvt ?, NVT - Nova Versão Transformadora

[[v24-23-1]]

^<<v24-23-1,1>>^ "Que aflição espera os pastores de minhas ovelhas, pois destruíram e dispersaram aqueles de quem deviam cuidar", diz o SENHOR.

[[v24-23-2]]

^<<v24-23-2,2>>^ Portanto, assim diz o SENHOR, o Deus de Israel, a esses líderes do povo: "Em vez de cuidarem do meu rebanho e o conduzirem em segurança, vocês o abandonaram e o levaram à destruição. Agora, eu os castigarei pelo mal que fizeram.

[[v24-23-3]]

^<<v24-23-3,3>>^ Contudo, reunirei o remanescente do meu rebanho das terras para onde os expulsei. Eu os trarei de volta para seu curral, e eles serão férteis e se multiplicarão.

[[v24-23-4]]

^<<v24-23-4,4>>^ Em seguida, nomearei bons pastores que cuidarão dessas ovelhas. Elas nunca mais terão medo, e nenhuma delas se perderá. Eu, o SENHOR, falei!

[[v24-23-5]]

^<<v24-23-5,5>>^ "Pois está chegando o dia", diz o SENHOR, "em que levantarei um Renovo, um descendente justo, da linhagem do rei Davi. Ele reinará com sabedoria e fará o que é justo e certo em toda a terra.

[[v24-23-6]]

^<<v24-23-6,6>>^ E este será seu nome: ‘O SENHOR é nossa justiça’. Nesse dia, Judá será salvo, e Israel viverá em segurança.

[[v24-23-7]]

^<<v24-23-7,7>>^ "Está chegando o dia", diz o SENHOR, "em que as pessoas que fizerem um juramento não dirão: ‘Tão certo como vive o SENHOR, que tirou o povo de Israel da terra do Egito’.

[[v24-23-8]]

^<<v24-23-8,8>>^ Em vez disso, dirão: ‘Tão certo como vive o SENHOR, que trouxe o povo de Israel de volta da terra do norte e de todas as nações onde os havia exilado’. Então viverão em sua própria terra."

[[v24-23-9]]

^<<v24-23-9,9>>^ Meu coração está quebrantado por causa dos falsos profetas, e todos os meus ossos tremem. Cambaleio como um bêbado, como alguém vencido pelo vinho, por causa das santas palavras que o SENHOR pronunciou contra eles.

[[v24-23-10]]

^<<v24-23-10,10>>^ Pois a terra está cheia de adultério e debaixo de maldição. A terra está de luto; os pastos do deserto secaram. Pois todos praticam o mal e abusam do poder.

[[v24-23-11]]

^<<v24-23-11,11>>^ "Até os sacerdotes e profetas são homens corrompidos. Vi seus atos desprezíveis aqui mesmo, em meu templo", diz o SENHOR.

[[v24-23-12]]

^<<v24-23-12,12>>^ "Portanto, os caminhos deles se tornarão escorregadios. Serão perseguidos na escuridão, e ali cairão. Pois trarei calamidade sobre eles no tempo determinado para seu castigo. Eu, o SENHOR, falei!

[[v24-23-13]]

^<<v24-23-13,13>>^ "Vi que os profetas de Samaria eram terríveis, pois profetizavam em nome de Baal e faziam Israel, meu povo, pecar.

[[v24-23-14]]

^<<v24-23-14,14>>^ Agora, porém, vejo que os profetas de Jerusalém são ainda piores; cometem adultério, gostam da desonestidade e incentivam quem pratica o mal, para que ninguém se arrependa de sua maldade. Esses profetas são tão perversos quanto os habitantes de Sodoma e Gomorra."

[[v24-23-15]]

^<<v24-23-15,15>>^ Portanto, assim diz o SENHOR dos Exércitos acerca dos profetas: "Eu os alimentarei com amargura e lhes darei veneno para beber, pois foi por causa dos profetas de Jerusalém que a perversidade encheu esta terra".

[[v24-23-16]]

^<<v24-23-16,16>>^ Assim diz o SENHOR dos Exércitos a seu povo: "Não deem ouvidos a esses profetas quando profetizam para vocês e os enchem de falsas esperanças. Eles inventam tudo que dizem; não falam da parte do SENHOR.

[[v24-23-17]]

^<<v24-23-17,17>>^ Vivem repetindo aos que desprezam minha palavra: ‘O SENHOR diz que terão paz!’. E aos que seguem os desejos teimosos de seu coração, dizem: ‘Nada de mal lhes acontecerá!’.

[[v24-23-18]]

^<<v24-23-18,18>>^ "Acaso algum desses profetas esteve na presença do Senhor para ouvir suas palavras? Algum deles prestou atenção e obedeceu?

[[v24-23-19]]

^<<v24-23-19,19>>^ Vejam, a ira do SENHOR irrompe como uma tempestade, um vendaval sobre a cabeça dos perversos!

[[v24-23-20]]

^<<v24-23-20,20>>^ A ira do SENHOR não passará até que ele cumpra tudo que planejou. Em dias futuros, vocês entenderão tudo isso claramente.

[[v24-23-21]]

^<<v24-23-21,21>>^ "Não enviei esses profetas, mas eles correm de um lado para o outro. Não lhes dei mensagem alguma, e ainda assim continuam a profetizar.

[[v24-23-22]]

^<<v24-23-22,22>>^ Se houvessem estado diante de mim e me ouvido, teriam anunciado minhas palavras e levado meu povo a se arrepender de seus maus caminhos e suas más ações.

[[v24-23-23]]

^<<v24-23-23,23>>^ Acaso sou Deus apenas de perto?", diz o SENHOR. "Não sou Deus também de longe?

[[v24-23-24]]

^<<v24-23-24,24>>^ Pode alguém se esconder de mim onde eu não veja? Não estou em toda parte, nos céus e na terra?", diz o SENHOR.

[[v24-23-25]]

^<<v24-23-25,25>>^ "Ouvi esses profetas dizerem: ‘Tive um sonho! Tive um sonho!’ e depois contarem mentiras em meu nome.

[[v24-23-26]]

^<<v24-23-26,26>>^ Até quando isso continuará? Se são profetas, são profetas do engano e inventam tudo que dizem.

[[v24-23-27]]

^<<v24-23-27,27>>^ Relatando esses sonhos falsos, procuram fazer meu povo se esquecer de mim, como seus antepassados se esqueceram de mim ao adorar os ídolos de Baal.

[[v24-23-28]]

^<<v24-23-28,28>>^ "Que esses falsos profetas relatem seus sonhos, mas que meus verdadeiros mensageiros proclamem fielmente todas as minhas palavras; há diferença entre palha e trigo!

[[v24-23-29]]

^<<v24-23-29,29>>^ Acaso minha palavra não arde como fogo?", diz o SENHOR. "Não é como martelo que despedaça a rocha?

[[v24-23-30]]

^<<v24-23-30,30>>^ "Portanto", diz o SENHOR, "sou contra esses profetas que roubam palavras uns dos outros e afirmam que as receberam de mim.

[[v24-23-31]]

^<<v24-23-31,31>>^ Sou contra esses profetas cheios de lábia que dizem: ‘Esta profecia é do SENHOR!’.

[[v24-23-32]]

^<<v24-23-32,32>>^ Sou contra esses falsos profetas. Seus sonhos imaginários são mentiras descaradas que fazem meu povo pecar. Não os enviei nem os nomeei, e eles não têm nada a dizer a este povo. Eu, o SENHOR, falei!"

[[v24-23-33]]

^<<v24-23-33,33>>^ "Se alguém do povo, ou algum dos profetas ou dos sacerdotes lhe perguntar: ‘Que palavras pesadas o SENHOR lhe deu para anunciar hoje?’, responda: ‘Vocês são o peso! O SENHOR diz que os abandonará!’.

[[v24-23-34]]

^<<v24-23-34,34>>^ "Se algum profeta, sacerdote ou qualquer outra pessoa disser: ‘Tenho uma profecia do SENHOR’, castigarei essa pessoa e toda a sua família.

[[v24-23-35]]

^<<v24-23-35,35>>^ Perguntem uns aos outros: ‘Qual é a resposta do SENHOR?’, ou ‘O que o SENHOR diz?’.

[[v24-23-36]]

^<<v24-23-36,36>>^ Mas parem de usar a expressão ‘profecia do SENHOR’. Pois alguns a usam para conferir autoridade às próprias ideias e distorcem as palavras de nosso Deus, o Deus vivo, o SENHOR dos Exércitos.

[[v24-23-37]]

^<<v24-23-37,37>>^ "Isto é o que você dirá aos profetas: ‘Qual é a resposta do SENHOR?’, ou ‘O que o SENHOR diz?’.

[[v24-23-38]]

^<<v24-23-38,38>>^ Mas, se responderem: ‘Esta é uma profecia do SENHOR!’, você deve dizer: ‘Assim diz o SENHOR: Porque usaram a expressão ‘profecia do SENHOR’, embora eu os tenha advertido de que não a usassem,

[[v24-23-39]]

^<<v24-23-39,39>>^ eu me esquecerei completamente de vocês. Sim, os expulsarei de minha presença, junto com esta cidade que dei a vocês e a seus antepassados.

[[v24-23-40]]

^<<v24-23-40,40>>^ Farei de vocês objeto de ridículo, e seu nome será infame para sempre’."

'''

xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[Próximo Capítulo &#62;]