include::./index.adoc[]

[[v24-8-0]]
=== Jeremias, 8
// nvt ?, NVT - Nova Versão Transformadora

[[v24-8-1]]

^<<v24-8-1,1>>^ "Naquele tempo", diz o SENHOR, "os inimigos abrirão as sepulturas dos reis e dos oficiais de Judá, e os túmulos dos sacerdotes, dos profetas e dos habitantes de Jerusalém.

[[v24-8-2]]

^<<v24-8-2,2>>^ Espalharão os ossos no chão, diante do sol, da lua e das estrelas, os deuses que meu povo amou, serviu, seguiu, buscou e adorou. Seus ossos não serão recolhidos nem sepultados outra vez, mas ficarão espalhados no chão como esterco.

[[v24-8-3]]

^<<v24-8-3,3>>^ E o povo que sobreviver dessa nação perversa preferirá a morte a viver nos lugares para onde os enviarei. Eu, o SENHOR dos Exércitos, falei!"

[[v24-8-4]]

^<<v24-8-4,4>>^ "Jeremias, diga ao povo: ‘Assim diz o SENHOR: "‘Quando uma pessoa cai, não volta a se levantar? Quando descobre que está no caminho errado, não dá meia-volta?

[[v24-8-5]]

^<<v24-8-5,5>>^ Então por que este povo de Jerusalém continua em seu caminho e se recusa a voltar? Apegam-se firmemente a suas mentiras e não querem retornar.

[[v24-8-6]]

^<<v24-8-6,6>>^ Escuto suas conversas e não ouço uma só palavra verdadeira. Acaso alguém está arrependido de sua maldade? Alguém diz: ‘Que coisa terrível eu fiz’? Não! Todos correm pelo caminho do pecado, velozes como cavalos galopando para a batalha.

[[v24-8-7]]

^<<v24-8-7,7>>^ Até a cegonha que voa pelos céus sabe a época de migrar, assim como a rolinha, a andorinha e o grou; todos voltam no tempo certo a cada ano. Meu povo, contudo, não conhece os decretos do SENHOR.

[[v24-8-8]]

^<<v24-8-8,8>>^ "‘Como podem dizer: ‘Somos sábios, pois temos a lei do SENHOR’, se seus mestres a distorcem escrevendo mentiras?

[[v24-8-9]]

^<<v24-8-9,9>>^ Esses mestres sábios serão envergonhados e cairão na armadilha de sua insensatez, pois rejeitaram a palavra do SENHOR; afinal, será que são mesmo tão sábios?

[[v24-8-10]]

^<<v24-8-10,10>>^ Entregarei suas esposas a outros e darei seus campos a estranhos. Desde o mais humilde até o mais importante, sua vida é dominada pela ganância. Até meus profetas e sacerdotes agem desse modo; são todos impostores.

[[v24-8-11]]

^<<v24-8-11,11>>^ Oferecem curativos superficiais para a ferida mortal do meu povo. Dão garantias de paz, quando não há paz alguma.

[[v24-8-12]]

^<<v24-8-12,12>>^ Acaso se envergonham de sua conduta detestável? De maneira nenhuma! Nem sabem o que é vergonha! Portanto, estarão entre os que caírem no massacre; ficarão arruinados quando eu os castigar, diz o SENHOR.

[[v24-8-13]]

^<<v24-8-13,13>>^ Certamente os consumirei; não haverá mais colheita de figos nem de uvas. Suas árvores frutíferas morrerão, tudo que lhes dei em breve acabará. Eu, o SENHOR, falei!’.

[[v24-8-14]]

^<<v24-8-14,14>>^ "Então o povo dirá: ‘Por que devemos ficar parados esperando? Venham, vamos para as cidades fortificadas e morramos ali! Pois o SENHOR, nosso Deus, decretou nossa destruição e nos deu um cálice de veneno para beber, pois pecamos contra o SENHOR.

[[v24-8-15]]

^<<v24-8-15,15>>^ Esperávamos paz, mas ela não veio; esperávamos tempo de cura, mas só encontramos terror’.

[[v24-8-16]]

^<<v24-8-16,16>>^ "Desde a terra de Dã, ao norte, pode-se ouvir o bufar dos cavalos de guerra dos inimigos. O relinchar de seus garanhões faz a terra tremer; vêm para devorar a terra e tudo que nela há, tanto as cidades como seus habitantes.

[[v24-8-17]]

^<<v24-8-17,17>>^ Enviarei essas tropas inimigas entre vocês, serpentes venenosas que ninguém consegue encantar; elas os morderão, e vocês morrerão. Eu, o SENHOR, falei!"

[[v24-8-18]]

^<<v24-8-18,18>>^ Minha tristeza não tem cura; meu coração está enfermo.

[[v24-8-19]]

^<<v24-8-19,19>>^ Escutem o choro do meu povo, pode-se ouvi-lo por toda a terra: "Acaso o SENHOR abandonou Sião? Seu rei não está mais ali?". "Por que provocaram minha ira com ídolos esculpidos e seus inúteis deuses estrangeiros?", diz o SENHOR.

[[v24-8-20]]

^<<v24-8-20,20>>^ O povo se lamenta: "A colheita chegou ao fim, o verão acabou, e, no entanto, não estamos salvos!".

[[v24-8-21]]

^<<v24-8-21,21>>^ Sofro com a dor do meu povo, lamento e sou tomado de tristeza.

[[v24-8-22]]

^<<v24-8-22,22>>^ Não há remédio em Gileade? Não há médico ali? Por que não há cura para as feridas do meu povo?

'''

xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[&#60; Capítulo Anterior] | <<v24-8-0,Topo>> | xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[Próximo Capítulo &#62;]