include::./index.adoc[]

[[v24-50-0]]
=== Jeremias, 50
// nvt ?, NVT - Nova Versão Transformadora

[[v24-50-1]]

^<<v24-50-1,1>>^ O SENHOR deu ao profeta Jeremias esta mensagem acerca da Babilônia e da terra dos babilônios:

[[v24-50-2]]

^<<v24-50-2,2>>^ "Anunciem a todo o mundo, não escondam nada. Levantem uma bandeira para proclamar a todos que a Babilônia cairá. Suas imagens e seus ídolos serão despedaçados; seus deuses, Bel e Merodaque, sofrerão completa humilhação.

[[v24-50-3]]

^<<v24-50-3,3>>^ Porque do norte uma nação virá e trará tamanha destruição que ninguém voltará a habitar ali. Tudo desaparecerá; tanto pessoas como animais fugirão."

[[v24-50-4]]

^<<v24-50-4,4>>^ "Naqueles dias e naquele tempo", diz o SENHOR, "o povo de Israel voltará com o povo de Judá. Virão chorando e buscando o SENHOR, seu Deus.

[[v24-50-5]]

^<<v24-50-5,5>>^ Perguntarão pelo caminho para Sião e voltarão para casa. Eles se apegarão ao Senhor numa aliança permanente que jamais será esquecida.

[[v24-50-6]]

^<<v24-50-6,6>>^ "Meu povo tem sido como ovelhas perdidas; seus pastores as fizeram desviar do caminho e as soltaram nos montes. Elas perderam o rumo e não lembram como voltar para o curral.

[[v24-50-7]]

^<<v24-50-7,7>>^ Todos que as encontraram as devoraram. Seus inimigos disseram: ‘Não fizemos nada de errado ao atacá-las, pois pecaram contra o SENHOR, seu verdadeiro lugar de descanso, a esperança de seus antepassados’.

[[v24-50-8]]

^<<v24-50-8,8>>^ "Agora, porém, fujam da Babilônia! Saiam da terra dos babilônios! Como bodes que vão adiante do rebanho, guiem meu povo de volta para casa.

[[v24-50-9]]

^<<v24-50-9,9>>^ Pois estou levantando um exército de grandes nações do norte. Unirão forças para atacar a Babilônia e a conquistarão. As flechas do inimigo serão certeiras; irão direto para o alvo!

[[v24-50-10]]

^<<v24-50-10,10>>^ A Babilônia será saqueada até que os saqueadores estejam cheios de despojos. Eu, o SENHOR, falei!"

[[v24-50-11]]

^<<v24-50-11,11>>^ "Vocês se alegram e exultam, vocês que saquearam a nação que me pertence. Saltam como bezerros na campina e relincham como garanhões.

[[v24-50-12]]

^<<v24-50-12,12>>^ Mas sua terra natal será coberta de vergonha e desonra. Vocês se tornarão a menor das nações, um deserto, uma terra seca e desolada.

[[v24-50-13]]

^<<v24-50-13,13>>^ Por causa da fúria do SENHOR, a Babilônia ficará vazia; ninguém viverá nela. Todos que passarem por lá ficarão pasmos e abrirão a boca de espanto quando virem suas ruínas.

[[v24-50-14]]

^<<v24-50-14,14>>^ "Todas vocês, nações vizinhas, preparem-se para atacar a Babilônia. Que seus arqueiros atirem contra ela e não poupem flechas, pois ela pecou contra o SENHOR.

[[v24-50-15]]

^<<v24-50-15,15>>^ De todos os lados, deem gritos de guerra contra ela. Vejam, está se rendendo! Seus muros caíram! É a vingança do SENHOR, portanto vinguem-se dela; façam a ela o mesmo que ela fez a outros!

[[v24-50-16]]

^<<v24-50-16,16>>^ Eliminem da Babilônia todos que plantam lavouras e mandem embora todos que colhem. Por causa da espada do inimigo, todos fugirão para sua própria terra."

[[v24-50-17]]

^<<v24-50-17,17>>^ "Os israelitas são como ovelhas dispersadas por leões. Primeiro o rei da Assíria os devorou, depois Nabucodonosor, rei da Babilônia, quebrou seus ossos."

[[v24-50-18]]

^<<v24-50-18,18>>^ Portanto, assim diz o SENHOR dos Exércitos, o Deus de Israel: "Castigarei o rei da Babilônia e sua terra, assim como castiguei o rei da Assíria.

[[v24-50-19]]

^<<v24-50-19,19>>^ Trarei Israel de volta para sua própria terra, para pastar nos campos no Carmelo e em Basã e para saciar-se novamente na região montanhosa de Efraim e em Gileade.

[[v24-50-20]]

^<<v24-50-20,20>>^ Naqueles dias", diz o SENHOR, "não se encontrará pecado algum em Israel nem em Judá, pois perdoarei o remanescente que eu preservar."

[[v24-50-21]]

^<<v24-50-21,21>>^ "Subam, guerreiros, contra a terra de Merataim e contra os habitantes de Pecode! Persigam-nos, matem-nos e destruam-nos completamente, como lhes ordenei", diz o SENHOR.

[[v24-50-22]]

^<<v24-50-22,22>>^ "Façam ouvir na terra o grito de guerra, o estrondo de grande destruição.

[[v24-50-23]]

^<<v24-50-23,23>>^ A Babilônia, o martelo de toda a terra, está quebrada e despedaçada; está desolada entre as nações.

[[v24-50-24]]

^<<v24-50-24,24>>^ Preparei uma armadilha para você, Babilônia; foi surpreendida e apanhada, pois lutou contra o SENHOR.

[[v24-50-25]]

^<<v24-50-25,25>>^ O SENHOR abriu seu arsenal e trouxe para fora as armas de sua fúria. Sim, o Soberano SENHOR dos Exércitos, agirá na terra dos babilônios.

[[v24-50-26]]

^<<v24-50-26,26>>^ Venham contra ela de terras distantes, arrombem seus celeiros, transformem seus muros e casas em montes de escombros. Destruam-na completamente, não deixem sobrar coisa alguma.

[[v24-50-27]]

^<<v24-50-27,27>>^ Ataquem todos os seus jovens guerreiros e acabem com eles. Que aflição os espera, pois chegou o dia do castigo da Babilônia!

[[v24-50-28]]

^<<v24-50-28,28>>^ Escutem o povo que escapou da Babilônia contar em Sião como o SENHOR, nosso Deus, se vingou dos que destruíram seu templo.

[[v24-50-29]]

^<<v24-50-29,29>>^ "Convoquem os arqueiros para virem à Babilônia, cerquem a cidade para que ninguém escape. Façam a ela o mesmo que ela fez a outros, pois desafiou o SENHOR, o Santo de Israel.

[[v24-50-30]]

^<<v24-50-30,30>>^ Seus jovens cairão nas ruas, todos os seus soldados serão mortos", diz o SENHOR.

[[v24-50-31]]

^<<v24-50-31,31>>^ "Veja, sou seu inimigo, povo arrogante", diz o Soberano SENHOR dos Exércitos. "O dia do acerto de contas chegou, o dia em que eu o castigarei.

[[v24-50-32]]

^<<v24-50-32,32>>^ Ó povo insolente, você tropeçará e cairá, e ninguém o levantará. Pois acendi um fogo nas cidades da Babilônia que queimará tudo ao seu redor."

[[v24-50-33]]

^<<v24-50-33,33>>^ Assim diz o SENHOR dos Exércitos: "O povo de Israel e o povo de Judá foram oprimidos; seus captores os prenderam e não querem soltá-los.

[[v24-50-34]]

^<<v24-50-34,34>>^ Mas seu Redentor é forte; seu nome é SENHOR dos Exércitos. Ele os defenderá e voltará a lhes dar descanso em Israel. Mas para o povo da Babilônia não haverá descanso!

[[v24-50-35]]

^<<v24-50-35,35>>^ "A espada de guerra virá sobre os babilônios", diz o SENHOR. "Virá sobre o povo da Babilônia, sobre seus oficiais e seus sábios.

[[v24-50-36]]

^<<v24-50-36,36>>^ A espada virá sobre seus falsos profetas, e eles se tornarão tolos. Virá sobre seus guerreiros valentes, e eles se apavorarão.

[[v24-50-37]]

^<<v24-50-37,37>>^ A espada virá sobre cavalos e carros de guerra e sobre os estrangeiros que ali habitam, e eles se tornarão como mulheres. Virá sobre seus tesouros, e todos eles serão saqueados.

[[v24-50-38]]

^<<v24-50-38,38>>^ A seca virá até mesmo sobre suas fontes de água, e elas secarão. Por que tudo isso acontecerá? Porque toda a terra se encheu de ídolos, e o povo está enlouquecido por eles.

[[v24-50-39]]

^<<v24-50-39,39>>^ "Em breve a Babilônia servirá de morada para animais do deserto e hienas; corujas farão ali seus ninhos. Jamais voltará a ser habitada, ficará desolada para sempre.

[[v24-50-40]]

^<<v24-50-40,40>>^ Eu a destruirei como destruí Sodoma e Gomorra e as cidades vizinhas", diz o SENHOR. "Ninguém viverá ali, ninguém habitará nela.

[[v24-50-41]]

^<<v24-50-41,41>>^ "Vejam, um grande exército vem do norte! Uma grande nação e muitos reis se levantam, de terras distantes, contra vocês.

[[v24-50-42]]

^<<v24-50-42,42>>^ Estão armados com arcos e lanças, são cruéis e não têm compaixão. Quando avançam montados em cavalos, o barulho é como o rugido do mar. Vêm em formação de batalha com o intuito de destruí-la, Babilônia.

[[v24-50-43]]

^<<v24-50-43,43>>^ O rei da Babilônia ouviu relatos sobre o inimigo, e suas mãos tremem de medo. Pontadas de angústia tomam conta dele, como as dores da mulher em trabalho de parto.

[[v24-50-44]]

^<<v24-50-44,44>>^ "Virei como um leão da mata do Jordão que ataca as ovelhas no pasto. Expulsarei a Babilônia de sua terra e ali colocarei o líder que eu escolher. Pois quem é semelhante a mim e quem pode me desafiar? Que governante pode se opor à minha vontade?"

[[v24-50-45]]

^<<v24-50-45,45>>^ Ouçam o que o SENHOR planejou contra a Babilônia e contra a terra dos babilônios. Até as crianças serão arrastadas como ovelhas, e suas casas, destruídas.

[[v24-50-46]]

^<<v24-50-46,46>>^ A terra tremerá com a queda da Babilônia, e por todo o mundo se ouvirá seu grito de desespero.

'''

xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[&#60; Capítulo Anterior] | <<v24-50-0,Topo>> | xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[Próximo Capítulo &#62;]