include::./index.adoc[]

[[v24-7-0]]
=== Jeremias, 7
// nvt ?, NVT - Nova Versão Transformadora

[[v24-7-1]]

^<<v24-7-1,1>>^ O SENHOR deu outra mensagem a Jeremias:

[[v24-7-2]]

^<<v24-7-2,2>>^ "Vá à entrada do templo do SENHOR e proclame esta mensagem ao povo: ‘Ó Judá, ouça esta mensagem do SENHOR! Escutem, todos vocês que adoram neste lugar!

[[v24-7-3]]

^<<v24-7-3,3>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: "‘Se vocês abandonarem seus maus caminhos, deixarei que fiquem em sua própria terra.

[[v24-7-4]]

^<<v24-7-4,4>>^ Não se deixem enganar por aqueles que lhes fazem falsas promessas e repetem: ‘O templo do SENHOR está aqui! O templo do SENHOR está aqui!’.

[[v24-7-5]]

^<<v24-7-5,5>>^ Contudo, só serei misericordioso se vocês abandonarem seus pensamentos e atos perversos e começarem a tratar uns aos outros com justiça,

[[v24-7-6]]

^<<v24-7-6,6>>^ se pararem de explorar os estrangeiros, os órfãos e as viúvas, se pararem de cometer homicídio e se deixarem de prejudicar a si mesmos ao adorar outros deuses.

[[v24-7-7]]

^<<v24-7-7,7>>^ Então permitirei que fiquem nesta terra que há muito tempo dei a seus antepassados para sempre.

[[v24-7-8]]

^<<v24-7-8,8>>^ "‘Não se deixem enganar por falsas promessas e conversas inúteis.

[[v24-7-9]]

^<<v24-7-9,9>>^ Acreditam mesmo que podem roubar, matar, cometer adultério, mentir e queimar incenso para Baal e para todos os seus outros novos deuses

[[v24-7-10]]

^<<v24-7-10,10>>^ e depois vir aqui, se apresentar diante de mim em meu templo e dizer: ‘Estamos seguros!’, para depois voltar a praticar todas essas coisas detestáveis?

[[v24-7-11]]

^<<v24-7-11,11>>^ Vocês mesmos não reconhecem que este templo, que leva meu nome, se transformou em esconderijo de ladrões? Certamente vejo todo o mal que acontece nele. Eu, o SENHOR, falei!

[[v24-7-12]]

^<<v24-7-12,12>>^ "‘Agora, vão a Siló, o primeiro lugar onde coloquei a tenda que levava meu nome. Vejam o que fiz ali por causa da perversidade do meu povo, os israelitas.

[[v24-7-13]]

^<<v24-7-13,13>>^ Enquanto vocês praticavam essas maldades, diz o SENHOR, eu lhes falei repetidamente, mas vocês não quiseram ouvir. Eu os chamei, mas vocês se recusaram a responder.

[[v24-7-14]]

^<<v24-7-14,14>>^ Portanto, assim como destruí Siló, agora destruirei este templo que leva meu nome, este templo no qual vocês confiam, este lugar que dei a vocês e a seus antepassados.

[[v24-7-15]]

^<<v24-7-15,15>>^ Expulsarei vocês de minha presença e os enviarei para longe, como fiz com seus parentes, o povo de Israel’."

[[v24-7-16]]

^<<v24-7-16,16>>^ "Jeremias, não interceda mais por este povo. Não chore nem faça orações por eles, e não suplique para que eu os ajude, pois não o ouvirei.

[[v24-7-17]]

^<<v24-7-17,17>>^ Não vê o que fazem nas cidades de Judá e nas ruas de Jerusalém?

[[v24-7-18]]

^<<v24-7-18,18>>^ Veja como as crianças juntam lenha e os pais acendem fogo para os sacrifícios. Veja como as mulheres preparam a massa e fazem bolos para a Rainha dos Céus. Além disso, apresentam ofertas derramadas para outros deuses. Tenho razão para estar tão irado!

[[v24-7-19]]

^<<v24-7-19,19>>^ Acaso é a mim que eles prejudicam?", pergunta o SENHOR. "Na verdade, prejudicam a si mesmos, para sua própria vergonha."

[[v24-7-20]]

^<<v24-7-20,20>>^ Portanto, assim diz o SENHOR Soberano: "Derramarei minha ira ardente sobre este lugar. Seus habitantes, seus animais, suas árvores e suas colheitas serão consumidos pelo fogo de minha ira, que ninguém pode apagar".

[[v24-7-21]]

^<<v24-7-21,21>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: "Peguem seus holocaustos e demais sacrifícios e comam a carne vocês mesmos!

[[v24-7-22]]

^<<v24-7-22,22>>^ Quando tirei seus antepassados do Egito, não eram ofertas e holocaustos que eu queria deles.

[[v24-7-23]]

^<<v24-7-23,23>>^ Esta foi minha ordem: ‘Obedeçam ao que digo, e eu serei o seu Deus, e vocês serão o meu povo. Façam o que ordeno, e tudo lhes irá bem’.

[[v24-7-24]]

^<<v24-7-24,24>>^ "Meu povo, porém, não me deu ouvidos. Continuaram a fazer o que bem queriam e a seguir os desejos teimosos de seu coração perverso. Andaram para trás em vez de avançar.

[[v24-7-25]]

^<<v24-7-25,25>>^ Desde o dia em que seus antepassados saíram do Egito até agora, continuo a enviar meus servos, os profetas, dia após dia.

[[v24-7-26]]

^<<v24-7-26,26>>^ Meu povo, porém, não me deu ouvidos. Foram ainda mais teimosos e desobedientes que seus antepassados.

[[v24-7-27]]

^<<v24-7-27,27>>^ "Diga-lhes tudo isso, mas eles não escutarão. Anuncie estas advertências, mas eles não responderão.

[[v24-7-28]]

^<<v24-7-28,28>>^ Diga-lhes: ‘Esta é a nação que não obedece ao SENHOR, seu Deus, e não quer ser ensinada. A verdade já não existe no meio deles; desapareceu de seus lábios.

[[v24-7-29]]

^<<v24-7-29,29>>^ Raspem a cabeça em sinal de luto e chorem nos montes. Pois o SENHOR rejeitou e abandonou esta geração que provocou sua ira’."

[[v24-7-30]]

^<<v24-7-30,30>>^ "O povo de Judá pecou diante dos meus olhos", diz o SENHOR. "Colocaram ídolos detestáveis no templo que leva meu nome e o contaminaram.

[[v24-7-31]]

^<<v24-7-31,31>>^ Construíram santuários idólatras em Tofete, no vale de Ben-Hinom, e ali sacrificaram seus filhos e filhas no fogo. Jamais ordenei tamanha maldade; nunca me passou pela mente!

[[v24-7-32]]

^<<v24-7-32,32>>^ Portanto, tenham cuidado", diz o SENHOR, "pois está chegando o dia em que não se chamará mais Tofete, nem vale de Ben-Hinom, mas vale da Matança. Sepultarão corpos em Tofete até não haver mais lugar.

[[v24-7-33]]

^<<v24-7-33,33>>^ Os cadáveres deste povo servirão de alimento para os abutres e os animais selvagens, e não restará ninguém para espantá-los.

[[v24-7-34]]

^<<v24-7-34,34>>^ Acabarei com os cânticos alegres e com o riso nas ruas de Jerusalém, e já não se ouvirão as vozes felizes de noivos e de noivas nas cidades de Judá. A terra ficará inteiramente desolada."

'''

xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[&#60; Capítulo Anterior] | <<v24-7-0,Topo>> | xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[Próximo Capítulo &#62;]