include::./index.adoc[]

[[v24-20-0]]
=== Jeremias, 20
// nvt ?, NVT - Nova Versão Transformadora

[[v24-20-1]]

^<<v24-20-1,1>>^ Pasur, filho de Imer, sacerdote encarregado do templo do SENHOR, ouviu o que Jeremias profetizava.

[[v24-20-2]]

^<<v24-20-2,2>>^ Mandou prender o profeta Jeremias e ordenou que o açoitassem e o pusessem no tronco junto à porta de Benjamim, no templo do SENHOR.

[[v24-20-3]]

^<<v24-20-3,3>>^ No dia seguinte, Pasur o soltou, e Jeremias disse: "Pasur, o SENHOR mudou seu nome. De agora em diante, você será chamado de ‘Homem que Vive em Terror’.

[[v24-20-4]]

^<<v24-20-4,4>>^ Pois assim diz o SENHOR: ‘Enviarei terror sobre você e sobre todos os seus amigos, e você verá quando forem mortos pelas espadas do inimigo. Entregarei o povo de Judá ao rei da Babilônia, e ele os levará presos para a Babilônia ou os atravessará com a espada.

[[v24-20-5]]

^<<v24-20-5,5>>^ Entregarei Jerusalém nas mãos de seus inimigos, e eles saquearão todos os tesouros da cidade — as pedras preciosas, o ouro e a prata de seus reis — e levarão para a Babilônia.

[[v24-20-6]]

^<<v24-20-6,6>>^ Você, Pasur, e todos em sua casa serão levados para o exílio na Babilônia. Ali morrerão e serão sepultados, você e todos os seus amigos a quem você profetizou mentiras’".

[[v24-20-7]]

^<<v24-20-7,7>>^ Ó SENHOR, tu me constrangeste, e eu me deixei constranger. És mais forte que eu e prevaleceste. Agora, sou motivo de zombaria todos os dias; todos riem de mim.

[[v24-20-8]]

^<<v24-20-8,8>>^ Pois, sempre que abro a boca, é para gritar: "Violência e destruição!". Essas mensagens do Senhor me transformaram em alvo constante de piadas.

[[v24-20-9]]

^<<v24-20-9,9>>^ Mas, se digo que nunca mais mencionarei o SENHOR, nem falarei em seu nome, sua palavra arde como fogo em meu coração; é como fogo em meus ossos. Estou cansado de tentar contê-la; é impossível!

[[v24-20-10]]

^<<v24-20-10,10>>^ Ouvi muitos boatos a meu respeito; me chamam de "Homem que Vive em Terror" e me ameaçam: "Se disser alguma coisa, o denunciaremos". Até os que se dizem amigos íntimos me vigiam e esperam que eu cometa algum erro fatal. Dizem: "Ele cairá em sua própria armadilha; então nos vingaremos dele".

[[v24-20-11]]

^<<v24-20-11,11>>^ O SENHOR, porém, está ao meu lado como poderoso guerreiro. Diante dele meus perseguidores tropeçarão; não conseguirão me derrotar. Fracassarão e serão totalmente humilhados; sua desonra jamais será esquecida.

[[v24-20-12]]

^<<v24-20-12,12>>^ Ó SENHOR dos Exércitos, tu provas o justo e examinas pensamentos e emoções. Permite que eu veja tua vingança contra eles, pois coloquei minha causa em tuas mãos.

[[v24-20-13]]

^<<v24-20-13,13>>^ Cantem ao SENHOR! Louvem o SENHOR! Pois ele salva o pobre e necessitado da mão de seus opressores.

[[v24-20-14]]

^<<v24-20-14,14>>^ E, no entanto, amaldiçoo o dia em que nasci; ninguém celebre o dia em que minha mãe me deu à luz.

[[v24-20-15]]

^<<v24-20-15,15>>^ Maldito o mensageiro que disse a meu pai: "Tenho boas notícias! Alegre-se, seu filho nasceu!".

[[v24-20-16]]

^<<v24-20-16,16>>^ Que ele seja destruído como as cidades antigas que o SENHOR arrasou sem compaixão. Que seja aterrorizado todo o dia com gritos de guerra,

[[v24-20-17]]

^<<v24-20-17,17>>^ pois não me matou quando nasci. Quem dera eu tivesse morrido no ventre de minha mãe e seu corpo tivesse sido minha sepultura!

[[v24-20-18]]

^<<v24-20-18,18>>^ Por que eu nasci? Toda a minha vida é apenas sofrimento, tristeza e vergonha.

'''

xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[&#60; Capítulo Anterior] | <<v24-20-0,Topo>> | xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[Próximo Capítulo &#62;]