include::./index.adoc[]

[[v24-4-0]]
=== Jeremias, 4
// nvt ?, NVT - Nova Versão Transformadora

[[v24-4-1]]

^<<v24-4-1,1>>^ "Ó Israel", diz o SENHOR, "se quisesse, poderia voltar para mim. Poderia jogar fora seus ídolos detestáveis e nunca mais se desviar.

[[v24-4-2]]

^<<v24-4-2,2>>^ Quando jurasse por meu nome e dissesse: ‘Tão certo como vive o SENHOR’, poderia fazê-lo em verdade, justiça e retidão. Então você seria uma bênção para as nações do mundo, e todos os povos viriam e louvariam meu nome."

[[v24-4-3]]

^<<v24-4-3,3>>^ Assim diz o SENHOR ao povo de Judá e de Jerusalém: "Passem o arado na terra endurecida! Não desperdicem sementes entre os espinhos!

[[v24-4-4]]

^<<v24-4-4,4>>^ Ó povo de Judá e habitantes de Jerusalém, removam os obstáculos de seu coração e mudem sua atitude perante o SENHOR. Do contrário, por causa de seus pecados, minha ira arderá como fogo que ninguém pode apagar.

[[v24-4-5]]

^<<v24-4-5,5>>^ "Anunciem em Judá e proclamem em Jerusalém! Mandem tocar a trombeta em toda a terra e avisem: ‘Reúnam-se! Corram para as cidades fortificadas!’.

[[v24-4-6]]

^<<v24-4-6,6>>^ Levantem a bandeira para advertir Sião: ‘Fujam agora mesmo! Não demorem!’. Pois, do norte, trago sobre vocês terrível destruição!".

[[v24-4-7]]

^<<v24-4-7,7>>^ Um leão saiu de seu abrigo, um destruidor de nações. Saiu de sua toca e se encaminha até vocês; ele devastará sua terra. Suas cidades serão arruinadas, e ninguém viverá nelas.

[[v24-4-8]]

^<<v24-4-8,8>>^ Portanto, vistam roupas de luto, chorem e lamentem, pois a ira ardente do Senhor ainda está sobre nós.

[[v24-4-9]]

^<<v24-4-9,9>>^ "Naquele dia", diz o SENHOR, "os reis e os oficiais estremecerão de medo. Os sacerdotes ficarão horrorizados, e os profetas, espantados."

[[v24-4-10]]

^<<v24-4-10,10>>^ Então eu disse: "Ó Soberano SENHOR, o povo foi enganado por aquilo que disseste, pois prometeste paz a Jerusalém, mas a espada está em nossa garganta!".

[[v24-4-11]]

^<<v24-4-11,11>>^ Naquele dia, o SENHOR dirá ao povo de Jerusalém: "Meu povo querido, do deserto sopra um vento abrasador, e não uma brisa suave para separar a palha dos cereais.

[[v24-4-12]]

^<<v24-4-12,12>>^ É uma rajada violenta, que eu enviei; agora pronunciarei sua sentença".

[[v24-4-13]]

^<<v24-4-13,13>>^ Os inimigos avançam sobre nós como nuvens de tempestade; seus carros de guerra são como vendavais, seus cavalos, mais velozes que águias. Que terrível será! Estamos perdidos!

[[v24-4-14]]

^<<v24-4-14,14>>^ Ó Jerusalém, purifique seu coração, para que seja salva. Até quando abrigará pensamentos malignos?

[[v24-4-15]]

^<<v24-4-15,15>>^ Sua destruição foi anunciada desde Dã até a região montanhosa de Efraim.

[[v24-4-16]]

^<<v24-4-16,16>>^ "Avisem as nações ao redor e anunciem a Jerusalém: Os inimigos vêm de uma terra distante e dão gritos de guerra contra as cidades de Judá.

[[v24-4-17]]

^<<v24-4-17,17>>^ Cercam Jerusalém como guardas ao redor de um campo, pois meu povo se rebelou contra mim", diz o SENHOR.

[[v24-4-18]]

^<<v24-4-18,18>>^ "Suas próprias ações trouxeram isso sobre vocês; é um castigo amargo, que atinge o seu coração!"

[[v24-4-19]]

^<<v24-4-19,19>>^ Meu coração, meu coração! Estou me contorcendo de dor! Meu coração bate forte dentro de mim; não consigo me aquietar! Pois ouvi o som das trombetas dos inimigos e o rugido de seus gritos de guerra.

[[v24-4-20]]

^<<v24-4-20,20>>^ Ondas de destruição cobrem a terra, até deixá-la inteiramente desolada. De repente, minhas tendas foram destruídas; meus abrigos foram derrubados num instante.

[[v24-4-21]]

^<<v24-4-21,21>>^ Até quando terei de ver as bandeiras e ouvir o som das trombetas?

[[v24-4-22]]

^<<v24-4-22,22>>^ "Meu povo é tolo e não me conhece", diz o SENHOR. "São crianças sem juízo, que não entendem coisa alguma. São astutos para fazer o mal, mas não têm ideia de como fazer o bem."

[[v24-4-23]]

^<<v24-4-23,23>>^ Olhei para a terra, e ela estava sem forma e vazia; olhei para os céus, e não havia luz alguma.

[[v24-4-24]]

^<<v24-4-24,24>>^ Olhei para os montes e para as colinas, e eles estremeciam e balançavam.

[[v24-4-25]]

^<<v24-4-25,25>>^ Olhei, e todo o povo tinha desaparecido; as aves do céu voaram para longe.

[[v24-4-26]]

^<<v24-4-26,26>>^ Olhei, e os campos férteis haviam se transformado em deserto; as cidades estavam em ruínas, por causa da ira ardente do SENHOR.

[[v24-4-27]]

^<<v24-4-27,27>>^ Assim diz o SENHOR: "Toda a terra será devastada, mas não a destruirei por completo.

[[v24-4-28]]

^<<v24-4-28,28>>^ A terra lamentará e os céus escurecerão, por causa de meu decreto contra meu povo; estou decidido e não voltarei atrás".

[[v24-4-29]]

^<<v24-4-29,29>>^ Ao som de cavaleiros e arqueiros, os habitantes da cidade fogem. Escondem-se entre os arbustos e correm para os montes. Todas as cidades foram abandonadas; não resta uma pessoa sequer!

[[v24-4-30]]

^<<v24-4-30,30>>^ O que você está fazendo, cidade devastada? Por que se veste com belas roupas e põe joias de ouro? Por que pinta os olhos? De nada adiantará enfeitar-se toda! Seus aliados, que eram seus amantes, a desprezam e tentam matá-la.

[[v24-4-31]]

^<<v24-4-31,31>>^ Ouço gritos, como os da mulher em trabalho de parto, gemidos de quem dá à luz o primeiro filho. É a bela Sião, que grita ofegante: "Socorro, estão me matando!".

'''

xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[&#60; Capítulo Anterior] | <<v24-4-0,Topo>> | xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[Próximo Capítulo &#62;]