include::./index.adoc[]

[[v24-25-0]]
=== Jeremias, 25
// nvt ?, NVT - Nova Versão Transformadora

[[v24-25-1]]

^<<v24-25-1,1>>^ Jeremias recebeu do SENHOR esta mensagem para todo o povo de Judá no quarto ano do reinado de Jeoaquim, filho de Josias, rei de Judá. Nesse mesmo ano, Nabucodonosor, rei da Babilônia, começou a reinar.

[[v24-25-2]]

^<<v24-25-2,2>>^ O profeta Jeremias disse a todo o povo de Judá e a todos os habitantes de Jerusalém:

[[v24-25-3]]

^<<v24-25-3,3>>^ "Durante 23 anos, desde o décimo terceiro ano do reinado de Josias, filho de Amom, rei de Judá, até hoje, o SENHOR me tem dado suas mensagens. Eu as anunciei fielmente, mas vocês não ouviram.

[[v24-25-4]]

^<<v24-25-4,4>>^ "Repetidamente, o SENHOR tem enviado seus servos, os profetas, mas vocês não ouviram nem prestaram atenção.

[[v24-25-5]]

^<<v24-25-5,5>>^ Todas as vezes a mensagem foi a mesma: ‘Abandonem seus maus caminhos e suas más ações. Só então habitarão nesta terra que o SENHOR deu a vocês e a seus antepassados para sempre.

[[v24-25-6]]

^<<v24-25-6,6>>^ Não provoquem minha ira ao adorar deuses que vocês fizeram com suas próprias mãos. Então, não lhes farei mal algum’.

[[v24-25-7]]

^<<v24-25-7,7>>^ "Mas vocês não me deram ouvidos", diz o SENHOR. "Provocaram minha ira ao adorar ídolos que vocês fizeram com as próprias mãos e trouxeram calamidades sobre si mesmos.

[[v24-25-8]]

^<<v24-25-8,8>>^ Agora, o SENHOR dos Exércitos diz: Porque não me escutaram,

[[v24-25-9]]

^<<v24-25-9,9>>^ reunirei todos os exércitos do norte sob o comando de meu servo Nabucodonosor, rei da Babilônia. Eu os trarei contra esta terra e seus habitantes e contra as nações vizinhas. Destruirei vocês completamente e os transformarei para sempre em ruínas e em objeto de horror e desprezo.

[[v24-25-10]]

^<<v24-25-10,10>>^ Acabarei com seus cânticos alegres e seu riso, e não se ouvirão mais as vozes felizes de noivos e de noivas. As pedras de moinho se calarão, e as luzes das casas se apagarão.

[[v24-25-11]]

^<<v24-25-11,11>>^ Esta terra inteira se transformará em desolação e ruína. Israel e as nações vizinhas servirão ao rei da Babilônia durante setenta anos.

[[v24-25-12]]

^<<v24-25-12,12>>^ "Então, quando terminarem os setenta anos de exílio, castigarei o rei e o povo da Babilônia por seus pecados", diz o SENHOR. "Transformarei a terra dos babilônios em ruínas para sempre.

[[v24-25-13]]

^<<v24-25-13,13>>^ Trarei sobre eles todos os terrores que prometi neste livro, todos os castigos anunciados por Jeremias contra as nações.

[[v24-25-14]]

^<<v24-25-14,14>>^ Muitas nações e muitos grandes reis escravizarão os babilônios, assim como eles escravizaram meu povo. Eu os castigarei na mesma proporção do sofrimento que causaram com suas ações."

[[v24-25-15]]

^<<v24-25-15,15>>^ Assim me disse o SENHOR, o Deus de Israel: "Pegue da minha mão este cálice cheio do vinho de minha ira e faça que bebam dele todas as nações às quais eu o enviar.

[[v24-25-16]]

^<<v24-25-16,16>>^ Quando beberem, ficarão cambaleando, enlouquecidas por causa das guerras que enviarei contra elas".

[[v24-25-17]]

^<<v24-25-17,17>>^ Então peguei o cálice da ira do SENHOR e fiz todas as nações beberem dele, cada uma das nações às quais o SENHOR me enviou.

[[v24-25-18]]

^<<v24-25-18,18>>^ Fui a Jerusalém e às outras cidades de Judá, e seus reis e oficiais beberam do cálice. Hoje, não passam de ruína desolada, objeto de horror, desprezo e maldição.

[[v24-25-19]]

^<<v24-25-19,19>>^ Dei o cálice ao faraó, rei do Egito, a seus servos e oficiais e a todo o seu povo,

[[v24-25-20]]

^<<v24-25-20,20>>^ bem como aos estrangeiros que vivem naquela terra. Também o dei a todos os reis da terra de Uz e aos reis das cidades filisteias de Ascalom, Gaza, Ecrom, e ao que resta de Asdode.

[[v24-25-21]]

^<<v24-25-21,21>>^ Dei o cálice às nações de Edom, Moabe e Amom,

[[v24-25-22]]

^<<v24-25-22,22>>^ aos reis de Tiro e Sidom e aos reis das regiões além do mar.

[[v24-25-23]]

^<<v24-25-23,23>>^ Dei-o também a Dedã, Temá, Buz e àqueles que vivem em lugares distantes.

[[v24-25-24]]

^<<v24-25-24,24>>^ Dei-o aos reis da Arábia, aos reis das tribos nômades do deserto

[[v24-25-25]]

^<<v24-25-25,25>>^ e aos reis de Zinri, de Elão e da Média.

[[v24-25-26]]

^<<v24-25-26,26>>^ Dei-o ainda aos reis das terras do norte, próximas e distantes, uma após a outra, a todos os reinos do mundo. E, por fim, o próprio rei da Babilônia bebeu do cálice.

[[v24-25-27]]

^<<v24-25-27,27>>^ Então o SENHOR me disse: "Agora diga-lhes: ‘Assim diz o SENHOR dos Exércitos, o Deus de Israel: Bebam do cálice, fiquem embriagados e vomitem; caiam para nunca mais levantar, pois envio contra vocês guerras terríveis’.

[[v24-25-28]]

^<<v24-25-28,28>>^ E, se não quiserem aceitar o cálice, diga-lhes: ‘Assim diz o SENHOR dos Exércitos: Vocês serão obrigados a beber.

[[v24-25-29]]

^<<v24-25-29,29>>^ Comecei a castigar Jerusalém, a cidade que leva meu nome. Acaso deixarei que escapem do castigo? Não, vocês não escaparão. Trarei guerra contra todas as nações da terra. Eu, o SENHOR dos Exércitos, falei!’.

[[v24-25-30]]

^<<v24-25-30,30>>^ "Agora, profetize todas essas coisas e diga-lhes: "‘De sua santa habitação nos céus o SENHOR rugirá contra sua terra. Gritará como aqueles que pisam uvas, gritará contra todos os habitantes da terra.

[[v24-25-31]]

^<<v24-25-31,31>>^ O estrondo de sua voz chegará aos confins da terra, pois o SENHOR apresentará sua causa contra as nações. Julgará toda a humanidade e matará os perversos à espada. Eu, o SENHOR, falei!’".

[[v24-25-32]]

^<<v24-25-32,32>>^ Assim diz o SENHOR dos Exércitos: "Vejam, a calamidade virá sobre uma nação após a outra! Um grande vendaval está se formando nos confins da terra!".

[[v24-25-33]]

^<<v24-25-33,33>>^ Nesse dia, aqueles que o SENHOR tiver massacrado encherão a terra de uma extremidade à outra. Ninguém chorará por eles nem ajuntará seus corpos para enterrá-los. Ficarão espalhados pela terra como esterco.

[[v24-25-34]]

^<<v24-25-34,34>>^ Chorem e gemam, pastores perversos! Rolem no pó, líderes do rebanho! O dia de sua matança chegou; vocês cairão e se despedaçarão como um vaso frágil.

[[v24-25-35]]

^<<v24-25-35,35>>^ Não encontrarão lugar para se esconder, não terão como escapar.

[[v24-25-36]]

^<<v24-25-36,36>>^ Ouçam os gritos desesperados dos pastores, o lamento dos líderes do rebanho, pois o SENHOR está destruindo o pasto deles.

[[v24-25-37]]

^<<v24-25-37,37>>^ Campos tranquilos serão devastados pela ira ardente do SENHOR.

[[v24-25-38]]

^<<v24-25-38,38>>^ Como um leão forte à procura de alimento, ele saiu da toca; a terra dos pastores ficará em ruínas por causa da espada do inimigo e da ira ardente do SENHOR.

'''

xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[&#60; Capítulo Anterior] | <<v24-25-0,Topo>> | xref:024-jeremias/024-jeremias-026.adoc#v24-26-0[Próximo Capítulo &#62;]