include::./index.adoc[]

[[v24-16-0]]
=== Jeremias, 16
// nvt ?, NVT - Nova Versão Transformadora

[[v24-16-1]]

^<<v24-16-1,1>>^ Recebi outra mensagem do SENHOR. Ele disse:

[[v24-16-2]]

^<<v24-16-2,2>>^ "Não se case nem tenha filhos neste lugar.

[[v24-16-3]]

^<<v24-16-3,3>>^ Pois assim diz o SENHOR a respeito dos filhos e das filhas que nascerem nesta terra e a respeito de suas mães e seus pais:

[[v24-16-4]]

^<<v24-16-4,4>>^ Eles morrerão de doenças terríveis. Ninguém chorará por eles, nem os enterrará; ficarão espalhados pela terra como esterco. Morrerão por guerra e fome, e seus cadáveres servirão de alimento para os abutres e os animais selvagens".

[[v24-16-5]]

^<<v24-16-5,5>>^ Assim diz o SENHOR: "Não vá a funerais para prantear, nem demonstre compaixão por este povo, pois tirei dele minha proteção; removi minha bondade e minha misericórdia.

[[v24-16-6]]

^<<v24-16-6,6>>^ Tanto os mais importantes como os mais simples morrerão nesta terra. Ninguém os sepultará nem chorará por eles. Seus amigos não se cortarão nem rasparão a cabeça em sinal de tristeza.

[[v24-16-7]]

^<<v24-16-7,7>>^ Ninguém oferecerá uma refeição para consolar os que estiverem de luto, nem mesmo pela morte da mãe ou do pai. Ninguém lhe dará um cálice de vinho para consolá-los.

[[v24-16-8]]

^<<v24-16-8,8>>^ "Não vá a seus banquetes e a suas festas. Não coma nem beba com eles.

[[v24-16-9]]

^<<v24-16-9,9>>^ Pois assim diz o SENHOR dos Exércitos, o Deus de Israel: Durante sua vida, diante de seus olhos, acabarei com os cânticos alegres e com o riso nesta terra, e não se ouvirão mais as vozes felizes de noivos e de noivas.

[[v24-16-10]]

^<<v24-16-10,10>>^ "Quando você anunciar tudo isso ao povo, eles perguntarão: ‘Por que o SENHOR decretou coisas tão terríveis contra nós? O que fizemos para ser tratados desse modo? Qual foi nosso pecado contra o SENHOR, nosso Deus?’.

[[v24-16-11]]

^<<v24-16-11,11>>^ "Então você lhes responderá que assim diz o SENHOR: ‘Seus antepassados me deixaram. Adoraram e serviram outros deuses, me abandonaram e não obedeceram à minha lei.

[[v24-16-12]]

^<<v24-16-12,12>>^ E vocês são ainda piores que seus antepassados! Seguem os desejos teimosos de seu coração perverso e não querem me ouvir.

[[v24-16-13]]

^<<v24-16-13,13>>^ Por isso os expulsarei desta terra e os enviarei a uma terra estrangeira, onde vocês e seus antepassados nunca estiveram. Ali poderão adorar deuses dia e noite, e não lhes concederei nenhum favor’."

[[v24-16-14]]

^<<v24-16-14,14>>^ "Mas está chegando o dia", diz o SENHOR, "em que, ao fazer um juramento, ninguém mais dirá: ‘Tão certo como vive o SENHOR, que tirou o povo de Israel da terra do Egito’.

[[v24-16-15]]

^<<v24-16-15,15>>^ Em vez disso, dirá: ‘Tão certo como vive o SENHOR, que trouxe o povo de Israel de volta da terra do norte e de todas as nações onde os havia exilado’. Pois eu os trarei de volta à terra que dei a seus antepassados.

[[v24-16-16]]

^<<v24-16-16,16>>^ "Agora, porém, envio muitos pescadores que os pescarão", diz o SENHOR, "e envio caçadores que os caçarão nos montes, nas colinas e nas cavernas.

[[v24-16-17]]

^<<v24-16-17,17>>^ Eu os observo de perto e vejo cada pecado. É impossível se esconderem de mim.

[[v24-16-18]]

^<<v24-16-18,18>>^ Eu os castigarei em dobro por todos os seus pecados, pois contaminaram minha terra com as imagens sem vida de seus ídolos repulsivos e encheram minha terra com suas práticas detestáveis."

[[v24-16-19]]

^<<v24-16-19,19>>^ SENHOR, és minha força e fortaleza, meu refúgio no dia da angústia. Nações de todo o mundo virão a ti e dirão: "Nossos antepassados nos deixaram uma herança enganosa, pois adoraram ídolos inúteis.

[[v24-16-20]]

^<<v24-16-20,20>>^ Acaso alguém pode fazer seus próprios deuses? De maneira nenhuma são deuses verdadeiros!".

[[v24-16-21]]

^<<v24-16-21,21>>^ O SENHOR diz: "Agora lhes mostrarei meu poder, agora lhes mostrarei minha força. Finalmente entenderão e saberão que eu sou o SENHOR."

'''

xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[&#60; Capítulo Anterior] | <<v24-16-0,Topo>> | xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[Próximo Capítulo &#62;]