include::./index.adoc[]

[[v24-29-0]]
=== Jeremias, 29
// nvt ?, NVT - Nova Versão Transformadora

[[v24-29-1]]

^<<v24-29-1,1>>^ O profeta Jeremias escreveu uma carta e a enviou de Jerusalém aos líderes, sacerdotes, profetas e a todo o povo que o rei Nabucodonosor havia levado para a Babilônia.

[[v24-29-2]]

^<<v24-29-2,2>>^ Isso aconteceu depois que o rei Joaquim, a rainha-mãe, os oficiais do palácio e os outros oficiais de Judá, bem como todos os artífices e artesãos, foram deportados de Jerusalém.

[[v24-29-3]]

^<<v24-29-3,3>>^ Ele enviou a carta por meio de Elasa, filho de Safã, e de Gemarias, filho de Hilquias, quando eles foram à Babilônia como embaixadores de Zedequias a Nabucodonosor. A carta de Jeremias dizia:

[[v24-29-4]]

^<<v24-29-4,4>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel, a todos os exilados que ele deportou de Jerusalém para a Babilônia:

[[v24-29-5]]

^<<v24-29-5,5>>^ "Construam casas e estabeleçam-se nelas. Plantem pomares e comam os frutos que eles produzirem.

[[v24-29-6]]

^<<v24-29-6,6>>^ Casem-se e tenham filhos. Encontrem esposas para seus filhos e maridos para suas filhas, a fim de que vocês tenham muitos netos. Multipliquem-se! Não diminuam!

[[v24-29-7]]

^<<v24-29-7,7>>^ Trabalhem pela paz e pela prosperidade da cidade para a qual os deportei. Orem por ela ao SENHOR, pois a prosperidade de vocês depende da prosperidade dela".

[[v24-29-8]]

^<<v24-29-8,8>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel: "Não se deixem enganar pelos profetas e adivinhos que há no meio de vocês na terra da Babilônia. Não deem ouvidos aos sonhos deles, porque sonham o que vocês querem ouvir.

[[v24-29-9]]

^<<v24-29-9,9>>^ Eles contam mentiras em meu nome. Eu não os enviei", diz o SENHOR.

[[v24-29-10]]

^<<v24-29-10,10>>^ Assim diz o SENHOR: "Vocês ficarão na Babilônia durante setenta anos. Depois disso, eu virei e cumprirei todas as boas promessas que lhes fiz e os trarei de volta para casa.

[[v24-29-11]]

^<<v24-29-11,11>>^ Porque eu sei os planos que tenho para vocês", diz o SENHOR. "São planos de bem, e não de mal, para lhes dar o futuro pelo qual anseiam.

[[v24-29-12]]

^<<v24-29-12,12>>^ Naqueles dias, quando vocês clamarem por mim em oração, eu os ouvirei.

[[v24-29-13]]

^<<v24-29-13,13>>^ Se me buscarem de todo o coração, me encontrarão.

[[v24-29-14]]

^<<v24-29-14,14>>^ Serei encontrado por vocês", diz o SENHOR. "Acabarei com seu exílio e os restaurarei. Eu os reunirei de todas as nações para as quais os enviei e os trarei de volta para casa, para sua terra."

[[v24-29-15]]

^<<v24-29-15,15>>^ Vocês dizem que o SENHOR levantou profetas para vocês na Babilônia.

[[v24-29-16]]

^<<v24-29-16,16>>^ Mas assim diz o SENHOR acerca do rei sentado no trono de Davi e de todos que ainda moram aqui em Jerusalém, seus compatriotas que não foram enviados para o exílio na Babilônia.

[[v24-29-17]]

^<<v24-29-17,17>>^ Assim diz o SENHOR dos Exércitos: "Enviarei guerra, fome e doença sobre eles e farei que sejam como figos ruins, tão estragados que não servem para comer.

[[v24-29-18]]

^<<v24-29-18,18>>^ Sim, eu os perseguirei com guerra, fome e doença e os espalharei pelo mundo. Em todas as nações para onde eu os enviar, farei deles objeto de condenação, horror, desprezo e zombaria.

[[v24-29-19]]

^<<v24-29-19,19>>^ Pois não querem me ouvir, embora eu lhes tenha falado repetidamente por meio dos profetas que enviei. E vocês que estão no exílio também não deram ouvidos", diz o SENHOR.

[[v24-29-20]]

^<<v24-29-20,20>>^ Portanto, ouçam esta mensagem do SENHOR, todos vocês exilados na Babilônia.

[[v24-29-21]]

^<<v24-29-21,21>>^ Assim diz o SENHOR dos Exércitos, o Deus de Israel, acerca de seus profetas — Acabe, filho de Colaías, e Zedequias, filho de Maaseias — que contam mentiras em meu nome: "Eu os entregarei a Nabucodonosor, rei da Babilônia, para que sejam mortos diante de vocês.

[[v24-29-22]]

^<<v24-29-22,22>>^ O terrível destino deles se tornará notório; por isso, quando os exilados judeus quiserem amaldiçoar alguém, dirão: ‘Que o SENHOR faça com você o que fez com Zedequias e Acabe, que foram queimados vivos pelo rei da Babilônia!’.

[[v24-29-23]]

^<<v24-29-23,23>>^ Pois esses homens fizeram coisas horríveis entre meu povo: cometeram adultério com a esposa de seu próximo e mentiram em meu nome, dizendo coisas que eu não havia ordenado. E eu sou testemunha disso. Eu, o SENHOR, falei".

[[v24-29-24]]

^<<v24-29-24,24>>^ O SENHOR enviou esta mensagem a Semaías, o neelamita:

[[v24-29-25]]

^<<v24-29-25,25>>^ "Assim diz o SENHOR dos Exércitos, o Deus de Israel: Você escreveu uma carta em seu próprio nome para o sacerdote Sofonias, filho de Maaseias, e enviou cópias para outros sacerdotes e para o povo em Jerusalém. Você escreveu:

[[v24-29-26]]

^<<v24-29-26,26>>^ "O SENHOR o nomeou para substituir Joiada, o sacerdote encarregado do templo do SENHOR. É responsabilidade sua prender no tronco e colocar uma corrente de ferro no pescoço de qualquer louco que afirmar ser profeta.

[[v24-29-27]]

^<<v24-29-27,27>>^ Por que, então, não fez nada para deter Jeremias, de Anatote, que finge ser profeta entre vocês?

[[v24-29-28]]

^<<v24-29-28,28>>^ Jeremias enviou uma carta à Babilônia e previu que nosso exílio seria longo. Disse: ‘Construam casas e estabeleçam-se nelas. Plantem pomares e comam os frutos que eles produzirem’".

[[v24-29-29]]

^<<v24-29-29,29>>^ Quando o sacerdote Sofonias recebeu essa carta, leu-a para Jeremias.

[[v24-29-30]]

^<<v24-29-30,30>>^ Então o SENHOR deu esta mensagem a Jeremias:

[[v24-29-31]]

^<<v24-29-31,31>>^ "Envie uma carta aberta a todos os exilados na Babilônia. Diga-lhes: ‘Assim diz o SENHOR acerca de Semaías, o neelamita: Porque ele profetizou a vocês sem que eu o tivesse enviado e os fez acreditar em suas mentiras,

[[v24-29-32]]

^<<v24-29-32,32>>^ castigarei a ele e a sua família. Nenhum de seus descendentes verá as coisas boas que farei por meu povo, pois ele os incitou a se rebelarem contra mim. Eu, o SENHOR, falei!’".

'''

xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[&#60; Capítulo Anterior] | <<v24-29-0,Topo>> | xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[Próximo Capítulo &#62;]