include::./index.adoc[]

[[v24-13-0]]
=== Jeremias, 13
// nvt ?, NVT - Nova Versão Transformadora

[[v24-13-1]]

^<<v24-13-1,1>>^ O SENHOR me disse: "Vá, compre um cinto de linho e vista-o, mas não o lave".

[[v24-13-2]]

^<<v24-13-2,2>>^ Comprei o cinto de linho, como o SENHOR me havia instruído, e o vesti.

[[v24-13-3]]

^<<v24-13-3,3>>^ Então recebi outra mensagem do SENHOR:

[[v24-13-4]]

^<<v24-13-4,4>>^ "Pegue o cinto de linho que está vestindo e vá ao rio Eufrates. Esconda-o ali, num buraco entre as pedras".

[[v24-13-5]]

^<<v24-13-5,5>>^ Fui e o escondi junto ao Eufrates, como o SENHOR me havia ordenado.

[[v24-13-6]]

^<<v24-13-6,6>>^ Depois de muito tempo, o SENHOR me disse: "Volte ao rio Eufrates e pegue o cinto que eu lhe disse que escondesse ali".

[[v24-13-7]]

^<<v24-13-7,7>>^ Fui ao Eufrates, cavei onde havia escondido o cinto e o tirei dali. Mas o cinto tinha apodrecido e não servia para nada.

[[v24-13-8]]

^<<v24-13-8,8>>^ Então recebi esta mensagem do SENHOR:

[[v24-13-9]]

^<<v24-13-9,9>>^ "Assim diz o SENHOR: Do mesmo modo farei apodrecer o orgulho de Judá e de Jerusalém.

[[v24-13-10]]

^<<v24-13-10,10>>^ Este povo perverso não quer me ouvir. Seguem os desejos teimosos de seu coração e adoram outros deuses. Portanto, eles se tornarão semelhantes a esse cinto: não servirão para nada!

[[v24-13-11]]

^<<v24-13-11,11>>^ Assim como o cinto se apega à cintura do homem, eu criei Judá e Israel para se apegarem a mim, diz o SENHOR. Deveriam ser meu povo, meu louvor e minha glória, uma honra para meu nome. Mas não quiseram me ouvir.

[[v24-13-12]]

^<<v24-13-12,12>>^ "Portanto, diga-lhes: ‘Assim diz o SENHOR, o Deus de Israel: Que todas as suas vasilhas fiquem cheias de vinho’. E eles responderão: ‘Claro! As vasilhas são feitas para ficar cheias de vinho’.

[[v24-13-13]]

^<<v24-13-13,13>>^ "Então diga-lhes: ‘Assim diz o SENHOR: Deixarei todos nesta terra completamente embriagados, desde o rei sentado no trono de Davi até os sacerdotes e os profetas, e todos os habitantes de Jerusalém.

[[v24-13-14]]

^<<v24-13-14,14>>^ Eu os despedaçarei, colocando uns contra os outros, até mesmo pais contra filhos, diz o SENHOR. Não deixarei que minha piedade, nem minha misericórdia, nem minha compaixão me impeçam de destruí-los’".

[[v24-13-15]]

^<<v24-13-15,15>>^ Ouçam e prestem atenção; não sejam arrogantes, pois o SENHOR falou.

[[v24-13-16]]

^<<v24-13-16,16>>^ Deem glória ao SENHOR, seu Deus, antes que as trevas venham sobre vocês, antes que ele os faça tropeçar e cair nos montes sombrios. Então, quando procurarem luz, só encontrarão escuridão densa e terrível.

[[v24-13-17]]

^<<v24-13-17,17>>^ E, se ainda assim não quiserem ouvir, chorarei sozinho por causa de seu orgulho. Lágrimas amargas se derramarão de meus olhos, pois o rebanho do SENHOR será levado para o exílio.

[[v24-13-18]]

^<<v24-13-18,18>>^ Diga ao rei e à mãe dele: "Desçam de seus tronos e sentem-se no pó, pois sua coroa gloriosa será arrancada de sua cabeça".

[[v24-13-19]]

^<<v24-13-19,19>>^ As cidades do Neguebe fecharão os portões, e ninguém conseguirá abri-los. Os habitantes de Judá serão levados como prisioneiros; todos irão para o exílio.

[[v24-13-20]]

^<<v24-13-20,20>>^ Abra os olhos e veja os exércitos que vêm do norte! Onde está seu rebanho, o lindo rebanho de que ele a encarregou de cuidar?

[[v24-13-21]]

^<<v24-13-21,21>>^ O que dirá quando o SENHOR colocar seus antigos aliados para a dominarem? Pontadas de angústia tomarão conta de você, como as dores da mulher em trabalho de parto.

[[v24-13-22]]

^<<v24-13-22,22>>^ Você se perguntará: "Por que isso me aconteceu?". Foi por causa de seus muitos pecados! Por isso os exércitos invasores arrancaram suas roupas e a violentaram.

[[v24-13-23]]

^<<v24-13-23,23>>^ Acaso o etíope pode mudar a cor de sua pele? Pode o leopardo tirar suas manchas? De igual modo, você é incapaz de fazer o bem, pois se acostumou a fazer o mal.

[[v24-13-24]]

^<<v24-13-24,24>>^ "Eu a dispersarei como palha levada pelos ventos do deserto.

[[v24-13-25]]

^<<v24-13-25,25>>^ Esta é sua parte, a porção que lhe reservei", diz o SENHOR, "pois você se esqueceu de mim e confiou em falsos deuses.

[[v24-13-26]]

^<<v24-13-26,26>>^ Eu mesmo arrancarei suas roupas, para que apareça sua vergonha.

[[v24-13-27]]

^<<v24-13-27,27>>^ Vi seu adultério e sua lascívia, sua idolatria detestável nos campos e sobre as colinas. Que aflição a espera, Jerusalém! Quando você se purificará?"

'''

xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[&#60; Capítulo Anterior] | <<v24-13-0,Topo>> | xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[Próximo Capítulo &#62;]