include::./index.adoc[]

[[v24-26-0]]
=== Jeremias, 26
// nvt ?, NVT - Nova Versão Transformadora

[[v24-26-1]]

^<<v24-26-1,1>>^ Jeremias recebeu esta mensagem do SENHOR no início do reinado de Jeoaquim, filho de Josias, rei de Judá:

[[v24-26-2]]

^<<v24-26-2,2>>^ "Assim diz o SENHOR: Vá ao pátio do templo do SENHOR e fale aos habitantes das cidades de Judá que vieram adorar no templo. Transmita-lhes minha mensagem completa, sem que falte uma só palavra.

[[v24-26-3]]

^<<v24-26-3,3>>^ Talvez eles escutem e abandonem seus maus caminhos. Então voltarei atrás e não enviarei a calamidade que estou prestes a derramar sobre eles por causa de seus pecados.

[[v24-26-4]]

^<<v24-26-4,4>>^ "Diga-lhes: ‘Assim diz o SENHOR: Se vocês não me derem ouvidos e não obedecerem à minha lei, que lhes dei,

[[v24-26-5]]

^<<v24-26-5,5>>^ e se não derem ouvidos a meus servos, os profetas — pois eu os enviei repetidamente para adverti-los, mas vocês não quiseram ouvir —,

[[v24-26-6]]

^<<v24-26-6,6>>^ então destruirei o templo, como destruí Siló, o lugar onde ficava o tabernáculo. Farei de Jerusalém objeto de maldição entre todas as nações da terra’".

[[v24-26-7]]

^<<v24-26-7,7>>^ Os sacerdotes, os profetas e todo o povo ouviram Jeremias falar na frente do templo do SENHOR.

[[v24-26-8]]

^<<v24-26-8,8>>^ Quando Jeremias terminou sua mensagem e disse tudo que o SENHOR lhe havia ordenado, os sacerdotes, os profetas e todo o povo o atacaram e gritaram: "Vamos matá-lo!

[[v24-26-9]]

^<<v24-26-9,9>>^ Que direito você tem de profetizar, em nome do SENHOR, que este templo será destruído como Siló? Que história é essa de que Jerusalém será destruída e ficará desabitada?". E todo o povo o ameaçava em frente ao templo do SENHOR.

[[v24-26-10]]

^<<v24-26-10,10>>^ Quando os oficiais de Judá ouviram o que estava acontecendo, correram do palácio até o templo e sentaram-se para julgar à entrada da porta Nova do templo do SENHOR.

[[v24-26-11]]

^<<v24-26-11,11>>^ Os sacerdotes e os profetas apresentaram suas acusações aos oficiais e ao povo. "Este homem deve ser condenado à morte", disseram. "Vocês ouviram com os próprios ouvidos que ele profetizou contra esta cidade!"

[[v24-26-12]]

^<<v24-26-12,12>>^ Então Jeremias disse aos oficiais e ao povo: "O SENHOR me enviou para profetizar contra este templo e esta cidade. O SENHOR me deu cada palavra que lhes falei.

[[v24-26-13]]

^<<v24-26-13,13>>^ Se, contudo, vocês deixarem de pecar e começarem a obedecer ao SENHOR, seu Deus, ele voltará atrás e não enviará a calamidade que anunciou contra vocês.

[[v24-26-14]]

^<<v24-26-14,14>>^ Quanto a mim, estou em suas mãos. Façam comigo o que lhes parecer melhor.

[[v24-26-15]]

^<<v24-26-15,15>>^ Se me matarem, porém, saibam que derramarão sangue inocente. Vocês, esta cidade e cada um de seus habitantes serão responsabilizados por isso. Pois é verdade que o SENHOR me enviou para dizer cada palavra que ouviram".

[[v24-26-16]]

^<<v24-26-16,16>>^ Então os oficiais e o povo disseram aos sacerdotes e aos profetas: "Este homem não merece a sentença de morte, pois nos falou em nome do SENHOR, nosso Deus".

[[v24-26-17]]

^<<v24-26-17,17>>^ Então alguns dos anciãos do povo se levantaram e falaram a todos que estavam reunidos ali.

[[v24-26-18]]

^<<v24-26-18,18>>^ Disseram: "Lembrem-se de quando Miqueias, de Moresete, profetizou durante o reinado de Ezequias, rei de Judá. Ele disse ao povo de Judá: ‘Assim diz o SENHOR dos Exércitos: O monte Sião será lavrado como um campo aberto; Jerusalém será transformada em ruínas. Mato cobrirá o monte onde hoje está o templo’.

[[v24-26-19]]

^<<v24-26-19,19>>^ Acaso o rei Ezequias e o povo o mataram porque ele disse isso? Não, mas temeram o SENHOR e lhe suplicaram por misericórdia. Então o SENHOR voltou atrás e não enviou a calamidade que havia pronunciado contra eles. Estamos prestes a fazer grande mal a nós mesmos".

[[v24-26-20]]

^<<v24-26-20,20>>^ Urias, filho de Semaías, de Quiriate-Jearim, também profetizava nessa época em nome do SENHOR. E, como Jeremias, previu a mesma calamidade sobre a cidade e a nação.

[[v24-26-21]]

^<<v24-26-21,21>>^ Quando o rei Jeoaquim, os comandantes do exército e os oficiais ouviram o que Urias disse, o rei planejou matá-lo. Urias, porém, soube do plano e, com medo, fugiu para o Egito.

[[v24-26-22]]

^<<v24-26-22,22>>^ Então o rei Jeoaquim enviou Elnatã, filho de Acbor, e outros homens ao Egito para capturar Urias.

[[v24-26-23]]

^<<v24-26-23,23>>^ Eles o prenderam e o levaram de volta ao rei Jeoaquim. O rei matou Urias com uma espada e mandou sepultá-lo numa vala comum.

[[v24-26-24]]

^<<v24-26-24,24>>^ Apesar disso, Aicam, filho de Safã, protegeu Jeremias e convenceu o tribunal a não o entregar à multidão para ser morto.

'''

xref:024-jeremias/024-jeremias-025.adoc#v24-25-0[&#60; Capítulo Anterior] | <<v24-26-0,Topo>> | xref:024-jeremias/024-jeremias-027.adoc#v24-27-0[Próximo Capítulo &#62;]