include::./index.adoc[]

[[v24-32-0]]
=== Jeremias, 32
// nvt ?, NVT - Nova Versão Transformadora

[[v24-32-1]]

^<<v24-32-1,1>>^ Jeremias recebeu esta mensagem do SENHOR no décimo ano do reinado de Zedequias, rei de Judá. Esse também foi o décimo oitavo ano do reinado de Nabucodonosor.

[[v24-32-2]]

^<<v24-32-2,2>>^ Nessa ocasião, o exército babilônio cercava Jerusalém, e Jeremias estava preso no pátio da guarda, no palácio real.

[[v24-32-3]]

^<<v24-32-3,3>>^ Zedequias, rei de Judá, o havia colocado ali e perguntado por que ele continuava a anunciar esta profecia: "Assim diz o SENHOR: ‘Estou prestes a entregar esta cidade ao rei da Babilônia, e ele a conquistará.

[[v24-32-4]]

^<<v24-32-4,4>>^ O rei Zedequias será capturado pelos babilônios e levado para falar face a face com o rei da Babilônia.

[[v24-32-5]]

^<<v24-32-5,5>>^ O rei levará Zedequias para a Babilônia, onde lidarei com ele’, diz o SENHOR. ‘Vocês não serão bem-sucedidos se lutarem contra os babilônios’".

[[v24-32-6]]

^<<v24-32-6,6>>^ Nesse tempo, o SENHOR me enviou uma mensagem:

[[v24-32-7]]

^<<v24-32-7,7>>^ "Seu primo Hanameel, filho de Salum, virá e lhe dirá: ‘Compre meu campo em Anatote. Pela lei, você tem direito de comprá-lo antes que eu o ofereça a outro’".

[[v24-32-8]]

^<<v24-32-8,8>>^ Exatamente como o SENHOR tinha dito, meu primo Hanameel veio me visitar na prisão e disse: "Compre meu campo em Anatote, na terra de Benjamim. Pela lei, você tem direito de comprá-lo antes que eu o ofereça a outro. Portanto, compre-o para si". Então entendi que a mensagem que eu tinha ouvido era do SENHOR.

[[v24-32-9]]

^<<v24-32-9,9>>^ Assim, comprei o campo em Anatote e paguei a Hanameel dezessete peças de prata.

[[v24-32-10]]

^<<v24-32-10,10>>^ Assinei e selei a escritura diante de testemunhas, pesei a prata e lhe paguei.

[[v24-32-11]]

^<<v24-32-11,11>>^ Em seguida, peguei a escritura selada e uma cópia não selada com os termos e as condições da compra

[[v24-32-12]]

^<<v24-32-12,12>>^ e as entreguei a Baruque, filho de Nerias, neto de Maaseias. Fiz tudo isso na presença de meu primo Hanameel, das testemunhas que assinaram a escritura e dos homens de Judá que estavam no pátio da guarda.

[[v24-32-13]]

^<<v24-32-13,13>>^ Então, na presença deles, disse a Baruque:

[[v24-32-14]]

^<<v24-32-14,14>>^ "Assim diz o SENHOR dos Exércitos, o Deus de Israel: ‘Pegue a escritura selada e a cópia não selada e coloque-as num vaso de barro, a fim de conservá-las por muito tempo’.

[[v24-32-15]]

^<<v24-32-15,15>>^ Pois assim diz o SENHOR dos Exércitos, o Deus de Israel: ‘Algum dia, as pessoas voltarão a ter propriedades nesta terra e comprarão e venderão casas, vinhedos e campos’".

[[v24-32-16]]

^<<v24-32-16,16>>^ Depois que entreguei os documentos a Baruque, filho de Nerias, orei ao SENHOR:

[[v24-32-17]]

^<<v24-32-17,17>>^ "Ó Soberano SENHOR! Tu fizeste os céus e a terra com tua mão forte e teu braço poderoso. Nada é difícil demais para ti!

[[v24-32-18]]

^<<v24-32-18,18>>^ Mostras tua bondade a milhares de pessoas, mas também permites que as consequências do pecado de uma geração recaiam sobre a geração seguinte. Tu és Deus grande e poderoso, o SENHOR dos Exércitos.

[[v24-32-19]]

^<<v24-32-19,19>>^ Tens toda sabedoria e fazes grandes milagres. Vês a conduta de todos e lhes dás o que merecem.

[[v24-32-20]]

^<<v24-32-20,20>>^ Realizaste sinais e maravilhas na terra do Egito, feitos lembrados ainda hoje. E continuas a fazer grandes milagres em Israel e em todo o mundo. Por isso o teu nome é famoso até hoje.

[[v24-32-21]]

^<<v24-32-21,21>>^ "Tiraste Israel do Egito com sinais e maravilhas, com mão forte e braço poderoso e com grande terror.

[[v24-32-22]]

^<<v24-32-22,22>>^ Deste ao povo de Israel esta terra que havias prometido a seus antepassados muito tempo atrás, terra que produz leite e mel com fartura.

[[v24-32-23]]

^<<v24-32-23,23>>^ Nossos antepassados vieram e tomaram posse da terra, mas não quiseram te obedecer nem seguir tuas instruções. Não fizeram nada do que lhes ordenaste. Por isso enviaste sobre eles esta terrível calamidade.

[[v24-32-24]]

^<<v24-32-24,24>>^ "Vê como foram construídas rampas junto aos muros da cidade! Por meio de guerra, fome e doença, a cidade será entregue aos babilônios, que a conquistarão. Tudo aconteceu exatamente como anunciaste.

[[v24-32-25]]

^<<v24-32-25,25>>^ E, no entanto, ó Soberano SENHOR, ordenaste que eu comprasse o campo e pagasse um bom preço por ele diante destas testemunhas, embora a cidade esteja prestes a ser entregue aos babilônios".

[[v24-32-26]]

^<<v24-32-26,26>>^ Então Jeremias recebeu esta mensagem do SENHOR:

[[v24-32-27]]

^<<v24-32-27,27>>^ "Eu sou o SENHOR, o Deus de toda a humanidade. Acaso alguma coisa é difícil demais para mim?

[[v24-32-28]]

^<<v24-32-28,28>>^ Portanto, assim diz o SENHOR: Entregarei esta cidade aos babilônios e a Nabucodonosor, rei da Babilônia, e ele a conquistará.

[[v24-32-29]]

^<<v24-32-29,29>>^ Os babilônios que estão cercando os muros entrarão na cidade e a incendiarão. Queimarão todas as casas em que o povo provocou minha ira queimando incenso a Baal em seus terraços e apresentando ofertas derramadas a outros deuses.

[[v24-32-30]]

^<<v24-32-30,30>>^ Desde o princípio, Israel e Judá fizeram somente o mal. Provocaram minha ira com suas maldades", diz o SENHOR.

[[v24-32-31]]

^<<v24-32-31,31>>^ "Desde o dia em que esta cidade foi construída até hoje, não fez outra coisa senão despertar minha fúria, por isso estou decidido a me livrar dela.

[[v24-32-32]]

^<<v24-32-32,32>>^ "Os pecados de Israel e de Judá — os pecados do povo de Jerusalém, dos reis, dos oficiais, dos sacerdotes e dos profetas — provocaram minha ira.

[[v24-32-33]]

^<<v24-32-33,33>>^ Meu povo deu as costas para mim e se recusou a voltar. Embora eu os tenha ensinado repetidamente, não quiseram receber instrução nem obedecer.

[[v24-32-34]]

^<<v24-32-34,34>>^ Colocaram seus ídolos detestáveis em meu templo e o profanaram.

[[v24-32-35]]

^<<v24-32-35,35>>^ Construíram lugares de adoração a Baal no vale de Ben-Hinom e ali sacrificaram seus filhos e filhas a Moloque. Jamais ordenei tamanha maldade; nunca me passou pela mente! Esse terrível mal fez Israel pecar."

[[v24-32-36]]

^<<v24-32-36,36>>^ "Agora, quero dizer algo mais a respeito desta cidade. Vocês afirmam: ‘Ela será entregue ao rei da Babilônia por meio de guerra, fome e doença’. Mas assim diz o SENHOR, o Deus de Israel:

[[v24-32-37]]

^<<v24-32-37,37>>^ Certamente trarei meu povo de volta de todas as nações entre as quais o espalhei em minha fúria. Eu os trarei de volta para este lugar e farei que vivam em segurança.

[[v24-32-38]]

^<<v24-32-38,38>>^ Eles serão o meu povo, e eu serei o seu Deus.

[[v24-32-39]]

^<<v24-32-39,39>>^ Eu lhes darei um só coração e um só propósito: adorar-me para sempre, para o seu próprio bem e para o bem de seus descendentes.

[[v24-32-40]]

^<<v24-32-40,40>>^ Estabelecerei com eles uma aliança permanente: jamais deixarei de lhes fazer o bem. Porei em seu coração o desejo de me adorar, e eles nunca se afastarão de mim.

[[v24-32-41]]

^<<v24-32-41,41>>^ Terei alegria em lhes fazer o bem e os plantarei nesta terra firmemente, de todo o coração.

[[v24-32-42]]

^<<v24-32-42,42>>^ "Assim diz o SENHOR: Assim como trouxe todas essas calamidades sobre eles, também lhes farei todo o bem que prometi.

[[v24-32-43]]

^<<v24-32-43,43>>^ Campos voltarão a ser comprados e vendidos nesta terra sobre a qual hoje vocês dizem: ‘Foi arrasada pelos babilônios, é uma terra desolada, em que não há mais pessoas nem animais’.

[[v24-32-44]]

^<<v24-32-44,44>>^ Sim, campos voltarão a ser comprados e vendidos e escrituras serão assinadas na terra de Benjamim, aqui em Jerusalém, nas cidades de Judá, na região montanhosa, nas colinas de Judá e no Neguebe. Pois, um dia, eu os restaurarei à sua terra. Eu, o SENHOR, falei!"

'''

xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[Próximo Capítulo &#62;]