include::./index.adoc[]

[[v24-40-0]]
=== Jeremias, 40
// nvt ?, NVT - Nova Versão Transformadora

[[v24-40-1]]

^<<v24-40-1,1>>^ O SENHOR deu uma mensagem a Jeremias depois que Nebuzaradã, capitão da guarda, o pôs em liberdade em Ramá. Ele havia encontrado Jeremias acorrentado entre todos os prisioneiros de Jerusalém e Judá que estavam sendo levados para o exílio na Babilônia.

[[v24-40-2]]

^<<v24-40-2,2>>^ O capitão da guarda mandou chamar Jeremias e disse: "O SENHOR, seu Deus, trouxe esta calamidade sobre esta terra.

[[v24-40-3]]

^<<v24-40-3,3>>^ O SENHOR cumpriu o que tinha dito, pois esse povo pecou contra o SENHOR e lhe desobedeceu. Por isso aconteceram todas essas coisas.

[[v24-40-4]]

^<<v24-40-4,4>>^ Mas eu vou tirar suas correntes e libertá-lo. Se quiser ir comigo para a Babilônia, está bem. Providenciarei que cuidem de você. Se não quiser ir, fique aqui. Toda a terra está diante de você; vá para onde quiser.

[[v24-40-5]]

^<<v24-40-5,5>>^ Se resolver ficar, volte para Gedalias, filho de Aicam e neto de Safã. O rei da Babilônia o nomeou governador de Judá. Fique com o povo que ele governa. E, se quiser ir para algum outro lugar, faça o que lhe parecer melhor". Então Nebuzaradã, capitão da guarda, deu a Jeremias um pouco de alimento e dinheiro e o deixou partir.

[[v24-40-6]]

^<<v24-40-6,6>>^ Jeremias voltou para Gedalias, filho de Aicam, em Mispá, e habitou em Judá com os poucos que haviam ficado na terra.

[[v24-40-7]]

^<<v24-40-7,7>>^ Os comandantes dos grupos de soldados que estavam no interior de Judá souberam que o rei da Babilônia havia nomeado Gedalias, filho de Aicam, para governar o povo pobre que tinha ficado em Judá, isto é, os homens, as mulheres e as crianças que não haviam sido enviados para o exílio na Babilônia.

[[v24-40-8]]

^<<v24-40-8,8>>^ Então foram ver Gedalias em Mispá. Entre eles estavam Ismael, filho de Netanias, Joanã e Jônatas, filhos de Careá, Seraías, filho de Tanumete, os filhos de Efai, o netofatita, Jazanias, filho do maacatita, e todos os seus homens.

[[v24-40-9]]

^<<v24-40-9,9>>^ Gedalias jurou a eles que os babilônios não tinham intenção de lhes fazer mal. "Não tenham medo de servi-los. Vivam na terra e sirvam ao rei da Babilônia, e tudo lhes irá bem", ele prometeu.

[[v24-40-10]]

^<<v24-40-10,10>>^ "Quanto a mim, ficarei em Mispá e os representarei diante dos babilônios que vierem se encontrar conosco. Estabeleçam-se nas cidades que tomaram e vivam dos frutos da terra. Colham uvas, frutas de verão e azeitonas e armazenem tudo."

[[v24-40-11]]

^<<v24-40-11,11>>^ Quando os judeus em Moabe, Amom, Edom e outras terras vizinhas souberam que o rei da Babilônia tinha deixado um remanescente do povo em Judá e que Gedalias era o governador,

[[v24-40-12]]

^<<v24-40-12,12>>^ começaram a voltar para Judá dos lugares para os quais haviam fugido. Pararam em Mispá, onde se encontraram com Gedalias. Depois, seguiram para os campos em Judá e tiveram uma farta colheita de uvas e frutas de verão.

[[v24-40-13]]

^<<v24-40-13,13>>^ Algum tempo depois, Joanã, filho de Careá, e os outros comandantes dos soldados que estavam no interior foram até Gedalias, em Mispá,

[[v24-40-14]]

^<<v24-40-14,14>>^ e lhe disseram: "Você sabia que Baalis, rei de Amom, enviou Ismael, filho de Netanias, para assassiná-lo?". Gedalias, porém, não acreditou neles.

[[v24-40-15]]

^<<v24-40-15,15>>^ Mais tarde, Joanã falou com Gedalias em particular e se ofereceu para matar Ismael em segredo. "Por que deixar que ele venha e mate você?", Joanã perguntou. "O que será, então, dos judeus que voltaram? Se isso acontecer, os poucos que restaram ficarão espalhados e perdidos."

[[v24-40-16]]

^<<v24-40-16,16>>^ Gedalias, porém, disse a Joanã: "Eu o proíbo de fazer isso, pois você está mentindo a respeito de Ismael".

'''

xref:024-jeremias/024-jeremias-039.adoc#v24-39-0[&#60; Capítulo Anterior] | <<v24-40-0,Topo>> | xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[Próximo Capítulo &#62;]