include::./index.adoc[]

[[v24-52-0]]
=== Jeremias, 52
// nvt ?, NVT - Nova Versão Transformadora

[[v24-52-1]]

^<<v24-52-1,1>>^ Zedequias tinha 21 anos quando começou a reinar, e reinou em Jerusalém por onze anos. Sua mãe se chamava Hamutal e era filha de Jeremias, de Libna.

[[v24-52-2]]

^<<v24-52-2,2>>^ Fez o que era mau aos olhos do SENHOR, como Jeoaquim antes dele.

[[v24-52-3]]

^<<v24-52-3,3>>^ Estas coisas aconteceram por causa da ira do SENHOR contra o povo de Jerusalém e de Judá. Por fim, ele os expulsou de sua presença. Zedequias se rebelou contra o rei da Babilônia.

[[v24-52-4]]

^<<v24-52-4,4>>^ Assim, em 15 de janeiro, durante o nono ano de reinado de Zedequias, Nabucodonosor, rei de Babilônia, e todo o seu exército cercaram Jerusalém e construíram rampas de ataque contra os muros.

[[v24-52-5]]

^<<v24-52-5,5>>^ Jerusalém permaneceu cercada até o décimo primeiro ano do reinado de Zedequias.

[[v24-52-6]]

^<<v24-52-6,6>>^ Em 18 de julho, no décimo primeiro ano do reinado de Zedequias, a fome na cidade tinha se tornado tão severa que não havia mais nenhum alimento.

[[v24-52-7]]

^<<v24-52-7,7>>^ Assim, abriram uma brecha no muro da cidade, e todos os soldados fugiram. Como a cidade estava cercada pelos babilônios, os soldados esperaram até o anoitecer. Então, passaram pelo portão entre os dois muros atrás do jardim do rei e fugiram em direção ao vale do Jordão.

[[v24-52-8]]

^<<v24-52-8,8>>^ Contudo, o exército babilônio perseguiu o rei Zedequias e o alcançou nas planícies de Jericó, pois todos os seus soldados o haviam abandonado e se dispersado.

[[v24-52-9]]

^<<v24-52-9,9>>^ Capturaram Zedequias e o levaram ao rei da Babilônia, em Ribla, na terra de Hamate. Ali o rei da Babilônia sentenciou Zedequias.

[[v24-52-10]]

^<<v24-52-10,10>>^ Obrigou Zedequias a vê-lo matar seus filhos e todos os oficiais de Judá.

[[v24-52-11]]

^<<v24-52-11,11>>^ Depois, arrancou seus olhos, o prendeu com correntes de bronze e o levou para a Babilônia. Zedequias permaneceu preso até o dia de sua morte.

[[v24-52-12]]

^<<v24-52-12,12>>^ Em 17 de agosto daquele ano, o décimo nono ano do reinado de Nabucodonosor, Nebuzaradã, capitão da guarda e oficial do rei babilônio, chegou a Jerusalém.

[[v24-52-13]]

^<<v24-52-13,13>>^ Queimou o templo do SENHOR, o palácio real e todas as casas de Jerusalém. Queimou também todos os edifícios importantes da cidade.

[[v24-52-14]]

^<<v24-52-14,14>>^ Depois, supervisionou o exército babilônio na demolição de todos os muros de Jerusalém.

[[v24-52-15]]

^<<v24-52-15,15>>^ Em seguida, Nebuzaradã, capitão da guarda, deportou alguns dos mais pobres, o povo que havia ficado na cidade, os desertores de Judá que se entregaram ao rei da Babilônia e o restante dos artesãos.

[[v24-52-16]]

^<<v24-52-16,16>>^ Permitiu, no entanto, que alguns dos mais pobres ficassem para cuidar dos vinhedos e dos campos.

[[v24-52-17]]

^<<v24-52-17,17>>^ Os babilônios despedaçaram as colunas de bronze na frente do templo do SENHOR, as bases móveis de bronze e o grande tanque de bronze chamado Mar, e levaram todo o bronze para a Babilônia.

[[v24-52-18]]

^<<v24-52-18,18>>^ Também levaram os baldes para cinzas, as pás, os cortadores de pavios, as bacias, as vasilhas e todos os outros utensílios de bronze usados para o serviço no templo.

[[v24-52-19]]

^<<v24-52-19,19>>^ O capitão da guarda também levou os baldes pequenos, os incensários, as bacias, as panelas, os candeeiros, as colheres, as vasilhas usadas para as ofertas derramadas e todos os outros utensílios de ouro puro ou de prata.

[[v24-52-20]]

^<<v24-52-20,20>>^ Era impossível calcular o peso do bronze das duas colunas, do Mar com os doze touros de bronze debaixo dele e das bases móveis. Esses objetos tinham sido feitos para o templo do SENHOR por ordem do rei Salomão.

[[v24-52-21]]

^<<v24-52-21,21>>^ Cada coluna media 8,3 metros de altura e tinha 5,5 metros de circunferência. Era oca, e suas paredes tinham cerca de 8 centímetros de espessura.

[[v24-52-22]]

^<<v24-52-22,22>>^ O capitel de bronze no alto de cada coluna media cerca de 2,25 metros de altura e era enfeitado ao redor com correntes entrelaçadas de romãs feitas de bronze.

[[v24-52-23]]

^<<v24-52-23,23>>^ Havia 96 romãs nos lados, e nas correntes entrelaçadas ao redor do topo havia, ao todo, cem romãs.

[[v24-52-24]]

^<<v24-52-24,24>>^ Nebuzaradã, capitão da guarda, levou como prisioneiros o sumo sacerdote Seraías, o sacerdote auxiliar Sofonias e três dos principais guardas das portas.

[[v24-52-25]]

^<<v24-52-25,25>>^ Dentre o povo que ainda estava escondido na cidade, levou um oficial responsável pelo exército, sete dos conselheiros pessoais do rei, o secretário do comandante do exército, que era encarregado do alistamento, e outros sessenta homens do povo.

[[v24-52-26]]

^<<v24-52-26,26>>^ Nebuzaradã, capitão da guarda, levou-os ao rei da Babilônia, em Ribla.

[[v24-52-27]]

^<<v24-52-27,27>>^ E ali em Ribla, na terra de Hamate, o rei da Babilônia mandou executá-los. Assim, o povo de Judá foi enviado para o exílio, para longe de sua terra.

[[v24-52-28]]

^<<v24-52-28,28>>^ No sétimo ano do reinado de Nabucodonosor, 3.023 judeus foram levados para o exílio na Babilônia.

[[v24-52-29]]

^<<v24-52-29,29>>^ No décimo oitavo ano de Nabucodonosor, mais 832 pessoas foram exiladas de Jerusalém.

[[v24-52-30]]

^<<v24-52-30,30>>^ No vigésimo terceiro ano de Nabucodonosor, ele enviou Nebuzaradã, capitão da guarda, que levou mais 745 judeus. Ao todo, 4.600 pessoas foram exiladas.

[[v24-52-31]]

^<<v24-52-31,31>>^ No trigésimo sétimo ano do exílio de Joaquim, rei de Judá, Evil-Merodaque começou a reinar na Babilônia. Foi bondoso com Joaquim e o libertou da prisão em 31 de março daquele ano.

[[v24-52-32]]

^<<v24-52-32,32>>^ Falou com ele gentilmente e o colocou num lugar mais elevado que o de outros reis exilados na Babilônia.

[[v24-52-33]]

^<<v24-52-33,33>>^ Providenciou-lhe roupas novas, em lugar das roupas de prisioneiro, e permitiu que ele comesse na presença do rei enquanto vivesse.

[[v24-52-34]]

^<<v24-52-34,34>>^ Joaquim recebeu do rei da Babilônia uma provisão diária de alimento enquanto viveu, até o dia de sua morte.

'''

xref:024-jeremias/024-jeremias-051.adoc#v24-51-0[&#60; Capítulo Anterior] | <<v24-52-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[Próximo Capítulo &#62;]