include::./index.adoc[]

[[v24-11-0]]
=== Jeremias, 11
// nvt ?, NVT - Nova Versão Transformadora

[[v24-11-1]]

^<<v24-11-1,1>>^ O SENHOR deu outra mensagem a Jeremias:

[[v24-11-2]]

^<<v24-11-2,2>>^ "Lembre os habitantes de Judá e de Jerusalém dos termos de minha aliança com eles.

[[v24-11-3]]

^<<v24-11-3,3>>^ Diga-lhes: ‘Assim diz o SENHOR, o Deus de Israel: Maldito será aquele que não obedecer aos termos de minha aliança!

[[v24-11-4]]

^<<v24-11-4,4>>^ Pois eu disse a seus antepassados quando os tirei do Egito, uma fornalha de fundir ferro: ‘Se vocês me obedecerem e fizerem tudo que ordeno, serão o meu povo, e eu serei o seu Deus’.

[[v24-11-5]]

^<<v24-11-5,5>>^ Disse isso para cumprir a promessa que fiz a seus antepassados de lhes dar uma terra que produzisse leite e mel com fartura, a terra em que hoje vocês habitam’". Então eu respondi: "Que assim seja, SENHOR!".

[[v24-11-6]]

^<<v24-11-6,6>>^ E o SENHOR disse: "Proclame esta mensagem nas cidades de Judá e nas ruas de Jerusalém. Diga: ‘Lembrem-se da antiga aliança e de todas as suas exigências.

[[v24-11-7]]

^<<v24-11-7,7>>^ Pois adverti solenemente seus antepassados quando os tirei do Egito: ‘Obedeçam-me!’. Repeti essa advertência inúmeras vezes até hoje,

[[v24-11-8]]

^<<v24-11-8,8>>^ mas seus antepassados não me deram ouvidos nem prestaram atenção. Pelo contrário, seguiram os desejos teimosos de seu coração perverso. E, porque se recusaram a obedecer, eu trouxe sobre eles todas as maldições descritas nesta aliança’".

[[v24-11-9]]

^<<v24-11-9,9>>^ O SENHOR falou comigo novamente e disse: "Descobri uma conspiração contra mim entre os habitantes de Judá e de Jerusalém.

[[v24-11-10]]

^<<v24-11-10,10>>^ Voltaram aos pecados de seus antepassados. Não quiseram me ouvir e adoraram outros deuses. Israel e Judá quebraram a aliança que fiz com seus antepassados.

[[v24-11-11]]

^<<v24-11-11,11>>^ Por isso, assim diz o SENHOR: Trarei calamidade sobre eles, e não escaparão. Ainda que me supliquem, não ouvirei seu clamor.

[[v24-11-12]]

^<<v24-11-12,12>>^ Os habitantes de Judá e de Jerusalém clamarão a seus ídolos e queimarão incenso para eles, mas os ídolos não os salvarão quando vier a calamidade.

[[v24-11-13]]

^<<v24-11-13,13>>^ Vejam, habitantes de Judá, seus deuses são tão numerosos quanto suas cidades! Seus altares vergonhosos, altares para queimar incenso a Baal, são tão numerosos quanto as ruas de Jerusalém!

[[v24-11-14]]

^<<v24-11-14,14>>^ "Portanto, Jeremias, não ore mais por este povo. Não chore por eles, pois não os ouvirei quando clamarem a mim em sua aflição.

[[v24-11-15]]

^<<v24-11-15,15>>^ "Que direito tem meu povo amado de vir ao meu templo depois de ter cometido tanta imoralidade? Acaso seus votos e sacrifícios poderão evitar sua destruição? A verdade é que se alegram em praticar o mal.

[[v24-11-16]]

^<<v24-11-16,16>>^ Eu, o SENHOR, os chamava de oliveira verdejante, bonita de ver e cheia de bons frutos. Agora, porém, enviei a fúria de seus inimigos para incendiar e destruir seus ramos.

[[v24-11-17]]

^<<v24-11-17,17>>^ "Eu, o SENHOR dos Exércitos, que plantei essa oliveira, ordenei que fosse destruída. Pois o povo de Israel e o povo de Judá fizeram o mal e provocaram minha ira ao queimar incenso a Baal".

[[v24-11-18]]

^<<v24-11-18,18>>^ Então o SENHOR me falou das conspirações que meus inimigos tramavam contra mim.

[[v24-11-19]]

^<<v24-11-19,19>>^ Eu era como cordeiro levado para o matadouro. Não fazia ideia de que planejavam me matar. "Vamos destruir esse homem e suas palavras!", diziam. "Vamos derrubá-lo para que seu nome seja esquecido para sempre!"

[[v24-11-20]]

^<<v24-11-20,20>>^ Ó SENHOR dos Exércitos, tu julgas com justiça e examinas pensamentos e emoções. Permite que eu veja tua vingança contra eles, pois coloquei minha causa em tuas mãos.

[[v24-11-21]]

^<<v24-11-21,21>>^ Assim diz o SENHOR a respeito dos homens de Anatote que queriam me ver morto. Eles tinham dito: "Nós o mataremos se não parar de profetizar em nome do SENHOR".

[[v24-11-22]]

^<<v24-11-22,22>>^ Portanto, assim diz o SENHOR dos Exércitos a respeito deles: "Eu os castigarei! Seus jovens morrerão na batalha, e seus filhos e filhas morrerão de fome.

[[v24-11-23]]

^<<v24-11-23,23>>^ Nenhum dos conspiradores de Anatote sobreviverá, pois eu trarei calamidade sobre eles quando chegar a hora de seu castigo".

'''

xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[&#60; Capítulo Anterior] | <<v24-11-0,Topo>> | xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[Próximo Capítulo &#62;]