include::./index.adoc[]

[[v24-3-0]]
=== Jeremias, 3
// nvt ?, NVT - Nova Versão Transformadora

[[v24-3-1]]

^<<v24-3-1,1>>^ "Se um homem se divorciar da esposa e ela se casar com outro homem, ele não a receberá de volta, pois isso contaminaria a terra. Você, porém, se prostituiu com muitos amantes e, no entanto, quer voltar para mim?", diz o SENHOR.

[[v24-3-2]]

^<<v24-3-2,2>>^ "Olhe para o alto dos montes: existe um só lugar em que você não tenha se contaminado pelo adultério com outros deuses? Senta-se à beira do caminho, como uma prostituta à espera de um cliente, sozinha, como um nômade no deserto. Contaminou a terra com sua prostituição e sua perversidade.

[[v24-3-3]]

^<<v24-3-3,3>>^ Por isso não vieram as chuvas de primavera, pois você é uma prostituta descarada, que não tem vergonha alguma.

[[v24-3-4]]

^<<v24-3-4,4>>^ Ainda assim, você me diz: ‘Pai, tens me conduzido desde minha juventude.

[[v24-3-5]]

^<<v24-3-5,5>>^ Certamente não ficarás irado para sempre! Certamente te esquecerás do que aconteceu!’. Você fala desse modo, mas continua a praticar todo o mal possível."

[[v24-3-6]]

^<<v24-3-6,6>>^ Durante o reinado de Josias, o SENHOR me disse: "Viu o que fez a infiel nação de Israel? Como esposa que comete adultério, Israel adorou outros deuses no alto dos montes e debaixo de toda árvore verdejante.

[[v24-3-7]]

^<<v24-3-7,7>>^ Pensei: ‘Depois de fazer tudo isso, ela voltará para mim’, mas não voltou, e Judá, sua irmã traiçoeira, viu isso.

[[v24-3-8]]

^<<v24-3-8,8>>^ Ela viu que me divorciei da infiel Israel por causa de seu adultério. Mas Judá, irmã traiçoeira, não teve temor algum; também me deixou e se entregou à prostituição.

[[v24-3-9]]

^<<v24-3-9,9>>^ Israel não se preocupou nem um pouco em cometer adultério ao adorar ídolos feitos de madeira e pedra. Agora, a terra está contaminada.

[[v24-3-10]]

^<<v24-3-10,10>>^ Apesar de tudo isso, Judá, sua irmã traiçoeira, não voltou para mim com sinceridade. Apenas fingiu estar arrependida. Eu, o SENHOR, falei!".

[[v24-3-11]]

^<<v24-3-11,11>>^ Então o SENHOR me disse: "Até mesmo a infiel Israel é menos culpada que a traiçoeira Judá!

[[v24-3-12]]

^<<v24-3-12,12>>^ Portanto, vá e proclame esta mensagem a Israel. Assim diz o SENHOR: "Ó Israel, meu povo infiel, volte para mim, pois sou misericordioso; não ficarei irado com você para sempre.

[[v24-3-13]]

^<<v24-3-13,13>>^ Reconheça sua culpa; admita que se rebelou contra o SENHOR, seu Deus, e cometeu adultério contra ele ao adorar ídolos debaixo de toda árvore verdejante. Confesse que não quis ouvir minha voz. Eu, o SENHOR falei!".

[[v24-3-14]]

^<<v24-3-14,14>>^ O SENHOR diz: "Voltem para casa, filhos rebeldes, pois eu sou seu mestre. Eu os trarei de volta a Sião — um desta cidade, dois daquela família — de onde quer que estejam dispersos.

[[v24-3-15]]

^<<v24-3-15,15>>^ Eu lhes darei líderes segundo meu coração, que os guiarão com conhecimento e entendimento.

[[v24-3-16]]

^<<v24-3-16,16>>^ "E, quando sua terra voltar a ficar cheia de gente", diz o SENHOR, "vocês não terão mais saudades da época em que tinham a arca da aliança do SENHOR. Não sentirão falta da arca nem se lembrarão dela, e não será necessário reconstruí-la.

[[v24-3-17]]

^<<v24-3-17,17>>^ Então Jerusalém será conhecida como ‘O Trono do SENHOR’. Todas as nações irão até lá para honrar o SENHOR. Não seguirão mais os desejos teimosos de seu coração perverso.

[[v24-3-18]]

^<<v24-3-18,18>>^ Naqueles dias, o povo de Judá e o povo de Israel voltarão juntos do exílio no norte, para a terra que dei a seus antepassados como herança para sempre.

[[v24-3-19]]

^<<v24-3-19,19>>^ "Disse comigo: Como eu gostaria de tratá-los como filhos! Meu maior desejo era lhes dar esta linda terra, a herança mais excelente do mundo. Queria que me chamassem de ‘Pai’ e que jamais se afastassem de mim.

[[v24-3-20]]

^<<v24-3-20,20>>^ Mas você me traiu, povo de Israel! Foi como esposa infiel que abandona o marido. Eu, o SENHOR, falei."

[[v24-3-21]]

^<<v24-3-21,21>>^ Ouvem-se vozes no alto dos montes, choro e súplicas dos israelitas, porque escolheram caminhos tortuosos e se esqueceram do SENHOR, seu Deus.

[[v24-3-22]]

^<<v24-3-22,22>>^ "Meus filhos rebeldes", diz o SENHOR, "voltem para mim, e eu curarei a rebeldia de seu coração." "Sim, nós voltaremos", o povo responde, "pois tu és o SENHOR, nosso Deus.

[[v24-3-23]]

^<<v24-3-23,23>>^ Nossa idolatria nas colinas e as orgias religiosas nos montes não passam de ilusão. Somente no SENHOR, nosso Deus, Israel encontrará salvação.

[[v24-3-24]]

^<<v24-3-24,24>>^ Desde a juventude observamos nossos antepassados desperdiçarem com algo vergonhoso tudo que trabalharam para ter: rebanhos e gado, filhos e filhas.

[[v24-3-25]]

^<<v24-3-25,25>>^ Que a vergonha nos sirva de cama, e a desonra, de cobertor, pois nós e nossos antepassados pecamos contra o SENHOR, nosso Deus. Desde a juventude até hoje, nunca lhe obedecemos."

'''

xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[Próximo Capítulo &#62;]